### ISSUE TITLE
MacOS 10.13.6 Anaconda3 5.2.0 installation error 

### ISSUE THREAD

**Issue by Jiawei-Navican** [ContinuumIO/anaconda-issues#10006]
### Actual Behavior

This afternoon, I am facing some issue with create a new conda environment. So I decide to uninstall and reinstall the anaconda. While after I remove the anaconda folder and try to reinstall it. I faced some issues with both the GUI installer and script installer. I even tried anaconda3 4.4.0 and miniconda. All face the same problem of time out error from .install.py script.

Please see the output log from /var/log/install.log . It's the same error when I use a script installer.

##### Anaconda or Miniconda version:
Anaconda3-5.2.0-macOS
##### Operating System:
MacOS High Sierra 10.13.6 
##### `/var/log/install.log`
```
2018-08-31 20:57:00-06 users-MacBook-Pro installd[848]: PackageKit: Executing script "./preinstall" in /private/tmp/PKInstallSandbox.kWElaO/Scripts/io.continuum.pkg.apreinstall.TISuwT
2018-08-31 20:57:00-06 users-MacBook-Pro installd[848]: PackageKit: Using trashcan path /var/folders/26/27p55dd5427bv0lf2kw6vls00000gq/T/PKInstallSandboxTrash/DA0666FB-341E-48EF-8CF6-11C20E315061.sandboxTrash for sandbox /var/folders/26/27p55dd5427bv0lf2kw6vls00000gq/C/PKInstallSandboxManager/DA0666FB-341E-48EF-8CF6-11C20E315061.activeSandbox
2018-08-31 20:57:00-06 users-MacBook-Pro installd[848]: PackageKit: Shoving /var/folders/26/27p55dd5427bv0lf2kw6vls00000gq/C/PKInstallSandboxManager/DA0666FB-341E-48EF-8CF6-11C20E315061.activeSandbox/Root (1 items) to /Users/user
2018-08-31 20:57:00-06 users-MacBook-Pro installd[848]: PackageKit: Executing script "./postinstall" in /private/tmp/PKInstallSandbox.kWElaO/Scripts/io.continuum.pkg.postextract.C8QEOz
2018-08-31 20:57:00-06 users-MacBook-Pro installd[848]: ./postinstall: PREFIX=/Users/user/anaconda3
2018-08-31 20:57:00-06 users-MacBook-Pro installd[848]: ./postinstall: Python 3.6.5 :: Anaconda, Inc.
2018-08-31 20:59:02-06 users-MacBook-Pro installd[848]: ./postinstall: Traceback (most recent call last):
2018-08-31 20:59:02-06 users-MacBook-Pro installd[848]: ./postinstall:   File "/Users/user/anaconda3/pkgs/.install.py", line 1869, in <module>
2018-08-31 20:59:02-06 users-MacBook-Pro installd[848]: ./postinstall:     main()
2018-08-31 20:59:02-06 users-MacBook-Pro installd[848]: ./postinstall:   File "/Users/user/anaconda3/pkgs/.install.py", line 1804, in main
2018-08-31 20:59:02-06 users-MacBook-Pro installd[848]: ./postinstall:     link_idists()
2018-08-31 20:59:02-06 users-MacBook-Pro installd[848]: ./postinstall:   File "/Users/user/anaconda3/pkgs/.install.py", line 1722, in link_idists
2018-08-31 20:59:02-06 users-MacBook-Pro installd[848]: ./postinstall:     link_dist(dist, linktype)
2018-08-31 20:59:02-06 users-MacBook-Pro installd[848]: ./postinstall:   File "/Users/user/anaconda3/pkgs/.install.py", line 1708, in link_dist
2018-08-31 20:59:02-06 users-MacBook-Pro installd[848]: ./postinstall:     link(prefix, dist, linktype)
2018-08-31 20:59:02-06 users-MacBook-Pro installd[848]: ./postinstall:   File "/Users/user/anaconda3/pkgs/.install.py", line 1609, in link
2018-08-31 20:59:02-06 users-MacBook-Pro installd[848]: ./postinstall:     update_prefix(join(prefix, f), prefix, placeholder, mode)
2018-08-31 20:59:02-06 users-MacBook-Pro installd[848]: ./postinstall:   File "/Users/user/anaconda3/pkgs/.install.py", line 1461, in update_prefix
2018-08-31 20:59:02-06 users-MacBook-Pro installd[848]: ./postinstall:     exp_backoff_fn(os.unlink, path)
2018-08-31 20:59:02-06 users-MacBook-Pro installd[848]: ./postinstall:   File "/Users/user/anaconda3/pkgs/.install.py", line 1392, in exp_backoff_fn
2018-08-31 20:59:02-06 users-MacBook-Pro installd[848]: ./postinstall:     return fn(*args)
2018-08-31 20:59:02-06 users-MacBook-Pro installd[848]: ./postinstall: TimeoutError: [Errno 60] Operation timed out: '/Users/user/anaconda3/lib/python3.6/lib-dynload/_codecs_hk.cpython-36m-darwin.so'
2018-08-31 20:59:02-06 users-MacBook-Pro installd[848]: PackageKit: releasing backupd
2018-08-31 20:59:02-06 users-MacBook-Pro installd[848]: PackageKit: allow user idle system sleep
2018-08-31 20:59:02-06 users-MacBook-Pro installd[848]: PackageKit: Install Failed: Error Domain=PKInstallErrorDomain Code=112 "An error occurred while running scripts from the package “Anaconda3-5.2.0-MacOSX-x86_64.pkg”." UserInfo={NSFilePath=./postinstall, NSURL=file://localhost/Users/user/Desktop/Anaconda3-5.2.0-MacOSX-x86_64.pkg#postextract.pkg, PKInstallPackageIdentifier=io.continuum.pkg.postextract, NSLocalizedDescription=An error occurred while running scripts from the package “Anaconda3-5.2.0-MacOSX-x86_64.pkg”.} {
            NSFilePath = "./postinstall";
            NSLocalizedDescription = "An error occurred while running scripts from the package \U201cAnaconda3-5.2.0-MacOSX-x86_64.pkg\U201d.";
            NSURL = "file://localhost/Users/user/Desktop/Anaconda3-5.2.0-MacOSX-x86_64.pkg#postextract.pkg";
            PKInstallPackageIdentifier = "io.continuum.pkg.postextract";
        }
2018-08-31 20:59:02-06 users-MacBook-Pro Installer[1079]: install:didFailWithError:Error Domain=PKInstallErrorDomain Code=112 "An error occurred while running scripts from the package “Anaconda3-5.2.0-MacOSX-x86_64.pkg”." UserInfo={NSFilePath=./postinstall, NSURL=file://localhost/Users/user/Desktop/Anaconda3-5.2.0-MacOSX-x86_64.pkg#postextract.pkg, PKInstallPackageIdentifier=io.continuum.pkg.postextract, NSLocalizedDescription=An error occurred while running scripts from the package “Anaconda3-5.2.0-MacOSX-x86_64.pkg”.}
```

**Comment by Jiawei-Navican** [comment]
It's caused by Symantec endpoint protection cloud application blocking feature.
