### ISSUE TITLE
Anaconda Navigator not opening

### ISSUE THREAD

**Issue by Kelvinli5354** [ContinuumIO/anaconda-issues#10043]
### Actual Behavior

nothing happens

### Expected Behavior

I expect the anaconda navigator to open

### Steps to Reproduce

I just did `conda update -all` and after it finished, anaconda navigator refused to open.

when i type `anaconda-navigator` into the command prompt, I get this:
```
C:\Users\kelvi>anaconda-navigator
Traceback (most recent call last):
  File "C:\Users\kelvi\Anaconda3\lib\site-packages\qtpy\__init__.py", line 199, in <module>
    from PySide import __version__ as PYSIDE_VERSION  # analysis:ignore
ModuleNotFoundError: No module named 'PySide'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\kelvi\Anaconda3\Scripts\anaconda-navigator-script.py", line 6, in <module>
    from anaconda_navigator.app.main import main
  File "C:\Users\kelvi\Anaconda3\lib\site-packages\anaconda_navigator\app\main.py", line 22, in <module>
    from anaconda_navigator.utils.conda import is_conda_available
  File "C:\Users\kelvi\Anaconda3\lib\site-packages\anaconda_navigator\utils\__init__.py", line 15, in <module>
    from qtpy.QtGui import QIcon
  File "C:\Users\kelvi\Anaconda3\lib\site-packages\qtpy\__init__.py", line 205, in <module>
    raise PythonQtError('No Qt bindings could be found')
qtpy.PythonQtError: No Qt bindings could be found
```

##### `conda info`

```
     active environment : None
       user config file : C:\Users\kelvi\.condarc
 populated config files : C:\Users\kelvi\.condarc
          conda version : 4.5.11
    conda-build version : 3.14.2
         python version : 3.6.3.final.0
       base environment : C:\Users\kelvi\Anaconda3  (writable)
           channel URLs : https://conda.anaconda.org/intel/win-64
                          https://conda.anaconda.org/intel/noarch
                          https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/win-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/win-64
                          https://repo.anaconda.com/pkgs/pro/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\Users\kelvi\Anaconda3\pkgs
                          C:\Users\kelvi\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\kelvi\Anaconda3\envs
                          C:\Users\kelvi\AppData\Local\conda\conda\envs
                          C:\Users\kelvi\.conda\envs
               platform : win-64
             user-agent : conda/4.5.11 requests/2.18.4 CPython/3.6.3 Windows/10 Windows/10.0.17134
          administrator : False
             netrc file : None
           offline mode : False
```

##### `conda list --show-channel-urls`

```
# packages in environment at C:\Users\kelvi\Anaconda3:
#
# Name                    Version                   Build  Channel
_r-mutex                  1.0.0                     mro_2
absl-py                   0.3.0                     <pip>
alabaster                 0.7.11                   py36_0
anaconda                  custom           py36h363777c_0
anaconda-client           1.7.2                    py36_0    anaconda
anaconda-navigator        1.8.7                    py36_0    anaconda
appdirs                   1.4.3            py36h28b3542_0
asn1crypto                0.24.0             py36_intel_1  [intel]  intel
astor                     0.7.1                     <pip>
astroid                   2.0.4                    py36_0
astropy                   3.0.4            py36hfa6e2cd_0
atomicwrites              1.2.1                    py36_0
attrs                     18.2.0           py36h28b3542_0
automat                   0.7.0                    py36_0
babel                     2.6.0                    py36_0
backcall                  0.1.0              py36_intel_0  [intel]  intel
backports                 1.0                py36_intel_6  [intel]  intel
backports.shutil_get_terminal_size 1.0.0                    py36_2
beautifulsoup4            4.6.3                    py36_0
bitarray                  0.8.3            py36hfa6e2cd_0
bkcharts                  0.2              py36h7e685f7_0
blas                      1.0                         mkl
blaze                     0.11.3                   py36_0
bleach                    2.1.3              py36_intel_0  [intel]  intel
bokeh                     0.13.0                   py36_0
boto                      2.49.0                   py36_0
bottleneck                1.2.1            py36h452e1ab_1
bzip2                     1.0.6             vc14_intel_14  [intel vc14]  intel
ca-certificates           2018.03.07                    0    anaconda
cachecontrol              0.12.5                   py36_0
certifi                   2018.1.18          py36_intel_0  [intel]  intel
cffi                      1.11.5             py36_intel_1  [intel]  intel
chardet                   3.0.4              py36_intel_1  [intel]  intel
click                     6.7              py36hec8c647_0
cloudpickle               0.5.5                    py36_0
clyent                    1.2.2                    py36_1
colorama                  0.3.9              py36_intel_0  [intel]  intel
comtypes                  1.1.7                    py36_0
conda                     4.5.11                   py36_0    anaconda
conda-build               3.14.2                   py36_0
conda-env                 2.6.0                         1
conda-verify              3.1.0                    py36_0
console_shortcut          0.1.1                         3
constantly                15.1.0           py36h28b3542_0
contextlib2               0.5.5            py36he5d52c0_0
cryptography              2.2.2              py36_intel_1  [intel]  intel
curl                      7.61.0               h7602738_0
cycler                    0.10.0             py36_intel_5  [intel]  intel
cymem                     1.31.2              py36_vc14_0  [vc14]  conda-forge
cython                    0.28.2             py36_intel_4  [intel]  intel
cytoolz                   0.9.0.1          py36hfa6e2cd_1
daal                      2018.0.3.20180405               0    intel
dask                      0.19.1                   py36_0
dask-core                 0.19.1                   py36_0
datashape                 0.5.4                    py36_1
decorator                 4.3.0              py36_intel_0  [intel]  intel
dill                      0.2.8.2                  py36_0
distlib                   0.2.7                    py36_0
distributed               1.23.1                   py36_0
Django                    2.0.7                     <pip>
docutils                  0.14             py36h6012d8f_0
en-core-web-sm            2.0.0                     <pip>
entrypoints               0.2.3              py36_intel_0  [intel]  intel
et_xmlfile                1.0.1            py36h3d2d736_0
fastcache                 1.0.2            py36hfa6e2cd_2
filelock                  3.0.6                    py36_0
flake8                    3.5.0                     <pip>
flask                     0.12.2           py36h98b5e8f_0
flask-cors                3.0.6                    py36_0
font-ttf-dejavu-sans-mono 2.37                 h6964260_0
font-ttf-inconsolata      2.001                hcb22688_0
font-ttf-source-code-pro  2.030                h7457263_0
font-ttf-ubuntu           0.83                 h8b1ccd4_0
fonts-anaconda            1                    h8fa9717_0
freetype                  2.8                vc14_intel_0  [intel vc14]  intel
future                    0.16.0                    <pip>
future                    0.16.0                   py36_2
gast                      0.2.0                     <pip>
gender-guesser            0.4.0                     <pip>
get_terminal_size         1.0.0              py36_intel_5  [intel]  intel
gevent                    1.3.6            py36hfa6e2cd_0
glob2                     0.6                      py36_0
google-images-download    2.3.0                     <pip>
greenlet                  0.4.14           py36hfa6e2cd_0
grpcio                    1.13.0                    <pip>
gym                       0.10.5                    <pip>
h5py                      2.7.1            py36he54a1c3_0
hdf5                      1.10.1             vc14_intel_1  [intel vc14]  intel
heapdict                  1.0.0                    py36_2
html5lib                  1.0.1              py36_intel_1  [intel]  intel
hyperlink                 18.0.0                   py36_0
icc_rt                    2018.0.3                intel_0  [intel]  intel
icu                       58.2                     vc14_0  [vc14]  conda-forge
idna                      2.6                py36_intel_0  [intel]  intel
imageio                   2.3.0                    py36_0
imagesize                 1.1.0                    py36_0
imutils                   0.4.6                     <pip>
incremental               17.5.0                   py36_0
intel-openmp              2018.0.3                      0
intelpython               2018.0.3                      0    intel
ipykernel                 4.6.1              py36_intel_0  [intel]  intel
ipython                   6.3.1              py36_intel_1  [intel]  intel
ipython_genutils          0.2.0              py36_intel_0  [intel]  intel
isort                     4.3.4                    py36_0
itsdangerous              0.24                     py36_1
jdcal                     1.4                      py36_0
jedi                      0.12.0             py36_intel_0  [intel]  intel
jinja2                    2.9.6              py36_intel_0  [intel]  intel
jpeg                      9b                       vc14_2  [vc14]  conda-forge
jsonschema                2.6.0              py36_intel_1  [intel]  intel
jupyter_client            5.1.0              py36_intel_1  [intel]  intel
jupyter_core              4.4.0              py36_intel_1  [intel]  intel
Keras                     2.2.2                     <pip>
Keras-Applications        1.0.4                     <pip>
Keras-Preprocessing       1.0.2                     <pip>
lazy-object-proxy         1.3.1            py36hfa6e2cd_2
libcurl                   7.61.0               h7602738_0
libiconv                  1.15                 h1df5818_7
libpng                    1.6.34             vc14_intel_1  [intel vc14]  intel
libsodium                 1.0.16                   vc14_0  [vc14]  conda-forge
libssh2                   1.8.0                hd619d38_4
libtiff                   4.0.9                    vc14_0  [vc14]  conda-forge
libxml2                   2.9.8                hadb2253_1
libxslt                   1.1.32                   vc14_0  [vc14]  conda-forge
llvm-meta                 6.0.0                         0    conda-forge
llvmlite                  0.20.0             py36_intel_0  [intel]  intel
locket                    0.2.0            py36hfed976d_1
lockfile                  0.12.2           py36h0468280_0
lxml                      4.2.4            py36hef2cd61_0
lzo                       2.10                     vc14_0  [vc14]  conda-forge
m2-bash                   4.3.042                       5
m2-gcc-libs               5.3.0                         4
m2-heimdal                1.5.3                        10
m2-heimdal-libs           1.5.3                        10
m2-icu                    56.1                          2
m2-libcrypt               1.3                           2
m2-libdb                  5.3.28                        3
m2-libedit                3.1                    20150326
m2-libopenssl             1.0.2.g                       2
m2-libreadline            6.3.008                       8
m2-libsqlite              3.10.0.0                      2
m2-msys2-runtime          2.5.0.17080.65c939c               3
m2-ncurses                6.0.20160220                  2
m2-openssh                7.1p2                         2
m2-openssl                1.0.2.g                       2
m2-zlib                   1.2.8                         4
m2w64-bzip2               1.0.6                         6
m2w64-ca-certificates     20150426                    103
m2w64-diffutils           3.3.2                         2
m2w64-expat               2.1.1                         2
m2w64-gcc-libgfortran     5.3.0                         6
m2w64-gcc-libs            5.3.0                         7
m2w64-gcc-libs-core       5.3.0                         7
m2w64-gettext             0.19.7                        2
m2w64-gmp                 6.1.0                         2
m2w64-grep                2.24                          2
m2w64-libffi              3.2.1                         4
m2w64-libiconv            1.14                          6
m2w64-libtasn1            4.7                           2
m2w64-libwinpthread-git   5.0.0.4634.697f757               2
m2w64-openssl             1.0.2.g                       2
m2w64-p11-kit             0.23.2                        2
m2w64-pcre                8.38                          2
m2w64-wineditline         2.101                         5
m2w64-zlib                1.2.8                        10
Markdown                  2.6.11                    <pip>
markupsafe                1.0                py36_intel_0  [intel]  intel
matplotlib                2.1.1           np114py36_intel_2  [intel]  intel
mccabe                    0.6.1                    py36_1
menuinst                  1.4.14           py36hfa6e2cd_0
mistune                   0.7.4              py36_intel_1  [intel]  intel
mkl                       2018.0.3                intel_1    intel
mkl-service               1.1.2            py36hb217b18_4
mkl_fft                   1.0.2           np114py36_intel_0  [intel]  intel
mkl_random                1.0.1           np114py36_intel_0  [intel]  intel
more-itertools            4.3.0                    py36_0
mpmath                    1.0.0              py36_intel_0  [intel]  intel
mro-base                  3.4.3                         0
mro-basics                3.4.3                         0
msgpack-numpy             0.4.3.1                  py36_0
msgpack-python            0.5.6            py36he980bc4_2    conda-forge
msys2-conda-epoch         20160418                      1
multipledispatch          0.6.0                    py36_0
murmurhash                0.28.0              py36_vc14_0  [vc14]  conda-forge
names                     0.3.0                     <pip>
navigator-updater         0.2.1                    py36_0
nbconvert                 5.2.1              py36_intel_1  [intel]  intel
nbformat                  4.4.0              py36_intel_1  [intel]  intel
networkx                  2.1                      py36_0
nltk                      3.3.0                    py36_0    anaconda
nose                      1.3.7             py36_intel_17  [intel]  intel
notebook                  5.2.2              py36_intel_0  [intel]  intel
numba                     0.35.0             py36_intel_0  [intel]  intel
numexpr                   2.6.4           np114py36_intel_0  [intel]  intel
numpy                     1.14.3             py36_intel_0  [intel]  intel
numpydoc                  0.8.0                    py36_0
odo                       0.5.1            py36h7560279_0
olefile                   0.45.1                   py36_0
opencv-python             3.4.2.17                  <pip>
openmp                    2018.0.3                intel_0    intel
openpyxl                  2.5.6                    py36_0
openssl                   1.0.2o             vc14_intel_0  [intel vc14]  intel
packaging                 17.1                     py36_0
pandas                    0.22.0          np114py36_intel_4  [intel]  intel
pandoc                    2.2.3.2                       0
pandocfilters             1.4.1              py36_intel_0  [intel]  intel
parso                     0.2.0              py36_intel_0  [intel]  intel
partd                     0.3.8            py36hc8e763b_0
path.py                   11.0.1             py36_intel_0  [intel]  intel
pathlib2                  2.3.2                    py36_0
patsy                     0.5.0                    py36_0
pep8                      1.7.1                    py36_0
pickleshare               0.7.4              py36_intel_1  [intel]  intel
pillow                    4.2.1            py36hdb25ab2_0
pip                       9.0.1              py36_intel_1  [intel]  intel
pip                       18.0                      <pip>
pipenv                    2018.6.25                 <pip>
pkginfo                   1.4.2                    py36_1
plac                      0.9.6                      py_1    conda-forge
pluggy                    0.7.1            py36h28b3542_0
ply                       3.11                     py36_0
preshed                   1.0.1            py36he025d50_0
progress                  1.4                      py36_0
prometheus_client         0.3.1            py36h28b3542_0
prompt_toolkit            1.0.15             py36_intel_0  [intel]  intel
protobuf                  3.6.0                     <pip>
psutil                    5.4.7            py36hfa6e2cd_0
py                        1.6.0                    py36_0
pyasn1                    0.4.4            py36h28b3542_0
pyasn1-modules            0.2.2                    py36_0
pycodestyle               2.4.0                    py36_0
pycosat                   0.6.3            py36hfa6e2cd_0
pycparser                 2.18               py36_intel_0  [intel]  intel
pycrypto                  2.6.1            py36hfa6e2cd_9
pycurl                    7.43.0.2         py36h74b6da3_0
pydaal                    2018.0.3.20180405 np114py36_intel_1  [intel]  intel
pyflakes                  2.0.0                    py36_0
pyglet                    1.3.2                     <pip>
pygments                  2.2.0              py36_intel_2  [intel]  intel
pylint                    2.1.1                    py36_0
pyodbc                    4.0.24           py36h6538335_0
pyopenssl                 17.5.0             py36_intel_0  [intel]  intel
pyparsing                 2.2.0              py36_intel_0  [intel]  intel
pyqt                      5.9.2            py36ha878b3d_0
PyQt5                     5.11.2                    <pip>
PyQt5_sip                 4.19.12                   <pip>
pyreadline                2.1                      py36_1
pysocks                   1.6.7              py36_intel_0  [intel]  intel
pytables                  3.4.2           np114py36_intel_4  [intel]  intel
pytest                    3.7.4                    py36_0
pytest-arraydiff          0.2              py36h39e3cac_0
pytest-astropy            0.4.0                    py36_0
pytest-doctestplus        0.1.3                    py36_0
pytest-openfiles          0.3.0                    py36_0
pytest-remotedata         0.3.0                    py36_0
python                    3.6.3                  intel_12  [intel]  intel
python-dateutil           2.6.0              py36_intel_3  [intel]  intel
pytz                      2018.4             py36_intel_0  [intel]  intel
pywavelets                1.0.0            py36h452e1ab_0
pywin32                   223              py36hfa6e2cd_1
pywinpty                  0.5.4                    py36_0
pyyaml                    3.12               py36_intel_4  [intel]  intel
pyzmq                     16.0.2             py36_intel_4  [intel]  intel
qt                        5.9.6            vc14h62aca36_0
qtawesome                 0.4.4            py36h5aa48f6_0
qtpy                      1.5.0                    py36_0
r                         3.4.3                  mro343_0
r-assertthat              0.2.0           mro343h889e2dd_0
r-backports               1.1.2           mro343h889e2dd_0
r-base64enc               0.1_3           mro343h889e2dd_0
r-bh                      1.65.0_1        mro343h889e2dd_0
r-bindr                   0.1             mro343h889e2dd_0
r-bindrcpp                0.2             mro343h889e2dd_0
r-bit                     1.1_12          mro343h889e2dd_0
r-bit64                   0.9_7           mro343h889e2dd_0
r-bitops                  1.0_6                        0a
r-blob                    1.1.0           mro343h889e2dd_0
r-boot                    1.3_20                 mro343_0
r-broom                   0.4.3           mro343h889e2dd_0
r-callr                   1.0.0           mro343h889e2dd_0
r-caret                   6.0_78          mro343h889e2dd_0
r-catools                 1.17.1          mro343h889e2dd_0
r-cellranger              1.1.0           mro343h889e2dd_0
r-checkpoint              0.4.3                  mro343_0
r-class                   7.3_14                 mro343_0
r-cli                     1.0.0           mro343h889e2dd_0
r-clipr                   0.4.0           mro343h889e2dd_0
r-cluster                 2.0.6                  mro343_0
r-codetools               0.2_15                 mro343_0
r-colorspace              1.3_2           mro343h889e2dd_0
r-config                  0.2             mro343h889e2dd_0
r-crayon                  1.3.4           mro343h889e2dd_0
r-curl                    3.1                    mro343_0
r-cvst                    0.2_1           mro343h889e2dd_0
r-data.table              1.10.4_3        mro343h889e2dd_0
r-dbi                     0.7             mro343h889e2dd_0
r-dbplyr                  1.1.0           mro343h889e2dd_0
r-ddalpha                 1.3.1           mro343h889e2dd_0
r-deoptimr                1.0_8           mro343h889e2dd_0
r-deployrrserve           9.0.0                  mro343_0
r-dichromat               2.0_0           mro343h889e2dd_0
r-digest                  0.6.13          mro343h889e2dd_0
r-dimred                  0.1.0           mro343h889e2dd_0
r-doparallel              1.0.12                 mro343_0
r-dplyr                   0.7.4           mro343h889e2dd_0
r-drr                     0.0.2           mro343h889e2dd_0
r-evaluate                0.10.1          mro343h889e2dd_0
r-forcats                 0.2.0           mro343h889e2dd_0
r-foreach                 1.4.5                  mro343_0
r-foreign                 0.8_69                 mro343_0
r-formatr                 1.5             mro343h889e2dd_0
r-ggplot2                 2.2.1           mro343h889e2dd_0
r-glmnet                  2.0_13          mro343h889e2dd_0
r-glue                    1.2.0           mro343h889e2dd_0
r-gower                   0.1.2           mro343h889e2dd_0
r-gtable                  0.2.0           mro343h889e2dd_0
r-haven                   1.1.0           mro343h889e2dd_0
r-hexbin                  1.27.1          mro343h889e2dd_0
r-highr                   0.6             mro343h889e2dd_0
r-hms                     0.4.0           mro343h889e2dd_0
r-htmltools               0.3.6           mro343h889e2dd_0
r-htmlwidgets             0.9             mro343h889e2dd_0
r-httpuv                  1.3.5           mro343h889e2dd_0
r-httr                    1.3.1           mro343h889e2dd_0
r-ipred                   0.9_6           mro343h889e2dd_0
r-irdisplay               0.4.4           mro343h889e2dd_0
r-irkernel                0.8.11                 mro343_0
r-iterators               1.0.9                  mro343_0
r-jsonlite                1.5                    mro343_0
r-kernlab                 0.9_25          mro343h889e2dd_0
r-kernsmooth              2.23_15                mro343_0
r-knitr                   1.18            mro343h889e2dd_0
r-labeling                0.3                          0a
r-lattice                 0.20_35                mro343_0
r-lava                    1.5.1           mro343h889e2dd_0
r-lazyeval                0.2.1           mro343h889e2dd_0
r-lubridate               1.7.1           mro343h889e2dd_0
r-magrittr                1.5                          0a
r-maps                    3.2.0           mro343h889e2dd_0
r-markdown                0.8             mro343h889e2dd_0
r-mass                    7.3_47                 mro343_0
r-matrix                  1.2_12                 mro343_0
r-mgcv                    1.8_22                 mro343_0
r-microsoftr              3.4.3.0097             mro343_0
r-mime                    0.5             mro343h889e2dd_0
r-miniui                  0.1.1           mro343h889e2dd_0
r-mnormt                  1.5_5           mro343h889e2dd_0
r-modelmetrics            1.1.0           mro343h889e2dd_0
r-modelr                  0.1.1           mro343h889e2dd_0
r-mongolite               1.4             mro343h889e2dd_0
r-munsell                 0.4.3           mro343h889e2dd_0
r-nlme                    3.1_131                mro343_0
r-nnet                    7.3_12                 mro343_0
r-numderiv                2016.8_1        mro343h889e2dd_0
r-odbc                    1.1.3           mro343h889e2dd_0
r-openssl                 0.9.9           mro343h889e2dd_0
r-packrat                 0.4.8_1         mro343h889e2dd_0
r-pbdzmq                  0.2_6           mro343h889e2dd_0
r-pillar                  1.0.1           mro343h889e2dd_0
r-pkgconfig               2.0.1           mro343h889e2dd_0
r-pki                     0.1_5.1         mro343h889e2dd_0
r-plogr                   0.1_1           mro343h889e2dd_0
r-plyr                    1.8.4           mro343h889e2dd_0
r-png                     0.1_7                  mro343_0
r-prodlim                 1.6.1           mro343h889e2dd_0
r-profvis                 0.3.4           mro343h889e2dd_0
r-psych                   1.7.8           mro343h889e2dd_0
r-purrr                   0.2.4           mro343h889e2dd_0
r-quantmod                0.4_12          mro343h889e2dd_0
r-r6                      2.2.2                  mro343_0
r-randomforest            4.6_12          mro343h889e2dd_0
r-rappdirs                0.3.1           mro343h889e2dd_0
r-rbokeh                  0.6.3                  mro343_0
r-rcolorbrewer            1.1_2           mro343h889e2dd_0
r-rcpp                    0.12.14         mro343h889e2dd_0
r-rcpproll                0.2.2           mro343h889e2dd_0
r-rcurl                   1.95_4.9        mro343h889e2dd_0
r-readr                   1.1.1           mro343h889e2dd_0
r-readxl                  1.0.0           mro343h889e2dd_0
r-recipes                 0.1.1           mro343h889e2dd_0
r-recommended             3.4.3                  mro343_0
r-rematch                 1.0.1           mro343h889e2dd_0
r-repr                    0.12.0          mro343h889e2dd_0
r-reprex                  0.1.1           mro343h889e2dd_0
r-reshape2                1.4.3           mro343h889e2dd_0
r-revoioq                 8.0.9                  mro343_0
r-revomods                11.0.0                 mro343_0
r-revoutilsmath           10.0.1                 mro343_0
r-rjava                   0.9_9           mro343h889e2dd_0
r-rjdbc                   0.2_5           mro343h889e2dd_0
r-rjsonio                 1.3_0                        0a
r-rlang                   0.1.6           mro343h889e2dd_0
r-rmarkdown               1.8             mro343h889e2dd_0
r-robustbase              0.92_8          mro343h889e2dd_0
r-rpart                   4.1_11                 mro343_0
r-rprojroot               1.3_1           mro343h889e2dd_0
r-rsconnect               0.8.5           mro343h889e2dd_0
r-rstudioapi              0.7             mro343h889e2dd_0
r-runit                   0.4.26                 mro343_0
r-rvest                   0.3.2           mro343h889e2dd_0
r-scales                  0.5.0           mro343h889e2dd_0
r-selectr                 0.3_1           mro343h889e2dd_0
r-sfsmisc                 1.1_1           mro343h889e2dd_0
r-shiny                   1.0.5           mro343h889e2dd_0
r-sourcetools             0.1.6           mro343h889e2dd_0
r-sparklyr                0.6.4           mro343h889e2dd_0
r-spatial                 7.3_11                 mro343_0
r-stringi                 1.1.6           mro343h889e2dd_0
r-stringr                 1.2.0           mro343h889e2dd_0
r-survival                2.41_3                 mro343_0
r-tibble                  1.4.1           mro343h889e2dd_0
r-tidyr                   0.7.2           mro343h889e2dd_0
r-tidyselect              0.2.3           mro343h889e2dd_0
r-tidyverse               1.2.1           mro343h889e2dd_0
r-timedate                3042.101        mro343h889e2dd_0
r-ttr                     0.23_2          mro343h889e2dd_0
r-utf8                    1.1.2           mro343h889e2dd_0
r-uuid                    0.1_2           mro343h889e2dd_0
r-viridislite             0.2.0           mro343h889e2dd_0
r-whisker                 0.3_2                        0a
r-withr                   2.1.1           mro343h889e2dd_0
r-xml2                    1.1.1           mro343h889e2dd_0
r-xtable                  1.8_2           mro343h889e2dd_0
r-xts                     0.10_1          mro343h889e2dd_0
r-yaml                    2.1.16          mro343h889e2dd_0
r-zoo                     1.8_0           mro343h889e2dd_0
regex                     2018.08.17       py36hfa6e2cd_0
requests                  2.18.4             py36_intel_0  [intel]  intel
rope                      0.11.0                   py36_0
ruamel_yaml               0.15.46          py36hfa6e2cd_0
scikit-image              0.13.1           py36hfa6e2cd_1
scikit-learn              0.19.1          np114py36_intel_29  [intel]  intel
scipy                     1.0.1           np114py36_intel_3  [intel]  intel
seaborn                   0.9.0                    py36_0
selenium                  3.13.0                    <pip>
send2trash                1.5.0                    py36_0
service_identity          17.0.0           py36h28b3542_0
setuptools                39.0.1                   py36_0    intel
simplegeneric             0.8.1              py36_intel_5  [intel]  intel
singledispatch            3.4.0.3          py36h17d0c80_0
sip                       4.19.12          py36h6538335_0
six                       1.10.0             py36_intel_8  [intel]  intel
snowballstemmer           1.2.1            py36h763602f_0
sortedcollections         1.0.1                    py36_0
sortedcontainers          2.0.5                    py36_0
sphinx                    1.7.8                    py36_0
sphinxcontrib             1.0                      py36_1
sphinxcontrib-websupport  1.1.0                    py36_1
sqlalchemy                1.2.11           py36hfa6e2cd_0
sqlite                    3.23.1             vc14_intel_0  [intel vc14]  intel
statsmodels               0.9.0            py36h452e1ab_0
sympy                     1.1.1              py36_intel_3  [intel]  intel
tbb                       2018.0.4                 vc14_0  [vc14]  intel
tblib                     1.3.2            py36h30f5020_0
tcl                       8.6.4             vc14_intel_19  [intel vc14]  intel
tensorboard               1.9.0                     <pip>
tensorflow                1.9.0                     <pip>
termcolor                 1.1.0                     <pip>
termcolor                 1.1.0                      py_2    conda-forge
terminado                 0.8.1                    py36_1
testpath                  0.3.1              py36_intel_0  [intel]  intel
thinc                     6.11.2           py36hae9bb9f_1
tk                        8.6.4             vc14_intel_27  [intel vc14]  intel
toolz                     0.9.0                    py36_0
tornado                   4.5.2              py36_intel_0  [intel]  intel
tqdm                      4.25.0           py36h28b3542_0
traitlets                 4.3.2              py36_intel_1  [intel]  intel
twisted                   18.7.0           py36hfa6e2cd_1
typed-ast                 1.1.0            py36hfa6e2cd_0
typing                    3.6.4                    py36_0
ujson                     1.35             py36hfa6e2cd_1    conda-forge
unicodecsv                0.14.1           py36h6450c06_0
urllib3                   1.22               py36_intel_0  [intel]  intel
vc                        14.0                          2    intel
virtualenv                16.0.0                    <pip>
virtualenv-clone          0.3.0                     <pip>
vs2015_runtime            14.0.25420              intel_0  [intel]  intel
wcwidth                   0.1.7              py36_intel_5  [intel]  intel
webencodings              0.5.1                    py36_0    intel
werkzeug                  0.14.1                   py36_0
wheel                     0.31.0             py36_intel_0  [intel]  intel
win_inet_pton             1.0.1              py36_intel_0  [intel]  intel
win_unicode_console       0.5                py36_intel_0  [intel]  intel
wincertstore              0.2                py36_intel_0  [intel]  intel
winpty                    0.4.3                         4
wrapt                     1.10.11          py36hfa6e2cd_2
xlrd                      1.1.0                    py36_1
xlsxwriter                1.1.0                    py36_0
xlwings                   0.11.8                   py36_0
xlwt                      1.3.0            py36h1a4751e_0
xx-ent-wiki-sm            2.0.0                     <pip>
xz                        5.2.3              vc14_intel_1  [intel vc14]  intel
yaml                      0.1.7                    vc14_0  [vc14]  conda-forge
zeromq                    4.2.5                    vc14_2  [vc14]  conda-forge
zict                      0.1.3                    py36_0
zlib                      1.2.11             vc14_intel_4  [intel vc14]  intel
zope                      1.0                      py36_1
zope.interface            4.5.0            py36hfa6e2cd_0
```

**Comment by yinlotus** [comment]
I have the same problem!

**Comment by Kelvinli5354** [comment]
I decided to just reinstall Anaconda. Apparently whenever I do `conda update -all` anaconda stops opening. So for future ref, just update is manually lol

**Comment by mwk0423** [comment]
hi , I have a similar experience and slove it after a series action：
1. search in computer and delete irrelevant python file.
search key words such as 'python36','python37','python27'....(My computer used to have python3.6.3 in drive C: ,but my anaconda install in D: ,so i can find the weird file easily）
2. update the pyside
`conda update pyside`
3. install pyqt5
`pip install python-qt5`(`conda install pyqt5` seem not work)

Hope these able to help you
