### ISSUE TITLE
Miniconda 4.5.11 - numpy import fails if base installation is not actiated

### ISSUE THREAD

**Issue by dvincentwest** [ContinuumIO/anaconda-issues#10054]
System:

```
Windows 10 64bit
Miniconda 4.5.11, Python 3.7.0, 64-bit (downloaded Sep 11)
```

After install of Miniconda3 run

```conda install numpy```

which succeeds.  Then run `python.exe` and try to import `numpy`

```> python
Python 3.7.0 (default, Jun 28 2018, 08:04:48) [MSC v.1912 64 bit (AMD64)] :: Anaconda, Inc. on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy
Traceback (most recent call last):
  File "C:\Miniconda3\lib\site-packages\numpy\core\__init__.py", line 16, in <module>
    from . import multiarray
ImportError: DLL load failed: The specified module could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Miniconda3\lib\site-packages\numpy\__init__.py", line 142, in <module>
    from . import add_newdocs
  File "C:\Miniconda3\lib\site-packages\numpy\add_newdocs.py", line 13, in <module>
    from numpy.lib import add_newdoc
  File "C:\Miniconda3\lib\site-packages\numpy\lib\__init__.py", line 8, in <module>
    from .type_check import *
  File "C:\Miniconda3\lib\site-packages\numpy\lib\type_check.py", line 11, in <module>
    import numpy.core.numeric as _nx
  File "C:\Miniconda3\lib\site-packages\numpy\core\__init__.py", line 26, in <module>
    raise ImportError(msg)
ImportError:
Importing the multiarray numpy extension module failed.  Most
likely you are trying to import a failed build of numpy.
If you're working with a numpy git repo, try `git clean -xdf` (removes all
files not under version control).  Otherwise reinstall numpy.

Original error was: DLL load failed: The specified module could not be found.
```

if I activate the base python installation, I have no problems

```
activate base
python
>>>import numpy
```
this will succeed

I have been using conda for several years now, and I have never had to activate the base environment for things to operate normally

**Comment by ulfworsoe** [comment]
I can add this: Creating a python3.7 environment like this

```
conda create -p mypython python=3.7 numpy
```
then running `mypython\python.exe -c "import numpy"` causes the same problem. Adding `Anaconda2\Library\bin` to the `PATH` environment variable allows it to run.

**Comment by mingwandroid** [comment]
> Adding Anaconda2\Library\bin to the PATH environment variable allows it to run.

Why would you use this partial, non functional activation scheme instead of the right one, conda activate?

**Comment by ulfworsoe** [comment]
We build and test a module for multiple versions of Python (2.7,3.4,3.5,3.6,3.7). We set up one Anaconda environment for each version to test against. When building and testing we need to know exactly environment we are executing in to avoid random environment variables influencing builds and tests - this is why we set it up out selves rather than call an external script. 

Activation works well in an interactive context, but it is not ideal for automated builds.

I should mention that even if it is not a supported feature, it  has worked at least for versions 3.3...3.6 on windows, and it still seems to work on linux and osx.

**Comment by mingwandroid** [comment]
> Activation works well in an interactive context, but it is not ideal for automated builds.

How so?

Activation facilitates arbitrary functionality within packages (setting env vars such as JAVA_HOME, running programs and scripts etc) and while we try to avoid them when possible attempting to use AD outside of activation is completely unsupported and clean expected to work. Just activate.

**Comment by msarahan** [comment]
You can absolutely activate in a scripted context. For batch scripts:

``call (path to miniconda install)\scripts\activate.bat``

Powershell is not currently supported.  If you really can't activate, you are losing functionality, and you'll also need to add more entries to PATH.

**Comment by ulfworsoe** [comment]
Of course there is no such thing as "this is absolutely impossible for us to do", but it would be very inconvenient. It is possible to change every call in our build system and test system to an external Anaconda Python to use run activate before executing Python (and having to introduce distinction between Python and Anaconda Python installations) - but the amount of work required is simply not worth it, so I'd rather just hack it and void the warranty. 

We use this setup solely for having a Python with Numpy support on Windows x64, so it is quite limited what functionality is lost.

**Comment by mingwandroid** [comment]
You're welcome to do that but should not file bugs in that situation.

**Comment by geochemistry** [comment]
> 
> 
> I can add this: Creating a python3.7 environment like this
> 
> ```
> conda create -p mypython python=3.7 numpy
> ```
> 
> then running `mypython\python.exe -c "import numpy"` causes the same problem. Adding `Anaconda2\Library\bin` to the `PATH` environment variable allows it to run.

I had the same error on Anaconda3. I added _\Anaconda3\Library\bin_ to system path variable and it worked

**Comment by mingwandroid** [comment]
Just call activate. I have no idea why this is considered burdensome.
