### ISSUE TITLE
How to modify the conda config to download the files using wget

### ISSUE THREAD

**Issue by Saranya411** [ContinuumIO/anaconda-issues#10050]
Hi ,

We are using conda install <package_name> and its failing with below error.

Failed to establish a new connection: [Errno 101] Network is unreachable',))

Solving environment:   failed      CondaHTTPError: HTTP 000 CONNECTION FAILED for url <https://conda.anaconda.org/r/linux-64/repodata.json>   Elapsed: -      An HTTP error occurred when trying to retrieve this URL.   HTTP errors are often intermittent, and a simple retry will get you on your   way.   
--

But we have access to the URL. curl is not working in our system and wget is working. 

We suspect conda install is using curl to download the files. 

Can anyone has any idead of how to change the config for conda install to refer wget instead of curl ?

Thanks,
Saranya

**Comment by Saranya411** [comment]
Anyone has any solution for this. now curl is working but conda install is still giving the same error.

**Comment by msarahan** [comment]
Conda is not using curl.  It's using requests, which is in turn using urllib, I think.  Are there proxies involved?

**Comment by Saranya411** [comment]
Hi Marashan, 

Thanks for your reply..  Am very new to conda...  And tried request.get (www.google. Com) but am not getting 200 response...  and getting some issues...  This may be cause why conda install is not working? 

Can you please help me in the above error?  And how to rectify it

**Comment by Saranya411** [comment]
I am getting below error when using requests.get.

>>> requests.get("https://www.google.com/")
Traceback (most recent call last):
  File "/pathtoanaconda/anaconda3/lib/python3.6/site-packages/urllib3/connection.py", line 141, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "/pathtoanaconda/anaconda3/lib/python3.6/site-packages/urllib3/util/connection.py", line 83, in create_connection
    raise err
  File "/pathtoanaconda/anaconda3/lib/python3.6/site-packages/urllib3/util/connection.py", line 73, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/pathtoanaconda/anaconda3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/pathtoanaconda/anaconda3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 346, in _make_request
    self._validate_conn(conn)
  File "/pathtoanaconda/anaconda3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 850, in _validate_conn
    conn.connect()
  File "/pathtoanaconda/anaconda3/lib/python3.6/site-packages/urllib3/connection.py", line 284, in connect
    conn = self._new_conn()
  File "/pathtoanaconda/anaconda3/lib/python3.6/site-packages/urllib3/connection.py", line 150, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x7fbcb4fb7cc0>: Failed to establish a new connection: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/pathtoanaconda/anaconda3/lib/python3.6/site-packages/requests/adapters.py", line 440, in send
    timeout=timeout
  File "/pathtoanaconda/anaconda3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/pathtoanaconda/anaconda3/lib/python3.6/site-packages/urllib3/util/retry.py", line 388, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fbcb4fb7cc0>: Failed to establish a new connection: [Errno 110] Connection timed out',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/pathtoanaconda/anaconda3/lib/python3.6/site-packages/requests/api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "/pathtoanaconda/anaconda3/lib/python3.6/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/pathtoanaconda/anaconda3/lib/python3.6/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/pathtoanaconda/anaconda3/lib/python3.6/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/pathtoanaconda/anaconda3/lib/python3.6/site-packages/requests/adapters.py", line 508, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fbcb4fb7cc0>: Failed to establish a new connection: [Errno 110] Connection timed out',))
>>>
>>>



Anyone has any idea on how to fix it. its working as root user and getting 200 response.

but getting the above issue when using it as non-root user.
