### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by scdabr** [ContinuumIO/anaconda-issues#10052]
## Main error
Application <b>orange3</b> launch may have produced errors.
## Traceback
```
Traceback (most recent call last):
  File "C:\Users\xxx\AppData\Local\Continuum\Anaconda3\Scripts\orange-canvas-script.py", line 6, in <module>
    from Orange.canvas.__main__ import main
  File "C:\Users\xxx\AppData\Local\Continuum\Anaconda3\lib\site-packages\Orange\canvas\__main__.py", line 30, in <module>
    from Orange.canvas.application.canvasmain import CanvasMainWindow
  File "C:\Users\xxx\AppData\Local\Continuum\Anaconda3\lib\site-packages\Orange\canvas\application\canvasmain.py", line 61, in <module>
    from .canvastooldock import CanvasToolDock, QuickCategoryToolbar, \
  File "C:\Users\xxx\AppData\Local\Continuum\Anaconda3\lib\site-packages\Orange\canvas\application\canvastooldock.py", line 25, in <module>
    from ..document.quickmenu import MenuPage
  File "C:\Users\xxx\AppData\Local\Continuum\Anaconda3\lib\site-packages\Orange\canvas\document\__init__.py", line 17, in <module>
    from .schemeedit import SchemeEditWidget
  File "C:\Users\xxx\AppData\Local\Continuum\Anaconda3\lib\site-packages\Orange\canvas\document\schemeedit.py", line 37, in <module>
    from .suggestions import Suggestions
  File "C:\Users\xxx\AppData\Local\Continuum\Anaconda3\lib\site-packages\Orange\canvas\document\suggestions.py", line 7, in <module>
    from .interactions import NewLinkAction
  File "C:\Users\xxx\AppData\Local\Continuum\Anaconda3\lib\site-packages\Orange\canvas\document\interactions.py", line 28, in <module>
    from ..canvas import items
  File "C:\U

**Comment by goanpeca** [comment]
Please remember to update to the latest version of Navigator to include
the latest fixes.

Open a terminal (on Linux or Mac) or the Anaconda Command Prompt (on windows)
and type:

```
conda update conda
conda update --all
```
