### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by BrightSea-Li** [ContinuumIO/anaconda-issues#10056]
## Main error
Application <b>spyder</b> launch may have produced errors.
## Traceback
```
Traceback (most recent call last):
  File "E:\Anaconda3\lib\site-packages\qtpy\QtWebEngineWidgets.py", line 22, in <module>
    from PyQt5.QtWebEngineWidgets import QWebEnginePage
ModuleNotFoundError: No module named 'PyQt5.QtWebEngineWidgets'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Anaconda3\Scripts\spyder-script.py", line 10, in <module>
    sys.exit(main())
  File "E:\Anaconda3\lib\site-packages\spyder\app\start.py", line 190, in main
    from spyder.app import mainwindow
  File "E:\Anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 92, in <module>
    from qtpy import QtWebEngineWidgets  # analysis:ignore
  File "E:\Anaconda3\lib\site-packages\qtpy\QtWebEngineWidgets.py", line 26, in <module>
    from PyQt5.QtWebKitWidgets import QWebPage as QWebEnginePage
ModuleNotFoundError: No module named 'PyQt5.QtWebKitWidgets'

```
## System information
```
python: 3.6.6
language: zh_CN
os: Windows;7;6.1.7601;x86;x86 Family 6 Model 42 Stepping 7, GenuineIntel
version: 1.6.2
platform: win-32
qt: 5.11.1
pyqt: 5.9.2
conda: 4.5.11
```

**Comment by goanpeca** [comment]
Please remember to update to the latest version of Navigator to include
the latest fixes.

Open a terminal (on Linux or Mac) or the Anaconda Command Prompt (on windows)
and type:

```
conda update conda
conda update --all
```

**Comment by Neocurve** [comment]
I have the same issue on fedora.
updated conda and all packages, but still not resolved.
