### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by yaceben** [ContinuumIO/anaconda-issues#10063]
Navigator Error
An unexpected error occurred on Navigator start-up

Report
Please report this issue in the anaconda issue tracker

Main Error
expected str, bytes or os.PathLike object, not NoneType
Traceback
Traceback (most recent call last):
  File "C:\Users\xxxxx\AppData\Local\Continuum\anaconda3\lib\site-packages\anaconda_navigator\exceptions.py", line 75, in exception_handler
    return_value = func(*args, **kwargs)
  File "C:\Users\xxxxx\AppData\Local\Continuum\anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 150, in start_app
    window = run_app(splash)
  File "C:\Users\xxxxx\AppData\Local\Continuum\anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 65, in run_app
    window = MainWindow(splash=splash, tab_project=False)
  File "C:\Users\xxxxx\AppData\Local\Continuum\anaconda3\lib\site-packages\anaconda_navigator\widgets\main_window.py", line 163, in __init__
    self.api = AnacondaAPI()
  File "C:\Users\xxxxx\AppData\Local\Continuum\anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 2185, in AnacondaAPI
    ANACONDA_API = _AnacondaAPI()
  File "C:\Users\xxxxx\AppData\Local\Continuum\anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 89, in __init__
    self._conda_api = CondaAPI()
  File "C:\Users\xxxxx\AppData\Local\Continuum\anaconda3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 1714, in CondaAPI
    CONDA_API = _CondaAPI()
  File "C:\Users\xxxxx\AppData\Local\Continuum\anaconda3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 353, in __init__
    self.sys_rc_path = join(self.ROOT_PREFIX, '.condarc')
  File "C:\Users\xxxxx\AppData\Local\Continuum\anaconda3\lib\ntpath.py", line 76, in join
    path = os.fspath(path)
TypeError: expected str, bytes or os.PathLike object, not NoneType

### Actual Behavior

Failed to open **Anaconda Navigator**

### Expected Behavior

Successfully opens **Anaconda Navigator**

### Steps to Reproduce

might be that I changed environment and did not deactivate it before closing **Anaconda Prompt**

##### Anaconda or Miniconda version:

Continuum Anaconda version 5.2.0.0 (not 100% sure)

##### Operating System:

Windows 10 pro 64 bits

##### `conda info`
cannot open conda prompt
```
Traceback (most recent call last):
  File "c:\users\xxxxx\appdata\local\continuum\anaconda3\envs\tensorflow\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\xxxxx\appdata\local\continuum\anaconda3\envs\tensorflow\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\xxxxx\AppData\Local\Continuum\anaconda3\Scripts\conda.exe\__main__.py", line 9, in <module>
  File "c:\users\xxxxx\appdata\local\continuum\anaconda3\envs\tensorflow\lib\site-packages\markdown\__main__.py", line 130, in run
    markdown.markdownFromFile(**options)
  File "c:\users\xxxxx\appdata\local\continuum\anaconda3\envs\tensorflow\lib\site-packages\markdown\__init__.py", line 529, in markdownFromFile
    kwargs.get('encoding', None))
  File "c:\users\xxxxx\appdata\local\continuum\anaconda3\envs\tensorflow\lib\site-packages\markdown\__init__.py", line 428, in convertFile
    input_file = codecs.open(input, mode="r", encoding=encoding)
  File "c:\users\xxxxx\appdata\local\continuum\anaconda3\envs\tensorflow\lib\codecs.py", line 897, in open
    file = builtins.open(filename, mode, buffering)
FileNotFoundError: [Errno 2] No such file or directory: 'shell.cmd.exe'
```

**Comment by goanpeca** [comment]
Please provide the information 

### Actual Behavior



### Expected Behavior



### Steps to Reproduce




##### Anaconda or Miniconda version:

##### Operating System:

##### `conda info`

```

```

##### `conda list --show-channel-urls`

```

```
