### ISSUE TITLE
No module named 'numpy.core.numeric'

### ISSUE THREAD

**Issue by roachsinai** [ContinuumIO/anaconda-issues#1007]
```
[xq@roach least_square]$ python
Python 3.5.2 |Anaconda custom (64-bit)| (default, Jul  2 2016, 17:53:06) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/xq/Installed/anaconda3/lib/python3.5/site-packages/numpy/__init__.py", line 184, in <module>
    from . import add_newdocs
  File "/home/xq/Installed/anaconda3/lib/python3.5/site-packages/numpy/add_newdocs.py", line 13, in <module>
    from numpy.lib import add_newdoc
  File "/home/xq/Installed/anaconda3/lib/python3.5/site-packages/numpy/lib/__init__.py", line 8, in <module>
    from .type_check import *
  File "/home/xq/Installed/anaconda3/lib/python3.5/site-packages/numpy/lib/type_check.py", line 11, in <module>
    import numpy.core.numeric as _nx
ImportError: No module named 'numpy.core.numeric'
```

Above error come after I updated my packages use `conda update --all`. My `numpy` version is `1.11.1-py35_0 defaults` after that update.

And Everything will be OK after `downgrade` numpy to `1.11.0`.

**Comment by roachsinai** [comment]
So embarrassed to found `pandas` also need to `downgrade` to `0.18.0` on my laptop. :-(

**Comment by cekai** [comment]
`pip install --upgrade numpy` fixed the issue for me

**Comment by cjarv** [comment]
Can you please specify which version of numpy corrected this issue?
