### ISSUE TITLE
I cannot run the command `conda update conda` on my command line

### ISSUE THREAD

**Issue by a52siddi** [ContinuumIO/anaconda-issues#10080]
Everything was working perfectly on my system until I downloaded tensorflow via the anaconda navigator. Now, I cannot run any conda commands through the command line. 

When I typed conda update conda on the command line I got this output:

```
C:\Users\Abdullah Siddiqui>conda update conda
Traceback (most recent call last):
  File "c:\users\abdullah siddiqui\anaconda3\envs\tensorflow\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\abdullah siddiqui\anaconda3\envs\tensorflow\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Abdullah Siddiqui\Anaconda3\Scripts\conda.exe\__main__.py", line 9, in <module>
  File "c:\users\abdullah siddiqui\anaconda3\envs\tensorflow\lib\site-packages\markdown\__main__.py", line 130, in run
    markdown.markdownFromFile(**options)
  File "c:\users\abdullah siddiqui\anaconda3\envs\tensorflow\lib\site-packages\markdown\__init__.py", line 529, in markdownFromFile
    kwargs.get('encoding', None))
  File "c:\users\abdullah siddiqui\anaconda3\envs\tensorflow\lib\site-packages\markdown\__init__.py", line 428, in convertFile
    input_file = codecs.open(input, mode="r", encoding=encoding)
  File "c:\users\abdullah siddiqui\anaconda3\envs\tensorflow\lib\codecs.py", line 895, in open
    file = builtins.open(filename, mode, buffering)
FileNotFoundError: [Errno 2] No such file or directory: 'update'
```

I cannot open the navigator and use any other features of conda either. 

My conda version is as follows:

```
C:\Users\Abdullah Siddiqui>conda --version
conda 2.6.11
```

Please tell me why this issue has occured and help me resolve it.

ADDITION:

What exactly is happening with continuum.io?

![continuum_crash](https://user-images.githubusercontent.com/5900455/45711495-bcddc700-bb57-11e8-9bd3-0d936ae0cea2.JPG)

**Comment by goanpeca** [comment]
Please provide the information requested on the issue



### Actual Behavior



### Expected Behavior



### Steps to Reproduce




##### Anaconda or Miniconda version:

##### Operating System:

##### `conda info`

```

```

##### `conda list --show-channel-urls`

```

```

**Comment by a52siddi** [comment]
I un-installed Anaconda and installed it again. I am not experiencing the same issues any more.

**Comment by csoja** [comment]
@a52siddi  I'm glad to hear it is working for you now.  Thanks for letting us know!
