### ISSUE TITLE
Anaconda Prompt and Navigator not opening

### ISSUE THREAD

**Issue by Adishah3103** [ContinuumIO/anaconda-issues#10090]
##### `conda info`

```Traceback (most recent call last):
  File "C:\Users\Aditya\Anaconda3\lib\site-packages\anaconda_navigator\exceptions.py", line 75, in exception_handler
    return_value = func(*args, **kwargs)
  File "C:\Users\Aditya\Anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 138, in start_app
    window = run_app(splash)
  File "C:\Users\Aditya\Anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 64, in run_app
    window = MainWindow(splash=splash, tab_project=False)
  File "C:\Users\Aditya\Anaconda3\lib\site-packages\anaconda_navigator\widgets\main_window.py", line 163, in __init__
    self.api = AnacondaAPI()
  File "C:\Users\Aditya\Anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 2122, in AnacondaAPI
    ANACONDA_API = _AnacondaAPI()
  File "C:\Users\Aditya\Anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 89, in __init__
    self._conda_api = CondaAPI()
  File "C:\Users\Aditya\Anaconda3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 1699, in CondaAPI
    CONDA_API = _CondaAPI()
  File "C:\Users\Aditya\Anaconda3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 347, in __init__
    self.set_conda_prefix()
  File "C:\Users\Aditya\Anaconda3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 506, in set_conda_prefix
    self.ROOT_PREFIX = info['root_prefix']
TypeError: byte indices must be integers or slices, not str

```

##### `conda list --show-channel-urls`

```

```

**Comment by Adishah3103** [comment]
Has someone faced this issue before?
Please help

**Comment by goanpeca** [comment]
@Adishah3103 could you open the `anaconda prompt` and type

`conda info`

and then

`conda list` ?
