### ISSUE TITLE
Anaconda Navigator Error

### ISSUE THREAD

**Issue by shashank288** [ContinuumIO/anaconda-issues#10096]
### Actual Behavior

```
```
Navigator Error
An unexpected error occurred on Navigator start-up

Report
Please report this issue in the anaconda issue tracker

Main Error
expected str, bytes or os.PathLike object, not NoneType
Traceback
Traceback (most recent call last):
  File "C:\Users\Shashank Sekhar\Anaconda3\lib\site-packages\anaconda_navigator\exceptions.py", line 75, in exception_handler
    return_value = func(*args, **kwargs)
  File "C:\Users\Shashank Sekhar\Anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 150, in start_app
    window = run_app(splash)
  File "C:\Users\Shashank Sekhar\Anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 65, in run_app
    window = MainWindow(splash=splash, tab_project=False)
  File "C:\Users\Shashank Sekhar\Anaconda3\lib\site-packages\anaconda_navigator\widgets\main_window.py", line 163, in __init__
    self.api = AnacondaAPI()
  File "C:\Users\Shashank Sekhar\Anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 2185, in AnacondaAPI
    ANACONDA_API = _AnacondaAPI()
  File "C:\Users\Shashank Sekhar\Anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 89, in __init__
    self._conda_api = CondaAPI()
  File "C:\Users\Shashank Sekhar\Anaconda3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 1714, in CondaAPI
    CONDA_API = _CondaAPI()
  File "C:\Users\Shashank Sekhar\Anaconda3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 353, in __init__
    self.sys_rc_path = join(self.ROOT_PREFIX, '.condarc')
  File "C:\Users\Shashank Sekhar\Anaconda3\lib\ntpath.py", line 76, in join
    path = os.fspath(path)
TypeError: expected str, bytes or os.PathLike object, not NoneType
```
```

### Expected Behavior

I expect the navigator window to open but it gives me this error.

### Steps to Reproduce

I try to run the anaconda navigator through the shortcut in the start menu.

##### Anaconda or Miniconda version: 
Anaconda 5.2.0 64-bit

##### Operating System:
Windows 8.1 Enterprise `64-bit`

##### `conda info`

```
C:\Users\Shashank Sekhar>conda info

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "C:\Users\Shashank Sekhar\Anaconda3\lib\site-packages\conda\exception
s.py", line 819, in __call__
        return func(*args, **kwargs)
      File "C:\Users\Shashank Sekhar\Anaconda3\lib\site-packages\conda\cli\main.
py", line 74, in _main
        context.__init__(argparse_args=args)
      File "C:\Users\Shashank Sekhar\Anaconda3\lib\site-packages\conda\base\cont
ext.py", line 236, in __init__
        argparse_args=argparse_args)
      File "C:\Users\Shashank Sekhar\Anaconda3\lib\site-packages\conda\common\co
nfiguration.py", line 722, in __init__
        self._set_search_path(search_path)
      File "C:\Users\Shashank Sekhar\Anaconda3\lib\site-packages\conda\common\co
nfiguration.py", line 728, in _set_search_path
        self._set_raw_data(load_file_configs(search_path))
      File "C:\Users\Shashank Sekhar\Anaconda3\lib\site-packages\conda\common\co
nfiguration.py", line 369, in load_file_configs
        raw_data = odict(kv for kv in chain.from_iterable(load_paths))
      File "C:\Users\Shashank Sekhar\Anaconda3\lib\site-packages\conda\common\co
nfiguration.py", line 369, in <genexpr>
        raw_data = odict(kv for kv in chain.from_iterable(load_paths))
      File "C:\Users\Shashank Sekhar\Anaconda3\lib\site-packages\conda\common\co
nfiguration.py", line 344, in _file_yaml_loader
        yield fullpath, YamlRawParameter.make_raw_parameters_from_file(fullpath)

      File "C:\Users\Shashank Sekhar\Anaconda3\lib\site-packages\conda\common\co
nfiguration.py", line 332, in make_raw_parameters_from_file
        ruamel_yaml = yaml_load(fh)
      File "C:\Users\Shashank Sekhar\Anaconda3\lib\site-packages\conda\common\se
rialize.py", line 54, in yaml_load
        return yaml.load(string, Loader=yaml.RoundTripLoader, version="1.2")
      File "C:\Users\Shashank Sekhar\Anaconda3\lib\site-packages\ruamel_yaml\mai
n.py", line 637, in load
        loader = Loader(stream, version, preserve_quotes=preserve_quotes)
      File "C:\Users\Shashank Sekhar\Anaconda3\lib\site-packages\ruamel_yaml\loa
der.py", line 59, in __init__
        Reader.__init__(self, stream, loader=self)
      File "C:\Users\Shashank Sekhar\Anaconda3\lib\site-packages\ruamel_yaml\rea
der.py", line 80, in __init__
        self.stream = stream  # type: Any  # as .read is called
      File "C:\Users\Shashank Sekhar\Anaconda3\lib\site-packages\ruamel_yaml\rea
der.py", line 125, in stream
        self.determine_encoding()
      File "C:\Users\Shashank Sekhar\Anaconda3\lib\site-packages\ruamel_yaml\rea
der.py", line 180, in determine_encoding
        self.update(1)
      File "C:\Users\Shashank Sekhar\Anaconda3\lib\site-packages\ruamel_yaml\rea
der.py", line 241, in update
        self.check_printable(data)
      File "C:\Users\Shashank Sekhar\Anaconda3\lib\site-packages\ruamel_yaml\rea
der.py", line 208, in check_printable
        'unicode', "special characters are not allowed")
    ruamel_yaml.reader.ReaderError: unacceptable character #x0000: special chara
cters are not allowed
      in "C:\Users\Shashank Sekhar\AppData\Roaming\SPB_16.6\.condarc", position
0

`$ C:\Users\Shashank Sekhar\Anaconda3\Scripts\conda info`


An unexpected error has occurred. Conda has prepared the above report.
If submitted, this report will be used by core maintainers to improve
future releases of conda.
Would you like conda to send this report to the core maintainers?
`[y/N]:`

```
##### `conda list --show-channel-urls`

```
C:\Users\Shashank Sekhar>conda list --show-channel-urls

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "C:\Users\Shashank Sekhar\Anaconda3\lib\site-packages\conda\exception
s.py", line 819, in __call__
        return func(*args, **kwargs)
      File "C:\Users\Shashank Sekhar\Anaconda3\lib\site-packages\conda\cli\main.
py", line 74, in _main
        context.__init__(argparse_args=args)
      File "C:\Users\Shashank Sekhar\Anaconda3\lib\site-packages\conda\base\cont
ext.py", line 236, in __init__
        argparse_args=argparse_args)
      File "C:\Users\Shashank Sekhar\Anaconda3\lib\site-packages\conda\common\co
nfiguration.py", line 722, in __init__
        self._set_search_path(search_path)
      File "C:\Users\Shashank Sekhar\Anaconda3\lib\site-packages\conda\common\co
nfiguration.py", line 728, in _set_search_path
        self._set_raw_data(load_file_configs(search_path))
      File "C:\Users\Shashank Sekhar\Anaconda3\lib\site-packages\conda\common\co
nfiguration.py", line 369, in load_file_configs
        raw_data = odict(kv for kv in chain.from_iterable(load_paths))
      File "C:\Users\Shashank Sekhar\Anaconda3\lib\site-packages\conda\common\co
nfiguration.py", line 369, in <genexpr>
        raw_data = odict(kv for kv in chain.from_iterable(load_paths))
      File "C:\Users\Shashank Sekhar\Anaconda3\lib\site-packages\conda\common\co
nfiguration.py", line 344, in _file_yaml_loader
        yield fullpath, YamlRawParameter.make_raw_parameters_from_file(fullpath)

      File "C:\Users\Shashank Sekhar\Anaconda3\lib\site-packages\conda\common\co
nfiguration.py", line 332, in make_raw_parameters_from_file
        ruamel_yaml = yaml_load(fh)
      File "C:\Users\Shashank Sekhar\Anaconda3\lib\site-packages\conda\common\se
rialize.py", line 54, in yaml_load
        return yaml.load(string, Loader=yaml.RoundTripLoader, version="1.2")
      File "C:\Users\Shashank Sekhar\Anaconda3\lib\site-packages\ruamel_yaml\mai
n.py", line 637, in load
        loader = Loader(stream, version, preserve_quotes=preserve_quotes)
      File "C:\Users\Shashank Sekhar\Anaconda3\lib\site-packages\ruamel_yaml\loa
der.py", line 59, in __init__
        Reader.__init__(self, stream, loader=self)
      File "C:\Users\Shashank Sekhar\Anaconda3\lib\site-packages\ruamel_yaml\rea
der.py", line 80, in __init__
        self.stream = stream  # type: Any  # as .read is called
      File "C:\Users\Shashank Sekhar\Anaconda3\lib\site-packages\ruamel_yaml\rea
der.py", line 125, in stream
        self.determine_encoding()
      File "C:\Users\Shashank Sekhar\Anaconda3\lib\site-packages\ruamel_yaml\rea
der.py", line 180, in determine_encoding
        self.update(1)
      File "C:\Users\Shashank Sekhar\Anaconda3\lib\site-packages\ruamel_yaml\rea
der.py", line 241, in update
        self.check_printable(data)
      File "C:\Users\Shashank Sekhar\Anaconda3\lib\site-packages\ruamel_yaml\rea
der.py", line 208, in check_printable
        'unicode', "special characters are not allowed")
    ruamel_yaml.reader.ReaderError: unacceptable character #x0000: special chara
cters are not allowed
      in "C:\Users\Shashank Sekhar\AppData\Roaming\SPB_16.6\.condarc", position
0

`$ C:\Users\Shashank Sekhar\Anaconda3\Scripts\conda list --show-channel-urls`

  environment variables:
                 CIO_TEST=<not set>
               CONDA_ROOT=C:\Users\Shashank Sekhar\Anaconda3
                 HOMEPATH=\Users\Shashank Sekhar
                     PATH=C:\Users\Shashank Sekhar\Anaconda3\Library\bin;C:\Prog
ramData\Oracle\J
                          ava\javapath;C:\Windows\System32;C:\Program Files
                          (x86)\Brackets\command;C:\Users\Shashank Sekhar\Anacon
da3\Scripts
             PSMODULEPATH=C:\Windows\system32\WindowsPowerShell\v1.0\Modules\
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>

     active environment : None
       user config file : C:\Users\Shashank Sekhar\AppData\Roaming\SPB_16.6\.con
darc
 populated config files :
          conda version : 4.5.4
    conda-build version : 3.10.5
         python version : 3.6.5.final.0
       base environment : C:\Users\Shashank Sekhar\Anaconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/win-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/win-64
                          https://repo.anaconda.com/pkgs/pro/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\Users\Shashank Sekhar\Anaconda3\pkgs
                          C:\Users\Shashank Sekhar\AppData\Local\conda\conda\pkg
s
       envs directories : C:\Users\Shashank Sekhar\Anaconda3\envs
                          C:\Users\Shashank Sekhar\AppData\Local\conda\conda\env
s
                          C:\Users\Shashank Sekhar\AppData\Roaming\SPB_16.6\.con
da\envs
               platform : win-64
             user-agent : conda/4.5.4 requests/2.18.4 CPython/3.6.5 Windows/8.1
Windows/6.3.9600
          administrator : False
             netrc file : None
           offline mode : False


An unexpected error has occurred. Conda has prepared the above report.
If submitted, this report will be used by core maintainers to improve
future releases of conda.
Would you like conda to send this report to the core maintainers?
[y/N]:
No report sent. To permanently opt-out, use

    $ conda config --set report_errors false

```

**Comment by goanpeca** [comment]
Please manualluy delete this file and try again `C:\Users\Shashank Sekhar\AppData\Roaming\SPB_16.6\.condarc`

**Comment by shashank288** [comment]
Thanks it worked for me.
