### ISSUE TITLE
Navigation issue (expected str, bytes or os.PathLike object, not NoneType)

### ISSUE THREAD

**Issue by radman666** [ContinuumIO/anaconda-issues#10105]
### Actual Behavior

Hi, there is an issue when attempting to open the anaconda navigator on my computer. I have tried updating it with -conda update conda on the anaconda navigator. The following error appears in my browser:

`
Main Error
expected str, bytes or os.PathLike object, not NoneType
Traceback
Traceback (most recent call last):
  File "C:\Users\Window10Pro\Desktop\Anaconda\lib\site-packages\anaconda_navigator\exceptions.py", line 75, in exception_handler
    return_value = func(*args, **kwargs)
  File "C:\Users\Window10Pro\Desktop\Anaconda\lib\site-packages\anaconda_navigator\app\start.py", line 150, in start_app
    window = run_app(splash)
  File "C:\Users\Window10Pro\Desktop\Anaconda\lib\site-packages\anaconda_navigator\app\start.py", line 65, in run_app
    window = MainWindow(splash=splash, tab_project=False)
  File "C:\Users\Window10Pro\Desktop\Anaconda\lib\site-packages\anaconda_navigator\widgets\main_window.py", line 163, in __init__
    self.api = AnacondaAPI()
  File "C:\Users\Window10Pro\Desktop\Anaconda\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 2185, in AnacondaAPI
    ANACONDA_API = _AnacondaAPI()
  File "C:\Users\Window10Pro\Desktop\Anaconda\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 89, in __init__
    self._conda_api = CondaAPI()
  File "C:\Users\Window10Pro\Desktop\Anaconda\lib\site-packages\anaconda_navigator\api\conda_api.py", line 1714, in CondaAPI
    CONDA_API = _CondaAPI()
  File "C:\Users\Window10Pro\Desktop\Anaconda\lib\site-packages\anaconda_navigator\api\conda_api.py", line 353, in __init__
    self.sys_rc_path = join(self.ROOT_PREFIX, '.condarc')
  File "C:\Users\Window10Pro\Desktop\Anaconda\lib\ntpath.py", line 76, in join
    path = os.fspath(path)
TypeError: expected str, bytes or os.PathLike object, not NoneType

`

### Expected Behavior

Ideally it should simply open, not quite sure why it isn't.

##### Anaconda or Miniconda version:

Anaconda windows version 3.2

##### Operating System:

Windows 10

**Comment by ialiman** [comment]
i have the same issue and same specs.
