### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by Xiajun666** [ContinuumIO/anaconda-issues#10116]
## Main error
Application <b>spyder</b> launch may have produced errors.
## Traceback
```
Traceback (most recent call last):
  File "/Users/Xiajun/anaconda/envs/py35/bin/spyder", line 7, in <module>
    from spyder.app.start import main
  File "/Users/Xiajun/anaconda/envs/py35/lib/python3.6/site-packages/spyder/app/start.py", line 12, in <module>
    import zmq
  File "/Users/Xiajun/anaconda/envs/py35/lib/python3.6/site-packages/zmq/__init__.py", line 29, in <module>
    _load_libzmq()
  File "/Users/Xiajun/anaconda/envs/py35/lib/python3.6/site-packages/zmq/__init__.py", line 9, in _load_libzmq
    import sys, ctypes, platform
  File "/Users/Xiajun/anaconda/envs/py35/lib/python3.6/platform.py", line 116, in <module>
    import sys, os, re, subprocess
  File "/Users/Xiajun/anaconda/envs/py35/lib/python3.6/subprocess.py", line 136, in <module>
    import _posixsubprocess
ImportError: dlopen(/Users/Xiajun/anaconda/envs/py35/lib/python3.6/lib-dynload/_posixsubprocess.cpython-36m-darwin.so, 2): Symbol not found: __Py_set_inheritable_async_safe
  Referenced from: /Users/Xiajun/anaconda/envs/py35/lib/python3.6/lib-dynload/_posixsubprocess.cpython-36m-darwin.so
  Expected in: flat namespace
 in /Users/Xiajun/anaconda/envs/py35/lib/python3.6/lib-dynload/_posixsubprocess.cpython-36m-darwin.so

```
## System information
```
platform: osx-64
version: 1.6.2
conda: 4.5.11
qt: 5.6.2
language: en
python: 2.7.14
os: Darwin;17.7.0;Darwin Kernel Version 17.7.0: Thu Jun 21 22:53:14 PDT 2018; root:xnu-4570.71.2~1/RELEASE_X86_64;x86_64;i386
pyqt: 5.6.0
```

**Comment by goanpeca** [comment]
Please remember to update to the latest version of Navigator to include
the latest fixes.

Open a terminal (on Linux or Mac) or the Anaconda Command Prompt (on windows)
and type:

```
conda update conda
conda update --all
```
