### ISSUE TITLE
Navigator not starting 

### ISSUE THREAD

**Issue by hrishikeshsontakke** [ContinuumIO/anaconda-issues#10148]
### Actual Behavior

Anaconda Navigator does not start.

### Expected Behavior

Anaconda navigator to start normally

##### Anaconda or Miniconda version:

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "G:\Software\Anaconda31\lib\site-packages\conda\cli\main.py", line 97, in main
        from ..activate import main as activator_main
      File "G:\Software\Anaconda31\lib\site-packages\conda\activate.py", line 15, in <module>
        context.__init__()  # oOn import, context does not include SEARCH_PATH. This line fixes that.
      File "G:\Software\Anaconda31\lib\site-packages\conda\base\context.py", line 237, in __init__
        argparse_args=argparse_args)
      File "G:\Software\Anaconda31\lib\site-packages\conda\common\configuration.py", line 722, in __init__
        self._set_search_path(search_path)
      File "G:\Software\Anaconda31\lib\site-packages\conda\common\configuration.py", line 728, in _set_search_path
        self._set_raw_data(load_file_configs(search_path))
      File "G:\Software\Anaconda31\lib\site-packages\conda\common\configuration.py", line 369, in load_file_configs
        raw_data = odict(kv for kv in chain.from_iterable(load_paths))
      File "G:\Software\Anaconda31\lib\site-packages\conda\common\configuration.py", line 369, in <genexpr>
        raw_data = odict(kv for kv in chain.from_iterable(load_paths))
      File "G:\Software\Anaconda31\lib\site-packages\conda\common\configuration.py", line 344, in _file_yaml_loader
        yield fullpath, YamlRawParameter.make_raw_parameters_from_file(fullpath)
      File "G:\Software\Anaconda31\lib\site-packages\conda\common\configuration.py", line 332, in make_raw_parameters_from_file
        ruamel_yaml = yaml_load(fh)
      File "G:\Software\Anaconda31\lib\site-packages\conda\common\serialize.py", line 54, in yaml_load
        return yaml.load(string, Loader=yaml.RoundTripLoader, version="1.2")
      File "G:\Software\Anaconda31\lib\site-packages\ruamel_yaml\main.py", line 638, in load
        loader = Loader(stream, version, preserve_quotes=preserve_quotes)
      File "G:\Software\Anaconda31\lib\site-packages\ruamel_yaml\loader.py", line 59, in __init__
        Reader.__init__(self, stream, loader=self)
      File "G:\Software\Anaconda31\lib\site-packages\ruamel_yaml\reader.py", line 80, in __init__
        self.stream = stream  # type: Any  # as .read is called
      File "G:\Software\Anaconda31\lib\site-packages\ruamel_yaml\reader.py", line 125, in stream
        self.determine_encoding()
      File "G:\Software\Anaconda31\lib\site-packages\ruamel_yaml\reader.py", line 180, in determine_encoding
        self.update(1)
      File "G:\Software\Anaconda31\lib\site-packages\ruamel_yaml\reader.py", line 266, in update
        self.check_printable(data)
      File "G:\Software\Anaconda31\lib\site-packages\ruamel_yaml\reader.py", line 233, in check_printable
        'unicode', "special characters are not allowed")
    ruamel_yaml.reader.ReaderError: unacceptable character #x0000: special characters are not allowed
      in "C:\Users\HP\.condarc", position 0

`$ G:\Software\Anaconda31\Scripts\conda shell.cmd.exe activate activate G:\Software\Anaconda31`

  environment variables:
                 CIO_TEST=<not set>
               CONDA_ROOT=G:\Software\Anaconda31
                CUDA_PATH=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.0
          EQ_LIBRARY_PATH=C:\MinGW\x86_64-w64-mingw32\lib;G:\Software\MinGW\x86_64-w64-mingw32\l
                          ib
                 HOMEPATH=\Users\HP
          NVTOOLSEXT_PATH=C:\Program Files\NVIDIA Corporation\NvToolsExt\
                     PATH=C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Program
                          Files\NVIDIA GPU Computing Toolkit\CUDA\v9.0\bin;C:\Program
                          Files\NVIDIA GPU Computing Toolkit\CUDA\v9.0\libnvvp;c:\Rtools\bin;c:\
                          Rtools\mingw_32\bin;C:\ProgramData\Oracle\Java\javapath;C:\MinGW\bin;C
                          :\MinGW\libexec\gcc\x86_64-pc-mingw32\4.9.2;G:\Software\MinGW\bin;G:\S
                          oftware\MinGW\libexec\gcc\x86_64-pc-mingw32\4.9.2;C:\Program
                          Files\Broadcom\Broadcom 802.11 Network Adapter;C:\Program Files
                          (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\window
                          s\system32;C:\windows;C:\windows\System32\Wbem;C:\windows\System32\Win
                          dowsPowerShell\v1.0\;C:\Program Files (x86)\Intel\Intel(R) Management
                          Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management
                          Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management
                          Engine Components\IPT;C:\Program Files\Intel\Intel(R) Management
                          Engine Components\IPT;C:\Program
                          Files\Intel\IntelSGXPSW\bin\x64\Release\;C:\Program Files\Intel\IntelS
                          GXPSW\bin\win32\Release\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\Sys
                          tem32\Wbem;C:\Program Files (x86)\Java\jdk1.8.0_65;C:\WINDOWS\System32
                          \WindowsPowerShell\v1.0\;C:\Android;C:\Windows\System32;C:\Program
                          Files (x86)\Java\jdk1.8.0_65\bin;C:\Program
                          Files\Java\jdk1.8.0_121\bin;C:\Program Files (x86)\NVIDIA Corporation\
                          PhysX\Common;G:\Software\nodejs\;G:\Software\cudnn-9.0-windows10-x64-v
                          7\cuda;;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WIN
                          DOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\
                          Program Files\Microsoft VS Code\bin;C:\Users\HP\AppData\Local\Microsof
                          t\WindowsApps;C:\Modeltech_eval_5.5e\win32;C:\Modeltech_5.5e\win32;C:\
                          Python34;C:\MinGW\bin;C:\Program
                          Files\Java\jdk1.8.0_121\bin;F:\android-sdk\platform-tools;C:\Users\HP\
                          AppData\Roaming\npm;C:\Users\HP\AppData\Local\Microsoft\WindowsApps;C:
                          \cudnn-9.1-windows10-x64-v7\cuda;
             PSMODULEPATH=C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules\
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>

     active environment : None
       user config file : C:\Users\HP\.condarc
 populated config files :
          conda version : 4.5.11
    conda-build version : 3.15.1
         python version : 3.7.0.final.0
       base environment : G:\Software\Anaconda31  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/win-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/win-64
                          https://repo.anaconda.com/pkgs/pro/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : G:\Software\Anaconda31\pkgs
                          C:\Users\HP\AppData\Local\conda\conda\pkgs
       envs directories : G:\Software\Anaconda31\envs
                          C:\Users\HP\AppData\Local\conda\conda\envs
                          C:\Users\HP\.conda\envs
               platform : win-64
             user-agent : conda/4.5.11 requests/2.19.1 CPython/3.7.0 Windows/10 Windows/10.0.17134
          administrator : False
             netrc file : None
           offline mode : False

An unexpected error has occurred. Conda has prepared the above report.

##### Operating System:
Windows 10 
##### `conda info`
C:\Users\HP>conda info

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "G:\Software\Anaconda31\lib\site-packages\conda\exceptions.py", line 819, in __call__
        return func(*args, **kwargs)
      File "G:\Software\Anaconda31\lib\site-packages\conda\cli\main.py", line 74, in _main
        context.__init__(argparse_args=args)
      File "G:\Software\Anaconda31\lib\site-packages\conda\base\context.py", line 237, in __init__
        argparse_args=argparse_args)
      File "G:\Software\Anaconda31\lib\site-packages\conda\common\configuration.py", line 722, in __init__
        self._set_search_path(search_path)
      File "G:\Software\Anaconda31\lib\site-packages\conda\common\configuration.py", line 728, in _set_search_path
        self._set_raw_data(load_file_configs(search_path))
      File "G:\Software\Anaconda31\lib\site-packages\conda\common\configuration.py", line 369, in load_file_configs
        raw_data = odict(kv for kv in chain.from_iterable(load_paths))
      File "G:\Software\Anaconda31\lib\site-packages\conda\common\configuration.py", line 369, in <genexpr>
        raw_data = odict(kv for kv in chain.from_iterable(load_paths))
      File "G:\Software\Anaconda31\lib\site-packages\conda\common\configuration.py", line 344, in _file_yaml_loader
        yield fullpath, YamlRawParameter.make_raw_parameters_from_file(fullpath)
      File "G:\Software\Anaconda31\lib\site-packages\conda\common\configuration.py", line 332, in make_raw_parameters_from_file
        ruamel_yaml = yaml_load(fh)
      File "G:\Software\Anaconda31\lib\site-packages\conda\common\serialize.py", line 54, in yaml_load
        return yaml.load(string, Loader=yaml.RoundTripLoader, version="1.2")
      File "G:\Software\Anaconda31\lib\site-packages\ruamel_yaml\main.py", line 638, in load
        loader = Loader(stream, version, preserve_quotes=preserve_quotes)
      File "G:\Software\Anaconda31\lib\site-packages\ruamel_yaml\loader.py", line 59, in __init__
        Reader.__init__(self, stream, loader=self)
      File "G:\Software\Anaconda31\lib\site-packages\ruamel_yaml\reader.py", line 80, in __init__
        self.stream = stream  # type: Any  # as .read is called
      File "G:\Software\Anaconda31\lib\site-packages\ruamel_yaml\reader.py", line 125, in stream
        self.determine_encoding()
      File "G:\Software\Anaconda31\lib\site-packages\ruamel_yaml\reader.py", line 180, in determine_encoding
        self.update(1)
      File "G:\Software\Anaconda31\lib\site-packages\ruamel_yaml\reader.py", line 266, in update
        self.check_printable(data)
      File "G:\Software\Anaconda31\lib\site-packages\ruamel_yaml\reader.py", line 233, in check_printable
        'unicode', "special characters are not allowed")
    ruamel_yaml.reader.ReaderError: unacceptable character #x0000: special characters are not allowed
      in "C:\Users\HP\.condarc", position 0

`$ G:\Software\Anaconda31\Scripts\conda info`

An unexpected error has occurred. Conda has prepared the above report.
```

```

##### `conda list --show-channel-urls`

```
Same error report as generated to conda -info
```

**Comment by goanpeca** [comment]
Please manually remove the file `C:\Users\HP\.condarc` and try again
