### ISSUE TITLE
Cannot Launch Navigator

### ISSUE THREAD

**Issue by rmchoi** [ContinuumIO/anaconda-issues#10151]
### Actual Behavior
**The following error message is displayed:**

Navigator Error

An unexpected error occurred on Navigator start-up

Report

Please report this issue in the anaconda  issue tracker  

Main Error

expected str, bytes or os.PathLike object, not NoneType

Traceback

Traceback (most recent call last):
  File "C:\Users\choirya\AppData\Local\Continuum\anaconda3\lib\site-packages\anaconda_navigator\exceptions.py", line 75, in exception_handler
    return_value = func(*args, **kwargs)
  File "C:\Users\choirya\AppData\Local\Continuum\anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 150, in start_app
    window = run_app(splash)
  File "C:\Users\choirya\AppData\Local\Continuum\anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 65, in run_app
    window = MainWindow(splash=splash, tab_project=False)
  File "C:\Users\choirya\AppData\Local\Continuum\anaconda3\lib\site-packages\anaconda_navigator\widgets\main_window.py", line 168, in __init__
    self.api = AnacondaAPI()
  File "C:\Users\choirya\AppData\Local\Continuum\anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 2294, in AnacondaAPI
    ANACONDA_API = _AnacondaAPI()
  File "C:\Users\choirya\AppData\Local\Continuum\anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 91, in __init__
    self._conda_api = CondaAPI()
  File "C:\Users\choirya\AppData\Local\Continuum\anaconda3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 1767, in CondaAPI
    CONDA_API = _CondaAPI()
  File "C:\Users\choirya\AppData\Local\Continuum\anaconda3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 353, in __init__
    self.sys_rc_path = join(self.ROOT_PREFIX, '.condarc')
  File "C:\Users\choirya\AppData\Local\Continuum\anaconda3\lib\ntpath.py", line 76, in join
    path = os.fspath(path)
TypeError: expected str, bytes or os.PathLike object, not NoneType

### Expected Behavior
Anaconda Navigator should be launched successfully.

### Steps to Reproduce
Launch Anaconda Navigator

##### Anaconda or Miniconda version:
5.3.0

##### Operating System:
Windows 10

##### `conda info`

```
C:\Users\choirya>conda info

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "C:\Users\choirya\AppData\Local\Continuum\anaconda3\lib\site-packages
\conda\exceptions.py", line 819, in __call__
        return func(*args, **kwargs)
      File "C:\Users\choirya\AppData\Local\Continuum\anaconda3\lib\site-packages
\conda\cli\main.py", line 74, in _main
        context.__init__(argparse_args=args)
      File "C:\Users\choirya\AppData\Local\Continuum\anaconda3\lib\site-packages
\conda\base\context.py", line 237, in __init__
        argparse_args=argparse_args)
      File "C:\Users\choirya\AppData\Local\Continuum\anaconda3\lib\site-packages
\conda\common\configuration.py", line 722, in __init__
        self._set_search_path(search_path)
      File "C:\Users\choirya\AppData\Local\Continuum\anaconda3\lib\site-packages
\conda\common\configuration.py", line 728, in _set_search_path
        self._set_raw_data(load_file_configs(search_path))
      File "C:\Users\choirya\AppData\Local\Continuum\anaconda3\lib\site-packages
\conda\common\configuration.py", line 369, in load_file_configs
        raw_data = odict(kv for kv in chain.from_iterable(load_paths))
      File "C:\Users\choirya\AppData\Local\Continuum\anaconda3\lib\site-packages
\conda\common\configuration.py", line 369, in <genexpr>
        raw_data = odict(kv for kv in chain.from_iterable(load_paths))
      File "C:\Users\choirya\AppData\Local\Continuum\anaconda3\lib\site-packages
\conda\common\configuration.py", line 344, in _file_yaml_loader
        yield fullpath, YamlRawParameter.make_raw_parameters_from_file(fullpath)

      File "C:\Users\choirya\AppData\Local\Continuum\anaconda3\lib\site-packages
\conda\common\configuration.py", line 332, in make_raw_parameters_from_file
        ruamel_yaml = yaml_load(fh)
      File "C:\Users\choirya\AppData\Local\Continuum\anaconda3\lib\site-packages
\conda\common\serialize.py", line 54, in yaml_load
        return yaml.load(string, Loader=yaml.RoundTripLoader, version="1.2")
      File "C:\Users\choirya\AppData\Local\Continuum\anaconda3\lib\site-packages
\ruamel_yaml\main.py", line 638, in load
        loader = Loader(stream, version, preserve_quotes=preserve_quotes)
      File "C:\Users\choirya\AppData\Local\Continuum\anaconda3\lib\site-packages
\ruamel_yaml\loader.py", line 59, in __init__
        Reader.__init__(self, stream, loader=self)
      File "C:\Users\choirya\AppData\Local\Continuum\anaconda3\lib\site-packages
\ruamel_yaml\reader.py", line 80, in __init__
        self.stream = stream  # type: Any  # as .read is called
      File "C:\Users\choirya\AppData\Local\Continuum\anaconda3\lib\site-packages
\ruamel_yaml\reader.py", line 125, in stream
        self.determine_encoding()
      File "C:\Users\choirya\AppData\Local\Continuum\anaconda3\lib\site-packages
\ruamel_yaml\reader.py", line 180, in determine_encoding
        self.update(1)
      File "C:\Users\choirya\AppData\Local\Continuum\anaconda3\lib\site-packages
\ruamel_yaml\reader.py", line 266, in update
        self.check_printable(data)
      File "C:\Users\choirya\AppData\Local\Continuum\anaconda3\lib\site-packages
\ruamel_yaml\reader.py", line 233, in check_printable
        'unicode', "special characters are not allowed")
    ruamel_yaml.reader.ReaderError: unacceptable character #x0000: special chara
cters are not allowed
      in "C:\Users\choirya\.condarc", position 0

`$ C:\Users\choirya\AppData\Local\Continuum\anaconda3\Scripts\conda info`


An unexpected error has occurred. Conda has prepared the above report.
If submitted, this report will be used by core maintainers to improve
future releases of conda.
Would you like conda to send this report to the core maintainers?
[y/N]:
```

##### `conda list --show-channel-urls`

```
C:\Users\choirya>conda list --show-channel-urls

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "C:\Users\choirya\AppData\Local\Continuum\anaconda3\lib\site-packages
\conda\exceptions.py", line 819, in __call__
        return func(*args, **kwargs)
      File "C:\Users\choirya\AppData\Local\Continuum\anaconda3\lib\site-packages
\conda\cli\main.py", line 74, in _main
        context.__init__(argparse_args=args)
      File "C:\Users\choirya\AppData\Local\Continuum\anaconda3\lib\site-packages
\conda\base\context.py", line 237, in __init__
        argparse_args=argparse_args)
      File "C:\Users\choirya\AppData\Local\Continuum\anaconda3\lib\site-packages
\conda\common\configuration.py", line 722, in __init__
        self._set_search_path(search_path)
      File "C:\Users\choirya\AppData\Local\Continuum\anaconda3\lib\site-packages
\conda\common\configuration.py", line 728, in _set_search_path
        self._set_raw_data(load_file_configs(search_path))
      File "C:\Users\choirya\AppData\Local\Continuum\anaconda3\lib\site-packages
\conda\common\configuration.py", line 369, in load_file_configs
        raw_data = odict(kv for kv in chain.from_iterable(load_paths))
      File "C:\Users\choirya\AppData\Local\Continuum\anaconda3\lib\site-packages
\conda\common\configuration.py", line 369, in <genexpr>
        raw_data = odict(kv for kv in chain.from_iterable(load_paths))
      File "C:\Users\choirya\AppData\Local\Continuum\anaconda3\lib\site-packages
\conda\common\configuration.py", line 344, in _file_yaml_loader
        yield fullpath, YamlRawParameter.make_raw_parameters_from_file(fullpath)

      File "C:\Users\choirya\AppData\Local\Continuum\anaconda3\lib\site-packages
\conda\common\configuration.py", line 332, in make_raw_parameters_from_file
        ruamel_yaml = yaml_load(fh)
      File "C:\Users\choirya\AppData\Local\Continuum\anaconda3\lib\site-packages
\conda\common\serialize.py", line 54, in yaml_load
        return yaml.load(string, Loader=yaml.RoundTripLoader, version="1.2")
      File "C:\Users\choirya\AppData\Local\Continuum\anaconda3\lib\site-packages
\ruamel_yaml\main.py", line 638, in load
        loader = Loader(stream, version, preserve_quotes=preserve_quotes)
      File "C:\Users\choirya\AppData\Local\Continuum\anaconda3\lib\site-packages
\ruamel_yaml\loader.py", line 59, in __init__
        Reader.__init__(self, stream, loader=self)
      File "C:\Users\choirya\AppData\Local\Continuum\anaconda3\lib\site-packages
\ruamel_yaml\reader.py", line 80, in __init__
        self.stream = stream  # type: Any  # as .read is called
      File "C:\Users\choirya\AppData\Local\Continuum\anaconda3\lib\site-packages
\ruamel_yaml\reader.py", line 125, in stream
        self.determine_encoding()
      File "C:\Users\choirya\AppData\Local\Continuum\anaconda3\lib\site-packages
\ruamel_yaml\reader.py", line 180, in determine_encoding
        self.update(1)
      File "C:\Users\choirya\AppData\Local\Continuum\anaconda3\lib\site-packages
\ruamel_yaml\reader.py", line 266, in update
        self.check_printable(data)
      File "C:\Users\choirya\AppData\Local\Continuum\anaconda3\lib\site-packages
\ruamel_yaml\reader.py", line 233, in check_printable
        'unicode', "special characters are not allowed")
    ruamel_yaml.reader.ReaderError: unacceptable character #x0000: special chara
cters are not allowed
      in "C:\Users\choirya\.condarc", position 0

`$ C:\Users\choirya\AppData\Local\Continuum\anaconda3\Scripts\conda list --show-
channel-urls`

  environment variables:
                 CIO_TEST=<not set>
               CONDA_ROOT=C:\Users\choirya\AppData\Local\Continuum\anaconda3
                 HOMEPATH=\
                     PATH=C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbe
m;C:\WINDOWS\Sys
                          tem32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\Wind
owsPowerShell\v1
                          .0\;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Pro
gram Files (x86)
                          \Plantronics\Spokes3G\;C:\Users\choirya\AppData\Local\
Continuum\anacon
                          da3;C:\Users\choirya\AppData\Local\Continuum\anaconda3
\Library\mingw-w
                          64\bin;C:\Users\choirya\AppData\Local\Continuum\anacon
da3\Library\usr\
                          bin;C:\Users\choirya\AppData\Local\Continuum\anaconda3
\Library\bin;C:\
                          Users\choirya\AppData\Local\Continuum\anaconda3\Script
s;C:\Users\choir
                          ya\.anaconda\navigator\scripts
             PSMODULEPATH=C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules\;C:
\Program
                          Files\Microsoft Application Virtualization\Client\
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>

     active environment : None
       user config file : C:\Users\choirya\.condarc
 populated config files :
          conda version : 4.5.11
    conda-build version : 3.15.1
         python version : 3.7.0.final.0
       base environment : C:\Users\choirya\AppData\Local\Continuum\anaconda3  (w
ritable)
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/win-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/win-64
                          https://repo.anaconda.com/pkgs/pro/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\Users\choirya\AppData\Local\Continuum\anaconda3\pkg
s
                          C:\Users\choirya\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\choirya\AppData\Local\Continuum\anaconda3\env
s
                          C:\Users\choirya\AppData\Local\conda\conda\envs
                          C:\Users\choirya\.conda\envs
               platform : win-64
             user-agent : conda/4.5.11 requests/2.19.1 CPython/3.7.0 Windows/7 W
indows/6.1.7601
          administrator : False
             netrc file : None
           offline mode : False


An unexpected error has occurred. Conda has prepared the above report.
If submitted, this report will be used by core maintainers to improve
future releases of conda.
Would you like conda to send this report to the core maintainers?
[y/N]:

```

**Comment by goanpeca** [comment]
Please manually remove this file `C:\Users\choirya\.condarc` and try again
