### ISSUE TITLE
Error:-( expected str, bytes or os.PathLike object, not NoneType ) with Anaconda installation 

### ISSUE THREAD

**Issue by abhijit-16** [ContinuumIO/anaconda-issues#10156]
### Actual Behavior

After Installing a Anaconda 5.3 version I am getting this error for anaconda Navigator.
------------------------
Navigator Error
An unexpected error occurred on Navigator start-up
Report
Please report this issue in the anaconda issue tracker 
Main Error

expected str, bytes or os.PathLike object, not NoneType

Traceback

Traceback (most recent call last):
  File "C:\Users\joshiabh\AppData\Local\Continuum\anaconda3\lib\site-packages\anaconda_navigator\exceptions.py", line 75, in exception_handler
    return_value = func(*args, **kwargs)
  File "C:\Users\joshiabh\AppData\Local\Continuum\anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 150, in start_app
    window = run_app(splash)
  File "C:\Users\joshiabh\AppData\Local\Continuum\anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 65, in run_app
    window = MainWindow(splash=splash, tab_project=False)
  File "C:\Users\joshiabh\AppData\Local\Continuum\anaconda3\lib\site-packages\anaconda_navigator\widgets\main_window.py", line 168, in __init__
    self.api = AnacondaAPI()
  File "C:\Users\joshiabh\AppData\Local\Continuum\anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 2294, in AnacondaAPI
    ANACONDA_API = _AnacondaAPI()
  File "C:\Users\joshiabh\AppData\Local\Continuum\anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 91, in __init__
    self._conda_api = CondaAPI()
  File "C:\Users\joshiabh\AppData\Local\Continuum\anaconda3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 1767, in CondaAPI
    CONDA_API = _CondaAPI()
  File "C:\Users\joshiabh\AppData\Local\Continuum\anaconda3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 353, in __init__
    self.sys_rc_path = join(self.ROOT_PREFIX, '.condarc')
  File "C:\Users\joshiabh\AppData\Local\Continuum\anaconda3\lib\ntpath.py", line 76, in join
    path = os.fspath(path)
TypeError: expected str, bytes or os.PathLike object, not NoneType

--------------------------------

when I tried to check Anaconda prompt I am getting this error 
--------------------------
    conda-build version : 3.15.1
         python version : 3.7.0.final.0
       base environment : C:\Users\joshiabh\AppData\Local\Continuum\anaconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/win-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/win-64
                          https://repo.anaconda.com/pkgs/pro/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\Users\joshiabh\AppData\Local\Continuum\anaconda3\pkgs
                          C:\Users\joshiabh\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\joshiabh\AppData\Local\Continuum\anaconda3\envs
                          C:\Users\joshiabh\AppData\Local\conda\conda\envs
                          C:\Users\joshiabh\.conda\envs
               platform : win-64
             user-agent : conda/4.5.11 requests/2.19.1 CPython/3.7.0 Windows/10 Windows/10.0.16299
          administrator : False
             netrc file : None
           offline mode : False

An unexpected error has occurred. Conda has prepared the above report.
If submitted, this report will be used by core maintainers to improve
future releases of conda.
Would you like conda to send this report to the core maintainers?
[y/N]:

-----------------------------

##### Anaconda or Miniconda version:

Anaconda 5.3 version

##### Operating System:
Windows 10 Enterprise 

Can you pls help me how to fix issue ?

Thanks

**Comment by goanpeca** [comment]
@abhijit-16 what type of install did you use?

Could uninstall and reinstall and use a location like:

`C:\Users\joshiabh\anaconda3\`

Instead of:

`C:\Users\joshiabh\AppData\Local\Continuum\anaconda3\` ?

**Comment by abhijit-16** [comment]
Hello Gonzalo,

I am using Anaconda3-5.3.0-Windows-x86_64.exe as an installation

I just did what you said (change the directory of installation) . no change
getting same error:(

Regards
Abhijit

**Comment by goanpeca** [comment]
If you open the `Anaconda Prompt` do you see some error?

**Comment by abhijit-16** [comment]
yes I see the error

**Comment by goanpeca** [comment]
@abhijit-16 in that case it seems that there was an installation error

**Comment by abhijit-16** [comment]
I did reinstallation but facing same error. I didn't change anything during installation do you want me to change anything during installation

**Comment by goanpeca** [comment]
Thoughts @kalefranz / @nehaljwani ?

**Comment by NareshGarg99** [comment]
is there is any solution for this error if i installed updated  version 2 times for change settings during installtion

**Comment by im-amir** [comment]
Hey @abhijit-16 
Please delete this file C:\Users\anmol singh\.condarc and try again

This should work!

**Comment by goanpeca** [comment]
@abhijit-16 did you try deleting `C:\Users\joshiabh\.condarc` ?

**Comment by ankitkpehlajani** [comment]
delete condarc file this worked for me

**Comment by omkardongre** [comment]
Deleting condarc really worked .
Thank you boss

**Comment by yogeshsoni92** [comment]
Deleting condarc worked .
Thanks

**Comment by rohitgupta** [comment]
Hello ,

Me too getting Error unable to see condarc file.

Main Error

expected str, bytes or os.PathLike object, not NoneType


Traceback

Traceback (most recent call last):
  File "C:\Users\rohit\Anaconda3\lib\site-packages\anaconda_navigator\exceptions.py", line 75, in exception_handler
    return_value = func(*args, **kwargs)
  File "C:\Users\rohit\Anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 150, in start_app
    window = run_app(splash)
  File "C:\Users\rohit\Anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 65, in run_app
    window = MainWindow(splash=splash, tab_project=False)
  File "C:\Users\rohit\Anaconda3\lib\site-packages\anaconda_navigator\widgets\main_window.py", line 168, in __init__
    self.api = AnacondaAPI()
  File "C:\Users\rohit\Anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 2294, in AnacondaAPI
    ANACONDA_API = _AnacondaAPI()
  File "C:\Users\rohit\Anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 91, in __init__
    self._conda_api = CondaAPI()
  File "C:\Users\rohit\Anaconda3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 1767, in CondaAPI
    CONDA_API = _CondaAPI()
  File "C:\Users\rohit\Anaconda3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 353, in __init__
    self.sys_rc_path = join(self.ROOT_PREFIX, '.condarc')
  File "C:\Users\rohit\Anaconda3\lib\ntpath.py", line 76, in join
    path = os.fspath(path)
TypeError: expected str, bytes or os.PathLike object, not NoneType


Please help on these.

**Comment by Venkatadattak** [comment]
> delete condarc file this worked for me

Yup this worked for me too ,Thank you

**Comment by rohitgupta** [comment]
We are unable to update anaconda after this.

Thanks and Regards
Rohit Gupta.

**Comment by dlee992** [comment]
I tried to remove .condarc, but not work. Then I tried to set `export CONDA_PREFIX=/my/path/miniconda3`, which works for me.

**Comment by BitCalSaul** [comment]
> export CONDA_PREFIX=

Bro, you save my life!!!

**Comment by zhuoqun-chen** [comment]
> I tried to remove .condarc, but not work. Then I tried to set `export CONDA_PREFIX=/my/path/miniconda3`, which works for me.

life saver!

**Comment by nipunsadvilkar** [comment]
Make sure to add `export CONDA_PREFIX=/my/path/miniconda3` in your `.bashrc` or `.zshrc` or the shell environment you're using
