### ISSUE TITLE
Remove dependence on ncurses in anaconda base?

### ISSUE THREAD

**Issue by yaroslavvb** [ContinuumIO/anaconda-issues#10159]
Yesterday, `conda create` was failing because ncurses was corrupted (error below).  This kind of error can block the whole world from using Anaconda, many of whom don't need this particular package. I'm wondering if it makes sense to reduce a set of base packages to a smaller, better tested, subset.

```
conda create -n jupyter python=3.6 -y
Solving environment: done

## Package Plan ##

  environment location: /Users/yaroslavvb/anaconda3/envs/jupyter

  added / updated specs: 
    - python=3.6


The following NEW packages will be INSTALLED:

    ca-certificates: 2018.03.07-0           
    certifi:         2018.8.24-py36_1       
    libcxx:          4.0.1-h579ed51_0       
    libcxxabi:       4.0.1-hebd6815_0       
    libedit:         3.1.20170329-hb402a30_2
    libffi:          3.2.1-h475c297_4       
    ncurses:         6.1-h0a44026_0         
    openssl:         1.0.2p-h1de35cc_0      
    pip:             10.0.1-py36_0          
    python:          3.6.6-hc167b69_0       
    readline:        7.0-h1de35cc_5         
    setuptools:      40.4.3-py36_0          
    sqlite:          3.25.2-ha441bb4_0      
    tk:              8.6.8-ha441bb4_0       
    wheel:           0.32.0-py36_0          
    xz:              5.2.4-h1de35cc_4       
    zlib:            1.2.11-hf3cbc9b_2      

Preparing transaction: done
Verifying transaction: failed

CondaVerificationError: The package for ncurses located at /Users/yaroslavvb/anaconda3/pkgs/ncurses-6.1-h0a44026_0
appears to be corrupted. The path 'share/terminfo/69/iTerm.app'
specified in the package manifest cannot be found.

CondaVerificationError: The package for ncurses located at /Users/yaroslavvb/anaconda3/pkgs/ncurses-6.1-h0a44026_0
appears to be corrupted. The path 'share/terminfo/69/iTerm2.app'
specified in the package manifest cannot be found.
```

**Comment by mingwandroid** [comment]
Everyone using conda needs ncurses and your problem is likely not going see you report. Conda clean --all followed by conda install ncurses -c defaults ncurses --force should see you right.

**Comment by yaroslavvb** [comment]
(btw, looks like ncurses distribution was fixed upstream, so trying today, this error no longer happens)

**Comment by yaroslavvb** [comment]
I have tried conda clean -a, I think the issue is with upstream package, yesterday it was trying to install `6.1-h0a44026_0` which has this error, today it's installing `ncurses-6.1` which doesn't

**Comment by mingwandroid** [comment]
This was only ever a local problem there's nothing wrong with the packages.

**Comment by yaroslavvb** [comment]
you may be right, I can no longer reproduce it today

**Comment by mingwandroid** [comment]
We test our software extensively BTW, our main weak point has been when ABI breaking changes are introduced by upstream by mistake against their stated policy (or our best guess at that) but we have something in place for that too now.

**Comment by mingwandroid** [comment]
And clearly there's something nasty going on somewhere that caused this local issue, so we're not totally bug free, but no one is.

**Comment by rswgnu** [comment]
I am seeing a similar problem with the latest release of Miniconda under 64-bit Linux (using the latest non-insider Windows Subsystem for Linux).  ncurses-6.1 fails to install correctly.  Another message mentioned that libedit needed ncurses-5.9, creating an incompatible dependency.  I did get some environments built by pinning ncurses to version 5.9 but now when trying to create a new environment today, I am seeing this error.  It would be tremendous to get this resolved:

    Traceback (most recent call last):
      File "/c/work/Miniconda-linux/lib/python3.7/site-packages/conda/exceptions.py", line 1003, in __call__
        return func(*args, **kwargs)
      File "/c/work/Miniconda-linux/lib/python3.7/site-packages/conda/cli/main.py", line 84, in _main
        exit_code = do_call(args, p)
      File "/c/work/Miniconda-linux/lib/python3.7/site-packages/conda/cli/conda_argparse.py", line 82, in do_call
        exit_code = getattr(module, func_name)(args, parser)
      File "/c/work/Miniconda-linux/lib/python3.7/site-packages/conda/cli/main_create.py", line 37, in execute
        install(args, parser, 'create')
      File "/c/work/Miniconda-linux/lib/python3.7/site-packages/conda/cli/install.py", line 275, in install
        handle_txn(unlink_link_transaction, prefix, args, newenv)
      File "/c/work/Miniconda-linux/lib/python3.7/site-packages/conda/cli/install.py", line 304, in handle_txn
        unlink_link_transaction.execute()
      File "/c/work/Miniconda-linux/lib/python3.7/site-packages/conda/core/link.py", line 236, in execute
        self.verify()
      File "/c/work/Miniconda-linux/lib/python3.7/site-packages/conda/common/io.py", line 88, in decorated
        return f(*args, **kwds)
      File "/c/work/Miniconda-linux/lib/python3.7/site-packages/conda/core/link.py", line 213, in verify
        self.prepare()
      File "/c/work/Miniconda-linux/lib/python3.7/site-packages/conda/core/link.py", line 205, in prepare
        stp.remove_specs, stp.update_specs)
      File "/c/work/Miniconda-linux/lib/python3.7/site-packages/conda/core/link.py", line 283, in _prepare
        for pkg_info in packages_info_to_link)
      File "/c/work/Miniconda-linux/lib/python3.7/site-packages/conda/core/link.py", line 283, in <genexpr>
        for pkg_info in packages_info_to_link)
      File "/c/work/Miniconda-linux/lib/python3.7/site-packages/conda/core/link.py", line 55, in determine_link_type
        if hardlink_supported(source_test_file, target_prefix):
      File "/c/work/Miniconda-linux/lib/python3.7/site-packages/conda/_vendor/auxlib/decorators.py", line 59, in _memoized_func
        result = func(*args, **kwargs)
      File "/c/work/Miniconda-linux/lib/python3.7/site-packages/conda/gateways/disk/test.py", line 46, in hardlink_supported
        assert isfile(source_file), source_file
    AssertionError: /c/work/Miniconda-linux/pkgs/ncurses-6.1-he6710b0_1/info/index.json

**Comment by mingwandroid** [comment]
The problem here is that Linux is case sensitive and Windows (including wsl, but folders can be marked as requiring case sensitivity now on Windows) is not. Your issue is not related to this issue at all and had already been reported and appropriate workarounds given. I'm on my phone so it's tricky for me to find references but they're out there.

**Comment by rswgnu** [comment]
Than you.  I will have a look.

-- Bob
