### ISSUE TITLE
Anaconda 2 root prefix 

### ISSUE THREAD

**Issue by david2588e** [ContinuumIO/anaconda-issues#10162]
### Actual Behavior

Navigator Error

An unexpected error occurred on Navigator start-up

Report

Please report this issue in the anaconda issue tracker

Main Error

'root_prefix'
Traceback

Traceback (most recent call last):
  File "C:\Users\Liu\Anaconda2\lib\site-packages\anaconda_navigator\exceptions.py", line 75, in exception_handler
    return_value = func(*args, **kwargs)
  File "C:\Users\Liu\Anaconda2\lib\site-packages\anaconda_navigator\app\start.py", line 150, in start_app
    window = run_app(splash)
  File "C:\Users\Liu\Anaconda2\lib\site-packages\anaconda_navigator\app\start.py", line 65, in run_app
    window = MainWindow(splash=splash, tab_project=False)
  File "C:\Users\Liu\Anaconda2\lib\site-packages\anaconda_navigator\widgets\main_window.py", line 163, in __init__
    self.api = AnacondaAPI()
  File "C:\Users\Liu\Anaconda2\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 2185, in AnacondaAPI
    ANACONDA_API = _AnacondaAPI()
  File "C:\Users\Liu\Anaconda2\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 89, in __init__
    self._conda_api = CondaAPI()
  File "C:\Users\Liu\Anaconda2\lib\site-packages\anaconda_navigator\api\conda_api.py", line 1714, in CondaAPI
    CONDA_API = _CondaAPI()
  File "C:\Users\Liu\Anaconda2\lib\site-packages\anaconda_navigator\api\conda_api.py", line 350, in __init__
    self.set_conda_prefix(info=get_conda_info())
  File "C:\Users\Liu\Anaconda2\lib\site-packages\anaconda_navigator\api\conda_api.py", line 505, in set_conda_prefix
    self.ROOT_PREFIX = info['root_prefix']
KeyError: 'root_prefix'

##### `conda info`

```

```

##### `conda list --show-channel-urls`

```

```

**Comment by goanpeca** [comment]
@david2588e could you open the `Anaconda Prompt` and provide the information of running

`conda info`

and

`conda list --show-channel-urls`

**Comment by urscion** [comment]
I also have this same issue. I installed miniconda and added anaconda-navigator. 


     active environment : base
    active env location : D:\Users\abcd\AppData\Local\Continuum\miniconda3
            shell level : 1
       user config file : D:\Users\abcd\.condarc
 populated config files : D:\Users\abcd\.condarc
          conda version : 4.5.11
    conda-build version : 3.16.3
         python version : 3.7.0.final.0
       base environment : D:\Users\abcd\AppData\Local\Continuum\miniconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/win-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/win-64
                          https://repo.anaconda.com/pkgs/pro/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : D:\Users\abcd\AppData\Local\Continuum\miniconda3\pkgs
                          D:\Users\abcd\AppData\Local\conda\conda\pkgs
       envs directories : D:\Users\abcd\AppData\Local\Continuum\miniconda3\envs
                          D:\Users\abcd\AppData\Local\conda\conda\envs
                          D:\Users\abcd\.conda\envs
               platform : win-64
             user-agent : conda/4.5.11 requests/2.19.1 CPython/3.7.0 Windows/7 Windows/6.1.7601
          administrator : False
             netrc file : None
           offline mode : False

# packages in environment at D:\Users\abcd\AppData\Local\Continuum\miniconda3:
#
# Name                    Version                   Build  Channel
anaconda-client           1.7.2                    py37_0    defaults
anaconda-navigator        1.9.2                    py37_0    defaults
asn1crypto                0.24.0                   py37_0    defaults
beautifulsoup4            4.6.3                    py37_0    defaults
bzip2                     1.0.6                hfa6e2cd_5    defaults
ca-certificates           2018.03.07                    0    defaults
certifi                   2018.10.15               py37_0    defaults
cffi                      1.11.5           py37h74b6da3_1    defaults
chardet                   3.0.4                    py37_1    defaults
clyent                    1.2.2                    py37_1    defaults
conda                     4.5.11                   py37_0    defaults
conda-build               3.16.3                   py37_0    defaults
conda-env                 2.6.0                         1    defaults
console_shortcut          0.1.1                         3    defaults
cryptography              2.3.1            py37h74b6da3_0    defaults
decorator                 4.3.0                    py37_0    defaults
filelock                  3.0.10                   py37_0    defaults
freetype                  2.9.1                ha9979f8_1    defaults
glob2                     0.6                      py37_1    defaults
icu                       58.2                 ha66f8fd_1    defaults
idna                      2.7                      py37_0    defaults
ipython_genutils          0.2.0                    py37_0    defaults
jinja2                    2.10                     py37_0    defaults
jpeg                      9b                   hb83a4c4_2    defaults
jsonschema                2.6.0                    py37_0    defaults
jupyter_core              4.4.0                    py37_0    defaults
libarchive                3.3.3                h798a506_0    defaults
libiconv                  1.15                 h1df5818_7    defaults
libpng                    1.6.34               h79bbb47_0    defaults
libtiff                   4.0.9                h36446d0_2    defaults
libxml2                   2.9.8                hadb2253_1    defaults
lz4-c                     1.8.1.2              h2fa13f4_0    defaults
lzo                       2.10                 h6df0209_2    defaults
markupsafe                1.0              py37hfa6e2cd_1    defaults
menuinst                  1.4.14           py37hfa6e2cd_0    defaults
nbformat                  4.4.0                    py37_0    defaults
olefile                   0.46                     py37_0    defaults
openssl                   1.0.2p               hfa6e2cd_0    defaults
pillow                    5.2.0            py37h08bbbbd_0    defaults
pip                       10.0.1                   py37_0    defaults
pkginfo                   1.4.2                    py37_1    defaults
psutil                    5.4.7            py37hfa6e2cd_0    defaults
pycosat                   0.6.3            py37hfa6e2cd_0    defaults
pycparser                 2.18                     py37_1    defaults
pyopenssl                 18.0.0                   py37_0    defaults
pyqt                      5.9.2            py37h6538335_2    defaults
pysocks                   1.6.8                    py37_0    defaults
python                    3.7.0                hea74fb7_0    defaults
python-dateutil           2.7.5                    py37_0    defaults
python-libarchive-c       2.8                      py37_6    defaults
pytz                      2018.7                   py37_0    defaults
pywin32                   223              py37hfa6e2cd_1    defaults
pyyaml                    3.13             py37hfa6e2cd_0    defaults
qt                        5.9.6            vc14h62aca36_0    defaults
qtpy                      1.5.2                    py37_0    defaults
requests                  2.19.1                   py37_0    defaults
ruamel_yaml               0.15.46          py37hfa6e2cd_0    defaults
setuptools                40.2.0                   py37_0    defaults
sip                       4.19.8           py37h6538335_0    defaults
six                       1.11.0                   py37_1    defaults
sqlite                    3.25.2               hfa6e2cd_0    defaults
tk                        8.6.8                hfa6e2cd_0    defaults
tqdm                      4.28.1           py37h28b3542_0    defaults
traitlets                 4.3.2                    py37_0    defaults
urllib3                   1.23                     py37_0    defaults
vc                        14                   h0510ff6_3    defaults
vs2015_runtime            14.0.25123                    3    defaults
wheel                     0.31.1                   py37_0    defaults
win_inet_pton             1.0.1                    py37_1    defaults
wincertstore              0.2                      py37_0    defaults
xz                        5.2.4                h2fa13f4_4    defaults
yaml                      0.1.7                hc54c509_2    defaults
zlib                      1.2.11               h8395fce_2    defaults
