### ISSUE TITLE
Anaconda Navigator will not run

### ISSUE THREAD

**Issue by AkshayNakra25** [ContinuumIO/anaconda-issues#10190]
### Actual Behavior

Navigator Error
An unexpected error occurred on Navigator start-up
Report
Please report this issue in the anaconda issue tracker 
Main Error

object of type 'NoneType' has no len()

Traceback

Traceback (most recent call last):
  File "C:\Users\aksha\Anaconda2\lib\site-packages\anaconda_navigator\exceptions.py", line 75, in exception_handler
    return_value = func(*args, **kwargs)
  File "C:\Users\aksha\Anaconda2\lib\site-packages\anaconda_navigator\app\start.py", line 150, in start_app
    window = run_app(splash)
  File "C:\Users\aksha\Anaconda2\lib\site-packages\anaconda_navigator\app\start.py", line 65, in run_app
    window = MainWindow(splash=splash, tab_project=False)
  File "C:\Users\aksha\Anaconda2\lib\site-packages\anaconda_navigator\widgets\main_window.py", line 163, in __init__
    self.api = AnacondaAPI()
  File "C:\Users\aksha\Anaconda2\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 2185, in AnacondaAPI
    ANACONDA_API = _AnacondaAPI()
  File "C:\Users\aksha\Anaconda2\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 89, in __init__
    self._conda_api = CondaAPI()
  File "C:\Users\aksha\Anaconda2\lib\site-packages\anaconda_navigator\api\conda_api.py", line 1714, in CondaAPI
    CONDA_API = _CondaAPI()
  File "C:\Users\aksha\Anaconda2\lib\site-packages\anaconda_navigator\api\conda_api.py", line 353, in __init__
    self.sys_rc_path = join(self.ROOT_PREFIX, '.condarc')
  File "C:\Users\aksha\Anaconda2\lib\ntpath.py", line 65, in join
    result_drive, result_path = splitdrive(path)
  File "C:\Users\aksha\Anaconda2\lib\ntpath.py", line 115, in splitdrive
    if len(p) > 1:
TypeError: object of type 'NoneType' has no len()

### Expected Behavior

Should have opened Navigator.
Tried from the command line too. Same issue from there as well.

##### Operating System:
Windows 10

##### `conda info`

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "C:\Users\aksha\Anaconda2\lib\site-packages\conda\exceptions.py", line 819, in __call__
        return func(*args, **kwargs)
      File "C:\Users\aksha\Anaconda2\lib\site-packages\conda\cli\main.py", line 74, in _main
        context.__init__(argparse_args=args)
      File "C:\Users\aksha\Anaconda2\lib\site-packages\conda\base\context.py", line 236, in __init__
        argparse_args=argparse_args)
      File "C:\Users\aksha\Anaconda2\lib\site-packages\conda\common\configuration.py", line 722, in __init__
        self._set_search_path(search_path)
      File "C:\Users\aksha\Anaconda2\lib\site-packages\conda\common\configuration.py", line 728, in _set_search_path
        self._set_raw_data(load_file_configs(search_path))
      File "C:\Users\aksha\Anaconda2\lib\site-packages\conda\common\configuration.py", line 369, in load_file_configs
        raw_data = odict(kv for kv in chain.from_iterable(load_paths))
      File "C:\Users\aksha\Anaconda2\lib\collections.py", line 69, in __init__
        self.__update(*args, **kwds)
      File "C:\Users\aksha\Anaconda2\lib\_abcoll.py", line 571, in update
        for key, value in other:
      File "C:\Users\aksha\Anaconda2\lib\site-packages\conda\common\configuration.py", line 369, in <genexpr>
        raw_data = odict(kv for kv in chain.from_iterable(load_paths))
      File "C:\Users\aksha\Anaconda2\lib\site-packages\conda\common\configuration.py", line 344, in _file_yaml_loader
        yield fullpath, YamlRawParameter.make_raw_parameters_from_file(fullpath)
      File "C:\Users\aksha\Anaconda2\lib\site-packages\conda\common\configuration.py", line 332, in make_raw_parameters_from_file
        ruamel_yaml = yaml_load(fh)
      File "C:\Users\aksha\Anaconda2\lib\site-packages\conda\common\serialize.py", line 54, in yaml_load
        return yaml.load(string, Loader=yaml.RoundTripLoader, version="1.2")
      File "C:\Users\aksha\Anaconda2\lib\site-packages\ruamel_yaml\main.py", line 637, in load
        loader = Loader(stream, version, preserve_quotes=preserve_quotes)
      File "C:\Users\aksha\Anaconda2\lib\site-packages\ruamel_yaml\loader.py", line 59, in __init__
        Reader.__init__(self, stream, loader=self)
      File "C:\Users\aksha\Anaconda2\lib\site-packages\ruamel_yaml\reader.py", line 80, in __init__
        self.stream = stream  # type: Any  # as .read is called
      File "C:\Users\aksha\Anaconda2\lib\site-packages\ruamel_yaml\reader.py", line 125, in stream
        self.determine_encoding()
      File "C:\Users\aksha\Anaconda2\lib\site-packages\ruamel_yaml\reader.py", line 180, in determine_encoding
        self.update(1)
      File "C:\Users\aksha\Anaconda2\lib\site-packages\ruamel_yaml\reader.py", line 241, in update
        self.check_printable(data)
      File "C:\Users\aksha\Anaconda2\lib\site-packages\ruamel_yaml\reader.py", line 208, in check_printable
        'unicode', "special characters are not allowed")
    ReaderError: unacceptable character #x0000: special characters are not allowed
      in "C:\Users\aksha\.condarc", position 0

##### `conda list --show-channel-urls`

 environment variables:
                 CIO_TEST=<not set>
                CLASSPATH=%CLASSPATH%;C:\junit\junit4.10.jar;.;
               CONDA_ROOT=C:\Users\aksha\Anaconda2
                 HOMEPATH=\Users\aksha
                     PATH=C:\ProgramData\Oracle\Java\javapath;C:\Program Files (x86)\Intel\iCLS
                          Client\;C:\Program Files\Intel\iCLS Client\;C:\WINDOWS\system32;C:\WIN
                          DOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1
                          .0\;C:\Program Files (x86)\Intel\Intel(R) Management Engine
                          Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine
                          Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine
                          Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine
                          Components\IPT;C:\Program Files (x86)\PuTTY\;C:\Program
                          Files\PuTTY\;C:\Program Files\nodejs\;C:\Program
                          Files\TortoiseSVN\bin;C:\Program Files\apache-
                          maven-3.5.3\bin;C:\WINDOWS\System32\OpenSSH\;C:\Program
                          Files\Microsoft VS Code\bin;C:\Users\aksha\Anaconda2;C:\Users\aksha\An
                          aconda2\Library\mingw-w64\bin;C:\Users\aksha\Anaconda2\Library\usr\bin
                          ;C:\Users\aksha\Anaconda2\Library\bin;C:\Users\aksha\Anaconda2\Scripts
                          ;C:\Users\aksha\AppData\Local\Microsoft\WindowsApps;C:\Users\aksha\App
                          Data\Roaming\npm;C:\Program Files\apache-maven-3.5.3\bin;C:\Program
                          Files\Java\jdk-9\bin;C:\Program Files\Git\bin
             PSMODULEPATH=C:\Program Files\WindowsPowerShell\Modules;C:\WINDOWS\system32\Windows
                          PowerShell\v1.0\Modules
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>

     active environment : None
       user config file : C:\Users\aksha\.condarc
 populated config files :
          conda version : 4.5.4
    conda-build version : 3.10.5
         python version : 2.7.15.final.0
       base environment : C:\Users\aksha\Anaconda2  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/win-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/win-64
                          https://repo.anaconda.com/pkgs/pro/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\Users\aksha\Anaconda2\pkgs
                          C:\Users\aksha\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\aksha\Anaconda2\envs
                          C:\Users\aksha\AppData\Local\conda\conda\envs
                          C:\Users\aksha\.conda\envs
               platform : win-64
             user-agent : conda/4.5.4 requests/2.18.4 CPython/2.7.15 Windows/10 Windows/10.0.17134
          administrator : False
             netrc file : None
           offline mode : False

An unexpected error has occurred. Conda has prepared the above report.
If submitted, this report will be used by core maintainers to improve
future releases of conda.

**Comment by goanpeca** [comment]
Please (nmanually) remove this file

`C:\Users\aksha\.condarc` and try again
