### ISSUE TITLE
An unexpected error occurred on Navigator start-up

### ISSUE THREAD

**Issue by zkcpku** [ContinuumIO/anaconda-issues#10239]
Navigator Error
An unexpected error occurred on Navigator start-up

Report
Please report this issue in the anaconda issue tracker

Main Error
byte indices must be integers or slices, not str
Traceback
Traceback (most recent call last):
  File "E:\Users\lenovo\Anaconda3\lib\site-packages\anaconda_navigator\exceptions.py", line 75, in exception_handler
    return_value = func(*args, **kwargs)
  File "E:\Users\lenovo\Anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 120, in start_app
    window = run_app(splash)
  File "E:\Users\lenovo\Anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 63, in run_app
    window = MainWindow(splash=splash)
  File "E:\Users\lenovo\Anaconda3\lib\site-packages\anaconda_navigator\widgets\main_window.py", line 160, in __init__
    self.api = AnacondaAPI()
  File "E:\Users\lenovo\Anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 1214, in AnacondaAPI
    ANACONDA_API = _AnacondaAPI()
  File "E:\Users\lenovo\Anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 65, in __init__
    self._conda_api = CondaAPI()
  File "E:\Users\lenovo\Anaconda3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 1654, in CondaAPI
    CONDA_API = _CondaAPI()
  File "E:\Users\lenovo\Anaconda3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 345, in __init__
    self.set_conda_prefix()
  File "E:\Users\lenovo\Anaconda3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 494, in set_conda_prefix
    self.ROOT_PREFIX = info['root_prefix']
TypeError: byte indices must be integers or slices, not str

**Comment by zkcpku** [comment]
Unable to create process using 'E:\Users\lenovo\Anaconda3\python.exe E:\Users\lenovo\Anaconda3\Scripts\conda-script.py shell.cmd.exe activate activate E:\Users\lenovo\Anaconda3'

**Comment by zkcpku** [comment]
It happened after I updated "pip"

**Comment by zkcpku** [comment]
I also installed "tensorflow" and "keras" using "conda install XXX"
