### ISSUE TITLE
Cannot start Spyder

### ISSUE THREAD

**Issue by PANCWX** [ContinuumIO/anaconda-issues#10252]
##### `conda info`

```

```

##### `conda list --show-channel-urls`

```

```

**Comment by PANCWX** [comment]
Using MacOS Mojave, I have been unable to start Spyder. I have re-dowloaded not only Spyder, but Anaconda as well using conda install, have tried conda update on qt and pyqt as well as Spyder and conda. I get the following message: Traceback (most recent call last):
File "/anaconda3/lib/python3.6/site-packages/qtpy/QtWebEngineWidgets.py", line 22, in 
from PyQt5.QtWebEngineWidgets import QWebEnginePage
ModuleNotFoundError: No module named 'PyQt5.QtWebEngineWidgets'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/anaconda3/bin/spyder", line 11, in 
sys.exit(main())
File "/anaconda3/lib/python3.6/site-packages/spyder/app/start.py", line 189, in main
from spyder.app import mainwindow
File "/anaconda3/lib/python3.6/site-packages/spyder/app/mainwindow.py", line 92, in 
from qtpy import QtWebEngineWidgets # analysis:ignore
File "/anaconda3/lib/python3.6/site-packages/qtpy/QtWebEngineWidgets.py", line 26, in 
from PyQt5.QtWebKitWidgets import QWebPage as QWebEnginePage
ModuleNotFoundError: No module named 'PyQt5.QtWebKitWidgets'

**Comment by PANCWX** [comment]
accidentally closed

**Comment by natemcintosh** [comment]
I'm also seeing this issue

**Comment by csoja** [comment]
Missing information requested in issue template - particularly output of conda info and conda list --show-channel-urls.
