### ISSUE TITLE
Installing PyOdbc package with conda downgrades PyOpenSSL because of which conda stops working

### ISSUE THREAD

**Issue by daksha121** [ContinuumIO/anaconda-issues#10258]
### Actual Behavior
Installed pyodbc package as:
sudo ./conda install pyodbc -y
This downgrades some packages including PyOpenSSL

```
Solving environment: done

==> WARNING: A newer version of conda exists. <==
  current version: 4.5.9
  latest version: 4.5.11

Please update conda by running
    $ conda update -n base -c defaults conda

## Package Plan ##
  environment location: /usr/bin/anaconda
  added / updated specs:
    - pyodbc

The following packages will be downloaded:
    package                    |            build
    ---------------------------|-----------------
    sqlite-3.25.2              |       h7b6447c_0         1.9 MB
    pyodbc-4.0.24              |   py27he6710b0_0          68 KB
    python-2.7.15              |       h9bab390_2        12.7 MB
    pycurl-7.19.0              |           py27_0         220 KB
    ca-certificates-2018.03.07 |                0         124 KB
    libcurl-7.61.1             |       h20c2e04_0         503 KB
    openssl-1.1.1              |       h7b6447c_0         5.0 MB
    pyqt-4.11.4                |           py27_4         3.3 MB
    anaconda-project-0.8.2     |           py27_0         471 KB
    chardet-3.0.4              |           py27_1         180 KB
    spyder-3.0.2               |           py27_0         3.0 MB
    qtconsole-4.4.2            |           py27_0         154 KB
    curl-7.61.1                |       hbc83047_0         146 KB
    zlib-1.2.11                |       ha838bed_2         101 KB
    cryptography-0.5.4         |           py27_0         608 KB
    libedit-3.1.20170329       |       h6b74fdf_2         172 KB
    tk-8.6.8                   |       hbc83047_0         3.1 MB
    libgcc-ng-8.2.0            |       hdf63c60_1         7.6 MB
    ncurses-6.1                |       hf484d3e_0         943 KB
    anaconda-navigator-1.8.4   |           py27_0         4.7 MB
    libstdcxx-ng-8.2.0         |       hdf63c60_1         2.9 MB
    pyopenssl-0.15.1           |           py27_2         159 KB
    unixodbc-2.3.7             |       h14c3975_0         319 KB
    readline-7.0               |       h7b6447c_5         392 KB
    qt-4.8.7                   |                2        34.1 MB
    ------------------------------------------------------------
                                           Total:        83.0 MB

The following NEW packages will be INSTALLED:
    anaconda-project:   0.8.2-py27_0
    ca-certificates:    2018.03.07-0
    chardet:            3.0.4-py27_1
    libcurl:            7.61.1-h20c2e04_0
    libedit:            3.1.20170329-h6b74fdf_2
    libstdcxx-ng:       8.2.0-hdf63c60_1
    ncurses:            6.1-hf484d3e_0
    pyodbc:             4.0.24-py27he6710b0_0
    unixodbc:           2.3.7-h14c3975_0

The following packages will be UPDATED:
    anaconda-navigator: 1.3.1-py27_0            --> 1.8.4-py27_0
    curl:               7.49.0-1                --> 7.61.1-hbc83047_0
    libgcc-ng:          7.2.0-hdf63c60_3        --> 8.2.0-hdf63c60_1
    openssl:            1.0.2j-0                --> 1.1.1-h7b6447c_0
    python:             2.7.12-1                --> 2.7.15-h9bab390_2
    qtconsole:          4.2.1-py27_1            --> 4.4.2-py27_0
    readline:           6.2-2                   --> 7.0-h7b6447c_5
    spyder:             3.0.0-py27_0            --> 3.0.2-py27_0
    sqlite:             3.13.0-0                --> 3.25.2-h7b6447c_0
    tk:                 8.5.18-0                --> 8.6.8-hbc83047_0
    zlib:               1.2.8-3                 --> 1.2.11-ha838bed_2

The following packages will be DOWNGRADED:
    cryptography:       1.5-py27_0              --> 0.5.4-py27_0
    pycurl:             7.43.0-py27_0           --> 7.19.0-py27_0
    pyopenssl:          16.2.0-py27_0           --> 0.15.1-py27_2
    pyqt:               5.6.0-py27_0            --> 4.11.4-py27_4
    qt:                 5.6.0-0                 --> 4.8.7-2
```

After this conda commands like list start erroring out with:
```
Traceback (most recent call last):
  File "./bin/conda", line 11, in <module>
    sys.exit(main())
  File "/usr/bin/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 113, in main
    return conda_exception_handler(_main, *args)
  File "/usr/bin/anaconda/lib/python2.7/site-packages/conda/exceptions.py", line 1108, in conda_exception_handler
    return_value = exception_handler(func, *args, **kwargs)
  File "/usr/bin/anaconda/lib/python2.7/site-packages/conda/exceptions.py", line 822, in __call__
    return self.handle_exception(exc_val, exc_tb)
  File "/usr/bin/anaconda/lib/python2.7/site-packages/conda/exceptions.py", line 862, in handle_exception
    return self.handle_unexpected_exception(exc_val, exc_tb)
  File "/usr/bin/anaconda/lib/python2.7/site-packages/conda/exceptions.py", line 873, in handle_unexpected_exception
    self.print_unexpected_error_report(error_report)
  File "/usr/bin/anaconda/lib/python2.7/site-packages/conda/exceptions.py", line 943, in print_unexpected_error_report
    from .cli.main_info import get_env_vars_str, get_main_info_str
  File "/usr/bin/anaconda/lib/python2.7/site-packages/conda/cli/main_info.py", line 25, in <module>
    from ..core.subdir_data import SubdirData
  File "/usr/bin/anaconda/lib/python2.7/site-packages/conda/core/subdir_data.py", line 28, in <module>
    from ..core.package_cache_data import PackageCacheData
  File "/usr/bin/anaconda/lib/python2.7/site-packages/conda/core/package_cache_data.py", line 13, in <module>
    from .path_actions import CacheUrlAction, ExtractPackageAction
  File "/usr/bin/anaconda/lib/python2.7/site-packages/conda/core/path_actions.py", line 25, in <module>
    from ..gateways.connection.download import download
  File "/usr/bin/anaconda/lib/python2.7/site-packages/conda/gateways/connection/__init__.py", line 19, in <module>
    from requests import ConnectionError, HTTPError, Session
  File "/usr/bin/anaconda/lib/python2.7/site-packages/requests/__init__.py", line 52, in <module>
    from .packages.urllib3.contrib import pyopenssl
  File "/usr/bin/anaconda/lib/python2.7/site-packages/requests/packages/urllib3/contrib/pyopenssl.py", line 46, in <module>
    import OpenSSL.SSL
  File "/usr/bin/anaconda/lib/python2.7/site-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import rand, crypto, SSL
  File "/usr/bin/anaconda/lib/python2.7/site-packages/OpenSSL/rand.py", line 11, in <module>
    from OpenSSL._util import (
  File "/usr/bin/anaconda/lib/python2.7/site-packages/OpenSSL/_util.py", line 7, in <module>
    binding = Binding()
  File "/usr/bin/anaconda/lib/python2.7/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 89, in __init__
    self._ensure_ffi_initialized()
  File "/usr/bin/anaconda/lib/python2.7/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 109, in _ensure_ffi_initialized
    libraries=libraries,
  File "/usr/bin/anaconda/lib/python2.7/site-packages/cryptography/hazmat/bindings/utils.py", line 80, in build_ffi
    extra_link_args=extra_link_args,
  File "/usr/bin/anaconda/lib/python2.7/site-packages/cffi/api.py", line 437, in verify
    lib = self.verifier.load_library()
  File "/usr/bin/anaconda/lib/python2.7/site-packages/cffi/verifier.py", line 114, in load_library
    return self._load_library()
  File "/usr/bin/anaconda/lib/python2.7/site-packages/cffi/verifier.py", line 225, in _load_library
    return self._vengine.load_library()
  File "/usr/bin/anaconda/lib/python2.7/site-packages/cffi/vengine_cpy.py", line 158, in load_library
    raise ffiplatform.VerificationError(error)
cffi.ffiplatform.VerificationError: importing '/usr/bin/anaconda/lib/python2.7/site-packages/cryptography/_Cryptography_cffi_4ed9e37dx4000d087.so': /usr/bin/anaconda/lib/python2.7/site-packages/cryptography/_Cryptography_cffi_4ed9e37dx4000d087.so: undefined symbol: SSLv2_client_method
```

### Steps to Reproduce

sudo ./conda install pyodbc -y
./conda list

##### Anaconda or Miniconda version:
conda 4.5.9

##### Operating System:
Ubuntu 16.04

##### `conda info`
Fails after package installation with: undefined symbol: SSLv2_client_method (same as above)
Before package installation:

```
     active environment : None
       user config file : /home/sshuser/.condarc
 populated config files :
          conda version : 4.5.11
    conda-build version : 2.0.2
         python version : 2.7.12.final.0
       base environment : /usr/bin/anaconda  (read only)
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/linux-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/linux-64
                          https://repo.anaconda.com/pkgs/pro/noarch
          package cache : /usr/bin/anaconda/pkgs
                          /home/sshuser/.conda/pkgs
       envs directories : /home/sshuser/.conda/envs
                          /usr/bin/anaconda/envs
               platform : linux-64
             user-agent : conda/4.5.11 requests/2.14.2 CPython/2.7.12 Linux/4.15.0-1023-azure ubuntu/16.04 glibc/2.23
                UID:GID : 2020:2020
             netrc file : None
           offline mode : False
```

##### `conda list --show-channel-urls`
Fails after package installation with: undefined symbol: SSLv2_client_method (same as above)
Before package installation:
```
# packages in environment at /usr/bin/anaconda:
#
# Name                    Version                   Build  Channel
_license                  1.1                      py27_1    defaults
alabaster                 0.7.9                    py27_0    defaults
anaconda                  custom                   py27_0    defaults
anaconda-clean            1.0.0                    py27_0    defaults
anaconda-client           1.5.1                    py27_0    defaults
anaconda-navigator        1.3.1                    py27_0    defaults
argcomplete               1.0.0                    py27_1    defaults
astroid                   1.4.7                    py27_0    defaults
astropy                   1.2.1               np111py27_0    defaults
autovizwidget             0.12.5                    <pip>
azure-common              1.1.16                    <pip>
azure-nspkg               3.0.0                     <pip>
azure-storage             0.20.2                    <pip>
babel                     2.3.4                    py27_0    defaults
backports                 1.0                      py27_0    defaults
backports_abc             0.4                      py27_0    defaults
beautifulsoup4            4.5.1                    py27_0    defaults
bitarray                  0.8.1                    py27_0    defaults
blas                      1.0                         mkl    defaults
blaze                     0.10.1                   py27_0    defaults
bokeh                     0.12.2                   py27_0    defaults
boto                      2.42.0                   py27_0    defaults
bottleneck                1.1.0               np111py27_0    defaults
cairo                     1.12.18                       6    defaults
cdecimal                  2.3                      py27_2    defaults
cffi                      1.7.0                    py27_0    defaults
chest                     0.2.3                    py27_0    defaults
click                     6.6                      py27_0    defaults
cloudpickle               0.2.1                    py27_0    defaults
clyent                    1.2.2                    py27_0    defaults
colorama                  0.3.7                    py27_0    defaults
conda                     4.5.11                   py27_0    defaults
conda-build               2.0.2                    py27_0    defaults
conda-env                 2.6.0                         1    defaults
configobj                 5.0.6                    py27_0    defaults
configparser              3.5.0                    py27_0    defaults
contextlib2               0.5.3                    py27_0    defaults
cryptography              1.5                      py27_0    defaults
curl                      7.49.0                        1    defaults
cycler                    0.10.0                   py27_0    defaults
cython                    0.24.1                   py27_0    defaults
cytoolz                   0.8.0                    py27_0    defaults
dask                      0.11.0                   py27_0    defaults
datashape                 0.5.2                    py27_0    defaults
dbus                      1.10.10                       0    defaults
decorator                 4.0.10                   py27_0    defaults
dill                      0.2.5                    py27_0    defaults
docutils                  0.12                     py27_2    defaults
dynd-python               0.7.2                    py27_0    defaults
entrypoints               0.2.2                    py27_0    defaults
enum34                    1.1.6                    py27_0    defaults
et_xmlfile                1.0.1                    py27_0    defaults
expat                     2.1.0                         0    defaults
fastcache                 1.0.2                    py27_1    defaults
filelock                  2.0.6                    py27_0    defaults
flask                     0.11.1                   py27_0    defaults
flask-cors                2.1.2                    py27_0    defaults
fontconfig                2.11.1                        6    defaults
freetype                  2.5.5                         1    defaults
funcsigs                  1.0.2                    py27_0    defaults
functools32               3.2.3.2                  py27_0    defaults
futures                   3.0.5                    py27_0    defaults
get_terminal_size         1.0.0                    py27_0    defaults
gevent                    1.1.2                    py27_0    defaults
glib                      2.43.0                        1    defaults
greenlet                  0.4.10                   py27_0    defaults
grin                      1.2.1                    py27_3    defaults
gst-plugins-base          1.8.0                         0    defaults
gstreamer                 1.8.0                         0    defaults
h5py                      2.6.0               np111py27_2    defaults
harfbuzz                  0.9.39                        1    defaults
hdf5                      1.8.17                        1    defaults
hdijupyterutils           0.12.5                    <pip>
heapdict                  1.0.0                    py27_1    defaults
icu                       54.1                          0    defaults
idna                      2.1                      py27_0    defaults
imagesize                 0.7.1                    py27_0    defaults
ipaddress                 1.0.16                   py27_0    defaults
ipykernel                 4.5.0                    py27_0    defaults
ipython                   4.2.1                     <pip>
ipython                   5.1.0                    py27_0    defaults
ipython_genutils          0.1.0                    py27_0    defaults
ipywidgets                6.0.1                     <pip>
itsdangerous              0.24                     py27_0    defaults
jbig                      2.1                           0    defaults
jdcal                     1.2                      py27_1    defaults
jedi                      0.9.0                    py27_1    defaults
jinja2                    2.8                      py27_1    defaults
jpeg                      8d                            2    defaults
jsonschema                2.5.1                    py27_0    defaults
jupyter                   1.0.0                     <pip>
jupyter_client            4.4.0                    py27_0    defaults
jupyter_console           5.0.0                    py27_0    defaults
jupyter_core              4.2.0                    py27_0    defaults
jupyterazure              0.1.0                     <pip>
lazy-object-proxy         1.2.1                    py27_0    defaults
libdynd                   0.7.2                         0    defaults
libffi                    3.2.1                         0    defaults
libgcc                    4.8.5                         2    defaults
libgcc-ng                 8.2.0                hdf63c60_1    defaults
libgfortran               3.0.0                         1    defaults
libpng                    1.6.22                        0    defaults
libsodium                 1.0.10                        0    defaults
libtiff                   4.0.6                         2    defaults
libxcb                    1.12                          0    defaults
libxml2                   2.9.2                         0    defaults
libxslt                   1.1.28                        0    defaults
llvmlite                  0.13.0                   py27_0    defaults
locket                    0.2.0                    py27_1    defaults
lxml                      3.6.4                    py27_0    defaults
markupsafe                0.23                     py27_2    defaults
matplotlib                1.5.3               np111py27_0    defaults
mistune                   0.7.3                    py27_0    defaults
mkl                       11.3.3                        0    defaults
mkl-service               1.1.2                    py27_2    defaults
mock                      2.0.0                     <pip>
mpmath                    0.19                     py27_1    defaults
multipledispatch          0.4.8                    py27_0    defaults
nb_anacondacloud          1.2.0                    py27_0    defaults
nb_conda                  2.0.0                    py27_0    defaults
nb_conda_kernels          2.0.0                    py27_0    defaults
nbconvert                 4.2.0                    py27_0    defaults
nbformat                  4.4.0                     <pip>
nbformat                  4.1.0                    py27_0    defaults
nbpresent                 3.0.2                    py27_0    defaults
networkx                  1.11                     py27_0    defaults
nltk                      3.2.1                    py27_0    defaults
nose                      1.3.7                    py27_1    defaults
notebook                  4.2.3                    py27_0    defaults
numba                     0.28.1              np111py27_0    defaults
numexpr                   2.6.1               np111py27_0    defaults
numpy                     1.11.1                   py27_0    defaults
odo                       0.5.0                    py27_1    defaults
openpyxl                  2.3.2                    py27_0    defaults
openssl                   1.0.2j                        0    defaults
pandas                    0.20.1              np111py27_0    defaults
partd                     0.3.6                    py27_0    defaults
patchelf                  0.9                           0    defaults
path.py                   8.2.1                    py27_0    defaults
pathlib2                  2.1.0                    py27_0    defaults
patsy                     0.4.1                    py27_0    defaults
pbr                       4.2.0                     <pip>
pep8                      1.7.0                    py27_0    defaults
pexpect                   4.0.1                    py27_0    defaults
pickleshare               0.7.4                    py27_0    defaults
pillow                    3.3.1                    py27_0    defaults
pip                       8.1.2                    py27_0    defaults
pixman                    0.32.6                        0    defaults
pkginfo                   1.3.2                    py27_0    defaults
plotly                    2.7.0                     <pip>
ply                       3.9                      py27_0    defaults
prompt_toolkit            1.0.3                    py27_0    defaults
psutil                    4.3.1                    py27_0    defaults
ptyprocess                0.5.1                    py27_0    defaults
py                        1.4.31                   py27_0    defaults
pyasn1                    0.1.9                    py27_0    defaults
pycairo                   1.10.0                   py27_0    defaults
pycosat                   0.6.3            py27h14c3975_0    defaults
pycparser                 2.14                     py27_1    defaults
pycrypto                  2.6.1                    py27_4    defaults
pycurl                    7.43.0                   py27_0    defaults
pyflakes                  1.3.0                    py27_0    defaults
pygments                  2.1.3                    py27_0    defaults
pykerberos                1.2.1                     <pip>
pylint                    1.5.4                    py27_1    defaults
pyopenssl                 16.2.0                   py27_0    defaults
pyparsing                 2.1.4                    py27_0    defaults
pyqt                      5.6.0                    py27_0    defaults
pytables                  3.2.3.1             np111py27_0    defaults
pytest                    2.9.2                    py27_0    defaults
python                    2.7.12                        1    defaults
python-dateutil           2.5.3                    py27_0    defaults
pytz                      2016.6.1                 py27_0    defaults
pywebhdfs                 0.4.1                     <pip>
pyyaml                    3.12                     py27_0    defaults
pyzmq                     15.4.0                   py27_0    defaults
qt                        5.6.0                         0    defaults
qtawesome                 0.3.3                    py27_0    defaults
qtconsole                 4.2.1                    py27_1    defaults
qtpy                      1.1.2                    py27_0    defaults
readline                  6.2                           2    defaults
redis                     3.2.0                         0    defaults
redis-py                  2.10.5                   py27_0    defaults
requests                  2.14.2                   py27_0    defaults
requests-kerberos         0.12.0                    <pip>
rope                      0.9.4                    py27_1    defaults
ruamel_yaml               0.11.14                  py27_0    defaults
scikit-image              0.12.3              np111py27_1    defaults
scikit-learn              0.17.1              np111py27_2    defaults
scipy                     0.18.1              np111py27_0    defaults
setuptools                27.2.0                   py27_0    defaults
simplegeneric             0.8.1                    py27_1    defaults
singledispatch            3.4.0.3                  py27_0    defaults
sip                       4.18                     py27_0    defaults
six                       1.10.0                   py27_0    defaults
snowballstemmer           1.2.1                    py27_0    defaults
sockjs-tornado            1.0.3                    py27_0    defaults
sparkmagic                0.12.4                    <pip>
sphinx                    1.4.6                    py27_0    defaults
spyder                    3.0.0                    py27_0    defaults
sqlalchemy                1.0.13                   py27_0    defaults
sqlite                    3.13.0                        0    defaults
ssl_match_hostname        3.4.0.2                  py27_1    defaults
statsmodels               0.6.1               np111py27_1    defaults
sympy                     1.0                      py27_0    defaults
terminado                 0.6                      py27_0    defaults
tk                        8.5.18                        0    defaults
toolz                     0.8.0                    py27_0    defaults
tornado                   4.4.1                    py27_0    defaults
traitlets                 4.3.0                    py27_0    defaults
unicodecsv                0.14.1                   py27_0    defaults
wcwidth                   0.1.7                    py27_0    defaults
werkzeug                  0.11.11                  py27_0    defaults
wheel                     0.29.0                   py27_0    defaults
widgetsnbextension        1.2.6                    py27_0    defaults
widgetsnbextension        2.0.1                     <pip>
wrapt                     1.10.6                   py27_0    defaults
xlrd                      1.0.0                    py27_0    defaults
xlsxwriter                0.9.3                    py27_0    defaults
xlwt                      1.1.2                    py27_0    defaults
xz                        5.2.2                         0    defaults
yaml                      0.1.6                         0    defaults
zeromq                    4.1.4                         0    defaults
zlib                      1.2.8                         3    defaults
```

**Comment by prashanthmadi** [comment]
conda_history file

```
==> 2018-10-29 19:30:22 <==
# cmd: /usr/bin/anaconda/lib/python2.7/site-packages/conda/__main__.py update -y libgcc
# conda version: 4.5.11
-defaults::anaconda-navigator-1.3.1-py27_0
-defaults::cryptography-1.5-py27_0
-defaults::curl-7.49.0-1
-defaults::libgcc-4.8.5-2
-defaults::matplotlib-1.5.3-np111py27_0
-defaults::openssl-1.0.2j-0
-defaults::pycurl-7.43.0-py27_0
-defaults::pyopenssl-16.2.0-py27_0
-defaults::pyqt-5.6.0-py27_0
-defaults::python-2.7.12-1
-defaults::qt-5.6.0-0
-defaults::qtconsole-4.2.1-py27_1
-defaults::readline-6.2-2
-defaults::spyder-3.0.0-py27_0
-defaults::sqlite-3.13.0-0
-defaults::tk-8.5.18-0
-defaults::zlib-1.2.8-3
+defaults::anaconda-navigator-1.8.4-py27_0
+defaults::anaconda-project-0.8.2-py27_0
+defaults::ca-certificates-2018.03.07-0
+defaults::chardet-3.0.4-py27_1
+defaults::cryptography-0.5.4-py27_0
+defaults::curl-7.61.1-hbc83047_0
+defaults::libcurl-7.61.1-h20c2e04_0
+defaults::libedit-3.1.20170329-h6b74fdf_2
+defaults::libgcc-7.2.0-h69d50b8_2
+defaults::libstdcxx-ng-8.2.0-hdf63c60_1
+defaults::matplotlib-1.5.1-np111py27_0
+defaults::ncurses-6.1-hf484d3e_0
+defaults::openssl-1.1.1-h7b6447c_0
+defaults::pycurl-7.19.0-py27_0
+defaults::pyopenssl-0.15.1-py27_2
+defaults::pyqt-4.11.4-py27_4
+defaults::python-2.7.15-h9bab390_2
+defaults::qt-4.8.7-2
+defaults::qtconsole-4.4.2-py27_0
+defaults::readline-7.0-h7b6447c_5
+defaults::spyder-3.0.2-py27_0
+defaults::sqlite-3.25.2-h7b6447c_0
+defaults::tk-8.6.8-hbc83047_0
+defaults::zlib-1.2.11-ha838bed_2

```
