### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by phcwj** [ContinuumIO/anaconda-issues#10263]
## Main error
Application <b>jupyterlab</b> launch may have produced errors.
## Traceback
```
[I 10:58:08.054 LabApp] [nb_conda_kernels] enabled, 5 kernels found
[I 10:58:08.375 LabApp] The port 8888 is already in use, trying another port.
[I 10:58:09.877 LabApp] [nb_anacondacloud] enabled
[I 10:58:09.882 LabApp] [nb_conda] enabled
[I 10:58:09.955 LabApp] \u2713 nbpresent HTML export ENABLED
[W 10:58:09.955 LabApp] \u2717 nbpresent PDF export DISABLED: No module named 'nbbrowserpdf'
[W 10:58:09.956 LabApp] JupyterLab server extension not enabled, manually loading...
[I 10:58:09.958 LabApp] JupyterLab extension loaded from C:\Users\wjche\Anaconda3\lib\site-packages\jupyterlab
[I 10:58:09.959 LabApp] JupyterLab application directory is C:\Users\wjche\Anaconda3\share\jupyter\lab
[I 10:58:10.105 LabApp] Serving notebooks from local directory: C:\Users\wjche
[I 10:58:10.105 LabApp] 0 active kernels 
[I 10:58:10.105 LabApp] The Jupyter Notebook is running at: http://localhost:8889/?token=dc6caa275a708950631725116684a66fc6b4b97ca42b8ddb
[I 10:58:10.105 LabApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 10:58:10.112 LabApp] 
    
    Copy/paste this URL into your browser when you connect for the first time,
    to login with a token:
        http://localhost:8889/?token=dc6caa275a708950631725116684a66fc6b4b97ca42b8ddb
[I 10:58:10.251 LabApp] Accepting one-time-token-authenticated connection from ::1
[W 10:58:12.059 LabApp] Could not determine jupyterlab build status without nodejs
[W 10:58:12.320 LabApp] No such file or directory: OpenCV_study.ipynb
[W 10:58:12.321 LabApp] 404 GET /api/contents/OpenCV_study.ipynb?content=0&1540609092261 (::1) 2.00ms referer=http://localhost:8889/lab
[I 10:58:14.497 LabApp] Creating new notebook in /
[I 10:58:14.793 LabApp] Kernel started: 8af60950-1cff-4942-8d9b-6066949f010f
Traceback (most recent call last):
  File "C:\Users\wjche\Anaconda3\lib\runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "C:\Users\wjche\Anaconda3\lib\runpy.py", line 142, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "C:\Users\wjche\Anaconda3\lib\runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "C:\Users\wjche\Anaconda3\lib\site-packages\ipykernel\__init__.py", line 2, in <module>
    from .connect import *
  File "C:\Users\wjche\Anaconda3\lib\site-packages\ipykernel\connect.py", line 13, in <module>
    from IPython.core.profiledir import ProfileDir
  File "C:\Users\wjche\Anaconda3\lib\site-packages\IPython\__init__.py", line 49, in <module>
    from .terminal.embed import embed
  File "C:\Users\wjche\Anaconda3\lib\site-packages\IPython\terminal\embed.py", line 18, in <module>
    from IPython.terminal.interactiveshell import TerminalInteractiveShell
  File "C:\Users\wjche\Anaconda3\lib\site-packages\IPython\terminal\interactiveshell.py", line 20, in <module>
    from prompt_toolkit.shortcuts import create_prompt_application, create_eventloop, create_prompt_layout, create_output
ImportError: cannot import name 'create_prompt_application'
[I 10:58:17.770 LabApp] KernelRestarter: restarting kernel (1/5)
Traceback (most recent call last):
  File "C:\Users\wjche\Anaconda3\lib\runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "C:\Users\wjche\Anaconda3\lib\runpy.py", line 142, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "C:\Users\wjche\Anaconda3\lib\runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "C:\Users\wjche\Anaconda3\lib\site-packages\ipykernel\__init__.py", line 2, in <module>
    from .connect import *
  File "C:\Users\wjche\Anaconda3\lib\site-packages\ipykernel\connect.py", line 13, in <module>
    from IPython.core.profiledir import ProfileDir
  File "C:\Users\wjche\Anaconda3\lib\site-packages\IPython\__init__.py", line 49, in <module>
    from .terminal.embed import embed
  File "C:\Users\wjche\Anaconda3\lib\site-packages\IPython\terminal\embed.py", line 18, in <module>
    from IPython.terminal.interactiveshell import TerminalInteractiveShell
  File "C:\Users\wjche\Anaconda3\lib\site-packages\IPython\terminal\interactiveshell.py", line 20, in <module>
    from prompt_toolkit.shortcuts import create_prompt_application, create_eventloop, create_prompt_layout, create_output
ImportError: cannot import name 'create_prompt_application'

```
## System information
```
qt: 5.6.2
pyqt: 5.6.0
conda: 4.5.11
platform: win-64
version: 1.6.2
os: Windows;10;10.0.17134;AMD64;Intel64 Family 6 Model 69 Stepping 1, GenuineIntel
language: zh_TW
python: 3.5.3
```

**Comment by goanpeca** [comment]
Please remember to update to the latest version of Navigator to include
the latest fixes.

Open a terminal (on Linux or Mac) or the Anaconda Command Prompt (on windows)
and type:

```
conda update conda
conda update --all
```
