### ISSUE TITLE
Error while Opening Anaconda navigator

### ISSUE THREAD

**Issue by donrockvic** [ContinuumIO/anaconda-issues#10268]
### Actual Behavior

Anaconda navigator is not opening
### Expected Behavior

it should open
##### Anaconda or Miniconda version:
anaconda 3
##### Operating System:
windows 10
##### `conda info`

```
Main Error
'conda_prefix'
Traceback
Traceback (most recent call last):
  File "C:\Users\Vicky Kumar\Anaconda3\lib\site-packages\anaconda_navigator\exceptions.py", line 75, in exception_handler
    return_value = func(*args, **kwargs)
  File "C:\Users\Vicky Kumar\Anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 150, in start_app
    window = run_app(splash)
  File "C:\Users\Vicky Kumar\Anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 65, in run_app
    window = MainWindow(splash=splash, tab_project=False)
  File "C:\Users\Vicky Kumar\Anaconda3\lib\site-packages\anaconda_navigator\widgets\main_window.py", line 163, in __init__
    self.api = AnacondaAPI()
  File "C:\Users\Vicky Kumar\Anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 2185, in AnacondaAPI
    ANACONDA_API = _AnacondaAPI()
  File "C:\Users\Vicky Kumar\Anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 89, in __init__
    self._conda_api = CondaAPI()
  File "C:\Users\Vicky Kumar\Anaconda3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 1714, in CondaAPI
    CONDA_API = _CondaAPI()
  File "C:\Users\Vicky Kumar\Anaconda3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 350, in __init__
    self.set_conda_prefix(info=get_conda_info())
  File "C:\Users\Vicky Kumar\Anaconda3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 506, in set_conda_prefix
    self.CONDA_PREFIX = info['conda_prefix']
KeyError: 'conda_prefix'
```

##### `conda list --show-channel-urls`

```

```

**Comment by goanpeca** [comment]
@donrockvic are you opening the `Anaconda Prompt` or a normal `Command Prompt`?

**Comment by donrockvic** [comment]
Anaconda Prompt
