### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by ymdarum** [ContinuumIO/anaconda-issues#10272]
## Main error
An unexpected error occurred on Navigator start-up<br>byte indices must be integers or slices, not str
## Traceback
```
Traceback (most recent call last):
  File "C:\Anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 111, in start_app
    with lock.acquire(timeout=3.0):  # timeout in seconds
  File "C:\Anaconda3\lib\site-packages\anaconda_navigator\external\filelock.py", line 254, in acquire
    raise Timeout(self._lock_file)
anaconda_navigator.external.filelock.Timeout: The file lock 'C:\Users\User\.anaconda\navigator\navigator.lock' could not be acquired.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Anaconda3\lib\site-packages\anaconda_navigator\exceptions.py", line 75, in exception_handler
    return_value = func(*args, **kwargs)
  File "C:\Anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 124, in start_app
    "There is an instance of "
  File "C:\Anaconda3\lib\site-packages\anaconda_navigator\widgets\dialogs\__init__.py", line 450, in __init__
    type_=self.INFORMATION_BOX,
  File "C:\Anaconda3\lib\site-packages\anaconda_navigator\widgets\dialogs\__init__.py", line 265, in __init__
    self.tracker = GATracker()
  File "C:\Anaconda3\lib\site-packages\anaconda_navigator\utils\analytics.py", line 284, in GATracker
    GA_TRACKER = _GATracker()
  File "C:\Anaconda3\lib\site-packages\anaconda_navigator\utils\analytics.py", line 95, in __init__
    self.api = AnacondaAPI()
  File "C:\Anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 1205, in AnacondaAPI
    ANACONDA_API = _AnacondaAPI()
  File "C:\Anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 65, in __init__
    self._conda_api = CondaAPI()
  File "C:\Anaconda3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 1622, in CondaAPI
    CONDA_API = _CondaAPI()
  File "C:\Anaconda3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 340, in __init__
    self.set_conda_prefix()
  File "C:\Anaconda3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 489, in set_conda_prefix
    self.ROOT_PREFIX = info['root_prefix']
TypeError: byte indices must be integers or slices, not str

```
## System information
```
python: 3.6.1
language: en_US
os: Windows;10;10.0.17134;AMD64;Intel64 Family 6 Model 142 Stepping 10, GenuineIntel
version: 1.6.2
platform: win-64
qt: 5.6.2
pyqt: 5.6.0
conda: 4.3.21
```

**Comment by goanpeca** [comment]
Closing as duplicate of #1837

---

Please remember to update to the latest version of Navigator to include
the latest fixes.

Open a terminal (on Linux or Mac) or the Anaconda Command Prompt (on windows)
and type:

```
$ conda update conda
$ conda update anaconda-navigator
$ conda update navigator-updater
```

---

**See Issue #1837 for more information on how to fix this.**
