### ISSUE TITLE
anaconda defaults openssl 1.1.1 upgrade is causing inconsistent py2 environments

### ISSUE THREAD

**Issue by s22chan** [ContinuumIO/anaconda-issues#10283]
### Actual Behavior

A new python runtime built with openssl 1.1.1 is installed in most cases, but dependent packages (mainly cryptography, urllib3) haven't been rebuilt and older packages haven't been pinned to a compatible openssl. Also linkage is not correctly set to symlinks and linked directly to versioned sharedlibs. End result is most packages that access openssl fail:

```python
>>> import requests
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/miniconda3/envs/protobuf/lib/python2.7/site-packages/requests/__init__.py", line 52, in <module>
    from .packages.urllib3.contrib import pyopenssl
  File "/miniconda3/envs/protobuf/lib/python2.7/site-packages/requests/packages/urllib3/contrib/pyopenssl.py", line 46, in <module>
    import OpenSSL.SSL
  File "/miniconda3/envs/protobuf/lib/python2.7/site-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import rand, crypto, SSL
  File "/miniconda3/envs/protobuf/lib/python2.7/site-packages/OpenSSL/rand.py", line 11, in <module>
    from OpenSSL._util import (
  File "/miniconda3/envs/protobuf/lib/python2.7/site-packages/OpenSSL/_util.py", line 7, in <module>
    binding = Binding()
  File "/miniconda3/envs/protobuf/lib/python2.7/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 89, in __init__
    self._ensure_ffi_initialized()
  File "/miniconda3/envs/protobuf/lib/python2.7/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 109, in _ensure_ffi_initialized
    libraries=libraries,
  File "/miniconda3/envs/protobuf/lib/python2.7/site-packages/cryptography/hazmat/bindings/utils.py", line 80, in build_ffi
    extra_link_args=extra_link_args,
  File "/miniconda3/envs/protobuf/lib/python2.7/site-packages/cffi/api.py", line 451, in verify
    lib = self.verifier.load_library()
  File "/miniconda3/envs/protobuf/lib/python2.7/site-packages/cffi/verifier.py", line 105, in load_library
    return self._load_library()
  File "/miniconda3/envs/protobuf/lib/python2.7/site-packages/cffi/verifier.py", line 216, in _load_library
    return self._vengine.load_library()
  File "/miniconda3/envs/protobuf/lib/python2.7/site-packages/cffi/vengine_cpy.py", line 159, in load_library
    raise VerificationError(error)
cffi.error.VerificationError: importing '/miniconda3/envs/protobuf/lib/python2.7/site-packages/cryptography/_Cryptography_cffi_4ed9e37dx4000d087.so': dlopen(/miniconda3/envs/protobuf/lib/python2.7/site-packages/cryptography/_Cryptography_cffi_4ed9e37dx4000d087.so, 2): Library not loaded: @loader_path/../../../libcrypto.1.0.0.dylib
  Referenced from: /miniconda3/envs/protobuf/lib/python2.7/site-packages/cryptography/_Cryptography_cffi_4ed9e37dx4000d087.so
  Reason: image not found
```

### Expected Behavior

either environments resolve correctly consistently to an older version of openssl, or new packages are built with openssl.

### Steps to Reproduce

on macos
```sh
conda create -n test python=2 conda-build
conda activate test
python -c 'import requests'
```
on ubuntu
```sh
conda create -n test python=2 conda=4.5.2 openssl=1.1.1
conda activate test
python -c 'import requests'
```

##### Anaconda or Miniconda version: 
Miniconda 4.5.11

##### Operating System:
Mac/Ubuntu

##### `conda info`
```
     active environment : test
    active env location : /miniconda3/envs/test
            shell level : 1
       user config file : /.condarc
 populated config files : /.condarc
          conda version : 4.5.11
    conda-build version : 3.16.1
         python version : 3.7.0.final.0
       base environment : /miniconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/osx-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/osx-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/osx-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/osx-64
                          https://repo.anaconda.com/pkgs/pro/noarch
          package cache : /miniconda3/pkgs
                          /.conda/pkgs
       envs directories : /miniconda3/envs
                          /.conda/envs
               platform : osx-64
             user-agent : conda/4.5.11 requests/2.19.1 CPython/3.7.0 Darwin/18.0.0 OSX/10.14
                UID:GID : 501:20
             netrc file : None
           offline mode : False

# conda environments:
#
base                     /miniconda3
test                  *  /miniconda3/envs/test

sys.version: 3.7.0 (default, Jun 28 2018, 07:39:16)
...
sys.prefix: /miniconda3
sys.executable: /miniconda3/bin/python
conda location: /miniconda3/lib/python3.7/site-packages/conda
conda-build: /miniconda3/bin/conda-build
conda-convert: /miniconda3/bin/conda-convert
conda-develop: /miniconda3/bin/conda-develop
conda-env: /miniconda3/bin/conda-env
conda-index: /miniconda3/bin/conda-index
conda-inspect: /miniconda3/bin/conda-inspect
conda-metapackage: /miniconda3/bin/conda-metapackage
conda-render: /miniconda3/bin/conda-render
conda-server: /miniconda3/bin/conda-server
conda-skeleton: /miniconda3/bin/conda-skeleton
user site dirs: ~/.local/lib/python2.7

CIO_TEST: <not set>
CONDA_DEFAULT_ENV: test
CONDA_EXE: /miniconda3/bin/conda
CONDA_PREFIX: /miniconda3/envs/test
CONDA_PROMPT_MODIFIER:
CONDA_PYTHON_EXE: /miniconda3/bin/python
CONDA_ROOT: /miniconda3
CONDA_SHLVL: 1
INFOPATH: /usr/local/share/info:
MANPATH: /usr/local/share/man:
PATH: /miniconda3/envs/test/bin:/usr/local/bin:/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/local/sbin:/usr/bin:/bin:/usr/sbin:/sbin
REQUESTS_CA_BUNDLE: <not set>
SSL_CERT_FILE: <not set>
```

##### `conda list --show-channel-urls`
```
# packages in environment at /miniconda3/envs/test:
#
# Name                    Version                   Build  Channel
beautifulsoup4            4.6.3                    py27_0    defaults
bzip2                     1.0.6                h1de35cc_5    defaults
ca-certificates           2018.03.07                    0    defaults
certifi                   2018.10.15               py27_0    defaults
cffi                      1.11.5           py27h6174b99_1    defaults
chardet                   3.0.4                    py27_1    defaults
conda                     4.5.2                    py27_0    defaults
conda-build               3.16.2                   py27_0    defaults
conda-env                 2.6.0                         1    defaults
contextlib2               0.5.5            py27h9cb85f4_0    defaults
cryptography              0.5.4                    py27_0    defaults
enum34                    1.1.6                    py27_1    defaults
filelock                  3.0.9                    py27_0    defaults
futures                   3.2.0                    py27_0    defaults
glob2                     0.6                      py27_1    defaults
icu                       58.2                 h4b95b61_1    defaults
jinja2                    2.10                     py27_0    defaults
libarchive                3.3.3                he8b1da1_2    defaults
libcxx                    4.0.1                hcfea43d_1    defaults
libcxxabi                 4.0.1                hcfea43d_1    defaults
libedit                   3.1.20170329         hb402a30_2    defaults
libffi                    3.2.1                h475c297_4    defaults
libiconv                  1.15                 hdd342a3_7    defaults
libxml2                   2.9.8                hab757c2_1    defaults
lz4-c                     1.8.1.2              h1de35cc_0    defaults
lzo                       2.10                 h362108e_2    defaults
markupsafe                1.0              py27h1de35cc_1    defaults
ncurses                   6.1                  h0a44026_0    defaults
openssl                   1.1.1                h1de35cc_0    defaults
pip                       10.0.1                   py27_0    defaults
pkginfo                   1.4.2                    py27_1    defaults
psutil                    5.4.7            py27h1de35cc_0    defaults
pycosat                   0.6.3            py27h1de35cc_0    defaults
pycparser                 2.19                     py27_0    defaults
pyopenssl                 0.15.1                   py27_2    defaults
python                    2.7.15               h8f8e585_2    defaults
python-libarchive-c       2.8                      py27_6    defaults
pytz                      2018.5                   py27_0    defaults
pyyaml                    3.13             py27h1de35cc_0    defaults
readline                  7.0                  h1de35cc_5    defaults
requests                  2.14.2                   py27_0    defaults
ruamel_yaml               0.15.46          py27h1de35cc_0    defaults
scandir                   1.9.0            py27h1de35cc_0    defaults
setuptools                40.4.3                   py27_0    defaults
six                       1.11.0                   py27_1    defaults
sqlite                    3.25.2               ha441bb4_0    defaults
tk                        8.6.8                ha441bb4_0    defaults
tqdm                      4.26.0           py27h28b3542_0    defaults
wheel                     0.32.2                   py27_0    defaults
xz                        5.2.4                h1de35cc_4    defaults
yaml                      0.1.7                hc338f04_2    defaults
zlib                      1.2.11               hf3cbc9b_2    defaults
zstd                      1.3.3                h2a6be3a_0    defaults
```

**Comment by s22chan** [comment]
realted to https://github.com/ContinuumIO/anaconda-issues/issues/10258

**Comment by mingwandroid** [comment]
> Also linkage is not correctly set to symlinks and linked directly to versioned sharedlibs. End result is most packages that access openssl fail:

macOS has no capability to link to symlinks unless you hack it so you will find this linkage issue on all macOS software distributionsd. Let me demonstrate for you using macOS's own native command-line tools compiler and linker:

```
pushd /opt/conda/pkgs/openssl-1.1.1-h1de35cc_0/lib
clang++ ~/gd.cio/hello-world.cpp -L$PWD -lssl
otool -l a.out | grep ssl
         name @rpath/libssl.1.1.dylib (offset 24)
```

I tried your reproducer on linux and it worked fine with the latest packages:

```
conda list
# packages in environment at /opt/conda/envs/test:
#
# Name                    Version                   Build  Channel
asn1crypto                0.24.0                   py27_0    defaults
beautifulsoup4            4.6.3                    py27_0    defaults
bzip2                     1.0.6                h14c3975_5    defaults
ca-certificates           2018.03.07                    0    defaults
certifi                   2018.10.15               py27_0    defaults
cffi                      1.11.5           py27he75722e_1    defaults
chardet                   3.0.4                    py27_1    defaults
conda                     4.5.11                   py27_0    defaults
conda-build               3.16.2                   py27_0    defaults
conda-env                 2.6.0                         1    defaults
contextlib2               0.5.5                    py27_0    defaults
cryptography              2.3.1            py27hc365091_0    defaults
enum34                    1.1.6                    py27_1    defaults
filelock                  3.0.9                    py27_0    defaults
futures                   3.2.0                    py27_0    defaults
glob2                     0.6                      py27_1    defaults
icu                       58.2                 h9c2bf20_1    defaults
idna                      2.7                      py27_0    defaults
ipaddress                 1.0.22                   py27_0    defaults
jinja2                    2.10                     py27_0    defaults
libarchive                3.3.3                h7d0bbab_1    defaults
libedit                   3.1.20170329         h6b74fdf_2    defaults
libffi                    3.2.1                hd88cf55_4    defaults
libgcc-ng                 8.2.0                hdf63c60_1    defaults
libstdcxx-ng              8.2.0                hdf63c60_1    defaults
libxml2                   2.9.8                h26e45fe_1    defaults
lz4-c                     1.8.1.2              h14c3975_0    defaults
lzo                       2.10                 h49e0be7_2    defaults
markupsafe                1.0              py27h14c3975_1    defaults
ncurses                   6.1                  hf484d3e_0    defaults
openssl                   1.0.2p               h14c3975_0    defaults
patchelf                  0.9                  he6710b0_3    defaults
pip                       10.0.1                   py27_0    defaults
pkginfo                   1.4.2                    py27_1    defaults
psutil                    5.4.7            py27h14c3975_0    defaults
pycosat                   0.6.3            py27h14c3975_0    defaults
pycparser                 2.19                     py27_0    defaults
pyopenssl                 18.0.0                   py27_0    defaults
pysocks                   1.6.8                    py27_0    defaults
python                    2.7.15               h77bded6_2    defaults
python-libarchive-c       2.8                      py27_6    defaults
pytz                      2018.5                   py27_0    defaults
pyyaml                    3.13             py27h14c3975_0    defaults
readline                  7.0                  h7b6447c_5    defaults
requests                  2.19.1                   py27_0    defaults
ruamel_yaml               0.15.46          py27h14c3975_0    defaults
scandir                   1.9.0            py27h14c3975_0    defaults
setuptools                40.4.3                   py27_0    defaults
six                       1.11.0                   py27_1    defaults
sqlite                    3.25.2               h7b6447c_0    defaults
tk                        8.6.8                hbc83047_0    defaults
tqdm                      4.26.0           py27h28b3542_0    defaults
urllib3                   1.23                     py27_0    defaults
wheel                     0.32.2                   py27_0    defaults
xz                        5.2.4                h14c3975_4    defaults
yaml                      0.1.7                had09818_2    defaults
zlib                      1.2.11               ha838bed_2    defaults
zstd                      1.3.3                h84994c4_0    defaults
```

Finally regarding the `DT_NEEDED` entry, again, I believe you think you know things that you do not.  It is the upstream package that determines the value of `DT_NEEDED`, specifically, the `DT_SONAME`. OpenSSL 1.1.1 has (as determined by `readelf -d`) an `SONAME` of:

>  0x000000000000000e (SONAME)             Library soname: [libssl.so.1.1]

.. so anything that links to it will adopt that name as the library filename to load.

This puts binary compatibility in the hands of the upstream project, provided we do not mess about with that code, which in this case, we do not. You can verify this against any linux distro very easily using docker, I used ArchLinux (`eu-readelf.d /usr/lib/libssl.so`) and got:

>  SONAME            Library soname: [libssl.so.1.1]

So you can see we're simply going with the upstream decisions wrt this.

**Comment by s22chan** [comment]
@mingwandroid for the linux repro, there are cases where it rollsback to conda=4.5.2 (but mainly you include conda channels with unpinned packages [like urllib3 on bioconda]).

I had previously opened an issue on conda-forge for the same problem: https://github.com/conda-forge/urllib3-feedstock/issues/18

I can see this is impossible to resolve on the anaconda side: is disallowing rollbacks on conda compared to the base version a manageable work-around?

**Comment by mingwandroid** [comment]
The issue here is unpinned packages in the legacy `free` channel. We'll look into that.

**Comment by mingwandroid** [comment]
Despite what I said about upstream being in charge of `DT_NEEDED` via `DT_SONAME` etc, we have our own version constraints in place (which clearly we need to align with upstream as best we can). These constraints are missing for some very old packages and unfortunately our solver finds these incorrect solutions sometimes.

**Comment by jjhelmus** [comment]
Builds of `cryptography` version 2.3.1 for OpenSSL 1.1.1 are now available.  The solver is now finding a much better solution for the environment:

```
~$ conda create -n test python=2 conda=4.5.2 openssl=1.1.1
Solving environment: done

## Package Plan ##

  environment location: /home/jhelmus/anaconda3/envs/test

  added / updated specs: 
    - conda=4.5.2
    - openssl=1.1.1
    - python=2


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    cryptography-2.3.1         |   py27h1ba5d50_2         586 KB  defaults
    conda-4.5.2                |           py27_0         1.0 MB  defaults
    ------------------------------------------------------------
                                           Total:         1.6 MB

The following NEW packages will be INSTALLED:

    asn1crypto:      0.24.0-py27_0           defaults
    ca-certificates: 2018.03.07-0            defaults
    certifi:         2018.10.15-py27_0       defaults
    cffi:            1.11.5-py27he75722e_1   defaults
    chardet:         3.0.4-py27_1            defaults
    conda:           4.5.2-py27_0            defaults
    conda-env:       2.6.0-1                 defaults
    cryptography:    2.3.1-py27h1ba5d50_2    defaults
    enum34:          1.1.6-py27_1            defaults
    futures:         3.2.0-py27_0            defaults
    idna:            2.7-py27_0              defaults
    ipaddress:       1.0.22-py27_0           defaults
    libedit:         3.1.20170329-h6b74fdf_2 defaults
    libffi:          3.2.1-hd88cf55_4        defaults
    libgcc-ng:       8.2.0-hdf63c60_1        defaults
    libstdcxx-ng:    8.2.0-hdf63c60_1        defaults
    ncurses:         6.1-hf484d3e_0          defaults
    openssl:         1.1.1-h7b6447c_0        defaults
    pycosat:         0.6.3-py27h14c3975_0    defaults
    pycparser:       2.19-py27_0             defaults
    pyopenssl:       18.0.0-py27_0           defaults
    pysocks:         1.6.8-py27_0            defaults
    python:          2.7.15-h9bab390_2       defaults
    readline:        7.0-h7b6447c_5          defaults
    requests:        2.19.1-py27_0           defaults
    ruamel_yaml:     0.15.46-py27h14c3975_0  defaults
    six:             1.11.0-py27_1           defaults
    sqlite:          3.25.2-h7b6447c_0       defaults
    tk:              8.6.8-hbc83047_0        defaults
    urllib3:         1.23-py27_0             defaults
    yaml:            0.1.7-had09818_2        defaults
    zlib:            1.2.11-ha838bed_2       defaults
```

`requests` can be imported in this environment:

```
~$ conda activate test
(test) ~$ python -c "import requests"
(test) ~$ 
```

**Comment by mingwandroid** [comment]
Thanks @jjhelmus

**Comment by s22chan** [comment]
looks good, thanks!
