### ISSUE TITLE
'root_prefix'

### ISSUE THREAD

**Issue by zhouyu1988** [ContinuumIO/anaconda-issues#10316]
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda2\lib\site-packages\anaconda_navigator\exceptions.py", line 75, in exception_handler
    return_value = func(*args, **kwargs)
  File "C:\ProgramData\Anaconda2\lib\site-packages\anaconda_navigator\app\start.py", line 150, in start_app
    window = run_app(splash)
  File "C:\ProgramData\Anaconda2\lib\site-packages\anaconda_navigator\app\start.py", line 65, in run_app
    window = MainWindow(splash=splash, tab_project=False)
  File "C:\ProgramData\Anaconda2\lib\site-packages\anaconda_navigator\widgets\main_window.py", line 168, in __init__
    self.api = AnacondaAPI()
  File "C:\ProgramData\Anaconda2\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 2294, in AnacondaAPI
    ANACONDA_API = _AnacondaAPI()
  File "C:\ProgramData\Anaconda2\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 91, in __init__
    self._conda_api = CondaAPI()
  File "C:\ProgramData\Anaconda2\lib\site-packages\anaconda_navigator\api\conda_api.py", line 1767, in CondaAPI
    CONDA_API = _CondaAPI()
  File "C:\ProgramData\Anaconda2\lib\site-packages\anaconda_navigator\api\conda_api.py", line 350, in __init__
    self.set_conda_prefix(info=get_conda_info())
  File "C:\ProgramData\Anaconda2\lib\site-packages\anaconda_navigator\api\conda_api.py", line 505, in set_conda_prefix
    self.ROOT_PREFIX = info['root_prefix']
KeyError: 'root_prefix'

##### `conda info`

```

```

##### `conda list --show-channel-urls`

```

```

**Comment by goanpeca** [comment]
Please provide the requested information on the issue template



### Actual Behavior



### Expected Behavior



### Steps to Reproduce




##### Anaconda or Miniconda version:

##### Operating System:

##### `conda info`

```

```

##### `conda list --show-channel-urls`

```

```
