### ISSUE TITLE
hi @goanpeca

### ISSUE THREAD

**Issue by SijinJohn** [ContinuumIO/anaconda-issues#10329]
##### `conda info`

```

```

##### `conda list --show-channel-urls`

```

```

**Comment by SijinJohn** [comment]
hi I am finding this navigator error

Navigator Error
An unexpected error occurred on Navigator start-up

Report
Please report this issue in the anaconda issue tracker

Main Error
expected str, bytes or os.PathLike object, not NoneType
Traceback
Traceback (most recent call last):
  File "C:\Users\sijin.john\AppData\Local\Continuum\anaconda3\lib\site-packages\anaconda_navigator\exceptions.py", line 75, in exception_handler
    return_value = func(*args, **kwargs)
  File "C:\Users\sijin.john\AppData\Local\Continuum\anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 150, in start_app
    window = run_app(splash)
  File "C:\Users\sijin.john\AppData\Local\Continuum\anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 65, in run_app
    window = MainWindow(splash=splash, tab_project=False)
  File "C:\Users\sijin.john\AppData\Local\Continuum\anaconda3\lib\site-packages\anaconda_navigator\widgets\main_window.py", line 163, in __init__
    self.api = AnacondaAPI()
  File "C:\Users\sijin.john\AppData\Local\Continuum\anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 2185, in AnacondaAPI
    ANACONDA_API = _AnacondaAPI()
  File "C:\Users\sijin.john\AppData\Local\Continuum\anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 89, in __init__
    self._conda_api = CondaAPI()
  File "C:\Users\sijin.john\AppData\Local\Continuum\anaconda3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 1714, in CondaAPI
    CONDA_API = _CondaAPI()
  File "C:\Users\sijin.john\AppData\Local\Continuum\anaconda3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 353, in __init__
    self.sys_rc_path = join(self.ROOT_PREFIX, '.condarc')
  File "C:\Users\sijin.john\AppData\Local\Continuum\anaconda3\lib\ntpath.py", line 76, in join
    path = os.fspath(path)
TypeError: expected str, bytes or os.PathLike object, not NoneType

conda info
Traceback (most recent call last):
  File "c:\users\sijin.john\appdata\local\continuum\anaconda3\envs\tensorflow\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\sijin.john\appdata\local\continuum\anaconda3\envs\tensorflow\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\sijin.john\AppData\Local\Continuum\anaconda3\Scripts\conda.exe\__main__.py", line 9, in <module>
  File "c:\users\sijin.john\appdata\local\continuum\anaconda3\envs\tensorflow\lib\site-packages\markdown\__main__.py", line 138, in run
    markdown.markdownFromFile(**options)
  File "c:\users\sijin.john\appdata\local\continuum\anaconda3\envs\tensorflow\lib\site-packages\markdown\core.py", line 411, in markdownFromFile
    kwargs.get('encoding', None))
  File "c:\users\sijin.john\appdata\local\continuum\anaconda3\envs\tensorflow\lib\site-packages\markdown\core.py", line 325, in convertFile
    input_file = codecs.open(input, mode="r", encoding=encoding)
  File "c:\users\sijin.john\appdata\local\continuum\anaconda3\envs\tensorflow\lib\codecs.py", line 895, in open
    file = builtins.open(filename, mode, buffering)
FileNotFoundError: [Errno 2] No such file or directory: 'info'

conda list --show-channel-urls
Usage: conda [options] [INPUTFILE]
       (STDIN is assumed if no INPUTFILE is given)

conda: error: no such option: --show-channel-urls

**Comment by SijinJohn** [comment]
Anaconda version

Usage: conda [options] [INPUTFILE]
       (STDIN is assumed if no INPUTFILE is given)

conda: error: no such option: --json
usage: anaconda [-h] [--disable-ssl-warnings] [--show-traceback] [-v] [-q]
                [-V] [-t TOKEN] [-s SITE]
                ...
anaconda: error: argument : invalid choice: 'version' (choose from 'auth', 'label', 'channel', 'config', 'copy', 'download', 'groups', 'login', 'logout', 'notebook', 'package', 'remove', 'search', 'show', 'upload', 'whoami')

**Comment by SijinJohn** [comment]
Operating system:-
Windows 10 Pro
Version:-1803
Os build :-17134.1

**Comment by jardinetsouffleton** [comment]
Just had the same problem. Tried uninstalling, restarting my PC and re-installing and had the same error again.

**Comment by jardinetsouffleton** [comment]
try deleting this file C:\Users\your name\.condarc ; it worked for me :)

**Comment by SijinJohn** [comment]
i deleted the condarc file but still show the same error.Why is it so??
Still the navigator error shows conarc :-
File "C:\Users\sijin.john\AppData\Local\Continuum\anaconda3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 353, in init
self.sys_rc_path = join(self.ROOT_PREFIX, '.condarc')

**Comment by djproc** [comment]
I had the same error and deleted codaarc and it solved the issue

**Comment by SijinJohn** [comment]
For me no luck. Will uninstalling help??

**Comment by akashAD98** [comment]
make sure that you have passed correct path for interpreter. like H:\anaconda\Scripts\conda.exe 
it should be conda.exe not anaconda.exe
