### ISSUE TITLE
PermissionError: [Errno 13] Permission denied in Jupyter Notebook

### ISSUE THREAD

**Issue by ArcherWoo** [ContinuumIO/anaconda-issues#10328]
I installed anaconda, and I also install JuliaPro 1.0. I tried to add IJulia package from JuliaPro and tried jupyter on both anaconda and terminal but all failed. 

### Actual Behavior

 ArcherWotekiAir:~ ArcherWoo$ jupyter notebook
Traceback (most recent call last):
  File "/anaconda3/bin/jupyter-notebook", line 11, in <module>
    sys.exit(main())
  File "/anaconda3/lib/python3.7/site-packages/jupyter_core/application.py", line 266, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/anaconda3/lib/python3.7/site-packages/traitlets/config/application.py", line 657, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-7>", line 2, in initialize
  File "/anaconda3/lib/python3.7/site-packages/traitlets/config/application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "/anaconda3/lib/python3.7/site-packages/notebook/notebookapp.py", line 1596, in initialize
    super(NotebookApp, self).initialize(argv)
  File "<decorator-gen-6>", line 2, in initialize
  File "/anaconda3/lib/python3.7/site-packages/traitlets/config/application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "/anaconda3/lib/python3.7/site-packages/jupyter_core/application.py", line 242, in initialize
    self.migrate_config()
  File "/anaconda3/lib/python3.7/site-packages/jupyter_core/application.py", line 168, in migrate_config
    migrate()
  File "/anaconda3/lib/python3.7/site-packages/jupyter_core/migrate.py", line 247, in migrate
    with open(os.path.join(env['jupyter_config'], 'migrated'), 'w') as f:
PermissionError: [Errno 13] Permission denied: '/Users/ArcherWoo/.jupyter/migrated'

### Expected Behavior

to open Just normally install and open jupyter notebook

### Steps to Reproduce

I opened the terminal and entered jupyter notebook.

##### Operating System: Mac OS Mojave

![screen shot 2018-11-14 at 7 50 11 am](https://user-images.githubusercontent.com/43308918/48442358-212ca800-e7e2-11e8-978d-98c36a200e9e.png)

**Comment by goanpeca** [comment]
Please remove this folder an try again

`'/Users/ArcherWoo/.jupyter`

**Comment by llinfeng** [comment]
Just to update about the note on "removing the `~/.jupyter` folder" ==> It did not fix my issue. I keep getting the following error:
![image](https://user-images.githubusercontent.com/5890407/52251847-32f78600-28cd-11e9-8325-fb60c03d2516.png)
