### ISSUE TITLE
Just installed Anaconda 5.3 for windows and it does not run, only Spyder launches

### ISSUE THREAD

**Issue by DSVarsanovich** [ContinuumIO/anaconda-issues#10326]
Downloaded Anaconda 5.3, the installation ran normally, now trying to launch Navigator or Jupyter and I get the black window that pops up and nothing happens. Please advise.

### Actual Behavior

Black window pops up and that is all

### Expected Behavior

Working App

##### `conda info`
it tells me that conda info is uknown command

##### `conda list --show-channel-urls`

```
it tells me that conda list is uknown command
```

**Comment by DSVarsanovich** [comment]
sorry in conda info it tells me that "conda" isn't an external or internal command

**Comment by mingwandroid** [comment]
Did you use the anaconda prompt?

**Comment by DSVarsanovich** [comment]
@mingwandroid Yep

**Comment by mingwandroid** [comment]
This is strange. Can you try using the full path to conda here?

**Comment by DSVarsanovich** [comment]
@mingwandroid sorry, can’t get you. You mean to copy and paste full path to conda here? Or what?

**Comment by mingwandroid** [comment]
Open the anaconda prompt then run:

C:\<full-path-to-anaconda>\Scripts\conda info

.. etc, then paste the results here.

**Comment by DSVarsanovich** [comment]
C:\Users\Пользователь>conda info
Traceback (most recent call last):
  File "D:\Anaconda2\Scripts\conda-script.py", line 10, in <module>
    sys.exit(main())
  File "D:\Anaconda2\lib\site-packages\conda\cli\main.py", line 112, in main
    from ..exceptions import conda_exception_handler
  File "D:\Anaconda2\lib\site-packages\conda\exceptions.py", line 18, in <module
>
    from .common.io import timeout
  File "D:\Anaconda2\lib\site-packages\conda\common\io.py", line 467, in <module
>
    class time_recorder(ContextDecorator):  # pragma: no cover
  File "D:\Anaconda2\lib\site-packages\conda\common\io.py", line 469, in time_re
corder
    record_file = expand(join('~', '.conda', 'instrumentation-record.csv'))
  File "D:\Anaconda2\lib\site-packages\conda\common\path.py", line 51, in expand

    return abspath(expanduser(expandvars(path)))
  File "D:\Anaconda2\lib\ntpath.py", line 311, in expanduser
    return userhome + path[i:]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xcf in position 9: ordinal
not in range(128)

**Comment by DSVarsanovich** [comment]
**Conda info** 
C:\Users\Пользователь>conda info
Traceback (most recent call last):
  File "D:\Anaconda2\Scripts\conda-script.py", line 10, in <module>
    sys.exit(main())
  File "D:\Anaconda2\lib\site-packages\conda\cli\main.py", line 112, in main
    from ..exceptions import conda_exception_handler
  File "D:\Anaconda2\lib\site-packages\conda\exceptions.py", line 18, in <module
>
    from .common.io import timeout
  File "D:\Anaconda2\lib\site-packages\conda\common\io.py", line 467, in <module
>
    class time_recorder(ContextDecorator):  # pragma: no cover
  File "D:\Anaconda2\lib\site-packages\conda\common\io.py", line 469, in time_re
corder
    record_file = expand(join('~', '.conda', 'instrumentation-record.csv'))
  File "D:\Anaconda2\lib\site-packages\conda\common\path.py", line 51, in expand

    return abspath(expanduser(expandvars(path)))
  File "D:\Anaconda2\lib\ntpath.py", line 311, in expanduser
    return userhome + path[i:]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xcf in position 9: ordinal
not in range(128)

**Conda list**
C:\Users\Пользователь>conda list
Traceback (most recent call last):
  File "D:\Anaconda2\Scripts\conda-script.py", line 10, in <module>
    sys.exit(main())
  File "D:\Anaconda2\lib\site-packages\conda\cli\main.py", line 112, in main
    from ..exceptions import conda_exception_handler
  File "D:\Anaconda2\lib\site-packages\conda\exceptions.py", line 18, in <module
>
    from .common.io import timeout
  File "D:\Anaconda2\lib\site-packages\conda\common\io.py", line 467, in <module
>
    class time_recorder(ContextDecorator):  # pragma: no cover
  File "D:\Anaconda2\lib\site-packages\conda\common\io.py", line 469, in time_re
corder
    record_file = expand(join('~', '.conda', 'instrumentation-record.csv'))
  File "D:\Anaconda2\lib\site-packages\conda\common\path.py", line 51, in expand

    return abspath(expanduser(expandvars(path)))
  File "D:\Anaconda2\lib\ntpath.py", line 311, in expanduser
    return userhome + path[i:]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xcf in position 9: ordinal
not in range(128)

**Comment by mingwandroid** [comment]
You cannot use Python 2 with non-ascii characters in either PATH or sys.prefix.

These are bugs in the Python interpreter itself.

I recommend you use Python 3 instead of possible.
