### ISSUE TITLE
Navigator error on opening anconda navigator

### ISSUE THREAD

**Issue by SijinJohn** [ContinuumIO/anaconda-issues#10334]
Navigator Error
An unexpected error occurred on Navigator start-up

Report
Please report this issue in the anaconda issue tracker

Main Error
expected str, bytes or os.PathLike object, not NoneType
Traceback
Traceback (most recent call last):
  File "C:\Users\sijin.john\AppData\Local\Continuum\anaconda3\lib\site-packages\anaconda_navigator\exceptions.py", line 75, in exception_handler
    return_value = func(*args, **kwargs)
  File "C:\Users\sijin.john\AppData\Local\Continuum\anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 150, in start_app
    window = run_app(splash)
  File "C:\Users\sijin.john\AppData\Local\Continuum\anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 65, in run_app
    window = MainWindow(splash=splash, tab_project=False)
  File "C:\Users\sijin.john\AppData\Local\Continuum\anaconda3\lib\site-packages\anaconda_navigator\widgets\main_window.py", line 163, in __init__
    self.api = AnacondaAPI()
  File "C:\Users\sijin.john\AppData\Local\Continuum\anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 2185, in AnacondaAPI
    ANACONDA_API = _AnacondaAPI()
  File "C:\Users\sijin.john\AppData\Local\Continuum\anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 89, in __init__
    self._conda_api = CondaAPI()
  File "C:\Users\sijin.john\AppData\Local\Continuum\anaconda3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 1714, in CondaAPI
    CONDA_API = _CondaAPI()
  File "C:\Users\sijin.john\AppData\Local\Continuum\anaconda3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 353, in __init__
    self.sys_rc_path = join(self.ROOT_PREFIX, '.condarc')
  File "C:\Users\sijin.john\AppData\Local\Continuum\anaconda3\lib\ntpath.py", line 76, in join
    path = os.fspath(path)
TypeError: expected str, bytes or os.PathLike object, not NoneType

### Actual Behavior

anaconda navigator doesn't  open

### Expected Behavior

anaconda navigator should open

##### Operating System:
Windows 10 Pro
Version:-1803
Os build :-17134.1

, paste the output of 'conda info' -->
```
Traceback (most recent call last):
  File "c:\users\sijin.john\appdata\local\continuum\anaconda3\envs\tensorflow\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\sijin.john\appdata\local\continuum\anaconda3\envs\tensorflow\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\sijin.john\AppData\Local\Continuum\anaconda3\Scripts\conda.exe\__main__.py", line 9, in <module>
  File "c:\users\sijin.john\appdata\local\continuum\anaconda3\envs\tensorflow\lib\site-packages\markdown\__main__.py", line 138, in run
    markdown.markdownFromFile(**options)
  File "c:\users\sijin.john\appdata\local\continuum\anaconda3\envs\tensorflow\lib\site-packages\markdown\core.py", line 411, in markdownFromFile
    kwargs.get('encoding', None))
  File "c:\users\sijin.john\appdata\local\continuum\anaconda3\envs\tensorflow\lib\site-packages\markdown\core.py", line 325, in convertFile
    input_file = codecs.open(input, mode="r", encoding=encoding)
  File "c:\users\sijin.john\appdata\local\continuum\anaconda3\envs\tensorflow\lib\codecs.py", line 895, in open
    file = builtins.open(filename, mode, buffering)
FileNotFoundError: [Errno 2] No such file or directory: 'info'
```

##### `conda list --show-channel-urls`

```
Usage: conda [options] [INPUTFILE]
       (STDIN is assumed if no INPUTFILE is given)

conda: error: no such option: --show-channel-urls
```

**Comment by SijinJohn** [comment]
Anaconda or Miniconda version:-
Usage: conda [options] [INPUTFILE]
       (STDIN is assumed if no INPUTFILE is given)

conda: error: no such option: --json
usage: anaconda [-h] [--disable-ssl-warnings] [--show-traceback] [-v] [-q]
                [-V] [-t TOKEN] [-s SITE]
                ...
anaconda: error: argument : invalid choice: 'or' (choose from 'auth', 'label', 'channel', 'config', 'copy', 'download', 'groups', 'login', 'logout', 'notebook', 'package', 'remove', 'search', 'show', 'upload', 'whoami')

**Comment by goanpeca** [comment]
Pleas try reinstalling in a shorter path

Something like

`C:\Users\sijin.john\Anaconda3`

**Comment by SijinJohn** [comment]
goanpeca

> Pleas try reinstalling in a shorter path
> 
> Something like
> 
> `C:\Users\sijin.john\Anaconda3`

i deleted the condarc file when i did a as per your replies to similar posts. But tha didnot solve the problem .i reinstalled the new anconda at C:\Users\sijin.john\Anaconda3  but is lost the old environment and packages.
