### ISSUE TITLE
An unexpected error occurred on Navigator start-up

### ISSUE THREAD

**Issue by zzhChris** [ContinuumIO/anaconda-issues#10336]
### Actual Behavior
An unexpected error occurred on Navigator start-up

byte indices must be integers or slices, not str

### Expected Behavior
the navigator should be open

the navigator should be open

##### `conda info`

Traceback (most recent call last):
  File "C:\Users\zzhch\Anaconda3\lib\site-packages\anaconda_navigator\exceptions.py", line 75, in exception_handler
    return_value = func(*args, **kwargs)
  File "C:\Users\zzhch\Anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 120, in start_app
    window = run_app(splash)
  File "C:\Users\zzhch\Anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 63, in run_app
    window = MainWindow(splash=splash)
  File "C:\Users\zzhch\Anaconda3\lib\site-packages\anaconda_navigator\widgets\main_window.py", line 163, in __init__
    self.api = AnacondaAPI()
  File "C:\Users\zzhch\Anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 2004, in AnacondaAPI
    ANACONDA_API = _AnacondaAPI()
  File "C:\Users\zzhch\Anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 88, in __init__
    self._conda_api = CondaAPI()
  File "C:\Users\zzhch\Anaconda3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 1690, in CondaAPI
    CONDA_API = _CondaAPI()
  File "C:\Users\zzhch\Anaconda3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 347, in __init__
    self.set_conda_prefix()
  File "C:\Users\zzhch\Anaconda3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 496, in set_conda_prefix
    self.ROOT_PREFIX = info['root_prefix']
TypeError: byte indices must be integers or slices, not str
```

##### `conda list --show-channel-urls`
<!-- between the ticks below, paste the output of 'conda list --show-channel-urls' -->
```

```

**Comment by zzhChris** [comment]
# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "C:\Users\zzhch\Anaconda3\lib\site-packages\conda\cli\main.py", line 97, in main
        from ..activate import main as activator_main
      File "C:\Users\zzhch\Anaconda3\lib\site-packages\conda\activate.py", line 15, in <module>
        context.__init__()  # oOn import, context does not include SEARCH_PATH. This line fixes that.
      File "C:\Users\zzhch\Anaconda3\lib\site-packages\conda\base\context.py", line 237, in __init__
        argparse_args=argparse_args)
      File "C:\Users\zzhch\Anaconda3\lib\site-packages\conda\common\configuration.py", line 722, in __init__
        self._set_search_path(search_path)
      File "C:\Users\zzhch\Anaconda3\lib\site-packages\conda\common\configuration.py", line 728, in _set_search_path
        self._set_raw_data(load_file_configs(search_path))
      File "C:\Users\zzhch\Anaconda3\lib\site-packages\conda\common\configuration.py", line 369, in load_file_configs
        raw_data = odict(kv for kv in chain.from_iterable(load_paths))
      File "C:\Users\zzhch\Anaconda3\lib\site-packages\conda\common\configuration.py", line 369, in <genexpr>
        raw_data = odict(kv for kv in chain.from_iterable(load_paths))
      File "C:\Users\zzhch\Anaconda3\lib\site-packages\conda\common\configuration.py", line 344, in _file_yaml_loader
        yield fullpath, YamlRawParameter.make_raw_parameters_from_file(fullpath)
      File "C:\Users\zzhch\Anaconda3\lib\site-packages\conda\common\configuration.py", line 332, in make_raw_parameters_from_file
        ruamel_yaml = yaml_load(fh)
      File "C:\Users\zzhch\Anaconda3\lib\site-packages\conda\common\serialize.py", line 54, in yaml_load
        return yaml.load(string, Loader=yaml.RoundTripLoader, version="1.2")
      File "C:\Users\zzhch\Anaconda3\lib\site-packages\ruamel_yaml\main.py", line 638, in load
        loader = Loader(stream, version, preserve_quotes=preserve_quotes)
      File "C:\Users\zzhch\Anaconda3\lib\site-packages\ruamel_yaml\loader.py", line 59, in __init__
        Reader.__init__(self, stream, loader=self)
      File "C:\Users\zzhch\Anaconda3\lib\site-packages\ruamel_yaml\reader.py", line 80, in __init__
        self.stream = stream  # type: Any  # as .read is called
      File "C:\Users\zzhch\Anaconda3\lib\site-packages\ruamel_yaml\reader.py", line 125, in stream
        self.determine_encoding()
      File "C:\Users\zzhch\Anaconda3\lib\site-packages\ruamel_yaml\reader.py", line 180, in determine_encoding
        self.update(1)
      File "C:\Users\zzhch\Anaconda3\lib\site-packages\ruamel_yaml\reader.py", line 266, in update
        self.check_printable(data)
      File "C:\Users\zzhch\Anaconda3\lib\site-packages\ruamel_yaml\reader.py", line 233, in check_printable
        'unicode', "special characters are not allowed")
    ruamel_yaml.reader.ReaderError: unacceptable character #x0000: special characters are not allowed
      in "C:\Users\zzhch\.condarc", position 0

`$ C:\Users\zzhch\Anaconda3\Scripts\conda shell.cmd.exe activate activate C:\Users\zzhch\Anaconda3`

  environment variables:
                 CIO_TEST=<not set>
               CONDA_ROOT=C:\Users\zzhch\Anaconda3
          EQ_LIBRARY_PATH=C:\MinGW\x86_64-w64-mingw32\lib
                 HOMEPATH=\Users\zzhch
                     PATH=C:\MinGW\bin;C:\MinGW\libexec\gcc\x86_64-w64-mingw32\7.2.0;C:\Program
                          Files (x86)\Razer Chroma SDK\bin;C:\Program Files\Razer Chroma
                          SDK\bin;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program
                          Files\Intel\iCLS Client\;C:\Windows\system32;C:\Windows;C:\Windows\Sys
                          tem32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program
                          Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program
                          Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files
                          (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program
                          Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files
                          (x86)\NVIDIA Corporation\PhysX\Common;C:\Users\Administrator\AppData\L
                          ocal\Microsoft\WindowsApps;C:\Program
                          Files\MATLAB\R2017b\runtime\win64;C:\Program Files\MATLAB\R2017b\bin;C
                          :\texlive\2017\bin\win32;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\Sys
                          tem32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\Syst
                          em32\OpenSSH\;C:\Users\zzhch\AppData\Local\Microsoft\WindowsApps;;C:\P
                          rogram Files\Microsoft VS Code\bin
             PSMODULEPATH=C:\Program Files\WindowsPowerShell\Modules;C:\WINDOWS\system32\Windows
                          PowerShell\v1.0\Modules
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>
    VBOX_MSI_INSTALL_PATH=C:\virtualbox\

     active environment : None
       user config file : C:\Users\zzhch\.condarc
 populated config files :
          conda version : 4.5.11
    conda-build version : 3.15.1
         python version : 3.7.0.final.0
       base environment : C:\Users\zzhch\Anaconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/win-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/win-64
                          https://repo.anaconda.com/pkgs/pro/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\Users\zzhch\Anaconda3\pkgs
                          C:\Users\zzhch\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\zzhch\Anaconda3\envs
                          C:\Users\zzhch\AppData\Local\conda\conda\envs
                          C:\Users\zzhch\.conda\envs
               platform : win-64
             user-agent : conda/4.5.11 requests/2.19.1 CPython/3.7.0 Windows/10 Windows/10.0.17134
          administrator : False
             netrc file : None
           offline mode : False


An unexpected error has occurred. Conda has prepared the above report.
If submitted, this report will be used by core maintainers to improve
future releases of conda.
Would you like conda to send this report to the core maintainers?
[y/N]: y
Upload successful.

Thank you for helping to improve conda.
Opt-in to always sending reports (and not see this message again)
by running

    $ conda config --set report_errors true

**Comment by goanpeca** [comment]
Please delete this file `C:\Users\zzhch\.condarc` and try again
