### ISSUE TITLE
ncurses from defaults breaks fiona from conda-forge on linux

### ISSUE THREAD

**Issue by dopplershift** [ContinuumIO/anaconda-issues#10345]
Noticed on Linux CI for [cartopy](https://github.com/SciTools/cartopy/pull/1205). If I install all packages from conda-forge, fiona is fine to import. If instead a defaults environment is created, then fiona is installed from conda-forge, things don't work:

```
$ python -c 'import fiona'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/osboxes/miniconda3/envs/test/lib/python3.6/site-packages/fiona/__init__.py", line 83, in <module>
    from fiona.collection import BytesCollection, Collection
  File "/home/osboxes/miniconda3/envs/test/lib/python3.6/site-packages/fiona/collection.py", line 9, in <module>
    from fiona.ogrext import Iterator, ItemsIterator, KeysIterator
ImportError: libncurses.so.6: cannot open shared object file: No such file or directory
```

Here's the linking information, showing the missing ncurses:
```
~$ ldd miniconda3/envs/test/lib/python3.6/site-packages/fiona/ogrext.cpython-36m-x86_64-linux-gnu.so 
	linux-vdso.so.1 =>  (0x00007ffd2a1ee000)
	libgdal.so.20 => /home/osboxes/miniconda3/envs/test/lib/python3.6/site-packages/fiona/../../../libgdal.so.20 (0x00007fd1543c8000)
	libpython3.6m.so.1.0 => /home/osboxes/miniconda3/envs/test/lib/python3.6/site-packages/fiona/../../../libpython3.6m.so.1.0 (0x00007fd153e8b000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fd153c6d000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fd1538a4000)
	libcrypto.so.1.0.0 => /home/osboxes/miniconda3/envs/test/lib/python3.6/site-packages/fiona/../../.././libcrypto.so.1.0.0 (0x00007fd153453000)
	libproj.so.12 => /home/osboxes/miniconda3/envs/test/lib/python3.6/site-packages/fiona/../../.././libproj.so.12 (0x00007fd1531cb000)
	libpoppler.so.78 => /home/osboxes/miniconda3/envs/test/lib/python3.6/site-packages/fiona/../../.././libpoppler.so.78 (0x00007fd152d2f000)
	libjson-c.so.2 => /home/osboxes/miniconda3/envs/test/lib/python3.6/site-packages/fiona/../../.././libjson-c.so.2 (0x00007fd152b22000)
	libfreexl.so.1 => /home/osboxes/miniconda3/envs/test/lib/python3.6/site-packages/fiona/../../.././libfreexl.so.1 (0x00007fd152915000)
	libgeos_c.so.1 => /home/osboxes/miniconda3/envs/test/lib/python3.6/site-packages/fiona/../../.././libgeos_c.so.1 (0x00007fd1526c8000)
	libsqlite3.so.0 => /home/osboxes/miniconda3/envs/test/lib/python3.6/site-packages/fiona/../../.././libsqlite3.so.0 (0x00007fd155c7f000)
	libkmlbase.so.1 => /home/osboxes/miniconda3/envs/test/lib/python3.6/site-packages/fiona/../../.././libkmlbase.so.1 (0x00007fd1524ad000)
	libkmldom.so.1 => /home/osboxes/miniconda3/envs/test/lib/python3.6/site-packages/fiona/../../.././libkmldom.so.1 (0x00007fd1521f9000)
	libkmlengine.so.1 => /home/osboxes/miniconda3/envs/test/lib/python3.6/site-packages/fiona/../../.././libkmlengine.so.1 (0x00007fd151fc0000)
	libkmlxsd.so.1 => /home/osboxes/miniconda3/envs/test/lib/python3.6/site-packages/fiona/../../.././libkmlxsd.so.1 (0x00007fd151da9000)
	libkmlregionator.so.1 => /home/osboxes/miniconda3/envs/test/lib/python3.6/site-packages/fiona/../../.././libkmlregionator.so.1 (0x00007fd151b9e000)
	libexpat.so.1 => /home/osboxes/miniconda3/envs/test/lib/python3.6/site-packages/fiona/../../.././libexpat.so.1 (0x00007fd151969000)
	libxerces-c-3.2.so => /home/osboxes/miniconda3/envs/test/lib/python3.6/site-packages/fiona/../../.././libxerces-c-3.2.so (0x00007fd1512d6000)
	libopenjp2.so.7 => /home/osboxes/miniconda3/envs/test/lib/python3.6/site-packages/fiona/../../.././libopenjp2.so.7 (0x00007fd151060000)
	libnetcdf.so.13 => /home/osboxes/miniconda3/envs/test/lib/python3.6/site-packages/fiona/../../.././libnetcdf.so.13 (0x00007fd150d08000)
	libhdf5_hl.so.100 => /home/osboxes/miniconda3/envs/test/lib/python3.6/site-packages/fiona/../../.././libhdf5_hl.so.100 (0x00007fd150ae6000)
	libmfhdf.so.0 => /home/osboxes/miniconda3/envs/test/lib/python3.6/site-packages/fiona/../../.././libmfhdf.so.0 (0x00007fd1508bb000)
	libdf.so.0 => /home/osboxes/miniconda3/envs/test/lib/python3.6/site-packages/fiona/../../.././libdf.so.0 (0x00007fd150607000)
	libgif.so.7 => /home/osboxes/miniconda3/envs/test/lib/python3.6/site-packages/fiona/../../.././libgif.so.7 (0x00007fd1503fd000)
	libjpeg.so.9 => /home/osboxes/miniconda3/envs/test/lib/python3.6/site-packages/fiona/../../.././libjpeg.so.9 (0x00007fd1501ab000)
	libgeotiff.so.2 => /home/osboxes/miniconda3/envs/test/lib/python3.6/site-packages/fiona/../../.././libgeotiff.so.2 (0x00007fd14ff76000)
	libtiff.so.5 => /home/osboxes/miniconda3/envs/test/lib/python3.6/site-packages/fiona/../../.././libtiff.so.5 (0x00007fd14fce3000)
	libpng16.so.16 => /home/osboxes/miniconda3/envs/test/lib/python3.6/site-packages/fiona/../../.././libpng16.so.16 (0x00007fd14faa2000)
	libpq.so.5 => /home/osboxes/miniconda3/envs/test/lib/python3.6/site-packages/fiona/../../.././libpq.so.5 (0x00007fd14f852000)
	libdap.so.25 => /home/osboxes/miniconda3/envs/test/lib/python3.6/site-packages/fiona/../../.././libdap.so.25 (0x00007fd14f3c3000)
	libdapserver.so.7 => /home/osboxes/miniconda3/envs/test/lib/python3.6/site-packages/fiona/../../.././libdapserver.so.7 (0x00007fd14f1b5000)
	libdapclient.so.6 => /home/osboxes/miniconda3/envs/test/lib/python3.6/site-packages/fiona/../../.././libdapclient.so.6 (0x00007fd14ef38000)
	libuuid.so.1 => /home/osboxes/miniconda3/envs/test/lib/python3.6/site-packages/fiona/../../.././libuuid.so.1 (0x00007fd14ed31000)
	libspatialite.so.7 => /home/osboxes/miniconda3/envs/test/lib/python3.6/site-packages/fiona/../../.././libspatialite.so.7 (0x00007fd14e3f8000)
	libpcre.so.1 => /home/osboxes/miniconda3/envs/test/lib/python3.6/site-packages/fiona/../../.././libpcre.so.1 (0x00007fd14e1a7000)
	libcurl.so.4 => /home/osboxes/miniconda3/envs/test/lib/python3.6/site-packages/fiona/../../.././libcurl.so.4 (0x00007fd14df29000)
	libxml2.so.2 => /home/osboxes/miniconda3/envs/test/lib/python3.6/site-packages/fiona/../../.././libxml2.so.2 (0x00007fd14db64000)
	liblzma.so.5 => /home/osboxes/miniconda3/envs/test/lib/python3.6/site-packages/fiona/../../.././liblzma.so.5 (0x00007fd14d93e000)
	libiconv.so.2 => /home/osboxes/miniconda3/envs/test/lib/python3.6/site-packages/fiona/../../.././libiconv.so.2 (0x00007fd14d64f000)
	libicui18n.so.58 => /home/osboxes/miniconda3/envs/test/lib/python3.6/site-packages/fiona/../../.././libicui18n.so.58 (0x00007fd14d14f000)
	libicuuc.so.58 => /home/osboxes/miniconda3/envs/test/lib/python3.6/site-packages/fiona/../../.././libicuuc.so.58 (0x00007fd14cd50000)
	libicudata.so.58 => /home/osboxes/miniconda3/envs/test/lib/python3.6/site-packages/fiona/../../.././libicudata.so.58 (0x00007fd14b250000)
	libkea.so.1.4 => /home/osboxes/miniconda3/envs/test/lib/python3.6/site-packages/fiona/../../.././libkea.so.1.4 (0x00007fd14afea000)
	libhdf5_cpp.so.103 => /home/osboxes/miniconda3/envs/test/lib/python3.6/site-packages/fiona/../../.././libhdf5_cpp.so.103 (0x00007fd14ad83000)
	libhdf5.so.103 => /home/osboxes/miniconda3/envs/test/lib/python3.6/site-packages/fiona/../../.././libhdf5.so.103 (0x00007fd14a7ca000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007fd14a5c2000)
	libz.so.1 => /home/osboxes/miniconda3/envs/test/lib/python3.6/site-packages/fiona/../../.././libz.so.1 (0x00007fd14a3ab000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fd14a1a7000)
	libstdc++.so.6 => /home/osboxes/miniconda3/envs/test/lib/python3.6/site-packages/fiona/../../.././libstdc++.so.6 (0x00007fd14a066000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fd149d60000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fd155b8a000)
	libgcc_s.so.1 => /home/osboxes/miniconda3/envs/test/lib/python3.6/site-packages/fiona/../../.././libgcc_s.so.1 (0x00007fd155c5b000)
	libutil.so.1 => /lib/x86_64-linux-gnu/libutil.so.1 (0x00007fd149b5d000)
	libfreetype.so.6 => /home/osboxes/miniconda3/envs/test/lib/python3.6/site-packages/fiona/../../../././libfreetype.so.6 (0x00007fd14987e000)
	libfontconfig.so.1 => /home/osboxes/miniconda3/envs/test/lib/python3.6/site-packages/fiona/../../../././libfontconfig.so.1 (0x00007fd14962f000)
	libgeos-3.6.2.so => /home/osboxes/miniconda3/envs/test/lib/python3.6/site-packages/fiona/../../../././libgeos-3.6.2.so (0x00007fd14908c000)
	libminizip.so => /home/osboxes/miniconda3/envs/test/lib/python3.6/site-packages/fiona/../../../././libminizip.so (0x00007fd148e81000)
	liburiparser.so => /home/osboxes/miniconda3/envs/test/lib/python3.6/site-packages/fiona/../../../././liburiparser.so (0x00007fd148c65000)
	libkmlconvenience.so.1 => /home/osboxes/miniconda3/envs/test/lib/python3.6/site-packages/fiona/../../../././libkmlconvenience.so.1 (0x00007fd148a48000)
	libssl.so.1.0.0 => /home/osboxes/miniconda3/envs/test/lib/python3.6/site-packages/fiona/../../../././libssl.so.1.0.0 (0x00007fd1487cf000)
	libgssapi_krb5.so.2 => /home/osboxes/miniconda3/envs/test/lib/python3.6/site-packages/fiona/../../../././libgssapi_krb5.so.2 (0x00007fd148575000)
	libncurses.so.6 => not found
	libtinfo.so.6 => not found
	libcharset.so.1 => /home/osboxes/miniconda3/envs/test/lib/python3.6/site-packages/fiona/../../../././libcharset.so.1 (0x00007fd148373000)
	libssh2.so.1 => /home/osboxes/miniconda3/envs/test/lib/python3.6/site-packages/fiona/../../../././libssh2.so.1 (0x00007fd14813b000)
	libkrb5.so.3 => /home/osboxes/miniconda3/envs/test/lib/python3.6/site-packages/fiona/../../../././libkrb5.so.3 (0x00007fd147e46000)
	libk5crypto.so.3 => /home/osboxes/miniconda3/envs/test/lib/python3.6/site-packages/fiona/../../../././libk5crypto.so.3 (0x00007fd147c25000)
	libcom_err.so.3 => /home/osboxes/miniconda3/envs/test/lib/python3.6/site-packages/fiona/../../../././libcom_err.so.3 (0x00007fd147a22000)
	libhdf5_hl_cpp.so.100 => /home/osboxes/miniconda3/envs/test/lib/python3.6/site-packages/fiona/../../../././libhdf5_hl_cpp.so.100 (0x00007fd14781f000)
	libkrb5support.so.0 => /home/osboxes/miniconda3/envs/test/lib/python3.6/site-packages/fiona/../../.././././libkrb5support.so.0 (0x00007fd147612000)
	libresolv.so.2 => /lib/x86_64-linux-gnu/libresolv.so.2 (0x00007fd1473f7000)
```

and the `conda list`:
```
# packages in environment at /home/osboxes/miniconda3/envs/test:
#
# Name                    Version                   Build  Channel
attrs                     18.2.0                     py_0    conda-forge
blas                      1.0                         mkl    defaults
boost-cpp                 1.67.0               h3a22d5f_0    conda-forge
bzip2                     1.0.6                h470a237_2    conda-forge
ca-certificates           2018.10.15           ha4d7672_0    conda-forge
cairo                     1.14.12              he6fea26_5    conda-forge
certifi                   2018.10.15            py36_1000    conda-forge
click                     7.0                        py_0    conda-forge
click-plugins             1.0.4                      py_0    conda-forge
cligj                     0.5.0                      py_0    conda-forge
curl                      7.62.0               h74213dd_0    conda-forge
expat                     2.2.5                hfc679d8_2    conda-forge
fiona                     1.8.1            py36hfc77a4a_0    conda-forge
fontconfig                2.13.1               h65d0f4c_0    conda-forge
freetype                  2.9.1                h6debe1e_4    conda-forge
freexl                    1.0.5                h470a237_2    conda-forge
gdal                      2.3.2            py36hb00a9d7_0    conda-forge
geos                      3.6.2                hfc679d8_3    conda-forge
geotiff                   1.4.2                h700e5ad_5    conda-forge
gettext                   0.19.8.1             h5e8e0c9_1    conda-forge
giflib                    5.1.4                h470a237_1    conda-forge
glib                      2.55.0               h464dc38_2    conda-forge
hdf4                      4.2.13               h951d187_2    conda-forge
hdf5                      1.10.3               hc401514_2    conda-forge
icu                       58.2                 hfc679d8_0    conda-forge
intel-openmp              2019.1                      144    defaults
jpeg                      9c                   h470a237_1    conda-forge
json-c                    0.12.1               h470a237_1    conda-forge
kealib                    1.4.10               hb88cf67_0    conda-forge
krb5                      1.16.2               hbb41f41_0    conda-forge
libcurl                   7.62.0               hbdb9355_0    conda-forge
libdap4                   3.19.1               h8fe5423_1    conda-forge
libedit                   3.1.20170329         h6b74fdf_2    defaults
libffi                    3.2.1                hd88cf55_4    defaults
libgcc-ng                 8.2.0                hdf63c60_1    defaults
libgdal                   2.3.2                hc73897a_0    conda-forge
libgfortran               3.0.0                         1    conda-forge
libgfortran-ng            7.2.0                hdf63c60_3    conda-forge
libiconv                  1.15                 h470a237_3    conda-forge
libkml                    1.3.0                hccc92b1_8    conda-forge
libnetcdf                 4.6.1               h9cd6fdc_11    conda-forge
libpng                    1.6.35               ha92aebf_2    conda-forge
libpq                     10.5                 he29860b_0    conda-forge
libspatialite             4.3.0a              hdfcc80b_23    conda-forge
libssh2                   1.8.0                h5b517e9_3    conda-forge
libstdcxx-ng              8.2.0                hdf63c60_1    defaults
libtiff                   4.0.9                he6b73bb_2    conda-forge
libuuid                   2.32.1               h470a237_2    conda-forge
libxcb                    1.13                 h470a237_2    conda-forge
libxml2                   2.9.8                h422b904_5    conda-forge
mkl                       2019.1                      144    defaults
mkl_fft                   1.0.6                    py36_0    conda-forge
mkl_random                1.0.2                    py36_0    conda-forge
munch                     2.3.2                      py_0    conda-forge
ncurses                   6.1                  hf484d3e_0    defaults
numpy                     1.15.4           py36h1d66e8a_0    defaults
numpy-base                1.15.4           py36h81de0dd_0    defaults
openjpeg                  2.3.0                h0e734dc_3    conda-forge
openssl                   1.0.2p               h470a237_1    conda-forge
pcre                      8.41                 hfc679d8_3    conda-forge
pip                       18.1                     py36_0    defaults
pixman                    0.34.0               h470a237_3    conda-forge
poppler                   0.67.0               h4d7e492_3    conda-forge
poppler-data              0.4.9                         0    conda-forge
postgresql                10.5                 h66035e0_0    conda-forge
proj4                     4.9.3                h470a237_8    conda-forge
pthread-stubs             0.4                  h470a237_1    conda-forge
python                    3.6.6                h5001a0f_3    conda-forge
readline                  7.0                  h7b6447c_5    defaults
setuptools                40.6.2                   py36_0    defaults
shapely                   1.6.4            py36h164cb2d_1    conda-forge
six                       1.11.0                py36_1001    conda-forge
sqlite                    3.25.3               h7b6447c_0    defaults
tk                        8.6.8                hbc83047_0    defaults
wheel                     0.32.3                   py36_0    defaults
xerces-c                  3.2.0                h5d6a6da_2    conda-forge
xorg-kbproto              1.0.7                h470a237_2    conda-forge
xorg-libice               1.0.9                h470a237_4    conda-forge
xorg-libsm                1.2.3                h8c8a85c_0    conda-forge
xorg-libx11               1.6.6                h470a237_0    conda-forge
xorg-libxau               1.0.8                h470a237_6    conda-forge
xorg-libxdmcp             1.1.2                h470a237_7    conda-forge
xorg-libxext              1.3.3                h470a237_4    conda-forge
xorg-libxrender           0.9.10               h470a237_2    conda-forge
xorg-renderproto          0.11.1               h470a237_2    conda-forge
xorg-xextproto            7.3.0                h470a237_2    conda-forge
xorg-xproto               7.0.31               h470a237_7    conda-forge
xz                        5.2.4                h14c3975_4    defaults
zlib                      1.2.11               ha838bed_2    defaults
```

**Comment by dopplershift** [comment]
ping @jjhelmus

**Comment by ccordoba12** [comment]
Conda-forge and defaults can't be mixed because they have different compilation specs. And even when they manage to have the same specs, conda-forge purports to be a full replacement to defaults, so it's packages can still differ from defaults.

**Comment by msarahan** [comment]
https://conda-forge.org/docs/conda-forge_gotchas.html#using-multiple-channels

This will get better over time with the rebuild using the new compilers.

**Comment by dopplershift** [comment]
To be clear @jjhelmus asked me to report on the Conda-forge Gitter.

I’m happy just having things work and was honestly surprised that Cartopy’s CI was set up to mix things before. Anyhow, thanks for the hard work on Anaconda/Conda!

**Comment by jjhelmus** [comment]
Thanks for the report @dopplershift.  Although `conda-forge` and `defaults` are incompatible a good goal is to fixes these incompatibilities when possible.  In this case the issue will not be fixed by rebuilding with the new compilers.  

The `conda-forge` package builds both a wide and non-wide version of the libraries so a full set of libraries is available for both variants (libncurses.so, libncurses.so.6, libncurses.so.6.1 as well libncursesw.so, libncursesw.so.6, libncursesw.so.6.1).  `defaults` builds the wide version and symlink to the non-wide libraries for the main DSO (libncursesw.so, libncursesw.so.6, libncursesw.so.6.1 and (libncurses.so but not libncurses.so.6, libncurses.so.6.1).  Since the wide version is compatible with the non-wide there should be no issue providing the symlinks to libncurses.so.6 and libncurses.so.6.1 in the `defaults` package.

**Comment by mingwandroid** [comment]
I did this to save memory btw. I don't want 2 different python modules each loading in different .so files for ncurses.

**Comment by jjhelmus** [comment]
The latest build (_1) of ncurses in defaults includes the necessary symlinks to the non-wide libraries to fix this issue.  `fiona` now imports with ncurses from `conda-forge` or `defaults`

**Comment by mingwandroid** [comment]
Nice, thanks @jjhelmus.
