### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by vincent27hugh** [ContinuumIO/anaconda-issues#10360]
## Main error
Application <b>spyder</b> launch may have produced errors.
## Traceback
```
Traceback (most recent call last):
  File "/Users/huwei/anaconda/envs/py36/lib/python3.6/site-packages/spyder/app/mainwindow.py", line 3208, in main
    mainwindow = run_spyder(app, options, args)
  File "/Users/huwei/anaconda/envs/py36/lib/python3.6/site-packages/spyder/app/mainwindow.py", line 3084, in run_spyder
    main.setup()
  File "/Users/huwei/anaconda/envs/py36/lib/python3.6/site-packages/spyder/app/mainwindow.py", line 848, in setup
    from spyder.plugins.editor import Editor
  File "/Users/huwei/anaconda/envs/py36/lib/python3.6/site-packages/spyder/plugins/editor.py", line 41, in <module>
    from spyder.utils.introspection.manager import IntrospectionManager
  File "/Users/huwei/anaconda/envs/py36/lib/python3.6/site-packages/spyder/utils/introspection/manager.py", line 21, in <module>
    from spyder.utils.introspection.plugin_client import PluginClient
  File "/Users/huwei/anaconda/envs/py36/lib/python3.6/site-packages/spyder/utils/introspection/plugin_client.py", line 18, in <module>
    import zmq
  File "/Users/huwei/anaconda/envs/py36/lib/python3.6/site-packages/zmq/__init__.py", line 42, in <module>
    _load_libzmq()
  File "/Users/huwei/anaconda/envs/py36/lib/python3.6/site-packages/zmq/__init__.py", line 13, in _load_libzmq
    PYPY = platform.python_implementation().lower() == 'pypy'
  File "/Users/huwei/anaconda/envs/py36/lib/python3.6/platform.py", line 1234, in python_implementation
    return _sys_version()[0]
  File "/Users/huwei/anaconda/envs/py36/lib/python3.6/platform.py", line 1192, in _sys_version
    repr(sys_version))
ValueError: failed to parse CPython sys.version: '3.6.5 |Anaconda, Inc.| (default, Mar 29 2018, 13:14:23) \n[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)]'

```
## System information
```
platform: osx-64
version: 1.6.2
conda: 4.5.11
qt: 5.6.2
language: en
python: 2.7.3
os: Darwin;15.6.0;Darwin Kernel Version 15.6.0: Fri Feb 17 10:21:18 PST 2017; root:xnu-3248.60.11.4.1~1/RELEASE_X86_64;x86_64;i386
pyqt: 5.6.0
```

**Comment by goanpeca** [comment]
Please remember to update to the latest version of Navigator to include
the latest fixes.

Open a terminal (on Linux or Mac) or the Anaconda Command Prompt (on windows)
and type:

```
conda update conda
conda update --all
```
