### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by Mr-DOW** [ContinuumIO/anaconda-issues#10376]
## Main error
Application <b>spyder</b> launch may have produced errors.
## Traceback
```
Traceback (most recent call last):
  File "E:\Anaconda3\Anaconda\lib\site-packages\spyder\app\mainwindow.py", line 3011, in main
    mainwindow = run_spyder(app, options, args)
  File "E:\Anaconda3\Anaconda\lib\site-packages\spyder\app\mainwindow.py", line 2913, in run_spyder
    main.setup()
  File "E:\Anaconda3\Anaconda\lib\site-packages\spyder\app\mainwindow.py", line 799, in setup
    from spyder.plugins.editor import Editor
  File "E:\Anaconda3\Anaconda\lib\site-packages\spyder\plugins\editor.py", line 43, in <module>
    from spyder.widgets.editor import (EditorMainWindow, EditorSplitter,
  File "E:\Anaconda3\Anaconda\lib\site-packages\spyder\widgets\editor.py", line 42, in <module>
    from spyder.widgets.fileswitcher import FileSwitcher
ModuleNotFoundError: No module named 'spyder.widgets.fileswitcher'

```
## System information
```
python: 3.6.1
language: zh_CN
os: Windows;10;10.0.17763;AMD64;Intel64 Family 6 Model 158 Stepping 10, GenuineIntel
version: 1.6.2
platform: win-64
qt: 5.6.2
pyqt: 5.6.0
conda: 4.3.21
```

**Comment by goanpeca** [comment]
Please remember to update to the latest version of Navigator to include
the latest fixes.

Open a terminal (on Linux or Mac) or the Anaconda Command Prompt (on windows)
and type:

```
conda update conda
conda update --all
```
