### ISSUE TITLE
Anaconda Won't Open Spyder (Mac)

### ISSUE THREAD

**Issue by bboresow** [ContinuumIO/anaconda-issues#10380]
I open Anaconda-Navigator. Under Spyder (3.3.2) I click "Launch". The message Launching Spyder appears in the lower left hand corner and the blue progress bar starts running. After about 5-7 seconds I receive the following "Application spyder launch may have produced errors"

Along with the following error message:
Traceback (most recent call last):
File "/Users/brett/anaconda3/lib/python3.7/site-packages/qtpy/QtWebEngineWidgets.py", line 22, in 
from PyQt5.QtWebEngineWidgets import QWebEnginePage
ImportError: dlopen(/Users/brett/anaconda3/lib/python3.7/site-packages/PyQt5/QtWebEngineWidgets.so, 2): Library not loaded: @rpath/libQt5WebEngineCore.5.dylib
Referenced from: /Users/brett/anaconda3/lib/python3.7/site-packages/PyQt5/QtWebEngineWidgets.so
Reason: image not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/Users/brett/anaconda3/bin/spyder", line 11, in 
sys.exit(main())
File "/Users/brett/anaconda3/lib/python3.7/site-packages/spyder/app/start.py", line 186, in main
from spyder.app import mainwindow
File "/Users/brett/anaconda3/lib/python3.7/site-packages/spyder/app/mainwindow.py", line 90, in 
from qtpy import QtWebEngineWidgets # analysis:ignore
File "/Users/brett/anaconda3/lib/python3.7/site-packages/qtpy/QtWebEngineWidgets.py", line 26, in 
from PyQt5.QtWebKitWidgets import QWebPage as QWebEnginePage
ModuleNotFoundError: No module named 'PyQt5.QtWebKitWidgets'

##### `conda info`
active environment : base
    active env location : /anaconda3
            shell level : 2
       user config file : /Users/brett/.condarc
 populated config files : /Users/brett/.condarc
          conda version : 4.5.11
    conda-build version : 3.15.1
         python version : 3.7.0.final.0
       base environment : /anaconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/osx-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/osx-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/osx-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/osx-64
                          https://repo.anaconda.com/pkgs/pro/noarch
          package cache : /anaconda3/pkgs
                          /Users/brett/.conda/pkgs
       envs directories : /anaconda3/envs
                          /Users/brett/.conda/envs
               platform : osx-64
             user-agent : conda/4.5.11 requests/2.19.1 CPython/3.7.0 Darwin/17.7.0 OSX/10.13.6
                UID:GID : 501:20
             netrc file : None
           offline mode : False
```

```
# Name                    Version                   Build  Channel
_ipyw_jlab_nb_ext_conf    0.1.0                    py37_0    defaults
alabaster                 0.7.11                   py37_0    defaults
anaconda                  5.3.1                    py37_0    defaults
anaconda-client           1.7.2                    py37_0    defaults
anaconda-navigator        1.9.2                    py37_0    defaults
anaconda-project          0.8.2                    py37_0    defaults
appdirs                   1.4.3            py37h28b3542_0    defaults
appnope                   0.1.0                    py37_0    defaults
appscript                 1.0.1            py37h1de35cc_1    defaults
asn1crypto                0.24.0                   py37_0    defaults
astroid                   2.0.4                    py37_0    defaults
astropy                   3.0.4            py37h1de35cc_0    defaults
atomicwrites              1.2.1                    py37_0    defaults
attrs                     18.2.0           py37h28b3542_0    defaults
automat                   0.7.0                    py37_0    defaults
babel                     2.6.0                    py37_0    defaults
backcall                  0.1.0                    py37_0    defaults
backports                 1.0                      py37_1    defaults
backports.shutil_get_terminal_size 1.0.0                    py37_2    defaults
beautifulsoup4            4.6.3                    py37_0    defaults
bitarray                  0.8.3            py37h1de35cc_0    defaults
bkcharts                  0.2                      py37_0    defaults
blas                      1.0                         mkl    defaults
blaze                     0.11.3                   py37_0    defaults
bleach                    2.1.4                    py37_0    defaults
blosc                     1.14.4               hd9629dc_0    defaults
bokeh                     0.13.0                   py37_0    defaults
boto                      2.49.0                   py37_0    defaults
bottleneck                1.2.1            py37h1d22016_1    defaults
bzip2                     1.0.6                h1de35cc_5    defaults
ca-certificates           2018.03.07                    0    defaults
certifi                   2018.10.15               py37_0    defaults
cffi                      1.11.5           py37h6174b99_1    defaults
chardet                   3.0.4                    py37_1    defaults
click                     6.7                      py37_0    defaults
cloudpickle               0.5.5                    py37_0    defaults
clyent                    1.2.2                    py37_1    defaults
colorama                  0.3.9                    py37_0    defaults
conda                     4.5.11                   py37_0    defaults
conda-build               3.15.1                   py37_0    defaults
conda-env                 2.6.0                         1    defaults
constantly                15.1.0           py37h28b3542_0    defaults
contextlib2               0.5.5                    py37_0    defaults
cryptography              2.3.1            py37hdbc3d79_0    defaults
curl                      7.61.0               ha441bb4_0    defaults
cycler                    0.10.0                   py37_0    defaults
cython                    0.28.5           py37h0a44026_0    defaults
cytoolz                   0.9.0.1          py37h1de35cc_1    defaults
dask                      0.19.1                   py37_0    defaults
dask-core                 0.19.1                   py37_0    defaults
datashape                 0.5.4                    py37_1    defaults
dbus                      1.13.2               h760590f_1    defaults
decorator                 4.3.0                    py37_0    defaults
defusedxml                0.5.0                    py37_1    defaults
distributed               1.23.1                   py37_0    defaults
docutils                  0.14                     py37_0    defaults
entrypoints               0.2.3                    py37_2    defaults
et_xmlfile                1.0.1                    py37_0    defaults
expat                     2.2.6                h0a44026_0    defaults
fastcache                 1.0.2            py37h1de35cc_2    defaults
filelock                  3.0.8                    py37_0    defaults
flask                     1.0.2                    py37_1    defaults
flask-cors                3.0.6                    py37_0    defaults
freetype                  2.9.1                hb4e5f40_0    defaults
get_terminal_size         1.0.0                h7520d66_0    defaults
gettext                   0.19.8.1             h15daf44_3    defaults
gevent                    1.3.6            py37h1de35cc_0    defaults
glib                      2.56.2               hd9629dc_0    defaults
glob2                     0.6                      py37_0    defaults
gmp                       6.1.2                hb37e062_1    defaults
gmpy2                     2.0.8            py37h6ef4df4_2    defaults
greenlet                  0.4.15           py37h1de35cc_0    defaults
h5py                      2.8.0            py37h878fce3_3    defaults
hdf5                      1.10.2               hfa1e0ec_1    defaults
heapdict                  1.0.0                    py37_2    defaults
html5lib                  1.0.1                    py37_0    defaults
hyperlink                 18.0.0                   py37_0    defaults
icu                       58.2                 h4b95b61_1    defaults
idna                      2.7                      py37_0    defaults
imageio                   2.4.1                    py37_0    defaults
imagesize                 1.1.0                    py37_0    defaults
incremental               17.5.0                   py37_0    defaults
intel-openmp              2019.0                      118    defaults
ipykernel                 4.9.0                    py37_1    defaults
ipython                   6.5.0                    py37_0    defaults
ipython_genutils          0.2.0                    py37_0    defaults
ipywidgets                7.4.1                    py37_0    defaults
isort                     4.3.4                    py37_0    defaults
itsdangerous              0.24                     py37_1    defaults
jbig                      2.1                  h4d881f8_0    defaults
jdcal                     1.4                      py37_0    defaults
jedi                      0.12.1                   py37_0    defaults
jinja2                    2.10                     py37_0    defaults
jpeg                      9b                   he5867d9_2    defaults
jsonschema                2.6.0                    py37_0    defaults
jupyter                   1.0.0                    py37_7    defaults
jupyter_client            5.2.3                    py37_0    defaults
jupyter_console           5.2.0                    py37_1    defaults
jupyter_core              4.4.0                    py37_0    defaults
jupyterlab                0.34.9                   py37_0    defaults
jupyterlab_launcher       0.13.1                   py37_0    defaults
keyring                   13.2.1                   py37_0    defaults
kiwisolver                1.0.1            py37h0a44026_0    defaults
lazy-object-proxy         1.3.1            py37h1de35cc_2    defaults
libcurl                   7.61.0               hf30b1f0_0    defaults
libcxx                    4.0.1                h579ed51_0    defaults
libcxxabi                 4.0.1                hebd6815_0    defaults
libedit                   3.1.20170329         hb402a30_2    defaults
libffi                    3.2.1                h475c297_4    defaults
libgfortran               3.0.1                h93005f0_2    defaults
libiconv                  1.15                 hdd342a3_7    defaults
libpng                    1.6.34               he12f830_0    defaults
libsodium                 1.0.16               h3efe00b_0    defaults
libssh2                   1.8.0                h322a93b_4    defaults
libtiff                   4.0.9                hcb84e12_2    defaults
libxml2                   2.9.8                hab757c2_1    defaults
libxslt                   1.1.32               hb819dd2_0    defaults
llvmlite                  0.24.0           py37hc454e04_0    defaults
locket                    0.2.0                    py37_1    defaults
lxml                      4.2.5            py37hef8c89e_0    defaults
lzo                       2.10                 h362108e_2    defaults
markupsafe                1.0              py37h1de35cc_1    defaults
matplotlib                2.2.3            py37h54f8f79_0    defaults
mccabe                    0.6.1                    py37_1    defaults
mistune                   0.8.3            py37h1de35cc_1    defaults
mkl                       2019.0                      118    defaults
mkl-service               1.1.2            py37h6b9c3cc_5    defaults
mkl_fft                   1.0.4            py37h5d10147_1    defaults
mkl_random                1.0.1            py37h5d10147_1    defaults
more-itertools            4.3.0                    py37_0    defaults
mpc                       1.1.0                h6ef4df4_1    defaults
mpfr                      4.0.1                h3018a27_3    defaults
mpmath                    1.0.0                    py37_2    defaults
msgpack-python            0.5.6            py37h04f5b5a_1    defaults
multipledispatch          0.6.0                    py37_0    defaults
navigator-updater         0.2.1                    py37_0    defaults
nbconvert                 5.4.0                    py37_1    defaults
nbformat                  4.4.0                    py37_0    defaults
ncurses                   6.1                  h0a44026_0    defaults
networkx                  2.1                      py37_0    defaults
nltk                      3.3.0                    py37_0    defaults
nose                      1.3.7                    py37_2    defaults
notebook                  5.6.0                    py37_0    defaults
numba                     0.39.0           py37h6440ff4_0    defaults
numexpr                   2.6.8            py37h1dc9127_0    defaults
numpy                     1.15.1           py37h6a91979_0    defaults
numpy-base                1.15.1           py37h8a80b8c_0    defaults
numpydoc                  0.8.0                    py37_0    defaults
odo                       0.5.1                    py37_0    defaults
olefile                   0.46                     py37_0    defaults
openpyxl                  2.5.6                    py37_0    defaults
openssl                   1.0.2p               h1de35cc_0    defaults
packaging                 17.1                     py37_0    defaults
pandas                    0.23.4           py37h6440ff4_0    defaults
pandoc                    1.19.2.1             ha5e8f32_1    defaults
pandocfilters             1.4.2                    py37_1    defaults
parso                     0.3.1                    py37_0    defaults
partd                     0.3.8                    py37_0    defaults
path.py                   11.1.0                   py37_0    defaults
pathlib2                  2.3.2                    py37_0    defaults
patsy                     0.5.0                    py37_0    defaults
pcre                      8.42                 h378b8a2_0    defaults
pep8                      1.7.1                    py37_0    defaults
pexpect                   4.6.0                    py37_0    defaults
pickleshare               0.7.4                    py37_0    defaults
pillow                    5.2.0            py37hb68e598_0    defaults
pip                       10.0.1                   py37_0    defaults
pkginfo                   1.4.2                    py37_1    defaults
pluggy                    0.7.1            py37h28b3542_0    defaults
ply                       3.11                     py37_0    defaults
prometheus_client         0.3.1            py37h28b3542_0    defaults
prompt_toolkit            1.0.15                   py37_0    defaults
psutil                    5.4.7            py37h1de35cc_0    defaults
ptyprocess                0.6.0                    py37_0    defaults
py                        1.6.0                    py37_0    defaults
pyasn1                    0.4.4            py37h28b3542_0    defaults
pyasn1-modules            0.2.2                    py37_0    defaults
pycodestyle               2.4.0                    py37_0    defaults
pycosat                   0.6.3            py37h1de35cc_0    defaults
pycparser                 2.18                     py37_1    defaults
pycrypto                  2.6.1            py37h1de35cc_9    defaults
pycurl                    7.43.0.2         py37hdbc3d79_0    defaults
pyflakes                  2.0.0                    py37_0    defaults
pygments                  2.2.0                    py37_0    defaults
pylint                    2.1.1                    py37_0    defaults
pyodbc                    4.0.24           py37h0a44026_0    defaults
pyopenssl                 18.0.0                   py37_0    defaults
pyparsing                 2.2.0                    py37_1    defaults
pyqt                      5.9.2            py37h655552a_2    defaults
pysocks                   1.6.8                    py37_0    defaults
pytables                  3.4.4            py37h13cba08_0    defaults
pytest                    3.8.0                    py37_0    defaults
pytest-arraydiff          0.2              py37h39e3cac_0    defaults
pytest-astropy            0.4.0                    py37_0    defaults
pytest-doctestplus        0.1.3                    py37_0    defaults
pytest-openfiles          0.3.0                    py37_0    defaults
pytest-remotedata         0.3.0                    py37_0    defaults
python                    3.7.0                hc167b69_0    defaults
python-dateutil           2.7.3                    py37_0    defaults
python.app                2                        py37_9    defaults
pytz                      2018.5                   py37_0    defaults
pywavelets                1.0.0            py37h1d22016_0    defaults
pyyaml                    3.13             py37h1de35cc_0    defaults
pyzmq                     17.1.2           py37h1de35cc_0    defaults
qt                        5.9.6                h45cd832_2    defaults
qtawesome                 0.4.4                    py37_0    defaults
qtconsole                 4.4.1                    py37_0    defaults
qtpy                      1.5.0                    py37_0    defaults
readline                  7.0                  h1de35cc_5    defaults
requests                  2.19.1                   py37_0    defaults
rope                      0.11.0                   py37_0    defaults
ruamel_yaml               0.15.46          py37h1de35cc_0    defaults
scikit-image              0.14.0           py37h0a44026_1    defaults
scikit-learn              0.19.2           py37h4f467ca_0    defaults
scipy                     1.1.0            py37h28f7352_1    defaults
seaborn                   0.9.0                    py37_0    defaults
send2trash                1.5.0                    py37_0    defaults
service_identity          17.0.0           py37h28b3542_0    defaults
setuptools                40.2.0                   py37_0    defaults
simplegeneric             0.8.1                    py37_2    defaults
singledispatch            3.4.0.3                  py37_0    defaults
sip                       4.19.8           py37h0a44026_0    defaults
six                       1.11.0                   py37_1    defaults
snappy                    1.1.7                he62c110_3    defaults
snowballstemmer           1.2.1                    py37_0    defaults
sortedcollections         1.0.1                    py37_0    defaults
sortedcontainers          2.0.5                    py37_0    defaults
sphinx                    1.7.9                    py37_0    defaults
sphinxcontrib             1.0                      py37_1    defaults
sphinxcontrib-websupport  1.1.0                    py37_1    defaults
spyder                    3.3.1                    py37_1    defaults
spyder-kernels            0.2.6                    py37_0    defaults
sqlalchemy                1.2.11           py37h1de35cc_0    defaults
sqlite                    3.24.0               ha441bb4_0    defaults
statsmodels               0.9.0            py37h1d22016_0    defaults
sympy                     1.2                      py37_0    defaults
tblib                     1.3.2                    py37_0    defaults
terminado                 0.8.1                    py37_1    defaults
testpath                  0.3.1                    py37_0    defaults
tk                        8.6.8                ha441bb4_0    defaults
toolz                     0.9.0                    py37_0    defaults
tornado                   5.1              py37h1de35cc_0    defaults
tqdm                      4.26.0           py37h28b3542_0    defaults
traitlets                 4.3.2                    py37_0    defaults
twisted                   18.7.0           py37h1de35cc_1    defaults
unicodecsv                0.14.1                   py37_0    defaults
unixodbc                  2.3.7                h1de35cc_0    defaults
urllib3                   1.23                     py37_0    defaults
wcwidth                   0.1.7                    py37_0    defaults
webencodings              0.5.1                    py37_1    defaults
werkzeug                  0.14.1                   py37_0    defaults
wheel                     0.31.1                   py37_0    defaults
widgetsnbextension        3.4.1                    py37_0    defaults
wrapt                     1.10.11          py37h1de35cc_2    defaults
xlrd                      1.1.0                    py37_1    defaults
xlsxwriter                1.1.0                    py37_0    defaults
xlwings                   0.11.8                   py37_0    defaults
xlwt                      1.3.0                    py37_0    defaults
xz                        5.2.4                h1de35cc_4    defaults
yaml                      0.1.7                hc338f04_2    defaults
zeromq                    4.2.5                h0a44026_1    defaults
zict                      0.1.3                    py37_0    defaults
zlib                      1.2.11               hf3cbc9b_2    defaults
zope                      1.0                      py37_1    defaults
zope.interface            4.5.0            py37h1de35cc_0    defaults
```

**Comment by bboresow** [comment]
If I open 'spyder' directly in the terminal it opens without problem. So not exactly sure what is going on with Anaconda. I also tried uninstalling and reinstalling

**Comment by goanpeca** [comment]
@ccordoba12?
