### ISSUE TITLE
Loading apps list...

### ISSUE THREAD

**Issue by oceam** [ContinuumIO/anaconda-issues#1039]
RangeError: Maximum call stack size exceeded
    at String.replace (native)
    at Function.st (file:///Users/oceam/anaconda/node-webkit/launcher/static/vendor/jquery/1.9.1/jquery.min.js:4:6145)
    at HTMLDocument.b.event.handlers (file:///Users/oceam/anaconda/node-webkit/launcher/static/vendor/jquery/1.9.1/jquery.min.js:3:28790)
    at HTMLDocument.b.event.dispatch (file:///Users/oceam/anaconda/node-webkit/launcher/static/vendor/jquery/1.9.1/jquery.min.js:3:28046)
    at HTMLDocument.v.handle (file:///Users/oceam/anaconda/node-webkit/launcher/static/vendor/jquery/1.9.1/jquery.min.js:3:25049)
    at Object.b.event.trigger (file:///Users/oceam/anaconda/node-webkit/launcher/static/vendor/jquery/1.9.1/jquery.min.js:3:27423)
    at HTMLDivElement.<anonymous> (file:///Users/oceam/anaconda/node-webkit/launcher/static/vendor/jquery/1.9.1/jquery.min.js:4:3107)
    at Function.b.extend.each (file:///Users/oceam/anaconda/node-webkit/launcher/static/vendor/jquery/1.9.1/jquery.min.js:3:5257)
    at b.fn.b.each (file:///Users/oceam/anaconda/node-webkit/launcher/static/vendor/jquery/1.9.1/jquery.min.js:3:2013)
    at b.fn.extend.trigger (file:///Users/oceam/anaconda/node-webkit/launcher/static/vendor/jquery/1.9.1/jquery.min.js:4:3083)

**Comment by goanpeca** [comment]
Launcher has been deprecated and replaced with [Anaconda Navigator](https://docs.continuum.io/anaconda/navigator). To install please open a command prompt and type

`conda install anaconda-navigator`

**Comment by oceam** [comment]
thanks a lot

**Comment by goanpeca** [comment]
:+1:
