### ISSUE TITLE
Navigator Error - unexpected error occurred on Navigator start-up

### ISSUE THREAD

**Issue by trabdlkarim** [ContinuumIO/anaconda-issues#10397]
An unexpected error occurred on Navigator start-up

## Main Error
'root_prefix'
## Traceback
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.7/site-packages/anaconda_navigator/exceptions.py", line 75, in exception_handler
    return_value = func(*args, **kwargs)
  File "/opt/anaconda3/lib/python3.7/site-packages/anaconda_navigator/app/start.py", line 150, in start_app
    window = run_app(splash)
  File "/opt/anaconda3/lib/python3.7/site-packages/anaconda_navigator/app/start.py", line 65, in run_app
    window = MainWindow(splash=splash, tab_project=False)
  File "/opt/anaconda3/lib/python3.7/site-packages/anaconda_navigator/widgets/main_window.py", line 168, in __init__
    self.api = AnacondaAPI()
  File "/opt/anaconda3/lib/python3.7/site-packages/anaconda_navigator/api/anaconda_api.py", line 2294, in AnacondaAPI
    ANACONDA_API = _AnacondaAPI()
  File "/opt/anaconda3/lib/python3.7/site-packages/anaconda_navigator/api/anaconda_api.py", line 91, in __init__
    self._conda_api = CondaAPI()
  File "/opt/anaconda3/lib/python3.7/site-packages/anaconda_navigator/api/conda_api.py", line 1767, in CondaAPI
    CONDA_API = _CondaAPI()
  File "/opt/anaconda3/lib/python3.7/site-packages/anaconda_navigator/api/conda_api.py", line 350, in __init__
    self.set_conda_prefix(info=get_conda_info())
  File "/opt/anaconda3/lib/python3.7/site-packages/anaconda_navigator/api/conda_api.py", line 505, in set_conda_prefix
    self.ROOT_PREFIX = info['root_prefix']
KeyError: 'root_prefix'

##### Anaconda version:
Anaconda 5.3.1
conda 4.5.11

##### Operating System:
Linux parrot 4.18.0-parrot10-amd64 
#1 SMP Debian 4.18.10-2parrot10 (2018-11-17) x86_64 GNU/Linux

**Comment by goanpeca** [comment]
Please provide the requested information on the issue template




### Actual Behavior



### Expected Behavior



### Steps to Reproduce




##### Anaconda or Miniconda version:

##### Operating System:

##### `conda info`

```

```

##### `conda list --show-channel-urls`

```

```

**Comment by trabdlkarim** [comment]
I've just edited the issue information, and I hope it is more formal to you now.

**Comment by goanpeca** [comment]
@trabdlkarim it seems the install did not complete successfully since the conda info command is not working properly.
