### ISSUE TITLE
Conda not working from terminal invokin

### ISSUE THREAD

**Issue by ambekarsameer** [ContinuumIO/anaconda-issues#10396]
### Actual Behavior

conda update anaconda
Solving environment: failed

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/home/sameer/anaconda3/lib/python3.6/site-packages/conda/exceptions.py", line 819, in __call__
        return func(*args, **kwargs)
      File "/home/sameer/anaconda3/lib/python3.6/site-packages/conda/cli/main.py", line 78, in _main
        exit_code = do_call(args, p)
      File "/home/sameer/anaconda3/lib/python3.6/site-packages/conda/cli/conda_argparse.py", line 77, in do_call
        exit_code = getattr(module, func_name)(args, parser)
      File "/home/sameer/anaconda3/lib/python3.6/site-packages/conda/cli/main_update.py", line 14, in execute
        install(args, parser, 'update')
      File "/home/sameer/anaconda3/lib/python3.6/site-packages/conda/cli/install.py", line 235, in install
        force_reinstall=context.force,
      File "/home/sameer/anaconda3/lib/python3.6/site-packages/conda/core/solve.py", line 518, in solve_for_transaction
        force_remove, force_reinstall)
      File "/home/sameer/anaconda3/lib/python3.6/site-packages/conda/core/solve.py", line 451, in solve_for_diff
        final_precs = self.solve_final_state(deps_modifier, prune, ignore_pinned, force_remove)
      File "/home/sameer/anaconda3/lib/python3.6/site-packages/conda/core/solve.py", line 180, in solve_final_state
        index, r = self._prepare(prepared_specs)
      File "/home/sameer/anaconda3/lib/python3.6/site-packages/conda/core/solve.py", line 592, in _prepare
        self.subdirs, prepared_specs)
      File "/home/sameer/anaconda3/lib/python3.6/site-packages/conda/core/index.py", line 215, in get_reduced_index
        new_records = query_all(spec)
      File "/home/sameer/anaconda3/lib/python3.6/site-packages/conda/core/index.py", line 184, in query_all
        return tuple(concat(future.result() for future in as_completed(futures)))
      File "/home/sameer/anaconda3/lib/python3.6/site-packages/conda/core/subdir_data.py", line 95, in query
        self.load()
      File "/home/sameer/anaconda3/lib/python3.6/site-packages/conda/core/subdir_data.py", line 149, in load
        _internal_state = self._load()
      File "/home/sameer/anaconda3/lib/python3.6/site-packages/conda/core/subdir_data.py", line 227, in _load
        mod_etag_headers.get('_mod'))
      File "/home/sameer/anaconda3/lib/python3.6/site-packages/conda/core/subdir_data.py", line 437, in fetch_repodata_remote_request
        timeout=timeout)
      File "/home/sameer/anaconda3/lib/python3.6/site-packages/requests/sessions.py", line 546, in get
        return self.request('GET', url, **kwargs)
      File "/home/sameer/anaconda3/lib/python3.6/site-packages/requests/sessions.py", line 533, in request
        resp = self.send(prep, **send_kwargs)
      File "/home/sameer/anaconda3/lib/python3.6/site-packages/requests/sessions.py", line 646, in send
        r = adapter.send(request, **kwargs)
      File "/home/sameer/anaconda3/lib/python3.6/site-packages/requests/adapters.py", line 412, in send
        conn = self.get_connection(request.url, proxies)
      File "/home/sameer/anaconda3/lib/python3.6/site-packages/requests/adapters.py", line 309, in get_connection
        proxy_manager = self.proxy_manager_for(proxy)
      File "/home/sameer/anaconda3/lib/python3.6/site-packages/requests/adapters.py", line 189, in proxy_manager_for
        **proxy_kwargs
      File "/home/sameer/anaconda3/lib/python3.6/site-packages/urllib3/contrib/socks.py", line 173, in __init__
        "Unable to determine SOCKS version from %s" % proxy_url
    ValueError: Unable to determine SOCKS version from socks://192.168.0.1:8081/

`$ /home/sameer/anaconda3/bin/conda update anaconda`

  environment variables:
                ALL_PROXY=<set>
                 CIO_TEST=<not set>
               CONDA_ROOT=/home/sameer/anaconda3
            DEFAULTS_PATH=/usr/share/gconf/ubuntu.default.path
           MANDATORY_PATH=/usr/share/gconf/ubuntu.mandatory.path
                 NO_PROXY=<set>
                     PATH=/home/sameer/anaconda3/bin:/home/sameer/.local/share/umake/bin:/home/s
                          ameer/bin:/home/sameer/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/
                          sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>
               WINDOWPATH=2
                all_proxy=<set>
                ftp_proxy=<set>
               http_proxy=<set>
              https_proxy=<set>
                 no_proxy=<set>
              socks_proxy=<set>

     active environment : None
       user config file : /home/sameer/.condarc
 populated config files : /home/sameer/.condarc
          conda version : 4.5.11
    conda-build version : 3.17.0
         python version : 3.6.6.final.0
       base environment : /home/sameer/anaconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/linux-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/linux-64
                          https://repo.anaconda.com/pkgs/pro/noarch
          package cache : /home/sameer/anaconda3/pkgs
                          /home/sameer/.conda/pkgs
       envs directories : /home/sameer/anaconda3/envs
                          /home/sameer/.conda/envs
               platform : linux-64
             user-agent : conda/4.5.11 requests/2.20.1 CPython/3.6.6 Linux/4.15.0-36-generic ubuntu/18.04 glibc/2.27
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False

An unexpected error has occurred. Conda has prepared the above report.
If submitted, this report will be used by core maintainers to improve
future releases of conda.
Would you like conda to send this report to the core maintainers?
[y/N]: y
Upload did not complete.
Thank you for helping to improve conda.
Opt-in to always sending reports (and not see this message again)
by running

    $ conda config --set report_errors true

### Expected Behavior
Should open normally and execute

### Steps to Reproduce
In ubuntu terminal type conda update conda, conda update anaconda, conda update --all

##### Anaconda or Miniconda version:
conda 4.5.11

##### Operating System:
Ubuntu 18
##### `conda info`

```
active environment : None
       user config file : /home/sameer/.condarc
 populated config files : /home/sameer/.condarc
          conda version : 4.5.11
    conda-build version : 3.17.0
         python version : 3.6.6.final.0
       base environment : /home/sameer/anaconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/linux-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/linux-64
                          https://repo.anaconda.com/pkgs/pro/noarch
          package cache : /home/sameer/anaconda3/pkgs
                          /home/sameer/.conda/pkgs
       envs directories : /home/sameer/anaconda3/envs
                          /home/sameer/.conda/envs
               platform : linux-64
             user-agent : conda/4.5.11 requests/2.20.1 CPython/3.6.6 Linux/4.15.0-36-generic ubuntu/18.04 glibc/2.27
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False

```

##### `conda list --show-channel-urls`

```
# packages in environment at /home/sameer/anaconda3:
#
# Name                    Version                   Build  Channel
_ipyw_jlab_nb_ext_conf    0.1.0                    py36_0    defaults
_tflow_1100_select        0.0.3                       mkl    defaults
_tflow_190_select         0.0.3                       mkl    defaults
_tflow_select             2.3.0                       mkl    defaults
absl-py                   0.6.1                    py36_0    defaults
alabaster                 0.7.12                   py36_0    defaults
anaconda                  custom           py36hbbc8b67_0    defaults
anaconda-client           1.7.2                    py36_0    defaults
anaconda-navigator        1.9.2                    py36_0    defaults
anaconda-project          0.8.2                    py36_0    defaults
appdirs                   1.4.3            py36h28b3542_0    defaults
asn1crypto                0.24.0                   py36_0    defaults
astor                     0.7.1                    py36_0    defaults
astroid                   2.1.0                    py36_0    defaults
astropy                   3.0.5            py36h7b6447c_0    defaults
atomicwrites              1.2.1                    py36_0    defaults
attrs                     18.2.0           py36h28b3542_0    defaults
automat                   0.7.0                    py36_0    defaults
babel                     2.6.0                    py36_0    defaults
backcall                  0.1.0                    py36_0    defaults
backports                 1.0                      py36_1    defaults
backports.os              0.1.1                    py36_0    defaults
backports.shutil_get_terminal_size 1.0.0                    py36_2    defaults
beautifulsoup4            4.6.3                    py36_0    defaults
bitarray                  0.8.3            py36h14c3975_0    defaults
bkcharts                  0.2                      py36_0    defaults
blas                      1.0                         mkl    defaults
blaze                     0.11.3                   py36_0    defaults
bleach                    3.0.2                    py36_0    defaults
blosc                     1.14.4               hdbcaa40_0    defaults
bokeh                     1.0.2                    py36_0    defaults
boto                      2.49.0                   py36_0    defaults
bottleneck                1.2.1            py36h035aef0_1    defaults
bzip2                     1.0.6                h14c3975_5    defaults
c-ares                    1.15.0               h7b6447c_1    defaults
ca-certificates           2018.03.07                    0    defaults
cairo                     1.14.12              h8948797_3    defaults
certifi                   2018.10.15               py36_0    defaults
cffi                      1.11.5           py36he75722e_1    defaults
chardet                   3.0.4                    py36_1    defaults
click                     7.0                      py36_0    defaults
cloudpickle               0.6.1                    py36_0    defaults
clyent                    1.2.2                    py36_1    defaults
colorama                  0.4.0                    py36_0    defaults
conda                     4.5.11                   py36_0    defaults
conda-build               3.17.0                   py36_0    defaults
conda-env                 2.6.0                         1    defaults
conda-verify              3.1.1                    py36_0    defaults
constantly                15.1.0           py36h28b3542_0    defaults
contextlib2               0.5.5                    py36_0    defaults
cryptography              2.3.1            py36hc365091_0    defaults
cryptography-vectors      2.4.2                    py36_0    defaults
curl                      7.61.0               h84994c4_0    defaults
cycler                    0.10.0                   py36_0    defaults
cython                    0.29             py36he6710b0_0    defaults
cytoolz                   0.9.0.1          py36h14c3975_1    defaults
dask                      1.0.0                    py36_0    defaults
dask-core                 1.0.0                    py36_0    defaults
datashape                 0.5.4                    py36_1    defaults
dbus                      1.13.2               h714fa37_1    defaults
decorator                 4.3.0                    py36_0    defaults
distributed               1.25.0                   py36_0    defaults
docutils                  0.14                     py36_0    defaults
entrypoints               0.2.3                    py36_2    defaults
et_xmlfile                1.0.1                    py36_0    defaults
expat                     2.2.6                he6710b0_0    defaults
fastcache                 1.0.2            py36h14c3975_2    defaults
filelock                  3.0.10                   py36_0    defaults
flask                     1.0.2                    py36_1    defaults
flask-cors                3.0.7                    py36_0    defaults
fontconfig                2.13.0               h9420a91_0    defaults
freetype                  2.9.1                h8a8886c_1    defaults
fribidi                   1.0.5                h7b6447c_0    defaults
future                    0.17.1                   py36_0    defaults
gast                      0.2.0                    py36_0    defaults
get_terminal_size         1.0.0                haa9412d_0    defaults
gevent                    1.3.7            py36h7b6447c_1    defaults
glib                      2.56.2               hd408876_0    defaults
glob2                     0.6                      py36_1    defaults
gmp                       6.1.2                h6c8ec71_1    defaults
gmpy2                     2.0.8            py36h10f8cd9_2    defaults
graphite2                 1.3.12               h23475e2_2    defaults
greenlet                  0.4.15           py36h7b6447c_0    defaults
grpcio                    1.14.1           py36h9ba97e2_0    defaults
gst-plugins-base          1.14.0               hbbd80ab_1    defaults
gstreamer                 1.14.0               hb453b48_1    defaults
h5py                      2.8.0            py36h989c5e5_3    defaults
harfbuzz                  1.8.8                hffaf4a1_0    defaults
hdf5                      1.10.2               hba1933b_1    defaults
heapdict                  1.0.0                    py36_2    defaults
html5lib                  1.0.1                    py36_0    defaults
hyperlink                 18.0.0                   py36_0    defaults
icu                       58.2                 h9c2bf20_1    defaults
idna                      2.7                      py36_0    defaults
imageio                   2.4.1                    py36_0    defaults
imagesize                 1.1.0                    py36_0    defaults
importlib_metadata        0.6                      py36_0    defaults
incremental               17.5.0                   py36_0    defaults
intel-openmp              2019.1                      144    defaults
ipykernel                 5.1.0            py36h39e3cac_0    defaults
ipython                   7.2.0            py36h39e3cac_0    defaults
ipython_genutils          0.2.0                    py36_0    defaults
ipywidgets                7.4.2                    py36_0    defaults
isort                     4.3.4                    py36_0    defaults
itsdangerous              1.1.0                    py36_0    defaults
jbig                      2.1                  hdba287a_0    defaults
jdcal                     1.4                      py36_0    defaults
jedi                      0.13.1                   py36_0    defaults
jeepney                   0.4                      py36_0    defaults
jinja2                    2.10                     py36_0    defaults
jpeg                      9b                   h024ee3a_2    defaults
jsonschema                2.6.0                    py36_0    defaults
jupyter                   1.0.0                    py36_4    defaults
jupyter_client            5.2.3                    py36_0    defaults
jupyter_console           6.0.0                    py36_0    defaults
jupyter_contrib_core      0.3.3                      py_2    conda-forge
jupyter_contrib_nbextensions 0.5.0                    py36_0    conda-forge
jupyter_core              4.4.0                    py36_0    defaults
jupyter_highlight_selected_word 0.2.0                    py36_0    conda-forge
jupyter_latex_envs        1.4.4                    py36_0    conda-forge
jupyter_nbextensions_configurator 0.4.0                    py36_0    conda-forge
jupyterlab                0.35.3                   py36_0    defaults
jupyterlab_launcher       0.13.1                   py36_0    defaults
jupyterlab_server         0.2.0                    py36_0    defaults
Keras                     2.2.2                     <pip>
keras-applications        1.0.6                    py36_0    defaults
Keras-Applications        1.0.4                     <pip>
keras-preprocessing       1.0.5                    py36_0    defaults
Keras-Preprocessing       1.0.2                     <pip>
keyring                   16.1.1                   py36_0    defaults
kiwisolver                1.0.1            py36hf484d3e_0    defaults
lazy-object-proxy         1.3.1            py36h14c3975_2    defaults
libarchive                3.3.3                h7d0bbab_1    defaults
libcurl                   7.61.0               h1ad7b7a_0    defaults
libedit                   3.1.20170329         h6b74fdf_2    defaults
libffi                    3.2.1                hd88cf55_4    defaults
libgcc-ng                 8.2.0                hdf63c60_1    defaults
libgfortran-ng            7.3.0                hdf63c60_0    defaults
liblief                   0.9.0                h7725739_1    defaults
libpng                    1.6.35               hbc83047_0    defaults
libprotobuf               3.6.1                hd408876_0    defaults
libsodium                 1.0.16               h1bed415_0    defaults
libssh2                   1.8.0                h9cfc8f7_4    defaults
libstdcxx-ng              8.2.0                hdf63c60_1    defaults
libtiff                   4.0.9                he85c1e1_2    defaults
libtool                   2.4.6                h7b6447c_5    defaults
libuuid                   1.0.3                h1bed415_2    defaults
libxcb                    1.13                 h1bed415_1    defaults
libxml2                   2.9.8                h26e45fe_1    defaults
libxslt                   1.1.32               h1312cb7_0    defaults
llvmlite                  0.26.0           py36hd408876_0    defaults
locket                    0.2.0                    py36_1    defaults
lxml                      4.2.5            py36hefd8a0e_0    defaults
lz4-c                     1.8.1.2              h14c3975_0    defaults
lzo                       2.10                 h49e0be7_2    defaults
markdown                  3.0.1                    py36_0    defaults
markupsafe                1.1.0            py36h7b6447c_0    defaults
matplotlib                2.2.3            py36hb69df0a_0    defaults
mccabe                    0.6.1                    py36_1    defaults
mistune                   0.8.4            py36h7b6447c_0    defaults
mkl                       2018.0.3                      1    defaults
mkl-service               1.1.2            py36h90e4bf4_5    defaults
mkl_fft                   1.0.6            py36h7dd41cf_0    defaults
mkl_random                1.0.1            py36h4414c95_1    defaults
more-itertools            4.3.0                    py36_0    defaults
mpc                       1.1.0                h10f8cd9_1    defaults
mpfr                      4.0.1                hdf1c602_3    defaults
mpmath                    1.0.0                    py36_2    defaults
msgpack-python            0.5.6            py36h6bb024c_1    defaults
multipledispatch          0.6.0                    py36_0    defaults
navigator-updater         0.2.1                    py36_0    defaults
nbconvert                 5.3.1                    py36_0    defaults
nbformat                  4.4.0                    py36_0    defaults
ncurses                   6.1                  he6710b0_1    defaults
networkx                  2.2                      py36_1    defaults
nltk                      3.3.0                    py36_0    defaults
nose                      1.3.7                    py36_2    defaults
notebook                  5.7.2                    py36_0    defaults
numba                     0.41.0           py36h962f231_0    defaults
numexpr                   2.6.8            py36hd89afb7_0    defaults
numpy                     1.15.4           py36h1d66e8a_0    defaults
numpy-base                1.15.4           py36h81de0dd_0    defaults
numpydoc                  0.8.0                    py36_0    defaults
odo                       0.5.1                    py36_0    defaults
olefile                   0.46                     py36_0    defaults
openpyxl                  2.5.11                   py36_0    defaults
openssl                   1.0.2p               h14c3975_0    defaults
packaging                 18.0                     py36_0    defaults
pandas                    0.23.4           py36h04863e7_0    defaults
pandoc                    2.2.3.2                       0    defaults
pandocfilters             1.4.2                    py36_1    defaults
pango                     1.42.4               h049681c_0    defaults
parso                     0.3.1                    py36_0    defaults
partd                     0.3.9                    py36_0    defaults
patchelf                  0.9                  he6710b0_3    defaults
path.py                   11.5.0                   py36_0    defaults
pathlib2                  2.3.2                    py36_0    defaults
patsy                     0.5.1                    py36_0    defaults
pcre                      8.42                 h439df22_0    defaults
pep8                      1.7.1                    py36_0    defaults
pexpect                   4.6.0                    py36_0    defaults
pickleshare               0.7.5                    py36_0    defaults
pillow                    5.3.0            py36h34e0f95_0    defaults
pip                       18.0                      <pip>
pip                       18.1                     py36_0    defaults
pixman                    0.34.0               hceecf20_3    defaults
pkginfo                   1.4.2                    py36_1    defaults
pluggy                    0.8.0                    py36_0    defaults
ply                       3.11                     py36_0    defaults
prometheus_client         0.4.2                    py36_0    defaults
prompt_toolkit            2.0.7                    py36_0    defaults
protobuf                  3.6.1            py36he6710b0_0    defaults
psutil                    5.4.8            py36h7b6447c_0    defaults
ptyprocess                0.6.0                    py36_0    defaults
py                        1.7.0                    py36_0    defaults
py-lief                   0.9.0            py36h7725739_1    defaults
pyasn1                    0.4.4            py36h28b3542_0    defaults
pyasn1-modules            0.2.2                    py36_0    defaults
pycodestyle               2.4.0                    py36_0    defaults
pycosat                   0.6.3            py36h14c3975_0    defaults
pycparser                 2.19                     py36_0    defaults
pycrypto                  2.6.1            py36h14c3975_9    defaults
pycurl                    7.43.0.2         py36hb7f436b_0    defaults
pyflakes                  2.0.0                    py36_0    defaults
pygments                  2.2.0                    py36_0    defaults
pyhamcrest                1.9.0                    py36_2    defaults
pylint                    2.2.2                    py36_0    defaults
pyodbc                    4.0.24           py36he6710b0_0    defaults
pyopenssl                 18.0.0                   py36_0    defaults
pyparsing                 2.3.0                    py36_0    defaults
pyqt                      5.9.2            py36h05f1152_2    defaults
pysocks                   1.6.8                    py36_0    defaults
pytables                  3.4.4            py36ha205bf6_0    defaults
pytest                    4.0.1                    py36_0    defaults
pytest-arraydiff          0.2              py36h39e3cac_0    defaults
pytest-astropy            0.4.0                    py36_0    defaults
pytest-doctestplus        0.2.0                    py36_0    defaults
pytest-openfiles          0.3.1                    py36_0    defaults
pytest-remotedata         0.3.1                    py36_0    defaults
python                    3.6.6                h6e4f718_2    defaults
python-dateutil           2.7.5                    py36_0    defaults
python-libarchive-c       2.8                      py36_6    defaults
pytz                      2018.7                   py36_0    defaults
pywavelets                1.0.1            py36hdd07704_0    defaults
pyyaml                    3.13             py36h14c3975_0    defaults
pyzmq                     17.1.2           py36h14c3975_0    defaults
qt                        5.9.6                h8703b6f_2    defaults
qtawesome                 0.5.3                    py36_0    defaults
qtconsole                 4.4.1                    py36_0    defaults
qtpy                      1.5.2                    py36_0    defaults
readline                  7.0                  h7b6447c_5    defaults
requests                  2.20.1                   py36_0    defaults
rope                      0.11.0                   py36_0    defaults
ruamel_yaml               0.15.46          py36h14c3975_0    defaults
scikit-image              0.14.0           py36hf484d3e_1    defaults
scikit-learn              0.20.1           py36h4989274_0    defaults
scipy                     1.1.0            py36hfa4b5c9_1    defaults
seaborn                   0.9.0                    py36_0    defaults
secretstorage             3.1.0                    py36_0    defaults
send2trash                1.5.0                    py36_0    defaults
service_identity          17.0.0           py36h28b3542_0    defaults
setuptools                40.6.2                   py36_0    defaults
simplegeneric             0.8.1                    py36_2    defaults
singledispatch            3.4.0.3                  py36_0    defaults
sip                       4.19.8           py36hf484d3e_0    defaults
six                       1.11.0                   py36_1    defaults
snappy                    1.1.7                hbae5bb6_3    defaults
snowballstemmer           1.2.1                    py36_0    defaults
sortedcollections         1.0.1                    py36_0    defaults
sortedcontainers          2.0.5                    py36_0    defaults
sphinx                    1.8.2                    py36_0    defaults
sphinxcontrib             1.0                      py36_1    defaults
sphinxcontrib-websupport  1.1.0                    py36_1    defaults
spyder                    3.3.1                    py36_1    defaults
spyder-kernels            0.3.0                    py36_0    defaults
sqlalchemy                1.2.14           py36h7b6447c_0    defaults
sqlite                    3.25.3               h7b6447c_0    defaults
statsmodels               0.9.0            py36h035aef0_0    defaults
sympy                     1.3                      py36_0    defaults
tblib                     1.3.2                    py36_0    defaults
tensorboard               1.12.0           py36hf484d3e_0    defaults
tensorflow                1.12.0          mkl_py36h69b6ba0_0    defaults
tensorflow-base           1.12.0          mkl_py36h3c3e929_0    defaults
termcolor                 1.1.0                    py36_1    defaults
terminado                 0.8.1                    py36_1    defaults
testpath                  0.4.2                    py36_0    defaults
tk                        8.6.8                hbc83047_0    defaults
toolz                     0.9.0                    py36_0    defaults
tornado                   5.1.1            py36h7b6447c_0    defaults
tqdm                      4.28.1           py36h28b3542_0    defaults
traitlets                 4.3.2                    py36_0    defaults
twisted                   18.9.0           py36h7b6447c_0    defaults
typed-ast                 1.1.0            py36h14c3975_0    defaults
typing                    3.6.4                    py36_0    defaults
unicodecsv                0.14.1                   py36_0    defaults
unixodbc                  2.3.7                h14c3975_0    defaults
urllib3                   1.23                     py36_0    defaults
wcwidth                   0.1.7                    py36_0    defaults
webencodings              0.5.1                    py36_1    defaults
werkzeug                  0.14.1                   py36_0    defaults
wheel                     0.32.3                   py36_0    defaults
widgetsnbextension        3.4.2                    py36_0    defaults
wrapt                     1.10.11          py36h14c3975_2    defaults
wurlitzer                 1.0.2                    py36_0    defaults
xlrd                      1.1.0                    py36_1    defaults
xlsxwriter                1.1.2                    py36_0    defaults
xlwt                      1.3.0                    py36_0    defaults
xz                        5.2.4                h14c3975_4    defaults
yaml                      0.1.7                had09818_2    defaults
zeromq                    4.2.5                hf484d3e_1    defaults
zict                      0.1.3                    py36_0    defaults
zlib                      1.2.11               h7b6447c_3    defaults
zope                      1.0                      py36_1    defaults
zope.interface            4.6.0            py36h7b6447c_0    defaults
zstd                      1.3.3                h84994c4_0    defaults

```

**Comment by nehaljwani** [comment]
Wherever you have configured the socks proxy, you are missing the version information.

This is insufficient: 
```
socks://192.168.0.1:8081/
```

It has to specify the version, for example:
```
socks5://192.168.0.1:8081/
```
