### ISSUE TITLE
Python Anaconda Fmask 0.5.1 issue on Windows

### ISSUE THREAD

**Issue by swordfish23** [ContinuumIO/anaconda-issues#10412]
There is something wrong using Python-fmask (Anaconda installation).
For instalaltion I used the instructions from http://pythonfmask.org/en/latest/#downloads

conda config --add channels conda-forge
conda create -n py_fmask_051 python-fmask
source activate myenv # omit 'source' on Windows

After installation on Windows 10 using Python 3.6.6 (packaged by conda-forge | (default, Jul 26 2018, 11:48:23) [MSC v.1900 64 bit (AMD64)] on win32) I activated the environment for applying fmask to a dataset. It results in the following error:

```
(py_fmask_051) E:\>fmask_sentinel2Stacked.py -o cloud.img --safedir E:\S2A_MSIL1C_20170403T104021_N0204_R008_T31UGR_20170403T104138.SAFE
Traceback (most recent call last):
  File "C:\Users\TITAN\AppData\Local\conda\conda\envs\py_fmask_051\Scripts\fmask_sentinel2Stacked.py-script.py", line 10, in <module>
    sys.exit(mainRoutine())
  File "C:\Users\TITAN\AppData\Local\conda\conda\envs\py_fmask_051\lib\site-packages\fmask\cmdline\sentinel2Stacked.py", line 289, in mainRoutine
    resampledBands = makeStackAndAngles(cmdargs)
  File "C:\Users\TITAN\AppData\Local\conda\conda\envs\py_fmask_051\lib\site-packages\fmask\cmdline\sentinel2Stacked.py", line 178, in makeStackAndAngles
    anglesfile])
  File "C:\Users\TITAN\AppData\Local\conda\conda\envs\py_fmask_051\lib\subprocess.py", line 286, in check_call
    retcode = call(*popenargs, **kwargs)
  File "C:\Users\TITAN\AppData\Local\conda\conda\envs\py_fmask_051\lib\subprocess.py", line 267, in call
    with Popen(*popenargs, **kwargs) as p:
  File "C:\Users\TITAN\AppData\Local\conda\conda\envs\py_fmask_051\lib\subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "C:\Users\TITAN\AppData\Local\conda\conda\envs\py_fmask_051x2\lib\subprocess.py", line 971, in _execute_child
    args = list2cmdline(args)
  File "C:\Users\TITAN\AppData\Local\conda\conda\envs\py_fmask_051x2\lib\subprocess.py", line 461, in list2cmdline
    needquote = (" " in arg) or ("\t" in arg) or not arg
TypeError: argument of type 'NoneType' is not iterable
```

I already contacted the fmask developers Neil Flood and Sam Gillingham and from there point of view the problem must be directed to you. The latest fmask modifications are available in a standalone version too (fmask 4.0), which is working (https://github.com/gersl/fmask). But I need to use python-fmask.
Please let me know if you need further information for helping me. Thank you!

##### `conda info`

```
     active environment : base
    active env location : C:\ProgramData\Anaconda3
            shell level : 1
       user config file : C:\Users\TITAN\.condarc
 populated config files : C:\Users\TITAN\.condarc
          conda version : 4.5.11
    conda-build version : 3.10.5
         python version : 3.6.5.final.0
       base environment : C:\ProgramData\Anaconda3  (read only)
           channel URLs : https://conda.anaconda.org/conda-forge/win-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/win-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/win-64
                          https://repo.anaconda.com/pkgs/pro/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\ProgramData\Anaconda3\pkgs
                          C:\Users\TITAN\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\TITAN\AppData\Local\conda\conda\envs
                          C:\ProgramData\Anaconda3\envs
                          C:\Users\TITAN\.conda\envs
               platform : win-64
             user-agent : conda/4.5.11 requests/2.18.4 CPython/3.6.5 Windows/10 Windows/10.0.17134
          administrator : False
             netrc file : None
           offline mode : False
```

**Comment by jjhelmus** [comment]
As this is an issue with a conda-forge package you will need to raise the issue with that project.  The [python-fmask feedstock repository](https://github.com/conda-forge/python-fmask-feedstock) would be a good place to ask for assistance.
