### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by Programmeurke** [ContinuumIO/anaconda-issues#10419]
## Main error
Application <b>jupyterlab</b> launch may have produced errors.
## Traceback
```
[I 22:04:20.030 LabApp] JupyterLab extension loaded from /anaconda/lib/python3.6/site-packages/jupyterlab
[I 22:04:20.030 LabApp] JupyterLab application directory is /anaconda/share/jupyter/lab
[W 22:04:20.031 LabApp] JupyterLab server extension not enabled, manually loading...
[I 22:04:20.033 LabApp] JupyterLab extension loaded from /anaconda/lib/python3.6/site-packages/jupyterlab
[I 22:04:20.033 LabApp] JupyterLab application directory is /anaconda/share/jupyter/lab
[I 22:04:20.034 LabApp] Serving notebooks from local directory: /Users/brunodirkx
[I 22:04:20.034 LabApp] The Jupyter Notebook is running at:
[I 22:04:20.034 LabApp] http://localhost:8888/?token=f1f07367dbd23ec2f1dc61e54bd98daf944290bb2187cb33
[I 22:04:20.034 LabApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 22:04:20.036 LabApp] 
    
    Copy/paste this URL into your browser when you connect for the first time,
    to login with a token:
        http://localhost:8888/?token=f1f07367dbd23ec2f1dc61e54bd98daf944290bb2187cb33
[I 22:04:20.155 LabApp] Accepting one-time-token-authenticated connection from ::1
[W 22:04:21.177 LabApp] Could not determine jupyterlab build status without nodejs
[W 22:04:21.396 LabApp] 404 GET /lab/api/workspaces/lab?1544648661242 (::1): Workspace 'lab' ('lab-a511') not found
[W 22:04:21.396 LabApp] Workspace 'lab' ('lab-a511') not found
[W 22:04:21.396 LabApp] 404 GET /lab/api/workspaces/lab?1544648661242 (::1) 1.23ms referer=http://localhost:8888/lab
[I 22:04:25.076 LabApp] Creating new notebook in /
[I 22:04:25.338 LabApp] Kernel started: c1ebccc4-812d-4c93-be11-8a699c166f6d
ERROR:tornado.general:Uncaught exception in ZMQStream callback
Traceback (most recent call last):
  File "/anaconda/lib/python3.6/site-packages/zmq/eventloop/zmqstream.py", line 432, in _run_callback
    callback(*args, **kwargs)
  File "/anaconda/lib/python3.6/site-packages/tornado/stack_context.py", line 277, in null_wrapper
    return fn(*args, **kwargs)
  File "/anaconda/lib/python3.6/site-packages/ipykernel/kernelbase.py", line 283, in dispatcher
    return self.dispatch_shell(stream, msg)
  File "/anaconda/lib/python3.6/site-packages/ipykernel/kernelbase.py", line 233, in dispatch_shell
    self.pre_handler_hook()
  File "/anaconda/lib/python3.6/site-packages/ipykernel/kernelbase.py", line 248, in pre_handler_hook
    self.saved_sigint_handler = signal(SIGINT, default_int_handler)
  File "/anaconda/lib/python3.6/signal.py", line 47, in signal
    handler = _signal.signal(_enum_to_int(signalnum), _enum_to_int(handler))
ValueError: signal only works in main thread
ERROR:tornado.general:Uncaught exception in zmqstream callback
Traceback (most recent call last):
  File "/anaconda/lib/python3.6/site-packages/zmq/eventloop/zmqstream.py", line 450, in _handle_events
    self._handle_recv()
  File "/anaconda/lib/python3.6/site-packages/zmq/eventloop/zmqstream.py", line 480, in _handle_recv
    self._run_callback(callback, msg)
  File "/anaconda/lib/python3.6/site-packages/zmq/eventloop/zmqstream.py", line 432, in _run_callback
    callback(*args, **kwargs)
  File "/anaconda/lib/python3.6/site-packages/tornado/stack_context.py", line 277, in null_wrapper
    return fn(*args, **kwargs)
  File "/anaconda/lib/python3.6/site-packages/ipykernel/kernelbase.py", line 283, in dispatcher
    return self.dispatch_shell(stream, msg)
  File "/anaconda/lib/python3.6/site-packages/ipykernel/kernelbase.py", line 233, in dispatch_shell
    self.pre_handler_hook()
  File "/anaconda/lib/python3.6/site-packages/ipykernel/kernelbase.py", line 248, in pre_handler_hook
    self.saved_sigint_handler = signal(SIGINT, default_int_handler)
  File "/anaconda/lib/python3.6/signal.py", line 47, in signal
    handler = _signal.signal(_enum_to_int(signalnum), _enum_to_int(handler))
ValueError: signal only works in main thread
ERROR:tornado.application:Exception in callback (<zmq.sugar.socket.Socket object at 0x10e3ca4c0>, <function wrap.<locals>.null_wrapper at 0x10e3b86a8>)
Traceback (most recent call last):
  File "/anaconda/lib/python3.6/site-packages/tornado/ioloop.py", line 888, in start
    handler_func(fd_obj, events)
  File "/anaconda/lib/python3.6/site-packages/tornado/stack_context.py", line 277, in null_wrapper
    return fn(*args, **kwargs)
  File "/anaconda/lib/python3.6/site-packages/zmq/eventloop/zmqstream.py", line 450, in _handle_events
    self._handle_recv()
  File "/anaconda/lib/python3.6/site-packages/zmq/eventloop/zmqstream.py", line 480, in _handle_recv
    self._run_callback(callback, msg)
  File "/anaconda/lib/python3.6/site-packages/zmq/eventloop/zmqstream.py", line 432, in _run_callback
    callback(*args, **kwargs)
  File "/anaconda/lib/python3.6/site-packages/tornado/stack_context.py", line 277, in null_wrapper
    return fn(*args, **kwargs)
  File "/anaconda/lib/python3.6/site-packages/ipykernel/kernelbase.py", line 283, in dispatcher
    return self.dispatch_shell(stream, msg)
  File "/anaconda/lib/python3.6/site-packages/ipykernel/kernelbase.py", line 233, in dispatch_shell
    self.pre_handler_hook()
  File "/anaconda/lib/python3.6/site-packages/ipykernel/kernelbase.py", line 248, in pre_handler_hook
    self.saved_sigint_handler = signal(SIGINT, default_int_handler)
  File "/anaconda/lib/python3.6/signal.py", line 47, in signal
    handler = _signal.signal(_enum_to_int(signalnum), _enum_to_int(handler))
ValueError: signal only works in main thread

```
## System information
```
python: 3.6.1
language: en
os: Darwin;17.7.0;Darwin Kernel Version 17.7.0: Wed Oct 10 23:06:14 PDT 2018; root:xnu-4570.71.13~1/RELEASE_X86_64;x86_64;i386
version: 1.6.2
platform: osx-64
qt: 5.6.2
pyqt: 5.6.0
conda: 4.5.11
```

**Comment by goanpeca** [comment]
Please remember to update to the latest version of Navigator to include
the latest fixes.

Open a terminal (on Linux or Mac) or the Anaconda Command Prompt (on windows)
and type:

```
conda update conda
conda update --all
```
