### ISSUE TITLE
Anaconda navigator not opening after win 10 update

### ISSUE THREAD

**Issue by ali373** [ContinuumIO/anaconda-issues#10426]
when i click anaconda navigator ,nothing happens,instead,when i type anaconda-navigator in anaconda prompt,get this:

(base) C:\Users\ali>anaconda-navigator
Traceback (most recent call last):
  File "C:\Users\ali\Anaconda2\Scripts\anaconda-navigator-script.py", line 6, in <module>
    from anaconda_navigator.app.main import main
  File "C:\Users\ali\Anaconda2\lib\site-packages\anaconda_navigator\app\main.py", line 22, in <module>
    from anaconda_navigator.utils.conda import is_conda_available
  File "C:\Users\ali\Anaconda2\lib\site-packages\anaconda_navigator\utils\__init__.py", line 15, in <module>
    from qtpy.QtGui import QIcon
  File "C:\Users\ali\Anaconda2\lib\site-packages\qtpy\__init__.py", line 205, in <module>
    raise PythonQtError('No Qt bindings could be found')
qtpy.PythonQtError: No Qt bindings could be found

Note:
1. i've installed qt
2.updated anaconda navigator and conda 
-->yesterday,it was working perfectly.Today,i just installed windows updates and this issues raised after that.

**Comment by goanpeca** [comment]
@ccordoba12 do you know about this?

**Comment by goanpeca** [comment]
@nehaljwani any thoughts on why a windows update would cause this?

**Comment by Shatami76** [comment]
exactly i have the same problem.
