### ISSUE TITLE
Conda has crushed on MAc  os High sierra 

### ISSUE THREAD

**Issue by gsahinpi** [ContinuumIO/anaconda-issues#10434]
### Actual Behavior

Any command related to conda gives the same error  message (SyntaxError: Generator expression must be parenthesized)

### Expected Behavior

Should not give a Syntax error message.

### Steps to Reproduce

just write conda on terminal.

##### Operating System:
MacOs High sierra version 10.13.16
##### `conda info`

```
Traceback (most recent call last):
  File "/Users/gokhansahin/anaconda3/bin/conda", line 11, in <module>
    sys.exit(main())
  File "/Users/gokhansahin/anaconda3/lib/python3.7/site-packages/conda/cli/main.py", line 112, in main
    from ..exceptions import conda_exception_handler
  File "/Users/gokhansahin/anaconda3/lib/python3.7/site-packages/conda/exceptions.py", line 18, in <module>
    from .common.io import timeout
  File "/Users/gokhansahin/anaconda3/lib/python3.7/site-packages/conda/common/io.py", line 24, in <module>
    from .path import expand
  File "/Users/gokhansahin/anaconda3/lib/python3.7/site-packages/conda/common/path.py", line 25, in <module>
    from cytoolz.itertoolz import accumulate, concat, take
  File "/Users/gokhansahin/anaconda3/lib/python3.7/site-packages/cytoolz/__init__.py", line 1, in <module>
    from .itertoolz import *
  File "cytoolz/itertoolz.pyx", line 19, in init cytoolz.itertoolz
  File "cytoolz/utils.pyx", line 10, in init cytoolz.utils
  File "/Users/gokhansahin/anaconda3/lib/python3.7/site-packages/toolz/__init__.py", line 3, in <module>
    from .functoolz import *
  File "/Users/gokhansahin/anaconda3/lib/python3.7/site-packages/toolz/functoolz.py", line 501
    f.__name__ for f in reversed((self.first,) + self.funcs),
    ^
SyntaxError: Generator expression must be parenthesized
```

##### `conda list --show-channel-urls`

```
Traceback (most recent call last):
  File "/Users/gokhansahin/anaconda3/bin/conda", line 11, in <module>
    sys.exit(main())
  File "/Users/gokhansahin/anaconda3/lib/python3.7/site-packages/conda/cli/main.py", line 112, in main
    from ..exceptions import conda_exception_handler
  File "/Users/gokhansahin/anaconda3/lib/python3.7/site-packages/conda/exceptions.py", line 18, in <module>
    from .common.io import timeout
  File "/Users/gokhansahin/anaconda3/lib/python3.7/site-packages/conda/common/io.py", line 24, in <module>
    from .path import expand
  File "/Users/gokhansahin/anaconda3/lib/python3.7/site-packages/conda/common/path.py", line 25, in <module>
    from cytoolz.itertoolz import accumulate, concat, take
  File "/Users/gokhansahin/anaconda3/lib/python3.7/site-packages/cytoolz/__init__.py", line 1, in <module>
    from .itertoolz import *
  File "cytoolz/itertoolz.pyx", line 19, in init cytoolz.itertoolz
  File "cytoolz/utils.pyx", line 10, in init cytoolz.utils
  File "/Users/gokhansahin/anaconda3/lib/python3.7/site-packages/toolz/__init__.py", line 3, in <module>
    from .functoolz import *
  File "/Users/gokhansahin/anaconda3/lib/python3.7/site-packages/toolz/functoolz.py", line 501
    f.__name__ for f in reversed((self.first,) + self.funcs),
    ^
SyntaxError: Generator expression must be parenthesized

```

**Comment by gsahinpi** [comment]
Unfortunately I have uninstalled and installed conda again and the problem
is solved with the exception of requiring an update to Spyder which i am
not reluctant to do.
