### ISSUE TITLE
Miniconda2 latest: exception during conda env create -f exception

### ISSUE THREAD

**Issue by hholst80** [ContinuumIO/anaconda-issues#1043]
I downloaded Miniconda latest 64-bit  and executed the following in Git bash:

```
$ conda env create -f environment.yml
```

with the contents of `environment.yml`

```
name: dev
dependencies:
- backports
- decorator
- dill
- ipython
- libpng
- matplotlib
- numpy
- openssl
- pandas
- pyyaml
- requests
- scikit-learn
- yaml
- zlib
- pip:
  - backports.shutil-get-terminal-size
  - future
  - ipython-genutils
  - logbook
  - prompt-toolkit
```

and I got this error message:

```
...
Extracting packages ...
[pickleshare         ]|#        1 file(s) copied.########                |  69%
[      COMPLETE      ]|##################################################| 100%
Linking packages ...
menuinst Exception:Traceback (most recent call last):##############      |  88%
  File "C:\Miniconda2\lib\site-packages\conda\install.py", line 518, in mk_menus
    menuinst.install(join(prefix, f), remove, prefix)
  File "C:\Miniconda2\lib\site-packages\menuinst\__init__.py", line 57, in install
    "import menuinst; menuinst.install(%r, %r, %r)" % (path, bool(remove), prefix)])
  File "C:\Miniconda2\lib\site-packages\menuinst\win_elevate.py", line 41, in runAsAdmin
    import win32api, win32con, win32event, win32process
ImportError: No module named win32api
Collecting backports.shutil-get-terminal-size
...
```

**Comment by hholst80** [comment]
No longer using conda.
