### ISSUE TITLE
anaconda-navigator fails to start

### ISSUE THREAD

**Issue by MohamedOMY** [ContinuumIO/anaconda-issues#10458]
### Actual Behavior
run anaconda 

Traceback (most recent call last):
  File "/home/mohamed/anaconda2/bin/anaconda-navigator", line 7, in <module>
    from anaconda_navigator.app.main import main
  File "/home/mohamed/anaconda2/lib/python2.7/site-packages/anaconda_navigator/app/main.py", line 22, in <module>
    from anaconda_navigator.utils.conda import is_conda_available
  File "/home/mohamed/anaconda2/lib/python2.7/site-packages/anaconda_navigator/utils/__init__.py", line 15, in <module>
    from qtpy.QtGui import QIcon
  File "/home/mohamed/anaconda2/lib/python2.7/site-packages/qtpy/QtGui.py", line 21, in <module>
    from PyQt5.QtGui import *
ImportError: libGL.so.1: cannot open shared object file: No such file or directory
### Expected Behavior
start anaconda-navigator

some packages are missing 
##### `conda info`

```

```

##### `conda list --show-channel-urls`

```
active environment : base
    active env location : /home/mohamed/anaconda2
            shell level : 1
       user config file : /home/mohamed/.condarc
 populated config files : /home/mohamed/.condarc
          conda version : 4.5.12
    conda-build version : 3.17.6
         python version : 2.7.15.final.0
       base environment : /home/mohamed/anaconda2  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/linux-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/linux-64
                          https://repo.anaconda.com/pkgs/pro/noarch
          package cache : /home/mohamed/anaconda2/pkgs
                          /home/mohamed/.conda/pkgs
       envs directories : /home/mohamed/anaconda2/envs
                          /home/mohamed/.conda/envs
               platform : linux-64
             user-agent : conda/4.5.12 requests/2.21.0 CPython/2.7.15 Linux/4.4.0-17134-Microsoft ubuntu/18.04 glibc/2.27
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False

```

**Comment by goanpeca** [comment]
@ccordoba12, thoughts on this one?
