### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by kankratekaran** [ContinuumIO/anaconda-issues#10463]
## Main error
Application <b>notebook</b> launch may have produced errors.
## Traceback
```
Traceback (most recent call last):
  File "/home/likewise-open/SLSCORP/karan.sharma.445/anaconda3/envs/py36/bin/jupyter-notebook", line 7, in <module>
    from notebook.notebookapp import main
  File "/home/likewise-open/SLSCORP/karan.sharma.445/anaconda3/envs/py36/lib/python3.6/site-packages/notebook/notebookapp.py", line 47, in <module>
    from zmq.eventloop import ioloop
  File "/home/likewise-open/SLSCORP/karan.sharma.445/anaconda3/envs/py36/lib/python3.6/site-packages/zmq/__init__.py", line 47, in <module>
    from zmq import backend
  File "/home/likewise-open/SLSCORP/karan.sharma.445/anaconda3/envs/py36/lib/python3.6/site-packages/zmq/backend/__init__.py", line 40, in <module>
    reraise(*exc_info)
  File "/home/likewise-open/SLSCORP/karan.sharma.445/anaconda3/envs/py36/lib/python3.6/site-packages/zmq/utils/sixcerpt.py", line 34, in reraise
    raise value
  File "/home/likewise-open/SLSCORP/karan.sharma.445/anaconda3/envs/py36/lib/python3.6/site-packages/zmq/backend/__init__.py", line 27, in <module>
    _ns = select_backend(first)
  File "/home/likewise-open/SLSCORP/karan.sharma.445/anaconda3/envs/py36/lib/python3.6/site-packages/zmq/backend/select.py", line 27, in select_backend
    mod = __import__(name, fromlist=public_api)
  File "/home/likewise-open/SLSCORP/karan.sharma.445/anaconda3/envs/py36/lib/python3.6/site-packages/zmq/backend/cython/__init__.py", line 6, in <module>
    from . import (constants, error, message, context,
ImportError: libsodium.so.23: cannot open shared object file: No such file or directory

```
## System information
```
python: 3.6.6
language: en_IN
os: Linux;3.16.0-30-generic;#40~14.04.1-Ubuntu SMP Thu Jan 15 17:43:14 UTC 2015;x86_64;x86_64
version: 1.6.2
platform: linux-64
qt: 5.9.6
pyqt: 5.9.2
conda: 4.5.11
```

**Comment by goanpeca** [comment]
Please remember to update to the latest version of Navigator to include
the latest fixes.

Open a terminal (on Linux or Mac) or the Anaconda Command Prompt (on windows)
and type:

```
conda update conda
conda update anaconda-navigator
conda update navigator-updater
```
