### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by mmccpit** [ContinuumIO/anaconda-issues#10501]
Traceback (most recent call last):
File "C:\Users\mmccp\Anaconda3\Scripts\jupyter-notebook-script.py", line 3, in 
import notebook.notebookapp
File "C:\Users\mmccp\Anaconda3\lib\site-packages\notebook\notebookapp.py", line 40, in 
ioloop.install()
File "C:\Users\mmccp\Anaconda3\lib\site-packages\zmq\eventloop\ioloop.py", line 210, in install
assert (not ioloop.IOLoop.initialized()) or \
AttributeError: type object 'IOLoop' has no attribute 'initialized'

**Comment by goanpeca** [comment]
Please provide information requested on the issue template



### Actual Behavior



### Expected Behavior



### Steps to Reproduce




##### Anaconda or Miniconda version:

##### Operating System:

##### `conda info`

```

```

##### `conda list --show-channel-urls`

```

```

**Comment by vshevchenko-anaconda** [comment]
I'm closing this ticket as stale. Please, open a new ticket if needed.
