### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by akshay8** [ContinuumIO/anaconda-issues#10545]
## Main error
Application <b>notebook</b> launch may have produced errors.
## Traceback
```
Traceback (most recent call last):
  File "C:\Users\om\Anaconda3\Scripts\jupyter-notebook-script.py", line 3, in <module>
    import notebook.notebookapp
  File "C:\Users\om\Anaconda3\lib\site-packages\notebook\notebookapp.py", line 40, in <module>
    ioloop.install()
  File "C:\Users\om\Anaconda3\lib\site-packages\zmq\eventloop\ioloop.py", line 207, in install
    from tornado import ioloop
  File "C:\Users\om\Anaconda3\lib\site-packages\tornado\ioloop.py", line 55, in <module>
    from tornado.util import (
ImportError: cannot import name 'TimeoutError'

```
## System information
```
python: 3.6.1
language: en_US
os: Windows;7;6.1.7601;x86;x86 Family 6 Model 23 Stepping 10, GenuineIntel
version: 1.6.2
platform: win-32
qt: 5.6.2
pyqt: 5.6.0
conda: 4.3.21
```
Jupyter notebook fails to open with this error.Any help?

**Comment by goanpeca** [comment]
Please remember to update to the latest version of Navigator to include
the latest fixes.

Open a terminal (on Linux or Mac) or the Anaconda Command Prompt (on windows)
and type:

```
conda update conda
conda update --all
```
