### ISSUE TITLE
Pillow conda package no longer working on Windows due to libtiff 4.0.10

### ISSUE THREAD

**Issue by astrofrog** [ContinuumIO/anaconda-issues#10553]
I am seeing errors with the latest pillow conda package on Windows with Python 2.7, due I think to an update in the libtiff library - specifically, things are broken with libtiff 4.0.10-he490001_1001 but work with libtiff 4.0.9-he490001_2.

### Steps to Reproduce

```
conda install pillow
```

then:

```
>>> from PIL import Image
```

### Actual Behavior

The import causes the following exception:

```
Executing: python test.py
Traceback (most recent call last):
  File "test.py", line 1, in <module>
    from PIL import Image
  File "C:\conda\envs\test\lib\site-packages\PIL\Image.py", line 94, in <module>
    from . import _imaging as core
ImportError: DLL load failed: The specified module could not be found.
```

(Full log in reproducible CI environment: https://ci.appveyor.com/project/glue-viz/glue/builds/21936417/job/0ajnci606j5kejd0)

Downgrading to libtiff 4.0.9 fixes the issue.

### Expected Behavior

No crash.

##### Anaconda or Miniconda version:

Miniconda latest

##### Operating System:

Windows

##### `conda info`

```
     active environment : test
    active env location : C:\conda\envs\test
            shell level : 1
       user config file : C:\Users\appveyor\.condarc
 populated config files : C:\Users\appveyor\.condarc
          conda version : 4.5.10
    conda-build version : not installed
         python version : 3.7.1.final.0
       base environment : C:\conda  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/win-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/win-64
                          https://repo.anaconda.com/pkgs/pro/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\conda\pkgs
                          C:\Users\appveyor\AppData\Local\conda\conda\pkgs
       envs directories : C:\conda\envs
                          C:\Users\appveyor\AppData\Local\conda\conda\envs
                          C:\Users\appveyor\.conda\envs
               platform : win-64
             user-agent : conda/4.5.10 requests/2.21.0 CPython/3.7.1 Windows/2012ServerR2 Windows/6.3.9600
          administrator : True
             netrc file : None
           offline mode : False
```

##### `conda list --show-channel-urls`

```
# packages in environment at C:\conda\envs\test:
#
# Name                    Version                   Build  Channel
atomicwrites              1.2.1                    py27_0    defaults
attrs                     18.2.0           py27h28b3542_0    defaults
certifi                   2018.11.29               py27_0    defaults
colorama                  0.4.1                    py27_0    defaults
freetype                  2.9.1                h4d385ea_1    defaults
funcsigs                  1.0.2            py27h8885ae1_0    defaults
jpeg                      9b                   ha175dff_2    defaults
libpng                    1.6.36               h7a46e7a_0    defaults
libtiff                   4.0.10            he490001_1001    defaults
more-itertools            5.0.0                    py27_0    defaults
olefile                   0.46                     py27_0    defaults
pathlib2                  2.3.3                    py27_0    defaults
pillow                    5.4.1            py27h5b88493_0    defaults
pip                       19.0.1                    <pip>
pip                       18.1                     py27_0    defaults
pluggy                    0.8.1                    py27_0    defaults
py                        1.7.0                    py27_0    defaults
pytest                    4.1.1                    py27_0    defaults
python                    2.7.15               hcb6e200_5    defaults
scandir                   1.9.0            py27h0c8e037_0    defaults
setuptools                40.6.3                   py27_0    defaults
six                       1.12.0                   py27_0    defaults
sqlite                    3.26.0               h0c8e037_0    defaults
tk                        8.6.8                h0c8e037_0    defaults
vc                        9                    h7299396_1    defaults
vs2008_runtime            9.00.30729.5054               0    defaults
wheel                     0.32.3                   py27_0    defaults
wincertstore              0.2              py27hf04cefb_0    defaults
zlib                      1.2.11               h3cc03e0_3    defaults
```

**Comment by jjhelmus** [comment]
Thanks for bringing this to our attention.  There were some issue with the libtiff 4.0.10 packages, they have been revoked from the repository, new environment should install the working 4.0.9 packages.  New working builds of 4.0.10 should be available shortly.

**Comment by jjhelmus** [comment]
Corrected libtiff 4.0.10 packages are available in `pkgs/main`.

**Comment by astrofrog** [comment]
Thanks!

**Comment by ronaldsipkema** [comment]
It seems the broken and removed libtiff 4.0.10 packages (h2929a5b_1001 and he490001_1001) have been re-added as .conda files to the main repo, i.e., when using conda 4.7+ things no longer work.

**Comment by jjhelmus** [comment]
The broken libtiff .conda packages have been removed.
