### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by wangjiatao** [ContinuumIO/anaconda-issues#10581]
## Main error
Application <b>spyder</b> launch may have produced errors.
## Traceback
```
Traceback (most recent call last):
  File "/Users/wangjiatao/anaconda/bin/spyder", line 7, in <module>
    from spyder.app.start import main
  File "/Users/wangjiatao/anaconda/lib/python3.6/site-packages/spyder/app/start.py", line 35, in <module>
    from spyder.config.main import CONF
  File "/Users/wangjiatao/anaconda/lib/python3.6/site-packages/spyder/config/main.py", line 22, in <module>
    from spyder.config.user import UserConfig
  File "/Users/wangjiatao/anaconda/lib/python3.6/site-packages/spyder/config/user.py", line 26, in <module>
    from spyder.utils.programs import check_version
  File "/Users/wangjiatao/anaconda/lib/python3.6/site-packages/spyder/utils/programs.py", line 18, in <module>
    import subprocess
  File "/Users/wangjiatao/anaconda/lib/python3.6/subprocess.py", line 136, in <module>
    import _posixsubprocess
ImportError: dlopen(/Users/wangjiatao/anaconda/lib/python3.6/lib-dynload/_posixsubprocess.cpython-36m-darwin.so, 2): Symbol not found: __Py_set_inheritable_async_safe
  Referenced from: /Users/wangjiatao/anaconda/lib/python3.6/lib-dynload/_posixsubprocess.cpython-36m-darwin.so
  Expected in: flat namespace
 in /Users/wangjiatao/anaconda/lib/python3.6/lib-dynload/_posixsubprocess.cpython-36m-darwin.so

```
## System information
```
python: 3.6.8
language: en
os: Darwin;18.2.0;Darwin Kernel Version 18.2.0: Thu Dec 20 20:46:53 PST 2018; root:xnu-4903.241.1~1/RELEASE_X86_64;x86_64;i386
version: 1.6.2
platform: osx-64
qt: 5.6.2
pyqt: 5.6.0
conda: 4.6.2
```

**Comment by yassinpy** [comment]
please remove this file

.condarc and try again

**Comment by goanpeca** [comment]
Also remember to update to the latest version of Navigator to include
the latest fixes.

Open a terminal (on Linux or Mac) or the Anaconda Command Prompt (on windows)
and type:

```
conda update conda
conda update anaconda-navigator
conda update navigator-updater
```
