### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by ArturoOntiveros** [ContinuumIO/anaconda-issues#10603]
### Actual Behavior

I tryed to start anaconda, but after 20 seconds of waiting, a chrome browser showed up with an error

### Expected Behavior

inicialize anaconda

### Steps to Reproduce

Click twice on Anaconda's logo. The app start with anacondas logo like loading the program, and then just a chrome browser apears with teh issue

##### Anaconda or Miniconda version:

anaconda2 5.1.0 64-bit

##### Operating System:

Microsoft Windows 10 Home Single Language

##### `conda info`

```
Navigator Error
An unexpected error occurred on Navigator start-up

Report
Please report this issue in the anaconda issue tracker

Main Error
object of type 'NoneType' has no len()
Traceback
Traceback (most recent call last):
  File "C:\Users\Arturo Ontiveros\Anaconda2\lib\site-packages\anaconda_navigator\exceptions.py", line 75, in exception_handler
    return_value = func(*args, **kwargs)
  File "C:\Users\Arturo Ontiveros\Anaconda2\lib\site-packages\anaconda_navigator\app\start.py", line 138, in start_app
    window = run_app(splash)
  File "C:\Users\Arturo Ontiveros\Anaconda2\lib\site-packages\anaconda_navigator\app\start.py", line 64, in run_app
    window = MainWindow(splash=splash, tab_project=False)
  File "C:\Users\Arturo Ontiveros\Anaconda2\lib\site-packages\anaconda_navigator\widgets\main_window.py", line 163, in __init__
    self.api = AnacondaAPI()
  File "C:\Users\Arturo Ontiveros\Anaconda2\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 2127, in AnacondaAPI
    ANACONDA_API = _AnacondaAPI()
  File "C:\Users\Arturo Ontiveros\Anaconda2\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 89, in __init__
    self._conda_api = CondaAPI()
  File "C:\Users\Arturo Ontiveros\Anaconda2\lib\site-packages\anaconda_navigator\api\conda_api.py", line 1714, in CondaAPI
    CONDA_API = _CondaAPI()
  File "C:\Users\Arturo Ontiveros\Anaconda2\lib\site-packages\anaconda_navigator\api\conda_api.py", line 353, in __init__
    self.sys_rc_path = join(self.ROOT_PREFIX, '.condarc')
  File "C:\Users\Arturo Ontiveros\Anaconda2\lib\ntpath.py", line 65, in join
    result_drive, result_path = splitdrive(path)
  File "C:\Users\Arturo Ontiveros\Anaconda2\lib\ntpath.py", line 115, in splitdrive
    if len(p) > 1:
TypeError: object of type 'NoneType' has no len()
```

##### `conda list --show-channel-urls`

```

```

**Comment by goanpeca** [comment]
Please provide the information requested on the issue template



### Actual Behavior



### Expected Behavior



### Steps to Reproduce




##### Anaconda or Miniconda version:

##### Operating System:

##### `conda info`

```

```

##### `conda list --show-channel-urls`

```

```
