### ISSUE TITLE
Sypder, Jupyter not launch from Navigator but can be launched from Prompt

### ISSUE THREAD

**Issue by xravian** [ContinuumIO/anaconda-issues#10605]
### Actual Behavior

I try to launch Sypder or Jupyter Notebook from Navigator, but nothing happens except a loading progress bar shown at the right-bottom of the Navigator.

![from_navigator](https://user-images.githubusercontent.com/10709265/52531185-87c35280-2d4c-11e9-80fd-09935974636f.gif)

### Expected Behavior

Launch Spyder as it should from Navigator.

### Steps to Reproduce

Install Anaconda3-2018.12-Windows-x86_64.exe. 
Start Navigator.
Click Spyder tool from base environment.
Nothing happens.

##### Anaconda or Miniconda version:

Anaconda Navigator 1.9.6
Conda 4.5.12

##### Operating System:

Windows 10 Pro x64 1809

##### `conda info`
```
(base) D:\Anaconda3\Scripts>conda info

     active environment : base
    active env location : D:\Anaconda3
            shell level : 1
       user config file : C:\Users\杨圣青\.condarc
 populated config files : C:\Users\杨圣青\.condarc
          conda version : 4.5.12
    conda-build version : 3.17.6
         python version : 3.7.1.final.0
       base environment : D:\Anaconda3  (writable)
           channel URLs : https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/win-64
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/noarch
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/msys2/win-64
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/msys2/noarch
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/win-64
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/noarch
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/win-64
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/noarch
          package cache : D:\Anaconda3\pkgs
                          C:\Users\杨圣青\AppData\Local\conda\conda\pkgs
       envs directories : D:\Anaconda3\envs
                          C:\Users\杨圣青\AppData\Local\conda\conda\envs
                          C:\Users\杨圣青\.conda\envs
               platform : win-64
             user-agent : conda/4.5.12 requests/2.21.0 CPython/3.7.1 Windows/10 Windows/10.0.17763
          administrator : False
             netrc file : None
           offline mode : False
```

##### `conda list --show-channel-urls`

I believe that this issue is not related to conda list. If anyone still need it, I will put the list here.

### More information

I think the problem is related to the Unicode user name in the path `C:\Users\杨圣青\`. I just don't know where the problem starts. I have tried to search config string including the Unicode name but with no luck to solve the problem.

I can launch the Spyder from Windows Start Menu, from Anaconda Prompt. So I think the package is installed correctly.

![from_startmenu](https://user-images.githubusercontent.com/10709265/52531189-9c074f80-2d4c-11e9-88cf-5b04ebc40e80.gif)

![from_prompt](https://user-images.githubusercontent.com/10709265/52531205-a88ba800-2d4c-11e9-9556-7227b48aef6f.gif)

I am aware of that I cannot install Anaconda to the path containing Unicode char or space. So I installed it at D:\Anaconda3\. Everything is going well except I cannot launch any tool from Navigartor. In addition, I have tried to create new environment and install Spyder, the problem persists: I can start Spyder from Start Menu or  Prompt, but not from Navigator itself.

When I run the spyder.exe from Windows default cmd, it returns error as follow:

```
D:\Anaconda3\Scripts>spyder
Traceback (most recent call last):
  File "D:\Anaconda3\lib\site-packages\qtpy\__init__.py", line 199, in <module>
    from PySide import __version__ as PYSIDE_VERSION  # analysis:ignore
ModuleNotFoundError: No module named 'PySide'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Anaconda3\Scripts\spyder-script.py", line 10, in <module>
    sys.exit(main())
  File "D:\Anaconda3\lib\site-packages\spyder\app\start.py", line 186, in main
    from spyder.app import mainwindow
  File "D:\Anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 48, in <module>
    requirements.check_qt()
  File "D:\Anaconda3\lib\site-packages\spyder\requirements.py", line 41, in check_qt
    import qtpy
  File "D:\Anaconda3\lib\site-packages\qtpy\__init__.py", line 205, in <module>
    raise PythonQtError('No Qt bindings could be found')
qtpy.PythonQtError: No Qt bindings could be found
``` 

Thanks in advanced for anyone looking into this issue.

**Comment by xravian** [comment]
Anyone?

**Comment by HeroadZ** [comment]
Same situation with you. Just can't find the reason.

**Comment by lumirinc** [comment]
I am facing the same situation even in 2021.
