### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by rishabhrshanbhag** [ContinuumIO/anaconda-issues#10607]
## Main error
Application <b>jupyterlab</b> launch may have produced errors.
## Traceback
```
[I 12:14:28.842 LabApp] The port 8888 is already in use, trying another port.
[I 12:14:28.843 LabApp] The port 8889 is already in use, trying another port.
[I 12:14:28.843 LabApp] The port 8890 is already in use, trying another port.
[I 12:14:28.844 LabApp] The port 8891 is already in use, trying another port.
[I 12:14:28.857 LabApp] JupyterLab extension loaded from E:\ProgramData\Anaconda3\lib\site-packages\jupyterlab
[I 12:14:28.857 LabApp] JupyterLab application directory is E:\ProgramData\Anaconda3\share\jupyter\lab
[W 12:14:28.858 LabApp] JupyterLab server extension not enabled, manually loading...
[I 12:14:28.862 LabApp] JupyterLab extension loaded from E:\ProgramData\Anaconda3\lib\site-packages\jupyterlab
[I 12:14:28.862 LabApp] JupyterLab application directory is E:\ProgramData\Anaconda3\share\jupyter\lab
[I 12:14:28.862 LabApp] Serving notebooks from local directory: E:\Program Files\Anaconda3.6\Jupyter Notebook
[I 12:14:28.862 LabApp] The Jupyter Notebook is running at:
[I 12:14:28.862 LabApp] http://localhost:8892/?token=ca1ac8b9fab847323fd0ac1a7106432853a3635f20adba2a
[I 12:14:28.863 LabApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 12:14:28.881 LabApp] 
    
    To access the notebook, open this file in a browser:
        file:///C:/Users/Telekenesis/AppData/Roaming/jupyter/runtime/nbserver-15872-open.html
    Or copy and paste one of these URLs:
        http://localhost:8892/?token=ca1ac8b9fab847323fd0ac1a7106432853a3635f20adba2a
[W 12:14:31.746 LabApp] Could not determine jupyterlab build status without nodejs
[I 12:14:37.256 LabApp] Kernel started: debd3e9b-320a-4ad5-9e1e-6e31ec5d6b30
ERROR:tornado.general:Uncaught exception in ZMQStream callback
Traceback (most recent call last):
  File "E:\ProgramData\Anaconda3\lib\site-packages\zmq\eventloop\zmqstream.py", line 432, in _run_callback
    callback(*args, **kwargs)
  File "E:\ProgramData\Anaconda3\lib\site-packages\tornado\stack_context.py", line 277, in null_wrapper
    return fn(*args, **kwargs)
  File "E:\ProgramData\Anaconda3\lib\site-packages\ipykernel\kernelbase.py", line 283, in dispatcher
    return self.dispatch_shell(stream, msg)
  File "E:\ProgramData\Anaconda3\lib\site-packages\ipykernel\kernelbase.py", line 233, in dispatch_shell
    self.pre_handler_hook()
  File "E:\ProgramData\Anaconda3\lib\site-packages\ipykernel\kernelbase.py", line 248, in pre_handler_hook
    self.saved_sigint_handler = signal(SIGINT, default_int_handler)
  File "E:\ProgramData\Anaconda3\lib\signal.py", line 47, in signal
    handler = _signal.signal(_enum_to_int(signalnum), _enum_to_int(handler))
ValueError: signal only works in main thread
ERROR:tornado.general:Uncaught exception in zmqstream callback
Traceback (most recent call last):
  File "E:\ProgramData\Anaconda3\lib\site-packages\zmq\eventloop\zmqstream.py", line 450, in _handle_events
    self._handle_recv()
  File "E:\ProgramData\Anaconda3\lib\site-packages\zmq\eventloop\zmqstream.py", line 480, in _handle_recv
    self._run_callback(callback, msg)
  File "E:\ProgramData\Anaconda3\lib\site-packages\zmq\eventloop\zmqstream.py", line 432, in _run_callback
    callback(*args, **kwargs)
  File "E:\ProgramData\Anaconda3\lib\site-packages\tornado\stack_context.py", line 277, in null_wrapper
    return fn(*args, **kwargs)
  File "E:\ProgramData\Anaconda3\lib\site-packages\ipykernel\kernelbase.py", line 283, in dispatcher
    return self.dispatch_shell(stream, msg)
  File "E:\ProgramData\Anaconda3\lib\site-packages\ipykernel\kernelbase.py", line 233, in dispatch_shell
    self.pre_handler_hook()
  File "E:\ProgramData\Anaconda3\lib\site-packages\ipykernel\kernelbase.py", line 248, in pre_handler_hook
    self.saved_sigint_handler = signal(SIGINT, default_int_handler)
  File "E:\ProgramData\Anaconda3\lib\signal.py", line 47, in signal
    handler = _signal.signal(_enum_to_int(signalnum), _enum_to_int(handler))
ValueError: signal only works in main thread
ERROR:tornado.application:Exception in callback (<zmq.sugar.socket.Socket object at 0x0000015841C69E18>, <function wrap.<locals>.null_wrapper at 0x0000015841C68C80>)
Traceback (most recent call last):
  File "E:\ProgramData\Anaconda3\lib\site-packages\tornado\ioloop.py", line 888, in start
    handler_func(fd_obj, events)
  File "E:\ProgramData\Anaconda3\lib\site-packages\tornado\stack_context.py", line 277, in null_wrapper
    return fn(*args, **kwargs)
  File "E:\ProgramData\Anaconda3\lib\site-packages\zmq\eventloop\zmqstream.py", line 450, in _handle_events
    self._handle_recv()
  File "E:\ProgramData\Anaconda3\lib\site-packages\zmq\eventloop\zmqstream.py", line 480, in _handle_recv
    self._run_callback(callback, msg)
  File "E:\ProgramData\Anaconda3\lib\site-packages\zmq\eventloop\zmqstream.py", line 432, in _run_callback
    callback(*args, **kwargs)
  File "E:\ProgramData\Anaconda3\lib\site-packages\tornado\stack_context.py", line 277, in null_wrapper
    return fn(*args, **kwargs)
  File "E:\ProgramData\Anaconda3\lib\site-packages\ipykernel\kernelbase.py", line 283, in dispatcher
    return self.dispatch_shell(stream, msg)
  File "E:\ProgramData\Anaconda3\lib\site-packages\ipykernel\kernelbase.py", line 233, in dispatch_shell
    self.pre_handler_hook()
  File "E:\ProgramData\Anaconda3\lib\site-packages\ipykernel\kernelbase.py", line 248, in pre_handler_hook
    self.saved_sigint_handler = signal(SIGINT, default_int_handler)
  File "E:\ProgramData\Anaconda3\lib\signal.py", line 47, in signal
    handler = _signal.signal(_enum_to_int(signalnum), _enum_to_int(handler))
ValueError: signal only works in main thread

```
## System information
```
python: 3.6.8
language: en_IN
os: Windows;10;10.0.17763;AMD64;Intel64 Family 6 Model 158 Stepping 9, GenuineIntel
version: 1.6.2
platform: win-64
qt: 5.9.6
pyqt: 5.9.2
conda: 4.5.11
```

**Comment by goanpeca** [comment]
Please remember to update to the latest version of Navigator to include
the latest fixes.

Open a terminal (on Linux or Mac) or the Anaconda Command Prompt (on windows)
and type:

```
conda update conda
conda update --all
```
