### ISSUE TITLE
No idea what this means...help

### ISSUE THREAD

**Issue by mca21821** [ContinuumIO/anaconda-issues#10602]
'conda_prefix'
Traceback

Traceback (most recent call last):
  File "/Users/markchristianadams/anaconda2/lib/python2.7/site-packages/anaconda_navigator/exceptions.py", line 75, in exception_handler
    return_value = func(*args, **kwargs)
  File "/Users/markchristianadams/anaconda2/lib/python2.7/site-packages/anaconda_navigator/app/start.py", line 151, in start_app
    window = run_app(splash)
  File "/Users/markchristianadams/anaconda2/lib/python2.7/site-packages/anaconda_navigator/app/start.py", line 65, in run_app
    window = MainWindow(splash=splash, tab_project=False)
  File "/Users/markchristianadams/anaconda2/lib/python2.7/site-packages/anaconda_navigator/widgets/main_window.py", line 168, in __init__
    self.api = AnacondaAPI()
  File "/Users/markchristianadams/anaconda2/lib/python2.7/site-packages/anaconda_navigator/api/anaconda_api.py", line 2337, in AnacondaAPI
    ANACONDA_API = _AnacondaAPI()
  File "/Users/markchristianadams/anaconda2/lib/python2.7/site-packages/anaconda_navigator/api/anaconda_api.py", line 89, in __init__
    self._conda_api = CondaAPI()
  File "/Users/markchristianadams/anaconda2/lib/python2.7/site-packages/anaconda_navigator/api/conda_api.py", line 1767, in CondaAPI
    CONDA_API = _CondaAPI()
  File "/Users/markchristianadams/anaconda2/lib/python2.7/site-packages/anaconda_navigator/api/conda_api.py", line 350, in __init__
    self.set_conda_prefix(info=get_conda_info())
  File "/Users/markchristianadams/anaconda2/lib/python2.7/site-packages/anaconda_navigator/api/conda_api.py", line 506, in set_conda_prefix
    self.CONDA_PREFIX = info['conda_prefix']
KeyError: 'conda_prefix'

**Comment by goanpeca** [comment]
Please provide the information requested on the issue template



### Actual Behavior



### Expected Behavior



### Steps to Reproduce




##### Anaconda or Miniconda version:

##### Operating System:

##### `conda info`

```

```

##### `conda list --show-channel-urls`

```

```
