### ISSUE TITLE
Navigator Error: TypeError: expected str, bytes or os.PathLike object, not NoneType

### ISSUE THREAD

**Issue by Sefayay** [ContinuumIO/anaconda-issues#10637]
### Actual Behavior

I installed the anaconda my laptop.

### Expected Behavior

After installing the program I wanted to run the program.

AND THE RESULT

Navigator Error
An unexpected error occurred on Navigator start-up

Report
Please report this issue in the anaconda issue tracker

Main Error
expected str, bytes or os.PathLike object, not NoneType
Traceback
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\anaconda_navigator\exceptions.py", line 75, in exception_handler
    return_value = func(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 150, in start_app
    window = run_app(splash)
  File "C:\ProgramData\Anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 65, in run_app
    window = MainWindow(splash=splash, tab_project=False)
  File "C:\ProgramData\Anaconda3\lib\site-packages\anaconda_navigator\widgets\main_window.py", line 168, in __init__
    self.api = AnacondaAPI()
  File "C:\ProgramData\Anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 2294, in AnacondaAPI
    ANACONDA_API = _AnacondaAPI()
  File "C:\ProgramData\Anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 91, in __init__
    self._conda_api = CondaAPI()
  File "C:\ProgramData\Anaconda3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 1767, in CondaAPI
    CONDA_API = _CondaAPI()
  File "C:\ProgramData\Anaconda3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 353, in __init__
    self.sys_rc_path = join(self.ROOT_PREFIX, '.condarc')
  File "C:\ProgramData\Anaconda3\lib\ntpath.py", line 76, in join
    path = os.fspath(path)
TypeError: expected str, bytes or os.PathLike object, not NoneType

**Comment by canthonyscott** [comment]
I am getting something similar. This was working find yesterday. Reinstalling Anaconda did not fix it.

```
(base) C:\Users\ascot>conda update -v -v conda
DEBUG conda.gateways.logging:set_verbosity(150): verbosity set to 2
DEBUG conda.core.solve:solve_final_state(212): solving prefix C:\Users\ascot\Anaconda3
  specs_to_remove: frozenset()
  specs_to_add: frozenset({MatchSpec("conda")})
  prune: False
Collecting package metadata: ...working... DEBUG conda.core.package_cache_data:_check_writable(252): package cache directory 'C:\Users\ascot\Anaconda3\pkgs' writable: True
DEBUG conda.core.subdir_data:_load(207): Using cached repodata for https://repo.anaconda.com/pkgs/free/win-64 at C:\Users\ascot\Anaconda3\pkgs\cache\d6a04735.json. Timeout in 7 sec
DEBUG conda.core.subdir_data:_read_pickled(284): found pickle file C:\Users\ascot\Anaconda3\pkgs\cache\d6a04735.q
DEBUG conda.core.subdir_data:_read_pickled(302): Pickle load validation failed for https://repo.anaconda.com/pkgs/free/win-64 at C:\Users\ascot\Anaconda3\pkgs\cache\d6a04735.json.
DEBUG conda.core.subdir_data:_read_local_repdata(257): Loading raw json for https://repo.anaconda.com/pkgs/free/win-64 at C:\Users\ascot\Anaconda3\pkgs\cache\d6a04735.json
failed

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "C:\Users\ascot\Anaconda3\lib\site-packages\conda\exceptions.py", line 1002, in __call__
        return func(*args, **kwargs)
      File "C:\Users\ascot\Anaconda3\lib\site-packages\conda\cli\main.py", line 84, in _main
        exit_code = do_call(args, p)
      File "C:\Users\ascot\Anaconda3\lib\site-packages\conda\cli\conda_argparse.py", line 82, in do_call
        exit_code = getattr(module, func_name)(args, parser)
      File "C:\Users\ascot\Anaconda3\lib\site-packages\conda\cli\main_update.py", line 20, in execute
        install(args, parser, 'update')
      File "C:\Users\ascot\Anaconda3\lib\site-packages\conda\cli\install.py", line 253, in install
        force_reinstall=context.force_reinstall or context.force,
      File "C:\Users\ascot\Anaconda3\lib\site-packages\conda\core\solve.py", line 107, in solve_for_transaction
        force_remove, force_reinstall)
      File "C:\Users\ascot\Anaconda3\lib\site-packages\conda\core\solve.py", line 145, in solve_for_diff
        force_remove)
      File "C:\Users\ascot\Anaconda3\lib\site-packages\conda\core\solve.py", line 235, in solve_final_state
        ssc = self._collect_all_metadata(ssc)
      File "C:\Users\ascot\Anaconda3\lib\site-packages\conda\common\io.py", line 85, in decorated
        return f(*args, **kwds)
      File "C:\Users\ascot\Anaconda3\lib\site-packages\conda\core\solve.py", line 286, in _collect_all_metadata
        index, r = self._prepare(prepared_specs)
      File "C:\Users\ascot\Anaconda3\lib\site-packages\conda\core\solve.py", line 678, in _prepare
        self.subdirs, prepared_specs)
      File "C:\Users\ascot\Anaconda3\lib\site-packages\conda\core\index.py", line 213, in get_reduced_index
        new_records = query_all(spec)
      File "C:\Users\ascot\Anaconda3\lib\site-packages\conda\core\index.py", line 176, in query_all
        return tuple(concat(future.result() for future in as_completed(futures)))
      File "C:\Users\ascot\Anaconda3\lib\site-packages\conda\core\subdir_data.py", line 93, in query
        self.load()
      File "C:\Users\ascot\Anaconda3\lib\site-packages\conda\core\subdir_data.py", line 147, in load
        _internal_state = self._load()
      File "C:\Users\ascot\Anaconda3\lib\site-packages\conda\core\subdir_data.py", line 209, in _load
        mod_etag_headers.get('_mod'))
      File "C:\Users\ascot\Anaconda3\lib\site-packages\conda\core\subdir_data.py", line 271, in _read_local_repdata
        _internal_state = self._process_raw_repodata_str(raw_repodata_str)
      File "C:\Users\ascot\Anaconda3\lib\site-packages\conda\core\subdir_data.py", line 367, in _process_raw_repodata_str
        package_record = PackageRecord(**info)
      File "C:\Users\ascot\Anaconda3\lib\site-packages\conda\_vendor\auxlib\entity.py", line 722, in __call__
        instance = super(EntityType, cls).__call__(*args, **kwargs)
      File "C:\Users\ascot\Anaconda3\lib\site-packages\conda\_vendor\auxlib\entity.py", line 739, in __init__
        setattr(self, key, kwargs[key])
      File "C:\Users\ascot\Anaconda3\lib\site-packages\conda\_vendor\auxlib\entity.py", line 430, in __set__
        instance.__dict__[self.name] = self.validate(instance, self.box(instance, instance.__class__, val))
      File "C:\Users\ascot\Anaconda3\lib\site-packages\conda\models\records.py", line 103, in box
        val = tuple(f for f in (ff.strip() for ff in val) if f)
    TypeError: 'NoneType' object is not iterable

`$ C:\Users\ascot\Anaconda3\Scripts\conda-script.py update -v -v conda`

  environment variables:
                 CIO_TEST=<not set>
        CONDA_DEFAULT_ENV=base
                CONDA_EXE=C:\Users\ascot\Anaconda3\Scripts\conda.exe
             CONDA_PREFIX=C:\Users\ascot\Anaconda3
    CONDA_PROMPT_MODIFIER=(base)
         CONDA_PYTHON_EXE=C:\Users\ascot\Anaconda3\python.exe
               CONDA_ROOT=C:\Users\ascot\Anaconda3
              CONDA_SHLVL=1
                 HOMEPATH=\Users\ascot
                     PATH=C:\Users\ascot\Anaconda3;C:\Users\ascot\Anaconda3\Library\mingw-w64\bi
                          n;C:\Users\ascot\Anaconda3\Library\usr\bin;C:\Users\ascot\Anaconda3\Li
                          brary\bin;C:\Users\ascot\Anaconda3\Scripts;C:\Users\ascot\Anaconda3\bi
                          n;C:\windows\system32;C:\windows;C:\windows\System32\Wbem;C:\windows\S
                          ystem32\WindowsPowerShell\v1.0\;C:\windows\System32\OpenSSH\;C:\Progra
                          m Files (x86)\PuTTY\;C:\Program Files\Git\cmd;C:\Users\ascot\AppData\L
                          ocal\Microsoft\WindowsApps;;C:\Users\ascot\AppData\Local\Programs\Micr
                          osoft VS Code\bin
             PSMODULEPATH=C:\Program Files\WindowsPowerShell\Modules;C:\windows\system32\Windows
                          PowerShell\v1.0\Modules
         PYTHONIOENCODING=1252
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>

     active environment : base
    active env location : C:\Users\ascot\Anaconda3
            shell level : 1
       user config file : C:\Users\ascot\.condarc
 populated config files : C:\Users\ascot\.condarc
          conda version : 4.6.3
    conda-build version : 3.17.6
         python version : 3.7.1.final.0
       base environment : C:\Users\ascot\Anaconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/win-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\Users\ascot\Anaconda3\pkgs
                          C:\Users\ascot\.conda\pkgs
                          C:\Users\ascot\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\ascot\Anaconda3\envs
                          C:\Users\ascot\.conda\envs
                          C:\Users\ascot\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.6.3 requests/2.21.0 CPython/3.7.1 Windows/10 Windows/10.0.17134
          administrator : False
             netrc file : None
           offline mode : False


An unexpected error has occurred. Conda has prepared the above report.

If submitted, this report will be used by core maintainers to improve
future releases of conda.
Would you like conda to send this report to the core maintainers?

[y/N]:
```

**Comment by goanpeca** [comment]
Please provide the information requested on the issue template



### Actual Behavior



### Expected Behavior



### Steps to Reproduce




##### Anaconda or Miniconda version:

##### Operating System:

##### `conda info`

```

```

##### `conda list --show-channel-urls`

```

```

**Comment by csoja** [comment]
It is most helpful when the information in the template is provided - particularly conda info and conda list --show-channel-urls
Some people have been able to "fix" similar issues by removing their .condarc file, so you may want to back it up, and try that.
