### ISSUE TITLE
Navigator Error Key error 'root_prefix'

### ISSUE THREAD

**Issue by joaquinmurrieta32** [ContinuumIO/anaconda-issues#10631]
### Actual Behavior
Opens an HTML file with error

### Expected Behavior
Open Anaconda Navigator

### Steps to Reproduce
Run Anaconda Navigator

##### Anaconda or Miniconda version:
Anaconda 2018.12 for Windows Installer Python 3.7
##### Operating System:
Windows 10
##### `conda info`

```

Navigator Error

An unexpected error occurred on Navigator start-up

Report

Please report this issue in the anaconda issue tracker  


Main Error

'root_prefix'


Traceback

Traceback (most recent call last):
  File "C:\Users\Joaquin\Anaconda3\lib\site-packages\anaconda_navigator\exceptions.py", line 75, in exception_handler
    return_value = func(*args, **kwargs)
  File "C:\Users\Joaquin\Anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 151, in start_app
    window = run_app(splash)
  File "C:\Users\Joaquin\Anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 65, in run_app
    window = MainWindow(splash=splash, tab_project=False)
  File "C:\Users\Joaquin\Anaconda3\lib\site-packages\anaconda_navigator\widgets\main_window.py", line 168, in __init__
    self.api = AnacondaAPI()
  File "C:\Users\Joaquin\Anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 2337, in AnacondaAPI
    ANACONDA_API = _AnacondaAPI()
  File "C:\Users\Joaquin\Anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 89, in __init__
    self._conda_api = CondaAPI()
  File "C:\Users\Joaquin\Anaconda3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 1767, in CondaAPI
    CONDA_API = _CondaAPI()
  File "C:\Users\Joaquin\Anaconda3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 350, in __init__
    self.set_conda_prefix(info=get_conda_info())
  File "C:\Users\Joaquin\Anaconda3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 505, in set_conda_prefix
    self.ROOT_PREFIX = info['root_prefix']
KeyError: 'root_prefix'


```

##### `conda list --show-channel-urls`

```

```

**Comment by goanpeca** [comment]
Please provide the information requested on the issue template



### Actual Behavior



### Expected Behavior



### Steps to Reproduce




##### Anaconda or Miniconda version:

##### Operating System:

##### `conda info`

```

```

##### `conda list --show-channel-urls`

```

```

**Comment by yoyo-sincerely** [comment]
I got the same problem.
```
conda info
```
```

     active environment : None
            shell level : 0
       user config file : C:\Users\yoyo\.condarc
 populated config files : C:\Users\yoyo\.condarc
          conda version : 4.6.1
    conda-build version : 3.0.19
         python version : 2.7.13.final.0
       base environment : D:\Anaconda  (writable)
           channel URLs : https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/win-64
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/noarch
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/win-64
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/win-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : D:\Anaconda\pkgs
                          C:\Users\yoyo\.conda\pkgs
                          C:\Users\yoyo\AppData\Local\conda\conda\pkgs
       envs directories : D:\Anaconda\envs
                          C:\Users\yoyo\.conda\envs
                          C:\Users\yoyo\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.6.1 requests/2.21.0 CPython/2.7.13 Windows/10 Windows/10.0.17763
          administrator : False
             netrc file : None
           offline mode : False
```
```
conda list --show-channel-urls
```
```
# packages in environment at D:\Anaconda:
#
# Name                    Version                   Build  Channel
_ipyw_jlab_nb_ext_conf    0.1.0                    py27_0    defaults
_license                  1.1                      py27_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
aiodns                    1.1.1                    pypi_0    pypi
aiohttp                   3.5.4                    pypi_0    pypi
alabaster                 0.7.10                   py27_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
anaconda                  5.3.1                    py37_0    defaults
anaconda-client           1.6.3                    py27_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
anaconda-navigator        1.8.4                    py27_0    defaults
anaconda-project          0.6.0                    py27_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
aniso8601                 4.1.0                    pypi_0    pypi
appdirs                   1.4.3                    py27_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
apscheduler               3.2.0                    pypi_0    pypi
asn1crypto                0.22.0                   py27_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
astroid                   1.5.3                    py27_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
astropy                   3.0.4            py37hfa6e2cd_0    defaults
async-timeout             3.0.1                    pypi_0    pypi
atomicwrites              1.2.1                    py27_0    defaults
attrs                     15.2.0                   py27_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
automat                   0.5.0                    py27_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
babel                     2.5.0                    py27_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
backcall                  0.1.0                    py27_0    defaults
backports                 1.0                      py27_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
backports.shutil_get_terminal_size 1.0.0                    py27_2    defaults
backports.shutil_which    3.5.2                    py27_0    defaults
backports_abc             0.5                      py27_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
beautifulsoup4            4.6.0                    py27_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
bitarray                  0.8.1                    py27_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
bkcharts                  0.2                      py27_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
blas                      1.0                         mkl    defaults
blaze                     0.11.3                   py37_0    defaults
bleach                    1.5.0                    py27_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
blosc                     1.15.0               hc65f11a_0    defaults
bokeh                     0.12.7                   py27_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
boto                      2.48.0                   py27_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
bottleneck                1.2.1                    pypi_0    pypi
bzip2                     1.0.6                     vc9_3    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
ca-certificates           2018.12.5                     0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
ccxt                      1.18.140                 pypi_0    pypi
certifi                   2018.11.29               pypi_0    pypi
cffi                      1.10.0                   py27_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
chardet                   3.0.4                    py27_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
click                     6.7                      py27_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
cloudpickle               0.4.0                    py27_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
clyent                    1.2.2                    py27_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
colorama                  0.3.9                    py27_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
comtypes                  1.1.2                    py27_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
conda                     4.6.1                    py27_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
conda-build               3.0.19           py27h70da8f8_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
conda-env                 2.6.0                         1    defaults
conda-verify              2.0.0                    py27_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
configparser              3.5.0                    py27_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
console_shortcut          0.1.1                         3    defaults
constantly                15.1.0                   py27_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
contextlib2               0.5.5                    py27_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
cryptography              2.4.2            py27hcfb25f9_0    defaults
curl                      7.52.1                    vc9_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
cycler                    0.10.0                   py27_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
cython                    0.26                     py27_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
cytoolz                   0.8.2                    py27_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
dask                      0.19.1                   py37_0    defaults
dask-core                 1.0.0                    py27_0    defaults
datashape                 0.5.4                    py37_1    defaults
decorator                 4.1.2                    py27_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
defusedxml                0.5.0                    py27_1    defaults
distributed               1.18.1                   py27_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
docutils                  0.14                     py27_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
entrypoints               0.2.3                    py27_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
enum34                    1.1.6                    py27_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
et_xmlfile                1.0.1                    py27_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
fastcache                 1.0.2                    py27_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
filelock                  2.0.7                    py27_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
flask                     0.12                     pypi_0    pypi
flask-cors                3.0.3                    py27_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
flask-restful             0.3.7                    pypi_0    pypi
flask-socketio            3.1.2                    pypi_0    pypi
freetype                  2.5.5                     vc9_2    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
funcsigs                  1.0.2                    pypi_0    pypi
functools32               3.2.3.2                  py27_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
functools_lru_cache       1.4                      py27_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
future                    0.17.1                   pypi_0    pypi
futures                   3.1.1                    py27_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
get_terminal_size         1.0.0                h38e98db_0    defaults
gevent                    1.2.2                    py27_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
gevent-websocket          0.10.1                   pypi_0    pypi
glob2                     0.5                      py27_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
greenlet                  0.4.12                   py27_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
h5py                      2.8.0            py37h3bdd7fb_2    defaults
hdf5                      1.8.17                    vc9_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
heapdict                  1.0.0                    py27_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
html5lib                  0.999                    py27_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
hyperlink                 17.1.1                   py27_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
icc_rt                    2017.0.4             h97af966_0    defaults
icu                       57.1                      vc9_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
idna                      2.6                      py27_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
imageio                   2.4.1                    py37_0    defaults
imagesize                 0.7.1                    py27_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
incremental               16.10.1                  py27_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
intel-openmp              2019.0                      118    defaults
ipaddress                 1.0.18                   py27_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
ipykernel                 4.6.1                    py27_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
ipython                   5.3.0                    py27_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
ipython_genutils          0.2.0                    py27_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
ipywidgets                6.0.0                    py27_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
isort                     4.2.15                   py27_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
itsdangerous              0.24                     py27_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
jdcal                     1.3                      py27_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
jedi                      0.10.2                   py27_2    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
jieba                     0.39                     pypi_0    pypi
jinja2                    2.9.6                    py27_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
jpeg                      8d                        vc9_2    defaults
jsonschema                2.6.0                    py27_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
jupyter                   1.0.0                    py27_3    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
jupyter_client            5.1.0                    py27_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
jupyter_console           5.2.0                    py27_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
jupyter_core              4.3.0                    py27_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
jupyterlab                0.33.11                  py27_0    defaults
jupyterlab_launcher       0.11.2           py27h28b3542_0    defaults
keras                     2.2.4                    pypi_0    pypi
keras-applications        1.0.6                    pypi_0    pypi
keras-preprocessing       1.0.5                    pypi_0    pypi
keyring                   9.3.1                    py27_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
kiwisolver                0.1.3                    py27_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
lazy-object-proxy         1.3.1                    py27_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
libcurl                   7.62.0               h7a46e7a_0    defaults
libiconv                  1.14                      vc9_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
libpng                    1.6.30                    vc9_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
libsodium                 1.0.3                         0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
libssh2                   1.8.0                hcfb25f9_4    defaults
libtiff                   4.0.6                     vc9_2    defaults
libxml2                   2.9.4             vc9h17753f3_5    defaults
libxslt                   1.1.29               hac38ac5_6    defaults
llvmlite                  0.20.0                   py27_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
locket                    0.2.0                    py27_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
lxml                      3.8.0                    py27_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
lzo                       2.10                 h0bb7fe3_2    defaults
m2w64-gcc-libgfortran     5.3.0                         6    defaults
m2w64-gcc-libs            5.3.0                         7    defaults
m2w64-gcc-libs-core       5.3.0                         7    defaults
m2w64-gmp                 6.1.0                         2    defaults
m2w64-libwinpthread-git   5.0.0.4634.697f757               2    defaults
markdown                  3.0.1                    pypi_0    pypi
markupsafe                1.0                      py27_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
matplotlib                3.0.2                    pypi_0    pypi
mccabe                    0.6.1                    pypi_0    pypi
menuinst                  1.4.14           py27h0c8e037_0    defaults
mistune                   0.7.4                    py27_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
mkl                       11.3.3                        1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
mkl-fft                   1.0.4                    pypi_0    pypi
mkl-random                1.0.1                    pypi_0    pypi
mkl-service               1.1.2            py37hb217b18_5    defaults
mkl_fft                   1.0.4            py37h1e22a9b_1    defaults
mkl_random                1.0.1            py37h77b88f5_1    defaults
more-itertools            3.2.0                    py27_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
mpmath                    0.19                     py27_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
msgpack-python            0.5.6                    pypi_0    pypi
msys2-conda-epoch         20160418                      1    defaults
multidict                 4.5.2                    pypi_0    pypi
multipledispatch          0.4.9                    py27_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
navigator-updater         0.2.0                    py27_0    defaults
nbconvert                 5.2.1                    py27_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
nbformat                  4.4.0                    py27_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
networkx                  1.11                     py27_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
nltk                      3.2.4                    py27_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
nose                      1.3.7                    py27_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
notebook                  5.0.0                    py27_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
numba                     0.39.0                   pypi_0    pypi
numexpr                   2.6.8                    pypi_0    pypi
numpy                     1.15.4                   pypi_0    pypi
numpy-base                1.15.1           py37h8128ebf_0    defaults
numpydoc                  0.7.0                    py27_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
odo                       0.5.1                    py37_0    defaults
olefile                   0.44                     py27_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
opencv-python             3.4.5.20                 pypi_0    pypi
openpyxl                  2.4.8                    py27_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
openssl                   1.1.1a               h0c8e037_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
packaging                 16.8                     py27_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
pandas                    0.23.4           py37h830ac7b_0    defaults
pandoc                    1.19.2.1             hb2460c7_1    defaults
pandocfilters             1.4.2                    py27_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
parso                     0.3.1                    py27_0    defaults
partd                     0.3.8                    py27_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
path.py                   10.3.1                   py27_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
pathlib2                  2.3.0                    py27_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
patsy                     0.5.0                    py37_0    defaults
pep8                      1.7.0                    py27_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
pickleshare               0.7.4                    py27_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
pillow                    4.0.0                    pypi_0    pypi
pip                       18.1                     pypi_0    pypi
pkginfo                   1.4.1                    py27_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
pluggy                    0.8.1                    py27_0    defaults
ply                       3.10                     py27_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
prometheus_client         0.5.0                    py27_0    defaults
prompt_toolkit            1.0.15                   py27_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
psutil                    5.2.2                    py27_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
py                        1.4.34                   py27_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
pyasn1                    0.2.3                    py27_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
pyasn1-modules            0.0.8                    py27_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
pycares                   2.4.0                    pypi_0    pypi
pycodestyle               2.3.1                    py27_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
pycosat                   0.6.3            py27h0c8e037_0    defaults
pycparser                 2.18                     py27_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
pycrypto                  2.6.1                    py27_6    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
pycurl                    7.43.0                   py27_2    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
pydotplus                 2.0.2                    pypi_0    pypi
pyflakes                  1.6.0                    py27_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
pygments                  2.2.0                    py27_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
pylint                    1.7.2                    py27_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
pymongo                   3.7.2                    pypi_0    pypi
pyodbc                    4.0.17                   py27_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
pyopenssl                 17.0.0                   py27_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
pyparsing                 2.2.0                    py27_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
pyqt                      4.11.4                   py27_7    defaults
pyqtgraph                 0.10.0                   pypi_0    pypi
pysocks                   1.6.6                    py27_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
pytables                  3.4.4            py37he6f6034_0    defaults
pytest                    3.2.1                    py27_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
pytest-arraydiff          0.2              py37h39e3cac_0    defaults
pytest-astropy            0.4.0                    py37_0    defaults
pytest-doctestplus        0.1.3                    py37_0    defaults
pytest-openfiles          0.3.2                    py27_0    defaults
pytest-remotedata         0.3.1                    py27_0    defaults
python                    2.7.13                        1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
python-dateutil           2.6.1                    py27_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
python-engineio           3.2.3                    pypi_0    pypi
python-socketio           3.1.1                    pypi_0    pypi
pytz                      2017.2                   py27_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
pywavelets                1.0.0                    pypi_0    pypi
pywin32                   220                      py27_2    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
pywinpty                  0.5.5                 py27_1000    defaults
pyyaml                    3.12                     py27_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
pyzmq                     16.0.2                   py27_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
qdarkstyle                2.6.5                    pypi_0    pypi
qt                        4.8.7                     vc9_6    defaults
qtawesome                 0.4.4                    py27_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
qtconsole                 4.4.3                    py27_0    defaults
qtpy                      1.3.1                    py27_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
requests                  2.20.0                   pypi_0    pypi
rope                      0.9.4                    py27_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
ruamel_yaml               0.11.14                  py27_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
scandir                   1.5                      py27_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
scikit-image              0.14.0           py37h6538335_1    defaults
scikit-learn              0.20.2                   pypi_0    pypi
scipy                     1.2.0                    pypi_0    pypi
seaborn                   0.9.0                    py37_0    defaults
selenium                  3.3.0                    pypi_0    pypi
send2trash                1.5.0                    py27_0    defaults
service_identity          17.0.0                   py27_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
setuptools                36.4.0                   py27_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
simplegeneric             0.8.1                    py27_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
singledispatch            3.4.0.3                  py27_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
sip                       4.18                     py27_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
six                       1.10.0                   py27_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
smartypants               2.0.1                    pypi_0    pypi
snappy                    1.1.7                he46498f_3    defaults
snowballstemmer           1.2.1                    py27_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
sortedcollections         0.5.3                    py27_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
sortedcontainers          1.4.4                    py27_0    quantopian
sphinx                    1.6.3                    pypi_0    pypi
sphinxcontrib             1.0                      py27_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
sphinxcontrib-websupport  1.0.1                    py27_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
spyder                    3.2.3                    py27_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
spyder-kernels            1.0.1                    py27_0    defaults
sqlalchemy                1.1.13                   py27_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
sqlite                    3.13.0                    vc9_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
ssl_match_hostname        3.5.0.1                  py27_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
statsmodels               0.9.0            py37h452e1ab_0    defaults
subprocess32              3.2.7                    py27_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
sympy                     1.1.1                    py27_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
ta-lib                    0.4.9               np110py27_0    quantopian
tblib                     1.3.2                    py27_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
terminado                 0.8.1                    py27_1    defaults
testpath                  0.3.1                    py27_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
tk                        8.5.18                    vc9_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
toolz                     0.8.2                    py27_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
tornado                   4.5.2                    py27_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
tqdm                      4.15.0                   py27_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
traitlets                 4.3.2                    py27_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
twisted                   17.5.0                   py27_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
typing                    3.6.2                    py27_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
tzlocal                   1.5.1                    pypi_0    pypi
unicodecsv                0.14.1                   py27_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
urllib3                   1.21.1                   py27_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
vc                        9                             0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
vnpy                      1.9.2                    pypi_0    pypi
vs2008_runtime            9.00.30729.5054               0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
vs2015_runtime            14.15.26706          h3a45250_0    defaults
wcwidth                   0.1.7                    py27_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
webencodings              0.5.1                    py27_1    defaults
websocket-client          0.54.0                   pypi_0    pypi
werkzeug                  0.11.15                  pypi_0    pypi
wheel                     0.29.0                   py27_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
widgetsnbextension        3.0.2                    py27_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
win_inet_pton             1.0.1                    py27_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
win_unicode_console       0.5                      py27_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
wincertstore              0.2                      py27_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
winpty                    0.4.3                         4    defaults
wmi                       1.4.9                    pypi_0    pypi
wrapt                     1.10.11                  py27_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
xlrd                      1.1.0                    py27_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
xlsxwriter                0.9.8                    py27_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
xlwings                   0.11.4                   py27_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
xlwt                      1.3.0                    py27_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
yaml                      0.1.6                         0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
yarl                      1.1.0                    pypi_0    pypi
zeromq                    4.1.3                     vc9_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
zict                      0.1.2                    py27_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
zlib                      1.2.11                    vc9_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
zope                      1.0                      py27_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
zope.interface            4.4.2                    py27_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
```

**Comment by yoyo-sincerely** [comment]
I solved this problem by add ";" to the path. ^_^

**Comment by qchengray** [comment]
> I solved this problem by adding ";" to the path. ^_^

Can you make the solution clear? which path did you added “；” to，I had suffered the same problem and try many update command but not solved.
