### ISSUE TITLE
Nothing works anymore, jupyter, conda, spyder, etc.

### ISSUE THREAD

**Issue by JohnHBoisvert** [ContinuumIO/anaconda-issues#10630]
### Actual Behavior

Nothing happens.  Its as if the anaconda installation uninstalled itself.

### Expected Behavior

I expected jupyter notebook and spyder to launch like its always done.

### Steps to Reproduce

When I tried to launch the Launcher, it prompted me here and told me to provide: Error: spawn ENOENT
    at exports._errnoException (util.js:742:11)
    at Process.ChildProcess._handle.onexit (child_process.js:1027:32)
    at child_process.js:1110:20
    at process._tickCallback (node.js:279:11)

##### Anaconda or Miniconda version:
The continuum analytics verison.

##### Operating System:
Mac OS Mojave (the latest)

##### `conda info`

```
-bash: conda: command not found
```

##### `conda list --show-channel-urls`

```
-bash: conda: command not found
```

**Comment by sprague252** [comment]
I just reported a similar issue.

https://github.com/ContinuumIO/anaconda-issues/issues/10712
