### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by ishareef7** [ContinuumIO/anaconda-issues#10644]
## Main error
Application <b>spyder</b> launch may have produced errors.
## Traceback
```
Traceback (most recent call last):
  File "/Users/ishareef7/anaconda/bin/spyder", line 6, in <module>
    sys.exit(spyder.app.start.main())
  File "/Users/ishareef7/anaconda/lib/python2.7/site-packages/spyder/app/start.py", line 103, in main
    from spyder.app import mainwindow
  File "/Users/ishareef7/anaconda/lib/python2.7/site-packages/spyder/app/mainwindow.py", line 92, in <module>
    from qtpy import QtWebEngineWidgets  # analysis:ignore
  File "/Users/ishareef7/anaconda/lib/python2.7/site-packages/qtpy/QtWebEngineWidgets.py", line 26, in <module>
    from PyQt5.QtWebKitWidgets import QWebPage as QWebEnginePage
ImportError: No module named QtWebKitWidgets

```
## System information
```
platform: osx-64
version: 1.6.2
conda: 4.3.21
qt: 5.6.2
language: en
python: 2.7.13
os: Darwin;18.2.0;Darwin Kernel Version 18.2.0: Fri Oct  5 19:41:49 PDT 2018; root:xnu-4903.221.2~2/RELEASE_X86_64;x86_64;i386
pyqt: 5.6.0
```

**Comment by goanpeca** [comment]
Please remember to update to the latest version of Navigator to include
the latest fixes.

Open a terminal (on Linux or Mac) or the Anaconda Command Prompt (on windows)
and type:

```
conda update conda
conda update --all
```
