### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by tsorenso** [ContinuumIO/anaconda-issues#10661]
## Main error
Application <b>spyder</b> launch may have produced errors.
## Traceback
```
Traceback (most recent call last):
  File "/Users/taylorsorenson/anaconda/envs/ssca/bin/spyder", line 11, in <module>
    sys.exit(main())
  File "/Users/taylorsorenson/anaconda/envs/ssca/lib/python2.7/site-packages/spyder/app/start.py", line 186, in main
    from spyder.app import mainwindow
  File "/Users/taylorsorenson/anaconda/envs/ssca/lib/python2.7/site-packages/spyder/app/mainwindow.py", line 90, in <module>
    from qtpy import QtWebEngineWidgets  # analysis:ignore
  File "/Users/taylorsorenson/anaconda/envs/ssca/lib/python2.7/site-packages/qtpy/QtWebEngineWidgets.py", line 26, in <module>
    from PyQt5.QtWebKitWidgets import QWebPage as QWebEnginePage
ImportError: No module named QtWebKitWidgets

```
## System information
```
platform: osx-64
version: 1.6.2
conda: 4.6.4
qt: 5.6.2
language: en
python: 2.7.13
os: Darwin;18.2.0;Darwin Kernel Version 18.2.0: Mon Nov 12 20:24:46 PST 2018; root:xnu-4903.231.4~2/RELEASE_X86_64;x86_64;i386
pyqt: 5.6.0
```

**Comment by tsorenso** [comment]
I'm also not able to Launch spyder in anaconda, for some unknown reason.
