### ISSUE TITLE
Anaconda crashes with Win 10's beta Unicode UTF-8 support

### ISSUE THREAD

**Issue by Aster-the-Med-Stu** [ContinuumIO/anaconda-issues#10662]
### Actual Behavior

Anaconda crashes

### Expected Behavior

Anaconda prompt runs correctly with Win 10 Beta Unicode UTF-8 support

### Steps to Reproduce
- Open Region & language settings (press WinKey and type: region)
- In Related settings section click Administrative language settings
- On the Administrative tab click Change system locale...
- Be sure to **check** Beta: Use Unicode UTF-8 for worldwide language support

### Possible Reason
Anaconda's init script failed to recoginze CP65001 as UTF-8

##### Anaconda or Miniconda version:
Anaconda 5.3.1

##### Operating System:

Win 10 Pro 64 Bit (Simplified Chinese)

##### Traceback
```
    Traceback (most recent call last):
      File "D:\Anaconda3\lib\site-packages\conda\cli\main.py", line 105, in main
        return activator_main()
      File "D:\Anaconda3\lib\site-packages\conda\activate.py", line 838, in main
        print(activator.execute(), end='')
      File "D:\Anaconda3\lib\site-packages\conda\activate.py", line 110, in execute
        return getattr(self, self.command)()
      File "D:\Anaconda3\lib\site-packages\conda\activate.py", line 88, in activate
        return self._finalize(self._yield_commands(builder_result), self.tempfile_extension)
      File "D:\Anaconda3\lib\site-packages\conda\activate.py", line 78, in _finalize
        tf.write(ensure_binary(self.command_join.join(commands)))
      File "D:\Anaconda3\lib\site-packages\conda\activate.py", line 536, in ensure_binary
        return value.encode(encoding)
    LookupError: unknown encoding: 65001
```

##### `conda info`

```
     active environment : None
       user config file : C:\Users\[redacted]\.condarc
 populated config files : C:\Users\[redacted]\.condarc
          conda version : 4.6.6
    conda-build version : 3.17.8
         python version : 3.6.8.final.0
       base environment : D:\Anaconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/win-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : D:\Anaconda3\pkgs
                          C:\Users\[redacted]\.conda\pkgs
                          C:\Users\[redacted]\AppData\Local\conda\conda\pkgs
       envs directories : D:\Anaconda3\envs
                          C:\Users\[redacted]\.conda\envs
                          C:\Users\[redacted]\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.6.6 requests/2.21.0 CPython/3.6.8 Windows/10 Windows/10.0.17763
          administrator : False
             netrc file : None
           offline mode : False
```

**Comment by Aster-the-Med-Stu** [comment]
Duplicate of #5448
