### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by shijiale0609** [ContinuumIO/anaconda-issues#10663]
## Main error
Application <b>spyder</b> launch may have produced errors.
## Traceback
```
Traceback (most recent call last):
  File "/Users/shijiale1995/anaconda/bin/spyder", line 7, in <module>
    from spyder.app.start import main
  File "/Users/shijiale1995/anaconda/lib/python3.6/site-packages/spyder/app/start.py", line 35, in <module>
    from spyder.config.main import CONF
  File "/Users/shijiale1995/anaconda/lib/python3.6/site-packages/spyder/config/main.py", line 22, in <module>
    from spyder.config.user import UserConfig
  File "/Users/shijiale1995/anaconda/lib/python3.6/site-packages/spyder/config/user.py", line 26, in <module>
    from spyder.utils.programs import check_version
  File "/Users/shijiale1995/anaconda/lib/python3.6/site-packages/spyder/utils/programs.py", line 18, in <module>
    import subprocess
  File "/Users/shijiale1995/anaconda/lib/python3.6/subprocess.py", line 136, in <module>
    import _posixsubprocess
ImportError: dlopen(/Users/shijiale1995/anaconda/lib/python3.6/lib-dynload/_posixsubprocess.cpython-36m-darwin.so, 2): Symbol not found: __Py_set_inheritable_async_safe
  Referenced from: /Users/shijiale1995/anaconda/lib/python3.6/lib-dynload/_posixsubprocess.cpython-36m-darwin.so
  Expected in: flat namespace
 in /Users/shijiale1995/anaconda/lib/python3.6/lib-dynload/_posixsubprocess.cpython-36m-darwin.so

```
## System information
```
python: 3.6.8
language: en
os: Darwin;17.7.0;Darwin Kernel Version 17.7.0: Thu Jun 21 22:53:14 PDT 2018; root:xnu-4570.71.2~1/RELEASE_X86_64;x86_64;i386
version: 1.6.2
platform: osx-64
qt: 5.9.6
pyqt: 5.9.2
conda: 4.6.4
```

**Comment by goanpeca** [comment]
Please remember to update to the latest version of Navigator to include
the latest fixes.

Open a terminal (on Linux or Mac) or the Anaconda Command Prompt (on windows)
and type:

```
conda update conda
conda update --all
```
