### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by DongkyuSim** [ContinuumIO/anaconda-issues#10664]
### Actual Behavior
Anaconda navigator could not open after installation and re-installation with re-booting also.  It only showed following messages:
_______________________________________________________________________________________________________________
**Navigator Error**

An unexpected error occurred on Navigator start-up

**Report**

Please report this issue in the anaconda  issue tracker  

**Main Error**

expected str, bytes or os.PathLike object, not NoneType

**Traceback**

Traceback (most recent call last):
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\anaconda_navigator\exceptions.py", line 75, in exception_handler
    return_value = func(*args, **kwargs)
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 151, in start_app
    window = run_app(splash)
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 65, in run_app
    window = MainWindow(splash=splash, tab_project=False)
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\anaconda_navigator\widgets\main_window.py", line 168, in __init__
    self.api = AnacondaAPI()
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 2337, in AnacondaAPI
    ANACONDA_API = _AnacondaAPI()
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 89, in __init__
    self._conda_api = CondaAPI()
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 1767, in CondaAPI
    CONDA_API = _CondaAPI()
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 353, in __init__
    self.sys_rc_path = join(self.ROOT_PREFIX, '.condarc')
  File "C:\Users\Administrator\Anaconda3\lib\ntpath.py", line 76, in join
    path = os.fspath(path)
TypeError: expected str, bytes or os.PathLike object, not NoneType
_______________________________________________________________________________________________________________

Moreover, when I opened Anaconda Prompt, there is a message as follows:

"The filename, directory name, or volume label syntax is incorrect."

I tried to delete .condarc file, but I can't find that file.

### Expected Behavior
Anaconda navigator should open after installing

**Comment by goanpeca** [comment]
Please update with the information requested on the issue template



### Actual Behavior



### Expected Behavior



### Steps to Reproduce




##### Anaconda or Miniconda version:

##### Operating System:

##### `conda info`

```

```

##### `conda list --show-channel-urls`

```

```

**Comment by DongkyuSim** [comment]
> Please update with the information requested on the issue template
> 
> ### Actual Behavior
> ### Expected Behavior
> ### Steps to Reproduce
> ##### Anaconda or Miniconda version:
> ##### Operating System:
> ##### `conda info`
> ```
> 
> ```
> ##### `conda list --show-channel-urls`
> ```
> 
> ```

I updated with the information requested on the issue template.

Please answer me.

**Comment by goanpeca** [comment]
@DongkyuSim you did not provide the information. Please do.

**Comment by csoja** [comment]
Some people have been able to "fix" similar issues by removing their .condarc file, so you may want to back it up, and try that.
