### ISSUE TITLE
libstdc++.so.6: version `GLIBCXX_3.4.21' not found

### ISSUE THREAD

**Issue by tranhoangcore** [ContinuumIO/anaconda-issues#10686]
<details>

```
(my_env) jupyterlab@b6d961f3a341:/resources/Demo/STDN$ python main.py --stdn
Traceback (most recent call last):
  File "/home/jupyterlab/anaconda3/envs/my_env/lib/python3.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/home/jupyterlab/anaconda3/envs/my_env/lib/python3.7/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/home/jupyterlab/anaconda3/envs/my_env/lib/python3.7/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/home/jupyterlab/anaconda3/envs/my_env/lib/python3.7/imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "/home/jupyterlab/anaconda3/envs/my_env/lib/python3.7/imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /home/jupyterlab/anaconda3/envs/my_env/lib/python3.7/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 1, in <module>
    import models
  File "/resources/Demo/STDN/models.py", line 4, in <module>
    import tensorflow as tf
  File "/home/jupyterlab/anaconda3/envs/my_env/lib/python3.7/site-packages/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "/home/jupyterlab/anaconda3/envs/my_env/lib/python3.7/site-packages/tensorflow/python/__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/home/jupyterlab/anaconda3/envs/my_env/lib/python3.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/home/jupyterlab/anaconda3/envs/my_env/lib/python3.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/home/jupyterlab/anaconda3/envs/my_env/lib/python3.7/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/home/jupyterlab/anaconda3/envs/my_env/lib/python3.7/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/home/jupyterlab/anaconda3/envs/my_env/lib/python3.7/imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "/home/jupyterlab/anaconda3/envs/my_env/lib/python3.7/imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /home/jupyterlab/anaconda3/envs/my_env/lib/python3.7/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so)


Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.

```

</details>

##### `conda info`

<details>

```
active environment : my_env
    active env location : /home/jupyterlab/anaconda3/envs/my_env
            shell level : 2
       user config file : /home/jupyterlab/.condarc
 populated config files :
          conda version : 4.5.12
    conda-build version : 3.17.6
         python version : 3.7.1.final.0
       base environment : /home/jupyterlab/anaconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/linux-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/linux-64
                          https://repo.anaconda.com/pkgs/pro/noarch
          package cache : /home/jupyterlab/anaconda3/pkgs
                          /home/jupyterlab/.conda/pkgs
       envs directories : /home/jupyterlab/anaconda3/envs
                          /home/jupyterlab/.conda/envs
               platform : linux-64
             user-agent : conda/4.5.12 requests/2.21.0 CPython/3.7.1 Linux/4.4.0-135-generic debian/8 glibc/2.19
                UID:GID : 1000:2000
             netrc file : None
           offline mode : False

```

</details>

##### `conda list --show-channel-urls`

<details>

```
# Name                    Version                   Build  Channel
absl-py                   0.7.0                     <pip>
astor                     0.7.1                     <pip>
ca-certificates           2019.1.23                     0    defaults
certifi                   2018.11.29               py37_0    defaults
cloog                     0.18.1                        1    serge-sans-paille
gast                      0.2.2                     <pip>
gcc_49                    4.9.1                         6    serge-sans-paille
gmp                       5.1.3                         0    serge-sans-paille
grpcio                    1.19.0                    <pip>
h5py                      2.9.0                     <pip>
isl                       0.12.2                        0    defaults
Keras-Applications        1.0.7                     <pip>
Keras-Preprocessing       1.0.9                     <pip>
libedit                   3.1.20181209         hc058e9b_0    defaults
libffi                    3.2.1                hd88cf55_4    defaults
libgcc                    7.2.0                h69d50b8_2    defaults
libgcc-ng                 8.2.0                hdf63c60_1    defaults
libstdcxx-ng              8.2.0                hdf63c60_1    defaults
Markdown                  3.0.1                     <pip>
mock                      2.0.0                     <pip>
mpc                       1.0.3                hf803216_4    defaults
mpfr                      3.1.5                h12ff648_1    defaults
ncurses                   6.1                  he6710b0_1    defaults
numpy                     1.16.2                    <pip>
openssl                   1.1.1b               h7b6447c_0    defaults
pbr                       5.1.2                     <pip>
pip                       19.0.3                   py37_0    defaults
protobuf                  3.6.1                     <pip>
python                    3.7.2                h0371630_0    defaults
readline                  7.0                  h7b6447c_5    defaults
setuptools                40.8.0                   py37_0    defaults
six                       1.12.0                    <pip>
sqlite                    3.26.0               h7b6447c_0    defaults
tensorboard               1.13.0                    <pip>
tensorflow                1.13.1                    <pip>
tensorflow-estimator      1.13.0                    <pip>
termcolor                 1.1.0                     <pip>
tk                        8.6.8                hbc83047_0    defaults
Werkzeug                  0.14.1                    <pip>
wheel                     0.33.1                   py37_0    defaults
xz                        5.2.4                h14c3975_4    defaults
zlib                      1.2.11               h7b6447c_3    defaults

```

</details>

**Comment by msarahan** [comment]
You've installed tensorflow from pip.  You need to ask them for support on their issue tracker.
