### ISSUE TITLE
Spyder: launching error 

### ISSUE THREAD

**Issue by beastgit** [ContinuumIO/anaconda-issues#10704]
Hello, 
I recently updated my Anaconda Python libraries and packages. since then I am unable to launch Spyder. I get the following error message upon attempting to launch

objc[2730]: Class RunLoopModeTracker is implemented in both /anaconda3/lib/python3.7/site-packages/PyQt5/Qt/lib/QtCore.framework/Versions/5/QtCore (0xb1957d270) and /anaconda3/lib/libQt5Core.5.dylib (0xb20d67a80). One of the two will be used. Which one is undefined.
Traceback (most recent call last):
File "/anaconda3/bin/spyder", line 11, in 
sys.exit(main())
File "/anaconda3/lib/python3.7/site-packages/spyder/app/start.py", line 186, in main
from spyder.app import mainwindow
File "/anaconda3/lib/python3.7/site-packages/spyder/app/mainwindow.py", line 90, in 
from qtpy import QtWebEngineWidgets # analysis:ignore
File "/anaconda3/lib/python3.7/site-packages/qtpy/QtWebEngineWidgets.py", line 22, in 
from PyQt5.QtWebEngineWidgets import QWebEnginePage
ValueError: PyCapsule_GetPointer called with incorrect name

**Comment by ccordoba12** [comment]
> objc[2730]: Class RunLoopModeTracker is implemented in both /anaconda3/lib/python3.7/site-packages/PyQt5/Qt/lib/QtCore.framework/Versions/5/QtCore (0xb1957d270) and /anaconda3/lib/libQt5Core.5.dylib (0xb20d67a80). One of the two will be used. Which one is undefined.

This error means that you installed `pyqt5` with pip along side the `pyqt` conda package. It could be solved by you uninstalling the pip package, but if not, then you'd need to reinstall Anaconda because you broke your current installation.

**Comment by Zoe2020** [comment]
objc[10589]: Class RunLoopModeTracker is implemented in both /Users/zohrehsouri/anaconda3/lib/python3.6/site-packages/PyQt5/Qt/lib/QtCore.framework/Versions/5/QtCore (0x110be5270) and /Users/zohrehsouri/anaconda3/lib/libQt5Core.5.dylib (0x18188868b8). One of the two will be used. Which one is undefined.
Traceback (most recent call last):
File "/Users/zohrehsouri/anaconda3/bin/spyder", line 11, in 
sys.exit(main())
File "/Users/zohrehsouri/anaconda3/lib/python3.6/site-packages/spyder/app/start.py", line 186, in main
from spyder.app import mainwindow
File "/Users/zohrehsouri/anaconda3/lib/python3.6/site-packages/spyder/app/mainwindow.py", line 90, in 
from qtpy import QtWebEngineWidgets # analysis:ignore
File "/Users/zohrehsouri/anaconda3/lib/python3.6/site-packages/qtpy/QtWebEngineWidgets.py", line 22, in 
from PyQt5.QtWebEngineWidgets import QWebEnginePage
ValueError: PyCapsule_GetPointer called with incorrect name

**Comment by ccordoba12** [comment]
@Zoe2020, you broke your Anaconda installation by running at some point `pip install pyqt5` or using pip to install another package that brought `pyqt5` as a dependency.

Now you have to remove and reinstall Anaconda.

**Comment by GuruComposer** [comment]
I reinstalled Anaconda, and I still have the same problem.

**Comment by GuruComposer** [comment]
How do I uninstall the pip package, and what is pip?

**Comment by ccordoba12** [comment]
@GuruComposer, please remove Anaconda again, but before reinstalling. please remove the directory where you installed Anaconda. That could help.

**Comment by GuruComposer** [comment]
Hi @ccordoba12, Thank you very much, I think I got it all working

**Comment by haseeb33** [comment]
I removed the pyqt5 by `pip uninstall pyqt5` and both anaconda navigator and spyder are working. 

P.S: it removed the framework from `anaconda/bin` but didn't delete pyqt5 from libraries of anaconda `anaconda/lib`

**Comment by sisika09** [comment]
@ccordoba12 I after installing tried opening anaconda navigator, but it didn't open neither did jupyter or spyder. Then after some googling, I did this.
`conda update conda
conda update --all`
`conda remove QtPy PyQt5
pip install QtPy PyQt5`
so now anaconda and jupyter work, but I still can't launch spyder.

It is showing this error

Traceback (most recent call last):
File "C:\anaconda\lib\site-packages\qtpy\QtWebEngineWidgets.py", line 22, in 
from PyQt5.QtWebEngineWidgets import QWebEnginePage
ImportError: DLL load failed while importing QtWebEngineWidgets: The specified procedure could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "C:\anaconda\Scripts\spyder-script.py", line 10, in 
sys.exit(main())
File "C:\anaconda\lib\site-packages\spyder\app\start.py", line 201, in main
from spyder.app import mainwindow
File "C:\anaconda\lib\site-packages\spyder\app\mainwindow.py", line 84, in 
from qtpy import QtWebEngineWidgets # analysis:ignore
File "C:\anaconda\lib\site-packages\qtpy\QtWebEngineWidgets.py", line 26, in 
from PyQt5.QtWebKitWidgets import QWebPage as QWebEnginePage
ModuleNotFoundError: No module named 'PyQt5.QtWebKitWidgets'


please help.

**Comment by maihao14** [comment]
Did anyone fix this problem? After google quite a long time, I still cannot fix it.

**Comment by kiarasharnk** [comment]
> Did anyone fix this problem? After google quite a long time, I still cannot fix it.

I got the same error, so I deleted the anaconda folder and reinstalled it again. It solved the problem!

**Comment by Shashi-phy** [comment]
I removed the pyqt5 by pip uninstall pyqt5 and it solved the problem.

**Comment by bevi-rosso** [comment]
With a Mac, it is alternatively possible to retrieve the backup of the Anaconda dir from Time Machine and restore before the problem. It works!

**Comment by farkhod-chelsea** [comment]
I installed fresh windows and everything again, but got same error as before. How to fix this error...? Thanks in advance

(tfcpu39) C:\Users\abdul>spyder
fromIccProfile: failed minimal tag size sanity
Traceback (most recent call last):
  File "C:\Users\abdul\anaconda3\envs\tfcpu39\lib\asyncio\windows_events.py", line 434, in select
    self._poll(timeout)
RuntimeError: <_overlapped.Overlapped object at 0x000001AA805D6540> still has pending operation at deallocation, the process may crash
Traceback (most recent call last):
  File "C:\Users\abdul\anaconda3\envs\tfcpu39\lib\asyncio\windows_events.py", line 434, in select
    self._poll(timeout)
RuntimeError: <_overlapped.Overlapped object at 0x000001AA8062B300> still has pending operation at deallocation, the process may crash

**Comment by farkhod-chelsea** [comment]
> I installed fresh windows and everything again, but got same error as before. How to fix this error...? Thanks in advance
> 
> (tfcpu39) C:\Users\abdul>spyder fromIccProfile: failed minimal tag size sanity Traceback (most recent call last): File "C:\Users\abdul\anaconda3\envs\tfcpu39\lib\asyncio\windows_events.py", line 434, in select self._poll(timeout) RuntimeError: <_overlapped.Overlapped object at 0x000001AA805D6540> still has pending operation at deallocation, the process may crash Traceback (most recent call last): File "C:\Users\abdul\anaconda3\envs\tfcpu39\lib\asyncio\windows_events.py", line 434, in select self._poll(timeout) RuntimeError: <_overlapped.Overlapped object at 0x000001AA8062B300> still has pending operation at deallocation, the process may crash

Previously, 2 time crushed while I was running many codes due to sudden off electricity. This time fresh windows and got same error. Actually, there is no pending operation
