### ISSUE TITLE
An unexpected error occurred on Navigator start-up

### ISSUE THREAD

**Issue by changhaizi** [ContinuumIO/anaconda-issues#10703]
**This appears after I try to open the Anaconda Command Prompt:**

 ERROR REPORT

    Traceback (most recent call last):
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\cli\main.py", line 97, in main
        from ..activate import main as activator_main
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\activate.py", line 15, in <module>
        context.__init__()  # oOn import, context does not include SEARCH_PATH. This line fixes that.
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\base\context.py", line 239, in __init__
        argparse_args=argparse_args)
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\common\configuration.py", line 722, in __init__
        self._set_search_path(search_path)
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\common\configuration.py", line 728, in _set_search_path
        self._set_raw_data(load_file_configs(search_path))
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\common\configuration.py", line 369, in load_file_configs
        raw_data = odict(kv for kv in chain.from_iterable(load_paths))
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\common\configuration.py", line 369, in <genexpr>
        raw_data = odict(kv for kv in chain.from_iterable(load_paths))
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\common\configuration.py", line 344, in _file_yaml_loader
        yield fullpath, YamlRawParameter.make_raw_parameters_from_file(fullpath)
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\common\configuration.py", line 332, in make_raw_parameters_from_file
        ruamel_yaml = yaml_load(fh)
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\common\serialize.py", line 54, in yaml_load
        return yaml.load(string, Loader=yaml.RoundTripLoader, version="1.2")
      File "C:\ProgramData\Anaconda3\lib\site-packages\ruamel_yaml\main.py", line 638, in load
        loader = Loader(stream, version, preserve_quotes=preserve_quotes)
      File "C:\ProgramData\Anaconda3\lib\site-packages\ruamel_yaml\loader.py", line 59, in __init__
        Reader.__init__(self, stream, loader=self)
      File "C:\ProgramData\Anaconda3\lib\site-packages\ruamel_yaml\reader.py", line 80, in __init__
        self.stream = stream  # type: Any  # as .read is called
      File "C:\ProgramData\Anaconda3\lib\site-packages\ruamel_yaml\reader.py", line 125, in stream
        self.determine_encoding()
      File "C:\ProgramData\Anaconda3\lib\site-packages\ruamel_yaml\reader.py", line 180, in determine_encoding
        self.update(1)
      File "C:\ProgramData\Anaconda3\lib\site-packages\ruamel_yaml\reader.py", line 266, in update
        self.check_printable(data)
      File "C:\ProgramData\Anaconda3\lib\site-packages\ruamel_yaml\reader.py", line 233, in check_printable
        'unicode', "special characters are not allowed")
    ruamel_yaml.reader.ReaderError: unacceptable character #x0000: special characters are not allowed
      in "C:\Users\Administrator\.condarc", position 0

`$ C:\ProgramData\Anaconda3\Scripts\conda shell.cmd.exe activate activate C:\ProgramData\Anaconda3`

  environment variables:
                 CIO_TEST=<not set>
               CONDA_ROOT=C:\ProgramData\Anaconda3
                CUDA_PATH=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.0
                 HOMEPATH=\Users\Administrator
          NVTOOLSEXT_PATH=C:\Program Files\NVIDIA Corporation\NvToolsExt\
                     PATH=C:\ProgramData\Anaconda3;C:\ProgramData\Anaconda3\Library\mingw-w64\bi
                          n;C:\ProgramData\Anaconda3\Library\usr\bin;C:\ProgramData\Anaconda3\Li
                          brary\bin;C:\ProgramData\Anaconda3\Scripts;C:\Program
                          Files\python37\Scripts\;C:\Program Files\python37\;C:\Program
                          Files\NVIDIA GPU Computing Toolkit\CUDA\v10.0\bin;C:\Program
                          Files\NVIDIA GPU Computing Toolkit\CUDA\v10.0\libnvvp;C:\Program
                          Files\Python36\Scripts\;C:\Program Files\Python36\;C:\Windows\system32
                          ;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerS
                          hell\v1.0\;C:\Program Files\NVIDIA Corporation\NVIDIA NGX;C:\Program
                          Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\NVIDIA
                          Corporation\NVIDIA NvDLISR;C:\Program Files\dotnet\;C:\Program
                          Files\Microsoft SQL Server\130\Tools\Binn\;C:\Strawberry\c\bin;C:\Stra
                          wberry\perl\site\bin;C:\Strawberry\perl\bin;C:\Program Files\GDAL;%Sys
                          temRoot%\system32;%SystemRoot%;%SystemRoot%\System32\Wbem;%SYSTEMROOT%
                          \System32\WindowsPowerShell\v1.0\;%SYSTEMROOT%\System32\OpenSSH\;C:\Us
                          ers\Administrator\AppData\Local\Microsoft\WindowsApps;;C:\Users\Admini
                          strator\AppData\Local\Programs\Microsoft VS Code\bin
             PSMODULEPATH=C:\Program Files\WindowsPowerShell\Modules;C:\WINDOWS\system32\Windows
                          PowerShell\v1.0\Modules
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>

     active environment : None
       user config file : C:\Users\Administrator\.condarc
 populated config files :
          conda version : 4.5.12
    conda-build version : 3.17.6
         python version : 3.7.1.final.0
       base environment : C:\ProgramData\Anaconda3  (read only)
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/win-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/win-64
                          https://repo.anaconda.com/pkgs/pro/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\ProgramData\Anaconda3\pkgs
                          C:\Users\Administrator\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\Administrator\AppData\Local\conda\conda\envs
                          C:\ProgramData\Anaconda3\envs
                          C:\Users\Administrator\.conda\envs
               platform : win-64
             user-agent : conda/4.5.12 requests/2.21.0 CPython/3.7.1 Windows/10 Windows/10.0.17134
          administrator : False
             netrc file : None
           offline mode : False

An unexpected error has occurred. Conda has prepared the above report.
If submitted, this report will be used by core maintainers to improve
future releases of conda.
Would you like conda to send this report to the core maintainers?
[y/N]: y
Upload successful.

**# And this appears after I try to open the Navigator:**

Navigator Error
An unexpected error occurred on Navigator start-up

Report
Please report this issue in the anaconda issue tracker

Main Error
expected str, bytes or os.PathLike object, not NoneType
Traceback
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\anaconda_navigator\exceptions.py", line 75, in exception_handler
    return_value = func(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 151, in start_app
    window = run_app(splash)
  File "C:\ProgramData\Anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 65, in run_app
    window = MainWindow(splash=splash, tab_project=False)
  File "C:\ProgramData\Anaconda3\lib\site-packages\anaconda_navigator\widgets\main_window.py", line 168, in __init__
    self.api = AnacondaAPI()
  File "C:\ProgramData\Anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 2337, in AnacondaAPI
    ANACONDA_API = _AnacondaAPI()
  File "C:\ProgramData\Anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 89, in __init__
    self._conda_api = CondaAPI()
  File "C:\ProgramData\Anaconda3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 1767, in CondaAPI
    CONDA_API = _CondaAPI()
  File "C:\ProgramData\Anaconda3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 353, in __init__
    self.sys_rc_path = join(self.ROOT_PREFIX, '.condarc')
  File "C:\ProgramData\Anaconda3\lib\ntpath.py", line 76, in join
    path = os.fspath(path)
TypeError: expected str, bytes or os.PathLike object, not NoneType

**Comment by Shvana** [comment]
I also have the same error when I update Anaconda and I have not been able to solve it. I would like some help

 Traceback (most recent call last):
      File "C:\Users\Shvana\Anaconda3\lib\site-packages\conda\cli\main.py", line 97, in main
        from ..activate import main as activator_main
      File "C:\Users\Shvana\Anaconda3\lib\site-packages\conda\activate.py", line 15, in <module>
        context.__init__()  # oOn import, context does not include SEARCH_PATH. This line fixes that.
      File "C:\Users\Shvana\Anaconda3\lib\site-packages\conda\base\context.py", line 239, in __init__
        argparse_args=argparse_args)
      File "C:\Users\Shvana\Anaconda3\lib\site-packages\conda\common\configuration.py", line 722, in __init__
        self._set_search_path(search_path)
      File "C:\Users\Shvana\Anaconda3\lib\site-packages\conda\common\configuration.py", line 728, in _set_search_path
        self._set_raw_data(load_file_configs(search_path))
      File "C:\Users\Shvana\Anaconda3\lib\site-packages\conda\common\configuration.py", line 369, in load_file_configs
        raw_data = odict(kv for kv in chain.from_iterable(load_paths))
      File "C:\Users\Shvana\Anaconda3\lib\site-packages\conda\common\configuration.py", line 369, in <genexpr>
        raw_data = odict(kv for kv in chain.from_iterable(load_paths))
      File "C:\Users\Shvana\Anaconda3\lib\site-packages\conda\common\configuration.py", line 344, in _file_yaml_loader
        yield fullpath, YamlRawParameter.make_raw_parameters_from_file(fullpath)
      File "C:\Users\Shvana\Anaconda3\lib\site-packages\conda\common\configuration.py", line 332, in make_raw_parameters_from_file
        ruamel_yaml = yaml_load(fh)
      File "C:\Users\Shvana\Anaconda3\lib\site-packages\conda\common\serialize.py", line 54, in yaml_load
        return yaml.load(string, Loader=yaml.RoundTripLoader, version="1.2")
      File "C:\Users\Shvana\Anaconda3\lib\site-packages\ruamel_yaml\main.py", line 638, in load
        loader = Loader(stream, version, preserve_quotes=preserve_quotes)
      File "C:\Users\Shvana\Anaconda3\lib\site-packages\ruamel_yaml\loader.py", line 59, in __init__
        Reader.__init__(self, stream, loader=self)
      File "C:\Users\Shvana\Anaconda3\lib\site-packages\ruamel_yaml\reader.py", line 80, in __init__
        self.stream = stream  # type: Any  # as .read is called
      File "C:\Users\Shvana\Anaconda3\lib\site-packages\ruamel_yaml\reader.py", line 125, in stream
        self.determine_encoding()
      File "C:\Users\Shvana\Anaconda3\lib\site-packages\ruamel_yaml\reader.py", line 180, in determine_encoding
        self.update(1)
      File "C:\Users\Shvana\Anaconda3\lib\site-packages\ruamel_yaml\reader.py", line 266, in update
        self.check_printable(data)
      File "C:\Users\Shvana\Anaconda3\lib\site-packages\ruamel_yaml\reader.py", line 233, in check_printable
        'unicode', "special characters are not allowed")
    ruamel_yaml.reader.ReaderError: unacceptable character #x0000: special characters are not allowed
      in "C:\Users\Shvana\.condarc", position 0

`$ C:\Users\Shvana\Anaconda3\Scripts\conda shell.cmd.exe activate activate C:\Users\Shvana\Anaconda3`

  environment variables:
                 CIO_TEST=<not set>
               CONDA_ROOT=C:\Users\Shvana\Anaconda3
                CUDA_PATH=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.0
                 HOMEPATH=\Users\Shvana
      MIC_LD_LIBRARY_PATH=C:\Program Files (x86)\Common Files\Intel\Shared
                          Libraries\compiler\lib\mic
          NVTOOLSEXT_PATH=C:\Program Files\NVIDIA Corporation\NvToolsExt\
                     PATH=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.0\bin;C:\Program
                          Files\NVIDIA GPU Computing Toolkit\CUDA\v9.0\libnvvp;C:\Program Files
                          (x86)\Common Files\Intel\Shared
                          Libraries\redist\intel64\compiler;C:\Program Files (x86)\Common
                          Files\Oracle\Java\javapath;C:\Program Files (x86)\Intel\iCLS
                          Client\;C:\Program Files\Intel\iCLS Client\;C:\Windows\system32;C:\Win
                          dows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1
                          .0\;C:\Windows\System32\OpenSSH\;C:\Program Files (x86)\Intel\Intel(R)
                          Management Engine Components\DAL;C:\Program Files\Intel\Intel(R)
                          Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R)
                          Management Engine Components\IPT;C:\Program Files\Intel\Intel(R)
                          Management Engine
                          Components\IPT;C:\ProgramData\chocolatey\bin;C:\Program
                          Files\nodejs\;C:\Program Files\Git\cmd;C:\Program Files (x86)\NVIDIA
                          Corporation\PhysX\Common;C:\Program Files\NVIDIA Corporation\NVIDIA
                          NvDLISR;C:\Program Files\CMake\bin;C:\Users\Shvana\AppData\Local\Micro
                          soft\WindowsApps;C:\Program Files\JetBrains\PyCharm
                          2018.3.1\bin;;C:\Program Files\JetBrains\WebStorm 2018.3.1\bin;;C:\Use
                          rs\Shvana\AppData\Roaming\npm;C:\cuda\bin;C:\cuda\include;C:\cuda\lib;
                          C:\cuda\lib\x64;C:\Users\Shvana\AppData\Local\Programs\Microsoft VS
                          Code\bin;C:\Program Files\JetBrains\CLion 2018.3.2\bin;;C:\Program
                          Files\heroku\bin;C:\Users\Shvana\AppData\Local\Android\Sdk\platform-
                          tools;C:\Users\Shvana\AppData\Local\Android\Sdk\tools;
             PSMODULEPATH=C:\Program Files\WindowsPowerShell\Modules;C:\Windows\system32\Windows
                          PowerShell\v1.0\Modules
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>

     active environment : None
       user config file : C:\Users\Shvana\.condarc
 populated config files :
          conda version : 4.5.12
    conda-build version : 3.17.6
         python version : 3.7.1.final.0
       base environment : C:\Users\Shvana\Anaconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/win-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/win-64
                          https://repo.anaconda.com/pkgs/pro/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\Users\Shvana\Anaconda3\pkgs
                          C:\Users\Shvana\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\Shvana\Anaconda3\envs
                          C:\Users\Shvana\AppData\Local\conda\conda\envs
                          C:\Users\Shvana\.conda\envs
               platform : win-64
             user-agent : conda/4.5.12 requests/2.21.0 CPython/3.7.1 Windows/10 Windows/10.0.17763
          administrator : False
             netrc file : None
           offline mode : False

**Comment by Shvana** [comment]
![image](https://user-images.githubusercontent.com/26860232/53747319-ff2e6280-3e70-11e9-9d68-039c6990e296.png)

**Comment by Shvana** [comment]
![image](https://user-images.githubusercontent.com/26860232/53747419-369d0f00-3e71-11e9-8bac-3500698750cd.png)

**Comment by changhaizi** [comment]
等了好久没人帮忙解答，自己折腾了好久，最终找到了解决这个问题的方法：删除“.condarc”文件"，（C:\Users\Administrator\.condarc"）。再就可以了。。。。。。。。

**Comment by kumarprem02** [comment]
me too having the same problem

**Comment by changhaizi** [comment]
Delete ‘condarc’.

**Comment by goanpeca** [comment]
Delete C:\Users\Administrator\.condarc and try again
