### ISSUE TITLE
Spyder not launching from Anaconda-Navigator

### ISSUE THREAD

**Issue by eshain** [ContinuumIO/anaconda-issues#10708]
### Actual Behavior

When I try to launch Spyder from Anaconda-Navigator, I get the progress bar scrolling in the lower left corner and it says it's launching Spyder for about 10 seconds, then nothing happens. No splash screen. No launch.

### Expected Behavior

I expect Spyder  to show its splash screen then to launch.

### Steps to Reproduce

No idea, it started happening since I updated Spyder to version 3.3.3 (from within Navigator). Spyder launches normally from MacOS terminal so it is working.

I updated conda, anaconda and spyder again (from terminal) with no improvement. I upgraded qt and that didn't help either. Other things like JupyterLab, QTConsole, etc. all launch OK.

##### Operating System:

MacOS 10.14.3

##### `conda info`

<details>

```
     active environment : None
       user config file : /Users/ericshain/.condarc
 populated config files : /Users/ericshain/.condarc
          conda version : 4.6.7
    conda-build version : 3.17.6
         python version : 3.6.8.final.0
       base environment : /Users/ericshain/anaconda  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/osx-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/osx-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/osx-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /Users/ericshain/anaconda/pkgs
                          /Users/ericshain/.conda/pkgs
       envs directories : /Users/ericshain/anaconda/envs
                          /Users/ericshain/.conda/envs
               platform : osx-64
             user-agent : conda/4.6.7 requests/2.19.1 CPython/3.6.8 Darwin/18.2.0 OSX/10.14.3
                UID:GID : 501:20
             netrc file : None
           offline mode : False
```

</details>

##### `conda list --show-channel-urls`

<details>

```
# packages in environment at /Users/ericshain/anaconda:
#
# Name                    Version                   Build  Channel
_license                  1.1                      py36_1    defaults
_nb_ext_conf              0.4.0                    py36_1    defaults
alabaster                 0.7.11                   py36_0    defaults
anaconda                  custom           py36ha4fed55_0    defaults
anaconda-client           1.7.2                    py36_0    defaults
anaconda-navigator        1.9.6                    py36_0    defaults
anaconda-project          0.8.2                    py36_0    defaults
anyqt                     0.0.10                   py36_0    defaults
appdirs                   1.4.3            py36h28b3542_0    defaults
appnope                   0.1.0            py36hf537a9a_0    defaults
appscript                 1.0.1            py36h1de35cc_1    defaults
argcomplete               1.9.4                    py36_0    defaults
asn1crypto                0.24.0                   py36_0    defaults
asteval                   0.9.13             pyh24bf2e0_0    conda-forge
astroid                   2.0.4                    py36_0    defaults
astropy                   3.0.4            py36h1de35cc_0    defaults
atomicwrites              1.2.1                    py36_0    defaults
attrs                     18.2.0           py36h28b3542_0    defaults
autobahn                  18.3.1                     py_0    vpython
automat                   0.7.0                    py36_0    defaults
babel                     2.6.0                    py36_0    defaults
backcall                  0.1.0                    py36_0    defaults
backports                 1.0                      py36_1    defaults
backports.os              0.1.1                    py36_0    defaults
backports.shutil_get_terminal_size 1.0.0                    py36_2    defaults
beautifulsoup4            4.6.3                    py36_0    defaults
bitarray                  0.8.3            py36h1de35cc_0    defaults
bkcharts                  0.2              py36h073222e_0    defaults
blas                      1.0                         mkl    defaults
blaze                     0.11.3                   py36_0    defaults
bleach                    2.1.4                    py36_0    defaults
blosc                     1.14.4               hd9629dc_0    defaults
bokeh                     0.13.0                   py36_0    defaults
boto                      2.49.0                   py36_0    defaults
bottlechest               0.7.1                    py36_0    defaults
bottleneck                1.2.1            py36h1d22016_1    defaults
brewer2mpl                1.4.1                    pypi_0    pypi
bzip2                     1.0.6                h1de35cc_5    defaults
ca-certificates           2019.1.23                     0    defaults
cairo                     1.14.12              hc4e6be7_4    defaults
certifi                   2018.11.29               py36_0    defaults
cffi                      1.11.5           py36h6174b99_1    defaults
chardet                   3.0.4                    py36_1    defaults
chest                     0.2.3                    py36_1    defaults
click                     6.7              py36hec950be_0    defaults
cloudpickle               0.5.5                    py36_0    defaults
clyent                    1.2.2                    py36_1    defaults
colorama                  0.3.9            py36hd29a30c_0    defaults
commonmark                0.8.1                    py36_0    defaults
conda                     4.6.7                    py36_0    defaults
conda-build               3.17.6                   py36_0    defaults
conda-env                 2.6.0                         1    defaults
conda-verify              3.1.1                    py36_0    defaults
configobj                 5.0.6                    py36_1    defaults
constantly                15.1.0           py36h28b3542_0    defaults
contextlib2               0.5.5            py36hd66e5e7_0    defaults
cryptography              2.5              py36ha12b0ac_0    defaults
curl                      7.63.0            ha441bb4_1000    defaults
cycler                    0.10.0           py36hfc81398_0    defaults
cython                    0.28.5           py36h0a44026_0    defaults
cytoolz                   0.9.0.1          py36h1de35cc_1    defaults
dask                      0.19.1                   py36_0    defaults
dask-core                 0.19.1                   py36_0    defaults
datashape                 0.5.4                    py36_1    defaults
dbus                      1.13.2               h760590f_1    defaults
decorator                 4.3.0                    py36_0    defaults
defusedxml                0.5.0                    py36_1    defaults
dill                      0.2.8.2                  py36_0    defaults
distributed               1.23.1                   py36_0    defaults
docutils                  0.14             py36hbfde631_0    defaults
dynd-python               removed                       0    defaults
entrypoints               0.2.3                    py36_2    defaults
et_xmlfile                1.0.1            py36h1315bdc_0    defaults
expat                     2.2.6                h0a44026_0    defaults
fast-histogram            0.4              py36h917ab60_0    defaults
fastcache                 1.0.2            py36h1de35cc_2    defaults
ffmpeg                    4.0                  h01ea3c9_0    defaults
filelock                  3.0.8                    py36_0    defaults
flask                     1.0.2                    py36_1    defaults
flask-cors                3.0.6                    py36_0    defaults
fontconfig                2.13.0               h5d5b041_1    defaults
freetype                  2.9.1                hb4e5f40_0    defaults
future                    0.17.1                   py36_0    defaults
get_terminal_size         1.0.0                h7520d66_0    defaults
gettext                   0.19.8.1             h15daf44_3    defaults
gevent                    1.3.6            py36h1de35cc_0    defaults
ggplot                    0.11.5                   pypi_0    pypi
glib                      2.56.2               hd9629dc_0    defaults
glob2                     0.6                      py36_0    defaults
glue-core                 0.13.3                   py36_0    defaults
glue-vispy-viewers        0.10                     py36_0    defaults
glueviz                   0.13.3                        0    defaults
gmp                       6.1.2                hb37e062_1    defaults
gmpy2                     2.0.8            py36h6ef4df4_2    defaults
graphite2                 1.3.12               h2098e52_2    defaults
greenlet                  0.4.15           py36h1de35cc_0    defaults
h5py                      2.8.0            py36h878fce3_3    defaults
harfbuzz                  1.8.8                hb8d4a28_0    defaults
hdf5                      1.10.2               hfa1e0ec_1    defaults
heapdict                  1.0.0                    py36_2    defaults
html5lib                  1.0.1                    py36_0    defaults
htmlparser                0.0.2                    pypi_0    pypi
hyperlink                 18.0.0                   py36_0    defaults
icu                       58.2                 h4b95b61_1    defaults
idna                      2.7                      py36_0    defaults
imageio                   2.4.1                    py36_0    defaults
imagesize                 1.1.0                    py36_0    defaults
importlib_metadata        0.6                      py36_0    defaults
incremental               17.5.0                   py36_0    defaults
intel-openmp              2019.0                      118    defaults
ipykernel                 5.1.0            py36h39e3cac_0    defaults
ipython                   6.5.0                    py36_0    defaults
ipython_genutils          0.2.0            py36h241746c_0    defaults
ipywidgets                7.4.1                    py36_0    defaults
isort                     4.3.4                    py36_0    defaults
itsdangerous              0.24                     py36_1    defaults
jasper                    2.0.14               h636a363_1    defaults
jbig                      2.1                  h4d881f8_0    defaults
jdcal                     1.4                      py36_0    defaults
jedi                      0.12.1                   py36_0    defaults
jinja2                    2.10                     py36_0    defaults
joblib                    0.13.0                   py36_0    defaults
jpeg                      9b                   he5867d9_2    defaults
jsonschema                2.6.0            py36hb385e00_0    defaults
jupyter                   1.0.0                    py36_7    defaults
jupyter_client            5.2.3                    py36_0    defaults
jupyter_console           5.2.0                    py36_1    defaults
jupyter_core              4.4.0                    py36_0    defaults
jupyterlab                0.35.3                   py36_0    defaults
jupyterlab_launcher       0.13.1                   py36_0    defaults
jupyterlab_server         0.2.0                    py36_0    defaults
keyring                   13.2.1                   py36_0    defaults
keyrings.alt              3.1.1                    py36_0    defaults
kiwisolver                1.0.1            py36h0a44026_0    defaults
krb5                      1.16.1               hddcf347_7    defaults
lazy-object-proxy         1.3.1            py36h1de35cc_2    defaults
libarchive                3.3.3                h786848e_5    defaults
libcurl                   7.63.0            h051b688_1000    defaults
libcxx                    4.0.1                h579ed51_0    defaults
libcxxabi                 4.0.1                hebd6815_0    defaults
libdynd                   0.7.2                         0    defaults
libedit                   3.1.20170329         hb402a30_2    defaults
libffi                    3.2.1                h475c297_4    defaults
libgfortran               3.0.1                h93005f0_2    defaults
libiconv                  1.15                 hdd342a3_7    defaults
liblief                   0.9.0                h2a1bed3_0    defaults
libopenblas               0.3.3                hdc02c5d_3    defaults
libopencv                 3.4.2                h7c891bd_1    defaults
libopus                   1.3                  h1de35cc_0    defaults
libpng                    1.6.36               ha441bb4_0    defaults
libprotobuf               3.6.1                hd9629dc_0    defaults
libsodium                 1.0.16               h3efe00b_0    defaults
libssh2                   1.8.0                ha12b0ac_4    defaults
libtiff                   4.0.9                hcb84e12_2    defaults
libvpx                    1.7.0                h378b8a2_0    defaults
libxml2                   2.9.8                hab757c2_1    defaults
libxslt                   1.1.32               hb819dd2_0    defaults
line-profiler             2.1.2                    pypi_0    pypi
llvmlite                  0.24.0           py36hc454e04_0    defaults
lmfit                     0.9.12             pyh24bf2e0_0    conda-forge
locket                    0.2.0            py36hca03003_1    defaults
lxml                      4.2.5            py36hef8c89e_0    defaults
lz4-c                     1.8.1.2              h1de35cc_0    defaults
lzo                       2.10                 h362108e_2    defaults
markupsafe                1.0              py36h1de35cc_1    defaults
matplotlib                2.2.3            py36h54f8f79_0    defaults
mccabe                    0.6.1                    py36_1    defaults
mistune                   0.8.3            py36h1de35cc_1    defaults
mkl                       2018.0.3                      1    defaults
mkl-service               1.1.2            py36h6b9c3cc_5    defaults
mkl_fft                   1.0.4            py36h5d10147_1    defaults
mkl_random                1.0.1            py36h5d10147_1    defaults
more-itertools            4.3.0                    py36_0    defaults
mpc                       1.1.0                h6ef4df4_1    defaults
mpfr                      4.0.1                h3018a27_3    defaults
mpl-scatter-density       0.3                      py36_0    defaults
mpmath                    1.0.0                    py36_2    defaults
msgpack-python            0.5.6            py36h04f5b5a_1    defaults
multipledispatch          0.6.0                    py36_0    defaults
navigator-updater         0.2.1                    py36_0    defaults
nb_anacondacloud          1.4.0                    py36_0    defaults
nb_conda                  2.2.1                    py36_0    defaults
nb_conda_kernels          2.2.0                    py36_0    defaults
nbconvert                 5.4.0                    py36_1    defaults
nbformat                  4.4.0            py36h827af21_0    defaults
nbpresent                 3.0.2                    py36_1    defaults
ncurses                   6.1                  h0a44026_0    defaults
networkx                  2.1                      py36_0    defaults
nltk                      3.3.0                    py36_0    defaults
nose                      1.3.7                    py36_2    defaults
notebook                  5.7.4                    py36_0    defaults
numba                     0.39.0           py36h6440ff4_0    defaults
numexpr                   2.6.8            py36h1dc9127_0    defaults
numpy                     1.15.1           py36h6a91979_0    defaults
numpy-base                1.15.1           py36h8a80b8c_0    defaults
numpydoc                  0.8.0                    py36_0    defaults
odo                       0.5.1            py36hc1af34a_0    defaults
olefile                   0.46                     py36_0    defaults
opencv                    3.4.1            py36h6fd60c2_2    defaults
openpyxl                  2.5.6                    py36_0    defaults
openssl                   1.1.1b               h1de35cc_0    defaults
orange3                   3.13.0           py36h1702cab_0    defaults
packaging                 17.1                     py36_0    defaults
pandas                    0.23.4           py36h6440ff4_0    defaults
pandoc                    1.19.2.1             ha5e8f32_1    defaults
pandocfilters             1.4.2                    py36_1    defaults
parso                     0.3.1                    py36_0    defaults
partd                     0.3.8            py36hf5c4cb8_0    defaults
path.py                   11.1.0                   py36_0    defaults
pathlib2                  2.3.2                    py36_0    defaults
patsy                     0.5.0                    py36_0    defaults
pcre                      8.42                 h378b8a2_0    defaults
pep8                      1.7.1                    py36_0    defaults
pexpect                   4.6.0                    py36_0    defaults
pickleshare               0.7.4            py36hf512f8e_0    defaults
pillow                    5.2.0            py36hb68e598_0    defaults
pip                       10.0.1                   py36_0    defaults
pixman                    0.34.0               hca0a616_3    defaults
pkginfo                   1.4.2                    py36_1    defaults
plotly                    3.4.2            py36h28b3542_0    defaults
pluggy                    0.7.1            py36h28b3542_0    defaults
ply                       3.11                     py36_0    defaults
prometheus_client         0.3.1            py36h28b3542_0    defaults
prompt_toolkit            1.0.15           py36haeda067_0    defaults
psutil                    5.4.7            py36h1de35cc_0    defaults
ptyprocess                0.6.0                    py36_0    defaults
py                        1.6.0                    py36_0    defaults
py-lief                   0.9.0            py36hd4eaf27_0    defaults
py-opencv                 3.4.1            py36h9d9193e_1    defaults
pyasn1                    0.4.4            py36h28b3542_0    defaults
pyasn1-modules            0.2.2                    py36_0    defaults
pycodestyle               2.4.0                    py36_0    defaults
pycosat                   0.6.3            py36h1de35cc_0    defaults
pycparser                 2.18                     py36_1    defaults
pycrypto                  2.6.1            py36h1de35cc_9    defaults
pycurl                    7.43.0.2         py36ha12b0ac_0    defaults
pyflakes                  2.0.0                    py36_0    defaults
pygments                  2.2.0            py36h240cd3f_0    defaults
pylint                    2.1.1                    py36_0    defaults
pyodbc                    4.0.24           py36h0a44026_0    defaults
pyopengl                  3.1.1a1             np113py36_0    defaults
pyopenssl                 18.0.0                   py36_0    defaults
pyparsing                 2.2.0                    py36_1    defaults
pyqt                      5.9.2            py36h655552a_2    defaults
pyqt5                     5.9.2                    pypi_0    pypi
pyqtgraph                 0.10.0                   py36_0    defaults
pysocks                   1.6.8                    py36_0    defaults
pytables                  3.4.4            py36h13cba08_0    defaults
pytest                    3.8.0                    py36_0    defaults
pytest-arraydiff          0.2              py36h39e3cac_0    defaults
pytest-astropy            0.4.0                    py36_0    defaults
pytest-doctestplus        0.1.3                    py36_0    defaults
pytest-openfiles          0.3.0                    py36_0    defaults
pytest-remotedata         0.3.0                    py36_0    defaults
python                    3.6.8                haf84260_0    defaults
python-dateutil           2.7.3                    py36_0    defaults
python-libarchive-c       2.8                      py36_6    defaults
python.app                2                        py36_8    defaults
pytz                      2018.5                   py36_0    defaults
pywavelets                1.0.0            py36h1d22016_0    defaults
pyyaml                    3.13             py36h1de35cc_0    defaults
pyzmq                     17.1.2           py36h1de35cc_0    defaults
qt                        5.9.7                h468cd18_1    defaults
qtawesome                 0.4.4            py36h468c6fb_0    defaults
qtconsole                 4.4.1                    py36_0    defaults
qtpy                      1.5.0                    py36_0    defaults
readline                  7.0                  h1de35cc_5    defaults
redis                     5.0.0                h1de35cc_0    defaults
redis-py                  3.0.1                    py36_0    defaults
reportlab                 3.5.12           py36hdea1bd8_0    defaults
requests                  2.19.1                   py36_0    defaults
retrying                  1.3.3                    py36_2    defaults
rope                      0.11.0                   py36_0    defaults
ruamel_yaml               0.15.46          py36h1de35cc_0    defaults
scikit-image              0.14.0           py36h0a44026_1    defaults
scikit-learn              0.19.2           py36h4f467ca_0    defaults
scipy                     1.1.0            py36h28f7352_1    defaults
seaborn                   0.9.0                    py36_0    defaults
send2trash                1.5.0                    py36_0    defaults
serverfiles               0.3.0                    py36_0    defaults
service_identity          17.0.0           py36h28b3542_0    defaults
setuptools                40.2.0                   py36_0    defaults
simplegeneric             0.8.1                    py36_2    defaults
singledispatch            3.4.0.3          py36hf20db9d_0    defaults
sip                       4.19.8                   pypi_0    pypi
six                       1.11.0                   py36_1    defaults
snappy                    1.1.7                he62c110_3    defaults
snowballstemmer           1.2.1            py36h6c7b616_0    defaults
sockjs-tornado            1.0.6                    py36_0    defaults
sortedcollections         1.0.1                    py36_0    defaults
sortedcontainers          2.0.5                    py36_0    defaults
sphinx                    1.7.9                    py36_0    defaults
sphinx_rtd_theme          0.4.2                    py36_0    defaults
sphinxcontrib             1.0                      py36_1    defaults
sphinxcontrib-websupport  1.1.0                    py36_1    defaults
spyder                    3.3.3                    py36_0    defaults
spyder-kernels            0.4.2                    py36_0    defaults
spyder-line-profiler      0.1.1                    pypi_0    pypi
sqlalchemy                1.2.11           py36h1de35cc_0    defaults
sqlite                    3.26.0               ha441bb4_0    defaults
statsmodels               0.9.0            py36h1d22016_0    defaults
sympy                     1.2                      py36_0    defaults
tblib                     1.3.2            py36hda67792_0    defaults
terminado                 0.8.1                    py36_1    defaults
testpath                  0.3.1            py36h625a49b_0    defaults
tk                        8.6.8                ha441bb4_0    defaults
toolz                     0.9.0                    py36_0    defaults
tornado                   5.1              py36h1de35cc_0    defaults
tqdm                      4.26.0           py36h28b3542_0    defaults
traitlets                 4.3.2            py36h65bd3ce_0    defaults
twisted                   17.5.0                   py36_0    defaults
txaio                     2.9.0                      py_0    vpython
typed-ast                 1.1.0            py36h1de35cc_0    defaults
typing                    3.6.4                    py36_0    defaults
ujson                     1.35             py36h1de35cc_0    defaults
uncertainties             3.0.3                 py36_1000    conda-forge
unicodecsv                0.14.1           py36he531d66_0    defaults
unixodbc                  2.3.7                h1de35cc_0    defaults
urllib3                   1.23                     py36_0    defaults
vpnotebook                0.1.3                    py36_1    vpython
vpython                   7.4.6                    py36_0    vpython
wcwidth                   0.1.7            py36h8c6ec74_0    defaults
webencodings              0.5.1                    py36_1    defaults
werkzeug                  0.14.1                   py36_0    defaults
wheel                     0.31.1                   py36_0    defaults
widgetsnbextension        3.4.1                    py36_0    defaults
wrapt                     1.10.11          py36h1de35cc_2    defaults
wurlitzer                 1.0.2                    py36_0    defaults
xlrd                      1.1.0                    py36_1    defaults
xlsxwriter                1.1.0                    py36_0    defaults
xlwings                   0.11.8                   py36_0    defaults
xlwt                      1.2.0            py36h5ad1178_0    defaults
xz                        5.2.4                h1de35cc_4    defaults
yaml                      0.1.7                hc338f04_2    defaults
zeromq                    4.2.5                h0a44026_1    defaults
zict                      0.1.3                    py36_0    defaults
zlib                      1.2.11               hf3cbc9b_2    defaults
zope                      1.0                      py36_1    defaults
zope.interface            4.5.0            py36h1de35cc_0    defaults
zstd                      1.3.7                h5bba6e5_0    defaults
```

</details>

**Comment by ccordoba12** [comment]
Please open Terminal.app, launch Spyder from there with the command `spyder` and report back any errors you get.

**Comment by eshain** [comment]
Carlos,

I need to cd to the directory spyder is in (/Users/ericshain/anaconda/bin/)and launch by typing

Erics-MacBook-Air:bin ericshain$ python spyder

Spyder then launches with the proper splash screen. I get the following in the terminal:

Erics-MacBook-Air:bin ericshain$ python spyder
QCoreTextFontDatabase: Failed to resolve family name for PostScript name  "GujaratiSangamMN"
QCoreTextFontDatabase: Failed to resolve family name for PostScript name  "KannadaSangamMN"
QCoreTextFontDatabase: Failed to resolve family name for PostScript name  "KhmerSangamMN"
QCoreTextFontDatabase: Failed to resolve family name for PostScript name  "LaoSangamMN"
QCoreTextFontDatabase: Failed to resolve family name for PostScript name  "SinhalaSangamMN"
QCoreTextFontDatabase: Failed to resolve family name for PostScript name  "TamilSangamMN"
QCoreTextFontDatabase: Failed to resolve family name for PostScript name  "EuphemiaUCAS"
QCoreTextFontDatabase: Failed to resolve family name for PostScript name  "PlantagenetCherokee"
QCoreTextFontDatabase: Failed to resolve family name for PostScript name  "Kefa-Regular"
QCoreTextFontDatabase: Failed to resolve family name for PostScript name  "Kokonor"
QCoreTextFontDatabase: Failed to resolve family name for PostScript name  "STSongti-SC-Regular"
QCoreTextFontDatabase: Failed to resolve family name for PostScript name  "STSongti-TC-Regular"
QCoreTextFontDatabase: Failed to resolve family name for PostScript name  "STSongti-TC-Regular"
QCoreTextFontDatabase: Failed to resolve family name for PostScript name  "AppleMyungjo"
QCoreTextFontDatabase: Failed to resolve family name for PostScript name  "ITFDevanagari-Book"
QCoreTextFontDatabase: Failed to resolve family name for PostScript name  "GujaratiSangamMN"
QCoreTextFontDatabase: Failed to resolve family name for PostScript name  "KannadaMN"
QCoreTextFontDatabase: Failed to resolve family name for PostScript name  "KhmerMN"
QCoreTextFontDatabase: Failed to resolve family name for PostScript name  "LaoMN"
QCoreTextFontDatabase: Failed to resolve family name for PostScript name  "MyanmarMN"
QCoreTextFontDatabase: Failed to resolve family name for PostScript name  "SinhalaMN"
QCoreTextFontDatabase: Failed to resolve family name for PostScript name  "TamilSangamMN"
QCoreTextFontDatabase: Failed to resolve family name for PostScript name  "EuphemiaUCAS"
QCoreTextFontDatabase: Failed to resolve family name for PostScript name  "PlantagenetCherokee"
QCoreTextFontDatabase: Failed to resolve family name for PostScript name  "Kefa-Regular"
QCoreTextFontDatabase: Failed to resolve family name for PostScript name  "Kokonor"
QCoreTextFontDatabase: Failed to resolve family name for PostScript name  "GujaratiSangamMN"
QCoreTextFontDatabase: Failed to resolve family name for PostScript name  "KannadaSangamMN"
QCoreTextFontDatabase: Failed to resolve family name for PostScript name  "KhmerSangamMN"
QCoreTextFontDatabase: Failed to resolve family name for PostScript name  "LaoSangamMN"
QCoreTextFontDatabase: Failed to resolve family name for PostScript name  "SinhalaSangamMN"
QCoreTextFontDatabase: Failed to resolve family name for PostScript name  "TamilSangamMN"
QCoreTextFontDatabase: Failed to resolve family name for PostScript name  "EuphemiaUCAS"
QCoreTextFontDatabase: Failed to resolve family name for PostScript name  "PlantagenetCherokee"
QCoreTextFontDatabase: Failed to resolve family name for PostScript name  "Kefa-Regular"
QCoreTextFontDatabase: Failed to resolve family name for PostScript name  "Kokonor"
QCoreTextFontDatabase: Failed to resolve family name for PostScript name  "STSongti-SC-Regular"
QCoreTextFontDatabase: Failed to resolve family name for PostScript name  "STSongti-TC-Regular"
QCoreTextFontDatabase: Failed to resolve family name for PostScript name  "STSongti-TC-Regular"
QCoreTextFontDatabase: Failed to resolve family name for PostScript name  "AppleMyungjo"
QCoreTextFontDatabase: Failed to resolve family name for PostScript name  "GujaratiSangamMN"
QCoreTextFontDatabase: Failed to resolve family name for PostScript name  "KannadaMN"
QCoreTextFontDatabase: Failed to resolve family name for PostScript name  "KhmerMN"
QCoreTextFontDatabase: Failed to resolve family name for PostScript name  "LaoMN"
QCoreTextFontDatabase: Failed to resolve family name for PostScript name  "MyanmarMN"
QCoreTextFontDatabase: Failed to resolve family name for PostScript name  "SinhalaMN"
QCoreTextFontDatabase: Failed to resolve family name for PostScript name  "TamilSangamMN"
QCoreTextFontDatabase: Failed to resolve family name for PostScript name  "EuphemiaUCAS"
QCoreTextFontDatabase: Failed to resolve family name for PostScript name  "PlantagenetCherokee"
QCoreTextFontDatabase: Failed to resolve family name for PostScript name  "Kefa-Regular"
QCoreTextFontDatabase: Failed to resolve family name for PostScript name  "Kokonor"
QCoreTextFontDatabase: Failed to resolve family name for PostScript name  "STSongti-SC-Regular"
QCoreTextFontDatabase: Failed to resolve family name for PostScript name  "STSongti-TC-Regular"
QCoreTextFontDatabase: Failed to resolve family name for PostScript name  "STSongti-TC-Regular"
QCoreTextFontDatabase: Failed to resolve family name for PostScript name  "AppleMyungjo"
QCoreTextFontDatabase: Failed to resolve family name for PostScript name  "GujaratiSangamMN"
QCoreTextFontDatabase: Failed to resolve family name for PostScript name  "KannadaMN"
QCoreTextFontDatabase: Failed to resolve family name for PostScript name  "KhmerMN"
QCoreTextFontDatabase: Failed to resolve family name for PostScript name  "LaoMN"
QCoreTextFontDatabase: Failed to resolve family name for PostScript name  "MyanmarMN"
QCoreTextFontDatabase: Failed to resolve family name for PostScript name  "SinhalaMN"
QCoreTextFontDatabase: Failed to resolve family name for PostScript name  "TamilSangamMN"
QCoreTextFontDatabase: Failed to resolve family name for PostScript name  "EuphemiaUCAS"
QCoreTextFontDatabase: Failed to resolve family name for PostScript name  "PlantagenetCherokee"
QCoreTextFontDatabase: Failed to resolve family name for PostScript name  "Kefa-Regular"
QCoreTextFontDatabase: Failed to resolve family name for PostScript name  "GujaratiSangamMN"
QCoreTextFontDatabase: Failed to resolve family name for PostScript name  "KannadaSangamMN"
QCoreTextFontDatabase: Failed to resolve family name for PostScript name  "KhmerSangamMN"
QCoreTextFontDatabase: Failed to resolve family name for PostScript name  "LaoSangamMN"
QCoreTextFontDatabase: Failed to resolve family name for PostScript name  "SinhalaSangamMN"
QCoreTextFontDatabase: Failed to resolve family name for PostScript name  "TamilSangamMN"
QCoreTextFontDatabase: Failed to resolve family name for PostScript name  "EuphemiaUCAS"
QCoreTextFontDatabase: Failed to resolve family name for PostScript name  "PlantagenetCherokee"
QCoreTextFontDatabase: Failed to resolve family name for PostScript name  "Kefa-Regular"

Other than these font issues, Spyder runs just fine this way.


Eric

**Comment by Swapnil2095** [comment]
Same issue with window 10 OS.

Traceback (most recent call last):
File "C:\Users\Dell\Python3\Anaconda3\Scripts\spyder-script.py", line 6, in 
from spyder.app.start import main
File "C:\Users\Dell\Python3\Anaconda3\lib\site-packages\spyder\app\start.py", line 35, in 
from spyder.config.main import CONF
File "C:\Users\Dell\Python3\Anaconda3\lib\site-packages\spyder\config\main.py", line 21, in 
from spyder.config.fonts import BIG, MEDIUM, MONOSPACE, SANS_SERIF
File "C:\Users\Dell\Python3\Anaconda3\lib\site-packages\spyder\config\fonts.py", line 14, in 
from spyder.config.utils import is_ubuntu
File "C:\Users\Dell\Python3\Anaconda3\lib\site-packages\spyder\config\utils.py", line 15, in 
from spyder_kernels.utils import iofuncs
File "C:\Users\Dell\Python3\Anaconda3\lib\site-packages\spyder_kernels\utils\iofuncs.py", line 521, in 
iofunctions.setup()
File "C:\Users\Dell\Python3\Anaconda3\lib\site-packages\spyder_kernels\utils\iofuncs.py", line 445, in setup
iofuncs = self.get_internal_funcs()+self.get_3rd_party_funcs()
File "C:\Users\Dell\Python3\Anaconda3\lib\site-packages\spyder_kernels\utils\iofuncs.py", line 496, in get_3rd_party_funcs
for mod in get_spyderplugins_mods(io=True):
File "C:\Users\Dell\Python3\Anaconda3\lib\site-packages\spyder\otherplugins.py", line 42, in get_spyderplugins_mods
_get_spyderplugins(plugin_path, io, modnames, modlist)
File "C:\Users\Dell\Python3\Anaconda3\lib\site-packages\spyder\otherplugins.py", line 51, in _get_spyderplugins
for name in os.listdir(plugin_path):
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'C:\\Users\\Dell\\ '

**Comment by ccordoba12** [comment]
> I need to cd to the directory spyder is in (/Users/ericshain/anaconda/bin/)

This means you didn't add Spyder to your PATH, which is probably making Navigator to fail. In any case, it's not a Spyder problem.

**Comment by eshain** [comment]
Carlos,

It may not be a Spyder problem, but it is a Navigator problem in that when I updated Spyder in Navigator, it broke the path. Any hints on adding Spyder to my PATH?

Eric

**Comment by eshain** [comment]
Not to be annoying, but I installed Anaconda using the OS X installer. Spyder has always worked just fine from Navigator. Updating Spyder from inside Navigator seems to have broken something. You  mention adding Spyder to PATH, but I've googled it and can't figure out what you want me to do. Could you please give me at least a hint?

**Comment by ccordoba12** [comment]
Sorry, that's probably not the solution to make things work in Navigator. It's just weird that you're unable to start Spyder from Terminal.app by simply typing `spyder`.

**Comment by eshain** [comment]
Carlos,

I find that strange too. When you mention PATH do you mean the system path of PYTHONPATH? Any idea what I should add to the PATH to make it work?

Eric

**Comment by ccordoba12** [comment]
I mean what's explained here:

https://www.architectryan.com/2012/10/02/add-to-the-path-on-mac-os-x-mountain-lion/

And you need to add `/Users/ericshain/anaconda/bin/` to your PATH.

**Comment by eshain** [comment]
I did as instructed and Spyder still doesn’t launch from terminal correctly:

Last login: Tue Mar  5 15:44:05 on ttys000
Erics-MacBook-Air:~ ericshain$ ECHO $PATH
/Users/ericshain/anaconda/bin:/Users/ericshain/anaconda/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/ericshain/anaconda/bin/:/opt/X11/bin
Erics-MacBook-Air:~ ericshain$ spyder
/Users/ericshain/anaconda/bin/pythonw: line 3: /Users/ericshain/anaconda/python.app/Contents/MacOS/python: No such file or directory
Erics-MacBook-Air:~ ericshain$ 

Do I need to reboot?

Eric

**Comment by ccordoba12** [comment]
Please run

    conda install -f python.app

That could fix your problem.

**Comment by eshain** [comment]
That works! Many thanks...

**Comment by furkan-uzun** [comment]
@ccordoba12 That's worked for me also, Thanks!

**Comment by hari020204** [comment]
@ccordoba12  thank you ! it made my spyder work !

**Comment by rdfuhr** [comment]
@ccordoba12 Invoking conda install -f python.app also worked for me, enabling spyder 4.2.1 to launch from Anaconda Navigator.

So I am curious to know:  what about installing python.app in that manner enabled spyder to be successfully launched from Anaconda Navigator?

**Comment by wochristian** [comment]
Python.app is a proxy on macOS letting Python libraries hook into the GUI event loop.  Installing it fixed this Spyder v 4.2.2 not starting from within Anaconda Navigator on my iMac running Big Sur v11.2.2. 

https://anaconda.org/anaconda/python.app

**Comment by Hossenbaccus** [comment]
No QCoreApplication instance found. Application patches not applied. You have to call load_stylesheet function after instantiation of QApplication to take effect.

**Comment by scigeek72** [comment]
spyder 5.2.2 is not launching from anaconda navigator (it says problem with launching), 

If I try to do it from terminal (via spyder command), I am getting the following message
ModuleNotFoundError: No module named 'PyQt5.QtWebKitWidgets'


The error message I get while trying to launch from Anaconda navigator is this:
Traceback (most recent call last):
File "/~/anaconda3/envs/spv522-py39-torch/lib/python3.9/site-packages/qtpy/QtWebEngineWidgets.py", line 21, in 
from PyQt5.QtWebEngineWidgets import QWebEnginePage
ModuleNotFoundError: No module named 'PyQt5.QtWebEngineWidgets'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "~/anaconda3/envs/spv522-py39-torch/bin/spyder", line 11, in 
sys.exit(main())
File "~/anaconda3/envs/spv522-py39-torch/lib/python3.9/site-packages/spyder/app/start.py", line 233, in main
from spyder.app import mainwindow
File "~/anaconda3/envs/spv522-py39-torch/lib/python3.9/site-packages/spyder/app/mainwindow.py", line 57, in 
from qtpy import QtWebEngineWidgets # analysis:ignore
File "~/anaconda3/envs/spv522-py39-torch/lib/python3.9/site-packages/qtpy/QtWebEngineWidgets.py", line 28, in 
from PyQt5.QtWebKitWidgets import QWebPage as QWebEnginePage
ModuleNotFoundError: No module named 'PyQt5.QtWebKitWidgets'
