### ISSUE TITLE
Python fails to load dlls when runned without activating conda environment (with solution)

### ISSUE THREAD

**Issue by jiefangxuanyan** [ContinuumIO/anaconda-issues#10705]
### Actual Behavior

I'm using Windows x64. When I run a Python executable directly **without activating it's environment**, it may fail loading dlls. An example could be like this:
```bat
path_to_python.exe -c "import numpy"
```
which gets:
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\Lantt\Miniconda3\envs\site_fix\lib\site-packages\numpy\__init__.py", line 140, in <module>
    from . import _distributor_init
  File "C:\Users\Lantt\Miniconda3\envs\site_fix\lib\site-packages\numpy\_distributor_init.py", line 34, in <module>
    from . import _mklinit
ImportError: DLL load failed: 找不到指定的模块。
```
"找不到指定的模块。" means "The specified module could not be found."

The reason I have to run Python without activating environment is that I use Anaconda with Pycharm IDE, and Pycharm doesn't have an option to activate conda environments before running Python.

I found there is some code fixing `PATH` environment variable in `site.py` packed with Python. I guess it's original purpose is exactly to solve my issue. But it doesn't work well for two reasons:
1. The path it prepends is incomplete. It adds `conda_env_prefix\Library\bin` to the `PATH` environment variable. But actually Anaconda related dlls are scattered into 5 different locations (`conda_env_prefix\Library\mingw-w64\bin`, `conda_env_prefix\Library\usr\bin`, `conda_env_prefix\Library\bin`, `conda_env_prefix\Scripts`, `conda_env_prefix\bin`).
2. Modifing `PATH` after a process launched takes no effect on dll searching. Obviously `site.py` cannot be run before the Python interpreter. Fortunately I realized that dll searching path can be changed after process launching by calling Windows API `AddDllDirectory`. Use this API to add missing paths can solve the dll loading problem.

I modified my `site.py` fixing the problems above. It works well. But I don't know where to submit a pull request.

My fixing code is like this:
```python
if sys.platform == 'win32':
    # Anaconda Distribution hack in-case the environment has not been activated properly.
    library_bins = [
        ['Library', 'mingw-w64', 'bin'],
        ['Library', 'usr', 'bin'],
        ['Library', 'bin'],
        ['Scripts'],
        ['bin']
    ]
    current_path = set(makepath(path)[1] for path in os.environ["PATH"].split(os.pathsep))
    missing_path = []
    for library_bin in library_bins:
        new_path = os.path.join(sys.prefix, *library_bin)
        if makepath(new_path)[1] not in current_path:
            buf = ctypes.create_unicode_buffer(new_path)
            ctypes.windll.kernel32.AddDllDirectory(buf)
            missing_path.append(new_path)
    missing_path.append(os.environ["PATH"])
    os.environ["PATH"] = os.pathsep.join(missing_path)
```

### Expected Behavior

Numpy should be imported with no error.

### Steps to Reproduce

Open an Anaconda command prompt:
```bat
conda create -n site_fix python=3 numpy
```
Then close the command prompt, open **a new normal command prompt without activating any conda environment**:
```bat
C:\Users\Lantt\Miniconda3\envs\site_fix\python.exe -c "import numpy"
```

##### Anaconda or Miniconda version:

Miniconda3-4.5.1-Windows-x86_64

##### Operating System:

Windows 10 家庭中文版 (home Chinese version) 1803 x64

##### `conda info`

<details>

```
PASTE OUTPUT HERE:
     active environment : site_fix
    active env location : C:\Users\Lantt\Miniconda3\envs\site_fix
            shell level : 1
       user config file : C:\Users\Lantt\.condarc
 populated config files : C:\Users\Lantt\.condarc
          conda version : 4.6.4
    conda-build version : not installed
         python version : 3.6.8.final.0
       base environment : C:\Users\Lantt\Miniconda3  (writable)
           channel URLs : https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/win-64
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/noarch
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/win-64
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/noarch
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/r/win-64
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/r/noarch
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/pro/win-64
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/pro/noarch
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/msys2/win-64
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/msys2/noarch
          package cache : C:\Users\Lantt\Miniconda3\pkgs
                          C:\Users\Lantt\.conda\pkgs
                          C:\Users\Lantt\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\Lantt\Miniconda3\envs
                          C:\Users\Lantt\.conda\envs
                          C:\Users\Lantt\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.6.4 requests/2.21.0 CPython/3.6.8 Windows/10 Windows/10.0.17134
          administrator : False
             netrc file : None
           offline mode : False
```

</details>

##### `conda list --show-channel-urls`

<details>

```
PASTE OUTPUT HERE:
# packages in environment at C:\Users\Lantt\Miniconda3\envs\site_fix:
#
# Name                    Version                   Build  Channel
blas                      1.0                         mkl    defaults
ca-certificates           2019.1.23                     0    defaults
certifi                   2018.11.29               py37_0    defaults
icc_rt                    2019.0.0             h0cc432a_1    defaults
intel-openmp              2019.1                      144    defaults
mkl                       2019.1                      144    defaults
mkl_fft                   1.0.10           py37h14836fe_0    defaults
mkl_random                1.0.2            py37h343c172_0    defaults
numpy                     1.16.2           py37h19fb1c0_0    defaults
numpy-base                1.16.2           py37hc3f5095_0    defaults
openssl                   1.1.1b               he774522_0    defaults
pip                       19.0.3                   py37_0    defaults
python                    3.7.2               h8c8aaf0_10    defaults
setuptools                40.8.0                   py37_0    defaults
sqlite                    3.26.0               he774522_0    defaults
vc                        14.1                 h0510ff6_4    defaults
vs2015_runtime            14.15.26706          h3a45250_0    defaults
wheel                     0.33.1                   py37_0    defaults
wincertstore              0.2                      py37_0    defaults
```

</details>

**Comment by mingwandroid** [comment]
This is not a bug. You are required to activate. We do not support non-activation.

**Comment by mingwandroid** [comment]
I also use PyCharm, and I use it from Windows.

All you need to do is to launch it from the `Anaconda Prompt`, or you could write a Start Menu launcher that activates first.

Your add to PATH thing is not activation (also why are you messing about with `AddDllDirectory`? you *really* should not). Modifying PATH is only a part of activation. This skips whatever activation steps each package needs.

**Comment by jiefangxuanyan** [comment]
Thanks for your reply. I will try fixing on the Pycharm side.

**Comment by mingwandroid** [comment]
Yes, the base env is not really different in many technical senses to any other env. Activation is always necessary. That does not mean typing conda activate is ever necessary though.

**Comment by codebraker** [comment]
Ok, thank you for your reply. 
Cheers!
