### ISSUE TITLE
Navigator Error : An unexpected error occurred on Navigator start-up

### ISSUE THREAD

**Issue by panni1995** [ContinuumIO/anaconda-issues#10715]
### Actual Behavior

On clicking in anoconda navigator instead of opening the navigator with applications its opening a chorme with below message:

Report
Please report this issue in the anaconda issue tracker

Main Error
expected str, bytes or os.PathLike object, not NoneType
Traceback
Traceback (most recent call last):
  File "W:\Softwares\Anaconda\Anaconda3\lib\site-packages\anaconda_navigator\exceptions.py", line 75, in exception_handler
    return_value = func(*args, **kwargs)
  File "W:\Softwares\Anaconda\Anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 151, in start_app
    window = run_app(splash)
  File "W:\Softwares\Anaconda\Anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 65, in run_app
    window = MainWindow(splash=splash, tab_project=False)
  File "W:\Softwares\Anaconda\Anaconda3\lib\site-packages\anaconda_navigator\widgets\main_window.py", line 168, in __init__
    self.api = AnacondaAPI()
  File "W:\Softwares\Anaconda\Anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 2337, in AnacondaAPI
    ANACONDA_API = _AnacondaAPI()
  File "W:\Softwares\Anaconda\Anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 89, in __init__
    self._conda_api = CondaAPI()
  File "W:\Softwares\Anaconda\Anaconda3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 1767, in CondaAPI
    CONDA_API = _CondaAPI()
  File "W:\Softwares\Anaconda\Anaconda3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 353, in __init__
    self.sys_rc_path = join(self.ROOT_PREFIX, '.condarc')
  File "W:\Softwares\Anaconda\Anaconda3\lib\ntpath.py", line 76, in join
    path = os.fspath(path)
TypeError: expected str, bytes or os.PathLike object, not NoneType

### Expected Behavior

It has to open a window with  few applications from where we can launch jupyter notebook, Spyder, vs code kind of things

### Steps to Reproduce

Double clik on the Anaconda navigator

##### Anaconda or Miniconda version:

Python 3.7 64 bit

##### Operating System:

Windows 10

##### `conda info`

<details>

```
PASTE OUTPUT HERE:

```

</details>

##### `conda list --show-channel-urls`

<details>

```
PASTE OUTPUT HERE:

```

</details>

**Comment by goanpeca** [comment]
Please provide the information requested on the issue template

**Comment by panni1995** [comment]
Hi I could'nt find any particular issue template. can you please specify particulary. Do you want me to edit title to actual issue instead of error message

**Comment by goanpeca** [comment]
Ope the anaconda prompt

Type:
```
conda info
```
Paste Output

Type
```
conda list --show-channel-urls
```
Paste Output

**Comment by panni1995** [comment]
It seems Anaconda prompt is also not working

when i try to open it is generating error report as below:

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "W:\Softwares\Anaconda\Anaconda3\lib\site-packages\conda\cli\main.py", line 97, in main
        from ..activate import main as activator_main
      File "W:\Softwares\Anaconda\Anaconda3\lib\site-packages\conda\activate.py", line 15, in <module>
        context.__init__()  # oOn import, context does not include SEARCH_PATH. This line fixes that.
      File "W:\Softwares\Anaconda\Anaconda3\lib\site-packages\conda\base\context.py", line 239, in __init__
        argparse_args=argparse_args)
      File "W:\Softwares\Anaconda\Anaconda3\lib\site-packages\conda\common\configuration.py", line 722, in __init__
        self._set_search_path(search_path)
      File "W:\Softwares\Anaconda\Anaconda3\lib\site-packages\conda\common\configuration.py", line 728, in _set_search_path
        self._set_raw_data(load_file_configs(search_path))
      File "W:\Softwares\Anaconda\Anaconda3\lib\site-packages\conda\common\configuration.py", line 369, in load_file_configs
        raw_data = odict(kv for kv in chain.from_iterable(load_paths))
      File "W:\Softwares\Anaconda\Anaconda3\lib\site-packages\conda\common\configuration.py", line 369, in <genexpr>
        raw_data = odict(kv for kv in chain.from_iterable(load_paths))
      File "W:\Softwares\Anaconda\Anaconda3\lib\site-packages\conda\common\configuration.py", line 344, in _file_yaml_loader
        yield fullpath, YamlRawParameter.make_raw_parameters_from_file(fullpath)
      File "W:\Softwares\Anaconda\Anaconda3\lib\site-packages\conda\common\configuration.py", line 332, in make_raw_parameters_from_file
        ruamel_yaml = yaml_load(fh)
      File "W:\Softwares\Anaconda\Anaconda3\lib\site-packages\conda\common\serialize.py", line 54, in yaml_load
        return yaml.load(string, Loader=yaml.RoundTripLoader, version="1.2")
      File "W:\Softwares\Anaconda\Anaconda3\lib\site-packages\ruamel_yaml\main.py", line 638, in load
        loader = Loader(stream, version, preserve_quotes=preserve_quotes)
      File "W:\Softwares\Anaconda\Anaconda3\lib\site-packages\ruamel_yaml\loader.py", line 59, in __init__
        Reader.__init__(self, stream, loader=self)
      File "W:\Softwares\Anaconda\Anaconda3\lib\site-packages\ruamel_yaml\reader.py", line 80, in __init__
        self.stream = stream  # type: Any  # as .read is called
      File "W:\Softwares\Anaconda\Anaconda3\lib\site-packages\ruamel_yaml\reader.py", line 125, in stream
        self.determine_encoding()
      File "W:\Softwares\Anaconda\Anaconda3\lib\site-packages\ruamel_yaml\reader.py", line 180, in determine_encoding
        self.update(1)
      File "W:\Softwares\Anaconda\Anaconda3\lib\site-packages\ruamel_yaml\reader.py", line 266, in update
        self.check_printable(data)
      File "W:\Softwares\Anaconda\Anaconda3\lib\site-packages\ruamel_yaml\reader.py", line 233, in check_printable
        'unicode', "special characters are not allowed")
    ruamel_yaml.reader.ReaderError: unacceptable character #x0000: special characters are not allowed
      in "C:\Users\PUNNY\.condarc", position 0

`$ W:\Softwares\Anaconda\Anaconda3\Scripts\conda shell.cmd.exe activate activate W:\Softwares\Anaconda\Anaconda3`

  environment variables:
                 CIO_TEST=<not set>
               CONDA_ROOT=W:\Softwares\Anaconda\Anaconda3
                 HOMEPATH=\Users\PUNNY
                     PATH=W:\Softwares\Python\Scripts\;W:\Oracle\software\bin;C:\WINDOWS\system3
                          2;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPower
                          Shell\v1.0\;C:\WINDOWS\System32\OpenSSH\;W:\Softwares\Git\cmd;W:\Softw
                          ares\Python;C:\Users\PUNNY\AppData\Local\Microsoft\WindowsApps;C:\User
                          s\PUNNY\AppData\Local\Programs\Microsoft VS
                          Code\bin;W:\Softwares\Microsoft VS
                          Code\bin;W:\Softwares\Python\Scripts;
             PSMODULEPATH=C:\Program Files\WindowsPowerShell\Modules;C:\WINDOWS\system32\Windows
                          PowerShell\v1.0\Modules
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>

     active environment : None
       user config file : C:\Users\PUNNY\.condarc
 populated config files :
          conda version : 4.5.12
    conda-build version : 3.17.6
         python version : 3.7.1.final.0
       base environment : W:\Softwares\Anaconda\Anaconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/win-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/win-64
                          https://repo.anaconda.com/pkgs/pro/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : W:\Softwares\Anaconda\Anaconda3\pkgs
                          C:\Users\PUNNY\AppData\Local\conda\conda\pkgs
       envs directories : W:\Softwares\Anaconda\Anaconda3\envs
                          C:\Users\PUNNY\AppData\Local\conda\conda\envs
                          C:\Users\PUNNY\.conda\envs
               platform : win-64
             user-agent : conda/4.5.12 requests/2.21.0 CPython/3.7.1 Windows/10 Windows/10.0.17134
          administrator : False
             netrc file : None
           offline mode : False


An unexpected error has occurred. Conda has prepared the above report.
If submitted, this report will be used by core maintainers to improve
future releases of conda.

**Comment by nehaljwani** [comment]
@panni1995 Try deleting `C:\Users\PUNNY\.condarc`

**Comment by panni1995** [comment]
Hi im out of town I will check it and reply once i'm back

**Comment by panni1995** [comment]
Still my anaconda prompt is not opening can you reopen the ticket please

**Comment by dianalomelin** [comment]
I had the same issue:
Main Error
expected str, bytes or os.PathLike object, not NoneType

All of the conda update commands were unable to run.

Reinstalling didn't work either and I just did what @nehaljwani mentioned, then launched the Navigator again and now it's working.

"Try deleting C:\Users\PUNNY\.condarc"

Thanks @nehaljwani
