### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by Nikitato** [ContinuumIO/anaconda-issues#10717]
Can't launch jupyter lab from anaconda navigator

## Main error
Application <b>jupyterlab</b> launch may have produced errors.
## Traceback
```
Traceback (most recent call last):
  File "/Users/nikita/anaconda/envs/py36/bin/jupyter-lab", line 7, in <module>
    from jupyterlab.labapp import main
  File "/Users/nikita/anaconda/envs/py36/lib/python3.7/site-packages/jupyterlab/labapp.py", line 12, in <module>
    from jupyterlab_server import slugify, WORKSPACE_EXTENSION
ModuleNotFoundError: No module named 'jupyterlab_server'

```
## System information
```
platform: osx-64
version: 1.6.2
conda: 4.3.30
qt: 5.6.2
language: en
python: 2.7.13
os: Darwin;17.7.0;Darwin Kernel Version 17.7.0: Thu Jun 21 22:53:14 PDT 2018; root:xnu-4570.71.2~1/RELEASE_X86_64;x86_64;i386
pyqt: 5.6.0
```

**Comment by goanpeca** [comment]
Please remember to update to the latest version of Navigator to include
the latest fixes.

Open a terminal (on Linux or Mac) or the Anaconda Command Prompt (on windows)
and type:

```
conda update conda
conda update --all
```
