### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by TWilliamBell** [ContinuumIO/anaconda-issues#10725]
## Main error
Application <b>spyder</b> launch may have produced errors.
## Traceback
```
objc[82661]: Class RunLoopModeTracker is implemented in both /Users/williambell/anaconda/lib/python3.6/site-packages/PyQt5/Qt/lib/QtCore.framework/Versions/5/QtCore (0x11fbe6270) and /Users/williambell/anaconda/lib/libQt5Core.5.dylib (0x12aee19a8). One of the two will be used. Which one is undefined.
Traceback (most recent call last):
  File "/Users/williambell/anaconda/bin/spyder", line 6, in <module>
    sys.exit(spyder.app.start.main())
  File "/Users/williambell/anaconda/lib/python3.6/site-packages/spyder/app/start.py", line 103, in main
    from spyder.app import mainwindow
  File "/Users/williambell/anaconda/lib/python3.6/site-packages/spyder/app/mainwindow.py", line 92, in <module>
    from qtpy import QtWebEngineWidgets  # analysis:ignore
  File "/Users/williambell/anaconda/lib/python3.6/site-packages/qtpy/QtWebEngineWidgets.py", line 22, in <module>
    from PyQt5.QtWebEngineWidgets import QWebEnginePage
ValueError: PyCapsule_GetPointer called with incorrect name

```
## System information
```
python: 3.6.1
language: en
os: Darwin;17.5.0;Darwin Kernel Version 17.5.0: Mon Mar  5 22:24:32 PST 2018; root:xnu-4570.51.1~1/RELEASE_X86_64;x86_64;i386
version: 1.6.2
platform: osx-64
qt: 5.12.1
pyqt: 5.6.0
conda: 4.3.21
```

**Comment by goanpeca** [comment]
Please remember to update to the latest version of Navigator to include
the latest fixes.

Open a terminal (on Linux or Mac) or the Anaconda Command Prompt (on windows)
and type:

```
conda update conda
conda update --all
```
