### ISSUE TITLE
An unexpected error occurred on Navigator start-up-'root_prefix'

### ISSUE THREAD

**Issue by GuoTingBQ** [ContinuumIO/anaconda-issues#10730]
### Actual Behavior

Navigator Error

An unexpected error occurred on Navigator start-up

Report

Please report this issue in the anaconda  issue tracker  

Main Error

'root_prefix'

Traceback

Traceback (most recent call last):
  File "D:\ProgramData\Anaconda2\lib\site-packages\anaconda_navigator\exceptions.py", line 75, in exception_handler
    return_value = func(*args, **kwargs)
  File "D:\ProgramData\Anaconda2\lib\site-packages\anaconda_navigator\app\start.py", line 151, in start_app
    window = run_app(splash)
  File "D:\ProgramData\Anaconda2\lib\site-packages\anaconda_navigator\app\start.py", line 65, in run_app
    window = MainWindow(splash=splash, tab_project=False)
  File "D:\ProgramData\Anaconda2\lib\site-packages\anaconda_navigator\widgets\main_window.py", line 168, in __init__
    self.api = AnacondaAPI()
  File "D:\ProgramData\Anaconda2\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 2337, in AnacondaAPI
    ANACONDA_API = _AnacondaAPI()
  File "D:\ProgramData\Anaconda2\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 89, in __init__
    self._conda_api = CondaAPI()
  File "D:\ProgramData\Anaconda2\lib\site-packages\anaconda_navigator\api\conda_api.py", line 1767, in CondaAPI
    CONDA_API = _CondaAPI()
  File "D:\ProgramData\Anaconda2\lib\site-packages\anaconda_navigator\api\conda_api.py", line 350, in __init__
    self.set_conda_prefix(info=get_conda_info())
  File "D:\ProgramData\Anaconda2\lib\site-packages\anaconda_navigator\api\conda_api.py", line 505, in set_conda_prefix
    self.ROOT_PREFIX = info['root_prefix']
KeyError: 'root_prefix'

### Expected Behavior

open the anaconda

### Steps to Reproduce

click this icon
![image](https://user-images.githubusercontent.com/48545036/54337150-f86dcf80-4668-11e9-9375-a637cdec471f.png)

##### Anaconda or Miniconda version:

<!--
(base) C:\Users\g00280619>conda info

     active environment : base
    active env location : D:\ProgramData\Anaconda2
            shell level : 1
       user config file : C:\Users\g00280619\.condarc
 populated config files : C:\Users\g00280619\.condarc
          conda version : 4.5.12
    conda-build version : 3.17.6
         python version : 2.7.15.final.0
       base environment : D:\ProgramData\Anaconda2  (writable)
           channel URLs : https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/win-64
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/noarch
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/win-64
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/noarch
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/msys2/win-64
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/msys2/noarch
                          https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/win-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/win-64
                          https://repo.anaconda.com/pkgs/pro/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : D:\ProgramData\Anaconda2\pkgs
                          C:\Users\g00280619\AppData\Local\conda\conda\pkgs
       envs directories : D:\ProgramData\Anaconda2\envs
                          C:\Users\g00280619\AppData\Local\conda\conda\envs
                          C:\Users\g00280619\.conda\envs
               platform : win-64
             user-agent : conda/4.5.12 requests/2.21.0 CPython/2.7.15 Windows/7Windows/6.1.7601
          administrator : True
             netrc file : None
           offline mode : False

**Comment by GuoTingBQ** [comment]
![image](https://user-images.githubusercontent.com/48545036/54337331-8ea1f580-4669-11e9-897e-06ad6dcb9354.png)

**Comment by GuoTingBQ** [comment]
Try to fix this issue ，still cannot open the “anaconda-navigator”


Step1：conda update anaconda-navigator

![image](https://user-images.githubusercontent.com/48545036/54338843-01ad6b00-466e-11e9-84e6-ebe8ee4e9bd0.png)
![image](https://user-images.githubusercontent.com/48545036/54338878-2570b100-466e-11e9-8957-97c092e809f9.png)

Step2：anaconda-navigator

![image](https://user-images.githubusercontent.com/48545036/54338994-754f7800-466e-11e9-8bee-634b2ab9e899.png)
