### ISSUE TITLE
Anaconda navigator not showing up

### ISSUE THREAD

**Issue by trail99** [ContinuumIO/anaconda-issues#10774]
### Actual Behavior

I've been trying to install Anaconda 2018.12. I installed it as usual but it's not showing up in my Start Menu.I navigated to the folder where anaconda-navigator was installed. I found the .exe file but it didn't have the default icons. None of the .exe's have icons. It's just the square windows box. It was working before but I had to uninstall it for some reason.

Things I've tried: Reboots, a couple thousand of them, Install to default path, Install for all users, Add to PATH, Uninstalling and Reinstalling, probably about 20 times, Installing 32 and/or 64 bit versions, Removing existing versions of python (from path as well as uninstalling completely,) Installing Miniconda (which installs Anaconda Prompt, but doesn't help much)
Even if I add to path, and I open cmd, and run anaconda-navigator, I get a command not found error.

I've seen many people have this issue. Some have solved, some haven't. I've done a lot of googling and also searched on github and stackoverflow, but to no avail.
Can someone please help me get past this issue? It's eating up me head.

### Expected Behavior

Showing up of icons and shortcuts for the software. 

### Steps to Reproduce

Just Installing it normally via the installer

##### Anaconda or Miniconda version:
Anaconda3 2018.12, Windows 32 Bit, 64 Bit (Python 3.7)

##### Operating System:
Windows 10 Home 64 Bit
##### `conda info`

<details>

```
PASTE OUTPUT HERE:

```

</details>

##### `conda list --show-channel-urls`

<details>

```
PASTE OUTPUT HERE:

```

</details>

**Comment by csoja** [comment]
Can you try again with the latest Anaconda 2019.03 installer?

**Comment by trail99** [comment]
Well it did work, kinda. Now I have all the applications, but none of them are starting up. I tried Navigator, Spyder. They just don't start. 
I opened up anaconda prompt and typed anaconda-navigator to see if it fires up from there. Unfortunately I got these errors:

(base) C:\Users\Anup>anaconda-navigator
Traceback (most recent call last):
  File "I:\Anaconda3\lib\site-packages\qtpy\__init__.py", line 202, in <module>
    from PySide import __version__ as PYSIDE_VERSION  # analysis:ignore
ModuleNotFoundError: No module named 'PySide'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "I:\Anaconda3\Scripts\anaconda-navigator-script.py", line 6, in <module>
    from anaconda_navigator.app.main import main
  File "I:\Anaconda3\lib\site-packages\anaconda_navigator\app\main.py", line 22, in <module>
    from anaconda_navigator.utils.conda import is_conda_available
  File "I:\Anaconda3\lib\site-packages\anaconda_navigator\utils\__init__.py", line 15, in <module>
    from qtpy.QtGui import QIcon
  File "I:\Anaconda3\lib\site-packages\qtpy\__init__.py", line 208, in <module>
    raise PythonQtError('No Qt bindings could be found')
qtpy.PythonQtError: No Qt bindings could be found
