### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by qxia1991** [ContinuumIO/anaconda-issues#10784]
## Main error
An unexpected error occurred on Navigator start-up<br>psutil.AccessDenied (pid=796)
## Traceback
```
Traceback (most recent call last):
  File "/anaconda/envs/py27/lib/python2.7/site-packages/anaconda_navigator/exceptions.py", line 75, in exception_handler
    return_value = func(*args, **kwargs)
  File "/anaconda/envs/py27/lib/python2.7/site-packages/anaconda_navigator/app/start.py", line 108, in start_app
    if misc.load_pid() is None:  # A stale lock might be around
  File "/anaconda/envs/py27/lib/python2.7/site-packages/anaconda_navigator/utils/misc.py", line 384, in load_pid
    cmds = process.cmdline()
  File "/anaconda/envs/py27/lib/python2.7/site-packages/psutil/__init__.py", line 701, in cmdline
    return self._proc.cmdline()
  File "/anaconda/envs/py27/lib/python2.7/site-packages/psutil/_psosx.py", line 306, in wrapper
    raise AccessDenied(self.pid, self._name)
AccessDenied: psutil.AccessDenied (pid=796)

```
## System information
```
platform: osx-64
version: 1.6.2
conda: 4.3.21
qt: 5.6.2
language: en
python: 2.7.13
os: Darwin;17.7.0;Darwin Kernel Version 17.7.0: Thu Dec 20 21:47:19 PST 2018; root:xnu-4570.71.22~1/RELEASE_X86_64;x86_64;i386
pyqt: 5.6.0
```

**Comment by csoja** [comment]
In the terminal or Anaconda Prompt:

conda update conda
conda update anaconda-navigator
conda update navigator-updater
anaconda-navigator --reset

The last command is the key to fixing your issue - as it removes the lock file that is causing your problem.
