### ISSUE TITLE
Un able to open anaconda navigator

### ISSUE THREAD

**Issue by Ashu-jun** [ContinuumIO/anaconda-issues#10792]
Traceback (most recent call last):
  File "C:\Users\intkonsys\Anaconda3\lib\site-packages\qtpy\__init__.py", line 199, in <module>
    from PySide import __version__ as PYSIDE_VERSION  # analysis:ignore
ModuleNotFoundError: No module named 'PySide'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\intkonsys\Anaconda3\Scripts\anaconda-navigator-script.py", line 6, in <module>
    from anaconda_navigator.app.main import main
  File "C:\Users\intkonsys\Anaconda3\lib\site-packages\anaconda_navigator\app\main.py", line 22, in <module>
    from anaconda_navigator.utils.conda import is_conda_available
  File "C:\Users\intkonsys\Anaconda3\lib\site-packages\anaconda_navigator\utils\__init__.py", line 15, in <module>
    from qtpy.QtGui import QIcon
  File "C:\Users\intkonsys\Anaconda3\lib\site-packages\qtpy\__init__.py", line 205, in <module>
    raise PythonQtError('No Qt bindings could be found')
qtpy.PythonQtError: No Qt bindings could be found

**Comment by Ashu-jun** [comment]
conda update conda
conda update --all
conda install psutil=5.4.6
conda install psutil=5.4.6 --force

i tried this all still it is not opening
