### ISSUE TITLE
Navigator Error->An unexpected error occurred on Navigator start-up

### ISSUE THREAD

**Issue by vikrambala** [ContinuumIO/anaconda-issues#10806]
### Actual Behavior

While opening the ananconda, the anaconda navigator is not opening

### Expected Behavior

Ananconda navigator to open and should be available

### Steps to Reproduce

Navigator Error
An unexpected error occurred on Navigator start-up
Report
Please report this issue in the anaconda issue tracker 
Main Error

expected str, bytes or os.PathLike object, not NoneType

Traceback

Traceback (most recent call last):
  File "C:\anaconda\AppData\Local\Continuum\anaconda3\lib\site-packages\anaconda_navigator\exceptions.py", line 75, in exception_handler
    return_value = func(*args, **kwargs)
  File "C:\anaconda\AppData\Local\Continuum\anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 151, in start_app
    window = run_app(splash)
  File "C:\anaconda\AppData\Local\Continuum\anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 65, in run_app
    window = MainWindow(splash=splash, tab_project=False)
  File "C:\anaconda\AppData\Local\Continuum\anaconda3\lib\site-packages\anaconda_navigator\widgets\main_window.py", line 168, in __init__
    self.api = AnacondaAPI()
  File "C:\anaconda\AppData\Local\Continuum\anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 2337, in AnacondaAPI
    ANACONDA_API = _AnacondaAPI()
  File "C:\anaconda\AppData\Local\Continuum\anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 89, in __init__
    self._conda_api = CondaAPI()
  File "C:\anaconda\AppData\Local\Continuum\anaconda3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 1767, in CondaAPI
    CONDA_API = _CondaAPI()
  File "C:\anaconda\AppData\Local\Continuum\anaconda3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 353, in __init__
    self.sys_rc_path = join(self.ROOT_PREFIX, '.condarc')
  File "C:\anaconda\AppData\Local\Continuum\anaconda3\lib\ntpath.py", line 76, in join
    path = os.fspath(path)
TypeError: expected str, bytes or os.PathLike object, not NoneType

##### Anaconda or Miniconda version:
          conda version : 4.5.12
    conda-build version : 3.17.6
         python version : 3.7.1.final.0

##### Operating System:
Windows 10 

##### `conda info`

<details>

```

 Traceback (most recent call last):
      File "C:\anaconda\AppData\Local\Continuum\anaconda3\lib\site-packages\conda\cli\main.py", line 97, in main
        from ..activate import main as activator_main
      File "C:\anaconda\AppData\Local\Continuum\anaconda3\lib\site-packages\conda\activate.py", line 15, in <module>
        context.__init__()  # oOn import, context does not include SEARCH_PATH. This line fixes that.
      File "C:\anaconda\AppData\Local\Continuum\anaconda3\lib\site-packages\conda\base\context.py", line 239, in __init__
        argparse_args=argparse_args)
      File "C:\anaconda\AppData\Local\Continuum\anaconda3\lib\site-packages\conda\common\configuration.py", line 722, in __init__
        self._set_search_path(search_path)
      File "C:\anaconda\AppData\Local\Continuum\anaconda3\lib\site-packages\conda\common\configuration.py", line 728, in _set_search_path
        self._set_raw_data(load_file_configs(search_path))
      File "C:\anaconda\AppData\Local\Continuum\anaconda3\lib\site-packages\conda\common\configuration.py", line 369, in load_file_configs
        raw_data = odict(kv for kv in chain.from_iterable(load_paths))
      File "C:\anaconda\AppData\Local\Continuum\anaconda3\lib\site-packages\conda\common\configuration.py", line 369, in <genexpr>
        raw_data = odict(kv for kv in chain.from_iterable(load_paths))
      File "C:\anaconda\AppData\Local\Continuum\anaconda3\lib\site-packages\conda\common\configuration.py", line 344, in _file_yaml_loader
        yield fullpath, YamlRawParameter.make_raw_parameters_from_file(fullpath)
      File "C:\anaconda\AppData\Local\Continuum\anaconda3\lib\site-packages\conda\common\configuration.py", line 332, in make_raw_parameters_from_file
        ruamel_yaml = yaml_load(fh)
      File "C:\anaconda\AppData\Local\Continuum\anaconda3\lib\site-packages\conda\common\serialize.py", line 54, in yaml_load
        return yaml.load(string, Loader=yaml.RoundTripLoader, version="1.2")
      File "C:\anaconda\AppData\Local\Continuum\anaconda3\lib\site-packages\ruamel_yaml\main.py", line 638, in load
        loader = Loader(stream, version, preserve_quotes=preserve_quotes)
      File "C:\anaconda\AppData\Local\Continuum\anaconda3\lib\site-packages\ruamel_yaml\loader.py", line 59, in __init__
        Reader.__init__(self, stream, loader=self)
      File "C:\anaconda\AppData\Local\Continuum\anaconda3\lib\site-packages\ruamel_yaml\reader.py", line 80, in __init__
        self.stream = stream  # type: Any  # as .read is called
      File "C:\anaconda\AppData\Local\Continuum\anaconda3\lib\site-packages\ruamel_yaml\reader.py", line 125, in stream
        self.determine_encoding()
      File "C:\anaconda\AppData\Local\Continuum\anaconda3\lib\site-packages\ruamel_yaml\reader.py", line 180, in determine_encoding
        self.update(1)
      File "C:\anaconda\AppData\Local\Continuum\anaconda3\lib\site-packages\ruamel_yaml\reader.py", line 266, in update
        self.check_printable(data)
      File "C:\anaconda\AppData\Local\Continuum\anaconda3\lib\site-packages\ruamel_yaml\reader.py", line 233, in check_printable
        'unicode', "special characters are not allowed")
    ruamel_yaml.reader.ReaderError: unacceptable character #x0000: special characters are not allowed
      in "C:\Users\balamurugan.moorthy\.condarc", position 0

```

</details>

##### `conda list --show-channel-urls`

<details>

```
 Traceback (most recent call last):
      File "C:\anaconda\AppData\Local\Continuum\anaconda3\lib\site-packages\conda\cli\main.py", line 97, in main
        from ..activate import main as activator_main
      File "C:\anaconda\AppData\Local\Continuum\anaconda3\lib\site-packages\conda\activate.py", line 15, in <module>
        context.__init__()  # oOn import, context does not include SEARCH_PATH. This line fixes that.
      File "C:\anaconda\AppData\Local\Continuum\anaconda3\lib\site-packages\conda\base\context.py", line 239, in __init__
        argparse_args=argparse_args)
      File "C:\anaconda\AppData\Local\Continuum\anaconda3\lib\site-packages\conda\common\configuration.py", line 722, in __init__
        self._set_search_path(search_path)
      File "C:\anaconda\AppData\Local\Continuum\anaconda3\lib\site-packages\conda\common\configuration.py", line 728, in _set_search_path
        self._set_raw_data(load_file_configs(search_path))
      File "C:\anaconda\AppData\Local\Continuum\anaconda3\lib\site-packages\conda\common\configuration.py", line 369, in load_file_configs
        raw_data = odict(kv for kv in chain.from_iterable(load_paths))
      File "C:\anaconda\AppData\Local\Continuum\anaconda3\lib\site-packages\conda\common\configuration.py", line 369, in <genexpr>
        raw_data = odict(kv for kv in chain.from_iterable(load_paths))
      File "C:\anaconda\AppData\Local\Continuum\anaconda3\lib\site-packages\conda\common\configuration.py", line 344, in _file_yaml_loader
        yield fullpath, YamlRawParameter.make_raw_parameters_from_file(fullpath)
      File "C:\anaconda\AppData\Local\Continuum\anaconda3\lib\site-packages\conda\common\configuration.py", line 332, in make_raw_parameters_from_file
        ruamel_yaml = yaml_load(fh)
      File "C:\anaconda\AppData\Local\Continuum\anaconda3\lib\site-packages\conda\common\serialize.py", line 54, in yaml_load
        return yaml.load(string, Loader=yaml.RoundTripLoader, version="1.2")
      File "C:\anaconda\AppData\Local\Continuum\anaconda3\lib\site-packages\ruamel_yaml\main.py", line 638, in load
        loader = Loader(stream, version, preserve_quotes=preserve_quotes)
      File "C:\anaconda\AppData\Local\Continuum\anaconda3\lib\site-packages\ruamel_yaml\loader.py", line 59, in __init__
        Reader.__init__(self, stream, loader=self)
      File "C:\anaconda\AppData\Local\Continuum\anaconda3\lib\site-packages\ruamel_yaml\reader.py", line 80, in __init__
        self.stream = stream  # type: Any  # as .read is called
      File "C:\anaconda\AppData\Local\Continuum\anaconda3\lib\site-packages\ruamel_yaml\reader.py", line 125, in stream
        self.determine_encoding()
      File "C:\anaconda\AppData\Local\Continuum\anaconda3\lib\site-packages\ruamel_yaml\reader.py", line 180, in determine_encoding
        self.update(1)
      File "C:\anaconda\AppData\Local\Continuum\anaconda3\lib\site-packages\ruamel_yaml\reader.py", line 266, in update
        self.check_printable(data)
      File "C:\anaconda\AppData\Local\Continuum\anaconda3\lib\site-packages\ruamel_yaml\reader.py", line 233, in check_printable
        'unicode', "special characters are not allowed")
    ruamel_yaml.reader.ReaderError: unacceptable character #x0000: special characters are not allowed
      in "C:\Users\balamurugan.moorthy\.condarc", position 0

```

</details>

**Comment by vikrambala** [comment]
Is this issue related to Microsoft Visual Studio.

I faced this issue after installing the Microsoft Visual Studio with Python. I have uninstall microsoft visual studio 2017. Uninstalled and installed Anaconda.

Still I face the same issue
