### ISSUE TITLE
error when launching Anaconda-navigator (Mac)

### ISSUE THREAD

**Issue by ebhen** [ContinuumIO/anaconda-issues#10838]
### Actual Behavior

Tonight I tried to launch my Anaconda-navigator (I was using it perfectly earlier in the day). This time it did not launch and I'm not able to enter the Anaconda-navigator. I haven't done anything yet, but suspect it could be an update issue regarding anaconda??

When running I get the following:

`2019-04-17 00:20:32,503 - ERROR download_api._get_url:416
Expecting value: line 1 column 1 (char 0)

Traceback (most recent call last):
  File "/anaconda3/lib/python3.6/site-packages/anaconda_navigator/widgets/main_window.py", line 539, in setup
    self.post_setup(conda_data=conda_data)
  File "/anaconda3/lib/python3.6/site-packages/anaconda_navigator/widgets/main_window.py", line 576, in post_setup
    self.tab_home.setup(conda_data)
  File "/anaconda3/lib/python3.6/site-packages/anaconda_navigator/widgets/tabs/home.py", line 169, in setup
    self.set_applications(applications, packages)
  File "/anaconda3/lib/python3.6/site-packages/anaconda_navigator/widgets/tabs/home.py", line 204, in set_applications
    apps = self.api.process_apps(applications, prefix=self.current_prefix)
  File "/anaconda3/lib/python3.6/site-packages/anaconda_navigator/api/anaconda_api.py", line 888, in process_apps
    versions=[vsdata.get('productVersion')],
AttributeError: 'str' object has no attribute 'get'
`
### Expected Behavior

Anaconda-Navigator should launch so I can get back to using jupyter notebook and spyder :)

##### Operating System:
Mac osx-64

##### `conda info`

<details>

```

     active environment : base
    active env location : /anaconda3
            shell level : 1
       user config file : /Users/emilhenningsen/.condarc
 populated config files : /Users/emilhenningsen/.condarc
          conda version : 4.5.12
    conda-build version : 3.17.5
         python version : 3.6.7.final.0
       base environment : /anaconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/osx-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/osx-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/osx-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/osx-64
                          https://repo.anaconda.com/pkgs/pro/noarch
          package cache : /anaconda3/pkgs
                          /Users/emilhenningsen/.conda/pkgs
       envs directories : /anaconda3/envs
                          /Users/emilhenningsen/.conda/envs
               platform : osx-64
             user-agent : conda/4.5.12 requests/2.21.0 CPython/3.6.7 Darwin/18.2.0 OSX/10.14.1
                UID:GID : 501:20
             netrc file : None
           offline mode : False

```

</details>

##### `conda list --show-channel-urls`

<details>

```
# packages in environment at /anaconda3:
#
# Name                    Version                   Build  Channel
_ipyw_jlab_nb_ext_conf    0.1.0                    py36_0    defaults
_py-xgboost-mutex         2.0                       cpu_0    conda-forge
alabaster                 0.7.12                     py_0    conda-forge
anaconda                  5.3.0                    py37_0    defaults
anaconda-client           1.7.1                      py_0    conda-forge
anaconda-navigator        1.9.6                    py36_0    defaults
anaconda-project          0.8.2                      py_1    conda-forge
appdirs                   1.4.3                      py_1    conda-forge
appnope                   0.1.0                 py36_1000    conda-forge
appscript                 1.0.1            py36h470a237_0    conda-forge
asn1crypto                0.24.0                py36_1003    conda-forge
astroid                   2.1.0                 py36_1000    conda-forge
astropy                   3.0.4            py37h1de35cc_0    defaults
atomicwrites              1.2.1                      py_0    conda-forge
attrs                     18.2.0                     py_0    conda-forge
automat                   0.7.0                      py_1    conda-forge
babel                     2.6.0                      py_1    conda-forge
backcall                  0.1.0                      py_0    conda-forge
backports                 1.0                        py_2    conda-forge
backports.os              0.1.1                 py36_1000    conda-forge
backports.shutil_get_terminal_size 1.0.0                      py_3    conda-forge
beautifulsoup4            4.6.3                 py36_1000    conda-forge
bitarray                  0.8.3            py36h470a237_0    conda-forge
bkcharts                  0.2                      py37_0    defaults
blas                      1.0                         mkl    defaults
blaze                     0.11.3                   py37_0    defaults
bleach                    3.0.2                      py_1    conda-forge
blosc                     1.14.4               hd9629dc_0    defaults
bokeh                     0.13.0                   py37_0    defaults
boto                      2.49.0                   py36_0    defaults
bottleneck                1.2.1            py37h1d22016_1    defaults
bzip2                     1.0.6                h1de35cc_5    defaults
ca-certificates           2018.03.07                    0    anaconda
certifi                   2018.10.15               py36_0    anaconda
cffi                      1.11.5           py36h5e8e0c9_1    conda-forge
chardet                   3.0.4                 py36_1003    conda-forge
click                     7.0                        py_0    conda-forge
cloudpickle               0.6.1                      py_0    conda-forge
clyent                    1.2.2                      py_1    conda-forge
colorama                  0.4.1                      py_0    conda-forge
conda                     4.5.12                   py36_0    defaults
conda-build               3.17.5                   py36_0    conda-forge
conda-env                 2.6.0                         1    defaults
constantly                15.1.0                     py_0    conda-forge
contextlib2               0.5.5                      py_2    conda-forge
cryptography              2.4.2            py36ha12b0ac_0    defaults
cryptography-vectors      2.3.1                 py36_1000    conda-forge
curl                      7.63.0            ha441bb4_1000    defaults
cycler                    0.10.0                     py_1    conda-forge
cython                    0.29.2           py36hfc679d8_0    conda-forge
cytoolz                   0.9.0.1          py36h470a237_1    conda-forge
dask                      0.19.1                   py37_0    defaults
dask-core                 1.0.0                      py_0    conda-forge
datashape                 0.5.4                    py37_1    defaults
dbus                      1.13.2               h760590f_1    defaults
decorator                 4.3.0                      py_0    conda-forge
defusedxml                0.5.0                      py_1    conda-forge
distributed               1.25.1                py36_1000    conda-forge
docutils                  0.14                  py36_1001    conda-forge
entrypoints               0.2.3                 py36_1002    conda-forge
et_xmlfile                1.0.1                 py36_1000    conda-forge
expat                     2.2.6                h0a44026_0    defaults
fastcache                 1.0.2            py36h470a237_1    conda-forge
filelock                  3.0.10                     py_0    conda-forge
flask                     1.0.2                      py_2    conda-forge
flask-cors                3.0.6                      py_0    conda-forge
freetype                  2.9.1                hb4e5f40_0    defaults
get_terminal_size         1.0.0                h7520d66_0    defaults
gettext                   0.19.8.1             h15daf44_3    defaults
gevent                    1.3.7            py36h470a237_0    conda-forge
glib                      2.56.2               hd9629dc_0    defaults
glob2                     0.6                        py_0    conda-forge
gmp                       6.1.2                hb37e062_1    defaults
gmpy2                     2.0.8            py36hb705a9b_2    conda-forge
greenlet                  0.4.13                   py36_0    conda-forge
h5py                      2.8.0            py37h878fce3_3    defaults
hdf5                      1.10.2               hfa1e0ec_1    defaults
heapdict                  1.0.0                 py36_1000    conda-forge
html5lib                  1.0.1                      py_0    conda-forge
hyperlink                 17.3.1                     py_0    conda-forge
icu                       58.2                 h4b95b61_1    defaults
idna                      2.8                   py36_1000    conda-forge
imageio                   2.4.1                    py37_0    defaults
imagesize                 1.1.0                      py_0    conda-forge
importlib_metadata        0.6                      py36_0    conda-forge
incremental               17.5.0                     py_0    conda-forge
intel-openmp              2019.0                      118    defaults
ipykernel                 5.1.0           py36h24bf2e0_1001    conda-forge
ipython                   7.2.0           py36h24bf2e0_1000    conda-forge
ipython_genutils          0.2.0                      py_1    conda-forge
ipywidgets                7.4.2                      py_0    conda-forge
isort                     4.3.4                 py36_1000    conda-forge
itsdangerous              1.1.0                      py_0    conda-forge
jbig                      2.1                  h4d881f8_0    defaults
jdcal                     1.4                        py_1    conda-forge
jedi                      0.13.2                py36_1000    conda-forge
jinja2                    2.10                       py_1    conda-forge
jpeg                      9b                   he5867d9_2    defaults
jsonschema                3.0.0a3               py36_1000    conda-forge
jupyter                   1.0.0                      py_1    conda-forge
jupyter_client            5.2.4                      py_0    conda-forge
jupyter_console           6.0.0                      py_0    conda-forge
jupyter_core              4.4.0                      py_0    conda-forge
jupyterlab                0.35.4                   py36_0    conda-forge
jupyterlab_launcher       0.13.1                     py_2    conda-forge
jupyterlab_server         0.2.0                      py_0    conda-forge
keyring                   17.0.0                py36_1000    conda-forge
kiwisolver                1.0.1            py36h2d50403_2    conda-forge
krb5                      1.16.1               hddcf347_7    defaults
lazy-object-proxy         1.3.1            py36h470a237_0    conda-forge
libarchive                3.3.3                h786848e_5    defaults
libcurl                   7.63.0            h051b688_1000    defaults
libcxx                    4.0.1                h579ed51_0    defaults
libcxxabi                 4.0.1                hebd6815_0    defaults
libedit                   3.1.20170329         hb402a30_2    defaults
libffi                    3.2.1                h475c297_4    defaults
libgfortran               3.0.1                h93005f0_2    defaults
libiconv                  1.15                 hdd342a3_7    defaults
liblief                   0.9.0                h2a1bed3_0    defaults
libpng                    1.6.35               ha441bb4_0    defaults
libsodium                 1.0.16               h3efe00b_0    defaults
libssh2                   1.8.0                ha12b0ac_4    defaults
libtiff                   4.0.9                hcb84e12_2    defaults
libxgboost                0.80                 hfc679d8_1    conda-forge
libxml2                   2.9.8                hab757c2_1    defaults
libxslt                   1.1.32               hb819dd2_0    defaults
llvm-openmp               4.0.1                hcfea43d_1    defaults
llvmlite                  0.26.0          py36h3fea490_1000    conda-forge
locket                    0.2.0                      py_2    conda-forge
lxml                      4.2.5            py36hc9114bc_0    conda-forge
lz4-c                     1.8.1.2              h1de35cc_0    anaconda
lzo                       2.10                 h362108e_2    defaults
markupsafe                1.1.0            py36h470a237_0    conda-forge
matplotlib                3.0.2                    py36_1    conda-forge
matplotlib-base           3.0.2            py36hb2d221d_1    conda-forge
mccabe                    0.6.1                      py_1    conda-forge
mistune                   0.8.4            py36h470a237_0    conda-forge
mkl                       2019.1                      144    defaults
mkl-service               1.1.2            py37h6b9c3cc_5    defaults
mkl_fft                   1.0.10                   py36_0    conda-forge
mkl_random                1.0.2                    py36_0    conda-forge
mock                      2.0.0                     <pip>
more-itertools            4.3.0                 py36_1000    conda-forge
mpc                       1.1.0                h6ef4df4_1    defaults
mpfr                      4.0.1                h3018a27_3    defaults
mpmath                    1.1.0                      py_0    conda-forge
msgpack-python            0.6.0            py36h2d50403_0    conda-forge
multipledispatch          0.6.0                      py_0    conda-forge
navigator-updater         0.2.1                    py36_0    defaults
nbconvert                 5.4.0                         1    conda-forge
nbformat                  4.4.0                      py_1    conda-forge
ncurses                   6.1                  h0a44026_0    defaults
networkx                  2.2                        py_1    conda-forge
nltk                      3.2.4                    py36_0    conda-forge
nose                      1.3.7                 py36_1002    conda-forge
notebook                  5.7.4                 py36_1000    conda-forge
numba                     0.39.0           py37h6440ff4_0    defaults
numexpr                   2.6.8            py37h1dc9127_0    defaults
numpy                     1.15.4           py36hacdab7b_0    defaults
numpy-base                1.15.4           py36h6575580_0    defaults
numpydoc                  0.8.0                      py_1    conda-forge
odo                       0.5.1                    py37_0    defaults
olefile                   0.46                       py_0    conda-forge
openpyxl                  2.5.12                     py_0    conda-forge
openssl                   1.1.1                h1de35cc_0    anaconda
packaging                 18.0                       py_0    conda-forge
pandas                    0.23.4           py36h6440ff4_0    anaconda
pandoc                    1.19.2.1             ha5e8f32_1    defaults
pandocfilters             1.4.2                      py_1    conda-forge
parso                     0.3.1                      py_0    conda-forge
partd                     0.3.9                      py_0    conda-forge
path.py                   11.5.0                     py_0    conda-forge
pathlib2                  2.3.3                 py36_1000    conda-forge
patsy                     0.5.1                    py36_0    anaconda
pbr                       5.1.1                     <pip>
pcre                      8.42                 h378b8a2_0    defaults
pep8                      1.7.1                      py_0    conda-forge
pexpect                   4.6.0                 py36_1000    conda-forge
pickleshare               0.7.5                 py36_1000    conda-forge
pillow                    5.3.0            py36hb68e598_0    defaults
pip                       18.1                  py36_1000    conda-forge
pkginfo                   1.4.2                      py_1    conda-forge
pluggy                    0.8.0                      py_0    conda-forge
ply                       3.11                       py_1    conda-forge
prometheus_client         0.5.0                      py_0    conda-forge
prompt_toolkit            2.0.7                      py_0    conda-forge
psutil                    5.4.8            py36h470a237_0    conda-forge
psycopg2                  2.7.6.1                   <pip>
ptyprocess                0.6.0                 py36_1000    conda-forge
py                        1.7.0                      py_0    conda-forge
py-lief                   0.9.0            py36hd4eaf27_0    defaults
py-xgboost                0.80             py36hfc679d8_1    conda-forge
pyasn1                    0.4.4                      py_1    conda-forge
pyasn1-modules            0.2.1                      py_0    conda-forge
pycodestyle               2.4.0                      py_1    conda-forge
pycosat                   0.6.3            py36h470a237_1    conda-forge
pycparser                 2.19                       py_0    conda-forge
pycrypto                  2.6.1            py36h470a237_2    conda-forge
pycurl                    7.43.0.2         py36ha12b0ac_0    defaults
pyflakes                  2.0.0                      py_0    conda-forge
pygments                  2.3.1                      py_0    conda-forge
pyhamcrest                1.9.0                      py_2    conda-forge
pylint                    2.2.2                 py36_1000    conda-forge
pyodbc                    4.0.25           py36hfc679d8_0    conda-forge
pyopenssl                 18.0.0                py36_1000    conda-forge
pyparsing                 2.3.0                      py_0    conda-forge
pyqt                      5.9.2            py36h655552a_2    defaults
pyrsistent                0.14.7           py36h470a237_0    conda-forge
pysocks                   1.6.8                 py36_1002    conda-forge
pytables                  3.4.4            py37h13cba08_0    defaults
pytest                    4.0.2                 py36_1000    conda-forge
pytest-arraydiff          0.2              py37h39e3cac_0    defaults
pytest-astropy            0.4.0                    py37_0    defaults
pytest-doctestplus        0.1.3                    py37_0    defaults
pytest-openfiles          0.3.1                      py_0    conda-forge
pytest-remotedata         0.3.1                      py_0    conda-forge
python                    3.6.7                haf84260_0    defaults
python-dateutil           2.7.5                      py_0    conda-forge
python-libarchive-c       2.8                   py36_1004    conda-forge
python.app                1.2             py36h470a237_200    conda-forge
pytz                      2018.7                     py_0    conda-forge
pywavelets                1.0.0            py37h1d22016_0    defaults
pyyaml                    3.13             py36h470a237_1    conda-forge
pyzmq                     17.1.2           py36hae99301_1    conda-forge
qt                        5.9.7                h468cd18_1    defaults
qtawesome                 0.5.3              pyh8a2030e_0    conda-forge
qtconsole                 4.4.3                      py_0    conda-forge
qtpy                      1.5.2              pyh8a2030e_0    conda-forge
readline                  7.0                  h1de35cc_5    defaults
requests                  2.21.0                py36_1000    conda-forge
rope                      0.10.7                     py_1    conda-forge
ruamel_yaml               0.15.71          py36h470a237_0    conda-forge
scikit-image              0.14.0           py37h0a44026_1    defaults
scikit-learn              0.20.1           py36h4f467ca_0    anaconda
scipy                     1.1.0            py36h1410ff5_2    defaults
seaborn                   0.9.0                    py36_0    anaconda
send2trash                1.5.0                      py_0    conda-forge
service_identity          17.0.0                     py_0    conda-forge
setuptools                40.6.3                   py36_0    conda-forge
simplegeneric             0.8.1                      py_1    conda-forge
singledispatch            3.4.0.3               py36_1000    conda-forge
sip                       4.19.8           py36hfc679d8_0    conda-forge
six                       1.12.0                py36_1000    conda-forge
snappy                    1.1.7                he62c110_3    defaults
snowballstemmer           1.2.1                      py_1    conda-forge
sortedcollections         1.0.1                      py_1    conda-forge
sortedcontainers          2.1.0                      py_0    conda-forge
sphinx                    1.8.2                 py36_1000    conda-forge
sphinxcontrib             1.0                      py36_1    defaults
sphinxcontrib-websupport  1.1.0                      py_1    conda-forge
spyder                    3.3.2                    py36_0    defaults
spyder-kernels            0.3.0                    py36_0    defaults
sqlalchemy                1.2.15           py36h470a237_0    conda-forge
sqlite                    3.25.3               ha441bb4_0    anaconda
statsmodels               0.9.0            py36h1d22016_0    anaconda
sympy                     1.3                   py36_1000    conda-forge
tblib                     1.3.2                      py_1    conda-forge
terminado                 0.8.1                 py36_1001    conda-forge
testpath                  0.4.2                 py36_1000    conda-forge
tk                        8.6.8                ha441bb4_0    defaults
toolz                     0.9.0                      py_1    conda-forge
tornado                   5.1.1            py36h470a237_0    conda-forge
tqdm                      4.28.1                     py_0    conda-forge
traitlets                 4.3.2                 py36_1000    conda-forge
twisted                   17.5.0                   py36_0    anaconda
typed-ast                 1.1.1            py36h470a237_0    conda-forge
unicodecsv                0.14.1                     py_1    conda-forge
unixodbc                  2.3.7                h1de35cc_0    defaults
urllib3                   1.24.1                py36_1000    conda-forge
wcwidth                   0.1.7                      py_1    conda-forge
webencodings              0.5.1                      py_1    conda-forge
werkzeug                  0.14.1                     py_0    conda-forge
wheel                     0.32.3                   py36_0    conda-forge
widgetsnbextension        3.4.2                 py36_1000    conda-forge
wrapt                     1.10.11          py36h470a237_1    conda-forge
wrds                      3.0.6                     <pip>
wurlitzer                 1.0.2                    py36_0    defaults
xgboost                   0.80             py36hfc679d8_1    conda-forge
xlrd                      1.2.0                      py_0    conda-forge
xlsxwriter                1.1.2                      py_0    conda-forge
xlwings                   0.15.1                   py36_0    conda-forge
xlwt                      1.3.0                      py_1    conda-forge
xz                        5.2.4                h1de35cc_4    defaults
yaml                      0.1.7                hc338f04_2    defaults
zeromq                    4.2.5                h0a44026_1    defaults
zict                      0.1.3                      py_0    conda-forge
zlib                      1.2.11               hf3cbc9b_2    defaults
zope                      1.0                      py36_1    defaults
zope.interface            4.6.0            py36h470a237_0    conda-forge
zstd                      1.3.7                h5bba6e5_0    anaconda

```

</details>

**Comment by csoja** [comment]
You have a mix of conda-forge and defaults packages - as well as a few pip packages.  Did you install anything between when Navigator worked and when it did not?  Sometimes packages from different sources aren't quite compatible and can cause these types of issues.  
In the meantime, you can launch Spyder or Jupyter Notebook from a terminal. https://docs.anaconda.com/anaconda/user-guide/getting-started/#optional-launch-spyder-or-jupyter-notebook-from-the-command-line
