### ISSUE TITLE
Error when opening Anaconda Navigator

### ISSUE THREAD

**Issue by AKHughes1994** [ContinuumIO/anaconda-issues#10836]
When trying to open the anaconda navigator it get's stuck during "Loading Applications" and doesn't display any applications. Opening from a terminal using anaconda-navigator outputs the following error: 

/anaconda3/lib/python3.6/site-packages/anaconda_navigator/api/conda_api.py:1364: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f)
2019-04-16 16:04:30,190 - ERROR download_api._get_url:416
Expecting value: line 1 column 1 (char 0)

Traceback (most recent call last):
  File "/anaconda3/lib/python3.6/site-packages/anaconda_navigator/widgets/main_window.py", line 539, in setup
    self.post_setup(conda_data=conda_data)
  File "/anaconda3/lib/python3.6/site-packages/anaconda_navigator/widgets/main_window.py", line 576, in post_setup
    self.tab_home.setup(conda_data)
  File "/anaconda3/lib/python3.6/site-packages/anaconda_navigator/widgets/tabs/home.py", line 169, in setup
    self.set_applications(applications, packages)
  File "/anaconda3/lib/python3.6/site-packages/anaconda_navigator/widgets/tabs/home.py", line 204, in set_applications
    apps = self.api.process_apps(applications, prefix=self.current_prefix)
  File "/anaconda3/lib/python3.6/site-packages/anaconda_navigator/api/anaconda_api.py", line 888, in process_apps
    versions=[vsdata.get('productVersion')],
AttributeError: 'str' object has no attribute 'get'

I have tried updating anaconda and resetting the navigator. My OS: is Mac HighSierra 10.13.6

Any help will be appreciated.

**Comment by kendonB** [comment]
Possibly related, I get this on Windows 10 on a fresh install:

```
(base) C:\Users\kmbel>anaconda-navigator
C:\Users\kmbel\Anaconda3\lib\site-packages\anaconda_navigator\api\conda_api.py:1364: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f)
2019-05-04 08:30:01,682 - ERROR download_api._download:234
Invalid url https://www.anaconda.com/api/events

2019-05-04 08:30:01,838 - ERROR download_api._download:234
Invalid url https://www.anaconda.com/api/videos

2019-05-04 08:30:02,182 - ERROR download_api._download:234
Invalid url https://www.anaconda.com/api/webinars

2019-05-04 08:30:24,545 - ERROR download_api._download:234
Invalid url https://www.anaconda.com/api/events

2019-05-04 08:30:24,762 - ERROR download_api._download:234
Invalid url https://www.anaconda.com/api/videos

2019-05-04 08:30:25,368 - ERROR download_api._download:234
Invalid url https://www.anaconda.com/api/webinars
```
