### ISSUE TITLE
Anaconda on Mac OS 10.13.6 Spyder Crash on start up

### ISSUE THREAD

**Issue by Whismeril** [ContinuumIO/anaconda-issues#10834]
### Actual Behavior

Spyder doesn't start, the TraceBock is

Traceback (most recent call last): File "/Users/me/anaconda3/bin/spyder", line 7, in  from spyder.app.start import main File "/Users/me/anaconda3/lib/python3.6/site-packages/spyder/app/start.py", line 13, in  import zmq File "/Users/me/anaconda3/lib/python3.6/site-packages/zmq/__init__.py", line 47, in  from zmq import backend File "/Users/me/anaconda3/lib/python3.6/site-packages/zmq/backend/__init__.py", line 40, in  reraise(*exc_info) File "/Users/me/anaconda3/lib/python3.6/site-packages/zmq/utils/sixcerpt.py", line 34, in reraise raise value File "/Users/me/anaconda3/lib/python3.6/site-packages/zmq/backend/__init__.py", line 27, in  _ns = select_backend(first) File "/Users/me/anaconda3/lib/python3.6/site-packages/zmq/backend/select.py", line 26, in select_backend mod = __import__(name, fromlist=public_api) File "/Users/me/anaconda3/lib/python3.6/site-packages/zmq/backend/cython/__init__.py", line 6, in  from . import (constants, error, message, context, ImportError: dlopen(/Users/me/anaconda3/lib/python3.6/site-packages/zmq/backend/cython/error.cpython-36m-darwin.so, 2): Library not loaded: @rpath/libsodium.23.dylib Referenced from: /Users/me/anaconda3/lib/libzmq.5.dylib Reason: image not found

![Capture](https://user-images.githubusercontent.com/49691966/56230005-91827280-607b-11e9-9343-b68fa58d821f.png)

I've tried spyder --reset, uninstall spyder, downgrade, anything works

### Expected Behavior

Spyder should find his image to start

### Steps to Reproduce

only trying start Spyder

##### Anaconda or Miniconda version:

Anacono 1.9.7

##### Operating System:

Mac OS 10.13.6 

##### `conda info`

<details>

```
PASTE OUTPUT HERE:

```

</details>

##### `conda list --show-channel-urls`

<details>

```
PASTE OUTPUT HERE:

```

</details>

**Comment by dukeingreen** [comment]
Having the same problem trying to collect more info to help debug:
1) I am Using a iMac Mid 2010, what is your HW?
2) Same Os version 
3) If try to run from command line, I got an  error that is somehow variable but look like a certain number, ... "Line 4...."  and "@#" let me know if you have the same error.
4) If I uninstall Matplotlib from the environmnet Spyder starts.

please let me know, Tks
