### ISSUE TITLE
Problems Running Environment

### ISSUE THREAD

**Issue by Gargoyle709** [ContinuumIO/anaconda-issues#10846]
I have anaconda for linux installed on my Chromebook OS.  In the terminal I created an environment "my_test_run" and opened it with 
"conda activate my_test_run"
Then I typed anaconda-navigator
and the following error appears:

Traceback (most recent call last):
  File "/usr/local/conda3/envs/my_test_run/bin/anaconda-navigator", line 7, in <module>
    from anaconda_navigator.app.main import main
  File "/usr/local/conda3/envs/my_test_run/lib/python3.7/site-packages/anaconda_navigator/app/main.py", line 22, in <module>
    from anaconda_navigator.utils.conda import is_conda_available
  File "/usr/local/conda3/envs/my_test_run/lib/python3.7/site-packages/anaconda_navigator/utils/__init__.py", line 15, in <module>
    from qtpy.QtGui import QIcon
  File "/usr/local/conda3/envs/my_test_run/lib/python3.7/site-packages/qtpy/QtGui.py", line 21, in <module>
    from PyQt5.QtGui import *
ImportError: libGL.so.1: cannot open shared object file: No such file or directory

What I want is to open an environment and start writing and running python.  How do I do that?
conda info and conda list give me nothing.

**Comment by csoja** [comment]
Have you been able to successfully follow the directions here: https://docs.anaconda.com/anaconda/user-guide/getting-started/#write-a-python-program-using-anaconda-prompt-or-terminal ?
