### ISSUE TITLE
Navigator doesn't start

### ISSUE THREAD

**Issue by sho-87** [ContinuumIO/anaconda-issues#1086]
I've tried installing Anaconda (Python 2.7 64bit) on both Windows 10 and OSX El Capitan and on both operating systems when I click the icon/menu item for launching navigator nothing happens

On my Windows machine I tried launching from command prompt with `anaconda-navigator` and I get the following error:

```
Traceback (most recent call last):
  File "C:\Users\Simon\Anaconda2\Scripts\anaconda-navigator-script.py", line 5, in <module>
    sys.exit(anaconda_navigator.app.main.main())
  File "C:\Users\Simon\Anaconda2\lib\site-packages\anaconda_navigator\app\main.py", line 61, in main
    window = run_app(splash)
  File "C:\Users\Simon\Anaconda2\lib\site-packages\anaconda_navigator\app\main.py", line 29, in run_app
    window = MainWindow(splash=splash)
  File "C:\Users\Simon\Anaconda2\lib\site-packages\anaconda_navigator\widgets\main_window.py", line 127, in __init__
    self.api = AnacondaAPI()
  File "C:\Users\Simon\Anaconda2\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 404, in AnacondaAPI
    ANACONDA_API = _AnacondaAPI()
  File "C:\Users\Simon\Anaconda2\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 41, in __init__
    super(_AnacondaAPI, self).__init__()
  File "C:\Users\Simon\Anaconda2\lib\site-packages\anaconda_navigator\api\manager_api.py", line 36, in __init__
    self._client_api = ClientAPI()
  File "C:\Users\Simon\Anaconda2\lib\site-packages\anaconda_navigator\api\client_api.py", line 489, in ClientAPI
    CLIENT_API = _ClientAPI()
  File "C:\Users\Simon\Anaconda2\lib\site-packages\anaconda_navigator\api\client_api.py", line 78, in __init__
    self._anaconda_client_api = binstar_client.utils.get_server_api(
AttributeError: 'module' object has no attribute 'get_server_api'
```

I thought this was related to #1076 but in my case its not complaining about licenses

The steps I took to get here were:

1. Install Anaconda 4.1.1 (Python 2.7 64 bit) using the installer from the website
2. `conda update conda`
3. `conda update anaconda`
4. Click shortcut to navigator/run from command prompt

**Comment by ilanschnell** [comment]
Today, Anaconda 4.2.0 was released, which should fix this issue.
