### ISSUE TITLE
Cannot activate virtual environment in PyDev

### ISSUE THREAD

**Issue by jacobbaylesssmc** [ContinuumIO/anaconda-issues#10869]
### Actual Behavior
(Windows 10, using Pydev 7.2.0.201903251948 and conda v. 4.6.14)

When I follow the instructions shown in the Anaconda documentation for setting up Eclipse/Pydev: [(https://docs.anaconda.com/anaconda/user-guide/tasks/integration/eclipse-pydev/)]

I find that, although I have configured the correct python interpreter from my virtual environment to be used, the virtual environment is not activated. Therefore, imports of packages such as numpy fail with the error:

```
Traceback (most recent call last):
  File "path-to-my-python-script.py", line 30, in <module>
    import numpy as np
  File "C:\Python\envs\myenv\lib\site-packages\numpy\__init__.py", line 140, in <module>
    from . import _distributor_init
  File "C:\Python\envs\myenv\lib\site-packages\numpy\_distributor_init.py", line 34, in <module>
    from . import _mklinit
ImportError: DLL load failed: The specified module could not be found.
```

However, running the same script from the command line, I can import numpy successfully.

### Expected Behavior

I would expect that by following the documented instructions to set up my IDE with virtual environments, the import would work successfully. This was the case in previous versions, so I suspect the documentation is just out of date.

Would it be possible to update the documentation to correctly show how to use virtual environments with PyDev?

### Steps to Reproduce

Download and install the latest Eclipse and Pydev
Download and install Miniconda
Create a virtual environment with Python 3 and numpy installed
Configure that environment according to the documentation on Anaconda's website
Write a script that runs numpy
Run the script from the command line
Attempt to run the script from within Pydev

##### Anaconda or Miniconda version:

Miniconda 4.5.12.0

##### Operating System:

Windows 10

##### `conda info`

<details>

```
     active environment : base
    active env location : C:\Python
            shell level : 1
       user config file : C:\Users\Jacob\.condarc
 populated config files :
          conda version : 4.6.14
    conda-build version : not installed
         python version : 3.7.3.final.0
       base environment : C:\Python  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/win-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\Python\pkgs
                          C:\Users\Jacob\.conda\pkgs
                          C:\Users\Jacob\AppData\Local\conda\conda\pkgs
       envs directories : C:\Python\envs
                          C:\Users\Jacob\.conda\envs
                          C:\Users\Jacob\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.6.14 requests/2.21.0 CPython/3.7.3 Windows/10 Windows/10.0.17134
          administrator : True
             netrc file : None
           offline mode : False

```

</details>

##### `conda list --show-channel-urls`

<details>

```
# packages in environment at C:\Python:
#
# Name                    Version                   Build  Channel
asn1crypto                0.24.0                   py37_0    defaults
ca-certificates           2019.1.23                     0    defaults
certifi                   2019.3.9                 py37_0    defaults
cffi                      1.12.3           py37h7a1dbc1_0    defaults
chardet                   3.0.4                    py37_1    defaults
conda                     4.6.14                   py37_0    defaults
conda-env                 2.6.0                         1    defaults
console_shortcut          0.1.1                         3    defaults
cryptography              2.6.1            py37h7a1dbc1_0    defaults
idna                      2.8                      py37_0    defaults
menuinst                  1.4.16           py37he774522_0    defaults
openssl                   1.1.1b               he774522_1    defaults
pip                       19.0.3                   py37_0    defaults
pycosat                   0.6.3            py37hfa6e2cd_0    defaults
pycparser                 2.19                     py37_0    defaults
pyopenssl                 19.0.0                   py37_0    defaults
pysocks                   1.6.8                    py37_0    defaults
python                    3.7.3                h8c8aaf0_0    defaults
pywin32                   223              py37hfa6e2cd_1    defaults
requests                  2.21.0                   py37_0    defaults
ruamel_yaml               0.15.46          py37hfa6e2cd_0    defaults
setuptools                41.0.0                   py37_0    defaults
six                       1.12.0                   py37_0    defaults
sqlite                    3.28.0               he774522_0    defaults
urllib3                   1.24.1                   py37_0    defaults
vc                        14.1                 h0510ff6_4    defaults
vs2015_runtime            14.15.26706          h3a45250_0    defaults
wheel                     0.33.1                   py37_0    defaults
win_inet_pton             1.1.0                    py37_0    defaults
wincertstore              0.2                      py37_0    defaults
yaml                      0.1.7                hc54c509_2    defaults


```

</details>

**Comment by jacobbaylesssmc** [comment]
I've now determined how to make this work in Pydev. I think that it's still important to update the Conda documentation accordingly.


Following [Fabio's advice](https://www.brainwy.com/tracker/PyDev/946), here's what I did to make it work. (Using Windows 10).

First I opened up the Anaconda prompt and, assuming my virtual environment is named "myenv", I typed
> activate myenv
> path

This prints out the PATH that Conda is using. I compared that to the PATH that is printed out when I just open cmd.exe and write
> path

and I see that Conda has added several additional items, such as C:\Python\envs\myenv; C:\Python\envs\myenv\Library\usr\bin; etc.

Then I opened Eclipse, and in Preferences>PyDev>Interpreters>Python Interpreters, I selected the interpreter that I've configured for myenv, and clicked the "Environment" tab. Then I added a new variable, which I called PATH, and set its value to C:\Python\envs\myenv;C:\Python\envs\myenv\Library\.... etc, adding in all the items that I saw Anaconda had added.

Now numpy and everything else works from inside the IDE.

**Comment by csoja** [comment]
Thank you for the report and the information to fix the documentation!
