### ISSUE TITLE
Navigator Error: An unexpected error occurred on Navigator start-up Windows 10

### ISSUE THREAD

**Issue by senkaou** [ContinuumIO/anaconda-issues#10864]
I have Windows 10 and ones I tray to start anaconda I have the Following erreur

Navigator Error
An unexpected error occurred on Navigator start-up
Report
Please report this issue in the anaconda issue tracker 
Main Error

expected str, bytes or os.PathLike object, not NoneType

Traceback

Traceback (most recent call last):
  File "C:\Users\kaoutar\Anaconda3\lib\site-packages\anaconda_navigator\exceptions.py", line 75, in exception_handler
    return_value = func(*args, **kwargs)
  File "C:\Users\kaoutar\Anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 151, in start_app
    window = run_app(splash)
  File "C:\Users\kaoutar\Anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 65, in run_app
    window = MainWindow(splash=splash, tab_project=False)
  File "C:\Users\kaoutar\Anaconda3\lib\site-packages\anaconda_navigator\widgets\main_window.py", line 168, in __init__
    self.api = AnacondaAPI()
  File "C:\Users\kaoutar\Anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 2337, in AnacondaAPI
    ANACONDA_API = _AnacondaAPI()
  File "C:\Users\kaoutar\Anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 89, in __init__
    self._conda_api = CondaAPI()
  File "C:\Users\kaoutar\Anaconda3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 1773, in CondaAPI
    CONDA_API = _CondaAPI()
  File "C:\Users\kaoutar\Anaconda3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 353, in __init__
    self.sys_rc_path = join(self.ROOT_PREFIX, '.condarc')
  File "C:\Users\kaoutar\Anaconda3\lib\ntpath.py", line 76, in join
    path = os.fspath(path)
TypeError: expected str, bytes or os.PathLike object, not NoneType

**Comment by csoja** [comment]
It is most helpful when the information in the template is provided - particularly conda info and conda list --show-channel-urls
Some people have been able to "fix" similar issues by removing their .condarc file, so you may want to back it up, and try that.

**Comment by dmddmd** [comment]
I get the same error. Yesterday, it was the first time I clicked 'sign out' in jupyter notebook (before, I just closed the browser). After that, on every start of anaconda navigator, I get that error. Don't know if it has sth to do with that.

**Comment by hurtmenot271** [comment]
I have the same error, can you please give more percisely

**Comment by csoja** [comment]
In a terminal or in the anaconda command prompt - type "conda info" and copy/paste the output of that command into this issue.  Then, type "conda list --show-channel-urls" and copy/past the output of that command into this issue.  

From the output of "conda info"  you will see where your .condarc files are located (user config file :  ....
 populated config files :  .... )  Backup the current version under  a different name, like condarc.bak - and then remove the .condarc file.  Conda will run with its defaults if that file is not present.  This may or may not solve your problem - as there is insufficient information in the error report to say for sure what the issue is.

**Comment by awanadil** [comment]
i got the same error in window 7 .plz guide

**Comment by csoja** [comment]
Please see https://docs.anaconda.com/anaconda/navigator/troubleshooting/#navigator-error-on-start-up
