### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by Chumuming** [ContinuumIO/anaconda-issues#10871]
## Main error
Application <b>spyder</b> launch may have produced errors.
## Traceback
```
objc[47704]: Class RunLoopModeTracker is implemented in both /Users/mmchiou/anaconda/envs/myenv_0428_2019/lib/python3.6/site-packages/PyQt5/Qt/lib/QtCore.framework/Versions/5/QtCore (0x101e63120) and /Users/mmchiou/anaconda/envs/myenv_0428_2019/lib/libQt5Core.5.dylib (0x104f75a80). One of the two will be used. Which one is undefined.
Traceback (most recent call last):
  File "/Users/mmchiou/anaconda/envs/myenv_0428_2019/bin/spyder", line 11, in <module>
    sys.exit(main())
  File "/Users/mmchiou/anaconda/envs/myenv_0428_2019/lib/python3.6/site-packages/spyder/app/start.py", line 186, in main
    from spyder.app import mainwindow
  File "/Users/mmchiou/anaconda/envs/myenv_0428_2019/lib/python3.6/site-packages/spyder/app/mainwindow.py", line 90, in <module>
    from qtpy import QtWebEngineWidgets  # analysis:ignore
  File "/Users/mmchiou/anaconda/envs/myenv_0428_2019/lib/python3.6/site-packages/qtpy/QtWebEngineWidgets.py", line 22, in <module>
    from PyQt5.QtWebEngineWidgets import QWebEnginePage
ValueError: PyCapsule_GetPointer called with incorrect name

```
## System information
```
python: 3.6.1
language: en
os: Darwin;16.7.0;Darwin Kernel Version 16.7.0: Thu Jun 21 20:07:39 PDT 2018; root:xnu-3789.73.14~1/RELEASE_X86_64;x86_64;i386
version: 1.6.2
platform: osx-64
qt: 5.6.2
pyqt: 5.6.0
conda: 4.3.29
```

**Comment by csoja** [comment]
I'm not sure what is causing your error.  However, it looks like you are running very old software. I'd recommend updating conda and anaconda-navigator and spyder.  I'm going to close this - please open a new issue if you are still having problems with the latest Spyder, conda, and Anaconda-Navigator.
