### ISSUE TITLE
from . import _mklinit ImportError: DLL load failed: The specified module could not be found.

### ISSUE THREAD

**Issue by hn2** [ContinuumIO/anaconda-issues#10884]
Traceback (most recent call last):
  File "c:\Users\hanna\.vscode\extensions\ms-python.python-2019.4.12954\pythonFiles\ptvsd_launcher.py", line 43, in <module>
    main(ptvsdArgs)
  File "c:\Users\hanna\.vscode\extensions\ms-python.python-2019.4.12954\pythonFiles\lib\python\ptvsd\__main__.py", line 410, in main
    run()
  File "c:\Users\hanna\.vscode\extensions\ms-python.python-2019.4.12954\pythonFiles\lib\python\ptvsd\__main__.py", line 291, in run_file
    runpy.run_path(target, run_name='__main__')
  File "C:\Users\hanna\Anaconda3\lib\runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "C:\Users\hanna\Anaconda3\lib\runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "C:\Users\hanna\Anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "c:\Users\hanna\Google Drive\hannannussbaum\Data Science\TensorFlowTest.py", line 1, in <module>
    import tensorflow as tf
  File "C:\Users\hanna\Anaconda3\lib\site-packages\tensorflow\__init__.py", line 24, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "C:\Users\hanna\Anaconda3\lib\site-packages\tensorflow\python\__init__.py", line 47, in <module>
    import numpy as np
  File "C:\Users\hanna\Anaconda3\lib\site-packages\numpy\__init__.py", line 140, in <module>
    from . import _distributor_init
  File "C:\Users\hanna\Anaconda3\lib\site-packages\numpy\_distributor_init.py", line 34, in <module>
    from . import _mklinit
ImportError: DLL load failed: The specified module could not be found.

**Comment by msarahan** [comment]
Please see https://conda.io/projects/conda/en/latest/user-guide/troubleshooting.html#numpy-mkl-library-load-failed

**Comment by hn2** [comment]
I tried following the doc but could not find any MKL file in windows/system32

**Comment by smiglidigli** [comment]
Have apparently the same problem. Also no mkl files in system.

C:\Anaconda3\python.exe C:/Users/xxxxx/PycharmProjects/ServiceLandsatImages/index.py
Traceback (most recent call last):
  File "C:/Users/xxxxx/PycharmProjects/ServiceLandsatImages/index.py", line 3, in <module>
    import numpy as np
  File "C:\Anaconda3\lib\site-packages\numpy\__init__.py", line 140, in <module>
    from . import _distributor_init
  File "C:\Anaconda3\lib\site-packages\numpy\_distributor_init.py", line 34, in <module>
    from . import _mklinit
ImportError: DLL load failed: The specified module could not be found.

**Comment by jonascj** [comment]
I don't know if it is related, but I have this error https://i.imgur.com/e3UyE1h.png on a fresh installation of Windows 10, Python 3.7 64bit and "pip install matplotlib".

**Comment by DTasev** [comment]
On Windows 10 with Anaconda and Miniconda, both 3.7, I was seeing this error when trying to `import numpy`.

Solution: paths were missing from my `PATH`. Using the `Anaconda Prompt` fixed the issue. Then I copied the `anaconda` paths from `echo %PATH%`, and I can now run it everywhere, after adjusting the local `PATH`.

**Comment by SergeyTaras** [comment]
@DTasev Could you please explain spep by step which directories did you copy and where? I am face exactly Win 10 issue. Thank you in advance.

**Comment by DTasev** [comment]
@SergeyTaras If you open a normal `cmd`, and one from the Anaconda Prompt, do `echo %PATH%` in both - you'll see the Anaconda one has a lot more paths related to where you installed Anaconda, which allows it to find the correct DLLs.

If you copy those different paths, then you can set them in the normal `cmd` using `set PATH="%PATH%;<ones you copied from the Anaconda prompt...>"`. If you want to make them stick system wide you can [follow this](https://www.mathworks.com/matlabcentral/answers/94933-how-do-i-edit-my-system-path-in-windows#answer_104285), although personally I prefer to manually toggle the environment variables. Alternatively, reinstalling Anaconda and clicking the "Add to PATH" option, at some point in the installation, will do the same thing, but automatically.

**Comment by SergeyTaras** [comment]
@DTasev thank you. I will try your way. At first I was confused, because I have not realized that echo %PATH% in cmd and in Anaconda Prompt are different. Will come back soon with a result.

**Comment by SanctumZero** [comment]
1) I seem to have this problem if I try to import numpy when running a script in an environment that's **_not_** the base environment - mind you that my extra environment does have numpy installed, so you would expect numpy to work

2) As soon as I also install numpy in the base environment, the problem goes away

3) Upon deleting numpy from the base environment > the problem comes back

**Comment by willis936** [comment]
I have this same problem when trying to launch VSCode from the start menu.
No error when launching VSCode from anaconda.
No environments other than base.

**Comment by GreatGameDota** [comment]
> @SergeyTaras If you open a normal `cmd`, and one from the Anaconda Prompt, do `echo %PATH%` in both - you'll see the Anaconda one has a lot more paths related to where you installed Anaconda, which allows it to find the correct DLLs.
> 
> If you copy those different paths, then you can set them in the normal `cmd` using `set PATH="%PATH%;<ones you copied from the Anaconda prompt...>"` (don't put the `<` and `>` though!). If you want to make them stick system wide you can [follow this](https://www.mathworks.com/matlabcentral/answers/94933-how-do-i-edit-my-system-path-in-windows#answer_104285), although personally I prefer to manually toggle the environment variables. Alternatively, reinstalling Anaconda and clicking the "Add to PATH" option, at some point in the installation, will do the same thing, but automatically.

Thanks! I reinstalled Anaconda and selected the PATH option and everything worked!

**Comment by fedorg** [comment]
I fixed mine by setting an environment flag:
`CONDA_DLL_SEARCH_MODIFICATION_ENABLE=1`
This allegedly only works with a special build of python that you can get by running
`conda update -c defaults python`

[doc link](https://conda.io/projects/conda/en/latest/user-guide/troubleshooting.html#numpy-mkl-library-load-failed)
similar issue: #8561

**Comment by zzz123xyz** [comment]
> @SergeyTaras If you open a normal `cmd`, and one from the Anaconda Prompt, do `echo %PATH%` in both - you'll see the Anaconda one has a lot more paths related to where you installed Anaconda, which allows it to find the correct DLLs.
> 
> If you copy those different paths, then you can set them in the normal `cmd` using `set PATH="%PATH%;<ones you copied from the Anaconda prompt...>"` (don't put the `<` and `>` though!). If you want to make them stick system wide you can [follow this](https://www.mathworks.com/matlabcentral/answers/94933-how-do-i-edit-my-system-path-in-windows#answer_104285), although personally I prefer to manually toggle the environment variables. Alternatively, reinstalling Anaconda and clicking the "Add to PATH" option, at some point in the installation, will do the same thing, but automatically.

can not agree more. Only add the anaconda related paths is also fine

**Comment by bzm3r** [comment]
Just wanted to leave a comment for those who find this thread: the issues with finding the right DLL can be fixed by setting the environment variable `CONDA_DLL_SEARCH_MODIFICATION_ENABLE` to `1`. See; https://docs.conda.io/projects/conda/en/latest/user-guide/troubleshooting.html#numpy-mkl-library-load-failed

**Comment by ThomasAJ05** [comment]
I tried all of the above and nothing worked except for @SergeyTaras suggestion of 'adding paths'. I added the following to Environmental Variables > User variables for ME > Path AFTER existing paths.

C:\Users\ME\Anaconda3
C:\Users\ME\Anaconda3\Library\mingw-w64\bin
C:\Users\ME\Anaconda3\Library\usr\bin
C:\Users\ME\Anaconda3\Library\bin
C:\Users\ME\Anaconda3\Scripts
C:\Users\ME\Anaconda3\bin
C:\Users\ME\Anaconda3\condabin

Also, in case someone else finds this issue thread and is using Visual Studio Code, another thorny problem of VS Code not finding 'Conda' was also resolved. Tried many things for that issue also.

**Comment by anuragtr** [comment]
I was facing this issue on Windows 10 while using Pycharm(with virtual environment) with Anaconda-Python as base interpreter . Overcame by:
1. Uninstalling and re-installing Anaconda
2. While re-installing Anaconda, check the box which asks to 'put Anaconda on PATH env variable'(don't remember the exact wording) (re-installing is not straightforward, will have to troubleshoot using google - this link will help: https://docs.anaconda.com/anaconda/user-guide/troubleshooting/#windows-error-failed-to-create-anaconda-menus-or-failed-to-add-anaconda-to-the-system-path)
3. Select newly installed Anaconda-Python as base interpreter.
4. 'import numpy', 'import pandas' started working in Pycharm. The issue disappeared.

**Comment by gyher** [comment]
I have the same experience with the same issue. But I found the packages can be imported in terminal.
And while I enable the VS Code from Anaconda prompt. There was a change of my directory
diff --git a/.vscode/settings.json b/.vscode/settings.json
new file mode 100644
index 0000000..b18fe94
--- /dev/null
+++ b/.vscode/settings.json
@@ -0,0 +1,3 @@
+{
+    "python.pythonPath": "D:\\anaconda3\\python.exe"
+}
Obviously, the root cause in my case is caused by the environment path. So testing in the VS Code enabled via Anaconda prompt is a good idea. And thanks @willis936 .
