### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by Meimeiainaonao** [ContinuumIO/anaconda-issues#10894]
## Main error
Application <b>spyder</b> launch may have produced errors.
## Traceback
```
Traceback (most recent call last):
  File "/Users/mac/anaconda/lib/python3.6/site-packages/qtpy/QtWebEngineWidgets.py", line 22, in <module>
    from PyQt5.QtWebEngineWidgets import QWebEnginePage
ImportError: dlopen(/Users/mac/anaconda/lib/python3.6/site-packages/PyQt5/QtWebEngineWidgets.so, 2): Library not loaded: @rpath/libQt5WebEngineCore.5.dylib
  Referenced from: /Users/mac/anaconda/lib/python3.6/site-packages/PyQt5/QtWebEngineWidgets.so
  Reason: image not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/mac/anaconda/bin/spyder", line 6, in <module>
    sys.exit(spyder.app.start.main())
  File "/Users/mac/anaconda/lib/python3.6/site-packages/spyder/app/start.py", line 103, in main
    from spyder.app import mainwindow
  File "/Users/mac/anaconda/lib/python3.6/site-packages/spyder/app/mainwindow.py", line 92, in <module>
    from qtpy import QtWebEngineWidgets  # analysis:ignore
  File "/Users/mac/anaconda/lib/python3.6/site-packages/qtpy/QtWebEngineWidgets.py", line 26, in <module>
    from PyQt5.QtWebKitWidgets import QWebPage as QWebEnginePage
ModuleNotFoundError: No module named 'PyQt5.QtWebKitWidgets'

```
## System information
```
python: 3.6.1
language: en
os: Darwin;18.5.0;Darwin Kernel Version 18.5.0: Mon Mar 11 20:40:32 PDT 2019; root:xnu-4903.251.3~3/RELEASE_X86_64;x86_64;i386
version: 1.6.2
platform: osx-64
qt: 5.6.2
pyqt: 5.6.0
conda: 4.3.30
```

**Comment by csoja** [comment]
I'm not sure what is causing your error. However, it looks like you are running very old software. I'd recommend updating conda and anaconda-navigator and spyder. I'm going to close this - please open a new issue if you are still having problems with the latest Spyder, conda, and Anaconda-Navigator.
