### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by JohnOwnbyHibner** [ContinuumIO/anaconda-issues#10893]
I was using it, rebooted my computer and got this error.
I've been having an issue with it not loading requested packages from the Environment tab.

### Actual Behavior

Navigator Error
An unexpected error occurred on Navigator start-up

Report
Please report this issue in the anaconda issue tracker

Main Error
expected str, bytes or os.PathLike object, not NoneType
Traceback
Traceback (most recent call last):
  File "F:\Anaconda\lib\site-packages\anaconda_navigator\exceptions.py", line 75, in exception_handler
    return_value = func(*args, **kwargs)
  File "F:\Anaconda\lib\site-packages\anaconda_navigator\app\start.py", line 151, in start_app
    window = run_app(splash)
  File "F:\Anaconda\lib\site-packages\anaconda_navigator\app\start.py", line 65, in run_app
    window = MainWindow(splash=splash, tab_project=False)
  File "F:\Anaconda\lib\site-packages\anaconda_navigator\widgets\main_window.py", line 168, in __init__
    self.api = AnacondaAPI()
  File "F:\Anaconda\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 2337, in AnacondaAPI
    ANACONDA_API = _AnacondaAPI()
  File "F:\Anaconda\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 89, in __init__
    self._conda_api = CondaAPI()
  File "F:\Anaconda\lib\site-packages\anaconda_navigator\api\conda_api.py", line 1773, in CondaAPI
    CONDA_API = _CondaAPI()
  File "F:\Anaconda\lib\site-packages\anaconda_navigator\api\conda_api.py", line 353, in __init__
    self.sys_rc_path = join(self.ROOT_PREFIX, '.condarc')
  File "F:\Anaconda\lib\ntpath.py", line 76, in join
    path = os.fspath(path)
TypeError: expected str, bytes or os.PathLike object, not NoneType

I tried several times to open Anaconda, keep getting this error. I will try a reinstall later today.

**Comment by JohnOwnbyHibner** [comment]
I did a complete uninstall with a clean reinstall on another hard drive. Still same error.

**Comment by csoja** [comment]
It is most helpful when the information in the template is provided - particularly conda info and conda list --show-channel-urls
Some people have been able to "fix" similar issues by removing their .condarc file, so you may want to back it up, and try that.

**Comment by JohnOwnbyHibner** [comment]
Hi,

I’m unable to access any part of python right now due to the error. I looked for the file and only found a sample file.

**Comment by JohnOwnbyHibner** [comment]
This is the only thing coming up for the file:
![2019-05-07 08_52_53-C__Users_Reliance Login_ condarc - Notepad++](https://user-images.githubusercontent.com/35269053/57314100-d7908c00-70a5-11e9-82df-5618bf908ecd.png)

**Comment by JohnOwnbyHibner** [comment]
I deleted the .condarc file and now it is loading!
