### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by papaguita** [ContinuumIO/anaconda-issues#10890]
**Navigator Error**

An unexpected error occurred on Navigator start-up

**Report**

Please report this issue in the anaconda  issue tracker  

**Main Error**

expected str, bytes or os.PathLike object, not NoneType

**Traceback**

Traceback (most recent call last):
  File "C:\Users\vanessacarm\Anaconda3\lib\site-packages\anaconda_navigator\exceptions.py", line 75, in exception_handler
    return_value = func(*args, **kwargs)
  File "C:\Users\vanessacarm\Anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 151, in start_app
    window = run_app(splash)
  File "C:\Users\vanessacarm\Anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 65, in run_app
    window = MainWindow(splash=splash, tab_project=False)
  File "C:\Users\vanessacarm\Anaconda3\lib\site-packages\anaconda_navigator\widgets\main_window.py", line 168, in __init__
    self.api = AnacondaAPI()
  File "C:\Users\vanessacarm\Anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 2337, in AnacondaAPI
    ANACONDA_API = _AnacondaAPI()
  File "C:\Users\vanessacarm\Anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 89, in __init__
    self._conda_api = CondaAPI()
  File "C:\Users\vanessacarm\Anaconda3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 1767, in CondaAPI
    CONDA_API = _CondaAPI()
  File "C:\Users\vanessacarm\Anaconda3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 353, in __init__
    self.sys_rc_path = join(self.ROOT_PREFIX, '.condarc')
  File "C:\Users\vanessacarm\Anaconda3\lib\ntpath.py", line 76, in join
    path = os.fspath(path)
TypeError: expected str, bytes or os.PathLike object, not NoneType

**Comment by papaguita** [comment]
Hi everyone, I'm new to Python and I've been doing alright so far, but suddenly Anaconda Navigator doesn't launch anymore. I've done nothing in my PC to change whatever could lead this to occur, please help.

**Comment by csoja** [comment]
It is most helpful when the information in the template is provided - particularly conda info and conda list --show-channel-urls  (One Windows, it is best to run these commands in the Anaconda Prompt.)
Some people have been able to "fix" similar issues by removing their .condarc file, so you may want to back it up, and try that.

**Comment by papaguita** [comment]
Hi csoja, thank for helping me, I did't understand your suggestions fo  fix the issue but I'm coping the error roport from the prompt, hope this helps

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\cli\main.py", line
97, in main
        from ..activate import main as activator_main
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\activate.py", line
15, in <module>
        context.__init__()  # oOn import, context does not include SEARCH_PATH.
This line fixes that.
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\base\context.py", l
ine 239, in __init__
        argparse_args=argparse_args)
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\common\configuratio
n.py", line 722, in __init__
        self._set_search_path(search_path)
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\common\configuratio
n.py", line 728, in _set_search_path
        self._set_raw_data(load_file_configs(search_path))
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\common\configuratio
n.py", line 369, in load_file_configs
        raw_data = odict(kv for kv in chain.from_iterable(load_paths))
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\common\configuratio
n.py", line 369, in <genexpr>
        raw_data = odict(kv for kv in chain.from_iterable(load_paths))
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\common\configuratio
n.py", line 344, in _file_yaml_loader
        yield fullpath, YamlRawParameter.make_raw_parameters_from_file(fullpath)

      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\common\configuratio
n.py", line 332, in make_raw_parameters_from_file
        ruamel_yaml = yaml_load(fh)
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\common\serialize.py
", line 54, in yaml_load
        return yaml.load(string, Loader=yaml.RoundTripLoader, version="1.2")
      File "C:\ProgramData\Anaconda3\lib\site-packages\ruamel_yaml\main.py", lin
e 638, in load
        loader = Loader(stream, version, preserve_quotes=preserve_quotes)
      File "C:\ProgramData\Anaconda3\lib\site-packages\ruamel_yaml\loader.py", l
ine 59, in __init__
        Reader.__init__(self, stream, loader=self)
      File "C:\ProgramData\Anaconda3\lib\site-packages\ruamel_yaml\reader.py", l
ine 80, in __init__
        self.stream = stream  # type: Any  # as .read is called
      File "C:\ProgramData\Anaconda3\lib\site-packages\ruamel_yaml\reader.py", l
ine 125, in stream
        self.determine_encoding()
      File "C:\ProgramData\Anaconda3\lib\site-packages\ruamel_yaml\reader.py", l
ine 180, in determine_encoding
        self.update(1)
      File "C:\ProgramData\Anaconda3\lib\site-packages\ruamel_yaml\reader.py", l
ine 266, in update
        self.check_printable(data)
      File "C:\ProgramData\Anaconda3\lib\site-packages\ruamel_yaml\reader.py", l
ine 233, in check_printable
        'unicode', "special characters are not allowed")
    ruamel_yaml.reader.ReaderError: unacceptable character #x0000: special chara
cters are not allowed
      in "C:\Users\vanessacarm\.condarc", position 0

`$ C:\ProgramData\Anaconda3\Scripts\conda shell.cmd.exe activate activate C:\Pro
gramData\Anaconda3`

  environment variables:
                 CIO_TEST=<not set>
               CONDA_ROOT=C:\ProgramData\Anaconda3
                 HOMEPATH=\Users\vanessacarm
                     PATH=C:\ProgramData\Anaconda3;C:\ProgramData\Anaconda3\Libr
ary\mingw-w64\bi
                          n;C:\ProgramData\Anaconda3\Library\usr\bin;C:\ProgramD
ata\Anaconda3\Li
                          brary\bin;C:\ProgramData\Anaconda3\Scripts;C:\ProgramD
ata\Oracle\Java\
                          javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\Sys
tem32\Wbem;C:\WI
                          NDOWS\System32\WindowsPowerShell\v1.0\;C:\Program File
s (x86)\Windows
                          Live\Shared;C:\Users\vanessacarm\AppData\Local\Program
s\Microsoft VS
                          Code\bin
             PSMODULEPATH=C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules\
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>

     active environment : None
       user config file : C:\Users\vanessacarm\.condarc
 populated config files :
          conda version : 4.5.12
    conda-build version : 3.17.6
         python version : 3.7.1.final.0
       base environment : C:\ProgramData\Anaconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/win-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/win-64
                          https://repo.anaconda.com/pkgs/pro/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\ProgramData\Anaconda3\pkgs
                          C:\Users\vanessacarm\AppData\Local\conda\conda\pkgs
       envs directories : C:\ProgramData\Anaconda3\envs
                          C:\Users\vanessacarm\AppData\Local\conda\conda\envs
                          C:\Users\vanessacarm\.conda\envs
               platform : win-64
             user-agent : conda/4.5.12 requests/2.21.0 CPython/3.7.1 Windows/8.1
 Windows/6.3.9600
          administrator : False
             netrc file : None
           offline mode : False

**Comment by csoja** [comment]
'unicode', "special characters are not allowed")
ruamel_yaml.reader.ReaderError: unacceptable character #x0000: special chara
cters are not allowed
in "C:\Users\vanessacarm.condarc",

If you look at the error report carefully, it looks like there is a character that Navigator can't make sense of in your current .condarc file.  You should back that up  and then remove it (or just rename it to something that doesn't have .condarc in the name).  Based on the output of conda info, you'll find that file here:  C:\Users\vanessacarm\.condarc

HTH

**Comment by papaguita** [comment]
Hi csoja, many thanks. I've just removed the file from the directory and it now works fine but I find the PC a bit slower. Anyway, I very appreciate your help many thanks again.

**Comment by csoja** [comment]
Glad to hear it is working for you now.  We are continuing to work on improving conda performance - so you may see improvement in future updates.
