### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by NeoInHeart** [ContinuumIO/anaconda-issues#10904]
## Main error
Application <b>notebook</b> launch may have produced errors.
## Traceback
```
[E 11:02:23.816 NotebookApp] Exception while loading config file C:\Users\liang\.jupyter\jupyter_notebook_config.py
    Traceback (most recent call last):
      File "E:\ProgramData\Anaconda3\lib\site-packages\traitlets\config\application.py", line 562, in _load_config_files
        config = loader.load_config()
      File "E:\ProgramData\Anaconda3\lib\site-packages\traitlets\config\loader.py", line 457, in load_config
        self._read_file_as_dict()
      File "E:\ProgramData\Anaconda3\lib\site-packages\traitlets\config\loader.py", line 489, in _read_file_as_dict
        py3compat.execfile(conf_filename, namespace)
      File "E:\ProgramData\Anaconda3\lib\site-packages\ipython_genutils\py3compat.py", line 198, in execfile
        exec(compiler(f.read(), fname, 'exec'), glob, loc)
      File "C:\Users\liang\.jupyter\jupyter_notebook_config.py", line 102, in <module>
        webbrowser.register('chrome', None, GenericBrowser(u'C:\\Users\\liang\\AppData\\Local\\Google\\Chrome\\Application\\chrome.exe'))
    NameError: name 'GenericBrowser' is not defined
[I 11:02:25.006 NotebookApp] Serving notebooks from local directory: C:\Users\liang
[I 11:02:25.006 NotebookApp] 0 active kernels 
[I 11:02:25.006 NotebookApp] The Jupyter Notebook is running at: http://localhost:8888/?token=71511ad7c17733c0881e369c54d7df3a674d496684312fee
[I 11:02:25.006 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 11:02:25.016 NotebookApp]

**Comment by csoja** [comment]
Looks like you have an error in your Jupyter configuration file, but the Notebook was still able to run. This does not look to be an issue with Anaconda or Anaconda-Navigator.  I'd recommend the Jupyter documentation or issue tracker.
