### ISSUE TITLE
SQLite load_extension not loading Spatialite Extension

### ISSUE THREAD

**Issue by tacree-odot** [ContinuumIO/anaconda-issues#10926]
### Actual Behavior

When attempting to load the spatialite extension, I am receiving the error:

**sqlite3.OperationalError: The specified module could not be found.**

I have tried loading this extension multiple ways, and none of them seem to work.  See errors below in the output.

### Expected Behavior
The extension should load.  Note that I have verified that the spatialite dll is in the environment, I am printing it in the script below.   

### Steps to Reproduce

I have produced the following script to demonstrate the issue below:
```
import sqlite3
import sys
from ctypes import util, cdll

# Verify some of the loaded paths and libraries:
lib = util.find_library('spatialite')

print('loaded spatialite library: ', lib)

for p in sys.path:
    print(p)

SQL = """
        select AsWKT(ST_LineFromText('LINESTRING(540000 220000, 540000 221609)', 32123))
        """
connection = sqlite3.Connection(':memory:')
connection.enable_load_extension(True)
# connection.execute("SELECT load_extension('mod_spatialite')")

try:
    connection.load_extension("mod_spatialite")
except:
    print("load_extension(mod_spatialite) failed, Error: ", sys.exc_info()[1], "occured.")
    print('\n\nTry loading using the name of the dll (spatialite.dll)')
    connection.load_extension("spatialite")

with connection as conn:
    cur = conn.execute(SQL)
    results = cur.fetchall()

    for result in results:
        wkt = result[0]
        print(wkt)
```

**Script output:**

> loaded spatialite library:  ...\Continuum\anaconda3\envs\geodb37\Library\bin\spatialite.dll
> ...\python\conda-test\src
> ...\python\conda-test
> ...\python\conda-test\src
> ...\Continuum\anaconda3\envs\geodb37\python37.zip
> ...\Continuum\anaconda3\envs\geodb37\DLLs
> ...\Continuum\anaconda3\envs\geodb37\lib
> ...\Continuum\anaconda3\envs\geodb37
> ...\Continuum\anaconda3\envs\geodb37\lib\site-packages
> 
> load_extension(mod_spatialite) failed, Error:  The specified module could not be found.
>  occured.
> 
> 
> Try loading using the name of the dll (spatialite.dll)
> Traceback (most recent call last):
>   File "...python/conda-test/src/test_spatialite.py", line 21, in <module>
>     connection.load_extension("mod_spatialite")
> sqlite3.OperationalError: The specified module could not be found.
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File ".../python/conda-test/src/test_spatialite.py", line 25, in <module>
>     connection.load_extension("spatialite")
> sqlite3.OperationalError: The specified procedure could not be found.

##### Anaconda or Miniconda version:
Anaconda3-2019.03-Windows-x86_64

##### Operating System:
Windows 10

##### `conda info`
<details>

```
      active environment : geodb37
    active env location : C:\Users\tacree1\AppData\Local\Continuum\anaconda3\envs\geodb37
            shell level : 2
       user config file : C:\Users\tacree1\.condarc
 populated config files : C:\Users\tacree1\.condarc
          conda version : 4.6.14
    conda-build version : 3.17.8
         python version : 3.7.3.final.0
       base environment : C:\Users\tacree1\AppData\Local\Continuum\anaconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/win-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\Users\tacree1\AppData\Local\Continuum\anaconda3\pkgs
                          C:\Users\tacree1\.conda\pkgs
                          C:\Users\tacree1\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\tacree1\AppData\Local\Continuum\anaconda3\envs
                          C:\Users\tacree1\.conda\envs
                          C:\Users\tacree1\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.6.14 requests/2.21.0 CPython/3.7.3 Windows/10 Windows/10.0.16299
          administrator : False
             netrc file : None
           offline mode : False   
```

</details>

##### `conda list --show-channel-urls`

<details>

```

# packages in environment at ...\Local\Continuum\anaconda3\envs\geodb37:
#
# Name                    Version                   Build  Channel
attrs                     19.1.0                   py37_1    defaults
blas                      1.0                         mkl    defaults
bzip2                     1.0.6                hfa6e2cd_5    defaults
ca-certificates           2019.1.23                     0    defaults
certifi                   2019.3.9                 py37_0    defaults
click                     7.0                      py37_0    defaults
click-plugins             1.1.1                      py_0    defaults
cligj                     0.5.0                    py37_0    defaults
curl                      7.64.1               h2a8f88b_0    defaults
cycler                    0.10.0                   py37_0    defaults
descartes                 1.1.0                    py37_0    defaults
expat                     2.2.5                he025d50_0    defaults
fiona                     1.8.4            py37h22081e2_0    defaults
freetype                  2.9.1                ha9979f8_1    defaults
freexl                    1.0.5                hfa6e2cd_0    defaults
gdal                      2.3.3            py37hdf43c64_0    defaults
geopandas                 0.4.1                      py_0    defaults
geos                      3.7.1                h33f27b4_0    defaults
hdf4                      4.2.13               h712560f_2    defaults
hdf5                      1.10.4               h7ebc959_0    defaults
icc_rt                    2019.0.0             h0cc432a_1    defaults
icu                       58.2                 ha66f8fd_1    defaults
intel-openmp              2019.3                      203    defaults
jpeg                      9b                   hb83a4c4_2    defaults
kealib                    1.4.7                h07cbb95_6    defaults
kiwisolver                1.1.0            py37ha925a31_0    defaults
krb5                      1.16.1               hc04afaa_7    defaults
libboost                  1.67.0               hd9e427e_4    defaults
libcurl                   7.64.1               h2a8f88b_0    defaults
libgdal                   2.3.3                h10f50ba_0    defaults
libiconv                  1.15                 h1df5818_7    defaults
libkml                    1.3.0                he5f2a48_4    defaults
libnetcdf                 4.6.1                h411e497_2    defaults
libpng                    1.6.37               h2a8f88b_0    defaults
libpq                     11.2                 h3235a2c_0    defaults
libspatialindex           1.8.5                h6538335_2    defaults
libspatialite             4.3.0a              hc36aec2_19    defaults
libssh2                   1.8.2                h7a1dbc1_0    defaults
libtiff                   4.0.10               hb898794_2    defaults
libxml2                   2.9.9                h464c3ec_0    defaults
mapclassify               2.0.1                      py_0    defaults
matplotlib                3.0.3            py37hc8f65d3_0    defaults
mkl                       2019.3                      203    defaults
mkl_fft                   1.0.12           py37h14836fe_0    defaults
mkl_random                1.0.2            py37h343c172_0    defaults
munch                     2.3.2                    py37_0    defaults
numpy                     1.16.3           py37h19fb1c0_0    defaults
numpy-base                1.16.3           py37hc3f5095_0    defaults
openssl                   1.1.1b               he774522_1    defaults
pandas                    0.24.2           py37ha925a31_0    defaults
pcre                      8.43                 ha925a31_0    defaults
pip                       19.1.1                   py37_0    defaults
proj4                     5.2.0                ha925a31_1    defaults
psycopg2                  2.7.6.1          py37h7a1dbc1_0    defaults
pyparsing                 2.4.0                      py_0    defaults
pyproj                    1.9.6            py37h6782396_0    defaults
pyqt                      5.9.2            py37h6538335_2    defaults
python                    3.7.3                h8c8aaf0_1    defaults
python-dateutil           2.8.0                    py37_0    defaults
pytz                      2019.1                     py_0    defaults
qt                        5.9.7            vc14h73c81de_0    defaults
rtree                     0.8.3                    py37_0    defaults
scipy                     1.2.1            py37h29ff71c_0    defaults
setuptools                41.0.1                   py37_0    defaults
shapely                   1.6.4            py37h222a598_0    defaults
sip                       4.19.8           py37h6538335_0    defaults
six                       1.12.0                   py37_0    defaults
sqlalchemy                1.3.3            py37he774522_0    defaults
sqlite                    3.28.0               he774522_0    defaults
tk                        8.6.8                hfa6e2cd_0    defaults
tornado                   6.0.2            py37he774522_0    defaults
vc                        14.1                 h0510ff6_4    defaults
vs2015_runtime            14.15.26706          h3a45250_4    defaults
wheel                     0.33.4                   py37_0    defaults
wincertstore              0.2                      py37_0    defaults
xerces-c                  3.2.2                ha925a31_0    defaults
xz                        5.2.4                h2fa13f4_4    defaults
zlib                      1.2.11               h62dcd97_3    defaults
zstd                      1.3.7                h508b16e_0    defaults
```

</details>

**Comment by eigenjohnson** [comment]
I have this same problem - is there any progress?

**Comment by BigBaaadBob** [comment]
Same problem here. I've tried both the anaconda and the conda-forge channels for libspatialite and get the exact same result. Here's the result from `conda create -n test libspatialite python` using python 3.8.5.

Test code:
```
from ctypes import util
lib = util.find_library('spatialite')
print('spatialite library: ', lib)

import sys
for p in sys.path:
    print(p)

import sqlite3

connection = sqlite3.connect('geotest')
connection.enable_load_extension(True)

connection.load_extension('spatialite.dll')
```
And the results:

```
spatialite library:  C:\Users\witr\miniconda3\envs\test\Library\bin\spatialite.dll
C:\Users\witr\Documents\Python Scripts\geo
C:\Users\witr\miniconda3\envs\test\python38.zip
C:\Users\witr\miniconda3\envs\test\DLLs
C:\Users\witr\miniconda3\envs\test\lib
C:\Users\witr\miniconda3\envs\test
C:\Users\witr\miniconda3\envs\test\lib\site-packages
Traceback (most recent call last):
  File "geo.py", line 16, in <module>
    connection.load_extension('spatialite.dll')
sqlite3.OperationalError: The specified procedure could not be found.
```

**Comment by bradh** [comment]
This looks like the sqlite is possibly build without extension loading. Does it work with other extensions?

**Comment by BigBaaadBob** [comment]
@bradh , As far as I can tell, extension loading is enabled in current conda builds and it certainly seems to be trying to load the spatialite extension. I found anaconda bug reports indicating that it wasn't enabled in the past and that was fixed.  I don't know of a simple extension to load (I've looked some, but this is sort of out of my area of knowledge) but if you can suggest one, I'll try it.  

For others: this is being discussed in more detail on the [spatialite google group](https://groups.google.com/g/spatialite-users/c/ecEEpxbDROk/m/FtRWCmTSBwAJ).

**Comment by PMeira** [comment]
> I found anaconda bug reports indicating that it wasn't enabled in the past and that was fixed. I don't know of a simple extension to load (I've looked some, but this is sort of out of my area of knowledge) but if you can suggest one, I'll try it.

Good to know, I've been replacing their `sqlite3.dll` for a while. I did test with the conda DLL now and indeed it's capable of loading extensions. :)

Trying to reproduce @BigBaaadBob's comment with `conda create -n test libspatialite python`, indeed it doesn't work. The `spatialite.dll` installed doesn't contain `sqlite3_modspatialite_init`. That's probably the issue -- this is probably not the extension module version of Spatialite.

If I use my own build of Spatialite (more precisely of `mod_spatialite.dll`), it works as expected.

**Comment by PMeira** [comment]
After playing with this, I think there are multiple issues are play. 

1. From the SQLite docs:

> If your shared library ends up being named "YourCode.so" or "YourCode.dll" or "YourCode.dylib" as shown in the compiler examples above, then the correct entry point name would be "sqlite3_yourcode_init". 

So `sqlite3_spatialite_init` or `sqlite3_modspatialite_init` is indeed missing, would explain why it doesn't load on Windows. On Linux, the extension can be loaded from `mod_spatialite.so` (containing `sqlite3_modspatialite_init`), which is installed by the conda package along with `libspatialite.so`.

2. Depending on the Python version, the R-tree extension is not built in the Anaconda `sqlite3.dll`. It seems that at least Python 3.6 has this issue. I think the official CPython releases also don't include that.

3. Old `sqlite3.dll` from Anaconda (and I believe also from the official CPython distributions) wasn't built with extension support, so that's the original reason why nothing worked before.

4. There could be issues with old DLLs and Anaconda. IIRC, conda uses some custom code to set search paths, but I'm not sure what's the current situation.

**Comment by AL89** [comment]
Hi there!

I noticed this post and I thought that I might want to share my experience, since I also have been struggling with this issue.

I have been using both Anaconda Python and regular Python, which I like to call it. Regular Python is the official version from [python.org](python.org)
Initially, I really wanted to use regular Python, but I found that Anaconda Python was the right choice when dealing with Spatialite databases. However, I still got some issues when I manually tried to locate the extension `mod_spatialite.dll`, using the command `conn.load_extension(path/to/mod_spatialite.dll)`.

But now I finally got a workaround for both Anaconda Python and regular Python. The method is to switch the working directory temporarily using the `os` module. Because, for some reason, loading of the extension works better when the working directory is in the path of the spatialite extensions.

**Code example**
So, below is my code. I use two helper functions, the first one getting the path of the file, where the code is written and the second to locate the folder where the extensions (i.e. `mod_spatialite.dll`) are located. In this case, the extensions path is relatively close to the script file.

The third function returns a `DataFrame` (or `GeoDataFrame` if geometry is present), based on the input SQLite database and the input table name using the `sqlite_utils` module (you can use the `sqlite3` module as well). Or if you have written a SQL string, you can use that instead.

Notice where the working directory is changed with the `os.chdir()` statement and then later changes it again.

```
import os
from sqlite_utils import Database
import pandas as pd
import geopandas as gpd
from shapely import wkt

def get_caller_filepath():
    filepath = os.path.dirname(__file__)
    return os.path.abspath(filepath)

def get_spatialite_path(folder:str='SpatialiteBin'):
    filepath = get_caller_filepath()
    spatial_filepath = filepath + '\\' + folder
    return spatial_filepath

# @staticmethod
def GetTableSQL(db:Database|str,sqlQuery:str=None,tablename:str=None,columns:str|list='*',crs=25832,close_db=False) -> pd.DataFrame|gpd.GeoDataFrame:
    if isinstance(db,str):
        db = Database(db)

    if isinstance(columns,list):
        columns = ', '.join(columns)

    if sqlQuery:
        querySplit = sqlQuery.split(' ')
        tablename = querySplit[-1].strip(';')
    else:
        sqlQuery = f'SELECT {columns} FROM {tablename};'
    
    try:
        cur = db.conn.cursor()

        dfTable = pd.read_sql_query(sql=sqlQuery,con=db.conn,coerce_float=False)
        if 'geometry' in dfTable.columns:
            cwd = os.getcwd()
            spatialite_path = get_spatialite_path()
            os.chdir(spatialite_path)   # Temporarily switch working directory to Spatialite extensions path
            db.conn.enable_load_extension(True)
            db.conn.load_extension('mod_spatialite.dll')
            db.execute('SELECT InitSpatialMetaData(1);')
            sql_geom = f'SELECT astext({tablename}.geometry) AS geometry FROM {tablename};'
            cur.execute(sql_geom)
            geom = [wkt.loads(g[0]) for g in cur.fetchall()]
            dfTable = gpd.GeoDataFrame(dfTable,geometry=geom).set_crs(epsg=crs)
            os.chdir(cwd)       # Change the working directory back to original
    except (AttributeError,pd.errors.DatabaseError) as e:
        print(f'Table {tablename} could not be loaded: ', e)
    finally:
        if cur:
            cur.close()
        if close_db:
            db.close()

    return dfTable
```

With this method I can go back and use regular Python, but it also works with Anaconda Python.
