### ISSUE TITLE
Anaconda Navigator can't launch on macOS 

### ISSUE THREAD

**Issue by sudiptapaul1978** [ContinuumIO/anaconda-issues#10929]
When launching Anaconda Navigator from its icon in Launchpad, nothing happens. I have tried all the options mentioned in different posts like #9103 but nothing is working.  Below is my Conda Info and also the Traceback when trying to open the anaconda-navigator. Please help ...

Conda Info -

    (base) Sudiptas-MacBook-Air:~ Babui$ conda info

     active environment : base
     active env location : /Users/Babui/anaconda3
       shell level : 1
       user config file : /Users/Babui/.condarc
     populated config files : 
          conda version : 4.6.11
     conda-build version : 3.17.8
     python version : 3.7.3.final.0
     base environment : /Users/Babui/anaconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/osx-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/osx-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/osx-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /Users/Babui/anaconda3/pkgs
                          /Users/Babui/.conda/pkgs
       envs directories : /Users/Babui/anaconda3/envs
                          /Users/Babui/.conda/envs
               platform : osx-64
       user-agent : conda/4.6.11 requests/2.21.0 CPython/3.7.3 Darwin/13.4.0 OSX/10.9.5
                UID:GID : 501:20
             netrc file : None
           offline mode : False

Traceback when trying to open the anaconda-navigator

       (base) Sudiptas-MacBook-Air:~ Babui$ anaconda-navigator
       Traceback (most recent call last):
                File "/Users/Babui/anaconda3/lib/python3.7/site- packages/qtpy/__init__.py", line 202, in <module>
               from PySide import __version__ as PYSIDE_VERSION  # analysis:ignore
               ModuleNotFoundError: No module named 'PySide'

       During handling of the above exception, another exception occurred:

       Traceback (most recent call last):
              File "/Users/Babui/anaconda3/bin/anaconda-navigator", line 7, in <module>
                      from anaconda_navigator.app.main import main
              File "/Users/Babui/anaconda3/lib/python3.7/site-packages/anaconda_navigator/app/main.py", line 22, in <module>
                      from anaconda_navigator.utils.conda import is_conda_available
              File "/Users/Babui/anaconda3/lib/python3.7/site-packages/anaconda_navigator/utils/__init__.py", line 15, in <module>
                      from qtpy.QtGui import QIcon
              File "/Users/Babui/anaconda3/lib/python3.7/site-packages/qtpy/__init__.py", line 208, in <module>
                     raise PythonQtError('No Qt bindings could be found')
                     qtpy.PythonQtError: No Qt bindings could be found

**Comment by wouterpotters** [comment]
See this issue: https://github.com/ContinuumIO/anaconda-issues/issues/1606
