### ISSUE TITLE
Trouble mirroring anaconda-nb-extensions and wakari channels

### ISSUE THREAD

**Issue by sandhujasmine** [ContinuumIO/anaconda-issues#1093]
Attached is the error when client tried to mirror these channels:

[python errors.txt](https://github.com/ContinuumIO/anaconda-issues/files/490581/python.errors.txt)

Also posting relevant error below:
```
Syncing 19 packages on platform linux-32 to the "wakari" user account
File linux-32/nbdime-0.1.0-py34_0.tar.bz2 missing. (downloading)
[INFO:event] {'job_id': '                                    ', 'package_name': u'nbdime', 'watcher_ids': [ObjectId('57e53965cc7617ef86d8d42e')], 'via_login': u'wakari', 'via_id': ObjectId('57e53965cc7617ef86d8d42e'), 'auth': None, 'queue': 'default', 'package_id': ObjectId('57e56e19cc7617f55afff862'), 'version': u'0.1.0', 'actor_id': ObjectId('57e53965cc7617ef86d8d42e'), 'fs_id': ObjectId('57e581c7cc7617f75b1b7154'), 'time': datetime.datetime(2016, 9, 23, 19, 25, 59, 959311, tzinfo=<UTC>), 'action': 'mirror.conda.dist.create', 'seen': False, 'actor_login': u'wakari'}
[INFO:event] {'job_id': '                                    ', 'package_name': u'nbdime', 'watcher_ids': [ObjectId('57e53965cc7617ef86d8d42e')], 'via_login': u'wakari', 'via_id': ObjectId('57e53965cc7617ef86d8d42e'), 'auth': None, 'queue': 'default', 'package_id': ObjectId('57e56e19cc7617f55afff862'), 'version': u'0.1.0', 'actor_id': ObjectId('57e53965cc7617ef86d8d42e'), 'fs_id': ObjectId('57e581c7cc7617f75b1b7154'), 'time': datetime.datetime(2016, 9, 23, 19, 25, 59, 965247, tzinfo=<UTC>), 'action': 'mirror.conda.dist.create', 'seen': False, 'actor_login': u'wakari'}
File linux-32/nbdime-0.1.0-py35_1.tar.bz2 missing. (downloading)
[INFO:event] {'job_id': '                                    ', 'package_name': u'nbdime', 'watcher_ids': [ObjectId('57e53965cc7617ef86d8d42e')], 'via_login': u'wakari', 'via_id': ObjectId('57e53965cc7617ef86d8d42e'), 'auth': None, 'queue': 'default', 'package_id': ObjectId('57e56e19cc7617f55afff862'), 'version': u'0.1.0', 'actor_id': ObjectId('57e53965cc7617ef86d8d42e'), 'fs_id': ObjectId('57e581c8cc7617f75b1b7158'), 'time': datetime.datetime(2016, 9, 23, 19, 26, 0, 733308, tzinfo=<UTC>), 'action': 'mirror.conda.dist.create', 'seen': False, 'actor_login': u'wakari'}
[INFO:event] {'job_id': '                                    ', 'package_name': u'nbdime', 'watcher_ids': [ObjectId('57e53965cc7617ef86d8d42e')], 'via_login': u'wakari', 'via_id': ObjectId('57e53965cc7617ef86d8d42e'), 'auth': None, 'queue': 'default', 'package_id': ObjectId('57e56e19cc7617f55afff862'), 'version': u'0.1.0', 'actor_id': ObjectId('57e53965cc7617ef86d8d42e'), 'fs_id': ObjectId('57e581c8cc7617f75b1b7158'), 'time': datetime.datetime(2016, 9, 23, 19, 26, 0, 737658, tzinfo=<UTC>), 'action': 'mirror.conda.dist.create', 'seen': False, 'actor_login': u'wakari'}
File linux-32/nbdime-0.1.0-py34_1.tar.bz2 missing. (downloading)
Traceback (most recent call last):
  File "/home/anaconda-server/miniconda2/bin/anaconda-server-sync-conda", line 9, in <module>
    load_entry_point('binstar-server==2.20.2', 'console_scripts', 'anaconda-server-sync-conda')()
  File "/home/anaconda-server/miniconda2/lib/python2.7/site-packages/binstar/scripts/sync_conda_mirror.py", line 118, in main
    sync_conda(owner, platform_indexes, public=not opts.private, clean=opts.clean)
  File "/home/anaconda-server/miniconda2/lib/python2.7/site-packages/binstar/tasks/mirrors/sync_conda.py", line 107, in sync_conda
    sync_conda_package(owner, index, subdir, name, public=public)
  File "/home/anaconda-server/miniconda2/lib/python2.7/site-packages/binstar/tasks/mirrors/sync_conda.py", line 97, in sync_conda_package
    conda_file_upload(owner, package, release, subdir, info)
  File "/home/anaconda-server/miniconda2/lib/python2.7/site-packages/binstar/tasks/mirrors/sync_conda.py", line 38, in conda_file_upload
    fetch_pkg(info, dst_dir=tmp_dir)
  File "/home/anaconda-server/miniconda2/lib/python2.7/site-packages/binstar/conda/fetch.py", line 243, in fetch_pkg
    download(url, path, session=session, md5=info['md5'], urlstxt=True)
  File "/home/anaconda-server/miniconda2/lib/python2.7/site-packages/binstar/conda/fetch.py", line 291, in download
    raise RuntimeError(msg)
RuntimeError: Connection error: EOF occurred in violation of protocol (_ssl.c:590): https://conda.anaconda.org/t/an-d17091b1-0f0f-41bc-9803-974a7dab0881/anaconda-nb-extensions/linux-32/nbdime-0.1.0-py34_1.tar.bz2
```

I'll post the `wakari.yaml` file as soon as I receive it.

**Comment by sandhujasmine** [comment]
The client got further along. Here's the .condarc file:
```
channels:
- https://conda.anaconda.org/t/an-d17091b1-0f0f-41bc-9803-974a7dab0881/anaconda-nb-extensions
- https://conda.anaconda.org/wakari
platforms:
- linux-64
```

There's still an error when mirroring `wakari`. See below:
```
File linux-64/ipython-we-4.2-py34_14_ged8e42a.tar.bz2 missing. (downloading)
Traceback (most recent call last):
  File "/home/anaconda-server/miniconda2/bin/anaconda-server-sync-conda", line 9, in <module>
    load_entry_point('binstar-server==2.20.2', 'console_scripts', 'anaconda-server-sync-conda')()
  File "/home/anaconda-server/miniconda2/lib/python2.7/site-packages/binstar/scripts/sync_conda_mirror.py", line 118, in main
    sync_conda(owner, platform_indexes, public=not opts.private, clean=opts.clean)
  File "/home/anaconda-server/miniconda2/lib/python2.7/site-packages/binstar/tasks/mirrors/sync_conda.py", line 107, in sync_conda
    sync_conda_package(owner, index, subdir, name, public=public)
  File "/home/anaconda-server/miniconda2/lib/python2.7/site-packages/binstar/tasks/mirrors/sync_conda.py", line 97, in sync_conda_package
    conda_file_upload(owner, package, release, subdir, info)
  File "/home/anaconda-server/miniconda2/lib/python2.7/site-packages/binstar/tasks/mirrors/sync_conda.py", line 38, in conda_file_upload
    fetch_pkg(info, dst_dir=tmp_dir)
  File "/home/anaconda-server/miniconda2/lib/python2.7/site-packages/binstar/conda/fetch.py", line 243, in fetch_pkg
    download(url, path, session=session, md5=info['md5'], urlstxt=True)
  File "/home/anaconda-server/miniconda2/lib/python2.7/site-packages/binstar/conda/fetch.py", line 291, in download
    raise RuntimeError(msg)
RuntimeError: Connection error: EOF occurred in violation of protocol (_ssl.c:590): https://conda.anaconda.org/wakari/linux-64/ipython-we-4.2-py34_14_ged8e42a.tar.bz2
```

Here's the full file of errors [anaconda-wakari-errors.txt](https://github.com/ContinuumIO/anaconda-issues/files/496728/anaconda-wakari-errors.txt)

**Comment by bkreider** [comment]
Does it happen at random files or at the same file each time?

**Comment by csoja** [comment]
Issue moved to [ContinuumIO/cas-mirror #11](https://github.com/ContinuumIO/cas-mirror/issues/11) via [**ZenHub**](https://www.zenhub.com/)
