### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by 02061994** [ContinuumIO/anaconda-issues#10935]
### Actual Behavior
 Successfully installed Anaconda3-5.2.0 in Windows 7,but when i open Anaconda Navigator an unexpected error occurred on Navigator start-up and shows this message:

Navigator Error
An unexpected error occurred on Navigator start-up

Report
Please report this issue in the anaconda issue tracker

Main Error
expected str, bytes or os.PathLike object, not NoneType
Traceback
Traceback (most recent call last):
  File "D:\python\lib\site-packages\anaconda_navigator\exceptions.py", line 75, in exception_handler
    return_value = func(*args, **kwargs)
  File "D:\python\lib\site-packages\anaconda_navigator\app\start.py", line 150, in start_app
    window = run_app(splash)
  File "D:\python\lib\site-packages\anaconda_navigator\app\start.py", line 65, in run_app
    window = MainWindow(splash=splash, tab_project=False)
  File "D:\python\lib\site-packages\anaconda_navigator\widgets\main_window.py", line 163, in __init__
    self.api = AnacondaAPI()
  File "D:\python\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 2185, in AnacondaAPI
    ANACONDA_API = _AnacondaAPI()
  File "D:\python\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 89, in __init__
    self._conda_api = CondaAPI()
  File "D:\python\lib\site-packages\anaconda_navigator\api\conda_api.py", line 1714, in CondaAPI
    CONDA_API = _CondaAPI()
  File "D:\python\lib\site-packages\anaconda_navigator\api\conda_api.py", line 353, in __init__
    self.sys_rc_path = join(self.ROOT_PREFIX, '.condarc')
  File "D:\python\lib\ntpath.py", line 76, in join
    path = os.fspath(path)
TypeError: expected str, bytes or os.PathLike object, not NoneType

### Expected Behavior

Anaconda Navigator should open.

### Steps to Reproduce

The anaconda navigator was opening as well as working fine. Then i used LinearRegression function in python and it stopped working.

Anaconda version:
Anaconda3-5.2.0-Windows-x86_64.exe

Operating System:
Windows 7

**Comment by csoja** [comment]
It looks like .condarc file may have gotten corrupted.  I'd recommend removing it and trying to run Navigator again.  You can find the location of the .condarc file by using _conda info_ in the Anaconda Prompt.
