### ISSUE TITLE
Cannot start jupyter notebook in Anaconda prompt, DLL load failed

### ISSUE THREAD

**Issue by Vinaykumar111** [ContinuumIO/anaconda-issues#10957]
****I have installed Anaconda prompt recently, While i'm trying to start jupyter notebook in Anaconda prompt it is saying that DLL load failed. Please help with this issue.**
python version: 3.7.3
conda version: 4.6.11**
Traceback (most recent call last):
  File "C:\Users\vkumar479\AppData\Local\Continuum\anaconda3\lib\site-packages\notebook\services\sessions\sessionmanager.py", line 10, in <module>
    import sqlite3
  File "C:\Users\vkumar479\AppData\Local\Continuum\anaconda3\lib\sqlite3\__init__.py", line 23, in <module>
    from sqlite3.dbapi2 import *
  File "C:\Users\vkumar479\AppData\Local\Continuum\anaconda3\lib\sqlite3\dbapi2.py", line 27, in <module>
    from _sqlite3 import *
ImportError: DLL load failed: The specified procedure could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\vkumar479\AppData\Local\Continuum\anaconda3\Scripts\jupyter-notebook-script.py", line 6, in <module>
    from notebook.notebookapp import main
  File "C:\Users\vkumar479\AppData\Local\Continuum\anaconda3\lib\site-packages\notebook\notebookapp.py", line 86, in <module>
    from .services.sessions.sessionmanager import SessionManager
  File "C:\Users\vkumar479\AppData\Local\Continuum\anaconda3\lib\site-packages\notebook\services\sessions\sessionmanager.py", line 13, in <module>
    from pysqlite2 import dbapi2 as sqlite3
ModuleNotFoundError: No module named 'pysqlite2'

**Comment by iharshit009** [comment]
go to that folder where your anaconda dir is, and then open cmd there and run jupyter notebook.

**Comment by Vinaykumar111** [comment]
Thanks @iharshit009 it is working fine now.
