### ISSUE TITLE
Navigator Startup error

### ISSUE THREAD

**Issue by RobertJEdwards** [ContinuumIO/anaconda-issues#10962]
### Actual Behavior

Got this message when I started Navigator:
Navigator Error
An unexpected error occurred on Navigator start-up

Report
Please report this issue in the anaconda issue tracker

Main Error
expected str, bytes or os.PathLike object, not NoneType
Traceback
Traceback (most recent call last):
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_86\lib\site-packages\anaconda_navigator\exceptions.py", line 75, in exception_handler
    return_value = func(*args, **kwargs)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_86\lib\site-packages\anaconda_navigator\app\start.py", line 150, in start_app
    window = run_app(splash)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_86\lib\site-packages\anaconda_navigator\app\start.py", line 65, in run_app
    window = MainWindow(splash=splash, tab_project=False)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_86\lib\site-packages\anaconda_navigator\widgets\main_window.py", line 163, in __init__
    self.api = AnacondaAPI()
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_86\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 2185, in AnacondaAPI
    ANACONDA_API = _AnacondaAPI()
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_86\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 89, in __init__
    self._conda_api = CondaAPI()
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_86\lib\site-packages\anaconda_navigator\api\conda_api.py", line 1714, in CondaAPI
    CONDA_API = _CondaAPI()
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_86\lib\site-packages\anaconda_navigator\api\conda_api.py", line 353, in __init__
    self.sys_rc_path = join(self.ROOT_PREFIX, '.condarc')
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_86\lib\ntpath.py", line 76, in join
    path = os.fspath(path)
TypeError: expected str, bytes or os.PathLike object, not NoneType

### Expected Behavior

Navigator starts and runs

### Steps to Reproduce

Lauching Anaconda Navigator (Anaconda

##### Anaconda or Miniconda version:

5.2.2

##### Operating System:
Windows 10
##### `conda info`

"sing Anaconda Cloud api site https://api.anaconda.org
Current conda install:

             platform : win-32
        conda version : 4.0.5
  conda-build version : 1.20.0
       python version : 3.5.1.final.0
     requests version : 2.9.1
     root environment : C:\Users\Robert\Anaconda3  (writable)
  default environment : C:\Users\Robert\Anaconda3
     envs directories : C:\Users\Robert\Anaconda3\envs
        package cache : C:\Users\Robert\Anaconda3\pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/win-32/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/win-32/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : C:\Users\Robert\.condarc
    is foreign system : True

# NOTE:
#     root directory 'C:\Users\Robert\Anaconda3' is uninitialized

<details>

```
PASTE OUTPUT HERE:

```

</details>

##### `conda list --show-channel-urls`

<details>

```
PASTE OUTPUT HERE:

```

</details>

**Comment by Toshio-Futami** [comment]
I got same error today.
Please tell me how to solve this problem?
[Navigator Error.txt](https://github.com/ContinuumIO/anaconda-issues/files/3240384/Navigator.Error.txt)

**Comment by Toshio-Futami** [comment]
I solved this issue by the following process.
1) I found out ".condrc"file on root directory.
2) I tried to read this file by Brackets but couldn't read it with error.
3) I deleted this file because I thought this file was corrupted.
4) Finally I succeeded open Anaconda Navigator.
