### ISSUE TITLE
Anaconda Navigator does not start

### ISSUE THREAD

**Issue by millsgt** [ContinuumIO/anaconda-issues#10973]
### Actual Behavior
Anaconda Navigator does not start

### Expected Behavior
Anaconda Navigator starts normally

### Steps to Reproduce

Click to start Anaconda Navigator 2

##### Anaconda or Miniconda version:
Anaconda 2.

##### Operating System:
Win10

##### `conda info`
Main Error

string indices must be integers, not str

Traceback

Traceback (most recent call last):
  File "C:\Users\mills\Anaconda2\lib\site-packages\anaconda_navigator\exceptions.py", line 75, in exception_handler
    return_value = func(*args, **kwargs)
  File "C:\Users\mills\Anaconda2\lib\site-packages\anaconda_navigator\app\start.py", line 115, in start_app
    window = run_app(splash)
  File "C:\Users\mills\Anaconda2\lib\site-packages\anaconda_navigator\app\start.py", line 58, in run_app
    window = MainWindow(splash=splash)
  File "C:\Users\mills\Anaconda2\lib\site-packages\anaconda_navigator\widgets\main_window.py", line 160, in __init__
    self.api = AnacondaAPI()
  File "C:\Users\mills\Anaconda2\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 1205, in AnacondaAPI
    ANACONDA_API = _AnacondaAPI()
  File "C:\Users\mills\Anaconda2\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 65, in __init__
    self._conda_api = CondaAPI()
  File "C:\Users\mills\Anaconda2\lib\site-packages\anaconda_navigator\api\conda_api.py", line 1622, in CondaAPI
    CONDA_API = _CondaAPI()
  File "C:\Users\mills\Anaconda2\lib\site-packages\anaconda_navigator\api\conda_api.py", line 340, in __init__
    self.set_conda_prefix()
  File "C:\Users\mills\Anaconda2\lib\site-packages\anaconda_navigator\api\conda_api.py", line 489, in set_conda_prefix
    self.ROOT_PREFIX = info['root_prefix']
TypeError: string indices must be integers, not str

**Comment by csoja** [comment]
Often this error is seen when there is a problem with your .condarc file.  I'd recommend removing that file.  You can see where it is located by looking at the output of _conda info_  in the Anaconda Prompt.
