### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by sivaids** [ContinuumIO/anaconda-issues#10976]
## Main error
Application <b>notebook</b> launch may have produced errors.
## Traceback
```
[I 09:52:11.678 NotebookApp] Serving notebooks from local directory: C:\Users\Spin-Pc-4-SVLQ
[I 09:52:11.678 NotebookApp] 0 active kernels 
[I 09:52:11.678 NotebookApp] The Jupyter Notebook is running at: http://localhost:8888/?token=2d23a83a5477ed9752b8954f5c64bae0e894204107e481ba
[I 09:52:11.678 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 09:52:11.685 NotebookApp] 
    
    Copy/paste this URL into your browser when you connect for the first time,
    to login with a token:
        http://localhost:8888/?token=2d23a83a5477ed9752b8954f5c64bae0e894204107e481ba
[I 09:52:11.832 NotebookApp] Accepting one-time-token-authenticated connection from ::1
[E 09:52:12.051 NotebookApp] Failed to load kernel spec: 'python3'
    Traceback (most recent call last):
      File "D:\pysoftall\Anaconda3\lib\site-packages\notebook\services\kernelspecs\handlers.py", line 58, in get
        d = kernelspec_model(self, kernel_name)
      File "D:\pysoftall\Anaconda3\lib\site-packages\notebook\services\kernelspecs\handlers.py", line 22, in kernelspec_model
        spec = ksm.get_kernel_spec(name)
      File "D:\pysoftall\Anaconda3\lib\site-packages\jupyter_client\kernelspec.py", line 205, in get_kernel_spec
        return self._get_kernel_spec_by_name(kernel_name, resource_dir)
      File "D:\pysoftall\Anaconda3\lib\site-packages\jupyter_client\kernelspec.py", line 192, in _get_kernel_spec_by_name
        return self.kernel_spec_class.from_resource_dir(resource_dir)
      File "D:\pysoftall\Anaconda3\lib\site-packages\jupyter_client\kernelspec.py", line 40, in from_resource_dir
        kernel_dict = json.load(f)
      File "D:\pysoftall\Anaconda3\lib\json\__init__.py", line 299, in load
        parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
      File "D:\pysoftall\Anaconda3\lib\json\__init__.py", line 354, in loads
        return _default_decoder.decode(s)
      File "D:\pysoftall\Anaconda3\lib\json\decoder.py", line 339, in decode
        obj, end = self.raw_decode(s, idx=_w(s, 0).end())
      File "D:\pysoftall\Anaconda3\lib\json\decoder.py", line 355, in raw_decode
        obj, end = self.scan_once(s, idx)
    json.decoder.JSONDecodeError: Invalid \escape: line 3 column 6 (char 18)

```
## System information
```
python: 3.6.1
language: en_US
os: Windows;10;10.0.17134;AMD64;Intel64 Family 6 Model 142 Stepping 10, GenuineIntel
version: 1.6.2
platform: win-64
qt: 5.6.2
pyqt: 5.6.0
conda: 4.3.30
```

**Comment by csoja** [comment]
You have an old version of conda and I suspect many other packages.  Please update to the latest versions and submit a new issue report if you are still having trouble. 

https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-pkgs.html
