### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by ryamo** [ContinuumIO/anaconda-issues#10980]
## Main error
The following errors occurred:
## Traceback
```
PackageNotFoundError: Dependencies missing in current win-64 channels: 
  - rstudio ==1.1.456 -> fonts-anaconda
  - rstudio ==1.1.456 -> freetype >=2.9.1

Close matches found; did you mean one of these?

    fonts-anaconda: anaconda

(and similarly for the other packages)
```
## System information
```
python: 3.6.1
language: en_US
os: Windows;10;10.0.17134;AMD64;Intel64 Family 6 Model 94 Stepping 3, GenuineIntel
version: 1.6.2
platform: win-64
qt: 5.6.2
pyqt: 5.6.0
conda: 4.3.21
```

**Comment by sduvvuri81** [comment]
Navigator Error
An unexpected error occurred on Navigator start-up

Report
Please report this issue in the anaconda issue tracker

Main Error
expected str, bytes or os.PathLike object, not NoneType
Traceback
Traceback (most recent call last):
  File "C:\Users\srinivas\Anaconda3\lib\site-packages\anaconda_navigator\exceptions.py", line 75, in exception_handler
    return_value = func(*args, **kwargs)
  File "C:\Users\srinivas\Anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 151, in start_app
    window = run_app(splash)
  File "C:\Users\srinivas\Anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 65, in run_app
    window = MainWindow(splash=splash, tab_project=False)
  File "C:\Users\srinivas\Anaconda3\lib\site-packages\anaconda_navigator\widgets\main_window.py", line 168, in __init__
    self.api = AnacondaAPI()
  File "C:\Users\srinivas\Anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 2337, in AnacondaAPI
    ANACONDA_API = _AnacondaAPI()
  File "C:\Users\srinivas\Anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 89, in __init__
    self._conda_api = CondaAPI()
  File "C:\Users\srinivas\Anaconda3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 1767, in CondaAPI
    CONDA_API = _CondaAPI()
  File "C:\Users\srinivas\Anaconda3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 353, in __init__
    self.sys_rc_path = join(self.ROOT_PREFIX, '.condarc')
  File "C:\Users\srinivas\Anaconda3\lib\ntpath.py", line 76, in join
    path = os.fspath(path)
TypeError: expected str, bytes or os.PathLike object, not NoneType

**Comment by csoja** [comment]
These are two different issues.  The first is a conflict with the packages in the environment where @ryamo is attempting to install RStudio.  I'd recommend creating a new environment and installing RStudio and the other packages you need into that environment.

The second issue - it is unclear because not all the necessary information is included to diagnose the problem - but often people that report issues like @sduvvuri81 has find that if they remove the .condarc file, the problem goes away.  However, if you have customized your .condarc file you will want to back it up/rename it before removing .condarc.   The output of _conda info_ in the anaconda prompt will list where the .condarc file(s) are located on your machine.
