### ISSUE TITLE
Unable to Launch Anaconda Navigator

### ISSUE THREAD

**Issue by sumitc29** [ContinuumIO/anaconda-issues#10982]
I am unable to launch anaconda navigator without any notification or error

Following are the things that I had tried.
1. Installing open SSL manually in my system
2. Reinstalling Anaconda 

**when tried to open navigator using prompt getting following error**
(base) C:\Users\sumitcha>anaconda-navigator
WARNING: The conda.compat module is deprecated and will be removed in a future release.
Traceback (most recent call last):
  File "C:\Users\sumitcha\AppData\Local\Continuum\anaconda3\Scripts\anaconda-navigator-script.py", line 10, in <module>
    sys.exit(main())
  File "C:\Users\sumitcha\AppData\Local\Continuum\anaconda3\lib\site-packages\anaconda_navigator\app\main.py", line 103, in main
    from anaconda_navigator.app.start import start_app
  File "C:\Users\sumitcha\AppData\Local\Continuum\anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 34, in <module>
    from anaconda_navigator.widgets.main_window import MainWindow
  File "C:\Users\sumitcha\AppData\Local\Continuum\anaconda3\lib\site-packages\anaconda_navigator\widgets\main_window.py", line 37, in <module>
    from anaconda_navigator.utils.analytics import GATracker
  File "C:\Users\sumitcha\AppData\Local\Continuum\anaconda3\lib\site-packages\anaconda_navigator\utils\analytics.py", line 44, in <module>
    from anaconda_navigator.external.UniversalAnalytics import Tracker
  File "C:\Users\sumitcha\AppData\Local\Continuum\anaconda3\lib\site-packages\anaconda_navigator\external\UniversalAnalytics\Tracker.py", line 28, in <module>

![image](https://user-images.githubusercontent.com/38399572/59009760-93cba680-884c-11e9-968c-647fedd7c306.png)

But I am able to import  "from urllib.request import HTTPHandler" in python

when I try ti Import "_ssl" it gives me following error
>>> import _ssl
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: DLL load failed: The specified procedure could not be found.

**_Please Help to resolve the issue_**

**Comment by csoja** [comment]
Can you please include the information requested in the issue template?  It is very important to be able to see the output from conda info and conda list --show-channel-urls
