### ISSUE TITLE
Importing the multiarray numpy extension module failed

### ISSUE THREAD

**Issue by KamarajuKusumanchi** [ContinuumIO/anaconda-issues#10992]
### Actual Behavior
The numpy package downloaded from Anaconda gives an error when trying to import it from pycharm IDE. If the packages are downloaded using pip, then there is no problem. The error during import is

```
Python 2.7.16 |Anaconda, Inc.| (default, Mar 14 2019, 15:42:17) [MSC v.1500 64 bit (AMD64)] on win32
>>> import numpy as np
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "C:\ProgramData\App-V\A15E630E-8600-4CAC-B2B5-1961F64A2DD0\922CB10C-6053-4412-9CBE-EBD3E92E1C71\Root\VFS\ProgramFilesX64\JETBRAINS\PYCHARM COMMUNITY EDITION 2018.1.1\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 20, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "C:\ProgramData\Continuum\Anaconda\envs\numpy_issue\lib\site-packages\numpy\__init__.py", line 142, in <module>
    from . import core
  File "C:\ProgramData\App-V\A15E630E-8600-4CAC-B2B5-1961F64A2DD0\922CB10C-6053-4412-9CBE-EBD3E92E1C71\Root\VFS\ProgramFilesX64\JETBRAINS\PYCHARM COMMUNITY EDITION 2018.1.1\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 20, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "C:\ProgramData\Continuum\Anaconda\envs\numpy_issue\lib\site-packages\numpy\core\__init__.py", line 71, in <module>
    raise ImportError(msg)
ImportError: 
IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!
Importing the multiarray numpy extension module failed.  Most
likely you are trying to import a failed build of numpy.
Here is how to proceed:
- If you're working with a numpy git repository, try `git clean -xdf`
  (removes all files not under version control) and rebuild numpy.
- If you are simply trying to use the numpy version that you have installed:
  your installation is broken - please reinstall numpy.
- If you have already reinstalled and that did not fix the problem, then:
  1. Check that you are using the Python you expect (you're using C:\ProgramData\Continuum\Anaconda\envs\numpy_issue\python.exe),
     and that you have no directories in your PATH or PYTHONPATH that can
     interfere with the Python and numpy versions you're trying to use.
  2. If (1) looks fine, you can open a new issue at
     https://github.com/numpy/numpy/issues.  Please include details on:
     - how you installed Python
     - how you installed numpy
     - your operating system
     - whether or not you have multiple versions of Python installed
     - if you built from source, your compiler versions and ideally a build log
     Note: this error has many possible causes, so please don't comment on
     an existing issue about this - open a new one instead.
Original error was: DLL load failed: The specified module could not be found.

```

### Expected Behavior

There should not be any errors when importing the package.

### Steps to Reproduce

Create an environment with the yml file

```
$ cat numpy_issue.yml
name: numpy_issue
channels:
  - defaults
dependencies:
  - python=2.7.16
  - numpy
```

`$ conda env create -f numpy_issue.yml`

Open Pycharm community edition 2018.1.1

Create a new project

Set the project interpreter and console interpreter

```
Settings -> Project:<project_name> -> Project Interpreter
Project Interpreter -> Settings button -> Add
Conda Environment -> Existing environment
```
Set the Interpreter to the one created above. In my case, the path is C:\ProgramData\Continuum\Anaconda\envs\numpy_issue\python.exe

`Make available to all projects -> check`

```
Settings -> Build, Execution, Deployment -> Console -> 
Python Console -> Python interpreter
```
Set to the same interpreter - C:\ProgramData\Continuum\Anaconda\envs\numpy_issue\python.exe

Now in pycharm window
start a python session by clicking on "Python Console"

Try to import numpy

```
Python 2.7.16 |Anaconda, Inc.| (default, Mar 14 2019, 15:42:17) [MSC v.1500 64 bit (AMD64)] on win32
>>> import numpy as np
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "C:\ProgramData\App-V\A15E630E-8600-4CAC-B2B5-1961F64A2DD0\922CB10C-6053-4412-9CBE-EBD3E92E1C71\Root\VFS\ProgramFilesX64\JETBRAINS\PYCHARM COMMUNITY EDITION 2018.1.1\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 20, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "C:\ProgramData\Continuum\Anaconda\envs\numpy_issue\lib\site-packages\numpy\__init__.py", line 142, in <module>
    from . import core
  File "C:\ProgramData\App-V\A15E630E-8600-4CAC-B2B5-1961F64A2DD0\922CB10C-6053-4412-9CBE-EBD3E92E1C71\Root\VFS\ProgramFilesX64\JETBRAINS\PYCHARM COMMUNITY EDITION 2018.1.1\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 20, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "C:\ProgramData\Continuum\Anaconda\envs\numpy_issue\lib\site-packages\numpy\core\__init__.py", line 71, in <module>
    raise ImportError(msg)
ImportError: 
IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!
Importing the multiarray numpy extension module failed.  Most
likely you are trying to import a failed build of numpy.
Here is how to proceed:
- If you're working with a numpy git repository, try `git clean -xdf`
  (removes all files not under version control) and rebuild numpy.
- If you are simply trying to use the numpy version that you have installed:
  your installation is broken - please reinstall numpy.
- If you have already reinstalled and that did not fix the problem, then:
  1. Check that you are using the Python you expect (you're using C:\ProgramData\Continuum\Anaconda\envs\numpy_issue\python.exe),
     and that you have no directories in your PATH or PYTHONPATH that can
     interfere with the Python and numpy versions you're trying to use.
  2. If (1) looks fine, you can open a new issue at
     https://github.com/numpy/numpy/issues.  Please include details on:
     - how you installed Python
     - how you installed numpy
     - your operating system
     - whether or not you have multiple versions of Python installed
     - if you built from source, your compiler versions and ideally a build log
     Note: this error has many possible causes, so please don't comment on
     an existing issue about this - open a new one instead.
Original error was: DLL load failed: The specified module could not be found.

```

##### Anaconda or Miniconda version:
```
$ conda --version
conda 4.6.14
```

##### Operating System:
Windows 7 Enterprise

##### `conda info`
<details>

```
$ conda info

     active environment : numpy_issue
    active env location : C:\ProgramData\Continuum\Anaconda\envs\numpy_issue
            shell level : 1
       user config file : C:\Users\kkusuman\.condarc
 populated config files : C:\Users\kkusuman\.condarc
          conda version : 4.6.14
    conda-build version : not installed
         python version : 2.7.16.final.0
       base environment : C:\ProgramData\Continuum\Anaconda  (writable)
           channel URLs : https://conda.anaconda.org/anaconda-fusion/win-64
                          https://conda.anaconda.org/anaconda-fusion/noarch
                          https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/win-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\ProgramData\Continuum\Anaconda\pkgs
                          C:\Users\kkusuman\.conda\pkgs
                          C:\Users\kkusuman\AppData\Local\conda\conda\pkgs
       envs directories : C:\ProgramData\Continuum\Anaconda\envs
                          C:\Users\kkusuman\.conda\envs
                          C:\Users\kkusuman\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.6.14 requests/2.21.0 CPython/2.7.16 Windows/7 Windows/6.1.7601
          administrator : False
             netrc file : None
           offline mode : False
```
</details>

##### `conda list --show-channel-urls`
<details>

```
$ conda list --show-channel-urls
# packages in environment at C:\ProgramData\Continuum\Anaconda\envs\numpy_issue:
#
# Name                    Version                   Build  Channel
blas                      1.0                         mkl    defaults
certifi                   2019.3.9                 py27_0    defaults
icc_rt                    2019.0.0             h0cc432a_1    defaults
intel-openmp              2019.4                      245    defaults
mkl                       2019.4                      245    defaults
mkl_fft                   1.0.12           py27h44c1dab_0    defaults
numpy                     1.16.3           py27h5fc8d92_0    defaults
numpy-base                1.16.3           py27hb1d0314_0    defaults
pip                       19.1.1                   py27_0    defaults
python                    2.7.16               hcb6e200_0    defaults
setuptools                41.0.1                   py27_0    defaults
sqlite                    3.28.0               h0c8e037_0    defaults
vc                        9                    h7299396_1    defaults
vs2008_runtime            9.00.30729.1         hfaea7d5_1    defaults
wheel                     0.33.4                   py27_0    defaults
wincertstore              0.2              py27hf04cefb_0    defaults
```

</details>

### What works instead

If numpy is downloaded directly from pip (as opposed to using conda), it works. Consider the following environment file

```
$ cat numpy_issue_workaround.yml
name: numpy_issue
channels:
  - defaults
dependencies:
  - python=2.7.16
  - pip:
    - numpy
```
Remove previous environment
`conda env remove --name numpy_issue`
Create it new
`conda env create -f numpy_issue_workaround.yml`

Now numpy can be imported in Pycharm's Console as
`import numpy as np`

##### `conda list --show-channel-urls`
<details>

```
$ conda list --show-channel-urls
# packages in environment at C:\ProgramData\Continuum\Anaconda\envs\numpy_issue:
#
# Name                    Version                   Build  Channel
certifi                   2019.3.9                 py27_0    defaults
numpy                     1.16.4                   pypi_0    pypi
pip                       19.1.1                   py27_0    defaults
python                    2.7.16               hcb6e200_0    defaults
setuptools                41.0.1                   py27_0    defaults
sqlite                    3.28.0               h0c8e037_0    defaults
vc                        9                    h7299396_1    defaults
vs2008_runtime            9.00.30729.1         hfaea7d5_1    defaults
wheel                     0.33.4                   py27_0    defaults
wincertstore              0.2              py27hf04cefb_0    defaults
```

</details>

**Comment by msarahan** [comment]
Update to a newer pycharm, or see https://conda.io/projects/conda/en/latest/user-guide/troubleshooting.html#numpy-mkl-library-load-failed
