### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by jskufca** [ContinuumIO/anaconda-issues#11018]
## Main error
Application <b>spyder</b> launch may have produced errors.
## Traceback
```
Traceback (most recent call last):
  File "Z:\ProgramData\Anaconda3\Scripts\spyder-script.py", line 10, in <module>
    sys.exit(main())
  File "Z:\ProgramData\Anaconda3\lib\site-packages\spyder\app\start.py", line 186, in main
    from spyder.app import mainwindow
  File "Z:\ProgramData\Anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 90, in <module>
    from qtpy import QtWebEngineWidgets  # analysis:ignore
  File "Z:\ProgramData\Anaconda3\lib\site-packages\qtpy\QtWebEngineWidgets.py", line 22, in <module>
    from PyQt5.QtWebEngineWidgets import QWebEnginePage
ValueError: PyCapsule_GetPointer called with incorrect name

```
## System information
```
python: 3.6.8
language: en_US
os: Windows;7;6.1.7601;AMD64;Intel64 Family 6 Model 15 Stepping 11, GenuineIntel
version: 1.6.2
platform: win-64
qt: 5.12.1
pyqt: 5.9.2
conda: 4.6.14
```

**Comment by csoja** [comment]
I'm not sure what is causing your error. However, it looks like you are running old software. I'd recommend updating conda and anaconda-navigator and spyder. I'm going to close this - please open a new issue if you are still having problems with the latest Spyder, conda, and Anaconda-Navigator.
