### ISSUE TITLE
Anaconda 3 Navigator error

### ISSUE THREAD

**Issue by eduardodisanti** [ContinuumIO/anaconda-issues#1102]
Error: spawn ENOENT
    at exports._errnoException (util.js:742:11)
    at Process.ChildProcess._handle.onexit (child_process.js:1027:32)
    at child_process.js:1110:20
    at process._tickCallback (node.js:279:11)

**Comment by eduardodisanti** [comment]
./launcher
[13285:0927/103934:INFO:CONSOLE(33)] ""Analytics is disabled"", source: file:///home/disaned/anaconda3/node-webkit/launcher/index.html (33)
[13285:0927/103934:WARNING:simple_index_file.cc(337)] Could not map Simple Index file.
[13285:0927/103934:INFO:CONSOLE(1)] ""ready"", source: file:///home/disaned/anaconda3/node-webkit/launcher/static/application.js (1)
[13285:0927/103934:INFO:CONSOLE(1)] ""initialize AppView"", source: file:///home/disaned/anaconda3/node-webkit/launcher/static/application.js (1)
[13285:0927/103934:INFO:CONSOLE(285)] ""RUNNING" ["info","--json"]", source: /home/disaned/anaconda3/node-webkit/launcher/node_modules/conda/conda.js (285)
[13285:0927/103934:INFO:CONSOLE(285)] ""RUNNING" ["info","--json"]", source: /home/disaned/anaconda3/node-webkit/launcher/node_modules/conda/conda.js (285)
[13285:0927/103934:INFO:CONSOLE(285)] ""RUNNING" ["info","--json"]", source: /home/disaned/anaconda3/node-webkit/launcher/node_modules/conda/conda.js (285)
[13285:0927/103934:INFO:CONSOLE(285)] ""RUNNING" ["info","--json"]", source: /home/disaned/anaconda3/node-webkit/launcher/node_modules/conda/conda.js (285)
[13285:0927/104059:INFO:CONSOLE(82)] "Uncaught Error: spawn ENOENT", source: events.js (82)
[13285:0927/104101:ERROR:browser_main_loop.cc(240)] Gtk: IA__gtk_widget_grab_focus: assertion 'GTK_IS_WIDGET (widget)' failed

**Comment by goanpeca** [comment]
You dont seem to be using Navigator, but the old and now deprecated launcher.

To install navigator you need to go to the command prompt and type

`conda install anaconda-navigator qtpy=1.0 qt=4.* pyqt=4.*` The command will be only

`conda install anaconda-navigator` when we release some fixes into our dependencies

Cheers
