### ISSUE TITLE
Cant open Spyder3.1.4

### ISSUE THREAD

**Issue by aaubry89** [ContinuumIO/anaconda-issues#11031]
### Actual Behavior

When I try to open Spyder 3.1.4 from the anaconda navigator, I get the following error message
`Traceback (most recent call last):
File "/Library/Frameworks/Python.framework/Versions/2.7/bin/spyder", line 10, in 
sys.exit(main())
File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/spyder/app/start.py", line 103, in main
from spyder.app import mainwindow
File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/spyder/app/mainwindow.py", line 49, in 
requirements.check_qt()
File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/spyder/requirements.py", line 39, in check_qt
import qtpy
File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/qtpy/__init__.py", line 208, in 
raise PythonQtError('No Qt bindings could be found')
qtpy.PythonQtError: No Qt bindings could be found
`

### Expected Behavior
Spyder should open

### Steps to Reproduce

typing anaconda-navigator in the command line and clicking on Spyder 

##### Anaconda or Miniconda version:
2

##### Operating System:
Mac OS 
##### `conda info`

<details>

```
 active environment : base
    active env location : /Users/tony/anaconda2
            shell level : 2
       user config file : /Users/tony/.condarc
 populated config files : /Users/tony/.condarc
          conda version : 4.6.14
    conda-build version : 3.17.8
         python version : 2.7.16.final.0
       base environment : /Users/tony/anaconda2  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/osx-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/osx-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/osx-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /Users/tony/anaconda2/pkgs
                          /Users/tony/.conda/pkgs
       envs directories : /Users/tony/anaconda2/envs
                          /Users/tony/.conda/envs
               platform : osx-64
             user-agent : conda/4.6.14 requests/2.22.0 CPython/2.7.16 Darwin/18.6.0 OSX/10.14.5
                UID:GID : 501:20
             netrc file : None
           offline mode : False


```

</details>

##### `conda list --show-channel-urls`

<details>

```
# Name                    Version                   Build  Channel
_ipyw_jlab_nb_ext_conf    0.1.0                    py27_0    defaults
_r-mutex                  1.0.0               anacondar_1    defaults
alabaster                 0.7.12                   py27_0    defaults
anaconda-client           1.7.2                    py27_0    defaults
anaconda-navigator        1.9.7                    py27_0    defaults
anaconda-project          0.8.2                    py27_0    defaults
appnope                   0.1.0            py27hb466136_0    defaults
appscript                 1.1.0            py27h1de35cc_0    defaults
asn1crypto                0.24.0                   py27_0    defaults
astroid                   1.6.5                    py27_0    defaults
astropy                   2.0.9            py27h1d22016_0    defaults
atomicwrites              1.3.0                    py27_1    defaults
attrs                     19.1.0                   py27_1    defaults
babel                     2.7.0                      py_0    defaults
backports                 1.0                        py_2    defaults
backports.functools_lru_cache 1.5                        py_2    defaults
backports.os              0.1.1                    py27_0    defaults
backports.shutil_get_terminal_size 1.0.0                    py27_2    defaults
backports.tempfile        1.0                        py_1    defaults
backports.weakref         1.0.post1                  py_1    defaults
backports_abc             0.5                        py_0    defaults
beautifulsoup4            4.7.1                    py27_1    defaults
bitarray                  0.9.3            py27h1de35cc_0    defaults
bkcharts                  0.2              py27haafc882_0    defaults
blas                      1.0                         mkl    defaults
bleach                    3.1.0                    py27_0    defaults
blosc                     1.16.3               hd9629dc_0    defaults
bokeh                     1.2.0                    py27_0    defaults
boto                      2.49.0                   py27_0    defaults
bottleneck                1.2.1            py27h1d22016_1    defaults
bwidget                   1.9.11                        1    defaults
bzip2                     1.0.6                h1de35cc_5    defaults
ca-certificates           2019.5.15                     0    defaults
cairo                     1.14.12              hc4e6be7_4    defaults
cctools                   895                           1    defaults
cdecimal                  2.3              py27h1de35cc_3    defaults
certifi                   2019.3.9                 py27_0    defaults
cffi                      1.12.3           py27hb5b8e2f_0    defaults
chardet                   3.0.4                    py27_1    defaults
clang                     4.0.1                         1    defaults
clang_osx-64              4.0.1               h1ce6c1d_16    defaults
clangxx                   4.0.1                         1    defaults
clangxx_osx-64            4.0.1               h22b1bf0_16    defaults
click                     7.0                      py27_0    defaults
cloudpickle               1.1.1                      py_0    defaults
clyent                    1.2.2                    py27_1    defaults
colorama                  0.4.1                    py27_0    defaults
compiler-rt               4.0.1                hcfea43d_1    defaults
conda                     4.6.14                   py27_0    defaults
conda-build               3.17.8                   py27_0    defaults
conda-env                 2.6.0                         1    defaults
conda-package-handling    1.3.9                    py27_0    defaults
conda-verify              3.4.2                      py_0    defaults
configparser              3.7.4                    py27_0    defaults
contextlib2               0.5.5            py27h9cb85f4_0    defaults
cryptography              2.7              py27ha12b0ac_0    defaults
curl                      7.64.1               ha441bb4_0    defaults
cycler                    0.10.0           py27hfc73c78_0    defaults
cyrus-sasl                2.1.26               hb48c43a_4    defaults
cython                    0.29.10          py27h0a44026_0    defaults
cytoolz                   0.9.0.1          py27h1de35cc_1    defaults
dask                      1.2.2                      py_0    defaults
dask-core                 1.2.2                      py_0    defaults
dbus                      1.13.6               h90a0687_0    defaults
decorator                 4.4.0                    py27_1    defaults
defusedxml                0.6.0                      py_0    defaults
distributed               1.28.1                   py27_0    defaults
docutils                  0.14             py27h0befae3_0    defaults
entrypoints               0.3                      py27_0    defaults
enum34                    1.1.6                    py27_1    defaults
et_xmlfile                1.0.1            py27hc42f929_0    defaults
expat                     2.2.6                h0a44026_0    defaults
fastcache                 1.1.0            py27h1de35cc_0    defaults
ffmpeg                    4.0                  h01ea3c9_0    defaults
filelock                  3.0.12                     py_0    defaults
flask                     1.0.3                    py27_0    defaults
font-ttf-dejavu-sans-mono 2.37                 h6964260_0    defaults
font-ttf-inconsolata      2.001                hcb22688_0    defaults
font-ttf-source-code-pro  2.030                h7457263_0    defaults
font-ttf-ubuntu           0.83                 h8b1ccd4_0    defaults
fontconfig                2.13.0               h5d5b041_1    defaults
fonts-anaconda            1                    h8fa9717_0    defaults
freetype                  2.9.1                hb4e5f40_0    defaults
fribidi                   1.0.5                h1de35cc_0    defaults
funcsigs                  1.0.2            py27hb9f6266_0    defaults
functools32               3.2.3.2                  py27_1    defaults
future                    0.17.1                   py27_0    defaults
futures                   3.2.0                    py27_0    defaults
get_terminal_size         1.0.0                h7520d66_0    defaults
gettext                   0.19.8.1             h15daf44_3    defaults
gevent                    1.4.0            py27h1de35cc_0    defaults
gfortran_osx-64           4.8.5                h22b1bf0_8    defaults
glib                      2.56.2               hd9629dc_0    defaults
glob2                     0.6                      py27_1    defaults
gmp                       6.1.2                hb37e062_1    defaults
gmpy2                     2.0.8            py27h6ef4df4_2    defaults
graphite2                 1.3.13               h2098e52_0    defaults
greenlet                  0.4.15           py27h1de35cc_0    defaults
grin                      1.2.1                    py27_4    defaults
gsl                       2.4                  h1de35cc_4    defaults
h5py                      2.8.0            py27h878fce3_3    defaults
harfbuzz                  1.8.8                hb8d4a28_0    defaults
hdf5                      1.10.2               hfa1e0ec_1    defaults
heapdict                  1.0.0                    py27_2    defaults
html5lib                  1.0.1                    py27_0    defaults
icu                       58.2                 h4b95b61_1    defaults
idna                      2.8                      py27_0    defaults
imageio                   2.5.0                    py27_0    defaults
imagesize                 1.1.0                    py27_0    defaults
importlib_metadata        0.17                     py27_1    defaults
intel-openmp              2019.4                      233    defaults
ipaddress                 1.0.22                   py27_0    defaults
ipykernel                 4.10.0                   py27_0    defaults
ipython                   5.8.0                    py27_0    defaults
ipython_genutils          0.2.0            py27h8b9a179_0    defaults
ipywidgets                7.4.2                    py27_0    defaults
isort                     4.3.20                   py27_0    defaults
itsdangerous              1.1.0                    py27_0    defaults
jasper                    2.0.14               h636a363_1    defaults
jbig                      2.1                  h4d881f8_0    defaults
jdcal                     1.4.1                      py_0    defaults
jedi                      0.13.3                   py27_0    defaults
jinja2                    2.10.1                   py27_0    defaults
jpeg                      9b                   he5867d9_2    defaults
jsonschema                3.0.1                    py27_0    defaults
jupyter                   1.0.0                    py27_7    defaults
jupyter_client            5.2.4                    py27_0    defaults
jupyter_console           5.2.0                    py27_1    defaults
jupyter_core              4.4.0                    py27_0    defaults
jupyterlab                0.33.11                  py27_0    defaults
jupyterlab_launcher       0.11.2           py27h28b3542_0    defaults
keyring                   18.0.0                   py27_0    defaults
kiwisolver                1.1.0            py27h0a44026_0    defaults
krb5                      1.16.1               hddcf347_7    defaults
lazy-object-proxy         1.4.1            py27h1de35cc_0    defaults
ld64                      274.2                         1    defaults
libarchive                3.3.3                h786848e_5    defaults
libcurl                   7.64.1               h051b688_0    defaults
libcxx                    4.0.1                hcfea43d_1    defaults
libcxxabi                 4.0.1                hcfea43d_1    defaults
libdb                     6.1.26               h0a44026_0    defaults
libedit                   3.1.20181209         hb402a30_0    defaults
libffi                    3.2.1                h475c297_4    defaults
libgfortran               3.0.1                h93005f0_2    defaults
libiconv                  1.15                 hdd342a3_7    defaults
liblief                   0.9.0                h2a1bed3_2    defaults
libntlm                   1.5                  h1de35cc_0    defaults
libopencv                 3.4.2                h7c891bd_1    defaults
libopus                   1.3                  h1de35cc_0    defaults
libpng                    1.6.37               ha441bb4_0    defaults
libsodium                 1.0.16               h3efe00b_0    defaults
libssh2                   1.8.2                ha12b0ac_0    defaults
libtiff                   4.0.10               hcb84e12_2    defaults
libvpx                    1.7.0                h378b8a2_0    defaults
libxml2                   2.9.9                hab757c2_0    defaults
libxslt                   1.1.33               h33a18ac_0    defaults
linecache2                1.0.0                    py27_0    defaults
llvm                      4.0.1                         1    defaults
llvm-lto-tapi             4.0.1                         1    defaults
llvm-openmp               4.0.1                hcfea43d_1    defaults
llvmlite                  0.29.0           py27h98b8051_0    defaults
locket                    0.2.0            py27ha10513d_1    defaults
lxml                      4.3.3            py27hef8c89e_0    defaults
lz4-c                     1.8.1.2              h1de35cc_0    defaults
lzo                       2.10                 h362108e_2    defaults
make                      4.2.1                h3efe00b_1    defaults
markupsafe                1.1.1            py27h1de35cc_0    defaults
matplotlib                2.2.3            py27h54f8f79_0    defaults
mccabe                    0.6.1                    py27_1    defaults
mistune                   0.8.4            py27h1de35cc_0    defaults
mkl                       2019.4                      233    defaults
mkl-service               2.0.2            py27h1de35cc_0    defaults
mkl_fft                   1.0.12           py27h5e564d8_0    defaults
mkl_random                1.0.2            py27h27c97d8_0    defaults
more-itertools            5.0.0                    py27_0    defaults
mpc                       1.1.0                h6ef4df4_1    defaults
mpfr                      4.0.1                h3018a27_3    defaults
mpmath                    1.1.0                    py27_0    defaults
msgpack-python            0.6.1            py27h04f5b5a_1    defaults
multipledispatch          0.6.0                    py27_0    defaults
navigator-updater         0.2.1                    py27_0    defaults
nbconvert                 5.5.0                      py_0    defaults
nbformat                  4.4.0            py27hddc86d0_0    defaults
ncurses                   6.1                  h0a44026_1    defaults
networkx                  2.2                      py27_1    defaults
nltk                      3.4.1                    py27_0    defaults
nose                      1.3.7                    py27_2    defaults
notebook                  5.7.8                    py27_0    defaults
numba                     0.44.1           py27h6440ff4_0    defaults
numexpr                   2.6.9            py27h7413580_0    defaults
numpy                     1.16.4           py27hacdab7b_0    defaults
numpy-base                1.16.4           py27h6575580_0    defaults
numpydoc                  0.9.1                      py_0    defaults
olefile                   0.46                     py27_0    defaults
opencv                    3.4.2            py27h6fd60c2_1    defaults
openjdk                   8.0.152              h393ad39_1    defaults
openpyxl                  2.6.2                      py_0    defaults
openssl                   1.1.1c               h1de35cc_1    defaults
packaging                 19.0                     py27_0    defaults
pandas                    0.24.2           py27h0a44026_0    defaults
pandoc                    2.2.3.2                       0    defaults
pandocfilters             1.4.2                    py27_1    defaults
pango                     1.42.4               h060686c_0    defaults
parso                     0.4.0                      py_0    defaults
partd                     0.3.10                   py27_1    defaults
path.py                   11.5.0                   py27_0    defaults
pathlib2                  2.3.3                    py27_0    defaults
patsy                     0.5.1                    py27_0    defaults
pcre                      8.43                 h0a44026_0    defaults
pep8                      1.7.1                    py27_0    defaults
pexpect                   4.7.0                    py27_0    defaults
pickleshare               0.7.5                    py27_0    defaults
pillow                    6.0.0            py27hb68e598_0    defaults
pip                       19.1.1                   py27_0    defaults
pixman                    0.38.0               h1de35cc_0    defaults
pkginfo                   1.5.0.1                  py27_0    defaults
pluggy                    0.12.0                     py_0    defaults
ply                       3.11                     py27_0    defaults
portaudio                 19.6.0               h41429eb_1    defaults
prometheus_client         0.6.0                    py27_0    defaults
prompt_toolkit            1.0.15           py27h4a7b9c2_0    defaults
psutil                    5.6.2            py27h1de35cc_0    defaults
ptyprocess                0.6.0                    py27_0    defaults
py                        1.8.0                    py27_0    defaults
py-lief                   0.9.0            py27h1413db1_2    defaults
py-opencv                 3.4.2            py27h7c891bd_1    defaults
pyaudio                   0.2.11           py27h1de35cc_1    defaults
pycodestyle               2.5.0                    py27_0    defaults
pycosat                   0.6.3            py27h1de35cc_0    defaults
pycparser                 2.19                     py27_0    defaults
pycrypto                  2.6.1            py27h1de35cc_9    defaults
pycurl                    7.43.0.2         py27ha12b0ac_0    defaults
pyflakes                  2.1.1                    py27_0    defaults
pygments                  2.4.2                      py_0    defaults
pylint                    1.9.2                    py27_0    defaults
pyodbc                    4.0.26           py27h0a44026_0    defaults
pyopenssl                 19.0.0                   py27_0    defaults
pyparsing                 2.4.0                      py_0    defaults
pyqt                      5.9.2            py27h655552a_2    defaults
pyrsistent                0.14.11          py27h1de35cc_0    defaults
pysocks                   1.7.0                    py27_0    defaults
pytables                  3.4.4            py27h13cba08_0    defaults
pytest                    4.6.2                    py27_0    defaults
python                    2.7.16               h97142e2_0    defaults
python-dateutil           2.8.0                    py27_0    defaults
python-libarchive-c       2.8                      py27_6    defaults
python.app                2                        py27_9    defaults
pytz                      2019.1                     py_0    defaults
pywavelets                1.0.3            py27h1d22016_1    defaults
pyyaml                    5.1              py27h1de35cc_0    defaults
pyzmq                     18.0.0           py27h0a44026_0    defaults
qt                        5.9.7                h468cd18_1    defaults
qtawesome                 0.5.7                    py27_1    defaults
qtconsole                 4.5.1                      py_0    defaults
qtpy                      1.7.1                      py_0    defaults
r-askpass                 1.0               r36h1de35cc_0    defaults
r-assertthat              0.2.1             r36h6115d3f_0    defaults
r-backports               1.1.4             r36h46e59ec_0    defaults
r-base                    3.6.0                hcb44179_0    defaults
r-base64enc               0.1_3             r36h46e59ec_4    defaults
r-bh                      1.69.0_1          r36h6115d3f_0    defaults
r-bindr                   0.1.1             r36h6115d3f_0    defaults
r-bindrcpp                0.2.2             r36h466af19_0    defaults
r-bit                     1.1_14            r36h46e59ec_0    defaults
r-bit64                   0.9_7             r36h46e59ec_0    defaults
r-bitops                  1.0_6             r36h46e59ec_4    defaults
r-blob                    1.1.1             r36h6115d3f_0    defaults
r-broom                   0.5.2             r36h6115d3f_0    defaults
r-catools                 1.17.1.2          r36h466af19_0    defaults
r-cellranger              1.1.0             r36h6115d3f_0    defaults
r-cli                     1.1.0             r36h6115d3f_0    defaults
r-clipr                   0.6.0             r36h6115d3f_0    defaults
r-config                  0.3               r36h6115d3f_0    defaults
r-crayon                  1.3.4             r36h6115d3f_0    defaults
r-curl                    3.3               r36h46e59ec_0    defaults
r-dbi                     1.0.0             r36h6115d3f_0    defaults
r-dbplyr                  1.4.0             r36h6115d3f_0    defaults
r-digest                  0.6.18            r36h46e59ec_0    defaults
r-dplyr                   0.8.0.1           r36h466af19_0    defaults
r-ellipsis                0.1.0             r36h46e59ec_0    defaults
r-evaluate                0.13              r36h6115d3f_0    defaults
r-fansi                   0.4.0             r36h46e59ec_0    defaults
r-forcats                 0.4.0             r36h6115d3f_0    defaults
r-forge                   0.2.0             r36h6115d3f_0    defaults
r-generics                0.0.2             r36h6115d3f_0    defaults
r-glue                    1.3.1             r36h46e59ec_0    defaults
r-haven                   2.1.0             r36h466af19_0    defaults
r-highr                   0.8               r36h6115d3f_0    defaults
r-hms                     0.4.2             r36h6115d3f_0    defaults
r-htmltools               0.3.6             r36h466af19_0    defaults
r-htmlwidgets             1.3               r36h6115d3f_0    defaults
r-httpuv                  1.5.1             r36h466af19_0    defaults
r-httr                    1.4.0             r36h6115d3f_0    defaults
r-jsonlite                1.6               r36h46e59ec_0    defaults
r-knitr                   1.22              r36h6115d3f_0    defaults
r-later                   0.8.0             r36h466af19_0    defaults
r-lattice                 0.20_38           r36h46e59ec_0    defaults
r-lazyeval                0.2.2             r36h46e59ec_0    defaults
r-magrittr                1.5               r36h6115d3f_4    defaults
r-markdown                0.9               r36h46e59ec_0    defaults
r-mime                    0.6               r36h46e59ec_0    defaults
r-miniui                  0.1.1.1           r36h6115d3f_0    defaults
r-mongolite               2.0.1             r36h46e59ec_0    defaults
r-nlme                    3.1_139           r36hfffe0aa_0    defaults
r-odbc                    1.1.5             r36h0a44026_0    defaults
r-openssl                 1.3               r36h46e59ec_0    defaults
r-packrat                 0.5.0             r36h6115d3f_0    defaults
r-pillar                  1.3.1             r36h6115d3f_0    defaults
r-pkgconfig               2.0.2             r36h6115d3f_0    defaults
r-pki                     0.1_5.1           r36h46e59ec_1    defaults
r-plogr                   0.2.0             r36h6115d3f_0    defaults
r-plyr                    1.8.4             r36h466af19_0    defaults
r-prettyunits             1.0.2             r36h6115d3f_0    defaults
r-profvis                 0.3.5             r36h46e59ec_0    defaults
r-progress                1.2.0             r36h6115d3f_0    defaults
r-promises                1.0.1             r36h466af19_0    defaults
r-purrr                   0.3.2             r36h46e59ec_0    defaults
r-r2d3                    0.2.3             r36h6115d3f_0    defaults
r-r6                      2.4.0             r36h6115d3f_0    defaults
r-rappdirs                0.3.1             r36h46e59ec_0    defaults
r-rcpp                    1.0.1             r36h466af19_0    defaults
r-rcurl                   1.95_4.12         r36h46e59ec_0    defaults
r-readr                   1.3.1             r36h466af19_0    defaults
r-readxl                  1.3.1             r36h466af19_0    defaults
r-rematch                 1.0.1             r36h6115d3f_0    defaults
r-reshape2                1.4.3             r36h466af19_0    defaults
r-rjava                   0.9_11            r36h46e59ec_0    defaults
r-rjdbc                   0.2_7.1           r36h6115d3f_0    defaults
r-rjsonio                 1.3_1.1           r36h466af19_0    defaults
r-rlang                   0.3.4             r36h46e59ec_0    defaults
r-rmarkdown               1.12              r36h6115d3f_0    defaults
r-rprojroot               1.3_2             r36h6115d3f_0    defaults
r-rsconnect               0.8.13            r36h6115d3f_0    defaults
r-rstudioapi              0.10              r36h6115d3f_0    defaults
r-shiny                   1.3.2             r36h6115d3f_0    defaults
r-sourcetools             0.1.7             r36h466af19_0    defaults
r-sparklyr                1.0.0             r36h6115d3f_0    defaults
r-stringi                 1.4.3             r36h466af19_0    defaults
r-stringr                 1.4.0             r36h6115d3f_0    defaults
r-sys                     3.2               r36h46e59ec_0    defaults
r-tibble                  2.1.1             r36h46e59ec_0    defaults
r-tidyr                   0.8.3             r36h466af19_0    defaults
r-tidyselect              0.2.5             r36h466af19_0    defaults
r-tinytex                 0.12              r36h6115d3f_0    defaults
r-utf8                    1.1.4             r36h46e59ec_0    defaults
r-withr                   2.1.2             r36h6115d3f_0    defaults
r-xfun                    0.6               r36h6115d3f_0    defaults
r-xml2                    1.2.0             r36h466af19_0    defaults
r-xtable                  1.8_4             r36h6115d3f_0    defaults
r-yaml                    2.2.0             r36h46e59ec_0    defaults
readline                  7.0                  h1de35cc_5    defaults
requests                  2.22.0                   py27_0    defaults
rope                      0.14.0                     py_0    defaults
rstudio                   1.1.456              h04f5b5a_1    defaults
ruamel_yaml               0.15.46          py27h1de35cc_0    defaults
scandir                   1.10.0           py27h1de35cc_0    defaults
scikit-image              0.14.2           py27h0a44026_0    defaults
scikit-learn              0.20.3           py27h27c97d8_0    defaults
scipy                     1.2.1            py27h1410ff5_0    defaults
seaborn                   0.9.0                    py27_0    defaults
send2trash                1.5.0                    py27_0    defaults
setuptools                41.0.1                   py27_0    defaults
simplegeneric             0.8.1                    py27_2    defaults
singledispatch            3.4.0.3          py27he22c18d_0    defaults
sip                       4.19.8           py27h0a44026_0    defaults
six                       1.12.0                   py27_0    defaults
snappy                    1.1.7                he62c110_3    defaults
snowballstemmer           1.2.1            py27h68ac032_0    defaults
sortedcollections         1.1.2                    py27_0    defaults
sortedcontainers          2.1.0                    py27_0    defaults
soupsieve                 1.8                      py27_0    defaults
sphinx                    1.8.5                    py27_0    defaults
sphinxcontrib             1.0                      py27_1    defaults
sphinxcontrib-websupport  1.1.2                      py_0    defaults
spyder                    3.1.4                    py27_0    defaults
spyder-kernels            0.4.4                    py27_0    defaults
sqlalchemy                1.3.4            py27h1de35cc_0    defaults
sqlite                    3.28.0               ha441bb4_0    defaults
ssl_match_hostname        3.7.0.1                  py27_0    defaults
statsmodels               0.9.0            py27h1d22016_0    defaults
subprocess32              3.5.4            py27h1de35cc_0    defaults
sympy                     1.4                      py27_0    defaults
tblib                     1.4.0                      py_0    defaults
terminado                 0.8.2                    py27_0    defaults
testpath                  0.4.2                    py27_0    defaults
tk                        8.6.8                ha441bb4_0    defaults
tktable                   2.10                 h1de35cc_0    defaults
toolz                     0.9.0                    py27_0    defaults
tornado                   5.1.1            py27h1de35cc_0    defaults
tqdm                      4.32.1                     py_0    defaults
traceback2                1.4.0                    py27_0    defaults
traitlets                 4.3.2            py27hcf08151_0    defaults
typing                    3.6.6                    py27_0    defaults
unicodecsv                0.14.1           py27h170f95c_0    defaults
unittest2                 1.1.0                    py27_0    defaults
unixodbc                  2.3.7                h1de35cc_0    defaults
urllib3                   1.24.2                   py27_0    defaults
wcwidth                   0.1.7            py27h817c265_0    defaults
webencodings              0.5.1                    py27_1    defaults
werkzeug                  0.15.4                     py_0    defaults
wheel                     0.33.4                   py27_0    defaults
widgetsnbextension        3.4.2                    py27_0    defaults
wrapt                     1.11.1           py27h1de35cc_0    defaults
wurlitzer                 1.0.2                    py27_0    defaults
xlrd                      1.2.0                    py27_0    defaults
xlsxwriter                1.1.8                      py_0    defaults
xlwings                   0.15.8                   py27_0    defaults
xlwt                      1.2.0            py27hbeec4ae_0    defaults
xz                        5.2.4                h1de35cc_4    defaults
yaml                      0.1.7                hc338f04_2    defaults
zeromq                    4.3.1                h0a44026_3    defaults
zict                      0.1.4                    py27_0    defaults
zipp                      0.5.1                      py_0    defaults
zlib                      1.2.11               h1de35cc_3    defaults
zstd                      1.3.7                h5bba6e5_0    defaults

```

</details>
Some background:
I was using the most recent version of Spyder, and needed to downgrade to 3.1.4 because of issues with the Ipython console and multithread processing. I tried deleting the new version but just deleting whatever folder had the name Spyder in it (I'm a noob...) and  have been having issues ever since

**Comment by Khris777** [comment]
I am getting the same issue when I install RStudio with Spyder installed on the Home page in my environment.

Removing RStudio solves the problem.
