### ISSUE TITLE
AttributeError: module 'matplotlib' has no attribute 'interactive'

### ISSUE THREAD

**Issue by schwemro** [ContinuumIO/anaconda-issues#11046]
### Actual Behavior
This is the error message after starting `spyder` from the terminal:
Error processing line 1 of .../anaconda3/envs/py37/lib/python3.6/site-packages/matplotlib-3.1.0-py3.6-nspkg.pth:

  Traceback (most recent call last):
    File ".../anaconda3/envs/py37/lib/python3.6/site.py", line 168, in addpackage
      exec(line)
    File "<string>", line 1, in <module>
    File "<frozen importlib._bootstrap>", line 568, in module_from_spec
  AttributeError: 'NoneType' object has no attribute 'loader'

Remainder of file ignored

And this appears in IPython console:
NOTE: The following error appeared when setting your Matplotlib backend

Traceback (most recent call last):
  File ".../anaconda3/envs/py37/lib/python3.6/site-packages/spyder_kernels/console/kernel.py", line 475, in _set_mpl_backend
    get_ipython().run_line_magic(magic, backend)
  File ".../anaconda3/envs/py37/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2307, in run_line_magic
    result = fn(*args, **kwargs)
  File "<.../anaconda3/envs/py37/lib/python3.6/site-packages/decorator.py:decorator-gen-108>", line 2, in matplotlib
  File ".../anaconda3/envs/py37/lib/python3.6/site-packages/IPython/core/magic.py", line 187, in <lambda>
    call = lambda f, *a, **k: f(*a, **k)
  File ".../anaconda3/envs/py37/lib/python3.6/site-packages/IPython/core/magics/pylab.py", line 99, in matplotlib
    gui, backend = self.shell.enable_matplotlib(args.gui)
  File ".../anaconda3/envs/py37/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 3384, in enable_matplotlib
    pt.activate_matplotlib(backend)
  File ".../anaconda3/envs/py37/lib/python3.6/site-packages/IPython/core/pylabtools.py", line 306, in activate_matplotlib
    matplotlib.interactive(True)
AttributeError: module 'matplotlib' has no attribute 'interactive'

### Expected Behavior

The following import should be possible:
`import matplotlib.pyplot as plt`

### Steps to Reproduce

`conda update conda`
`conda update conda-build`

##### Anaconda or Miniconda version:

4.7.5

##### `conda info`
<details>

```
     active environment : ...
    active env location : ...
            shell level : 2
       user config file : .../.condarc
 populated config files : .../.condarc
          conda version : 4.7.5
    conda-build version : 3.18.5
         python version : 3.7.3.final.0
       virtual packages : 
       base environment : .../anaconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/osx-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/osx-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : .../anaconda3/pkgs
                          .../.conda/pkgs
       envs directories : .../anaconda3/envs
                         .../.conda/envs
               platform : osx-64
             user-agent : conda/4.7.5 requests/2.22.0 CPython/3.7.3 Darwin/18.6.0 OSX/10.14.5
                UID:GID : 501:20
             netrc file : None
           offline mode : False

```

</details>

##### `conda list --show-channel-urls`

<details>

```
# Name                    Version                   Build  Channel
alabaster                 0.7.12                   py36_0    defaults
altgraph                  0.16.1                     py_0    conda-forge
appnope                   0.1.0            py36hf537a9a_0    defaults
asn1crypto                0.24.0                   py36_0    defaults
astroid                   2.2.5                    py36_0    defaults
attrs                     19.1.0                   py36_1    defaults
babel                     2.7.0                      py_0    defaults
backcall                  0.1.0                    py36_0    defaults
blas                      1.0                         mkl    defaults
bleach                    3.1.0                    py36_0    defaults
bokeh                     1.2.0                    py36_0    defaults
bottleneck                1.2.1            py36h1d22016_1    defaults
bzip2                     1.0.6                h1de35cc_5    defaults
ca-certificates           2019.5.15                     0    defaults
cairo                     1.14.12              hc4e6be7_4    defaults
certifi                   2019.6.16                py36_0    defaults
cffi                      1.12.3           py36hb5b8e2f_0    defaults
cftime                    1.0.3.4          py36h1d22016_1    defaults
chardet                   3.0.4                    py36_1    defaults
click                     7.0                      py36_0    defaults
cloudpickle               1.1.1                      py_0    defaults
cryptography              2.7              py36ha12b0ac_0    defaults
curl                      7.64.1               ha441bb4_0    defaults
cycler                    0.10.0           py36hfc81398_0    defaults
cython                    0.29.10          py36h0a44026_0    defaults
cytoolz                   0.9.0.1          py36h1de35cc_1    defaults
dask                      1.2.2                      py_0    defaults
dask-core                 1.2.2                      py_0    defaults
dask-glm                  0.2.0                    py36_0    defaults
dask-ml                   0.13.0                     py_0    defaults
dbus                      1.13.6               h90a0687_0    defaults
decorator                 4.4.0                    py36_1    defaults
defusedxml                0.6.0                      py_0    defaults
distributed               1.28.1                   py36_0    defaults
docutils                  0.14             py36hbfde631_0    defaults
entrypoints               0.3                      py36_0    defaults
expat                     2.2.6                h0a44026_0    defaults
fontconfig                2.13.0               h5d5b041_1    defaults
freetype                  2.9.1                hb4e5f40_0    defaults
freexl                    1.0.5                h1de35cc_0    defaults
gdal                      2.3.3            py36hbe65578_0    defaults
geos                      3.7.1                h0a44026_0    defaults
gettext                   0.19.8.1             h15daf44_3    defaults
giflib                    5.1.4                h1de35cc_1    defaults
glib                      2.56.2               hd9629dc_0    defaults
hdf4                      4.2.13               h39711bb_2    defaults
hdf5                      1.10.4               hfa1e0ec_0    defaults
heapdict                  1.0.0                    py36_2    defaults
icu                       58.2                 h4b95b61_1    defaults
idna                      2.8                      py36_0    defaults
imagesize                 1.1.0                    py36_0    defaults
intel-openmp              2019.4                      233    defaults
ipykernel                 5.1.1            py36h39e3cac_0    defaults
ipython                   7.5.0            py36h39e3cac_0    defaults
ipython_genutils          0.2.0            py36h241746c_0    defaults
isort                     4.3.20                   py36_0    defaults
jedi                      0.13.3                   py36_0    defaults
jinja2                    2.10.1                   py36_0    defaults
joblib                    0.13.2                   py36_0    defaults
jpeg                      9b                   he5867d9_2    defaults
json-c                    0.13.1               h3efe00b_0    defaults
jsonschema                3.0.1                    py36_0    defaults
jupyter_client            5.2.4                    py36_0    defaults
jupyter_core              4.4.0                    py36_0    defaults
kealib                    1.4.7                hf5ed860_6    defaults
keyring                   18.0.0                   py36_0    defaults
kiwisolver                1.1.0            py36h0a44026_0    defaults
krb5                      1.16.1               hddcf347_7    defaults
lazy-object-proxy         1.4.1            py36h1de35cc_0    defaults
libboost                  1.67.0               hebc422b_4    defaults
libcurl                   7.64.1               h051b688_0    defaults
libcxx                    4.0.1                hcfea43d_1    defaults
libcxxabi                 4.0.1                hcfea43d_1    defaults
libdap4                   3.19.1               h3d3e54a_0    defaults
libedit                   3.1.20181209         hb402a30_0    defaults
libffi                    3.2.1                h475c297_4    defaults
libgdal                   2.3.3                h0950a36_0    defaults
libgfortran               3.0.1                h93005f0_2    defaults
libiconv                  1.15                 hdd342a3_7    defaults
libkml                    1.3.0                hbe12b63_4    defaults
libnetcdf                 4.6.1                hd5207e6_2    defaults
libpng                    1.6.37               ha441bb4_0    defaults
libpq                     11.2                 h051b688_0    defaults
libsodium                 1.0.16               h3efe00b_0    defaults
libspatialite             4.3.0a              h644ec7d_19    defaults
libssh2                   1.8.2                ha12b0ac_0    defaults
libtiff                   4.0.10            hcb84e12_1001    defaults
libxml2                   2.9.9                hab757c2_0    defaults
llvm-openmp               4.0.1                hcfea43d_1    defaults
llvmlite                  0.29.0           py36h98b8051_0    defaults
locket                    0.2.0            py36hca03003_1    defaults
macholib                  1.11                       py_0    conda-forge
markupsafe                1.1.1            py36h1de35cc_0    defaults
matplotlib                3.1.0            py36h54f8f79_0    defaults
mccabe                    0.6.1                    py36_1    defaults
mistune                   0.8.4            py36h1de35cc_0    defaults
mkl                       2019.4                      233    defaults
mkl-service               2.0.2            py36h1de35cc_0    defaults
mkl_fft                   1.0.12           py36h5e564d8_0    defaults
mkl_random                1.0.2            py36h27c97d8_0    defaults
msgpack-python            0.6.1            py36h04f5b5a_1    defaults
multipledispatch          0.6.0                    py36_0    defaults
nbconvert                 5.5.0                      py_0    defaults
nbformat                  4.4.0            py36h827af21_0    defaults
ncurses                   6.1                  h0a44026_1    defaults
netcdf4                   1.4.2            py36h13743db_0    defaults
numba                     0.44.1           py36h6440ff4_0    defaults
numpy                     1.16.4           py36hacdab7b_0    defaults
numpy-base                1.16.4           py36h6575580_0    defaults
numpydoc                  0.9.1                      py_0    defaults
olefile                   0.46                     py36_0    defaults
openjpeg                  2.3.0                hb95cd4c_1    defaults
openssl                   1.1.1c               h1de35cc_1    defaults
packaging                 19.0                     py36_0    defaults
pandas                    0.24.2           py36h0a44026_0    defaults
pandoc                    2.2.3.2                       0    defaults
pandocfilters             1.4.2                    py36_1    defaults
parso                     0.4.0                      py_0    defaults
partd                     0.3.10                   py36_1    defaults
patsy                     0.5.1                    py36_0    defaults
pcre                      8.43                 h0a44026_0    defaults
pep8                      1.7.1                    py36_0    defaults
pexpect                   4.7.0                    py36_0    defaults
pickleshare               0.7.5                    py36_0    defaults
pillow                    6.0.0            py36hb68e598_0    defaults
pip                       19.1.1                   py36_0    defaults
pixman                    0.38.0               h1de35cc_0    defaults
poppler                   0.65.0               ha097c24_1    defaults
poppler-data              0.4.9                         0    defaults
proj4                     5.2.0                h0a44026_1    defaults
prompt_toolkit            2.0.9                    py36_0    defaults
psutil                    5.6.2            py36h1de35cc_0    defaults
ptyprocess                0.6.0                    py36_0    defaults
pycodestyle               2.5.0                    py36_0    defaults
pycparser                 2.19                     py36_0    defaults
pycrypto                  2.6.1            py36h1de35cc_9    defaults
pyflakes                  2.1.1                    py36_0    defaults
pygments                  2.4.2                      py_0    defaults
pyinstaller               3.4              py36ha92aebf_0    conda-forge
pylint                    2.3.1                    py36_0    defaults
pyopenssl                 19.0.0                   py36_0    defaults
pyparsing                 2.4.0                      py_0    defaults
pyqt                      5.9.2            py36h655552a_2    defaults
pyrsistent                0.14.11          py36h1de35cc_0    defaults
pysocks                   1.7.0                    py36_0    defaults
python                    3.6.8                haf84260_0    defaults
python-dateutil           2.8.0                    py36_0    defaults
python.app                2                        py36_9    defaults
pytz                      2019.1                     py_0    defaults
pyyaml                    5.1              py36h1de35cc_0    defaults
pyzmq                     18.0.0           py36h0a44026_0    defaults
qt                        5.9.7                h468cd18_1    defaults
qtawesome                 0.5.7                    py36_1    defaults
qtconsole                 4.5.1                      py_0    defaults
qtpy                      1.7.1                      py_0    defaults
readline                  7.0                  h1de35cc_5    defaults
requests                  2.22.0                   py36_0    defaults
rope                      0.14.0                     py_0    defaults
scikit-learn              0.21.2           py36h27c97d8_0    defaults
scipy                     1.2.1            py36h1410ff5_0    defaults
seaborn                   0.9.0                    py36_0    defaults
setuptools                41.0.1                   py36_0    defaults
sip                       4.19.8           py36h0a44026_0    defaults
six                       1.12.0                   py36_0    defaults
snowballstemmer           1.2.1            py36h6c7b616_0    defaults
sortedcontainers          2.1.0                    py36_0    defaults
sphinx                    2.1.0                      py_0    defaults
sphinxcontrib-applehelp   1.0.1                      py_0    defaults
sphinxcontrib-devhelp     1.0.1                      py_0    defaults
sphinxcontrib-htmlhelp    1.0.2                      py_0    defaults
sphinxcontrib-jsmath      1.0.1                      py_0    defaults
sphinxcontrib-qthelp      1.0.2                      py_0    defaults
sphinxcontrib-serializinghtml 1.1.3                      py_0    defaults
spyder                    3.3.4                    py36_0    defaults
spyder-kernels            0.4.4                    py36_0    defaults
sqlite                    3.28.0               ha441bb4_0    defaults
statsmodels               0.9.0            py36h1d22016_0    defaults
tblib                     1.4.0                      py_0    defaults
testpath                  0.4.2                    py36_0    defaults
tk                        8.6.8                ha441bb4_0    defaults
toolz                     0.9.0                    py36_0    defaults
tornado                   6.0.2            py36h1de35cc_0    defaults
tqdm                      4.32.1                     py_0    defaults
traitlets                 4.3.2            py36h65bd3ce_0    defaults
typed-ast                 1.3.4            py36h1de35cc_0    defaults
urllib3                   1.24.2                   py36_0    defaults
wcwidth                   0.1.7            py36h8c6ec74_0    defaults
webencodings              0.5.1                    py36_1    defaults
wheel                     0.33.4                   py36_0    defaults
wrapt                     1.11.1           py36h1de35cc_0    defaults
wurlitzer                 1.0.2                    py36_0    defaults
xarray                    0.12.1                     py_0    defaults
xerces-c                  3.2.2                h44e365a_0    defaults
xz                        5.2.4                h1de35cc_4    defaults
yaml                      0.1.7                hc338f04_2    defaults
zeromq                    4.3.1                h0a44026_3    defaults
zict                      0.1.4                    py36_0    defaults
zlib                      1.2.11               h1de35cc_3    defaults

```

</details>

**Comment by yypai** [comment]
I have a possibly related instance. Mine is after the installation of matplotlib-base when installing scikit-image. The error is:
```
Error processing line 1 of /anaconda3/lib/python3.7/site-packages/matplotlib-3.1.0-py3.7-nspkg.pth:

  Traceback (most recent call last):
    File "/anaconda3/lib/python3.7/site.py", line 168, in addpackage
      exec(line)
    File "<string>", line 1, in <module>
    File "<frozen importlib._bootstrap>", line 580, in module_from_spec
  AttributeError: 'NoneType' object has no attribute 'loader'

Remainder of file ignored
```
