### ISSUE TITLE
conda update anaconda causes anaconda to be unable to start

### ISSUE THREAD

**Issue by sweattej** [ContinuumIO/anaconda-issues#11044]
### Actual Behavior

 did a conda update conda which appeared to work, then did a conda updata anaconda which failed with the following 
ERROR conda.core.link:_execute(637): An error occurred while installing package 'None'
now anaconda won't start from the applications folder(use mac os) and won't start from a terminal which give following response
joels-imac:~ #######$ Anaconda-Navigator
Traceback (most recent call last):
  File "/Users/########/anaconda/bin/Anaconda-Navigator", line 7, in <module>
    from anaconda_navigator.app.main import main
  File "/Users/#######/anaconda/lib/python3.6/site-packages/anaconda_navigator/app/main.py", line 22, in <module>
    from anaconda_navigator.utils.conda import is_conda_available
  File "/Users/########/anaconda/lib/python3.6/site-packages/anaconda_navigator/utils/__init__.py", line 15, in <module>
    from qtpy.QtGui import QIcon
ModuleNotFoundError: No module named 'qtpy.QtGui'
 

### Expected Behavior

 anaconda should have been updated and able to be started

### Steps to Reproduce

conda update conda
conda update anaconda

##### Anaconda or Miniconda version:

 no file downloaded

##### `conda info`

$ conda info

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/Users/sweattej1/anaconda/lib/python3.6/site-packages/conda/exceptions.py", line 1043, in __call__
        return func(*args, **kwargs)
      File "/Users/sweattej1/anaconda/lib/python3.6/site-packages/conda/cli/main.py", line 84, in _main
        exit_code = do_call(args, p)
      File "/Users/sweattej1/anaconda/lib/python3.6/site-packages/conda/cli/conda_argparse.py", line 80, in do_call
        module = import_module(relative_mod, __name__.rsplit('.', 1)[0])
      File "/Users/sweattej1/anaconda/lib/python3.6/importlib/__init__.py", line 126, in import_module
        return _bootstrap._gcd_import(name[level:], package, level)
      File "<frozen importlib._bootstrap>", line 994, in _gcd_import
      File "<frozen importlib._bootstrap>", line 971, in _find_and_load
      File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
      File "<frozen importlib._bootstrap_external>", line 678, in exec_module
      File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
      File "/Users/sweattej1/anaconda/lib/python3.6/site-packages/conda/cli/main_info.py", line 19, in <module>
        from ..core.index import _supplement_index_with_system
      File "/Users/sweattej1/anaconda/lib/python3.6/site-packages/conda/core/index.py", line 9, in <module>
        from .package_cache_data import PackageCacheData
      File "/Users/sweattej1/anaconda/lib/python3.6/site-packages/conda/core/package_cache_data.py", line 15, in <module>
        from conda_package_handling.api import InvalidArchiveError
      File "/Users/sweattej1/anaconda/lib/python3.6/site-packages/conda_package_handling/api.py", line 3, in <module>
        from libarchive.exception import ArchiveError as _LibarchiveArchiveError
      File "/Users/sweattej1/anaconda/lib/python3.6/site-packages/libarchive/__init__.py", line 1, in <module>
        from .entry import ArchiveEntry
      File "/Users/sweattej1/anaconda/lib/python3.6/site-packages/libarchive/entry.py", line 6, in <module>
        from . import ffi
      File "/Users/sweattej1/anaconda/lib/python3.6/site-packages/libarchive/ffi.py", line 27, in <module>
        libarchive = ctypes.cdll.LoadLibrary(libarchive_path)
      File "/Users/sweattej1/anaconda/lib/python3.6/ctypes/__init__.py", line 426, in LoadLibrary
        return self._dlltype(name)
      File "/Users/sweattej1/anaconda/lib/python3.6/ctypes/__init__.py", line 348, in __init__
        self._handle = _dlopen(self._name, mode)
    OSError: dlopen(/Users/sweattej1/anaconda/bin/../lib/libarchive.dylib, 6): Library not loaded: @rpath/libxml2.2.dylib
      Referenced from: /Users/sweattej1/anaconda/lib/libarchive.13.dylib
      Reason: Incompatible library version: libarchive.dylib requires version 12.0.0 or later, but libxml2.2.dylib provides version 10.0.0

<details>

```
PASTE OUTPUT HERE:

```

</details>

##### `conda list --show-channel-urls`

<details>

```
PASTE OUTPUT HERE: conda does not work

```

</details>

**Comment by sweattej** [comment]
well I hope this is not where one goes to get some assistance with anaconda.

**Comment by awoehrl** [comment]
Same problem on my side.

**Comment by sweattej** [comment]
I've seen several others with the same sort of problem. Github is apparently useless, I guess you have to purchase support now. Oh well, it was inevitable.

**Comment by msarahan** [comment]
No, we don't offer support outside of enterprises.  Sorry, you'll have to be patient, or otherwise figure things out for yourself.  A totally free product with totally free support is nice, but it doesn't pay the bills.  We have to spend most of our time on things other than debugging user systems.

Your error message points to an incorrect xmllib package getting loaded.  I can't begin to suggest exactly where the incorrect version is coming from, or if there's a correct version to be found, but you can learn more by examining what's going on with your system using tools like otool: https://medium.com/@donblas/fun-with-rpath-otool-and-install-name-tool-e3e41ae86172

**Comment by sweattej** [comment]
Right, be great if you’d fix the software so it is dependable. Cost or no cost.

Joel Sweatte
College of Engineering and Technology
East Carolina University
Science & Technology bldg. Suite 100
252-328-9439

**Comment by msarahan** [comment]
You seem to think that having things always work for everyone is a goal that we don't share, or that we're not working towards.  It's not a 100% achievable goal, but it is one of our goals.  I'm sorry you're on the short end of that stick right now, but you can do more to help yourself and others, or if you're not up for being helpful, you can be patient.  Or, you can complain, which disincentivizes us to spend time investigating your particular issue over any of the others.

**Comment by sweattej** [comment]
There are numerous people who have the same issue I do. I don’t expect you will spend any time on MY issue. It’s your issue and instead of trading emails with idiots like me stupid enough to try and use this crap you should fix the software.

Joel Sweatte
College of Engineering and Technology
East Carolina University
Science & Technology bldg. Suite 100
252-328-9439

**Comment by msarahan** [comment]
Good luck.  We might take a look at this if a more polite user raises it.
