### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by GeorgeWuBW** [ContinuumIO/anaconda-issues#11052]
## Main error
An unexpected error occurred on Navigator start-up<br>psutil.AccessDenied (pid=1588)
## Traceback
```
Traceback (most recent call last):
  File "C:\Users\gxw12\AppData\Local\Continuum\Anaconda2\lib\site-packages\anaconda_navigator\exceptions.py", line 75, in exception_handler
    return_value = func(*args, **kwargs)
  File "C:\Users\gxw12\AppData\Local\Continuum\Anaconda2\lib\site-packages\anaconda_navigator\app\start.py", line 108, in start_app
    if misc.load_pid() is None:  # A stale lock might be around
  File "C:\Users\gxw12\AppData\Local\Continuum\Anaconda2\lib\site-packages\anaconda_navigator\utils\misc.py", line 384, in load_pid
    cmds = process.cmdline()
  File "C:\Users\gxw12\AppData\Local\Continuum\Anaconda2\lib\site-packages\psutil\__init__.py", line 669, in cmdline
    return self._proc.cmdline()
  File "C:\Users\gxw12\AppData\Local\Continuum\Anaconda2\lib\site-packages\psutil\_pswindows.py", line 638, in wrapper
    raise AccessDenied(self.pid, self._name)
AccessDenied: psutil.AccessDenied (pid=1588)

```
## System information
```
platform: win-64
version: 1.6.2
conda: 4.7.5
qt: 5.6.2
language: en_AU
python: 2.7.16
os: Windows;7;6.1.7601;AMD64;Intel64 Family 6 Model 78 Stepping 3, GenuineIntel
pyqt: 5.6.0
```

**Comment by csoja** [comment]
In the Anaconda Prompt:

conda update conda
conda update anaconda-navigator
conda update navigator-updater
anaconda-navigator --reset

The last command is the key to fixing your issue - as it removes the lock file that is causing your problem.
