### ISSUE TITLE
Navigator Error  An unexpected error occurred on Navigator start-up

### ISSUE THREAD

**Issue by nickratterman** [ContinuumIO/anaconda-issues#11060]
Anaconda was fully-functional before I updated. I received a notification saying that it was very important to update every 10 seconds or so. I updated and it when I tried to launch again, it produced this:
```
Traceback (most recent call last):
  File "/Users/me/anaconda/envs/env/lib/python2.7/site-packages/anaconda_navigator/exceptions.py", line 75, in exception_handler
    return_value = func(*args, **kwargs)
  File "/Users/me/anaconda/envs/env/lib/python2.7/site-packages/anaconda_navigator/app/start.py", line 115, in start_app
    window = run_app(splash)
  File "/Users/me/anaconda/envs/env/lib/python2.7/site-packages/anaconda_navigator/app/start.py", line 58, in run_app
    window = MainWindow(splash=splash)
  File "/Users/me/anaconda/envs/env/lib/python2.7/site-packages/anaconda_navigator/widgets/main_window.py", line 160, in __init__
    self.api = AnacondaAPI()
  File "/Users/me/anaconda/envs/env/lib/python2.7/site-packages/anaconda_navigator/api/anaconda_api.py", line 1205, in AnacondaAPI
    ANACONDA_API = _AnacondaAPI()
  File "/Users/me/anaconda/envs/env/lib/python2.7/site-packages/anaconda_navigator/api/anaconda_api.py", line 65, in __init__
    self._conda_api = CondaAPI()
  File "/Users/me/anaconda/envs/env/lib/python2.7/site-packages/anaconda_navigator/api/conda_api.py", line 1622, in CondaAPI
    CONDA_API = _CondaAPI()
  File "/Users/me/anaconda/envs/env/lib/python2.7/site-packages/anaconda_navigator/api/conda_api.py", line 340, in __init__
    self.set_conda_prefix()
  File "/Users/me/anaconda/envs/env/lib/python2.7/site-packages/anaconda_navigator/api/conda_api.py", line 488, in set_conda_prefix
    info = worker.communicate()[0]
  File "/Users/me/anaconda/envs/env/lib/python2.7/site-packages/anaconda_navigator/api/conda_api.py", line 266, in communicate
    " ".join(self._cmd_list), result[0]['message']
KeyError: 'message'
```

I checked the other git issues and tried the following:

```
conda update anaconda-navigator
conda update navigator-updater
anaconda-navigator --reset
```

I uninstalled and reinstalled the latest version. Same error message.

I uninstalled and installed an older version. Same error message. 

I have gone through several threads and have tried every single recommended solution, but Anaconda Navigator is simply broken. 

I am using a Mac on Mojave OS. 

Please help: I use this every day and need it functional.

**Comment by Misbahrani** [comment]
How did you use the above commands??? is your anaconda prompt working???

**Comment by nickratterman** [comment]
I ran them using the terminal

**Comment by Misbahrani** [comment]
okay, in my case after update terminal is not working.
I guess there is some issue with the update.

**Comment by nickratterman** [comment]
Yes, this update caused a massive problem for me, too.

I completely wiped Anaconda from my system, which I have wanted to do for a while now. I’ll manage without it.

**Comment by amoghshitre** [comment]
Same error is occurring any solutions?

**Comment by nickratterman** [comment]
My solution was to stop using Anaconda.
