### ISSUE TITLE
Anaconda3-5.3.0 Windows 10: conda update anaconda fails

### ISSUE THREAD

**Issue by dineshbvadhia** [ContinuumIO/anaconda-issues#11075]
Have been using Anaconda since 2012 on Windows without any installation problems until today. Installed miniconda first followed by Anaconda3-5.3.0 on Windows 10.

`> conda update conda
`

worked fine

`> conda update anaconda`

failed with the following:

```
(base) C:\Users\User>conda update anaconda
WARNING conda.base.context:use_only_tar_bz2(632): Conda is constrained to only using the old .tar.bz2 file format because you have conda-build installed, and it is <3.18.3.  Update or remove conda-build to get smaller downloads and faster extractions.
Collecting package metadata (repodata.json): done
Solving environment: /
The environment is inconsistent, please check the package plan carefully
The following packages are causing the inconsistency:

  - defaults/win-64::anaconda==5.3.0=py37_0
  - defaults/win-64::astropy==3.0.4=py37hfa6e2cd_0
  - defaults/win-64::bkcharts==0.2=py37_0
  - defaults/win-64::blaze==0.11.3=py37_0
  - defaults/win-64::bokeh==0.13.0=py37_0
  - defaults/win-64::bottleneck==1.2.1=py37h452e1ab_1
  - defaults/win-64::dask==0.19.1=py37_0
  - defaults/win-64::datashape==0.5.4=py37_1
  - defaults/win-64::h5py==2.8.0=py37h3bdd7fb_2
  - defaults/win-64::imageio==2.4.1=py37_0
  - defaults/win-64::matplotlib==2.2.3=py37hd159220_0
  - defaults/win-64::mkl-service==1.1.2=py37hb217b18_5
  - defaults/win-64::mkl_fft==1.0.4=py37h1e22a9b_1
  - defaults/win-64::mkl_random==1.0.1=py37h77b88f5_1
  - defaults/win-64::numba==0.39.0=py37h830ac7b_0
  - defaults/win-64::numexpr==2.6.8=py37h9ef55f4_0
  - defaults/win-64::numpy==1.15.1=py37ha559c80_0
  - defaults/win-64::numpy-base==1.15.1=py37h8128ebf_0
  - defaults/win-64::odo==0.5.1=py37_0
  - defaults/win-64::pandas==0.23.4=py37h830ac7b_0
  - defaults/win-64::patsy==0.5.0=py37_0
  - defaults/win-64::pytables==3.4.4=py37he6f6034_0
  - defaults/win-64::pytest-arraydiff==0.2=py37h39e3cac_0
  - defaults/win-64::pytest-astropy==0.4.0=py37_0
  - defaults/win-64::pytest-doctestplus==0.1.3=py37_0
  - defaults/win-64::pywavelets==1.0.0=py37h452e1ab_0
  - defaults/win-64::scikit-image==0.14.0=py37h6538335_1
  - defaults/win-64::scikit-learn==0.19.2=py37heebcf9a_0
  - defaults/win-64::scipy==1.1.0=py37h4f6bf74_1
  - defaults/win-64::seaborn==0.9.0=py37_0
  - defaults/win-64::statsmodels==0.9.0=py37h452e1ab_0
done

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "C:\Users\User\Anaconda3\lib\site-packages\conda\models\prefix_graph.py", line 252, in _topo_sort_handle_cycles
        value = next(t)
      File "C:\Users\User\Anaconda3\lib\site-packages\conda\models\prefix_graph.py", line 230, in _toposort_raise_on_cycles
        raise CyclicalDependencyError(tuple(graph))
    conda.exceptions.CyclicalDependencyError: Cyclic dependencies exist among these items:
      - defaults::_ipyw_jlab_nb_ext_conf-0.1.0-py37_0
      - defaults::anaconda-client-1.7.2-py37_0
      - defaults::anaconda-navigator-1.9.7-py37_0
      - defaults::cloudpickle-1.2.1-py_0
      - defaults::conda-4.7.5-py37_0
      - defaults::conda-build-3.18.5-py37_0
      - defaults::conda-package-handling-1.3.10-py37_0
      - defaults::defusedxml-0.6.0-py_0
      - defaults::distributed-1.28.1-py37_0
      - defaults::filelock-3.0.12-py_0
      - defaults::flask-1.0.3-py37_0
      - defaults::flask-cors-3.0.8-py_0
      - defaults::glob2-0.7-py_0
      - defaults::importlib_metadata-0.17-py37_1
      - defaults::ipykernel-5.1.1-py37h39e3cac_0
      - defaults::ipython-7.6.0-py37h39e3cac_0
      - defaults::ipywidgets-7.4.2-py37_0
      - defaults::jedi-0.13.3-py37_0
      - defaults::jupyter_client-5.2.4-py37_0
      - defaults::jupyter_core-4.5.0-py_0
      - defaults::jupyterlab-0.35.4-py37hf63ae98_0
      - defaults::jupyterlab_server-0.2.0-py37_0
      - defaults::navigator-updater-0.2.1-py37_0
      - defaults::nbconvert-5.5.0-py_0
      - defaults::nbformat-4.4.0-py37_0
      - defaults::networkx-2.3-py_0
      - defaults::notebook-5.7.8-py37_0
      - defaults::packaging-19.0-py37_0
      - defaults::parso-0.5.0-py_0
      - defaults::partd-1.0.0-py_0
      - defaults::pluggy-0.12.0-py_0
      - defaults::prometheus_client-0.7.1-py_0
      - defaults::prompt_toolkit-2.0.9-py37_0
      - defaults::pygments-2.4.2-py_0
      - defaults::pyparsing-2.4.0-py_0
      - defaults::pytest-5.0.0-py37_0
      - defaults::pytest-openfiles-0.3.2-py37_0
      - defaults::pytest-remotedata-0.3.1-py37_0
      - defaults::pytz-2019.1-py_0
      - defaults::qtpy-1.8.0-py_0
      - defaults::tblib-1.4.0-py_0
      - defaults::tqdm-4.32.1-py_0
      - defaults::werkzeug-0.15.4-py_0
      - defaults::widgetsnbextension-3.4.2-py37_0
      - defaults::zict-1.0.0-py_0
      - defaults::zipp-0.5.1-py_0
      - defaults::astropy-3.0.4-py37hfa6e2cd_0
      - defaults::bkcharts-0.2-py37_0
      - defaults::blaze-0.11.3-py37_0
      - defaults::bokeh-0.13.0-py37_0
      - defaults::bottleneck-1.2.1-py37h452e1ab_1
      - defaults::dask-0.19.1-py37_0
      - defaults::datashape-0.5.4-py37_1
      - defaults::h5py-2.8.0-py37h3bdd7fb_2
      - defaults::imageio-2.4.1-py37_0
      - defaults::matplotlib-2.2.3-py37hd159220_0
      - defaults::mkl_fft-1.0.4-py37h1e22a9b_1
      - defaults::mkl_random-1.0.1-py37h77b88f5_1
      - defaults::numba-0.39.0-py37h830ac7b_0
      - defaults::numexpr-2.6.8-py37h9ef55f4_0
      - defaults::numpy-1.15.1-py37ha559c80_0
      - defaults::odo-0.5.1-py37_0
      - defaults::pandas-0.23.4-py37h830ac7b_0
      - defaults::patsy-0.5.0-py37_0
      - defaults::pytables-3.4.4-py37he6f6034_0
      - defaults::pytest-arraydiff-0.2-py37h39e3cac_0
      - defaults::pytest-astropy-0.4.0-py37_0
      - defaults::pytest-doctestplus-0.1.3-py37_0
      - defaults::pywavelets-1.0.0-py37h452e1ab_0
      - defaults::scikit-image-0.14.0-py37h6538335_1
      - defaults::scikit-learn-0.19.2-py37heebcf9a_0
      - defaults::scipy-1.1.0-py37h4f6bf74_1
      - defaults::seaborn-0.9.0-py37_0
      - defaults::statsmodels-0.9.0-py37h452e1ab_0
      - defaults::packaging-17.1-py37_0
      - defaults::qtconsole-4.4.1-py37_0
      - defaults::flask-cors-3.0.6-py37_0
      - defaults::jedi-0.12.1-py37_0
      - defaults::ipywidgets-7.4.1-py37_0
      - defaults::jupyter_client-5.2.3-py37_0
      - defaults::prompt_toolkit-1.0.15-py37_0
      - defaults::jupyterlab-0.34.9-py37_0
      - defaults::nbconvert-5.4.0-py37_1
      - defaults::distributed-1.23.1-py37_0
      - defaults::sphinx-1.7.9-py37_0
      - defaults::pytest-remotedata-0.3.0-py37_0
      - defaults::jupyterlab_launcher-0.13.1-py37_0
      - defaults::notebook-5.6.0-py37_0
      - defaults::numpydoc-0.8.0-py37_0
      - defaults::ipython-6.5.0-py37_0
      - defaults::flask-1.0.2-py37_1
      - defaults::jupyter-1.0.0-py37_7
      - defaults::qtawesome-0.4.4-py37_0
      - defaults::spyder-3.3.1-py37_1
      - defaults::jupyter_console-5.2.0-py37_1
      - defaults::babel-2.6.0-py37_0
      - defaults::spyder-kernels-0.2.6-py37_0
      - defaults::widgetsnbextension-3.4.1-py37_0
      - defaults::pytest-3.8.0-py37_0
      - defaults::ipykernel-4.10.0-py37_0
      - defaults::pytest-openfiles-0.3.0-py37_0
      - defaults::anaconda-project-0.8.2-py37_0

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "C:\Users\User\Anaconda3\lib\site-packages\conda\exceptions.py", line 1043, in __call__
        return func(*args, **kwargs)
      File "C:\Users\User\Anaconda3\lib\site-packages\conda\cli\main.py", line 84, in _main
        exit_code = do_call(args, p)
      File "C:\Users\User\Anaconda3\lib\site-packages\conda\cli\conda_argparse.py", line 82, in do_call
        exit_code = getattr(module, func_name)(args, parser)
      File "C:\Users\User\Anaconda3\lib\site-packages\conda\cli\main_update.py", line 20, in execute
        install(args, parser, 'update')
      File "C:\Users\User\Anaconda3\lib\site-packages\conda\cli\install.py", line 280, in install
        force_reinstall=context.force_reinstall or context.force,
      File "C:\Users\User\Anaconda3\lib\site-packages\conda\core\solve.py", line 112, in solve_for_transaction
        force_remove, force_reinstall)
      File "C:\Users\User\Anaconda3\lib\site-packages\conda\core\solve.py", line 150, in solve_for_diff
        force_remove)
      File "C:\Users\User\Anaconda3\lib\site-packages\conda\core\solve.py", line 261, in solve_final_state
        ssc.solution_precs = IndexedSet(PrefixGraph(ssc.solution_precs).graph)
      File "C:\Users\User\Anaconda3\lib\site-packages\conda\models\prefix_graph.py", line 47, in __init__
        self._toposort()
      File "C:\Users\User\Anaconda3\lib\site-packages\conda\models\prefix_graph.py", line 202, in _toposort
        sorted_nodes = tuple(self._topo_sort_handle_cycles(graph_copy))
      File "C:\Users\User\Anaconda3\lib\site-packages\conda\models\prefix_graph.py", line 259, in _topo_sort_handle_cycles
        yield cls._toposort_pop_key(graph)
      File "C:\Users\User\Anaconda3\lib\site-packages\conda\models\prefix_graph.py", line 274, in _toposort_pop_key
        (len(parents), node.name, node) for node, parents in iteritems(graph)
    TypeError: '<' not supported between instances of 'PrefixRecord' and 'PackageRecord'

`$ C:\Users\User\Anaconda3\Scripts\conda-script.py update anaconda`

  environment variables:
                 CIO_TEST=<not set>
        CONDA_DEFAULT_ENV=base
                CONDA_EXE=C:\Users\User\Anaconda3\condabin\..\Scripts\conda.exe
               CONDA_EXES="C:\Users\User\Anaconda3\condabin\..\Scripts\conda.exe"
             CONDA_PREFIX=C:\Users\User\Anaconda3
    CONDA_PROMPT_MODIFIER=(base)
         CONDA_PYTHON_EXE=C:\Users\User\Anaconda3\python.exe
               CONDA_ROOT=C:\Users\User\Anaconda3
              CONDA_SHLVL=1
                 HOMEPATH=\Users\User
                     PATH=C:\Users\User\Anaconda3;C:\Users\User\Anaconda3\Library\mingw-w64\bin;
                          C:\Users\User\Anaconda3\Library\usr\bin;C:\Users\User\Anaconda3\Librar
                          y\bin;C:\Users\User\Anaconda3\Scripts;C:\Users\User\Anaconda3\bin;C:\U
                          sers\User\Anaconda3;C:\Users\User\Anaconda3\Library\mingw-w64\bin;C:\U
                          sers\User\Anaconda3\Library\usr\bin;C:\Users\User\Anaconda3\Library\bi
                          n;C:\Users\User\Anaconda3\Scripts;C:\Users\User\Anaconda3\bin;C:\Windo
                          ws\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\Wi
                          ndowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files
                          (x86)\PuTTY\;C:\Program Files\Microsoft VS Code\bin;C:\Program
                          Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessComm
                          on\;C:\Users\User\AppData\Local\Microsoft\WindowsApps;
             PSMODULEPATH=C:\Program Files\WindowsPowerShell\Modules;C:\Windows\system32\Windows
                          PowerShell\v1.0\Modules
         PYTHONIOENCODING=1252
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>

     active environment : base
    active env location : C:\Users\User\Anaconda3
            shell level : 1
       user config file : C:\Users\User\.condarc
 populated config files :
          conda version : 4.7.5
    conda-build version : 3.15.1
         python version : 3.7.0.final.0
       virtual packages :
       base environment : C:\Users\User\Anaconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\Users\User\Anaconda3\pkgs
                          C:\Users\User\.conda\pkgs
                          C:\Users\User\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\User\Anaconda3\envs
                          C:\Users\User\.conda\envs
                          C:\Users\User\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.7.5 requests/2.19.1 CPython/3.7.0 Windows/10 Windows/10.0.17134
          administrator : False
             netrc file : None
           offline mode : False


An unexpected error has occurred. Conda has prepared the above report.

If submitted, this report will be used by core maintainers to improve
future releases of conda.
Would you like conda to send this report to the core maintainers?

[y/N]:

```

Tried installing Anaconda first followed by Miniconda but same errors.
Tried updating conda-build but errors again.
Tried removing conda-build but same errors again.
Removed previous Anaconda and Conda installations from all folders.

Any ideas?

**Comment by ciupicri** [comment]
Looks similar to my issue #11057 after updating to __conda 4.7.5__.

**Comment by dineshbvadhia** [comment]
Uninstalled Anaconda and re-installed. Performed 

> conda update anaconda

 BUT NOT

> conda update conda

And the Anaconda installation was successful. The command

> conda install <program-name>

also worked.

Looks like the problem is with updating conda itself. 

Closing this issue here as it belongs in the Conda rep.
