### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by RuikangSun** [ContinuumIO/anaconda-issues#11072]
Navigator Error

An unexpected error occurred on Navigator start-up
Report

Please report this issue in the anaconda issue tracker
Main Error

byte indices must be integers or slices, not str

Traceback

Traceback (most recent call last):
  File "D:\Anaconda3\lib\site-packages\anaconda_navigator\exceptions.py", line 75, in exception_handler
    return_value = func(*args, **kwargs)
  File "D:\Anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 120, in start_app
    window = run_app(splash)
  File "D:\Anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 63, in run_app
    window = MainWindow(splash=splash)
  File "D:\Anaconda3\lib\site-packages\anaconda_navigator\widgets\main_window.py", line 161, in __init__
    self.api = AnacondaAPI()
  File "D:\Anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 1258, in AnacondaAPI
    ANACONDA_API = _AnacondaAPI()
  File "D:\Anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 70, in __init__
    self._conda_api = CondaAPI()
  File "D:\Anaconda3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 1654, in CondaAPI
    CONDA_API = _CondaAPI()
  File "D:\Anaconda3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 345, in __init__
    self.set_conda_prefix()
  File "D:\Anaconda3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 494, in set_conda_prefix
    self.ROOT_PREFIX = info['root_prefix']
TypeError: byte indices must be integers or slices, not str

**Comment by RuikangSun** [comment]
I have tried "conda update anaconda-navigator".
However:
![gadgd](https://user-images.githubusercontent.com/20597187/60476658-fc247100-9cae-11e9-9a26-0e1f572eb353.png)

**Comment by RuikangSun** [comment]
I have followed #1837 but it doesn't work.

**Comment by RuikangSun** [comment]
Close old issues.
