### ISSUE TITLE
Anaconda navigator not working

### ISSUE THREAD

**Issue by MengLok** [ContinuumIO/anaconda-issues#11085]
### Actual Behavior

Whenever I open Anaconda Navigator there is a Navigator Error :

```
Navigator Error
An unexpected error occurred on Navigator start-up

Report
Please report this issue in the anaconda issue tracker

Main Error
byte indices must be integers or slices, not str
Traceback
Traceback (most recent call last):
  File "C:\Users\USER\Anaconda2\envs\py3k\lib\site-packages\anaconda_navigator\exceptions.py", line 75, in exception_handler
    return_value = func(*args, **kwargs)
  File "C:\Users\USER\Anaconda2\envs\py3k\lib\site-packages\anaconda_navigator\app\start.py", line 115, in start_app
    window = run_app(splash)
  File "C:\Users\USER\Anaconda2\envs\py3k\lib\site-packages\anaconda_navigator\app\start.py", line 58, in run_app
    window = MainWindow(splash=splash)
  File "C:\Users\USER\Anaconda2\envs\py3k\lib\site-packages\anaconda_navigator\widgets\main_window.py", line 160, in __init__
    self.api = AnacondaAPI()
  File "C:\Users\USER\Anaconda2\envs\py3k\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 1205, in AnacondaAPI
    ANACONDA_API = _AnacondaAPI()
  File "C:\Users\USER\Anaconda2\envs\py3k\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 65, in __init__
    self._conda_api = CondaAPI()
  File "C:\Users\USER\Anaconda2\envs\py3k\lib\site-packages\anaconda_navigator\api\conda_api.py", line 1622, in CondaAPI
    CONDA_API = _CondaAPI()
  File "C:\Users\USER\Anaconda2\envs\py3k\lib\site-packages\anaconda_navigator\api\conda_api.py", line 340, in __init__
    self.set_conda_prefix()
  File "C:\Users\USER\Anaconda2\envs\py3k\lib\site-packages\anaconda_navigator\api\conda_api.py", line 489, in set_conda_prefix
    self.ROOT_PREFIX = info['root_prefix']
TypeError: byte indices must be integers or slices, not str


```

### Expected Behavior

There shouldn't be an error and I should be able to access all the functions

### Steps to Reproduce

Whenever I try to open Anaconda Navigator

##### Anaconda or Miniconda version:

I am not sure as I need to open Anaconda Prompt to check but my Anaconda Prompt doesn't work as well!

##### `conda info`

<details>

```
My Anaconda Prompt doesn't work now so I cannot enter this command line.

```

</details>

##### `conda list --show-channel-urls`

<details>

```
My Anaconda Prompt doesn't work now so I cannot enter this command line.


```

</details>

**Comment by skvivekanand** [comment]
I am also facing same issue

**Comment by woodjuice** [comment]
I got the same problem
