### ISSUE TITLE
anaconda not loading. Error message not working; uninstall also failing 

### ISSUE THREAD

**Issue by VMS12** [ContinuumIO/anaconda-issues#11083]
##### `conda info`

<details>

```
PASTE OUTPUT HERE:

```

</details>

##### `conda list --show-channel-urls`

<details>

```
PASTE OUTPUT HERE:

```

</details>

**Comment by VMS12** [comment]
**anaconda not starting - receive the following message. Uninstall also not working**

Traceback
Traceback (most recent call last):
  File "/anaconda/lib/python3.6/site-packages/anaconda_navigator/exceptions.py", line 75, in exception_handler
    return_value = func(*args, **kwargs)
  File "/anaconda/lib/python3.6/site-packages/anaconda_navigator/app/start.py", line 115, in start_app
    window = run_app(splash)
  File "/anaconda/lib/python3.6/site-packages/anaconda_navigator/app/start.py", line 58, in run_app
    window = MainWindow(splash=splash)
  File "/anaconda/lib/python3.6/site-packages/anaconda_navigator/widgets/main_window.py", line 160, in __init__
    self.api = AnacondaAPI()
  File "/anaconda/lib/python3.6/site-packages/anaconda_navigator/api/anaconda_api.py", line 1205, in AnacondaAPI
    ANACONDA_API = _AnacondaAPI()
  File "/anaconda/lib/python3.6/site-packages/anaconda_navigator/api/anaconda_api.py", line 65, in __init__
    self._conda_api = CondaAPI()
  File "/anaconda/lib/python3.6/site-packages/anaconda_navigator/api/conda_api.py", line 1622, in CondaAPI
    CONDA_API = _CondaAPI()
  File "/anaconda/lib/python3.6/site-packages/anaconda_navigator/api/conda_api.py", line 340, in __init__
    self.set_conda_prefix()
  File "/anaconda/lib/python3.6/site-packages/anaconda_navigator/api/conda_api.py", line 488, in set_conda_prefix
    info = worker.communicate()[0]
  File "/anaconda/lib/python3.6/site-packages/anaconda_navigator/api/conda_api.py", line 266, in communicate
    " ".join(self._cmd_list), result[0]['message']
KeyError: 'message'
