### ISSUE TITLE
Ubuntu cryptography 0.4 undefined symbol: EC_GFp_nistp224_method

### ISSUE THREAD

**Issue by rchekaluk** [ContinuumIO/anaconda-issues#111]
Ubuntu Trusty 14.04, with recent libssl [patched for Heartbleed](http://discourse.ubuntu.com/t/the-heartbleed-bug/1607/5):

```
Package: libssl1.0.0                     
Version: 1.0.1f-1ubuntu2
```

cryptography 0.3 installs fine:

```
$ /usr/local/anaconda/bin/pip install cryptography==0.3
```

However cryptography 0.4 throws "undefined symbol: EC_GFp_nistp224_method":

```
$ /usr/local/anaconda/bin/pip install --upgrade cryptography
Downloading/unpacking cryptography from https://pypi.python.org/packages/source/c/cryptography/cryptography-0.4.tar.gz#md5=d1bb13648a12eda2a54653ba113d2e84
  Downloading cryptography-0.4.tar.gz (260kB): 260kB downloaded
  Running setup.py (path:/tmp/pip_build_ubuntu/cryptography/setup.py) egg_info for package cryptography

    building '_Cryptography_cffi_684bb40axf342507b' extension
    gcc -pthread -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/usr/local/anaconda/include/python2.7 -c cryptography/hazmat/primitives/__pycache__/_Cryptography_cffi_684bb40axf342507b.c -o /tmp/pip_build_ubuntu/cryptography/cryptography/hazmat/primitives/__pycache__/cryptography/hazmat/primitives/__pycache__/_Cryptography_cffi_684bb40axf342507b.o
    gcc -pthread -shared /tmp/pip_build_ubuntu/cryptography/cryptography/hazmat/primitives/__pycache__/cryptography/hazmat/primitives/__pycache__/_Cryptography_cffi_684bb40axf342507b.o -L/usr/local/anaconda/lib -lpython2.7 -o /tmp/pip_build_ubuntu/cryptography/cryptography/hazmat/primitives/__pycache__/_Cryptography_cffi_684bb40axf342507b.so
    building '_Cryptography_cffi_8f86901cxc1767c5a' extension
    gcc -pthread -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/usr/local/anaconda/include/python2.7 -c cryptography/hazmat/primitives/__pycache__/_Cryptography_cffi_8f86901cxc1767c5a.c -o /tmp/pip_build_ubuntu/cryptography/cryptography/hazmat/primitives/__pycache__/cryptography/hazmat/primitives/__pycache__/_Cryptography_cffi_8f86901cxc1767c5a.o
    gcc -pthread -shared /tmp/pip_build_ubuntu/cryptography/cryptography/hazmat/primitives/__pycache__/cryptography/hazmat/primitives/__pycache__/_Cryptography_cffi_8f86901cxc1767c5a.o -L/usr/local/anaconda/lib -lpython2.7 -o /tmp/pip_build_ubuntu/cryptography/cryptography/hazmat/primitives/__pycache__/_Cryptography_cffi_8f86901cxc1767c5a.so
    building '_Cryptography_cffi_444d7397xa22f8491' extension
    gcc -pthread -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/usr/local/anaconda/include/python2.7 -c cryptography/hazmat/bindings/__pycache__/_Cryptography_cffi_444d7397xa22f8491.c -o /tmp/pip_build_ubuntu/cryptography/cryptography/hazmat/bindings/__pycache__/cryptography/hazmat/bindings/__pycache__/_Cryptography_cffi_444d7397xa22f8491.o
    gcc -pthread -shared /tmp/pip_build_ubuntu/cryptography/cryptography/hazmat/bindings/__pycache__/cryptography/hazmat/bindings/__pycache__/_Cryptography_cffi_444d7397xa22f8491.o -L/usr/local/anaconda/lib -lcrypto -lssl -lpython2.7 -o /tmp/pip_build_ubuntu/cryptography/cryptography/hazmat/bindings/__pycache__/_Cryptography_cffi_444d7397xa22f8491.so
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/tmp/pip_build_ubuntu/cryptography/setup.py", line 174, in <module>
        "test": PyTest,
      File "/usr/local/anaconda/lib/python2.7/distutils/core.py", line 152, in setup
        dist.run_commands()
      File "/usr/local/anaconda/lib/python2.7/distutils/dist.py", line 953, in run_commands
        self.run_command(cmd)
      File "/usr/local/anaconda/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "<string>", line 15, in replacement_run
      File "/usr/local/anaconda/lib/python2.7/site-packages/setuptools-3.4.4-py2.7.egg/setuptools/command/egg_info.py", line 186, in find_sources
      File "/usr/local/anaconda/lib/python2.7/site-packages/setuptools-3.4.4-py2.7.egg/setuptools/command/egg_info.py", line 246, in run
      File "/usr/local/anaconda/lib/python2.7/site-packages/setuptools-3.4.4-py2.7.egg/setuptools/command/egg_info.py", line 282, in add_defaults
      File "/usr/local/anaconda/lib/python2.7/site-packages/setuptools-3.4.4-py2.7.egg/setuptools/command/sdist.py", line 167, in add_defaults
      File "/usr/local/anaconda/lib/python2.7/distutils/cmd.py", line 312, in get_finalized_command
        cmd_obj.ensure_finalized()
      File "/usr/local/anaconda/lib/python2.7/distutils/cmd.py", line 109, in ensure_finalized
        self.finalize_options()
      File "/usr/local/anaconda/lib/python2.7/site-packages/setuptools-3.4.4-py2.7.egg/setuptools/command/build_py.py", line 26, in finalize_options
      File "/usr/local/anaconda/lib/python2.7/distutils/command/build_py.py", line 46, in finalize_options
        ('force', 'force'))
      File "/usr/local/anaconda/lib/python2.7/distutils/cmd.py", line 298, in set_undefined_options
        src_cmd_obj.ensure_finalized()
      File "/usr/local/anaconda/lib/python2.7/distutils/cmd.py", line 109, in ensure_finalized
        self.finalize_options()
      File "/tmp/pip_build_ubuntu/cryptography/setup.py", line 88, in finalize_options
        self.distribution.ext_modules = get_ext_modules()
      File "/tmp/pip_build_ubuntu/cryptography/setup.py", line 68, in get_ext_modules
        OpenSSLBinding().ffi.verifier.get_extension(),
      File "cryptography/hazmat/bindings/openssl/binding.py", line 87, in __init__
        self._ensure_ffi_initialized()
      File "cryptography/hazmat/bindings/openssl/binding.py", line 106, in _ensure_ffi_initialized
        libraries=libraries,
      File "cryptography/hazmat/bindings/utils.py", line 80, in build_ffi
        extra_link_args=extra_link_args,
      File "/usr/local/anaconda/lib/python2.7/site-packages/cffi/api.py", line 341, in verify
        lib = self.verifier.load_library()
      File "/usr/local/anaconda/lib/python2.7/site-packages/cffi/verifier.py", line 75, in load_library
        return self._load_library()
      File "/usr/local/anaconda/lib/python2.7/site-packages/cffi/verifier.py", line 151, in _load_library
        return self._vengine.load_library()
      File "/usr/local/anaconda/lib/python2.7/site-packages/cffi/vengine_cpy.py", line 138, in load_library
        raise ffiplatform.VerificationError(error)
    cffi.ffiplatform.VerificationError: importing '/tmp/pip_build_ubuntu/cryptography/cryptography/hazmat/bindings/__pycache__/_Cryptography_cffi_444d7397xa22f8491.so': /tmp/pip_build_ubuntu/cryptography/cryptography/hazmat/bindings/__pycache__/_Cryptography_cffi_444d7397xa22f8491.so: undefined symbol: EC_GFp_nistp224_method
    Complete output from command python setup.py egg_info:
    running egg_info

creating pip-egg-info/cryptography.egg-info

writing requirements to pip-egg-info/cryptography.egg-info/requires.txt

writing pip-egg-info/cryptography.egg-info/PKG-INFO

writing top-level names to pip-egg-info/cryptography.egg-info/top_level.txt

writing dependency_links to pip-egg-info/cryptography.egg-info/dependency_links.txt

writing manifest file 'pip-egg-info/cryptography.egg-info/SOURCES.txt'

warning: manifest_maker: standard file '-c' not found



running build_ext

building '_Cryptography_cffi_684bb40axf342507b' extension

creating /tmp/pip_build_ubuntu/cryptography/cryptography/hazmat/primitives/__pycache__/cryptography

creating /tmp/pip_build_ubuntu/cryptography/cryptography/hazmat/primitives/__pycache__/cryptography/hazmat

creating /tmp/pip_build_ubuntu/cryptography/cryptography/hazmat/primitives/__pycache__/cryptography/hazmat/primitives

creating /tmp/pip_build_ubuntu/cryptography/cryptography/hazmat/primitives/__pycache__/cryptography/hazmat/primitives/__pycache__

gcc -pthread -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/usr/local/anaconda/include/python2.7 -c cryptography/hazmat/primitives/__pycache__/_Cryptography_cffi_684bb40axf342507b.c -o /tmp/pip_build_ubuntu/cryptography/cryptography/hazmat/primitives/__pycache__/cryptography/hazmat/primitives/__pycache__/_Cryptography_cffi_684bb40axf342507b.o

gcc -pthread -shared /tmp/pip_build_ubuntu/cryptography/cryptography/hazmat/primitives/__pycache__/cryptography/hazmat/primitives/__pycache__/_Cryptography_cffi_684bb40axf342507b.o -L/usr/local/anaconda/lib -lpython2.7 -o /tmp/pip_build_ubuntu/cryptography/cryptography/hazmat/primitives/__pycache__/_Cryptography_cffi_684bb40axf342507b.so

running build_ext

building '_Cryptography_cffi_8f86901cxc1767c5a' extension

gcc -pthread -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/usr/local/anaconda/include/python2.7 -c cryptography/hazmat/primitives/__pycache__/_Cryptography_cffi_8f86901cxc1767c5a.c -o /tmp/pip_build_ubuntu/cryptography/cryptography/hazmat/primitives/__pycache__/cryptography/hazmat/primitives/__pycache__/_Cryptography_cffi_8f86901cxc1767c5a.o

gcc -pthread -shared /tmp/pip_build_ubuntu/cryptography/cryptography/hazmat/primitives/__pycache__/cryptography/hazmat/primitives/__pycache__/_Cryptography_cffi_8f86901cxc1767c5a.o -L/usr/local/anaconda/lib -lpython2.7 -o /tmp/pip_build_ubuntu/cryptography/cryptography/hazmat/primitives/__pycache__/_Cryptography_cffi_8f86901cxc1767c5a.so

running build_ext

building '_Cryptography_cffi_444d7397xa22f8491' extension

creating /tmp/pip_build_ubuntu/cryptography/cryptography/hazmat/bindings/__pycache__/cryptography

creating /tmp/pip_build_ubuntu/cryptography/cryptography/hazmat/bindings/__pycache__/cryptography/hazmat

creating /tmp/pip_build_ubuntu/cryptography/cryptography/hazmat/bindings/__pycache__/cryptography/hazmat/bindings

creating /tmp/pip_build_ubuntu/cryptography/cryptography/hazmat/bindings/__pycache__/cryptography/hazmat/bindings/__pycache__

gcc -pthread -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/usr/local/anaconda/include/python2.7 -c cryptography/hazmat/bindings/__pycache__/_Cryptography_cffi_444d7397xa22f8491.c -o /tmp/pip_build_ubuntu/cryptography/cryptography/hazmat/bindings/__pycache__/cryptography/hazmat/bindings/__pycache__/_Cryptography_cffi_444d7397xa22f8491.o

gcc -pthread -shared /tmp/pip_build_ubuntu/cryptography/cryptography/hazmat/bindings/__pycache__/cryptography/hazmat/bindings/__pycache__/_Cryptography_cffi_444d7397xa22f8491.o -L/usr/local/anaconda/lib -lcrypto -lssl -lpython2.7 -o /tmp/pip_build_ubuntu/cryptography/cryptography/hazmat/bindings/__pycache__/_Cryptography_cffi_444d7397xa22f8491.so

Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/tmp/pip_build_ubuntu/cryptography/setup.py", line 174, in <module>

    "test": PyTest,

  File "/usr/local/anaconda/lib/python2.7/distutils/core.py", line 152, in setup

    dist.run_commands()

  File "/usr/local/anaconda/lib/python2.7/distutils/dist.py", line 953, in run_commands

    self.run_command(cmd)

  File "/usr/local/anaconda/lib/python2.7/distutils/dist.py", line 972, in run_command

    cmd_obj.run()

  File "<string>", line 15, in replacement_run

  File "/usr/local/anaconda/lib/python2.7/site-packages/setuptools-3.4.4-py2.7.egg/setuptools/command/egg_info.py", line 186, in find_sources

  File "/usr/local/anaconda/lib/python2.7/site-packages/setuptools-3.4.4-py2.7.egg/setuptools/command/egg_info.py", line 246, in run

  File "/usr/local/anaconda/lib/python2.7/site-packages/setuptools-3.4.4-py2.7.egg/setuptools/command/egg_info.py", line 282, in add_defaults

  File "/usr/local/anaconda/lib/python2.7/site-packages/setuptools-3.4.4-py2.7.egg/setuptools/command/sdist.py", line 167, in add_defaults

  File "/usr/local/anaconda/lib/python2.7/distutils/cmd.py", line 312, in get_finalized_command

    cmd_obj.ensure_finalized()

  File "/usr/local/anaconda/lib/python2.7/distutils/cmd.py", line 109, in ensure_finalized

    self.finalize_options()

  File "/usr/local/anaconda/lib/python2.7/site-packages/setuptools-3.4.4-py2.7.egg/setuptools/command/build_py.py", line 26, in finalize_options

  File "/usr/local/anaconda/lib/python2.7/distutils/command/build_py.py", line 46, in finalize_options

    ('force', 'force'))

  File "/usr/local/anaconda/lib/python2.7/distutils/cmd.py", line 298, in set_undefined_options

    src_cmd_obj.ensure_finalized()

  File "/usr/local/anaconda/lib/python2.7/distutils/cmd.py", line 109, in ensure_finalized

    self.finalize_options()

  File "/tmp/pip_build_ubuntu/cryptography/setup.py", line 88, in finalize_options

    self.distribution.ext_modules = get_ext_modules()

  File "/tmp/pip_build_ubuntu/cryptography/setup.py", line 68, in get_ext_modules

    OpenSSLBinding().ffi.verifier.get_extension(),

  File "cryptography/hazmat/bindings/openssl/binding.py", line 87, in __init__

    self._ensure_ffi_initialized()

  File "cryptography/hazmat/bindings/openssl/binding.py", line 106, in _ensure_ffi_initialized

    libraries=libraries,

  File "cryptography/hazmat/bindings/utils.py", line 80, in build_ffi

    extra_link_args=extra_link_args,

  File "/usr/local/anaconda/lib/python2.7/site-packages/cffi/api.py", line 341, in verify

    lib = self.verifier.load_library()

  File "/usr/local/anaconda/lib/python2.7/site-packages/cffi/verifier.py", line 75, in load_library

    return self._load_library()

  File "/usr/local/anaconda/lib/python2.7/site-packages/cffi/verifier.py", line 151, in _load_library

    return self._vengine.load_library()

  File "/usr/local/anaconda/lib/python2.7/site-packages/cffi/vengine_cpy.py", line 138, in load_library

    raise ffiplatform.VerificationError(error)

cffi.ffiplatform.VerificationError: importing '/tmp/pip_build_ubuntu/cryptography/cryptography/hazmat/bindings/__pycache__/_Cryptography_cffi_444d7397xa22f8491.so': /tmp/pip_build_ubuntu/cryptography/cryptography/hazmat/bindings/__pycache__/_Cryptography_cffi_444d7397xa22f8491.so: undefined symbol: EC_GFp_nistp224_method

----------------------------------------
Cleaning up...
```

Seems related to these but not exactly the same since DYLD_LIBRARY_PATH workaround has no effect:
- https://github.com/ContinuumIO/anaconda-issues/issues/110
- https://github.com/conda/conda-build/issues/61
- http://software-carpentry.org/blog/2014/04/mr-biczo-was-right.html

Symbol appears to have been added "[between (OpenSSL) 1.0.0h and 1.0.1](https://www.openssl.org/news/changelog.html)"

**Comment by hadim** [comment]
Same error here even after `conda install cryptography` : 

```sh
$ python -c "import OpenSSL"
Traceback (most recent call last):
  File "/home/hadim/local/conda/envs/web/lib/python3.4/site-packages/cffi/vengine_cpy.py", line 150, in load_library
    self.verifier.modulefilename)
ImportError: /home/hadim/local/conda/envs/web/lib/python3.4/site-packages/cryptography/_Cryptography_cffi_e9178e86x399b1113.cpython-34m.so: undefined symbol: EC_GFp_nistp224_method

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/hadim/local/conda/envs/web/lib/python3.4/site-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import rand, crypto, SSL
  File "/home/hadim/local/conda/envs/web/lib/python3.4/site-packages/OpenSSL/rand.py", line 11, in <module>
    from OpenSSL._util import (
  File "/home/hadim/local/conda/envs/web/lib/python3.4/site-packages/OpenSSL/_util.py", line 7, in <module>
    binding = Binding()
  File "/home/hadim/local/conda/envs/web/lib/python3.4/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 114, in __init__
    self._ensure_ffi_initialized()
  File "/home/hadim/local/conda/envs/web/lib/python3.4/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 126, in _ensure_ffi_initialized
    cls._modules,
  File "/home/hadim/local/conda/envs/web/lib/python3.4/site-packages/cryptography/hazmat/bindings/utils.py", line 31, in load_library_for_binding
    lib = ffi.verifier.load_library()
  File "/home/hadim/local/conda/envs/web/lib/python3.4/site-packages/cffi/verifier.py", line 97, in load_library
    return self._load_library()
  File "/home/hadim/local/conda/envs/web/lib/python3.4/site-packages/cffi/verifier.py", line 207, in _load_library
    return self._vengine.load_library()
  File "/home/hadim/local/conda/envs/web/lib/python3.4/site-packages/cffi/vengine_cpy.py", line 153, in load_library
    raise ffiplatform.VerificationError(error)
cffi.ffiplatform.VerificationError: importing '/home/hadim/local/conda/envs/web/lib/python3.4/site-packages/cryptography/_Cryptography_cffi_e9178e86x399b1113.cpython-34m.so': /home/hadim/local/conda/envs/web/lib/python3.4/site-packages/cryptography/_Cryptography_cffi_e9178e86x399b1113.cpython-34m.so: undefined symbol: EC_GFp_nistp224_method
```

```sh
 $ conda info
Current conda install:

             platform : linux-64
        conda version : 3.10.1
  conda-build version : 1.12.0
       python version : 3.4.3.final.0
     requests version : 2.6.0
     root environment : /home/hadim/local/conda  (writable)
  default environment : /home/hadim/local/conda/envs/web
     envs directories : /home/hadim/local/conda/envs
        package cache : /home/hadim/local/conda/pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/linux-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/linux-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : None
    is foreign system : False
```

**Comment by asmeurer** [comment]
@hadim perhaps a `conda install -f cryptography` will fix it for you.

**Comment by hargup** [comment]
`conda install -f cryptography` didn't work for me, I had to first delete the cryptography package directory and then install it.
`
rm -rf /home/hargup/anaconda/lib/python2.7/site-packages/cryptography
`
