### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by Rickzhang512** [ContinuumIO/anaconda-issues#11100]
## Main error
Application <b>spyder</b> launch may have produced errors.
## Traceback
```
Traceback (most recent call last):
  File "C:\Users\lenovo\Anaconda3\lib\site-packages\qtpy\QtWebEngineWidgets.py", line 22, in <module>
    from PyQt5.QtWebEngineWidgets import QWebEnginePage
ImportError: No module named 'PyQt5.QtWebEngineWidgets'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\lenovo\Anaconda3\Scripts\spyder-script.py", line 5, in <module>
    sys.exit(spyder.app.start.main())
  File "C:\Users\lenovo\Anaconda3\lib\site-packages\spyder\app\start.py", line 103, in main
    from spyder.app import mainwindow
  File "C:\Users\lenovo\Anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 92, in <module>
    from qtpy import QtWebEngineWidgets  # analysis:ignore
  File "C:\Users\lenovo\Anaconda3\lib\site-packages\qtpy\QtWebEngineWidgets.py", line 26, in <module>
    from PyQt5.QtWebKitWidgets import QWebPage as QWebEnginePage
ImportError: No module named 'PyQt5.QtWebKitWidgets'

```
## System information
```
python: 3.5.3
platform: win-64
pyqt: 5.6.0
os: Windows;10;10.0.17763;AMD64;Intel64 Family 6 Model 78 Stepping 3, GenuineIntel
language: zh_CN
version: 1.6.2
qt: 5.13.0
conda: 4.3.30
```

**Comment by csoja** [comment]
I'm not sure what is causing your error. However, it looks like you are running very old software. I'd recommend updating conda and anaconda-navigator and spyder. I'm going to close this - please open a new issue if you are still having problems with the latest Spyder, conda, and Anaconda-Navigator.
