### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by raissk** [ContinuumIO/anaconda-issues#11106]
I followed the instructions to update spyder, but now when I launch it through Anaconda, I get the following error (I also tried running spyder through the command prompt but am getting another error):

## Main error
Application <b>spyder</b> launch may have produced errors.
## Traceback
```
Traceback (most recent call last):
  File "C:\Users\raissa\AppData\Local\Continuum\Anaconda3\Scripts\spyder-script.py", line 10, in <module>
    sys.exit(main())
  File "C:\Users\raissa\AppData\Local\Continuum\Anaconda3\lib\site-packages\spyder\app\start.py", line 186, in main
    from spyder.app import mainwindow
  File "C:\Users\raissa\AppData\Local\Continuum\Anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 49, in <module>
    requirements.check_spyder_kernels()
  File "C:\Users\raissa\AppData\Local\Continuum\Anaconda3\lib\site-packages\spyder\requirements.py", line 66, in check_spyder_kernels
    % actual_ver)
  File "C:\Users\raissa\AppData\Local\Continuum\Anaconda3\lib\site-packages\spyder\requirements.py", line 24, in show_warning
    raise RuntimeError(message)
RuntimeError: Please check Spyder installation requirements:
spyder-kernels < 1.0 is required (found 1.4.0).

```
## System information
```
python: 3.6.8
language: en_CA
os: Windows;10;10.0.17763;AMD64;Intel64 Family 6 Model 79 Stepping 1, GenuineIntel
version: 1.6.2
platform: win-64
qt: 5.9.6
pyqt: 5.9.2
conda: 4.7.5
```

**Comment by shuntera** [comment]
Same error for me, though I am on a mac.
