### ISSUE TITLE
Anaconda-Navigator won't open on Mac OSX

### ISSUE THREAD

**Issue by lolmaster31** [ContinuumIO/anaconda-issues#11101]
### Actual Behavior

When I double-click on the "Anaconda-Navigator" shortcut in my Anaconda3 folder downloaded in my HD, the logo pops up with the fine print text "initializing..." but then disappears and opens an error message in Safari with the following content:

"Navigator Error

An unexpected error occurred on Navigator start-up

Report

Please report this issue in the anaconda issue tracker

Main Error

expected str, bytes or os.PathLike object, not NoneType
Traceback

Traceback (most recent call last):
  File "/anaconda3/lib/python3.7/site-packages/anaconda_navigator/exceptions.py", line 75, in exception_handler
    return_value = func(*args, **kwargs)
  File "/anaconda3/lib/python3.7/site-packages/anaconda_navigator/app/start.py", line 151, in start_app
    window = run_app(splash)
  File "/anaconda3/lib/python3.7/site-packages/anaconda_navigator/app/start.py", line 65, in run_app
    window = MainWindow(splash=splash, tab_project=False)
  File "/anaconda3/lib/python3.7/site-packages/anaconda_navigator/widgets/main_window.py", line 168, in __init__
    self.api = AnacondaAPI()
  File "/anaconda3/lib/python3.7/site-packages/anaconda_navigator/api/anaconda_api.py", line 2337, in AnacondaAPI
    ANACONDA_API = _AnacondaAPI()
  File "/anaconda3/lib/python3.7/site-packages/anaconda_navigator/api/anaconda_api.py", line 89, in __init__
    self._conda_api = CondaAPI()
  File "/anaconda3/lib/python3.7/site-packages/anaconda_navigator/api/conda_api.py", line 1773, in CondaAPI
    CONDA_API = _CondaAPI()
  File "/anaconda3/lib/python3.7/site-packages/anaconda_navigator/api/conda_api.py", line 353, in __init__
    self.sys_rc_path = join(self.ROOT_PREFIX, '.condarc')
  File "/anaconda3/lib/python3.7/posixpath.py", line 80, in join
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType"

### Expected Behavior

I was expecting an instance of the Navigator to open.

### Steps to Reproduce

1. In Mac OSX, find install location of "anaconda3".

2. Double click on the "anaconda3" folder, then double click on "Anaconda-Navigator".

##### Anaconda or Miniconda version:

Anaconda 2019.03 for Mac OS

##### Operating System:
MacOS Mojave Version 10.14.5
##### `conda info`

<details>

```
-bash: conda: command not found

```

</details>

##### `conda list --show-channel-urls`

<details>

```
-bash: conda: command not found

```

</details>

**Comment by nicksome168** [comment]
I have the same problem right after I run the command ` conda update -n base -c defaults conda`
I am using Mac OS high sierra (10.13.6) and current conda version 4.7.5
