### ISSUE TITLE
Navigator Error `root_prefix`

### ISSUE THREAD

**Issue by ShauryaUppal-1Mg** [ContinuumIO/anaconda-issues#11107]
![Screenshot 2019-07-12 at 5 41 09 PM](https://user-images.githubusercontent.com/47315683/61127249-610c7200-a4cc-11e9-9cbd-3de7362fec7c.png)

Navigator Error
An unexpected error occurred on Navigator start-up

Report
Please report this issue in the anaconda issue tracker

Main Error
'root_prefix'
Traceback
Traceback (most recent call last):
  File "/anaconda3/lib/python3.6/site-packages/anaconda_navigator/exceptions.py", line 75, in exception_handler
    return_value = func(*args, **kwargs)
  File "/anaconda3/lib/python3.6/site-packages/anaconda_navigator/app/start.py", line 151, in start_app
    window = run_app(splash)
  File "/anaconda3/lib/python3.6/site-packages/anaconda_navigator/app/start.py", line 65, in run_app
    window = MainWindow(splash=splash, tab_project=False)
  File "/anaconda3/lib/python3.6/site-packages/anaconda_navigator/widgets/main_window.py", line 168, in __init__
    self.api = AnacondaAPI()
  File "/anaconda3/lib/python3.6/site-packages/anaconda_navigator/api/anaconda_api.py", line 2337, in AnacondaAPI
    ANACONDA_API = _AnacondaAPI()
  File "/anaconda3/lib/python3.6/site-packages/anaconda_navigator/api/anaconda_api.py", line 89, in __init__
    self._conda_api = CondaAPI()
  File "/anaconda3/lib/python3.6/site-packages/anaconda_navigator/api/conda_api.py", line 1767, in CondaAPI
    CONDA_API = _CondaAPI()
  File "/anaconda3/lib/python3.6/site-packages/anaconda_navigator/api/conda_api.py", line 350, in __init__
    self.set_conda_prefix(info=get_conda_info())
  File "/anaconda3/lib/python3.6/site-packages/anaconda_navigator/api/conda_api.py", line 505, in set_conda_prefix
    self.ROOT_PREFIX = info['root_prefix']
KeyError: 'root_prefix'

**Comment by hellymac** [comment]
Main Error

'root_prefix'
Traceback

Traceback (most recent call last):
  File "/Users/me/anaconda3/lib/python3.6/site-packages/anaconda_navigator/exceptions.py", line 75, in exception_handler
    return_value = func(*args, **kwargs)
  File "/Users/me/anaconda3/lib/python3.6/site-packages/anaconda_navigator/app/start.py", line 151, in start_app
    window = run_app(splash)
  File "/Users/me/anaconda3/lib/python3.6/site-packages/anaconda_navigator/app/start.py", line 65, in run_app
    window = MainWindow(splash=splash, tab_project=False)
  File "/Users/me/anaconda3/lib/python3.6/site-packages/anaconda_navigator/widgets/main_window.py", line 168, in __init__
    self.api = AnacondaAPI()
  File "/Users/me/anaconda3/lib/python3.6/site-packages/anaconda_navigator/api/anaconda_api.py", line 2337, in AnacondaAPI
    ANACONDA_API = _AnacondaAPI()
  File "/Users/me/anaconda3/lib/python3.6/site-packages/anaconda_navigator/api/anaconda_api.py", line 89, in __init__
    self._conda_api = CondaAPI()
  File "/Users/me/anaconda3/lib/python3.6/site-packages/anaconda_navigator/api/conda_api.py", line 1773, in CondaAPI
    CONDA_API = _CondaAPI()
  File "/Users/me/anaconda3/lib/python3.6/site-packages/anaconda_navigator/api/conda_api.py", line 350, in __init__
    self.set_conda_prefix(info=get_conda_info())
  File "/Users/me/anaconda3/lib/python3.6/site-packages/anaconda_navigator/api/conda_api.py", line 505, in set_conda_prefix
    self.ROOT_PREFIX = info['root_prefix']
KeyError: 'root_prefix'

Same issue on macOS

**Comment by Fr33raNg3r** [comment]
sama issue on windows10 pro

**Comment by csoja** [comment]
What is the output of _conda info_ and _conda list --show-channel-urls_?  (You'll need to run these in a terminal or in the Anaconda Prompt if you are on Windows.)

**Comment by hellymac** [comment]
I uninstall anaconda (remove "anaconda3" file) and re install anaconda
It works

**Comment by OrlandoGrigo** [comment]
I have excatly the same issue.
Any possible fix?

I can list all the channels. I tried to update conda but got the error message:
"**CustomValidationError: Parameter channel_priority = 'strict' declared in <<merged>> is invalid.
The value 'strict' cannot be boolified.**"

**Comment by csoja** [comment]
Make sure you are running the latest version of anaconda navigator.  
In a terminal or the Anaconda Command Prompt:
_conda update conda
conda update anaconda-navigator
conda update navigator-updater_

If the problem persists after the updates, please see if any of the suggestions in the Navigator troubleshooting section help: https://docs.anaconda.com/anaconda/navigator/troubleshooting/

If not, please open a new issue.
