### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by hsingh574** [ContinuumIO/anaconda-issues#11117]
## Main error
An unexpected error occurred on Navigator start-up<br>psutil.AccessDenied (pid=1189)
## Traceback
```
Traceback (most recent call last):
  File "/Users/harman/anaconda/lib/python3.6/site-packages/psutil/_psosx.py", line 348, in catch_zombie
    yield
  File "/Users/harman/anaconda/lib/python3.6/site-packages/psutil/_psosx.py", line 412, in cmdline
    return cext.proc_cmdline(self.pid)
ProcessLookupError: [Errno 3] No such process

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/harman/anaconda/lib/python3.6/site-packages/anaconda_navigator/exceptions.py", line 75, in exception_handler
    return_value = func(*args, **kwargs)
  File "/Users/harman/anaconda/lib/python3.6/site-packages/anaconda_navigator/app/start.py", line 108, in start_app
    if misc.load_pid() is None:  # A stale lock might be around
  File "/Users/harman/anaconda/lib/python3.6/site-packages/anaconda_navigator/utils/misc.py", line 384, in load_pid
    cmds = process.cmdline()
  File "/Users/harman/anaconda/lib/python3.6/site-packages/psutil/__init__.py", line 661, in cmdline
    return self._proc.cmdline()
  File "/Users/harman/anaconda/lib/python3.6/site-packages/psutil/_psosx.py", line 330, in wrapper
    return fun(self, *args, **kwargs)
  File "/Users/harman/anaconda/lib/python3.6/site-packages/psutil/_psosx.py", line 412, in cmdline
    return cext.proc_cmdline(self.pid)
  File "/Users/harman/anaconda/lib/python3.6/contextlib.py", line 99, in __exit__
    self.gen.throw(type, value, traceback)
  File "/Users/harman/anaconda/lib/python3.6/site-packages/psutil/_psosx.py", line 361, in catch_zombie
    raise AccessDenied(proc.pid, proc._name)
psutil._exceptions.AccessDenied: psutil.AccessDenied (pid=1189)

```
## System information
```
python: 3.6.7
language: en
os: Darwin;17.7.0;Darwin Kernel Version 17.7.0: Thu Jun 21 22:53:14 PDT 2018; root:xnu-4570.71.2~1/RELEASE_X86_64;x86_64;i386
version: 1.6.2
platform: osx-64
qt: 5.6.2
pyqt: 5.6.0
conda: 4.6.14
```

**Comment by csoja** [comment]
In the terminal:

conda update conda
conda update anaconda-navigator
conda update navigator-updater
anaconda-navigator --reset

The last command is the key to fixing your issue - as it removes the lock file that is causing your problem.
