### ISSUE TITLE
Unable to query `conda info`

### ISSUE THREAD

**Issue by arranjdavis** [ContinuumIO/anaconda-issues#11120]
Hello,

It seems I have messed up something with my Anaconda Navigator / something worse than that. I am on a MacOS (Mojave 10.14.5) and the Anaconda Navigator will not launch from the desktop or from the terminal.

### Actual Behavior ###

But to debug this it seems like I need to run the `conda info` command. However, this produces the following error:

    Traceback (most recent call last):
      File "/anaconda3/lib/python3.6/site-packages/conda/exceptions.py", line 1043, in __call__
        return func(*args, **kwargs)
      File "/anaconda3/lib/python3.6/site-packages/conda/cli/main.py", line 84, in _main
        exit_code = do_call(args, p)
      File "/anaconda3/lib/python3.6/site-packages/conda/cli/conda_argparse.py", line 80, in do_call
        module = import_module(relative_mod, __name__.rsplit('.', 1)[0])
      File "/anaconda3/lib/python3.6/importlib/__init__.py", line 126, in import_module
        return _bootstrap._gcd_import(name[level:], package, level)
      File "<frozen importlib._bootstrap>", line 994, in _gcd_import
      File "<frozen importlib._bootstrap>", line 971, in _find_and_load
      File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
      File "<frozen importlib._bootstrap_external>", line 678, in exec_module
      File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
      File "/anaconda3/lib/python3.6/site-packages/conda/cli/main_info.py", line 19, in <module>
        from ..core.index import _supplement_index_with_system
      File "/anaconda3/lib/python3.6/site-packages/conda/core/index.py", line 9, in <module>
        from .package_cache_data import PackageCacheData
      File "/anaconda3/lib/python3.6/site-packages/conda/core/package_cache_data.py", line 15, in <module>
        from conda_package_handling.api import InvalidArchiveError
      File "/anaconda3/lib/python3.6/site-packages/conda_package_handling/api.py", line 3, in <module>
        from libarchive.exception import ArchiveError as _LibarchiveArchiveError
      File "/anaconda3/lib/python3.6/site-packages/libarchive/__init__.py", line 1, in <module>
        from .entry import ArchiveEntry
      File "/anaconda3/lib/python3.6/site-packages/libarchive/entry.py", line 4, in <module>
        from ctypes import c_char_p, create_string_buffer
      File "/anaconda3/lib/python3.6/ctypes/__init__.py", line 7, in <module>
        from _ctypes import Union, Structure, Array
    ImportError: dlopen(/anaconda3/lib/python3.6/lib-dynload/_ctypes.cpython-36m-darwin.so, 2): Library not loaded: @rpath/libffi.6.dylib
      Referenced from: /anaconda3/lib/python3.6/lib-dynload/_ctypes.cpython-36m-darwin.so
      Reason: image not found

$ /anaconda3/bin/conda info`

### Expected Behavior ###

I expect to get a normal output from the `conda info` command.

### Steps to Reproduce

Enter `conda info` into the terminal (and who knows what I did in the past to get myself in this situation!).

##### `conda info`

This is exactly what is not working (see above error message).

##### `conda list --show-channel-urls`

<details>

```
Traceback (most recent call last):
  File "/anaconda3/lib/python3.6/site-packages/conda/exceptions.py", line 1043, in __call__
    return func(*args, **kwargs)
  File "/anaconda3/lib/python3.6/site-packages/conda/cli/main.py", line 84, in _main
    exit_code = do_call(args, p)
  File "/anaconda3/lib/python3.6/site-packages/conda/cli/conda_argparse.py", line 80, in do_call
    module = import_module(relative_mod, __name__.rsplit('.', 1)[0])
  File "/anaconda3/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/anaconda3/lib/python3.6/site-packages/conda/cli/main_list.py", line 14, in <module>
    from ..core.prefix_data import PrefixData
  File "/anaconda3/lib/python3.6/site-packages/conda/core/prefix_data.py", line 24, in <module>
    from ..gateways.disk.create import write_as_json_to_file
  File "/anaconda3/lib/python3.6/site-packages/conda/gateways/disk/create.py", line 17, in <module>
    import conda_package_handling.api
  File "/anaconda3/lib/python3.6/site-packages/conda_package_handling/api.py", line 3, in <module>
    from libarchive.exception import ArchiveError as _LibarchiveArchiveError
  File "/anaconda3/lib/python3.6/site-packages/libarchive/__init__.py", line 1, in <module>
    from .entry import ArchiveEntry
  File "/anaconda3/lib/python3.6/site-packages/libarchive/entry.py", line 4, in <module>
    from ctypes import c_char_p, create_string_buffer
  File "/anaconda3/lib/python3.6/ctypes/__init__.py", line 7, in <module>
    from _ctypes import Union, Structure, Array
ImportError: dlopen(/anaconda3/lib/python3.6/lib-dynload/_ctypes.cpython-36m-darwin.so, 2): Library not loaded: @rpath/libffi.6.dylib
  Referenced from: /anaconda3/lib/python3.6/lib-dynload/_ctypes.cpython-36m-darwin.so
  Reason: image not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/anaconda3/bin/conda", line 13, in <module>
    sys.exit(main())
  File "/anaconda3/lib/python3.6/site-packages/conda/cli/main.py", line 150, in main
    return conda_exception_handler(_main, *args, **kwargs)
  File "/anaconda3/lib/python3.6/site-packages/conda/exceptions.py", line 1335, in conda_exception_handler
    return_value = exception_handler(func, *args, **kwargs)
  File "/anaconda3/lib/python3.6/site-packages/conda/exceptions.py", line 1046, in __call__
    return self.handle_exception(exc_val, exc_tb)
  File "/anaconda3/lib/python3.6/site-packages/conda/exceptions.py", line 1090, in handle_exception
    return self.handle_unexpected_exception(exc_val, exc_tb)
  File "/anaconda3/lib/python3.6/site-packages/conda/exceptions.py", line 1101, in handle_unexpected_exception
    self.print_unexpected_error_report(error_report)
  File "/anaconda3/lib/python3.6/site-packages/conda/exceptions.py", line 1171, in print_unexpected_error_report
    from .cli.main_info import get_env_vars_str, get_main_info_str
  File "/anaconda3/lib/python3.6/site-packages/conda/cli/main_info.py", line 19, in <module>
    from ..core.index import _supplement_index_with_system
  File "/anaconda3/lib/python3.6/site-packages/conda/core/index.py", line 9, in <module>
    from .package_cache_data import PackageCacheData
  File "/anaconda3/lib/python3.6/site-packages/conda/core/package_cache_data.py", line 15, in <module>
    from conda_package_handling.api import InvalidArchiveError
  File "/anaconda3/lib/python3.6/site-packages/conda_package_handling/api.py", line 3, in <module>
    from libarchive.exception import ArchiveError as _LibarchiveArchiveError
  File "/anaconda3/lib/python3.6/site-packages/libarchive/__init__.py", line 1, in <module>
    from .entry import ArchiveEntry
  File "/anaconda3/lib/python3.6/site-packages/libarchive/entry.py", line 4, in <module>
    from ctypes import c_char_p, create_string_buffer
  File "/anaconda3/lib/python3.6/ctypes/__init__.py", line 7, in <module>
    from _ctypes import Union, Structure, Array
ImportError: dlopen(/anaconda3/lib/python3.6/lib-dynload/_ctypes.cpython-36m-darwin.so, 2): Library not loaded: @rpath/libffi.6.dylib
  Referenced from: /anaconda3/lib/python3.6/lib-dynload/_ctypes.cpython-36m-darwin.so
  Reason: image not found



```

</details>

**Comment by arranjdavis** [comment]
I would say that this is best dealt with by simply removing Anaconda `anaconda3` in my instance, and reinstalling. Took about 10 minutes!
