### ISSUE TITLE
[Windows] Cannot open https://www.apache.org (SSL certificate verify failed)

### ISSUE THREAD

**Issue by pitrou** [ContinuumIO/anaconda-issues#11130]
On a freshly created environment on Windows 7:
```
(ttt) c:\>conda list
# packages in environment at C:\Miniconda3\envs\ttt:
#
# Name                    Version                   Build  Channel
certifi                   2019.6.16                py36_0
pip                       19.1.1                   py36_0
python                    3.6.8                h9f7ef89_7
setuptools                41.0.1                   py36_0
sqlite                    3.29.0               he774522_0
vc                        14.1                 h0510ff6_4
vs2015_runtime            14.15.26706          h3a45250_4
wheel                     0.33.4                   py36_0
wincertstore              0.2              py36h7fe50ca_0
```

Opening a HTTPS URL on `www.apache.org` fails with a certificate error:
```
(ttt) c:\>python -c "from urllib.request import urlopen; urlopen('https://www.apache.org/')"
Traceback (most recent call last):
  File "C:\Miniconda3\envs\ttt\lib\urllib\request.py", line 1318, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "C:\Miniconda3\envs\ttt\lib\http\client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\Miniconda3\envs\ttt\lib\http\client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "C:\Miniconda3\envs\ttt\lib\http\client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\Miniconda3\envs\ttt\lib\http\client.py", line 1026, in _send_output
    self.send(msg)
  File "C:\Miniconda3\envs\ttt\lib\http\client.py", line 964, in send
    self.connect()
  File "C:\Miniconda3\envs\ttt\lib\http\client.py", line 1400, in connect
    server_hostname=server_hostname)
  File "C:\Miniconda3\envs\ttt\lib\ssl.py", line 407, in wrap_socket
    _context=self, _session=session)
  File "C:\Miniconda3\envs\ttt\lib\ssl.py", line 817, in __init__
    self.do_handshake()
  File "C:\Miniconda3\envs\ttt\lib\ssl.py", line 1077, in do_handshake
    self._sslobj.do_handshake()
  File "C:\Miniconda3\envs\ttt\lib\ssl.py", line 689, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c
:852)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Miniconda3\envs\ttt\lib\urllib\request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Miniconda3\envs\ttt\lib\urllib\request.py", line 526, in open
    response = self._open(req, data)
  File "C:\Miniconda3\envs\ttt\lib\urllib\request.py", line 544, in _open
    '_open', req)
  File "C:\Miniconda3\envs\ttt\lib\urllib\request.py", line 504, in _call_chain
    result = func(*args)
  File "C:\Miniconda3\envs\ttt\lib\urllib\request.py", line 1361, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "C:\Miniconda3\envs\ttt\lib\urllib\request.py", line 1320, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certifica
te verify failed (_ssl.c:852)>
```

**Comment by pitrou** [comment]
I'll note that this has started happening 3 days ago according to our AppVeyor history. Last good build:
https://ci.appveyor.com/project/ApacheSoftwareFoundation/arrow/builds/26112134/job/a4kuhassu8snkk3c?fullLog=true
First bad build:
https://ci.appveyor.com/project/ApacheSoftwareFoundation/arrow/builds/26115130/job/yun5kri0y60a76hr?fullLog=true

**Comment by pitrou** [comment]
The error can be reproduced with Python 3.7.3 from python.org, but version 3.7.4 fixed the error.

I think the relevant fix is https://bugs.python.org/issue35941 . On 3.7.3 I have:
```
>>> len(_ssl.enum_certificates("CA"))
3
```
On 3.7.4 I have:
```
>>> len(_ssl.enum_certificates("CA"))
9
```

It would need to be applied on 3.6 as well.

**Comment by pitrou** [comment]
Closing in favour of https://github.com/conda-forge/python-feedstock/issues/267
