### ISSUE TITLE
anaconda broke after installing kivy

### ISSUE THREAD

**Issue by Nathanael8** [ContinuumIO/anaconda-issues#11155]
### Actual Behavior

I installed kivy by `conda install kivy -c conda-forge` as the kivy website suggests.
then i wanted to start anaconda and my browser opened with the following message, that also told me to report it her

> Navigator Error
> 
> An unexpected error occurred on Navigator start-up
> 
> Report
> 
> Please report this issue in the anaconda issue tracker
> 
> Main Error
> 
> 'message'
> Traceback
> 
> Traceback (most recent call last):
>   File "/anaconda3/lib/python3.6/site-packages/anaconda_navigator/exceptions.py", line 75, in exception_handler
>     return_value = func(*args, **kwargs)
>   File "/anaconda3/lib/python3.6/site-packages/anaconda_navigator/app/start.py", line 120, in start_app
>     window = run_app(splash)
>   File "/anaconda3/lib/python3.6/site-packages/anaconda_navigator/app/start.py", line 63, in run_app
>     window = MainWindow(splash=splash)
>   File "/anaconda3/lib/python3.6/site-packages/anaconda_navigator/widgets/main_window.py", line 160, in __init__
>     self.api = AnacondaAPI()
>   File "/anaconda3/lib/python3.6/site-packages/anaconda_navigator/api/anaconda_api.py", line 1258, in AnacondaAPI
>     ANACONDA_API = _AnacondaAPI()
>   File "/anaconda3/lib/python3.6/site-packages/anaconda_navigator/api/anaconda_api.py", line 70, in __init__
>     self._conda_api = CondaAPI()
>   File "/anaconda3/lib/python3.6/site-packages/anaconda_navigator/api/conda_api.py", line 1654, in CondaAPI
>     CONDA_API = _CondaAPI()
>   File "/anaconda3/lib/python3.6/site-packages/anaconda_navigator/api/conda_api.py", line 345, in __init__
>     self.set_conda_prefix()
>   File "/anaconda3/lib/python3.6/site-packages/anaconda_navigator/api/conda_api.py", line 493, in set_conda_prefix
>     info = worker.communicate()[0]
>   File "/anaconda3/lib/python3.6/site-packages/anaconda_navigator/api/conda_api.py", line 271, in communicate
>     " ".join(self._cmd_list), result[0]['message']
> KeyError: 'message'
> 

### Expected Behavior

anaconda should launch

### Steps to Reproduce

launching the anaconda app

##### Anaconda or Miniconda version:

I use Anaconda3 i don't know how to get it in more details, since `conda list anaconda` which I found to tell me the version does not run.
edit:
I found something in .bash_profile
```
# added by Anaconda3 5.0.0 installer
export PATH="/anaconda3/bin:$PATH"
```

##### Operating System:

macOS High Sierra v10.13.6

##### `conda info`

<details>

```
# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/anaconda3/lib/python3.6/site-packages/conda/exceptions.py", line 1062, in __call__
        return func(*args, **kwargs)
      File "/anaconda3/lib/python3.6/site-packages/conda/cli/main.py", line 84, in _main
        exit_code = do_call(args, p)
      File "/anaconda3/lib/python3.6/site-packages/conda/cli/conda_argparse.py", line 80, in do_call
        module = import_module(relative_mod, __name__.rsplit('.', 1)[0])
      File "/anaconda3/lib/python3.6/importlib/__init__.py", line 126, in import_module
        return _bootstrap._gcd_import(name[level:], package, level)
      File "<frozen importlib._bootstrap>", line 978, in _gcd_import
      File "<frozen importlib._bootstrap>", line 961, in _find_and_load
      File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
      File "<frozen importlib._bootstrap_external>", line 678, in exec_module
      File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
      File "/anaconda3/lib/python3.6/site-packages/conda/cli/main_info.py", line 19, in <module>
        from ..core.index import _supplement_index_with_system
      File "/anaconda3/lib/python3.6/site-packages/conda/core/index.py", line 9, in <module>
        from .package_cache_data import PackageCacheData
      File "/anaconda3/lib/python3.6/site-packages/conda/core/package_cache_data.py", line 15, in <module>
        from conda_package_handling.api import InvalidArchiveError
      File "/anaconda3/lib/python3.6/site-packages/conda_package_handling/api.py", line 3, in <module>
        from libarchive.exception import ArchiveError as _LibarchiveArchiveError
      File "/anaconda3/lib/python3.6/site-packages/libarchive/__init__.py", line 1, in <module>
        from .entry import ArchiveEntry
      File "/anaconda3/lib/python3.6/site-packages/libarchive/entry.py", line 6, in <module>
        from . import ffi
      File "/anaconda3/lib/python3.6/site-packages/libarchive/ffi.py", line 184, in <module>
        c_int, check_int)
      File "/anaconda3/lib/python3.6/site-packages/libarchive/ffi.py", line 95, in ffi
        f = getattr(libarchive, 'archive_'+name)
      File "/anaconda3/lib/python3.6/ctypes/__init__.py", line 361, in __getattr__
        func = self.__getitem__(name)
      File "/anaconda3/lib/python3.6/ctypes/__init__.py", line 366, in __getitem__
        func = self._FuncPtr((name_or_ordinal, self))
    AttributeError: dlsym(0x7fb485564a50, archive_read_open_filename_w): symbol not found

`$ /anaconda3/bin/conda info`


An unexpected error has occurred. Conda has prepared the above report.

If submitted, this report will be used by core maintainers to improve
future releases of conda.
Would you like conda to send this report to the core maintainers?

[y/N]: y
Upload successful.

Thank you for helping to improve conda.
Opt-in to always sending reports (and not see this message again)
by running

    $ conda config --set report_errors true

```

</details>

##### `conda list --show-channel-urls`

<details>

```
Traceback (most recent call last):
  File "/anaconda3/lib/python3.6/site-packages/conda/exceptions.py", line 1062, in __call__
    return func(*args, **kwargs)
  File "/anaconda3/lib/python3.6/site-packages/conda/cli/main.py", line 84, in _main
    exit_code = do_call(args, p)
  File "/anaconda3/lib/python3.6/site-packages/conda/cli/conda_argparse.py", line 80, in do_call
    module = import_module(relative_mod, __name__.rsplit('.', 1)[0])
  File "/anaconda3/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 978, in _gcd_import
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
  File "/anaconda3/lib/python3.6/site-packages/conda/cli/main_list.py", line 14, in <module>
    from ..core.prefix_data import PrefixData
  File "/anaconda3/lib/python3.6/site-packages/conda/core/prefix_data.py", line 24, in <module>
    from ..gateways.disk.create import write_as_json_to_file
  File "/anaconda3/lib/python3.6/site-packages/conda/gateways/disk/create.py", line 17, in <module>
    import conda_package_handling.api
  File "/anaconda3/lib/python3.6/site-packages/conda_package_handling/api.py", line 3, in <module>
    from libarchive.exception import ArchiveError as _LibarchiveArchiveError
  File "/anaconda3/lib/python3.6/site-packages/libarchive/__init__.py", line 1, in <module>
    from .entry import ArchiveEntry
  File "/anaconda3/lib/python3.6/site-packages/libarchive/entry.py", line 6, in <module>
    from . import ffi
  File "/anaconda3/lib/python3.6/site-packages/libarchive/ffi.py", line 184, in <module>
    c_int, check_int)
  File "/anaconda3/lib/python3.6/site-packages/libarchive/ffi.py", line 95, in ffi
    f = getattr(libarchive, 'archive_'+name)
  File "/anaconda3/lib/python3.6/ctypes/__init__.py", line 361, in __getattr__
    func = self.__getitem__(name)
  File "/anaconda3/lib/python3.6/ctypes/__init__.py", line 366, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: dlsym(0x7fa1af603e60, archive_read_open_filename_w): symbol not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/anaconda3/bin/conda", line 13, in <module>
    sys.exit(main())
  File "/anaconda3/lib/python3.6/site-packages/conda/cli/main.py", line 150, in main
    return conda_exception_handler(_main, *args, **kwargs)
  File "/anaconda3/lib/python3.6/site-packages/conda/exceptions.py", line 1354, in conda_exception_handler
    return_value = exception_handler(func, *args, **kwargs)
  File "/anaconda3/lib/python3.6/site-packages/conda/exceptions.py", line 1065, in __call__
    return self.handle_exception(exc_val, exc_tb)
  File "/anaconda3/lib/python3.6/site-packages/conda/exceptions.py", line 1109, in handle_exception
    return self.handle_unexpected_exception(exc_val, exc_tb)
  File "/anaconda3/lib/python3.6/site-packages/conda/exceptions.py", line 1120, in handle_unexpected_exception
    self.print_unexpected_error_report(error_report)
  File "/anaconda3/lib/python3.6/site-packages/conda/exceptions.py", line 1190, in print_unexpected_error_report
    from .cli.main_info import get_env_vars_str, get_main_info_str
  File "/anaconda3/lib/python3.6/site-packages/conda/cli/main_info.py", line 19, in <module>
    from ..core.index import _supplement_index_with_system
  File "/anaconda3/lib/python3.6/site-packages/conda/core/index.py", line 9, in <module>
    from .package_cache_data import PackageCacheData
  File "/anaconda3/lib/python3.6/site-packages/conda/core/package_cache_data.py", line 15, in <module>
    from conda_package_handling.api import InvalidArchiveError
  File "/anaconda3/lib/python3.6/site-packages/conda_package_handling/api.py", line 7, in <module>
    from .tarball import CondaTarBZ2 as _CondaTarBZ2
  File "/anaconda3/lib/python3.6/site-packages/conda_package_handling/tarball.py", line 7, in <module>
    import libarchive
  File "/anaconda3/lib/python3.6/site-packages/libarchive/__init__.py", line 1, in <module>
    from .entry import ArchiveEntry
  File "/anaconda3/lib/python3.6/site-packages/libarchive/entry.py", line 6, in <module>
    from . import ffi
  File "/anaconda3/lib/python3.6/site-packages/libarchive/ffi.py", line 184, in <module>
    c_int, check_int)
  File "/anaconda3/lib/python3.6/site-packages/libarchive/ffi.py", line 95, in ffi
    f = getattr(libarchive, 'archive_'+name)
  File "/anaconda3/lib/python3.6/ctypes/__init__.py", line 361, in __getattr__
    func = self.__getitem__(name)
  File "/anaconda3/lib/python3.6/ctypes/__init__.py", line 366, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: dlsym(0x7fa1af603e60, archive_read_open_filename_w): symbol not found


```

</details>

**Comment by csoja** [comment]
I'm assuming you didn't see this issue until after you installed kivy?  Unfortunately, it looks like your conda is not in a good state at this point.  
I'd recommend downloading Miniconda and installing that to try and fix it: https://docs.anaconda.com/anaconda/user-guide/troubleshooting/#error-message-on-miniconda-install-already-installed
If that fixes it, I'd recommend installing kivy into a new environment and not into the base environment where conda is installed. https://conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html

**Comment by Nathanael8** [comment]
In the end I did a clean reinstallation of my OS.
