### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by nickClicktripz** [ContinuumIO/anaconda-issues#11151]
## Main error
An unexpected error occurred on Navigator start-up<br>psutil.AccessDenied (pid=670)
## Traceback
```
Traceback (most recent call last):
  File "/Users/nick/anaconda/lib/python3.6/site-packages/psutil/_psosx.py", line 359, in catch_zombie
    yield
  File "/Users/nick/anaconda/lib/python3.6/site-packages/psutil/_psosx.py", line 425, in cmdline
    return cext.proc_cmdline(self.pid)
ProcessLookupError: [Errno 3] No such process

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/nick/anaconda/lib/python3.6/site-packages/anaconda_navigator/exceptions.py", line 75, in exception_handler
    return_value = func(*args, **kwargs)
  File "/Users/nick/anaconda/lib/python3.6/site-packages/anaconda_navigator/app/start.py", line 108, in start_app
    if misc.load_pid() is None:  # A stale lock might be around
  File "/Users/nick/anaconda/lib/python3.6/site-packages/anaconda_navigator/utils/misc.py", line 384, in load_pid
    cmds = process.cmdline()
  File "/Users/nick/anaconda/lib/python3.6/site-packages/psutil/__init__.py", line 790, in cmdline
    return self._proc.cmdline()
  File "/Users/nick/anaconda/lib/python3.6/site-packages/psutil/_psosx.py", line 339, in wrapper
    return fun(self, *args, **kwargs)
  File "/Users/nick/anaconda/lib/python3.6/site-packages/psutil/_psosx.py", line 425, in cmdline
    return cext.proc_cmdline(self.pid)
  File "/Users/nick/anaconda/lib/python3.6/contextlib.py", line 99, in __exit__
    self.gen.throw(type, value, traceback)
  File "/Users/nick/anaconda/lib/python3.6/site-packages/psutil/_psosx.py", line 372, in catch_zombie
    raise AccessDenied(proc.pid, proc._name)
psutil.AccessDenied: psutil.AccessDenied (pid=670)

```
## System information
```
python: 3.6.8
language: en
os: Darwin;16.7.0;Darwin Kernel Version 16.7.0: Thu Jun 15 17:36:27 PDT 2017; root:xnu-3789.70.16~2/RELEASE_X86_64;x86_64;i386
version: 1.6.2
platform: osx-64
qt: 5.9.6
pyqt: 5.9.2
conda: 4.7.10
```

**Comment by csoja** [comment]
In the terminal:

conda update conda
conda update anaconda-navigator
conda update navigator-updater
anaconda-navigator --reset

The last command is the key to fixing your issue - as it removes the lock file that is causing your problem.
