### ISSUE TITLE
Tensorflow-gpu does not work when using Conv2D

### ISSUE THREAD

**Issue by Hayashi-Yudai** [ContinuumIO/anaconda-issues#11156]
### Actual Behavior

I use RTX-2080 GPU and try to construct CNN. In the past, I used tensorflow-gpu==1.12.0 and has no problems, but after update the tensorflow-gpu==1.13.1, I cannot train CNN network.

The reason I post this issue to "anaconda-issue" is that the cause is the cudnn version which installed when `conda install tensorflow-gpu==1.13.1`. In the newer version of conda command, cudnn==7.6 is installed by default, and it causes the error even in the tensorflow-gpu==1.12.0, but after downgrading to 7.3.1, no error occur. I want to try tensorflow-gpu==1.13.1 with cudnn==7.4, but conda does not have that version.

### Expected Behavior

Train CNN network with GPU.

### Steps to Reproduce

```
conda create -n test python=3.6.8
conda activate test
conda install tensorflow-gpu==1.13.1
python test.py
```

test.py
```python
import tensorflow as tf                                                                                                                        
import numpy as np

X = tf.keras.Input(shape=(32,32,3))
y = tf.keras.layers.Conv2D(10, kernel_size=3)(X)
model = tf.keras.Model(X, y)
pred = model.predict(np.random.randn(1, 32, 32, 3)) 
```

the error message is
```
WARNING:tensorflow:From /home/yudai/.conda/envs/gpu-test/lib/python3.6/site-packages/tensorflow/python/ops/resource_variable_ops.py:435: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
2019-07-29 00:33:27.664910: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
2019-07-29 00:33:27.667928: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 3600000000 Hz
2019-07-29 00:33:27.668338: I tensorflow/compiler/xla/service/service.cc:150] XLA service 0x55586ad24030 executing computations on platform Host. Devices:
2019-07-29 00:33:27.668350: I tensorflow/compiler/xla/service/service.cc:158]   StreamExecutor device (0): <undefined>, <undefined>
2019-07-29 00:33:27.762892: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:998] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2019-07-29 00:33:27.763367: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1433] Found device 0 with properties: 
name: GeForce RTX 2080 major: 7 minor: 5 memoryClockRate(GHz): 1.71
pciBusID: 0000:01:00.0
totalMemory: 7.76GiB freeMemory: 6.93GiB
2019-07-29 00:33:27.763379: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1512] Adding visible gpu devices: 0
2019-07-29 00:33:27.763947: I tensorflow/core/common_runtime/gpu/gpu_device.cc:984] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-07-29 00:33:27.763955: I tensorflow/core/common_runtime/gpu/gpu_device.cc:990]      0 
2019-07-29 00:33:27.763958: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1003] 0:   N 
2019-07-29 00:33:27.764021: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 6739 MB memory) -> physical GPU (device: 0, name: GeForce RTX 2080, pci bus id: 0000:01:00.0, compute capability: 7.5)
2019-07-29 00:33:27.765026: I tensorflow/compiler/xla/service/service.cc:150] XLA service 0x55586c7c6040 executing computations on platform CUDA. Devices:
2019-07-29 00:33:27.765035: I tensorflow/compiler/xla/service/service.cc:158]   StreamExecutor device (0): GeForce RTX 2080, Compute Capability 7.5
2019-07-29 00:33:28.695936: E tensorflow/stream_executor/cuda/cuda_dnn.cc:334] Could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR
2019-07-29 00:33:28.699779: E tensorflow/stream_executor/cuda/cuda_dnn.cc:334] Could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR
Traceback (most recent call last):
  File "test.py", line 7, in <module>
    pred = model.predict(np.random.randn(1, 32, 32, 3))
  File "/home/yudai/.conda/envs/gpu-test/lib/python3.6/site-packages/tensorflow/python/keras/engine/training.py", line 1113, in predict
    self, x, batch_size=batch_size, verbose=verbose, steps=steps)
  File "/home/yudai/.conda/envs/gpu-test/lib/python3.6/site-packages/tensorflow/python/keras/engine/training_arrays.py", line 329, in model_iteration
    batch_outs = f(ins_batch)
  File "/home/yudai/.conda/envs/gpu-test/lib/python3.6/site-packages/tensorflow/python/keras/backend.py", line 3076, in __call__
    run_metadata=self.run_metadata)
  File "/home/yudai/.conda/envs/gpu-test/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1439, in __call__
    run_metadata_ptr)
  File "/home/yudai/.conda/envs/gpu-test/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py", line 528, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.UnknownError: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
	 [[{{node conv2d/Conv2D}}]]

```

##### Anaconda or Miniconda version:
conda 4.5.12

##### Operating System:
Ubuntu 18.04

##### `conda info`

<details>

```
     active environment : gpu-test
    active env location : /home/yudai/.conda/envs/gpu-test
            shell level : 1
       user config file : /home/yudai/.condarc
 populated config files : 
          conda version : 4.5.12
    conda-build version : 3.17.6
         python version : 3.7.1.final.0
       base environment : /home/yudai/anaconda3  (read only)
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/linux-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/linux-64
                          https://repo.anaconda.com/pkgs/pro/noarch
          package cache : /home/yudai/anaconda3/pkgs
                          /home/yudai/.conda/pkgs
       envs directories : /home/yudai/.conda/envs
                          /home/yudai/anaconda3/envs
               platform : linux-64
             user-agent : conda/4.5.12 requests/2.21.0 CPython/3.7.1 Linux/4.15.0-55-generic ubuntu/18.04 glibc/2.27
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False

```

</details>

##### `conda list --show-channel-urls`

<details>

```
# packages in environment at /home/yudai/.conda/envs/gpu-test:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main    defaults
_tflow_select             2.1.0                       gpu    defaults
absl-py                   0.7.1                    py36_0    defaults
astor                     0.7.1                    py36_0    defaults
blas                      1.0                         mkl    defaults
c-ares                    1.15.0               h7b6447c_1    defaults
ca-certificates           2019.5.15                     0    defaults
certifi                   2019.6.16                py36_0    defaults
cudatoolkit               10.0.130                      0    defaults
cudnn                     7.6.0                cuda10.0_0    defaults
cupti                     10.0.130                      0    defaults
cycler                    0.10.0                    <pip>
decorator                 4.4.0                     <pip>
gast                      0.2.2                    py36_0    defaults
grpcio                    1.16.1           py36hf8bcb03_1    defaults
h5py                      2.9.0            py36h7918eee_0    defaults
hdf5                      1.10.4               hb1b8bf9_0    defaults
imageio                   2.5.0                     <pip>
imgaug                    0.2.9                     <pip>
intel-openmp              2019.4                      243    defaults
keras-applications        1.0.8                      py_0    defaults
keras-preprocessing       1.1.0                      py_1    defaults
kiwisolver                1.1.0                     <pip>
libedit                   3.1.20181209         hc058e9b_0    defaults
libffi                    3.2.1                hd88cf55_4    defaults
libgcc-ng                 9.1.0                hdf63c60_0    defaults
libgfortran-ng            7.3.0                hdf63c60_0    defaults
libprotobuf               3.8.0                hd408876_0    defaults
libstdcxx-ng              9.1.0                hdf63c60_0    defaults
markdown                  3.1.1                    py36_0    defaults
matplotlib                3.1.1                     <pip>
mkl                       2019.4                      243    defaults
mkl-service               2.0.2            py36h7b6447c_0    defaults
mkl_fft                   1.0.12           py36ha843d7b_0    defaults
mkl_random                1.0.2            py36hd81dba3_0    defaults
mock                      3.0.5                    py36_0    defaults
ncurses                   6.1                  he6710b0_1    defaults
networkx                  2.3                       <pip>
numpy                     1.16.4           py36h7e9f1db_0    defaults
numpy-base                1.16.4           py36hde5b4d6_0    defaults
opencv-python             4.1.0.25                  <pip>
openssl                   1.1.1c               h7b6447c_1    defaults
Pillow                    6.1.0                     <pip>
pip                       19.1.1                   py36_0    defaults
protobuf                  3.8.0            py36he6710b0_0    defaults
pyparsing                 2.4.1.1                   <pip>
python                    3.6.8                h0371630_0    defaults
python-dateutil           2.8.0                     <pip>
PyWavelets                1.0.3                     <pip>
readline                  7.0                  h7b6447c_5    defaults
scikit-image              0.15.0                    <pip>
scipy                     1.3.0            py36h7c811a0_0    defaults
setuptools                41.0.1                   py36_0    defaults
Shapely                   1.6.4.post2               <pip>
six                       1.12.0                   py36_0    defaults
sqlite                    3.29.0               h7b6447c_0    defaults
tensorboard               1.13.1           py36hf484d3e_0    defaults
tensorflow                1.13.1          gpu_py36h3991807_0    defaults
tensorflow-base           1.13.1          gpu_py36h8d69cac_0    defaults
tensorflow-estimator      1.13.0                     py_0    defaults
tensorflow-gpu            1.13.1               h0d30ee6_0    defaults
termcolor                 1.1.0                    py36_1    defaults
tk                        8.6.8                hbc83047_0    defaults
werkzeug                  0.15.4                     py_0    defaults
wheel                     0.33.4                   py36_0    defaults
xz                        5.2.4                h14c3975_4    defaults
zlib                      1.2.11               h7b6447c_3    defaults
```

</details>

**Comment by 183amir** [comment]
@Hayashi-Yudai why are you reporting this issue here? Is it because of the conda package of tensorflow? Does your code example work using a pip installed version of tensorflow?

**Comment by Hayashi-Yudai** [comment]
Thank you @183amir. It's over a years ago, so I do not remember this clearly. But I think this issue says that if I install tensorflow-gpu with `conda` command, the above code fails, but does not fail if installing by `pip`.

**Comment by 183amir** [comment]
> But I think this issue says that if I install tensorflow-gpu with conda command, the above code fails, but does not fail if installing by pip.

Your issue doesn't say that and that's what confused me. If you don't care about this problem anymore, I suggest you close this issue then. Thank you.
