### ISSUE TITLE
Anaconda Crashes After running conda update

### ISSUE THREAD

**Issue by ozziejin** [ContinuumIO/anaconda-issues#11166]
### Actual Behavior
Anaconda Navigator flash crashes and shows below error code:

### Expected Behavior

open Anaconda Navigator in windows

### Steps to Reproduce

open Anaconda Navigator

##### Anaconda or Miniconda version:
Anaconda 3

##### Operating System:
Window 10
##### `conda info`

<details>

```
PASTE OUTPUT HERE:

```

</details>

##### `conda list --show-channel-urls`

Main Error
'root_prefix'
Traceback
Traceback (most recent call last):
  File "C:\Users\lu.jin01\AppData\Local\Continuum\anaconda3\lib\site-packages\anaconda_navigator\exceptions.py", line 75, in exception_handler
    return_value = func(*args, **kwargs)
  File "C:\Users\lu.jin01\AppData\Local\Continuum\anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 151, in start_app
    window = run_app(splash)
  File "C:\Users\lu.jin01\AppData\Local\Continuum\anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 65, in run_app
    window = MainWindow(splash=splash, tab_project=False)
  File "C:\Users\lu.jin01\AppData\Local\Continuum\anaconda3\lib\site-packages\anaconda_navigator\widgets\main_window.py", line 168, in __init__
    self.api = AnacondaAPI()
  File "C:\Users\lu.jin01\AppData\Local\Continuum\anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 2337, in AnacondaAPI
    ANACONDA_API = _AnacondaAPI()
  File "C:\Users\lu.jin01\AppData\Local\Continuum\anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 89, in __init__
    self._conda_api = CondaAPI()
  File "C:\Users\lu.jin01\AppData\Local\Continuum\anaconda3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 1773, in CondaAPI
    CONDA_API = _CondaAPI()
  File "C:\Users\lu.jin01\AppData\Local\Continuum\anaconda3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 350, in __init__
    self.set_conda_prefix(info=get_conda_info())
  File "C:\Users\lu.jin01\AppData\Local\Continuum\anaconda3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 505, in set_conda_prefix
    self.ROOT_PREFIX = info['root_prefix']
KeyError: 'root_prefix'

```
PASTE OUTPUT HERE:

```

</details>

**Comment by ozziejin** [comment]
Hello, any update? Thanks.

**Comment by ozziejin** [comment]
Updates: it turns out it's because I didn't have admin access on my laptop. For newbies like me, or at least the old me: two workarounds:
1. get admin access
2. create a virtual environment

I end up getting the admin access, but according to my research, the 2nd option also works.
