### ISSUE TITLE
Miniconda2-4.7.10-linux-x86_64.sh fails within Singularity build

### ISSUE THREAD

**Issue by tschoonj** [ContinuumIO/anaconda-issues#11163]
### Actual Behavior

During a [Singularity image build ](https://circleci.com/gh/DiamondLightSource/Savu/73)on a Circle-CI vm, I observe the following error:

```
wget -q https://repo.anaconda.com/miniconda/Miniconda2-latest-Linux-x86_64.sh -O /usr/local/miniconda.sh
bash /usr/local/miniconda.sh -b -p /usr/local/miniconda

                                      [2826] Failed to execute script conda.exe

Traceback (most recent call last):
  File "conda.exe.py", line 53, in <module>
  File "concurrent/futures/process.py", line 402, in __init__
  File "multiprocessing/context.py", line 102, in Queue
  File "multiprocessing/queues.py", line 42, in __init__
  File "multiprocessing/context.py", line 67, in Lock
  File "multiprocessing/synchronize.py", line 162, in __init__
  File "multiprocessing/synchronize.py", line 59, in __init__
OSError: [Errno 38] Function not implemented
```

Downgrading from latest to the 4.6.14 installer fixes this.

### Expected Behavior

Miniconda to install just like before.

### Steps to Reproduce

I cannot reproduce this locally with a Singularity build: it only appears on the Circle-CI VM.

##### Anaconda or Miniconda version:

Miniconda2 4.7.10

##### Operating System:

Linux

##### `conda info`

Didn't get this far :smile: 

##### `conda list --show-channel-urls`

Same here

**Comment by huangyingzhang** [comment]
I also have the same problem today. Did you figure out this problem?

**Comment by tschoonj** [comment]
Not really... Downgrading the installer to version 4.6.14 works for me though.

**Comment by huangyingzhang** [comment]
> Not really... Downgrading the installer to version 4.6.14 works for me though.

Thank you. Downgrading the version also works for me.

**Comment by msarahan** [comment]
The installer has some multiprocess code to speed things up.  Your singularity containers appear to not support that low-level multiprocess mechanism.  We need to add a fallback to the old single-process approach.

**Comment by mingwandroid** [comment]
Twenty seconds of Googling reveals: https://github.com/sylabs/singularity/issues/875

**Comment by msarahan** [comment]
nice find.  That helps explain a lot.  I think the easiest way forward from our side is the fallback, but it would be nice if the singularity people fixed this on their side, too.

**Comment by mingwandroid** [comment]
In the meantime, you can probably still use the latest by following the advice:

> I can confirm that passing in `-B /run/shm:/run/shm` works. It not only fixes my issue but also fixes the python `multiprocessing.Pool()` sample above that was also a problem for me.

**Comment by mingwandroid** [comment]
I think if we add a fallback to conda the bug will just manifest further down the chain (and result in further bug reports). So IMHO we shouldn't bother.
