### ISSUE TITLE
TypeError: expected str, bytes or os.PathLike object, not NoneType

### ISSUE THREAD

**Issue by claireting** [ContinuumIO/anaconda-issues#11180]
### Actual Behavior

open the anaconda,this is a wrong.  
TypeError: expected str, bytes or os.PathLike object, not NoneType

##### Anaconda or Miniconda version:

anaconda3 2019.03 window64bit   python3.7
##### `conda info`

<details>

```
PASTE OUTPUT HERE:Traceback
Traceback (most recent call last):
  File "D:\Anaconda3\lib\site-packages\anaconda_navigator\exceptions.py", line 75, in exception_handler
    return_value = func(*args, **kwargs)
  File "D:\Anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 151, in start_app
    window = run_app(splash)
  File "D:\Anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 65, in run_app
    window = MainWindow(splash=splash, tab_project=False)
  File "D:\Anaconda3\lib\site-packages\anaconda_navigator\widgets\main_window.py", line 168, in __init__
    self.api = AnacondaAPI()
  File "D:\Anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 2337, in AnacondaAPI
    ANACONDA_API = _AnacondaAPI()
  File "D:\Anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 89, in __init__
    self._conda_api = CondaAPI()
  File "D:\Anaconda3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 1773, in CondaAPI
    CONDA_API = _CondaAPI()
  File "D:\Anaconda3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 353, in __init__
    self.sys_rc_path = join(self.ROOT_PREFIX, '.condarc')
  File "D:\Anaconda3\lib\ntpath.py", line 76, in join
    path = os.fspath(path)
TypeError: expected str, bytes or os.PathLike object, not NoneType```

</details>

##### `conda list --show-channel-urls`
<!-- Paste the output of 'conda list --show-channel-urls' between the two sets of backticks (```) below -->

<details>

```
PASTE OUTPUT HERE:

```

</details>

**Comment by gh4mike** [comment]
I have suddenly started experiencing this error.  Uninstalled and reinstalled (Anaconda3-5.2.0-Windows-x86_64 previously downloaded), still same problem.  Was running fine, then bam, this started happening out of the blue.  No updates caused this -- was not connected to internet in fact. Now I cannot start navigator, cannot use Python. Very frustrating.

**Comment by csoja** [comment]
It is possible your .condarc file has gotten corrupted.  I suspect if you delete your .condarc file, it will fix the problem.  If you don't know where your .condarc file is stored (it is the configuration file for conda) - you can usually find out by opening the Anaconda Prompt and executing _conda info_

**Comment by gh4mike** [comment]
Thanks for the comment.  It turns out to be a much bigger problem.  Tried uninstalling/reinstalling Anaconda...wouldn't reinstall.  This all started with a blue screen event while using Navigator, so something in the OS must have gotten corrupted.  Had been getting random blue screens ever since upgrading the SSD.  Tried refreshing Windows 10, but got a blue screen during that, at which time the laptop became unbootable.  Eventually was able to reloaded the OS via a bootable USB.  Installed Anaconda, then got yet another blue screen near the end of the install...but nonetheless the install appears to have been successful.  Suspect a bad SSD, will be exchanging, hopefully that will fix the problem for good.
