### ISSUE TITLE
Cannot build wheels due to bad SOABI value in Python 3.7.4 from main channel

### ISSUE THREAD

**Issue by qwhelan** [ContinuumIO/anaconda-issues#11195]
It appears that `python setup.py bdist_wheel` fails on Anaconda Python 3.7.4 due to a bad `SOABI` setting of `cpython-@PYVERNODOTS@m-x86_64-linux-gnu` from a template variable not being rendered.

The correct setting is of the form: `cpython-37m-x86_64-linux-gnu`. 

### Actual Behavior
The `wheel` package validates this setting and aborts wheel creation with the following error:
```
running install_scripts
Traceback (most recent call last):
  File "setup.py", line 112, in <module>
    setup(**metadata)
  File "/home/chris/anaconda3/envs/bottleneck_testing/lib/python3.7/site-packages/setuptools/__init__.py", line 145, in setup
    return distutils.core.setup(**attrs)
  File "/home/chris/anaconda3/envs/bottleneck_testing/lib/python3.7/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/home/chris/anaconda3/envs/bottleneck_testing/lib/python3.7/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/home/chris/anaconda3/envs/bottleneck_testing/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/chris/anaconda3/envs/bottleneck_testing/lib/python3.7/site-packages/wheel/bdist_wheel.py", line 226, in run
    impl_tag, abi_tag, plat_tag = self.get_tag()
  File "/home/chris/anaconda3/envs/bottleneck_testing/lib/python3.7/site-packages/wheel/bdist_wheel.py", line 179, in get_tag
    assert tag == supported_tags[0], "%s != %s" % (tag, supported_tags[0])
AssertionError: ('cp37', 'cp@pyvernodots@m', 'linux_x86_64') != ('cp37', 'cp@PYVERNODOTS@m', 'linux_x86_64')
```

This setting can be directly accessed in a Python shell:
```
Python 3.7.4 (default, Aug  9 2019, 18:51:30) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import sysconfig
>>> sysconfig.get_config_var("SOABI")
8.3.0
'cpython-@PYVERNODOTS@m-x86_64-linux-gnu'
```
The 8.3.0 appears to correspond to the `gcc` version on the host system. It should not be showing up here, as shown below. This is possibly indicative of another issue.

### Expected Behavior

Building wheels should work on Anaconda Python and the SOABI setting should be reverted to the correct value:
```
Python 3.7.3 (default, Mar 27 2019, 22:11:17) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import sysconfig
>>> sysconfig.get_config_var('SOABI')
'cpython-37m-x86_64-linux-gnu'
```

### Steps to Reproduce

1. Create conda env using `python=3.7.4`
2. Attempt to run `python setup.py bdist_wheel` for package of your choice
3. Wheel build will fail.
4. Downgrade python to 3.7.3
5. Build wheel
6. Wheel build succeeds

##### `conda info`

<details>

```
     active environment : bottleneck_testing
    active env location : /home/chris/anaconda3/envs/bottleneck_testing
            shell level : 2
       user config file : /home/chris/.condarc
 populated config files : 
          conda version : 4.7.11
    conda-build version : 3.18.9
         python version : 3.7.3.final.0
       virtual packages : 
       base environment : /home/chris/anaconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /home/chris/anaconda3/pkgs
                          /home/chris/.conda/pkgs
       envs directories : /home/chris/anaconda3/envs
                          /home/chris/.conda/envs
               platform : linux-64
             user-agent : conda/4.7.11 requests/2.21.0 CPython/3.7.3 Linux/5.0.0-23-generic ubuntu/19.04 glibc/2.29
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False
```

</details>

##### `conda list --show-channel-urls`

<details>

```
 conda list --show-channel-urls
# packages in environment at /home/chris/anaconda3/envs/bottleneck_testing:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main    defaults
blas                      1.0                         mkl    defaults
ca-certificates           2019.5.15                     1    defaults
certifi                   2019.6.16                py37_1    defaults
intel-openmp              2019.4                      243    defaults
libedit                   3.1.20181209         hc058e9b_0    defaults
libffi                    3.2.1                hd88cf55_4    defaults
libgcc-ng                 9.1.0                hdf63c60_0    defaults
libgfortran-ng            7.3.0                hdf63c60_0    defaults
libstdcxx-ng              9.1.0                hdf63c60_0    defaults
mkl                       2019.4                      243    defaults
mkl_fft                   1.0.12           py37ha843d7b_0    defaults
mkl_random                1.0.2            py37hd81dba3_0    defaults
ncurses                   6.1                  he6710b0_1    defaults
numpy                     1.16.4           py37h7e9f1db_0    defaults
numpy-base                1.16.4           py37hde5b4d6_0    defaults
openssl                   1.1.1c               h7b6447c_1    defaults
pip                       19.1.1                   py37_0    defaults
python                    3.7.3                h0371630_0    defaults
readline                  7.0                  h7b6447c_5    defaults
setuptools                41.0.1                   py37_0    defaults
sqlite                    3.29.0               h7b6447c_0    defaults
tk                        8.6.8                hbc83047_0    defaults
wheel                     0.31.1                   py37_0    defaults
xz                        5.2.4                h14c3975_4    defaults
zlib                      1.2.11               h7b6447c_3    defaults
```

</details>

**Comment by jjhelmus** [comment]
There are some issues with our build of Python 3.7.4.  We will be fixing the issue and releasing updated packages shortly.  Sorry for any inconveniences this has caused.

**Comment by jjhelmus** [comment]
Corrected builds of Python 3.7.4 are available in `defaults`.  These are build number `1`, when installing name will end with `_1`.  Existing environments can be upgraded using `conda update python`.  New environment will automatically install the new build unless the older build is explicitly requested.  

I tested this build extensively and can confirmed that wheels can be built using it and the various sysconfig data is correct.

I would like to apologies again for this mixup.

**Comment by mmccarty** [comment]
@jjhelmus Thank you for the effort to fix this quickly.  I appreciate everyone's hard work!

**Comment by bsipocz** [comment]
Thank you @jjhelmus for the fix, I can confirm it indeed work for our case.

**Comment by qwhelan** [comment]
@jjhelmus Confirming it works now, thanks!

**Comment by greglandrum** [comment]
yep, that fixed the problems we were having too. Thanks!
