### ISSUE TITLE
Not able to install  any python  library  in anaconda - am getting the below error

### ISSUE THREAD

**Issue by goldi28** [ContinuumIO/anaconda-issues#11202]
`$ C:\Users\i317684\AppData\Local\Continuum\anaconda3\Scripts\conda-script.py install -c conda-forge selenium`

  environment variables:
                 CIO_TEST=<not set>
        CONDA_DEFAULT_ENV=base
                CONDA_EXE=C:\Users\i317684\AppData\Local\Continuum\anaconda3\condabin\..\Scripts
                          \conda.exe
               CONDA_EXES="C:\Users\i317684\AppData\Local\Continuum\anaconda3\condabin\..\Script
                          s\conda.exe"
             CONDA_PREFIX=C:\Users\i317684\AppData\Local\Continuum\anaconda3
    CONDA_PROMPT_MODIFIER=(base)
         CONDA_PYTHON_EXE=C:\Users\i317684\AppData\Local\Continuum\anaconda3\python.exe
               CONDA_ROOT=C:\Users\i317684\AppData\Local\Continuum\anaconda3
              CONDA_SHLVL=1
                 HOMEPATH=\Users\i317684
              HTTPS_PROXY=<set>
               HTTP_PROXY=<set>
                  IWBPATH=C:\Program Files (x86)\SAP\FrontEnd\iwb
                     PATH=C:\Users\i317684\AppData\Local\Continuum\anaconda3;C:\Users\i317684\Ap
                          pData\Local\Continuum\anaconda3\Library\mingw-w64\bin;C:\Users\i317684
                          \AppData\Local\Continuum\anaconda3\Library\usr\bin;C:\Users\i317684\Ap
                          pData\Local\Continuum\anaconda3\Library\bin;C:\Users\i317684\AppData\L
                          ocal\Continuum\anaconda3\Scripts;C:\Users\i317684\AppData\Local\Contin
                          uum\anaconda3\bin;C:\Users\i317684\AppData\Local\Continuum\anaconda3;C
                          :\Users\i317684\AppData\Local\Continuum\anaconda3\Library\mingw-w64\bi
                          n;C:\Users\i317684\AppData\Local\Continuum\anaconda3\Library\usr\bin;C
                          :\Users\i317684\AppData\Local\Continuum\anaconda3\Library\bin;C:\Users
                          \i317684\AppData\Local\Continuum\anaconda3\Scripts;C:\Users\i317684\Ap
                          pData\Local\Continuum\anaconda3\bin;C:\Users\i317684\AppData\Local\Con
                          tinuum\anaconda3\condabin;C:\ProgramData\DockerDesktop\version-
                          bin;C:\Program Files\Docker\Docker\Resources\bin;C:\Program Files
                          (x86)\Common Files\Oracle\Java\javapath;C:\ProgramData\Oracle\Java\jav
                          apath;c:\windows\system32;c:\windows;c:\windows\system32\wbem;c:\windo
                          ws\system32\windowspowershell\v1.0;C:\WINDOWS\system32;C:\WINDOWS;C:\W
                          INDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0;C:\WIN
                          DOWS\System32\OpenSSH;C:\Program Files\Cloud
                          Foundry;C:\Users\i317684\AppData\Local\Microsoft\WindowsApps;.
                  PD_PATH=C:\Program Files (x86)\AceBIT\Password Depot 9
        PLMVIS_82_LIBPATH=C:\Program Files (x86)\SAP\FrontEnd\SAPgui\Program
             PSMODULEPATH=C:\Program Files\WindowsPowerShell\Modules;C:\WINDOWS\system32\Windows
                          PowerShell\v1.0\Modules;C:\Program Files (x86)\Microsoft Azure
                          Information Protection\Powershell
       REQUESTS_CA_BUNDLE=<not set>
         SSF_LIBRARY_PATH=C:\Program Files (x86)\SAP\FrontEnd\SecureLogin\lib\sapcrypto.dll
            SSL_CERT_FILE=<not set>

     active environment : base
    active env location : C:\Users\i317684\AppData\Local\Continuum\anaconda3
            shell level : 1
       user config file : C:\Users\i317684\.condarc
 populated config files : C:\Users\i317684\.condarc
          conda version : 4.7.10
    conda-build version : 3.18.8
         python version : 3.7.3.final.0
       virtual packages :
       base environment : C:\Users\i317684\AppData\Local\Continuum\anaconda3  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/win-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\Users\i317684\AppData\Local\Continuum\anaconda3\pkgs
                          C:\Users\i317684\.conda\pkgs
                          C:\Users\i317684\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\i317684\AppData\Local\Continuum\anaconda3\envs
                          C:\Users\i317684\.conda\envs
                          C:\Users\i317684\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.7.10 requests/2.21.0 CPython/3.7.3 Windows/10 Windows/10.0.17763
          administrator : False
             netrc file : None
           offline mode : False

An unexpected error has occurred. Conda has prepared the above report.

If submitted, this report will be used by core maintainers to improve
future releases of conda.
Would you like conda to send this report to the core maintainers?

**Comment by goldi28** [comment]
Please help , its urgent

**Comment by jjhelmus** [comment]
Can you please provide the information requested in issue template.

**Comment by goldi28** [comment]
Issue :`$ C:\Users\i317684\AppData\Local\anaconda2\Scripts\conda-script.py install selenium`
Do not install any library

### Actual Behavior

Python Librarary is not getting installed. 
C:\Users\i317684>conda install selenium
Collecting package metadata (current_repodata.json): failed   <<<<< not sure why it is trying to collect from current_repodata.json






It should get installed and 

C:\Users\i317684>conda install selenium
Collecting package metadata <<<<<< Current_repodata.json should not be looking into


### Expected Behavior



Python Librarary is not getting installed. 
C:\Users\i317684>conda install selenium
Collecting package metadata (current_repodata.json): failed   <<<<< not sure why it is trying to collect from current_repodata.json


### Steps to Reproduce


Try installing any libraray in python

C:\Users\i317684>conda install selenium


##### Anaconda or Miniconda version:

 conda version : 4.7.10
    conda-build version : 3.18.8
         python version : 3.7.3.final.0



##### Operating System:

Windows 10
##### `conda info`


`$ C:\Users\i317684\AppData\Local\anaconda2\Scripts\conda-script.py install selenium`

```
PASTE OUTPUT HERE:

```

</details>

##### `conda list --show-channel-urls`


<details>

```
PASTE OUTPUT HERE:

C:\Users\i317684>conda install selenium
Collecting package metadata (current_repodata.json): failed

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "C:\Users\i317684\AppData\Local\anaconda2\lib\site-packages\urllib3\connection.py", line 159, in _new_conn
        (self._dns_host, self.port), self.timeout, **extra_kw)
      File "C:\Users\i317684\AppData\Local\anaconda2\lib\site-packages\urllib3\util\connection.py", line 57, in create_connection
        for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
      File "C:\Users\i317684\AppData\Local\anaconda2\lib\socket.py", line 748, in getaddrinfo
        for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
    socket.gaierror: [Errno 11001] getaddrinfo failed

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "C:\Users\i317684\AppData\Local\anaconda2\lib\site-packages\urllib3\connectionpool.py", line 594, in urlopen
        self._prepare_proxy(conn)
      File "C:\Users\i317684\AppData\Local\anaconda2\lib\site-packages\urllib3\connectionpool.py", line 805, in _prepare_proxy
        conn.connect()
      File "C:\Users\i317684\AppData\Local\anaconda2\lib\site-packages\urllib3\connection.py", line 301, in connect
        conn = self._new_conn()
      File "C:\Users\i317684\AppData\Local\anaconda2\lib\site-packages\urllib3\connection.py", line 168, in _new_conn
        self, "Failed to establish a new connection: %s" % e)
    urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x00000266B80A3D68>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "C:\Users\i317684\AppData\Local\anaconda2\lib\site-packages\requests\adapters.py", line 449, in send
        timeout=timeout
      File "C:\Users\i317684\AppData\Local\anaconda2\lib\site-packages\urllib3\connectionpool.py", line 667, in urlopen
        **response_kw)
      File "C:\Users\i317684\AppData\Local\anaconda2\lib\site-packages\urllib3\connectionpool.py", line 667, in urlopen
        **response_kw)
      File "C:\Users\i317684\AppData\Local\anaconda2\lib\site-packages\urllib3\connectionpool.py", line 667, in urlopen
        **response_kw)
      File "C:\Users\i317684\AppData\Local\anaconda2\lib\site-packages\urllib3\connectionpool.py", line 638, in urlopen
        _stacktrace=sys.exc_info()[2])
      File "C:\Users\i317684\AppData\Local\anaconda2\lib\site-packages\urllib3\util\retry.py", line 399, in increment
        raise MaxRetryError(_pool, url, error or ResponseError(cause))
    urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='repo.anaconda.com', port=443): Max retries exceeded with url: /pkgs/main/win-64/current_repodata.json (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x00000266B80A3D68>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')))

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "C:\Users\i317684\AppData\Local\anaconda2\lib\site-packages\conda\core\subdir_data.py", line 471, in fetch_repodata_remote_request
        timeout=timeout)
      File "C:\Users\i317684\AppData\Local\anaconda2\lib\site-packages\requests\sessions.py", line 546, in get
        return self.request('GET', url, **kwargs)
      File "C:\Users\i317684\AppData\Local\anaconda2\lib\site-packages\requests\sessions.py", line 533, in request
        resp = self.send(prep, **send_kwargs)
      File "C:\Users\i317684\AppData\Local\anaconda2\lib\site-packages\requests\sessions.py", line 646, in send
        r = adapter.send(request, **kwargs)
      File "C:\Users\i317684\AppData\Local\anaconda2\lib\site-packages\requests\adapters.py", line 510, in send
        raise ProxyError(e, request=request)
    requests.exceptions.ProxyError: HTTPSConnectionPool(host='repo.anaconda.com', port=443): Max retries exceeded with url: /pkgs/main/win-64/current_repodata.json (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x00000266B80A3D68>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')))

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "C:\Users\i317684\AppData\Local\anaconda2\lib\site-packages\conda\exceptions.py", line 1062, in __call__
        return func(*args, **kwargs)
      File "C:\Users\i317684\AppData\Local\anaconda2\lib\site-packages\conda\cli\main.py", line 84, in _main
        exit_code = do_call(args, p)
      File "C:\Users\i317684\AppData\Local\anaconda2\lib\site-packages\conda\cli\conda_argparse.py", line 82, in do_call
        exit_code = getattr(module, func_name)(args, parser)
      File "C:\Users\i317684\AppData\Local\anaconda2\lib\site-packages\conda\cli\main_install.py", line 20, in execute
        install(args, parser, 'install')
      File "C:\Users\i317684\AppData\Local\anaconda2\lib\site-packages\conda\cli\install.py", line 256, in install
        force_reinstall=context.force_reinstall or context.force,
      File "C:\Users\i317684\AppData\Local\anaconda2\lib\site-packages\conda\core\solve.py", line 112, in solve_for_transaction
        force_remove, force_reinstall)
      File "C:\Users\i317684\AppData\Local\anaconda2\lib\site-packages\conda\core\solve.py", line 150, in solve_for_diff
        force_remove)
      File "C:\Users\i317684\AppData\Local\anaconda2\lib\site-packages\conda\core\solve.py", line 249, in solve_final_state
        ssc = self._collect_all_metadata(ssc)
      File "C:\Users\i317684\AppData\Local\anaconda2\lib\site-packages\conda\common\io.py", line 88, in decorated
        return f(*args, **kwds)
      File "C:\Users\i317684\AppData\Local\anaconda2\lib\site-packages\conda\core\solve.py", line 389, in _collect_all_metadata
        index, r = self._prepare(prepared_specs)
      File "C:\Users\i317684\AppData\Local\anaconda2\lib\site-packages\conda\core\solve.py", line 974, in _prepare
        self.subdirs, prepared_specs, self._repodata_fn)
      File "C:\Users\i317684\AppData\Local\anaconda2\lib\site-packages\conda\core\index.py", line 214, in get_reduced_index
        repodata_fn=repodata_fn)
      File "C:\Users\i317684\AppData\Local\anaconda2\lib\site-packages\conda\core\subdir_data.py", line 91, in query_all
        result = tuple(concat(executor.map(subdir_query, channel_urls)))
      File "C:\Users\i317684\AppData\Local\anaconda2\lib\concurrent\futures\_base.py", line 586, in result_iterator
        yield fs.pop().result()
      File "C:\Users\i317684\AppData\Local\anaconda2\lib\concurrent\futures\_base.py", line 432, in result
        return self.__get_result()
      File "C:\Users\i317684\AppData\Local\anaconda2\lib\concurrent\futures\_base.py", line 384, in __get_result
        raise self._exception
      File "C:\Users\i317684\AppData\Local\anaconda2\lib\concurrent\futures\thread.py", line 57, in run
        result = self.fn(*self.args, **self.kwargs)
      File "C:\Users\i317684\AppData\Local\anaconda2\lib\site-packages\conda\core\subdir_data.py", line 87, in <lambda>
        package_ref_or_match_spec))
      File "C:\Users\i317684\AppData\Local\anaconda2\lib\site-packages\conda\core\subdir_data.py", line 96, in query
        self.load()
      File "C:\Users\i317684\AppData\Local\anaconda2\lib\site-packages\conda\core\subdir_data.py", line 160, in load
        _internal_state = self._load()
      File "C:\Users\i317684\AppData\Local\anaconda2\lib\site-packages\conda\core\subdir_data.py", line 234, in _load
        repodata_fn=self.repodata_fn)
      File "C:\Users\i317684\AppData\Local\anaconda2\lib\site-packages\conda\core\subdir_data.py", line 477, in fetch_repodata_remote_request
        raise ProxyError()   # see #3962
    TypeError: __init__() missing 1 required positional argument: 'message'

`$ C:\Users\i317684\AppData\Local\anaconda2\Scripts\conda-script.py install selenium`

  environment variables:
                 CIO_TEST=<not set>
                CONDA_EXE=C:\Users\i317684\AppData\Local\anaconda2\condabin\..\Scripts\conda.exe
               CONDA_EXES="C:\Users\i317684\AppData\Local\anaconda2\condabin\..\Scripts\conda.ex
                          e"
               CONDA_ROOT=C:\Users\i317684\AppData\Local\anaconda2
                 HOMEPATH=\Users\i317684
              HTTPS_PROXY=<set>
               HTTP_PROXY=<set>
                  IWBPATH=C:\Program Files (x86)\SAP\FrontEnd\iwb
                     PATH=C:\Users\i317684\AppData\Local\anaconda2;C:\Users\i317684\AppData\Loca
                          l\anaconda2\Library\mingw-w64\bin;C:\Users\i317684\AppData\Local\anaco
                          nda2\Library\usr\bin;C:\Users\i317684\AppData\Local\anaconda2\Library\
                          bin;C:\Users\i317684\AppData\Local\anaconda2\Scripts;C:\Users\i317684\
                          AppData\Local\anaconda2\bin;C:\ProgramData\DockerDesktop\version-
                          bin;C:\Program Files\Docker\Docker\Resources\bin;C:\Program Files
                          (x86)\Common Files\Oracle\Java\javapath;C:\ProgramData\Oracle\Java\jav
                          apath;c:\windows\system32;c:\windows;c:\windows\system32\wbem;c:\windo
                          ws\system32\windowspowershell\v1.0\;C:\WINDOWS\system32;C:\WINDOWS;C:\
                          WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\W
                          INDOWS\System32\OpenSSH\;C:\Program Files\Cloud Foundry;C:\Users\i3176
                          84\AppData\Local\anaconda2;C:\Users\i317684\AppData\Local\anaconda2\Li
                          brary\mingw-w64\bin;C:\Users\i317684\AppData\Local\anaconda2\Library\u
                          sr\bin;C:\Users\i317684\AppData\Local\anaconda2\Library\bin;C:\Users\i
                          317684\AppData\Local\anaconda2\Scripts;C:\Users\i317684\AppData\Local\
                          Programs\Python\Python37-32\Scripts\;C:\Users\i317684\AppData\Local\Pr
                          ograms\Python\Python37-32\;C:\Users\i317684\AppData\Local\Microsoft\Wi
                          ndowsApps
                  PD_PATH=C:\Program Files (x86)\AceBIT\Password Depot 9
        PLMVIS_82_LIBPATH=C:\Program Files (x86)\SAP\FrontEnd\SAPgui\Program
             PSMODULEPATH=C:\Program Files\WindowsPowerShell\Modules;C:\WINDOWS\system32\Windows
                          PowerShell\v1.0\Modules;C:\Program Files (x86)\Microsoft Azure
                          Information Protection\Powershell
       REQUESTS_CA_BUNDLE=<not set>
         SSF_LIBRARY_PATH=C:\Program Files (x86)\SAP\FrontEnd\SecureLogin\lib\sapcrypto.dll
            SSL_CERT_FILE=<not set>

     active environment : None
       user config file : C:\Users\i317684\.condarc
 populated config files : C:\Users\i317684\.condarc
          conda version : 4.7.10
    conda-build version : 3.18.8
         python version : 3.7.3.final.0
       virtual packages :
       base environment : C:\Users\i317684\AppData\Local\anaconda2  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\Users\i317684\AppData\Local\anaconda2\pkgs
                          C:\Users\i317684\.conda\pkgs
                          C:\Users\i317684\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\i317684\AppData\Local\anaconda2\envs
                          C:\Users\i317684\.conda\envs
                          C:\Users\i317684\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.7.10 requests/2.22.0 CPython/3.7.3 Windows/10 Windows/10.0.17763
          administrator : False
             netrc file : None
           offline mode : False


An unexpected error has occurred. Conda has prepared the above report.

If submitted, this report will be used by core maintainers to improve
future releases of conda.
Would you like conda to send this report to the core maintainers?

[y/N]:

No report sent. To permanently opt-out, use

    $ conda config --set report_errors false

</details>

**Comment by goldi28** [comment]
Please help , its urgent, if needed we can have a talk +919535525490
Do let me know if you need any more info

**Comment by goldi28** [comment]
It seems like exception inside exception is the main issue

**Comment by goldi28** [comment]
??

**Comment by forrestwaters** [comment]
The stack trace indicates you're using a proxy and are unable to resolve `repo.anaconda.com`. You'll need to look into your proxy configuration. https://docs.conda.io/projects/conda/en/latest/user-guide/configuration/use-condarc.html#config-proxy
