### ISSUE TITLE
errors in opening anaconda navigator

### ISSUE THREAD

**Issue by paipaixu** [ContinuumIO/anaconda-issues#11207]
Main Error
'root_prefix'
Traceback
Traceback (most recent call last):
  File "/Users/paixu/anaconda/lib/python2.7/site-packages/anaconda_navigator/exceptions.py", line 75, in exception_handler
    return_value = func(*args, **kwargs)
  File "/Users/paixu/anaconda/lib/python2.7/site-packages/anaconda_navigator/app/start.py", line 138, in start_app
    window = run_app(splash)
  File "/Users/paixu/anaconda/lib/python2.7/site-packages/anaconda_navigator/app/start.py", line 64, in run_app
    window = MainWindow(splash=splash, tab_project=False)
  File "/Users/paixu/anaconda/lib/python2.7/site-packages/anaconda_navigator/widgets/main_window.py", line 163, in __init__
    self.api = AnacondaAPI()
  File "/Users/paixu/anaconda/lib/python2.7/site-packages/anaconda_navigator/api/anaconda_api.py", line 2127, in AnacondaAPI
    ANACONDA_API = _AnacondaAPI()
  File "/Users/paixu/anaconda/lib/python2.7/site-packages/anaconda_navigator/api/anaconda_api.py", line 89, in __init__
    self._conda_api = CondaAPI()
  File "/Users/paixu/anaconda/lib/python2.7/site-packages/anaconda_navigator/api/conda_api.py", line 1714, in CondaAPI
    CONDA_API = _CondaAPI()
  File "/Users/paixu/anaconda/lib/python2.7/site-packages/anaconda_navigator/api/conda_api.py", line 350, in __init__
    self.set_conda_prefix(info=get_conda_info())
  File "/Users/paixu/anaconda/lib/python2.7/site-packages/anaconda_navigator/api/conda_api.py", line 505, in set_conda_prefix
    self.ROOT_PREFIX = info['root_prefix']
KeyError: 'root_prefix'

**Comment by paipaixu** [comment]
i cannot update anaconda ... it came back with "symbol not found" AttributeError..

**Comment by paipaixu** [comment]
after i tried "anaconda-navigator --reset". now the error message becomes "'NoneType' object has no attribute 'endswith'

i cannot use "conda update" as it always says "symbol not found"

**Comment by csoja** [comment]
Make sure you are running the latest version of anaconda navigator.
In a terminal or the Anaconda Command Prompt:
conda update conda
conda update anaconda-navigator
conda update navigator-updater

If the problem persists after the updates, please see if any of the suggestions in the Navigator troubleshooting section help: https://docs.anaconda.com/anaconda/navigator/troubleshooting/

If not, please open a new issue and include the information in the issue template.
