### ISSUE TITLE
spyder crashes after update

### ISSUE THREAD

**Issue by iamu99** [ContinuumIO/anaconda-issues#11211]
### Actual Behavior

conda gives me the error: spyder crashed during the last session. I tried running the spyder --reset and restarting my MacOS but to no avail.

### Expected Behavior

smooth startup

### Steps to Reproduce

launching spyder

##### Anaconda or Miniconda version:

<details>

     active environment : None
       user config file : /Users/sadiamubarik/.condarc
 populated config files : /Users/sadiamubarik/.condarc
          conda version : 4.4.8
    conda-build version : 3.0.27
         python version : 3.6.3.final.0
       base environment : /Users/sadiamubarik/anaconda3  (writable)
           channel URLs : https://repo.continuum.io/pkgs/main/osx-64
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/osx-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/osx-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/osx-64
                          https://repo.continuum.io/pkgs/pro/noarch
          package cache : /Users/sadiamubarik/anaconda3/pkgs
                          /Users/sadiamubarik/.conda/pkgs
       envs directories : /Users/sadiamubarik/anaconda3/envs
                          /Users/sadiamubarik/.conda/envs
               platform : osx-64
             user-agent : conda/4.4.8 requests/2.18.4 CPython/3.6.3 Darwin/15.6.0 OSX/10.11.6
                UID:GID : 501:20
             netrc file : None
           offline mode : False

</details>

##### `conda list --show-channel-urls`

<details>

-bash: #: command not found
</details>

**Comment by iamu99** [comment]
conda gives the following error: 

Traceback (most recent call last):
File "/Users/sadiamubarik/anaconda3/lib/python3.6/site-packages/spyder/app/mainwindow.py", line 3285, in main
mainwindow = run_spyder(app, options, args)
File "/Users/sadiamubarik/anaconda3/lib/python3.6/site-packages/spyder/app/mainwindow.py", line 3140, in run_spyder
main.setup()
File "/Users/sadiamubarik/anaconda3/lib/python3.6/site-packages/spyder/app/mainwindow.py", line 844, in setup
from spyder.plugins.editor import Editor
File "/Users/sadiamubarik/anaconda3/lib/python3.6/site-packages/spyder/plugins/editor.py", line 41, in 
from spyder.utils.introspection.manager import IntrospectionManager
File "/Users/sadiamubarik/anaconda3/lib/python3.6/site-packages/spyder/utils/introspection/manager.py", line 21, in 
from spyder.utils.introspection.plugin_client import PluginClient
File "/Users/sadiamubarik/anaconda3/lib/python3.6/site-packages/spyder/utils/introspection/plugin_client.py", line 18, in 
import zmq
File "/Users/sadiamubarik/anaconda3/lib/python3.6/site-packages/zmq/__init__.py", line 47, in 
from zmq import backend
File "/Users/sadiamubarik/anaconda3/lib/python3.6/site-packages/zmq/backend/__init__.py", line 40, in 
reraise(*exc_info)
File "/Users/sadiamubarik/anaconda3/lib/python3.6/site-packages/zmq/utils/sixcerpt.py", line 34, in reraise
raise value
File "/Users/sadiamubarik/anaconda3/lib/python3.6/site-packages/zmq/backend/__init__.py", line 27, in 
_ns = select_backend(first)
File "/Users/sadiamubarik/anaconda3/lib/python3.6/site-packages/zmq/backend/select.py", line 26, in select_backend
mod = __import__(name, fromlist=public_api)
File "/Users/sadiamubarik/anaconda3/lib/python3.6/site-packages/zmq/backend/cython/__init__.py", line 6, in 
from . import (constants, error, message, context,
ImportError: dlopen(/Users/sadiamubarik/anaconda3/lib/python3.6/site-packages/zmq/backend/cython/error.cpython-36m-darwin.so, 2): Library not loaded: @rpath/libsodium.23.dylib
Referenced from: /Users/sadiamubarik/anaconda3/lib/libzmq.5.dylib
Reason: image not found
