### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by Janecocoa** [ContinuumIO/anaconda-issues#11215]
## Main error
An unexpected error occurred on Navigator start-up<br>psutil.AccessDenied (pid=683)
## Traceback
```
Traceback (most recent call last):
  File "/Users/noppadonsakulsom/anaconda/lib/python3.6/site-packages/psutil/_psosx.py", line 313, in catch_zombie
    yield
  File "/Users/noppadonsakulsom/anaconda/lib/python3.6/site-packages/psutil/_psosx.py", line 377, in cmdline
    return cext.proc_cmdline(self.pid)
ProcessLookupError: [Errno 3] No such process

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/noppadonsakulsom/anaconda/lib/python3.6/site-packages/anaconda_navigator/exceptions.py", line 75, in exception_handler
    return_value = func(*args, **kwargs)
  File "/Users/noppadonsakulsom/anaconda/lib/python3.6/site-packages/anaconda_navigator/app/start.py", line 108, in start_app
    if misc.load_pid() is None:  # A stale lock might be around
  File "/Users/noppadonsakulsom/anaconda/lib/python3.6/site-packages/anaconda_navigator/utils/misc.py", line 384, in load_pid
    cmds = process.cmdline()
  File "/Users/noppadonsakulsom/anaconda/lib/python3.6/site-packages/psutil/__init__.py", line 712, in cmdline
    return self._proc.cmdline()
  File "/Users/noppadonsakulsom/anaconda/lib/python3.6/site-packages/psutil/_psosx.py", line 295, in wrapper
    return fun(self, *args, **kwargs)
  File "/Users/noppadonsakulsom/anaconda/lib/python3.6/site-packages/psutil/_psosx.py", line 377, in cmdline
    return cext.proc_cmdline(self.pid)
  File "/Users/noppadonsakulsom/anaconda/lib/python3.6/contextlib.py", line 99, in __exit__
    self.gen.throw(type, value, traceback)
  File "/Users/noppadonsakulsom/anaconda/lib/python3.6/site-packages/psutil/_psosx.py", line 326, in catch_zombie
    raise AccessDenied(proc.pid, proc._name)
psutil.AccessDenied: psutil.AccessDenied (pid=683)

```
## System information
```
python: 3.6.8
language: en
os: Darwin;18.7.0;Darwin Kernel Version 18.7.0: Thu Jun 20 18:42:21 PDT 2019; root:xnu-4903.270.47~4/RELEASE_X86_64;x86_64;i386
version: 1.6.2
platform: osx-64
qt: 5.6.2
pyqt: 5.6.0
conda: 4.7.11
```

**Comment by csoja** [comment]
In a terminal:

conda update conda
conda update anaconda-navigator
conda update navigator-updater
anaconda-navigator --reset

The last command is the key to fixing your issue - as it removes the lock file that is causing your problem.
