### ISSUE TITLE
Navigator Error : An unexpected error occurred on Navigator start-up

### ISSUE THREAD

**Issue by shinron001** [ContinuumIO/anaconda-issues#11220]
##### `conda info`

<details>

```
PASTE OUTPUT HERE:

```

</details>

##### `conda list --show-channel-urls`

<details>

```
PASTE OUTPUT HERE:

```
Navigator Error
An unexpected error occurred on Navigator start-up

Report
Please report this issue in the anaconda issue tracker

Main Error
expected str, bytes or os.PathLike object, not NoneType
Traceback
Traceback (most recent call last):
  File "C:\Users\Darkside\Anaconda3\lib\site-packages\anaconda_navigator\exceptions.py", line 75, in exception_handler
    return_value = func(*args, **kwargs)
  File "C:\Users\Darkside\Anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 151, in start_app
    window = run_app(splash)
  File "C:\Users\Darkside\Anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 65, in run_app
    window = MainWindow(splash=splash, tab_project=False)
  File "C:\Users\Darkside\Anaconda3\lib\site-packages\anaconda_navigator\widgets\main_window.py", line 168, in __init__
    self.api = AnacondaAPI()
  File "C:\Users\Darkside\Anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 2337, in AnacondaAPI
    ANACONDA_API = _AnacondaAPI()
  File "C:\Users\Darkside\Anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 89, in __init__
    self._conda_api = CondaAPI()
  File "C:\Users\Darkside\Anaconda3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 1773, in CondaAPI
    CONDA_API = _CondaAPI()
  File "C:\Users\Darkside\Anaconda3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 353, in __init__
    self.sys_rc_path = join(self.ROOT_PREFIX, '.condarc')
  File "C:\Users\Darkside\Anaconda3\lib\ntpath.py", line 76, in join
    path = os.fspath(path)
TypeError: expected str, bytes or os.PathLike object, not NoneType
</details>

**Comment by VRHaritha** [comment]
My Anaconda version is 3.6 and my operating system is Windows 10. I'm unable to open anaconda navigator. I'm getting navigation error. I uninstalled many times and re-installed it but the result is the same. Please help me. Thanks in advance.

**Comment by csoja** [comment]
The details of the Navigator error suggest that your .condarc file has gotten corrupted.  I'd recommend deleting it and attempting to start Navigator again.
Typically, the .condarc file is located in a directory like C:\Users\YOURUSERNAME\.condarc
Or you can use the command _conda info_ in the Anaconda Prompt.  The output of that will list the exact location of the .condarc configuration file(s) conda is using.

**Comment by VRHaritha** [comment]
Thank you so much. It worked perfectly....
