### ISSUE TITLE
packaging 19.1 requires attrs as a dependency

### ISSUE THREAD

**Issue by 183amir** [ContinuumIO/anaconda-issues#11236]
### Actual Behavior

Installed packaging 19.1 conda package is missing a dependency of `attrs` package

### Expected Behavior

Installing packaging 19.1 should install the `attrs` conda package as well.

### Steps to Reproduce

```
conda create -n temp python=3.6 setuptools sphinx=2.1.2
conda activate temp
python -c "import pkg_resources; pkg_resources.require('sphinx')"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "~/miniconda/envs/temp/lib/python3.6/site-packages/pkg_resources/__init__.py", line 900, in require
    needed = self.resolve(parse_requirements(requirements))
  File "~/miniconda/envs/temp/lib/python3.6/site-packages/pkg_resources/__init__.py", line 786, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'attrs' distribution was not found and is required by packaging
```
This happens only in packaging 19.1

##### `conda info`

<details>

```
     active environment : temp
    active env location : /home/amir/miniconda/envs/temp
            shell level : 3
       user config file : /home/amir/.condarc
 populated config files : /home/amir/miniconda/.condarc
                          /home/amir/.condarc
          conda version : 4.7.10
    conda-build version : 3.16.3
         python version : 3.6.8.final.0
       virtual packages : 
       base environment : /home/amir/miniconda  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /home/amir/miniconda/pkgs
                          /home/amir/.conda/pkgs
       envs directories : /home/amir/miniconda/envs
                          /home/amir/.conda/envs
               platform : linux-64
             user-agent : conda/4.7.10 requests/2.22.0 CPython/3.6.8 Linux/5.2.9-arch1-1-ARCH arch/rolling glibc/2.29
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False
```

</details>

##### `conda list --show-channel-urls`

<details>

```
# packages in environment at /home/amir/miniconda/envs/temp:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main    defaults
alabaster                 0.7.12                   py36_0    defaults
asn1crypto                0.24.0                   py36_0    defaults
babel                     2.7.0                      py_0    defaults
ca-certificates           2019.5.15                     1    defaults
certifi                   2019.6.16                py36_1    defaults
cffi                      1.12.3           py36h2e261b9_0    defaults
chardet                   3.0.4                 py36_1003    defaults
cryptography              2.7              py36h1ba5d50_0    defaults
docutils                  0.15.2                   py36_0    defaults
idna                      2.8                      py36_0    defaults
imagesize                 1.1.0                    py36_0    defaults
jinja2                    2.10.1                   py36_0    defaults
libedit                   3.1.20181209         hc058e9b_0    defaults
libffi                    3.2.1                hd88cf55_4    defaults
libgcc-ng                 9.1.0                hdf63c60_0    defaults
libstdcxx-ng              9.1.0                hdf63c60_0    defaults
markupsafe                1.1.1            py36h7b6447c_0    defaults
ncurses                   6.1                  he6710b0_1    defaults
openssl                   1.1.1c               h7b6447c_1    defaults
packaging                 19.1                     py36_0    defaults
pycparser                 2.19                     py36_0    defaults
pygments                  2.4.2                      py_0    defaults
pyopenssl                 19.0.0                   py36_0    defaults
pyparsing                 2.4.2                      py_0    defaults
pysocks                   1.7.0                    py36_0    defaults
python                    3.6.9                h265db76_0    defaults
pytz                      2019.2                     py_0    defaults
readline                  7.0                  h7b6447c_5    defaults
requests                  2.22.0                   py36_0    defaults
setuptools                41.0.1                   py36_0    defaults
six                       1.12.0                   py36_0    defaults
snowballstemmer           1.9.0                      py_0    defaults
sphinx                    2.1.2                      py_0    defaults
sphinxcontrib             1.0                      py36_1    defaults
sphinxcontrib-applehelp   1.0.1                      py_0    defaults
sphinxcontrib-devhelp     1.0.1                      py_0    defaults
sphinxcontrib-htmlhelp    1.0.2                      py_0    defaults
sphinxcontrib-jsmath      1.0.1                      py_0    defaults
sphinxcontrib-qthelp      1.0.2                      py_0    defaults
sphinxcontrib-serializinghtml 1.1.3                      py_0    defaults
sphinxcontrib-websupport  1.1.2                      py_0    defaults
sqlite                    3.29.0               h7b6447c_0    defaults
tk                        8.6.8                hbc83047_0    defaults
typing                    3.6.4                    py36_0    defaults
urllib3                   1.24.2                   py36_0    defaults
xz                        5.2.4                h14c3975_4    defaults
zlib                      1.2.11               h7b6447c_3    defaults

```

</details>

**Comment by 183amir** [comment]
Sorry looks like I read the message wrongly. It's not sphinx but its `packaging`. Please see: https://github.com/pypa/packaging/issues/178

**Comment by anjos** [comment]
@jjhelmus and @Maggie-M, I just noticed your recent update to packaging 19.2 (https://github.com/AnacondaRecipes/packaging-feedstock/commit/6f193954a5b5408c416255043e2090c515895bd8) does not include a fix for this issue.  Could you please confirm the issue?

**Comment by jjhelmus** [comment]
@anjos `attrs` was dropped as a dependency in the 19.2 release of packaging, see pypa/packaging#179.  The 19.2 conda package's requirements reflects this change.

**Comment by anjos** [comment]
I can confirm this fixed the problem.  Thx.
