### ISSUE TITLE
Fixing conflict with python-daemon=2.1.2, python 2.7.16 (related luigi 2.8.9 dependencies)

### ISSUE THREAD

**Issue by pmlandwehr** [ContinuumIO/anaconda-issues#11249]
I would be loathe to ask about planned updates to `luigi` since it's also in `conda-forge`, but [version `2.8.9` updates a very old version pinning for `tornado`](https://github.com/spotify/luigi/releases/tag/2.8.9), so it would be cool if that could be added to the default version of conda at some point.

**Comment by pmlandwehr** [comment]
This appears to have happened! (Thanks!) However, the new version breaks a critical dependency in luigi for `python-daemon<2.2.0`. (See [this luigi issue](https://github.com/spotify/luigi/issues/2525) and [this python-daemon issue](https://pagure.io/python-daemon/issue/18), referenced in the current setup.py. For reasons that are unclear, the conda package in the default channel for `python-daemon=2.1.2` now has unresolvable conflicts with python 2.7.15 and 2.7.16.  Please see the example code snippet below, which checks luigi and python-daemon version, tries to run a luigi task, and the tries to revert to an older python-daemon:

```
pmlandwehr@pml-computer ~> conda list luigi                                                                                                                                         (base) 
# packages in environment at /opt/anaconda2:
#
# Name                    Version                   Build  Channel
luigi                     2.8.9                    py27_0  
pmlandwehr@pml-computer ~>                                                                                                                                                          (base) 
pmlandwehr@pml-computer ~> conda list python-daemon                                                                                                                                 (base) 
# packages in environment at /opt/anaconda2:
#
# Name                    Version                   Build  Channel
python-daemon             2.2.3                    py27_0  
pmlandwehr@pml-computer ~> process-local-parallel --help                                                                                                                            (base) 
Traceback (most recent call last):
  File "/opt/anaconda2/bin/process-local-parallel", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/opt/anaconda2/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3250, in <module>
    @_call_aside
  File "/opt/anaconda2/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3234, in _call_aside
    f(*args, **kwargs)
  File "/opt/anaconda2/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3263, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/opt/anaconda2/lib/python2.7/site-packages/pkg_resources/__init__.py", line 585, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/opt/anaconda2/lib/python2.7/site-packages/pkg_resources/__init__.py", line 598, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/opt/anaconda2/lib/python2.7/site-packages/pkg_resources/__init__.py", line 786, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'python-daemon<2.2.0' distribution was not found and is required by luigi
pmlandwehr@pml-computer ~> conda install python-daemon=2.1.2                                                                                                                        (base) 
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: - 
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed                                                                                                                                                                                     
                                                                                                                                                                                           
UnsatisfiableError: The following specifications were found                                                                                                                                
to be incompatible with the existing python installation in your environment:

Specifications:

  - python-daemon=2.1.2 -> python[version='>=3.7,<3.8.0a0']

Your python: python=2.7

If python is on the left-most side of the chain, that's the version you've asked for.
When python appears to the right, that indicates that the thing on the left is somehow
not available for the python version you are constrained to. Note that conda will not
change your python version to a different minor version unless you explicitly specify
that.

The following specifications were found to be incompatible with each other:



Package wheel conflicts for:
python-daemon=2.1.2 -> python[version='>=3.7,<3.8.0a0'] -> pip -> wheel
python=2.7 -> pip -> wheel
Package pip conflicts for:
python=2.7 -> pip
python-daemon=2.1.2 -> python[version='>=3.7,<3.8.0a0'] -> pip
Package ca-certificates conflicts for:
python=2.7 -> ca-certificates
python-daemon=2.1.2 -> python[version='>=3.7,<3.8.0a0'] -> openssl[version='>=1.1.1c,<1.1.2a'] -> ca-certificates
Package certifi conflicts for:
python-daemon=2.1.2 -> setuptools -> certifi[version='>=2016.09']
python=2.7 -> pip -> setuptools -> certifi[version='>=2016.09']
Package setuptools conflicts for:
python=2.7 -> pip -> setuptools
python-daemon=2.1.2 -> setuptools

pmlandwehr@pml-computer ~>  
```

**Comment by jjhelmus** [comment]
What platform are you running into this conflict?  On linux-64 I'm not running into an issue creating a Python 2.7 environment with luigi 2.8.9 and python-deamon<2.2:

```
$ conda create -n example python=2.7 luigi "python-daemon<2.2.0"
Collecting package metadata (current_repodata.json): done
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /home/jhelmus/conda/envs/example

  added / updated specs:
    - luigi
    - python-daemon[version='<2.2.0']
    - python=2.7


The following NEW packages will be INSTALLED:

  _libgcc_mutex      pkgs/main/linux-64::_libgcc_mutex-0.1-main
  backports_abc      pkgs/main/linux-64::backports_abc-0.5-py27_0
  ca-certificates    pkgs/main/linux-64::ca-certificates-2019.8.28-0
  certifi            pkgs/main/linux-64::certifi-2019.9.11-py27_0
  docutils           pkgs/main/linux-64::docutils-0.15.2-py27_0
  enum34             pkgs/main/linux-64::enum34-1.1.6-py27_1
  futures            pkgs/main/linux-64::futures-3.3.0-py27_0
  libedit            pkgs/main/linux-64::libedit-3.1.20181209-hc058e9b_0
  libffi             pkgs/main/linux-64::libffi-3.2.1-hd88cf55_4
  libgcc-ng          pkgs/main/linux-64::libgcc-ng-9.1.0-hdf63c60_0
  libstdcxx-ng       pkgs/main/linux-64::libstdcxx-ng-9.1.0-hdf63c60_0
  lockfile           pkgs/main/linux-64::lockfile-0.12.2-py27_0
  luigi              pkgs/main/linux-64::luigi-2.8.9-py27_0
  ncurses            pkgs/main/linux-64::ncurses-6.1-he6710b0_1
  openssl            pkgs/main/linux-64::openssl-1.1.1d-h7b6447c_2
  python             pkgs/main/linux-64::python-2.7.16-h9bab390_7
  python-daemon      pkgs/main/linux-64::python-daemon-2.1.2-py27_0
  python-dateutil    pkgs/main/linux-64::python-dateutil-2.8.0-py27_0
  readline           pkgs/main/linux-64::readline-7.0-h7b6447c_5
  setuptools         pkgs/main/linux-64::setuptools-41.2.0-py27_0
  singledispatch     pkgs/main/linux-64::singledispatch-3.4.0.3-py27_0
  six                pkgs/main/linux-64::six-1.12.0-py27_0
  sqlite             pkgs/main/linux-64::sqlite-3.29.0-h7b6447c_0
  tk                 pkgs/main/linux-64::tk-8.6.8-hbc83047_0
  tornado            pkgs/main/linux-64::tornado-5.1.1-py27h7b6447c_0
  zlib               pkgs/main/linux-64::zlib-1.2.11-h7b6447c_3
```

**Comment by jjhelmus** [comment]
I'm guessing the issue is with osx-64 since there is not solution unless the free channel is added back:

```
$ CONDA_SUBDIR=osx-64 conda create -n example python=2.7 luigi "python-daemon<2.2"
Collecting package metadata (current_repodata.json): done
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: | 
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed                                                                                                                                                                              
                                                                                                                                                                                    
UnsatisfiableError: The following specifications were found to be incompatible with each other:                                                                                     



Package python conflicts for:
python=2.7
luigi -> pyparsing -> python
python-daemon[version='<2.2'] -> python[version='>=3.7,<3.8.0a0']
Package python-daemon conflicts for:
luigi -> python-daemon[version='<3.0']

```

```
$ CONDA_RESTORE_FREE_CHANNEL=1 CONDA_SUBDIR=osx-64 conda create -n example python=2.7 luigi "python-daemon<2.2"
Collecting package metadata (current_repodata.json): done                 
Solving environment: done                                                 
                                                                          
## Package Plan ##                                                        
                                                                          
  environment location: /home/jhelmus/conda/envs/example                  
                                                                          
  added / updated specs:                                                  
    - luigi                                                               
    - python-daemon[version='<2.2']                                       
    - python=2.7                                                          
                                                                          
                                                 
The following NEW packages will be INSTALLED:    
                                                                          
  backports_abc      pkgs/main/osx-64::backports_abc-0.5-py27h6972548_0   
  ca-certificates    pkgs/main/osx-64::ca-certificates-2019.8.28-0        
  certifi            pkgs/main/osx-64::certifi-2019.9.11-py27_0           
  enum34             pkgs/main/osx-64::enum34-1.1.6-py27_1                
  futures            pkgs/main/osx-64::futures-3.3.0-py27_0               
  libcxx             pkgs/main/osx-64::libcxx-4.0.1-hcfea43d_1            
  libcxxabi          pkgs/main/osx-64::libcxxabi-4.0.1-hcfea43d_1         
  libedit            pkgs/main/osx-64::libedit-3.1.20181209-hb402a30_0    
  libffi             pkgs/main/osx-64::libffi-3.2.1-h475c297_4            
  lockfile           pkgs/main/osx-64::lockfile-0.12.2-py27_0             
  luigi              pkgs/main/osx-64::luigi-2.8.9-py27_0                 
  ncurses            pkgs/main/osx-64::ncurses-6.1-h0a44026_1             
  python             pkgs/main/osx-64::python-2.7.16-h97142e2_7           
  python-daemon      pkgs/free/osx-64::python-daemon-2.1.2-py27_0         
  python-dateutil    pkgs/main/osx-64::python-dateutil-2.8.0-py27_0       
  readline           pkgs/main/osx-64::readline-7.0-h1de35cc_5            
  setuptools         pkgs/main/osx-64::setuptools-41.2.0-py27_0           
  singledispatch     pkgs/main/osx-64::singledispatch-3.4.0.3-py27he22c18d_0
  six                pkgs/main/osx-64::six-1.12.0-py27_0                  
  sqlite             pkgs/main/osx-64::sqlite-3.29.0-ha441bb4_0           
  tk                 pkgs/main/osx-64::tk-8.6.8-ha441bb4_0                
  tornado            pkgs/main/osx-64::tornado-5.1.1-py27h1de35cc_0       
  zlib               pkgs/main/osx-64::zlib-1.2.11-h1de35cc_3   
```

@pmlandwehr Is adding the free channel back for a solution an acceptable solution?  This channel was removed in conda 4.7 as described in the [blog post](https://www.anaconda.com/why-we-removed-the-free-channel-in-conda-4-7/) on the topic.

**Comment by pmlandwehr** [comment]
Hey! Yep, I'm on an os x 64 environment. I wasn't aware of the free channel, and I don't know that I really have the capability to evaluate that, honestly. It's a fine solution for me, specifically. I have also found that I can compel conda-forge to install `python-daemon=2.1.2` package even though the default is to install the latest version. I think the question is what the right thing is for anaconda to do in this scenario, especially since it sounds from the blog post that y'all want to discourage use of the free channel. But yes! I'm satisfied.
Here's my conda info, for the record"

```
     active environment : base
    active env location : /opt/anaconda2
            shell level : 1
       user config file : /Users/pmlandwehr/.condarc
 populated config files : /Users/pmlandwehr/.condarc
          conda version : 4.7.12
    conda-build version : not installed
         python version : 2.7.16.final.0
       virtual packages : 
       base environment : /opt/anaconda2  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/osx-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/osx-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /opt/anaconda2/pkgs
                          /Users/pmlandwehr/.conda/pkgs
       envs directories : /opt/anaconda2/envs
                          /Users/pmlandwehr/.conda/envs
               platform : osx-64
             user-agent : conda/4.7.12 requests/2.22.0 CPython/2.7.16 Darwin/18.7.0 OSX/10.14.6
                UID:GID : 501:20
             netrc file : None
           offline mode : False
```

**Comment by jjhelmus** [comment]
Great to hear this is working for you @pmlandwehr.  Although not ideal, adding in the `free` channel to be able to install the older version of `python-daemon` seems like the best option at this point.  Hopefully future updates to `luigi` will have better support newer versions of `python-daemon` so this is less of an issue.
