### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by Kushan007** [ContinuumIO/anaconda-issues#11247]
### Actual Behavior

Navigator Error
An unexpected error occurred on Navigator start-up

### Expected Behavior

The anaconda navigator should open up

### Steps to Reproduce

Opening the navigator reproduces the issue

##### Anaconda or Miniconda version:

Version - Anaconda3

##### `conda info`

<details>

```
Traceback
Traceback (most recent call last):
  File "C:\Users\hp\Anaconda3\lib\site-packages\anaconda_navigator\exceptions.py", line 75, in exception_handler
    return_value = func(*args, **kwargs)
  File "C:\Users\hp\Anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 151, in start_app
    window = run_app(splash)
  File "C:\Users\hp\Anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 65, in run_app
    window = MainWindow(splash=splash, tab_project=False)
  File "C:\Users\hp\Anaconda3\lib\site-packages\anaconda_navigator\widgets\main_window.py", line 168, in __init__
    self.api = AnacondaAPI()
  File "C:\Users\hp\Anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 2337, in AnacondaAPI
    ANACONDA_API = _AnacondaAPI()
  File "C:\Users\hp\Anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 89, in __init__
    self._conda_api = CondaAPI()
  File "C:\Users\hp\Anaconda3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 1773, in CondaAPI
    CONDA_API = _CondaAPI()
  File "C:\Users\hp\Anaconda3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 350, in __init__
    self.set_conda_prefix(info=get_conda_info())
  File "C:\Users\hp\Anaconda3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 505, in set_conda_prefix
    self.ROOT_PREFIX = info['root_prefix']
KeyError: 'root_prefix'

```

</details>

##### `conda list --show-channel-urls`

<details>

```

```

</details>

**Comment by csoja** [comment]
Have you tried the suggestions here:  https://docs.anaconda.com/anaconda/navigator/troubleshooting/#navigator-error-on-start-up ?
Also, though you have not included the output of conda info or conda list --show-channel-urls, I suspect you need to update to the latest conda and Anaconda-Navigator.  I'm going to close this issue - but please reopen if you are still having trouble with the latest.
