### ISSUE TITLE
How to install Google Cloud sdk, since Anaconda makes Python3 default??

### ISSUE THREAD

**Issue by dartdog** [ContinuumIO/anaconda-issues#1125]
I just tried to install the Google cloud sdk as instructed here:
Running on a new Ubuntu 16.04 install
https://cloud.google.com/sdk/downloads
and I get this: 
Running the install as suggested : tom@tomServal:~$ curl https://sdk.cloud.google.com | bash
/home/tom/google-cloud-sdk/install.sh
Welcome to the Google Cloud SDK!
Traceback (most recent call last):
  File "/home/tom/google-cloud-sdk/lib/third_party/enum/__init__.py", line 364, in __getattr__
    return cls._member_map_[name]
KeyError: '_convert'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/tom/google-cloud-sdk/bin/bootstrapping/install.py", line 8, in <module>
    import bootstrapping
  File "/home/tom/google-cloud-sdk/bin/bootstrapping/bootstrapping.py", line 9, in <module>
    import setup
  File "/home/tom/google-cloud-sdk/bin/bootstrapping/setup.py", line 34, in <module>
    from googlecloudsdk.core.util import platforms
  File "/home/tom/google-cloud-sdk/lib/googlecloudsdk/core/util/platforms.py", line 18, in <module>
    import platform
  File "/home/tom/anaconda3/lib/python3.5/platform.py", line 117, in <module>
    import sys, os, re, subprocess
  File "/home/tom/anaconda3/lib/python3.5/subprocess.py", line 364, in <module>
    import signal
  File "/home/tom/anaconda3/lib/python3.5/signal.py", line 8, in <module>
    _IntEnum._convert(
  File "/home/tom/google-cloud-sdk/lib/third_party/enum/__init__.py", line 366, in __getattr__
    raise AttributeError(name)
AttributeError: _convert

I've reported to Google but was hoping someone there has a solution

**Comment by dartdog** [comment]
So.. I think that by activating the py27 env then doing the installs using the bash installer I have a good installation, and I think it works without the env being active after install... we shall see... Might be good to document somewhere!
