### ISSUE TITLE
Navigation Error: 'root prefix'

### ISSUE THREAD

**Issue by willbaumgardner** [ContinuumIO/anaconda-issues#11258]
### Actual Behavior
Opening Anaconda Navigator on Windows 1 takes me to webpage with this error:

Navigator Error

An unexpected error occurred on Navigator start-up
Report

Please report this issue in the anaconda issue tracker
Main Error

'root_prefix'

Traceback

Traceback (most recent call last):
  File "C:\Users\willb\Anaconda3\lib\site-packages\anaconda_navigator\exceptions.py", line 75, in exception_handler
    return_value = func(*args, **kwargs)
  File "C:\Users\willb\Anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 151, in start_app
    window = run_app(splash)
  File "C:\Users\willb\Anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 65, in run_app
    window = MainWindow(splash=splash, tab_project=False)
  File "C:\Users\willb\Anaconda3\lib\site-packages\anaconda_navigator\widgets\main_window.py", line 168, in __init__
    self.api = AnacondaAPI()
  File "C:\Users\willb\Anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 2337, in AnacondaAPI
    ANACONDA_API = _AnacondaAPI()
  File "C:\Users\willb\Anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 89, in __init__
    self._conda_api = CondaAPI()
  File "C:\Users\willb\Anaconda3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 1773, in CondaAPI
    CONDA_API = _CondaAPI()
  File "C:\Users\willb\Anaconda3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 350, in __init__
    self.set_conda_prefix(info=get_conda_info())
  File "C:\Users\willb\Anaconda3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 505, in set_conda_prefix
    self.ROOT_PREFIX = info['root_prefix']
KeyError: 'root_prefix'

### Expected Behavior

Anaconda Navigator Opens

### Steps to Reproduce

This happens any time I try to open Anaconda Navigator. I reinstalled Anaconda and the same error is still occurring.

##### Anaconda or Miniconda version:
Anaconda3 2019.07

##### Operating System:

Windows 10

![image](https://user-images.githubusercontent.com/40476767/64296320-b000e180-cf28-11e9-911a-ffb1427485d1.png)

**Comment by csoja** [comment]
Make sure you are running the latest version of anaconda navigator.
In a terminal or the Anaconda Command Prompt:
conda update conda
conda update anaconda-navigator
conda update navigator-updater

If the problem persists after the updates, please see if any of the suggestions in the Navigator troubleshooting section help: https://docs.anaconda.com/anaconda/navigator/troubleshooting/

If not, please open a new issue.
