### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by mangeshksagar** [ContinuumIO/anaconda-issues#11265]
## Main error
Application <b>spyder</b> launch may have produced errors.
## Traceback
```
Traceback (most recent call last):
  File "/nfs/cms/mtech18/mangesh.kshirsagar/.conda/envs/Home/lib/python3.6/site-packages/spyder/app/mainwindow.py", line 3285, in main
    mainwindow = run_spyder(app, options, args)
  File "/nfs/cms/mtech18/mangesh.kshirsagar/.conda/envs/Home/lib/python3.6/site-packages/spyder/app/mainwindow.py", line 3140, in run_spyder
    main.setup()
  File "/nfs/cms/mtech18/mangesh.kshirsagar/.conda/envs/Home/lib/python3.6/site-packages/spyder/app/mainwindow.py", line 831, in setup
    from spyder.plugins.help import Help
  File "/nfs/cms/mtech18/mangesh.kshirsagar/.conda/envs/Home/lib/python3.6/site-packages/spyder/plugins/help.py", line 32, in <module>
    from spyder.utils.help.sphinxify import (CSS_PATH, generate_context,
  File "/nfs/cms/mtech18/mangesh.kshirsagar/.conda/envs/Home/lib/python3.6/site-packages/spyder/utils/help/sphinxify.py", line 31, in <module>
    import sphinx
ModuleNotFoundError: No module named 'sphinx'

```
## System information
```
pyqt: 5.6.0
language: en_IN
qt: 5.6.2
python: 3.5.3
os: Linux;4.15.0-60-generic;#67~16.04.1-Ubuntu SMP Mon Aug 26 08:57:33 UTC 2019;x86_64;x86_64
version: 1.6.2
platform: linux-64
conda: 4.3.30
```

**Comment by csoja** [comment]
I'm not sure what is causing your error. However, it looks like you are running very old software. I'd recommend updating conda and anaconda-navigator and spyder. I'm going to close this - please open a new issue if you are still having problems with the latest Spyder, conda, and Anaconda-Navigator.
