### ISSUE TITLE
ImportError with _collections and deque

### ISSUE THREAD

**Issue by mutaku** [ContinuumIO/anaconda-issues#11266]
### Actual Behavior
1) trying to run conda package started to cause an import error
`ImportError: cannot import name deque` caused by miniconda2/lib/python2.7/collections.py
2) updated conda and same result
3) deleted conda entirely and fixed paths, ran miniconda installer and upon initializing it hit same error and would not start

* Conda was installed and working fine for > 1 year without issue.

### Expected Behavior
1) conda executes packages without failing
2) same as above assuming it was a bug
3) clean install should work

### Steps to Reproduce
Run conda in any manner (miniconda2/bin/conda)

##### Anaconda or Miniconda version:
Miniconda2-latest-Linux-x86_64.sh

##### `conda info`

```
Traceback (most recent call last):
  File "miniconda2/bin/conda", line 12, in <module>
    from conda.cli import main
  File "/home/user/miniconda2/lib/python2.7/site-packages/conda/__init__.py", line 19, in <module>
    from .common.compat import text_type, iteritems
  File "/home/user/miniconda2/lib/python2.7/site-packages/conda/common/compat.py", line 94, in <module>
    from collections import Mapping, Sequence
  File "/home/user/miniconda2/lib/python2.7/collections.py", line 20, in <module>
    from _collections import deque, defaultdict
ImportError: cannot import name deque

```

</details>

##### `conda list --show-channel-urls`

```
Not applicable - will not run

```

</details>

**Comment by mutaku** [comment]
Upon additional testing, it appears that anything in `lib/python2.7/collections.py` that references `_collections` fails to import.
