### ISSUE TITLE
Anaconda-Navigator.app not opening after MacOSx update

### ISSUE THREAD

**Issue by ssalieska** [ContinuumIO/anaconda-issues#11267]
The application “Anaconda-Navigator.app” can’t be opened. error comes up when trying to open Anaconda-Navigator icon on Mac. This error occurred after MacOSx update.

##### `conda info`

<details>

```
Vendor:  continuum
Product: anaconda
Message: trial mode expires in 30 days
/Users/ssalie/anaconda/lib/python2.7/site-packages/cryptography/hazmat/primitives/constant_time.py:26: CryptographyDeprecationWarning: Support for your Python version is deprecated. The next version of cryptography will remove support. Please upgrade to a release (2.7.7+) that supports hmac.compare_digest as soon as possible.
  utils.PersistentlyDeprecated2018,

     active environment : None
       user config file : /Users/ssalie/.condarc
 populated config files : /Users/ssalie/.condarc
          conda version : 4.7.11
    conda-build version : 0+unknown
         python version : 2.7.3.final.0
       virtual packages :
       base environment : /Users/ssalie/anaconda  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/osx-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/osx-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/osx-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /Users/ssalie/anaconda/pkgs
                          /Users/ssalie/.conda/pkgs
       envs directories : /Users/ssalie/anaconda/envs
                          /Users/ssalie/.conda/envs
               platform : osx-64
             user-agent : conda/4.7.11 requests/2.18.4 CPython/2.7.3 Darwin/18.7.0 OSX/10.14.6
                UID:GID : 501:20
             netrc file : None
           offline mode : False

```

</details>

##### `conda list --show-channel-urls`

```

MacBook-Pro-2:~ ssalie$ conda list
Vendor:  continuum
Product: anaconda
Message: trial mode expires in 30 days
/Users/ssalie/anaconda/lib/python2.7/site-packages/cryptography/hazmat/primitives/constant_time.py:26: CryptographyDeprecationWarning: Support for your Python version is deprecated. The next version of cryptography will remove support. Please upgrade to a release (2.7.7+) that supports hmac.compare_digest as soon as possible.
  utils.PersistentlyDeprecated2018,

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/Users/ssalie/anaconda/lib/python2.7/site-packages/conda/exceptions.py", line 1062, in __call__
        return func(*args, **kwargs)
      File "/Users/ssalie/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 84, in _main
        exit_code = do_call(args, p)
      File "/Users/ssalie/anaconda/lib/python2.7/site-packages/conda/cli/conda_argparse.py", line 82, in do_call
        exit_code = getattr(module, func_name)(args, parser)
      File "/Users/ssalie/anaconda/lib/python2.7/site-packages/conda/cli/main_list.py", line 142, in execute
        show_channel_urls=context.show_channel_urls)
      File "/Users/ssalie/anaconda/lib/python2.7/site-packages/conda/cli/main_list.py", line 80, in print_packages
        show_channel_urls=show_channel_urls)
      File "/Users/ssalie/anaconda/lib/python2.7/site-packages/conda/cli/main_list.py", line 45, in list_packages
        installed = sorted(PrefixData(prefix, pip_interop_enabled=True).iter_records(),
      File "/Users/ssalie/anaconda/lib/python2.7/site-packages/conda/core/prefix_data.py", line 133, in iter_records
        return itervalues(self._prefix_records)
      File "/Users/ssalie/anaconda/lib/python2.7/site-packages/conda/core/prefix_data.py", line 162, in _prefix_records
        return self.__prefix_records or self.load() or self.__prefix_records
      File "/Users/ssalie/anaconda/lib/python2.7/site-packages/conda/common/io.py", line 88, in decorated
        return f(*args, **kwds)
      File "/Users/ssalie/anaconda/lib/python2.7/site-packages/conda/core/prefix_data.py", line 72, in load
        self._load_site_packages()
      File "/Users/ssalie/anaconda/lib/python2.7/site-packages/conda/core/prefix_data.py", line 277, in _load_site_packages
        python_record = read_python_record(self.prefix_path, af, python_pkg_record.version)
      File "/Users/ssalie/anaconda/lib/python2.7/site-packages/conda/gateways/disk/read.py", line 249, in read_python_record
        pydist = PythonDistribution.init(prefix_path, anchor_file, python_version)
      File "/Users/ssalie/anaconda/lib/python2.7/site-packages/conda/common/pkg_formats/python.py", line 91, in init
        return PythonEggInfoDistribution(anchor_full_path, python_version, sp_reference)
      File "/Users/ssalie/anaconda/lib/python2.7/site-packages/conda/common/pkg_formats/python.py", line 402, in __init__
        super(PythonEggInfoDistribution, self).__init__(anchor_full_path, python_version)
      File "/Users/ssalie/anaconda/lib/python2.7/site-packages/conda/common/pkg_formats/python.py", line 105, in __init__
        raise RuntimeError("Path not found: %s" % anchor_full_path)
    RuntimeError: Path not found: /Users/ssalie/anaconda/lib/python2.7/site-packages/Sphinx-1.3.5-py2.7.egg/EGG-INFO

`$ /Users/ssalie/anaconda/bin/conda list`

  environment variables:
                 CIO_TEST=<not set>
               CONDA_ROOT=/Users/ssalie/anaconda
                     PATH=/Users/ssalie/anaconda/bin:/Library/Frameworks/Python.framework/Versio
                          ns/2.7/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/sha
                          re/dotnet:/opt/X11/bin:/Library/Frameworks/Mono.framework/Versions/Cur
                          rent/Commands
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>

     active environment : None
       user config file : /Users/ssalie/.condarc
 populated config files : /Users/ssalie/.condarc
          conda version : 4.7.11
    conda-build version : 0+unknown
         python version : 2.7.3.final.0
       virtual packages :
       base environment : /Users/ssalie/anaconda  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/osx-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/osx-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/osx-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /Users/ssalie/anaconda/pkgs
                          /Users/ssalie/.conda/pkgs
       envs directories : /Users/ssalie/anaconda/envs
                          /Users/ssalie/.conda/envs
               platform : osx-64
             user-agent : conda/4.7.11 requests/2.18.4 CPython/2.7.3 Darwin/18.7.0 OSX/10.14.6
                UID:GID : 501:20
             netrc file : None
           offline mode : False


An unexpected error has occurred. Conda has prepared the above report.

If submitted, this report will be used by core maintainers to improve
future releases of conda.
Would you like conda to send this report to the core maintainers?

**Comment by coder606-ctrl** [comment]
I have the same issue, did you figure out how to fix it considering that this is a post from like 3 years ago

**Comment by bartread** [comment]
I had the same issue when following the instructions to use a Spotlight search to launch navigator. However, I'd installed Anaconda just for myself so I went to the Applications subfolder in my home folder and then double clicked Anaconda-Navigator.app to launch and it worked fine.
