### ISSUE TITLE
Problems installing anaconda for fedora linux

### ISSUE THREAD

**Issue by ydafalla** [ContinuumIO/anaconda-issues#11282]
Hello Everyone
I am trying to install Anaconda 3 in a Fedora linux operating system. I downloaded the Anaconda3-2019.07-Linux-x86_64.sh file from the anaconda website. 
I then typed bash Anaconda3-2019.07-Linux-x86_64.sh. 
I get the following error:

Traceback (most recent call last):
  File "concurrent/futures/process.py", line 175, in _process_worker
  File "conda.exe.py", line 45, in _extract
  File "site-packages/conda_package_handling/api.py", line 49, in extract
  File "site-packages/conda_package_handling/conda_fmt.py", line 52, in extract
  File "site-packages/conda_package_handling/conda_fmt.py", line 35, in _extract_component
  File "zipfile.py", line 1507, in extract
  File "zipfile.py", line 1579, in _extract_member
OSError: [Errno 122] Disk quota exceeded
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "conda.exe.py", line 56, in <module>
  File "concurrent/futures/_base.py", line 425, in result
  File "concurrent/futures/_base.py", line 384, in __get_result
OSError: [Errno 122] Disk quota exceeded
[23078] Failed to execute script conda.exe

How can i solve this issue?

Thanks

**Comment by mingwandroid** [comment]
> OSError: [Errno 122] Disk quota exceeded

You have run our of disk space. Closing.
