### ISSUE TITLE
Issue trying to open anaconda-navigator in linux?

### ISSUE THREAD

**Issue by ydafalla** [ContinuumIO/anaconda-issues#11288]
### Actual Behavior

I successfully installed anaconda and when i try running the anaconda-navigator i keep getting the following error:

Traceback (most recent call last):
  File "/home/anaconda3/lib/python3.7/site-packages/anaconda_navigator/api/anaconda_api.py", line 418, in _load_unsafe_channels
    new_worker.unsafe_channels = info['channels']
TypeError: byte indices must be integers or slices, not str
Traceback (most recent call last):
  File "/home/anaconda3/lib/python3.7/site-packages/anaconda_navigator/api/anaconda_api.py", line 423, in _conda_info_processed
    base_worker = worker.base_worker
AttributeError: 'ProcessWorker' object has no attribute 'base_worker'

### Expected Behavior

I expect the anaconda-navigator to start working normally.

### Steps to Reproduce

Type anaconda-navigator in the linux terminal

##### Operating System:
Fedora Linux
##### `conda info`

<details>

```
     active environment : base
    active env location : /home/anaconda3
            shell level : 1
       user config file : /users/yousif/.condarc
 populated config files : 
          conda version : 4.7.12
    conda-build version : 3.18.9
         python version : 3.7.4.final.0
       virtual packages : 
       base environment : /home/anaconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /home/anaconda3/pkgs
                          /users/yousif/.conda/pkgs
       envs directories : /home/anaconda3/envs
                          /users/yousif/.conda/envs
               platform : linux-64
             user-agent : conda/4.7.12 requests/2.22.0 CPython/3.7.4 Linux/4.17.7-200.fc28.x86_64 fedora/28 glibc/2.27
                UID:GID : 100522423:100522423
             netrc file : None
           offline mode : False


```

**Comment by tony-john-mcneil** [comment]
Same issue for me, same conda info.
On XUbuntu:
lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.3 LTS
Release:	18.04
Codename:	bionic

**Comment by dtlloyd** [comment]
I see something similar also with Ubuntu 18.04.3 LTS, however in my case the error crops up when trying to change environments in the anaconda navigator window and usually leads to the program needing to restarted.

**Comment by cunha17** [comment]
I'm experiencing the same issue with Fedora 30. The exactly same error message, the same steps to reproduce. Tried "conda update conda", "conda update --all", "conda activate root", "conda activate base" and also removing "~/.condarc". Also tried to open Anaconda Navigator as root. Nothing seems to change the error message. 

Have to say that I'm behind a corporate proxy/firewall, my environment variables are correctly set (http_proxy, https_proxy, ftp_proxty, ftps_proxt and no_proxy) and I tested "elinks https://api.anaconda.org" and it fetches the json correcly, so I don't think it's a problem with firewall/proxy. 

My **conda info --all** output:
```
     active environment : base
    active env location : /usr/anaconda3
            shell level : 1
       user config file : /home/cristiano.cunha/.condarc
 populated config files : 
          conda version : 4.8.2
    conda-build version : 3.18.11
         python version : 3.7.6.final.0
       virtual packages : __cuda=10.2
                          __glibc=2.29
       base environment : /usr/anaconda3  (read only)
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /usr/anaconda3/pkgs
                          /home/cristiano.cunha/.conda/pkgs
       envs directories : /home/cristiano.cunha/.conda/envs
                          /usr/anaconda3/envs
               platform : linux-64
             user-agent : conda/4.8.2 requests/2.22.0 CPython/3.7.6 Linux/5.4.17-100.fc30.x86_64 fedora/30 glibc/2.29
                UID:GID : 1000:1000
             netrc file : /home/cristiano.cunha/.netrc
           offline mode : False

# conda environments:
#
base                  *  /usr/anaconda3

sys.version: 3.7.6 (default, Jan  8 2020, 19:59:22) 
...
sys.prefix: /usr/anaconda3
sys.executable: /usr/anaconda3/bin/python
conda location: /usr/anaconda3/lib/python3.7/site-packages/conda
conda-build: /usr/anaconda3/bin/conda-build
conda-convert: /usr/anaconda3/bin/conda-convert
conda-debug: /usr/anaconda3/bin/conda-debug
conda-develop: /usr/anaconda3/bin/conda-develop
conda-env: /usr/anaconda3/bin/conda-env
conda-index: /usr/anaconda3/bin/conda-index
conda-inspect: /usr/anaconda3/bin/conda-inspect
conda-metapackage: /usr/anaconda3/bin/conda-metapackage
conda-render: /usr/anaconda3/bin/conda-render
conda-server: /usr/anaconda3/bin/conda-server
conda-skeleton: /usr/anaconda3/bin/conda-skeleton
conda-verify: /usr/anaconda3/bin/conda-verify
user site dirs: 

CIO_TEST: <not set>
CONDA_DEFAULT_ENV: base
CONDA_EXE: /usr/anaconda3/bin/conda
CONDA_PREFIX: /usr/anaconda3
CONDA_PROMPT_MODIFIER: (base) 
CONDA_PYTHON_EXE: /usr/anaconda3/bin/python
CONDA_ROOT: /usr/anaconda3
CONDA_SHLVL: 1
PATH: /usr/anaconda3/bin:/usr/anaconda3/bin:/usr/condabin:/usr/lib64/qt-3.3/bin:/usr/local/bin:/usr/bin:/bin:/usr/games:/usr/local/sbin:/usr/sbin:/home/cristiano.cunha/.composer/vendor/bin:/home/cristiano.cunha/.local/bin:/home/cristiano.cunha/bin
REQUESTS_CA_BUNDLE: <not set>
SSL_CERT_FILE: <not set>
WINDOWPATH: 1
ftp_proxy: <set>
ftps_proxy: <set>
http_proxy: <set>
https_proxy: <set>
no_proxy: <set>
```

**Comment by chubaek** [comment]
I also have the same issue. Does anyone had a solution?
