### ISSUE TITLE
intel-openmp=2019.5 causes crash in multiprocessing workers: OMP: Error #13: Assertion failure at z_Linux_util.cpp(2361)

### ISSUE THREAD

**Issue by ogrisel** [ContinuumIO/anaconda-issues#11294]
### Steps to Reproduce

In a Linux shell:

```
$ conda create -n ompcrash numpy mkl intel-openmp=2019.5
$ conda activate ompcrash
```

Then run the following program (saved as `/tmp/mkl_fork_execv.py`):

```python
import numpy as np
import multiprocessing as mp

a = np.random.randn(100, 100)
np.dot(a, a)  # no problem


if __name__ == "__main__":
    p = mp.get_context("spawn").Process(target=np.dot, args=(a, a))
    p.start()
    p.join()
    print("ok")
```

### Actual Behavior

The multiprocessing worker process crashes with:

```
$ python /tmp/mkl_fork_execv.py 
OMP: Error #13: Assertion failure at z_Linux_util.cpp(2361).
OMP: Hint Please submit a bug report with this message, compile and run commands used, and machine configuration info including native compiler and operating system versions. Faster response will be obtained by including all program sources. For information on submitting this issue, please see http://www.intel.com/software/products/support/.
```

### Expected Behavior

I expected the program to print "ok" on stdout and exit 0.

This expected behavior used to work with previous versions of intel-openmp. For instance:

```
$ conda install -y intel-openmp=2019.4
[...]
The following packages will be DOWNGRADED:

  intel-openmp                                   2019.5-281 --> 2019.4-243

Preparing transaction: done
Verifying transaction: done
Executing transaction: done
$ python /tmp/mkl_fork_execv.py 
ok
```

##### Anaconda or Miniconda version:

Miniconda 3 with conda 4.7.12.

##### `conda info`

<details>

```
$ conda info

     active environment : numpy-mkl
    active env location : /home/ogrisel/miniconda3/envs/ompcrash
            shell level : 1
       user config file : /home/ogrisel/.condarc
 populated config files : /home/ogrisel/.condarc
          conda version : 4.7.12
    conda-build version : not installed
         python version : 3.7.3.final.0
       virtual packages : 
       base environment : /home/ogrisel/miniconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /home/ogrisel/miniconda3/pkgs
                          /home/ogrisel/.conda/pkgs
       envs directories : /home/ogrisel/miniconda3/envs
                          /home/ogrisel/.conda/envs
               platform : linux-64
             user-agent : conda/4.7.12 requests/2.22.0 CPython/3.7.3 Linux/5.0.0-27-generic ubuntu/18.04.3 glibc/2.27
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False

```

</details>

##### `conda list --show-channel-urls`

<details>

```
$ conda list --show-channel-urls
# packages in environment at /home/ogrisel/miniconda3/envs/ompcrash:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main    defaults
backcall                  0.1.0                    py37_0    defaults
blas                      1.0                         mkl    defaults
ca-certificates           2019.5.15                     1    defaults
certifi                   2019.6.16                py37_1    defaults
decorator                 4.4.0                    py37_1    defaults
intel-openmp              2019.5                      281    defaults
ipython                   7.8.0            py37h39e3cac_0    defaults
ipython_genutils          0.2.0                    py37_0    defaults
jedi                      0.15.1                   py37_0    defaults
libedit                   3.1.20181209         hc058e9b_0    defaults
libffi                    3.2.1                hd88cf55_4    defaults
libgcc-ng                 9.1.0                hdf63c60_0    defaults
libgfortran-ng            7.3.0                hdf63c60_0    defaults
libstdcxx-ng              9.1.0                hdf63c60_0    defaults
mkl                       2019.5                      281    defaults
mkl-service               2.3.0            py37he904b0f_0    defaults
mkl_fft                   1.0.14           py37ha843d7b_0    defaults
mkl_random                1.0.2            py37hd81dba3_0    defaults
ncurses                   6.1                  he6710b0_1    defaults
numpy                     1.16.5           py37h7e9f1db_0    defaults
numpy-base                1.16.5           py37hde5b4d6_0    defaults
openssl                   1.1.1d               h7b6447c_1    defaults
parso                     0.5.1                      py_0    defaults
pexpect                   4.7.0                    py37_0    defaults
pickleshare               0.7.5                    py37_0    defaults
pip                       19.2.2                   py37_0    defaults
prompt_toolkit            2.0.9                    py37_0    defaults
ptyprocess                0.6.0                    py37_0    defaults
pygments                  2.4.2                      py_0    defaults
python                    3.7.4                h265db76_1    defaults
readline                  7.0                  h7b6447c_5    defaults
setuptools                41.0.1                   py37_0    defaults
six                       1.12.0                   py37_0    defaults
sqlite                    3.29.0               h7b6447c_0    defaults
tk                        8.6.8                hbc83047_0    defaults
traitlets                 4.3.2                    py37_0    defaults
wcwidth                   0.1.7                    py37_0    defaults
wheel                     0.33.4                   py37_0    defaults
xz                        5.2.4                h14c3975_4    defaults
zlib                      1.2.11               h7b6447c_3    defaults


```

</details>

**Comment by ogrisel** [comment]
The above steps to reproduce provide a minimal reproduction case that only depends on numpy and multiprocessing.

But it's also causing crashes in scikit-learn 0.21.2 from the "defaults" channel. For instance:

```
$ python -c "from sklearn.cluster import KMeans; import numpy as np; KMeans(n_clusters=30, n_jobs=2).fit(np.random.randn(10000, 30))"
OMP: Error #13: Assertion failure at z_Linux_util.cpp(2361).
OMP: Hint Please submit a bug report with this message, compile and run commands used, and machine configuration info including native compiler and operating system versions. Faster response will be obtained by including all program sources. For information on submitting this issue, please see http://www.intel.com/software/products/support/.
OMP: Error #13: Assertion failure at z_Linux_util.cpp(2361).
OMP: Hint Please submit a bug report with this message, compile and run commands used, and machine configuration info including native compiler and operating system versions. Faster response will be obtained by including all program sources. For information on submitting this issue, please see http://www.intel.com/software/products/support/.
exception calling callback for <Future at 0x7f75c5ca2850 state=finished raised TerminatedWorkerError>
Traceback (most recent call last):
  File "/home/ogrisel/miniconda3/envs/ompcrash/lib/python3.7/site-packages/joblib/externals/loky/_base.py", line 625, in _invoke_callbacks
    callback(self)
  File "/home/ogrisel/miniconda3/envs/ompcrash/lib/python3.7/site-packages/joblib/parallel.py", line 309, in __call__
    self.parallel.dispatch_next()
  File "/home/ogrisel/miniconda3/envs/ompcrash/lib/python3.7/site-packages/joblib/parallel.py", line 731, in dispatch_next
    if not self.dispatch_one_batch(self._original_iterator):
  File "/home/ogrisel/miniconda3/envs/ompcrash/lib/python3.7/site-packages/joblib/parallel.py", line 759, in dispatch_one_batch
    self._dispatch(tasks)
  File "/home/ogrisel/miniconda3/envs/ompcrash/lib/python3.7/site-packages/joblib/parallel.py", line 716, in _dispatch
    job = self._backend.apply_async(batch, callback=cb)
  File "/home/ogrisel/miniconda3/envs/ompcrash/lib/python3.7/site-packages/joblib/_parallel_backends.py", line 510, in apply_async
    future = self._workers.submit(SafeFunction(func))
  File "/home/ogrisel/miniconda3/envs/ompcrash/lib/python3.7/site-packages/joblib/externals/loky/reusable_executor.py", line 151, in submit
    fn, *args, **kwargs)
  File "/home/ogrisel/miniconda3/envs/ompcrash/lib/python3.7/site-packages/joblib/externals/loky/process_executor.py", line 1022, in submit
    raise self._flags.broken
joblib.externals.loky.process_executor.TerminatedWorkerError: A worker process managed by the executor was unexpectedly terminated. This could be caused by a segmentation fault while calling the function or by an excessive memory usage causing the Operating System to kill the worker. The exit codes of the workers are {SIGABRT(-6)}
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/ogrisel/code/scikit-learn/sklearn/cluster/k_means_.py", line 953, in fit
    for seed in seeds)
  File "/home/ogrisel/miniconda3/envs/ompcrash/lib/python3.7/site-packages/joblib/parallel.py", line 934, in __call__
    self.retrieve()
  File "/home/ogrisel/miniconda3/envs/ompcrash/lib/python3.7/site-packages/joblib/parallel.py", line 833, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "/home/ogrisel/miniconda3/envs/ompcrash/lib/python3.7/site-packages/joblib/_parallel_backends.py", line 521, in wrap_future_result
    return future.result(timeout=timeout)
  File "/home/ogrisel/miniconda3/envs/ompcrash/lib/python3.7/concurrent/futures/_base.py", line 435, in result
    return self.__get_result()
  File "/home/ogrisel/miniconda3/envs/ompcrash/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/home/ogrisel/miniconda3/envs/ompcrash/lib/python3.7/site-packages/joblib/externals/loky/_base.py", line 625, in _invoke_callbacks
    callback(self)
  File "/home/ogrisel/miniconda3/envs/ompcrash/lib/python3.7/site-packages/joblib/parallel.py", line 309, in __call__
    self.parallel.dispatch_next()
  File "/home/ogrisel/miniconda3/envs/ompcrash/lib/python3.7/site-packages/joblib/parallel.py", line 731, in dispatch_next
    if not self.dispatch_one_batch(self._original_iterator):
  File "/home/ogrisel/miniconda3/envs/ompcrash/lib/python3.7/site-packages/joblib/parallel.py", line 759, in dispatch_one_batch
    self._dispatch(tasks)
  File "/home/ogrisel/miniconda3/envs/ompcrash/lib/python3.7/site-packages/joblib/parallel.py", line 716, in _dispatch
    job = self._backend.apply_async(batch, callback=cb)
  File "/home/ogrisel/miniconda3/envs/ompcrash/lib/python3.7/site-packages/joblib/_parallel_backends.py", line 510, in apply_async
    future = self._workers.submit(SafeFunction(func))
  File "/home/ogrisel/miniconda3/envs/ompcrash/lib/python3.7/site-packages/joblib/externals/loky/reusable_executor.py", line 151, in submit
    fn, *args, **kwargs)
  File "/home/ogrisel/miniconda3/envs/ompcrash/lib/python3.7/site-packages/joblib/externals/loky/process_executor.py", line 1022, in submit
    raise self._flags.broken
joblib.externals.loky.process_executor.TerminatedWorkerError: A worker process managed by the executor was unexpectedly terminated. This could be caused by a segmentation fault while calling the function or by an excessive memory usage causing the Operating System to kill the worker. The exit codes of the workers are {SIGABRT(-6)}
```

While the same code used to work with `intel-openmp=2019.4`.

**Comment by msarahan** [comment]
Thanks for the report. We'll follow up with Intel ASAP and probably pull the package in the meantime.

**Comment by oleksandr-pavlyk** [comment]
@ogrisel As a temporary work-around, please set `KMP_INIT_AT_FORK=FALSE`:

```
(openmpcrash) [08:42:14 vmlin openmpcrash]$ cat mkl_fork_execv.py
import numpy as np
import multiprocessing as mp

a = np.random.randn(100, 100)
np.dot(a, a)  # no problem

if __name__ == "__main__":
    p = mp.get_context("spawn").Process(target=np.dot, args=(a, a))
    p.start()
    p.join()
    print("ok")
(openmpcrash) [08:42:18 vmlin openmpcrash]$ KMP_INIT_AT_FORK=FALSE python mkl_fork_execv.py
ok
```

**Comment by ogrisel** [comment]
Thanks very much @oleksandr-pavlyk !

**Comment by ogrisel** [comment]
Any update on this? We would like to make a new release of joblib on Monday or Tuesday next week and we would like to know if we will need to ship the workaround as part of this release but we would rather not include the workaround in the release if the issue is likely to be fixed in the short term.

**Comment by dgasmith** [comment]
This is effecting us as well. Adding a `intel-openmp!=2019.5` for now.

**Comment by oleksandr-pavlyk** [comment]
The OpenMP team has confirmed that setting `KMP_INIT_AT_FORK=FALSE` is the only available work-around. It is unlikely that the fix will be released during the course of the next two weeks, so I am afraid it is best to ship the workaround as part of joblib's release. Sorry about that.

**Comment by dgasmith** [comment]
Agreed, just echoing that this is effecting us in a completely unrelated project. I do think this package should be pulled ASAP.

**Comment by msarahan** [comment]
These packages have been pulled until we can come up with a seamless workaround or fix.
