### ISSUE TITLE
Navigator Error (after rebuilding Win 10 User profile?)

### ISSUE THREAD

**Issue by ottadini** [ContinuumIO/anaconda-issues#11309]
### Actual Behavior

Start Anaconda Navigator from Windows Start menu. Eventually the process fails and opens a browser with the following traceback:

```
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\anaconda_navigator\exceptions.py", line 75, in exception_handler
    return_value = func(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 151, in start_app
    window = run_app(splash)
  File "C:\ProgramData\Anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 65, in run_app
    window = MainWindow(splash=splash, tab_project=False)
  File "C:\ProgramData\Anaconda3\lib\site-packages\anaconda_navigator\widgets\main_window.py", line 168, in __init__
    self.api = AnacondaAPI()
  File "C:\ProgramData\Anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 2337, in AnacondaAPI
    ANACONDA_API = _AnacondaAPI()
  File "C:\ProgramData\Anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 89, in __init__
    self._conda_api = CondaAPI()
  File "C:\ProgramData\Anaconda3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 1773, in CondaAPI
    CONDA_API = _CondaAPI()
  File "C:\ProgramData\Anaconda3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 353, in __init__
    self.sys_rc_path = join(self.ROOT_PREFIX, '.condarc')
  File "C:\ProgramData\Anaconda3\lib\ntpath.py", line 76, in join
    path = os.fspath(path)
TypeError: expected str, bytes or os.PathLike object, not NoneType

```

### Expected Behavior

Anaconda Navigator loads and displays.

### Steps to Reproduce

Delete Windows User profile, and recreate bylogin. 

##### Anaconda or Miniconda version:

Anaconda3 5.2.0 64-bit.

##### Operating System:

Windows 10.

##### `conda info`

<details>

Fails with:

```

>conda info

InvalidTypeError: Parameter proxy_servers = {} declared in <<merged>> has type <class 'dict'>.
Valid types:
  - <class 'conda._vendor.frozendict.frozendict'>


```

</details>

##### `conda list --show-channel-urls`

<details>

```
>conda list --show-channel-urls
# packages in environment at C:\ProgramData\Anaconda3:
#
# Name                    Version                   Build  Channel
_ipyw_jlab_nb_ext_conf    0.1.0            py36he6757f0_0    defaults
alabaster                 0.7.12                     py_0    conda-forge
anaconda-client           1.7.2                      py_0    conda-forge
anaconda-navigator        1.9.7                    py36_0    defaults
asn1crypto                0.24.0                py36_1003    conda-forge
astroid                   1.6.5                    py36_0    conda-forge
attrs                     19.1.0                     py_0    conda-forge
babel                     2.5.3                    py36_0    defaults
backcall                  0.1.0                      py_0    conda-forge
beautifulsoup4            4.8.0                    py36_0    conda-forge
bleach                    3.1.0                      py_0    conda-forge
ca-certificates           2019.9.11            hecc5488_0    conda-forge
certifi                   2019.9.11                py36_0    conda-forge
cffi                      1.12.3           py36hb32ad35_0    conda-forge
chardet                   3.0.4                 py36_1003    conda-forge
click                     7.0                        py_0    conda-forge
cloudpickle               1.2.2                      py_0    conda-forge
clyent                    1.2.2                      py_1    conda-forge
colorama                  0.4.1                      py_0    conda-forge
comtypes                  1.1.4                    py36_0    defaults
conda                     4.7.12                   py36_0    conda-forge
conda-build               3.10.5                   py36_0    defaults
conda-package-handling    1.6.0            py36h2fa13f4_0    conda-forge
conda-verify              3.1.1                 py36_1000    conda-forge
console_shortcut          0.1.1                h6bb2dd7_3    defaults
coverage                  4.5.1            py36hfa6e2cd_0    defaults
cryptography              2.7              py36hb32ad35_0    conda-forge
decorator                 4.4.0                      py_0    conda-forge
defusedxml                0.5.0                      py_1    conda-forge
docutils                  0.15.2                   py36_0    conda-forge
entrypoints               0.3                   py36_1000    conda-forge
filelock                  3.0.10                     py_0    conda-forge
freetype                  2.8.1                ha63716d_1    conda-forge
future                    0.17.1                py36_1000    conda-forge
glob2                     0.7                        py_0    conda-forge
gsapy                     0.9.6                    pypi_0    pypi
icu                       64.2                 he025d50_1    conda-forge
idna                      2.8                   py36_1000    conda-forge
imagesize                 1.1.0                      py_0    conda-forge
intel-openmp              2019.4                      245    defaults
ipydatawidgets            4.0.1                      py_0    conda-forge
ipykernel                 5.1.2            py36h5ca1d4c_0    conda-forge
ipyscales                 0.3.0                      py_0    conda-forge
ipython                   7.8.0            py36h5ca1d4c_0    conda-forge
ipython_genutils          0.2.0                      py_1    conda-forge
ipywidgets                7.5.1                      py_0    conda-forge
isort                     4.3.21                   py36_0    conda-forge
jedi                      0.15.1                   py36_0    conda-forge
jinja2                    2.10.1                     py_0    conda-forge
jpeg                      9c                hfa6e2cd_1001    conda-forge
json5                     0.8.5                      py_0    conda-forge
jsonschema                3.0.2                    py36_0    conda-forge
jupyter_client            5.3.3                    py36_1    conda-forge
jupyter_core              4.4.0                      py_0    conda-forge
jupyterlab                1.1.3                      py_0    conda-forge
jupyterlab_server         1.0.6                      py_0    conda-forge
keyring                   19.2.0                   py36_0    conda-forge
lazy-object-proxy         1.4.2            py36hfa6e2cd_0    conda-forge
libblas                   3.8.0                    12_mkl    conda-forge
libcblas                  3.8.0                    12_mkl    conda-forge
liblapack                 3.8.0                    12_mkl    conda-forge
libpng                    1.6.37               h7602738_0    conda-forge
libsodium                 1.0.17               h2fa13f4_0    conda-forge
libtiff                   4.0.10            h6512ee2_1003    conda-forge
lz4-c                     1.8.3             he025d50_1001    conda-forge
m2w64-gcc-libgfortran     5.3.0                         6    defaults
m2w64-gcc-libs            5.3.0                         7    defaults
m2w64-gcc-libs-core       5.3.0                         7    defaults
m2w64-gmp                 6.1.0                         2    defaults
m2w64-libwinpthread-git   5.0.0.4634.697f757               2    defaults
markupsafe                1.1.1            py36hfa6e2cd_0    conda-forge
mccabe                    0.6.1                      py_1    conda-forge
menuinst                  1.4.16                   py36_0    conda-forge
mistune                   0.8.4           py36hfa6e2cd_1000    conda-forge
mkl                       2019.4                      245    defaults
mock                      2.0.0            py36h9086845_0    defaults
msgpack                   0.5.6                    pypi_0    pypi
msys2-conda-epoch         20160418                      1    defaults
mypy                      0.620                    py36_0    defaults
navigator-updater         0.2.1                    py36_0    defaults
nbconvert                 5.6.0                    py36_1    conda-forge
nbformat                  4.4.0                      py_1    conda-forge
nodejs                    8.9.3                hd6b2f15_0    defaults
notebook                  6.0.1                    py36_0    conda-forge
numpy                     1.17.2           py36hc71023c_0    conda-forge
numpydoc                  0.9.1                      py_0    conda-forge
olefile                   0.46                       py_0    conda-forge
openssl                   1.1.1c               hfa6e2cd_0    conda-forge
packaging                 19.2                       py_0    conda-forge
pandoc                    2.7.3                         0    conda-forge
pandocfilters             1.4.2                      py_1    conda-forge
parso                     0.5.1                      py_0    conda-forge
pbr                       5.4.2                      py_0    conda-forge
pickleshare               0.7.5                 py36_1000    conda-forge
pillow                    5.1.0            py36h0738816_0    defaults
pint                      0.8.1                      py_1    conda-forge
pip                       19.0.1                   pypi_0    pypi
pkginfo                   1.5.0.1                    py_0    conda-forge
prometheus_client         0.7.1                      py_0    conda-forge
prompt_toolkit            2.0.9                      py_0    conda-forge
psutil                    5.4.8           py36hfa6e2cd_1000    conda-forge
pyautogui                 0.9.38                   py36_0    conda-forge
pycodestyle               2.5.0                      py_0    conda-forge
pycosat                   0.6.3           py36hfa6e2cd_1001    conda-forge
pycparser                 2.19                     py36_1    conda-forge
pyflakes                  2.1.1                      py_0    conda-forge
pygments                  2.4.2                      py_0    conda-forge
pylint                    1.8.4                    py36_0    conda-forge
pymsgbox                  1.0.7                      py_0    conda-forge
pyopenssl                 19.0.0                   py36_0    conda-forge
pyparsing                 2.4.2                      py_0    conda-forge
pyqt                      5.9.2            py36h6538335_4    conda-forge
pyrsistent                0.15.4           py36hfa6e2cd_0    conda-forge
pyscreeze                 0.1.22                     py_0    conda-forge
pysocks                   1.7.1                    py36_0    conda-forge
python                    3.6.5                h0c2934d_0    defaults
python-dateutil           2.8.0                      py_0    conda-forge
pythreejs                 1.1.0                    py36_3    conda-forge
pytweening                1.0.3                      py_0    conda-forge
pytz                      2019.2                     py_0    conda-forge
pywin32                   224             py36hfa6e2cd_1000    conda-forge
pywin32-ctypes            0.2.0                 py36_1000    conda-forge
pywinauto                 0.6.5                    pypi_0    pypi
pywinpty                  0.5.5                 py36_1000    conda-forge
pyyaml                    5.1.2            py36hfa6e2cd_0    conda-forge
pyzmq                     18.1.0           py36h16f9016_0    conda-forge
qt                        5.9.7                h506e8af_3    conda-forge
qtawesome                 0.6.0                      py_0    conda-forge
qtconsole                 4.5.5                      py_0    conda-forge
qtpy                      1.9.0                      py_0    conda-forge
requests                  2.22.0                   py36_1    conda-forge
rope                      0.14.0                     py_0    conda-forge
ruamel_yaml               0.15.71         py36hfa6e2cd_1000    conda-forge
send2trash                1.5.0                      py_0    conda-forge
setuptools                41.2.0                   py36_0    conda-forge
sip                       4.19.8          py36h6538335_1000    conda-forge
six                       1.11.0           py36h4db2310_1    defaults
snowballstemmer           1.9.1                      py_0    conda-forge
soupsieve                 1.9.3                    py36_0    conda-forge
sphinx                    1.7.4                    py36_0    defaults
sphinxcontrib-websupport  1.1.2                      py_0    conda-forge
spyder                    3.3.6                    py36_0    conda-forge
spyder-kernels            0.5.2                    py36_0    conda-forge
sqlite                    3.29.0               hfa6e2cd_1    conda-forge
terminado                 0.8.2                    py36_0    conda-forge
testpath                  0.4.2                   py_1001    conda-forge
tk                        8.6.9             hfa6e2cd_1003    conda-forge
tornado                   6.0.3            py36hfa6e2cd_0    conda-forge
tqdm                      4.36.1                     py_0    conda-forge
traitlets                 4.3.2                 py36_1000    conda-forge
traittypes                0.2.1                      py_1    conda-forge
typed-ast                 1.1.1           py36hfa6e2cd_1000    conda-forge
typing                    3.6.4                    py36_0    conda-forge
urllib3                   1.25.6                   py36_0    conda-forge
vc                        14.1                 h0510ff6_4    defaults
vs2015_runtime            14.16.27012          hf0eaf9b_0    defaults
wcwidth                   0.1.7                      py_1    conda-forge
webencodings              0.5.1                      py_1    conda-forge
wheel                     0.33.6                   py36_0    conda-forge
widgetsnbextension        3.5.1                    py36_0    conda-forge
win_inet_pton             1.1.0                    py36_0    conda-forge
wincertstore              0.2                   py36_1002    conda-forge
winpty                    0.4.3                         4    conda-forge
wrapt                     1.11.2           py36hfa6e2cd_0    conda-forge
xmltodict                 0.11.0                     py_1    conda-forge
xz                        5.2.4             h2fa13f4_1001    conda-forge
yaml                      0.1.7             hfa6e2cd_1001    conda-forge
zeromq                    4.3.2                h6538335_2    conda-forge
zlib                      1.2.11            h2fa13f4_1006    conda-forge
zstd                      1.4.0                hd8a0e53_0    conda-forge

```

</details>

**Comment by csoja** [comment]
Looks like your conda configuration file (.condarc) has gotten corrupted.  I'd recommend deleting it and restarting Navigator.
