### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by JanOdijk** [ContinuumIO/anaconda-issues#11303]
## Main error
Application <b>spyder</b> launch may have produced errors.
## Traceback
```
Traceback (most recent call last):
  File "C:\Users\Odijk101\AppData\Local\Continuum\Anaconda3\Scripts\spyder-script.py", line 5, in <module>
    sys.exit(spyder.app.start.main())
  File "C:\Users\Odijk101\AppData\Local\Continuum\Anaconda3\lib\site-packages\spyder\app\start.py", line 103, in main
    from spyder.app import mainwindow
  File "C:\Users\Odijk101\AppData\Local\Continuum\Anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 92, in <module>
    from qtpy import QtWebEngineWidgets  # analysis:ignore
  File "C:\Users\Odijk101\AppData\Local\Continuum\Anaconda3\lib\site-packages\qtpy\QtWebEngineWidgets.py", line 22, in <module>
    from PyQt5.QtWebEngineWidgets import QWebEnginePage
ValueError: PyCapsule_GetPointer called with incorrect name

```
## System information
```
python: 3.6.6
language: nl_NL
os: Windows;10;10.0.15063;AMD64;Intel64 Family 6 Model 78 Stepping 3, GenuineIntel
version: 1.6.2
platform: win-64
qt: 5.12.3
pyqt: 5.9.2
conda: 4.5.12
```

**Comment by csoja** [comment]
I'm not sure what is causing your error. However, it looks like you are running very old software. I'd recommend updating conda and anaconda-navigator and spyder. I'm going to close this - please open a new issue if you are still having problems with the latest Spyder, conda, and Anaconda-Navigator.
