### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by glennmagerman** [ContinuumIO/anaconda-issues#11311]
Main Error

'message'
Traceback

Traceback (most recent call last):
  File "/Users/glenn/anaconda/lib/python3.6/site-packages/anaconda_navigator/exceptions.py", line 75, in exception_handler
    return_value = func(*args, **kwargs)
  File "/Users/glenn/anaconda/lib/python3.6/site-packages/anaconda_navigator/app/start.py", line 120, in start_app
    window = run_app(splash)
  File "/Users/glenn/anaconda/lib/python3.6/site-packages/anaconda_navigator/app/start.py", line 63, in run_app
    window = MainWindow(splash=splash)
  File "/Users/glenn/anaconda/lib/python3.6/site-packages/anaconda_navigator/widgets/main_window.py", line 160, in __init__
    self.api = AnacondaAPI()
  File "/Users/glenn/anaconda/lib/python3.6/site-packages/anaconda_navigator/api/anaconda_api.py", line 1214, in AnacondaAPI
    ANACONDA_API = _AnacondaAPI()
  File "/Users/glenn/anaconda/lib/python3.6/site-packages/anaconda_navigator/api/anaconda_api.py", line 65, in __init__
    self._conda_api = CondaAPI()
  File "/Users/glenn/anaconda/lib/python3.6/site-packages/anaconda_navigator/api/conda_api.py", line 1654, in CondaAPI
    CONDA_API = _CondaAPI()
  File "/Users/glenn/anaconda/lib/python3.6/site-packages/anaconda_navigator/api/conda_api.py", line 345, in __init__
    self.set_conda_prefix()
  File "/Users/glenn/anaconda/lib/python3.6/site-packages/anaconda_navigator/api/conda_api.py", line 493, in set_conda_prefix
    info = worker.communicate()[0]
  File "/Users/glenn/anaconda/lib/python3.6/site-packages/anaconda_navigator/api/conda_api.py", line 271, in communicate
    " ".join(self._cmd_list), result[0]['message']
KeyError: 'message'

System information:
MacBook Pro 2016, 3.3 GHz i7, 16GB Ram, OS Mojave
Launcher: Anaconda-Navigator

**Comment by csoja** [comment]
Do the suggestions in this Troubleshooting documentation help? https://docs.anaconda.com/anaconda/navigator/troubleshooting/#navigator-error-on-start-up
