### ISSUE TITLE
Navigator error in anaconda navigator

### ISSUE THREAD

**Issue by sandaruwani** [ContinuumIO/anaconda-issues#11317]
### Actual Behavior

Navigator Error
An unexpected error occurred on Navigator start-up
Main Error
expected str, bytes or os.PathLike object, not NoneType
Traceback
Traceback (most recent call last):
File "C:\Users\anmol singh\Anaconda3\lib\site-packages\anaconda_navigator\exceptions.py", line 75, in exception_handler
return_value = func(*args, **kwargs)
File "C:\Users\anmol singh\Anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 150, in start_app
window = run_app(splash)
File "C:\Users\anmol singh\Anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 65, in run_app
window = MainWindow(splash=splash, tab_project=False)
File "C:\Users\anmol singh\Anaconda3\lib\site-packages\anaconda_navigator\widgets\main_window.py", line 163, in init
self.api = AnacondaAPI()
File "C:\Users\anmol singh\Anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 2185, in AnacondaAPI
ANACONDA_API = _AnacondaAPI()
File "C:\Users\anmol singh\Anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 89, in init
self._conda_api = CondaAPI()
File "C:\Users\anmol singh\Anaconda3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 1714, in CondaAPI
CONDA_API = _CondaAPI()
File "C:\Users\anmol singh\Anaconda3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 353, in init
self.sys_rc_path = join(self.ROOT_PREFIX, '.condarc')
File "C:\Users\anmol singh\Anaconda3\lib\ntpath.py", line 76, in join
path = os.fspath(path)
TypeError: expected str, bytes or os.PathLike object, not NoneType
-->

### Expected Behavior

shoud open anaconda

##### `conda info`

<details>

```
PASTE OUTPUT HERE:

```

</details>

##### `conda list --show-channel-urls`

<details>

```
PASTE OUTPUT HERE:

```

</details>

**Comment by csoja** [comment]
@sandaruwani Looks like your conda configuration file has gotten corrupted.  I'd recommend removing it.  I think you'll find it here "C:\Users\anmol singh\Anaconda3\\.condarc"
