### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by NateZimmer** [ContinuumIO/anaconda-issues#11310]
## Main error
Application <b>notebook</b> launch may have produced errors.
## Traceback
```
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\Scripts\jupyter-notebook-script.py", line 6, in <module>
    from notebook.notebookapp import main
  File "C:\ProgramData\Anaconda3\lib\site-packages\notebook\notebookapp.py", line 40, in <module>
    ioloop.install()
  File "C:\ProgramData\Anaconda3\lib\site-packages\zmq\eventloop\ioloop.py", line 210, in install
    assert (not ioloop.IOLoop.initialized()) or \
AttributeError: type object 'IOLoop' has no attribute 'initialized'

```
## System information
```
python: 3.6.3
language: en_US
os: Windows;10;10.0.18362;AMD64;Intel64 Family 6 Model 26 Stepping 4, GenuineIntel
version: 1.6.2
platform: win-64
qt: 5.6.2
pyqt: 5.6.0
conda: 4.3.30
```

**Comment by csoja** [comment]
I'm not sure what is causing your error. However, it looks like you are running very old software. I'd recommend updating conda and anaconda-navigator and Jupyter. I'm going to close this - please open a new issue if you are still having problems with the latest Jupyter, conda, and Anaconda-Navigator.
