### ISSUE TITLE
anaconda promt and navigator not working

### ISSUE THREAD

**Issue by benjaminbitanihirwe** [ContinuumIO/anaconda-issues#11318]
### Actual Behavior

evry time i run anaconda prompt from the window start menu it generates an error. while the navigator app also does not work. it open in browser with an error message. after uninstalling and re instlling i get the same error

##### Anaconda or Miniconda version:
anaconda

##### Operating System:
windows 10
##### `conda info`

<details>

```

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "C:\Users\Pearl\Anaconda3\lib\site-packages\conda\exceptions.py", line 789, in __call__
        return func(*args, **kwargs)
      File "C:\Users\Pearl\Anaconda3\lib\site-packages\conda\cli\main.py", line 74, in _main
        context.__init__(argparse_args=args)
      File "C:\Users\Pearl\Anaconda3\lib\site-packages\conda\base\context.py", line 234, in __init__
        argparse_args=argparse_args)
      File "C:\Users\Pearl\Anaconda3\lib\site-packages\conda\common\configuration.py", line 723, in __init__
        self._set_search_path(search_path)
      File "C:\Users\Pearl\Anaconda3\lib\site-packages\conda\common\configuration.py", line 729, in _set_search_path
        self._set_raw_data(load_file_configs(search_path))
      File "C:\Users\Pearl\Anaconda3\lib\site-packages\conda\common\configuration.py", line 371, in load_file_configs
        raw_data = odict(kv for kv in chain.from_iterable(load_paths))
      File "C:\Users\Pearl\Anaconda3\lib\site-packages\conda\common\configuration.py", line 371, in <genexpr>
        raw_data = odict(kv for kv in chain.from_iterable(load_paths))
      File "C:\Users\Pearl\Anaconda3\lib\site-packages\conda\common\configuration.py", line 346, in _file_yaml_loader
        yield fullpath, YamlRawParameter.make_raw_parameters_from_file(fullpath)
      File "C:\Users\Pearl\Anaconda3\lib\site-packages\conda\common\configuration.py", line 334, in make_raw_parameters_from_file
        ruamel_yaml = yaml_load(fh)
      File "C:\Users\Pearl\Anaconda3\lib\site-packages\conda\common\serialize.py", line 54, in yaml_load
        return yaml.load(string, Loader=yaml.RoundTripLoader, version="1.2")
      File "C:\Users\Pearl\Anaconda3\lib\site-packages\ruamel_yaml\main.py", line 637, in load
        loader = Loader(stream, version, preserve_quotes=preserve_quotes)
      File "C:\Users\Pearl\Anaconda3\lib\site-packages\ruamel_yaml\loader.py", line 59, in __init__
        Reader.__init__(self, stream, loader=self)
      File "C:\Users\Pearl\Anaconda3\lib\site-packages\ruamel_yaml\reader.py", line 80, in __init__
        self.stream = stream  # type: Any  # as .read is called
      File "C:\Users\Pearl\Anaconda3\lib\site-packages\ruamel_yaml\reader.py", line 125, in stream
        self.determine_encoding()
      File "C:\Users\Pearl\Anaconda3\lib\site-packages\ruamel_yaml\reader.py", line 180, in determine_encoding
        self.update(1)
      File "C:\Users\Pearl\Anaconda3\lib\site-packages\ruamel_yaml\reader.py", line 241, in update
        self.check_printable(data)
      File "C:\Users\Pearl\Anaconda3\lib\site-packages\ruamel_yaml\reader.py", line 208, in check_printable
        'unicode', "special characters are not allowed")
    ruamel_yaml.reader.ReaderError: unacceptable character #x0000: special characters are not allowed
      in "C:\Users\Pearl\.condarc", position 0

`$ C:\Users\Pearl\Anaconda3\Scripts\conda info`


An unexpected error has occurred. Conda has prepared the above report.
If submitted, this report will be used by core maintainers to improve
future releases of conda.
Would you like conda to send this report to the core maintainers?

```

</details>

##### `conda list --show-channel-urls`

<details>

```

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "C:\Users\Pearl\Anaconda3\lib\site-packages\conda\exceptions.py", line 789, in __call__
        return func(*args, **kwargs)
      File "C:\Users\Pearl\Anaconda3\lib\site-packages\conda\cli\main.py", line 74, in _main
        context.__init__(argparse_args=args)
      File "C:\Users\Pearl\Anaconda3\lib\site-packages\conda\base\context.py", line 234, in __init__
        argparse_args=argparse_args)
      File "C:\Users\Pearl\Anaconda3\lib\site-packages\conda\common\configuration.py", line 723, in __init__
        self._set_search_path(search_path)
      File "C:\Users\Pearl\Anaconda3\lib\site-packages\conda\common\configuration.py", line 729, in _set_search_path
        self._set_raw_data(load_file_configs(search_path))
      File "C:\Users\Pearl\Anaconda3\lib\site-packages\conda\common\configuration.py", line 371, in load_file_configs
        raw_data = odict(kv for kv in chain.from_iterable(load_paths))
      File "C:\Users\Pearl\Anaconda3\lib\site-packages\conda\common\configuration.py", line 371, in <genexpr>
        raw_data = odict(kv for kv in chain.from_iterable(load_paths))
      File "C:\Users\Pearl\Anaconda3\lib\site-packages\conda\common\configuration.py", line 346, in _file_yaml_loader
        yield fullpath, YamlRawParameter.make_raw_parameters_from_file(fullpath)
      File "C:\Users\Pearl\Anaconda3\lib\site-packages\conda\common\configuration.py", line 334, in make_raw_parameters_from_file
        ruamel_yaml = yaml_load(fh)
      File "C:\Users\Pearl\Anaconda3\lib\site-packages\conda\common\serialize.py", line 54, in yaml_load
        return yaml.load(string, Loader=yaml.RoundTripLoader, version="1.2")
      File "C:\Users\Pearl\Anaconda3\lib\site-packages\ruamel_yaml\main.py", line 637, in load
        loader = Loader(stream, version, preserve_quotes=preserve_quotes)
      File "C:\Users\Pearl\Anaconda3\lib\site-packages\ruamel_yaml\loader.py", line 59, in __init__
        Reader.__init__(self, stream, loader=self)
      File "C:\Users\Pearl\Anaconda3\lib\site-packages\ruamel_yaml\reader.py", line 80, in __init__
        self.stream = stream  # type: Any  # as .read is called
      File "C:\Users\Pearl\Anaconda3\lib\site-packages\ruamel_yaml\reader.py", line 125, in stream
        self.determine_encoding()
      File "C:\Users\Pearl\Anaconda3\lib\site-packages\ruamel_yaml\reader.py", line 180, in determine_encoding
        self.update(1)
      File "C:\Users\Pearl\Anaconda3\lib\site-packages\ruamel_yaml\reader.py", line 241, in update
        self.check_printable(data)
      File "C:\Users\Pearl\Anaconda3\lib\site-packages\ruamel_yaml\reader.py", line 208, in check_printable
        'unicode', "special characters are not allowed")
    ruamel_yaml.reader.ReaderError: unacceptable character #x0000: special characters are not allowed
      in "C:\Users\Pearl\.condarc", position 0

`$ C:\Users\Pearl\Anaconda3\Scripts\conda info`


An unexpected error has occurred. Conda has prepared the above report.
If submitted, this report will be used by core maintainers to improve
future releases of conda.
Would you like conda to send this report to the core maintainers?

```

</details>

**Comment by csoja** [comment]
Your .condarc file has gotten corrupted.  Please see the troubleshooting section of the documentation for tips on fixing this: https://docs.anaconda.com/anaconda/navigator/troubleshooting/#navigator-error-on-start-up
