### ISSUE TITLE
Missing JupyterLab package dependency when installed in Anaconda

### ISSUE THREAD

**Issue by Jdogzz** [ContinuumIO/anaconda-issues#11315]
### Actual Behavior

The JupyterLab notebook throws an error "Error Starting Kernel" when starting for the first time, with this traceback:

```
Traceback (most recent call last):
  File "C:\Users\user\Anaconda3\envs\testenv\lib\site-packages\tornado\web.py", line 1699, in _execute
    result = await result
  File "C:\Users\user\Anaconda3\envs\testenv\lib\site-packages\tornado\gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "C:\Users\user\Anaconda3\envs\testenv\lib\site-packages\notebook\services\sessions\handlers.py", line 72, in post
    type=mtype))
  File "C:\Users\user\Anaconda3\envs\testenv\lib\site-packages\tornado\gen.py", line 735, in run
    value = future.result()
  File "C:\Users\user\Anaconda3\envs\testenv\lib\site-packages\tornado\gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "C:\Users\user\Anaconda3\envs\testenv\lib\site-packages\notebook\services\sessions\sessionmanager.py", line 88, in create_session
    kernel_id = yield self.start_kernel_for_session(session_id, path, name, type, kernel_name)
  File "C:\Users\user\Anaconda3\envs\testenv\lib\site-packages\tornado\gen.py", line 735, in run
    value = future.result()
  File "C:\Users\user\Anaconda3\envs\testenv\lib\site-packages\tornado\gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "C:\Users\user\Anaconda3\envs\testenv\lib\site-packages\notebook\services\sessions\sessionmanager.py", line 101, in start_kernel_for_session
    self.kernel_manager.start_kernel(path=kernel_path, kernel_name=kernel_name)
  File "C:\Users\user\Anaconda3\envs\testenv\lib\site-packages\tornado\gen.py", line 735, in run
    value = future.result()
  File "C:\Users\user\Anaconda3\envs\testenv\lib\site-packages\tornado\gen.py", line 209, in wrapper
    yielded = next(result)
  File "C:\Users\user\Anaconda3\envs\testenv\lib\site-packages\notebook\services\kernels\kernelmanager.py", line 168, in start_kernel
    super(MappingKernelManager, self).start_kernel(**kwargs)
  File "C:\Users\user\Anaconda3\envs\testenv\lib\site-packages\jupyter_client\multikernelmanager.py", line 110, in start_kernel
    km.start_kernel(**kwargs)
  File "C:\Users\user\Anaconda3\envs\testenv\lib\site-packages\jupyter_client\manager.py", line 240, in start_kernel
    self.write_connection_file()
  File "C:\Users\user\Anaconda3\envs\testenv\lib\site-packages\jupyter_client\connect.py", line 547, in write_connection_file
    kernel_name=self.kernel_name
  File "C:\Users\user\Anaconda3\envs\testenv\lib\site-packages\jupyter_client\connect.py", line 212, in write_connection_file
    with secure_write(fname) as f:
  File "C:\Users\user\Anaconda3\envs\testenv\lib\contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "C:\Users\user\Anaconda3\envs\testenv\lib\site-packages\jupyter_client\connect.py", line 100, in secure_write
    win32_restrict_file_to_user(fname)
  File "C:\Users\user\Anaconda3\envs\testenv\lib\site-packages\jupyter_client\connect.py", line 53, in win32_restrict_file_to_user
    import win32api
ModuleNotFoundError: No module named 'win32api'
```

So there's one issue present with this module missing. I found a stackoverflow thread ( [https://stackoverflow.com/questions/21343774/importerror-no-module-named-win32api](https://stackoverflow.com/questions/21343774/importerror-no-module-named-win32api) ) which suggested installing the pywin32 package, so I went to the Anaconda package list for my new environment, installed that from the list of Not Installed packages, and then closed and reopened JupyterLab. After that, I was able to select the kernel and use the notebook as expected.

### Expected Behavior

The notebook should be usable without additional user intervention out of the box.

### Steps to Reproduce

1. Used the 64 bit graphical installer from the Anaconda website, with all the default options.
2. Made a new environment with Python 3.7 packages.
3. Went to the Home panel to the applications in my new environment, and installed JupyterLab.
4. Launched JupyterLab and made a new notebook with the default Python 3 kernel.

##### Operating System:

Windows 10 64 bit (I was able to reproduce this with a clean VM testbed here: [https://developer.microsoft.com/en-us/windows/downloads/virtual-machines](https://developer.microsoft.com/en-us/windows/downloads/virtual-machines) )

##### `conda info`

<details>

```
     active environment : testenv
    active env location : C:\Users\user\Anaconda3\envs\testenv
            shell level : 1
       user config file : C:\Users\user\.condarc
 populated config files : C:\Users\user\.condarc
          conda version : 4.7.10
    conda-build version : 3.18.8
         python version : 3.7.3.final.0
       virtual packages :
       base environment : C:\Users\user\Anaconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\Users\user\Anaconda3\pkgs
                          C:\Users\user\.conda\pkgs
                          C:\Users\user\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\user\Anaconda3\envs
                          C:\Users\user\.conda\envs
                          C:\Users\user\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.7.10 requests/2.22.0 CPython/3.7.3 Windows/10 Windows/10.0.18362
          administrator : False
             netrc file : None
           offline mode : False

```

</details>

##### `conda list --show-channel-urls`

<details>

```
# packages in environment at C:\Users\user\Anaconda3\envs\testenv:
#
# Name                    Version                   Build  Channel
attrs                     19.1.0                   py37_1    defaults
backcall                  0.1.0                    py37_0    defaults
bleach                    3.1.0                    py37_0    defaults
ca-certificates           2019.8.28                     0    defaults
certifi                   2019.9.11                py37_0    defaults
colorama                  0.4.1                    py37_0    defaults
decorator                 4.4.0                    py37_1    defaults
defusedxml                0.6.0                      py_0    defaults
entrypoints               0.3                      py37_0    defaults
ipykernel                 5.1.2            py37h39e3cac_0    defaults
ipython                   7.8.0            py37h39e3cac_0    defaults
ipython_genutils          0.2.0                    py37_0    defaults
jedi                      0.15.1                   py37_0    defaults
jinja2                    2.10.1                   py37_0    defaults
json5                     0.8.5                      py_0    defaults
jsonschema                3.0.2                    py37_0    defaults
jupyter_client            5.3.3                      py_0    defaults
jupyter_core              4.5.0                      py_0    defaults
jupyterlab                1.0.2            py37hf63ae98_0    defaults
jupyterlab_server         1.0.6                      py_0    defaults
libsodium                 1.0.16               h9d3ae62_0    defaults
m2w64-gcc-libgfortran     5.3.0                         6    defaults
m2w64-gcc-libs            5.3.0                         7    defaults
m2w64-gcc-libs-core       5.3.0                         7    defaults
m2w64-gmp                 6.1.0                         2    defaults
m2w64-libwinpthread-git   5.0.0.4634.697f757               2    defaults
markupsafe                1.1.1            py37he774522_0    defaults
mistune                   0.8.4            py37he774522_0    defaults
msys2-conda-epoch         20160418                      1    defaults
nbconvert                 5.6.0                    py37_1    defaults
nbformat                  4.4.0                    py37_0    defaults
notebook                  6.0.1                    py37_0    defaults
openssl                   1.1.1d               he774522_0    defaults
pandoc                    2.2.3.2                       0    defaults
pandocfilters             1.4.2                    py37_1    defaults
parso                     0.5.1                      py_0    defaults
pickleshare               0.7.5                    py37_0    defaults
pip                       19.2.3                   py37_0    defaults
prometheus_client         0.7.1                      py_0    defaults
prompt_toolkit            2.0.9                    py37_0    defaults
pygments                  2.4.2                      py_0    defaults
pyrsistent                0.14.11          py37he774522_0    defaults
python                    3.7.4                h5263a28_0    defaults
python-dateutil           2.8.0                    py37_0    defaults
pywin32                   223              py37hfa6e2cd_1    defaults
pywinpty                  0.5.5                 py37_1000    defaults
pyzmq                     18.1.0           py37ha925a31_0    defaults
send2trash                1.5.0                    py37_0    defaults
setuptools                41.2.0                   py37_0    defaults
six                       1.12.0                   py37_0    defaults
sqlite                    3.29.0               he774522_0    defaults
terminado                 0.8.2                    py37_0    defaults
testpath                  0.4.2                    py37_0    defaults
tornado                   6.0.3            py37he774522_0    defaults
traitlets                 4.3.2                    py37_0    defaults
vc                        14.1                 h0510ff6_4    defaults
vs2015_runtime            14.16.27012          hf0eaf9b_0    defaults
wcwidth                   0.1.7                    py37_0    defaults
webencodings              0.5.1                    py37_1    defaults
wheel                     0.33.6                   py37_0    defaults
wincertstore              0.2                      py37_0    defaults
winpty                    0.4.3                         4    defaults
zeromq                    4.3.1                h33f27b4_3    defaults

```

</details>

**Comment by msarahan** [comment]
Thanks.  We will add that as a dependency.

**Comment by jjhelmus** [comment]
A new build on `jupyter_client` is now available that includes the dependency on `pywin32`.  This new package will be installed automatically in new environments.

**Comment by StrikerRUS** [comment]
@msarahan @jjhelmus 
Hi! Seems to be still the issue with conda environment with Python 3.5. Python 3.6 is fine.
Please update the package for Python 3.5. Its' EOL `2020-09-13`, so it's quite alive and worth to maintain.
https://devguide.python.org/#status-of-python-branches

```
conda install -q -y -n $env:CONDA_ENV ipywidgets notebook
jupyter nbconvert --ExecutePreprocessor.timeout=180 --to notebook --execute --inplace *.ipynb
```
```
[NbConvertApp] Converting notebook interactive_plot_example.ipynb to notebook
Traceback (most recent call last):
  File "C:\Miniconda\envs\test-env\Scripts\jupyter-nbconvert-script.py", line 9, in <module>
    sys.exit(main())
  File "C:\Miniconda\envs\test-env\lib\site-packages\jupyter_core\application.py", line 267, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "C:\Miniconda\envs\test-env\lib\site-packages\traitlets\config\application.py", line 658, in launch_instance
    app.start()
  File "C:\Miniconda\envs\test-env\lib\site-packages\nbconvert\nbconvertapp.py", line 338, in start
    self.convert_notebooks()
  File "C:\Miniconda\envs\test-env\lib\site-packages\nbconvert\nbconvertapp.py", line 508, in convert_notebooks
    self.convert_single_notebook(notebook_filename)
  File "C:\Miniconda\envs\test-env\lib\site-packages\nbconvert\nbconvertapp.py", line 479, in convert_single_notebook
    output, resources = self.export_single_notebook(notebook_filename, resources, input_buffer=input_buffer)
  File "C:\Miniconda\envs\test-env\lib\site-packages\nbconvert\nbconvertapp.py", line 408, in export_single_notebook
    output, resources = self.exporter.from_filename(notebook_filename, resources=resources)
  File "C:\Miniconda\envs\test-env\lib\site-packages\nbconvert\exporters\exporter.py", line 179, in from_filename
    return self.from_file(f, resources=resources, **kw)
  File "C:\Miniconda\envs\test-env\lib\site-packages\nbconvert\exporters\exporter.py", line 197, in from_file
    return self.from_notebook_node(nbformat.read(file_stream, as_version=4), resources=resources, **kw)
  File "C:\Miniconda\envs\test-env\lib\site-packages\nbconvert\exporters\notebook.py", line 32, in from_notebook_node
    nb_copy, resources = super(NotebookExporter, self).from_notebook_node(nb, resources, **kw)
  File "C:\Miniconda\envs\test-env\lib\site-packages\nbconvert\exporters\exporter.py", line 139, in from_notebook_node
    nb_copy, resources = self._preprocess(nb_copy, resources)
  File "C:\Miniconda\envs\test-env\lib\site-packages\nbconvert\exporters\exporter.py", line 316, in _preprocess
    nbc, resc = preprocessor(nbc, resc)
  File "C:\Miniconda\envs\test-env\lib\site-packages\nbconvert\preprocessors\base.py", line 47, in __call__
    return self.preprocess(nb, resources)
  File "C:\Miniconda\envs\test-env\lib\site-packages\nbconvert\preprocessors\execute.py", line 379, in preprocess
    with self.setup_preprocessor(nb, resources, km=km):
  File "C:\Miniconda\envs\test-env\lib\contextlib.py", line 59, in __enter__
    return next(self.gen)
  File "C:\Miniconda\envs\test-env\lib\site-packages\nbconvert\preprocessors\execute.py", line 324, in setup_preprocessor
    self.km, self.kc = self.start_new_kernel(cwd=path)
  File "C:\Miniconda\envs\test-env\lib\site-packages\nbconvert\preprocessors\execute.py", line 271, in start_new_kernel
    km.start_kernel(extra_arguments=self.extra_arguments, **kwargs)
  File "C:\Miniconda\envs\test-env\lib\site-packages\jupyter_client\manager.py", line 240, in start_kernel
    self.write_connection_file()
  File "C:\Miniconda\envs\test-env\lib\site-packages\jupyter_client\connect.py", line 547, in write_connection_file
    kernel_name=self.kernel_name
  File "C:\Miniconda\envs\test-env\lib\site-packages\jupyter_client\connect.py", line 212, in write_connection_file
    with secure_write(fname) as f:
  File "C:\Miniconda\envs\test-env\lib\contextlib.py", line 59, in __enter__
    return next(self.gen)
  File "C:\Miniconda\envs\test-env\lib\site-packages\jupyter_client\connect.py", line 100, in secure_write
    win32_restrict_file_to_user(fname)
  File "C:\Miniconda\envs\test-env\lib\site-packages\jupyter_client\connect.py", line 53, in win32_restrict_file_to_user
    import win32api
ImportError: No module named 'win32api'
```

```
conda info

     active environment : test-env
    active env location : C:\Miniconda\envs\test-env
            shell level : 1
       user config file : C:\Users\VssAdministrator\.condarc
 populated config files : C:\Users\VssAdministrator\.condarc
          conda version : 4.7.12
    conda-build version : not installed
         python version : 3.7.3.final.0
       virtual packages : 
       base environment : C:\Miniconda  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\Miniconda\pkgs
                          C:\Users\VssAdministrator\.conda\pkgs
                          C:\Users\VssAdministrator\AppData\Local\conda\conda\pkgs
       envs directories : C:\Miniconda\envs
                          C:\Users\VssAdministrator\.conda\envs
                          C:\Users\VssAdministrator\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.7.12 requests/2.21.0 CPython/3.7.3 Windows/10 Windows/10.0.14393
          administrator : True
             netrc file : None
           offline mode : False
```
```
conda list --show-channel-urls
# packages in environment at C:\Miniconda\envs\test-env:
#
# Name                    Version                   Build  Channel
atomicwrites              1.3.0                      py_0    defaults
attrs                     19.1.0                     py_0    defaults
backcall                  0.1.0                    py35_0    defaults
blas                      1.0                         mkl    defaults
bleach                    2.1.4                    py35_0    defaults
ca-certificates           2019.8.28                     0    defaults
certifi                   2018.8.24                py35_1    defaults
colorama                  0.3.9            py35h32a752f_0    defaults
cycler                    0.10.0           py35hcc71164_0    defaults
decorator                 4.4.0                      py_0    defaults
defusedxml                0.6.0                      py_0    defaults
entrypoints               0.2.3                    py35_2    defaults
freetype                  2.9.1                ha9979f8_1    defaults
graphviz                  2.38                 hfd603c8_2    defaults
html5lib                  1.0.1                    py35_0    defaults
icc_rt                    2019.0.0             h0cc432a_1    defaults
icu                       58.2                 ha66f8fd_1    defaults
intel-openmp              2019.4                      245    defaults
ipykernel                 4.10.0                   py35_0    defaults
ipython                   6.5.0                    py35_0    defaults
ipython_genutils          0.2.0            py35ha709e79_0    defaults
ipywidgets                7.4.1                    py35_0    defaults
jedi                      0.12.1                   py35_0    defaults
jinja2                    2.10                     py35_0    defaults
joblib                    0.12.3                   py35_0    defaults
jpeg                      9b                   hb83a4c4_2    defaults
jsonschema                2.6.0            py35h27d56d3_0    defaults
jupyter_client            5.3.3                      py_0    defaults
jupyter_core              4.5.0                      py_0    defaults
kiwisolver                1.0.1            py35h6538335_0    defaults
libpng                    1.6.37               h2a8f88b_0    defaults
libsodium                 1.0.16               h9d3ae62_0    defaults
lightgbm                  2.3.1                    pypi_0    pypi
m2w64-gcc-libgfortran     5.3.0                         6    defaults
m2w64-gcc-libs            5.3.0                         7    defaults
m2w64-gcc-libs-core       5.3.0                         7    defaults
m2w64-gmp                 6.1.0                         2    defaults
m2w64-libwinpthread-git   5.0.0.4634.697f757               2    defaults
markupsafe                1.0              py35hfa6e2cd_1    defaults
matplotlib                3.0.0            py35hd159220_0    defaults
mistune                   0.8.3            py35hfa6e2cd_1    defaults
mkl                       2018.0.3                      1    defaults
mkl_fft                   1.0.6            py35hdbbee80_0    defaults
mkl_random                1.0.1            py35h77b88f5_1    defaults
more-itertools            4.3.0                    py35_0    defaults
msys2-conda-epoch         20160418                      1    defaults
nbconvert                 5.5.0                      py_0    defaults
nbformat                  4.4.0            py35h908c9d9_0    defaults
notebook                  5.6.0                    py35_0    defaults
numpy                     1.15.2           py35ha559c80_0    defaults
numpy-base                1.15.2           py35h8128ebf_0    defaults
openssl                   1.1.1d               he774522_2    defaults
pandas                    0.23.4           py35h830ac7b_0    defaults
pandoc                    2.2.3.2                       0    defaults
pandocfilters             1.4.2                    py35_1    defaults
parso                     0.5.1                      py_0    defaults
pathlib2                  2.3.2                    py35_0    defaults
pickleshare               0.7.4            py35h2f9f535_0    defaults
pip                       10.0.1                   py35_0    defaults
pluggy                    0.11.0                     py_0    defaults
prometheus_client         0.7.1                      py_0    defaults
prompt_toolkit            1.0.15           py35h89c7cb4_0    defaults
psutil                    5.4.7            py35hfa6e2cd_0    defaults
py                        1.6.0                    py35_0    defaults
pygments                  2.4.2                      py_0    defaults
pyparsing                 2.4.2                      py_0    defaults
pyqt                      5.9.2            py35h6538335_2    defaults
pytest                    3.8.1                    py35_0    defaults
python                    3.5.6                he025d50_0    defaults
python-dateutil           2.7.3                    py35_0    defaults
python-graphviz           0.10.1                     py_0    defaults
pytz                      2019.2                     py_0    defaults
pywinpty                  0.5.4                    py35_0    defaults
pyzmq                     17.1.2           py35hfa6e2cd_0    defaults
qt                        5.9.7            vc14h73c81de_0    defaults
scikit-learn              0.20.0           py35heebcf9a_1    defaults
scipy                     1.1.0            py35h4f6bf74_1    defaults
send2trash                1.5.0                    py35_0    defaults
setuptools                40.2.0                   py35_0    defaults
simplegeneric             0.8.1                    py35_2    defaults
sip                       4.19.8           py35h6538335_0    defaults
six                       1.11.0                   py35_1    defaults
sqlite                    3.29.0               he774522_0    defaults
terminado                 0.8.1                    py35_1    defaults
testpath                  0.3.1            py35h06cf69e_0    defaults
tornado                   5.1.1            py35hfa6e2cd_0    defaults
traitlets                 4.3.2            py35h09b975b_0    defaults
vc                        14.1                 h0510ff6_4    defaults
vs2015_runtime            14.16.27012          hf0eaf9b_0    defaults
wcwidth                   0.1.7            py35h6e80d8a_0    defaults
webencodings              0.5.1                    py35_1    defaults
wheel                     0.31.1                   py35_0    defaults
widgetsnbextension        3.4.1                    py35_0    defaults
win_unicode_console       0.5              py35h56988b5_0    defaults
wincertstore              0.2              py35hfebbdb8_0    defaults
winpty                    0.4.3                         4    defaults
zeromq                    4.2.5                he025d50_1    defaults
zlib                      1.2.11               h62dcd97_3    defaults
```

**Comment by msarahan** [comment]
Anaconda supports the most recent 2 python 3 releases and python 2.7.  We will not be adding further support for python 3.5, nor fixing old python 3.5 packages without an enterprise support contract.

**Comment by jjhelmus** [comment]
Running `conda install pywin32` in the environment will install the necessary package.

**Comment by StrikerRUS** [comment]
@msarahan Is there any public notes/article about dropping Python 3.5 support?

@jjhelmus Thanks! Already using this workaround 👍
