### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by FERMARMEN** [ContinuumIO/anaconda-issues#11330]
### Actual Behavior

Anaconda Navigator crash when it is starting. It opens a web page that shows the "Navigator Error" message.

### Expected Behavior

It should open the navigator interface.

### Steps to Reproduce

Click on Anaconda navigator.

##### Anaconda or Miniconda version:
Anaconda

Python 3.6.5 (Anaconda3 5.2.0 64-bit)
and
Anaconda3-2019.07-Windows-x86_64
Both have the same fail.

##### Operating System:
Windows 7 Profesional

##### `conda info`

<details>

```
PASTE OUTPUT HERE:

Navigator Error

An unexpected error occurred on Navigator start-up
Report

Please report this issue in the anaconda issue tracker
Main Error

expected str, bytes or os.PathLike object, not NoneType

Traceback

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\anaconda_navigator\exceptions.py", line 75, in exception_handler
    return_value = func(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 150, in start_app
    window = run_app(splash)
  File "C:\ProgramData\Anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 65, in run_app
    window = MainWindow(splash=splash, tab_project=False)
  File "C:\ProgramData\Anaconda3\lib\site-packages\anaconda_navigator\widgets\main_window.py", line 163, in __init__
    self.api = AnacondaAPI()
  File "C:\ProgramData\Anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 2185, in AnacondaAPI
    ANACONDA_API = _AnacondaAPI()
  File "C:\ProgramData\Anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 89, in __init__
    self._conda_api = CondaAPI()
  File "C:\ProgramData\Anaconda3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 1714, in CondaAPI
    CONDA_API = _CondaAPI()
  File "C:\ProgramData\Anaconda3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 353, in __init__
    self.sys_rc_path = join(self.ROOT_PREFIX, '.condarc')
  File "C:\ProgramData\Anaconda3\lib\ntpath.py", line 76, in join
    path = os.fspath(path)
TypeError: expected str, bytes or os.PathLike object, not NoneType


```

</details>

##### `conda list --show-channel-urls`

<details>

```
PASTE OUTPUT HERE:

```

</details>

**Comment by csoja** [comment]
Based on the error it looks like your .condarc conda configuration file has gotten corrupted.  I'd recommend removing that and see if Navigator starts up ok again.

**Comment by FERMARMEN** [comment]
Thank you so much!!. It's working properly now. You save my day.😁

Thank you for the fast support.
