### ISSUE TITLE
Navigator Error:  An unexpected error occurred on Navigator start-up

### ISSUE THREAD

**Issue by stephendmiller1991** [ContinuumIO/anaconda-issues#11332]
Getting the below error when trying to open anaconda 

Navigator Error

An unexpected error occurred on Navigator start-up

Report

Please report this issue in the anaconda issue tracker

Main Error

expected str, bytes or os.PathLike object, not NoneType
Traceback

Traceback (most recent call last):
  File "/anaconda3/lib/python3.7/site-packages/anaconda_navigator/exceptions.py", line 75, in exception_handler
    return_value = func(*args, **kwargs)
  File "/anaconda3/lib/python3.7/site-packages/anaconda_navigator/app/start.py", line 151, in start_app
    window = run_app(splash)
  File "/anaconda3/lib/python3.7/site-packages/anaconda_navigator/app/start.py", line 65, in run_app
    window = MainWindow(splash=splash, tab_project=False)
  File "/anaconda3/lib/python3.7/site-packages/anaconda_navigator/widgets/main_window.py", line 168, in __init__
    self.api = AnacondaAPI()
  File "/anaconda3/lib/python3.7/site-packages/anaconda_navigator/api/anaconda_api.py", line 2337, in AnacondaAPI
    ANACONDA_API = _AnacondaAPI()
  File "/anaconda3/lib/python3.7/site-packages/anaconda_navigator/api/anaconda_api.py", line 89, in __init__
    self._conda_api = CondaAPI()
  File "/anaconda3/lib/python3.7/site-packages/anaconda_navigator/api/conda_api.py", line 1767, in CondaAPI
    CONDA_API = _CondaAPI()
  File "/anaconda3/lib/python3.7/site-packages/anaconda_navigator/api/conda_api.py", line 353, in __init__
    self.sys_rc_path = join(self.ROOT_PREFIX, '.condarc')
  File "/anaconda3/lib/python3.7/posixpath.py", line 80, in join
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType

**Comment by csoja** [comment]
Looks like your .condarc conda configuration file has gotten corrupted.  I'd recommend removing it and starting Navigator again.

**Comment by stephendmiller1991** [comment]
where is that file located?

**Comment by csoja** [comment]
If you open up the Anaconda Prompt, and execute _conda info_ on the command line,  one of the pieces of information displayed will be where your .condarc configuration file is located.  
The docs have additional information on Anaconda if you are new to the ecosystem: https://docs.anaconda.com/anaconda/user-guide/getting-started/
