### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by evaneversaydie** [ContinuumIO/anaconda-issues#11344]
## Main error
An unexpected error occurred on Navigator start-up<br>psutil.AccessDenied (pid=4144)
## Traceback
```
Traceback (most recent call last):
  File "C:\Users\Eva\Anaconda3\lib\site-packages\psutil\_pswindows.py", line 635, in wrapper
    return fun(self, *args, **kwargs)
  File "C:\Users\Eva\Anaconda3\lib\site-packages\psutil\_pswindows.py", line 705, in cmdline
    ret = cext.proc_cmdline(self.pid)
PermissionError: [WinError 5] 存取被拒。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Eva\Anaconda3\lib\site-packages\anaconda_navigator\exceptions.py", line 75, in exception_handler
    return_value = func(*args, **kwargs)
  File "C:\Users\Eva\Anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 108, in start_app
    if misc.load_pid() is None:  # A stale lock might be around
  File "C:\Users\Eva\Anaconda3\lib\site-packages\anaconda_navigator\utils\misc.py", line 384, in load_pid
    cmds = process.cmdline()
  File "C:\Users\Eva\Anaconda3\lib\site-packages\psutil\__init__.py", line 665, in cmdline
    return self._proc.cmdline()
  File "C:\Users\Eva\Anaconda3\lib\site-packages\psutil\_pswindows.py", line 638, in wrapper
    raise AccessDenied(self.pid, self._name)
psutil._exceptions.AccessDenied: psutil.AccessDenied (pid=4144)

```
## System information
```
python: 3.6.5
language: zh_TW
os: Windows;10;10.0.18362;AMD64;Intel64 Family 6 Model 142 Stepping 9, GenuineIntel
version: 1.6.2
platform: win-64
qt: 5.9.4
pyqt: 5.9.2
conda: 4.5.4
```

**Comment by csoja** [comment]
In the Anaconda Prompt:

conda update conda
conda update anaconda-navigator
conda update navigator-updater
anaconda-navigator --reset

The last command is the key to fixing your issue - as it removes the lock file that is causing your problem.
