### ISSUE TITLE
Anaconda not opening

### ISSUE THREAD

**Issue by jadtay** [ContinuumIO/anaconda-issues#11342]
### Actual Behavior

Anaconda does not launch when i click the application but i am able to open the application using anaconda-navigator in the Anaconda prompt

Am also unable to launch Jupyter notebook

### Expected Behavior

Anaconda should launch

### Steps to Reproduce

I click on the Anaconda application and it does not launch

##### Anaconda or Miniconda version:
conda 4.7.12

##### Operating System:
Windows 10
##### `conda info`

<details>

```
PASTE OUTPUT HERE:

```

</details>

##### `conda list --show-channel-urls`

<details>

```
PASTE OUTPUT HERE:
  active environment : base
    active env location : C:\Users\jadta\Anaconda3
            shell level : 1
       user config file : C:\Users\jadta\.condarc
 populated config files : C:\Users\jadta\.condarc
          conda version : 4.7.12
    conda-build version : 3.18.8
         python version : 3.7.3.final.0
       virtual packages : __cuda=10.0
       base environment : C:\Users\jadta\Anaconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\Users\jadta\Anaconda3\pkgs
                          C:\Users\jadta\.conda\pkgs
                          C:\Users\jadta\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\jadta\Anaconda3\envs
                          C:\Users\jadta\.conda\envs
                          C:\Users\jadta\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.7.12 requests/2.22.0 CPython/3.7.3 Windows/10 Windows/10.0.18362
          administrator : False
             netrc file : None
           offline mode : False

```

</details>

**Comment by jadtay** [comment]
Also get this error when launching Jupyter notebook:

Traceback (most recent call last):
File "C:\Users\jadta\Anaconda3\Scripts\jupyter-notebook-script.py", line 6, in 
from notebook.notebookapp import main
File "C:\Users\jadta\AppData\Roaming\Python\Python37\site-packages\notebook\notebookapp.py", line 47, in 
from zmq.eventloop import ioloop
File "C:\Users\jadta\AppData\Roaming\Python\Python37\site-packages\zmq\__init__.py", line 47, in 
from zmq import backend
File "C:\Users\jadta\AppData\Roaming\Python\Python37\site-packages\zmq\backend\__init__.py", line 40, in 
reraise(*exc_info)
File "C:\Users\jadta\AppData\Roaming\Python\Python37\site-packages\zmq\utils\sixcerpt.py", line 34, in reraise
raise value
File "C:\Users\jadta\AppData\Roaming\Python\Python37\site-packages\zmq\backend\__init__.py", line 27, in 
_ns = select_backend(first)
File "C:\Users\jadta\AppData\Roaming\Python\Python37\site-packages\zmq\backend\select.py", line 28, in select_backend
mod = __import__(name, fromlist=public_api)
File "C:\Users\jadta\AppData\Roaming\Python\Python37\site-packages\zmq\backend\cython\__init__.py", line 6, in 
from . import (constants, error, message, context,
ImportError: cannot import name 'constants' from 'zmq.backend.cython' (C:\Users\jadta\AppData\Roaming\Python\Python37\site-packages\zmq\backend\cython\__init__.py)
