### ISSUE TITLE
Theano lazylinker broken in macOS Catalina

### ISSUE THREAD

**Issue by ApoorvDP** [ContinuumIO/anaconda-issues#11359]
### Actual Behavior

Attempting to import theano causes an error.

Error stack trace:
```
You can find the C code in this temporary file: /var/folders/3z/h9fchh2j4t36rj95hskd1vz80000gn/T/theano_compilation_error_jr3ufqk1
Traceback (most recent call last):
  File "/Users/apoorv/anaconda3/lib/python3.7/site-packages/theano/gof/lazylinker_c.py", line 81, in <module>
    actual_version, force_compile, _need_reload))
ImportError: Version check of the existing lazylinker compiled file. Looking for version 0.211, but found None. Extra debug information: force_compile=False, _need_reload=True

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/apoorv/anaconda3/lib/python3.7/site-packages/theano/gof/lazylinker_c.py", line 105, in <module>
    actual_version, force_compile, _need_reload))
ImportError: Version check of the existing lazylinker compiled file. Looking for version 0.211, but found None. Extra debug information: force_compile=False, _need_reload=True

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/apoorv/anaconda3/lib/python3.7/site-packages/theano/__init__.py", line 110, in <module>
    from theano.compile import (
  File "/Users/apoorv/anaconda3/lib/python3.7/site-packages/theano/compile/__init__.py", line 12, in <module>
    from theano.compile.mode import *
  File "/Users/apoorv/anaconda3/lib/python3.7/site-packages/theano/compile/mode.py", line 11, in <module>
    import theano.gof.vm
  File "/Users/apoorv/anaconda3/lib/python3.7/site-packages/theano/gof/vm.py", line 674, in <module>
    from . import lazylinker_c
  File "/Users/apoorv/anaconda3/lib/python3.7/site-packages/theano/gof/lazylinker_c.py", line 140, in <module>
    preargs=args)
  File "/Users/apoorv/anaconda3/lib/python3.7/site-packages/theano/gof/cmodule.py", line 2399, in compile_str
    (status, compile_stderr.replace('\n', '. ')))
Exception: Compilation failed (return status=1): In file included from /Users/apoorv/.theano/compiledir_Darwin-19.0.0-x86_64-i386-64bit-i386-3.7.3-64/lazylinker_ext/mod.cpp:1:. In file included from /Users/apoorv/anaconda3/include/python3.7m/Python.h:25:. /Users/apoorv/anaconda3/bin/../include/c++/v1/stdio.h:108:15: fatal error: 'stdio.h' file not found. #include_next <stdio.h>.               ^~~~~~~~~. 1 error generated.. 
```

### Expected Behavior

No error, as it was with macOS Mojave 10.14.6

### Steps to Reproduce

Open terminal, type:

`python`

In the python console, type:

`import theano`

##### Anaconda or Miniconda version:

anaconda Command line client (version 1.7.2)
Directory: anaconda3
python 3.7.3
conda 4.7.12
theano 1.0.4

##### Operating System:

macOS Catalina 10.15

##### `conda info`

<details>

```
     active environment : None
       user config file : /Users/apoorv/.condarc
 populated config files : /Users/apoorv/.condarc
          conda version : 4.7.12
    conda-build version : 3.18.8
         python version : 3.7.3.final.0
       virtual packages : 
       base environment : /Users/apoorv/anaconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/osx-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/osx-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /Users/apoorv/anaconda3/pkgs
                          /Users/apoorv/.conda/pkgs
       envs directories : /Users/apoorv/anaconda3/envs
                          /Users/apoorv/.conda/envs
               platform : osx-64
             user-agent : conda/4.7.12 requests/2.22.0 CPython/3.7.3 Darwin/19.0.0 OSX/10.15
                UID:GID : 501:20
             netrc file : None
           offline mode : False
```

</details>

##### `conda list --show-channel-urls`

<details>

```
# packages in environment at /Users/apoorv/anaconda3:
#
# Name                    Version                   Build  Channel
_anaconda_depends         2019.03                  py37_0    defaults
_ipyw_jlab_nb_ext_conf    0.1.0                    py37_0    defaults
_tflow_select             2.3.0                       mkl    defaults
absl-py                   0.8.0                    py37_0    defaults
alabaster                 0.7.12                   py37_0    defaults
anaconda                  custom                   py37_1    defaults
anaconda-clean            1.1.0                    py37_1    defaults
anaconda-client           1.7.2                    py37_0    defaults
anaconda-navigator        1.9.7                    py37_0    defaults
anaconda-project          0.8.3                      py_0    defaults
appnope                   0.1.0                    py37_0    defaults
appscript                 1.1.0            py37h1de35cc_0    defaults
asn1crypto                0.24.0                   py37_0    defaults
astor                     0.8.0                    py37_0    defaults
astroid                   2.2.5                    py37_0    defaults
astropy                   3.2.1            py37h1de35cc_0    defaults
atomicwrites              1.3.0                    py37_1    defaults
attrs                     19.1.0                   py37_1    defaults
babel                     2.7.0                      py_0    defaults
backcall                  0.1.0                    py37_0    defaults
backports                 1.0                        py_2    defaults
backports.functools_lru_cache 1.5                        py_2    defaults
backports.os              0.1.1                    py37_0    defaults
backports.shutil_get_terminal_size 1.0.0                    py37_2    defaults
backports.tempfile        1.0                        py_1    defaults
backports.weakref         1.0.post1                  py_1    defaults
beautifulsoup4            4.7.1                    py37_1    defaults
bitarray                  0.9.3            py37h1de35cc_0    defaults
bkcharts                  0.2                      py37_0    defaults
blas                      1.0                         mkl    defaults
bleach                    3.1.0                    py37_0    defaults
blosc                     1.16.3               hd9629dc_0    defaults
bokeh                     1.2.0                    py37_0    defaults
boto                      2.49.0                   py37_0    defaults
bottleneck                1.2.1            py37h1d22016_1    defaults
bzip2                     1.0.8                h1de35cc_0    defaults
c-ares                    1.15.0            h1de35cc_1001    defaults
ca-certificates           2019.8.28                     0    defaults
cairo                     1.14.12              hc4e6be7_4    defaults
cctools                   895                           1    defaults
certifi                   2019.9.11                py37_0    defaults
cffi                      1.12.3           py37hb5b8e2f_0    defaults
chardet                   3.0.4                    py37_1    defaults
clang                     4.0.1                         1    defaults
clang_osx-64              4.0.1               h1ce6c1d_18    defaults
clangxx                   4.0.1                         1    defaults
clangxx_osx-64            4.0.1               h22b1bf0_18    defaults
click                     7.0                      py37_0    defaults
cloudpickle               1.2.1                      py_0    defaults
clyent                    1.2.2                    py37_1    defaults
colorama                  0.4.1                    py37_0    defaults
compiler-rt               4.0.1                hcfea43d_1    defaults
conda                     4.7.12                   py37_0    defaults
conda-build               3.18.8                   py37_0    defaults
conda-env                 2.6.0                         1    defaults
conda-package-handling    1.3.11                   py37_0    defaults
conda-verify              3.4.2                      py_1    defaults
contextlib2               0.5.5                    py37_0    defaults
cryptography              2.7              py37ha12b0ac_0    defaults
curl                      7.65.2               ha441bb4_0    defaults
cycler                    0.10.0                   py37_0    defaults
cython                    0.29.12          py37h0a44026_0    defaults
cytoolz                   0.10.0           py37h1de35cc_0    defaults
dask                      2.1.0                      py_0    defaults
dask-core                 2.1.0                      py_0    defaults
dbus                      1.13.6               h90a0687_0    defaults
decorator                 4.4.0                    py37_1    defaults
defusedxml                0.6.0                      py_0    defaults
distributed               2.1.0                      py_0    defaults
docutils                  0.14                     py37_0    defaults
entrypoints               0.3                      py37_0    defaults
et_xmlfile                1.0.1                    py37_0    defaults
expat                     2.2.6                h0a44026_0    defaults
fastcache                 1.1.0            py37h1de35cc_0    defaults
ffmpeg                    4.0                  h01ea3c9_0    defaults
filelock                  3.0.12                     py_0    defaults
flask                     1.1.1                      py_0    defaults
fontconfig                2.13.0               h5d5b041_1    defaults
freetype                  2.9.1                hb4e5f40_0    defaults
future                    0.17.1                   py37_0    defaults
gast                      0.3.2                      py_0    defaults
get_terminal_size         1.0.0                h7520d66_0    defaults
gettext                   0.19.8.1             h15daf44_3    defaults
gevent                    1.4.0            py37h1de35cc_0    defaults
glib                      2.56.2               hd9629dc_0    defaults
glob2                     0.7                        py_0    defaults
gmp                       6.1.2                hb37e062_1    defaults
gmpy2                     2.0.8            py37h6ef4df4_2    defaults
graphite2                 1.3.13               h2098e52_0    defaults
greenlet                  0.4.15           py37h1de35cc_0    defaults
grpcio                    1.16.1           py37h044775b_1    defaults
h5py                      2.8.0            py37h878fce3_3    defaults
harfbuzz                  1.8.8                hb8d4a28_0    defaults
hdf5                      1.10.2               hfa1e0ec_1    defaults
heapdict                  1.0.0                    py37_2    defaults
html5lib                  1.0.1                    py37_0    defaults
icu                       58.2                 h4b95b61_1    defaults
idna                      2.8                      py37_0    defaults
imageio                   2.5.0                    py37_0    defaults
imagesize                 1.1.0                    py37_0    defaults
importlib_metadata        0.17                     py37_1    defaults
intel-openmp              2019.4                      233    defaults
ipykernel                 5.1.1            py37h39e3cac_0    defaults
ipython                   7.6.1            py37h39e3cac_0    defaults
ipython_genutils          0.2.0                    py37_0    defaults
ipywidgets                7.5.0                      py_0    defaults
isort                     4.3.21                   py37_0    defaults
itsdangerous              1.1.0                    py37_0    defaults
jasper                    2.0.14               h636a363_1    defaults
jbig                      2.1                  h4d881f8_0    defaults
jdcal                     1.4.1                      py_0    defaults
jedi                      0.13.3                   py37_0    defaults
jinja2                    2.10.1                   py37_0    defaults
joblib                    0.13.2                   py37_0    defaults
jpeg                      9b                   he5867d9_2    defaults
json5                     0.8.4                      py_0    defaults
jsonschema                3.0.1                    py37_0    defaults
jupyter                   1.0.0                    py37_7    defaults
jupyter_client            5.3.1                      py_0    defaults
jupyter_console           6.0.0                    py37_0    defaults
jupyter_core              4.5.0                      py_0    defaults
jupyterlab                1.0.2            py37hf63ae98_0    defaults
jupyterlab_server         1.0.0                      py_0    defaults
keras                     2.2.4                         0    defaults
keras-applications        1.0.8                      py_0    defaults
keras-base                2.2.4                    py37_0    defaults
keras-preprocessing       1.1.0                      py_1    defaults
keyring                   18.0.0                   py37_0    defaults
kiwisolver                1.1.0            py37h0a44026_0    defaults
krb5                      1.16.1               hddcf347_7    defaults
lazy-object-proxy         1.4.1            py37h1de35cc_0    defaults
ld64                      274.2                         1    defaults
libarchive                3.3.3                h786848e_5    defaults
libcurl                   7.65.2               h051b688_0    defaults
libcxx                    4.0.1                hcfea43d_1    defaults
libcxxabi                 4.0.1                hcfea43d_1    defaults
libedit                   3.1.20181209         hb402a30_0    defaults
libffi                    3.2.1                h475c297_4    defaults
libgfortran               3.0.1                h93005f0_2    defaults
libiconv                  1.15                 hdd342a3_7    defaults
liblief                   0.9.0                h2a1bed3_2    defaults
libopencv                 3.4.2                h7c891bd_1    defaults
libopus                   1.3                  h1de35cc_0    defaults
libpng                    1.6.37               ha441bb4_0    defaults
libprotobuf               3.9.2                hd9629dc_0    defaults
libsodium                 1.0.16               h3efe00b_0    defaults
libssh2                   1.8.2                ha12b0ac_0    defaults
libtiff                   4.0.10               hcb84e12_2    defaults
libvpx                    1.7.0                h378b8a2_0    defaults
libxml2                   2.9.9                hf6e021a_1    defaults
libxslt                   1.1.33               h33a18ac_0    defaults
llvm                      4.0.1                         1    defaults
llvm-lto-tapi             4.0.1                         1    defaults
llvm-openmp               4.0.1                hcfea43d_1    defaults
llvmlite                  0.29.0           py37h98b8051_0    defaults
locket                    0.2.0                    py37_1    defaults
lxml                      4.3.4            py37hef8c89e_0    defaults
lz4-c                     1.8.1.2              h1de35cc_0    defaults
lzo                       2.10                 h362108e_2    defaults
markdown                  3.1.1                    py37_0    defaults
markupsafe                1.1.1            py37h1de35cc_0    defaults
matplotlib                3.1.0            py37h54f8f79_0    defaults
mccabe                    0.6.1                    py37_1    defaults
mistune                   0.8.4            py37h1de35cc_0    defaults
mkl                       2019.4                      233    defaults
mkl-service               2.0.2            py37h1de35cc_0    defaults
mkl_fft                   1.0.12           py37h5e564d8_0    defaults
mkl_random                1.0.2            py37h27c97d8_0    defaults
mock                      3.0.5                    py37_0    defaults
more-itertools            7.0.0                    py37_0    defaults
mpc                       1.1.0                h6ef4df4_1    defaults
mpfr                      4.0.1                h3018a27_3    defaults
mpmath                    1.1.0                    py37_0    defaults
msgpack-python            0.6.1            py37h04f5b5a_1    defaults
multipledispatch          0.6.0                    py37_0    defaults
navigator-updater         0.2.1                    py37_0    defaults
nbconvert                 5.5.0                      py_0    defaults
nbformat                  4.4.0                    py37_0    defaults
ncurses                   6.1                  h0a44026_1    defaults
networkx                  2.3                        py_0    defaults
ninja                     1.9.0            py37h04f5b5a_0    defaults
nltk                      3.4.4                    py37_0    defaults
nose                      1.3.7                    py37_2    defaults
notebook                  6.0.0                    py37_0    defaults
numba                     0.44.1           py37h6440ff4_0    defaults
numexpr                   2.6.9            py37h7413580_0    defaults
numpy                     1.16.4           py37hacdab7b_0    defaults
numpy-base                1.16.4           py37h6575580_0    defaults
numpydoc                  0.9.1                      py_0    defaults
olefile                   0.46                     py37_0    defaults
opencv                    3.4.2            py37h6fd60c2_1    defaults
openpyxl                  2.6.2                      py_0    defaults
openssl                   1.1.1d               h1de35cc_2    defaults
packaging                 19.0                     py37_0    defaults
pandas                    0.24.2           py37h0a44026_0    defaults
pandoc                    2.2.3.2                       0    defaults
pandocfilters             1.4.2                    py37_1    defaults
parso                     0.5.0                      py_0    defaults
partd                     1.0.0                      py_0    defaults
path.py                   12.0.1                     py_0    defaults
pathlib2                  2.3.4                    py37_0    defaults
patsy                     0.5.1                    py37_0    defaults
pcre                      8.43                 h0a44026_0    defaults
pep8                      1.7.1                    py37_0    defaults
pexpect                   4.7.0                    py37_0    defaults
pickleshare               0.7.5                    py37_0    defaults
pillow                    6.1.0            py37hb68e598_0    defaults
pip                       19.1.1                   py37_0    defaults
pixman                    0.38.0               h1de35cc_0    defaults
pkginfo                   1.5.0.1                  py37_0    defaults
pluggy                    0.12.0                     py_0    defaults
ply                       3.11                     py37_0    defaults
prometheus_client         0.7.1                      py_0    defaults
prompt_toolkit            2.0.9                    py37_0    defaults
protobuf                  3.9.2            py37h0a44026_0    defaults
psutil                    5.6.3            py37h1de35cc_0    defaults
ptyprocess                0.6.0                    py37_0    defaults
py                        1.8.0                    py37_0    defaults
py-lief                   0.9.0            py37h1413db1_2    defaults
py-opencv                 3.4.2            py37h7c891bd_1    defaults
pycodestyle               2.5.0                    py37_0    defaults
pycosat                   0.6.3            py37h1de35cc_0    defaults
pycparser                 2.19                     py37_0    defaults
pycrypto                  2.6.1            py37h1de35cc_9    defaults
pycurl                    7.43.0.3         py37ha12b0ac_0    defaults
pyflakes                  2.1.1                    py37_0    defaults
pygments                  2.4.2                      py_0    defaults
pylint                    2.3.1                    py37_0    defaults
pyodbc                    4.0.26           py37h0a44026_0    defaults
pyopenssl                 19.0.0                   py37_0    defaults
pyparsing                 2.4.0                      py_0    defaults
pyqt                      5.9.2            py37h655552a_2    defaults
pyrsistent                0.14.11          py37h1de35cc_0    defaults
pysocks                   1.7.0                    py37_0    defaults
pytables                  3.4.4            py37h13cba08_0    defaults
pytest                    5.0.1                    py37_0    defaults
pytest-arraydiff          0.3              py37h39e3cac_0    defaults
pytest-astropy            0.5.0                    py37_0    defaults
pytest-doctestplus        0.3.0                    py37_0    defaults
pytest-openfiles          0.3.2                    py37_0    defaults
pytest-remotedata         0.3.1                    py37_0    defaults
python                    3.7.3                h359304d_0    defaults
python-dateutil           2.8.0                    py37_0    defaults
python-libarchive-c       2.8                     py37_11    defaults
python.app                2                        py37_9    defaults
pytorch                   1.2.0                   py3.7_0    pytorch
pytz                      2019.1                     py_0    defaults
pywavelets                1.0.3            py37h1d22016_1    defaults
pyyaml                    5.1.1            py37h1de35cc_0    defaults
pyzmq                     18.0.0           py37h0a44026_0    defaults
qt                        5.9.7                h468cd18_1    defaults
qtawesome                 0.5.7                    py37_1    defaults
qtconsole                 4.5.1                      py_0    defaults
qtpy                      1.8.0                      py_0    defaults
readline                  7.0                  h1de35cc_5    defaults
requests                  2.22.0                   py37_0    defaults
rope                      0.14.0                     py_0    defaults
ruamel_yaml               0.15.46          py37h1de35cc_0    defaults
scikit-image              0.15.0           py37h0a44026_0    defaults
scikit-learn              0.21.2           py37h27c97d8_0    defaults
scipy                     1.3.0            py37h1410ff5_0    defaults
seaborn                   0.9.0                    py37_0    defaults
send2trash                1.5.0                    py37_0    defaults
setuptools                41.0.1                   py37_0    defaults
simplegeneric             0.8.1                    py37_2    defaults
singledispatch            3.4.0.3                  py37_0    defaults
sip                       4.19.8           py37h0a44026_0    defaults
six                       1.12.0                   py37_0    defaults
snappy                    1.1.7                he62c110_3    defaults
snowballstemmer           1.9.0                      py_0    defaults
sortedcollections         1.1.2                    py37_0    defaults
sortedcontainers          2.1.0                    py37_0    defaults
soupsieve                 1.8                      py37_0    defaults
sphinx                    2.1.2                      py_0    defaults
sphinxcontrib             1.0                      py37_1    defaults
sphinxcontrib-applehelp   1.0.1                      py_0    defaults
sphinxcontrib-devhelp     1.0.1                      py_0    defaults
sphinxcontrib-htmlhelp    1.0.2                      py_0    defaults
sphinxcontrib-jsmath      1.0.1                      py_0    defaults
sphinxcontrib-qthelp      1.0.2                      py_0    defaults
sphinxcontrib-serializinghtml 1.1.3                      py_0    defaults
sphinxcontrib-websupport  1.1.2                      py_0    defaults
spyder                    3.3.6                    py37_0    defaults
spyder-kernels            0.5.1                    py37_0    defaults
sqlalchemy                1.3.5            py37h1de35cc_0    defaults
sqlite                    3.29.0               ha441bb4_0    defaults
statsmodels               0.10.0           py37h1d22016_0    defaults
sympy                     1.4                      py37_0    defaults
tbb                       2019.4               h04f5b5a_0    defaults
tblib                     1.4.0                      py_0    defaults
tensorboard               1.14.0           py37h80053f4_0    defaults
tensorflow                1.14.0          mkl_py37h085be34_0    defaults
tensorflow-base           1.14.0          mkl_py37h5a24fda_0    defaults
tensorflow-estimator      1.14.0                     py_0    defaults
termcolor                 1.1.0                    py37_1    defaults
terminado                 0.8.2                    py37_0    defaults
testpath                  0.4.2                    py37_0    defaults
theano                    1.0.4            py37h04f5b5a_0    defaults
tk                        8.6.8                ha441bb4_0    defaults
toolz                     0.10.0                     py_0    defaults
torchvision               0.4.0                  py37_cpu    pytorch
tornado                   6.0.3            py37h1de35cc_0    defaults
tqdm                      4.32.1                     py_0    defaults
traitlets                 4.3.2                    py37_0    defaults
unicodecsv                0.14.1                   py37_0    defaults
unixodbc                  2.3.7                h1de35cc_0    defaults
urllib3                   1.24.2                   py37_0    defaults
wcwidth                   0.1.7                    py37_0    defaults
webencodings              0.5.1                    py37_1    defaults
werkzeug                  0.15.4                     py_0    defaults
wheel                     0.33.4                   py37_0    defaults
widgetsnbextension        3.5.0                    py37_0    defaults
wrapt                     1.11.2           py37h1de35cc_0    defaults
wurlitzer                 1.0.2                    py37_0    defaults
xlrd                      1.2.0                    py37_0    defaults
xlsxwriter                1.1.8                      py_0    defaults
xlwings                   0.15.8                   py37_0    defaults
xlwt                      1.3.0                    py37_0    defaults
xz                        5.2.4                h1de35cc_4    defaults
yaml                      0.1.7                hc338f04_2    defaults
zeromq                    4.3.1                h0a44026_3    defaults
zict                      1.0.0                      py_0    defaults
zipp                      0.5.1                      py_0    defaults
zlib                      1.2.11               h1de35cc_3    defaults
zstd                      1.3.7                h5bba6e5_0    defaults
```

</details>

### Additional info

Tried uninstalling and reinstalling Anaconda, didn't work.

Tried uninstalling and reinstalling Xcode and Xcode command line tools, didn't work.

Tried compiling a C file directly, compiled without a hitch. Not a compiler error.

**Comment by kpasso1015** [comment]
Before Catalina OS(Mojave OS)

I resolved this error by tiping 

` open /Library/Developer/CommandLineTools/Packages/macOS_SDK_headers_for_macOS_10.14.pkg`
according to this issue (https://github.com/Theano/Theano/issues/6645)

However, now I can't find this pkg.
`/Library/Developer/CommandLineTools/Package` was disappeared.

**Comment by geoffsmith** [comment]
I worked around this by setting the CPATH env: ```export CPATH=`xcrun --show-sdk-path`/usr/include```. See here: https://apple.stackexchange.com/questions/372032/usr-include-missing-on-macos-catalina-with-xcode-11

**Comment by ApoorvDP** [comment]
Thanks Geoff, that worked instantly!

Still hope Anaconda adds the ability to handle this automatically, without needing to depend on the workaround.

**Comment by AndrewAnnex** [comment]
I am currently running into this issue, interestingly theano has been working for me on catalina but broke after running `xcode-select --install`

**Comment by trdavidson** [comment]
@AndrewAnnex - any update perhaps on something that did work?

**Comment by AndrewAnnex** [comment]
@trdavidson actually I figured out that this issue was, bizarrely, isolated to jupyter notebooks I was running within PyCharm. Even though pycharm was configured to use the same conda environment/jupyter kernel. Running jupyter outside of pycharm fixed the issue for me. I have no idea what would be particular to the pycharm environment but I could imagine that pycharm overrides some kind of environment state, either aliases or the path for example. I did not investigate it further however so these are only guesses

**Comment by trdavidson** [comment]
very odd indeed - thanks for the response! diving down the rabbit hole  a little myself, the following sequence worked in the end:  
1. `xcode-select --install`    
2. followed by the command in this stack post:
https://stackoverflow.com/a/58323411/3723434 . 
This is because tl;dr: apple messed with the /usr/ folder, and didn’t propogate change everywhere . 
  
3. To ensure that the header files needed to successfully run c/c++ programs (which often happens under the hood) are symlinked correctly, follow the following: 
 
`https://stackoverflow.com/a/58349403/3723434`

**Comment by klawson6** [comment]
Following @trdavidson solved my problem! Cheers!

**Comment by AndrewAnnex** [comment]
for those running into my issue with pycharm+anaconda+theano I think finally solved the issue after uninstalling all the theano/pymc3/pygpu related packages and then more or less following the procedure detailed here minus the windows specific parts https://github.com/Theano/Theano/issues/6654#issuecomment-518041103. 

it helps to use a terminal app outside of pycharm to double check things as there were different orders that caused the lazy linker error vs other obscure errors
