### ISSUE TITLE
Invalid Anaconda prompt and navigator does not run

### ISSUE THREAD

**Issue by mlauronen** [ContinuumIO/anaconda-issues#11365]
### Actual Behavior
I am following [these instructions](https://docs.anaconda.com/anaconda/install/windows/) and after successful installation I am trying to run the Anaconda Navigator. The Navigator does not start ie.  nothing happens when the icon is selected (found in Start menus). Anaconda Prompt does not work either (see conda info)

### Expected Behavior
Navigator should start

### Steps to Reproduce
Install and try the icon. Happens continuously.

##### Operating System:
Windows 10 Home

##### `conda info`
<details>
```
C:\Users\Käyttäjä\Anaconda3\Scripts>conda info

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "C:\Users\Käyttäjä\Anaconda3\lib\site-packages\conda\exceptions.py", line 1062, in __call__
        return func(*args, **kwargs)
      File "C:\Users\Käyttäjä\Anaconda3\lib\site-packages\conda\cli\main.py", line 84, in _main
        exit_code = do_call(args, p)
      File "C:\Users\Käyttäjä\Anaconda3\lib\site-packages\conda\cli\conda_argparse.py", line 80, in do_call
        module = import_module(relative_mod, __name__.rsplit('.', 1)[0])
      File "C:\Users\Käyttäjä\Anaconda3\lib\importlib\__init__.py", line 127, in import_module
        return _bootstrap._gcd_import(name[level:], package, level)
      File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
      File "<frozen importlib._bootstrap>", line 983, in _find_and_load
      File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
      File "<frozen importlib._bootstrap_external>", line 728, in exec_module
      File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
      File "C:\Users\Käyttäjä\Anaconda3\lib\site-packages\conda\cli\main_info.py", line 19, in <module>
        from ..core.index import _supplement_index_with_system
      File "C:\Users\Käyttäjä\Anaconda3\lib\site-packages\conda\core\index.py", line 9, in <module>
        from .package_cache_data import PackageCacheData
      File "C:\Users\Käyttäjä\Anaconda3\lib\site-packages\conda\core\package_cache_data.py", line 15, in <module>
        from conda_package_handling.api import InvalidArchiveError
      File "C:\Users\Käyttäjä\Anaconda3\lib\site-packages\conda_package_handling\api.py", line 3, in <module>
        from libarchive.exception import ArchiveError as _LibarchiveArchiveError
      File "C:\Users\Käyttäjä\Anaconda3\lib\site-packages\libarchive\__init__.py", line 1, in <module>
        from .entry import ArchiveEntry
      File "C:\Users\Käyttäjä\Anaconda3\lib\site-packages\libarchive\entry.py", line 6, in <module>
        from . import ffi
      File "C:\Users\Käyttäjä\Anaconda3\lib\site-packages\libarchive\ffi.py", line 48, in <module>
        libarchive = ctypes.cdll.LoadLibrary(libarchive_path)
      File "C:\Users\Käyttäjä\Anaconda3\lib\ctypes\__init__.py", line 434, in LoadLibrary
        return self._dlltype(name)
      File "C:\Users\Käyttäjä\Anaconda3\lib\ctypes\__init__.py", line 356, in __init__
        self._handle = _dlopen(self._name, mode)
    TypeError: LoadLibrary() argument 1 must be str, not None

`$ C:\Users\Käyttäjä\Anaconda3\Scripts\conda-script.py info`


An unexpected error has occurred. Conda has prepared the above report.

If submitted, this report will be used by core maintainers to improve
future releases of conda.
Would you like conda to send this report to the core maintainers?
```
</details>

##### `conda list --show-channel-urls`
<details>
```
Conda command does not work either. Please see above.

```
</details>

**Comment by mlauronen** [comment]
Can the application to handle the scandinavian characters in file name path names (look at my windows username) ?

**Comment by mlauronen** [comment]
btw. Anaconda Prompt (Anaconda3) does not work either. The command line windows is opened but the following happens:

(base) C:\Users\Käyttäjä>conda
'conda' is not recognized as an internal or external command,
operable program or batch file.

(base) C:\Users\Käyttäjä>

**Comment by mlauronen** [comment]
I found you recommend installing Anaconda or Miniconda into a directory that contains only 7-bit ASCII characters. This was the problem.
