### ISSUE TITLE
Nothing happens when clicking 'Open Terminal' on anaconda-navigator environment

### ISSUE THREAD

**Issue by brylie** [ContinuumIO/anaconda-issues#1139]
In Anaconda Navigator, clicking 'Open Terminal' (in the green arrow popup menu) produces no result.

![screenshot_20161006_095203](https://cloud.githubusercontent.com/assets/17307/19143145/9421a54a-8baa-11e6-959c-7a0bcfc88b4a.png)
# Expected result

Clicking on the 'Open Terminal' menu item would open a system terminal with the proper environment activated.
# Environment
- OS: Ubuntu 16.04
- Desktop: KDE Plasma 5.8.0

**Comment by goanpeca** [comment]
@brylie could you open navigator from the command line and see if there is any error output on the console when you execute that action?

**Comment by brylie** [comment]
@goanpeca OK. 

When starting anaconda-navigator, I get the following notice three times:

> libpng warning: iCCP: known incorrect sRGB profile

**Comment by brylie** [comment]
When clicking the 'Open Terminal' menu item, there is no output in the terminal.

**Comment by goanpeca** [comment]
You can safely ignore 

>libpng warning: iCCP: known incorrect sRGB profile

Hmmmm ok 

Could you type on the command line

`conda info`


`source activate orange`
`conda list`

And paste the result here?

**Comment by brylie** [comment]
Conda info: 

```
Current conda install:

               platform : linux-64
          conda version : 4.2.9
       conda is private : False
      conda-env version : 4.2.9
    conda-build version : 2.0.2
         python version : 3.5.2.final.0
       requests version : 2.11.1
       root environment : /home/brylie/anaconda3  (writable)
    default environment : /home/brylie/anaconda3
       envs directories : /home/brylie/anaconda3/envs
          package cache : /home/brylie/anaconda3/pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/linux-64/
                          https://repo.continuum.io/pkgs/free/noarch/
                          https://repo.continuum.io/pkgs/pro/linux-64/                                                                                                                                                                                                         
                          https://repo.continuum.io/pkgs/pro/noarch/                                                                                                                                                                                                           
            config file : None                                                                                                                                                                                                                                                 
           offline mode : False  
```

```
$ source activate Orange                                                                                                                                                                                                                               
(Orange):~$ conda list                                                                                                                                                                                                                                  
# packages in environment at /home/brylie/anaconda3/envs/Orange:                                                                                                                                                                                                               
#                                                                                                                                                                                                                                                                              
openssl                   1.0.2j                        0                                                                                                                                                                                                                      
pip                       8.1.2                    py35_0                                                                                                                                                                                                                      
python                    3.5.2                         0                                                                                                                                                                                                                      
readline                  6.2                           2                                                                                                                                                                                                                      
setuptools                27.2.0                   py35_0                                                                                                                                                                                                                      
sqlite                    3.13.0                        0                                                                                                                                                                                                                      
tk                        8.5.18                        0                                                                                                                                                                                                                      
wheel                     0.29.0                   py35_0                                                                                                                                                                                                                      
xz                        5.2.2                         0                                                                                                                                                                                                                      
zlib                      1.2.8                         3
```

**Comment by brylie** [comment]
I am able to `conda install Orange3` successfully.

I just didn't know how to activate the environment from the terminal. Likewise, the 'Open Terminal' menu item is not working.

**Comment by brylie** [comment]
Ah, dang it. I can't even run `orange-canvas` manually from the terminal:

```
$ orange-canvas 
Traceback (most recent call last):
  File "/home/brylie/anaconda3/envs/Orange/bin/orange-canvas", line 4, in <module>
    import Orange.canvas.__main__
  File "/home/brylie/anaconda3/envs/Orange/lib/python3.5/site-packages/Orange/canvas/__main__.py", line 24, in <module>
    from Orange.canvas.application.canvasmain import CanvasMainWindow
  File "/home/brylie/anaconda3/envs/Orange/lib/python3.5/site-packages/Orange/canvas/application/canvasmain.py", line 26, in <module>
    from PyQt4.QtWebKit import QWebView
ImportError: libQtWebKit.so.4: cannot open shared object file: No such file or directory
```

**Comment by brylie** [comment]
Conda can't find a package matching 'libqtwebkit':

```
$ anaconda search -t conda libqtwebkit
Using Anaconda API: https://api.anaconda.org
Run 'anaconda show <USER/PACKAGE>' to get more details:
No packages found
     Name                      |  Version | Package Types   | Platforms      
     ------------------------- |   ------ | --------------- | ---------------
Found 0 packages
```

**Comment by goanpeca** [comment]
@brylie your env shows a mismatch of qt and pyqt

```
pyqt                      4.11.4                   py35_3  
pyqtgraph                 0.9.10                   py35_1  
python                    3.5.2                         0  
qt                        5.6.0                         0  
```

For orange to work you need to have qt=4 and pyqt=4


`source activate orange`
`conda install pyqt=4 qt=4`

**Comment by brylie** [comment]
Thanks @goanpeca. It would be really useful, as an end user, if the installation would properly manage the dependencies. The steps to create a new environment and install Orange3 are error prone. 

Is there some middle ground solution, where the 'Install Orange3' button could be added back to the anaconda-navigator homescreen (e.g. clicking 'Install Orange3' would create a new environment, install Qt4, orange, etc)?

**Comment by goanpeca** [comment]
@brylie what you suggesst is exactly what we are working on for 1.4 :-)

**Comment by brylie** [comment]
Thanks @goanpeca 

Also, the original issue reported in this thread is still unresolved. I still cannot 'Open Terminal' from the anaconda-navigator, in KDE plasma 5.8.

**Comment by goanpeca** [comment]
Hi @brylie adding this to the next release milestone. Sorry for the delay.

**Comment by brylie** [comment]
All good. For what it's worth, the issue may be resolved already. At least in KDE, I am able now to open a terminal from within anaconda-navigator.

**Comment by goanpeca** [comment]
Great to hear that. I will close for now, but if anything similar happens, please feel free to reopen it

**Comment by brylie** [comment]
Thanks for your support @goanpeca

**Comment by unmeshbane** [comment]
the command line says 
(C:\Users\Unmesh\Anaconda3) C:\Users\Unmesh\Documents>source activate tensorflow
'source' is not recognized as an internal or external command,
operable program or batch file.
