### ISSUE TITLE
Navigator ErrorTraceback (most recent call last): File "C:\Users\DELL\Anaconda3\Scripts\jupyter-notebook-script.py", line 3, in  import notebook.notebookapp File "C:\Users\DELL\Anaconda3\lib\site-packages\notebook\notebookapp.py", line 74, in  from .services.kernels.kernelmanager import MappingKernelManager File "C:\Users\DELL\Anaconda3\lib\site-packages\notebook\services\kernels\kernelmanager.py", line 16, in  from jupyter_client.multikernelmanager import MultiKernelManager File "C:\Users\DELL\Anaconda3\lib\site-packages\jupyter_client\__init__.py", line 4, in  from .connect import * File "C:\Users\DELL\Anaconda3\lib\site-packages\jupyter_client\connect.py", line 35, in  from jupyter_core.paths import jupyter_data_dir, jupyter_runtime_dir, secure_write ImportError: cannot import name 'secure_write'

### ISSUE THREAD

**Issue by san-943** [ContinuumIO/anaconda-issues#11401]
## Main error
Application <b>notebook</b> launch may have produced errors.
## Traceback
```
Traceback (most recent call last):
  File "C:\Users\DELL\Anaconda3\Scripts\jupyter-notebook-script.py", line 3, in <module>
    import notebook.notebookapp
  File "C:\Users\DELL\Anaconda3\lib\site-packages\notebook\notebookapp.py", line 74, in <module>
    from .services.kernels.kernelmanager import MappingKernelManager
  File "C:\Users\DELL\Anaconda3\lib\site-packages\notebook\services\kernels\kernelmanager.py", line 16, in <module>
    from jupyter_client.multikernelmanager import MultiKernelManager
  File "C:\Users\DELL\Anaconda3\lib\site-packages\jupyter_client\__init__.py", line 4, in <module>
    from .connect import *
  File "C:\Users\DELL\Anaconda3\lib\site-packages\jupyter_client\connect.py", line 35, in <module>
    from jupyter_core.paths import jupyter_data_dir, jupyter_runtime_dir, secure_write
ImportError: cannot import name 'secure_write'

```
## System information
```
python: 3.6.1
language: en_US
os: Windows;10;10.0.17134;AMD64;Intel64 Family 6 Model 61 Stepping 4, GenuineIntel
version: 1.6.2
platform: win-64
qt: 5.6.2
pyqt: 5.6.0
conda: 4.3.21
```

**Comment by csoja** [comment]
Please update conda and anaconda-navigator to the latest version.
In the Anaconda Prompt:
_conda update conda
conda update anaconda-navigator
conda update navigator-updater_

If you are still seeing this issue after an update, please open a new bug report and provided all the information requested in the Github template.
