### ISSUE TITLE
An error occurred while starting the kernel

### ISSUE THREAD

**Issue by amrfodd** [ContinuumIO/anaconda-issues#11415]
An error occurred while starting the kernel The error is: Traceback (most recent call last): File "C: \ Users \ Amrfodd \ AppData \ Local \ Continuum \ anaconda3 \ lib \ site-packages \ spyder \ plugins \ ipythonconsole.py "line 1572, in create_kernel_manager_and_kernel_client kernel_manager.start_kernel (stderr = stderr_handle) File" C: \ Users \ Amrfodd \ AppData \ Roaming \ Python \ Python37 \ site-packages \ jupyter_client \ manager.py ", line 240, in start_kernel self. write_connection_file () File "C: \ Users \ Amrfodd \ AppData \ Roaming \ Python \ Python37 \ site-packages \ jupyter_client \ connect.py", line 476, in write_connection_file kernel_name = self.kernel_name File "C: \ Users \ Amrfodd \ AppData \ Roaming \ Python \ Python37 \ site-packages \ jupyter_client \ connect.py ", line 141, in write_connection_file with secure_write (fname) as f: File" C: \ Users \ Amrfodd \ AppData \ Local \ Continuum \ anaconda3 \ lib \ contextlib.py ", line 112, in __enter__ return next (self.gen) File" C: \ Users \ Amrfodd \ AppData \ Roaming \ Python \ Python37 \ site-packages \ jupyt er_core \ paths.py ", line 424, in secure_write win32_restrict_file_to_user (fname) File" C: \ Users \ Amrfodd \ AppData \ Roaming \ Python \ Python37 \ site-packages \ jupyter_core \ paths.py ", line 359, in win32_restrict_file_to_user import win32api ImportError: DLL load failed: The specified procedure could not be found.

i am using windows 64 bit 
i reinstalled it many times and it working for while then it gives me this.
i searched for a similar issue but no solution has solved the problem

**Comment by KingDarBoja** [comment]
@amrfodd Did you installed it on your virtual enviroment? I do have the same `ImportError: DLL load failed: The specified procedure could not be found.` error message and still no clue about why it is happening.

I followed [these steps](https://anbasile.github.io/programming/2017/06/25/jupyter-venv/) to add jupyter for my venv but looks like it doesn't work.

**Comment by BulaZim** [comment]
I have just had same issue. Not running from Virtual Env. Have tried various things set out here https://github.com/ContinuumIO/anaconda-issues/issues/10079
(uninstalling obvs, upgrading jupyter, adding Anaconda to PATH etc) to no avail

though I see noted here (https://github.com/jupyter/notebook/issues/4332) that there is issue with 64 bit anaconda

**Comment by KingDarBoja** [comment]
@BulaZim I am using Windows 10 x64 and had to uninstall all Python-related stuff (registry, applications, enviroments) and used CCleaner to eliminate any remaining registry. Also, don't forget to delete them from `username/Program Data/local` and all those folders.

After that, reboot and make a clean install of Python by using Anaconda only. After finishing, reboot again and try Jupyter once again, it should work :) 

My previous workaround didn't work for too long so better to clean everything and avoid messing with dll files at all costs. I suggest using enviroments per Python project to avoid crashing the default enviroment (base).
