### ISSUE TITLE
space in user name trips up ipykernel post-link script

### ISSUE THREAD

**Issue by PatWong99** [ContinuumIO/anaconda-issues#11421]
I have scikit-learn version 0.20.3 installed and I wanted to install the latest version.

I originally did this on the command line with `conda update scikit-learn`. But this failed to update scikit-learn AND screwed up my matplotlib which was at version 3.0.3. Whenever I run the command `import matplotlib.pylot` this error comes up:
`"ModuleNotFoundError: No module named 'matplotlib.pyplot"`

So I tried updating both these packages to their latest versions. 3.1.1 for matplotlib and 0.21.3 for scikit-learn via anaconda navigator. However, the screen is stuck on "the following packages will be modified | solving package specifications"

When I run "python" on the anaconda powershell prompt I'm getting this issue:

```
Error processing line 1 of C:\ProgramData\Anaconda3\lib\site-packages\matplotlib-3.0.3-py3.7-nspkg.pth:
  Traceback (most recent call last):
    File "C:\ProgramData\Anaconda3\lib\site.py", line 168, in addpackage
      exec(line)
    File "<string>", line 1, in <module>
    File "<frozen importlib._bootstrap>", line 580, in module_from_spec
  AttributeError: 'NoneType' object has no attribute 'loader'

Remainder of file ignored
```
I've tried uninstall matplotlib. When I do this in anaconda nothing happens. When I do this using `conda remove matplotlib` I get this error:
```
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
ERROR conda.core.link:_execute(700): An error occurred while installing package 'defaults::ipykernel-5.1.3-py37h39e3cac_0'.
Rolling back transaction: done

LinkError: post-link script failed for package defaults::ipykernel-5.1.3-py37h39e3cac_0
location of failed script: C:\ProgramData\Anaconda3\Scripts\.ipykernel-post-link.bat
==> script messages <==
<None>
==> script output <==
stdout:
stderr: Access is denied.
Access is denied.
The system cannot find the file C:\Users\Patrick.
Could Not Find C:\Users\Patrick Wong\AppData\Local\Temp\conda-24308-26134.tmp

return code: 1
```

##### Operating System:
Windows 10

##### `conda info`
```
     active environment : base
    active env location : C:\ProgramData\Anaconda3
            shell level : 1
       user config file : C:\Users\Patrick Wong\.condarc
 populated config files : C:\Users\Patrick Wong\.condarc
          conda version : 4.7.12
    conda-build version : 3.17.8
         python version : 3.7.3.final.0
       virtual packages : __cuda=10.1
       base environment : C:\ProgramData\Anaconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\ProgramData\Anaconda3\pkgs
                          C:\Users\Patrick Wong\.conda\pkgs
                          C:\Users\Patrick Wong\AppData\Local\conda\conda\pkgs
       envs directories : C:\ProgramData\Anaconda3\envs
                          C:\Users\Patrick Wong\.conda\envs
                          C:\Users\Patrick Wong\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.7.12 requests/2.21.0 CPython/3.7.3 Windows/10 Windows/10.0.18362
          administrator : False
             netrc file : None
           offline mode : False
```

**Comment by leehanchung** [comment]
Having the exact same problem.

```
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
ERROR conda.core.link:_execute(700): An error occurred while installing package 'defaults::ipykernel-5.1.3-py37h39e3cac_0'.
Rolling back transaction: done

LinkError: post-link script failed for package defaults::ipykernel-5.1.3-py37h39e3cac_0
location of failed script: B:\user\miniconda\Scripts\.ipykernel-post-link.bat
==> script messages <==
<None>
==> script output <==
stdout:
stderr: Access is denied.
Access is denied.
The system cannot find the file C:\Users\Han-chung.
Could Not Find C:\Users\Han-chung Lee\AppData\Local\Temp\conda-18727-445.tmp

return code: 1

()

(base) PS B:\user> conda info                                                                                
     active environment : base
    active env location : B:\user\miniconda
            shell level : 1
       user config file : C:\Users\Han-chung Lee\.condarc
 populated config files :
          conda version : 4.7.12
    conda-build version : not installed
         python version : 3.7.4.final.0
       virtual packages : __cuda=10.1
       base environment : B:\user\miniconda  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : B:\user\miniconda\pkgs
                          C:\Users\Han-chung Lee\.conda\pkgs
                          C:\Users\Han-chung Lee\AppData\Local\conda\conda\pkgs
       envs directories : B:\user\miniconda\envs
                          C:\Users\Han-chung Lee\.conda\envs
                          C:\Users\Han-chung Lee\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.7.12 requests/2.22.0 CPython/3.7.4 Windows/10 Windows/10.0.18362
          administrator : False
             netrc file : C:\Users\Han-chung Lee/.netrc
           offline mode : False
```

**Comment by raymustafa** [comment]
Same problem

**Comment by sumedha19129** [comment]
I am facing the exact problem

**Comment by xandrade** [comment]
Gosh, what is going on? same issue here

**Comment by wangbowenll** [comment]
same issue!!!   i feel crash

**Comment by Douglas-Klos** [comment]
Also experiencing this issue when trying to update anaconda on Windows 10.
Google search for [ERROR conda.core.link:_execute(700): An error occurred while installing package 'defaults::ipykernel-5.1.3-py37h39e3cac_0'.] led me here.

**Comment by anttir** [comment]
same, trying to update basically any package fails because 
 conda.core.link:_execute(700): An error occurred while installing package 'defaults::ipykernel-5.1.3-py37h39e3cac_0'
running on Win10

**Comment by msarahan** [comment]
This appears to be related to spaces in your install path.  Your user name is split by one or more space characters, and the post-link script is not behaving correctly there.  The post-link script was a workaround for another bug, and has been removed in the conda-forge upstream recipe.  We will adopt that change and produce new packages.  Look for build number 1 in an hour or so.

**Comment by msarahan** [comment]
New packages are up.  If this fixes the issue for you, please close this issue, or comment here so that we can close it.
