### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by Prashantmdgl9** [ContinuumIO/anaconda-issues#11429]
## Main error
Application <b>qtconsole</b> launch may have produced errors.
## Traceback
```
Traceback (most recent call last):
  File "/Users/prashantmudgal/anaconda/bin/jupyter-qtconsole", line 4, in <module>
    import qtconsole.qtconsoleapp
  File "/Users/prashantmudgal/anaconda/lib/python3.6/site-packages/qtconsole/qtconsoleapp.py", line 64, in <module>
    from qtconsole.jupyter_widget import JupyterWidget
  File "/Users/prashantmudgal/anaconda/lib/python3.6/site-packages/qtconsole/jupyter_widget.py", line 19, in <module>
    from IPython.lib.lexers import IPythonLexer, IPython3Lexer
  File "/Users/prashantmudgal/anaconda/lib/python3.6/site-packages/IPython/__init__.py", line 49, in <module>
    from .terminal.embed import embed
  File "/Users/prashantmudgal/anaconda/lib/python3.6/site-packages/IPython/terminal/embed.py", line 18, in <module>
    from IPython.terminal.interactiveshell import TerminalInteractiveShell
  File "/Users/prashantmudgal/anaconda/lib/python3.6/site-packages/IPython/terminal/interactiveshell.py", line 20, in <module>
    from prompt_toolkit.shortcuts import create_prompt_application, create_eventloop, create_prompt_layout, create_output
ImportError: cannot import name 'create_prompt_application'

```
## System information
```
python: 3.6.9
language: en
os: Darwin;19.0.0;Darwin Kernel Version 19.0.0: Thu Oct 17 16:17:15 PDT 2019; root:xnu-6153.41.3~29/RELEASE_X86_64;x86_64;i386
version: 1.6.2
platform: osx-64
qt: 5.6.2
pyqt: 5.6.0
conda: 4.7.12
```

**Comment by Sharolyn** [comment]
I have the same issue.  Is there a workaround?

**Comment by csoja** [comment]
It looks like you have an old version of Anaconda-Navigator installed.  Please update to the latest.
_conda update conda
conda update anaconda-navigator
conda update navigator-updater_

One workaround is that you can launch qtconsole from the Anaconda Prompt on Windows or from a terminal on macOS.
_jupyter qtconsole_
