### ISSUE TITLE
Anaconda Error when installing R in windows 10

### ISSUE THREAD

**Issue by zixiliuUSC** [ContinuumIO/anaconda-issues#11434]
### Traceback

Traceback (most recent call last):
  File "C:\Users\Ou Zixi\Anaconda3\lib\site-packages\anaconda_navigator\exceptions.py", line 75, in exception_handler
    return_value = func(*args, **kwargs)
  File "C:\Users\Ou Zixi\Anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 151, in start_app
    window = run_app(splash)
  File "C:\Users\Ou Zixi\Anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 65, in run_app
    window = MainWindow(splash=splash, tab_project=False)
  File "C:\Users\Ou Zixi\Anaconda3\lib\site-packages\anaconda_navigator\widgets\main_window.py", line 168, in __init__
    self.api = AnacondaAPI()
  File "C:\Users\Ou Zixi\Anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 2337, in AnacondaAPI
    ANACONDA_API = _AnacondaAPI()
  File "C:\Users\Ou Zixi\Anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 89, in __init__
    self._conda_api = CondaAPI()
  File "C:\Users\Ou Zixi\Anaconda3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 1773, in CondaAPI
    CONDA_API = _CondaAPI()
  File "C:\Users\Ou Zixi\Anaconda3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 353, in __init__
    self.sys_rc_path = join(self.ROOT_PREFIX, '.condarc')
  File "C:\Users\Ou Zixi\Anaconda3\lib\ntpath.py", line 76, in join
    path = os.fspath(path)
TypeError: expected str, bytes or os.PathLike object, not NoneType

### Anaconda or Miniconda version:

I don't know the conda version now since the conda prompt also gets broken. 

### Operating System:
Windows 10 18362.418
lan: Chinese

### Additional info
I try to install R in conda navigator but the program get stuck and computer crash.

**Comment by csoja** [comment]
Looks like your .condarc file has gotten corrupted.  This troubleshooting section in the docs should help you get past it: https://docs.anaconda.com/anaconda/navigator/troubleshooting/#navigator-error-on-start-up
