### ISSUE TITLE
Anaconda Navigator won't open 

### ISSUE THREAD

**Issue by RedbusCanoe** [ContinuumIO/anaconda-issues#11440]
### Actual Behavior

Anaconda Navigator doesn't open.
The Navigator splash screen green circle appears for a while and then a new tab in my browsers opens telling me "An unexpected error occurred on Navigator start-up" and to report the issue here.

Main Error

module 'binstar_client.utils' has no attribute 'get_server_api'
Traceback

Traceback (most recent call last):
  File "/Applications/Anaconda/anaconda/lib/python3.5/site-packages/anaconda_navigator/exceptions.py", line 75, in exception_handler
    return_value = func(*args, **kwargs)
  File "/Applications/Anaconda/anaconda/lib/python3.5/site-packages/anaconda_navigator/app/start.py", line 138, in start_app
    window = run_app(splash)
  File "/Applications/Anaconda/anaconda/lib/python3.5/site-packages/anaconda_navigator/app/start.py", line 64, in run_app
    window = MainWindow(splash=splash, tab_project=False)
  File "/Applications/Anaconda/anaconda/lib/python3.5/site-packages/anaconda_navigator/widgets/main_window.py", line 163, in __init__
    self.api = AnacondaAPI()
  File "/Applications/Anaconda/anaconda/lib/python3.5/site-packages/anaconda_navigator/api/anaconda_api.py", line 2127, in AnacondaAPI
    ANACONDA_API = _AnacondaAPI()
  File "/Applications/Anaconda/anaconda/lib/python3.5/site-packages/anaconda_navigator/api/anaconda_api.py", line 90, in __init__
    self._client_api = ClientAPI()
  File "/Applications/Anaconda/anaconda/lib/python3.5/site-packages/anaconda_navigator/api/client_api.py", line 638, in ClientAPI
    CLIENT_API = _ClientAPI()
  File "/Applications/Anaconda/anaconda/lib/python3.5/site-packages/anaconda_navigator/api/client_api.py", line 93, in __init__
    self.reload_binstar_client()
  File "/Applications/Anaconda/anaconda/lib/python3.5/site-packages/anaconda_navigator/api/client_api.py", line 307, in reload_binstar_client
    binstar = binstar_client.utils.get_server_api(
AttributeError: module 'binstar_client.utils' has no attribute 'get_server_api'

### Expected Behavior

Anaconda Navigator starts properly

### Steps to Reproduce

double clicking on the anaconda-navigator icon

##### Anaconda or Miniconda version:

no idea.

##### Operating System:

MacOS 10.15.1

##### `conda info`

<details>

```
active environment : None
       user config file : /Users/peternisbet-jones/.condarc
 populated config files : /Users/peternisbet-jones/.condarc
          conda version : 4.5.11
    conda-build version : 1.18.1
         python version : 3.5.4.final.0
       base environment : /Applications/Anaconda/anaconda  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/osx-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/osx-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/osx-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/osx-64
                          https://repo.anaconda.com/pkgs/pro/noarch
          package cache : /Applications/Anaconda/anaconda/pkgs
                          /Users/peternisbet-jones/.conda/pkgs
       envs directories : /Applications/Anaconda/anaconda/envs
                          /Users/peternisbet-jones/.conda/envs
               platform : osx-64
             user-agent : conda/4.5.11 requests/2.12.4 CPython/3.5.4 Darwin/19.0.0 OSX/10.15.1
                UID:GID : 501:20
             netrc file : None
           offline mode : False

```

</details>

##### `conda list --show-channel-urls`

<details>

```
# packages in environment at /Applications/Anaconda/anaconda:
#
# Name                    Version                   Build  Channel
abstract-rendering        0.5.1               np110py35_0    defaults
alabaster                 0.7.7                    py35_0    defaults
anaconda                  custom                   py35_0    defaults
anaconda-client           1.1.0                    py35_0    defaults
anaconda-navigator        1.8.4                    py35_0    defaults
anaconda-project          0.8.4                      py_0    defaults
appnope                   0.1.0                    py35_0    defaults
appscript                 1.0.1                    py35_0    defaults
argcomplete               1.0.0                    py35_1    defaults
astropy                   1.0.5               np110py35_1    defaults
babel                     2.3.3                    py35_0    defaults
beautifulsoup4            4.4.1                    py35_0    defaults
bitarray                  0.8.1                    py35_0    defaults
blaze-core                0.8.3                    py35_0    defaults
bokeh                     0.10.0                   py35_0    defaults
boto                      2.38.0                   py35_0    defaults
cffi                      1.5.2                    py35_0    defaults
chardet                   3.0.4                    py35_1    defaults
clyent                    0.4.0                    py35_0    defaults
colorama                  0.3.3                    py35_0    defaults
conda                     4.5.11                   py35_0    defaults
conda-build               1.18.1                   py35_0    defaults
conda-env                 2.6.0                         1    defaults
configobj                 5.0.6                    py35_0    defaults
cryptography              1.4                      py35_0    defaults
curl                      7.45.0                        0    defaults
cycler                    0.9.0                    py35_0    defaults
cython                    0.23.4                   py35_0    defaults
cytoolz                   0.7.4                    py35_0    defaults
datashape                 0.4.7               np110py35_1    defaults
decorator                 4.0.9                    py35_0    defaults
docutils                  0.12                     py35_0    defaults
entrypoints               0.2                      py35_1    defaults
fastcache                 1.0.2                    py35_0    defaults
flask                     0.10.1                   py35_1    defaults
freetype                  2.5.5                         0    defaults
greenlet                  0.4.9                    py35_0    defaults
h5py                      2.5.0               np110py35_4    defaults
hdf5                      1.8.15.1                      2    defaults
idna                      2.0                      py35_0    defaults
imagesize                 0.7.0                    py35_0    defaults
ipykernel                 4.3.1                    py35_0    defaults
ipython                   4.1.2                    py35_2    defaults
ipython-notebook          4.0.4                    py35_0    defaults
ipython-qtconsole         4.0.1                    py35_0    defaults
ipython_genutils          0.1.0                    py35_0    defaults
ipywidgets                4.1.0                    py35_0    defaults
itsdangerous              0.24                     py35_0    defaults
jdcal                     1.0                      py35_0    defaults
jedi                      0.9.0                    py35_0    defaults
jinja2                    2.8                      py35_0    defaults
jpeg                      8d                            1    defaults
jsonschema                2.4.0                    py35_0    defaults
jupyter                   1.0.0                    py35_0    defaults
jupyter_client            4.2.2                    py35_0    defaults
jupyter_console           4.0.3                    py35_0    defaults
jupyter_core              4.1.0                    py35_0    defaults
launcher                  1.0.0                         3    defaults
libpng                    1.6.17                        0    defaults
libtiff                   4.0.6                         0    defaults
libxml2                   2.9.2                         0    defaults
libxslt                   1.1.28                        2    defaults
lmfit                     0.9.3                     <pip>
lxml                      3.4.4                    py35_0    defaults
markupsafe                0.23                     py35_0    defaults
matplotlib                1.5.1               np110py35_0    defaults
mistune                   0.7.2                    py35_1    defaults
mpmath                    0.19                     py35_0    defaults
multipledispatch          0.4.8                    py35_0    defaults
nbconvert                 4.2.0                    py35_0    defaults
nbformat                  4.0.1                    py35_0    defaults
networkx                  1.10                     py35_0    defaults
nltk                      3.1                      py35_0    defaults
node-webkit               0.10.1                        0    defaults
nose                      1.3.7                    py35_0    defaults
notebook                  4.0.6                    py35_0    defaults
numexpr                   2.4.4               np110py35_0    defaults
numpy                     1.10.2                   py35_0    defaults
odo                       0.3.4                    py35_0    defaults
openpyxl                  2.2.6                    py35_0    defaults
openssl                   1.0.2g                        0    defaults
pandas                    0.17.0              np110py35_0    defaults
path.py                   8.2                      py35_0    defaults
patsy                     0.4.0               np110py35_0    defaults
pep8                      1.7.0                    py35_0    defaults
pexpect                   4.0.1                    py35_0    defaults
pickleshare               0.5                      py35_0    defaults
pillow                    3.0.0                    py35_1    defaults
pip                       8.1.1                    py35_1    defaults
ply                       3.8                      py35_0    defaults
psutil                    4.1.0                    py35_1    defaults
ptyprocess                0.5                      py35_0    defaults
py                        1.4.30                   py35_0    defaults
pyasn1                    0.1.9                    py35_0    defaults
pycosat                   0.6.3            py35h745f8c1_0    defaults
pycparser                 2.14                     py35_0    defaults
pycrypto                  2.6.1                    py35_0    defaults
pycurl                    7.19.5.1                 py35_3    defaults
pyflakes                  1.1.0                    py35_0    defaults
pygments                  2.1.3                    py35_0    defaults
pyopenssl                 16.2.0                   py35_0    defaults
pyparsing                 2.0.3                    py35_0    defaults
pyqt                      4.11.4                   py35_1    defaults
pytables                  3.2.2               np110py35_0    defaults
pytest                    2.8.1                    py35_0    defaults
python                    3.5.4                         0    defaults
python-dateutil           2.4.2                    py35_0    defaults
python.app                1.2                      py35_4    defaults
pytz                      2016.3                   py35_0    defaults
pyyaml                    3.11                     py35_1    defaults
pyzmq                     15.2.0                   py35_0    defaults
qt                        4.8.7                         1    defaults
qtconsole                 4.2.1                    py35_0    defaults
qtpy                      1.9.0                      py_0    defaults
readline                  6.2                           2    defaults
redis                     2.6.9                         0    defaults
redis-py                  2.10.3                   py35_0    defaults
requests                  2.12.4                   py35_0    defaults
rope                      0.9.4                    py35_1    defaults
ruamel_yaml               0.11.14                  py35_1    defaults
scikit-image              0.11.3              np110py35_0    defaults
scikit-learn              0.16.1              np110py35_0    defaults
scipy                     0.16.0              np110py35_1    defaults
setuptools                20.7.0                   py35_0    defaults
simplegeneric             0.8.1                    py35_0    defaults
sip                       4.16.9                   py35_0    defaults
six                       1.10.0                   py35_0    defaults
snowballstemmer           1.2.1                    py35_0    defaults
sockjs-tornado            1.0.1                    py35_0    defaults
sphinx                    1.4.1                    py35_0    defaults
sphinx_rtd_theme          0.1.9                    py35_0    defaults
spyder                    2.3.8                    py35_1    defaults
spyder-app                2.3.8                    py35_0    defaults
sqlalchemy                1.0.9                    py35_0    defaults
sqlite                    3.13.0                        0    defaults
statsmodels               0.6.1               np110py35_0    defaults
sympy                     0.7.6.1                  py35_0    defaults
terminado                 0.5                      py35_1    defaults
tk                        8.5.18                        0    defaults
toolz                     0.7.4                    py35_0    defaults
tornado                   4.3                      py35_0    defaults
traitlets                 4.2.1                    py35_0    defaults
ujson                     1.33                     py35_0    defaults
unicodecsv                0.14.1                   py35_0    defaults
werkzeug                  0.10.4                   py35_0    defaults
wheel                     0.29.0                   py35_0    defaults
xlrd                      0.9.4                    py35_0    defaults
xlsxwriter                0.7.7                    py35_0    defaults
xlwings                   0.4.1                    py35_0    defaults
xlwt                      1.0.0                    py35_0    defaults
xz                        5.2.2                         0    defaults
yaml                      0.1.6                         0    defaults
zeromq                    4.1.3                         0    defaults
zlib                      1.2.8                         0    defaults

```

</details>

**Comment by csoja** [comment]
Have you tried this?  https://docs.anaconda.com/anaconda/navigator/troubleshooting/#navigator-error-on-start-up

**Comment by RedbusCanoe** [comment]
I stupidly didn't write down exactly what I tried, but I believe I did try that fix.  I had a bunch of other issues as well - disappearing libraries etc - so in the end I just un/reinstalled anaconda completely and that fixed everything.  I think it was initially caused when I upgraded my mac to Catalina.

**Comment by csoja** [comment]
I'm glad to hear everything is working for you now.  Catalina has caused quite a bit of trouble for Anaconda users: https://www.anaconda.com/how-to-restore-anaconda-after-macos-catalina-update/
