### ISSUE TITLE
anaconda unwant open the program too miniconda

### ISSUE THREAD

**Issue by Azaretdodo** [ContinuumIO/anaconda-issues#11459]
(when I want to open anaconda3)
Main Error
expected str, bytes or os.PathLike object, not NoneType
Traceback
Traceback (most recent call last):
  File "C:\Users\doria\Anaconda3\lib\site-packages\anaconda_navigator\exceptions.py", line 75, in exception_handler
    return_value = func(*args, **kwargs)
  File "C:\Users\doria\Anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 151, in start_app
    window = run_app(splash)
  File "C:\Users\doria\Anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 65, in run_app
    window = MainWindow(splash=splash, tab_project=False)
  File "C:\Users\doria\Anaconda3\lib\site-packages\anaconda_navigator\widgets\main_window.py", line 168, in __init__
    self.api = AnacondaAPI()
  File "C:\Users\doria\Anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 2337, in AnacondaAPI
    ANACONDA_API = _AnacondaAPI()
  File "C:\Users\doria\Anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 89, in __init__
    self._conda_api = CondaAPI()
  File "C:\Users\doria\Anaconda3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 1767, in CondaAPI
    CONDA_API = _CondaAPI()
  File "C:\Users\doria\Anaconda3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 353, in __init__
    self.sys_rc_path = join(self.ROOT_PREFIX, '.condarc')
  File "C:\Users\doria\Anaconda3\lib\ntpath.py", line 76, in join
    path = os.fspath(path)
TypeError: expected str, bytes or os.PathLike object, not NoneType

(when I want to open miniconda)
Le chemin d’accès spécifié est introuvable.
C:\Users\doria>

(when I want to open anaconda prompt)
ConfigurationLoadError: Unable to load configuration file.
  path: C:\Users\doria\.condarc
  reason: invalid yaml at position 0
C:\Users\doria>

**Comment by csoja** [comment]
https://docs.anaconda.com/anaconda/navigator/troubleshooting/#navigator-error-on-start-up

**Comment by Azaretdodo** [comment]
The error keep because I can't have a conda working and I don't find condarc !!!

![CondaProgramDoes,'tInstalled](https://user-images.githubusercontent.com/30596513/69144553-d36d0e80-0acb-11ea-84c4-d8c7ce7e3596.jpg)
![StartButtonCondaInstalledButUnworks](https://user-images.githubusercontent.com/30596513/69144584-e54eb180-0acb-11ea-95af-71dc770515a2.jpg)


Thank you in advance to bring me a conda and anaconda working,

Regards.


Azaretdodo.

**Comment by msarahan** [comment]
Conda doesn't work from a standard cmd.exe by default. You need to use
anaconda prompt in your start menu. If you want conda to work outside of
anaconda prompt, you can run the "conda init" command in anaconda prompt.
Any new shells from then will have conda available.

Crystal's advice regarding the .condarc file is very important. It may be a
hidden file. Look in your user home folder for both condarc and .condarc,
and be sure that all hidden files are shown.

**Comment by Azaretdodo** [comment]
Conda unwork to on anaconda prompt

I have install conda GitHub

I have try the conda command line install

I have install menuinst GitHub missing by conda GitHub

Finaly after the conda GitHub install conda is install broken but it answer something other than a conda 0 percent installer...

I don't know what I must do now

Thank you in advance to help me become a anaconda and mini conda works,

Retards.


Azaretdodo.

Télécharger Outlook pour Android<https://aka.ms/ghei36>
________________________________

**Comment by Azaretdodo** [comment]
I wento to install this github :

https://github.com/Anaconda-Platform/anaconda-client

I have folllown the tutorial,

The installing doesn't happen error but because conda is broken I keep error when I open anaconda navigator,

I think by my side now I don't have other must to do,

Thank you in advance to help me repair anaconda and conda,

Regards.


Azaretdodo.
