### ISSUE TITLE
Issue running Python kernel in Jupyter (lab, notebook) on macOS, present since about August

### ISSUE THREAD

**Issue by mg4news** [ContinuumIO/anaconda-issues#11470]
### Actual Behavior
I use miniconda on Linux and macOS. Since about August, the updates to conda packages break my Jupyter installation on macOS ONLY. The only way for me to keep working is to roll back to an old installation from July or earlier (4.7.10 seems to work). Of course the issue with this is that I cant use current packages, like TensorFlow 2.0.0. 

The issue is one that has been reported many times as a Jupyter issue, an attribute error on launching the kernel. I found a lot of references to incompatibilities with Tornado, but cannot find a combination of versions that work for me. 

I have completely removed my installation a number of times, reinstalled from scratch, and still get the same issue.

This only happens on macOS, an identical installation on Linux Mint works fine. When I compare the versions of both installs, all the common files have the same version. 

Jupiter lab (and notebook) launch fine. As soon as I try to open a notebook with a Python kernel I get the following:

``` 
[W 11:08:16.829 LabApp] Replacing stale connection: 707630ab-9aac-445e-80b5-84e5217990b3:6144ae34-a72c-449f-9822-628aed91cf9d
[I 11:08:25.827 LabApp] Adapting from protocol version 5.1 (kernel 707630ab-9aac-445e-80b5-84e5217990b3) to 5.3 (client).
[E 11:08:25.828 LabApp] Uncaught exception GET /api/kernels/707630ab-9aac-445e-80b5-84e5217990b3/channels?session_id=68cd21ab-fe03-4cc8-b878-e82a61630136&token=7e944932807a858b10c74830b284cd8e88977f32501cce60 (::1)
    HTTPServerRequest(protocol='http', host='localhost:8888', method='GET', uri='/api/kernels/707630ab-9aac-445e-80b5-84e5217990b3/channels?session_id=68cd21ab-fe03-4cc8-b878-e82a61630136&token=7e944932807a858b10c74830b284cd8e88977f32501cce60', version='HTTP/1.1', remote_ip='::1')
    Traceback (most recent call last):
      File "/Users/martin/.local/lib/python3.7/site-packages/tornado/websocket.py", line 956, in _accept_connection
        open_result = handler.open(*handler.open_args, **handler.open_kwargs)
      File "/Users/martin/miniconda3/envs/env_tf2/lib/python3.7/site-packages/notebook/services/kernels/handlers.py", line 274, in open
        self.create_stream()
      File "/Users/martin/miniconda3/envs/env_tf2/lib/python3.7/site-packages/notebook/services/kernels/handlers.py", line 127, in create_stream
        meth = getattr(km, 'connect_' + channel)
    AttributeError: 'MappingKernelManager' object has no attribute 'connect_control'
```

### Expected Behavior
Kernel should start, the notebook should be editable and usable. 

### Steps to Reproduce
On macOS:
- install miniconda
- install jupyterlab
- open jupyterlab
- create a Python based notebook

##### Anaconda or Miniconda version:
Miniconda 4.7.12
##### Operating System:
macOS Catalina (but this happened before the update to Catalina)

##### `conda info`

<details>

```
     active environment : env_tf2
    active env location : /Users/martin/miniconda3/envs/env_tf2
            shell level : 2
       user config file : /Users/martin/.condarc
 populated config files : 
          conda version : 4.7.12
    conda-build version : not installed
         python version : 3.7.3.final.0
       virtual packages : 
       base environment : /Users/martin/miniconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/osx-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/osx-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /Users/martin/miniconda3/pkgs
                          /Users/martin/.conda/pkgs
       envs directories : /Users/martin/miniconda3/envs
                          /Users/martin/.conda/envs
               platform : osx-64
             user-agent : conda/4.7.12 requests/2.21.0 CPython/3.7.3 Darwin/19.0.0 OSX/10.15.1
                UID:GID : 501:20
             netrc file : None
           offline mode : False
```

</details>

##### `conda list --show-channel-urls`

<details>

```
_tflow_select             2.3.0                       mkl    defaults
absl-py                   0.8.1                    py37_0    defaults
appnope                   0.1.0                    py37_0    defaults
asn1crypto                1.2.0                    py37_0    defaults
astor                     0.8.0                    py37_0    defaults
attrs                     19.3.0                     py_0    defaults
backcall                  0.1.0                    py37_0    defaults
blas                      1.0                         mkl    defaults
bleach                    3.1.0                    py37_0    defaults
c-ares                    1.15.0            h1de35cc_1001    defaults
ca-certificates           2019.10.16                    0    defaults
certifi                   2019.9.11                py37_0    defaults
cffi                      1.13.2           py37hb5b8e2f_0    defaults
chardet                   3.0.4                 py37_1003    defaults
cryptography              2.8              py37ha12b0ac_0    defaults
decorator                 4.4.1                      py_0    defaults
defusedxml                0.6.0                      py_0    defaults
dill                      0.3.1.1                  py37_0    defaults
entrypoints               0.3                      py37_0    defaults
future                    0.18.2                   py37_0    defaults
gast                      0.2.2                    py37_0    defaults
google-pasta              0.1.8                      py_0    defaults
googleapis-common-protos  1.6.0                    py37_0    defaults
grpcio                    1.16.1           py37h044775b_1    defaults
h5py                      2.9.0            py37h3134771_0    defaults
hdf5                      1.10.4               hfa1e0ec_0    defaults
idna                      2.8                      py37_0    defaults
importlib_metadata        0.23                     py37_0    defaults
intel-openmp              2019.4                      233    defaults
ipykernel                 5.1.3            py37h39e3cac_0    defaults
ipython                   7.9.0            py37h39e3cac_0    defaults
ipython_genutils          0.2.0                    py37_0    defaults
jedi                      0.15.1                   py37_0    defaults
jinja2                    2.10.3                     py_0    defaults
json5                     0.8.5                      py_0    defaults
jsonschema                3.2.0                    py37_0    defaults
jupyter_client            5.3.4                    py37_0    defaults
jupyter_core              4.6.1                    py37_0    defaults
jupyterlab                1.2.3              pyhf63ae98_0    defaults
jupyterlab_server         1.0.6                      py_0    defaults
keras-applications        1.0.8                      py_0    defaults
keras-preprocessing       1.1.0                      py_1    defaults
libcxx                    4.0.1                hcfea43d_1    defaults
libcxxabi                 4.0.1                hcfea43d_1    defaults
libedit                   3.1.20181209         hb402a30_0    defaults
libffi                    3.2.1                h475c297_4    defaults
libgfortran               3.0.1                h93005f0_2    defaults
libprotobuf               3.10.1               hd9629dc_0    defaults
libsodium                 1.0.16               h3efe00b_0    defaults
markdown                  3.1.1                    py37_0    defaults
markupsafe                1.1.1            py37h1de35cc_0    defaults
mistune                   0.8.4            py37h1de35cc_0    defaults
mkl                       2019.4                      233    defaults
mkl-service               2.3.0            py37hfbe908c_0    defaults
mkl_fft                   1.0.15           py37h5e564d8_0    defaults
mkl_random                1.1.0            py37ha771720_0    defaults
more-itertools            7.2.0                    py37_0    defaults
nbconvert                 5.6.1                    py37_0    defaults
nbformat                  4.4.0                    py37_0    defaults
ncurses                   6.1                  h0a44026_1    defaults
notebook                  6.0.2                    py37_0    defaults
numpy                     1.17.3           py37h4174a10_0    defaults
numpy-base                1.17.3           py37h6575580_0    defaults
openssl                   1.1.1d               h1de35cc_3    defaults
opt_einsum                3.1.0                      py_0    defaults
pandoc                    2.2.3.2                       0    defaults
pandocfilters             1.4.2                    py37_1    defaults
parso                     0.5.1                      py_0    defaults
pexpect                   4.7.0                    py37_0    defaults
pickleshare               0.7.5                    py37_0    defaults
pip                       19.3.1                   py37_0    defaults
prometheus_client         0.7.1                      py_0    defaults
promise                   2.2.1                    py37_0    defaults
prompt_toolkit            2.0.10                     py_0    defaults
protobuf                  3.10.1           py37h0a44026_0    defaults
psutil                    5.6.5            py37h1de35cc_0    defaults
ptyprocess                0.6.0                    py37_0    defaults
pycparser                 2.19                     py37_0    defaults
pygments                  2.4.2                      py_0    defaults
pyopenssl                 19.1.0                   py37_0    defaults
pyrsistent                0.15.5           py37h1de35cc_0    defaults
pysocks                   1.7.1                    py37_0    defaults
python                    3.7.5                h359304d_0    defaults
python-dateutil           2.8.1                      py_0    defaults
pyzmq                     18.1.0           py37h0a44026_0    defaults
readline                  7.0                  h1de35cc_5    defaults
requests                  2.22.0                   py37_0    defaults
scipy                     1.3.1            py37h1410ff5_0    defaults
send2trash                1.5.0                    py37_0    defaults
setuptools                41.6.0                   py37_0    defaults
six                       1.13.0                   py37_0    defaults
sqlite                    3.30.1               ha441bb4_0    defaults
tensorboard               2.0.0              pyhb230dea_0    defaults
tensorflow                2.0.0           mkl_py37hda344b4_0    defaults
tensorflow-base           2.0.0           mkl_py37h66b1bf0_0    defaults
tensorflow-datasets       1.2.0                    py37_0    defaults
tensorflow-estimator      2.0.0              pyh2649769_0    defaults
tensorflow-metadata       0.14.0             pyhe6710b0_1    defaults
termcolor                 1.1.0                    py37_1    defaults
terminado                 0.8.3                    py37_0    defaults
testpath                  0.4.4                      py_0    defaults
tk                        8.6.8                ha441bb4_0    defaults
tornado                   6.0.3            py37h1de35cc_0    defaults
tqdm                      4.38.0                     py_0    defaults
traitlets                 4.3.3                    py37_0    defaults
urllib3                   1.24.2                   py37_0    defaults
wcwidth                   0.1.7                    py37_0    defaults
webencodings              0.5.1                    py37_1    defaults
werkzeug                  0.16.0                     py_0    defaults
wheel                     0.33.6                   py37_0    defaults
wrapt                     1.11.2           py37h1de35cc_0    defaults
xz                        5.2.4                h1de35cc_4    defaults
zeromq                    4.3.1                h0a44026_3    defaults
zipp                      0.6.0                      py_0    defaults
zlib                      1.2.11               h1de35cc_3    defaults


```

</details>

**Comment by jjhelmus** [comment]
The line `Adapting from protocol version 5.1 (kernel 707630ab-9aac-445e-80b5-84e5217990b3) to 5.3 (client).` in the log is concerning as it indicated that the kernel is starting with a different protocol from jupyterlab/notebook.  

Do you have any packages installed in user locations, for example in ~/.local/lib/python3.7/site-package, or is PYTHONPATH set?

**Comment by mg4news** [comment]
Yes, there are packages in ~/.local/lib/python3.7/site-package. Should 
these be deleted, or?

**Comment by jjhelmus** [comment]
> there are packages in ~/.local/lib/python3.7/site-package.
Packages in this location can cause issues as they have preference over those installed by conda.  Removing them is recommended.

**Comment by mg4news** [comment]
I removed all python 3.7 related files from ~/.local/. Thing is I'm not 
sure where they would have come from? A previous Anaconda or miniconda 
installation?

**Comment by mg4news** [comment]
Sorry, I meant to say, I removed them all, and the issue went away. Thanks.

**Comment by jjhelmus** [comment]
Python packages can get installed into ~/.local is pip is run with the `--user` argument.  This flag is on by default in some cases but not from Anaconda or Miniconda.
