### ISSUE TITLE
Cannot Launch Jupyter due to import sqlite3 issue. DLL failed to load

### ISSUE THREAD

**Issue by bionnic** [ContinuumIO/anaconda-issues#11498]
### Actual Behavior

Hi Team,
I cannot launch Jupyter notebooks after installing anaconda.  I receive the following error:
  File "C:\Users\nbiondolillo\Anaconda3\lib\site-packages\notebook\services\sessions\sessionmanager.py", line 9, in <module>
    import sqlite3
  File "C:\Users\nbiondolillo\Anaconda3\lib\sqlite3\__init__.py", line 23, in <module>
    from sqlite3.dbapi2 import *
  File "C:\Users\nbiondolillo\Anaconda3\lib\sqlite3\dbapi2.py", line 27, in <module>
    from _sqlite3 import *
ImportError: DLL load failed: The specified procedure could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\nbiondolillo\Anaconda3\Scripts\jupyter-notebook-script.py", line 6, in <module>
    from notebook.notebookapp import main
  File "C:\Users\nbiondolillo\Anaconda3\lib\site-packages\notebook\notebookapp.py", line 83, in <module>
    from .services.sessions.sessionmanager import SessionManager
  File "C:\Users\nbiondolillo\Anaconda3\lib\site-packages\notebook\services\sessions\sessionmanager.py", line 12, in <module>
    from pysqlite2 import dbapi2 as sqlite3
ModuleNotFoundError: No module named 'pysqlite2'

### Expected Behavior

A jupyter notebook should launch. I receive the same error message when launching from the navigator and anaconda command prompt

### Steps to Reproduce

Launching Jupyter. 
Ive added 4 path enviorments, moved the sqlite3.dll file, updated all packages, uninstalled and reinstalled pymzq
reinstalled jupyter.

##### Anaconda or Miniconda version:

I installed Anaconda 2 days ago.
# Name                    Version                   Build  Channel
anaconda-client           1.7.2                    py37_0
anaconda-navigator        1.9.7                    py37_0

##### Operating System:
I have windows 10
##### `conda info`

<details>

```
(base) C:\Users\nbiondolillo>conda info

     active environment : base
    active env location : C:\Users\nbiondolillo\Anaconda3
            shell level : 1
       user config file : C:\Users\nbiondolillo\.condarc
 populated config files : C:\Users\nbiondolillo\.condarc
          conda version : 4.7.12
    conda-build version : 3.18.11
         python version : 3.7.5.final.0
       virtual packages :
       base environment : C:\Users\nbiondolillo\Anaconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\Users\nbiondolillo\Anaconda3\pkgs
                          C:\Users\nbiondolillo\.conda\pkgs
                          C:\Users\nbiondolillo\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\nbiondolillo\Anaconda3\envs
                          C:\Users\nbiondolillo\.conda\envs
                          C:\Users\nbiondolillo\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.7.12 requests/2.22.0 CPython/3.7.5 Windows/10 Windows/10.0.18362
          administrator : False
             netrc file : None
           offline mode : False

```

</details>

##### `conda list --show-channel-urls`

<details>

```
# Name                    Version                   Build  Channel
anaconda-client           1.7.2                    py37_0    defaults
anaconda-navigator        1.9.7                    py37_0    defaults
asn1crypto                1.2.0                    py37_0    defaults
attrs                     19.3.0                     py_0    defaults
backcall                  0.1.0                    py37_0    defaults
backports                 1.0                        py_2    defaults
backports.functools_lru_cache 1.6.1                      py_0    defaults
backports.tempfile        1.0                        py_1    defaults
backports.weakref         1.0.post1                  py_1    defaults
beautifulsoup4            4.8.1                    py37_0    defaults
bleach                    3.1.0                    py37_0    defaults
bzip2                     1.0.8                he774522_0    defaults
ca-certificates           2019.11.27                    0    defaults
certifi                   2019.11.28               py37_0    defaults
cffi                      1.13.2           py37h7a1dbc1_0    defaults
chardet                   3.0.4                 py37_1003    defaults
click                     7.0                      py37_0    defaults
clyent                    1.2.2                    py37_1    defaults
colorama                  0.4.1                    py37_0    defaults
conda                     4.7.12                   py37_0    defaults
conda-build               3.18.11                  py37_0    defaults
conda-env                 2.6.0                         1    defaults
conda-package-handling    1.6.0            py37h62dcd97_0    defaults
conda-verify              3.4.2                      py_1    defaults
console_shortcut          0.1.1                         3    defaults
cryptography              2.8              py37h7a1dbc1_0    defaults
decorator                 4.4.1                      py_0    defaults
defusedxml                0.6.0                      py_0    defaults
entrypoints               0.3                      py37_0    defaults
filelock                  3.0.12                     py_0    defaults
freetype                  2.9.1                ha9979f8_1    defaults
future                    0.18.2                   py37_0    defaults
glob2                     0.7                        py_0    defaults
icu                       58.2                 ha66f8fd_1    defaults
idna                      2.8                      py37_0    defaults
importlib_metadata        1.1.0                    py37_0    defaults
ipykernel                 5.1.3            py37h39e3cac_0    defaults
ipython                   7.10.1           py37h39e3cac_0    defaults
ipython_genutils          0.2.0                    py37_0    defaults
ipywidgets                7.5.1                      py_0    defaults
jedi                      0.15.1                   py37_0    defaults
jinja2                    2.10.3                     py_0    defaults
jpeg                      9b                   hb83a4c4_2    defaults
jsonschema                3.2.0                    py37_0    defaults
jupyter                   1.0.0                    py37_7    defaults
jupyter_client            5.3.4                    py37_0    defaults
jupyter_console           6.0.0                    py37_0    defaults
jupyter_core              4.6.1                    py37_0    defaults
libarchive                3.3.3                h0643e63_5    defaults
libiconv                  1.15                 h1df5818_7    defaults
liblief                   0.9.0                ha925a31_2    defaults
libpng                    1.6.37               h2a8f88b_0    defaults
libsodium                 1.0.16               h9d3ae62_0    defaults
libtiff                   4.1.0                h56a325e_0    defaults
libxml2                   2.9.9                h464c3ec_0    defaults
lz4-c                     1.8.1.2              h2fa13f4_0    defaults
lzo                       2.10                 h6df0209_2    defaults
m2w64-gcc-libgfortran     5.3.0                         6    defaults
m2w64-gcc-libs            5.3.0                         7    defaults
m2w64-gcc-libs-core       5.3.0                         7    defaults
m2w64-gmp                 6.1.0                         2    defaults
m2w64-libwinpthread-git   5.0.0.4634.697f757               2    defaults
markupsafe                1.1.1            py37he774522_0    defaults
menuinst                  1.4.16           py37he774522_0    defaults
mistune                   0.8.4            py37he774522_0    defaults
more-itertools            7.2.0                    py37_0    defaults
msys2-conda-epoch         20160418                      1    defaults
navigator-updater         0.2.1                    py37_0    defaults
nbconvert                 5.6.1                    py37_0    defaults
nbformat                  4.4.0                    py37_0    defaults
notebook                  6.0.2                    py37_0    defaults
olefile                   0.46                     py37_0    defaults
openssl                   1.1.1d               he774522_3    defaults
pandoc                    2.2.3.2                       0    defaults
pandocfilters             1.4.2                    py37_1    defaults
parso                     0.5.1                      py_0    defaults
pickleshare               0.7.5                    py37_0    defaults
pillow                    6.2.1            py37hdc69c19_0    defaults
pip                       19.3.1                   py37_0    defaults
pkginfo                   1.5.0.1                  py37_0    defaults
plotly                    4.3.0                    pypi_0    pypi
powershell_shortcut       0.0.1                         2    defaults
prometheus_client         0.7.1                      py_0    defaults
prompt_toolkit            2.0.9                    py37_0    defaults
psutil                    5.6.7            py37he774522_0    defaults
pulp                      2.0                      pypi_0    pypi
py-lief                   0.9.0            py37ha925a31_2    defaults
pycosat                   0.6.3            py37hfa6e2cd_0    defaults
pycparser                 2.19                     py37_0    defaults
pygments                  2.5.2                      py_0    defaults
pyopenssl                 19.1.0                   py37_0    defaults
pyqt                      5.9.2            py37h6538335_2    defaults
pyrsistent                0.15.6           py37he774522_0    defaults
pysocks                   1.7.1                    py37_0    defaults
python                    3.7.5                h8c8aaf0_0    defaults
python-dateutil           2.8.1                      py_0    defaults
python-libarchive-c       2.8                     py37_13    defaults
pytz                      2019.3                     py_0    defaults
pywin32                   223              py37hfa6e2cd_1    defaults
pywinpty                  0.5.5                 py37_1000    defaults
pyyaml                    5.1.2            py37he774522_0    defaults
pyzmq                     18.1.0           py37ha925a31_0    defaults
qt                        5.9.7            vc14h73c81de_0    defaults
qtconsole                 4.6.0                      py_0    defaults
qtpy                      1.9.0                      py_0    defaults
requests                  2.22.0                   py37_1    defaults
retrying                  1.3.3                    pypi_0    pypi
ruamel_yaml               0.15.46          py37hfa6e2cd_0    defaults
send2trash                1.5.0                    py37_0    defaults
setuptools                42.0.2                   py37_0    defaults
sip                       4.19.8           py37h6538335_0    defaults
six                       1.13.0                   py37_0    defaults
soupsieve                 1.9.5                    py37_0    defaults
sqlite                    3.30.1               he774522_0    defaults
terminado                 0.8.3                    py37_0    defaults
testpath                  0.4.4                      py_0    defaults
tk                        8.6.8                hfa6e2cd_0    defaults
tornado                   6.0.3            py37he774522_0    defaults
tqdm                      4.40.0                     py_0    defaults
traitlets                 4.3.3                    py37_0    defaults
urllib3                   1.25.7                   py37_0    defaults
vc                        14.1                 h0510ff6_4    defaults
vs2015_runtime            14.16.27012          hf0eaf9b_0    defaults
wcwidth                   0.1.7                    py37_0    defaults
webencodings              0.5.1                    py37_1    defaults
wheel                     0.33.6                   py37_0    defaults
widgetsnbextension        3.5.1                    py37_0    defaults
win_inet_pton             1.1.0                    py37_0    defaults
wincertstore              0.2                      py37_0    defaults
winpty                    0.4.3                         4    defaults
xz                        5.2.4                h2fa13f4_4    defaults
yaml                      0.1.7                hc54c509_2    defaults
zeromq                    4.3.1                h33f27b4_3    defaults
zipp                      0.6.0                      py_0    defaults
zlib                      1.2.11               h62dcd97_3    defaults
zstd                      1.3.7                h508b16e_0    defaults

```

</details>

**Comment by jjhelmus** [comment]
It looks like Python is failing to load the sqlite DLL.  Have you activated the conda environment where ipython is installed using `conda activate base` or executed the command from the anaconda prompt?

**Comment by bionnic** [comment]
Yes, I did that and it did not fix the issue. I was able to launch it by following the numpy known issue and writing a set [forget_exact_DDL_enable_lingo_on_phone_atm] = 1, but it was not a permanent and jupyter doesnt recognize conda packages upon launch.

**Comment by czokw1** [comment]
Hi @bionnic , I had same issue what I exactly did is adding sqllite3.dll file to folder C:\Users\XXXXX\Anaconda3\DLLs

I found solution here:

https://stackoverflow.com/questions/54876404/unable-to-import-sqlite3-using-anaconda-python?answertab=active#tab-top
