### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by Oluwatosin26** [ContinuumIO/anaconda-issues#11506]
## Main error
An unexpected error occurred on Navigator start-up<br>psutil.AccessDenied (pid=8324)
## Traceback
```
Traceback (most recent call last):
  File "C:\Users\Oluwatosin\Anaconda3\lib\site-packages\psutil\_pswindows.py", line 620, in wrapper
    return fun(self, *args, **kwargs)
  File "C:\Users\Oluwatosin\Anaconda3\lib\site-packages\psutil\_pswindows.py", line 690, in cmdline
    ret = cext.proc_cmdline(self.pid)
PermissionError: [WinError 5] Access is denied

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Oluwatosin\Anaconda3\lib\site-packages\anaconda_navigator\exceptions.py", line 75, in exception_handler
    return_value = func(*args, **kwargs)
  File "C:\Users\Oluwatosin\Anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 108, in start_app
    if misc.load_pid() is None:  # A stale lock might be around
  File "C:\Users\Oluwatosin\Anaconda3\lib\site-packages\anaconda_navigator\utils\misc.py", line 384, in load_pid
    cmds = process.cmdline()
  File "C:\Users\Oluwatosin\Anaconda3\lib\site-packages\psutil\__init__.py", line 701, in cmdline
    return self._proc.cmdline()
  File "C:\Users\Oluwatosin\Anaconda3\lib\site-packages\psutil\_pswindows.py", line 623, in wrapper
    raise AccessDenied(self.pid, self._name)
psutil.AccessDenied: psutil.AccessDenied (pid=8324)

```
## System information
```
python: 3.6.8
language: en_US
os: Windows;7;6.1.7601;AMD64;Intel64 Family 6 Model 78 Stepping 3, GenuineIntel
version: 1.6.2
platform: win-64
qt: 5.9.6
pyqt: 5.

**Comment by jadecacho** [comment]
> I just had this error too a few minutes ago.

### Navigator Error
An unexpected error occurred on Navigator start-up

### Report
Please report this issue in the anaconda issue tracker

### Main Error
expected str, bytes or os.PathLike object, not NoneType

### Traceback
    
    Traceback (most recent call last):
      File "C:\Users\W-book\Anaconda3\lib\site-packages\anaconda_navigator\exceptions.py", line 75, in exception_handler
        return_value = func(*args, **kwargs)
      File "C:\Users\W-book\Anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 151, in start_app
        window = run_app(splash)
      File "C:\Users\W-book\Anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 65, in run_app
        window = MainWindow(splash=splash, tab_project=False)
      File "C:\Users\W-book\Anaconda3\lib\site-packages\anaconda_navigator\widgets\main_window.py", line 168, in __init__
        self.api = AnacondaAPI()
      File "C:\Users\W-book\Anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 2337, in AnacondaAPI
        ANACONDA_API = _AnacondaAPI()
      File "C:\Users\W-book\Anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 89, in __init__
        self._conda_api = CondaAPI()
      File "C:\Users\W-book\Anaconda3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 1773, in CondaAPI
        CONDA_API = _CondaAPI()
      File "C:\Users\W-book\Anaconda3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 353, in __init__
        self.sys_rc_path = join(self.ROOT_PREFIX, '.condarc')
      File "C:\Users\W-book\Anaconda3\lib\ntpath.py", line 76, in join
        path = os.fspath(path)
    TypeError: expected str, bytes or os.PathLike object, not NoneType

**Comment by jadecacho** [comment]
Done the following:

- restarted computer: not resolved
- cleared browser's cache: not resolved
- reinstalled Anaconda: not resolved

**Comment by CrisChir** [comment]
**Navigator Error**
An unexpected error occurred on Navigator start-up
**Report**
Please report this issue in the anaconda issue tracker 
**Main Error**

expected str, bytes or os.PathLike object, not NoneType

Traceback

Traceback (most recent call last):
  File "C:\Anaconda3\lib\site-packages\anaconda_navigator\exceptions.py", line 75, in exception_handler
    return_value = func(*args, **kwargs)
  File "C:\Anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 151, in start_app
    window = run_app(splash)
  File "C:\Anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 65, in run_app
    window = MainWindow(splash=splash, tab_project=False)
  File "C:\Anaconda3\lib\site-packages\anaconda_navigator\widgets\main_window.py", line 168, in __init__
    self.api = AnacondaAPI()
  File "C:\Anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 2337, in AnacondaAPI
    ANACONDA_API = _AnacondaAPI()
  File "C:\Anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 89, in __init__
    self._conda_api = CondaAPI()
  File "C:\Anaconda3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 1773, in CondaAPI
    CONDA_API = _CondaAPI()
  File "C:\Anaconda3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 353, in __init__
    self.sys_rc_path = join(self.ROOT_PREFIX, '.condarc')
  File "C:\Anaconda3\lib\ntpath.py", line 76, in join
    path = os.fspath(path)
TypeError: expected str, bytes or os.PathLike object, not NoneType

**Anaconda Prompt :**
> Traceback (most recent call last):
  File "C:\Anaconda3\lib\site-packages\conda\cli\main.py", line 137, in main
    from ..activate import main as activator_main
  File "C:\Anaconda3\lib\site-packages\conda\activate.py", line 23, in <module>
    from .base.context import ROOT_ENV_NAME, context, locate_prefix_by_name
  File "C:\Anaconda3\lib\site-packages\conda\base\context.py", line 28, in <module>
    from ..common.configuration import (Configuration, ConfigurationLoadError, MapParameter,
  File "C:\Anaconda3\lib\site-packages\conda\common\configuration.py", line 40, in <module>
    from .serialize import yaml_load
  File "C:\Anaconda3\lib\site-packages\conda\common\serialize.py", line 45, in <module>
    yaml.representer.RoundTripRepresenter.add_representer(odict, represent_ordereddict)
   AttributeError: module 'ruamel_yaml' has no attribute 'representer'

> During handling of the above exception, another exception occurred:

> Traceback (most recent call last):
  File "C:\Anaconda3\Scripts\conda-script.py", line 12, in <module>
    sys.exit(main())
  File "C:\Anaconda3\lib\site-packages\conda\cli\main.py", line 147, in main
    return ExceptionHandler().handle_exception(exc_val, exc_tb)
  File "C:\Anaconda3\lib\site-packages\conda\exceptions.py", line 1121, in handle_exception
    return self.handle_unexpected_exception(exc_val, exc_tb)
  File "C:\Anaconda3\lib\site-packages\conda\exceptions.py", line 1132, in handle_unexpected_exception
    self.print_unexpected_error_report(error_report)
  File "C:\Anaconda3\lib\site-packages\conda\exceptions.py", line 1187, in print_unexpected_error_report
    from .base.context import context
  File "C:\Anaconda3\lib\site-packages\conda\base\context.py", line 28, in <module>
    from ..common.configuration import (Configuration, ConfigurationLoadError, MapParameter,
  File "C:\Anaconda3\lib\site-packages\conda\common\configuration.py", line 40, in <module>
    from .serialize import yaml_load
  File "C:\Anaconda3\lib\site-packages\conda\common\serialize.py", line 45, in <module>
    yaml.representer.RoundTripRepresenter.add_representer(odict, represent_ordereddict)
AttributeError: module 'ruamel_yaml' has no attribute 'representer'

**Comment by CrisChir** [comment]
Deleting condarc is not working .

**Comment by csoja** [comment]
There are two different errors being reported here.
One is a corrupted .condarc file - and for that one, removing the .condarc file should fix it.  You may need to see the results of _conda info_ to make sure you are capturing all of the ones installed on your computer.
The other is a lock file that was not removed - so you need to reset navigator. 

Better instructions for both of these are available in the docs here: 
https://docs.anaconda.com/anaconda/navigator/troubleshooting/#navigator-error-on-start-up
https://docs.anaconda.com/anaconda/navigator/troubleshooting/#access-denied-error

**Comment by jadecacho** [comment]
# This solved the issue:

- Uninstall Anaconda
- Restart PC
- Install Anaconda

**Comment by CrisChir** [comment]
More here at Anaconda guide: https://docs.anaconda.com/anaconda/user-guide/troubleshooting/
**Windows**
Change your original installer’s name so you do not overwrite it:
move Anaconda Anaconda_old
Run the Anaconda.exe installer as usual and use robocopy to sync the directories:
robocopy Anaconda_old Anaconda /S
rd /s Anaconda_old
