### ISSUE TITLE
Sublime Text build system from conda environment: Numpy "DLL load failed: The specified module could not be found"

### ISSUE THREAD

**Issue by sjoerdloenen** [ContinuumIO/anaconda-issues#11504]
### Actual Behavior

When using the numpy package in a python script ran within sublime text I get the error "DLL load failed: The specified module could not be found".

I posted this issue on the numpy github issue page, where I was advised to open an issue here. In the post on the numpy github I have also included the error messages. Link to the post: https://github.com/numpy/numpy/issues/14755.
The main error: 
Import error:  "DLL load failed: The specified module could not be found."
There is (also) a problem with "_mklinit"
From the responses on this page it seems that it has something to do with that vanilla numpy is not shipped with MKL, whereas anaconda uses MKL for the numpy pacakge.

**Description of my situation:**

I already tried reinstalling numpy using conda, but to no avail.

I established different "build systems" within sublime text to run the python code (extremely basic test code, see below). The build systems use python executable files: "C:/Users/Sjoerd/Miniconda3/envs/DevPython37/python", where DevPython37 is my user defined name of the conda environment related to the python version I want to use. I have one environment with Python 3.7 and one with 2.7. The error occurs with both environments.

When starting sublime text from the anaconda prompt this error does not occur.
Also when I start jupyter notebook from the anaconda prompt and use numpy in the jupyter notebook, numpy also works fine.
However, I would like it to work when I start up sublime text from any location and not just when using the terminal. I hope someone is able to help me resolve this issue.

There is some (to me seemingly) similar issue relating to PyCharm (ContinuumIO/anaconda-issues#1508 (comment)). This is how I figured out it works when opening sublime text from the terminal.

**Test code that raises the numpy error**
`
import time
import numpy as np

for i in range(5):
	print ("hello world...")
	time.sleep(1)

A = np.array([1,2,3])
print A
`
(NOTE: with python3.7 the syntax of print is adapted to print(A))

The code to establish the build system (".sublime-build" file, located at "C:\Users\Sjoerd\AppData\Roaming\Sublime Text 3\Packages\User"). python2.7 case is similar.
`
{
    "cmd": ["C:/Users/Sjoerd/Miniconda3/envs/DevPython37/python", "-u", "$file"],
    "selector": "source.python",
    "file_regex": "^\\s*File \"(...*?)\", line ([0-9]*)"
}
`

**Error Message**
ERROR MESSAGE WHEN USING PYTHON27 BUILD SYSTEM:
`
Traceback (most recent call last):
  File "C:\Users\Sjoerd\Documents\Python_Projects\Hello_world_test.py", line 2, in <module>
    import numpy as np
  File "C:\Users\Sjoerd\Miniconda3\envs\DevPython27\lib\site-packages\numpy\__init__.py", line 142, in <module>
    from . import core
  File "C:\Users\Sjoerd\Miniconda3\envs\DevPython27\lib\site-packages\numpy\core\__init__.py", line 71, in <module>
    raise ImportError(msg)
ImportError: 
`

ERROR MESSAGE WHEN USING PYTHON37 BUILD SYSTEM:
`
Traceback (most recent call last):
  File "C:\Users\Sjoerd\Documents\Python_Projects\Hello_world_test.py", line 3, in <module>
    import numpy as np
  File "C:\Users\Sjoerd\Miniconda3\envs\DevPython37\lib\site-packages\numpy\__init__.py", line 140, in <module>
    from . import _distributor_init
  File "C:\Users\Sjoerd\Miniconda3\envs\DevPython37\lib\site-packages\numpy\_distributor_init.py", line 34, in <module>
    from . import _mklinit
ImportError: DLL load failed: The specified module could not be found.
`

I would highly appreciate if someone could help me to solve this as it would make my workflow more efficient instead of always having to open sublime text through the anaconda prompt.

Thanks in advance.

### Expected Behavior

I would expect the code to simply work if I start sublime text from anywhere and not just if I start sublime text from the anaconda prompt.

##### System specifications:

I use Windows 10 on a 64-bit machine.
Python version: error occurs with both the Python3.7 (with numpy 1.16.5) build system and the Python2.7 (with numpy 1.16.5) build system.
Conda version 4.7.12 (installed through Miniconda3)

##### `conda info`

<details>

```
     active environment : DevPython27
    active env location : C:\Users\Sjoerd\Miniconda3\envs\DevPython27
            shell level : 2
       user config file : C:\Users\Sjoerd\.condarc
 populated config files : C:\Users\Sjoerd\.condarc
          conda version : 4.7.12
    conda-build version : not installed
         python version : 3.7.4.final.0
       virtual packages : __cuda=9.0
       base environment : C:\Users\Sjoerd\Miniconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
                          https://conda.anaconda.org/conda-forge/win-64
                          https://conda.anaconda.org/conda-forge/noarch
          package cache : C:\Users\Sjoerd\Miniconda3\pkgs
                          C:\Users\Sjoerd\.conda\pkgs
                          C:\Users\Sjoerd\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\Sjoerd\Miniconda3\envs
                          C:\Users\Sjoerd\.conda\envs
                          C:\Users\Sjoerd\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.7.12 requests/2.22.0 CPython/3.7.4 Windows/10 Windows/10.0.18362
          administrator : False
             netrc file : None
           offline mode : False

```

</details>

##### `conda list --show-channel-urls`

<details>

```
# Name                    Version                   Build  Channel
attrs                     19.2.0                     py_0    defaults
backports                 1.0                        py_2    defaults
backports.functools_lru_cache 1.5                        py_2    defaults
backports.shutil_get_terminal_size 1.0.0                    py27_2    defaults
backports.shutil_which    3.5.2                    py27_0    defaults
backports_abc             0.5              py27h0ec6b72_0    defaults
blas                      1.0                         mkl    defaults
bleach                    3.1.0                    py27_0    defaults
ca-certificates           2019.10.16                    0    defaults
certifi                   2019.9.11                py27_0    defaults
colorama                  0.4.1                    py27_0    defaults
configparser              4.0.2                    py27_0    defaults
cycler                    0.10.0           py27h59acbbf_0    defaults
cython                    0.29.13          py27hc56fc5f_0    defaults
decorator                 4.4.0                    py27_1    defaults
defusedxml                0.6.0                      py_0    defaults
entrypoints               0.3                      py27_0    defaults
enum34                    1.1.6                    py27_1    defaults
fastcache                 1.1.0            py27h0c8e037_0    defaults
freetype                  2.9.1                h4d385ea_1    defaults
functools32               3.2.3.2                  py27_1    defaults
futures                   3.3.0                    py27_0    defaults
h5py                      2.9.0            py27hb721d18_0    defaults
hdf5                      1.10.4               h530792d_0    defaults
icc_rt                    2019.0.0             h0cc432a_1    defaults
icu                       58.2                 h2aa20d9_1    defaults
intel-openmp              2019.4                      245    defaults
ipaddress                 1.0.22                   py27_0    defaults
ipykernel                 4.10.0                   py27_0    defaults
ipython                   5.8.0                    py27_0    defaults
ipython_genutils          0.2.0            py27hbe997df_0    defaults
ipywidgets                7.5.1                      py_0    defaults
jinja2                    2.10.3                     py_0    defaults
jpeg                      9b                   ha175dff_2    defaults
jsonschema                3.0.2                    py27_0    defaults
jupyter                   1.0.0                    py27_7    defaults
jupyter_client            5.3.4                    py27_0    defaults
jupyter_console           5.2.0                    py27_1    defaults
jupyter_core              4.6.0                    py27_0    defaults
kiwisolver                1.1.0            py27hc56fc5f_0    defaults
libpng                    1.6.37               h7a46e7a_0    defaults
libsodium                 1.0.16               h8b3e59e_0    defaults
linecache2                1.0.0                    py27_0    defaults
m2w64-gcc-libgfortran     5.3.0                         6    defaults
m2w64-gcc-libs            5.3.0                         7    defaults
m2w64-gcc-libs-core       5.3.0                         7    defaults
m2w64-gmp                 6.1.0                         2    defaults
m2w64-libwinpthread-git   5.0.0.4634.697f757               2    defaults
markupsafe                1.1.1            py27h0c8e037_0    defaults
matplotlib                2.2.3            py27h263d877_0    defaults
mistune                   0.8.4            py27h0c8e037_0    defaults
mkl                       2019.4                      245    defaults
mkl-service               2.3.0            py27h0b88c2a_0    defaults
mkl_fft                   1.0.14           py27h44c1dab_0    defaults
mpmath                    1.1.0                    py27_0    defaults
msys2-conda-epoch         20160418                      1    defaults
nbconvert                 5.6.0                    py27_1    defaults
nbformat                  4.4.0            py27hf49b375_0    defaults
nose                      1.3.7                    py27_2    defaults
notebook                  5.7.8                    py27_0    defaults
numpy                     1.16.5           py27h5fc8d92_0    defaults
numpy-base                1.16.5           py27hb1d0314_0    defaults
openssl                   1.0.2t            vc9h3cc03e0_0    defaults
pandoc                    2.2.3.2                       0    defaults
pandocfilters             1.4.2                    py27_1    defaults
pathlib2                  2.3.5                    py27_0    defaults
pickleshare               0.7.5                    py27_0    defaults
pip                       19.2.3                   py27_0    defaults
prometheus_client         0.7.1                      py_0    defaults
prompt_toolkit            1.0.15           py27h3a8ec6a_0    defaults
pygments                  2.4.2                      py_0    defaults
pyparsing                 2.4.2                      py_0    defaults
pyqt                      5.6.0            py27h6e61f57_6    defaults
pyreadline                2.1                      py27_1    defaults
pyrsistent                0.15.4           py27h0c8e037_0    defaults
python                    2.7.16               hcb6e200_0    defaults
python-dateutil           2.8.0                    py27_0    defaults
pytz                      2019.3                     py_0    defaults
pywin32                   223              py27h0c8e037_1    defaults
pywinpty                  0.5.5                 py27_1000    defaults
pyzmq                     18.1.0           py27hc56fc5f_0    defaults
qt                        5.6.2            vc9hc26998b_12    defaults
qtconsole                 4.5.5                      py_0    defaults
scandir                   1.10.0           py27h0c8e037_0    defaults
scipy                     1.2.1            py27h4c3ab11_0    defaults
send2trash                1.5.0                    py27_0    defaults
setuptools                41.4.0                   py27_0    defaults
simplegeneric             0.8.1                    py27_2    defaults
singledispatch            3.4.0.3          py27h3f9d112_0    defaults
sip                       4.18.1           py27hc56fc5f_2    defaults
six                       1.12.0                   py27_0    defaults
sqlite                    3.30.0               h0c8e037_0    defaults
sympy                     1.4                      py27_0    defaults
terminado                 0.8.2                    py27_0    defaults
testpath                  0.4.2                    py27_0    defaults
tornado                   5.1.1            py27h0c8e037_0    defaults
traceback2                1.4.0                    py27_0    defaults
traitlets                 4.3.3                    py27_0    defaults
unittest2                 1.1.0                    py27_0    defaults
vc                        9                    h7299396_1    defaults
vs2008_runtime            9.00.30729.1         hfaea7d5_1    defaults
wcwidth                   0.1.7            py27hb1a0d82_0    defaults
webencodings              0.5.1                    py27_1    defaults
wheel                     0.33.6                   py27_0    defaults
widgetsnbextension        3.5.1                    py27_0    defaults
win_unicode_console       0.5              py27hc037021_0    defaults
wincertstore              0.2              py27hf04cefb_0    defaults
winpty                    0.4.3                         4    defaults
zeromq                    4.3.1                h2880e7c_3    defaults
zlib                      1.2.11               h3cc03e0_3    defaults
```

</details>

**Comment by jjhelmus** [comment]
When using conda on Windows it is necessary to activate the environment prior to running the interpreter.  Activation adds the necessary entries to the PATH so that DLLs can be loaded.  I do not know how to force Sublime Text to activate and environment but the process to do this from [a cmd.exe session is documented](https://docs.conda.io/projects/conda/en/latest/user-guide/troubleshooting.html#windows-environment-has-not-been-activated).

**Comment by sjoerdloenen** [comment]
Thanks to Olivezer, a solution is found, see:
https://github.com/numpy/numpy/issues/14755#issuecomment-594853764
