### ISSUE TITLE
Un able to open the Python 4.0 in anaconda after installing it

### ISSUE THREAD

**Issue by Krish11582** [ContinuumIO/anaconda-issues#11517]
Once i have downloaded the Spyder 4.0 using the update applcation from inside Anaconda navigator i am not able to open the Spyder applcation at all. Error i am getting is 

Traceback (most recent call last): File "C:\Users\narakris\AppData\Local\Continuum\anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 3711, in main mainwindow = run_spyder(app, options, args) File "C:\Users\narakris\AppData\Local\Continuum\anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 3552, in run_spyder main.setup() File "C:\Users\narakris\AppData\Local\Continuum\anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 1010, in setup from spyder.plugins.ipythonconsole.plugin import IPythonConsole File "C:\Users\narakris\AppData\Local\Continuum\anaconda3\lib\site-packages\spyder\plugins\ipythonconsole\plugin.py", line 52, in from spyder.plugins.ipythonconsole.widgets import ClientWidget File "C:\Users\narakris\AppData\Local\Continuum\anaconda3\lib\site-packages\spyder\plugins\ipythonconsole\widgets\__init__.py", line 16, in from .debugging import DebuggingWidget File "C:\Users\narakris\AppData\Local\Continuum\anaconda3\lib\site-packages\spyder\plugins\ipythonconsole\widgets\debugging.py", line 22, in from IPython.core.inputtransformer2 import TransformerManager ModuleNotFoundError: No module named 'IPython.core.inputtransformer2'

Can someone please help me on the same

**Comment by ccordoba12** [comment]
It looks like your Anaconda installation is corrupted, so no you need to reinstall it.
