### ISSUE TITLE
Can't update Anaconda or anything in Anaconda

### ISSUE THREAD

**Issue by rallyguy** [ContinuumIO/anaconda-issues#11524]
### Actual Behavior

When I attempt to update Anaconda, conda, or Spyder using the Anaconda PowerShell Prompt: "conda update anaconda, conda update --all, conda install spyder=4.0.0", I get an error and it rolls back the changes.

When I attempt to update Spyder through the navigator, it states that I can't install it in the current environment (the root environment, which is preferable). 

When I attempt to use the command prompt/"Terminal" by selecting it within the Environments page of the Anaconda Navigator I get a message that states: Access Denied (twice) and that the file conda-10550-12384.tmp cannot be found. 

Part of the issue may be that I originally installed Anaconda on my user which has a space between the first and last name (c:\user\first last\anaconda), but I reinstalled it to the c:\Anaconda directory. However, the "cannot find file conda-10550-12384.tmp" error still references my user directory name with the space (?). 

When I attempt to update packages on the Environment page of the Navigator, I get the message: "Multiple errors encountered"

I have uninstalled and reinstalled multiple times, including using the anaconda-clean (though, I may have botched my original installation, ending the task prematurely through my Windows 10 task manager (?). 

### Expected Behavior

Everything should update seamlessly 

### Steps to Reproduce

Simply typing "conda update" or "conda install" produces these errors. Also, attempting to update through the Anaconda Navigator results in errors also. 

##### Anaconda or Miniconda version:

2019.10

##### Operating System:
Windows 10

##### `conda info`

<details>

```
PASTE OUTPUT HERE:

```

Preparing transaction: done
Verifying transaction: done
Executing transaction: | DEBUG menuinst_win32:__init__(199): Menu: name: 'Anaconda${PY_VER} ${PLATFORM}', prefix: 'C:\ProgramData\Anaconda3', env_name: 'None', mode: 'system', used_mode: 'system'
DEBUG menuinst_win32:create(323): Shortcut cmd is C:\ProgramData\Anaconda3\pythonw.exe, args are ['C:\\ProgramData\\Anaconda3\\cwp.py', 'C:\\ProgramData\\Anaconda3', 'C:\\ProgramData\\Anaconda3\\pythonw.exe', 'C:\\ProgramData\\Anaconda3\\Scripts\\spyder-script.py']
DEBUG menuinst_win32:create(323): Shortcut cmd is C:\ProgramData\Anaconda3\python.exe, args are ['C:\\ProgramData\\Anaconda3\\cwp.py', 'C:\\ProgramData\\Anaconda3', 'C:\\ProgramData\\Anaconda3\\python.exe', 'C:\\ProgramData\\Anaconda3\\Scripts\\spyder-script.py', '--reset']
DEBUG menuinst_win32:__init__(199): Menu: name: 'Anaconda${PY_VER} ${PLATFORM}', prefix: 'C:\ProgramData\Anaconda3', env_name: 'None', mode: 'system', used_mode: 'system'
DEBUG menuinst_win32:create(323): Shortcut cmd is C:\ProgramData\Anaconda3\pythonw.exe, args are ['C:\\ProgramData\\Anaconda3\\cwp.py', 'C:\\ProgramData\\Anaconda3', 'C:\\ProgramData\\Anaconda3\\pythonw.exe', 'C:\\ProgramData\\Anaconda3\\Scripts\\spyder-script.py']
DEBUG menuinst_win32:create(323): Shortcut cmd is C:\ProgramData\Anaconda3\python.exe, args are ['C:\\ProgramData\\Anaconda3\\cwp.py', 'C:\\ProgramData\\Anaconda3', 'C:\\ProgramData\\Anaconda3\\python.exe', 'C:\\ProgramData\\Anaconda3\\Scripts\\spyder-script.py', '--reset']
DEBUG menuinst_win32:__init__(199): Menu: name: 'Anaconda${PY_VER} ${PLATFORM}', prefix: 'C:\ProgramData\Anaconda3', env_name: 'None', mode: 'system', used_mode: 'system'
DEBUG menuinst_win32:create(323): Shortcut cmd is C:\ProgramData\Anaconda3\python.exe, args are ['C:\\ProgramData\\Anaconda3\\cwp.py', 'C:\\ProgramData\\Anaconda3', 'C:\\ProgramData\\Anaconda3\\python.exe', 'C:\\ProgramData\\Anaconda3\\Scripts\\jupyter-notebook-script.py', '"%USERPROFILE%/"']
DEBUG menuinst_win32:__init__(199): Menu: name: 'Anaconda${PY_VER} ${PLATFORM}', prefix: 'C:\ProgramData\Anaconda3', env_name: 'None', mode: 'system', used_mode: 'system'
DEBUG menuinst_win32:create(323): Shortcut cmd is C:\ProgramData\Anaconda3\python.exe, args are ['C:\\ProgramData\\Anaconda3\\cwp.py', 'C:\\ProgramData\\Anaconda3', 'C:\\ProgramData\\Anaconda3\\python.exe', 'C:\\ProgramData\\Anaconda3\\Scripts\\jupyter-notebook-script.py', '"%USERPROFILE%/"']
done
ERROR conda.core.link:_execute(700): An error occurred while installing package 'defaults::ipykernel-5.1.3-py37h39e3cac_0'.
Rolling back transaction: \ menuinst Exception
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\conda\gateways\disk\create.py", line 246, in make_menu
    menuinst.install(join(prefix, win_path_ok(file_path)), remove, prefix)
  File "C:\ProgramData\Anaconda3\lib\site-packages\menuinst\__init__.py", line 58, in install
    _install(path, remove, prefix, mode='system')
  File "C:\ProgramData\Anaconda3\lib\site-packages\menuinst\__init__.py", line 33, in _install
    data = json.load(open(path))
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\ProgramData\\Anaconda3\\Menu\\notebook.json'menuinst Exception
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\conda\gateways\disk\create.py", line 246, in make_menu
    menuinst.install(join(prefix, win_path_ok(file_path)), remove, prefix)
  File "C:\ProgramData\Anaconda3\lib\site-packages\menuinst\__init__.py", line 58, in install
    _install(path, remove, prefix, mode='system')
  File "C:\ProgramData\Anaconda3\lib\site-packages\menuinst\__init__.py", line 33, in _install
    data = json.load(open(path))
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\ProgramData\\Anaconda3\\Menu\\notebook.json'menuinst Exception
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\conda\gateways\disk\create.py", line 246, in make_menu
    menuinst.install(join(prefix, win_path_ok(file_path)), remove, prefix)
  File "C:\ProgramData\Anaconda3\lib\site-packages\menuinst\__init__.py", line 58, in install
    _install(path, remove, prefix, mode='system')
  File "C:\ProgramData\Anaconda3\lib\site-packages\menuinst\__init__.py", line 33, in _install
    data = json.load(open(path))
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\ProgramData\\Anaconda3\\Menu\\spyder_shortcut.json'menuinst Exception
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\conda\gateways\disk\create.py", line 246, in make_menu
    menuinst.install(join(prefix, win_path_ok(file_path)), remove, prefix)
  File "C:\ProgramData\Anaconda3\lib\site-packages\menuinst\__init__.py", line 58, in install
    _install(path, remove, prefix, mode='system')
  File "C:\ProgramData\Anaconda3\lib\site-packages\menuinst\__init__.py", line 33, in _install
    data = json.load(open(path))
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\ProgramData\\Anaconda3\\Menu\\spyder_shortcut.jsodone
LinkError: post-link script failed for package defaults::ipykernel-5.1.3-py37h39e3cac_0
location of failed script: C:\ProgramData\Anaconda3\Scripts\.ipykernel-post-link.bat
==> script messages <==
<None>
==> script output <==
stdout:
stderr: The system cannot find the path specified.
activate does not accept more than one argument:
['C:\\ProgramData\\Anaconda3', 'USERLASTNAME\\AppData\\Local\\Temp\\conda-14136-7633.tmp']

return code: 2
()
</details>

**Comment by bfkeats** [comment]
Did you ever resolve this? I'm getting the same error.

**Comment by rallyguy** [comment]
I did not!

**Comment by bfkeats** [comment]
I applied the nuanced solution of reinstalling anaconda.

**Comment by pj1989** [comment]
same problem here

**Comment by MohammadRaziei** [comment]
I have the same problem :)

**Comment by janalysis** [comment]
I will add to the chorus of people with the same problem.
