### ISSUE TITLE
Anaconda3-2019.10-Windows-x86_64.exe w/ path fails to launch jupyter

### ISSUE THREAD

**Issue by michaelrempel** [ContinuumIO/anaconda-issues#11543]
### Actual Behavior
when launching Jupyter notebook on a fresh install.
the DLL location was added to my environment path for all users
d:\Anaconda3;d:\Anaconda3\Library\mingw-w64\bin;d:\Anaconda3\Library\usr\bin;d:\Anaconda3\Library\bin;d:\Anaconda3\Scripts;

note that the sqllite3.dll exists in Library/bin, but it seems to want to do 
pysqlite2 import dbapi2 as sqlite3
in the error dump below

It also does the same thing launching jupyter notebook from a command prompt

note to responders, I have been coding for decades but I am fairly new to Python, just learning

Traceback (most recent call last):
File "D:\Anaconda3\lib\site-packages\notebook\services\sessions\sessionmanager.py", line 9, in 
import sqlite3
File "D:\Anaconda3\lib\sqlite3\__init__.py", line 23, in 
from sqlite3.dbapi2 import *
File "D:\Anaconda3\lib\sqlite3\dbapi2.py", line 27, in 
from _sqlite3 import *
ImportError: DLL load failed: The specified procedure could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "D:\Anaconda3\Scripts\jupyter-notebook-script.py", line 6, in 
from notebook.notebookapp import main
File "D:\Anaconda3\lib\site-packages\notebook\notebookapp.py", line 86, in 
from .services.sessions.sessionmanager import SessionManager
File "D:\Anaconda3\lib\site-packages\notebook\services\sessions\sessionmanager.py", line 12, in 
from pysqlite2 import dbapi2 as sqlite3
ModuleNotFoundError: No module named 'pysqlite2'

##### `conda info`

<details>

```
PASTE OUTPUT HERE:

```

</details>

##### `conda list --show-channel-urls`

<details>

```
PASTE OUTPUT HERE:

```

</details>

**Comment by Amberjay18** [comment]
> ### Actual Behavior
> update. A test.py file with one line
> import sqlite3
> 
> fails with the following error
> (venv) D:\Projects\Anaconda\test\sqlite3>python sqlite.py
> Traceback (most recent call last):
> File "sqlite.py", line 1, in
> import sqlite3
> File "d:\Anaconda3\lib\sqlite3__init__.py", line 23, in
> from sqlite3.dbapi2 import *
> File "d:\Anaconda3\lib\sqlite3\dbapi2.py", line 27, in
> from _sqlite3 import *
> ImportError: DLL load failed: The specified procedure could not be found.
> 
> I double checked and only 1 Python version 3.7 is registered in the registry
> --end update------
> 
> when launching Jupyter notebook on a fresh install.
> the DLL location was added to my environment path for all users
> d:\Anaconda3;d:\Anaconda3\Library\mingw-w64\bin;d:\Anaconda3\Library\usr\bin;d:\Anaconda3\Library\bin;d:\Anaconda3\Scripts;
> 
> note that the sqllite3.dll exists in Library/bin, but it seems to want to do
> pysqlite2 import dbapi2 as sqlite3
> in the error dump below
> 
> It also does the same thing launching jupyter notebook from a command prompt
> 
> note to responders, I have been coding for decades but I am fairly new to Python, just learning
> 
> Traceback (most recent call last):
> File "D:\Anaconda3\lib\site-packages\notebook\services\sessions\sessionmanager.py", line 9, in
> import sqlite3
> File "D:\Anaconda3\lib\sqlite3__init__.py", line 23, in
> from sqlite3.dbapi2 import *
> File "D:\Anaconda3\lib\sqlite3\dbapi2.py", line 27, in
> from _sqlite3 import *
> ImportError: DLL load failed: The specified procedure could not be found.
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
> File "D:\Anaconda3\Scripts\jupyter-notebook-script.py", line 6, in
> from notebook.notebookapp import main
> File "D:\Anaconda3\lib\site-packages\notebook\notebookapp.py", line 86, in
> from .services.sessions.sessionmanager import SessionManager
> File "D:\Anaconda3\lib\site-packages\notebook\services\sessions\sessionmanager.py", line 12, in
> from pysqlite2 import dbapi2 as sqlite3
> ModuleNotFoundError: No module named 'pysqlite2'
> 
> ### Expected Behavior
> no bugs
> 
> ### Steps to Reproduce
> try to launch jupyter notebook
> 
> ##### Anaconda or Miniconda version:
> in the title
> ##### Operating System:
> windows 10
> 
> ##### `conda info`
> ##### `conda list --show-channel-urls`

https://conda.io/projects/conda/en/latest/user-guide/troubleshooting.html#the-system-cannot-find-the-path-specified-on-windows 
Maybe you can see this link and find the solution. Basicly it's the PATH problem.
