### ISSUE TITLE
Anaconda Navigator will not launch after conda upate.

### ISSUE THREAD

**Issue by rrosenfeld10** [ContinuumIO/anaconda-issues#11552]
### Actual Behavior

when I attempt to open Anaconda Navigator on my Mac, I only get a "navigator Start error with the following text:

Traceback (most recent call last):
File "/Users/a549887/anaconda3/lib/python3.7/site-packages/anaconda_navigator/exceptions.py", line 75, in exception_handler
return_value = func(*args, **kwargs)
File "/Users/a549887/anaconda3/lib/python3.7/site-packages/anaconda_navigator/app/start.py", line 151, in start_app
window = run_app(splash)
File "/Users/a549887/anaconda3/lib/python3.7/site-packages/anaconda_navigator/app/start.py", line 65, in run_app
window = MainWindow(splash=splash, tab_project=False)
File "/Users/a549887/anaconda3/lib/python3.7/site-packages/anaconda_navigator/widgets/main_window.py", line 168, in __init__
self.api = AnacondaAPI()
File "/Users/a549887/anaconda3/lib/python3.7/site-packages/anaconda_navigator/api/anaconda_api.py", line 2337, in AnacondaAPI
ANACONDA_API = _AnacondaAPI()
File "/Users/a549887/anaconda3/lib/python3.7/site-packages/anaconda_navigator/api/anaconda_api.py", line 89, in __init__
self._conda_api = CondaAPI()
File "/Users/a549887/anaconda3/lib/python3.7/site-packages/anaconda_navigator/api/conda_api.py", line 1773, in CondaAPI
CONDA_API = _CondaAPI()
File "/Users/a549887/anaconda3/lib/python3.7/site-packages/anaconda_navigator/api/conda_api.py", line 350, in __init__
self.set_conda_prefix(info=get_conda_info())
File "/Users/a549887/anaconda3/lib/python3.7/site-packages/anaconda_navigator/api/conda_api.py", line 505, in set_conda_prefix
self.ROOT_PREFIX = info['root_prefix']
KeyError: 'root_prefix'

### Expected Behavior

Expectation is for Anaconda Navigator to open so that I can work with Jupyter Lab or Notebooks.

### Steps to Reproduce

I ran conda update to update packages and conda version as it had been some time since i had updated things. Following that i restarted my machine and I am now unable to launch the Anaconda Navigator.

##### `conda info`

<details>

```
active environment : base
    active env location : /Users/a549887/anaconda3
            shell level : 1
       user config file : /Users/a549887/.condarc
 populated config files : /Users/a549887/.condarc
          conda version : 4.8.1
    conda-build version : 3.18.11
         python version : 3.7.6.final.0
       virtual packages : __osx=10.14.6
       base environment : /Users/a549887/anaconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/osx-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/osx-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /Users/a549887/anaconda3/pkgs
                          /Users/a549887/.conda/pkgs
       envs directories : /Users/a549887/anaconda3/envs
                          /Users/a549887/.conda/envs
               platform : osx-64
             user-agent : conda/4.8.1 requests/2.22.0 CPython/3.7.6 Darwin/18.7.0 OSX/10.14.6
                UID:GID : 2087728659:20
             netrc file : None
           offline mode : False

```

##### `conda list --show-channel-urls`

<details>

```
# Name                    Version                   Build  Channel
_ipyw_jlab_nb_ext_conf    0.1.0                    py37_0  
absl-py                   0.8.1                    py37_0  
anaconda-client           1.7.2                    py37_0  
anaconda-navigator        1.9.7                    py37_1  
appnope                   0.1.0                    py37_0  
asn1crypto                1.3.0                    py37_0  
astor                     0.8.0                    py37_0  
attrs                     19.3.0                     py_0  
backcall                  0.1.0                    py37_0  
backports                 1.0                        py_2  
backports.functools_lru_cache 1.6.1                      py_0  
backports.tempfile        1.0                        py_1  
backports.weakref         1.0.post1                  py_1  
beautifulsoup4            4.8.2                    py37_0  
bidict                    0.18.3                     py_0    conda-forge
blas                      1.0                    openblas  
bleach                    3.1.0                    py37_0  
boto                      2.49.0                   py37_0  
boto3                     1.10.39                    py_0  
botocore                  1.13.39                    py_0  
bz2file                   0.98                     py37_1  
bzip2                     1.0.8                h1de35cc_0  
c-ares                    1.15.0            h1de35cc_1001  
ca-certificates           2019.11.27                    0  
cachetools                3.1.1                      py_0    conda-forge
certifi                   2019.11.28               py37_0  
cffi                      1.13.2           py37hb5b8e2f_0  
chardet                   3.0.4                 py37_1003  
click                     7.0                      py37_0  
clyent                    1.2.2                    py37_1  
conda                     4.8.1                    py37_0  
conda-build               3.18.11                  py37_0  
conda-env                 2.6.0                         1  
conda-package-handling    1.6.0            py37h1de35cc_0  
conda-verify              3.4.2                      py_1  
cryptography              2.8              py37ha12b0ac_0  
cycler                    0.10.0                   py37_0  
cymem                     2.0.2            py37h04f5b5a_0  
cytoolz                   0.9.0.1          py37h1de35cc_1  
dbus                      1.13.12              h90a0687_0  
decorator                 4.4.1                      py_0  
defusedxml                0.6.0                      py_0  
dill                      0.2.9                    py37_0  
docopt                    0.6.2                    pypi_0    pypi
docutils                  0.15.2                   py37_0  
en-pytt-bertbaseuncased-lg 2.1.1                    pypi_0    pypi
entrypoints               0.3                      py37_0  
expat                     2.2.6                h0a44026_0  
filelock                  3.0.12                     py_0  
freetype                  2.9.1                hb4e5f40_0  
future                    0.18.2                   py37_0  
gast                      0.3.2                      py_0  
gensim                    3.8.0            py37h6440ff4_0  
gettext                   0.19.8.1             h15daf44_3  
glib                      2.63.1               hd977a24_0  
glob2                     0.7                        py_0  
grpcio                    1.16.1           py37h044775b_1  
h5py                      2.9.0            py37h3134771_0  
hdf5                      1.10.4               hfa1e0ec_0  
icu                       58.2                 h4b95b61_1  
idna                      2.8                      py37_0  
importlib_metadata        1.3.0                    py37_0  
ipykernel                 5.1.3            py37h39e3cac_0  
ipython                   7.11.1           py37h39e3cac_0  
ipython_genutils          0.2.0                    py37_0  
ipywidgets                7.5.1                      py_0  
jedi                      0.15.2                   py37_0  
jellyfish                 0.6.1           py37h1de35cc_1000    conda-forge
jinja2                    2.10.3                     py_0  
jmespath                  0.9.4                      py_0  
joblib                    0.14.1                     py_0  
jpeg                      9b                   he5867d9_2  
json5                     0.8.5                      py_0  
jsonschema                3.2.0                    py37_0  
jupyter_client            5.3.4                    py37_0  
jupyter_core              4.6.1                    py37_0  
jupyterlab                1.2.4              pyhf63ae98_0  
jupyterlab_server         1.0.6                      py_0  
keras                     2.2.4                         0  
keras-applications        1.0.8                      py_0  
keras-base                2.2.4                    py37_0  
keras-preprocessing       1.1.0                      py_1  
kiwisolver                1.1.0            py37h0a44026_0  
libarchive                3.3.3                h786848e_5  
libcxx                    4.0.1                hcfea43d_1  
libcxxabi                 4.0.1                hcfea43d_1  
libedit                   3.1.20181209         hb402a30_0  
libffi                    3.2.1                h475c297_4  
libgfortran               3.0.1                h93005f0_2  
libiconv                  1.15                 hdd342a3_7  
liblief                   0.9.0                h2a1bed3_2  
libopenblas               0.3.6                hdc02c5d_2  
libpng                    1.6.37               ha441bb4_0  
libprotobuf               3.11.2               hd9629dc_0  
libsodium                 1.0.16               h3efe00b_0  
libtiff                   4.1.0                hcb84e12_0  
libxml2                   2.9.9                hf6e021a_1  
lz4-c                     1.8.1.2              h1de35cc_0  
lzo                       2.10                 h362108e_2  
markdown                  3.1.1                    py37_0  
markupsafe                1.1.1            py37h1de35cc_0  
matplotlib                3.1.1            py37h54f8f79_0  
mistune                   0.8.4            py37h1de35cc_0  
more-itertools            8.0.2                      py_0  
msgpack-numpy             0.4.3.2                  py37_0  
msgpack-python            0.6.1            py37h04f5b5a_1  
murmurhash                1.0.2            py37h0a44026_0  
navigator-updater         0.2.1                    py37_0  
nbconvert                 5.6.1                    py37_0  
nbformat                  4.4.0                    py37_0  
ncurses                   6.1                  h0a44026_1  
networkx                  2.4                        py_0  
nltk                      3.4.5                    py37_0  
nltk_data                 2017.10.22                 py_0    conda-forge
notebook                  6.0.2                    py37_0  
num2words                 0.5.10                   pypi_0    pypi
numpy                     1.17.4           py37hfd23ef0_0  
numpy-base                1.17.4           py37ha711998_0  
olefile                   0.46                     py37_0  
openssl                   1.1.1d               h1de35cc_3  
pandas                    0.25.3           py37h0a44026_0  
pandoc                    2.2.3.2                       0  
pandocfilters             1.4.2                    py37_1  
parso                     0.5.2                      py_0  
patsy                     0.5.1                    py37_0  
pcre                      8.43                 h0a44026_0  
pexpect                   4.7.0                    py37_0  
pickleshare               0.7.5                    py37_0  
pillow                    7.0.0            py37h4655f20_0  
pip                       19.3.1                   py37_0  
pkginfo                   1.5.0.1                  py37_0  
plac                      0.9.6                    py37_0  
plotly                    4.4.1                      py_0  
preshed                   2.0.1            py37h0a44026_0  
prometheus_client         0.7.1                      py_0  
prompt_toolkit            3.0.2                      py_0  
protobuf                  3.9.0                    pypi_0    pypi
psutil                    5.6.7            py37h1de35cc_0  
ptyprocess                0.6.0                    py37_0  
py-lief                   0.9.0            py37h1413db1_2  
pycosat                   0.6.3            py37h1de35cc_0  
pycparser                 2.19                     py37_0  
pyemd                     0.5.1            py37h9537418_0  
pygments                  2.5.2                      py_0  
pyodbc                    4.0.27           py37h0a44026_0  
pyopenssl                 19.1.0                   py37_0  
pyparsing                 2.4.6                      py_0  
pyphen                    0.9.5                      py_0    conda-forge
pyqt                      5.9.2            py37h655552a_2  
pyrsistent                0.15.6           py37h1de35cc_0  
pysocks                   1.7.1                    py37_0  
pyspellchecker            0.5.0                    pypi_0    pypi
python                    3.7.6                h359304d_2  
python-dateutil           2.8.0                    py37_0  
python-libarchive-c       2.8                     py37_13  
python.app                2                        py37_9  
pytz                      2019.3                     py_0  
pyyaml                    5.2              py37h1de35cc_0  
pyzmq                     18.1.0           py37h0a44026_0  
qt                        5.9.7                h468cd18_1  
qtpy                      1.9.0                      py_0  
rake_nltk                 1.0.3                 py37_1000    conda-forge
rank-bm25                 0.2                      pypi_0    pypi
readline                  7.0                  h1de35cc_5  
regex                     2019.12.9        py37h1de35cc_0  
requests                  2.22.0                   py37_1  
retrying                  1.3.3                    py37_2  
ripgrep                   11.0.2               he32d670_0  
ruamel_yaml               0.15.87          py37h1de35cc_0  
s3transfer                0.2.1                    py37_0  
scikit-learn              0.20.3           py37hebd9d1a_0  
scipy                     1.3.1            py37h1a1e112_0  
seaborn                   0.9.0              pyh91ea838_1  
send2trash                1.5.0                    py37_0  
setuptools                44.0.0                   py37_0  
sip                       4.19.8           py37h0a44026_0  
six                       1.13.0                   py37_0  
smart_open                1.9.0                      py_0  
soupsieve                 1.9.5                    py37_0  
spacy                     2.0.16           py37h6440ff4_0  
spacy-model-en_core_web_lg 2.1.0              pyh0e0b3c3_0    conda-forge
spacy-model-en_core_web_md 2.1.0              pyhdea317b_0    conda-forge
sqlite                    3.30.1               ha441bb4_0  
srsly                     0.1.0            py37h6de7cb9_0    conda-forge
stanfordnlp               0.2.0                    pypi_0    pypi
statsmodels               0.10.1           py37h1d22016_0  
symspellpy                6.3.9                    pypi_0    pypi
tensorboard               1.13.1                   py37_0    conda-forge
tensorflow                1.13.1               hfddd6c2_6    conda-forge
tensorflow-base           1.13.1                   py37_6    conda-forge
tensorflow-estimator      1.13.0           py37h24bf2e0_0    conda-forge
termcolor                 1.1.0                    py37_1  
terminado                 0.8.3                    py37_0  
testpath                  0.4.4                      py_0  
textacy                   0.8.0                    py37_0    conda-forge
thinc                     6.12.1           py37hebd9d1a_0  
tk                        8.6.8                ha441bb4_0  
toolz                     0.10.0                     py_0  
torch                     1.1.0.post2              pypi_0    pypi
tornado                   6.0.3            py37h1de35cc_0  
tqdm                      4.41.1                     py_0  
traitlets                 4.3.3                    py37_0  
ujson                     1.35             py37h1de35cc_0  
unixodbc                  2.3.7                h1de35cc_0  
urllib3                   1.25.7                   py37_0  
wcwidth                   0.1.7                    py37_0  
webencodings              0.5.1                    py37_1  
werkzeug                  0.16.0                     py_0  
wheel                     0.33.6                   py37_0  
widgetsnbextension        3.5.1                    py37_0  
wrapt                     1.10.11          py37h1de35cc_2  
xlrd                      1.2.0                    py37_0  
xz                        5.2.4                h1de35cc_4  
yaml                      0.1.7                hc338f04_2  
zeromq                    4.3.1                h0a44026_3  
zipp                      0.6.0                      py_0  
zlib                      1.2.11               h1de35cc_3  
zstd                      1.3.7                h5bba6e5_0 

```

</details>

**Comment by forrestwaters** [comment]
Please try the latest anaconda-navigator 1.9.12
```
conda update anaconda-navigator
```
