### ISSUE TITLE
NAVIGATION ERROR WHEN TRYING TO OPEN

### ISSUE THREAD

**Issue by EdidiongEsu** [ContinuumIO/anaconda-issues#11567]
This error shows up when I try to load my anaconda. It started when my computer went off during a power outage. I have uninstalled it but the error still shows. PLEASE HELP!!! I tried uploading the snapshot but to no avail.
This is what shows:

Main Error
expected str, bytes or os.PathLike object, not NoneType
Traceback
Traceback (most recent call last):
  File "C:\Users\ru\Anaconda3\lib\site-packages\anaconda_navigator\exceptions.py", line 75, in exception_handler
    return_value = func(*args, **kwargs)
  File "C:\Users\ru\Anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 151, in start_app
    window = run_app(splash)
  File "C:\Users\ru\Anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 65, in run_app
    window = MainWindow(splash=splash, tab_project=False)
  File "C:\Users\ru\Anaconda3\lib\site-packages\anaconda_navigator\widgets\main_window.py", line 168, in __init__
    self.api = AnacondaAPI()
  File "C:\Users\ru\Anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 2337, in AnacondaAPI
    ANACONDA_API = _AnacondaAPI()
  File "C:\Users\ru\Anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 89, in __init__
    self._conda_api = CondaAPI()
  File "C:\Users\ru\Anaconda3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 1767, in CondaAPI
    CONDA_API = _CondaAPI()
  File "C:\Users\ru\Anaconda3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 353, in __init__
    self.sys_rc_path = join(self.ROOT_PREFIX, '.condarc')
  File "C:\Users\ru\Anaconda3\lib\ntpath.py", line 76, in join
    path = os.fspath(path)
TypeError: expected str, bytes or os.PathLike object, not NoneType

**Comment by EdidiongEsu** [comment]
![Capture](https://user-images.githubusercontent.com/54672202/72815888-a671df00-3c67-11ea-8c74-8c4d3135c3bb.JPG)

**Comment by EdidiongEsu** [comment]
I solved this by deleting `C:\Users\ru\.condarc` file.
