### ISSUE TITLE
anaconda instalation issue

### ISSUE THREAD

**Issue by ggardu** [ContinuumIO/anaconda-issues#11574]
##### `conda info`

<details>

```
PASTE OUTPUT HERE:

```

</details>

##### `conda list --show-channel-urls`

<details>

```
PASTE OUTPUT HERE:

```

</details>

**Comment by ggardu** [comment]
I have downloaded Anaconda 2019.10 from anaconda.com/distribution for Windows. Installed it. I open Jupiter like usual, and I have "kernel error". I tried to restart, it does not move, like I did nothing to it. I worked with anaconda several times, every time it worked fine. Now, it doesn't start. At a certain moment of time I receive an error like this below:
Traceback (most recent call last):
  File "C:\Users\gg\Anaconda2\lib\site-packages\tornado\web.py", line 1592, in _execute
    result = yield result
  File "C:\Users\gg\Anaconda2\lib\site-packages\tornado\gen.py", line 1133, in run
    value = future.result()
  File "C:\Users\gg\Anaconda2\lib\site-packages\tornado\concurrent.py", line 261, in result
    raise_exc_info(self._exc_info)
  File "C:\Users\gg\Anaconda2\lib\site-packages\tornado\gen.py", line 1141, in run
    yielded = self.gen.throw(*exc_info)
  File "C:\Users\gg\Anaconda2\lib\site-packages\notebook\services\sessions\handlers.py", line 73, in post
    type=mtype))
  File "C:\Users\gg\Anaconda2\lib\site-packages\tornado\gen.py", line 1133, in run
    value = future.result()
  File "C:\Users\gg\Anaconda2\lib\site-packages\tornado\concurrent.py", line 261, in result
    raise_exc_info(self._exc_info)
  File "C:\Users\gg\Anaconda2\lib\site-packages\tornado\gen.py", line 1141, in run
    yielded = self.gen.throw(*exc_info)
  File "C:\Users\gg\Anaconda2\lib\site-packages\notebook\services\sessions\sessionmanager.py", line 79, in create_session
    kernel_id = yield self.start_kernel_for_session(session_id, path, name, type, kernel_name)
  File "C:\Users\gg\Anaconda2\lib\site-packages\tornado\gen.py", line 1133, in run
    value = future.result()
  File "C:\Users\gg\Anaconda2\lib\site-packages\tornado\concurrent.py", line 261, in result
    raise_exc_info(self._exc_info)
  File "C:\Users\gg\Anaconda2\lib\site-packages\tornado\gen.py", line 1141, in run
    yielded = self.gen.throw(*exc_info)
  File "C:\Users\gg\Anaconda2\lib\site-packages\notebook\services\sessions\sessionmanager.py", line 92, in start_kernel_for_session
    self.kernel_manager.start_kernel(path=kernel_path, kernel_name=kernel_name)
  File "C:\Users\gg\Anaconda2\lib\site-packages\tornado\gen.py", line 1133, in run
    value = future.result()
  File "C:\Users\gg\Anaconda2\lib\site-packages\tornado\concurrent.py", line 261, in result
    raise_exc_info(self._exc_info)
  File "C:\Users\gg\Anaconda2\lib\site-packages\tornado\gen.py", line 326, in wrapper
    yielded = next(result)
  File "C:\Users\gg\Anaconda2\lib\site-packages\notebook\services\kernels\kernelmanager.py", line 160, in start_kernel
    super(MappingKernelManager, self).start_kernel(**kwargs)
  File "C:\Users\gg\Anaconda2\lib\site-packages\jupyter_client\multikernelmanager.py", line 110, in start_kernel
    km.start_kernel(**kwargs)
  File "C:\Users\gg\Anaconda2\lib\site-packages\jupyter_client\manager.py", line 240, in start_kernel
    self.write_connection_file()
  File "C:\Users\gg\Anaconda2\lib\site-packages\jupyter_client\connect.py", line 547, in write_connection_file
    kernel_name=self.kernel_name
  File "C:\Users\gg\Anaconda2\lib\site-packages\jupyter_client\connect.py", line 212, in write_connection_file
    with secure_write(fname) as f:
  File "C:\Users\gg\Anaconda2\lib\contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "C:\Users\gg\Anaconda2\lib\site-packages\jupyter_client\connect.py", line 102, in secure_write
    with os.fdopen(os.open(fname, open_flag, 0o600), mode) as f:
OSError: [Errno 13] Permission denied

I used: python -m ipykernel install --user
and it sayd that python kernel is already installed.
I have tried all version from anaconda.com/distribution for Windows 10, all have this kernel issue.
Could you help me, please ?
Thank you.

**Comment by csoja** [comment]
Do you have write permissions to C:\Users\gg\Anaconda2\lib\site-packages\jupyter_client\connect.py ? The error you've pasted in says "Permission denied".
