### ISSUE TITLE
Error for `jupyter nbconvert` on Windows

### ISSUE THREAD

**Issue by StrikerRUS** [ContinuumIO/anaconda-issues#11598]
### Actual Behavior

```

[NbConvertApp] Converting notebook interactive_plot_example.ipynb to notebook
996
Traceback (most recent call last):
997
  File "C:\Miniconda36-x64\envs\test-env\Scripts\jupyter-nbconvert-script.py", line 10, in <module>
998
    sys.exit(main())
999
  File "C:\Miniconda36-x64\envs\test-env\lib\site-packages\jupyter_core\application.py", line 268, in launch_instance
1000
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
1001
  File "C:\Miniconda36-x64\envs\test-env\lib\site-packages\traitlets\config\application.py", line 664, in launch_instance
1002
    app.start()
1003
  File "C:\Miniconda36-x64\envs\test-env\lib\site-packages\nbconvert\nbconvertapp.py", line 340, in start
1004
    self.convert_notebooks()
1005
  File "C:\Miniconda36-x64\envs\test-env\lib\site-packages\nbconvert\nbconvertapp.py", line 510, in convert_notebooks
1006
    self.convert_single_notebook(notebook_filename)
1007
  File "C:\Miniconda36-x64\envs\test-env\lib\site-packages\nbconvert\nbconvertapp.py", line 481, in convert_single_notebook
1008
    output, resources = self.export_single_notebook(notebook_filename, resources, input_buffer=input_buffer)
1009
  File "C:\Miniconda36-x64\envs\test-env\lib\site-packages\nbconvert\nbconvertapp.py", line 410, in export_single_notebook
1010
    output, resources = self.exporter.from_filename(notebook_filename, resources=resources)
1011
  File "C:\Miniconda36-x64\envs\test-env\lib\site-packages\nbconvert\exporters\exporter.py", line 179, in from_filename
1012
    return self.from_file(f, resources=resources, **kw)
1013
  File "C:\Miniconda36-x64\envs\test-env\lib\site-packages\nbconvert\exporters\exporter.py", line 197, in from_file
1014
    return self.from_notebook_node(nbformat.read(file_stream, as_version=4), resources=resources, **kw)
1015
  File "C:\Miniconda36-x64\envs\test-env\lib\site-packages\nbconvert\exporters\notebook.py", line 32, in from_notebook_node
1016
    nb_copy, resources = super(NotebookExporter, self).from_notebook_node(nb, resources, **kw)
1017
  File "C:\Miniconda36-x64\envs\test-env\lib\site-packages\nbconvert\exporters\exporter.py", line 139, in from_notebook_node
1018
    nb_copy, resources = self._preprocess(nb_copy, resources)
1019
  File "C:\Miniconda36-x64\envs\test-env\lib\site-packages\nbconvert\exporters\exporter.py", line 316, in _preprocess
1020
    nbc, resc = preprocessor(nbc, resc)
1021
  File "C:\Miniconda36-x64\envs\test-env\lib\site-packages\nbconvert\preprocessors\base.py", line 47, in __call__
1022
    return self.preprocess(nb, resources)
1023
  File "C:\Miniconda36-x64\envs\test-env\lib\site-packages\nbconvert\preprocessors\execute.py", line 403, in preprocess
1024
    with self.setup_preprocessor(nb, resources, km=km):
1025
  File "C:\Miniconda36-x64\envs\test-env\lib\contextlib.py", line 81, in __enter__
1026
    return next(self.gen)
1027
  File "C:\Miniconda36-x64\envs\test-env\lib\site-packages\nbconvert\preprocessors\execute.py", line 345, in setup_preprocessor
1028
    self.km, self.kc = self.start_new_kernel(**kwargs)
1029
  File "C:\Miniconda36-x64\envs\test-env\lib\site-packages\nbconvert\preprocessors\execute.py", line 288, in start_new_kernel
1030
    config=self.config)
1031
  File "C:\Miniconda36-x64\envs\test-env\lib\site-packages\traitlets\traitlets.py", line 958, in __new__
1032
    inst.setup_instance(*args, **kwargs)
1033
  File "C:\Miniconda36-x64\envs\test-env\lib\site-packages\traitlets\traitlets.py", line 986, in setup_instance
1034
    super(HasTraits, self).setup_instance(*args, **kwargs)
1035
  File "C:\Miniconda36-x64\envs\test-env\lib\site-packages\traitlets\traitlets.py", line 977, in setup_instance
1036
    value.instance_init(self)
1037
  File "C:\Miniconda36-x64\envs\test-env\lib\site-packages\traitlets\traitlets.py", line 1691, in instance_init
1038
    self._resolve_classes()
1039
  File "C:\Miniconda36-x64\envs\test-env\lib\site-packages\traitlets\traitlets.py", line 1696, in _resolve_classes
1040
    self.klass = self._resolve_string(self.klass)
1041
  File "C:\Miniconda36-x64\envs\test-env\lib\site-packages\traitlets\traitlets.py", line 1507, in _resolve_string
1042
    return import_item(string)
1043
  File "C:\Miniconda36-x64\envs\test-env\lib\site-packages\traitlets\utils\importstring.py", line 34, in import_item
1044
    module = __import__(package, fromlist=[obj])
1045
  File "C:\Miniconda36-x64\envs\test-env\lib\site-packages\jupyter_client\session.py", line 56, in <module>
1046
    from zmq.eventloop.ioloop import IOLoop
1047
  File "C:\Miniconda36-x64\envs\test-env\lib\site-packages\zmq\eventloop\__init__.py", line 3, in <module>
1048
    from zmq.eventloop.ioloop import IOLoop
1049
  File "C:\Miniconda36-x64\envs\test-env\lib\site-packages\zmq\eventloop\ioloop.py", line 78, in <module>
1050
    while _IOLoop.configurable_default() is not _IOLoop:
1051
  File "C:\Miniconda36-x64\envs\test-env\lib\site-packages\tornado\ioloop.py", line 328, in configurable_default
1052
    from tornado.platform.asyncio import AsyncIOLoop
1053
  File "C:\Miniconda36-x64\envs\test-env\lib\site-packages\tornado\platform\asyncio.py", line 34, in <module>
1054
    asyncio.set_event_loop_policy(asyncio.WindowsSelectorEventLoopPolicy())
1055
AttributeError: module 'asyncio' has no attribute 'WindowsSelectorEventLoopPolicy'
1056
Command exited with code 1
```

### Expected Behavior

Successful conversion.

### Steps to Reproduce

```
conda install -q -y -n test-env ipywidgets notebook
jupyter nbconvert --ExecutePreprocessor.timeout=180 --to notebook --execute --inplace *.ipynb
```

##### `conda info`

<details>

```
7
conda info
858
859
     active environment : test-env
860
    active env location : C:\Miniconda36-x64\envs\test-env
861
            shell level : 2
862
       user config file : C:\Users\appveyor\.condarc
863
 populated config files : C:\Users\appveyor\.condarc
864
          conda version : 4.8.2
865
    conda-build version : not installed
866
         python version : 3.6.5.final.0
867
       virtual packages : 
868
       base environment : C:\Miniconda36-x64  (writable)
869
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
870
                          https://repo.anaconda.com/pkgs/main/noarch
871
                          https://repo.anaconda.com/pkgs/r/win-64
872
                          https://repo.anaconda.com/pkgs/r/noarch
873
                          https://repo.anaconda.com/pkgs/msys2/win-64
874
                          https://repo.anaconda.com/pkgs/msys2/noarch
875
          package cache : C:\Miniconda36-x64\pkgs
876
                          C:\Users\appveyor\.conda\pkgs
877
                          C:\Users\appveyor\AppData\Local\conda\conda\pkgs
878
       envs directories : C:\Miniconda36-x64\envs
879
                          C:\Users\appveyor\.conda\envs
880
                          C:\Users\appveyor\AppData\Local\conda\conda\envs
881
               platform : win-64
882
             user-agent : conda/4.8.2 requests/2.18.4 CPython/3.6.5 Windows/2012ServerR2 Windows/6.3.9600
883
          administrator : True
884
             netrc file : None
885
           offline mode : False

```

</details>

##### `conda list --show-channel-urls`

<details>

```

conda list --show-channel-urls
888
# packages in environment at C:\Miniconda36-x64\envs\test-env:
889
#
890
# Name                    Version                   Build  Channel
891
atomicwrites              1.3.0                    py36_1    defaults
892
attrs                     19.3.0                     py_0    defaults
893
backcall                  0.1.0                    py36_0    defaults
894
blas                      1.0                         mkl    defaults
895
bleach                    3.1.0                    py36_0    defaults
896
ca-certificates           2020.1.1                      0    defaults
897
certifi                   2019.11.28               py36_0    defaults
898
colorama                  0.4.3                      py_0    defaults
899
cycler                    0.10.0           py36h009560c_0    defaults
900
decorator                 4.4.1                      py_0    defaults
901
defusedxml                0.6.0                      py_0    defaults
902
entrypoints               0.3                      py36_0    defaults
903
freetype                  2.9.1                ha9979f8_1    defaults
904
graphviz                  2.38                 hfd603c8_2    defaults
905
icc_rt                    2019.0.0             h0cc432a_1    defaults
906
icu                       58.2                 ha66f8fd_1    defaults
907
importlib_metadata        1.5.0                    py36_0    defaults
908
inflect                   4.1.0                    py36_0    defaults
909
intel-openmp              2020.0                      166    defaults
910
ipykernel                 5.1.4            py36h39e3cac_0    defaults
911
ipython                   7.12.0           py36h5ca1d4c_0    defaults
912
ipython_genutils          0.2.0                    py36_0    defaults
913
ipywidgets                7.5.1                      py_0    defaults
914
jaraco.itertools          5.0.0                      py_0    defaults
915
jedi                      0.16.0                   py36_0    defaults
916
jinja2                    2.11.1                     py_0    defaults
917
joblib                    0.14.1                     py_0    defaults
918
jpeg                      9b                   hb83a4c4_2    defaults
919
jsonschema                3.2.0                    py36_0    defaults
920
jupyter_client            5.3.4                    py36_0    defaults
921
jupyter_core              4.6.1                    py36_0    defaults
922
kiwisolver                1.1.0            py36ha925a31_0    defaults
923
libpng                    1.6.37               h2a8f88b_0    defaults
924
libsodium                 1.0.16               h9d3ae62_0    defaults
925
lightgbm                  2.3.2                    pypi_0    pypi
926
m2w64-gcc-libgfortran     5.3.0                         6    defaults
927
m2w64-gcc-libs            5.3.0                         7    defaults
928
m2w64-gcc-libs-core       5.3.0                         7    defaults
929
m2w64-gmp                 6.1.0                         2    defaults
930
m2w64-libwinpthread-git   5.0.0.4634.697f757               2    defaults
931
markupsafe                1.1.1            py36he774522_0    defaults
932
matplotlib                3.1.3                    py36_0    defaults
933
matplotlib-base           3.1.3            py36h64f37c6_0    defaults
934
mistune                   0.8.4            py36he774522_0    defaults
935
mkl                       2020.0                      166    defaults
936
mkl-service               2.3.0            py36hb782905_0    defaults
937
mkl_fft                   1.0.15           py36h14836fe_0    defaults
938
mkl_random                1.1.0            py36h675688f_0    defaults
939
more-itertools            8.2.0                      py_0    defaults
940
msys2-conda-epoch         20160418                      1    defaults
941
nbconvert                 5.6.1                    py36_0    defaults
942
nbformat                  5.0.4                      py_0    defaults
943
notebook                  6.0.3                    py36_0    defaults
944
numpy                     1.18.1           py36h93ca92e_0    defaults
945
numpy-base                1.18.1           py36hc3f5095_1    defaults
946
openssl                   1.1.1d               he774522_3    defaults
947
packaging                 20.1                       py_0    defaults
948
pandas                    1.0.0            py36h47e9c7a_0    defaults
949
pandoc                    2.2.3.2                       0    defaults
950
pandocfilters             1.4.2                    py36_1    defaults
951
parso                     0.6.0                      py_0    defaults
952
pickleshare               0.7.5                    py36_0    defaults
953
pip                       20.0.2                   py36_1    defaults
954
pluggy                    0.13.1                   py36_0    defaults
955
prometheus_client         0.7.1                      py_0    defaults
956
prompt_toolkit            3.0.3                      py_0    defaults
957
psutil                    5.6.7            py36he774522_0    defaults
958
py                        1.8.1                      py_0    defaults
959
pygments                  2.5.2                      py_0    defaults
960
pyparsing                 2.4.6                      py_0    defaults
961
pyqt                      5.9.2            py36h6538335_2    defaults
962
pyrsistent                0.15.7           py36he774522_0    defaults
963
pytest                    5.3.5                    py36_0    defaults
964
python                    3.6.10               h9f7ef89_0    defaults
965
python-dateutil           2.8.1                      py_0    defaults
966
python-graphviz           0.13.2                     py_0    defaults
967
pytz                      2019.3                     py_0    defaults
968
pywin32                   227              py36he774522_1    defaults
969
pywinpty                  0.5.7                    py36_0    defaults
970
pyzmq                     18.1.1           py36ha925a31_0    defaults
971
qt                        5.9.7            vc14h73c81de_0    defaults
972
scikit-learn              0.21.3           py36h6288b17_0    defaults
973
scipy                     1.4.1            py36h9439919_0    defaults
974
send2trash                1.5.0                    py36_0    defaults
975
setuptools                45.1.0                   py36_0    defaults
976
sip                       4.19.8           py36h6538335_0    defaults
977
six                       1.14.0                   py36_0    defaults
978
sqlite                    3.31.1               he774522_0    defaults
979
terminado                 0.8.3                    py36_0    defaults
980
testpath                  0.4.4                      py_0    defaults
981
tornado                   6.0.3            py36he774522_1    defaults
982
traitlets                 4.3.3                    py36_0    defaults
983
vc                        14.1                 h0510ff6_4    defaults
984
vs2015_runtime            14.16.27012          hf0eaf9b_1    defaults
985
wcwidth                   0.1.8                      py_0    defaults
986
webencodings              0.5.1                    py36_1    defaults
987
wheel                     0.34.2                   py36_0    defaults
988
widgetsnbextension        3.5.1                    py36_0    defaults
989
wincertstore              0.2              py36h7fe50ca_0    defaults
990
winpty                    0.4.3                         4    defaults
991
zeromq                    4.3.1                h33f27b4_3    defaults
992
zipp                      2.1.0                      py_0    defaults
993
zlib                      1.2.11               h62dcd97_3    defaults

```

</details>

**Comment by StrikerRUS** [comment]
Closing as I'm no longer have access to the environment and will not be able to confirm fixes.
