### ISSUE TITLE
UnboundLocalError:  Anaconda navigator got struck in loading applications screen

### ISSUE THREAD

**Issue by simplesand** [ContinuumIO/anaconda-issues#11642]
I too have same problem, anaconda navigator got struck in loading applications screen

$anaconda-navigator --version
```1.9.12```

**OS Info**
```
DISTRIB_ID=neon
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="KDE neon User Edition 5.18"
```

```
Traceback (most recent call last):
  File "/home/siddharth/anaconda3/lib/python3.7/site-packages/anaconda_navigator/widgets/main_window.py", line 541, in setup
    self.post_setup(conda_data=conda_data)
  File "/home/siddharth/anaconda3/lib/python3.7/site-packages/anaconda_navigator/widgets/main_window.py", line 578, in post_setup
    self.tab_home.setup(conda_data)
  File "/home/siddharth/anaconda3/lib/python3.7/site-packages/anaconda_navigator/widgets/tabs/home.py", line 169, in setup
    self.set_applications(applications, packages)
  File "/home/siddharth/anaconda3/lib/python3.7/site-packages/anaconda_navigator/widgets/tabs/home.py", line 204, in set_applications
    apps = self.api.process_apps(applications, prefix=self.current_prefix)
  File "/home/siddharth/anaconda3/lib/python3.7/site-packages/anaconda_navigator/api/anaconda_api.py", line 848, in process_apps
    app = app(config=self.config, process_api=self._process_api, conda_api=self._conda_api)
  File "/home/siddharth/anaconda3/lib/python3.7/site-packages/anaconda_navigator/api/external_apps/vscode.py", line 48, in __init__
    **kwargs
  File "/home/siddharth/anaconda3/lib/python3.7/site-packages/anaconda_navigator/api/external_apps/base.py", line 43, in __init__
    self.init()
  File "/home/siddharth/anaconda3/lib/python3.7/site-packages/anaconda_navigator/api/external_apps/base.py", line 60, in init
    SUBDIR, INST_EXT, INST_DIR = self._find_linux_install_dir()
  File "/home/siddharth/anaconda3/lib/python3.7/site-packages/anaconda_navigator/api/external_apps/vscode.py", line 168, in _find_linux_install_dir
    if DISTRO_NAME in ['ubuntu', 'debian']:
UnboundLocalError: local variable 'DISTRO_NAME' referenced before assignment
```

_Originally posted by @simplesand in https://github.com/ContinuumIO/anaconda-issues/issues/11635#issuecomment-593785644_

**Comment by forrestwaters** [comment]
Please see https://github.com/ContinuumIO/anaconda-issues/issues/11635#issuecomment-594494001. Closing to consolidate discussion.

**Comment by rjavierch** [comment]
> Please see [#11635 (comment)](https://github.com/ContinuumIO/anaconda-issues/issues/11635#issuecomment-594494001). Closing to consolidate discussion.

Thanks! it worked for me.
