### ISSUE TITLE
Anaconda Navigator error: 'list' object has no attribute 'get'

### ISSUE THREAD

**Issue by Fulvioo** [ContinuumIO/anaconda-issues#11644]
### Actual Behavior

Anaconda Navigator doesn't start

### Expected Behavior

It shoud start

### Steps to Reproduce

Well. It's hard to describe.
I had a working installation of Anaconda, Python with a tf env, all working till yesterday.
Having had a problem with Scipy DLL I decided to reinstall everything from the ground. I havent uninstalled the previous version but simply renamed the folder Anaconda3 to Anaconda3_old.

Then I installed the new version to Anaconda3 dir.
This error happened after a crash on Spyder idle kernel.
Anaconda Navigator it was open at the time of the crash, but the it doesn't open anymore.
Anaconda Powershell says:
```
Direttiva utilizzo mancante
In C:\Users\fulvio\Anaconda3\shell\condabin\Conda.psm1:101 car:9
+         Invoke-Expression -Command $activateCommand;
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ParserError: (:) [Invoke-Expression], ParseException
    + FullyQualifiedErrorId : MissingUsingStatementDirective,Microsoft.PowerShell.Commands.InvokeExpressionCommand
```

##### Anaconda or Miniconda version:

Anaconda3-2019.10-Windows-x86_64

##### Operating System:
Win10
##### `conda info`

```
Traceback (most recent call last):
  File "C:\Users\fulvio\Anaconda3\lib\site-packages\anaconda_navigator\exceptions.py", line 75, in exception_handler
    return_value = func(*args, **kwargs)
  File "C:\Users\fulvio\Anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 151, in start_app
    window = run_app(splash)
  File "C:\Users\fulvio\Anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 65, in run_app
    window = MainWindow(splash=splash, tab_project=False)
  File "C:\Users\fulvio\Anaconda3\lib\site-packages\anaconda_navigator\widgets\main_window.py", line 170, in __init__
    self.api = AnacondaAPI()
  File "C:\Users\fulvio\Anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 1525, in AnacondaAPI
    ANACONDA_API = _AnacondaAPI()
  File "C:\Users\fulvio\Anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 77, in __init__
    self._conda_api = CondaAPI()
  File "C:\Users\fulvio\Anaconda3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 1804, in CondaAPI
    CONDA_API = _CondaAPI()
  File "C:\Users\fulvio\Anaconda3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 371, in __init__
    self.set_conda_prefix(info=get_conda_info())
  File "C:\Users\fulvio\Anaconda3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 533, in set_conda_prefix
    self.ROOT_PREFIX = info.get('root_prefix')
AttributeError: 'list' object has no attribute 'get'

```

**Comment by Fulvioo** [comment]
After uninstalling all the previous versions of Anaconda and Python (3.7, 3.6, 3.4) and re installing everything, now it appears everything's working properly

**Comment by Berurin** [comment]
I had the same Anaconda Navigator error, but after uninstalling all the previous versions of Anaconda and Python (3.7, 3.6, 3.4) and
it didn't work. I wanna know how I can do?

**Comment by franva** [comment]
https://github.com/conda/conda/issues/10349
