### ISSUE TITLE
Failed to install jupyter on Miniconda

### ISSUE THREAD

**Issue by xq114** [ContinuumIO/anaconda-issues#11659]
### Actual Behavior

When I tried to install jupyter on Miniconda, I ran into an error like this:
```
(base) PS C:\Users\xq114> conda install jupyter 
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: - 
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "C:\Users\xq114\_src\bin\Miniconda3\lib\site-packages\conda\cli\install.py", line 265, in install     
        should_retry_solve=(_should_retry_unfrozen or repodata_fn != repodata_fns[-1]),
      File "C:\Users\xq114\_src\bin\Miniconda3\lib\site-packages\conda\core\solve.py", line 117, in solve_for_transaction
        should_retry_solve)
      File "C:\Users\xq114\_src\bin\Miniconda3\lib\site-packages\conda\core\solve.py", line 158, in solve_for_diff
        force_remove, should_retry_solve)
      File "C:\Users\xq114\_src\bin\Miniconda3\lib\site-packages\conda\core\solve.py", line 275, in solve_final_state
        ssc = self._add_specs(ssc)
      File "C:\Users\xq114\_src\bin\Miniconda3\lib\site-packages\conda\core\solve.py", line 696, in _add_specs   
        raise UnsatisfiableError({})
    conda.exceptions.UnsatisfiableError:
    Did not find conflicting dependencies. If you would like to know which
    packages conflict ensure that you have enabled unsatisfiable hints.

    conda config --set unsatisfiable_hints True


    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "C:\Users\xq114\_src\bin\Miniconda3\lib\site-packages\conda\exceptions.py", line 1079, in __call__    
        return func(*args, **kwargs)
      File "C:\Users\xq114\_src\bin\Miniconda3\lib\site-packages\conda\cli\main.py", line 84, in _main
        exit_code = do_call(args, p)
      File "C:\Users\xq114\_src\bin\Miniconda3\lib\site-packages\conda\cli\conda_argparse.py", line 82, in do_call
        return getattr(module, func_name)(args, parser)
      File "C:\Users\xq114\_src\bin\Miniconda3\lib\site-packages\conda\cli\main_install.py", line 20, in execute 
        install(args, parser, 'install')
      File "C:\Users\xq114\_src\bin\Miniconda3\lib\site-packages\conda\cli\install.py", line 299, in install     
        should_retry_solve=(repodata_fn != repodata_fns[-1]),
      File "C:\Users\xq114\_src\bin\Miniconda3\lib\site-packages\conda\core\solve.py", line 117, in solve_for_transaction
        should_retry_solve)
      File "C:\Users\xq114\_src\bin\Miniconda3\lib\site-packages\conda\core\solve.py", line 158, in solve_for_diff
        force_remove, should_retry_solve)
      File "C:\Users\xq114\_src\bin\Miniconda3\lib\site-packages\conda\core\solve.py", line 275, in solve_final_state
        ssc = self._add_specs(ssc)
      File "C:\Users\xq114\_src\bin\Miniconda3\lib\site-packages\conda\core\solve.py", line 694, in _add_specs   
        ssc.r.find_conflicts(spec_set)
      File "C:\Users\xq114\_src\bin\Miniconda3\lib\site-packages\conda\resolve.py", line 347, in find_conflicts  
        bad_deps = self.build_conflict_map(specs, specs_to_add, history_specs)
      File "C:\Users\xq114\_src\bin\Miniconda3\lib\site-packages\conda\resolve.py", line 507, in build_conflict_map
        root, search_node, dep_graph, num_occurances)
      File "C:\Users\xq114\_src\bin\Miniconda3\lib\site-packages\conda\resolve.py", line 369, in breadth_first_search_for_dep_graph
        last_spec = MatchSpec.union((path[-1], target_paths[-1][-1]))[0]
      File "C:\Users\xq114\_src\bin\Miniconda3\lib\site-packages\conda\models\match_spec.py", line 481, in union 
        return cls.merge(match_specs, union=True)
      File "C:\Users\xq114\_src\bin\Miniconda3\lib\site-packages\conda\models\match_spec.py", line 475, in merge 
        reduce(lambda x, y: x._merge(y, union), group) if len(group) > 1 else group[0]
      File "C:\Users\xq114\_src\bin\Miniconda3\lib\site-packages\conda\models\match_spec.py", line 475, in <lambda>
        reduce(lambda x, y: x._merge(y, union), group) if len(group) > 1 else group[0]
      File "C:\Users\xq114\_src\bin\Miniconda3\lib\site-packages\conda\models\match_spec.py", line 502, in _merge
        final = this_component.union(that_component)
      File "C:\Users\xq114\_src\bin\Miniconda3\lib\site-packages\conda\models\match_spec.py", line 764, in union 
        return '|'.join(options)
    TypeError: sequence item 0: expected str instance, Channel found

`$ C:\Users\xq114\_src\bin\Miniconda3\Scripts\conda-script.py install jupyter`

  environment variables:
                 CIO_TEST=<not set>
        CONDA_DEFAULT_ENV=base
                CONDA_EXE=C:\Users\xq114\_src\bin\Miniconda3\Scripts\conda.exe
             CONDA_PREFIX=C:\Users\xq114\_src\bin\Miniconda3
    CONDA_PROMPT_MODIFIER=(base)
         CONDA_PYTHON_EXE=C:\Users\xq114\_src\bin\Miniconda3\python.exe
               CONDA_ROOT=C:\Users\xq114\_src\bin\Miniconda3
              CONDA_SHLVL=1
                 HOMEPATH=\Users\xq114
                     PATH=C:\Users\xq114\_src\bin\Miniconda3;C:\Users\xq114\_src\bin\Miniconda3\
                          Library\mingw-w64\bin;C:\Users\xq114\_src\bin\Miniconda3\Library\usr\b
                          in;C:\Users\xq114\_src\bin\Miniconda3\Library\bin;C:\Users\xq114\_src\
                          bin\Miniconda3\Scripts;C:\Users\xq114\_src\bin\Miniconda3\bin;C:\Users
                          \xq114\_src\bin\Miniconda3;C:\Users\xq114\_src\bin\Miniconda3\Library\
                          mingw-w64\bin;C:\Users\xq114\_src\bin\Miniconda3\Library\usr\bin;C:\Us
                          ers\xq114\_src\bin\Miniconda3\Library\bin;C:\Users\xq114\_src\bin\Mini
                          conda3\Scripts;C:\Users\xq114\_src\bin\Miniconda3\bin;C:\Users\xq114\_
                          src\bin\Miniconda3;C:\Users\xq114\_src\bin\Miniconda3\Library\mingw-w6
                          4\bin;C:\Users\xq114\_src\bin\Miniconda3\Library\usr\bin;C:\Users\xq11
                          4\_src\bin\Miniconda3\Library\bin;C:\Users\xq114\_src\bin\Miniconda3\S
                          cripts;C:\Users\xq114\_src\bin\Miniconda3\bin;C:\Users\xq114\_src\bin\
                          Miniconda3\condabin;C:\Program Files (x86)\Common Files\Oracle\Java\ja
                          vapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WIND
                          OWS\System32\WindowsPowerShell\v1.0;C:\WINDOWS\System32\OpenSSH;C:\Pro
                          gram Files (x86)\NVIDIA Corporation\PhysX\Common;C:\ProgramData\chocol
                          atey\bin;C:\Users\xq114\_src\bin\nvm;C:\Users\xq114\_src\bin\nodejs;C:
                          \Users\xq114\_src\bin\Calibre;C:\Program Files (x86)\Intel\Intel(R)
                          Management Engine Components\DAL;C:\Program Files\Intel\Intel(R)
                          Management Engine Components\DAL;C:\Program Files (x86)\Common
                          Files\Acronis\VirtualFile;C:\Program Files (x86)\Common
                          Files\Acronis\VirtualFile64;C:\Program Files (x86)\Common
                          Files\Acronis\FileProtector;C:\Program Files (x86)\Common
                          Files\Acronis\FileProtector64;C:\Program Files (x86)\Common Files\Acro
                          nis\SnapAPI;C:\Users\xq114\_src\bin;C:\Users\xq114\_src\local\bin;C:\U
                          sers\xq114\_src\bin\msys64;C:\Users\xq114\_src\bin\msys64\mingw64\bin;
                          C:\Users\xq114\_src\bin\msys64\usr\bin;C:\Users\xq114\_src\bin\Julia-1
                          .3.1\bin;C:\Users\xq114\_src\bin\MiKTeX 2.9\miktex\bin\x64;C:\Users\xq
                          114\_src\bin\nvm;C:\Users\xq114\_src\bin\nodejs;C:\Users\xq114\AppData
                          \Local\Microsoft\WindowsApps;.
             PSMODULEPATH=C:\Users\xq114\Documents\WindowsPowerShell\Modules;C:\Program Files\Wi
                          ndowsPowerShell\Modules;C:\WINDOWS\system32\WindowsPowerShell\v1.0\Mod
                          ules
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>

     active environment : base
    active env location : C:\Users\xq114\_src\bin\Miniconda3
            shell level : 1
       user config file : C:\Users\xq114\.condarc
 populated config files : C:\Users\xq114\.condarc
          conda version : 4.8.2
    conda-build version : not installed
         python version : 3.7.6.final.0
       virtual packages : __cuda=10.2
       base environment : C:\Users\xq114\_src\bin\Miniconda3  (writable)
           channel URLs : https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/win-64
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/noarch
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/win-64
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/noarch
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/r/win-64
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/r/noarch
          package cache : C:\Users\xq114\_src\bin\Miniconda3\pkgs
                          C:\Users\xq114\.conda\pkgs
                          C:\Users\xq114\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\xq114\_src\bin\Miniconda3\envs
                          C:\Users\xq114\.conda\envs
                          C:\Users\xq114\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.8.2 requests/2.22.0 CPython/3.7.6 Windows/10 Windows/10.0.18362
          administrator : False
             netrc file : None
           offline mode : False


An unexpected error has occurred. Conda has prepared the above report.

If submitted, this report will be used by core maintainers to improve
future releases of conda.
Would you like conda to send this report to the core maintainers?

Upload successful.

Thank you for helping to improve conda.
Opt-in to always sending reports (and not see this message again)
by running

    $ conda config --set report_errors true

```

### Expected Behavior

Install jupyter normally.

### Steps to Reproduce

I downloaded Miniconda, set the channels(or the network connection would be very slow) and tried to install jupyter(I wander if it is related to gpu/cuda, My gpu is Nvidia GeForce with cuda version 10.2)

##### Anaconda or Miniconda version:
Miniconda3 latest

##### Operating System:
Windows 10 1909

##### `conda info`

<details>

```
     active environment : base
    active env location : C:\Users\xq114\_src\bin\Miniconda3
            shell level : 1
       user config file : C:\Users\xq114\.condarc
 populated config files : C:\Users\xq114\.condarc
          conda version : 4.8.2
    conda-build version : not installed
         python version : 3.7.6.final.0
       virtual packages : __cuda=10.2
       base environment : C:\Users\xq114\_src\bin\Miniconda3  (writable)
           channel URLs : https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/win-64
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/noarch
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/win-64
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/noarch
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/r/win-64
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/r/noarch
          package cache : C:\Users\xq114\_src\bin\Miniconda3\pkgs
                          C:\Users\xq114\.conda\pkgs
                          C:\Users\xq114\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\xq114\_src\bin\Miniconda3\envs
                          C:\Users\xq114\.conda\envs
                          C:\Users\xq114\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.8.2 requests/2.22.0 CPython/3.7.6 Windows/10 Windows/10.0.18362
          administrator : False
             netrc file : None
           offline mode : False
```

</details>

##### `conda list --show-channel-urls`

<details>

```
# packages in environment at C:\Users\xq114\_src\bin\Miniconda3:
#
# Name                    Version                   Build  Channel
asn1crypto                1.3.0                    py37_0    https://repo.anaconda.com/pkgs/main
ca-certificates           2020.1.1                      0    https://repo.anaconda.com/pkgs/main
certifi                   2019.11.28               py37_0    https://repo.anaconda.com/pkgs/main
cffi                      1.14.0           py37h7a1dbc1_0    https://repo.anaconda.com/pkgs/main
chardet                   3.0.4                 py37_1003    https://repo.anaconda.com/pkgs/main
conda                     4.8.2                    py37_0    https://repo.anaconda.com/pkgs/main
conda-package-handling    1.6.0            py37h62dcd97_0    https://repo.anaconda.com/pkgs/main
console_shortcut          0.1.1                         4    https://repo.anaconda.com/pkgs/main
cryptography              2.8              py37h7a1dbc1_0    https://repo.anaconda.com/pkgs/main
idna                      2.8                      py37_0    https://repo.anaconda.com/pkgs/main
menuinst                  1.4.16           py37he774522_0    https://repo.anaconda.com/pkgs/main
openssl                   1.1.1d               he774522_4    https://repo.anaconda.com/pkgs/main
pip                       20.0.2                   py37_1    https://repo.anaconda.com/pkgs/main
powershell_shortcut       0.0.1                         3    https://repo.anaconda.com/pkgs/main
pycosat                   0.6.3            py37he774522_0    https://repo.anaconda.com/pkgs/main
pycparser                 2.19                     py37_0    https://repo.anaconda.com/pkgs/main
pyopenssl                 19.1.0                   py37_0    https://repo.anaconda.com/pkgs/main
pysocks                   1.7.1                    py37_0    https://repo.anaconda.com/pkgs/main
python                    3.7.6                h60c2a47_2    https://repo.anaconda.com/pkgs/main
pywin32                   227              py37he774522_1    https://repo.anaconda.com/pkgs/main
requests                  2.22.0                   py37_1    https://repo.anaconda.com/pkgs/main
ruamel_yaml               0.15.87          py37he774522_0    https://repo.anaconda.com/pkgs/main
setuptools                45.2.0                   py37_0    https://repo.anaconda.com/pkgs/main
six                       1.14.0                   py37_0    https://repo.anaconda.com/pkgs/main
sqlite                    3.31.1               he774522_0    https://repo.anaconda.com/pkgs/main
tqdm                      4.42.1                     py_0    https://repo.anaconda.com/pkgs/main
urllib3                   1.25.8                   py37_0    https://repo.anaconda.com/pkgs/main
vc                        14.1                 h0510ff6_4    https://repo.anaconda.com/pkgs/main
vs2015_runtime            14.16.27012          hf0eaf9b_1    https://repo.anaconda.com/pkgs/main
wheel                     0.34.2                   py37_0    https://repo.anaconda.com/pkgs/main
win_inet_pton             1.1.0                    py37_0    https://repo.anaconda.com/pkgs/main
wincertstore              0.2                      py37_0    https://repo.anaconda.com/pkgs/main
yaml                      0.1.7                hc54c509_2    https://repo.anaconda.com/pkgs/main
```

</details>

**Comment by xq114** [comment]
It seems related to the mirror. closed.
