### ISSUE TITLE
Navigator Error.An unexpected error occurred on Navigator start-up

### ISSUE THREAD

**Issue by SandeepKR23** [ContinuumIO/anaconda-issues#11656]
### Actual Behavior

I tried launching the Anaconda navigator,later ended up in error message

    <html>
    <head>
      <title>Navigator Error</title>
    </head>
    <body>
      <div>
        <h1>Navigator Error</h1>
        <p>An unexpected error occurred on Navigator start-up</p>
        <h2>Report</h2>
        <p>Please report this issue in the anaconda
          <a href="https://github.com/continuumio/anaconda-issues">
            issue tracker
          </a>
        </p>
      </div>
      <div>
        <h2>Main Error</h2>
        <p><pre>expected str, bytes or os.PathLike object, not NoneType</pre></p>
        <h2>Traceback</h2>
        <p><pre>Traceback (most recent call last):
  File "C:\Users\TEJDEEP\Anaconda3.1\lib\site-packages\anaconda_navigator\exceptions.py", line 75, in exception_handler
    return_value = func(*args, **kwargs)
  File "C:\Users\TEJDEEP\Anaconda3.1\lib\site-packages\anaconda_navigator\app\start.py", line 151, in start_app
    window = run_app(splash)
  File "C:\Users\TEJDEEP\Anaconda3.1\lib\site-packages\anaconda_navigator\app\start.py", line 65, in run_app
    window = MainWindow(splash=splash, tab_project=False)
  File "C:\Users\TEJDEEP\Anaconda3.1\lib\site-packages\anaconda_navigator\widgets\main_window.py", line 168, in __init__
    self.api = AnacondaAPI()
  File "C:\Users\TEJDEEP\Anaconda3.1\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 2337, in AnacondaAPI
    ANACONDA_API = _AnacondaAPI()
  File "C:\Users\TEJDEEP\Anaconda3.1\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 89, in __init__
    self._conda_api = CondaAPI()
  File "C:\Users\TEJDEEP\Anaconda3.1\lib\site-packages\anaconda_navigator\api\conda_api.py", line 1773, in CondaAPI
    CONDA_API = _CondaAPI()
  File "C:\Users\TEJDEEP\Anaconda3.1\lib\site-packages\anaconda_navigator\api\conda_api.py", line 353, in __init__
    self.sys_rc_path = join(self.ROOT_PREFIX, '.condarc')
  File "C:\Users\TEJDEEP\Anaconda3.1\lib\ntpath.py", line 76, in join
    path = os.fspath(path)
TypeError: expected str, bytes or os.PathLike object, not NoneType
</pre></p>
      </div>
    </body>
    </html>
    
### Expected Behavior

it should launch Anaconda navigator

### Steps to Reproduce

1. Installed Anaconda navigator
2. tried launching Anaconda navigator from the window.

    <html>
    <head>
      <title>Navigator Error</title>
    </head>
    <body>
      <div>
        <h1>Navigator Error</h1>
        <p>An unexpected error occurred on Navigator start-up</p>
        <h2>Report</h2>
        <p>Please report this issue in the anaconda
          <a href="https://github.com/continuumio/anaconda-issues">
            issue tracker
          </a>
        </p>
      </div>
      <div>
        <h2>Main Error</h2>
        <p><pre>expected str, bytes or os.PathLike object, not NoneType</pre></p>
        <h2>Traceback</h2>
        <p><pre>Traceback (most recent call last):
  File "C:\Users\TEJDEEP\Anaconda3.1\lib\site-packages\anaconda_navigator\exceptions.py", line 75, in exception_handler
    return_value = func(*args, **kwargs)
  File "C:\Users\TEJDEEP\Anaconda3.1\lib\site-packages\anaconda_navigator\app\start.py", line 151, in start_app
    window = run_app(splash)
  File "C:\Users\TEJDEEP\Anaconda3.1\lib\site-packages\anaconda_navigator\app\start.py", line 65, in run_app
    window = MainWindow(splash=splash, tab_project=False)
  File "C:\Users\TEJDEEP\Anaconda3.1\lib\site-packages\anaconda_navigator\widgets\main_window.py", line 168, in __init__
    self.api = AnacondaAPI()
  File "C:\Users\TEJDEEP\Anaconda3.1\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 2337, in AnacondaAPI
    ANACONDA_API = _AnacondaAPI()
  File "C:\Users\TEJDEEP\Anaconda3.1\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 89, in __init__
    self._conda_api = CondaAPI()
  File "C:\Users\TEJDEEP\Anaconda3.1\lib\site-packages\anaconda_navigator\api\conda_api.py", line 1773, in CondaAPI
    CONDA_API = _CondaAPI()
  File "C:\Users\TEJDEEP\Anaconda3.1\lib\site-packages\anaconda_navigator\api\conda_api.py", line 353, in __init__
    self.sys_rc_path = join(self.ROOT_PREFIX, '.condarc')
  File "C:\Users\TEJDEEP\Anaconda3.1\lib\ntpath.py", line 76, in join
    path = os.fspath(path)
TypeError: expected str, bytes or os.PathLike object, not NoneType
</pre></p>
      </div>
    </body>
    </html>
    
##### `conda info`

<details>

```
PASTE OUTPUT HERE:

```

</details>

##### `conda list --show-channel-urls`

<details>

```
PASTE OUTPUT HERE:

```

</details>

**Comment by Ankit-Patil-Simply** [comment]
What should i do to overcome this error?

**Comment by csoja** [comment]
Please see https://docs.anaconda.com/anaconda/navigator/troubleshooting/#navigator-error-on-start-up
