### ISSUE TITLE
ImportError: DLL load failed: A dynamic link library (DLL) initialization routine failed.

### ISSUE THREAD

**Issue by sujithgunturu** [ContinuumIO/anaconda-issues#11655]
`from alinea.adel.astk_interface import AdelWheat
`

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Personal\Desktop\OpenAlea research\adel\src\alinea\adel\astk_interface.py", line 6, in <module>
    from alinea.adel.AdelR import setAdel, RunAdel, genGeoAxe, checkAxeDyn, getAxeT, \
  File "C:\Users\Personal\Desktop\OpenAlea research\adel\src\alinea\adel\AdelR.py", line 23, in <module>
    import rpy2.robjects as robj
  File "C:\Users\Personal\.conda\envs\openaleatotestadel\lib\site-packages\rpy2\robjects\__init__.py", line 16, in <module>
    import rpy2.rinterface as rinterface
  File "C:\Users\Personal\.conda\envs\openaleatotestadel\lib\site-packages\rpy2\rinterface\__init__.py", line 92, in <module>
    from rpy2.rinterface._rinterface import (baseenv,
ImportError: DLL load failed: A dynamic link library (DLL) initialization routine failed.

`(openaleatotestadel) C:\Users\Personal>conda info`

     active environment : openaleatotestadel
    active env location : C:\Users\Personal\.conda\envs\openaleatotestadel
            shell level : 1
       user config file : C:\Users\Personal\.condarc
 populated config files : C:\Users\Personal\.condarc
          conda version : 4.7.12
    conda-build version : 3.18.9
         python version : 3.7.4.final.0
       virtual packages :
       base environment : C:\ProgramData\Anaconda3  (read only)
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\ProgramData\Anaconda3\pkgs
                          C:\Users\Personal\.conda\pkgs
                          C:\Users\Personal\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\Personal\.conda\envs
                          C:\ProgramData\Anaconda3\envs
                          C:\Users\Personal\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.7.12 requests/2.22.0 CPython/3.7.4 Windows/10 Windows/10.0.18362
          administrator : False
             netrc file : None
           offline mode : False

`(openaleatotestadel) C:\Users\Personal>python --version`
Python 2.7.17

My python version in conda info and python --version is different. Is this the reason causing this issue.

**Comment by sujithgunturu** [comment]
solved
