### ISSUE TITLE
Updating Anaconda with Navigator removes Windows Start Menu shortcuts

### ISSUE THREAD

**Issue by patricktokeeffe** [ContinuumIO/anaconda-issues#1168]
With a fresh installation of Anaconda2-4.1.1 (x64) on Win7 x64, I observed kernels started by Spyder would immediately die. I decided to update everything before investigating by launching Anaconda Navigator and upgrading the metapackage `anaconda` from 4.1.1 -> 4.2.0. 

Now my start menu only contains a shortcut to <kbd>Anaconda Prompt</kbd>. (Disappearing shortcuts were mentioned in #1116 but I didn't find an open issue; closest is probably #1100)

![missing_shortcuts](https://cloud.githubusercontent.com/assets/1348834/19493496/59212c8c-9527-11e6-98e8-62f0cde6a416.png)

I tried using the suggestion in [this comment](https://github.com/ContinuumIO/anaconda-issues/issues/614#issuecomment-170950335) of #614 within in Anaconda Prompt but it resulted in an exception:

```
(C:\Anaconda2) C:\Users\LAR>conda update menuinst
Fetching package metadata .........
Solving package specifications: ..........

Package plan for installation in environment C:\Anaconda2:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    menuinst-1.4.2             |           py27_0         104 KB

The following packages will be UPDATED:

    menuinst: 1.4.1-py27_0 --> 1.4.2-py27_0

Proceed ([y]/n)? y

menuinst-1.4.2 100% |###############################| Time: 0:00:00 347.47 kB/s

(C:\Anaconda2) C:\Users\LAR>conda install -f console_shortcut ipython ipython-notebook ipython-qtconsole launcher spyder
Fetching package metadata .........
Solving package specifications: ..........

Package plan for installation in environment C:\Anaconda2:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    ipython-notebook-4.0.4     |           py27_3          12 KB
    ipython-qtconsole-4.0.1    |           py27_4          19 KB
    launcher-1.0.0             |                4         1.6 MB
    ------------------------------------------------------------
                                           Total:         1.6 MB

The following NEW packages will be INSTALLED:

    console_shortcut:  0.1.1-py27_1
    ipython:           5.1.0-py27_0
    ipython-notebook:  4.0.4-py27_3
    ipython-qtconsole: 4.0.1-py27_4
    launcher:          1.0.0-4
    spyder:            3.0.0-py27_0 (copy)

Proceed ([y]/n)? y

Fetching packages ...
ipython-notebo 100% |###############################| Time: 0:00:00 832.74 kB/s
ipython-qtcons 100% |###############################| Time: 0:00:00 245.50 kB/s
launcher-1.0.0 100% |###############################| Time: 0:00:01   1.66 MB/s
Pruning extracted packages from the cache ...
WARNING conda.install:rm_extracted(779): Directory not removed during RM_EXTRACTED instruction: C:\Anaconda2\pkgs\spyder-3.0.0-py27_0
[      COMPLETE      ]|##################################################| 100%
Extracting packages ...
WARNING conda.common.disk:exp_backoff_fn(169): Uncaught backoff with errno 173%
An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues



Current conda install:

               platform : win-64
          conda version : 4.2.9
       conda is private : False
      conda-env version : 4.2.9
    conda-build version : 1.21.3
         python version : 2.7.12.final.0
       requests version : 2.11.1
       root environment : C:\Anaconda2  (writable)
    default environment : C:\Anaconda2
       envs directories : C:\Anaconda2\envs
          package cache : C:\Anaconda2\pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/win-64/
                          https://repo.continuum.io/pkgs/free/noarch/
                          https://repo.continuum.io/pkgs/pro/win-64/
                          https://repo.continuum.io/pkgs/pro/noarch/
                          https://repo.continuum.io/pkgs/msys2/win-64/
                          https://repo.continuum.io/pkgs/msys2/noarch/
            config file : None
           offline mode : False



`$ C:\Anaconda2\Scripts\conda-script.py install -f console_shortcut ipython ipython-notebook ipython-qtconsole launcher spyder`




    Traceback (most recent call last):
      File "C:\Anaconda2\lib\site-packages\conda\exceptions.py", line 473, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "C:\Anaconda2\lib\site-packages\conda\cli\main.py", line 144, in _main
        exit_code = args.func(args, p)
      File "C:\Anaconda2\lib\site-packages\conda\cli\main_install.py", line 80, in execute
        install(args, parser, 'install')
      File "C:\Anaconda2\lib\site-packages\conda\cli\install.py", line 405, in install
        execute_actions(actions, index, verbose=not context.quiet)
      File "C:\Anaconda2\lib\site-packages\conda\plan.py", line 643, in execute_actions
        inst.execute_instructions(plan, index, verbose)
      File "C:\Anaconda2\lib\site-packages\conda\instructions.py", line 134, in execute_instructions
        cmd(state, arg)
      File "C:\Anaconda2\lib\site-packages\conda\instructions.py", line 58, in EXTRACT_CMD
        extract(arg)
      File "C:\Anaconda2\lib\site-packages\conda\install.py", line 803, in extract
        exp_backoff_fn(os.rename, temp_path, path)
      File "C:\Anaconda2\lib\site-packages\conda\common\disk.py", line 152, in exp_backoff_fn
        result = fn(*args, **kwargs)
    WindowsError: [Error 183] Cannot create a file when that file already exists
```

I'm going to attempt a full uninstall/reinstall next (time permitting). Suggestions welcome.

FWIW, Spyder is able to start kernels and appears to work correctly again after updating.

**Comment by goanpeca** [comment]
@ilanschnell, @ccordoba12 ?

**Comment by goanpeca** [comment]
Issue moved to [ContinuumIO/navigator #788](https://github.com/ContinuumIO/navigator/issues/788) via [**ZenHub**](https://www.zenhub.com/)
