### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by shahidsaifi92** [ContinuumIO/anaconda-issues#11687]
Navigator Error
An unexpected error occurred on Navigator start-up

Report
Please report this issue in the anaconda issue tracker

Main Error
'bytes' object has no attribute 'get'
Traceback
Traceback (most recent call last):
  File "C:\Users\Shahi\Anaconda3\lib\site-packages\anaconda_navigator\exceptions.py", line 75, in exception_handler
    return_value = func(*args, **kwargs)
  File "C:\Users\Shahi\Anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 151, in start_app
    window = run_app(splash)
  File "C:\Users\Shahi\Anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 65, in run_app
    window = MainWindow(splash=splash, tab_project=False)
  File "C:\Users\Shahi\Anaconda3\lib\site-packages\anaconda_navigator\widgets\main_window.py", line 170, in __init__
    self.api = AnacondaAPI()
  File "C:\Users\Shahi\Anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 1525, in AnacondaAPI
    ANACONDA_API = _AnacondaAPI()
  File "C:\Users\Shahi\Anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 77, in __init__
    self._conda_api = CondaAPI()
  File "C:\Users\Shahi\Anaconda3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 1804, in CondaAPI
    CONDA_API = _CondaAPI()
  File "C:\Users\Shahi\Anaconda3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 371, in __init__
    self.set_conda_prefix(info=get_conda_info())
  File "C:\Users\Shahi\Anaconda3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 533, in set_conda_prefix
    self.ROOT_PREFIX = info.get('root_prefix')
AttributeError: 'bytes' object has no attribute 'get'

**Comment by asenturk** [comment]
A have the same error:

Main Error
```
'bytes' object has no attribute 'get'
Traceback
Traceback (most recent call last):
  File "D:\Programlar\Anaconda3\lib\site-packages\anaconda_navigator\exceptions.py", line 75, in exception_handler
    return_value = func(*args, **kwargs)
  File "D:\Programlar\Anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 151, in start_app
    window = run_app(splash)
  File "D:\Programlar\Anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 65, in run_app
    window = MainWindow(splash=splash, tab_project=False)
  File "D:\Programlar\Anaconda3\lib\site-packages\anaconda_navigator\widgets\main_window.py", line 170, in __init__
    self.api = AnacondaAPI()
  File "D:\Programlar\Anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 1525, in AnacondaAPI
    ANACONDA_API = _AnacondaAPI()
  File "D:\Programlar\Anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 77, in __init__
    self._conda_api = CondaAPI()
  File "D:\Programlar\Anaconda3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 1804, in CondaAPI
    CONDA_API = _CondaAPI()
  File "D:\Programlar\Anaconda3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 371, in __init__
    self.set_conda_prefix(info=get_conda_info())
  File "D:\Programlar\Anaconda3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 533, in set_conda_prefix
    self.ROOT_PREFIX = info.get('root_prefix')
AttributeError: 'bytes' object has no attribute 'get'
```
