### ISSUE TITLE
Setting CONDA_DLL_SEARCH_MODIFICATION_ENABLE env variable breaks pip installation of  tensorflow-gpu

### ISSUE THREAD

**Issue by matthiasseibold** [ContinuumIO/anaconda-issues#11693]
### Actual Behavior

Python crashes when I try to import any library (numpy, matplotlib, etc..) and also whe i open spyder with the following error:
`Intel MKL FATAL ERROR: Cannot load mkl_intel_thread.dll.`

When applying the solution from this issue:
https://github.com/ContinuumIO/anaconda-issues/issues/10213 

and setting the env variable `CONDA_DLL_SEARCH_MODIFICATION_ENABLE ` I cannot run a conda environment with tensorflow-gpu support. It does not find the CUDA dll:
`ImportError: Could not find 'cudart64_101.dll'.`

What is really interesting is that setting this env variable also breaks my pip installation of tensorflow-gpu with the same error:
`ImportError: Could not find 'cudart64_101.dll'.`

Removing the env variable fixes the error and I can run the conda environment with a pip installation of tensorflow-gpu. However, the conda installation of tensorflow-gpu does not work in any case.

### Expected Behavior

tensorflow-gpu installation should work with the env variable `CONDA_DLL_SEARCH_MODIFICATION_ENABLE ` set.

### Steps to Reproduce

set the env variable `CONDA_DLL_SEARCH_MODIFICATION_ENABLE ` with Value "1"

Run in Anaconda:
conda create -n tf-gpu
conda activate tf-gpu
conda install python=3.7
pip install tensorflow
python
import tensorflow

##### Anaconda or Miniconda version:

Anaconda 4.8.3 

##### Operating System:

Windows 10

##### `conda info`

<details>

```
     active environment : tf-gpu
    active env location : C:\Users\matth\anaconda3\envs\tf-gpu
            shell level : 4
       user config file : C:\Users\matth\.condarc
 populated config files : C:\Users\matth\.condarc
          conda version : 4.8.1
    conda-build version : 3.18.11
         python version : 3.7.6.final.0
       virtual packages : __cuda=11.0
       base environment : C:\Users\matth\anaconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\Users\matth\anaconda3\pkgs
                          C:\Users\matth\.conda\pkgs
                          C:\Users\matth\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\matth\anaconda3\envs
                          C:\Users\matth\.conda\envs
                          C:\Users\matth\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.8.1 requests/2.22.0 CPython/3.7.6 Windows/10 Windows/10.0.18362
          administrator : False
             netrc file : None
           offline mode : False

```

</details>

##### `conda list --show-channel-urls`

<details>

```
PASTE OUTPUT HERE:

```

</details>

**Comment by tovaroe** [comment]
I'm having a very similar problem. Without setting CONDA_DLL_SEARCH_MODIFICATION_ENABLE I run into various dll-erros when importing numpy/scipy/sklearn or modules thereof (depending on which environment I'm in...). After setting CONDA_DLL_SEARCH_MODIFICATION_ENABLE, tf-gpu fails with "ImportError: Could not find 'cudart64_101.dll".
After deleting the CONDA_DLL_SEARCH_MODIFICATION_ENABLE environment variable, I can use tensorflow-gpu again (but various numpy/scipy/... modules stop working with dll-errors). 
I only used conda to install libaries and did not use pip. I tried using different environments for tf and numpy/scipy only to no effect.

And just to mention, I just started with a (relatively) clean installation of Windows 10 LTSC. I do not know what causes the "dll-hell", but it's probably one of the very few programs I installed when resetting my PC. Maybe I could try another clean Windows install and see what happens when I only install anaconda and no other program...

### Steps to Reproduce "ImportError: Could not find 'cudart64_101.dll'."

set the env variable CONDA_DLL_SEARCH_MODIFICATION_ENABLE with Value "1"

Run in Anaconda:
conda create -n tftest tensorflow-gpu
conda activate tftest
python
import tensorflow

### Steps to Reproduce scipy dll errors:

delete the env variable CONDA_DLL_SEARCH_MODIFICATION_ENABLE

Run in Anaconda:
conda activate tftest
python
import scipy.stats

(--> throws ImportError: DLL load failed:
<details>
```
>>> import scipy.stats
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Tom\anaconda3\envs\tftest\lib\site-packages\scipy\stats\__init__.py", line 384, in <module>
    from .stats import *
  File "C:\Users\Tom\anaconda3\envs\tftest\lib\site-packages\scipy\stats\stats.py", line 185, in <module>
    from . import distributions
  File "C:\Users\Tom\anaconda3\envs\tftest\lib\site-packages\scipy\stats\distributions.py", line 10, in <module>
    from ._distn_infrastructure import (entropy, rv_discrete, rv_continuous,
  File "C:\Users\Tom\anaconda3\envs\tftest\lib\site-packages\scipy\stats\_distn_infrastructure.py", line 25, in <module>
    from scipy import optimize
  File "C:\Users\Tom\anaconda3\envs\tftest\lib\site-packages\scipy\optimize\__init__.py", line 390, in <module>
    from ._minimize import *
  File "C:\Users\Tom\anaconda3\envs\tftest\lib\site-packages\scipy\optimize\_minimize.py", line 30, in <module>
    from ._trustregion_constr import _minimize_trustregion_constr
  File "C:\Users\Tom\anaconda3\envs\tftest\lib\site-packages\scipy\optimize\_trustregion_constr\__init__.py", line 4, in <module>
    from .minimize_trustregion_constr import _minimize_trustregion_constr
  File "C:\Users\Tom\anaconda3\envs\tftest\lib\site-packages\scipy\optimize\_trustregion_constr\minimize_trustregion_constr.py", line 4, in <module>
    from scipy.sparse.linalg import LinearOperator
  File "C:\Users\Tom\anaconda3\envs\tftest\lib\site-packages\scipy\sparse\linalg\__init__.py", line 116, in <module>
    from .eigen import *
  File "C:\Users\Tom\anaconda3\envs\tftest\lib\site-packages\scipy\sparse\linalg\eigen\__init__.py", line 11, in <module>
    from .arpack import *
  File "C:\Users\Tom\anaconda3\envs\tftest\lib\site-packages\scipy\sparse\linalg\eigen\arpack\__init__.py", line 22, in <module>
    from .arpack import *
  File "C:\Users\Tom\anaconda3\envs\tftest\lib\site-packages\scipy\sparse\linalg\eigen\arpack\arpack.py", line 45, in <module>
    from . import _arpack
ImportError: DLL load failed: Die angegebene Prozedur wurde nicht gefunden.
```
</details>
and this is just one of various errors I encounter when the CONDA_DLL_SEARCH_MODIFICATION_ENABLE env variable is not set...)

##### Anaconda or Miniconda version:
anaconda 2020.02, conda 4.8.3

##### Operating System:
Windows 10 Enterprise LTSC

##### `conda info`

<details>

```
  
     active environment : tftest
    active env location : C:\Users\Tom\anaconda3\envs\tftest
            shell level : 2
       user config file : C:\Users\Tom\.condarc
 populated config files :
          conda version : 4.8.3
    conda-build version : 3.18.11
         python version : 3.7.6.final.0
       virtual packages : __cuda=11.0
       base environment : C:\Users\Tom\anaconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\Users\Tom\anaconda3\pkgs
                          C:\Users\Tom\.conda\pkgs
                          C:\Users\Tom\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\Tom\anaconda3\envs
                          C:\Users\Tom\.conda\envs
                          C:\Users\Tom\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.8.3 requests/2.22.0 CPython/3.7.6 Windows/10 Windows/10.0.17763
          administrator : False
             netrc file : None
           offline mode : False

```

</details>



##### `conda list --show-channel-urls`


<details>

```
# Name                    Version                   Build  Channel
_tflow_select             2.1.0                       gpu    defaults
absl-py                   0.9.0                    py37_0    defaults
astor                     0.8.0                    py37_0    defaults
blas                      1.0                         mkl    defaults
blinker                   1.4                      py37_0    defaults
ca-certificates           2020.1.1                      0    defaults
cachetools                3.1.1                      py_0    defaults
certifi                   2020.4.5.1               py37_0    defaults
cffi                      1.14.0           py37h7a1dbc1_0    defaults
chardet                   3.0.4                 py37_1003    defaults
click                     7.1.2                      py_0    defaults
cryptography              2.9.2            py37h7a1dbc1_0    defaults
cudatoolkit               10.1.243             h74a9793_0    defaults
cudnn                     7.6.5                cuda10.1_0    defaults
gast                      0.2.2                    py37_0    defaults
google-auth               1.14.1                     py_0    defaults
google-auth-oauthlib      0.4.1                      py_2    defaults
google-pasta              0.2.0                      py_0    defaults
grpcio                    1.27.2           py37h351948d_0    defaults
h5py                      2.10.0           py37h5e291fa_0    defaults
hdf5                      1.10.4               h7ebc959_0    defaults
icc_rt                    2019.0.0             h0cc432a_1    defaults
idna                      2.9                        py_1    defaults
intel-openmp              2020.1                      216    defaults
keras-applications        1.0.8                      py_0    defaults
keras-preprocessing       1.1.0                      py_1    defaults
libprotobuf               3.11.4               h7bd577a_0    defaults
markdown                  3.1.1                    py37_0    defaults
mkl                       2020.1                      216    defaults
mkl-service               2.3.0            py37hb782905_0    defaults
mkl_fft                   1.0.15           py37h14836fe_0    defaults
mkl_random                1.1.1            py37h47e9c7a_0    defaults
numpy                     1.18.1           py37h93ca92e_0    defaults
numpy-base                1.18.1           py37hc3f5095_1    defaults
oauthlib                  3.1.0                      py_0    defaults
openssl                   1.1.1g               he774522_0    defaults
opt_einsum                3.1.0                      py_0    defaults
pip                       20.0.2                   py37_3    defaults
protobuf                  3.11.4           py37h33f27b4_0    defaults
pyasn1                    0.4.8                      py_0    defaults
pyasn1-modules            0.2.7                      py_0    defaults
pycparser                 2.20                       py_0    defaults
pyjwt                     1.7.1                    py37_0    defaults
pyopenssl                 19.1.0                   py37_0    defaults
pyreadline                2.1                      py37_1    defaults
pysocks                   1.7.1                    py37_0    defaults
python                    3.7.7                h81c818b_4    defaults
requests                  2.23.0                   py37_0    defaults
requests-oauthlib         1.3.0                      py_0    defaults
rsa                       4.0                        py_0    defaults
scipy                     1.4.1            py37h9439919_0    defaults
setuptools                46.4.0                   py37_0    defaults
six                       1.14.0                   py37_0    defaults
sqlite                    3.31.1               h2a8f88b_1    defaults
tensorboard               2.2.1              pyh532a8cf_0    defaults
tensorboard-plugin-wit    1.6.0                      py_0    defaults
tensorflow                2.1.0           gpu_py37h7db9008_0    defaults
tensorflow-base           2.1.0           gpu_py37h55f5790_0    defaults
tensorflow-estimator      2.1.0              pyhd54b08b_0    defaults
tensorflow-gpu            2.1.0                h0d30ee6_0    defaults
termcolor                 1.1.0                    py37_1    defaults
urllib3                   1.25.8                   py37_0    defaults
vc                        14.1                 h0510ff6_4    defaults
vs2015_runtime            14.16.27012          hf0eaf9b_2    defaults
werkzeug                  0.16.1                     py_0    defaults
wheel                     0.34.2                   py37_0    defaults
win_inet_pton             1.1.0                    py37_0    defaults
wincertstore              0.2                      py37_0    defaults
wrapt                     1.12.1           py37he774522_1    defaults
zlib                      1.2.11               h62dcd97_4    defaults
```

</details>

**Comment by tovaroe** [comment]
If anyone has a similar problem and wants to use tensorflow & numpy simultaneously, here's my current workaround:

Start without having CONDA_DLL_SEARCH_MODIFICATION_ENABLE set.
In python:

```
import tensorflow as tf
tf.config.list_physical_devices() #this seems to ensure that all necessary dlls that can otherwise not be found are loaded

import os
os.environ['CONDA_DLL_SEARCH_MODIFICATION_ENABLE'] = '1' #setting the env variable
import numpy as np # works fine
import scipy.stats # works fine
```

I haven't tested this thoroughly (just a simple CNN for MNIST classification), so no guarantees :)

And as a side note: Interestingly, if you set CONDA_DLL_SEARCH_MODIFICATION_ENABLE in Windows, then open python and delete the env variable with os.environ.pop('CONDA_DLL_SEARCH_MODIFICATION_ENABLE'), this does NOT work and I run into the same cudart64_101.dll error again.

**Comment by mingwandroid** [comment]
Thanks, I'll try to look into this.

**Comment by Meet1995** [comment]
Did you find any fix for the issue?

I have a similar issue where I am installing a kernel using ipykernel with CONDA_DLL_SEARCH_MODIFICATION_ENABLE env variable. When I conect to this kernel, importing numpy and scipy works for me but I am getting the same **Could not find cudart64_101.dll** error when I import tensorflow (version 2.3 installed from conda-forge). 

This is how my kernel.json looks:
![image](https://user-images.githubusercontent.com/41198480/105975145-a1364400-60b4-11eb-9c18-98a1132cf9c7.png)
