### ISSUE TITLE
install scikit-image

### ISSUE THREAD

**Issue by ltrojan** [ContinuumIO/anaconda-issues#1170]
`conda create scikit-image --name scratch`

`Linking packages ...
An unexpected error has occurred, please consider sending the#########################################################################################################                  |  89%
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.

Traceback (most recent call last): 
  File "/opt/miniconda2/bin/conda", line 5, in <module>
    sys.exit(main())
  File "/opt/miniconda2/lib/python2.7/site-packages/conda/cli/main.py", line 195, in main
    args_func(args, p)
  File "/opt/miniconda2/lib/python2.7/site-packages/conda/cli/main.py", line 202, in args_func
    args.func(args, p)
  File "/opt/miniconda2/lib/python2.7/site-packages/conda/cli/main_create.py", line 49, in execute
    install.install(args, parser, 'create')
  File "/opt/miniconda2/lib/python2.7/site-packages/conda/cli/install.py", line 423, in install
    plan.execute_actions(actions, index, verbose=not args.quiet)
  File "/opt/miniconda2/lib/python2.7/site-packages/conda/plan.py", line 537, in execute_actions
    inst.execute_instructions(plan, index, verbose)
  File "/opt/miniconda2/lib/python2.7/site-packages/conda/instructions.py", line 148, in execute_instructions
    cmd(state, arg)
  File "/opt/miniconda2/lib/python2.7/site-packages/conda/instructions.py", line 91, in LINK_CMD
    link(state['prefix'], arg, index=state['index'])
  File "/opt/miniconda2/lib/python2.7/site-packages/conda/instructions.py", line 87, in link
    install.link(pkgs_dir, prefix, dist, lt, index=index)
  File "/opt/miniconda2/lib/python2.7/site-packages/conda/install.py", line 634, in link
    _link(src, dst, lt)
  File "/opt/miniconda2/lib/python2.7/site-packages/conda/install.py", line 132, in _link
    shutil.copy2(src, dst)
  File "/opt/miniconda2/lib/python2.7/shutil.py", line 130, in copy2
    copyfile(src, dst)
  File "/opt/miniconda2/lib/python2.7/shutil.py", line 82, in copyfile
    with open(src, 'rb') as fsrc:  
IOError: [Errno 2] No such file or directory: u'/mnt/nfs/home/user/.conda/envs/.pkgs/qt-5.6.0-1/bin/qmake'`

**Comment by ltrojan** [comment]
```
The following NEW packages will be INSTALLED:

    cairo:            1.12.18-6
    cycler:           0.10.0-py27_0
    dbus:             1.10.10-0
    decorator:        4.0.10-py27_0
    expat:            2.1.0-0
    fontconfig:       2.11.1-6
    freetype:         2.5.5-1
    glib:             2.43.0-1
    gst-plugins-base: 1.8.0-0
    gstreamer:        1.8.0-0
    icu:              54.1-0
    jbig:             2.1-0
    jpeg:             8d-2
    libffi:           3.2.1-0
    libgcc:           5.2.0-0
    libgfortran:      3.0.0-1
    libpng:           1.6.22-0
    libtiff:          4.0.6-2
    libxcb:           1.12-1
    libxml2:          2.9.2-0
    matplotlib:       1.5.3-np111py27_0
    mkl:              11.3.3-0
    networkx:         1.11-py27_0  
    numpy:            1.11.2-py27_0
    openssl:          1.0.2j-0
    pillow:           3.4.1-py27_0 
    pip:              8.1.2-py27_0 
    pixman:           0.32.6-0
    pycairo:          1.10.0-py27_0
    pyparsing:        2.1.4-py27_0 
    pyqt:             5.6.0-py27_0 
    python:           2.7.12-1
    python-dateutil:  2.5.3-py27_0 
    pytz:             2016.7-py27_0
    qt:               5.6.0-1
    readline:         6.2-2              (soft-link)
    scikit-image:     0.12.3-np111py27_1
    scipy:            0.18.1-np111py27_0
    setuptools:       27.2.0-py27_0
    sip:              4.18-py27_0  
    six:              1.10.0-py27_0
    sqlite:           3.13.0-0
    tk:               8.5.18-0           (soft-link)
    wheel:            0.29.0-py27_0
    xz:               5.2.2-0
    zlib:             1.2.8-3

```

**Comment by ltrojan** [comment]
```
ltrojan@gpu02:~/repo/gin_pipeline$ conda -V
conda 3.19.0
```

Hope this is sufficient info...
