### ISSUE TITLE
Anaconda3 will not install on linux: 'Failed to execute script entry_point'

### ISSUE THREAD

**Issue by celorette** [ContinuumIO/anaconda-issues#11703]
I'm very new to anaconda and to using Linux, so forgive my ignorance on any points. I'm trying to install anaconda on a remote Linux server I'm using for work.

### Actual Behavior

After running bash Downloads/Anaconda3-2020.02-Linux-x86_64.sh, I get the license agreement, then after answering yes, an error occurs, as listed:

```
WARNING: md5sum mismatch of tar archive
expected: 826b70d8ad34b7d9230d4da350d1b598
     got: 2472505c465de6c6f14c391e4a1047f4  -
Unpacking payload ...
concurrent.futures.process._RemoteTraceback:
'''
Traceback (most recent call last):
  File "concurrent/futures/process.py", line 367, in _queue_management_worker
  File "multiprocessing/connection.py", line 251, in recv
TypeError: __init__() missing 1 required positional argument: 'msg'
'''

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "entry_point.py", line 69, in <module>
  File "concurrent/futures/process.py", line 483, in _chain_from_iterable_of_lists
  File "concurrent/futures/_base.py", line 598, in result_iterator
  File "concurrent/futures/_base.py", line 435, in result
  File "concurrent/futures/_base.py", line 384, in __get_result
concurrent.futures.process.BrokenProcessPool: A process in the process pool was terminated abruptly while the future was running or pending.
[13995] Failed to execute script entry_point
```

### Expected Behavior

The installation should proceed.

### Steps to Reproduce

I deleted the directory 'anaconda3' that was created by the first steps of the installer and the files within, and tried running the installer again. The same error occured. 

##### Anaconda or Miniconda version:

Anaconda 3.7 64-bit installer

##### Operating System:
Ubuntu 18.04.4 LTS (GNU/Linux 4.15.0-88-generic x86_64)

##### `conda info`

```
conda: command not found

```

##### `conda list --show-channel-urls`

```
conda: command not found

```

**Comment by r-azh** [comment]
I get the same error

**Comment by ronaldokun** [comment]
I have been having the exact same error for more than 2 months on Windows when running the installer and checking the log when nothing is installed.

**Comment by UlionTse** [comment]
So?

**Comment by marhil95** [comment]
I had the same problem until I found this [issue](https://github.com/conda/conda/issues/9125) and figured out that I was running out of disc space.

**Comment by zochzh** [comment]
I met the same problem, have you solved it?

**Comment by zochzh** [comment]
I encountered the same problem and found that it was caused by incomplete downloading.You could just redownload and install it.

**Comment by UlionTse** [comment]
@zochzh You are right.

**Comment by ftarlao** [comment]
In my case I got this error by not having enough memory (RAM) at disposal for the installation to complete for the Anaconda Power9 installer; in detail I executed the installation on a remote node (srun -i, with slurm scheduler, I have a multi-arch cluster) and it failed lot of times, the problem has been solved by raisin' the RAM memory for the task to 5GB, --mem=5G solved the issue.

**Comment by FadyMorris** [comment]
@ftarlao 
Same here. I have an Ubuntu 20 on my machine and my installation kept failing until I restarted my PC and logged in TTY session instead of graphical user interface to have the maximum memory available for the installer.

**Comment by somenewaccountthen** [comment]
So this is a 'could be anything realy' error if i get it right? very unusefull.

**Comment by cataratoru-fara-cap** [comment]
I too have an encrypted home folder, it's definetly my issue because root instalation works fine. But why shouldn't I install there? Would it by any case be possible to move the instalation from root to home?

**Comment by UlionTse** [comment]
Because the old Linux system comes with Python, and the Python version is lower, and it cannot be simply replaced, because parts of the system may depend on it. We should pay attention to avoiding confusion in the python environment of the work environment and the system python environment.

**Comment by ElHouas** [comment]
@somenewaccountthen Thanks for your respinde, I face the same problem you had with the installation. How did you solve the installation step? Did you decrypt and then encrypt again the /home folder?
Is there any other route to avoid decryption the /home folder?

Thanks!

**Comment by cataratoru-fara-cap** [comment]
My solution was to just decrypt the folder, yes. I found the root cause of the issue tho, there is a file somewhere in the installation, possibly more, that have a name length greater than the limit for encrypted drives. One of those was in the arrow pakage and had a name that was "placeholder_placeholder_placeholder_" and so on. I found this out by installing anaconda in root and then trying to move the instalation.

**Comment by johantenhouten** [comment]
I had the same problem on my laptop (Mint Linix)  

I think the problem is with  the encrypted home folder

The solution was to install anaconda to /opt/anaconda3
The after installation run conda init it will change the bashrc for you. Cant remember bout changing permissions on files in /opt..

Hope this helps
