### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by SunnieV** [ContinuumIO/anaconda-issues#11710]
## Main error
An unexpected error occurred on Navigator start-up<br>string indices must be integers, not str
## Traceback
```
Traceback (most recent call last):
  File "/Users/sunithavege/anaconda/lib/python2.7/site-packages/anaconda_navigator/exceptions.py", line 75, in exception_handler
    return_value = func(*args, **kwargs)
  File "/Users/sunithavege/anaconda/lib/python2.7/site-packages/anaconda_navigator/app/start.py", line 115, in start_app
    window = run_app(splash)
  File "/Users/sunithavege/anaconda/lib/python2.7/site-packages/anaconda_navigator/app/start.py", line 58, in run_app
    window = MainWindow(splash=splash)
  File "/Users/sunithavege/anaconda/lib/python2.7/site-packages/anaconda_navigator/widgets/main_window.py", line 160, in __init__
    self.api = AnacondaAPI()
  File "/Users/sunithavege/anaconda/lib/python2.7/site-packages/anaconda_navigator/api/anaconda_api.py", line 1205, in AnacondaAPI
    ANACONDA_API = _AnacondaAPI()
  File "/Users/sunithavege/anaconda/lib/python2.7/site-packages/anaconda_navigator/api/anaconda_api.py", line 65, in __init__
    self._conda_api = CondaAPI()
  File "/Users/sunithavege/anaconda/lib/python2.7/site-packages/anaconda_navigator/api/conda_api.py", line 1622, in CondaAPI
    CONDA_API = _CondaAPI()
  File "/Users/sunithavege/anaconda/lib/python2.7/site-packages/anaconda_navigator/api/conda_api.py", line 340, in __init__
    self.set_conda_prefix()
  File "/Users/sunithavege/anaconda/lib/python2.7/site-packages/anaconda_navigator/api/conda_api.py", line 489, in set_conda_prefix
    self.ROOT_PREFIX = info['root_prefix']
TypeError: string indices must be integers, not str

```
## System information
```
platform: osx-64
version: 1.6.2
conda: 4.3.21
qt: 5.6.2
language: en
python: 2.7.13
os: Darwin;19.3.0;Darwin Kernel Version 19.3.0: Thu Jan  9 20:58:23 PST 2020; root:xnu-6153.81.5~1/RELEASE_X86_64;x86_64;i386
pyqt: 5.6.0
```

**Comment by csoja** [comment]
You are using a very old version of conda and Anaconda Navigator.  We would recommend that you upgrade to the latest:
  
In Anaconda Prompt or a terminal, run:
_conda update conda
conda update anaconda-navigator
conda update navigator-updater_

If you are still encountering trouble after upgrading, please open a new issue.
