### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by ryu-Xu** [ContinuumIO/anaconda-issues#11711]
## Main error
An unexpected error occurred on Navigator start-up<br>psutil.AccessDenied (pid=2844)
## Traceback
```
Traceback (most recent call last):
  File "D:\Anaconda3\envs\tensorflow_gpu\lib\site-packages\psutil\_pswindows.py", line 780, in cmdline
    ret = cext.proc_cmdline(self.pid, use_peb=True)
PermissionError: [WinError 5] 拒绝访问。: '(originated from OpenProcess)'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Anaconda3\envs\tensorflow_gpu\lib\site-packages\psutil\_pswindows.py", line 679, in wrapper
    return fun(self, *args, **kwargs)
  File "D:\Anaconda3\envs\tensorflow_gpu\lib\site-packages\psutil\_pswindows.py", line 695, in wrapper
    return fun(self, *args, **kwargs)
  File "D:\Anaconda3\envs\tensorflow_gpu\lib\site-packages\psutil\_pswindows.py", line 783, in cmdline
    ret = cext.proc_cmdline(self.pid, use_peb=False)
PermissionError: [WinError 5] 拒绝访问。: '(originated from OpenProcess)'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Anaconda3\envs\tensorflow_gpu\lib\site-packages\anaconda_navigator\exceptions.py", line 75, in exception_handler
    return_value = func(*args, **kwargs)
  File "D:\Anaconda3\envs\tensorflow_gpu\lib\site-packages\anaconda_navigator\app\start.py", line 108, in start_app
    if misc.load_pid() is None:  # A stale lock might be around
  File "D:\Anaconda3\envs\tensorflow_gpu\lib\site-packages\anaconda_navigator\utils\misc.py", line 384, in load_pid
    cmds = process.cmdline()
  File "D:\Anaconda3\envs\tensorflow_gpu\lib\site-packages\psutil\__init__.py", line 690, in cmdline
    return self._proc.cmdline()
  File "D:\Anaconda3\envs\tensorflow_gpu\lib\site-packages\psutil\_pswindows.py", line 681, in wrapper
    raise convert_oserror(err, pid=self.pid, name=self._name)
psutil.AccessDenied: psutil.AccessDenied (pid=2844)

```
## System information
```
python: 3.6.10
language: zh_CN
os: Windows;10;10.0.17763;AMD64;Intel64 Family 6 Model 69 Stepping 1, GenuineIntel
version: 1.6.2
platform: win-64
qt: 5.6.2
pyqt: 5.6.0
conda: 4.3.30
```

**Comment by csoja** [comment]
https://docs.anaconda.com/anaconda/navigator/troubleshooting/#access-denied-error
