### ISSUE TITLE
Spyder not starting in a newly created environment

### ISSUE THREAD

**Issue by RobKwiatkowski** [ContinuumIO/anaconda-issues#11720]
### Actual Behavior

I've installed the newest version of Anaconda and created a clean environment with Python 3.8 (name "test"). After installing Spyder in a new environment and launching, it appears for a few seconds and then closes. The next time the following error appears in Anaconda Prompt:

`Unable to create process using 'C:\Users\User\anaconda3\envs\test\python.exe C:\Users\User\anaconda3\envs\test\Scripts\spyder-script.py `

However, running Spyder from a base environment works fine.

### Expected Behavior

After the creation of a new environment and installing Spyder it should run it seamlessly.

### Steps to Reproduce
1. Install a below-mentioned version of Anaconda.
2. Create a new environment: `conda create -n test`
3. Activate the new environment: `conda activate test`
4. Install Spyder: `conda install spyder`
5. Run Spyder: `spyder`
Now the loading banner should appear for a few second and the IDE does not start.
6. Repeat running spyder and you receive above-mentioned error.

##### Anaconda or Miniconda version:
Anaconda3-2020.02-Windows-x86_64.exe

##### Operating System:

Windows 10 x64

##### `conda info`
<details>

```
     active environment : test
    active env location : C:\Users\User\anaconda3\envs\test
            shell level : 2
       user config file : C:\Users\User\.condarc
 populated config files : C:\Users\User\.condarc
          conda version : 4.8.3
    conda-build version : 3.18.11
         python version : 3.7.6.final.0
       virtual packages : __cuda=11.0
       base environment : C:\Users\User\anaconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\Users\User\anaconda3\pkgs
                          C:\Users\User\.conda\pkgs
                          C:\Users\User\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\User\anaconda3\envs
                          C:\Users\User\.conda\envs
                          C:\Users\User\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.8.3 requests/2.22.0 CPython/3.7.6 Windows/10 Windows/10.0.18362
          administrator : False
             netrc file : None
           offline mode : False

```

</details>

##### `conda list --show-channel-urls`
<details>

```
# packages in environment at C:\Users\User\anaconda3\envs\test:
#
# Name                    Version                   Build  Channel
alabaster                 0.7.12                     py_0    defaults
argh                      0.26.2                   py38_0    defaults
asn1crypto                1.3.0                    py38_0    defaults
astroid                   2.3.3                    py38_0    defaults
atomicwrites              1.3.0                      py_0    defaults
attrs                     19.3.0                     py_0    defaults
autopep8                  1.4.4                      py_0    defaults
babel                     2.8.0                      py_0    defaults
backcall                  0.1.0                    py38_0    defaults
bcrypt                    3.1.7            py38he774522_0    defaults
bleach                    3.1.0                      py_0    defaults
ca-certificates           2020.1.1                      0    defaults
certifi                   2019.11.28               py38_1    defaults
cffi                      1.14.0           py38h7a1dbc1_0    defaults
chardet                   3.0.4                 py38_1003    defaults
cloudpickle               1.3.0                      py_0    defaults
colorama                  0.4.3                      py_0    defaults
cryptography              2.8              py38h7a1dbc1_0    defaults
decorator                 4.4.2                      py_0    defaults
defusedxml                0.6.0                      py_0    defaults
diff-match-patch          20181111                   py_0    defaults
docutils                  0.16                     py38_0    defaults
entrypoints               0.3                      py38_0    defaults
flake8                    3.7.9                    py38_0    defaults
future                    0.18.2                   py38_0    defaults
icu                       58.2                 ha66f8fd_1    defaults
idna                      2.9                        py_1    defaults
imagesize                 1.2.0                      py_0    defaults
importlib_metadata        1.5.0                    py38_0    defaults
intervaltree              3.0.2                      py_0    defaults
ipykernel                 5.1.4            py38h39e3cac_0    defaults
ipython                   7.13.0           py38h5ca1d4c_0    defaults
ipython_genutils          0.2.0                    py38_0    defaults
isort                     4.3.21                   py38_0    defaults
jedi                      0.15.2                   py38_0    defaults
jinja2                    2.11.1                     py_0    defaults
jpeg                      9b                   hb83a4c4_2    defaults
jsonschema                3.2.0                    py38_0    defaults
jupyter_client            6.1.2                      py_0    defaults
jupyter_core              4.6.3                    py38_0    defaults
keyring                   21.1.1                   py38_2    defaults
lazy-object-proxy         1.4.3            py38he774522_0    defaults
libpng                    1.6.37               h2a8f88b_0    defaults
libsodium                 1.0.16               h9d3ae62_0    defaults
libspatialindex           1.9.3                h33f27b4_0    defaults
markupsafe                1.1.1            py38he774522_0    defaults
mccabe                    0.6.1                    py38_1    defaults
mistune                   0.8.4           py38he774522_1000    defaults
nbconvert                 5.6.1                    py38_0    defaults
nbformat                  5.0.4                      py_0    defaults
numpydoc                  0.9.2                      py_0    defaults
openssl                   1.1.1f               he774522_0    defaults
packaging                 20.3                       py_0    defaults
pandoc                    2.2.3.2                       0    defaults
pandocfilters             1.4.2                    py38_1    defaults
paramiko                  2.7.1                      py_0    defaults
parso                     0.5.2                      py_0    defaults
pathtools                 0.1.2                      py_1    defaults
pexpect                   4.8.0                    py38_0    defaults
pickleshare               0.7.5                 py38_1000    defaults
pip                       20.0.2                   py38_1    defaults
pluggy                    0.13.1                   py38_0    defaults
prompt-toolkit            3.0.4                      py_0    defaults
prompt_toolkit            3.0.4                         0    defaults
psutil                    5.7.0            py38he774522_0    defaults
pycodestyle               2.5.0                    py38_0    defaults
pycparser                 2.20                       py_0    defaults
pydocstyle                4.0.1                      py_0    defaults
pyflakes                  2.1.1                    py38_0    defaults
pygments                  2.6.1                      py_0    defaults
pylint                    2.4.4                    py38_0    defaults
pynacl                    1.3.0            py38h62dcd97_0    defaults
pyopenssl                 19.1.0                   py38_0    defaults
pyparsing                 2.4.6                      py_0    defaults
pyqt                      5.9.2            py38ha925a31_4    defaults
pyrsistent                0.16.0           py38he774522_0    defaults
pysocks                   1.7.1                    py38_0    defaults
python                    3.8.2                h5fd99cc_0    defaults
python-dateutil           2.8.1                      py_0    defaults
python-jsonrpc-server     0.3.4                      py_0    defaults
python-language-server    0.31.9                   py38_0    defaults
pytz                      2019.3                     py_0    defaults
pywin32                   227              py38he774522_1    defaults
pywin32-ctypes            0.2.0                 py38_1000    defaults
pyyaml                    5.3.1            py38he774522_0    defaults
pyzmq                     18.1.1           py38ha925a31_0    defaults
qdarkstyle                2.8                        py_0    defaults
qt                        5.9.7            vc14h73c81de_0    defaults
qtawesome                 0.7.0                      py_0    defaults
qtconsole                 4.7.2                      py_0    defaults
qtpy                      1.9.0                      py_0    defaults
requests                  2.23.0                   py38_0    defaults
rope                      0.16.0                     py_0    defaults
rtree                     0.9.3            py38h21ff451_0    defaults
setuptools                46.1.3                   py38_0    defaults
sip                       4.19.13          py38ha925a31_0    defaults
six                       1.14.0                   py38_0    defaults
snowballstemmer           2.0.0                      py_0    defaults
sortedcontainers          2.1.0                    py38_0    defaults
sphinx                    2.4.4                      py_0    defaults
sphinxcontrib-applehelp   1.0.2                      py_0    defaults
sphinxcontrib-devhelp     1.0.2                      py_0    defaults
sphinxcontrib-htmlhelp    1.0.3                      py_0    defaults
sphinxcontrib-jsmath      1.0.1                      py_0    defaults
sphinxcontrib-qthelp      1.0.3                      py_0    defaults
sphinxcontrib-serializinghtml 1.1.4                      py_0    defaults
spyder                    4.1.1                    py38_1    defaults
spyder-kernels            1.9.0                    py38_0    defaults
sqlite                    3.31.1               he774522_0    defaults
testpath                  0.4.4                      py_0    defaults
tornado                   6.0.4            py38he774522_1    defaults
traitlets                 4.3.3                    py38_0    defaults
ujson                     1.35             py38he774522_0    defaults
urllib3                   1.25.8                   py38_0    defaults
vc                        14.1                 h0510ff6_4    defaults
vs2015_runtime            14.16.27012          hf0eaf9b_1    defaults
watchdog                  0.10.2                   py38_0    defaults
wcwidth                   0.1.9                      py_0    defaults
webencodings              0.5.1                    py38_1    defaults
wheel                     0.34.2                   py38_0    defaults
win_inet_pton             1.1.0                    py38_0    defaults
wincertstore              0.2                      py38_0    defaults
wrapt                     1.12.1           py38he774522_1    defaults
yaml                      0.1.7                hc54c509_2    defaults
yapf                      0.28.0                     py_0    defaults
zeromq                    4.3.1                h33f27b4_3    defaults
zipp                      2.2.0                      py_0    defaults
zlib                      1.2.11               h62dcd97_3    defaults
```

</details>

**Comment by VietEcon** [comment]
I also encountered a similar problem and would love to hear a solution as well.

**Comment by marles77** [comment]
Yeah, actually, none of the apps launches in an environment other than root after the update to 1.9.12. It's pretty annoying.

**Comment by saurabh87prabhu** [comment]
I have a similar looking situation where I can launch spyder from conda prompt if I run as administrator, not for current user. I had installed it using the "Just me" option for users.

**Comment by sreek011** [comment]
Can launch both spyder and navigator if launched as administrator in windows 10/ 64bit environment. Doesnt work in the user environment though the installation was done  for user.

**Comment by TereLoza** [comment]
I have a similar problem. I installed a new environment to run python 2.7. I enabled the environment and tried to run Spyder from Anaconda, Spyder opens but closes after a few seconds. I tried to do it from command line, and the same thing happens, but it doesn't mark any error.

**Comment by remkade** [comment]
Hi all, so sorry for the slow response. Is this fixed with newer versions of Spyder? It looks like we have 5.x versions on conda now.

**Comment by sagrotan17** [comment]
I have the same Problem on Windows 10 / 64-bit. After starting Anaconda-Navigator (2.1.0) in base (root) spyder starts properly - also after updateing spyder from version 4 to 5. In a new environment (dash) I have installed spyder. When I try to launch spyder a starting window ("spyder 5") appears and after a few seconds it disapear but spyder does not start. Tryed the install an older version of spyder in my environment (4 instead of 5.0.5), but it does not solve the problem. 
It also does not help to start Anaconda-Navigator with admin permissions...

I have checked as the user above in "base" and "dash" following and I am not sure if the entries are okay:  In "dash" environment I have installed spyder 5.0.5 and not 5.1.1?!:

(base) PS C:\Users\User> conda list --show-channel-urls
# packages in environment at C:\Users\User\anaconda3:
# Name                    Version                   Build  Channel
...
spyder                    5.0.5            py38haa95532_2    defaults
spyder-kernels            2.0.5            py38haa95532_0    defaults


(dash) PS C:\Users\User> conda list --show-channel-urls
# packages in environment at C:\Users\User\anaconda3\envs\dash:
# Name                    Version                   Build  Channel
...
spyder                    5.1.1                    pypi_0    pypi
spyder-kernels            2.1.2                    pypi_0    pypi


(dash) PS C:\Users\User> conda info
     active environment : dash
    active env location : C:\Users\User\anaconda3\envs\dash
            shell level : 2
       user config file : C:\Users\User\.condarc
 populated config files : C:\Users\User\.condarc
          conda version : 4.10.3
    conda-build version : 3.21.5
         python version : 3.8.11.final.0
       virtual packages : __cuda=10.1=0
                          __win=0=0
                          __archspec=1=x86_64
       base environment : C:\Users\User\anaconda3  (writable)
      conda av data dir : C:\Users\User\anaconda3\etc\conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\Users\User\anaconda3\pkgs
                          C:\Users\User\.conda\pkgs
                          C:\Users\User\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\User\anaconda3\envs
                          C:\Users\User\.conda\envs
                          C:\Users\User\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.10.3 requests/2.26.0 CPython/3.8.11 Windows/10 Windows/10.0.19042
          administrator : False
             netrc file : None
           offline mode : False

And here the output in  base:
(base) PS C:\Users\User> conda info

     active environment : base
    active env location : C:\Users\User\anaconda3
            shell level : 1
       user config file : C:\Users\User\.condarc
 populated config files : C:\Users\User\.condarc
          conda version : 4.10.3
    conda-build version : 3.21.5
         python version : 3.8.11.final.0
       virtual packages : __cuda=10.1=0
                          __win=0=0
                          __archspec=1=x86_64
       base environment : C:\Users\User\anaconda3  (writable)
      conda av data dir : C:\Users\User\anaconda3\etc\conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\Users\User\anaconda3\pkgs
                          C:\Users\User\.conda\pkgs
                          C:\Users\User\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\User\anaconda3\envs
                          C:\Users\User\.conda\envs
                          C:\Users\User\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.10.3 requests/2.26.0 CPython/3.8.11 Windows/10 Windows/10.0.19042
          administrator : False
             netrc file : None
           offline mode : False


When I try starting spyder in a terminal I get following error message:

(dash) PS C:\Users\User> spyder
Traceback (most recent call last):
  File "C:\Users\User\anaconda3\envs\dash\lib\site-packages\spyder\app\mainwindow.py", line 2132, in create_window
    main.setup()
  File "C:\Users\User\anaconda3\envs\dash\lib\site-packages\spyder\app\mainwindow.py", line 835, in setup
    external_plugins = find_external_plugins()
  File "C:\Users\User\anaconda3\envs\dash\lib\site-packages\spyder\app\solver.py", line 105, in find_external_plugins
    internal_plugins = find_internal_plugins()
  File "C:\Users\User\anaconda3\envs\dash\lib\site-packages\spyder\app\solver.py", line 94, in find_internal_plugins
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\User\anaconda3\envs\dash\lib\site-packages\spyder\plugins\pylint\__init__.py", line 14, in <module>
    from spyder.plugins.pylint.plugin import Pylint
  File "C:\Users\User\anaconda3\envs\dash\lib\site-packages\spyder\plugins\pylint\__init__.py", line 14, in <module>
    from spyder.plugins.pylint.plugin import Pylint
  File "C:\Users\User\anaconda3\envs\dash\lib\site-packages\spyder\plugins\pylint\plugin.py", line 22, in <module>
    from spyder.plugins.pylint.confpage import PylintConfigPage
  File "C:\Users\User\anaconda3\envs\dash\lib\site-packages\spyder\plugins\pylint\confpage.py", line 16, in <module>
    from spyder.plugins.pylint.main_widget import (MAX_HISTORY_ENTRIES,
  File "C:\Users\User\anaconda3\envs\dash\lib\site-packages\spyder\plugins\pylint\main_widget.py", line 35, in <module>
    from spyder.plugins.pylint.utils import get_pylintrc_path
  File "C:\Users\User\anaconda3\envs\dash\lib\site-packages\spyder\plugins\pylint\utils.py", line 16, in <module>
    import pylint.config
  File "C:\Users\User\anaconda3\envs\dash\lib\site-packages\pylint\config\__init__.py", line 39, in <module>
    from pylint.config.configuration_mixin import ConfigurationMixIn
  File "C:\Users\User\anaconda3\envs\dash\lib\site-packages\pylint\config\configuration_mixin.py", line 4, in <module>
    from pylint.config.option_manager_mixin import OptionsManagerMixIn
  File "C:\Users\User\anaconda3\envs\dash\lib\site-packages\pylint\config\option_manager_mixin.py", line 16, in <module>
    from pylint import utils
  File "C:\Users\User\anaconda3\envs\dash\lib\site-packages\pylint\utils\__init__.py", line 46, in <module>
    from pylint.utils.ast_walker import ASTWalker
  File "C:\Users\User\anaconda3\envs\dash\lib\site-packages\pylint\utils\ast_walker.py", line 6, in <module>
    from astroid import nodes
  File "C:\Users\User\anaconda3\envs\dash\lib\site-packages\astroid\__init__.py", line 53, in <module>
    from astroid import inference, raw_building
  File "C:\Users\User\anaconda3\envs\dash\lib\site-packages\astroid\inference.py", line 37, in <module>
    from astroid import decorators, helpers, nodes, protocols, util
  File "C:\Users\User\anaconda3\envs\dash\lib\site-packages\astroid\helpers.py", line 23, in <module>
    from astroid import manager, nodes, raw_building, scoped_nodes, util
  File "C:\Users\User\anaconda3\envs\dash\lib\site-packages\astroid\nodes\__init__.py", line 26, in <module>
    from astroid.nodes.node_classes import (  # pylint: disable=redefined-builtin (Ellipsis)
  File "C:\Users\User\anaconda3\envs\dash\lib\site-packages\astroid\nodes\node_classes.py", line 569, in <module>
    class AssignName(
  File "C:\Users\User\anaconda3\envs\dash\lib\site-packages\astroid\nodes\node_classes.py", line 589, in AssignName
    @decorators.deprecate_default_argument_values(name="str")
AttributeError: module 'astroid.decorators' has no attribute 'deprecate_default_argument_values'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\User\anaconda3\envs\dash\Scripts\spyder-script.py", line 10, in <module>
    sys.exit(main())
  File "C:\Users\User\anaconda3\envs\dash\lib\site-packages\spyder\app\start.py", line 227, in main
    mainwindow.main(options, args)
  File "C:\Users\User\anaconda3\envs\dash\lib\site-packages\spyder\app\mainwindow.py", line 2282, in main
    mainwindow = create_window(app, splash, options, args)
  File "C:\Users\User\anaconda3\envs\dash\lib\site-packages\spyder\app\mainwindow.py", line 2134, in create_window
    if main.console is not None:
  File "C:\Users\User\anaconda3\envs\dash\lib\site-packages\spyder\app\mainwindow.py", line 1156, in __getattr__
    return self.get_plugin(self._INTERNAL_PLUGINS_MAPPING[attr])
  File "C:\Users\User\anaconda3\envs\dash\lib\site-packages\spyder\app\mainwindow.py", line 169, in get_plugin
    raise SpyderAPIError(
spyder.api.exceptions.SpyderAPIError: Plugin "internal_console" not found!
(dash) PS C:\Users\User>

I have searched for a solution in the web, but nothing found ;O)
Hope someone has a tipp for me.
As additional information: Starting PyCharm Communicty from Anaconda Navigator in my "dash" environment works without a problems ;O)

Best regards
