### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by ayidhalqahtani** [ContinuumIO/anaconda-issues#11749]
## Main error
An unexpected error occurred on Navigator start-up<br>psutil.AccessDenied (pid=606)
## Traceback
```
Traceback (most recent call last):
  File "/Users/Tiger/anaconda/lib/python2.7/site-packages/anaconda_navigator/exceptions.py", line 75, in exception_handler
    return_value = func(*args, **kwargs)
  File "/Users/Tiger/anaconda/lib/python2.7/site-packages/anaconda_navigator/app/start.py", line 108, in start_app
    if misc.load_pid() is None:  # A stale lock might be around
  File "/Users/Tiger/anaconda/lib/python2.7/site-packages/anaconda_navigator/utils/misc.py", line 384, in load_pid
    cmds = process.cmdline()
  File "/Users/Tiger/anaconda/lib/python2.7/site-packages/psutil/__init__.py", line 666, in cmdline
    return self._proc.cmdline()
  File "/Users/Tiger/anaconda/lib/python2.7/site-packages/psutil/_psosx.py", line 330, in wrapper
    return fun(self, *args, **kwargs)
  File "/Users/Tiger/anaconda/lib/python2.7/site-packages/psutil/_psosx.py", line 412, in cmdline
    return cext.proc_cmdline(self.pid)
  File "/Users/Tiger/anaconda/lib/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "/Users/Tiger/anaconda/lib/python2.7/site-packages/psutil/_psosx.py", line 361, in catch_zombie
    raise AccessDenied(proc.pid, proc._name)
AccessDenied: psutil.AccessDenied (pid=606)

```
## System information
```
platform: osx-64
version: 1.6.2
conda: 4.7.9
qt: 5.6.2
language: en
python: 2.7.3
os: Darwin;18.7.0;Darwin Kernel Version 18.7.0: Tue Aug 20 16:57:14 PDT 2019; root:xnu-4903.271.2~2/RELEASE_X86_64;x86_64;i386
pyqt: 5.6.0
```

**Comment by csoja** [comment]
https://docs.anaconda.com/anaconda/navigator/troubleshooting/#access-denied-error
