### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by kkalpesh** [ContinuumIO/anaconda-issues#11759]
## Main error
Application <b>spyder</b> launch may have produced errors.
## Traceback
```
Traceback (most recent call last):
  File "/Users/kalpeshkhandhadia/anaconda/bin/spyder", line 11, in <module>
    sys.exit(main())
  File "/Users/kalpeshkhandhadia/anaconda/lib/python3.6/site-packages/spyder/app/start.py", line 205, in main
    mainwindow.main()
  File "/Users/kalpeshkhandhadia/anaconda/lib/python3.6/site-packages/spyder/app/mainwindow.py", line 3734, in main
    mainwindow = run_spyder(app, options, args)
  File "/Users/kalpeshkhandhadia/anaconda/lib/python3.6/site-packages/spyder/app/mainwindow.py", line 3590, in run_spyder
    main.setup()
  File "/Users/kalpeshkhandhadia/anaconda/lib/python3.6/site-packages/spyder/app/mainwindow.py", line 837, in setup
    from spyder.plugins.console.plugin import Console
  File "/Users/kalpeshkhandhadia/anaconda/lib/python3.6/site-packages/spyder/plugins/console/plugin.py", line 29, in <module>
    from spyder.utils.environ import EnvDialog
  File "/Users/kalpeshkhandhadia/anaconda/lib/python3.6/site-packages/spyder/utils/environ.py", line 19, in <module>
    from spyder.plugins.variableexplorer.widgets.collectionseditor import (
  File "/Users/kalpeshkhandhadia/anaconda/lib/python3.6/site-packages/spyder/plugins/variableexplorer/widgets/collectionseditor.py", line 57, in <module>
    from spyder.plugins.variableexplorer.widgets.collectionsdelegate import (
  File "/Users/kalpeshkhandhadia/anaconda/lib/python3.6/site-packages/spyder/plugins/variableexplorer/widgets/collectionsdelegate.py", line 39, in <module>
    from spyder.plugins.variableexplorer.widgets.dataframeeditor import (
  File "/Users/kalpeshkhandhadia/anaconda/lib/python3.6/site-packages/spyder/plugins/variableexplorer/widgets/dataframeeditor.py", line 47, in <module>
    from pandas import DataFrame, Index, Series, isna
ImportError: cannot import name 'isna'

```
## System information
```
python: 3.6.1
language: en
os: Darwin;18.7.0;Darwin Kernel Version 18.7.0: Mon Feb 10 21:08:45 PST 2020; root:xnu-4903.278.28~1/RELEASE_X86_64;x86_64;i386
version: 1.6.2
platform: osx-64
qt: 5.6.2
pyqt: 5.6.0
conda: 4.8.3
```

**Comment by PierreGrillet** [comment]
## Main Error
Spyder crash during launch

## Traceback
Getting the same traceback as @kkalpesh 

## System Information
python: 3.6.3
language : fr
os: Windows 7 Entreprise SP1
platform : win-64
PyQt5 = 5.15
conda 4.3.30
pip 20.1.1

**Comment by PierreGrillet** [comment]
Fixed by installing missing dependence 
```
pip install -U pandas_datareader
```
