### ISSUE TITLE
'bytes' object has no attribute 'get'

### ISSUE THREAD

**Issue by jiteshjhawar** [ContinuumIO/anaconda-issues#11754]
##### `conda info`

<details>

```
PASTE OUTPUT HERE:

```

</details>

##### `conda list --show-channel-urls`

<details>

```
PASTE OUTPUT HERE:

```
Traceback (most recent call last):
  File "/home/jitesh/anaconda3/lib/python3.7/site-packages/anaconda_navigator/exceptions.py", line 75, in exception_handler
    return_value = func(*args, **kwargs)
  File "/home/jitesh/anaconda3/lib/python3.7/site-packages/anaconda_navigator/app/start.py", line 151, in start_app
    window = run_app(splash)
  File "/home/jitesh/anaconda3/lib/python3.7/site-packages/anaconda_navigator/app/start.py", line 65, in run_app
    window = MainWindow(splash=splash, tab_project=False)
  File "/home/jitesh/anaconda3/lib/python3.7/site-packages/anaconda_navigator/widgets/main_window.py", line 170, in __init__
    self.api = AnacondaAPI()
  File "/home/jitesh/anaconda3/lib/python3.7/site-packages/anaconda_navigator/api/anaconda_api.py", line 1525, in AnacondaAPI
    ANACONDA_API = _AnacondaAPI()
  File "/home/jitesh/anaconda3/lib/python3.7/site-packages/anaconda_navigator/api/anaconda_api.py", line 77, in __init__
    self._conda_api = CondaAPI()
  File "/home/jitesh/anaconda3/lib/python3.7/site-packages/anaconda_navigator/api/conda_api.py", line 1804, in CondaAPI
    CONDA_API = _CondaAPI()
  File "/home/jitesh/anaconda3/lib/python3.7/site-packages/anaconda_navigator/api/conda_api.py", line 371, in __init__
    self.set_conda_prefix(info=get_conda_info())
  File "/home/jitesh/anaconda3/lib/python3.7/site-packages/anaconda_navigator/api/conda_api.py", line 533, in set_conda_prefix
    self.ROOT_PREFIX = info.get('root_prefix')
AttributeError: 'bytes' object has no attribute 'get'

</details>

**Comment by MSL-HEITA** [comment]
i had the same problem solved it by deleting the .condarc file it was corrupted 
when you restart anaconda it will recreate it again .
and try updating it with command prompt using command
>>>conda update conda
>>> conda anaconda-navigator updater
