### ISSUE TITLE
Spyder doesn't launch

### ISSUE THREAD

**Issue by SamueleBolotta** [ContinuumIO/anaconda-issues#11768]
I was working on a CSV file. All of a sudden Spyder stopped working and I cannot access it anymore. This is the issue I see when launching Spyder from the terminal:

Traceback (most recent call last):
  File "C:\Users\bolot\anaconda3\Scripts\spyder-script.py", line 10, in <module>
    sys.exit(main())
  File "C:\Users\bolot\anaconda3\lib\site-packages\spyder\app\start.py", line 201, in main
    from spyder.app import mainwindow
  File "C:\Users\bolot\anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 157, in <module>
    from spyder.plugins.help.utils.sphinxify import CSS_PATH, DARK_CSS_PATH
  File "C:\Users\bolot\anaconda3\lib\site-packages\spyder\plugins\help\utils\sphinxify.py", line 36, in <module>
    from sphinx.application import Sphinx
  File "C:\Users\bolot\anaconda3\lib\site-packages\sphinx\application.py", line 42, in <module>
    from sphinx.highlighting import lexer_classes, lexers
  File "C:\Users\bolot\anaconda3\lib\site-packages\sphinx\highlighting.py", line 30, in <module>
    from sphinx.ext import doctest
  File "C:\Users\bolot\anaconda3\lib\site-packages\sphinx\ext\doctest.py", line 28, in <module>
    from sphinx.builders import Builder
  File "C:\Users\bolot\anaconda3\lib\site-packages\sphinx\builders\__init__.py", line 24, in <module>
    from sphinx.io import read_doc
  File "C:\Users\bolot\anaconda3\lib\site-packages\sphinx\io.py", line 35, in <module>
    from sphinx.transforms.i18n import (
  File "C:\Users\bolot\anaconda3\lib\site-packages\sphinx\transforms\i18n.py", line 22, in <module>
    from sphinx.domains.std import make_glossary_term, split_term_classifiers
  File "C:\Users\bolot\anaconda3\lib\site-packages\sphinx\domains\std.py", line 26, in <module>
    from sphinx.directives import ObjectDescription
  File "C:\Users\bolot\anaconda3\lib\site-packages\sphinx\directives\__init__.py", line 261, in <module>
    from sphinx.directives.patches import (  # noqa
  File "C:\Users\bolot\anaconda3\lib\site-packages\sphinx\directives\patches.py", line 15, in <module>
    from docutils.parsers.rst.directives import images, html, tables
  File "C:\Users\bolot\anaconda3\lib\site-packages\docutils\parsers\rst\directives\tables.py", line 173, in <module>
    class CSVTable(Table):
  File "C:\Users\bolot\anaconda3\lib\site-packages\docutils\parsers\rst\directives\tables.py", line 196, in CSVTable
    class DocutilsDialect(csv.Dialect):
AttributeError: module 'csv' has no attribute 'Dialect'

Thanks!

**Comment by ccordoba12** [comment]
> AttributeError: module 'csv' has no attribute 'Dialect'

This usually means that you create a file called `csv.py` in your Users directory, which is interfering with Spyder. Please try to locate it and either remove it or at least rename it.
