### ISSUE TITLE
Anaconda Navigator won't open

### ISSUE THREAD

**Issue by jmwheels** [ContinuumIO/anaconda-issues#11767]
### Actual Behavior

I just installed Anaconda for the first time.  When I click on Anaconda Navigator from the start menu, nothing happens.  I tried uninstalling and reinstalling but nothing changes.  

I can open the anaconda prompt, and when I type anaconda-navigator I get this error message:

Traceback (most recent call last):
  File "C:\Users\jmwhe\anaconda3\lib\site-packages\qtpy\__init__.py", line 204, in <module>
    from PySide import __version__ as PYSIDE_VERSION  # analysis:ignore
ModuleNotFoundError: No module named 'PySide'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\jmwhe\anaconda3\Scripts\anaconda-navigator-script.py", line 6, in <module>
    from anaconda_navigator.app.main import main
  File "C:\Users\jmwhe\anaconda3\lib\site-packages\anaconda_navigator\app\main.py", line 22, in <module>
    from anaconda_navigator.utils.conda import is_conda_available
  File "C:\Users\jmwhe\anaconda3\lib\site-packages\anaconda_navigator\utils\__init__.py", line 15, in <module>
    from qtpy.QtGui import QIcon
  File "C:\Users\jmwhe\anaconda3\lib\site-packages\qtpy\__init__.py", line 210, in <module>
    raise PythonQtError('No Qt bindings could be found')
qtpy.PythonQtError: No Qt bindings could be found

### Expected Behavior

I expected Anaconda Navigator to open.

### Steps to Reproduce

start button, type anaconda prompt, open anaconda prompt and type "anaconda-navigator" to get the error message

##### Anaconda or Miniconda version:

Anaconda3-2020.02-Windows-x86_64

##### Operating System:

Windows

##### `conda info`

<details>

```
PASTE OUTPUT HERE:

```

</details>

##### `conda list --show-channel-urls`

<details>

```
PASTE OUTPUT HERE:

```

</details>

**Comment by luzhideng** [comment]
same issue here and don't know what to do. Tried everything I could. 
`conda update conda
conda update --all`

**Comment by sreek011** [comment]
I had this problem and it is resolved. I have the following to share. It may be useful:

A. Problem:
1. Anaconda-navigator  and Spyder (may be other apps also, I didn't try) stopped working (they used to work without any issue before). System - Windows 10 64bit (Anaconda 2019.10)

2. Error message for spyder:
(base) C:\Users\panicker>spyder

Traceback (most recent call last):
File "C:\Users\panicker\anaconda3\lib\site-packages\qtpy_init_.py", line 204, in
from PySide import version as PYSIDE_VERSION # analysis:ignore
ModuleNotFoundError: No module named 'PySide'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "C:\Users\panicker\anaconda3\Scripts\spyder-script.py", line 10, in
sys.exit(main())
File "C:\Users\panicker\anaconda3\lib\site-packages\spyder\app\start.py", line 201, in main
from spyder.app import mainwindow
File "C:\Users\panicker\anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 52, in
requirements.check_qt()
File "C:\Users\panicker\anaconda3\lib\site-packages\spyder\requirements.py", line 41, in check_qt
import qtpy
File "C:\Users\panicker\anaconda3\lib\site-packages\qtpy_init_.py", line 210, in
raise PythonQtError('No Qt bindings could be found')
qtpy.PythonQtError: No Qt bindings could be found



B. Probable reason for the problem:
Installed PyQt5 by...  pip install PyQt5


C. Attempts to fix the problem:
Approach 1. 
a. Uninstalled anaconda (2019.10). (windows control panel, add remove programs, uninstall)
b. Newer version, 2020.02 was available and hence downloaded the same and installed (installed with default/ recommended options)

z. Outcome  - problem persisted, but able to launch both Anaconda Navigator and spyder in the admin mode.

Approach 2. 

a. Uninstalled anaconda (2020.02) (windows control panel, add remove programs, uninstall)
b. Old package 2019.10 installed. (installed with default/ recommended options)
Outcome  - problem persisted, but able to launch both Anaconda Navigator and spyder in the admin mode.

Approach 3. Did the following for clean uninstall as given in the anaconda documentation:
a. > 'conda install anaconda-clean' (Anaconda prompt was working) 
b. > 'anaconda-clean --yes' 
c. Uninstall anaconda (windows control panel, add remove programs, uninstall)
d. Entries (anaconda, spyder, python etc...) in windows registry removed
e. Installed Newer version, 2020.02 (installed with default/ recommended options) 

z. Outcome  - problem persisted, but able to launch both Anaconda Navigator and spyder in the admin mode.


D. Approach 3 - Solution that worked:

a. > 'conda install anaconda-clean' (Anaconda prompt was working) 
b. > 'anaconda-clean --yes' 
c. Uninstalled anaconda (2020.02) (windows control panel, add remove programs, uninstall)
d. Entries (anaconda, spyder, python etc...) in windows registry removed

e. Deleted files and folders persisting after uninstall. - Launch windows file explorer, go to root directory under which anaconda was installed ), In my case C: (windows) drive. Search with key words anaconda, python, spyder etc. Folders and files persisting after anaconda installation were listed in the search results. Delete all persisting files and folders

f. Installed Newer version, 2020.02 (installed with default/ recommended options) 

z. Outcome  - problem resolved.
