### ISSUE TITLE
Getting error while launching Spyder in anaconda

### ISSUE THREAD

**Issue by raviwithfuture** [ContinuumIO/anaconda-issues#11775]
### Actual Behavior

I created by an environment called 'TensorFlow' to install Keras and tensor flow in my anaconda. I was able to run my environment successfully in Jupyter but when I am trying to launch Spyder in Anaconda then getting the following error 

Traceback (most recent call last):
File "D:\ProgramData\Anaconda3\envs\tensorflow\Scripts\spyder-script.py", line 10, in 
sys.exit(main())
File "D:\ProgramData\Anaconda3\envs\tensorflow\lib\site-packages\spyder\app\start.py", line 205, in main
mainwindow.main()
File "D:\ProgramData\Anaconda3\envs\tensorflow\lib\site-packages\spyder\app\mainwindow.py", line 3734, in main
mainwindow = run_spyder(app, options, args)
File "D:\ProgramData\Anaconda3\envs\tensorflow\lib\site-packages\spyder\app\mainwindow.py", line 3590, in run_spyder
main.setup()
File "D:\ProgramData\Anaconda3\envs\tensorflow\lib\site-packages\spyder\app\mainwindow.py", line 977, in setup
'spyder.plugins.{}'.format(plugin_name))
File "D:\ProgramData\Anaconda3\envs\tensorflow\lib\importlib\__init__.py", line 127, in import_module
return _bootstrap._gcd_import(name[level:], package, level)
File "", line 1006, in _gcd_import
File "", line 983, in _find_and_load
File "", line 967, in _find_and_load_unlocked
File "", line 677, in _load_unlocked
File "", line 728, in exec_module
File "", line 219, in _call_with_frames_removed
File "D:\ProgramData\Anaconda3\envs\tensorflow\lib\site-packages\spyder\plugins\pylint\__init__.py", line 14, in 
from .plugin import Pylint as PLUGIN_CLASS
File "D:\ProgramData\Anaconda3\envs\tensorflow\lib\site-packages\spyder\plugins\pylint\plugin.py", line 29, in 
from spyder.plugins.pylint.confpage import PylintConfigPage
File "D:\ProgramData\Anaconda3\envs\tensorflow\lib\site-packages\spyder\plugins\pylint\confpage.py", line 16, in 
from spyder.plugins.pylint.widgets.pylintgui import PylintWidget
File "D:\ProgramData\Anaconda3\envs\tensorflow\lib\site-packages\spyder\plugins\pylint\widgets\pylintgui.py", line 37, in 
from spyder.plugins.pylint.utils import get_pylintrc_path
File "D:\ProgramData\Anaconda3\envs\tensorflow\lib\site-packages\spyder\plugins\pylint\utils.py", line 16, in 
import pylint.config
File "D:\ProgramData\Anaconda3\envs\tensorflow\lib\site-packages\pylint\config.py", line 54, in 
import toml
ModuleNotFoundError: No module named 'toml'

### Expected Behavior

It should launch Spyder

### Steps to Reproduce

I tried to reset spyder but it did not work though I am able o launch Jupyter without any issue.

##### Anaconda or Miniconda version:

conda 4.8.2

##### Operating System:
Window 10
##### `conda info`

<details>

```
active environment : tensorflow
    active env location : D:\ProgramData\Anaconda3\envs\tensorflow
            shell level : 2
       user config file : C:\Users\Ravi Kumar Pandit\.condarc
 populated config files : C:\Users\Ravi Kumar Pandit\.condarc
          conda version : 4.8.2
    conda-build version : 3.18.11
         python version : 3.7.6.final.0
       virtual packages : __cuda=9.1
       base environment : D:\ProgramData\Anaconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
                          https://conda.anaconda.org/conda-forge/win-64
                          https://conda.anaconda.org/conda-forge/noarch
          package cache : D:\ProgramData\Anaconda3\pkgs
                          C:\Users\Ravi Kumar Pandit\.conda\pkgs
                          C:\Users\Ravi Kumar Pandit\AppData\Local\conda\conda\pkgs
       envs directories : D:\ProgramData\Anaconda3\envs
                          C:\Users\Ravi Kumar Pandit\.conda\envs
                          C:\Users\Ravi Kumar Pandit\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.8.2 requests/2.22.0 CPython/3.7.6 Windows/10 Windows/10.0.18362
          administrator : True
             netrc file : None
           offline mode : False

```

</details>

##### `conda list --show-channel-urls`

<details>

```
# Name                    Version                   Build  Channel
_tflow_select             2.2.0                     eigen    defaults
absl-py                   0.9.0                    py37_0    defaults
alabaster                 0.7.12                   py37_0    defaults
argh                      0.26.2                   py37_0    defaults
asn1crypto                1.3.0                    py37_0    defaults
astor                     0.8.0                    py37_0    defaults
astroid                   2.3.3                    py37_0    defaults
atomicwrites              1.3.0                    py37_1    defaults
attrs                     19.3.0                     py_0    defaults
autopep8                  1.4.4                      py_0    defaults
babel                     2.8.0                      py_0    defaults
backcall                  0.1.0                    py37_0    defaults
bcrypt                    3.1.7            py37he774522_0    defaults
blas                      1.0                         mkl    defaults
bleach                    3.1.4                      py_0    defaults
blinker                   1.4                      py37_0    defaults
ca-certificates           2020.1.1                      0    defaults
cachetools                3.1.1                      py_0    defaults
certifi                   2020.4.5.1               py37_0    defaults
cffi                      1.14.0           py37h7a1dbc1_0    defaults
chardet                   3.0.4                 py37_1003    defaults
click                     7.1.1                      py_0    defaults
cloudpickle               1.4.0                      py_0    defaults
colorama                  0.4.3                      py_0    defaults
cryptography              2.8              py37h7a1dbc1_0    defaults
decorator                 4.4.2                      py_0    defaults
defusedxml                0.6.0                      py_0    defaults
diff-match-patch          20181111                   py_0    defaults
docutils                  0.16                     py37_0    defaults
entrypoints               0.3                      py37_0    defaults
flake8                    3.7.9                    py37_0    defaults
future                    0.18.2                   py37_0    defaults
gast                      0.2.2                    py37_0    defaults
google-auth               1.13.1                     py_0    defaults
google-auth-oauthlib      0.4.1                      py_2    defaults
google-pasta              0.2.0                      py_0    defaults
grpcio                    1.27.2           py37h351948d_0    defaults
h5py                      2.10.0           py37h5e291fa_0    defaults
hdf5                      1.10.4               h7ebc959_0    defaults
icc_rt                    2019.0.0             h0cc432a_1    defaults
icu                       58.2                 ha925a31_3    defaults
idna                      2.9                        py_1    defaults
imagesize                 1.2.0                      py_0    defaults
importlib_metadata        1.5.0                    py37_0    defaults
intel-openmp              2020.0                      166    defaults
intervaltree              3.0.2                      py_0    defaults
ipykernel                 5.1.4            py37h39e3cac_0    defaults
ipython                   7.13.0           py37h5ca1d4c_0    defaults
ipython_genutils          0.2.0                    py37_0    defaults
isort                     4.3.21                   py37_0    defaults
jedi                      0.15.2                   py37_0    defaults
jinja2                    2.11.2                     py_0    defaults
jpeg                      9b                   hb83a4c4_2    defaults
jsonschema                3.2.0                    py37_0    defaults
jupyter_client            6.1.3                      py_0    defaults
jupyter_core              4.6.3                    py37_0    defaults
keras                     2.3.1                         0    defaults
keras-applications        1.0.8                      py_0    defaults
keras-base                2.3.1                    py37_0    defaults
keras-preprocessing       1.1.0                      py_1    defaults
keyring                   21.1.1                   py37_2    defaults
lazy-object-proxy         1.4.3            py37he774522_0    defaults
libpng                    1.6.37               h2a8f88b_0    defaults
libprotobuf               3.11.4               h7bd577a_0    defaults
libsodium                 1.0.16               h9d3ae62_0    defaults
libspatialindex           1.9.3                h33f27b4_0    defaults
m2w64-gcc-libgfortran     5.3.0                         6    defaults
m2w64-gcc-libs            5.3.0                         7    defaults
m2w64-gcc-libs-core       5.3.0                         7    defaults
m2w64-gmp                 6.1.0                         2    defaults
m2w64-libwinpthread-git   5.0.0.4634.697f757               2    defaults
markdown                  3.1.1                    py37_0    defaults
markupsafe                1.1.1            py37he774522_0    defaults
mccabe                    0.6.1                    py37_1    defaults
mistune                   0.8.4            py37he774522_0    defaults
mkl                       2020.0                      166    defaults
mkl-service               2.3.0            py37hb782905_0    defaults
mkl_fft                   1.0.15           py37h14836fe_0    defaults
mkl_random                1.1.0            py37h675688f_0    defaults
msys2-conda-epoch         20160418                      1    defaults
nbconvert                 5.6.1                    py37_0    defaults
nbformat                  5.0.4                      py_0    defaults
notebook                  6.0.3                    py37_0    defaults
numpy                     1.18.1           py37h93ca92e_0    defaults
numpy-base                1.18.1           py37hc3f5095_1    defaults
numpydoc                  0.9.2                      py_0    defaults
oauthlib                  3.1.0                      py_0    defaults
openssl                   1.1.1g               he774522_0    defaults
opt_einsum                3.1.0                      py_0    defaults
packaging                 20.3                       py_0    defaults
pandoc                    2.2.3.2                       0    defaults
pandocfilters             1.4.2                    py37_1    defaults
paramiko                  2.7.1                      py_0    defaults
parso                     0.5.2                      py_0    defaults
pathtools                 0.1.2                      py_1    defaults
pexpect                   4.8.0                    py37_0    defaults
pickleshare               0.7.5                    py37_0    defaults
pip                       20.0.2                   py37_1    defaults
pluggy                    0.13.1                   py37_0    defaults
prometheus_client         0.7.1                      py_0    defaults
prompt-toolkit            3.0.4                      py_0    defaults
prompt_toolkit            3.0.4                         0    defaults
protobuf                  3.11.4           py37h33f27b4_0    defaults
psutil                    5.7.0            py37he774522_0    defaults
pyasn1                    0.4.8                      py_0    defaults
pyasn1-modules            0.2.7                      py_0    defaults
pycodestyle               2.5.0                    py37_0    defaults
pycparser                 2.20                       py_0    defaults
pydocstyle                4.0.1                      py_0    defaults
pyflakes                  2.1.1                    py37_0    defaults
pygments                  2.6.1                      py_0    defaults
pyjwt                     1.7.1                    py37_0    defaults
pylint                    2.5.0                    py37_0    defaults
pynacl                    1.3.0            py37h62dcd97_0    defaults
pyopenssl                 19.1.0                   py37_0    defaults
pyparsing                 2.4.7                      py_0    defaults
pyqt                      5.9.2            py37h6538335_2    defaults
pyreadline                2.1                      py37_1    defaults
pyrsistent                0.16.0           py37he774522_0    defaults
pysocks                   1.7.1                    py37_0    defaults
python                    3.7.7                h60c2a47_2    defaults
python-dateutil           2.8.1                      py_0    defaults
python-jsonrpc-server     0.3.4                      py_0    defaults
python-language-server    0.31.10                  py37_0    defaults
pytz                      2019.3                     py_0    defaults
pywin32                   227              py37he774522_1    defaults
pywin32-ctypes            0.2.0                 py37_1000    defaults
pywinpty                  0.5.7                    py37_0    defaults
pyyaml                    5.3.1            py37he774522_0    defaults
pyzmq                     18.1.1           py37ha925a31_0    defaults
qdarkstyle                2.8.1                      py_0    defaults
qt                        5.9.7            vc14h73c81de_0    defaults
qtawesome                 0.7.0                      py_0    defaults
qtconsole                 4.7.3                      py_0    defaults
qtpy                      1.9.0                      py_0    defaults
requests                  2.23.0                   py37_0    defaults
requests-oauthlib         1.3.0                      py_0    defaults
rope                      0.16.0                     py_0    defaults
rsa                       4.0                        py_0    defaults
rtree                     0.9.3            py37h21ff451_0    defaults
scipy                     1.4.1            py37h9439919_0    defaults
send2trash                1.5.0                    py37_0    defaults
setuptools                46.1.3                   py37_0    defaults
sip                       4.19.8           py37h6538335_0    defaults
six                       1.14.0                   py37_0    defaults
snowballstemmer           2.0.0                      py_0    defaults
sortedcontainers          2.1.0                    py37_0    defaults
sphinx                    3.0.3                      py_0    defaults
sphinxcontrib-applehelp   1.0.2                      py_0    defaults
sphinxcontrib-devhelp     1.0.2                      py_0    defaults
sphinxcontrib-htmlhelp    1.0.3                      py_0    defaults
sphinxcontrib-jsmath      1.0.1                      py_0    defaults
sphinxcontrib-qthelp      1.0.3                      py_0    defaults
sphinxcontrib-serializinghtml 1.1.4                      py_0    defaults
spyder                    4.1.2                    py37_0    defaults
spyder-kernels            1.9.0                    py37_0    defaults
sqlite                    3.31.1               h2a8f88b_1    defaults
tensorboard               2.1.0                     py3_0    defaults
tensorflow                2.1.0           eigen_py37hd727fc0_0    defaults
tensorflow-base           2.1.0           eigen_py37h49b2757_0    defaults
tensorflow-estimator      2.1.0              pyhd54b08b_0    defaults
termcolor                 1.1.0                    py37_1    defaults
terminado                 0.8.3                    py37_0    defaults
testpath                  0.4.4                      py_0    defaults
tornado                   6.0.4            py37he774522_1    defaults
traitlets                 4.3.3                    py37_0    defaults
ujson                     1.35             py37hfa6e2cd_0    defaults
urllib3                   1.25.8                   py37_0    defaults
vc                        14.1                 h0510ff6_4    defaults
vs2015_runtime            14.16.27012          hf0eaf9b_1    defaults
watchdog                  0.10.2                   py37_0    defaults
wcwidth                   0.1.9                      py_0    defaults
webencodings              0.5.1                    py37_1    defaults
werkzeug                  0.14.1                   py37_0    defaults
wheel                     0.34.2                   py37_0    defaults
win_inet_pton             1.1.0                    py37_0    defaults
wincertstore              0.2                      py37_0    defaults
winpty                    0.4.3                         4    defaults
wrapt                     1.12.1           py37he774522_1    defaults
yaml                      0.1.7                hc54c509_2    defaults
yapf                      0.28.0                     py_0    defaults
zeromq                    4.3.1                h33f27b4_3    defaults
zipp                      3.1.0                      py_0    defaults
zlib                      1.2.11               h62dcd97_4    defaults

```

</details>

**Comment by croth1** [comment]
Also asked multiple times on stackoverflow (e.g. here): https://stackoverflow.com/questions/61529446/spyder-failed-to-launch-in-anaconda-after-update-4-1-2

It seems that the dependencies for 2.5.0 are missing toml. Quick workaround: `conda install "pylint<2.5"`
