### ISSUE TITLE
After boto3 installation Anaconda is completely destroyed

### ISSUE THREAD

**Issue by heinrntt** [ContinuumIO/anaconda-issues#11783]
After boto3 installation Anaconda is completely destroyed.
-Anaconda Navigator 1.9.6
-Installation with Navigator environments -> Not installed search -> boto3 -> apply -> Anaconda is completely destroyed

Browser output:

Navigator Error
An unexpected error occurred on Navigator start-up

Report
Please report this issue in the anaconda issue tracker

Main Error
'NoneType' object has no attribute 'split'
Traceback
Traceback (most recent call last):
  File "C:\Users\heinr\AppData\Local\Continuum\anaconda3\lib\site-packages\anaconda_navigator\exceptions.py", line 75, in exception_handler
    return_value = func(*args, **kwargs)
  File "C:\Users\heinr\AppData\Local\Continuum\anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 151, in start_app
    window = run_app(splash)
  File "C:\Users\heinr\AppData\Local\Continuum\anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 65, in run_app
    window = MainWindow(splash=splash, tab_project=False)
  File "C:\Users\heinr\AppData\Local\Continuum\anaconda3\lib\site-packages\anaconda_navigator\widgets\main_window.py", line 170, in __init__
    self.api = AnacondaAPI()
  File "C:\Users\heinr\AppData\Local\Continuum\anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 1525, in AnacondaAPI
    ANACONDA_API = _AnacondaAPI()
  File "C:\Users\heinr\AppData\Local\Continuum\anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 77, in __init__
    self._conda_api = CondaAPI()
  File "C:\Users\heinr\AppData\Local\Continuum\anaconda3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 1804, in CondaAPI
    CONDA_API = _CondaAPI()
  File "C:\Users\heinr\AppData\Local\Continuum\anaconda3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 371, in __init__
    self.set_conda_prefix(info=get_conda_info())
  File "C:\Users\heinr\AppData\Local\Continuum\anaconda3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 540, in set_conda_prefix
    for part in info.get('conda_version').split('.'):
AttributeError: 'NoneType' object has no attribute 'split'

**Comment by vshevchenko-anaconda** [comment]
Duplicate of https://github.com/ContinuumIO/anaconda-issues/issues/11780
