### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by manojsoni2** [ContinuumIO/anaconda-issues#11788]
## Main error
Application <b>spyder</b> launch may have produced errors.
## Traceback
```
Traceback (most recent call last):
  File "C:\Users\neo\Anaconda5\Scripts\spyder-script.py", line 5, in <module>
    sys.exit(spyder.app.start.main())
  File "C:\Users\neo\Anaconda5\lib\site-packages\spyder\app\start.py", line 103, in main
    from spyder.app import mainwindow
  File "C:\Users\neo\Anaconda5\lib\site-packages\spyder\app\mainwindow.py", line 95, in <module>
    from qtawesome.iconic_font import FontError
  File "C:\Users\neo\Anaconda5\lib\site-packages\qtawesome\__init__.py", line 20, in <module>
    from .animation import Pulse, Spin
ModuleNotFoundError: No module named 'qtawesome.animation'

```
## System information
```
python: 3.6.1
language: en_US
os: Windows;8;6.2.9200;AMD64;Intel64 Family 6 Model 69 Stepping 1, GenuineIntel
version: 1.6.2
platform: win-64
qt: 5.6.2
pyqt: 5.6.0
conda: 4.5.4
```

**Comment by diegomagela** [comment]
@manojsoni2, try spyder --reset
