### ISSUE TITLE
'bytes' object has no attribute 'get'

### ISSUE THREAD

**Issue by Sandee3526** [ContinuumIO/anaconda-issues#11797]
Hi , i am unable to open anaconda navigator. Getting this exception error, it was working fine till yesterday..

Navigator Error
An unexpected error occurred on Navigator start-up

Report
Please report this issue in the anaconda issue tracker

Main Error
'bytes' object has no attribute 'get'
Traceback
Traceback (most recent call last):
  File "C:\Users\sjn\AppData\Local\Continuum\anaconda3\lib\site-packages\anaconda_navigator\exceptions.py", line 75, in exception_handler
    return_value = func(*args, **kwargs)
  File "C:\Users\sjn\AppData\Local\Continuum\anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 151, in start_app
    window = run_app(splash)
  File "C:\Users\sjn\AppData\Local\Continuum\anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 65, in run_app
    window = MainWindow(splash=splash, tab_project=False)
  File "C:\Users\sjn\AppData\Local\Continuum\anaconda3\lib\site-packages\anaconda_navigator\widgets\main_window.py", line 170, in __init__
    self.api = AnacondaAPI()
  File "C:\Users\sjn\AppData\Local\Continuum\anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 1525, in AnacondaAPI
    ANACONDA_API = _AnacondaAPI()
  File "C:\Users\sjn\AppData\Local\Continuum\anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 77, in __init__
    self._conda_api = CondaAPI()
  File "C:\Users\sjn\AppData\Local\Continuum\anaconda3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 1804, in CondaAPI
    CONDA_API = _CondaAPI()
  File "C:\Users\sjn\AppData\Local\Continuum\anaconda3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 371, in __init__
    self.set_conda_prefix(info=get_conda_info())
  File "C:\Users\sjn\AppData\Local\Continuum\anaconda3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 533, in set_conda_prefix
    self.ROOT_PREFIX = info.get('root_prefix')
AttributeError: 'bytes' object has no attribute 'get'

**Comment by hilakibe** [comment]
I am facing the same error!!!!!
Navigator Error
An unexpected error occurred on Navigator start-up

Report
Please report this issue in the anaconda issue tracker

Main Error
'bytes' object has no attribute 'get'
Traceback
Traceback (most recent call last):
  File "C:\Users\me\Anaconda3\lib\site-packages\anaconda_navigator\exceptions.py", line 75, in exception_handler
    return_value = func(*args, **kwargs)
  File "C:\Users\me\Anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 151, in start_app
    window = run_app(splash)
  File "C:\Users\me\Anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 65, in run_app
    window = MainWindow(splash=splash, tab_project=False)
  File "C:\Users\me\Anaconda3\lib\site-packages\anaconda_navigator\widgets\main_window.py", line 170, in __init__
    self.api = AnacondaAPI()
  File "C:\Users\me\Anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 1525, in AnacondaAPI
    ANACONDA_API = _AnacondaAPI()
  File "C:\Users\me\Anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 77, in __init__
    self._conda_api = CondaAPI()
  File "C:\Users\me\Anaconda3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 1804, in CondaAPI
    CONDA_API = _CondaAPI()
  File "C:\Users\me\Anaconda3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 371, in __init__
    self.set_conda_prefix(info=get_conda_info())
  File "C:\Users\me\Anaconda3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 533, in set_conda_prefix
    self.ROOT_PREFIX = info.get('root_prefix')
AttributeError: 'bytes' object has no attribute 'get'

**Comment by KalaDude** [comment]
Similar error on Ubuntu 16.04

(base) edward@neo-2018:~/anaconda3$ anaconda-navigator
An unexpected error occurred on Navigator start-up<br>'bytes' object has no attribute 'get'
Traceback (most recent call last):
  File "/home/edward/anaconda3/lib/python3.7/site-packages/anaconda_navigator/exceptions.py", line 75, in exception_handler
    return_value = func(*args, **kwargs)
  File "/home/edward/anaconda3/lib/python3.7/site-packages/anaconda_navigator/app/start.py", line 151, in start_app
    window = run_app(splash)
  File "/home/edward/anaconda3/lib/python3.7/site-packages/anaconda_navigator/app/start.py", line 65, in run_app
    window = MainWindow(splash=splash, tab_project=False)
  File "/home/edward/anaconda3/lib/python3.7/site-packages/anaconda_navigator/widgets/main_window.py", line 170, in __init__
    self.api = AnacondaAPI()
  File "/home/edward/anaconda3/lib/python3.7/site-packages/anaconda_navigator/api/anaconda_api.py", line 1525, in AnacondaAPI
    ANACONDA_API = _AnacondaAPI()
  File "/home/edward/anaconda3/lib/python3.7/site-packages/anaconda_navigator/api/anaconda_api.py", line 77, in __init__
    self._conda_api = CondaAPI()
  File "/home/edward/anaconda3/lib/python3.7/site-packages/anaconda_navigator/api/conda_api.py", line 1804, in CondaAPI
    CONDA_API = _CondaAPI()
  File "/home/edward/anaconda3/lib/python3.7/site-packages/anaconda_navigator/api/conda_api.py", line 371, in __init__
    self.set_conda_prefix(info=get_conda_info())
  File "/home/edward/anaconda3/lib/python3.7/site-packages/anaconda_navigator/api/conda_api.py", line 533, in set_conda_prefix
    self.ROOT_PREFIX = info.get('root_prefix')
AttributeError: 'bytes' object has no attribute 'get'

**Comment by skupriienko** [comment]
I have the same error "AttributeError: 'bytes' object has no attribute 'get'"
