### ISSUE TITLE
issues

### ISSUE THREAD

**Issue by Brittanygirl** [ContinuumIO/anaconda-issues#11816]
##### `conda info`

<details>

```
PASTE OUTPUT HERE:

```

</details>

##### `conda list --show-channel-urls`

<details>

```
PASTE OUTPUT HERE:

```

</details>

**Comment by Brittanygirl** [comment]
'NoneType' object has no attribute 'split'

**Comment by Brittanygirl** [comment]
Traceback (most recent call last):
  File "D:\Software\Anaconda3\lib\site-packages\anaconda_navigator\exceptions.py", line 75, in exception_handler
    return_value = func(*args, **kwargs)
  File "D:\Software\Anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 151, in start_app
    window = run_app(splash)
  File "D:\Software\Anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 65, in run_app
    window = MainWindow(splash=splash, tab_project=False)
  File "D:\Software\Anaconda3\lib\site-packages\anaconda_navigator\widgets\main_window.py", line 170, in __init__
    self.api = AnacondaAPI()
  File "D:\Software\Anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 1525, in AnacondaAPI
    ANACONDA_API = _AnacondaAPI()
  File "D:\Software\Anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 77, in __init__
    self._conda_api = CondaAPI()
  File "D:\Software\Anaconda3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 1804, in CondaAPI
    CONDA_API = _CondaAPI()
  File "D:\Software\Anaconda3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 371, in __init__
    self.set_conda_prefix(info=get_conda_info())
  File "D:\Software\Anaconda3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 540, in set_conda_prefix
    for part in info.get('conda_version').split('.'):
AttributeError: 'NoneType' object has no attribute 'split'

**Comment by meetcs143** [comment]
Hey, I am facing the exact same issue. Did you fix it? If yes, do tell. Below is my issue:

`Navigator Error
An unexpected error occurred on Navigator start-up

Report
Please report this issue in the anaconda issue tracker

Main Error
'NoneType' object has no attribute 'split'
Traceback
Traceback (most recent call last):
  File "/Users/chandra.shekhr3/opt/anaconda3/lib/python3.8/site-packages/anaconda_navigator/exceptions.py", line 72, in exception_handler
    return_value = func(*args, **kwargs)
  File "/Users/chandra.shekhr3/opt/anaconda3/lib/python3.8/site-packages/anaconda_navigator/app/start.py", line 146, in start_app
    window = run_app(splash)
  File "/Users/chandra.shekhr3/opt/anaconda3/lib/python3.8/site-packages/anaconda_navigator/app/start.py", line 65, in run_app
    window = MainWindow(splash=splash)
  File "/Users/chandra.shekhr3/opt/anaconda3/lib/python3.8/site-packages/anaconda_navigator/widgets/main_window.py", line 165, in __init__
    self.api = AnacondaAPI()
  File "/Users/chandra.shekhr3/opt/anaconda3/lib/python3.8/site-packages/anaconda_navigator/api/anaconda_api.py", line 1518, in AnacondaAPI
    ANACONDA_API = _AnacondaAPI()
  File "/Users/chandra.shekhr3/opt/anaconda3/lib/python3.8/site-packages/anaconda_navigator/api/anaconda_api.py", line 82, in __init__
    self._conda_api = CondaAPI()
  File "/Users/chandra.shekhr3/opt/anaconda3/lib/python3.8/site-packages/anaconda_navigator/api/conda_api.py", line 1571, in CondaAPI
    CONDA_API = _CondaAPI()
  File "/Users/chandra.shekhr3/opt/anaconda3/lib/python3.8/site-packages/anaconda_navigator/api/conda_api.py", line 342, in __init__
    self.set_conda_prefix(info=get_conda_info())
  File "/Users/chandra.shekhr3/opt/anaconda3/lib/python3.8/site-packages/anaconda_navigator/api/conda_api.py", line 500, in set_conda_prefix
    for part in info.get('conda_version').split('.'):
AttributeError: 'NoneType' object has no attribute 'split'`
