### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by yugenechen** [ContinuumIO/anaconda-issues#11821]
## Main error
An unexpected error occurred on Navigator start-up<br>byte indices must be integers or slices, not str
## Traceback
```
Traceback (most recent call last):
  File "C:\Program Files\Anaconda3\lib\site-packages\anaconda_navigator\exceptions.py", line 75, in exception_handler
    return_value = func(*args, **kwargs)
  File "C:\Program Files\Anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 115, in start_app
    window = run_app(splash)
  File "C:\Program Files\Anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 58, in run_app
    window = MainWindow(splash=splash)
  File "C:\Program Files\Anaconda3\lib\site-packages\anaconda_navigator\widgets\main_window.py", line 160, in __init__
    self.api = AnacondaAPI()
  File "C:\Program Files\Anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 1205, in AnacondaAPI
    ANACONDA_API = _AnacondaAPI()
  File "C:\Program Files\Anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 65, in __init__
    self._conda_api = CondaAPI()
  File "C:\Program Files\Anaconda3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 1622, in CondaAPI
    CONDA_API = _CondaAPI()
  File "C:\Program Files\Anaconda3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 340, in __init__
    self.set_conda_prefix()
  File "C:\Program Files\Anaconda3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 489, in set_conda_prefix
    self.ROOT_PREFIX = info['root_prefix']
TypeError: byte indices must be integers or slices, not str

```
## System information
```
python: 3.6.1
language: en_US
os: Windows;10;10.0.18362;AMD64;Intel64 Family 6 Model 69 Stepping 1, GenuineIntel
version: 1.6.2
platform: win-64
qt: 5.6.2
pyqt: 5.6.0
conda: 4.3.21
```

**Comment by Tarun-c** [comment]
I'm also getting an error while open anaconda navigator application.but when I'm open spyder it's perfectly open.
An unexpected error occurred on Navigator start-up

Main Error

'bytes' object has no attribute 'get'

Traceback

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\anaconda_navigator\exceptions.py", line 75, in exception_handler
    return_value = func(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 151, in start_app
    window = run_app(splash)
  File "C:\ProgramData\Anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 65, in run_app
    window = MainWindow(splash=splash, tab_project=False)
  File "C:\ProgramData\Anaconda3\lib\site-packages\anaconda_navigator\widgets\main_window.py", line 170, in __init__
    self.api = AnacondaAPI()
  File "C:\ProgramData\Anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 1525, in AnacondaAPI
    ANACONDA_API = _AnacondaAPI()
  File "C:\ProgramData\Anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 77, in __init__
    self._conda_api = CondaAPI()
  File "C:\ProgramData\Anaconda3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 1804, in CondaAPI
    CONDA_API = _CondaAPI()
  File "C:\ProgramData\Anaconda3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 371, in __init__
    self.set_conda_prefix(info=get_conda_info())
  File "C:\ProgramData\Anaconda3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 533, in set_conda_prefix
    self.ROOT_PREFIX = info.get('root_prefix')
AttributeError: 'bytes' object has no attribute 'get'

**Comment by chantya127** [comment]
Try removing .condarc file from the directory ,as it might be corrupted.

OR

**Try these commands** :
1) conda update anaconda-navigator
2) conda update navigator-updater
3) anaconda-navigator --reset

**Comment by yugenechen** [comment]
What worked in the end was uninstalling Anaconda and re-installing it.  I had both Python 2 and Python 3 installed in different locations.  I noted after opening this error case that I could not create any environments in Python 3.  Environment options Create, Clone, Import, (and Remove) were all grayed out.  Uninstalling and re-installing only Anaconda 3 seems to have solved the issue.  I also used conda and the Anaconda Navigator package manager to add the other packages I had previously installed.  It took three days to install and re-configure everything but all seems good (but Anaconda 3 is very slow starting up).
