### ISSUE TITLE
Navigator Error - I was asked to report it

### ISSUE THREAD

**Issue by blaasa** [ContinuumIO/anaconda-issues#11830]
### Actual Behavior

Error occurred when I tried to start Anaconda.
Anaconda asked me to report this error, and so I do.

### Expected Behavior

Should start without error.

### Steps to Reproduce

I just clicked on the Anaconda icon in my tools bar (Windows 2010), as I always did to start Anaconda.

##### Anaconda or Miniconda version:
Anaconda3-2019.10-Windows-x86_64.exe

##### `conda info`

Unfortunately Anaconda / conda does not start anymore. I just put here now the Error and Traceback:

Main Error

'bytes' object has no attribute 'get'

Traceback

Traceback (most recent call last):
  File "C:\Tools\Anaconda3\lib\site-packages\anaconda_navigator\exceptions.py", line 75, in exception_handler
    return_value = func(*args, **kwargs)
  File "C:\Tools\Anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 151, in start_app
    window = run_app(splash)
  File "C:\Tools\Anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 65, in run_app
    window = MainWindow(splash=splash, tab_project=False)
  File "C:\Tools\Anaconda3\lib\site-packages\anaconda_navigator\widgets\main_window.py", line 170, in __init__
    self.api = AnacondaAPI()
  File "C:\Tools\Anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 1525, in AnacondaAPI
    ANACONDA_API = _AnacondaAPI()
  File "C:\Tools\Anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 77, in __init__
    self._conda_api = CondaAPI()
  File "C:\Tools\Anaconda3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 1804, in CondaAPI
    CONDA_API = _CondaAPI()
  File "C:\Tools\Anaconda3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 371, in __init__
    self.set_conda_prefix(info=get_conda_info())
  File "C:\Tools\Anaconda3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 533, in set_conda_prefix
    self.ROOT_PREFIX = info.get('root_prefix')
AttributeError: 'bytes' object has no attribute 'get'

<details>

```
PASTE OUTPUT HERE:

```

</details>

##### `conda list --show-channel-urls`

<details>

```
PASTE OUTPUT HERE:

```

</details>

**Comment by csoja** [comment]
There are some suggestions in the Troubleshooting section of the Navigator documentation that may be of help: https://docs.anaconda.com/anaconda/navigator/troubleshooting/#troubleshooting
