### ISSUE TITLE
Anaconda Jypiter wont start, Spyder reporting errors

### ISSUE THREAD

**Issue by spiralciric** [ContinuumIO/anaconda-issues#11857]
I did try uninstalling and installing Anaconda, but the problem remains the same.
Windows 10 x64, latest Anaconda
Installation goes fine, but when I start Spyder it reports this:
"You have missing dependencies, nbconvert >=4.0": None. However, nbconvert is already installed.
It prompted me to install Kite, when I did it says Kite installation error.
When I try to launch jupyter lab I get this:
Traceback (most recent call last):
File "C:\Users\Aleksandar\anaconda3\Scripts\jupyter-lab-script.py", line 5, in 
from jupyterlab.labapp import main
File "C:\Users\Aleksandar\anaconda3\lib\site-packages\jupyterlab\labapp.py", line 14, in 
from jupyterlab_server import slugify, WORKSPACE_EXTENSION
File "C:\Users\Aleksandar\anaconda3\lib\site-packages\jupyterlab_server\__init__.py", line 4, in 
from .app import LabServerApp
File "C:\Users\Aleksandar\anaconda3\lib\site-packages\jupyterlab_server\app.py", line 9, in 
from .server import ServerApp
File "C:\Users\Aleksandar\anaconda3\lib\site-packages\jupyterlab_server\server.py", line 14, in 
from notebook.base.handlers import (
File "C:\Users\Aleksandar\anaconda3\lib\site-packages\notebook\base\handlers.py", line 22, in 
from tornado import web, gen, escape, httputil
File "C:\Users\Aleksandar\anaconda3\lib\site-packages\tornado\web.py", line 87, in 
from tornado.httpserver import HTTPServer
File "C:\Users\Aleksandar\anaconda3\lib\site-packages\tornado\httpserver.py", line 32, in 
from tornado.http1connection import HTTP1ServerConnection, HTTP1ConnectionParameters
File "C:\Users\Aleksandar\anaconda3\lib\site-packages\tornado\http1connection.py", line 34, in 
from tornado import iostream
File "C:\Users\Aleksandar\anaconda3\lib\site-packages\tornado\iostream.py", line 40, in 
from tornado.netutil import ssl_wrap_socket, _client_ssl_defaults, _server_ssl_defaults
File "C:\Users\Aleksandar\anaconda3\lib\site-packages\tornado\netutil.py", line 39, in 
_client_ssl_defaults = ssl.create_default_context(ssl.Purpose.SERVER_AUTH)
File "C:\Users\Aleksandar\anaconda3\lib\ssl.py", line 589, in create_default_context
context.load_default_certs(purpose)
File "C:\Users\Aleksandar\anaconda3\lib\ssl.py", line 490, in load_default_certs
self._load_windows_store_certs(storename, purpose)
File "C:\Users\Aleksandar\anaconda3\lib\ssl.py", line 482, in _load_windows_store_certs
self.load_verify_locations(cadata=certs)
ssl.SSLError: nested asn1 error (_ssl.c:4003)

**Comment by BillS85** [comment]
I have a similar problem that occurred after I tried to uninstall osmnx using pip in the conda environment, I assume pip has corrupted the dependencies and now I worry that if I uninstall 
Anaconda and reinstall it that other problems will present themselves. I should have stuck with pandas and altair Live and learn.
