### ISSUE TITLE
Anaconda Will Not Start - Was Working fine

### ISSUE THREAD

**Issue by marcusobrien** [ContinuumIO/anaconda-issues#11856]
### Actual Behavior
Run Anaconda, crashes straight to browser exception

### Expected Behavior
Anaconda to start up normally, was working fine 10 minutes ago. 

Navigator Error
An unexpected error occurred on Navigator start-up

Report
Please report this issue in the anaconda issue tracker

Main Error
'list' object has no attribute 'get'
Traceback
Traceback (most recent call last):
  File "C:\Users\marcu\anaconda3\lib\site-packages\anaconda_navigator\exceptions.py", line 75, in exception_handler
    return_value = func(*args, **kwargs)
  File "C:\Users\marcu\anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 151, in start_app
    window = run_app(splash)
  File "C:\Users\marcu\anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 65, in run_app
    window = MainWindow(splash=splash, tab_project=False)
  File "C:\Users\marcu\anaconda3\lib\site-packages\anaconda_navigator\widgets\main_window.py", line 170, in __init__
    self.api = AnacondaAPI()
  File "C:\Users\marcu\anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 1525, in AnacondaAPI
    ANACONDA_API = _AnacondaAPI()
  File "C:\Users\marcu\anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 77, in __init__
    self._conda_api = CondaAPI()
  File "C:\Users\marcu\anaconda3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 1804, in CondaAPI
    CONDA_API = _CondaAPI()
  File "C:\Users\marcu\anaconda3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 371, in __init__
    self.set_conda_prefix(info=get_conda_info())
  File "C:\Users\marcu\anaconda3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 533, in set_conda_prefix
    self.ROOT_PREFIX = info.get('root_prefix')
AttributeError: 'list' object has no attribute 'get'

### Steps to Reproduce
Run Anaconda - double click it in Windows 10

##### Operating System:
Window 10

##### `conda info`

```
active environment : TF1WithAlpha
    active env location : C:\Users\marcu\anaconda3\envs\TF1WithAlpha
            shell level : 1
       user config file : C:\Users\marcu\.condarc
 populated config files : C:\Users\marcu\.condarc
          conda version : 4.8.2
    conda-build version : 3.18.11
         python version : 3.7.6.final.0
       virtual packages : __cuda=11.0
       base environment : C:\Users\marcu\anaconda3  (writable)
           channel URLs : https://conda.anaconda.org/marcus7/win-64
                          https://conda.anaconda.org/marcus7/noarch
                          https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
                          https://conda.anaconda.org/conda-forge/win-64
                          https://conda.anaconda.org/conda-forge/noarch
          package cache : C:\Users\marcu\anaconda3\pkgs
                          C:\Users\marcu\.conda\pkgs
                          C:\Users\marcu\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\marcu\anaconda3\envs
                          C:\Users\marcu\.conda\envs
                          C:\Users\marcu\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.8.2 requests/2.22.0 CPython/3.7.6 Windows/10 Windows/10.0.18362
          administrator : False
             netrc file : None
           offline mode : False

```

##### `conda list --show-channel-urls`

```
# packages in environment at C:\Users\marcu\anaconda3\envs\TF1WithAlpha:
#
# Name                    Version                   Build  Channel
absl-py                   0.9.0                    py36_0    defaults
alabaster                 0.7.12                   py36_0    defaults
argh                      0.26.2                   py36_0    defaults
astor                     0.8.0                    py36_0    defaults
astroid                   2.4.1                    py36_0    defaults
atomicwrites              1.4.0                      py_0    defaults
attrs                     19.3.0                     py_0    defaults
autopep8                  1.4.4                      py_0    defaults
babel                     2.8.0                      py_0    defaults
backcall                  0.1.0                    py36_0    defaults
bcrypt                    3.1.7            py36he774522_0    defaults
blas                      1.0                         mkl    defaults
bleach                    3.1.4                      py_0    defaults
ca-certificates           2020.1.1                      0    defaults
certifi                   2020.4.5.1               py36_0    defaults
cffi                      1.14.0           py36h7a1dbc1_0    defaults
chardet                   3.0.4                 py36_1003    defaults
cloudpickle               1.4.1                      py_0    defaults
colorama                  0.4.3                      py_0    defaults
console_shortcut          0.1.1                         4    defaults
cryptography              2.9.2            py36h7a1dbc1_0    defaults
cycler                    0.10.0           py36h009560c_0    defaults
decorator                 4.4.2                      py_0    defaults
defusedxml                0.6.0                      py_0    defaults
diff-match-patch          20181111                   py_0    defaults
docutils                  0.16                     py36_0    defaults
entrypoints               0.3                      py36_0    defaults
flake8                    3.7.9                    py36_0    defaults
freetype                  2.9.1                ha9979f8_1    defaults
future                    0.18.2                   py36_0    defaults
gast                      0.3.3                      py_0    defaults
grpcio                    1.27.2           py36h351948d_0    defaults
h5py                      2.10.0           py36h5e291fa_0    defaults
hdf5                      1.10.4               h7ebc959_0    defaults
icc_rt                    2019.0.0             h0cc432a_1    defaults
icu                       58.2                 ha925a31_3    defaults
idna                      2.9                        py_1    defaults
imagesize                 1.2.0                      py_0    defaults
importlib-metadata        1.6.0                    py36_0    defaults
importlib_metadata        1.6.0                         0    defaults
intel-openmp              2020.1                      216    defaults
intervaltree              3.0.2                      py_0    defaults
ipykernel                 5.1.4            py36h39e3cac_0    defaults
ipython                   7.13.0           py36h5ca1d4c_0    defaults
ipython_genutils          0.2.0                    py36_0    defaults
isort                     4.3.21                   py36_0    defaults
jedi                      0.15.2                   py36_0    defaults
jinja2                    2.11.2                     py_0    defaults
joblib                    0.15.1                     py_0    defaults
jpeg                      9b                   hb83a4c4_2    defaults
jsonschema                3.2.0                    py36_0    defaults
jupyter_client            6.1.3                      py_0    defaults
jupyter_core              4.6.3                    py36_0    defaults
keras                     2.3.1                         0    defaults
keras-applications        1.0.8                      py_0    defaults
keras-base                2.3.1                    py36_0    defaults
keras-preprocessing       1.1.0                      py_1    defaults
keyring                   21.1.1                   py36_2    defaults
kiwisolver                1.2.0            py36h74a9793_0    defaults
lazy-object-proxy         1.4.3            py36he774522_0    defaults
libiconv                  1.15                 h1df5818_7    defaults
libpng                    1.6.37               h2a8f88b_0    defaults
libprotobuf               3.11.4               h7bd577a_0    defaults
libsodium                 1.0.16               h9d3ae62_0    defaults
libspatialindex           1.9.3                h33f27b4_0    defaults
libxml2                   2.9.9                h464c3ec_0    defaults
libxslt                   1.1.33               h579f668_0    defaults
lxml                      4.5.0            py36h1350720_0    defaults
markdown                  3.1.1                    py36_0    defaults
markupsafe                1.1.1            py36he774522_0    defaults
matplotlib                3.1.3                    py36_0    defaults
matplotlib-base           3.1.3            py36h64f37c6_0    defaults
mccabe                    0.6.1                    py36_1    defaults
mistune                   0.8.4            py36he774522_0    defaults
mkl                       2020.1                      216    defaults
mkl-service               2.3.0            py36hb782905_0    defaults
mkl_fft                   1.0.15           py36h14836fe_0    defaults
mkl_random                1.1.0            py36h675688f_0    defaults
nbconvert                 5.6.1                    py36_0    defaults
nbformat                  5.0.6                      py_0    defaults
numpy                     1.18.1           py36h93ca92e_0    defaults
numpy-base                1.18.1           py36hc3f5095_1    defaults
numpydoc                  0.9.2                      py_0    defaults
openssl                   1.1.1g               he774522_0    defaults
packaging                 20.3                       py_0    defaults
pandas                    1.0.3            py36h47e9c7a_0    defaults
pandas-datareader         0.8.1                      py_0    defaults
pandoc                    2.2.3.2                       0    defaults
pandocfilters             1.4.2                    py36_1    defaults
paramiko                  2.7.1                      py_0    defaults
parso                     0.5.2                      py_0    defaults
pathtools                 0.1.2                      py_1    defaults
pexpect                   4.8.0                    py36_0    defaults
pickleshare               0.7.5                    py36_0    defaults
pip                       20.0.2                   py36_3    defaults
pluggy                    0.13.1                   py36_0    defaults
prompt-toolkit            3.0.4                      py_0    defaults
prompt_toolkit            3.0.4                         0    defaults
protobuf                  3.11.4           py36h33f27b4_0    defaults
psutil                    5.7.0            py36he774522_0    defaults
pycodestyle               2.5.0                    py36_0    defaults
pycparser                 2.20                       py_0    defaults
pydocstyle                4.0.1                      py_0    defaults
pyflakes                  2.1.1                    py36_0    defaults
pygments                  2.6.1                      py_0    defaults
pylint                    2.5.2                    py36_0    defaults
pynacl                    1.3.0            py36h62dcd97_0    defaults
pyopenssl                 19.1.0                   py36_0    defaults
pyparsing                 2.4.7                      py_0    defaults
pyqt                      5.9.2            py36h6538335_2    defaults
pyreadline                2.1                      py36_1    defaults
pyrsistent                0.16.0           py36he774522_0    defaults
pysocks                   1.7.1                    py36_0    defaults
python                    3.6.10               h9f7ef89_2    defaults
python-dateutil           2.8.1                      py_0    defaults
python-jsonrpc-server     0.3.4                      py_0    defaults
python-language-server    0.31.10                  py36_0    defaults
pytz                      2020.1                     py_0    defaults
pywin32                   227              py36he774522_1    defaults
pywin32-ctypes            0.2.0                 py36_1000    defaults
pyyaml                    5.3.1            py36he774522_0    defaults
pyzmq                     18.1.1           py36ha925a31_0    defaults
qdarkstyle                2.8.1                      py_0    defaults
qt                        5.9.7            vc14h73c81de_0    defaults
qtawesome                 0.7.0                      py_0    defaults
qtconsole                 4.7.4                      py_0    defaults
qtpy                      1.9.0                      py_0    defaults
requests                  2.23.0                   py36_0    defaults
rope                      0.17.0                     py_0    defaults
rtree                     0.9.4            py36h21ff451_1    defaults
scikit-learn              0.22.1           py36h6288b17_0    defaults
scipy                     1.4.1            py36h9439919_0    defaults
setuptools                46.4.0                   py36_0    defaults
sip                       4.19.8           py36h6538335_0    defaults
six                       1.14.0                   py36_0    defaults
snowballstemmer           2.0.0                      py_0    defaults
sortedcontainers          2.1.0                    py36_0    defaults
sphinx                    3.0.3                      py_0    defaults
sphinxcontrib-applehelp   1.0.2                      py_0    defaults
sphinxcontrib-devhelp     1.0.2                      py_0    defaults
sphinxcontrib-htmlhelp    1.0.3                      py_0    defaults
sphinxcontrib-jsmath      1.0.1                      py_0    defaults
sphinxcontrib-qthelp      1.0.3                      py_0    defaults
sphinxcontrib-serializinghtml 1.1.4                      py_0    defaults
spyder                    4.1.3                    py36_0    defaults
spyder-kernels            1.9.1                    py36_0    defaults
sqlite                    3.31.1               h2a8f88b_1    defaults
tensorboard               1.13.1                   py36_0    conda-forge
tensorflow                1.13.2               h21ff451_0    conda-forge
tensorflow-base           1.13.2                   py36_0    conda-forge
tensorflow-estimator      1.13.0           py36h39e3cac_0    conda-forge
termcolor                 1.1.0                    py36_1    defaults
testpath                  0.4.4                      py_0    defaults
toml                      0.10.0           py36h28b3542_0    defaults
tornado                   6.0.4            py36he774522_1    defaults
traitlets                 4.3.3                    py36_0    defaults
typed-ast                 1.4.1            py36he774522_0    defaults
ujson                     1.35             py36hfa6e2cd_0    defaults
urllib3                   1.25.8                   py36_0    defaults
vc                        14.1                 h0510ff6_4    defaults
vs2015_runtime            14.16.27012          hf0eaf9b_2    defaults
watchdog                  0.10.2                   py36_0    defaults
wcwidth                   0.1.9                      py_0    defaults
webencodings              0.5.1                    py36_1    defaults
werkzeug                  1.0.1                      py_0    defaults
wheel                     0.34.2                   py36_0    defaults
win_inet_pton             1.1.0                    py36_0    defaults
wincertstore              0.2              py36h7fe50ca_0    defaults
wrapt                     1.11.2           py36he774522_0    defaults
yaml                      0.1.7                hc54c509_2    defaults
yapf                      0.28.0                     py_0    defaults
zeromq                    4.3.1                h33f27b4_3    defaults
zipp                      3.1.0                      py_0    defaults
zlib                      1.2.11               h62dcd97_4    defaults

```
</details>

**Comment by csoja** [comment]
Perhaps your .condarc conda configuration file has gotten corrupted? https://docs.anaconda.com/anaconda/navigator/troubleshooting/#navigator-error-on-start-up
