### ISSUE TITLE
Jupyter notebook fails to launch

### ISSUE THREAD

**Issue by AnupamSaraph** [ContinuumIO/anaconda-issues#11878]
Jupyter notebook fails to launch on shift-enter with the following error:

>Jupyter notebook failed to launch. Error: Traceback (most recent call last): File "C:\ProgramData\Anaconda3\lib\site-packages\jsonschema\__init__.py", line 31, in <module> from importlib import metadata ImportError: cannot import name 'metadata' from 'importlib' (C:\ProgramData\Anaconda3\lib\importlib\__init__.py) During handling of the above exception, another exception occurred: Traceback (most recent call last): File "C:\ProgramData\Anaconda3\lib\site-packages\nbformat\validator.py", line 12, in <module> from jsonschema import ValidationError File "C:\ProgramData\Anaconda3\lib\site-packages\jsonschema\__init__.py", line 33, in <module> import importlib_metadata as metadata ModuleNotFoundError: No module named 'importlib_metadata' During handling of the above exception, another exception occurred: Traceback (most recent call last): File "c:\Users\Anupam Saraph\.vscode\extensions\ms-python.python-2020.6.88468\pythonFiles\vscode_datascience_helpers\daemon\daem...

**Comment by ArthurZ** [comment]
Also got it
