### ISSUE TITLE
Spyder 4.1.3 fails to launch after update

### ISSUE THREAD

**Issue by sdmayor** [ContinuumIO/anaconda-issues#11884]
Hello, I updated Anaconda Navigator and Spyder today as it suggested that I do and now Spyder fails to launch.  Anaconda Navigator is version 1.9.12 and Spyder is version 4.1.3.   On a Mac Pro under High Sierra 10.13.6.

When I click on the Spyder launch button, it goes through an initialization, and looks like it is trying to load the editor and console but the IDE never appears and it leaves me with an "Application launch error" window containing the following:

Traceback (most recent call last):
File "/Users/sdmayor/anaconda3/bin/spyder", line 11, in 
sys.exit(main())
File "/Users/sdmayor/anaconda3/lib/python3.6/site-packages/spyder/app/start.py", line 205, in main
mainwindow.main()
File "/Users/sdmayor/anaconda3/lib/python3.6/site-packages/spyder/app/mainwindow.py", line 3748, in main
mainwindow = run_spyder(app, options, args)
File "/Users/sdmayor/anaconda3/lib/python3.6/site-packages/spyder/app/mainwindow.py", line 3623, in run_spyder
main.setup()
File "/Users/sdmayor/anaconda3/lib/python3.6/site-packages/spyder/app/mainwindow.py", line 945, in setup
from spyder.plugins.ipythonconsole.plugin import IPythonConsole
File "/Users/sdmayor/anaconda3/lib/python3.6/site-packages/spyder/plugins/ipythonconsole/plugin.py", line 46, in 
from spyder.plugins.ipythonconsole.widgets import (ClientWidget,
File "/Users/sdmayor/anaconda3/lib/python3.6/site-packages/spyder/plugins/ipythonconsole/widgets/__init__.py", line 16, in 
from .debugging import DebuggingWidget
File "/Users/sdmayor/anaconda3/lib/python3.6/site-packages/spyder/plugins/ipythonconsole/widgets/debugging.py", line 22, in 
from IPython.core.inputtransformer2 import TransformerManager
ModuleNotFoundError: No module named 'IPython.core.inputtransformer2'

Any assistance is greatly appreciated.

**Comment by ccordoba12** [comment]
Please run

    conda update ipython

to fix this problem.

**Comment by sdmayor** [comment]
Thank you!  That fixed it.
