### ISSUE TITLE
navigation issue

### ISSUE THREAD

**Issue by berryq460** [ContinuumIO/anaconda-issues#11904]
##### `conda info`

<details>

```
PASTE OUTPUT HERE:

```Traceback (most recent call last):
File "C:\Users\Quiana\Anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 134, in start_app
with lock.acquire(timeout=3.0): # timeout in seconds
File "C:\Users\Quiana\Anaconda3\lib\site-packages\anaconda_navigator\external\filelock.py", line 259, in acquire
raise Timeout(self._lock_file)
anaconda_navigator.external.filelock.Timeout: The file lock 'C:\Users\Quiana\.anaconda\navigator\navigator.lock' could not be acquired.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "C:\Users\Quiana\Anaconda3\lib\site-packages\anaconda_navigator\exceptions.py", line 75, in exception_handler
return_value = func(*args, **kwargs)
File "C:\Users\Quiana\Anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 147, in start_app
"There is an instance of "
File "C:\Users\Quiana\Anaconda3\lib\site-packages\anaconda_navigator\widgets\dialogs\__init__.py", line 451, in __init__
type_=self.INFORMATION_BOX,
File "C:\Users\Quiana\Anaconda3\lib\site-packages\anaconda_navigator\widgets\dialogs\__init__.py", line 265, in __init__
self.tracker = GATracker()
File "C:\Users\Quiana\Anaconda3\lib\site-packages\anaconda_navigator\utils\analytics.py", line 285, in GATracker
GA_TRACKER = _GATracker()
File "C:\Users\Quiana\Anaconda3\lib\site-packages\anaconda_navigator\utils\analytics.py", line 100, in __init__
self.api = AnacondaAPI()
File "C:\Users\Quiana\Anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 2183, in AnacondaAPI
ANACONDA_API = _AnacondaAPI()
File "C:\Users\Quiana\Anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 89, in __init__
self._conda_api = CondaAPI()
File "C:\Users\Quiana\Anaconda3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 1714, in CondaAPI
CONDA_API = _CondaAPI()
File "C:\Users\Quiana\Anaconda3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 353, in __init__
self.sys_rc_path = join(self.ROOT_PREFIX, '.condarc')
File "C:\Users\Quiana\Anaconda3\lib\ntpath.py", line 75, in join
path = os.fspath(path)
TypeError: expected str, bytes or os.PathLike object, not NoneType


</details>

##### `conda list --show-channel-urls`
<!-- Paste the output of 'conda list --show-channel-urls' between the two sets of backticks (```) below -->

<details>

```
PASTE OUTPUT HERE:

```

</details>

**Comment by pujapai-333** [comment]
Navigator Error
An unexpected error occurred on Navigator start-up

Report
Please report this issue in the anaconda issue tracker

Main Error
expected str, bytes or os.PathLike object, not NoneType
Traceback
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda2\lib\site-packages\anaconda_navigator\exceptions.py", line 75, in exception_handler
    return_value = func(*args, **kwargs)
  File "C:\ProgramData\Anaconda2\lib\site-packages\anaconda_navigator\app\start.py", line 150, in start_app
    window = run_app(splash)
  File "C:\ProgramData\Anaconda2\lib\site-packages\anaconda_navigator\app\start.py", line 65, in run_app
    window = MainWindow(splash=splash, tab_project=False)
  File "C:\ProgramData\Anaconda2\lib\site-packages\anaconda_navigator\widgets\main_window.py", line 168, in __init__
    self.api = AnacondaAPI()
  File "C:\ProgramData\Anaconda2\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 2294, in AnacondaAPI
    ANACONDA_API = _AnacondaAPI()
  File "C:\ProgramData\Anaconda2\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 91, in __init__
    self._conda_api = CondaAPI()
  File "C:\ProgramData\Anaconda2\lib\site-packages\anaconda_navigator\api\conda_api.py", line 1767, in CondaAPI
    CONDA_API = _CondaAPI()
  File "C:\ProgramData\Anaconda2\lib\site-packages\anaconda_navigator\api\conda_api.py", line 353, in __init__
    self.sys_rc_path = join(self.ROOT_PREFIX, '.condarc')
  File "C:\ProgramData\Anaconda2\lib\ntpath.py", line 76, in join
    path = os.fspath(path)
TypeError: expected str, bytes or os.PathLike object, not NoneType

**Comment by csoja** [comment]
Please see https://docs.anaconda.com/anaconda/navigator/troubleshooting/#navigator-error-on-start-up
