### ISSUE TITLE
I downloaded latest anaconda navigator but it cannot open. it prompts and close the window

### ISSUE THREAD

**Issue by akshaye1** [ContinuumIO/anaconda-issues#11945]
Traceback (most recent call last):
  File "C:\Users\HP\anaconda3\lib\site-packages\conda\exceptions.py", line 1079, in __call__
    return func(*args, **kwargs)
  File "C:\Users\HP\anaconda3\lib\site-packages\conda\cli\main.py", line 84, in _main
    exit_code = do_call(args, p)
  File "C:\Users\HP\anaconda3\lib\site-packages\conda\cli\conda_argparse.py", line 80, in do_call
    module = import_module(relative_mod, __name__.rsplit('.', 1)[0])
  File "C:\Users\HP\anaconda3\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\HP\anaconda3\lib\site-packages\conda\cli\main_update.py", line 8, in <module>
    from .install import install
  File "C:\Users\HP\anaconda3\lib\site-packages\conda\cli\install.py", line 19, in <module>
    from ..core.index import calculate_channel_urls, get_index
  File "C:\Users\HP\anaconda3\lib\site-packages\conda\core\index.py", line 10, in <module>
    from .package_cache_data import PackageCacheData
  File "C:\Users\HP\anaconda3\lib\site-packages\conda\core\package_cache_data.py", line 15, in <module>
    from .path_actions import CacheUrlAction, ExtractPackageAction
  File "C:\Users\HP\anaconda3\lib\site-packages\conda\core\path_actions.py", line 30, in <module>
    from ..gateways.connection.download import download
  File "C:\Users\HP\anaconda3\lib\site-packages\conda\gateways\connection\__init__.py", line 21, in <module>
    from requests import ConnectionError, HTTPError, Session
  File "C:\Users\HP\anaconda3\lib\site-packages\requests\__init__.py", line 112, in <module>
    from . import utils
  File "C:\Users\HP\anaconda3\lib\site-packages\requests\utils.py", line 26, in <module>
    from ._internal_utils import to_native_string
  File "C:\Users\HP\anaconda3\lib\site-packages\requests\_internal_utils.py", line 11, in <module>
    from .compat import is_py2, builtin_str, str
  File "C:\Users\HP\anaconda3\lib\site-packages\requests\compat.py", line 60, in <module>
    from http.cookies import Morsel
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 859, in get_code
  File "<frozen importlib._bootstrap_external>", line 917, in get_data
OSError: [Errno 9] Bad file descriptor

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\HP\anaconda3\Scripts\conda-script.py", line 12, in <module>
    sys.exit(main())
  File "C:\Users\HP\anaconda3\lib\site-packages\conda\cli\main.py", line 150, in main
    return conda_exception_handler(_main, *args, **kwargs)
  File "C:\Users\HP\anaconda3\lib\site-packages\conda\exceptions.py", line 1371, in conda_exception_handler
    return_value = exception_handler(func, *args, **kwargs)
  File "C:\Users\HP\anaconda3\lib\site-packages\conda\exceptions.py", line 1082, in __call__
    return self.handle_exception(exc_val, exc_tb)
  File "C:\Users\HP\anaconda3\lib\site-packages\conda\exceptions.py", line 1126, in handle_exception
    return self.handle_unexpected_exception(exc_val, exc_tb)
  File "C:\Users\HP\anaconda3\lib\site-packages\conda\exceptions.py", line 1137, in handle_unexpected_exception
    self.print_unexpected_error_report(error_report)
  File "C:\Users\HP\anaconda3\lib\site-packages\conda\exceptions.py", line 1207, in print_unexpected_error_report
    from .cli.main_info import get_env_vars_str, get_main_info_str
  File "C:\Users\HP\anaconda3\lib\site-packages\conda\cli\main_info.py", line 19, in <module>
    from ..core.index import _supplement_index_with_system
  File "C:\Users\HP\anaconda3\lib\site-packages\conda\core\index.py", line 10, in <module>
    from .package_cache_data import PackageCacheData
  File "C:\Users\HP\anaconda3\lib\site-packages\conda\core\package_cache_data.py", line 15, in <module>
    from .path_actions import CacheUrlAction, ExtractPackageAction
  File "C:\Users\HP\anaconda3\lib\site-packages\conda\core\path_actions.py", line 30, in <module>
    from ..gateways.connection.download import download
  File "C:\Users\HP\anaconda3\lib\site-packages\conda\gateways\connection\__init__.py", line 21, in <module>
    from requests import ConnectionError, HTTPError, Session
  File "C:\Users\HP\anaconda3\lib\site-packages\requests\__init__.py", line 112, in <module>
    from . import utils
  File "C:\Users\HP\anaconda3\lib\site-packages\requests\utils.py", line 26, in <module>
    from ._internal_utils import to_native_string
  File "C:\Users\HP\anaconda3\lib\site-packages\requests\_internal_utils.py", line 11, in <module>
    from .compat import is_py2, builtin_str, str
  File "C:\Users\HP\anaconda3\lib\site-packages\requests\compat.py", line 60, in <module>
    from http.cookies import Morsel
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 859, in get_code
  File "<frozen importlib._bootstrap_external>", line 917, in get_data
OSError: [Errno 9] Bad file descriptor

**Comment by Shogun-007** [comment]
Same issue can any one help
