### ISSUE TITLE
OSError: [Errno 9] Bad file descriptor anaconda app not opening 

### ISSUE THREAD

**Issue by vartika-123** [ContinuumIO/anaconda-issues#11949]
### Actual Behavior

raceback (most recent call last):
  File "C:\Users\TEMP\anaconda3\Scripts\pip-script.py", line 10, in <module>
    sys.exit(main())
  File "C:\Users\TEMP\anaconda3\lib\site-packages\pip\_internal\cli\main.py", line 73, in main
    command = create_command(cmd_name, isolated=("--isolated" in cmd_args))
  File "C:\Users\TEMP\anaconda3\lib\site-packages\pip\_internal\commands\__init__.py", line 96, in create_command
    module = importlib.import_module(module_path)
  File "C:\Users\TEMP\anaconda3\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\TEMP\anaconda3\lib\site-packages\pip\_internal\commands\install.py", line 24, in <module>
    from pip._internal.cli.req_command import RequirementCommand
  File "C:\Users\TEMP\anaconda3\lib\site-packages\pip\_internal\cli\req_command.py", line 15, in <module>
    from pip._internal.index.package_finder import PackageFinder
  File "C:\Users\TEMP\anaconda3\lib\site-packages\pip\_internal\index\package_finder.py", line 21, in <module>
    from pip._internal.index.collector import parse_links
  File "C:\Users\TEMP\anaconda3\lib\site-packages\pip\_internal\index\collector.py", line 12, in <module>
    from pip._vendor import html5lib, requests
  File "C:\Users\TEMP\anaconda3\lib\site-packages\pip\_vendor\requests\__init__.py", line 114, in <module>
    from . import utils
  File "C:\Users\TEMP\anaconda3\lib\site-packages\pip\_vendor\requests\utils.py", line 26, in <module>
    from ._internal_utils import to_native_string
  File "C:\Users\TEMP\anaconda3\lib\site-packages\pip\_vendor\requests\_internal_utils.py", line 11, in <module>
    from .compat import is_py2, builtin_str, str
  File "C:\Users\TEMP\anaconda3\lib\site-packages\pip\_vendor\requests\compat.py", line 64, in <module>
    from http.cookies import Morsel
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 859, in get_code
  File "<frozen importlib._bootstrap_external>", line 917, in get_data
OSError: [Errno 9] Bad file descriptor

(base) C:\Users\TEMP>
(base) C:\Users\TEMP>1
'1' is not recognized as an internal or external command,
operable program or batch file.

(base) C:\Users\TEMP>conda update conda
Traceback (most recent call last):
  File "C:\Users\TEMP\anaconda3\lib\site-packages\conda\exceptions.py", line 1079, in __call__
    return func(*args, **kwargs)
  File "C:\Users\TEMP\anaconda3\lib\site-packages\conda\cli\main.py", line 84, in _main
    exit_code = do_call(args, p)
  File "C:\Users\TEMP\anaconda3\lib\site-packages\conda\cli\conda_argparse.py", line 80, in do_call
    module = import_module(relative_mod, __name__.rsplit('.', 1)[0])
  File "C:\Users\TEMP\anaconda3\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\TEMP\anaconda3\lib\site-packages\conda\cli\main_update.py", line 8, in <module>
    from .install import install
  File "C:\Users\TEMP\anaconda3\lib\site-packages\conda\cli\install.py", line 19, in <module>
    from ..core.index import calculate_channel_urls, get_index
  File "C:\Users\TEMP\anaconda3\lib\site-packages\conda\core\index.py", line 10, in <module>
    from .package_cache_data import PackageCacheData
  File "C:\Users\TEMP\anaconda3\lib\site-packages\conda\core\package_cache_data.py", line 15, in <module>
    from .path_actions import CacheUrlAction, ExtractPackageAction
  File "C:\Users\TEMP\anaconda3\lib\site-packages\conda\core\path_actions.py", line 30, in <module>
    from ..gateways.connection.download import download
  File "C:\Users\TEMP\anaconda3\lib\site-packages\conda\gateways\connection\__init__.py", line 21, in <module>
    from requests import ConnectionError, HTTPError, Session
  File "C:\Users\TEMP\anaconda3\lib\site-packages\requests\__init__.py", line 112, in <module>
    from . import utils
  File "C:\Users\TEMP\anaconda3\lib\site-packages\requests\utils.py", line 26, in <module>
    from ._internal_utils import to_native_string
  File "C:\Users\TEMP\anaconda3\lib\site-packages\requests\_internal_utils.py", line 11, in <module>
    from .compat import is_py2, builtin_str, str
  File "C:\Users\TEMP\anaconda3\lib\site-packages\requests\compat.py", line 60, in <module>
    from http.cookies import Morsel
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 859, in get_code
  File "<frozen importlib._bootstrap_external>", line 917, in get_data
OSError: [Errno 9] Bad file descriptor

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\TEMP\anaconda3\Scripts\conda-script.py", line 12, in <module>
    sys.exit(main())
  File "C:\Users\TEMP\anaconda3\lib\site-packages\conda\cli\main.py", line 150, in main
    return conda_exception_handler(_main, *args, **kwargs)
  File "C:\Users\TEMP\anaconda3\lib\site-packages\conda\exceptions.py", line 1371, in conda_exception_handler
    return_value = exception_handler(func, *args, **kwargs)
  File "C:\Users\TEMP\anaconda3\lib\site-packages\conda\exceptions.py", line 1082, in __call__
    return self.handle_exception(exc_val, exc_tb)
  File "C:\Users\TEMP\anaconda3\lib\site-packages\conda\exceptions.py", line 1126, in handle_exception
    return self.handle_unexpected_exception(exc_val, exc_tb)
  File "C:\Users\TEMP\anaconda3\lib\site-packages\conda\exceptions.py", line 1137, in handle_unexpected_exception
    self.print_unexpected_error_report(error_report)
  File "C:\Users\TEMP\anaconda3\lib\site-packages\conda\exceptions.py", line 1207, in print_unexpected_error_report
    from .cli.main_info import get_env_vars_str, get_main_info_str
  File "C:\Users\TEMP\anaconda3\lib\site-packages\conda\cli\main_info.py", line 19, in <module>
    from ..core.index import _supplement_index_with_system
  File "C:\Users\TEMP\anaconda3\lib\site-packages\conda\core\index.py", line 10, in <module>
    from .package_cache_data import PackageCacheData
  File "C:\Users\TEMP\anaconda3\lib\site-packages\conda\core\package_cache_data.py", line 15, in <module>
    from .path_actions import CacheUrlAction, ExtractPackageAction
  File "C:\Users\TEMP\anaconda3\lib\site-packages\conda\core\path_actions.py", line 30, in <module>
    from ..gateways.connection.download import download
  File "C:\Users\TEMP\anaconda3\lib\site-packages\conda\gateways\connection\__init__.py", line 21, in <module>
    from requests import ConnectionError, HTTPError, Session
  File "C:\Users\TEMP\anaconda3\lib\site-packages\requests\__init__.py", line 112, in <module>
    from . import utils
  File "C:\Users\TEMP\anaconda3\lib\site-packages\requests\utils.py", line 26, in <module>
    from ._internal_utils import to_native_string
  File "C:\Users\TEMP\anaconda3\lib\site-packages\requests\_internal_utils.py", line 11, in <module>
    from .compat import is_py2, builtin_str, str
  File "C:\Users\TEMP\anaconda3\lib\site-packages\requests\compat.py", line 60, in <module>
    from http.cookies import Morsel
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 859, in get_code
  File "<frozen importlib._bootstrap_external>", line 917, in get_data
OSError: [Errno 9] Bad file descriptor

##### `conda info`

<details>

```
PASTE OUTPUT HERE:

```

</details>

##### `conda list --show-channel-urls`

<details>

```
PASTE OUTPUT HERE:

```

</details>

**Comment by vartika-123** [comment]
i guess it is some windows error because after some time i had to  reinstalled my windows and it started working after that
so u can try that if u can

**Comment by Pranavmaid** [comment]
Yes you are right 
it was windows error which comes when file is not close properly 
I Run " python -c "from http.cookies import Morsel" " on Windows Safe mode and it work for me

**Comment by Anish113** [comment]
This is the error , when I wrote conda info
C:\Users\Anish Saha>conda info

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "C:\Anaconda3\lib\site-packages\conda\exceptions.py", line 1074, in __call__
        return func(*args, **kwargs)
      File "C:\Anaconda3\lib\site-packages\conda\cli\main.py", line 84, in _main
        exit_code = do_call(args, p)
      File "C:\Anaconda3\lib\site-packages\conda\cli\conda_argparse.py", line 80, in do_call
        module = import_module(relative_mod, __name__.rsplit('.', 1)[0])
      File "C:\Anaconda3\lib\importlib\__init__.py", line 127, in import_module
        return _bootstrap._gcd_import(name[level:], package, level)
      File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
      File "<frozen importlib._bootstrap>", line 983, in _find_and_load
      File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
      File "<frozen importlib._bootstrap_external>", line 728, in exec_module
      File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
      File "C:\Anaconda3\lib\site-packages\conda\cli\main_info.py", line 19, in <module>
        from ..core.index import _supplement_index_with_system
      File "C:\Anaconda3\lib\site-packages\conda\core\index.py", line 9, in <module>
        from .package_cache_data import PackageCacheData
      File "C:\Anaconda3\lib\site-packages\conda\core\package_cache_data.py", line 15, in <module>
        from .path_actions import CacheUrlAction, ExtractPackageAction
      File "C:\Anaconda3\lib\site-packages\conda\core\path_actions.py", line 30, in <module>
        from ..gateways.connection.download import download
      File "C:\Anaconda3\lib\site-packages\conda\gateways\connection\__init__.py", line 21, in <module>
        from requests import ConnectionError, HTTPError, Session
      File "C:\Anaconda3\lib\site-packages\requests\__init__.py", line 112, in <module>
        from . import utils
      File "C:\Anaconda3\lib\site-packages\requests\utils.py", line 26, in <module>
        from ._internal_utils import to_native_string
      File "C:\Anaconda3\lib\site-packages\requests\_internal_utils.py", line 11, in <module>
        from .compat import is_py2, builtin_str, str
      File "C:\Anaconda3\lib\site-packages\requests\compat.py", line 60, in <module>
        from http.cookies import Morsel
      File "<frozen importlib._bootstrap>", line 983, in _find_and_load
      File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
      File "<frozen importlib._bootstrap_external>", line 724, in exec_module
      File "<frozen importlib._bootstrap_external>", line 859, in get_code
      File "<frozen importlib._bootstrap_external>", line 917, in get_data
    OSError: [Errno 9] Bad file descriptor

**Comment by radziuliss** [comment]
@Anish113 or someone, there is solution for this problem?
