### ISSUE TITLE
can not launch Rstudio in Anaconda3

### ISSUE THREAD

**Issue by goranad77** [ContinuumIO/anaconda-issues#11959]
< After installation of Rstudio in Anaconda3, can not launch it. Anaconda Navigator shows me tab with this message:

/home/goranad77/anaconda3/envs/renv/bin/rstudio: error while loading shared libraries: libffi.so.6: cannot open shared object file: No such file or directory

at the same time anaconda- navigator shows this text in terminal:

└──╼ $anaconda-navigator
Traceback (most recent call last):
  File "/home/goranad77/anaconda3/lib/python3.7/site-packages/anaconda_navigator/api/anaconda_api.py", line 455, in _conda_info_processed
    processed_info = self._process_conda_info(info)
  File "/home/goranad77/anaconda3/lib/python3.7/site-packages/anaconda_navigator/api/anaconda_api.py", line 570, in _process_conda_info
    for env_dir in info['envs_dirs']:
KeyError: 'envs_dirs'

I check the status of the package  libffi.so.6 in terminal:

└──╼ $locate libffi.so.6
locate: warning: database ‘/var/cache/locate/locatedb’ is more than 8 days old (actual age is 53.6 days)
/home/goranad77/anaconda3/lib/libffi.so.6
/home/goranad77/anaconda3/lib/libffi.so.6.0.4
/home/goranad77/anaconda3/pkgs/libffi-3.2.1-hd88cf55_4/lib/libffi.so.6
/home/goranad77/anaconda3/pkgs/libffi-3.2.1-hd88cf55_4/lib/libffi.so.6.0.4
What should I do?
I thought I followed instructions about installing Rstudio but something is wrong, Jypiter Notebooks runs well with python in Anaconda.

Thanks for opening an issue! Please fill out the following template in full.

A few things to keep in mind:

- This issue tracker is for issues with installing Anaconda or Miniconda or
with packages built by Anaconda, Inc. like Anaconda Navigator. It is also a
place to request packages or other enhancements of the Anaconda Distribution.

- For conda issues, you should open an issue at https://github.com/conda/conda/issues
- For conda-build issues, you should open an issue at https://github.com/conda/conda-build
- For an issue with a particular conda-forge package, you should open an issue
on the corresponding feedstock: https://github.com/conda-forge
-->

##### `conda info`

<details>

```
PASTE OUTPUT HERE:

```

</details>

##### `conda list --show-channel-urls`

<details>

```
PASTE OUTPUT HERE:

```

</details>

**Comment by goranad77** [comment]
After reinstalling R-studio by following Anaconda instructions I get this message when I launch it:
Unable to find an installation of R on the system (which R didn't return valid output); Unable to locate R binary by scanning standard locations
I did follow the instructions on this page:
https://docs.anaconda.com/anaconda/navigator/tutorials/create-r-environment/
OS Debian Parrot
anaconda3
