### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by DivyaSri-11** [ContinuumIO/anaconda-issues#11969]
## Main error
An unexpected error occurred on Navigator start-up<br>psutil.AccessDenied (pid=3816)
## Traceback
```
Traceback (most recent call last):
  File "C:\Users\ES\Anaconda3\lib\site-packages\psutil\_pswindows.py", line 620, in wrapper
    return fun(self, *args, **kwargs)
  File "C:\Users\ES\Anaconda3\lib\site-packages\psutil\_pswindows.py", line 690, in cmdline
    ret = cext.proc_cmdline(self.pid)
PermissionError: [WinError 5] Access is denied

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\ES\Anaconda3\lib\site-packages\anaconda_navigator\exceptions.py", line 75, in exception_handler
    return_value = func(*args, **kwargs)
  File "C:\Users\ES\Anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 108, in start_app
    if misc.load_pid() is None:  # A stale lock might be around
  File "C:\Users\ES\Anaconda3\lib\site-packages\anaconda_navigator\utils\misc.py", line 384, in load_pid
    cmds = process.cmdline()
  File "C:\Users\ES\Anaconda3\lib\site-packages\psutil\__init__.py", line 701, in cmdline
    return self._proc.cmdline()
  File "C:\Users\ES\Anaconda3\lib\site-packages\psutil\_pswindows.py", line 623, in wrapper
    raise AccessDenied(self.pid, self._name)
psutil.AccessDenied: psutil.AccessDenied (pid=3816)

```
## System information
```
python: 3.6.1
language: en_US
os: Windows;7;6.1.7601;AMD64;Intel64 Family 6 Model 69 Stepping 1, GenuineIntel
version: 1.6.2
platform: win-64
qt: 5.6.2
pyqt: 5.6.0
conda: 4.3.21
```

**Comment by lammiyad** [comment]
I couldn't launch my anaconda navigator on window . Please any help. here is the issue when I try to launch:                                        (base) C:\Users\Eba>anaconda-navigator
Traceback (most recent call last):
  File "C:\Users\Eba\anaconda\Scripts\anaconda-navigator-script.py", line 10, in <module>
    sys.exit(main())
  File "C:\Users\Eba\anaconda\lib\site-packages\anaconda_navigator\app\main.py", line 103, in main
    from anaconda_navigator.app.start import start_app
  File "C:\Users\Eba\anaconda\lib\site-packages\anaconda_navigator\app\start.py", line 34, in <module>
    from anaconda_navigator.widgets.main_window import MainWindow
  File "C:\Users\Eba\anaconda\lib\site-packages\anaconda_navigator\widgets\main_window.py", line 33, in <module>
    from anaconda_navigator.api.anaconda_api import AnacondaAPI
  File "C:\Users\Eba\anaconda\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 28, in <module>
    from anaconda_navigator.api.client_api import ClientAPI
  File "C:\Users\Eba\anaconda\lib\site-packages\anaconda_navigator\api\client_api.py", line 20, in <module>
    import binstar_client
  File "C:\Users\Eba\anaconda\lib\site-packages\binstar_client\__init__.py", line 5, in <module>
    import requests
  File "C:\Users\Eba\anaconda\lib\site-packages\requests\__init__.py", line 120, in <module>
    from . import utils
  File "C:\Users\Eba\anaconda\lib\site-packages\requests\utils.py", line 27, in <module>
    from ._internal_utils import to_native_string
  File "C:\Users\Eba\anaconda\lib\site-packages\requests\_internal_utils.py", line 11, in <module>
    from .compat import is_py2, builtin_str, str
  File "C:\Users\Eba\anaconda\lib\site-packages\requests\compat.py", line 61, in <module>
    from http.cookies import Morsel
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 779, in exec_module
  File "<frozen importlib._bootstrap_external>", line 915, in get_code
  File "<frozen importlib._bootstrap_external>", line 973, in get_data
OSError: [Errno 9] Bad file descriptor

(base) C:\Users\Eba>

**Comment by csoja** [comment]
@DivyaSri-11  Please see https://docs.anaconda.com/anaconda/navigator/troubleshooting/#access-denied-error
@lammiyad  Have you tried https://docs.anaconda.com/anaconda/navigator/troubleshooting/#navigator-error-on-start-up ?

**Comment by lammiyad** [comment]
Yes, I've tried it and it doesn't workout. Same error is coming for every options. Thank you

**Comment by lammiyad** [comment]
> @DivyaSri-11 Please see https://docs.anaconda.com/anaconda/navigator/troubleshooting/#access-denied-error
> @lammiyad Have you tried https://docs.anaconda.com/anaconda/navigator/troubleshooting/#navigator-error-on-start-up ?

Yes, I've tried it and it doesn't workout. Same error is coming for every options. Thank you
