### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by debkumar81** [ContinuumIO/anaconda-issues#11976]
### Actual Behavior

**Navigator Error**
An unexpected error occurred on Navigator start-up

**Report**
Please report this issue in the anaconda issue tracker

**Main Error**
'list' object has no attribute 'get'

**Traceback**
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\anaconda_navigator\exceptions.py", line 75, in exception_handler
    return_value = func(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 151, in start_app
    window = run_app(splash)
  File "C:\ProgramData\Anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 65, in run_app
    window = MainWindow(splash=splash, tab_project=False)
  File "C:\ProgramData\Anaconda3\lib\site-packages\anaconda_navigator\widgets\main_window.py", line 170, in __init__
    self.api = AnacondaAPI()
  File "C:\ProgramData\Anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 1525, in AnacondaAPI
    ANACONDA_API = _AnacondaAPI()
  File "C:\ProgramData\Anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 77, in __init__
    self._conda_api = CondaAPI()
  File "C:\ProgramData\Anaconda3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 1804, in CondaAPI
    CONDA_API = _CondaAPI()
  File "C:\ProgramData\Anaconda3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 371, in __init__
    self.set_conda_prefix(info=get_conda_info())
  File "C:\ProgramData\Anaconda3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 533, in set_conda_prefix
    self.ROOT_PREFIX = info.get('root_prefix')
AttributeError: 'list' object has no attribute 'get'

### Expected Behavior

Normal Anaconda to open

##### `conda info`

<details>

```
PASTE OUTPUT HERE:

```

</details>

##### `conda list --show-channel-urls`

<details>

```
PASTE OUTPUT HERE:

```

</details>

**Comment by csoja** [comment]
What version of conda and Anaconda Navigator are you using?  Can you update to the latest?
Latest version of Navigator: 1.9.12
Latest version of conda: 4.8.3

**Comment by debkumar81** [comment]
I downloaded the latest version from Anaconda homepage. Uninstalled previous versions that I had in my system
Surprisingly, if I do `conda list`, I am getting ` 'conda' is not recognized as an internal or external command, operable program or batch file`.

**Comment by csoja** [comment]
Are you getting that error from the Anaconda Prompt? Or the basic Command Prompt?

**Comment by debkumar81** [comment]
Anaconda Prompt. Here is what I get when I run them in both Powershell Prompt and Prompt.
![anacondapowershell](https://user-images.githubusercontent.com/9061241/89798854-b74a4b00-dafa-11ea-8316-a33f7e805ba1.png)
![anacondaprompt](https://user-images.githubusercontent.com/9061241/89798870-bc0eff00-dafa-11ea-9e54-1d9cc9e5fe35.png)

**Comment by debkumar81** [comment]
Not sure if you would be able to see the screen grabs.
