### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by muralidharanrl** [ContinuumIO/anaconda-issues#11982]
## Main error
Application <b>notebook</b> launch may have produced errors.
## Traceback
```
Traceback (most recent call last):
  File "C:\Users\Muralidharan\Anaconda3\Scripts\jupyter-notebook-script.py", line 3, in <module>
    import notebook.notebookapp
  File "C:\Users\Muralidharan\Anaconda3\lib\site-packages\notebook\notebookapp.py", line 74, in <module>
    from .services.kernels.kernelmanager import MappingKernelManager
  File "C:\Users\Muralidharan\Anaconda3\lib\site-packages\notebook\services\kernels\kernelmanager.py", line 16, in <module>
    from jupyter_client.multikernelmanager import MultiKernelManager
  File "C:\Users\Muralidharan\Anaconda3\lib\site-packages\jupyter_client\__init__.py", line 6, in <module>
    from .client import KernelClient
  File "C:\Users\Muralidharan\Anaconda3\lib\site-packages\jupyter_client\client.py", line 18, in <module>
    from .connect import ConnectionFileMixin
ImportError: cannot import name 'ConnectionFileMixin'

```
## System information
```
python: 3.6.1
language: en_US
os: Windows;10;10.0.18362;AMD64;Intel64 Family 6 Model 61 Stepping 4, GenuineIntel
version: 1.6.2
platform: win-64
qt: 5.6.2
pyqt: 5.6.0
conda: 4.3.21
```

**Comment by csoja** [comment]
You are using a very old version of conda and Anaconda Navigator - please update to the latest.
