### ISSUE TITLE
Root Prefix 

### ISSUE THREAD

**Issue by Saifri** [ContinuumIO/anaconda-issues#12042]
### Actual Behavior

I am getting Root Prefix error when trying to open Anaconda in my Mac . Need to mention that I already ran update command in my terminal. Still getting following error. 

Main Error

'root_prefix'
Traceback

Traceback (most recent call last):
  File "/Users/saifulmajumder/anaconda3/lib/python3.7/site-packages/anaconda_navigator/exceptions.py", line 75, in exception_handler
    return_value = func(*args, **kwargs)
  File "/Users/saifulmajumder/anaconda3/lib/python3.7/site-packages/anaconda_navigator/app/start.py", line 151, in start_app
    window = run_app(splash)
  File "/Users/saifulmajumder/anaconda3/lib/python3.7/site-packages/anaconda_navigator/app/start.py", line 65, in run_app
    window = MainWindow(splash=splash, tab_project=False)
  File "/Users/saifulmajumder/anaconda3/lib/python3.7/site-packages/anaconda_navigator/widgets/main_window.py", line 168, in __init__
    self.api = AnacondaAPI()
  File "/Users/saifulmajumder/anaconda3/lib/python3.7/site-packages/anaconda_navigator/api/anaconda_api.py", line 2337, in AnacondaAPI
    ANACONDA_API = _AnacondaAPI()
  File "/Users/saifulmajumder/anaconda3/lib/python3.7/site-packages/anaconda_navigator/api/anaconda_api.py", line 89, in __init__
    self._conda_api = CondaAPI()
  File "/Users/saifulmajumder/anaconda3/lib/python3.7/site-packages/anaconda_navigator/api/conda_api.py", line 1773, in CondaAPI
    CONDA_API = _CondaAPI()
  File "/Users/saifulmajumder/anaconda3/lib/python3.7/site-packages/anaconda_navigator/api/conda_api.py", line 350, in __init__
    self.set_conda_prefix(info=get_conda_info())
  File "/Users/saifulmajumder/anaconda3/lib/python3.7/site-packages/anaconda_navigator/api/conda_api.py", line 505, in set_conda_prefix
    self.ROOT_PREFIX = info['root_prefix']
KeyError: 'root_prefix'

##### `conda info`

<details>

```
PASTE OUTPUT HERE:

```

</details>

##### `conda list --show-channel-urls`

<details>

```
PASTE OUTPUT HERE:

```

</details>

**Comment by csoja** [comment]
Can you try the suggestion here? https://docs.anaconda.com/anaconda/navigator/troubleshooting/#navigator-error-on-start-up
