### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by ccpe1386** [ContinuumIO/anaconda-issues#12069]
### Actual Behavior

An unexpected error occurred on Navigator start-up

### Expected Behavior

Anaconda navigator should lunch properly

##### `conda info`

<details>

```
'bytes' object has no attribute 'get'

```

</details>

##### `conda list --show-channel-urls`

<details>

```
Traceback (most recent call last):
  File "C:\Intel\Anaconda\lib\site-packages\anaconda_navigator\exceptions.py", line 75, in exception_handler
    return_value = func(*args, **kwargs)
  File "C:\Intel\Anaconda\lib\site-packages\anaconda_navigator\app\start.py", line 151, in start_app
    window = run_app(splash)
  File "C:\Intel\Anaconda\lib\site-packages\anaconda_navigator\app\start.py", line 65, in run_app
    window = MainWindow(splash=splash, tab_project=False)
  File "C:\Intel\Anaconda\lib\site-packages\anaconda_navigator\widgets\main_window.py", line 170, in __init__
    self.api = AnacondaAPI()
  File "C:\Intel\Anaconda\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 1525, in AnacondaAPI
    ANACONDA_API = _AnacondaAPI()
  File "C:\Intel\Anaconda\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 77, in __init__
    self._conda_api = CondaAPI()
  File "C:\Intel\Anaconda\lib\site-packages\anaconda_navigator\api\conda_api.py", line 1804, in CondaAPI
    CONDA_API = _CondaAPI()
  File "C:\Intel\Anaconda\lib\site-packages\anaconda_navigator\api\conda_api.py", line 371, in __init__
    self.set_conda_prefix(info=get_conda_info())
  File "C:\Intel\Anaconda\lib\site-packages\anaconda_navigator\api\conda_api.py", line 533, in set_conda_prefix
    self.ROOT_PREFIX = info.get('root_prefix')
AttributeError: 'bytes' object has no attribute 'get'

```

</details>

**Comment by csoja** [comment]
Please update to the latest version of conda and Anaconda-Navigator.  The latest released version of Anaconda Navigator is v1.9.12.  The latest released version of conda is 4.8.4.
