### ISSUE TITLE
Jupyter notebook launch may have produced errors

### ISSUE THREAD

**Issue by DayaKaps** [ContinuumIO/anaconda-issues#12071]
After Installing Latest Anaconda Individual Edition, After starting Jupyter Lab, I am getting below errors

[E 13:25:16.109 LabApp] Exception while loading config file C:\Users\DK\.jupyter\jupyter_notebook_config.py
Traceback (most recent call last):
File "C:\Users\DK\anaconda3\lib\site-packages\traitlets\config\application.py", line 563, in _load_config_files
config = loader.load_config()
File "C:\Users\DK\anaconda3\lib\site-packages\traitlets\config\loader.py", line 457, in load_config
self._read_file_as_dict()
File "C:\Users\DK\anaconda3\lib\site-packages\traitlets\config\loader.py", line 489, in _read_file_as_dict
py3compat.execfile(conf_filename, namespace)
File "C:\Users\DK\anaconda3\lib\site-packages\ipython_genutils\py3compat.py", line 198, in execfile
exec(compiler(f.read(), fname, 'exec'), glob, loc)
File "C:\Users\DK\.jupyter\jupyter_notebook_config.py", line 266
c.NotebookApp.notebook_dir = "C:\Users\DK\Desktop\Everything Personal\PythonFullThrottle"
^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape

**Comment by DayaKaps** [comment]
Resolved by re-install
