### ISSUE TITLE
Couldn't open Jupyter, Spyder, Anaconda Navigator on Win10 x64 

### ISSUE THREAD

**Issue by meRscliche** [ContinuumIO/anaconda-issues#12082]
Couldn't open Jupyter, Spyder, Anaconda Navigator on Win10 x64 after installed Anaconda 2020.07
====
How I try to solve this issue, yet Spyder still doesn't work.
----

### (1) Issue

Today (2020/10/06) I opened my NB and found that I couldn't open Jupyter, Spyder, Anaconda anymore on my Win10 x64 NB. So weird. So I uninstalled it and install the latest version 2020.07.

### (2) Possible errors in this article：

1. After installed Anaconda, I couldn't open Spyder, Jupyter, and Anaconda Navigator
2. Entering some lines in Anaconda Prompt, and I saw "could not find or load the Qt platform plugin windows."
3. Warnings occured when insalling PyQt5(pyqt5):
ERROR: spyder 4.1.4 requires pyqtwebengine<5.13; python_version >= "3", which is not installed.
ERROR: spyder 4.1.4 has requirement pyqt5<5.13; python_version >= "3", but you'll have pyqt5 5.15.1 which is incompatible.

### (3) Solution
Open the Anaconda Prompt as a system administrator, then enter the following line in order:
````
conda update conda
conda update --all
````
````
conda remove QtPy PyQt5
pip install QtPy PyQt5
````
ERROR: spyder 4.1.4 requires pyqtwebengine<5.13; python_version >= "3", which is not installed.
ERROR: spyder 4.1.4 has requirement pyqt5<5.13; python_version >= "3", but you'll have pyqt5 5.15.1 which is incompatible.
````
conda update anaconda-navigator
anaconda-navigator --reset
conda update anaconda-client
conda update -f anaconda-client
````

Through the steps above, I could open Jupyter and Anaconda Navigator. As for Spyder, it doesn't work anymore. I really hope someone could tell me how to make my Spyder available  again.

**Comment by meRscliche** [comment]
Somehow I managed to solve it, but I _got to launch Jupyter and Spyder in Anaconda Navigator from now on_. Well, it's better than never launching Jupyter and Spyder.

(2) Launch the Anaconda Prompt as a system administrator, then enter the following line in order:
```
conda update conda
conda update --all
conda remove QtPy PyQt5
pip install QtPy PyQt5
```
ERROR: spyder 4.1.4 requires pyqtwebengine<5.13; python_version >= "3", which is not installed.
ERROR: spyder 4.1.4 has requirement pyqt5<5.13; python_version >= "3", but you'll have pyqt5 5.15.1 which is incompatible.
_The errors above are just warnings and won't stop the process._
```
conda update anaconda-navigator
anaconda-navigator --reset
conda update anaconda-client
conda update -f anaconda-client
```

**Comment by KrishnaRajule** [comment]
I had got the same Error:

> PythonQtError: No Qt bindings could be found

I followed this solution and now the anaconda-navigator works for me. Thank You

**Comment by meRscliche** [comment]
> I had got the same Error:
> 
> > PythonQtError: No Qt bindings could be found
> 
> I followed this solution and now the anaconda-navigator launches. Thank You

Glad to know that.

**Comment by sisika09** [comment]
I am new to this, and it doesn't launch even for me. How do I figure out if I have this Qtpython error as well.
I tried entering 
```
conda update conda
conda update --all 
```
but it said conda is not recognized as an internal or external command,
operable program or batch file.
please help me

**Comment by meRscliche** [comment]
> I am new to this, and it doesn't launch even for me. How do I figure out if I have this Qtpython error as well.
> I tried entering 
> ```
> conda update conda
> conda update --all 
> ```
> but it said conda is not recognized as an internal or external command,
> operable program or batch file.
> please help me
> 

I suggest you reinstall or install another version of Anaconda, cuz the command "conda" should have been in Anaconda once you installed any versions of Anaconda.

**Comment by sisika09** [comment]
I am able to open anaconda navigator now, thank you, but I still can't launch spyder(not even through anaconda navigator) what should I do ?

**Comment by meRscliche** [comment]
> I am able to open anaconda navigator now, thank you, but I still can't launch spyder(not even through anaconda navigator) what should I do ?

Glad to know that. Do the "conda" works now ? Have you run the codes above ?

**Comment by sisika09** [comment]
> Glad to know that. Does the "conda" work now ? Have you run the codes above ?
'conda' works now and I was able to open navigator as well as jupyter all thanks
 to you. But I am still not able to open spyder.You mentioned that you were able to open spyder from navigator, when I tried that it showed an error,
File "C:\anaconda\lib\site-packages\qtpy\QtWebEngineWidgets.py", line 22, in
from PyQt5.QtWebEngineWidgets import QWebEnginePage
ImportError: DLL load failed while importing QtWebEngineWidgets: The specified procedure could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "C:\anaconda\Scripts\spyder-script.py", line 10, in
sys.exit(main())
File "C:\anaconda\lib\site-packages\spyder\app\start.py", line 201, in main
from spyder.app import mainwindow
File "C:\anaconda\lib\site-packages\spyder\app\mainwindow.py", line 84, in
from qtpy import QtWebEngineWidgets # analysis:ignore
File "C:\anaconda\lib\site-packages\qtpy\QtWebEngineWidgets.py", line 26, in
from PyQt5.QtWebKitWidgets import QWebPage as QWebEnginePage
ModuleNotFoundError: No module named 'PyQt5.QtWebKitWidgets'



Did you also face this error ? if so what did you do ?
and thank you so much for your help.

**Comment by meRscliche** [comment]
> > Glad to know that. Does the "conda" work now ? Have you run the codes above ?
> > 'conda' works now and I was able to open navigator as well as jupyter all thanks
> > to you. But I am still not able to open spyder.You mentioned that you were able to open spyder from navigator, when I tried that it showed an error,
> > File "C:\anaconda\lib\site-packages\qtpy\QtWebEngineWidgets.py", line 22, in
> > from PyQt5.QtWebEngineWidgets import QWebEnginePage
> > ImportError: DLL load failed while importing QtWebEngineWidgets: The specified procedure could not be found.
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
> File "C:\anaconda\Scripts\spyder-script.py", line 10, in
> sys.exit(main())
> File "C:\anaconda\lib\site-packages\spyder\app\start.py", line 201, in main
> from spyder.app import mainwindow
> File "C:\anaconda\lib\site-packages\spyder\app\mainwindow.py", line 84, in
> from qtpy import QtWebEngineWidgets # analysis:ignore
> File "C:\anaconda\lib\site-packages\qtpy\QtWebEngineWidgets.py", line 26, in
> from PyQt5.QtWebKitWidgets import QWebPage as QWebEnginePage
> ModuleNotFoundError: No module named 'PyQt5.QtWebKitWidgets'
> 
> Did you also face this error ? if so what did you do ?
> and thank you so much for your help.

Try the codes in the following order: 
````
conda remove QtPy PyQt5
pip install QtPy PyQt5

conda update conda
conda update --all 

conda update anaconda-navigator
anaconda-navigator --reset
conda update anaconda-client
conda update -f anaconda-client
````

**Comment by sisika09** [comment]
> conda remove QtPy PyQt5
When I ran this code, it said,

Collecting package metadata (repodata.json): done
Solving environment: failed

PackagesNotFoundError: The following packages are missing from the target environment:
  - pyqt5
could this be the reason why it's not working ?

**Comment by meRscliche** [comment]
> > conda remove QtPy PyQt5
> 
> When I ran this code, it said,
> 
> Collecting package metadata (repodata.json): done
> Solving environment: failed
> 
> PackagesNotFoundError: The following packages are missing from the target environment:
>   - pyqt5
> could this be the reason why it's not working ?
> 

Ok. Just skip this line.
