### ISSUE TITLE
Conda create fails 

### ISSUE THREAD

**Issue by durack1** [ContinuumIO/anaconda-issues#1209]
The following error occurs when attempting to create an environment after installing anaconda 4.2.0 on OS X (10.11.6):
```
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Current conda install:

               platform : osx-64
          conda version : 4.2.9
       conda is private : False
      conda-env version : 4.2.9
    conda-build version : 2.0.2
         python version : 2.7.12.final.0
       requests version : 2.11.1
       root environment : /Users/durack1/anaconda2  (writable)
    default environment : /Users/durack1/anaconda2
       envs directories : /Users/durack1/anaconda2/envs
          package cache : /Users/durack1/anaconda2/pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/osx-64/
                          https://repo.continuum.io/pkgs/free/noarch/
                          https://repo.continuum.io/pkgs/pro/osx-64/
                          https://repo.continuum.io/pkgs/pro/noarch/
            config file : /Users/durack1/.condarc
           offline mode : False

`$ /Volumes/durack1ml/Users/durack1/anaconda2/bin/conda create -n uvcdat261 -c uvcdat uvcdat`

    Traceback (most recent call last):
      File "/Users/durack1/anaconda2/lib/python2.7/site-packages/conda/exceptions.py", line 473, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/Users/durack1/anaconda2/lib/python2.7/site-packages/conda/cli/main.py", line 144, in _main
        exit_code = args.func(args, p)
      File "/Users/durack1/anaconda2/lib/python2.7/site-packages/conda/cli/main_create.py", line 68, in execute
        install(args, parser, 'create')
      File "/Users/durack1/anaconda2/lib/python2.7/site-packages/conda/cli/install.py", line 420, in install
        raise CondaRuntimeError('RuntimeError: %s' % e)
      File "/Users/durack1/anaconda2/lib/python2.7/site-packages/conda/__init__.py", line 45, in __str__
        return text_type(self.message % self._kwargs)
    ValueError: unsupported format character 'D' (0x44) at index 215
```

**Comment by doutriaux1** [comment]
seems to work with conda version:
```
conda 4.2.11
```

**Comment by durack1** [comment]
@doutriaux1 I seem to have managed to get things working with `conda 4.2.11` so yes, it seems `4.2.9` was the problem, pity it was the default install from the available anaconda installer
