### ISSUE TITLE
Anaconda Navigator does not launch

### ISSUE THREAD

**Issue by rdp108** [ContinuumIO/anaconda-issues#12102]
### Actual Behavior

When I attempt to launch anaconda navigator from command line, I receive the following error message: 
C:\Users\user\anaconda3\Scripts> anaconda-navigator
Traceback (most recent call last):
  File "C:\Users\user\anaconda3\lib\site-packages\qtpy\__init__.py", line 204, in <module>
    from PySide import __version__ as PYSIDE_VERSION  # analysis:ignore
ModuleNotFoundError: No module named 'PySide'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\user\anaconda3\Scripts\anaconda-navigator-script.py", line 6, in <module>
    from anaconda_navigator.app.main import main
  File "C:\Users\user\anaconda3\lib\site-packages\anaconda_navigator\app\main.py", line 22, in <module>
    from anaconda_navigator.utils.conda import is_conda_available
  File "C:\Users\user\anaconda3\lib\site-packages\anaconda_navigator\utils\__init__.py", line 15, in <module>
    from qtpy.QtGui import QIcon
  File "C:\Users\user\anaconda3\lib\site-packages\qtpy\__init__.py", line 210, in <module>
    raise PythonQtError('No Qt bindings could be found')
qtpy.PythonQtError: No Qt bindings could be found

### Expected Behavior

Anaconda Navigator should launch fully once the command line prompt is entered. 

### Steps to Reproduce

I ran the following commands in command line: 
conda update conda
conda update anaconda-navigator
conda update spyder

##### Anaconda or Miniconda version:
Anaconda3 2020.07

##### Operating System:
Windows 10
##### `conda info`

<details>

```
  active environment : None
       user config file : C:\Users\user\.condarc
 populated config files : C:\Users\user\.condarc
          conda version : 4.9.0
    conda-build version : 3.20.3
         python version : 3.8.5.final.0
       virtual packages : __win=0=0
                          __archspec=1=x86_64
       base environment : C:\Users\user\anaconda3  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/win-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\Users\user\anaconda3\pkgs
                          C:\Users\user\.conda\pkgs
                          C:\Users\user\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\user\anaconda3\envs
                          C:\Users\user\.conda\envs
                          C:\Users\user\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.9.0 requests/2.24.0 CPython/3.8.5 Windows/10 Windows/10.0.19041
          administrator : False
             netrc file : None
           offline mode : False

```

</details>

##### `conda list --show-channel-urls`

<details>

```
# Name                    Version                   Build  Channel
_anaconda_depends         2020.07                  py38_0
_ipyw_jlab_nb_ext_conf    0.1.0                    py38_0
alabaster                 0.7.12                     py_0    conda-forge
anaconda                  custom                   py38_1
anaconda-client           1.7.2                      py_0    conda-forge
anaconda-navigator        1.9.12                   py38_0
anaconda-project          0.8.3                      py_0    conda-forge
argh                      0.26.2          pyh9f0ad1d_1002    conda-forge
argon2-cffi               20.1.0           py38h1e8a9f7_2    conda-forge
asn1crypto                1.4.0              pyh9f0ad1d_0    conda-forge
astroid                   2.4.2            py38h32f6830_1    conda-forge
astropy                   4.0.3            py38h1e8a9f7_0    conda-forge
async_generator           1.10                       py_0    conda-forge
atomicwrites              1.4.0              pyh9f0ad1d_0    conda-forge
attrs                     20.2.0             pyh9f0ad1d_0    conda-forge
autopep8                  1.5.4              pyh9f0ad1d_0    conda-forge
babel                     2.8.0                      py_0    conda-forge
backcall                  0.2.0              pyh9f0ad1d_0    conda-forge
backports                 1.0                        py_2    conda-forge
backports.functools_lru_cache 1.6.1                      py_0    conda-forge
backports.shutil_get_terminal_size 1.0.0                      py_3    conda-forge
backports.tempfile        1.0                        py_0    conda-forge
backports.weakref         1.0.post1       py38h32f6830_1002    conda-forge
bcrypt                    3.2.0            py38h1e8a9f7_1    conda-forge
beautifulsoup4            4.9.3              pyhb0f4dca_0    conda-forge
bitarray                  1.6.0            py38h1e8a9f7_0    conda-forge
bkcharts                  0.2                      py38_0
blas                      1.0                         mkl
bleach                    3.2.1              pyh9f0ad1d_0    conda-forge
blosc                     1.20.1               ha925a31_0    conda-forge
bokeh                     2.2.2            py38h32f6830_0    conda-forge
boto                      2.49.0                     py_0    conda-forge
bottleneck                1.3.2            py38h1e00858_2    conda-forge
brotli                    1.0.9                ha925a31_2    conda-forge
brotlipy                  0.7.0           py38hab1e662_1001    conda-forge
bzip2                     1.0.8                he774522_3    conda-forge
ca-certificates           2020.6.20            hecda079_0    conda-forge
certifi                   2020.6.20        py38h9bdc248_2    conda-forge
cffi                      1.14.3           py38h0e640b1_1    conda-forge
chardet                   3.0.4           py38h9bdc248_1008    conda-forge
charls                    2.1.0                h33f27b4_2    conda-forge
click                     7.1.2              pyh9f0ad1d_0    conda-forge
cloudpickle               1.6.0                      py_0    conda-forge
clyent                    1.2.2                      py_1    conda-forge
colorama                  0.4.4              pyh9f0ad1d_0    conda-forge
comtypes                  1.1.7           py38h32f6830_1002    conda-forge
conda                     4.9.0            py38h9bdc248_1    conda-forge
conda-build               3.20.3                   py38_0
conda-env                 2.6.0                         1
conda-package-handling    1.7.2            py38h8934438_0    conda-forge
conda-verify              3.4.2                      py_1
console_shortcut          0.1.1                         4
contextlib2               0.6.0.post1                py_0    conda-forge
cryptography              3.1.1            py38h0e640b1_1    conda-forge
curl                      7.71.1               h4b64cdc_8    conda-forge
cycler                    0.10.0                     py_2    conda-forge
cython                    0.29.21          py38h4b9bc1a_1    conda-forge
cytoolz                   0.11.0           py38h1e8a9f7_1    conda-forge
dask                      2.30.0                     py_0    conda-forge
dask-core                 2.30.0                     py_0    conda-forge
decorator                 4.4.2                      py_0    conda-forge
defusedxml                0.6.0                      py_0    conda-forge
diff-match-patch          20200713           pyh9f0ad1d_0    conda-forge
distributed               2.30.0           py38h32f6830_1    conda-forge
docutils                  0.16             py38h9bdc248_2    conda-forge
entrypoints               0.3             py38h32f6830_1002    conda-forge
et_xmlfile                1.0.1                   py_1001    conda-forge
fastcache                 1.1.0            py38h1e8a9f7_2    conda-forge
filelock                  3.0.12             pyh9f0ad1d_0    conda-forge
flake8                    3.8.4                      py_0    conda-forge
flask                     1.1.2              pyh9f0ad1d_0    conda-forge
freetype                  2.10.3               hd328e21_0    conda-forge
fsspec                    0.8.4                      py_0    conda-forge
future                    0.18.2           py38h32f6830_2    conda-forge
get_terminal_size         1.0.0                h38e98db_0
gevent                    20.9.0           py38h1e8a9f7_1    conda-forge
giflib                    5.2.1                h2fa13f4_2    conda-forge
glob2                     0.7                        py_0    conda-forge
gmpy2                     2.1.0b1          py38h2c62616_1    conda-forge
greenlet                  0.4.17           py38h1e8a9f7_1    conda-forge
h5py                      2.10.0          nompi_py38h6053941_105    conda-forge
hdf5                      1.10.6          nompi_h89124ea_1110    conda-forge
heapdict                  1.0.1                      py_0    conda-forge
html5lib                  1.1                pyh9f0ad1d_0    conda-forge
icc_rt                    2019.0.0             h0cc432a_1
icu                       67.1                 h33f27b4_0    conda-forge
idna                      2.10               pyh9f0ad1d_0    conda-forge
imagecodecs               2020.5.30        py38h44615b6_4    conda-forge
imageio                   2.9.0                      py_0    conda-forge
imagesize                 1.2.0                      py_0    conda-forge
importlib-metadata        2.0.0                      py_1    conda-forge
importlib_metadata        2.0.0                         1    conda-forge
iniconfig                 1.1.0              pyh9f0ad1d_0    conda-forge
intel-openmp              2020.2                      254
intervaltree              3.0.2                      py_0    conda-forge
ipykernel                 5.3.4            py38h7b7c402_1    conda-forge
ipython                   7.18.1           py38h1cdfbd6_1    conda-forge
ipython_genutils          0.2.0                      py_1    conda-forge
ipywidgets                7.5.1              pyh9f0ad1d_1    conda-forge
isort                     5.6.4                      py_0    conda-forge
itsdangerous              1.1.0                      py_0    conda-forge
jdcal                     1.4.1                      py_0    conda-forge
jedi                      0.17.1           py38h32f6830_0    conda-forge
jinja2                    2.11.2             pyh9f0ad1d_0    conda-forge
joblib                    0.17.0                     py_0    conda-forge
jpeg                      9d                   he774522_0    conda-forge
json5                     0.9.5              pyh9f0ad1d_0    conda-forge
jsonschema                3.2.0                      py_2    conda-forge
jupyter                   1.0.0                    py38_7
jupyter_client            6.1.7                      py_0    conda-forge
jupyter_console           6.2.0                      py_0    conda-forge
jupyter_core              4.6.3            py38h32f6830_2    conda-forge
jupyterlab                2.2.8                      py_0    conda-forge
jupyterlab_pygments       0.1.2              pyh9f0ad1d_0    conda-forge
jupyterlab_server         1.2.0                      py_0    conda-forge
jxrlib                    1.1                  hfa6e2cd_2    conda-forge
keyring                   21.4.0           py38h32f6830_2    conda-forge
kiwisolver                1.2.0            py38h95a2b95_1    conda-forge
krb5                      1.17.1               hc04afaa_3    conda-forge
lazy-object-proxy         1.4.3            py38h1e8a9f7_2    conda-forge
lcms2                     2.11                 he1115b7_0    conda-forge
lerc                      2.2                  ha925a31_0    conda-forge
libaec                    1.0.4                he025d50_1    conda-forge
libarchive                3.4.3                h793d221_0    conda-forge
libclang                  10.0.1          default_hf44288c_1    conda-forge
libcurl                   7.71.1               h4b64cdc_8    conda-forge
libiconv                  1.16                 he774522_0    conda-forge
liblief                   0.10.1               ha925a31_2    conda-forge
libllvm9                  9.0.1                hde8ddfe_1    conda-forge
libpng                    1.6.37               ha81a0f5_2    conda-forge
libsodium                 1.0.18               h62dcd97_1    conda-forge
libspatialindex           1.9.3                he025d50_3    conda-forge
libssh2                   1.9.0                hb06d900_5    conda-forge
libtiff                   4.1.0                h885aae3_6    conda-forge
libwebp-base              1.1.0                hfa6e2cd_3    conda-forge
libxml2                   2.9.10               h1006b36_2    conda-forge
libxslt                   1.1.33               h579f668_1    conda-forge
libzopfli                 1.0.3                ha925a31_0    conda-forge
llvmlite                  0.34.0           py38h74e2f34_2    conda-forge
locket                    0.2.0                      py_2    conda-forge
lxml                      4.6.1            py38he3d0fc9_0    conda-forge
lz4-c                     1.9.2                h62dcd97_2    conda-forge
lzo                       2.10              he774522_1000    conda-forge
m2w64-gcc-libgfortran     5.3.0                         6
m2w64-gcc-libs            5.3.0                         7
m2w64-gcc-libs-core       5.3.0                         7
m2w64-gmp                 6.1.0                         2
m2w64-libwinpthread-git   5.0.0.4634.697f757               2
markupsafe                1.1.1            py38hab1e662_2    conda-forge
matplotlib                3.3.2            py38h32f6830_1    conda-forge
matplotlib-base           3.3.2            py38h6584adb_1    conda-forge
mccabe                    0.6.1                      py_1    conda-forge
menuinst                  1.4.16           py38he774522_1
mistune                   0.8.4           py38h1e8a9f7_1002    conda-forge
mkl                       2020.2                      256
mkl-service               2.3.0            py38h1e8a9f7_1    conda-forge
mkl_fft                   1.2.0            py38h1e00858_1    conda-forge
mkl_random                1.2.0            py38h251f6bf_1    conda-forge
mock                      4.0.2            py38h32f6830_1    conda-forge
more-itertools            8.5.0                      py_0    conda-forge
mpc                       1.1.0             h7edee0f_1009    conda-forge
mpfr                      4.0.2                h62dcd97_1    conda-forge
mpir                      3.0.0             he025d50_1002    conda-forge
mpmath                    1.1.0                      py_0    conda-forge
msgpack-python            1.0.0            py38h95a2b95_2    conda-forge
msys2-conda-epoch         20160418                      1
multipledispatch          0.6.0                      py_0    conda-forge
navigator-updater         0.2.1                    py38_0
nbclient                  0.5.1                      py_0    conda-forge
nbconvert                 6.0.7            py38h32f6830_1    conda-forge
nbformat                  5.0.8                      py_0    conda-forge
nest-asyncio              1.4.1                      py_0    conda-forge
networkx                  2.5                        py_0    conda-forge
nltk                      3.4.4                      py_0    conda-forge
nose                      1.3.7                   py_1006    conda-forge
notebook                  6.1.4            py38h32f6830_1    conda-forge
numba                     0.51.2           py38h251f6bf_0    conda-forge
numexpr                   2.7.1            py38h251f6bf_3    conda-forge
numpy                     1.19.1           py38h5510c5b_0
numpy-base                1.19.1           py38ha3acd2a_0
numpydoc                  1.1.0                      py_1    conda-forge
olefile                   0.46               pyh9f0ad1d_1    conda-forge
openjpeg                  2.3.1                h57dd2e7_3    conda-forge
openpyxl                  3.0.5                      py_0    conda-forge
openssl                   1.1.1h               he774522_0    conda-forge
packaging                 20.4               pyh9f0ad1d_0    conda-forge
pandas                    1.1.3            py38h251f6bf_2    conda-forge
pandoc                    2.11.0.2             hf4a77e7_0    conda-forge
pandocfilters             1.4.2                      py_1    conda-forge
paramiko                  2.7.2              pyh9f0ad1d_0    conda-forge
parso                     0.7.0                      py_0
partd                     1.1.0                      py_0    conda-forge
path                      15.0.0           py38h32f6830_1    conda-forge
path.py                   12.5.0                        0    conda-forge
pathlib2                  2.3.5            py38h32f6830_1    conda-forge
pathtools                 0.1.2                      py_1    conda-forge
patsy                     0.5.1                      py_0    conda-forge
pep8                      1.7.1                      py_0    conda-forge
pexpect                   4.8.0              pyh9f0ad1d_2    conda-forge
pickleshare               0.7.5                   py_1003    conda-forge
pillow                    8.0.0            py38h1d4d63c_0    conda-forge
pip                       20.2.4                     py_0    conda-forge
pkginfo                   1.5.0.1                    py_0    conda-forge
pluggy                    0.13.1           py38h32f6830_3    conda-forge
ply                       3.11                       py_1    conda-forge
powershell_shortcut       0.0.1                         3
prometheus_client         0.8.0              pyh9f0ad1d_0    conda-forge
prompt-toolkit            3.0.8                      py_0    conda-forge
prompt_toolkit            3.0.8                         0    conda-forge
psutil                    5.7.2            py38hab1e662_1    conda-forge
ptyprocess                0.6.0                   py_1001    conda-forge
py                        1.9.0              pyh9f0ad1d_0    conda-forge
py-lief                   0.10.1           py38h4b9bc1a_2    conda-forge
pycodestyle               2.6.0              pyh9f0ad1d_0    conda-forge
pycosat                   0.6.3           py38hab1e662_1005    conda-forge
pycparser                 2.20               pyh9f0ad1d_2    conda-forge
pycurl                    7.43.0.5         py38h6be4be5_3    conda-forge
pydocstyle                5.1.1                      py_0    conda-forge
pyflakes                  2.2.0              pyh9f0ad1d_0    conda-forge
pygments                  2.7.1                      py_0    conda-forge
pylint                    2.6.0            py38h32f6830_1    conda-forge
pynacl                    1.4.0            py38hd4486f3_2    conda-forge
pyodbc                    4.0.30           py38h7ae7562_1    conda-forge
pyopenssl                 19.1.0                     py_1    conda-forge
pyparsing                 2.4.7              pyh9f0ad1d_0    conda-forge
pyqt                      5.12.3           py38h7ae7562_4    conda-forge
pyqt5-sip                 4.19.18                  pypi_0    pypi
pyqtchart                 5.12                     pypi_0    pypi
pyqtwebengine             5.12.1                   pypi_0    pypi
pyreadline                2.1             py38h32f6830_1002    conda-forge
pyrsistent                0.17.3           py38h1e8a9f7_1    conda-forge
pyside2                   5.15.1                   pypi_0    pypi
pysocks                   1.7.1            py38h9bdc248_2    conda-forge
pytables                  3.6.1            py38hd2a2a0e_2    conda-forge
pytest                    6.1.1            py38h32f6830_1    conda-forge
python                    3.8.5                h5fd99cc_1
python-dateutil           2.8.1                      py_0    conda-forge
python-jsonrpc-server     0.4.0              pyh9f0ad1d_0    conda-forge
python-language-server    0.35.1                     py_0    conda-forge
python-libarchive-c       2.9              py38h9bdc248_2    conda-forge
python_abi                3.8                      1_cp38    conda-forge
pytz                      2020.1             pyh9f0ad1d_0    conda-forge
pywavelets                1.1.1            py38h1e00858_3    conda-forge
pywin32                   228              py38h1e8a9f7_0    conda-forge
pywin32-ctypes            0.2.0           py38h32f6830_1002    conda-forge
pywinpty                  0.5.7            py38h32f6830_1    conda-forge
pyyaml                    5.3.1            py38hab1e662_1    conda-forge
pyzmq                     19.0.2           py38h77b9d75_2    conda-forge
qdarkstyle                2.8.1              pyh9f0ad1d_1    conda-forge
qt                        5.12.9               hb2cf2c5_0    conda-forge
qtawesome                 1.0.1              pyh9f0ad1d_0    conda-forge
qtconsole                 4.7.7              pyh9f0ad1d_0    conda-forge
qtpy                      1.9.0                      py_0    conda-forge
regex                     2020.10.15       py38h1e8a9f7_0    conda-forge
requests                  2.24.0             pyh9f0ad1d_0    conda-forge
rope                      0.18.0             pyh9f0ad1d_0    conda-forge
rtree                     0.9.4            py38h7ad75cc_1    conda-forge
ruamel_yaml               0.15.80         py38hab1e662_1003    conda-forge
scikit-image              0.17.2           py38h251f6bf_2    conda-forge
scikit-learn              0.23.2           py38h47e9c7a_0
scipy                     1.5.0            py38h9439919_0
seaborn                   0.11.0                        0    conda-forge
seaborn-base              0.11.0                     py_0    conda-forge
send2trash                1.5.0                      py_0    conda-forge
setuptools                49.6.0           py38h9bdc248_2    conda-forge
shiboken2                 5.15.1                   pypi_0    pypi
simplegeneric             0.8.1                      py_1    conda-forge
singledispatch            3.4.0.3         pyh9f0ad1d_1001    conda-forge
sip                       4.19.24          py38h7ae7562_2    conda-forge
six                       1.15.0             pyh9f0ad1d_0    conda-forge
snappy                    1.1.8                ha925a31_3    conda-forge
snowballstemmer           2.0.0                      py_0    conda-forge
sortedcollections         1.2.1              pyh9f0ad1d_0    conda-forge
sortedcontainers          2.2.2              pyh9f0ad1d_0    conda-forge
soupsieve                 2.0.1                      py_1    conda-forge
sphinx                    3.2.1                      py_0    conda-forge
sphinxcontrib             1.0                      py38_1
sphinxcontrib-applehelp   1.0.2                      py_0    conda-forge
sphinxcontrib-devhelp     1.0.2                      py_0    conda-forge
sphinxcontrib-htmlhelp    1.0.3                      py_0    conda-forge
sphinxcontrib-jsmath      1.0.1                      py_0    conda-forge
sphinxcontrib-qthelp      1.0.3                      py_0    conda-forge
sphinxcontrib-serializinghtml 1.1.4                      py_0    conda-forge
sphinxcontrib-websupport  1.2.4              pyh9f0ad1d_0    conda-forge
spyder                    4.1.5            py38h32f6830_0    conda-forge
spyder-kernels            1.9.4            py38h32f6830_0    conda-forge
sqlalchemy                1.3.20           py38h1e8a9f7_0    conda-forge
sqlite                    3.33.0               he774522_1    conda-forge
statsmodels               0.12.0           py38h1e00858_1    conda-forge
sympy                     1.6.2            py38h32f6830_1    conda-forge
tbb                       2020.1               he980bc4_0    conda-forge
tblib                     1.6.0                      py_0    conda-forge
terminado                 0.9.1            py38h32f6830_1    conda-forge
testpath                  0.4.4                      py_0    conda-forge
threadpoolctl             2.1.0              pyh5ca1d4c_0    conda-forge
tifffile                  2020.10.1                  py_0    conda-forge
tk                        8.6.10               he774522_1    conda-forge
toml                      0.10.1             pyh9f0ad1d_0    conda-forge
toolz                     0.11.1                     py_0    conda-forge
tornado                   6.0.4            py38h1e8a9f7_2    conda-forge
tqdm                      4.50.2             pyh9f0ad1d_0    conda-forge
traitlets                 5.0.5                      py_0    conda-forge
typing_extensions         3.7.4.3                    py_0    conda-forge
ujson                     4.0.1            py38h7ae7562_1    conda-forge
unicodecsv                0.14.1                     py_1    conda-forge
urllib3                   1.25.10                    py_0    conda-forge
vc                        14.1                 h869be7e_1    conda-forge
vs2015_runtime            14.16.27012          h30e32a0_2    conda-forge
watchdog                  0.10.3           py38h32f6830_2    conda-forge
wcwidth                   0.2.5              pyh9f0ad1d_2    conda-forge
webencodings              0.5.1                      py_1    conda-forge
werkzeug                  1.0.1              pyh9f0ad1d_0    conda-forge
wheel                     0.35.1             pyh9f0ad1d_0    conda-forge
widgetsnbextension        3.5.1              pyh9f0ad1d_3    conda-forge
win_inet_pton             1.1.0            py38h32f6830_1    conda-forge
win_unicode_console       0.5                   py38_1000    conda-forge
wincertstore              0.2             py38h32f6830_1005    conda-forge
winpty                    0.4.3                         4    conda-forge
wrapt                     1.11.2           py38h1e8a9f7_1    conda-forge
xlrd                      1.2.0              pyh9f0ad1d_1    conda-forge
xlsxwriter                1.3.7              pyh9f0ad1d_0    conda-forge
xlwings                   0.20.8           py38h32f6830_0    conda-forge
xlwt                      1.3.0                      py_1    conda-forge
xmltodict                 0.12.0                     py_0    conda-forge
xz                        5.2.5                h62dcd97_1    conda-forge
yaml                      0.2.5                he774522_0    conda-forge
yapf                      0.30.0             pyh9f0ad1d_0    conda-forge
zeromq                    4.3.2                ha925a31_4    conda-forge
zfp                       0.5.5                ha925a31_4    conda-forge
zict                      2.0.0                      py_0    conda-forge
zipp                      3.3.1                      py_0    conda-forge
zlib                      1.2.11            h62dcd97_1010    conda-forge
zope                      1.0                      py38_1
zope.event                4.5.0              pyh9f0ad1d_0    conda-forge
zope.interface            5.1.2            py38h1e8a9f7_1    conda-forge
zstd                      1.4.5                h1f3a1b7_2    conda-forge


```

</details>

**Comment by rdp108** [comment]
Update: I am now running into the following error message: 
(base) C:\Users\user> anaconda-navigator
Traceback (most recent call last):
  File "C:\Users\user\miniconda3\lib\site-packages\anaconda_navigator\widgets\main_window.py", line 550, in setup
    self.post_setup(conda_data=conda_data)
  File "C:\Users\user\miniconda3\lib\site-packages\anaconda_navigator\widgets\main_window.py", line 587, in post_setup
    self.tab_home.setup(conda_data)
  File "C:\Users\user\miniconda3\lib\site-packages\anaconda_navigator\widgets\tabs\home.py", line 170, in setup
    self.set_environments(environments)
  File "C:\Users\user\miniconda3\lib\site-packages\anaconda_navigator\widgets\tabs\home.py", line 177, in set_environments
    self.combo.currentIndexChanged.disconnect()
RuntimeError: Failed to disconnect signal currentIndexChanged(int).

**Comment by csoja** [comment]
Looking at your environment, you mainly have packages from conda-forge, and quite a few from pypi as well.  Though there is generally good compatibility between defaults channels and conda-forge, this is not always the case.  Things are often even less compatible when you start pulling in packages for PyPI.  Navigator depends on the following packages: anaconda-client chardet pillow psutil pyqt python pyyaml  qtpy  requests setuptools xmltodict navigator-updater.  (And some of these packages depend on others - most notably Qt which looks like was causing your original issues.)  Also, other applications installed on your system can also create conflicts/issues - if say your path has files Navigator is looking for earlier in the list - but those were from other applications and perhaps not the right versions/builds that Navigator actually needs.

What changed between your initial error report, and your updated error report?
Can you create a new environment with just Anaconda-Navigator installed into it with only the default channels in your channel list? Do you see the same error with that environment?
