### ISSUE TITLE
Navigator wont start

### ISSUE THREAD

**Issue by 007tracy** [ContinuumIO/anaconda-issues#12111]
### Actual Behavior

Navigator won't start

##### `conda info`

<details>

```
PASTE OUTPUT HERE:

```

</details>

##### `conda list --show-channel-urls`

<details>

Main Error
'bytes' object has no attribute 'get'
Traceback
Traceback (most recent call last):
  File "C:\Users\vp\anaconda37\lib\site-packages\anaconda_navigator\exceptions.py", line 75, in exception_handler
    return_value = func(*args, **kwargs)
  File "C:\Users\vp\anaconda37\lib\site-packages\anaconda_navigator\app\start.py", line 151, in start_app
    window = run_app(splash)
  File "C:\Users\vp\anaconda37\lib\site-packages\anaconda_navigator\app\start.py", line 65, in run_app
    window = MainWindow(splash=splash, tab_project=False)
  File "C:\Users\vp\anaconda37\lib\site-packages\anaconda_navigator\widgets\main_window.py", line 170, in __init__
    self.api = AnacondaAPI()
  File "C:\Users\vp\anaconda37\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 1525, in AnacondaAPI
    ANACONDA_API = _AnacondaAPI()
  File "C:\Users\vp\anaconda37\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 77, in __init__
    self._conda_api = CondaAPI()
  File "C:\Users\vp\anaconda37\lib\site-packages\anaconda_navigator\api\conda_api.py", line 1804, in CondaAPI
    CONDA_API = _CondaAPI()
  File "C:\Users\vp\anaconda37\lib\site-packages\anaconda_navigator\api\conda_api.py", line 371, in __init__
    self.set_conda_prefix(info=get_conda_info())
  File "C:\Users\vp\anaconda37\lib\site-packages\anaconda_navigator\api\conda_api.py", line 533, in set_conda_prefix
    self.ROOT_PREFIX = info.get('root_prefix')
AttributeError: 'bytes' object has no attribute 'get```
PASTE OUTPUT HERE:

```

</details>

**Comment by csoja** [comment]
The information requested in the bug report template is critical to being able to provide any pointed on how to fix the issue. 
With the above, I can only direct you to the troubleshooting page (https://docs.anaconda.com/anaconda/navigator/troubleshooting/#troubleshooting) , and alert you that there are new versions of conda and Anaconda-Navigator (v1.10.0) that have been released in the last week.  You'll need to use the Anaconda Prompt to update them: _conda update conda_   and _conda update anaconda-navigator_
