### ISSUE TITLE
Unable to import tensorflow

### ISSUE THREAD

**Issue by wggbullet** [ContinuumIO/anaconda-issues#12113]
### Actual Behavior

After successfully install tensorflow on my Mac, the import tensorflow fails.
Installation: pip install tensorflow

### Expected Behavior

base) [deeplearning]$ python -c "import tensorflow as tf;print(tf.reduce_sum(tf.random.normal([1000, 1000])))"
Traceback (most recent call last):
File "/Users/username/anaconda3/lib/python3.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 64, in
from tensorflow.python._pywrap_tensorflow_internal import *
ImportError: dlopen(/Users/username/anaconda3/lib/python3.7/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so, 6): Symbol not found: _SecKeyCopyExternalRepresentation
Referenced from: /Users/username/anaconda3/lib/python3.7/site-packages/tensorflow/python/../libtensorflow_framework.2.dylib
Expected in: /System/Library/Frameworks/Security.framework/Versions/A/Security
in /Users/username/anaconda3/lib/python3.7/site-packages/tensorflow/python/../libtensorflow_framework.2.dylib

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "", line 1, in
File "/Users/username/anaconda3/lib/python3.7/site-packages/tensorflow/init.py", line 41, in
from tensorflow.python.tools import module_util as _module_util
File "/Users/username/anaconda3/lib/python3.7/site-packages/tensorflow/python/init.py", line 40, in
from tensorflow.python.eager import context
File "/Users/username/anaconda3/lib/python3.7/site-packages/tensorflow/python/eager/context.py", line 35, in
from tensorflow.python import pywrap_tfe
File "/Users/username/anaconda3/lib/python3.7/site-packages/tensorflow/python/pywrap_tfe.py", line 28, in
from tensorflow.python import pywrap_tensorflow
File "/Users/username/anaconda3/lib/python3.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 83, in
raise ImportError(msg)
ImportError: Traceback (most recent call last):
File "/Users/username/anaconda3/lib/python3.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 64, in
from tensorflow.python._pywrap_tensorflow_internal import *
ImportError: dlopen(/Users/username/anaconda3/lib/python3.7/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so, 6): Symbol not found: _SecKeyCopyExternalRepresentation
Referenced from: /Users/username/anaconda3/lib/python3.7/site-packages/tensorflow/python/../libtensorflow_framework.2.dylib
Expected in: /System/Library/Frameworks/Security.framework/Versions/A/Security
in /Users/username/anaconda3/lib/python3.7/site-packages/tensorflow/python/../libtensorflow_framework.2.dylib

Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions. Include the entire stack trace
above this error message when asking for help.
(base) [deeplearning]$

##### `conda info`

<details>

```
PASTE OUTPUT HERE:

```

</details>

##### `conda list --show-channel-urls`

<details>

```
PASTE OUTPUT HERE:
base) [deeplearning]$ python -c "import tensorflow as tf;print(tf.reduce_sum(tf.random.normal([1000, 1000])))"
Traceback (most recent call last):
File "/Users/username/anaconda3/lib/python3.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 64, in
from tensorflow.python._pywrap_tensorflow_internal import *
ImportError: dlopen(/Users/username/anaconda3/lib/python3.7/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so, 6): Symbol not found: _SecKeyCopyExternalRepresentation
Referenced from: /Users/username/anaconda3/lib/python3.7/site-packages/tensorflow/python/../libtensorflow_framework.2.dylib
Expected in: /System/Library/Frameworks/Security.framework/Versions/A/Security
in /Users/username/anaconda3/lib/python3.7/site-packages/tensorflow/python/../libtensorflow_framework.2.dylib

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "", line 1, in
File "/Users/username/anaconda3/lib/python3.7/site-packages/tensorflow/init.py", line 41, in
from tensorflow.python.tools import module_util as _module_util
File "/Users/username/anaconda3/lib/python3.7/site-packages/tensorflow/python/init.py", line 40, in
from tensorflow.python.eager import context
File "/Users/username/anaconda3/lib/python3.7/site-packages/tensorflow/python/eager/context.py", line 35, in
from tensorflow.python import pywrap_tfe
File "/Users/username/anaconda3/lib/python3.7/site-packages/tensorflow/python/pywrap_tfe.py", line 28, in
from tensorflow.python import pywrap_tensorflow
File "/Users/username/anaconda3/lib/python3.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 83, in
raise ImportError(msg)
ImportError: Traceback (most recent call last):
File "/Users/username/anaconda3/lib/python3.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 64, in
from tensorflow.python._pywrap_tensorflow_internal import *
ImportError: dlopen(/Users/username/anaconda3/lib/python3.7/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so, 6): Symbol not found: _SecKeyCopyExternalRepresentation
Referenced from: /Users/username/anaconda3/lib/python3.7/site-packages/tensorflow/python/../libtensorflow_framework.2.dylib
Expected in: /System/Library/Frameworks/Security.framework/Versions/A/Security
in /Users/username/anaconda3/lib/python3.7/site-packages/tensorflow/python/../libtensorflow_framework.2.dylib

Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions. Include the entire stack trace
above this error message when asking for help.
(base) [deeplearning]$
```

</details>

**Comment by csoja** [comment]
Did you attempt to _conda install tensorflow_ before resorting to pip?
A few blog posts that may be of interest:
https://www.anaconda.com/blog/tensorflow-in-anaconda
https://www.anaconda.com/blog/understanding-conda-and-pip
https://www.anaconda.com/blog/using-pip-in-a-conda-environment

**Comment by wggbullet** [comment]
> Did you attempt to _conda install tensorflow_ before resorting to pip?
> A few blog posts that may be of interest:
> https://www.anaconda.com/blog/tensorflow-in-anaconda
> https://www.anaconda.com/blog/understanding-conda-and-pip
> https://www.anaconda.com/blog/using-pip-in-a-conda-environment

I've tried some many different ways, like install from conda install, install earlier version, install from downloaded file, ...
All those end up with the problem: the installation went through without any problem.
But when I do import tensorflow as tf, the below error occurs.. I googled it and it is such a common error and hundreds of pages mentioning this same error. But there is no good solution or anything, which is really upsetting..
base) [deeplearning]$ python -c "import tensorflow as tf;print(tf.reduce_sum(tf.random.normal([1000, 1000])))"
Traceback (most recent call last):
File "/Users/username/anaconda3/lib/python3.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 64, in
from tensorflow.python._pywrap_tensorflow_internal import *
ImportError: dlopen(/Users/username/anaconda3/lib/python3.7/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so, 6): Symbol not found: _SecKeyCopyExternalRepresentation
Referenced from: /Users/username/anaconda3/lib/python3.7/site-packages/tensorflow/python/../libtensorflow_framework.2.dylib
Expected in: /System/Library/Frameworks/Security.framework/Versions/A/Security
in /Users/username/anaconda3/lib/python3.7/site-packages/tensorflow/python/../libtensorflow_framework.2.dylib

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "", line 1, in
File "/Users/username/anaconda3/lib/python3.7/site-packages/tensorflow/init.py", line 41, in
from tensorflow.python.tools import module_util as _module_util
File "/Users/username/anaconda3/lib/python3.7/site-packages/tensorflow/python/init.py", line 40, in
from tensorflow.python.eager import context
File "/Users/username/anaconda3/lib/python3.7/site-packages/tensorflow/python/eager/context.py", line 35, in
from tensorflow.python import pywrap_tfe
File "/Users/username/anaconda3/lib/python3.7/site-packages/tensorflow/python/pywrap_tfe.py", line 28, in
from tensorflow.python import pywrap_tensorflow
File "/Users/username/anaconda3/lib/python3.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 83, in
raise ImportError(msg)
ImportError: Traceback (most recent call last):
File "/Users/username/anaconda3/lib/python3.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 64, in
from tensorflow.python._pywrap_tensorflow_internal import *
ImportError: dlopen(/Users/username/anaconda3/lib/python3.7/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so, 6): Symbol not found: _SecKeyCopyExternalRepresentation
Referenced from: /Users/username/anaconda3/lib/python3.7/site-packages/tensorflow/python/../libtensorflow_framework.2.dylib
Expected in: /System/Library/Frameworks/Security.framework/Versions/A/Security
in /Users/username/anaconda3/lib/python3.7/site-packages/tensorflow/python/../libtensorflow_framework.2.dylib

Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions. Include the entire stack trace
above this error message when asking for help.

**Comment by csoja** [comment]
I'm sorry to hear you've run into this. I see you created an issue on Tensorflow's board (https://github.com/tensorflow/tensorflow/issues/44207) - which is where I would expect this question needs to go as you are installing Tensorflow via pip and not via conda.  We do not build and do not distribute the pip Tensorflow package, and do not recommend using pip to install Tensorflow into an Anaconda environment.   You said you've seen this issues lots of places - is the issue always someone pip installing Tensorflow into an Anaconda environment - or is the issue independent of Anaconda?
