### ISSUE TITLE
macOs BigSur Anaconda2 install error：AttributeError: dlsym(RTLD_DEFAULT, AbsoluteToNanoseconds): symbol not found

### ISSUE THREAD

**Issue by mingmingding2** [ContinuumIO/anaconda-issues#12160]
### Steps to Reproduce

bash ~/Downloads/Anaconda2-2019.10-MacOSX-x86_64.sh

##### Anaconda or Miniconda version:

naconda2-2019.10-MacOSX-x86_64.sh
##### Operating System:
BigSur
##### `conda info`

<details>
$ conda info
Traceback (most recent call last):
  File "/Users/mingmingding/miniconda2/bin/conda", line 13, in <module>
    sys.exit(main())
  File "/Users/mingmingding/miniconda2/lib/python2.7/site-packages/conda/cli/main.py", line 149, in main
    from ..exceptions import conda_exception_handler
  File "/Users/mingmingding/miniconda2/lib/python2.7/site-packages/conda/exceptions.py", line 19, in <module>
    from ._vendor.auxlib.entity import EntityEncoder
  File "/Users/mingmingding/miniconda2/lib/python2.7/site-packages/conda/_vendor/auxlib/entity.py", line 253, in <module>
    from .collection import AttrDict, frozendict, make_immutable
  File "/Users/mingmingding/miniconda2/lib/python2.7/site-packages/conda/_vendor/auxlib/collection.py", line 10, in <module>
    from .compat import isiterable, iteritems, odict, text_type
  File "/Users/mingmingding/miniconda2/lib/python2.7/site-packages/conda/_vendor/auxlib/compat.py", line 10, in <module>
    from ._vendor.five import WhateverIO as StringIO, with_metaclass
  File "/Users/mingmingding/miniconda2/lib/python2.7/site-packages/conda/_vendor/auxlib/_vendor/five.py", line 80, in <module>
    absolute_to_nanoseconds = CoreServices.AbsoluteToNanoseconds
  File "/Users/mingmingding/miniconda2/lib/python2.7/ctypes/__init__.py", line 379, in __getattr__
    func = self.__getitem__(name)
  File "/Users/mingmingding/miniconda2/lib/python2.7/ctypes/__init__.py", line 384, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: dlsym(RTLD_DEFAULT, AbsoluteToNanoseconds): symbol not found
```
PASTE OUTPUT HERE:

```
# mingmingding @ MINGMINDING-MB0 in ~/anaconda2/bin on git:master x [13:23:04] C:127
$ ./conda
Traceback (most recent call last):
  File "./conda", line 13, in <module>
    sys.exit(main())
  File "/Users/mingmingding/anaconda2/lib/python2.7/site-packages/conda/cli/main.py", line 149, in main
    from ..exceptions import conda_exception_handler
  File "/Users/mingmingding/anaconda2/lib/python2.7/site-packages/conda/exceptions.py", line 19, in <module>
    from ._vendor.auxlib.entity import EntityEncoder
  File "/Users/mingmingding/anaconda2/lib/python2.7/site-packages/conda/_vendor/auxlib/entity.py", line 253, in <module>
    from .collection import AttrDict, frozendict, make_immutable
  File "/Users/mingmingding/anaconda2/lib/python2.7/site-packages/conda/_vendor/auxlib/collection.py", line 10, in <module>
    from .compat import isiterable, iteritems, odict, text_type
  File "/Users/mingmingding/anaconda2/lib/python2.7/site-packages/conda/_vendor/auxlib/compat.py", line 10, in <module>
    from ._vendor.five import WhateverIO as StringIO, with_metaclass
  File "/Users/mingmingding/anaconda2/lib/python2.7/site-packages/conda/_vendor/auxlib/_vendor/five.py", line 80, in <module>
    absolute_to_nanoseconds = CoreServices.AbsoluteToNanoseconds
  File "/Users/mingmingding/anaconda2/lib/python2.7/ctypes/__init__.py", line 379, in __getattr__
    func = self.__getitem__(name)
  File "/Users/mingmingding/anaconda2/lib/python2.7/ctypes/__init__.py", line 384, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: dlsym(RTLD_DEFAULT, AbsoluteToNanoseconds): symbol not found
</details>

##### `conda list --show-channel-urls`

<details>

```
PASTE OUTPUT HERE:

```

</details>

**Comment by mingmingding2** [comment]
fixed somehow.

$ vim ~/.zshrc

# mingmingding @ MINGMINDING-MB0 in ~/anaconda2/bin on git:master x [20:52:37]
$ source  ~/.zshrc
(base) ➜  bin git:(master) ✗ pwd
/Users/mingmingding/anaconda2/bin
(base) ➜  bin git:(master) ✗ sudo conda list
# packages in environment at /Users/mingmingding/anaconda3:
#
# Name                    Version                   Build  Channel
_ipyw_jlab_nb_ext_conf    0.1.0                    py38_0
alabaster                 0.7.12                     py_0
anaconda                  2020.07                  py38_0
anaconda-client           1.7.2                    py38_0
anaconda-navigator        1.9.12                   py38_0
anaconda-project          0.8.4                      py_0
applaunchservices         0.2.1                      py_0
appnope                   0.1.0                 py38_1001
appscript                 1.1.1            py38haf1e3a3_0
argh                      0.26.2                   py38_0
asn1crypto                1.3.0                    py38_1
astroid                   2.4.2                    py38_0
astropy                   4.0.1.post1      py38h01d97ff_1
atomicwrites              1.4.0                      py_0
attrs                     19.3.0                     py_0
autopep8                  1.5.3                      py_0
babel                     2.8.0                      py_0
backcall                  0.2.0                      py_0
backports                 1.0                        py_2
backports.functools_lru_cache 1.6.1                      py_0
backports.shutil_get_terminal_size 1.0.0                    py38_2
backports.tempfile        1.0                        py_1
backports.weakref         1.0.post1                  py_1
beautifulsoup4            4.9.1                    py38_0
bitarray                  1.4.0            py38haf1e3a3_0
bkcharts                  0.2                      py38_0
blas                      1.0                         mkl
bleach                    3.1.5                      py_0
blosc                     1.19.0               hab81aa3_0
bokeh                     2.1.1                    py38_0
boto                      2.49.0                   py38_0
bottleneck                1.3.2            py38hf1fa96c_1
brotlipy                  0.7.0           py38haf1e3a3_1000
bzip2                     1.0.8                h1de35cc_0
ca-certificates           2020.6.24                     0
certifi                   2020.6.20                py38_0
cffi                      1.14.0           py38hc512035_1
chardet                   3.0.4                 py38_1003
click                     7.1.2                      py_0
cloudpickle               1.5.0                      py_0
clyent                    1.2.2                    py38_1
colorama                  0.4.3                      py_0
conda                     4.8.3                    py38_0
conda-build               3.18.11                  py38_0
conda-env                 2.6.0                         1
conda-package-handling    1.6.1            py38h1de35cc_0
conda-verify              3.4.2                      py_1
contextlib2               0.6.0.post1                py_0
cryptography              2.9.2            py38ha12b0ac_0
curl                      7.71.1               hb0a8c7a_1
cycler                    0.10.0                   py38_0
cython                    0.29.21          py38hb1e8313_0
cytoolz                   0.10.1           py38h1de35cc_0
dask                      2.20.0                     py_0
dask-core                 2.20.0                     py_0
dbus                      1.13.16              h18a8e69_0
decorator                 4.4.2                      py_0
defusedxml                0.6.0                      py_0
diff-match-patch          20200713                   py_0
distributed               2.20.0                   py38_0
docutils                  0.16                     py38_1
entrypoints               0.3                      py38_0
et_xmlfile                1.0.1                   py_1001
expat                     2.2.9                hb1e8313_2
fastcache                 1.1.0            py38h1de35cc_0
filelock                  3.0.12                     py_0
flake8                    3.8.3                      py_0
flask                     1.1.2                      py_0
freetype                  2.10.2               ha233b18_0
fsspec                    0.7.4                      py_0
future                    0.18.2                   py38_1
get_terminal_size         1.0.0                h7520d66_0
gettext                   0.19.8.1             hb0f4f8b_2
gevent                    20.6.2           py38haf1e3a3_0
glib                      2.65.0               hc5f4afa_0
glob2                     0.7                        py_0
gmp                       6.1.2                hb37e062_1
gmpy2                     2.0.8            py38h6ef4df4_3
greenlet                  0.4.16           py38haf1e3a3_0
h5py                      2.10.0           py38h3134771_0
hdf5                      1.10.4               hfa1e0ec_0
heapdict                  1.0.1                      py_0
html5lib                  1.1                        py_0
icu                       58.2                 h0a44026_3
idna                      2.10                       py_0
imageio                   2.9.0                      py_0
imagesize                 1.2.0                      py_0
importlib-metadata        1.7.0                    py38_0
importlib_metadata        1.7.0                         0
