### ISSUE TITLE
Anaconda 4.2 unusable on Windows 7 SP1

### ISSUE THREAD

**Issue by mitchell271** [ContinuumIO/anaconda-issues#1218]
Fresh install of Anconda 4.2 x64 using Python 2.7 for Windows breaks conda and Anaconda packages are unusable
Running Windows 7 Professional SP1

Output from cygwin as follows (identical to Windows cmd)
```
{ ~ }  » conda info                                                                             ~
Traceback (most recent call last):
  File "C:\Python27\Scripts\conda-script.py", line 11, in <module>
    load_entry_point('conda==4.2.7', 'console_scripts', 'conda')()
  File "c:\python27\lib\site-packages\pkg_resources\__init__.py", line 564, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "c:\python27\lib\site-packages\pkg_resources\__init__.py", line 2608, in load_entry_point
    return ep.load()
  File "c:\python27\lib\site-packages\pkg_resources\__init__.py", line 2268, in load
    return self.resolve()
  File "c:\python27\lib\site-packages\pkg_resources\__init__.py", line 2274, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "c:\python27\lib\site-packages\conda\cli\__init__.py", line 8, in <module>
    from .main import main  # NOQA
  File "c:\python27\lib\site-packages\conda\cli\main.py", line 46, in <module>
    from ..base.context import context
  File "c:\python27\lib\site-packages\conda\base\context.py", line 18, in <module>
    from ..common.configuration import (Configuration, MapParameter, PrimitiveParameter,
  File "c:\python27\lib\site-packages\conda\common\configuration.py", line 40, in <module>
    from ruamel.yaml.comments import CommentedSeq, CommentedMap  # pragma: no cover
ImportError: No module named ruamel.yaml.comments
```

Installer md5 checksum is correct. Attempted reinstall, computer restart post-install, no solution.

Also renders Anaconda included packages unusable in projects. Example script and output from most recent PyCharm Community update
```
import scipy.io as scp
mat_contents = scp.loadmat('sample.mat')

Traceback (most recent call last):
  File "Y:/USER/mat_cat/main.py", line 1, in <module>
    import scipy.io as scp
  File "C:\Users\USERNAME\AppData\Local\Continuum\Anaconda2\lib\site-packages\scipy\__init__.py", line 61, in <module>
    from numpy import show_config as show_numpy_config
  File "C:\Users\USERNAME\AppData\Local\Continuum\Anaconda2\lib\site-packages\numpy\__init__.py", line 180, in <module>
    from . import add_newdocs
  File "C:\Users\USERNAME\AppData\Local\Continuum\Anaconda2\lib\site-packages\numpy\add_newdocs.py", line 13, in <module>
    from numpy.lib import add_newdoc
  File "C:\Users\USERNAME\AppData\Local\Continuum\Anaconda2\lib\site-packages\numpy\lib\__init__.py", line 8, in <module>
    from .type_check import *
  File "C:\Users\USERNAME\AppData\Local\Continuum\Anaconda2\lib\site-packages\numpy\lib\type_check.py", line 11, in <module>
    import numpy.core.numeric as _nx
  File "C:\Users\USERNAME\AppData\Local\Continuum\Anaconda2\lib\site-packages\numpy\core\__init__.py", line 22, in <module>
    from . import _internal  # for freeze programs
  File "C:\Users\USERNAME\AppData\Local\Continuum\Anaconda2\lib\site-packages\numpy\core\_internal.py", line 14, in <module>
    import ctypes
  File "C:\Python27\Lib\ctypes\__init__.py", line 7, in <module>
    from _ctypes import Union, Structure, Array
ImportError: DLL load failed: %1 is not a valid Win32 application.
```

Install of Anaconda passes, but usage of Anaconda packages and conda is impossible. Issue persists after conda uninstall and reinstall using pip.

**Comment by ccordoba12** [comment]
I'd say the culprit is not Anaconda but a second Python installation you seem to have in `C:\Python27`. At least that's what your error messages are showing.

**Comment by mitchell271** [comment]
Completely removed Anaconda. Decided to install various packages via pip instead. Thanks for the quick response though
