### ISSUE TITLE
Traceback (most recent call last):   File "C:\Users\PARTH\anaconda3\lib\site-packages\qtpy\__init__.py", line 204, in <module>     from PySide import __version__ as PYSIDE_VERSION  # analysis:ignore ModuleNotFoundError: No module named 'PySide'  During handling of the above exception, another exception occurred:  Traceback (most recent call last):   File "C:\Users\PARTH\anaconda3\Scripts\anaconda-navigator-script.py", line 6, in <module>     from anaconda_navigator.app.main import main   File "C:\Users\PARTH\anaconda3\lib\site-packages\anaconda_navigator\app\main.py", line 22, in <module>     from anaconda_navigator.utils.conda import is_conda_available   File "C:\Users\PARTH\anaconda3\lib\site-packages\anaconda_navigator\utils\__init__.py", line 15, in <module>     from qtpy.QtGui import QIcon   File "C:\Users\PARTH\anaconda3\lib\site-packages\qtpy\__init__.py", line 210, in <module>     raise PythonQtError('No Qt bindings could be found') qtpy.PythonQtError: No Qt bindings could be found

### ISSUE THREAD

**Issue by ParthPanchal13** [ContinuumIO/anaconda-issues#12186]
##### `conda info`

<details>

```
PASTE OUTPUT HERE:

```

</details>

##### `conda list --show-channel-urls`

<details>

```
PASTE OUTPUT HERE:

```

</details>

**Comment by lukasalexanderweber** [comment]
wow nice issue
