### ISSUE TITLE
spyder conda, no connection to https://repo.continuum.io, [Error 10109] getaddrinfo failed

### ISSUE THREAD

**Issue by matthikus** [ContinuumIO/anaconda-issues#1220]
i,ve tryed to install anaconda on my win10_64 system the hole sunday and lost all time...
the installation from https://www.continuum.io/downloads#windows works fine...

...after this i click on spyder ide in my win10 startmenue it opened and than...

                Spyder updates ...Unable to connect to the internet.

right down in the ide on the IPythonconsole reads...

                Kernel died, restarting...

dthan i tryd the win cmd nad startet an conda update...and it follows...

            

   ```
 C:\Users\Matthew MacLeod>conda update --all
    Fetching package metadata ...Could not connect to https://repo.continuum.io/pkgs/pro/noarch/
    Could not connect to https://repo.continuum.io/pkgs/msys2/noarch/
    Could not connect to https://repo.continuum.io/pkgs/msys2/win-64/
    Could not connect to https://repo.continuum.io/pkgs/pro/win-64/
    Could not connect to https://repo.continuum.io/pkgs/free/noarch/
    Could not connect to https://repo.continuum.io/pkgs/free/win-64/
    Could not connect to https://repo.continuum.io/pkgs/free/win-64/
    An unexpected error has occurred.
    Please consider posting the following information to the
    conda GitHub issue tracker at:

        https://github.com/conda/conda/issues



    Current conda install:

                   platform : win-64
              conda version : 4.2.9
           conda is private : False
          conda-env version : 4.2.9
        conda-build version : 2.0.2
             python version : 3.5.2.final.0
           requests version : 2.11.1
           root environment : C:\Users\Matthew MacLeod\Anaconda3  (writable)
        default environment : C:\Users\Matthew MacLeod\Anaconda3
           envs directories : C:\Users\Matthew MacLeod\Anaconda3\envs
              package cache : C:\Users\Matthew MacLeod\Anaconda3\pkgs
               channel URLs : https://repo.continuum.io/pkgs/free/win-64/
                              https://repo.continuum.io/pkgs/free/noarch/
                              https://repo.continuum.io/pkgs/pro/win-64/
                              https://repo.continuum.io/pkgs/pro/noarch/
                              https://repo.continuum.io/pkgs/msys2/win-64/
                              https://repo.continuum.io/pkgs/msys2/noarch/
                config file : None
               offline mode : False



    `$ C:\Users\Matthew MacLeod\Anaconda3\Scripts\conda-script.py update --all`




        Traceback (most recent call last):
          File "C:\Users\Matthew MacLeod\Anaconda3\lib\site-packages\requests\packages\urllib3\connection.py", line 142, in _new_conn
            (self.host, self.port), self.timeout, **extra_kw)
          File "C:\Users\Matthew MacLeod\Anaconda3\lib\site-packages\requests\packages\urllib3\util\connection.py", line 75, in create_connection
            for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
          File "C:\Users\Matthew MacLeod\Anaconda3\lib\socket.py", line 732, in getaddrinfo
            for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
        socket.gaierror: [Errno 10109] getaddrinfo failed

        During handling of the above exception, another exception occurred:

        Traceback (most recent call last):
          File "C:\Users\Matthew MacLeod\Anaconda3\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 595, in urlopen
            chunked=chunked)
          File "C:\Users\Matthew MacLeod\Anaconda3\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 352, in _make_request
            self._validate_conn(conn)
          File "C:\Users\Matthew MacLeod\Anaconda3\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 831, in _validate_conn
            conn.connect()
          File "C:\Users\Matthew MacLeod\Anaconda3\lib\site-packages\requests\packages\urllib3\connection.py", line 254, in connect
            conn = self._new_conn()
          File "C:\Users\Matthew MacLeod\Anaconda3\lib\site-packages\requests\packages\urllib3\connection.py", line 151, in _new_conn
            self, "Failed to establish a new connection: %s" % e)
        requests.packages.urllib3.exceptions.NewConnectionError: <requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x0000028BDB26BD30>: Failed to establish a new connection: [Errno 10109] getaddrinfo failed

        During handling of the above exception, another exception occurred:

        Traceback (most recent call last):
          File "C:\Users\Matthew MacLeod\Anaconda3\lib\site-packages\requests\adapters.py", line 423, in send
            timeout=timeout
          File "C:\Users\Matthew MacLeod\Anaconda3\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 668, in urlopen
            release_conn=release_conn, **response_kw)
          File "C:\Users\Matthew MacLeod\Anaconda3\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 668, in urlopen
            release_conn=release_conn, **response_kw)
          File "C:\Users\Matthew MacLeod\Anaconda3\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 668, in urlopen
            release_conn=release_conn, **response_kw)
          File "C:\Users\Matthew MacLeod\Anaconda3\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 640, in urlopen
            _stacktrace=sys.exc_info()[2])
          File "C:\Users\Matthew MacLeod\Anaconda3\lib\site-packages\requests\packages\urllib3\util\retry.py", line 287, in increment
            raise MaxRetryError(_pool, url, error or ResponseError(cause))
        requests.packages.urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='repo.continuum.io', port=443): Max retries exceeded with url: /pkgs/free/win-64/repodata.json.bz2 (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x0000028BDB26BD30>: Failed to establish a new connection: [Errno 10109] getaddrinfo failed',))

        During handling of the above exception, another exception occurred:

        Traceback (most recent call last):
          File "C:\Users\Matthew MacLeod\Anaconda3\lib\site-packages\conda\fetch.py", line 112, in fetch_repodata
            timeout=(3.05, 60))
          File "C:\Users\Matthew MacLeod\Anaconda3\lib\site-packages\requests\sessions.py", line 488, in get
            return self.request('GET', url, **kwargs)
          File "C:\Users\Matthew MacLeod\Anaconda3\lib\site-packages\requests\sessions.py", line 475, in request
            resp = self.send(prep, **send_kwargs)
          File "C:\Users\Matthew MacLeod\Anaconda3\lib\site-packages\requests\sessions.py", line 596, in send
            r = adapter.send(request, **kwargs)
          File "C:\Users\Matthew MacLeod\Anaconda3\lib\site-packages\requests\adapters.py", line 487, in send
            raise ConnectionError(e, request=request)
        requests.exceptions.ConnectionError: HTTPSConnectionPool(host='repo.continuum.io', port=443): Max retries exceeded with url: /pkgs/free/win-64/repodata.json.bz2 (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x0000028BDB26BD30>: Failed to establish a new connection: [Errno 10109] getaddrinfo failed',))

        During handling of the above exception, another exception occurred:

        Traceback (most recent call last):
          File "C:\Users\Matthew MacLeod\Anaconda3\lib\site-packages\conda\fetch.py", line 287, in fetch_index
            repodatas = [(u, f.result()) for u, f in zip(urls, futures)]
          File "C:\Users\Matthew MacLeod\Anaconda3\lib\site-packages\conda\fetch.py", line 287, in <listcomp>
            repodatas = [(u, f.result()) for u, f in zip(urls, futures)]
          File "C:\Users\Matthew MacLeod\Anaconda3\lib\concurrent\futures\_base.py", line 405, in result
            return self.__get_result()
          File "C:\Users\Matthew MacLeod\Anaconda3\lib\concurrent\futures\_base.py", line 357, in __get_result
            raise self._exception
          File "C:\Users\Matthew MacLeod\Anaconda3\lib\concurrent\futures\thread.py", line 55, in run
            result = self.fn(*self.args, **self.kwargs)
          File "C:\Users\Matthew MacLeod\Anaconda3\lib\site-packages\conda\fetch.py", line 70, in func
            res = f(*args, **kwargs)
          File "C:\Users\Matthew MacLeod\Anaconda3\lib\site-packages\conda\fetch.py", line 187, in fetch_repodata
            raise CondaRuntimeError(msg)
        conda.exceptions.CondaRuntimeError: Runtime error: Connection error: HTTPSConnectionPool(host='repo.continuum.io', port=443): Max retries exceeded with url: /pkgs/free/win-64/repodata.json.bz2 (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x0000028BDB26BD30>: Failed to establish a new connection: [Errno 10109] getaddrinfo failed',)): https://repo.continuum.io/pkgs/free/win-64/


        During handling of the above exception, another exception occurred:

        Traceback (most recent call last):
          File "C:\Users\Matthew MacLeod\Anaconda3\lib\site-packages\requests\packages\urllib3\connection.py", line 142, in _new_conn
            (self.host, self.port), self.timeout, **extra_kw)
          File "C:\Users\Matthew MacLeod\Anaconda3\lib\site-packages\requests\packages\urllib3\util\connection.py", line 75, in create_connection
            for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
          File "C:\Users\Matthew MacLeod\Anaconda3\lib\socket.py", line 732, in getaddrinfo
            for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
        socket.gaierror: [Errno 10109] getaddrinfo failed

        During handling of the above exception, another exception occurred:

        Traceback (most recent call last):
          File "C:\Users\Matthew MacLeod\Anaconda3\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 595, in urlopen
            chunked=chunked)
          File "C:\Users\Matthew MacLeod\Anaconda3\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 352, in _make_request
            self._validate_conn(conn)
          File "C:\Users\Matthew MacLeod\Anaconda3\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 831, in _validate_conn
            conn.connect()
          File "C:\Users\Matthew MacLeod\Anaconda3\lib\site-packages\requests\packages\urllib3\connection.py", line 254, in connect
            conn = self._new_conn()
          File "C:\Users\Matthew MacLeod\Anaconda3\lib\site-packages\requests\packages\urllib3\connection.py", line 151, in _new_conn
            self, "Failed to establish a new connection: %s" % e)
        requests.packages.urllib3.exceptions.NewConnectionError: <requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x0000028BDBAEDD30>: Failed to establish a new connection: [Errno 10109] getaddrinfo failed

        During handling of the above exception, another exception occurred:

        Traceback (most recent call last):
          File "C:\Users\Matthew MacLeod\Anaconda3\lib\site-packages\requests\adapters.py", line 423, in send
            timeout=timeout
          File "C:\Users\Matthew MacLeod\Anaconda3\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 668, in urlopen
            release_conn=release_conn, **response_kw)
          File "C:\Users\Matthew MacLeod\Anaconda3\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 668, in urlopen
            release_conn=release_conn, **response_kw)
          File "C:\Users\Matthew MacLeod\Anaconda3\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 668, in urlopen
            release_conn=release_conn, **response_kw)
          File "C:\Users\Matthew MacLeod\Anaconda3\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 640, in urlopen
            _stacktrace=sys.exc_info()[2])
          File "C:\Users\Matthew MacLeod\Anaconda3\lib\site-packages\requests\packages\urllib3\util\retry.py", line 287, in increment
            raise MaxRetryError(_pool, url, error or ResponseError(cause))
        requests.packages.urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='repo.continuum.io', port=443): Max retries exceeded with url: /pkgs/free/win-64/repodata.json.bz2 (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x0000028BDBAEDD30>: Failed to establish a new connection: [Errno 10109] getaddrinfo failed',))

        During handling of the above exception, another exception occurred:

        Traceback (most recent call last):
          File "C:\Users\Matthew MacLeod\Anaconda3\lib\site-packages\conda\fetch.py", line 112, in fetch_repodata
            timeout=(3.05, 60))
          File "C:\Users\Matthew MacLeod\Anaconda3\lib\site-packages\requests\sessions.py", line 488, in get

        return self.request('GET', url, **kwargs)

          File "C:\Users\Matthew MacLeod\Anaconda3\lib\site-packages\requests\sessions.py", line 475, in request
            resp = self.send(prep, **send_kwargs)
          File "C:\Users\Matthew MacLeod\Anaconda3\lib\site-packages\requests\sessions.py", line 596, in send
            r = adapter.send(request, **kwargs)
          File "C:\Users\Matthew MacLeod\Anaconda3\lib\site-packages\requests\adapters.py", line 487, in send
            raise ConnectionError(e, request=request)
        requests.exceptions.ConnectionError: HTTPSConnectionPool(host='repo.continuum.io', port=443): Max retries exceeded with url: /pkgs/free/win-64/repodata.json.bz2 (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x0000028BDBAEDD30>: Failed to establish a new connection: [Errno 10109] getaddrinfo failed',))

        During handling of the above exception, another exception occurred:

        Traceback (most recent call last):
          File "C:\Users\Matthew MacLeod\Anaconda3\lib\site-packages\conda\exceptions.py", line 473, in conda_exception_handler
            return_value = func(*args, **kwargs)
          File "C:\Users\Matthew MacLeod\Anaconda3\lib\site-packages\conda\cli\main.py", line 144, in _main
            exit_code = args.func(args, p)
          File "C:\Users\Matthew MacLeod\Anaconda3\lib\site-packages\conda\cli\main_update.py", line 65, in execute
            install(args, parser, 'update')
          File "C:\Users\Matthew MacLeod\Anaconda3\lib\site-packages\conda\cli\install.py", line 238, in install
            prefix=prefix)
          File "C:\Users\Matthew MacLeod\Anaconda3\lib\site-packages\conda\api.py", line 24, in get_index
            index = fetch_index(channel_urls, use_cache=use_cache, unknown=unknown)
          File "C:\Users\Matthew MacLeod\Anaconda3\lib\site-packages\conda\fetch.py", line 293, in fetch_index
            for url in urls]
          File "C:\Users\Matthew MacLeod\Anaconda3\lib\site-packages\conda\fetch.py", line 293, in <listcomp>
            for url in urls]
          File "C:\Users\Matthew MacLeod\Anaconda3\lib\site-packages\conda\fetch.py", line 70, in func
            res = f(*args, **kwargs)
          File "C:\Users\Matthew MacLeod\Anaconda3\lib\site-packages\conda\fetch.py", line 187, in fetch_repodata
            raise CondaRuntimeError(msg)
        conda.exceptions.CondaRuntimeError: Runtime error: Connection error: HTTPSConnectionPool(host='repo.continuum.io', port=443): Max retries exceeded with url: /pkgs/free/win-64/repodata.json.bz2 (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x0000028BDBAEDD30>: Failed to establish a new connection: [Errno 10109] getaddrinfo failed',)): https://repo.continuum.io/pkgs/free/win-64/



    (C:\Users\Matthew MacLeod\Anaconda3) C:\Users\Matthew MacLeod>
```

has anybody a solution for this ??

...i tried all...searched google and haven't found any logical solution on my self :-(

**Comment by matthikus** [comment]
Edit: 

now i tryed this one:

```
(C:\Users\Matthew MacLeod\Anaconda3) C:\Users\Matthew MacLeod>conda create --name test spyder
Fetching package metadata ...Could not connect to https://repo.continuum.io/pkgs/pro/win-64/
Could not connect to https://repo.continuum.io/pkgs/msys2/win-64/
Could not connect to https://repo.continuum.io/pkgs/msys2/noarch/
Could not connect to https://repo.continuum.io/pkgs/pro/noarch/
Could not connect to https://repo.continuum.io/pkgs/free/noarch/
Could not connect to https://repo.continuum.io/pkgs/free/win-64/
Could not connect to https://repo.continuum.io/pkgs/free/win-64/
An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues



Current conda install:

               platform : win-64
          conda version : 4.2.9
       conda is private : False
      conda-env version : 4.2.9
    conda-build version : 2.0.2
         python version : 3.5.2.final.0
       requests version : 2.11.1
       root environment : C:\Users\Matthew MacLeod\Anaconda3  (writable)
    default environment : C:\Users\Matthew MacLeod\Anaconda3
       envs directories : C:\Users\Matthew MacLeod\Anaconda3\envs
          package cache : C:\Users\Matthew MacLeod\Anaconda3\pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/win-64/
                          https://repo.continuum.io/pkgs/free/noarch/
                          https://repo.continuum.io/pkgs/pro/win-64/
                          https://repo.continuum.io/pkgs/pro/noarch/
                          https://repo.continuum.io/pkgs/msys2/win-64/
                          https://repo.continuum.io/pkgs/msys2/noarch/
            config file : None
           offline mode : False



`$ C:\Users\Matthew MacLeod\Anaconda3\Scripts\conda-script.py create --name test spyder`




    Traceback (most recent call last):
      File "C:\Users\Matthew MacLeod\Anaconda3\lib\site-packages\requests\packages\urllib3\connection.py", line 142, in _new_conn
        (self.host, self.port), self.timeout, **extra_kw)
      File "C:\Users\Matthew MacLeod\Anaconda3\lib\site-packages\requests\packages\urllib3\util\connection.py", line 75, in create_connection
        for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
      File "C:\Users\Matthew MacLeod\Anaconda3\lib\socket.py", line 732, in getaddrinfo
        for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
    socket.gaierror: [Errno 10109] getaddrinfo failed

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "C:\Users\Matthew MacLeod\Anaconda3\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 595, in urlopen
        chunked=chunked)
      File "C:\Users\Matthew MacLeod\Anaconda3\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 352, in _make_request
        self._validate_conn(conn)
      File "C:\Users\Matthew MacLeod\Anaconda3\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 831, in _validate_conn
        conn.connect()
      File "C:\Users\Matthew MacLeod\Anaconda3\lib\site-packages\requests\packages\urllib3\connection.py", line 254, in connect
        conn = self._new_conn()
      File "C:\Users\Matthew MacLeod\Anaconda3\lib\site-packages\requests\packages\urllib3\connection.py", line 151, in _new_conn
        self, "Failed to establish a new connection: %s" % e)
    requests.packages.urllib3.exceptions.NewConnectionError: : Failed to establish a new connection: [Errno 10109] getaddrinfo failed

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "C:\Users\Matthew MacLeod\Anaconda3\lib\site-packages\requests\adapters.py", line 423, in send
        timeout=timeout
      File "C:\Users\Matthew MacLeod\Anaconda3\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 668, in urlopen
        release_conn=release_conn, **response_kw)
      File "C:\Users\Matthew MacLeod\Anaconda3\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 668, in urlopen
        release_conn=release_conn, **response_kw)
      File "C:\Users\Matthew MacLeod\Anaconda3\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 668, in urlopen
        release_conn=release_conn, **response_kw)
      File "C:\Users\Matthew MacLeod\Anaconda3\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 640, in urlopen
        _stacktrace=sys.exc_info()[2])
      File "C:\Users\Matthew MacLeod\Anaconda3\lib\site-packages\requests\packages\urllib3\util\retry.py", line 287, in increment
        raise MaxRetryError(_pool, url, error or ResponseError(cause))
    requests.packages.urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='repo.continuum.io', port=443): Max retries exceeded with url: /pkgs/free/win-64/repodata.json.bz2 (Caused by NewConnectionError(': Failed to establish a new connection: [Errno 10109] getaddrinfo failed',))

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "C:\Users\Matthew MacLeod\Anaconda3\lib\site-packages\conda\fetch.py", line 112, in fetch_repodata
        timeout=(3.05, 60))
      File "C:\Users\Matthew MacLeod\Anaconda3\lib\site-packages\requests\sessions.py", line 488, in get
        return self.request('GET', url, **kwargs)
      File "C:\Users\Matthew MacLeod\Anaconda3\lib\site-packages\requests\sessions.py", line 475, in request
        resp = self.send(prep, **send_kwargs)
      File "C:\Users\Matthew MacLeod\Anaconda3\lib\site-packages\requests\sessions.py", line 596, in send
        r = adapter.send(request, **kwargs)
      File "C:\Users\Matthew MacLeod\Anaconda3\lib\site-packages\requests\adapters.py", line 487, in send
        raise ConnectionError(e, request=request)
    requests.exceptions.ConnectionError: HTTPSConnectionPool(host='repo.continuum.io', port=443): Max retries exceeded with url: /pkgs/free/win-64/repodata.json.bz2 (Caused by NewConnectionError(': Failed to establish a new connection: [Errno 10109] getaddrinfo failed',))

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "C:\Users\Matthew MacLeod\Anaconda3\lib\site-packages\conda\fetch.py", line 287, in fetch_index
        repodatas = [(u, f.result()) for u, f in zip(urls, futures)]
      File "C:\Users\Matthew MacLeod\Anaconda3\lib\site-packages\conda\fetch.py", line 287, in 
        repodatas = [(u, f.result()) for u, f in zip(urls, futures)]
      File "C:\Users\Matthew MacLeod\Anaconda3\lib\concurrent\futures\_base.py", line 405, in result
        return self.__get_result()
      File "C:\Users\Matthew MacLeod\Anaconda3\lib\concurrent\futures\_base.py", line 357, in __get_result
        raise self._exception
      File "C:\Users\Matthew MacLeod\Anaconda3\lib\concurrent\futures\thread.py", line 55, in run
        result = self.fn(*self.args, **self.kwargs)
      File "C:\Users\Matthew MacLeod\Anaconda3\lib\site-packages\conda\fetch.py", line 70, in func
        res = f(*args, **kwargs)
      File "C:\Users\Matthew MacLeod\Anaconda3\lib\site-packages\conda\fetch.py", line 187, in fetch_repodata
        raise CondaRuntimeError(msg)
    conda.exceptions.CondaRuntimeError: Runtime error: Connection error: HTTPSConnectionPool(host='repo.continuum.io', port=443): Max retries exceeded with url: /pkgs/free/win-64/repodata.json.bz2 (Caused by NewConnectionError(': Failed to establish a new connection: [Errno 10109] getaddrinfo failed',)): https://repo.continuum.io/pkgs/free/win-64/


    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "C:\Users\Matthew MacLeod\Anaconda3\lib\site-packages\requests\packages\urllib3\connection.py", line 142, in _new_conn
        (self.host, self.port), self.timeout, **extra_kw)
      File "C:\Users\Matthew MacLeod\Anaconda3\lib\site-packages\requests\packages\urllib3\util\connection.py", line 75, in create_connection
        for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
      File "C:\Users\Matthew MacLeod\Anaconda3\lib\socket.py", line 732, in getaddrinfo
        for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
    socket.gaierror: [Errno 10109] getaddrinfo failed

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "C:\Users\Matthew MacLeod\Anaconda3\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 595, in urlopen
        chunked=chunked)
      File "C:\Users\Matthew MacLeod\Anaconda3\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 352, in _make_request
        self._validate_conn(conn)
      File "C:\Users\Matthew MacLeod\Anaconda3\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 831, in _validate_conn
        conn.connect()
      File "C:\Users\Matthew MacLeod\Anaconda3\lib\site-packages\requests\packages\urllib3\connection.py", line 254, in connect
        conn = self._new_conn()
      File "C:\Users\Matthew MacLeod\Anaconda3\lib\site-packages\requests\packages\urllib3\connection.py", line 151, in _new_conn
        self, "Failed to establish a new connection: %s" % e)
    requests.packages.urllib3.exceptions.NewConnectionError: : Failed to establish a new connection: [Errno 10109] getaddrinfo failed

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "C:\Users\Matthew MacLeod\Anaconda3\lib\site-packages\requests\adapters.py", line 423, in send
        timeout=timeout
      File "C:\Users\Matthew MacLeod\Anaconda3\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 668, in urlopen
        release_conn=release_conn, **response_kw)
      File "C:\Users\Matthew MacLeod\Anaconda3\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 668, in urlopen
        release_conn=release_conn, **response_kw)
      File "C:\Users\Matthew MacLeod\Anaconda3\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 668, in urlopen
        release_conn=release_conn, **response_kw)
      File "C:\Users\Matthew MacLeod\Anaconda3\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 640, in urlopen
        _stacktrace=sys.exc_info()[2])
      File "C:\Users\Matthew MacLeod\Anaconda3\lib\site-packages\requests\packages\urllib3\util\retry.py", line 287, in increment
        raise MaxRetryError(_pool, url, error or ResponseError(cause))
    requests.packages.urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='repo.continuum.io', port=443): Max retries exceeded with url: /pkgs/free/win-64/repodata.json.bz2 (Caused by NewConnectionError(': Failed to establish a new connection: [Errno 10109] getaddrinfo failed',))

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "C:\Users\Matthew MacLeod\Anaconda3\lib\site-packages\conda\fetch.py", line 112, in fetch_repodata
        timeout=(3.05, 60))
      File "C:\Users\Matthew MacLeod\Anaconda3\lib\site-packages\requests\sessions.py", line 488, in get
        return self.request('GET', url, **kwargs)
      File "C:\Users\Matthew MacLeod\Anaconda3\lib\site-packages\requests\sessions.py", line 475, in request
        resp = self.send(prep, **send_kwargs)
      File "C:\Users\Matthew MacLeod\Anaconda3\lib\site-packages\requests\sessions.py", line 596, in send
        r = adapter.send(request, **kwargs)
      File "C:\Users\Matthew MacLeod\Anaconda3\lib\site-packages\requests\adapters.py", line 487, in send
        raise ConnectionError(e, request=request)
    requests.exceptions.ConnectionError: HTTPSConnectionPool(host='repo.continuum.io', port=443): Max retries exceeded with url: /pkgs/free/win-64/repodata.json.bz2 (Caused by NewConnectionError(': Failed to establish a new connection: [Errno 10109] getaddrinfo failed',))

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "C:\Users\Matthew MacLeod\Anaconda3\lib\site-packages\conda\exceptions.py", line 473, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "C:\Users\Matthew MacLeod\Anaconda3\lib\site-packages\conda\cli\main.py", line 144, in _main
        exit_code = args.func(args, p)
      File "C:\Users\Matthew MacLeod\Anaconda3\lib\site-packages\conda\cli\main_create.py", line 68, in execute
        install(args, parser, 'create')
      File "C:\Users\Matthew MacLeod\Anaconda3\lib\site-packages\conda\cli\install.py", line 238, in install
        prefix=prefix)
      File "C:\Users\Matthew MacLeod\Anaconda3\lib\site-packages\conda\api.py", line 24, in get_index
        index = fetch_index(channel_urls, use_cache=use_cache, unknown=unknown)
      File "C:\Users\Matthew MacLeod\Anaconda3\lib\site-packages\conda\fetch.py", line 293, in fetch_index
        for url in urls]
      File "C:\Users\Matthew MacLeod\Anaconda3\lib\site-packages\conda\fetch.py", line 293, in 
        for url in urls]
      File "C:\Users\Matthew MacLeod\Anaconda3\lib\site-packages\conda\fetch.py", line 70, in func
        res = f(*args, **kwargs)
      File "C:\Users\Matthew MacLeod\Anaconda3\lib\site-packages\conda\fetch.py", line 187, in fetch_repodata
        raise CondaRuntimeError(msg)
    conda.exceptions.CondaRuntimeError: Runtime error: Connection error: HTTPSConnectionPool(host='repo.continuum.io', port=443): Max retries exceeded with url: /pkgs/free/win-64/repodata.json.bz2 (Caused by NewConnectionError(': Failed to establish a new connection: [Errno 10109] getaddrinfo failed',)): https://repo.continuum.io/pkgs/free/win-64/



(C:\Users\Matthew MacLeod\Anaconda3) C:\Users\Matthew MacLeod>
```

**Comment by ccordoba12** [comment]
Could you try again? It seems you were experiencing network failures in our side.

**Comment by matthikus** [comment]
UPDATE: Today at morning 07:08 same Issues... no changings :-(

What could it be ? ...

**Comment by matthikus** [comment]
EDIT 13: O'clock same isssue 


```
Kernel died, restarting


 
Kernel died, restarting


 
Kernel died, restarting


 
Kernel died, restarting


 
Kernel died, restarting


 
Kernel died, restarting


 
Kernel died, restarting


 
Kernel died, restarting


 
Kernel died, restarting


 
Kernel died, restarting


 
Kernel died, restarting

``````

**Comment by matthikus** [comment]
i've found 2  similar posts and there isnt any solution:

https://github.com/spyder-ide/spyder/issues/3444

https://github.com/spyder-ide/spyder/issues/3506

i cannot work with this ide at this status :-(

**Comment by ccordoba12** [comment]
It seems your firewall or antivirus are blocking all internet traffic, and that's preventing Spyder to create an IPython console for you.

Please add a rule to them to prevent it.

**Comment by matthikus** [comment]
i tried it yesterday with deactivated firewall and the same issue... but i try with a rule

**Comment by ccordoba12** [comment]
The fact that you're getting these errors

     conda.exceptions.CondaRuntimeError: Runtime error: Connection error: HTTPSConnectionPool(host='repo.continuum.io', port=443)

is a clear indication of network issues in your side.

You have to figure them out by yourself :-)

**Comment by matthikus** [comment]
ok sry but firewall with a rule for C:\Users\Matthew MacLeod\Anaconda3\Scripts\Spyder.exe

or a rule for C:\Users\Matthew MacLeod\Anaconda3\python.exe changed nothing...then i deactivated my firewall and strictly opend a port on my router 443 and it hasn't changed nothing...

this is not the solution... :-(

**Comment by matthikus** [comment]
and in the mainpage or the installer never stood this written ...
and i cannot be the only one with a windows system and a firwall ...so what app i should excactly allow? and also if the firewall is deactivated i've got the same issues with kernel died ...all the time...so the firewall is not the problem

**Comment by nehaljwani** [comment]
@matthikus are you still facing this issue?

**Comment by nehaljwani** [comment]
Closing due to inactivity.
