### ISSUE TITLE
Anaconda3 install error

### ISSUE THREAD

**Issue by yjc-yang** [ContinuumIO/anaconda-issues#12202]
install Anaconda3-2020.11-Windows-x86_64.exe  in win10 but error occurred as list

Navigator Error
An unexpected error occurred on Navigator start-up

Report
Please report this issue in the anaconda issue tracker

Main Error
'list' object has no attribute 'get'
Traceback
Traceback (most recent call last):
  File "C:\Anaconda3\lib\site-packages\anaconda_navigator\exceptions.py", line 75, in exception_handler
    return_value = func(*args, **kwargs)
  File "C:\Anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 151, in start_app
    window = run_app(splash)
  File "C:\Anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 65, in run_app
    window = MainWindow(splash=splash, tab_project=False)
  File "C:\Anaconda3\lib\site-packages\anaconda_navigator\widgets\main_window.py", line 170, in __init__
    self.api = AnacondaAPI()
  File "C:\Anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 1600, in AnacondaAPI
    ANACONDA_API = _AnacondaAPI()
  File "C:\Anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 78, in __init__
    self._conda_api = CondaAPI()
  File "C:\Anaconda3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 1923, in CondaAPI
    CONDA_API = _CondaAPI()
  File "C:\Anaconda3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 376, in __init__
    self.set_conda_prefix(info=get_conda_info())
  File "C:\Anaconda3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 540, in set_conda_prefix
    self.ROOT_PREFIX = info.get('root_prefix')
AttributeError: 'list' object has no attribute 'get'

**Comment by yjc-yang** [comment]
While click  the Anaconda Powershell Prompt (Anaconda3)

Could not open file mapping object (2).
Could : 無法辨識 'Could' 詞彙是否為 Cmdlet、函數、指令檔或可執行程式的名稱。請檢查名稱拼字是否正確，如果包含路徑的話，
請確認路徑是否正確，然後再試一次。
位於 線路:10 字元:1
+ Could not open file mapping object (2).
+ ~~~~~
    + CategoryInfo          : ObjectNotFound: (Could:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
