### ISSUE TITLE
Cannot install Anaconda 2020.11 version on Ubuntu 20.04

### ISSUE THREAD

**Issue by ad-free** [ContinuumIO/anaconda-issues#12205]
Do you accept the license terms? [yes|no]
[no] >>> yes

Anaconda3 will now be installed into this location:
/root/anaconda3

  - Press ENTER to confirm the location
  - Press CTRL-C to abort the installation
  - Or specify a different location below

[/root/anaconda3] >>>
PREFIX=/root/anaconda3
Unpacking payload ...
concurrent.futures.process._RemoteTraceback:
'''
Traceback (most recent call last):
  File "concurrent/futures/process.py", line 368, in _queue_management_worker
  File "multiprocessing/connection.py", line 251, in recv
TypeError: __init__() missing 1 required positional argument: 'msg'
'''

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "entry_point.py", line 69, in <module>
  File "concurrent/futures/process.py", line 484, in _chain_from_iterable_of_lists
  File "concurrent/futures/_base.py", line 611, in result_iterator
  File "concurrent/futures/_base.py", line 439, in result
  File "concurrent/futures/_base.py", line 388, in __get_result
concurrent.futures.process.BrokenProcessPool: A process in the process pool was terminated abruptly while the future was running or pending.
[3459123] Failed to execute script entry_point

**Comment by dfairweather** [comment]
I was getting this exact error, turns out my disk didn't have enough memory. Cleared some space and now it works!

**Comment by mhptr** [comment]
I had a similar issue. However, I had pre-installed miniconda3. I had spent a lot of time to fix this issue. But as soon as I deleted the miniconda3 and its envs, I could install Anaconda3 without any issues.
