### ISSUE TITLE
pytest-6.2.1-py38haa95532_0 fails to load

### ISSUE THREAD

**Issue by letrout** [ContinuumIO/anaconda-issues#12214]
### Actual Behavior

Consumes all memory on my system, then fails with:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\luthj\Anaconda3\envs\pytest38\lib\site-packages\pytest\__init__.py", line 3, in <module>
    from . import collect
  File "C:\Users\luthj\Anaconda3\envs\pytest38\lib\site-packages\pytest\collect.py", line 8, in <module>
    from _pytest.deprecated import PYTEST_COLLECT_MODULE
  File "C:\Users\luthj\Anaconda3\envs\pytest38\lib\site-packages\_pytest\__init__.py", line 83, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 779, in exec_module
  File "<frozen importlib._bootstrap_external>", line 911, in get_code
  File "<frozen importlib._bootstrap_external>", line 580, in _compile_bytecode
ValueError: bad marshal data (unknown type code)

### Expected Behavior

import pytest cleanly 

### Steps to Reproduce

conda create -n pytest38 python=3.8 pytest
conda activate pytest38
python -c "import pytest"

##### Anaconda or Miniconda version:

pytest-6.2.1-py38haa95532_0

##### Operating System:

Windows 10

##### `conda info`

<details>

```
     active environment : pytest38
    active env location : C:\Users\luthj\Anaconda3\envs\pytest38
            shell level : 2
       user config file : C:\Users\luthj\.condarc
 populated config files : C:\Users\luthj\.condarc
          conda version : 4.9.2
    conda-build version : 3.18.11
         python version : 3.8.3.final.0
       virtual packages : __cuda=10.2=0
                          __win=0=0
                          __archspec=1=x86_64
       base environment : C:\Users\luthj\Anaconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\Users\luthj\Anaconda3\pkgs
                          C:\Users\luthj\.conda\pkgs
                          C:\Users\luthj\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\luthj\Anaconda3\envs
                          C:\Users\luthj\.conda\envs
                          C:\Users\luthj\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.9.2 requests/2.24.0 CPython/3.8.3 Windows/10 Windows/10.0.18362
          administrator : False
             netrc file : None
           offline mode : False

```

</details>

##### `conda list --show-channel-urls`

<details>

```
# packages in environment at C:\Users\luthj\Anaconda3\envs\pytest38:
#
# Name                    Version                   Build  Channel
atomicwrites              1.4.0                      py_0    defaults
attrs                     20.3.0             pyhd3eb1b0_0    defaults
ca-certificates           2020.12.8            haa95532_0    defaults
certifi                   2020.12.5        py38haa95532_0    defaults
colorama                  0.4.4              pyhd3eb1b0_0    defaults
iniconfig                 1.1.1                      py_0    defaults
more-itertools            8.6.0              pyhd3eb1b0_0    defaults
openssl                   1.1.1i               h2bbff1b_0    defaults
packaging                 20.8               pyhd3eb1b0_0    defaults
pip                       20.3.3           py38haa95532_0    defaults
pluggy                    0.13.1                   py38_0    defaults
py                        1.10.0             pyhd3eb1b0_0    defaults
pyparsing                 2.4.7                      py_0    defaults
pytest                    6.2.1            py38haa95532_0    defaults
python                    3.8.5                h5fd99cc_1    defaults
setuptools                51.0.0           py38haa95532_2    defaults
six                       1.15.0           py38haa95532_0    defaults
sqlite                    3.33.0               h2a8f88b_0    defaults
toml                      0.10.1                     py_0    defaults
vc                        14.2                 h21ff451_1    defaults
vs2015_runtime            14.27.29016          h5e58377_2    defaults
wheel                     0.36.2             pyhd3eb1b0_0    defaults
wincertstore              0.2                      py38_0    defaults
zlib                      1.2.11               h62dcd97_4    defaults

```

</details>

**Comment by mingwandroid** [comment]
Thanks for the report.

We tried to reproduce this on Windows and also on Linux but failed. If you can paste the output from:

`python -X importtime -c 'import pytest'`

.. that might be helpful!

Cheers.

**Comment by letrout** [comment]
Hm, I tried this another PC and was also unable to repro. The PC with the issue is 1909, the one without is 2004. FWIW the PC with the issue is a corporate PC with all sorts of "security" bloatware. Not sure what else is different.

python -X importtime -c 'import pytest':
<details>
import time: self [us] | cumulative | imported package
import time:      4668 |       4668 | _frozen_importlib_external
import time:     15329 |      15329 |   time
import time:      7567 |      22895 | zipimport
import time:       333 |        333 |     _codecs
import time:     10411 |      10743 |   codecs
import time:      3625 |       3625 |   encodings.aliases
import time:     31624 |      45991 | encodings
import time:     25529 |      25529 | encodings.utf_8
import time:     27253 |      27253 | encodings.cp1252
import time:       854 |        854 | _signal
import time:      6746 |       6746 | encodings.latin_1
import time:       909 |        909 |     _abc
import time:     39722 |      40631 |   abc
import time:     13434 |      54065 | io
import time:       499 |        499 |       _stat
import time:     13202 |      13701 |     stat
import time:      4018 |       4018 |     _collections_abc
import time:      2036 |       2036 |       genericpath
import time:     17843 |      19878 |     ntpath
import time:     35554 |      73149 |   os
import time:     15403 |      15403 |   _sitebuiltins
import time:      1315 |       1315 |     _locale
import time:     16894 |      18208 |   _bootlocale
import time:      5080 |       5080 |   sitecustomize
import time:      3006 |       3006 |   usercustomize
import time:     57771 |     172615 | site
import time:     15277 |      15277 |     warnings
import time:     13837 |      13837 |     types
import time:        86 |         86 |           _operator
import time:      9194 |       9279 |         operator
import time:     18265 |      18265 |         keyword
import time:       590 |        590 |           _heapq
import time:     23117 |      23706 |         heapq
import time:      2056 |       2056 |         itertools
import time:     12664 |      12664 |         reprlib
import time:       787 |        787 |         _collections
import time:     55785 |     122540 |       collections
import time:     23544 |      23544 |       collections.abc
import time:      1559 |       1559 |           _functools
import time:     17917 |      19475 |         functools
import time:     40072 |      59546 |       contextlib
import time:     21513 |      21513 |         enum
import time:      4527 |       4527 |           _sre
import time:     10441 |      10441 |             sre_constants
import time:     23520 |      33961 |           sre_parse
import time:     17833 |      56320 |         sre_compile
import time:      5880 |       5880 |         copyreg
import time:     16954 |     100664 |       re
import time:     67387 |     373680 |     typing
import time:  47481949 |   47481949 |         _pytest._version
import time:     29274 |   47511223 |       _pytest
import time:      5268 |   47516490 |     _pytest.deprecated
import time:     34748 |   47954030 |   pytest.collect
import time:     23955 |   47977985 | pytest
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\luthj\Anaconda3\envs\pytest38\lib\site-packages\pytest\__init__.py", line 3, in <module>
    from . import collect
  File "C:\Users\luthj\Anaconda3\envs\pytest38\lib\site-packages\pytest\collect.py", line 8, in <module>
    from _pytest.deprecated import PYTEST_COLLECT_MODULE
  File "C:\Users\luthj\Anaconda3\envs\pytest38\lib\site-packages\_pytest\__init__.py", line 83, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 779, in exec_module
  File "<frozen importlib._bootstrap_external>", line 911, in get_code
  File "<frozen importlib._bootstrap_external>", line 580, in _compile_bytecode
ValueError: bad marshal data (unknown type code)
</details>
