### ISSUE TITLE
Package "gitdb" is broken after "smmap" was updated to 4.0.0

### ISSUE THREAD

**Issue by anjos** [ContinuumIO/anaconda-issues#12255]
### Actual Behavior

```sh
$ conda create -n test gitdb
$ conda activate test
(test) $ python
>>> import pkg_resources
>>> pkg_resources.require('gitdb')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/andre/conda/envs/test/lib/python3.9/site-packages/pkg_resources/__init__.py", line 886, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/Users/andre/conda/envs/test/lib/python3.9/site-packages/pkg_resources/__init__.py", line 777, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (smmap 4.0.0 (/Users/andre/conda/envs/test/lib/python3.9/site-packages), Requirement.parse('smmap<4,>=3.0.1'), {'gitdb'})
``` 

This is due to the fact gitdb requirements file actually states `smmap<4`, but that requirement is not taken into consideration at the conda recipe that built the package, causing this issue.

### Expected Behavior

Requiring `gitdb` should behave correctly.

### Steps to Reproduce

See above.

##### `conda info`

<details>

```

     active environment : test
    active env location : /Users/andre/conda/envs/test
            shell level : 1
       user config file : /Users/andre/.condarc
 populated config files : /Users/andre/conda/condarc
          conda version : 4.9.2
    conda-build version : 3.21.4
         python version : 3.7.4.final.0
       virtual packages : __osx=10.15.7=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /Users/andre/conda  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/osx-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/osx-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /Users/andre/conda/pkgs
                          /Users/andre/.conda/pkgs
       envs directories : /Users/andre/conda/envs
                          /Users/andre/.conda/envs
               platform : osx-64
             user-agent : conda/4.9.2 requests/2.25.1 CPython/3.7.4 Darwin/19.6.0 OSX/10.15.7
                UID:GID : 501:20
             netrc file : None
           offline mode : False

```

</details>

##### `conda list --show-channel-urls`

<details>

```
# packages in environment at /Users/andre/conda/envs/test:
#
# Name                    Version                   Build  Channel
ca-certificates           2021.1.19            hecd8cb5_0    defaults
certifi                   2020.12.5        py39hecd8cb5_0    defaults
gitdb                     4.0.5                      py_0    defaults
libcxx                    10.0.0                        1    defaults
libedit                   3.1.20191231         h1de35cc_1    defaults
libffi                    3.3                  hb1e8313_2    defaults
ncurses                   6.2                  h0a44026_1    defaults
openssl                   1.1.1i               h9ed2024_0    defaults
pip                       20.3.3           py39hecd8cb5_0    defaults
python                    3.9.1                h88f2d9e_2    defaults
readline                  8.0                  h1de35cc_0    defaults
setuptools                52.0.0           py39hecd8cb5_0    defaults
smmap                     4.0.0              pyhd3eb1b0_0    defaults
sqlite                    3.33.0               hffcf06c_0    defaults
tk                        8.6.10               hb0a8c7a_0    defaults
tzdata                    2020f                h52ac0ba_0    defaults
wheel                     0.36.2             pyhd3eb1b0_0    defaults
xz                        5.2.5                h1de35cc_0    defaults
zlib                      1.2.11               h1de35cc_3    defaults
```

</details>

**Comment by Tronyxsystem** [comment]
I have installed gitdb2 and everything works fine now.

More info => https://github.com/gitpython-developers/smmap/issues/44

**Comment by anjos** [comment]
Yes, I confirm this is working better now.
