### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by jaisyking** [ContinuumIO/anaconda-issues#12336]
## Main error
Application <b>notebook</b> launch may have produced errors.
## Traceback
```
Error processing line 7 of C:\Users\Jaisy King\Anaconda3\lib\site-packages\pywin32.pth:

  Traceback (most recent call last):
    File "C:\Users\Jaisy King\Anaconda3\lib\site.py", line 168, in addpackage
      exec(line)
    File "<string>", line 1, in <module>
  ModuleNotFoundError: No module named 'pywin32_bootstrap'

Remainder of file ignored
[I 07:22:22.462 NotebookApp] The port 8888 is already in use, trying another port.
[I 07:22:22.617 NotebookApp] Serving notebooks from local directory: C:\Users\Jaisy King
[I 07:22:22.617 NotebookApp] 0 active kernels 
[I 07:22:22.617 NotebookApp] The Jupyter Notebook is running at: http://localhost:8889/?token=3cb11396e43ab08e32eaffdf702d3cd18dca4081870034f8
[I 07:22:22.617 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 07:22:22.618 NotebookApp] 
    
    Copy/paste this URL into your browser when you connect for the first time,
    to login with a token:
        http://localhost:8889/?token=3cb11396e43ab08e32eaffdf702d3cd18dca4081870034f8
[I 07:22:22.979 NotebookApp] Accepting one-time-token-authenticated connection from ::1

```
## System information
```
python: 3.6.1
language: en_GB
os: Windows;8.1;6.3.9600;AMD64;Intel64 Family 6 Model 69 Stepping 1, GenuineIntel
version: 1.6.2
platform: win-64
qt: 5.6.2
pyqt: 5.6.0
conda: 4.3.21
```

**Comment by csoja** [comment]
You are using a very old version of conda and Navigator.  I would recommend updating to the latest using the Anaconda Prompt or a terminal. If you are unfamiliar with how to do that, please refer to the documentation at docs.anaconda.com
I'm going to close this issue - but if you are still experience this error after an update, please create a new issue and include all the information requested in the issue template.
