### ISSUE TITLE
Anaconda Navigator error on startup

### ISSUE THREAD

**Issue by drsanchikagupta** [ContinuumIO/anaconda-issues#12333]
### Actual Behavior

Navigator Error
An unexpected error occurred on Navigator start-up

Report
Please report this issue in the anaconda issue tracker

Main Error
'root_prefix'
Traceback
Traceback (most recent call last):
  File "/Users/sanch_g/anaconda3/lib/python3.7/site-packages/anaconda_navigator/exceptions.py", line 75, in exception_handler
    return_value = func(*args, **kwargs)
  File "/Users/sanch_g/anaconda3/lib/python3.7/site-packages/anaconda_navigator/app/start.py", line 151, in start_app
    window = run_app(splash)
  File "/Users/sanch_g/anaconda3/lib/python3.7/site-packages/anaconda_navigator/app/start.py", line 65, in run_app
    window = MainWindow(splash=splash, tab_project=False)
  File "/Users/sanch_g/anaconda3/lib/python3.7/site-packages/anaconda_navigator/widgets/main_window.py", line 168, in __init__
    self.api = AnacondaAPI()
  File "/Users/sanch_g/anaconda3/lib/python3.7/site-packages/anaconda_navigator/api/anaconda_api.py", line 2337, in AnacondaAPI
    ANACONDA_API = _AnacondaAPI()
  File "/Users/sanch_g/anaconda3/lib/python3.7/site-packages/anaconda_navigator/api/anaconda_api.py", line 89, in __init__
    self._conda_api = CondaAPI()
  File "/Users/sanch_g/anaconda3/lib/python3.7/site-packages/anaconda_navigator/api/conda_api.py", line 1773, in CondaAPI
    CONDA_API = _CondaAPI()
  File "/Users/sanch_g/anaconda3/lib/python3.7/site-packages/anaconda_navigator/api/conda_api.py", line 350, in __init__
    self.set_conda_prefix(info=get_conda_info())
  File "/Users/sanch_g/anaconda3/lib/python3.7/site-packages/anaconda_navigator/api/conda_api.py", line 505, in set_conda_prefix
    self.ROOT_PREFIX = info['root_prefix']
KeyError: 'root_prefix'

### Expected Behavior

Open Anaconda GUI

### Steps to Reproduce

Start the Navigator

##### `conda info`

<details>

```
# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/Users/sanch_g/anaconda3/lib/python3.7/site-packages/conda/exceptions.py", line 1079, in __call__
        return func(*args, **kwargs)
      File "/Users/sanch_g/anaconda3/lib/python3.7/site-packages/conda/cli/main.py", line 84, in _main
        exit_code = do_call(args, p)
      File "/Users/sanch_g/anaconda3/lib/python3.7/site-packages/conda/cli/conda_argparse.py", line 80, in do_call
        module = import_module(relative_mod, __name__.rsplit('.', 1)[0])
      File "/Users/sanch_g/anaconda3/lib/python3.7/importlib/__init__.py", line 127, in import_module
        return _bootstrap._gcd_import(name[level:], package, level)
      File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
      File "<frozen importlib._bootstrap>", line 983, in _find_and_load
      File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
      File "<frozen importlib._bootstrap_external>", line 728, in exec_module
      File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
      File "/Users/sanch_g/anaconda3/lib/python3.7/site-packages/conda/cli/main_info.py", line 19, in <module>
        from ..core.index import _supplement_index_with_system
      File "/Users/sanch_g/anaconda3/lib/python3.7/site-packages/conda/core/index.py", line 10, in <module>
        from .package_cache_data import PackageCacheData
      File "/Users/sanch_g/anaconda3/lib/python3.7/site-packages/conda/core/package_cache_data.py", line 15, in <module>
        from .path_actions import CacheUrlAction, ExtractPackageAction
      File "/Users/sanch_g/anaconda3/lib/python3.7/site-packages/conda/core/path_actions.py", line 30, in <module>
        from ..gateways.connection.download import download
      File "/Users/sanch_g/anaconda3/lib/python3.7/site-packages/conda/gateways/connection/download.py", line 18, in <module>
        from .session import CondaSession
      File "/Users/sanch_g/anaconda3/lib/python3.7/site-packages/conda/gateways/connection/session.py", line 13, in <module>
        from .adapters.s3 import S3Adapter
      File "/Users/sanch_g/anaconda3/lib/python3.7/site-packages/conda/gateways/connection/adapters/s3.py", line 14, in <module>
        boto3.client('s3')  # https://github.com/conda/conda/issues/8993
      File "/Users/sanch_g/anaconda3/lib/python3.7/site-packages/boto3/__init__.py", line 93, in client
        return _get_default_session().client(*args, **kwargs)
      File "/Users/sanch_g/anaconda3/lib/python3.7/site-packages/boto3/session.py", line 263, in client
        aws_session_token=aws_session_token, config=config)
      File "/Users/sanch_g/anaconda3/lib/python3.7/site-packages/botocore/session.py", line 797, in create_client
        region_name = self._resolve_region_name(region_name, config)
      File "/Users/sanch_g/anaconda3/lib/python3.7/site-packages/botocore/session.py", line 853, in _resolve_region_name
        validate_region_name(region_name)
      File "/Users/sanch_g/anaconda3/lib/python3.7/site-packages/botocore/utils.py", line 1016, in validate_region_name
        raise InvalidRegionError(region_name=region_name)
    botocore.exceptions.InvalidRegionError: Provided region_name 'ap - south - 1' doesn't match a supported format.

`$ /Users/sanch_g/anaconda3/bin/conda info`


An unexpected error has occurred. Conda has prepared the above report.

If submitted, this report will be used by core maintainers to improve
future releases of conda.
Would you like conda to send this report to the core maintainers?


```

</details>

##### `conda list --show-channel-urls`

<details>

```
# packages in environment at /Users/sanch_g/anaconda3:
#
# Name                    Version                   Build  Channel
_ipyw_jlab_nb_ext_conf    0.1.0                    py37_0    defaults
_py-xgboost-mutex         2.0                       cpu_0    anaconda
absl-py                   0.10.0                   pypi_0    pypi
alabaster                 0.7.12                   py37_0    defaults
anaconda-client           1.7.2                    py37_0    defaults
anaconda-navigator        1.9.7                    py37_0    defaults
anaconda-project          0.8.2                    py37_0    defaults
appdirs                   1.4.4                    pypi_0    pypi
appnope                   0.1.0                    py37_0    defaults
appscript                 1.1.0            py37h1de35cc_0    defaults
asciitree                 0.3.3                    pypi_0    pypi
asgiref                   3.3.1                    pypi_0    pypi
asn1crypto                0.24.0                   py37_0    defaults
astroid                   2.2.5                    py37_0    defaults
astropy                   3.1.2            py37h1de35cc_0    defaults
astunparse                1.6.3                    pypi_0    pypi
atomicwrites              1.3.0                    py37_1    defaults
attrs                     19.1.0                   py37_1    defaults
azure-core                1.12.0                   pypi_0    pypi
azure-storage-blob        12.6.0                   pypi_0    pypi
babel                     2.6.0                    py37_0    defaults
backcall                  0.1.0                    py37_0    defaults
backports                 1.0                      py37_1    defaults
backports.os              0.1.1                    py37_0    defaults
backports.shutil_get_terminal_size 1.0.0                    py37_2    defaults
beautifulsoup4            4.7.1                    py37_1    defaults
bitarray                  0.8.3            py37h1de35cc_0    defaults
bkcharts                  0.2                      py37_0    defaults
blas                      1.0                         mkl    defaults
bleach                    3.1.0                    py37_0    defaults
blis                      0.4.1                    pypi_0    pypi
blosc                     1.15.0               hd9629dc_0    defaults
bokeh                     1.0.4                    py37_0    defaults
boto                      2.49.0                   py37_0    defaults
boto3                     1.17.20                  pypi_0    pypi
botocore                  1.20.29                  pypi_0    pypi
bottleneck                1.2.1            py37h1d22016_1    defaults
bugout                    0.1.8                    pypi_0    pypi
bzip2                     1.0.6                h1de35cc_5    defaults
ca-certificates           2020.1.1                      0    anaconda
cachetools                4.1.1                    pypi_0    pypi
cachey                    0.2.1                    pypi_0    pypi
catalogue                 1.0.0                    pypi_0    pypi
cctools                   895                           1    defaults
certifi                   2020.4.5.1               py37_0    anaconda
cffi                      1.12.2           py37hb5b8e2f_1    defaults
chardet                   3.0.4                    py37_1    defaults
clang                     4.0.1                         1    defaults
clang_osx-64              4.0.1               h1ce6c1d_16    defaults
clangxx                   4.0.1                         1    defaults
clangxx_osx-64            4.0.1               h22b1bf0_16    defaults
click                     7.0                      py37_0    defaults
cloudpickle               1.6.0                    pypi_0    pypi
clyent                    1.2.2                    py37_1    defaults
colorama                  0.4.1                    py37_0    defaults
colorlover                0.3.0                    pypi_0    pypi
compiler-rt               4.0.1                hcfea43d_1    defaults
conda                     4.8.3                    py37_0    anaconda
conda-build               3.17.8                   py37_0    defaults
conda-env                 2.6.0                         1    defaults
conda-package-handling    1.6.0            py37h1de35cc_0    anaconda
conda-verify              3.1.1                    py37_0    defaults
contextlib2               0.5.5                    py37_0    defaults
convertdate               2.1.3                   py_1000    conda-forge
cryptography              2.6.1            py37ha12b0ac_0    defaults
cufflinks                 0.15                     pypi_0    pypi
curl                      7.64.0               ha441bb4_2    defaults
cycler                    0.10.0                   py37_0    defaults
cymem                     2.0.3                    pypi_0    pypi
cython                    0.29.6           py37h0a44026_0    defaults
cytoolz                   0.9.0.1          py37h1de35cc_1    defaults
dask                      1.1.4                    py37_1    defaults
dask-core                 1.1.4                    py37_1    defaults
dbus                      1.13.6               h90a0687_0    defaults
decorator                 4.4.0                    py37_1    defaults
defusedxml                0.5.0                    py37_1    defaults
dill                      0.3.3                    pypi_0    pypi
distlib                   0.3.1                    pypi_0    pypi
distributed               1.26.0                   py37_1    defaults
django                    3.1.7                    pypi_0    pypi
django-extensions         3.1.1                    pypi_0    pypi
docutils                  0.14                     py37_0    defaults
en-core-web-sm            2.2.0                    pypi_0    pypi
entrypoints               0.3                      py37_0    defaults
ephem                     3.7.6.0                  pypi_0    pypi
et_xmlfile                1.0.1                    py37_0    defaults
expat                     2.2.6                h0a44026_0    defaults
fastcache                 1.0.2            py37h1de35cc_2    defaults
fasteners                 0.16                     pypi_0    pypi
fbprophet                 0.5              py37h6de7cb9_0    conda-forge
filelock                  3.0.10                   py37_0    defaults
flask                     1.0.2                    py37_1    defaults
freetype                  2.9.1                hb4e5f40_0    defaults
fsspec                    0.8.5                    pypi_0    pypi
future                    0.17.1                   py37_0    defaults
gast                      0.3.3                    pypi_0    pypi
gcsfs                     0.6.2                    pypi_0    pypi
get_terminal_size         1.0.0                h7520d66_0    defaults
gettext                   0.19.8.1             h15daf44_3    defaults
gevent                    1.4.0            py37h1de35cc_0    defaults
glib                      2.56.2               hd9629dc_0    defaults
glob2                     0.6                      py37_1    defaults
gmp                       6.1.2                hb37e062_1    defaults
gmpy2                     2.0.8            py37h6ef4df4_2    defaults
google-auth               1.22.1                   pypi_0    pypi
google-auth-oauthlib      0.4.1                    pypi_0    pypi
google-pasta              0.2.0                    pypi_0    pypi
greenlet                  0.4.15           py37h1de35cc_0    defaults
grpcio                    1.32.0                   pypi_0    pypi
h5py                      2.10.0                   pypi_0    pypi
hdf5                      1.10.2               hfa1e0ec_1    defaults
heapdict                  1.0.0                    py37_2    defaults
holidays                  0.9.10                     py_0    conda-forge
hqueue                    0.2.0                    pypi_0    pypi
html5lib                  1.0.1                    py37_0    defaults
hub                       1.3.0                    pypi_0    pypi
humbug                    0.1.4                    pypi_0    pypi
icu                       58.2                 h4b95b61_1    defaults
idna                      2.8                      py37_0    defaults
imageio                   2.5.0                    py37_0    defaults
imagesize                 1.1.0                    py37_0    defaults
importlib-metadata        2.0.0                    pypi_0    pypi
intel-openmp              2019.3                      199    defaults
ipykernel                 5.1.0            py37h39e3cac_0    defaults
ipython                   7.4.0            py37h39e3cac_0    defaults
ipython_genutils          0.2.0                    py37_0    defaults
ipywidgets                7.4.2                    py37_0    defaults
isodate                   0.6.0                    pypi_0    pypi
isort                     4.3.16                   py37_0    defaults
itsdangerous              1.1.0                    py37_0    defaults
jbig                      2.1                  h4d881f8_0    defaults
jdcal                     1.4                      py37_0    defaults
jedi                      0.13.3                   py37_0    defaults
jinja2                    2.10                     py37_0    defaults
jmespath                  0.10.0                   pypi_0    pypi
joblib                    0.13.2                   pypi_0    pypi
jpeg                      9b                   he5867d9_2    defaults
jsonschema                3.0.1                    py37_0    defaults
jupyter                   1.0.0                    py37_7    defaults
jupyter_client            5.2.4                    py37_0    defaults
jupyter_console           6.0.0                    py37_0    defaults
jupyter_core              4.4.0                    py37_0    defaults
jupyterlab                0.35.4           py37hf63ae98_0    defaults
jupyterlab_server         0.2.0                    py37_0    defaults
keras                     2.4.3                    pypi_0    pypi
keras-preprocessing       1.1.2                    pypi_0    pypi
keyring                   18.0.0                   py37_0    defaults
kiwisolver                1.0.1            py37h0a44026_0    defaults
krb5                      1.16.1               hddcf347_7    defaults
krippendorff              0.4.0                    pypi_0    pypi
lazy-object-proxy         1.3.1            py37h1de35cc_2    defaults
ld64                      274.2                         1    defaults
libarchive                3.3.3                h786848e_5    defaults
libcurl                   7.64.0               h051b688_2    defaults
libcxx                    4.0.1                hcfea43d_1    defaults
libcxxabi                 4.0.1                hcfea43d_1    defaults
libedit                   3.1.20181209         hb402a30_0    defaults
libffi                    3.2.1                h475c297_4    defaults
libgfortran               3.0.1                h93005f0_2    defaults
libiconv                  1.15                 hdd342a3_7    defaults
liblief                   0.9.0                h2a1bed3_2    defaults
libpng                    1.6.36               ha441bb4_0    defaults
libsodium                 1.0.16               h3efe00b_0    defaults
libssh2                   1.8.0                ha12b0ac_4    defaults
libtiff                   4.0.10               hcb84e12_2    defaults
libxgboost                0.90                 h0a44026_1    anaconda
libxml2                   2.9.9                hab757c2_0    defaults
libxslt                   1.1.33               h33a18ac_0    defaults
lightgbm                  2.2.1            py37h0a44026_0    defaults
littleutils               0.2.2                    pypi_0    pypi
llvm                      4.0.1                         1    defaults
llvm-lto-tapi             4.0.1                         1    defaults
llvm-openmp               4.0.1                hcfea43d_1    defaults
llvmlite                  0.28.0           py37h8c7ce04_0    defaults
locket                    0.2.0                    py37_1    defaults
lunardate                 0.2.0                      py_0    conda-forge
lxml                      4.3.2            py37hef8c89e_0    defaults
lz4                       3.1.3                    pypi_0    pypi
lz4-c                     1.8.1.2              h1de35cc_0    defaults
lzo                       2.10                 h362108e_2    defaults
markdown                  3.3                      pypi_0    pypi
markupsafe                1.1.1            py37h1de35cc_0    defaults
matplotlib                3.0.3            py37h54f8f79_0    defaults
mccabe                    0.6.1                    py37_1    defaults
mistune                   0.8.4            py37h1de35cc_0    defaults
mkl                       2019.3                      199    defaults
mkl-service               1.1.2            py37hfbe908c_5    defaults
mkl_fft                   1.0.10           py37h5e564d8_0    defaults
mkl_random                1.0.2            py37h27c97d8_0    defaults
mongoengine               0.23.0                   pypi_0    pypi
more-itertools            6.0.0                    py37_0    defaults
mpc                       1.1.0                h6ef4df4_1    defaults
mpfr                      4.0.1                h3018a27_3    defaults
mpmath                    1.1.0                    py37_0    defaults
msgpack                   1.0.2                    pypi_0    pypi
msrest                    0.6.21                   pypi_0    pypi
multipledispatch          0.6.0                    py37_0    defaults
multiprocess              0.70.11.1                pypi_0    pypi
murmurhash                1.0.2                    pypi_0    pypi
navigator-updater         0.2.1                    py37_0    defaults
nbconvert                 5.4.1                    py37_3    defaults
nbformat                  4.4.0                    py37_0    defaults
ncurses                   6.1                  h0a44026_1    defaults
networkx                  2.2                      py37_1    defaults
nltk                      3.4                      py37_1    defaults
nose                      1.3.7                    py37_2    defaults
notebook                  5.7.8                    py37_0    defaults
numba                     0.43.1           py37h6440ff4_0    defaults
numcodecs                 0.7.3                    pypi_0    pypi
numexpr                   2.6.9            py37h7413580_0    defaults
numpy                     1.16.2           py37hacdab7b_0    defaults
numpy-base                1.16.2           py37h6575580_0    defaults
numpydoc                  0.8.0                    py37_0    defaults
oauthlib                  3.1.0                    pypi_0    pypi
olefile                   0.46                     py37_0    defaults
openpyxl                  2.6.1                    py37_1    defaults
openssl                   1.1.1g               h1de35cc_0    anaconda
opt-einsum                3.3.0                    pypi_0    pypi
outdated                  0.2.0                    pypi_0    pypi
packaging                 19.0                     py37_0    defaults
pandas                    0.24.2           py37h0a44026_0    defaults
pandas-datareader         0.7.0                    pypi_0    pypi
pandoc                    2.2.3.2                       0    defaults
pandocfilters             1.4.2                    py37_1    defaults
parso                     0.3.4                    py37_0    defaults
partd                     0.3.10                   py37_1    defaults
path.py                   11.5.0                   py37_0    defaults
pathlib2                  2.3.3                    py37_0    defaults
pathos                    0.2.7                    pypi_0    pypi
patsy                     0.5.1                    py37_0    defaults
pcre                      8.43                 h0a44026_0    defaults
pep8                      1.7.1                    py37_0    defaults
pexpect                   4.6.0                    py37_0    defaults
pickleshare               0.7.5                    py37_0    defaults
pillow                    8.1.2                    pypi_0    pypi
pip                       21.0                     pypi_0    pypi
pipenv                    2020.11.15               pypi_0    pypi
pkginfo                   1.5.0.1                  py37_0    defaults
plac                      1.1.3                    pypi_0    pypi
plotly                    3.10.0                   pypi_0    pypi
pluggy                    0.9.0                    py37_0    defaults
ply                       3.11                     py37_0    defaults
pmdarima                  1.2.1                    pypi_0    pypi
pox                       0.2.9                    pypi_0    pypi
ppft                      1.6.6.3                  pypi_0    pypi
preshed                   3.0.2                    pypi_0    pypi
prometheus_client         0.6.0                    py37_0    defaults
prompt_toolkit            2.0.9                    py37_0    defaults
protobuf                  3.13.0                   pypi_0    pypi
psutil                    5.8.0                    pypi_0    pypi
ptyprocess                0.6.0                    py37_0    defaults
py                        1.8.0                    py37_0    defaults
py-lief                   0.9.0            py37h1413db1_2    defaults
py-xgboost                0.90             py37h0a44026_1    anaconda
pyasn1                    0.4.8                    pypi_0    pypi
pyasn1-modules            0.2.8                    pypi_0    pypi
pycode-similar            1.4                      pypi_0    pypi
pycodestyle               2.5.0                    py37_0    defaults
pycosat                   0.6.3            py37h1de35cc_0    defaults
pycparser                 2.19                     py37_0    defaults
pycrypto                  2.6.1            py37h1de35cc_9    defaults
pycurl                    7.43.0.2         py37ha12b0ac_0    defaults
pydantic                  1.8.1                    pypi_0    pypi
pydot                     1.4.1                    pypi_0    pypi
pyflakes                  2.1.1                    py37_0    defaults
pygments                  2.3.1                    py37_0    defaults
pylint                    2.3.1                    py37_0    defaults
pymongo                   3.11.3                   pypi_0    pypi
pyodbc                    4.0.26           py37h0a44026_0    defaults
pyopenssl                 19.0.0                   py37_0    defaults
pyparsing                 2.3.1                    py37_0    defaults
pyqt                      5.9.2            py37h655552a_2    defaults
pyrsistent                0.14.11          py37h1de35cc_0    defaults
pysocks                   1.6.8                    py37_0    defaults
pystan                    2.19.0.0                 pypi_0    pypi
pytables                  3.4.4            py37h13cba08_0    defaults
pytest                    4.3.1                    py37_0    defaults
pytest-arraydiff          0.3              py37h39e3cac_0    defaults
pytest-astropy            0.5.0                    py37_0    defaults
pytest-doctestplus        0.3.0                    py37_0    defaults
pytest-openfiles          0.3.2                    py37_0    defaults
pytest-remotedata         0.3.1                    py37_0    defaults
python                    3.7.3                h359304d_0    defaults
python-dateutil           2.8.0                    py37_0    defaults
python-graphviz           0.11                     pypi_0    pypi
python-libarchive-c       2.8                      py37_6    defaults
python.app                2                        py37_9    defaults
pytz                      2018.9                   py37_0    defaults
pywavelets                1.0.2            py37h1d22016_0    defaults
pyyaml                    5.1              py37h1de35cc_0    defaults
pyzmq                     18.0.0           py37h0a44026_0    defaults
qt                        5.9.7                h468cd18_1    defaults
qtawesome                 0.5.7                    py37_1    defaults
qtconsole                 4.4.3                    py37_0    defaults
qtpy                      1.7.0                    py37_1    defaults
readline                  7.0                  h1de35cc_5    defaults
requests                  2.25.1                   pypi_0    pypi
requests-oauthlib         1.3.0                    pypi_0    pypi
retrying                  1.3.3                    pypi_0    pypi
rope                      0.12.0                   py37_0    defaults
rsa                       4.6                      pypi_0    pypi
ruamel_yaml               0.15.46          py37h1de35cc_0    defaults
s3fs                      0.4.2                    pypi_0    pypi
s3transfer                0.3.4                    pypi_0    pypi
scikit-image              0.14.2           py37h0a44026_0    defaults
scikit-learn              0.20.3           py37h27c97d8_0    defaults
scipy                     1.2.1            py37h1410ff5_0    defaults
seaborn                   0.9.0                    py37_0    defaults
send2trash                1.5.0                    py37_0    defaults
setuptools                50.3.0                   pypi_0    pypi
setuptools-git            1.2                      pypi_0    pypi
simplegeneric             0.8.1                    py37_2    defaults
singledispatch            3.4.0.3                  py37_0    defaults
sip                       4.19.8           py37h0a44026_0    defaults
six                       1.12.0                   py37_0    defaults
snappy                    1.1.7                he62c110_3    defaults
snowballstemmer           1.2.1                    py37_0    defaults
sortedcollections         1.1.2                    py37_0    defaults
sortedcontainers          2.1.0                    py37_0    defaults
soupsieve                 1.8                      py37_0    defaults
spacy                     2.3.2                    pypi_0    pypi
sphinx                    1.8.5                    py37_0    defaults
sphinxcontrib             1.0                      py37_1    defaults
sphinxcontrib-websupport  1.1.0                    py37_1    defaults
spyder                    3.3.3                    py37_0    defaults
spyder-kernels            0.4.2                    py37_0    defaults
sqlalchemy                1.3.1            py37h1de35cc_0    defaults
sqlite                    3.27.2               ha441bb4_0    defaults
sqlparse                  0.4.1                    pypi_0    pypi
srsly                     1.0.2                    pypi_0    pypi
statsmodels               0.9.0            py37h1d22016_0    defaults
sympy                     1.3                      py37_0    defaults
tbb                       2020.0               h04f5b5a_0    anaconda
tblib                     1.3.2                    py37_0    defaults
tensorboard               2.3.0                    pypi_0    pypi
tensorboard-plugin-wit    1.7.0                    pypi_0    pypi
termcolor                 1.1.0                    pypi_0    pypi
terminado                 0.8.1                    py37_1    defaults
testpath                  0.4.2                    py37_0    defaults
thinc                     7.4.1                    pypi_0    pypi
tk                        8.6.8                ha441bb4_0    defaults
toolz                     0.9.0                    py37_0    defaults
tornado                   6.0.2            py37h1de35cc_0    defaults
tqdm                      4.54.1                   pypi_0    pypi
traitlets                 4.3.2                    py37_0    defaults
typing-extensions         3.7.4.3                  pypi_0    pypi
unicodecsv                0.14.1                   py37_0    defaults
unixodbc                  2.3.7                h1de35cc_0    defaults
urllib3                   1.26.4                   pypi_0    pypi
virtualenv                20.4.0                   pypi_0    pypi
virtualenv-clone          0.5.4                    pypi_0    pypi
wasabi                    0.8.0                    pypi_0    pypi
wcwidth                   0.1.7                    py37_0    defaults
webencodings              0.5.1                    py37_1    defaults
werkzeug                  0.14.1                   py37_0    defaults
wheel                     0.33.1                   py37_0    defaults
widgetsnbextension        3.4.2                    py37_0    defaults
wordcloud                 1.7.0                    pypi_0    pypi
wrapt                     1.11.1           py37h1de35cc_0    defaults
wurlitzer                 1.0.2                    py37_0    defaults
xlrd                      1.2.0                    py37_0    defaults
xlsxwriter                1.1.5                    py37_0    defaults
xlwings                   0.15.4                   py37_0    defaults
xlwt                      1.3.0                    py37_0    defaults
xz                        5.2.4                h1de35cc_4    defaults
yaml                      0.1.7                hc338f04_2    defaults
zarr                      2.6.1                    pypi_0    pypi
zeromq                    4.3.1                h0a44026_3    defaults
zict                      0.1.4                    py37_0    defaults
zipp                      3.3.0                    pypi_0    pypi
zlib                      1.2.11               h1de35cc_3    defaults
zstd                      1.3.7                h5bba6e5_0    defaults

```

</details>

**Comment by khanjan-vora** [comment]
Hello, today I got the same error. I found a way to solve it by deleting the config file. You can find it in the C drive > user > username (in windows)! The name of the file is "**.condarc**". My Anaconda Navigator runs perfectly file now. Hope it helps!

**Comment by coverton-usgs** [comment]
Thank you khanjan-vora I was beating my head against the wall on that and your solutions worked

**Comment by khanjan-vora** [comment]
> 
> 
> Thank you khanjan-vora I was beating my head against the wall on that and your solutions worked

Thank you :) Together learning & growing!

**Comment by drsanchikagupta** [comment]
@khanjan-vora Yes, I tried doing that. But deleting the .condarc did not work for me. So I deleted the entire anaconda3 folder from my system and installed it again. And it is working now.
