### ISSUE TITLE
Spyder won't open in Anaconda with this environment

### ISSUE THREAD

**Issue by jjsakon** [ContinuumIO/anaconda-issues#12346]
I've tried this on two computers now and get the same error on both. This environment was set up to specifically run one program: Mayavi brain plotting (https://docs.enthought.com/mayavi/mayavi/). The weird part is this environment used to work with Spyder just fine so I'm not sure what changed. Does this error message mean anything to anyone? Thanks.

## Main error
Application <b>spyder</b> launch may have produced errors.
## Traceback
```
Traceback (most recent call last):
  File "/Users/johnsakon/anaconda/envs/brainPlotEnv/lib/python3.5/site-packages/spyder/app/mainwindow.py", line 3093, in main
    mainwindow = run_spyder(app, options, args)
  File "/Users/johnsakon/anaconda/envs/brainPlotEnv/lib/python3.5/site-packages/spyder/app/mainwindow.py", line 2995, in run_spyder
    main.setup()
  File "/Users/johnsakon/anaconda/envs/brainPlotEnv/lib/python3.5/site-packages/spyder/app/mainwindow.py", line 911, in setup
    from spyder.plugins.variableexplorer import VariableExplorer
  File "/Users/johnsakon/anaconda/envs/brainPlotEnv/lib/python3.5/site-packages/spyder/plugins/variableexplorer.py", line 18, in <module>
    from spyder.widgets.variableexplorer.namespacebrowser import NamespaceBrowser
  File "/Users/johnsakon/anaconda/envs/brainPlotEnv/lib/python3.5/site-packages/spyder/widgets/variableexplorer/namespacebrowser.py", line 25, in <module>
    import ipykernel.pickleutil
  File "/Users/johnsakon/anaconda/envs/brainPlotEnv/lib/python3.5/site-packages/ipykernel/__init__.py", line 2, in <module>
    from .connect import *
  File "/Users/johnsakon/anaconda/envs/brainPlotEnv/lib/python3.5/site-packages/ipykernel/connect.py", line 13, in <module>
    from IPython.core.profiledir import ProfileDir
  File "/Users/johnsakon/anaconda/envs/brainPlotEnv/lib/python3.5/site-packages/IPython/__init__.py", line 55, in <module>
    from .terminal.embed import embed
  File "/Users/johnsakon/anaconda/envs/brainPlotEnv/lib/python3.5/site-packages/IPython/terminal/embed.py", line 16, in <module>
    from IPython.terminal.interactiveshell import TerminalInteractiveShell
  File "/Users/johnsakon/anaconda/envs/brainPlotEnv/lib/python3.5/site-packages/IPython/terminal/interactiveshell.py", line 32, in <module>
    from .debugger import TerminalPdb, Pdb
  File "/Users/johnsakon/anaconda/envs/brainPlotEnv/lib/python3.5/site-packages/IPython/terminal/debugger.py", line 6, in <module>
    from IPython.core.completer import IPCompleter
  File "/Users/johnsakon/anaconda/envs/brainPlotEnv/lib/python3.5/site-packages/IPython/core/completer.py", line 146, in <module>
    import jedi
  File "/Users/johnsakon/anaconda/envs/brainPlotEnv/lib/python3.5/site-packages/jedi/__init__.py", line 41, in <module>
    from jedi.api import Script, Interpreter, set_debug_function, \
  File "/Users/johnsakon/anaconda/envs/brainPlotEnv/lib/python3.5/site-packages/jedi/api/__init__.py", line 15, in <module>
    import parso
  File "/Users/johnsakon/anaconda/envs/brainPlotEnv/lib/python3.5/site-packages/parso/__init__.py", line 41, in <module>
    from parso.parser import ParserSyntaxError
  File "/Users/johnsakon/anaconda/envs/brainPlotEnv/lib/python3.5/site-packages/parso/parser.py", line 113
    node_map: Dict[str, type] = {}
            ^
SyntaxError: invalid syntax

```
## System information
```
platform: osx-64
version: 1.6.2
conda: 4.7.11
qt: 5.6.2
language: en
python: 2.7.13
os: Darwin;17.7.0;Darwin Kernel Version 17.7.0: Mon Aug 31 22:11:23 PDT 2020; root:xnu-4570.71.82.6~1/RELEASE_X86_64;x86_64;i386
pyqt: 5.6.0
```

**Comment by jjsakon** [comment]
If it helps this is the environment I'm importing:

name: brainPlotEnv
channels:
  - defaults
dependencies:
  - ca-certificates=2018.03.07=0
  - certifi=2018.8.24=py35_1
  - libcxx=4.0.1=hcfea43d_1
  - libcxxabi=4.0.1=hcfea43d_1
  - libedit=3.1.20170329=hb402a30_2
  - libffi=3.2.1=h475c297_4
  - ncurses=6.1=h0a44026_1
  - openssl=1.0.2p=h1de35cc_0
  - pip=10.0.1=py35_0
  - python=3.5.6=hc167b69_0
  - readline=7.0=h1de35cc_5
  - setuptools=40.2.0=py35_0
  - sqlite=3.25.3=ha441bb4_0
  - tk=8.6.8=ha441bb4_0
  - wheel=0.31.1=py35_0
  - xz=5.2.4=h1de35cc_4
  - zlib=1.2.11=h1de35cc_3
  - pip:
    - appnope==0.1.0
    - apptools==4.4.0
    - backports.shutil-get-terminal-size==1.0.0
    - configobj==5.0.6
    - decorator==4.3.0
    - envisage==4.7.0
    - gnureadline==6.3.8
    - ipython==4.2.0
    - ipython-genutils==0.2.0
    - mayavi==4.6.2
    - mne==0.17.0
    - numpy==1.15.4
    - pexpect==4.6.0
    - pickleshare==0.7.5
    - ptyprocess==0.6.0
    - pyface==6.0.0
    - pygments==2.3.0
    - pyqt5==5.11.3
    - pyqt5-sip==4.19.13
    - simplegeneric==0.8.1
    - six==1.11.0
    - traitlets==4.3.2
    - traits==4.6.0
    - traitsui==6.0.0
    - vtk==8.1.2

**Comment by csoja** [comment]
You did not share what version of Spyder you are running.  The system information lists Python 2.7 and a very old version of conda, but the error message and then your follow-on comment lists python 3.5.  It may be an issue with an unpinned dependency, where a newer version of the dependency adversely affected Spyder.  You might want to look into parso, jedi, and some of the others listed.  
Also, there is a conda command where you can roll back your environments - so if it was working at one point, you could attempt to roll back to that point. I believe the command is listed on the conda cheatsheet. https://docs.conda.io/projects/conda/en/latest/user-guide/cheatsheet.html

**Comment by jjsakon** [comment]
Hi Csoja. Thanks for the link to the rollback. Unfortunately I already tried uninstalling and reinstalling Anaconda multiple times (trying both a newer and older version) so probably can't do that now.

I've tried a number of different Spyder versions from 3.0 to 5.0. It seems to be a kernel-related issue since I eventually got 3.3.2 to open. However, jupyterlab also had a kernel issue so I tried googling around on how to make sure the right kernel is being selected. For Spyder I went to Preferences->Python interpreter and made sure to select the python that's within my env (/Users/sakon/.conda/envs/brainPlotEnv/bin/python3.5). 

However, when restarting the kernel with Spyder I get this  error message:
`Your Python environment or installation doesn't have the spyder‑kernels module or the right version of it installed. Without this module is not possible for Spyder to create a console for you.

You can install it by running in a system terminal:
conda install spyder‑kernels=0.*
or
pip install spyder‑kernels==0.* `

Running that from my env in the terminal didn't work though:
` File "/Users/sakon/.conda/envs/brainPlotEnv/lib/python3.5/site-packages/pip/_vendor/packaging/requirements.py", line 97, in __init__
    requirement_string[e.loc:e.loc + 8]))
pip._vendor.packaging.requirements.InvalidRequirement: Invalid requirement, parse error at "'â€‘kerne'" `

Plus, using conda list I can see spyder-kernels *is* already installed:
`spyder-kernels            1.9.2                     <pip>`

Maybe this all has something to do with installing Anaconda within Users/sakon on my mac instead of in base folder?

**Comment by robert99** [comment]
You have a mix of Python 2.7.13 and 3.5.6 still registered.
You could try to run first the conda program anaconda-clean to remove old install data and make sure you uninstall all previous anaconda versions.
