### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by abrahamsaragih** [ContinuumIO/anaconda-issues#12397]
### Actual Behavior

Error message appears on Anaconda Navigator start-up.

### Expected Behavior

After the start-up, the navigator should be opened normally.

### Steps to Reproduce

Every time I try to open the Anaconda Navigator.

##### Anaconda or Miniconda version:

Anaconda3-2020.11-Windows-x86_64
##### `conda info`

<details>

```
# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "C:\Users\user\anaconda3\lib\site-packages\conda\exceptions.py", line 1079, in __call__
        return func(*args, **kwargs)
      File "C:\Users\user\anaconda3\lib\site-packages\conda\cli\main.py", line 84, in _main
        exit_code = do_call(args, p)
      File "C:\Users\user\anaconda3\lib\site-packages\conda\cli\conda_argparse.py", line 81, in do_call
        module = import_module(relative_mod, __name__.rsplit('.', 1)[0])
      File "C:\Users\user\anaconda3\lib\importlib\__init__.py", line 127, in import_module
        return _bootstrap._gcd_import(name[level:], package, level)
      File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
      File "<frozen importlib._bootstrap>", line 991, in _find_and_load
      File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
      File "<frozen importlib._bootstrap_external>", line 783, in exec_module
      File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
      File "C:\Users\user\anaconda3\lib\site-packages\conda\cli\main_info.py", line 19, in <module>
        from ..core.index import _supplement_index_with_system
      File "C:\Users\user\anaconda3\lib\site-packages\conda\core\index.py", line 12, in <module>
        from .package_cache_data import PackageCacheData
      File "C:\Users\user\anaconda3\lib\site-packages\conda\core\package_cache_data.py", line 14, in <module>
        from .path_actions import CacheUrlAction, ExtractPackageAction
      File "C:\Users\user\anaconda3\lib\site-packages\conda\core\path_actions.py", line 13, in <module>
        from .envs_manager import get_user_environments_txt_file, register_env, unregister_env
      File "C:\Users\user\anaconda3\lib\site-packages\conda\core\envs_manager.py", line 11, in <module>
        from .prefix_data import PrefixData
      File "C:\Users\user\anaconda3\lib\site-packages\conda\core\prefix_data.py", line 26, in <module>
        from ..gateways.disk.create import write_as_json_to_file
      File "C:\Users\user\anaconda3\lib\site-packages\conda\gateways\disk\create.py", line 18, in <module>
        from .delete import path_is_clean, rm_rf
      File "C:\Users\user\anaconda3\lib\site-packages\conda\gateways\disk\delete.py", line 16, in <module>
        from .link import islink, lexists
      File "<frozen importlib._bootstrap>", line 991, in _find_and_load
      File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
      File "<frozen importlib._bootstrap_external>", line 779, in exec_module
      File "<frozen importlib._bootstrap_external>", line 911, in get_code
      File "<frozen importlib._bootstrap_external>", line 580, in _compile_bytecode
    ValueError: bad marshal data (unknown type code)

`$ C:\Users\user\anaconda3\Scripts\conda-script.py info`

```

</details>

##### `conda list --show-channel-urls`

<details>

```
Traceback (most recent call last):
  File "C:\Users\user\anaconda3\lib\site-packages\conda\exceptions.py", line 1079, in __call__
    return func(*args, **kwargs)
  File "C:\Users\user\anaconda3\lib\site-packages\conda\cli\main.py", line 84, in _main
    exit_code = do_call(args, p)
  File "C:\Users\user\anaconda3\lib\site-packages\conda\cli\conda_argparse.py", line 81, in do_call
    module = import_module(relative_mod, __name__.rsplit('.', 1)[0])
  File "C:\Users\user\anaconda3\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\user\anaconda3\lib\site-packages\conda\cli\main_list.py", line 14, in <module>
    from ..core.prefix_data import PrefixData
  File "C:\Users\user\anaconda3\lib\site-packages\conda\core\prefix_data.py", line 26, in <module>
    from ..gateways.disk.create import write_as_json_to_file
  File "C:\Users\user\anaconda3\lib\site-packages\conda\gateways\disk\create.py", line 18, in <module>
    from .delete import path_is_clean, rm_rf
  File "C:\Users\user\anaconda3\lib\site-packages\conda\gateways\disk\delete.py", line 16, in <module>
    from .link import islink, lexists
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 779, in exec_module
  File "<frozen importlib._bootstrap_external>", line 911, in get_code
  File "<frozen importlib._bootstrap_external>", line 580, in _compile_bytecode
ValueError: bad marshal data (unknown type code)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\user\anaconda3\Scripts\conda-script.py", line 12, in <module>
    sys.exit(main())
  File "C:\Users\user\anaconda3\lib\site-packages\conda\cli\main.py", line 152, in main
    return conda_exception_handler(_main, *args, **kwargs)
  File "C:\Users\user\anaconda3\lib\site-packages\conda\exceptions.py", line 1371, in conda_exception_handler
    return_value = exception_handler(func, *args, **kwargs)
  File "C:\Users\user\anaconda3\lib\site-packages\conda\exceptions.py", line 1082, in __call__
    return self.handle_exception(exc_val, exc_tb)
  File "C:\Users\user\anaconda3\lib\site-packages\conda\exceptions.py", line 1126, in handle_exception
    return self.handle_unexpected_exception(exc_val, exc_tb)
  File "C:\Users\user\anaconda3\lib\site-packages\conda\exceptions.py", line 1137, in handle_unexpected_exception
    self.print_unexpected_error_report(error_report)
  File "C:\Users\user\anaconda3\lib\site-packages\conda\exceptions.py", line 1207, in print_unexpected_error_report
    from .cli.main_info import get_env_vars_str, get_main_info_str
  File "C:\Users\user\anaconda3\lib\site-packages\conda\cli\main_info.py", line 19, in <module>
    from ..core.index import _supplement_index_with_system
  File "C:\Users\user\anaconda3\lib\site-packages\conda\core\index.py", line 12, in <module>
    from .package_cache_data import PackageCacheData
  File "C:\Users\user\anaconda3\lib\site-packages\conda\core\package_cache_data.py", line 14, in <module>
    from .path_actions import CacheUrlAction, ExtractPackageAction
  File "C:\Users\user\anaconda3\lib\site-packages\conda\core\path_actions.py", line 13, in <module>
    from .envs_manager import get_user_environments_txt_file, register_env, unregister_env
  File "C:\Users\user\anaconda3\lib\site-packages\conda\core\envs_manager.py", line 11, in <module>
    from .prefix_data import PrefixData
  File "C:\Users\user\anaconda3\lib\site-packages\conda\core\prefix_data.py", line 26, in <module>
    from ..gateways.disk.create import write_as_json_to_file
  File "C:\Users\user\anaconda3\lib\site-packages\conda\gateways\disk\create.py", line 18, in <module>
    from .delete import path_is_clean, rm_rf
  File "C:\Users\user\anaconda3\lib\site-packages\conda\gateways\disk\delete.py", line 16, in <module>
    from .link import islink, lexists
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 779, in exec_module
  File "<frozen importlib._bootstrap_external>", line 911, in get_code
  File "<frozen importlib._bootstrap_external>", line 580, in _compile_bytecode
ValueError: bad marshal data (unknown type code)


```

</details>

**Comment by abrahamsaragih** [comment]
Solved
