### ISSUE TITLE
Windows 10 unexpected error when launching anaconda navigator

### ISSUE THREAD

**Issue by Gargoyle001** [ContinuumIO/anaconda-issues#12432]
### Actual Behavior

When launching anaconda an error occurs

### Steps to Reproduce

uninstalling all python versions on computer, installing python 3.9. then uninstalling anaconda and re-installing it. 
following some troubleshooting guidelines, last step was anaconda-navigator --reset

##### Anaconda or Miniconda version:
Anaconda3-2021.05-Windows-x86_64

##### `conda info`
Navigator Error
An unexpected error occurred on Navigator start-up

Report
Please report this issue in the anaconda issue tracker

Main Error
C:\Users\danie\.continuum\anaconda-client\config.yaml: Permission denied
Traceback
Traceback (most recent call last):
  File "C:\Users\danie\anaconda3\lib\site-packages\binstar_client\utils\config.py", line 275, in save_config
    with open(config_file, 'w') as fd:
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\danie\\.continuum\\anaconda-client\\config.yaml'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\danie\anaconda3\lib\site-packages\anaconda_navigator\exceptions.py", line 72, in exception_handler
    return_value = func(*args, **kwargs)
  File "C:\Users\danie\anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 146, in start_app
    window = run_app(splash)
  File "C:\Users\danie\anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 65, in run_app
    window = MainWindow(splash=splash)
  File "C:\Users\danie\anaconda3\lib\site-packages\anaconda_navigator\widgets\main_window.py", line 165, in __init__
    self.api = AnacondaAPI()
  File "C:\Users\danie\anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 1518, in AnacondaAPI
    ANACONDA_API = _AnacondaAPI()
  File "C:\Users\danie\anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 83, in __init__
    self._client_api = ClientAPI(config=self.config)
  File "C:\Users\danie\anaconda3\lib\site-packages\anaconda_navigator\api\client_api.py", line 659, in ClientAPI
    CLIENT_API = _ClientAPI(config=config)
  File "C:\Users\danie\anaconda3\lib\site-packages\anaconda_navigator\api\client_api.py", line 95, in __init__
    self.reload_client()
  File "C:\Users\danie\anaconda3\lib\site-packages\anaconda_navigator\api\client_api.py", line 325, in reload_client
    client = self._load_binstar_client(url)
  File "C:\Users\danie\anaconda3\lib\site-packages\anaconda_navigator\api\client_api.py", line 357, in _load_binstar_client
    binstar_client.utils.set_config(config)
  File "C:\Users\danie\anaconda3\lib\site-packages\binstar_client\utils\config.py", line 283, in set_config
    save_config(data, USER_CONFIG if user else SYSTEM_CONFIG)
  File "C:\Users\danie\anaconda3\lib\site-packages\binstar_client\utils\config.py", line 278, in save_config
    raise BinstarError('%s: %s' % (exc.filename, exc.strerror,))
binstar_client.errors.BinstarError: C:\Users\danie\.continuum\anaconda-client\config.yaml: Permission denied

**Comment by Dishant-01** [comment]
even I am facing this issue since morning.
there is some sort  of bug in update i guess

**Comment by titand98** [comment]
Thanks to you. It's working now

**Comment by malekaburaddaha** [comment]
where do you find that file?
Whenever I open that path it says that it cannot find it and I need to check the spelling
