### ISSUE TITLE
TensorFlow ImportError

### ISSUE THREAD

**Issue by yinqihuang** [ContinuumIO/anaconda-issues#12436]
**System information:**
- OS Platform: windows version 20h2
- Python version: 3.7.7

**Trying to run python in terminal, already done:**

`(base) C:\Users\Yinqi\trRosetta2\trRosetta>conda create -n tf tensorflow`

**But ran into this error:**

`ImportError: DLL load failed: The specified module could not be found. Failed to load the native TensorFlow runtime.`

**Full traceback:**
```
File "C:\Users\Yinqi\anaconda3\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 64, in <module>
        from tensorflow.python._pywrap_tensorflow_internal import *
    ImportError: DLL load failed: The specified module could not be found.
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "predict.py", line 6, in <module>
        import tensorflow as tf
      File "C:\Users\Yinqi\anaconda3\lib\site-packages\tensorflow\__init__.py", line 41, in <module>
        from tensorflow.python.tools import module_util as _module_util
      File "C:\Users\Yinqi\anaconda3\lib\site-packages\tensorflow\python\__init__.py", line 40, in <module>
        from tensorflow.python.eager import context
      File "C:\Users\Yinqi\anaconda3\lib\site-packages\tensorflow\python\eager\context.py", line 35, in <module>
        from tensorflow.python import pywrap_tfe
      File "C:\Users\Yinqi\anaconda3\lib\site-packages\tensorflow\python\pywrap_tfe.py", line 28, in <module>
        from tensorflow.python import pywrap_tensorflow
      File "C:\Users\Yinqi\anaconda3\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 83, in <module>
        raise ImportError(msg)
    ImportError: Traceback (most recent call last):
      File "C:\Users\Yinqi\anaconda3\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 64, in <module>
        from tensorflow.python._pywrap_tensorflow_internal import *
    ImportError: DLL load failed: The specified module could not be found.
```

**Comment by csoja** [comment]
Which version of tensorflow do you have installed? Please include the details requested in the issue template - the list of what is installed in your current environment and your conda configuration is critical to be able to provide any help.

**Comment by yinqihuang** [comment]
It seems that my computer doesn't have the cpu that supports avx
