### ISSUE TITLE
anaconda navigator

### ISSUE THREAD

**Issue by wenqiu24** [ContinuumIO/anaconda-issues#12435]
Navigator Error
An unexpected error occurred on Navigator start-up

Report
Please report this issue in the anaconda issue tracker

Main Error
check_hostname requires server_hostname
Traceback
Traceback (most recent call last):
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 142, in start_app
    with lock.acquire(timeout=3.0):  # timeout in seconds
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\anaconda_navigator\external\filelock.py", line 246, in acquire
    raise Timeout(self._lock_file)
anaconda_navigator.external.filelock.Timeout: The file lock 'C:\Users\Administrator\AppData\Roaming\.anaconda\navigator\.anaconda\navigator\navigator.lock' could not be acquired.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\anaconda_navigator\exceptions.py", line 72, in exception_handler
    return_value = func(*args, **kwargs)
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 152, in start_app
    msgbox = MessageBoxInformation(
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\anaconda_navigator\widgets\dialogs\__init__.py", line 521, in __init__
    super(MessageBoxInformation, self).__init__(
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\anaconda_navigator\widgets\dialogs\__init__.py", line 345, in __init__
    self.tracker = GATracker()
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\anaconda_navigator\utils\analytics.py", line 265, in GATracker
    GA_TRACKER = _GATracker()
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\anaconda_navigator\utils\analytics.py", line 103, in __init__
    self.api = AnacondaAPI()
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 1518, in AnacondaAPI
    ANACONDA_API = _AnacondaAPI()
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 83, in __init__
    self._client_api = ClientAPI(config=self.config)
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\anaconda_navigator\api\client_api.py", line 659, in ClientAPI
    CLIENT_API = _ClientAPI(config=config)
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\anaconda_navigator\api\client_api.py", line 95, in __init__
    self.reload_client()
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\anaconda_navigator\api\client_api.py", line 326, in reload_client
    client.user()
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\binstar_client\__init__.py", line 244, in user
    res = self.session.get(url, verify=self.session.verify)
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\requests\sessions.py", line 555, in get
    return self.request('GET', url, **kwargs)
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\requests\sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\requests\sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\requests\adapters.py", line 439, in send
    resp = conn.urlopen(
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\urllib3\connectionpool.py", line 696, in urlopen
    self._prepare_proxy(conn)
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\urllib3\connectionpool.py", line 964, in _prepare_proxy
    conn.connect()
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\urllib3\connection.py", line 359, in connect
    conn = self._connect_tls_proxy(hostname, conn)
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\urllib3\connection.py", line 500, in _connect_tls_proxy
    return ssl_wrap_socket(
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\urllib3\util\ssl_.py", line 432, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls)
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\urllib3\util\ssl_.py", line 474, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock)
  File "C:\Users\Administrator\Anaconda3\lib\ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "C:\Users\Administrator\Anaconda3\lib\ssl.py", line 997, in _create
    raise ValueError("check_hostname requires server_hostname")
ValueError: check_hostname requires server_hostname

**Comment by hussain-awan** [comment]
I also have this kind of error
So how did you solve it?
