### ISSUE TITLE
Navigation Error - C:\Users\.continuum\anaconda-client\config.yaml: Permission denied

### ISSUE THREAD

**Issue by sidkadam69** [ContinuumIO/anaconda-issues#12453]
Navigator Error
An unexpected error occurred on Navigator start-up

Report
Please report this issue in the anaconda issue tracker

Main Error
C:\Users\.continuum\anaconda-client\config.yaml: Permission denied
Traceback
Traceback (most recent call last):
  File "C:\Users\Anaconda3\lib\site-packages\binstar_client\utils\config.py", line 275, in save_config
    with open(config_file, 'w') as fd:
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\\.continuum\\anaconda-client\\config.yaml'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Anaconda3\lib\site-packages\anaconda_navigator\exceptions.py", line 72, in exception_handler
    return_value = func(*args, **kwargs)
  File "C:\Users\Anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 146, in start_app
    window = run_app(splash)
  File "C:\Users\Anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 65, in run_app
    window = MainWindow(splash=splash)
  File "C:\Users\Anaconda3\lib\site-packages\anaconda_navigator\widgets\main_window.py", line 165, in __init__
    self.api = AnacondaAPI()
  File "C:\Users\Anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 1518, in AnacondaAPI
    ANACONDA_API = _AnacondaAPI()
  File "C:\Users\Anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 83, in __init__
    self._client_api = ClientAPI(config=self.config)
  File "C:\Users\Anaconda3\lib\site-packages\anaconda_navigator\api\client_api.py", line 659, in ClientAPI
    CLIENT_API = _ClientAPI(config=config)
  File "C:\Users\Anaconda3\lib\site-packages\anaconda_navigator\api\client_api.py", line 95, in __init__
    self.reload_client()
  File "C:\Users\Anaconda3\lib\site-packages\anaconda_navigator\api\client_api.py", line 325, in reload_client
    client = self._load_binstar_client(url)
  File "C:\Users\Anaconda3\lib\site-packages\anaconda_navigator\api\client_api.py", line 357, in _load_binstar_client
    binstar_client.utils.set_config(config)
  File "C:\Users\Anaconda3\lib\site-packages\binstar_client\utils\config.py", line 283, in set_config
    save_config(data, USER_CONFIG if user else SYSTEM_CONFIG)
  File "C:\Users\Anaconda3\lib\site-packages\binstar_client\utils\config.py", line 278, in save_config
    raise BinstarError('%s: %s' % (exc.filename, exc.strerror,))
binstar_client.errors.BinstarError: C:\Users\.continuum\anaconda-client\config.yaml: Permission denied

**Comment by om-hb** [comment]
I get exactly the same error message!

<details>

```
Traceback (most recent call last):
  File "C:\Users\XXX\Anaconda3\lib\site-packages\binstar_client\utils\config.py", line 275, in save_config
    with open(config_file, 'w') as fd:
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\XXX\\.continuum\\anaconda-client\\config.yaml'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\XXX\Anaconda3\lib\site-packages\anaconda_navigator\exceptions.py", line 72, in exception_handler
    return_value = func(*args, **kwargs)
  File "C:\Users\XXX\Anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 146, in start_app
    window = run_app(splash)
  File "C:\Users\XXX\Anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 65, in run_app
    window = MainWindow(splash=splash)
  File "C:\Users\XXX\Anaconda3\lib\site-packages\anaconda_navigator\widgets\main_window.py", line 165, in __init__
    self.api = AnacondaAPI()
  File "C:\Users\XXX\Anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 1518, in AnacondaAPI
    ANACONDA_API = _AnacondaAPI()
  File "C:\Users\XXX\Anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 83, in __init__
    self._client_api = ClientAPI(config=self.config)
  File "C:\Users\XXX\Anaconda3\lib\site-packages\anaconda_navigator\api\client_api.py", line 659, in ClientAPI
    CLIENT_API = _ClientAPI(config=config)
  File "C:\Users\XXX\Anaconda3\lib\site-packages\anaconda_navigator\api\client_api.py", line 95, in __init__
    self.reload_client()
  File "C:\Users\XXX\Anaconda3\lib\site-packages\anaconda_navigator\api\client_api.py", line 325, in reload_client
    client = self._load_binstar_client(url)
  File "C:\Users\XXX\Anaconda3\lib\site-packages\anaconda_navigator\api\client_api.py", line 357, in _load_binstar_client
    binstar_client.utils.set_config(config)
  File "C:\Users\XXX\Anaconda3\lib\site-packages\binstar_client\utils\config.py", line 283, in set_config
    save_config(data, USER_CONFIG if user else SYSTEM_CONFIG)
  File "C:\Users\XXX\Anaconda3\lib\site-packages\binstar_client\utils\config.py", line 278, in save_config
    raise BinstarError('%s: %s' % (exc.filename, exc.strerror,))
binstar_client.errors.BinstarError: C:\Users\XXX\.continuum\anaconda-client\config.yaml: Permission denied
```
</details>

##### Anaconda or Miniconda version:

2020.11

##### Operating System:

Windows 10 64bit

##### conda info:


<details>

```
     active environment : base
    active env location : C:\Users\XXX\Anaconda3
            shell level : 1
       user config file : C:\Users\XXX\.condarc
 populated config files : C:\Users\XXX\.condarc
          conda version : 4.10.3
    conda-build version : 3.20.5
         python version : 3.8.5.final.0
       virtual packages : __cuda=11.3=0
                          __win=0=0
                          __archspec=1=x86_64
       base environment : C:\Users\XXX\anaconda3  (writable)
      conda av data dir : C:\Users\XXX\anaconda3\etc\conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/anaconda-fusion/win-64
                          https://conda.anaconda.org/anaconda-fusion/noarch
                          https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\Users\XXX\anaconda3\pkgs
                          C:\Users\XXX\.conda\pkgs
                          C:\Users\XXX\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\XXX\anaconda3\envs
                          C:\Users\XXX\.conda\envs
                          C:\Users\XXX\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.10.3 requests/2.24.0 CPython/3.8.5 Windows/10 Windows/10.0.19041
          administrator : False
             netrc file : None
           offline mode : False

```
</details>

**Comment by om-hb** [comment]
Could fix the issue by manually deleting the _anaconda-client_ folder as mentioned in #1238.
