### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by Kwirayasa72** [ContinuumIO/anaconda-issues#12471]
### Actual Behavior

 An unexpected error occurred on Navigator start-up

##### `conda info`

<details>

```
PASTE OUTPUT HERE:

```

</details>

##### `conda list --show-channel-urls`

<details>

```
PASTE OUTPUT HERE:

```

</details>

**Comment by Kwirayasa72** [comment]
Navigator Error

An unexpected error occurred on Navigator start-up

Report

Please report this issue in the anaconda  issue tracker  


Main Error

check_hostname requires server_hostname


Traceback

Traceback (most recent call last):
  File "C:\Users\Wirayasa\anaconda3\lib\site-packages\anaconda_navigator\exceptions.py", line 72, in exception_handler
    return_value = func(*args, **kwargs)
  File "C:\Users\Wirayasa\anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 146, in start_app
    window = run_app(splash)
  File "C:\Users\Wirayasa\anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 65, in run_app
    window = MainWindow(splash=splash)
  File "C:\Users\Wirayasa\anaconda3\lib\site-packages\anaconda_navigator\widgets\main_window.py", line 165, in __init__
    self.api = AnacondaAPI()
