### ISSUE TITLE
I cannot run Anaconda Navigator

### ISSUE THREAD

**Issue by aldirhmn** [ContinuumIO/anaconda-issues#12491]
Navigator Error
An unexpected error occurred on Navigator start-up

Report
Please report this issue in the anaconda issue tracker

**Main Error**
An unexpected error occurred on Navigator start-up<br>unacceptable character #x0000: special characters are not allowed
  in "C:\Users\aldir\.continuum\anaconda-client\config.yaml", position 0
Traceback (most recent call last):
  File "C:\Users\aldir\anaconda3\lib\site-packages\anaconda_navigator\exceptions.py", line 72, in exception_handler
    return_value = func(*args, **kwargs)
  File "C:\Users\aldir\anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 146, in start_app
    window = run_app(splash)
  File "C:\Users\aldir\anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 65, in run_app
    window = MainWindow(splash=splash)
  File "C:\Users\aldir\anaconda3\lib\site-packages\anaconda_navigator\widgets\main_window.py", line 165, in __init__
    self.api = AnacondaAPI()
  File "C:\Users\aldir\anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 1518, in AnacondaAPI
    ANACONDA_API = _AnacondaAPI()
  File "C:\Users\aldir\anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 83, in __init__
    self._client_api = ClientAPI(config=self.config)
  File "C:\Users\aldir\anaconda3\lib\site-packages\anaconda_navigator\api\client_api.py", line 659, in ClientAPI
    CLIENT_API = _ClientAPI(config=config)
  File "C:\Users\aldir\anaconda3\lib\site-packages\anaconda_navigator\api\client_api.py", line 95, in __init__
    self.reload_client()
  File "C:\Users\aldir\anaconda3\lib\site-packages\anaconda_navigator\api\client_api.py", line 322, in reload_client
    url = binstar_client.utils.get_config()['url']
  File "C:\Users\aldir\anaconda3\lib\site-packages\binstar_client\utils\config.py", line 249, in get_config
    file_configs = load_file_configs(SEARCH_PATH)
  File "C:\Users\aldir\anaconda3\lib\site-packages\binstar_client\utils\config.py", line 241, in load_file_configs
    raw_data = collections.OrderedDict(kv for kv in itertools.chain.from_iterable(load_paths))
  File "C:\Users\aldir\anaconda3\lib\site-packages\binstar_client\utils\config.py", line 241, in <genexpr>
    raw_data = collections.OrderedDict(kv for kv in itertools.chain.from_iterable(load_paths))
  File "C:\Users\aldir\anaconda3\lib\site-packages\binstar_client\utils\config.py", line 221, in _dir_yaml_loader
    yield filepath, load_config(filepath)
  File "C:\Users\aldir\anaconda3\lib\site-packages\binstar_client\utils\config.py", line 205, in load_config
    data = yaml_load(fd)
  File "C:\Users\aldir\anaconda3\lib\site-packages\binstar_client\utils\yaml.py", line 12, in yaml_load
    return safe_load(stream)
  File "C:\Users\aldir\anaconda3\lib\site-packages\yaml\__init__.py", line 162, in safe_load
    return load(stream, SafeLoader)
  File "C:\Users\aldir\anaconda3\lib\site-packages\yaml\__init__.py", line 112, in load
    loader = Loader(stream)
  File "C:\Users\aldir\anaconda3\lib\site-packages\yaml\loader.py", line 34, in __init__
    Reader.__init__(self, stream)
  File "C:\Users\aldir\anaconda3\lib\site-packages\yaml\reader.py", line 85, in __init__
    self.determine_encoding()
  File "C:\Users\aldir\anaconda3\lib\site-packages\yaml\reader.py", line 135, in determine_encoding
    self.update(1)
  File "C:\Users\aldir\anaconda3\lib\site-packages\yaml\reader.py", line 169, in update
    self.check_printable(data)
  File "C:\Users\aldir\anaconda3\lib\site-packages\yaml\reader.py", line 143, in check_printable
    raise ReaderError(self.name, position, ord(character),
yaml.reader.ReaderError: unacceptable character #x0000: special characters are not allowed
  in "C:\Users\aldir\.continuum\anaconda-client\config.yaml", position 0

Actual Behavior

Got this error Massage!

Expected Behavior

Expected navigator to start

Steps to Reproduce

repeat
E:\Anaconda3\pythonw.exe E:\Anaconda3\cwp.py E:\Anaconda3 E:\Anaconda3\pythonw.exe E:\Anaconda3\Scripts\anaconda-navigator-script.py

 Anaconda or Miniconda version:
5.1.0

Operating System:
windows 10

##### `conda info`

<details>

```
 active environment : None
       user config file : C:\Users\aldir\.condarc
 populated config files : C:\Users\aldir\.condarc
          conda version : 4.10.1
    conda-build version : 3.21.4
         python version : 3.8.8.final.0
       virtual packages : __cuda=11.0=0
                          __win=0=0
                          __archspec=1=x86_64
       base environment : C:\Users\aldir\anaconda3  (writable)
      conda av data dir : C:\Users\aldir\anaconda3\etc\conda
  conda av metadata url : https://repo.anaconda.com/pkgs/main
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\Users\aldir\anaconda3\pkgs
                          C:\Users\aldir\.conda\pkgs
                          C:\Users\aldir\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\aldir\anaconda3\envs
                          C:\Users\aldir\.conda\envs
                          C:\Users\aldir\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.10.1 requests/2.25.1 CPython/3.8.8 Windows/10 Windows/10.0.19041
          administrator : False
             netrc file : None
           offline mode : False

```

</details>

##### `conda list --show-channel-urls`

<details>

```
An unexpected error occurred on Navigator start-up<br>unacceptable character #x0000: special characters are not allowed
  in "C:\Users\aldir\.continuum\anaconda-client\config.yaml", position 0
Traceback (most recent call last):
  File "C:\Users\aldir\anaconda3\lib\site-packages\anaconda_navigator\exceptions.py", line 72, in exception_handler
    return_value = func(*args, **kwargs)
  File "C:\Users\aldir\anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 146, in start_app
    window = run_app(splash)
  File "C:\Users\aldir\anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 65, in run_app
    window = MainWindow(splash=splash)
  File "C:\Users\aldir\anaconda3\lib\site-packages\anaconda_navigator\widgets\main_window.py", line 165, in __init__
    self.api = AnacondaAPI()
  File "C:\Users\aldir\anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 1518, in AnacondaAPI
    ANACONDA_API = _AnacondaAPI()
  File "C:\Users\aldir\anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 83, in __init__
    self._client_api = ClientAPI(config=self.config)
  File "C:\Users\aldir\anaconda3\lib\site-packages\anaconda_navigator\api\client_api.py", line 659, in ClientAPI
    CLIENT_API = _ClientAPI(config=config)
  File "C:\Users\aldir\anaconda3\lib\site-packages\anaconda_navigator\api\client_api.py", line 95, in __init__
    self.reload_client()
  File "C:\Users\aldir\anaconda3\lib\site-packages\anaconda_navigator\api\client_api.py", line 322, in reload_client
    url = binstar_client.utils.get_config()['url']
  File "C:\Users\aldir\anaconda3\lib\site-packages\binstar_client\utils\config.py", line 249, in get_config
    file_configs = load_file_configs(SEARCH_PATH)
  File "C:\Users\aldir\anaconda3\lib\site-packages\binstar_client\utils\config.py", line 241, in load_file_configs
    raw_data = collections.OrderedDict(kv for kv in itertools.chain.from_iterable(load_paths))
  File "C:\Users\aldir\anaconda3\lib\site-packages\binstar_client\utils\config.py", line 241, in <genexpr>
    raw_data = collections.OrderedDict(kv for kv in itertools.chain.from_iterable(load_paths))
  File "C:\Users\aldir\anaconda3\lib\site-packages\binstar_client\utils\config.py", line 221, in _dir_yaml_loader
    yield filepath, load_config(filepath)
  File "C:\Users\aldir\anaconda3\lib\site-packages\binstar_client\utils\config.py", line 205, in load_config
    data = yaml_load(fd)
  File "C:\Users\aldir\anaconda3\lib\site-packages\binstar_client\utils\yaml.py", line 12, in yaml_load
    return safe_load(stream)
  File "C:\Users\aldir\anaconda3\lib\site-packages\yaml\__init__.py", line 162, in safe_load
    return load(stream, SafeLoader)
  File "C:\Users\aldir\anaconda3\lib\site-packages\yaml\__init__.py", line 112, in load
    loader = Loader(stream)
  File "C:\Users\aldir\anaconda3\lib\site-packages\yaml\loader.py", line 34, in __init__
    Reader.__init__(self, stream)
  File "C:\Users\aldir\anaconda3\lib\site-packages\yaml\reader.py", line 85, in __init__
    self.determine_encoding()
  File "C:\Users\aldir\anaconda3\lib\site-packages\yaml\reader.py", line 135, in determine_encoding
    self.update(1)
  File "C:\Users\aldir\anaconda3\lib\site-packages\yaml\reader.py", line 169, in update
    self.check_printable(data)
  File "C:\Users\aldir\anaconda3\lib\site-packages\yaml\reader.py", line 143, in check_printable
    raise ReaderError(self.name, position, ord(character),
yaml.reader.ReaderError: unacceptable character #x0000: special characters are not allowed
  in "C:\Users\aldir\.continuum\anaconda-client\config.yaml", position 0


```

</details>

**Comment by remkade** [comment]
It looks like you have a null byte as the first character in your config.yaml. Do you know if that file has been edited?

**Comment by aldirhmn** [comment]
> 
> 
> It looks like you have a null byte as the first character in your config.yaml. Do you know if that file has been edited?

I dont know config.yaml should be edited and i think i never edit that file. Ive already update my conda and nothing happen, can u help me?

**Comment by csoja** [comment]
I'd backup the file (C:\Users\aldir.continuum\anaconda-client\config.yaml) under a different name and then delete it and attempt to run Navigator again.

**Comment by Vasanthagokul** [comment]
That last comment by @csoja worked for me
