### ISSUE TITLE
Spyder will not run on conda

### ISSUE THREAD

**Issue by zkubin** [ContinuumIO/anaconda-issues#12495]
##### `conda info`

<details>

```
 File "C:\Users\moond\Desktop\New folder\lib\site-packages\conda\gateways\logging.py", line 134, in emit
    stream.write(ufs % msg)
  File "C:\Users\moond\Desktop\New folder\lib\site-packages\colorama\ansitowin32.py", line 41, in write
    self.__convertor.write(text)
  File "C:\Users\moond\Desktop\New folder\lib\site-packages\colorama\ansitowin32.py", line 162, in write
    self.write_and_convert(text)
  File "C:\Users\moond\Desktop\New folder\lib\site-packages\colorama\ansitowin32.py", line 190, in write_and_convert
    self.write_plain_text(text, cursor, len(text))
  File "C:\Users\moond\Desktop\New folder\lib\site-packages\colorama\ansitowin32.py", line 195, in write_plain_text
    self.wrapped.write(text[start:end])
LookupError: unknown encoding: cp65001
Logged from file main_info.py, line 318
Traceback (most recent call last):
  File "C:\Users\moond\Desktop\New folder\lib\site-packages\conda\gateways\logging.py", line 134, in emit
    stream.write(ufs % msg)
  File "C:\Users\moond\Desktop\New folder\lib\site-packages\colorama\ansitowin32.py", line 41, in write
    self.__convertor.write(text)
  File "C:\Users\moond\Desktop\New folder\lib\site-packages\colorama\ansitowin32.py", line 162, in write
    self.write_and_convert(text)
  File "C:\Users\moond\Desktop\New folder\lib\site-packages\colorama\ansitowin32.py", line 190, in write_and_convert
    self.write_plain_text(text, cursor, len(text))
  File "C:\Users\moond\Desktop\New folder\lib\site-packages\colorama\ansitowin32.py", line 195, in write_plain_text
    self.wrapped.write(text[start:end])
LookupError: unknown encoding: cp65001
Logged from file main_info.py, line 319

```

</details>

##### `conda list --show-channel-urls`

<details>

```
 Traceback (most recent call last):
  File "C:\Users\moond\Desktop\New folder\lib\site-packages\conda\gateways\logging.py", line 134, in emit
    stream.write(ufs % msg)
  File "C:\Users\moond\Desktop\New folder\lib\site-packages\colorama\ansitowin32.py", line 41, in write
    self.__convertor.write(text)
  File "C:\Users\moond\Desktop\New folder\lib\site-packages\colorama\ansitowin32.py", line 162, in write
    self.write_and_convert(text)
  File "C:\Users\moond\Desktop\New folder\lib\site-packages\colorama\ansitowin32.py", line 190, in write_and_convert
    self.write_plain_text(text, cursor, len(text))
  File "C:\Users\moond\Desktop\New folder\lib\site-packages\colorama\ansitowin32.py", line 195, in write_plain_text
    self.wrapped.write(text[start:end])
LookupError: unknown encoding: cp65001
Logged from file exceptions.py, line 1088
Traceback (most recent call last):
  File "C:\Users\moond\Desktop\New folder\lib\site-packages\conda\gateways\logging.py", line 134, in emit
    stream.write(ufs % msg)
  File "C:\Users\moond\Desktop\New folder\lib\site-packages\colorama\ansitowin32.py", line 41, in write
    self.__convertor.write(text)
  File "C:\Users\moond\Desktop\New folder\lib\site-packages\colorama\ansitowin32.py", line 162, in write
    self.write_and_convert(text)
  File "C:\Users\moond\Desktop\New folder\lib\site-packages\colorama\ansitowin32.py", line 190, in write_and_convert
    self.write_plain_text(text, cursor, len(text))
  File "C:\Users\moond\Desktop\New folder\lib\site-packages\colorama\ansitowin32.py", line 195, in write_plain_text
    self.wrapped.write(text[start:end])
LookupError: unknown encoding: cp65001
Logged from file exceptions.py, line 1088
Traceback (most recent call last):
  File "C:\Users\moond\Desktop\New folder\lib\site-packages\conda\gateways\logging.py", line 134, in emit
    stream.write(ufs % msg)
  File "C:\Users\moond\Desktop\New folder\lib\site-packages\colorama\ansitowin32.py", line 41, in write
    self.__convertor.write(text)
  File "C:\Users\moond\Desktop\New folder\lib\site-packages\colorama\ansitowin32.py", line 162, in write
    self.write_and_convert(text)
  File "C:\Users\moond\Desktop\New folder\lib\site-packages\colorama\ansitowin32.py", line 190, in write_and_convert
    self.write_plain_text(text, cursor, len(text))
  File "C:\Users\moond\Desktop\New folder\lib\site-packages\colorama\ansitowin32.py", line 195, in write_plain_text
    self.wrapped.write(text[start:end])
LookupError: unknown encoding: cp65001
Logged from file exceptions.py, line 1088

```

</details>

**Comment by zkubin** [comment]
I'm not sure why it doesn't show above, but I m trying to open spyder from Conda and it is not working.
