### ISSUE TITLE
pyarrow default compression (lz4) appears to be broken

### ISSUE THREAD

**Issue by johnholman** [ContinuumIO/anaconda-issues#12500]
### Actual Behavior

It seems that pyarrow when installed from the defaults channel or one of its dependencies has been created without support for lz4 compression.

For example saving a file with lz4 compression requested produces an error (by default this version is saving without any compression):

>>> import pandas as pd
>>> df = pd.read_csv('test.csv')
>>> df.to_feather('out.feather', compress='lz4')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\johng\miniconda3\envs\test1\lib\site-packages\pandas\util\_decorators.py", line 199, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\johng\miniconda3\envs\test1\lib\site-packages\pandas\core\frame.py", line 2291, in to_feather
    to_feather(self, path, **kwargs)
  File "C:\Users\johng\miniconda3\envs\test1\lib\site-packages\pandas\io\feather_format.py", line 80, in to_feather
    feather.write_feather(df, handles.handle, **kwargs)
TypeError: write_feather() got an unexpected keyword argument 'compress'
>>> df.to_feather('out.feather', compression='lz4')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\johng\miniconda3\envs\test1\lib\site-packages\pandas\util\_decorators.py", line 199, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\johng\miniconda3\envs\test1\lib\site-packages\pandas\core\frame.py", line 2291, in to_feather
    to_feather(self, path, **kwargs)
  File "C:\Users\johng\miniconda3\envs\test1\lib\site-packages\pandas\io\feather_format.py", line 80, in to_feather
    feather.write_feather(df, handles.handle, **kwargs)
  File "C:\Users\johng\miniconda3\envs\test1\lib\site-packages\pyarrow\feather.py", line 183, in write_feather
    ext.write_feather(table, dest, compression=compression,
  File "pyarrow\feather.pxi", line 51, in pyarrow.lib.write_feather
  File "pyarrow\error.pxi", line 118, in pyarrow.lib.check_status
pyarrow.lib.ArrowNotImplementedError: Support for codec 'lz4' not built
### Expected Behavior

Feather files with lz4 files should be written and read correctly - this is the default compression for pyarrow. 

Note - installation from conda-forge works correctly. 

### Steps to Reproduce
As above

##### Anaconda or Miniconda version:

Miniconda current version

##### Operating System:

Windows 10

##### `conda info`

<details>

```
     active environment : test1
    active env location : C:\Users\johng\miniconda3\envs\test1
            shell level : 2
       user config file : C:\Users\johng\.condarc
 populated config files : C:\Users\johng\miniconda3\.condarc
                          C:\Users\johng\.condarc
          conda version : 4.10.1
    conda-build version : not installed
         python version : 3.9.5.final.0
       virtual packages : __cuda=11.1=0
                          __win=0=0
                          __archspec=1=x86_64
       base environment : C:\Users\johng\miniconda3  (writable)
      conda av data dir : C:\Users\johng\miniconda3\etc\conda
  conda av metadata url : https://repo.anaconda.com/pkgs/main
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\Users\johng\miniconda3\pkgs
                          C:\Users\johng\.conda\pkgs
                          C:\Users\johng\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\johng\miniconda3\envs
                          C:\Users\johng\.conda\envs
                          C:\Users\johng\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.10.1 requests/2.25.1 CPython/3.9.5 Windows/10 Windows/10.0.19041
          administrator : False
             netrc file : None
           offline mode : False

```

</details>

##### `conda list --show-channel-urls`

<details>

```
# packages in environment at C:\Users\johng\miniconda3\envs\test1:
#
# Name                    Version                   Build  Channel
arrow-cpp                 4.0.1            py39h0d1d0e5_3    defaults
aws-c-common              0.4.57               ha925a31_1    defaults
aws-c-event-stream        0.1.6                hd77b12b_5    defaults
aws-checksums             0.1.9                ha925a31_0    defaults
aws-sdk-cpp               1.8.185              hd77b12b_0    defaults
blas                      1.0                         mkl    defaults
boost-cpp                 1.73.0              h2bbff1b_11    defaults
bottleneck                1.3.2            py39h7cc1a96_1    defaults
brotli                    1.0.9                ha925a31_2    defaults
bzip2                     1.0.8                he774522_0    defaults
c-ares                    1.17.1               h2bbff1b_0    defaults
ca-certificates           2021.5.25            haa95532_1    defaults
certifi                   2021.5.30        py39haa95532_0    defaults
cycler                    0.10.0           py39haa95532_0    defaults
double-conversion         3.1.5                ha925a31_1    defaults
freetype                  2.10.4               hd328e21_0    defaults
gflags                    2.2.2                ha925a31_0    defaults
glog                      0.5.0                hd77b12b_0    defaults
grpc-cpp                  1.26.0               h351948d_0    defaults
icc_rt                    2019.0.0             h0cc432a_1    defaults
icu                       58.2                 ha925a31_3    defaults
intel-openmp              2021.2.0           haa95532_616    defaults
jpeg                      9b                   hb83a4c4_2    defaults
kiwisolver                1.3.1            py39hd77b12b_0    defaults
krb5                      1.18.2               hc04afaa_0    defaults
libboost                  1.73.0              h6c2663c_11    defaults
libcurl                   7.71.1               h2a8f88b_1    defaults
libpng                    1.6.37               h2a8f88b_0    defaults
libprotobuf               3.11.2               h7bd577a_0    defaults
libssh2                   1.9.0                h7a1dbc1_1    defaults
libtiff                   4.2.0                hd0e1b90_0    defaults
lz4-c                     1.9.3                h2bbff1b_0    defaults
matplotlib                3.3.4            py39haa95532_0    defaults
matplotlib-base           3.3.4            py39h49ac443_0    defaults
mkl                       2021.2.0           haa95532_296    defaults
mkl-service               2.3.0            py39h2bbff1b_1    defaults
mkl_fft                   1.3.0            py39h277e83a_2    defaults
mkl_random                1.2.1            py39hf11a4ad_2    defaults
numexpr                   2.7.3            py39hb80d3ca_1    defaults
numpy                     1.20.2           py39ha4e8547_0    defaults
numpy-base                1.20.2           py39hc2deb75_0    defaults
olefile                   0.46                       py_0    defaults
openssl                   1.1.1k               h2bbff1b_0    defaults
pandas                    1.2.5            py39hd77b12b_0    defaults
pillow                    8.2.0            py39h4fa10fc_0    defaults
pip                       21.1.3           py39haa95532_0    defaults
pyarrow                   4.0.1            py39h953b917_3    defaults
pyparsing                 2.4.7              pyhd3eb1b0_0    defaults
pyqt                      5.9.2            py39hd77b12b_6    defaults
python                    3.9.5                h6244533_3    defaults
python-dateutil           2.8.1              pyhd3eb1b0_0    defaults
pytz                      2021.1             pyhd3eb1b0_0    defaults
qt                        5.9.7            vc14h73c81de_0    defaults
re2                       2020.11.01           hd77b12b_1    defaults
scipy                     1.6.2            py39h66253e8_1    defaults
setuptools                52.0.0           py39haa95532_0    defaults
sip                       4.19.13          py39hd77b12b_0    defaults
six                       1.16.0             pyhd3eb1b0_0    defaults
snappy                    1.1.8                h33f27b4_0    defaults
sqlite                    3.36.0               h2bbff1b_0    defaults
tk                        8.6.10               he774522_0    defaults
tornado                   6.1              py39h2bbff1b_0    defaults
tzdata                    2021a                h52ac0ba_0    defaults
uriparser                 0.9.3                h33f27b4_1    defaults
utf8proc                  2.6.1                h2bbff1b_0    defaults
vc                        14.2                 h21ff451_1    defaults
vs2015_runtime            14.27.29016          h5e58377_2    defaults
wheel                     0.36.2             pyhd3eb1b0_0    defaults
wincertstore              0.2              py39h2bbff1b_0    defaults
xz                        5.2.5                h62dcd97_0    defaults
zlib                      1.2.11               h62dcd97_4    defaults
zstd                      1.4.9                h19a0ad4_0    defaults

```

</details>

**Comment by jorisvandenbossche** [comment]
I think it is specifically missing on windows, see my comment at https://github.com/AnacondaRecipes/arrow-cpp-feedstock/commit/abd5c84f14d1972deac0691b6cca6c6f3df4f764

cc @katietz

**Comment by fleimgruber** [comment]
@jorisvandenbossche thanks for spotting and mentioning. What would be your recommended workaround here?

**Comment by jorisvandenbossche** [comment]
Use conda-forge ...

**Comment by douglasmacdonald** [comment]
Hi,

Using conda-forge without first installing lz4 did not work for me.

My current work around (don't know if first step 'uninstall' is necessary)

* > `mamba uninstall pyarrow`
* > `mamba install -c anaconda lz4`
* > `mamba install pyarrow -c conda-forge`

Good  luck

**Comment by gdementen** [comment]
Installing from conda-forge is a nice workaround. It helped me test feather with compression on some of our datasets (it rocks!) but I have had awful experiences mixing conda-forge packages in anaconda-based environments (basically making the environments impossible to update) so I am not ready to do this in production any time soon. In short, please fix this 😉.

**Comment by gdementen** [comment]
relevant issue: https://github.com/AnacondaRecipes/arrow-cpp-feedstock/issues/3
