### ISSUE TITLE
Navigator Error - permission denied

### ISSUE THREAD

**Issue by evaykl** [ContinuumIO/anaconda-issues#12523]
### Behavior

successfully installed Anaconda3-2021.05-MacOSX-x86_64.pkg. But when try to open the navigator (double click the navigator icon), the following error screen pop up (see Error Message).

I tried the solution at https://docs.anaconda.com/anaconda/navigator/troubleshooting/#access-denied-error 

not working

### Error Message
Main Error

/Users/liuyikun/.continuum/anaconda-client: Permission denied
Traceback

Traceback (most recent call last):
  File "/Users/liuyikun/opt/anaconda3/lib/python3.8/site-packages/binstar_client/utils/config.py", line 273, in save_config
    os.makedirs(data_dir)
  File "/Users/liuyikun/opt/anaconda3/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/Users/liuyikun/.continuum/anaconda-client'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/liuyikun/opt/anaconda3/lib/python3.8/site-packages/anaconda_navigator/exceptions.py", line 72, in exception_handler
    return_value = func(*args, **kwargs)
  File "/Users/liuyikun/opt/anaconda3/lib/python3.8/site-packages/anaconda_navigator/app/start.py", line 146, in start_app
    window = run_app(splash)
  File "/Users/liuyikun/opt/anaconda3/lib/python3.8/site-packages/anaconda_navigator/app/start.py", line 65, in run_app
    window = MainWindow(splash=splash)
  File "/Users/liuyikun/opt/anaconda3/lib/python3.8/site-packages/anaconda_navigator/widgets/main_window.py", line 165, in __init__
    self.api = AnacondaAPI()
  File "/Users/liuyikun/opt/anaconda3/lib/python3.8/site-packages/anaconda_navigator/api/anaconda_api.py", line 1518, in AnacondaAPI
    ANACONDA_API = _AnacondaAPI()
  File "/Users/liuyikun/opt/anaconda3/lib/python3.8/site-packages/anaconda_navigator/api/anaconda_api.py", line 83, in __init__
    self._client_api = ClientAPI(config=self.config)
  File "/Users/liuyikun/opt/anaconda3/lib/python3.8/site-packages/anaconda_navigator/api/client_api.py", line 659, in ClientAPI
    CLIENT_API = _ClientAPI(config=config)
  File "/Users/liuyikun/opt/anaconda3/lib/python3.8/site-packages/anaconda_navigator/api/client_api.py", line 95, in __init__
    self.reload_client()
  File "/Users/liuyikun/opt/anaconda3/lib/python3.8/site-packages/anaconda_navigator/api/client_api.py", line 325, in reload_client
    client = self._load_binstar_client(url)
  File "/Users/liuyikun/opt/anaconda3/lib/python3.8/site-packages/anaconda_navigator/api/client_api.py", line 357, in _load_binstar_client
    binstar_client.utils.set_config(config)
  File "/Users/liuyikun/opt/anaconda3/lib/python3.8/site-packages/binstar_client/utils/config.py", line 283, in set_config
    save_config(data, USER_CONFIG if user else SYSTEM_CONFIG)
  File "/Users/liuyikun/opt/anaconda3/lib/python3.8/site-packages/binstar_client/utils/config.py", line 278, in save_config
    raise BinstarError('%s: %s' % (exc.filename, exc.strerror,))
binstar_client.errors.BinstarError: /Users/liuyikun/.continuum/anaconda-client: Permission denied

##### Anaconda or Miniconda version:

 Anaconda3-2021.05-MacOSX-x86_64.pkg

##### Operating System:
macOS Big Sur

##### `conda info`
 active environment : base
    active env location : /Users/liuyikun/opt/anaconda3
            shell level : 1
       user config file : /Users/liuyikun/.condarc
 populated config files : /Users/liuyikun/.condarc
          conda version : 4.10.3
    conda-build version : 3.21.4
         python version : 3.8.8.final.0
       virtual packages : __osx=10.16=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /Users/liuyikun/opt/anaconda3  (writable)
      conda av data dir : /Users/liuyikun/opt/anaconda3/etc/conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/osx-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/osx-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /Users/liuyikun/opt/anaconda3/pkgs
                          /Users/liuyikun/.conda/pkgs
       envs directories : /Users/liuyikun/opt/anaconda3/envs
                          /Users/liuyikun/.conda/envs
               platform : osx-64
             user-agent : conda/4.10.3 requests/2.25.1 CPython/3.8.8 Darwin/20.4.0 OSX/10.16
                UID:GID : 501:20
             netrc file : None
           offline mode : False

**Comment by evaykl** [comment]
I found a solution. 

This issue occurs because I installed and uninstalled Anaconda previously, and the old config.yaml file was not deleted. This file is located in /Users/liuyikun/.continuum/anaconda-client

so the solution is to find and delete the file **config.yaml** , or simply delete the whole folder **/Users/liuyikun/.continuum/**

and because .continuum/ is an invisible folder, so the easiest way is to use command line  **sudo rm -rf .continuum**   to delete the folder.
