### ISSUE TITLE
Navigator issues

### ISSUE THREAD

**Issue by N1cola2** [ContinuumIO/anaconda-issues#12526]
### Actual Behavior

It shows the following error
('Forbidden: Request forbidden -- authorization will not help ([GET] https://api.anaconda.org/user -> 403)', 403)

Traceback (most recent call last):
  File "C:\Users\teixenic\Anaconda3\lib\site-packages\anaconda_navigator\exceptions.py", line 72, in exception_handler
    return_value = func(*args, **kwargs)
  File "C:\Users\teixenic\Anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 146, in start_app
    window = run_app(splash)
  File "C:\Users\teixenic\Anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 65, in run_app
    window = MainWindow(splash=splash)
  File "C:\Users\teixenic\Anaconda3\lib\site-packages\anaconda_navigator\widgets\main_window.py", line 165, in __init__
    self.api = AnacondaAPI()
  File "C:\Users\teixenic\Anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 1518, in AnacondaAPI
    ANACONDA_API = _AnacondaAPI()
  File "C:\Users\teixenic\Anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 83, in __init__
    self._client_api = ClientAPI(config=self.config)
  File "C:\Users\teixenic\Anaconda3\lib\site-packages\anaconda_navigator\api\client_api.py", line 659, in ClientAPI
    CLIENT_API = _ClientAPI(config=config)
  File "C:\Users\teixenic\Anaconda3\lib\site-packages\anaconda_navigator\api\client_api.py", line 95, in __init__
    self.reload_client()
  File "C:\Users\teixenic\Anaconda3\lib\site-packages\anaconda_navigator\api\client_api.py", line 326, in reload_client
    client.user()
  File "C:\Users\teixenic\Anaconda3\lib\site-packages\binstar_client\__init__.py", line 245, in user
    self._check_response(res)
  File "C:\Users\teixenic\Anaconda3\lib\site-packages\binstar_client\__init__.py", line 230, in _check_response
    raise ErrCls(msg, res.status_code)
binstar_client.errors.BinstarError: ('Forbidden: Request forbidden -- authorization will not help ([GET] https://api.anaconda.org/user -> 403)', 403)
### Expected Behavior

It should open the conda navigator

### Steps to Reproduce

opening the conda

##### `conda info`

<details>

```
PASTE OUTPUT HERE:

```

</details>

##### `conda list --show-channel-urls`

<details>

```
PASTE OUTPUT HERE:

```

</details>

**Comment by csoja** [comment]
What version of Navigator are you using?

**Comment by hamidturky** [comment]
Hello! I have the same issue just installed anaconda before a couple of hours.
navigator version : 3.8.8 
Thanks!

**Comment by hamidturky** [comment]
> Hello! I have the same issue just installed anaconda before a couple of hours.
> navigator version : 3.8.8
> Thanks!

now it is fixed just restarted the pc
