### ISSUE TITLE
Anaconda installation problem

### ISSUE THREAD

**Issue by BlaiseMR** [ContinuumIO/anaconda-issues#12533]
I was installing Anaconda on my computer, then after a completed installation I get a lot of errors you can see below. As a result I can't run Anaconda and and Anaconda Navigator.
What can I do to fix taht issue ?

 After a lot of file extraction ...                                      
'''
Traceback (most recent call last):
  File "concurrent\futures\process.py", line 368, in _queue_management_worker
  File "multiprocessing\connection.py", line 251, in recv
TypeError: __init__() missing 1 required positional argument: 'msg'
'''

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "entry_point.py", line 69, in <module>
  File "concurrent\futures\process.py", line 484, in _chain_from_iterable_of_lists
  File "concurrent\futures\_base.py", line 611, in result_iterator
  File "concurrent\futures\_base.py", line 439, in result
  File "concurrent\futures\_base.py", line 388, in __get_result
concurrent.futures.process.BrokenProcessPool: A process in the process pool was terminated abruptly while the future was running or pending.
[4032] Failed to execute script entry_point
Collecting package metadata (current_repodata.json): ...working... done
Solving environment: ...working... failed with initial frozen solve. Retrying with flexible solve.
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... failed with initial frozen solve. Retrying with flexible solve.

PackagesNotFoundError: The following packages are not available from current channels:

  - werkzeug==1.0.1=pyhd3eb1b0_0
  - pandocfilters==1.4.3=py38haa95532_1
  - bokeh==2.3.2=py38haa95532_0
  - notebook==6.3.0=py38haa95532_0
  - win_inet_pton==1.1.0=py38haa95532_0
  - msgpack-python==1.0.2=py38h59b6b97_1
  - numba==0.53.1=py38hf11a4ad_0
  - pytz==2021.1=pyhd3eb1b0_0
  - m2w64-gcc-libs==5.3.0=7
  - backports==1.0=pyhd3eb1b0_2
  - partd==1.2.0=pyhd3eb1b0_0
  - decorator==5.0.6=pyhd3eb1b0_0
  - blosc==1.21.0=h19a0ad4_0
  - pyls-black==0.4.6=hd3eb1b0_0
  - nltk==3.6.1=pyhd3eb1b0_0
  - pep8==1.7.1=py38_0
  - pysocks==1.7.1=py38haa95532_0
  - conda-content-trust==0.1.1=pyhd3eb1b0_0
  - statsmodels==0.12.2=py38h2bbff1b_0
  - pyreadline==2.1=py38_1
  - anaconda-project==0.9.1=pyhd3eb1b0_1
  - backcall==0.2.0=pyhd3eb1b0_0
  - cffi==1.14.5=py38hcd4344a_0
  - diff-match-patch==20200713=py_0
  - py==1.10.0=pyhd3eb1b0_0
  - distributed==2021.4.0=py38haa95532_0
  - yaml==0.2.5=he774522_0
  - json5==0.9.5=py_0
  - ipykernel==5.3.4=py38h5ca1d4c_0
  - pytables==3.6.1=py38ha5be198_0
  - defusedxml==0.7.1=pyhd3eb1b0_0
  - zeromq==4.3.3=ha925a31_3
  - bitarray==1.9.2=py38h2bbff1b_1
  - py-lief==0.10.1=py38ha925a31_0
  - intel-openmp==2021.2.0=haa95532_616
  - ply==3.11=py38_0
  - backports.shutil_get_terminal_size==1.0.0=pyhd3eb1b0_3
  - scikit-image==0.18.1=py38hf11a4ad_0
  - pycparser==2.20=py_2
  - m2w64-gmp==6.1.0=2
  - rtree==0.9.7=py38h2eaa2aa_1
  - xlwings==0.23.0=py38haa95532_0
  - nbclient==0.5.3=pyhd3eb1b0_0
  - freetype==2.10.4=hd328e21_0
  - toolz==0.11.1=pyhd3eb1b0_0
  - _ipyw_jlab_nb_ext_conf==0.1.0=py38_0
  - path==15.1.2=py38haa95532_0
  - appdirs==1.4.4=py_0
  - pexpect==4.8.0=pyhd3eb1b0_3
  - intervaltree==3.1.0=py_0
  - networkx==2.5=py_0
  - bzip2==1.0.8=he774522_0
  - markupsafe==1.1.1=py38he774522_0
  - boto==2.49.0=py38_0
  - toml==0.10.2=pyhd3eb1b0_0
  - openpyxl==3.0.7=pyhd3eb1b0_0
  - krb5==1.18.2=hc04afaa_0
  - multipledispatch==0.6.0=py38_0
  - xlwt==1.3.0=py38_0
  - pywinpty==0.5.7=py38_0
  - msys2-conda-epoch==20160418=1
  - ipython_genutils==0.2.0=pyhd3eb1b0_1
  - jdcal==1.4.1=py_0
  - dask-core==2021.4.0=pyhd3eb1b0_0
  - mkl_fft==1.3.0=py38h277e83a_2
  - pyerfa==1.7.3=py38h2bbff1b_0
  - jupyter-packaging==0.7.12=pyhd3eb1b0_0
  - singledispatch==3.6.1=pyhd3eb1b0_1001
  - libtiff==4.2.0=hd0e1b90_0
  - blas==1.0=mkl
  - soupsieve==2.2.1=pyhd3eb1b0_0
  - ruamel_yaml==0.15.100=py38h2bbff1b_0
  - parso==0.7.0=py_0
  - brotlipy==0.7.0=py38h2bbff1b_1003
  - contextlib2==0.6.0.post1=py_0
  - mkl==2021.2.0=haa95532_296
  - path.py==12.5.0=0
  - brotli==1.0.9=ha925a31_2
  - jsonschema==3.2.0=py_2
  - console_shortcut==0.1.1=4
  - conda-repo-cli==1.0.4=pyhd3eb1b0_0
  - zict==2.0.0=pyhd3eb1b0_0
  - imagecodecs==2021.3.31=py38h5da4933_0
  - lerc==2.2.1=hd77b12b_0
  - zipp==3.4.1=pyhd3eb1b0_0
  - certifi==2020.12.5=py38haa95532_0
  - urllib3==1.26.4=pyhd3eb1b0_0
  - ca-certificates==2021.4.13=haa95532_1
  - lzo==2.10=he774522_2
  - pillow==8.2.0=py38h4fa10fc_0
  - pyrsistent==0.17.3=py38he774522_0
  - threadpoolctl==2.1.0=pyh5ca1d4c_0
  - pywin32==227=py38he774522_1
  - pywin32-ctypes==0.2.0=py38_1000
  - seaborn==0.11.1=pyhd3eb1b0_0
  - pkginfo==1.7.0=py38haa95532_0
  - mypy_extensions==0.4.3=py38_0
  - idna==2.10=pyhd3eb1b0_0
  - pycodestyle==2.6.0=pyhd3eb1b0_0
  - libsodium==1.0.18=h62dcd97_0
  - mccabe==0.6.1=py38_1
  - jupyterlab_server==2.4.0=pyhd3eb1b0_0
  - conda-build==3.21.4=py38haa95532_0
  - jupyter_server==1.4.1=py38haa95532_0
  - pyopenssl==20.0.1=pyhd3eb1b0_1
  - paramiko==2.7.2=py_0
  - hdf5==1.10.4=h7ebc959_0
  - wcwidth==0.2.5=py_0
  - python-libarchive-c==2.9=pyhd3eb1b0_1
  - traitlets==5.0.5=pyhd3eb1b0_0
  - sympy==1.8=py38haa95532_0
  - alabaster==0.7.12=pyhd3eb1b0_0
  - sortedcollections==2.1.0=pyhd3eb1b0_0
  - matplotlib==3.3.4=py38haa95532_0
  - prompt-toolkit==3.0.17=pyh06a4308_0
  - mkl-service==2.3.0=py38h2bbff1b_1
  - m2w64-gcc-libs-core==5.3.0=7
  - pyqt==5.9.2=py38ha925a31_4
  - zope.event==4.5.0=py38_0
  - jupyterlab_pygments==0.1.2=py_0
  - sphinxcontrib==1.0=py38_1
  - kiwisolver==1.3.1=py38hd77b12b_0
  - jpeg==9b=hb83a4c4_2
  - libzopfli==1.0.3=ha925a31_0
  - libarchive==3.4.2=h5e25573_0
  - jupyter==1.0.0=py38_7
  - xz==5.2.5=h62dcd97_0
  - sphinxcontrib-websupport==1.2.4=py_0
  - anyio==2.2.0=py38haa95532_2
  - six==1.15.0=py38haa95532_0
  - webencodings==0.5.1=py38_1
  - snappy==1.1.8=h33f27b4_0
  - cloudpickle==1.6.0=py_0
  - greenlet==1.0.0=py38hd77b12b_2
  - qt==5.9.7=vc14h73c81de_0
  - cryptography==3.4.7=py38h71e12ea_0
  - astropy==4.2.1=py38h2bbff1b_1
  - icu==58.2=ha925a31_3
  - python-jsonrpc-server==0.4.0=py_0
  - zlib==1.2.11=h62dcd97_4
  - chardet==4.0.0=py38haa95532_1003
  - get_terminal_size==1.0.0=h38e98db_0
  - sqlalchemy==1.4.7=py38h2bbff1b_0
  - sniffio==1.2.0=py38haa95532_1
  - openssl==1.1.1k=h2bbff1b_0
  - glob2==0.7=pyhd3eb1b0_0
  - anaconda-navigator==2.0.3=py38_0
  - liblief==0.10.1=ha925a31_0
  - giflib==5.2.1=h62dcd97_0
  - send2trash==1.5.0=pyhd3eb1b0_1
  - testpath==0.4.4=pyhd3eb1b0_0
  - bottleneck==1.3.2=py38h2a96729_1
  - libpng==1.6.37=h2a8f88b_0
  - black==19.10b0=py_0
  - rope==0.18.0=py_0
  - joblib==1.0.1=pyhd3eb1b0_0
  - lcms2==2.12=h83e58a3_0
  - vc==14.2=h21ff451_1
  - menuinst==1.4.16=py38he774522_1
  - sphinxcontrib-jsmath==1.0.1=pyhd3eb1b0_0
  - fsspec==0.9.0=pyhd3eb1b0_0
  - sphinxcontrib-applehelp==1.0.2=pyhd3eb1b0_0
  - wheel==0.36.2=pyhd3eb1b0_0
  - h5py==2.10.0=py38h5e291fa_0
  - lazy-object-proxy==1.6.0=py38h2bbff1b_0
  - backports.weakref==1.0.post1=py_1
  - babel==2.9.0=pyhd3eb1b0_0
  - jupyter_console==6.4.0=pyhd3eb1b0_0
  - pyparsing==2.4.7=pyhd3eb1b0_0
  - mistune==0.8.4=py38he774522_1000
  - python==3.8.8=hdbf39b2_5
  - vs2015_runtime==14.27.29016=h5e58377_2
  - wrapt==1.12.1=py38he774522_1
  - sortedcontainers==2.3.0=pyhd3eb1b0_0
  - asn1crypto==1.4.0=py_0
  - scikit-learn==0.24.1=py38hf11a4ad_0
  - tifffile==2021.4.8=pyhd3eb1b0_2
  - cycler==0.10.0=py38_0
  - nbconvert==6.0.7=py38_0
  - patsy==0.5.1=py38_0
  - pickleshare==0.7.5=pyhd3eb1b0_1003
  - importlib-metadata==3.10.0=py38haa95532_0
  - conda-env==2.6.0=1
  - zfp==0.5.5=hd77b12b_6
  - conda==4.10.1=py38haa95532_1
  - spyder==4.2.5=py38haa95532_0
  - textdistance==4.2.1=pyhd3eb1b0_0
  - jupyter_core==4.7.1=py38haa95532_0
  - cytoolz==0.11.0=py38he774522_0
  - flask==1.1.2=pyhd3eb1b0_0
  - sphinx==4.0.1=pyhd3eb1b0_0
  - openjpeg==2.3.0=h5ec785f_1
  - pyflakes==2.2.0=pyhd3eb1b0_0
  - pathspec==0.7.0=py_0
  - ptyprocess==0.7.0=pyhd3eb1b0_2
  - nose==1.3.7=pyhd3eb1b0_1006
  - dask==2021.4.0=pyhd3eb1b0_0
  - colorama==0.4.4=pyhd3eb1b0_0
  - et_xmlfile==1.0.1=py_1001
  - mkl_random==1.2.1=py38hf11a4ad_2
  - prompt_toolkit==3.0.17=hd3eb1b0_0
  - lz4-c==1.9.3=h2bbff1b_0
  - sqlite==3.35.4=h2bbff1b_0
  - argon2-cffi==20.1.0=py38h2bbff1b_1
  - setuptools==52.0.0=py38haa95532_0
  - backports.functools_lru_cache==1.6.4=pyhd3eb1b0_0
  - scipy==1.6.2=py38h66253e8_1
  - wincertstore==0.2=py38_0
  - packaging==20.9=pyhd3eb1b0_0
  - bleach==3.3.0=pyhd3eb1b0_0
  - winpty==0.4.3=4
  - requests==2.25.1=pyhd3eb1b0_0
  - m2w64-gcc-libgfortran==5.3.0=6
  - iniconfig==1.1.1=pyhd3eb1b0_0
  - llvmlite==0.36.0=py38h34b8924_4
  - pyodbc==4.0.30=py38ha925a31_0
  - pyls-spyder==0.3.2=pyhd3eb1b0_0
  - jedi==0.17.2=py38haa95532_1
  - gevent==21.1.2=py38h2bbff1b_1
  - qtawesome==1.0.2=pyhd3eb1b0_0
  - libssh2==1.9.0=h7a1dbc1_1
  - qdarkstyle==2.8.1=py_0
  - importlib_metadata==3.10.0=hd3eb1b0_0
  - sphinxcontrib-devhelp==1.0.2=pyhd3eb1b0_0
  - qtconsole==5.0.3=pyhd3eb1b0_0
  - simplegeneric==0.8.1=py38_2
  - astroid==2.5=py38haa95532_1
  - libaec==1.0.4=h33f27b4_1
  - conda-token==0.3.0=pyhd3eb1b0_0
  - xlsxwriter==1.3.8=pyhd3eb1b0_0
  - tornado==6.1=py38h2bbff1b_0
  - widgetsnbextension==3.5.1=py38_0
  - libspatialindex==1.9.3=h6c2663c_0
  - sphinxcontrib-serializinghtml==1.1.4=pyhd3eb1b0_0
  - autopep8==1.5.6=pyhd3eb1b0_0
  - bcrypt==3.2.0=py38he774522_0
  - jupyterlab==3.0.14=pyhd3eb1b0_1
  - xlrd==2.0.1=pyhd3eb1b0_0
  - conda-verify==3.4.2=py_1
  - tblib==1.7.0=py_0
  - three-merge==0.1.1=pyhd3eb1b0_0
  - charls==2.2.0=h6c2663c_0
  - lxml==4.6.3=py38h9b66d53_0
  - imagesize==1.2.0=pyhd3eb1b0_0
  - pygments==2.8.1=pyhd3eb1b0_0
  - pycurl==7.43.0.6=py38h7a1dbc1_0
  - fastcache==1.1.0=py38he774522_0
  - imageio==2.9.0=pyhd3eb1b0_0
  - m2w64-libwinpthread-git==5.0.0.4634.697f757=2
  - pyzmq==20.0.0=py38hd77b12b_1
  - olefile==0.46=py_0
  - sphinxcontrib-qthelp==1.0.3=pyhd3eb1b0_0
  - heapdict==1.0.1=py_0
  - yapf==0.31.0=pyhd3eb1b0_0
  - pywavelets==1.1.1=py38he774522_2
  - typing_extensions==3.7.4.3=pyha847dfd_0
  - watchdog==1.0.2=py38haa95532_1
  - backports.tempfile==1.0=pyhd3eb1b0_1
  - libiconv==1.15=h1df5818_7
  - nbformat==5.1.3=pyhd3eb1b0_0
  - click==7.1.2=pyhd3eb1b0_0
  - itsdangerous==1.1.0=pyhd3eb1b0_0
  - unicodecsv==0.14.1=py38_0
  - qtpy==1.9.0=py_0
  - ipython==7.22.0=py38hd4e2768_0
  - prometheus_client==0.10.1=pyhd3eb1b0_0
  - zope==1.0=py38_1
  - pytest==6.2.3=py38haa95532_2
  - libdeflate==1.7=h2bbff1b_5
  - sip==4.19.13=py38ha925a31_0
  - numpydoc==1.1.0=pyhd3eb1b0_1
  - curl==7.71.1=h2a8f88b_1
  - matplotlib-base==3.3.4=py38h49ac443_0
  - more-itertools==8.7.0=pyhd3eb1b0_0
  - numexpr==2.7.3=py38hb80d3ca_1
  - html5lib==1.1=py_0
  - cython==0.29.23=py38hd77b12b_0
  - future==0.18.2=py38_1
  - nest-asyncio==1.5.1=pyhd3eb1b0_0
  - jinja2==2.11.3=pyhd3eb1b0_0
  - pluggy==0.13.1=py38haa95532_0
  - conda-package-handling==1.7.3=py38h8cc25b3_1
  - pycosat==0.6.3=py38h2bbff1b_0
  - beautifulsoup4==4.9.3=pyha847dfd_0
  - entrypoints==0.3=py38_0
  - numpy-base==1.20.1=py38haf7ebc8_0
  - locket==0.2.1=py38haa95532_1
  - tqdm==4.59.0=pyhd3eb1b0_1
  - ujson==4.0.2=py38hd77b12b_0
  - pynacl==1.4.0=py38h62dcd97_1
  - bkcharts==0.2=py38_0
  - xmltodict==0.12.0=py_0
  - anaconda-client==1.7.2=py38_0
  - psutil==5.8.0=py38h2bbff1b_1
  - jupyter_client==6.1.12=pyhd3eb1b0_0
  - python-language-server==0.36.2=pyhd3eb1b0_0
  - libxslt==1.1.34=he774522_0
  - mock==4.0.3=pyhd3eb1b0_0
  - async_generator==1.10=pyhd3eb1b0_0
  - pip==21.0.1=py38haa95532_0
  - powershell_shortcut==0.0.1=3
  - navigator-updater==0.2.1=py38_0
  - spyder-kernels==1.10.2=py38haa95532_0
  - attrs==20.3.0=pyhd3eb1b0_0
  - nbclassic==0.2.6=pyhd3eb1b0_0
  - zstd==1.4.5=h04227a9_0
  - anaconda==2021.05=py38_0
  - libcurl==7.71.1=h2a8f88b_1
  - pathlib2==2.3.5=py38haa95532_2
  - filelock==3.0.12=pyhd3eb1b0_1
  - numpy==1.20.1=py38h34a8a5c_0
  - argh==0.26.2=py38_0
  - isort==5.8.0=pyhd3eb1b0_0
  - ipywidgets==7.6.3=pyhd3eb1b0_1
  - docutils==0.17=py38haa95532_1
  - pandoc==2.12=haa95532_0
  - libxml2==2.9.10=hb89e7f3_3
  - zope.interface==5.3.0=py38h2bbff1b_0
  - sphinxcontrib-htmlhelp==1.0.3=pyhd3eb1b0_0
  - atomicwrites==1.4.0=py_0
  - regex==2021.4.4=py38h2bbff1b_0
  - mpmath==1.2.1=py38haa95532_0
  - pyyaml==5.4.1=py38h2bbff1b_1
  - win_unicode_console==0.5=py38_0
  - pydocstyle==6.0.0=pyhd3eb1b0_0
  - pylint==2.7.4=py38haa95532_1
  - pandas==1.2.4=py38hd77b12b_0
  - icc_rt==2019.0.0=h0cc432a_1
  - comtypes==1.1.9=py38haa95532_1002
  - typed-ast==1.4.2=py38h2bbff1b_1
  - terminado==0.9.4=py38haa95532_0
  - python-dateutil==2.8.1=pyhd3eb1b0_0
  - jupyterlab_widgets==1.0.0=pyhd3eb1b0_1
  - tk==8.6.10=he774522_0
  - clyent==1.2.2=py38_1
  - snowballstemmer==2.1.0=pyhd3eb1b0_0
  - keyring==22.3.0=py38haa95532_0
  - flake8==3.9.0=pyhd3eb1b0_0
  - tbb==2020.3=h74a9793_0

Current channels:

  - https://repo.anaconda.com/pkgs/main/win-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/win-64
  - https://repo.anaconda.com/pkgs/r/noarch
  - https://repo.anaconda.com/pkgs/msys2/win-64
  - https://repo.anaconda.com/pkgs/msys2/noarch
  - https://repo.anaconda.com/pkgs/pro/win-64
  - https://repo.anaconda.com/pkgs/pro/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.

Delete file: C:\Users\My_name\anaconda3\pkgs\env.txt
Output folder: C:\Users\My_name\anaconda3\conda-meta
Extract: history
Creating Anaconda3 menus...
Execute: "C:\Users\My_name\anaconda3\pythonw.exe" -E -s "C:\Users\My_name\anaconda3\Lib\_nsis.py" mkdirs
Running post install...
Execute: "C:\Users\My_name\anaconda3\pythonw.exe" -E -s "C:\Users\My_name\anaconda3\Lib\_nsis.py" post_install
Execute: "C:\Users\My_name\anaconda3\pythonw.exe" -E -s "C:\Users\My_name\anaconda3\pkgs\.cio-config.py" "C:\Users\My_name\Downloads\Anaconda3-2021.05-Windows-x86_64.exe"
Created uninstaller: C:\Users\My_name\anaconda3\Uninstall-Anaconda3.exe
Completed

**Comment by BlaiseMR** [comment]
So, I decide to install an other version of Anaconda then updating it later through Anaconda Prompt.
When I install a previous version : Anaconda3-2018.12-Windows-x86_64 / Anaconda3-2019.10-Windows-x86_64 I get other problem but it install this time Anaconda Navigator and all other stuff.
the informations given by DebugView is :

[15552] [19:19:00:12:955][15556] CLogger::Create : Error opening log file [C:\ProgramData\NVIDIA Corporation\ShadowPlay\CaptureCore.log], Error [0x5]
[16920] _nsis.py: allusers is False
[16920] Menu: name: 'Anaconda${PY_VER} ${PLATFORM}', prefix: 'C:\Users\My_name\Anaconda3', env_name: 'None', mode: 'user', used_mode: 'user'
[16920] Shortcut cmd is C:\Users\My_name\Anaconda3\pythonw.exe, args are ['C:\\Users\\My_name\\Anaconda3\\cwp.py', 'C:\\Users\\My_name\\Anaconda3', 'C:\\Users\\My_name\\Anaconda3\\pythonw.exe', 'C:\\Users\\My_name\\Anaconda3\\Scripts\\anaconda-navigator-script.py']
[16920] _nsis.py: Processed C:\Users\My_name\Anaconda3\Menu\anaconda-navigator.json successfully.
[16920] Menu: name: 'Anaconda${PY_VER} ${PLATFORM}', prefix: 'C:\Users\My_name\Anaconda3', env_name: 'None', mode: 'user', used_mode: 'user'
[16920] Shortcut cmd is %windir%\System32\cmd.exe, args are ['"/K"', 'C:\\Users\\My_name\\Anaconda3\\Scripts\\activate.bat', 'C:\\Users\\My_name\\Anaconda3']
[16920] _nsis.py: Processed C:\Users\My_name\Anaconda3\Menu\console_shortcut.json successfully.
[16920] Menu: name: 'Anaconda${PY_VER} ${PLATFORM}', prefix: 'C:\Users\My_name\Anaconda3', env_name: 'None', mode: 'user', used_mode: 'user'
[16920] Shortcut cmd is C:\Users\My_name\Anaconda3\python.exe, args are ['C:\\Users\\My_name\\Anaconda3\\cwp.py', 'C:\\Users\\My_name\\Anaconda3', 'C:\\Users\\My_name\\Anaconda3\\python.exe', 'C:\\Users\\My_name\\Anaconda3\\Scripts\\jupyter-notebook-script.py', '"%USERPROFILE%/"']
[16920] _nsis.py: Processed C:\Users\My_name\Anaconda3\Menu\notebook.json successfully.
[16920] Menu: name: 'Anaconda${PY_VER} ${PLATFORM}', prefix: 'C:\Users\My_name\Anaconda3', env_name: 'None', mode: 'user', used_mode: 'user'
[16920] Shortcut cmd is C:\Users\My_name\Anaconda3\pythonw.exe, args are ['C:\\Users\\My_name\\Anaconda3\\cwp.py', 'C:\\Users\\My_name\\Anaconda3', 'C:\\Users\\My_name\\Anaconda3\\pythonw.exe', 'C:\\Users\\My_name\\Anaconda3\\Scripts\\spyder-script.py']
[16920] Shortcut cmd is C:\Users\My_name\Anaconda3\python.exe, args are ['C:\\Users\\My_name\\Anaconda3\\cwp.py', 'C:\\Users\\My_name\\Anaconda3', 'C:\\Users\\My_name\\Anaconda3\\python.exe', 'C:\\Users\\My_name\\Anaconda3\\Scripts\\spyder-script.py', '--reset']
[16920] _nsis.py: Processed C:\Users\My_name\Anaconda3\Menu\spyder_shortcut.json successfully.
[16896] _nsis.py: allusers is False
[6344] _nsis.py: allusers is False

**Comment by BlaiseMR** [comment]
I find the solution of my problem, some one said :
"I can verify this happens on Windows installations that have spaces or non-ASCII characters in the username regardless of Python2 or Python3. The recent Anaconda-4.3 release does not allow Anaconda to be installed in a path that has spaces or non-ASCII characters anymore."
https://github.com/ContinuumIO/anaconda-issues/issues/1270#issuecomment-277018492
I have a non-ASCII character in my name...
