### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by AlejandroZuluagaM** [ContinuumIO/anaconda-issues#12541]
Hi, I just installed Anaconda 4.4.0 (python 3.6) on my mac osx 10.9.2.
When I try to open the program I get this error:
Thanks in advanced for your help.

## Main error
An unexpected error occurred on Navigator start-up<br>string indices must be integers, not str
## Traceback
```
Traceback (most recent call last):
  File "/Applications/anaconda/lib/python2.7/site-packages/anaconda_navigator/exceptions.py", line 75, in exception_handler
    return_value = func(*args, **kwargs)
  File "/Applications/anaconda/lib/python2.7/site-packages/anaconda_navigator/app/start.py", line 115, in start_app
    window = run_app(splash)
  File "/Applications/anaconda/lib/python2.7/site-packages/anaconda_navigator/app/start.py", line 58, in run_app
    window = MainWindow(splash=splash)
  File "/Applications/anaconda/lib/python2.7/site-packages/anaconda_navigator/widgets/main_window.py", line 160, in __init__
    self.api = AnacondaAPI()
  File "/Applications/anaconda/lib/python2.7/site-packages/anaconda_navigator/api/anaconda_api.py", line 1205, in AnacondaAPI
    ANACONDA_API = _AnacondaAPI()
  File "/Applications/anaconda/lib/python2.7/site-packages/anaconda_navigator/api/anaconda_api.py", line 65, in __init__
    self._conda_api = CondaAPI()
  File "/Applications/anaconda/lib/python2.7/site-packages/anaconda_navigator/api/conda_api.py", line 1622, in CondaAPI
    CONDA_API = _CondaAPI()
  File "/Applications/anaconda/lib/python2.7/site-packages/anaconda_navigator/api/conda_api.py", line 340, in __init__
    self.set_conda_prefix()
  File "/Applications/anaconda/lib/python2.7/site-packages/anaconda_navigator/api/conda_api.py", line 489, in set_conda_prefix
    self.ROOT_PREFIX = info['root_prefix']
TypeError: string indices must be integers, not str

```
## System information
```
platform: osx-64
version: 1.6.2
conda: 4.3.21
qt: 5.6.2
language: en
python: 2.7.13
os: Darwin;13.1.0;Darwin Kernel Version 13.1.0: Thu Jan 16 19:40:37 PST 2014; root:xnu-2422.90.20~2/RELEASE_X86_64;x86_64;i386
pyqt: 5.6.0
```

**Comment by AlejandroZuluagaM** [comment]
Fixed, don't worry!!!
