### ISSUE TITLE
Navigator Startup Error

### ISSUE THREAD

**Issue by itprorh66** [ContinuumIO/anaconda-issues#12550]
### Actual Behavior

Navigator Error on startup

### Steps to Reproduce

Starting Anaconda Navigator, thyis issue has just arisen today.  Yesterday it worked fine.

##### Operating System:
Windows 10

##### `conda info`

<details>

```
Navigator Error
An unexpected error occurred on Navigator start-up

Report
Please report this issue in the anaconda issue tracker

Main Error
unacceptable character #x0000: special characters are not allowed
  in "C:\Users\BobHentz\.continuum\anaconda-client\config.yaml", position 0
Traceback
Traceback (most recent call last):
  File "D:\Anaconda3\lib\site-packages\anaconda_navigator\exceptions.py", line 72, in exception_handler
    return_value = func(*args, **kwargs)
  File "D:\Anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 146, in start_app
    window = run_app(splash)
  File "D:\Anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 65, in run_app
    window = MainWindow(splash=splash)
  File "D:\Anaconda3\lib\site-packages\anaconda_navigator\widgets\main_window.py", line 165, in __init__
    self.api = AnacondaAPI()
  File "D:\Anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 1518, in AnacondaAPI
    ANACONDA_API = _AnacondaAPI()
  File "D:\Anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 83, in __init__
    self._client_api = ClientAPI(config=self.config)
  File "D:\Anaconda3\lib\site-packages\anaconda_navigator\api\client_api.py", line 659, in ClientAPI
    CLIENT_API = _ClientAPI(config=config)
  File "D:\Anaconda3\lib\site-packages\anaconda_navigator\api\client_api.py", line 95, in __init__
    self.reload_client()
  File "D:\Anaconda3\lib\site-packages\anaconda_navigator\api\client_api.py", line 322, in reload_client
    url = binstar_client.utils.get_config()['url']
  File "D:\Anaconda3\lib\site-packages\binstar_client\utils\config.py", line 249, in get_config
    file_configs = load_file_configs(SEARCH_PATH)
  File "D:\Anaconda3\lib\site-packages\binstar_client\utils\config.py", line 241, in load_file_configs
    raw_data = collections.OrderedDict(kv for kv in itertools.chain.from_iterable(load_paths))
  File "D:\Anaconda3\lib\site-packages\binstar_client\utils\config.py", line 241, in 
    raw_data = collections.OrderedDict(kv for kv in itertools.chain.from_iterable(load_paths))
  File "D:\Anaconda3\lib\site-packages\binstar_client\utils\config.py", line 221, in _dir_yaml_loader
    yield filepath, load_config(filepath)
  File "D:\Anaconda3\lib\site-packages\binstar_client\utils\config.py", line 205, in load_config
    data = yaml_load(fd)
  File "D:\Anaconda3\lib\site-packages\binstar_client\utils\yaml.py", line 12, in yaml_load
    return safe_load(stream)
  File "D:\Anaconda3\lib\site-packages\yaml\__init__.py", line 162, in safe_load
    return load(stream, SafeLoader)
  File "D:\Anaconda3\lib\site-packages\yaml\__init__.py", line 112, in load
    loader = Loader(stream)
  File "D:\Anaconda3\lib\site-packages\yaml\loader.py", line 34, in __init__
    Reader.__init__(self, stream)
  File "D:\Anaconda3\lib\site-packages\yaml\reader.py", line 85, in __init__
    self.determine_encoding()
  File "D:\Anaconda3\lib\site-packages\yaml\reader.py", line 135, in determine_encoding
    self.update(1)
  File "D:\Anaconda3\lib\site-packages\yaml\reader.py", line 169, in update
    self.check_printable(data)
  File "D:\Anaconda3\lib\site-packages\yaml\reader.py", line 143, in check_printable
    raise ReaderError(self.name, position, ord(character),
yaml.reader.ReaderError: unacceptable character #x0000: special characters are not allowed
  in "C:\Users\BobHentz\.continuum\anaconda-client\config.yaml", position 0

```

</details>

##### `conda list --show-channel-urls`

<details>

```
PASTE OUTPUT HERE:

```

</details>

**Comment by csoja** [comment]
Looks like C:\Users\BobHentz\.continuum\anaconda-client\config.yaml is corrupted.  I'd recommend backing up the current file to config.old, and then deleting C:\Users\BobHentz\.continuum\anaconda-client\config.yaml and attempting to restart navigator again.

**Comment by itprorh66** [comment]
already done, navigator restored.


Bob Hentz
On 8/2/2021 9:39:48 AM, csoja ***@***.***> wrote:
Looks like C:\Users\BobHentz.continuum\anaconda-client\config.yaml is corrupted. I'd recommend backing up the current file to config.old, and then deleting C:\Users\BobHentz.continuum\anaconda-client\config.yaml and attempting to restart navigator again.
