### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by KCGubler** [ContinuumIO/anaconda-issues#12554]
## Main error
Application <b>notebook</b> launch may have produced errors.
## Traceback
```
Traceback (most recent call last):
  File "C:\Anaconda\Scripts\jupyter-notebook-script.py", line 3, in <module>
    import notebook.notebookapp
  File "C:\Anaconda\lib\site-packages\notebook\notebookapp.py", line 40, in <module>
    ioloop.install()
  File "C:\Anaconda\lib\site-packages\zmq\eventloop\ioloop.py", line 207, in install
    from tornado import ioloop
  File "C:\Anaconda\lib\site-packages\tornado\ioloop.py", line 53, in <module>
    from tornado.util import Configurable, TimeoutError, import_object
ImportError: cannot import name 'TimeoutError'

```
## System information
```
python: 3.6.1
language: en_US
os: Windows;10;10.0.18362;AMD64;Intel64 Family 6 Model 158 Stepping 13, GenuineIntel
version: 1.6.2
platform: win-64
qt: 5.6.2
pyqt: 5.6.0
conda: 4.3.21
```

**Comment by KCGubler** [comment]
And now my Jupyter Notebook won't open from the Anaconda Navigator. Any help would be greatly appreciated.
