### ISSUE TITLE
Navigator Error('NoneType' object has no attribute 'split')

### ISSUE THREAD

**Issue by meetcs143** [ContinuumIO/anaconda-issues#12579]
### Actual Behavior

When I open Anaconda Navigator, I get the following error:

**Navigator Error**
An unexpected error occurred on Navigator start-up

**Main Error**
'NoneType' object has no attribute 'split'

**Traceback**
Traceback (most recent call last):
  File "/Users/chandra.shekhr3/opt/anaconda3/lib/python3.8/site-packages/anaconda_navigator/exceptions.py", line 72, in exception_handler
    return_value = func(*args, **kwargs)
  File "/Users/chandra.shekhr3/opt/anaconda3/lib/python3.8/site-packages/anaconda_navigator/app/start.py", line 146, in start_app
    window = run_app(splash)
  File "/Users/chandra.shekhr3/opt/anaconda3/lib/python3.8/site-packages/anaconda_navigator/app/start.py", line 65, in run_app
    window = MainWindow(splash=splash)
  File "/Users/chandra.shekhr3/opt/anaconda3/lib/python3.8/site-packages/anaconda_navigator/widgets/main_window.py", line 165, in __init__
    self.api = AnacondaAPI()
  File "/Users/chandra.shekhr3/opt/anaconda3/lib/python3.8/site-packages/anaconda_navigator/api/anaconda_api.py", line 1518, in AnacondaAPI
    ANACONDA_API = _AnacondaAPI()
  File "/Users/chandra.shekhr3/opt/anaconda3/lib/python3.8/site-packages/anaconda_navigator/api/anaconda_api.py", line 82, in __init__
    self._conda_api = CondaAPI()
  File "/Users/chandra.shekhr3/opt/anaconda3/lib/python3.8/site-packages/anaconda_navigator/api/conda_api.py", line 1571, in CondaAPI
    CONDA_API = _CondaAPI()
  File "/Users/chandra.shekhr3/opt/anaconda3/lib/python3.8/site-packages/anaconda_navigator/api/conda_api.py", line 342, in __init__
    self.set_conda_prefix(info=get_conda_info())
  File "/Users/chandra.shekhr3/opt/anaconda3/lib/python3.8/site-packages/anaconda_navigator/api/conda_api.py", line 500, in set_conda_prefix
    for part in info.get('conda_version').split('.'):
AttributeError: 'NoneType' object has no attribute 'split'

### Expected Behavior

Should open anaconda navigator from which we can launch jupyter notebook, spyder etc..

##### `conda info`

<details>

```
PASTE OUTPUT HERE:
CustomValidationError: Parameter ssl_verify = '${HOME}/IDFCBANKCA.pem' declared in /Users/chandra.shekhr3/.condarc is invalid.
ssl_verify value '${HOME}/IDFCBANKCA.pem' must be a boolean, a path to a certificate bundle file, or a path to a directory containing certificates of trusted CAs.
```

</details>

##### `conda list --show-channel-urls`

<details>

```
PASTE OUTPUT HERE:
asn1crypto                0.24.0                   py37_0    defaults
bzip2                     1.0.8                h1de35cc_0    defaults
ca-certificates           2019.5.15                     0    defaults
certifi                   2019.6.16                py37_0    defaults
cffi                      1.12.3           py37hb5b8e2f_0    defaults
chardet                   3.0.4                    py37_1    defaults
conda                     4.7.10                   py37_0    defaults
conda-package-handling    1.3.11                   py37_0    defaults
cryptography              2.7              py37ha12b0ac_0    defaults
idna                      2.8                      py37_0    defaults
libarchive                3.3.3                h786848e_5    defaults
libcxx                    4.0.1                hcfea43d_1    defaults
libcxxabi                 4.0.1                hcfea43d_1    defaults
libedit                   3.1.20181209         hb402a30_0    defaults
libffi                    3.2.1                h475c297_4    defaults
libiconv                  1.15                 hdd342a3_7    defaults
libxml2                   2.9.9                hf6e021a_1    defaults
lz4-c                     1.8.1.2              h1de35cc_0    defaults
lzo                       2.10                 h362108e_2    defaults
ncurses                   6.1                  h0a44026_1    defaults
openssl                   1.1.1c               h1de35cc_1    defaults
pip                       19.1.1                   py37_0    defaults
pycosat                   0.6.3            py37h1de35cc_0    defaults
pycparser                 2.19                     py37_0    defaults
pyopenssl                 19.0.0                   py37_0    defaults
pysocks                   1.7.0                    py37_0    defaults
python                    3.7.3                h359304d_0    defaults
python-libarchive-c       2.8                     py37_11    defaults
python.app                2                        py37_9    defaults
readline                  7.0                  h1de35cc_5    defaults
requests                  2.22.0                   py37_0    defaults
ruamel_yaml               0.15.46          py37h1de35cc_0    defaults
setuptools                41.0.1                   py37_0    defaults
six                       1.12.0                   py37_0    defaults
sqlite                    3.29.0               ha441bb4_0    defaults
tk                        8.6.8                ha441bb4_0    defaults
tqdm                      4.32.1                     py_0    defaults
urllib3                   1.24.2                   py37_0    defaults
wheel                     0.33.4                   py37_0    defaults
xz                        5.2.4                h1de35cc_4    defaults
yaml                      0.1.7                hc338f04_2    defaults
zlib                      1.2.11               h1de35cc_3    defaults
zstd                      1.3.7                h5bba6e5_0    defaults
```

</details>

**Comment by vshevchenko-anaconda** [comment]
Duplicate of #11780
