### ISSUE TITLE
Cannot launch Spyder after upgrading to spyder 3

### ISSUE THREAD

**Issue by Tuzi12** [ContinuumIO/anaconda-issues#1258]
Hi guys,

I recently upgraded the spyder to 3 through pip install --upgrade, but since then, I cannot launch it at all, after saying 'loading ipython...' the window flashes before it disappears completely. The crash log is as below: 

Traceback (most recent call last):
  File "c:\python27\lib\site-packages\spyder\app\mainwindow.py", line 3001, in main
    mainwindow = run_spyder(app, options, args)
  File "c:\python27\lib\site-packages\spyder\app\mainwindow.py", line 2905, in run_spyder
    main.setup()
  File "c:\python27\lib\site-packages\spyder\app\mainwindow.py", line 1010, in setup
    from xy.config import DOC_PATH as xy_doc_path
  File "c:\python27\lib\site-packages\xy\config.py", line 40, in <module>
    CONF = UserConfig('xy', defaults=DEFAULTS, version=__version__, subfolder='.xy')
  File "c:\python27\lib\site-packages\xy\userconfig.py", line 110, in __init__
    if version != self.get_version(version):
  File "c:\python27\lib\site-packages\xy\userconfig.py", line 130, in get_version
    return self.get(self.DEFAULT_SECTION_NAME, 'version', version)
  File "c:\python27\lib\site-packages\xy\userconfig.py", line 269, in get
    value = cp.ConfigParser.get(self, section, option, raw=self.raw)
  File "c:\python27\lib\site-packages\backports\configparser\__init__.py", line 811, in get
    d)
  File "c:\python27\lib\site-packages\backports\configparser\__init__.py", line 384, in before_get
    self._interpolate_some(parser, option, L, value, section, defaults, 1)
  File "c:\python27\lib\site-packages\backports\configparser\__init__.py", line 397, in _interpolate_some
    rawval = parser.get(section, option, raw=True, fallback=rest)
**TypeError: get() got an unexpected keyword argument 'raw'**

I searched around on google for a fix, but did not have any luck so far. Any ideas? 

Thank you!

**Comment by Tuzi12** [comment]
Sorry, just noticed this is 'anaconda-issues' section. Mine should be **pythonxy**, and i just realized that I could not open pythonxy either :(

**Comment by ccordoba12** [comment]
Closing as this is not related to Anaconda.
