### ISSUE TITLE
Anaconda Navigator will not open - 'No Qt bindings could be found'

### ISSUE THREAD

**Issue by liyong-gb** [ContinuumIO/anaconda-issues#12587]
hi，I installed anaconda just a few minutes ago ,while I click anaconda navigator,but the navigator would not open,from some web suggestions,I try the flowing way,but I failed again，who can help me?
the 1st way:conda update anaconda-navigator
the 2nd way :anaconda-navigator --reset
the 3rd way ：conda update anaconda-client
the 4th way：conda update -f anaconda-client
the 5th way:pip install PyQt5
now,I decide uninstall anaconda and install again,I want to konw how to install a successful anaconda.
`C:\Users\username>anaconda-navigator
Traceback (most recent call last):
  File "E:\Anaconda\Anaconda\lib\site-packages\qtpy\__init__.py", line 204, in <module>
    from PySide import __version__ as PYSIDE_VERSION  # analysis:ignore
ModuleNotFoundError: No module named 'PySide'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Anaconda\Anaconda\Scripts\anaconda-navigator-script.py", line 10, in <module>
    sys.exit(main())
  File "E:\Anaconda\Anaconda\lib\site-packages\anaconda_navigator\app\main.py", line 119, in main
    from anaconda_navigator.app.start import start_app
  File "E:\Anaconda\Anaconda\lib\site-packages\anaconda_navigator\app\start.py", line 19, in <module>
    from qtpy import PYQT5
  File "E:\Anaconda\Anaconda\lib\site-packages\qtpy\__init__.py", line 210, in <module>
    raise PythonQtError('No Qt bindings could be found')
qtpy.PythonQtError: No Qt bindings could be found
`
another question
In the morning ,I install anacodna in other machine,it's successful,but in this machine I failed,I installed them in the same way!!!!!

**Comment by harshi-18** [comment]
even I have the same problem

**Comment by liyong-gb** [comment]
My problem is solved
