### ISSUE TITLE
Cannot use dbm.gnu in python 3.3 or 3.4

### ISSUE THREAD

**Issue by desilinguist** [ContinuumIO/anaconda-issues#126]
The `dbm.gnu` module cannot be imported on either python 3.3 or 3.4. It gives me the following error:

``` python
Python 3.3.5 |Continuum Analytics, Inc.| (default, Mar 10 2014, 11:22:25) 
[GCC 4.0.1 (Apple Inc. build 5493)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import dbm.gnu
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/nmadnani/anaconda/envs/3.3/lib/python3.3/dbm/gnu.py", line 3, in <module>
    from _gdbm import *
ImportError: No module named '_gdbm'
```

**Comment by nikicc** [comment]
I'm having the same issue. Any progress on this?

**Comment by nehaljwani** [comment]
Debian devs have added the following patch:
```bash
(126_) [nwani@centos6x64 Downloads]$ cat ./debian/patches/gdbm-import.diff
# DP: suggest installation of python3-gdbm package on failing _gdbm import

--- a/Lib/dbm/gnu.py
+++ b/Lib/dbm/gnu.py
@@ -1,3 +1,6 @@
 """Provide the _gdbm module as a dbm submodule."""
 
-from _gdbm import *
+try:
+    from _gdbm import *
+except ImportError as msg:
+    raise ImportError(str(msg) + ', please install the python3-gdbm package')
```

**Comment by nehaljwani** [comment]
Related: https://bugs.launchpad.net/ubuntu/+source/python3.2/+bug/995616

Marking this as a package request for `py3x` build of `python-gdbm`
