### ISSUE TITLE
An unexpected error occurred on Navigator start-up

### ISSUE THREAD

**Issue by BruceGeng2012** [ContinuumIO/anaconda-issues#12610]
Dear Sir,

1. First time to install, when try to open it , just showing the Error content like this:

Navigator Error
An unexpected error occurred on Navigator start-up

Report
Please report this issue in the anaconda issue tracker

Main Error
check_hostname requires server_hostname
Traceback
Traceback (most recent call last):
  File "C:\Users\bruce\anaconda3\lib\site-packages\anaconda_navigator\exceptions.py", line 72, in exception_handler
    return_value = func(*args, **kwargs)
  File "C:\Users\bruce\anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 146, in start_app
    window = run_app(splash)
  File "C:\Users\bruce\anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 65, in run_app
    window = MainWindow(splash=splash)
  File "C:\Users\bruce\anaconda3\lib\site-packages\anaconda_navigator\widgets\main_window.py", line 165, in __init__
    self.api = AnacondaAPI()
  File "C:\Users\bruce\anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 1518, in AnacondaAPI
    ANACONDA_API = _AnacondaAPI()
  File "C:\Users\bruce\anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 83, in __init__
    self._client_api = ClientAPI(config=self.config)
  File "C:\Users\bruce\anaconda3\lib\site-packages\anaconda_navigator\api\client_api.py", line 659, in ClientAPI
    CLIENT_API = _ClientAPI(config=config)
  File "C:\Users\bruce\anaconda3\lib\site-packages\anaconda_navigator\api\client_api.py", line 95, in __init__
    self.reload_client()
  File "C:\Users\bruce\anaconda3\lib\site-packages\anaconda_navigator\api\client_api.py", line 326, in reload_client
    client.user()
  File "C:\Users\bruce\anaconda3\lib\site-packages\binstar_client\__init__.py", line 244, in user
    res = self.session.get(url, verify=self.session.verify)
  File "C:\Users\bruce\anaconda3\lib\site-packages\requests\sessions.py", line 555, in get
    return self.request('GET', url, **kwargs)
  File "C:\Users\bruce\anaconda3\lib\site-packages\requests\sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\bruce\anaconda3\lib\site-packages\requests\sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\bruce\anaconda3\lib\site-packages\requests\adapters.py", line 439, in send
    resp = conn.urlopen(
  File "C:\Users\bruce\anaconda3\lib\site-packages\urllib3\connectionpool.py", line 696, in urlopen
    self._prepare_proxy(conn)
  File "C:\Users\bruce\anaconda3\lib\site-packages\urllib3\connectionpool.py", line 964, in _prepare_proxy
    conn.connect()
  File "C:\Users\bruce\anaconda3\lib\site-packages\urllib3\connection.py", line 359, in connect
    conn = self._connect_tls_proxy(hostname, conn)
  File "C:\Users\bruce\anaconda3\lib\site-packages\urllib3\connection.py", line 500, in _connect_tls_proxy
    return ssl_wrap_socket(
  File "C:\Users\bruce\anaconda3\lib\site-packages\urllib3\util\ssl_.py", line 432, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls)
  File "C:\Users\bruce\anaconda3\lib\site-packages\urllib3\util\ssl_.py", line 474, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock)
  File "C:\Users\bruce\anaconda3\lib\ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "C:\Users\bruce\anaconda3\lib\ssl.py", line 997, in _create
    raise ValueError("check_hostname requires server_hostname")
ValueError: check_hostname requires server_hostnameThanks for opening an issue! Please fill out the following template in full.

A few things to keep in mind:

- This issue tracker is for issues with installing Anaconda or Miniconda or with packages built by Anaconda, Inc. like Anaconda Navigator. It is also a place to request packages or other enhancements of the Anaconda Distribution.

- Anaconda Community Code of Conduct: https://www.anaconda.com/community-code-of-conduct/

- For conda issues, you should open an issue at https://github.com/conda/conda/issues

- For conda-build issues, you should open an issue at https://github.com/conda/conda-build

- For an issue with a particular conda-forge package, you should open an issue on the corresponding feedstock: https://github.com/conda-forge

##### `conda info`

<details>

```
PASTE OUTPUT HERE:

```

</details>

##### `conda list --show-channel-urls`

<details>

```
PASTE OUTPUT HERE:

```

</details>

2. Am trying to open it but keep showing this error...
    Try the method as below:
    https://docs.anaconda.com/anaconda/user-guide/tasks/proxy/

    Still the same...

    .condarc file as below:

always_yes: true
channels:
  - defaults
  - conda-forge
  - defaults
ssl_verify: true
proxy_servers:
    http: http://192.168.0.108:11223
    https: https://192.168.0.108:11223
channel_priority: strict
show_channel_urls: True
report_errors: False

3. Kindly give a hand, thx...

**Comment by BruceGeng2012** [comment]
Already solved by myself...

**Comment by BruceGeng2012** [comment]
Sharing my method and u also can have a try....
1. The first time met the issue, which was showing content as below:

`Navigator Error
An unexpected error occurred on Navigator start-up

Report
Please report this issue in the anaconda issue tracker

Main Error
check_hostname requires server_hostname
Traceback
Traceback (most recent call last):
File "C:\Users\bruce\anaconda3\lib\site-packages\anaconda_navigator\exceptions.py", line 72, in exception_handler
return_value = func(*args, **kwargs)
File "C:\Users\bruce\anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 146, in start_app
window = run_app(splash)
File "C:\Users\bruce\anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 65, in run_app
window = MainWindow(splash=splash)
File "C:\Users\bruce\anaconda3\lib\site-packages\anaconda_navigator\widgets\main_window.py", line 165, in init
self.api = AnacondaAPI()
File "C:\Users\bruce\anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 1518, in AnacondaAPI
ANACONDA_API = _AnacondaAPI()
File "C:\Users\bruce\anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 83, in init
self._client_api = ClientAPI(config=self.config)
File "C:\Users\bruce\anaconda3\lib\site-packages\anaconda_navigator\api\client_api.py", line 659, in ClientAPI
CLIENT_API = ClientAPI(config=config)
File "C:\Users\bruce\anaconda3\lib\site-packages\anaconda_navigator\api\client_api.py", line 95, in init
self.reload_client()
File "C:\Users\bruce\anaconda3\lib\site-packages\anaconda_navigator\api\client_api.py", line 326, in reload_client
client.user()
File "C:\Users\bruce\anaconda3\lib\site-packages\binstar_client_init.py", line 244, in user
res = self.session.get(url, verify=self.session.verify)
File "C:\Users\bruce\anaconda3\lib\site-packages\requests\sessions.py", line 555, in get
return self.request('GET', url, **kwargs)
File "C:\Users\bruce\anaconda3\lib\site-packages\requests\sessions.py", line 542, in request
resp = self.send(prep, **send_kwargs)
File "C:\Users\bruce\anaconda3\lib\site-packages\requests\sessions.py", line 655, in send
r = adapter.send(request, **kwargs)
File "C:\Users\bruce\anaconda3\lib\site-packages\requests\adapters.py", line 439, in send
resp = conn.urlopen(
File "C:\Users\bruce\anaconda3\lib\site-packages\urllib3\connectionpool.py", line 696, in urlopen
self._prepare_proxy(conn)
File "C:\Users\bruce\anaconda3\lib\site-packages\urllib3\connectionpool.py", line 964, in _prepare_proxy
conn.connect()
File "C:\Users\bruce\anaconda3\lib\site-packages\urllib3\connection.py", line 359, in connect
conn = self._connect_tls_proxy(hostname, conn)
File "C:\Users\bruce\anaconda3\lib\site-packages\urllib3\connection.py", line 500, in connect_tls_proxy
return ssl_wrap_socket(
File "C:\Users\bruce\anaconda3\lib\site-packages\urllib3\util\ssl.py", line 432, in ssl_wrap_socket
ssl_sock = ssl_wrap_socket_impl(sock, context, tls_in_tls)
File "C:\Users\bruce\anaconda3\lib\site-packages\urllib3\util\ssl.py", line 474, in _ssl_wrap_socket_impl
return ssl_context.wrap_socket(sock)
File "C:\Users\bruce\anaconda3\lib\ssl.py", line 500, in wrap_socket
return self.sslsocket_class._create(
File "C:\Users\bruce\anaconda3\lib\ssl.py", line 997, in _create
raise ValueError("check_hostname requires server_hostname")
ValueError: check_hostname requires server_hostnameThanks for opening an issue! Please fill out the following template in full.`


2. Tryed to use variables within my Enviroment Variables as below:
C:\Users\bruce\anaconda3
C:\Users\bruce\anaconda3\Library\bin
C:\Users\bruce\anaconda3\Scripts
C:\Users\bruce\anaconda3\Library\mingw-w64\bin
Name:  http_proxy
Value:   http://my address:my port
Name:  https_proxy
Value:   http://my address:my port
Attention: both proxy name are differ, but value same. Especially "value: http" without ‘s’

3. And put the code into .condarc file...

channels:
  - http://mirrors.ustc.edu.cn/anaconda/pkgs/free/
  - http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/
  - http://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/

show_channel_urls: true
allow_other_channels: true
  proxy_servers:
  http: http://192.168.0.108:11223
  https: http://192.168.0.108:11223
ssl_verify: true

4. Second time to start anaconda3, the issue content as below...

Navigator Error
An unexpected error occurred on Navigator start-up

Report
Please report this issue in the anaconda issue tracker

Main Error
'bytes' object has no attribute 'get'
Traceback
Traceback (most recent call last):
  File "C:\Users\bruce\anaconda3\lib\site-packages\anaconda_navigator\exceptions.py", line 72, in exception_handler
    return_value = func(*args, **kwargs)
  File "C:\Users\bruce\anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 146, in start_app
    window = run_app(splash)
  File "C:\Users\bruce\anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 65, in run_app
    window = MainWindow(splash=splash)
  File "C:\Users\bruce\anaconda3\lib\site-packages\anaconda_navigator\widgets\main_window.py", line 165, in __init__
    self.api = AnacondaAPI()
  File "C:\Users\bruce\anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 1518, in AnacondaAPI
    ANACONDA_API = _AnacondaAPI()
  File "C:\Users\bruce\anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 82, in __init__
    self._conda_api = CondaAPI()
  File "C:\Users\bruce\anaconda3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 1571, in CondaAPI
    CONDA_API = _CondaAPI()
  File "C:\Users\bruce\anaconda3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 342, in __init__
    self.set_conda_prefix(info=get_conda_info())
  File "C:\Users\bruce\anaconda3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 493, in set_conda_prefix
    self.ROOT_PREFIX = info.get('root_prefix')
AttributeError: 'bytes' object has no attribute 'get'


4. Deleted file .condarc...restart...succeed...
5. check .condarc file
channels:
  - defaults

Nothing else...hope that can help others...

**Comment by LtDan33** [comment]
@BruceGeng2012 Thanks for the follow-up with what worked! A few are having this issue and this will be a great rally point to see if this could help others.

**Comment by BruceGeng2012** [comment]
> @BruceGeng2012 Thanks for the follow-up with what worked! A few are having this issue and this will be a great rally point to see if this could help others. 
> 

It's my privilege...hope you a wonderful day...

**Comment by Lssousadc** [comment]
Hi Guys!

@BruceGeng2012 , where can I find this ".condarc" file you mentioned? I have been looking for it but I can't find it.
