### ISSUE TITLE
Navigator Error ('list' object has no attribute 'get')

### ISSUE THREAD

**Issue by darryllmcleod** [ContinuumIO/anaconda-issues#12617]
### Actual Behavior

When I try to open Anaconda Navigator (by clicking on it), multiple screens pop up and work their way through (expected), and then a google chrome window opens (which is my default browser) with an error message and not the Anaconda Naviator.

### Expected Behavior

The Anaconda Navigator should open (in the default browser).

### Steps to Reproduce

Hit 'windows' button, type 'anaconda' and click 'Anaconda Navigator' which is one of the options that pops up.

##### Anaconda or Miniconda version:

Anaconda 3 2021.05

##### Operating System:

Windows 10 Enterprise, 1909_4.0

##### `conda info`

<details>

```
PASTE OUTPUT HERE:

Navigator Error
An unexpected error occurred on Navigator start-up

Report
Please report this issue in the anaconda issue tracker

Main Error
'list' object has no attribute 'get'
Traceback
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\anaconda_navigator\exceptions.py", line 72, in exception_handler
    return_value = func(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 146, in start_app
    window = run_app(splash)
  File "C:\ProgramData\Anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 65, in run_app
    window = MainWindow(splash=splash)
  File "C:\ProgramData\Anaconda3\lib\site-packages\anaconda_navigator\widgets\main_window.py", line 166, in __init__
    self.api = AnacondaAPI()
  File "C:\ProgramData\Anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 1534, in AnacondaAPI
    ANACONDA_API = _AnacondaAPI()
  File "C:\ProgramData\Anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 81, in __init__
    self._conda_api = CondaAPI()
  File "C:\ProgramData\Anaconda3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 1571, in CondaAPI
    CONDA_API = _CondaAPI()
  File "C:\ProgramData\Anaconda3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 342, in __init__
    self.set_conda_prefix(info=get_conda_info())
  File "C:\ProgramData\Anaconda3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 493, in set_conda_prefix
    self.ROOT_PREFIX = info.get('root_prefix')
AttributeError: 'list' object has no attribute 'get'

##### `conda list --show-channel-urls`

file:///C:/Users/darryllmcleodhughe/AppData/Local/Temp/tmpmw05wqx4.html

**Comment by cooltnt** [comment]
win10,  Anaconda3-2022.05-Windows-x86_64.exe
same error
