### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by skyleong7777** [ContinuumIO/anaconda-issues#12629]
i just installed and open the Anaconda, but got the below issue. please help me to solve the below issue, 

Navigator Error
An unexpected error occurred on Navigator start-up

Report
Please report this issue in the anaconda issue tracker

Main Error
Could not find a suitable TLS CA certificate bundle, invalid path: None
Traceback
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\anaconda_navigator\exceptions.py", line 72, in exception_handler
    return_value = func(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 146, in start_app
    window = run_app(splash)
  File "C:\ProgramData\Anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 65, in run_app
    window = MainWindow(splash=splash)
  File "C:\ProgramData\Anaconda3\lib\site-packages\anaconda_navigator\widgets\main_window.py", line 165, in __init__
    self.api = AnacondaAPI()
  File "C:\ProgramData\Anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 1518, in AnacondaAPI
    ANACONDA_API = _AnacondaAPI()
  File "C:\ProgramData\Anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 83, in __init__
    self._client_api = ClientAPI(config=self.config)
  File "C:\ProgramData\Anaconda3\lib\site-packages\anaconda_navigator\api\client_api.py", line 659, in ClientAPI
    CLIENT_API = _ClientAPI(config=config)
  File "C:\ProgramData\Anaconda3\lib\site-packages\anaconda_navigator\api\client_api.py", line 95, in __init__
    self.reload_client()
  File "C:\ProgramData\Anaconda3\lib\site-packages\anaconda_navigator\api\client_api.py", line 326, in reload_client
    client.user()
  File "C:\ProgramData\Anaconda3\lib\site-packages\binstar_client\__init__.py", line 244, in user
    res = self.session.get(url, verify=self.session.verify)
  File "C:\ProgramData\Anaconda3\lib\site-packages\requests\sessions.py", line 555, in get
    return self.request('GET', url, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\requests\sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\requests\sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\requests\adapters.py", line 416, in send
    self.cert_verify(conn, request.url, verify, cert)
  File "C:\ProgramData\Anaconda3\lib\site-packages\requests\adapters.py", line 227, in cert_verify
    raise IOError("Could not find a suitable TLS CA certificate bundle, "
OSError: Could not find a suitable TLS CA certificate bundle, invalid path: None

**Comment by jamasole** [comment]
I got the same message. I'm installing Anaconda on Mac OS 11.6,  The message started after updating Anaconda.

**Comment by ykobayshi** [comment]
I also have this kinds of message on Windows10 after updating Anaconda.

Traceback (most recent call last):
  File "C:\Users\xx\anaconda3\lib\site-packages\anaconda_navigator\exceptions.py", line 72, in exception_handler
    return_value = func(*args, **kwargs)
  File "C:\Users\xx\anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 146, in start_app
    window = run_app(splash)
  File "C:\Users\xx\anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 65, in run_app
    window = MainWindow(splash=splash)
  File "C:\Users\xx\anaconda3\lib\site-packages\anaconda_navigator\widgets\main_window.py", line 165, in __init__
    self.api = AnacondaAPI()
  File "C:\Users\xx\anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 1518, in AnacondaAPI
    ANACONDA_API = _AnacondaAPI()
  File "C:\Users\xx\anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 82, in __init__
    self._conda_api = CondaAPI()
  File "C:\Users\xx\anaconda3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 1571, in CondaAPI
    CONDA_API = _CondaAPI()
  File "C:\Users\xx\anaconda3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 342, in __init__
    self.set_conda_prefix(info=get_conda_info())
  File "C:\Users\xx\anaconda3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 493, in set_conda_prefix
    self.ROOT_PREFIX = info.get('root_prefix')
AttributeError: 'bytes' object has no attribute 'get'
