### ISSUE TITLE
Navigator Error!

### ISSUE THREAD

**Issue by freelancelwj7** [ContinuumIO/anaconda-issues#12628]
I have installed and while opening the file i am getting the below error.

Navigator Error
An unexpected error occurred on Navigator start-up

Report
Please report this issue in the anaconda issue tracker

Main Error
check_hostname requires server_hostname
Traceback
Traceback (most recent call last):
  File "E:\Anaconda\lib\site-packages\anaconda_navigator\exceptions.py", line 72, in exception_handler
    return_value = func(*args, **kwargs)
  File "E:\Anaconda\lib\site-packages\anaconda_navigator\app\start.py", line 146, in start_app
    window = run_app(splash)
  File "E:\Anaconda\lib\site-packages\anaconda_navigator\app\start.py", line 65, in run_app
    window = MainWindow(splash=splash)
  File "E:\Anaconda\lib\site-packages\anaconda_navigator\widgets\main_window.py", line 166, in __init__
    self.api = AnacondaAPI()
  File "E:\Anaconda\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 1534, in AnacondaAPI
    ANACONDA_API = _AnacondaAPI()
  File "E:\Anaconda\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 82, in __init__
    self._client_api = ClientAPI(config=self.config)
  File "E:\Anaconda\lib\site-packages\anaconda_navigator\api\client_api.py", line 660, in ClientAPI
    CLIENT_API = _ClientAPI(config=config)
  File "E:\Anaconda\lib\site-packages\anaconda_navigator\api\client_api.py", line 95, in __init__
    self.reload_client()
  File "E:\Anaconda\lib\site-packages\anaconda_navigator\api\client_api.py", line 326, in reload_client
    client.user()
  File "E:\Anaconda\lib\site-packages\binstar_client\__init__.py", line 241, in user
    res = self.session.get(url, verify=self.session.verify)
  File "E:\Anaconda\lib\site-packages\requests\sessions.py", line 555, in get
    return self.request('GET', url, **kwargs)
  File "E:\Anaconda\lib\site-packages\requests\sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "E:\Anaconda\lib\site-packages\requests\sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "E:\Anaconda\lib\site-packages\requests\adapters.py", line 449, in send
    timeout=timeout
  File "E:\Anaconda\lib\site-packages\urllib3\connectionpool.py", line 696, in urlopen
    self._prepare_proxy(conn)
  File "E:\Anaconda\lib\site-packages\urllib3\connectionpool.py", line 964, in _prepare_proxy
    conn.connect()
  File "E:\Anaconda\lib\site-packages\urllib3\connection.py", line 359, in connect
    conn = self._connect_tls_proxy(hostname, conn)
  File "E:\Anaconda\lib\site-packages\urllib3\connection.py", line 506, in _connect_tls_proxy
    ssl_context=ssl_context,
  File "E:\Anaconda\lib\site-packages\urllib3\util\ssl_.py", line 453, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls)
  File "E:\Anaconda\lib\site-packages\urllib3\util\ssl_.py", line 495, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock)
  File "E:\Anaconda\lib\ssl.py", line 423, in wrap_socket
    session=session
  File "E:\Anaconda\lib\ssl.py", line 827, in _create
    raise ValueError("check_hostname requires server_hostname")
ValueError: check_hostname requires server_hostname

**Comment by LtDan33** [comment]
Hey there, thanks for bringing this up! Can you do 2 things?

1) try `conda update urllib3` and try again

2) If above doesn't work, add the below information so that we can troubleshoot quicker?

### Actual Behavior





### Expected Behavior





### Steps to Reproduce





##### Anaconda or Miniconda version:



##### Operating System:

##### `conda info`


<details>

```
PASTE OUTPUT HERE:

```

</details>

##### `conda list --show-channel-urls`


<details>

```
PASTE OUTPUT HERE:

```

</details>
