### ISSUE TITLE
Navigator Error at startup

### ISSUE THREAD

**Issue by jamasole** [ContinuumIO/anaconda-issues#12641]
I have a fresh install and upon opening I get the following error message.

Navigator Error
An unexpected error occurred on Navigator start-up

Report
Please report this issue in the anaconda issue tracker

Main Error
/Users/javier/.continuum/anaconda-client: Permission denied
Traceback
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.8/site-packages/binstar_client/utils/config.py", line 273, in save_config
    os.makedirs(data_dir)
  File "/opt/anaconda3/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/Users/javier/.continuum/anaconda-client'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.8/site-packages/anaconda_navigator/exceptions.py", line 72, in exception_handler
    return_value = func(*args, **kwargs)
  File "/opt/anaconda3/lib/python3.8/site-packages/anaconda_navigator/app/start.py", line 146, in start_app
    window = run_app(splash)
  File "/opt/anaconda3/lib/python3.8/site-packages/anaconda_navigator/app/start.py", line 65, in run_app
    window = MainWindow(splash=splash)
  File "/opt/anaconda3/lib/python3.8/site-packages/anaconda_navigator/widgets/main_window.py", line 165, in __init__
    self.api = AnacondaAPI()
  File "/opt/anaconda3/lib/python3.8/site-packages/anaconda_navigator/api/anaconda_api.py", line 1518, in AnacondaAPI
    ANACONDA_API = _AnacondaAPI()
  File "/opt/anaconda3/lib/python3.8/site-packages/anaconda_navigator/api/anaconda_api.py", line 83, in __init__
    self._client_api = ClientAPI(config=self.config)
  File "/opt/anaconda3/lib/python3.8/site-packages/anaconda_navigator/api/client_api.py", line 659, in ClientAPI
    CLIENT_API = _ClientAPI(config=config)
  File "/opt/anaconda3/lib/python3.8/site-packages/anaconda_navigator/api/client_api.py", line 95, in __init__
    self.reload_client()
  File "/opt/anaconda3/lib/python3.8/site-packages/anaconda_navigator/api/client_api.py", line 325, in reload_client
    client = self._load_binstar_client(url)
  File "/opt/anaconda3/lib/python3.8/site-packages/anaconda_navigator/api/client_api.py", line 357, in _load_binstar_client
    binstar_client.utils.set_config(config)
  File "/opt/anaconda3/lib/python3.8/site-packages/binstar_client/utils/config.py", line 283, in set_config
    save_config(data, USER_CONFIG if user else SYSTEM_CONFIG)
  File "/opt/anaconda3/lib/python3.8/site-packages/binstar_client/utils/config.py", line 278, in save_config
    raise BinstarError('%s: %s' % (exc.filename, exc.strerror,))
binstar_client.errors.BinstarError: /Users/javier/.continuum/anaconda-client: Permission deniedThanks for opening an issue! Please fill out the following template in full.

### Expected Behavior

Open the Navigator

### Steps to Reproduce

Double click on the Navigator icon

##### Operating System:

Mac OS 11.6

##### `conda info`

<details>

```
PASTE OUTPUT HERE:

```

</details>

##### `conda list --show-channel-urls`

<details>

```
PASTE OUTPUT HERE:

```

</details>

**Comment by jamasole** [comment]
I partly solved it this way. I'm using Mac OS
1. I erased the fresh installed Anaconda Navigator 
2. I run ONYX to clear the caches
3. I installed the version 2020.11 in the global Application folder (not the /opt directory is uses to install it in)
4. I made a copy of the Anaconda3 folder
5. I opened the Anaconda3 installed and it opened fine. I could see the prompts saying: loading packages....
6. I opened a terminal within the environment and typed: conda update conda Anaconda Anaconda-Navigator. I could see the update working fine as, for example pip changed from version 20 to version 24. 
7. I closed Anaconda
8. I tried to reopen Anaconda and it crashed. Before seeing the prompts: loading packages... i got the message at the beginning of this issue: Navigator Error etc. 
9. I tried to open the copy with the original 2020.11 version, and it also crashed. 
10.  I deleted everything and started again. So I'm stuck but fine with version 2020.11
