### ISSUE TITLE
Incompatible library version when installing opencv via conda

### ISSUE THREAD

**Issue by moaazsidat** [ContinuumIO/anaconda-issues#1266]
Running into a problem when installing opencv via conda. 

More specifically, when I open `python` and try `import cv2`, I get the following error:
```
>>> import cv2
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: dlopen(//anaconda/lib/python3.5/site-packages/cv2.cpython-35m-darwin.so, 2): Library not loaded: @rpath/libpng16.16.dylib
  Referenced from: /anaconda/lib/libopencv_imgcodecs.3.1.0.dylib
  Reason: Incompatible library version: libopencv_imgcodecs.3.1.dylib requires version 41.0.0 or later, but libpng16.16.dylib provides version 39.0.0
```

I came across this issue that was filed earlier, tried the suggestion here, but still getting the same error.
https://github.com/ContinuumIO/anaconda-issues/issues/826

Anyone know what might be going on? Thanks!

**Comment by elvawyf** [comment]
I meet the same issue. Anyone could provide a help? Thanks a lot! 

```
>>>  import cv2
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: dlopen(/anaconda/lib/python3.6/site-packages/cv2.cpython-36m-darwin.so, 2): Library not loaded: @rpath/libpng16.16.dylib
  Referenced from: /anaconda/lib/libopencv_imgcodecs.3.1.0.dylib
  Reason: Incompatible library version: libopencv_imgcodecs.3.1.dylib requires version 45.0.0 or later, but libpng16.16.dylib provides version 44.0.0
```

**Comment by Dr-Champ** [comment]
Exactly the same issue here

I installed opencv3 with conda, specifically this build

`opencv                    3.1.0               np112py36_1    condo-forge`

When doing the import cv2, this is thrown out.

`Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: dlopen(/Users/Champ/anaconda/envs/tensorflow/lib/python3.6/site-packages/cv2.cpython-36m-darwin.so, 2): Library not loaded: @rpath/libpng16.16.dylib
  Referenced from: /Users/Champ/anaconda/envs/tensorflow/lib/libopencv_imgcodecs.3.1.0.dylib
  Reason: Incompatible library version: libopencv_imgcodecs.3.1.dylib requires version 45.0.0 or later, but libpng16.16.dylib provides version 44.0.0`

**Comment by MeteorKepler** [comment]
The same! Anyone could help?

**Comment by danduncan** [comment]
I resolved this issue for Anaconda + OpenCV + MacOSX. 

Original error message:

> ImportError: dlopen(/Users/Dan/anaconda/envs/py27_opencv/lib/python2.7/site-packages/cv2.so, 2): Library not loaded: @rpath/libpng16.16.dylib
> 
> Referenced from: /Users/Dan/anaconda/envs/py27_opencv/lib/libopencv_imgcodecs.3.1.0.dylib
> 
> Reason: Incompatible library version: libopencv_imgcodecs.3.1.dylib requires version 45.0.0 or later, but libpng16.16.dylib provides version 44.0.0

Diagnosis: Possibly as a result of also having Homebrew, there were multiple copies of libpng on my system. Even though Anaconda uses virtual environments, opencv was being linked to the wrong copy of libpng.

Solution:

1. Clean uninstall Homebrew
2. Clean uninstall Anaconda
3. Delete (or comment out) any extra variables being set in `~/.bash_profile`, specifically anything related to anaconda, `DYLD_LIBRARY_PATH`, and `DYLD_FALLBACK_LIBRARY_PATH`
4. Restart computer to reset your environment variables
5. Reinstall Anaconda+OpenCV. Do not reinstall Homebrew.

After doing all of this, the conflict was resolved and OpenCV worked as expected.

P.S.
An alternative solution may be to hunt down the offending libraries (possibly at `/usr/bin/` or `/usr/local/bin/`) and update them individually. 
Just for thoroughness, one final possibility: the environment variable `DYLD_LIBRARY_PATH` tells the system possible places to look for libraries, while the variable `DYLD_FALLBACK_LIBRARY_PATH` tells the system where else to look if a library wasn't found along `DYLD_LIBRARY_PATH`. These variables can be set in `~/.bash_profile`. It may be possible to use them to force your system to reference the correct copy of libpng. But this change is system-wide and will potentially crash any other apps that rely on either libpng or `DYLD_LIBRARY_PATH`.

**Comment by mingwandroid** [comment]
Since `SIP` was introduced in El Capitan [1], no software can reasonably rely on the `DYLD_*` family of environment variables [2] so removing those entries should do nothing, unless A. You've disabled SIP [3] and B. You use some software that depends on `DYLD_*`. This is highly unlikely, and I can guarantee that no software provided by the Anaconda Distribution relies on those.

[1] https://support.apple.com/en-gb/HT204899
[2] https://developer.apple.com/library/content/documentation/Security/Conceptual/System_Integrity_Protection_Guide/RuntimeProtections/RuntimeProtections.html
[3] https://developer.apple.com/library/content/documentation/Security/Conceptual/System_Integrity_Protection_Guide/ConfiguringSystemIntegrityProtection/ConfiguringSystemIntegrityProtection.html

**Comment by mingwandroid** [comment]
If you want to see which shared libraries get loaded by macOS that can be achieved with the following command-line.

`sudo dtruss python -c 'import cv2' 2>&1 | grep '.so\|.dylib'`

@moaazsidat you didn't specify how you installed OpenCV. Was it from `conda-forge` or the `default` channels?

Using packages from `defaults` only I've not been able to reproduce this. The OpenCV there doesn't link to `libpng` at all:

```
conda create -y -n opencv2-defaults opencv
source activate opencv2-defaults
python -c 'import cv2' # note that there is no error here
sudo dtruss python -c 'import cv2' 2>&1 | grep '.so\|.dylib' | grep png
```

With `opencv3` from `conda-forge` for `Python 3.6`, I get:

```
conda create -y -n opencv3-condaforge -c conda-forge opencv python=3.6
source activate opencv3-condaforge
python -c 'import cv2'
```
.. gives:
```
python -c 'import cv2'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: dlopen(/Users/rdonnelly/mc-x64-3.6/envs/opencv3-condaforge/lib/python3.6/site-packages/cv2.cpython-36m-darwin.so, 2): Library not loaded: @rpath/libopenblasp-r0.2.19.dylib
  Referenced from: /Users/rdonnelly/mc-x64-3.6/envs/opencv3-condaforge/lib/libopencv_hdf.3.2.0.dylib
  Reason: image not found
```

.. ok, so the `Python 3.6` `opencv` on `conda-forge` that gets installed when you are not tracking any `blas feature` seems to be brokenly linked to `openblas` anyway (pinging @jakirkham, is this a bug?). Not to worry, we can add the missing feature to ~/.condarc and try again (it is probably only safe to do it this way if you know you have no features at present, otherwise hand edit the file):

```
echo "track_features:" >> ~/.condarc
echo "  - blas_openblas" >> ~/.condarc
```

.. next, remove the conda-forge env and try again:

```
source activate root
rm -rf $CONDA_PREFIX/envs/opencv3-condaforge
conda create -y -n opencv3-condaforge -c conda-forge opencv python=3.6
python -c 'import cv2'
```

.. and it works with no problem. If anyone tries this or something slightly less officially recommended (e.g. not creating an isolated environment) and still has problems, then please show me the output from:

`sudo dtruss python -c 'import cv2' 2>&1 | grep '.so\|.dylib'`

.. and I will do my best to continue diagnosing what is wrong here.

**Comment by jakirkham** [comment]
> .. ok, so the Python 3.6 opencv on conda-forge that gets installed when you are not tracking any blas feature seems to be brokenly linked to openblas anyway (pinging @jakirkham, is this a bug?).

It was fixed in PR ( https://github.com/conda-forge/opencv-feedstock/pull/65 ). 😕 That said you are not the only one experiencing this ( https://github.com/conda-forge/opencv-feedstock/issues/69 ). Probably the solver is throwing up old packages that don't have the feature.

Not totally sure what the right fix is to that. Maybe pull any `opencv` packages linked to `openblas` that don't explicitly require it. However that opens a new can of worms that people might not get the latest version as older versions don't have the feature. Can't remember how the `conda` solver was instructed to resolve this conflict ATM.

**Comment by Po-Hsuan-Huang** [comment]
I am using Mac Sierra v.10.12.6 and using conda environment (v4.3.23) with python 2.7.13

I tried 
`
echo "track_features:" >> ~/.condarc
`
`
echo "  - blas_openblas" >> ~/.condarc
`
and soruce the ~/.condarc 
doesn't work.

The error message :
`
ImportError: dlopen(/Users/pohsuanhuang/miniconda/envs/tensorflow/lib/python2.7/site-packages/cv2.so, 2): Library not loaded: @rpath/libavresample.3.dylib
  Referenced from: /Users/pohsuanhuang/miniconda/envs/tensorflow/lib/libopencv_videoio.3.2.0.dylib
  Reason: image not found
`
@mingwandroid 

 sudo dtruss python -c 'import cv2' 2>&1 | grep '.so\|.dylib'

gives me : 
[gist snippet](https://gist.github.com/Po-Hsuan-Huang/808fbeec11a3363b25b8c887dfdc7fbe.js)

**Comment by pirmoradian** [comment]
The only way that I could solve this library incompatibility problem was by uninstalling the latest version of opencv (3.3.1) and, instead, installing an older version (2.4.11) that I knew it was working at some point:

`conda uninstall opencv`
`conda install -c https://conda.binstar.org/menpo opencv`

**Comment by abhinav3** [comment]
Thanks @pirmoradian

**Comment by Joevonlong** [comment]
can be solved by find some way to install libpng16.16.dylib, then solved

**Comment by Adityaojas** [comment]
I simply solved this issue by using 
conda update --all
hope this works for y'all too.

**Comment by bryanltj** [comment]
Thank you! @pirmoradian

**Comment by voinik** [comment]
Thanks @Adityaojas !
