### ISSUE TITLE
/Users/Alex/.continuum/anaconda-client/config.yaml: Permission denied

### ISSUE THREAD

**Issue by alex-papadopoulos** [ContinuumIO/anaconda-issues#12665]
### Actual Behavior

I was prompted to update Navigator. Having successfully completed the update, I am now unable to start Navigator on macOS, as I get the error

Main Error

/Users/Alex/.continuum/anaconda-client/config.yaml: Permission denied
Traceback

Traceback (most recent call last):
  File "/Users/Alex/opt/anaconda3/lib/python3.8/site-packages/binstar_client/utils/config.py", line 275, in save_config
    with open(config_file, 'w') as fd:
PermissionError: [Errno 13] Permission denied: '/Users/Alex/.continuum/anaconda-client/config.yaml'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/Alex/opt/anaconda3/lib/python3.8/site-packages/anaconda_navigator/exceptions.py", line 72, in exception_handler
    return_value = func(*args, **kwargs)
  File "/Users/Alex/opt/anaconda3/lib/python3.8/site-packages/anaconda_navigator/app/start.py", line 146, in start_app
    window = run_app(splash)
  File "/Users/Alex/opt/anaconda3/lib/python3.8/site-packages/anaconda_navigator/app/start.py", line 65, in run_app
    window = MainWindow(splash=splash)
  File "/Users/Alex/opt/anaconda3/lib/python3.8/site-packages/anaconda_navigator/widgets/main_window/__init__.py", line 228, in __init__
    self.api = AnacondaAPI()
  File "/Users/Alex/opt/anaconda3/lib/python3.8/site-packages/anaconda_navigator/api/anaconda_api.py", line 1587, in AnacondaAPI
    ANACONDA_API = _AnacondaAPI()
  File "/Users/Alex/opt/anaconda3/lib/python3.8/site-packages/anaconda_navigator/api/anaconda_api.py", line 82, in __init__
    self._client_api = ClientAPI(config=self.config)
  File "/Users/Alex/opt/anaconda3/lib/python3.8/site-packages/anaconda_navigator/api/client_api.py", line 660, in ClientAPI
    CLIENT_API = _ClientAPI(config=config)
  File "/Users/Alex/opt/anaconda3/lib/python3.8/site-packages/anaconda_navigator/api/client_api.py", line 95, in __init__
    self.reload_client()
  File "/Users/Alex/opt/anaconda3/lib/python3.8/site-packages/anaconda_navigator/api/client_api.py", line 325, in reload_client
    client = self._load_binstar_client(url)
  File "/Users/Alex/opt/anaconda3/lib/python3.8/site-packages/anaconda_navigator/api/client_api.py", line 357, in _load_binstar_client
    binstar_client.utils.set_config(config)
  File "/Users/Alex/opt/anaconda3/lib/python3.8/site-packages/binstar_client/utils/config.py", line 283, in set_config
    save_config(data, USER_CONFIG if user else SYSTEM_CONFIG)
  File "/Users/Alex/opt/anaconda3/lib/python3.8/site-packages/binstar_client/utils/config.py", line 278, in save_config
    raise BinstarError('%s: %s' % (exc.filename, exc.strerror,))
binstar_client.errors.BinstarError: /Users/Alex/.continuum/anaconda-client/config.yaml: Permission denied

##### Anaconda or Miniconda version:

anaconda version 2021.05 

##### Operating System:

macOS Big Sur (11.1)

Any sort of help on how to get around this and have Navigator working properly again would be greatly appreciated!

**Comment by csoja** [comment]
Looks like Navigator doesn't have permission to /Users/Alex/.continuum/anaconda-client/config.yaml
I'd recommend either fixing the permissions, or renaming the current file from config.yaml to config.old and trying to launch Navigator again.

**Comment by Qyoom** [comment]
Didn't work for me. I changed config.yaml to config.OLD and still get the same permission error

**Comment by csoja** [comment]
Can you share the error you are seeing?

**Comment by Qyoom** [comment]
Thank you, csoja, for your reply. The problem somehow resolved itself with my thrashing at it. I basically attempted the Anaconda install three times and the third time was a charm!
