### ISSUE TITLE
Crashed while adaconda navigator 2.10

### ISSUE THREAD

**Issue by SamCHENG16** [ContinuumIO/anaconda-issues#12660]
Main Error
'list' object has no attribute 'get'
Traceback
Traceback (most recent call last):
  File "C:\Users\600026775\Anaconda3\lib\site-packages\anaconda_navigator\exceptions.py", line 72, in exception_handler
    return_value = func(*args, **kwargs)
  File "C:\Users\600026775\Anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 146, in start_app
    window = run_app(splash)
  File "C:\Users\600026775\Anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 65, in run_app
    window = MainWindow(splash=splash)
  File "C:\Users\600026775\Anaconda3\lib\site-packages\anaconda_navigator\widgets\main_window\__init__.py", line 228, in __init__
    self.api = AnacondaAPI()
  File "C:\Users\600026775\Anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 1587, in AnacondaAPI
    ANACONDA_API = _AnacondaAPI()
  File "C:\Users\600026775\Anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 81, in __init__
    self._conda_api = CondaAPI()
  File "C:\Users\600026775\Anaconda3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 1668, in CondaAPI
    CONDA_API = _CondaAPI()
  File "C:\Users\600026775\Anaconda3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 330, in __init__
    self.set_conda_prefix(info=get_conda_info())
  File "C:\Users\600026775\Anaconda3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 481, in set_conda_prefix
    self.ROOT_PREFIX = info.get('root_prefix')
AttributeError: 'list' object has no attribute 'get'

**Comment by vshevchenko-anaconda** [comment]
Hi @SamCHENG16 ,
Navigator 2.1.1 is released. Could you try to update to the latest version to see if that helps?
