### ISSUE TITLE
Anaconda Navigator will not start.

### ISSUE THREAD

**Issue by STodd1119** [ContinuumIO/anaconda-issues#12670]
Thanks for opening an issue! Please fill out the following template in full.

A few things to keep in mind:

- This issue tracker is for issues with installing Anaconda or Miniconda or with packages built by Anaconda, Inc. like Anaconda Navigator. It is also a place to request packages or other enhancements of the Anaconda Distribution.

- Anaconda Community Code of Conduct: https://www.anaconda.com/community-code-of-conduct/

- For conda issues, you should open an issue at https://github.com/conda/conda/issues

- For conda-build issues, you should open an issue at https://github.com/conda/conda-build

- For an issue with a particular conda-forge package, you should open an issue on the corresponding feedstock: https://github.com/conda-forge

### Actual Behavior

I installed Anaconda yesterday and everything was working fine.  Today when I start by double clicking the icon I get the following in my web browser.
Navigator Error
An unexpected error occurred on Navigator start-up

Report
Please report this issue in the anaconda issue tracker

Main Error
'charmap' codec can't decode byte 0x8d in position 3184: character maps to 
Traceback
Traceback (most recent call last):
  File "C:\Users\stephen_todd\Anaconda3\lib\site-packages\anaconda_navigator\exceptions.py", line 72, in exception_handler
    return_value = func(*args, **kwargs)
  File "C:\Users\stephen_todd\Anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 146, in start_app
    window = run_app(splash)
  File "C:\Users\stephen_todd\Anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 65, in run_app
    window = MainWindow(splash=splash)
  File "C:\Users\stephen_todd\Anaconda3\lib\site-packages\anaconda_navigator\widgets\main_window\__init__.py", line 325, in __init__
    self.stack.add_advertisement(url=advertisement_url)
  File "C:\Users\stephen_todd\Anaconda3\lib\site-packages\anaconda_navigator\widgets\tabs\tabwidget.py", line 278, in add_advertisement
    self.tabbar.add_advertisement(url)
  File "C:\Users\stephen_todd\Anaconda3\lib\site-packages\anaconda_navigator\widgets\tabs\tabwidget.py", line 134, in add_advertisement
    label_image_link = LabelImageLinkVertical(ad.text, ad.url, ad.image, 150, 150, 10)
  File "C:\Users\stephen_todd\Anaconda3\lib\site-packages\anaconda_navigator\widgets\__init__.py", line 471, in __init__
    self.setStyleSheet(load_style_sheet())
  File "C:\Users\stephen_todd\Anaconda3\lib\site-packages\anaconda_navigator\utils\styles.py", line 119, in load_style_sheet
    sass_data = f.read()
  File "C:\Users\stephen_todd\Anaconda3\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x8d in position 3184: character maps to 

### Expected Behavior

I should have had the anaconda application load and run.

### Steps to Reproduce

as described above.  I double click the anaconda navigator and get the above error.

##### Anaconda or Miniconda version:

2021.05

##### Operating System:
Windows 10
##### `conda info`

<details>

```
PASTE OUTPUT HERE:

```

</details>

##### `conda list --show-channel-urls`

<details>

```
PASTE OUTPUT HERE:

```

</details>

**Comment by vshevchenko-anaconda** [comment]
Hi @STodd1119,
Navigator 2.1.1 is released. Could you try to update to the latest version to see if that helps?

**Comment by STodd1119** [comment]
Thank you this appears to have corrected my issue.
