### ISSUE TITLE
Not able to upgrade navigator by click upgrade now button

### ISSUE THREAD

**Issue by funkgeek** [ContinuumIO/anaconda-issues#12678]
Thanks for opening an issue! Please fill out the following template in full.

A few things to keep in mind:

- This issue tracker is for issues with installing Anaconda or Miniconda or with packages built by Anaconda, Inc. like Anaconda Navigator. It is also a place to request packages or other enhancements of the Anaconda Distribution.

- Anaconda Community Code of Conduct: https://www.anaconda.com/community-code-of-conduct/

- For conda issues, you should open an issue at https://github.com/conda/conda/issues

- For conda-build issues, you should open an issue at https://github.com/conda/conda-build

- For an issue with a particular conda-forge package, you should open an issue on the corresponding feedstock: https://github.com/conda-forge

Everytime when I open anaconda navigator, it advised me to upgrade, and I clicked yes, but nothing happened. Then I also clicked the upgrade now button on the top right bar of navigator and clicked yes, still nothing happened. 
Then I went to anaconda cmd prompt and type "conda update anaconda-navigator", it started upgrading but after finishing that, when I turn anaconda off and on again,   it still showed I need to upgrade. 
And I also not able to upgrade sypder. I clicked upgrade application, but it still stay in the old version

it should start upgrading my anaconda navigator. And my spyder also should upgrade.

##### `conda info`

<details>

```
PASTE OUTPUT HERE:

```

</details>

##### `conda list --show-channel-urls`

<details>

```
PASTE OUTPUT HERE:

```

</details>

**Comment by yeechin18** [comment]
Same issue with anaconda navigator 1.9.12 on macOS. I tried updating manually from my terminal but received the message 

> # All requested packages already installed.

**Comment by vshevchenko-anaconda** [comment]
Hi @funkgeek ,
Navigator 2.1.1 is released. Could you try to update to the latest version to see if that helps, please? To do that you can use 
`conda update anaconda-navigator` command

**Comment by peter-pri** [comment]
I checked that it now fixed for for me under Windows 10. I could upgrade to 2.1.0 and 2.1.1

**Comment by aloktz** [comment]
I am having this exact issue with the exact same error message word for word after upgrading to pop os 20.04.

**Comment by thaswell** [comment]
I am having a similar issue updating Anaconda Navigator 1.9.12 to 2.2.0. If I open Anaconda Navigator and click the '(i) Upgrade Now" link, I get the 'Update Application' pop-up prompting to update to 2.2.0. If I click 'Yes', I get the following error in the terminal that I used to launch Anaconda Navigator:

Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.8/site-packages/anaconda_navigator/widgets/main_window.py", line 824, in update_application
    pid = self.open_updater(
  File "/opt/anaconda3/lib/python3.8/site-packages/anaconda_navigator/widgets/main_window.py", line 851, in open_updater
    return launch(
  File "/opt/anaconda3/lib/python3.8/site-packages/anaconda_navigator/utils/launch.py", line 316, in launch
    new_command = command.replace('\\', '/')
AttributeError: 'list' object has no attribute 'replace'

- I have updated conda and run 'conda update --all' in my base environment to reduce issues with incompatible older versions.
- I have also tried running 'conda install anaconda=custom' to make sure that the conda metapackage wasn't pinned. 
- I have tried 'conda update anaconda-navigator' with the base environment activated and deactivated

Does anyone have any other ideas?   Thanks!

**Comment by jcwang-phys** [comment]
The solution is in this post

https://github.com/conda/conda/issues/10349#issuecomment-792939109
