### ISSUE TITLE
Downloaded anaconda investigator today. Unable to start up

### ISSUE THREAD

**Issue by aarthi-subramanian** [ContinuumIO/anaconda-issues#12701]
Thanks for opening an issue! Please fill out the following template in full.

A few things to keep in mind:

- This issue tracker is for issues with installing Anaconda or Miniconda or with packages built by Anaconda, Inc. like Anaconda Navigator. It is also a place to request packages or other enhancements of the Anaconda Distribution.

- Anaconda Community Code of Conduct: https://www.anaconda.com/community-code-of-conduct/

- For conda issues, you should open an issue at https://github.com/conda/conda/issues

- For conda-build issues, you should open an issue at https://github.com/conda/conda-build

- For an issue with a particular conda-forge package, you should open an issue on the corresponding feedstock: https://github.com/conda-forge

##### `conda info`

<details>

```
PASTE OUTPUT HERE:

```

</details>

##### `conda list --show-channel-urls`

<details>

```
PASTE OUTPUT HERE:

```

</details>

**Comment by aarthi-subramanian** [comment]
```
Navigator Error
An unexpected error occurred on Navigator start-up

Report
Please report this issue in the anaconda issue tracker

Main Error
/Users/aarthisubramanian/.continuum/anaconda-client: Permission denied
Traceback
Traceback (most recent call last):
  File "/Users/aarthisubramanian/opt/anaconda3/lib/python3.8/site-packages/binstar_client/utils/config.py", line 273, in save_config
    os.makedirs(data_dir)
  File "/Users/aarthisubramanian/opt/anaconda3/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/Users/aarthisubramanian/.continuum/anaconda-client'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/aarthisubramanian/opt/anaconda3/lib/python3.8/site-packages/anaconda_navigator/exceptions.py", line 72, in exception_handler
    return_value = func(*args, **kwargs)
  File "/Users/aarthisubramanian/opt/anaconda3/lib/python3.8/site-packages/anaconda_navigator/app/start.py", line 146, in start_app
    window = run_app(splash)
  File "/Users/aarthisubramanian/opt/anaconda3/lib/python3.8/site-packages/anaconda_navigator/app/start.py", line 65, in run_app
    window = MainWindow(splash=splash)
  File "/Users/aarthisubramanian/opt/anaconda3/lib/python3.8/site-packages/anaconda_navigator/widgets/main_window.py", line 165, in __init__
    self.api = AnacondaAPI()
  File "/Users/aarthisubramanian/opt/anaconda3/lib/python3.8/site-packages/anaconda_navigator/api/anaconda_api.py", line 1518, in AnacondaAPI
    ANACONDA_API = _AnacondaAPI()
  File "/Users/aarthisubramanian/opt/anaconda3/lib/python3.8/site-packages/anaconda_navigator/api/anaconda_api.py", line 83, in __init__
    self._client_api = ClientAPI(config=self.config)
  File "/Users/aarthisubramanian/opt/anaconda3/lib/python3.8/site-packages/anaconda_navigator/api/client_api.py", line 659, in ClientAPI
    CLIENT_API = _ClientAPI(config=config)
  File "/Users/aarthisubramanian/opt/anaconda3/lib/python3.8/site-packages/anaconda_navigator/api/client_api.py", line 95, in __init__
    self.reload_client()
  File "/Users/aarthisubramanian/opt/anaconda3/lib/python3.8/site-packages/anaconda_navigator/api/client_api.py", line 325, in reload_client
    client = self._load_binstar_client(url)
  File "/Users/aarthisubramanian/opt/anaconda3/lib/python3.8/site-packages/anaconda_navigator/api/client_api.py", line 357, in _load_binstar_client
    binstar_client.utils.set_config(config)
  File "/Users/aarthisubramanian/opt/anaconda3/lib/python3.8/site-packages/binstar_client/utils/config.py", line 283, in set_config
    save_config(data, USER_CONFIG if user else SYSTEM_CONFIG)
  File "/Users/aarthisubramanian/opt/anaconda3/lib/python3.8/site-packages/binstar_client/utils/config.py", line 278, in save_config
    raise BinstarError('%s: %s' % (exc.filename, exc.strerror,))
binstar_client.errors.BinstarError: /Users/aarthisubramanian/.continuum/anaconda-client: Permission denied
```

**Comment by jinzaizhichi** [comment]
Close proxy

**Comment by jinzaizhichi** [comment]
@aarthi-subramanian  Close proxy
