### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by Mido4life** [ContinuumIO/anaconda-issues#12711]
Traceback
Traceback (most recent call last):
  File "C:\Users\josep\anaconda3\lib\site-packages\binstar_client\utils\config.py", line 275, in save_config
    with open(config_file, 'w') as fd:
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\josep\\.continuum\\anaconda-client\\config.yaml'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\josep\anaconda3\lib\site-packages\anaconda_navigator\exceptions.py", line 72, in exception_handler
    return_value = func(*args, **kwargs)
  File "C:\Users\josep\anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 146, in start_app
    window = run_app(splash)
  File "C:\Users\josep\anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 65, in run_app
    window = MainWindow(splash=splash)
  File "C:\Users\josep\anaconda3\lib\site-packages\anaconda_navigator\widgets\main_window\__init__.py", line 228, in __init__
    self.api = AnacondaAPI()
  File "C:\Users\josep\anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 1587, in AnacondaAPI
    ANACONDA_API = _AnacondaAPI()
  File "C:\Users\josep\anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 82, in __init__
    self._client_api = ClientAPI(config=self.config)
  File "C:\Users\josep\anaconda3\lib\site-packages\anaconda_navigator\api\client_api.py", line 660, in ClientAPI
    CLIENT_API = _ClientAPI(config=config)
  File "C:\Users\josep\anaconda3\lib\site-packages\anaconda_navigator\api\client_api.py", line 95, in __init__
    self.reload_client()
  File "C:\Users\josep\anaconda3\lib\site-packages\anaconda_navigator\api\client_api.py", line 325, in reload_client
    client = self._load_binstar_client(url)
  File "C:\Users\josep\anaconda3\lib\site-packages\anaconda_navigator\api\client_api.py", line 357, in _load_binstar_client
    binstar_client.utils.set_config(config)
  File "C:\Users\josep\anaconda3\lib\site-packages\binstar_client\utils\config.py", line 283, in set_config
    save_config(data, USER_CONFIG if user else SYSTEM_CONFIG)
  File "C:\Users\josep\anaconda3\lib\site-packages\binstar_client\utils\config.py", line 278, in save_config
    raise BinstarError('%s: %s' % (exc.filename, exc.strerror,))
binstar_client.errors.BinstarError: C:\Users\josep\.continuum\anaconda-client\config.yaml: Permission denied

**Comment by csoja** [comment]
C:\Users\josep\.continuum\anaconda-client\config.yaml  <- If you backup this file to config.old and then delete config.yaml, I think you'll be able to launch Navigator again.
