### ISSUE TITLE
start navigator error

### ISSUE THREAD

**Issue by anna-forest** [ContinuumIO/anaconda-issues#12734]
Navigator Error
An unexpected error occurred on Navigator start-up

Report
Please report this issue in the anaconda issue tracker

Main Error
unacceptable character #x0000: special characters are not allowed
  in "C:\Users\Administrator\.continuum\anaconda-client\config.yaml", position 0
Traceback
Traceback (most recent call last):
  File "D:\xin\anzhuang\anaconda3\lib\site-packages\anaconda_navigator\exceptions.py", line 72, in exception_handler
    return_value = func(*args, **kwargs)
  File "D:\xin\anzhuang\anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 146, in start_app
    window = run_app(splash)
  File "D:\xin\anzhuang\anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 65, in run_app
    window = MainWindow(splash=splash)
  File "D:\xin\anzhuang\anaconda3\lib\site-packages\anaconda_navigator\widgets\main_window.py", line 165, in __init__
    self.api = AnacondaAPI()
  File "D:\xin\anzhuang\anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 1518, in AnacondaAPI
    ANACONDA_API = _AnacondaAPI()
  File "D:\xin\anzhuang\anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 83, in __init__
    self._client_api = ClientAPI(config=self.config)
  File "D:\xin\anzhuang\anaconda3\lib\site-packages\anaconda_navigator\api\client_api.py", line 659, in ClientAPI
    CLIENT_API = _ClientAPI(config=config)
  File "D:\xin\anzhuang\anaconda3\lib\site-packages\anaconda_navigator\api\client_api.py", line 95, in __init__
    self.reload_client()
  File "D:\xin\anzhuang\anaconda3\lib\site-packages\anaconda_navigator\api\client_api.py", line 322, in reload_client
    url = binstar_client.utils.get_config()['url']
  File "D:\xin\anzhuang\anaconda3\lib\site-packages\binstar_client\utils\config.py", line 249, in get_config
    file_configs = load_file_configs(SEARCH_PATH)
  File "D:\xin\anzhuang\anaconda3\lib\site-packages\binstar_client\utils\config.py", line 241, in load_file_configs
    raw_data = collections.OrderedDict(kv for kv in itertools.chain.from_iterable(load_paths))
  File "D:\xin\anzhuang\anaconda3\lib\site-packages\binstar_client\utils\config.py", line 241, in 
    raw_data = collections.OrderedDict(kv for kv in itertools.chain.from_iterable(load_paths))
  File "D:\xin\anzhuang\anaconda3\lib\site-packages\binstar_client\utils\config.py", line 221, in _dir_yaml_loader
    yield filepath, load_config(filepath)
  File "D:\xin\anzhuang\anaconda3\lib\site-packages\binstar_client\utils\config.py", line 205, in load_config
    data = yaml_load(fd)
  File "D:\xin\anzhuang\anaconda3\lib\site-packages\binstar_client\utils\yaml.py", line 12, in yaml_load
    return safe_load(stream)
  File "D:\xin\anzhuang\anaconda3\lib\site-packages\yaml\__init__.py", line 162, in safe_load
    return load(stream, SafeLoader)
  File "D:\xin\anzhuang\anaconda3\lib\site-packages\yaml\__init__.py", line 112, in load
    loader = Loader(stream)
  File "D:\xin\anzhuang\anaconda3\lib\site-packages\yaml\loader.py", line 34, in __init__
    Reader.__init__(self, stream)
  File "D:\xin\anzhuang\anaconda3\lib\site-packages\yaml\reader.py", line 85, in __init__
    self.determine_encoding()
  File "D:\xin\anzhuang\anaconda3\lib\site-packages\yaml\reader.py", line 135, in determine_encoding
    self.update(1)
  File "D:\xin\anzhuang\anaconda3\lib\site-packages\yaml\reader.py", line 169, in update
    self.check_printable(data)
  File "D:\xin\anzhuang\anaconda3\lib\site-packages\yaml\reader.py", line 143, in check_printable
    raise ReaderError(self.name, position, ord(character),
yaml.reader.ReaderError: unacceptable character #x0000: special characters are not allowed
  in "C:\Users\Administrator\.continuum\anaconda-client\config.yaml", position 0

**Comment by RPChinhara-202117** [comment]
Navigator Error
An unexpected error occurred on Navigator start-up

Report
Please report this issue in the anaconda issue tracker

Main Error
C:\Users\rpchi\.continuum\anaconda-client\config.yaml: Permission denied
Traceback
Traceback (most recent call last):
  File "C:\Users\rpchi\Anaconda\lib\site-packages\binstar_client\utils\config.py", line 276, in save_config
    with open(config_file, 'w') as fd:
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\rpchi\\.continuum\\anaconda-client\\config.yaml'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\rpchi\Anaconda\lib\site-packages\anaconda_navigator\exceptions.py", line 72, in exception_handler
    return_value = func(*args, **kwargs)
  File "C:\Users\rpchi\Anaconda\lib\site-packages\anaconda_navigator\app\start.py", line 151, in start_app
    window = run_app(splash)
  File "C:\Users\rpchi\Anaconda\lib\site-packages\anaconda_navigator\app\start.py", line 66, in run_app
    window = MainWindow(splash=splash)
  File "C:\Users\rpchi\Anaconda\lib\site-packages\anaconda_navigator\widgets\main_window\__init__.py", line 235, in __init__
    self.api = AnacondaAPI()
  File "C:\Users\rpchi\Anaconda\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 1442, in AnacondaAPI
    ANACONDA_API = _AnacondaAPI()
  File "C:\Users\rpchi\Anaconda\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 80, in __init__
    self._client_api = ClientAPI(config=self.config)
  File "C:\Users\rpchi\Anaconda\lib\site-packages\anaconda_navigator\api\client_api.py", line 650, in ClientAPI
    CLIENT_API = _ClientAPI(config=config)
  File "C:\Users\rpchi\Anaconda\lib\site-packages\anaconda_navigator\api\client_api.py", line 94, in __init__
    self.reload_client()
  File "C:\Users\rpchi\Anaconda\lib\site-packages\anaconda_navigator\api\client_api.py", line 324, in reload_client
    client = self._load_binstar_client(url)
  File "C:\Users\rpchi\Anaconda\lib\site-packages\anaconda_navigator\api\client_api.py", line 355, in _load_binstar_client
    binstar_client.utils.set_config(config)
  File "C:\Users\rpchi\Anaconda\lib\site-packages\binstar_client\utils\config.py", line 284, in set_config
    save_config(data, USER_CONFIG if user else SYSTEM_CONFIG)
  File "C:\Users\rpchi\Anaconda\lib\site-packages\binstar_client\utils\config.py", line 279, in save_config
    raise BinstarError('%s: %s' % (exc.filename, exc.strerror,))
binstar_client.errors.BinstarError: C:\Users\rpchi\.continuum\anaconda-client\config.yaml: Permission denied

**Comment by AnishaMathur** [comment]
Navigator Error
An unexpected error occurred on Navigator start-up

Report
Please report this issue in the anaconda issue tracker

Main Error
'NoneType' object has no attribute 'split'
Traceback
Traceback (most recent call last):
  File "/Users/anishamathur/opt/anaconda3/lib/python3.8/site-packages/anaconda_navigator/exceptions.py", line 72, in exception_handler
    return_value = func(*args, **kwargs)
  File "/Users/anishamathur/opt/anaconda3/lib/python3.8/site-packages/anaconda_navigator/app/start.py", line 146, in start_app
    window = run_app(splash)
  File "/Users/anishamathur/opt/anaconda3/lib/python3.8/site-packages/anaconda_navigator/app/start.py", line 65, in run_app
    window = MainWindow(splash=splash)
  File "/Users/anishamathur/opt/anaconda3/lib/python3.8/site-packages/anaconda_navigator/widgets/main_window/__init__.py", line 228, in __init__
    self.api = AnacondaAPI()
  File "/Users/anishamathur/opt/anaconda3/lib/python3.8/site-packages/anaconda_navigator/api/anaconda_api.py", line 1587, in AnacondaAPI
    ANACONDA_API = _AnacondaAPI()
  File "/Users/anishamathur/opt/anaconda3/lib/python3.8/site-packages/anaconda_navigator/api/anaconda_api.py", line 81, in __init__
    self._conda_api = CondaAPI()
  File "/Users/anishamathur/opt/anaconda3/lib/python3.8/site-packages/anaconda_navigator/api/conda_api.py", line 1668, in CondaAPI
    CONDA_API = _CondaAPI()
  File "/Users/anishamathur/opt/anaconda3/lib/python3.8/site-packages/anaconda_navigator/api/conda_api.py", line 330, in __init__
    self.set_conda_prefix(info=get_conda_info())
  File "/Users/anishamathur/opt/anaconda3/lib/python3.8/site-packages/anaconda_navigator/api/conda_api.py", line 488, in set_conda_prefix
    for part in info.get('conda_version').split('.'):
AttributeError: 'NoneType' object has no attribute 'split'

**Comment by sazzadurrahman** [comment]
**Navigator Error**
An unexpected error occurred on Navigator start-up

**Report**
Please report this issue in the anaconda issue tracker

**Main Error**
'root_prefix'
Traceback
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\anaconda_navigator\exceptions.py", line 75, in exception_handler
    return_value = func(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 150, in start_app
    window = run_app(splash)
  File "C:\ProgramData\Anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 65, in run_app
    window = MainWindow(splash=splash, tab_project=False)
  File "C:\ProgramData\Anaconda3\lib\site-packages\anaconda_navigator\widgets\main_window.py", line 163, in __init__
    self.api = AnacondaAPI()
  File "C:\ProgramData\Anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 2185, in AnacondaAPI
    ANACONDA_API = _AnacondaAPI()
  File "C:\ProgramData\Anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 89, in __init__
    self._conda_api = CondaAPI()
  File "C:\ProgramData\Anaconda3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 1714, in CondaAPI
    CONDA_API = _CondaAPI()
  File "C:\ProgramData\Anaconda3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 350, in __init__
    self.set_conda_prefix(info=get_conda_info())
  File "C:\ProgramData\Anaconda3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 505, in set_conda_prefix
    self.ROOT_PREFIX = info['root_prefix']
KeyError: 'root_prefix'
