### ISSUE TITLE
Anaconda-Navigator will not open on MacOS Catalina due to Permission denied error

### ISSUE THREAD

**Issue by skiiks9754** [ContinuumIO/anaconda-issues#12743]
### Expected Behavior

I expected that I could open Anaconda-Navigator

Steps to reproduce:
right click and select OPEN under Applications folder

##### Anaconda or Miniconda version:

Anaconda3-2021.11-MacOSX-x86_64.pkg

##### `conda info`

<details>

```
PASTE OUTPUT HERE:

```

</details>

##### `conda list --show-channel-urls`

<details>

```
Main Error
/Users//.continuum/anaconda-client: Permission denied
Traceback
Traceback (most recent call last):
  File "/Users/name/opt/anaconda3/lib/python3.9/site-packages/binstar_client/utils/config.py", line 274, in save_config
    os.makedirs(data_dir)
  File "/Users/name/opt/anaconda3/lib/python3.9/os.py", line 225, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/Users/name/.continuum/anaconda-client'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/name/opt/anaconda3/lib/python3.9/site-packages/anaconda_navigator/exceptions.py", line 72, in exception_handler
    return_value = func(*args, **kwargs)
  File "/Users/name/opt/anaconda3/lib/python3.9/site-packages/anaconda_navigator/app/start.py", line 151, in start_app
    window = run_app(splash)
  File "/Users/name/opt/anaconda3/lib/python3.9/site-packages/anaconda_navigator/app/start.py", line 66, in run_app
    window = MainWindow(splash=splash)
  File "/Users/name/opt/anaconda3/lib/python3.9/site-packages/anaconda_navigator/widgets/main_window/__init__.py", line 235, in __init__
    self.api = AnacondaAPI()
  File "/Users/name/opt/anaconda3/lib/python3.9/site-packages/anaconda_navigator/api/anaconda_api.py", line 1442, in AnacondaAPI
    ANACONDA_API = _AnacondaAPI()
  File "/Users/name/opt/anaconda3/lib/python3.9/site-packages/anaconda_navigator/api/anaconda_api.py", line 80, in __init__
    self._client_api = ClientAPI(config=self.config)
  File "/Users/name/opt/anaconda3/lib/python3.9/site-packages/anaconda_navigator/api/client_api.py", line 650, in ClientAPI
    CLIENT_API = _ClientAPI(config=config)
  File "/Users/name/opt/anaconda3/lib/python3.9/site-packages/anaconda_navigator/api/client_api.py", line 94, in __init__
    self.reload_client()
  File "/Users/name/opt/anaconda3/lib/python3.9/site-packages/anaconda_navigator/api/client_api.py", line 324, in reload_client
    client = self._load_binstar_client(url)
  File "/Users/name/opt/anaconda3/lib/python3.9/site-packages/anaconda_navigator/api/client_api.py", line 355, in _load_binstar_client
    binstar_client.utils.set_config(config)
  File "/Users/name/opt/anaconda3/lib/python3.9/site-packages/binstar_client/utils/config.py", line 284, in set_config
    save_config(data, USER_CONFIG if user else SYSTEM_CONFIG)
  File "/Users/name/opt/anaconda3/lib/python3.9/site-packages/binstar_client/utils/config.py", line 279, in save_config
    raise BinstarError('%s: %s' % (exc.filename, exc.strerror,))
binstar_client.errors.BinstarError: /Users/name/.continuum/anaconda-client: Permission denied


</details>

**Comment by csoja** [comment]
It looks like Anaconda Navigator does not have access to /Users/name/.continuum/anaconda-client  - if you can change the permissions to enable Navigator to access that directory, I expect it will open.  Or you could try an older version of Anaconda Navigator.
