### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by umair986** [ContinuumIO/anaconda-issues#12778]
### Actual Behavior

Main Error
unacceptable character #x0000: special characters are not allowed
  in "C:\Users\lenovo\.continuum\anaconda-client\config.yaml", position 0
Traceback
Traceback (most recent call last):
  File "C:\Users\lenovo\.conda\lib\site-packages\anaconda_navigator\exceptions.py", line 72, in exception_handler
    return_value = func(*args, **kwargs)
  File "C:\Users\lenovo\.conda\lib\site-packages\anaconda_navigator\app\start.py", line 151, in start_app
    window = run_app(splash)
  File "C:\Users\lenovo\.conda\lib\site-packages\anaconda_navigator\app\start.py", line 66, in run_app
    window = MainWindow(splash=splash)
  File "C:\Users\lenovo\.conda\lib\site-packages\anaconda_navigator\widgets\main_window\__init__.py", line 235, in __init__
    self.api = AnacondaAPI()
  File "C:\Users\lenovo\.conda\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 1442, in AnacondaAPI
    ANACONDA_API = _AnacondaAPI()
  File "C:\Users\lenovo\.conda\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 80, in __init__
    self._client_api = ClientAPI(config=self.config)
  File "C:\Users\lenovo\.conda\lib\site-packages\anaconda_navigator\api\client_api.py", line 650, in ClientAPI
    CLIENT_API = _ClientAPI(config=config)
  File "C:\Users\lenovo\.conda\lib\site-packages\anaconda_navigator\api\client_api.py", line 94, in __init__
    self.reload_client()
  File "C:\Users\lenovo\.conda\lib\site-packages\anaconda_navigator\api\client_api.py", line 321, in reload_client
    url = binstar_client.utils.get_config()['url']
  File "C:\Users\lenovo\.conda\lib\site-packages\binstar_client\utils\config.py", line 250, in get_config
    file_configs = load_file_configs(SEARCH_PATH)
  File "C:\Users\lenovo\.conda\lib\site-packages\binstar_client\utils\config.py", line 242, in load_file_configs
    raw_data = collections.OrderedDict(kv for kv in itertools.chain.from_iterable(load_paths))
  File "C:\Users\lenovo\.conda\lib\site-packages\binstar_client\utils\config.py", line 242, in 
    raw_data = collections.OrderedDict(kv for kv in itertools.chain.from_iterable(load_paths))
  File "C:\Users\lenovo\.conda\lib\site-packages\binstar_client\utils\config.py", line 222, in _dir_yaml_loader
    yield filepath, load_config(filepath)
  File "C:\Users\lenovo\.conda\lib\site-packages\binstar_client\utils\config.py", line 206, in load_config
    data = yaml_load(fd)
  File "C:\Users\lenovo\.conda\lib\site-packages\binstar_client\utils\yaml.py", line 12, in yaml_load
    return safe_load(stream)
  File "C:\Users\lenovo\.conda\lib\site-packages\yaml\__init__.py", line 125, in safe_load
    return load(stream, SafeLoader)
  File "C:\Users\lenovo\.conda\lib\site-packages\yaml\__init__.py", line 79, in load
    loader = Loader(stream)
  File "C:\Users\lenovo\.conda\lib\site-packages\yaml\loader.py", line 34, in __init__
    Reader.__init__(self, stream)
  File "C:\Users\lenovo\.conda\lib\site-packages\yaml\reader.py", line 85, in __init__
    self.determine_encoding()
  File "C:\Users\lenovo\.conda\lib\site-packages\yaml\reader.py", line 135, in determine_encoding
    self.update(1)
  File "C:\Users\lenovo\.conda\lib\site-packages\yaml\reader.py", line 169, in update
    self.check_printable(data)
  File "C:\Users\lenovo\.conda\lib\site-packages\yaml\reader.py", line 143, in check_printable
    raise ReaderError(self.name, position, ord(character),
yaml.reader.ReaderError: unacceptable character #x0000: special characters are not allowed
  in "C:\Users\lenovo\.continuum\anaconda-client\config.yaml", position 0
### Expected Behavior

it wasnt giving this error until yesterday. today suddenly it started giving me this error i've reinstalled the anaconda navigator 4-5 times but still it gives the same error

### Steps to Reproduce

idk pls help as iwant to continue my udemy course 

##### Operating System:
windows 10 64 bit 
##### `conda info`

<details>

```
PASTE OUTPUT HERE:

```

</details>

##### `conda list --show-channel-urls`

<details>

```
PASTE OUTPUT HERE:

```

</details>

**Comment by csoja** [comment]
Looks like C:\Users\lenovo.continuum\anaconda-client\config.yaml has gotten corrupted - perhaps if you rename this file to config.old, and then try to start Navigator, it will launch as expected.
