### ISSUE TITLE
Navigator error - An unexpected error occurred on Navigator start-up

### ISSUE THREAD

**Issue by tiwooksj** [ContinuumIO/anaconda-issues#12782]
i am windows 10 pro user
and i tried to install the latest version (Anaconda3-2021.11-Windows-x86_64)
but i keep facing this issues. please help how to fix it.

Navigator Error
An unexpected error occurred on Navigator start-up

Report
Please report this issue in the anaconda issue tracker

Main Error
'list' object has no attribute 'get'
Traceback
Traceback (most recent call last):
  File "C:\Users\USER\Anaconda3\lib\site-packages\anaconda_navigator\exceptions.py", line 72, in exception_handler
    return_value = func(*args, **kwargs)
  File "C:\Users\USER\Anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 151, in start_app
    window = run_app(splash)
  File "C:\Users\USER\Anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 66, in run_app
    window = MainWindow(splash=splash)
  File "C:\Users\USER\Anaconda3\lib\site-packages\anaconda_navigator\widgets\main_window\__init__.py", line 235, in __init__
    self.api = AnacondaAPI()
  File "C:\Users\USER\Anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 1442, in AnacondaAPI
    ANACONDA_API = _AnacondaAPI()
  File "C:\Users\USER\Anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 79, in __init__
    self._conda_api = CondaAPI()
  File "C:\Users\USER\Anaconda3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 1813, in CondaAPI
    CONDA_API = _CondaAPI()
  File "C:\Users\USER\Anaconda3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 495, in __init__
    self.set_conda_prefix(info=get_conda_info())
  File "C:\Users\USER\Anaconda3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 655, in set_conda_prefix
    self.ROOT_PREFIX = info.get('root_prefix')  # str
AttributeError: 'list' object has no attribute 'get'

**Comment by cooltnt** [comment]
win10,  Anaconda3-2022.05-Windows-x86_64.exe
