### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by JAY-007-TRIVEDI** [ContinuumIO/anaconda-issues#12786]
Navigator Error
An unexpected error occurred on Navigator start-up

Report
Please report this issue in the anaconda issue tracker

Main Error
unacceptable character #x0000: special characters are not allowed
  in "C:\Users\Hp\.continuum\anaconda-client\config.yaml", position 0
Traceback
Traceback (most recent call last):
  File "D:\anaconda3\lib\site-packages\anaconda_navigator\exceptions.py", line 72, in exception_handler
    return_value = func(*args, **kwargs)
  File "D:\anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 151, in start_app
    window = run_app(splash)
  File "D:\anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 66, in run_app
    window = MainWindow(splash=splash)
  File "D:\anaconda3\lib\site-packages\anaconda_navigator\widgets\main_window\__init__.py", line 235, in __init__
    self.api = AnacondaAPI()
  File "D:\anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 1442, in AnacondaAPI
    ANACONDA_API = _AnacondaAPI()
  File "D:\anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 80, in __init__
    self._client_api = ClientAPI(config=self.config)
  File "D:\anaconda3\lib\site-packages\anaconda_navigator\api\client_api.py", line 650, in ClientAPI
    CLIENT_API = _ClientAPI(config=config)
  File "D:\anaconda3\lib\site-packages\anaconda_navigator\api\client_api.py", line 94, in __init__
    self.reload_client()
  File "D:\anaconda3\lib\site-packages\anaconda_navigator\api\client_api.py", line 321, in reload_client
    url = binstar_client.utils.get_config()['url']
  File "D:\anaconda3\lib\site-packages\binstar_client\utils\config.py", line 250, in get_config
    file_configs = load_file_configs(SEARCH_PATH)
  File "D:\anaconda3\lib\site-packages\binstar_client\utils\config.py", line 242, in load_file_configs
    raw_data = collections.OrderedDict(kv for kv in itertools.chain.from_iterable(load_paths))
  File "D:\anaconda3\lib\site-packages\binstar_client\utils\config.py", line 242, in 
    raw_data = collections.OrderedDict(kv for kv in itertools.chain.from_iterable(load_paths))
  File "D:\anaconda3\lib\site-packages\binstar_client\utils\config.py", line 222, in _dir_yaml_loader
    yield filepath, load_config(filepath)
  File "D:\anaconda3\lib\site-packages\binstar_client\utils\config.py", line 206, in load_config
    data = yaml_load(fd)
  File "D:\anaconda3\lib\site-packages\binstar_client\utils\yaml.py", line 12, in yaml_load
    return safe_load(stream)
  File "D:\anaconda3\lib\site-packages\yaml\__init__.py", line 125, in safe_load
    return load(stream, SafeLoader)
  File "D:\anaconda3\lib\site-packages\yaml\__init__.py", line 79, in load
    loader = Loader(stream)
  File "D:\anaconda3\lib\site-packages\yaml\loader.py", line 34, in __init__
    Reader.__init__(self, stream)
  File "D:\anaconda3\lib\site-packages\yaml\reader.py", line 85, in __init__
    self.determine_encoding()
  File "D:\anaconda3\lib\site-packages\yaml\reader.py", line 135, in determine_encoding
    self.update(1)
  File "D:\anaconda3\lib\site-packages\yaml\reader.py", line 169, in update
    self.check_printable(data)
  File "D:\anaconda3\lib\site-packages\yaml\reader.py", line 143, in check_printable
    raise ReaderError(self.name, position, ord(character),
yaml.reader.ReaderError: unacceptable character #x0000: special characters are not allowed
  in "C:\Users\Hp\.continuum\anaconda-client\config.yaml", position 0

**Comment by csoja** [comment]
Looks like your anaconda-client configuration file got corrupted.  I'd recommend renaming it - C:\Users\Hp.continuum\anaconda-client\config.yaml  -> C:\Users\Hp.continuum\anaconda-client\config.old and then attempting to start Navigator again.
