### ISSUE TITLE
TypeError:  expected str, bytes or os.PathLike object, not NoneType

### ISSUE THREAD

**Issue by chrisf62** [ContinuumIO/anaconda-issues#12785]
### Actual Behavior

Navigator doesn't fully start up.  Starts to initialize, then crashes.  I can see the navigator logo briefly before crash

### Expected Behavior

Navigator Should start up

### Steps to Reproduce

I downloaded Anaconda3-5.3.1-Windows-x86_64.exe from https://repo.anaconda.com/archive/

I checked the hashes and they matched -- 295FED5940369D4EA1E2C6D04D418619D9942C19D925921CBEB941BBC5BD7659

I turned off the firewall and virus software and then initiated the exe file with the default settings for "just me" as a user

##### Anaconda or Miniconda version:

Anaconda3-5.3.1-Windows-x86_64.exe

##### Operating System:
Windows 10 Pro 
version 20H2 
installed 2/11/2021 
Build 19042.1415 
Experience Windows Feature Experience Pack 120.2212.3920.0
##### 

```
Main Error
expected str, bytes or os.PathLike object, not NoneType
Traceback
Traceback (most recent call last):
  File "C:\Users\chris\Anaconda3\lib\site-packages\anaconda_navigator\exceptions.py", line 75, in exception_handler
    return_value = func(*args, **kwargs)
  File "C:\Users\chris\Anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 150, in start_app
    window = run_app(splash)
  File "C:\Users\chris\Anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 65, in run_app
    window = MainWindow(splash=splash, tab_project=False)
  File "C:\Users\chris\Anaconda3\lib\site-packages\anaconda_navigator\widgets\main_window.py", line 168, in __init__
    self.api = AnacondaAPI()
  File "C:\Users\chris\Anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 2294, in AnacondaAPI
    ANACONDA_API = _AnacondaAPI()
  File "C:\Users\chris\Anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 91, in __init__
    self._conda_api = CondaAPI()
  File "C:\Users\chris\Anaconda3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 1767, in CondaAPI
    CONDA_API = _CondaAPI()
  File "C:\Users\chris\Anaconda3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 353, in __init__
    self.sys_rc_path = join(self.ROOT_PREFIX, '.condarc')
  File "C:\Users\chris\Anaconda3\lib\ntpath.py", line 76, in join
    path = os.fspath(path)
TypeError: expected str, bytes or os.PathLike object, not NoneType

```

</details>

##### `conda list --show-channel-urls`

<details>

```
PASTE OUTPUT HERE:

```

</details>

**Comment by mccurcio** [comment]
Ditto, 
conda 4.11.0
on:
Edition	Windows 11 Home
Version	21H2
Installed on	‎10/‎12
OS build	22000.376
Experience	Windows Feature Experience Pack 1000.22000.376.0

 conda info

     active environment : base
    active env location : C:\Users\user\anaconda3
            shell level : 1
       user config file : C:\Users\user\.condarc
 populated config files : C:\Users\user\.condarc
          conda version : 4.11.0
    conda-build version : 3.21.6
         python version : 3.9.7.final.0
       virtual packages : __win=0=0
                          __archspec=1=x86_64
       base environment : C:\Users\user\anaconda3  (writable)
      conda av data dir : C:\Users\user\anaconda3\etc\conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/win-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\Users\user\anaconda3\pkgs
                          C:\Users\user\.conda\pkgs
                          C:\Users\user\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\mockr\anaconda3\envs
                          C:\Users\user\.conda\envs
                          C:\Users\user\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.11.0 requests/2.26.0 CPython/3.9.7 Windows/10 Windows/10.0.22000
          administrator : False
             netrc file : None
           offline mode : False
