### ISSUE TITLE
Anaconda initializing 

### ISSUE THREAD

**Issue by andradron** [ContinuumIO/anaconda-issues#1279]
while launching anaconda the icon of program stuck and initializing doesn't go forward .I've already tried to reinstall python and anaconda.Python 2.7.12   anaconda 4.2.0

**Comment by ajohns13** [comment]
I'm seeing the same issue for the GUI application with python 2.7.11 and Anaconda 4.3.0

**Comment by goanpeca** [comment]
If you go to the command prompt and type:

`anaconda-navigator` what is the output you see?

**Comment by ajohns13** [comment]
I ended up running with the CLI fine. But I replicated the issue and I get a `Permission denied` response. Let me know if you want to see a full trace.

**Comment by goanpeca** [comment]
@ajohns13 could you paste the issue? I know how to fix it :-), but need to see the erro

**Comment by ajohns13** [comment]
```Traceback (most recent call last):
  File "/Users/TommyJohnson/anaconda2/bin/anaconda-navigator", line 6, in <module>
    sys.exit(anaconda_navigator.app.main.main())
  File "/Users/TommyJohnson/anaconda2/lib/python2.7/site-packages/anaconda_navigator/app/main.py", line 52, in main
    start_app(options)
  File "/Users/TommyJohnson/anaconda2/lib/python2.7/site-packages/anaconda_navigator/app/start.py", line 87, in start_app
    window = run_app(splash)
  File "/Users/TommyJohnson/anaconda2/lib/python2.7/site-packages/anaconda_navigator/app/start.py", line 42, in run_app
    window = MainWindow(splash=splash)
  File "/Users/TommyJohnson/anaconda2/lib/python2.7/site-packages/anaconda_navigator/widgets/main_window.py", line 204, in __init__
    self.environments_tab = EnvironmentsTab(parent=self)
  File "/Users/TommyJohnson/anaconda2/lib/python2.7/site-packages/anaconda_navigator/widgets/tabs/environments.py", line 131, in __init__
    data_directory=CHANNELS_PATH,
  File "/Users/TommyJohnson/anaconda2/lib/python2.7/site-packages/anaconda_navigator/widgets/manager/packages.py", line 382, in __init__
    self.api.client_set_domain(self.api.client_get_api_url())
  File "/Users/TommyJohnson/anaconda2/lib/python2.7/site-packages/anaconda_navigator/api/client_api.py", line 365, in set_domain
    binstar_client.utils.set_config(config)
  File "/Users/TommyJohnson/anaconda2/lib/python2.7/site-packages/binstar_client/utils/config.py", line 260, in set_config
    save_config(data, USER_CONFIG if user else SYSTEM_CONFIG)
  File "/Users/TommyJohnson/anaconda2/lib/python2.7/site-packages/binstar_client/utils/config.py", line 255, in save_config
    raise BinstarError('%s: %s' % (exc.filename, exc.strerror,))
binstar_client.errors.BinstarError: /Users/TommyJohnson/.continuum/anaconda-client: Permission denied```

@goanpeca sorry for the delay, hope this helps

**Comment by goanpeca** [comment]
Hi @ajohns13 you need to run from the terminal

`sudo rm -rf ~/.continuum/`

That should remove the folder that has the wrong permissions so that navigator can recreate it with the correct access.
