### ISSUE TITLE
ipython qtconsole dies

### ISSUE THREAD

**Issue by asmeurer** [ContinuumIO/anaconda-issues#128]
This is in Python 3. The qtconsole kernel keeps dying with

``` pytb
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/aaronmeurer/anaconda/envs/test/lib/python3.4/site-packages/IPython/__init__.py", line 45, in <module>
    from .config.loader import Config
  File "/Users/aaronmeurer/anaconda/envs/test/lib/python3.4/site-packages/IPython/config/__init__.py", line 16, in <module>
    from .application import *
  File "/Users/aaronmeurer/anaconda/envs/test/lib/python3.4/site-packages/IPython/config/application.py", line 30, in <module>
    from IPython.external.decorator import decorator
ImportError: cannot import name 'decorator'
```

**Comment by nehaljwani** [comment]
Closing, as `Python 3.4` is no longer supported
