### ISSUE TITLE
Navigation start-up error

### ISSUE THREAD

**Issue by samer-sarakbi** [ContinuumIO/anaconda-issues#12805]
Thanks for opening an issue! Please fill out the following template in full.

A few things to keep in mind:

- This issue tracker is for issues with installing Anaconda or Miniconda or with packages built by Anaconda, Inc. like Anaconda Navigator. It is also a place to request packages or other enhancements of the Anaconda Distribution.

- Anaconda Community Code of Conduct: https://www.anaconda.com/community-code-of-conduct/

- For conda issues, you should open an issue at https://github.com/conda/conda/issues

- For conda-build issues, you should open an issue at https://github.com/conda/conda-build

- For an issue with a particular conda-forge package, you should open an issue on the corresponding feedstock: https://github.com/conda-forge

### Actual Behavior
Trying to open the App is doesn't open and gives an error

### Expected Behavior

open the app

### Steps to Reproduce

Open the app from windows start up menu

##### Operating System: windows 
Device name	SLB-GN076M2
Full device name	SLB-GN076M2.DIR.slb.com
Processor	Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz   2.70 GHz
Installed RAM	32.0 GB (31.9 GB usable)
Device ID	0852fd20-8bf7-4e00-9592-03161db04b3b
Product ID	00329-00000-00003-AA916
System type	64-bit operating system, x64-based processor
Pen and touch	No pen or touch input is available for this display

##### `conda info`

<details>

```
PASTE OUTPUT HERE:

```

</details>

##### `conda list --show-channel-urls`

<details>

```
PASTE OUTPUT HERE:

```

Main Error
'bytes' object has no attribute 'get'
Traceback
Traceback (most recent call last):
  File "C:\Users\salsarakbi\Anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 147, in start_app
    with lock.acquire(timeout=3.0):  # timeout in seconds
  File "C:\Users\salsarakbi\Anaconda3\lib\site-packages\anaconda_navigator\external\filelock.py", line 246, in acquire
    raise Timeout(self._lock_file)
anaconda_navigator.external.filelock.Timeout: The file lock 'C:\Users\salsarakbi\AppData\Roaming\.anaconda\navigator\.anaconda\navigator\navigator.lock' could not be acquired.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\salsarakbi\Anaconda3\lib\site-packages\anaconda_navigator\exceptions.py", line 72, in exception_handler
    return_value = func(*args, **kwargs)
  File "C:\Users\salsarakbi\Anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 157, in start_app
    msgbox = MessageBoxInformation(
  File "C:\Users\salsarakbi\Anaconda3\lib\site-packages\anaconda_navigator\widgets\dialogs\__init__.py", line 516, in __init__
    super().__init__(type_=self.INFORMATION_BOX, title=title, text=text, parent=parent)
  File "C:\Users\salsarakbi\Anaconda3\lib\site-packages\anaconda_navigator\widgets\dialogs\__init__.py", line 339, in __init__
    self.tracker = GATracker()
  File "C:\Users\salsarakbi\Anaconda3\lib\site-packages\anaconda_navigator\utils\analytics.py", line 260, in GATracker
    GA_TRACKER = _GATracker()
  File "C:\Users\salsarakbi\Anaconda3\lib\site-packages\anaconda_navigator\utils\analytics.py", line 98, in __init__
    self.api = AnacondaAPI()
  File "C:\Users\salsarakbi\Anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 1442, in AnacondaAPI
    ANACONDA_API = _AnacondaAPI()
  File "C:\Users\salsarakbi\Anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 79, in __init__
    self._conda_api = CondaAPI()
  File "C:\Users\salsarakbi\Anaconda3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 1813, in CondaAPI
    CONDA_API = _CondaAPI()
  File "C:\Users\salsarakbi\Anaconda3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 495, in __init__
    self.set_conda_prefix(info=get_conda_info())
  File "C:\Users\salsarakbi\Anaconda3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 655, in set_conda_prefix
    self.ROOT_PREFIX = info.get('root_prefix')  # str
AttributeError: 'bytes' object has no attribute 'get'

**Comment by samer-sarakbi** [comment]
Not able to open the App, repetitively
