### ISSUE TITLE
Navigator Load Error

### ISSUE THREAD

**Issue by deewor** [ContinuumIO/anaconda-issues#12810]
### Actual Behavior

Navigator Error
An unexpected error occurred on Navigator start-up

Report
Please report this issue in the anaconda issue tracker

Main Error
/Users/wor/.continuum/anaconda-client: Permission denied
Traceback
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.9/site-packages/binstar_client/utils/config.py", line 274, in save_config
    os.makedirs(data_dir)
  File "/opt/anaconda3/lib/python3.9/os.py", line 225, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/Users/wor/.continuum/anaconda-client'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.9/site-packages/anaconda_navigator/exceptions.py", line 72, in exception_handler
    return_value = func(*args, **kwargs)
  File "/opt/anaconda3/lib/python3.9/site-packages/anaconda_navigator/app/start.py", line 151, in start_app
    window = run_app(splash)
  File "/opt/anaconda3/lib/python3.9/site-packages/anaconda_navigator/app/start.py", line 66, in run_app
    window = MainWindow(splash=splash)
  File "/opt/anaconda3/lib/python3.9/site-packages/anaconda_navigator/widgets/main_window/__init__.py", line 235, in __init__
    self.api = AnacondaAPI()
  File "/opt/anaconda3/lib/python3.9/site-packages/anaconda_navigator/api/anaconda_api.py", line 1442, in AnacondaAPI
    ANACONDA_API = _AnacondaAPI()
  File "/opt/anaconda3/lib/python3.9/site-packages/anaconda_navigator/api/anaconda_api.py", line 80, in __init__
    self._client_api = ClientAPI(config=self.config)
  File "/opt/anaconda3/lib/python3.9/site-packages/anaconda_navigator/api/client_api.py", line 650, in ClientAPI
    CLIENT_API = _ClientAPI(config=config)
  File "/opt/anaconda3/lib/python3.9/site-packages/anaconda_navigator/api/client_api.py", line 94, in __init__
    self.reload_client()
  File "/opt/anaconda3/lib/python3.9/site-packages/anaconda_navigator/api/client_api.py", line 324, in reload_client
    client = self._load_binstar_client(url)
  File "/opt/anaconda3/lib/python3.9/site-packages/anaconda_navigator/api/client_api.py", line 355, in _load_binstar_client
    binstar_client.utils.set_config(config)
  File "/opt/anaconda3/lib/python3.9/site-packages/binstar_client/utils/config.py", line 284, in set_config
    save_config(data, USER_CONFIG if user else SYSTEM_CONFIG)
  File "/opt/anaconda3/lib/python3.9/site-packages/binstar_client/utils/config.py", line 279, in save_config
    raise BinstarError('%s: %s' % (exc.filename, exc.strerror,))
binstar_client.errors.BinstarError: /Users/wor/.continuum/anaconda-client: Permission denied

### Expected Behavior

Navigator should load without error

##### Operating System:
OSX 10.15.7
##### `conda info`

<details>

```
PASTE OUTPUT HERE:

```

</details>

##### `conda list --show-channel-urls`

<details>

```
PASTE OUTPUT HERE:

```

</details>

**Comment by Xomox4** [comment]
I have the very same issue  and persisting. No amount of culling the existing version and reinstalling appears to solve the problem that the lauchpad icon is unresponsive to clicking. Going into the 'Finder' /Applications and clicking on the anaconda navigator makes the icon wobble as it seems to be loading the app but then ends up as the error dump (attached) in a Safari page
[Navigator Error.pdf](https://github.com/ContinuumIO/anaconda-issues/files/7933106/Navigator.Error.pdf)
.
