### ISSUE TITLE
Could not find a suitable TLS CA certificate bundle, invalid path: True

### ISSUE THREAD

**Issue by himanshu-0611** [ContinuumIO/anaconda-issues#12829]
When I am trying to open anaconda navigator, it is redirecting to a web page on my web browser showing the following message:

```
An unexpected error occurred on Navigator start-up
Report

Please report this issue in the anaconda issue tracker
Main Error

Could not find a suitable TLS CA certificate bundle, invalid path: True

Traceback

Traceback (most recent call last):
  File "F:\anaconda\lib\site-packages\anaconda_navigator\exceptions.py", line 72, in exception_handler
    return_value = func(*args, **kwargs)
  File "F:\anaconda\lib\site-packages\anaconda_navigator\app\start.py", line 151, in start_app
    window = run_app(splash)
  File "F:\anaconda\lib\site-packages\anaconda_navigator\app\start.py", line 66, in run_app
    window = MainWindow(splash=splash)
  File "F:\anaconda\lib\site-packages\anaconda_navigator\widgets\main_window\__init__.py", line 235, in __init__
    self.api = AnacondaAPI()
  File "F:\anaconda\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 1442, in AnacondaAPI
    ANACONDA_API = _AnacondaAPI()
  File "F:\anaconda\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 80, in __init__
    self._client_api = ClientAPI(config=self.config)
  File "F:\anaconda\lib\site-packages\anaconda_navigator\api\client_api.py", line 650, in ClientAPI
    CLIENT_API = _ClientAPI(config=config)
  File "F:\anaconda\lib\site-packages\anaconda_navigator\api\client_api.py", line 94, in __init__
    self.reload_client()
  File "F:\anaconda\lib\site-packages\anaconda_navigator\api\client_api.py", line 325, in reload_client
    client.user()
  File "F:\anaconda\lib\site-packages\binstar_client\__init__.py", line 241, in user
    res = self.session.get(url, verify=self.session.verify)
  File "C:\Users\HP\AppData\Roaming\Python\Python39\site-packages\requests\sessions.py", line 555, in get
    return self.request('GET', url, **kwargs)
  File "C:\Users\HP\AppData\Roaming\Python\Python39\site-packages\requests\sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\HP\AppData\Roaming\Python\Python39\site-packages\requests\sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\HP\AppData\Roaming\Python\Python39\site-packages\requests\adapters.py", line 416, in send
    self.cert_verify(conn, request.url, verify, cert)
  File "C:\Users\HP\AppData\Roaming\Python\Python39\site-packages\requests\adapters.py", line 227, in cert_verify
    raise IOError("Could not find a suitable TLS CA certificate bundle, "
OSError: Could not find a suitable TLS CA certificate bundle, invalid path: True
```

**Comment by Swalscha** [comment]
Same problem today. Didn't find any solution so far...
