### ISSUE TITLE
Not able to launch Anaconda

### ISSUE THREAD

**Issue by jcp3** [ContinuumIO/anaconda-issues#12896]
### Actual Behavior

Attempted to launch Anaconda from desktop. Launch failed with "Navigator Error":
'charmap' codec can't decode byte 0x81 in position 72: character maps to

Main Error
'charmap' codec can't decode byte 0x81 in position 72: character maps to 
Traceback
Traceback (most recent call last):
  File "C:\Users\john_pflueger\AppData\Local\Continuum\anaconda3\lib\site-packages\anaconda_navigator\exceptions.py", line 74, in exception_handler
    return_value = func(*args, **kwargs)
  File "C:\Users\john_pflueger\AppData\Local\Continuum\anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 137, in start_app
    window = run_app(splash)
  File "C:\Users\john_pflueger\AppData\Local\Continuum\anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 60, in run_app
    window = MainWindow(splash=splash)
  File "C:\Users\john_pflueger\AppData\Local\Continuum\anaconda3\lib\site-packages\anaconda_navigator\widgets\main_window\__init__.py", line 224, in __init__
    for _ in anaconda_solvers.POOL.solve():
  File "C:\Users\john_pflueger\AppData\Local\Continuum\anaconda3\lib\site-packages\anaconda_navigator\utils\anaconda_solvers\core.py", line 72, in solve
    configuration: typing.Any = binstar_client.utils.get_config()
  File "C:\Users\john_pflueger\AppData\Local\Continuum\anaconda3\lib\site-packages\binstar_client\utils\config.py", line 250, in get_config
    file_configs = load_file_configs(SEARCH_PATH)
  File "C:\Users\john_pflueger\AppData\Local\Continuum\anaconda3\lib\site-packages\binstar_client\utils\config.py", line 242, in load_file_configs
    raw_data = collections.OrderedDict(kv for kv in itertools.chain.from_iterable(load_paths))
  File "C:\Users\john_pflueger\AppData\Local\Continuum\anaconda3\lib\site-packages\binstar_client\utils\config.py", line 242, in 
    raw_data = collections.OrderedDict(kv for kv in itertools.chain.from_iterable(load_paths))
  File "C:\Users\john_pflueger\AppData\Local\Continuum\anaconda3\lib\site-packages\binstar_client\utils\config.py", line 222, in _dir_yaml_loader
    yield filepath, load_config(filepath)
  File "C:\Users\john_pflueger\AppData\Local\Continuum\anaconda3\lib\site-packages\binstar_client\utils\config.py", line 206, in load_config
    data = yaml_load(fd)
  File "C:\Users\john_pflueger\AppData\Local\Continuum\anaconda3\lib\site-packages\binstar_client\utils\yaml.py", line 12, in yaml_load
    return safe_load(stream)
  File "C:\Users\john_pflueger\AppData\Local\Continuum\anaconda3\lib\site-packages\yaml\__init__.py", line 125, in safe_load
    return load(stream, SafeLoader)
  File "C:\Users\john_pflueger\AppData\Local\Continuum\anaconda3\lib\site-packages\yaml\__init__.py", line 79, in load
    loader = Loader(stream)
  File "C:\Users\john_pflueger\AppData\Local\Continuum\anaconda3\lib\site-packages\yaml\loader.py", line 34, in __init__
    Reader.__init__(self, stream)
  File "C:\Users\john_pflueger\AppData\Local\Continuum\anaconda3\lib\site-packages\yaml\reader.py", line 85, in __init__
    self.determine_encoding()
  File "C:\Users\john_pflueger\AppData\Local\Continuum\anaconda3\lib\site-packages\yaml\reader.py", line 124, in determine_encoding
    self.update_raw()
  File "C:\Users\john_pflueger\AppData\Local\Continuum\anaconda3\lib\site-packages\yaml\reader.py", line 178, in update_raw
    data = self.stream.read(size)
  File "C:\Users\john_pflueger\AppData\Local\Continuum\anaconda3\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 72: character maps to

### Expected Behavior

Should launch

### Steps to Reproduce

Happens every time I try to launch Anaconda

##### Anaconda or Miniconda version:

After initial failures, reinstalled Anaconda from:

Anaconda3-2021.11-Windows-x86_64.exe
Failures continued

##### Operating System:

Microsoft Windows 10 Enterprise
Version: 10.0.118363 Build 18363

##### `conda info`

<details>

```
PASTE OUTPUT HERE:

```

</details>

##### `conda list --show-channel-urls`

<details>

```
PASTE OUTPUT HERE:

```

</details>

**Comment by jcp3** [comment]
Sat, 9 April:
Did a full uninstall of Anaconda3 with subsequent reinstall.

Still get the same error. Suggestions?

**Comment by trusharmanohare** [comment]
Navigator Error
An unexpected error occurred on Navigator start-up

Report
Please report this issue in the anaconda [issue tracker](https://github.com/continuumio/anaconda-issues)

Main Error
unacceptable character #x0000: special characters are not allowed
  in "C:\Users\TUSHAR\.continuum\anaconda-client\config.yaml", position 0
Traceback
Traceback (most recent call last):
  File "C:\Users\TUSHAR\anaconda3\lib\site-packages\anaconda_navigator\exceptions.py", line 72, in exception_handler
    return_value = func(*args, **kwargs)
  File "C:\Users\TUSHAR\anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 151, in start_app
    window = run_app(splash)
  File "C:\Users\TUSHAR\anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 66, in run_app
    window = MainWindow(splash=splash)
  File "C:\Users\TUSHAR\anaconda3\lib\site-packages\anaconda_navigator\widgets\main_window\__init__.py", line 235, in __init__
    self.api = AnacondaAPI()
  File "C:\Users\TUSHAR\anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 1442, in AnacondaAPI
    ANACONDA_API = _AnacondaAPI()
  File "C:\Users\TUSHAR\anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 80, in __init__
    self._client_api = ClientAPI(config=self.config)
  File "C:\Users\TUSHAR\anaconda3\lib\site-packages\anaconda_navigator\api\client_api.py", line 650, in ClientAPI
    CLIENT_API = _ClientAPI(config=config)
  File "C:\Users\TUSHAR\anaconda3\lib\site-packages\anaconda_navigator\api\client_api.py", line 94, in __init__
    self.reload_client()
  File "C:\Users\TUSHAR\anaconda3\lib\site-packages\anaconda_navigator\api\client_api.py", line 321, in reload_client
    url = binstar_client.utils.get_config()['url']
  File "C:\Users\TUSHAR\anaconda3\lib\site-packages\binstar_client\utils\config.py", line 250, in get_config
    file_configs = load_file_configs(SEARCH_PATH)
  File "C:\Users\TUSHAR\anaconda3\lib\site-packages\binstar_client\utils\config.py", line 242, in load_file_configs
    raw_data = collections.OrderedDict(kv for kv in itertools.chain.from_iterable(load_paths))
  File "C:\Users\TUSHAR\anaconda3\lib\site-packages\binstar_client\utils\config.py", line 242, in 
    raw_data = collections.OrderedDict(kv for kv in itertools.chain.from_iterable(load_paths))
  File "C:\Users\TUSHAR\anaconda3\lib\site-packages\binstar_client\utils\config.py", line 222, in _dir_yaml_loader
    yield filepath, load_config(filepath)
  File "C:\Users\TUSHAR\anaconda3\lib\site-packages\binstar_client\utils\config.py", line 206, in load_config
    data = yaml_load(fd)
  File "C:\Users\TUSHAR\anaconda3\lib\site-packages\binstar_client\utils\yaml.py", line 12, in yaml_load
    return safe_load(stream)
  File "C:\Users\TUSHAR\anaconda3\lib\site-packages\yaml\__init__.py", line 125, in safe_load
    return load(stream, SafeLoader)
  File "C:\Users\TUSHAR\anaconda3\lib\site-packages\yaml\__init__.py", line 79, in load
    loader = Loader(stream)
  File "C:\Users\TUSHAR\anaconda3\lib\site-packages\yaml\loader.py", line 34, in __init__
    Reader.__init__(self, stream)
  File "C:\Users\TUSHAR\anaconda3\lib\site-packages\yaml\reader.py", line 85, in __init__
    self.determine_encoding()
  File "C:\Users\TUSHAR\anaconda3\lib\site-packages\yaml\reader.py", line 135, in determine_encoding
    self.update(1)
  File "C:\Users\TUSHAR\anaconda3\lib\site-packages\yaml\reader.py", line 169, in update
    self.check_printable(data)
  File "C:\Users\TUSHAR\anaconda3\lib\site-packages\yaml\reader.py", line 143, in check_printable
    raise ReaderError(self.name, position, ord(character),
yaml.reader.ReaderError: unacceptable character #x0000: special characters are not allowed
  in "C:\Users\TUSHAR\.continuum\anaconda-client\config.yaml", position 0

**Comment by trusharmanohare** [comment]
can you please solve the issue quickly.

**Comment by xelcho** [comment]
I too am running into similar issues. After updating navigator, no launch.

the errors I am seeing are around qt5core.dll etc.

**Comment by jcp3** [comment]
Thank you for the suggestion @xelcho . Unfortunately, it did not work in my case.

**Comment by desiremunyikwa** [comment]
Turning off internet connection, then start Anaconda did the trick for me. Turn on internet again afterwards.

**Comment by jcp3** [comment]
Bump... still looking for help.
