### ISSUE TITLE
Error Launching Anaconda Navigator

### ISSUE THREAD

**Issue by pythonconda** [ContinuumIO/anaconda-issues#12901]
When I first installed Anaconda Navigator I could launch it and use it. After restarting my computer though I receive this error every time I try to launch Navigator. I have uninstalled and re-installed the software, but receive this error even after re-installing.

Navigator Error
An unexpected error occurred on Navigator start-up

Report
Please report this issue in the anaconda [issue tracker](https://github.com/continuumio/anaconda-issues)

Main Error
('Service Unavailable: The server cannot process the request due to a high load ([GET] https://api.anaconda.org/user -> 503)', 503)
Traceback
Traceback (most recent call last):
  File "C:\Users\jmarron\Anaconda3\lib\site-packages\anaconda_navigator\exceptions.py", line 72, in exception_handler
    return_value = func(*args, **kwargs)
  File "C:\Users\jmarron\Anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 151, in start_app
    window = run_app(splash)
  File "C:\Users\jmarron\Anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 66, in run_app
    window = MainWindow(splash=splash)
  File "C:\Users\jmarron\Anaconda3\lib\site-packages\anaconda_navigator\widgets\main_window\__init__.py", line 235, in __init__
    self.api = AnacondaAPI()
  File "C:\Users\jmarron\Anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 1442, in AnacondaAPI
    ANACONDA_API = _AnacondaAPI()
  File "C:\Users\jmarron\Anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 80, in __init__
    self._client_api = ClientAPI(config=self.config)
  File "C:\Users\jmarron\Anaconda3\lib\site-packages\anaconda_navigator\api\client_api.py", line 650, in ClientAPI
    CLIENT_API = _ClientAPI(config=config)
  File "C:\Users\jmarron\Anaconda3\lib\site-packages\anaconda_navigator\api\client_api.py", line 94, in __init__
    self.reload_client()
  File "C:\Users\jmarron\Anaconda3\lib\site-packages\anaconda_navigator\api\client_api.py", line 325, in reload_client
    client.user()
  File "C:\Users\jmarron\Anaconda3\lib\site-packages\binstar_client\__init__.py", line 242, in user
    self._check_response(res)
  File "C:\Users\jmarron\Anaconda3\lib\site-packages\binstar_client\__init__.py", line 227, in _check_response
    raise ErrCls(msg, res.status_code)
binstar_client.errors.ServerError: ('Service Unavailable: The server cannot process the request due to a high load ([GET] https://api.anaconda.org/user -> 503)', 503)

### Actual Behavior
I receive the above error every time I launch Anaconda Navigator

### Expected Behavior
Anaconda Navigator to launch

### Steps to Reproduce
Happens every time I launch Navigator

##### Operating System:
Windows 10

##### `conda info`

<details>

```
PASTE OUTPUT HERE:

```

</details>

##### `conda list --show-channel-urls`

<details>

```
PASTE OUTPUT HERE:

```

</details>

**Comment by vshevchenko-anaconda** [comment]
Please use https://github.com/ContinuumIO/anaconda-issues/issues/12973 to add any additional details.
