### ISSUE TITLE
Starting Anaconda 

### ISSUE THREAD

**Issue by moahmmed44702** [ContinuumIO/anaconda-issues#12914]
<html>
    <head>
      <title>Navigator Error</title>
    </head>
    <body>
      <div>
        <h1>Navigator Error</h1>
        <p>An unexpected error occurred on Navigator start-up</p>
        <h2>Report</h2>
        <p>Please report this issue in the anaconda
          <a href="https://github.com/continuumio/anaconda-issues">
            issue tracker
          </a>
        </p>
      </div>
      <div>
        <h2>Main Error</h2>
        <p><pre>unacceptable character #x0000: special characters are not allowed
  in "C:\Users\ASUS\.continuum\anaconda-client\config.yaml", position 0</pre></p>
        <h2>Traceback</h2>
        <p><pre>Traceback (most recent call last):
  File "C:\Users\ASUS\anaconda3\lib\site-packages\anaconda_navigator\exceptions.py", line 72, in exception_handler
    return_value = func(*args, **kwargs)
  File "C:\Users\ASUS\anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 151, in start_app
    window = run_app(splash)
  File "C:\Users\ASUS\anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 66, in run_app
    window = MainWindow(splash=splash)
  File "C:\Users\ASUS\anaconda3\lib\site-packages\anaconda_navigator\widgets\main_window\__init__.py", line 235, in __init__
    self.api = AnacondaAPI()
  File "C:\Users\ASUS\anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 1442, in AnacondaAPI
    ANACONDA_API = _AnacondaAPI()
  File "C:\Users\ASUS\anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 80, in __init__
    self._client_api = ClientAPI(config=self.config)
  File "C:\Users\ASUS\anaconda3\lib\site-packages\anaconda_navigator\api\client_api.py", line 650, in ClientAPI
    CLIENT_API = _ClientAPI(config=config)
  File "C:\Users\ASUS\anaconda3\lib\site-packages\anaconda_navigator\api\client_api.py", line 94, in __init__
    self.reload_client()
  File "C:\Users\ASUS\anaconda3\lib\site-packages\anaconda_navigator\api\client_api.py", line 321, in reload_client
    url = binstar_client.utils.get_config()['url']
  File "C:\Users\ASUS\anaconda3\lib\site-packages\binstar_client\utils\config.py", line 250, in get_config
    file_configs = load_file_configs(SEARCH_PATH)
  File "C:\Users\ASUS\anaconda3\lib\site-packages\binstar_client\utils\config.py", line 242, in load_file_configs
    raw_data = collections.OrderedDict(kv for kv in itertools.chain.from_iterable(load_paths))
  File "C:\Users\ASUS\anaconda3\lib\site-packages\binstar_client\utils\config.py", line 242, in <genexpr>
    raw_data = collections.OrderedDict(kv for kv in itertools.chain.from_iterable(load_paths))
  File "C:\Users\ASUS\anaconda3\lib\site-packages\binstar_client\utils\config.py", line 222, in _dir_yaml_loader
    yield filepath, load_config(filepath)
  File "C:\Users\ASUS\anaconda3\lib\site-packages\binstar_client\utils\config.py", line 206, in load_config
    data = yaml_load(fd)
  File "C:\Users\ASUS\anaconda3\lib\site-packages\binstar_client\utils\yaml.py", line 12, in yaml_load
    return safe_load(stream)
  File "C:\Users\ASUS\anaconda3\lib\site-packages\yaml\__init__.py", line 125, in safe_load
    return load(stream, SafeLoader)
  File "C:\Users\ASUS\anaconda3\lib\site-packages\yaml\__init__.py", line 79, in load
    loader = Loader(stream)
  File "C:\Users\ASUS\anaconda3\lib\site-packages\yaml\loader.py", line 34, in __init__
    Reader.__init__(self, stream)
  File "C:\Users\ASUS\anaconda3\lib\site-packages\yaml\reader.py", line 85, in __init__
    self.determine_encoding()
  File "C:\Users\ASUS\anaconda3\lib\site-packages\yaml\reader.py", line 135, in determine_encoding
    self.update(1)
  File "C:\Users\ASUS\anaconda3\lib\site-packages\yaml\reader.py", line 169, in update
    self.check_printable(data)
  File "C:\Users\ASUS\anaconda3\lib\site-packages\yaml\reader.py", line 143, in check_printable
    raise ReaderError(self.name, position, ord(character),
yaml.reader.ReaderError: unacceptable character #x0000: special characters are not allowed
  in "C:\Users\ASUS\.continuum\anaconda-client\config.yaml", position 0
</pre></p>
      </div>
    </body>
    </html>

**Comment by csoja** [comment]
Looks like there is an issue in your anaconda-client config.yaml file.  If you rename C:\Users\ASUS\.continuum\anaconda-client\config.yaml to C:\Users\ASUS\.continuum\anaconda-client\config.old that should enable you to start Navigator.  If you need your current configuration - then you may want to look at the file itself and fix it so that it no longer contains the unallowed special character.
