### ISSUE TITLE
Problem starting Anaconda Navigator

### ISSUE THREAD

**Issue by sheridanfew** [ContinuumIO/anaconda-issues#12910]
Hi there, 

I seem to be having trouble with permissions running anaconda navigator on MacOS Monterey 12.3.1 (I have admin rights). Any advice would be greatly appreciated. See below:

**Navigator Error**
An unexpected error occurred on Navigator start-up

**Report**
Please report this issue in the anaconda [issue tracker](https://github.com/continuumio/anaconda-issues)

**Main Error**
/Users/Shez/.continuum/anaconda-client: Permission denied

**Traceback**
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.9/site-packages/binstar_client/utils/config.py", line 274, in save_config
    os.makedirs(data_dir)
  File "/opt/anaconda3/lib/python3.9/os.py", line 225, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/Users/Shez/.continuum/anaconda-client'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.9/site-packages/anaconda_navigator/exceptions.py", line 72, in exception_handler
    return_value = func(*args, **kwargs)
  File "/opt/anaconda3/lib/python3.9/site-packages/anaconda_navigator/app/start.py", line 151, in start_app
    window = run_app(splash)
  File "/opt/anaconda3/lib/python3.9/site-packages/anaconda_navigator/app/start.py", line 66, in run_app
    window = MainWindow(splash=splash)
  File "/opt/anaconda3/lib/python3.9/site-packages/anaconda_navigator/widgets/main_window/__init__.py", line 235, in __init__
    self.api = AnacondaAPI()
  File "/opt/anaconda3/lib/python3.9/site-packages/anaconda_navigator/api/anaconda_api.py", line 1442, in AnacondaAPI
    ANACONDA_API = _AnacondaAPI()
  File "/opt/anaconda3/lib/python3.9/site-packages/anaconda_navigator/api/anaconda_api.py", line 80, in __init__
    self._client_api = ClientAPI(config=self.config)
  File "/opt/anaconda3/lib/python3.9/site-packages/anaconda_navigator/api/client_api.py", line 650, in ClientAPI
    CLIENT_API = _ClientAPI(config=config)
  File "/opt/anaconda3/lib/python3.9/site-packages/anaconda_navigator/api/client_api.py", line 94, in __init__
    self.reload_client()
  File "/opt/anaconda3/lib/python3.9/site-packages/anaconda_navigator/api/client_api.py", line 324, in reload_client
    client = self._load_binstar_client(url)
  File "/opt/anaconda3/lib/python3.9/site-packages/anaconda_navigator/api/client_api.py", line 355, in _load_binstar_client
    binstar_client.utils.set_config(config)
  File "/opt/anaconda3/lib/python3.9/site-packages/binstar_client/utils/config.py", line 284, in set_config
    save_config(data, USER_CONFIG if user else SYSTEM_CONFIG)
  File "/opt/anaconda3/lib/python3.9/site-packages/binstar_client/utils/config.py", line 279, in save_config
    raise BinstarError('%s: %s' % (exc.filename, exc.strerror,))
binstar_client.errors.BinstarError: /Users/Shez/.continuum/anaconda-client: Permission denied

**Comment by sheridanfew** [comment]
Thanks! It's working now. I deleted the old version and a version that had archived during an OS upgrade, then reinstalled.
