### ISSUE TITLE
ANACONDA CANNOT LAUNCH NAVIGATOR AND SPYDER DOES NOT OPEN

### ISSUE THREAD

**Issue by Lelost** [ContinuumIO/anaconda-issues#12916]
Thanks for opening an issue! Please fill out the following template in full.

A few things to keep in mind:

- This issue tracker is for issues with installing Anaconda or Miniconda or with packages built by Anaconda, Inc. like Anaconda Navigator. It is also a place to request packages or other enhancements of the Anaconda Distribution.

- Anaconda Community Code of Conduct: https://www.anaconda.com/community-code-of-conduct/

- For conda issues, you should open an issue at https://github.com/conda/conda/issues

- For conda-build issues, you should open an issue at https://github.com/conda/conda-build

- For an issue with a particular conda-forge package, you should open an issue on the corresponding feedstock: https://github.com/conda-forge

##### `conda info`

<details>

```
Traceback
Traceback (most recent call last):
  File "C:\Users\Mokone\anaconda3\lib\site-packages\anaconda_navigator\exceptions.py", line 72, in exception_handler
    return_value = func(*args, **kwargs)
  File "C:\Users\Mokone\anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 151, in start_app
    window = run_app(splash)
  File "C:\Users\Mokone\anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 66, in run_app
    window = MainWindow(splash=splash)
  File "C:\Users\Mokone\anaconda3\lib\site-packages\anaconda_navigator\widgets\main_window\__init__.py", line 235, in __init__
    self.api = AnacondaAPI()
  File "C:\Users\Mokone\anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 1442, in AnacondaAPI
    ANACONDA_API = _AnacondaAPI()
  File "C:\Users\Mokone\anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 79, in __init__
    self._conda_api = CondaAPI()
  File "C:\Users\Mokone\anaconda3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 1813, in CondaAPI
    CONDA_API = _CondaAPI()
  File "C:\Users\Mokone\anaconda3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 495, in __init__
    self.set_conda_prefix(info=get_conda_info())
  File "C:\Users\Mokone\anaconda3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 655, in set_conda_prefix
    self.ROOT_PREFIX = info.get('root_prefix')  # str
AttributeError: 'list' object has no attribute 'get'

```

</details>

##### `conda list --show-channel-urls`

<details>

```
Navigator Error
An unexpected error occurred on Navigator start-up

Report
Please report this issue in the anaconda [issue tracker](https://github.com/continuumio/anaconda-issues)

Main Error
'list' object has no attribute 'get'
Traceback
Traceback (most recent call last):
  File "C:\Users\Mokone\anaconda3\lib\site-packages\anaconda_navigator\exceptions.py", line 74, in exception_handler
    return_value = func(*args, **kwargs)
  File "C:\Users\Mokone\anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 137, in start_app
    window = run_app(splash)
  File "C:\Users\Mokone\anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 60, in run_app
    window = MainWindow(splash=splash)
  File "C:\Users\Mokone\anaconda3\lib\site-packages\anaconda_navigator\widgets\main_window\__init__.py", line 228, in __init__
    self.api = AnacondaAPI()
  File "C:\Users\Mokone\anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 1116, in AnacondaAPI
    ANACONDA_API = _AnacondaAPI()
  File "C:\Users\Mokone\anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 69, in __init__
    self._conda_api = CondaAPI()
  File "C:\Users\Mokone\anaconda3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 1824, in CondaAPI
    CONDA_API = _CondaAPI()
  File "C:\Users\Mokone\anaconda3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 485, in __init__
    self.set_conda_prefix(info=get_conda_info(allow_fixes=True))
  File "C:\Users\Mokone\anaconda3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 638, in set_conda_prefix
    self.ROOT_PREFIX = info.get('root_prefix')  # str
AttributeError: 'list' object has no attribute 'get'

```

</details>

**Comment by naeemahaz** [comment]
Same here

**Comment by cooltnt** [comment]
win10,   Anaconda3-2022.05-Windows-x86_64.exe

same error
