### ISSUE TITLE
I have same problems :(

### ISSUE THREAD

**Issue by Chokhonelidze** [ContinuumIO/anaconda-issues#12953]
Traceback (most recent call last):
File "/home/george/anaconda3/lib/python3.9/site-packages/traitlets/traitlets.py", line 537, in get
value = obj._trait_values[self.name]
KeyError: 'runtime_dir'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/home/george/anaconda3/bin/jupyter-notebook", line 11, in 
sys.exit(main())
File "/home/george/anaconda3/lib/python3.9/site-packages/jupyter_core/application.py", line 264, in launch_instance
return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
File "/home/george/anaconda3/lib/python3.9/site-packages/traitlets/config/application.py", line 845, in launch_instance
app.initialize(argv)
File "/home/george/anaconda3/lib/python3.9/site-packages/traitlets/config/application.py", line 88, in inner
return method(app, *args, **kwargs)
File "/home/george/anaconda3/lib/python3.9/site-packages/notebook/notebookapp.py", line 2148, in initialize
self.init_configurables()
File "/home/george/anaconda3/lib/python3.9/site-packages/notebook/notebookapp.py", line 1650, in init_configurables
connection_dir=self.runtime_dir,
File "/home/george/anaconda3/lib/python3.9/site-packages/traitlets/traitlets.py", line 577, in __get__
return self.get(obj, cls)
File "/home/george/anaconda3/lib/python3.9/site-packages/traitlets/traitlets.py", line 540, in get
default = obj.trait_defaults(self.name)
File "/home/george/anaconda3/lib/python3.9/site-packages/traitlets/traitlets.py", line 1580, in trait_defaults
return self._get_trait_default_generator(names[0])(self)
File "/home/george/anaconda3/lib/python3.9/site-packages/jupyter_core/application.py", line 95, in _runtime_dir_default
ensure_dir_exists(rd, mode=0o700)
File "/home/george/anaconda3/lib/python3.9/site-packages/jupyter_core/utils/__init__.py", line 11, in ensure_dir_exists
os.makedirs(path, mode=mode)
File "/home/george/anaconda3/lib/python3.9/os.py", line 225, in makedirs
mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/home/george/.local/share/jupyter/runtime'

I deleted .anaconda but nothing helped :(

**Comment by csoja** [comment]
The error is: Permission denied: '/home/george/.local/share/jupyter/runtime' 
So, Anaconda does not have permission to access that file.  If you can update the permissions so that the application - you may be able to run it successfully.
