### ISSUE TITLE
Issue opening anaconda

### ISSUE THREAD

**Issue by Mashedp0tat0es** [ContinuumIO/anaconda-issues#12958]
Hi all,

This all started when I tried to install panda profilling, through terminal and jupyter. After multiple attempts at installation, I was still unable to import pandas-profiling and restarted my laptop in hopes that it would be resolved. However, now I can't even open jyputer with the error message as follow:

Traceback (most recent call last):
File "C:\Users\chinh\anaconda3\Scripts\jupyter-notebook-script.py", line 6, in 
from notebook.notebookapp import main
File "C:\Users\chinh\anaconda3\lib\site-packages\notebook\notebookapp.py", line 44, in 
from jinja2 import Environment, FileSystemLoader
File "C:\Users\chinh\anaconda3\lib\site-packages\jinja2\__init__.py", line 12, in 
from .environment import Environment
File "C:\Users\chinh\anaconda3\lib\site-packages\jinja2\environment.py", line 25, in 
from .defaults import BLOCK_END_STRING
File "C:\Users\chinh\anaconda3\lib\site-packages\jinja2\defaults.py", line 3, in 
from .filters import FILTERS as DEFAULT_FILTERS # noqa: F401
File "C:\Users\chinh\anaconda3\lib\site-packages\jinja2\filters.py", line 13, in 
from markupsafe import soft_unicode
ImportError: cannot import name 'soft_unicode' from 'markupsafe' (C:\Users\chinh\anaconda3\lib\site-packages\markupsafe\__init__.py)

Would appreciate it if someone could help me!!

**Comment by mrezaarabi** [comment]
Hi,

I encountered the same problem, and the following solution worked fine for me: (If you use Anaconda Navigator to open and run Jupyter Notebooks, I hope this will help)

1) Uninstall the pandas-profiling package using "pip uninstall pandas-profiling"
2) Conda users can open up the Anaconda Power Shell Prompt and use the below command to install the pandas profiling package in python: "conda install -c anaconda pandas-profiling"
