### ISSUE TITLE
Anaconda navigator issue when start up

### ISSUE THREAD

**Issue by PelinaP** [ContinuumIO/anaconda-issues#12976]
### Checklist

- [X] I added a descriptive title
- [X] I searched for other issues and couldn't find a solution or duplication
- [X] I already searched in Google and didn't find any good information or help
- [X] I looked at the [docs](https://docs.anaconda.com/anaconda/navigator/) and didn't see anything to help

### What happened?

it does not open or direct me

### Conda info

```shell
Traceback (most recent call last):
File "C:\Users\energy\anaconda3\lib\site-packages\anaconda_navigator\exceptions.py", line 72, in exception_handler
return_value = func(*args, **kwargs)
File "C:\Users\energy\anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 151, in start_app
window = run_app(splash)
File "C:\Users\energy\anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 66, in run_app
window = MainWindow(splash=splash)
File "C:\Users\energy\anaconda3\lib\site-packages\anaconda_navigator\widgets\main_window\__init__.py", line 235, in __init__
self.api = AnacondaAPI()
File "C:\Users\energy\anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 1442, in AnacondaAPI
ANACONDA_API = _AnacondaAPI()
File "C:\Users\energy\anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 80, in __init__
self._client_api = ClientAPI(config=self.config)
File "C:\Users\energy\anaconda3\lib\site-packages\anaconda_navigator\api\client_api.py", line 650, in ClientAPI
CLIENT_API = _ClientAPI(config=config)
File "C:\Users\energy\anaconda3\lib\site-packages\anaconda_navigator\api\client_api.py", line 94, in __init__
self.reload_client()
File "C:\Users\energy\anaconda3\lib\site-packages\anaconda_navigator\api\client_api.py", line 325, in reload_client
client.user()
File "C:\Users\energy\anaconda3\lib\site-packages\binstar_client\__init__.py", line 242, in user
self._check_response(res)
File "C:\Users\energy\anaconda3\lib\site-packages\binstar_client\__init__.py", line 227, in _check_response
raise ErrCls(msg, res.status_code)
binstar_client.errors.ServerError: ('?: Undefined error ([GET] https://api.anaconda.org/user -> 530)', 530)
```

### Conda config

```shell
Traceback (most recent call last):
File "C:\Users\energy\anaconda3\lib\site-packages\anaconda_navigator\exceptions.py", line 72, in exception_handler
return_value = func(*args, **kwargs)
File "C:\Users\energy\anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 151, in start_app
window = run_app(splash)
File "C:\Users\energy\anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 66, in run_app
window = MainWindow(splash=splash)
File "C:\Users\energy\anaconda3\lib\site-packages\anaconda_navigator\widgets\main_window\__init__.py", line 235, in __init__
self.api = AnacondaAPI()
File "C:\Users\energy\anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 1442, in AnacondaAPI
ANACONDA_API = _AnacondaAPI()
File "C:\Users\energy\anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 80, in __init__
self._client_api = ClientAPI(config=self.config)
File "C:\Users\energy\anaconda3\lib\site-packages\anaconda_navigator\api\client_api.py", line 650, in ClientAPI
CLIENT_API = _ClientAPI(config=config)
File "C:\Users\energy\anaconda3\lib\site-packages\anaconda_navigator\api\client_api.py", line 94, in __init__
self.reload_client()
File "C:\Users\energy\anaconda3\lib\site-packages\anaconda_navigator\api\client_api.py", line 325, in reload_client
client.user()
File "C:\Users\energy\anaconda3\lib\site-packages\binstar_client\__init__.py", line 242, in user
self._check_response(res)
File "C:\Users\energy\anaconda3\lib\site-packages\binstar_client\__init__.py", line 227, in _check_response
raise ErrCls(msg, res.status_code)
binstar_client.errors.ServerError: ('?: Undefined error ([GET] https://api.anaconda.org/user -> 530)', 530)
```

### Conda list

```shell
Traceback (most recent call last):
File "C:\Users\energy\anaconda3\lib\site-packages\anaconda_navigator\exceptions.py", line 72, in exception_handler
return_value = func(*args, **kwargs)
File "C:\Users\energy\anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 151, in start_app
window = run_app(splash)
File "C:\Users\energy\anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 66, in run_app
window = MainWindow(splash=splash)
File "C:\Users\energy\anaconda3\lib\site-packages\anaconda_navigator\widgets\main_window\__init__.py", line 235, in __init__
self.api = AnacondaAPI()
File "C:\Users\energy\anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 1442, in AnacondaAPI
ANACONDA_API = _AnacondaAPI()
File "C:\Users\energy\anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 80, in __init__
self._client_api = ClientAPI(config=self.config)
File "C:\Users\energy\anaconda3\lib\site-packages\anaconda_navigator\api\client_api.py", line 650, in ClientAPI
CLIENT_API = _ClientAPI(config=config)
File "C:\Users\energy\anaconda3\lib\site-packages\anaconda_navigator\api\client_api.py", line 94, in __init__
self.reload_client()
File "C:\Users\energy\anaconda3\lib\site-packages\anaconda_navigator\api\client_api.py", line 325, in reload_client
client.user()
File "C:\Users\energy\anaconda3\lib\site-packages\binstar_client\__init__.py", line 242, in user
self._check_response(res)
File "C:\Users\energy\anaconda3\lib\site-packages\binstar_client\__init__.py", line 227, in _check_response
raise ErrCls(msg, res.status_code)
binstar_client.errors.ServerError: ('?: Undefined error ([GET] https://api.anaconda.org/user -> 530)', 530)
```

**Comment by vshevchenko-anaconda** [comment]
Please use https://github.com/ContinuumIO/anaconda-issues/issues/12973 to add any additional details.
