### ISSUE TITLE
Recent qtconsole broken on Windows 10

### ISSUE THREAD

**Issue by zoof** [ContinuumIO/anaconda-issues#12985]
### Checklist

- [X] I added a descriptive title
- [X] I searched for other issues and couldn't find a solution or duplication
- [X] I already searched in Google and didn't find any good information or help
- [X] I looked at the [docs](https://docs.anaconda.com/) and didn't see anything to help

### What happened?

When I try to start qtconsole from the command line from PowerShell, I get:
```
$ jupyter-qtconsole.exe
Traceback (most recent call last):
  File "C:\Users\user\Miniconda3\Scripts\jupyter-qtconsole-script.py", line 5, in <module>
    from qtconsole.qtconsoleapp import main
  File "C:\Users\user\Miniconda3\lib\site-packages\qtconsole\qtconsoleapp.py", line 61, in <module>
    from qtpy import QtCore, QtGui, QtWidgets, QT_VERSION
  File "C:\Users\user\Miniconda3\lib\site-packages\qtpy\QtCore.py", line 57, in <module>
    from PyQt5.QtCore import *
ImportError: DLL load failed while importing QtCore: The specified procedure could not be found.
```
My initial thought had been that something broke with a recent upgrade so I uninstalled Miniconda and reinstalled it (Miniconda3-py39_4.12.0-Windows-x86_64.exe) with the same results.

### Conda info

```shell
$ conda info

     active environment : base
    active env location : C:\Users\user\Miniconda3
            shell level : 1
       user config file : C:\Users\user\.condarc
 populated config files :
          conda version : 4.13.0
    conda-build version : not installed
         python version : 3.9.12.final.0
       virtual packages : __win=0=0
                          __archspec=1=x86_64
       base environment : C:\Users\user\Miniconda3  (writable)
      conda av data dir : C:\Users\user\Miniconda3\etc\conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\Users\user\Miniconda3\pkgs
                          C:\Users\user\.conda\pkgs
                          C:\Users\user\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\user\Miniconda3\envs
                          C:\Users\user\.conda\envs
                          C:\Users\user\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.13.0 requests/2.27.1 CPython/3.9.12 Windows/10 Windows/10.0.19044
          administrator : False
             netrc file : None
           offline mode : False
```

### Conda config

```shell
No output.
```

### Conda list

```shell
$ conda list --show-channel-urls
# packages in environment at C:\Users\user\Miniconda3:
#
# Name                    Version                   Build  Channel
argon2-cffi               21.3.0             pyhd3eb1b0_0    defaults
argon2-cffi-bindings      21.2.0           py39h2bbff1b_0    defaults
asttokens                 2.0.5              pyhd3eb1b0_0    defaults
attrs                     21.4.0             pyhd3eb1b0_0    defaults
backcall                  0.2.0              pyhd3eb1b0_0    defaults
beautifulsoup4            4.11.1           py39haa95532_0    defaults
blas                      1.0                         mkl    defaults
bleach                    4.1.0              pyhd3eb1b0_0    defaults
bottleneck                1.3.4            py39h080aedc_0    defaults
brotli                    1.0.9                ha925a31_2    defaults
brotlipy                  0.7.0           py39h2bbff1b_1003    defaults
ca-certificates           2022.4.26            haa95532_0    defaults
certifi                   2022.6.15        py39haa95532_0    defaults
cffi                      1.15.0           py39h2bbff1b_1    defaults
charset-normalizer        2.0.4              pyhd3eb1b0_0    defaults
colorama                  0.4.4              pyhd3eb1b0_0    defaults
conda                     4.13.0           py39haa95532_0    defaults
conda-content-trust       0.1.1              pyhd3eb1b0_0    defaults
conda-package-handling    1.8.1            py39h8cc25b3_0    defaults
console_shortcut          0.1.1                         4    defaults
cryptography              36.0.0           py39h21b164f_0    defaults
cycler                    0.11.0             pyhd3eb1b0_0    defaults
debugpy                   1.5.1            py39hd77b12b_0    defaults
decorator                 5.1.1              pyhd3eb1b0_0    defaults
defusedxml                0.7.1              pyhd3eb1b0_0    defaults
entrypoints               0.4              py39haa95532_0    defaults
et_xmlfile                1.1.0            py39haa95532_0    defaults
executing                 0.8.3              pyhd3eb1b0_0    defaults
fonttools                 4.25.0             pyhd3eb1b0_0    defaults
freetype                  2.10.4               hd328e21_0    defaults
icc_rt                    2019.0.0             h0cc432a_1    defaults
icu                       58.2                 ha925a31_3    defaults
idna                      3.3                pyhd3eb1b0_0    defaults
intel-openmp              2021.4.0          haa95532_3556    defaults
ipykernel                 6.9.1            py39haa95532_0    defaults
ipython                   8.3.0            py39haa95532_0    defaults
ipython_genutils          0.2.0              pyhd3eb1b0_1    defaults
ipywidgets                7.6.5              pyhd3eb1b0_1    defaults
jedi                      0.18.1           py39haa95532_1    defaults
jinja2                    3.0.3              pyhd3eb1b0_0    defaults
jpeg                      9e                   h2bbff1b_0    defaults
jsonschema                4.4.0            py39haa95532_0    defaults
jupyter                   1.0.0            py39haa95532_7    defaults
jupyter_client            7.2.2            py39haa95532_0    defaults
jupyter_console           6.4.3              pyhd3eb1b0_0    defaults
jupyter_core              4.10.0           py39haa95532_0    defaults
jupyterlab_pygments       0.1.2                      py_0    defaults
jupyterlab_widgets        1.0.0              pyhd3eb1b0_1    defaults
kiwisolver                1.4.2            py39hd77b12b_0    defaults
libpng                    1.6.37               h2a8f88b_0    defaults
libtiff                   4.2.0                he0120a3_1    defaults
libwebp                   1.2.2                h2bbff1b_0    defaults
lz4-c                     1.9.3                h2bbff1b_1    defaults
markupsafe                2.1.1            py39h2bbff1b_0    defaults
matplotlib                3.5.1            py39haa95532_1    defaults
matplotlib-base           3.5.1            py39hd77b12b_1    defaults
matplotlib-inline         0.1.2              pyhd3eb1b0_2    defaults
menuinst                  1.4.18           py39h59b6b97_0    defaults
mistune                   0.8.4           py39h2bbff1b_1000    defaults
mkl                       2021.4.0           haa95532_640    defaults
mkl-service               2.4.0            py39h2bbff1b_0    defaults
mkl_fft                   1.3.1            py39h277e83a_0    defaults
mkl_random                1.2.2            py39hf11a4ad_0    defaults
mpmath                    1.2.1            py39haa95532_0    defaults
munkres                   1.1.4                      py_0    defaults
nbclient                  0.5.13           py39haa95532_0    defaults
nbconvert                 6.4.4            py39haa95532_0    defaults
nbformat                  5.3.0            py39haa95532_0    defaults
nest-asyncio              1.5.5            py39haa95532_0    defaults
notebook                  6.4.11           py39haa95532_0    defaults
numexpr                   2.8.1            py39hb80d3ca_2    defaults
numpy                     1.22.3           py39h7a0a035_0    defaults
numpy-base                1.22.3           py39hca35cd5_0    defaults
openpyxl                  3.0.9              pyhd3eb1b0_0    defaults
openssl                   1.1.1o               h2bbff1b_0    defaults
packaging                 21.3               pyhd3eb1b0_0    defaults
pandas                    1.4.2            py39hd77b12b_0    defaults
pandocfilters             1.5.0              pyhd3eb1b0_0    defaults
parso                     0.8.3              pyhd3eb1b0_0    defaults
patsy                     0.5.2            py39haa95532_1    defaults
pickleshare               0.7.5           pyhd3eb1b0_1003    defaults
pillow                    9.0.1            py39hdc2b20a_0    defaults
pip                       21.2.4           py39haa95532_0    defaults
powershell_shortcut       0.0.1                         3    defaults
prometheus_client         0.13.1             pyhd3eb1b0_0    defaults
prompt-toolkit            3.0.20             pyhd3eb1b0_0    defaults
prompt_toolkit            3.0.20               hd3eb1b0_0    defaults
pure_eval                 0.2.2              pyhd3eb1b0_0    defaults
pycosat                   0.6.3            py39h2bbff1b_0    defaults
pycparser                 2.21               pyhd3eb1b0_0    defaults
pygments                  2.11.2             pyhd3eb1b0_0    defaults
pyopenssl                 22.0.0             pyhd3eb1b0_0    defaults
pyparsing                 3.0.4              pyhd3eb1b0_0    defaults
pyqt                      5.9.2            py39hd77b12b_6    defaults
pyrsistent                0.18.0           py39h196d8e1_0    defaults
pysocks                   1.7.1            py39haa95532_0    defaults
python                    3.9.12               h6244533_0    defaults
python-dateutil           2.8.2              pyhd3eb1b0_0    defaults
python-fastjsonschema     2.15.1             pyhd3eb1b0_0    defaults
pytz                      2022.1           py39haa95532_0    defaults
pywin32                   302              py39h2bbff1b_2    defaults
pywinpty                  2.0.2            py39h5da7b33_0    defaults
pyzmq                     22.3.0           py39hd77b12b_2    defaults
qt                        5.9.7            vc14h73c81de_0    defaults
qtconsole                 5.3.0              pyhd3eb1b0_0    defaults
qtpy                      2.0.1              pyhd3eb1b0_0    defaults
requests                  2.27.1             pyhd3eb1b0_0    defaults
ruamel_yaml               0.15.100         py39h2bbff1b_0    defaults
scipy                     1.7.3            py39h0a974cb_0    defaults
send2trash                1.8.0              pyhd3eb1b0_1    defaults
setuptools                61.2.0           py39haa95532_0    defaults
sip                       4.19.13          py39hd77b12b_0    defaults
six                       1.16.0             pyhd3eb1b0_1    defaults
soupsieve                 2.3.1              pyhd3eb1b0_0    defaults
sqlite                    3.38.2               h2bbff1b_0    defaults
stack_data                0.2.0              pyhd3eb1b0_0    defaults
statsmodels               0.13.2           py39h2bbff1b_0    defaults
sympy                     1.10.1           py39haa95532_0    defaults
terminado                 0.13.1           py39haa95532_0    defaults
testpath                  0.6.0            py39haa95532_0    defaults
tk                        8.6.12               h2bbff1b_0    defaults
tornado                   6.1              py39h2bbff1b_0    defaults
tqdm                      4.63.0             pyhd3eb1b0_0    defaults
traitlets                 5.1.1              pyhd3eb1b0_0    defaults
typing-extensions         4.1.1                hd3eb1b0_0    defaults
typing_extensions         4.1.1              pyh06a4308_0    defaults
tzdata                    2022a                hda174b7_0    defaults
urllib3                   1.26.8             pyhd3eb1b0_0    defaults
vc                        14.2                 h21ff451_1    defaults
vs2015_runtime            14.27.29016          h5e58377_2    defaults
wcwidth                   0.2.5              pyhd3eb1b0_0    defaults
webencodings              0.5.1            py39haa95532_1    defaults
wheel                     0.37.1             pyhd3eb1b0_0    defaults
widgetsnbextension        3.5.2            py39haa95532_0    defaults
win_inet_pton             1.1.0            py39haa95532_0    defaults
wincertstore              0.2              py39haa95532_2    defaults
winpty                    0.4.3                         4    defaults
xz                        5.2.5                h8cc25b3_1    defaults
yaml                      0.2.5                he774522_0    defaults
zlib                      1.2.12               h8cc25b3_2    defaults
zstd                      1.5.2                h19a0ad4_0    defaults
```

**Comment by skupr-anaconda** [comment]
@zoof Could you try install the latest qtconsole version **5.3.1**? 
Let us know if the issue persists.

**Comment by zoof** [comment]
Yes, that seems to have fixed the problem.
