### ISSUE TITLE
I can't open anaconda navigator

### ISSUE THREAD

**Issue by zhhhhhf** [ContinuumIO/anaconda-issues#12993]
### Checklist

- [X] I added a descriptive title
- [X] I searched for other issues and couldn't find a solution or duplication
- [X] I already searched in Google and didn't find any good information or help
- [X] I looked at the [docs](https://docs.anaconda.com/) and didn't see anything to help

### What happened?

I can't open anaconda navigator

### Conda info

```shell
Current conda install:

               platform : win-64
          conda version : 4.3.21
       conda is private : False
      conda-env version : 4.3.21
    conda-build version : not installed
         python version : 3.6.1.final.0
       requests version : 2.14.2
       root environment : C:\Users\999\Anaconda3  (writable)
    default environment : C:\Users\999\Anaconda3\envs\pytorch
       envs directories : C:\Users\999\Anaconda3\envs
                          C:\Users\999\AppData\Local\conda\conda\envs
                          C:\Users\999\.conda\envs
          package cache : C:\Users\999\Anaconda3\pkgs
                          C:\Users\999\AppData\Local\conda\conda\pkgs
           channel URLs : http://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/win-64
                          http://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/noarch
                          http://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/win-64
                          http://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/noarch
                          http://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/r/win-64
                          http://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/r/noarch
            config file : C:\Users\999\.condarc
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.21 requests/2.14.2 CPython/3.6.1 Windows/10 Windows/10.0.22000
          administrator : False
```

### Conda config

```shell
==> C:\Users\999\.condarc <==
ssl_verify: True
channels:
  - defaults
default_channels:
  - http://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
  - http://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
  - http://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/r
custom_channels:
  conda-forge: http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud
  msys2: http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud
  bioconda: http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud
  menpo: http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud
  pytorch: http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud
  simpleitk: http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud
show_channel_urls: True
```

### Conda list

```shell
#
_tflow_select             2.3.0                       mkl    defaults
absl-py                   0.15.0             pyhd3eb1b0_0    defaults
aiohttp                   3.7.4.post0      py36h2bbff1b_2    defaults
astor                     0.8.1            py36haa95532_0    defaults
async-timeout             3.0.1            py36haa95532_0    defaults
attrs                     21.4.0             pyhd3eb1b0_0    defaults
babel                     2.9.1              pyhd3eb1b0_0    defaults
blas                      1.0                         mkl    defaults
blinker                   1.4              py36haa95532_0    defaults
brotlipy                  0.7.0           py36h2bbff1b_1003    defaults
ca-certificates           2022.4.26            haa95532_0    defaults
cachetools                4.2.2              pyhd3eb1b0_0    defaults
certifi                   2021.5.30        py36haa95532_0    defaults
cffi                      1.14.6           py36h2bbff1b_0    defaults
chardet                   4.0.0           py36haa95532_1003    defaults
charset-normalizer        2.0.4              pyhd3eb1b0_0    defaults
click                     8.0.3              pyhd3eb1b0_0    defaults
colorama                  0.4.4              pyhd3eb1b0_0    defaults
coverage                  5.5              py36h2bbff1b_2    defaults
cryptography              35.0.0           py36h71e12ea_0    defaults
cudatoolkit               11.3.1               h59b6b97_2    defaults
cycler                    0.11.0             pyhd3eb1b0_0    defaults
cython                    0.29.24          py36hd77b12b_0    defaults
dataclasses               0.8                pyh4f3eec9_6    defaults
freetype                  2.10.4               hd328e21_0    defaults
gast                      0.2.2                    py36_0    defaults
google-auth               2.6.0              pyhd3eb1b0_0    defaults
google-auth-oauthlib      0.4.4              pyhd3eb1b0_0    defaults
google-pasta              0.2.0              pyhd3eb1b0_0    defaults
grpcio                    1.36.1           py36hc60d5dd_1    defaults
h5py                      2.10.0           py36h5e291fa_0    defaults
hdf5                      1.10.4               h7ebc959_0    defaults
icc_rt                    2019.0.0             h0cc432a_1    defaults
icu                       58.2                 ha925a31_3    defaults
idna                      3.3                pyhd3eb1b0_0    defaults
idna_ssl                  1.1.0            py36haa95532_0    defaults
importlib-metadata        4.8.1            py36haa95532_0    defaults
intel-openmp              2019.4                      245    defaults
jpeg                      9e                   h2bbff1b_0    defaults
keras-applications        1.0.8                      py_1    defaults
keras-preprocessing       1.1.2              pyhd3eb1b0_0    defaults
kiwisolver                1.3.1            py36hd77b12b_0    defaults
libmklml                  2019.0.5             haa95532_0    defaults
libopencv                 3.4.2                h20b85fd_0    defaults
libpng                    1.6.37               h2a8f88b_0    defaults
libprotobuf               3.17.2               h23ce68f_1    defaults
libtiff                   4.2.0                he0120a3_1    defaults
libuv                     1.40.0               he774522_0    defaults
libwebp                   1.2.2                h2bbff1b_0    defaults
lz4-c                     1.9.3                h2bbff1b_1    defaults
markdown                  3.3.4            py36haa95532_0    defaults
matplotlib                3.3.4            py36haa95532_0    defaults
matplotlib-base           3.3.4            py36h49ac443_0    defaults
mkl                       2020.2                      256    defaults
mkl-service               2.3.0            py36hb782905_0    defaults
mkl_fft                   1.3.0            py36h46781fe_0    defaults
mkl_random                1.1.1            py36h47e9c7a_0    defaults
multidict                 5.1.0            py36h2bbff1b_2    defaults
nibabel                   3.2.2                     <pip>
numpy                     1.19.2           py36hadc3359_0    defaults
numpy-base                1.19.2           py36ha3acd2a_0    defaults
oauthlib                  3.1.0                      py_0    defaults
olefile                   0.46               pyhd3eb1b0_0    defaults
openssl                   1.1.1p               h2bbff1b_0    defaults
opt_einsum                3.3.0              pyhd3eb1b0_1    defaults
packaging                 21.3                      <pip>
pandas                    1.1.5            py36hf11a4ad_0    defaults
Pillow                    8.4.0                     <pip>
pillow                    8.3.1            py36h8f6046a_0    defaults
Pillow-PIL                0.1.dev0                  <pip>
pip                       21.3.1                    <pip>
pip                       9.0.1                    py36_1    https://repo.continuum.io/pkgs/free
protobuf                  3.17.2           py36hd77b12b_0    defaults
py-opencv                 3.4.2            py36hc319ecb_0    defaults
pyasn1                    0.4.8              pyhd3eb1b0_0    defaults
pyasn1-modules            0.2.8                      py_0    defaults
pycparser                 2.21               pyhd3eb1b0_0    defaults
pydicom                   2.3.0              pyh6c4a22f_0    conda-forge
pyjwt                     2.1.0            py36haa95532_0    defaults
pynrrd                    0.4.3                     <pip>
pyopenssl                 22.0.0             pyhd3eb1b0_0    defaults
pyparsing                 3.0.4              pyhd3eb1b0_0    defaults
pyqt                      5.9.2            py36h6538335_2    defaults
pyreadline                2.1              py36h094d952_1    defaults
pysocks                   1.7.1            py36haa95532_0    defaults
python                    3.6.13               h3758d61_0    defaults
python-dateutil           2.8.2              pyhd3eb1b0_0    defaults
pytorch                   1.10.2          py3.6_cuda11.3_cudnn8_0    pytorch
pytorch-mutex             1.0                        cuda    pytorch
pytz                      2021.3             pyhd3eb1b0_0    defaults
qt                        5.9.7            vc14h73c81de_0    defaults
requests                  2.27.1             pyhd3eb1b0_0    defaults
requests-oauthlib         1.3.0                      py_0    defaults
rsa                       4.7.2              pyhd3eb1b0_1    defaults
scipy                     1.5.2            py36h9439919_0    defaults
setuptools                58.0.4           py36haa95532_0    defaults
SimpleITK                 2.1.1.2                   <pip>
sip                       4.19.8           py36h6538335_0    defaults
six                       1.16.0             pyhd3eb1b0_1    defaults
sqlite                    3.38.5               h2bbff1b_0    defaults
tensorboard               2.4.0              pyhc547734_0    defaults
tensorboard-plugin-wit    1.6.0                      py_0    defaults
tensorflow                2.1.0           mkl_py36h31ad7c1_0    defaults
tensorflow-base           2.1.0           mkl_py36h230818c_0    defaults
tensorflow-estimator      2.6.0              pyh7b7c402_0    defaults
termcolor                 1.1.0            py36haa95532_1    defaults
tk                        8.6.12               h2bbff1b_0    defaults
torchaudio                0.10.2               py36_cu113    pytorch
torchvision               0.11.3               py36_cu113    pytorch
tornado                   6.1              py36h2bbff1b_0    defaults
tqdm                      4.63.0             pyhd3eb1b0_0    defaults
typing-extensions         4.1.1                hd3eb1b0_0    defaults
typing_extensions         4.1.1              pyh06a4308_0    defaults
urllib3                   1.26.8             pyhd3eb1b0_0    defaults
vc                        14.2                 h21ff451_1    defaults
vs2015_runtime            14.27.29016          h5e58377_2    defaults
werkzeug                  0.16.1                     py_0    defaults
wheel                     0.29.0                   py36_0    https://repo.continuum.io/pkgs/free
win_inet_pton             1.1.0            py36haa95532_0    defaults
wincertstore              0.2                      py36_0    https://repo.continuum.io/pkgs/free
wrapt                     1.12.1           py36he774522_1    defaults
xz                        5.2.5                h8cc25b3_1    defaults
yarl                      1.6.3            py36h2bbff1b_0    defaults
zipp                      3.6.0              pyhd3eb1b0_0    defaults
zlib                      1.2.12               h8cc25b3_2    defaults
zstd                      1.5.2                h19a0ad4_0    defaults
```

### Additional Context

Traceback (most recent call last):
File "C:\Users\999\Anaconda3\lib\site-packages\psutil\_pswindows.py", line 620, in wrapper
return fun(self, *args, **kwargs)
File "C:\Users\999\Anaconda3\lib\site-packages\psutil\_pswindows.py", line 690, in cmdline
ret = cext.proc_cmdline(self.pid)
PermissionError: [WinError 5] 拒绝访问。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "C:\Users\999\Anaconda3\lib\site-packages\anaconda_navigator\exceptions.py", line 75, in exception_handler
return_value = func(*args, **kwargs)
File "C:\Users\999\Anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 108, in start_app
if misc.load_pid() is None: # A stale lock might be around
File "C:\Users\999\Anaconda3\lib\site-packages\anaconda_navigator\utils\misc.py", line 384, in load_pid
cmds = process.cmdline()
File "C:\Users\999\Anaconda3\lib\site-packages\psutil\__init__.py", line 701, in cmdline
return self._proc.cmdline()
File "C:\Users\999\Anaconda3\lib\site-packages\psutil\_pswindows.py", line 623, in wrapper
raise AccessDenied(self.pid, self._name)
psutil.AccessDenied: psutil.AccessDenied (pid=2512)

**Comment by csoja** [comment]
please see https://docs.anaconda.com/anaconda/navigator/troubleshooting/#access-denied-error

**Comment by vshevchenko-anaconda** [comment]
Updated link to the troubleshooting page
https://docs.anaconda.com/free/navigator/troubleshooting/#access-denied-error

I'm closing this ticket as stale. Please, open a new ticket if needed.
