### ISSUE TITLE
UNEXPECTED ERROR ON NAVIGATOR START UP

### ISSUE THREAD

**Issue by Amethyst-crypto** [ContinuumIO/anaconda-issues#13046]
### Checklist

- [X] I added a descriptive title
- [X] I searched for other issues and couldn't find a solution or duplication
- [X] I already searched in Google and didn't find any good information or help
- [X] I looked at the [docs](https://docs.anaconda.com/anaconda/navigator/) and didn't see anything to help

### What happened?

I opened the anaconda application but it showed a navigation error. i re-installed it and it still showed the same error.

Main Error
unacceptable character #x0000: special characters are not allowed
  in "C:\Users\HP\.continuum\anaconda-client\config.yaml", position 0
Traceback
Traceback (most recent call last):
  File "C:\Users\HP\anaconda3\lib\site-packages\anaconda_navigator\exceptions.py", line 74, in exception_handler
    return_value = func(*args, **kwargs)
  File "C:\Users\HP\anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 137, in start_app
    window = run_app(splash)
  File "C:\Users\HP\anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 60, in run_app
    window = MainWindow(splash=splash)
  File "C:\Users\HP\anaconda3\lib\site-packages\anaconda_navigator\widgets\main_window\__init__.py", line 224, in __init__
    for _ in anaconda_solvers.POOL.solve():
  File "C:\Users\HP\anaconda3\lib\site-packages\anaconda_navigator\utils\anaconda_solvers\core.py", line 72, in solve
    configuration: typing.Any = binstar_client.utils.get_config()
  File "C:\Users\HP\anaconda3\lib\site-packages\binstar_client\utils\config.py", line 250, in get_config
    file_configs = load_file_configs(SEARCH_PATH)
  File "C:\Users\HP\anaconda3\lib\site-packages\binstar_client\utils\config.py", line 242, in load_file_configs
    raw_data = collections.OrderedDict(kv for kv in itertools.chain.from_iterable(load_paths))
  File "C:\Users\HP\anaconda3\lib\site-packages\binstar_client\utils\config.py", line 242, in 
    raw_data = collections.OrderedDict(kv for kv in itertools.chain.from_iterable(load_paths))
  File "C:\Users\HP\anaconda3\lib\site-packages\binstar_client\utils\config.py", line 222, in _dir_yaml_loader
    yield filepath, load_config(filepath)
  File "C:\Users\HP\anaconda3\lib\site-packages\binstar_client\utils\config.py", line 206, in load_config
    data = yaml_load(fd)
  File "C:\Users\HP\anaconda3\lib\site-packages\binstar_client\utils\yaml.py", line 12, in yaml_load
    return safe_load(stream)
  File "C:\Users\HP\anaconda3\lib\site-packages\yaml\__init__.py", line 125, in safe_load
    return load(stream, SafeLoader)
  File "C:\Users\HP\anaconda3\lib\site-packages\yaml\__init__.py", line 79, in load
    loader = Loader(stream)
  File "C:\Users\HP\anaconda3\lib\site-packages\yaml\loader.py", line 34, in __init__
    Reader.__init__(self, stream)
  File "C:\Users\HP\anaconda3\lib\site-packages\yaml\reader.py", line 85, in __init__
    self.determine_encoding()
  File "C:\Users\HP\anaconda3\lib\site-packages\yaml\reader.py", line 135, in determine_encoding
    self.update(1)
  File "C:\Users\HP\anaconda3\lib\site-packages\yaml\reader.py", line 169, in update
    self.check_printable(data)
  File "C:\Users\HP\anaconda3\lib\site-packages\yaml\reader.py", line 143, in check_printable
    raise ReaderError(self.name, position, ord(character),
yaml.reader.ReaderError: unacceptable character #x0000: special characters are not allowed
  in "C:\Users\HP\.continuum\anaconda-client\config.yaml", position 0

### Conda info

```shell
'conda' is not recognized as an internal or external command,
operable program or batch file.
```

### Conda config

```shell
'conda' is not recognized as an internal or external command,
operable program or batch file.
```

### Conda list

```shell
'conda' is not recognized as an internal or external command,
operable program or batch file.
```

**Comment by csoja** [comment]
Looks like C:\Users\HP.continuum\anaconda-client\config.yaml has gotten corrupted.  If you rename that file to config.old, it should get you past your current problem.

as a side note, you will want to run the conda commands (conda info, conda config, conda list) in the anaconda prompt so the conda environment is appropriately activated.

**Comment by vshevchenko-anaconda** [comment]
Troubleshooting page [Delete your .continuum folder](https://docs.anaconda.com/free/navigator/troubleshooting/#anaconda-navigator-fails-to-start-and-gives-permission-denied-error:~:text=to%20most%20complex.-,Delete%20your%20.continuum%20folder,-Back%20up%20your) should help.

I'm closing this ticket as stale. Please, open a new ticket if needed.
