### ISSUE TITLE
binstar [ERROR].-

### ISSUE THREAD

**Issue by jimsrc** [ContinuumIO/anaconda-issues#1304]
When I do:
```bash
$ binstar --show-traceback search -t conda cython
```
I get:

```bash
Using Anaconda API: https://api.anaconda.org
Run 'anaconda show <USER/PACKAGE>' to get more details:
Packages:
     Name                      |  Version | Package Types   | Platforms
     ------------------------- |   ------ | --------------- | ---------------
     RahulJain/cython          |     0.24 | conda           | win-64
     RaspberryPi/cython        |   0.23.1 | conda           | linux-armv6l
     aetrial/cython            |          | conda           | linux-64, osx-64
     anaconda/cython           |   0.25.2 | conda           | linux-64, win-32, win-64, linux-32, osx-64
     astropy-ci-extras/cython  |   0.20.1 | conda           | linux-64
     auto/cython               |   0.20.1 | conda           | linux-64
                                          : http://www.cython.org
     auto/cython-codegen       |      0.2 | conda           | linux-64, linux-32
                                          : UNKNOWN
     auto/cython-plugin        |      1.0 | conda           | linux-64, linux-32
                                          : https://bitbucket.org/jaraco/cython-plugin
     bioconda/setuptools_cython |    0.2.1 | conda           | linux-64, osx-64
                                          : Cython setuptools integration
     clg_boar/cython           |   0.23.4 | conda           | win-64
     conda-forge/cython        |   0.25.2 | conda           | linux-64, win-32, win-64, osx-64
                                          : The Cython compiler for writing C extensions for the Python language
     conda-forge/cythongsl     |    0.2.1 | conda           | linux-64, osx-64
                                          : CythonGSL provides a Cython interface for the GNU Scientific Library (GSL).
     dhirschfeld/cython_gsl    | 0.2.1.post.9251fcbe56 | conda           | win-32, win-64
                                          : https://github.com/twiecki/CythonGSL
     hargup/cython             |          | conda           | linux-64
                                          : The Cython compiler for writing C extensions for the Python language.
     intel/cython              |     0.24 | conda           | linux-64, win-64, osx-64
[ERROR]
Traceback (most recent call last):
  File "/home/jim/anaconda2/bin/binstar", line 6, in <module>
    sys.exit(binstar_client.scripts.cli.main())
  File "/home/jim/anaconda2/lib/python2.7/site-packages/binstar_client/scripts/cli.py", line 87, in main
    description=__doc__, version=version)
  File "/home/jim/anaconda2/lib/python2.7/site-packages/binstar_client/scripts/cli.py", line 66, in binstar_main
    return args.main(args)
  File "/home/jim/anaconda2/lib/python2.7/site-packages/binstar_client/commands/search.py", line 15, in search
    pprint_packages(packages, access=False)
  File "/home/jim/anaconda2/lib/python2.7/site-packages/binstar_client/utils/pprint.py", line 70, in pprint_packages
    pprint_package(package, access, full_name, revision=revisions)
  File "/home/jim/anaconda2/lib/python2.7/site-packages/binstar_client/utils/pprint.py", line 34, in pprint_package
    package['conda_platforms'] = ', '.join(package['conda_platforms'])
TypeError: sequence item 0: expected string or Unicode, NoneType found
```

This same error message occurs when I search for several other packages. However, for some other packages (installed or not installed in my pc) this error doen't occur.
I don't get to understand what's going on.

This is my info:
```bash
Current conda install:

               platform : linux-64
          conda version : 4.2.13
       conda is private : False
      conda-env version : 4.2.13
    conda-build version : 2.0.2
         python version : 2.7.12.final.0
       requests version : 2.11.1
       root environment : /home/jim/anaconda2  (writable)
    default environment : /home/jim/anaconda2
       envs directories : /home/jim/anaconda2/envs
          package cache : /home/jim/anaconda2/pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : None
           offline mode : False
```

Thank you very much!

**Comment by FelipeCalliari** [comment]
**Even if it is not the best solution..**

The problem can be easily solved by editting this file:
```
[anaconda_path]\lib\site-packages\binstar_client\utils\pprint.py
```

**Original**
line34: `package['conda_platforms'] = ', '.join(package['conda_platforms'])`

**Modified**
line34: `if package['conda_platforms'].count(None):`
line35: `     package['conda_platforms'].remove(None)`
line36: `package['conda_platforms'] = ', '.join(package['conda_platforms'])`

**Comment by jimsrc** [comment]
this patch  works!! (Y)
