### ISSUE TITLE
Anaconda Navigator won't open - MacOs Sierra Version 10.12.6

### ISSUE THREAD

**Issue by PaulosMak** [ContinuumIO/anaconda-issues#13114]
### Checklist

- [X] I added a descriptive title.
- [X] I searched through [existing issues](https://github.com/ContinuumIO/anaconda-issues/issues) and couldn't find a solution or duplicate issue.
- [X] I searched on the web (e.g. Google) and didn't find any helpful information.
- [X] I searched the [Anaconda documentation](https://docs.anaconda.com/) and didn't find any helpful information.

### Impacted product

- [X] A conda package (built by Anaconda)
- [X] Anaconda Distribution (formerly Anaconda Individual Edition)
- [ ] Miniconda
- [X] Anaconda.org

### What happened?

I updated anaconda and now it won't open. 
Anaconda Navigator won't open. 

Tried $ anaconda-navigator

I get this traceback error:

Traceback (most recent call last):
  File "/opt/anaconda3/bin/anaconda-navigator", line 7, in <module>
    from anaconda_navigator.app.main import main
  File "/opt/anaconda3/lib/python3.8/site-packages/anaconda_navigator/app/main.py", line 19, in <module>
    from anaconda_navigator.app.start import start_app
  File "/opt/anaconda3/lib/python3.8/site-packages/anaconda_navigator/app/start.py", line 15, in <module>
    from qtpy.QtCore import QCoreApplication, QEvent, QObject, Qt  # pylint: disable=no-name-in-module
  File "/opt/anaconda3/lib/python3.8/site-packages/qtpy/QtCore.py", line 15, in <module>
    from PyQt5.QtCore import *
ImportError: dlopen(/opt/anaconda3/lib/python3.8/site-packages/PyQt5/QtCore.abi3.so, 2): Symbol not found: _futimens
  Referenced from: /opt/anaconda3/lib/python3.8/site-packages/PyQt5/../../../libQt5Core.5.dylib (which was built for Mac OS X 10.13)
  Expected in: /usr/lib/libSystem.B.dylib
 in /opt/anaconda3/lib/python3.8/site-packages/PyQt5/../../../libQt5Core.5.dylib
(base) fasikas-MacBook-Pro:~ Paulos$ 

### Expected behavior or outcome

It seems like qt is not compatible with my mac. What do I do now. Is there a way to go back to the old version of anaconda.

### Conda info

```shell
active environment : base
    active env location : /opt/anaconda3
            shell level : 1
       user config file : /Users/Melat/.condarc
 populated config files : /Users/Melat/.condarc
          conda version : 22.11.1
    conda-build version : 3.20.5
         python version : 3.8.5.final.0
       virtual packages : __archspec=1=x86_64
                          __osx=10.12.6=0
                          __unix=0=0
       base environment : /opt/anaconda3  (writable)
      conda av data dir : /opt/anaconda3/etc/conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/osx-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/osx-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /opt/anaconda3/pkgs
                          /Users/Melat/.conda/pkgs
       envs directories : /opt/anaconda3/envs
                          /Users/Melat/.conda/envs
               platform : osx-64
             user-agent : conda/22.11.1 requests/2.28.1 CPython/3.8.5 Darwin/16.7.0 OSX/10.12.6
                UID:GID : 502:20
             netrc file : None
           offline mode : False
```

### Conda config

```shell
==> /Users/Melat/.condarc <==
ssl_verify: True
channels:
  - defaults
```

**Comment by slawomirmarczynski** [comment]
I had got a similar trouble. It was a "random.py" file with an hello-world program content which had been loaded instead valid random package from std. lib. A kind of a race on the python path.
