### ISSUE TITLE
Cannot open Anaconda navigator after installing BERT package - MAC

### ISSUE THREAD

**Issue by Yvette0512** [ContinuumIO/anaconda-issues#13173]
### Checklist

- [X] I added a descriptive title
- [X] I searched for other issues and couldn't find a solution or duplication
- [X] I already searched in Google and didn't find any good information or help
- [X] I looked at the [docs](https://docs.anaconda.com/anaconda/navigator/) and didn't see anything to help

### What happened?

I cannot open Anaconda after installing a package called BERT. After I opened Anaconda, the icon jumps to the bottom of my screen and then disappears. And then I cannot find the Anaconda on the Chrome website.

### Conda info

```shell
# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/opt/anaconda3/lib/python3.9/site-packages/conda/exceptions.py", line 1118, in __call__
        return func(*args, **kwargs)
      File "/opt/anaconda3/lib/python3.9/site-packages/conda/cli/main.py", line 57, in main_subshell
        p = generate_parser()
      File "/opt/anaconda3/lib/python3.9/site-packages/conda/cli/conda_argparse.py", line 40, in generate_parser
        p = ArgumentParser(
      File "/opt/anaconda3/lib/python3.9/site-packages/conda/cli/conda_argparse.py", line 117, in __init__
        self._subcommands = context.plugin_manager.get_hook_results("subcommands")
      File "/opt/anaconda3/lib/python3.9/site-packages/conda/base/context.py", line 421, in plugin_manager
        from ..plugins.manager import get_plugin_manager
      File "/opt/anaconda3/lib/python3.9/site-packages/conda/plugins/__init__.py", line 3, in <module>
        from .hookspec import hookimpl  # noqa: F401
      File "/opt/anaconda3/lib/python3.9/site-packages/conda/plugins/hookspec.py", line 10, in <module>
        from .types import CondaSolver, CondaSubcommand, CondaVirtualPackage
      File "/opt/anaconda3/lib/python3.9/site-packages/conda/plugins/types.py", line 6, in <module>
        from ..core.solve import Solver
      File "/opt/anaconda3/lib/python3.9/site-packages/conda/core/solve.py", line 19, in <module>
        from .index import get_reduced_index, _supplement_index_with_system
      File "/opt/anaconda3/lib/python3.9/site-packages/conda/core/index.py", line 15, in <module>
        from .package_cache_data import PackageCacheData
      File "/opt/anaconda3/lib/python3.9/site-packages/conda/core/package_cache_data.py", line 26, in <module>
        from .path_actions import CacheUrlAction, ExtractPackageAction
      File "/opt/anaconda3/lib/python3.9/site-packages/conda/core/path_actions.py", line 32, in <module>
        from ..gateways.connection.download import download
      File "/opt/anaconda3/lib/python3.9/site-packages/conda/gateways/connection/download.py", line 12, in <module>
        from .session import CondaSession
      File "/opt/anaconda3/lib/python3.9/site-packages/conda/gateways/connection/session.py", line 11, in <module>
        from .adapters.s3 import S3Adapter
      File "/opt/anaconda3/lib/python3.9/site-packages/conda/gateways/connection/adapters/s3.py", line 10, in <module>
        import boto3
      File "/opt/anaconda3/lib/python3.9/site-packages/boto3/__init__.py", line 17, in <module>
        from boto3.session import Session
      File "/opt/anaconda3/lib/python3.9/site-packages/boto3/session.py", line 17, in <module>
        import botocore.session
      File "/opt/anaconda3/lib/python3.9/site-packages/botocore/session.py", line 26, in <module>
        import botocore.client
      File "/opt/anaconda3/lib/python3.9/site-packages/botocore/client.py", line 15, in <module>
        from botocore import waiter, xform_name
      File "/opt/anaconda3/lib/python3.9/site-packages/botocore/waiter.py", line 18, in <module>
        from botocore.docs.docstring import WaiterDocstring
      File "/opt/anaconda3/lib/python3.9/site-packages/botocore/docs/__init__.py", line 15, in <module>
        from botocore.docs.service import ServiceDocumenter
      File "/opt/anaconda3/lib/python3.9/site-packages/botocore/docs/service.py", line 14, in <module>
        from botocore.docs.client import ClientDocumenter, ClientExceptionsDocumenter
      File "/opt/anaconda3/lib/python3.9/site-packages/botocore/docs/client.py", line 14, in <module>
        from botocore.docs.example import ResponseExampleDocumenter
      File "/opt/anaconda3/lib/python3.9/site-packages/botocore/docs/example.py", line 13, in <module>
        from botocore.docs.shape import ShapeDocumenter
      File "/opt/anaconda3/lib/python3.9/site-packages/botocore/docs/shape.py", line 19, in <module>
        from botocore.utils import is_json_value_header
      File "/opt/anaconda3/lib/python3.9/site-packages/botocore/utils.py", line 34, in <module>
        import botocore.httpsession
      File "/opt/anaconda3/lib/python3.9/site-packages/botocore/httpsession.py", line 34, in <module>
        from urllib3.contrib.pyopenssl import orig_util_SSLContext as SSLContext
      File "/opt/anaconda3/lib/python3.9/site-packages/urllib3/contrib/pyopenssl.py", line 50, in <module>
        import OpenSSL.SSL
      File "/opt/anaconda3/lib/python3.9/site-packages/OpenSSL/__init__.py", line 8, in <module>
        from OpenSSL import crypto, SSL
      File "/opt/anaconda3/lib/python3.9/site-packages/OpenSSL/crypto.py", line 14, in <module>
        from cryptography import utils, x509
      File "/opt/anaconda3/lib/python3.9/site-packages/cryptography/x509/__init__.py", line 6, in <module>
        from cryptography.x509 import certificate_transparency
      File "/opt/anaconda3/lib/python3.9/site-packages/cryptography/x509/certificate_transparency.py", line 10, in <module>
        from cryptography.hazmat.bindings._rust import x509 as rust_x509
    pyo3_runtime.PanicException: Python API call failed

`$ /opt/anaconda3/bin/conda info`
```

### Conda config

```shell
During handling of the above exception, another exception occurred:

ImportError: dlopen(/opt/anaconda3/lib/python3.9/site-packages/_cffi_backend.cpython-39-darwin.so, 0x0002): Library not loaded: '@rpath/libffi.7.dylib'
  Referenced from: '/opt/anaconda3/lib/python3.9/site-packages/_cffi_backend.cpython-39-darwin.so'
  Reason: tried: '/opt/anaconda3/lib/libffi.7.dylib' (no such file), '/opt/anaconda3/lib/libffi.7.dylib' (no such file), '/opt/anaconda3/lib/python3.9/site-packages/../../libffi.7.dylib' (no such file), '/opt/anaconda3/lib/libffi.7.dylib' (no such file), '/opt/anaconda3/lib/libffi.7.dylib' (no such file), '/opt/anaconda3/lib/python3.9/site-packages/../../libffi.7.dylib' (no such file), '/opt/anaconda3/bin/../lib/libffi.7.dylib' (no such file), '/opt/anaconda3/bin/../lib/libffi.7.dylib' (no such file), '/usr/local/lib/libffi.7.dylib' (no such file), '/usr/lib/libffi.7.dylib' (no such file)
thread '<unnamed>' panicked at 'Python API call failed', /Users/runner/miniforge3/conda-bld/cryptography-split_1679811332750/_build_env/.cargo/registry/src/github.com-1ecc6299db9ec823/pyo3-0.15.2/src/err/mod.rs:582:5
Traceback (most recent call last):
  File "/opt/anaconda3/bin/conda", line 13, in <module>
    sys.exit(main())
  File "/opt/anaconda3/lib/python3.9/site-packages/conda/cli/main.py", line 112, in main
    return conda_exception_handler(main, *args, **kwargs)
  File "/opt/anaconda3/lib/python3.9/site-packages/conda/exceptions.py", line 1418, in conda_exception_handler
    return_value = exception_handler(func, *args, **kwargs)
  File "/opt/anaconda3/lib/python3.9/site-packages/conda/exceptions.py", line 1121, in __call__
    return self.handle_exception(exc_val, exc_tb)
  File "/opt/anaconda3/lib/python3.9/site-packages/conda/exceptions.py", line 1161, in handle_exception
    return self.handle_unexpected_exception(exc_val, exc_tb)
  File "/opt/anaconda3/lib/python3.9/site-packages/conda/exceptions.py", line 1171, in handle_unexpected_exception
    error_report = self.get_error_report(exc_val, exc_tb)
  File "/opt/anaconda3/lib/python3.9/site-packages/conda/exceptions.py", line 1193, in get_error_report
    from .cli.main_info import get_info_dict
  File "/opt/anaconda3/lib/python3.9/site-packages/conda/cli/main_info.py", line 17, in <module>
    from ..core.index import _supplement_index_with_system
  File "/opt/anaconda3/lib/python3.9/site-packages/conda/core/index.py", line 15, in <module>
    from .package_cache_data import PackageCacheData
  File "/opt/anaconda3/lib/python3.9/site-packages/conda/core/package_cache_data.py", line 26, in <module>
    from .path_actions import CacheUrlAction, ExtractPackageAction
  File "/opt/anaconda3/lib/python3.9/site-packages/conda/core/path_actions.py", line 32, in <module>
    from ..gateways.connection.download import download
  File "/opt/anaconda3/lib/python3.9/site-packages/conda/gateways/connection/download.py", line 12, in <module>
    from .session import CondaSession
  File "/opt/anaconda3/lib/python3.9/site-packages/conda/gateways/connection/session.py", line 11, in <module>
    from .adapters.s3 import S3Adapter
  File "/opt/anaconda3/lib/python3.9/site-packages/conda/gateways/connection/adapters/s3.py", line 10, in <module>
    import boto3
  File "/opt/anaconda3/lib/python3.9/site-packages/boto3/__init__.py", line 17, in <module>
    from boto3.session import Session
  File "/opt/anaconda3/lib/python3.9/site-packages/boto3/session.py", line 17, in <module>
    import botocore.session
  File "/opt/anaconda3/lib/python3.9/site-packages/botocore/session.py", line 26, in <module>
    import botocore.client
  File "/opt/anaconda3/lib/python3.9/site-packages/botocore/client.py", line 15, in <module>
    from botocore import waiter, xform_name
  File "/opt/anaconda3/lib/python3.9/site-packages/botocore/waiter.py", line 18, in <module>
    from botocore.docs.docstring import WaiterDocstring
  File "/opt/anaconda3/lib/python3.9/site-packages/botocore/docs/__init__.py", line 15, in <module>
    from botocore.docs.service import ServiceDocumenter
  File "/opt/anaconda3/lib/python3.9/site-packages/botocore/docs/service.py", line 14, in <module>
    from botocore.docs.client import ClientDocumenter, ClientExceptionsDocumenter
  File "/opt/anaconda3/lib/python3.9/site-packages/botocore/docs/client.py", line 14, in <module>
    from botocore.docs.example import ResponseExampleDocumenter
  File "/opt/anaconda3/lib/python3.9/site-packages/botocore/docs/example.py", line 13, in <module>
    from botocore.docs.shape import ShapeDocumenter
  File "/opt/anaconda3/lib/python3.9/site-packages/botocore/docs/shape.py", line 19, in <module>
    from botocore.utils import is_json_value_header
  File "/opt/anaconda3/lib/python3.9/site-packages/botocore/utils.py", line 34, in <module>
    import botocore.httpsession
  File "/opt/anaconda3/lib/python3.9/site-packages/botocore/httpsession.py", line 34, in <module>
    from urllib3.contrib.pyopenssl import orig_util_SSLContext as SSLContext
  File "/opt/anaconda3/lib/python3.9/site-packages/urllib3/contrib/pyopenssl.py", line 50, in <module>
    import OpenSSL.SSL
  File "/opt/anaconda3/lib/python3.9/site-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import crypto, SSL
  File "/opt/anaconda3/lib/python3.9/site-packages/OpenSSL/crypto.py", line 14, in <module>
    from cryptography import utils, x509
  File "/opt/anaconda3/lib/python3.9/site-packages/cryptography/x509/__init__.py", line 6, in <module>
    from cryptography.x509 import certificate_transparency
  File "/opt/anaconda3/lib/python3.9/site-packages/cryptography/x509/certificate_transparency.py", line 10, in <module>
    from cryptography.hazmat.bindings._rust import x509 as rust_x509
pyo3_runtime.PanicException: Python API call failed
```

### Conda list

```shell
File "/opt/anaconda3/bin/conda", line 13, in <module>
    sys.exit(main())
  File "/opt/anaconda3/lib/python3.9/site-packages/conda/cli/main.py", line 112, in main
    return conda_exception_handler(main, *args, **kwargs)
  File "/opt/anaconda3/lib/python3.9/site-packages/conda/exceptions.py", line 1418, in conda_exception_handler
    return_value = exception_handler(func, *args, **kwargs)
  File "/opt/anaconda3/lib/python3.9/site-packages/conda/exceptions.py", line 1121, in __call__
    return self.handle_exception(exc_val, exc_tb)
  File "/opt/anaconda3/lib/python3.9/site-packages/conda/exceptions.py", line 1161, in handle_exception
    return self.handle_unexpected_exception(exc_val, exc_tb)
  File "/opt/anaconda3/lib/python3.9/site-packages/conda/exceptions.py", line 1171, in handle_unexpected_exception
    error_report = self.get_error_report(exc_val, exc_tb)
  File "/opt/anaconda3/lib/python3.9/site-packages/conda/exceptions.py", line 1193, in get_error_report
    from .cli.main_info import get_info_dict
  File "/opt/anaconda3/lib/python3.9/site-packages/conda/cli/main_info.py", line 17, in <module>
    from ..core.index import _supplement_index_with_system
  File "/opt/anaconda3/lib/python3.9/site-packages/conda/core/index.py", line 15, in <module>
    from .package_cache_data import PackageCacheData
  File "/opt/anaconda3/lib/python3.9/site-packages/conda/core/package_cache_data.py", line 26, in <module>
    from .path_actions import CacheUrlAction, ExtractPackageAction
  File "/opt/anaconda3/lib/python3.9/site-packages/conda/core/path_actions.py", line 32, in <module>
    from ..gateways.connection.download import download
  File "/opt/anaconda3/lib/python3.9/site-packages/conda/gateways/connection/download.py", line 12, in <module>
    from .session import CondaSession
  File "/opt/anaconda3/lib/python3.9/site-packages/conda/gateways/connection/session.py", line 11, in <module>
    from .adapters.s3 import S3Adapter
  File "/opt/anaconda3/lib/python3.9/site-packages/conda/gateways/connection/adapters/s3.py", line 10, in <module>
    import boto3
  File "/opt/anaconda3/lib/python3.9/site-packages/boto3/__init__.py", line 17, in <module>
    from boto3.session import Session
  File "/opt/anaconda3/lib/python3.9/site-packages/boto3/session.py", line 17, in <module>
    import botocore.session
  File "/opt/anaconda3/lib/python3.9/site-packages/botocore/session.py", line 26, in <module>
    import botocore.client
  File "/opt/anaconda3/lib/python3.9/site-packages/botocore/client.py", line 15, in <module>
    from botocore import waiter, xform_name
  File "/opt/anaconda3/lib/python3.9/site-packages/botocore/waiter.py", line 18, in <module>
    from botocore.docs.docstring import WaiterDocstring
  File "/opt/anaconda3/lib/python3.9/site-packages/botocore/docs/__init__.py", line 15, in <module>
    from botocore.docs.service import ServiceDocumenter
  File "/opt/anaconda3/lib/python3.9/site-packages/botocore/docs/service.py", line 14, in <module>
    from botocore.docs.client import ClientDocumenter, ClientExceptionsDocumenter
  File "/opt/anaconda3/lib/python3.9/site-packages/botocore/docs/client.py", line 14, in <module>
    from botocore.docs.example import ResponseExampleDocumenter
  File "/opt/anaconda3/lib/python3.9/site-packages/botocore/docs/example.py", line 13, in <module>
    from botocore.docs.shape import ShapeDocumenter
  File "/opt/anaconda3/lib/python3.9/site-packages/botocore/docs/shape.py", line 19, in <module>
    from botocore.utils import is_json_value_header
  File "/opt/anaconda3/lib/python3.9/site-packages/botocore/utils.py", line 34, in <module>
    import botocore.httpsession
  File "/opt/anaconda3/lib/python3.9/site-packages/botocore/httpsession.py", line 34, in <module>
    from urllib3.contrib.pyopenssl import orig_util_SSLContext as SSLContext
  File "/opt/anaconda3/lib/python3.9/site-packages/urllib3/contrib/pyopenssl.py", line 50, in <module>
    import OpenSSL.SSL
  File "/opt/anaconda3/lib/python3.9/site-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import crypto, SSL
  File "/opt/anaconda3/lib/python3.9/site-packages/OpenSSL/crypto.py", line 14, in <module>
    from cryptography import utils, x509
  File "/opt/anaconda3/lib/python3.9/site-packages/cryptography/x509/__init__.py", line 6, in <module>
    from cryptography.x509 import certificate_transparency
  File "/opt/anaconda3/lib/python3.9/site-packages/cryptography/x509/certificate_transparency.py", line 10, in <module>
    from cryptography.hazmat.bindings._rust import x509 as rust_x509
pyo3_runtime.PanicException: Python API call failed
```

**Comment by Sentient07** [comment]
Facing the same error. Any updates?
