### ISSUE TITLE
UnicodeDecodeError while checking VSCode version

### ISSUE THREAD

**Issue by manuco** [ContinuumIO/anaconda-issues#13186]
### Checklist

- [X] I added a descriptive title
- [X] I searched for other issues and couldn't find a solution or duplication
- [X] I already searched in Google and didn't find any good information or help
- [X] I looked at the [docs](https://docs.anaconda.com/anaconda/navigator/) and didn't see anything to help

### What happened?

# Summary

When launching Anaconda Navigator, the following exception prevents the software to launch properly :

**See after for an analysis**

```
# Command trying to be launched
['C:\\(path to VSCode)\\VisualStudio\\bin\\code.cmd', '--version']

# Raw stderr printed for debug (my addition)
b"'\\\\(host)\\DFS_USERS$\\(user)\\(some random dir)'\r\nCMD.EXE a \x82t\x82 d\x82marr\x82 avec le chemin d'acc\x8as comme r\x82pertoire en\r\ncours. Les chemins d'acc\x8as UNC ne sont pas prise en charge. Utilisation\r\ndu r\x82pertoire Windows par d\x82faut.\r\n"

# The exception
2023-05-04 16:39:39,952 - ERROR __init__.global_exception_logger:19
'utf-8' codec can't decode byte 0x82 in position 62: invalid start byte
Traceback (most recent call last):
  File "C:\Developpement\Anaconda3\lib\site-packages\anaconda_navigator\widgets\main_window\__init__.py", line 486, in setup
    self.post_setup(conda_data=output)
  File "C:\Developpement\Anaconda3\lib\site-packages\anaconda_navigator\widgets\main_window\__init__.py", line 514, in post_setup
    self.tab_home.setup(conda_data)
  File "C:\Developpement\Anaconda3\lib\site-packages\anaconda_navigator\widgets\tabs\home.py", line 253, in setup
    self.update_applications()
  File "C:\Developpement\Anaconda3\lib\site-packages\anaconda_navigator\widgets\tabs\home.py", line 292, in update_applications
    self.api.process_apps(self.__applications, prefix=self.current_prefix).values(),
  File "C:\Developpement\Anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 502, in process_apps
    collected_applications: external_apps.ApplicationCollection = external_apps.get_applications(
  File "C:\Developpement\Anaconda3\lib\site-packages\anaconda_navigator\api\external_apps\__init__.py", line 49, in get_applications
    apps: typing.Sequence[typing.Union[BaseApp, AppPatch]] = config_utils.load_configuration(context=context)
  File "C:\Developpement\Anaconda3\lib\site-packages\anaconda_navigator\api\external_apps\config_utils.py", line 217, in load_configuration
    return apply_configuration(
  File "C:\Developpement\Anaconda3\lib\site-packages\anaconda_navigator\api\external_apps\config_utils.py", line 198, in apply_configuration
    addition: typing.Union[None, base.BaseApp, base.AppPatch] = base.BaseApp.parse_configuration(
  File "C:\Developpement\Anaconda3\lib\site-packages\anaconda_navigator\api\external_apps\base.py", line 233, in parse_configuration
    return target_cls._parse_configuration(  # pylint: disable=protected-access
  File "C:\Developpement\Anaconda3\lib\site-packages\anaconda_navigator\api\external_apps\base.py", line 458, in _parse_configuration
    result: BaseInstallableApp = BaseInstallableApp(
  File "<attrs generated init anaconda_navigator.api.external_apps.base.BaseInstallableApp>", line 16, in __init__
    self.__attrs_post_init__()
  File "C:\Developpement\Anaconda3\lib\site-packages\anaconda_navigator\api\external_apps\base.py", line 378, in __attrs_post_init__
    for location in self._detector(context=context):
  File "C:\Developpement\Anaconda3\lib\site-packages\anaconda_navigator\api\external_apps\bundle\vscode_utils.py", line 58, in __call__
    stdout, _, _ = conda_launch_utils.run_process([application.executable, '--version'])
  File "C:\Developpement\Anaconda3\lib\site-packages\anaconda_navigator\utils\conda\launch.py", line 50, in run_process
    stderr = ansi_utlils.escape_ansi(raw_stderr.decode())
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x82 in position 62: invalid start byte
```

# Analysis

When launching, Anaconda Navigator tries to guess version numbers of some external installable packages. Like VS Code which is installed on my computer. It does that by launching some processes, like `code.cmd --version`. And it launches this process in the home directory.

My home directory is not a local one, but some Windows UNC path (https://learn.microsoft.com/en-us/dotnet/standard/io/file-path-formats#unc-paths). UNC pathes are like `\\host\dir\file.txt` and don't contain drive letters (like `C:`).

Launching `code.cmd` is like launching `cmd.exe`, since `code.cmd` is a shell script (a Windows one). But `cmd.exe` doesn't support UNC pathes (🙄), so it warns on stderr, in the locale language (fr-FR for my case) and with the **locale default encoding** that it will choose another path. **That's not the problem**, but the reported errors will cause the problem.

In France, the Microsoft default encoding is [Windows-1252](https://en.wikipedia.org/wiki/Windows-1252), a friend of ISO8859-1 (so called "Latin-1"). This encoding is not the same as UTF-8. Decoding strings encoded with Windows-1252 (or any single byte encoding) with an UTF-8 decoder results in the famous UnicodeDecodeError.

So at the return of the `code.cmd` process, Anaconda Navigator tries to decode the stderr stream with the UTF-8 decoder, which fails, and the Navigator crashes.

See `anaconda_navigator\utils\conda\launch.py` line 50 for the place of the mis-decode operation.

Suggested fix :

```diff
        print(cmd_list)
        print(raw_stderr)
        
-        stderr = ansi_utlils.escape_ansi(raw_stderr.decode())
+        stderr = ansi_utlils.escape_ansi(raw_stderr.decode(errors="replace"))
    except OSError:
        error = True
```

### Conda info

```shell
active environment : base
    active env location : C:\<some local path>\Anaconda3
            shell level : 1
       user config file : C:\Users\<login>\.condarc
 populated config files : C:\Users\<login>\.condarc
          conda version : 23.1.0
    conda-build version : not installed
         python version : 3.10.9.final.0
       virtual packages : __archspec=1=x86_64
                          __win=0=0
       base environment : C:\<some local path>\Anaconda3  (writable)
      conda av data dir : C:\<some local path>\Anaconda3\etc\conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\<some local path>\Anaconda3\pkgs
                          C:\Users\<login>\.conda\pkgs
                          C:\Users\<login>\AppData\Local\conda\conda\pkgs
       envs directories : C:\<some local path>\Anaconda3\envs
                          C:\Users\<login>\.conda\envs
                          C:\Users\<login>\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/23.1.0 requests/2.28.1 CPython/3.10.9 Windows/10 Windows/10.0.19045
          administrator : False
             netrc file : None
           offline mode : False
```

### Conda config

```shell
==> C:\Users\<login>\.condarc <==
ssl_verify: True
channels:
  - defaults
```

### Conda list

```shell
# packages in environment at C:\<some local path>\Anaconda3:
#
# Name                    Version                   Build  Channel
anaconda-client           1.11.1          py310haa95532_0    defaults
anaconda-navigator        2.4.0           py310haa95532_0    defaults
attrs                     22.1.0          py310haa95532_0    defaults
brotlipy                  0.7.0           py310h2bbff1b_1002    defaults
bzip2                     1.0.8                he774522_0    defaults
ca-certificates           2023.01.10           haa95532_0    defaults
certifi                   2022.12.7       py310haa95532_0    defaults
cffi                      1.15.1          py310h2bbff1b_3    defaults
chardet                   4.0.0           py310haa95532_1003    defaults
charset-normalizer        2.0.4              pyhd3eb1b0_0    defaults
clyent                    1.2.2           py310haa95532_1    defaults
colorama                  0.4.6           py310haa95532_0    defaults
conda                     23.1.0          py310haa95532_0    defaults
conda-content-trust       0.1.3           py310haa95532_0    defaults
conda-package-handling    2.0.2           py310haa95532_0    defaults
conda-package-streaming   0.7.0           py310haa95532_0    defaults
conda-repo-cli            1.0.27          py310haa95532_0    defaults
conda-token               0.4.0              pyhd3eb1b0_0    defaults
console_shortcut_miniconda 0.1.1                haa95532_1    defaults
cryptography              38.0.4          py310h21b164f_0    defaults
defusedxml                0.7.1              pyhd3eb1b0_0    defaults
freetype                  2.12.1               ha860e81_0    defaults
giflib                    5.2.1                h8cc25b3_3    defaults
glib                      2.69.1               h5dc1a3c_2    defaults
gst-plugins-base          1.18.5               h9e645db_0    defaults
gstreamer                 1.18.5               hd78058f_0    defaults
icu                       58.2                 ha925a31_3    defaults
idna                      3.4             py310haa95532_0    defaults
jpeg                      9e                   h2bbff1b_1    defaults
jsonschema                4.17.3          py310haa95532_0    defaults
jupyter_core              5.2.0           py310haa95532_0    defaults
lerc                      3.0                  hd77b12b_0    defaults
libclang                  12.0.0          default_h627e005_2    defaults
libdeflate                1.17                 h2bbff1b_0    defaults
libffi                    3.4.2                hd77b12b_6    defaults
libiconv                  1.16                 h2bbff1b_2    defaults
libogg                    1.3.5                h2bbff1b_1    defaults
libpng                    1.6.39               h8cc25b3_0    defaults
libtiff                   4.5.0                h6c2663c_2    defaults
libvorbis                 1.3.7                he774522_0    defaults
libwebp                   1.2.4                hbc33d0d_1    defaults
libwebp-base              1.2.4                h2bbff1b_1    defaults
libxml2                   2.9.14               h0ad7f3c_0    defaults
libxslt                   1.1.35               h2bbff1b_0    defaults
lz4-c                     1.9.4                h2bbff1b_0    defaults
menuinst                  1.4.19          py310h59b6b97_0    defaults
navigator-updater         0.3.0           py310haa95532_0    defaults
nbformat                  5.7.0           py310haa95532_0    defaults
openssl                   1.1.1t               h2bbff1b_0    defaults
packaging                 22.0            py310haa95532_0    defaults
pathlib                   1.0.1              pyhd3eb1b0_1    defaults
pcre                      8.45                 hd77b12b_0    defaults
pillow                    9.4.0           py310hd77b12b_0    defaults
pip                       22.3.1          py310haa95532_0    defaults
platformdirs              2.5.2           py310haa95532_0    defaults
pluggy                    1.0.0           py310haa95532_1    defaults
ply                       3.11            py310haa95532_0    defaults
powershell_shortcut_miniconda 0.0.1                haa95532_1    defaults
psutil                    5.9.0           py310h2bbff1b_0    defaults
pycosat                   0.6.4           py310h2bbff1b_0    defaults
pycparser                 2.21               pyhd3eb1b0_0    defaults
pyjwt                     2.4.0           py310haa95532_0    defaults
pyopenssl                 22.0.0             pyhd3eb1b0_0    defaults
pyqt                      5.15.7          py310hd77b12b_0    defaults
pyqt5-sip                 12.11.0         py310hd77b12b_0    defaults
pyrsistent                0.18.0          py310h2bbff1b_0    defaults
pysocks                   1.7.1           py310haa95532_0    defaults
python                    3.10.9               h966fe2a_0    defaults
python-dateutil           2.8.2              pyhd3eb1b0_0    defaults
python-fastjsonschema     2.16.2          py310haa95532_0    defaults
pytz                      2022.7          py310haa95532_0    defaults
pywin32                   305             py310h2bbff1b_0    defaults
pyyaml                    6.0             py310h2bbff1b_1    defaults
qt-main                   5.15.2               he8e5bd7_7    defaults
qt-webengine              5.15.9               hb9a9bb5_5    defaults
qtpy                      2.2.0           py310haa95532_0    defaults
qtwebkit                  5.212                h3ad3cdb_4    defaults
requests                  2.28.1          py310haa95532_0    defaults
ruamel.yaml               0.17.21         py310h2bbff1b_0    defaults
ruamel.yaml.clib          0.2.6           py310h2bbff1b_1    defaults
setuptools                65.6.3          py310haa95532_0    defaults
sip                       6.6.2           py310hd77b12b_0    defaults
six                       1.16.0             pyhd3eb1b0_1    defaults
sqlite                    3.40.1               h2bbff1b_0    defaults
tk                        8.6.12               h2bbff1b_0    defaults
toml                      0.10.2             pyhd3eb1b0_0    defaults
toolz                     0.12.0          py310haa95532_0    defaults
tqdm                      4.64.1          py310haa95532_0    defaults
traitlets                 5.7.1           py310haa95532_0    defaults
tzdata                    2022g                h04d1e81_0    defaults
ujson                     5.4.0           py310hd77b12b_0    defaults
urllib3                   1.26.14         py310haa95532_0    defaults
vc                        14.2                 h21ff451_1    defaults
vs2015_runtime            14.27.29016          h5e58377_2    defaults
wheel                     0.37.1             pyhd3eb1b0_0    defaults
win_inet_pton             1.1.0           py310haa95532_0    defaults
wincertstore              0.2             py310haa95532_2    defaults
xz                        5.2.10               h8cc25b3_1    defaults
yaml                      0.2.5                he774522_0    defaults
zlib                      1.2.13               h8cc25b3_0    defaults
zstandard                 0.18.0          py310h2bbff1b_0    defaults
zstd                      1.5.2                h19a0ad4_0    defaults
```

### Additional Context

OS : Windows (you guessed it) 10 on a corporate Active Directory setup

VS Code version : code.cmd --version
1.77.3
704ed70d4fd1c6bd6342c436f1ede30d1cff4710
x64

**Comment by liyafe1997** [comment]
I have the exact same problem. And the above suggested fix works for me.
Seems the anaconda-navigator just call code.exe --version and it doesn't return anything, just let the vscode pop up...

**Comment by liyafe1997** [comment]
Another reason I guess is we are on a non-English version of Windows (for me, it is zh-CN).

If I run code.exe --version, I can see some Non-ASCII strings, maybe this is the problem cause the error "UnicodeDecodeError".

![1](https://github.com/ContinuumIO/anaconda-issues/assets/18359157/72b1766b-e221-4219-853f-624e85851316)

**Comment by liyafe1997** [comment]
I found the root reason of causing this.... Maybe you made the same mistake @manuco 
We should put the ```vscode_dir/bin``` into the PATH, instead of the root dir of vscode.
Because there is an ```code.cmd``` it can return the vscode version correctly...

Now everything works for anaconda navigator, and vscode no longer popup while running the navigator.
![1](https://github.com/ContinuumIO/anaconda-issues/assets/18359157/690fcbcf-d5a3-4c59-a451-a4800ad68342)

**Comment by manuco** [comment]
@liyafe1997 Thanks for your messages. The problem is not that vscode is not found (indeed, it is in the $PATH and is found), but that my home is not a local directory, and that code.cmd doesn't launch at all, and the error message is not in UTF-8.

But you're right on the fact that this is the same error. Whatever the OS error message is (code.exe not found, or anything else), it is written in the language of the locale, not only with ASCII characters, and not in UTF-8.
