### ISSUE TITLE
`pytest-xdist` is missing `py` dependency

### ISSUE THREAD

**Issue by kenodegard** [ContinuumIO/anaconda-issues#13198]
### Checklist

- [X] I added a descriptive title.
- [X] I searched through [existing issues](https://github.com/ContinuumIO/anaconda-issues/issues) and couldn't find a solution or duplicate issue.
- [X] I searched on the web (e.g. Google) and didn't find any helpful information.
- [X] I searched the [Anaconda documentation](https://docs.anaconda.com/) and didn't find any helpful information.

### Impacted product

- [X] A conda package (built by Anaconda)
- [ ] Anaconda Distribution (formerly Anaconda Individual Edition)
- [ ] Miniconda
- [ ] Anaconda.org

### What happened?

`pytest 7.3.1` dropped the `py` dependency however `pytest-xdist` still depends on `py`:

```bash
$ conda create -n scratch -y -q pytest-xdist
$ conda activate scratch
(scratch) $ pytest -n auto $(mktemp)
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/Users/kodegard/.conda/arm64/23.3.1/3.10/envs/scratch/lib/python3.11/site-packages/_pytest/main.py", line 265, in wrap_session
INTERNALERROR>     config._do_configure()
INTERNALERROR>   File "/Users/kodegard/.conda/arm64/23.3.1/3.10/envs/scratch/lib/python3.11/site-packages/_pytest/config/__init__.py", line 1046, in _do_configure
INTERNALERROR>     self.hook.pytest_configure.call_historic(kwargs=dict(config=self))
INTERNALERROR>   File "/Users/kodegard/.conda/arm64/23.3.1/3.10/envs/scratch/lib/python3.11/site-packages/pluggy/_hooks.py", line 277, in call_historic
INTERNALERROR>     res = self._hookexec(self.name, self.get_hookimpls(), kwargs, False)
INTERNALERROR>           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
INTERNALERROR>   File "/Users/kodegard/.conda/arm64/23.3.1/3.10/envs/scratch/lib/python3.11/site-packages/pluggy/_manager.py", line 80, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
INTERNALERROR>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
INTERNALERROR>   File "/Users/kodegard/.conda/arm64/23.3.1/3.10/envs/scratch/lib/python3.11/site-packages/pluggy/_callers.py", line 60, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>            ^^^^^^^^^^^^^^^^^^^^
INTERNALERROR>   File "/Users/kodegard/.conda/arm64/23.3.1/3.10/envs/scratch/lib/python3.11/site-packages/pluggy/_result.py", line 60, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "/Users/kodegard/.conda/arm64/23.3.1/3.10/envs/scratch/lib/python3.11/site-packages/pluggy/_callers.py", line 39, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>           ^^^^^^^^^^^^^^^^^^^^^^^^^
INTERNALERROR>   File "/Users/kodegard/.conda/arm64/23.3.1/3.10/envs/scratch/lib/python3.11/site-packages/xdist/plugin.py", line 192, in pytest_configure
INTERNALERROR>     from xdist.dsession import DSession
INTERNALERROR>   File "/Users/kodegard/.conda/arm64/23.3.1/3.10/envs/scratch/lib/python3.11/site-packages/_pytest/assertion/rewrite.py", line 172, in exec_module
INTERNALERROR>     exec(co, module.__dict__)
INTERNALERROR>   File "/Users/kodegard/.conda/arm64/23.3.1/3.10/envs/scratch/lib/python3.11/site-packages/xdist/dsession.py", line 5, in <module>
INTERNALERROR>     from xdist.scheduler import (
INTERNALERROR>   File "/Users/kodegard/.conda/arm64/23.3.1/3.10/envs/scratch/lib/python3.11/site-packages/_pytest/assertion/rewrite.py", line 172, in exec_module
INTERNALERROR>     exec(co, module.__dict__)
INTERNALERROR>   File "/Users/kodegard/.conda/arm64/23.3.1/3.10/envs/scratch/lib/python3.11/site-packages/xdist/scheduler/__init__.py", line 1, in <module>
INTERNALERROR>     from xdist.scheduler.each import EachScheduling  # noqa
INTERNALERROR>     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
INTERNALERROR>   File "/Users/kodegard/.conda/arm64/23.3.1/3.10/envs/scratch/lib/python3.11/site-packages/_pytest/assertion/rewrite.py", line 172, in exec_module
INTERNALERROR>     exec(co, module.__dict__)
INTERNALERROR>   File "/Users/kodegard/.conda/arm64/23.3.1/3.10/envs/scratch/lib/python3.11/site-packages/xdist/scheduler/each.py", line 1, in <module>
INTERNALERROR>     from py.log import Producer
INTERNALERROR> ModuleNotFoundError: No module named 'py.log'; 'py' is not a package
```

### Expected behavior or outcome

`pytest-xdist` should work

### Conda info

```shell
active environment : scratch
    active env location : /Users/kodegard/.conda/arm64/23.3.1/3.10/envs/scratch
            shell level : 1
       user config file : /Users/kodegard/.condarc
 populated config files : /Users/kodegard/.condarc
          conda version : 23.3.1
    conda-build version : 3.24.0
         python version : 3.10.8.final.0
       virtual packages : __archspec=1=arm64
                          __osx=13.2.1=0
                          __unix=0=0
       base environment : /Users/kodegard/.conda/arm64/23.3.1/3.10  (writable)
      conda av data dir : /Users/kodegard/.conda/arm64/23.3.1/3.10/etc/conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/osx-arm64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/osx-arm64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /Users/kodegard/.conda/arm64/23.3.1/3.10/pkgs
                          /Users/kodegard/.conda/pkgs
       envs directories : /Users/kodegard/.conda/arm64/23.3.1/3.10/envs
                          /Users/kodegard/.conda/envs
               platform : osx-arm64
             user-agent : conda/23.3.1 requests/2.28.1 CPython/3.10.8 Darwin/22.3.0 OSX/13.2.1
                UID:GID : 501:20
             netrc file : None
           offline mode : False
```

### Conda config

```shell
==> /Users/kodegard/.condarc <==
auto_activate_base: False
changeps1: False
```

### Conda list

```shell
# packages in environment at /Users/kodegard/.conda/arm64/23.3.1/3.10/envs/scratch:
#
# Name                    Version                   Build  Channel
attrs                     22.1.0          py311hca03da5_0    defaults
bzip2                     1.0.8                h620ffc9_4    defaults
ca-certificates           2023.01.10           hca03da5_0    defaults
execnet                   1.9.0              pyhd3eb1b0_0    defaults
iniconfig                 1.1.1              pyhd3eb1b0_0    defaults
libffi                    3.4.4                hca03da5_0    defaults
ncurses                   6.4                  h313beb8_0    defaults
openssl                   1.1.1t               h1a28f6b_0    defaults
packaging                 23.0            py311hca03da5_0    defaults
pip                       23.0.1          py311hca03da5_0    defaults
pluggy                    1.0.0           py311hca03da5_1    defaults
pytest                    7.3.1           py311hca03da5_0    defaults
pytest-forked             1.3.0              pyhd3eb1b0_0    defaults
pytest-xdist              2.5.0              pyhd3eb1b0_0    defaults
python                    3.11.3               hc0d8a6c_0    defaults
readline                  8.2                  h1a28f6b_0    defaults
setuptools                66.0.0          py311hca03da5_0    defaults
sqlite                    3.41.2               h80987f9_0    defaults
tk                        8.6.12               hb8d0fd4_0    defaults
tomli                     2.0.1           py311hca03da5_0    defaults
tzdata                    2023c                h04d1e81_0    defaults
wheel                     0.38.4          py311hca03da5_0    defaults
xz                        5.4.2                h80987f9_0    defaults
zlib                      1.2.13               h5a0b063_0    defaults
```

**Comment by schuylermartin45** [comment]
Thanks for the heads-up, we are actively working on a hotfix. It seems likely that many `pytest-*` packages were silently relying on `py` as a dependency and fall into this camp.

**Comment by schuylermartin45** [comment]
Hotfix just got merged, this should resolve this issue and all other plugins that transitively relied on `py`: https://github.com/AnacondaRecipes/repodata-hotfixes/pull/193

**Comment by schuylermartin45** [comment]
Changes have been deployed. Let us know if the issue is resolved so we can close this ticket out.

**Comment by kenodegard** [comment]
yup the hotfix works, thanks!
