### ISSUE TITLE
Initial launch of Navigator fails with unexpected error

### ISSUE THREAD

**Issue by sj527y** [ContinuumIO/anaconda-issues#13212]
### Checklist

- [X] I added a descriptive title
- [X] I searched for other issues and couldn't find a solution or duplication
- [X] I already searched in Google and didn't find any good information or help
- [X] I looked at the [docs](https://docs.anaconda.com/anaconda/navigator/) and didn't see anything to help

### What happened?

Navigator Error
An unexpected error occurred on Navigator start-up

Report
Please report this issue in the anaconda [issue tracker](https://github.com/continuumio/anaconda-issues)

Main Error
HTTPSConnectionPool(host='api.anaconda.org', port=443): Read timed out. (read timeout=None)
Traceback
Traceback (most recent call last):
  File "C:\Users\sj527y\AppData\Local\anaconda3\lib\site-packages\urllib3\connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "C:\Users\sj527y\AppData\Local\anaconda3\lib\site-packages\urllib3\connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "C:\Users\sj527y\AppData\Local\anaconda3\lib\site-packages\urllib3\connection.py", line 414, in connect
    self.sock = ssl_wrap_socket(
  File "C:\Users\sj527y\AppData\Local\anaconda3\lib\site-packages\urllib3\util\ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "C:\Users\sj527y\AppData\Local\anaconda3\lib\site-packages\urllib3\util\ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "C:\Users\sj527y\AppData\Local\anaconda3\lib\ssl.py", line 513, in wrap_socket
    return self.sslsocket_class._create(
  File "C:\Users\sj527y\AppData\Local\anaconda3\lib\ssl.py", line 1071, in _create
    self.do_handshake()
  File "C:\Users\sj527y\AppData\Local\anaconda3\lib\ssl.py", line 1342, in do_handshake
    self._sslobj.do_handshake()
TimeoutError: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\sj527y\AppData\Local\anaconda3\lib\site-packages\requests\adapters.py", line 489, in send
    resp = conn.urlopen(
  File "C:\Users\sj527y\AppData\Local\anaconda3\lib\site-packages\urllib3\connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "C:\Users\sj527y\AppData\Local\anaconda3\lib\site-packages\urllib3\util\retry.py", line 550, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "C:\Users\sj527y\AppData\Local\anaconda3\lib\site-packages\urllib3\packages\six.py", line 770, in reraise
    raise value
  File "C:\Users\sj527y\AppData\Local\anaconda3\lib\site-packages\urllib3\connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "C:\Users\sj527y\AppData\Local\anaconda3\lib\site-packages\urllib3\connectionpool.py", line 389, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=conn.timeout)
  File "C:\Users\sj527y\AppData\Local\anaconda3\lib\site-packages\urllib3\connectionpool.py", line 340, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='api.anaconda.org', port=443): Read timed out. (read timeout=None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\sj527y\AppData\Local\anaconda3\lib\site-packages\anaconda_navigator\exceptions.py", line 74, in exception_handler
    return_value = func(*args, **kwargs)
  File "C:\Users\sj527y\AppData\Local\anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 137, in start_app
    window = run_app(splash)
  File "C:\Users\sj527y\AppData\Local\anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 59, in run_app
    window = MainWindow(splash=splash)
  File "C:\Users\sj527y\AppData\Local\anaconda3\lib\site-packages\anaconda_navigator\widgets\main_window\__init__.py", line 219, in __init__
    self.api = AnacondaAPI()
  File "C:\Users\sj527y\AppData\Local\anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 1085, in AnacondaAPI
    ANACONDA_API = _AnacondaAPI()
  File "C:\Users\sj527y\AppData\Local\anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 70, in __init__
    self._client_api = ClientAPI()
  File "C:\Users\sj527y\AppData\Local\anaconda3\lib\site-packages\anaconda_navigator\api\client_api.py", line 667, in ClientAPI
    CLIENT_API = _ClientAPI()
  File "C:\Users\sj527y\AppData\Local\anaconda3\lib\site-packages\anaconda_navigator\api\client_api.py", line 144, in __init__
    self.reload_client()
  File "C:\Users\sj527y\AppData\Local\anaconda3\lib\site-packages\anaconda_navigator\api\client_api.py", line 344, in reload_client
    client.user()
  File "C:\Users\sj527y\AppData\Local\anaconda3\lib\site-packages\binstar_client\__init__.py", line 246, in user
    res = self.session.get(url, verify=self.session.verify)
  File "C:\Users\sj527y\AppData\Local\anaconda3\lib\site-packages\requests\sessions.py", line 600, in get
    return self.request("GET", url, **kwargs)
  File "C:\Users\sj527y\AppData\Local\anaconda3\lib\site-packages\requests\sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\sj527y\AppData\Local\anaconda3\lib\site-packages\requests\sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\sj527y\AppData\Local\anaconda3\lib\site-packages\requests\adapters.py", line 578, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='api.anaconda.org', port=443): Read timed out. (read timeout=None)

### Conda info

```shell
see above
```

### Conda config

```shell
see above
```

### Conda list

```shell
see above
```

**Comment by GreySwordman** [comment]
I have encountered similar issue too after I tried to install Tensorflow in Anaconda . I am self learning Python as a hobby. 
Can someone help me to use jupitor notebook again , for me to keep learning Python . 
The error code as the following :

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\anaconda_navigator\exceptions.py", line 74, in exception_handler
    return_value = func(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 137, in start_app
    window = run_app(splash)
  File "C:\ProgramData\Anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 60, in run_app
    window = MainWindow(splash=splash)
  File "C:\ProgramData\Anaconda3\lib\site-packages\anaconda_navigator\widgets\main_window\__init__.py", line 228, in __init__
    self.api = AnacondaAPI()
  File "C:\ProgramData\Anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 1116, in AnacondaAPI
    ANACONDA_API = _AnacondaAPI()
  File "C:\ProgramData\Anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 69, in __init__
    self._conda_api = CondaAPI()
  File "C:\ProgramData\Anaconda3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 1824, in CondaAPI
    CONDA_API = _CondaAPI()
  File "C:\ProgramData\Anaconda3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 485, in __init__
    self.set_conda_prefix(info=get_conda_info(allow_fixes=True))
  File "C:\ProgramData\Anaconda3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 638, in set_conda_prefix
    self.ROOT_PREFIX = info.get('root_prefix')  # str
AttributeError: 'list' object has no attribute 'get'
