### ISSUE TITLE
Navigator won't start after updating Pandas

### ISSUE THREAD

**Issue by gncoinc** [ContinuumIO/anaconda-issues#13225]
### Checklist

- [X] I added a descriptive title
- [X] I searched for other issues and couldn't find a solution or duplication
- [X] I already searched in Google and didn't find any good information or help
- [X] I looked at the [docs](https://docs.anaconda.com/anaconda/navigator/) and didn't see anything to help

### What happened?

After updating Pandas due to another issue, Navigator won't start anymore. I have tried force-updating, reinstalling etc., but even after numerous computer restarts, the error persists. This is the full log:

Navigator Error

An unexpected error occurred on Navigator start-up

Report

Please report this issue in the anaconda [issue tracker](https://github.com/ContinuumIO/anaconda-issues/issues) 

Main Error

'list' object has no attribute 'get'

Traceback

Traceback (most recent call last):
  File "C:\Users\sdittmann\AppData\Local\anaconda3\lib\site-packages\anaconda_navigator\exceptions.py", line 109, in exception_handler
    return_value = func(*args, **kwargs)
  File "C:\Users\sdittmann\AppData\Local\anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 137, in start_app
    window = run_app(splash)
  File "C:\Users\sdittmann\AppData\Local\anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 59, in run_app
    window = MainWindow(splash=splash)
  File "C:\Users\sdittmann\AppData\Local\anaconda3\lib\site-packages\anaconda_navigator\widgets\main_window\__init__.py", line 217, in __init__
    self.api = AnacondaAPI()
  File "C:\Users\sdittmann\AppData\Local\anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 1085, in AnacondaAPI
    ANACONDA_API = _AnacondaAPI()
  File "C:\Users\sdittmann\AppData\Local\anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 69, in __init__
    self._conda_api = CondaAPI()
  File "C:\Users\sdittmann\AppData\Local\anaconda3\lib\site-packages\anaconda_navigator\api\conda_api\__init__.py", line 1743, in CondaAPI
    CONDA_API = _CondaAPI()
  File "C:\Users\sdittmann\AppData\Local\anaconda3\lib\site-packages\anaconda_navigator\api\conda_api\__init__.py", line 434, in __init__
    self.set_conda_prefix(info=get_conda_info(allow_fixes=True))
  File "C:\Users\sdittmann\AppData\Local\anaconda3\lib\site-packages\anaconda_navigator\api\conda_api\__init__.py", line 583, in set_conda_prefix
    self.ROOT_PREFIX = info.get('root_prefix')  # str
AttributeError: 'list' object has no attribute 'get'

### Conda info

```shell
active environment : base
    active env location : C:\Users\sdittmann\AppData\Local\anaconda3
            shell level : 1
       user config file : C:\Users\sdittmann\.condarc
 populated config files : C:\Users\sdittmann\.condarc
          conda version : 23.7.0
    conda-build version : 3.26.0
         python version : 3.10.12.final.0
       virtual packages : __archspec=1=x86_64
                          __cuda=12.0=0
                          __win=0=0
       base environment : C:\Users\sdittmann\AppData\Local\anaconda3  (writable)
      conda av data dir : C:\Users\sdittmann\AppData\Local\anaconda3\etc\conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\Users\sdittmann\AppData\Local\anaconda3\pkgs
                          C:\Users\sdittmann\.conda\pkgs
                          C:\Users\sdittmann\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\sdittmann\AppData\Local\anaconda3\envs
                          C:\Users\sdittmann\.conda\envs
                          C:\Users\sdittmann\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/23.7.0 requests/2.29.0 CPython/3.10.12 Windows/10 Windows/10.0.19045
          administrator : False
             netrc file : None
           offline mode : False
```

### Conda config

```shell
==> C:\Users\sdittmann\.condarc <==
default_python: None
channels:
  - defaults

==> envvars <==
allow_softlinks: False
```

### Conda list

```shell
#
# Name                    Version                   Build  Channel
_r-mutex                  1.0.0               anacondar_1    defaults
aiofiles                  22.1.0          py310haa95532_0    defaults
aiosqlite                 0.18.0          py310haa95532_0    defaults
anaconda-client           1.12.0          py310haa95532_0    defaults
anaconda-navigator        2.4.2           py310haa95532_0    defaults
anaconda-project          0.11.1          py310haa95532_0    defaults
anyio                     3.5.0           py310haa95532_0    defaults
appdirs                   1.4.4                    pypi_0    pypi
argon2-cffi               21.3.0             pyhd3eb1b0_0    defaults
argon2-cffi-bindings      21.2.0          py310h2bbff1b_0    defaults
asttokens                 2.0.5              pyhd3eb1b0_0    defaults
attrs                     22.1.0          py310haa95532_0    defaults
babel                     2.11.0          py310haa95532_0    defaults
backcall                  0.2.0              pyhd3eb1b0_0    defaults
backports                 1.1                pyhd3eb1b0_0    defaults
backports.functools_lru_cache 1.6.4              pyhd3eb1b0_0    defaults
backports.tempfile        1.0                pyhd3eb1b0_1    defaults
backports.weakref         1.0.post1                  py_1    defaults
beautifulsoup4            4.12.2          py310haa95532_0    defaults
blas                      1.0                         mkl    defaults
bleach                    4.1.0              pyhd3eb1b0_0    defaults
boltons                   23.0.0          py310haa95532_0    defaults
bottleneck                1.3.5           py310h9128911_0    defaults
brotlipy                  0.7.0           py310h2bbff1b_1002    defaults
bzip2                     1.0.8                he774522_0    defaults
ca-certificates           2023.05.30           haa95532_0    defaults
certifi                   2023.7.22       py310haa95532_0    defaults
cffi                      1.15.1          py310h2bbff1b_3    defaults
chardet                   4.0.0           py310haa95532_1003    defaults
charset-normalizer        2.0.4              pyhd3eb1b0_0    defaults
click                     8.0.4           py310haa95532_0    defaults
clyent                    1.2.2           py310haa95532_1    defaults
colorama                  0.4.6           py310haa95532_0    defaults
comm                      0.1.2           py310haa95532_0    defaults
conda                     23.7.0          py310haa95532_0    defaults
conda-build               3.26.0          py310haa95532_0    defaults
conda-content-trust       0.1.3           py310haa95532_0    defaults
conda-index               0.2.3           py310haa95532_0    defaults
conda-pack                0.6.0              pyhd3eb1b0_0    defaults
conda-package-handling    2.1.0           py310haa95532_0    defaults
conda-package-streaming   0.8.0           py310haa95532_0    defaults
conda-repo-cli            1.0.41          py310haa95532_0    defaults
conda-token               0.4.0              pyhd3eb1b0_0    defaults
conda-verify              3.4.2                      py_1    defaults
console_shortcut          0.1.1                         4    defaults
cryptography              39.0.1          py310h21b164f_0    defaults
debugpy                   1.5.1           py310hd77b12b_0    defaults
decorator                 5.1.1              pyhd3eb1b0_0    defaults
defusedxml                0.7.1              pyhd3eb1b0_0    defaults
diff-cover                7.7.0                    pypi_0    pypi
entrypoints               0.4             py310haa95532_0    defaults
exceptiongroup            1.1.2                    pypi_0    pypi
executing                 0.8.3              pyhd3eb1b0_0    defaults
filelock                  3.9.0           py310haa95532_0    defaults
freetype                  2.12.1               ha860e81_0    defaults
future                    0.18.3          py310haa95532_0    defaults
giflib                    5.2.1                h8cc25b3_3    defaults
glib                      2.69.1               h5dc1a3c_2    defaults
glob2                     0.7                pyhd3eb1b0_0    defaults
gst-plugins-base          1.18.5               h9e645db_0    defaults
gstreamer                 1.18.5               hd78058f_0    defaults
icu                       58.2                 ha925a31_3    defaults
idna                      3.4             py310haa95532_0    defaults
iniconfig                 2.0.0                    pypi_0    pypi
intel-openmp              2023.1.0         h59b6b97_46319    defaults
ipykernel                 6.19.2          py310h9909e9c_0    defaults
ipython                   8.12.0          py310haa95532_0    defaults
ipython_genutils          0.2.0              pyhd3eb1b0_1    defaults
isodate                   0.6.1                    pypi_0    pypi
jedi                      0.18.1          py310haa95532_1    defaults
jinja2                    3.1.2           py310haa95532_0    defaults
jpeg                      9e                   h2bbff1b_1    defaults
json5                     0.9.6              pyhd3eb1b0_0    defaults
jsonpatch                 1.32               pyhd3eb1b0_0    defaults
jsonpointer               2.1                pyhd3eb1b0_0    defaults
jsonschema                4.17.3          py310haa95532_0    defaults
jupyter_client            8.1.0           py310haa95532_0    defaults
jupyter_core              5.3.0           py310haa95532_0    defaults
jupyter_events            0.6.3           py310haa95532_0    defaults
jupyter_server            2.5.0           py310haa95532_0    defaults
jupyter_server_fileid     0.9.0           py310haa95532_0    defaults
jupyter_server_terminals  0.4.4           py310haa95532_1    defaults
jupyter_server_ydoc       0.8.0           py310haa95532_1    defaults
jupyter_ydoc              0.2.4           py310haa95532_0    defaults
jupyterlab                3.6.3           py310haa95532_0    defaults
jupyterlab_pygments       0.1.2                      py_0    defaults
jupyterlab_server         2.22.0          py310haa95532_0    defaults
krb5                      1.19.4               h5b6d351_0    defaults
lerc                      3.0                  hd77b12b_0    defaults
libarchive                3.6.2                h2033e3e_1    defaults
libclang                  14.0.6          default_hb5a9fac_1    defaults
libclang13                14.0.6          default_h8e68704_1    defaults
libdeflate                1.17                 h2bbff1b_0    defaults
libffi                    3.4.4                hd77b12b_0    defaults
libiconv                  1.16                 h2bbff1b_2    defaults
liblief                   0.12.3               hd77b12b_0    defaults
libogg                    1.3.5                h2bbff1b_1    defaults
libpng                    1.6.39               h8cc25b3_0    defaults
libsodium                 1.0.18               h62dcd97_0    defaults
libtiff                   4.5.0                h6c2663c_2    defaults
libvorbis                 1.3.7                he774522_0    defaults
libwebp                   1.2.4                hbc33d0d_1    defaults
libwebp-base              1.2.4                h2bbff1b_1    defaults
libxml2                   2.10.3               h0ad7f3c_0    defaults
libxslt                   1.1.37               h2bbff1b_0    defaults
lxml                      4.9.2           py310h2bbff1b_0    defaults
lz4-c                     1.9.4                h2bbff1b_0    defaults
m2-msys2-runtime          2.5.0.17080.65c939c               3    defaults
m2-patch                  2.7.5                         2    defaults
m2w64-bwidget             1.9.10                        2    defaults
m2w64-bzip2               1.0.6                         6    defaults
m2w64-expat               2.1.1                         2    defaults
m2w64-fftw                3.3.4                         6    defaults
m2w64-flac                1.3.1                         3    defaults
m2w64-gcc-libgfortran     5.3.0                         6    defaults
m2w64-gcc-libs            5.3.0                         7    defaults
m2w64-gcc-libs-core       5.3.0                         7    defaults
m2w64-gettext             0.19.7                        2    defaults
m2w64-gmp                 6.1.0                         2    defaults
m2w64-gsl                 2.1                           2    defaults
m2w64-libiconv            1.14                          6    defaults
m2w64-libjpeg-turbo       1.4.2                         3    defaults
m2w64-libogg              1.3.2                         3    defaults
m2w64-libpng              1.6.21                        2    defaults
m2w64-libsndfile          1.0.26                        2    defaults
m2w64-libsodium           1.0.10                        2    defaults
m2w64-libtiff             4.0.6                         2    defaults
m2w64-libvorbis           1.3.5                         2    defaults
m2w64-libwinpthread-git   5.0.0.4634.697f757               2    defaults
m2w64-libxml2             2.9.3                         4    defaults
m2w64-mpfr                3.1.4                         4    defaults
m2w64-openblas            0.2.19                        1    defaults
m2w64-pcre                8.38                          2    defaults
m2w64-speex               1.2rc2                        3    defaults
m2w64-speexdsp            1.2rc3                        3    defaults
m2w64-tcl                 8.6.5                         3    defaults
m2w64-tk                  8.6.5                         3    defaults
m2w64-tktable             2.10                          5    defaults
m2w64-wineditline         2.101                         5    defaults
m2w64-xz                  5.2.2                         2    defaults
m2w64-zeromq              4.1.4                         2    defaults
m2w64-zlib                1.2.8                        10    defaults
markupsafe                2.1.1           py310h2bbff1b_0    defaults
matplotlib-inline         0.1.6           py310haa95532_0    defaults
menuinst                  1.4.19          py310h59b6b97_0    defaults
mistune                   0.8.4           py310h2bbff1b_1000    defaults
mkl                       2023.1.0         h8bd8f75_46356    defaults
mkl-service               2.4.0           py310h2bbff1b_1    defaults
mkl_fft                   1.3.6           py310h4ed8f06_1    defaults
mkl_random                1.2.2           py310h4ed8f06_1    defaults
more-itertools            8.12.0             pyhd3eb1b0_0    defaults
mouseinfo                 0.1.3                    pypi_0    pypi
msys2-conda-epoch         20160418                      1    defaults
navigator-updater         0.4.0           py310haa95532_0    defaults
nbclassic                 0.5.5           py310haa95532_0    defaults
nbclient                  0.5.13          py310haa95532_0    defaults
nbconvert                 6.5.4           py310haa95532_0    defaults
nbformat                  5.7.0           py310haa95532_0    defaults
nest-asyncio              1.5.6           py310haa95532_0    defaults
notebook                  6.5.4           py310haa95532_0    defaults
notebook-shim             0.2.2           py310haa95532_0    defaults
numexpr                   2.8.4           py310h2cd9be0_1    defaults
numpy                     1.25.0          py310h055cbcc_0    defaults
numpy-base                1.25.0          py310h65a83cf_0    defaults
openssl                   1.1.1u               h2bbff1b_0    defaults
packaging                 23.0            py310haa95532_0    defaults
pandas                    2.0.0                    pypi_0    pypi
pandocfilters             1.5.0              pyhd3eb1b0_0    defaults
parso                     0.8.3              pyhd3eb1b0_0    defaults
pathlib                   1.0.1              pyhd3eb1b0_1    defaults
pathspec                  0.11.1                   pypi_0    pypi
pcre                      8.45                 hd77b12b_0    defaults
pickleshare               0.7.5           pyhd3eb1b0_1003    defaults
pillow                    9.4.0           py310hd77b12b_0    defaults
pip                       23.2.1          py310haa95532_0    defaults
pkginfo                   1.9.6           py310haa95532_0    defaults
platformdirs              2.5.2           py310haa95532_0    defaults
pluggy                    1.0.0           py310haa95532_1    defaults
ply                       3.11            py310haa95532_0    defaults
polars                    0.17.11                  pypi_0    pypi
powershell_shortcut       0.0.1                         3    defaults
prometheus_client         0.14.1          py310haa95532_0    defaults
prompt-toolkit            3.0.36          py310haa95532_0    defaults
psutil                    5.9.0           py310h2bbff1b_0    defaults
pure_eval                 0.2.2              pyhd3eb1b0_0    defaults
py-lief                   0.12.3          py310hd77b12b_0    defaults
pyautogui                 0.9.53                   pypi_0    pypi
pycosat                   0.6.4           py310h2bbff1b_0    defaults
pycparser                 2.21               pyhd3eb1b0_0    defaults
pygetwindow               0.0.9                    pypi_0    pypi
pygments                  2.15.1          py310haa95532_1    defaults
pyjwt                     2.4.0           py310haa95532_0    defaults
pymsgbox                  1.0.9                    pypi_0    pypi
pyopenssl                 23.2.0          py310haa95532_0    defaults
pyperclip                 1.8.2                    pypi_0    pypi
pyqt                      5.15.7          py310hd77b12b_0    defaults
pyqt5-sip                 12.11.0         py310hd77b12b_0    defaults
pyrect                    0.2.0                    pypi_0    pypi
pyrsistent                0.18.0          py310h2bbff1b_0    defaults
pyscreeze                 0.1.28                   pypi_0    pypi
pysocks                   1.7.1           py310haa95532_0    defaults
pytest                    7.4.0                    pypi_0    pypi
python                    3.10.12              h966fe2a_0    defaults
python-dateutil           2.8.2              pyhd3eb1b0_0    defaults
python-fastjsonschema     2.16.2          py310haa95532_0    defaults
python-json-logger        2.0.7           py310haa95532_0    defaults
python-libarchive-c       2.9                pyhd3eb1b0_1    defaults
pytweening                1.0.7                    pypi_0    pypi
pytz                      2022.7          py310haa95532_0    defaults
pywin32                   305             py310h2bbff1b_0    defaults
pywinpty                  2.0.10          py310h5da7b33_0    defaults
pyyaml                    6.0             py310h2bbff1b_1    defaults
pyzmq                     25.1.0          py310hd77b12b_0    defaults
qt-main                   5.15.2               he8e5bd7_8    defaults
qt-webengine              5.15.9               hb9a9bb5_5    defaults
qtpy                      2.2.0           py310haa95532_0    defaults
qtwebkit                  5.212                h2bbfb41_5    defaults
r-base                    3.6.1                hf18239d_1    r
r-base64enc               0.1_3             r36h6115d3f_4    r
r-crayon                  1.3.4             r36h6115d3f_0    r
r-digest                  0.6.18            r36h6115d3f_0    r
r-evaluate                0.13              r36h6115d3f_0    r
r-htmltools               0.3.6             r36h6115d3f_0    r
r-irdisplay               0.7.0             r36h6115d3f_0    r
r-irkernel                0.8.15                    r36_0    r
r-jsonlite                1.6               r36h6115d3f_0    r
r-pbdzmq                  0.3_3             r36h6115d3f_0    r
r-rcpp                    1.0.1             r36h6115d3f_0    r
r-repr                    0.19.2            r36h6115d3f_0    r
r-uuid                    0.1_2             r36h6115d3f_4    r
regex                     2023.6.3                 pypi_0    pypi
requests                  2.29.0          py310haa95532_0    defaults
requests-file             1.5.1              pyhd3eb1b0_0    defaults
requests-toolbelt         0.9.1              pyhd3eb1b0_0    defaults
rfc3339-validator         0.1.4           py310haa95532_0    defaults
rfc3986-validator         0.1.1           py310haa95532_0    defaults
ruamel.yaml               0.17.21         py310h2bbff1b_0    defaults
ruamel.yaml.clib          0.2.6           py310h2bbff1b_1    defaults
ruamel_yaml               0.17.21         py310h2bbff1b_0    defaults
send2trash                1.8.0              pyhd3eb1b0_1    defaults
setuptools                68.0.0          py310haa95532_0    defaults
simple-salesforce         1.12.3                   pypi_0    pypi
sip                       6.6.2           py310hd77b12b_0    defaults
six                       1.16.0             pyhd3eb1b0_1    defaults
sniffio                   1.2.0           py310haa95532_1    defaults
soupsieve                 2.4             py310haa95532_0    defaults
sqlfluff                  2.1.3                    pypi_0    pypi
sqlite                    3.41.2               h2bbff1b_0    defaults
stack_data                0.2.0              pyhd3eb1b0_0    defaults
tbb                       2021.8.0             h59b6b97_0    defaults
tblib                     2.0.0                    pypi_0    pypi
terminado                 0.17.1          py310haa95532_0    defaults
tinycss2                  1.2.1           py310haa95532_0    defaults
tk                        8.6.12               h2bbff1b_0    defaults
toml                      0.10.2             pyhd3eb1b0_0    defaults
tomli                     2.0.1           py310haa95532_0    defaults
toolz                     0.12.0          py310haa95532_0    defaults
tornado                   6.2             py310h2bbff1b_0    defaults
tqdm                      4.65.0          py310h9909e9c_0    defaults
traitlets                 5.7.1           py310haa95532_0    defaults
typing-extensions         4.7.1           py310haa95532_0    defaults
typing_extensions         4.7.1           py310haa95532_0    defaults
tzdata                    2023.3                   pypi_0    pypi
ujson                     5.4.0           py310hd77b12b_0    defaults
urllib3                   1.26.16         py310haa95532_0    defaults
vc                        14.2                 h21ff451_1    defaults
vs2015_runtime            14.27.29016          h5e58377_2    defaults
wcwidth                   0.2.5              pyhd3eb1b0_0    defaults
webencodings              0.5.1           py310haa95532_1    defaults
websocket-client          0.58.0          py310haa95532_4    defaults
wheel                     0.38.4          py310haa95532_0    defaults
win_inet_pton             1.1.0           py310haa95532_0    defaults
winpty                    0.4.3                         4    defaults
xz                        5.4.2                h8cc25b3_0    defaults
y-py                      0.5.9           py310hb6bf4ef_0    defaults
yaml                      0.2.5                he774522_0    defaults
ypy-websocket             0.8.2           py310haa95532_0    defaults
zeep                      4.2.1                    pypi_0    pypi
zeromq                    4.3.4                hd77b12b_0    defaults
zlib                      1.2.13               h8cc25b3_0    defaults
zstandard                 0.19.0          py310h2bbff1b_0    defaults
zstd                      1.5.5                hd43e919_0    defaults
```

### Additional Context

I had to reinstall Pandas because it would no longer recognize common commands. After that, the error started.

**Comment by varlackc** [comment]
It seems that you are using the Conda version `23.7.0` and anaconda-navigator version `2.4.2`

  I am curious if you have tried an older more stable version of Conda and Navigator, it might be worth a try to check to see if using an older more stable version might solve the issue. 

  It might be worth a try to look at version `23.5.0` or earlier, and using also an older more stable version of Navigator.
