### ISSUE TITLE
An unexpected error occurred on Navigator start-up

### ISSUE THREAD

**Issue by spancavil** [ContinuumIO/anaconda-issues#13228]
### Checklist

- [X] I added a descriptive title.
- [X] I searched through [existing issues](https://github.com/ContinuumIO/anaconda-issues/issues) and couldn't find a solution or duplicate issue.
- [X] I searched on the web (e.g. Google) and didn't find any helpful information.
- [X] I searched the [Anaconda documentation](https://docs.anaconda.com/) and didn't find any helpful information.

### Impacted product

- [ ] A conda package (built by Anaconda)
- [ ] Anaconda Distribution (formerly Anaconda Individual Edition)
- [ ] Miniconda
- [X] Anaconda.org

### What happened?

Navigator Error

An unexpected error occurred on Navigator start-up
Report

Please report this issue in the anaconda [issue tracker](https://github.com/ContinuumIO/anaconda-issues/issues)
Main Error

'list' object has no attribute 'get'

Traceback

Traceback (most recent call last):
  File "/home/spancavil/anaconda3/lib/python3.9/site-packages/anaconda_navigator/exceptions.py", line 109, in exception_handler
    return_value = func(*args, **kwargs)
  File "/home/spancavil/anaconda3/lib/python3.9/site-packages/anaconda_navigator/app/start.py", line 137, in start_app
    window = run_app(splash)
  File "/home/spancavil/anaconda3/lib/python3.9/site-packages/anaconda_navigator/app/start.py", line 59, in run_app
    window = MainWindow(splash=splash)
  File "/home/spancavil/anaconda3/lib/python3.9/site-packages/anaconda_navigator/widgets/main_window/__init__.py", line 217, in __init__
    self.api = AnacondaAPI()
  File "/home/spancavil/anaconda3/lib/python3.9/site-packages/anaconda_navigator/api/anaconda_api.py", line 1085, in AnacondaAPI
    ANACONDA_API = _AnacondaAPI()
  File "/home/spancavil/anaconda3/lib/python3.9/site-packages/anaconda_navigator/api/anaconda_api.py", line 69, in __init__
    self._conda_api = CondaAPI()
  File "/home/spancavil/anaconda3/lib/python3.9/site-packages/anaconda_navigator/api/conda_api/__init__.py", line 1743, in CondaAPI
    CONDA_API = _CondaAPI()
  File "/home/spancavil/anaconda3/lib/python3.9/site-packages/anaconda_navigator/api/conda_api/__init__.py", line 434, in __init__
    self.set_conda_prefix(info=get_conda_info(allow_fixes=True))
  File "/home/spancavil/anaconda3/lib/python3.9/site-packages/anaconda_navigator/api/conda_api/__init__.py", line 583, in set_conda_prefix
    self.ROOT_PREFIX = info.get('root_prefix')  # str
AttributeError: 'list' object has no attribute 'get'

### Expected behavior or outcome

Anaconda dont open on Ubuntu.

**Comment by varlackc** [comment]
It might be worth a try to update the navigator using the debug option, it might be worth it to give this a try. 

  ```
  conda update anaconda-navigator
  anaconda-navigator --debug
  ```
