### ISSUE TITLE
email verification failed error 403

### ISSUE THREAD

**Issue by fjviloria** [ContinuumIO/anaconda-issues#13238]
### Checklist

- [X] I added a descriptive title
- [X] I searched for other issues and couldn't find a solution or duplication
- [X] I already searched in Google and didn't find any good information or help
- [X] I looked at the [docs](https://docs.anaconda.com/anaconda/navigator/) and didn't see anything to help

### What happened?

it does not start
![anaconda error](https://github.com/ContinuumIO/anaconda-issues/assets/57884890/cb74f98c-159e-439b-8110-1a6b4e36564c)

### Conda info

```shell
no output
```

### Conda config

```shell
no output
```

### Conda list

```shell
no output
```

### Additional Context

it does not response to commands

**Comment by treymaddaleno** [comment]
Hi fjviloria - I'm having a fairly similar issue.
I'm going to add in my screenshot here as corroboration / additional context for anybody encountering this.
<img width="488" alt="anacondanavigator_error403_email" src="https://github.com/ContinuumIO/anaconda-issues/assets/29264914/d162f512-5469-4da7-af59-6ae06c0a891f">

**Comment by PyGuy2000** [comment]
I have the same issue:

**Navigator Error**
An unexpected error occurred on Navigator start-up

**Report**
Please report this issue in the anaconda [issue tracker](https://github.com/continuumio/anaconda-issues)

**Main Error**
('Email verification failed!', 403)
Traceback
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\anaconda_navigator\exceptions.py", line 72, in exception_handler
    return_value = func(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 146, in start_app
    window = run_app(splash)
  File "C:\ProgramData\Anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 65, in run_app
    window = MainWindow(splash=splash)
  File "C:\ProgramData\Anaconda3\lib\site-packages\anaconda_navigator\widgets\main_window.py", line 165, in __init__
    self.api = AnacondaAPI()
  File "C:\ProgramData\Anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 1518, in AnacondaAPI
    ANACONDA_API = _AnacondaAPI()
  File "C:\ProgramData\Anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 83, in __init__
    self._client_api = ClientAPI(config=self.config)
  File "C:\ProgramData\Anaconda3\lib\site-packages\anaconda_navigator\api\client_api.py", line 659, in ClientAPI
    CLIENT_API = _ClientAPI(config=config)
  File "C:\ProgramData\Anaconda3\lib\site-packages\anaconda_navigator\api\client_api.py", line 95, in __init__
    self.reload_client()
  File "C:\ProgramData\Anaconda3\lib\site-packages\anaconda_navigator\api\client_api.py", line 326, in reload_client
    client.user()
  File "C:\ProgramData\Anaconda3\lib\site-packages\binstar_client\__init__.py", line 245, in user
    self._check_response(res)
  File "C:\ProgramData\Anaconda3\lib\site-packages\binstar_client\__init__.py", line 230, in _check_response
    raise ErrCls(msg, res.status_code)
binstar_client.errors.BinstarError: ('Email verification failed!', 403)

**Comment by Gotobuild** [comment]
I have the same issue when start up anaconda navigator

![image](https://github.com/ContinuumIO/anaconda-issues/assets/115911246/59f6eef1-743b-496f-8c39-68c42df01f4a)

**Comment by softRustle** [comment]
Same issue on Navigator start-up.

**Main Error**
('Email verification failed!', 403)

**Traceback**
Traceback (most recent call last):
  File "D:\Progs\Anaconda\lib\site-packages\anaconda_navigator\exceptions.py", line 74, in exception_handler
    return_value = func(*args, **kwargs)
  File "D:\Progs\Anaconda\lib\site-packages\anaconda_navigator\app\start.py", line 137, in start_app
    window = run_app(splash)
  File "D:\Progs\Anaconda\lib\site-packages\anaconda_navigator\app\start.py", line 59, in run_app
    window = MainWindow(splash=splash)
  File "D:\Progs\Anaconda\lib\site-packages\anaconda_navigator\widgets\main_window\__init__.py", line 221, in __init__
    self.api = AnacondaAPI()
  File "D:\Progs\Anaconda\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 1176, in AnacondaAPI
    ANACONDA_API = _AnacondaAPI()
  File "D:\Progs\Anaconda\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 71, in __init__
    self._client_api = ClientAPI(config=self.config)
  File "D:\Progs\Anaconda\lib\site-packages\anaconda_navigator\api\client_api.py", line 683, in ClientAPI
    CLIENT_API = _ClientAPI(config=config)
  File "D:\Progs\Anaconda\lib\site-packages\anaconda_navigator\api\client_api.py", line 145, in __init__
    self.reload_client()
  File "D:\Progs\Anaconda\lib\site-packages\anaconda_navigator\api\client_api.py", line 360, in reload_client
    client.user()
  File "D:\Progs\Anaconda\lib\site-packages\binstar_client\__init__.py", line 242, in user
    self._check_response(res)
  File "D:\Progs\Anaconda\lib\site-packages\binstar_client\__init__.py", line 227, in _check_response
    raise ErrCls(msg, res.status_code)
binstar_client.errors.BinstarError: ('Email verification failed!', 403)

**Comment by Wlntr** [comment]
I'm having the same issue. I was able to still use Anaconda for my purposes by going through the command prompt.

**Comment by nithinelias** [comment]
Same issue here , wats going on with anaconda ?

**Comment by naureen-nura** [comment]
Wow, I thought it was only me, but I am facing the same issue as well. Reinstalled Anaconda but no luck.

**Comment by varlackc** [comment]
It might be a good idea to update navigator in debugging mode, it might be worth it to try the following command:

   ```
   conda update anaconda-navigator
   anaconda-navigator --debug
   ```

**Comment by nithinelias** [comment]
I get the same error with debug flag on 

```
(base) C:\Users\Nithin-Elias>anaconda-navigator --debug
2023-08-04 10:55:51,706 - DEBUG __init__.setup_logger:32
Setting up logger

2023-08-04 10:55:55,407 - CRITICAL exceptions.handle_exception:122
('Email verification failed!', 403)
Traceback (most recent call last):
  File "D:\anaconda3\Lib\site-packages\anaconda_navigator\exceptions.py", line 109, in exception_handler
    return_value = func(*args, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^
  File "D:\anaconda3\Lib\site-packages\anaconda_navigator\app\start.py", line 137, in start_app
    window = run_app(splash)
             ^^^^^^^^^^^^^^^
  File "D:\anaconda3\Lib\site-packages\anaconda_navigator\app\start.py", line 59, in run_app
    window = MainWindow(splash=splash)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\anaconda3\Lib\site-packages\anaconda_navigator\widgets\main_window\__init__.py", line 217, in __init__
    self.api = AnacondaAPI()
               ^^^^^^^^^^^^^
  File "D:\anaconda3\Lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 1085, in AnacondaAPI
    ANACONDA_API = _AnacondaAPI()
                   ^^^^^^^^^^^^^^
  File "D:\anaconda3\Lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 70, in __init__
    self._client_api = ClientAPI()
                       ^^^^^^^^^^^
  File "D:\anaconda3\Lib\site-packages\anaconda_navigator\api\client_api.py", line 667, in ClientAPI
    CLIENT_API = _ClientAPI()
                 ^^^^^^^^^^^^
  File "D:\anaconda3\Lib\site-packages\anaconda_navigator\api\client_api.py", line 144, in __init__
    self.reload_client()
  File "D:\anaconda3\Lib\site-packages\anaconda_navigator\api\client_api.py", line 344, in reload_client
    client.user()
  File "D:\anaconda3\Lib\site-packages\binstar_client\__init__.py", line 247, in user
    self._check_response(res)
  File "D:\anaconda3\Lib\site-packages\binstar_client\__init__.py", line 232, in _check_response
    raise ErrCls(msg, res.status_code)
binstar_client.errors.BinstarError: ('Email verification failed!', 403)
2023-08-04 10:55:55,936 - ERROR exceptions.handle_exception:133
('Email verification failed!', 403)
Traceback (most recent call last):
  File "D:\anaconda3\Lib\site-packages\anaconda_navigator\exceptions.py", line 109, in exception_handler
    return_value = func(*args, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^
  File "D:\anaconda3\Lib\site-packages\anaconda_navigator\app\start.py", line 137, in start_app
    window = run_app(splash)
             ^^^^^^^^^^^^^^^
  File "D:\anaconda3\Lib\site-packages\anaconda_navigator\app\start.py", line 59, in run_app
    window = MainWindow(splash=splash)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\anaconda3\Lib\site-packages\anaconda_navigator\widgets\main_window\__init__.py", line 217, in __init__
    self.api = AnacondaAPI()
               ^^^^^^^^^^^^^
  File "D:\anaconda3\Lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 1085, in AnacondaAPI
    ANACONDA_API = _AnacondaAPI()
                   ^^^^^^^^^^^^^^
  File "D:\anaconda3\Lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 70, in __init__
    self._client_api = ClientAPI()
                       ^^^^^^^^^^^
  File "D:\anaconda3\Lib\site-packages\anaconda_navigator\api\client_api.py", line 667, in ClientAPI
    CLIENT_API = _ClientAPI()
                 ^^^^^^^^^^^^
  File "D:\anaconda3\Lib\site-packages\anaconda_navigator\api\client_api.py", line 144, in __init__
    self.reload_client()
  File "D:\anaconda3\Lib\site-packages\anaconda_navigator\api\client_api.py", line 344, in reload_client
    client.user()
  File "D:\anaconda3\Lib\site-packages\binstar_client\__init__.py", line 247, in user
    self._check_response(res)
  File "D:\anaconda3\Lib\site-packages\binstar_client\__init__.py", line 232, in _check_response
    raise ErrCls(msg, res.status_code)
binstar_client.errors.BinstarError: ('Email verification failed!', 403)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\anaconda3\Lib\site-packages\anaconda_navigator\exceptions.py", line 131, in handle_exception
    display_qt_error_box(message)
  File "D:\anaconda3\Lib\site-packages\anaconda_navigator\exceptions.py", line 63, in display_qt_error_box
    msg_box = MessageBoxError(
              ^^^^^^^^^^^^^^^^
  File "D:\anaconda3\Lib\site-packages\anaconda_navigator\widgets\dialogs\__init__.py", line 531, in __init__
    super().__init__(
  File "D:\anaconda3\Lib\site-packages\anaconda_navigator\widgets\dialogs\__init__.py", line 339, in __init__
    self.tracker = GATracker() if analytics else None
                   ^^^^^^^^^^^
  File "D:\anaconda3\Lib\site-packages\anaconda_navigator\utils\analytics.py", line 253, in GATracker
    GA_TRACKER = _GATracker()
                 ^^^^^^^^^^^^
  File "D:\anaconda3\Lib\site-packages\anaconda_navigator\utils\analytics.py", line 89, in __init__
    self.api = AnacondaAPI()
               ^^^^^^^^^^^^^
  File "D:\anaconda3\Lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 1085, in AnacondaAPI
    ANACONDA_API = _AnacondaAPI()
                   ^^^^^^^^^^^^^^
  File "D:\anaconda3\Lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 70, in __init__
    self._client_api = ClientAPI()
                       ^^^^^^^^^^^
  File "D:\anaconda3\Lib\site-packages\anaconda_navigator\api\client_api.py", line 667, in ClientAPI
    CLIENT_API = _ClientAPI()
                 ^^^^^^^^^^^^
  File "D:\anaconda3\Lib\site-packages\anaconda_navigator\api\client_api.py", line 144, in __init__
    self.reload_client()
  File "D:\anaconda3\Lib\site-packages\anaconda_navigator\api\client_api.py", line 344, in reload_client
    client.user()
  File "D:\anaconda3\Lib\site-packages\binstar_client\__init__.py", line 247, in user
    self._check_response(res)
  File "D:\anaconda3\Lib\site-packages\binstar_client\__init__.py", line 232, in _check_response
    raise ErrCls(msg, res.status_code)
binstar_client.errors.BinstarError: ('Email verification failed!', 403)

(base) C:\Users\N
```

**Comment by fjviloria** [comment]
I resolved the issue by verifying my email and password with my anaconda account.Then I uninstalled and reinstalled anaconda navigator and works fine Hope this will help Franklin Viloria Sent from my iPhoneOn Aug 4, 2023, at 00:30, Maxwell Varlack ***@***.***> wrote:﻿
 It might be a good idea to update navigator in debugging mode, it might be worth it to try the following command:

conda update anaconda-navigator
anaconda-navigator --debug

**Comment by erdo100** [comment]
> 

Tried as you said but no difference

**Comment by hchien** [comment]
I have the same issue:

Main Error
('Email verification failed!', 403)
Traceback
Traceback (most recent call last):
  File "/Users/hchien/anaconda3/lib/python3.11/site-packages/anaconda_navigator/exceptions.py", line 109, in exception_handler
    return_value = func(*args, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hchien/anaconda3/lib/python3.11/site-packages/anaconda_navigator/app/start.py", line 137, in start_app
    window = run_app(splash)
             ^^^^^^^^^^^^^^^
  File "/Users/hchien/anaconda3/lib/python3.11/site-packages/anaconda_navigator/app/start.py", line 59, in run_app
    window = MainWindow(splash=splash)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hchien/anaconda3/lib/python3.11/site-packages/anaconda_navigator/widgets/main_window/__init__.py", line 217, in __init__
    self.api = AnacondaAPI()
               ^^^^^^^^^^^^^
  File "/Users/hchien/anaconda3/lib/python3.11/site-packages/anaconda_navigator/api/anaconda_api.py", line 1085, in AnacondaAPI
    ANACONDA_API = _AnacondaAPI()
                   ^^^^^^^^^^^^^^
  File "/Users/hchien/anaconda3/lib/python3.11/site-packages/anaconda_navigator/api/anaconda_api.py", line 70, in __init__
    self._client_api = ClientAPI()
                       ^^^^^^^^^^^
  File "/Users/hchien/anaconda3/lib/python3.11/site-packages/anaconda_navigator/api/client_api.py", line 667, in ClientAPI
    CLIENT_API = _ClientAPI()
                 ^^^^^^^^^^^^
  File "/Users/hchien/anaconda3/lib/python3.11/site-packages/anaconda_navigator/api/client_api.py", line 144, in __init__
    self.reload_client()
  File "/Users/hchien/anaconda3/lib/python3.11/site-packages/anaconda_navigator/api/client_api.py", line 344, in reload_client
    client.user()
  File "/Users/hchien/anaconda3/lib/python3.11/site-packages/binstar_client/__init__.py", line 247, in user
    self._check_response(res)
  File "/Users/hchien/anaconda3/lib/python3.11/site-packages/binstar_client/__init__.py", line 232, in _check_response
    raise ErrCls(msg, res.status_code)
binstar_client.errors.BinstarError: ('Email verification failed!', 403)

**Comment by nithinelias** [comment]
I think it's a windows permission issue . I run anaconda from secondary non
admin account where I get this issue

But from the primary account I don't see this . Don't know what triggered
this all of a sudden . I ve been using this from secondary account all
these days

**Comment by magnatitude80** [comment]
I have completely reinstalled Anaconda Navigator just to get back to this same error again.  Since I started using Python several months ago (I have been coding for over 20 years) I have spent more time troubleshooting Anaconda than using it successfully and I'm about to give up on it altogether.  I have to install packages in the environment and whenever something like this comes up I have to do it all over again.  Is the paid support any better than this?

**Comment by harkxn** [comment]
> 
I have the same issue on my Mac. 
![Screenshot 2023-08-08 at 12 02 09 AM](https://github.com/ContinuumIO/anaconda-issues/assets/140350137/b3b50c61-f40c-40a7-bfca-99d5cf6df208)

**Comment by hipvlady** [comment]
Same:

Navigator Error
An unexpected error occurred on Navigator start-up

Report
Please report this issue in the anaconda [issue tracker](https://github.com/ContinuumIO/anaconda-issues/issues)

Main Error
('Email verification failed!', 403)
Traceback
Traceback (most recent call last):
  File "/usr/local/anaconda3/lib/python3.11/site-packages/anaconda_navigator/exceptions.py", line 109, in exception_handler
    return_value = func(*args, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/anaconda3/lib/python3.11/site-packages/anaconda_navigator/app/start.py", line 137, in start_app
    window = run_app(splash)
             ^^^^^^^^^^^^^^^
  File "/usr/local/anaconda3/lib/python3.11/site-packages/anaconda_navigator/app/start.py", line 59, in run_app
    window = MainWindow(splash=splash)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/anaconda3/lib/python3.11/site-packages/anaconda_navigator/widgets/main_window/__init__.py", line 217, in __init__
    self.api = AnacondaAPI()
               ^^^^^^^^^^^^^
  File "/usr/local/anaconda3/lib/python3.11/site-packages/anaconda_navigator/api/anaconda_api.py", line 1085, in AnacondaAPI
    ANACONDA_API = _AnacondaAPI()
                   ^^^^^^^^^^^^^^
  File "/usr/local/anaconda3/lib/python3.11/site-packages/anaconda_navigator/api/anaconda_api.py", line 70, in __init__
    self._client_api = ClientAPI()
                       ^^^^^^^^^^^
  File "/usr/local/anaconda3/lib/python3.11/site-packages/anaconda_navigator/api/client_api.py", line 667, in ClientAPI
    CLIENT_API = _ClientAPI()
                 ^^^^^^^^^^^^
  File "/usr/local/anaconda3/lib/python3.11/site-packages/anaconda_navigator/api/client_api.py", line 144, in __init__
    self.reload_client()
  File "/usr/local/anaconda3/lib/python3.11/site-packages/anaconda_navigator/api/client_api.py", line 344, in reload_client
    client.user()
  File "/usr/local/anaconda3/lib/python3.11/site-packages/binstar_client/__init__.py", line 244, in user
    self._check_response(res)
  File "/usr/local/anaconda3/lib/python3.11/site-packages/binstar_client/__init__.py", line 229, in _check_response
    raise ErrCls(msg, res.status_code)
binstar_client.errors.BinstarError: ('Email verification failed!', 403)

**Comment by hipvlady** [comment]
I got the workaround. Login in the browser to [https://anaconda.org/account/login](https://anaconda.org/account/login )
At the top, u'll see the warning about unverified email. Resend the verification email. Click on the link in the email.
Navigator will back to 'normal' work.

**Comment by vshevchenko-anaconda** [comment]
Users with unverified email addresses can no longer access the API, and as a result, they are unable to use the anaconda-client and Navigator tools as well. The issue here is that Navigator fails to properly catch the error caused by this restriction.

Workarounds:

- Use the 'anaconda logout' Command: If you're unable to access Navigator due to this issue, you can try using the 'anaconda logout' command. This should log you out from Navigator, allowing you to use it as an incognito user. However, while Navigator will become usable again, your unverified account's access limitations will remain in place.

- Verify Your Account on anaconda.org: To resolve the issue, we recommend verifying your account on anaconda.org. Follow these steps:
  1. Visit https://anaconda.org/account/login and enter your credentials.
  2. If your email is unverified, you will be prompted to verify it.
  3. Click on the "Resend Confirmation Email" button.
  4. Follow the instructions in your email inbox to complete the verification process.
  
  The fix for Navigator itself will be included in the next release.

**Comment by nithinelias** [comment]
@vshevchenko-anaconda  - excellent . that worked for me , thanks a lot !

**Comment by Gotobuild** [comment]
> 

This really work ! Thank you for your tips

**Comment by DrPrameela** [comment]
This really worked. Thanks a lot for your tips. Anaconda is moving to cloud I think, so its revamping

**Comment by repositryLUFFY** [comment]
My e-mail is verified but I am still facing the same problem

**Comment by csoja** [comment]
@repositryLUFFY If you "anaconda logout" from a terminal or command prompt as described by vshevchenko-anaconda above - do you still see the same problem?

**Comment by naureen-nura** [comment]
Email verification solved my problem, Thanks!

**Comment by repositryLUFFY** [comment]
> @repositryLUFFY If you "anaconda logout" from a terminal or command prompt as described by vshevchenko-anaconda above - do you still see the same problem?

Thanks , I will try it out

**Comment by Droszczak** [comment]
I faced the same problem and when I checked my email everything started working normally again!
Login in the browser to https://anaconda.org/account/login

**Comment by Manali-MS** [comment]
I have been facing the exact same issue for about a month. But today I logged into [https://anaconda.org/account/login] and after verifying my email address, the issue is fixed. Now the Anaconda navigator is opening and working fine.
