### ISSUE TITLE
Unable to start spyder 3.0.0b7 through Anaconda-Navigator on archlinux

### ISSUE THREAD

**Issue by thorstenwagner** [ContinuumIO/anaconda-issues#1325]
I've downloaded the latest version, update qt pyqt and then try to start spyder through the anaconda-navigator. However, I always get the following exception:

```
 Traceback
 (most recent call last):
  File "/home/thorsten/anaconda3/lib/python3.5/site-packages/qtpy/QtWebEngineWidgets.py", line 22, in <module>
    from PyQt5.QtWebEngineWidgets import QWebEnginePage
ImportError: No module named 'PyQt5.QtWebEngineWidgets'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/thorsten/anaconda3/bin/spyder", line 3, in <module>
    start.main()
  File "/home/thorsten/anaconda3/lib/python3.5/site-packages/spyder/app/start.py", line 103, in main
    from spyder.app import mainwindow
  File "/home/thorsten/anaconda3/lib/python3.5/site-packages/spyder/app/mainwindow.py", line 92, in <module>
    from qtpy import QtWebEngineWidgets  # analysis:ignore
  File "/home/thorsten/anaconda3/lib/python3.5/site-packages/qtpy/QtWebEngineWidgets.py", line 26, in <module>
    from PyQt5.QtWebKitWidgets import QWebPage as QWebEnginePage
ImportError: libselinux.so.1: cannot open shared object file: No such file or directory
```

If I install spyder from the archlinux repository it works fine.

**Comment by thorstenwagner** [comment]
I've tried to update anaconda via conda update anaconda:

```
conda update anaconda
Fetching package metadata .......
Solving package specifications: ..........

Package plan for installation in environment /home/thorsten/anaconda3:

The following packages will be UPDATED:

    spyder:     3.0.0b7-py35_1 spyder-ide --> 3.0.0-py35_0

The following packages will be DOWNGRADED due to dependency conflicts:

    cairo:      1.14.6-0                  --> 1.12.18-6   
    fontconfig: 2.12.1-0                  --> 2.11.1-6    
    pixman:     0.34.0-0                  --> 0.32.6-0    
    pyqt:       5.6.0-py35_1              --> 5.6.0-py35_0
    qt:         5.6.2-2                   --> 5.6.0-0    
```

The problem is still the same.

**Comment by thorstenwagner** [comment]
This fixed the problem:
> yaourt -S libselinux
