### ISSUE TITLE
'bytes' object has no attribute 'get'

### ISSUE THREAD

**Issue by jyothsnayeluru1990** [ContinuumIO/anaconda-issues#13288]
### Checklist

- [X] I added a descriptive title
- [X] I searched for other issues and couldn't find a solution or duplication
- [X] I already searched in Google and didn't find any good information or help
- [X] I looked at the [docs](https://docs.anaconda.com/anaconda/navigator/) and didn't see anything to help

### What happened?

when i try to open the navigator it is giving he error as 'bytes' object has no attribute 'get'
i have deleted the .condarc file and tried but i can still see the error

### Conda info

```shell
# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "C:\Users\NIVEGNA CHOWDARY\anaconda3\Lib\site-packages\conda\exception_handler.py", line 17, in __call__
        return func(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^
      File "C:\Users\NIVEGNA CHOWDARY\anaconda3\Lib\site-packages\conda\cli\main.py", line 54, in main_subshell
        parser = generate_parser(add_help=True)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "C:\Users\NIVEGNA CHOWDARY\anaconda3\Lib\site-packages\conda\cli\conda_argparse.py", line 127, in generate_parser
        configure_parser_plugins(sub_parsers)
      File "C:\Users\NIVEGNA CHOWDARY\anaconda3\Lib\site-packages\conda\cli\conda_argparse.py", line 354, in configure_parser_plugins
        else set(find_commands()).difference(plugin_subcommands)
                 ^^^^^^^^^^^^^^^
      File "C:\Users\NIVEGNA CHOWDARY\anaconda3\Lib\site-packages\conda\cli\find_commands.py", line 71, in find_commands        for entry in os.scandir(dir_path):
                     ^^^^^^^^^^^^^^^^^^^^
    OSError: [WinError 123] The filename, directory name, or volume label syntax is incorrect: '"C:\\Program Files\\Common Files\\Oracle\\Java\\javapath'

`$ C:\Users\NIVEGNA CHOWDARY\anaconda3\Scripts\conda-script.py info`


An unexpected error has occurred. Conda has prepared the above report.
If you suspect this error is being caused by a malfunctioning plugin,
consider using the --no-plugins option to turn off plugins.

Example: conda --no-plugins install <package>

Alternatively, you can set the CONDA_NO_PLUGINS environment variable on
the command line to run the command without plugins enabled.

Example: CONDA_NO_PLUGINS=true conda install <package>

If submitted, this report will be used by core maintainers to improve
future releases of conda.
Would you like conda to send this report to the core maintainers? [y/N]:
```

### Conda config

```shell
# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "C:\Users\NIVEGNA CHOWDARY\anaconda3\Lib\site-packages\conda\exception_handler.py", line 17, in __call__
        return func(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^
      File "C:\Users\NIVEGNA CHOWDARY\anaconda3\Lib\site-packages\conda\cli\main.py", line 54, in main_subshell
        parser = generate_parser(add_help=True)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "C:\Users\NIVEGNA CHOWDARY\anaconda3\Lib\site-packages\conda\cli\conda_argparse.py", line 127, in generate_parser
        configure_parser_plugins(sub_parsers)
      File "C:\Users\NIVEGNA CHOWDARY\anaconda3\Lib\site-packages\conda\cli\conda_argparse.py", line 354, in configure_parser_plugins
        else set(find_commands()).difference(plugin_subcommands)
                 ^^^^^^^^^^^^^^^
      File "C:\Users\NIVEGNA CHOWDARY\anaconda3\Lib\site-packages\conda\cli\find_commands.py", line 71, in find_commands
        for entry in os.scandir(dir_path):
                     ^^^^^^^^^^^^^^^^^^^^
    OSError: [WinError 123] The filename, directory name, or volume label syntax is incorrect: '"C:\\Program Files\\Common Files\\Oracle\\Java\\javapath'

`$ C:\Users\NIVEGNA CHOWDARY\anaconda3\Scripts\conda-script.py config --show-sources`

  environment variables:
                 CIO_TEST=<not set>
                CONDA_EXE=C:\Users\NIVEGNA CHOWDARY\anaconda3\condabin\..\Scripts\conda.exe
               CONDA_EXES="C:\Users\NIVEGNA CHOWDARY\anaconda3\condabin\..\Scripts\conda.exe"
               CONDA_ROOT=C:\Users\NIVEGNA CHOWDARY\anaconda3
           CURL_CA_BUNDLE=<not set>
                 HOMEPATH=\Users\NIVEGNA CHOWDARY
               LD_PRELOAD=<not set>
                     PATH="C:\Program Files\Common Files\Oracle\Java\javapath;C:\Program
                          Files\Java\jdk-16\bin";C:\Program Files\Java\jdk-16\bin;';C:\Program
                          Files\MySQL\MySQL Utilities 1.6\;C:\Program Files (x86)\Intel\Intel(R)
                          Management Engine Components\DAL;C:\Program Files\Intel\Intel(R)
                          Management Engine Components\DAL;C:\Program
                          Files\dotnet\;C:\Users\NIVEGNA CHOWDARY\anaconda3;C:\Users\NIVEGNA
                          CHOWDARY\anaconda3\Library\mingw-w64\bin;C:\Users\NIVEGNA
                          CHOWDARY\anaconda3\Library\usr\bin;C:\Users\NIVEGNA
                          CHOWDARY\anaconda3\Library\bin;C:\Users\NIVEGNA
                          CHOWDARY\anaconda3\Scripts;C:\Users\NIVEGNA CHOWDARY\AppData\Local\Pro
                          grams\Python\Python312\Scripts\;C:\Users\NIVEGNA
                          CHOWDARY\AppData\Local\Programs\Python\Python312\;C:\Users\NIVEGNA
                          CHOWDARY\AppData\Local\Microsoft\WindowsApps
             PSMODULEPATH=C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules\;C:\Program Files\W
                          indowsPowerShell\Modules;C:\WINDOWS\system32\WindowsPowerShell\v1.0\Mo
                          dules
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>

     active environment : None
       user config file : C:\Users\NIVEGNA CHOWDARY\.condarc
 populated config files :
          conda version : 23.7.4
    conda-build version : 3.26.1
         python version : 3.11.5.final.0
       virtual packages : __archspec=1=x86_64
                          __win=0=0
       base environment : C:\Users\NIVEGNA CHOWDARY\anaconda3  (writable)
      conda av data dir : C:\Users\NIVEGNA CHOWDARY\anaconda3\etc\conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\Users\NIVEGNA CHOWDARY\anaconda3\pkgs
                          C:\Users\NIVEGNA CHOWDARY\.conda\pkgs
                          C:\Users\NIVEGNA CHOWDARY\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\NIVEGNA CHOWDARY\anaconda3\envs
                          C:\Users\NIVEGNA CHOWDARY\.conda\envs
                          C:\Users\NIVEGNA CHOWDARY\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/23.7.4 requests/2.31.0 CPython/3.11.5 Windows/10 Windows/10.0.19045
          administrator : False
             netrc file : None
           offline mode : False


An unexpected error has occurred. Conda has prepared the above report.
If you suspect this error is being caused by a malfunctioning plugin,
consider using the --no-plugins option to turn off plugins.

Example: conda --no-plugins install <package>

Alternatively, you can set the CONDA_NO_PLUGINS environment variable on
the command line to run the command without plugins enabled.

Example: CONDA_NO_PLUGINS=true conda install <package>

If submitted, this report will be used by core maintainers to improve
future releases of conda.
Would you like conda to send this report to the core maintainers? [y/N]:
```

### Conda list

```shell
# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "C:\Users\NIVEGNA CHOWDARY\anaconda3\Lib\site-packages\conda\exception_handler.py", line 17, in __call__
        return func(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^
      File "C:\Users\NIVEGNA CHOWDARY\anaconda3\Lib\site-packages\conda\cli\main.py", line 54, in main_subshell
        parser = generate_parser(add_help=True)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "C:\Users\NIVEGNA CHOWDARY\anaconda3\Lib\site-packages\conda\cli\conda_argparse.py", line 127, in generate_parser
        configure_parser_plugins(sub_parsers)
      File "C:\Users\NIVEGNA CHOWDARY\anaconda3\Lib\site-packages\conda\cli\conda_argparse.py", line 354, in configure_parser_plugins
        else set(find_commands()).difference(plugin_subcommands)
                 ^^^^^^^^^^^^^^^
      File "C:\Users\NIVEGNA CHOWDARY\anaconda3\Lib\site-packages\conda\cli\find_commands.py", line 71, in find_commands
        for entry in os.scandir(dir_path):
                     ^^^^^^^^^^^^^^^^^^^^
    OSError: [WinError 123] The filename, directory name, or volume label syntax is incorrect: '"C:\\Program Files\\Common Files\\Oracle\\Java\\javapath'

`$ C:\Users\NIVEGNA CHOWDARY\anaconda3\Scripts\conda-script.py list --show-channel-urls`

  environment variables:
                 CIO_TEST=<not set>
                CONDA_EXE=C:\Users\NIVEGNA CHOWDARY\anaconda3\condabin\..\Scripts\conda.exe
               CONDA_EXES="C:\Users\NIVEGNA CHOWDARY\anaconda3\condabin\..\Scripts\conda.exe"
               CONDA_ROOT=C:\Users\NIVEGNA CHOWDARY\anaconda3
           CURL_CA_BUNDLE=<not set>
                 HOMEPATH=\Users\NIVEGNA CHOWDARY
               LD_PRELOAD=<not set>
                     PATH="C:\Program Files\Common Files\Oracle\Java\javapath;C:\Program
                          Files\Java\jdk-16\bin";C:\Program Files\Java\jdk-16\bin;';C:\Program
                          Files\MySQL\MySQL Utilities 1.6\;C:\Program Files (x86)\Intel\Intel(R)
                          Management Engine Components\DAL;C:\Program Files\Intel\Intel(R)
                          Management Engine Components\DAL;C:\Program
                          Files\dotnet\;C:\Users\NIVEGNA CHOWDARY\anaconda3;C:\Users\NIVEGNA
                          CHOWDARY\anaconda3\Library\mingw-w64\bin;C:\Users\NIVEGNA
                          CHOWDARY\anaconda3\Library\usr\bin;C:\Users\NIVEGNA
                          CHOWDARY\anaconda3\Library\bin;C:\Users\NIVEGNA
                          CHOWDARY\anaconda3\Scripts;C:\Users\NIVEGNA CHOWDARY\AppData\Local\Pro
                          grams\Python\Python312\Scripts\;C:\Users\NIVEGNA
                          CHOWDARY\AppData\Local\Programs\Python\Python312\;C:\Users\NIVEGNA
                          CHOWDARY\AppData\Local\Microsoft\WindowsApps
             PSMODULEPATH=C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules\;C:\Program Files\W
                          indowsPowerShell\Modules;C:\WINDOWS\system32\WindowsPowerShell\v1.0\Mo
                          dules
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>

     active environment : None
       user config file : C:\Users\NIVEGNA CHOWDARY\.condarc
 populated config files :
          conda version : 23.7.4
    conda-build version : 3.26.1
         python version : 3.11.5.final.0
       virtual packages : __archspec=1=x86_64
                          __win=0=0
       base environment : C:\Users\NIVEGNA CHOWDARY\anaconda3  (writable)
      conda av data dir : C:\Users\NIVEGNA CHOWDARY\anaconda3\etc\conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\Users\NIVEGNA CHOWDARY\anaconda3\pkgs
                          C:\Users\NIVEGNA CHOWDARY\.conda\pkgs
                          C:\Users\NIVEGNA CHOWDARY\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\NIVEGNA CHOWDARY\anaconda3\envs
                          C:\Users\NIVEGNA CHOWDARY\.conda\envs
                          C:\Users\NIVEGNA CHOWDARY\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/23.7.4 requests/2.31.0 CPython/3.11.5 Windows/10 Windows/10.0.19045
          administrator : False
             netrc file : None
           offline mode : False


An unexpected error has occurred. Conda has prepared the above report.
If you suspect this error is being caused by a malfunctioning plugin,
consider using the --no-plugins option to turn off plugins.

Example: conda --no-plugins install <package>

Alternatively, you can set the CONDA_NO_PLUGINS environment variable on
the command line to run the command without plugins enabled.

Example: CONDA_NO_PLUGINS=true conda install <package>

If submitted, this report will be used by core maintainers to improve
future releases of conda.
Would you like conda to send this report to the core maintainers? [y/N]:
```

**Comment by Soham-Bharti** [comment]
I am having the same. Tried everything that I can whether it's reinstallation to updating anaconda from prompt

**Comment by lmaonewhow** [comment]
The navigator has done an important job of looking for available commands from environment variables, maybe your question appears on "C:\\Program Files\\Common Files\\Oracle\\Java\\javapath', I have a similar problem with my Java, I have configured a similar %Java_Home%\bin; %Java_Home%\jre\bin; Java variable, but it is not parsed by the navigator normally with quotation marks, try to remove the variable or provide more information

**Comment by Hassan0Kamel** [comment]
did you solve it?

**Comment by andrespineda** [comment]
In Windows, edit your Environment Variables and look for the "Path" variable.

Edit the string that is assigned to that variable and delete the quote mark (") just before the C:\\Program Files...
**This is before:**
 "C:\\Program Files\\Common Files\\Oracle\\Java\\javapath
**This is After:**
 C:\\Program Files\\Common Files\\Oracle\\Java\\javapath

Click OK and then launch Anaconda Navigator.

This worked for me.
