### ISSUE TITLE
Main error 'bytes' has no attributes 'get'

### ISSUE THREAD

**Issue by JohnOlabs** [ContinuumIO/anaconda-issues#13286]
### Checklist

- [X] I added a descriptive title
- [X] I searched for other issues and couldn't find a solution or duplication
- [X] I already searched in Google and didn't find any good information or help
- [X] I looked at the [docs](https://docs.anaconda.com/anaconda/navigator/) and didn't see anything to help

### What happened?

Anaconda navigator has been working well for me until one day i got the Main error 'bytes' has no attributes 'get'. And it could not open the navigator. I then uninstalled it and cleared the directory and reinsstalled it. 

It then kinda worked but then when I closed it and reopened it it displayed the same error message.

I really need help and don't understand whats going on. 

### Conda info

```shell
(base) C:\Users\johno_9297evi>conda info

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "C:\Users\johno_9297evi\anaconda3\Lib\site-packages\conda\exception_handler.py", line 17, in __call__
        return func(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^
      File "C:\Users\johno_9297evi\anaconda3\Lib\site-packages\conda\cli\main.py", line 54, in main_subshell
        parser = generate_parser(add_help=True)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "C:\Users\johno_9297evi\anaconda3\Lib\site-packages\conda\cli\conda_argparse.py", line 127, in generate_parser
        configure_parser_plugins(sub_parsers)
      File "C:\Users\johno_9297evi\anaconda3\Lib\site-packages\conda\cli\conda_argparse.py", line 354, in configure_parser_plugins
        else set(find_commands()).difference(plugin_subcommands)
                 ^^^^^^^^^^^^^^^
      File "C:\Users\johno_9297evi\anaconda3\Lib\site-packages\conda\cli\find_commands.py", line 71, in find_commands
        for entry in os.scandir(dir_path):
                     ^^^^^^^^^^^^^^^^^^^^
    OSError: [WinError 123] The filename, directory name, or volume label syntax is incorrect: 'HKEY_LOCAL_MACHINE\\SYSTEM\\CurrentControlSet\\Control\\Session Manager\\Environment    PATH    REG_EXPAND_SZ    C:\\Program Files\\Common Files\\Oracle\\Java\\javapath'

`$ C:\Users\johno_9297evi\anaconda3\Scripts\conda-script.py info`


An unexpected error has occurred. Conda has prepared the above report.
If you suspect this error is being caused by a malfunctioning plugin,
consider using the --no-plugins option to turn off plugins.

Example: conda --no-plugins install <package>

Alternatively, you can set the CONDA_NO_PLUGINS environment variable on
the command line to run the command without plugins enabled.

Example: CONDA_NO_PLUGINS=true conda install <package>

If submitted, this report will be used by core maintainers to improve
future releases of conda.
Would you like conda to send this report to the core maintainers? [y/N]: y
Upload did not complete.

Thank you for helping to improve conda.
Opt-in to always sending reports (and not see this message again)
by running

    $ conda config --set report_errors true
```

### Conda config

```shell
`$ C:\Users\johno_9297evi\anaconda3\Scripts\conda-script.py info`


An unexpected error has occurred. Conda has prepared the above report.
If you suspect this error is being caused by a malfunctioning plugin,
consider using the --no-plugins option to turn off plugins.

Example: conda --no-plugins install <package>

Alternatively, you can set the CONDA_NO_PLUGINS environment variable on
the command line to run the command without plugins enabled.

Example: CONDA_NO_PLUGINS=true conda install <package>

If submitted, this report will be used by core maintainers to improve
future releases of conda.
Would you like conda to send this report to the core maintainers? [y/N]: y
Upload did not complete.

Thank you for helping to improve conda.
Opt-in to always sending reports (and not see this message again)
by running

    $ conda config --set report_errors true


(base) C:\Users\johno_9297evi>conda config --show-sources

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "C:\Users\johno_9297evi\anaconda3\Lib\site-packages\conda\exception_handler.py", line 17, in __call__
        return func(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^
      File "C:\Users\johno_9297evi\anaconda3\Lib\site-packages\conda\cli\main.py", line 54, in main_subshell
        parser = generate_parser(add_help=True)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "C:\Users\johno_9297evi\anaconda3\Lib\site-packages\conda\cli\conda_argparse.py", line 127, in generate_parser
        configure_parser_plugins(sub_parsers)
      File "C:\Users\johno_9297evi\anaconda3\Lib\site-packages\conda\cli\conda_argparse.py", line 354, in configure_parser_plugins
        else set(find_commands()).difference(plugin_subcommands)
                 ^^^^^^^^^^^^^^^
      File "C:\Users\johno_9297evi\anaconda3\Lib\site-packages\conda\cli\find_commands.py", line 71, in find_commands
        for entry in os.scandir(dir_path):
                     ^^^^^^^^^^^^^^^^^^^^
    OSError: [WinError 123] The filename, directory name, or volume label syntax is incorrect: 'HKEY_LOCAL_MACHINE\\SYSTEM\\CurrentControlSet\\Control\\Session Manager\\Environment    PATH    REG_EXPAND_SZ    C:\\Program Files\\Common Files\\Oracle\\Java\\javapath'

`$ C:\Users\johno_9297evi\anaconda3\Scripts\conda-script.py config --show-sources`

  environment variables:
                 CIO_TEST=<not set>
        CONDA_DEFAULT_ENV=base
                CONDA_EXE=C:\Users\johno_9297evi\anaconda3\condabin\..\Scripts\conda.exe
               CONDA_EXES="C:\Users\johno_9297evi\anaconda3\condabin\..\Scripts\conda.exe"
             CONDA_PREFIX=C:\Users\johno_9297evi\anaconda3
    CONDA_PROMPT_MODIFIER=(base)
         CONDA_PYTHON_EXE=C:\Users\johno_9297evi\anaconda3\python.exe
               CONDA_ROOT=C:\Users\johno_9297evi\anaconda3
              CONDA_SHLVL=1
           CURL_CA_BUNDLE=<not set>
                 HOMEPATH=\Users\johno_9297evi
               LD_PRELOAD=<not set>
                     PATH=C:\Users\johno_9297evi\anaconda3;C:\Users\johno_9297evi\anaconda3\Libr
                          ary\mingw-
                          w64\bin;C:\Users\johno_9297evi\anaconda3\Library\usr\bin;C:\Users\john
                          o_9297evi\anaconda3\Library\bin;C:\Users\johno_9297evi\anaconda3\Scrip
                          ts;C:\Users\johno_9297evi\anaconda3\bin;C:\Users\johno_9297evi\anacond
                          a3\condabin;HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Sessio
                          n Manager\Environment    PATH    REG_EXPAND_SZ    C:\Program
                          Files\Common Files\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS
                          ;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0;C
                          :\WINDOWS\System32\OpenSSH;C:\MinGW\bin;C:\MinGW\msys\1.0\bin;C:\Progr
                          am Files\MongoDB\Server\6.0\bin;C:\Program Files\Git\cmd;C:\Users\john
                          o_9297evi\AppData\Local\Programs\nosqlbooster4mongo;C:\Program
                          Files\Java\jdk-11.0.12\bin;C:\Program Files\dotnet;C:\Users\johno_9297
                          evi\anaconda3;C:\Users\johno_9297evi\anaconda3\Library\mingw-
                          w64\bin;C:\Users\johno_9297evi\anaconda3\Library\usr\bin;C:\Users\john
                          o_9297evi\anaconda3\Library\bin;C:\Users\johno_9297evi\anaconda3\Scrip
                          ts;C:\Users\johno_9297evi\AppData\Local\Microsoft\WindowsApps;C:\Users
                          \johno_9297evi\AppData\Local\Microsoft\WindowsApps;C:\Program
                          Files\MongoDB\Server\6.0\bin;C:\Program Files (x86)\MongoDB Atlas CLI
             PSMODULEPATH=C:\Program Files\WindowsPowerShell\Modules;C:\WINDOWS\system32\Windows
                          PowerShell\v1.0\Modules
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=C:\Users\johno_9297evi\anaconda3\Library\ssl\cacert.pem

     active environment : base
    active env location : C:\Users\johno_9297evi\anaconda3
            shell level : 1
       user config file : C:\Users\johno_9297evi\.condarc
 populated config files : C:\Users\johno_9297evi\.condarc
          conda version : 23.7.4
    conda-build version : 3.26.1
         python version : 3.11.5.final.0
       virtual packages : __archspec=1=x86_64
                          __win=0=0
       base environment : C:\Users\johno_9297evi\anaconda3  (writable)
      conda av data dir : C:\Users\johno_9297evi\anaconda3\etc\conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\Users\johno_9297evi\anaconda3\pkgs
                          C:\Users\johno_9297evi\.conda\pkgs
                          C:\Users\johno_9297evi\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\johno_9297evi\anaconda3\envs
                          C:\Users\johno_9297evi\.conda\envs
                          C:\Users\johno_9297evi\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/23.7.4 requests/2.31.0 CPython/3.11.5 Windows/10 Windows/10.0.22621
          administrator : False
             netrc file : None
           offline mode : False


An unexpected error has occurred. Conda has prepared the above report.
If you suspect this error is being caused by a malfunctioning plugin,
consider using the --no-plugins option to turn off plugins.

Example: conda --no-plugins install <package>

Alternatively, you can set the CONDA_NO_PLUGINS environment variable on
the command line to run the command without plugins enabled.

Example: CONDA_NO_PLUGINS=true conda install <package>

If submitted, this report will be used by core maintainers to improve
future releases of conda.
Would you like conda to send this report to the core maintainers? [y/N]: y
Upload did not complete.

Thank you for helping to improve conda.
Opt-in to always sending reports (and not see this message again)
by running

    $ conda config --set report_errors true
```

### Conda list

```shell
`$ C:\Users\johno_9297evi\anaconda3\Scripts\conda-script.py list --show-channel-urls`

  environment variables:
                 CIO_TEST=<not set>
        CONDA_DEFAULT_ENV=base
                CONDA_EXE=C:\Users\johno_9297evi\anaconda3\condabin\..\Scripts\conda.exe
               CONDA_EXES="C:\Users\johno_9297evi\anaconda3\condabin\..\Scripts\conda.exe"
             CONDA_PREFIX=C:\Users\johno_9297evi\anaconda3
    CONDA_PROMPT_MODIFIER=(base)
         CONDA_PYTHON_EXE=C:\Users\johno_9297evi\anaconda3\python.exe
               CONDA_ROOT=C:\Users\johno_9297evi\anaconda3
              CONDA_SHLVL=1
           CURL_CA_BUNDLE=<not set>
                 HOMEPATH=\Users\johno_9297evi
               LD_PRELOAD=<not set>
                     PATH=C:\Users\johno_9297evi\anaconda3;C:\Users\johno_9297evi\anaconda3\Libr
                          ary\mingw-
                          w64\bin;C:\Users\johno_9297evi\anaconda3\Library\usr\bin;C:\Users\john
                          o_9297evi\anaconda3\Library\bin;C:\Users\johno_9297evi\anaconda3\Scrip
                          ts;C:\Users\johno_9297evi\anaconda3\bin;C:\Users\johno_9297evi\anacond
                          a3\condabin;HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Sessio
                          n Manager\Environment    PATH    REG_EXPAND_SZ    C:\Program
                          Files\Common Files\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS
                          ;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0;C
                          :\WINDOWS\System32\OpenSSH;C:\MinGW\bin;C:\MinGW\msys\1.0\bin;C:\Progr
                          am Files\MongoDB\Server\6.0\bin;C:\Program Files\Git\cmd;C:\Users\john
                          o_9297evi\AppData\Local\Programs\nosqlbooster4mongo;C:\Program
                          Files\Java\jdk-11.0.12\bin;C:\Program Files\dotnet;C:\Users\johno_9297
                          evi\anaconda3;C:\Users\johno_9297evi\anaconda3\Library\mingw-
                          w64\bin;C:\Users\johno_9297evi\anaconda3\Library\usr\bin;C:\Users\john
                          o_9297evi\anaconda3\Library\bin;C:\Users\johno_9297evi\anaconda3\Scrip
                          ts;C:\Users\johno_9297evi\AppData\Local\Microsoft\WindowsApps;C:\Users
                          \johno_9297evi\AppData\Local\Microsoft\WindowsApps;C:\Program
                          Files\MongoDB\Server\6.0\bin;C:\Program Files (x86)\MongoDB Atlas CLI
             PSMODULEPATH=C:\Program Files\WindowsPowerShell\Modules;C:\WINDOWS\system32\Windows
                          PowerShell\v1.0\Modules
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=C:\Users\johno_9297evi\anaconda3\Library\ssl\cacert.pem

     active environment : base
    active env location : C:\Users\johno_9297evi\anaconda3
            shell level : 1
       user config file : C:\Users\johno_9297evi\.condarc
 populated config files : C:\Users\johno_9297evi\.condarc
          conda version : 23.7.4
    conda-build version : 3.26.1
         python version : 3.11.5.final.0
       virtual packages : __archspec=1=x86_64
                          __win=0=0
       base environment : C:\Users\johno_9297evi\anaconda3  (writable)
      conda av data dir : C:\Users\johno_9297evi\anaconda3\etc\conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\Users\johno_9297evi\anaconda3\pkgs
                          C:\Users\johno_9297evi\.conda\pkgs
                          C:\Users\johno_9297evi\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\johno_9297evi\anaconda3\envs
                          C:\Users\johno_9297evi\.conda\envs
                          C:\Users\johno_9297evi\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/23.7.4 requests/2.31.0 CPython/3.11.5 Windows/10 Windows/10.0.22621
          administrator : False
             netrc file : None
           offline mode : False


An unexpected error has occurred. Conda has prepared the above report.
If you suspect this error is being caused by a malfunctioning plugin,
consider using the --no-plugins option to turn off plugins.

Example: conda --no-plugins install <package>

Alternatively, you can set the CONDA_NO_PLUGINS environment variable on
the command line to run the command without plugins enabled.

Example: CONDA_NO_PLUGINS=true conda install <package>

If submitted, this report will be used by core maintainers to improve
future releases of conda.
Would you like conda to send this report to the core maintainers? [y/N]: y
Upload did not complete.

Thank you for helping to improve conda.
Opt-in to always sending reports (and not see this message again)
by running

    $ conda config --set report_errors true
```

### Additional Context

<img width="556" alt="Screenshot error" src="https://github.com/ContinuumIO/anaconda-issues/assets/98469442/b69bf137-47ba-4419-9c9b-a482ca98681c">

**Comment by JohnOlabs** [comment]
Updating Anaconda error:

Microsoft Windows [Version 10.0.22621.2428]
(c) Microsoft Corporation. All rights reserved.

C:\Users\johno_9297evi>conda update conda

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "C:\Users\johno_9297evi\anaconda3\Lib\site-packages\conda\exception_handler.py", line 17, in __call__
        return func(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^
      File "C:\Users\johno_9297evi\anaconda3\Lib\site-packages\conda\cli\main.py", line 54, in main_subshell
        parser = generate_parser(add_help=True)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "C:\Users\johno_9297evi\anaconda3\Lib\site-packages\conda\cli\conda_argparse.py", line 127, in generate_parser
        configure_parser_plugins(sub_parsers)
      File "C:\Users\johno_9297evi\anaconda3\Lib\site-packages\conda\cli\conda_argparse.py", line 354, in configure_parser_plugins
        else set(find_commands()).difference(plugin_subcommands)
                 ^^^^^^^^^^^^^^^
      File "C:\Users\johno_9297evi\anaconda3\Lib\site-packages\conda\cli\find_commands.py", line 71, in find_commands
        for entry in os.scandir(dir_path):
                     ^^^^^^^^^^^^^^^^^^^^
    OSError: [WinError 123] The filename, directory name, or volume label syntax is incorrect: 'HKEY_LOCAL_MACHINE\\SYSTEM\\CurrentControlSet\\Control\\Session Manager\\Environment    PATH    REG_EXPAND_SZ    C:\\Program Files\\Common Files\\Oracle\\Java\\javapath'

`$ C:\Users\johno_9297evi\anaconda3\Scripts\conda-script.py update conda`

  environment variables:
                 CIO_TEST=<not set>
                CONDA_EXE=C:\Users\johno_9297evi\anaconda3\condabin\..\Scripts\conda.exe
               CONDA_EXES="C:\Users\johno_9297evi\anaconda3\condabin\..\Scripts\conda.exe"
               CONDA_ROOT=C:\Users\johno_9297evi\anaconda3
           CURL_CA_BUNDLE=<not set>
                 HOMEPATH=\Users\johno_9297evi
               LD_PRELOAD=<not set>
                     PATH=HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Session
                          Manager\Environment    PATH    REG_EXPAND_SZ    C:\Program
                          Files\Common Files\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS
                          ;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;
                          C:\WINDOWS\System32\OpenSSH\;C:\MinGW\bin;C:\MinGW\msys\1.0\bin;C:\Pro
                          gram Files\MongoDB\Server\6.0\bin;C:\Program Files\Git\cmd;C:\Users\jo
                          hno_9297evi\AppData\Local\Programs\nosqlbooster4mongo;C:\Program
                          Files\Java\jdk-11.0.12\bin;C:\Program Files\dotnet\;C:\Users\johno_929
                          7evi\anaconda3;C:\Users\johno_9297evi\anaconda3\Library\mingw-
                          w64\bin;C:\Users\johno_9297evi\anaconda3\Library\usr\bin;C:\Users\john
                          o_9297evi\anaconda3\Library\bin;C:\Users\johno_9297evi\anaconda3\Scrip
                          ts;C:\Users\johno_9297evi\AppData\Local\Microsoft\WindowsApps;C:\Users
                          \johno_9297evi\AppData\Local\Microsoft\WindowsApps;C:\Program
                          Files\MongoDB\Server\6.0\bin;C:\Program Files (x86)\MongoDB Atlas CLI\
             PSMODULEPATH=C:\Program Files\WindowsPowerShell\Modules;C:\WINDOWS\system32\Windows
                          PowerShell\v1.0\Modules
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>

     active environment : None
       user config file : C:\Users\johno_9297evi\.condarc
 populated config files : C:\Users\johno_9297evi\.condarc
          conda version : 23.7.4
    conda-build version : 3.26.1
         python version : 3.11.5.final.0
       virtual packages : __archspec=1=x86_64
                          __win=0=0
       base environment : C:\Users\johno_9297evi\anaconda3  (writable)
      conda av data dir : C:\Users\johno_9297evi\anaconda3\etc\conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\Users\johno_9297evi\anaconda3\pkgs
                          C:\Users\johno_9297evi\.conda\pkgs
                          C:\Users\johno_9297evi\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\johno_9297evi\anaconda3\envs
                          C:\Users\johno_9297evi\.conda\envs
                          C:\Users\johno_9297evi\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/23.7.4 requests/2.31.0 CPython/3.11.5 Windows/10 Windows/10.0.22621
          administrator : False
             netrc file : None
           offline mode : False


An unexpected error has occurred. Conda has prepared the above report.
If you suspect this error is being caused by a malfunctioning plugin,
consider using the --no-plugins option to turn off plugins.

Example: conda --no-plugins install <package>

Alternatively, you can set the CONDA_NO_PLUGINS environment variable on
the command line to run the command without plugins enabled.

Example: CONDA_NO_PLUGINS=true conda install <package>

If submitted, this report will be used by core maintainers to improve
future releases of conda.
Would you like conda to send this report to the core maintainers? [y/N]: conda update anaconda-navigator

No report sent. To permanently opt-out, use

    $ conda config --set report_errors false


C:\Users\johno_9297evi>conda update navigator-update

**Comment by liupeng0913** [comment]
hi, I encountered the same error as you. The root cause _"OSError: [WinError 123] The filename, directory name, or volume label syntax is incorrect:"_ is due to incorrectly configured fields in the system environment variables.
 I have no idea why Anaconda traverses reading all the system environment variables, but it does, and therefore causes the error we encountered.
Maybe you should check the configuration of *HKEY_LOCAL_MACHINE\\SYSTEM\\CurrentControlSet...*

**Comment by JohnOlabs** [comment]
[heart]         John Olabhie reacted to your message:
________________________________

**Comment by JohnOlabs** [comment]
Hi Liu,

Thanks so much for your kind assistance. I genuinely appreciate it very much. I will give it a go.

Many thanks,
John

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Khojram** [comment]
hi, I also encountered the same error as you. And i am unable to fix the issue please help..
