### ISSUE TITLE
Navigator Error on second time startup

### ISSUE THREAD

**Issue by muzammil-13** [ContinuumIO/anaconda-issues#13298]
### Checklist

- [X] I added a descriptive title
- [X] I searched for other issues and couldn't find a solution or duplication
- [X] I already searched in Google and didn't find any good information or help
- [X] I looked at the [docs](https://docs.anaconda.com/anaconda/navigator/) and didn't see anything to help

### What happened?

**Navigator Start Error**

Navigator Error
An unexpected error occurred on Navigator start-up
Report
Please report this issue in the anaconda issue tracker
Main Error
_![anaconda3 navigator error (Screenshot 2023-11-22 073437](https://github.com/ContinuumIO/anaconda-issues/assets/58184829/72507c2b-20c7-4d40-ae66-79da186e418d)_
Traceback
Traceback (most recent call last):
File "C:\Users\muzam\anaconda3\Lib\site-packages\anaconda_navigator\exceptio
return_value = func(*args, ** kwargs)
File "C:\Users\muzam\anaconda3\Lib\site-packages\anaconda_navigator\app\star
window = run_app(splash)
File "C:\Users\muzam\anaconda3\Lib\site-packages\anaconda_navigator\app\star
window = MainWindow(splash=splash)
File "C:\Users\muzam\anaconda3\Lib\site-packages\anaconda_navigator\widgets\
self.api = AnacondaAPI ()
File "C:\Users\muzam\anaconda3\Lib\site-packages\anaconda_navigator\api\anac
ANACONDA_API = AnacondaAPI ()
RAA
File "C:\Users\muzam\anaconda3\Lib\site-packages\anaconda_navigator\api\anac
self ._ conda_api = CondaAPI ()
RAAAARAARA
File "C:\Users\muzam\anaconda3\Lib\site-packages\anaconda_navigator\api\cond
CONDA_API = CondaAPI ()
File "C:\Users\muzam\anaconda3\Lib\site-packages\anaconda_navigator\api\cond
self.set_conda_prefix(info=get_conda_info(allow_fixes=True) )
File "C:\Users\muzam\anaconda3\Lib\site-packages\anaconda_navigator\api\cond
self.ROOT_PREFIX = info.get ('root_prefix') # str
AAAAAAAR
AttributeError: 'bytes' object has no attribute 'get'

### Conda info

```shell
# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "C:\Users\muzam\anaconda3\Lib\site-packages\conda\exception_handler.py", line 17, in __call__
        return func(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^
      File "C:\Users\muzam\anaconda3\Lib\site-packages\conda\cli\main.py", line 54, in main_subshell
        parser = generate_parser(add_help=True)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "C:\Users\muzam\anaconda3\Lib\site-packages\conda\cli\conda_argparse.py", line 127, in generate_parser
        configure_parser_plugins(sub_parsers)
      File "C:\Users\muzam\anaconda3\Lib\site-packages\conda\cli\conda_argparse.py", line 354, in configure_parser_plugins
        else set(find_commands()).difference(plugin_subcommands)
                 ^^^^^^^^^^^^^^^
      File "C:\Users\muzam\anaconda3\Lib\site-packages\conda\cli\find_commands.py", line 71, in find_commands
        for entry in os.scandir(dir_path):
                     ^^^^^^^^^^^^^^^^^^^^
    OSError: [WinError 123] The filename, directory name, or volume label syntax is incorrect: '"C:\\Android\\Sdk\\platform-tools\\adb.exe'

`$ C:\Users\muzam\anaconda3\Scripts\conda-script.py info`


An unexpected error has occurred. Conda has prepared the above report.
If you suspect this error is being caused by a malfunctioning plugin,
consider using the --no-plugins option to turn off plugins.

Example: conda --no-plugins install <package>
```

### Conda config

```shell
# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "C:\Users\muzam\anaconda3\Lib\site-packages\conda\exception_handler.py", line 17, in __call__
        return func(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^
      File "C:\Users\muzam\anaconda3\Lib\site-packages\conda\cli\main.py", line 54, in main_subshell
        parser = generate_parser(add_help=True)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "C:\Users\muzam\anaconda3\Lib\site-packages\conda\cli\conda_argparse.py", line 127, in generate_parser
        configure_parser_plugins(sub_parsers)
      File "C:\Users\muzam\anaconda3\Lib\site-packages\conda\cli\conda_argparse.py", line 354, in configure_parser_plugins
        else set(find_commands()).difference(plugin_subcommands)
                 ^^^^^^^^^^^^^^^
      File "C:\Users\muzam\anaconda3\Lib\site-packages\conda\cli\find_commands.py", line 71, in find_commands
        for entry in os.scandir(dir_path):
                     ^^^^^^^^^^^^^^^^^^^^
    OSError: [WinError 123] The filename, directory name, or volume label syntax is incorrect: '"C:\\Android\\Sdk\\platform-tools\\adb.exe'

`$ C:\Users\muzam\anaconda3\Scripts\conda-script.py config --show-sources`

  environment variables:
                 CIO_TEST=<not set>
        CONDA_DEFAULT_ENV=base
                CONDA_EXE=C:\Users\muzam\anaconda3\condabin\..\Scripts\conda.exe
               CONDA_EXES="C:\Users\muzam\anaconda3\condabin\..\Scripts\conda.exe"
             CONDA_PREFIX=C:\Users\muzam\anaconda3
    CONDA_PROMPT_MODIFIER=(base)
         CONDA_PYTHON_EXE=C:\Users\muzam\anaconda3\python.exe
               CONDA_ROOT=C:\Users\muzam\anaconda3
              CONDA_SHLVL=1
           CURL_CA_BUNDLE=<not set>
                 HOMEPATH=\Users\muzam
               LD_PRELOAD=<not set>
                     PATH=C:\Users\muzam\anaconda3;C:\Users\muzam\anaconda3\Library\mingw-
                          w64\bin;C:\Users\muzam\anaconda3\Library\usr\bin;C:\Users\muzam\anacon
                          da3\Library\bin;C:\Users\muzam\anaconda3\Scripts;C:\Users\muzam\anacon
                          da3\bin;C:\Users\muzam\anaconda3\condabin;C:\Program Files\Eclipse
                          Adoptium\jdk-21.0.0.35-hotspot\bin;C:\Program Files\OpenSSH;C:\Users\m
                          uzam\AppData\Local\Programs\Python\Python311\Scripts;C:\Users\muzam\Ap
                          pData\Local\Programs\Python\Python311;C:\WINDOWS\system32;C:\WINDOWS;C
                          :\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0;C:\
                          WINDOWS\System32\OpenSSH;C:\Program Files\Git\cmd;C:\Program
                          Files\nodejs;C:\ProgramData\chocolatey\bin;"C:\Android\Sdk\platform-
                          tools\adb.exe; C:\Android\Sdk\platform-tools\fastboot.exe";C:\Users\mu
                          zam\anaconda3;C:\Users\muzam\anaconda3\Library\mingw-
                          w64\bin;C:\Users\muzam\anaconda3\Library\usr\bin;C:\Users\muzam\anacon
                          da3\Library\bin;C:\Users\muzam\anaconda3\Scripts;C:\Users\muzam\AppDat
                          a\Local\Programs\Python\Python38\Scripts;C:\Users\muzam\AppData\Local\
                          Programs\Python\Python38;C:\Users\muzam\AppData\Local\Microsoft\Window
                          sApps;C:\Program Files\JetBrains\PyCharm Community Edition
                          2023.2\bin;C:\Users\muzam\AppData\Local\Programs\Microsoft VS Code\bin
                          ;C:\Android\flutter\bin;C:\Users\muzam\AppData\Roaming\npm;C:\Users\mu
                          zam\anaconda3 ; C:\Users\muzam\anaconda3\Scripts ;
                          C:\Users\muzam\anaconda3\Library\bin
             PSMODULEPATH=C:\Program Files\WindowsPowerShell\Modules;C:\WINDOWS\system32\Windows
                          PowerShell\v1.0\Modules
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=C:\Users\muzam\anaconda3\Library\ssl\cacert.pem
    VBOX_MSI_INSTALL_PATH=C:\Program Files\Oracle\VirtualBox\

     active environment : base
    active env location : C:\Users\muzam\anaconda3
            shell level : 1
       user config file : C:\Users\muzam\.condarc
 populated config files : C:\Users\muzam\.condarc
          conda version : 23.7.4
    conda-build version : 3.26.1
         python version : 3.11.5.final.0
       virtual packages : __archspec=1=x86_64
                          __win=0=0
       base environment : C:\Users\muzam\anaconda3  (writable)
      conda av data dir : C:\Users\muzam\anaconda3\etc\conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\Users\muzam\anaconda3\pkgs
                          C:\Users\muzam\.conda\pkgs
                          C:\Users\muzam\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\muzam\anaconda3\envs
                          C:\Users\muzam\.conda\envs
                          C:\Users\muzam\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/23.7.4 requests/2.31.0 CPython/3.11.5 Windows/10 Windows/10.0.22631
          administrator : True
             netrc file : None
           offline mode : False


An unexpected error has occurred. Conda has prepared the above report.
If you suspect this error is being caused by a malfunctioning plugin,
consider using the --no-plugins option to turn off plugins.

Example: conda --no-plugins install <package>

Alternatively, you can set the CONDA_NO_PLUGINS environment variable on
the command line to run the command without plugins enabled.

Example: CONDA_NO_PLUGINS=true conda install <package>

If submitted, this report will be used by core maintainers to improve
future releases of conda.
Would you like conda to send this report to the core maintainers? [y/N]:

No report sent. To permanently opt-out, use

    $ conda config --set report_errors false
```

### Conda list

```shell
# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "C:\Users\muzam\anaconda3\Lib\site-packages\conda\exception_handler.py", line 17, in __call__
        return func(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^
      File "C:\Users\muzam\anaconda3\Lib\site-packages\conda\cli\main.py", line 54, in main_subshell
        parser = generate_parser(add_help=True)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "C:\Users\muzam\anaconda3\Lib\site-packages\conda\cli\conda_argparse.py", line 127, in generate_parser
        configure_parser_plugins(sub_parsers)
      File "C:\Users\muzam\anaconda3\Lib\site-packages\conda\cli\conda_argparse.py", line 354, in configure_parser_plugins
        else set(find_commands()).difference(plugin_subcommands)
                 ^^^^^^^^^^^^^^^
      File "C:\Users\muzam\anaconda3\Lib\site-packages\conda\cli\find_commands.py", line 71, in find_commands
        for entry in os.scandir(dir_path):
                     ^^^^^^^^^^^^^^^^^^^^
    OSError: [WinError 123] The filename, directory name, or volume label syntax is incorrect: '"C:\\Android\\Sdk\\platform-tools\\adb.exe'

`$ C:\Users\muzam\anaconda3\Scripts\conda-script.py list --show-channel-urls`

  environment variables:
                 CIO_TEST=<not set>
        CONDA_DEFAULT_ENV=base
                CONDA_EXE=C:\Users\muzam\anaconda3\condabin\..\Scripts\conda.exe
               CONDA_EXES="C:\Users\muzam\anaconda3\condabin\..\Scripts\conda.exe"
             CONDA_PREFIX=C:\Users\muzam\anaconda3
    CONDA_PROMPT_MODIFIER=(base)
         CONDA_PYTHON_EXE=C:\Users\muzam\anaconda3\python.exe
               CONDA_ROOT=C:\Users\muzam\anaconda3
              CONDA_SHLVL=1
           CURL_CA_BUNDLE=<not set>
                 HOMEPATH=\Users\muzam
               LD_PRELOAD=<not set>
                     PATH=C:\Users\muzam\anaconda3;C:\Users\muzam\anaconda3\Library\mingw-
                          w64\bin;C:\Users\muzam\anaconda3\Library\usr\bin;C:\Users\muzam\anacon
                          da3\Library\bin;C:\Users\muzam\anaconda3\Scripts;C:\Users\muzam\anacon
                          da3\bin;C:\Users\muzam\anaconda3\condabin;C:\Program Files\Eclipse
                          Adoptium\jdk-21.0.0.35-hotspot\bin;C:\Program Files\OpenSSH;C:\Users\m
                          uzam\AppData\Local\Programs\Python\Python311\Scripts;C:\Users\muzam\Ap
                          pData\Local\Programs\Python\Python311;C:\WINDOWS\system32;C:\WINDOWS;C
                          :\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0;C:\
                          WINDOWS\System32\OpenSSH;C:\Program Files\Git\cmd;C:\Program
                          Files\nodejs;C:\ProgramData\chocolatey\bin;"C:\Android\Sdk\platform-
                          tools\adb.exe; C:\Android\Sdk\platform-tools\fastboot.exe";C:\Users\mu
                          zam\anaconda3;C:\Users\muzam\anaconda3\Library\mingw-
                          w64\bin;C:\Users\muzam\anaconda3\Library\usr\bin;C:\Users\muzam\anacon
                          da3\Library\bin;C:\Users\muzam\anaconda3\Scripts;C:\Users\muzam\AppDat
                          a\Local\Programs\Python\Python38\Scripts;C:\Users\muzam\AppData\Local\
                          Programs\Python\Python38;C:\Users\muzam\AppData\Local\Microsoft\Window
                          sApps;C:\Program Files\JetBrains\PyCharm Community Edition
                          2023.2\bin;C:\Users\muzam\AppData\Local\Programs\Microsoft VS Code\bin
                          ;C:\Android\flutter\bin;C:\Users\muzam\AppData\Roaming\npm;C:\Users\mu
                          zam\anaconda3 ; C:\Users\muzam\anaconda3\Scripts ;
                          C:\Users\muzam\anaconda3\Library\bin
             PSMODULEPATH=C:\Program Files\WindowsPowerShell\Modules;C:\WINDOWS\system32\Windows
                          PowerShell\v1.0\Modules
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=C:\Users\muzam\anaconda3\Library\ssl\cacert.pem
    VBOX_MSI_INSTALL_PATH=C:\Program Files\Oracle\VirtualBox\

     active environment : base
    active env location : C:\Users\muzam\anaconda3
            shell level : 1
       user config file : C:\Users\muzam\.condarc
 populated config files : C:\Users\muzam\.condarc
          conda version : 23.7.4
    conda-build version : 3.26.1
         python version : 3.11.5.final.0
       virtual packages : __archspec=1=x86_64
                          __win=0=0
       base environment : C:\Users\muzam\anaconda3  (writable)
      conda av data dir : C:\Users\muzam\anaconda3\etc\conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\Users\muzam\anaconda3\pkgs
                          C:\Users\muzam\.conda\pkgs
                          C:\Users\muzam\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\muzam\anaconda3\envs
                          C:\Users\muzam\.conda\envs
                          C:\Users\muzam\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/23.7.4 requests/2.31.0 CPython/3.11.5 Windows/10 Windows/10.0.22631
          administrator : True
             netrc file : None
           offline mode : False


An unexpected error has occurred. Conda has prepared the above report.
If you suspect this error is being caused by a malfunctioning plugin,
consider using the --no-plugins option to turn off plugins.

Example: conda --no-plugins install <package>

Alternatively, you can set the CONDA_NO_PLUGINS environment variable on
the command line to run the command without plugins enabled.

Example: CONDA_NO_PLUGINS=true conda install <package>

If submitted, this report will be used by core maintainers to improve
future releases of conda.
Would you like conda to send this report to the core maintainers? [y/N]:

No report sent. To permanently opt-out, use

    $ conda config --set report_errors false
```

### Additional Context

![Uploading anaconda3 navigator error (Screenshot 2023-11-22 073437.png…]()

**Comment by TheGreatFateemah** [comment]
What is the solution to this problem please?

**Comment by muzammil-13** [comment]
> did you solve it?

No...

**Comment by Khojram** [comment]
i am also encounter the same issue. and unable to fix the same..if any one fix this please help

**Comment by IronK109** [comment]
plllsssssssss me too

**Comment by Sadhik2299** [comment]
I'm also facing same issue, could someone help on this

**Comment by deepikaarunD** [comment]
Im also facing same issue

**Comment by muzammil-13** [comment]
Issue **solved** with **latest update!**
