### ISSUE TITLE
我的导航器无法正常启动

### ISSUE THREAD

**Issue by LTtt456c** [ContinuumIO/anaconda-issues#13302]
### Checklist

- [X] I added a descriptive title
- [X] I searched for other issues and couldn't find a solution or duplication
- [X] I already searched in Google and didn't find any good information or help
- [X] I looked at the [docs](https://docs.anaconda.com/anaconda/navigator/) and didn't see anything to help

### What happened?

安装anaconda3后使用Anaconda Navigator启动报错

### Conda info

```shell
# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "D:\ProgramData\anaconda3\Lib\site-packages\conda\exception_handler.py", line 17, in __call__
        return func(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^
      File "D:\ProgramData\anaconda3\Lib\site-packages\conda\cli\main.py", line 54, in main_subshell
        parser = generate_parser(add_help=True)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "D:\ProgramData\anaconda3\Lib\site-packages\conda\cli\conda_argparse.py", line 127, in generate_parser
        configure_parser_plugins(sub_parsers)
      File "D:\ProgramData\anaconda3\Lib\site-packages\conda\cli\conda_argparse.py", line 354, in configure_parser_plugins
        else set(find_commands()).difference(plugin_subcommands)
                 ^^^^^^^^^^^^^^^
      File "D:\ProgramData\anaconda3\Lib\site-packages\conda\cli\find_commands.py", line 71, in find_commands
        for entry in os.scandir(dir_path):
                     ^^^^^^^^^^^^^^^^^^^^
    OSError: [WinError 123] 文件名、目录名或卷标语法不正确。: '\u202aC:\\Users\\27590\\AppData\\Local\\pnpm\\pnpm.exe'

`$ D:\ProgramData\anaconda3\Scripts\conda-script.py info`


An unexpected error has occurred. Conda has prepared the above report.
If you suspect this error is being caused by a malfunctioning plugin,
consider using the --no-plugins option to turn off plugins.

Example: conda --no-plugins install <package>

Alternatively, you can set the CONDA_NO_PLUGINS environment variable on
the command line to run the command without plugins enabled.

Example: CONDA_NO_PLUGINS=true conda install <package>

If submitted, this report will be used by core maintainers to improve
future releases of conda.
Would you like conda to send this report to the core maintainers? [y/N]: y
```

### Conda config

```shell
C:\Users\27590>conda config --show-sources

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "D:\ProgramData\anaconda3\Lib\site-packages\conda\exception_handler.py", line 17, in __call__
        return func(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^
      File "D:\ProgramData\anaconda3\Lib\site-packages\conda\cli\main.py", line 54, in main_subshell
        parser = generate_parser(add_help=True)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "D:\ProgramData\anaconda3\Lib\site-packages\conda\cli\conda_argparse.py", line 127, in generate_parser
        configure_parser_plugins(sub_parsers)
      File "D:\ProgramData\anaconda3\Lib\site-packages\conda\cli\conda_argparse.py", line 354, in configure_parser_plugins
        else set(find_commands()).difference(plugin_subcommands)
                 ^^^^^^^^^^^^^^^
      File "D:\ProgramData\anaconda3\Lib\site-packages\conda\cli\find_commands.py", line 71, in find_commands
        for entry in os.scandir(dir_path):
                     ^^^^^^^^^^^^^^^^^^^^
    OSError: [WinError 123] 文件名、目录名或卷标语法不正确。: '\u202aC:\\Users\\27590\\AppData\\Local\\pnpm\\pnpm.exe'

`$ D:\ProgramData\anaconda3\Scripts\conda-script.py config --show-sources`

  environment variables:
                 CIO_TEST=<not set>
                CLASSPATH=.
               CONDA_ROOT=D:\ProgramData\anaconda3
                CUDA_PATH=D:\Program Files\NVIDIA GPU CorporationToolkit\CUDA\v12.2
           CURL_CA_BUNDLE=<not set>
                 HOMEPATH=\Users\27590
               LD_PRELOAD=<not set>
                NODE_PATH=D:\Program Files\nodejs\node_modules
                     PATH=D:\Program Files (x86)\VMware\VMware Workstation\bin\;D:\Program
                          Files\NVIDIA GPU CorporationToolkit\CUDA\v12.2\bin;D:\Program
                          Files\NVIDIA GPU CorporationToolkit\CUDA\v12.2\libnvvp;D:\Program
                          Files\Python310\Scripts\;D:\Program Files\Python310\;C:\Windows\system
                          32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowe
                          rShell\v1.0\;C:\Windows\System32\OpenSSH\;D:\Program
                          Files\Git\cmd;C:\Program Files\NVIDIA Corporation\Nsight Compute
                          2023.2.1\;C:\Program Files (x86)\NVIDIA
                          Corporation\PhysX\Common;C:\Program Files\NVIDIA Corporation\NVIDIA
                          NvDLISR;C:\Program Files (x86)\dotnet\;C:\Program
                          Files\dotnet\;D:\Programs\apache-maven-3.6.3\bin;D:\Program
                          Files\nodejs\;D:\Program Files\Redis\;D:\Program Files (x86)\platform-
                          tools;C:\Program Files\Bandizip\;C:\Program Files\Docker\Docker\resour
                          ces\bin;‪C:\Users\27590\AppData\Local\pnpm\pnpm.exe;‪C:\Users\27590\Ap
                          pData\Local\pnpm;D:\Programs\apache-flume\conf;D:\Programs\apache-flum
                          e\bin;D:\ProgramData\anaconda3;D:\ProgramData\anaconda3\Scripts;D:\Pro
                          gramData\anaconda3\Library\bin;D:\Code\jdks\openjdk-
                          21.0.1\bin;C:\Users\27590\AppData\Local\pnpm;C:\Program
                          Files\MySQL\MySQL Shell 8.0\bin\;C:\Users\27590\AppData\Local\Microsof
                          t\WindowsApps;;D:\Programs\Microsoft VS Code\bin;D:\Program
                          Files\Huawei\DevEco Studio\bin;;C:\Users\27590\AppData\Roaming\npm;C:\
                          Users\27590\AppData\Local\Microsoft\WinGet\Packages\Gyan.FFmpeg_Micros
                          oft.Winget.Source_8wekyb3d8bbwe\ffmpeg-6.0-full_build\bin;
             PSMODULEPATH=C:\Program Files\WindowsPowerShell\Modules;C:\Windows\system32\Windows
                          PowerShell\v1.0\Modules;C:\Windows\AtlasModules\Scripts\Modules;C:\Win
                          dows\AtlasModules\Scripts\Modules
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>

     active environment : None
       user config file : C:\Users\27590\.condarc
 populated config files :
          conda version : 23.7.4
    conda-build version : 3.26.1
         python version : 3.11.5.final.0
       virtual packages : __archspec=1=x86_64
                          __cuda=12.3=0
                          __win=0=0
       base environment : D:\ProgramData\anaconda3  (read only)
      conda av data dir : D:\ProgramData\anaconda3\etc\conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : D:\ProgramData\anaconda3\pkgs
                          C:\Users\27590\.conda\pkgs
                          C:\Users\27590\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\27590\.conda\envs
                          D:\ProgramData\anaconda3\envs
                          C:\Users\27590\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/23.7.4 requests/2.31.0 CPython/3.11.5 Windows/10 Windows/10.0.22631
          administrator : False
             netrc file : None
           offline mode : False


An unexpected error has occurred. Conda has prepared the above report.
If you suspect this error is being caused by a malfunctioning plugin,
consider using the --no-plugins option to turn off plugins.

Example: conda --no-plugins install <package>

Alternatively, you can set the CONDA_NO_PLUGINS environment variable on
the command line to run the command without plugins enabled.

Example: CONDA_NO_PLUGINS=true conda install <package>

If submitted, this report will be used by core maintainers to improve
future releases of conda.
Would you like conda to send this report to the core maintainers? [y/N]: y
```

### Conda list

```shell
C:\Users\27590>conda list --show-channel-urls

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "D:\ProgramData\anaconda3\Lib\site-packages\conda\exception_handler.py", line 17, in __call__
        return func(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^
      File "D:\ProgramData\anaconda3\Lib\site-packages\conda\cli\main.py", line 54, in main_subshell
        parser = generate_parser(add_help=True)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "D:\ProgramData\anaconda3\Lib\site-packages\conda\cli\conda_argparse.py", line 127, in generate_parser
        configure_parser_plugins(sub_parsers)
      File "D:\ProgramData\anaconda3\Lib\site-packages\conda\cli\conda_argparse.py", line 354, in configure_parser_plugins
        else set(find_commands()).difference(plugin_subcommands)
                 ^^^^^^^^^^^^^^^
      File "D:\ProgramData\anaconda3\Lib\site-packages\conda\cli\find_commands.py", line 71, in find_commands
        for entry in os.scandir(dir_path):
                     ^^^^^^^^^^^^^^^^^^^^
    OSError: [WinError 123] 文件名、目录名或卷标语法不正确。: '\u202aC:\\Users\\27590\\AppData\\Local\\pnpm\\pnpm.exe'

`$ D:\ProgramData\anaconda3\Scripts\conda-script.py list --show-channel-urls`

  environment variables:
                 CIO_TEST=<not set>
                CLASSPATH=.
               CONDA_ROOT=D:\ProgramData\anaconda3
                CUDA_PATH=D:\Program Files\NVIDIA GPU CorporationToolkit\CUDA\v12.2
           CURL_CA_BUNDLE=<not set>
                 HOMEPATH=\Users\27590
               LD_PRELOAD=<not set>
                NODE_PATH=D:\Program Files\nodejs\node_modules
                     PATH=D:\Program Files (x86)\VMware\VMware Workstation\bin\;D:\Program
                          Files\NVIDIA GPU CorporationToolkit\CUDA\v12.2\bin;D:\Program
                          Files\NVIDIA GPU CorporationToolkit\CUDA\v12.2\libnvvp;D:\Program
                          Files\Python310\Scripts\;D:\Program Files\Python310\;C:\Windows\system
                          32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowe
                          rShell\v1.0\;C:\Windows\System32\OpenSSH\;D:\Program
                          Files\Git\cmd;C:\Program Files\NVIDIA Corporation\Nsight Compute
                          2023.2.1\;C:\Program Files (x86)\NVIDIA
                          Corporation\PhysX\Common;C:\Program Files\NVIDIA Corporation\NVIDIA
                          NvDLISR;C:\Program Files (x86)\dotnet\;C:\Program
                          Files\dotnet\;D:\Programs\apache-maven-3.6.3\bin;D:\Program
                          Files\nodejs\;D:\Program Files\Redis\;D:\Program Files (x86)\platform-
                          tools;C:\Program Files\Bandizip\;C:\Program Files\Docker\Docker\resour
                          ces\bin;‪C:\Users\27590\AppData\Local\pnpm\pnpm.exe;‪C:\Users\27590\Ap
                          pData\Local\pnpm;D:\Programs\apache-flume\conf;D:\Programs\apache-flum
                          e\bin;D:\ProgramData\anaconda3;D:\ProgramData\anaconda3\Scripts;D:\Pro
                          gramData\anaconda3\Library\bin;D:\Code\jdks\openjdk-
                          21.0.1\bin;C:\Users\27590\AppData\Local\pnpm;C:\Program
                          Files\MySQL\MySQL Shell 8.0\bin\;C:\Users\27590\AppData\Local\Microsof
                          t\WindowsApps;;D:\Programs\Microsoft VS Code\bin;D:\Program
                          Files\Huawei\DevEco Studio\bin;;C:\Users\27590\AppData\Roaming\npm;C:\
                          Users\27590\AppData\Local\Microsoft\WinGet\Packages\Gyan.FFmpeg_Micros
                          oft.Winget.Source_8wekyb3d8bbwe\ffmpeg-6.0-full_build\bin;
             PSMODULEPATH=C:\Program Files\WindowsPowerShell\Modules;C:\Windows\system32\Windows
                          PowerShell\v1.0\Modules;C:\Windows\AtlasModules\Scripts\Modules;C:\Win
                          dows\AtlasModules\Scripts\Modules
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>

     active environment : None
       user config file : C:\Users\27590\.condarc
 populated config files :
          conda version : 23.7.4
    conda-build version : 3.26.1
         python version : 3.11.5.final.0
       virtual packages : __archspec=1=x86_64
                          __cuda=12.3=0
                          __win=0=0
       base environment : D:\ProgramData\anaconda3  (read only)
      conda av data dir : D:\ProgramData\anaconda3\etc\conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : D:\ProgramData\anaconda3\pkgs
                          C:\Users\27590\.conda\pkgs
                          C:\Users\27590\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\27590\.conda\envs
                          D:\ProgramData\anaconda3\envs
                          C:\Users\27590\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/23.7.4 requests/2.31.0 CPython/3.11.5 Windows/10 Windows/10.0.22631
          administrator : False
             netrc file : None
           offline mode : False


An unexpected error has occurred. Conda has prepared the above report.
If you suspect this error is being caused by a malfunctioning plugin,
consider using the --no-plugins option to turn off plugins.

Example: conda --no-plugins install <package>

Alternatively, you can set the CONDA_NO_PLUGINS environment variable on
the command line to run the command without plugins enabled.

Example: CONDA_NO_PLUGINS=true conda install <package>

If submitted, this report will be used by core maintainers to improve
future releases of conda.
Would you like conda to send this report to the core maintainers? [y/N]: y
```

### Additional Context

![bug](https://github.com/ContinuumIO/anaconda-issues/assets/53040718/51bf7fae-11f1-4ddc-a767-be1b4abc858f)

**Comment by LovemeLoveMeCode** [comment]
same problem
