### ISSUE TITLE
Navigation error on start-up

### ISSUE THREAD

**Issue by faridstage** [ContinuumIO/anaconda-issues#13312]
### Checklist

- [X] I added a descriptive title
- [X] I searched for other issues and couldn't find a solution or duplication
- [X] I already searched in Google and didn't find any good information or help
- [X] I looked at the [docs](https://docs.anaconda.com/anaconda/navigator/) and didn't see anything to help

### What happened?

i successfully installed anaconda and clicked next with auto lunch the app and it started corectly then when i closed it and reopend it again it gives me navigation error

navigation error 
an unexpected error occured on navigation start-up

main error
'bytes' objects has no attribute 'get'

and never opend 

when i open conda prompt and try to run any commant litrerly it gives me error 

### Conda info

```shell
# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "C:\Users\FARID\anaconda3\Lib\site-packages\conda\exception_handler.py", line 17, in __call__
        return func(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^
      File "C:\Users\FARID\anaconda3\Lib\site-packages\conda\cli\main.py", line 54, in main_subshell
        parser = generate_parser(add_help=True)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "C:\Users\FARID\anaconda3\Lib\site-packages\conda\cli\conda_argparse.py", line 127, in generate_parser
        configure_parser_plugins(sub_parsers)
      File "C:\Users\FARID\anaconda3\Lib\site-packages\conda\cli\conda_argparse.py", line 354, in configure_parser_plugins
        else set(find_commands()).difference(plugin_subcommands)
                 ^^^^^^^^^^^^^^^
      File "C:\Users\FARID\anaconda3\Lib\site-packages\conda\cli\find_commands.py", line 71, in find_commands
        for entry in os.scandir(dir_path):
                     ^^^^^^^^^^^^^^^^^^^^
    OSError: [WinError 123] The filename, directory name, or volume label syntax is incorrect: '"C:\\windows\\system32'

`$ C:\Users\FARID\anaconda3\Scripts\conda-script.py info`


An unexpected error has occurred. Conda has prepared the above report.
If you suspect this error is being caused by a malfunctioning plugin,
consider using the --no-plugins option to turn off plugins.

Example: conda --no-plugins install <package>

Alternatively, you can set the CONDA_NO_PLUGINS environment variable on
the command line to run the command without plugins enabled.

Example: CONDA_NO_PLUGINS=true conda install <package>

If submitted, this report will be used by core maintainers to improve
future releases of conda.
Would you like conda to send this report to the core maintainers? [y/N]:
```

### Conda config

```shell
environment variables:
                 CIO_TEST=<not set>
        CONDA_DEFAULT_ENV=base
                CONDA_EXE=C:\Users\FARID\anaconda3\condabin\..\Scripts\conda.exe
               CONDA_EXES="C:\Users\FARID\anaconda3\condabin\..\Scripts\conda.exe"
             CONDA_PREFIX=C:\Users\FARID\anaconda3
    CONDA_PROMPT_MODIFIER=(base)
         CONDA_PYTHON_EXE=C:\Users\FARID\anaconda3\python.exe
               CONDA_ROOT=C:\Users\FARID\anaconda3
              CONDA_SHLVL=1
           CURL_CA_BUNDLE=<not set>
                 HOMEPATH=\Users\FARID
               LD_PRELOAD=<not set>
                     PATH=C:\Users\FARID\anaconda3;C:\Users\FARID\anaconda3\Library\mingw-
                          w64\bin;C:\Users\FARID\anaconda3\Library\usr\bin;C:\Users\FARID\anacon
                          da3\Library\bin;C:\Users\FARID\anaconda3\Scripts;C:\Users\FARID\anacon
                          da3\bin;C:\Users\FARID\anaconda3\condabin;C:\Program Files\Common File
                          s\Oracle\Java\javapath;C:\ProgramData\Oracle\Java\javapath;C:\Program
                          Files\Microsoft MPI\Bin;C:\oraclexe\app\oracle\product\11.2.0\server\b
                          in;"C:\windows\system32;C:\xampp\htdocs\cars";C:\windows;C:\windows\Sy
                          stem32\Wbem;C:\windows\System32\WindowsPowerShell\v1.0;C:\windows\Syst
                          em32\OpenSSH;C:\Program Files (x86)\NVIDIA
                          Corporation\PhysX\Common;C:\Program Files\NVIDIA Corporation\NVIDIA
                          NvDLISR;C:\Program Files\Microsoft SQL Server\Client
                          SDK\ODBC\170\Tools\Binn;C:\Program Files (x86)\Microsoft SQL
                          Server\150\Tools\Binn;C:\Program Files\Microsoft SQL
                          Server\150\Tools\Binn;C:\Program Files\Microsoft SQL
                          Server\150\DTS\Binn;C:\Program Files (x86)\Microsoft SQL
                          Server\150\DTS\Binn;C:\Program Files\Azure Data Studio\bin;C:\Program
                          Files\Microsoft SQL Server\130\Tools\Binn;C:\Program
                          Files\php-8.0.9-nts-Win32-vs16-x64;C:\xampp\php;C:\Program
                          Files\Java\jdk-17.0.1\bin;C:\spark\bin;C:\Program Files
                          (x86)\Microsoft SQL Server\140\Tools\Binn;C:\Program Files\Microsoft
                          SQL Server\140\Tools\Binn;C:\Program Files (x86)\Microsoft SQL
                          Server\140\DTS\Binn;C:\Program Files\Microsoft SQL
                          Server\140\DTS\Binn;C:\Program Files\Microsoft SQL Server\Client SDK\O
                          DBC\130\Tools\Binn;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\
                          Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0;C:\WINDOWS\System32\Op
                          enSSH;C:\Program Files\Git\cmd;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDO
                          WS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0;C:\WINDOWS
                          \System32\OpenSSH;C:\Users\FARID\AppData\Roaming\nvm;C:\Program
                          Files\nodejs;C:\ProgramData\chocolatey\bin;C:\Program
                          Files\Docker\Docker\resources\bin;C:\Users\FARID\Downloads\youtube-
                          dl;D:\youtube-dl\bin;C:\Program Files\nodejs;C:\Program Files\dotnet;C
                          :\Users\FARID\Downloads\stripe_1.18.0_windows_x86_64;C:\php8;C:\Progra
                          mData\ComposerSetup\bin;C:\Users\FARID\anaconda3;C:\Users\FARID\anacon
                          da3\Library\mingw-
                          w64\bin;C:\Users\FARID\anaconda3\Library\usr\bin;C:\Users\FARID\anacon
                          da3\Library\bin;C:\Users\FARID\anaconda3\Scripts;C:\Program
                          Files\MySQL\MySQL Shell 8.0\bin;C:\Users\FARID\AppData\Local\Microsoft
                          \WindowsApps;C:\Users\FARID\AppData\Local\Programs\Microsoft VS
                          Code\bin;C:\Program Files\Azure Data
                          Studio\bin;C:\XAMPP\php;C:\xampp\htdocs\cars;C:\Program
                          Files\Java\jdk-17.0.1\bin;C:\spark\bin;C:\Program
                          Files\JetBrains\PyCharm Community Edition
                          2023.1\bin;.;C:\Users\FARID\AppData\Roaming\nvm;C:\Program
                          Files\nodejs;C:\Program Files\Java\jdk-
                          20\bin;C:\Users\FARID\AppData\Roaming\npm;C:\Users\FARID\.dotnet\tools
                          ;C:\Users\FARID\Downloads\stripe_1.18.0_windows_x86_64;C:\Users\FARID\
                          AppData\Roaming\Composer\vendor\bin;C:\Program Files\JetBrains\PyCharm
                          2023.3.1\bin;.
             PSMODULEPATH=C:\Program Files\WindowsPowerShell\Modules;C:\WINDOWS\system32\Windows
                          PowerShell\v1.0\Modules;C:\Program Files (x86)\Microsoft SQL
                          Server\150\Tools\PowerShell\Modules\;C:\Program Files (x86)\Microsoft
                          SQL Server\140\Tools\PowerShell\Modules\
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=C:\Users\FARID\anaconda3\Library\ssl\cacert.pem

     active environment : base
    active env location : C:\Users\FARID\anaconda3
            shell level : 1
       user config file : C:\Users\FARID\.condarc
 populated config files : C:\Users\FARID\.condarc
          conda version : 23.7.4
    conda-build version : 3.26.1
         python version : 3.11.5.final.0
       virtual packages : __archspec=1=x86_64
                          __cuda=12.2=0
                          __win=0=0
       base environment : C:\Users\FARID\anaconda3  (writable)
      conda av data dir : C:\Users\FARID\anaconda3\etc\conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\Users\FARID\anaconda3\pkgs
                          C:\Users\FARID\.conda\pkgs
                          C:\Users\FARID\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\FARID\anaconda3\envs
                          C:\Users\FARID\.conda\envs
                          C:\Users\FARID\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/23.7.4 requests/2.31.0 CPython/3.11.5 Windows/10 Windows/10.0.22621
          administrator : False
             netrc file : None
           offline mode : False


An unexpected error has occurred. Conda has prepared the above report.
If you suspect this error is being caused by a malfunctioning plugin,
consider using the --no-plugins option to turn off plugins.

Example: conda --no-plugins install <package>

Alternatively, you can set the CONDA_NO_PLUGINS environment variable on
the command line to run the command without plugins enabled.

Example: CONDA_NO_PLUGINS=true conda install <package>

If submitted, this report will be used by core maintainers to improve
future releases of conda.
Would you like conda to send this report to the core maintainers? [y/N]:
```

### Conda list

```shell
environment variables:
                 CIO_TEST=<not set>
        CONDA_DEFAULT_ENV=base
                CONDA_EXE=C:\Users\FARID\anaconda3\condabin\..\Scripts\conda.exe
               CONDA_EXES="C:\Users\FARID\anaconda3\condabin\..\Scripts\conda.exe"
             CONDA_PREFIX=C:\Users\FARID\anaconda3
    CONDA_PROMPT_MODIFIER=(base)
         CONDA_PYTHON_EXE=C:\Users\FARID\anaconda3\python.exe
               CONDA_ROOT=C:\Users\FARID\anaconda3
              CONDA_SHLVL=1
           CURL_CA_BUNDLE=<not set>
                 HOMEPATH=\Users\FARID
               LD_PRELOAD=<not set>
                     PATH=C:\Users\FARID\anaconda3;C:\Users\FARID\anaconda3\Library\mingw-
                          w64\bin;C:\Users\FARID\anaconda3\Library\usr\bin;C:\Users\FARID\anacon
                          da3\Library\bin;C:\Users\FARID\anaconda3\Scripts;C:\Users\FARID\anacon
                          da3\bin;C:\Users\FARID\anaconda3\condabin;C:\Program Files\Common File
                          s\Oracle\Java\javapath;C:\ProgramData\Oracle\Java\javapath;C:\Program
                          Files\Microsoft MPI\Bin;C:\oraclexe\app\oracle\product\11.2.0\server\b
                          in;"C:\windows\system32;C:\xampp\htdocs\cars";C:\windows;C:\windows\Sy
                          stem32\Wbem;C:\windows\System32\WindowsPowerShell\v1.0;C:\windows\Syst
                          em32\OpenSSH;C:\Program Files (x86)\NVIDIA
                          Corporation\PhysX\Common;C:\Program Files\NVIDIA Corporation\NVIDIA
                          NvDLISR;C:\Program Files\Microsoft SQL Server\Client
                          SDK\ODBC\170\Tools\Binn;C:\Program Files (x86)\Microsoft SQL
                          Server\150\Tools\Binn;C:\Program Files\Microsoft SQL
                          Server\150\Tools\Binn;C:\Program Files\Microsoft SQL
                          Server\150\DTS\Binn;C:\Program Files (x86)\Microsoft SQL
                          Server\150\DTS\Binn;C:\Program Files\Azure Data Studio\bin;C:\Program
                          Files\Microsoft SQL Server\130\Tools\Binn;C:\Program
                          Files\php-8.0.9-nts-Win32-vs16-x64;C:\xampp\php;C:\Program
                          Files\Java\jdk-17.0.1\bin;C:\spark\bin;C:\Program Files
                          (x86)\Microsoft SQL Server\140\Tools\Binn;C:\Program Files\Microsoft
                          SQL Server\140\Tools\Binn;C:\Program Files (x86)\Microsoft SQL
                          Server\140\DTS\Binn;C:\Program Files\Microsoft SQL
                          Server\140\DTS\Binn;C:\Program Files\Microsoft SQL Server\Client SDK\O
                          DBC\130\Tools\Binn;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\
                          Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0;C:\WINDOWS\System32\Op
                          enSSH;C:\Program Files\Git\cmd;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDO
                          WS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0;C:\WINDOWS
                          \System32\OpenSSH;C:\Users\FARID\AppData\Roaming\nvm;C:\Program
                          Files\nodejs;C:\ProgramData\chocolatey\bin;C:\Program
                          Files\Docker\Docker\resources\bin;C:\Users\FARID\Downloads\youtube-
                          dl;D:\youtube-dl\bin;C:\Program Files\nodejs;C:\Program Files\dotnet;C
                          :\Users\FARID\Downloads\stripe_1.18.0_windows_x86_64;C:\php8;C:\Progra
                          mData\ComposerSetup\bin;C:\Users\FARID\anaconda3;C:\Users\FARID\anacon
                          da3\Library\mingw-
                          w64\bin;C:\Users\FARID\anaconda3\Library\usr\bin;C:\Users\FARID\anacon
                          da3\Library\bin;C:\Users\FARID\anaconda3\Scripts;C:\Program
                          Files\MySQL\MySQL Shell 8.0\bin;C:\Users\FARID\AppData\Local\Microsoft
                          \WindowsApps;C:\Users\FARID\AppData\Local\Programs\Microsoft VS
                          Code\bin;C:\Program Files\Azure Data
                          Studio\bin;C:\XAMPP\php;C:\xampp\htdocs\cars;C:\Program
                          Files\Java\jdk-17.0.1\bin;C:\spark\bin;C:\Program
                          Files\JetBrains\PyCharm Community Edition
                          2023.1\bin;.;C:\Users\FARID\AppData\Roaming\nvm;C:\Program
                          Files\nodejs;C:\Program Files\Java\jdk-
                          20\bin;C:\Users\FARID\AppData\Roaming\npm;C:\Users\FARID\.dotnet\tools
                          ;C:\Users\FARID\Downloads\stripe_1.18.0_windows_x86_64;C:\Users\FARID\
                          AppData\Roaming\Composer\vendor\bin;C:\Program Files\JetBrains\PyCharm
                          2023.3.1\bin;.
             PSMODULEPATH=C:\Program Files\WindowsPowerShell\Modules;C:\WINDOWS\system32\Windows
                          PowerShell\v1.0\Modules;C:\Program Files (x86)\Microsoft SQL
                          Server\150\Tools\PowerShell\Modules\;C:\Program Files (x86)\Microsoft
                          SQL Server\140\Tools\PowerShell\Modules\
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=C:\Users\FARID\anaconda3\Library\ssl\cacert.pem

     active environment : base
    active env location : C:\Users\FARID\anaconda3
            shell level : 1
       user config file : C:\Users\FARID\.condarc
 populated config files : C:\Users\FARID\.condarc
          conda version : 23.7.4
    conda-build version : 3.26.1
         python version : 3.11.5.final.0
       virtual packages : __archspec=1=x86_64
                          __cuda=12.2=0
                          __win=0=0
       base environment : C:\Users\FARID\anaconda3  (writable)
      conda av data dir : C:\Users\FARID\anaconda3\etc\conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\Users\FARID\anaconda3\pkgs
                          C:\Users\FARID\.conda\pkgs
                          C:\Users\FARID\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\FARID\anaconda3\envs
                          C:\Users\FARID\.conda\envs
                          C:\Users\FARID\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/23.7.4 requests/2.31.0 CPython/3.11.5 Windows/10 Windows/10.0.22621
          administrator : False
             netrc file : None
           offline mode : False


An unexpected error has occurred. Conda has prepared the above report.
If you suspect this error is being caused by a malfunctioning plugin,
consider using the --no-plugins option to turn off plugins.

Example: conda --no-plugins install <package>

Alternatively, you can set the CONDA_NO_PLUGINS environment variable on
the command line to run the command without plugins enabled.

Example: CONDA_NO_PLUGINS=true conda install <package>

If submitted, this report will be used by core maintainers to improve
future releases of conda.
Would you like conda to send this report to the core maintainers? [y/N]:
```

**Comment by IronK109** [comment]
maaaaaaaaaaaaaaan im having the same issue do u know how to fix it

**Comment by abdelhalem20fathi** [comment]
how can i fix it

**Comment by Seoe-Tsalong** [comment]
I have the same problem. any solution?

**Comment by EdnaEze** [comment]
Having the same problem.

**Comment by mamatakumaridevi** [comment]
Facing the same issue. Any solution?
