### ISSUE TITLE
Navigator Start Error

### ISSUE THREAD

**Issue by wing-li-dfs** [ContinuumIO/anaconda-issues#13335]
### Checklist

- [X] I added a descriptive title
- [X] I searched for other issues and couldn't find a solution or duplication
- [X] I already searched in Google and didn't find any good information or help
- [X] I looked at the [docs](https://docs.anaconda.com/anaconda/navigator/) and didn't see anything to help

### What happened?

open "Anaconda Navigator", and there's navigator error

![anaconda_error](https://github.com/ContinuumIO/anaconda-issues/assets/142477117/352b395a-c8a6-42cb-b636-6fc8546eff33)

### Conda info

```shell
# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "C:\Users\WL2235539\AppData\Local\anaconda3\Lib\site-packages\conda\exception_handler.py", line 17, in __call__
        return func(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^
      File "C:\Users\WL2235539\AppData\Local\anaconda3\Lib\site-packages\conda\cli\main.py", line 54, in main_subshell
        parser = generate_parser(add_help=True)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "C:\Users\WL2235539\AppData\Local\anaconda3\Lib\site-packages\conda\cli\conda_argparse.py", line 127, in generate_parser
        configure_parser_plugins(sub_parsers)
      File "C:\Users\WL2235539\AppData\Local\anaconda3\Lib\site-packages\conda\cli\conda_argparse.py", line 354, in configure_parser_plugins
        else set(find_commands()).difference(plugin_subcommands)
                 ^^^^^^^^^^^^^^^
      File "C:\Users\WL2235539\AppData\Local\anaconda3\Lib\site-packages\conda\cli\find_commands.py", line 71, in find_commands
        for entry in os.scandir(dir_path):
                     ^^^^^^^^^^^^^^^^^^^^
    OSError: [WinError 123] The filename, directory name, or volume label syntax is incorrect: 'C:\\UsersC:\\Users\\WL2235539\\AppData\\Local\\anaconda3'

`$ C:\Users\WL2235539\AppData\Local\anaconda3\Scripts\conda-script.py info`


An unexpected error has occurred. Conda has prepared the above report.
If you suspect this error is being caused by a malfunctioning plugin,
consider using the --no-plugins option to turn off plugins.

Example: conda --no-plugins install <package>

Alternatively, you can set the CONDA_NO_PLUGINS environment variable on
the command line to run the command without plugins enabled.

Example: CONDA_NO_PLUGINS=true conda install <package>

If submitted, this report will be used by core maintainers to improve
future releases of conda.
Would you like conda to send this report to the core maintainers? [y/N]:
```

### Conda config

```shell
environment variables:
                 CIO_TEST=<not set>
        CONDA_DEFAULT_ENV=base
                CONDA_EXE=C:\Users\WL2235539\AppData\Local\anaconda3\condabin\..\Scripts\conda.e
                          xe
               CONDA_EXES="C:\Users\WL2235539\AppData\Local\anaconda3\condabin\..\Scripts\conda.
                          exe"
             CONDA_PREFIX=C:\Users\WL2235539\AppData\Local\anaconda3
    CONDA_PROMPT_MODIFIER=(base)
         CONDA_PYTHON_EXE=C:\Users\WL2235539\AppData\Local\anaconda3\python.exe
               CONDA_ROOT=C:\Users\WL2235539\AppData\Local\anaconda3
              CONDA_SHLVL=1
           CURL_CA_BUNDLE=<not set>
                 HOMEPATH=\Users\WL2235539
               LD_PRELOAD=<not set>
                     PATH=C:\Users\WL2235539\AppData\Local\anaconda3;C:\Users\WL2235539\AppData\
                          Local\anaconda3\Library\mingw-
                          w64\bin;C:\Users\WL2235539\AppData\Local\anaconda3\Library\usr\bin;C:\
                          Users\WL2235539\AppData\Local\anaconda3\Library\bin;C:\Users\WL2235539
                          \AppData\Local\anaconda3\Scripts;C:\Users\WL2235539\AppData\Local\anac
                          onda3\bin;C:\Users\WL2235539\AppData\Local\anaconda3\condabin;C:\Progr
                          amData\Oracle\Java\javapath;C:\Program Files (x86)\IBM\EHLLAPI;C:\wind
                          ows\system32;C:\windows;C:\windows\System32\Wbem;C:\windows\System32\W
                          indowsPowerShell\v1.0;C:\windows\System32\OpenSSH;C:\Program Files
                          (x86)\IBM\Client Access\Emulator;C:\Program Files (x86)\IBM\Client
                          Access\Shared;C:\Program Files (x86)\IBM\Client Access;C:\Program
                          Files\dotnet;C:\ProgramData\Oracle\Java\javapath;C:\Program Files (x86
                          )\IBM\EHLLAPI;C:\windows\system32;C:\windows;C:\windows\System32\Wbem;
                          C:\windows\System32\WindowsPowerShell\v1.0;C:\windows\System32\OpenSSH
                          ;C:\Program Files (x86)\IBM\Client Access\Emulator;C:\Program Files
                          (x86)\IBM\Client Access\Shared;C:\Program Files (x86)\IBM\Client
                          Access;C:\Program Files\dotnet;C:\Users\WL2235539\AppData\Local\Micros
                          oft\WindowsApps;.;C:\UsersC:\Users\WL2235539\AppData\Local\anaconda3;C
                          :\Users\WL2235539\AppData\Local\Programs\Microsoft VS Code\bin
             PSMODULEPATH=C:\Program Files\WindowsPowerShell\Modules;C:\windows\system32\Windows
                          PowerShell\v1.0\Modules
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=C:\Users\WL2235539\AppData\Local\anaconda3\Library\ssl\cacert.pem

     active environment : base
    active env location : C:\Users\WL2235539\AppData\Local\anaconda3
            shell level : 1
       user config file : C:\Users\WL2235539\.condarc
 populated config files : C:\Users\WL2235539\.condarc
          conda version : 23.7.4
    conda-build version : 3.26.1
         python version : 3.11.5.final.0
       virtual packages : __archspec=1=x86_64
                          __win=0=0
       base environment : C:\Users\WL2235539\AppData\Local\anaconda3  (writable)
      conda av data dir : C:\Users\WL2235539\AppData\Local\anaconda3\etc\conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\Users\WL2235539\AppData\Local\anaconda3\pkgs
                          C:\Users\WL2235539\.conda\pkgs
                          C:\Users\WL2235539\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\WL2235539\AppData\Local\anaconda3\envs
                          C:\Users\WL2235539\.conda\envs
                          C:\Users\WL2235539\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/23.7.4 requests/2.31.0 CPython/3.11.5 Windows/10 Windows/10.0.19044
          administrator : False
             netrc file : None
           offline mode : False


An unexpected error has occurred. Conda has prepared the above report.
If you suspect this error is being caused by a malfunctioning plugin,
consider using the --no-plugins option to turn off plugins.

Example: conda --no-plugins install <package>

Alternatively, you can set the CONDA_NO_PLUGINS environment variable on
the command line to run the command without plugins enabled.

Example: CONDA_NO_PLUGINS=true conda install <package>

If submitted, this report will be used by core maintainers to improve
future releases of conda.
Would you like conda to send this report to the core maintainers? [y/N]:
```

### Conda list

```shell
environment variables:
                 CIO_TEST=<not set>
        CONDA_DEFAULT_ENV=base
                CONDA_EXE=C:\Users\WL2235539\AppData\Local\anaconda3\condabin\..\Scripts\conda.e
                          xe
               CONDA_EXES="C:\Users\WL2235539\AppData\Local\anaconda3\condabin\..\Scripts\conda.
                          exe"
             CONDA_PREFIX=C:\Users\WL2235539\AppData\Local\anaconda3
    CONDA_PROMPT_MODIFIER=(base)
         CONDA_PYTHON_EXE=C:\Users\WL2235539\AppData\Local\anaconda3\python.exe
               CONDA_ROOT=C:\Users\WL2235539\AppData\Local\anaconda3
              CONDA_SHLVL=1
           CURL_CA_BUNDLE=<not set>
                 HOMEPATH=\Users\WL2235539
               LD_PRELOAD=<not set>
                     PATH=C:\Users\WL2235539\AppData\Local\anaconda3;C:\Users\WL2235539\AppData\
                          Local\anaconda3\Library\mingw-
                          w64\bin;C:\Users\WL2235539\AppData\Local\anaconda3\Library\usr\bin;C:\
                          Users\WL2235539\AppData\Local\anaconda3\Library\bin;C:\Users\WL2235539
                          \AppData\Local\anaconda3\Scripts;C:\Users\WL2235539\AppData\Local\anac
                          onda3\bin;C:\Users\WL2235539\AppData\Local\anaconda3\condabin;C:\Progr
                          amData\Oracle\Java\javapath;C:\Program Files (x86)\IBM\EHLLAPI;C:\wind
                          ows\system32;C:\windows;C:\windows\System32\Wbem;C:\windows\System32\W
                          indowsPowerShell\v1.0;C:\windows\System32\OpenSSH;C:\Program Files
                          (x86)\IBM\Client Access\Emulator;C:\Program Files (x86)\IBM\Client
                          Access\Shared;C:\Program Files (x86)\IBM\Client Access;C:\Program
                          Files\dotnet;C:\ProgramData\Oracle\Java\javapath;C:\Program Files (x86
                          )\IBM\EHLLAPI;C:\windows\system32;C:\windows;C:\windows\System32\Wbem;
                          C:\windows\System32\WindowsPowerShell\v1.0;C:\windows\System32\OpenSSH
                          ;C:\Program Files (x86)\IBM\Client Access\Emulator;C:\Program Files
                          (x86)\IBM\Client Access\Shared;C:\Program Files (x86)\IBM\Client
                          Access;C:\Program Files\dotnet;C:\Users\WL2235539\AppData\Local\Micros
                          oft\WindowsApps;.;C:\UsersC:\Users\WL2235539\AppData\Local\anaconda3;C
                          :\Users\WL2235539\AppData\Local\Programs\Microsoft VS Code\bin
             PSMODULEPATH=C:\Program Files\WindowsPowerShell\Modules;C:\windows\system32\Windows
                          PowerShell\v1.0\Modules
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=C:\Users\WL2235539\AppData\Local\anaconda3\Library\ssl\cacert.pem

     active environment : base
    active env location : C:\Users\WL2235539\AppData\Local\anaconda3
            shell level : 1
       user config file : C:\Users\WL2235539\.condarc
 populated config files : C:\Users\WL2235539\.condarc
          conda version : 23.7.4
    conda-build version : 3.26.1
         python version : 3.11.5.final.0
       virtual packages : __archspec=1=x86_64
                          __win=0=0
       base environment : C:\Users\WL2235539\AppData\Local\anaconda3  (writable)
      conda av data dir : C:\Users\WL2235539\AppData\Local\anaconda3\etc\conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\Users\WL2235539\AppData\Local\anaconda3\pkgs
                          C:\Users\WL2235539\.conda\pkgs
                          C:\Users\WL2235539\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\WL2235539\AppData\Local\anaconda3\envs
                          C:\Users\WL2235539\.conda\envs
                          C:\Users\WL2235539\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/23.7.4 requests/2.31.0 CPython/3.11.5 Windows/10 Windows/10.0.19044
          administrator : False
             netrc file : None
           offline mode : False


An unexpected error has occurred. Conda has prepared the above report.
If you suspect this error is being caused by a malfunctioning plugin,
consider using the --no-plugins option to turn off plugins.

Example: conda --no-plugins install <package>

Alternatively, you can set the CONDA_NO_PLUGINS environment variable on
the command line to run the command without plugins enabled.

Example: CONDA_NO_PLUGINS=true conda install <package>

If submitted, this report will be used by core maintainers to improve
future releases of conda.
```

**Comment by muxia777** [comment]
怎么解决的？

**Comment by Sadhik2299** [comment]
I'm also facing the same issue, it will be very helpful if someone resolves the issue.
