### ISSUE TITLE
Install script: Nondescriptive error on full disk

### ISSUE THREAD

**Issue by smurfix** [ContinuumIO/anaconda-issues#13334]
### Checklist

- [X] I added a descriptive title.
- [X] I searched through [existing issues](https://github.com/ContinuumIO/anaconda-issues/issues) and couldn't find a solution or duplicate issue.
- [X] I searched on the web (e.g. Google) and didn't find any helpful information.
- [X] I searched the [Anaconda documentation](https://docs.anaconda.com/) and didn't find any helpful information.

### Impacted product

- [ ] A conda package (built by Anaconda)
- [X] Anaconda Distribution (formerly Anaconda Individual Edition)
- [ ] Miniconda
- [ ] Anaconda.org

### What happened?

Installing to a full partition results in an error. The problem is that the error handling code is broken.

### Expected behavior or outcome

Some output to stderr that contains the words "disk/partition" and "full/out of space".

### Conda info

```shell
n/a

Installer Anaconda3-2023.09-0-Linux-x86_64.sh
```

### Conda config

```shell
n/a
```

### Conda list

```shell
n/a
```

### Additional information

```
Unpacking payload ...
concurrent.futures.process._RemoteTraceback:
'''
Traceback (most recent call last):
  File "concurrent/futures/process.py", line 387, in wait_result_broken_or_wakeup
  File "multiprocessing/connection.py", line 256, in recv
TypeError: __init__() missing 1 required positional argument: 'msg'
'''

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "entry_point.py", line 69, in <module>
  File "concurrent/futures/process.py", line 562, in _chain_from_iterable_of_lists
  File "concurrent/futures/_base.py", line 609, in result_iterator
  File "concurrent/futures/_base.py", line 446, in result
  File "concurrent/futures/_base.py", line 391, in __get_result
concurrent.futures.process.BrokenProcessPool: A process in the process pool was terminated abruptly while the future was running or pending.
[30081] Failed to execute script 'entry_point' due to unhandled exception!
```

**Comment by marcoesters** [comment]
Thank you for reporting this! I filed issues with the appropriate projects to get these features implemented in the future.

**Comment by smurfix** [comment]
Note that the `TypeError` I quoted above also needs to be addressed. The code path for remote error handling and propagation that falls on its face here should be covered by some test script or other …
