### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by hannahl37** [ContinuumIO/anaconda-issues#13436]
### Checklist

- [X] I added a descriptive title.
- [X] I searched through [existing issues](https://github.com/ContinuumIO/anaconda-issues/issues) and couldn't find a solution or duplicate issue.
- [X] I searched on the web (e.g. Google) and didn't find any helpful information.
- [X] I searched the [Anaconda documentation](https://docs.anaconda.com/) and didn't find any helpful information.

### Impacted product

- [X] A conda package (built by Anaconda)
- [ ] Anaconda Distribution (formerly Anaconda Individual Edition)
- [ ] Miniconda
- [ ] Anaconda.org

### What happened?

Cannot launch navigator.  Upon launching navigator, I got these errors.
Navigator Error
An unexpected error occurred on Navigator start-up

Report
Please report this issue in the anaconda [issue tracker](https://github.com/continuumio/anaconda-issues)

Main Error
('Service Unavailable: The server cannot process the request due to a high load ([GET] https://api.anaconda.org/user -> 503)', 503)
Traceback
Traceback (most recent call last):
  File "C:\Users\Lambrusc\Anaconda3\lib\site-packages\anaconda_navigator\exceptions.py", line 74, in exception_handler
    return_value = func(*args, **kwargs)
  File "C:\Users\Lambrusc\Anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 137, in start_app
    window = run_app(splash)
  File "C:\Users\Lambrusc\Anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 60, in run_app
    window = MainWindow(splash=splash)
  File "C:\Users\Lambrusc\Anaconda3\lib\site-packages\anaconda_navigator\widgets\main_window\__init__.py", line 228, in __init__
    self.api = AnacondaAPI()
  File "C:\Users\Lambrusc\Anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 1116, in AnacondaAPI
    ANACONDA_API = _AnacondaAPI()
  File "C:\Users\Lambrusc\Anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 70, in __init__
    self._client_api = ClientAPI(config=self.config)
  File "C:\Users\Lambrusc\Anaconda3\lib\site-packages\anaconda_navigator\api\client_api.py", line 645, in ClientAPI
    CLIENT_API = _ClientAPI(config=config)
  File "C:\Users\Lambrusc\Anaconda3\lib\site-packages\anaconda_navigator\api\client_api.py", line 100, in __init__
    self.reload_client()
  File "C:\Users\Lambrusc\Anaconda3\lib\site-packages\anaconda_navigator\api\client_api.py", line 314, in reload_client
    client.user()
  File "C:\Users\Lambrusc\Anaconda3\lib\site-packages\binstar_client\__init__.py", line 242, in user
    self._check_response(res)
  File "C:\Users\Lambrusc\Anaconda3\lib\site-packages\binstar_client\__init__.py", line 227, in _check_response
    raise ErrCls(msg, res.status_code)
binstar_client.errors.ServerError: ('Service Unavailable: The server cannot process the request due to a high load ([GET] https://api.anaconda.org/user -> 503)', 503)

### Expected behavior or outcome

Navigator should launch without an issue

**Comment by prc-tech** [comment]
Identical issue, Fresh install  with the following

report

Navigator Error

An unexpected error occurred on Navigator start-up

Report

Please report this issue in the anaconda [issue tracker](https://github.com/ContinuumIO/anaconda-issues/issues)

Main Error

Unable to configure handler 'file'
Traceback

Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.12/logging/config.py", line 608, in configure
    handler = self.configure_handler(handlers[name])
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/logging/config.py", line 876, in configure_handler
    result = factory(**kwargs)
             ^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/logging/handlers.py", line 155, in __init__
    BaseRotatingHandler.__init__(self, filename, mode, encoding=encoding,
  File "/opt/anaconda3/lib/python3.12/logging/handlers.py", line 58, in __init__
    logging.FileHandler.__init__(self, filename, mode=mode,
  File "/opt/anaconda3/lib/python3.12/logging/__init__.py", line 1231, in __init__
    StreamHandler.__init__(self, self._open())
                                 ^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/logging/__init__.py", line 1263, in _open
    return open_func(self.baseFilename, self.mode,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
PermissionError: [Errno 1] Operation not permitted: '/Users/pc/.anaconda/navigator/logs/navigator.log'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.12/site-packages/anaconda_navigator/exceptions.py", line 109, in exception_handler
    return_value = func(*args, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/site-packages/anaconda_navigator/app/start.py", line 105, in start_app
    setup_logger()
  File "/opt/anaconda3/lib/python3.12/site-packages/anaconda_navigator/utils/logs/__init__.py", line 25, in setup_logger
    logging.config.dictConfig(LOGGER_CONFIG.dict_config)
  File "/opt/anaconda3/lib/python3.12/logging/config.py", line 942, in dictConfig
    dictConfigClass(config).configure()
  File "/opt/anaconda3/lib/python3.12/logging/config.py", line 615, in configure
    raise ValueError('Unable to configure handler '
ValueError: Unable to configure handler 'file'


My system -   Model Name:	MacBook Pro
  Model Identifier:	MacBookPro17,1
  Model Number:	MYD82B/A
  Chip:	Apple M1
  Total Number of Cores:	8 (4 performance and 4 efficiency)
  Memory:	8 GB
  System Firmware Version:	11881.41.5
  OS Loader Version:	11881.41.5
  Activation Lock Status:	Enabled
