### ISSUE TITLE
binstar cli built for python 3.3 doesn't work

### ISSUE THREAD

**Issue by mwiebe** [ContinuumIO/anaconda-issues#135]
Here's what it does:

```
D:\>binstar
Traceback (most recent call last):
  File "C:\Users\mwiebe\Anaconda\Scripts\binstar-script.py", line 3, in <module>
    from binstar_client.scripts.cli import main
  File "C:\Users\mwiebe\Anaconda\lib\site-packages\binstar-0.4.1-py3.3.egg\binstar_client\__init__.py", line 401
    print s3res.text
              ^
SyntaxError: invalid syntax

D:\>conda list binstar
# packages in environment at C:\Users\mwiebe\Anaconda:
#
binstar                   0.5.3                    py33_0
```

**Comment by csoja** [comment]
no longer relevant.
