### ISSUE TITLE
Problem with graphviz

### ISSUE THREAD

**Issue by gvaria1** [ContinuumIO/anaconda-issues#1357]
Dear all, 

I am trying to visualize a decision tree with graph_viz and I am getting the following error:

> InvocationException: Program terminated with status: 1. stderr follows: Warning: Could not load "/home/moritz/Python/anaconda3/lib/graphviz/libgvplugin_pango.so.6" - file not found
Warning: Could not load "/home/moritz/Python/anaconda3/lib/graphviz/libgvplugin_pango.so.6" - file not found
Format: "pdf" not recognized. Use one of: canon cmap cmapx cmapx_np dot eps fig gv imap imap_np ismap pdf pic plain plain-ext png pov ps ps2 svg svgz tk vml vmlz xdot xdot1.2 xdot1.4

I would be grateful, if you could provide some help. Many thanks dkl

**Comment by naveendennis** [comment]
Hi Everyone,

I am also getting the same error.

Traceback (most recent call last):
```
  File "read_amazon_dataset.py", line 123, in <module>
    Image(graph.create_png())
  File "/home/dennis/anaconda3/lib/python3.5/site-packages/pydotplus/graphviz.py", line 1797, in <lambda>
    lambda f=frmt, prog=self.prog: self.create(format=f, prog=prog)
  File "/home/dennis/anaconda3/lib/python3.5/site-packages/pydotplus/graphviz.py", line 2032, in create
    status, stderr_output))
pydotplus.graphviz.InvocationException: Program terminated with status: 1. stderr follows: Warning: Could not load "/home/dennis/anaconda3/lib/graphviz/libgvplugin_pango.so.6" - file not found
Warning: Could not load "/home/dennis/anaconda3/lib/graphviz/libgvplugin_pango.so.6" - file not found
Format: "png" not recognized. Use one of: canon cmap cmapx cmapx_np dot eps fig gv imap imap_np ismap pdf pic plain plain-ext png pov ps ps2 svg svgz tk vml vmlz xdot xdot1.2 xdot1.4
```

And when I try to use `graph.create_fig()` instead of `graph.create_png()`, the file _"/home/dennis/anaconda3/lib/graphviz/libgvplugin_pango.so.6"_ could not be loaded event though it exists in the directory.

The directory structure of the graphviz directory is shown below:

.
├── config6
├── libgvplugin_core.la
├── libgvplugin_core.so -> libgvplugin_core.so.6.0.0
├── libgvplugin_core.so.6 -> libgvplugin_core.so.6.0.0
├── libgvplugin_core.so.6.0.0
├── libgvplugin_dot_layout.la
├── libgvplugin_dot_layout.so -> libgvplugin_dot_layout.so.6.0.0
├── libgvplugin_dot_layout.so.6 -> libgvplugin_dot_layout.so.6.0.0
├── libgvplugin_dot_layout.so.6.0.0
├── libgvplugin_neato_layout.la
├── libgvplugin_neato_layout.so -> libgvplugin_neato_layout.so.6.0.0
├── libgvplugin_neato_layout.so.6 -> libgvplugin_neato_layout.so.6.0.0
├── libgvplugin_neato_layout.so.6.0.0
├── libgvplugin_pango.la
├── libgvplugin_pango.so -> libgvplugin_pango.so.6.0.0
├── libgvplugin_pango.so.6 -> libgvplugin_pango.so.6.0.0
└── libgvplugin_pango.so.6.0.0

**Comment by ijstokes** [comment]
Same here.  Python 3.5 on Linux 64.  For me the weird thing is that the file reported as missing is totally there (in my case).

```
InvocationException: Program terminated with status: 1. stderr follows: Warning: Could not load "/projects/demo/deeplearn/envs/default/lib/graphviz/libgvplugin_pango.so.6" - file not found
Warning: Could not load "/projects/demo/deeplearn/envs/default/lib/graphviz/libgvplugin_pango.so.6" - file not found
Format: "png" not recognized. Use one of: canon cmap cmapx cmapx_np dot eps fig gv imap imap_np ismap pdf pic plain plain-ext png pov ps ps2 svg svgz tk vml vmlz xdot xdot1.2 xdot1.4
```

And here are the supposedly missing files:

```
$ ls -Fla /projects/demo/deeplearn/envs/default/lib/graphviz/libgvplugin_pango.so.6*                                                                                        
lrwxrwxrwx  1 demo demo     26 Mar  3 11:10
/projects/demo/deeplearn/envs/default/lib/graphviz/libgvplugin_pango.so.6 -> libgvplugin_pango.so.6.0.0*
-rwxrwxr-x+ 1 demo demo 134468 Mar  3 11:10 /projects/demo/deeplearn/envs/default/lib/graphviz/libgvplugin_pango.so.6.0.0*
```

And here is `ldd` output for `dot` (which I assume is what is being invoked):

```
$ which dot
/projects/demo/deeplearn/envs/dnn/bin/dot                                                                                                                                            

$ ldd `which dot`                                                                                                                                                           
        linux-vdso.so.1 =>  (0x00007ffed53cf000)
        libgvc.so.6 => /projects/demo/deeplearn/envs/dnn/bin/../lib/libgvc.so.6 (0x00007fb2a1a67000)
        libltdl.so.7 => /projects/demo/deeplearn/envs/dnn/bin/../lib/libltdl.so.7 (0x00007fb2a185e000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fb2a165a000)
        libxdot.so.4 => /projects/demo/deeplearn/envs/dnn/bin/../lib/libxdot.so.4 (0x00007fb2a1456000)
        libcgraph.so.6 => /projects/demo/deeplearn/envs/dnn/bin/../lib/libcgraph.so.6 (0x00007fb2a1240000)
        libpathplan.so.4 => /projects/demo/deeplearn/envs/dnn/bin/../lib/libpathplan.so.4 (0x00007fb2a1038000)
        libexpat.so.1 => /projects/demo/deeplearn/envs/dnn/bin/../lib/libexpat.so.1 (0x00007fb2a0e10000)
        libz.so.1 => /projects/demo/deeplearn/envs/dnn/bin/../lib/libz.so.1 (0x00007fb2a0bfa000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fb2a08f4000)
        libcdt.so.5 => /projects/demo/deeplearn/envs/dnn/bin/../lib/libcdt.so.5 (0x00007fb2a06ee000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fb2a0329000)
        /lib64/ld-linux-x86-64.so.2 (0x00007fb2a1d05000)
```

And finally versions:

```
$ conda list | grep -i -e dot -e graph -e pango
graphviz                  2.38.0                        4
pango                     1.40.3                        1
pydot-ng                  1.0.0                     <pip>
pydotplus                 2.0.2                    py35_0    bioconda
```

**Comment by ccordoba12** [comment]
Are you trying to run graphviz on a headless server?

**Comment by ijstokes** [comment]
@ccordoba12 yes.  This is an Anaconda Enterprise instance.  But how does that affect things?

**Comment by ccordoba12** [comment]
Because (most probably) `libgvplugin_pango.so.6` requires X libraries to run.

Could you run `ldd` on that library, please?

**Comment by ijstokes** [comment]
```
$ ldd /projects/demo/deeplearn/envs/default/lib/graphviz/libgvplugin_pango.so.6                                           
        linux-vdso.so.1 =>  (0x00007fff6ecb2000)                                                                                   
        libgvc.so.6 => /projects/demo/deeplearn/envs/default/lib/graphviz/../libgvc.so.6 (0x00007f8ec2ee0000)                      
        libltdl.so.7 => /projects/demo/deeplearn/envs/default/lib/graphviz/../libltdl.so.7 (0x00007f8ec2cd7000)                    
        libxdot.so.4 => /projects/demo/deeplearn/envs/default/lib/graphviz/../libxdot.so.4 (0x00007f8ec2ad3000)                    
        libcgraph.so.6 => /projects/demo/deeplearn/envs/default/lib/graphviz/../libcgraph.so.6 (0x00007f8ec28bd000)                
        libcdt.so.5 => /projects/demo/deeplearn/envs/default/lib/graphviz/../libcdt.so.5 (0x00007f8ec26b7000)                      
        libpathplan.so.4 => /projects/demo/deeplearn/envs/default/lib/graphviz/../libpathplan.so.4 (0x00007f8ec24af000)            
        libexpat.so.1 => /projects/demo/deeplearn/envs/default/lib/graphviz/../libexpat.so.1 (0x00007f8ec2287000)                  
        libpangocairo-1.0.so.0 => /projects/demo/deeplearn/envs/default/lib/graphviz/../libpangocairo-1.0.so.0 (0x00007f8ec207b000)
        libcairo.so.2 => /projects/demo/deeplearn/envs/default/lib/graphviz/../libcairo.so.2 (0x00007f8ec1d3b000)                  
        libpixman-1.so.0 => /projects/demo/deeplearn/envs/default/lib/graphviz/../libpixman-1.so.0 (0x00007f8ec1a96000)            
        libpng16.so.16 => /projects/demo/deeplearn/envs/default/lib/graphviz/../libpng16.so.16 (0x00007f8ec1854000)                
        libXrender.so.1 => /usr/lib/x86_64-linux-gnu/libXrender.so.1 (0x00007f8ec164a000)                                          
        libX11.so.6 => /usr/lib/x86_64-linux-gnu/libX11.so.6 (0x00007f8ec1315000)                                                  
        libXext.so.6 => /usr/lib/x86_64-linux-gnu/libXext.so.6 (0x00007f8ec1103000)                                                
        libpangoft2-1.0.so.0 => /projects/demo/deeplearn/envs/default/lib/graphviz/../libpangoft2-1.0.so.0 (0x00007f8ec0ef0000)    
        libharfbuzz.so.0 => /projects/demo/deeplearn/envs/default/lib/graphviz/../libharfbuzz.so.0 (0x00007f8ec0c7b000)            
        libpango-1.0.so.0 => /projects/demo/deeplearn/envs/default/lib/graphviz/../libpango-1.0.so.0 (0x00007f8ec0a31000)          
        libgthread-2.0.so.0 => /projects/demo/deeplearn/envs/default/lib/graphviz/../libgthread-2.0.so.0 (0x00007f8ec0830000)      
        libfontconfig.so.1 => /projects/demo/deeplearn/envs/default/lib/graphviz/../libfontconfig.so.1 (0x00007f8ec05f3000)        
        libxml2.so.2 => /projects/demo/deeplearn/envs/default/lib/graphviz/../libxml2.so.2 (0x00007f8ec0299000)                    
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f8ec0095000)                                                        
        libz.so.1 => /projects/demo/deeplearn/envs/default/lib/graphviz/../libz.so.1 (0x00007f8ebfe7f000)                          
        libiconv.so.2 => not found                                                                                                 
        libgobject-2.0.so.0 => /projects/demo/deeplearn/envs/default/lib/graphviz/../libgobject-2.0.so.0 (0x00007f8ebfc2e000)      
        libffi.so.6 => /projects/demo/deeplearn/envs/default/lib/graphviz/../libffi.so.6 (0x00007f8ebfa25000)                      
        libglib-2.0.so.0 => /projects/demo/deeplearn/envs/default/lib/graphviz/../libglib-2.0.so.0 (0x00007f8ebf6e7000)            
        libpcre.so.1 => /projects/demo/deeplearn/envs/default/lib/graphviz/../libpcre.so.1 (0x00007f8ebf4bf000)                    
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f8ebf2a1000)                                              
        librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f8ebf099000)                                                        
        libfreetype.so.6 => /projects/demo/deeplearn/envs/default/lib/graphviz/../libfreetype.so.6 (0x00007f8ebee00000)            
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f8ebeafa000)                                                          
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f8ebe735000)                                                          
        libgmodule-2.0.so.0 => /projects/demo/deeplearn/envs/default/lib/graphviz/.././libgmodule-2.0.so.0 (0x00007f8ebe532000)    
        /lib64/ld-linux-x86-64.so.2 (0x00007f8ec3389000)                                                                           
        libxcb.so.1 => /projects/demo/deeplearn/envs/default/lib/graphviz/../libxcb.so.1 (0x00007f8ebe30d000)                      
        libXau.so.6 => /usr/lib/x86_64-linux-gnu/libXau.so.6 (0x00007f8ebe109000)                                                  
        libXdmcp.so.6 => /usr/lib/x86_64-linux-gnu/libXdmcp.so.6 (0x00007f8ebdf03000)  
```

Looks like `libiconv.so.2` is **reported** as missing, however the `libiconv` 1.14 conda package is installed and is available:

```
$ find /projects/demo/deeplearn | grep libiconv.so.2                                                                      
/projects/demo/deeplearn/envs/dnn/lib/libiconv.so.2                                                                                
/projects/demo/deeplearn/envs/dnn/lib/libiconv.so.2.5.1                                                                            
/projects/demo/deeplearn/envs/conda_dnn/lib/libiconv.so.2                                                                          
/projects/demo/deeplearn/envs/conda_dnn/lib/libiconv.so.2.5.1                                                                      
/projects/demo/deeplearn/envs/.pkgs/libiconv-1.14-0/lib/libiconv.so.2                                                              
/projects/demo/deeplearn/envs/.pkgs/libiconv-1.14-0/lib/libiconv.so.2.5.1
```

**Comment by ccordoba12** [comment]
So the only missing library is `libiconv`. That's good to know.

I didn't add it as a dependency of graphviz (probably because it was detected from the system), so that's the problem here.

I'll work to solve this one as soon as I can.

**Comment by nehaljwani** [comment]
Now `libiconv` is being pulled as a transitive dependency. Do we still want to update the recipe to add it as a direct dependency?
```bash
(root) [nwani@somemachine]$ conda create -n graphviz graphviz
Fetching package metadata .........
Solving package specifications: .

Package plan for installation in environment /home/nwani/m3/envs/graphviz:

The following NEW packages will be INSTALLED:

    cairo:      1.14.8-0
    expat:      2.1.0-0
    fontconfig: 2.12.1-3
    freetype:   2.5.5-2
    glib:       2.50.2-1
    graphviz:   2.38.0-4
    harfbuzz:   0.9.39-2
    jbig:       2.1-0
    jpeg:       9b-0
    libffi:     3.2.1-1
    libiconv:   1.14-0
    libpng:     1.6.27-0
    libtiff:    4.0.6-3
    libtool:    2.4.2-0
    libxml2:    2.9.4-0
    pango:      1.40.3-1
    pcre:       8.39-1
    pixman:     0.34.0-0
    xz:         5.2.2-1
    zlib:       1.2.8-3

Proceed ([y]/n)?
```

**Comment by mingwandroid** [comment]
Only if graphviz links to it directly.

**Comment by ccordoba12** [comment]
@nehaljwani, I think we need to recompile graphviz on Linux with libiconv as a dependency of it, at least according to what @ijstokes said: 

> Looks like libiconv.so.2 is reported as missing, however the libiconv 1.14 conda package is installed and is available:

**Comment by mingwandroid** [comment]
`ldd` reports transitive dependencies.

**Comment by nehaljwani** [comment]
It does seem to be a direct dependency.

```bash
$ objdump -x \
          ~/m3/pkgs/graphviz-2.38.0-4/lib/graphviz/libgvplugin_pango.so | \
          grep NEEDED | \
          grep iconv
  NEEDED      libiconv.so.2
```

**Comment by mingwandroid** [comment]
Right, needs adding then. Sorry!

**Comment by ccordoba12** [comment]
Thanks for the clarification to both of you!

**Comment by CicoZhang** [comment]
I have encountered this problem today in different servers where some of the Galaxy tools are using the graphviz dependencies from bioconda. 

> Warning: Could not load "/tool_deps/_conda/envs/mulled-v1-06620e44bd4436ba16aaab5d81f7cd5b7916bffcf21beed99d0b81327ada73d4/lib/graphviz/libgvplugin_pango.so.6" - file not found
Warning: Could not load "/tool_deps/_conda/envs/mulled-v1-06620e44bd4436ba16aaab5d81f7cd5b7916bffcf21beed99d0b81327ada73d4/lib/graphviz/libgvplugin_pango.so.6" - file not found
Format: "pdf" not recognized. Use one of: canon cmap cmapx cmapx_np dot eps fig gv imap imap_np ismap pdf pic plain plain-ext png pov ps ps2 svg svgz tk vml vmlz xdot xdot1.2 xdot1.4
The tool produced the following additional output:

**Comment by tboyarski** [comment]
Just encountered this problem running on a CentOS5 server (head node) @ilanschnell. 

I ran ldd as per request by @ccordoba12 , and I also received a 'GLIBC_2.7' error which I did not see @ijstokes as having received. I'm not experienced enough to know if my additional glibc2.7 error is apart of the underlying warnings being received, but I thought I'd post this in the event that it is. In the past, I've always installed from conda's default channel because the binaries typically are complied from a glibc2.5 compatible docker image. With that said, I think they just recently dropped support for some backwards compatibility, so glibc might be a side issue exclusive to me. GLIBC compatibility has always been an issue for me on this server, so this may not be apart of the error, just a side symptom and not be related to the following warning message:

```
Warning: Could not load "/extscratch/clc/usr/anaconda/4.3.0/envs/CentOS5-Compatible/lib/graphviz/libgvplugin_pango.so.6" - file not found
```

Interestingly, as I prove further down, I am still able to produce a viable DAG, regardless of these errors.


ldd on conda installation of dot:
```
(CentOS5-Compatible) [tboyarski@login4 newProj]$ ldd /extscratch/clc/usr/anaconda/4.3.0/envs/CentOS5-Compatible/lib/graphviz/libgvplugin_pango.so.6
/extscratch/clc/usr/anaconda/4.3.0/envs/CentOS5-Compatible/lib/graphviz/libgvplugin_pango.so.6: /lib64/libc.so.6: version `GLIBC_2.7' not found (required by /extscratch/clc/usr/anaconda/4.3.0/envs/CentOS5-Compatible/lib/graphviz/../libxml2.so.2)
/extscratch/clc/usr/anaconda/4.3.0/envs/CentOS5-Compatible/lib/graphviz/libgvplugin_pango.so.6: /lib64/libc.so.6: version `GLIBC_2.7' not found (required by /extscratch/clc/usr/anaconda/4.3.0/envs/CentOS5-Compatible/lib/graphviz/../libiconv.so.2)
	libgvc.so.6 => /extscratch/clc/usr/anaconda/4.3.0/envs/CentOS5-Compatible/lib/graphviz/../libgvc.so.6 (0x00002b2371428000)
	libltdl.so.7 => /extscratch/clc/usr/anaconda/4.3.0/envs/CentOS5-Compatible/lib/graphviz/../libltdl.so.7 (0x00002b23716c6000)
	libxdot.so.4 => /extscratch/clc/usr/anaconda/4.3.0/envs/CentOS5-Compatible/lib/graphviz/../libxdot.so.4 (0x00002b23718d0000)
	libcgraph.so.6 => /extscratch/clc/usr/anaconda/4.3.0/envs/CentOS5-Compatible/lib/graphviz/../libcgraph.so.6 (0x00002b2371ad4000)
	libcdt.so.5 => /extscratch/clc/usr/anaconda/4.3.0/envs/CentOS5-Compatible/lib/graphviz/../libcdt.so.5 (0x00002b2371cea000)
	libpathplan.so.4 => /extscratch/clc/usr/anaconda/4.3.0/envs/CentOS5-Compatible/lib/graphviz/../libpathplan.so.4 (0x00002b2371ef1000)
	libexpat.so.1 => /extscratch/clc/usr/anaconda/4.3.0/envs/CentOS5-Compatible/lib/graphviz/../libexpat.so.1 (0x00002b23720f9000)
	libpangocairo-1.0.so.0 => /extscratch/clc/usr/anaconda/4.3.0/envs/CentOS5-Compatible/lib/graphviz/../libpangocairo-1.0.so.0 (0x00002b2372323000)
	libcairo.so.2 => /extscratch/clc/usr/anaconda/4.3.0/envs/CentOS5-Compatible/lib/graphviz/../libcairo.so.2 (0x00002b2372531000)
	libpixman-1.so.0 => /extscratch/clc/usr/anaconda/4.3.0/envs/CentOS5-Compatible/lib/graphviz/../libpixman-1.so.0 (0x00002b2372876000)
	libpng16.so.16 => /extscratch/clc/usr/anaconda/4.3.0/envs/CentOS5-Compatible/lib/graphviz/../libpng16.so.16 (0x00002b2372b1d000)
	libXrender.so.1 => /usr/lib64/libXrender.so.1 (0x00002b2372d6d000)
	libX11.so.6 => /usr/lib64/libX11.so.6 (0x00002b2372f76000)
	libXext.so.6 => /usr/lib64/libXext.so.6 (0x00002b2373282000)
	libpangoft2-1.0.so.0 => /extscratch/clc/usr/anaconda/4.3.0/envs/CentOS5-Compatible/lib/graphviz/../libpangoft2-1.0.so.0 (0x00002b2373494000)
	libharfbuzz.so.0 => /extscratch/clc/usr/anaconda/4.3.0/envs/CentOS5-Compatible/lib/graphviz/../libharfbuzz.so.0 (0x00002b23736a9000)
	libpango-1.0.so.0 => /extscratch/clc/usr/anaconda/4.3.0/envs/CentOS5-Compatible/lib/graphviz/../libpango-1.0.so.0 (0x00002b2373904000)
	libgthread-2.0.so.0 => /extscratch/clc/usr/anaconda/4.3.0/envs/CentOS5-Compatible/lib/graphviz/../libgthread-2.0.so.0 (0x00002b2373b4f000)
	libfontconfig.so.1 => /extscratch/clc/usr/anaconda/4.3.0/envs/CentOS5-Compatible/lib/graphviz/../libfontconfig.so.1 (0x00002b2373d50000)
	libxml2.so.2 => /extscratch/clc/usr/anaconda/4.3.0/envs/CentOS5-Compatible/lib/graphviz/../libxml2.so.2 (0x00002b2373f94000)
	libdl.so.2 => /lib64/libdl.so.2 (0x00002b23742fc000)
	libz.so.1 => /extscratch/clc/usr/anaconda/4.3.0/envs/CentOS5-Compatible/lib/graphviz/../libz.so.1 (0x00002b2374500000)
	libiconv.so.2 => /extscratch/clc/usr/anaconda/4.3.0/envs/CentOS5-Compatible/lib/graphviz/../libiconv.so.2 (0x00002b2374716000)
	libgobject-2.0.so.0 => /extscratch/clc/usr/anaconda/4.3.0/envs/CentOS5-Compatible/lib/graphviz/../libgobject-2.0.so.0 (0x00002b2374a05000)
	libffi.so.6 => /extscratch/clc/usr/anaconda/4.3.0/envs/CentOS5-Compatible/lib/graphviz/../libffi.so.6 (0x00002b2374c54000)
	libglib-2.0.so.0 => /extscratch/clc/usr/anaconda/4.3.0/envs/CentOS5-Compatible/lib/graphviz/../libglib-2.0.so.0 (0x00002b2374e5e000)
	libpcre.so.1 => /extscratch/clc/usr/anaconda/4.3.0/envs/CentOS5-Compatible/lib/graphviz/../libpcre.so.1 (0x00002b2375175000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00002b23753b7000)
	librt.so.1 => /lib64/librt.so.1 (0x00002b23755d2000)
	libfreetype.so.6 => /extscratch/clc/usr/anaconda/4.3.0/envs/CentOS5-Compatible/lib/graphviz/../libfreetype.so.6 (0x00002b23757dc000)
	libm.so.6 => /lib64/libm.so.6 (0x00002b2375a76000)
	libc.so.6 => /lib64/libc.so.6 (0x00002b2375cf9000)
	/lib64/ld-linux-x86-64.so.2 (0x0000003d53400000)
	libXau.so.6 => /usr/lib64/libXau.so.6 (0x00002b2376051000)
	libXdmcp.so.6 => /usr/lib64/libXdmcp.so.6 (0x00002b2376253000)
	libicui18n.so.56 => /extscratch/clc/usr/anaconda/4.3.0/envs/CentOS5-Compatible/lib/graphviz/.././libicui18n.so.56 (0x00002b2376459000)
	libicuuc.so.56 => /extscratch/clc/usr/anaconda/4.3.0/envs/CentOS5-Compatible/lib/graphviz/.././libicuuc.so.56 (0x00002b2376955000)
	libicudata.so.56 => /extscratch/clc/usr/anaconda/4.3.0/envs/CentOS5-Compatible/lib/graphviz/.././libicudata.so.56 (0x00002b2376d3b000)
	liblzma.so.5 => /extscratch/clc/usr/anaconda/4.3.0/envs/CentOS5-Compatible/lib/graphviz/.././liblzma.so.5 (0x00002b237871e000)
	libstdc++.so.6 => /extscratch/clc/usr/anaconda/4.3.0/envs/CentOS5-Compatible/lib/graphviz/../././libstdc++.so.6 (0x00002b2378944000)
	libgcc_s.so.1 => /extscratch/clc/usr/anaconda/4.3.0/envs/CentOS5-Compatible/lib/graphviz/../././libgcc_s.so.1 (0x00002b2378c5a000)
```


ls on the supposidly non-existant file, proves that it does exist:
```
[tboyarski@login4 Snakemake]$ ls /extscratch/clc/usr/anaconda/4.3.0/envs/CentOS5-Compatible/lib/graphviz/
total 4.1M
drwxr-xr-x  2 tboyarski users  64K Aug  3 10:08 ./
drwxrwxr-x 19 tboyarski clc    64K Aug  3 10:09 ../
-rw-rw-r--  2 tboyarski users 2.1K Jun  6 11:26 config6
-rwxrwxr-x  1 tboyarski users 1.7K Aug  3 10:08 libgvplugin_core.la*
lrwxrwxrwx  1 tboyarski users   25 Aug  3 10:08 libgvplugin_core.so -> libgvplugin_core.so.6.0.0*
lrwxrwxrwx  1 tboyarski users   25 Aug  3 10:08 libgvplugin_core.so.6 -> libgvplugin_core.so.6.0.0*
-rwxrwxr-x  2 tboyarski users 386K Jun  6 11:26 libgvplugin_core.so.6.0.0*
-rwxrwxr-x  1 tboyarski users 1.7K Aug  3 10:08 libgvplugin_dot_layout.la*
lrwxrwxrwx  1 tboyarski users   31 Aug  3 10:08 libgvplugin_dot_layout.so -> libgvplugin_dot_layout.so.6.0.0*
lrwxrwxrwx  1 tboyarski users   31 Aug  3 10:08 libgvplugin_dot_layout.so.6 -> libgvplugin_dot_layout.so.6.0.0*
-rwxrwxr-x  2 tboyarski users 758K Jun  6 11:26 libgvplugin_dot_layout.so.6.0.0*
-rwxrwxr-x  1 tboyarski users 1.7K Aug  3 10:08 libgvplugin_neato_layout.la*
lrwxrwxrwx  1 tboyarski users   33 Aug  3 10:08 libgvplugin_neato_layout.so -> libgvplugin_neato_layout.so.6.0.0*
lrwxrwxrwx  1 tboyarski users   33 Aug  3 10:08 libgvplugin_neato_layout.so.6 -> libgvplugin_neato_layout.so.6.0.0*
-rwxrwxr-x  2 tboyarski users 2.2M Jun  6 11:26 libgvplugin_neato_layout.so.6.0.0*
-rwxrwxr-x  1 tboyarski users 3.1K Aug  3 10:08 libgvplugin_pango.la*
lrwxrwxrwx  1 tboyarski users   26 Aug  3 10:08 libgvplugin_pango.so -> libgvplugin_pango.so.6.0.0*
lrwxrwxrwx  1 tboyarski users   26 Aug  3 10:08 libgvplugin_pango.so.6 -> libgvplugin_pango.so.6.0.0*
-rwxrwxr-x  1 tboyarski users 132K Aug  3 10:08 libgvplugin_pango.so.6.0.0*
```


The server admins had already installed a version, and it doesn't generate any warnings.

- Server Version: dot - graphviz version 2.38.0 (20140413.2041)
- conda Version: dot - graphviz version 2.38.0 (20140413.2041)

server path to dot:
```
[tboyarski@login4 Snakemake]$ ldd /gsc/software/linux-x86_64-centos5/graphviz-2.38/bin/dot
	libgvc.so.6 => /gsc/software/linux-x86_64-centos5/graphviz-2.38/lib/libgvc.so.6 (0x00002b2400410000)
	libdl.so.2 => /lib64/libdl.so.2 (0x0000003d53c00000)
	libxdot.so.4 => /gsc/software/linux-x86_64-centos5/graphviz-2.38/lib/libxdot.so.4 (0x00002b24006c0000)
	libcgraph.so.6 => /gsc/software/linux-x86_64-centos5/graphviz-2.38/lib/libcgraph.so.6 (0x00002b24008c4000)
	libpathplan.so.4 => /gsc/software/linux-x86_64-centos5/graphviz-2.38/lib/libpathplan.so.4 (0x00002b2400ad9000)
	libz.so.1 => /usr/lib64/libz.so.1 (0x0000003d54c00000)
	libm.so.6 => /lib64/libm.so.6 (0x0000003d54400000)
	libcdt.so.5 => /gsc/software/linux-x86_64-centos5/graphviz-2.38/lib/libcdt.so.5 (0x00002b2400ce2000)
	libc.so.6 => /lib64/libc.so.6 (0x0000003d53800000)
	/lib64/ld-linux-x86-64.so.2 (0x0000003d53400000)
```

Regardless of the warning, I can still produce a DAG with both versions. The version with the warning produces a slightly larger file. They look ever so slightly different.

- Server Version DAG: https://github.com/tboyarski/BCCRC-Snakemake/blob/master/help/serverDOT.svg
- conda Version DAG: https://github.com/tboyarski/BCCRC-Snakemake/blob/master/help/condaDOT.svg

Here is my installation:

```
(CentOS5-Compatible) [tboyarski@login4 newProj]$ conda install graphviz=2.38.0=5
Fetching package metadata .........
Solving package specifications: .

Package plan for installation in environment /home/tboyarski/share/usr/anaconda/4.3.0/envs/CentOS5-Compatible:

The following NEW packages will be INSTALLED:

    graphviz:   2.38.0-5

The following packages will be UPDATED:

    cairo:      1.14.6-3 conda-forge --> 1.14.8-0

The following packages will be SUPERSEDED by a higher-priority channel:

    fontconfig: 2.12.1-3 conda-forge --> 2.12.1-3
    freetype:   2.7-1    conda-forge --> 2.5.5-2
    glib:       2.51.4-0 conda-forge --> 2.50.2-1
    harfbuzz:   1.3.4-1  conda-forge --> 0.9.39-2
    pango:      1.40.3-3 conda-forge --> 1.40.3-1

Proceed ([y]/n)? y

glib-2.50.2-1. 100% |#####################################################################################################################################| Time: 0:00:00  30.97 MB/s
freetype-2.5.5 100% |#####################################################################################################################################| Time: 0:00:00  35.88 MB/s
fontconfig-2.1 100% |#####################################################################################################################################| Time: 0:00:00  36.40 MB/s
cairo-1.14.8-0 100% |#####################################################################################################################################| Time: 0:00:00  36.31 MB/s
harfbuzz-0.9.3 100% |#####################################################################################################################################| Time: 0:00:00  33.68 MB/s
graphviz-2.38. 100% |#####################################################################################################################################| Time: 0:00:00  37.03 MB/s
```

Server Head OS:
```
LSB Version:	:core-3.1-amd64:core-3.1-ia32:core-3.1-noarch:graphics-3.1-amd64:graphics-3.1-ia32:graphics-3.1-noarch
Distributor ID:	RedHatEnterpriseServer
Description:	Red Hat Enterprise Linux Server release 5.4 (Tikanga)
Release:	5.4
Codename:	Tikanga
```

**Comment by mingwandroid** [comment]
We no longer support Centos5.

**Comment by mingwandroid** [comment]
On this issue, `libiconv` should never have been built and provided for GNU/Linux since it's built into `glibc`. The same is true of `gettext`!

Hopefully we can fix this oversight.

**Comment by unnir** [comment]
this helped me, ubuntu:

`sudo apt-get install graphviz
`

**Comment by Deepanshu8391** [comment]
Hey,
I have followed the following steps and it worked fine for me.
1 . Download and install graphviz-2.38.msi from
    https://graphviz.gitlab.io/_pages/Download/Download_windows.html

2 . Set the path variable
    (a) Control Panel > System and Security > System > Advanced System Settings > Environment Variables > Path > Edit
    (b) add 'C:\Program Files (x86)\Graphviz2.38\bin'
