### ISSUE TITLE
problems trying to search/install matplotlib 2.0.0 from conda-forge

### ISSUE THREAD

**Issue by smontanaro** [ContinuumIO/anaconda-issues#1379]
I'm unable to search for matplotlib 2.0.0 after adding the conda-forge channel. The full thread is here, but here are the most recent bits...

https://groups.google.com/a/continuum.io/d/msg/conda/y61DSWfcNxo/hUmdKPbcBAAJ

Dharhas> Maybe check if to see if you have anything weird in your .condarc file or
Dharhas> just delete it. Folks have had issues before if a bad channel name existed
Dharhas> in the .condarc config file.

Seems fairly innocuous:

```
(anaconda) ~% cat ~/.condarc
channels:
  - conda-forge
  - defaults

```
Still, removing it (well, moving it out of the way) solved my problem.

Kale> I think you're just using an old version of conda.  Probably something less than 4.2.10.

Kale> Please advance to either 4.2.16 or 4.3.7.

That also seems to be true:

```
% conda --version
conda 4.1.6

```
Updating it initially failed:

```
% conda update conda
Error: Package 'conda' is not installed in /Users/skip/anaconda/envs/anaconda

In fact I needed to deactivate my current environment to install it.

Now that conda is at a proper version:

(anaconda) ~% conda --version
conda 4.3.7

```
I don't get recursion errors, but still can't search matplotlib with the conda-forge in the mix:

```
~% mv .condarc- .condarc
~% type activate
activate is a function
activate ()
{
    . /Users/skip/anaconda/bin/activate "$@"
}
~% activate anaconda
(anaconda) ~% conda search matplotlib
Fetching package metadata ...

CondaHTTPError: HTTP 401 UNAUTHORIZED for url <https://conda.anaconda.org/t/sm-f174968d-6e7c-419a-ba8e-a9f2177c417e/conda-forge/osx-64/repodata.json>
Elapsed: 00:00.373658

The remote server has indicated you are using invalid credentials for this channel.

If the remote site is anaconda.org or follows the Anaconda Server API, you
will need to
  (a) login to the site with `anaconda login`, or
  (b) provide conda with a valid token directly.

Further configuration help can be found at <https://conda.io/docs/config.html>.

```
Move .condarc out of the way and I'm back in business, albeit sans matplotlib 2.0.0.

Add conda-forge channel again (starting from an empty .condarc file), and the error returns (this time searching from the root environment):

```
~% ~/anaconda/bin/conda config --add channels conda-forge
~% cat ~/.condarc
channels:
  - conda-forge
  - defaults
~% ~/anaconda/bin/conda search matplotlib
Fetching package metadata ...

CondaHTTPError: HTTP 401 UNAUTHORIZED for url <https://conda.anaconda.org/t/sm-f174968d-6e7c-419a-ba8e-a9f2177c417e/conda-forge/osx-64/repodata.json>
Elapsed: 00:00.728581

The remote server has indicated you are using invalid credentials for this channel.

If the remote site is anaconda.org or follows the Anaconda Server API, you
will need to
  (a) login to the site with `anaconda login`, or
  (b) provide conda with a valid token directly.

```
Further configuration help can be found at <https://conda.io/docs/config.html>.

More:

~% ~/anaconda/bin/conda info -a
Current conda install:

               platform : osx-64
          conda version : 4.3.7
       conda is private : False
      conda-env version : 4.3.7
    conda-build version : 1.21.3
         python version : 3.5.2.final.0
       requests version : 2.12.4
       root environment : /Users/skip/anaconda  (writable)
    default environment : /Users/skip/anaconda
       envs directories : /Users/skip/anaconda/envs
          package cache : /Users/skip/anaconda/pkgs
           channel URLs : https://conda.anaconda.org/conda-forge/osx-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.continuum.io/pkgs/free/osx-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/osx-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/osx-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : /Users/skip/.condarc
           offline mode : False
             user-agent : conda/4.3.7 requests/2.12.4 CPython/3.5.2 Darwin/15.6.0 OSX/10.11.6
                UID:GID : 501:20

# conda environments:
#
anaconda                 /Users/skip/anaconda/envs/anaconda
nltk                     /Users/skip/anaconda/envs/nltk
py27                     /Users/skip/anaconda/envs/py27
root                  *  /Users/skip/anaconda

sys.version: 3.5.2 |Anaconda custom (x86_64)| (defaul...
sys.prefix: /Users/skip/anaconda
sys.executable: /Users/skip/anaconda/bin/python
conda location: /Users/skip/anaconda/lib/python3.5/site-packages/conda
conda-build: /Users/skip/anaconda/bin/conda-build
conda-convert: /Users/skip/anaconda/bin/conda-convert
conda-develop: /Users/skip/anaconda/bin/conda-develop
conda-env: /Users/skip/anaconda/bin/conda-env
conda-index: /Users/skip/anaconda/bin/conda-index
conda-inspect: /Users/skip/anaconda/bin/conda-inspect
conda-metapackage: /Users/skip/anaconda/bin/conda-metapackage
conda-pipbuild: /Users/skip/anaconda/bin/conda-pipbuild
conda-render: /Users/skip/anaconda/bin/conda-render
conda-server: /Users/skip/anaconda/bin/conda-server
conda-sign: /Users/skip/anaconda/bin/conda-sign
conda-skeleton: /Users/skip/anaconda/bin/conda-skeleton
user site dirs: 

CIO_TEST: <not set>
CONDA_DEFAULT_ENV: <not set>
CONDA_ENVS_PATH: <not set>
DYLD_LIBRARY_PATH: <not set>
PATH: /usr/local/heroku/bin:/usr/local/heroku/bin:/Users/skip/.local/bin:/Users/skip/cmd:/Users/skip/local/bin:/usr/local/mysql/bin:/opt/local/bin:/opt/local/sbin:/usr/local/bin:/usr/bin:/bin::/usr/X11R6/bin:/usr/local/sbin:/usr/sbin:/sbin:/Users/skip/cmd/fmscripts:/Library/PostgreSQL/9.2/bin:/Library/Developer/CommandLineTools/usr/bin.
PYTHONHOME: <not set>
PYTHONPATH: <not set>

WARNING: could not import _license.show_info
# try:
# $ conda install -n root _license

List of packages attached.

[conda-list.txt](https://github.com/ContinuumIO/anaconda-issues/files/726460/conda-list.txt)

Finally:

~% ~/anaconda/bin/anaconda whoami
Using Anaconda Cloud api site https://api.anaconda.org
Username: smontanaro
Member since: Sat Jan 21 21:14:13 2017
  +description: None
  +company: None
  +name: None
  +user_type: user
  +url: None
  +location: None

**Comment by msarahan** [comment]
I have seen anaconda.org credentials go stale and cause this.  Try

``anaconda logout``

followed by

``anaconda login``

to refresh the credentials.  It does seem unlikely, though, given your "Member since" info...

**Comment by ilanschnell** [comment]
We actually now support `matplotlib 2.0.0` in the default channels also.

**Comment by 183amir** [comment]
This may not be the best place to report it but `matplotlib 2.0.0` form the defaults channel seems to be broken:
```sh
$ conda create -n temp --override-channels -c defaults python=2.7 matplotlib                                                                                                       :(
Fetching package metadata .......
Solving package specifications: ..........

Package plan for installation in environment /home/amir/miniconda/envs/temp:

The following NEW packages will be INSTALLED:

    cairo:            1.14.8-0          defaults
    cycler:           0.10.0-py27_0     defaults
    dbus:             1.10.10-0         defaults
    expat:            2.1.0-0           defaults
    fontconfig:       2.12.1-2          defaults
    freetype:         2.5.5-2           defaults
    functools32:      3.2.3.2-py27_0    defaults
    glib:             2.50.2-1          defaults
    gst-plugins-base: 1.8.0-0           defaults
    gstreamer:        1.8.0-0           defaults
    icu:              54.1-0            defaults
    jpeg:             9b-0              defaults
    libffi:           3.2.1-1           defaults
    libgcc:           5.2.0-0           defaults
    libiconv:         1.14-0            defaults
    libpng:           1.6.27-0          defaults
    libxcb:           1.12-1            defaults
    libxml2:          2.9.4-0           defaults
    matplotlib:       2.0.0-np111py27_0 defaults
    mkl:              2017.0.1-0        defaults
    numpy:            1.11.3-py27_0     defaults
    openssl:          1.0.2k-0          defaults
    pcre:             8.39-1            defaults
    pip:              9.0.1-py27_1      defaults
    pixman:           0.34.0-0          defaults
    pycairo:          1.10.0-py27_0     defaults
    pyparsing:        2.1.4-py27_0      defaults
    pyqt:             5.6.0-py27_2      defaults
    python:           2.7.13-0          defaults
    python-dateutil:  2.6.0-py27_0      defaults
    pytz:             2016.10-py27_0    defaults
    qt:               5.6.2-3           defaults
    readline:         6.2-2             defaults
    setuptools:       27.2.0-py27_0     defaults
    sip:              4.18-py27_0       defaults
    six:              1.10.0-py27_0     defaults
    sqlite:           3.13.0-0          defaults
    tk:               8.5.18-0          defaults
    wheel:            0.29.0-py27_0     defaults
    zlib:             1.2.8-3           defaults

Proceed ([y]/n)? 

Linking packages ...
[      COMPLETE      ]|#################################################################################################################################################################################################################| 100%
#
# To activate this environment, use:
# > source activate temp
#
# To deactivate this environment, use:
# > source deactivate temp
#

$ source activate temp
$ python -c "import pkg_resources; pkg_resources.require('matplotlib')"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/amir/miniconda/envs/temp/lib/python2.7/site-packages/setuptools-27.2.0-py2.7.egg/pkg_resources/__init__.py", line 968, in require
  File "/home/amir/miniconda/envs/temp/lib/python2.7/site-packages/setuptools-27.2.0-py2.7.egg/pkg_resources/__init__.py", line 854, in resolve
pkg_resources.DistributionNotFound: The 'subprocess32' distribution was not found and is required by matplotlib
```

There is a new python library for python 2 called `subprocess32` and matplotlib depends on it.
It is a dependency of matplotlib 2 in conda-forge
```sh
conda-forge.github.io (git) $ python scripts/list_deps.py conda-forge --dependencies subprocess32
fenics 2016.2.0 py27_0 None        : subprocess32
fenics 2016.2.0 py27_2 None        : subprocess32
fenics 2016.2.0 py27_3 None        : subprocess32
fenics 2016.2.0 py27_4 None        : subprocess32
matplotlib 2.0.0 np110py27_0 None  : subprocess32
matplotlib 2.0.0 np110py27_1 None  : subprocess32
matplotlib 2.0.0 np111py27_0 None  : subprocess32
matplotlib 2.0.0 np111py27_1 None  : subprocess32
matplotlib 2.0.0 np112py27_1 None  : subprocess32
matplotlib 2.0.0b2 np110py27_3 None: subprocess32
matplotlib 2.0.0b2 np111py27_3 None: subprocess32
matplotlib 2.0.0b3 np110py27_3 None: subprocess32
matplotlib 2.0.0b3 np110py27_4 None: subprocess32
matplotlib 2.0.0b3 np110py27_5 None: subprocess32
matplotlib 2.0.0b3 np111py27_3 None: subprocess32
matplotlib 2.0.0b3 np111py27_4 None: subprocess32
matplotlib 2.0.0b3 np111py27_5 None: subprocess32
matplotlib 2.0.0b4 np110py27_0 None: subprocess32
matplotlib 2.0.0b4 np110py27_1 None: subprocess32
matplotlib 2.0.0b4 np111py27_0 None: subprocess32
matplotlib 2.0.0b4 np111py27_1 None: subprocess32
matplotlib 2.0.0rc1 np110py27_0 None: subprocess32
matplotlib 2.0.0rc1 np110py27_1 None: subprocess32
matplotlib 2.0.0rc1 np111py27_0 None: subprocess32
matplotlib 2.0.0rc1 np111py27_1 None: subprocess32
matplotlib 2.0.0rc2 np110py27_0 None: subprocess32
matplotlib 2.0.0rc2 np110py27_1 None: subprocess32
matplotlib 2.0.0rc2 np110py27_2 None: subprocess32
matplotlib 2.0.0rc2 np111py27_0 None: subprocess32
matplotlib 2.0.0rc2 np111py27_1 None: subprocess32
matplotlib 2.0.0rc2 np111py27_2 None: subprocess32
matplotlib 2.0.0rc2 np112py27_2 None: subprocess32
```

**Comment by ilanschnell** [comment]
I've added `subprocess32` as a dependency of the `matplotlib 2.0.0` (Python 2) packages.

**Comment by 183amir** [comment]
Thank you. Great!

**Comment by ilanschnell** [comment]
Closing issue.  Please feel free to reopen if there are still problems.

**Comment by ilanschnell** [comment]
I just realized that the original issue was about access to `conda-forge`, so even though we have `matplotlib-2.0.0` (with `subprocess32` Python 2 dependency) in the default repository now, I'm not sure if the original issue has been resolved.  Sorry for closing.

**Comment by smontanaro** [comment]
I am still stumped by this. I deleted ~/.condarc, ~/.continuum, and ~/.conda then moved my existing ~/anaconda and ~/miniconda directories out of the way and downloaded and executed the Anaconda 3.6 install script.  I created an environment named numpy and activated it. So far, so good.

I tried "conda search pybind11" and found nothing, so I added conda-forge with this command:

(numpy) python_example% ~/anaconda3/bin/conda config --add channels conda-forge

and searched again. Presto!

(numpy) python_example% conda search pybind11
Fetching package metadata ...

CondaHTTPError: HTTP 401 UNAUTHORIZED for url <https://conda.anaconda.org/t/sm-64bed4d2-1be6-466e-ab16-73788252c7f1/conda-forge/osx-64/repodata.json>
Elapsed: 00:00.720628

The remote server has indicated you are using invalid credentials for this channel.

If the remote site is anaconda.org or follows the Anaconda Server API, you
will need to
  (a) login to the site with `anaconda login`, or
  (b) provide conda with a valid token directly.

Further configuration help can be found at <https://conda.io/docs/config.html>.

Can anyone see anything I failed to do correctly?
