### ISSUE TITLE
anaconda (search and...) broken

### ISSUE THREAD

**Issue by chrisamow** [ContinuumIO/anaconda-issues#1382]
Initially was trying to set up an environment and apparently I have some dependencies that may be unsupported by anaconda, so I went to look for more details and...
(I had to install the anaconda-client also, that I'll include at the end)

conda version 4.3.8  (python 2.7)
turns out I can't even call anaconda --version - script breaks same way, so this is not search specific

```
➜  artisticfreq1 git:(master) ✗ ★conda create -n af --file requirements.txt                                   [1] 16:45:07
Fetching package metadata .........


PackageNotFoundError: Package not found: '' Package missing in current linux-64 channels:
  - flask-flatpages ==0.5

You can search for packages on anaconda.org with

    anaconda search -t conda flask-flatpages


➜  artisticfreq1 git:(master) ✗ ★ anaconda search -t conda flask-flatpages                                                                                             [1] 16:45:18
Traceback (most recent call last):
  File "/home/chris/anaconda/bin/anaconda", line 6, in <module>
    sys.exit(binstar_client.scripts.cli.main())
  File "/home/chris/anaconda/lib/python2.7/site-packages/binstar_client/scripts/cli.py", line 88, in main
    description=__doc__, version=version)
  File "/home/chris/anaconda/lib/python2.7/site-packages/binstar_client/scripts/cli.py", line 51, in binstar_main
    add_subparser_modules(parser, sub_command_module, 'conda_server.subcommand')
TypeError: add_subparser_modules() takes exactly 2 arguments (3 given)
```

```
➜  artisticfreq1 git:(master) ✗ ★ conda install anaconda-client                                               [2] 16:43:58
Fetching package metadata .......
Solving package specifications: ..........

Package plan for installation in environment /home/chris/anaconda:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    conda-env-2.6.0            |                0          502 B
    requests-2.12.4            |           py27_0         762 KB
    anaconda-client-1.6.0      |           py27_0         127 KB
    cryptography-1.7.1         |           py27_0         848 KB
    pyopenssl-16.2.0           |           py27_0          68 KB
    conda-4.3.8                |           py27_0         468 KB
    ------------------------------------------------------------
                                           Total:         2.2 MB

The following NEW packages will be INSTALLED:

    anaconda-client: 1.6.0-py27_0

The following packages will be UPDATED:

    conda:           4.1.11-py27_0           --> 4.3.8-py27_0
    conda-env:       2.5.1-py27_0            --> 2.6.0-0
    cryptography:    1.3-py27_0              --> 1.7.1-py27_0
    pyopenssl:       0.15.1-py27_1 <unknown> --> 16.2.0-py27_0
    requests:        2.9.1-py27_0            --> 2.12.4-py27_0

Proceed ([y]/n)?
```

**Comment by goanpeca** [comment]
@chrisamow could you type 

```
$ conda info
$ conda list
```

And paste the output here?

**Comment by nick-youngblut** [comment]
I'm also having an issue with `anaconda search`. Maybe this should be a separate issue? My setup: 
~~~
# Sever: Ubuntu 14.04 x86_64. 
# Anaconda (for python3.5) install
wget https://repo.continuum.io/archive/Anaconda3-4.2.0-Linux-x86_64.sh
bash Anaconda3-4.2.0-Linux-x86_64.sh -b -p `pwd`"/anaconda3"
conda update conda
~~~


Searching for "r-base" package produces an error.

`anaconda search r-base`


~~~
Using Anaconda API: https://api.anaconda.org
Run 'anaconda show <USER/PACKAGE>' to get more details:
Packages:
     Name                      |  Version | Package Types   | Platforms
     ------------------------- |   ------ | --------------- | ---------------
[ERROR]
Traceback (most recent call last):
  File "/ebio/abt3_projects/methanogen_host_evo/anaconda3/bin/anaconda", line 6, in <module>
    sys.exit(binstar_client.scripts.cli.main())
  File "/ebio/abt3_projects/methanogen_host_evo/anaconda3/lib/python3.5/site-packages/binstar_client/scripts/cli.py", line 87, in main
    description=__doc__, version=version)
  File "/ebio/abt3_projects/methanogen_host_evo/anaconda3/lib/python3.5/site-packages/binstar_client/scripts/cli.py", line 66, in binstar_main
    return args.main(args)
  File "/ebio/abt3_projects/methanogen_host_evo/anaconda3/lib/python3.5/site-packages/binstar_client/commands/search.py", line 15, in search
    pprint_packages(packages, access=False)
  File "/ebio/abt3_projects/methanogen_host_evo/anaconda3/lib/python3.5/site-packages/binstar_client/utils/pprint.py", line 70, in pprint_packages
    pprint_package(package, access, full_name, revision=revisions)
  File "/ebio/abt3_projects/methanogen_host_evo/anaconda3/lib/python3.5/site-packages/binstar_client/utils/pprint.py", line 34, in pprint_package
    package['conda_platforms'] = ', '.join(package['conda_platforms'])
TypeError: sequence item 2: expected str instance, NoneType found
~~~

 I get a similar error when searching for other packages (e.g., `anaconda search mothur`)

**Comment by csoja** [comment]
@nick-youngblut 
It would be very helpful, if you would add the output to this issue from
_conda info_
_conda list_

**Comment by goanpeca** [comment]
Closing due to lack of response
