### ISSUE TITLE
Anaconda-Navigator.app fails to start due to ".continuum/anaconda-client: Permission denied"

### ISSUE THREAD

**Issue by tlk** [ContinuumIO/anaconda-issues#1397]
Hello there,
just wanted to report that a fresh install with Anaconda3-4.3.0-MacOSX-x86_64.pkg on OSX/10.12.2 appears to set wrong ownership on $HOME/.continuum

When double-clicking the /Applications/Anaconda-Navigator.app icon/symlink a green loader was displayed for a few seconds until it disappeared. No error message, it just disappeared. Same result when repeated.

So I ran the following from command line:

```
5k:~ tlk$ conda info
Current conda install:

               platform : osx-64
          conda version : 4.3.8
       conda is private : False
      conda-env version : 4.3.8
    conda-build version : not installed
         python version : 3.6.0.final.0
       requests version : 2.12.4
       root environment : //anaconda  (writable)
    default environment : //anaconda
       envs directories : //anaconda/envs
          package cache : //anaconda/pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/osx-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/osx-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/osx-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : /Users/tlk/.condarc
           offline mode : False
             user-agent : conda/4.3.8 requests/2.12.4 CPython/3.6.0 Darwin/16.3.0 OSX/10.12.2
                UID:GID : 501:20

5k:~ tlk$ anaconda-navigator
Traceback (most recent call last):
  File "//anaconda/lib/python3.6/site-packages/binstar_client/utils/config.py", line 250, in save_config
    os.makedirs(data_dir)
  File "//anaconda/lib/python3.6/os.py", line 220, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/Users/tlk/.continuum/anaconda-client'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "//anaconda/bin/anaconda-navigator", line 6, in <module>
    sys.exit(anaconda_navigator.app.main.main())
  File "//anaconda/lib/python3.6/site-packages/anaconda_navigator/app/main.py", line 52, in main
    start_app(options)
  File "//anaconda/lib/python3.6/site-packages/anaconda_navigator/app/start.py", line 87, in start_app
    window = run_app(splash)
  File "//anaconda/lib/python3.6/site-packages/anaconda_navigator/app/start.py", line 42, in run_app
    window = MainWindow(splash=splash)
  File "//anaconda/lib/python3.6/site-packages/anaconda_navigator/widgets/main_window.py", line 204, in __init__
    self.environments_tab = EnvironmentsTab(parent=self)
  File "//anaconda/lib/python3.6/site-packages/anaconda_navigator/widgets/tabs/environments.py", line 131, in __init__
    data_directory=CHANNELS_PATH,
  File "//anaconda/lib/python3.6/site-packages/anaconda_navigator/widgets/manager/packages.py", line 382, in __init__
    self.api.client_set_domain(self.api.client_get_api_url())
  File "//anaconda/lib/python3.6/site-packages/anaconda_navigator/api/client_api.py", line 365, in set_domain
    binstar_client.utils.set_config(config)
  File "//anaconda/lib/python3.6/site-packages/binstar_client/utils/config.py", line 260, in set_config
    save_config(data, USER_CONFIG if user else SYSTEM_CONFIG)
  File "//anaconda/lib/python3.6/site-packages/binstar_client/utils/config.py", line 255, in save_config
    raise BinstarError('%s: %s' % (exc.filename, exc.strerror,))
binstar_client.errors.BinstarError: /Users/tlk/.continuum/anaconda-client: Permission denied
5k:~ tlk$
5k:~ tlk$ ls -la  /Users/tlk/.continuum
total 0
drwxr-xr-x   2 root  staff    68 31 Jan 20:31 .
drwxr-xr-x+ 63 tlk   staff  2142 31 Jan 20:36 ..
5k:~ tlk$ sudo chown $USER $HOME/.continuum
5k:~ tlk$
```

Afterwards the application started successfully.

I think this is related to #1238 - looks like there is an issue with the macosx installer?

**Comment by goanpeca** [comment]
@tlk did you at some point used the anaconda-clean package?

**Comment by tlk** [comment]
Nope

Wow! quick response :)

**Comment by goanpeca** [comment]
Hmmmm pingin @ilanschnell 

Thanks for the report @tlk

**Comment by ilanschnell** [comment]
Looks like a bug in `anaconda-client` to me.

**Comment by tlk** [comment]
#1401 looks like a dupe

**Comment by goanpeca** [comment]
Yep, just provided some info. We will look further into this. Closing for now :-)

**Comment by Rossell9** [comment]
I've been experiencing the same issue, and progress on what I should do?

**Comment by trgrey** [comment]
Hello - I'm having this issue, though I did run anaconda-clean. @goanpeca do you know what I could do to fix this?

**Comment by goanpeca** [comment]
Please run

`sudo rm -rf ~/.continuum/`

**Comment by rjdp** [comment]
thanks it works now , @goanpeca  any details on why this happened.

**Comment by navborg** [comment]
Hi @goanpeca, 

I am having the same problem tried your solution but I get "Password:*key symbol*" 
and can not type anything?

**Comment by rjdp** [comment]
@navborg probably you're new to unix system, password prompts don't output the kepresses on screen for security reason,so just type your password and press enter

**Comment by navborg** [comment]
Hi @rjdp haha yes I figured it out two seconds after I posted. Thanks for the help. Problem now solved

**Comment by aps0017** [comment]
Hi @goanpeca ,

experienced the same issue with the latest anaconda installer for mac big sur (11.4) and it worked! Many thanks for the suggestion.
