### ISSUE TITLE
Anaconda Navigator Not Launching!

### ISSUE THREAD

**Issue by Alphamineron** [ContinuumIO/anaconda-issues#1404]
Hey!
I'm not a genius Computer Science Grad but just a high school student trying to start learning Machine Learning. I was watching a Google Developers videos and they were using Anaconda to code so I went on to install it. I installed it for my user. Turns out that the Navigator doesn't start.
I also had to install the launcher manually through `conda install launcher` in Terminal.
When I click on the alias in the applications folder, the Navigator pops up in the dock, shows up on the monitor saying initiating and then just disappears.
So, I decided running it from Terminal using `anaconda-navigator` and here's was I got:

`Traceback (most recent call last):
  File "/Users/AI-Mac1/anaconda/bin/anaconda-navigator", line 6, in <module>
    sys.exit(anaconda_navigator.app.main.main())
  File "/Users/AI-Mac1/anaconda/lib/python2.7/site-packages/anaconda_navigator/app/main.py", line 52, in main
    start_app(options)
  File "/Users/AI-Mac1/anaconda/lib/python2.7/site-packages/anaconda_navigator/app/start.py", line 87, in start_app
    window = run_app(splash)
  File "/Users/AI-Mac1/anaconda/lib/python2.7/site-packages/anaconda_navigator/app/start.py", line 42, in run_app
    window = MainWindow(splash=splash)
  File "/Users/AI-Mac1/anaconda/lib/python2.7/site-packages/anaconda_navigator/widgets/main_window.py", line 204, in __init__
    self.environments_tab = EnvironmentsTab(parent=self)
  File "/Users/AI-Mac1/anaconda/lib/python2.7/site-packages/anaconda_navigator/widgets/tabs/environments.py", line 131, in __init__
    data_directory=CHANNELS_PATH,
  File "/Users/AI-Mac1/anaconda/lib/python2.7/site-packages/anaconda_navigator/widgets/manager/packages.py", line 382, in __init__
    self.api.client_set_domain(self.api.client_get_api_url())
  File "/Users/AI-Mac1/anaconda/lib/python2.7/site-packages/anaconda_navigator/api/client_api.py", line 365, in set_domain
    binstar_client.utils.set_config(config)
  File "/Users/AI-Mac1/anaconda/lib/python2.7/site-packages/binstar_client/utils/config.py", line 260, in set_config
    save_config(data, USER_CONFIG if user else SYSTEM_CONFIG)
  File "/Users/AI-Mac1/anaconda/lib/python2.7/site-packages/binstar_client/utils/config.py", line 255, in save_config
    raise BinstarError('%s: %s' % (exc.filename, exc.strerror,))
binstar_client.errors.BinstarError: /Users/AI-Mac1/.continuum/anaconda-client: Permission denied`

Thank You so much in Advance!

**Comment by goanpeca** [comment]
Please open a terminal and run

`rm -rf /Users/AI-Mac1/.continuum`

And try again :-)

**Comment by Alphamineron** [comment]
@goanpeca Thanks You so much! It works now!
Although I have a little doubt!
This is the [Youtube Video](https://www.youtube.com/watch?v=cKxRvEZd3Mw&list=PLOU2XLYxmsIIuiBfYad6rFYQU_jL2ryal&index=7) I was talking about, and there the host just shows a empty terminal like window to code, although I can't figure out how to get to that point....

Thank You Once again
