### ISSUE TITLE
Anaconda Navigator crashing upon start-up

### ISSUE THREAD

**Issue by misc1611** [ContinuumIO/anaconda-issues#1413]
Hi there,
I've just tried running the latest version of Anaconda Navigator (downloaded from Continuum today) on macOS Sierra (10.12.3) and seem to be encountering the same issue as others have described - the app tried loading for about 5 or 10 seconds and then crashes.

It seems the problem still exists, sorry.

**Comment by goanpeca** [comment]
@misc1611 could you go to the terminal and run from there and paste any error trace you see?

`anaconda-navigator`

**Comment by misc1611** [comment]
As requested:

Traceback (most recent call last):
  File "/Applications/anaconda/lib/python3.6/site-packages/binstar_client/utils/config.py", line 250, in save_config
    os.makedirs(data_dir)
  File "/Applications/anaconda/lib/python3.6/os.py", line 220, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/Users/david/.continuum/anaconda-client'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Applications/anaconda/bin/anaconda-navigator", line 6, in <module>
    sys.exit(anaconda_navigator.app.main.main())
  File "/Applications/anaconda/lib/python3.6/site-packages/anaconda_navigator/app/main.py", line 52, in main
    start_app(options)
  File "/Applications/anaconda/lib/python3.6/site-packages/anaconda_navigator/app/start.py", line 87, in start_app
    window = run_app(splash)
  File "/Applications/anaconda/lib/python3.6/site-packages/anaconda_navigator/app/start.py", line 42, in run_app
    window = MainWindow(splash=splash)
  File "/Applications/anaconda/lib/python3.6/site-packages/anaconda_navigator/widgets/main_window.py", line 204, in __init__
    self.environments_tab = EnvironmentsTab(parent=self)
  File "/Applications/anaconda/lib/python3.6/site-packages/anaconda_navigator/widgets/tabs/environments.py", line 131, in __init__
    data_directory=CHANNELS_PATH,
  File "/Applications/anaconda/lib/python3.6/site-packages/anaconda_navigator/widgets/manager/packages.py", line 382, in __init__
    self.api.client_set_domain(self.api.client_get_api_url())
  File "/Applications/anaconda/lib/python3.6/site-packages/anaconda_navigator/api/client_api.py", line 365, in set_domain
    binstar_client.utils.set_config(config)
  File "/Applications/anaconda/lib/python3.6/site-packages/binstar_client/utils/config.py", line 260, in set_config
    save_config(data, USER_CONFIG if user else SYSTEM_CONFIG)
  File "/Applications/anaconda/lib/python3.6/site-packages/binstar_client/utils/config.py", line 255, in save_config
    raise BinstarError('%s: %s' % (exc.filename, exc.strerror,))
binstar_client.errors.BinstarError: /Users/david/.continuum/anaconda-client: Permission denied

**Comment by rficek** [comment]
I have this problem as well. I've tried reinstalling, but the same error keeps occurring. I'm running macOS Sierra 10.12.3.

**Comment by goanpeca** [comment]
You can fix the Issue by removing the `.continuum` folder

Going to the terminal and running

`sudo rm -rf ~/.continuum/`

Should fix it

**Comment by rficek** [comment]
@goanpeca Thank you. It did fix it.

**Comment by misc1611** [comment]
Likewise, working now - thanks goanpeca!

**Comment by goanpeca** [comment]
Glad to hear it is fixed. I am not sure why we are having this issue, luckily the fix is easy :-)
