### ISSUE TITLE
Anaconda-Navigator crushes for Mac OSX 10.10 

### ISSUE THREAD

**Issue by DeanDro** [ContinuumIO/anaconda-issues#1420]
Hello, 
I have downloaded Anaconda twice in case there was an error in the first time, but still can't make it work. I run it through the terminal and this is the response I got. I noticed a similar question from another person, but the response I am getting is slightly different. Can you please advise solution? 

Thanks

Response: 
Traceback (most recent call last):
  File "//anaconda/bin/anaconda-navigator", line 6, in <module>
    sys.exit(anaconda_navigator.app.main.main())
  File "//anaconda/lib/python2.7/site-packages/anaconda_navigator/app/main.py", line 52, in main
    start_app(options)
  File "//anaconda/lib/python2.7/site-packages/anaconda_navigator/app/start.py", line 87, in start_app
    window = run_app(splash)
  File "//anaconda/lib/python2.7/site-packages/anaconda_navigator/app/start.py", line 42, in run_app
    window = MainWindow(splash=splash)
  File "//anaconda/lib/python2.7/site-packages/anaconda_navigator/widgets/main_window.py", line 204, in __init__
    self.environments_tab = EnvironmentsTab(parent=self)
  File "//anaconda/lib/python2.7/site-packages/anaconda_navigator/widgets/tabs/environments.py", line 131, in __init__
    data_directory=CHANNELS_PATH,
  File "//anaconda/lib/python2.7/site-packages/anaconda_navigator/widgets/manager/packages.py", line 382, in __init__
    self.api.client_set_domain(self.api.client_get_api_url())
  File "//anaconda/lib/python2.7/site-packages/anaconda_navigator/api/client_api.py", line 365, in set_domain
    binstar_client.utils.set_config(config)
  File "//anaconda/lib/python2.7/site-packages/binstar_client/utils/config.py", line 260, in set_config
    save_config(data, USER_CONFIG if user else SYSTEM_CONFIG)
  File "//anaconda/lib/python2.7/site-packages/binstar_client/utils/config.py", line 255, in save_config
    raise BinstarError('%s: %s' % (exc.filename, exc.strerror,))
binstar_client.errors.BinstarError: /Users/Dean/.continuum/anaconda-client: Permission denied

**Comment by goanpeca** [comment]
On the terminal please run

`sudo rm -rf ~/.continuum/`

And try again

**Comment by DeanDro** [comment]
It worked! Thank you!
