### ISSUE TITLE
conda create fails with "Access is denied" error

### ISSUE THREAD

**Issue by stmax82** [ContinuumIO/anaconda-issues#1432]
Creating a conda environment with Python 3.4 works successfully:

conda create -p pyenv34 python=3.4

Creating a conda environment with Python 3.5 or 3.6 fails with an error:

```
C:\Users\max\Desktop\...>conda create -p pyenv35 python=3.5
Fetching package metadata .........
Solving package specifications: ..........

Package plan for installation in environment C:\Users\max\Desktop\...\pyenv35:

The following NEW packages will be INSTALLED:

    pip:            9.0.1-py35_1
    python:         3.5.2-0       (copy)
    setuptools:     27.2.0-py35_1 (copy)
    vs2015_runtime: 14.0.25123-0  (copy)
    wheel:          0.29.0-py35_0 (copy)

Proceed ([y]/n)? y

Extracting packages ...
WARNING conda.lock:touch(53): Failed to create lock, do not run conda in parallel processes [errno 13]
An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues



Current conda install:

               platform : win-64
          conda version : 4.2.12
       conda is private : False
      conda-env version : 4.2.12
    conda-build version : not installed
         python version : 3.5.2.final.0
       requests version : 2.11.1
       root environment : C:\Program Files\Miniconda3  (read only)
    default environment : C:\Program Files\Miniconda3
       envs directories : C:\Users\max\.conda\envs
                          C:\Program Files\Miniconda3\envs
          package cache : C:\Users\max\.conda\envs\.pkgs
                          C:\Program Files\Miniconda3\pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
            config file : None
           offline mode : False



`$ C:\Program Files\Miniconda3\Scripts\conda-script.py create -p pyenv35 python=3.5`




    Traceback (most recent call last):
      File "C:\Program Files\Miniconda3\lib\site-packages\conda\exceptions.py", line 479, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "C:\Program Files\Miniconda3\lib\site-packages\conda\cli\main.py", line 145, in _main
        exit_code = args.func(args, p)
      File "C:\Program Files\Miniconda3\lib\site-packages\conda\cli\main_create.py", line 68, in execute
        install(args, parser, 'create')
      File "C:\Program Files\Miniconda3\lib\site-packages\conda\cli\install.py", line 405, in install
        execute_actions(actions, index, verbose=not context.quiet)
      File "C:\Program Files\Miniconda3\lib\site-packages\conda\plan.py", line 643, in execute_actions
        inst.execute_instructions(plan, index, verbose)
      File "C:\Program Files\Miniconda3\lib\site-packages\conda\instructions.py", line 134, in execute_instructions
        cmd(state, arg)
      File "C:\Program Files\Miniconda3\lib\site-packages\conda\instructions.py", line 58, in EXTRACT_CMD
        extract(arg)
      File "C:\Program Files\Miniconda3\lib\site-packages\conda\install.py", line 805, in extract
        t.extractall(path=temp_path)
      File "C:\Program Files\Miniconda3\lib\tarfile.py", line 1996, in extractall
        numeric_owner=numeric_owner)
      File "C:\Program Files\Miniconda3\lib\tarfile.py", line 2038, in extract
        numeric_owner=numeric_owner)
      File "C:\Program Files\Miniconda3\lib\tarfile.py", line 2100, in _extract_member
        os.makedirs(upperdirs)
      File "C:\Program Files\Miniconda3\lib\os.py", line 231, in makedirs
        makedirs(head, mode, exist_ok)
      File "C:\Program Files\Miniconda3\lib\os.py", line 241, in makedirs
        mkdir(name, mode)
    PermissionError: [WinError 5] Access is denied: 'C:\\Program Files\\Miniconda3\\pkgs\\vs2015_runtime-14.0.25123-0.tmp'

```

Note that I'm using Miniconda and I have it installed "for all users", which requires admin privileges during setup - but creating personal conda environments should also work without admin privileges (as it does with Python 3.4), shouldn't it?

**Comment by nehaljwani** [comment]
`4.2.12` is a very old version of conda. Please open the command prompt as administrator, run `conda update conda` and then close and reopen the prompt as normal user and check if the issue persists.
