### ISSUE TITLE
Running spyder from terminal fails in root

### ISSUE THREAD

**Issue by DanielSnipes** [ContinuumIO/anaconda-issues#1439]
Spyder is failing to open when I try to run it from root out of terminal. I get this message:

mbp-dsnipes:python2.7 dsnipes$ conda env list
# conda environments:
#
py3                      //anaconda/envs/py3
python3                  //anaconda/envs/python3
tensorflow               //anaconda/envs/tensorflow
root                  *  //anaconda

mbp-dsnipes:python2.7 dsnipes$ spyder
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
Traceback (most recent call last):
  File "//anaconda/lib/python2.7/site-packages/spyder/app/mainwindow.py", line 2989, in main
    mainwindow = run_spyder(app, options, args)
  File "//anaconda/lib/python2.7/site-packages/spyder/app/mainwindow.py", line 2893, in run_spyder
    main.setup()
  File "//anaconda/lib/python2.7/site-packages/spyder/app/mainwindow.py", line 823, in setup
    self.findinfiles = FindInFiles(self)
  File "//anaconda/lib/python2.7/site-packages/spyder/plugins/findinfiles.py", line 52, in __init__
    include = self.include_patterns()
  File "//anaconda/lib/python2.7/site-packages/spyder/plugins/findinfiles.py", line 105, in include_patterns
    for ext in get_edit_extensions():
  File "//anaconda/lib/python2.7/site-packages/spyder/config/utils.py", line 140, in get_edit_extensions
    edit_filetypes = get_edit_filetypes()
  File "//anaconda/lib/python2.7/site-packages/spyder/config/utils.py", line 118, in get_edit_filetypes
    pygments_exts = _get_pygments_extensions()
  File "//anaconda/lib/python2.7/site-packages/spyder/config/utils.py", line 85, in _get_pygments_extensions
    for lx in lexers.get_all_lexers():
  File "//anaconda/lib/python2.7/site-packages/pygments/lexers/__init__.py", line 53, in get_all_lexers
    for lexer in find_plugin_lexers():
  File "//anaconda/lib/python2.7/site-packages/pygments/plugin.py", line 53, in find_plugin_lexers
    yield entrypoint.load()
  File "//anaconda/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2296, in load
    return self.resolve()
  File "//anaconda/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2302, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "//anaconda/lib/python2.7/site-packages/IPython/__init__.py", line 48, in <module>
    from .core.application import Application
  File "//anaconda/lib/python2.7/site-packages/IPython/core/application.py", line 25, in <module>
    from IPython.core import release, crashhandler
  File "//anaconda/lib/python2.7/site-packages/IPython/core/crashhandler.py", line 28, in <module>
    from IPython.core import ultratb
  File "//anaconda/lib/python2.7/site-packages/IPython/core/ultratb.py", line 128, in <module>
    from IPython.utils.terminal import get_terminal_size
  File "//anaconda/lib/python2.7/site-packages/IPython/utils/terminal.py", line 22, in <module>
    from backports.shutil_get_terminal_size import get_terminal_size as _get_terminal_size
ImportError: No module named shutil_get_terminal_size

**Comment by ccordoba12** [comment]
Did you use `pip` to install some packages instead of conda?

**Comment by DanielSnipes** [comment]
yes

**Comment by csoja** [comment]
This is an old issue.  Please update to the latest version of Spyder and open a new issue if you are still having trouble.
