### ISSUE TITLE
Anaconda navigator 1.4 can't launch on Mac OS

### ISSUE THREAD

**Issue by SHPLIU** [ContinuumIO/anaconda-issues#1449]
I install the latest version of Anaconda Anaconda3-4.3.0-MacOSX-x86_64.pkg. When I launch Anaconda navigator , it spend a long time (5 minutes) to initiate and then quit without any message.
I noticed during the initiating phase, the application connects to internet and inbound 2~3 MB per second for a long time. What's happening?

**Comment by goanpeca** [comment]
@SHPLIU 

Cpuld you open a terminal and launch it from there by typing

`anaconda-navigator`

and paste any output you see ?

**Comment by SHPLIU** [comment]
@goanpeca  Thank you for the quick response. Here is the log.

Traceback (most recent call last):
  File "/Users/i055911/Applications/anaconda/lib/python3.6/site-packages/binstar_client/utils/config.py", line 250, in save_config
    os.makedirs(data_dir)
  File "/Users/i055911/Applications/anaconda/lib/python3.6/os.py", line 220, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/Users/i055911/.continuum/anaconda-client'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/i055911/Applications/anaconda/bin/anaconda-navigator", line 6, in <module>
    sys.exit(anaconda_navigator.app.main.main())
  File "/Users/i055911/Applications/anaconda/lib/python3.6/site-packages/anaconda_navigator/app/main.py", line 52, in main
    start_app(options)
  File "/Users/i055911/Applications/anaconda/lib/python3.6/site-packages/anaconda_navigator/app/start.py", line 87, in start_app
    window = run_app(splash)
  File "/Users/i055911/Applications/anaconda/lib/python3.6/site-packages/anaconda_navigator/app/start.py", line 42, in run_app
    window = MainWindow(splash=splash)
  File "/Users/i055911/Applications/anaconda/lib/python3.6/site-packages/anaconda_navigator/widgets/main_window.py", line 204, in __init__
    self.environments_tab = EnvironmentsTab(parent=self)
  File "/Users/i055911/Applications/anaconda/lib/python3.6/site-packages/anaconda_navigator/widgets/tabs/environments.py", line 131, in __init__
    data_directory=CHANNELS_PATH,
  File "/Users/i055911/Applications/anaconda/lib/python3.6/site-packages/anaconda_navigator/widgets/manager/packages.py", line 382, in __init__
    self.api.client_set_domain(self.api.client_get_api_url())
  File "/Users/i055911/Applications/anaconda/lib/python3.6/site-packages/anaconda_navigator/api/client_api.py", line 365, in set_domain
    binstar_client.utils.set_config(config)
  File "/Users/i055911/Applications/anaconda/lib/python3.6/site-packages/binstar_client/utils/config.py", line 260, in set_config
    save_config(data, USER_CONFIG if user else SYSTEM_CONFIG)
  File "/Users/i055911/Applications/anaconda/lib/python3.6/site-packages/binstar_client/utils/config.py", line 255, in save_config
    raise BinstarError('%s: %s' % (exc.filename, exc.strerror,))
binstar_client.errors.BinstarError: /Users/i055911/.continuum/anaconda-client: Permission denied

**Comment by goanpeca** [comment]
Could you type in the console

`sudo rm -rf ~/.continuum/`

And try launching navigator once more?

**Comment by SHPLIU** [comment]
Great, It works. Thank you very much for this guidance.
Just for improvement, I tried to uninstall Anaconda with anaconda-clean program. I got a message say that /.continuum/ is not removed. But it seems this folder is hidden. I can't see it. Next time, might add your instruction to the uninstall document. 

Anyway, appreciate for your help and enjoy a good day!

**Comment by goanpeca** [comment]
>Great, It works. Thank you very much for this guidance.
Just for improvement, I tried to uninstall Anaconda with anaconda-clean program. I got a message say that /.continuum/ is not removed. But it seems this folder is hidden. I can't see it. Next time, might add your instruction to the uninstall document.

Thanks for the feedback.

Cheers
