### ISSUE TITLE
Jupyter notebook is not launching - No module named environment

### ISSUE THREAD

**Issue by AstridWa** [ContinuumIO/anaconda-issues#1452]
I get this error, any ideas?

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda2\Scripts\jupyter-notebook-script.py", line 3, in <module>
    import notebook.notebookapp
  File "C:\ProgramData\Anaconda2\lib\site-packages\notebook\notebookapp.py", line 28, in <module>
    from jinja2 import Environment, FileSystemLoader
  File "C:\ProgramData\Anaconda2\lib\site-packages\jinja2\__init__.py", line 33, in <module>
    from jinja2.environment import Environment, Template
ImportError: **No module named environment**

**Comment by nehaljwani** [comment]
@AstridWa Could you please share output for 
```bash
conda list -ec
```
