### ISSUE TITLE
Jupyter Notebook not initializing

### ISSUE THREAD

**Issue by bradleyrobinson** [ContinuumIO/anaconda-issues#1458]
Anything with Jupyter Notebook is not working with the Python 3.6 release of Anaconda for me on Windows 10.  The issue appears like this:

Traceback (most recent call last):
  File "C:\Users\bradl\Anaconda3\lib\site-packages\notebook\base\handlers.py", line 503, in wrapper
    result = yield gen.maybe_future(method(self, *args, **kwargs))
  File "C:\Users\bradl\Anaconda3\lib\site-packages\tornado\gen.py", line 1015, in run
    value = future.result()
  File "C:\Users\bradl\Anaconda3\lib\site-packages\tornado\concurrent.py", line 237, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 3, in raise_exc_info
  File "C:\Users\bradl\Anaconda3\lib\site-packages\tornado\gen.py", line 1021, in run
    yielded = self.gen.throw(*exc_info)
  File "C:\Users\bradl\Anaconda3\lib\site-packages\notebook\services\sessions\handlers.py", line 75, in post
    type=mtype))
  File "C:\Users\bradl\Anaconda3\lib\site-packages\tornado\gen.py", line 1015, in run
    value = future.result()
  File "C:\Users\bradl\Anaconda3\lib\site-packages\tornado\concurrent.py", line 237, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 3, in raise_exc_info
  File "C:\Users\bradl\Anaconda3\lib\site-packages\tornado\gen.py", line 1021, in run
    yielded = self.gen.throw(*exc_info)
  File "C:\Users\bradl\Anaconda3\lib\site-packages\notebook\services\sessions\sessionmanager.py", line 79, in create_session
    kernel_id = yield self.start_kernel_for_session(session_id, path, name, type, kernel_name)
  File "C:\Users\bradl\Anaconda3\lib\site-packages\tornado\gen.py", line 1015, in run
    value = future.result()
  File "C:\Users\bradl\Anaconda3\lib\site-packages\tornado\concurrent.py", line 237, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 3, in raise_exc_info
  File "C:\Users\bradl\Anaconda3\lib\site-packages\tornado\gen.py", line 1021, in run
    yielded = self.gen.throw(*exc_info)
  File "C:\Users\bradl\Anaconda3\lib\site-packages\notebook\services\sessions\sessionmanager.py", line 92, in start_kernel_for_session
    self.kernel_manager.start_kernel(path=kernel_path, kernel_name=kernel_name)
  File "C:\Users\bradl\Anaconda3\lib\site-packages\tornado\gen.py", line 1015, in run
    value = future.result()
  File "C:\Users\bradl\Anaconda3\lib\site-packages\tornado\concurrent.py", line 237, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 3, in raise_exc_info
  File "C:\Users\bradl\Anaconda3\lib\site-packages\tornado\gen.py", line 285, in wrapper
    yielded = next(result)
  File "C:\Users\bradl\Anaconda3\lib\site-packages\notebook\services\kernels\kernelmanager.py", line 87, in start_kernel
    super(MappingKernelManager, self).start_kernel(**kwargs)
  File "C:\Users\bradl\Anaconda3\lib\site-packages\jupyter_client\multikernelmanager.py", line 110, in start_kernel
    km.start_kernel(**kwargs)
  File "C:\Users\bradl\Anaconda3\lib\site-packages\jupyter_client\manager.py", line 243, in start_kernel
    **kw)
  File "C:\Users\bradl\Anaconda3\lib\site-packages\jupyter_client\manager.py", line 189, in _launch_kernel
    return launch_kernel(kernel_cmd, **kw)
  File "C:\Users\bradl\Anaconda3\lib\site-packages\jupyter_client\launcher.py", line 123, in launch_kernel
    proc = Popen(cmd, **kwargs)
  File "C:\Users\bradl\Anaconda3\lib\subprocess.py", line 707, in __init__
    restore_signals, start_new_session)
  File "C:\Users\bradl\Anaconda3\lib\subprocess.py", line 990, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified

I did uninstall the previous Python 3.5.2 version of Anaconda because it wasn't allowing me to update to 3.6 (said I had Python 3.4 that was conflicting with Py3.6, don't know why, never installed that on this system ever).

**Comment by bradleyrobinson** [comment]
I've 'replicated' the error on another computer, and this has to do with a buggy install/uninstall. Because Anaconda install/uninstall does not properly set and clean path variables (as well as the registry), this somehow breaks jupyter if you try to uninstall and install Anaconda. The path and registry from the old installation remain on the computer, and some variable (which I cannot figure out what it is) from this old installation breaks Jupyter. It appears that everything else works, though it is quite inconvenient that I can no longer use Jupyter notebooks anymore!  
![bad_uninstall](https://cloud.githubusercontent.com/assets/13645980/26497255/1a14affa-41e8-11e7-9922-2af49da1d953.png)

I'm guessing what will need to be changed (if this is ever fixed) is making sure that something can check for old installs of Anaconda and scrub anything that might cause problems.
