### ISSUE TITLE
#1281 issue in Anaconda3-4.3.0

### ISSUE THREAD

**Issue by striges** [ContinuumIO/anaconda-issues#1470]
Clean installation on ArchLinux. This is reported in #1281. Same error.
Traceback (most recent call last):
  File "./anaconda-navigator", line 6, in <module>
    sys.exit(anaconda_navigator.app.main.main())
  File "/home/sugar/test111/lib/python3.6/site-packages/anaconda_navigator/app/main.py", line 52, in main
    start_app(options)
  File "/home/sugar/test111/lib/python3.6/site-packages/anaconda_navigator/app/start.py", line 87, in start_app
    window = run_app(splash)
  File "/home/sugar/test111/lib/python3.6/site-packages/anaconda_navigator/app/start.py", line 42, in run_app
    window = MainWindow(splash=splash)
  File "/home/sugar/test111/lib/python3.6/site-packages/anaconda_navigator/widgets/main_window.py", line 160, in __init__
    self.api = AnacondaAPI()
  File "/home/sugar/test111/lib/python3.6/site-packages/anaconda_navigator/api/anaconda_api.py", line 711, in AnacondaAPI
    ANACONDA_API = _AnacondaAPI()
  File "/home/sugar/test111/lib/python3.6/site-packages/anaconda_navigator/api/anaconda_api.py", line 49, in __init__
    self._conda_api = CondaAPI()
  File "/home/sugar/test111/lib/python3.6/site-packages/anaconda_navigator/api/conda_api.py", line 1302, in CondaAPI
    CONDA_API = _CondaAPI()
  File "/home/sugar/test111/lib/python3.6/site-packages/anaconda_navigator/api/conda_api.py", line 307, in __init__
    self.set_root_prefix()
  File "/home/sugar/test111/lib/python3.6/site-packages/anaconda_navigator/api/conda_api.py", line 427, in set_root_prefix
    self.ROOT_PREFIX = info['root_prefix']
TypeError: byte indices must be integers or slices, not str

conda info
Current conda install:

               platform : linux-64
          conda version : 4.3.8
       conda is private : False
      conda-env version : 4.3.8
    conda-build version : not installed
         python version : 3.6.0.final.0
       requests version : 2.12.4
       root environment : /home/sugar/test111  (writable)
    default environment : /home/sugar/test111
       envs directories : /home/sugar/test111/envs
          package cache : /home/sugar/test111/pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/linux-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : None
           offline mode : False
             user-agent : conda/4.3.8 requests/2.12.4 CPython/3.6.0 Linux/4.4.49-1-lts arch/ glibc/2.24
                UID:GID : 1000:1000

**Comment by goanpeca** [comment]
It seems conda is not correctly set on thw PATH

**Comment by striges** [comment]
OK. Is there a way to let anaconda-navigator add `prefix/bin` into PATH, without change the PATH beforehand. Currently I am wrapping it with a shell-script.

**Comment by mingwandroid** [comment]
You should let conda's activate script manage your environment activation:

`source /home/sugar/test111/bin/activate`

**Comment by striges** [comment]
Sadly no tcsh support. Anyway thank you @mingwandroid

**Comment by mingwandroid** [comment]
`tcsh` does not provide an equivalent of `$BASH_SOURCE` when sourced which makes it difficult to support.

**Comment by grantrostig** [comment]
@goanpeca, what do you mean about having to sett the path correctly?  
conda does not require that the path be set, according to install script default.
Also the documentation states to accept the "bad" default and doesn't mention needing to set the path.

BTW, all the Linux program/collections that I use, allow the programs to be run from their directory.

I reinstalled and had it change my path and then it worked, but the bug/documenation defect still stands.

Same error on Fedora 24 linux.  I installed:
$ sh ./Anaconda3-4.3.0-Linux-x86_64.sh
into ~/bin
accepted all other defaults (including NOT to add anaconda to my path _as recommended_ !)
$ cd ~/bin/anaconda3/bin
$ ./anaconda-navigator 
ERROR: 
Traceback (most recent call last):
  File "./anaconda-navigator", line 6, in <module>
    sys.exit(anaconda_navigator.app.main.main())
  File "/home/user1/bin/anaconda3/lib/python3.6/site-packages/anaconda_navigator/app/main.py", line 52, in main
    start_app(options)
  File "/home/user1/bin/anaconda3/lib/python3.6/site-packages/anaconda_navigator/app/start.py", line 87, in start_app
    window = run_app(splash)
  File "/home/user1/bin/anaconda3/lib/python3.6/site-packages/anaconda_navigator/app/start.py", line 42, in run_app
    window = MainWindow(splash=splash)
  File "/home/user1/bin/anaconda3/lib/python3.6/site-packages/anaconda_navigator/widgets/main_window.py", line 160, in __init__
    self.api = AnacondaAPI()
  File "/home/user1/bin/anaconda3/lib/python3.6/site-packages/anaconda_navigator/api/anaconda_api.py", line 711, in AnacondaAPI
    ANACONDA_API = _AnacondaAPI()
  File "/home/user1/bin/anaconda3/lib/python3.6/site-packages/anaconda_navigator/api/anaconda_api.py", line 49, in __init__
    self._conda_api = CondaAPI()
  File "/home/user1/bin/anaconda3/lib/python3.6/site-packages/anaconda_navigator/api/conda_api.py", line 1302, in CondaAPI
    CONDA_API = _CondaAPI()
  File "/home/user1/bin/anaconda3/lib/python3.6/site-packages/anaconda_navigator/api/conda_api.py", line 307, in __init__
    self.set_root_prefix()
  File "/home/user1/bin/anaconda3/lib/python3.6/site-packages/anaconda_navigator/api/conda_api.py", line 427, in set_root_prefix
    self.ROOT_PREFIX = info['root_prefix']
TypeError: byte indices must be integers or slices, not str
[user1@localhost bin]$ 

I speculate is a error (or related error not caught in testing) in the install script that has been present for months and variants of it have been reported on github months ago.

Note that my installation of fedora has some files called:
$ whereis anaconda
anaconda: /usr/sbin/anaconda /usr/libexec/anaconda /usr/share/anaconda

These files and packages (begin with "@" in list below) had been installed by some other linux package for some other reason, but this should not interfere with an isolated installation of anaconda, or at least the installed should detect it as a problem:

[user1@localhost bin]$ dnf list | grep anaconda
anaconda.x86_64                          24.13.7-1.fc24                 @koji-override-0
anaconda-core.x86_64                     24.13.7-1.fc24                 @koji-override-0
anaconda-gui.x86_64                      24.13.7-1.fc24                 @koji-override-0
anaconda-tui.x86_64                      24.13.7-1.fc24                 @koji-override-0
anaconda-user-help.noarch                22.4-4.fc24                    @koji-override-0
anaconda-widgets.x86_64                  24.13.7-1.fc24                 @koji-override-0
libreport-anaconda.x86_64                2.7.2-1.fc24                   @updates
anaconda-dracut.x86_64                   24.13.7-1.fc24                 fedora  
anaconda-realmd.noarch                   0.2-5.fc24                     fedora  
anaconda-widgets.i686                    24.13.7-1.fc24                 fedora  
anaconda-widgets-devel.i686              24.13.7-1.fc24                 fedora  
anaconda-widgets-devel.x86_64            24.13.7-1.fc24                 fedora  
docker-anaconda-addon.noarch             0.2-1.fc24                     fedora  
kexec-tools-anaconda-addon.x86_64        2.0.12-7.fc24.1                updates 
oscap-anaconda-addon.noarch              0.7-1.fc22                     fedora  

###
