### ISSUE TITLE
Anaconda Navigator won't run on Windows 7 32-bit

### ISSUE THREAD

**Issue by bignosebadhair** [ContinuumIO/anaconda-issues#1481]
Hey guys,

So I just downloaded the latest Anaconda 4.3.0.1 32-bit version. The setup went through without a glitch. But now when I run it directly from the start menu nothing happens. I tried running to from a console and this is the output I get:

```
D:\Anaconda3>anaconda-navigator
Traceback (most recent call last):
  File "D:\Anaconda3\Scripts\anaconda-navigator-script.py", line 5, in <module>
    sys.exit(anaconda_navigator.app.main.main())
  File "D:\Anaconda3\lib\site-packages\anaconda_navigator\app\main.py", line 47,
 in main
    from anaconda_navigator.utils.logs import clean_logs
  File "D:\Anaconda3\lib\site-packages\anaconda_navigator\utils\__init__.py", li
ne 15, in <module>
    from qtpy.QtGui import QIcon
  File "D:\Anaconda3\lib\site-packages\qtpy\QtGui.py", line 20, in <module>
    from PyQt5.QtGui import *
ImportError: DLL load failed: The specified procedure could not be found.
```

My system state at this point was:

```
D:\Anaconda3>conda info
Current conda install:

               platform : win-32
          conda version : 4.3.8
       conda is private : False
      conda-env version : 4.3.8
    conda-build version : not installed
         python version : 3.6.0.final.0
       requests version : 2.12.4
       root environment : D:\Anaconda3  (writable)
    default environment : D:\Anaconda3
       envs directories : D:\Anaconda3\envs
          package cache : D:\Anaconda3\pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/win-32
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/win-32
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/win-32
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-32
                          https://repo.continuum.io/pkgs/msys2/noarch
            config file : None
           offline mode : False
             user-agent : conda/4.3.8 requests/2.12.4 CPython/3.6.0 Windows/7 Wi
ndows/6.1.7601


D:\Anaconda3>conda list
# packages in environment at D:\Anaconda3:
#
_license                  1.1                      py36_1
alabaster                 0.7.9                    py36_0
anaconda                  4.3.0               np111py36_0
anaconda-client           1.6.0                    py36_0
anaconda-navigator        1.4.3                    py36_0
astroid                   1.4.9                    py36_0
astropy                   1.3                 np111py36_0
babel                     2.3.4                    py36_0
backports                 1.0                      py36_0
beautifulsoup4            4.5.3                    py36_0
bitarray                  0.8.1                    py36_1
blaze                     0.10.1                   py36_0
bokeh                     0.12.4                   py36_0
boto                      2.45.0                   py36_0
bottleneck                1.2.0               np111py36_0
bzip2                     1.0.6                    vc14_3  [vc14]
cffi                      1.9.1                    py36_0
chardet                   2.3.0                    py36_0
chest                     0.2.3                    py36_0
click                     6.7                      py36_0
cloudpickle               0.2.2                    py36_0
clyent                    1.2.2                    py36_0
colorama                  0.3.7                    py36_0
comtypes                  1.1.2                    py36_0
conda                     4.3.8                    py36_0
conda-env                 2.6.0                         0
configobj                 5.0.6                    py36_0
console_shortcut          0.1.1                    py36_1
contextlib2               0.5.4                    py36_0
cryptography              1.7.1                    py36_0
curl                      7.52.1                   vc14_0  [vc14]
cycler                    0.10.0                   py36_0
cython                    0.25.2                   py36_0
cytoolz                   0.8.2                    py36_0
dask                      0.13.0                   py36_0
datashape                 0.5.4                    py36_0
decorator                 4.0.11                   py36_0
dill                      0.2.5                    py36_0
docutils                  0.13.1                   py36_0
entrypoints               0.2.2                    py36_0
et_xmlfile                1.0.1                    py36_0
fastcache                 1.0.2                    py36_1
flask                     0.12                     py36_0
flask-cors                3.0.2                    py36_0
freetype                  2.5.5                    vc14_2  [vc14]
get_terminal_size         1.0.0                    py36_0
gevent                    1.2.1                    py36_0
greenlet                  0.4.11                   py36_0
h5py                      2.6.0               np111py36_2
hdf5                      1.8.15.1                 vc14_4  [vc14]
heapdict                  1.0.0                    py36_1
icu                       57.1                     vc14_0  [vc14]
idna                      2.2                      py36_0
imagesize                 0.7.1                    py36_0
ipykernel                 4.5.2                    py36_0
ipython                   5.1.0                    py36_0
ipython_genutils          0.1.0                    py36_0
ipywidgets                5.2.2                    py36_1
isort                     4.2.5                    py36_0
itsdangerous              0.24                     py36_0
jdcal                     1.3                      py36_0
jedi                      0.9.0                    py36_1
jinja2                    2.9.4                    py36_0
jpeg                      9b                       vc14_0  [vc14]
jsonschema                2.5.1                    py36_0
jupyter                   1.0.0                    py36_3
jupyter_client            4.4.0                    py36_0
jupyter_console           5.0.0                    py36_0
jupyter_core              4.2.1                    py36_0
lazy-object-proxy         1.2.2                    py36_0
libpng                    1.6.27                   vc14_0  [vc14]
libtiff                   4.0.6                    vc14_3  [vc14]
llvmlite                  0.15.0                   py36_0
locket                    0.2.0                    py36_1
lxml                      3.7.2                    py36_0
markupsafe                0.23                     py36_2
matplotlib                2.0.0               np111py36_0
menuinst                  1.4.4                    py36_0
mistune                   0.7.3                    py36_0
mkl                       2017.0.1                      0
mkl-service               1.1.2                    py36_3
mpmath                    0.19                     py36_1
multipledispatch          0.4.9                    py36_0
nbconvert                 4.2.0                    py36_0
nbformat                  4.2.0                    py36_0
networkx                  1.11                     py36_0
nltk                      3.2.2                    py36_0
nose                      1.3.7                    py36_1
notebook                  4.3.1                    py36_1
numba                     0.30.1              np111py36_0
numexpr                   2.6.1               np111py36_2
numpy                     1.11.3                   py36_0
numpydoc                  0.6.0                    py36_0
odo                       0.5.0                    py36_1
openpyxl                  2.4.1                    py36_0
openssl                   1.0.2k                   vc14_0  [vc14]
pandas                    0.19.2              np111py36_1
partd                     0.3.7                    py36_0
path.py                   10.0                     py36_0
pathlib2                  2.2.0                    py36_0
patsy                     0.4.1                    py36_0
pep8                      1.7.0                    py36_0
pickleshare               0.7.4                    py36_0
pillow                    4.0.0                    py36_0
pip                       9.0.1                    py36_1
ply                       3.9                      py36_0
prompt_toolkit            1.0.9                    py36_0
psutil                    5.0.1                    py36_0
py                        1.4.32                   py36_0
pyasn1                    0.1.9                    py36_0
pycosat                   0.6.1                    py36_1
pycparser                 2.17                     py36_0
pycrypto                  2.6.1                    py36_5
pycurl                    7.43.0                   py36_2
pyflakes                  1.5.0                    py36_0
pygments                  2.1.3                    py36_0
pylint                    1.6.4                    py36_1
pyopenssl                 16.2.0                   py36_0
pyparsing                 2.1.4                    py36_0
pyqt                      5.6.0                    py36_2
pytables                  3.2.2               np111py36_4
pytest                    3.0.5                    py36_0
python                    3.6.0                         0
python-dateutil           2.6.0                    py36_0
pytz                      2016.10                  py36_0
pywin32                   220                      py36_2
pyyaml                    3.12                     py36_0
pyzmq                     16.0.2                   py36_0
qt                        5.6.2                    vc14_3  [vc14]
qtawesome                 0.4.3                    py36_0
qtconsole                 4.2.1                    py36_2
qtpy                      1.2.1                    py36_0
requests                  2.12.4                   py36_0
rope                      0.9.4                    py36_1
ruamel_yaml               0.11.14                  py36_1
scikit-image              0.12.3              np111py36_1
scikit-learn              0.18.1              np111py36_1
scipy                     0.18.1              np111py36_1
seaborn                   0.7.1                    py36_0
setuptools                27.2.0                   py36_1
simplegeneric             0.8.1                    py36_1
singledispatch            3.4.0.3                  py36_0
sip                       4.18                     py36_0
six                       1.10.0                   py36_0
snowballstemmer           1.2.1                    py36_0
sockjs-tornado            1.0.3                    py36_0
sphinx                    1.5.1                    py36_0
spyder                    3.1.2                    py36_0
sqlalchemy                1.1.5                    py36_0
statsmodels               0.6.1               np111py36_1
sympy                     1.0                      py36_0
tk                        8.5.18                   vc14_0  [vc14]
toolz                     0.8.2                    py36_0
tornado                   4.4.2                    py36_0
traitlets                 4.3.1                    py36_0
unicodecsv                0.14.1                   py36_0
vs2015_runtime            14.0.25123                    0
wcwidth                   0.1.7                    py36_0
werkzeug                  0.11.15                  py36_0
wheel                     0.29.0                   py36_0
widgetsnbextension        1.2.6                    py36_0
win_unicode_console       0.5                      py36_0
wrapt                     1.10.8                   py36_0
xlrd                      1.0.0                    py36_0
xlsxwriter                0.9.6                    py36_0
xlwings                   0.10.2                   py36_0
xlwt                      1.2.0                    py36_0
zlib                      1.2.8                    vc14_3  [vc14]
```

Next I tried updating the Navigator as below but the result was the same error message above.
```
D:\Anaconda3>conda update anaconda-navigator
```
I then tried a full update as below but the issue still remains.
```
D:\Anaconda3>conda update conda
D:\Anaconda3>conda update --all

D:\Anaconda3>conda list
# packages in environment at D:\Anaconda3:
#
_license                  1.1                      py36_1
alabaster                 0.7.9                    py36_0
anaconda                  custom                   py36_0
anaconda-client           1.6.2                    py36_0
anaconda-navigator        1.4.3                    py36_0
astroid                   1.4.9                    py36_0
astropy                   1.3                 np111py36_0
babel                     2.3.4                    py36_0
backports                 1.0                      py36_0
beautifulsoup4            4.5.3                    py36_0
bitarray                  0.8.1                    py36_1
blaze                     0.10.1                   py36_0
bleach                    1.5.0                    py36_0
bokeh                     0.12.4                   py36_0
boto                      2.45.0                   py36_0
bottleneck                1.2.0               np111py36_0
bzip2                     1.0.6                    vc14_3  [vc14]
cffi                      1.9.1                    py36_0
chardet                   2.3.0                    py36_0
chest                     0.2.3                    py36_0
click                     6.7                      py36_0
cloudpickle               0.2.2                    py36_0
clyent                    1.2.2                    py36_0
colorama                  0.3.7                    py36_0
comtypes                  1.1.2                    py36_0
conda                     4.3.13                   py36_0
conda-env                 2.6.0                         0
configobj                 5.0.6                    py36_0
console_shortcut          0.1.1                    py36_1
contextlib2               0.5.4                    py36_0
cryptography              1.7.1                    py36_0
curl                      7.52.1                   vc14_0  [vc14]
cycler                    0.10.0                   py36_0
cython                    0.25.2                   py36_0
cytoolz                   0.8.2                    py36_0
dask                      0.13.0                   py36_0
datashape                 0.5.4                    py36_0
decorator                 4.0.11                   py36_0
dill                      0.2.5                    py36_0
docutils                  0.13.1                   py36_0
entrypoints               0.2.2                    py36_1
et_xmlfile                1.0.1                    py36_0
fastcache                 1.0.2                    py36_1
flask                     0.12                     py36_0
flask-cors                3.0.2                    py36_0
freetype                  2.5.5                    vc14_2  [vc14]
get_terminal_size         1.0.0                    py36_0
gevent                    1.2.1                    py36_0
greenlet                  0.4.12                   py36_0
h5py                      2.6.0               np111py36_2
hdf5                      1.8.15.1                 vc14_4  [vc14]
heapdict                  1.0.0                    py36_1
html5lib                  0.999                    py36_0
icu                       57.1                     vc14_0  [vc14]
idna                      2.2                      py36_0
imagesize                 0.7.1                    py36_0
ipykernel                 4.5.2                    py36_0
ipython                   5.1.0                    py36_0
ipython_genutils          0.1.0                    py36_0
ipywidgets                5.2.2                    py36_1
isort                     4.2.5                    py36_0
itsdangerous              0.24                     py36_0
jdcal                     1.3                      py36_0
jedi                      0.9.0                    py36_1
jinja2                    2.9.5                    py36_0
jpeg                      9b                       vc14_0  [vc14]
jsonschema                2.5.1                    py36_0
jupyter                   1.0.0                    py36_3
jupyter_client            5.0.0                    py36_0
jupyter_console           5.1.0                    py36_0
jupyter_core              4.3.0                    py36_0
lazy-object-proxy         1.2.2                    py36_0
libpng                    1.6.27                   vc14_0  [vc14]
libtiff                   4.0.6                    vc14_3  [vc14]
llvmlite                  0.16.0                   py36_0
locket                    0.2.0                    py36_1
lxml                      3.7.3                    py36_0
markupsafe                0.23                     py36_2
matplotlib                2.0.0               np111py36_0
menuinst                  1.4.4                    py36_0
mistune                   0.7.3                    py36_0
mkl                       2017.0.1                      0
mkl-service               1.1.2                    py36_3
mpmath                    0.19                     py36_1
multipledispatch          0.4.9                    py36_0
nbconvert                 5.1.1                    py36_0
nbformat                  4.3.0                    py36_0
networkx                  1.11                     py36_0
nltk                      3.2.2                    py36_0
nose                      1.3.7                    py36_1
notebook                  4.3.1                    py36_1
numba                     0.31.0              np111py36_0
numexpr                   2.6.2               np111py36_0
numpy                     1.11.3                   py36_0
numpydoc                  0.6.0                    py36_0
odo                       0.5.0                    py36_1
olefile                   0.44                     py36_0
openpyxl                  2.4.1                    py36_0
openssl                   1.0.2k                   vc14_0  [vc14]
pandas                    0.19.2              np111py36_1
pandocfilters             1.4.1                    py36_0
partd                     0.3.7                    py36_0
path.py                   10.1                     py36_0
pathlib2                  2.2.0                    py36_0
patsy                     0.4.1                    py36_0
pep8                      1.7.0                    py36_0
pickleshare               0.7.4                    py36_0
pillow                    4.0.0                    py36_1
pip                       9.0.1                    py36_1
ply                       3.10                     py36_0
prompt_toolkit            1.0.9                    py36_0
psutil                    5.1.3                    py36_0
py                        1.4.32                   py36_0
pyasn1                    0.1.9                    py36_0
pycosat                   0.6.1                    py36_1
pycparser                 2.17                     py36_0
pycrypto                  2.6.1                    py36_5
pycurl                    7.43.0                   py36_2
pyflakes                  1.5.0                    py36_0
pygments                  2.2.0                    py36_0
pylint                    1.6.4                    py36_1
pyopenssl                 16.2.0                   py36_0
pyparsing                 2.1.4                    py36_0
pyqt                      5.6.0                    py36_2
pytables                  3.2.2               np111py36_4
pytest                    3.0.5                    py36_0
python                    3.6.0                         0
python-dateutil           2.6.0                    py36_0
pytz                      2016.10                  py36_0
pywin32                   220                      py36_2
pyyaml                    3.12                     py36_0
pyzmq                     16.0.2                   py36_0
qt                        5.6.2                    vc14_3  [vc14]
qtawesome                 0.4.4                    py36_0
qtconsole                 4.2.1                    py36_2
qtpy                      1.2.1                    py36_0
requests                  2.13.0                   py36_0
rope                      0.9.4                    py36_1
ruamel_yaml               0.11.14                  py36_1
scikit-image              0.12.3              np111py36_1
scikit-learn              0.18.1              np111py36_1
scipy                     0.18.1              np111py36_1
seaborn                   0.7.1                    py36_0
setuptools                27.2.0                   py36_1
simplegeneric             0.8.1                    py36_1
singledispatch            3.4.0.3                  py36_0
sip                       4.18                     py36_0
six                       1.10.0                   py36_0
snowballstemmer           1.2.1                    py36_0
sockjs-tornado            1.0.3                    py36_0
sphinx                    1.5.1                    py36_0
spyder                    3.1.3                    py36_0
sqlalchemy                1.1.5                    py36_0
statsmodels               0.8.0               np111py36_0
sympy                     1.0                      py36_0
testpath                  0.3                      py36_0
tk                        8.5.18                   vc14_0  [vc14]
toolz                     0.8.2                    py36_0
tornado                   4.4.2                    py36_0
traitlets                 4.3.2                    py36_0
unicodecsv                0.14.1                   py36_0
vs2015_runtime            14.0.25123                    0
wcwidth                   0.1.7                    py36_0
werkzeug                  0.11.15                  py36_0
wheel                     0.29.0                   py36_0
widgetsnbextension        1.2.6                    py36_0
win_unicode_console       0.5                      py36_0
wrapt                     1.10.8                   py36_0
xlrd                      1.0.0                    py36_0
xlsxwriter                0.9.6                    py36_0
xlwings                   0.10.2                   py36_0
xlwt                      1.2.0                    py36_0
zlib                      1.2.8                    vc14_3  [vc14]
```

I installed it on my D: drive instead of the default path because of a free space constraint. 

I tried a reinstall (uninstall+reboot+install) too without any success.

Could someone please help me out here? Is there any more information I need to provide?

**Comment by mingwandroid** [comment]
Hi @bignosebadhair, some questions:

1. Did you elect to add let the installer add Anaconda to your PATH?
2. How did you launch your command prompt

Thanks.

**Comment by bignosebadhair** [comment]
Hi @mingwandroid 

> 1. Did you elect to let the installer add Anaconda to your PATH?
Yes. 
> 2. How did you launch your command prompt?
First from the standard windows command prompt. And then using the console provided by Anaconda. Both resulted in the same error message.

**Comment by mingwandroid** [comment]
Thanks. From the `Anaconda Prompt`, can you enter the following and paste the results of each line?

```
where Qt5Core.dll
where qmake
where python
where pythonw
qmake -query
```

Thanks.

**Comment by bignosebadhair** [comment]
```
(D:\Anaconda3) D:\Anaconda3>where Qt5Core.dll
D:\Anaconda3\Library\bin\Qt5Core.dll

(D:\Anaconda3) D:\Anaconda3>where qmake
D:\Anaconda3\Library\bin\qmake.exe

(D:\Anaconda3) D:\Anaconda3>where python
D:\Anaconda3\python.exe

(D:\Anaconda3) D:\Anaconda3>where pythonw
D:\Anaconda3\pythonw.exe

(D:\Anaconda3) D:\Anaconda3>qmake -query
QT_SYSROOT:
QT_INSTALL_PREFIX:D:/Anaconda3/Library
QT_INSTALL_ARCHDATA:D:/Anaconda3/Library
QT_INSTALL_DATA:D:/Anaconda3/Library
QT_INSTALL_DOCS:D:/Anaconda3/Library/doc
QT_INSTALL_HEADERS:D:/Anaconda3/Library/include/qt
QT_INSTALL_LIBS:D:/Anaconda3/Library/lib
QT_INSTALL_LIBEXECS:D:/Anaconda3/Library/bin
QT_INSTALL_BINS:D:/Anaconda3/Library/bin
QT_INSTALL_TESTS:D:/Anaconda3/Library/tests
QT_INSTALL_PLUGINS:D:/Anaconda3/Library/plugins
QT_INSTALL_IMPORTS:D:/Anaconda3/Library/imports
QT_INSTALL_QML:D:/Anaconda3/Library/qml
QT_INSTALL_TRANSLATIONS:D:/Anaconda3/Library/translations
QT_INSTALL_CONFIGURATION:
QT_INSTALL_EXAMPLES:D:/Anaconda3/Library/examples
QT_INSTALL_DEMOS:D:/Anaconda3/Library/examples
QT_HOST_PREFIX:D:/Anaconda3/Library
QT_HOST_DATA:D:/Anaconda3/Library
QT_HOST_BINS:D:/Anaconda3/Library/bin
QT_HOST_LIBS:D:/Anaconda3/Library/lib
QMAKE_SPEC:win32-msvc2015
QMAKE_XSPEC:win32-msvc2015
QMAKE_VERSION:3.0
QT_VERSION:5.6.2
```

**Comment by mingwandroid** [comment]
What version of Windows do you run?

**Comment by mingwandroid** [comment]
Can you show me the value (from cmd.exe) of your PATH by: `echo %PATH%`.

Also can you try launching Navigator from the Start Menu again while running `procmon.exe` (https://technet.microsoft.com/en-us/sysinternals/processmonitor.aspx) filtering to exclude all programs not called pythonw.exe?

If you  need more detailed instructions the let me know.

**Comment by bignosebadhair** [comment]
Hi @mingwandroid 

The output of my environment variable is below.
```
D:\Anaconda3>echo %PATH%
C:\ProgramData\Oracle\Java\javapath;C:\Perl\site\bin;C:\Perl\bin;C:\Python27\;C:
\Python27\Scripts;C:\Program Files\Intel\iCLS Client\;C:\Windows\system32;C:\Win
dows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Pro
gram Files\QT Lite\QTSystem;C:\Program Files\Box\Box Edit\;C:\Program Files\Inte
l\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Mana
gement Engine Components\IPT;C:\Program Files\Lenovo\Access Connections\;C:\Prog
ram Files\TortoiseSVN\bin;C:\Program Files\IAR Systems\Embedded Workbench 6.4\ar
m\bin;C:\Program Files\QT Lite\QTSystem\;C:\Python27\Lib\site-packages\py2exe;C:
\wamp\bin\mysql\mysql5.7.9\bin;C:\wamp\bin\apache\apache2.4.17\bin;D:\Program Fi
les\Git\cmd;D:\Program Files\Git\mingw32\bin;D:\Program Files\Git\usr\bin;C:\Pro
gram Files\WebEx\PTools020000000;C:\Program Files\1E\NomadBranch\;D:\Anaconda3\L
ibrary\lib\;D:\Anaconda3\Library\include\qt\;D:\Anaconda3\Lib\site-packages\;D:\
Anaconda3\lib\site-packages\qtpy\;D:\Anaconda3;D:\Anaconda3\Scripts;D:\Anaconda3
\Library\bin;
```

I've got the output of procmon filtered for pythonw. What format would you like me to upload it in? The default .PML isn't allowed. I tried compressing it to a .zip but that didn't allow me to upload either.

**Comment by mingwandroid** [comment]
Save it as a csv, and make sure to not save filtered events and you can either attach it here, or email it to me rdonnelly@continuum.io

Thanks.

**Comment by bignosebadhair** [comment]
I apologize for the delay. Unfortunately my hard disk crashed and a week of trying to recover it went nowhere. I've now got a 64-bit version of Windows where the Navigator opens fine. 

Thanks for trying to help me out.
