### ISSUE TITLE
Anaconda Navigator and Spyder install errors - Mac OS X Sierra

### ISSUE THREAD

**Issue by eseba** [ContinuumIO/anaconda-issues#1486]
Trying to get Anaconda installed, getting errors when I run Navigator and Spyder.  Most likely due to permissions... I've seen this error mentioned on other posts, but the suggested fixes have yet to work for  me (could definitely be user error though as I am new to Mac environment).

```
Erics-iMac:~ ericmseba$ conda info
Current conda install:

               platform : osx-64
          conda version : 4.3.8
       conda is private : False
      conda-env version : 4.3.8
    conda-build version : not installed
         python version : 3.6.0.final.0
       requests version : 2.12.4
       root environment : /Users/ericmseba/anaconda  (writable)
    default environment : /Users/ericmseba/anaconda
       envs directories : /Users/ericmseba/anaconda/envs
          package cache : /Users/ericmseba/anaconda/pkgs
           channel URLs : https://conda.anaconda.org/anaconda-fusion/osx-64
                          https://conda.anaconda.org/anaconda-fusion/noarch
                          https://repo.continuum.io/pkgs/free/osx-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/osx-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/osx-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : /Users/ericmseba/.condarc
           offline mode : False
             user-agent : conda/4.3.8 requests/2.12.4 CPython/3.6.0 Darwin/16.1.0 OSX/10.12.1
                UID:GID : 501:20
```

I launch Navigator from terminal and this is what I get... it launches but with errors:

```
Erics-iMac:~ ericmseba$ anaconda-navigator
2017-02-27 19:52:29,464 - ERROR download_api._download:189
Invalid url https://pbs.twimg.com/profile_images/624030560457850880/17LrFnZt_400x400.png>

2017-02-27 19:52:29,764 - ERROR download_api._download:189
Invalid url https://pbs.twimg.com/profile_images/624030560457850880/17LrFnZt_400x400.png

2017-02-27 19:52:30,092 - ERROR download_api._download:189
Invalid url https://pbs.twimg.com/profile_images/1678023092/DSC_Logo_400x400.jpg

2017-02-27 19:52:30,418 - ERROR download_api._download:189
Invalid url `https://pbs.twimg.com/profile_images/1678023092/DSC_Logo_400x400.jpg

```
Navigator comes up but when I click on Spyder it starts to launch but then dies...

```
Failed to write user configuration file.
Please submit a bug report.
Traceback (most recent call last):
  File "/Users/ericmseba/anaconda/lib/python3.6/site-packages/spyder/utils/external/lockfile.py", line 150, in lock
    symlink(str(os.getpid()), self.name)
FileExistsError: [Errno 17] File exists: '516' -> '/Users/ericmseba/.spyder-py3/spyder.lock'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/ericmseba/anaconda/lib/python3.6/site-packages/spyder/utils/external/lockfile.py", line 177, in lock
    kill(int(pid), 0)
ProcessLookupError: [Errno 3] No such process

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/ericmseba/anaconda/lib/python3.6/site-packages/spyder/app/start.py", line 77, in main
    lock_created = lock.lock()
  File "/Users/ericmseba/anaconda/lib/python3.6/site-packages/spyder/utils/external/lockfile.py", line 196, in lock
    rmlink(self.name)
PermissionError: [Errno 13] Permission denied: '/Users/ericmseba/.spyder-py3/spyder.lock'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/ericmseba/anaconda/lib/python3.6/site-packages/spyder/config/user.py", line 111, in _save
    _write_file(fname)
  File "/Users/ericmseba/anaconda/lib/python3.6/site-packages/spyder/config/user.py", line 107, in _write_file
    with open(fname, 'w', encoding='utf-8') as configfile:
PermissionError: [Errno 13] Permission denied: '/Users/ericmseba/.spyder-py3/spyder.ini'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/ericmseba/anaconda/bin/spyder", line 6, in <module>
    sys.exit(spyder.app.start.main())
  File "/Users/ericmseba/anaconda/lib/python3.6/site-packages/spyder/app/start.py", line 97, in main
    from spyder.app import mainwindow
  File "/Users/ericmseba/anaconda/lib/python3.6/site-packages/spyder/app/mainwindow.py", line 115, in <module>
    from spyder.utils.qthelpers import qapplication, MENU_SEPARATOR
  File "/Users/ericmseba/anaconda/lib/python3.6/site-packages/spyder/utils/qthelpers.py", line 26, in <module>
    from spyder.config.gui import get_shortcut
  File "/Users/ericmseba/anaconda/lib/python3.6/site-packages/spyder/config/gui.py", line 168, in <module>
    set_default_color_scheme(_name, replace=False)
  File "/Users/ericmseba/anaconda/lib/python3.6/site-packages/spyder/config/gui.py", line 164, in set_default_color_scheme
    set_color_scheme(name, sh.get_color_scheme(name), replace=replace)
  File "/Users/ericmseba/anaconda/lib/python3.6/site-packages/spyder/config/gui.py", line 158, in set_color_scheme
    CONF.set(section, "names", sorted(list(set(names))))
  File "/Users/ericmseba/anaconda/lib/python3.6/site-packages/spyder/config/user.py", line 437, in set
    self._save()
  File "/Users/ericmseba/anaconda/lib/python3.6/site-packages/spyder/config/user.py", line 121, in _save
    raise(e)
  File "/Users/ericmseba/anaconda/lib/python3.6/site-packages/spyder/config/user.py", line 115, in _save
    os.remove(fname)
PermissionError: [Errno 13] Permission denied: '/Users/ericmseba/.spyder-py3/spyder.ini'
```

Any thoughts? Thank you in advance.

**Comment by ccordoba12** [comment]
I don't know why you don't have permissions to write in your own home directory. That's the problem here.

**Comment by goanpeca** [comment]
It seems you used sudo at some point?

Either way maybe removing the spyder folder could help

`rm -rf /Users/ericmseba/.spyder-py3/`

**Comment by eseba** [comment]
Getting closer... Spyder errors look cleaned up but now getting this Jupyter error, oddly enough when I launch Spyder:

```
Erics-iMac:~ ericmseba$ anaconda-navigator
2017-02-27 21:18:47,294 - ERROR download_api._download:189
Invalid url https://pbs.twimg.com/profile_images/624030560457850880/17LrFnZt_400x400.png

2017-02-27 21:18:47,595 - ERROR download_api._download:189
Invalid url https://pbs.twimg.com/profile_images/1678023092/DSC_Logo_400x400.jpg

2017-02-27 21:18:47,937 - ERROR download_api._download:189
Invalid url https://pbs.twimg.com/profile_images/624030560457850880/17LrFnZt_400x400.png

2017-02-27 21:18:48,287 - ERROR download_api._download:189
Invalid url https://pbs.twimg.com/profile_images/1678023092/DSC_Logo_400x400.jpg

[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
Traceback (most recent call last):
  File "/Users/ericmseba/anaconda/lib/python3.6/site-packages/spyder/app/mainwindow.py", line 2989, in main
    mainwindow = run_spyder(app, options, args)
  File "/Users/ericmseba/anaconda/lib/python3.6/site-packages/spyder/app/mainwindow.py", line 2893, in run_spyder
    main.setup()
  File "/Users/ericmseba/anaconda/lib/python3.6/site-packages/spyder/app/mainwindow.py", line 1109, in setup
    self.setup_layout(default=False)
  File "/Users/ericmseba/anaconda/lib/python3.6/site-packages/spyder/app/mainwindow.py", line 1380, in setup_layout
    self.setup_default_layouts('default', settings)
  File "/Users/ericmseba/anaconda/lib/python3.6/site-packages/spyder/app/mainwindow.py", line 1559, in setup_default_layouts
    widget.toggle_view(True)
  File "/Users/ericmseba/anaconda/lib/python3.6/site-packages/spyder/plugins/ipythonconsole.py", line 682, in toggle_view
    self.create_new_client(give_focus=False)
  File "/Users/ericmseba/anaconda/lib/python3.6/site-packages/spyder/plugins/ipythonconsole.py", line 914, in create_new_client
    self.connect_client_to_kernel(client)
  File "/Users/ericmseba/anaconda/lib/python3.6/site-packages/spyder/plugins/ipythonconsole.py", line 933, in connect_client_to_kernel
    stderr_file)
  File "/Users/ericmseba/anaconda/lib/python3.6/site-packages/spyder/plugins/ipythonconsole.py", line 1331, in create_kernel_manager_and_kernel_client
    kernel_manager.start_kernel(stderr=stderr)
  File "/Users/ericmseba/anaconda/lib/python3.6/site-packages/jupyter_client/manager.py", line 224, in start_kernel
    self.write_connection_file()
  File "/Users/ericmseba/anaconda/lib/python3.6/site-packages/jupyter_client/connect.py", line 407, in write_connection_file
    kernel_name=self.kernel_name
  File "/Users/ericmseba/anaconda/lib/python3.6/site-packages/jupyter_client/connect.py", line 135, in write_connection_file
    with open(fname, 'w') as f:
PermissionError: [Errno 13] Permission denied: '/Users/ericmseba/Library/Jupyter/runtime/kernel-0e98fcf7f490.json'
```
In terminal would I type

`sudo rm -rf /Users/ericmseba/Library/Jupyter/`

or something similar? Or is there something else going on here?

**Comment by goanpeca** [comment]
@ccordoba12  :-| ?

**Comment by ccordoba12** [comment]
You should restore the right permissions to your own user using the `chown` command. However, I've never done that in Mac.

Maybe @mingwandroid could be of help here.

**Comment by mingwandroid** [comment]
`chown` can be used just the same, yes.

**Comment by ccordoba12** [comment]
I didn't know how to get user and group id on Mac. Thanks for the tip @mingwandroid!

**Comment by eseba** [comment]
Success!  Spyder and Jupiter both launch now. Final code after running Navigator in terminal:

```
Erics-iMac:~ ericmseba$ anaconda-navigator
2017-02-28 07:31:09,221 - ERROR download_api._download:189
Invalid url https://pbs.twimg.com/profile_images/624030560457850880/17LrFnZt_400x400.png

2017-02-28 07:31:09,541 - ERROR download_api._download:189
Invalid url https://pbs.twimg.com/profile_images/1678023092/DSC_Logo_400x400.jpg

2017-02-28 07:31:09,863 - ERROR download_api._download:189
Invalid url https://pbs.twimg.com/profile_images/624030560457850880/17LrFnZt_400x400.png

2017-02-28 07:31:10,193 - ERROR download_api._download:189
Invalid url https://pbs.twimg.com/profile_images/1678023092/DSC_Logo_400x400.jpg

[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
```

Hopefully I'm all set now.  Thanks everyone for all your help!

**Comment by ccordoba12** [comment]
Glad to help!

**Comment by Siemingfong** [comment]
I got the same problem solve successfully.
