### ISSUE TITLE
Anaconda Navigator Launching Issue (Initializing) 

### ISSUE THREAD

**Issue by Mustak944** [ContinuumIO/anaconda-issues#1487]
When i try to launch my Anaconda Navigator directly from launchpad it closes after showing the "initializing" message. and when i tried it from my terminal after updating everything even the Navigator itself. It gives me this message (below). 

```
Mustaks-MBP:~ Mustak$ anaconda-navigator
Traceback (most recent call last):
  File "/Users/Mustak/anaconda3/lib/python3.6/site-packages/binstar_client/utils/config.py", line 250, in save_config
    os.makedirs(data_dir)
  File "/Users/Mustak/anaconda3/lib/python3.6/os.py", line 220, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/Users/Mustak/.continuum/anaconda-client'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/Mustak/anaconda3/bin/anaconda-navigator", line 6, in <module>
    sys.exit(anaconda_navigator.app.main.main())
  File "/Users/Mustak/anaconda3/lib/python3.6/site-packages/anaconda_navigator/app/main.py", line 52, in main
    start_app(options)
  File "/Users/Mustak/anaconda3/lib/python3.6/site-packages/anaconda_navigator/app/start.py", line 87, in start_app
    window = run_app(splash)
  File "/Users/Mustak/anaconda3/lib/python3.6/site-packages/anaconda_navigator/app/start.py", line 42, in run_app
    window = MainWindow(splash=splash)
  File "/Users/Mustak/anaconda3/lib/python3.6/site-packages/anaconda_navigator/widgets/main_window.py", line 204, in __init__
    self.environments_tab = EnvironmentsTab(parent=self)
  File "/Users/Mustak/anaconda3/lib/python3.6/site-packages/anaconda_navigator/widgets/tabs/environments.py", line 131, in __init__
    data_directory=CHANNELS_PATH,
  File "/Users/Mustak/anaconda3/lib/python3.6/site-packages/anaconda_navigator/widgets/manager/packages.py", line 382, in __init__
    self.api.client_set_domain(self.api.client_get_api_url())
  File "/Users/Mustak/anaconda3/lib/python3.6/site-packages/anaconda_navigator/api/client_api.py", line 365, in set_domain
    binstar_client.utils.set_config(config)
  File "/Users/Mustak/anaconda3/lib/python3.6/site-packages/binstar_client/utils/config.py", line 260, in set_config
    save_config(data, USER_CONFIG if user else SYSTEM_CONFIG)
  File "/Users/Mustak/anaconda3/lib/python3.6/site-packages/binstar_client/utils/config.py", line 255, in save_config
    raise BinstarError('%s: %s' % (exc.filename, exc.strerror,))
binstar_client.errors.BinstarError: /Users/Mustak/.continuum/anaconda-client: Permission denied
```

I'm using 
macOS Sierra 10.12.3

**Comment by Mustak944** [comment]
Problem Solved-
To fix the issue you will need to remove the .continuum folder located in your user folder (it is a hidden folder!)

```
You can open a terminal and run

sudo rm -rf ~/.continuum/
```

This solution was found here- 
https://groups.google.com/a/continuum.io/forum/#!topic/anaconda/2Gjx2go_btM
