### ISSUE TITLE
What is the problem that Anaconda-Navigator is not launched MacOS Sierra 10.12.3?

### ISSUE THREAD

**Issue by irobiul** [ContinuumIO/anaconda-issues#1488]
` anaconda-navigator

Traceback (most recent call last):
  File "/Users/robiulislam/anaconda/bin/anaconda-navigator", line 6, in <module>
    sys.exit(anaconda_navigator.app.main.main())
  File "/Users/robiulislam/anaconda/lib/python3.6/site-packages/anaconda_navigator/app/main.py", line 51, in main
    from anaconda_navigator.app.start import start_app
  File "/Users/robiulislam/anaconda/lib/python3.6/site-packages/anaconda_navigator/app/start.py", line 23, in <module>
    from anaconda_navigator.widgets.dialogs.splash import SplashScreen
  File "/Users/robiulislam/anaconda/lib/python3.6/site-packages/anaconda_navigator/widgets/__init__.py", line 20, in <module>
    from anaconda_navigator.utils.analytics import GATracker
  File "/Users/robiulislam/anaconda/lib/python3.6/site-packages/anaconda_navigator/utils/analytics.py", line 39, in <module>
    from anaconda_navigator.api.anaconda_api import AnacondaAPI
  File "/Users/robiulislam/anaconda/lib/python3.6/site-packages/anaconda_navigator/api/anaconda_api.py", line 24, in <module>
    from anaconda_navigator.api.client_api import ClientAPI
  File "/Users/robiulislam/anaconda/lib/python3.6/site-packages/anaconda_navigator/api/client_api.py", line 20, in <module>
    from binstar_client.utils import get_config, set_config
  File "/Users/robiulislam/anaconda/lib/python3.6/site-packages/binstar_client/__init__.py", line 10, in <module>
    from .errors import *
  File "/Users/robiulislam/anaconda/lib/python3.6/site-packages/binstar_client/errors.py", line 1, in <module>
    from clyent.errors import ClyentError
  File "/Users/robiulislam/anaconda/lib/python3.6/site-packages/clyent/__init__.py", line 10, in <module>
    from pkg_resources import iter_entry_points
ModuleNotFoundError: No module named 'pkg_resources'`

**Comment by Chen9228** [comment]
same problem. Even after reinstalled the anaconda still give the same message

**Comment by goanpeca** [comment]
Seem you are missing setuptools

If you go to a terminal and type

`conda install setuptools -f` does it fix your problem?

**Comment by sellensr** [comment]
probably unrelated, but I just tracked down a problem that crashed 1.4.3 of navigator because somehow the .continuum directory in my user directory had become owned by root. It didn't cause a problem in the previous release. chown solved the problem. Same OS version

**Comment by irobiul** [comment]
Thanks @goanpeca  . It's works like magic

**Comment by PankajGitProject** [comment]
Thank you, the solution still works.
