### ISSUE TITLE
navigator can't open

### ISSUE THREAD

**Issue by zaharzhong** [ContinuumIO/anaconda-issues#1496]
```
Traceback (most recent call last):
  File "E:\Anaconda2\Scripts\anaconda-navigator-script.py", line 5, in <module>
    sys.exit(anaconda_navigator.app.main.main())
  File "E:\Anaconda2\lib\site-packages\anaconda_navigator\app\main.py", line 52, in main
    start_app(options)
  File "E:\Anaconda2\lib\site-packages\anaconda_navigator\app\start.py", line 87, in start_app
    window = run_app(splash)
  File "E:\Anaconda2\lib\site-packages\anaconda_navigator\app\start.py", line 42, in run_app
    window = MainWindow(splash=splash)
  File "E:\Anaconda2\lib\site-packages\anaconda_navigator\widgets\main_window.py", line 160, in __init__
    self.api = AnacondaAPI()
  File "E:\Anaconda2\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 711, in AnacondaAPI
    ANACONDA_API = _AnacondaAPI()
  File "E:\Anaconda2\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 49, in __init__
    self._conda_api = CondaAPI()
  File "E:\Anaconda2\lib\site-packages\anaconda_navigator\api\conda_api.py", line 1302, in CondaAPI
    CONDA_API = _CondaAPI()
  File "E:\Anaconda2\lib\site-packages\anaconda_navigator\api\conda_api.py", line 307, in __init__
    self.set_root_prefix()
  File "E:\Anaconda2\lib\site-packages\anaconda_navigator\api\conda_api.py", line 427, in set_root_prefix
    self.ROOT_PREFIX = info['root_prefix']
TypeError: list indices must be integers, not str
```

**Comment by zaharzhong** [comment]
It is latest version.Anaconda2-4.3.0.1-Windows-x86_64

**Comment by goanpeca** [comment]
@zaharzhong, could you open the anaconda prompt and type

`conda info --json` and paste the results

and `conda list` and pste the results?

Cheers

**Comment by Mizzourah2006** [comment]
I'm having the same error as above and this is what I am getting the following from both: Import Error: No module named ruamel.yaml.comments

**Comment by zaharzhong** [comment]
@goanpeca I can‘t open the anaconda prompt of anaconda2.I'm using Anaconda3 now.
I‘m not sure whether the previously installed python2 has been uninstalled properly but I can‘t find python2 in the program list,registry and environment variable.

**Comment by goanpeca** [comment]
@zaharzhong I srongly advice you remove all your previous installations and reinstall for `The current user` only and not `All users`.
