### ISSUE TITLE
Bad Magic Number with Accelerate and Py 3.5 environment

### ISSUE THREAD

**Issue by AlbertDeFusco** [ContinuumIO/anaconda-issues#1498]
I have installed Anaconda 4.3.0 (Python 3.6) on OSX.

In the root environment Accelerate works fine.

```
adefusco@0235-adefusco:~>conda install accelerate
Fetching package metadata ...........
Solving package specifications: .

Package plan for installation in environment /Users/adefusco/Applications/anaconda43:

The following NEW packages will be INSTALLED:

    accelerate:         2.3.1-np111py36_0
    accelerate_cudalib: 2.0-0
    cudatoolkit:        7.5-0
    snakeviz:           0.4.1-py36_0

The following packages will be UPDATED:

    anaconda:           4.3.0-np111py36_0  --> custom-py36_0
    conda:              4.3.8-py36_0       --> 4.3.13-py36_0

The following packages will be DOWNGRADED due to dependency conflicts:

    mkl:                2017.0.1-0         --> 11.3.3-0
    numexpr:            2.6.1-np111py36_2  --> 2.6.1-np111py36_1
    numpy:              1.11.3-py36_0      --> 1.11.2-py36_0
    scikit-learn:       0.18.1-np111py36_1 --> 0.18.1-np111py36_0
    scipy:              0.18.1-np111py36_1 --> 0.18.1-np111py36_0

Proceed ([y]/n)? y

accelerate_cud 100% |###################################################################| Time: 0:00:00  11.51 MB/s
cudatoolkit-7. 100% |###################################################################| Time: 0:00:15  14.96 MB/s
mkl-11.3.3-0.t 100% |###################################################################| Time: 0:00:07  15.09 MB/s
anaconda-custo 100% |###################################################################| Time: 0:00:00   4.03 MB/s
numpy-1.11.2-p 100% |###################################################################| Time: 0:00:00  14.49 MB/s
numexpr-2.6.1- 100% |###################################################################| Time: 0:00:00  12.90 MB/s
scipy-0.18.1-n 100% |###################################################################| Time: 0:00:00  15.14 MB/s
snakeviz-0.4.1 100% |###################################################################| Time: 0:00:00  12.70 MB/s
scikit-learn-0 100% |###################################################################| Time: 0:00:00  12.88 MB/s
conda-4.3.13-p 100% |###################################################################| Time: 0:00:00  15.59 MB/s
accelerate-2.3 100% |###################################################################| Time: 0:00:00  14.45 MB/s
python -c 'import sys;print(sys.version);import accelerate;print(accelerate.__version__)'
3.6.0 |Anaconda custom (x86_64)| (default, Dec 23 2016, 13:19:00)
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)]
2.3.1
```

When I make a Py 3.5 environment with Accelerate I cannot import it.

```
adefusco@0235-adefusco:~>conda create -n acc python=3.5 accelerate
Fetching package metadata ...........
Solving package specifications: .

Package plan for installation in environment /Users/adefusco/Applications/anaconda43/envs/acc:

The following NEW packages will be INSTALLED:

    accelerate:         2.3.1-np111py35_0
    accelerate_cudalib: 2.0-0

... <output truncated> ...

adefusco@0235-adefusco:~>source activate acc
(acc) adefusco@0235-adefusco:~>python -c 'import sys;print(sys.version);import accelerate;print(accelerate.__version__)'
3.5.3 |Continuum Analytics, Inc.| (default, Feb 22 2017, 20:51:01)
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)]
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/adefusco/Applications/anaconda43/envs/acc/lib/python3.5/site-packages/accelerate/__init__.py", line 5, in <module>
    from accelerate import config
ImportError: bad magic number in 'accelerate.config': b'\x16\r\r\n'
```

**Comment by AlbertDeFusco** [comment]
It was discovered that Python 3.5.3 has a different magic number than previous 3.5.x versions.

Py 3.5.1

```
conda create -n py351 python=3.5.1
/Users/adefusco/Applications/anaconda3/4.3.0/envs/py351/bin/python -c 'import imp;print(imp.get_magic())'
b'\x16\r\r\n'
```

Py 3.5.2

```
conda create -n py352 python=3.5.2
/Users/adefusco/Applications/anaconda3/4.3.0/envs/py352/bin/python -c 'import imp;print(imp.get_magic())'
b'\x16\r\r\n' 
```


Py 3.5.3

```
conda create -n py353 python=3.5.3
/Users/adefusco/Applications/anaconda3/4.3.0/envs/py353/bin/python -c 'import imp;print(imp.get_magic())'
b'\x17\r\r\n'
```


http://bugs.python.org/issue29514

**Comment by ilanschnell** [comment]
CPython 3.5.3 has bumped the pyc-file magic number due to a bug in how BUILD_MAP_UNPACK_WITH_CALL was compiled.  We applying a work around that will accept the old magic number when loading .pyc's
