### ISSUE TITLE
anaconda navigator crashing Mac OS

### ISSUE THREAD

**Issue by felipehduek** [ContinuumIO/anaconda-issues#1518]
Dear All,

anaconda navigator 1.5 
spyder 3.1.3 python 2.7 

I'm having a lot of trouble opening anaconda navigator in my Mac 10.12.3
Whenever I click the Icon, the program start loading and then crashes...
The only I came up with to open it, is by terminal, and then typing sudo anaconda-navigator
, my password, and then it finally opens!

I tried entering HD>anaconda and change the sharing permission but it didn't worked out...

Thank you for the attention.

**Comment by goanpeca** [comment]
@felipehduek could you paster the error trace you get when you run from the terminal?

If it is related to a permissions error in a `.continuum` folder, you could do:

`sudo rm -rf ~/.continuum/` to fix it

**Comment by felipehduek** [comment]
even after trying 
`sudo rm -rf ~/.continuum/` - anaconda navigator now opens, but when I try to open spyder, it keeps loading and it doesn't open...

`Last login: Thu Mar 16 14:48:51 on ttys000
Felipes-MacBook:~ felipehenriqueduek$ anaconda-navigator
Traceback (most recent call last):
  File "/anaconda/lib/python2.7/site-packages/anaconda_navigator/widgets/main_window.py", line 1049, in launch_application
    root_prefix=self.api.ROOT_PREFIX
  File "/anaconda/lib/python2.7/site-packages/anaconda_navigator/utils/launch.py", line 156, in launch
    root_prefix=root_prefix
  File "/anaconda/lib/python2.7/site-packages/anaconda_navigator/utils/launch.py", line 97, in run_app_on_unix
    suffix,
  File "/anaconda/lib/python2.7/site-packages/anaconda_navigator/utils/launch.py", line 127, in create_app_run_script
    os.chmod(fpath, 0o777)
OSError: [Errno 1] Operation not permitted: '/Users/felipehenriqueduek/.anaconda/navigator/scripts/spyder.sh'
2017-03-16 14:51:10,854 - ERROR download_api._download:189
Invalid url https://pbs.twimg.com/profile_images/624030560457850880/17LrFnZt_400x400.png

2017-03-16 14:51:11,165 - ERROR download_api._download:189
Invalid url https://pbs.twimg.com/profile_images/1678023092/DSC_Logo_400x400.jpg

2017-03-16 14:51:11,504 - ERROR download_api._download:189
Invalid url https://pbs.twimg.com/profile_images/624030560457850880/17LrFnZt_400x400.png

2017-03-16 14:51:12,469 - ERROR download_api._download:189
Invalid url https://pbs.twimg.com/profile_images/1678023092/DSC_Logo_400x400.jpg


`

**Comment by goanpeca** [comment]
@felipehduek could delete the `.anaconda` folder as well?

`sudo rm -rf ~/.anaconda/`

`sudo rm -rf ~/.continuum/`

?

**Comment by felipehduek** [comment]
finally! thank you so much
@goanpeca
