### ISSUE TITLE
anaconda navigator won't launch after the recent update. Mac OX system

### ISSUE THREAD

**Issue by WilliamHsu09** [ContinuumIO/anaconda-issues#1521]
the anaconda navigator does not launch after the most recent update of anaconda. (the launch was okay before). Have tried to uninstall and reinstall, it just doesn't work. 
When trying to launch at the terminal, it reads as follows. Any thoughts on this?

Traceback (most recent call last):
  File "/Users/xxx/anaconda3/lib/python3.6/site-packages/binstar_client/utils/config.py", line 250, in save_config
    os.makedirs(data_dir)
  File "/Users/xxx/anaconda3/lib/python3.6/os.py", line 220, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/Users/xxx/.continuum/anaconda-client'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/xxx/anaconda3/bin/anaconda-navigator", line 6, in <module>
    sys.exit(anaconda_navigator.app.main.main())
  File "/Users/xxx/anaconda3/lib/python3.6/site-packages/anaconda_navigator/app/main.py", line 52, in main
    start_app(options)
  File "/Users/xxx/anaconda3/lib/python3.6/site-packages/anaconda_navigator/app/start.py", line 87, in start_app
    window = run_app(splash)
  File "/Users/xxx/anaconda3/lib/python3.6/site-packages/anaconda_navigator/app/start.py", line 42, in run_app
    window = MainWindow(splash=splash)
  File "/Users/xxx/anaconda3/lib/python3.6/site-packages/anaconda_navigator/widgets/main_window.py", line 206, in __init__
    self.environments_tab = EnvironmentsTab(parent=self)
  File "/Users/xxx/anaconda3/lib/python3.6/site-packages/anaconda_navigator/widgets/tabs/environments.py", line 131, in __init__
    data_directory=CHANNELS_PATH,
  File "/Users/xxx/anaconda3/lib/python3.6/site-packages/anaconda_navigator/widgets/manager/packages.py", line 382, in __init__
    self.api.client_set_domain(self.api.client_get_api_url())
  File "/Users/xxx/anaconda3/lib/python3.6/site-packages/anaconda_navigator/api/client_api.py", line 365, in set_domain
    binstar_client.utils.set_config(config)
  File "/Users/xxx/anaconda3/lib/python3.6/site-packages/binstar_client/utils/config.py", line 260, in set_config
    save_config(data, USER_CONFIG if user else SYSTEM_CONFIG)
  File "/Users/xxx/anaconda3/lib/python3.6/site-packages/binstar_client/utils/config.py", line 255, in save_config
    raise BinstarError('%s: %s' % (exc.filename, exc.strerror,))
binstar_client.errors.BinstarError: /Users/xxx/.continuum/anaconda-client: Permission denied

**Comment by felipehduek** [comment]
I have the same problem here!
does it works when you type sudo anaconda-navigator ?

**Comment by WilliamHsu09** [comment]
The sudo does work, though there are errors following. 

eduroam-169-233-202-227:~ xxx$ sudo anaconda-navigator
Password:

2017-03-14 19:06:55,050 - ERROR download_api._download:189
Invalid url https://pbs.twimg.com/profile_images/624030560457850880/17LrFnZt_400x400.png

2017-03-14 19:06:55,686 - ERROR download_api._download:189
Invalid url https://pbs.twimg.com/profile_images/1678023092/DSC_Logo_400x400.jpg

2017-03-14 19:06:59,915 - ERROR download_api._download:189
Invalid url https://pbs.twimg.com/profile_images/624030560457850880/17LrFnZt_400x400.png

2017-03-14 19:07:00,550 - ERROR download_api._download:189
Invalid url https://pbs.twimg.com/profile_images/1678023092/DSC_Logo_400x400.jpg

**Comment by felipehduek** [comment]
I'm facing a similar problem...

**Comment by ccordoba12** [comment]
Please run

    sudo rm -rf ~/.continuum

to fix the problem.

**Comment by felipehduek** [comment]
it worked! thank you so much
@ccordoba12

**Comment by Jelena11** [comment]
Please check the file ownership with
`ls -la /Users/<USER>/.continuum`
if you have root as owner, then change the owner of the folder
`sudo chown <USER> /Users/<USER>/.continuum`
This worked for me.
