### ISSUE TITLE
can't start jupyter notebook from window cmd - ImportError: cannot import name '_overlapped'

### ISSUE THREAD

**Issue by kamelchaker** [ContinuumIO/anaconda-issues#1570]
see exceptions below 
C:\Users\Kamel>jupyter notebook
Traceback (most recent call last):
  File "C:\Users\Kamel\Anaconda3\lib\asyncio\__init__.py", line 16, in <module>
    from . import _overlapped
ImportError: cannot import name '_overlapped'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Kamel\Anaconda3\Scripts\jupyter-notebook-script.py", line 3, in
 <module>
    import notebook.notebookapp
  File "C:\Users\Kamel\Anaconda3\lib\site-packages\notebook\notebookapp.py", lin
e 28, in <module>
    from jinja2 import Environment, FileSystemLoader
  File "C:\Users\Kamel\Anaconda3\lib\site-packages\jinja2\__init__.py", line 81,
 in <module>
    _patch_async()
  File "C:\Users\Kamel\Anaconda3\lib\site-packages\jinja2\__init__.py", line 77,
 in _patch_async
    from jinja2.asyncsupport import patch_all
  File "C:\Users\Kamel\Anaconda3\lib\site-packages\jinja2\asyncsupport.py", line
 13, in <module>
    import asyncio
  File "C:\Users\Kamel\Anaconda3\lib\asyncio\__init__.py", line 18, in <module>
    import _overlapped  # Will also be exported.
OSError: [WinError 10106] The requested service provider could not be loaded or
initialized

C:\Users\Kamel>

**Comment by Django-xinfa** [comment]
It has been so long. Why is'nt there any ways?

**Comment by zmhhmz** [comment]
I've just come across the same problem. Still no answer??
