### ISSUE TITLE
Anaconda3 4.3.1 Windows 64-bit throws error: "AttributeError: '_NamespacePath' object has no attribute 'sort':

### ISSUE THREAD

**Issue by woodblair** [ContinuumIO/anaconda-issues#1573]
I installed Anaconda3 4.3.1 on Windows 10 (64-bit). but nothing works. It stuck at following error:

Traceback (most recent call last):
  File "C:\Users\weiminli\Anaconda3\Scripts\conda-script.py", line 5, in <module>
    sys.exit(conda.cli.main())
  File "C:\Users\weiminli\Anaconda3\lib\site-packages\conda\cli\main.py", line 151, in main
    activate.main()
  File "C:\Users\weiminli\Anaconda3\lib\site-packages\conda\cli\activate.py", line 118, in main
    from conda.utils import shells
  File "C:\Users\weiminli\Anaconda3\lib\site-packages\conda\utils.py", line 13, in <module>
    from .gateways.disk.read import compute_md5sum
  File "C:\Users\weiminli\Anaconda3\lib\site-packages\conda\gateways\disk\read.py", line 22, in <module>
    from ...models.channel import Channel
  File "C:\Users\weiminli\Anaconda3\lib\site-packages\conda\models\channel.py", line 9, in <module>
    from ..base.context import context
  File "C:\Users\weiminli\Anaconda3\lib\site-packages\conda\base\context.py", line 19, in <module>
    from .._vendor.auxlib.path import expand
  File "C:\Users\weiminli\Anaconda3\lib\site-packages\conda\_vendor\auxlib\path.py", line 8, in <module>
    import pkg_resources
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 646, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 616, in _load_backward_compatible
  File "C:\Users\weiminli\Anaconda3\lib\site-packages\setuptools-27.2.0-py3.6.egg\pkg_resources\__init__.py", line 2985, in <module>
  File "C:\Users\weiminli\Anaconda3\lib\site-packages\setuptools-27.2.0-py3.6.egg\pkg_resources\__init__.py", line 2971, in _call_aside
  File "C:\Users\weiminli\Anaconda3\lib\site-packages\setuptools-27.2.0-py3.6.egg\pkg_resources\__init__.py", line 3013, in _initialize_master_working_set
  File "C:\Users\weiminli\Anaconda3\lib\site-packages\setuptools-27.2.0-py3.6.egg\pkg_resources\__init__.py", line 2544, in activate
  File "C:\Users\weiminli\Anaconda3\lib\site-packages\setuptools-27.2.0-py3.6.egg\pkg_resources\__init__.py", line 2118, in declare_namespace
  File "C:\Users\weiminli\Anaconda3\lib\site-packages\setuptools-27.2.0-py3.6.egg\pkg_resources\__init__.py", line 2058, in _handle_ns
  File "C:\Users\weiminli\Anaconda3\lib\site-packages\setuptools-27.2.0-py3.6.egg\pkg_resources\__init__.py", line 2087, in _rebuild_mod_path
AttributeError: '_NamespacePath' object has no attribute 'sort'

**Comment by mingwandroid** [comment]
At what point is it stuck? During install or after install when trying to use it?

How did you install it? `All Users` or `Just Me`? Did you elect to allow the installer to modify your `PATH` or not?

If it got stuck after install when trying to use it, how did you launch the console? A normal `cmd.exe` prompt or using the `Anaconda Prompt`?

**Comment by woodblair** [comment]
Hi Ray,
I choose "Just Me"  and default tp allow the installer to modify PATH.
The error was thrown after installation, when starting Anaconda Prompt,, Jupyter Notebook, or IPython, ., etc. basically nothing usable. here caused by the same error as shown above.

May be some environment need to be  checked?  where to find the installation log file?

Please help.

Regards,
-weimin

**Comment by mingwandroid** [comment]
Please launch the `Anaconda Prompt` from your `Start Menu` and show the output from:

`echo %PATH%`

**Comment by woodblair** [comment]
Below was executed within Anaconda Prompt. I still get the error when start it.
Note I installed Anacoda again and selected the target location at: "C:\Users\Anaconda3"
-------------------------------------------------------------------

C:\Users\weiminli>echo %PATH%
C:\ProgramData\Oracle\Java\javapath;C:\Program Files\Common Files\Microsoft Shared\Windows Live;C:\Program Files (x86)\Common Files\Microsoft Shared\Windows Live;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;c:\Program Files (x86)\Common Files\Roxio Shared\DLLShared\;c:\Program Files (x86)\Common Files\Roxio Shared\12.0\DLLShared\;C:\Program Files (x86)\Windows Live\Shared;c:\Program Files (x86)\Microsoft SQL Server\100\Tools\Binn\;c:\Program Files\Microsoft SQL Server\100\Tools\Binn\;c:\Program Files\Microsoft SQL Server\100\DTS\Binn\;c:\Program Files (x86)\Microsoft ASP.NET\ASP.NET Web Pages\v1.0\;C:\Program Files (x86)\Microsoft SQL Server\110\Tools\Binn\;C:\Program Files\Microsoft SQL Server\110\Tools\Binn\;C:\Program Files\Microsoft SQL Server\110\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\110\Tools\Binn\ManagementStudio\;C:\Program Files (x86)\Microsoft Visual Studio 10.0\Common7\IDE\PrivateAssemblies\;C:\Program Files (x86)\Microsoft SQL Server\110\DTS\Binn\;C:\Program Files (x86)\Windows Kits\8.0\Windows Performance Toolkit\;C:\Program Files\Microsoft\Web Platform Installer\;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\QuickTime\QTSystem\;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files\Git\cmd;C:\Program Files\Java\jdk1.8.0_92\bin;C:\Program Files\nodejs\;C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit\;C:\Program Files\CMake\bin;C:\Hadoop\apache-maven-3.3.9\bin;C:\Program Files\Git\usr\bin;C:\ProtocolBuffer;C:\Program Files (x86)\Skype\Phone\;C:\Users\Anaconda3;C:\Users\Anaconda3\Scripts;C:\Users\Anaconda3\Library\bin;C:\Program Files\Java\jdk1.8.0_92\bin;C:\Users\weiminli\AppData\Roaming\npm;C:\Users\weiminli\AppData\Local\Microsoft\WindowsApps

**Comment by avaghefi** [comment]
I have the exact same problem. Any ideas?

**Comment by oozliuoo** [comment]
same problem on Mac, any updates?

**Comment by nehaljwani** [comment]
Related: https://github.com/pypa/setuptools/commit/d9125bcb60fa2e1a5270259dad6b6a94c8f61cde and https://github.com/pypa/setuptools/issues/885 and https://github.com/pypa/setuptools/commit/3943cf4

**Comment by gigglegrig** [comment]
same problem. what I found is I only have this problem when using full version of Anaconda, but the problem won't occur if I install Jupyter Notebook using Miniconda.

**Comment by code3hr** [comment]
is there any solution to this problem? cus i have the same issue

**Comment by Aisuko** [comment]
I downloaded Anaconda3 and create new enviroment env_python36_for_dl , when i open terminal input `pip`, the error appear as

```
Traceback (most recent call last):
  File "C:\Users\Yurak\AppData\Local\conda\conda\envs\env_python36_for_dl\Scripts\pip-script.py", line 3, in <module>
    import pip
  File "C:\Users\Yurak\AppData\Local\conda\conda\envs\env_python36_for_dl\lib\site-packages\pip\__init__.py", line 26, in <module>
    from pip.utils import get_installed_distributions, get_prog
  File "C:\Users\Yurak\AppData\Local\conda\conda\envs\env_python36_for_dl\lib\site-packages\pip\utils\__init__.py", line 27, in <module>
    from pip._vendor import pkg_resources
  File "C:\Users\Yurak\AppData\Local\conda\conda\envs\env_python36_for_dl\lib\site-packages\pip\_vendor\pkg_resources\__init__.py", line 3018, in <module>
    @_call_aside
  File "C:\Users\Yurak\AppData\Local\conda\conda\envs\env_python36_for_dl\lib\site-packages\pip\_vendor\pkg_resources\__init__.py", line 3004, in _call_aside
    f(*args, **kwargs)
  File "C:\Users\Yurak\AppData\Local\conda\conda\envs\env_python36_for_dl\lib\site-packages\pip\_vendor\pkg_resources\__init__.py", line 3046, in _initialize_master_working_set
    dist.activate(replace=False)
  File "C:\Users\Yurak\AppData\Local\conda\conda\envs\env_python36_for_dl\lib\site-packages\pip\_vendor\pkg_resources\__init__.py", line 2578, in activate
    declare_namespace(pkg)
  File "C:\Users\Yurak\AppData\Local\conda\conda\envs\env_python36_for_dl\lib\site-packages\pip\_vendor\pkg_resources\__init__.py", line 2152, in declare_namespace
    _handle_ns(packageName, path_item)
  File "C:\Users\Yurak\AppData\Local\conda\conda\envs\env_python36_for_dl\lib\site-packages\pip\_vendor\pkg_resources\__init__.py", line 2092, in _handle_ns
    _rebuild_mod_path(path, packageName, module)
  File "C:\Users\Yurak\AppData\Local\conda\conda\envs\env_python36_for_dl\lib\site-packages\pip\_vendor\pkg_resources\__init__.py", line 2121, in _rebuild_mod_path
    orig_path.sort(key=position_in_sys_path)
AttributeError: '_NamespacePath' object has no attribute 'sort'
```
I had set up `pip` and `setuptools`  `tensorflow` with Anaconda3.

If i open Anaconda3 `root environment` in terminal , pip work properly.
