### ISSUE TITLE
Cannot open the navigator of python

### ISSUE THREAD

**Issue by willaccc** [ContinuumIO/anaconda-issues#1577]
I use OS X and recently I figured I cannot open navigator. I tried using the terminal to call but not work. 
`$ anaconda-navigator
Traceback (most recent call last):
  File "//anaconda/bin/anaconda-navigator", line 4, in <module>
    import anaconda_navigator.app.main
  File "//anaconda/lib/python3.5/site-packages/anaconda_navigator/app/main.py", line 21, in <module>
    from anaconda_navigator.widgets.dialogs.splash import SplashScreen
  File "//anaconda/lib/python3.5/site-packages/anaconda_navigator/widgets/__init__.py", line 18, in <module>
    from anaconda_navigator.utils.analytics import GATracker
  File "//anaconda/lib/python3.5/site-packages/anaconda_navigator/utils/analytics.py", line 33, in <module>
    from qtpy.QtCore import QT_VERSION_STR, QObject, QThread, QTimer, Signal
ImportError: cannot import name 'QT_VERSION_STR'`

**Comment by willaccc** [comment]
This is my conda info
`$ conda info
Current conda install:

               platform : osx-64
          conda version : 4.3.15
       conda is private : False
      conda-env version : 4.3.15
    conda-build version : 2.1.8
         python version : 3.5.3.final.0
       requests version : 2.13.0
       root environment : //anaconda  (writable)
    default environment : //anaconda
       envs directories : //anaconda/envs
                          /Users/willacheng/.conda/envs
          package cache : //anaconda/pkgs
                          /Users/willacheng/.conda/pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/osx-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/osx-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/osx-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : None
           offline mode : False
             user-agent : conda/4.3.15 requests/2.13.0 CPython/3.5.3 Darwin/15.6.0 OSX/10.11.6
                UID:GID : 501:20`

**Comment by willaccc** [comment]
#910

**Comment by willaccc** [comment]
Tried update the navigator to version 1.5 but seemed not working. 


$ conda install anaconda-navigator=1.5.1
Fetching package metadata .........
Solving package specifications: .


UnsatisfiableError: The following specifications were found to be in conflict:
 - anaconda-navigator 1.5.1*
 - spyder-app -> spyder 2.3.7 -> pyqt 4.* -> qt 4.8.6
 - spyder-app -> spyder 2.3.7 -> pyqt 4.* -> sip 4.16.5
Use "conda info <package>" to see the dependencies for each package.
