### ISSUE TITLE
Can't run anaconda-navigator on Linux

### ISSUE THREAD

**Issue by akontsevich** [ContinuumIO/anaconda-issues#1580]
Installed latest anacaonda 4.3.1 x64 on Linux Mint 18.1 (Ubuntu 16.04) and tried to launch anaconda-navigator - no luck: does not show any GUI. Also Anaconda programs was not added to operating system’s main menu as mentioned here: https://docs.continuum.io/anaconda/navigator

Spyder was not working also, however works now after anaconda reinstall.

Any solution to solve this? 

Console output attached: [anaconda-navigator.out.txt](https://github.com/ContinuumIO/anaconda-issues/files/894825/anaconda-navigator.out.txt)

**Comment by mingwandroid** [comment]
The page toy linked to says:

```
Different Linux distributions such as CentOS or Ubuntu have many different systems for adding shortcuts to menus and to the desktop, so Anaconda does not add these shortcuts automatically. Instead, you can use your operating system to create shortcuts that run the command anaconda-navigator on the desktop or on the operating system’s main menu or both.
```

So you should not expect to see any shortcuts. I'll look into your problem as soon as I have time.

**Comment by akontsevich** [comment]
PyCharm or NetBeans create menu shortcut without a problem on any Linux. There are common techniques for this, for example just create `~/.local/share/applications/anaconda-navigator.desktop` file like this: [netbeans-8.1.desktop.txt](https://github.com/ContinuumIO/anaconda-issues/files/894851/netbeans-8.1.desktop.txt)

**Comment by mingwandroid** [comment]
I am not trying to suggest that this is not possible, clearly it is. I was merely pointing out that the URL you linked to does not claim that Anaconda will create shortcuts on Linux.

This is something we are hoping to add though.

**Comment by akontsevich** [comment]
> I was merely pointing out that the URL you linked to does not claim that Anaconda will create shortcuts on Linux. This is something we are hoping to add though
Yeah, thanks, I missed this phrase under the link.

**Comment by ccordoba12** [comment]
Closing because this is a known problem but we don't have plans to solve it in the near future.

Thanks for reporting though.

**Comment by akontsevich** [comment]
What is the problem about? Any way to solve?

**Comment by ccordoba12** [comment]
There's no problem, we just don't have time for this right now, sorry.

**Comment by darlanpj** [comment]
source ~/anaconda3/bin/activate root
anaconda-navigator

**Comment by akontsevich** [comment]
> source ~/anaconda3/bin/activate root
>anaconda-navigator

Cool, was able to run it in this way! Thanks!

**Comment by ferti1969** [comment]
Thank you!

**Comment by danoff** [comment]
Thank you @darlanpj I was having the same issue and that worked for me too!!

**Comment by ChamanAgrawal** [comment]
@darlanpj I have to activate root every time I close the terminal, any help?

**Comment by JenimPatel** [comment]
Thanks @darlanpj, I too was facing same problem and that worked for me too!

**Comment by judiprodige** [comment]
Hi
Please, help me.
I open the jupyter notebook, kernel error appears.

Traceback (most recent call last):
File "C:\Users\ossej\Anaconda3\lib\site-packages\tornado\web.py", line 1699, in _execute
result = await result
File "C:\Users\ossej\Anaconda3\lib\site-packages\tornado\gen.py", line 742, in run
yielded = self.gen.throw(*exc_info) # type: ignore
File "C:\Users\ossej\AppData\Roaming\Python\Python37\site-packages\notebook\services\sessions\handlers.py", line 72, in post
type=mtype))
File "C:\Users\ossej\Anaconda3\lib\site-packages\tornado\gen.py", line 735, in run
value = future.result()
File "C:\Users\ossej\Anaconda3\lib\site-packages\tornado\gen.py", line 742, in run
yielded = self.gen.throw(*exc_info) # type: ignore
File "C:\Users\ossej\AppData\Roaming\Python\Python37\site-packages\notebook\services\sessions\sessionmanager.py", line 88, in create_session
kernel_id = yield self.start_kernel_for_session(session_id, path, name, type, kernel_name)
File "C:\Users\ossej\Anaconda3\lib\site-packages\tornado\gen.py", line 735, in run
value = future.result()
File "C:\Users\ossej\Anaconda3\lib\site-packages\tornado\gen.py", line 742, in run
yielded = self.gen.throw(*exc_info) # type: ignore
File "C:\Users\ossej\AppData\Roaming\Python\Python37\site-packages\notebook\services\sessions\sessionmanager.py", line 101, in start_kernel_for_session
self.kernel_manager.start_kernel(path=kernel_path, kernel_name=kernel_name)
File "C:\Users\ossej\Anaconda3\lib\site-packages\tornado\gen.py", line 735, in run
value = future.result()
File "C:\Users\ossej\Anaconda3\lib\site-packages\tornado\gen.py", line 209, in wrapper
yielded = next(result)
File "C:\Users\ossej\AppData\Roaming\Python\Python37\site-packages\notebook\services\kernels\kernelmanager.py", line 168, in start_kernel
super(MappingKernelManager, self).start_kernel(**kwargs)
File "C:\Users\ossej\AppData\Roaming\Python\Python37\site-packages\jupyter_client\multikernelmanager.py", line 110, in start_kernel
km.start_kernel(**kwargs)
File "C:\Users\ossej\AppData\Roaming\Python\Python37\site-packages\jupyter_client\manager.py", line 240, in start_kernel
self.write_connection_file()
File "C:\Users\ossej\AppData\Roaming\Python\Python37\site-packages\jupyter_client\connect.py", line 547, in write_connection_file
kernel_name=self.kernel_name
File "C:\Users\ossej\AppData\Roaming\Python\Python37\site-packages\jupyter_client\connect.py", line 212, in write_connection_file
with secure_write(fname) as f:
File "C:\Users\ossej\Anaconda3\lib\contextlib.py", line 112, in enter
return next(self.gen)
File "C:\Users\ossej\AppData\Roaming\Python\Python37\site-packages\jupyter_client\connect.py", line 100, in secure_write
win32_restrict_file_to_user(fname)
File "C:\Users\ossej\AppData\Roaming\Python\Python37\site-packages\jupyter_client\connect.py", line 53, in win32_restrict_file_to_user
import win32api
ImportError: DLL load failed: La procédure spécifiée est introuvable.

**Comment by gurv23** [comment]
> source ~/anaconda3/bin/activate root
> anaconda-navigator

everytime when we have to start conda run these command
