### ISSUE TITLE
No module named 'spyderlib' 

### ISSUE THREAD

**Issue by Rietaros** [ContinuumIO/anaconda-issues#1589]
I found this error : 

```
Traceback (most recent call last):
  File "spyder.py", line 2, in <module>
    from spyderlib import start_app
ImportError: No module named spyderlib
```

while running :+1: 
`python spyder.py`

In my Linux Anaconda virtual environment. Any idea how to fix this? 

*Before I found that error, I did some update using `conda update --all`

thank you in advance

**Comment by ccordoba12** [comment]
The `spyderlib` module was renamed to `spyder` when Spyder 3.0 was released. So you need to verify that you have the latest Spyder version installed.

**Comment by Rietaros** [comment]
I try to launch it from Anaconda

```
ubuntu@ubuntu:~/anaconda3/bin$ python spyder.py
Traceback (most recent call last):
  File "spyder.py", line 2, in <module>
    from spyder import start_app
  File "/home/ubuntu/anaconda3/bin/spyder.py", line 2, in <module>
    from spyder import start_app
ImportError: cannot import name 'start_app'
```

**Comment by Rietaros** [comment]
I found that if I use spyder2 for python2, there's no error.

And this is spyder related library for python2 in my PC:
- spyderlib
- spyderplugins

spyder related library for python2 im my PC:
- spyder
- spyder_breakpoints
- spyder_io_dcm
- spyder_io_hdf5
- spyder_profiler
- spyder_pylint

**Comment by ccordoba12** [comment]
Do you have two versions of Anaconda installed?

**Comment by Rietaros** [comment]
Nope, just Anaconda3 for my Python3 Virtual Environment. While Python2 is my default Python for Linux. I installed Spyder from Anaconda3.

But, the problem only appear when I launch Spyder from Anaconda launcher (which is called from spyder.py).
