### ISSUE TITLE
nb_conda 2.0.0 in Anaconda 4.3.1 is not working

### ISSUE THREAD

**Issue by sodre** [ContinuumIO/anaconda-issues#1590]
nb_conda is generating exceptions in Jupyter Notebook.
Steps to reproduce:
1) Create a conda environment with Anaconda 4.3.1 with either python 2.7 or 3.5.
2) Conda install nb_conda from /anaconda channel.
3) Launch jupyter notebook
4) Navigate to the "conda" tab in the notebook. 
5) You will get an "Internal Server Error" in the browser and the below exception from the terminal.
```
(anaconda2) sodre at envy in /opt/miniconda3/envs
$ jupyter-notebook
[I 01:03:29.471 NotebookApp] [nb_conda_kernels] enabled, 11 kernels found
[I 01:03:29.951 NotebookApp] [nb_anacondacloud] enabled
[I 01:03:29.957 NotebookApp] [nb_conda] enabled
[I 01:03:30.052 NotebookApp] ✓ nbpresent HTML export ENABLED
[W 01:03:30.052 NotebookApp] ✗ nbpresent PDF export DISABLED: No module named nbbrowserpdf.exporters.pdf
[I 01:03:30.059 NotebookApp] Serving notebooks from local directory: /opt/miniconda3/envs
[I 01:03:30.059 NotebookApp] 0 active kernels 
[I 01:03:30.059 NotebookApp] The Jupyter Notebook is running at: http://localhost:8888/?token=4bc080990e495ba9e45b7b027e078615aa3a0f244be59c9a
[I 01:03:30.059 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 01:03:30.060 NotebookApp] 
    
    Copy/paste this URL into your browser when you connect for the first time,
    to login with a token:
        http://localhost:8888/?token=XXX
[I 01:03:30.458 NotebookApp] Accepting one-time-token-authenticated connection from ::1
[E 01:03:33.846 NotebookApp] Unhandled error in API request
    Traceback (most recent call last):
      File "/opt/miniconda3/envs/anaconda2/lib/python2.7/site-packages/notebook/base/handlers.py", line 503, in wrapper
        result = yield gen.maybe_future(method(self, *args, **kwargs))
      File "/opt/miniconda3/envs/anaconda2/lib/python2.7/site-packages/nb_conda/handlers.py", line 62, in get
        self.finish(json.dumps(self.env_manager.env_packages(env)))
      File "/opt/miniconda3/envs/anaconda2/lib/python2.7/site-packages/nb_conda/envmanager.py", line 124, in env_packages
        "packages": [pkg_info(package) for package in data]
      File "/opt/miniconda3/envs/anaconda2/lib/python2.7/site-packages/nb_conda/envmanager.py", line 16, in pkg_info
        name, version, build = s.rsplit('-', 2)
    AttributeError: 'dict' object has no attribute 'rsplit'
[E 01:03:33.849 NotebookApp] {
      "Accept-Language": "en-us", 
      "Accept-Encoding": "gzip, deflate", 
      "Host": "localhost:8888", 
      "Accept": "application/json, text/javascript, */*; q=0.01", 
      "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_4) AppleWebKit/603.1.30 (KHTML, like Gecko) Version/10.1 Safari/603.1.30", 
      "Dnt": "1", 
      "Connection": "keep-alive", 
      "X-Requested-With": "XMLHttpRequest", 
      "Referer": "http://localhost:8888/tree?token=7534eb2eb6a14c9b0abc979e2c6ca947fa4284dc8f224aed", 
      "Cookie": "username-localhost-8888=\"2|1:0|10:1491541410|23:username-localhost-8888|44:XXX=|XXX\"; _xsrf=2|XXX|XXX|XXX; fldt=hide; splunkweb_csrf_token_8000=XXX; csrftoken=XXX"
    }
[E 01:03:33.849 NotebookApp] 500 GET /conda/environments/anaconda2?_=1491541410594 (::1) 934.80ms referer=http://localhost:8888/tree?token=XXX
```

Cursory debugging tells me that [env_packages](https://github.com/Anaconda-Platform/nb_conda/blob/master/nb_conda/envmanager.py#L125) `package` is a dict, but the [pkg_info](https://github.com/Anaconda-Platform/nb_conda/blob/master/nb_conda/envmanager.py#L15) code expects a string, e.g. when called from [check_update](https://github.com/Anaconda-Platform/nb_conda/blob/master/nb_conda/envmanager.py#L145).

**Comment by damianavila** [comment]
@sodre, this is solved in the latest release nb_conda 2.2.0 available at conda-forge. Closing here.

**Comment by sodre** [comment]
thanks @damianavila, any idea when it will hit the anaconda channel?

**Comment by damianavila** [comment]
Hopefully very soon! Need to sync with others :wink:
