### ISSUE TITLE
conda build r-gglasso - linux

### ISSUE THREAD

**Issue by diehl** [ContinuumIO/anaconda-issues#1592]
I've been trying to build the R package `gglasso` on a linux VM today and keep seeing the following.
Any thoughts on how to resolve the `make: not found` issue? 

```
root@b8fc8572ad49:/data# conda build -c r r-gglasso
BUILD START: r-gglasso-1.3-r3.3.2_0
    (actual version deferred until further download or env creation)
updating index in: /opt/conda/conda-bld/linux-64
updating index in: /opt/conda/conda-bld/noarch

The following NEW packages will be INSTALLED:

    bzip2:      1.0.6-3
    cairo:      1.14.8-0
    cloog:      0.18.0-0
    curl:       7.52.1-0
    fontconfig: 2.12.1-3
    freetype:   2.5.5-2
    gcc:        4.8.5-7
    glib:       2.50.2-1
    gmp:        6.1.0-0
    gsl:        2.2.1-0
    harfbuzz:   0.9.39-2
    icu:        54.1-0
    isl:        0.12.2-0
    jbig:       2.1-0
    jpeg:       9b-0
    libffi:     3.2.1-1
    libgcc:     5.2.0-0
    libiconv:   1.14-0
    libpng:     1.6.27-0
    libtiff:    4.0.6-3
    libxml2:    2.9.4-0
    mpc:        1.0.3-0
    mpfr:       3.1.5-0
    ncurses:    5.9-10
    openssl:    1.0.2k-1
    pango:      1.40.3-1
    pcre:       8.39-1
    pixman:     0.34.0-0
    r-base:     3.3.2-1  r
    readline:   6.2-2
    tk:         8.5.18-0
    xz:         5.2.2-1
    zlib:       1.2.8-3

Source cache directory is: /opt/conda/conda-bld/src_cache
Found source in cache: gglasso_1.3.tar.gz
Extracting download
BUILD START (revised): r-gglasso-1.3-r3.3.2_0
Package: r-gglasso-1.3-r3.3.2_0
source tree in: /opt/conda/conda-bld/r-gglasso_1491782548154/work/gglasso
+ source /opt/conda/bin/activate /opt/conda/conda-bld/r-gglasso_1491782548154/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla
+ mv DESCRIPTION DESCRIPTION.old
+ grep -v '^Priority: ' DESCRIPTION.old
+ /opt/conda/conda-bld/r-gglasso_1491782548154/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/bin/R CMD INSTALL --build .
* installing to library ‘/opt/conda/conda-bld/r-gglasso_1491782548154/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/lib/R/library’
* installing *source* package ‘gglasso’ ...
** package ‘gglasso’ successfully unpacked and MD5 sums checked
** libs
sh: 1: make: not found
ERROR: compilation failed for package ‘gglasso’
* removing ‘/opt/conda/conda-bld/r-gglasso_1491782548154/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/lib/R/library/gglasso’
Traceback (most recent call last):
  File "/opt/conda/bin/conda-build", line 6, in <module>
    sys.exit(conda_build.cli.main_build.main())
  File "/opt/conda/lib/python2.7/site-packages/conda_build/cli/main_build.py", line 334, in main
    execute(sys.argv[1:])
  File "/opt/conda/lib/python2.7/site-packages/conda_build/cli/main_build.py", line 325, in execute
    noverify=args.no_verify)
  File "/opt/conda/lib/python2.7/site-packages/conda_build/api.py", line 97, in build
    need_source_download=need_source_download, config=config)
  File "/opt/conda/lib/python2.7/site-packages/conda_build/build.py", line 1503, in build_tree
    config=config)
  File "/opt/conda/lib/python2.7/site-packages/conda_build/build.py", line 1135, in build
    utils.check_call_env(cmd, env=env, cwd=src_dir)
  File "/opt/conda/lib/python2.7/site-packages/conda_build/utils.py", line 620, in check_call_env
    return _func_defaulting_env_to_os_environ(subprocess.check_call, *popenargs, **kwargs)
  File "/opt/conda/lib/python2.7/site-packages/conda_build/utils.py", line 616, in _func_defaulting_env_to_os_environ
    return func(_args, **kwargs)
  File "/opt/conda/lib/python2.7/subprocess.py", line 186, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/bin/bash', '-x', '-e', '/opt/conda/conda-bld/r-gglasso_1491782548154/work/gglasso/conda_build.sh']' returned non-zero exit status 1
```

**Comment by diehl** [comment]
Realizing the issue. Had to install `make` on this VM. Who knew. ;-)
