### ISSUE TITLE
Conda Commands and Navigator not working

### ISSUE THREAD

**Issue by Sayan97** [ContinuumIO/anaconda-issues#1595]
### On opening anaconda prompt:-
**Anaconda Prompt Error: -**
```
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\Scripts\conda-script.py", line 5, in <module>
    sys.exit(conda.cli.main())
  File "C:\ProgramData\Anaconda3\lib\site-packages\conda\cli\main.py", line 151, in main
    activate.main()
  File "C:\ProgramData\Anaconda3\lib\site-packages\conda\cli\activate.py", line 118, in main
    from conda.utils import shells
  File "C:\ProgramData\Anaconda3\lib\site-packages\conda\utils.py", line 13, in <module>
    from .gateways.disk.read import compute_md5sum
  File "C:\ProgramData\Anaconda3\lib\site-packages\conda\gateways\disk\read.py", line 22, in <module>
    from ...models.channel import Channel
  File "C:\ProgramData\Anaconda3\lib\site-packages\conda\models\channel.py", line 9, in <module>
    from ..base.context import context
  File "C:\ProgramData\Anaconda3\lib\site-packages\conda\base\context.py", line 584, in <module>
    context = Context(SEARCH_PATH, APP_NAME, None)
  File "C:\ProgramData\Anaconda3\lib\site-packages\conda\common\configuration.py", line 715, in __init__
    self._set_search_path(search_path)
  File "C:\ProgramData\Anaconda3\lib\site-packages\conda\common\configuration.py", line 733, in _set_search_path
    self._set_raw_data(load_file_configs(search_path))
  File "C:\ProgramData\Anaconda3\lib\site-packages\conda\common\configuration.py", line 368, in load_file_configs
    raw_data = odict(kv for kv in chain.from_iterable(load_paths))
  File "C:\ProgramData\Anaconda3\lib\site-packages\conda\common\configuration.py", line 368, in <genexpr>
    raw_data = odict(kv for kv in chain.from_iterable(load_paths))
  File "C:\ProgramData\Anaconda3\lib\site-packages\conda\common\configuration.py", line 343, in _file_yaml_loader
    yield fullpath, YamlRawParameter.make_raw_parameters_from_file(fullpath)
  File "C:\ProgramData\Anaconda3\lib\site-packages\conda\common\configuration.py", line 331, in make_raw_parameters_from_file
    ruamel_yaml = yaml_load(fh)
  File "C:\ProgramData\Anaconda3\lib\site-packages\conda\common\yaml.py", line 26, in yaml_load
    return yaml.load(string, Loader=yaml.RoundTripLoader, version="1.2")
  File "C:\ProgramData\Anaconda3\lib\site-packages\ruamel_yaml\main.py", line 73, in load
    loader = Loader(stream, version, preserve_quotes=preserve_quotes)
  File "C:\ProgramData\Anaconda3\lib\site-packages\ruamel_yaml\loader.py", line 56, in __init__
    Reader.__init__(self, stream)
  File "C:\ProgramData\Anaconda3\lib\site-packages\ruamel_yaml\reader.py", line 98, in __init__
    self.determine_encoding()
  File "C:\ProgramData\Anaconda3\lib\site-packages\ruamel_yaml\reader.py", line 149, in determine_encoding
    self.update(1)
  File "C:\ProgramData\Anaconda3\lib\site-packages\ruamel_yaml\reader.py", line 189, in update
    self.check_printable(data)
  File "C:\ProgramData\Anaconda3\lib\site-packages\ruamel_yaml\reader.py", line 160, in check_printable
    'unicode', "special characters are not allowed")
ruamel_yaml.reader.ReaderError: unacceptable character #x0000: special characters are not allowed
  in "C:\Users\Sayan\.condarc", position 0
```

### Steps to produce: -
```
Microsoft Windows [Version 10.0.14393]
(c) 2016 Microsoft Corporation. All rights reserved.

C:\WINDOWS\system32>conda list
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\conda\exceptions.py", line 573, in conda_exception_handler
    return_value = func(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\conda\cli\main.py", line 85, in _main
    from ..base.context import context
  File "C:\ProgramData\Anaconda3\lib\site-packages\conda\base\context.py", line 584, in <module>
    context = Context(SEARCH_PATH, APP_NAME, None)
  File "C:\ProgramData\Anaconda3\lib\site-packages\conda\common\configuration.py", line 715, in __init__
    self._set_search_path(search_path)
  File "C:\ProgramData\Anaconda3\lib\site-packages\conda\common\configuration.py", line 733, in _set_search_path
    self._set_raw_data(load_file_configs(search_path))
  File "C:\ProgramData\Anaconda3\lib\site-packages\conda\common\configuration.py", line 368, in load_file_configs
    raw_data = odict(kv for kv in chain.from_iterable(load_paths))
  File "C:\ProgramData\Anaconda3\lib\site-packages\conda\common\configuration.py", line 368, in <genexpr>
    raw_data = odict(kv for kv in chain.from_iterable(load_paths))
  File "C:\ProgramData\Anaconda3\lib\site-packages\conda\common\configuration.py", line 343, in _file_yaml_loader
    yield fullpath, YamlRawParameter.make_raw_parameters_from_file(fullpath)
  File "C:\ProgramData\Anaconda3\lib\site-packages\conda\common\configuration.py", line 331, in make_raw_parameters_from_file
    ruamel_yaml = yaml_load(fh)
  File "C:\ProgramData\Anaconda3\lib\site-packages\conda\common\yaml.py", line 26, in yaml_load
    return yaml.load(string, Loader=yaml.RoundTripLoader, version="1.2")
  File "C:\ProgramData\Anaconda3\lib\site-packages\ruamel_yaml\main.py", line 73, in load
    loader = Loader(stream, version, preserve_quotes=preserve_quotes)
  File "C:\ProgramData\Anaconda3\lib\site-packages\ruamel_yaml\loader.py", line 56, in __init__
    Reader.__init__(self, stream)
  File "C:\ProgramData\Anaconda3\lib\site-packages\ruamel_yaml\reader.py", line 98, in __init__
    self.determine_encoding()
  File "C:\ProgramData\Anaconda3\lib\site-packages\ruamel_yaml\reader.py", line 149, in determine_encoding
    self.update(1)
  File "C:\ProgramData\Anaconda3\lib\site-packages\ruamel_yaml\reader.py", line 189, in update
    self.check_printable(data)
  File "C:\ProgramData\Anaconda3\lib\site-packages\ruamel_yaml\reader.py", line 160, in check_printable
    'unicode', "special characters are not allowed")
ruamel_yaml.reader.ReaderError: unacceptable character #x0000: special characters are not allowed
  in "C:\Users\Sayan\.condarc", position 0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\Scripts\conda-script.py", line 5, in <module>
    sys.exit(conda.cli.main())
  File "C:\ProgramData\Anaconda3\lib\site-packages\conda\cli\main.py", line 164, in main
    return conda_exception_handler(_main, *args)
  File "C:\ProgramData\Anaconda3\lib\site-packages\conda\exceptions.py", line 589, in conda_exception_handler
    print_unexpected_error_message(e)
  File "C:\ProgramData\Anaconda3\lib\site-packages\conda\exceptions.py", line 526, in print_unexpected_error_message
    from conda.base.context import context
  File "C:\ProgramData\Anaconda3\lib\site-packages\conda\base\context.py", line 584, in <module>
    context = Context(SEARCH_PATH, APP_NAME, None)
  File "C:\ProgramData\Anaconda3\lib\site-packages\conda\common\configuration.py", line 715, in __init__
    self._set_search_path(search_path)
  File "C:\ProgramData\Anaconda3\lib\site-packages\conda\common\configuration.py", line 733, in _set_search_path
    self._set_raw_data(load_file_configs(search_path))
  File "C:\ProgramData\Anaconda3\lib\site-packages\conda\common\configuration.py", line 368, in load_file_configs
    raw_data = odict(kv for kv in chain.from_iterable(load_paths))
  File "C:\ProgramData\Anaconda3\lib\site-packages\conda\common\configuration.py", line 368, in <genexpr>
    raw_data = odict(kv for kv in chain.from_iterable(load_paths))
  File "C:\ProgramData\Anaconda3\lib\site-packages\conda\common\configuration.py", line 343, in _file_yaml_loader
    yield fullpath, YamlRawParameter.make_raw_parameters_from_file(fullpath)
  File "C:\ProgramData\Anaconda3\lib\site-packages\conda\common\configuration.py", line 331, in make_raw_parameters_from_file
    ruamel_yaml = yaml_load(fh)
  File "C:\ProgramData\Anaconda3\lib\site-packages\conda\common\yaml.py", line 26, in yaml_load
    return yaml.load(string, Loader=yaml.RoundTripLoader, version="1.2")
  File "C:\ProgramData\Anaconda3\lib\site-packages\ruamel_yaml\main.py", line 73, in load
    loader = Loader(stream, version, preserve_quotes=preserve_quotes)
  File "C:\ProgramData\Anaconda3\lib\site-packages\ruamel_yaml\loader.py", line 56, in __init__
    Reader.__init__(self, stream)
  File "C:\ProgramData\Anaconda3\lib\site-packages\ruamel_yaml\reader.py", line 98, in __init__
    self.determine_encoding()
  File "C:\ProgramData\Anaconda3\lib\site-packages\ruamel_yaml\reader.py", line 149, in determine_encoding
    self.update(1)
  File "C:\ProgramData\Anaconda3\lib\site-packages\ruamel_yaml\reader.py", line 189, in update
    self.check_printable(data)
  File "C:\ProgramData\Anaconda3\lib\site-packages\ruamel_yaml\reader.py", line 160, in check_printable
    'unicode', "special characters are not allowed")
ruamel_yaml.reader.ReaderError: unacceptable character #x0000: special characters are not allowed
  in "C:\Users\Sayan\.condarc", position 0
```

**Comment by mingwandroid** [comment]
Please show the contents of `C:\Users\Sayan\.condarc`

**Comment by Sayan97** [comment]
![capture](https://cloud.githubusercontent.com/assets/26685910/24928258/7402515c-1f1f-11e7-904e-f6eb02f6e260.JPG)
![capture](https://cloud.githubusercontent.com/assets/26685910/24928357/cd863982-1f1f-11e7-9813-b3c1b09d2b38.JPG)
![capture](https://cloud.githubusercontent.com/assets/26685910/24928402/f4d76952-1f1f-11e7-9644-100665116310.JPG)
![capture](https://cloud.githubusercontent.com/assets/26685910/24928440/10bd931c-1f20-11e7-9733-dcbd368f8446.JPG)

**Comment by mingwandroid** [comment]
`C:\Users\Sayan\.condarc` should be a file, it may be hidden (you may need to enable 'Show Hidden Files' in `Windows Explorer`). This may help: http://www.laptopmag.com/articles/show-hidden-files-windows

Otherwise, it may be easier to launch `cmd.exe` and type `more C:\Users\Sayan\.condarc`

**Comment by Sayan97** [comment]
I see the file, which application do I open it with?

**Comment by mingwandroid** [comment]
`notepad.exe` is a reasonable choice.

**Comment by Sayan97** [comment]
![capture](https://cloud.githubusercontent.com/assets/26685910/24929515/d881c988-1f23-11e7-8c99-ae84419b2130.JPG)

**Comment by mingwandroid** [comment]
Hmm, ok, please delete this file and try again. `Conda` should re-create it, though I am not sure what's wrong with it from your screen-grab.

**Comment by Sayan97** [comment]
### IT WORKED!!! THANK YOU!!! Now the Anaconda Navigator as well as the Conda commands are working. Deleting the file worked wonders. Until next time (hopefully not). Thank you for your time.

**Comment by mingwandroid** [comment]
Glad to get you going again.

**Comment by dmittal7** [comment]
great it worked for me also .thank you.

**Comment by Zaiku1972** [comment]
worked like a charm.. thank you

**Comment by tiagosgc** [comment]
I had the same problem with a previous bad installation. Your fix worked for me also.

**Comment by MagicalBomb** [comment]
Thanks for your help!!

**Comment by nikitaluthra** [comment]
It worked. Thank you so much !

**Comment by nathhje** [comment]
Yes! It worked, finally figured it out.
