### ISSUE TITLE
Python 2 import ssl

### ISSUE THREAD

**Issue by willpearse** [ContinuumIO/anaconda-issues#1601]
On a fresh 64-bit install of Anconda2 (4.3.1) with Python 2 (2.7.13) on Windows 10, I get the following error:

```
>>> import ssl
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "C:\Users\username_redacted\Anaconda2\lib\ssl.py", line 133, in <module>
  PROTOCOL_SSLv23 = PROTOCOL_TLS
NameError: name 'PROTOCOL_TLS' is not defined
```

I realise there are a few postings about SSL problems with Python in Anaconda that could be related: I've already tried running things like `conda update openssl`, I don't have certifi installed, and `pip install ssl` doesn't work (since ssl is bundled with python now, I guess).

Does anyone have any ideas? I'd be very grateful for some advice, and I'm sorry if I've missed something obvious. I may be a little slow to reply as I'm about to go travelling for a while.

Thank you!!!

**Comment by mingwandroid** [comment]
I just tried this (with Miniconda though) and had no issues. Can you show the output from:

```
import sys
print '\n'.join(sys.path)
```

Thanks.

**Comment by nehaljwani** [comment]
I am not able to reproduce this either. Could you please share output for:
```
python -c "import _ssl; print _ssl.__file__ , 'PROTOCOL_TLS' in dir(_ssl)"
```

**Comment by nehaljwani** [comment]
Closing due to inactivity.
