### ISSUE TITLE
The application “Navigator” can't be opened

### ISSUE THREAD

**Issue by jamka1902** [ContinuumIO/anaconda-issues#1606]
When I click on the navigator it says, The application "Navigator" can't be opened How can I fix this? It was completely fine few days ago and now I am trying to open it again and it says this suddenly. I tried updating it but still no result.
I am using Mac book OS Sierra version 10.12.3.

I tried updating the anaconda and navigator still not working

`conda update anaconda`
`conda update anaconda-navigator`

`conda info`  
output -> 
```
Current conda install:

               platform : osx-64
          conda version : 4.3.16
       conda is private : False
      conda-env version : 4.3.16
    conda-build version : 1.14.1
         python version : 2.7.11.final.0
       requests version : 2.13.0
       root environment : //anaconda  (writable)
    default environment : //anaconda
       envs directories : //anaconda/envs
                          /Users/username/.conda/envs
          package cache : //anaconda/pkgs
                          /Users/username/.conda/pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/osx-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/osx-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/osx-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : None
           offline mode : False
             user-agent : conda/4.3.16 requests/2.13.0 CPython/2.7.11 Darwin/16.4.0 OSX/10.12.3
                UID:GID : 501:20
```  

`conda list`  
output -> 
```
# packages in environment at //anaconda:
#
_license                  1.1                      py27_0    <unknown>
abstract-rendering        0.5.1               np111py27_0    anaconda
alabaster                 0.7.7                    py27_0  
anaconda                  custom                   py27_0  
anaconda-client           1.4.0                    py27_0  
anaconda-navigator        1.2.3                    py27_0  
appnope                   0.1.0                    py27_0  
appscript                 1.0.1                    py27_0    <unknown>
apptools                  4.3.0                     <pip>
argcomplete               1.0.0                    py27_1  
astropy                   1.3                 np111py27_0    anaconda
babel                     2.2.0                    py27_0  
backports_abc             0.4                      py27_0  
bcolz                     1.0.0                    py27_0  
beautiful-soup            4.3.2                    py27_0    <unknown>
beautifulsoup4            4.4.1                    py27_0  
binstar                   0.11.0                   py27_0    <unknown>
bitarray                  0.8.1                    py27_0    <unknown>
blaze                     0.9.1                    py27_0  
blaze-core                0.9.0                    py27_0  
blz                       removed                       0  
bokeh                     0.11.1                   py27_0  
boto                      2.39.0                   py27_0  
bottleneck                1.2.0               np111py27_0    anaconda
cdecimal                  2.3                      py27_0    <unknown>
certifi                   2015.9.6.2               py27_0  
cffi                      1.5.2                    py27_0  
chest                     0.2.3                    py27_0  
cloudpickle               0.1.1                    py27_0  
clyent                    1.2.1                    py27_0  
colorama                  0.3.7                    py27_0  
conda                     4.3.16                   py27_0  
conda-build               1.14.1                   py27_0    <unknown>
conda-env                 2.6.0                         0  
conda-manager             0.3.1                    py27_0  
configobj                 5.0.6                    py27_0    <unknown>
configparser              3.5.0b2                  py27_0  
cryptography              1.7.1                    py27_0    anaconda
curl                      7.45.0                        0  
cycler                    0.10.0                   py27_0  
cython                    0.23.4                   py27_1  
cytoolz                   0.7.5                    py27_0  
dask                      0.8.1                    py27_0  
datashape                 0.5.1                    py27_0  
decorator                 4.0.9                    py27_0  
dill                      0.2.4                    py27_0  
docutils                  0.12                     py27_0    <unknown>
dynd-python               0.7.2                    py27_0  
entrypoints               0.2                      py27_0  
enum34                    1.1.2                    py27_0  
et_xmlfile                1.0.1                    py27_0  
fastcache                 1.0.2                    py27_0    <unknown>
flask                     0.10.1                   py27_1    <unknown>
flask-cors                2.1.2                    py27_0  
freetype                  2.5.5                         0  
funcsigs                  0.4                      py27_0    <unknown>
futures                   3.0.3                    py27_0  
gevent                    1.1.0                    py27_0  
gevent-websocket          0.9.5                    py27_1  
greenlet                  0.4.9                    py27_0  
grin                      1.2.1                    py27_1    <unknown>
h5py                      2.6.0               np111py27_2    anaconda
hdf5                      1.8.17                        1    anaconda
heapdict                  1.0.0                    py27_0  
idna                      2.0                      py27_0    <unknown>
imageio                   2.0.1                     <pip>
ipaddress                 1.0.14                   py27_0  
ipykernel                 4.3.1                    py27_0  
ipython                   4.1.2                    py27_1  
ipython-notebook          4.0.4                    py27_0  
ipython-qtconsole         4.0.1                    py27_0  
ipython_genutils          0.1.0                    py27_0  
ipywidgets                4.1.1                    py27_0  
itsdangerous              0.24                     py27_0    <unknown>
jbig                      2.1                           0  
jdcal                     1.2                      py27_0  
jedi                      0.9.0                    py27_0  
jinja2                    2.8                      py27_0  
jpeg                      8d                            1    <unknown>
jsonschema                2.4.0                    py27_0    <unknown>
jupyter                   1.0.0                    py27_2  
jupyter_client            4.2.2                    py27_0  
jupyter_console           4.1.1                    py27_0  
jupyter_core              4.1.0                    py27_0  
launcher                  1.0.0                         3  
libdynd                   0.7.2                         0  
libpng                    1.6.17                        0    <unknown>
libsodium                 0.4.5                         0    <unknown>
libtiff                   4.0.6                         1  
libxml2                   2.9.2                         0    <unknown>
libxslt                   1.1.28                        2  
llvmlite                  0.16.0                   py27_0    anaconda
locket                    0.2.0                    py27_0  
lxml                      3.6.0                    py27_0  
markupsafe                0.23                     py27_0    <unknown>
matplotlib                1.5.1               np111py27_0    anaconda
mistune                   0.7.2                    py27_1  
mkl                       2017.0.1                      0    anaconda
mkl-service               1.1.2                    py27_3    anaconda
mock                      1.0.1                    py27_0    <unknown>
mpld3                     0.2                       <pip>
mpmath                    0.19                     py27_0  
multipledispatch          0.4.8                    py27_0  
nbconvert                 4.1.0                    py27_0  
nbformat                  4.0.1                    py27_0  
networkx                  1.11                     py27_0  
nltk                      3.2                      py27_0  
node-webkit               0.10.1                        0  
nose                      1.3.7                    py27_0    <unknown>
notebook                  4.1.0                    py27_2  
numba                     0.31.0              np111py27_0    anaconda
numexpr                   2.6.2               np111py27_0    anaconda
numpy                     1.11.3                   py27_0    anaconda
odo                       0.4.2                    py27_0  
openpyxl                  2.3.2                    py27_0  
openssl                   1.0.2g                        0  
orange                    2.7.8                    py27_3  
orange-app                1.0                      py27_0  
pandas                    0.19.2              np111py27_1    anaconda
partd                     0.3.2                    py27_1  
path.py                   8.1.2                    py27_1  
patsy                     0.4.1                    py27_0    anaconda
pep8                      1.7.0                    py27_0  
pexpect                   4.0.1                    py27_0  
pickleshare               0.5                      py27_0  
pillow                    3.1.1                    py27_0  
pip                       8.1.1                    py27_1  
pip                       8.1.2                     <pip>
ply                       3.8                      py27_0  
psutil                    4.1.0                    py27_1  
ptyprocess                0.5                      py27_0  
py                        1.4.31                   py27_0  
pyasn1                    0.1.9                    py27_0  
pyaudio                   0.2.7                    py27_0    <unknown>
pycosat                   0.6.1                    py27_0    <unknown>
pycparser                 2.14                     py27_0    <unknown>
pycrypto                  2.6.1                    py27_0    <unknown>
pycurl                    7.19.5.3                 py27_0  
pyface                    5.0.0                     <pip>
pyflakes                  1.1.0                    py27_0  
pygments                  2.1.1                    py27_0  
pyopenssl                 16.2.0                   py27_0    anaconda
pyparsing                 2.0.3                    py27_0    <unknown>
pyqt                      4.11.4                   py27_1  
pytables                  3.3.0               np111py27_0    anaconda
pytest                    2.8.5                    py27_0  
python                    2.7.11                        0  
python-dateutil           2.5.1                    py27_0  
python-igraph             0.7.1.post6               <pip>
python.app                1.2                      py27_4    <unknown>
pytz                      2016.2                   py27_0  
pyyaml                    3.11                     py27_1    <unknown>
pyzmq                     15.2.0                   py27_0  
qt                        4.8.7                         1  
qtawesome                 0.3.2                    py27_0  
qtconsole                 4.2.0                    py27_0  
qtpy                      1.0                      py27_0  
readline                  6.2                           2  
redis                     2.6.9                         0    <unknown>
redis-py                  2.10.3                   py27_0    <unknown>
requests                  2.13.0                   py27_0    anaconda
rope                      0.9.4                    py27_1    <unknown>
ruamel_yaml               0.11.14                  py27_1    anaconda
runipy                    0.1.3                    py27_0    <unknown>
scikit-image              0.12.3              np111py27_1    anaconda
scikit-learn              0.18.1              np111py27_1    anaconda
scipy                     0.18.1              np111py27_1    anaconda
setuptools                20.3                     py27_0  
simplegeneric             0.8.1                    py27_0  
singledispatch            3.4.0.3                  py27_0  
sip                       4.16.9                   py27_0  
six                       1.10.0                   py27_0  
snowballstemmer           1.2.1                    py27_0  
sockjs-tornado            1.0.1                    py27_0  
sphinx                    1.3.5                    py27_0  
sphinx_rtd_theme          0.1.9                    py27_0  
spyder                    2.3.8                    py27_1  
spyder-app                2.3.8                    py27_0  
sqlalchemy                1.0.12                   py27_0  
sqlite                    3.9.2                         0  
ssl_match_hostname        3.4.0.2                  py27_0    <unknown>
statsmodels               0.8.0               np111py27_0    anaconda
sympy                     1.0                      py27_0  
terminado                 0.5                      py27_1  
texttable                 0.8.4                     <pip>
tk                        8.5.18                        0  
toolz                     0.7.4                    py27_0  
tornado                   4.3                      py27_0  
traitlets                 4.2.1                    py27_0  
traits                    4.5.0                     <pip>
traitsui                  5.0.0                     <pip>
ujson                     1.33                     py27_0    <unknown>
unicodecsv                0.14.1                   py27_0  
werkzeug                  0.11.4                   py27_0  
wheel                     0.29.0                   py27_0  
xlrd                      0.9.4                    py27_0  
xlsxwriter                0.8.4                    py27_0  
xlwings                   0.7.0                    py27_0  
xlwt                      1.0.0                    py27_0    <unknown>
xz                        5.0.5                         1  
yaml                      0.1.6                         0    <unknown>
zeromq                    4.1.3                         0  
zlib                      1.2.8                         0  

```

command line : `anaconda-navigator` gives 

    Traceback (most recent call last):
      File "//anaconda/bin/anaconda-navigator", line 4, in <module>
        import anaconda_navigator.app.main
      File "//anaconda/lib/python2.7/site-packages/anaconda_navigator/app/main.py", line 16, in <module>
        from qtpy.QtCore import QCoreApplication, QEvent, QObject, Qt
      File "//anaconda/lib/python2.7/site-packages/qtpy/__init__.py", line 129, in <module>
        raise PythonQtError('No Qt bindings could be found')
    qtpy.PythonQtError: No Qt bindings could be found

**Comment by goanpeca** [comment]
Please update to the latest Qt and latest navigator on the terminal type:

```
$ conda remove qt=4 pyqt=4
$ conda install qt=5 pyqt=5
$ conda install anaconda-navigator
```

However I do see that you have double slashes everywhere

`//anaconda/` that is certainly causing problems!
