### ISSUE TITLE
Windows 10: Anaconda Navigator won't open

### ISSUE THREAD

**Issue by kawazima8869** [ContinuumIO/anaconda-issues#1632]
When I click on the Anaconda Navigator, it won't open, and there's no other infomation showing up.
Then, I reinstall Anaconda 4.3.1 (64-bit),and  Anaconda Navigator still won't open.

I tried updating the anaconda and navigator using command, and found out that it seems conda commands are not working as well.

`conda info`
output ->
```
C:\Users\Office>conda update anaconda
Traceback (most recent call last):
  File "C:\Users\Office\Anaconda3\lib\site-packages\conda\exceptions.py", line 573, in conda_exception_handler
    return_value = func(*args, **kwargs)
  File "C:\Users\Office\Anaconda3\lib\site-packages\conda\cli\main.py", line 85, in _main
    from ..base.context import context
  File "C:\Users\Office\Anaconda3\lib\site-packages\conda\base\context.py", line 584, in <module>
    context = Context(SEARCH_PATH, APP_NAME, None)
  File "C:\Users\Office\Anaconda3\lib\site-packages\conda\common\configuration.py", line 715, in __init__
    self._set_search_path(search_path)
  File "C:\Users\Office\Anaconda3\lib\site-packages\conda\common\configuration.py", line 733, in _set_search_path
    self._set_raw_data(load_file_configs(search_path))
  File "C:\Users\Office\Anaconda3\lib\site-packages\conda\common\configuration.py", line 368, in load_file_configs
    raw_data = odict(kv for kv in chain.from_iterable(load_paths))
  File "C:\Users\Office\Anaconda3\lib\site-packages\conda\common\configuration.py", line 368, in <genexpr>
    raw_data = odict(kv for kv in chain.from_iterable(load_paths))
  File "C:\Users\Office\Anaconda3\lib\site-packages\conda\common\configuration.py", line 343, in _file_yaml_loader
    yield fullpath, YamlRawParameter.make_raw_parameters_from_file(fullpath)
  File "C:\Users\Office\Anaconda3\lib\site-packages\conda\common\configuration.py", line 331, in make_raw_parameters_from_file
    ruamel_yaml = yaml_load(fh)
  File "C:\Users\Office\Anaconda3\lib\site-packages\conda\common\yaml.py", line 26, in yaml_load
    return yaml.load(string, Loader=yaml.RoundTripLoader, version="1.2")
  File "C:\Users\Office\Anaconda3\lib\site-packages\ruamel_yaml\main.py", line 73, in load
    loader = Loader(stream, version, preserve_quotes=preserve_quotes)
  File "C:\Users\Office\Anaconda3\lib\site-packages\ruamel_yaml\loader.py", line 56, in __init__
    Reader.__init__(self, stream)
  File "C:\Users\Office\Anaconda3\lib\site-packages\ruamel_yaml\reader.py", line 98, in __init__
    self.determine_encoding()
  File "C:\Users\Office\Anaconda3\lib\site-packages\ruamel_yaml\reader.py", line 149, in determine_encoding
    self.update(1)
  File "C:\Users\Office\Anaconda3\lib\site-packages\ruamel_yaml\reader.py", line 189, in update
    self.check_printable(data)
  File "C:\Users\Office\Anaconda3\lib\site-packages\ruamel_yaml\reader.py", line 160, in check_printable
    'unicode', "special characters are not allowed")
ruamel_yaml.reader.ReaderError: unacceptable character #x0000: special characters are not allowed
  in "C:\Users\Office\.condarc", position 0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Office\Anaconda3\Scripts\conda-script.py", line 5, in <module>
    sys.exit(conda.cli.main())
  File "C:\Users\Office\Anaconda3\lib\site-packages\conda\cli\main.py", line 164, in main
    return conda_exception_handler(_main, *args)
  File "C:\Users\Office\Anaconda3\lib\site-packages\conda\exceptions.py", line 589, in conda_exception_handler
    print_unexpected_error_message(e)
  File "C:\Users\Office\Anaconda3\lib\site-packages\conda\exceptions.py", line 526, in print_unexpected_error_message
    from conda.base.context import context
  File "C:\Users\Office\Anaconda3\lib\site-packages\conda\base\context.py", line 584, in <module>
    context = Context(SEARCH_PATH, APP_NAME, None)
  File "C:\Users\Office\Anaconda3\lib\site-packages\conda\common\configuration.py", line 715, in __init__
    self._set_search_path(search_path)
  File "C:\Users\Office\Anaconda3\lib\site-packages\conda\common\configuration.py", line 733, in _set_search_path
    self._set_raw_data(load_file_configs(search_path))
  File "C:\Users\Office\Anaconda3\lib\site-packages\conda\common\configuration.py", line 368, in load_file_configs
    raw_data = odict(kv for kv in chain.from_iterable(load_paths))
  File "C:\Users\Office\Anaconda3\lib\site-packages\conda\common\configuration.py", line 368, in <genexpr>
    raw_data = odict(kv for kv in chain.from_iterable(load_paths))
  File "C:\Users\Office\Anaconda3\lib\site-packages\conda\common\configuration.py", line 343, in _file_yaml_loader
    yield fullpath, YamlRawParameter.make_raw_parameters_from_file(fullpath)
  File "C:\Users\Office\Anaconda3\lib\site-packages\conda\common\configuration.py", line 331, in make_raw_parameters_from_file
    ruamel_yaml = yaml_load(fh)
  File "C:\Users\Office\Anaconda3\lib\site-packages\conda\common\yaml.py", line 26, in yaml_load
    return yaml.load(string, Loader=yaml.RoundTripLoader, version="1.2")
  File "C:\Users\Office\Anaconda3\lib\site-packages\ruamel_yaml\main.py", line 73, in load
    loader = Loader(stream, version, preserve_quotes=preserve_quotes)
  File "C:\Users\Office\Anaconda3\lib\site-packages\ruamel_yaml\loader.py", line 56, in __init__
    Reader.__init__(self, stream)
  File "C:\Users\Office\Anaconda3\lib\site-packages\ruamel_yaml\reader.py", line 98, in __init__
    self.determine_encoding()
  File "C:\Users\Office\Anaconda3\lib\site-packages\ruamel_yaml\reader.py", line 149, in determine_encoding
    self.update(1)
  File "C:\Users\Office\Anaconda3\lib\site-packages\ruamel_yaml\reader.py", line 189, in update
    self.check_printable(data)
  File "C:\Users\Office\Anaconda3\lib\site-packages\ruamel_yaml\reader.py", line 160, in check_printable
    'unicode', "special characters are not allowed")
ruamel_yaml.reader.ReaderError: unacceptable character #x0000: special characters are not allowed
  in "C:\Users\Office\.condarc", position 0

C:\Users\Office>conda update anaconda-navigator
Traceback (most recent call last):
  File "C:\Users\Office\Anaconda3\lib\site-packages\conda\exceptions.py", line 573, in conda_exception_handler
    return_value = func(*args, **kwargs)
  File "C:\Users\Office\Anaconda3\lib\site-packages\conda\cli\main.py", line 85, in _main
    from ..base.context import context
  File "C:\Users\Office\Anaconda3\lib\site-packages\conda\base\context.py", line 584, in <module>
    context = Context(SEARCH_PATH, APP_NAME, None)
  File "C:\Users\Office\Anaconda3\lib\site-packages\conda\common\configuration.py", line 715, in __init__
    self._set_search_path(search_path)
  File "C:\Users\Office\Anaconda3\lib\site-packages\conda\common\configuration.py", line 733, in _set_search_path
    self._set_raw_data(load_file_configs(search_path))
  File "C:\Users\Office\Anaconda3\lib\site-packages\conda\common\configuration.py", line 368, in load_file_configs
    raw_data = odict(kv for kv in chain.from_iterable(load_paths))
  File "C:\Users\Office\Anaconda3\lib\site-packages\conda\common\configuration.py", line 368, in <genexpr>
    raw_data = odict(kv for kv in chain.from_iterable(load_paths))
  File "C:\Users\Office\Anaconda3\lib\site-packages\conda\common\configuration.py", line 343, in _file_yaml_loader
    yield fullpath, YamlRawParameter.make_raw_parameters_from_file(fullpath)
  File "C:\Users\Office\Anaconda3\lib\site-packages\conda\common\configuration.py", line 331, in make_raw_parameters_from_file
    ruamel_yaml = yaml_load(fh)
  File "C:\Users\Office\Anaconda3\lib\site-packages\conda\common\yaml.py", line 26, in yaml_load
    return yaml.load(string, Loader=yaml.RoundTripLoader, version="1.2")
  File "C:\Users\Office\Anaconda3\lib\site-packages\ruamel_yaml\main.py", line 73, in load
    loader = Loader(stream, version, preserve_quotes=preserve_quotes)
  File "C:\Users\Office\Anaconda3\lib\site-packages\ruamel_yaml\loader.py", line 56, in __init__
    Reader.__init__(self, stream)
  File "C:\Users\Office\Anaconda3\lib\site-packages\ruamel_yaml\reader.py", line 98, in __init__
    self.determine_encoding()
  File "C:\Users\Office\Anaconda3\lib\site-packages\ruamel_yaml\reader.py", line 149, in determine_encoding
    self.update(1)
  File "C:\Users\Office\Anaconda3\lib\site-packages\ruamel_yaml\reader.py", line 189, in update
    self.check_printable(data)
  File "C:\Users\Office\Anaconda3\lib\site-packages\ruamel_yaml\reader.py", line 160, in check_printable
    'unicode', "special characters are not allowed")
ruamel_yaml.reader.ReaderError: unacceptable character #x0000: special characters are not allowed
  in "C:\Users\Office\.condarc", position 0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Office\Anaconda3\Scripts\conda-script.py", line 5, in <module>
    sys.exit(conda.cli.main())
  File "C:\Users\Office\Anaconda3\lib\site-packages\conda\cli\main.py", line 164, in main
    return conda_exception_handler(_main, *args)
  File "C:\Users\Office\Anaconda3\lib\site-packages\conda\exceptions.py", line 589, in conda_exception_handler
    print_unexpected_error_message(e)
  File "C:\Users\Office\Anaconda3\lib\site-packages\conda\exceptions.py", line 526, in print_unexpected_error_message
    from conda.base.context import context
  File "C:\Users\Office\Anaconda3\lib\site-packages\conda\base\context.py", line 584, in <module>
    context = Context(SEARCH_PATH, APP_NAME, None)
  File "C:\Users\Office\Anaconda3\lib\site-packages\conda\common\configuration.py", line 715, in __init__
    self._set_search_path(search_path)
  File "C:\Users\Office\Anaconda3\lib\site-packages\conda\common\configuration.py", line 733, in _set_search_path
    self._set_raw_data(load_file_configs(search_path))
  File "C:\Users\Office\Anaconda3\lib\site-packages\conda\common\configuration.py", line 368, in load_file_configs
    raw_data = odict(kv for kv in chain.from_iterable(load_paths))
  File "C:\Users\Office\Anaconda3\lib\site-packages\conda\common\configuration.py", line 368, in <genexpr>
    raw_data = odict(kv for kv in chain.from_iterable(load_paths))
  File "C:\Users\Office\Anaconda3\lib\site-packages\conda\common\configuration.py", line 343, in _file_yaml_loader
    yield fullpath, YamlRawParameter.make_raw_parameters_from_file(fullpath)
  File "C:\Users\Office\Anaconda3\lib\site-packages\conda\common\configuration.py", line 331, in make_raw_parameters_from_file
    ruamel_yaml = yaml_load(fh)
  File "C:\Users\Office\Anaconda3\lib\site-packages\conda\common\yaml.py", line 26, in yaml_load
    return yaml.load(string, Loader=yaml.RoundTripLoader, version="1.2")
  File "C:\Users\Office\Anaconda3\lib\site-packages\ruamel_yaml\main.py", line 73, in load
    loader = Loader(stream, version, preserve_quotes=preserve_quotes)
  File "C:\Users\Office\Anaconda3\lib\site-packages\ruamel_yaml\loader.py", line 56, in __init__
    Reader.__init__(self, stream)
  File "C:\Users\Office\Anaconda3\lib\site-packages\ruamel_yaml\reader.py", line 98, in __init__
    self.determine_encoding()
  File "C:\Users\Office\Anaconda3\lib\site-packages\ruamel_yaml\reader.py", line 149, in determine_encoding
    self.update(1)
  File "C:\Users\Office\Anaconda3\lib\site-packages\ruamel_yaml\reader.py", line 189, in update
    self.check_printable(data)
  File "C:\Users\Office\Anaconda3\lib\site-packages\ruamel_yaml\reader.py", line 160, in check_printable
    'unicode', "special characters are not allowed")
ruamel_yaml.reader.ReaderError: unacceptable character #x0000: special characters are not allowed
  in "C:\Users\Office\.condarc", position 0
```
`conda list`
output ->
```
C:\Users\Office>conda list
Traceback (most recent call last):
  File "C:\Users\Office\Anaconda3\lib\site-packages\conda\exceptions.py", line 573, in conda_exception_handler
    return_value = func(*args, **kwargs)
  File "C:\Users\Office\Anaconda3\lib\site-packages\conda\cli\main.py", line 85, in _main
    from ..base.context import context
  File "C:\Users\Office\Anaconda3\lib\site-packages\conda\base\context.py", line 584, in <module>
    context = Context(SEARCH_PATH, APP_NAME, None)
  File "C:\Users\Office\Anaconda3\lib\site-packages\conda\common\configuration.py", line 715, in __init__
    self._set_search_path(search_path)
  File "C:\Users\Office\Anaconda3\lib\site-packages\conda\common\configuration.py", line 733, in _set_search_path
    self._set_raw_data(load_file_configs(search_path))
  File "C:\Users\Office\Anaconda3\lib\site-packages\conda\common\configuration.py", line 368, in load_file_configs
    raw_data = odict(kv for kv in chain.from_iterable(load_paths))
  File "C:\Users\Office\Anaconda3\lib\site-packages\conda\common\configuration.py", line 368, in <genexpr>
    raw_data = odict(kv for kv in chain.from_iterable(load_paths))
  File "C:\Users\Office\Anaconda3\lib\site-packages\conda\common\configuration.py", line 343, in _file_yaml_loader
    yield fullpath, YamlRawParameter.make_raw_parameters_from_file(fullpath)
  File "C:\Users\Office\Anaconda3\lib\site-packages\conda\common\configuration.py", line 331, in make_raw_parameters_from_file
    ruamel_yaml = yaml_load(fh)
  File "C:\Users\Office\Anaconda3\lib\site-packages\conda\common\yaml.py", line 26, in yaml_load
    return yaml.load(string, Loader=yaml.RoundTripLoader, version="1.2")
  File "C:\Users\Office\Anaconda3\lib\site-packages\ruamel_yaml\main.py", line 73, in load
    loader = Loader(stream, version, preserve_quotes=preserve_quotes)
  File "C:\Users\Office\Anaconda3\lib\site-packages\ruamel_yaml\loader.py", line 56, in __init__
    Reader.__init__(self, stream)
  File "C:\Users\Office\Anaconda3\lib\site-packages\ruamel_yaml\reader.py", line 98, in __init__
    self.determine_encoding()
  File "C:\Users\Office\Anaconda3\lib\site-packages\ruamel_yaml\reader.py", line 149, in determine_encoding
    self.update(1)
  File "C:\Users\Office\Anaconda3\lib\site-packages\ruamel_yaml\reader.py", line 189, in update
    self.check_printable(data)
  File "C:\Users\Office\Anaconda3\lib\site-packages\ruamel_yaml\reader.py", line 160, in check_printable
    'unicode', "special characters are not allowed")
ruamel_yaml.reader.ReaderError: unacceptable character #x0000: special characters are not allowed
  in "C:\Users\Office\.condarc", position 0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Office\Anaconda3\Scripts\conda-script.py", line 5, in <module>
    sys.exit(conda.cli.main())
  File "C:\Users\Office\Anaconda3\lib\site-packages\conda\cli\main.py", line 164, in main
    return conda_exception_handler(_main, *args)
  File "C:\Users\Office\Anaconda3\lib\site-packages\conda\exceptions.py", line 589, in conda_exception_handler
    print_unexpected_error_message(e)
  File "C:\Users\Office\Anaconda3\lib\site-packages\conda\exceptions.py", line 526, in print_unexpected_error_message
    from conda.base.context import context
  File "C:\Users\Office\Anaconda3\lib\site-packages\conda\base\context.py", line 584, in <module>
    context = Context(SEARCH_PATH, APP_NAME, None)
  File "C:\Users\Office\Anaconda3\lib\site-packages\conda\common\configuration.py", line 715, in __init__
    self._set_search_path(search_path)
  File "C:\Users\Office\Anaconda3\lib\site-packages\conda\common\configuration.py", line 733, in _set_search_path
    self._set_raw_data(load_file_configs(search_path))
  File "C:\Users\Office\Anaconda3\lib\site-packages\conda\common\configuration.py", line 368, in load_file_configs
    raw_data = odict(kv for kv in chain.from_iterable(load_paths))
  File "C:\Users\Office\Anaconda3\lib\site-packages\conda\common\configuration.py", line 368, in <genexpr>
    raw_data = odict(kv for kv in chain.from_iterable(load_paths))
  File "C:\Users\Office\Anaconda3\lib\site-packages\conda\common\configuration.py", line 343, in _file_yaml_loader
    yield fullpath, YamlRawParameter.make_raw_parameters_from_file(fullpath)
  File "C:\Users\Office\Anaconda3\lib\site-packages\conda\common\configuration.py", line 331, in make_raw_parameters_from_file
    ruamel_yaml = yaml_load(fh)
  File "C:\Users\Office\Anaconda3\lib\site-packages\conda\common\yaml.py", line 26, in yaml_load
    return yaml.load(string, Loader=yaml.RoundTripLoader, version="1.2")
  File "C:\Users\Office\Anaconda3\lib\site-packages\ruamel_yaml\main.py", line 73, in load
    loader = Loader(stream, version, preserve_quotes=preserve_quotes)
  File "C:\Users\Office\Anaconda3\lib\site-packages\ruamel_yaml\loader.py", line 56, in __init__
    Reader.__init__(self, stream)
  File "C:\Users\Office\Anaconda3\lib\site-packages\ruamel_yaml\reader.py", line 98, in __init__
    self.determine_encoding()
  File "C:\Users\Office\Anaconda3\lib\site-packages\ruamel_yaml\reader.py", line 149, in determine_encoding
    self.update(1)
  File "C:\Users\Office\Anaconda3\lib\site-packages\ruamel_yaml\reader.py", line 189, in update
    self.check_printable(data)
  File "C:\Users\Office\Anaconda3\lib\site-packages\ruamel_yaml\reader.py", line 160, in check_printable
    'unicode', "special characters are not allowed")
ruamel_yaml.reader.ReaderError: unacceptable character #x0000: special characters are not allowed
  in "C:\Users\Office\.condarc", position 0
```

**Comment by mingwandroid** [comment]
I've seen this before. The solution was to delete `C:\Users\Office\.condarc`. If you have stuff in that file that you want to keep then it's best to make a new one and re-enter it.
