### ISSUE TITLE
Navigator does not load up - Mac - post updates

### ISSUE THREAD

**Issue by jai2033shankar** [ContinuumIO/anaconda-issues#1654]
@goanpeca : Have updated the packages, and post that the navigator gave up on me. 
I have re installed twice, and followed all the directions as indicated on site - Continuum, nothing seems to work. Below is the error trace:

Last login: Tue May  2 07:57:31 on ttys000
VISHWAKARMAsAir:~ VISH$ anaconda-navigator
Traceback (most recent call last):
  File "/Users/VISH/anaconda2/bin/anaconda-navigator", line 6, in <module>
    sys.exit(anaconda_navigator.app.main.main())
  File "/Users/VISH/anaconda2/lib/python2.7/site-packages/anaconda_navigator/app/main.py", line 52, in main
    start_app(options)
  File "/Users/VISH/anaconda2/lib/python2.7/site-packages/anaconda_navigator/app/start.py", line 87, in start_app
    window = run_app(splash)
  File "/Users/VISH/anaconda2/lib/python2.7/site-packages/anaconda_navigator/app/start.py", line 42, in run_app
    window = MainWindow(splash=splash)
  File "/Users/VISH/anaconda2/lib/python2.7/site-packages/anaconda_navigator/widgets/main_window.py", line 206, in __init__
    self.environments_tab = EnvironmentsTab(parent=self)
  File "/Users/VISH/anaconda2/lib/python2.7/site-packages/anaconda_navigator/widgets/tabs/environments.py", line 131, in __init__
    data_directory=CHANNELS_PATH,
  File "/Users/VISH/anaconda2/lib/python2.7/site-packages/anaconda_navigator/widgets/manager/packages.py", line 382, in __init__
    self.api.client_set_domain(self.api.client_get_api_url())
  File "/Users/VISH/anaconda2/lib/python2.7/site-packages/anaconda_navigator/api/client_api.py", line 365, in set_domain
    binstar_client.utils.set_config(config)
  File "/Users/VISH/anaconda2/lib/python2.7/site-packages/binstar_client/utils/config.py", line 260, in set_config
    save_config(data, USER_CONFIG if user else SYSTEM_CONFIG)
  File "/Users/VISH/anaconda2/lib/python2.7/site-packages/binstar_client/utils/config.py", line 255, in save_config
    raise BinstarError('%s: %s' % (exc.filename, exc.strerror,))
binstar_client.errors.BinstarError: /Users/VISH/.continuum/anaconda-client: Permission denied
_____________

Any help is appreciated. 

Thanks

**Comment by goanpeca** [comment]
Hi @jai2033shankar you have a couple of options you can delete the `.continuum` folder which was created with incorrect permissions by a previous version of Anaconda.

You can go to the terminal and type

`sudo rm -rf ~/.continuum/` and restart navigator and it should work

**Comment by jai2033shankar** [comment]
Worked for me @goanpeca . Thank you.
