### ISSUE TITLE
Newly created Py27 Env won't run Spyder

### ISSUE THREAD

**Issue by kalefranz** [ContinuumIO/anaconda-issues#1708]
_From @dartdog on November 7, 2016 17:51_

After having the issues described here https://github.com/conda/conda/issues/3827 and here https://github.com/conda/conda/issues/3437 I created a new python 27 environment with anaconda:

  conda create -n py27n python=2.7 anaconda
installed and tried to start up spyder and got:

source activate py27n
(py27n) tom@tomServal:~$ spyder
Traceback (most recent call last):
  File "/home/tom/anaconda3/envs/py27n/bin/spyder", line 6, in <module>
    sys.exit(spyder.app.start.main())
  File "/home/tom/anaconda3/envs/py27n/lib/python2.7/site-packages/spyder/app/start.py", line 103, in main
    from spyder.app import mainwindow
  File "/home/tom/anaconda3/envs/py27n/lib/python2.7/site-packages/spyder/app/mainwindow.py", line 92, in <module>
    from qtpy import QtWebEngineWidgets  # analysis:ignore
  File "/home/tom/anaconda3/envs/py27n/lib/python2.7/site-packages/qtpy/QtWebEngineWidgets.py", line 26, in <module>
    from PyQt5.QtWebKitWidgets import QWebPage as QWebEnginePage
ImportError: libiconv.so.2: cannot open shared object file: No such file or directory

_Copied from original issue: conda/conda#3828_

**Comment by nehaljwani** [comment]
libiconv has been added as a dependency to anaconda >= 4.3.0 . Updating anaconda should solve this. Otherwise install the conda package `libiconv`

```bash
conda install libiconv
```

**Comment by ccordoba12** [comment]
Ok, closing because this seems to be solved.
