### ISSUE TITLE
pip install ImportError in conda env 

### ISSUE THREAD

**Issue by kalefranz** [ContinuumIO/anaconda-issues#1710]
_From @fonnesbeck on October 28, 2016 13:32_

Trying to use `pip` in a fresh conda env results in the following ImportError:

``` bash
Obtaining file:///Users/fonnescj/Repositories/pymc3
Could not import setuptools which is required to install from a source distribution.
Traceback (most recent call last):
  File "/Users/fonnescj/anaconda3/envs/dev/lib/python3.5/site-packages/pip/req/req_install.py", line 372, in setup_py
    import setuptools  # noqa
  File "/Users/fonnescj/anaconda3/envs/dev/lib/python3.5/site-packages/setuptools/__init__.py", line 13, in <module>
    from setuptools.extension import Extension
  File "/Users/fonnescj/anaconda3/envs/dev/lib/python3.5/site-packages/setuptools/extension.py", line 9, in <module>
    from .monkey import get_unpatched
ImportError: No module named 'setuptools.monkey'
```

Confirmed that setuptools and pip are up to date with conda.

Running Anaconda Python 3.5.2 on macOS 10.12.

_Copied from original issue: conda/conda#3757_

**Comment by nehaljwani** [comment]
@fonnesbeck Which version of setuptools do you have in your conda environment? Could you please share output for: `conda list | grep setuptools`

**Comment by fonnesbeck** [comment]
Actually, I don't see this issue anymore, so I don't know if it is applicable anymore.

**Comment by nehaljwani** [comment]
Closing as it is not reproducible. Re-open if you feel otherwise.
