### ISSUE TITLE
i can't install mingw

### ISSUE THREAD

**Issue by kalefranz** [ContinuumIO/anaconda-issues#1723]
_From @leila000 on May 12, 2017 7:58_

I had this issue below
-----------------------------------
WARNING (theano.configdefaults): g++ not detected ! Theano will be
 unable to execute optimized C-implementations (for both CPU and GPU) and
 will default to Python implementations. Performance will be severely
 degraded. To remove this warning, set Theano flags cxx to an empty string.
----------------------------------
and i did some search and someone said try to install mingw
but it didn't work well and i can't see why 
please help
thanks

=======================================================
(C:\Users\gy\Anaconda3) C:\Windows\system32>conda install mingw
Fetching package metadata .........
Solving package specifications: ..........

Package plan for installation in environment C:\Users\gy\Anaconda3:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    mingw-4.7                  |                1        56.3 MB

The following NEW packages will be INSTALLED:

    conda-env: 2.6.0-0
    mingw:     4.7-1

The following packages will be UPDATED:

    conda:     4.2.9-py35_0  --> 4.3.17-py35_0
    pyopenssl: 16.0.0-py35_0 --> 16.2.0-py35_0
    requests:  2.11.1-py35_0 --> 2.13.0-py35_0

Proceed ([y]/n)? y

Fetching packages ...
An unexpected error has occurred.########           | ETA:  0:04:54  66.53 kB/s
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Current conda install:

               platform : win-64
          conda version : 4.2.9
       conda is private : False
      conda-env version : 4.2.9
    conda-build version : 2.0.2
         python version : 3.5.2.final.0
       requests version : 2.11.1
       root environment : C:\Users\gy\Anaconda3  (writable)
    default environment : C:\Users\gy\Anaconda3
       envs directories : C:\Users\gy\Anaconda3\envs
          package cache : C:\Users\gy\Anaconda3\pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/win-64/
                          https://repo.continuum.io/pkgs/free/noarch/
                          https://repo.continuum.io/pkgs/pro/win-64/
                          https://repo.continuum.io/pkgs/pro/noarch/
                          https://repo.continuum.io/pkgs/msys2/win-64/
                          https://repo.continuum.io/pkgs/msys2/noarch/
            config file : None
           offline mode : False

`$ C:\Users\gy\Anaconda3\Scripts\conda-script.py install mingw`

    Traceback (most recent call last):
      File "C:\Users\gy\Anaconda3\lib\site-packages\requests\packages\urllib3\response.py", line 232, in _error_catcher
        yield
      File "C:\Users\gy\Anaconda3\lib\site-packages\requests\packages\urllib3\response.py", line 314, in read
        data = self._fp.read(amt)
      File "C:\Users\gy\Anaconda3\lib\http\client.py", line 448, in read
        n = self.readinto(b)
      File "C:\Users\gy\Anaconda3\lib\http\client.py", line 488, in readinto
        n = self.fp.readinto(b)
      File "C:\Users\gy\Anaconda3\lib\socket.py", line 575, in readinto
        return self._sock.recv_into(b)
      File "C:\Users\gy\Anaconda3\lib\ssl.py", line 929, in recv_into
        return self.read(nbytes, buffer)
      File "C:\Users\gy\Anaconda3\lib\ssl.py", line 791, in read
        return self._sslobj.read(len, buffer)
      File "C:\Users\gy\Anaconda3\lib\ssl.py", line 575, in read
        v = self._sslobj.read(len, buffer)
    socket.timeout: The read operation timed out

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "C:\Users\gy\Anaconda3\lib\site-packages\requests\models.py", line 676, in generate
        for chunk in self.raw.stream(chunk_size, decode_content=True):
      File "C:\Users\gy\Anaconda3\lib\site-packages\requests\packages\urllib3\response.py", line 357, in stream
        data = self.read(amt=amt, decode_content=decode_content)
      File "C:\Users\gy\Anaconda3\lib\site-packages\requests\packages\urllib3\response.py", line 324, in read
        flush_decoder = True
      File "C:\Users\gy\Anaconda3\lib\contextlib.py", line 77, in __exit__
        self.gen.throw(type, value, traceback)
      File "C:\Users\gy\Anaconda3\lib\site-packages\requests\packages\urllib3\response.py", line 237, in _error_catcher
        raise ReadTimeoutError(self._pool, None, 'Read timed out.')
    requests.packages.urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='repo.continuum.io', port=443): Read timed out.

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "C:\Users\gy\Anaconda3\lib\site-packages\conda\fetch.py", line 419, in download
        for chunk in resp.iter_content(2**14):
      File "C:\Users\gy\Anaconda3\lib\site-packages\requests\models.py", line 683, in generate
        raise ConnectionError(e)
    requests.exceptions.ConnectionError: HTTPSConnectionPool(host='repo.continuum.io', port=443): Read timed out.

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "C:\Users\gy\Anaconda3\lib\site-packages\conda\cli\install.py", line 405, in install
        execute_actions(actions, index, verbose=not context.quiet)
      File "C:\Users\gy\Anaconda3\lib\site-packages\conda\plan.py", line 643, in execute_actions
        inst.execute_instructions(plan, index, verbose)
      File "C:\Users\gy\Anaconda3\lib\site-packages\conda\instructions.py", line 134, in execute_instructions
        cmd(state, arg)
      File "C:\Users\gy\Anaconda3\lib\site-packages\conda\instructions.py", line 47, in FETCH_CMD
        fetch_pkg(state['index'][arg + '.tar.bz2'])
      File "C:\Users\gy\Anaconda3\lib\site-packages\conda\fetch.py", line 336, in fetch_pkg
        download(url, path, session=session, md5=info['md5'], urlstxt=True)
      File "C:\Users\gy\Anaconda3\lib\site-packages\conda\fetch.py", line 438, in download
        raise CondaRuntimeError("Could not open %r for writing (%s)." % (pp, e))
    conda.exceptions.CondaRuntimeError: Runtime error: Could not open 'C:\\Users\\gy\\Anaconda3\\pkgs\\mingw-4.7-1.tar.bz2.part' for writing (HTTPSConnectionPool(host='repo.continuum.io', port=443): Read timed out.).

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "C:\Users\gy\Anaconda3\lib\site-packages\conda\exceptions.py", line 473, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "C:\Users\gy\Anaconda3\lib\site-packages\conda\cli\main.py", line 144, in _main
        exit_code = args.func(args, p)
      File "C:\Users\gy\Anaconda3\lib\site-packages\conda\cli\main_install.py", line 80, in execute
        install(args, parser, 'install')
      File "C:\Users\gy\Anaconda3\lib\site-packages\conda\cli\install.py", line 422, in install
        raise CondaSystemExit('Exiting', e)
      File "C:\Users\gy\Anaconda3\lib\contextlib.py", line 77, in __exit__
        self.gen.throw(type, value, traceback)
      File "C:\Users\gy\Anaconda3\lib\site-packages\conda\cli\common.py", line 573, in json_progress_bars
        yield
      File "C:\Users\gy\Anaconda3\lib\site-packages\conda\cli\install.py", line 420, in install
        raise CondaRuntimeError('RuntimeError: %s' % e)
    conda.exceptions.CondaRuntimeError: Runtime error: RuntimeError: Runtime error: Could not open 'C:\\Users\\gy\\Anaconda3\\pkgs\\mingw-4.7-1.tar.bz2.part' for writing (HTTPSConnectionPool(host='repo.continuum.io', port=443): Read timed out.).

_Copied from original issue: conda/conda#5299_

**Comment by kalefranz** [comment]
_From @mingwandroid on May 12, 2017 8:55_

You do not need `mingw`, that is old and doesn't support 64-bit. `conda install theano` is enough. Try that from an `Anaconda Prompt` and try again from that same prompt.

Please also show the output of `conda list --show-channel-urls`.

**Comment by kalefranz** [comment]
This is an intermittent HTTP error.  `conda update conda` will help.

**Comment by kalefranz** [comment]
_From @mingwandroid on May 12, 2017 18:18_

@kalefranz Please move this to anaconda-issues, it's still open as I've requested feedback from @leila000.
