### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by fanglei80** [ContinuumIO/anaconda-issues#1739]
The following errors occured:

None:
Traceback (most recent call last):
  File "/Users/fanglei/anaconda/lib/python2.7/site-packages/conda/exceptions.py", line 473, in conda_exception_handler
    return_value = func(*args, **kwargs)
  File "/Users/fanglei/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 144, in _main
    exit_code = args.func(args, p)
  File "/Users/fanglei/anaconda/lib/python2.7/site-packages/conda/cli/main_install.py", line 80, in execute
    install(args, parser, 'install')
  File "/Users/fanglei/anaconda/lib/python2.7/site-packages/conda/cli/install.py", line 238, in install
    prefix=prefix)
  File "/Users/fanglei/anaconda/lib/python2.7/site-packages/conda/api.py", line 24, in get_index
    index = fetch_index(channel_urls, use_cache=use_cache, unknown=unknown)
  File "/Users/fanglei/anaconda/lib/python2.7/site-packages/conda/fetch.py", line 293, in fetch_index
    for url in urls]
  File "/Users/fanglei/anaconda/lib/python2.7/site-packages/conda/fetch.py", line 70, in func
    res = f(*args, **kwargs)
  File "/Users/fanglei/anaconda/lib/python2.7/site-packages/conda/fetch.py", line 187, in fetch_repodata
    raise CondaRuntimeError(msg)
CondaRuntimeError: Runtime error: Connection error: HTTPSConnectionPool(host='repo.continuum.io', port=443): Max retries exceeded with url: /pkgs/free/osx-64/repodata.json.bz2 (Caused by ReadTimeoutError("HTTPSConnectionPool(host='repo.continuum.io', port=443): Read timed out. (read timeout=3.05)",)): https://repo.continuum.io/pkgs/free/osx-64/

{'platform': 'osx-64', 'version': '1.2.1', 'conda': u'4.2.9', 'qt': '4.8.7', 'language': 'en', 'python': '2.7.12', 'os': 'Darwin;16.5.0;Darwin Kernel Version 16.5.0: Fri Mar  3 16:52:33 PST 2017; root:xnu-3789.51.2~3/RELEASE_X86_64;x86_64;i386', 'pyqt': u'4.11.4'}

**Comment by Shuolongbj** [comment]
time out .pls try to run some times again or use the tsinghua mirror
ref:https://mirrors.tuna.tsinghua.edu.cn/help/anaconda/

**Comment by goanpeca** [comment]
@fanglei80  You could also update navigator to a more up to date version, by running on the **Anaconda Command Prompt**:

```
$ conda remove qt=4 pyqt=4
$ conda remove qt=5 pyqt=5
$ conda install anaconda-navigator
```
