### ISSUE TITLE
Anaconda won't launch on Mac

### ISSUE THREAD

**Issue by diegodeplaen** [ContinuumIO/anaconda-issues#1742]
Greetings to all.

When I try to launch Anaconda in the cmd with `anaconda-navigator`, I get the following message:

```
Traceback (most recent call last):
  File "/Users/diegodeplaen/anaconda/bin/anaconda-navigator", line 6, in <module>
    sys.exit(anaconda_navigator.app.main.main())
  File "/Users/diegodeplaen/anaconda/lib/python3.5/site-packages/anaconda_navigator/app/main.py", line 70, in main
    window = run_app(splash)
  File "/Users/diegodeplaen/anaconda/lib/python3.5/site-packages/anaconda_navigator/app/main.py", line 38, in run_app
    window = MainWindow(splash=splash)
  File "/Users/diegodeplaen/anaconda/lib/python3.5/site-packages/anaconda_navigator/widgets/main_window.py", line 145, in __init__
    self.api = AnacondaAPI()
  File "/Users/diegodeplaen/anaconda/lib/python3.5/site-packages/anaconda_navigator/api/anaconda_api.py", line 434, in AnacondaAPI
    ANACONDA_API = _AnacondaAPI()
  File "/Users/diegodeplaen/anaconda/lib/python3.5/site-packages/anaconda_navigator/api/anaconda_api.py", line 39, in __init__
    self._conda_api = CondaAPI()
  File "/Users/diegodeplaen/anaconda/lib/python3.5/site-packages/anaconda_navigator/api/conda_api.py", line 1185, in CondaAPI
    CONDA_API = _CondaAPI()
  File "/Users/diegodeplaen/anaconda/lib/python3.5/site-packages/anaconda_navigator/api/conda_api.py", line 267, in __init__
    self.set_root_prefix()
  File "/Users/diegodeplaen/anaconda/lib/python3.5/site-packages/anaconda_navigator/api/conda_api.py", line 374, in set_root_prefix
    self.ROOT_PREFIX = info['root_prefix']
TypeError: byte indices must be integers or slices, not str

```
When I enter `conda list`, i get the following:

```
An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues



Traceback (most recent call last):
  File "/Users/diegodeplaen/anaconda/lib/python3.5/site-packages/conda/exceptions.py", line 626, in conda_exception_handler
    return_value = func(*args, **kwargs)
  File "/Users/diegodeplaen/anaconda/lib/python3.5/site-packages/conda/cli/main.py", line 98, in _main
    imported = importlib.import_module(module)
  File "/Users/diegodeplaen/anaconda/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/Users/diegodeplaen/anaconda/lib/python3.5/site-packages/conda/cli/main_list.py", line 20, in <module>
    from ..egg_info import get_egg_info
  File "/Users/diegodeplaen/anaconda/lib/python3.5/site-packages/conda/egg_info.py", line 15, in <module>
    from .misc import rel_path
  File "/Users/diegodeplaen/anaconda/lib/python3.5/site-packages/conda/misc.py", line 19, in <module>
    from .core.index import get_index, _supplement_index_with_cache
  File "/Users/diegodeplaen/anaconda/lib/python3.5/site-packages/conda/core/index.py", line 8, in <module>
    from .package_cache import PackageCache
  File "/Users/diegodeplaen/anaconda/lib/python3.5/site-packages/conda/core/package_cache.py", line 10, in <module>
    from .path_actions import CacheUrlAction, ExtractPackageAction
  File "/Users/diegodeplaen/anaconda/lib/python3.5/site-packages/conda/core/path_actions.py", line 31, in <module>
    from ..gateways.download import download
  File "/Users/diegodeplaen/anaconda/lib/python3.5/site-packages/conda/gateways/download.py", line 16, in <module>
    from ..connection import CondaSession
  File "/Users/diegodeplaen/anaconda/lib/python3.5/site-packages/conda/connection.py", line 16, in <module>
    from requests.utils import get_auth_from_url, get_netrc_auth
ImportError: cannot import name 'get_auth_from_url'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/diegodeplaen/anaconda/bin/conda", line 6, in <module>
    sys.exit(conda.cli.main())
  File "/Users/diegodeplaen/anaconda/lib/python3.5/site-packages/conda/cli/main.py", line 162, in main
    return conda_exception_handler(_main, *args)
  File "/Users/diegodeplaen/anaconda/lib/python3.5/site-packages/conda/exceptions.py", line 630, in conda_exception_handler
    return handle_exception(e)
  File "/Users/diegodeplaen/anaconda/lib/python3.5/site-packages/conda/exceptions.py", line 620, in handle_exception
    print_unexpected_error_message(e)
  File "/Users/diegodeplaen/anaconda/lib/python3.5/site-packages/conda/exceptions.py", line 578, in print_unexpected_error_message
    info_stdout, info_stderr = get_info()
  File "/Users/diegodeplaen/anaconda/lib/python3.5/site-packages/conda/exceptions.py", line 548, in get_info
    args.func(args, p)
  File "/Users/diegodeplaen/anaconda/lib/python3.5/site-packages/conda/cli/main_info.py", line 148, in execute
    from conda.api import get_index
  File "/Users/diegodeplaen/anaconda/lib/python3.5/site-packages/conda/api.py", line 1, in <module>
    from .core.index import get_index
  File "/Users/diegodeplaen/anaconda/lib/python3.5/site-packages/conda/core/index.py", line 8, in <module>
    from .package_cache import PackageCache
  File "/Users/diegodeplaen/anaconda/lib/python3.5/site-packages/conda/core/package_cache.py", line 10, in <module>
    from .path_actions import CacheUrlAction, ExtractPackageAction
  File "/Users/diegodeplaen/anaconda/lib/python3.5/site-packages/conda/core/path_actions.py", line 31, in <module>
    from ..gateways.download import download
  File "/Users/diegodeplaen/anaconda/lib/python3.5/site-packages/conda/gateways/download.py", line 16, in <module>
    from ..connection import CondaSession
  File "/Users/diegodeplaen/anaconda/lib/python3.5/site-packages/conda/connection.py", line 16, in <module>
    from requests.utils import get_auth_from_url, get_netrc_auth
ImportError: cannot import name 'get_auth_from_url'

```

**Comment by goanpeca** [comment]
@kalefranz ?

**Comment by kalefranz** [comment]
You've apparently somehow uninstalled requests. You might be able to recover with `pip install requests`. If not, you'll need to download a miniconda installer that has python 3.5, and then run it over your current install.

**Comment by diegodeplaen** [comment]
It worked thanks!
