### ISSUE TITLE
Anaconda > Spyder > System Error . 

### ISSUE THREAD

**Issue by Lolo24ca** [ContinuumIO/anaconda-issues#1744]
Hi ,

Spyder (3 ) was running fine up until this evening when i got the following error.

```
Traceback (most recent call last):

  File "<ipython-input-1-a5988a9d12cd>", line 1, in <module>
    runfile('/Users/Lio/Desktop/NM +/Nasdaq_Momentum_rev2.py', wdir='/Users/Lio/Desktop/NM +')

  File "/Users/Lio/anaconda/lib/python3.6/site-packages/spyder/utils/site/sitecustomize.py", line 866, in runfile
    execfile(filename, namespace)

  File "/Users/Lio/anaconda/lib/python3.6/site-packages/spyder/utils/site/sitecustomize.py", line 102, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "/Users/Lio/Desktop/NM +/Nasdaq_Momentum_rev2.py", line 55, in <module>
    benchmark_daily_hist = web.DataReader(benchmark, datasource, start, end)

  File "/Users/Lio/anaconda/lib/python3.6/site-packages/pandas_datareader/data.py", line 132, in DataReader
    session=session).read()

  File "/Users/Lio/anaconda/lib/python3.6/site-packages/pandas_datareader/base.py", line 145, in __init__
    pause=pause, session=session)

  File "/Users/Lio/anaconda/lib/python3.6/site-packages/pandas_datareader/base.py", line 47, in __init__
    start, end = _sanitize_dates(start, end)

  File "/Users/Lio/anaconda/lib/python3.6/site-packages/pandas_datareader/_utils.py", line 61, in _sanitize_dates
    start = to_datetime(start)

  File "/Users/Lio/anaconda/lib/python3.6/site-packages/pandas/util/decorators.py", line 91, in wrapper
    return func(*args, **kwargs)

  File "/Users/Lio/anaconda/lib/python3.6/site-packages/pandas/tseries/tools.py", line 291, in to_datetime
    unit=unit, infer_datetime_format=infer_datetime_format)

  File "/Users/Lio/anaconda/lib/python3.6/site-packages/pandas/tseries/tools.py", line 429, in _to_datetime
    return _convert_listlike(np.array([arg]), box, format)[0]

  File "/Users/Lio/anaconda/lib/python3.6/site-packages/pandas/tseries/tools.py", line 398, in _convert_listlike
    require_iso8601=require_iso8601

  File "pandas/tslib.pyx", line 2134, in pandas.tslib.array_to_datetime (pandas/tslib.c:41972)

  File "pandas/tslib.pyx", line 2269, in pandas.tslib.array_to_datetime (pandas/tslib.c:40684)

  File "pandas/tslib.pyx", line 2229, in pandas.tslib.array_to_datetime (pandas/tslib.c:39919)

  File "pandas/src/datetime.pxd", line 141, in datetime._string_to_dts (pandas/tslib.c:85631)

**SystemError: <class 'str'> returned a result with an error set**

```

not sure what make of it . Any help would be greatly appreciated

**Comment by ccordoba12** [comment]
What if you rename or put your code in a directory other than `/Users/Lio/Desktop/NM +`. This seems the cause of the error to me.

**Comment by Lolo24ca** [comment]
Hi Carlos ,

Thank you for your email. The issue is not with the folder, its a system error with Ananconda. I followed your instruction and changed folder , but got the same error as reported yesterday.

**Comment by ccordoba12** [comment]
This errors seems more related to Pandas than to Spyder. Pinging @TomAugspurger about it.

**Comment by Lolo24ca** [comment]
Thanks Carlos for your quick reply .

**Comment by TomAugspurger** [comment]
What version of pandas and pandas datreader are you using? Pandas data reader just had a release (yesterday I think) if you want to try upgrading that it might work.

**Comment by Lolo24ca** [comment]
Hi Tom , 

I upgraded the data reader to the latest version ( 0.4.0) , still doesn’t work. I able to run the same code with no issue on another computer , solely on Python. but seem to have an issue when running the same code in Anaconda. Issue started on Thursday. I ‘ll try to uninstall and install Anaconda again and see if it works. Please let me know if you have any other idea on what may be causing this. 

Thanks for your help 

Lionel

**Comment by Lolo24ca** [comment]
i removed and re-install anaconda , but still getting the same system error.

**Comment by TomAugspurger** [comment]
@Lolo24ca can you post your version info? `import pandas; pandas.show_versions()`

**Comment by Lolo24ca** [comment]
Hi Tom , 

Version 0.18.1 of Pandas is installed .. please see below 

```
INSTALLED VERSIONS
------------------
commit: None
python: 3.6.0.final.0
python-bits: 64
OS: Darwin
OS-release: 16.5.0
machine: x86_64
processor: i386
byteorder: little
LC_ALL: None
LANG: None

pandas: 0.18.1
nose: 1.3.7
pip: 9.0.1
setuptools: 35.0.2
Cython: 0.25.2
numpy: 1.11.3
scipy: 0.18.1
statsmodels: None
xarray: None
IPython: 6.0.0
sphinx: 1.6.1
patsy: 0.4.1
dateutil: 2.6.0
pytz: 2017.2
blosc: None
bottleneck: 1.2.0
tables: 3.3.0
numexpr: 2.6.1
matplotlib: 2.0.0
openpyxl: 2.4.1
xlrd: 1.0.0
xlwt: 1.2.0
xlsxwriter: 0.9.6
lxml: 3.7.2
bs4: 4.5.3
html5lib: 0.999999999
httplib2: None
apiclient: None
sqlalchemy: 1.1.5
pymysql: None
psycopg2: None
jinja2: 2.9.6
boto: 2.45.0
pandas_datareader: 0.4.0
```
Thank you.

**Comment by TomAugspurger** [comment]
Ah that might be it then. You'll need either an older version of data_reader if you're keeping that pandas, or upgrade pandas to 0.20.1 if you're using 0.4.0.

**Comment by Lolo24ca** [comment]
You are the best Tom ! its working ..thank you  :) 

cheers 

Lionel

**Comment by pri54** [comment]
Hello.,
Spyder 3.2.4 and python2.7.14 was running fine up.i got the following error.

File "<ipython-input-2-a78c6e49bc27>", line 1, in <module>
    runfile('D:/antenna/antennacodingeverthing/h1_line_profile.py', wdir='D:/antenna/antennacodingeverthing')

  File "D:\ProgramData\Anaconda2\lib\site-packages\spyder\utils\site\sitecustomize.py", line 710, in runfile
    execfile(filename, namespace)

  File "D:\ProgramData\Anaconda2\lib\site-packages\spyder\utils\site\sitecustomize.py", line 86, in execfile
    exec(compile(scripttext, filename, 'exec'), glob, loc)

  File "D:/antenna/antennacodingeverthing/h1_line_profile.py", line 12, in <module>
    fid = open(filename, 'rb')

IOError: [Errno 2] No such file or directory: 'D:\\antenna\\antenna_coding_everthing\\test_run\\45E_40S\\1420000000_30_sec.dat'


Any help would be greatly appreciated
