### ISSUE TITLE
SSLError when attempting to install or update anything while ssl_verify true

### ISSUE THREAD

**Issue by dkhungry** [ContinuumIO/anaconda-issues#1747]
I'm running into ssl_verify issues with running install or update when ssl_verify is true.  It works when this is false.  I just installed anaconda on my rig.

I've already tried:
- setting ssl_verify to false and updating conda, requests, openssl, cryptography, pyopenssl
- download cacert.pem and point ssl_verify to it
- reinstalling anaconda

I've looked through some of the other issues and haven't found an applicable fix yet.  I'd rather not have to disable ssl_verify, so any help would be appreciated.

Trace:
```
`$ C:\Program Files\Anaconda3\Scripts\conda-script.py update conda -v`




    Traceback (most recent call last):
      File "C:\Program Files\Anaconda3\lib\site-packages\requests\packages\urlli
b3\contrib\pyopenssl.py", line 438, in wrap_socket
        cnx.do_handshake()
      File "C:\Program Files\Anaconda3\lib\site-packages\OpenSSL\SSL.py", line 1
638, in do_handshake
        self._raise_ssl_error(self._ssl, result)
      File "C:\Program Files\Anaconda3\lib\site-packages\OpenSSL\SSL.py", line 1
378, in _raise_ssl_error
        _raise_current_error()
      File "C:\Program Files\Anaconda3\lib\site-packages\OpenSSL\_util.py", line
 54, in exception_from_error_queue
        raise exception_type(errors)
    OpenSSL.SSL.Error: [('SSL routines', 'ssl3_get_server_certificate', 'certifi
cate verify failed')]

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "C:\Program Files\Anaconda3\lib\site-packages\requests\packages\urlli
b3\connectionpool.py", line 600, in urlopen
        chunked=chunked)
      File "C:\Program Files\Anaconda3\lib\site-packages\requests\packages\urlli
b3\connectionpool.py", line 345, in _make_request
        self._validate_conn(conn)
      File "C:\Program Files\Anaconda3\lib\site-packages\requests\packages\urlli
b3\connectionpool.py", line 844, in _validate_conn
        conn.connect()
      File "C:\Program Files\Anaconda3\lib\site-packages\requests\packages\urlli
b3\connection.py", line 326, in connect
        ssl_context=context)
      File "C:\Program Files\Anaconda3\lib\site-packages\requests\packages\urlli
b3\util\ssl_.py", line 325, in ssl_wrap_socket
        return context.wrap_socket(sock, server_hostname=server_hostname)
      File "C:\Program Files\Anaconda3\lib\site-packages\requests\packages\urlli
b3\contrib\pyopenssl.py", line 445, in wrap_socket
        raise ssl.SSLError('bad handshake: %r' % e)
    ssl.SSLError: ("bad handshake: Error([('SSL routines', 'ssl3_get_server_cert
ificate', 'certificate verify failed')],)",)

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "C:\Program Files\Anaconda3\lib\site-packages\requests\adapters.py",
line 438, in send
        timeout=timeout
      File "C:\Program Files\Anaconda3\lib\site-packages\requests\packages\urlli
b3\connectionpool.py", line 630, in urlopen
        raise SSLError(e)
    requests.packages.urllib3.exceptions.SSLError: ("bad handshake: Error([('SSL
 routines', 'ssl3_get_server_certificate', 'certificate verify failed')],)",)

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "C:\Program Files\Anaconda3\lib\site-packages\conda\core\repodata.py"
, line 138, in fetch_repodata_remote_request
        timeout=timeout)
      File "C:\Program Files\Anaconda3\lib\site-packages\requests\sessions.py",
line 531, in get
        return self.request('GET', url, **kwargs)
      File "C:\Program Files\Anaconda3\lib\site-packages\requests\sessions.py",
line 518, in request
        resp = self.send(prep, **send_kwargs)
      File "C:\Program Files\Anaconda3\lib\site-packages\requests\sessions.py",
line 639, in send
        r = adapter.send(request, **kwargs)
      File "C:\Program Files\Anaconda3\lib\site-packages\requests\adapters.py",
line 512, in send
        raise SSLError(e, request=request)
    requests.exceptions.SSLError: ("bad handshake: Error([('SSL routines', 'ssl3
_get_server_certificate', 'certificate verify failed')],)",)

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "C:\Program Files\Anaconda3\lib\site-packages\conda\exceptions.py", l
ine 632, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "C:\Program Files\Anaconda3\lib\site-packages\conda\cli\main.py", lin
e 134, in _main
        exit_code = args.func(args, p)
      File "C:\Program Files\Anaconda3\lib\site-packages\conda\cli\main_update.p
y", line 65, in execute
        install(args, parser, 'update')
      File "C:\Program Files\Anaconda3\lib\site-packages\conda\cli\install.py",
line 221, in install
        unknown=index_args['unknown'], prefix=prefix)
      File "C:\Program Files\Anaconda3\lib\site-packages\conda\core\index.py", l
ine 93, in get_index
        index = fetch_index(channel_priority_map, use_cache=use_cache)
      File "C:\Program Files\Anaconda3\lib\site-packages\conda\core\index.py", l
ine 112, in fetch_index
        repodatas = collect_all_repodata(use_cache, tasks)
      File "C:\Program Files\Anaconda3\lib\site-packages\conda\core\repodata.py"
, line 74, in collect_all_repodata
        repodatas = _collect_repodatas_serial(use_cache, tasks)
      File "C:\Program Files\Anaconda3\lib\site-packages\conda\core\repodata.py"
, line 481, in _collect_repodatas_serial
        for url, schan, pri in tasks]
      File "C:\Program Files\Anaconda3\lib\site-packages\conda\core\repodata.py"
, line 481, in <listcomp>
        for url, schan, pri in tasks]
      File "C:\Program Files\Anaconda3\lib\site-packages\conda\core\repodata.py"
, line 109, in func
        res = f(*args, **kwargs)
      File "C:\Program Files\Anaconda3\lib\site-packages\conda\core\repodata.py"
, line 460, in fetch_repodata
        mod_etag_headers.get('_mod'))
      File "C:\Program Files\Anaconda3\lib\site-packages\conda\core\repodata.py"
, line 314, in fetch_repodata_remote_request
        e.response)
    conda.exceptions.CondaHTTPError: HTTP None None for url <https://repo.contin
uum.io/pkgs/free/win-64/repodata.json.bz2>
    Elapsed: None

    An HTTP error occurred when trying to retrieve this URL.
    HTTP errors are often intermittent, and a simple retry will get you on your
way.
    SSLError(SSLError(SSLError("bad handshake: Error([('SSL routines', 'ssl3_get
_server_certificate', 'certificate verify failed')],)",),),)
```
Conda Info:
```
C:\Users\DKHautamak>conda info
Current conda install:

               platform : win-64
          conda version : 4.3.18
       conda is private : False
      conda-env version : 4.3.18
    conda-build version : not installed
         python version : 3.6.0.final.0
       requests version : 2.14.2
       root environment : C:\Program Files\Anaconda3  (read only)
    default environment : C:\Program Files\Anaconda3
       envs directories : C:\Users\DKHautamak\AppData\Local\conda\conda\envs
                          C:\Program Files\Anaconda3\envs
                          C:\Users\DKHautamak\.conda\envs
          package cache : C:\Program Files\Anaconda3\pkgs
                          C:\Users\DKHautamak\AppData\Local\conda\conda\pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/win-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
            config file : C:\Users\DKHautamak\.condarc
           offline mode : False
             user-agent : conda/4.3.18 requests/2.14.2 CPython/3.6.0 Windows/7 W
indows/6.1.7601
          administrator : unknown
```
Conda config --show
```
C:\Users\DKHautamak>conda config --show
add_anaconda_token: True
add_pip_as_python_dependency: True
allow_non_channel_urls: True
allow_softlinks: True
always_copy: False
always_softlink: False
always_yes: False
anaconda_upload: None
auto_update_conda: True
changeps1: True
channel_alias: https://conda.anaconda.org
channel_priority: True
channels:
  - defaults
client_ssl_cert: None
client_ssl_cert_key: None
clobber: False
create_default_packages: []
custom_channels:
  pkgs/free: https://repo.continuum.io/
  pkgs/r: https://repo.continuum.io/
  pkgs/pro: https://repo.continuum.io/
  pkgs/msys2: https://repo.continuum.io/
custom_multichannels:
  defaults: ["https://repo.continuum.io/pkgs/free", "https://repo.continuum.io/p
kgs/r", "https://repo.continuum.io/pkgs/pro", "https://repo.continuum.io/pkgs/ms
ys2"]
  local: []
default_channels:
  - https://repo.continuum.io/pkgs/free
  - https://repo.continuum.io/pkgs/r
  - https://repo.continuum.io/pkgs/pro
  - https://repo.continuum.io/pkgs/msys2
disallow: []
envs_dirs:
  - C:\Users\DKHautamak\AppData\Local\conda\conda\envs
  - C:\Program Files\Anaconda3\envs
  - C:\Users\DKHautamak\.conda\envs
force: False
json: False
local_repodata_ttl: 1
migrated_channel_aliases: []
offline: False
path_conflict: clobber
pinned_packages: []
pkgs_dirs:
  - C:\Program Files\Anaconda3\pkgs
  - C:\Users\DKHautamak\AppData\Local\conda\conda\pkgs
proxy_servers: {}
quiet: False
remote_connect_timeout_secs: 9.15
remote_max_retries: 3
remote_read_timeout_secs: 60.0
rollback_enabled: True
shortcuts: True
show_channel_urls: None
ssl_verify: True
track_features: []
use_pip: True
verbosity: 0
```
Conda config --show-sources is blank

**Comment by nehaljwani** [comment]
After turning off ssl_verify, try the following:
```bash
conda update conda requests cryptography pyopenssl openssl
```
Then turn it back on and report if the issue persists?

**Comment by dkhungry** [comment]
Yes the issue still persists - I've done this step once already but checked again to make sure.  Here are the versions of the packages:
```
C:\Users\DKHautamak>conda config --set ssl_verify false

C:\Users\DKHautamak>conda update requests cryptography pyopenssl openssl
Fetching package metadata ...........
Solving package specifications: .

# All requested packages already installed.
# packages in environment at C:\Program Files\Anaconda3:
#
cryptography              1.8.1                    py36_0
openssl                   1.0.2k                   vc14_0  [vc14]
pyopenssl                 17.0.0                   py36_0
requests                  2.14.2                   py36_0
```

**Comment by nehaljwani** [comment]
@dkhungry Could you please share the output for the following commands (in the root environment):

```bash
where openssl
openssl s_client -connect repo.continuum.io:443
```

Also, could you please check if the conda package `certifi` is installed? If yes, could you please share it's version, update it and then check if it resolves your issue?

**Comment by dkhungry** [comment]
Trying to run where openssl yields:
```
C:\Windows\system32>where openssl
INFO: Could not find files for the given pattern(s).
```



Certifi was not installed.  I installed it and the version is.

```
C:\Windows\system32>conda update certifi
Fetching package metadata .............
Solving package specifications: .

# All requested packages already installed.
# packages in environment at C:\Users\DKHautamak\AppData\Local\Continuum\Anacond
a3:
#
certifi                   2016.2.28                py36_0
```

The error still persist, but I'm guessing it has something to do with being unable to find openssl with the first command.

**Comment by nehaljwani** [comment]
@dkhungry Did you try `where openssl` *after* activating the conda environment?

**Comment by dkhungry** [comment]
I've attempted this after activating the root environment and the same error happens where it can't find openssl.  Should I be trying in a separate environment from root?

**Comment by nehaljwani** [comment]
@dkhungry Oh, my bad, the windows build of openssl doesn't provide that binary.

**Comment by WillieMaddox** [comment]
a year later...

I've been using Anaconda3 on Win10 for about 6 months now with no problems up until yesterday. 
 This post is the discusses the exact issue I am having.  So I repeated all the steps outlined above, except now openssl is recognized in anaconda, but the config file points to a linux path. 

```shell
(base) C:\Windows>where openssl
C:\ProgramData\Anaconda3\openssl.exe

(base) C:\Windows>openssl s_client -connect repo.contimuum.io:443
WARNING: can't open config file: /usr/local/ssl/openssl.cnf
gethostbyname failure
connect:errno=11001
```

Does anyone have suggestions?

I'll report back if I find a solution unless someone beats me to it.

**Comment by Mutisk** [comment]
> (base) C:\Windows>openssl s_client -connect repo.contimuum.io:443
misspelled domain --> gethostbyname failure

**Comment by mlambi** [comment]
Many years later, mine just failed.  I don't know if I used pandas to download stuff last year, but I know I was pulling data for stuff in python datascience unit in class.  So, I know I was able to get tables from wikipedia, etc.  Decided to practice some python before school starts, and boom; cert issues.  I let everything update after my 2 month hiatus from conda, but man, this stinks.

I need conda for school next year, and I can't figure out what went wrong or how to fix it.
