### ISSUE TITLE
Failed to start  the R kernel, jupyter looking in the wrong directory

### ISSUE THREAD

**Issue by matrs** [ContinuumIO/anaconda-issues#1759]
` user-agent : conda/4.3.18 requests/2.14.2 CPython/3.6.1 Linux/4.10.13-1-ARCH arch/ glibc/2.25    
`

I cannot start R notebooks. Python 2, 3, Octave, SQL notebooks work fine. R works fine too, it's just the notebook that doesn't work.

I installed R using `conda install -c r r-essentials`
All continuum packages are installed in `/mnt/OPT/anaconda3`

 I don't have R installed from my distribution, only from Continuum

```
$which R
/mnt/OPT/anaconda3/bin/R
```
**Error message:**
```
Traceback (most recent call last):
  File "/mnt/OPT/anaconda3/lib/python3.6/site-packages/notebook/base/handlers.py", line 516, in wrapper
    result = yield gen.maybe_future(method(self, *args, **kwargs))
  File "/mnt/OPT/anaconda3/lib/python3.6/site-packages/tornado/gen.py", line 1055, in run
    value = future.result()
  File "/mnt/OPT/anaconda3/lib/python3.6/site-packages/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
  File "/mnt/OPT/anaconda3/lib/python3.6/site-packages/tornado/gen.py", line 1063, in run
    yielded = self.gen.throw(*exc_info)
  File "/mnt/OPT/anaconda3/lib/python3.6/site-packages/notebook/services/sessions/handlers.py", line 75, in post
    type=mtype))
  File "/mnt/OPT/anaconda3/lib/python3.6/site-packages/tornado/gen.py", line 1055, in run
    value = future.result()
  File "/mnt/OPT/anaconda3/lib/python3.6/site-packages/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
  File "/mnt/OPT/anaconda3/lib/python3.6/site-packages/tornado/gen.py", line 1063, in run
    yielded = self.gen.throw(*exc_info)
  File "/mnt/OPT/anaconda3/lib/python3.6/site-packages/notebook/services/sessions/sessionmanager.py", line 79, in create_session
    kernel_id = yield self.start_kernel_for_session(session_id, path, name, type, kernel_name)
  File "/mnt/OPT/anaconda3/lib/python3.6/site-packages/tornado/gen.py", line 1055, in run
    value = future.result()
  File "/mnt/OPT/anaconda3/lib/python3.6/site-packages/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
  File "/mnt/OPT/anaconda3/lib/python3.6/site-packages/tornado/gen.py", line 1063, in run
    yielded = self.gen.throw(*exc_info)
  File "/mnt/OPT/anaconda3/lib/python3.6/site-packages/notebook/services/sessions/sessionmanager.py", line 92, in start_kernel_for_session
    self.kernel_manager.start_kernel(path=kernel_path, kernel_name=kernel_name)
  File "/mnt/OPT/anaconda3/lib/python3.6/site-packages/tornado/gen.py", line 1055, in run
    value = future.result()
  File "/mnt/OPT/anaconda3/lib/python3.6/site-packages/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
  File "/mnt/OPT/anaconda3/lib/python3.6/site-packages/tornado/gen.py", line 307, in wrapper
    yielded = next(result)
  File "/mnt/OPT/anaconda3/lib/python3.6/site-packages/notebook/services/kernels/kernelmanager.py", line 94, in start_kernel
    super(MappingKernelManager, self).start_kernel(**kwargs)
  File "/mnt/OPT/anaconda3/lib/python3.6/site-packages/jupyter_client/multikernelmanager.py", line 110, in start_kernel
    km.start_kernel(**kwargs)
  File "/mnt/OPT/anaconda3/lib/python3.6/site-packages/jupyter_client/manager.py", line 257, in start_kernel
    **kw)
  File "/mnt/OPT/anaconda3/lib/python3.6/site-packages/jupyter_client/manager.py", line 203, in _launch_kernel
    return launch_kernel(kernel_cmd, **kw)
  File "/mnt/OPT/anaconda3/lib/python3.6/site-packages/jupyter_client/launcher.py", line 128, in launch_kernel
    proc = Popen(cmd, **kwargs)
  File "/mnt/OPT/anaconda3/lib/python3.6/subprocess.py", line 707, in __init__
    restore_signals, start_new_session)
  File "/mnt/OPT/anaconda3/lib/python3.6/subprocess.py", line 1326, in _execute_child
    raise child_exception_type(errno_num, err_msg)
FileNotFoundError: [Errno 2] No such file or directory: '/usr/lib64/R/bin/R'

```

So why (continuum) python is looking into `'/usr/lib64/R/bin/R'` ?
 
I tried removing/installing  the notebook but nothing changed

**Comment by matrs** [comment]
I fixed it cleaning everything from my system, it had some remnants (".config_files")  and reinstalling anaconda
