### ISSUE TITLE
conda commands failing after OSX update

### ISSUE THREAD

**Issue by andyxerxes** [ContinuumIO/anaconda-issues#1769]
After a recent update to OSX 10.12.5, I had two problems. The first was Jupyter notebook not launching properly, but this got (temporarily) solved, as described here https://groups.google.com/a/continuum.io/forum/#!topic/anaconda/2ixBaRD90Jk

However, I also have an issue with conda commands. Doing anything like "conda info" or "conda update conda"  etc gives the following return:

~> conda info
Traceback (most recent call last):
  File "/Users/axl/anaconda/bin/conda", line 6, in <module>
    sys.exit(conda.cli.main())
  File "/Users/axl/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 161, in main
    from ..exceptions import conda_exception_handler
  File "/Users/axl/anaconda/lib/python2.7/site-packages/conda/exceptions.py", line 11, in <module>
    from ._vendor.auxlib.entity import EntityEncoder
  File "/Users/axl/anaconda/lib/python2.7/site-packages/conda/_vendor/auxlib/__init__.py", line 27, in <module>
    from .logz import getLogger, NullHandler
  File "/Users/axl/anaconda/lib/python2.7/site-packages/conda/_vendor/auxlib/logz.py", line 8, in <module>
    from .compat import text_type
  File "/Users/axl/anaconda/lib/python2.7/site-packages/conda/_vendor/auxlib/compat.py", line 7, in <module>
    from ._vendor.five import WhateverIO as StringIO, with_metaclass
  File "/Users/axl/anaconda/lib/python2.7/site-packages/conda/_vendor/auxlib/_vendor/five.py", line 80, in <module>
    absolute_to_nanoseconds = CoreServices.AbsoluteToNanoseconds
  File "/Users/axl/anaconda/lib/python2.7/ctypes/__init__.py", line 375, in __getattr__
    func = self.__getitem__(name)
  File "/Users/axl/anaconda/lib/python2.7/ctypes/__init__.py", line 380, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: dlsym(RTLD_DEFAULT, AbsoluteToNanoseconds): symbol not found

I tried some fixes as suggested by Ian Stokes Rees at the above posting, but they all did the same thing.

**Comment by kalefranz** [comment]
This issue was moved to conda/conda#5439
