### ISSUE TITLE
Not Able to Launch Anaconda (Mac) HELP

### ISSUE THREAD

**Issue by ameliawilson** [ContinuumIO/anaconda-issues#1774]
My mac is Version 10.10.5

I previously had Anaconda with Python 2.7
I tried to uninstall it and install the graphical installer with Python 3.6
After I did this I could not open anaconda. It says initializing then quits. I have tried several times to uninstall and reinstall the graphical installers and they nothing works. It is the same issue as described

From other forums I see it might be the path, but I do not know what to do/how to change it.

**Comment by lpeterson02** [comment]
I have the same issue. I ran into this back in February as well and just uninstalled thinking I must have done something wrong. I tried again today using the graphical installer and ran into the same issue.

**Comment by lpeterson02** [comment]
NVM this fixed it https://github.com/ContinuumIO/anaconda-issues/issues/1585

**Comment by ameliawilson** [comment]
@goanpeca @lpeterson02 this did not fix it for mine :/
I have tried to follow the steps in many of these forums and the results are different. 

$  anaconda-navigator
-bash: anaconda-navigator: command not found
Amelias-MacBook-Air:~ ameliawilson$ sudo rm -rf /Users/ameliawilson/.continuum
Amelias-MacBook-Air:~ ameliawilson$ anaconda-navigator
-bash: anaconda-navigator: command not found

**Comment by RufusVS** [comment]
Similar here, here's my traceback:

Ryans-MacBook-Pro:~ rufussmith$ anaconda-navigator
Traceback (most recent call last):
  File "/Users/rufussmith/anaconda/bin/anaconda-navigator", line 6, in <module>
    sys.exit(anaconda_navigator.app.main.main())
  File "/Users/rufussmith/anaconda/lib/python2.7/site-packages/anaconda_navigator/app/main.py", line 52, in main
    start_app(options)
  File "/Users/rufussmith/anaconda/lib/python2.7/site-packages/anaconda_navigator/app/start.py", line 87, in start_app
    window = run_app(splash)
  File "/Users/rufussmith/anaconda/lib/python2.7/site-packages/anaconda_navigator/app/start.py", line 42, in run_app
    window = MainWindow(splash=splash)
  File "/Users/rufussmith/anaconda/lib/python2.7/site-packages/anaconda_navigator/widgets/main_window.py", line 162, in __init__
    self.api = AnacondaAPI()
  File "/Users/rufussmith/anaconda/lib/python2.7/site-packages/anaconda_navigator/api/anaconda_api.py", line 718, in AnacondaAPI
    ANACONDA_API = _AnacondaAPI()
  File "/Users/rufussmith/anaconda/lib/python2.7/site-packages/anaconda_navigator/api/anaconda_api.py", line 50, in __init__
    self._conda_api = CondaAPI()
  File "/Users/rufussmith/anaconda/lib/python2.7/site-packages/anaconda_navigator/api/conda_api.py", line 1302, in CondaAPI
    CONDA_API = _CondaAPI()
  File "/Users/rufussmith/anaconda/lib/python2.7/site-packages/anaconda_navigator/api/conda_api.py", line 307, in __init__
    self.set_root_prefix()
  File "/Users/rufussmith/anaconda/lib/python2.7/site-packages/anaconda_navigator/api/conda_api.py", line 427, in set_root_prefix
    self.ROOT_PREFIX = info['root_prefix']
TypeError: string indices must be integers, not str
Ryans-MacBook-Pro:~ rufussmith$
