### ISSUE TITLE
Navigator won't launch

### ISSUE THREAD

**Issue by djaychela** [ContinuumIO/anaconda-issues#1807]
Fresh install of Anaconda on a fresh install (VM) of Ubuntu 16.04 LTS, 64-bit.

`Traceback (most recent call last):
  File "/home/darren/anaconda2/lib/python2.7/site-packages/anaconda_navigator/exceptions.py", line 75, in exception_handler
    return_value = func(*args, **kwargs)
  File "/home/darren/anaconda2/lib/python2.7/site-packages/anaconda_navigator/app/start.py", line 115, in start_app
    window = run_app(splash)
  File "/home/darren/anaconda2/lib/python2.7/site-packages/anaconda_navigator/app/start.py", line 58, in run_app
    window = MainWindow(splash=splash)
  File "/home/darren/anaconda2/lib/python2.7/site-packages/anaconda_navigator/widgets/main_window.py", line 160, in __init__
    self.api = AnacondaAPI()
  File "/home/darren/anaconda2/lib/python2.7/site-packages/anaconda_navigator/api/anaconda_api.py", line 1205, in AnacondaAPI
    ANACONDA_API = _AnacondaAPI()
  File "/home/darren/anaconda2/lib/python2.7/site-packages/anaconda_navigator/api/anaconda_api.py", line 65, in __init__
    self._conda_api = CondaAPI()
  File "/home/darren/anaconda2/lib/python2.7/site-packages/anaconda_navigator/api/conda_api.py", line 1622, in CondaAPI
    CONDA_API = _CondaAPI()
  File "/home/darren/anaconda2/lib/python2.7/site-packages/anaconda_navigator/api/conda_api.py", line 340, in __init__
    self.set_conda_prefix()
  File "/home/darren/anaconda2/lib/python2.7/site-packages/anaconda_navigator/api/conda_api.py", line 489, in set_conda_prefix
    self.ROOT_PREFIX = info['root_prefix']
TypeError: string indices must be integers, not str`

**Comment by goanpeca** [comment]
@djaychela looks like conda is not on your bath, you need to add it on your bashrc file
