### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by faisalahmed0086** [ContinuumIO/anaconda-issues#1867]
## Main error
An unexpected error occurred on Navigator start-up<br>psutil.AccessDenied (pid=2868)
## Traceback
```
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\psutil\_pswindows.py", line 620, in wrapper
    return fun(self, *args, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\psutil\_pswindows.py", line 690, in cmdline
    ret = cext.proc_cmdline(self.pid)
PermissionError: [WinError 5] Access is denied

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\anaconda_navigator\exceptions.py", line 75, in exception_handler
    return_value = func(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 108, in start_app
    if misc.load_pid() is None:  # A stale lock might be around
  File "C:\ProgramData\Anaconda3\lib\site-packages\anaconda_navigator\utils\misc.py", line 384, in load_pid
    cmds = process.cmdline()
  File "C:\ProgramData\Anaconda3\lib\site-packages\psutil\__init__.py", line 701, in cmdline
    return self._proc.cmdline()
  File "C:\ProgramData\Anaconda3\lib\site-packages\psutil\_pswindows.py", line 623, in wrapper
    raise AccessDenied(self.pid, self._name)
psutil.AccessDenied: psutil.AccessDenied (pid=2868)

```
## System information
```
python: 3.6.1
language: en_US
os: Windows;7;6.1.7601;AMD64;Intel64 Family 6 Model 23 Stepping 10, GenuineIntel
version: 1.6.2
platform: win-32
qt: 5.6.2
pyqt: 5.6.0
conda: 4.3.21
```

**Comment by goanpeca** [comment]
I **strongly** recommend you install Anaconda for the current user only. If you used for all users and mix starting navigator with sudo and without sudo you will run into permission errors.
