### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by drxsc** [ContinuumIO/anaconda-issues#1884]
## Main error
Application <b>orange3</b> launch may have produced errors.
## Traceback
```
C:\Users\\Anaconda3\lib\site-packages\orangecontrib\spark\widgets\data\spark_to_orange.py:3: RuntimeWarning: Loaded module AnyQt._backport as a substitute for PyQt4
  from PyQt4.QtGui import QSizePolicy
C:\Users\\Anaconda3\lib\site-packages\orangecontrib\spark\widgets\data\spark_to_orange.py:3: RuntimeWarning: Loaded module AnyQt._backport.QtGui as a substitute for PyQt4.QtGui
  from PyQt4.QtGui import QSizePolicy
C:\Users\\Anaconda3\lib\site-packages\orangecontrib\spark\widgets\ml\spark_ml_dataset.py:9: RuntimeWarning: Loaded module AnyQt._backport.QtCore as a substitute for PyQt4.QtCore
  from PyQt4.QtCore import Qt
C:\Users\\Anaconda3\lib\site-packages\gensim\utils.py:860: UserWarning: detected Windows; aliasing chunkize to chunkize_serial
  warnings.warn("detected Windows; aliasing chunkize to chunkize_serial")
Slow version of gensim.models.doc2vec is being used
C:\Users\\Anaconda3\lib\site-packages\statsmodels\compat\pandas.py:56: FutureWarning: The pandas.core.datetools module is deprecated and will be removed in a future version. Please use the pandas.tseries module instead.
  from pandas.core import datetools
Error parsing
Traceback (most recent call last):
  File "C:\Users\\Anaconda3\lib\site-packages\Orange\canvas\help\provider.py", line 195, in _load_inventory
    self.items = self._parse(stream.read().decode("utf-8"))
  File "C:\Users\\Anaconda3\lib\site-packages\Orange\canvas\help\provider.py", line 207, in _parse
    for el in self.root.findall(path):
AttributeError: 'NoneType' object has no attribute 'fi

**Comment by stefanseefeld** [comment]
The above traceback appears incomplete. Please provide a complete one so we can attempt to help.

**Comment by goanpeca** [comment]
Closing due to lack of response
