### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by slipa** [ContinuumIO/anaconda-issues#1901]
## Main error
Application <b>spyder</b> launch may have produced errors.
## Traceback
```
Traceback (most recent call last):
  File "/home/samuel/anaconda2/lib/python2.7/site-packages/spyder/app/mainwindow.py", line 3011, in main
    mainwindow = run_spyder(app, options, args)
  File "/home/samuel/anaconda2/lib/python2.7/site-packages/spyder/app/mainwindow.py", line 2913, in run_spyder
    main.setup()
  File "/home/samuel/anaconda2/lib/python2.7/site-packages/spyder/app/mainwindow.py", line 860, in setup
    from spyder.plugins.externalconsole import ExternalConsole
  File "/home/samuel/anaconda2/lib/python2.7/site-packages/spyder/plugins/externalconsole.py", line 39, in <module>
    from spyder.widgets.externalshell.pythonshell import ExternalPythonShell
  File "/home/samuel/anaconda2/lib/python2.7/site-packages/spyder/widgets/externalshell/pythonshell.py", line 34, in <module>
    from spyder.widgets.variableexplorer.namespacebrowser import NamespaceBrowser
  File "/home/samuel/anaconda2/lib/python2.7/site-packages/spyder/widgets/variableexplorer/namespacebrowser.py", line 26, in <module>
    import ipykernel.pickleutil
  File "/home/samuel/anaconda2/lib/python2.7/site-packages/ipykernel/__init__.py", line 2, in <module>
    from .connect import *
  File "/home/samuel/anaconda2/lib/python2.7/site-packages/ipykernel/connect.py", line 18, in <module>
    import jupyter_client
  File "/home/samuel/anaconda2/lib/python2.7/site-packages/jupyter_client/__init__.py", line 7, in <module>
    from .manager import KernelManager, run_kernel
  File "/home/samuel/anaconda2/lib/python2.7/site-packages/jupyter_client/manager.py", line 32, in <module>
    from .session import Session
  File "/home/samuel/anaconda2/lib/python2.7/site-packages/jupyter_client/session.py", line 61, in <module>
    from jupyter_client.jsonutil import extract_dates, squash_dates, date_default
  File "/home/samuel/anaconda2/lib/python2.7/site-packages/jupyter_client/jsonutil.py", line 28, in <module>
    datetime.strptime("1", "%d")
  File "/home/samuel/anaconda2/lib/python2.7/_strptime.py", line 274, in <module>
    _TimeRE_cache = TimeRE()
  File "/home/samuel/anaconda2/lib/python2.7/_strptime.py", line 192, in __init__
    self.locale_time = LocaleTime()
  File "/home/samuel/anaconda2/lib/python2.7/_strptime.py", line 70, in __init__
    self.lang = _getlang()
  File "/home/samuel/anaconda2/lib/python2.7/_strptime.py", line 29, in _getlang
    return locale.getlocale(locale.LC_TIME)
  File "/home/samuel/anaconda2/lib/python2.7/locale.py", line 564, in getlocale
    return _parse_localename(localename)
  File "/home/samuel/anaconda2/lib/python2.7/locale.py", line 477, in _parse_localename
    raise ValueError, 'unknown locale: %s' % localename
ValueError: unknown locale: lzh_TW

```
## System information
```
platform: linux-64
version: 1.6.2
conda: 4.3.21
qt: 5.6.2
language: en_US
python: 2.7.13
os: Linux;4.8.0-53-generic;#56~16.04.1-Ubuntu SMP Tue May 16 01:18:56 UTC 2017;x86_64;x86_64
pyqt: 5.6.0
```

**Comment by goanpeca** [comment]
@slipa it seems you have your locale set incorrectly. It should be `zh_TW` not `lzh_TW`
