### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by sjakhar** [ContinuumIO/anaconda-issues#1902]
## Main error
Application <b>notebook</b> launch may have produced errors.
## Traceback
```
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\Scripts\jupyter-notebook-script.py", line 3, in <module>
    import notebook.notebookapp
  File "C:\ProgramData\Anaconda3\lib\site-packages\notebook\notebookapp.py", line 55, in <module>
    from tornado import httpserver
  File "C:\ProgramData\Anaconda3\lib\site-packages\tornado\httpserver.py", line 34, in <module>
    from tornado.http1connection import HTTP1ServerConnection, HTTP1ConnectionParameters
  File "C:\ProgramData\Anaconda3\lib\site-packages\tornado\http1connection.py", line 30, in <module>
    from tornado import iostream
  File "C:\ProgramData\Anaconda3\lib\site-packages\tornado\iostream.py", line 40, in <module>
    from tornado.netutil import ssl_wrap_socket, ssl_match_hostname, SSLCertificateError, _client_ssl_defaults, _server_ssl_defaults
  File "C:\ProgramData\Anaconda3\lib\site-packages\tornado\netutil.py", line 39, in <module>
    import certifi
ImportError: No module named certifi

```
## System information
```
platform: win-64
version: 1.6.2
conda: 4.2.13
qt: 5.6.2
language: en_GB
python: 2.7.8
os: Windows;8;6.2.9200;AMD64;Intel64 Family 6 Model 69 Stepping 1, GenuineIntel
pyqt: 5.6.0
```

**Comment by nehaljwani** [comment]
Does `conda install certifi` fix this for you?

**Comment by goanpeca** [comment]
Closing due to lack of response

**Comment by sjakhar** [comment]
I apologise for not responding on this issue. And yes `conda install certifi` fixed it for me.
