### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by 1123avb** [ContinuumIO/anaconda-issues#1915]
Hello.
I am trying to install an anaconda for python 3.6 version, for Windows 7, 32-bit system and here is what I get after my attempt to start spyder 3.1.4:

## Main error
Application <b>spyder</b> launch may have produced errors.
## Traceback
```
Traceback (most recent call last):
  File "C:\Users\Anaconda3\lib\asyncio\__init__.py", line 16, in <module>
    from . import _overlapped
ImportError: cannot import name '_overlapped'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 3011, in main
    mainwindow = run_spyder(app, options, args)
  File "C:\Users\Anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 2913, in run_spyder
    main.setup()
  File "C:\Users\Anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 784, in setup
    from spyder.plugins.help import Help
  File "C:\Users\Anaconda3\lib\site-packages\spyder\plugins\help.py", line 33, in <module>
    from spyder.utils.help.sphinxify import (CSS_PATH, generate_context,
  File "C:\Users\Anaconda3\lib\site-packages\spyder\utils\help\sphinxify.py", line 30, in <module>
    from jinja2 import Environment, FileSystemLoader
  File "C:\Users\Anaconda3\lib\site-packages\jinja2\__init__.py", line 81, in <module>
    _patch_async()
  File "C:\Users\Anaconda3\lib\site-packages\jinja2\__init__.py", line 77, in _patch_async
    from jinja2.asyncsupport import patch_all
  File "C:\Users\Anaconda3\lib\site-packages\jinja2\asyncsupport.py", line 13, in <module>
    import asyncio
  File "C:\Users\Anaconda3\lib\asyncio\__init__.py", line 18, in <module>
    import _

How can I solve such problem???

**Comment by goanpeca** [comment]
@ccordoba12  ?

**Comment by goanpeca** [comment]
IGNORE THIS

**Comment by zmhhmz** [comment]
still no answer?
