### ISSUE TITLE
binstar misses clyent

### ISSUE THREAD

**Issue by pitrou** [ContinuumIO/anaconda-issues#196]
I installed binstar using conda but I get the following error:

```
Z:\bst>binstar
Traceback (most recent call last):
  File "C:\Miniconda3-64\Scripts\binstar-script.py", line 3, in <module>
    from binstar_client.scripts.cli import main
  File "C:\Miniconda3-64\lib\site-packages\binstar_client\__init__.py", line 8,
in <module>
    from .errors import BinstarError, Conflict, NotFound, Unauthorized
  File "C:\Miniconda3-64\lib\site-packages\binstar_client\errors.py", line 1, in
 <module>
    from clyent.errors import ClyentError
ImportError: No module named 'clyent'
```

**Comment by nehaljwani** [comment]
The `'binstar'` conda package has been renamed to `'anaconda-client'`. And it has the conda package `clyent` listed as it's dependency.

```cmd
anaconda-client 1.6.3 py36_0
----------------------------
file name   : anaconda-client-1.6.3-py36_0.tar.bz2
name        : anaconda-client
version     : 1.6.3
build number: 0
channel     : defaults
size        : 183 KB
arch        : x86_64
date        : 2017-04-25
license     : BSD
md5         : 1bddf4b02f73bcd1eb9d9a52a4df2e79
noarch      : None
platform    : win32
url         : https://repo.continuum.io/pkgs/free/win-64/anaconda-client-1.6.3-py36_0.tar.bz2
dependencies:
    clyent
    python 3.6*
    python-dateutil
    pytz
    pyyaml
    requests >=2.9.1
    setuptools
```
