### ISSUE TITLE
UnicodeError when launching ipython on windows with non-ascii letter in HOMEPATH

### ISSUE THREAD

**Issue by skjaeve** [ContinuumIO/anaconda-issues#198]
When I launch IPython in a console window I get an unicode error. I expect it's due to a non-ascii letter in my homepath. This is a fresh Anaconda install. Plain python works fine. This happens on Windows 7.

I can't do anything in IPython. Running a script or importing a module fails with a repeat of the error message.

```
C:\Users\Åsmund>ipython
Python 2.7.8 |Anaconda 2.1.0 (64-bit)| (default, Jul  2 2014, 15:12:11) [MSC v.1500 64 bit (AMD64)]
Type "copyright", "credits" or "license" for more information.

IPython 2.2.0 -- An enhanced Interactive Python.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://binstar.org
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.
c:\Anaconda\lib\site-packages\IPython\core\ultratb.py:267: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
  if rname == '<ipython console>' or rname.endswith('<string>'):
ERROR: Internal Python error in the inspect module.
Below is the traceback from this internal error.

Traceback (most recent call last):
  File "c:\Anaconda\lib\site-packages\IPython\core\ultratb.py", line 776, in structured_traceback
    records = _fixed_getinnerframes(etb, context, tb_offset)
  File "c:\Anaconda\lib\site-packages\IPython\core\ultratb.py", line 230, in wrapped
    return f(*args, **kwargs)
  File "c:\Anaconda\lib\site-packages\IPython\core\ultratb.py", line 267, in _fixed_getinnerframes
    if rname == '<ipython console>' or rname.endswith('<string>'):
UnicodeDecodeError: 'ascii' codec can't decode byte 0x8f in position 9: ordinal not in range(128)

Unfortunately, your original traceback can not be constructed.



In [1]:
```

**Comment by pbethke** [comment]
I have an updated anaconda on win 7 as well, after an update of anaconda this bug showed up. im not at my work pc, but can provide version numbers if that is helpful. i know that ipython is 2.3.1
