### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by iop956** [ContinuumIO/anaconda-issues#1984]
## Main error
An unexpected error occurred on Navigator start-up<br>psutil.AccessDenied (pid=607)
## Traceback
```
Traceback (most recent call last):
  File "/Users/deanimal77/anaconda/lib/python3.6/site-packages/psutil/_psosx.py", line 293, in wrapper
    return fun(self, *args, **kwargs)
  File "/Users/deanimal77/anaconda/lib/python3.6/site-packages/psutil/_psosx.py", line 356, in cmdline
    return cext.proc_cmdline(self.pid)
PermissionError: [Errno 13] Permission denied

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/deanimal77/anaconda/lib/python3.6/site-packages/anaconda_navigator/exceptions.py", line 75, in exception_handler
    return_value = func(*args, **kwargs)
  File "/Users/deanimal77/anaconda/lib/python3.6/site-packages/anaconda_navigator/app/start.py", line 108, in start_app
    if misc.load_pid() is None:  # A stale lock might be around
  File "/Users/deanimal77/anaconda/lib/python3.6/site-packages/anaconda_navigator/utils/misc.py", line 384, in load_pid
    cmds = process.cmdline()
  File "/Users/deanimal77/anaconda/lib/python3.6/site-packages/psutil/__init__.py", line 701, in cmdline
    return self._proc.cmdline()
  File "/Users/deanimal77/anaconda/lib/python3.6/site-packages/psutil/_psosx.py", line 306, in wrapper
    raise AccessDenied(self.pid, self._name)
psutil.AccessDenied: psutil.AccessDenied (pid=607)

```
## System information
```
python: 3.6.1
language: en
os: Darwin;16.6.0;Darwin Kernel Version 16.6.0: Fri Apr 14 16:21:16 PDT 2017; root:xnu-3789.60.24~6/RELEASE_X86_64;x86_64;i386
version: 1.6.2
platform: osx-64
qt: 5.6.2
pyqt: 5.6.0
conda: 4.3.21
```

**Comment by goanpeca** [comment]
@iop956 please run 

`$ anaconda-navigator --reset`

Did you try to run Navigator with sudo, and then without sude?

**Comment by iop956** [comment]
Thanks, issue resolved.
--------------------------------------------
On Thu, 6/8/17, Gonzalo Peña-Castellanos <notifications@github.com> wrote:

 Subject: Re: [ContinuumIO/anaconda-issues] Navigator Error (#1984)
 To: "ContinuumIO/anaconda-issues" <anaconda-issues@noreply.github.com>
 Cc: "iop956" <iop956@yahoo.com>, "Mention" <mention@noreply.github.com>
 Date: Thursday, June 8, 2017, 3:57 PM
 
 @iop956 please run
 $ anaconda-navigator --reset
 Did you try to run Navigator with sudo, and then without
 sude?
 
 —
 You are
 receiving this because you were mentioned.
 Reply to
 this email directly, view
 it on GitHub, or mute
 the thread.

**Comment by PinkZhi** [comment]
I just restarting machine and resolve this problem.

**Comment by rod14298** [comment]
Thanks man! very helpfull!

**Comment by swainnirbikar** [comment]
unable to open it

**Comment by swainnirbikar** [comment]
done thank you so much @goanpeca

**Comment by koevje** [comment]
$ conda update anaconda-navigator didn't work out for me, in which interface do i have to run the code? 

I'am unable to run anaconda navigator.

**Comment by kingtigran** [comment]
It worked for me. Thank you so much!

**Comment by crsarav** [comment]
Thanks, it worked.

**Comment by thermike2** [comment]
I am on win10 and the command  anaconda-navigator --reset did the job! Thank you!

**Comment by RaouiaHAMZA** [comment]
Thanks ! 
It worked !

**Comment by saif8091** [comment]
Updated the navigator, conda and everything else but its still not working.

**Comment by vinayak19th** [comment]
Nothing is working, checked most of the linked thread already

**Comment by CarlRugfelt** [comment]
I get this error message
Traceback (most recent call last):
File "/anaconda3/lib/python3.6/site-packages/psutil/_psosx.py", line 348, in catch_zombie
yield
File "/anaconda3/lib/python3.6/site-packages/psutil/_psosx.py", line 412, in cmdline
return cext.proc_cmdline(self.pid)
ProcessLookupError: [Errno 3] No such process

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/anaconda3/lib/python3.6/site-packages/anaconda_navigator/exceptions.py", line 75, in exception_handler
return_value = func(*args, **kwargs)
File "/anaconda3/lib/python3.6/site-packages/anaconda_navigator/app/start.py", line 113, in start_app
if misc.load_pid() is None: # A stale lock might be around
File "/anaconda3/lib/python3.6/site-packages/anaconda_navigator/utils/misc.py", line 384, in load_pid
cmds = process.cmdline()
File "/anaconda3/lib/python3.6/site-packages/psutil/__init__.py", line 666, in cmdline
return self._proc.cmdline()
File "/anaconda3/lib/python3.6/site-packages/psutil/_psosx.py", line 330, in wrapper
return fun(self, *args, **kwargs)
File "/anaconda3/lib/python3.6/site-packages/psutil/_psosx.py", line 412, in cmdline
return cext.proc_cmdline(self.pid)
File "/anaconda3/lib/python3.6/contextlib.py", line 99, in __exit__
self.gen.throw(type, value, traceback)
File "/anaconda3/lib/python3.6/site-packages/psutil/_psosx.py", line 361, in catch_zombie
raise AccessDenied(proc.pid, proc._name)
psutil._exceptions.AccessDenied: psutil.AccessDenied (pid=694)

I have tried updating in terminal (Mac OS) via $conda update but I do not get it to work. Where do I go wrong?

**Comment by goanpeca** [comment]
You can run on the Terminal or Anaconda prompt:

```
anaconda-navigator --reset
```

**Comment by AssenD** [comment]
same here :(
(windows 7 64 PRO)
problem closed, but not solved as it seems
after updating - installed apps reduced to only three (J Notebook, Spyder and VScode), all others were gone

**Comment by skykryst** [comment]
I got this error. Apparently PySide module not found. Please help.


(base) C:\WINDOWS\system32>conda update conda
Solving environment: done

# All requested packages already installed.


(base) C:\WINDOWS\system32>conda update anaconda-navigator
Solving environment: done

# All requested packages already installed.


(base) C:\WINDOWS\system32>anaconda-navigator --reset
Traceback (most recent call last):
  File "C:\Users\Aakash Meshram\AppData\Roaming\Python\Python37\site-packages\qtpy\__init__.py", line 199, in <module>
    from PySide import __version__ as PYSIDE_VERSION  # analysis:ignore
ModuleNotFoundError: No module named 'PySide'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Anaconda3\Scripts\anaconda-navigator-script.py", line 6, in <module>
    from anaconda_navigator.app.main import main
  File "C:\Anaconda3\lib\site-packages\anaconda_navigator\app\main.py", line 22, in <module>
    from anaconda_navigator.utils.conda import is_conda_available
  File "C:\Anaconda3\lib\site-packages\anaconda_navigator\utils\__init__.py", line 15, in <module>
    from qtpy.QtGui import QIcon
  File "C:\Users\Aakash Meshram\AppData\Roaming\Python\Python37\site-packages\qtpy\__init__.py", line 205, in <module>
    raise PythonQtError('No Qt bindings could be found')
qtpy.PythonQtError: No Qt bindings could be found

(base) C:\WINDOWS\system32>anaconda-navigator
Traceback (most recent call last):
  File "C:\Users\Aakash Meshram\AppData\Roaming\Python\Python37\site-packages\qtpy\__init__.py", line 199, in <module>
    from PySide import __version__ as PYSIDE_VERSION  # analysis:ignore
ModuleNotFoundError: No module named 'PySide'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Anaconda3\Scripts\anaconda-navigator-script.py", line 6, in <module>
    from anaconda_navigator.app.main import main
  File "C:\Anaconda3\lib\site-packages\anaconda_navigator\app\main.py", line 22, in <module>
    from anaconda_navigator.utils.conda import is_conda_available
  File "C:\Anaconda3\lib\site-packages\anaconda_navigator\utils\__init__.py", line 15, in <module>
    from qtpy.QtGui import QIcon
  File "C:\Users\Aakash Meshram\AppData\Roaming\Python\Python37\site-packages\qtpy\__init__.py", line 205, in <module>
    raise PythonQtError('No Qt bindings could be found')
qtpy.PythonQtError: No Qt bindings could be found
