### ISSUE TITLE
Navigator Error - Application spyder launch may have produced errors

### ISSUE THREAD

**Issue by mriener** [ContinuumIO/anaconda-issues#1987]
## Main error
Application <b>spyder</b> launch may have produced errors.
## Traceback
```
Traceback (most recent call last):
  File "/Users/riener/anaconda/lib/python3.5/site-packages/qtpy/QtWebEngineWidgets.py", line 22, in <module>
    from PyQt5.QtWebEngineWidgets import QWebEnginePage
ImportError: dlopen(/Users/riener/anaconda/lib/python3.5/site-packages/PyQt5/QtWebEngineWidgets.so, 2): Library not loaded: @rpath/libQt5WebEngineCore.5.dylib
  Referenced from: /Users/riener/anaconda/lib/python3.5/site-packages/PyQt5/QtWebEngineWidgets.so
  Reason: image not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/riener/anaconda/bin/spyder", line 6, in <module>
    sys.exit(spyder.app.start.main())
  File "/Users/riener/anaconda/lib/python3.5/site-packages/spyder/app/start.py", line 103, in main
    from spyder.app import mainwindow
  File "/Users/riener/anaconda/lib/python3.5/site-packages/spyder/app/mainwindow.py", line 92, in <module>
    from qtpy import QtWebEngineWidgets  # analysis:ignore
  File "/Users/riener/anaconda/lib/python3.5/site-packages/qtpy/QtWebEngineWidgets.py", line 26, in <module>
    from PyQt5.QtWebKitWidgets import QWebPage as QWebEnginePage
ImportError: No module named 'PyQt5.QtWebKitWidgets'

```
## System information
```
python: 3.5.1
conda: 4.3.21
pyqt: 5.6.0
version: 1.6.2
os: Darwin;15.6.0;Darwin Kernel Version 15.6.0: Tue Apr 11 16:00:51 PDT 2017; root:xnu-3248.60.11.5.3~1/RELEASE_X86_64;x86_64;i386
language: en
platform: osx-64
qt: 5.6.2
```

**Comment by goanpeca** [comment]
IGNORE THIS

**Comment by goanpeca** [comment]
@ccordoba12 ?

**Comment by ccordoba12** [comment]
Did you install pyqt5 using pip by any chance?
