### ISSUE TITLE
Navigator won't start after anaconda update

### ISSUE THREAD

**Issue by uenz** [ContinuumIO/anaconda-issues#2005]
Hi,
im running Anaconda on macOS 10.12.5. I did a update with 
`conda update --all python=2.7` which succeeded well under my windows 7 installation.
Now launching of Navigator.app on macOS results in
## Error
`LSOpenURLsWithRole() failed with error -10810 for the file /Applications/navigator.app
`
## System information
Current conda install:

               platform : osx-64
          conda version : 4.3.21
       conda is private : False
      conda-env version : 4.3.21
    conda-build version : 2.1.15
         python version : 2.7.13.final.0
       requests version : 2.14.2

**Comment by goanpeca** [comment]
@uenz what happens if you try to run from the terminal

```
$ /Users/<my-username>/anaconda/Anaconda-Navigator.app/Contents/MacOS/run.sh
```

?

**Comment by uenz** [comment]
On my installation the path is
´$ /Users/<my-username>/anaconda/Navigator.app/Contents/MacOS/run.sh´
and returns
´Traceback (most recent call last):
  File "/Users/asr/anaconda/bin/anaconda-navigator", line 4, in <module>
    import anaconda_navigator.app.main
  File "/Users/asr/anaconda/lib/python2.7/site-packages/anaconda_navigator/app/main.py", line 21, in <module>
    from anaconda_navigator.widgets.dialogs.splash import SplashScreen
  File "/Users/asr/anaconda/lib/python2.7/site-packages/anaconda_navigator/widgets/__init__.py", line 18, in <module>
    from anaconda_navigator.utils.analytics import GATracker
  File "/Users/asr/anaconda/lib/python2.7/site-packages/anaconda_navigator/utils/analytics.py", line 33, in <module>
    from qtpy.QtCore import QT_VERSION_STR, QObject, QThread, QTimer, Signal
ImportError: cannot import name QT_VERSION_STR´

**Comment by goanpeca** [comment]
@uenz try doing

```
$ conda install qt=5 -f
$ conda install pyqt=5 -f
$ conda install qtpy -f
$ conda install anaconda-navigator=1.6.3 -f
```

**Comment by uenz** [comment]
orange seems to cause the issue
```
conda install qt=5 -f
```
```
UnsatisfiableError: The following specifications were found to be in conflict:
  - orange -> pyqt 4.* -> qt >=4.8.6,<5.0
  - qt 5*
```
```
conda install pyqt=5 -f
```
``` - orange -> pyqt 4.* -> qt >=4.8.6,<5.0
  - orange -> pyqt 4.* -> sip >=4.16.4,<4.18
  - pyqt 5* -> qt 5.6*
```
Uninstalled orange and tied again.
Now it updated and the navigator works.

**Comment by goanpeca** [comment]
@uenz you can use orange3 which works with Qt5

**Comment by cswor** [comment]
What does that fix look like for Win10? I'm currently dead on this root prefix error. Anaconda won't start.
