### ISSUE TITLE
spyder missing jinja2 as runtime dep

### ISSUE THREAD

**Issue by tacaswell** [ContinuumIO/anaconda-issues#201]
```
tcaswell@tcaswellpc1:~$ conda create -n spyder_bare spyder
Fetching package metadata: ....
Solving package specifications: .
Package plan for installation in environment /home/tcaswell/.pe/spyder_bare:

The following NEW packages will be INSTALLED:

    docutils:  0.12-py27_0  
    ipython:   2.3.0-py27_0 
    libsodium: 0.4.5-0      
    openssl:   1.0.1h-1     
    pygments:  1.6-py27_0   
    pyqt:      4.10.4-py27_0
    python:    2.7.8-1      
    pyzmq:     14.4.1-py27_0
    qt:        4.8.5-0      
    readline:  6.2-2        
    sip:       4.15.5-py27_0
    spyder:    2.3.1-py27_1 
    sqlite:    3.8.4.1-0    
    system:    5.8-1        
    tk:        8.5.15-0     
    zeromq:    4.0.4-0      
    zlib:      1.2.7-0      

Proceed ([y]/n)? y

Linking packages ...
[      COMPLETE      ] |#########################################################################################################################| 100%
#
# To activate this environment, use:
# $ source activate spyder_bare
#
# To deactivate this environment, use:
# $ source deactivate
#
tcaswell@tcaswellpc1:~$ source activate spyder_bare
discarding /home/tcaswell/mc/bin from PATH
prepending /home/tcaswell/.pe/spyder_bare/bin to PATH
(spyder_bare)tcaswell@tcaswellpc1:~$ spyder
Traceback (most recent call last):
  File "/home/tcaswell/.pe/spyder_bare/lib/python2.7/site-packages/spyderlib/spyder.py", line 2346, in main
    mainwindow = run_spyder(app, options, args)
  File "/home/tcaswell/.pe/spyder_bare/lib/python2.7/site-packages/spyderlib/spyder.py", line 2234, in run_spyder
    main.setup()
  File "/home/tcaswell/.pe/spyder_bare/lib/python2.7/site-packages/spyderlib/spyder.py", line 791, in setup
    from spyderlib.plugins.inspector import ObjectInspector
  File "/home/tcaswell/.pe/spyder_bare/lib/python2.7/site-packages/spyderlib/plugins/inspector.py", line 48, in <module>
    from spyderlib.utils.inspector.sphinxify import (CSS_PATH, sphinxify,
  File "/home/tcaswell/.pe/spyder_bare/lib/python2.7/site-packages/spyderlib/utils/inspector/sphinxify.py", line 29, in <module>
    from jinja2 import Environment, FileSystemLoader
ImportError: No module named jinja2

```

**Comment by ilanschnell** [comment]
Thanks for the error report.  I've added this dependency, so whenever we update spyder it will be included.
