### ISSUE TITLE
Starting Orange3 - Navigator Error

### ISSUE THREAD

**Issue by demianvk** [ContinuumIO/anaconda-issues#2012]
I added geoPandas via Conda which had quite a few dependencies that needed to be installed/updated included a version of PyQT.  
## Main error
Application <b>orange3</b> launch may have produced errors.
## Traceback
```
D:\Users\DemianVK\AppData\Local\Continuum\Anaconda3\lib\site-packages\orangecontrib\spark\widgets\data\spark_to_orange.py:3: RuntimeWarning: Loaded module AnyQt._backport as a substitute for PyQt4
  from PyQt4.QtGui import QSizePolicy
D:\Users\DemianVK\AppData\Local\Continuum\Anaconda3\lib\site-packages\orangecontrib\spark\widgets\data\spark_to_orange.py:3: RuntimeWarning: Loaded module AnyQt._backport.QtGui as a substitute for PyQt4.QtGui
  from PyQt4.QtGui import QSizePolicy
D:\Users\DemianVK\AppData\Local\Continuum\Anaconda3\lib\site-packages\orangecontrib\spark\widgets\ml\spark_ml_dataset.py:9: RuntimeWarning: Loaded module AnyQt._backport.QtCore as a substitute for PyQt4.QtCore
  from PyQt4.QtCore import Qt
D:\Users\DemianVK\AppData\Local\Continuum\Anaconda3\lib\site-packages\gensim\utils.py:860: UserWarning: detected Windows; aliasing chunkize to chunkize_serial
  warnings.warn("detected Windows; aliasing chunkize to chunkize_serial")
Slow version of gensim.models.doc2vec is being used
An error occurred while fetching help inventory 'PyQt5.QtCore.QUrl('http://example.com/my-widget/docs/')'
Error parsing
Traceback (most recent call last):
  File "D:\Users\DemianVK\AppData\Local\Continuum\Anaconda3\lib\site-packages\Orange\canvas\help\provider.py", line 195, in _load_inventory
    self.items = self._parse(stream.read().decode("utf-8"))
  File "D:\Users\DemianVK\AppData\Local\Continuum\Anaconda3\lib\site-packages\Orange\canvas\help\provider.py", line 207, in _parse
    for el in self.root.findall(path):
AttributeError: '

**Comment by stefanseefeld** [comment]
The above traceback appears incomplete. Please provide a complete traceback.

**Comment by goanpeca** [comment]
Closing due to lack of response
