### ISSUE TITLE
Navigator Application Error/Warning: Spyder

### ISSUE THREAD

**Issue by thms317** [ContinuumIO/anaconda-issues#2017]
## Main error
Application <b>spyder</b> launch may have produced errors.
## Traceback
```
Traceback (most recent call last):
  File "C:\Users\brouw\Anaconda3\Scripts\spyder-script.py", line 3, in <module>
    import spyder.app.start
  File "C:\Users\brouw\Anaconda3\lib\site-packages\spyder\app\start.py", line 13, in <module>
    from spyder.config.base import get_conf_path, running_in_mac_app
  File "C:\Users\brouw\Anaconda3\lib\site-packages\spyder\config\base.py", line 365, in <module>
    _ = get_translation("spyder")
  File "C:\Users\brouw\Anaconda3\lib\site-packages\spyder\config\base.py", line 345, in get_translation
    _trans = gettext.translation(modname, locale_path, codeset="utf-8")
  File "C:\Users\brouw\Anaconda3\lib\gettext.py", line 505, in translation
    mofiles = find(domain, localedir, languages, all=True)
  File "C:\Users\brouw\Anaconda3\lib\gettext.py", line 489, in find
    if os.path.exists(mofile):
  File "C:\Users\brouw\Anaconda3\lib\genericpath.py", line 19, in exists
    os.stat(path)
ValueError: stat: embedded null character in path

```
## System information
```
python: 3.6.1
language: nl_NL
os: Windows;10;10.0.15063;AMD64;Intel64 Family 6 Model 94 Stepping 3, GenuineIntel
version: 1.6.2
platform: win-64
qt: 5.6.2
pyqt: 5.6.0
conda: 4.3.21
```

Furthermore, this error also happens when I update to most recent Spyder. I tried to roll back a version, but to no avail.

**Comment by goanpeca** [comment]
@ccordoba12 ?

**Comment by ccordoba12** [comment]
No idea, sorry.

**Comment by thms317** [comment]
Dudes, thank you for the help. I managed to resolve this issue by uninstalling anaconda and manually deleting anything spyder-related after which i reinstalled and it worked. Silly error.

**Comment by t5k6** [comment]
Deleting the ".spyder-py3" folder under users directory (on Windows) solved the issue for me.

**Comment by thms317** [comment]
yes, that did the trick!
