### ISSUE TITLE
Navigator backtrace index error on Ubuntu 17.04

### ISSUE THREAD

**Issue by teledyn** [ContinuumIO/anaconda-issues#2026]
Following instructions from the Udemy course on machine learning, using Ubuntu 17.04, I ran the installer script as sudo to install into /opt/anaconda2, which succeeds however ... launching the Navigator fails with the following backtrace:

garym@garym-hp:~$ /opt/anaconda2/bin/anaconda-navigator 
An unexpected error occurred on Navigator start-up<br>string indices must be integers, not str
Traceback (most recent call last):
  File "/opt/anaconda2/lib/python2.7/site-packages/anaconda_navigator/exceptions.py", line 75, in exception_handler
    return_value = func(*args, **kwargs)
  File "/opt/anaconda2/lib/python2.7/site-packages/anaconda_navigator/app/start.py", line 115, in start_app
    window = run_app(splash)
  File "/opt/anaconda2/lib/python2.7/site-packages/anaconda_navigator/app/start.py", line 58, in run_app
    window = MainWindow(splash=splash)
  File "/opt/anaconda2/lib/python2.7/site-packages/anaconda_navigator/widgets/main_window.py", line 160, in __init__
    self.api = AnacondaAPI()
  File "/opt/anaconda2/lib/python2.7/site-packages/anaconda_navigator/api/anaconda_api.py", line 1205, in AnacondaAPI
    ANACONDA_API = _AnacondaAPI()
  File "/opt/anaconda2/lib/python2.7/site-packages/anaconda_navigator/api/anaconda_api.py", line 65, in __init__
    self._conda_api = CondaAPI()
  File "/opt/anaconda2/lib/python2.7/site-packages/anaconda_navigator/api/conda_api.py", line 1622, in CondaAPI
    CONDA_API = _CondaAPI()
  File "/opt/anaconda2/lib/python2.7/site-packages/anaconda_navigator/api/conda_api.py", line 340, in __init__
    self.set_conda_prefix()
  File "/opt/anaconda2/lib/python2.7/site-packages/anaconda_navigator/api/conda_api.py", line 489, in set_conda_prefix
    self.ROOT_PREFIX = info['root_prefix']
TypeError: string indices must be integers, not str

**Comment by teledyn** [comment]
Turns out this is an artifact of the /opt/anaconda2/bin not being at the top of the $PATH
