### ISSUE TITLE
Navigator: after attempting to install NumbaPro/Accelerate

### ISSUE THREAD

**Issue by nikilp** [ContinuumIO/anaconda-issues#2038]
The last modification I did, I believe, was my attempt to install NumbaPro/Accelerate on the root environment with python 3, and the requirement for python 2 produced error.

I can launch some of my other environments, but my attempt to launch the root env spider leads to:

## Main error
Application <b>spyder</b> launch may have produced errors.
## Traceback
```
Traceback (most recent call last):
  File "E:\DataScience\Anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 2999, in main
    mainwindow = run_spyder(app, options, args)
  File "E:\DataScience\Anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 2901, in run_spyder
    main.setup()
  File "E:\DataScience\Anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 784, in setup
    from spyder.plugins.help import Help
  File "E:\DataScience\Anaconda3\lib\site-packages\spyder\plugins\help.py", line 33, in <module>
    from spyder.utils.help.sphinxify import (CSS_PATH, generate_context,
  File "E:\DataScience\Anaconda3\lib\site-packages\spyder\utils\help\sphinxify.py", line 30, in <module>
    from jinja2 import Environment, FileSystemLoader
  File "E:\DataScience\Anaconda3\lib\site-packages\jinja2\__init__.py", line 33, in <module>
    from jinja2.environment import Environment, Template
  File "E:\DataScience\Anaconda3\lib\site-packages\jinja2\environment.py", line 15, in <module>
    from jinja2 import nodes
  File "E:\DataScience\Anaconda3\lib\site-packages\jinja2\nodes.py", line 19, in <module>
    from jinja2.utils import Markup
  File "E:\DataScience\Anaconda3\lib\site-packages\jinja2\utils.py", line 624, in <module>
    from markupsafe import Markup, escape, soft_unicode
  File "E:\DataScience\Anaconda3\lib\site-packages\markupsafe\__init__.py", line 14, in <module>
    from markupsafe._compat import text_type, string_types, int_types, \
ModuleNotFoundError:  No module named 'markupsafe._compat'

**Comment by goanpeca** [comment]
@ccordoba12 ?
