### ISSUE TITLE
Navigator Application Error: Spyder

### ISSUE THREAD

**Issue by MikaCC** [ContinuumIO/anaconda-issues#2046]
## Main error
Application <b>spyder</b> launch may have produced errors.
## Traceback
```
Traceback (most recent call last):
  File "/Users/sicongchen/anaconda/lib/python3.5/site-packages/qtpy/QtWebEngineWidgets.py", line 22, in <module>
    from PyQt5.QtWebEngineWidgets import QWebEnginePage
ImportError: dlopen(/Users/sicongchen/anaconda/lib/python3.5/site-packages/PyQt5/QtWebEngineWidgets.so, 2): Library not loaded: @rpath/libQt5WebEngineCore.5.dylib
  Referenced from: /Users/sicongchen/anaconda/lib/python3.5/site-packages/PyQt5/QtWebEngineWidgets.so
  Reason: image not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/sicongchen/anaconda/bin/spyder", line 6, in <module>
    sys.exit(spyder.app.start.main())
  File "/Users/sicongchen/anaconda/lib/python3.5/site-packages/spyder/app/start.py", line 103, in main
    from spyder.app import mainwindow
  File "/Users/sicongchen/anaconda/lib/python3.5/site-packages/spyder/app/mainwindow.py", line 92, in <module>
    from qtpy import QtWebEngineWidgets  # analysis:ignore
  File "/Users/sicongchen/anaconda/lib/python3.5/site-packages/qtpy/QtWebEngineWidgets.py", line 26, in <module>
    from PyQt5.QtWebKitWidgets import QWebPage as QWebEnginePage
ImportError: No module named 'PyQt5.QtWebKitWidgets'

```
## System information
```
pyqt: 5.6.0
platform: osx-64
language: en
qt: 5.6.2
version: 1.6.2
os: Darwin;16.5.0;Darwin Kernel Version 16.5.0: Fri Mar  3 16:52:33 PST 2017; root:xnu-3789.51.2~3/RELEASE_X86_64;x86_64;i386
python: 3.5.3
conda: 4.3.21
```

**Comment by goanpeca** [comment]
@ccordoba12 ?
