### ISSUE TITLE
ImportError: DLL load failed: %1 is not a valid Win32 application.

### ISSUE THREAD

**Issue by laylasun** [ContinuumIO/anaconda-issues#2099]
## Main error
Application <b>notebook</b> launch may have produced errors.
## Traceback
```
Traceback (most recent call last):
  File "C:\Users\laylasun\Anaconda2\Scripts\jupyter-notebook-script.py", line 3, in <module>
    import notebook.notebookapp
  File "C:\Users\laylasun\AppData\Roaming\Python\Python27\site-packages\notebook\notebookapp.py", line 39, in <module>
    from zmq.eventloop import ioloop
  File "C:\Users\laylasun\AppData\Roaming\Python\Python27\site-packages\zmq\__init__.py", line 34, in <module>
    from zmq import backend
  File "C:\Users\laylasun\AppData\Roaming\Python\Python27\site-packages\zmq\backend\__init__.py", line 40, in <module>
    reraise(*exc_info)
  File "C:\Users\laylasun\AppData\Roaming\Python\Python27\site-packages\zmq\backend\__init__.py", line 27, in <module>
    _ns = select_backend(first)
  File "C:\Users\laylasun\AppData\Roaming\Python\Python27\site-packages\zmq\backend\select.py", line 26, in select_backend
    mod = __import__(name, fromlist=public_api)
  File "C:\Users\laylasun\AppData\Roaming\Python\Python27\site-packages\zmq\backend\cython\__init__.py", line 6, in <module>
    from . import (constants, error, message, context,
ImportError: DLL load failed: %1 is not a valid Win32 application.

```
## System information
```
platform: win-64
version: 1.6.2
conda: 4.3.21
qt: 5.6.2
language: en_US
python: 2.7.13
os: Windows;10;10.0.14393;AMD64;Intel64 Family 6 Model 78 Stepping 3, GenuineIntel
pyqt: 5.6.0
```
But both Anaconda and Python27 are installed for Win64

**Comment by kelseykruse** [comment]
I'm having this same issue. Have you been able to figure anything out?

**Comment by rickiricki** [comment]
i have same issue but not in anaconda but straight after python 2.7 + pip install jupyter  installation

**Comment by kkirasich** [comment]
I had the same thing.  I saw that in the error the package zmq was the issue so I ran the following:
python -m pip install --upgrade zmq

After that it worked for me.
