### ISSUE TITLE
Maximum call stack size exceeded

### ISSUE THREAD

**Issue by guocheng** [ContinuumIO/anaconda-issues#212]
On the launcher window, I clicked on the 1.0.0 (after the Manage Channels label) and I got the following error and the launcher crashed.

Here is the app info:

Anaconda Launcher Info
Version: 1.0.0 (node-webkit 0.10.1)

Conda Version: 3.7.3

Root Prefix: /Users/cheng/anaconda

Default Prefix: /Users/cheng/anaconda

Python Version: 2.7.8.final.0

Platform: osx-64

-------------------------------------------

RangeError: Maximum call stack size exceeded
    at String.replace (native)
    at Function.st (file:///Users/cheng/anaconda/node-webkit/launcher/static/vendor/jquery/1.9.1/jquery.min.js:4:6145)
    at HTMLDocument.b.event.handlers (file:///Users/cheng/anaconda/node-webkit/launcher/static/vendor/jquery/1.9.1/jquery.min.js:3:28790)
    at HTMLDocument.b.event.dispatch (file:///Users/cheng/anaconda/node-webkit/launcher/static/vendor/jquery/1.9.1/jquery.min.js:3:28046)
    at HTMLDocument.v.handle (file:///Users/cheng/anaconda/node-webkit/launcher/static/vendor/jquery/1.9.1/jquery.min.js:3:25049)
    at Object.b.event.trigger (file:///Users/cheng/anaconda/node-webkit/launcher/static/vendor/jquery/1.9.1/jquery.min.js:3:27423)
    at HTMLDivElement.<anonymous> (file:///Users/cheng/anaconda/node-webkit/launcher/static/vendor/jquery/1.9.1/jquery.min.js:4:3107)
    at Function.b.extend.each (file:///Users/cheng/anaconda/node-webkit/launcher/static/vendor/jquery/1.9.1/jquery.min.js:3:5257)
    at b.fn.b.each (file:///Users/cheng/anaconda/node-webkit/launcher/static/vendor/jquery/1.9.1/jquery.min.js:3:2013)
    at b.fn.extend.trigger (file:///Users/cheng/anaconda/node-webkit/launcher/static/vendor/jquery/1.9.1/jquery.min.js:4:3083)

**Comment by tswicegood** [comment]
Hi @guocheng, I'm doing a pass through the GitHub issues.  Just wondering if this is still an issue for you?

**Comment by guocheng** [comment]
Nope, thanks for asking.

**Comment by tswicegood** [comment]
Excellent.  Guess it got fixed and nobody marked this off.  Closing it out but feel free to re-open if it crops back up.
