### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by msinvent** [ContinuumIO/anaconda-issues#2131]
Trying to launch spyder using anaconda navigator but getting the following error.

## Main error
Application <b>spyder</b> launch may have produced errors.
## Traceback
```
Traceback (most recent call last):
  File "/home/yogi/anaconda3/bin/spyder", line 6, in <module>
    sys.exit(spyder.app.start.main())
  File "/home/yogi/anaconda3/lib/python3.6/site-packages/spyder/app/start.py", line 103, in main
    from spyder.app import mainwindow
  File "/home/yogi/anaconda3/lib/python3.6/site-packages/spyder/app/mainwindow.py", line 165, in <module>
    from spyder.utils.environ import WinUserEnvDialog
  File "/home/yogi/anaconda3/lib/python3.6/site-packages/spyder/utils/environ.py", line 20, in <module>
    from spyder.widgets.variableexplorer.collectionseditor import CollectionsEditor
  File "/home/yogi/anaconda3/lib/python3.6/site-packages/spyder/widgets/variableexplorer/collectionseditor.py", line 46, in <module>
    from spyder.widgets.variableexplorer.importwizard import ImportWizard
  File "/home/yogi/anaconda3/lib/python3.6/site-packages/spyder/widgets/variableexplorer/importwizard.py", line 26, in <module>
    import pandas as pd
  File "/home/yogi/anaconda3/lib/python3.6/site-packages/pandas/__init__.py", line 23, in <module>
    from pandas.compat.numpy import *
  File "/home/yogi/anaconda3/lib/python3.6/site-packages/pandas/compat/__init__.py", line 361, in <module>
    from dateutil import parser as _date_parser
  File "/home/yogi/anaconda3/lib/python3.6/site-packages/dateutil/parser.py", line 158
    l.append("%s=%s" % (attr, `value`))
                              ^
SyntaxError: invalid syntax

```
## System information
```
python: 3.6.1
language: en_US
os: Linux;4.8.0-54-generic;#57~16.04.1-Ubuntu SMP Wed May 24 16:22:28 UTC 2017;x86_64;x86_64
version: 1.6.2
platform: linux-64
qt: 5.6.2
pyqt: 5.6.0
conda: 4.3.21
```

**Comment by goanpeca** [comment]
@ccordoba12 ?
