### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by pardha-fission** [ContinuumIO/anaconda-issues#2139]
## Main error
Application <b>orange3</b> launch may have produced errors.
## Traceback
```
/home/pardha/anaconda3/lib/python3.6/site-packages/Orange/canvas/scheme/readwrite.py:993: RuntimeWarning: Loaded module AnyQt._backport as a substitute for PyQt4
  return pickle.loads(base64.decodebytes(string.encode('ascii')))
/home/pardha/anaconda3/lib/python3.6/site-packages/Orange/canvas/scheme/readwrite.py:993: RuntimeWarning: Loaded module AnyQt._backport.QtCore as a substitute for PyQt4.QtCore
  return pickle.loads(base64.decodebytes(string.encode('ascii')))
Could not load properties for 'File'.
Traceback (most recent call last):
  File "/home/pardha/anaconda3/lib/python3.6/site-packages/Orange/canvas/scheme/readwrite.py", line 699, in scheme_load
    properties = loads(data.data, data.format)
  File "/home/pardha/anaconda3/lib/python3.6/site-packages/Orange/canvas/scheme/readwrite.py", line 993, in loads
    return pickle.loads(base64.decodebytes(string.encode('ascii')))
SystemError: unable to find to find module: PyQt4.QtCore
Could not load properties for 'File'.
Traceback (most recent call last):
  File "/home/pardha/anaconda3/lib/python3.6/site-packages/Orange/canvas/scheme/readwrite.py", line 699, in scheme_load
    properties = loads(data.data, data.format)
  File "/home/pardha/anaconda3/lib/python3.6/site-packages/Orange/canvas/scheme/readwrite.py", line 993, in loads
    return pickle.loads(base64.decodebytes(string.encode('ascii')))
SystemError: unable to find to find module: PyQt4.QtCore
Could not load properties for 'File'.
Traceback (most recent call last):
  File "/home/pardha/anaconda3/lib/python3.6/site-packages/Orange/canvas/scheme/readwrite.py", line 699, in scheme_load
    properties = loads(data.data, data.format)
  File "/home/pardha/anaconda3/lib/python3.6/site-packages/Orange/canvas/scheme/readwrite.py", line 993, in loads
    return pickle.loads(base64.decodebytes(string.encode('ascii')))
SystemError: unable to find to find module: PyQt4.QtCore
Could not load properties for 'Test & Score'.
Traceback (most recent call last):
  File "/home/pardha/anaconda3/lib/python3.6/site-packages/Orange/canvas/scheme/readwrite.py", line 699, in scheme_load
    properties = loads(data.data, data.format)
  File "/home/pardha/anaconda3/lib/python3.6/site-packages/Orange/canvas/scheme/readwrite.py", line 993, in loads
    return pickle.loads(base64.decodebytes(string.encode('ascii')))
SystemError: unable to find to find module: PyQt4.QtCore

```
## System information
```
python: 3.6.1
language: en_IN
os: Linux;4.8.0-54-generic;#57~16.04.1-Ubuntu SMP Wed May 24 16:22:28 UTC 2017;x86_64;x86_64
version: 1.6.2
platform: linux-64
qt: 5.6.2
pyqt: 5.6.0
conda: 4.3.21
```

**Comment by goanpeca** [comment]
Could you open a terminal and run from there to get the full error stack trace?
