### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by hanyingong** [ContinuumIO/anaconda-issues#2172]
## Main error
An unexpected error occurred on Navigator start-up<br>byte indices must be integers or slices, not str
## Traceback
```
Traceback (most recent call last):
  File "D:\Program Files\Anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 111, in start_app
    with lock.acquire(timeout=3.0):  # timeout in seconds
  File "D:\Program Files\Anaconda3\lib\site-packages\anaconda_navigator\external\filelock.py", line 254, in acquire
    raise Timeout(self._lock_file)
anaconda_navigator.external.filelock.Timeout: The file lock 'C:\Users\hanying.ong.2015\.anaconda\navigator\navigator.lock' could not be acquired.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Program Files\Anaconda3\lib\site-packages\anaconda_navigator\exceptions.py", line 75, in exception_handler
    return_value = func(*args, **kwargs)
  File "D:\Program Files\Anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 124, in start_app
    "There is an instance of "
  File "D:\Program Files\Anaconda3\lib\site-packages\anaconda_navigator\widgets\dialogs\__init__.py", line 450, in __init__
    type_=self.INFORMATION_BOX,
  File "D:\Program Files\Anaconda3\lib\site-packages\anaconda_navigator\widgets\dialogs\__init__.py", line 265, in __init__
    self.tracker = GATracker()
  File "D:\Program Files\Anaconda3\lib\site-packages\anaconda_navigator\utils\analytics.py", line 284, in GATracker
    GA_TRACKER = _GATracker()
  File "D:\Program Files\Anaconda3\lib\site-packages\anaconda_navigator\utils\analytics.py", line 95, in __init__
    self.api =

**Comment by goanpeca** [comment]
@hanyingong did you try to open 2 instances of navigator?

Try running on the terminal

```
$ anaconda-navigator --reset
```
