### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by JohnWmD** [ContinuumIO/anaconda-issues#2176]
## Main error
Application <b>spyder</b> launch may have produced errors.
## Traceback
```
Traceback (most recent call last):
  File "/anaconda/bin/spyder", line 6, in <module>
    sys.exit(spyder.app.start.main())
  File "/anaconda/lib/python3.6/site-packages/spyder/app/start.py", line 103, in main
    from spyder.app import mainwindow
  File "/anaconda/lib/python3.6/site-packages/spyder/app/mainwindow.py", line 165, in <module>
    from spyder.utils.environ import WinUserEnvDialog
  File "/anaconda/lib/python3.6/site-packages/spyder/utils/environ.py", line 20, in <module>
    from spyder.widgets.variableexplorer.collectionseditor import CollectionsEditor
  File "/anaconda/lib/python3.6/site-packages/spyder/widgets/variableexplorer/collectionseditor.py", line 46, in <module>
    from spyder.widgets.variableexplorer.importwizard import ImportWizard
  File "/anaconda/lib/python3.6/site-packages/spyder/widgets/variableexplorer/importwizard.py", line 26, in <module>
    import pandas as pd
  File "/anaconda/lib/python3.6/site-packages/pandas/__init__.py", line 23, in <module>
    from pandas.compat.numpy import *
  File "/anaconda/lib/python3.6/site-packages/pandas/compat/__init__.py", line 361, in <module>
    from dateutil import parser as _date_parser
  File "/anaconda/lib/python3.6/site-packages/dateutil/parser.py", line 158
    l.append("%s=%s" % (attr, `value`))
                              ^
SyntaxError: invalid syntax

```
## System information
```
python: 3.6.1
language: en
os: Darwin;16.6.0;Darwin Kernel Version 16.6.0: Fri Apr 14 16:21:16 PDT 2017; root:xnu-3789.60.24~6/RELEASE_X86_64;x86_64;i386
version: 1.6.2
platform: osx-64
qt: 5.6.2
pyqt: 5.6.0
conda: 4.3.21
```

**Comment by goanpeca** [comment]
@ccordoba12 ?
