### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by AishaFarsi** [ContinuumIO/anaconda-issues#2241]
## Main error
The following errors occurred:
## Traceback
```
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\conda\exceptions.py", line 632, in conda_exception_handler
    return_value = func(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\conda\cli\main.py", line 137, in _main
    exit_code = args.func(args, p)
  File "C:\ProgramData\Anaconda3\lib\site-packages\conda\cli\main_install.py", line 80, in execute
    install(args, parser, 'install')
  File "C:\ProgramData\Anaconda3\lib\site-packages\conda\cli\install.py", line 357, in install
    execute_actions(actions, index, verbose=not context.quiet)
  File "C:\ProgramData\Anaconda3\lib\site-packages\conda\plan.py", line 830, in execute_actions
    execute_instructions(plan, index, verbose)
  File "C:\ProgramData\Anaconda3\lib\site-packages\conda\instructions.py", line 247, in execute_instructions
    cmd(state, arg)
  File "C:\ProgramData\Anaconda3\lib\site-packages\conda\instructions.py", line 108, in UNLINKLINKTRANSACTION_CMD
    txn.execute()
  File "C:\ProgramData\Anaconda3\lib\site-packages\conda\core\link.py", line 263, in execute
    self.verify()
  File "C:\ProgramData\Anaconda3\lib\site-packages\conda\core\link.py", line 242, in verify
    self.prepare()
  File "C:\ProgramData\Anaconda3\lib\site-packages\conda\core\link.py", line 149, in prepare
    for pkg_info in self.packages_info_to_link)
  File "C:\ProgramData\Anaconda3\lib\site-packages\conda\core\link.py", line 149, in <genexpr>
    for pkg_info in self.packages_inf

**Comment by goanpeca** [comment]
@AishaFarsi I suggest you install anaconda for the current user and not all users.
