### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by Sindhujab** [ContinuumIO/anaconda-issues#2263]
## Main error
Application <b>spyder</b> launch may have produced errors.
## Traceback
```
Traceback (most recent call last):
  File "/Users/enixtainnovationspvtltd/anaconda/bin/spyder", line 3, in <module>
    start_app.main()
  File "/Users/enixtainnovationspvtltd/anaconda/lib/python2.7/site-packages/spyderlib/start_app.py", line 114, in main
    from spyderlib import spyder
  File "/Users/enixtainnovationspvtltd/anaconda/lib/python2.7/site-packages/spyderlib/spyder.py", line 77, in <module>
    requirements.check_qt()
  File "/Users/enixtainnovationspvtltd/anaconda/lib/python2.7/site-packages/spyderlib/requirements.py", line 50, in check_qt
    % (qt_infos['pyqt']+qt_infos['pyside']))
  File "/Users/enixtainnovationspvtltd/anaconda/lib/python2.7/site-packages/spyderlib/requirements.py", line 25, in show_warning
    raise RuntimeError(message)
RuntimeError: Please check Spyder installation requirements:
PyQt4 4.6+ (or PySide 1.2.0+) is required.

```
## System information
```
conda: 4.3.21
language: en
python: 3.5.3
pyqt: 5.6.0
version: 1.6.2
os: Darwin;14.5.0;Darwin Kernel Version 14.5.0: Thu Jun 16 19:58:21 PDT 2016; root:xnu-2782.50.4~1/RELEASE_X86_64;x86_64;i386
platform: osx-64
qt: 5.6.2
```

**Comment by goanpeca** [comment]
@Sindhujab it seems your system has both qt4 and qt5 (with conda) installed so your libraries are messed up :-|

Could you send the output of 

```
$ conda list
```

**Comment by goanpeca** [comment]
Closing due to lack of response
