### ISSUE TITLE
Spyder - Jinja2 dependency not installed?

### ISSUE THREAD

**Issue by goanpeca** [ContinuumIO/anaconda-issues#234]
@ccordoba12

When making a new environment and installing **spyder** on it:

After activating the environment and calling **spyder** from the command prompt, I get the following error trace, even though in the recipe [Jinja2 is listed as a dependency](https://github.com/conda/conda-recipes/blob/master/spyder/meta.yaml)

```
conda create --name p3 python=3.4 spyder
source activate p3
spyder

Traceback (most recent call last):
  File "/home/goanpeca/anaconda/envs/p3/lib/python3.4/site-packages/spyderlib/spyder.py", line 2354, in main
    mainwindow = run_spyder(app, options, args)
  File "/home/goanpeca/anaconda/envs/p3/lib/python3.4/site-packages/spyderlib/spyder.py", line 2242, in run_spyder
    main.setup()
  File "/home/goanpeca/anaconda/envs/p3/lib/python3.4/site-packages/spyderlib/spyder.py", line 793, in setup
    from spyderlib.plugins.inspector import ObjectInspector
  File "/home/goanpeca/anaconda/envs/p3/lib/python3.4/site-packages/spyderlib/plugins/inspector.py", line 48, in <module>
    from spyderlib.utils.inspector.sphinxify import (CSS_PATH, sphinxify,
  File "/home/goanpeca/anaconda/envs/p3/lib/python3.4/site-packages/spyderlib/utils/inspector/sphinxify.py", line 29, in <module>
    from jinja2 import Environment, FileSystemLoader
ImportError: No module named 'jinja2'
Segmentation fault (core dumped)
```
or
```
conda create --name p2 python=2.7 spyder
source activate p2
spyder

Traceback (most recent call last):
  File "/home/goanpeca/anaconda/envs/p2/lib/python2.7/site-packages/spyderlib/spyder.py", line 2354, in main
    mainwindow = run_spyder(app, options, args)
  File "/home/goanpeca/anaconda/envs/p2/lib/python2.7/site-packages/spyderlib/spyder.py", line 2242, in run_spyder
    main.setup()
  File "/home/goanpeca/anaconda/envs/p2/lib/python2.7/site-packages/spyderlib/spyder.py", line 793, in setup
    from spyderlib.plugins.inspector import ObjectInspector
  File "/home/goanpeca/anaconda/envs/p2/lib/python2.7/site-packages/spyderlib/plugins/inspector.py", line 48, in <module>
    from spyderlib.utils.inspector.sphinxify import (CSS_PATH, sphinxify,
  File "/home/goanpeca/anaconda/envs/p2/lib/python2.7/site-packages/spyderlib/utils/inspector/sphinxify.py", line 29, in <module>
    from jinja2 import Environment, FileSystemLoader
ImportError: No module named jinja2
Segmentation fault (core dumped)
```

By manually installing **jinja2** with **conda** it gets solved, but it is on the recipe so it should have been done since **spyder** was installed, no?

I have tested this on Ubuntu 14.04 so far

**Comment by ilanschnell** [comment]
Yes, the jinja2 dependency is missing currently from the sypder package.  You can manually install jinja2 by:
```
$ conda install --name p2 jinja2
```
The next time we create a spyder conda packages, this will be fixed.

**Comment by ccordoba12** [comment]
@ilanschnell that would be fixed when creating new environments too?

**Comment by ilanschnell** [comment]
Yes

**Comment by tswicegood** [comment]
FYI, I just got bit by this when creating a new environment.
