### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by cyslug** [ContinuumIO/anaconda-issues#2356]
## Main error
Application <b>spyder</b> launch may have produced errors.
## Traceback
```
Traceback (most recent call last):
  File "C:\Users\robi_\Anaconda2\lib\site-packages\spyder\app\mainwindow.py", line 3011, in main
    mainwindow = run_spyder(app, options, args)
  File "C:\Users\robi_\Anaconda2\lib\site-packages\spyder\app\mainwindow.py", line 2913, in run_spyder
    main.setup()
  File "C:\Users\robi_\Anaconda2\lib\site-packages\spyder\app\mainwindow.py", line 873, in setup
    from spyder.plugins.ipythonconsole import IPythonConsole
  File "C:\Users\robi_\Anaconda2\lib\site-packages\spyder\plugins\ipythonconsole.py", line 60, in <module>
    from spyder.widgets.ipythonconsole import ClientWidget
  File "C:\Users\robi_\Anaconda2\lib\site-packages\spyder\widgets\ipythonconsole\__init__.py", line 12, in <module>
    from .debugging import DebuggingWidget
  File "C:\Users\robi_\Anaconda2\lib\site-packages\spyder\widgets\ipythonconsole\debugging.py", line 16, in <module>
    from qtconsole.rich_jupyter_widget import RichJupyterWidget
  File "C:\Users\robi_\Anaconda2\lib\site-packages\qtconsole\rich_jupyter_widget.py", line 14, in <module>
    from .jupyter_widget import JupyterWidget
  File "C:\Users\robi_\Anaconda2\lib\site-packages\qtconsole\jupyter_widget.py", line 19, in <module>
    from IPython.lib.lexers import IPythonLexer, IPython3Lexer
  File "C:\Users\robi_\Anaconda2\lib\site-packages\IPython\__init__.py", line 48, in <module>
    from .core.application import Application
  File "C:\Users\robi_\Anaconda2\lib\site-packages\IPython\core\application.py", line 25, in <module>
    from IPython.core i

**Comment by ccordoba12** [comment]
There seems to missing content in your traceback. Please try to run

    conda install -f ipython

and try again.
