### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by 4bic** [ContinuumIO/anaconda-issues#2413]
## Main error
Application <b>anaconda-fusion</b> launch may have produced errors.
## Traceback
```
/Users/4bic/anaconda/lib/python3.6/site-packages/IPython/html.py:14: ShimWarning: The `IPython.html` package has been deprecated. You should import from `notebook` instead. `IPython.html.widgets` has moved to `ipywidgets`.
  "`IPython.html.widgets` has moved to `ipywidgets`.", ShimWarning)
Traceback (most recent call last):
  File "/Users/4bic/anaconda/bin/fusion", line 6, in <module>
    sys.exit(anacondafusion.__main__.fuse_all())
  File "/Users/4bic/anaconda/lib/python3.6/site-packages/anacondafusion/__main__.py", line 69, in fuse_all
    main()
  File "/Users/4bic/anaconda/lib/python3.6/site-packages/anacondafusion/__main__.py", line 42, in main
    serve(sys.argv)
  File "/Users/4bic/anaconda/lib/python3.6/site-packages/anacondafusion/server.py", line 514, in serve
    os.mkdir(dst)
FileNotFoundError: [Errno 2] No such file or directory: '/Users/4bic/Library/Containers/com.microsoft.Excel/Data/Documents/wef/'

```
## System information
```
python: 3.6.0
language: en
os: Darwin;16.6.0;Darwin Kernel Version 16.6.0: Fri Apr 14 16:21:16 PDT 2017; root:xnu-3789.60.24~6/RELEASE_X86_64;x86_64;i386
version: 1.6.2
platform: osx-64
qt: 5.6.2
pyqt: 5.6.0
conda: 4.3.21
```

**Comment by goanpeca** [comment]
Please update to the latest version of Navigator.

On Navigator click on the update button on the top right of the interface or
on the terminal type

```
$ conda update anaconda-navigator
```
