### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by hammer2505** [ContinuumIO/anaconda-issues#2418]
## Main error
An unexpected error occurred on Navigator start-up<br>'ascii' codec can't encode characters in position 21-22: ordinal not in range(128)
## Traceback
```
Traceback (most recent call last):
  File "/home/hammer/anaconda2/lib/python2.7/site-packages/anaconda_navigator/exceptions.py", line 75, in exception_handler
    return_value = func(*args, **kwargs)
  File "/home/hammer/anaconda2/lib/python2.7/site-packages/anaconda_navigator/app/start.py", line 115, in start_app
    window = run_app(splash)
  File "/home/hammer/anaconda2/lib/python2.7/site-packages/anaconda_navigator/app/start.py", line 58, in run_app
    window = MainWindow(splash=splash)
  File "/home/hammer/anaconda2/lib/python2.7/site-packages/anaconda_navigator/widgets/main_window.py", line 322, in __init__
    self.tab_projects = ProjectsTab(parent=self)
  File "/home/hammer/anaconda2/lib/python2.7/site-packages/anaconda_navigator/widgets/tabs/projects.py", line 77, in __init__
    self.widget = ProjectsWidget()
  File "/home/hammer/anaconda2/lib/python2.7/site-packages/anaconda_navigator/widgets/projects.py", line 212, in __init__
    self.file_explorer = ExplorerWidget()
  File "/home/hammer/anaconda2/lib/python2.7/site-packages/anaconda_navigator/widgets/explorer.py", line 1252, in __init__
    self.update_breadcrumb()
  File "/home/hammer/anaconda2/lib/python2.7/site-packages/anaconda_navigator/widgets/explorer.py", line 1267, in update_breadcrumb
    text += '<a href="{link}">{p}</a>'.format(p=p, link=cum_path)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 21-22: ordinal not in range(128)

```
## System information
```
platform: linux-64
version: 1.6.2
conda: 4.3.21
qt: 5.6.2
language: en_US
python: 2.7.13
os: Linux;4.4.0-79-generic;#100-Ubuntu SMP Wed May 17 19:58:14 UTC 2017;x86_64;x86_64
pyqt: 5.6.0
```

**Comment by goanpeca** [comment]
Please update to the latest version of Navigator.

On Navigator click on the update button on the top right of the interface or
on the terminal type

```
$ conda update anaconda-navigator
```
