### ISSUE TITLE
Cannot import rasterio on OS X 

### ISSUE THREAD

**Issue by ceball** [ContinuumIO/anaconda-issues#2428]
I did ``conda install rasterio``, but cannot import the resulting package.

Not sure if this is the same issue being discussed in #960 - sorry if this is a duplicate. 

```
$ python -c "import rasterio"
Traceback (most recent call last):
 File "<string>", line 1, in <module>
 File "/Users/cball/mc3/envs/dev_datashader/lib/python3.5/site-packages/rasterio/__init__.py", line 15, in <module>
   from rasterio._base import (
ImportError: dlopen(/Users/cball/mc3/envs/dev_datashader/lib/python3.5/site-packages/rasterio/_base.cpython-35m-darwin.so, 2): Library not loaded: @rpath/libjpeg.8.dylib
 Referenced from: /Users/cball/mc3/envs/dev_datashader/lib/libgdal.20.dylib
 Reason: image not found
```

In contrast, ``pip install rasterio`` seems to give me a working rasterio package.

## Details of what I did

I installed miniconda3, then did ``conda create --name dev_datashader``, followed by ``source activate dev_datashader``. (I installed some other packages at this point - hope that's not relevant.)

Then...

```
(dev_datashader)$ conda install rasterio
Fetching package metadata ...........
Solving package specifications: .

Package plan for installation in environment /Users/cball/mc3/envs/dev_datashader:

The following NEW packages will be INSTALLED:

    affine:        2.0.0-py35_0      
    click:         6.7-py35_0        
    click-plugins: 1.0.3-py35_0      
    cligj:         0.4.0-py35_0      
    curl:          7.49.0-1          
    geos:          3.5.0-0           
    geotiff:       1.4.1-0           
    hdf4:          4.2.12-1          
    hdf5:          1.8.17-1          
    kealib:        1.4.6-0           
    libgdal:       2.1.0-0           
    libnetcdf:     4.4.1-0           
    proj4:         4.9.2-0           
    pyparsing:     2.1.4-py35_0      
    rasterio:      0.36.0-np112py35_0
    snuggs:        1.4.0-py35_0      
    xerces-c:      3.1.4-0           

Proceed ([y]/n)? y

geos-3.5.0-0.t 100% |#####################################| Time: 0:00:00   5.70 MB/s
proj4-4.9.2-0. 100% |#####################################| Time: 0:00:00   6.18 MB/s
xerces-c-3.1.4 100% |#####################################| Time: 0:00:00   3.39 MB/s
curl-7.49.0-1. 100% |#####################################| Time: 0:00:00   3.38 MB/s
hdf4-4.2.12-1. 100% |#####################################| Time: 0:00:00   4.40 MB/s
hdf5-1.8.17-1. 100% |#####################################| Time: 0:00:00   3.23 MB/s
affine-2.0.0-p 100% |#####################################| Time: 0:00:00  27.49 MB/s
click-6.7-py35 100% |#####################################| Time: 0:00:00   7.36 MB/s
geotiff-1.4.1- 100% |#####################################| Time: 0:00:00   3.26 MB/s
kealib-1.4.6-0 100% |#####################################| Time: 0:00:00   4.92 MB/s
libnetcdf-4.4. 100% |#####################################| Time: 0:00:00   3.32 MB/s
pyparsing-2.1. 100% |#####################################| Time: 0:00:00   2.25 MB/s
click-plugins- 100% |#####################################| Time: 0:00:00  10.32 MB/s
cligj-0.4.0-py 100% |#####################################| Time: 0:00:00  18.85 MB/s
libgdal-2.1.0- 100% |#####################################| Time: 0:00:02   3.24 MB/s
snuggs-1.4.0-p 100% |#####################################| Time: 0:00:00   3.59 MB/s
rasterio-0.36. 100% |#####################################| Time: 0:00:00   2.02 MB/s
(dev_datashader)$ python -c "import rasterio"
Traceback (most recent call last):
 File "<string>", line 1, in <module>
 File "/Users/cball/mc3/envs/dev_datashader/lib/python3.5/site-packages/rasterio/__init__.py", line 15, in <module>
   from rasterio._base import (
ImportError: dlopen(/Users/cball/mc3/envs/dev_datashader/lib/python3.5/site-packages/rasterio/_base.cpython-35m-darwin.so, 2): Library not loaded: @rpath/libjpeg.8.dylib
 Referenced from: /Users/cball/mc3/envs/dev_datashader/lib/libgdal.20.dylib
 Reason: image not found
```

I have OS X 10.12.5, in case it matters.

```
(dev_datashader)$ find ~/mc3/envs/dev_datashader/lib -iname "*libjpeg*"
/Users/cball/mc3/envs/dev_datashader/lib/libjpeg.9.dylib
/Users/cball/mc3/envs/dev_datashader/lib/libjpeg.a
/Users/cball/mc3/envs/dev_datashader/lib/libjpeg.dylib
/Users/cball/mc3/envs/dev_datashader/lib/libjpeg.la
```

```
(dev_datashader)$ conda update libgdal jpeg
Fetching package metadata ...........
Solving package specifications: .

# All requested packages already installed.
# packages in environment at /Users/cball/mc3/envs/dev_datashader:
#
jpeg                      9b                            0  
libgdal                   2.1.0                         0  
```

**Comment by ceball** [comment]
Just a note that rasterio from conda-forge appears to work.
