### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by kkane5** [ContinuumIO/anaconda-issues#2442]
## Main error
An unexpected error occurred on Navigator start-up<br>[Error 0] The operation completed successfully
## Traceback
```
Traceback (most recent call last):
  File "C:\Users\Kevin\Anaconda2\lib\site-packages\anaconda_navigator\exceptions.py", line 75, in exception_handler
    return_value = func(*args, **kwargs)
  File "C:\Users\Kevin\Anaconda2\lib\site-packages\anaconda_navigator\app\start.py", line 108, in start_app
    if misc.load_pid() is None:  # A stale lock might be around
  File "C:\Users\Kevin\Anaconda2\lib\site-packages\anaconda_navigator\utils\misc.py", line 384, in load_pid
    cmds = process.cmdline()
  File "C:\Users\Kevin\Anaconda2\lib\site-packages\psutil\__init__.py", line 701, in cmdline
    return self._proc.cmdline()
  File "C:\Users\Kevin\Anaconda2\lib\site-packages\psutil\_pswindows.py", line 620, in wrapper
    return fun(self, *args, **kwargs)
  File "C:\Users\Kevin\Anaconda2\lib\site-packages\psutil\_pswindows.py", line 690, in cmdline
    ret = cext.proc_cmdline(self.pid)
WindowsError: [Error 0] The operation completed successfully

```
## System information
```
platform: win-32
version: 1.6.2
conda: 4.3.21
qt: 5.6.2
language: en_US
python: 2.7.13
os: Windows;7;6.1.7601;AMD64;Intel64 Family 6 Model 42 Stepping 7, GenuineIntel
pyqt: 5.6.0
```

**Comment by goanpeca** [comment]
Please try to reset the configurarion

`anaconda-navigator --reset`

---

Please update to the latest version of Navigator.

On Navigator click on the update button on the top right of the interface or
on the terminal type

```
$ conda update anaconda-navigator
```
