### ISSUE TITLE
mklfft causes scipy test failures

### ISSUE THREAD

**Issue by xiaoweiz** [ContinuumIO/anaconda-issues#245]
The issue was initially reported at scipy/scipy#4400 and it turned out to be a possible Anaconda issue as hinted by @asmeurer . 

Here's system setup:
+ OS X Mavericks
+ Anaconda 2.1.0 with MKL optimization
+ Scipy 0.15.1
+ Numpy 1.9.1

With `mklfft` installed
```shell
python -c "from scipy import ndimage; ndimage.test('full')"
Running unit tests for scipy.ndimage
NumPy version 1.9.1
NumPy is installed in /Users/zhangxiaowei/anaconda/lib/python2.7/site-packages/numpy
SciPy version 0.15.0
SciPy is installed in /Users/zhangxiaowei/anaconda/lib/python2.7/site-packages/scipy
Python version 2.7.9 |Continuum Analytics, Inc.| (default, Dec 15 2014, 10:37:34) [GCC 4.2.1 (Apple Inc. build 5577)]
nose version 1.3.4
...............................................................................................................................................................................................................................................................................................FF..............................................................................................................................................................
======================================================================
FAIL: test_ndimage.TestNdimage.test_fourier_shift_complex01
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/zhangxiaowei/anaconda/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/Users/zhangxiaowei/anaconda/lib/python2.7/site-packages/scipy/ndimage/tests/test_ndimage.py", line 1336, in test_fourier_shift_complex01
    assert_array_almost_equal(a.real[1:, 1:], expected[:-1, :-1])
  File "/Users/zhangxiaowei/anaconda/lib/python2.7/site-packages/numpy/testing/utils.py", line 842, in assert_array_almost_equal
    precision=decimal)
  File "/Users/zhangxiaowei/anaconda/lib/python2.7/site-packages/numpy/testing/utils.py", line 665, in assert_array_compare
    raise AssertionError(msg)
AssertionError:
Arrays are not almost equal to 6 decimals

(mismatch 78.9247311828%)
 x: array([[  1.514934e-06,   1.000002e+00,   2.000001e+00,   3.000002e+00,
          4.000001e+00,   5.000002e+00,   6.000002e+00,   7.000002e+00,
          8.000001e+00,   9.000001e+00,   1.000000e+01,   1.100000e+01,...
 y: array([[   0.+0.j,    1.+0.j,    2.+0.j,    3.+0.j,    4.+0.j,    5.+0.j,
           6.+0.j,    7.+0.j,    8.+0.j,    9.+0.j,   10.+0.j,   11.+0.j,
          12.+0.j,   13.+0.j,   14.+0.j],...

======================================================================
FAIL: test_ndimage.TestNdimage.test_fourier_shift_real01
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/zhangxiaowei/anaconda/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/Users/zhangxiaowei/anaconda/lib/python2.7/site-packages/scipy/ndimage/tests/test_ndimage.py", line 1322, in test_fourier_shift_real01
    assert_array_almost_equal(a[1:, 1:], expected[:-1, :-1])
  File "/Users/zhangxiaowei/anaconda/lib/python2.7/site-packages/numpy/testing/utils.py", line 842, in assert_array_almost_equal
    precision=decimal)
  File "/Users/zhangxiaowei/anaconda/lib/python2.7/site-packages/numpy/testing/utils.py", line 665, in assert_array_compare
    raise AssertionError(msg)
AssertionError:
Arrays are not almost equal to 6 decimals

(mismatch 100.0%)
 x: array([[  46.954332, -157.977735, -339.941516, -470.421044, -530.813966,
        -511.298085, -415.024098, -256.      ,  -58.002222,  149.259413,
         334.880048,  470.421044,  535.875433,  520.016407,  426.071989],...
 y: array([[   0.,    1.,    2.,    3.,    4.,    5.,    6.,    7.,    8.,
           9.,   10.,   11.,   12.,   13.,   14.],
       [  16.,   17.,   18.,   19.,   20.,   21.,   22.,   23.,   24.,...

----------------------------------------------------------------------
Ran 447 tests in 2.189s

FAILED (failures=2)
```

After removing `mklfft`, the issue goes away. 

```shell
conda remove mklfft                                                      [11:00:43]
Fetching package metadata: ..

Package plan for package removal in environment /Users/zhangxiaowei/anaconda:

The following packages will be REMOVED:

    mklfft: 1.0-np19py27_p0

Proceed ([y]/n)?

Unlinking packages ...
[      COMPLETE      ] |############################################################| 100%
```
```shell
python -c "from scipy import ndimage; ndimage.test('full')"              [11:01:06]
Running unit tests for scipy.ndimage
NumPy version 1.9.1
NumPy is installed in /Users/zhangxiaowei/anaconda/lib/python2.7/site-packages/numpy
SciPy version 0.15.1
SciPy is installed in /Users/zhangxiaowei/anaconda/lib/python2.7/site-packages/scipy
Python version 2.7.9 |Continuum Analytics, Inc.| (default, Dec 15 2014, 10:37:34) [GCC 4.2.1 (Apple Inc. build 5577)]
nose version 1.3.4
...............................................................................................................................................................................................................................................................................................................................................................................................................................................................
----------------------------------------------------------------------
Ran 447 tests in 2.088s

OK
```

**Comment by xiaoweiz** [comment]
Have just upgraded `mklfft` to 2.0 through `conda` and the reported issue is gone.
