### ISSUE TITLE
Problem with scipy: 0.15.1-np19py33_0

### ISSUE THREAD

**Issue by 0zeroth** [ContinuumIO/anaconda-issues#260]
After upgrading scipy (as part of upgrading the pandas stack), cannot import scipy packages.

``` python
from scipy.signal import lfilter
Traceback (most recent call last):

  File "<ipython-input-2-6b56905a1303>", line 1, in <module>
    from scipy.signal import lfilter

  File "D:\Miniconda3\lib\site-packages\scipy\signal\__init__.py", line 264, in <module>
    from .bsplines import *

  File "D:\Miniconda3\lib\site-packages\scipy\signal\bsplines.py", line 4, in <module>
    import scipy.special

  File "D:\Miniconda3\lib\site-packages\scipy\special\__init__.py", line 589, in <module>
    from . import specfun

ImportError: cannot import name specfun
```

**Comment by ccordoba12** [comment]
Please close any Python application (IPython, the IPython notebook or Spyder) before running this command

    conda install -f scipy

That should fix your problem

**Comment by MHee** [comment]
I have the same sort of problems with Python 2.7 and unfortunately 
```
conda install -f scipy
```
does not fix it...

Here is what happens in a test environment:
```
[test] C:\Users\mheesema\AppData\Local\Continuum\Anaconda\Scripts>conda install -f scipy
Fetching package metadata: ....
Solving package specifications: .
Package plan for installation in environment C:\Users\mheesema\AppData\Local\Continuum\Anaconda\envs\test:

The following packages will be UPDATED:

    scipy: 0.15.1-np19py27_0 --> 0.15.1-np19py27_0

Proceed ([y]/n)?

[      COMPLETE      ] |#################################################| 100%
Extracting packages ...
[      COMPLETE      ] |#################################################| 100%
Unlinking packages ...
[      COMPLETE      ] |#################################################| 100%
Linking packages ...
[      COMPLETE      ] |#################################################| 100%

[test] C:\Users\mheesema\AppData\Local\Continuum\Anaconda\Scripts>ipython
Python 2.7.8 |Anaconda 2.1.0 (64-bit)| (default, Jul  2 2014, 15:12:11) [MSC v.1500 64 bit (AMD64)]
Type "copyright", "credits" or "license" for more information.

IPython 2.3.1 -- An enhanced Interactive Python.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://binstar.org
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: from scipy.signal import lfilter
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-6b56905a1303> in <module>()
----> 1 from scipy.signal import lfilter

C:\Users\mheesema\AppData\Local\Continuum\Anaconda\lib\site-packages\scipy\signal\__init__.py in <module>()
    262 from .spline import *
    263
--> 264 from .bsplines import *
    265 from .cont2discrete import *
    266 from .dltisys import *

C:\Users\mheesema\AppData\Local\Continuum\Anaconda\lib\site-packages\scipy\signal\bsplines.py in <module>()
      2
      3 from scipy.lib.six import xrange
----> 4 import scipy.special
      5 from numpy import logical_and, asarray, pi, zeros_like, \
      6      piecewise, array, arctan2, tan, zeros, arange, floor

C:\Users\mheesema\AppData\Local\Continuum\Anaconda\lib\site-packages\scipy\special\__init__.py in <module>()
    591 from .orthogonal import *
    592 from .spfun_stats import multigammaln
--> 593 from ._ellip_harm import ellip_harm, ellip_harm_2, ellip_normal
    594 from .lambertw import lambertw
    595

C:\Users\mheesema\AppData\Local\Continuum\Anaconda\lib\site-packages\scipy\special\_ellip_harm.py in <module>()
      4 import numpy as np
      5
----> 6 from ._ufuncs import _ellip_harm
      7 from ._ellip_harm_2 import _ellipsoid, _ellipsoid_norm
      8

ImportError: cannot import name _ellip_harm

```

**Comment by JanSchulz** [comment]
I had the same error (from an import of statsmodels) and in my case the `conda update -f scipy` command after a reload of all my kernels helped.

**Comment by neil-s** [comment]
On a fully updated version of conda and anaconda, the `conda update -f scipy` command did the trick for me.

**Comment by starsblinking** [comment]
I restart spyder and the problem disappears!
