### ISSUE TITLE
mklfft 2.0 breaks NumPy

### ISSUE THREAD

**Issue by woutergins** [ContinuumIO/anaconda-issues#261]
I updated my packages, meaning I upgraded to this:

    accelerate: 1.9.0-np19py34_p0  --> 1.10.0-np19py34_p0
    conda-env:  2.0.2-py34_0       --> 2.1.0-py34_0
    llvmlite:   0.2.0-py34_0       --> 0.2.2-py34_1
    mklfft:     1.0-np19py34_p0    --> 2.0-np19py34_p0
    numba:      0.16.0-np19py34_0  --> 0.17.0-np19py34_0
    numbapro:   0.17.0-np19py34_p0 --> 0.17.1-np19py34_p0

Following this, importing NumPy lead to the following error:

    >>> import numpy as np
    Traceback (most recent call last):
    File "<stdin>", line 1, in <module>
    File "C:\Users\MyStuff\Anaconda3\lib\site-packages\numpy\__init__.py", line 189, in <module>
    from . import fft
    File "C:\Users\MyStuff\Anaconda3\lib\site-packages\numpy\fft\__init__.py", line 7, in <module>
    from mklfft.fftpack import *
    File "C:\Users\MyStuff\Anaconda3\lib\site-packages\mklfft\fftpack.py", line 48, in <module>
    def _raw_fft(a, n=None, axis=-1, init_function=fftpack.cffti,
    AttributeError: 'module' object has no attribute 'cffti'

Downgrading to mklfft 1.0 fixed this issue.

**Comment by sklam** [comment]
I cannot duplicate the problem on Windows 7 or OSX.  Can you tell me which Windows version you are on?  Can you try install mklfft on a fresh conda environment?

**Comment by sklam** [comment]
We suspect that conda failed to update some files because they were kept opened by a process.  Restarting the system and retrying the installation should fix the problem.  You may need to force the writing of the files by using the -f option, e.g. `conda install -f numpy mkl mklfft`.  Please let us know if the problem persists.

**Comment by sklam** [comment]
A client has reported that the "force" command resolved the problem.  

@ilanschnell, @asmeurer,  Is there a way for conda to know if a file cannot be written to because another process has ownership on it?  Conda should report ask the user to close all processes or restart if necessary.

**Comment by asmeurer** [comment]
There are ways to do it but currently conda only does a basic process check. See https://github.com/conda/conda/issues/1001.
