### ISSUE TITLE
GDAL not finding Proj.4

### ISSUE THREAD

**Issue by BrendanMD** [ContinuumIO/anaconda-issues#263]
Anaconda 2.1.0 Windows 64 bit
gdal                      1.11.0               np19py27_0
proj4                     4.8.0                         0

I have installed GDAL and Proj.4, but I am getting an error when I try to run one of the GDAL sample scripts, tolatlong.py(http://svn.osgeo.org/gdal/trunk/gdal/swig/python/samples/tolatlong.py) e.g.

```
E:\parse_cis>python tolatlong.py 0 0 temp.tif
Traceback (most recent call last):
  File "tolatlong.py", line 106, in <module>
    (int, lat, height) = ct.TransformPoint(X, Y)
  File "C:\Users\DeTraceyB\AppData\Local\Continuum\Anaconda\lib\site-packages\osgeo\osr.py", line 757, in TransformPoint
    return _osr.CoordinateTransformation_TransformPoint(self, *args)
NotImplementedError: Wrong number or type of arguments for overloaded function 'CoordinateTransformation_TransformPoint'.
  Possible C/C++ prototypes are:
    OSRCoordinateTransformationShadow::TransformPoint(double [3])
    OSRCoordinateTransformationShadow::TransformPoint(double [3],double,double,double)
```

When I google this error I see it might be related to GDAL not finding Proj (https://github.com/avalentino/gsdview/issues/89). But as I said, I have installed Proj (conda install -c https://conda.binstar.org/osgeo proj4). The same error occurs when trying to call osr.CoordinateTransformation_TransformPoint from a script in Spyder. The Proj installer dumped copies of proj.dll, proj.exe, cs2cs.exe, geod.exe and nad2bin.exe in the Anaconda root directory (C:\Users\MyUserName\AppData\Local\Continuum\Anaconda), which is messy, but makes it odd if proj.dll is not being found.

**Comment by BrendanMD** [comment]
Should have tested on more than one geotiff. My sample had no 'Coordinate System'. Issue closed.

**Comment by michaelaye** [comment]
Hm, I have exactly this problem, but citing that PROJ.4 library cannot be found and I have confirmed that my file has all required information:

```bash
$ gdalinfo img.cal.map.cub
Driver: ISIS3/USGS Astrogeology ISIS cube (Version 3)
Files: img.cal.map.cub
Size is 19388, 67951
Coordinate System is:
PROJCS["Sinusoidal Mars",
    GEOGCS["GCS_Mars",
        DATUM["D_Mars",
            SPHEROID["Mars",3396190,0]],
        PRIMEM["Reference_Meridian",0],
        UNIT["degree",0.0174532925199433]],
    PROJECTION["Sinusoidal"],
    PARAMETER["longitude_of_center",296.28065864847],
    PARAMETER["false_easting",0],
    PARAMETER["false_northing",0]]
Origin = (-4959.626702915599708,-4803213.120008500292897)
Pixel Size = (0.495566217317710,-0.495566217317710)
Corner Coordinates:
Upper Left  (   -4959.627,-4803213.120)
Lower Left  (   -4959.627,-4836887.340)
Upper Right (    4648.411,-4803213.120)
Lower Right (    4648.411,-4836887.340)
Center      (    -155.608,-4820050.230)
Band 1 Block=262x128 Type=Float32, ColorInterp=Undefined
  NoData Value=-3.40282265508890445e+38
```

```bash
$ python tolatlong.py 0 0 img.cal.map.cub
ERROR 6: Unable to load PROJ.4 library (libproj.dylib), creation of
OGRCoordinateTransformation failed.
Traceback (most recent call last):
  File "tolatlong.py", line 75, in <module>
    (int, lat, height) = ct.TransformPoint(X, Y)
  File "/Users/klay6683/miniconda3/envs/py27/lib/python2.7/site-packages/osgeo/osr.py", line 795, in TransformPoint
    return _osr.CoordinateTransformation_TransformPoint(self, *args)
NotImplementedError: Wrong number of arguments for overloaded function 'CoordinateTransformation_TransformPoint'.
  Possible C/C++ prototypes are:
    TransformPoint(OSRCoordinateTransformationShadow *,double [3])
    TransformPoint(OSRCoordinateTransformationShadow *,double [3],double,double,double)
```

How can I make my anaconda python find the PROJ.4 library?

**Comment by theobarnhart** [comment]
I also seem to be having this issue. Anyone found a fix yet?

**Comment by kalefranz** [comment]
@ilanschnell @csoja https://twitter.com/michaelaye/status/699756403880165376

**Comment by kalefranz** [comment]
@groutr can we get @michaelaye an update on where things are here?

**Comment by jjhelmus** [comment]
This issue seems to affect the command line tools that are included with the libgdal package, at least the OS X  2.0.0 build 0 package.

```
$ conda list libgdal
# packages in environment at /Users/jhelmus/anaconda/envs/gdal_test:
#
libgdal                   2.0.
$ gdaltransform -s_srs EPSG:28992 -t_srs EPSG:31370
ERROR 6: Unable to load PROJ.4 library (libproj.dylib), creation of
OGRCoordinateTransformation failed.
```

libgdal does not seems to be linked against proj, as indicated by the missing `-lproj` in the output from gdal-config.

```
$ ./gdal-config --dep-libs
-lsqlite3 -lexpat -L/opt/anaconda1anaconda2anaconda3/lib -lnetcdf -L/opt/anaconda1anaconda2anaconda3/lib -lhdf5 -L/usr/lib -lpq -lz -lpthread -ldl -L/opt/anaconda1anaconda2anaconda3/lib -lcurl -lssl -lcrypto -lgssapi_krb5 -lresolv -lz -liconv -lxml2 -lz -lpthread -licucore -lm
```

The `--with-static-proj4` flag may need to be assigned in ./configure during the build.  Despite its name it does not appear to actually statically link in the proj4 library, at least on OS X.

**Comment by dmopalmer** [comment]
Creating an environment with only gdal (under OS X) gives a functioning system.
```
conda create -y --name gdal_try python=3 gdal
source activate gdal_try
gdaltransform -s_srs EPSG:28992 -t_srs EPSG:31370 < /dev/null
```
However, some contributed packages downgrade libgdal to a nonfunctioning version.
```
conda install -y -c https://conda.anaconda.org/menpo opencv3
```
says
```
The following NEW packages will be INSTALLED:

    opencv3:   3.1.0-py35_0
    tbb:       4.3_20141023-0

The following packages will be DOWNGRADED:

    hdf5:      1.8.16-0 --> 1.8.15.1-2
    kealib:    1.4.5-2  --> 1.4.5-0
    libgdal:   2.0.0-4  --> 2.0.0-0
    libnetcdf: 4.4.0-1  --> 4.3.3.1-3
```
Running gdaltransform gives an error message saying that krb5 can't be loaded.  If you then install that, it gives the proj.4 error, and installing proj4 and proj.4 does not fix it.

So now I have to learn Yet-Another-Recipe-Based-System to figure out how to take menpo's recipe for opencv and make it not downgrade things.

**Comment by groutr** [comment]
@dmopalmer what channels are you using in `.condarc`?

**Comment by dmopalmer** [comment]
I did the standard install, which did not create a .condarc file.  `conda info` gives:
```
(gdal_try4)% conda info
Using Anaconda Cloud api site https://api.anaconda.org
Current conda install:

             platform : osx-64
        conda version : 4.0.5
  conda-build version : 0+unknown
       python version : 2.7.11.final.0
     requests version : 2.9.1
     root environment : /Users/palmer/anaconda  (writable)
  default environment : /Users/palmer/anaconda/envs/gdal_try4
     envs directories : /Users/palmer/anaconda/envs
        package cache : /Users/palmer/anaconda/pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/osx-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/osx-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : None
    is foreign system : False

```

**Comment by goanpeca** [comment]
Closing for lack of activity.

Please reopen if you consider otherwise.

Thanks!
