### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by HLBayes** [ContinuumIO/anaconda-issues#2635]
## Main error
Application <b>spyder</b> launch may have produced errors.
## Traceback
```
Traceback (most recent call last):
  File "E:\software\Anaconda\Scripts\spyder-script.py", line 3, in <module>
    import spyder.app.start
  File "E:\software\Anaconda\lib\site-packages\spyder\app\start.py", line 13, in <module>
    from spyder.config.base import get_conf_path, running_in_mac_app
  File "E:\software\Anaconda\lib\site-packages\spyder\config\base.py", line 365, in <module>
    _ = get_translation("spyder")
  File "E:\software\Anaconda\lib\site-packages\spyder\config\base.py", line 337, in get_translation
    language = load_lang_conf()
  File "E:\software\Anaconda\lib\site-packages\spyder\config\base.py", line 318, in load_lang_conf
    lang = get_interface_language()
  File "E:\software\Anaconda\lib\site-packages\spyder\config\base.py", line 289, in get_interface_language
    spyder_languages = get_available_translations()
  File "E:\software\Anaconda\lib\site-packages\spyder\config\base.py", line 260, in get_available_translations
    error = _('Update LANGUAGE_CODES (inside config/base.py) if a new '
NameError: global name '_' is not defined

```
## System information
```
platform: win-64
version: 1.6.2
conda: 4.3.21
qt: 5.6.2
language: zh_CN
python: 2.7.13
os: Windows;10;10.0.14393;AMD64;Intel64 Family 6 Model 60 Stepping 3, GenuineIntel
pyqt: 5.6.0
```

**Comment by goanpeca** [comment]
@ccordoba12 ?

**Comment by ccordoba12** [comment]
What is your Spyder version?

**Comment by nikhildamodaran** [comment]
Version 3.1.4

**Comment by HLBayes** [comment]
Python 2.7.13|Anaconda 4.4.0 (64-bit)



Best wish to you !

  Libo Huang  
Computer Science and Technology, Guangdong University of Technology
Lab: http://www.dmirlab.com
Email: www.446425957@qq.com
 
From: Nikhil Damodaran
Date: 2017-06-28 11:20
To: ContinuumIO/anaconda-issues
CC: HLBayes; Author
Subject: Re: [ContinuumIO/anaconda-issues] Navigator Error (#2635)
Version 3.1.4

**Comment by ccordoba12** [comment]
Please run in a terminal

    spyder --reset
    conda install -f spyder

and try again.
