### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by Varsha-Rao** [ContinuumIO/anaconda-issues#2671]
## Main error
Application <b>spyder</b> launch may have produced errors.
## Traceback
```
Traceback (most recent call last):
  File "C:\Users\tr100074\AppData\Local\Continuum\Anaconda3\Scripts\spyder-script.py", line 5, in <module>
    sys.exit(spyder.app.start.main())
  File "C:\Users\tr100074\AppData\Local\Continuum\Anaconda3\lib\site-packages\spyder\app\start.py", line 103, in main
    from spyder.app import mainwindow
  File "C:\Users\tr100074\AppData\Local\Continuum\Anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 165, in <module>
    from spyder.utils.environ import WinUserEnvDialog
  File "C:\Users\tr100074\AppData\Local\Continuum\Anaconda3\lib\site-packages\spyder\utils\environ.py", line 20, in <module>
    from spyder.widgets.variableexplorer.collectionseditor import CollectionsEditor
  File "C:\Users\tr100074\AppData\Local\Continuum\Anaconda3\lib\site-packages\spyder\widgets\variableexplorer\collectionseditor.py", line 46, in <module>
    from spyder.widgets.variableexplorer.importwizard import ImportWizard
  File "C:\Users\tr100074\AppData\Local\Continuum\Anaconda3\lib\site-packages\spyder\widgets\variableexplorer\importwizard.py", line 26, in <module>
    import pandas as pd
  File "C:\Users\tr100074\AppData\Local\Continuum\Anaconda3\lib\site-packages\pandas\__init__.py", line 42, in <module>
    from pandas.core.api import *
  File "C:\Users\tr100074\AppData\Local\Continuum\Anaconda3\lib\site-packages\pandas\core\api.py", line 10, in <module>
    from pandas.core.groupby import Grouper
  File "C:\Users\tr100074\AppData\Local\Continuum\Anaconda3

**Comment by goanpeca** [comment]
@ccordoba12
