### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by mayurkmane** [ContinuumIO/anaconda-issues#2676]
## Main error
An unexpected error occurred on Navigator start-up<br>psutil.AccessDenied (pid=668)

Note: I have updated Anaconda Navigator and also re-installed, still no solution for this error.
## Traceback
```
Traceback (most recent call last):
  File "C:\Users\mmane\AppData\Local\Continuum\Anaconda3\lib\site-packages\psutil\_pswindows.py", line 620, in wrapper
    return fun(self, *args, **kwargs)
  File "C:\Users\mmane\AppData\Local\Continuum\Anaconda3\lib\site-packages\psutil\_pswindows.py", line 690, in cmdline
    ret = cext.proc_cmdline(self.pid)
PermissionError: [WinError 5] Access is denied

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\mmane\AppData\Local\Continuum\Anaconda3\lib\site-packages\anaconda_navigator\exceptions.py", line 75, in exception_handler
    return_value = func(*args, **kwargs)
  File "C:\Users\mmane\AppData\Local\Continuum\Anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 108, in start_app
    if misc.load_pid() is None:  # A stale lock might be around
  File "C:\Users\mmane\AppData\Local\Continuum\Anaconda3\lib\site-packages\anaconda_navigator\utils\misc.py", line 384, in load_pid
    cmds = process.cmdline()
  File "C:\Users\mmane\AppData\Local\Continuum\Anaconda3\lib\site-packages\psutil\__init__.py", line 701, in cmdline
    return self._proc.cmdline()
  File "C:\Users\mmane\AppData\Local\Continuum\Anaconda3\lib\site-packages\psutil\_pswindows.py", line 623, in wrapper
    raise AccessDenied(self.pid, self._name)
psutil.AccessDenied: psutil.AccessDenied (pid=668)

```
## System information
```
python: 3.6.1
Windows 10 OS
Intel i5 Processor with 8GB RAM
langu

**Comment by mayurkmane** [comment]
I have resolved this issue by deleting all anaconda related files (.anaconda and .conda folders) from C drive and re-installing anaconda with updated version.
