### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by geenatan** [ContinuumIO/anaconda-issues#2707]
## Main error
Application <b>spyder</b> launch may have produced errors.
## Traceback
```
Traceback (most recent call last):
  File "C:\PythonAnaconda\Scripts\spyder-script.py", line 5, in <module>
    sys.exit(spyder.app.start.main())
  File "C:\PythonAnaconda\lib\site-packages\spyder\app\start.py", line 103, in main
    from spyder.app import mainwindow
  File "C:\PythonAnaconda\lib\site-packages\spyder\app\mainwindow.py", line 165, in <module>
    from spyder.utils.environ import WinUserEnvDialog
  File "C:\PythonAnaconda\lib\site-packages\spyder\utils\environ.py", line 20, in <module>
    from spyder.widgets.variableexplorer.collectionseditor import CollectionsEditor
  File "C:\PythonAnaconda\lib\site-packages\spyder\widgets\variableexplorer\collectionseditor.py", line 46, in <module>
    from spyder.widgets.variableexplorer.importwizard import ImportWizard
  File "C:\PythonAnaconda\lib\site-packages\spyder\widgets\variableexplorer\importwizard.py", line 26, in <module>
    import pandas as pd
  File "C:\PythonAnaconda\lib\site-packages\pandas\__init__.py", line 23, in <module>
    from pandas.compat.numpy import *
  File "C:\PythonAnaconda\lib\site-packages\pandas\compat\__init__.py", line 361, in <module>
    from dateutil import parser as _date_parser
  File "C:\PythonAnaconda\lib\site-packages\dateutil\parser.py", line 158
    l.append("%s=%s" % (attr, `value`))
                              ^
SyntaxError: invalid syntax

```
## System information
```
python: 3.6.1
language: en_GB
os: Windows;10;10.0.14393;AMD64;Intel64 Family 6 Model 58 Stepping 9, Genuin

**Comment by goanpeca** [comment]
@ccordoba12
