### ISSUE TITLE
New IPython3 (notebook) packages don't declare all necessary dependencies

### ISSUE THREAD

**Issue by rmcgibbo** [ContinuumIO/anaconda-issues#276]
The packages `mistune` and `pygments` are [required](https://github.com/ipython/ipython/blob/master/setup.py#L258) for the latest release IPython notebook, but they are not included as a dependencies in the new conda packages that came out this morning.

Test with:
```
$ conda install ipython-notebook
$ python -c "from IPython.sphinxext import ipython_console_highlighting"
```

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/rmcgibbo/miniconda/envs/3.4.2/lib/python3.4/site-packages/IPython/sphinxext/ipython_console_highlighting.py", line 7, in <module>
    from ..nbconvert.utils.lexers import IPyLexer
  File "/Users/rmcgibbo/miniconda/envs/3.4.2/lib/python3.4/site-packages/IPython/nbconvert/__init__.py", line 3, in <module>
    from .exporters import *
  File "/Users/rmcgibbo/miniconda/envs/3.4.2/lib/python3.4/site-packages/IPython/nbconvert/exporters/__init__.py", line 1, in <module>
    from .export import *
  File "/Users/rmcgibbo/miniconda/envs/3.4.2/lib/python3.4/site-packages/IPython/nbconvert/exporters/export.py", line 13, in <module>
    from .templateexporter import TemplateExporter
  File "/Users/rmcgibbo/miniconda/envs/3.4.2/lib/python3.4/site-packages/IPython/nbconvert/exporters/templateexporter.py", line 30, in <module>
    from IPython.nbconvert import filters
  File "/Users/rmcgibbo/miniconda/envs/3.4.2/lib/python3.4/site-packages/IPython/nbconvert/filters/__init__.py", line 6, in <module>
    from .markdown import *
  File "/Users/rmcgibbo/miniconda/envs/3.4.2/lib/python3.4/site-packages/IPython/nbconvert/filters/markdown.py", line 17, in <module>
    import mistune
ImportError: No module named 'mistune'
```

**Comment by rmcgibbo** [comment]
Also perhaps `terminado` and `mock`, but I'm not sure about that.

**Comment by rmcgibbo** [comment]
Looks like this has been fixed with the latest build.
