### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by florianfraisseagfa** [ContinuumIO/anaconda-issues#2810]
## Main error
Application <b>notebook</b> launch may have produced errors.
## Traceback
```
Traceback (most recent call last):
  File "H:\Anaconda\lib\asyncio\__init__.py", line 16, in <module>
    from . import _overlapped
ImportError: cannot import name '_overlapped'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "H:\Anaconda\Scripts\jupyter-notebook-script.py", line 3, in <module>
    import notebook.notebookapp
  File "H:\Anaconda\lib\site-packages\notebook\notebookapp.py", line 35, in <module>
    from jinja2 import Environment, FileSystemLoader
  File "H:\Anaconda\lib\site-packages\jinja2\__init__.py", line 81, in <module>
    _patch_async()
  File "H:\Anaconda\lib\site-packages\jinja2\__init__.py", line 77, in _patch_async
    from jinja2.asyncsupport import patch_all
  File "H:\Anaconda\lib\site-packages\jinja2\asyncsupport.py", line 13, in <module>
    import asyncio
  File "H:\Anaconda\lib\asyncio\__init__.py", line 18, in <module>
    import _overlapped  # Will also be exported.
OSError: [WinError 10022] An invalid argument was supplied

```
## System information
```
python: 3.6.1
language: nl_BE
os: Windows;7;6.1.7601;AMD64;Intel64 Family 6 Model 60 Stepping 3, GenuineIntel
version: 1.6.2
platform: win-64
qt: 5.6.2
pyqt: 5.6.0
conda: 4.3.21
```

**Comment by goanpeca** [comment]
@ccordoba12 ?
