### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by csJd** [ContinuumIO/anaconda-issues#2822]
## Main error
Application <b>notebook</b> launch may have produced errors.
## Traceback
```
Traceback (most recent call last):
  File "D:\dsr\anaconda\Scripts\jupyter-notebook-script.py", line 3, in <module>
    import notebook.notebookapp
  File "D:\dsr\anaconda\lib\site-packages\notebook\notebookapp.py", line 35, in <module>
    from jinja2 import Environment, FileSystemLoader
  File "D:\dsr\anaconda\lib\site-packages\jinja2\__init__.py", line 33, in <module>
    from jinja2.environment import Environment, Template
  File "D:\dsr\anaconda\lib\site-packages\jinja2\environment.py", line 15, in <module>
    from jinja2 import nodes
  File "D:\dsr\anaconda\lib\site-packages\jinja2\nodes.py", line 19, in <module>
    from jinja2.utils import Markup
  File "D:\dsr\anaconda\lib\site-packages\jinja2\utils.py", line 624, in <module>
    from markupsafe import Markup, escape, soft_unicode
  File "D:\dsr\anaconda\lib\site-packages\markupsafe\__init__.py", line 14, in <module>
    from markupsafe._compat import text_type, string_types, int_types, \
ModuleNotFoundError: No module named 'markupsafe._compat'

```
## System information
```
python: 3.6.1
language: en_US
os: Windows;10;10.0.15063;AMD64;Intel64 Family 6 Model 58 Stepping 9, GenuineIntel
version: 1.6.2
platform: win-64
qt: 5.6.2
pyqt: 5.6.0
conda: 4.3.22
```

**Comment by goanpeca** [comment]
@csJd seems you have a broken install try to reinstall the notebook from the terminal

`$ conda install notebook markupsafe -f`
