### ISSUE TITLE
On Linux, typing nonexistent command in terminal gives ImportError

### ISSUE THREAD

**Issue by petebachant** [ContinuumIO/anaconda-issues#286]
To replicate:

```bash
$ fkjhdkjhfs
Failed to import the site module
Traceback (most recent call last):
  File "/usr/lib/python3.4/site.py", line 586, in <module>
    main()
  File "/usr/lib/python3.4/site.py", line 572, in main
    known_paths = addusersitepackages(known_paths)
  File "/usr/lib/python3.4/site.py", line 287, in addusersitepackages
    user_site = getusersitepackages()
  File "/usr/lib/python3.4/site.py", line 263, in getusersitepackages
    user_base = getuserbase() # this will also set USER_BASE
  File "/usr/lib/python3.4/site.py", line 253, in getuserbase
    USER_BASE = get_config_var('userbase')
  File "/usr/lib/python3.4/sysconfig.py", line 597, in get_config_var
    return get_config_vars().get(name)
  File "/usr/lib/python3.4/sysconfig.py", line 540, in get_config_vars
    _init_posix(_CONFIG_VARS)
  File "/usr/lib/python3.4/sysconfig.py", line 412, in _init_posix
    from _sysconfigdata import build_time_vars
  File "/usr/lib/python3.4/_sysconfigdata.py", line 6, in <module>
    from _sysconfigdata_m import *
ImportError: No module named '_sysconfigdata_m'
```

Using Linux Mint 17.1.

**Comment by ccordoba12** [comment]
There doesn't seem to be Anaconda present in your traceback because `/usr/lib/python3.4` is your system Python

**Comment by petebachant** [comment]
Strange. This doesn't happen if I remove `export PATH="/home/pete/anaconda3/bin:$PATH"` from my `.bashrc`.

**Comment by ccordoba12** [comment]
I think something else is messing up with your PATH. Maybe you have something unnoticed in `~/.profile` or something.

**Comment by aweinstein** [comment]
@ccordoba12:I have the same problem as @petebachant. In my case:

    $ python --version
    Python 3.4.3 :: Anaconda 2.1.0 (64-bit)

```
$ x
Failed to import the site module
Traceback (most recent call last):
  File "/usr/lib/python3.4/site.py", line 586, in <module>
    main()
  File "/usr/lib/python3.4/site.py", line 572, in main
    known_paths = addusersitepackages(known_paths)
  File "/usr/lib/python3.4/site.py", line 287, in addusersitepackages
    user_site = getusersitepackages()
  File "/usr/lib/python3.4/site.py", line 263, in getusersitepackages
    user_base = getuserbase() # this will also set USER_BASE
  File "/usr/lib/python3.4/site.py", line 253, in getuserbase
    USER_BASE = get_config_var('userbase')
  File "/usr/lib/python3.4/sysconfig.py", line 597, in get_config_var
    return get_config_vars().get(name)
  File "/usr/lib/python3.4/sysconfig.py", line 540, in get_config_vars
    _init_posix(_CONFIG_VARS)
  File "/usr/lib/python3.4/sysconfig.py", line 412, in _init_posix
    from _sysconfigdata import build_time_vars
  File "/usr/lib/python3.4/_sysconfigdata.py", line 6, in <module>
    from _sysconfigdata_m import *
ImportError: No module named '_sysconfigdata_m' 
```

Changing the name of the anaconda directory removes the problem (but obviously I don't have access to anaconda then). I found this related bug report:

https://bugs.launchpad.net/ubuntu/+source/python3.3/+bug/1192890

Following the instructions (changing the line in `/etc/bash.bashrc`) also solves the problem.

Since this problem happens write after installing anaconda, I would think is related to the anaconda installation.

In case it matters, I'm running linux mint 17.

**Comment by petebachant** [comment]
I was also able to fix the problem by changing `/etc/bash.bashrc` to run the script without calling an instance of python:

```bash
# if the command-not-found package is installed, use it
if [ -x /usr/lib/command-not-found ]; then
        function command_not_found_handle {
                # check because c-n-f could've been removed in the meantime
                if [ -x /usr/lib/command-not-found ]; then
                   /usr/lib/command-not-found -- $1
                   return $?
                else
                   return 127
                fi
        }
fi
```

**Comment by ccordoba12** [comment]
What do you propose we should solve this issue in our side? Touching something in /etc is obviously not an option ;-)

**Comment by petebachant** [comment]
I guess this is an issue that should be fixed inside Mint, not Anaconda. I will look elsewhere. Thanks for your help @ccordoba12 and @aweinstein!

**Comment by bergkoet** [comment]
There's now a proposed a fix for this in the Ubuntu bug tracker:
https://bugs.launchpad.net/command-not-found/+bug/1480388
