### ISSUE TITLE
glueviz missing dependencies

### ISSUE THREAD

**Issue by tswicegood** [ContinuumIO/anaconda-issues#288]
I created a new environment with `glueviz` and was unable to get it to start until I installed the following packages:

* sip
* pyqt
* matplotlib
* pandas

I'm pretty sure all of these are hard dependencies, so they should be added to the meta data.

**Comment by tswicegood** [comment]
Note, I've gotten reports of this note working in the Anaconda Launcher internally at Continuum.  Need to make sure this is addressed, otherwise the application that appears first when installing apps from the `defaults` channel is borked.

cc @ilanschnell

**Comment by tswicegood** [comment]
Here's a gist of my environment history: https://gist.github.com/68cac5b7da232e85cab3

**Comment by Gabriel-p** [comment]
Not sure if this is related or if I should open a new issue.

I installed glueviz via anaconda-navigator. Attempting to launch  it fails with:

````
Traceback (most recent call last):
  File "/home/gabriel/anaconda2/bin/glue", line 4, in <module>
    from glue.main import main
  File "/home/gabriel/anaconda2/lib/python2.7/site-packages/glue/__init__.py", line 125, in <module>
    from .qglue import qglue
  File "/home/gabriel/anaconda2/lib/python2.7/site-packages/glue/qglue.py", line 14, in <module>
    import numpy as np
  File "/home/gabriel/.local/lib/python2.7/site-packages/numpy/__init__.py", line 180, in <module>
    from . import add_newdocs
  File "/home/gabriel/.local/lib/python2.7/site-packages/numpy/add_newdocs.py", line 13, in <module>
    from numpy.lib import add_newdoc
  File "/home/gabriel/.local/lib/python2.7/site-packages/numpy/lib/__init__.py", line 18, in <module>
    from .polynomial import *
  File "/home/gabriel/.local/lib/python2.7/site-packages/numpy/lib/polynomial.py", line 20, in <module>
    from numpy.linalg import eigvals, lstsq, inv
  File "/home/gabriel/.local/lib/python2.7/site-packages/numpy/linalg/__init__.py", line 51, in <module>
    from .linalg import *
  File "/home/gabriel/.local/lib/python2.7/site-packages/numpy/linalg/linalg.py", line 29, in <module>
    from numpy.linalg import lapack_lite, _umath_linalg
ImportError: /home/gabriel/anaconda2/bin/../lib/libgfortran.so.3: version `GFORTRAN_1.4' not found (required by /usr/lib/liblapack.so.3)
````

**Comment by ilanschnell** [comment]
The `libgfortran` error is unrelated to glueviz, probably some other update went wrong.
```
$ conda update libgfortran
```
should fix it.

**Comment by Gabriel-p** [comment]
I get:

````
$ conda update libgfortran
Using Anaconda Cloud api site https://api.anaconda.org
Fetching package metadata: ....
# All requested packages already installed.
# packages in environment at /home/gabriel/anaconda2:
#
libgfortran               3.0                           0  
````

after that, trying to launch `glueviz` results in:

````
Traceback (most recent call last):
  File "/home/gabriel/anaconda2/bin/glue", line 4, in <module>
    from glue.main import main
  File "/home/gabriel/anaconda2/lib/python2.7/site-packages/glue/__init__.py", line 125, in <module>
    from .qglue import qglue
  File "/home/gabriel/anaconda2/lib/python2.7/site-packages/glue/qglue.py", line 14, in <module>
    import numpy as np
  File "/home/gabriel/.local/lib/python2.7/site-packages/numpy/__init__.py", line 199, in <module>
    from . import random
  File "/home/gabriel/.local/lib/python2.7/site-packages/numpy/random/__init__.py", line 99, in <module>
    from .mtrand import *
ImportError: /home/gabriel/.local/lib/python2.7/site-packages/numpy/random/mtrand.so: undefined symbol: PyFPE_jbuf
````

Numpy is definitely installed.

**Comment by astrofrog** [comment]
@tswicegood - could you try installing ``glueviz`` from the ``conda-forge`` channel? It should be more up-to-date there and include all the correct dependencies:

```
conda install -c conda-forge glueviz
```
