### ISSUE TITLE
Launch Spyder from Windows Anaconda 64bits

### ISSUE THREAD

**Issue by jhazart** [ContinuumIO/anaconda-issues#290]
Hello,
when launching spyder (or spyder --reset), I get the error : 
Traceback (most recent call last):
  File "D:\dev\sw\Anaconda\Scripts\spyder-script.py", line 1, in <module>
    from spyderlib import start_app
  File "D:\dev\sw\Anaconda\lib\site-packages\spyderlib\start_app.py", line 13, in <module>
    from spyderlib.baseconfig import get_conf_path
  File "D:\dev\sw\Anaconda\lib\site-packages\spyderlib\baseconfig.py", line 188, in <module>
    from spyderlib.otherplugins import PLUGIN_PATH
  File "D:\dev\sw\Anaconda\lib\site-packages\spyderlib\otherplugins.py", line 17, in <module>
    from spyderlib.utils import programs
  File "D:\dev\sw\Anaconda\lib\site-packages\spyderlib\utils\programs.py", line 27, in <module>
    TEMPDIR = tempfile.gettempdir() + osp.sep + 'spyder'
  File "D:\dev\sw\Anaconda\lib\tempfile.py", line 269, in gettempdir
    tempdir = _get_default_tempdir()
  File "D:\dev\sw\Anaconda\lib\tempfile.py", line 200, in _get_default_tempdir
    with _io.open(fd, 'wb', closefd=False) as fp:
AttributeError: 'module' object has no attribute 'open'

Even when I reinstalled Anaconda I had the same problem. It worked a week ago.

Any clue ?
Thks

**Comment by ccordoba12** [comment]
It seems your Anaconda installation is corrupt somehow. Other than that, I don't know how to help you :-(

**Comment by goanpeca** [comment]
Closing for lack of activity.

Please reopen if you consider otherwise.

Thanks!
