### ISSUE TITLE
Anaconda Navigator Launch Issue

### ISSUE THREAD

**Issue by Sigurd922** [ContinuumIO/anaconda-issues#2901]
## Main error
An unexpected error occurred on Navigator start-up<br>'ascii' codec can't encode characters in position 24-27: ordinal not in range(128)
## Traceback
```
Traceback (most recent call last):
  File "E:\tools\anaconda\lib\site-packages\anaconda_navigator\exceptions.py", line 75, in exception_handler
    return_value = func(*args, **kwargs)
  File "E:\tools\anaconda\lib\site-packages\anaconda_navigator\app\start.py", line 115, in start_app
    window = run_app(splash)
  File "E:\tools\anaconda\lib\site-packages\anaconda_navigator\app\start.py", line 58, in run_app
    window = MainWindow(splash=splash)
  File "E:\tools\anaconda\lib\site-packages\anaconda_navigator\widgets\main_window.py", line 218, in __init__
    self.config.set('main', 'projects_path', None)
  File "E:\tools\anaconda\lib\site-packages\anaconda_navigator\config\user.py", line 454, in set
    self._save()
  File "E:\tools\anaconda\lib\site-packages\anaconda_navigator\config\user.py", line 121, in _save
    _write_file(fname)
  File "E:\tools\anaconda\lib\site-packages\anaconda_navigator\config\user.py", line 115, in _write_file
    self._write(configfile)
  File "E:\tools\anaconda\lib\site-packages\anaconda_navigator\config\user.py", line 92, in _write
    fp.write("{0}\n".format(key))
UnicodeEncodeError: 'ascii' codec can't encode characters in position 24-27: ordinal not in range(128)

```
## System information
```
platform: win-64
version: 1.6.2
conda: 4.3.21
qt: 5.6.2
language: zh_CN
python: 2.7.13
os: Windows;10;10.0.15063;AMD64;Intel64 Family 6 Model 158 Stepping 9, GenuineIntel
pyqt: 5

**Comment by goanpeca** [comment]
@Sigurd922 please reset navigator

Open a terminal:

```
$ anaconda-navigator --reset
```

**Comment by goanpeca** [comment]
Closing due to lack of response
