### ISSUE TITLE
'pip install simplejson' kills pip

### ISSUE THREAD

**Issue by scjody** [ContinuumIO/anaconda-issues#291]
Simply installing simplejson via `pip install simplejson` is enough to kill pip on a fresh install of Anaconda 2.1.0:

```
C:\Users\plotly\Anaconda>pip install simplejson
Downloading/unpacking simplejson
  Running setup.py (path:C:\Users\plotly\AppData\Local\Temp\pip_build_plotly\simplejson\setup.py) egg_info for package simplejson

Installing collected packages: simplejson
  Running setup.py install for simplejson
    building 'simplejson._speedups' extension
    C:\Users\plotly\Anaconda3\Scripts\gcc.bat -mdll -O -Wall -IC:\Users\plotly\Anaconda3\include -IC:\Users\plotly\Anaconda3\include
 -c simplejson/_speedups.c -o build\temp.win-amd64-3.4\Release\simplejson\_speedups.o
    C:\Users\plotly\Anaconda3\Scripts\gcc.bat -shared -s build\temp.win-amd64-3.4\Release\simplejson\_speedups.o build\temp.win-amd6
4-3.4\Release\simplejson\_speedups.def -LC:\Users\plotly\Anaconda3\libs -LC:\Users\plotly\Anaconda3\PCbuild\amd64 -lpython34 -lmsvcr
100 -o build\lib.win-amd64-3.4\simplejson\_speedups.pyd

Successfully installed simplejson
Cleaning up...

C:\Users\plotly\Anaconda>pip
Traceback (most recent call last):
  File "C:\Users\plotly\Anaconda3\Scripts\pip-script.py", line 3, in <module>
    from pip import main
  File "C:\Users\plotly\Anaconda3\lib\site-packages\pip\__init__.py", line 11, in <module>
    from pip.vcs import git, mercurial, subversion, bazaar  # noqa
  File "C:\Users\plotly\Anaconda3\lib\site-packages\pip\vcs\mercurial.py", line 9, in <module>
    from pip.download import path_to_url
  File "C:\Users\plotly\Anaconda3\lib\site-packages\pip\download.py", line 22, in <module>
    from pip._vendor import requests, six
  File "C:\Users\plotly\Anaconda3\lib\site-packages\pip\_vendor\requests\__init__.py", line 58, in <module>
    from . import utils
  File "C:\Users\plotly\Anaconda3\lib\site-packages\pip\_vendor\requests\utils.py", line 25, in <module>
    from .compat import parse_http_list as _parse_list_header
  File "C:\Users\plotly\Anaconda3\lib\site-packages\pip\_vendor\requests\compat.py", line 77, in <module>
    import simplejson as json
  File "C:\Users\plotly\Anaconda3\lib\site-packages\simplejson\__init__.py", line 112, in <module>
    from .scanner import JSONDecodeError
  File "C:\Users\plotly\Anaconda3\lib\site-packages\simplejson\scanner.py", line 10, in <module>
    c_make_scanner = _import_c_make_scanner()
  File "C:\Users\plotly\Anaconda3\lib\site-packages\simplejson\scanner.py", line 6, in _import_c_make_scanner
    from simplejson._speedups import make_scanner
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x83 in position 4: invalid start byte
```

Deleting simplejson will allow pip to work again, but there seems to be no way to install a working simplejson in Anaconda!

**Comment by Arttii** [comment]
My solution as to install it from here http://www.lfd.uci.edu/~gohlke/pythonlibs/#simplejson. pip install just does not work it seems
