### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by kevinwnag** [ContinuumIO/anaconda-issues#2922]
## Main error
Application <b>spyder</b> launch may have produced errors.
## Traceback
```
Traceback (most recent call last):
  File "/Users/kevinwang/anaconda/envs/kevin/lib/python3.5/site-packages/qtpy/QtWebEngineWidgets.py", line 22, in <module>
    from PyQt5.QtWebEngineWidgets import QWebEnginePage
ImportError: dlopen(/Users/kevinwang/anaconda/envs/kevin/lib/python3.5/site-packages/PyQt5/QtWebEngineWidgets.so, 2): Library not loaded: @rpath/libQt5WebEngineCore.5.dylib
  Referenced from: /Users/kevinwang/anaconda/envs/kevin/lib/python3.5/site-packages/PyQt5/QtWebEngineWidgets.so
  Reason: image not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/kevinwang/anaconda/envs/kevin/bin/spyder", line 6, in <module>
    sys.exit(spyder.app.start.main())
  File "/Users/kevinwang/anaconda/envs/kevin/lib/python3.5/site-packages/spyder/app/start.py", line 103, in main
    from spyder.app import mainwindow
  File "/Users/kevinwang/anaconda/envs/kevin/lib/python3.5/site-packages/spyder/app/mainwindow.py", line 92, in <module>
    from qtpy import QtWebEngineWidgets  # analysis:ignore
  File "/Users/kevinwang/anaconda/envs/kevin/lib/python3.5/site-packages/qtpy/QtWebEngineWidgets.py", line 26, in <module>
    from PyQt5.QtWebKitWidgets import QWebPage as QWebEnginePage
ImportError: No module named 'PyQt5.QtWebKitWidgets'

```
## System information
```
python: 3.6.1
language: en
os: Darwin;16.6.0;Darwin Kernel Version 16.6.0: Fri Apr 14 16:21:16 PDT 2017; root:xnu-3789.60.24~6/RELEASE_X86_64;x86_64;i386
version: 1.6.2
platform: osx-64
qt: 5.6.2
pyqt: 5.6.0
conda: 4.3.22
```

**Comment by goanpeca** [comment]
@ccordoba12 ?

**Comment by goanpeca** [comment]
Tracking on: https://github.com/ContinuumIO/anaconda-issues/issues/7230
