### ISSUE TITLE
Can't open spyder

### ISSUE THREAD

**Issue by IlDordollano** [ContinuumIO/anaconda-issues#2962]
## Main error
Application <b>spyder</b> launch may have produced errors.
## Traceback
```
Traceback (most recent call last):
  File "/home/damiano/Executable/anaconda3/lib/python3.6/site-packages/qtpy/QtWebEngineWidgets.py", line 22, in <module>
    from PyQt5.QtWebEngineWidgets import QWebEnginePage
ModuleNotFoundError: No module named 'PyQt5.QtWebEngineWidgets'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/damiano/Executable/anaconda3/bin/spyder", line 6, in <module>
    sys.exit(spyder.app.start.main())
  File "/home/damiano/Executable/anaconda3/lib/python3.6/site-packages/spyder/app/start.py", line 103, in main
    from spyder.app import mainwindow
  File "/home/damiano/Executable/anaconda3/lib/python3.6/site-packages/spyder/app/mainwindow.py", line 92, in <module>
    from qtpy import QtWebEngineWidgets  # analysis:ignore
  File "/home/damiano/Executable/anaconda3/lib/python3.6/site-packages/qtpy/QtWebEngineWidgets.py", line 26, in <module>
    from PyQt5.QtWebKitWidgets import QWebPage as QWebEnginePage
ImportError: libselinux.so.1: cannot open shared object file: No such file or directory

```
## System information
```
python: 3.6.1
language: en_US
os: Linux;4.9.32-31.lts;#1 SMP Thu Jun 22 04:35:56 UTC 2017;x86_64;
version: 1.6.2
platform: linux-64
qt: 5.6.2
pyqt: 5.6.0
conda: 4.3.22
```

**Comment by ccordoba12** [comment]
Please install `libselinux` using the package manager of your Linux distribution. That should fix your problem.
