### ISSUE TITLE
psutil access denied

### ISSUE THREAD

**Issue by kimpster** [ContinuumIO/anaconda-issues#2976]
An unexpected error occured on Navigator start-up
psutil.AccessDenied (pid=423)

 Tried updating conda, anaconda and anaconda navigator still did not work. Running python 2.7 

`Traceback (most recent call last):
File "/Users/Ryan/anaconda/lib/python2.7/site-packages/anaconda_navigator/exceptions.py", line 75, in exception_handler
return_value = func(*args, **kwargs)
File "/Users/Ryan/anaconda/lib/python2.7/site-packages/anaconda_navigator/app/start.py", line 108, in start_app
if misc.load_pid() is None: # A stale lock might be around
File "/Users/Ryan/anaconda/lib/python2.7/site-packages/anaconda_navigator/utils/misc.py", line 384, in load_pid
cmds = process.cmdline()
File "/Users/Ryan/anaconda/lib/python2.7/site-packages/psutil/__init__.py", line 701, in cmdline
return self._proc.cmdline()
File "/Users/Ryan/anaconda/lib/python2.7/site-packages/psutil/_psosx.py", line 306, in wrapper
raise AccessDenied(self.pid, self._name)
AccessDenied: psutil.AccessDenied (pid=423)
`

**Comment by kimpster** [comment]
duplicate of #1984 

Did not see the post initially
