### ISSUE TITLE
Error upon opening QTconsole, also when running iPython from command line. Windows 10, 64 bit OS

### ISSUE THREAD

**Issue by greydongilmore** [ContinuumIO/anaconda-issues#3032]
## Main error
Application <b>qtconsole</b> launch may have produced errors.
## Traceback
```
Error in sys.excepthook:
Traceback (most recent call last):
  File "C:\Users\Greydon\AppData\Roaming\Python\Python27\site-packages\qtconsole\qtconsoleapp.py", line 49, in gui_excepthook
    old_excepthook(exctype, value, tb)
TypeError: 'NoneType' object is not callable

Original exception was:
Traceback (most recent call last):
  File "C:\Users\Greydon\Anaconda2\Scripts\jupyter-qtconsole-script.py", line 3, in <module>
    import qtconsole.qtconsoleapp
  File "C:\Users\Greydon\AppData\Roaming\Python\Python27\site-packages\qtconsole\qtconsoleapp.py", line 64, in <module>
    from qtconsole.jupyter_widget import JupyterWidget
  File "C:\Users\Greydon\AppData\Roaming\Python\Python27\site-packages\qtconsole\jupyter_widget.py", line 19, in <module>
    from IPython.lib.lexers import IPythonLexer, IPython3Lexer
  File "C:\Users\Greydon\Anaconda2\lib\site-packages\IPython\__init__.py", line 48, in <module>
    from .core.application import Application
  File "C:\Users\Greydon\Anaconda2\lib\site-packages\IPython\core\application.py", line 25, in <module>
    from IPython.core import release, crashhandler
  File "C:\Users\Greydon\Anaconda2\lib\site-packages\IPython\core\crashhandler.py", line 28, in <module>
    from IPython.core import ultratb
  File "C:\Users\Greydon\Anaconda2\lib\site-packages\IPython\core\ultratb.py", line 128, in <module>
    from IPython.utils.terminal import get_terminal_size
  File "C:\Users\Greydon\Anaconda2\lib\site-packages\IPython\utils\terminal.py", line 22, in <module>
    from backports.shutil_get_te

**Comment by goanpeca** [comment]
@ccordoba12 ?

**Comment by ccordoba12** [comment]
This is an error in IPython, not in Qtconsole. I don't know why it's happening though.

Here you can find a possible solution

https://github.com/spyder-ide/spyder/issues/4605#issuecomment-312638657
