### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by mariolovric** [ContinuumIO/anaconda-issues#3060]
## Main error
Application <b>notebook</b> launch may have produced errors.
## Traceback
```
C:\Users\mlovric\AppData\Local\Continuum\Anaconda3\Lib\site-packages\IPython\nbformat.py:13: ShimWarning: The `IPython.nbformat` package has been deprecated since IPython 4.0. You should import from nbformat instead.
  "You should import from nbformat instead.", ShimWarning)
Traceback (most recent call last):
  File "C:\Users\mlovric\AppData\Local\Continuum\Anaconda3\Scripts\jupyter-notebook-script.py", line 3, in <module>
    import notebook.notebookapp
  File "C:\Users\mlovric\AppData\Local\Continuum\Anaconda3\lib\site-packages\notebook\notebookapp.py", line 76, in <module>
    from .services.contents.manager import ContentsManager
  File "C:\Users\mlovric\AppData\Local\Continuum\Anaconda3\lib\site-packages\notebook\services\contents\manager.py", line 16, in <module>
    from nbformat import sign, validate as validate_nb, ValidationError
ImportError: cannot import name 'sign'

```
## System information
```
python: 3.6.1
language: en_GB
os: Windows;10;10.0.15063;AMD64;Intel64 Family 6 Model 94 Stepping 3, GenuineIntel
version: 1.6.2
platform: win-64
qt: 5.6.2
pyqt: 5.6.0
conda: 4.3.21
```

**Comment by goanpeca** [comment]
@takluyver thoughts?

**Comment by takluyver** [comment]
You may have got a file called `nbformat.py` (or similar) which is shadowing the real nbformat module it's trying to import.

**Comment by mariolovric** [comment]
Thanks.

It happened after I tried to change the jupyter starting folder with 
    jupyter notebook --generate-config

However I reinstalled anaconda after this happened and didnt try to change the jupyter configuration file again.


KR
