### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by ZIP97** [ContinuumIO/anaconda-issues#3071]
## Main error
Application <b>xonsh</b> launch may have produced errors.
## Traceback
```
F:\Anaconda\lib\site-packages\win_unicode_console\__init__.py:31: RuntimeWarning: sys.stdin.encoding == 'utf-8', whereas sys.stdout.encoding == 'cp936', readline hook consumer may assume they are the same
  readline_hook.enable(use_pyreadline=use_pyreadline)
Traceback (most recent call last):
  File "F:\Anaconda\Scripts\xonsh-script.py", line 5, in <module>
    sys.exit(xonsh.main.main())
  File "F:\Anaconda\lib\site-packages\xonsh\__amalgam__.py", line 20488, in main
    _failback_to_other_shells(args, err)
  File "F:\Anaconda\lib\site-packages\xonsh\__amalgam__.py", line 20457, in _failback_to_other_shells
    raise err
  File "F:\Anaconda\lib\site-packages\xonsh\__amalgam__.py", line 20486, in main
    return main_xonsh(args)
  File "F:\Anaconda\lib\site-packages\xonsh\__amalgam__.py", line 20510, in main_xonsh
    print_welcome_screen()
  File "F:\Anaconda\lib\site-packages\xonsh\__amalgam__.py", line 15144, in print_welcome_screen
    termwidth = os.get_terminal_size().columns
OSError: [WinError 6] 句柄无效。

```
## System information
```
python: 3.6.1
language: zh_CN
os: Windows;7;6.1.7601;AMD64;Intel64 Family 6 Model 142 Stepping 9, GenuineIntel
version: 1.6.2
platform: win-64
qt: 5.6.2
pyqt: 5.6.0
conda: 4.3.21
```

**Comment by goanpeca** [comment]
test

**Comment by goanpeca** [comment]
Hi @ZIP97 thanks for reporting could you try launching Xonsh from the Anaconda Prompt (not from Navigator) to see if you can launch it or not?

Also if there is any traceback could you paste it?
