### ISSUE TITLE
#3203 Issue not resolved.

### ISSUE THREAD

**Issue by mushtaque87** [ContinuumIO/anaconda-issues#3204]
I did 
sudo conda update anaconda-navigator
Password:
Fetching package metadata .........
Solving package specifications: .

 All requested packages already installed.
 packages in environment at /Users/philips/anaconda:

anaconda-navigator        1.6.3                    py27_0  

#I did this But I get this new error and there is no report button also 

Traceback (most recent call last):
File "/Users/philips/anaconda/lib/python2.7/site-packages/anaconda_navigator/exceptions.py", line 75, in exception_handler
return_value = func(*args, **kwargs)
File "/Users/philips/anaconda/lib/python2.7/site-packages/anaconda_navigator/app/start.py", line 108, in start_app
if misc.load_pid() is None: # A stale lock might be around
File "/Users/philips/anaconda/lib/python2.7/site-packages/anaconda_navigator/utils/misc.py", line 384, in load_pid
cmds = process.cmdline()
File "/Users/philips/anaconda/lib/python2.7/site-packages/psutil/init.py", line 701, in cmdline
return self._proc.cmdline()
File "/Users/philips/anaconda/lib/python2.7/site-packages/psutil/_psosx.py", line 306, in wrapper
raise AccessDenied(self.pid, self._name)
AccessDenied: psutil.AccessDenied (pid=4795)

**Comment by goanpeca** [comment]
Closing as duplicate. Read information on issue #1984

---

Please update to the latest version of Navigator.

on the terminal type

```
$ conda update anaconda-navigator
```
