### ISSUE TITLE
platform.python_version() is broken in anaconda python on Linux

### ISSUE THREAD

**Issue by aldanor** [ContinuumIO/anaconda-issues#33]
This is the original `platform.py` ([see here](https://github.com/python/cpython/blob/237284d0a73e472f836adc72f090432ae7c5dfad/Lib/platform.py#L1175)):

``` python
_sys_version_parser = re.compile(
    r'([\w.+]+)\s*'
    '\(#?([^,]+),\s*([\w ]+),\s*([\w :]+)\)\s*'
    '\[([^\]]+)\]?', re.ASCII)
```

This is the same piece of `platform.py` from anaconda installation (notice the "version extra" part):

``` python
_sys_version_parser = re.compile(
    r'([\w.+]+)\s*'
    '\|[^|]*\|\s*' # version extra
    '\(#?([^,]+),\s*([\w ]+),\s*([\w :]+)\)\s*'
    '\[([^\]]+)\]?')
```

Because of the (non-optional) "extra" part, this breaks `platform.python_version()` on Linux and subsequently some distutils routines:

``` bash
$ which python
/home/smirnov/anaconda/bin/python

$ python
Python 2.7.5 (default, Aug  5 2013, 11:01:47)
[GCC 4.3.4 [gcc-4_3-branch revision 152973]] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import platform
>>> platform.python_version()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/smirnov/anaconda/lib/python2.7/platform.py", line 1496, in python_version
    return _sys_version()[1]
  File "/home/smirnov/anaconda/lib/python2.7/platform.py", line 1451, in _sys_version
    repr(sys_version))
ValueError: failed to parse CPython sys.version: '2.7.5 (default, Aug  5 2013, 11:01:47) \n[GCC 4.3.4 [gcc-4_3-branch revision 152973]]'
>>>
```

On Windows, the `sys.version` seems to be populated correctly, hence it doesn't fail:

``` bash
> python
Python 2.7.5 |Anaconda 1.6.2 (64-bit)| (default, Jul 1, 2013, 12:37:52) [MSC v.1500 64 bit (AMD 64)] on win32
```

**Comment by asmeurer** [comment]
This has also been reported at https://github.com/conda/conda/issues/1215, which doesn't look like LD_LIBRARY_PATH (it's Windows) or virtualenv.

**Comment by mvdoc** [comment]
@aldanor: I got this same problem trying to run tox with conda. Any hope you'll publish your workaround?
thanks!

**Comment by andrewbolster** [comment]
Getting what I believe is the same issue 

```
➜   conda update anaconda 
Warning: could not import binstar_client (failed to parse CPython sys.version: '2.7.10 |Anaconda 2.3.0 (64-bit)| (default, May 28 2015, 17:02:03) \n[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)]')Fetching package metadata: An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.


Traceback (most recent call last):
  File "/home/bolster/anaconda/bin/conda", line 5, in <module>
    sys.exit(main())
  File "/home/bolster/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 201, in main
    args_func(args, p)
  File "/home/bolster/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 208, in args_func
    args.func(args, p)
  File "/home/bolster/anaconda/lib/python2.7/site-packages/conda/cli/common.py", line 612, in inner
    return func(args, parser)
  File "/home/bolster/anaconda/lib/python2.7/site-packages/conda/cli/main_update.py", line 39, in execute
    install.install(args, parser, 'update')
  File "/home/bolster/anaconda/lib/python2.7/site-packages/conda/cli/install.py", line 255, in install
    offline=args.offline)
  File "/home/bolster/anaconda/lib/python2.7/site-packages/conda/cli/common.py", line 549, in get_index_trap
    return get_index(*args, **kwargs)
  File "/home/bolster/anaconda/lib/python2.7/site-packages/conda/api.py", line 42, in get_index
    unknown=unknown)
  File "/home/bolster/anaconda/lib/python2.7/site-packages/conda/utils.py", line 119, in __call__
    value = self.func(*args, **kw)
  File "/home/bolster/anaconda/lib/python2.7/site-packages/conda/fetch.py", line 228, in fetch_index
    session = CondaSession()
  File "/home/bolster/anaconda/lib/python2.7/site-packages/conda/connection.py", line 59, in __init__
    super(CondaSession, self).__init__(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 287, in __init__
    self.headers = default_headers()
  File "/usr/local/lib/python2.7/dist-packages/requests/utils.py", line 563, in default_headers
    'User-Agent': default_user_agent(),
  File "/usr/local/lib/python2.7/dist-packages/requests/utils.py", line 532, in default_user_agent
    _implementation = platform.python_implementation()
  File "/usr/lib/python2.7/platform.py", line 1521, in python_implementation
    return _sys_version()[0]
  File "/usr/lib/python2.7/platform.py", line 1486, in _sys_version
    repr(sys_version))
ValueError: failed to parse CPython sys.version: '2.7.10 |Anaconda 2.3.0 (64-bit)| (default, May 28 2015, 17:02:03) \n[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)]'
```

output of `ldd`

```
	linux-vdso.so.1 =>  (0x00007ffd8cefb000)
	libpython2.7.so.1.0 => /home/bolster/anaconda/bin/../lib/libpython2.7.so.1.0 (0x00007f252dd66000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f252db48000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f252d944000)
	libutil.so.1 => /lib/x86_64-linux-gnu/libutil.so.1 (0x00007f252d741000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f252d439000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f252d06f000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f252e149000)
```

**Comment by jbpoline** [comment]
looks like others (including me) are having the same issue - see issue  #394

**Comment by DanielTakeshi** [comment]
Did any of you come up with a solution for this? I don't have LD_LIBRARY_PATH set up so I don't think that's the issue. My output looks like the output from @andrewbolster . Were you able to find a fix / workaround?

**Comment by jbpoline** [comment]
Hi,

My issue was solved after removing all .pth files from easy installs. I
then did a script to remove the anaconda path when deactivating the
environment.

cheers
JB

**Comment by DanielTakeshi** [comment]
Thanks for the response. I'm not sure how to do what you suggested but seems like someone has another idea here:

http://stackoverflow.com/questions/34145861/valueerror-failed-to-parse-cpython-sys-version-after-using-conda-command

In any case, it seems like this is still a bug with *some* code, right? I'm not seeing how anything is resolved yet.

**Comment by hal98x** [comment]
I recently ran conda to install a package. It updated the conda environment and Python from 2.7.10 -> 2.7.11. now when I run conda or spyder I get the Value Error reported here.  I can run platform. python_version() and get the value error.  I am running on Windows, Anaconda distribution,

**Comment by TimCraigGenia** [comment]
I'm having this error on mac, it prevents me from even uninstalling anaconda.  Pretty annoying.

**Comment by mingwandroid** [comment]
We released a new `virtualenv` package with patches to allow it to find the correct libpython. Please test and close this if it works for you.

**Comment by goanpeca** [comment]
Closing due to lack of response

**Comment by dcmoyer** [comment]
I installed anaconda on a system with several pre-existing python installs on it, one of which was included in the `PYTHONPATH` variable. Changing this variable resolved my version of this error, which was also a complaint about an incoherent sys.version string.

Apologies for thread resurrection.
