### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by Anupam13** [ContinuumIO/anaconda-issues#3389]
## Main error
Application <b>spyder</b> launch may have produced errors.
## Traceback
```
Traceback (most recent call last):
  File "C:\Users\anupam\Anaconda3\Scripts\spyder-script.py", line 5, in <module>
    sys.exit(spyder.app.start.main())
  File "C:\Users\anupam\Anaconda3\lib\site-packages\spyder\app\start.py", line 103, in main
    from spyder.app import mainwindow
  File "C:\Users\anupam\Anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 165, in <module>
    from spyder.utils.environ import WinUserEnvDialog
  File "C:\Users\anupam\Anaconda3\lib\site-packages\spyder\utils\environ.py", line 20, in <module>
    from spyder.widgets.variableexplorer.collectionseditor import CollectionsEditor
  File "C:\Users\anupam\Anaconda3\lib\site-packages\spyder\widgets\variableexplorer\collectionseditor.py", line 46, in <module>
    from spyder.widgets.variableexplorer.importwizard import ImportWizard
  File "C:\Users\anupam\Anaconda3\lib\site-packages\spyder\widgets\variableexplorer\importwizard.py", line 26, in <module>
    import pandas as pd
  File "C:\Users\anupam\Anaconda3\lib\site-packages\pandas\__init__.py", line 51, in <module>
    plot_params = pandas.plotting._style._Options(deprecated=True)
AttributeError: module 'pandas' has no attribute 'plotting'

```
## System information
```
python: 3.6.1
language: en_IN
os: Windows;10;10.0.14393;AMD64;Intel64 Family 6 Model 61 Stepping 4, GenuineIntel
version: 1.6.2
platform: win-64
qt: 5.6.2
pyqt: 5.6.0
conda: 4.3.21
```
**The spyder launch is producing these errors and thus can't open the application  **

**Comment by goanpeca** [comment]
Please reinstall pandas

```
conda install pandas --force
```
