### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by dservais** [ContinuumIO/anaconda-issues#3402]
## Main error
Application <b>glueviz</b> launch may have produced errors.
## Traceback
```
Traceback (most recent call last):
  File "C:\Users\serva\AppData\Roaming\Python\Python36\site-packages\numpy\core\__init__.py", line 16, in <module>
    from . import multiarray
ImportError: cannot import name 'multiarray'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\serva\Anaconda3\Scripts\glue-script.py", line 3, in <module>
    import glue.main
  File "C:\Users\serva\Anaconda3\lib\site-packages\glue\__init__.py", line 125, in <module>
    from .qglue import qglue
  File "C:\Users\serva\Anaconda3\lib\site-packages\glue\qglue.py", line 14, in <module>
    import numpy as np
  File "C:\Users\serva\AppData\Roaming\Python\Python36\site-packages\numpy\__init__.py", line 142, in <module>
    from . import add_newdocs
  File "C:\Users\serva\AppData\Roaming\Python\Python36\site-packages\numpy\add_newdocs.py", line 13, in <module>
    from numpy.lib import add_newdoc
  File "C:\Users\serva\AppData\Roaming\Python\Python36\site-packages\numpy\lib\__init__.py", line 8, in <module>
    from .type_check import *
  File "C:\Users\serva\AppData\Roaming\Python\Python36\site-packages\numpy\lib\type_check.py", line 11, in <module>
    import numpy.core.numeric as _nx
  File "C:\Users\serva\AppData\Roaming\Python\Python36\site-packages\numpy\core\__init__.py", line 26, in <module>
    raise ImportError(msg)
ImportError: 
Importing the multiarray numpy extension module failed.  Most
likely you are trying

**Comment by dservais** [comment]
Hello,
I'm using anaconda3 and by installing Orange I just got this message.
Best regards

**Comment by alimp5** [comment]
OS: Kali Linux - full upgraded
OS Version 64 bit
App version: Anaconda34.4.0linuxx8664.sh


Navigator Error

An unexpected error occurred on Navigator start-up
Report

Please report this issue in the anaconda issue tracker
Main Error

byte indices must be integers or slices, not str

Traceback

Traceback (most recent call last):
  File "/root/anaconda3/lib/python3.6/site-packages/anaconda_navigator/exceptions.py", line 75, in exception_handler
    return_value = func(*args, **kwargs)
  File "/root/anaconda3/lib/python3.6/site-packages/anaconda_navigator/app/start.py", line 115, in start_app
    window = run_app(splash)
  File "/root/anaconda3/lib/python3.6/site-packages/anaconda_navigator/app/start.py", line 58, in run_app
    window = MainWindow(splash=splash)
  File "/root/anaconda3/lib/python3.6/site-packages/anaconda_navigator/widgets/main_window.py", line 160, in __init__
    self.api = AnacondaAPI()
  File "/root/anaconda3/lib/python3.6/site-packages/anaconda_navigator/api/anaconda_api.py", line 1205, in AnacondaAPI
    ANACONDA_API = _AnacondaAPI()
  File "/root/anaconda3/lib/python3.6/site-packages/anaconda_navigator/api/anaconda_api.py", line 65, in __init__
    self._conda_api = CondaAPI()
  File "/root/anaconda3/lib/python3.6/site-packages/anaconda_navigator/api/conda_api.py", line 1622, in CondaAPI
    CONDA_API = _CondaAPI()
  File "/root/anaconda3/lib/python3.6/site-packages/anaconda_navigator/api/conda_api.py", line 340, in __init__
    self.set_conda_prefix()
  File "/root/anaconda3/lib/python3.6/site-packages/anaconda_navigator/api/conda_api.py", line 489, in set_conda_prefix
    self.ROOT_PREFIX = info['root_prefix']
TypeError: byte indices must be integers or slices, not str

How to run Anaconda GUI interface in Linux !!??
Where is the problem !!??

**Comment by goanpeca** [comment]
@dservais could you reinstall numpy from the command line and try again?

Also could you run orange3 from terminal and paste the full stack trace
