### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by iApparate** [ContinuumIO/anaconda-issues#3466]
## Main error
Application <b>spyder</b> launch may have produced errors.
## Traceback
```
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 3011, in main
    mainwindow = run_spyder(app, options, args)
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 2913, in run_spyder
    main.setup()
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 785, in setup
    self.help = Help(self)
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\plugins\help.py", line 465, in __init__
    html_text_no_doc=warning(self.no_doc_string))
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\utils\help\sphinxify.py", line 76, in warning
    warning = env.get_template("warning.html")
  File "C:\ProgramData\Anaconda3\lib\site-packages\jinja2\environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "C:\ProgramData\Anaconda3\lib\site-packages\jinja2\environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "C:\ProgramData\Anaconda3\lib\site-packages\jinja2\loaders.py", line 113, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "C:\ProgramData\Anaconda3\lib\site-packages\jinja2\loaders.py", line 175, in get_source
    contents = f.read().decode(self.encoding)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xbb in position 217156: invalid start byte

```
## System information
```
python:

**Comment by goanpeca** [comment]
@ccordoba12 ?
