### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by taxkmj** [ContinuumIO/anaconda-issues#3469]
## Main error
Application <b>spyder</b> launch may have produced errors.
## Traceback
```
Traceback (most recent call last):
  File "C:\Anaconda3\lib\site-packages\qtpy\__init__.py", line 119, in <module>
    from PySide import __version__ as PYSIDE_VERSION  # analysis:ignore
ModuleNotFoundError: No module named 'PySide'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Anaconda3\Scripts\spyder-script.py", line 5, in <module>
    sys.exit(spyder.app.start.main())
  File "C:\Anaconda3\lib\site-packages\spyder\app\start.py", line 103, in main
    from spyder.app import mainwindow
  File "C:\Anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 49, in <module>
    requirements.check_qt()
  File "C:\Anaconda3\lib\site-packages\spyder\requirements.py", line 39, in check_qt
    import qtpy
  File "C:\Anaconda3\lib\site-packages\qtpy\__init__.py", line 125, in <module>
    raise PythonQtError('No Qt bindings could be found')
qtpy.PythonQtError: No Qt bindings could be found

```
## System information
```
python: 3.5.3
qt: 5.6.2
platform: win-64
conda: 4.3.22
version: 1.6.2
os: Windows;10;10.0.15063;AMD64;Intel64 Family 6 Model 158 Stepping 9, GenuineIntel
language: ko_KR
pyqt: 5.6.0
```

**Comment by goanpeca** [comment]
We do not support pyside, so we advice you ue PyQt for qt bindings.
