### ISSUE TITLE
mpl 1.1.1 does not have right libpng out of the box

### ISSUE THREAD

**Issue by tacaswell** [ContinuumIO/anaconda-issues#357]
Installing matplotlib 1.1.1 pulling is libpng 1.5.13, but is built against libpng 1.2.50.  Forcibly down-grading libpng fixes the problem.

I assume this is a low priority, but felt compelled to report it anyway.

```
23:08 $ conda create -p /tmp/mpl_stock matplotlib=1.1.1
Fetching package metadata: ......
Solving package specifications: ...................
Package plan for installation in environment /tmp/mpl_stock:

The following NEW packages will be INSTALLED:

    cairo:      1.12.18-0        (soft-link)
    dateutil:   2.4.1-py27_0     (soft-link)
    freetype:   2.4.10-0         (soft-link)
    libpng:     1.5.13-1         (soft-link)
    matplotlib: 1.1.1-np17py27_1 (soft-link)
    ncurses:    5.9-5            (soft-link)
    numpy:      1.7.1-py27_2     (soft-link)
    openssl:    1.0.1k-1         (soft-link)
    pixman:     0.26.2-0         (soft-link)
    py2cairo:   1.10.0-py27_2    (soft-link)
    python:     2.7.10-0         (soft-link)
    pytz:       2015.4-py27_0    (soft-link)
    readline:   6.2.5-1          (soft-link)
    six:        1.9.0-py27_0     (soft-link)
    sqlite:     3.8.4.1-1        (soft-link)
    system:     5.8-2            (soft-link)
    tk:         8.5.18-0         (soft-link)
    zlib:       1.2.8-0          (soft-link)

Proceed ([y]/n)? y

Linking packages ...
[      COMPLETE      ]|##################################################################################################################################################################################################################################################| 100%
#
# To activate this environment, use:
# $ source activate /tmp/mpl_stock
#
# To deactivate this environment, use:
# $ source deactivate
#
✔ ~/source 
23:08 $ source activate /tmp/mpl_stock
discarding /home/tcaswell/mc/bin from PATH
prepending /tmp/mpl_stock/bin to PATH
(mpl_stock) ✔ ~/source 
23:08 $ python
Python 2.7.10 |Continuum Analytics, Inc.| (default, May 28 2015, 17:02:03) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://binstar.org
>>> import matplotlib.pyplot as plt
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/tmp/mpl_stock/lib/python2.7/site-packages/matplotlib/pyplot.py", line 23, in <module>
    from matplotlib.figure import Figure, figaspect
  File "/tmp/mpl_stock/lib/python2.7/site-packages/matplotlib/figure.py", line 18, in <module>
    from axes import Axes, SubplotBase, subplot_class_factory
  File "/tmp/mpl_stock/lib/python2.7/site-packages/matplotlib/axes.py", line 14, in <module>
    import matplotlib.axis as maxis
  File "/tmp/mpl_stock/lib/python2.7/site-packages/matplotlib/axis.py", line 14, in <module>
    import matplotlib.text as mtext
  File "/tmp/mpl_stock/lib/python2.7/site-packages/matplotlib/text.py", line 31, in <module>
    from matplotlib.backend_bases import RendererBase
  File "/tmp/mpl_stock/lib/python2.7/site-packages/matplotlib/backend_bases.py", line 48, in <module>
    import matplotlib.textpath as textpath
  File "/tmp/mpl_stock/lib/python2.7/site-packages/matplotlib/textpath.py", line 9, in <module>
    from matplotlib.mathtext import MathTextParser
  File "/tmp/mpl_stock/lib/python2.7/site-packages/matplotlib/mathtext.py", line 52, in <module>
    import matplotlib._png as _png
ImportError: libpng12.so.0: cannot open shared object file: No such file or directory
>>> 
(mpl_stock) ✔ ~/source 
23:08 $ conda install libpng=1.2.50
Fetching package metadata: ......
Solving package specifications: .
Package plan for installation in environment /tmp/mpl_stock:

The following packages will be DOWNGRADED:

    libpng: 1.5.13-1 --> 1.2.50-0 (soft-link)

Proceed ([y]/n)? y

Unlinking packages ...
[      COMPLETE      ]|##################################################################################################################################################################################################################################################| 100%
Linking packages ...
[      COMPLETE      ]|##################################################################################################################################################################################################################################################| 100%
(mpl_stock) ✔ ~/source 
23:08 $ python
Python 2.7.10 |Continuum Analytics, Inc.| (default, May 28 2015, 17:02:03) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://binstar.org
>>> import matplotlib.pyplot
>>> 
```

**Comment by jnothman** [comment]
I haven't yet understood whether this is related to an issue I'm having trying to use a conda env with matplotlib within a Django/mod_wsgi setup. I'm getting an error identical to that reported at [SO](https://stackoverflow.com/questions/33497639/why-is-wsgi-looking-for-a-library-in-lib64-when-the-correct-version-is-in-the-p).

Somehow libpng is unlinked from libz when accessed through Apache/mod_wsgi.

When I run:
`ldd /path/to/miniconda3/lib/python3.6/site-packages/matplotlib/../../.././libpng16.so.16` in a shell, I get:
```
ldd /path/to/miniconda3/lib/python3.6/site-packages/matplotlib/../../.././libpng16.so.16
        linux-vdso.so.1 =>  (0x00007ffd02f8a000)
        libz.so.1 => /path/to/miniconda3/lib/python3.6/site-packages/matplotlib/../../../././libz.so.1 (0x00007f2882574000)
        libm.so.6 => /lib64/libm.so.6 (0x00007f28822e5000)
        libc.so.6 => /lib64/libc.so.6 (0x00007f2881f51000)
        /lib64/ld-linux-x86-64.so.2 (0x0000003965200000)
```
When I run it within my `wsgi.py` the lines for libz and libm disappear. I have little idea what this means, but it somehow causes libpng to try to link to the incorrect `/lib64/libz.so.1`.

As I said, I'm not sure if this is related to the above issue (probably not). I have failed to downgrade libpng (due to conflict with freetype) using conda install, but maybe there's another way. If it's not related, should I open a new anaconda issue?

**Comment by tacaswell** [comment]
Unless there is something about conda missing places to put the required metadata, I think an issue about the packaging issue for an ancient version of mpl can be safely closed!

**Comment by jnothman** [comment]
Okay, then I'll presume my current issue is distinct. I suppose I need to
work out how to raise it cleanly.
