### ISSUE TITLE
anaconda-python3.4 installer: spyder not working

### ISSUE THREAD

**Issue by jcrypto** [ContinuumIO/anaconda-issues#362]
Anaconda from the official python 3.4 package (Anaconda3-2.2.0-Linux-x86_64.sh, sha256sum 4aac68743e7706adb93f042f970373a6e7e087dbf4b02ac467c94ca4ce33d2d1) doesn't have a working spyder:

```
$ spyder 
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/lib/python3.4/site-packages/spyderlib/qt/__init__.py", line 46, in <module>
    from PySide import __version__  # analysis:ignore
ImportError: No module named 'PySide'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/lib/python3.4/site-packages/spyderlib/requirements.py", line 40, in check_qt
    from spyderlib import qt
  File "/home/ubuntu/anaconda3/lib/python3.4/site-packages/spyderlib/qt/__init__.py", line 48, in <module>
    raise ImportError("Spyder requires PySide or PyQt to be installed")
ImportError: Spyder requires PySide or PyQt to be installed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/bin/spyder", line 3, in <module>
    start_app.main()
  File "/home/ubuntu/anaconda3/lib/python3.4/site-packages/spyderlib/start_app.py", line 85, in main
    from spyderlib import spyder
  File "/home/ubuntu/anaconda3/lib/python3.4/site-packages/spyderlib/spyder.py", line 77, in <module>
    requirements.check_qt()
  File "/home/ubuntu/anaconda3/lib/python3.4/site-packages/spyderlib/requirements.py", line 50, in check_qt
    % (qt_infos['pyqt']+qt_infos['pyside']))
  File "/home/ubuntu/anaconda3/lib/python3.4/site-packages/spyderlib/requirements.py", line 25, in show_warning
    raise RuntimeError(message)
RuntimeError: Please check Spyder installation requirements:
PyQt4 4.6+ (or PySide 1.2.0+) is required.
```

**Comment by liubenyuan** [comment]
experience the same error.
```
PS C:\Windows\system32> conda.exe search pyside
Fetching package metadata: ..
pyside                       1.1.2                    py33_0  http://repo.continuum.io/pkgs/free/win-64/
                             1.1.2                    py27_0  http://repo.continuum.io/pkgs/free/win-64/
                             1.2.0                    py33_0  http://repo.continuum.io/pkgs/free/win-64/
                             1.2.0                    py27_0  http://repo.continuum.io/pkgs/free/win-64/
                          .  1.2.1                    py33_0  http://repo.continuum.io/pkgs/free/win-64/
                             1.2.1                    py27_0  http://repo.continuum.io/pkgs/free/win-64/
PS C:\Windows\system32> conda.exe install pyside
Fetching package metadata: ..
Solving package specifications: .........
Error: Unsatisfiable package specifications.
Generating hint:
[      COMPLETE      ]|##################################################| 100%


Hint: the following packages conflict with each other:
  - pyside
  - python 3.4*

Use 'conda info pyside' etc. to see the dependencies for each package.

Note that the following features are enabled:
  - vc10
```

**Comment by goanpeca** [comment]
We no longer support python 3.4
