### ISSUE TITLE
kernel dead issue

### ISSUE THREAD

**Issue by hhkang94** [ContinuumIO/anaconda-issues#3633]
## Main error
Application <b>notebook</b> launch may have produced errors.
## Traceback
```
[I 14:20:28.467 NotebookApp] The port 8888 is already in use, trying another port.
[I 14:20:28.612 NotebookApp] Serving notebooks from local directory: C:\Users\hhkang94
[I 14:20:28.612 NotebookApp] 0 active kernels 
[I 14:20:28.612 NotebookApp] The Jupyter Notebook is running at: http://localhost:8889/?token=483b1bfff547f824e28e355ab937907613c56e96f388bc27
[I 14:20:28.614 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 14:20:28.615 NotebookApp] 
    
    Copy/paste this URL into your browser when you connect for the first time,
    to login with a token:
        http://localhost:8889/?token=483b1bfff547f824e28e355ab937907613c56e96f388bc27
[I 14:20:29.743 NotebookApp] Accepting one-time-token-authenticated connection from ::1
[I 14:20:37.516 NotebookApp] Kernel started: 99d427a2-edf1-4847-9889-197217e691db
Traceback (most recent call last):
  File "C:\Users\hhkang94\AppData\Local\Continuum\Anaconda2\lib\runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "C:\Users\hhkang94\AppData\Local\Continuum\Anaconda2\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Users\hhkang94\AppData\Local\Continuum\Anaconda2\lib\site-packages\ipykernel_launcher.py", line 15, in <module>
    from ipykernel import kernelapp as app
  File "C:\Users\hhkang94\AppData\Local\Continuum\Anaconda2\lib\site-packages\ipykernel\__init__.py", line 2, in <module>
    from .connect import *
  File "C:\Users\hhkang94\AppData\Local\Continuum\Anaconda2\lib\site-pac

**Comment by csoja** [comment]
Unfortunately, this is not the right place to find help for Jupyter Notebook kernel issues.  I'd recommend https://github.com/jupyter/notebook/issues
