### ISSUE TITLE
Image not found when installing cryptography

### ISSUE THREAD

**Issue by chriddyp** [ContinuumIO/anaconda-issues#365]
I just upgraded `pip install requests` which upgraded pyOPenSSL and cryptography to `pyOpenSSL-0.15.1` `cryptography-0.9.1`

```
Collecting requests[security] (from plotly==1.7.0)
  Downloading requests-2.7.0-py2.py3-none-any.whl (470kB)
    100% |████████████████████████████████| 471kB 382kB/s 
Collecting six (from plotly==1.7.0)
  Downloading six-1.9.0-py2.py3-none-any.whl
Collecting pytz (from plotly==1.7.0)
  Downloading pytz-2015.4-py2.py3-none-any.whl (475kB)
    100% |████████████████████████████████| 475kB 569kB/s 
Collecting pyOpenSSL (from requests[security]->plotly==1.7.0)
  Downloading pyOpenSSL-0.15.1-py2.py3-none-any.whl (102kB)
    100% |████████████████████████████████| 106kB 2.3MB/s 
Collecting ndg-httpsclient (from requests[security]->plotly==1.7.0)
  Downloading ndg_httpsclient-0.4.0.tar.gz
Collecting pyasn1 (from requests[security]->plotly==1.7.0)
  Downloading pyasn1-0.1.8.tar.gz (75kB)
    100% |████████████████████████████████| 77kB 2.5MB/s 
Collecting cryptography>=0.7 (from pyOpenSSL->requests[security]->plotly==1.7.0)
  Downloading cryptography-0.9.1.tar.gz (302kB)
    100% |████████████████████████████████| 303kB 481kB/s 
Collecting idna (from cryptography>=0.7->pyOpenSSL->requests[security]->plotly==1.7.0)
  Downloading idna-2.0-py2.py3-none-any.whl (61kB)
    100% |████████████████████████████████| 61kB 864kB/s 
Collecting setuptools (from cryptography>=0.7->pyOpenSSL->requests[security]->plotly==1.7.0)
  Downloading setuptools-18.0.1-py2.py3-none-any.whl (461kB)
    100% |████████████████████████████████| 462kB 390kB/s 
Collecting enum34 (from cryptography>=0.7->pyOpenSSL->requests[security]->plotly==1.7.0)
  Downloading enum34-1.0.4.tar.gz
Collecting ipaddress (from cryptography>=0.7->pyOpenSSL->requests[security]->plotly==1.7.0)
  Downloading ipaddress-1.0.7-py27-none-any.whl
Collecting cffi>=0.8 (from cryptography>=0.7->pyOpenSSL->requests[security]->plotly==1.7.0)
  Downloading cffi-1.1.2.tar.gz (326kB)
    100% |████████████████████████████████| 327kB 469kB/s 
Collecting pycparser (from cffi>=0.8->cryptography>=0.7->pyOpenSSL->requests[security]->plotly==1.7.0)
  Downloading pycparser-2.14.tar.gz (223kB)
    100% |████████████████████████████████| 225kB 1.1MB/s 
Building wheels for collected packages: ndg-httpsclient, pyasn1, cryptography, enum34, cffi, pycparser
  Running setup.py bdist_wheel for ndg-httpsclient
  Stored in directory: /Users/Chelsea/Library/Caches/pip/wheels/30/85/40/a29750f9287fe119a10708580a73cfb16f51e5f9a820430a2d
  Running setup.py bdist_wheel for pyasn1
  Stored in directory: /Users/Chelsea/Library/Caches/pip/wheels/c4/c5/95/c73b6aecd3119583f44a299c290a2d94bc3f67ae38728af1ef
  Running setup.py bdist_wheel for cryptography
  Stored in directory: /Users/Chelsea/Library/Caches/pip/wheels/e8/30/96/8e41d49df58739c767c139b9bfb3b04fcf127af2471a54c73e
  Running setup.py bdist_wheel for enum34
  Stored in directory: /Users/Chelsea/Library/Caches/pip/wheels/d1/b2/2c/b51348698bd1921a226cf48d790b282d86fb4bcf9728afd6b3
  Running setup.py bdist_wheel for cffi
  Stored in directory: /Users/Chelsea/Library/Caches/pip/wheels/99/e7/9a/68b1c8ca6f6f92b5feebd4d9434f50712b84f6a66d1285ea21
  Running setup.py bdist_wheel for pycparser
  Stored in directory: /Users/Chelsea/Library/Caches/pip/wheels/c7/28/31/bac6d0b118c0bdcbf57f9219afdf2e624379c07efa6c769dbc
Successfully built ndg-httpsclient pyasn1 cryptography enum34 cffi pycparser
Installing collected packages: six, idna, pyasn1, setuptools, enum34, ipaddress, pycparser, cffi, cryptography, pyOpenSSL, ndg-httpsclient, requests, pytz, plotly
  Found existing installation: setuptools 17.0
    Uninstalling setuptools-17.0:
      Successfully uninstalled setuptools-17.0
  Running setup.py install for plotly
Successfully installed cffi-1.1.2 cryptography-0.9.1 enum34-1.0.4 idna-2.0 ipaddress-1.0.7 ndg-httpsclient-0.4.0 plotly-1.7.0 pyOpenSSL-0.15.1 pyasn1-0.1.8 pycparser-2.14 pytz-2015.4 requests-2.7.0 setuptools-18.0.1 six-1.9.0
```

Now, when I import `requests`, I get:

```
chelseas-mbp:my_project_folder Chelsea$ source venv/bin/activate
(venv)chelseas-mbp:my_project_folder Chelsea$ python
Python 2.7.5 (default, Mar  9 2014, 22:15:05) 
[GCC 4.2.1 Compatible Apple LLVM 5.0 (clang-500.0.68)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import requests
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/Chelsea/my_project_folder/venv/lib/python2.7/site-packages/requests/__init__.py", line 53, in <module>
    from .packages.urllib3.contrib import pyopenssl
  File "/Users/Chelsea/my_project_folder/venv/lib/python2.7/site-packages/requests/packages/urllib3/contrib/pyopenssl.py", line 53, in <module>
    import OpenSSL.SSL
  File "/Users/Chelsea/my_project_folder/venv/lib/python2.7/site-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import rand, crypto, SSL
  File "/Users/Chelsea/my_project_folder/venv/lib/python2.7/site-packages/OpenSSL/rand.py", line 11, in <module>
    from OpenSSL._util import (
  File "/Users/Chelsea/my_project_folder/venv/lib/python2.7/site-packages/OpenSSL/_util.py", line 7, in <module>
    binding = Binding()
  File "/Users/Chelsea/my_project_folder/venv/lib/python2.7/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 114, in __init__
    self._ensure_ffi_initialized()
  File "/Users/Chelsea/my_project_folder/venv/lib/python2.7/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 126, in _ensure_ffi_initialized
    cls._modules,
  File "/Users/Chelsea/my_project_folder/venv/lib/python2.7/site-packages/cryptography/hazmat/bindings/utils.py", line 31, in load_library_for_binding
    lib = ffi.verifier.load_library()
  File "/Users/Chelsea/my_project_folder/venv/lib/python2.7/site-packages/cffi/verifier.py", line 97, in load_library
    return self._load_library()
  File "/Users/Chelsea/my_project_folder/venv/lib/python2.7/site-packages/cffi/verifier.py", line 207, in _load_library
    return self._vengine.load_library()
  File "/Users/Chelsea/my_project_folder/venv/lib/python2.7/site-packages/cffi/vengine_cpy.py", line 155, in load_library
    raise ffiplatform.VerificationError(error)
cffi.ffiplatform.VerificationError: importing '/Users/Chelsea/my_project_folder/venv/lib/python2.7/site-packages/cryptography/_Cryptography_cffi_a269d620xd5c405b7.so': dlopen(/Users/Chelsea/my_project_folder/venv/lib/python2.7/site-packages/cryptography/_Cryptography_cffi_a269d620xd5c405b7.so, 2): Library not loaded: libssl.1.0.0.dylib
  Referenced from: /Users/Chelsea/my_project_folder/venv/lib/python2.7/site-packages/cryptography/_Cryptography_cffi_a269d620xd5c405b7.so
  Reason: image not found
```

yikes!

[From the cryptography installation instructions](https://cryptography.io/en/latest/installation/#building-cryptography-with-conda) it seems like I should've set my `DYLD_LIBRARY_PATH` before `pip install`ing.

What is the recommended way to `pip install requests --upgrade`? Is this a bug or known behavior?

Thanks for the help!

**Comment by chriddyp** [comment]
incorrect diagnosis, moved issue to here: https://github.com/pyca/pyopenssl/issues/290
