### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by sanketpatel91** [ContinuumIO/anaconda-issues#3663]
## Main error
Application <b>spyder</b> launch may have produced errors.
## Traceback
```
Traceback (most recent call last):
  File "C:\Users\uidg6828\AppData\Local\Continuum\Anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 3069, in main
    mainwindow = run_spyder(app, options, args)
  File "C:\Users\uidg6828\AppData\Local\Continuum\Anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 2969, in run_spyder
    main = MainWindow(options)
  File "C:\Users\uidg6828\AppData\Local\Continuum\Anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 338, in __init__
    from spyder.plugins.configdialog import (MainConfigPage,
  File "C:\Users\uidg6828\AppData\Local\Continuum\Anaconda3\lib\site-packages\spyder\plugins\configdialog.py", line 39, in <module>
    from spyder.widgets.sourcecode.codeeditor import CodeEditor
  File "C:\Users\uidg6828\AppData\Local\Continuum\Anaconda3\lib\site-packages\spyder\widgets\sourcecode\codeeditor.py", line 58, in <module>
    from spyder.widgets.sourcecode.base import TextEditBaseWidget
  File "C:\Users\uidg6828\AppData\Local\Continuum\Anaconda3\lib\site-packages\spyder\widgets\sourcecode\base.py", line 35, in <module>
    from spyder.widgets.mixins import BaseEditMixin
  File "C:\Users\uidg6828\AppData\Local\Continuum\Anaconda3\lib\site-packages\spyder\widgets\mixins.py", line 29, in <module>
    from spyder.py3compat import is_text_string, to_text_string, u
ImportError: cannot import name 'u'

```
## System information
```
python: 3.6.1
language: en_IN
os: Windows;7;6.1.7601;AMD64;Intel64 Family 6 Model 69 Stepp

**Comment by goanpeca** [comment]
@ccordoba12
