### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by aseemarora** [ContinuumIO/anaconda-issues#3753]
## Main error
Application <b>spyder</b> launch may have produced errors.
## Traceback
```
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\config\user.py", line 111, in _save
    _write_file(fname)
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\config\user.py", line 107, in _write_file
    with open(fname, 'w', encoding='utf-8') as configfile:
OSError: [Errno 22] Invalid argument: 'C:\\Users\\sania\\.spyder-py3\\spyder.ini'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\Scripts\spyder-script.py", line 5, in <module>
    sys.exit(spyder.app.start.main())
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\app\start.py", line 135, in main
    from spyder.app import mainwindow
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 112, in <module>
    from spyder.utils.qthelpers import qapplication, MENU_SEPARATOR
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\utils\qthelpers.py", line 26, in <module>
    from spyder.config.gui import get_shortcut
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\config\gui.py", line 168, in <module>
    set_default_color_scheme(_name, replace=False)
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\config\gui.py", line 164, in set_default_color_scheme
    set_color_scheme(name, sh.get_color_scheme(name), replace=replace)
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\config\gui.py", line 158, in s

**Comment by goanpeca** [comment]
@ccordoba12 ?
