### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by altuor** [ContinuumIO/anaconda-issues#3783]
## Main error
Application <b>notebook</b> launch may have produced errors.
## Traceback
```
[I 11:04:24.623 NotebookApp] Writing notebook server cookie secret to /run/user/1000/jupyter/notebook_cookie_secret
Traceback (most recent call last):
  File "/MyDocuments/Apps/anaconda3/bin/jupyter-notebook", line 6, in <module>
    sys.exit(notebook.notebookapp.main())
  File "/MyDocuments/Apps/anaconda3/lib/python3.6/site-packages/jupyter_core/application.py", line 267, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/MyDocuments/Apps/anaconda3/lib/python3.6/site-packages/traitlets/config/application.py", line 657, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-7>", line 2, in initialize
  File "/MyDocuments/Apps/anaconda3/lib/python3.6/site-packages/traitlets/config/application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "/MyDocuments/Apps/anaconda3/lib/python3.6/site-packages/notebook/notebookapp.py", line 1296, in initialize
    self.init_webapp()
  File "/MyDocuments/Apps/anaconda3/lib/python3.6/site-packages/notebook/notebookapp.py", line 1120, in init_webapp
    self.http_server.listen(port, self.ip)
  File "/MyDocuments/Apps/anaconda3/lib/python3.6/site-packages/tornado/tcpserver.py", line 142, in listen
    sockets = bind_sockets(port, address=address)
  File "/MyDocuments/Apps/anaconda3/lib/python3.6/site-packages/tornado/netutil.py", line 197, in bind_sockets
    sock.bind(sockaddr)
OSError: [Errno 99] Cannot assign requested address

```
## System information
```
python: 3.6.1
language: en_US
os: Linux;4.11.8-2-default;#1 SMP PREEMPT Thu Jun 29 14:37:33 UTC 2017 (42bd7a0);x86_64;x86_64
version: 1.6.2
platform: linux-64
qt: 5.6.2
pyqt: 5.6.0
conda: 4.3.23
```

**Comment by ingen0s** [comment]
Has anyone else been able to resolve this? This tends to stick from time to time.
