### ISSUE TITLE
Can't update, install or remove packages from Anaconda - Error log attached

### ISSUE THREAD

**Issue by dineshgit** [ContinuumIO/anaconda-issues#3852]
## Main error
The following errors occurred:
## Traceback
```
Traceback (most recent call last):
  File "C:\Toolkits\Anaconda3-4.2.0\lib\site-packages\conda\exceptions.py", line 632, in conda_exception_handler
    return_value = func(*args, **kwargs)
  File "C:\Toolkits\Anaconda3-4.2.0\lib\site-packages\conda\cli\main.py", line 137, in _main
    exit_code = args.func(args, p)
  File "C:\Toolkits\Anaconda3-4.2.0\lib\site-packages\conda\cli\main_remove.py", line 139, in execute
    prefix=prefix)
  File "C:\Toolkits\Anaconda3-4.2.0\lib\site-packages\conda\core\index.py", line 98, in get_index
    _supplement_index_with_prefix(index, prefix, known_channels)
  File "C:\Toolkits\Anaconda3-4.2.0\lib\site-packages\conda\core\index.py", line 32, in _supplement_index_with_prefix
    for dist, info in iteritems(linked_data(prefix)):
  File "C:\Toolkits\Anaconda3-4.2.0\lib\site-packages\conda\core\linked_data.py", line 115, in linked_data
    load_linked_data(prefix, dist_name, ignore_channels=ignore_channels)
  File "C:\Toolkits\Anaconda3-4.2.0\lib\site-packages\conda\core\linked_data.py", line 36, in load_linked_data
    rec = json.load(fi)
  File "C:\Toolkits\Anaconda3-4.2.0\lib\json\__init__.py", line 268, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "C:\Toolkits\Anaconda3-4.2.0\lib\json\__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "C:\Toolkits\Anaconda3-4.2.0\lib\json\decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Toolkits\Anaconda3-4.2.0\lib\json\decod

**Comment by goanpeca** [comment]
@kalefranz ?

**Comment by dineshgit** [comment]
![error image](https://user-images.githubusercontent.com/20434896/29155804-d1cedc1e-7dd0-11e7-9450-8dfb109206b3.JPG)

This is what I see on my  Jupyter notebook page as well. Does anyone have any solutions to this issue ? I'm not able to rely on the Anaconda system in my laptop because I can't install any new packages.  Any helpful suggestions will be appreciated.

**Comment by dineshgit** [comment]
Traceback (most recent call last): File "C:\Toolkits\Anaconda3-4.2.0\lib\site-packages\conda\exceptions.py", line 632, in conda_exception_handler return_value = func(*args, **kwargs) File "C:\Toolkits\Anaconda3-4.2.0\lib\site-packages\conda\cli\main.py", line 137, in _main exit_code = args.func(args, p) File "C:\Toolkits\Anaconda3-4.2.0\lib\site-packages\conda\cli\main_list.py", line 242, in execute show_channel_urls=context.show_channel_urls) File "C:\Toolkits\Anaconda3-4.2.0\lib\site-packages\conda\cli\main_list.py", line 172, in print_packages installed = linked(prefix) File "C:\Toolkits\Anaconda3-4.2.0\lib\site-packages\conda\core\linked_data.py", line 123, in linked return set(linked_data(prefix, ignore_channels=ignore_channels).keys()) File "C:\Toolkits\Anaconda3-4.2.0\lib\site-packages\conda\core\linked_data.py", line 115, in linked_data load_linked_data(prefix, dist_name, ignore_channels=ignore_channels) File "C:\Toolkits\Anaconda3-4.2.0\lib\site-packages\conda\core\linked_data.py", line 36, in load_linked_data rec = json.load(fi) File "C:\Toolkits\Anaconda3-4.2.0\lib\json\__init__.py", line 268, in load parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw) File "C:\Toolkits\Anaconda3-4.2.0\lib\json\__init__.py", line 319, in loads return _default_decoder.decode(s) File "C:\Toolkits\Anaconda3-4.2.0\lib\json\decoder.py", line 339, in decode obj, end = self.raw_decode(s, idx=_w(s, 0).end()) File "C:\Toolkits\Anaconda3-4.2.0\lib\json\decoder.py", line 357, in raw_decode raise JSONDecodeError("Expecting value", s, err.value) from None json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
