### ISSUE TITLE
Difficulties with Rasterio on OSX (Python 2.7.10)

### ISSUE THREAD

**Issue by raj-kesavan** [ContinuumIO/anaconda-issues#390]
I'm having a lot of difficulty working with Rasterio on OSX 10.10, with Python 2.7.10 - issues with .dylibs.

After 
```
conda create -n airborn rasterio
source activate airborn
python -c "import rasterio"
```
I get
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/raj.kesavan/anaconda/envs/airborn/lib/python2.7/site-packages/rasterio/__init__.py", line 8, in <module>
    from rasterio._base import eval_window, window_shape, window_index
ImportError: dlopen(/Users/raj.kesavan/anaconda/envs/airborn/lib/python2.7/site-packages/rasterio/_base.so, 2): Library not loaded: @rpath/./libhdf5_hl.9.dylib
  Referenced from: /Users/raj.kesavan/anaconda/envs/airborn/lib/libnetcdf.7.dylib
  Reason: image not found
```
I've tried almost every combination of h5netcdf, h5py, hdf4, hdf5, libnetcdf, geos, netcdf4, proj4, and gdal I can think of (various versions, installing some but not others, etc.) In general what will happen is the missing library keeps shifting to `libhdf5_hl.10.dylib` or `libgdal.1.dylib` or `libproj.0.dylib`, and fixing one (by installing one of the above packages) will cause another. Any advice?

**Comment by groutr** [comment]
Can you give the versions + build numbers of the packages you have installed in your `gdalbroken` environment?  You get this by activating the environment and posting the output of `conda list`

**Comment by raj-kesavan** [comment]
```
~ λ conda list -n gdalbroken
# packages in environment at /Users/raj.kesavan/anaconda/envs/gdalbroken:
#
curl                      7.43.0                        1
gdal                      2.0.0                np19py27_0
hdf5                      1.8.15.1                      1
krb5                      1.13.2                        0
libgdal                   2.0.0                         0
libnetcdf                 4.3.3.1                       1
numpy                     1.9.2                    py27_0
openssl                   1.0.1k                        1
pip                       7.1.0                    py27_0
python                    2.7.10                        0
pyyaml                    3.11                      <pip>
readline                  6.2                           2
setuptools                18.0.1                   py27_0
sqlite                    3.8.4.1                       1
tk                        8.5.18                        0
zlib                      1.2.8                         0
```

**Comment by groutr** [comment]
Do you have the `DYLD_LIBRARY_PATH` environment variable set?  If that is not set, could you try temporarily removing `osgeo` and `ioos` channels from your `.condarc` and see if the problem persists?

**Comment by raj-kesavan** [comment]
Should DYLD_LIBRARY_PATH be set or not set? Either way, I tried

```
DYLD_LIBRARY_PATH=/Users/raj.kesavan/anaconda/envs/gdalbroken/lib/
```
and got the same error (same with `DYLD_LIBRARY_PATH=`).

I removed everything but `default` from `.condarc` and make a new environment; same problem.

**Comment by starsk62** [comment]
Hello. i am having the same problem. can some body help me.
>>> import gdal
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/starsk/anaconda/envs/DV/lib/python2.7/site-packages/gdal.py", line 2, in <module>
    from osgeo.gdal import deprecation_warn
  File "/Users/starsk/anaconda/envs/DV/lib/python2.7/site-packages/osgeo/__init__.py", line 21, in <module>
    _gdal = swig_import_helper()
  File "/Users/starsk/anaconda/envs/DV/lib/python2.7/site-packages/osgeo/__init__.py", line 17, in swig_import_helper
    _mod = imp.load_module('_gdal', fp, pathname, description)
ImportError: dlopen(/Users/starsk/anaconda/envs/DV/lib/python2.7/site-packages/osgeo/_gdal.so, 2): Library not loaded: @rpath/./libhdf5_hl.9.dylib
  Referenced from: /Users/starsk/anaconda/envs/DV/lib/libnetcdf.7.dylib
  Reason: image not found
>>>
