### ISSUE TITLE
Errors at environment creation due to menuinst trying to create shortcuts. How to avoid this?

### ISSUE THREAD

**Issue by gansanay** [ContinuumIO/anaconda-issues#3903]
I'm using Miniconda 4.3.21 in the context of Gitlab project builds and tests that are distributed on gitlab runners: hosts are willing engineers who accept to receive building and testing tasks for software packages they don't use, which means that the process of building and testing on their computers should be as silent as possible.

On Windows hosts, the environment creation pauses a very long time after displaying `Creating environment PROJECT...`, and then I get the following errors:

```
INFO menuinst_win32:__init__(182): Menu: name: 'Anaconda${PY_VER} ${PLATFORM}', prefix: 'D:\Multi-Runner\builds\XXX\PROJECT\Miniconda2\envs\PROJECT', env_name: 'PROJECT', mode: 'None', used_mode: 'user'
INFO menuinst_win32:folder_path(73): WARNING: menuinst key: 'start'
                 path: 'C:\Windows\system32\config\systemprofile\AppData\Roaming\Microsoft\Windows\Start Menu\Programs'
     .. excepted with: 'PathNotVerifiableException' in knownfolders.py, implementing workarounds ..
INFO menuinst_win32:folder_path(98):      .. due to lack of 'check_other_mode' not picking
        non-excepting path of 'C:\ProgramData\Microsoft\Windows\Start Menu\Programs'
 in knownfolders.py
INFO menuinst_win32:folder_path(73): WARNING: menuinst key: 'quicklaunch'
                 path: 'C:\Windows\system32\config\systemprofile\AppData\Roaming\Microsoft\Internet Explorer\Quick Launch'
     .. excepted with: 'PathNotVerifiableException' in knownfolders.py, implementing workarounds ..
menuinst Exception:Traceback (most recent call last):
  File "D:\Multi-Runner\builds\XXX\PROJECT\Miniconda2\lib\site-packages\conda\gateways\disk\create.py", line 150, in make_menu
    menuinst.install(join(prefix, win_path_ok(file_path)), remove, prefix)
  File "D:\Multi-Runner\builds\XXX\PROJECT\Miniconda2\lib\site-packages\menuinst\__init__.py", line 66, in install
    _install(path, remove, prefix)
  File "D:\Multi-Runner\builds\XXX\PROJECT\Miniconda2\lib\site-packages\menuinst\__init__.py", line 40, in _install
    m = Menu(menu_name, prefix=prefix, env_name=env_name, mode=mode)
  File "D:\Multi-Runner\builds\XXX\PROJECT\Miniconda2\lib\site-packages\menuinst\win32.py", line 184, in __init__
    self.set_dir(name, self.prefix, env_name, used_mode)
  File "D:\Multi-Runner\builds\XXX\PROJECT\Miniconda2\lib\site-packages\menuinst\win32.py", line 213, in set_dir
    self.dir[k] = folder_path(mode, check_other_mode, k)
  File "D:\Multi-Runner\builds\XXX\PROJECT\Miniconda2\lib\site-packages\menuinst\win32.py", line 84, in folder_path
    path, exception = dirs_src[other_mode][key]
KeyError: u'quicklaunch'
INFO menuinst_win32:__init__(182): Menu: name: 'Anaconda${PY_VER} ${PLATFORM}', prefix: 'D:\Multi-Runner\builds\XXX\PROJECT\Miniconda2\envs\PROJECT', env_name: 'PROJECT', mode: 'None', used_mode: 'user'
INFO menuinst_win32:folder_path(73): WARNING: menuinst key: 'start'
                 path: 'C:\Windows\system32\config\systemprofile\AppData\Roaming\Microsoft\Windows\Start Menu\Programs'
     .. excepted with: 'PathNotVerifiableException' in knownfolders.py, implementing workarounds ..
INFO menuinst_win32:folder_path(98):      .. due to lack of 'check_other_mode' not picking
        non-excepting path of 'C:\ProgramData\Microsoft\Windows\Start Menu\Programs'
 in knownfolders.py
INFO menuinst_win32:folder_path(73): WARNING: menuinst key: 'quicklaunch'
                 path: 'C:\Windows\system32\config\systemprofile\AppData\Roaming\Microsoft\Internet Explorer\Quick Launch'
     .. excepted with: 'PathNotVerifiableException' in knownfolders.py, implementing workarounds ..
menuinst Exception:Traceback (most recent call last):
  File "D:\Multi-Runner\builds\XXX\PROJECT\Miniconda2\lib\site-packages\conda\gateways\disk\create.py", line 150, in make_menu
    menuinst.install(join(prefix, win_path_ok(file_path)), remove, prefix)
  File "D:\Multi-Runner\builds\XXX\PROJECT\Miniconda2\lib\site-packages\menuinst\__init__.py", line 66, in install
    _install(path, remove, prefix)
  File "D:\Multi-Runner\builds\XXX\PROJECT\Miniconda2\lib\site-packages\menuinst\__init__.py", line 40, in _install
    m = Menu(menu_name, prefix=prefix, env_name=env_name, mode=mode)
  File "D:\Multi-Runner\builds\XXX\PROJECT\Miniconda2\lib\site-packages\menuinst\win32.py", line 184, in __init__
    self.set_dir(name, self.prefix, env_name, used_mode)
  File "D:\Multi-Runner\builds\XXX\PROJECT\Miniconda2\lib\site-packages\menuinst\win32.py", line 213, in set_dir
    self.dir[k] = folder_path(mode, check_other_mode, k)
  File "D:\Multi-Runner\builds\XXX\PROJECT\Miniconda2\lib\site-packages\menuinst\win32.py", line 84, in folder_path
    path, exception = dirs_src[other_mode][key]
KeyError: u'quicklaunch'
```

Where do these errors come from?

Actually, I chose miniconda for having a lightweight conda distribution for these distributed builds: I would really like to avoid any impact of these miniconda installs on hosts start menus... How can I do this?

**Comment by mingwandroid** [comment]
These info messages are being displayed due to a bug in conda's logging system, pinging @kalefranz. They are telling you about a failure to create menu entries but you don't want them anyway so your goal is achieved.

**Comment by gansanay** [comment]
It didn't happen before, and the pause I mention is at least 1 minute long... that's why I need to prevent it from even trying.

**Comment by mingwandroid** [comment]
It's a new bug in conda's logging that was interdicted between when it did and didn't happen. Can you define 'before' more clearly.

The pause has nothing to do with these messages. They are just coincident.

The pauses are because creating environments in conda is a slow process.

**Comment by gansanay** [comment]
'before' was 4.3.8: we sticked to this version for some time because later ones had UnicodeDecodeError when installing qt

**Comment by Nikhil-Garakapati** [comment]
Executing transaction: \ DEBUG menuinst_win32:__init__(199): Menu: name: 'Anaconda${PY_VER} ${PLATFORM}', prefix: 'C:\Users\Public\Anaconda\envs\tensorflow', env_name: 'tensorflow', mode: 'None', used_mode: 'user'
DEBUG menuinst_win32:create(323): Shortcut cmd is C:\Users\Public\Anaconda\pythonw.exe, args are ['C:\\Users\\Public\\Anaconda\\cwp.py', 'C:\\Users\\Public\\Anaconda\\envs\\tensorflow', 'C:\\Users\\Public\\Anaconda\\envs\\tensorflow\\pythonw.exe', 'C:\\Users\\Public\\Anaconda\\envs\\tensorflow\\Scripts\\spyder-script.py']
| DEBUG menuinst_win32:create(323): Shortcut cmd is C:\Users\Public\Anaconda\python.exe, args are ['C:\\Users\\Public\\Anaconda\\cwp.py', 'C:\\Users\\Public\\Anaconda\\envs\\tensorflow', 'C:\\Users\\Public\\Anaconda\\envs\\tensorflow\\python.exe', 'C:\\Users\\Public\\Anaconda\\envs\\tensorflow\\Scripts\\spyder-script.py', '--reset']

I got this Debugging error while I was installing spyder in the virtual environment.
Can anyone check out with this and help me?

**Comment by rishi454** [comment]
While I installing Tensorflow below debug has been occurred . So kindly sort out this issue.

 DEBUG menuinst_win32:__init__(196): Menu: name: 'Anaconda${PY_VER} ${PLATFORM}', prefix: 'C:\Users\Shanvika\Anaconda3', env_name: 'None', mode: 'system', used_mode: 'system'
DEBUG menuinst_win32:create(320): Shortcut cmd is C:\Users\Shanvika\Anaconda3\pythonw.exe, args are ['C:\\Users\\Shanvika\\Anaconda3\\cwp.py', 'C:\\Users\\Shanvika\\Anaconda3', 'C:\\Users\\Shanvika\\Anaconda3\\pythonw.exe', 'C:\\Users\\Shanvika\\Anaconda3\\Scripts\\anaconda-navigator-script.py']
| DEBUG menuinst_win32:__init__(196): Menu: name: 'Anaconda${PY_VER} ${PLATFORM}', prefix: 'C:\Users\Shanvika\Anaconda3', env_name: 'None', mode: 'system', used_mode: 'system'
DEBUG menuinst_win32:create(320): Shortcut cmd is C:\Users\Shanvika\Anaconda3\python.exe, args are ['C:\\Users\\Shanvika\\Anaconda3\\cwp.py', 'C:\\Users\\Shanvika\\Anaconda3', 'C:\\Users\\Shanvika\\Anaconda3\\python.exe', 'C:\\Users\\Shanvika\\Anaconda3\\Scripts\\jupyter-notebook-script.py', '%USERPROFILE%']
/ DEBUG menuinst_win32:__init__(196): Menu: name: 'Anaconda${PY_VER} ${PLATFORM}', prefix: 'C:\Users\Shanvika\Anaconda3', env_name: 'None', mode: 'system', used_mode: 'system'
DEBUG menuinst_win32:create(320): Shortcut cmd is C:\Users\Shanvika\Anaconda3\pythonw.exe, args are ['C:\\Users\\Shanvika\\Anaconda3\\cwp.py', 'C:\\Users\\Shanvika\\Anaconda3', 'C:\\Users\\Shanvika\\Anaconda3\\pythonw.exe', 'C:\\Users\\Shanvika\\Anaconda3\\Scripts\\spyder-script.py']
- DEBUG menuinst_win32:create(320): Shortcut cmd is C:\Users\Shanvika\Anaconda3\python.exe, args are ['C:\\Users\\Shanvika\\Anaconda3\\cwp.py', 'C:\\Users\\Shanvika\\Anaconda3', 'C:\\Users\\Shanvika\\Anaconda3\\python.exe', 'C:\\Users\\Shanvika\\Anaconda3\\Scripts\\spyder-script.py', '--reset']
done

CondaError: Cannot link a source that does not exist. C:\Users\Shanvika\Anaconda3\Scripts\conda.exe
Running `conda clean --packages` may resolve your problem.

**Comment by ThomasBourgeois** [comment]
Same error here, that I have been having for the past 3 days no matter what I do. 
Last thing i did was : 
conda update --all --force-reinstall

When executing transaction i get : 
- DEBUG menuinst_win32:__init__(199): Menu: name: 'Anaconda${PY_VER} ${PLATFORM}', prefix: 'C:\Users\thomas.bourgeois\AppData\Local\Continuum\miniconda3\envs\immd', env_name: 'immd', mode: 'user', used_mode: 'user'
\ DEBUG menuinst_win32:create(323): Shortcut cmd is C:\Users\thomas.bourgeois\AppData\Local\Continuum\miniconda3\python.exe, args are ['C:\\Users\\thomas.bourgeois\\AppData\\Local\\Continuum\\miniconda3\\cwp.py', 'C:\\Users\\thomas.bourgeois\\AppData\\Local\\Continuum\\miniconda3\\envs\\immd', 'C:\\Users\\thomas.bourgeois\\AppData\\Local\\Continuum\\miniconda3\\envs\\immd\\python.exe', 'C:\\Users\\thomas.bourgeois\\AppData\\Local\\Continuum\\miniconda3\\envs\\immd\\Scripts\\jupyter-notebook-script.py', '%USERPROFILE%']
DEBUG menuinst_win32:__init__(199): Menu: name: 'Anaconda${PY_VER} ${PLATFORM}', prefix: 'C:\Users\thomas.bourgeois\AppData\Local\Continuum\miniconda3\envs\immd', env_name: 'immd', mode: 'user', used_mode: 'user'
DEBUG menuinst_win32:create(323): Shortcut cmd is C:\Users\thomas.bourgeois\AppData\Local\Continuum\miniconda3\python.exe, args are ['C:\\Users\\thomas.bourgeois\\AppData\\Local\\Continuum\\miniconda3\\cwp.py', 'C:\\Users\\thomas.bourgeois\\AppData\\Local\\Continuum\\miniconda3\\envs\\immd', 'C:\\Users\\thomas.bourgeois\\AppData\\Local\\Continuum\\miniconda3\\envs\\immd\\python.exe', 'C:\\Users\\thomas.bourgeois\\AppData\\Local\\Continuum\\miniconda3\\envs\\immd\\Scripts\\jupyter-notebook-script.py', '%USERPROFILE%']

**Comment by csteel45** [comment]
Any progress on this?

**Comment by kalyan678** [comment]
I am facing the same issue currently. Any update/progress on this issue?

**Comment by transientsd** [comment]
Maybe update conda can work, you could try.
