### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by jeffe-cpm** [ContinuumIO/anaconda-issues#4000]
I got this error when I launch jupyter notebook, Any idea how to fix that?

Win7 x64 SP1
Anaconda 4.4 with Python 3.6 64-bit
Jupyter 5.0.0

## Main error
Application <b>notebook</b> launch may have produced errors.
## Traceback
```
[W 17:04:07.179 NotebookApp] server_extensions is deprecated, use nbserver_extensions
[W 17:04:12.034 NotebookApp] Error loading server extension jupyter_nbextensions_configurator
    Traceback (most recent call last):
      File "C:\Users\JC\Anaconda3\lib\site-packages\notebook\notebookapp.py", line 1271, in init_server_extensions
        mod = importlib.import_module(modulename)
      File "C:\Users\JC\Anaconda3\lib\importlib\__init__.py", line 126, in import_module
        return _bootstrap._gcd_import(name[level:], package, level)
      File "<frozen importlib._bootstrap>", line 978, in _gcd_import
      File "<frozen importlib._bootstrap>", line 961, in _find_and_load
      File "<frozen importlib._bootstrap>", line 948, in _find_and_load_unlocked
    ModuleNotFoundError: No module named 'jupyter_nbextensions_configurator'
[I 17:04:12.442 NotebookApp] Serving notebooks from local directory: C:\Users\JC
[I 17:04:12.442 NotebookApp] 0 active kernels 
[I 17:04:12.442 NotebookApp] The Jupyter Notebook is running at: http://localhost:8888/?token=bf5df8de0468b3876a8b56c23d369dfc2edaa6d3c6f56a0a
[I 17:04:12.442 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 17:04:12.453 NotebookApp] 
    
    Copy/paste this URL into your browser when you connect for the first time,
    to login with a token:
        http://localhost:8888/?token=bf5df8de0468b3876a8b56c23d369dfc2edaa6d3c6f56a0a
[I 17:04:12.693 NotebookApp] Accepting one-time-token-authenticated connection from ::1
[W 17:04:13.463 Noteboo

**Comment by akshaybabloo** [comment]
Are you having problem accessing the link - `http://localhost:8888/?token=bf5df8de0468b3876a8b56c23d369dfc2edaa6d3c6f56a0a` with this error?
