### ISSUE TITLE
Installing fiona forces libgdal to update although it is then incompatible with gdal

### ISSUE THREAD

**Issue by jorisvandenbossche** [ContinuumIO/anaconda-issues#401]
As an example, I try here to create an environment with ``fiona`` but with ``gdal`` 1.11.2. This tries to install `libgdal` 2.0.0, but this is incompatible with the installed `gdal` version, leading to import errors.

```
C:\Users\vdbosscj>conda create -n test-fiona gdal=1.11.2 fiona
Fetching package metadata: ....
Solving package specifications: ...............
Warning: 2 possible package resolutions (only showing differing packages):
        [u'cligj-0.2.0-py27_0.tar.bz2', u'fiona-1.6.0-np19py27_0.tar.bz2', u'gda
l-1.11.2-np19py27_1.tar.bz2', u'libgdal-2.0.0-0.tar.bz2'],
        [u'cligj-0.1.0-py27_0.tar.bz2', u'fiona-1.5.1-np19py27_0.tar.bz2', u'gda
l-1.11.2-np19py27_4.tar.bz2', u'libgdal-1.11.2-2.tar.bz2'],

Package plan for installation in environment C:\Anaconda\envs\test-fiona:

The following NEW packages will be INSTALLED:

    click:      4.1-py27_0
    cligj:      0.2.0-py27_0
    curl:       7.43.0-1
    fiona:      1.6.0-np19py27_0
    gdal:       1.11.2-np19py27_1    <------------
    hdf5:       1.8.15.1-2
    krb5:       1.13.2-0
    libgdal:    2.0.0-0       <-----------
    libnetcdf:  4.3.3.1-2
    numpy:      1.9.2-py27_0
    pip:        7.1.0-py27_0
    python:     2.7.10-0
    setuptools: 18.0.1-py27_0
    six:        1.9.0-py27_0
    zlib:       1.2.8-0

Proceed ([y]/n)? n
```

**Comment by jorisvandenbossche** [comment]
Workaround seems to explicitly install an older version of fiona (fiona 1.5 will do)

**Comment by groutr** [comment]
This is because the latest version of fiona is compiled against libgdal 2.0.  If you want to use an older version of gdal, you will have to use a version of fiona that was compiled against that version of gdal.

**Comment by groutr** [comment]
I'm not sure why this is giving two possible resolutions.  The second resolution should be the correct one.

**Comment by groutr** [comment]
I think I know what is going on.  Fiona doesn't depend on the gdal python bindings, only on the gdal library.  The latest version of the fiona package was changed to reflect that.

**Comment by jorisvandenbossche** [comment]
Thanks for looking into it!

But doesn't the gdal python bindings depend on the gdal lib? So this should then raise a dependency error? (I would expect, when trying to install gdal=1.11.2 en fiona=1.6, to get a message about unresolvable dependencies)

**Comment by asmeurer** [comment]
The problem is that some old builds have invalid dependencies, so conda is picking them.

**Comment by bekozi** [comment]
I am able to get fiona to work with ``conda install fiona "libgdal<2.0"``. However, fiona is not yet 2.0-compliant (see https://github.com/Toblerity/Fiona/issues/259) and the default recipe should probably reflect this!

**Comment by jorisvandenbossche** [comment]
Can something be done about this? Installing `fiona` with conda still leads to incompatible versions and a non-working install.

Creating a freqh environment with python 3.4 and installin fiona: it installs `libgdal` 2.0.0, while fiona is not compatible with gdal 2, and leading to fiona not working:

```
C:\Users\vdbosscj>conda create -n test-fiona python=3.4
Fetching package metadata: ....
Solving package specifications: .
Package plan for installation in environment C:\Anaconda\envs\test-fiona:

The following NEW packages will be INSTALLED:

    pip:        7.1.2-py34_0
    python:     3.4.3-0
    setuptools: 18.4-py34_0
    wheel:      0.26.0-py34_1

Proceed ([y]/n)?

Linking packages ...
[      COMPLETE      ]|##################################################| 100%
#
# To activate this environment, use:
# > activate test-fiona
#

C:\Users\vdbosscj>activate test-fiona
Activating environment "test-fiona"...

[test-fiona] C:\Users\vdbosscj>conda install fiona
Fetching package metadata: ....
Solving package specifications: ...........
Package plan for installation in environment C:\Anaconda\envs\test-fiona:

The following NEW packages will be INSTALLED:

    click:     4.1-py34_0
    cligj:     0.2.0-py34_0
    curl:      7.43.0-1
    fiona:     1.6.0-np110py34_0
    hdf5:      1.8.15.1-vc10_3   [vc10]
    krb5:      1.13.2-0
    libgdal:   2.0.0-0
    libnetcdf: 4.3.3.1-3
    numpy:     1.10.1-py34_0
    six:       1.10.0-py34_0
    zlib:      1.2.8-vc10_2      [vc10]

Proceed ([y]/n)? y

Linking packages ...
[      COMPLETE      ]|##################################################| 100%

[test-fiona] C:\Users\vdbosscj>python
Python 3.4.3 |Continuum Analytics, Inc.| (default, Mar  6 2015, 12:06:10) [MSC v
.1600 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import fiona
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Anaconda\envs\test-fiona\lib\site-packages\fiona\__init__.py", line 7
5, in <module>
    from fiona.collection import Collection, BytesCollection, vsi_path
  File "C:\Anaconda\envs\test-fiona\lib\site-packages\fiona\collection.py", line
 7, in <module>
    from fiona.ogrext import Iterator, ItemsIterator, KeysIterator
ImportError: DLL load failed: The specified module could not be found.
>>>
```

**Comment by shoyer** [comment]
:+1: this has also been affecting us

**Comment by jjstarn-usgs** [comment]
I and my user group also are affected by this.

**Comment by ChrisBarker-NOAA** [comment]
It would be really nice to get this fixed. A summary:

Anaconda has upgraded to GDAL 2.*, which Fiona is not yet compatible with.

https://github.com/Toblerity/Fiona/issues/289 -- not it's not respovled yet :-)

Meanwhile, Anaconda has split out the python gdal bindings from the lib, which is a nice change, but it make a bit of a mess.

The "gdal" package is now the python bindings, which depend on "libgdal". So if you get teh latest "gdal", you now get both the python bindings and libgdal.

fiona 1.6.0 np110py27_0

now depends on libgdal 2.0.0

so it all installs fine -- but unfortunately, fiona 1.6 doesn't actually work with libgdal 2.* :-)

Of course the "proper" solution is to update Fiona, but in the meantime, could a fiona1.6 be build with latest numpy that depends on libgdal1.11.* ??

Which brings up the question -- can libgdal 1.11 and libgdal 2.* be installed at the same time, or do they clash? If they clash, then a libgdal2 package might be in order, so we could install then both at once.

**Comment by darribas** [comment]
+1 on getting it fixed!

**Comment by abjer** [comment]
Have the same problem!

**Comment by gaberosser** [comment]
Similar issue here on Windows 7. The fiona package fails to read some (but, weirdly, *not* all) shapefiles, returning an empty container. I can't afford to downgrade numpy due to other dependencies, so I'm a bit stuck right now.

**Comment by fmaussion** [comment]
Note that the ioos channel has temporarily fixed this:
https://github.com/ioos/conda-recipes/issues/623

**Comment by mhearne-usgs** [comment]
@fmaussion Your comment above says that the ioos channel has temporarily fixed this... how?  I tried the various commands in that thread, but none of them would allow me to install a working fiona on Python 3.x.

**Comment by fmaussion** [comment]
We have no problem with fiona on py2 or py3 since we install **all** our packages from the ioos channel, for example (in an empty environment):

`conda install -c ioos fiona geopandas matplotlib pyproj numpy rasterio xarray` 

A future install or upgrade from the standard conda channels might brake the chain, I don't know. But the above definitely works for us (we use it for our ci on linux, mac, and windows).

**Comment by mhearne-usgs** [comment]
@fmaussion - 
I am on a Mac: 10.10.5
conda version 4.0.5

I tried the following:
conda create --name py3exp python=3 -y
source activate py3exp
conda install -y -c ioos fiona geopandas matplotlib pyproj numpy rasterio xarray ipython

And then in ipython, I get the errors below.  I tried "conda create --name py3exp python=3.4", but got the same results.

Is anyone using the same version of OSX that I am?

In [1]: import fiona
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-cc872b235141> in <module>()
----> 1 import fiona

/Users/mhearne/anaconda/envs/py3exp/lib/python3.5/site-packages/fiona/__init__.py in <module>()
     70 from six import string_types
     71
---> 72 from fiona.collection import Collection, BytesCollection, vsi_path
     73 from fiona._drivers import driver_count, GDALEnv, supported_drivers
     74 from fiona.odict import OrderedDict

/Users/mhearne/anaconda/envs/py3exp/lib/python3.5/site-packages/fiona/collection.py in <module>()
      5 import sys
      6
----> 7 from fiona.ogrext import Iterator, ItemsIterator, KeysIterator
      8 from fiona.ogrext import Session, WritingSession
      9 from fiona.ogrext import (

ImportError: dlopen(/Users/mhearne/anaconda/envs/py3exp/lib/python3.5/site-packages/fiona/ogrext.cpython-35m-darwin.so, 2): Library not loaded: /usr/local/lib/libjson-c.2.dylib
  Referenced from: /Users/mhearne/anaconda/envs/py3exp/lib/libgdal.1.dylib
  Reason: image not found

**Comment by jorisvandenbossche** [comment]
@mhearne-usgs Can you try with the `conda-forge` channel instead of `ioos`? I think from now on the packages will be updated more at that place, and I know they recently fixed an issue for fiona/gdal on OSX.

If you still get errors, best to report an issue at https://github.com/conda-forge/fiona-feedstock/issues

**Comment by fmaussion** [comment]
Aha, ok. Travis CI uses OS X 10.9.5

I heard from one of our users that it might not work on mac, I now recall.
