### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by apolloyyu** [ContinuumIO/anaconda-issues#4010]
## Main error
Application <b>spyder</b> launch may have produced errors.
## Traceback
```
Traceback (most recent call last):
  File "C:\Users\Apollo\Anaconda3\lib\site-packages\qtpy\QtWebEngineWidgets.py", line 22, in <module>
    from PyQt5.QtWebEngineWidgets import QWebEnginePage
ModuleNotFoundError: No module named 'PyQt5.QtWebEngineWidgets'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Apollo\Anaconda3\Scripts\spyder-script.py", line 5, in <module>
    sys.exit(spyder.app.start.main())
  File "C:\Users\Apollo\Anaconda3\lib\site-packages\spyder\app\start.py", line 103, in main
    from spyder.app import mainwindow
  File "C:\Users\Apollo\Anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 92, in <module>
    from qtpy import QtWebEngineWidgets  # analysis:ignore
  File "C:\Users\Apollo\Anaconda3\lib\site-packages\qtpy\QtWebEngineWidgets.py", line 26, in <module>
    from PyQt5.QtWebKitWidgets import QWebPage as QWebEnginePage
ImportError: DLL load failed: 找不到指定的程序。

```
## System information
```
python: 3.6.1
language: zh_CN
os: Windows;10;10.0.15063;AMD64;Intel64 Family 6 Model 158 Stepping 9, GenuineIntel
version: 1.6.2
platform: win-64
qt: 5.6.2
pyqt: 5.6.0
conda: 4.3.21
```

**Comment by goanpeca** [comment]
@ccordoba12 ?
