### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by Satheesh-Rajkamal** [ContinuumIO/anaconda-issues#4038]
I got this error, any idea to fix this issue?

An unexpected error occurred on Navigator start-up

Report

Please report this issue in the anaconda issue tracker

Main Error

list indices must be integers or slices, not str
Traceback

Traceback (most recent call last):
  File "C:\Users\satheesh.r\AppData\Local\Continuum\conda\lib\site-packages\anaconda_navigator\exceptions.py", line 75, in exception_handler
    return_value = func(*args, **kwargs)
  File "C:\Users\satheesh.r\AppData\Local\Continuum\conda\lib\site-packages\anaconda_navigator\app\start.py", line 115, in start_app
    window = run_app(splash)
  File "C:\Users\satheesh.r\AppData\Local\Continuum\conda\lib\site-packages\anaconda_navigator\app\start.py", line 58, in run_app
    window = MainWindow(splash=splash)
  File "C:\Users\satheesh.r\AppData\Local\Continuum\conda\lib\site-packages\anaconda_navigator\widgets\main_window.py", line 160, in __init__
    self.api = AnacondaAPI()
  File "C:\Users\satheesh.r\AppData\Local\Continuum\conda\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 1205, in AnacondaAPI
    ANACONDA_API = _AnacondaAPI()
  File "C:\Users\satheesh.r\AppData\Local\Continuum\conda\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 65, in __init__
    self._conda_api = CondaAPI()
  File "C:\Users\satheesh.r\AppData\Local\Continuum\conda\lib\site-packages\anaconda_navigator\api\conda_api.py", line 1622, in CondaAPI
    CONDA_API = _CondaAPI()
  File "C:\Users\satheesh.r\AppData\Local\Continuum\conda\lib\site-packages\anaconda_navigator\api\conda_api.py", line 340, in __init__
    self.set_conda_prefix()
  File "C:\Users\satheesh.r\AppData\Local\Continuum\conda\lib\site-packages\anaconda_navigator\api\conda_api.py", line 489, in set_conda_prefix
    self.ROOT_PREFIX = info['root_prefix']
TypeError: list indices must be integers or slices, not str

**Comment by nevadarain** [comment]
Anaconda is worthless..... I solved by just using pip to install all my libraries I use. And I use eclipse as my IDE

**Comment by goanpeca** [comment]
@Satheesh-Rajkamal how did you try to launch navigator? 

Could you open an anaconda prompt and type 

`conda info` and `conda list` and paste the results?
