### ISSUE TITLE
conda update anaconda error ...An unexpected error has occurred

### ISSUE THREAD

**Issue by jamartinh** [ContinuumIO/anaconda-issues#404]
``` bash
Traceback (most recent call last):
  File "C:\Anaconda\lib\runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "C:\Anaconda\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Anaconda\Scripts\conda.exe\__main__.py", line 9, in <module>
  File "C:\Anaconda\lib\site-packages\conda\cli\main.py", line 194, in main
    args_func(args, p)
  File "C:\Anaconda\lib\site-packages\conda\cli\main.py", line 201, in args_func
    args.func(args, p)
  File "C:\Anaconda\lib\site-packages\conda\cli\main_update.py", line 38, in execute
    install.install(args, parser, 'update')
  File "C:\Anaconda\lib\site-packages\conda\cli\install.py", line 244, in install
    offline=args.offline)
  File "C:\Anaconda\lib\site-packages\conda\cli\common.py", line 548, in get_index_trap
    return get_index(*args, **kwargs)
  File "C:\Anaconda\lib\site-packages\conda\api.py", line 42, in get_index
    unknown=unknown)
  File "C:\Anaconda\lib\site-packages\conda\utils.py", line 119, in __call__
    value = self.func(*args, **kw)
  File "C:\Anaconda\lib\site-packages\conda\fetch.py", line 255, in fetch_index
    repodatas.append((url, future.result()))
  File "C:\Anaconda\lib\site-packages\concurrent\futures\_base.py", line 407, in result
    return self.__get_result()
  File "C:\Anaconda\lib\site-packages\concurrent\futures\_base.py", line 359, in __get_result
    reraise(self._exception, self._traceback)
  File "C:\Anaconda\lib\site-packages\concurrent\futures\_compat.py", line 107, in reraise
    exec('raise exc_type, exc_value, traceback', {}, locals_)
  File "C:\Anaconda\lib\site-packages\concurrent\futures\thread.py", line 61, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Anaconda\lib\site-packages\conda\fetch.py", line 65, in func
    res = f(*args, **kwargs)
  File "C:\Anaconda\lib\site-packages\conda\fetch.py", line 100, in fetch_repodata
    headers=headers, proxies=session.proxies)
  File "C:\Users\jamh\AppData\Roaming\Python\Python27\site-packages\requests-2.6.0-py2.7.egg\requests\sessions.py", line 476, in get
    return self.request('GET', url, **kwargs)
  File "C:\Users\jamh\AppData\Roaming\Python\Python27\site-packages\requests-2.6.0-py2.7.egg\requests\sessions.py", line 464, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\jamh\AppData\Roaming\Python\Python27\site-packages\requests-2.6.0-py2.7.egg\requests\sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\jamh\AppData\Roaming\Python\Python27\site-packages\requests-2.6.0-py2.7.egg\requests\adapters.py", line 370, in send
    timeout=timeout
  File "C:\Users\jamh\AppData\Roaming\Python\Python27\site-packages\requests-2.6.0-py2.7.egg\requests\packages\urllib3\connectionpool.py", line 544, in urlopen
    body=body, headers=headers)
  File "C:\Users\jamh\AppData\Roaming\Python\Python27\site-packages\requests-2.6.0-py2.7.egg\requests\packages\urllib3\connectionpool.py", line 341, in _make_request
    self._validate_conn(conn)
  File "C:\Users\jamh\AppData\Roaming\Python\Python27\site-packages\requests-2.6.0-py2.7.egg\requests\packages\urllib3\connectionpool.py", line 762, in _validate_conn
    conn.connect()
  File "C:\Users\jamh\AppData\Roaming\Python\Python27\site-packages\requests-2.6.0-py2.7.egg\requests\packages\urllib3\connection.py", line 245, in connect
    cert = self.sock.getpeercert()
  File "C:\Users\jamh\AppData\Roaming\Python\Python27\site-packages\requests-2.6.0-py2.7.egg\requests\packages\urllib3\contrib\pyopenssl.py", line 251, in getpeercert
    for value in get_subj_alt_name(x509)
  File "C:\Users\jamh\AppData\Roaming\Python\Python27\site-packages\requests-2.6.0-py2.7.egg\requests\packages\urllib3\contrib\pyopenssl.py", line 152, in get_subj_alt_name
    asn1Spec=general_names)
  File "C:\Anaconda\lib\site-packages\pyasn1\codec\ber\decoder.py", line 792, in __call__
    stGetValueDecoder, self, substrateFun
  File "C:\Anaconda\lib\site-packages\pyasn1\codec\ber\decoder.py", line 367, in valueDecoder
    component, head = decodeFun(head, asn1Spec)
  File "C:\Anaconda\lib\site-packages\pyasn1\codec\ber\decoder.py", line 792, in __call__
    stGetValueDecoder, self, substrateFun
  File "C:\Anaconda\lib\site-packages\pyasn1\codec\ber\decoder.py", line 430, in valueDecoder
    r.setComponentByType(effectiveTagSet, component, 0, asn1Spec is None)
  File "C:\Anaconda\lib\site-packages\pyasn1\type\univ.py", line 874, in setComponentByType
    idx = self._componentType.getPositionByType(tagSet)
  File "C:\Anaconda\lib\site-packages\pyasn1\type\namedtype.py", line 68, in getPositionByType
    raise error.PyAsn1Error('Type %s not found' % (tagSet,))
pyasn1.error.PyAsn1Error: Type TagSet(Tag(tagClass=128, tagFormat=0, tagId=2)) not found

C:\Windows\system32>conda info
Current conda install:

             platform : win-64
        conda version : 3.16.0
  conda-build version : 1.8.2
       python version : 2.7.8.final.0
     requests version : 2.6.0
     root environment : C:\Anaconda  (writable)
  default environment : C:\Anaconda
     envs directories : C:\Anaconda\envs
        package cache : C:\Anaconda\pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/win-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/win-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : None
    is foreign system : False
```

**Comment by csoja** [comment]
Closing as no longer relevant - there have been many package updates since this issue was logged.
