### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by srinivasbodi** [ContinuumIO/anaconda-issues#4040]
## Main error
Application <b>spyder</b> launch may have produced errors.
## Traceback
```
Traceback (most recent call last):
  File "D:\Python\Anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 3069, in main
    mainwindow = run_spyder(app, options, args)
  File "D:\Python\Anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 2969, in run_spyder
    main = MainWindow(options)
  File "D:\Python\Anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 338, in __init__
    from spyder.plugins.configdialog import (MainConfigPage,
  File "D:\Python\Anaconda3\lib\site-packages\spyder\plugins\configdialog.py", line 39, in <module>
    from spyder.widgets.sourcecode.codeeditor import CodeEditor
  File "D:\Python\Anaconda3\lib\site-packages\spyder\widgets\sourcecode\codeeditor.py", line 58, in <module>
    from spyder.widgets.sourcecode.base import TextEditBaseWidget
  File "D:\Python\Anaconda3\lib\site-packages\spyder\widgets\sourcecode\base.py", line 35, in <module>
    from spyder.widgets.mixins import BaseEditMixin
  File "D:\Python\Anaconda3\lib\site-packages\spyder\widgets\mixins.py", line 29, in <module>
    from spyder.py3compat import is_text_string, to_text_string, u
ImportError: cannot import name 'u'

```
## System information
```
python: 3.6.1
language: en_IN
os: Windows;10;10.0.14393;AMD64;Intel64 Family 6 Model 23 Stepping 10, GenuineIntel
version: 1.6.2
platform: win-64
qt: 5.6.2
pyqt: 5.6.0
conda: 4.3.23
```

**Comment by goanpeca** [comment]
@ccordoba12?
