### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by leebond** [ContinuumIO/anaconda-issues#4043]
## Main error
Application <b>notebook</b> launch may have produced errors.
## Traceback
```
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\Scripts\jupyter-notebook-script.py", line 3, in <module>
    import notebook.notebookapp
  File "C:\ProgramData\Anaconda3\lib\site-packages\notebook\__init__.py", line 25, in <module>
    from .nbextensions import install_nbextension
  File "C:\ProgramData\Anaconda3\lib\site-packages\notebook\nbextensions.py", line 572, in <module>
    from .extensions import (
  File "C:\ProgramData\Anaconda3\lib\site-packages\notebook\extensions.py", line 8, in <module>
    from tornado.log import LogFormatter
ModuleNotFoundError: No module named 'tornado.log'

```
## System information
```
python: 3.6.1
language: en_SG
os: Windows;7;6.1.7601;AMD64;Intel64 Family 6 Model 61 Stepping 4, GenuineIntel
version: 1.6.2
platform: win-64
qt: 5.6.2
pyqt: 5.6.0
conda: 4.3.21
```

**Comment by goanpeca** [comment]
@leebond please try to reinstall tornado. On a terminal type

`conda install tornado --force`

See https://stackoverflow.com/questions/42265338/jupyter-notebook-importerror-no-module-named-tornado-log
