### ISSUE TITLE
Report error: started Launcher from conda cloned env of root py2.7

### ISSUE THREAD

**Issue by edb983** [ContinuumIO/anaconda-issues#406]
I cloned the "root" installation of anaconda (from the conda training tutorial).
Then double-clicked "Launcher.app" in the new env folder. Not sure if this is proper way to launch an environment?
These errors listed and asked to report here ... so reporting:

Error: spawn ENOENT
    at exports._errnoException (util.js:742:11)
    at Process.ChildProcess._handle.onexit (child_process.js:1027:32)
    at child_process.js:1110:20
    at process._tickCallback (node.js:279:11)

**Comment by edb983** [comment]
OK. Noticed that I still had a different environment active (in Terminal).
deactivated that environment, then activated the environment I was starting "Launcher.app" from.
This time it seems to have launched as expected!
Launching Spyder ... yes! Looks like it is working. 
I think this issue is resolved.
