### ISSUE TITLE
jupyter notebook not launching

### ISSUE THREAD

**Issue by subinoy** [ContinuumIO/anaconda-issues#4081]
```
subinoy@suny-desk ~/anaconda3/lib/python3.6/site-packages $ jupyter-notebook
Traceback (most recent call last):
  File "/home/subinoy/anaconda3/bin/jupyter-notebook", line 4, in <module>
    import notebook.notebookapp
  File "/home/subinoy/anaconda3/lib/python3.6/site-packages/notebook/notebookapp.py", line 28, in <module>
    from jinja2 import Environment, FileSystemLoader
  File "/home/subinoy/anaconda3/lib/python3.6/site-packages/jinja2/__init__.py", line 81, in <module>
    _patch_async()
  File "/home/subinoy/anaconda3/lib/python3.6/site-packages/jinja2/__init__.py", line 77, in _patch_async
    from jinja2.asyncsupport import patch_all
  File "/home/subinoy/anaconda3/lib/python3.6/site-packages/jinja2/asyncsupport.py", line 13, in <module>
    import asyncio
  File "/home/subinoy/anaconda3/lib/python3.6/asyncio/__init__.py", line 21, in <module>
    from .base_events import *
  File "/home/subinoy/anaconda3/lib/python3.6/asyncio/base_events.py", line 17, in <module>
    import concurrent.futures
  File "/home/subinoy/anaconda3/lib/python3.6/site-packages/concurrent/futures/__init__.py", line 8, in <module>
    from concurrent.futures._base import (FIRST_COMPLETED,
  File "/home/subinoy/anaconda3/lib/python3.6/site-packages/concurrent/futures/_base.py", line 355
    raise type(self._exception), self._exception, self._traceback
                               ^
SyntaxError: invalid syntax
```

```
subinoy@suny-desk ~ $ conda info
Current conda install:

               platform : linux-64
          conda version : 4.3.23
       conda is private : False
      conda-env version : 4.3.23
    conda-build version : not installed
         python version : 3.6.0.final.0
       requests version : 2.18.2
       root environment : /home/subinoy/anaconda3  (writable)
    default environment : /home/subinoy/anaconda3
       envs directories : /home/subinoy/anaconda3/envs
                          /home/subinoy/.conda/envs
          package cache : /home/subinoy/anaconda3/pkgs
                          /home/subinoy/.conda/pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/linux-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : None
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.23 requests/2.18.2 CPython/3.6.0 Linux/4.4.0-64-generic debian/stretch/sid glibc/2.23    
                UID:GID : 1000:1000
subinoy@suny-desk ~ $ conda list
# packages in environment at /home/subinoy/anaconda3:
#
_license                  1.1                      py36_1  
accumulator               0.2                       <pip>
alabaster                 0.7.9                    py36_0  
alembic                   0.9.4                     <pip>
anaconda                  custom                   py36_0  
anaconda-client           1.6.0                    py36_0  
anaconda-navigator        1.4.3                    py36_0  
asn1crypto                0.22.0                    <pip>
astroid                   1.4.9                    py36_0  
astropy                   1.3                 np111py36_0  
babel                     2.3.4                    py36_0  
backports                 1.0                      py36_0  
backtrader                1.9.57.122                <pip>
bcolz                     0.12.1                    <pip>
beautifulsoup4            4.5.3                    py36_0  
beautifulsoup4            4.6.0                     <pip>
biopython                 1.66                      <pip>
bitarray                  0.8.1                    py36_0  
bleach                    1.5.0                    py36_0  
boto                      2.45.0                   py36_0  
bottleneck                1.2.0               np111py36_0  
brewer2mpl                1.4.1                     <pip>
cairo                     1.14.8                        0  
certifi                   2017.7.27.1               <pip>
cffi                      1.10.0                    <pip>
cffi                      1.9.1                    py36_0  
chardet                   3.0.4                     <pip>
chardet                   2.3.0                    py36_0  
chest                     0.2.3                    py36_0  
click                     6.7                      py36_0  
cloudpickle               0.2.2                    py36_0  
clyent                    1.2.2                    py36_0  
colorama                  0.3.7                    py36_0  
conda                     4.3.23                   py36_0  
conda-env                 2.6.0                         0  
configobj                 5.0.6                    py36_0  
contextlib2               0.5.4                    py36_0  
cryptography              1.7.1                    py36_0  
cryptography              2.0.2                     <pip>
curl                      7.52.1                        0  
cycler                    0.10.0                   py36_0  
cyordereddict             1.0.0                     <pip>
cython                    0.25.2                   py36_0  
cytoolz                   0.8.2                    py36_0  
datashape                 0.5.4                    py36_0  
dbus                      1.10.10                       0  
decorator                 4.0.11                   py36_0  
dill                      0.2.5                    py36_0  
docutils                  0.13.1                   py36_0  
empyrical                 0.3.0                     <pip>
entrypoints               0.2.2                    py36_0  
et_xmlfile                1.0.1                    py36_0  
expat                     2.1.0                         0  
ezIBpy                    1.12.56                   <pip>
fastcache                 1.0.2                    py36_1  
fix-yahoo-finance         0.0.18                    <pip>
Flask                     0.12.2                    <pip>
fontconfig                2.12.1                        2  
freetype                  2.5.5                         2  
futures                   3.0.3                     <pip>
get                       0.0.0                     <pip>
get_terminal_size         1.0.0                    py36_0  
gevent                    1.2.1                    py36_0  
ggplot                    0.11.5                    <pip>
glib                      2.50.2                        1  
greenlet                  0.4.11                   py36_0  
gst-plugins-base          1.8.0                         0  
gstreamer                 1.8.0                         0  
h5py                      2.6.0               np111py36_2  
harfbuzz                  0.9.39                        2  
hdf5                      1.8.17                        1  
heapdict                  1.0.0                    py36_1  
html5lib                  0.9999999                py36_0  
IbPy2                     0.8.0                     <pip>
icu                       54.1                          0  
idna                      2.2                      py36_0  
idna                      2.5                       <pip>
imagesize                 0.7.1                    py36_0  
intervaltree              2.1.0                     <pip>
ipykernel                 4.5.2                    py36_0  
ipython                   6.1.0                    py36_0  
ipython_genutils          0.1.0                    py36_0  
ipywidgets                6.0.0                    py36_0  
isort                     4.2.5                    py36_0  
itsdangerous              0.24                     py36_0  
jbig                      2.1                           0  
jdcal                     1.3                      py36_0  
jedi                      0.10.2                   py36_2  
Jinja2                    2.9.6                     <pip>
jinja2                    2.9.6                    py36_0  
jpeg                      9b                            0  
jsonschema                2.5.1                    py36_0  
jupyter                   1.0.0                    py36_3  
jupyter_client            4.4.0                    py36_0  
jupyter_console           5.0.0                    py36_0  
jupyter_core              4.2.1                    py36_0  
lazy-object-proxy         1.2.2                    py36_0  
libffi                    3.2.1                         1  
libgcc                    4.8.5                         2  
libgfortran               3.0.0                         1  
libiconv                  1.14                          0  
libpng                    1.6.27                        0  
libsodium                 1.0.10                        0  
libtiff                   4.0.6                         3  
libxcb                    1.12                          1  
libxml2                   2.9.4                         0  
libxslt                   1.1.29                        0  
llvmlite                  0.15.0                   py36_0  
locket                    0.2.0                    py36_1  
Logbook                   1.1.0                     <pip>
lru-dict                  1.1.6                     <pip>
lxml                      3.7.2                    py36_0  
Mako                      1.0.7                     <pip>
MarkupSafe                1.0                       <pip>
markupsafe                0.23                     py36_2  
matplotlib                2.0.0               np111py36_0  
mistune                   0.7.3                    py36_0  
mitos                     0.0.3                     <pip>
mkl                       2017.0.1                      0  
mkl-service               1.1.2                    py36_3  
mpmath                    0.19                     py36_1  
multipledispatch          0.4.9                    py36_0  
multitasking              0.0.4                     <pip>
nbconvert                 5.2.1                    py36_0  
nbformat                  4.2.0                    py36_0  
networkx                  1.11                     py36_0  
nexmo                     1.5.0                     <pip>
nltk                      3.2.2                    py36_0  
nose                      1.3.7                    py36_1  
notebook                  5.0.0                    py36_0  
nsepy                     0.4                       <pip>
nsetools                  1.0.1                     <pip>
numba                     0.30.1              np111py36_0  
numexpr                   2.6.1               np111py36_2  
numpy                     1.11.3                   py36_0  
numpy                     1.13.1                    <pip>
odo                       0.5.0                    py36_1  
openpyxl                  2.4.1                    py36_0  
openssl                   1.0.2k                        0  
pandas                    0.19.2              np111py36_1  
pandas                    0.20.3                    <pip>
pandas-datareader         0.5.0                     <pip>
pandocfilters             1.4.1                    py36_0  
partd                     0.3.7                    py36_0  
path.py                   10.0                     py36_0  
pathlib2                  2.2.0                    py36_0  
patsy                     0.4.1                    py36_0  
pcre                      8.39                          1  
pep8                      1.7.0                    py36_0  
pexpect                   4.2.1                    py36_0  
pickleshare               0.7.4                    py36_0  
pillow                    4.0.0                    py36_0  
pip                       9.0.1                    py36_1  
pixman                    0.34.0                        0  
ply                       3.9                      py36_0  
post                      0.0.0                     <pip>
prompt_toolkit            1.0.9                    py36_0  
psutil                    5.0.1                    py36_0  
ptyprocess                0.5.1                    py36_0  
public                    0.0.0                     <pip>
py                        1.4.32                   py36_0  
PyAlgoTrade               0.18                      <pip>
pyasn1                    0.1.9                    py36_0  
pycosat                   0.6.1                    py36_1  
pycparser                 2.18                      <pip>
pycparser                 2.17                     py36_0  
pycrypto                  2.6.1                    py36_4  
pycurl                    7.43.0                   py36_2  
pyflakes                  1.5.0                    py36_0  
pygments                  2.1.3                    py36_0  
PyJWT                     1.5.2                     <pip>
pylint                    1.6.4                    py36_1  
PyMySQL                   0.7.11                    <pip>
pyopenssl                 16.2.0                   py36_0  
pyparsing                 2.1.4                    py36_0  
pyqt                      5.6.0                    py36_2  
PySocks                   1.6.7                     <pip>
pytables                  3.3.0               np111py36_0  
pytest                    3.0.5                    py36_0  
python                    3.6.0                         0  
python-dateutil           2.6.0                    py36_0  
python-dateutil           2.6.1                     <pip>
python-editor             1.0.3                     <pip>
pytz                      2016.10                  py36_0  
pytz                      2017.2                    <pip>
pyyaml                    3.12                     py36_0  
pyzmq                     16.0.2                   py36_0  
qt                        5.6.2                         3  
qtawesome                 0.4.3                    py36_0  
qtconsole                 4.2.1                    py36_1  
qtpy                      1.2.1                    py36_0  
QTPyLib                   1.5.74                    <pip>
query-string              0.0.0                     <pip>
quotelib                  1.0                       <pip>
readline                  6.2                           2  
redis                     3.2.0                         0  
redis-py                  2.10.5                   py36_0  
request                   0.0.0                     <pip>
requests                  2.12.4                   py36_0  
requests                  2.18.2                    <pip>
requests-file             1.4.2                     <pip>
requests-ftp              0.3.1                     <pip>
rope                      0.9.4                    py36_1  
ruamel_yaml               0.11.14                  py36_1  
scikit-image              0.12.3              np111py36_1  
scikit-learn              0.18.1              np111py36_1  
scipy                     0.18.1              np111py36_1  
seaborn                   0.7.1                    py36_0  
setupfiles                0.0.50                    <pip>
setuptools                27.2.0                   py36_0  
simplegeneric             0.8.1                    py36_1  
singledispatch            3.4.0.3                  py36_0  
sip                       4.18                     py36_0  
six                       1.10.0                   py36_0  
snowballstemmer           1.2.1                    py36_0  
sockjs-tornado            1.0.3                    py36_0  
sortedcontainers          1.5.7                     <pip>
sqlalchemy                1.1.5                    py36_0  
sqlite                    3.13.0                        0  
statsmodels               0.6.1               np111py36_1  
sympy                     1.0                      py36_0  
terminado                 0.6                      py36_0  
testpath                  0.3.1                    py36_0  
tk                        8.5.18                        0  
toolz                     0.8.2                    py36_0  
tornado                   4.4.2                    py36_0  
trade                     0.2.9                     <pip>
traitlets                 4.3.1                    py36_0  
twilio                    6.5.0                     <pip>
unicodecsv                0.14.1                   py36_0  
urllib3                   1.22                      <pip>
wcwidth                   0.1.7                    py36_0  
Werkzeug                  0.12.2                    <pip>
werkzeug                  0.11.15                  py36_0  
wheel                     0.29.0                   py36_0  
widgetsnbextension        2.0.0                    py36_0  
wrapt                     1.10.8                   py36_0  
xlrd                      1.0.0                    py36_0  
xlsxwriter                0.9.6                    py36_0  
xlwt                      1.2.0                    py36_0  
xz                        5.2.2                         1  
yaml                      0.1.6                         0  
zeromq                    4.1.5                         0  
zipline                   1.1.1                     <pip>
zlib                      1.2.8                         3  
-----------------------------------------------------
subinoy@suny-desk ~ $ jupyter-notebook
Traceback (most recent call last):
  File "/home/subinoy/anaconda3/bin/jupyter-notebook", line 4, in <module>
    import notebook.notebookapp
  File "/home/subinoy/anaconda3/lib/python3.6/site-packages/notebook/notebookapp.py", line 35, in <module>
    from jinja2 import Environment, FileSystemLoader
  File "/home/subinoy/anaconda3/lib/python3.6/site-packages/jinja2/__init__.py", line 81, in <module>
    _patch_async()
  File "/home/subinoy/anaconda3/lib/python3.6/site-packages/jinja2/__init__.py", line 77, in _patch_async
    from jinja2.asyncsupport import patch_all
  File "/home/subinoy/anaconda3/lib/python3.6/site-packages/jinja2/asyncsupport.py", line 13, in <module>
    import asyncio
  File "/home/subinoy/anaconda3/lib/python3.6/asyncio/__init__.py", line 21, in <module>
    from .base_events import *
  File "/home/subinoy/anaconda3/lib/python3.6/asyncio/base_events.py", line 17, in <module>
    import concurrent.futures
  File "/home/subinoy/anaconda3/lib/python3.6/site-packages/concurrent/futures/__init__.py", line 8, in <module>
    from concurrent.futures._base import (FIRST_COMPLETED,
  File "/home/subinoy/anaconda3/lib/python3.6/site-packages/concurrent/futures/_base.py", line 355
    raise type(self._exception), self._exception, self._traceback
                               ^
SyntaxError: invalid syntax
```

**Comment by goanpeca** [comment]
It looks like your local installation of futures is the problem. Do you know that ~/.local directory is there?Please consider temporarily removing ~/.local/lib/python2.7/site-packages/concurrent/futuresfrom your system. (Move it aside, rename it to futures2, whatever). If that fixes the problem then leave it removed :-) In fact, please consider removing any package found in ~/.local that conflicts with any package installed in your Anaconda environment.
--

**Comment by goanpeca** [comment]
Related to https://github.com/conda/conda/issues/2255

**Comment by subinoy** [comment]
Thank you, Gonzalo for your solution

It works fine now.

Subinoy

**Comment by goanpeca** [comment]
Glad to hear it works @subinoy  :+1:
