### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by qinzhengke** [ContinuumIO/anaconda-issues#4090]
## Main error
Application <b>spyder</b> launch may have produced errors.
## Traceback
```
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\Scripts\spyder-script.py", line 3, in <module>
    import spyder.app.start
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\app\start.py", line 13, in <module>
    from spyder.config.base import get_conf_path, running_in_mac_app
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\config\base.py", line 365, in <module>
    _ = get_translation("spyder")
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\config\base.py", line 345, in get_translation
    _trans = gettext.translation(modname, locale_path, codeset="utf-8")
  File "C:\ProgramData\Anaconda3\lib\gettext.py", line 505, in translation
    mofiles = find(domain, localedir, languages, all=True)
  File "C:\ProgramData\Anaconda3\lib\gettext.py", line 489, in find
    if os.path.exists(mofile):
  File "C:\ProgramData\Anaconda3\lib\genericpath.py", line 19, in exists
    os.stat(path)
ValueError: stat: embedded null character in path

```
## System information
```
python: 3.6.1
language: zh_CN
os: Windows;7;6.1.7601;AMD64;Intel64 Family 6 Model 94 Stepping 3, GenuineIntel
version: 1.6.2
platform: win-64
qt: 5.6.2
pyqt: 5.6.0
conda: 4.3.21
```

**Comment by goanpeca** [comment]
@ccordoba12

**Comment by goanpeca** [comment]
Please try to install the Anaconda distribution for the current user only, instead of all users.
