### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by c4n** [ContinuumIO/anaconda-issues#4116]
## Main error
Application <b>spyder</b> launch may have produced errors.
## Traceback
```
Traceback (most recent call last):
  File "/opt/anaconda/lib/python3.6/site-packages/qtpy/QtWebEngineWidgets.py", line 22, in <module>
    from PyQt5.QtWebEngineWidgets import QWebEnginePage
ModuleNotFoundError: No module named 'PyQt5.QtWebEngineWidgets'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/anaconda/bin/spyder", line 6, in <module>
    sys.exit(spyder.app.start.main())
  File "/opt/anaconda/lib/python3.6/site-packages/spyder/app/start.py", line 103, in main
    from spyder.app import mainwindow
  File "/opt/anaconda/lib/python3.6/site-packages/spyder/app/mainwindow.py", line 92, in <module>
    from qtpy import QtWebEngineWidgets  # analysis:ignore
  File "/opt/anaconda/lib/python3.6/site-packages/qtpy/QtWebEngineWidgets.py", line 26, in <module>
    from PyQt5.QtWebKitWidgets import QWebPage as QWebEnginePage
ImportError: libselinux.so.1: cannot open shared object file: No such file or directory

```
## System information
```
python: 3.6.1
language: en_US
os: Linux;4.9.39-1-MANJARO;#1 SMP PREEMPT Fri Jul 21 08:25:24 UTC 2017;x86_64;
version: 1.6.2
platform: linux-64
qt: 5.6.2
pyqt: 5.6.0
conda: 4.3.24
```

**Comment by c4n** [comment]
[Solved]
For Arch/Manjaro users, you just need to install libselinux
yaourt -S libselinux
