### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by jlnavarro** [ContinuumIO/anaconda-issues#4200]
## Main error
Application <b>spyder</b> launch may have produced errors.
## Traceback
```
Traceback (most recent call last):
  File "/Users/jlnavarrop/anaconda/envs/py362/bin/spyder", line 6, in <module>
    sys.exit(spyder.app.start.main())
  File "/Users/jlnavarrop/anaconda/envs/py362/lib/python3.6/site-packages/spyder/app/start.py", line 135, in main
    from spyder.app import mainwindow
  File "/Users/jlnavarrop/anaconda/envs/py362/lib/python3.6/site-packages/spyder/app/mainwindow.py", line 112, in <module>
    from spyder.utils.qthelpers import qapplication, MENU_SEPARATOR
  File "/Users/jlnavarrop/anaconda/envs/py362/lib/python3.6/site-packages/spyder/utils/qthelpers.py", line 26, in <module>
    from spyder.config.gui import get_shortcut
  File "/Users/jlnavarrop/anaconda/envs/py362/lib/python3.6/site-packages/spyder/config/gui.py", line 29, in <module>
    from spyder.utils import syntaxhighlighters as sh
  File "/Users/jlnavarrop/anaconda/envs/py362/lib/python3.6/site-packages/spyder/utils/syntaxhighlighters.py", line 30, in <module>
    from spyder.utils.workers import WorkerManager
ModuleNotFoundError: No module named 'spyder.utils.workers'

```
## System information
```
python: 3.6.1
language: en
os: Darwin;16.7.0;Darwin Kernel Version 16.7.0: Thu Jun 15 17:36:27 PDT 2017; root:xnu-3789.70.16~2/RELEASE_X86_64;x86_64;i386
version: 1.6.2
platform: osx-64
qt: 5.6.2
pyqt: 5.6.0
conda: 4.3.23
```

**Comment by goanpeca** [comment]
Please remember to update to the latest version of Navigator to include
the latest fixes.

Open a terminal (on Linux or Mac) or the Anaconda Command Prompt (on windows)
and type:

```
$ conda update spyder
$ conda update conda
$ conda update anaconda-navigator
$ conda update navigator-updater
```
