### ISSUE TITLE
error message 

### ISSUE THREAD

**Issue by Paul-D-Shaughnessy** [ContinuumIO/anaconda-issues#4234]
Traceback (most recent call last):
  File "C:\Users\pauls\Anaconda2\envs\python36\Scripts\jupyter-notebook-script.py", line 5, in <module>
    sys.exit(notebook.notebookapp.main())
  File "C:\Users\pauls\Anaconda2\envs\python36\lib\site-packages\jupyter_core\application.py", line 267, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "C:\Users\pauls\Anaconda2\envs\python36\lib\site-packages\traitlets\config\application.py", line 657, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-7>", line 2, in initialize
  File "C:\Users\pauls\Anaconda2\envs\python36\lib\site-packages\traitlets\config\application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "C:\Users\pauls\Anaconda2\envs\python36\lib\site-packages\notebook\notebookapp.py", line 1296, in initialize
    self.init_webapp()
  File "C:\Users\pauls\Anaconda2\envs\python36\lib\site-packages\notebook\notebookapp.py", line 1093, in init_webapp
    self.jinja_environment_options
  File "C:\Users\pauls\Anaconda2\envs\python36\lib\site-packages\notebook\notebookapp.py", line 167, in __init__
    default_url, settings_overrides, jinja_env_options)
  File "C:\Users\pauls\Anaconda2\envs\python36\lib\site-packages\notebook\notebookapp.py", line 259, in init_settings
    nbextensions_path=jupyter_app.nbextensions_path,
  File "C:\Users\pauls\Anaconda2\envs\python36\lib\site-packages\notebook\notebookapp.py", line 807, in nbextensions_path
    from IPython.paths import get_ipython_dir
  File "C:\Users\pauls\Anaconda2\envs\python36\lib\site-packages\IPython\__init__.py", line 55, in <module>
    from .terminal.embed import embed
  File "C:\Users\pauls\Anaconda2\envs\python36\lib\site-packages\IPython\terminal\embed.py", line 16, in <module>
    from IPython.terminal.interactiveshell import TerminalInteractiveShell
  File "C:\Users\pauls\Anaconda2\envs\python36\lib\site-packages\IPython\terminal\interactiveshell.py", line 91, in <module>
    class TerminalInteractiveShell(InteractiveShell):
  File "C:\Users\pauls\Anaconda2\envs\python36\lib\site-packages\IPython\terminal\interactiveshell.py", line 134, in TerminalInteractiveShell
    highlighting: \n %s""" % ', '.join(get_all_styles())
  File "C:\Users\pauls\Anaconda2\envs\python36\lib\site-packages\pygments\styles\__init__.py", line 79, in get_all_styles
    for name, _ in find_plugin_styles():
  File "C:\Users\pauls\Anaconda2\envs\python36\lib\site-packages\pygments\plugin.py", line 62, in find_plugin_styles
    for entrypoint in iter_entry_points(STYLE_ENTRY_POINT):
  File "C:\Users\pauls\Anaconda2\envs\python36\lib\site-packages\pygments\plugin.py", line 45, in iter_entry_points
    import pkg_resources
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 646, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 616, in _load_backward_compatible
  File "C:\Users\pauls\Anaconda2\envs\python36\lib\site-packages\setuptools-27.2.0-py3.6.egg\pkg_resources\__init__.py", line 2985, in <module>
  File "C:\Users\pauls\Anaconda2\envs\python36\lib\site-packages\setuptools-27.2.0-py3.6.egg\pkg_resources\__init__.py", line 2971, in _call_aside
  File "C:\Users\pauls\Anaconda2\envs\python36\lib\site-packages\setuptools-27.2.0-py3.6.egg\pkg_resources\__init__.py", line 3013, in _initialize_master_working_set
  File "C:\Users\pauls\Anaconda2\envs\python36\lib\site-packages\setuptools-27.2.0-py3.6.egg\pkg_resources\__init__.py", line 2544, in activate
  File "C:\Users\pauls\Anaconda2\envs\python36\lib\site-packages\setuptools-27.2.0-py3.6.egg\pkg_resources\__init__.py", line 2118, in declare_namespace
  File "C:\Users\pauls\Anaconda2\envs\python36\lib\site-packages\setuptools-27.2.0-py3.6.egg\pkg_resources\__init__.py", line 2058, in _handle_ns
  File "C:\Users\pauls\Anaconda2\envs\python36\lib\site-packages\setuptools-27.2.0-py3.6.egg\pkg_resources\__init__.py", line 2087, in _rebuild_mod_path
AttributeError: '_NamespacePath' object has no attribute 'sort'

(C:\Users\pauls\Anaconda2\envs\python36) C:\Users\pauls>conda update jupyter-notebook

PackageNotInstalledError: Package is not installed in prefix.
  prefix: C:\Users\pauls\Anaconda2\envs\python36
  package name: jupyter-notebook

**Comment by Paul-D-Shaughnessy** [comment]
This package is installed. I installed through anaconda under application python36

**Comment by Paul-D-Shaughnessy** [comment]
Please close issue.  I had to remove a folders with local and roaming versions of python 3.6 this appears to resolved the issue.
