### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by markrans** [ContinuumIO/anaconda-issues#4254]
## Main error
Application <b>spyder</b> launch may have produced errors.
## Traceback
```
Traceback (most recent call last):
  File "/Users/mark1/anaconda/bin/spyder", line 6, in <module>
    sys.exit(spyder.app.start.main())
  File "/Users/mark1/anaconda/lib/python3.5/site-packages/spyder/app/start.py", line 140, in main
    from spyder.app import mainwindow
  File "/Users/mark1/anaconda/lib/python3.5/site-packages/spyder/app/mainwindow.py", line 112, in <module>
    from spyder.utils.qthelpers import qapplication, MENU_SEPARATOR
  File "/Users/mark1/anaconda/lib/python3.5/site-packages/spyder/utils/qthelpers.py", line 26, in <module>
    from spyder.config.gui import get_shortcut
  File "/Users/mark1/anaconda/lib/python3.5/site-packages/spyder/config/gui.py", line 29, in <module>
    from spyder.utils import syntaxhighlighters as sh
  File "/Users/mark1/anaconda/lib/python3.5/site-packages/spyder/utils/syntaxhighlighters.py", line 30, in <module>
    from spyder.utils.workers import WorkerManager
ImportError: No module named 'spyder.utils.workers'

```
## System information
```
version: 1.6.2
pyqt: 5.6.0
platform: osx-64
os: Darwin;15.6.0;Darwin Kernel Version 15.6.0: Tue Apr 11 16:00:51 PDT 2017; root:xnu-3248.60.11.5.3~1/RELEASE_X86_64;x86_64;i386
qt: 5.6.2
python: 3.5.3
language: en
conda: 4.3.24
```

**Comment by goanpeca** [comment]
@ccordoba12 ?
