### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by alonlavian** [ContinuumIO/anaconda-issues#4291]
## Main error
Application <b>notebook</b> launch may have produced errors.
## Traceback
```
Traceback (most recent call last):
  File "F:\Anaconda3\Scripts\jupyter-notebook-script.py", line 3, in <module>
    import notebook.notebookapp
  File "F:\Anaconda3\lib\site-packages\notebook\notebookapp.py", line 35, in <module>
    from jinja2 import Environment, FileSystemLoader
  File "F:\Anaconda3\lib\site-packages\jinja2\__init__.py", line 33, in <module>
    from jinja2.environment import Environment, Template
  File "F:\Anaconda3\lib\site-packages\jinja2\environment.py", line 15, in <module>
    from jinja2 import nodes
  File "F:\Anaconda3\lib\site-packages\jinja2\nodes.py", line 19, in <module>
    from jinja2.utils import Markup
  File "F:\Anaconda3\lib\site-packages\jinja2\utils.py", line 624, in <module>
    from markupsafe import Markup, escape, soft_unicode
  File "F:\Anaconda3\lib\site-packages\markupsafe\__init__.py", line 14, in <module>
    from markupsafe._compat import text_type, string_types, int_types, \
ModuleNotFoundError: No module named 'markupsafe._compat'

```
## System information
```
python: 3.6.1
language: he_IL
os: Windows;10;10.0.15063;AMD64;Intel64 Family 6 Model 60 Stepping 3, GenuineIntel
version: 1.6.2
platform: win-64
qt: 5.6.2
pyqt: 5.6.0
conda: 4.3.21
```

**Comment by alonlavian** [comment]
happened after I upgraded markupsafe.
downgraded and issue is resolved.
