### ISSUE TITLE
Anaconda not working at all [Windows]

### ISSUE THREAD

**Issue by aidan959** [ContinuumIO/anaconda-issues#4346]
Whenever I open up Anaconda Prompt,  the prompt spits out this error,
```
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\Scripts\conda-script.py", line 5, in <module>
    sys.exit(conda.cli.main())
  File "C:\ProgramData\Anaconda3\lib\site-packages\conda\cli\main.py", line 151, in main
    activate.main()
  File "C:\ProgramData\Anaconda3\lib\site-packages\conda\cli\activate.py", line 118, in main
    from conda.utils import shells
  File "C:\ProgramData\Anaconda3\lib\site-packages\conda\utils.py", line 13, in <module>
    from .gateways.disk.read import compute_md5sum
  File "C:\ProgramData\Anaconda3\lib\site-packages\conda\gateways\disk\read.py", line 22, in <module>
    from ...models.channel import Channel
  File "C:\ProgramData\Anaconda3\lib\site-packages\conda\models\channel.py", line 9, in <module>
    from ..base.context import context
  File "C:\ProgramData\Anaconda3\lib\site-packages\conda\base\context.py", line 19, in <module>
    from .._vendor.auxlib.path import expand
  File "C:\ProgramData\Anaconda3\lib\site-packages\conda\_vendor\auxlib\path.py", line 8, in <module>
    import pkg_resources
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 646, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 616, in _load_backward_compatible
  File "C:\ProgramData\Anaconda3\lib\site-packages\setuptools-27.2.0-py3.6.egg\pkg_resources\__init__.py", line 2985, in <module>
  File "C:\ProgramData\Anaconda3\lib\site-packages\setuptools-27.2.0-py3.6.egg\pkg_resources\__init__.py", line 2971, in _call_aside
  File "C:\ProgramData\Anaconda3\lib\site-packages\setuptools-27.2.0-py3.6.egg\pkg_resources\__init__.py", line 3013, in _initialize_master_working_set
  File "C:\ProgramData\Anaconda3\lib\site-packages\setuptools-27.2.0-py3.6.egg\pkg_resources\__init__.py", line 2544, in activate
  File "C:\ProgramData\Anaconda3\lib\site-packages\setuptools-27.2.0-py3.6.egg\pkg_resources\__init__.py", line 2118, in declare_namespace
  File "C:\ProgramData\Anaconda3\lib\site-packages\setuptools-27.2.0-py3.6.egg\pkg_resources\__init__.py", line 2058, in _handle_ns
  File "C:\ProgramData\Anaconda3\lib\site-packages\setuptools-27.2.0-py3.6.egg\pkg_resources\__init__.py", line 2087, in _rebuild_mod_path
AttributeError: '_NamespacePath' object has no attribute 'sort'
```

This output comes in anytime I use anything to do with anaconda or python. The Anaconda Navigator does not open. I am running Windows 10 with the newest patches, and have completely removed anaconda many times. If someone is able to help it would be much appreciated.

**Comment by goanpeca** [comment]
@aidan959 did you install for all users?

**Comment by aidan959** [comment]
@goanpeca I did install for all users

**Comment by goanpeca** [comment]
@aidan959 I would advice you install for the current user only. @kalefranz thoughts on the error?

**Comment by aidan959** [comment]
@goanpeca am attempting that now thanks

**Comment by goanpeca** [comment]
@aidan959 make sure to properly uninstall the system wide install before, installing the new user wide anaconda.

**Comment by aidan959** [comment]
@goanpeca tried but to no avail same errors seem to persist

**Comment by goanpeca** [comment]
The exact same error, or now is it pointing to the new install ??

If you open a terminal and type 

`$ pip install --upgrade setuptools` ?

**Comment by aidan959** [comment]
`Traceback (most recent call last):
  File "C:\Users\Aidan\Anaconda3\Scripts\pip-script.py", line 3, in <module>
    import pip
  File "C:\Users\Aidan\Anaconda3\lib\site-packages\pip\__init__.py", line 26, in <module>
    from pip.utils import get_installed_distributions, get_prog
  File "C:\Users\Aidan\Anaconda3\lib\site-packages\pip\utils\__init__.py", line 27, in <module>
    from pip._vendor import pkg_resources
  File "C:\Users\Aidan\Anaconda3\lib\site-packages\pip\_vendor\pkg_resources\__init__.py", line 3018, in <module>
    @_call_aside
  File "C:\Users\Aidan\Anaconda3\lib\site-packages\pip\_vendor\pkg_resources\__init__.py", line 3004, in _call_aside
    f(*args, **kwargs)
  File "C:\Users\Aidan\Anaconda3\lib\site-packages\pip\_vendor\pkg_resources\__init__.py", line 3046, in _initialize_master_working_set
    dist.activate(replace=False)
  File "C:\Users\Aidan\Anaconda3\lib\site-packages\pip\_vendor\pkg_resources\__init__.py", line 2578, in activate
    declare_namespace(pkg)
  File "C:\Users\Aidan\Anaconda3\lib\site-packages\pip\_vendor\pkg_resources\__init__.py", line 2152, in declare_namespace
    _handle_ns(packageName, path_item)
  File "C:\Users\Aidan\Anaconda3\lib\site-packages\pip\_vendor\pkg_resources\__init__.py", line 2092, in _handle_ns
    _rebuild_mod_path(path, packageName, module)
  File "C:\Users\Aidan\Anaconda3\lib\site-packages\pip\_vendor\pkg_resources\__init__.py", line 2121, in _rebuild_mod_path
    orig_path.sort(key=position_in_sys_path)
AttributeError: '_NamespacePath' object has no attribute 'sort'` is the error, I uninstalled python prior to installing anaconda

**Comment by aidan959** [comment]
@goanpeca  where do I paste this? as appending it to the top of the file didn't change anything?

**Comment by goanpeca** [comment]
@aidan959 not appending... replacing. The code in that file should look like https://raw.githubusercontent.com/kalefranz/conda/1a45b2ca07df9e6ce0980722fda7c25ed35131b8/conda/_vendor/auxlib/path.py

**Comment by aidan959** [comment]
@goanpeca I figured it out, the code you linked had - and + signs, which meant replace, it is working flawlessly thank you so much

**Comment by aidan959** [comment]
@goanpeca I am unable to say how thankful I am
