### ISSUE TITLE
Anaconda is not launching Jupyter in my PC

### ISSUE THREAD

**Issue by Pumauam** [ContinuumIO/anaconda-issues#4349]
## Main error
Application <b>notebook</b> launch may have produced errors.
## Traceback
```
Traceback (most recent call last):
  File "C:\Users\uos\Anaconda2\Scripts\jupyter-notebook-script.py", line 5, in <module>
    sys.exit(notebook.notebookapp.main())
  File "C:\Users\uos\Anaconda2\lib\site-packages\jupyter_core\application.py", line 267, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "C:\Users\uos\Anaconda2\lib\site-packages\traitlets\config\application.py", line 657, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-7>", line 2, in initialize
  File "C:\Users\uos\Anaconda2\lib\site-packages\traitlets\config\application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "C:\Users\uos\Anaconda2\lib\site-packages\notebook\notebookapp.py", line 1290, in initialize
    super(NotebookApp, self).initialize(argv)
  File "<decorator-gen-6>", line 2, in initialize
  File "C:\Users\uos\Anaconda2\lib\site-packages\traitlets\config\application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "C:\Users\uos\Anaconda2\lib\site-packages\jupyter_core\application.py", line 243, in initialize
    self.migrate_config()
  File "C:\Users\uos\Anaconda2\lib\site-packages\jupyter_core\application.py", line 169, in migrate_config
    migrate()
  File "C:\Users\uos\Anaconda2\lib\site-packages\jupyter_core\migrate.py", line 240, in migrate
    ensure_dir_exists(env['jupyter_config'])
  File "C:\Users\uos\Anaconda2\lib\site-packages\ipython_genutils\p

**Comment by goanpeca** [comment]
@Pumauam could you open a terminal and launch `jupyter notebook` from there. Does it work, or do you see a traceback?

**Comment by Pumauam** [comment]
@goanpeca following your advice I opened a terminal and launched jupyter notebook from there. It didn't work (it just showed that it is not recognized as an internal or extrenal command, etc..)

**Comment by Pumauam** [comment]
By the way, spyder is working properly

**Comment by goanpeca** [comment]
@Pumauam did you open the anaconda-prompt, or just a "regular" windows command prompt?

**Comment by Pumauam** [comment]
@goanpeca I used first the regular windows command prompt. After reading your last message I found the anaconda-prompt. It neither launched jupyter but left the following traceback:

(C:\Users\uos\Anaconda2) C:\Users\uos>jupyter notebook
Traceback (most recent call last):
  File "C:\Users\uos\Anaconda2\Scripts\jupyter-notebook-script.py", line 5, in <
module>
    sys.exit(notebook.notebookapp.main())
  File "C:\Users\uos\Anaconda2\lib\site-packages\jupyter_core\application.py", l
ine 267, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "C:\Users\uos\Anaconda2\lib\site-packages\traitlets\config\application.py
", line 657, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-7>", line 2, in initialize
  File "C:\Users\uos\Anaconda2\lib\site-packages\traitlets\config\application.py
", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "C:\Users\uos\Anaconda2\lib\site-packages\notebook\notebookapp.py", line
1290, in initialize
    super(NotebookApp, self).initialize(argv)
  File "<decorator-gen-6>", line 2, in initialize
  File "C:\Users\uos\Anaconda2\lib\site-packages\traitlets\config\application.py
", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "C:\Users\uos\Anaconda2\lib\site-packages\jupyter_core\application.py", l
ine 243, in initialize
    self.migrate_config()
  File "C:\Users\uos\Anaconda2\lib\site-packages\jupyter_core\application.py", l
ine 169, in migrate_config
    migrate()
  File "C:\Users\uos\Anaconda2\lib\site-packages\jupyter_core\migrate.py", line
240, in migrate
    ensure_dir_exists(env['jupyter_config'])
  File "C:\Users\uos\Anaconda2\lib\site-packages\ipython_genutils\path.py", line
 167, in ensure_dir_exists
    os.makedirs(path, mode=mode)
  File "C:\Users\uos\Anaconda2\lib\os.py", line 150, in makedirs
    makedirs(head, mode)
  File "C:\Users\uos\Anaconda2\lib\os.py", line 157, in makedirs
    mkdir(name, mode)
WindowsError: [Error 3] The system cannot find the path specified: 'U:\\'

**Comment by goanpeca** [comment]
@Pumauam looks like some env var might be set incorrectly on your system. Take a look at https://github.com/jupyter/help/issues/5

**Comment by Pumauam** [comment]
@goanpeca, thanks, in the thread you shared with me the user sean13 wrote what it worked for him: 

"Thanks! It was set to P:\User. I switched it to C:\temp and the notebook seemed to open!
You guys are great!"

Apparently he switched from P:\User to C:\temp, however I don't know how to do that (change user) in the anaconda-prompt

**Comment by goanpeca** [comment]
@Pumauam what he meant is that that some environment variable was incorrectly set to wrong value (for some reason)  https://kb.wisc.edu/cae/page.php?id=24500
