### ISSUE TITLE
Failure installing setuptools-18.2

### ISSUE THREAD

**Issue by rchekaluk** [ContinuumIO/anaconda-issues#436]
The following failure occurs when installing setuptools:

```
$ /usr/local/anaconda/bin/pip install --upgrade setuptools --allow-unverified setuptools --allow-external setuptools
Collecting setuptools
  Downloading setuptools-18.2-py2.py3-none-any.whl (461kB)

    0% |▎                               | 4.1kB 28.9MB/s eta 0:00:01
    1% |▋                               | 8.2kB 20.6MB/s eta 0:00:01
    ...
    99% |███████████████████████████████▉| 458kB 30.1MB/s eta 0:00:01
    100% |████████████████████████████████| 462kB 444kB/s 
Installing collected packages: setuptools
  Found existing installation: setuptools 18.1
    Uninstalling setuptools-18.1:
      Successfully uninstalled setuptools-18.1
Successfully installed setuptools
Traceback (most recent call last):
  File "/usr/local/anaconda/bin/pip", line 6, in <module>
    sys.exit(main())
  File "/usr/local/anaconda/lib/python2.7/site-packages/pip/__init__.py", line 230, in main
    return command.main(cmd_args)
  File "/usr/local/anaconda/lib/python2.7/site-packages/pip/basecommand.py", line 248, in main
    pip_version_check(session)
  File "/usr/local/anaconda/lib/python2.7/site-packages/pip/utils/outdated.py", line 102, in pip_version_check
    installed_version = get_installed_version("pip")
  File "/usr/local/anaconda/lib/python2.7/site-packages/pip/utils/__init__.py", line 858, in get_installed_version
    working_set = pkg_resources.WorkingSet()
  File "/usr/local/anaconda/lib/python2.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 629, in __init__
    self.add_entry(entry)
  File "/usr/local/anaconda/lib/python2.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 685, in add_entry
    for dist in find_distributions(entry, True):
  File "/usr/local/anaconda/lib/python2.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2075, in find_eggs_in_zip
    if metadata.has_metadata('PKG-INFO'):
  File "/usr/local/anaconda/lib/python2.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 1605, in has_metadata
    return self.egg_info and self._has(self._fn(self.egg_info, name))
  File "/usr/local/anaconda/lib/python2.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 1963, in _has
    return zip_path in self.zipinfo or zip_path in self._index()
  File "/usr/local/anaconda/lib/python2.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 1843, in zipinfo
    return self._zip_manifests.load(self.loader.archive)
  File "/usr/local/anaconda/lib/python2.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 1783, in load
    mtime = os.stat(path).st_mtime
OSError: [Errno 2] No such file or directory: '/usr/local/anaconda/lib/python2.7/site-packages/setuptools-18.1-py2.7.egg'
```

Versions are:

```
$ cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=14.04
DISTRIB_CODENAME=trusty
DISTRIB_DESCRIPTION="Ubuntu 14.04.3 LTS"

$ python -c "import sys; print sys.version"
2.7.10 |Anaconda 2.0.0 (64-bit)| (default, May 28 2015, 17:02:03) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)]

```

**Comment by nehaljwani** [comment]
The `setuptools` package provided in the defaults channel. Use `conda install setuptools`
