### ISSUE TITLE
Spyder crashes while starting in Ananconda Navigator

### ISSUE THREAD

**Issue by srnimani** [ContinuumIO/anaconda-issues#4364]
## Main error
Application <b>spyder</b> launch may have produced errors.
## Traceback
```
Traceback (most recent call last):
  File "/Users/srnimani/miniconda3/lib/python3.5/site-packages/spyder/app/mainwindow.py", line 3067, in main
    mainwindow = run_spyder(app, options, args)
  File "/Users/srnimani/miniconda3/lib/python3.5/site-packages/spyder/app/mainwindow.py", line 2969, in run_spyder
    main.setup()
  File "/Users/srnimani/miniconda3/lib/python3.5/site-packages/spyder/app/mainwindow.py", line 820, in setup
    from spyder.plugins.help import Help
  File "/Users/srnimani/miniconda3/lib/python3.5/site-packages/spyder/plugins/help.py", line 32, in <module>
    from spyder.utils.help.sphinxify import (CSS_PATH, generate_context,
  File "/Users/srnimani/miniconda3/lib/python3.5/site-packages/spyder/utils/help/sphinxify.py", line 32, in <module>
    from sphinx.application import Sphinx
  File "/Users/srnimani/miniconda3/lib/python3.5/site-packages/Sphinx-1.6.2-py3.5.egg/sphinx/application.py", line 38, in <module>
    from sphinx.registry import SphinxComponentRegistry
  File "/Users/srnimani/miniconda3/lib/python3.5/site-packages/Sphinx-1.6.2-py3.5.egg/sphinx/registry.py", line 15, in <module>
    from pkg_resources import iter_entry_points
ImportError: No module named 'pkg_resources'

```
## System information
```
python: 3.6.1
language: en
os: Darwin;16.7.0;Darwin Kernel Version 16.7.0: Thu Jun 15 17:36:27 PDT 2017; root:xnu-3789.70.16~2/RELEASE_X86_64;x86_64;i386
version: 1.6.2
platform: osx-64
qt: 5.6.2
pyqt: 5.6.0
conda: 4.3.24
```

**Comment by ccordoba12** [comment]
Did you use pip to update sphinx?
