### ISSUE TITLE
libreadline needs to link against libtinfo

### ISSUE THREAD

**Issue by dan-blanchard** [ContinuumIO/anaconda-issues#44]
I was trying to create a recipe for `rpy2` over in ContinuumIO/conda-recipes#35 and everything with it works fine until you try to import it:

```
BUILD END: rpy2-2.3.8-py33_0
TEST START: rpy2-2.3.8-py33_0

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    rpy2-2.3.8                 |           py33_0         314 KB

The following packages will be linked:

    package                    |            build
    ---------------------------|-----------------
    openssl-1.0.1c             |                0   hard-link
    python-3.3.3               |                0   hard-link
    readline-6.2               |                0   hard-link
    rpy2-2.3.8                 |           py33_0   hard-link
    sqlite-3.7.13              |                0   hard-link
    system-5.8                 |                1   hard-link
    tk-8.5.13                  |                0   hard-link
    zlib-1.2.7                 |                0   hard-link

Fetching packages ...
rpy2-2.3.8-py33_0.tar.bz2 100% |#################################################################################################################################################| Time: 0:00:00  59.47 MB/s
Extracting packages ...
[      COMPLETE      ] |##############################################################################################################################################################################| 100%
Linking packages ...
[      COMPLETE      ] |##############################################################################################################################################################################| 100%
===== testing package: rpy2-2.3.8-py33_0 =====
import: 'rpy2'
import: 'rpy2.interactive'
Traceback (most recent call last):
  File "/home/dblanchard/anaconda/conda-bld/test-tmp_dir/run_test.py", line 26, in <module>
    import rpy2.interactive
  File "/home/dblanchard/anaconda/envs/_test/lib/python3.3/site-packages/rpy2/interactive/__init__.py", line 13, in <module>
    from rpy2.robjects.packages import _loaded_namespaces
  File "/home/dblanchard/anaconda/envs/_test/lib/python3.3/site-packages/rpy2/robjects/__init__.py", line 15, in <module>
    import rpy2.rinterface as rinterface
  File "/home/dblanchard/anaconda/envs/_test/lib/python3.3/site-packages/rpy2/rinterface/__init__.py", line 102, in <module>
    from rpy2.rinterface._rinterface import *
ImportError: /home/dblanchard/anaconda/envs/_test/lib/python3.3/site-packages/rpy2/rinterface/../../../../libreadline.so.6: undefined symbol: PC
Command failed: /home/dblanchard/anaconda/envs/_test/bin/python3 /home/dblanchard/anaconda/conda-bld/test-tmp_dir/run_test.py
```

From I've found [here](http://trac.sagemath.org/ticket/7610) it looks like it needs to have been compiled with the `DT_NEEDED` flag set for many things to work correctly.

**Comment by jseabold** [comment]
I'm still running into this linking error from readline in multiple places, and it looks like this is mentioned in several issues across the tracker. Currently running *ubuntu 15.10. Fresh conda install. I try to have my conda lib sit in front of my system libraries on LD_LIBRARY_PATH but with this readline problem it's impossible.

**Comment by alexbw** [comment]
+1

**Comment by janssen** [comment]
Same here.  I really need a workaround.

**Comment by janssen** [comment]
I'm on 15.10 with a fresh install of miniconda2.  I'm getting this error message from libreadline.  When I remove the libreadline-6.2 installed in conda, and just let the system's readline-6.3 be the default, things work.

**Comment by elehcim** [comment]
Are there any updates on this? The workaround using the system `libreadline.so` (that is `libreadline.so.6.3`) is the only way?

**Comment by jhunkeler** [comment]
I'm in the same boat:
https://github.com/ContinuumIO/anaconda-recipes/issues/56

**Comment by goanpeca** [comment]
@mingwandroid ?
