### ISSUE TITLE
can't launch spyder

### ISSUE THREAD

**Issue by boazdori** [ContinuumIO/anaconda-issues#4409]
Traceback (most recent call last):
File "C:\Users\user\Anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 3067, in main
mainwindow = run_spyder(app, options, args)
File "C:\Users\user\Anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 2969, in run_spyder
main.setup()
File "C:\Users\user\Anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 899, in setup
from spyder.plugins.variableexplorer import VariableExplorer
File "C:\Users\user\Anaconda3\lib\site-packages\spyder\plugins\variableexplorer.py", line 18, in 
from spyder.widgets.variableexplorer.namespacebrowser import NamespaceBrowser
File "C:\Users\user\Anaconda3\lib\site-packages\spyder\widgets\variableexplorer\namespacebrowser.py", line 25, in 
import ipykernel.pickleutil
File "C:\Users\user\Anaconda3\lib\site-packages\ipykernel\__init__.py", line 2, in 
from .connect import *
File "C:\Users\user\Anaconda3\lib\site-packages\ipykernel\connect.py", line 13, in 
from IPython.core.profiledir import ProfileDir
File "C:\Users\user\Anaconda3\lib\site-packages\IPython\__init__.py", line 55, in 
from .terminal.embed import embed
File "C:\Users\user\Anaconda3\lib\site-packages\IPython\terminal\embed.py", line 15, in 
from IPython.core.interactiveshell import DummyMod, InteractiveShell
File "C:\Users\user\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 61, in 
from IPython.utils import io
File "C:\Users\user\Anaconda3\lib\site-packages\IPython\utils\io.py", line 88, in 
devnull = open(os.devnull, 'w')
FileNotFoundError: [Errno 2] No such file or directory: 'nul'

**Comment by ccordoba12** [comment]
Please update IPython and try again.

**Comment by boazdori** [comment]
updated to the last ipython but still dosn't work
when trying to run ipython i also get the same error
File "C:\Users\user\Anaconda3\lib\site-packages\IPython\utils\io.py", line 88, in
devnull = open(os.devnull, 'w')
FileNotFoundError: [Errno 2] No such file or directory: 'nul'

**Comment by boazdori** [comment]
just to add a few points from the anaconda menue ipython jypter notebook and spyder are not woking giving the same error message

**Comment by boazdori** [comment]
Carlos thanks for you last fully uninstalled all anaconda files ran a clean install of Anaconda3 still the same problem persists unabeling me to use ipython jypter notebook and spyder can use idle i get the same error message
Thnaks

**Comment by ccordoba12** [comment]
No idea what happens in your case. You can take a look at

https://github.com/ipython/ipython/issues/9023
https://github.com/Khroki/MCEdit-Unified/issues/534

**Comment by boazdori** [comment]
Carlos hi,
found the problem under regedit null should be set to 1 i changed that number to 4 recomended for ram management. 
once i changed it back to 1 all is working. 
Thanks again
Boaz

**Comment by ccordoba12** [comment]
Great! Thanks for letting us know about it.
