### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by jaykayn** [ContinuumIO/anaconda-issues#4445]
## Main error
Application <b>spyder</b> launch may have produced errors.
## Traceback
```
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.6/site-packages/qtpy/QtWebEngineWidgets.py", line 22, in <module>
    from PyQt5.QtWebEngineWidgets import QWebEnginePage
ImportError: /opt/anaconda3/lib/python3.6/site-packages/numexpr/../../../libstdc++.so.6: version `CXXABI_1.3.8' not found (required by /usr/lib/x86_64-linux-gnu/libicui18n.so.57)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/anaconda3/bin/spyder", line 6, in <module>
    sys.exit(spyder.app.start.main())
  File "/opt/anaconda3/lib/python3.6/site-packages/spyder/app/start.py", line 103, in main
    from spyder.app import mainwindow
  File "/opt/anaconda3/lib/python3.6/site-packages/spyder/app/mainwindow.py", line 92, in <module>
    from qtpy import QtWebEngineWidgets  # analysis:ignore
  File "/opt/anaconda3/lib/python3.6/site-packages/qtpy/QtWebEngineWidgets.py", line 26, in <module>
    from PyQt5.QtWebKitWidgets import QWebPage as QWebEnginePage
ImportError: /opt/anaconda3/lib/python3.6/site-packages/PyQt5/../../../libQt5WebKit.so.5: symbol _ZN13QSGRenderNodeC2Ev, version Qt_5_PRIVATE_API not defined in file libQt5Quick.so.5 with link time reference

```
## System information
```
python: 3.6.1
language: en_US
os: Linux;4.11.0-kali1-amd64;#1 SMP Debian 4.11.6-1kali1 (2017-06-21);x86_64;
version: 1.6.2
platform: linux-64
qt: 5.8.0
pyqt: 5.6.0
conda: 4.3.22
```

**Comment by goanpeca** [comment]
@ccordoba12 ?

**Comment by ccordoba12** [comment]
Do you have `LD_LIBRARY_PATH` set? I mean, it seems you're mixing Anaconda and system libraries, for example here:

    ... (required by /usr/lib/x86_64-linux-gnu/libicui18n.so.57)

`numexpr` shouldn't try to load that library because Anaconda comes with its own ICU package, so it shouldn't be looked for outside of `/opt/anaconda3/`.

**Comment by goanpeca** [comment]
Stale issue, closing.
