### ISSUE TITLE
Navigator Won't Launch / Spyder and Jupyter Will load and Run Independently

### ISSUE THREAD

**Issue by Sholgar** [ContinuumIO/anaconda-issues#4504]
This is the error message I get. I have  searched but cannot find a solution to the "Main Error" described.  I don't understand the error. Is there a work around? I ran conda update anaconda-navigator....no change. Still dead. Thanks 
************************************************************
An unexpected error occurred on Navigator start-up

Report

Please report this issue in the anaconda issue tracker

Main Error

**unacceptable character #x0000: special characters are not allowed
  in "C:\Users\Kevin\AppData\Local\ContinuumIO\binstar\config.yaml", position 0**
Traceback

Traceback (most recent call last):
  File "C:\Users\Kevin\Anaconda3\lib\site-packages\anaconda_navigator\exceptions.py", line 75, in exception_handler
    return_value = func(*args, **kwargs)
  File "C:\Users\Kevin\Anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 120, in start_app
    window = run_app(splash)
  File "C:\Users\Kevin\Anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 63, in run_app
    window = MainWindow(splash=splash)
  File "C:\Users\Kevin\Anaconda3\lib\site-packages\anaconda_navigator\widgets\main_window.py", line 160, in __init__
    self.api = AnacondaAPI()
  File "C:\Users\Kevin\Anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 1214, in AnacondaAPI
    ANACONDA_API = _AnacondaAPI()
  File "C:\Users\Kevin\Anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 66, in __init__
    self._client_api = ClientAPI()
  File "C:\Users\Kevin\Anaconda3\lib\site-packages\anaconda_navigator\api\client_api.py", line 612, in ClientAPI
    CLIENT_API = _ClientAPI()
  File "C:\Users\Kevin\Anaconda3\lib\site-packages\anaconda_navigator\api\client_api.py", line 82, in __init__
    log_level=logging.NOTSET
  File "C:\Users\Kevin\Anaconda3\lib\site-packages\binstar_client\utils\config.py", line 94, in get_server_api
    config = get_config(remote_site=site)
  File "C:\Users\Kevin\Anaconda3\lib\site-packages\binstar_client\utils\config.py", line 228, in get_config
    file_configs = load_file_configs(SEARCH_PATH)
  File "C:\Users\Kevin\Anaconda3\lib\site-packages\binstar_client\utils\config.py", line 222, in load_file_configs
    raw_data = collections.OrderedDict(kv for kv in itertools.chain.from_iterable(load_paths))
  File "C:\Users\Kevin\Anaconda3\lib\site-packages\binstar_client\utils\config.py", line 222, in 
    raw_data = collections.OrderedDict(kv for kv in itertools.chain.from_iterable(load_paths))
  File "C:\Users\Kevin\Anaconda3\lib\site-packages\binstar_client\utils\config.py", line 202, in _dir_yaml_loader
    yield filepath, load_config(filepath)
  File "C:\Users\Kevin\Anaconda3\lib\site-packages\binstar_client\utils\config.py", line 186, in load_config
    data = yaml.load(fd)
  File "C:\Users\Kevin\Anaconda3\lib\site-packages\yaml\__init__.py", line 70, in load
    loader = Loader(stream)
  File "C:\Users\Kevin\Anaconda3\lib\site-packages\yaml\loader.py", line 34, in __init__
    Reader.__init__(self, stream)
  File "C:\Users\Kevin\Anaconda3\lib\site-packages\yaml\reader.py", line 85, in __init__
    self.determine_encoding()

**Comment by goanpeca** [comment]
HI @Sholgar could you manually remove `C:\Users\Kevin\AppData\Local\ContinuumIO\binstar\config.yaml` and try again?

**Comment by Sholgar** [comment]
Awesome! I'm now a little embarrassed that I couldn't provide you with more of a challenge.  :) 
Your solution worked and all seems to be well. I'm hesitant to delete stuff I don't understand and being a Python/Anaconda newbie doesn't help. I really appreciate the quick and accurate reply. I've been fighting this for few days without success.

regards,
Kevin

**Comment by goanpeca** [comment]
@Sholgar no biggie, glad to be of help and great to hear you are entering the python world, its a great world :-p

**Comment by qx4845** [comment]
I am having a similar issue in Linux Mint 18.2 Cinnamon 64-bit. Spyder launches independently, but when I attempt to launch 'anaconda-navigator' a browser tab opens with the information below. When I search my system for 'config.yaml' I get two results, one located in /anaconda3/lib/python3.6/site-packages/distributed, and another located in /anaconda3/pkgs/distributed-1.16.3-py36_0/lib/python3.6/site-packages/distributed . Should I remove both? If not, which one should I remove? They are both listed as 590 bytes in size. I'm in the same situation: I would rather not remove more files than necessary.

Thanks,
Stephen

Main Error:
byte indices must be integers or slices, not str

Traceback:
Traceback (most recent call last):
  File "/home/stephen/anaconda3/lib/python3.6/site-packages/anaconda_navigator/exceptions.py", line 75, in exception_handler
    return_value = func(*args, **kwargs)
  File "/home/stephen/anaconda3/lib/python3.6/site-packages/anaconda_navigator/app/start.py", line 115, in start_app
    window = run_app(splash)
  File "/home/stephen/anaconda3/lib/python3.6/site-packages/anaconda_navigator/app/start.py", line 58, in run_app
    window = MainWindow(splash=splash)
  File "/home/stephen/anaconda3/lib/python3.6/site-packages/anaconda_navigator/widgets/main_window.py", line 160, in __init__
    self.api = AnacondaAPI()
  File "/home/stephen/anaconda3/lib/python3.6/site-packages/anaconda_navigator/api/anaconda_api.py", line 1205, in AnacondaAPI
    ANACONDA_API = _AnacondaAPI()
  File "/home/stephen/anaconda3/lib/python3.6/site-packages/anaconda_navigator/api/anaconda_api.py", line 65, in __init__
    self._conda_api = CondaAPI()
  File "/home/stephen/anaconda3/lib/python3.6/site-packages/anaconda_navigator/api/conda_api.py", line 1622, in CondaAPI
    CONDA_API = _CondaAPI()
  File "/home/stephen/anaconda3/lib/python3.6/site-packages/anaconda_navigator/api/conda_api.py", line 340, in __init__
    self.set_conda_prefix()
  File "/home/stephen/anaconda3/lib/python3.6/site-packages/anaconda_navigator/api/conda_api.py", line 489, in set_conda_prefix
    self.ROOT_PREFIX = info['root_prefix']
TypeError: byte indices must be integers or slices, not str

**Comment by qx4845** [comment]
I am having a similar issue in Linux Mint 18.2 Cinnamon 64-bit. Spyder launches independently, but when I try to launch 'anaconda-navigator' it opens a browser tab with the information below. I searched for 'config.yaml', and I found two instances of that file. I deleted both of them, but I still get the same error when I attempt to launch 'anaconda-navigator'. Spyder still launches and runs fine. Is there anything else that I could try short of removing and then reinstalling Anaconda from scratch?

Thanks,
Stephen

Main Error:
byte indices must be integers or slices, not str

Traceback:
Traceback (most recent call last):
  File "/home/stephen/anaconda3/lib/python3.6/site-packages/anaconda_navigator/exceptions.py", line 75, in exception_handler
    return_value = func(*args, **kwargs)
  File "/home/stephen/anaconda3/lib/python3.6/site-packages/anaconda_navigator/app/start.py", line 115, in start_app
    window = run_app(splash)
  File "/home/stephen/anaconda3/lib/python3.6/site-packages/anaconda_navigator/app/start.py", line 58, in run_app
    window = MainWindow(splash=splash)
  File "/home/stephen/anaconda3/lib/python3.6/site-packages/anaconda_navigator/widgets/main_window.py", line 160, in __init__
    self.api = AnacondaAPI()
  File "/home/stephen/anaconda3/lib/python3.6/site-packages/anaconda_navigator/api/anaconda_api.py", line 1205, in AnacondaAPI
    ANACONDA_API = _AnacondaAPI()
  File "/home/stephen/anaconda3/lib/python3.6/site-packages/anaconda_navigator/api/anaconda_api.py", line 65, in __init__
    self._conda_api = CondaAPI()
  File "/home/stephen/anaconda3/lib/python3.6/site-packages/anaconda_navigator/api/conda_api.py", line 1622, in CondaAPI
    CONDA_API = _CondaAPI()
  File "/home/stephen/anaconda3/lib/python3.6/site-packages/anaconda_navigator/api/conda_api.py", line 340, in __init__
    self.set_conda_prefix()
  File "/home/stephen/anaconda3/lib/python3.6/site-packages/anaconda_navigator/api/conda_api.py", line 489, in set_conda_prefix
    self.ROOT_PREFIX = info['root_prefix']
TypeError: byte indices must be integers or slices, not str
