### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by zixiyaqi** [ContinuumIO/anaconda-issues#4612]
## Main error
Application <b>spyder</b> launch may have produced errors.
## Traceback
```
Traceback (most recent call last):
  File "H:\Anaconda3\Scripts\spyder-script.py", line 3, in <module>
    import spyder.app.start
  File "H:\Anaconda3\lib\site-packages\spyder\app\start.py", line 21, in <module>
    from spyder.config.base import get_conf_path, running_in_mac_app
  File "H:\Anaconda3\lib\site-packages\spyder\config\base.py", line 362, in <module>
    _ = get_translation("spyder")
  File "H:\Anaconda3\lib\site-packages\spyder\config\base.py", line 334, in get_translation
    language = load_lang_conf()
  File "H:\Anaconda3\lib\site-packages\spyder\config\base.py", line 315, in load_lang_conf
    lang = get_interface_language()
  File "H:\Anaconda3\lib\site-packages\spyder\config\base.py", line 286, in get_interface_language
    spyder_languages = get_available_translations()
  File "H:\Anaconda3\lib\site-packages\spyder\config\base.py", line 257, in get_available_translations
    error = _('Update LANGUAGE_CODES (inside config/base.py) if a new '
NameError: name '_' is not defined

```
## System information
```
python: 3.6.1
language: zh_CN
os: Windows;10;10.0.15063;AMD64;Intel64 Family 6 Model 158 Stepping 9, GenuineIntel
version: 1.6.2
platform: win-64
qt: 5.6.2
pyqt: 5.6.0
conda: 4.3.25
```

**Comment by zixiyaqi** [comment]
已经解决了这个问题。
This problem has been solved.
这是由于我自己安装了汉化资源包导致的。
This is due to my own installation of Chinese Translation.
安装后使用了初始化设置，导致汉化丢失，程序不能启动。
After install this , I used the Initialization settings, which lead to Chinese Translation lost.
The program can't run.
重新安装汉化包即可。
Installing the Chinese Translation again can solve this.
谢谢你们对这个问题的关注。
Thank you all the same for your attention to this question.
