### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by arielgatech** [ContinuumIO/anaconda-issues#4619]
## Main error
Application <b>spyder</b> launch may have produced errors.
## Traceback
```
Traceback (most recent call last):
  File "D:\Program Files\Anaconda\lib\site-packages\spyder\app\mainwindow.py", line 3011, in main
    mainwindow = run_spyder(app, options, args)
  File "D:\Program Files\Anaconda\lib\site-packages\spyder\app\mainwindow.py", line 2913, in run_spyder
    main.setup()
  File "D:\Program Files\Anaconda\lib\site-packages\spyder\app\mainwindow.py", line 766, in setup
    message=_("Spyder Internal Console\n\n"
  File "D:\Program Files\Anaconda\lib\site-packages\spyder\plugins\console.py", line 65, in __init__
    light_background=light_background)
  File "D:\Program Files\Anaconda\lib\site-packages\spyder\widgets\internalshell.py", line 141, in __init__
    profile)
  File "D:\Program Files\Anaconda\lib\site-packages\spyder\widgets\shell.py", line 687, in __init__
    initial_message)
  File "D:\Program Files\Anaconda\lib\site-packages\spyder\widgets\shell.py", line 71, in __init__
    self.history = self.load_history()
  File "D:\Program Files\Anaconda\lib\site-packages\spyder\widgets\shell.py", line 507, in load_history
    if rawhistory[1] != self.INITHISTORY[1]:
IndexError: list index out of range

```
## System information
```
platform: win-64
version: 1.6.2
conda: 4.3.22
qt: 5.6.2
language: en_US
python: 2.7.13
os: Windows;8.1;6.3.9600;AMD64;Intel64 Family 6 Model 60 Stepping 3, GenuineIntel
pyqt: 5.6.0
```

**Comment by goanpeca** [comment]
@ccordoba12 ?

**Comment by ccordoba12** [comment]
This can be fixed by running

    spyder --reset

in a system terminal (i.e. cmd.exe).
