### ISSUE TITLE
Issue with Anaconda Launcher

### ISSUE THREAD

**Issue by pkedrosky** [ContinuumIO/anaconda-issues#462]
Please replace this line with an explanation of what you were attempting to do when you ran into this error

---
## Uncaught Exception

```
Error: spawn conda ENOENT
    at exports._errnoException (util.js:734:11)
    at Process.ChildProcess._handle.onexit (child_process.js:1022:32)
    at child_process.js:1115:20
    at process._tickCallback (node.js:375:11)
```
## Platform Information
- Operating System: darwin
- Conda Version: 3.18.1
- Conda Platform: osx-64

``` json
{
  "channels": [
    "https://repo.continuum.io/pkgs/free/osx-64/",
    "https://repo.continuum.io/pkgs/free/noarch/",
    "https://repo.continuum.io/pkgs/pro/osx-64/",
    "https://repo.continuum.io/pkgs/pro/noarch/"
  ],
  "conda_build_version": "1.11.0",
  "conda_version": "3.18.1",
  "default_prefix": "/Users/pk/anaconda",
  "envs": [],
  "envs_dirs": [
    "/Users/pk/anaconda/envs"
  ],
  "is_foreign": false,
  "pkgs_dirs": [
    "/Users/pk/anaconda/pkgs"
  ],
  "platform": "osx-64",
  "python_version": "2.7.10.final.0",
  "rc_path": null,
  "requests_version": "2.8.0",
  "root_prefix": "/Users/pk/anaconda",
  "root_writable": true,
  "sys_rc_path": "/Users/pk/anaconda/.condarc",
  "user_rc_path": "/Users/pk/.condarc",
  "condaBuildVersion": "1.11.0",
  "condaVersion": "3.18.1",
  "defaultPrefix": "/Users/pk/anaconda",
  "envsDirs": [
    "/Users/pk/anaconda/envs"
  ],
  "isForeign": false,
  "pkgsDirs": [
    "/Users/pk/anaconda/pkgs"
  ],
  "pythonVersion": "2.7.10.final.0",
  "rcPath": null,
  "requestsVersion": "2.8.0",
  "rootPrefix": "/Users/pk/anaconda",
  "rootWritable": true,
  "sysRcPath": "/Users/pk/anaconda/.condarc",
  "userRcPath": "/Users/pk/.condarc"
}
```

**Comment by goanpeca** [comment]
Thanks for reporting. Will look into it

**Comment by goanpeca** [comment]
Launcher is deprecated and has been replaced by Anaconda Navigator. To learn more about it please check the [documentation](https://docs.continuum.io/anaconda/navigator/)

To install please open the Anaconda Prompt/Terminal and type

```
$ conda install anaconda-navigator
```
