### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by LukaJevtovic** [ContinuumIO/anaconda-issues#4628]
## Main error
Application <b>spyder</b> launch may have produced errors.
## Traceback
```
Traceback (most recent call last):
  File "C:\Users\Luka Jevtovic\Anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 3011, in main
    mainwindow = run_spyder(app, options, args)
  File "C:\Users\Luka Jevtovic\Anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 2913, in run_spyder
    main.setup()
  File "C:\Users\Luka Jevtovic\Anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 766, in setup
    message=_("Spyder Internal Console\n\n"
  File "C:\Users\Luka Jevtovic\Anaconda3\lib\site-packages\spyder\plugins\console.py", line 65, in __init__
    light_background=light_background)
  File "C:\Users\Luka Jevtovic\Anaconda3\lib\site-packages\spyder\widgets\internalshell.py", line 141, in __init__
    profile)
  File "C:\Users\Luka Jevtovic\Anaconda3\lib\site-packages\spyder\widgets\shell.py", line 687, in __init__
    initial_message)
  File "C:\Users\Luka Jevtovic\Anaconda3\lib\site-packages\spyder\widgets\shell.py", line 71, in __init__
    self.history = self.load_history()
  File "C:\Users\Luka Jevtovic\Anaconda3\lib\site-packages\spyder\widgets\shell.py", line 507, in load_history
    if rawhistory[1] != self.INITHISTORY[1]:
IndexError: list index out of range

```
## System information
```
python: 3.6.1
language: en_US
os: Windows;10;10.0.15063;AMD64;Intel64 Family 6 Model 42 Stepping 7, GenuineIntel
version: 1.6.2
platform: win-64
qt: 5.6.2
pyqt: 5.6.0
conda: 4.3.21
```

**Comment by goanpeca** [comment]
Try `$  spyder --reset` on the terminal and restart spyder
