### ISSUE TITLE
problem for install conda gurobi7.0.2 pkg

### ISSUE THREAD

**Issue by rosemarye** [ContinuumIO/anaconda-issues#4773]
Anaconda already installed as below 
Python 2.7.13 |Anaconda 4.4.0 (x86_64)| (default, Dec 20 2016, 23:05:08) 
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://anaconda.org
>>> 

Last login: Wed Aug 30 16:24:28 on ttys000
vlan-2604-10-16-21-180:~ RosemaryE$ conda install gurobi
An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Current conda install:

               platform : osx-64
          conda version : 4.3.21
       conda is private : False
      conda-env version : 4.3.21
    conda-build version : not installed
         python version : 2.7.13.final.0
       requests version : 2.14.2
       root environment : /Users/apple/anaconda  (writable)
    default environment : /Users/apple/anaconda
       envs directories : /Users/apple/anaconda/envs
                          /Users/apple/.conda/envs
          package cache : /Users/apple/anaconda/pkgs
                          /Users/apple/.conda/pkgs
           channel URLs : http://conda.anaconda.org/gurobi/osx-64
                          http://conda.anaconda.org/gurobi/noarch
                          https://repo.continuum.io/pkgs/free/osx-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/osx-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/osx-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : /Users/apple/.condarc
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.21 requests/2.14.2 CPython/2.7.13 Darwin/16.6.0 OSX/10.12.5    
                UID:GID : 501:20

`$ /Users/apple/anaconda/bin/conda install gurobi`

    Traceback (most recent call last):
      File "/Users/apple/anaconda/lib/python2.7/site-packages/conda/exceptions.py", line 632, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/Users/apple/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 137, in _main
        exit_code = args.func(args, p)
      File "/Users/apple/anaconda/lib/python2.7/site-packages/conda/cli/main_install.py", line 80, in execute
        install(args, parser, 'install')
      File "/Users/apple/anaconda/lib/python2.7/site-packages/conda/cli/install.py", line 148, in install
        linked_dists = install_linked(prefix)
      File "/Users/apple/anaconda/lib/python2.7/site-packages/conda/core/linked_data.py", line 123, in linked
        return set(linked_data(prefix, ignore_channels=ignore_channels).keys())
      File "/Users/apple/anaconda/lib/python2.7/site-packages/conda/core/linked_data.py", line 115, in linked_data
        load_linked_data(prefix, dist_name, ignore_channels=ignore_channels)
      File "/Users/apple/anaconda/lib/python2.7/site-packages/conda/core/linked_data.py", line 36, in load_linked_data
        rec = json.load(fi)
      File "/Users/apple/anaconda/lib/python2.7/json/__init__.py", line 291, in load
        **kw)
      File "/Users/apple/anaconda/lib/python2.7/json/__init__.py", line 339, in loads
        return _default_decoder.decode(s)
      File "/Users/apple/anaconda/lib/python2.7/json/decoder.py", line 364, in decode
        obj, end = self.raw_decode(s, idx=_w(s, 0).end())
      File "/Users/apple/anaconda/lib/python2.7/json/decoder.py", line 380, in raw_decode
        obj, end = self.scan_once(s, idx)
    ValueError: Expecting object: line 30 column 1 (char 1326)

wondering the reason why i cant install, cant figure it out. Please give some instructions

**Comment by goanpeca** [comment]
@rosemarye could you update to the latest version of conda?

`$ conda update conda`

**Comment by rosemarye** [comment]
well i do not know what is the different between the lasted version and the 7.2 one, since the class requires us to install the7.2 version i'm not sure if i can update or not
