### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by aaryaa** [ContinuumIO/anaconda-issues#4775]
## Main error
Application <b>notebook</b> launch may have produced errors.
## Traceback
```
Error processing line 2 of /home/sujeet/anaconda3/lib/python3.6/site-packages/gapic_google_cloud_datastore_v1-0.15.3-py3.6-nspkg.pth:

  Traceback (most recent call last):
    File "/home/sujeet/anaconda3/lib/python3.6/site.py", line 168, in addpackage
      exec(line)
    File "<string>", line 1, in <module>
  KeyError: 'google'

Remainder of file ignored
Error processing line 2 of /home/sujeet/anaconda3/lib/python3.6/site-packages/gapic_google_cloud_error_reporting_v1beta1-0.15.3-py3.6-nspkg.pth:

  Traceback (most recent call last):
    File "/home/sujeet/anaconda3/lib/python3.6/site.py", line 168, in addpackage
      exec(line)
    File "<string>", line 1, in <module>
  KeyError: 'google'

Remainder of file ignored
Error processing line 2 of /home/sujeet/anaconda3/lib/python3.6/site-packages/gapic_google_cloud_logging_v2-0.91.3-py3.6-nspkg.pth:

  Traceback (most recent call last):
    File "/home/sujeet/anaconda3/lib/python3.6/site.py", line 168, in addpackage
      exec(line)
    File "<string>", line 1, in <module>
  KeyError: 'google'

Remainder of file ignored
Error processing line 2 of /home/sujeet/anaconda3/lib/python3.6/site-packages/gapic_google_cloud_pubsub_v1-0.15.4-py3.6-nspkg.pth:

  Traceback (most recent call last):
    File "/home/sujeet/anaconda3/lib/python3.6/site.py", line 168, in addpackage
      exec(line)
    File "<string>", line 1, in <module>
  KeyError: 'google'

Remainder of file ignored
Error processing line 2 of /home/sujeet/anaconda3/lib/python3.6/site-packages/gapic_google_cloud_spanner_admin_database_v1-0.15.3-py3.6-nspkg.pth:

  Traceback (most recent call last):
    File "/home/sujeet/anaconda3/lib/python3.6/site.py", line 168, in addpackage
      exec(line)
    File "<string>", line 1, in <module>
  KeyError: 'google'

Remainder of file ignored
Error processing line 2 of /home/sujeet/anaconda3/lib/python3.6/site-packages/gapic_google_cloud_spanner_admin_instance_v1-0.15.3-py3.6-nspkg.pth:

  Traceback (most recent call last):
    File "/home/sujeet/anaconda3/lib/python3.6/site.py", line 168, in addpackage
      exec(line)
    File "<string>", line 1, in <module>
  KeyError: 'google'

Remainder of file ignored
Error processing line 2 of /home/sujeet/anaconda3/lib/python3.6/site-packages/gapic_google_cloud_spanner_v1-0.15.3-py3.6-nspkg.pth:

  Traceback (most recent call last):
    File "/home/sujeet/anaconda3/lib/python3.6/site.py", line 168, in addpackage
      exec(line)
    File "<string>", line 1, in <module>
  KeyError: 'google'

Remainder of file ignored
[I 12:42:26.492 NotebookApp] The port 8888 is already in use, trying another port.
[I 12:42:26.493 NotebookApp] The port 8889 is already in use, trying another port.
[I 12:42:26.500 NotebookApp] Serving notebooks from local directory: /home/sujeet
[I 12:42:26.500 NotebookApp] 0 active kernels 
[I 12:42:26.500 NotebookApp] The Jupyter Notebook is running at: http://localhost:8890/?token=9e66357156a2c6869e8209a0fc847e039ae069bdea445dee
[I 12:42:26.500 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 12:42:26.501 NotebookApp] 
    
    Copy/paste this URL into your browser when you connect for the first time,
    to login with a token:
        http://localhost:8890/?token=9e66357156a2c6869e8209a0fc847e039ae069bdea445dee
/usr/bin/google-chrome-stable: /home/sujeet/anaconda3/lib/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by /usr/lib/x86_64-linux-gnu/libmirclient.so.9)
/usr/bin/google-chrome-stable: /home/sujeet/anaconda3/lib/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by /usr/lib/x86_64-linux-gnu/libmirclient.so.9)
/usr/bin/google-chrome-stable: /home/sujeet/anaconda3/lib/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /usr/lib/x86_64-linux-gnu/libmirclient.so.9)
/usr/bin/google-chrome-stable: /home/sujeet/anaconda3/lib/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /usr/lib/x86_64-linux-gnu/libmircommon.so.5)
/usr/bin/google-chrome-stable: /home/sujeet/anaconda3/lib/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by /usr/lib/x86_64-linux-gnu/libmircommon.so.5)
/usr/bin/google-chrome-stable: /home/sujeet/anaconda3/lib/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /usr/lib/x86_64-linux-gnu/libmircommon.so.5)
/usr/bin/google-chrome-stable: /home/sujeet/anaconda3/lib/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by /usr/lib/x86_64-linux-gnu/libmirprotobuf.so.3)
/usr/bin/google-chrome-stable: /home/sujeet/anaconda3/lib/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /usr/lib/x86_64-linux-gnu/libmirprotobuf.so.3)
/usr/bin/google-chrome-stable: /home/sujeet/anaconda3/lib/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /usr/lib/x86_64-linux-gnu/libboost_system.so.1.58.0)
/usr/bin/google-chrome-stable: /home/sujeet/anaconda3/lib/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /usr/lib/x86_64-linux-gnu/libprotobuf-lite.so.9)
/usr/bin/google-chrome-stable: /home/sujeet/anaconda3/lib/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /usr/lib/x86_64-linux-gnu/libboost_filesystem.so.1.58.0)
/usr/bin/google-chrome-stable: /home/sujeet/anaconda3/lib/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /usr/lib/x86_64-linux-gnu/libboost_filesystem.so.1.58.0)

```
## System information
```
python: 3.6.1
language: en_IN
os: Linux;4.10.0-32-generic;#36~16.04.1-Ubuntu SMP Wed Aug 9 09:19:02 UTC 2017;x86_64;x86_64
version: 1.6.2
platform: linux-64
qt: 5.6.2
pyqt: 5.6.0
conda: 4.3.25
```

**Comment by goanpeca** [comment]
This seems like an error related to `gapic_google_cloud_datastore_v1` package, please reinstall it

**Comment by amueller** [comment]
Actually, it's an incompatibility between the libstdc++ that gapic_google_cloud_datastore_v1 was built and the one shipped with conda.

**Comment by unnir** [comment]
re-installation did not help

**Comment by unnir** [comment]
re-installation of  gapic_google_cloud_datastore_v1 did not help
