### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by kandooio** [ContinuumIO/anaconda-issues#4785]
## Main error
Application <b>spyder</b> launch may have produced errors.
## Traceback
```
Traceback (most recent call last):
  File "C:\Users\rariyaratnam\AppData\Local\Continuum\Anaconda3\Scripts\spyder-script.py", line 3, in <module>
    import spyder.app.start
  File "C:\Users\rariyaratnam\AppData\Local\Continuum\Anaconda3\lib\site-packages\spyder\app\start.py", line 13, in <module>
    from spyder.config.base import get_conf_path, running_in_mac_app
  File "C:\Users\rariyaratnam\AppData\Local\Continuum\Anaconda3\lib\site-packages\spyder\config\base.py", line 365, in <module>
    _ = get_translation("spyder")
  File "C:\Users\rariyaratnam\AppData\Local\Continuum\Anaconda3\lib\site-packages\spyder\config\base.py", line 345, in get_translation
    _trans = gettext.translation(modname, locale_path, codeset="utf-8")
  File "C:\Users\rariyaratnam\AppData\Local\Continuum\Anaconda3\lib\gettext.py", line 505, in translation
    mofiles = find(domain, localedir, languages, all=True)
  File "C:\Users\rariyaratnam\AppData\Local\Continuum\Anaconda3\lib\gettext.py", line 489, in find
    if os.path.exists(mofile):
  File "C:\Users\rariyaratnam\AppData\Local\Continuum\Anaconda3\lib\genericpath.py", line 19, in exists
    os.stat(path)
ValueError: stat: embedded null character in path

```
## System information
```
python: 3.6.1
language: en_IE
os: Windows;7;6.1.7601;AMD64;Intel64 Family 6 Model 94 Stepping 3, GenuineIntel
version: 1.6.2
platform: win-64
qt: 5.6.2
pyqt: 5.6.0
conda: 4.3.21
```

**Comment by goanpeca** [comment]
@kandooio what version of spyder are you using?

**Comment by kandooio** [comment]
spyder version 3.1.4

**Comment by kandooio** [comment]
Update:

Updated spyder version to 3.2.1 and still getting the same error

**Comment by goanpeca** [comment]
@ccordoba12 ?

**Comment by ccordoba12** [comment]
The problem is in the `os` module, not in Spyder. So I really don't know what's happening.

**Comment by goanpeca** [comment]
Could it be a path length issue since it is installed at `C:\Users\rariyaratnam\AppData\Local\Continuum\Anaconda3\` ?

**Comment by kandooio** [comment]
@goanpeca a pox on my long surname if it is! 

Reinstalling to C:\Users\rariyaratnam\Anaconda2 to see if issue resolves itself.

**Comment by kandooio** [comment]
Can confirm that the issue was path length. Thanks very much for your help @goanpeca
