### ISSUE TITLE
jsonschema not installed properly

### ISSUE THREAD

**Issue by ricklupton** [ContinuumIO/anaconda-issues#481]
I'm trying to install jupyter in a new conda environment using Python 3.4 on Fedora 22, but the jsonschema package does not seem to be installed correctly by conda.

First, I create a new environment and install jupyter:

```console
$ conda create -n test python=3.4                                            
Fetching package metadata: ....
Solving package specifications: .........
Package plan for installation in environment /home/rick/anaconda3/envs/test:

The following NEW packages will be INSTALLED:

    openssl:    1.0.1k-1     
    pip:        7.1.2-py34_0 
    python:     3.4.3-1      
    readline:   6.2-2        
    setuptools: 18.4-py34_0  
    sqlite:     3.8.4.1-1    
    system:     5.8-2        
    tk:         8.5.18-0     
    wheel:      0.26.0-py34_1
    xz:         5.0.5-0      
    zlib:       1.2.8-0      

Proceed ([y]/n)? y

Linking packages ...
[      COMPLETE      ]|#############################################################| 100%

$ source activate test                                                                
discarding /home/rick/anaconda3/bin from PATH
prepending /home/rick/anaconda3/envs/test/bin to PATH

(test)$ conda install jsonschema
Fetching package metadata: ....
Solving package specifications: ...........
Package plan for installation in environment /home/rick/anaconda3/envs/test:

The following NEW packages will be INSTALLED:

    jsonschema: 2.4.0-py34_0

Proceed ([y]/n)? y

Linking packages ...
[      COMPLETE      ]|#############################################################| 100%
```

However, jsonschema is not installed properly -- it looks like the `_version.py` file, which is supposed to be autogenerated, is not present. It can be fixed by installing jsonschema with pip:

```console
(test)$ python -c 'import jsonschema'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/rick/anaconda3/envs/test/lib/python3.4/site-packages/jsonschema/__init__.py", line 22, in <module>
    from jsonschema._version import __version__
ImportError: No module named 'jsonschema._version'

(test)$ ls /home/rick/anaconda3/envs/jupyter/lib/python3.4/site-packages/jsonschema/_version.py
ls: cannot access /home/rick/anaconda3/envs/jupyter/lib/python3.4/site-packages/jsonschema/_version.py: No such file or directory

(test)$ pip install --upgrade jsonschema
Collecting jsonschema
  Using cached jsonschema-2.5.1-py2.py3-none-any.whl
Installing collected packages: jsonschema
  Found existing installation: jsonschema 2.4.0
    DEPRECATION: Uninstalling a distutils installed project (jsonschema) has been deprecated and will be removed in a future version. This is due to the fact that uninstalling a distutils project will only partially uninstall the project.
    Uninstalling jsonschema-2.4.0:
      Successfully uninstalled jsonschema-2.4.0
Successfully installed jsonschema-2.5.1

(test)$ python -c 'import jsonschema
(test)$ ls /home/rick/anaconda3/envs/jupyter/lib/python3.4/site-packages/jsonschema/_version.py
/home/rick/anaconda3/envs/jupyter/lib/python3.4/site-packages/jsonschema/_version.py
```

**Comment by groutr** [comment]
I cannot reproduce this on my 64bit Centos vm.  It imports fine on my machine. However, I can verify that there is no _version.py either.
