### ISSUE TITLE
libstdc++.so.6: version `GLIBCXX_3.4.20' not found

### ISSUE THREAD

**Issue by Juanlu001** [ContinuumIO/anaconda-issues#483]
I have been testing the latest gcc package from Anaconda which should fix several portability issues (https://github.com/conda/conda-recipes/pull/279, thanks to @stuarteberg) for building my conda recipes for FEniCS. However, I am having some problems (at least on Arch Linux and Ubuntu 14.04) where some library calls fail with this error:

```libstdc++.so.6: version `GLIBCXX_3.4.20' not found```

Which happens because Anaconda libstdc++.so.6 is a bit too old:

```bash
$ strings ~/.miniconda3/envs/fenics_test/lib/libstdc++.so.6 | grep GLIBCXX
LIBCXX
GLIBCXX_3.4
GLIBCXX_3.4.1
GLIBCXX_3.4.2
GLIBCXX_3.4.3
GLIBCXX_3.4.4
GLIBCXX_3.4.5
GLIBCXX_3.4.6
GLIBCXX_3.4.7
GLIBCXX_3.4.8
GLIBCXX_3.4.9
GLIBCXX_3.4.10
GLIBCXX_3.4.11
GLIBCXX_3.4.12
GLIBCXX_3.4.13
GLIBCXX_3.4.14
GLIBCXX_3.4.15
GLIBCXX_3.4.16
GLIBCXX_3.4.17
GLIBCXX_3.4.18
GLIBCXX_3.4.19
GLIBCXX_FORCE_NEW
```

(see for instance https://github.com/Juanlu001/fenics-recipes/issues/35 and https://github.com/Juanlu001/fenics-recipes/issues/36)

Is there a way to have a newer version of the library coming with conda? cc @ccordoba12

**Comment by ccordoba12** [comment]
So is this a mismatch between our package and the one that comes in Arch/Ubuntu?

I'm sorry but I don't completely understand the problem :-)

**Comment by ccordoba12** [comment]
I meant our `gcc`

**Comment by Juanlu001** [comment]
Probably so @ccordoba12. The user that reported https://github.com/Juanlu001/fenics-recipes/issues/36 is now unable to use the packages when having `gcc-4.9`, while everything works fine on Ubuntu 14.04 when having `gcc-4.8`.

This problem appeared when I started using Anaconda `gcc`:

```
$ DISPLAY=:0 LIBGL_DEBUG=verbose python demo_poisson.py
Vendor:  Continuum Analytics, Inc.
Package: mkl
Message: trial mode expires in 30 days
Solving linear variational problem.
libGL: screen 0 does not appear to be DRI3 capable
libGL: pci id for fd 4: 10de:0641, driver nouveau
libGL: OpenDriver: trying /usr/lib/x86_64-linux-gnu/dri/tls/nouveau_dri.so
libGL: OpenDriver: trying /usr/lib/x86_64-linux-gnu/dri/nouveau_dri.so
libGL: dlopen /usr/lib/x86_64-linux-gnu/dri/nouveau_dri.so failed
(/home/earanda/anaconda/envs/fenics27/lib/python2.7/site-packages/ufc/../../../libstdc++.so.6:
version `GLIBCXX_3.4.20' not found (required by
/usr/lib/x86_64-linux-gnu/dri/nouveau_dri.so))
libGL: OpenDriver: trying ${ORIGIN}/dri/tls/nouveau_dri.so
libGL: OpenDriver: trying ${ORIGIN}/dri/nouveau_dri.so
libGL: dlopen ${ORIGIN}/dri/nouveau_dri.so failed
(/home/earanda/anaconda/envs/fenics27/lib/python2.7/site-packages/ufc/../../../libstdc++.so.6:
version `GLIBCXX_3.4.20' not found (required by
/usr/lib/x86_64-linux-gnu/dri/nouveau_dri.so))
libGL: OpenDriver: trying /usr/lib/dri/tls/nouveau_dri.so
libGL: OpenDriver: trying /usr/lib/dri/nouveau_dri.so
libGL: dlopen /usr/lib/dri/nouveau_dri.so failed
(/usr/lib/dri/nouveau_dri.so: cannot open shared object file: No such file
or directory)
libGL error: unable to load driver: nouveau_dri.so
libGL error: driver pointer missing
libGL error: failed to load driver: nouveau
libGL: OpenDriver: trying /usr/lib/x86_64-linux-gnu/dri/tls/swrast_dri.so
libGL: OpenDriver: trying /usr/lib/x86_64-linux-gnu/dri/swrast_dri.so
libGL: dlopen /usr/lib/x86_64-linux-gnu/dri/swrast_dri.so failed
(/home/earanda/anaconda/envs/fenics27/lib/python2.7/site-packages/ufc/../../../libstdc++.so.6:
version `GLIBCXX_3.4.20' not found (required by
/usr/lib/x86_64-linux-gnu/dri/swrast_dri.so))
libGL: OpenDriver: trying ${ORIGIN}/dri/tls/swrast_dri.so
libGL: OpenDriver: trying ${ORIGIN}/dri/swrast_dri.so
libGL: dlopen ${ORIGIN}/dri/swrast_dri.so failed
(/home/earanda/anaconda/envs/fenics27/lib/python2.7/site-packages/ufc/../../../libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by
/usr/lib/x86_64-linux-gnu/dri/swrast_dri.so))
libGL: OpenDriver: trying /usr/lib/dri/tls/swrast_dri.so
libGL: OpenDriver: trying /usr/lib/dri/swrast_dri.so
libGL: dlopen /usr/lib/dri/swrast_dri.so failed
(/usr/lib/dri/swrast_dri.so: cannot open shared object file: No such file
or directory)
libGL error: unable to load driver: swrast_dri.so
libGL error: failed to load driver: swrast
X Error of failed request:  BadValue (integer parameter out of range for
operation)
  Major opcode of failed request:  156 (GLX)
  Minor opcode of failed request:  3 (X_GLXCreateContext)
  Value in failed request:  0x0
  Serial number of failed request:  58
  Current serial number in output stream:  59
```

As you can see, libGL is failing to load because a graphic cards driver requires a newer version of `GLIBCXX`.

On Arch Linux a similar problem appears, but it's mixed with the fact that it's loading boost from the system instead of the one available in Anaconda. It's an unrelated issue (?) but it eventually causes the discussed one:

```
$ LD_LIBRARY_PATH= python ~/.miniconda3/envs/fenics_test/share/dolfin/demo/documented/poisson/python/demo_poisson.py 
In instant.import_module_directly: Failed to import module 'dolfin_compile_code_c8b988ab6016262c9eebd6dc8482b98c0cf05c33' from '/home/juanlu/.instant/cache';
ImportError:/home/juanlu/.miniconda3/envs/fenics_test/lib/python2.7/site-packages/ufc/../../../libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /usr/lib/libboost_filesystem.so.1.58.0);
Failed to import module found in cache. Modulename: 'dolfin_compile_code_c8b988ab6016262c9eebd6dc8482b98c0cf05c33';
Path: '/home/juanlu/.instant/cache';
ImportError:/home/juanlu/.miniconda3/envs/fenics_test/lib/python2.7/site-packages/ufc/../../../libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /usr/lib/libboost_filesystem.so.1.58.0);
Traceback (most recent call last):
  File "/home/juanlu/.miniconda3/envs/fenics_test/share/dolfin/demo/documented/poisson/python/demo_poisson.py", line 54, in <module>
    f = Expression("10*exp(-(pow(x[0] - 0.5, 2) + pow(x[1] - 0.5, 2)) / 0.02)")
  File "/home/juanlu/.miniconda3/envs/fenics_test/lib/python2.7/site-packages/dolfin/functions/expression.py", line 602, in __new__
    mpi_comm=mpi_comm)
  File "/home/juanlu/.miniconda3/envs/fenics_test/lib/python2.7/site-packages/dolfin/compilemodules/expressions.py", line 217, in compile_expressions
    mpi_comm=mpi_comm)
  File "/home/juanlu/.miniconda3/envs/fenics_test/lib/python2.7/site-packages/dolfin/compilemodules/expressions.py", line 145, in compile_expression_code
    mpi_comm=mpi_comm)
  File "/home/juanlu/.miniconda3/envs/fenics_test/lib/python2.7/site-packages/dolfin/compilemodules/jit.py", line 64, in mpi_jit
    return local_jit(*args, **kwargs)
  File "/home/juanlu/.miniconda3/envs/fenics_test/lib/python2.7/site-packages/dolfin/compilemodules/compilemodule.py", line 411, in compile_extension_module
    compiled_module = instant.import_module(module_name)
  File "/home/juanlu/.miniconda3/envs/fenics_test/lib/python2.7/site-packages/instant/cache.py", line 171, in import_module
    return check_disk_cache(modulename, cache_dir, moduleids)
  File "/home/juanlu/.miniconda3/envs/fenics_test/lib/python2.7/site-packages/instant/cache.py", line 139, in check_disk_cache
    module = import_and_cache_module(path, modulename, moduleids)
  File "/home/juanlu/.miniconda3/envs/fenics_test/lib/python2.7/site-packages/instant/cache.py", line 87, in import_and_cache_module
    instant_assert(module is not None, "Failed to import module found in cache. Modulename: '%s';\nPath: '%s';\n%s:%s;" % (modulename, path, type(e).__name__, e))
  File "/home/juanlu/.miniconda3/envs/fenics_test/lib/python2.7/site-packages/instant/output.py", line 91, in instant_assert
    raise AssertionError(text)
AssertionError: Failed to import module found in cache. Modulename: 'dolfin_compile_code_c8b988ab6016262c9eebd6dc8482b98c0cf05c33';
Path: '/home/juanlu/.instant/cache';
ImportError:/home/juanlu/.miniconda3/envs/fenics_test/lib/python2.7/site-packages/ufc/../../../libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /usr/lib/libboost_filesystem.so.1.58.0);
```

**Comment by stuarteberg** [comment]
The anaconda `gcc` and `libgcc` packages are made with `gcc 4.8.5`.  That means they use `libstdc++` version `3.4.19` (See [here](https://gcc.gnu.org/onlinedocs/libstdc++/manual/abi.html).)

If one of your packages is trying to find symbols from `libstdc++` version `3.4.20`, then you must have built that package using your own version of `gcc` and/or `libstdc++` (i.e. you used your OS's version of `libstdc++`, not the version from Anaconda.

Looking at the FEniCS recipes, I notice a few issues.  You should update all of your recipes to follow the rules below, at least when building C++ packages

- In `meta.yaml`, always include `gcc` as a `build` dependency, never a `run` dependency.
- If the recipe requires `gcc` to build, then you must list `libgcc` as `run` dependency.
- In your `build.sh`, **make sure** you are using the anaconda-provided `gcc` binary as your compiler.  Do this by setting the `CC` and `CXX` variables at the top of your build script.  For example:

```
CC=${PREFIX}/bin/gcc
CXX=${PREFIX}/bin/g++

./configure --prefix=${PREFIX}
make
make install
```

For CMake-based projects, you can set these at configure time:

```
mkdir build
cd build
cmake .. \
    -DCMAKE_C_COMPILER=${PREFIX}/bin/gcc \
    -DCMAKE_CXX_COMPILER=${PREFIX}/bin/g++ \
    -DCMAKE_INSTALL_PREFIX=${PREFIX} \
    ........

make
make install
```

Finally, regarding glibc compatibility (not C++ compatibility):  It's worth noting that the Anaconda maintainers build everything on CentOS 5.11.  That way, the resulting binaries always run on newer versions of Linux.  I do the same for my own packages.

**Comment by stuarteberg** [comment]
>On Arch Linux a similar problem appears, but it's mixed with the fact that it's loading boost from the system instead of the one available in Anaconda.

You should fix this by helping the `dolphin` build scripts locate the correct copy of `boost`.  It looks like you may be able to do this via an environment variable:

https://bitbucket.org/fenics-project/dolfin/src/fe82e5a5ffa4a5625b327bfdbdd60084a6847699/CMakeLists.txt?at=master&fileviewer=file-view-default#CMakeLists.txt-306

(That's a little weird to me.)  In my own recipes, I usually pass some cache variables to the cmake step, which are recognized by cmake's `find_package(Boost)` function.  See, for example:
https://github.com/ilastik/ilastik-build-conda/blob/master/vigra/build.sh#L48

**Comment by Juanlu001** [comment]
Thanks a lot for your advice @stuarteberg, it's very much appreciated. This was my first real world experience with compilers so a little bit of help is very valuable :) I will try and implement these changes in the following days.

**Comment by Juanlu001** [comment]
Let's talk about these specific issues elsewhere though.

**Comment by stuarteberg** [comment]
>As you can see, libGL is failing to load because a graphic cards driver requires a newer version of GLIBCXX.

As an experiment, I wonder what happens if you manually replace the `anaconda/envs/fenics27/lib/libstdc++.so.6` with a symlink to your OS's copy of `libstdc++.so.6`.  If that works, then perhaps you could come up with a hack to apply that as a post-install step for the environments you create.

**Comment by ccordoba12** [comment]
@Juanlu001, I'm afraid that even after following @stuarteberg advice you're going to keep having the same problems.

And that's because Fenics is trying to load `libGL`. Since it can't find it in Anaconda, it looks for it on the systen, only to to find that it was compiled with a newer gcc :-(

**Comment by stuarteberg** [comment]
>@Juanlu001, I'm afraid that even after following @stuarteberg advice you're going to keep having the same problems.

I agree with Carlos.  I think your best option is to try the experiment I mentioned above, unless anyone has other ideas.

**Comment by Juanlu001** [comment]
>> @Juanlu001, I'm afraid that even after following @stuarteberg advice you're going to keep having the same problems.

> I agree with Carlos. I think your best option is to try the experiment I mentioned above, unless anyone has other ideas.

I see. Actually visualization support via VTK is a major blocking point for building the packages on anaconda.org, so it seems I will have to devise some hack as @stuarteberg suggested before, or state that it is not portable at all.

Thanks again for your input!

**Comment by ccordoba12** [comment]
I made our latest VTK package (6.3.0) to depend on a new `mesa` package. If I understand things correctly, this avoids depending on the system GL implementation.

Maybe that fixes your problems :-)

**Comment by Juanlu001** [comment]
> I made our latest VTK package (6.3.0) to depend on a new `mesa` package. If I understand things correctly, this avoids depending on the system GL implementation.

That is music for my ears :) Will keep you posted with my progress.

**Comment by Juanlu001** [comment]
@ccordoba12 I have found that trying to compile against VTK 6 complains about missing `/usr/lib64/libGLU.so`, which I think is related to mesa. Even if I install the proper package with `apt-get` it will still complain because I would have to create a symbolic link to `/usr/lib/x86_64-linux-gnu/libGLU.so.1` (see http://packages.ubuntu.com/trusty/amd64/libglu1-mesa/filelist), so it's another source of non-portability, if I am correct. How can we check if it's actually a problem in conda `mesa`?

**Comment by epifanio** [comment]
Hi, not sure if relevant ... but i just built a debian package for a software library on debian jessie (it was a clean installation using gcc from the jessie repository). After installing the deb on an other debian jessie os but that uses anaconda as python distribution. Running the software everything works fine except for some part of its python c/wrapper library (it uses cython), the error is reported here:

```
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-11-90e929814cac> in <module>()
----> 1 from grass.pygrass.vector import Vector
      2 import grass.script as gscript
      3 
      4 
      5 elevation = 'elevation'

/usr/local/grass-7.0.2svn/etc/python/grass/pygrass/vector/__init__.py in <module>()
      3 import grass.lib.gis as libgis
      4 libgis.G_gisinit('')
----> 5 import grass.lib.vector as libvect
      6 
      7 #

/usr/local/grass-7.0.2svn/etc/python/grass/lib/vector.py in <module>()
     21 # Begin libraries
     22 
---> 23 _libs["grass_vector.7.0.2svn"] = load_library("grass_vector.7.0.2svn")
     24 
     25 # 1 libraries

/usr/local/grass-7.0.2svn/etc/python/grass/lib/ctypes_loader.pyc in load_library(self, libname)
     53         for path in paths:
     54             if os.path.exists(path):
---> 55                 return self.load(path)
     56 
     57         raise ImportError,"%s not found." % libname

/usr/local/grass-7.0.2svn/etc/python/grass/lib/ctypes_loader.pyc in load(self, path)
     69                 return ctypes.cdll.LoadLibrary(path)
     70         except OSError as e:
---> 71             raise ImportError,e
     72 
     73     def getpaths(self,libname):

ImportError: /home/main/anaconda/lib/./libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /usr/lib/libgdal.so.1)
```

**Comment by Juanlu001** [comment]
I'm closing this issue since it is a mixture of portability problems and something that doesn't quite work with VTK/mesa. Since I think I solved the former, I'm closing this and will try to investigate further the latter.

**Comment by ccordoba12** [comment]
Thanks for letting us know about it.

**Comment by rmanak** [comment]
`conda install libgcc` solved this problem for me!

**Comment by gstecca** [comment]
thanks @rmanak  the same command solved everything for me! `conda install libgcc`
I started to have the problem after upgrading Anaconda to version 3.4.2.0 64 bit linux on ubuntu 16.04. The error shown up when I tried to start jupyter notebook. Unistall and reinstall anaconda did not resolve. 
If I try now to update/upgrade Anaconda, conda will downgrade library libgcc and the problem returns ... For now just going perfect without upgrades :-)

**Comment by kirk86** [comment]
For me the issue is still there if I try to install latest tensorflow from pip  instead of conda channels which have only outdated versions.

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/user/miniconda2/envs/yt8m/lib/python2.7/site-packages/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import *
  File "/home/user/miniconda2/envs/yt8m/lib/python2.7/site-packages/tensorflow/python/__init__.py", line 72, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/home/user/miniconda2/envs/yt8m/lib/python2.7/site-packages/tensorflow/python/__init__.py", line 61, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/home/user/miniconda2/envs/yt8m/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 28, in <module>
    _pywrap_tensorflow = swig_import_helper()
  File "/home/user/miniconda2/envs/yt8m/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow', fp, pathname, description)
ImportError: /lib64/libc.so.6: version `GLIBC_2.16' not found (required by /home/user/miniconda2/envs/yt8m/lib/python2.7/site-packages/tensorflow/python/_pywrap_tensorflow.so)
```

**Comment by stuarteberg** [comment]
@kirk86 That error refers to `GLIBC` symbol, not  `GLIBCXX`, so the problem is different.  My guess is that the latest version of tensorflow available from pip is not compatible with your OS.  What OS are you using?

Your error indicates that your copy of `_pywrap_tensorflow.so` requires at least `glibc` 2.16.
For example, `Ubuntu 12.10` is too old:
https://distrowatch.com/table.php?distribution=ubuntu

I think your options are:

- Use conda's tensorflow bindings
- Compile the tensorflow bindings on your own
- Upgrade your OS, and then use pip to obtain the bindings.

**Comment by kirk86** [comment]
@stuarteberg thanks for your helpful insight. I'm on a cluster with limited permissions. The OS is CentOS 6.6 final. I think from your suggestions the last two bullet points are out of question since I've tried before compile things but failed completely because the OS is missing some packages and I can't install anything. As for your first bullet point, would you ming providing some more info on how to accomplish that? Thanks!

**Comment by stuarteberg** [comment]
@kirk86 
>As for your first bullet point, would you mind providing some more info
I am not a tensorflow expert, but is there any reason you can't just use `conda install tensorflow`?

**Comment by kirk86** [comment]
@stuarteberg `conda install tensorflow` installs version 0.10rc0 and I need version 1.0 for some project

**Comment by stuarteberg** [comment]
>I need version 1.0 for some project

I see.  In that case, I think the other two bullet points are your only options.  (I just checked conda-forge, (`conda install -c conda-forge tensorflow`) but they are still using 0.12.1.)

Tensorflow 1.0.0 was released very recently.  I would guess that Anaconda and/or conda-forge will update their package for it soon.

**Comment by kirk86** [comment]
@stuarteberg thanks for heads up. I'll try to the other two bullet points and see I can make something out of them. Hopefully anaconda won't take too long to update. Usually they have this tendency trying not to brake compatibility

**Comment by msarahan** [comment]
@kirk86 this problem is happening because the Tensorflow builds on PyPI are built with Ubuntu 16.04.  The way that GLIBC compatibility works is that packages built on old glibc are forward compatible.  Thus, the official Tensorflow builds are only compatible with Ubuntu 16.04 and up.

You can use a docker image to get past this, or you can wait on conda packages.  Note that conda-forge's packages are just a re-packaging of the Pip wheels, and will have the same problems.  Continuum is working on new conda packages built from source, and we hope to have these out next week.

**Comment by kirk86** [comment]
@msarahan thank you for your helpful insight. I remember that I also faced the exact problem that you mention with packages from conda-forge. Everything would install fine but then when I would drop into an ipython kernel tying to import the equivalent package I would get a kernel error. I'm excited to see that you guys are on top of the problem. Looking forward for next week. Would we have to uninstall and install conda or would a `conda update --all` suffice?

**Comment by stuarteberg** [comment]
>this problem is happening because the Tensorflow builds on PyPI are built with Ubuntu 16.04.

Interesting.  Based on the above `GLIBC` error, you're clearly correct.  But I'm confused: The tensorflow PyPI page uses the word "manylinux":
https://pypi.python.org/pypi/tensorflow

And I thought that is supposed to imply CentOS-5 compatibility.  Do you know what's going on?

**Comment by msarahan** [comment]
auditwheel thinks this is valid, but auditwheel is wrong:

```
tensorflow-1.0.0-cp27-cp27mu-manylinux1_x86_64.whl is consistent with
the following platform tag: "manylinux1_x86_64".

The wheel references external versioned symbols in these system-
provided shared libraries: libstdc++.so.6 with versions
{'GLIBCXX_3.4.17', 'GLIBCXX_3.4.15', 'GLIBCXX_3.4.19',
'GLIBCXX_3.4.11', 'CXXABI_1.3', 'GLIBCXX_3.4', 'GLIBCXX_3.4.9',
'GLIBCXX_3.4.14', 'CXXABI_1.3.5', 'GLIBCXX_3.4.18'}, libc.so.6 with
versions {'GLIBC_2.14', 'GLIBC_2.3.2', 'GLIBC_2.10', 'GLIBC_2.9',
'GLIBC_2.16', 'GLIBC_2.6', 'GLIBC_2.2.5', 'GLIBC_2.4', 'GLIBC_2.3',
'GLIBC_2.17', 'GLIBC_2.7', 'GLIBC_2.11', 'GLIBC_2.3.4'}, librt.so.1
with versions {'GLIBC_2.2.5'}, libdl.so.2 with versions
{'GLIBC_2.2.5'}, libm.so.6 with versions {'GLIBC_2.2.5'},
libgcc_s.so.1 with versions {'GCC_3.0'}, libpthread.so.0 with versions
{'GLIBC_2.3.2', 'GLIBC_2.2.5', 'GLIBC_2.3.4'}

The following external shared libraries are required by the wheel:
{
    "libc.so.6": "/lib64/libc-2.5.so",
    "libdl.so.2": "/lib64/libdl-2.5.so",
    "libgcc_s.so.1": "/usr/local/lib64/libgcc_s.so.1",
    "libm.so.6": "/lib64/libm-2.5.so",
    "libpthread.so.0": "/lib64/libpthread-2.5.so",
    "librt.so.1": "/lib64/librt-2.5.so",
    "libstdc++.so.6": "/usr/local/lib64/libstdc++.so.6.0.21"
}
```

Those GLIBC symbols > 2.5 mean that it's not compatible with centOS 5, and thus should not be a valid manylinux wheel under the 

>  work on a stock CentOS 5.11 [6] system that contains the system package manager's provided versions of these libraries.

qualification (https://www.python.org/dev/peps/pep-0513/)

I don't know why auditwheel permits those symbols.

**Comment by msarahan** [comment]
Further, compatibility with CentOS 5 is dubious for GPU support, as the past couple of versions of have dropped CentOS5 support.  The oldest linux distro I know of that they still support is SLES 11 (glibc 2.11)

**Comment by stuarteberg** [comment]
Thanks for the info about `auditwheel`, Mike.

**Comment by merl-dev** [comment]
Had the same problem today building tensorflow ubuntu16, got 

> ImportError: /home/ubuntu/anaconda3/bin/../lib/libstdc++.so.6: version `GLIBCXX_3.4.21' not found >>(required by /home/ubuntu/anaconda3/lib/python3.6/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so)

resolved by 
```
conda install libgcc
```

**Comment by mataney** [comment]
> conda install libgcc
I needed to uninstall and install again.

**Comment by pitybea** [comment]
conda uninstall gcc
conda install -c serge-sans-paille gcc_49

saved me

**Comment by alexattia** [comment]
I tried both @pitybea and @mataney solutions and both didn't work for me.

**Comment by Ryanglambert** [comment]
I tried pitybea's solution and it worked.  I'm on aws using the dlami image (ami-c27af5ba)

For the 3 thumbsdowners maybe take a look at what I have installed maybe that helps: 

```
# Name                    Version                   Build  Channel
absl-py                   0.1.10                    <pip>
argh                      0.26.2                    <pip>
asn1crypto                0.24.0                   py36_0  
autovizwidget             0.12.5           py36hb2c7800_0  
bazel                     0.8.1                         0    conda-forge
blas                      1.1                    openblas    conda-forge
bleach                    2.0.0                      py_1    conda-forge
bleach                    1.5.0                     <pip>
bokeh                     0.12.14                  py36_0  
boto3                     1.5.34                    <pip>
botocore                  1.8.48                    <pip>
bzip2                     1.0.6                         1    conda-forge
ca-certificates           2017.08.26           h1d4fec5_0  
cairo                     1.14.12              h77bcde2_0  
certifi                   2018.1.18                py36_0  
cffi                      1.11.4           py36h9745a5d_0  
chardet                   3.0.4            py36h0f667ec_1  
cloog                     0.18.1                        1    serge-sans-paille
cryptography              2.1.4            py36hd09be54_0  
cycler                    0.10.0                    <pip>
daiquiri                  1.3.0                     <pip>
dbus                      1.10.22                       0    conda-forge
decorator                 4.1.2                    py36_0    conda-forge
decorator                 4.2.1                     <pip>
docutils                  0.14                      <pip>
entrypoints               0.2.3                    py36_1    conda-forge
environment-kernels       1.1.1                     <pip>
expat                     2.2.5                he0dffb1_0  
ffmpeg                    3.4                  h7264315_0  
fontconfig                2.12.4               h88586e7_1  
freetype                  2.8                  hab7d2ae_1  
gcc_49                    4.9.1                         6    serge-sans-paille
gettext                   0.19.8.1                      0    conda-forge
giflib                    5.1.4                         0    conda-forge
glib                      2.53.6               h5d9569c_2  
gmp                       6.1.2                         0    conda-forge
graphite2                 1.3.10               hf63cedd_1  
graphviz                  2.40.1               h25d223c_0  
grpcio                    1.8.3                     <pip>
gst-plugins-base          1.8.0                         0    conda-forge
gstreamer                 1.8.0                         0  
h5py                      2.7.1                    py36_2    conda-forge
harfbuzz                  1.7.4                hc5b324e_0  
hdf5                      1.10.1                        2    conda-forge
hdijupyterutils           0.12.5           py36hc0bb8fd_0  
html5lib                  0.9999999                 <pip>
html5lib                  1.0.1                      py_0    conda-forge
icu                       58.2                 h9c2bf20_1  
idna                      2.6              py36h82fb2a8_1  
intel-openmp              2018.0.0             hc7b2577_8  
ipykernel                 4.8.2                    py36_0    conda-forge
ipython                   6.2.1                    py36_1    conda-forge
ipython_genutils          0.2.0                    py36_0    conda-forge
ipywidgets                7.1.2                    py36_0  
isl                       0.12.2                        0  
jasper                    1.900.1                       4    conda-forge
jedi                      0.11.1                   py36_0    conda-forge
jinja2                    2.10                     py36_0    conda-forge
jmespath                  0.9.3                     <pip>
jpeg                      9b                   h024ee3a_2  
jsonschema                2.6.0                    py36_1    conda-forge
jupyter_client            5.2.2                    py36_0    conda-forge
jupyter_core              4.4.0                      py_0    conda-forge
Keras                     2.1.4                     <pip>
krb5                      1.14.2               hcdc1b81_6  
libedit                   3.1                  heed3624_0  
libffi                    3.2.1                hd88cf55_4  
libgcc                    7.2.0                h69d50b8_2  
libgcc-ng                 7.2.0                h7cc24e2_2  
libgfortran               3.0.0                         1  
libgfortran-ng            7.2.0                h9f7466a_2  
libiconv                  1.15                          0    conda-forge
libopus                   1.2.1                hb9ed12e_0  
libpng                    1.6.34               hb9fc6fc_0  
libprotobuf               3.4.1                h5b8497f_0  
libsodium                 1.0.15                        1    conda-forge
libstdcxx-ng              7.2.0                h7a57d05_2  
libtiff                   4.0.9                h28f6b97_0  
libtool                   2.4.6                h544aabb_3  
libvpx                    1.6.1                h888fd40_0  
libwebp                   0.5.2                         7    conda-forge
libxcb                    1.12                 hcd93eb1_4  
libxml2                   2.9.7                h26e45fe_0  
Markdown                  2.6.11                    <pip>
markupsafe                1.0                      py36_0    conda-forge
matplotlib                2.1.2                     <pip>
mistune                   0.8.3                      py_0    conda-forge
mkl                       2018.0.1             h19d6760_4  
mpc                       1.0.3                hec55b23_5  
mpfr                      3.1.5                h11a74b3_2  
nb_conda                  2.2.1                    py36_0    conda-forge
nb_conda_kernels          2.1.0                    py36_0    conda-forge
nbconvert                 5.3.1                      py_1    conda-forge
nbformat                  4.4.0                    py36_0    conda-forge
ncurses                   6.0                  h9df7e31_2  
notebook                  5.4.0                    py36_0    conda-forge
numpy                     1.14.1          py36_blas_openblas_200  [blas_openblas]  conda-forge
openblas                  0.2.20                        7    conda-forge
opencv                    3.3.1            py36h6cbbc71_1  
opencv-python             3.4.0.12                  <pip>
opencv3                   3.1.0                    py36_0    menpo
openjdk                   8.0.121                       1  
openssl                   1.0.2n               hb7f436b_0  
packaging                 16.8             py36ha668100_1  
pandas                    0.22.0           py36hf484d3e_0  
pandoc                    2.1.1                         0    conda-forge
pandocfilters             1.4.2                     <pip>
pandocfilters             1.4.1                    py36_0    conda-forge
pango                     1.41.0               hd475d92_0  
parso                     0.1.1                      py_0    conda-forge
pcre                      8.41                 hc27e229_1  
pexpect                   4.4.0                    py36_0    conda-forge
pickleshare               0.7.4                    py36_0    conda-forge
Pillow                    5.0.0                     <pip>
pip                       9.0.1            py36h6c6f9ce_4  
pixman                    0.34.0               hceecf20_3  
plotly                    2.4.0                    py36_0  
prompt_toolkit            1.0.15                   py36_0    conda-forge
protobuf                  3.5.1                     <pip>
protobuf                  3.5.0                    py36_1    conda-forge
psycopg2                  2.7.4                     <pip>
ptyprocess                0.5.2                    py36_0    conda-forge
py4j                      0.10.4                    <pip>
pycparser                 2.18             py36hf9f622e_1  
pygal                     2.4.0                     <pip>
pygments                  2.2.0                    py36_0    conda-forge
pykerberos                1.1.14           py36h84109d8_2  
pyopenssl                 17.5.0           py36h20ba746_0  
pyparsing                 2.2.0            py36hee85983_1  
pysocks                   1.6.7            py36hd97a5b1_1  
pyspark                   2.2.1                     <pip>
python                    3.6.4                hc3d631a_1  
python-dateutil           2.6.1                    py36_0    conda-forge
pytz                      2018.3                   py36_0  
pyyaml                    3.12             py36hafb9ca4_1  
pyzmq                     17.0.0                   py36_3    conda-forge
qt                        4.8.7                         4  
readline                  7.0                  ha6073c6_4  
requests                  2.18.4           py36he2e5f8d_1  
requests-kerberos         0.11.0           py36h333c0e5_1  
s3transfer                0.1.13                    <pip>
scikit-learn              0.19.1           py36h7aa7ec6_0  
scipy                     1.0.0            py36hbf646e7_0  
scipy                     1.0.0                     <pip>
send2trash                1.5.0                      py_0    conda-forge
setuptools                38.5.1                   py36_0  
simplegeneric             0.8.1                    py36_0    conda-forge
six                       1.11.0                   py36_1    conda-forge
sparkmagic                0.12.5           py36h8c657a7_0  
SQLAlchemy                1.2.3                     <pip>
sqlite                    3.22.0               h1bed415_0  
tensorboard               1.0.0a4                   <pip>
tensorflow-gpu            1.5.0                     <pip>
tensorflow-tensorboard    1.5.1                     <pip>
terminado                 0.8.1                    py36_0    conda-forge
testpath                  0.3.1                    py36_0    conda-forge
tk                        8.6.7                hc745277_3  
tornado                   4.5.3                    py36_0    conda-forge
traitlets                 4.3.2                    py36_0    conda-forge
urllib3                   1.22             py36hbe7ace6_0  
wcwidth                   0.1.7                    py36_0    conda-forge
webencodings              0.5.1                     <pip>
webencodings              0.5                      py36_0    conda-forge
Werkzeug                  0.14.1                    <pip>
wheel                     0.30.0           py36hfd4bba0_1  
widgetsnbextension        3.1.4                    py36_0  
x264                      20131217                      3    conda-forge
xz                        5.2.3                h55aa19d_2  
yaml                      0.1.7                had09818_2  
zeromq                    4.2.3                         2    conda-forge
zlib                      1.2.11               ha838bed_2 
```

**Comment by williford** [comment]
Just a note - I received this error when using dlib. It was being thrown by the system's libstdc++.so.6 file, even though I had `conda install libgcc`. I found out if I import dlib immediately, then it correctly uses the conda env's `libstdc++.so.6` file.
