### ISSUE TITLE
Importing sasl fails on machines with a different minor version of libsasl

### ISSUE THREAD

**Issue by mcg1969** [ContinuumIO/anaconda-issues#4848]
```
$ python
Python 3.5.3 |Continuum Analytics, Inc.| (default, Mar  6 2017, 11:58:13)
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import sasl
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/wakari/projects/mg796775/admin_11/envs/default/lib/python3.5/site-packages/sasl/__init__.py", line 15, in <module>
    from sasl.saslwrapper import *
ImportError: libsasl2.so.2: cannot open shared object file: No such file or directory
>>>
$ cat /etc/redhat-release
Red Hat Enterprise Linux Server release 7.2 (Maipo)
```
The problem here is quite straightforward: the required library does not exist; rather, a newer version is present:
```
$ ls -l /lib/libsasl*
lrwxrwxrwx. 1 root root     17 Mar 25  2016 /lib/libsasl2.so.3 -> libsasl2.so.3.0.0
-rwxr-xr-x. 1 root root 115708 Dec  4  2015 /lib/libsasl2.so.3.0.0
```
But the fact remains that this package is broken on any machine that demands that specific minor release of libsasl. Thoughts?

**Comment by mingwandroid** [comment]
I cannot reproduce this.

**Comment by mingwandroid** [comment]
```
ls -l /usr/lib64/libsasl2.so.2*
lrwxrwxrwx. 1 root root     18 Jun 21 23:54 /usr/lib64/libsasl2.so.2 -> libsasl2.so.2.0.23
-rwxr-xr-x. 1 root root 108728 Mar 25  2015 /usr/lib64/libsasl2.so.2.0.23
```

```
conda create -n py35sasl python=3.5 sasl
```

Launch Python REPL and enter:
```
>>> from sasl.saslwrapper import *
```

.. leave it running and open another shell, find the process id of python:
```
ps aux|grep python
ray       2800  0.0  0.4 326404 19328 ?        S    21:13   0:00 python /usr/share/system-config-printer/applet.py
ray       3473  0.0  0.2 151380  7912 pts/0    S+   21:15   0:00 python
ray       3489  0.0  0.0 105372   856 pts/1    S+   21:15   0:00 grep python
```

List the loaded shared libraries of 3473:
```
lsof -p 3473 | grep "\.so\|.dylib" | tr -s " " | cut -f9 -d' ' | sort | xargs md5sum | sed -r 's|(MD5 \()([0-9a-zA-Z/.+\_-]*)\) = ([0-9a-f]*)|\3 \2|g' | sort
```

.. gives:

```
091249a2a28be524759311fb9e93236f  /lib64/libpthread-2.12.so
09ddd3f3e1e5cf5e00b6fbca1e6a6e59  /usr/lib64/libstdc++.so.6.0.13
0b3b0188b45343313da6b5a0b4507ee1  /home/ray/mc-x64-3.6/envs/py35sasl/lib/libpython3.5m.so.1.0
1090e2a67ff36f9383e1beef97eaa314  /usr/lib64/libsasl2.so.2.0.23
1130104740577a2fb2a26c1b28b43c0f  /home/ray/mc-x64-3.6/envs/py35sasl/lib/python3.5/lib-dynload/readline.cpython-35m-x86_64-linux-gnu.so
20af976a20273f1572e23378ee946608  /lib64/libm-2.12.so
2abad390f77cc036e995bfc276afe592  /lib64/libdl-2.12.so
35d08df7278520cca28f1201636aae0a  /lib64/libutil-2.12.so
5225dfdd46a65a0d9cb27d9b95c1eb51  /home/ray/mc-x64-3.6/envs/py35sasl/lib/python3.5/lib-dynload/_heapq.cpython-35m-x86_64-linux-gnu.so
69153737a0a5c25c63a6bff09e5dd68b  /home/ray/mc-x64-3.6/envs/py35sasl/lib/python3.5/site-packages/sasl/saslwrapper.cpython-35m-x86_64-linux-gnu.so
692c8fb49ff4b033310922feca82d94d  /lib64/librt-2.12.so
6e7c3c9a3aa2a515f7a3923d65ea9e7c  /lib64/ld-2.12.so
87f319513461158c0d06bed8655cd8ae  /home/ray/mc-x64-3.6/envs/py35sasl/lib/libreadline.so.6.2
8e89ff1f1c968fa4bcb9cc6f0eb1cffc  /home/ray/mc-x64-3.6/envs/py35sasl/lib/python3.5/lib-dynload/_struct.cpython-35m-x86_64-linux-gnu.so
8fcd93566dc4af742b4474e3fce7fbfa  /lib64/libtinfo.so.5.7
91edfe295897371f771f477a76467789  /lib64/libfreebl3.so
96bc55b015b97119a9554c7a3ed4e7d2  /lib64/libresolv-2.12.so
b7049a764bd4c6f56ca3942c00f020b3  /lib64/libcrypt-2.12.so
b8292d0c08805b2109f5bc3394ac10b1  /lib64/libncursesw.so.5.7
fa2ee3b6d869a539394805b87bac76b9  /lib64/libc-2.12.so
fff3bb1da0648512327d02cd8a7ffdf1  /lib64/libgcc_s-4.4.7-20120601.so.1
```

**Comment by jjhelmus** [comment]
But the sasl package is looking for libsas2.so.2 library to be provided by the system:

```
(root) ~$ conda create -n foo python=3.5 sasl
Fetching package metadata .........
Solving package specifications: .

Package plan for installation in environment /home/jhelmus/anaconda3/envs/foo:

The following NEW packages will be INSTALLED:

    openssl:  1.0.2l-0      defaults
    python:   3.5.4-0       defaults
    readline: 6.2-2         defaults
    sasl:     0.2.1-py35_0  defaults
    six:      1.10.0-py35_0 defaults
    sqlite:   3.13.0-0      defaults
    tk:       8.5.18-0      defaults
    xz:       5.2.3-0       defaults
    zlib:     1.2.11-0      defaults

Proceed ([y]/n)? y

#
# To activate this environment, use:
# > source activate foo
#
# To deactivate an active environment, use:
# > source deactivate
#

(root) ~$ conda inspect linkages -n foo sasl
sasl
----

python-3.5.4-0:
    libpython3.5m.so.1.0 (lib/libpython3.5m.so.1.0)

system:
    libc.so.6 (/lib/x86_64-linux-gnu/libc.so.6)
    libdl.so.2 (/lib/x86_64-linux-gnu/libdl.so.2)
    libgcc_s.so.1 (/lib/x86_64-linux-gnu/libgcc_s.so.1)
    libm.so.6 (/lib/x86_64-linux-gnu/libm.so.6)
    libpthread.so.0 (/lib/x86_64-linux-gnu/libpthread.so.0)
    librt.so.1 (/lib/x86_64-linux-gnu/librt.so.1)
    libsasl2.so.2 (/usr/lib/x86_64-linux-gnu/libsasl2.so.2)
    libstdc++.so.6 (/usr/lib/x86_64-linux-gnu/libstdc++.so.6)
    libutil.so.1 (/lib/x86_64-linux-gnu/libutil.so.1)
    linux-vdso.so.1 ()

not found:


(root) ~$ readelf -d ~/anaconda3/envs/foo/lib/python3.5/site-packages/sasl/saslwrapper.cpython-35m-x86_64-linux-gnu.so

Dynamic section at offset 0x11610 contains 27 entries:
  Tag        Type                         Name/Value
 0x0000000000000001 (NEEDED)             Shared library: [libsasl2.so.2]
 0x0000000000000001 (NEEDED)             Shared library: [libpython3.5m.so.1.0]
 0x0000000000000001 (NEEDED)             Shared library: [libstdc++.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [libm.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [libgcc_s.so.1]
 0x0000000000000001 (NEEDED)             Shared library: [libpthread.so.0]
 0x0000000000000001 (NEEDED)             Shared library: [libc.so.6]
 0x000000000000000f (RPATH)              Library rpath: [$ORIGIN/../../..]
 0x000000000000000c (INIT)               0x4238
 0x000000000000000d (FINI)               0xf5f8
 0x000000006ffffef5 (GNU_HASH)           0x158
 0x0000000000000005 (STRTAB)             0x14a0
 0x0000000000000006 (SYMTAB)             0x300
 0x000000000000000a (STRSZ)              5277 (bytes)
 0x000000000000000b (SYMENT)             24 (bytes)
 0x0000000000000003 (PLTGOT)             0x211918
 0x0000000000000002 (PLTRELSZ)           2976 (bytes)
 0x0000000000000014 (PLTREL)             RELA
 0x0000000000000017 (JMPREL)             0x3698
 0x0000000000000007 (RELA)               0x2b58
 0x0000000000000008 (RELASZ)             2880 (bytes)
 0x0000000000000009 (RELAENT)            24 (bytes)
 0x000000006ffffffe (VERNEED)            0x2ab8
 0x000000006fffffff (VERNEEDNUM)         4
 0x000000006ffffff0 (VERSYM)             0x293e
 0x000000006ffffff9 (RELACOUNT)          80
 0x0000000000000000 (NULL)               0x0
```

**Comment by mingwandroid** [comment]
Yeah, we don't have our own libsasl at all here AFAICT!

**Comment by mcg1969** [comment]
Other people have encountered this: https://github.com/cloudera/impyla/issues/237

We are indeed relying on system libsasl2.

**Comment by jjhelmus** [comment]
Can we use libgsasl as a replacement for libsasl2?

**Comment by mcg1969** [comment]
I don't think so, I don't think they are API compatible, are they?

**Comment by jjhelmus** [comment]
No, I don't think they are compatible and the `sasl` python package is explicit in it's need for the `sasl2` library.

**Comment by mingwandroid** [comment]
We have a recipe for cyrus-sasl: https://github.com/conda/conda-recipes/tree/master/cyrus-sasl

**Comment by mcg1969** [comment]
OK, then perhaps what we need to do is build that, put it on defaults, and change this recipe to depend on it.

**Comment by allyelsey** [comment]
I've run into this issue is there any workaround?

**Comment by jjhelmus** [comment]
cyrus-sasl is available on defaults as well as a new version of sasl which has the correct requirements. These versions should fix this issue.  

@allyelsey can you provide more details on the environment where you are seeing this issue?  The output of `conda list` and `conda info` would be most helpful.

**Comment by ssweety387** [comment]
@Jonathan, It was reported by a customer.
It looks like they are using the latest version of sasl.
Here is the question :
We are trying to write a python script to connect to hive and query the hive tables. For this we created a new environment and installed pyhive package using conda install command. When we installed the pyhive package the dependencies (future, sasl,thrift & thrift_sasl) also got installed
```pyhive: 0.4.0-py27_0 
future: 0.16.0-py27_1
sasl: 0.2.1-py27_0
thrift: 0.10.0-py27_0
thrift_sasl: 0.2.1-py27_0
```
Now when we try to import the package from the python prompt, we are getting the below error:
```
-bash-4.2$ /anaconda-efs/envs/cap_int_py27_hive_test/bin/python
Python 2.7.13 |Continuum Analytics, Inc.| (default, Dec 20 2016, 23:09:15)
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://anaconda.org
>>> from pyhive import hive
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "/anaconda-efs/envs/cap_int_py27_hive_test/lib/python2.7/site-packages/pyhive/hive.py", line 22, in <module>
import sasl
File "/anaconda-efs/envs/cap_int_py27_hive_test/lib/python2.7/site-packages/sasl/__init__.py", line 15, in <module>
from sasl.saslwrapper import *
ImportError: libsasl2.so.2: cannot open shared object file: No such file or directory 
 ```
Looks like there is a dependency on libsasl2.so.2 library. But this library doesn't exists.

**Comment by saraneem** [comment]
@Jonathan, It was reported by a customer.
It looks like they are using the latest version of sasl.
Here is the question :
>We are trying to write a python script to connect to hive and query the hive tables. For this we created a new environment and installed pyhive package using conda install command. When we installed the pyhive package the dependencies (future, sasl,thrift & thrift_sasl) also got installed
```
pyhive: 0.4.0-py27_0 
future: 0.16.0-py27_1
sasl: 0.2.1-py27_0
thrift: 0.10.0-py27_0
thrift_sasl: 0.2.1-py27_0
```
>Now when we try to import the package from the python prompt, we are getting the below error:
```
-bash-4.2$ /anaconda-efs/envs/cap_int_py27_hive_test/bin/python
Python 2.7.13 |Continuum Analytics, Inc.| (default, Dec 20 2016, 23:09:15)
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://anaconda.org
>>> from pyhive import hive
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "/anaconda-efs/envs/cap_int_py27_hive_test/lib/python2.7/site-packages/pyhive/hive.py", line 22, in <module>
import sasl
File "/anaconda-efs/envs/cap_int_py27_hive_test/lib/python2.7/site-packages/sasl/__init__.py", line 15, in <module>
from sasl.saslwrapper import *
ImportError: libsasl2.so.2: cannot open shared object file: No such file or directory 
 ```
>Looks like there is a dependency on libsasl2.so.2 library. But this library doesn't exists.

**Comment by jjhelmus** [comment]
@saraneem The `sasl: 0.2.1-py27_0` package is known to be bad, the latest one, `sasl: 0.2.1            py27h4575015_0` has the fix described here.  Can the customer update to this version.  The new package is in the `main` channel which will not be available below conda 4.3.27 without manually adding the repository. 

I noticed that the build numbers for the two packages are the same which can cause some issues in conda.  I'm uploading a new build `_1` of sasl that should fix this.

**Comment by jjhelmus** [comment]
`sasl-0.2.1-py27hf484d3e_1` and related packages are now available in the main sub-channel of `defaults`.
