### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by cbirdferrer** [ContinuumIO/anaconda-issues#4857]
## Main error
Application <b>spyder</b> launch may have produced errors.
## Traceback
```
Traceback (most recent call last):
  File "/Users/clarabirdferrer/anaconda/lib/python3.6/site-packages/qtpy/QtWebEngineWidgets.py", line 22, in <module>
    from PyQt5.QtWebEngineWidgets import QWebEnginePage
ImportError: dlopen(/Users/clarabirdferrer/anaconda/lib/python3.6/site-packages/PyQt5/QtWebEngineWidgets.so, 2): Library not loaded: @rpath/libQt5WebEngineCore.5.dylib
  Referenced from: /Users/clarabirdferrer/anaconda/lib/python3.6/site-packages/PyQt5/QtWebEngineWidgets.so
  Reason: image not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/clarabirdferrer/anaconda/bin/spyder", line 6, in <module>
    sys.exit(spyder.app.start.main())
  File "/Users/clarabirdferrer/anaconda/lib/python3.6/site-packages/spyder/app/start.py", line 135, in main
    from spyder.app import mainwindow
  File "/Users/clarabirdferrer/anaconda/lib/python3.6/site-packages/spyder/app/mainwindow.py", line 92, in <module>
    from qtpy import QtWebEngineWidgets  # analysis:ignore
  File "/Users/clarabirdferrer/anaconda/lib/python3.6/site-packages/qtpy/QtWebEngineWidgets.py", line 26, in <module>
    from PyQt5.QtWebKitWidgets import QWebPage as QWebEnginePage
ModuleNotFoundError: No module named 'PyQt5.QtWebKitWidgets'

```
## System information
```
python: 3.6.1
language: en
os: Darwin;16.7.0;Darwin Kernel Version 16.7.0: Thu Jun 15 17:36:27 PDT 2017; root:xnu-3789.70.16~2/RELEASE_X86_64;x86_64;i386
version: 1.6.2
platform: osx-64
qt: 5.6.2
pyqt: 5.6.0
conda: 4.3.23
```

**Comment by ccordoba12** [comment]
You need to install `libselinux` using your package manager to fix this problem.

**Comment by ccordoba12** [comment]
Sorry, that's for Linux.

**Comment by ccordoba12** [comment]
Did you install pyqt5 using pip?

**Comment by goanpeca** [comment]
Tracking on: https://github.com/ContinuumIO/anaconda-issues/issues/7230
