### ISSUE TITLE
h5py conda package no longer tied to Numpy version, causing issues

### ISSUE THREAD

**Issue by astrofrog** [ContinuumIO/anaconda-issues#486]
Since yesterday, I'm seeing the following warning when installing a group of dependencies that includes h5py and Numpy:

```
Warning: 2 possible package resolutions (only showing differing packages):
	[u'h5py-2.5.0-py27_3.tar.bz2'],
	[u'h5py-2.5.0-np19py27_3.tar.bz2'],
```

The one that gets installed is the one not tied to Numpy:

```
    h5py-2.5.0                 |           py27_3         2.4 MB
```

But this then causes issues later on:

```
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/home/travis/miniconda/envs/test/lib/python2.7/site-packages/_pytest/main.py", line 88, in wrap_session
INTERNALERROR>     config.hook.pytest_sessionstart(session=session)
INTERNALERROR>   File "/home/travis/miniconda/envs/test/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 724, in __call__
INTERNALERROR>     return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
INTERNALERROR>   File "/home/travis/miniconda/envs/test/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 338, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/home/travis/miniconda/envs/test/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 333, in <lambda>
INTERNALERROR>     _MultiCall(methods, kwargs, hook.spec_opts).execute()
INTERNALERROR>   File "/home/travis/miniconda/envs/test/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 596, in execute
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/home/travis/miniconda/envs/test/lib/python2.7/site-packages/_pytest/terminal.py", line 293, in pytest_sessionstart
INTERNALERROR>     config=self.config, startdir=self.startdir)
INTERNALERROR>   File "/home/travis/miniconda/envs/test/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 724, in __call__
INTERNALERROR>     return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
INTERNALERROR>   File "/home/travis/miniconda/envs/test/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 338, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/home/travis/miniconda/envs/test/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 333, in <lambda>
INTERNALERROR>     _MultiCall(methods, kwargs, hook.spec_opts).execute()
INTERNALERROR>   File "/home/travis/miniconda/envs/test/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 596, in execute
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/home/travis/build/glue-viz/glue/glue/conftest.py", line 33, in pytest_report_header
INTERNALERROR>     return os.linesep + glue_version + os.linesep + os.linesep + get_status()
INTERNALERROR>   File "/home/travis/build/glue-viz/glue/glue/_deps.py", line 157, in get_status
INTERNALERROR>     s += str(dep) + os.linesep
INTERNALERROR>   File "/home/travis/build/glue-viz/glue/glue/_deps.py", line 65, in __str__
INTERNALERROR>     status = 'INSTALLED (%s)' % self.version
INTERNALERROR>   File "/home/travis/build/glue-viz/glue/glue/_deps.py", line 37, in version
INTERNALERROR>     module = __import__(self.module)
INTERNALERROR>   File "/home/travis/miniconda/envs/test/lib/python2.7/site-packages/h5py/__init__.py", line 23, in <module>
INTERNALERROR>     from . import _conv
INTERNALERROR>   File "h5py/h5t.pxd", line 14, in init h5py._conv (/home/ilan/minonda/conda-bld/work/h5py/_conv.c:7364)
INTERNALERROR>   File "h5py/numpy.pxd", line 66, in init h5py.h5t (/home/ilan/minonda/conda-bld/work/h5py/h5t.c:20460)
INTERNALERROR> ValueError: numpy.dtype has the wrong size, try recompiling
```

The full log is here: https://travis-ci.org/glue-viz/glue/jobs/86499280

**Comment by astrofrog** [comment]
The issue also happens on mac: https://travis-ci.org/glue-viz/glue/jobs/86499306

**Comment by ilanschnell** [comment]
Thanks.  This should be fixed shortly.

**Comment by DanlanChen** [comment]
Hello, I do not know why i have this same problem:File "h5py/numpy.pxd", line 66, in init h5py.h5t (/home/ilan/minonda/conda-bld/work/h5py/h5t.c:20460)
ValueError: numpy.dtype has the wrong size, try recompiling

**Comment by DanlanChen** [comment]
I am using 1.9.3 numpy version

**Comment by ilanschnell** [comment]
@DanlanChen AFAICT all `h5py` conda packages are tied to a specific `numpy` version.  Which exact versions of packages are you using?  What is the output from `conda list`?  Thanks
