### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by vinipachecov** [ContinuumIO/anaconda-issues#4904]
## Main error
Application <b>spyder</b> launch may have produced errors.
## Traceback
```
Fontconfig error: "/home/vinipachecov/.config/fontconfig/conf.d/99-deepin.conf", line 1: Unsupported version '2.0'

Traceback (most recent call last):
  File "/home/vinipachecov/anaconda3/envs/tensorflow/bin/spyder", line 6, in <module>
    sys.exit(spyder.app.start.main())
  File "/home/vinipachecov/anaconda3/envs/tensorflow/lib/python2.7/site-packages/spyder/app/start.py", line 103, in main
    from spyder.app import mainwindow
  File "/home/vinipachecov/anaconda3/envs/tensorflow/lib/python2.7/site-packages/spyder/app/mainwindow.py", line 49, in <module>
    requirements.check_qt()
  File "/home/vinipachecov/anaconda3/envs/tensorflow/lib/python2.7/site-packages/spyder/requirements.py", line 39, in check_qt
    import qtpy
  File "/home/vinipachecov/anaconda3/envs/tensorflow/lib/python2.7/site-packages/qtpy/__init__.py", line 96, in <module>
    sip.setapi('QString', 2)
ValueError: API 'QString' has already been set to version 1

```
## System information
```
platform: linux-64
version: 1.6.2
conda: 4.3.17
qt: 5.6.2
language: en_US
python: 2.7.13
os: Linux;4.9.0-deepin11-amd64;#1 SMP PREEMPT Deepin 4.9.40-2 (2017-08-12);x86_64;
pyqt: 5.6.0
```

**Comment by ccordoba12** [comment]
Please install Qt5 in your `tensorflow` environment and try again.
