### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by fido2478** [ContinuumIO/anaconda-issues#492]
Error: spawn ENOENT
    at exports._errnoException (util.js:742:11)
    at Process.ChildProcess._handle.onexit (child_process.js:1027:32)
    at child_process.js:1110:20
    at process._tickCallback (node.js:279:11)

**Comment by msarahan** [comment]
Hi, sorry you're having trouble.  This report does not help us investigate your issues very much.  We don't know what application you're trying to use.  We  don't know what platform you're on.  We don't know what version of our software you're trying to use.

**Comment by nehaljwani** [comment]
Closing due to inactivity.
