### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by b007rankin** [ContinuumIO/anaconda-issues#4986]
## Main error
Application <b>spyder</b> launch may have produced errors.
## Traceback
```
Traceback (most recent call last):
  File "c:\programdata\anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\programdata\anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\ProgramData\Anaconda3\Scripts\spyder.exe\__main__.py", line 9, in <module>
  File "c:\programdata\anaconda3\lib\site-packages\spyder\app\start.py", line 135, in main
    from spyder.app import mainwindow
  File "c:\programdata\anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 112, in <module>
    from spyder.utils.qthelpers import qapplication, MENU_SEPARATOR
  File "c:\programdata\anaconda3\lib\site-packages\spyder\utils\qthelpers.py", line 26, in <module>
    from spyder.config.gui import get_shortcut
  File "c:\programdata\anaconda3\lib\site-packages\spyder\config\gui.py", line 29, in <module>
    from spyder.utils import syntaxhighlighters as sh
  File "c:\programdata\anaconda3\lib\site-packages\spyder\utils\syntaxhighlighters.py", line 30, in <module>
    from spyder.utils.workers import WorkerManager
ModuleNotFoundError: No module named 'spyder.utils.workers'

```
## System information
```
python: 3.6.1
language: en_US
os: Windows;10;10.0.15063;AMD64;Intel64 Family 6 Model 60 Stepping 3, GenuineIntel
version: 1.6.2
platform: win-64
qt: 5.6.2
pyqt: 5.6.0
conda: 4.3.25
```

**Comment by goanpeca** [comment]
@b007rankin could you please update to the latest spyder?

`$ conda update spyder`
