### ISSUE TITLE
package update errors

### ISSUE THREAD

**Issue by breisfeld** [ContinuumIO/anaconda-issues#501]
Normally, issuing 

```
$ conda update --all
```

works very well. However, today I got the following errors:

```
...
[      COMPLETE      ]|##################################################| 100%
Unlinking packages ...
menuinst Exception:Traceback (most recent call last):                    |  33%
  File "k:\Python\Anaconda\lib\site-packages\conda\install.py", line 343, in mk_menus
    env_setup_cmd=env_setup_cmd)
  File "k:\Python\Anaconda\lib\site-packages\menuinst\__init__.py", line 44, in install
    env_setup_cmd=env_setup_cmd).remove()
  File "k:\Python\Anaconda\lib\site-packages\menuinst\win32.py", line 105, in remove
    self.create(remove=True)
  File "k:\Python\Anaconda\lib\site-packages\menuinst\win32.py", line 113, in create
    cmd = bat_func('python.exe', self.shortcut["pyscript"].split())
  File "k:\Python\Anaconda\lib\site-packages\menuinst\win32.py", line 80, in write_bat_file
    setup_cmd = setup_cmd.split()  # split into activate cmd + env
AttributeError: 'NoneType' object has no attribute 'split'
menuinst Exception:Traceback (most recent call last):                    |  37%
  File "k:\Python\Anaconda\lib\site-packages\conda\install.py", line 343, in mk_menus
    env_setup_cmd=env_setup_cmd)
  File "k:\Python\Anaconda\lib\site-packages\menuinst\__init__.py", line 44, in install
    env_setup_cmd=env_setup_cmd).remove()
  File "k:\Python\Anaconda\lib\site-packages\menuinst\win32.py", line 105, in remove
    self.create(remove=True)
  File "k:\Python\Anaconda\lib\site-packages\menuinst\win32.py", line 113, in create
    cmd = bat_func('python.exe', self.shortcut["pyscript"].split())
  File "k:\Python\Anaconda\lib\site-packages\menuinst\win32.py", line 80, in write_bat_file
    setup_cmd = setup_cmd.split()  # split into activate cmd + env
AttributeError: 'NoneType' object has no attribute 'split'
menuinst Exception:Traceback (most recent call last):                    |  41%
  File "k:\Python\Anaconda\lib\site-packages\conda\install.py", line 343, in mk_menus
    env_setup_cmd=env_setup_cmd)
  File "k:\Python\Anaconda\lib\site-packages\menuinst\__init__.py", line 44, in install
    env_setup_cmd=env_setup_cmd).remove()
  File "k:\Python\Anaconda\lib\site-packages\menuinst\win32.py", line 105, in remove
    self.create(remove=True)
  File "k:\Python\Anaconda\lib\site-packages\menuinst\win32.py", line 111, in create
    cmd = bat_func('pythonw.exe', self.shortcut["pywscript"].split())
  File "k:\Python\Anaconda\lib\site-packages\menuinst\win32.py", line 80, in write_bat_file
    setup_cmd = setup_cmd.split()  # split into activate cmd + env
AttributeError: 'NoneType' object has no attribute 'split'
menuinst Exception:Traceback (most recent call last):                    |  45%
  File "k:\Python\Anaconda\lib\site-packages\conda\install.py", line 343, in mk_menus
    env_setup_cmd=env_setup_cmd)
  File "k:\Python\Anaconda\lib\site-packages\menuinst\__init__.py", line 44, in install
    env_setup_cmd=env_setup_cmd).remove()
  File "k:\Python\Anaconda\lib\site-packages\menuinst\win32.py", line 105, in remove
    self.create(remove=True)
  File "k:\Python\Anaconda\lib\site-packages\menuinst\win32.py", line 119, in create
    self.shortcut["pyscript"].split())
KeyError: 'pyscript'
[      COMPLETE      ]|##################################################| 100%
Linking packages ...
menuinst Exception:Traceback (most recent call last):##########          |  81%
  File "k:\Python\Anaconda\lib\site-packages\conda\install.py", line 343, in mk_menus
    env_setup_cmd=env_setup_cmd)
  File "k:\Python\Anaconda\lib\site-packages\menuinst\__init__.py", line 51, in install
    env_setup_cmd=env_setup_cmd).create()
  File "k:\Python\Anaconda\lib\site-packages\menuinst\win32.py", line 113, in create
    cmd = bat_func('python.exe', self.shortcut["pyscript"].split())
  File "k:\Python\Anaconda\lib\site-packages\menuinst\win32.py", line 80, in write_bat_file
    setup_cmd = setup_cmd.split()  # split into activate cmd + env
AttributeError: 'NoneType' object has no attribute 'split'
menuinst Exception:Traceback (most recent call last):###############     |  90%
  File "k:\Python\Anaconda\lib\site-packages\conda\install.py", line 343, in mk_menus
    env_setup_cmd=env_setup_cmd)
  File "k:\Python\Anaconda\lib\site-packages\menuinst\__init__.py", line 51, in install
    env_setup_cmd=env_setup_cmd).create()
  File "k:\Python\Anaconda\lib\site-packages\menuinst\win32.py", line 113, in create
    cmd = bat_func('python.exe', self.shortcut["pyscript"].split())
  File "k:\Python\Anaconda\lib\site-packages\menuinst\win32.py", line 80, in write_bat_file
    setup_cmd = setup_cmd.split()  # split into activate cmd + env
AttributeError: 'NoneType' object has no attribute 'split'
menuinst Exception:Traceback (most recent call last):################    |  93%
  File "k:\Python\Anaconda\lib\site-packages\conda\install.py", line 343, in mk_menus
    env_setup_cmd=env_setup_cmd)
  File "k:\Python\Anaconda\lib\site-packages\menuinst\__init__.py", line 51, in install
    env_setup_cmd=env_setup_cmd).create()
  File "k:\Python\Anaconda\lib\site-packages\menuinst\win32.py", line 111, in create
    cmd = bat_func('pythonw.exe', self.shortcut["pywscript"].split())
  File "k:\Python\Anaconda\lib\site-packages\menuinst\win32.py", line 80, in write_bat_file
    setup_cmd = setup_cmd.split()  # split into activate cmd + env
AttributeError: 'NoneType' object has no attribute 'split'
menuinst Exception:Traceback (most recent call last):##################  |  96%
  File "k:\Python\Anaconda\lib\site-packages\conda\install.py", line 343, in mk_menus
    env_setup_cmd=env_setup_cmd)
  File "k:\Python\Anaconda\lib\site-packages\menuinst\__init__.py", line 51, in install
    env_setup_cmd=env_setup_cmd).create()
  File "k:\Python\Anaconda\lib\site-packages\menuinst\win32.py", line 111, in create
    cmd = bat_func('pythonw.exe', self.shortcut["pywscript"].split())
  File "k:\Python\Anaconda\lib\site-packages\menuinst\win32.py", line 80, in write_bat_file
    setup_cmd = setup_cmd.split()  # split into activate cmd + env
AttributeError: 'NoneType' object has no attribute 'split'
[      COMPLETE      ]|##################################################| 100%
```

Platform:
Windows 7: 64 bit.

```
$ conda --version
conda 3.18.3
```

```
$ python
Python 2.7.10 |Anaconda 2.2.0 (64-bit)| (default, Oct 21 2015, 19:35:23) [MSC v.1500 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://anaconda.org
```

**Comment by csoja** [comment]
I'm going to close this issue - due to it being so old and so many new releases since this error report.  Hopefully, this error has long since been fixed.
