### ISSUE TITLE
An error ocurred while starting the kernel

### ISSUE THREAD

**Issue by JbEy41** [ContinuumIO/anaconda-issues#516]
Hi, 

I'm quite new to Python and Anaconda. I use a Mac and I download Python 3-5. I cannot use Spyder-app and I get the following error:

"Error in sitecustomize; set PYTHONVERBOSE for traceback:
TypeError: 'NoneType' object is not callable
Traceback (most recent call last):
File "/Users/NAME/anaconda/lib/python3.5/site‑packages/spyderlib/widgets/externalshell/start_ipython_kernel.py", line 183, in 
from IPython.kernel.zmq.kernelapp import IPKernelApp
File "/Users/NAME/anaconda/lib/python3.5/site‑packages/IPython/__init__.py", line 48, in 
from .terminal.embed import embed
File "/Users/NAMEanaconda/lib/python3.5/site‑packages/IPython/terminal/embed.py", line 16, in 
from IPython.core.interactiveshell import DummyMod
File "/Users/NAME/anaconda/lib/python3.5/site‑packages/IPython/core/interactiveshell.py", line 31, in 
from pickleshare import PickleShareDB
File "/Users/NAME/anaconda/lib/python3.5/site‑packages/pickleshare.py", line 41, in 
from path import path as Path
File "/Users/NAME/anaconda/lib/python3.5/site‑packages/path.py", line 123, in 
__version__ = pkg_resources.require('path.py')[0].version
TypeError: 'NoneType' object is not callable"

Has anyone faced this problem before ? I have tried to uninstall and re-install Anaconda several times but it stil does not work =(.

**Comment by ccordoba12** [comment]
I think you need to run

    conda update setuptools

to fix it.

**Comment by JbEy41** [comment]
Thanks a lit Carlos.

Finally it was just a problem of old bash that were in my lab top. I deleted them and it's working now !

Best regards , 

Envoyé de mon iPhone

**Comment by ccordoba12** [comment]
Ok, thanks for the update

**Comment by adarshkr2510** [comment]
> I think you need to run
> 
> ```
> conda update setuptools
> ```
> 
> to fix it.
getting a error ::-
'conda' is not recognized as an internal or external command,
operable program or batch file.
