### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by sumitbhongale** [ContinuumIO/anaconda-issues#5175]
## Main error
Application <b>notebook</b> launch may have produced errors.
## Traceback
```
[W 22:10:15.237 NotebookApp] Error loading server extension jupyterlab
    Traceback (most recent call last):
      File "C:\Users\Sumit_Bhongale\Anaconda3\lib\site-packages\notebook\notebookapp.py", line 1271, in init_server_extensions
        mod = importlib.import_module(modulename)
      File "C:\Users\Sumit_Bhongale\Anaconda3\lib\importlib\__init__.py", line 126, in import_module
        return _bootstrap._gcd_import(name[level:], package, level)
      File "<frozen importlib._bootstrap>", line 978, in _gcd_import
      File "<frozen importlib._bootstrap>", line 961, in _find_and_load
      File "<frozen importlib._bootstrap>", line 948, in _find_and_load_unlocked
    ModuleNotFoundError: No module named 'jupyterlab'
[I 22:10:15.657 NotebookApp] Serving notebooks from local directory: C:\Users\Sumit_Bhongale
[I 22:10:15.657 NotebookApp] 0 active kernels 
[I 22:10:15.657 NotebookApp] The Jupyter Notebook is running at: http://localhost:8888/?token=0cfe6bced533a13c81dfa01ddc43868a36064a9af5f34505
[I 22:10:15.657 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 22:10:15.675 NotebookApp] 
    
    Copy/paste this URL into your browser when you connect for the first time,
    to login with a token:
        http://localhost:8888/?token=0cfe6bced533a13c81dfa01ddc43868a36064a9af5f34505
[I 22:10:16.213 NotebookApp] Accepting one-time-token-authenticated connection from ::1

```
## System information
```
python: 3.6.1
language: en_US
os: Windows;10;10.0.15063;AMD64;In

**Comment by goanpeca** [comment]
@sumitbhongale you have some install error

`ModuleNotFoundError: No module named 'jupyterlab'`
