### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by mnislam01** [ContinuumIO/anaconda-issues#5189]
An unexpected error occurred on Navigator start-up.

Navigator failing to start-up from launcher bar. But works fine when launched from terminal typing, "anaconda-navigator".
-----------------------------------------------------------
OS: Ubuntu 16.04 amd64
-----------------------------------------------------------
Traceback
-----------------------------------------------------------
Traceback (most recent call last):
  File "/usr/share/anaconda3/lib/python3.6/site-packages/anaconda_navigator/exceptions.py", line 75, in exception_handler
    return_value = func(*args, **kwargs)
  File "/usr/share/anaconda3/lib/python3.6/site-packages/anaconda_navigator/app/start.py", line 115, in start_app
    window = run_app(splash)
  File "/usr/share/anaconda3/lib/python3.6/site-packages/anaconda_navigator/app/start.py", line 58, in run_app
    window = MainWindow(splash=splash)
  File "/usr/share/anaconda3/lib/python3.6/site-packages/anaconda_navigator/widgets/main_window.py", line 160, in __init__
    self.api = AnacondaAPI()
  File "/usr/share/anaconda3/lib/python3.6/site-packages/anaconda_navigator/api/anaconda_api.py", line 1205, in AnacondaAPI
    ANACONDA_API = _AnacondaAPI()
  File "/usr/share/anaconda3/lib/python3.6/site-packages/anaconda_navigator/api/anaconda_api.py", line 65, in __init__
    self._conda_api = CondaAPI()
  File "/usr/share/anaconda3/lib/python3.6/site-packages/anaconda_navigator/api/conda_api.py", line 1622, in CondaAPI
    CONDA_API = _CondaAPI()
  File "/usr/share/anaconda3/lib/python3.6/site-packages/anaconda_navigator/api/conda_api.py", line 340, in __init__
    self.set_conda_prefix()
  File "/usr/share/anaconda3/lib/python3.6/site-packages/anaconda_navigator/api/conda_api.py", line 489, in set_conda_prefix
    self.ROOT_PREFIX = info['root_prefix']
TypeError: byte indices must be integers or slices, not str
-----------------------------------------------------------

**Comment by goanpeca** [comment]
@mnislam01 if you open the terminal and type:

```
$ source activate root
$ anaconda-navigator
```
What is the output?

**Comment by goanpeca** [comment]
@mnislam01 seems to be working fine then. The download_api errors you see are being fixed and soon to be released with 1.6.6
