### ISSUE TITLE
Spyder Launch Error

### ISSUE THREAD

**Issue by lanyuezheng** [ContinuumIO/anaconda-issues#5193]
## Main error
Application <b>spyder</b> launch may have produced errors.
## Traceback
```
Traceback (most recent call last):
  File "/anaconda/lib/python2.7/site-packages/spyder/app/mainwindow.py", line 3011, in main
    mainwindow = run_spyder(app, options, args)
  File "/anaconda/lib/python2.7/site-packages/spyder/app/mainwindow.py", line 2923, in run_spyder
    main.post_visible_setup()
  File "/anaconda/lib/python2.7/site-packages/spyder/app/mainwindow.py", line 1217, in post_visible_setup
    self.historylog.add_history(get_conf_path('history.py'))
  File "/anaconda/lib/python2.7/site-packages/spyder/plugins/history.py", line 232, in add_history
    text, _ = encoding.read(filename)
  File "/anaconda/lib/python2.7/site-packages/spyder/utils/encoding.py", line 243, in read
    text, encoding = decode( open(filename, 'rb').read() )
IOError: [Errno 2] No such file or directory: u'/Users/a3991/.spyder/history.py'

```
## System information
```
platform: osx-64
version: 1.6.2
conda: 4.3.21
qt: 5.6.2
language: en
python: 2.7.13
os: Darwin;15.6.0;Darwin Kernel Version 15.6.0: Thu Jun 23 18:25:34 PDT 2016; root:xnu-3248.60.10~1/RELEASE_X86_64;x86_64;i386
pyqt: 5.6.0
```

**Comment by goanpeca** [comment]
@lanyuezheng please open the temrinal and type

```
$ spyder --reset
```

**Comment by lanyuezheng** [comment]
Thanks! That works!!

 Lan
On Sep 7, 2017, at 8:06 PM, Gonzalo Peña-Castellanos <notifications@github.com<mailto:notifications@github.com>> wrote:


@lanyuezheng<https://github.com/lanyuezheng> please open the temrinal and type

$ spyder --reset
