### ISSUE TITLE
Error launching spyder

### ISSUE THREAD

**Issue by tritemio** [ContinuumIO/anaconda-issues#520]
I just updated spyder on a windows x64 system with python 3.4 and now I get this error launching spyder:

```
C:\Data>spyder
Traceback (most recent call last):
  File "C:\Users\laser2002j\Miniconda3\lib\site-packages\spyderlib\qt\__init__.py", line 48, in <module>
    from PySide import __version__  # analysis:ignore
ImportError: No module named 'PySide'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\laser2002j\Miniconda3\lib\site-packages\spyderlib\requirements.py", line 40, in check_qt
    from spyderlib import qt
  File "C:\Users\laser2002j\Miniconda3\lib\site-packages\spyderlib\qt\__init__.py", line 50, in <module>
    raise ImportError("Spyder requires PySide or PyQt to be installed")
ImportError: Spyder requires PySide or PyQt to be installed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\laser2002j\Miniconda3\Scripts\spyder-script.py", line 2, in <module>
    start_app.main()
  File "C:\Users\laser2002j\Miniconda3\lib\site-packages\spyderlib\start_app.py", line 114, in main
    from spyderlib import spyder
  File "C:\Users\laser2002j\Miniconda3\lib\site-packages\spyderlib\spyder.py", line 48, in <module>
    requirements.check_qt()
  File "C:\Users\laser2002j\Miniconda3\lib\site-packages\spyderlib\requirements.py", line 50, in check_qt
    % (qt_infos['pyqt']+qt_infos['pyside']))
  File "C:\Users\laser2002j\Miniconda3\lib\site-packages\spyderlib\requirements.py", line 25, in show_warning
    raise RuntimeError(message)
RuntimeError: Please check Spyder installation requirements:
PyQt4 4.6+ (or PySide 1.2.0+) is required.
```

This is what is currently installed:

```
C:\Data>conda install spyder
Fetching package metadata: ......
Solving package specifications: .........................
# All requested packages already installed.
# packages in environment at C:\Users\laser2002j\Miniconda3:
#
spyder                    2.3.7                    py34_3
C:\Data>conda install pyqt
Fetching package metadata: ......
Solving package specifications: ....................
# All requested packages already installed.
# packages in environment at C:\Users\laser2002j\Miniconda3:
#
pyqt                      4.11.4                   py34_2
```

**Comment by msarahan** [comment]
Please see #509 and https://github.com/conda/conda/issues/1753 - you need to either activate an environment, or manually alter PATH to have (PREFIX)\Library\bin on it.  We are working on a more transparent fix.

**Comment by tritemio** [comment]
@msarahan thanks. For the record, this is on Windows x64  and on a Miniconda3 installation only a few weeks old (less than 1 month).

**Comment by msarahan** [comment]
Yes, the relative age of the installation doesn't matter, though.  Installers before the Anaconda 2.4 release and Miniconda < 3.18 will exhibit this issue.  These paths are set by the installer, not by Conda, so an installer update was necessary.  We are working on a fix to patch old installations.

**Comment by tritemio** [comment]
Great, thank! I confirm that adding (PREFIX)\Library\bin to the PATH fixed the issue.

**Comment by msarahan** [comment]
This fix has been released as conda-env-2.4.4-1.  It has been tested to work with both user-level, and system-level installations of Miniconda version 3.16 and Anaconda 2.3.  Updating from earlier versions should behave similarly.

You will see a message like:
```
"Ensuring that C:\Users\builder\Miniconda\Library\bin is on user PATH environment variable."

SUCCESS: Specified value was saved.
Please open a new console window to make sure that the new PATH is in effect.
```

when the script runs.  You can view the script in (your prefix)\Scripts\.conda-env-post-link.bat

I'm closing this issue, but feel free to reopen this if the issue remains.

**Comment by necrolph** [comment]
I got similar error after installing graphviz library in my conda.
```
C:\Users\Clement>spyder
Traceback (most recent call last):
  File "C:\Python\Anaconda3\lib\site-packages\spyderlib\qt\__init__.py", line 48
, in <module>
    from PySide import __version__  # analysis:ignore
ImportError: No module named 'PySide'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python\Anaconda3\lib\site-packages\spyderlib\requirements.py", line 4
0, in check_qt
    from spyderlib import qt
  File "C:\Python\Anaconda3\lib\site-packages\spyderlib\qt\__init__.py", line 50
, in <module>
    raise ImportError("Spyder requires PySide or PyQt to be installed")
ImportError: Spyder requires PySide or PyQt to be installed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python\Anaconda3\Scripts\spyder-script.py", line 2, in <module>
    start_app.main()
  File "C:\Python\Anaconda3\lib\site-packages\spyderlib\start_app.py", line 114,
 in main
    from spyderlib import spyder
  File "C:\Python\Anaconda3\lib\site-packages\spyderlib\spyder.py", line 48, in
<module>
    requirements.check_qt()
  File "C:\Python\Anaconda3\lib\site-packages\spyderlib\requirements.py", line 5
0, in check_qt
    % (qt_infos['pyqt']+qt_infos['pyside']))
  File "C:\Python\Anaconda3\lib\site-packages\spyderlib\requirements.py", line 2
5, in show_warning
    raise RuntimeError(message)
RuntimeError: Please check Spyder installation requirements:
PyQt4 4.6+ (or PySide 1.2.0+) is required.
```
My config: windows 8, Spyder 2.3.8
```
C:\Users\Clement>conda info
Using Anaconda Cloud api site https://api.anaconda.org
Current conda install:

             platform : win-64
        conda version : 4.0.5
  conda-build version : 1.18.1
       python version : 3.5.1.final.0
     requests version : 2.9.1
     root environment : C:\Python\Anaconda3  (writable)
  default environment : C:\Python\Anaconda3
     envs directories : C:\Python\Anaconda3\envs
        package cache : C:\Python\Anaconda3\pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/win-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/win-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : None
    is foreign system : False
```
PATH variable already has "C:\Python\Anaconda3\Library\bin", so it won't solve the problem.

**Comment by kr-praveen** [comment]
This error means that you installed pyqt5 with pip along side the pyqt conda package. It could be solved by you uninstalling the pip package.
Try:
pip uninstall PyQt5
Then update conda:
conda update conda
conda update anaconda-navigator

It will surely resolve your problem

**Comment by sergatron** [comment]
> This error means that you installed pyqt5 with pip along side the pyqt conda package. It could be solved by you uninstalling the pip package.
> Try:
> pip uninstall PyQt5
> Then update conda:
> conda update conda
> conda update anaconda-navigator
> 
> It will surely resolve your problem

Yes! Thank you, it worked
