### ISSUE TITLE
Attribute Error: Anaconda on Linux Guest MacOS Sierra Host

### ISSUE THREAD

**Issue by SteveNg2013** [ContinuumIO/anaconda-issues#5202]
I'm running Anaconda on a Linux Mint distribution running as Guest in MacOS Sierra host. Sometime after starting up Anaconda and launching a Jupyter notebook, I keep seeing the following error repeated over and over again -

Traceback (most recent call last):
  File "/home/sng/anaconda3/lib/python3.6/site-packages/anaconda_navigator/api/anaconda_api.py", line 321, in _conda_info_processed
    processed_info = self._process_conda_info(info)
  File "/home/sng/anaconda3/lib/python3.6/site-packages/anaconda_navigator/api/anaconda_api.py", line 432, in _process_conda_info
    processed_info = info.copy()
AttributeError: 'bytes' object has no attribute 'copy'

I've reinstalled both Anaconda and Anaconda-navigator with no improvement.

Some pertinent info -
Anaconda version: Anaconda3-4.4.0-Linux-x86_64
Anaconda-navigator version: 1.6.4
Linux Mint version: LinuxMint18 4.4.0-93-generic #116-Ubuntu
OS-X version: 10.12.6

I am running in preinstalled "root" environment

**Comment by saemundo** [comment]
I'm having the same issue
It's not affecting my work, just an annoyance.
I'm running Anaconda on Ubuntu 16.04

**Comment by goanpeca** [comment]
Are you guys using the latest anaconda-navigator (1.6.9?)

```
$ conda update conda
$ conda update anaconda-navigator
$ conda update navigator-updater
```

**Comment by Fetchered** [comment]
Request re-open, issue not resolved. I'm having the same problem, running the latest version of Conda (4.5.4) anaconda-navigator (1.8.5) and navigator-updater (0.2.0).
Was running 4.5.1, 1.8.1, and 0.1.x before this and still had the same issues. Not resolved in latest version.

Ubuntu 16.04.4
`Traceback (most recent call last):
  File "/home/___/anaconda3/lib/python3.6/site-packages/anaconda_navigator/api/anaconda_api.py", line 438, in _conda_info_processed
    processed_info = self._process_conda_info(info)
  File "/home/___/anaconda3/lib/python3.6/site-packages/anaconda_navigator/api/anaconda_api.py", line 549, in _process_conda_info
    processed_info = info.copy()
AttributeError: 'bytes' object has no attribute 'copy'`

**Comment by HughRunyan** [comment]
same problem, same OS except MATE, everything is updated.

**Comment by dbooth-boston** [comment]
Same problem on Ubuntu 16.04, x86_64.  
> $ anaconda-navigator --version
1.8.7

Could something be getting the wrong version of python?  I had both python2 and python3 installed before installing Anaconda, but Anaconda installed a newer version of python3:

> $ python --version
Python 3.6.5 :: Anaconda, Inc.

Here is the error message from anaconda-navigator:
> QProcessPrivate::createPipe: Cannot create pipe 0x562a4c5eb410: Too many open files
Traceback (most recent call last):
  File "/downloads/anaconda/install/lib/python3.6/site-packages/anaconda_navigator/api/anaconda_api.py", line 438, in _conda_info_processed
    processed_info = self._process_conda_info(info)
  File "/downloads/anaconda/install/lib/python3.6/site-packages/anaconda_navigator/api/anaconda_api.py", line 549, in _process_conda_info
    processed_info = info.copy()
AttributeError: 'bytes' object has no attribute 'copy'

**Comment by knzudgt** [comment]
Same problem on Ubuntu 14.04, x86_64.

    $ anaconda-navigator --version
    1.8.7
    $ python --version
    Python 3.6.5 :: Anaconda, Inc.

The error message is:

    Traceback (most recent call last):
    File "/home/marco/anaconda3/lib/python3.6/site-packages/anaconda_navigator/api/anaconda_api.py", line 438, in _conda_info_processed
    processed_info = self._process_conda_info(info)
    File "/home/marco/anaconda3/lib/python3.6/site-packages/anaconda_navigator/api/anaconda_api.py", line 549, in _process_conda_info
    processed_info = info.copy()
    AttributeError: 'bytes' object has no attribute 'copy'

**Comment by cgodfreyUW** [comment]
Think I'm having the same exact issue:
`Traceback (most recent call last):
  File "/home/charles/anaconda3/lib/python3.6/site-packages/anaconda_navigator/api/anaconda_api.py", line 513, in _conda_info_processed
    processed_info = self._process_conda_info(info)
  File "/home/charles/anaconda3/lib/python3.6/site-packages/anaconda_navigator/api/anaconda_api.py", line 624, in _process_conda_info
    processed_info = info.copy()
AttributeError: 'bytes' object has no attribute 'copy'
QProcessPrivate::createPipe: Cannot create pipe 0x555ed6602810: Too many open files
`
 Running Ubuntu 18.04.
As mentioned by others, it doesn't seem to be causing any problems, just printing a ton of output into the terminal where I started the navigator.

**Comment by mmeier93** [comment]
Has this issue been resolved? I have the exact same problem. It doesn't seem to affect my work in Spyder but who knows, I don't really understand what it means so it is worrying.

Specs:
Ubuntu 18.04
conda version 4.4.11
Anaconda-navigator version 1.9.4
Python version 3.7.0

  ```
 QProcessPrivate::createPipe: Cannot create pipe 0x56189c1b0d80: Too many open files
Traceback (most recent call last):
  File "/home/mmeier/anaconda3/lib/python3.7/site-packages/anaconda_navigator/api/anaconda_api.py", line 495, in _conda_info_processed
    processed_info = self._process_conda_info(info)
  File "/home/mmeier/anaconda3/lib/python3.7/site-packages/anaconda_navigator/api/anaconda_api.py", line 606, in _process_conda_info
    processed_info = info.copy()
AttributeError: 'bytes' object has no attribute 'copy'
```

**Comment by alexandre-rouxel** [comment]
same error message with the following environment:
Ubuntu : 18.04
Python 3.6.8 :: Anaconda, Inc.
anaconda-navigator : 1.9.6

**Comment by soqueroprogramar** [comment]
Same.
Ubuntu:18.04
Linux Kernel: 4.15.0-29-generic
Anaconda-navigator: 1.9.6
Anaconda Command line client: 1.7.2
Jupyter Notebook version : 5.7.4
Python: 3.7.1

Full error: 
Traceback (most recent call last):
  File "/home/use-name/anaconda3/lib/python3.7/site-packages/anaconda_navigator/api/anaconda_api.py", line 496, in _conda_info_processed
    processed_info = self._process_conda_info(info)
  File "/home/user-name/anaconda3/lib/python3.7/site-packages/anaconda_navigator/api/anaconda_api.py", line 607, in _process_conda_info
    processed_info = info.copy()
AttributeError: 'bytes' object has no attribute 'copy'

**Comment by msarahan** [comment]
We've been able to reproduce this problem internally by having insufficient memory on the machine, but we're having a hard time reproducing it other ways.  What are the specs of the machine that you're running on?

**Comment by whamalai** [comment]
Same with me, ubuntu 18.04, conda version 4.6.11. However, my infinite error loop was a bit more informative:
QProcessPrivate::createPipe: Cannot create pipe 0x5640e803b880: Too many open files
Traceback (most recent call last):
  File "/home/wh/anaconda3/lib/python3.7/site-packages/anaconda_navigator/api/anaconda_api.py", line 496, in _conda_info_processed
    processed_info = self._process_conda_info(info)
  File "/home/wh/anaconda3/lib/python3.7/site-packages/anaconda_navigator/api/anaconda_api.py", line 607, in _process_conda_info
    processed_info = info.copy()
AttributeError: 'bytes' object has no attribute 'copy'
QProcessPrivate::createPipe: Cannot create pipe 0x5640e89665f0: Too many open files
...
I had maybe 16 notebooks open and kernels running. I shut down all kernels and the error disappeared. So, it seems it doesn't like too many kernels running at the same time. Memory was not a problem to any extent.

**Comment by mingwandroid** [comment]
You might find a solution by playing around with ulimit:
https://ss64.com/bash/ulimit.html

**Comment by whamalai** [comment]
I thought I had a fix, but too early. Now the same error loop (with the earlier messages) begun even if I had just 2 notebooks open and stopping kernels didn't help. For some reason, the notebook took over 100% of CPU (I wasn't running anything anymore) and jammed.

**Comment by hemangjoshi37a** [comment]
Has anyone found any solution yet???

**Comment by liamr0y** [comment]
Same issue. Using Ubuntu 18.04. Doing the updates doesn't resolve the problem. Any solution yet?

**Comment by mdsadiqueinam** [comment]
Same issue. Using Ubuntu 20.04, with latest version of anaconda, and with only 1 python file open on vscode
and my laptop memory is only 4gb
