### ISSUE TITLE
Unable to launch Spyder via Anaconda navigator

### ISSUE THREAD

**Issue by Shiranthaw** [ContinuumIO/anaconda-issues#5213]
Also tried with "spyder --reset", but no luck.

## Main error
Application <b>spyder</b> launch may have produced errors.
## Traceback
```
Traceback (most recent call last):
  File "C:\Users\Tom\Anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 3067, in main
    mainwindow = run_spyder(app, options, args)
  File "C:\Users\Tom\Anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 2967, in run_spyder
    main = MainWindow(options)
  File "C:\Users\Tom\Anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 338, in __init__
    from spyder.plugins.configdialog import (MainConfigPage,
  File "C:\Users\Tom\Anaconda3\lib\site-packages\spyder\plugins\configdialog.py", line 39, in <module>
    from spyder.widgets.sourcecode.codeeditor import CodeEditor
  File "C:\Users\Tom\Anaconda3\lib\site-packages\spyder\widgets\sourcecode\codeeditor.py", line 58, in <module>
    from spyder.widgets.sourcecode.base import TextEditBaseWidget
  File "C:\Users\Tom\Anaconda3\lib\site-packages\spyder\widgets\sourcecode\base.py", line 35, in <module>
    from spyder.widgets.mixins import BaseEditMixin
  File "C:\Users\Tom\Anaconda3\lib\site-packages\spyder\widgets\mixins.py", line 29, in <module>
    from spyder.py3compat import is_text_string, to_text_string, u
ImportError: cannot import name 'u'

```
## System information
```
python: 3.6.1
language: en_AU
os: Windows;10;10.0.15063;AMD64;Intel64 Family 6 Model 142 Stepping 9, GenuineIntel
version: 1.6.2
platform: win-64
qt: 5.6.2
pyqt: 5.6.0
conda: 4.3.21
```

**Comment by ccordoba12** [comment]
Please run in a system terminal (i.e. `cmd.exe`)

    conda install -f spyder

and try to start Spyder again.

**Comment by Shiranthaw** [comment]
Hello,
Thank you very much. It worked.
Best regards,
Shirantha. 

    On Saturday, 9 September 2017, 4:11, Gonzalo Peña-Castellanos <notifications@github.com> wrote:
 

 Closed #5213.—

**Comment by punvenu** [comment]
It solved my problem as well thank you.

**Comment by Tanmoyray** [comment]
i am trying bt has not worked ...

error:
Traceback (most recent call last):
File "/anaconda3/bin/spyder", line 7, in 
from spyder.app.start import main
File "/anaconda3/lib/python3.6/site-packages/spyder/app/start.py", line 27, in 
from spyder.config.main import CONF
File "/anaconda3/lib/python3.6/site-packages/spyder/config/main.py", line 22, in 
from spyder.config.user import UserConfig
File "/anaconda3/lib/python3.6/site-packages/spyder/config/user.py", line 26, in 
from spyder.utils.programs import check_version
File "/anaconda3/lib/python3.6/site-packages/spyder/utils/programs.py", line 18, in 
import subprocess
File "/anaconda3/lib/python3.6/subprocess.py", line 136, in 
import _posixsubprocess
ImportError: dlopen(/anaconda3/lib/python3.6/lib-dynload/_posixsubprocess.cpython-36m-darwin.so, 2): Symbol not found: __Py_set_inheritable_async_safe
Referenced from: /anaconda3/lib/python3.6/lib-dynload/_posixsubprocess.cpython-36m-darwin.so
Expected in: flat namespace
in /anaconda3/lib/python3.6/lib-dynload/_posixsubprocess.cpython-36m-darwin.so

Please help.

**Comment by daniyal89** [comment]
(base) C:\Users\Daniyal\Anaconda3>spyder
Traceback (most recent call last):
  File "C:\Users\Daniyal\Anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 3126, in main
    mainwindow = run_spyder(app, options, args)
  File "C:\Users\Daniyal\Anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 3023, in run_spyder
    main.setup()
  File "C:\Users\Daniyal\Anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 840, in setup
    self.workingdirectory = WorkingDirectory(self, self.init_workdir, main=self)
  File "C:\Users\Daniyal\Anaconda3\lib\site-packages\spyder\plugins\workingdirectory.py", line 159, in __init__
    self.chdir(workdir)
  File "C:\Users\Daniyal\Anaconda3\lib\site-packages\spyder\plugins\workingdirectory.py", line 296, in chdir
    self.refresh_plugin()
  File "C:\Users\Daniyal\Anaconda3\lib\site-packages\spyder\plugins\workingdirectory.py", line 204, in refresh_plugin
    self.save_wdhistory()
  File "C:\Users\Daniyal\Anaconda3\lib\site-packages\spyder\plugins\workingdirectory.py", line 234, in save_wdhistory
    encoding.writelines(text, self.LOG_PATH)
  File "C:\Users\Daniyal\Anaconda3\lib\site-packages\spyder\utils\encoding.py", line 236, in writelines
    return write(os.linesep.join(lines), filename, encoding, mode)
  File "C:\Users\Daniyal\Anaconda3\lib\site-packages\spyder\utils\encoding.py", line 227, in write
    with open(filename, mode) as textfile:
FileNotFoundError: [Errno 2] No such file or directory: '%DANIYAL\\.spyder-py3\\workingdir'

**Comment by neowangkkk** [comment]
Same here. Installed in the terminal but still cannot launch spyder.

Traceback (most recent call last):
File "/anaconda3/lib/python3.6/site-packages/qtpy/QtWebEngineWidgets.py", line 22, in 
from PyQt5.QtWebEngineWidgets import QWebEnginePage
ImportError: dlopen(/anaconda3/lib/python3.6/site-packages/PyQt5/QtWebEngineWidgets.so, 2): Library not loaded: @rpath/libQt5WebEngineCore.5.dylib
Referenced from: /anaconda3/lib/python3.6/site-packages/PyQt5/QtWebEngineWidgets.so
Reason: image not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/anaconda3/bin/spyder", line 11, in 
sys.exit(main())
File "/anaconda3/lib/python3.6/site-packages/spyder/app/start.py", line 159, in main
from spyder.app import mainwindow
File "/anaconda3/lib/python3.6/site-packages/spyder/app/mainwindow.py", line 92, in 
from qtpy import QtWebEngineWidgets # analysis:ignore
File "/anaconda3/lib/python3.6/site-packages/qtpy/QtWebEngineWidgets.py", line 26, in 
from PyQt5.QtWebKitWidgets import QWebPage as QWebEnginePage
ModuleNotFoundError: No module named 'PyQt5.QtWebKitWidgets'

**Comment by makrand12** [comment]
I started from terminal and issued and error as segmentation fault(core dumped) please help me with it.

**Comment by Bhargav0528** [comment]
conda update -all worked for me

As I had installed Tensorflow it downgraded pyqt library
So try updating once :)

**Comment by polytech1** [comment]
@Bhargav0528 Worked me (except you forgot one "-") ;-)

**Comment by ADebut** [comment]
> Please run in a system terminal (i.e. `cmd.exe`)
> 
> ```
> conda install -f spyder
> ```
> and try to start Spyder again.

solved! Thanks so much!!! It has troubled me several days!

**Comment by tankxie** [comment]
run 
`conda update --all`

can solve this problem！

**Comment by jeroenschoonderbeek** [comment]
I installed package tornado and since then I can start Spyder. I tried update all and install f spyder but nothing works. This is error message I get.

Traceback (most recent call last):
File "/anaconda3/lib/python3.6/site-packages/spyder/app/mainwindow.py", line 3285, in main
mainwindow = run_spyder(app, options, args)
File "/anaconda3/lib/python3.6/site-packages/spyder/app/mainwindow.py", line 3140, in run_spyder
main.setup()
File "/anaconda3/lib/python3.6/site-packages/spyder/app/mainwindow.py", line 844, in setup
from spyder.plugins.editor import Editor
File "/anaconda3/lib/python3.6/site-packages/spyder/plugins/editor.py", line 41, in 
from spyder.utils.introspection.manager import IntrospectionManager
File "/anaconda3/lib/python3.6/site-packages/spyder/utils/introspection/manager.py", line 21, in 
from spyder.utils.introspection.plugin_client import PluginClient
File "/anaconda3/lib/python3.6/site-packages/spyder/utils/introspection/plugin_client.py", line 18, in 
import zmq
File "/anaconda3/lib/python3.6/site-packages/zmq/__init__.py", line 42, in 
_load_libzmq()
File "/anaconda3/lib/python3.6/site-packages/zmq/__init__.py", line 13, in _load_libzmq
PYPY = platform.python_implementation().lower() == 'pypy'
File "/anaconda3/lib/python3.6/platform.py", line 1265, in python_implementation
return _sys_version()[0]
File "/anaconda3/lib/python3.6/platform.py", line 1223, in _sys_version
repr(sys_version))
ValueError: failed to parse CPython sys.version: '3.6.6 |Anaconda, Inc.| (default, Jun 28 2018, 11:07:29) \n[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)]'

Can somebody help me?

**Comment by eranyil** [comment]
thanks. it worked

> run
> `conda update --all`
> 
> can solve this problem！
