### ISSUE TITLE
Anaconda crashing on launch

### ISSUE THREAD

**Issue by AMacInnes** [ContinuumIO/anaconda-issues#5298]
Trying to run anaconda on a mac OS.Sierra - crashes upon launch. Have removed and reinstalled on my machine. Seemed to be related to enum files so i successfully did pip install enum but...still crashing
Tried conda unstall ... and get the following traceback:
Traceback (most recent call last):
      File "//anaconda/lib/python2.7/site-packages/conda/exceptions.py", line 617, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "//anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 137, in _main
        exit_code = args.func(args, p)
      File "//anaconda/lib/python2.7/site-packages/conda/cli/main_remove.py", line 136, in execute
        prefix=prefix)
      File "//anaconda/lib/python2.7/site-packages/conda/core/index.py", line 125, in get_index
        supplement_index_with_prefix(index, prefix, known_channels)
      File "//anaconda/lib/python2.7/site-packages/conda/core/index.py", line 58, in supplement_index_with_prefix
        for dist, info in iteritems(linked_data(prefix)):
      File "//anaconda/lib/python2.7/site-packages/conda/core/linked_data.py", line 113, in linked_data
        load_linked_data(prefix, dist_name, ignore_channels=ignore_channels)
      File "//anaconda/lib/python2.7/site-packages/conda/core/linked_data.py", line 66, in load_linked_data
        linked_data_[prefix][dist] = rec = IndexRecord(**rec)
      File "//anaconda/lib/python2.7/site-packages/conda/_vendor/auxlib/entity.py", line 702, in __call__
        instance = super(EntityType, cls).__call__(*args, **kwargs)
      File "//anaconda/lib/python2.7/site-packages/conda/_vendor/auxlib/entity.py", line 719, in __init__
        setattr(self, key, kwargs[key])
      File "//anaconda/lib/python2.7/site-packages/conda/_vendor/auxlib/entity.py", line 831, in __setattr__
        super(ImmutableEntity, self).__setattr__(attribute, value)
      File "//anaconda/lib/python2.7/site-packages/conda/_vendor/auxlib/entity.py", line 424, in __set__
        instance.__dict__[self.name] = self.validate(instance, self.box(instance, val))
      File "//anaconda/lib/python2.7/site-packages/conda/_vendor/auxlib/entity.py", line 658, in box
        return val if isinstance(val, self._type) else self._type(**val)
      File "//anaconda/lib/python2.7/site-packages/conda/_vendor/auxlib/entity.py", line 702, in __call__
        instance = super(EntityType, cls).__call__(*args, **kwargs)
      File "//anaconda/lib/python2.7/site-packages/conda/_vendor/auxlib/entity.py", line 719, in __init__
        setattr(self, key, kwargs[key])
      File "//anaconda/lib/python2.7/site-packages/conda/_vendor/auxlib/entity.py", line 424, in __set__
        instance.__dict__[self.name] = self.validate(instance, self.box(instance, val))
      File "//anaconda/lib/python2.7/site-packages/conda/models/index_record.py", line 15, in box
        return super(LinkTypeField, self).box(instance, val)
      File "//anaconda/lib/python2.7/site-packages/conda/_vendor/auxlib/entity.py", line 551, in box
        return val if isinstance(val, self._type) else self._type(val)
      File "//anaconda/lib/python2.7/site-packages/enum.py", line 199, in __init__
        raise EnumBadKeyError(key)
    EnumBadKeyError: Enumeration keys must be strings: 1

**Comment by goanpeca** [comment]
@AMacInnes there is something weird on your installation path. There are double slashes everywhere.

Did you install for current user only? All user installs on Mac should be disabled, but on sierra sometimes the option was enabled due to a bug in OSX. Could you reinstall for the current user only and check the path does not include `//`

**Comment by AMacInnes** [comment]
there is a problem with install location - don't quite understand 
<img width="597" alt="screen shot 2017-09-10 at 9 49 17 am" src="https://user-images.githubusercontent.com/5417891/30249599-670132ce-960d-11e7-8a7d-f3c5746bc6a2.png">

**Comment by AMacInnes** [comment]
the install completes however a pop indicates that anaconda already installed..."use conda update anaconda" to update

**Comment by goanpeca** [comment]
You will have to manually remove your folder from a previous anaconda install, look at:

`/Users/<YOUR USER>/anaconda3` or `/Users/<YOUR USER>/anaconda`

**Comment by AMacInnes** [comment]
ok got it and it works now. thanks for your help.
