### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by hzidoum** [ContinuumIO/anaconda-issues#5321]
## Main error
Application <b>spyder</b> launch may have produced errors.
## Traceback
```
Traceback (most recent call last):
  File "//anaconda/lib/python3.5/site-packages/qtpy/__init__.py", line 119, in <module>
    from PySide import __version__ as PYSIDE_VERSION  # analysis:ignore
ImportError: No module named 'PySide'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "//anaconda/bin/spyder", line 6, in <module>
    sys.exit(spyder.app.start.main())
  File "//anaconda/lib/python3.5/site-packages/spyder/app/start.py", line 103, in main
    from spyder.app import mainwindow
  File "//anaconda/lib/python3.5/site-packages/spyder/app/mainwindow.py", line 49, in <module>
    requirements.check_qt()
  File "//anaconda/lib/python3.5/site-packages/spyder/requirements.py", line 39, in check_qt
    import qtpy
  File "//anaconda/lib/python3.5/site-packages/qtpy/__init__.py", line 125, in <module>
    raise PythonQtError('No Qt bindings could be found')
qtpy.PythonQtError: No Qt bindings could be found

```
## System information
```
platform: osx-64
version: 1.6.2
conda: 4.2.13
qt: 5.6.2
language: en
python: 2.7.13
os: Darwin;13.4.0;Darwin Kernel Version 13.4.0: Sun Aug 17 19:50:11 PDT 2014; root:xnu-2422.115.4~1/RELEASE_X86_64;x86_64;i386
pyqt: 5.6.0
```

**Comment by ccordoba12** [comment]
Please install Anaconda in your home directory and try again.

**Comment by goanpeca** [comment]
@AMacInnes there is something weird on your installation path. There are double slashes everywhere.

Did you install for current user only? All user installs on Mac should be disabled, but on sierra sometimes the option was enabled due to a bug in OSX. Could you reinstall for the current user only and check the path does not include `//`

You will have to manually remove your folder from a previous anaconda install, look at:

`/Users/<YOUR USER>/anaconda3 or /Users/<YOUR USER>/anaconda`
