### ISSUE TITLE
scipy.linalg.lu_factor hangs with matrices 25x25 or bigger

### ISSUE THREAD

**Issue by twmacro** [ContinuumIO/anaconda-issues#533]
I'm seeing odd behavior on our Linux machine, but not on Windows. I installed Anaconda3-2.4.0-Linux-x86_64.sh. This works:

    import numpy as np
    import scipy.linalg as la
    a = np.random.randn(24, 24)
    lu = la.lu_factor(a)

But this hangs on the lu_factor:

    a = np.random.randn(25, 25)
    lu = la.lu_factor(a)  # <-- hangs on 'getrf' call in decomp_lu.py

I noticed the exact same behavior with scipy.linalg.expm ... in that case, the hang occurs on the call to 'gesv' in basic.py.

We also purchased the MKL optimizations and that version does the same thing (very bummed!).

**Comment by twmacro** [comment]
I just want to note that I'm not having these issues on a different Linux machine. Not sure what to try next, though the 25 number seems suspicious.

**Comment by twmacro** [comment]
A little more info. According to gdb, the top 3 elements of the backtrace for both cases I mentioned above (the `getrf` call and the `gesv` call) are:

    #0  0x00007ffff6d7b287 in sched_yield () from /lib64/libc.so.6                                      
    #1  0x00007fffefa7a365 in exec_blas_async_wait ()                                                   
       from ~/anaconda3/lib/python3.5/site-packages/numpy/core/../../../../libopenblas.so.0                                                                                    
    #2  0x00007fffefba2b21 in dgetrf_parallel ()                                                        
       from ~/anaconda3/lib/python3.5/site-packages/numpy/core/../../../../libopenblas.so.0

**Comment by twmacro** [comment]
And a little more info. On the machine that seems to go in an infinite loop, the processor is (from /proc/cpuinfo):

    Intel(R) Xeon(R) CPU E7- 8870  @ 2.40GHz

On the machine with no trouble, the cpu is:

    Intel(R) Core(TM) i7-3612QM CPU @ 2.10GHz

**Comment by twmacro** [comment]
Correction to my first post: using the MKL optimizations does work. Something must have went wrong when we tried it previously.
