### ISSUE TITLE
Conda start up issue

### ISSUE THREAD

**Issue by aschae11** [ContinuumIO/anaconda-issues#5367]
After installing a fresh version of Anaconda 4.4.0 on Scientific Linux 7 I run into an issue with the startup. Typing  "conda list" dumps the following traceback. I am not sure what is going on here and looking through the other posts' issues I didn't find anything related.  If I try and start/update the navigator I get the same traceback as #1837 but the trace back listed below seems to be the root of the issue.

I am not sure where to go from here.     

Traceback (most recent call last):
  File "/home/schaefer/anaconda2/bin/conda", line 6, in <module>
    sys.exit(conda.cli.main())
  File "/home/schaefer/anaconda2/lib/python2.7/site-packages/conda/cli/main.py", line 179, in main
    return conda_exception_handler(_main, *args)
  File "/home/schaefer/anaconda2/lib/python2.7/site-packages/conda/exceptions.py", line 636, in conda_exception_handler
    return handle_exception(e)
  File "/home/schaefer/anaconda2/lib/python2.7/site-packages/conda/exceptions.py", line 626, in handle_exception
    print_unexpected_error_message(e)
  File "/home/schaefer/anaconda2/lib/python2.7/site-packages/conda/exceptions.py", line 571, in print_unexpected_error_message
    from .base.context import context
  File "/home/schaefer/anaconda2/lib/python2.7/site-packages/conda/base/context.py", line 759, in <module>
    context = Context(SEARCH_PATH, APP_NAME, None)
  File "/home/schaefer/anaconda2/lib/python2.7/site-packages/conda/common/configuration.py", line 727, in __init__
    self._set_search_path(search_path)
  File "/home/schaefer/anaconda2/lib/python2.7/site-packages/conda/common/configuration.py", line 745, in _set_search_path
    self._set_raw_data(load_file_configs(search_path))
  File "/home/schaefer/anaconda2/lib/python2.7/site-packages/conda/common/configuration.py", line 369, in load_file_configs
    raw_data = odict(kv for kv in chain.from_iterable(load_paths))
  File "/home/schaefer/anaconda2/lib/python2.7/collections.py", line 69, in __init__
    self.__update(*args, **kwds)
  File "/home/schaefer/anaconda2/lib/python2.7/_abcoll.py", line 571, in update
    for key, value in other:
  File "/home/schaefer/anaconda2/lib/python2.7/site-packages/conda/common/configuration.py", line 369, in <genexpr>
    raw_data = odict(kv for kv in chain.from_iterable(load_paths))
  File "/home/schaefer/anaconda2/lib/python2.7/site-packages/conda/common/configuration.py", line 344, in _file_yaml_loader
    yield fullpath, YamlRawParameter.make_raw_parameters_from_file(fullpath)
  File "/home/schaefer/anaconda2/lib/python2.7/site-packages/conda/common/configuration.py", line 336, in make_raw_parameters_from_file
    return cls.make_raw_parameters(filepath, ruamel_yaml) or EMPTY_MAP
  File "/home/schaefer/anaconda2/lib/python2.7/site-packages/conda/common/configuration.py", line 325, in make_raw_parameters
    for key in from_map)
  File "/home/schaefer/anaconda2/lib/python2.7/site-packages/conda/common/configuration.py", line 325, in <genexpr>
    for key in from_map)
TypeError: string indices must be integers, not str

**Comment by goanpeca** [comment]
@aschae11 if you install the latest conda?

```
$ conda update conda

```

**Comment by aschae11** [comment]
It gives that same traceback.

**Comment by goanpeca** [comment]
Seems your conda configuration has an invalid value, could you look for a `.condarc` located inside `/home/schaefer/` and delete it ?

**Comment by aschae11** [comment]
I'd suppose it would be good to know you cant use that file name for storing a source environment.

It works after deleting that. Thanks.
