### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by xllakshman** [ContinuumIO/anaconda-issues#5368]
## Main error
Application <b>notebook</b> launch may have produced errors.
## Traceback
```
Traceback (most recent call last):
  File "C:\Users\USER\Anaconda3\Scripts\jupyter-notebook-script.py", line 5, in <module>
    sys.exit(notebook.notebookapp.main())
  File "C:\Users\USER\Anaconda3\lib\site-packages\jupyter_core\application.py", line 267, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "C:\Users\USER\Anaconda3\lib\site-packages\traitlets\config\application.py", line 657, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-7>", line 2, in initialize
  File "C:\Users\USER\Anaconda3\lib\site-packages\traitlets\config\application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "C:\Users\USER\Anaconda3\lib\site-packages\notebook\notebookapp.py", line 1296, in initialize
    self.init_webapp()
  File "C:\Users\USER\Anaconda3\lib\site-packages\notebook\notebookapp.py", line 1115, in init_webapp
    xheaders=self.trust_xheaders)
  File "C:\Users\USER\Anaconda3\lib\site-packages\tornado\util.py", line 293, in __new__
    instance.initialize(*args, **init_kwargs)
  File "C:\Users\USER\Anaconda3\lib\site-packages\tornado\httpserver.py", line 167, in initialize
    read_chunk_size=chunk_size)
  File "C:\Users\USER\Anaconda3\lib\site-packages\tornado\tcpserver.py", line 128, in __init__
    self.ssl_options['certfile'])
ValueError: certfile "/home/ubuntu/ssl/cert.pem" does not exist

```
## System information
```
python: 3.6.

**Comment by goanpeca** [comment]
@xllakshman looks like your path to certificates is wrongly configured, you are on windows, yet trying to access `/home/ubuntu/ssl/cert.pem`
