### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by stat0619** [ContinuumIO/anaconda-issues#5417]
## Main error
Application <b>notebook</b> launch may have produced errors.
## Traceback
```
Traceback (most recent call last):
  File "C:\Users\sdl06\Anaconda2\Scripts\jupyter-notebook-script.py", line 3, in <module>
    import notebook.notebookapp
  File "C:\Users\sdl06\Anaconda2\lib\site-packages\notebook\notebookapp.py", line 55, in <module>
    from tornado import httpserver
  File "C:\Users\sdl06\Anaconda2\lib\site-packages\tornado\httpserver.py", line 34, in <module>
    from tornado.http1connection import HTTP1ServerConnection, HTTP1ConnectionParameters
  File "C:\Users\sdl06\Anaconda2\lib\site-packages\tornado\http1connection.py", line 30, in <module>
    from tornado import iostream
  File "C:\Users\sdl06\Anaconda2\lib\site-packages\tornado\iostream.py", line 40, in <module>
    from tornado.netutil import ssl_wrap_socket, ssl_match_hostname, SSLCertificateError, _client_ssl_defaults, _server_ssl_defaults
  File "C:\Users\sdl06\Anaconda2\lib\site-packages\tornado\netutil.py", line 39, in <module>
    import certifi
ImportError: No module named certifi

```
## System information
```
platform: win-64
version: 1.6.2
conda: 4.3.25
qt: 5.6.2
language: en_US
python: 2.7.8
os: Windows;8;6.2.9200;AMD64;Intel64 Family 6 Model 60 Stepping 3, GenuineIntel
pyqt: 5.6.0
```

**Comment by goanpeca** [comment]
Try on the terminal

```
$ conda install certifi
```

And try again
