### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by ladyloris** [ContinuumIO/anaconda-issues#5420]
I downloaded Anaconda on Sunday, and I have not been able to open it once. It takes a while to open, says it's initializing, then crashes and opens a "Navigator Error" web page. I am running macOS Sierra.

The main error is as follows:

string indices must be integers, not str

Traceback (most recent call last):
  File "/Users/siennahaines/anaconda/lib/python2.7/site-packages/anaconda_navigator/exceptions.py", line 75, in exception_handler
    return_value = func(*args, **kwargs)
  File "/Users/siennahaines/anaconda/lib/python2.7/site-packages/anaconda_navigator/app/start.py", line 120, in start_app
    window = run_app(splash)
  File "/Users/siennahaines/anaconda/lib/python2.7/site-packages/anaconda_navigator/app/start.py", line 63, in run_app
    window = MainWindow(splash=splash)
  File "/Users/siennahaines/anaconda/lib/python2.7/site-packages/anaconda_navigator/widgets/main_window.py", line 160, in __init__
    self.api = AnacondaAPI()
  File "/Users/siennahaines/anaconda/lib/python2.7/site-packages/anaconda_navigator/api/anaconda_api.py", line 1214, in AnacondaAPI
    ANACONDA_API = _AnacondaAPI()
  File "/Users/siennahaines/anaconda/lib/python2.7/site-packages/anaconda_navigator/api/anaconda_api.py", line 65, in __init__
    self._conda_api = CondaAPI()
  File "/Users/siennahaines/anaconda/lib/python2.7/site-packages/anaconda_navigator/api/conda_api.py", line 1654, in CondaAPI
    CONDA_API = _CondaAPI()
  File "/Users/siennahaines/anaconda/lib/python2.7/site-packages/anaconda_navigator/api/conda_api.py", line 345, in __init__
    self.set_conda_prefix()
  File "/Users/siennahaines/anaconda/lib/python2.7/site-packages/anaconda_navigator/api/conda_api.py", line 494, in set_conda_prefix
    self.ROOT_PREFIX = info['root_prefix']
TypeError: string indices must be integers, not str

**Comment by goanpeca** [comment]
@ladyloris if you open a terminal and type

```
$ source activate root
$ anaconda-navigator
```

**Comment by ladyloris** [comment]
Just tried this, got the same error:

**Main Error**

string indices must be integers, not str

**Traceback**

Traceback (most recent call last):
  File "/Users/siennahaines/anaconda/lib/python2.7/site-packages/anaconda_navigator/exceptions.py", line 75, in exception_handler
    return_value = func(*args, **kwargs)
  File "/Users/siennahaines/anaconda/lib/python2.7/site-packages/anaconda_navigator/app/start.py", line 120, in start_app
    window = run_app(splash)
  File "/Users/siennahaines/anaconda/lib/python2.7/site-packages/anaconda_navigator/app/start.py", line 63, in run_app
    window = MainWindow(splash=splash)
  File "/Users/siennahaines/anaconda/lib/python2.7/site-packages/anaconda_navigator/widgets/main_window.py", line 160, in __init__
    self.api = AnacondaAPI()
  File "/Users/siennahaines/anaconda/lib/python2.7/site-packages/anaconda_navigator/api/anaconda_api.py", line 1214, in AnacondaAPI
    ANACONDA_API = _AnacondaAPI()
  File "/Users/siennahaines/anaconda/lib/python2.7/site-packages/anaconda_navigator/api/anaconda_api.py", line 65, in __init__
    self._conda_api = CondaAPI()
  File "/Users/siennahaines/anaconda/lib/python2.7/site-packages/anaconda_navigator/api/conda_api.py", line 1654, in CondaAPI
    CONDA_API = _CondaAPI()
  File "/Users/siennahaines/anaconda/lib/python2.7/site-packages/anaconda_navigator/api/conda_api.py", line 345, in __init__
    self.set_conda_prefix()
  File "/Users/siennahaines/anaconda/lib/python2.7/site-packages/anaconda_navigator/api/conda_api.py", line 494, in set_conda_prefix
    self.ROOT_PREFIX = info['root_prefix']
TypeError: string indices must be integers, not str
