### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by alessandronastasi** [ContinuumIO/anaconda-issues#5485]
## Main error
Application <b>glueviz</b> launch may have produced errors.
## Traceback
```
Traceback (most recent call last):
  File "/Users/alessandro/anaconda2/bin/glue", line 6, in <module>
    sys.exit(glue.main.main())
  File "/Users/alessandro/anaconda2/lib/python2.7/site-packages/glue/main.py", line 232, in main
    start_glue(**kwargs)
  File "/Users/alessandro/anaconda2/lib/python2.7/site-packages/glue/main.py", line 140, in start_glue
    from glue.app.qt import GlueApplication
  File "/Users/alessandro/anaconda2/lib/python2.7/site-packages/glue/app/qt/__init__.py", line 3, in <module>
    from .application import GlueApplication
  File "/Users/alessandro/anaconda2/lib/python2.7/site-packages/glue/app/qt/application.py", line 10, in <module>
    from qtpy import QtCore, QtWidgets, QtGui, compat
  File "/Users/alessandro/anaconda2/lib/python2.7/site-packages/qtpy/QtCore.py", line 34, in <module>
    from PyQt4.QtGui import (QItemSelection, QItemSelectionModel,
ImportError: dlopen(/Users/alessandro/anaconda2/lib/python2.7/site-packages/PyQt4/QtGui.so, 2): Library not loaded: @rpath/libpng16.16.dylib
  Referenced from: /Users/alessandro/anaconda2/lib/libQtGui.4.8.7.dylib
  Reason: Incompatible library version: libQtGui.4.dylib requires version 39.0.0 or later, but libpng16.16.dylib provides version 34.0.0

```
## System information
```
version: 1.6.2
conda: 4.3.23
qt: 5.6.2
python: 3.5.3
pyqt: 4.11.4
language: en
platform: osx-64
os: Darwin;15.6.0;Darwin Kernel Version 15.6.0: Sun Jun  4 21:43:07 PDT 2017; root:xnu-3248.70.3~1/RELEASE_X86_64;x86_64;i386
```

**Comment by goanpeca** [comment]
Anaconda no longer supports qt4 and qt4 is officially deprecated, please update to a newer version to use qt5

```
$ conda update qt glueviz
```

---

Please remember to update to the latest version of Navigator to include
the latest fixes.

Open a terminal (on Linux or Mac) or the Anaconda Command Prompt (on windows)
and type:

```
$ conda update anaconda-navigator
$ conda update navigator-updater
```
