### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by maab57** [ContinuumIO/anaconda-issues#5563]
## Main error
Application <b>spyder</b> launch may have produced errors.
## Traceback
```
Traceback (most recent call last):
  File "/home/marcelo/anaconda3/lib/python3.6/site-packages/qtpy/QtWebEngineWidgets.py", line 22, in <module>
    from PyQt5.QtWebEngineWidgets import QWebEnginePage
ModuleNotFoundError: No module named 'PyQt5.QtWebEngineWidgets'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/marcelo/anaconda3/bin/spyder", line 6, in <module>
    sys.exit(spyder.app.start.main())
  File "/home/marcelo/anaconda3/lib/python3.6/site-packages/spyder/app/start.py", line 103, in main
    from spyder.app import mainwindow
  File "/home/marcelo/anaconda3/lib/python3.6/site-packages/spyder/app/mainwindow.py", line 92, in <module>
    from qtpy import QtWebEngineWidgets  # analysis:ignore
  File "/home/marcelo/anaconda3/lib/python3.6/site-packages/qtpy/QtWebEngineWidgets.py", line 26, in <module>
    from PyQt5.QtWebKitWidgets import QWebPage as QWebEnginePage
ImportError: libselinux.so.1: cannot open shared object file: No such file or directory

```
## System information
```
python: 3.6.1
language: es_ES
os: Linux;4.9.48-1-MANJARO;#1 SMP PREEMPT Thu Sep 7 10:44:53 UTC 2017;x86_64;
version: 1.6.2
platform: linux-64
qt: 5.6.2
pyqt: 5.6.0
conda: 4.3.21
```

**Comment by goanpeca** [comment]
You need to install libselinux using the package manager of your Linux distro to fix this error. There's nothing we can do about it in our side.

**Comment by maab57** [comment]
I installed libselinux and the problem was solved. Thank you very much.

2017-09-15 19:31 GMT-03:00 Gonzalo Peña-Castellanos <
notifications@github.com>:
