### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by ahmedabdelmoniem** [ContinuumIO/anaconda-issues#5565]
I get this error when i try to launch spyder
## Main error
Application <b>spyder</b> launch may have produced errors.
## Traceback
```
Traceback (most recent call last):
  File "C:\Users\Nonsense\Anaconda3\Scripts\spyder-script.py", line 3, in <module>
    import spyder.app.start
  File "C:\Users\Nonsense\Anaconda3\lib\site-packages\spyder\app\start.py", line 13, in <module>
    from spyder.config.base import get_conf_path, running_in_mac_app
  File "C:\Users\Nonsense\Anaconda3\lib\site-packages\spyder\config\base.py", line 365, in <module>
    _ = get_translation("spyder")
  File "C:\Users\Nonsense\Anaconda3\lib\site-packages\spyder\config\base.py", line 345, in get_translation
    _trans = gettext.translation(modname, locale_path, codeset="utf-8")
  File "C:\Users\Nonsense\Anaconda3\lib\gettext.py", line 505, in translation
    mofiles = find(domain, localedir, languages, all=True)
  File "C:\Users\Nonsense\Anaconda3\lib\gettext.py", line 489, in find
    if os.path.exists(mofile):
  File "C:\Users\Nonsense\Anaconda3\lib\genericpath.py", line 19, in exists
    os.stat(path)
ValueError: stat: embedded null character in path

```
## System information
```
python: 3.6.1
language: en_US
os: Windows;7;6.1.7601;AMD64;Intel64 Family 6 Model 30 Stepping 5, GenuineIntel
version: 1.6.2
platform: win-32
qt: 5.6.2
pyqt: 5.6.0
conda: 4.3.21
```

**Comment by ahmedabdelmoniem** [comment]
on another note versions 2.3.8 and 2.3.9 seems to works the other newer versions don't, with the the error message always showing up.

**Comment by goanpeca** [comment]
Try deleting the folder 

`C:\Users\Nonsense\.spyder-py2` or `C:\Users\Nonsense\.spyder-py3`
