### ISSUE TITLE
anaconda 2.4 matplotlib missing pyside

### ISSUE THREAD

**Issue by eyaler** [ContinuumIO/anaconda-issues#558]
import matplotlib.pyplot as plt

i get:

Traceback (most recent call last):
  File "C:\Anaconda35\lib\site-packages\matplotlib\backends\qt_compat.py", line 159, in <module>
    from PySide import QtCore, QtGui, __version__, __version_info__
ImportError: No module named 'PySide'

i am on win8.1 with vs2015 installed.

**Comment by ccordoba12** [comment]
We stopped to support PySide several releases ago.

**Comment by eyaler** [comment]
ok. so how can i use matplotlib.pyplot?

**Comment by ccordoba12** [comment]
Installing PyQt. Perhaps it was installed incorrectly in your case. Then please run

    conda install -f pyqt

and try again.

**Comment by eyaler** [comment]
no love.
i reinstalled pyqt but same error. in fact i tried installing anaconda 2.4 several times on several different machines and get the same error. here is the full output:

>>> import matplotlib.pyplot as plt
Traceback (most recent call last):
  File "C:\Anaconda35\lib\site-packages\matplotlib\backends\qt_compat.py", line
159, in <module>
    from PySide import QtCore, QtGui, __version__, __version_info__
ImportError: No module named 'PySide'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Anaconda35\lib\site-packages\matplotlib\pyplot.py", line 114, in <mod
ule>
    _backend_mod, new_figure_manager, draw_if_interactive, _show = pylab_setup()

  File "C:\Anaconda35\lib\site-packages\matplotlib\backends\__init__.py", line 3
2, in pylab_setup
    globals(),locals(),[backend_name],0)
  File "C:\Anaconda35\lib\site-packages\matplotlib\backends\backend_qt4agg.py",
line 18, in <module>
    from .backend_qt5agg import FigureCanvasQTAggBase as _FigureCanvasQTAggBase
  File "C:\Anaconda35\lib\site-packages\matplotlib\backends\backend_qt5agg.py",
line 15, in <module>
    from .backend_qt5 import QtCore
  File "C:\Anaconda35\lib\site-packages\matplotlib\backends\backend_qt5.py", lin
e 31, in <module>
    from .qt_compat import QtCore, QtGui, QtWidgets, _getSaveFileName, __version
__
  File "C:\Anaconda35\lib\site-packages\matplotlib\backends\qt_compat.py", line
162, in <module>
    "Matplotlib qt-based backends require an external PyQt4, PyQt5,\n"
ImportError: Matplotlib qt-based backends require an external PyQt4, PyQt5,
or PySide package to be installed, but it was not found.
>>>

thanks,
e.

**Comment by msarahan** [comment]
You probably have a config setting left over from something earlier:

http://matplotlib.org/faq/usage_faq.html#how-do-i-select-pyqt4-or-pyside

**Comment by eyaler** [comment]
@msarahan - exactly. thanks!

**Comment by jinselove** [comment]
Hi I got the same issue. May I ask how did you fix it?

**Comment by aj8907** [comment]
Install pyside for version 2.7 worked for me:

`conda install -c anaconda pyside=1.2.1`
