### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by rkrockstar** [ContinuumIO/anaconda-issues#5603]
## Main error
Application <b>notebook</b> launch may have produced errors.
## Traceback
```
Traceback (most recent call last):
  File "C:\Users\Rounak Kulkarni\Anaconda3\Scripts\jupyter-notebook-script.py", line 3, in <module>
    import notebook.notebookapp
  File "C:\Users\Rounak Kulkarni\Anaconda3\lib\site-packages\notebook\__init__.py", line 25, in <module>
    from .nbextensions import install_nbextension
  File "C:\Users\Rounak Kulkarni\Anaconda3\lib\site-packages\notebook\nbextensions.py", line 32, in <module>
    from traitlets.config.manager import BaseJSONConfigManager
  File "C:\Users\Rounak Kulkarni\Anaconda3\lib\site-packages\traitlets\config\__init__.py", line 6, in <module>
    from .application import *
  File "C:\Users\Rounak Kulkarni\Anaconda3\lib\site-packages\traitlets\config\application.py", line 17, in <module>
    from decorator import decorator
  File "C:\Tools\helium-python-1.9.6\heliumlib\decorator.py", line 156
    exec code in evaldict
            ^
SyntaxError: Missing parentheses in call to 'exec'

```
## System information
```
python: 3.6.1
language: en_US
os: Windows;10;10.0.15063;AMD64;Intel64 Family 6 Model 78 Stepping 3, GenuineIntel
version: 1.6.2
platform: win-64
qt: 5.6.2
pyqt: 5.6.0
conda: 4.3.21
```

**Comment by goanpeca** [comment]
Hi @rkrockstar, two things, installing anaconda in a path with spaces will make some libraries work incorrectly. It seems something on your path is loading some libraries in the `Tools` folder. That needs to be fixed.
