### ISSUE TITLE
Error with opening Anaconda

### ISSUE THREAD

**Issue by joeclavette** [ContinuumIO/anaconda-issues#566]
Error: spawn ENOENT
    at exports._errnoException (util.js:742:11)
    at Process.ChildProcess._handle.onexit (child_process.js:1027:32)
    at child_process.js:1110:20
    at process._tickCallback (node.js:279:11)

**Comment by ilanschnell** [comment]
What is the exact command you are running?  Which OS?  Version of Anaconda?  What is the output from `conda info`?  Thanks
