### ISSUE TITLE
Issue with Anaconda Launcher

### ISSUE THREAD

**Issue by mimidu** [ContinuumIO/anaconda-issues#5661]
Hi I tried to install Launcher but got into error:

---

## Uncaught Exception

```
Error: spawn conda ENOENT
    at exports._errnoException (util.js:734:11)
    at Process.ChildProcess._handle.onexit (child_process.js:1022:32)
    at child_process.js:1115:20
    at process._tickCallback (node.js:375:11)
```

## Platform Information

* Operating System: darwin
* Conda Version: 4.3.25
* Conda Platform: osx-64

```json
{
  "GID": 20,
  "UID": 502,
  "channels": [
    "https://repo.continuum.io/pkgs/free/osx-64",
    "https://repo.continuum.io/pkgs/free/noarch",
    "https://repo.continuum.io/pkgs/r/osx-64",
    "https://repo.continuum.io/pkgs/r/noarch",
    "https://repo.continuum.io/pkgs/pro/osx-64",
    "https://repo.continuum.io/pkgs/pro/noarch"
  ],
  "conda_build_version": "1.14.1",
  "conda_env_version": "4.3.25",
  "conda_location": "/Users/yanlihou/anaconda/lib/python2.7/site-packages/conda",
  "conda_prefix": "/Users/yanlihou/anaconda",
  "conda_private": false,
  "conda_version": "4.3.25",
  "default_prefix": "/Users/yanlihou/anaconda",
  "env_vars": {
    "CIO_TEST": "<not set>",
    "CONDA_DEFAULT_ENV": "<not set>",
    "CONDA_ENVS_PATH": "<not set>",
    "DYLD_LIBRARY_PATH": "<not set>",
    "PATH": "/Users/yanlihou/anaconda/bin:/Users/yanlihou/anaconda/bin:/Library/Frameworks/Python.framework/Versions/Current/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin",
    "PYTHONHOME": "<not set>",
    "PYTHONPATH": "<not set>"
  },
  "envs": [],
  "envs_dirs": [
    "/Users/yanlihou/anaconda/envs",
    "/Users/yanlihou/.conda/envs"
  ],
  "netrc_file": null,
  "offline": false,
  "pkgs_dirs": [
    "/Users/yanlihou/anaconda/pkgs",
    "/Users/yanlihou/.conda/pkgs"
  ],
  "platform": "osx-64",
  "python_version": "2.7.13.final.0",
  "rc_path": null,
  "requests_version": "2.14.2",
  "root_prefix": "/Users/yanlihou/anaconda",
  "root_writable": true,
  "site_dirs": [],
  "sys.executable": "/Users/yanlihou/anaconda/bin/python",
  "sys.prefix": "/Users/yanlihou/anaconda",
  "sys.version": "2.7.13 |Anaconda 2.3.0 (x86_64)| (default, Dec 20 2016, 23:05:08) \n[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)]",
  "sys_rc_path": "/Users/yanlihou/anaconda/.condarc",
  "user_agent": "conda/4.3.25 requests/2.14.2 CPython/2.7.13 Darwin/12.6.0 OSX/10.8.5",
  "user_rc_path": "/Users/yanlihou/.condarc",
  "condaBuildVersion": "1.14.1",
  "condaEnvVersion": "4.3.25",
  "condaLocation": "/Users/yanlihou/anaconda/lib/python2.7/site-packages/conda",
  "condaPrefix": "/Users/yanlihou/anaconda",
  "condaPrivate": false,
  "condaVersion": "4.3.25",
  "defaultPrefix": "/Users/yanlihou/anaconda",
  "envVars": {
    "CIO_TEST": "<not set>",
    "CONDA_DEFAULT_ENV": "<not set>",
    "CONDA_ENVS_PATH": "<not set>",
    "DYLD_LIBRARY_PATH": "<not set>",
    "PATH": "/Users/yanlihou/anaconda/bin:/Users/yanlihou/anaconda/bin:/Library/Frameworks/Python.framework/Versions/Current/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin",
    "PYTHONHOME": "<not set>",
    "PYTHONPATH": "<not set>"
  },
  "envsDirs": [
    "/Users/yanlihou/anaconda/envs",
    "/Users/yanlihou/.conda/envs"
  ],
  "netrcFile": null,
  "pkgsDirs": [
    "/Users/yanlihou/anaconda/pkgs",
    "/Users/yanlihou/.conda/pkgs"
  ],
  "pythonVersion": "2.7.13.final.0",
  "rcPath": null,
  "requestsVersion": "2.14.2",
  "rootPrefix": "/Users/yanlihou/anaconda",
  "rootWritable": true,
  "siteDirs": [],
  "sysRcPath": "/Users/yanlihou/anaconda/.condarc",
  "userAgent": "conda/4.3.25 requests/2.14.2 CPython/2.7.13 Darwin/12.6.0 OSX/10.8.5",
  "userRcPath": "/Users/yanlihou/.condarc"
}
```

**Comment by goanpeca** [comment]
@mimidu Launcher is deprecated. Navigator replaced the now very old (+2 years!) launcher.

See more information at https://docs.anaconda.com/anaconda/navigator

Open a terminal (on Linux or Mac) or the Anaconda Command Prompt (on windows)
and type:

```
$ conda update anaconda-navigator
$ conda install navigator-updater
```
