### ISSUE TITLE
ImportError: C extension pandas

### ISSUE THREAD

**Issue by tycobb** [ContinuumIO/anaconda-issues#571]
I get the below error whenever I try and run a python script via .py file. I uninstall and install python via     
    conda uninstall pandas
    conda install pandas 

I also did a fresh install of my OS (Ubuntu 15.10) and that didn't fix this issue.

ImportError: C extension: 'bytes_to_str' not built. If you want to import pandas from the source directory, you may need to run 'python setup.py build_ext --inplace' to build the C extensions first.

The error is only occurring when I try to import pandas and run via $python test2.py. 
$ptyhon test1.py does not give me an issue.

test1.py 
    import numpy

test2.py
    import numpy
    import pandas

If i open up the python shell and import pandas I get no issue.

$ python
>>> import pandas
>>>

**Comment by tycobb** [comment]
$ python ~/googledrive/scripts/test.py
Traceback (most recent call last):
  File "/home/michael/anaconda3/lib/python3.5/site-packages/pandas/compat/__init__.py", line 46, in <module>
    import __builtin__ as builtins
ImportError: No module named '__builtin__'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/michael/anaconda3/lib/python3.5/site-packages/pandas/__init__.py", line 7, in <module>
    from pandas import hashtable, tslib, lib
  File "pandas/tslib.pyx", line 53, in init pandas.tslib (pandas/tslib.c:102872)
  File "/home/michael/anaconda3/lib/python3.5/site-packages/pandas/compat/__init__.py", line 59, in <module>
    import http.client as httplib
  File "/home/michael/anaconda3/lib/python3.5/http/client.py", line 71, in <module>
    import email.parser
  File "/home/michael/googledrive/scripts/email.py", line 8, in <module>
    import pandas.io.data as web
  File "/home/michael/anaconda3/lib/python3.5/site-packages/pandas/io/data.py", line 15, in <module>
    from pandas.compat import(
ImportError: cannot import name 'bytes_to_str'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/michael/googledrive/scripts/test.py", line 11, in <module>
    main()
  File "/home/michael/googledrive/scripts/test.py", line 2, in main
    import pandas as pd
  File "/home/michael/anaconda3/lib/python3.5/site-packages/pandas/__init__.py", line 13, in <module>
    "extensions first.".format(module))
ImportError: C extension: 'bytes_to_str' not built. If you want to import pandas from the source directory, you may need to run 'python setup.py build_ext --inplace' to build the C extensions first.

Any ideas? Above is the full error I get.

**Comment by tycobb** [comment]
Note that my issue doesn't exist when I run it with ipython.

$ ipython ~/googledrive/scripts/test.py
