### ISSUE TITLE
Latest matplotlib is broken on Python 3.5

### ISSUE THREAD

**Issue by Juanlu001** [ContinuumIO/anaconda-issues#573]
I am getting `ImportError: cannot import name 'six'` when using Python 3.5. I tried the same with a Python 3.4 envirnonment and it works without problems.

```
$ python -V
Python 3.5.0 :: Continuum Analytics, Inc.
$ python -c "import matplotlib"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/juanlu/.miniconda3/envs/mpl35/lib/python3.5/site-packages/matplotlib/__init__.py", line 105, in <module>
    from matplotlib.externals import six
ImportError: cannot import name 'six'
$ conda info -a
Current conda install:

             platform : linux-64
        conda version : 3.18.8
  conda-build version : 1.18.2
       python version : 3.4.3.final.0
     requests version : 2.8.1
     root environment : /home/juanlu/.miniconda3  (writable)
  default environment : /home/juanlu/.miniconda3/envs/mpl35
     envs directories : /home/juanlu/.miniconda3/envs
        package cache : /home/juanlu/.miniconda3/pkgs
         channel URLs : https://conda.anaconda.org/t/<TOKEN>/juanlu001/linux-64/
                        https://conda.anaconda.org/t/<TOKEN>/juanlu001/noarch/
                        https://conda.anaconda.org/t/<TOKEN>/poliastro/linux-64/
                        https://conda.anaconda.org/t/<TOKEN>/poliastro/noarch/
                        https://repo.continuum.io/pkgs/free/linux-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/linux-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : /home/juanlu/.condarc
    is foreign system : False

# conda environments:
#
_test                    /home/juanlu/.miniconda3/envs/_test
anaconda                 /home/juanlu/.miniconda3/envs/anaconda
fenics_test              /home/juanlu/.miniconda3/envs/fenics_test
gtoc8                    /home/juanlu/.miniconda3/envs/gtoc8
miniconda                /home/juanlu/.miniconda3/envs/miniconda
mpl35                 *  /home/juanlu/.miniconda3/envs/mpl35
poliastro27              /home/juanlu/.miniconda3/envs/poliastro27
poliastro34              /home/juanlu/.miniconda3/envs/poliastro34
poliastro35              /home/juanlu/.miniconda3/envs/poliastro35
py27                     /home/juanlu/.miniconda3/envs/py27
py34                     /home/juanlu/.miniconda3/envs/py34
py35                     /home/juanlu/.miniconda3/envs/py35
pykep27                  /home/juanlu/.miniconda3/envs/pykep27
pyomo34                  /home/juanlu/.miniconda3/envs/pyomo34
root                     /home/juanlu/.miniconda3

sys.version: 3.4.3 |Continuum Analytics, Inc.| (defau...
sys.prefix: /home/juanlu/.miniconda3
sys.executable: /home/juanlu/.miniconda3/bin/python3
conda location: /home/juanlu/.miniconda3/lib/python3.4/site-packages/conda
conda-build: /home/juanlu/.miniconda3/bin/conda-build
conda-convert: /home/juanlu/.miniconda3/bin/conda-convert
conda-develop: /home/juanlu/.miniconda3/bin/conda-develop
conda-env: /home/juanlu/.miniconda3/bin/conda-env
conda-index: /home/juanlu/.miniconda3/bin/conda-index
conda-inspect: /home/juanlu/.miniconda3/bin/conda-inspect
conda-metapackage: /home/juanlu/.miniconda3/bin/conda-metapackage
conda-pipbuild: /home/juanlu/.miniconda3/bin/conda-pipbuild
conda-server: /home/juanlu/.miniconda3/bin/conda-server
conda-sign: /home/juanlu/.miniconda3/bin/conda-sign
conda-skeleton: /home/juanlu/.miniconda3/bin/conda-skeleton
user site dirs: 

CIO_TEST: <not set>
CONDA_DEFAULT_ENV: mpl35
CONDA_ENVS_PATH: <not set>
LD_LIBRARY_PATH: /opt/opencascade/lib
PATH: /home/juanlu/.miniconda3/envs/mpl35/bin:/home/juanlu/.local/bin:/home/juanlu/.gem/ruby/2.1.0/bin:/home/juanlu/.local/bin:/home/juanlu/.gem/ruby/2.1.0/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/lib/jvm/default/bin:/opt/opencascade/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/opt/visit/bin
PYTHONHOME: <not set>
PYTHONPATH: <not set>

License directories:
    /home/juanlu/.continuum
    /home/juanlu/.miniconda3/licenses
License files (license*.txt):
    /home/juanlu/.continuum/license_academic_20150103071001.txt
               Reading license file : 1
                    Signature valid : 1
                       Vendor match : 1
                            product : 'Academic'
                           packages : 'numbapro mkl iopro'
                           end_date : '2016-01-03'
                               type : None
Package/feature end dates:
    numbapro        : 2016-01-03
    iopro           : 2016-01-03
    mkl             : 2016-01-03
$ conda list
# packages in environment at /home/juanlu/.miniconda3/envs/mpl35:
#
cycler                    0.9.0                    py35_0    defaults
fontconfig                2.11.1                        5    defaults
freetype                  2.5.5                         0    defaults
libgfortran               1.0                           0    defaults
libpng                    1.6.17                        0    defaults
libxml2                   2.9.2                         0    defaults
matplotlib                1.5.0               np110py35_0    defaults
numpy                     1.10.1                   py35_0    defaults
openblas                  0.2.14                        3    defaults
openssl                   1.0.2d                        0    defaults
pip                       7.1.2                    py35_0    defaults
pyparsing                 2.0.3                    py35_0    defaults
pyqt                      4.11.4                   py35_1    defaults
python                    3.5.0                         1    defaults
python-dateutil           2.4.2                    py35_0    defaults
pytz                      2015.7                   py35_0    defaults
qt                        4.8.7                         1    defaults
readline                  6.2                           2    <unknown>
setuptools                18.5                     py35_0    defaults
sip                       4.16.9                   py35_0    defaults
six                       1.10.0                   py35_0    defaults
sqlite                    3.8.4.1                       1    http://repo.continuum.io/pkgs/free/linux-64/sqlite-3.8.4.1-1.tar.bz2
tk                        8.5.18                        0    http://repo.continuum.io/pkgs/free/linux-64/tk-8.5.18-0.tar.bz2
wheel                     0.26.0                   py35_1    defaults
xz                        5.0.5                         0    <unknown>
zlib                      1.2.8                         0    http://repo.continuum.io/pkgs/free/linux-64/zlib-1.2.8-0.tar.bz2
$
```

**Comment by Juanlu001** [comment]
Cannot reproduce in a different machine, it has to be some specific problem. Closing.
