### ISSUE TITLE
ImportError: C extension for numpy and pandas

### ISSUE THREAD

**Issue by ohadle** [ContinuumIO/anaconda-issues#580]
Somewhat similar to https://github.com/ContinuumIO/anaconda-issues/issues/571.

I just installed anaconda (2.4.1, 64 bit) on my Ubuntu 15.10 VM. Importing either numpy or pandas fails:

```
>>> import pandas
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ohad/anaconda2/lib/python2.7/site-packages/pandas/__init__.py", line 13, in <module>
    "extensions first.".format(module))
ImportError: C extension: /home/ohad/.local/lib/python2.7/site-packages/numpy/random/mtrand.so: undefined symbol: PyFPE_jbuf not built. If you want to import pandas from the source directory, you may need to run 'python setup.py build_ext --inplace' to build the C extensions first.
```

```
>>> import numpy
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ohad/.local/lib/python2.7/site-packages/numpy/__init__.py", line 170, in <module>
    from . import add_newdocs
ImportError: cannot import name add_newdocs
```

**Comment by ilanschnell** [comment]
It looks like you have your system configured to look for numpy in `/home/ohad/.local/lib/python2.7/site-packages`.  Conda packages would usually never be installed there.  You can see from the traceback that pandas is imported from the Anaconda location, but not numpy.
