### ISSUE TITLE
Unexpected error in Navigator start up

### ISSUE THREAD

**Issue by gkanbach** [ContinuumIO/anaconda-issues#5821]
Navigator Error

An unexpected error occurred on Navigator start-up

Report

Please report this issue in the anaconda issue tracker

Main Error

string indices must be integers, not str
Traceback

Traceback (most recent call last):
  File "/Users/gottfriedkanbach/anaconda/lib/python2.7/site-packages/anaconda_navigator/exceptions.py", line 75, in exception_handler
    return_value = func(*args, **kwargs)
  File "/Users/gottfriedkanbach/anaconda/lib/python2.7/site-packages/anaconda_navigator/app/start.py", line 115, in start_app
    window = run_app(splash)
  File "/Users/gottfriedkanbach/anaconda/lib/python2.7/site-packages/anaconda_navigator/app/start.py", line 58, in run_app
    window = MainWindow(splash=splash)
  File "/Users/gottfriedkanbach/anaconda/lib/python2.7/site-packages/anaconda_navigator/widgets/main_window.py", line 160, in __init__
    self.api = AnacondaAPI()
  File "/Users/gottfriedkanbach/anaconda/lib/python2.7/site-packages/anaconda_navigator/api/anaconda_api.py", line 1205, in AnacondaAPI
    ANACONDA_API = _AnacondaAPI()
  File "/Users/gottfriedkanbach/anaconda/lib/python2.7/site-packages/anaconda_navigator/api/anaconda_api.py", line 65, in __init__
    self._conda_api = CondaAPI()
  File "/Users/gottfriedkanbach/anaconda/lib/python2.7/site-packages/anaconda_navigator/api/conda_api.py", line 1622, in CondaAPI
    CONDA_API = _CondaAPI()
  File "/Users/gottfriedkanbach/anaconda/lib/python2.7/site-packages/anaconda_navigator/api/conda_api.py", line 340, in __init__
    self.set_conda_prefix()
  File "/Users/gottfriedkanbach/anaconda/lib/python2.7/site-packages/anaconda_navigator/api/conda_api.py", line 489, in set_conda_prefix
    self.ROOT_PREFIX = info['root_prefix']
TypeError: string indices must be integers, not str

**Comment by gkanbach** [comment]
in previous issues I found that launching the navigator by typing 'anaconda-navigator' in a terminal window should do the trick --- and indeed it started just fine (although it takes a while on my old Mac Book with  OS X El Capitan v. 10.11.6
