### ISSUE TITLE
Incorrect dependencies for linux-64 libgdal-2.0.0-1 conda package

### ISSUE THREAD

**Issue by jjhelmus** [ContinuumIO/anaconda-issues#584]
The linux-64 libgdal-2.0.0-1 conda package in the default channel reports its geos dependency as un-versioned when in fact it has been linked to libgeos 3.4.2 and therefore requires that specific version to properly run.  Interestingly the libgdal-2.0.0-0 packages does not depend on geos at all.

```
~/.../pkgs/libgdal-2.0.0-1$ ldd lib/libgdal.so.20
    linux-vdso.so.1 =>  (0x00007fffc8360000)
    libgeos_c.so.1 => not found
    libgeos-3.4.2.so => not found
        ...
```

```
~/.../pkgs/libgdal-2.0.0-1$ cat info/index.json 
{
  "arch": "x86_64", 
  "build": "1", 
  "build_number": 1, 
  "depends": [
    "geos", 
    "hdf4", 
    "hdf5", 
    "kealib", 
    "libnetcdf", 
    "proj4", 
    "xerces-c"
  ], 
  "license": "MIT", 
  "name": "libgdal", 
  "platform": "linux", 
  "subdir": "linux-64", 
  "version": "2.0.0"
```

This causes problems if two packages which both depend on geos, but different version of the library, are installed in the same conda environment.  For example installing basemap and gdal into the same environment results in only basemap being functional:

```
~/sandbox$ conda create -n issue pip python=2.7
Fetching package metadata: ....
Solving package specifications: .............
Package plan for installation in environment /home/jhelmus/anaconda/envs/issue:

The following NEW packages will be INSTALLED:

    openssl:    1.0.2d-0     
    pip:        7.1.2-py27_0 
    python:     2.7.11-0     
    readline:   6.2-2        
    setuptools: 18.5-py27_0  
    sqlite:     3.8.4.1-1    
    tk:         8.5.18-0     
    wheel:      0.26.0-py27_1
    zlib:       1.2.8-0      

Proceed ([y]/n)? y

Linking packages ...
[      COMPLETE      ]|#########################################################################| 100%
#
# To activate this environment, use:
# $ source activate issue
#
# To deactivate this environment, use:
# $ source deactivate
#
~/sandbox$ source activate issue
discarding /home/jhelmus/anaconda/bin from PATH
prepending /home/jhelmus/anaconda/envs/issue/bin to PATH
~/sandbox$ conda install basemap gdal
Fetching package metadata: ....
Solving package specifications: .........................
Package plan for installation in environment /home/jhelmus/anaconda/envs/issue:

The following NEW packages will be INSTALLED:

    basemap:         1.0.7-np110py27_0
    cairo:           1.12.18-6        
    curl:            7.43.0-1         
    cycler:          0.9.0-py27_0     
    fontconfig:      2.11.1-5         
    freetype:        2.5.5-0          
    gdal:            2.0.0-py27_1     
    geos:            3.3.3-0          
    hdf4:            4.2.11-0         
    hdf5:            1.8.15.1-2       
    jpeg:            8d-0             
    kealib:          1.4.5-0          
    krb5:            1.13.2-0         
    libgdal:         2.0.0-1          
    libgfortran:     1.0-0            
    libnetcdf:       4.3.3.1-1        
    libpng:          1.6.17-0         
    libxml2:         2.9.2-0          
    matplotlib:      1.5.0-np110py27_0
    numpy:           1.10.1-py27_0    
    openblas:        0.2.14-3         
    pixman:          0.32.6-0         
    proj4:           4.9.1-0          
    py2cairo:        1.10.0-py27_2    
    pyparsing:       2.0.3-py27_0     
    pyqt:            4.11.4-py27_1    
    python-dateutil: 2.4.2-py27_0     
    pytz:            2015.7-py27_0    
    qt:              4.8.7-1          
    sip:             4.16.9-py27_0    
    six:             1.10.0-py27_0    
    xerces-c:        3.1.2-0          

The following packages will be DOWNGRADED:

    openssl:         1.0.2d-0 --> 1.0.1k-1         
    python:          2.7.11-0 --> 2.7.10-1         

Proceed ([y]/n)? y

Unlinking packages ...
[      COMPLETE      ]|#########################################################################| 100%
Linking packages ...
[      COMPLETE      ]|#########################################################################| 100%
~/sandbox$ python -c "from mpl_toolkits.basemap import Basemap"
~/sandbox$ python -c "import gdal"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/jhelmus/anaconda/envs/issue/lib/python2.7/site-packages/gdal.py", line 2, in <module>
    from osgeo.gdal import deprecation_warn
  File "/home/jhelmus/anaconda/envs/issue/lib/python2.7/site-packages/osgeo/__init__.py", line 21, in <module>
    _gdal = swig_import_helper()
  File "/home/jhelmus/anaconda/envs/issue/lib/python2.7/site-packages/osgeo/__init__.py", line 17, in swig_import_helper
    _mod = imp.load_module('_gdal', fp, pathname, description)
ImportError: libgeos-3.4.2.so: cannot open shared object file: No such file or directory
```

I believe if the libgdal-2.0.0-1 package had the correct dependency then conda would detect the conflicting geos version requirements (geos 3.3.3 vs 3.4.2) and back down to a version of libgdal which supports both packages (in this case  libgdal 2.0.0-0).  

The specific example above could also be solved by providing a build of basemap linked against geos 3.4.2 but I still believe that adding the version of geos to the libgdal would be best.

**Comment by groutr** [comment]
Thank you for the analysis.  geos was added as a dependency in the latest builds of libgdal to enable some extra functionality.  I will fix the recipe this week and release new packages.

**Comment by jjhelmus** [comment]
Wonderful, thanks for the quick response.

**Comment by theJollySin** [comment]
Was this fixed? Or, is there a way for me to hack around this?

**Comment by jjhelmus** [comment]
One work-around is to specify build 0 of the libgdal 2.0.0 library when installing the conda package using the following `conda install -gdal basemap libgdal=2.0.0=0`.  This results in a setup where both basemap and gdal both work.  I have not tested in org works with this setup.

**Comment by flamingbear** [comment]
@jjhelmus do you know how to specify the build version in meta.yaml?  I'm trying to build a package that depends on gdal 2.0 + matplotlib + etc.

Thanks
Matt

**Comment by flamingbear** [comment]
@jjhelmus nevermind.
`- libgdal 2.0.0 0 `

**Comment by jjhelmus** [comment]
I still am seeing an issues getting gdal and basemap installed in the same conda environment despite the libgdal 2.0.0-2 package. I believe a basemap package which links against geos 3.4.2 is needed.  

For the time being the following work around can be used to create a working environment with gdal and basemap `conda install --yes gdal basemap libgdal=2.0.0=0 krb5`.

```
~$ conda create -n flower python=2.7 gdal basemap
Fetching package metadata: ..
Solving package specifications: ...................
Package plan for installation in environment /home/jhelmus/anaconda/envs/flower:

The following NEW packages will be INSTALLED:

    basemap:         1.0.7-np110py27_0
    cairo:           1.12.18-6        
    curl:            7.45.0-0         
    cycler:          0.10.0-py27_0    
    fontconfig:      2.11.1-5         
    freetype:        2.5.5-0          
    gdal:            2.0.0-py27_1     
    geos:            3.3.3-0          
    hdf4:            4.2.11-0         
    hdf5:            1.8.15.1-2       
    jpeg:            8d-0             
    kealib:          1.4.5-0          
    libgdal:         2.0.0-1          
    libnetcdf:       4.3.3.1-3        
    libpng:          1.6.17-0         
    libxml2:         2.9.2-0          
    matplotlib:      1.5.1-np110py27_0
    mkl:             11.3.1-0         
    numpy:           1.10.4-py27_0    
    openssl:         1.0.2g-0         
    pip:             8.0.3-py27_0     
    pixman:          0.32.6-0         
    proj4:           4.9.1-0          
    pycairo:         1.10.0-py27_0    
    pyparsing:       2.0.3-py27_0     
    pyqt:            4.11.4-py27_1    
    python:          2.7.11-0         
    python-dateutil: 2.4.2-py27_0     
    pytz:            2015.7-py27_0    
    qt:              4.8.7-1          
    readline:        6.2-2            
    setuptools:      20.1.1-py27_0    
    sip:             4.16.9-py27_0    
    six:             1.10.0-py27_0    
    sqlite:          3.9.2-0          
    tk:              8.5.18-0         
    wheel:           0.29.0-py27_0    
    xerces-c:        3.1.2-0          
    zlib:            1.2.8-0          

Proceed ([y]/n)? y

Linking packages ...
[      COMPLETE      ]|###################################################| 100%
#
# To activate this environment, use:
# $ source activate flower
#
# To deactivate this environment, use:
# $ source deactivate
#
~$ source activate flower
discarding /home/jhelmus/anaconda/bin from PATH
prepending /home/jhelmus/anaconda/envs/flower/bin to PATH
~$ python -c "from mpl_toolkits.basemap import Basemap"
~$ python -c "import gdal"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/jhelmus/anaconda/envs/flower/lib/python2.7/site-packages/gdal.py", line 2, in <module>
    from osgeo.gdal import deprecation_warn
  File "/home/jhelmus/anaconda/envs/flower/lib/python2.7/site-packages/osgeo/__init__.py", line 21, in <module>
    _gdal = swig_import_helper()
  File "/home/jhelmus/anaconda/envs/flower/lib/python2.7/site-packages/osgeo/__init__.py", line 17, in swig_import_helper
    _mod = imp.load_module('_gdal', fp, pathname, description)
ImportError: libgeos-3.4.2.so: cannot open shared object file: No such file or directory
```

**Comment by mcg1969** [comment]
I've copied this over from [this conda issue](https://github.com/conda/conda/issues/2219#issuecomment-194511221).

--------

... `gdal`'s dependency lists are all over the map. Conda tries to differentiate between "strong" and "weak" dependencies: "strong" dependencies are shared across _all_ versions of a package, while "weak" dependencies are version-specific. In the case of "gdal", it's quite crazy:

- The earliest versions depended only on `python`
- Later versions brought in `numpy`
- Later versions brought in `libnetcdf` and `hdf5`
- Somewhere in the _middle of version 1.11.2_, `libgdal` was brought in. That's right, `libgdal` isn't even a consistent dependency in a minor version of `gdal`.
- _For build 1 of version 2.0.0_, a bunch of the dependencies are _dropped_, and _all_ that is left is `libgdal`, `numpy`, and `python`. Furthermore, the version requirement in `libgdal` is _dropped_: according to the metadata, any version of `libgdal` will do. (Surely that's not right.)

So the _only_ strong dependency that `gdal` has is `python` itself. Weak dependencies include `numpy`, `libnetcdf`, `libgdal`, `hdf5`.

This is crazymaking for a solver that is trying to take an algorithmic approach to determining which packages should be brought in and which should not be. Currently, the solver maximizes versions in this order: 1) requested packages, 2) strong dependencies, and 3) weak dependencies. Furthermore, when maximizing weak dependency versions, it favors _no package at all_ whenever possible. So the solver likes the idea of not having to bring in a few extra packages.

So my view is this: if a particular build of `libgdal` is critical here, then it needs to be _explicitly requested in the dependencies_. If you're not doing that, then you're giving the solver the discretion to do things you might not like.

**Comment by mcg1969** [comment]
@ilanschnell, this is a metadata fix, IMO.

**Comment by davidh-ssec** [comment]
Is there any news on this? I've had a lot of trouble with gdal versions and dependencies on linux, mac, and windows. The solution always seems to be manually installing krb5 or forcing version 1.11.2 or forcing libgdal to not be installed. Shouldn't these things all be specified in the meta.yaml? Is there a reason this hasn't been fixed?

**Comment by remenska** [comment]
+1

**Comment by eronlloyd** [comment]
I, too, am experiencing GDAL issues here. Still getting
> ImportError: libcom_err.so.3: cannot open shared object file: No such file or directory

after installing a fresh conda env on a CentOS 7 server with Python 3.5 and the latest conda updates.

**Comment by flamingbear** [comment]
@eronlloyd Can I suggest you try the gdal from conda-forge?  It seems to install the correct dependencies more times than not.

**Comment by eronlloyd** [comment]
@flamingbear that's exactly what I was able to do. Working out so far!

**Comment by DennisScuba** [comment]
Hi,

I have the same error, supisingly yesterday it worked but now I got this error:

```
runfile('/media/mattes/data1/dataDMattes/Code/Python/PythonProgram/main.py', wdir='/media/mattes/data1/dataDMattes/Code/Python/PythonProgram')
Traceback (most recent call last):

  File "<ipython-input-5-e8fdc416f3c8>", line 1, in <module>
    runfile('/media/mattes/data1/dataDMattes/Code/Python/PythonProgram/main.py', wdir='/media/mattes/data1/dataDMattes/Code/Python/PythonProgram')

  File "/home/mattes/anaconda3/envs/gmt-python/lib/python3.6/site-packages/spyder/utils/site/sitecustomize.py", line 705, in runfile
    execfile(filename, namespace)

  File "/home/mattes/anaconda3/envs/gmt-python/lib/python3.6/site-packages/spyder/utils/site/sitecustomize.py", line 102, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "/media/mattes/data1/dataDMattes/Code/Python/PythonProgram/main.py", line 18, in <module>
    import ogr

  File "/home/mattes/anaconda3/envs/gmt-python/lib/python3.6/site-packages/ogr.py", line 2, in <module>
    from osgeo.gdal import deprecation_warn

  File "/home/mattes/anaconda3/envs/gmt-python/lib/python3.6/site-packages/osgeo/__init__.py", line 21, in <module>
    _gdal = swig_import_helper()

  File "/home/mattes/anaconda3/envs/gmt-python/lib/python3.6/site-packages/osgeo/__init__.py", line 17, in swig_import_helper
    _mod = imp.load_module('_gdal', fp, pathname, description)

  File "/home/mattes/anaconda3/envs/gmt-python/lib/python3.6/imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)

  File "/home/mattes/anaconda3/envs/gmt-python/lib/python3.6/imp.py", line 343, in load_dynamic
    return _load(spec)

ImportError: libgeos-3.4.2.so: cannot open shared object file: No such file or directory
```

The output of `conda list`is the following:

```
# packages in environment at /home/mattes/anaconda3/envs/gmt-python:
#
# Name                    Version                   Build  Channel
alabaster                 0.7.10                   py36_1    conda-forge
asn1crypto                0.24.0                   py36_0    conda-forge
astroid                   1.6.4                    py36_0    conda-forge
babel                     2.5.3                    py36_0    conda-forge
backcall                  0.1.0                      py_0    conda-forge
backports                 1.0                      py36_1    conda-forge
backports.functools_lru_cache 1.5                      py36_0    conda-forge
blas                      1.1                    openblas    conda-forge
bleach                    2.1.3                      py_0    conda-forge
bokeh                     0.12.16                  py36_0    conda-forge
boost                     1.66.0                   py36_1    conda-forge
boost-cpp                 1.66.0                        1    conda-forge
bottleneck                1.2.1                    py36_1    conda-forge
bzip2                     1.0.6                         1    conda-forge
ca-certificates           2018.4.16                     0    conda-forge
cairo                     1.14.6                        5    conda-forge
certifi                   2018.4.16                py36_0    conda-forge
cffi                      1.11.5                   py36_0    conda-forge
cftime                    1.0.0                    py36_0    conda-forge
chardet                   3.0.4                    py36_0    conda-forge
click                     6.7                        py_1    conda-forge
cloudpickle               0.5.3                      py_0    conda-forge
cryptography              2.2.1                    py36_0    conda-forge
curl                      7.60.0                        0    conda-forge
cycler                    0.10.0           py36h93f1223_0    anaconda
cytoolz                   0.9.0.1                  py36_0    conda-forge
dask                      0.17.5                     py_0    conda-forge
dask-core                 0.17.5                     py_0    conda-forge
dbus                      1.11.0                        0    conda-forge
dcw-gmt                   1.1.3                         0    conda-forge
decorator                 4.3.0                      py_0    conda-forge
distributed               1.21.8                   py36_0    conda-forge
docutils                  0.14                     py36_0    conda-forge
entrypoints               0.2.3                    py36_1    conda-forge
expat                     2.1.0                         3    conda-forge
fftw                      3.3.7                         0    conda-forge
fontconfig                2.12.1                        6    conda-forge
freetype                  2.7                           2    conda-forge
freexl                    1.0.5                         0    conda-forge
gdal                      2.1.3                    py36_7    conda-forge
geos                      3.6.2                heeff764_2    anaconda
geotiff                   1.4.2                         1    conda-forge
gettext                   0.19.8.1                      0    conda-forge
ghostscript               9.22                          0    conda-forge
giflib                    5.1.4                         0    conda-forge
glib                      2.51.4                        0    conda-forge
gmp                       6.1.2                         0    conda-forge
gmt                       5.4.3           blas_openblas_200  [blas_openblas]  conda-forge
gmt-python                0+unknown                 <pip>
graphite2                 1.3.11                        0    conda-forge
gshhg-gmt                 2.3.7                         0    conda-forge
gst-plugins-base          1.8.0                         0    conda-forge
gstreamer                 1.8.0                         1    conda-forge
h5netcdf                  0.5.1                      py_0    conda-forge
h5py                      2.8.0            py36h470a237_0    conda-forge
harfbuzz                  1.4.3                         0    conda-forge
hdf4                      4.2.13                        0    conda-forge
hdf5                      1.10.1                        2    conda-forge
heapdict                  1.0.0                    py36_0    conda-forge
html5lib                  1.0.1                      py_0    conda-forge
icu                       58.2                          0    conda-forge
idna                      2.6                      py36_1    conda-forge
imagesize                 1.0.0                    py36_0    conda-forge
ipykernel                 4.8.2                    py36_0    conda-forge
ipython                   6.4.0                    py36_0    conda-forge
ipython_genutils          0.2.0                    py36_0    conda-forge
isort                     4.3.4                    py36_0    conda-forge
iteration_utilities       0.7.0                    py36_0    conda-forge
jedi                      0.12.0                   py36_0    conda-forge
jinja2                    2.10                     py36_0    conda-forge
jpeg                      9b                            2    conda-forge
json-c                    0.12.1                        0    conda-forge
jsonschema                2.6.0                    py36_1    conda-forge
jupyter_client            5.2.3                    py36_0    conda-forge
jupyter_core              4.4.0                      py_0    conda-forge
kealib                    1.4.7                         4    conda-forge
kiwisolver                1.0.1                    py36_1    conda-forge
krb5                      1.14.6                        0    conda-forge
lazy-object-proxy         1.3.1                    py36_0    conda-forge
libboost                  1.65.1               habcd387_4  
libdap4                   3.18.3                        2    conda-forge
libffi                    3.2.1                         3    conda-forge
libgcc                    7.2.0                h69d50b8_2  
libgcc-ng                 7.2.0                hdf63c60_3  
libgdal                   2.0.0                         1    anaconda
libgfortran               3.0.0                         1  
libiconv                  1.15                          0    conda-forge
libkml                    1.3.0                h8777076_2  
libnetcdf                 4.4.1.1                      10    conda-forge
libpng                    1.6.28                        2    conda-forge
libpq                     9.6.3                         0    conda-forge
libsodium                 1.0.16                        0    conda-forge
libspatialite             4.3.0a                       18    conda-forge
libssh2                   1.8.0                         2    conda-forge
libstdcxx-ng              7.2.0                hdf63c60_3  
libtiff                   4.0.9                         0    conda-forge
libxcb                    1.13                          0    conda-forge
libxml2                   2.9.8                         0    conda-forge
locket                    0.2.0                    py36_1    conda-forge
markupsafe                1.0                      py36_0    conda-forge
matlabengineforpython     R2018a                    <pip>
matplotlib                1.5.3               np113py36_8    conda-forge
mccabe                    0.6.1                    py36_0    conda-forge
mistune                   0.8.3                    py36_1    conda-forge
msgpack-python            0.5.6            py36h2d50403_2    conda-forge
nbconvert                 5.3.1                      py_1    conda-forge
nbformat                  4.4.0                    py36_0    conda-forge
ncurses                   5.9                          10    conda-forge
netcdf4                   1.3.1                    py36_1    conda-forge
numpy                     1.13.3          py36_blas_openblas_201  [blas_openblas]  conda-forge
numpydoc                  0.8.0                    py36_0    conda-forge
openblas                  0.2.20                        8    conda-forge
openjpeg                  2.1.2                         3    conda-forge
openssl                   1.0.2o                        0    conda-forge
packaging                 17.1                       py_0    conda-forge
pandas                    0.23.0                   py36_1    conda-forge
pandoc                    2.2.1                         0    conda-forge
pandocfilters             1.4.2                    py36_0    conda-forge
pango                     1.40.4                        0    conda-forge
parso                     0.2.1                      py_0    conda-forge
partd                     0.3.8                    py36_0    conda-forge
patsy                     0.5.0                    py36_0    anaconda
pcre                      8.41                          1    conda-forge
pexpect                   4.5.0                    py36_0    conda-forge
pickleshare               0.7.4                    py36_0    conda-forge
pip                       9.0.3                    py36_0    conda-forge
pixman                    0.34.0                        2    conda-forge
poppler                   0.52.0                        2    conda-forge
poppler-data              0.4.9                         0    conda-forge
proj4                     4.9.3                         5    conda-forge
prompt_toolkit            1.0.15                   py36_0    conda-forge
psutil                    5.4.5                    py36_0    conda-forge
ptyprocess                0.5.2                    py36_0    conda-forge
pycodestyle               2.4.0                    py36_0    conda-forge
pycparser                 2.18                     py36_0    conda-forge
pyflakes                  2.0.0                      py_0    conda-forge
pygments                  2.2.0                    py36_0    conda-forge
pylint                    1.9.0                    py36_0    conda-forge
pyopenssl                 18.0.0                   py36_0    conda-forge
pyparsing                 2.2.0                    py36_0    conda-forge
pyproj                    1.9.5.1                   <pip>
pyqt                      4.11.4                   py36_3    conda-forge
pyshp                     1.2.12                     py_0    conda-forge
pysocks                   1.6.8                    py36_1    conda-forge
python                    3.6.3                         1    conda-forge
python-dateutil           2.7.3                      py_0    conda-forge
pytz                      2018.4                     py_0    conda-forge
pyyaml                    3.12                     py36_1    conda-forge
pyzmq                     17.0.0                   py36_4    conda-forge
qt                        4.8.7                         7    conda-forge
qtawesome                 0.4.4                    py36_0    conda-forge
qtconsole                 4.3.1                    py36_0    conda-forge
qtpy                      1.4.2            py36h8a2030e_0    conda-forge
readline                  6.2                           0    conda-forge
requests                  2.18.4                   py36_1    conda-forge
rope                      0.10.7                   py36_0    conda-forge
scipy                     1.1.0           py36_blas_openblas_200  [blas_openblas]  conda-forge
setuptools                39.2.0                   py36_0    conda-forge
shapely                   1.6.4                    py36_0    conda-forge
simplegeneric             0.8.1                    py36_0    conda-forge
sip                       4.18                     py36_1    conda-forge
six                       1.11.0                   py36_1    conda-forge
snowballstemmer           1.2.1                    py36_0    conda-forge
sortedcontainers          2.0.2                    py36_0    conda-forge
sphinx                    1.7.4                    py36_0    conda-forge
sphinxcontrib-websupport  1.0.1                    py36_0    conda-forge
spyder                    3.2.8                    py36_0    conda-forge
sqlite                    3.13.0                        1    conda-forge
statsmodels               0.9.0            py36h3010b51_0    anaconda
tblib                     1.3.2                    py36_0    conda-forge
testpath                  0.3.1                    py36_0    conda-forge
tk                        8.5.19                        2    conda-forge
toolz                     0.9.0                      py_0    conda-forge
tornado                   5.0.2                    py36_0    conda-forge
traitlets                 4.3.2                    py36_0    conda-forge
typing                    3.6.4                    py36_0    conda-forge
urllib3                   1.22                     py36_0    conda-forge
util-linux                2.21                          0  
wcwidth                   0.1.7                    py36_0    conda-forge
webencodings              0.5                      py36_0    conda-forge
wheel                     0.31.0                   py36_0    conda-forge
wrapt                     1.10.11                  py36_0    conda-forge
xarray                    0.10.4                   py36_0    conda-forge
xerces-c                  3.2.0                         0    conda-forge
xorg-libxau               1.0.8                         3    conda-forge
xorg-libxdmcp             1.1.2                         3    conda-forge
xz                        5.2.3                         0    conda-forge
yaml                      0.1.7                         0    conda-forge
zeromq                    4.2.5                         1    conda-forge
zict                      0.1.3                      py_0    conda-forge
zlib                      1.2.11               h470a237_2    conda-forge

```

Does someone has an idea?
Thank you very much in advance!

**Comment by msarahan** [comment]
We don't support conda-forge packages on this issue tracker.  Conda-forge is an independent entity from Anaconda.

The poppler problem that exists right now can be resolved with:

```conda install "poppler<0.62"```

Closing this issue, because aside from the current poppler problem, our GDAL stack is in much better shape since the 5.0 transition effort.
