### ISSUE TITLE
Issue with Anaconda Launcher

### ISSUE THREAD

**Issue by kaelchan** [ContinuumIO/anaconda-issues#586]
Please highlight this text, then hit Ctrl V or Cmd V to replace with the information about your error.Please replace this line with an explanation of what you were attempting to do when you ran into this error

---
## Uncaught Exception

```
Error: spawn conda ENOENT
    at exports._errnoException (util.js:734:11)
    at Process.ChildProcess._handle.onexit (child_process.js:1022:32)
    at child_process.js:1115:20
    at process._tickCallback (node.js:375:11)
```
## Platform Information
- Operating System: darwin
- Conda Version: 3.18.9
- Conda Platform: osx-64

``` json
{
  "channels": [
    "https://repo.continuum.io/pkgs/free/osx-64/",
    "https://repo.continuum.io/pkgs/free/noarch/",
    "https://repo.continuum.io/pkgs/pro/osx-64/",
    "https://repo.continuum.io/pkgs/pro/noarch/"
  ],
  "conda_build_version": "1.18.2",
  "conda_version": "3.18.9",
  "default_prefix": "//anaconda",
  "envs": [
    "//anaconda/envs/py35"
  ],
  "envs_dirs": [
    "//anaconda/envs"
  ],
  "is_foreign": false,
  "pkgs_dirs": [
    "//anaconda/pkgs"
  ],
  "platform": "osx-64",
  "python_version": "3.5.1.final.0",
  "rc_path": null,
  "requests_version": "2.8.1",
  "root_prefix": "//anaconda",
  "root_writable": true,
  "sys_rc_path": "//anaconda/.condarc",
  "user_rc_path": "/Users/kael/.condarc",
  "condaBuildVersion": "1.18.2",
  "condaVersion": "3.18.9",
  "defaultPrefix": "//anaconda",
  "envsDirs": [
    "//anaconda/envs"
  ],
  "isForeign": false,
  "pkgsDirs": [
    "//anaconda/pkgs"
  ],
  "pythonVersion": "3.5.1.final.0",
  "rcPath": null,
  "requestsVersion": "2.8.1",
  "rootPrefix": "//anaconda",
  "rootWritable": true,
  "sysRcPath": "//anaconda/.condarc",
  "userRcPath": "/Users/kael/.condarc"
}
```

Please remove this line, scroll back to the top, and follow the directions at the top of this report.

**Comment by goanpeca** [comment]
Launcher has been deprecated for several months. Anaconda Navigator replaced it. Lo learn more please visit the documentation.

To install navigator on the command line you can type:

`$ conda install anaconda-navigator` or download the latest Anaconda
