### ISSUE TITLE
Compiling with older versions of gfortran causes segfault in interpolative in SciPy 0.13

### ISSUE THREAD

**Issue by teoliphant** [ContinuumIO/anaconda-issues#59]
scipy.test() in Anaconda 1.9 causes a segfault 

due to the use of a compiler that appears not to handle the entry() construct of fortran correctly..  

Here is the scipy issue where it is noted that updating to gfortran 4.4 fixes the problem.

https://github.com/scipy/scipy/issues/2939

**Comment by pv** [comment]
Appears to be still there in current anaconda packages (scipy 0.17.0-np110py27_1), cf. https://github.com/scipy/scipy/issues/5917

**Comment by ilanschnell** [comment]
We now use gfortran 4.4.7 on Linux and link against libgfortran 3.0.  All tests run without segfaults.

**Comment by lileipku00** [comment]
@ilanschnell  yes, without segfaults for new `scipy`.

 but when `conda update scipy`, `libgfortran` was updated from 1.0 to 3.0, then `numpy.test` , which passed all tests, now outputs

```
======================================================================
FAIL: test_umath.TestComplexFunctions.test_branch_cuts(<ufunc 'arccosh'>, [-1, 0.5], [1j, 1j], 1, -1, True)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/user/anaconda/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/user/anaconda/lib/python2.7/site-packages/numpy/core/tests/test_umath.py", line 1748, in _check_branch_cut
    assert_(np.all(np.absolute(y0.imag - yp.imag) < atol), (y0, yp))
  File "/home/user/anaconda/lib/python2.7/site-packages/numpy/testing/utils.py", line 53, in assert_
    raise AssertionError(smsg)
AssertionError: (array([  0.00000000e+00+3.14159265j,   1.11022302e-16-1.04719755j]), array([  4.71216091e-07+3.14159218j,   1.28119737e-13+1.04719755j]))

----------------------------------------------------------------------
Ran 6153 tests in 141.610s

FAILED (KNOWNFAIL=3, SKIP=1, failures=1)
```
on one server and with one more error on another
```
======================================================================
ERROR: test_kind.TestKind.test_all
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/user/anaconda/lib/python2.7/site-packages/nose/case.py", line 381, in setUp
    try_run(self.inst, ('setup', 'setUp'))
  File "/home/user/anaconda/lib/python2.7/site-packages/nose/util.py", line 471, in try_run
    return func()
  File "/home/user/anaconda/lib/python2.7/site-packages/numpy/f2py/tests/util.py", line 367, in setUp
    module_name=self.module_name)
  File "/home/user/anaconda/lib/python2.7/site-packages/numpy/f2py/tests/util.py", line 79, in wrapper
    memo[key] = func(*a, **kw)
  File "/home/user/anaconda/lib/python2.7/site-packages/numpy/f2py/tests/util.py", line 150, in build_module
    __import__(module_name)
ImportError: /home/user/anaconda/bin/../lib/libgfortran.so.3: version `GFORTRAN_1.4' not found (required by /tmp/tmpg_y9Gt/_test_ext_module_5405.so)

======================================================================
FAIL: test_umath.TestComplexFunctions.test_branch_cuts(<ufunc 'arccosh'>, [-1, 0.5], [1j, 1j], 1, -1, True)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/user/anaconda/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/user/anaconda/lib/python2.7/site-packages/numpy/core/tests/test_umath.py", line 1748, in _check_branch_cut
    assert_(np.all(np.absolute(y0.imag - yp.imag) < atol), (y0, yp))
  File "/home/user/anaconda/lib/python2.7/site-packages/numpy/testing/utils.py", line 53, in assert_
    raise AssertionError(smsg)
AssertionError: (array([  0.00000000e+00+3.14159265j,   1.11022302e-16-1.04719755j]), array([  4.71216091e-07+3.14159218j,   1.28119737e-13+1.04719755j]))

----------------------------------------------------------------------
Ran 6153 tests in 103.409s

FAILED (KNOWNFAIL=3, SKIP=1, errors=1, failures=1)

```

**Comment by ilanschnell** [comment]
Thanks, I'm rebuilding `numpy` (the `nomkl` version) against the new `libgfortran 3.0` as well.

**Comment by ilanschnell** [comment]
The latest `numpy 1.9`, `numpy 1.10` and `scipy` (0.17.0, linked to numpy 1.9/1.10) are not all (mkl and nomkl) rebuild against libgfortran 3.0 (on 32 and 64 bit Linux, against Python 2.7, 3.4, 3.5).

2 (projects) x 2 (numpy versions) x 2 (mkl/nomkl) x 3 (Pythons) x 2 (Linux 32/64) = 48 conda packages
