### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by cgestraviz** [ContinuumIO/anaconda-issues#5973]
## Main error
The following errors occurred:
## Traceback
```
Traceback (most recent call last):
  File "/Users/Carlos/anaconda/lib/python3.6/site-packages/conda/exceptions.py", line 640, in conda_exception_handler
    return_value = func(*args, **kwargs)
  File "/Users/Carlos/anaconda/lib/python3.6/site-packages/conda_env/cli/main_create.py", line 78, in execute
    directory=os.getcwd())
  File "/Users/Carlos/anaconda/lib/python3.6/site-packages/conda_env/specs/__init__.py", line 20, in detect
    if spec.can_handle():
  File "/Users/Carlos/anaconda/lib/python3.6/site-packages/conda_env/specs/yaml_file.py", line 14, in can_handle
    self._environment = env.from_file(self.filename)
  File "/Users/Carlos/anaconda/lib/python3.6/site-packages/conda_env/env.py", line 79, in from_file
    yamlstr = fp.read()
  File "/Users/Carlos/anaconda/lib/python3.6/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xd1 in position 8: ordinal not in range(128)

```
## System information
```
python: 3.6.2
language: en
os: Darwin;15.6.0;Darwin Kernel Version 15.6.0: Sun Jun  4 21:43:07 PDT 2017; root:xnu-3248.70.3~1/RELEASE_X86_64;x86_64;i386
version: 1.6.2
platform: osx-64
qt: 5.6.2
pyqt: 5.6.0
conda: 4.3.25
```

**Comment by goanpeca** [comment]
@cgestraviz are you using non ascii characters or accented characters somewhere?
