### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by saif1980** [ContinuumIO/anaconda-issues#5999]
## Main error
An unexpected error occurred on Navigator start-up<br>psutil.AccessDenied (pid=2200)
## Traceback
```
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\psutil\_pswindows.py", line 620, in wrapper
    return fun(self, *args, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\psutil\_pswindows.py", line 690, in cmdline
    ret = cext.proc_cmdline(self.pid)
PermissionError: [WinError 5] Access is denied

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\anaconda_navigator\exceptions.py", line 75, in exception_handler
    return_value = func(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 108, in start_app
    if misc.load_pid() is None:  # A stale lock might be around
  File "C:\ProgramData\Anaconda3\lib\site-packages\anaconda_navigator\utils\misc.py", line 384, in load_pid
    cmds = process.cmdline()
  File "C:\ProgramData\Anaconda3\lib\site-packages\psutil\__init__.py", line 701, in cmdline
    return self._proc.cmdline()
  File "C:\ProgramData\Anaconda3\lib\site-packages\psutil\_pswindows.py", line 623, in wrapper
    raise AccessDenied(self.pid, self._name)
psutil.AccessDenied: psutil.AccessDenied (pid=2200)

```
## System information
```
python: 3.6.1
language: en_US
os: Windows;7;6.1.7601;AMD64;Intel64 Family 6 Model 60 Stepping 3, GenuineIntel
version: 1.6.2
platform: win-64
qt: 5.6.2
pyqt: 5.6.0
conda: 4.3

**Comment by saif1980** [comment]
i execute the commands as below
C:\ProgramData\Anaconda3\Scripts>conda update anaconda-navigator
Fetching package metadata ...........
Solving package specifications: .

Package plan for installation in environment C:\ProgramData\Anaconda3:

The following packages will be UPDATED:

    anaconda:           4.4.0-np112py36_0 --> custom-py36_0
    anaconda-navigator: 1.6.2-py36_0      --> 1.6.4-py36_0
    conda:              4.3.21-py36_0     --> 4.3.25-py36_0

Proceed ([y]/n)? y

anaconda-custo 100% |###############################| Time: 0:00:00 151.36 kB/s
anaconda-navig 100% |###############################| Time: 0:00:53  75.19 kB/s
conda-4.3.25-p 100% |###############################| Time: 0:00:07  73.46 kB/s
INFO menuinst_win32:__init__(182): Menu: name: 'Anaconda${PY_VER} ${PLATFORM}',
prefix: 'C:\ProgramData\Anaconda3', env_name: 'None', mode: 'None', used_mode: '
system'
INFO menuinst_win32:__init__(182): Menu: name: 'Anaconda${PY_VER} ${PLATFORM}',
prefix: 'C:\ProgramData\Anaconda3', env_name: 'None', mode: 'None', used_mode: '
system'
INFO menuinst_win32:__init__(182): Menu: name: 'Anaconda${PY_VER} ${PLATFORM}',
prefix: 'C:\ProgramData\Anaconda3', env_name: 'None', mode: 'None', used_mode: '
system'
INFO menuinst_win32:__init__(182): Menu: name: 'Anaconda${PY_VER} ${PLATFORM}',
prefix: 'C:\ProgramData\Anaconda3', env_name: 'None', mode: 'None', used_mode: '
system'

C:\ProgramData\Anaconda3\Scripts>conda update navigator-updater
Fetching package metadata ...........
Solving package specifications: .

# All requested packages already installed.
# packages in environment at C:\ProgramData\Anaconda3:
#
navigator-updater         0.1.0                    py36_0

C:\ProgramData\Anaconda3\Scripts>


but then when i start the navigator i get the below message:

Traceback (most recent call last):
File "C:\ProgramData\Anaconda3\lib\site-packages\psutil\_pswindows.py", line 620, in wrapper
return fun(self, *args, **kwargs)
File "C:\ProgramData\Anaconda3\lib\site-packages\psutil\_pswindows.py", line 690, in cmdline
ret = cext.proc_cmdline(self.pid)
PermissionError: [WinError 5] Access is denied

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "C:\ProgramData\Anaconda3\lib\site-packages\anaconda_navigator\exceptions.py", line 75, in exception_handler
return_value = func(*args, **kwargs)
File "C:\ProgramData\Anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 113, in start_app
if misc.load_pid() is None: # A stale lock might be around
File "C:\ProgramData\Anaconda3\lib\site-packages\anaconda_navigator\utils\misc.py", line 384, in load_pid
cmds = process.cmdline()
File "C:\ProgramData\Anaconda3\lib\site-packages\psutil\__init__.py", line 701, in cmdline
return self._proc.cmdline()
File "C:\ProgramData\Anaconda3\lib\site-packages\psutil\_pswindows.py", line 623, in wrapper
raise AccessDenied(self.pid, self._name)
psutil.AccessDenied: psutil.AccessDenied (pid=2200)

**Comment by saif1980** [comment]
OK i restart the PC and it works now

**Comment by goanpeca** [comment]
@saif1980 I see you have an all user install. I recommend to do a current user install.
