### ISSUE TITLE
ImportError: No module named _imagingtk

### ISSUE THREAD

**Issue by alefnula** [ContinuumIO/anaconda-issues#6]
Apparently the PIL module is not compiled to support the Tkinter GUI module. Here is a simple script that reproduces the problem:

``` python
import Tkinter as tk
from PIL import Image, ImageTk

root = tk.Tk()
image = Image.open('test.jpg')
photo = ImageTk.PhotoImage(image)
```

Error:

``` python
Traceback (most recent call last):
  File "test.py", line 6, in <module>
    photo = ImageTk.PhotoImage(image)
  File "C:\Anaconda\lib\site-packages\PIL\ImageTk.py", line 116, in __init__
    self.paste(image)
  File "C:\Anaconda\lib\site-packages\PIL\ImageTk.py", line 181, in paste
    import _imagingtk
ImportError: No module named _imagingtk
```

Update: I forgot to specify, this is on Windows (both 32bit and 64bit installations). On MacOSX the same code results in `Segmentation fault: 11`

**Comment by pablo-esteban** [comment]
I removed PIL and updated to Pillow 3.0.0 but the problem persists. My environment is:

             platform : win-64
        conda version : 3.18.9
    conda-build version : 1.14.1
         python version : 2.7.11.final.0
       requests version : 2.9.0

**Comment by akorosov** [comment]
Similar but not the same issue:
Image.open('tmp.png').save('tmp.jpg', 'JPEG') crashes python with segmentation fault
 Current conda install:
```
             platform : linux-64
        conda version : 3.19.0
  conda-build version : not installed
       python version : 2.7.11.final.0
     requests version : 2.9.1
               pillow : 3.1.0                    py27_0  defaults 
```

**Comment by ddale** [comment]
I've offered a fix to the broken PhotoImage/_imagingtk issue on Mac (pillow builds against system framework tk, anaconda loads its own tk), just requires a one-line patch to the setup.py file.

On windows, it looks like as long as the setup.py file is able to identify that tk is installed, and can find tk.h, it will build _imagingtk.

**Comment by ddale** [comment]
I think this is a trivial fix. I just added tk to the build and run requirements in this recipe: https://github.com/praxes/hedm-conda-recipes/tree/master/pillow, built, installed, and no longer get the missing _imagingtk errors.

**Comment by Sruthik22** [comment]
@ddale what do I have to do being a Windows User

**Comment by yoavram** [comment]
Download pillow from Google's site.
Go to http://www.lfd.uci.edu/~gohlke/pythonlibs/#pillow, choose the correct who file based on your platform and python version, then run `pip install <filename.whl>`

**Comment by Veagau** [comment]
> I have: Python 2.7.6 |Anaconda 2.0.1 (64-bit).
> 
> Finally I had to remove PIL with conda and install "pillow" from http://www.lfd.uci.edu/~gohlke/pythonlibs/#pil (Pillow-2.5.3.win-amd64-py2.7.exe for me) and I can now use PhotoImage to display jpeg images with the code below:
> 
> ```
> import os
> import Tkinter
> from PIL import Image, ImageTk
> working_dir = "C:\Users\user\Images\\"
> os.chdir(working_dir)
> a = Image.open("Test.jpg")
> master = Tkinter.Tk()
> photo = ImageTk.PhotoImage(a)
> Tkinter.Label(master, image=photo).pack()
> master.mainloop()
> ```

It works out for me.
