### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by hacksk** [ContinuumIO/anaconda-issues#6011]
## Main error
Application <b>spyder</b> launch may have produced errors.
## Traceback
```
Traceback (most recent call last):
  File "/home/hacksk/anaconda2/bin/spyder", line 6, in <module>
    sys.exit(spyder.app.start.main())
  File "/home/hacksk/anaconda2/lib/python2.7/site-packages/spyder/app/start.py", line 103, in main
    from spyder.app import mainwindow
  File "/home/hacksk/anaconda2/lib/python2.7/site-packages/spyder/app/mainwindow.py", line 92, in <module>
    from qtpy import QtWebEngineWidgets  # analysis:ignore
  File "/home/hacksk/anaconda2/lib/python2.7/site-packages/qtpy/QtWebEngineWidgets.py", line 26, in <module>
    from PyQt5.QtWebKitWidgets import QWebPage as QWebEnginePage
ImportError: libselinux.so.1: cannot open shared object file: No such file or directory

```
## System information
```
platform: linux-64
version: 1.6.2
conda: 4.3.21
qt: 5.6.2
language: en
python: 2.7.13
os: Linux;4.12.13-1-ARCH;#1 SMP PREEMPT Fri Sep 15 06:36:43 UTC 2017;x86_64;
pyqt: 5.6.0
```

**Comment by ccordoba12** [comment]
Please install libselinux with your package manager to fix this error.
