### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by medakasbi** [ContinuumIO/anaconda-issues#6013]
## Main error
Application <b>notebook</b> launch may have produced errors.
## Traceback
```
[E 09:27:25.183 NotebookApp] Exception while loading config file C:\Users\MOHAMED\.jupyter\jupyter_notebook_config.py
    Traceback (most recent call last):
      File "C:\Users\MOHAMED\Anaconda3\lib\site-packages\traitlets\config\application.py", line 562, in _load_config_files
        config = loader.load_config()
      File "C:\Users\MOHAMED\Anaconda3\lib\site-packages\traitlets\config\loader.py", line 457, in load_config
        self._read_file_as_dict()
      File "C:\Users\MOHAMED\Anaconda3\lib\site-packages\traitlets\config\loader.py", line 489, in _read_file_as_dict
        py3compat.execfile(conf_filename, namespace)
      File "C:\Users\MOHAMED\Anaconda3\lib\site-packages\ipython_genutils\py3compat.py", line 198, in execfile
        exec(compiler(f.read(), fname, 'exec'), glob, loc)
      File "C:\Users\MOHAMED\.jupyter\jupyter_notebook_config.py", line 587
        function(sublime_keymap, cell, IPython) {
                                                ^
    SyntaxError: invalid syntax

```
## System information
```
python: 3.6.1
language: fr_FR
os: Windows;10;10.0.10586;AMD64;AMD64 Family 16 Model 6 Stepping 3, AuthenticAMD
version: 1.6.2
platform: win-64
qt: 5.6.2
pyqt: 5.6.0
conda: 4.3.23
```

**Comment by goanpeca** [comment]
The file `C:\Users\MOHAMED\.jupyter\jupyter_notebook_config.py"` seems to be incorrect, you could delete and try again.
