### ISSUE TITLE
Previously existing .condarc breaks conda

### ISSUE THREAD

**Issue by desilinguist** [ContinuumIO/anaconda-issues#61]
I had a `.condarc` from a previous installation that just had the following two lines in it:

```
channels
  - defaults
  - http://conda.binstar.org/dan_blanchard
```

I then downloaded the Anaconda installer and ran it. Everything installed smoothly but when I tried to do anything with `conda`, e.g., `conda update conda` or `conda create test`, I always got the following error:

``` python
Traceback (most recent call last):
  File "/Users/nmadnani/anaconda/bin/conda", line 3, in <module>
    from conda.cli import main
  File "/Users/nmadnani/anaconda/lib/python2.7/site-packages/conda/cli/__init__.py", line 8, in <module>
    from conda.cli.main import main
  File "/Users/nmadnani/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 46, in <module>
    from conda.cli import main_build
  File "/Users/nmadnani/anaconda/lib/python2.7/site-packages/conda/cli/main_build.py", line 11, in <module>
    from conda.cli import common
  File "/Users/nmadnani/anaconda/lib/python2.7/site-packages/conda/cli/common.py", line 8, in <module>
    import conda.config as config
  File "/Users/nmadnani/anaconda/lib/python2.7/site-packages/conda/config.py", line 79, in <module>
    rc.get('root_dir', sys.prefix))))
AttributeError: 'str' object has no attribute 'get'
```

Removing the .condarc makes everything work.

**Comment by csoja** [comment]
@kalefranz Can we close this one?

**Comment by kalefranz** [comment]
Yeah definitely not relevant anymore.
