### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by CaMarchPa** [ContinuumIO/anaconda-issues#6114]
## Main error
An unexpected error occurred on Navigator start-up<br>'ascii' codec can't encode character u'\xe9' in position 11: ordinal not in range(128)
## Traceback
```
Traceback (most recent call last):
  File "/home/ali/anaconda2/lib/python2.7/site-packages/anaconda_navigator/exceptions.py", line 75, in exception_handler
    return_value = func(*args, **kwargs)
  File "/home/ali/anaconda2/lib/python2.7/site-packages/anaconda_navigator/app/start.py", line 115, in start_app
    window = run_app(splash)
  File "/home/ali/anaconda2/lib/python2.7/site-packages/anaconda_navigator/app/start.py", line 58, in run_app
    window = MainWindow(splash=splash)
  File "/home/ali/anaconda2/lib/python2.7/site-packages/anaconda_navigator/widgets/main_window.py", line 322, in __init__
    self.tab_projects = ProjectsTab(parent=self)
  File "/home/ali/anaconda2/lib/python2.7/site-packages/anaconda_navigator/widgets/tabs/projects.py", line 77, in __init__
    self.widget = ProjectsWidget()
  File "/home/ali/anaconda2/lib/python2.7/site-packages/anaconda_navigator/widgets/projects.py", line 212, in __init__
    self.file_explorer = ExplorerWidget()
  File "/home/ali/anaconda2/lib/python2.7/site-packages/anaconda_navigator/widgets/explorer.py", line 1252, in __init__
    self.update_breadcrumb()
  File "/home/ali/anaconda2/lib/python2.7/site-packages/anaconda_navigator/widgets/explorer.py", line 1267, in update_breadcrumb
    text += '<a href="{link}">{p}</a>'.format(p=p, link=cum_path)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 11: ordinal not in range(128)

```
## System information
```
platform: linux-64
version: 1.6.2
conda: 4.3.21
qt: 5.6.2
language: fr_FR
python: 2.7.13
os: Linux;4.2.0-27-generic;#32~14.04.1-Ubuntu SMP Fri Jan 22 15:32:26 UTC 2016;x86_64;x86_64
pyqt: 5.6.0
```

**Comment by goanpeca** [comment]
@CaMarchPa it seems some of the paths used included non-ascii or accented characters. We do not officially support them, so please remove those paths and use unaccented non-ascii paths
