### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by Pkumar37** [ContinuumIO/anaconda-issues#6124]
## Main error
Application <b>spyder</b> launch may have produced errors.
## Traceback
```
Traceback (most recent call last):
  File "/Users/pkum37/anaconda/lib/python3.6/site-packages/spyder/app/mainwindow.py", line 3011, in main
    mainwindow = run_spyder(app, options, args)
  File "/Users/pkum37/anaconda/lib/python3.6/site-packages/spyder/app/mainwindow.py", line 2913, in run_spyder
    main.setup()
  File "/Users/pkum37/anaconda/lib/python3.6/site-packages/spyder/app/mainwindow.py", line 784, in setup
    from spyder.plugins.help import Help
  File "/Users/pkum37/anaconda/lib/python3.6/site-packages/spyder/plugins/help.py", line 33, in <module>
    from spyder.utils.help.sphinxify import (CSS_PATH, generate_context,
  File "/Users/pkum37/anaconda/lib/python3.6/site-packages/spyder/utils/help/sphinxify.py", line 31, in <module>
    import sphinx
  File "/Users/pkum37/sphinx.py", line 9, in <module>
    import cmu_sphinx4
ModuleNotFoundError: No module named 'cmu_sphinx4'

```
## System information
```
python: 3.6.1
language: en
os: Darwin;16.6.0;Darwin Kernel Version 16.6.0: Fri Apr 14 16:21:16 PDT 2017; root:xnu-3789.60.24~6/RELEASE_X86_64;x86_64;i386
version: 1.6.2
platform: osx-64
qt: 5.6.2
pyqt: 5.6.0
conda: 4.3.22
```

**Comment by goanpeca** [comment]
Please reinstall sphinx

```
conda install sphinx --force
```
