### ISSUE TITLE
Anaconda AssertionError: SRE module mismatch on windows 8.1

### ISSUE THREAD

**Issue by aktech** [ContinuumIO/anaconda-issues#619]
I installed the Python3.5 version of Anaconda (64bit) for windows from here:
https://www.continuum.io/downloads#_windows

And this is what happens, when I try to run `ipython`

```
Microsoft Windows [Version 6.3.9600]
(c) 2013 Microsoft Corporation. All rights reserved.

C:\Users\Amit>ipython
Traceback (most recent call last):
  File "C:\Anaconda3\Scripts\ipython-script.py", line 3, in <module>
    from IPython import start_ipython
  File "C:\Anaconda3\lib\site-packages\IPython\__init__.py", line 47, in <module>
    from .core.application import Application
  File "C:\Anaconda3\lib\site-packages\IPython\core\application.py", line 16, in <module>
    import glob
  File "C:\Python34\Lib\glob.py", line 4, in <module>
    import re
  File "C:\Python34\Lib\re.py", line 123, in <module>
    import sre_compile
  File "C:\Python34\Lib\sre_compile.py", line 18, in <module>
    assert _sre.MAGIC == MAGIC, "SRE module mismatch"
AssertionError: SRE module mismatch

C:\Users\Amit>
```

**Comment by nate-russell** [comment]
any progress? i have the same issue on windows 10

**Comment by YazDog** [comment]
How did you work this?

**Comment by nate-russell** [comment]
I re-installed anaconda until it worked. Haven't had the issue again.

**Comment by kiran8966** [comment]
you do not need to reinstall, just click on search bar of window and find IDLE(python<version>
and create a new file  and past the whole code on it and then run it.
