### ISSUE TITLE
install thrid-party package error 

### ISSUE THREAD

**Issue by dzhwinter** [ContinuumIO/anaconda-issues#620]
I'm installing the package of "see", a third party non-conda package has nothing to do with anaconda.
conda can't find the package, but pip does. 

I have tried the doc said method with pip, then I get this response
```
~/anaconda $ pip install see
Collecting see
  Downloading see-1.1.1.tar.gz
Building wheels for collected packages: see
  Running setup.py bdist_wheel for see
  Stored in directory: /Users/dzh/Library/Caches/pip/wheels/73/fd/6e/c31703cd39f88ba852bd22f1e6502383e85e4f0941dbb71b52
Successfully built see
Installing collected packages: see
Exception:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/pip/basecommand.py", line 211, in main
    status = self.run(options, args)
  File "/usr/local/lib/python2.7/site-packages/pip/commands/install.py", line 311, in run
    root=options.root_path,
  File "/usr/local/lib/python2.7/site-packages/pip/req/req_set.py", line 646, in install
    **kwargs
  File "/usr/local/lib/python2.7/site-packages/pip/req/req_install.py", line 803, in install
    self.move_wheel_files(self.source_dir, root=root)
  File "/usr/local/lib/python2.7/site-packages/pip/req/req_install.py", line 998, in move_wheel_files
    isolated=self.isolated,
  File "/usr/local/lib/python2.7/site-packages/pip/wheel.py", line 339, in move_wheel_files
    clobber(source, lib_dir, True)
  File "/usr/local/lib/python2.7/site-packages/pip/wheel.py", line 317, in clobber
    shutil.copyfile(srcfile, destfile)
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 83, in copyfile
    with open(dst, 'wb') as fdst:
IOError: [Errno 13] Permission denied: '/lib/python2.7/site-packages/see.py'
~/anaconda $ 
```
I  also have tried build the package locally, but still failed. 
http://stackoverflow.com/questions/18640305/how-to-keep-track-of-pip-installed-packages-in-an-anaconda-conda-env
```
~/anaconda $ conda pipbuild see
Package search: {'_pypi_ordering': False, 'version': '1.1.1', 'name': 'see', 'summary': 'A human-readable alternative to dir'}
Creating standard recipe for see-1.1.1
An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda-build/issues

Include the output of the command 'conda info' in your report.


Traceback (most recent call last):
  File "/Users/dzh/anaconda/bin/conda-pipbuild", line 5, in <module>
    sys.exit(main())
  File "/Users/dzh/anaconda/lib/python2.7/site-packages/conda_build/main_pipbuild.py", line 81, in main
    args_func(args, p)
  File "/Users/dzh/anaconda/lib/python2.7/site-packages/conda_build/main_build.py", line 468, in args_func
    args.func(args, p)
  File "/Users/dzh/anaconda/lib/python2.7/site-packages/conda_build/main_pipbuild.py", line 369, in execute
    build_package(package, version, noarch_python=args.noarch_python)
  File "/Users/dzh/anaconda/lib/python2.7/site-packages/conda_build/main_pipbuild.py", line 302, in build_package
    directory = build_recipe(package, version=version)
  File "/Users/dzh/anaconda/lib/python2.7/site-packages/conda_build/main_pipbuild.py", line 147, in build_recipe
    output = result.strip().splitlines()
AttributeError: 'tuple' object has no attribute 'strip'

```

as others suggest that, pip 
anaconda can't find the package
```
system info:

             platform : osx-64
        conda version : 3.19.0
  conda-build version : 1.18.2
       python version : 2.7.11.final.0
     requests version : 2.9.0
     root environment : /Users/dzh/anaconda  (writable)
  default environment : /Users/dzh/anaconda
     envs directories : /Users/dzh/anaconda/envs
        package cache : /Users/dzh/anaconda/pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/osx-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/osx-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : None
    is foreign system : False
```

**Comment by dzhwinter** [comment]
look at the first paragraph, there is an error suggest that the conda try to install package to "/lib/python/", and get an permission error.  Why pip will go  there?

My system is OSX EI Caption. Both installed pip globally and inner conda env. Any suggestions?
