### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by babybear1992** [ContinuumIO/anaconda-issues#6233]
## Main error
Application <b>jupyterlab</b> launch may have produced errors.
## Traceback
```
[W 11:04:20.772 LabApp] Error loading server extension jupyter_nbextensions_configurator
    Traceback (most recent call last):
      File "/Users/yixiong/anaconda/lib/python3.6/site-packages/notebook/notebookapp.py", line 1271, in init_server_extensions
        mod = importlib.import_module(modulename)
      File "/Users/yixiong/anaconda/lib/python3.6/importlib/__init__.py", line 126, in import_module
        return _bootstrap._gcd_import(name[level:], package, level)
      File "<frozen importlib._bootstrap>", line 978, in _gcd_import
      File "<frozen importlib._bootstrap>", line 961, in _find_and_load
      File "<frozen importlib._bootstrap>", line 948, in _find_and_load_unlocked
    ModuleNotFoundError: No module named 'jupyter_nbextensions_configurator'
[I 11:04:20.776 LabApp] JupyterLab alpha preview extension loaded from /Users/yixiong/anaconda/lib/python3.6/site-packages/jupyterlab
JupyterLab v0.27.0
Known labextensions:
[I 11:04:20.779 LabApp] Running the core application with no additional extensions or settings
[W 11:04:20.780 LabApp] JupyterLab server extension not enabled, manually loading...
[I 11:04:20.781 LabApp] JupyterLab alpha preview extension loaded from /Users/yixiong/anaconda/lib/python3.6/site-packages/jupyterlab
JupyterLab v0.27.0
Known labextensions:
[I 11:04:20.782 LabApp] Running the core application with no additional extensions or settings
[I 11:04:20.789 LabApp] Serving notebooks from local directory: /Users/yixiong
[I 11:04:20.789 LabApp] 0 active kernels 
[I 11:04:20.789 LabApp] The Jupyter Notebook is running at: http://localhost:8888/?token=af0ff123285f867af8cca42a64a77f2ef8cd6401c86962b5
[I 11:04:20.789 LabApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 11:04:20.790 LabApp] 
    
    Copy/paste this URL into your browser when you connect for the first time,
    to login with a token:
        http://localhost:8888/?token=af0ff123285f867af8cca42a64a77f2ef8cd6401c86962b5
[I 11:04:21.071 LabApp] Accepting one-time-token-authenticated connection from ::1

```
## System information
```
python: 3.6.1
language: en
os: Darwin;16.7.0;Darwin Kernel Version 16.7.0: Thu Jun 15 17:36:27 PDT 2017; root:xnu-3789.70.16~2/RELEASE_X86_64;x86_64;i386
version: 1.6.2
platform: osx-64
qt: 5.6.2
pyqt: 5.6.0
conda: 4.3.21
```

**Comment by goanpeca** [comment]
@bollwyvl thoughts?
