### ISSUE TITLE
Issue with Anaconda Launcher

### ISSUE THREAD

**Issue by dantonino** [ContinuumIO/anaconda-issues#625]
I have installed launcher I just try to open Anaconda Launcher 2.0.0rc1 as bellow:

```
  conda install -c https://conda.anaconda.org/goanpeca/channel/dev launcher=2.0.0rc1
```

I am getting this issue when I try to open python Notebook.

Thanks for your help!
## Uncaught Exception

```
Error: spawn conda ENOENT
    at exports._errnoException (util.js:734:11)
    at Process.ChildProcess._handle.onexit (child_process.js:1022:32)
    at child_process.js:1115:20
    at process._tickCallback (node.js:375:11)
```
## Platform Information
- Operating System: darwin
- Conda Version: 3.19.0
- Conda Platform: osx-64

``` json
{
  "channels": [
    "https://repo.continuum.io/pkgs/free/osx-64/",
    "https://repo.continuum.io/pkgs/free/noarch/",
    "https://repo.continuum.io/pkgs/pro/osx-64/",
    "https://repo.continuum.io/pkgs/pro/noarch/"
  ],
  "conda_build_version": "1.14.1",
  "conda_version": "3.19.0",
  "default_prefix": "/Users/diego/anaconda",
  "envs": [],
  "envs_dirs": [
    "/Users/diego/anaconda/envs"
  ],
  "is_foreign": false,
  "pkgs_dirs": [
    "/Users/diego/anaconda/pkgs"
  ],
  "platform": "osx-64",
  "python_version": "2.7.11.final.0",
  "rc_path": null,
  "requests_version": "2.9.1",
  "root_prefix": "/Users/diego/anaconda",
  "root_writable": true,
  "sys_rc_path": "/Users/diego/anaconda/.condarc",
  "user_rc_path": "/Users/diego/.condarc",
  "condaBuildVersion": "1.14.1",
  "condaVersion": "3.19.0",
  "defaultPrefix": "/Users/diego/anaconda",
  "envsDirs": [
    "/Users/diego/anaconda/envs"
  ],
  "isForeign": false,
  "pkgsDirs": [
    "/Users/diego/anaconda/pkgs"
  ],
  "pythonVersion": "2.7.11.final.0",
  "rcPath": null,
  "requestsVersion": "2.9.1",
  "rootPrefix": "/Users/diego/anaconda",
  "rootWritable": true,
  "sysRcPath": "/Users/diego/anaconda/.condarc",
  "userRcPath": "/Users/diego/.condarc"
}
```

**Comment by goanpeca** [comment]
Launcher is deprecated and has been replaced by Anaconda Navigator. To learn more about it please check the [documentation](https://docs.continuum.io/anaconda/navigator/)

To install please open the Anaconda Prompt/Terminal and type

```
$ conda install anaconda-navigator
```
