### ISSUE TITLE
GDAL import fails

### ISSUE THREAD

**Issue by odhondt** [ContinuumIO/anaconda-issues#630]
`import gdal` returns error:

`ImportError: libhdf5_hl.so.9: cannot open shared object file: No such file or directory`

on Anaconda 2.4.1 (64-bit). My system is Ubuntu 14.04.

**Comment by starsk62** [comment]
i am having the same problem >>> import gdal
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/starsk/anaconda/envs/DV/lib/python2.7/site-packages/gdal.py", line 2, in <module>
    from osgeo.gdal import deprecation_warn
  File "/Users/starsk/anaconda/envs/DV/lib/python2.7/site-packages/osgeo/__init__.py", line 21, in <module>
    _gdal = swig_import_helper()
  File "/Users/starsk/anaconda/envs/DV/lib/python2.7/site-packages/osgeo/__init__.py", line 17, in swig_import_helper
    _mod = imp.load_module('_gdal', fp, pathname, description)
ImportError: dlopen(/Users/starsk/anaconda/envs/DV/lib/python2.7/site-packages/osgeo/_gdal.so, 2): Library not loaded: @rpath/./libhdf5_hl.9.dylib
  Referenced from: /Users/starsk/anaconda/envs/DV/lib/libnetcdf.7.dylib
  Reason: image not found
>>>

**Comment by flamingbear** [comment]
I was looking at the package page and it looks like gdal and libgdal were removed from anaconda in the latest version.  But it's not mentioned in the changelog, so maybe it's a mistake?

**Comment by sshuair** [comment]
I got the same problem
