### ISSUE TITLE
Error Fetching Packages 

### ISSUE THREAD

**Issue by bpdatamining** [ContinuumIO/anaconda-issues#631]
Hi , 

Currently, (after I ran an API SDK based script which probabably didn't have a close() statement) I am unable to start a Anaconda as Launcher throws following Errors:

Error fetching package index
'WrappedSocket' object has no attribute 'close'

Traceback (most recent call last):
  File "C:\Python27\Scripts\conda-script.py", line 4, in <module>
    sys.exit(main())
  File "C:\Python27\lib\site-packages\conda\cli\main.py", line 195, in main
    args_func(args, p)
  File "C:\Python27\lib\site-packages\conda\cli\main.py", line 202, in args_func
    args.func(args, p)
  File "C:\Python27\lib\site-packages\conda\cli\main_install.py", line 45, in execute
    install.install(args, parser, 'install')
  File "C:\Python27\lib\site-packages\conda\cli\install.py", line 239, in install
    offline=args.offline)
  File "C:\Python27\lib\site-packages\conda\cli\common.py", line 597, in get_index_trap
    return get_index(*args, **kwargs)
  File "C:\Python27\lib\site-packages\conda\api.py", line 42, in get_index
    unknown=unknown)
  File "C:\Python27\lib\site-packages\conda\utils.py", line 118, in __call__
    value = self.func(*args, **kw)
  File "C:\Python27\lib\site-packages\conda\fetch.py", line 259, in fetch_index
    repodatas.append((url, future.result()))
  File "C:\Python27\lib\site-packages\concurrent\futures\_base.py", line 407, in result
    return self.__get_result()
  File "C:\Python27\lib\site-packages\concurrent\futures\_base.py", line 359, in __get_result
    reraise(self._exception, self._traceback)
  File "C:\Python27\lib\site-packages\concurrent\futures\_compat.py", line 107, in reraise
    exec('raise exc_type, exc_value, traceback', {}, locals_)
  File "C:\Python27\lib\site-packages\concurrent\futures\thread.py", line 61, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Python27\lib\site-packages\conda\fetch.py", line 65, in func
    res = f(*args, **kwargs)
  File "C:\Python27\lib\site-packages\conda\fetch.py", line 100, in fetch_repodata
    headers=headers, proxies=session.proxies)
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 347, in get
    return self.request('GET', url, **kwargs)
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 335, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 438, in send
    r = adapter.send(request, **kwargs)
  File "C:\Python27\lib\site-packages\requests\adapters.py", line 292, in send
    timeout=timeout
  File "C:\Python27\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 423, in urlopen
    conn = self._get_conn(timeout=pool_timeout)
  File "C:\Python27\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 224, in _get_conn
    raise ClosedPoolError(self, "Pool is closed.")
requests.packages.urllib3.exceptions.ClosedPoolError: HTTPSConnectionPool(host='repo.continuum.io', port=443): Pool is closed.

'conda info'
Current conda install:

             platform : win-32
        conda version : 3.19.0
  conda-build version : not installed
       python version : 2.7.6.final.0
     requests version : 1.2.3
     root environment : C:\Python27  (writable)
  default environment : C:\Python27
     envs directories : C:\Python27\envs
        package cache : C:\Python27\pkgs
         channel URLs : https://conda.binstar.org/sloria/win-32/
                        https://conda.binstar.org/sloria/noarch/
                        https://repo.continuum.io/pkgs/free/win-32/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/win-32/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : C:\Users\...........\.condarc
    is foreign system : True

Update or reinstall for conda/anaconda is not working. 

Please, advise. 

Many Thanks
Bhoomin Pandya

PS:
Just for your information, I had incorporated Anaconda on ELB services with AWS which is not accessible also.

**Comment by bpdatamining** [comment]
Hi, 
After editing the .condarc file and removing the repo.continuum.io channels - removed the close or timeout problem. I am still checking it things would work well and conda and anaconda packages can be updated. 
I shall revert to you if I face problem. 
Thanks, 
Bhoomin Pandya

**Comment by bpdatamining** [comment]
Hi, 

Please close this problem as I have solved it as this was a problem of the Certificate from 
https:\\repo. continuum.io which was connected to the ELB services which expired. I had to delete the expired license. _license-1.1-py27_1.tar.bz2

I am now able to launch the instance. 

Best Regards, 
Bhoomin Pandya

**Comment by msarahan** [comment]
Thanks for posting the solution.

**Comment by bpdatamining** [comment]
Hi Mike, 

After I tried to create a scipy virualenv outside anaconda (or installing scikit learn and some packages) the error comes back again. 

My.condarc is now following as I removed the repo.continuum.io URIs :
binstar_uploads: false
channels:
- https://conda.binstar.org/numba
- defaults

Since the EC2 ELB instance was in the c:\python27 directory I have restored back the python folder to available restoration which also turns out to be the one with error. 

I reinstalled Anaconda in default directory C:\Users\<user name>\anaconda2
but this is also showing the error. 

Restoring c:\python27 does not solve the error as the stored folder has the same error.

I tried to download new certificate it doesn't work. From console the repo.continuum.io shows <Response [200]>

I am sorry to open the issue again after once it was solved. Please, advise. 

Many Thanks
Best Regards, 
Bhoomin Pandya
