### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by Vishnu1024** [ContinuumIO/anaconda-issues#6327]
## Main error
Application <b>spyder</b> launch may have produced errors.
## Traceback
```
Traceback (most recent call last):
  File "C:\Users\bbnsu_000\Anaconda2\Scripts\spyder-script.py", line 5, in <module>
    sys.exit(spyder.app.start.main())
  File "C:\Users\bbnsu_000\Anaconda2\lib\site-packages\spyder\app\start.py", line 103, in main
    from spyder.app import mainwindow
  File "C:\Users\bbnsu_000\Anaconda2\lib\site-packages\spyder\app\mainwindow.py", line 95, in <module>
    from qtawesome.iconic_font import FontError
  File "C:\Users\bbnsu_000\Anaconda2\lib\site-packages\qtawesome\__init__.py", line 19, in <module>
    from .iconic_font import IconicFont, set_global_defaults
  File "C:\Users\bbnsu_000\Anaconda2\lib\site-packages\qtawesome\iconic_font.py", line 28, in <module>
    from six import unichr
ImportError: cannot import name unichr

```
## System information
```
platform: win-64
version: 1.6.2
conda: 4.3.21
qt: 5.6.2
language: en_US
python: 2.7.13
os: Windows;10;10.0.15063;AMD64;Intel64 Family 6 Model 69 Stepping 1, GenuineIntel
pyqt: 5.6.0
```

**Comment by goanpeca** [comment]
@ccordoba12 do you know about this?
