### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by chaudharygaurav07** [ContinuumIO/anaconda-issues#6333]
## Main error
Application <b>notebook</b> launch may have produced errors.
## Traceback
```
Traceback (most recent call last):
  File "C:\Program Files\Anaconda3\lib\site-packages\traitlets\traitlets.py", line 528, in get
    value = obj._trait_values[self.name]
KeyError: 'runtime_dir'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Anaconda3\Scripts\jupyter-notebook-script.py", line 5, in <module>
    sys.exit(notebook.notebookapp.main())
  File "C:\Program Files\Anaconda3\lib\site-packages\jupyter_core\application.py", line 267, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "C:\Program Files\Anaconda3\lib\site-packages\traitlets\config\application.py", line 657, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-7>", line 2, in initialize
  File "C:\Program Files\Anaconda3\lib\site-packages\traitlets\config\application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "C:\Program Files\Anaconda3\lib\site-packages\notebook\notebookapp.py", line 1294, in initialize
    self.init_configurables()
  File "C:\Program Files\Anaconda3\lib\site-packages\notebook\notebookapp.py", line 1033, in init_configurables
    connection_dir=self.runtime_dir,
  File "C:\Program Files\Anaconda3\lib\site-packages\traitlets\traitlets.py", line 556, in __get__
    return self.get(obj, cls)
  File "C:\Program Files\Anaconda3\lib\site-packages\traitlets\traitlets.py", line 535, in get
    value = self._validat

**Comment by goanpeca** [comment]
@chaudharygaurav07 I would advice for you to reinstall for the current user and not for all users.
