### ISSUE TITLE
MKL corruption, possibly due to fresh Anaconda3 v5.0.0 install

### ISSUE THREAD

**Issue by ijstokes** [ContinuumIO/anaconda-issues#6378]
I can no longer import `numpy` from most of my environments (but oddly: not from all of them).  I get errors along the following lines:

```
$ python
Python 3.6.1 | packaged by conda-forge | (default, May 11 2017, 18:00:28) 
[GCC 4.2.1 Compatible Apple LLVM 6.1.0 (clang-602.0.53)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy
Traceback (most recent call last):
  File "/Users/ijstokes/anaconda/envs/webex/lib/python3.6/site-packages/numpy/core/__init__.py", line 16, in <module>
    from . import multiarray
ImportError: dlopen(/Users/ijstokes/anaconda/envs/webex/lib/python3.6/site-packages/numpy/core/multiarray.cpython-36m-darwin.so, 10): Library not loaded: @rpath/libmkl_intel_lp64.dylib
  Referenced from: /Users/ijstokes/anaconda/envs/webex/lib/python3.6/site-packages/numpy/core/multiarray.cpython-36m-darwin.so
  Reason: no suitable image found.  Did find:
	/Users/ijstokes/anaconda/envs/webex/lib/python3.6/site-packages/numpy/core/../../../../libmkl_intel_lp64.dylib: file too short
	/Users/ijstokes/anaconda/envs/webex/lib/libmkl_intel_lp64.dylib: file too short
	/Users/ijstokes/anaconda/envs/webex/lib/libmkl_intel_lp64.dylib: file too short
	/Users/ijstokes/anaconda/envs/webex/lib/libmkl_intel_lp64.dylib: file too short
	/Users/ijstokes/anaconda/envs/webex/lib/libmkl_intel_lp64.dylib: file too short
	/Users/ijstokes/anaconda/envs/webex/lib/libmkl_intel_lp64.dylib: file too short
	/Users/ijstokes/anaconda/envs/webex/bin/../lib/libmkl_intel_lp64.dylib: file too short

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/ijstokes/anaconda/envs/webex/lib/python3.6/site-packages/numpy/__init__.py", line 146, in <module>
    from . import add_newdocs
  File "/Users/ijstokes/anaconda/envs/webex/lib/python3.6/site-packages/numpy/add_newdocs.py", line 13, in <module>
    from numpy.lib import add_newdoc
  File "/Users/ijstokes/anaconda/envs/webex/lib/python3.6/site-packages/numpy/lib/__init__.py", line 8, in <module>
    from .type_check import *
  File "/Users/ijstokes/anaconda/envs/webex/lib/python3.6/site-packages/numpy/lib/type_check.py", line 11, in <module>
    import numpy.core.numeric as _nx
  File "/Users/ijstokes/anaconda/envs/webex/lib/python3.6/site-packages/numpy/core/__init__.py", line 24, in <module>
    raise ImportError(msg)
ImportError: 
Importing the multiarray numpy extension module failed.  Most
likely you are trying to import a failed build of numpy.
If you're working with a numpy git repo, try `git clean -xdf` (removes all
files not under version control).  Otherwise reinstall numpy.
```

Here is the output of `conda list -e`:

[broken_numpy_env.txt](https://github.com/ContinuumIO/anaconda-issues/files/1354504/broken_numpy_env.txt)

The only thing that I can think of that I've done since yesterday (when this was working) was to install Anaconda3 v5.0.0 to a new directory.

**Comment by ijstokes** [comment]
Looking into this more, I discovered that my `~/anaconda/pkgs/mkl-2017.0.1-0` directory had been largely cleared out: only a few files remained inside the `info` directory.  What might cause this?  That is weird behavior.  I seem to have been able to rectify the situation by doing:

```
pushd ~/anaconda/pkgs/mkl-2017.0.1-0
tar jxvf ../mkl-2017.0.1-0.tar.bz2
conda install --force mkl
```

**Comment by ijstokes** [comment]
What I don't understand is how, with file linking, these files were deleted from multiple conda environments (I'm having to go through and do the `conda install --force mkl` step in multiple envs to get them working again).  IIUC deleting the files in the package cache would not impact conda envs that used those files as they would still retain hard links to MKL.

The only thing I can think of is if anti-virus software identified MKL as a threat and systematically deleted the files everywhere they occurred.  But AMP Endpoint Connector is the only AV software I know of that I have running (managed by our IT team), and I can't see any evidence in the logs that it has quarantined any files.

**Comment by csoja** [comment]
@ijstokes based on the output when you ran python - it looks like the python you are running is coming from conda-forge and not Anaconda 5.0.
Anaconda 5.0 Python will say "Anaconda, Inc." instead of "packaged by conda-forge"
conda-forge doesn't build with mkl - so I expect if you are forcing the mkl flag, you are then replacing the conda-forge builds with Anaconda ones.  
I cannot imagine how you got in such a state just by installing Anaconda 5.0.

**Comment by ijstokes** [comment]
@csoja I see what you mean!  I wonder how that happened as well.  But it doesn't explain how the files in the package cache disappeared, which seemed to be the main cause of the problem.  I'm now wondering if it could have been file corruption.  If that was the case it was strangely selective.  But that might explain how it was that the files disappeared from many conda envs at once.

I'll try to figure out how to get the Anaconda Python back...
