### ISSUE TITLE
Can't open Jupyter Qt Console from terminal on Windows

### ISSUE THREAD

**Issue by petebachant** [ContinuumIO/anaconda-issues#6456]
Trying to open the Jupyter Qt Console from Git Bash or the Windows Command Prompt (I installed Anaconda in such a way that it would be on the path) gives:

```
$ jupyter qtconsole
This application failed to start because it could not find or load the Qt platform plugin "windows"
in "".

Available platform plugins are: minimal, offscreen, windows.

Reinstalling the application may fix this problem.
```

It can be launched from the Anaconda Navigator or command prompt, however.

My environment was just updated today, but I can't export it from Anaconda command prompt. I assume this is a different issue:

```
$ conda env export -n root
Traceback (most recent call last):
  File "C:\Users\pbachant\AppData\Local\Continuum\Anaconda3\Scripts\pip-script.py", line 6, in <module>
    from pip import main
  File "C:\Users\pbachant\AppData\Local\Continuum\Anaconda3\lib\site-packages\pip\__init__.py", line 28, in <module>
    from pip.vcs import git, mercurial, subversion, bazaar  # noqa
  File "C:\Users\pbachant\AppData\Local\Continuum\Anaconda3\lib\site-packages\pip\vcs\mercurial.py", line 9, in <module>
    from pip.download import path_to_url
  File "C:\Users\pbachant\AppData\Local\Continuum\Anaconda3\lib\site-packages\pip\download.py", line 41, in <module>
    from pip._vendor.requests.adapters import BaseAdapter, HTTPAdapter
ModuleNotFoundError: No module named 'pip._vendor.requests.adapters'
An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues



Current conda install:

               platform : win-64
          conda version : 4.3.27
       conda is private : False
      conda-env version : 4.3.27
    conda-build version : not installed
         python version : 3.6.2.final.0
       requests version : 2.18.4
       root environment : C:\Users\pbachant\AppData\Local\Continuum\Anaconda3  (writable)
    default environment : C:\Users\pbachant\AppData\Local\Continuum\Anaconda3
       envs directories : C:\Users\pbachant\AppData\Local\Continuum\Anaconda3\envs
                          C:\Users\pbachant\AppData\Local\conda\conda\envs
                          C:\Users\pbachant\.conda\envs
          package cache : C:\Users\pbachant\AppData\Local\Continuum\Anaconda3\pkgs
                          C:\Users\pbachant\AppData\Local\conda\conda\pkgs
           channel URLs : https://repo.continuum.io/pkgs/main/win-64
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/win-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
            config file : C:\Users\pbachant\.condarc
             netrc file : C:\Users\pbachant/.netrc
           offline mode : False
             user-agent : conda/4.3.27 requests/2.18.4 CPython/3.6.2 Windows/7 Windows/6.1.7601
          administrator : False

`$ C:\Users\pbachant\AppData\Local\Continuum\Anaconda3\Scripts\conda-env export -n root`




    Traceback (most recent call last):
      File "C:\Users\pbachant\AppData\Local\Continuum\Anaconda3\lib\site-packages\conda\exceptions.py", line 640, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "C:\Users\pbachant\AppData\Local\Continuum\Anaconda3\lib\site-packages\conda_env\cli\main_export.py", line 90, in execute
        ignore_channels=args.ignore_channels)
      File "C:\Users\pbachant\AppData\Local\Continuum\Anaconda3\lib\site-packages\conda_env\env.py", line 46, in from_environment
        add_pip_installed(prefix, installed, json=True)
      File "C:\Users\pbachant\AppData\Local\Continuum\Anaconda3\lib\site-packages\conda_env\pip_util.py", line 114, in add_pip_installed
        for pip_pkg in installed(prefix, output=output):
      File "C:\Users\pbachant\AppData\Local\Continuum\Anaconda3\lib\site-packages\conda_env\pip_util.py", line 53, in installed
        args = pip_args(prefix)
      File "C:\Users\pbachant\AppData\Local\Continuum\Anaconda3\lib\site-packages\conda_env\pip_util.py", line 32, in pip_args
        pip_version = subprocess.check_output(ret + ['-V']).decode('utf-8').split()[1]
      File "C:\Users\pbachant\AppData\Local\Continuum\Anaconda3\lib\subprocess.py", line 336, in check_output
        **kwargs).stdout
      File "C:\Users\pbachant\AppData\Local\Continuum\Anaconda3\lib\subprocess.py", line 418, in run
        output=stdout, stderr=stderr)
    subprocess.CalledProcessError: Command '['C:\\Users\\pbachant\\AppData\\Local\\Continuum\\Anaconda3\\python.exe', 'C:\\Users\\pbachant\\AppData\\Local\\Continuum\\Anaconda3\\Scripts\\pip-script.py', '-V']' returned non-zero exit status 1.
```

**Comment by msarahan** [comment]
The pip vendoring thing is a known issue.  There seems to have been an old corrupt pip package that didn't list all of its files.  When you update pip, some files remain.  That's a problem because we've removed those files and un-vendored pip, out of concern for path length issues that we saw during testing.

You may be able to fix it by manually deleting the C:\Users\pbachant\AppData\Local\Continuum\Anaconda3\lib\site-packages\pip\_vendor\requests folder - that's been what I've seen to be the files that shouldn't be there.

**Comment by petebachant** [comment]
Tried that, and tried a fresh install. No luck :disappointed:

**Comment by mingwandroid** [comment]
> I installed Anaconda in such a way that it would be on the path

Can you show the value of `PATH` here? There are 5 entries needed on `PATH` for a properly activated conda env and they must be added in the right order for `deactivate` to work correctly.

Given that:

> It can be launched from the Anaconda Navigator or command prompt

I suspect this has not been done 'correctly'.

Conda 4.3.27 also gained a fix so that you can use the activate shell script on MSYS2 (upon which Git for Windows is derived).

I encourage you to give up trying to fake activation by manually setting `PATH` and to instead call either the activate shell script from ~/.bash_profile if you want to use bash or by running the Anaconda Prompt if you want to use cmd.exe.

**Comment by petebachant** [comment]
When I say Anaconda is on the path, I mean I ticked the box in the installer to add Anaconda to the path. I don't do any manual path manipulation for installation, activation of envs, etc. 

Here is my `PATH` (separated into new lines):

```
/c/Users/pbachant/bin:
/mingw64/bin:
/usr/local/bin:
/usr/bin:/bin:
/mingw64/bin:
/usr/bin:
/c/Users/pbachant/bin:
/c/Program Files (x86)/Intel/iCLS Client:
/c/Program Files/Intel/iCLS Client:
/c/windows/system32:
/c/windows:
/c/windows/System32/Wbem:
/c/windows/System32/WindowsPowerShell/v1.0:
/c/Program Files (x86)/Intel/UCRT:
/c/Program Files/Intel/UCRT:
/c/Program Files (x86)/Intel/Intel(R) Management Engine Components/DAL:
/c/Program Files/Intel/Intel(R) Management Engine Components/DAL:
/c/Program Files (x86)/Intel/Intel(R) Management Engine Components/IPT:
/c/Program Files/Intel/Intel(R) Management Engine Components/IPT:
/c/Program Files/Lenovo/Touch Fingerprint Software:
/c/Program Files (x86)/Common Files/Lenovo:
/c/ProgramData/Lenovo/ReadyApps:
/c/ProgramData/chocolatey/bin:
/c/Program Files/MATLAB/R2017a/bin:
/c/Program Files (x86)/Skype/Phone:
/c/Program Files (x86)/Lenovo/Password Manager:
/c/Program Files (x86)/Lenovo/Access Connections:
/c/Program Files/Intel/WiFi/bin:
/c/Program Files/Common Files/Intel/WirelessCommon:
/c/Program Files (x86)/Windows Kits/8.1/Windows Performance Toolkit:
/cmd:
/c/Program Files/MiKTeX 2.9/miktex/bin/x64:
/c/Users/pbachant/AppData/Local/Continuum/anaconda3:
/c/Users/pbachant/AppData/Local/Continuum/anaconda3/Library/mingw-w64/bin:
/c/Users/pbachant/AppData/Local/Continuum/anaconda3/Library/usr/bin:
/c/Users/pbachant/AppData/Local/Continuum/anaconda3/Library/bin:
/c/Users/pbachant/AppData/Local/Continuum/anaconda3/Scripts:
/c/Users/pbachant/AppData/Local/atom/bin:
/c/tools/mysql/current/bin:
/c/Program Files/Intel/WiFi/bin:
/c/Program Files/Common Files/Intel/WirelessCommon:
/c/Program Files/Oracle/VirtualBox:
/c/tools/mingw64/bin:
/c/Program Files/Microsoft VS Code/bin:
/usr/bin/vendor_perl:
/usr/bin/core_perl
```

**Comment by petebachant** [comment]
If I prepend all the Anaconda entries to `PATH`, I am able to launch Jupyter Qt Console properly.

**Comment by mingwandroid** [comment]
Yeah, the problem with `PATH` on Windows are many and pretty much insurmountable.

Windows has 'system' paths and 'user' paths and the 'system' ones come first. If *any* DLL is located in *any* of those folders that Anaconda software needs to load, then those DLLs get loaded instead. There's just nothing we can do about this which is why the installer now strongly suggests you do not do that.

DLL hell on Windows is a really big problem still and my advice is to never allow any software to muck with your PATH when you have the choice, and this includes our software!

**Comment by mingwandroid** [comment]
As you are a Bash-on-Windows user, I recommend you remove our entries from the PATH env. var, then add this to your `~/.bash_profile`:

`. /c/Users/pbachant/AppData/Local/Continuum/anaconda3/Scripts/activate`

**Comment by petebachant** [comment]
Ah, yes that does work, and seems like a more robust solution. I'll close this issue. Thanks so much!

**Comment by mingwandroid** [comment]
No problem!
