### ISSUE TITLE
JLab Error

### ISSUE THREAD

**Issue by AlexandreLenoir** [ContinuumIO/anaconda-issues#6463]
## Main error
Application <b>notebook</b> launch may have produced errors.
## Traceback
```
[W 23:19:18.542 NotebookApp] Error loading server extension jupyter_nbextensions_configurator
    Traceback (most recent call last):
      File "/home/alex/anaconda3/envs/Python35/lib/python3.5/site-packages/notebook/notebookapp.py", line 1271, in init_server_extensions
        mod = importlib.import_module(modulename)
      File "/home/alex/anaconda3/envs/Python35/lib/python3.5/importlib/__init__.py", line 126, in import_module
        return _bootstrap._gcd_import(name[level:], package, level)
      File "<frozen importlib._bootstrap>", line 985, in _gcd_import
      File "<frozen importlib._bootstrap>", line 968, in _find_and_load
      File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
    ImportError: No module named 'jupyter_nbextensions_configurator'
[I 23:19:18.545 NotebookApp] Serving notebooks from local directory: /home/alex
[I 23:19:18.545 NotebookApp] 0 active kernels 
[I 23:19:18.545 NotebookApp] The Jupyter Notebook is running at: http://localhost:8888/?token=bdb2428ef3c41445ddbc368a206951a4d3e5e15fed94ed4f
[I 23:19:18.545 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 23:19:18.545 NotebookApp] 
    
    Copy/paste this URL into your browser when you connect for the first time,
    to login with a token:
        http://localhost:8888/?token=bdb2428ef3c41445ddbc368a206951a4d3e5e15fed94ed4f
[I 23:19:18.648 NotebookApp] Accepting one-time-token-authenticated connection from 127.0.0.1
[W 23:19:19.111 NotebookApp] 404 GET /nbextensions/nbextensions_configurator/tree_tab/main.js?v=20171006231918 (127.0.0.1) 5.27ms referer=http://localhost:8888/tree

```
## System information
```
python: 3.6.1
language: en_US
os: Linux;4.4.0-96-generic-tuxonice;#119~ppa3-Ubuntu SMP Mon Sep 25 18:04:53 UTC 2017;x86_64;x86_64
version: 1.6.2
platform: linux-64
qt: 5.6.2
pyqt: 5.6.0
conda: 4.3.21
```

**Comment by AlexandreLenoir** [comment]
Here is more information about this issue. I am failing in running this command : 
conda install -c conda-forge jupyter_contrib_nbextensions
 this gives the following error : jupyter_contrib_nbextensions.install.NotebookRunningError: Cannot configure while the Jupyter notebook server is running
However, when checking process list (I run Ubuntu 17.04), I cannot find any instance of jupyter running.
The problem reported occurs when I launch jupyter after this unsuccessful installation attempt. I guess that the installation is just half way.

**Comment by csoja** [comment]
This is probably a better issue for the JupyterLab repo: https://github.com/jupyterlab/jupyterlab/issues or the conda-forge feedstock:  https://github.com/conda-forge/jupyter_contrib_nbextensions-feedstock  I am going to close it here.
