### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by arcayi** [ContinuumIO/anaconda-issues#6472]
## Main error
Application <b>orange3</b> launch may have produced errors.
## Traceback
```
Traceback (most recent call last):
  File "/anaconda/bin/orange-canvas", line 4, in <module>
    import Orange.canvas.__main__
  File "/anaconda/lib/python3.6/site-packages/Orange/__init__.py", line 11, in <module>
    from .misc.lazy_module import _LazyModule
  File "/anaconda/lib/python3.6/site-packages/Orange/misc/__init__.py", line 3, in <module>
    from .distmatrix import DistMatrix
  File "/anaconda/lib/python3.6/site-packages/Orange/misc/distmatrix.py", line 3, in <module>
    from Orange.data import Table, StringVariable, Domain
  File "/anaconda/lib/python3.6/site-packages/Orange/data/__init__.py", line 4, in <module>
    from .variable import *
  File "/anaconda/lib/python3.6/site-packages/Orange/data/variable.py", line 12, in <module>
    from Orange.util import Registry, color_to_hex, hex_to_color, Reprable
  File "/anaconda/lib/python3.6/site-packages/Orange/util.py", line 17, in <module>
    from Orange.data.util import scale  # pylint: disable=unused-import
  File "/anaconda/lib/python3.6/site-packages/Orange/data/util.py", line 6, in <module>
    from scipy import sparse as sp
  File "/anaconda/lib/python3.6/site-packages/scipy/__init__.py", line 114, in <module>
    from scipy._lib._ccallback import LowLevelCallable
  File "/anaconda/lib/python3.6/site-packages/scipy/_lib/_ccallback.py", line 1, in <module>
    from . import _ccallback_c
  File "_ccallback_c.pyx", line 210, in init scipy._lib._ccallback_c
  File "/anaconda/lib/python3.6/ctypes/__init__.py", line 7, in <module>
    from _ctypes import Union, Structure, Array
ImportError: dlopen(/anaconda/lib/python3.6/lib-dynload/_ctypes.cpython-36m-darwin.so, 2): Symbol not found: __PyUnicode_AsWideCharString
  Referenced from: /anaconda/lib/python3.6/lib-dynload/_ctypes.cpython-36m-darwin.so
  Expected in: flat namespace
 in /anaconda/lib/python3.6/lib-dynload/_ctypes.cpython-36m-darwin.so

```
## System information
```
python: 3.6.1
language: en
os: Darwin;16.7.0;Darwin Kernel Version 16.7.0: Thu Jun 15 17:36:27 PDT 2017; root:xnu-3789.70.16~2/RELEASE_X86_64;x86_64;i386
version: 1.6.2
platform: osx-64
qt: 5.6.2
pyqt: 5.6.0
conda: 4.3.27
```

**Comment by arcayi** [comment]
The problem has been solved as following steps:
1, Downgrade python in Anaconda from 3.6.3 to 3.6.2. ( It is reported to be 3.6.1. There must be some mistakes during report the issue. )
2, re-launch the orange3

**Comment by goanpeca** [comment]
@mingwandroid is 3.6.3 static link build related to any of this?
