### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by fernandoruizanton** [ContinuumIO/anaconda-issues#6515]
## Main error
Application <b>spyder</b> launch may have produced errors.
## Traceback
```
Traceback (most recent call last):
  File "/anaconda/bin/spyder", line 6, in <module>
    sys.exit(spyder.app.start.main())
  File "/anaconda/lib/python3.6/site-packages/spyder/app/start.py", line 103, in main
    from spyder.app import mainwindow
  File "/anaconda/lib/python3.6/site-packages/spyder/app/mainwindow.py", line 165, in <module>
    from spyder.utils.environ import WinUserEnvDialog
  File "/anaconda/lib/python3.6/site-packages/spyder/utils/environ.py", line 20, in <module>
    from spyder.widgets.variableexplorer.collectionseditor import CollectionsEditor
  File "/anaconda/lib/python3.6/site-packages/spyder/widgets/variableexplorer/collectionseditor.py", line 48, in <module>
    from spyder.widgets.variableexplorer.utils import (
  File "/anaconda/lib/python3.6/site-packages/spyder/widgets/variableexplorer/utils.py", line 104, in <module>
    import bs4
  File "/anaconda/lib/python3.6/site-packages/bs4/__init__.py", line 35, in <module>
    from .builder import builder_registry, ParserRejectedMarkup
  File "/anaconda/lib/python3.6/site-packages/bs4/builder/__init__.py", line 329, in <module>
    from . import _lxml
  File "/anaconda/lib/python3.6/site-packages/bs4/builder/_lxml.py", line 11, in <module>
    from lxml import etree
  File "lxml.etree.pyx", line 48, in init lxml.etree (src/lxml/lxml.etree.c:159872)
ValueError: level must be >= 0

```
## System information
```
python: 3.6.1
language: en
os: Darwin;17.2.0;Darwin Kernel Version 17.2.0: Mon Sep 18 15:44:59 PDT 2017; root:xnu-4570.20.55~19/RELEASE_X86_64;x86_64;i386
version: 1.6.2
platform: osx-64
qt: 5.6.2
pyqt: 5.6.0
conda: 4.3.27
```

**Comment by goanpeca** [comment]
Have you seen this before @spyder-ide/core-developers
