### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by SooyeongHwang** [ContinuumIO/anaconda-issues#6533]
## Main error
Application <b>spyder</b> launch may have produced errors.
## Traceback
```
Traceback (most recent call last):
  File "/anaconda/bin/spyder", line 6, in <module>
    sys.exit(spyder.app.start.main())
  File "/anaconda/lib/python3.6/site-packages/spyder/app/start.py", line 103, in main
    from spyder.app import mainwindow
  File "/anaconda/lib/python3.6/site-packages/spyder/app/mainwindow.py", line 162, in <module>
    from spyder.utils.environ import WinUserEnvDialog
  File "/anaconda/lib/python3.6/site-packages/spyder/utils/environ.py", line 20, in <module>
    from spyder.widgets.variableexplorer.collectionseditor import CollectionsEditor
  File "/anaconda/lib/python3.6/site-packages/spyder/widgets/variableexplorer/collectionseditor.py", line 46, in <module>
    from spyder.widgets.variableexplorer.importwizard import ImportWizard
  File "/anaconda/lib/python3.6/site-packages/spyder/widgets/variableexplorer/importwizard.py", line 26, in <module>
    import pandas as pd
  File "/anaconda/lib/python3.6/site-packages/pandas/__init__.py", line 25, in <module>
    from pandas import hashtable, tslib, lib
  File "pandas/src/numpy.pxd", line 157, in init pandas.tslib (pandas/tslib.c:116121)
ValueError: numpy.dtype has the wrong size, try recompiling. Expected 88, got 96

```
## System information
```
python: 3.6.0
language: en
os: Darwin;16.6.0;Darwin Kernel Version 16.6.0: Fri Apr 14 16:21:16 PDT 2017; root:xnu-3789.60.24~6/RELEASE_X86_64;x86_64;i386
version: 1.6.2
platform: osx-64
qt: 5.6.2
pyqt: 5.6.0
conda: 4.3.21
```

**Comment by goanpeca** [comment]
@ccordoba12 thoughts?
