### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by assadullah1467** [ContinuumIO/anaconda-issues#6566]
## Main error
Application <b>notebook</b> launch may have produced errors.
## Traceback
```
Traceback (most recent call last):
  File "C:\Users\assad\Anaconda3\Scripts\jupyter-notebook-script.py", line 3, in <module>
    import notebook.notebookapp
  File "C:\Users\assad\Anaconda3\lib\site-packages\notebook\__init__.py", line 25, in <module>
    from .nbextensions import install_nbextension
  File "C:\Users\assad\Anaconda3\lib\site-packages\notebook\nbextensions.py", line 572, in <module>
    from .extensions import (
  File "C:\Users\assad\Anaconda3\lib\site-packages\notebook\extensions.py", line 8, in <module>
    from tornado.log import LogFormatter
  File "C:\Users\assad\Anaconda3\lib\site-packages\tornado\log.py", line 37, in <module>
    from tornado.escape import _unicode
  File "C:\Users\assad\Anaconda3\lib\site-packages\tornado\escape.py", line 28, in <module>
    from tornado.util import unicode_type, basestring_type, u
ImportError: cannot import name 'u'

```
## System information
```
python: 3.6.1
language: en_AU
os: Windows;10;10.0.15063;AMD64;Intel64 Family 6 Model 78 Stepping 3, GenuineIntel
version: 1.6.2
platform: win-64
qt: 5.6.2
pyqt: 5.6.0
conda: 4.3.29
```

**Comment by assadullah1467** [comment]
It is refusing to start

**Comment by goanpeca** [comment]
@assadullah1467 do you get the same error if you try opening the `Anaconda Prompt` and typing 

```
$ jupyter notebook
``` 

?

**Comment by siddrc** [comment]
Any solution on this ?
