### ISSUE TITLE
Ipython error in Windows Subsystem for Linux

### ISSUE THREAD

**Issue by albertotb** [ContinuumIO/anaconda-issues#6573]
This is related to issue #6424 . I have installed Anaconda3. Installing a new enviroment with Python 2.7 works fine until I try to start ipython:

```
ERROR:root:code for hash md5 was not found.
Traceback (most recent call last):
  File "/home/alberto/anaconda3/envs/py27/lib/python2.7/hashlib.py", line 147, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/home/alberto/anaconda3/envs/py27/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type md5
ERROR:root:code for hash sha1 was not found.
Traceback (most recent call last):
  File "/home/alberto/anaconda3/envs/py27/lib/python2.7/hashlib.py", line 147, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/home/alberto/anaconda3/envs/py27/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type sha1
ERROR:root:code for hash sha224 was not found.
Traceback (most recent call last):
  File "/home/alberto/anaconda3/envs/py27/lib/python2.7/hashlib.py", line 147, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/home/alberto/anaconda3/envs/py27/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type sha224
ERROR:root:code for hash sha256 was not found.
Traceback (most recent call last):
  File "/home/alberto/anaconda3/envs/py27/lib/python2.7/hashlib.py", line 147, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/home/alberto/anaconda3/envs/py27/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type sha256
ERROR:root:code for hash sha384 was not found.
Traceback (most recent call last):
  File "/home/alberto/anaconda3/envs/py27/lib/python2.7/hashlib.py", line 147, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/home/alberto/anaconda3/envs/py27/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type sha384
ERROR:root:code for hash sha512 was not found.
Traceback (most recent call last):
  File "/home/alberto/anaconda3/envs/py27/lib/python2.7/hashlib.py", line 147, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/home/alberto/anaconda3/envs/py27/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type sha512
Traceback (most recent call last):
  File "/home/alberto/anaconda3/envs/py27/lib/python2.7/runpy.py", line 163, in _run_module_as_main
    mod_name, _Error)
  File "/home/alberto/anaconda3/envs/py27/lib/python2.7/runpy.py", line 111, in _get_module_details
    __import__(mod_name)  # Do not catch exceptions initializing package
  File "/home/alberto/anaconda3/envs/py27/lib/python2.7/site-packages/ipykernel/__init__.py", line 2, in <module>
    from .connect import *
  File "/home/alberto/anaconda3/envs/py27/lib/python2.7/site-packages/ipykernel/connect.py", line 13, in <module>
    from IPython.core.profiledir import ProfileDir
  File "/home/alberto/anaconda3/envs/py27/lib/python2.7/site-packages/IPython/__init__.py", line 48, in <module>
    from .core.application import Application
  File "/home/alberto/anaconda3/envs/py27/lib/python2.7/site-packages/IPython/core/application.py", line 25, in <module>
    from IPython.core import release, crashhandler
  File "/home/alberto/anaconda3/envs/py27/lib/python2.7/site-packages/IPython/core/crashhandler.py", line 28, in <module>
    from IPython.core import ultratb
  File "/home/alberto/anaconda3/envs/py27/lib/python2.7/site-packages/IPython/core/ultratb.py", line 124, in <module>
    from IPython.utils import path as util_path
  File "/home/alberto/anaconda3/envs/py27/lib/python2.7/site-packages/IPython/utils/path.py", line 16, in <module>
    from hashlib import md5
ImportError: cannot import name md5
```

Similar error is obtained if I try to install a fresh Anaconda 2 distribution.

Info about my conda installation:

```
Current conda install:

               platform : linux-64
          conda version : 4.3.27
       conda is private : False
      conda-env version : 4.3.27
    conda-build version : 3.0.23
         python version : 3.6.2.final.0
       requests version : 2.18.4
       root environment : /home/alberto/anaconda3  (writable)
    default environment : /home/alberto/anaconda3/envs/py27
       envs directories : /home/alberto/anaconda3/envs
                          /home/alberto/.conda/envs
          package cache : /home/alberto/anaconda3/pkgs
                          /home/alberto/.conda/pkgs
           channel URLs : https://repo.continuum.io/pkgs/main/linux-64
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/linux-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : None
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.27 requests/2.18.4 CPython/3.6.2 Linux/4.4.0-43-Microsoft debian/stretch/sid glibc/2.23
                UID:GID : 1000:1000
```

**Comment by albertotb** [comment]
A workaround is provided in the lastest OpenSSL and Python 2 builds. Check #6424

**Comment by mingwandroid** [comment]
It is a fix, not a workaround.
