### ISSUE TITLE
cannot install R studio

### ISSUE THREAD

**Issue by Watesoyan** [ContinuumIO/anaconda-issues#6599]
## Main error
The following errors occurred:
## Traceback
```
Traceback (most recent call last):
  File "F:\Anaconda2\lib\site-packages\conda\exceptions.py", line 640, in conda_exception_handler
    return_value = func(*args, **kwargs)
  File "F:\Anaconda2\lib\site-packages\conda\cli\main.py", line 140, in _main
    exit_code = args.func(args, p)
  File "F:\Anaconda2\lib\site-packages\conda\cli\main_install.py", line 80, in execute
    install(args, parser, 'install')
  File "F:\Anaconda2\lib\site-packages\conda\cli\install.py", line 261, in install
    channel_priority_map=_channel_priority_map, is_update=isupdate)
  File "F:\Anaconda2\lib\site-packages\conda\plan.py", line 473, in install_actions_list
    linked_in_root = linked_data(context.root_prefix)
  File "F:\Anaconda2\lib\site-packages\conda\core\linked_data.py", line 115, in linked_data
    load_linked_data(prefix, dist_name, ignore_channels=ignore_channels)
  File "F:\Anaconda2\lib\site-packages\conda\core\linked_data.py", line 68, in load_linked_data
    linked_data_[prefix][dist] = rec = IndexRecord(**rec)
  File "F:\Anaconda2\lib\site-packages\conda\_vendor\auxlib\entity.py", line 702, in __call__
    instance = super(EntityType, cls).__call__(*args, **kwargs)
  File "F:\Anaconda2\lib\site-packages\conda\_vendor\auxlib\entity.py", line 719, in __init__
    setattr(self, key, kwargs[key])
  File "F:\Anaconda2\lib\site-packages\conda\_vendor\auxlib\entity.py", line 424, in __set__
    instance.__dict__[self.name] = self.validate(instance, self.box(instance, val))
  File "F:\Anaconda2\lib\site-pack

**Comment by goanpeca** [comment]
@Watesoyan could you try to install rstudio from the CLI and see of this error persists?

Also could you launch navigator from the CLI (open anaconda prompt and type `anaconda-navigator`) and paste any traceback that appears?
