### ISSUE TITLE
Re: Anaconda Navigator does not start on Mac OS X 10.12.6

### ISSUE THREAD

**Issue by MatthiasJobst** [ContinuumIO/anaconda-issues#6607]
Here is my post from the mailing list. Will Warner suggested to create an issue here.

Today I installed Anaconda. As it did not start when clicking the Thumbnail I turned to the terminal. But there I get the following error message:

```
anaconda-navigator

Traceback (most recent call last):

  File "/Users/xxx/anaconda3/lib/python3.6/site-packages/qtpy/__init__.py", line 148, in <module>

    from PySide import __version__ as PYSIDE_VERSION  # analysis:ignore

ModuleNotFoundError: No module named 'PySide'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "/Users/xxx/anaconda3/bin/anaconda-navigator", line 11, in <module>

    sys.exit(main())

  File "/Users/xxx/anaconda3/lib/python3.6/site-packages/anaconda_navigator/app/main.py", line 125, in main

    from anaconda_navigator.utils.logs import clean_logs

  File "/Users/xxx/anaconda3/lib/python3.6/site-packages/anaconda_navigator/utils/__init__.py", line 15, in <module>

    from qtpy.QtGui import QIcon

  File "/Users/xxx/anaconda3/lib/python3.6/site-packages/qtpy/__init__.py", line 154, in <module>

    raise PythonQtError('No Qt bindings could be found')

qtpy.PythonQtError: No Qt bindings could be found
```

I tried to follow the instructions from an earlier post:

> conda update conda
> 
> conda update anaconda-navigator

With the result as above.

I also tried to install pyside but that did not work either:

```
conda install PySide

Fetching package metadata ...........

Solving package specifications: .



UnsatisfiableError: The following specifications were found to be in conflict:

  - pyside -> python 2.7*

  - python 3.6*

Use "conda info <package>" to see the dependencies for each package.
```

**Comment by rezwanulhaquerezwan** [comment]
@MatthiasJobst . I have same problem. How can I sove this issue ?

**Comment by mingwandroid** [comment]
Please show the output of `conda info` and `conda list --show-channel-urls`.

**Comment by rezwanulhaquerezwan** [comment]
`conda info`
 ------
```
Current conda install:

               platform : osx-64
          conda version : 4.3.30
       conda is private : False
      conda-env version : 4.3.30
    conda-build version : not installed
         python version : 3.6.3.final.0
       requests version : 2.18.4
       root environment : /Users/rezwan/anaconda  (writable)
    default environment : /Users/rezwan/anaconda
       envs directories : /Users/rezwan/anaconda/envs
                          /Users/rezwan/.conda/envs
          package cache : /Users/rezwan/anaconda/pkgs
                          /Users/rezwan/.conda/pkgs
           channel URLs : https://repo.continuum.io/pkgs/main/osx-64
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/osx-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/osx-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/osx-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : /Users/rezwan/.condarc
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.30 requests/2.18.4 CPython/3.6.3 Darwin/16.7.0 OSX/10.12.6    
                UID:GID : 501:20
```

`conda list --show-channel-urls`
 ----
```
# packages in environment at /Users/rezwan/anaconda:
#
_license                  1.1                      py36_1    defaults
alabaster                 0.7.10           py36h174008c_0    defaults
anaconda                  5.0.1            py36h6e48e2d_1    defaults
anaconda-client           1.6.5            py36h04cfe59_0    defaults
anaconda-navigator        1.6.9            py36ha31b149_0    defaults
anaconda-project          0.8.0            py36h99320b2_0    defaults
appnope                   0.1.0            py36hf537a9a_0    defaults
appscript                 1.0.1            py36h9e71e49_1    defaults
asn1crypto                0.22.0           py36hb705621_1    defaults
astroid                   1.5.3            py36h1333018_0    defaults
astropy                   2.0.2            py36hf79c81d_4    defaults
babel                     2.5.0            py36h9f161ff_0    defaults
backports                 1.0              py36ha3c1827_1    defaults
backports.shutil_get_terminal_size 1.0.0            py36hd7a2ee4_2    defaults
beautifulsoup4            4.6.0            py36h72d3c9f_1    defaults
bitarray                  0.8.1            py36h20fa61d_0    defaults
bkcharts                  0.2              py36h073222e_0    defaults
blaze                     0.11.3           py36h02e7a37_0    defaults
bleach                    2.0.0            py36h8fcea71_0    defaults
bokeh                     0.12.10          py36hfd5be35_0    defaults
boto                      2.48.0           py36hdbc59ac_1    defaults
bottleneck                1.2.1            py36hbd380ad_0    defaults
bzip2                     1.0.6                h92991f9_1    defaults
ca-certificates           2017.08.26           ha1e5d58_0    defaults
certifi                   2017.7.27.1      py36hd973bb6_0    defaults
cffi                      1.10.0           py36h880867e_1    defaults
chardet                   3.0.4            py36h96c241c_1    defaults
click                     6.7              py36hec950be_0    defaults
cloudpickle               0.4.0            py36h13b7e56_0    defaults
clyent                    1.2.2            py36hae3ad88_0    defaults
colorama                  0.3.9            py36hd29a30c_0    defaults
conda                     4.3.30           py36h173c244_0    defaults
conda-env                 2.6.0                         0    conda-forge
contextlib2               0.5.5            py36hd66e5e7_0    defaults
cryptography              2.0.3            py36h22d4226_1    defaults
curl                      7.55.1               h7601780_3    defaults
cycler                    0.10.0           py36hfc81398_0    defaults
cython                    0.26.1           py36hd51f8eb_0    defaults
cytoolz                   0.8.2            py36h290905f_0    defaults
dask                      0.15.3           py36hc3ad2d6_0    defaults
dask-core                 0.15.3           py36hc0be6b7_0    defaults
datashape                 0.5.4            py36hfb22df8_0    defaults
dbus                      1.10.22              h50d9ad6_0    defaults
decorator                 4.1.2            py36h69a1b52_0    defaults
distributed               1.19.1           py36h4ae75d2_0    defaults
docutils                  0.14             py36hbfde631_0    defaults
entrypoints               0.2.3            py36hd81d71f_2    defaults
et_xmlfile                1.0.1            py36h1315bdc_0    defaults
expat                     2.2.4                h8f26bf8_1    defaults
fastcache                 1.0.2            py36h8606a76_0    defaults
filelock                  2.0.12           py36h0d0b4fb_0    defaults
flask                     0.12.2           py36h5658096_0    defaults
flask-cors                3.0.3            py36h7387b97_0    defaults
freetype                  2.8                  h143eb01_0    defaults
get_terminal_size         1.0.0                h7520d66_0    defaults
gettext                   0.19.8.1             hb0f4f8b_2    defaults
gevent                    1.2.2            py36ha70b9d6_0    defaults
glib                      2.53.6               ha08cb78_1    defaults
glob2                     0.5              py36h12393a9_0    defaults
gmp                       6.1.2                h4a9834d_0    defaults
gmpy2                     2.0.8            py36h7ef02cb_1    defaults
greenlet                  0.4.12           py36hf09ba7b_0    defaults
h5py                      2.7.0            py36h6400cee_1    defaults
hdf5                      1.10.1               h6090a45_0    defaults
heapdict                  1.0.0            py36h27a9ac6_0    defaults
html5lib                  0.999999999      py36h79312fd_0    defaults
icu                       58.2                 hea21ae5_0    defaults
idna                      2.6              py36h8628d0a_1    defaults
imageio                   2.2.0            py36h5e01289_0    defaults
imagesize                 0.7.1            py36h3495948_0    defaults
imutils                   0.4.3                     <pip>
intel-openmp              2018.0.0             h68bdfb3_7    defaults
ipykernel                 4.6.1            py36h3208c25_0    defaults
ipython                   6.1.0            py36hf612aae_1    defaults
ipython_genutils          0.2.0            py36h241746c_0    defaults
ipywidgets                7.0.0            py36h24d3910_0    defaults
isort                     4.2.15           py36hceb2a01_0    defaults
itsdangerous              0.24             py36h49fbb8d_1    defaults
jbig                      2.1                  h4d881f8_0    defaults
jdcal                     1.3              py36h1986823_0    defaults
jedi                      0.10.2           py36h6325097_0    defaults
jinja2                    2.9.6            py36hde4beb4_1    defaults
jpeg                      9b                   haccd157_1    defaults
jsonschema                2.6.0            py36hb385e00_0    defaults
jupyter                   1.0.0            py36h598a6cc_0    defaults
jupyter_client            5.1.0            py36hf6c435f_0    defaults
jupyter_console           5.2.0            py36hccf5b1c_1    defaults
jupyter_core              4.3.0            py36h93810fe_0    defaults
jupyterlab                0.27.0           py36hd3092eb_2    defaults
jupyterlab_launcher       0.4.0            py36h93e02e9_0    defaults
keras                     2.0.6                    py36_0    conda-forge
launcher                  1.0.0                         3    defaults
lazy-object-proxy         1.3.1            py36h2fbbe47_0    defaults
libcxx                    4.0.1                h579ed51_0    defaults
libcxxabi                 4.0.1                hebd6815_0    defaults
libedit                   3.1                  hb4e282d_0    defaults
libffi                    3.2.1                hd939716_3    defaults
libgfortran               3.0.1                h93005f0_2    defaults
libiconv                  1.15                 h99df5da_5    defaults
libpng                    1.6.32               hce72d48_2    defaults
libsodium                 1.0.13               hba5e272_2    defaults
libssh2                   1.8.0                h1218725_2    defaults
libtiff                   4.0.8                h8cd0352_9    defaults
libxml2                   2.9.4                hbd0960b_5    defaults
libxslt                   1.1.29               h95a2935_5    defaults
llvmlite                  0.20.0                   py36_0    defaults
locket                    0.2.0            py36hca03003_1    defaults
lxml                      4.1.0            py36h8179fc0_0    defaults
lzo                       2.10                 hb6b8854_1    defaults
markupsafe                1.0              py36h3a1e703_1    defaults
matplotlib                2.1.0            py36h5068139_0    defaults
mccabe                    0.6.1            py36hdaeb55d_0    defaults
mistune                   0.7.4            py36hccd6237_0    defaults
mkl                       2018.0.0             h5ef208c_6    defaults
mkl-service               1.1.2            py36h7ea6df4_4    defaults
mock                      2.0.0                    py36_0    conda-forge
mpc                       1.0.3                hc455b36_4    defaults
mpfr                      3.1.5                h7fa3772_1    defaults
mpmath                    0.19             py36h9185fea_2    defaults
msgpack-python            0.4.8            py36h46767b2_0    defaults
multipledispatch          0.4.9            py36hc5f92b5_0    defaults
navigator-updater         0.1.0            py36h7aee5fb_0    defaults
nbconvert                 5.3.1            py36h810822e_0    defaults
nbformat                  4.4.0            py36h827af21_0    defaults
ncurses                   6.0                  ha932d30_1    defaults
networkx                  2.0              py36hefccab9_0    defaults
nltk                      3.2.4            py36h27d1ea0_0    defaults
node-webkit               0.10.1                        0    defaults
nose                      1.3.7            py36h73fae2b_2    defaults
notebook                  5.0.0            py36h462289e_2    defaults
numba                     0.35.0              np113py36_6    defaults
numexpr                   2.6.2            py36h0f4f1da_1    defaults
numpy                     1.13.3           py36h2cdce51_0    defaults
numpy                     1.13.3                    <pip>
numpydoc                  0.7.0            py36he54d08e_0    defaults
odo                       0.5.1            py36hc1af34a_0    defaults
olefile                   0.44             py36ha08bf50_0    defaults
opencv-contrib-python     3.3.0.10                  <pip>
openpyxl                  2.4.8            py36he899640_1    defaults
openssl                   1.0.2l               h57f3a61_2    defaults
packaging                 16.8             py36he5e8135_0    defaults
pandas                    0.20.3           py36hd6655d8_2    defaults
pandoc                    1.19.2.1             ha5e8f32_1    defaults
pandocfilters             1.4.2            py36h3b0b094_1    defaults
partd                     0.3.8            py36hf5c4cb8_0    defaults
path.py                   10.3.1           py36hd33c240_0    defaults
pathlib2                  2.3.0            py36h877a6d8_0    defaults
patsy                     0.4.1            py36ha1b3fa5_0    defaults
pbr                       3.1.1                    py36_0    conda-forge
pcre                      8.41                 h29eefc5_0    defaults
pep8                      1.7.0            py36hc268eb1_0    defaults
pexpect                   4.2.1            py36h3eac828_0    defaults
pickleshare               0.7.4            py36hf512f8e_0    defaults
pillow                    4.2.1            py36h0263179_0    defaults
pip                       9.0.1            py36hbd95645_3    defaults
pkginfo                   1.4.1            py36h25bf955_0    defaults
ply                       3.10             py36h10e714e_0    defaults
prompt_toolkit            1.0.15           py36haeda067_0    defaults
protobuf                  3.0.0b2                   <pip>
protobuf                  3.3.2                    py36_0    conda-forge
psutil                    5.4.0            py36ha052210_0    defaults
ptyprocess                0.5.2            py36he6521c3_0    defaults
py                        1.4.34           py36hecf431b_1    defaults
pycodestyle               2.3.1            py36h83e8646_0    defaults
pycosat                   0.6.2            py36h1486600_0    defaults
pycparser                 2.18             py36h724b2fc_1    defaults
pycrypto                  2.6.1            py36h72f2894_1    defaults
pycurl                    7.43.0           py36hdb90038_3    defaults
pyflakes                  1.6.0            py36hea45e83_0    defaults
pygments                  2.2.0            py36h240cd3f_0    defaults
pylint                    1.7.4            py36hdee9077_0    defaults
pyodbc                    4.0.17           py36h5478161_0    defaults
pyopenssl                 17.2.0           py36h5d7bf08_0    defaults
pyparsing                 2.2.0            py36hb281f35_0    defaults
pyqt                      5.6.0            py36he5c6137_6    defaults
pysocks                   1.6.7            py36hfa33cec_1    defaults
pytables                  3.4.2            py36hfbd7ab0_2    defaults
pytest                    3.2.1            py36h9963153_1    defaults
python                    3.6.3                h6804ab2_0    defaults
python-dateutil           2.6.1            py36h86d2abb_1    defaults
python.app                2                py36h7fe2238_6    defaults
pytz                      2017.2           py36h2e7dfbc_1    defaults
pywavelets                0.5.2            py36h2710a04_0    defaults
pyyaml                    3.12             py36h2ba1e63_1    defaults
pyzmq                     16.0.2           py36h087ffad_2    defaults
qt                        5.6.2               h9975529_14    defaults
qtawesome                 0.4.4            py36h468c6fb_0    defaults
qtconsole                 4.3.1            py36hd96c0ff_0    defaults
qtpy                      1.3.1            py36h16bb863_0    defaults
QtPy                      1.0                       <pip>
readline                  7.0                  h81b24a6_3    defaults
requests                  2.18.4           py36h4516966_1    defaults
rope                      0.10.5           py36h5764ad1_0    defaults
ruamel_yaml               0.11.14          py36h9d7ade0_2    defaults
scikit-image              0.13.0           py36h398857d_1    defaults
scikit-learn              0.19.1           py36hffbff8c_0    defaults
scipy                     0.19.1           py36h3e758e1_3    defaults
seaborn                   0.8.0            py36h74df97e_0    defaults
setuptools                36.6.0                    <pip>
setuptools                36.5.0           py36h2134326_0    defaults
simplegeneric             0.8.1            py36he5b5b09_0    defaults
singledispatch            3.4.0.3          py36hf20db9d_0    defaults
sip                       4.18.1           py36h2824476_2    defaults
six                       1.11.0           py36h0e22d5e_1    defaults
six                       1.11.0                    <pip>
snowballstemmer           1.2.1            py36h6c7b616_0    defaults
sortedcollections         0.5.3            py36he9c3ed6_0    defaults
sortedcontainers          1.5.7            py36ha982688_0    defaults
sphinx                    1.6.3            py36hcd1b3e7_0    defaults
sphinxcontrib             1.0              py36h9364dc8_1    defaults
sphinxcontrib-websupport  1.0.1            py36h92f4a7a_1    defaults
spyder                    3.2.4            py36h908396f_0    defaults
sqlalchemy                1.1.13           py36h156b851_0    defaults
sqlite                    3.20.1               h900c3b0_1    defaults
statsmodels               0.8.0            py36h9c68fc9_0    defaults
sympy                     1.1.1            py36h7f3cf04_0    defaults
tblib                     1.3.2            py36hda67792_0    defaults
tensorflow                0.8.0rc0                  <pip>
tensorflow                1.0.0                    py36_0    conda-forge
terminado                 0.6              py36h656782e_0    defaults
testpath                  0.3.1            py36h625a49b_0    defaults
tk                        8.6.7                hcdce994_1    defaults
toolz                     0.8.2            py36h7b95164_0    defaults
tornado                   4.5.2            py36h468dda9_0    defaults
traitlets                 4.3.2            py36h65bd3ce_0    defaults
typing                    3.6.2            py36haa2d9ef_0    defaults
unicodecsv                0.14.1           py36he531d66_0    defaults
unixodbc                  2.3.4                h4cb4dde_1    defaults
urllib3                   1.22             py36h68b9469_0    defaults
wcwidth                   0.1.7            py36h8c6ec74_0    defaults
webencodings              0.5.1            py36h3b9701d_1    defaults
werkzeug                  0.12.2           py36h168efa1_0    defaults
wheel                     0.30.0                    <pip>
wheel                     0.29.0           py36h3597b6d_1    defaults
widgetsnbextension        3.0.2            py36h91f43ea_1    defaults
wrapt                     1.10.11          py36hc29e774_0    defaults
xlrd                      1.1.0            py36h336f4a2_1    defaults
xlsxwriter                1.0.2            py36h3736301_0    defaults
xlwings                   0.11.4           py36hc75f156_0    defaults
xlwt                      1.2.0            py36h5ad1178_0    defaults
xz                        5.2.3                ha24016e_1    defaults
yaml                      0.1.7                hff548bb_1    defaults
zeromq                    4.2.2                h131e0f7_1    defaults
zict                      0.1.3            py36h71da714_0    defaults
zlib                      1.2.11               h60db283_1    defaults
```

What can I do now @mingwandroid ?

**Comment by MatthiasJobst** [comment]
My files are attached. 
[condainfo.txt](https://github.com/ContinuumIO/anaconda-issues/files/1443294/condainfo.txt)
[condalist.txt](https://github.com/ContinuumIO/anaconda-issues/files/1443295/condalist.txt)

This is from a Mac that I have been using brew and installing python. I have been successful with installing anaconda on a Mac without brew. Makes sense?

**Comment by mingwandroid** [comment]
I'll look into this more next week or maybe tomorrow if I can find time.

**Comment by MatthiasJobst** [comment]
Based on my hunch further up, I uninstalled brew like describe on their home-brew site and now I can run Anaconda.

**Comment by sundayle** [comment]
block Anacona Host
sudo vim /etc/hosts
127.0.0.1 api.alpha.binstar.org
127.0.0.1 api.anaconda.org

https://www.sundayle.com/2018/01/21/Anacona-Navigator-No-response/
