### ISSUE TITLE
 The filename, directory name, or volume label syntax is incorrect: 'C:\\WINDOWS\\System32\\ C:

### ISSUE THREAD

**Issue by sravanikadem** [ContinuumIO/anaconda-issues#6675]
D:\anaconda) C:\WINDOWS\System32>jupyter notebook
Traceback (most recent call last):
  File "D:\anaconda\Scripts\jupyter-notebook-script.py", line 5, in <module>
    sys.exit(notebook.notebookapp.main())
  File "D:\anaconda\lib\site-packages\jupyter_core\application.py", line 267, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "D:\anaconda\lib\site-packages\traitlets\config\application.py", line 657, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-7>", line 2, in initialize
  File "D:\anaconda\lib\site-packages\traitlets\config\application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "D:\anaconda\lib\site-packages\notebook\notebookapp.py", line 1290, in initialize
    super(NotebookApp, self).initialize(argv)
  File "<decorator-gen-6>", line 2, in initialize
  File "D:\anaconda\lib\site-packages\traitlets\config\application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "D:\anaconda\lib\site-packages\jupyter_core\application.py", line 243, in initialize
    self.migrate_config()
  File "D:\anaconda\lib\site-packages\jupyter_core\application.py", line 169, in migrate_config
    migrate()
  File "D:\anaconda\lib\site-packages\jupyter_core\migrate.py", line 240, in migrate
    ensure_dir_exists(env['jupyter_config'])
  File "D:\anaconda\lib\site-packages\ipython_genutils\path.py", line 167, in ensure_dir_exists
    os.makedirs(path, mode=mode)
  File "D:\anaconda\lib\os.py", line 150, in makedirs
    makedirs(head, mode)
  File "D:\anaconda\lib\os.py", line 150, in makedirs
    makedirs(head, mode)
  File "D:\anaconda\lib\os.py", line 150, in makedirs
    makedirs(head, mode)
  File "D:\anaconda\lib\os.py", line 150, in makedirs
    makedirs(head, mode)
  File "D:\anaconda\lib\os.py", line 150, in makedirs
    makedirs(head, mode)
  File "D:\anaconda\lib\os.py", line 157, in makedirs
    mkdir(name, mode)
WindowsError: [Error 123] The filename, directory name, or volume label syntax is incorrect: 'C:\\WINDOWS\\System32\\ C:

when run jupyter notebook i am getting following error.

**Comment by goanpeca** [comment]
Why are you running jupyter notebook from `C:\WINDOWS\System32>` directory?

Also did you make an all system install? I recommend you use installation for current user only.
