### ISSUE TITLE
numpy 1.10 on OSX - ImportError: cannot import name scalarmath

### ISSUE THREAD

**Issue by richafrank** [ContinuumIO/anaconda-issues#668]
miniconda2 on osx-64

```bash
$ conda create --name numpy110 python=2.7 numpy=1.10
$ source activate numpy110
$ python -c "import numpy"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/rich/miniconda2/envs/numpy110/lib/python2.7/site-packages/numpy/__init__.py", line 170, in <module>
    from . import add_newdocs
  File "/Users/rich/miniconda2/envs/numpy110/lib/python2.7/site-packages/numpy/add_newdocs.py", line 13, in <module>
    from numpy.lib import add_newdoc
  File "/Users/rich/miniconda2/envs/numpy110/lib/python2.7/site-packages/numpy/lib/__init__.py", line 8, in <module>
    from .type_check import *
  File "/Users/rich/miniconda2/envs/numpy110/lib/python2.7/site-packages/numpy/lib/type_check.py", line 11, in <module>
    import numpy.core.numeric as _nx
  File "/Users/rich/miniconda2/envs/numpy110/lib/python2.7/site-packages/numpy/core/__init__.py", line 20, in <module>
    from . import scalarmath
ImportError: cannot import name scalarmath
```

I saw this with 1.10.4 and 1.10.2.

**Comment by richafrank** [comment]
Noticed that someone else reported this on [stackoverflow] (https://stackoverflow.com/questions/34343685/trouble-creating-a-conda-enviroment-with-numpy-10-1-2) as well.

**Comment by kalefranz** [comment]
kfranz@0283:~ ❯ conda create --name temp27 python=2.7 cython=0.23.4
    ...
    kfranz@0283:~ ❯ source activate temp27
    discarding /Users/kfranz/.conda/bin from PATH
    prepending /Users/kfranz/.conda/envs/temp27/bin to PATH
    (temp27)kfranz@0283:~ ❯ conda list|grep -i cython
    cython                    0.23.4                   py27_1
    (temp27)kfranz@0283:~ ❯ python -c "import Cython;print Cython.__version__"
    0.23.4
    (temp27)kfranz@0283:~ ❯ conda info
    Current conda install:

                 platform : osx-64
            conda version : 3.19.1
      conda-build version : 1.18.2
           python version : 2.7.10.final.0
         requests version : 2.9.1
         root environment : /Users/kfranz/.conda  (writable)
      default environment : /Users/kfranz/.conda/envs/temp27
         envs directories : /Users/kfranz/.conda/envs
            package cache : /Users/kfranz/.conda/pkgs
             channel URLs : https://repo.continuum.io/pkgs/free/osx-64/
                            https://repo.continuum.io/pkgs/free/noarch/
                            https://repo.continuum.io/pkgs/pro/osx-64/
                            https://repo.continuum.io/pkgs/pro/noarch/
              config file : /Users/kfranz/.condarc
        is foreign system : False

Also not able to reproduce.  But let's get this figured out... `conda info` is the starting point...

**Comment by richafrank** [comment]
```bash
$ conda info
Current conda install:

             platform : osx-64
        conda version : 3.19.1
  conda-build version : 1.19.0
       python version : 2.7.11.final.0
     requests version : 2.9.1
     root environment : /Users/rich/miniconda2  (writable)
  default environment : /Users/rich/miniconda2
     envs directories : /Users/rich/miniconda2/envs
        package cache : /Users/rich/miniconda2/pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/osx-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/osx-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : None
    is foreign system : False
```
