### ISSUE TITLE
gfortran_linux-64 pins to broken Python 3.6.2_15.

### ISSUE THREAD

**Issue by rainwoodman** [ContinuumIO/anaconda-issues#6698]
```
(root) [yfeng1@waterfall anaconda-recipes]$ conda install gfortran_linux-64
Fetching package metadata ...........
Solving package specifications: .

Package plan for installation in environment /home/yfeng1/anaconda3/install:

The following NEW packages will be INSTALLED:

    gfortran_impl_linux-64: 7.2.0-hb3c8cce_2
    gfortran_linux-64:      7.2.0-hc3a7fdf_7

The following packages will be DOWNGRADED:

    python:                 3.6.3-hc9025b9_1 --> 3.6.2-hdfe5801_15

(root) [yfeng1@waterfall anaconda-recipes]$ conda update python
Failed to import the site module
Traceback (most recent call last):
  File "/home/yfeng1/anaconda3/install/lib/python3.6/site.py", line 541, in <module>
    main()
  File "/home/yfeng1/anaconda3/install/lib/python3.6/site.py", line 522, in main
    known_paths = addusersitepackages(known_paths)
  File "/home/yfeng1/anaconda3/install/lib/python3.6/site.py", line 282, in addusersitepackages
    user_site = getusersitepackages()
  File "/home/yfeng1/anaconda3/install/lib/python3.6/site.py", line 258, in getusersitepackages
    user_base = getuserbase() # this will also set USER_BASE
  File "/home/yfeng1/anaconda3/install/lib/python3.6/site.py", line 248, in getuserbase
    USER_BASE = get_config_var('userbase')
  File "/home/yfeng1/anaconda3/install/lib/python3.6/sysconfig.py", line 601, in get_config_var
    return get_config_vars().get(name)
  File "/home/yfeng1/anaconda3/install/lib/python3.6/sysconfig.py", line 550, in get_config_vars
    _init_posix(_CONFIG_VARS)
  File "/home/yfeng1/anaconda3/install/lib/python3.6/sysconfig.py", line 421, in _init_posix
    _temp = __import__(name, globals(), locals(), ['build_time_vars'], 0)
ModuleNotFoundError: No module named '_sysconfigdata_x86_64_conda_cos6_linux_gnu'
```

**Comment by mingwandroid** [comment]
Which version of conda are you running here? `gfortran_linux-64` does not pin to conda at all. I suspect a conda bug.

**Comment by rainwoodman** [comment]
```
(root) [yfeng1@waterfall ~]$ conda info
Current conda install:

               platform : linux-64
          conda version : 4.3.29
       conda is private : False
      conda-env version : 4.3.29
    conda-build version : 3.0.26
         python version : 3.6.3.final.0
       requests version : 2.18.4
       root environment : /home/yfeng1/anaconda3/install  (writable)
    default environment : /home/yfeng1/anaconda3/install
       envs directories : /home/yfeng1/anaconda3/install/envs
                          /home/yfeng1/.conda/envs
          package cache : /home/yfeng1/anaconda3/install/pkgs
                          /home/yfeng1/.conda/pkgs
           channel URLs : https://repo.continuum.io/pkgs/main/linux-64
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/linux-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : /home/yfeng1/.condarc
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.29 requests/2.18.4 CPython/3.6.3 Linux/4.12.13-200.fc25.x86_64 Fedora/25 glibc/2.24    
                UID:GID : 1000:1000
```

**Comment by mingwandroid** [comment]
@kalefranz, can you take a look at this please?

**Comment by kalefranz** [comment]
Seems like it might be related to https://github.com/conda/conda/issues/6164#issuecomment-336664013

**Comment by jakirkham** [comment]
Any news on this? Seeing this if I merely try to switch from an environment with the `gcc` package into another environment.

**Comment by msarahan** [comment]
@jakirkham can you give us a reproducer series of steps in a docker container?  I don't see anything in the dependencies that should have this effect.

depends for gfortran_linux-64-7.2.0-25.tar.bz2:

0 | "binutils_linux-64 7.2.0 25"
-- | --
1 | "gcc_linux-64 7.2.0 25"
2 | "gfortran_impl_linux-64 7.2.0.*"

**Comment by msarahan** [comment]
```
[root@e6461efe113d build_scripts]# conda -V
conda 4.4.10
[root@e6461efe113d build_scripts]# python -V
Python 3.6.4 :: Anaconda, Inc.
[root@e6461efe113d build_scripts]# conda install gfortran_linux-64
Solving environment: done

## Package Plan ##

  environment location: /opt/conda

  added / updated specs:
    - gfortran_linux-64


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    gfortran_linux-64-7.2.0    |               25           5 KB  defaults
    gfortran_impl_linux-64-7.2.0|       hb3c8cce_2         8.8 MB  defaults
    libgfortran-ng-7.2.0       |       h9f7466a_2         349 KB  defaults
    ------------------------------------------------------------
                                           Total:         9.2 MB

The following NEW packages will be INSTALLED:

    gfortran_impl_linux-64: 7.2.0-hb3c8cce_2 defaults
    gfortran_linux-64:      7.2.0-25         defaults
    libgfortran-ng:         7.2.0-h9f7466a_2 defaults
```

**Comment by jakirkham** [comment]
It's been a few days, but I did something like this.

1. Install `gcc_linux-64` in a new environment.
2. Activate that environment.
3. Try to switch out of that environment (e.g. to `root`).

I think it was basically getting confused and trying to use `python` from a different environment than `gcc_linux-64` was installed in, which caused things to go sideways. If this doesn't help, I can take a closer look.

**Comment by msarahan** [comment]
I can reproduce this when:

1. root env is an older python version that is missing the compiler compatibility shim
2. other env has newer python and compiler package installed
3. activate other env, then activate root.

This is happening because once the inner environment is activated, these env vars are set:

```
_PYTHON_SYSCONFIGDATA_NAME=_sysconfigdata_x86_64_conda_cos6_linux_gnu
_PYTHON_SYSCONFIGDATA_NAME_USED=_sysconfigdata_x86_64_conda_cos6_linux_gnu
```

All Python 3.6 installs use these vars (and we backported these vars to earlier python versions).  It is insufficient for conda to unset them only at deactivation time, because any conda operation done with the inner env activated will use the outer python, and will fail.

The workaround I recommend right now is to update python in your root environment.  To get unstuck and perform this update, do

``unset _PYTHON_SYSCONFIGDATA_NAME``

A proper fix would be to patch the older pythons and have them handle failure to import this module more gracefully.  A more hackish solution might be to have conda force python to ignore this environment variable, but I'm not sure if Conda could even get at os.environ soon enough before python tried to load this info.

I recommend updating your root env python for now.  We'll talk about this issue internally and decide whether this is worth a fix, given that the workaround is pretty straightforward.

```
[root@dad185ee6924 build_scripts]# conda install python=3.6.2
Solving environment: done

## Package Plan ##

  environment location: /opt/conda

  added / updated specs:
    - python=3.6.2


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    python-3.6.2               |      hca45abc_19        27.0 MB  defaults

The following packages will be DOWNGRADED:

    python: 3.6.4-hc3d631a_1 defaults --> 3.6.2-hca45abc_19 defaults

Proceed ([y]/n)? y


Downloading and Extracting Packages
python 3.6.2: ############################################################################################## | 100%
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
[root@dad185ee6924 build_scripts]# conda install python=3.6.1
Solving environment: done

## Package Plan ##

  environment location: /opt/conda

  added / updated specs:
    - python=3.6.1


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    python-3.6.1               |                2        16.4 MB  defaults
    git-2.14.1                 |  pl526h58e4575_2        11.3 MB  defaults
    readline-6.2               |                2         606 KB  defaults
    tk-8.5.18                  |                0         1.9 MB  defaults
    sqlite-3.13.0              |                0         4.0 MB  defaults
    ------------------------------------------------------------
                                           Total:        34.1 MB

The following packages will be DOWNGRADED:

    git:      2.16.1-pl526hb75a9fb_1 defaults --> 2.14.1-pl526h58e4575_2 defaults
    python:   3.6.2-hca45abc_19      defaults --> 3.6.1-2                defaults
    readline: 7.0-ha6073c6_4         defaults --> 6.2-2                  defaults
    sqlite:   3.22.0-h1bed415_0      defaults --> 3.13.0-0               defaults
    tk:       8.6.7-hc745277_3       defaults --> 8.5.18-0               defaults

Proceed ([y]/n)?


Downloading and Extracting Packages
python 3.6.1: ############################################################################################## | 100%
git 2.14.1: ################################################################################################ | 100%
readline 6.2: ############################################################################################## | 100%
tk 8.5.18: ################################################################################################# | 100%
sqlite 3.13.0: ############################################################################################# | 100%
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
[root@dad185ee6924 build_scripts]# source activate compiler
INFO: activate-binutils_linux-64.sh made the following environmental changes:
+ADDR2LINE=/opt/conda/envs/compiler/bin/x86_64-conda_cos6-linux-gnu-addr2line
+AR=/opt/conda/envs/compiler/bin/x86_64-conda_cos6-linux-gnu-ar
+AS=/opt/conda/envs/compiler/bin/x86_64-conda_cos6-linux-gnu-as
+CXXFILT=/opt/conda/envs/compiler/bin/x86_64-conda_cos6-linux-gnu-c++filt
+ELFEDIT=/opt/conda/envs/compiler/bin/x86_64-conda_cos6-linux-gnu-elfedit
+GPROF=/opt/conda/envs/compiler/bin/x86_64-conda_cos6-linux-gnu-gprof
+HOST=x86_64-conda_cos6-linux-gnu
+LD_GOLD=/opt/conda/envs/compiler/bin/x86_64-conda_cos6-linux-gnu-ld.gold
+LD=/opt/conda/envs/compiler/bin/x86_64-conda_cos6-linux-gnu-ld
+NM=/opt/conda/envs/compiler/bin/x86_64-conda_cos6-linux-gnu-nm
+OBJCOPY=/opt/conda/envs/compiler/bin/x86_64-conda_cos6-linux-gnu-objcopy
+OBJDUMP=/opt/conda/envs/compiler/bin/x86_64-conda_cos6-linux-gnu-objdump
+RANLIB=/opt/conda/envs/compiler/bin/x86_64-conda_cos6-linux-gnu-ranlib
+READELF=/opt/conda/envs/compiler/bin/x86_64-conda_cos6-linux-gnu-readelf
+SIZE=/opt/conda/envs/compiler/bin/x86_64-conda_cos6-linux-gnu-size
+STRINGS=/opt/conda/envs/compiler/bin/x86_64-conda_cos6-linux-gnu-strings
+STRIP=/opt/conda/envs/compiler/bin/x86_64-conda_cos6-linux-gnu-strip
INFO: activate-gfortran_linux-64.sh made the following environmental changes:
+DEBUG_FFLAGS=-fopenmp -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -pipe -fopenmp -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-all -fno-plt -Og -g -Wall -Wextra -fcheck=all -fbacktrace -fimplicit-none -fvar-tracking-assignments -pipe
+DEBUG_FORTRANFLAGS=-fopenmp -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -pipe -fopenmp -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-all -fno-plt -Og -g -Wall -Wextra -fcheck=all -fbacktrace -fimplicit-none -fvar-tracking-assignments -pipe
+F77=/opt/conda/envs/compiler/bin/x86_64-conda_cos6-linux-gnu-gfortran
+F95=/opt/conda/envs/compiler/bin/x86_64-conda_cos6-linux-gnu-f95
+FC=/opt/conda/envs/compiler/bin/x86_64-conda_cos6-linux-gnu-gfortran
+FFLAGS=-fopenmp -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -pipe
+FORTRANFLAGS=-fopenmp -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -pipe
+GFORTRAN=/opt/conda/envs/compiler/bin/x86_64-conda_cos6-linux-gnu-gfortran
INFO: activate-gcc_linux-64.sh made the following environmental changes:
+CC=/opt/conda/envs/compiler/bin/x86_64-conda_cos6-linux-gnu-cc
+CFLAGS=-march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -pipe
+CPPFLAGS=-DNDEBUG -D_FORTIFY_SOURCE=2 -O2
+CPP=/opt/conda/envs/compiler/bin/x86_64-conda_cos6-linux-gnu-cpp
+DEBUG_CFLAGS=-march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-all -fno-plt -Og -g -Wall -Wextra -fvar-tracking-assignments -pipe
+DEBUG_CPPFLAGS=-D_DEBUG -D_FORTIFY_SOURCE=2 -Og
+GCC_AR=/opt/conda/envs/compiler/bin/x86_64-conda_cos6-linux-gnu-gcc-ar
+GCC_NM=/opt/conda/envs/compiler/bin/x86_64-conda_cos6-linux-gnu-gcc-nm
+GCC=/opt/conda/envs/compiler/bin/x86_64-conda_cos6-linux-gnu-gcc
+GCC_RANLIB=/opt/conda/envs/compiler/bin/x86_64-conda_cos6-linux-gnu-gcc-ranlib
+LDFLAGS=-Wl,-O2 -Wl,--sort-common -Wl,--as-needed -Wl,-z,relro -Wl,-z,now
+_PYTHON_SYSCONFIGDATA_NAME=_sysconfigdata_x86_64_conda_cos6_linux_gnu
(compiler) [root@dad185ee6924 build_scripts]# source activate
Failed to import the site module
Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site.py", line 544, in <module>
    main()
  File "/opt/conda/lib/python3.6/site.py", line 530, in main
    known_paths = addusersitepackages(known_paths)
  File "/opt/conda/lib/python3.6/site.py", line 282, in addusersitepackages
    user_site = getusersitepackages()
  File "/opt/conda/lib/python3.6/site.py", line 258, in getusersitepackages
    user_base = getuserbase() # this will also set USER_BASE
  File "/opt/conda/lib/python3.6/site.py", line 248, in getuserbase
    USER_BASE = get_config_var('userbase')
  File "/opt/conda/lib/python3.6/sysconfig.py", line 601, in get_config_var
    return get_config_vars().get(name)
  File "/opt/conda/lib/python3.6/sysconfig.py", line 550, in get_config_vars
    _init_posix(_CONFIG_VARS)
  File "/opt/conda/lib/python3.6/sysconfig.py", line 421, in _init_posix
    _temp = __import__(name, globals(), locals(), ['build_time_vars'], 0)
ModuleNotFoundError: No module named '_sysconfigdata_x86_64_conda_cos6_linux_gnu'
(compiler) [root@dad185ee6924 build_scripts]# python
Python 3.6.4 |Anaconda, Inc.| (default, Jan 16 2018, 18:10:19)
[GCC 7.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>>
(compiler) [root@dad185ee6924 build_scripts]# conda -V
Failed to import the site module
Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site.py", line 544, in <module>
    main()
  File "/opt/conda/lib/python3.6/site.py", line 530, in main
    known_paths = addusersitepackages(known_paths)
  File "/opt/conda/lib/python3.6/site.py", line 282, in addusersitepackages
    user_site = getusersitepackages()
  File "/opt/conda/lib/python3.6/site.py", line 258, in getusersitepackages
    user_base = getuserbase() # this will also set USER_BASE
  File "/opt/conda/lib/python3.6/site.py", line 248, in getuserbase
    USER_BASE = get_config_var('userbase')
  File "/opt/conda/lib/python3.6/sysconfig.py", line 601, in get_config_var
    return get_config_vars().get(name)
  File "/opt/conda/lib/python3.6/sysconfig.py", line 550, in get_config_vars
    _init_posix(_CONFIG_VARS)
  File "/opt/conda/lib/python3.6/sysconfig.py", line 421, in _init_posix
    _temp = __import__(name, globals(), locals(), ['build_time_vars'], 0)
ModuleNotFoundError: No module named '_sysconfigdata_x86_64_conda_cos6_linux_gnu'
```

**Comment by lucainnocenti** [comment]
@msarahan I've been having the same issue (or a very similar one at least): activating any conda environment with compilers installed (like those that get installed when installing something like theano) makes the system python unusable.

I'm not sure I understand your suggested fix though: I have python 3.6.4 in all my conda environments, and my system python is 3.6.3. The following shows the problem:

```
 me@me-laptop  ~  /usr/bin/python3.6 --version
Python 3.6.3
 me@me-laptop  ~  . activate base
INFO: activate-binutils_linux-64.sh made the following environmental changes:
+ADDR2LINE=/home/me/anaconda3/bin/x86_64-conda_cos6-linux-gnu-addr2line
+AR=/home/me/anaconda3/bin/x86_64-conda_cos6-linux-gnu-ar
+AS=/home/me/anaconda3/bin/x86_64-conda_cos6-linux-gnu-as
+CXXFILT=/home/me/anaconda3/bin/x86_64-conda_cos6-linux-gnu-c++filt
+ELFEDIT=/home/me/anaconda3/bin/x86_64-conda_cos6-linux-gnu-elfedit
+GPROF=/home/me/anaconda3/bin/x86_64-conda_cos6-linux-gnu-gprof
+HOST=x86_64-conda_cos6-linux-gnu
+LD_GOLD=/home/me/anaconda3/bin/x86_64-conda_cos6-linux-gnu-ld.gold
+LD=/home/me/anaconda3/bin/x86_64-conda_cos6-linux-gnu-ld
+NM=/home/me/anaconda3/bin/x86_64-conda_cos6-linux-gnu-nm
+OBJCOPY=/home/me/anaconda3/bin/x86_64-conda_cos6-linux-gnu-objcopy
+OBJDUMP=/home/me/anaconda3/bin/x86_64-conda_cos6-linux-gnu-objdump
+RANLIB=/home/me/anaconda3/bin/x86_64-conda_cos6-linux-gnu-ranlib
+READELF=/home/me/anaconda3/bin/x86_64-conda_cos6-linux-gnu-readelf
+SIZE=/home/me/anaconda3/bin/x86_64-conda_cos6-linux-gnu-size
+STRINGS=/home/me/anaconda3/bin/x86_64-conda_cos6-linux-gnu-strings
+STRIP=/home/me/anaconda3/bin/x86_64-conda_cos6-linux-gnu-strip
INFO: activate-gcc_linux-64.sh made the following environmental changes:
+CC=/home/me/anaconda3/bin/x86_64-conda_cos6-linux-gnu-cc
+CFLAGS=-march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -pipe
+CPPFLAGS=-DNDEBUG -D_FORTIFY_SOURCE=2 -O2
+CPP=/home/me/anaconda3/bin/x86_64-conda_cos6-linux-gnu-cpp
+DEBUG_CFLAGS=-march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-all -fno-plt -Og -g -Wall -Wextra -fvar-tracking-assignments -pipe
+DEBUG_CPPFLAGS=-D_DEBUG -D_FORTIFY_SOURCE=2 -Og
+GCC_AR=/home/me/anaconda3/bin/x86_64-conda_cos6-linux-gnu-gcc-ar
+GCC=/home/me/anaconda3/bin/x86_64-conda_cos6-linux-gnu-gcc
+GCC_NM=/home/me/anaconda3/bin/x86_64-conda_cos6-linux-gnu-gcc-nm
+GCC_RANLIB=/home/me/anaconda3/bin/x86_64-conda_cos6-linux-gnu-gcc-ranlib
+LDFLAGS=-Wl,-O2 -Wl,--sort-common -Wl,--as-needed -Wl,-z,relro -Wl,-z,now
+_PYTHON_SYSCONFIGDATA_NAME=_sysconfigdata_x86_64_conda_cos6_linux_gnu
INFO: activate-gxx_linux-64.sh made the following environmental changes:
+CXXFLAGS=-fvisibility-inlines-hidden -std=c++17 -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -pipe
+CXX=/home/me/anaconda3/bin/x86_64-conda_cos6-linux-gnu-c++
+DEBUG_CXXFLAGS=-fvisibility-inlines-hidden -std=c++17 -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-all -fno-plt -Og -g -Wall -Wextra -fvar-tracking-assignments -pipe
+GXX=/home/me/anaconda3/bin/x86_64-conda_cos6-linux-gnu-g++
(base)  me@x86_64-conda_cos6-linux-gnu  ~  python --version
Python 3.6.4 :: Anaconda custom (64-bit)
(base)  me@x86_64-conda_cos6-linux-gnu  ~  /usr/bin/python3.6 --version
Python 3.6.3
(base)  me@x86_64-conda_cos6-linux-gnu  ~  /usr/bin/python3.6          
Failed to import the site module
Traceback (most recent call last):
  File "/usr/lib/python3.6/site.py", line 561, in <module>
    main()
  File "/usr/lib/python3.6/site.py", line 547, in main
    known_paths = addusersitepackages(known_paths)
  File "/usr/lib/python3.6/site.py", line 288, in addusersitepackages
    user_site = getusersitepackages()
  File "/usr/lib/python3.6/site.py", line 264, in getusersitepackages
    user_base = getuserbase() # this will also set USER_BASE
  File "/usr/lib/python3.6/site.py", line 254, in getuserbase
    USER_BASE = get_config_var('userbase')
  File "/usr/lib/python3.6/sysconfig.py", line 607, in get_config_var
    return get_config_vars().get(name)
  File "/usr/lib/python3.6/sysconfig.py", line 550, in get_config_vars
    _init_posix(_CONFIG_VARS)
  File "/usr/lib/python3.6/sysconfig.py", line 421, in _init_posix
    _temp = __import__(name, globals(), locals(), ['build_time_vars'], 0)
ModuleNotFoundError: No module named '_sysconfigdata_x86_64_conda_cos6_linux_gnu'
```

I've seen apparently similar problems reported in other issues (https://github.com/conda/conda-build/issues/2523, https://github.com/conda/conda/issues/6030, https://github.com/conda/conda/issues/6225). I'm not 100% sure it is the same problem though because they all mention upgrading python to solve the issue, which doesn't work for me (let me know if it turns out that this is not the same issue discussed in this thread and I'll open a new issue).

**Comment by mingwandroid** [comment]
To run `/usr/bin/python3.6` you need to deactivate your conda environment first.

**Comment by lucainnocenti** [comment]
@mingwandroid if I do that it works, yes. The problem is indeed not that I want to use the system python with a conda environment activated, but rather that the system programs that use the system python are broken. For example, this means that I cannot navigate with [`autojump`](https://github.com/wting/autojump) when one such conda environment is activated.

**Comment by mingwandroid** [comment]
Well, this is a known problem. We have an idea about how to fix it but haven't found time yet. Can you not make a conda package for it or if that's too much work, can you just run:

```
git clone git://github.com/joelthelion/autojump.git
cd autojump
./install.py
```

.. from within an activated conda environment.

**Comment by lucainnocenti** [comment]
I see. That's fine, I can work around it. It's good to know that it is a known issue.

**Comment by lucainnocenti** [comment]
I see. If it's been worked on that's fine, I'll find my way around it.
I just want to point out that breaking the system python distribution is not really only an issue with something like autojump. For example, I also cannot install packages via `pip`, because `pip` calls the command `lsb_release -a`, which tries to use the system python libraries in `/usr/lib/python3.6/`. Your suggestion basically amounts to recompile all programs that use python to have them use the `conda` one.

**Comment by mingwandroid** [comment]
Yeah, we really need to fix this ASAP.

**Comment by lucainnocenti** [comment]
@mingwandroid  I found a way to use `pip` and other commands from inside an affected conda environment. It seems pretty hacky and I don't really know what I'm doing when handling these compilation flags, so I would appreciate if you could give me confirmation that I'm not messing up my system by doing this.

Changing the `_PYTHON_SYSCONFIGDATA_NAME` variable with
```
export _PYTHON_SYSCONFIGDATA_NAME='_sysconfigdata_m_linux_x86_64-linux-gnu'
```
 fixes the problem. I got the value to put by running `import os; import sys; os.environ.get('_PYTHON_SYSCONFIGDATA_NAME', '_sysconfigdata_{abi}_{platform}_{multiarch}'.format(abi=sys.abiflags,platform=sys.platform,multiarch=getattr(sys.implementation, '_multiarch',''),))` in a python shell *before* activating any conda environment. I got this python command by looking at `sysconfig.py`, L421, as pointed out by the tracebacks.

**Comment by mingwandroid** [comment]
I have a 'proper' (by some definitions of proper, this stuff is very ugly) fix ready now for all 3 Python versions. I need to build them and do extensive testing though. I also need to change our compiler activation scripts.

My fix is to add `_CONDA_PYTHON_SYSCONFIGDATA_NAME` so that we never need to set `_PYTHON_SYSCONFIGDATA_NAME` which should un-break system pythons.

**Comment by lucainnocenti** [comment]
@mingwandroid  that sounds great! Is there a quick and dirty way to do that while we wait for it to be implemented? Or should I stick with the "fix" I suggested above?

**Comment by mingwandroid** [comment]
Best to stick to your own workaround for now.

**Comment by wangxiaodiu** [comment]
I solved this problem in my env by doing:
1. `unset _PYTHON_SYSCONFIGDATA_NAME` as @msarahan suggested in [the comment](https://github.com/ContinuumIO/anaconda-issues/issues/6698#issuecomment-367788444)
2. `conda install gcc_linux-64`
3. deactivate and then activate.
Hope this could help in case someone needs a simple fix.

**Comment by smithsp** [comment]
I get "ModuleNotFoundError: No module named '_sysconfigdata_x86_64_conda_cos6_linux_gnu'" in https://circleci.com/gh/conda-forge/py-fann2-feedstock/34?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link .  Is it related to this error or should I look elsewhere?

**Comment by marscher** [comment]
now this one has reached conda-forges build infrastructure... my other CI is suffering from this already since a week or so, but I think it is a regression, because it used to work in the meantime.

**Comment by marscher** [comment]
It seems like it is only affecting Python 2.7 builds.

**Comment by marscher** [comment]
and 3.7

**Comment by mingwandroid** [comment]
@marscher, you you update python in the base env to https://anaconda.org/conda-forge/python/3.7.0/download/linux-64/python-3.7.0-hd21baee_1004.tar.bz2 before doing the build?

I believe what's happening here is that old python (built with old compilers, without patches to support new compilers) are being used with new compilers. I'm not sure what you're meant to do to avoid that though, pinging @conda-forge/core

**Comment by marscher** [comment]
Is that the most recent build of py37? I can just retrigger my build to test it.

**Comment by mingwandroid** [comment]
No, there's 2 streams in progress at the minute, and they have build numbers separated by 1000. I'm not sure what you're meant to do to specify things though.

**Comment by marscher** [comment]
On 10/10/18 2:13 PM, Ray Donnelly wrote:
> No, there's 2 streams in progress at the minute, and they have build 
> numbers separated by 1000. I'm not sure what you're meant to do to 
> specify things though.
In an old comment of @msahran back almost one year, he stated that one 
need to keep Python installed in root originating from the defaults 
channel in order to make use of the new compilers. So I tried exactly 
that - without success.

I just overlooked that your are referring to a cf build of Python. Sorry 
will just change my build config to test it.

**Comment by marscher** [comment]
When I just install the tar.bz2 manually (download, conda install), it will be just overridden upon installation of conda-build. Is there a way to circumvent this?

**Comment by marscher** [comment]
since this pkg is labeled gcc7, i will just try to install from there.

**Comment by marscher** [comment]
https://travis-ci.org/markovmodel/msmtools/jobs/439626991 still the same picture.

**Comment by jjhelmus** [comment]
I believe conda-forge/python-feedstock#203 is the same issue.  

Conda-forge is currently building two sets of packages.  The `gcc7` ones use the conda provided compilers while the `main` packages use a toolchain provided by the system.  

A [patch](https://github.com/conda-forge/python-feedstock/blob/2.7/recipe/0001-backport-Python-3.6-_PYTHON_SYSCONFIGDATA_NAME.patch) is needed to allow the `gcc7` packages but is not needed for the `main` labelled packages a should likely be removed.

**Comment by marscher** [comment]
solution xref: https://github.com/conda-forge/python-feedstock/issues/203

**Comment by wshuai294** [comment]
Hello, has the issue been solved? I met a similar problem after installing `cxx-compiler`.
