### ISSUE TITLE
ImportError: No module named 'pip._vendor.requests.adapters' for any pip command

### ISSUE THREAD

**Issue by Gabrielvon** [ContinuumIO/anaconda-issues#6719]
* Pip version: 9.0.1
* Python version: 3.5.4
* Operating system: windows 7

### Description:

pip install --upgrade tensorflow == 1.3.0

### What I've run:
![image](https://user-images.githubusercontent.com/8952869/31595471-a773f6ca-b26e-11e7-82c0-ceb8ae05d208.png)

```
(root) C:\Users\trader>pip install --upgrader tensorflow==1.3.0
Traceback (most recent call last):
  File "C:\Users\trader\Anaconda3\Scripts\pip-script.py", line 6, in <module>
    from pip import main
  File "C:\Users\trader\Anaconda3\lib\site-packages\pip\__init__.py", line 28, i
n <module>
    from pip.vcs import git, mercurial, subversion, bazaar  # noqa
  File "C:\Users\trader\Anaconda3\lib\site-packages\pip\vcs\mercurial.py", line
9, in <module>
    from pip.download import path_to_url
  File "C:\Users\trader\Anaconda3\lib\site-packages\pip\download.py", line 41, i
n <module>
    from pip._vendor.requests.adapters import BaseAdapter, HTTPAdapter
ImportError: No module named 'pip._vendor.requests.adapters'

(root) C:\Users\trader>pip -v
Traceback (most recent call last):
  File "C:\Users\trader\Anaconda3\Scripts\pip-script.py", line 6, in <module>
    from pip import main
  File "C:\Users\trader\Anaconda3\lib\site-packages\pip\__init__.py", line 28, i
n <module>
    from pip.vcs import git, mercurial, subversion, bazaar  # noqa
  File "C:\Users\trader\Anaconda3\lib\site-packages\pip\vcs\mercurial.py", line
9, in <module>
    from pip.download import path_to_url
  File "C:\Users\trader\Anaconda3\lib\site-packages\pip\download.py", line 41, i
n <module>
    from pip._vendor.requests.adapters import BaseAdapter, HTTPAdapter
ImportError: No module named 'pip._vendor.requests.adapters'
```

**Comment by akapocsi** [comment]
This is crippling my workflow.  Happy I exported and cloned my root env before upgrading to the latest "stable" version of anaconda.

**Comment by msarahan** [comment]
Please see https://github.com/ContinuumIO/anaconda-issues/issues/6456 for more info and possible resolution.

This change was made because pip nested their vendoring more deeply in recent releases.  In testing, we saw path length issues that broke things much worse than the issue you're seeing, and acted to remedy them by un-vendoring pip.  This works for clean installs, but highlights a buggy legacy package.  We can't fix the buggy legacy package - removing it always leaves the files that are causing issues.

**Comment by akapocsi** [comment]
Deleting "C:\Anaconda3\Lib\site-packages\pip\" and subsequently forcing a re-installation with "conda install pip -f" fixed the issue for me.

**Comment by Gabrielvon** [comment]
@akapocsi Thanks a lot! It works like a charm!

**Comment by Gabrielvon** [comment]
@msarahan I am hardly understanding the #6456 professionally but your comment explained the problems to me. I got the direct solution from @akapocsi . Thanks for answering though.

**Comment by msarahan** [comment]
Sure, no problem.  Sorry for not posting a more direct answer.  Thanks @akapocsi for posting better instructions.

**Comment by Mereep** [comment]
I have the same issue as the Threadstarter with the exception I am using Windows 10.

I also followed the instruction stated by @akapocsi . It did not succeed. I stumble from one mess to another trying to install tensorflow-gpu.

The whole workflow seems broken from a to z. 

![problems](https://user-images.githubusercontent.com/7294792/31852083-e4ef3dd2-b671-11e7-8324-6a672fb7328f.PNG)

**Comment by akapocsi** [comment]
@mereep Why did you delete pip.exe?

The instructions I posted above indicate that you need to delete a folder, not a file.

**Comment by akapocsi** [comment]
@mereep Try deleting "C:\Users\richard\Anaconda3\Lib\site-packages\pip" and subsequently forcing a re-installation with "conda install pip -f"

**Comment by dualvim** [comment]
@akapocsi you're a genius! I was facing the same problem of @Gabrielvon and reading the issue #6456 didn't help me (I'm a Python newbie).  These instructions solved my problems in less than 1 minute! Thank you!

**Comment by Mereep** [comment]
@akapocsi Yes, correct, I didn't notice that this is the site-package folder. And since the exe was recreated after that, I assumed it was the correct way. Thanks for that hint. Deleting the site-package node will actually work (partially).

While pip seems to at least start again, Installing packages (on my system) doesn't work still.

![pip_install_prob](https://user-images.githubusercontent.com/7294792/31884712-546e88a2-b7ee-11e7-9af9-6c44806bb6b9.PNG)

I also cannot upgrade pip itself using pip, since the error occurs then also. Should I open a ticket for that or does that look like a totally local problem?

**Comment by Gabrielvon** [comment]
close issue.

**Comment by malhotravasu** [comment]
Easy fix for windows users:
>easy_install requests

**Comment by lafftar** [comment]
thank you @malhotravasu

**Comment by Honghe** [comment]
FYI, 
- the Anaconda global Python site-package location is `C:\ProgramData\Anaconda3\Lib\site-packages`
- but the individual environment site-package location is `C:\Users\<user>\AppData\Roaming\Python\Python36\site-packages`

So after you deleted `pip` directory but something is still wrong, maybe you have deleted the wrong directory.

**Comment by Souhaib-fkr** [comment]
> easy_install requests

How do I fix the error?

**Comment by Souhaib-fkr** [comment]
How do I fix the error? ::

C:\Users\SouhaibFkr_Nitro5>pip
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\SouhaibFkr_Nitro5\AppData\Local\Programs\Python\Python311\Scripts\pip.exe\__main__.py", line 4, in <module>
  File "C:\Users\SouhaibFkr_Nitro5\AppData\Local\Programs\Python\Python311\Lib\site-packages\pip\_internal\cli\main.py", line 9, in <module>
    from pip._internal.cli.autocompletion import autocomplete
  File "C:\Users\SouhaibFkr_Nitro5\AppData\Local\Programs\Python\Python311\Lib\site-packages\pip\_internal\cli\autocompletion.py", line 10, in <module>
    from pip._internal.cli.main_parser import create_main_parser
  File "C:\Users\SouhaibFkr_Nitro5\AppData\Local\Programs\Python\Python311\Lib\site-packages\pip\_internal\cli\main_parser.py", line 9, in <module>
    from pip._internal.build_env import get_runnable_pip
  File "C:\Users\SouhaibFkr_Nitro5\AppData\Local\Programs\Python\Python311\Lib\site-packages\pip\_internal\build_env.py", line 20, in <module>
    from pip._internal.cli.spinners import open_spinner
  File "C:\Users\SouhaibFkr_Nitro5\AppData\Local\Programs\Python\Python311\Lib\site-packages\pip\_internal\cli\spinners.py", line 9, in <module>
    from pip._internal.utils.logging import get_indentation
  File "C:\Users\SouhaibFkr_Nitro5\AppData\Local\Programs\Python\Python311\Lib\site-packages\pip\_internal\utils\logging.py", line 29, in <module>
    from pip._internal.utils.misc import ensure_dir
  File "C:\Users\SouhaibFkr_Nitro5\AppData\Local\Programs\Python\Python311\Lib\site-packages\pip\_internal\utils\misc.py", line 37, in <module>
    from pip._vendor.pep517 import Pep517HookCaller
  File "C:\Users\SouhaibFkr_Nitro5\AppData\Local\Programs\Python\Python311\Lib\site-packages\pip\_vendor\pep517\__init__.py", line 6, in <module>
    from .wrappers import *  # noqa: F401, F403
    ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SouhaibFkr_Nitro5\AppData\Local\Programs\Python\Python311\Lib\site-packages\pip\_vendor\pep517\wrappers.py", line 11, in <module>
    from .in_process import _in_proc_script_path
ImportError: cannot import name '_in_proc_script_path' from 'pip._vendor.pep517.in_process' (unknown location)
