### ISSUE TITLE
caffe needs to pin protobuf requirement to version 

### ISSUE THREAD

**Issue by jjhelmus** [ContinuumIO/anaconda-issues#6733]
The `caffe` and `caffe-gpu` package in `defaults` has a requirement on protobuf without any version dependencies.  Unfortunately, the caffe packages links to libprotobuf.so.12 which is provided by the protbuf version 3.2.0:

```
~$ conda create -n caffe python=3.6 caffe
Fetching package metadata ...........
Solving package specifications: .

Package plan for installation in environment /home/jhelmus/anaconda3/envs/caffe:

The following NEW packages will be INSTALLED:

    bokeh:            0.12.10-py36hbb0e44a_0     defaults
...
    caffe:            1.0.0rc5-np112py36_0       defaults
...
    protobuf:         3.4.0-py36_0               defaults
...
~$ source activate caffe
(caffe) ~$ python -c "import caffe"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/jhelmus/anaconda3/envs/caffe/lib/python3.6/site-packages/caffe/__init__.py", line 1, in <module>
    from .pycaffe import Net, SGDSolver, NesterovSolver, AdaGradSolver, RMSPropSolver, AdaDeltaSolver, AdamSolver, NCCL, Timer
  File "/home/jhelmus/anaconda3/envs/caffe/lib/python3.6/site-packages/caffe/pycaffe.py", line 13, in <module>
    from ._caffe import Net, SGDSolver, NesterovSolver, AdaGradSolver, \
ImportError: libprotobuf.so.12: cannot open shared object file: No such file or directory
(caffe) ~$ 
(caffe) ~$ lddtree ~/anaconda3/envs/caffe/lib/libcaffe.so.1.0.0-rc5 
libcaffe.so.1.0.0-rc5 => /home/jhelmus/anaconda3/envs/caffe/lib/libcaffe.so.1.0.0-rc5 (interpreter => none)
    libboost_system.so.1.61.0 => /home/jhelmus/anaconda3/envs/caffe/lib/./libboost_system.so.1.61.0
    libboost_thread.so.1.61.0 => /home/jhelmus/anaconda3/envs/caffe/lib/./libboost_thread.so.1.61.0
    libboost_filesystem.so.1.61.0 => /home/jhelmus/anaconda3/envs/caffe/lib/./libboost_filesystem.so.1.61.0
    libboost_chrono.so.1.61.0 => /home/jhelmus/anaconda3/envs/caffe/lib/./libboost_chrono.so.1.61.0
    libboost_date_time.so.1.61.0 => /home/jhelmus/anaconda3/envs/caffe/lib/./libboost_date_time.so.1.61.0
    libboost_atomic.so.1.61.0 => /home/jhelmus/anaconda3/envs/caffe/lib/./libboost_atomic.so.1.61.0
    libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0
        ld-linux-x86-64.so.2 => /lib/x86_64-linux-gnu/ld-linux-x86-64.so.2
    libglog.so.0 => /home/jhelmus/anaconda3/envs/caffe/lib/./libglog.so.0
    libgflags.so.2 => /home/jhelmus/anaconda3/envs/caffe/lib/./libgflags.so.2
    libprotobuf.so.12 => not found
    libhdf5_cpp.so.12 => /home/jhelmus/anaconda3/envs/caffe/lib/./libhdf5_cpp.so.12
    libhdf5.so.10 => /home/jhelmus/anaconda3/envs/caffe/lib/./libhdf5.so.10
    librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1
    libz.so.1 => /home/jhelmus/anaconda3/envs/caffe/lib/./libz.so.1
    libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2
    libhdf5_hl_cpp.so.11 => /home/jhelmus/anaconda3/envs/caffe/lib/./libhdf5_hl_cpp.so.11
    libhdf5_hl.so.10 => /home/jhelmus/anaconda3/envs/caffe/lib/./libhdf5_hl.so.10
    liblmdb.so => /home/jhelmus/anaconda3/envs/caffe/lib/./liblmdb.so
    libleveldb.so.1 => /home/jhelmus/anaconda3/envs/caffe/lib/./libleveldb.so.1
    libsnappy.so.1 => /home/jhelmus/anaconda3/envs/caffe/lib/./libsnappy.so.1
    libopencv_highgui.so.3.1 => /home/jhelmus/anaconda3/envs/caffe/lib/./libopencv_highgui.so.3.1
        libopencv_videoio.so.3.1 => /home/jhelmus/anaconda3/envs/caffe/lib/././libopencv_videoio.so.3.1
        libgomp.so.1 => /home/jhelmus/anaconda3/envs/caffe/lib/././libgomp.so.1
    libmkl_rt.so => /home/jhelmus/anaconda3/envs/caffe/lib/./libmkl_rt.so
    libpython3.6m.so.1.0 => /home/jhelmus/anaconda3/envs/caffe/lib/./libpython3.6m.so.1.0
        libutil.so.1 => /lib/x86_64-linux-gnu/libutil.so.1
    libboost_python.so.1.61.0 => /home/jhelmus/anaconda3/envs/caffe/lib/./libboost_python.so.1.61.0
    libopencv_imgcodecs.so.3.1 => /home/jhelmus/anaconda3/envs/caffe/lib/./libopencv_imgcodecs.so.3.1
        libjpeg.so.8 => /home/jhelmus/anaconda3/envs/caffe/lib/././libjpeg.so.8
        libpng16.so.16 => /home/jhelmus/anaconda3/envs/caffe/lib/././libpng16.so.16
        libtiff.so.5 => /home/jhelmus/anaconda3/envs/caffe/lib/././libtiff.so.5
            liblzma.so.5 => /home/jhelmus/anaconda3/envs/caffe/lib/./././liblzma.so.5
    libopencv_imgproc.so.3.1 => /home/jhelmus/anaconda3/envs/caffe/lib/./libopencv_imgproc.so.3.1
    libopencv_core.so.3.1 => /home/jhelmus/anaconda3/envs/caffe/lib/./libopencv_core.so.3.1
    libstdc++.so.6 => /home/jhelmus/anaconda3/envs/caffe/lib/./libstdc++.so.6
    libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6
    libgcc_s.so.1 => /home/jhelmus/anaconda3/envs/caffe/lib/./libgcc_s.so.1
    libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6
(caffe) ~$ conda install protobuf=3.2
Fetching package metadata ...........
Solving package specifications: .

Package plan for installation in environment /home/jhelmus/anaconda3/envs/caffe:

The following packages will be DOWNGRADED:

    libprotobuf: 3.4.0-0      defaults --> 3.2.0-0      defaults
    protobuf:    3.4.0-py36_0 defaults --> 3.2.0-py36_0 defaults

Proceed ([y]/n)? y

(caffe) ~$ python -c "import caffe"
(caffe) ~$
(caffe) ~$ lddtree ~/anaconda3/envs/caffe/lib/libcaffe.so.1.0.0-rc5 
libcaffe.so.1.0.0-rc5 => /home/jhelmus/anaconda3/envs/caffe/lib/libcaffe.so.1.0.0-rc5 (interpreter => none)
    libboost_system.so.1.61.0 => /home/jhelmus/anaconda3/envs/caffe/lib/./libboost_system.so.1.61.0
    libboost_thread.so.1.61.0 => /home/jhelmus/anaconda3/envs/caffe/lib/./libboost_thread.so.1.61.0
    libboost_filesystem.so.1.61.0 => /home/jhelmus/anaconda3/envs/caffe/lib/./libboost_filesystem.so.1.61.0
    libboost_chrono.so.1.61.0 => /home/jhelmus/anaconda3/envs/caffe/lib/./libboost_chrono.so.1.61.0
    libboost_date_time.so.1.61.0 => /home/jhelmus/anaconda3/envs/caffe/lib/./libboost_date_time.so.1.61.0
    libboost_atomic.so.1.61.0 => /home/jhelmus/anaconda3/envs/caffe/lib/./libboost_atomic.so.1.61.0
    libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0
        ld-linux-x86-64.so.2 => /lib/x86_64-linux-gnu/ld-linux-x86-64.so.2
    libglog.so.0 => /home/jhelmus/anaconda3/envs/caffe/lib/./libglog.so.0
    libgflags.so.2 => /home/jhelmus/anaconda3/envs/caffe/lib/./libgflags.so.2
    libprotobuf.so.12 => /home/jhelmus/anaconda3/envs/caffe/lib/./libprotobuf.so.12
    libhdf5_cpp.so.12 => /home/jhelmus/anaconda3/envs/caffe/lib/./libhdf5_cpp.so.12
    libhdf5.so.10 => /home/jhelmus/anaconda3/envs/caffe/lib/./libhdf5.so.10
    librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1
    libz.so.1 => /home/jhelmus/anaconda3/envs/caffe/lib/./libz.so.1
    libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2
    libhdf5_hl_cpp.so.11 => /home/jhelmus/anaconda3/envs/caffe/lib/./libhdf5_hl_cpp.so.11
    libhdf5_hl.so.10 => /home/jhelmus/anaconda3/envs/caffe/lib/./libhdf5_hl.so.10
    liblmdb.so => /home/jhelmus/anaconda3/envs/caffe/lib/./liblmdb.so
    libleveldb.so.1 => /home/jhelmus/anaconda3/envs/caffe/lib/./libleveldb.so.1
    libsnappy.so.1 => /home/jhelmus/anaconda3/envs/caffe/lib/./libsnappy.so.1
    libopencv_highgui.so.3.1 => /home/jhelmus/anaconda3/envs/caffe/lib/./libopencv_highgui.so.3.1
        libopencv_videoio.so.3.1 => /home/jhelmus/anaconda3/envs/caffe/lib/././libopencv_videoio.so.3.1
        libgomp.so.1 => /home/jhelmus/anaconda3/envs/caffe/lib/././libgomp.so.1
    libmkl_rt.so => /home/jhelmus/anaconda3/envs/caffe/lib/./libmkl_rt.so
    libpython3.6m.so.1.0 => /home/jhelmus/anaconda3/envs/caffe/lib/./libpython3.6m.so.1.0
        libutil.so.1 => /lib/x86_64-linux-gnu/libutil.so.1
    libboost_python.so.1.61.0 => /home/jhelmus/anaconda3/envs/caffe/lib/./libboost_python.so.1.61.0
    libopencv_imgcodecs.so.3.1 => /home/jhelmus/anaconda3/envs/caffe/lib/./libopencv_imgcodecs.so.3.1
        libjpeg.so.8 => /home/jhelmus/anaconda3/envs/caffe/lib/././libjpeg.so.8
        libpng16.so.16 => /home/jhelmus/anaconda3/envs/caffe/lib/././libpng16.so.16
        libtiff.so.5 => /home/jhelmus/anaconda3/envs/caffe/lib/././libtiff.so.5
            liblzma.so.5 => /home/jhelmus/anaconda3/envs/caffe/lib/./././liblzma.so.5
    libopencv_imgproc.so.3.1 => /home/jhelmus/anaconda3/envs/caffe/lib/./libopencv_imgproc.so.3.1
    libopencv_core.so.3.1 => /home/jhelmus/anaconda3/envs/caffe/lib/./libopencv_core.so.3.1
    libstdc++.so.6 => /home/jhelmus/anaconda3/envs/caffe/lib/./libstdc++.so.6
    libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6
    libgcc_s.so.1 => /home/jhelmus/anaconda3/envs/caffe/lib/./libgcc_s.so.1
    libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6
```
From the above linkages it appears as if the `python-gflags` and `leveldb` requirement should also be pinned to compatible versions.

All of this could be done by adjusting the requirements in `repodata.json` but updating caffe to 1.0.0 and releasing new packages is likely more efficient.

**Comment by 183amir** [comment]
@jjhelmus we are facing the same issue. The issue also appears when you want to install the latest caffe `1.0.0rc5` and tensorflow `1.3.0` in the same environment. So is it possible to make their dependencies compatible too? i.e. use the same protobuf version in both.

**Comment by jjhelmus** [comment]
@183amir I don't believe it is possible to have working `caffe 1.0.0rc5` and `tensorflow 1.3.0` packages in the same environment at the moment.  As indicated above `caffe 1.0.0rc5` requires protobuf 3.2.0 to work properly where as tensorflow requires protobuf >=3.3.0.  A new build of caffe against a more recent protobuf should allow both packages to be installed and work in an environment.

**Comment by 183amir** [comment]
@jjhelmus any recent version of caffe compatible with tensorflow 1.3.0 would suffice my needs.
I do not see in caffe's installation instructions that it needs protobuf 3.2.0. I think it compiles with any protobuf 3 version.

Maybe I should have formed my question like this: Could you please release a new caffe package with a protobuff version that is compatible with tensorflow 1.3.0?

**Comment by jjhelmus** [comment]
> Could you please release a new caffe package with a protobuff version that is compatible with tensorflow 1.3.0?

Yes, it is on my agenda, hopefully by the end of the week.

**Comment by tiagofrepereira2012** [comment]
Hi, any news about this one?

Thanks

**Comment by jjhelmus** [comment]
An updated caffe is still in the works.  Converting the caffe dependencies, especially protobuf, to use the new compilers in Anaconda 5 has taken longer than expected.

**Comment by ijstokes** [comment]
I got part way to resolving this by doing `conda install protobuf=3.2`.  Following that I got rid of the `libprotobuf.so.12 not found` error and traded it in for:

```
$ caffe
caffe: symbol lookup error: caffe: undefined symbol: _ZN6google14FlagRegistererC1EPKcS2_S2_S2_PvS3_
```

**Comment by jjhelmus** [comment]
Try `conda install gflags=2.1`.  That resolved the undefined symbols for me.

**Comment by ijstokes** [comment]
Thanks! sounds like the path to success with `caffe` using conda packages is something like:

```
conda create -n caffe -c conda-forge python=3.6 caffe protobuf=3.2 gflags=2.1`
```

**Comment by csoja** [comment]
@ijstokes  Is the version of caffe in defaults not working for you?  (I notice you are getting it from the conda-forge channel)

**Comment by jjhelmus** [comment]
The caffe 1.0 package released on January 5, 2018 correctly express their requirements and depend on libprotobuf 3.4.1.  These should be compatible with Tensorflow 1.3.0 in `defaults`.

Sorry for the long time it took to get these out.  A number of Caffe dependencies needed to be rebuilt which took considerable time.

A new `caffe-gpu` package is still in progress.  A new compiler toolchain is needed to meet both the CUDA and C++11 ABI requirements.

**Comment by jjhelmus** [comment]
`caffe-gpu` packages with the correct requirements are now available in `default`.
