### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by hiteshnitetc** [ContinuumIO/anaconda-issues#6778]
## Main error
Application <b>spyder</b> launch may have produced errors.
## Traceback
```
Traceback (most recent call last):
  File "/home/nd/anaconda3/lib/python3.6/site-packages/spyder/app/mainwindow.py", line 3093, in main
    mainwindow = run_spyder(app, options, args)
  File "/home/nd/anaconda3/lib/python3.6/site-packages/spyder/app/mainwindow.py", line 2995, in run_spyder
    main.setup()
  File "/home/nd/anaconda3/lib/python3.6/site-packages/spyder/app/mainwindow.py", line 847, in setup
    from spyder.plugins.editor import Editor
  File "/home/nd/anaconda3/lib/python3.6/site-packages/spyder/plugins/editor.py", line 41, in <module>
    from spyder.utils.introspection.manager import IntrospectionManager
  File "/home/nd/anaconda3/lib/python3.6/site-packages/spyder/utils/introspection/manager.py", line 21, in <module>
    from spyder.utils.introspection.plugin_client import PluginClient
  File "/home/nd/anaconda3/lib/python3.6/site-packages/spyder/utils/introspection/plugin_client.py", line 18, in <module>
    import zmq
  File "/home/nd/anaconda3/lib/python3.6/site-packages/zmq/__init__.py", line 49, in <module>
    _libzmq = ctypes.CDLL(bundled[0], mode=ctypes.RTLD_GLOBAL)
  File "/home/nd/anaconda3/lib/python3.6/ctypes/__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /home/nd/anaconda3/lib/python3.6/site-packages/zmq/libzmq.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZTVNSt7__cxx1118basic_stringstreamIcSt11char_traitsIcESaIcEEE

```
## System information
```
python: 3.6.1
language: en_IN
os: Linux;4.10.0-37-generic;#41~16.04.1-Ubuntu SMP Fri Oct 6 22:42:59 UTC 2017;x86_64;x86_64
version: 1.6.2
platform: linux-64
qt: 5.6.2
pyqt: 5.6.0
conda: 4.3.29
```

**Comment by hiteshnitetc** [comment]
The problem got resolved by `conda install libgcc`. 
Thanks!
