### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by Raj800** [ContinuumIO/anaconda-issues#6780]
## Main error
Application <b>notebook</b> launch may have produced errors.
## Traceback
```
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\notebook\services\sessions\sessionmanager.py", line 10, in <module>
    import sqlite3
  File "C:\ProgramData\Anaconda3\lib\sqlite3\__init__.py", line 23, in <module>
    from sqlite3.dbapi2 import *
ModuleNotFoundError: No module named 'sqlite3.dbapi2'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\Scripts\jupyter-notebook-script.py", line 6, in <module>
    from notebook.notebookapp import main
  File "C:\ProgramData\Anaconda3\lib\site-packages\notebook\notebookapp.py", line 79, in <module>
    from .services.sessions.sessionmanager import SessionManager
  File "C:\ProgramData\Anaconda3\lib\site-packages\notebook\services\sessions\sessionmanager.py", line 13, in <module>
    from pysqlite2 import dbapi2 as sqlite3
ModuleNotFoundError: No module named 'pysqlite2'

```
## System information
```
python: 3.6.1
language: en_IN
os: Windows;10;10.0.16299;AMD64;Intel64 Family 6 Model 37 Stepping 5, GenuineIntel
version: 1.6.2
platform: win-64
qt: 5.6.2
pyqt: 5.6.0
conda: 4.3.27
```

**Comment by Raj800** [comment]
Sir, Please help. If this question is already answered somewhere else, then please let me know. I was not able to find solution for it.

**Comment by goanpeca** [comment]
@Raj800 it seems you installed Anaconda for all users, I encourage you to reinstall the latest version of anaconda (5.0)  for the current user onlly
