### ISSUE TITLE
unable to open anaconda

### ISSUE THREAD

**Issue by 33bolla** [ContinuumIO/anaconda-issues#6793]
Report

Please report this issue in the anaconda  issue tracker  

Main Error

unacceptable character #x0000: special characters are not allowed
  in "C:\Users\Utente\AppData\Local\ContinuumIO\binstar\config.yaml", position 0

Traceback

Traceback (most recent call last):
  File "C:\Users\Utente\Anaconda3\lib\site-packages\anaconda_navigator\exceptions.py", line 75, in exception_handler
    return_value = func(*args, **kwargs)
  File "C:\Users\Utente\Anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 120, in start_app
    window = run_app(splash)
  File "C:\Users\Utente\Anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 63, in run_app
    window = MainWindow(splash=splash)
  File "C:\Users\Utente\Anaconda3\lib\site-packages\anaconda_navigator\widgets\main_window.py", line 160, in __init__
    self.api = AnacondaAPI()
  File "C:\Users\Utente\Anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 1258, in AnacondaAPI
    ANACONDA_API = _AnacondaAPI()
  File "C:\Users\Utente\Anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 71, in __init__
    self._client_api = ClientAPI()
  File "C:\Users\Utente\Anaconda3\lib\site-packages\anaconda_navigator\api\client_api.py", line 612, in ClientAPI
    CLIENT_API = _ClientAPI()
  File "C:\Users\Utente\Anaconda3\lib\site-packages\anaconda_navigator\api\client_api.py", line 82, in __init__
    log_level=logging.NOTSET
  File "C:\Users\Utente\Anaconda3\lib\site-packages\binstar_client\utils\config.py", line 94, in get_server_api
    config = get_config(remote_site=site)
  File "C:\Users\Utente\Anaconda3\lib\site-packages\binstar_client\utils\config.py", line 228, in get_config
    file_configs = load_file_configs(SEARCH_PATH)
  File "C:\Users\Utente\Anaconda3\lib\site-packages\binstar_client\utils\config.py", line 222, in load_file_configs
    raw_data = collections.OrderedDict(kv for kv in itertools.chain.from_iterable(load_paths))
  File "C:\Users\Utente\Anaconda3\lib\site-packages\binstar_client\utils\config.py", line 222, in 
    raw_data = collections.OrderedDict(kv for kv in itertools.chain.from_iterable(load_paths))
  File "C:\Users\Utente\Anaconda3\lib\site-packages\binstar_client\utils\config.py", line 202, in _dir_yaml_loader
    yield filepath, load_config(filepath)
  File "C:\Users\Utente\Anaconda3\lib\site-packages\binstar_client\utils\config.py", line 186, in load_config
    data = yaml.load(fd)
  File "C:\Users\Utente\Anaconda3\lib\site-packages\yaml\__init__.py", line 70, in load
    loader = Loader(stream)
  File "C:\Users\Utente\Anaconda3\lib\site-packages\yaml\loader.py", line 34, in __init__
    Reader.__init__(self, stream)
  File "C:\Users\Utente\Anaconda3\lib\site-packages\yaml\reader.py", line 85, in __init__
    self.determine_encoding()
  File "C:\Users\Utente\Anaconda3\lib\site-packages\yaml\reader.py", line 135, in determine_encoding
    self.update(1)
  File "C:\Users\Utente\Anaconda3\lib\site-packages\yaml\reader.py", line 169, in update
    self.check_printable(data)
  File "C:\Users\Utente\Anaconda3\lib\site-packages\yaml\reader.py", line 144, in check_printable
    'unicode', "special characters are not allowed")
yaml.reader.ReaderError: unacceptable character #x0000: special characters are not allowed
  in "C:\Users\Utente\AppData\Local\ContinuumIO\binstar\config.yaml", position 0

Thanks!

**Comment by goanpeca** [comment]
@33bolla please delete this file `C:\Users\Utente\AppData\Local\ContinuumIO\binstar\config.yaml` and try again

**Comment by 33bolla** [comment]
Thank you !
________________________________

**Comment by ddivittorio** [comment]
Thank you!
