### ISSUE TITLE
Spaces between end of path and path delimiter cause FileNotFoundError when running anaconda in Windows

### ISSUE THREAD

**Issue by jaminsore** [ContinuumIO/anaconda-issues#680]
When running an anaconda command (e.g., `anaconda --help`), I am getting a `FileNoteFoundError`.  I found the issue is that I had a space between the end of a path in my `PATH` and the path delimiter.  This is caused by a known inconsistency in the behavior of `os.listdir()` and `os.ispath()` or `os.path.exists()`.  

I tracked this down to `binstar_build_client.utils`.

```
python -c "from binstar_build_client.utils import get_conda_root_prefix; print(get_conda_root_prefix())"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Anaconda3\lib\site-packages\binstar_build_client\utils\__init__.py", line 11, in get_conda_root_prefix
    if os.path.isdir(entry) and CONDA_EXE in os.listdir(entry):
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'C:\\Program Files (x86)\\Common Files\\lenovo\\easyplussdk\\bin '
```

Here is my `conda info` output

```

Using Anaconda Cloud api site https://api.anaconda.org
Current conda install:

             platform : win-64
        conda version : 3.19.3
  conda-build version : 1.19.0
       python version : 3.5.1.final.0
     requests version : 2.9.1
     root environment : C:\Anaconda3  (writable)
  default environment : C:\Anaconda3
     envs directories : C:\Anaconda3\envs
        package cache : C:\Anaconda3\pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/win-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/win-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : None
    is foreign system : False

```

Changing  `binstar_build_client.utils.get_conda_root_prefix()` to 

```
def get_conda_root_prefix():

    for entry in os.environ.get('PATH').split(os.pathsep):
        entry = entry.strip()
        if os.path.isdir(entry) and CONDA_EXE in os.listdir(entry):
            conda_exe_path = os.path.realpath(os.path.join(entry, 'conda'))
            bin_dir = os.path.dirname(conda_exe_path)
            return os.path.dirname(bin_dir)
```

Fixes the issue.

**Comment by goanpeca** [comment]
Tracked at https://github.com/Anaconda-Platform/anaconda-client/issues/410
