### ISSUE TITLE
Invalid path issue

### ISSUE THREAD

**Issue by CaptainCapitalizm** [ContinuumIO/anaconda-issues#6814]
Hey, so I'm new to anaconda and I keep getting this error whenever I try to download a new package or to even update conda on my Windows machine:

``$ C:\Users\Adrian\Anaconda3\Scripts\conda update conda`

    Traceback (most recent call last):
      File "C:\Users\Adrian\Anaconda3\lib\site-packages\conda\exceptions.py", line 640, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "C:\Users\Adrian\Anaconda3\lib\site-packages\conda\cli\main.py", line 140, in _main
        exit_code = args.func(args, p)
      File "C:\Users\Adrian\Anaconda3\lib\site-packages\conda\cli\main_update.py", line 65, in execute
        install(args, parser, 'update')
      File "C:\Users\Adrian\Anaconda3\lib\site-packages\conda\cli\install.py", line 231, in install
        unknown=index_args['unknown'], prefix=prefix)
      File "C:\Users\Adrian\Anaconda3\lib\site-packages\conda\core\index.py", line 101, in get_index
        index = fetch_index(channel_priority_map, use_cache=use_cache)
      File "C:\Users\Adrian\Anaconda3\lib\site-packages\conda\core\index.py", line 120, in fetch_index
        repodatas = collect_all_repodata(use_cache, tasks)
      File "C:\Users\Adrian\Anaconda3\lib\site-packages\conda\core\repodata.py", line 75, in collect_all_repodata
        repodatas = _collect_repodatas_serial(use_cache, tasks)
      File "C:\Users\Adrian\Anaconda3\lib\site-packages\conda\core\repodata.py", line 485, in _collect_repodatas_serial
        for url, schan, pri in tasks]
      File "C:\Users\Adrian\Anaconda3\lib\site-packages\conda\core\repodata.py", line 485, in <listcomp>
        for url, schan, pri in tasks]
      File "C:\Users\Adrian\Anaconda3\lib\site-packages\conda\core\repodata.py", line 115, in func
        res = f(*args, **kwargs)
      File "C:\Users\Adrian\Anaconda3\lib\site-packages\conda\core\repodata.py", line 464, in fetch_repodata
        mod_etag_headers.get('_mod'))
      File "C:\Users\Adrian\Anaconda3\lib\site-packages\conda\core\repodata.py", line 144, in fetch_repodata_remote_request
        timeout=timeout)
      File "C:\Users\Adrian\Anaconda3\lib\site-packages\requests\sessions.py", line 521, in get
        return self.request('GET', url, **kwargs)
      File "C:\Users\Adrian\Anaconda3\lib\site-packages\requests\sessions.py", line 508, in request
        resp = self.send(prep, **send_kwargs)
      File "C:\Users\Adrian\Anaconda3\lib\site-packages\requests\sessions.py", line 618, in send
        r = adapter.send(request, **kwargs)
      File "C:\Users\Adrian\Anaconda3\lib\site-packages\requests\adapters.py", line 407, in send
        self.cert_verify(conn, request.url, verify, cert)
      File "C:\Users\Adrian\Anaconda3\lib\site-packages\requests\adapters.py", line 226, in cert_verify
        "invalid path: {0}".format(cert_loc))
    OSError: Could not find a suitable TLS CA certificate bundle, invalid path: C:\Program Files\Total Defense\Internet Security Suite\Anti-Phishing`

So, I know that the issue lies in the fact that anaconda is calling upon that Total Defense file in Program Files. However, that file doesn't exist. I uninstalled Total Defense a long time ago so I have no idea why anaconda is calling upon it since I just recently installed it. 

Any help would be much appreciated.

**Comment by msarahan** [comment]
Total Defense set an environment variable that Anaconda is looking at.  Total Defense didn't restore the original value or unset that variable when you uninstalled it.  You'll need to figure out which variable is pointing to that location and clear it.

Closing, as this is not an anaconda issue - we're the victims of Total Defense not behaving here.
