### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by hongyu89** [ContinuumIO/anaconda-issues#6836]
## Main error
Application <b>spyder</b> launch may have produced errors.
## Traceback
```
Traceback (most recent call last):
  File "/Users/hyu/anaconda/envs/carnd-term1/bin/spyder", line 7, in <module>
    from spyder.app.start import main
  File "/Users/hyu/anaconda/envs/carnd-term1/lib/python3.5/site-packages/spyder/app/start.py", line 13, in <module>
    import zmq
  File "/Users/hyu/anaconda/envs/carnd-term1/lib/python3.5/site-packages/zmq/__init__.py", line 34, in <module>
    from zmq import backend
  File "/Users/hyu/anaconda/envs/carnd-term1/lib/python3.5/site-packages/zmq/backend/__init__.py", line 21, in <module>
    if platform.python_implementation() == 'PyPy':
  File "/Users/hyu/anaconda/envs/carnd-term1/lib/python3.5/platform.py", line 1292, in python_implementation
    return _sys_version()[0]
  File "/Users/hyu/anaconda/envs/carnd-term1/lib/python3.5/platform.py", line 1252, in _sys_version
    repr(sys_version))
ValueError: failed to parse CPython sys.version: '3.5.4 |Anaconda, Inc.| (default, Oct  5 2017, 02:58:14) \n[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)]'

```
## System information
```
python: 3.6.1
language: en
os: Darwin;16.7.0;Darwin Kernel Version 16.7.0: Thu Jun 15 17:36:27 PDT 2017; root:xnu-3789.70.16~2/RELEASE_X86_64;x86_64;i386
version: 1.6.2
platform: osx-64
qt: 5.6.2
pyqt: 5.6.0
conda: 4.3.29
```

**Comment by goanpeca** [comment]
@hongyu89 could you update to the latest anaconda?
