### ISSUE TITLE
Attributeerror: '_namespacepath' object has no attribute 'sort'

### ISSUE THREAD

**Issue by Aisuko** [ContinuumIO/anaconda-issues#6847]
I downloaded Anaconda3 and create new enviroment env_python36_for_dl , when i open terminal input `pip`, the error appear as

```
Traceback (most recent call last):
  File "C:\Users\Yurak\AppData\Local\conda\conda\envs\env_python36_for_dl\Scripts\pip-script.py", line 3, in <module>
    import pip
  File "C:\Users\Yurak\AppData\Local\conda\conda\envs\env_python36_for_dl\lib\site-packages\pip\__init__.py", line 26, in <module>
    from pip.utils import get_installed_distributions, get_prog
  File "C:\Users\Yurak\AppData\Local\conda\conda\envs\env_python36_for_dl\lib\site-packages\pip\utils\__init__.py", line 27, in <module>
    from pip._vendor import pkg_resources
  File "C:\Users\Yurak\AppData\Local\conda\conda\envs\env_python36_for_dl\lib\site-packages\pip\_vendor\pkg_resources\__init__.py", line 3018, in <module>
    @_call_aside
  File "C:\Users\Yurak\AppData\Local\conda\conda\envs\env_python36_for_dl\lib\site-packages\pip\_vendor\pkg_resources\__init__.py", line 3004, in _call_aside
    f(*args, **kwargs)
  File "C:\Users\Yurak\AppData\Local\conda\conda\envs\env_python36_for_dl\lib\site-packages\pip\_vendor\pkg_resources\__init__.py", line 3046, in _initialize_master_working_set
    dist.activate(replace=False)
  File "C:\Users\Yurak\AppData\Local\conda\conda\envs\env_python36_for_dl\lib\site-packages\pip\_vendor\pkg_resources\__init__.py", line 2578, in activate
    declare_namespace(pkg)
  File "C:\Users\Yurak\AppData\Local\conda\conda\envs\env_python36_for_dl\lib\site-packages\pip\_vendor\pkg_resources\__init__.py", line 2152, in declare_namespace
    _handle_ns(packageName, path_item)
  File "C:\Users\Yurak\AppData\Local\conda\conda\envs\env_python36_for_dl\lib\site-packages\pip\_vendor\pkg_resources\__init__.py", line 2092, in _handle_ns
    _rebuild_mod_path(path, packageName, module)
  File "C:\Users\Yurak\AppData\Local\conda\conda\envs\env_python36_for_dl\lib\site-packages\pip\_vendor\pkg_resources\__init__.py", line 2121, in _rebuild_mod_path
    orig_path.sort(key=position_in_sys_path)
AttributeError: '_NamespacePath' object has no attribute 'sort'
```
I had set up `pip` and `setuptools`  `tensorflow` with Anaconda3.

If i open Anaconda3 `root environment` in terminal , pip work properly.

**Comment by Aisuko** [comment]
I have a solutions:
1, First open  `Anaconda Navigator` , and install 'setuptools'
2, open `Anaconda prompt` and input 'easy_install pip'

`pip` work properly
