### ISSUE TITLE
SNIMissingWarning with fresh Anaconda install and conda 4.0.0

### ISSUE THREAD

**Issue by pzwang** [ContinuumIO/anaconda-issues#685]
I just did a fresh install of Anaconda 1.8.0 on my Windows 7 (64-bit) VM, followed by a "conda update conda".  This puts me at `conda=4.0.0`.

While trying to install Jupyter and Jupyter Notebook, I get the following errors:

```
D:\src>conda install jupyter jupyter-notebook
Fetching package metadata: C:\Users\pwang\Anaconda\lib\site-packages\requests\packages\urllib3\util\ssl_.py:315: SNIMissingWarning:
An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may c
ause the server to present an incorrect TLS certificate, which can cause validation failures. For more information, see https://urll
ib3.readthedocs.org/en/latest/security.html#snimissingwarning.
  SNIMissingWarning
C:\Users\pwang\Anaconda\lib\site-packages\requests\packages\urllib3\util\ssl_.py:120: InsecurePlatformWarning: A true SSLContext obj
ect is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For mo
re information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
....
An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.


Traceback (most recent call last):
  File "C:\Users\pwang\Anaconda\Scripts\conda-script.py", line 5, in <module>
    sys.exit(main())
  File "C:\Users\pwang\Anaconda\lib\site-packages\conda\cli\main.py", line 139, in main
    args_func(args, p)
  File "C:\Users\pwang\Anaconda\lib\site-packages\conda\cli\main.py", line 146, in args_func
    args.func(args, p)
  File "C:\Users\pwang\Anaconda\lib\site-packages\conda\cli\main_install.py", line 45, in execute
    install.install(args, parser, 'install')
  File "C:\Users\pwang\Anaconda\lib\site-packages\conda\cli\install.py", line 334, in install
    update_deps=args.update_deps)
  File "C:\Users\pwang\Anaconda\lib\site-packages\conda\plan.py", line 413, in install_actions
    pkgs = r.install(specs, [d + '.tar.bz2' for d in linked], update_deps=update_deps)
  File "C:\Users\pwang\Anaconda\lib\site-packages\conda\resolve.py", line 858, in install
    specs, preserve = self.install_specs(specs, installed or [], update_deps)
  File "C:\Users\pwang\Anaconda\lib\site-packages\conda\resolve.py", line 839, in install_specs
    limit, preserve = self.bad_installed(installed, specs)
  File "C:\Users\pwang\Anaconda\lib\site-packages\conda\resolve.py", line 807, in bad_installed
    solution = C.sat(constraints)
  File "C:\Users\pwang\Anaconda\lib\site-packages\conda\logic.py", line 422, in sat
    solution = pycosat.solve(clauses, vars=self.m, prop_limit=limit)
TypeError: list expected

D:\src>
```

So, of course, the most pressing issue for me is the SNIMissingWarning.  But I'm also perplexed by the `TypeError` in logic.py:422.  I guess `self.m` somehow gets borked when this exception happens?

**Comment by pzwang** [comment]
To be clear, I'm not quite sure how I ended up with the Anaconda 1.8.0 installer, I guess that's what I had laying around on my VM.  I could have sworn I downloaded a new installer today off of the Continuum website, but now all those links seem to return Anaconda-2.5.0 installers (as they should).  But, OTOH I don't know how much of this issue is related to that.  I'm doing an uninstall of 1.8.0 and installing 2.5.0 now...

**Comment by stereomax** [comment]
conda 4.0.0 tries to downgrade Anaconda on two of my Windows 7 machines (both Dell desktops) from 2.5.0/2.1.0 to 1.8.0 when I do a "conda update anaconda". I don't know why. On my Windows 7 laptop conda 4.0.0 is fine with Anaconda 2.5.0
