### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by HenryBiko** [ContinuumIO/anaconda-issues#6901]
## Main error
Application <b>spyder</b> launch may have produced errors.
## Traceback
```
Traceback (most recent call last):
  File "D:\Downloads\lib\site-packages\spyder\app\mainwindow.py", line 3099, in main
    mainwindow = run_spyder(app, options, args)
  File "D:\Downloads\lib\site-packages\spyder\app\mainwindow.py", line 3011, in run_spyder
    main.post_visible_setup()
  File "D:\Downloads\lib\site-packages\spyder\app\mainwindow.py", line 1269, in post_visible_setup
    self.historylog.add_history(get_conf_path('history.py'))
  File "D:\Downloads\lib\site-packages\spyder\plugins\history.py", line 232, in add_history
    text, _ = encoding.read(filename)
  File "D:\Downloads\lib\site-packages\spyder\utils\encoding.py", line 243, in read
    text, encoding = decode( open(filename, 'rb').read() )
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\HenryBiko\\.spyder-py3\\history.py'

```
## System information
```
python: 3.6.1
language: en_GB
os: Windows;10;10.0.15063;AMD64;Intel64 Family 6 Model 158 Stepping 9, GenuineIntel
version: 1.6.2
platform: win-64
qt: 5.6.2
pyqt: 5.6.0
conda: 4.3.30
```

**Comment by goanpeca** [comment]
@ccordoba12 ?

**Comment by goanpeca** [comment]
Try removing this folder `'C:\\Users\\HenryBiko\\.spyder-py3\\`
