### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by kevinzhang2016** [ContinuumIO/anaconda-issues#6957]
## Main error
Application <b>notebook</b> launch may have produced errors.
## Traceback
```
[E 15:20:03.092 NotebookApp] Exception while loading config file C:\Users\ztk\.jupyter\jupyter_notebook_config.py
    Traceback (most recent call last):
      File "C:\ProgramData\Anaconda3\lib\site-packages\traitlets\config\application.py", line 562, in _load_config_files
        config = loader.load_config()
      File "C:\ProgramData\Anaconda3\lib\site-packages\traitlets\config\loader.py", line 457, in load_config
        self._read_file_as_dict()
      File "C:\ProgramData\Anaconda3\lib\site-packages\traitlets\config\loader.py", line 489, in _read_file_as_dict
        py3compat.execfile(conf_filename, namespace)
      File "C:\ProgramData\Anaconda3\lib\site-packages\ipython_genutils\py3compat.py", line 198, in execfile
        exec(compiler(f.read(), fname, 'exec'), glob, loc)
      File "C:\Users\ztk\.jupyter\jupyter_notebook_config.py", line 203
        c.NotebookApp.notebook_dir = 'C:\Users\ztk\Documents\jupyter'
                                    ^
    SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape
[I 15:20:09.605 NotebookApp] Serving notebooks from local directory: C:\Users\ztk
[I 15:20:09.605 NotebookApp] 0 active kernels 
[I 15:20:09.605 NotebookApp] The Jupyter Notebook is running at: http://localhost:8888/?token=8e3a6e326cd78647f0a049b5985470003321799d59c58a10
[I 15:20:09.605 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 15:20:09.611 NotebookApp] 
    
    Copy/past

**Comment by goanpeca** [comment]
Your jupyter config file seems to be wrong. Please remove this file

`C:\Users\ztk\.jupyter\jupyter_notebook_config.py`

---

Please update conda and navigator to the latest version.

Open a terminal (on Linux or Mac) or the Anaconda Command Prompt (on windows)
and type:

```
$ conda update conda
$ conda update anaconda-navigator
$ conda update navigator-updater
```
