### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by youngxhui** [ContinuumIO/anaconda-issues#6967]
## Main error
The following errors occurred:
## Traceback
```
PackageNotFoundError: Packages missing in current channels:
            
  - rstudio ==1.0.153

We have searched for the packages in the following channels:
            
  - https://repo.continuum.io/pkgs/main/win-64
  - https://repo.continuum.io/pkgs/main/noarch
  - https://repo.continuum.io/pkgs/free/win-64
  - https://repo.continuum.io/pkgs/free/noarch
  - https://repo.continuum.io/pkgs/r/win-64
  - https://repo.continuum.io/pkgs/r/noarch
  - https://repo.continuum.io/pkgs/pro/win-64
  - https://repo.continuum.io/pkgs/pro/noarch
  - https://repo.continuum.io/pkgs/msys2/win-64
  - https://repo.continuum.io/pkgs/msys2/noarch
            
```
## System information
```
platform: win-64
version: 1.6.2
conda: 4.3.21
qt: 5.6.2
language: zh_CN
python: 2.7.13
os: Windows;10;10.0.16299;AMD64;Intel64 Family 6 Model 60 Stepping 3, GenuineIntel
pyqt: 5.6.0
```

**Comment by Pyramiding** [comment]
Navigator Error

An unexpected error occurred on Navigator start-up
Report

Please report this issue in the anaconda issue tracker
Main Error

string indices must be integers, not str

Traceback

Traceback (most recent call last):
  File "/home/wu/anaconda2/lib/python2.7/site-packages/anaconda_navigator/exceptions.py", line 75, in exception_handler
    return_value = func(*args, **kwargs)
  File "/home/wu/anaconda2/lib/python2.7/site-packages/anaconda_navigator/app/start.py", line 115, in start_app
    window = run_app(splash)
  File "/home/wu/anaconda2/lib/python2.7/site-packages/anaconda_navigator/app/start.py", line 58, in run_app
    window = MainWindow(splash=splash)
  File "/home/wu/anaconda2/lib/python2.7/site-packages/anaconda_navigator/widgets/main_window.py", line 160, in __init__
    self.api = AnacondaAPI()
  File "/home/wu/anaconda2/lib/python2.7/site-packages/anaconda_navigator/api/anaconda_api.py", line 1205, in AnacondaAPI
    ANACONDA_API = _AnacondaAPI()
  File "/home/wu/anaconda2/lib/python2.7/site-packages/anaconda_navigator/api/anaconda_api.py", line 65, in __init__
    self._conda_api = CondaAPI()
  File "/home/wu/anaconda2/lib/python2.7/site-packages/anaconda_navigator/api/conda_api.py", line 1622, in CondaAPI
    CONDA_API = _CondaAPI()
  File "/home/wu/anaconda2/lib/python2.7/site-packages/anaconda_navigator/api/conda_api.py", line 340, in __init__
    self.set_conda_prefix()
  File "/home/wu/anaconda2/lib/python2.7/site-packages/anaconda_navigator/api/conda_api.py", line 489, in set_conda_prefix
    self.ROOT_PREFIX = info['root_prefix']
TypeError: string indices must be integers, not str

**Comment by goanpeca** [comment]
**See issue #1837 for more information on how to fix this issue.**

---

Please update conda and navigator to the latest version.

Open a terminal (on Linux or Mac) or the Anaconda Command Prompt (on windows)
and type:

```
$ conda update conda
$ conda update anaconda-navigator
$ conda update navigator-updater
```
