### ISSUE TITLE
OSError: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by dharshanv07** [ContinuumIO/anaconda-issues#6992]
I'm unable to access any conda utilities. Even conda list returns OS error.
Traceback (most recent call last):
  File "/home/qruize-admin/anaconda2/bin/conda", line 11, in <module>
    sys.exit(main())
  File "/home/qruize-admin/anaconda2/lib/python2.7/site-packages/conda/cli/main.py", line 182, in main
    return conda_exception_handler(_main, *args)
  File "/home/qruize-admin/anaconda2/lib/python2.7/site-packages/conda/exceptions.py", line 644, in conda_exception_handler
    return handle_exception(e)
  File "/home/qruize-admin/anaconda2/lib/python2.7/site-packages/conda/exceptions.py", line 634, in handle_exception
    print_unexpected_error_message(e)
  File "/home/qruize-admin/anaconda2/lib/python2.7/site-packages/conda/exceptions.py", line 596, in print_unexpected_error_message
    stderrlogger.info(get_main_info_str(get_info_dict()))
  File "/home/qruize-admin/anaconda2/lib/python2.7/site-packages/conda/cli/main_info.py", line 161, in get_info_dict
    from ..config import rc_path, sys_rc_path, user_rc_path
  File "/home/qruize-admin/anaconda2/lib/python2.7/site-packages/conda/config.py", line 70, in <module>
    root_writable = context.root_writable
  File "/home/qruize-admin/anaconda2/lib/python2.7/site-packages/conda/base/context.py", line 284, in root_writable
    from ..gateways.disk.test import prefix_is_writable
  File "/home/qruize-admin/anaconda2/lib/python2.7/site-packages/conda/gateways/disk/test.py", line 8, in <module>
    from .create import create_link
  File "/home/qruize-admin/anaconda2/lib/python2.7/site-packages/conda/gateways/disk/create.py", line 15, in <module>
    from .delete import rm_rf
  File "/home/qruize-admin/anaconda2/lib/python2.7/site-packages/conda/gateways/disk/delete.py", line 10, in <module>
    from uuid import uuid4
  File "/home/qruize-admin/uuid.py", line 5, in <module>
    k=get_id()
  File "/home/qruize-admin/uuid.py", line 4, in get_id
    return subprocess.Popen('hal-get-property --udi /org/freedesktop/Hal/devices/computer --key system.hardware.uuid'.split())
  File "/home/qruize-admin/anaconda2/lib/python2.7/subprocess.py", line 390, in __init__
    errread, errwrite)
  File "/home/qruize-admin/anaconda2/lib/python2.7/subprocess.py", line 1025, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

I tried reinstalling latest version (Anaconda2-5.0.1) that too didn't work for me.

**Comment by mingwandroid** [comment]
What do you have for `PYTHONPATH`?

`echo $PYTHONPATH`

**Comment by dharshanv07** [comment]
echo $PYTHONPATH returns
/usr/local/lib/python3.5/dist-packages:/usr/local/lib/python2.7/dist-packages:

**Comment by mingwandroid** [comment]
Please show the output from:

`python -c 'import sys; print sys.path'`

**Comment by dharshanv07** [comment]
I gives
['', '/usr/local/lib/python3.5/dist-packages', '/usr/local/lib/python2.7/dist-packages', '/home/qruize-admin', '/home/qruize-admin/anaconda2/lib/python27.zip', '/home/qruize-admin/anaconda2/lib/python2.7', '/home/qruize-admin/anaconda2/lib/python2.7/plat-linux2', '/home/qruize-admin/anaconda2/lib/python2.7/lib-tk', '/home/qruize-admin/anaconda2/lib/python2.7/lib-old', '/home/qruize-admin/anaconda2/lib/python2.7/lib-dynload', '/home/qruize-admin/.local/lib/python2.7/site-packages', '/home/qruize-admin/anaconda2/lib/python2.7/site-packages']

**Comment by mingwandroid** [comment]
OK, `PYTHONPATH` is generally a very harmful thing to have set to anything. In this case, because of what you have set it to, you are mixing Python 3.5 and Python 2.7 modules. That is not going to end well. Please try the following:

```
unset PYTHONPATH
conda list
```

You need to track down where you have set `PYTHONPATH` (look in `~/.bashrc` and `~/.bash_profile`) and remove that.

**Comment by mingwandroid** [comment]
Here is a reference I just found. I haven't listened to it but the summary text seems to have the right idea: https://pythonbytes.fm/episodes/show/22/pythonpath-considered-harmful

**Comment by dharshanv07** [comment]
thanks @mingwandroid .. It works. I will explore on this link and correct my PYTHONPATH.
