### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by dpati09** [ContinuumIO/anaconda-issues#7021]
## Main error
Application <b>spyder</b> launch may have produced errors.
## Traceback
```
Traceback (most recent call last):
  File "C:\Users\WINGS\Anaconda3\Scripts\spyder-script.py", line 3, in <module>
    import spyder.app.start
  File "C:\Users\WINGS\Anaconda3\lib\site-packages\spyder\app\start.py", line 13, in <module>
    from spyder.config.base import get_conf_path, running_in_mac_app
  File "C:\Users\WINGS\Anaconda3\lib\site-packages\spyder\config\base.py", line 365, in <module>
    _ = get_translation("spyder")
  File "C:\Users\WINGS\Anaconda3\lib\site-packages\spyder\config\base.py", line 345, in get_translation
    _trans = gettext.translation(modname, locale_path, codeset="utf-8")
  File "C:\Users\WINGS\Anaconda3\lib\gettext.py", line 505, in translation
    mofiles = find(domain, localedir, languages, all=True)
  File "C:\Users\WINGS\Anaconda3\lib\gettext.py", line 489, in find
    if os.path.exists(mofile):
  File "C:\Users\WINGS\Anaconda3\lib\genericpath.py", line 19, in exists
    os.stat(path)
ValueError: stat: embedded null character in path

```
## System information
```
python: 3.6.1
language: en_US
os: Windows;7;6.1.7601;AMD64;Intel64 Family 6 Model 15 Stepping 13, GenuineIntel
version: 1.6.2
platform: win-64
qt: 5.6.2
pyqt: 5.6.0
conda: 4.3.27
```

**Comment by dpati09** [comment]
Hi I am new to Anacoda ......Yesterday I was facing the same issue and raised the issue here. Today I got message the issue is resolved but I am getting same error.

Kindly let me know what else I can do.

Thanks,
Debasish

**Comment by goanpeca** [comment]
`ValueError: stat: embedded null character in path`, it seems a path that spyder depends on has an invalid character. is `WINGS` the real username?

**Comment by dpati09** [comment]
WINGS is my PC name

**Comment by goanpeca** [comment]
@ccordoba12 thoughts?
