### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by friendlywlb** [ContinuumIO/anaconda-issues#7024]
## Main error
The following errors occurred:
## Traceback
```
Traceback (most recent call last):
  File "C:\Users\frien\Anaconda3\lib\site-packages\conda\exceptions.py", line 632, in conda_exception_handler
    return_value = func(*args, **kwargs)
  File "C:\Users\frien\Anaconda3\lib\site-packages\conda_env\cli\main_create.py", line 78, in execute
    directory=os.getcwd())
  File "C:\Users\frien\Anaconda3\lib\site-packages\conda_env\specs\__init__.py", line 20, in detect
    if spec.can_handle():
  File "C:\Users\frien\Anaconda3\lib\site-packages\conda_env\specs\yaml_file.py", line 14, in can_handle
    self._environment = env.from_file(self.filename)
  File "C:\Users\frien\Anaconda3\lib\site-packages\conda_env\env.py", line 79, in from_file
    yamlstr = fp.read()
UnicodeDecodeError: 'gbk' codec can't decode byte 0xa6 in position 20764: illegal multibyte sequence

```
## System information
```
python: 3.6.1
language: en_US
os: Windows;10;10.0.16299;AMD64;Intel64 Family 6 Model 78 Stepping 3, GenuineIntel
version: 1.6.2
platform: win-64
qt: 5.6.2
pyqt: 5.6.0
conda: 4.3.21
```

**Comment by goanpeca** [comment]
@friendlywlb it seems you were using an invalid environment.yml file
