### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by usd001** [ContinuumIO/anaconda-issues#7037]
## Main error
Application <b>qtconsole</b> launch may have produced errors.
## Traceback
```
Traceback (most recent call last):
  File "/Applications/anaconda/envs/py27_qt4/bin/jupyter-qtconsole", line 2, in <module>
    from qtconsole.qtconsoleapp import main
  File "/Applications/anaconda/envs/py27_qt4/lib/python2.7/site-packages/qtconsole/qtconsoleapp.py", line 60, in <module>
    from qtconsole.qt import QtCore, QtGui
  File "/Applications/anaconda/envs/py27_qt4/lib/python2.7/site-packages/qtconsole/qt.py", line 23, in <module>
    QtCore, QtGui, QtSvg, QT_API = load_qt(api_opts)
  File "/Applications/anaconda/envs/py27_qt4/lib/python2.7/site-packages/qtconsole/qt_loaders.py", line 365, in load_qt
    result = loaders[api]()
  File "/Applications/anaconda/envs/py27_qt4/lib/python2.7/site-packages/qtconsole/qt_loaders.py", line 242, in import_pyqt4
    import sip
ImportError: No module named sip

```
## System information
```
platform: osx-64
version: 1.6.2
conda: 4.3.30
qt: 5.6.2
language: en
python: 2.7.11
os: Darwin;16.7.0;Darwin Kernel Version 16.7.0: Thu Jun 15 17:36:27 PDT 2017; root:xnu-3789.70.16~2/RELEASE_X86_64;x86_64;i386
pyqt: 5.6.0
```

**Comment by mingwandroid** [comment]
Your env is named `py27_qt4`. Does this mean Qt4? We do not support that anymore. You may still be able to create an env with Qt4, but you will not be able to run any of the Qt-linked graphical applications provided by the `Anaconda Distribution` in such an env.
