### ISSUE TITLE
can't open my anaconda-navigator

### ISSUE THREAD

**Issue by Andhros** [ContinuumIO/anaconda-issues#7049]
my traceback:

Traceback (most recent call last):
  File "/home/andhros/anaconda2/bin/anaconda-navigator", line 11, in <module>
    sys.exit(main())
  File "/home/andhros/anaconda2/lib/python2.7/site-packages/anaconda_navigator/app/main.py", line 125, in main
    from anaconda_navigator.utils.logs import clean_logs
  File "/home/andhros/anaconda2/lib/python2.7/site-packages/anaconda_navigator/utils/__init__.py", line 15, in <module>
    from qtpy.QtGui import QIcon
  File "/home/andhros/anaconda2/lib/python2.7/site-packages/qtpy/__init__.py", line 154, in <module>
    raise PythonQtError('No Qt bindings could be found')
qtpy.PythonQtError: No Qt bindings could be found

what should I do? (ps: I don't have sudo or root privileges)

**Comment by goanpeca** [comment]
what happens if you open a terminal and do

```
$ source activate root
$ anaconda-navigator
```
?

**Comment by Andhros** [comment]
the same traceback appears:

Traceback (most recent call last):
  File "/home/andhros/anaconda2/bin/anaconda-navigator", line 11, in <module>
    sys.exit(main())
  File "/home/andhros/anaconda2/lib/python2.7/site-packages/anaconda_navigator/app/main.py", line 125, in main
    from anaconda_navigator.utils.logs import clean_logs
  File "/home/andhros/anaconda2/lib/python2.7/site-packages/anaconda_navigator/utils/__init__.py", line 15, in <module>
    from qtpy.QtGui import QIcon
  File "/home/andhros/anaconda2/lib/python2.7/site-packages/qtpy/__init__.py", line 154, in <module>
    raise PythonQtError('No Qt bindings could be found')
qtpy.PythonQtError: No Qt bindings could be found

**Comment by goanpeca** [comment]
@Andhros you may have a corrupt installation :-\ ?

**Comment by Andhros** [comment]
how's that since I did it all perfectly as instructed in anaconda's documentation? i'm trying to install in a remote cluster, dunno why it's not working because in my local machine worked flawlessly.

**Comment by goanpeca** [comment]
@Andhros I am curious.

If you are trying to install in a remote cluster why do you need a GUI like Anaconda Navigator?

**Comment by Andhros** [comment]
Well, I would like to run it remotely. That's not possible?

**Comment by Andhros** [comment]
I would like to use the spyder IDE for example, but remotely.

**Comment by goanpeca** [comment]
@Andhros I don't think you can do that. @ccordoba12 ?

**Comment by Andhros** [comment]
why couldn't I do it accessing via an ssh -X protocol?

**Comment by sajid-ali-nu** [comment]
You can open an ipython notebook and forward the port via ssh though. 

https://coderwall.com/p/ohk6cg/remote-access-to-ipython-notebooks-via-ssh

**Comment by Andhros** [comment]
thanks my friend.

**Comment by nurgasemetey** [comment]
I am also getting this error. Before installing `gcc` using `conda`,  it was working well.
I installed `gcc` using : `conda install gcc`.

Later I closed anaconda navigator and started using `anaconda-navigator`.
Then there was following error:

```
Traceback (most recent call last):
  File "/home/nurgasemetey/anaconda2/bin/anaconda-navigator", line 11, in <module>
    sys.exit(main())
  File "/home/nurgasemetey/anaconda2/lib/python2.7/site-packages/anaconda_navigator/app/main.py", line 125, in main
    from anaconda_navigator.utils.logs import clean_logs
  File "/home/nurgasemetey/anaconda2/lib/python2.7/site-packages/anaconda_navigator/utils/__init__.py", line 15, in <module>
    from qtpy.QtGui import QIcon
  File "/home/nurgasemetey/anaconda2/lib/python2.7/site-packages/qtpy/__init__.py", line 154, in <module>
    raise PythonQtError('No Qt bindings could be found')
qtpy.PythonQtError: No Qt bindings could be found
```
