### ISSUE TITLE
Navigator doesn't open

### ISSUE THREAD

**Issue by Ch4OSm4n** [ContinuumIO/anaconda-issues#7070]
Hi all,
I installed several times different versions of Anaconda suite but in noone I can launch the Anaconda Navigator.
Appear (and disappear) a prompt windowd and nothing happens.

`Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\conda\cli\main.py", line 170, in main
    import conda.cli.activate as activate
  File "C:\ProgramData\Anaconda3\lib\site-packages\conda\cli\activate.py", line 12, in <module>
    from ..utils import shells
  File "C:\ProgramData\Anaconda3\lib\site-packages\conda\utils.py", line 15, in <module>
    from .gateways.disk.read import compute_md5sum
  File "C:\ProgramData\Anaconda3\lib\site-packages\conda\gateways\disk\read.py", line 22, in <module>
    from ...models.channel import Channel
  File "C:\ProgramData\Anaconda3\lib\site-packages\conda\models\channel.py", line 8, in <module>
    from ..base.context import context
  File "C:\ProgramData\Anaconda3\lib\site-packages\conda\base\context.py", line 771, in <module>
    context = Context(SEARCH_PATH, APP_NAME, None)
  File "C:\ProgramData\Anaconda3\lib\site-packages\conda\common\configuration.py", line 727, in __init__
    self._set_search_path(search_path)
  File "C:\ProgramData\Anaconda3\lib\site-packages\conda\common\configuration.py", line 745, in _set_search_path
    self._set_raw_data(load_file_configs(search_path))
  File "C:\ProgramData\Anaconda3\lib\site-packages\conda\common\configuration.py", line 369, in load_file_configs
    raw_data = odict(kv for kv in chain.from_iterable(load_paths))
  File "C:\ProgramData\Anaconda3\lib\site-packages\conda\common\configuration.py", line 369, in <genexpr>
    raw_data = odict(kv for kv in chain.from_iterable(load_paths))
  File "C:\ProgramData\Anaconda3\lib\site-packages\conda\common\configuration.py", line 344, in _file_yaml_loader
    yield fullpath, YamlRawParameter.make_raw_parameters_from_file(fullpath)
  File "C:\ProgramData\Anaconda3\lib\site-packages\conda\common\configuration.py", line 332, in make_raw_parameters_from_file
    ruamel_yaml = yaml_load(fh)
  File "C:\ProgramData\Anaconda3\lib\site-packages\conda\common\yaml.py", line 26, in yaml_load
    return yaml.load(string, Loader=yaml.RoundTripLoader, version="1.2")
  File "C:\ProgramData\Anaconda3\lib\site-packages\ruamel_yaml\main.py", line 73, in load
    loader = Loader(stream, version, preserve_quotes=preserve_quotes)
  File "C:\ProgramData\Anaconda3\lib\site-packages\ruamel_yaml\loader.py", line 56, in __init__
    Reader.__init__(self, stream)
  File "C:\ProgramData\Anaconda3\lib\site-packages\ruamel_yaml\reader.py", line 98, in __init__
    self.determine_encoding()
  File "C:\ProgramData\Anaconda3\lib\site-packages\ruamel_yaml\reader.py", line 149, in determine_encoding
    self.update(1)
  File "C:\ProgramData\Anaconda3\lib\site-packages\ruamel_yaml\reader.py", line 189, in update
    self.check_printable(data)
  File "C:\ProgramData\Anaconda3\lib\site-packages\ruamel_yaml\reader.py", line 160, in check_printable
    'unicode', "special characters are not allowed")
ruamel_yaml.reader.ReaderError: unacceptable character #x0000: special characters are not allowed
  in "C:\Users\Ch4OSm4n\.condarc", position 0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\Scripts\conda-script.py", line 10, in <module>
    sys.exit(main())
  File "C:\ProgramData\Anaconda3\lib\site-packages\conda\cli\main.py", line 178, in main
    init_loggers()
  File "C:\ProgramData\Anaconda3\lib\site-packages\conda\cli\main.py", line 84, in init_loggers
    from ..console import setup_verbose_handlers
  File "C:\ProgramData\Anaconda3\lib\site-packages\conda\console.py", line 9, in <module>
    from .base.context import context
  File "C:\ProgramData\Anaconda3\lib\site-packages\conda\base\context.py", line 771, in <module>
    context = Context(SEARCH_PATH, APP_NAME, None)
  File "C:\ProgramData\Anaconda3\lib\site-packages\conda\common\configuration.py", line 727, in __init__
    self._set_search_path(search_path)
  File "C:\ProgramData\Anaconda3\lib\site-packages\conda\common\configuration.py", line 745, in _set_search_path
    self._set_raw_data(load_file_configs(search_path))
  File "C:\ProgramData\Anaconda3\lib\site-packages\conda\common\configuration.py", line 369, in load_file_configs
    raw_data = odict(kv for kv in chain.from_iterable(load_paths))
  File "C:\ProgramData\Anaconda3\lib\site-packages\conda\common\configuration.py", line 369, in <genexpr>
    raw_data = odict(kv for kv in chain.from_iterable(load_paths))
  File "C:\ProgramData\Anaconda3\lib\site-packages\conda\common\configuration.py", line 344, in _file_yaml_loader
    yield fullpath, YamlRawParameter.make_raw_parameters_from_file(fullpath)
  File "C:\ProgramData\Anaconda3\lib\site-packages\conda\common\configuration.py", line 332, in make_raw_parameters_from_file
    ruamel_yaml = yaml_load(fh)
  File "C:\ProgramData\Anaconda3\lib\site-packages\conda\common\yaml.py", line 26, in yaml_load
    return yaml.load(string, Loader=yaml.RoundTripLoader, version="1.2")
  File "C:\ProgramData\Anaconda3\lib\site-packages\ruamel_yaml\main.py", line 73, in load
    loader = Loader(stream, version, preserve_quotes=preserve_quotes)
  File "C:\ProgramData\Anaconda3\lib\site-packages\ruamel_yaml\loader.py", line 56, in __init__
    Reader.__init__(self, stream)
  File "C:\ProgramData\Anaconda3\lib\site-packages\ruamel_yaml\reader.py", line 98, in __init__
    self.determine_encoding()
  File "C:\ProgramData\Anaconda3\lib\site-packages\ruamel_yaml\reader.py", line 149, in determine_encoding
    self.update(1)
  File "C:\ProgramData\Anaconda3\lib\site-packages\ruamel_yaml\reader.py", line 189, in update
    self.check_printable(data)
  File "C:\ProgramData\Anaconda3\lib\site-packages\ruamel_yaml\reader.py", line 160, in check_printable
    'unicode', "special characters are not allowed")
ruamel_yaml.reader.ReaderError: unacceptable character #x0000: special characters are not allowed
  in "C:\Users\Ch4OSm4n\.condarc", position 0`

**Comment by goanpeca** [comment]
@Ch4OSm4n the file `C:\Users\Ch4OSm4n.condarc` is probably corrupt. Please delete that.

Also I would advice to use `Current User` Installs instead of `All User Installs`
