### ISSUE TITLE
conda dependency issue of lxml with libiconv under certain conditions

### ISSUE THREAD

**Issue by cbyrohl** [ContinuumIO/anaconda-issues#7142]
Hi there,

on my current anaconda 5, conda lacks the lxml dependency libiconv, while conda-forge does not:

```
> conda remove lxml libiconv
> conda install -c conda-forge lxml
The following NEW packages will be INSTALLED:
    libiconv: 1.14-4       conda-forge
    libxml2:  2.9.5-1      conda-forge
    libxslt:  1.1.29-5     conda-forge
    lxml:     4.1.0-py27_0 conda-forge
> conda install lxml
The following NEW packages will be INSTALLED:
    libxml2: 2.9.4-h6b072ca_5    
    libxslt: 1.1.29-hcf9102b_5   
    lxml:    4.1.0-py27hb025457_0
```

While conda-forge installs libiconv, being a dependency for lxml. Conda does not. On a clean setup both installation methods works though:

```
> conda install -c conda-forge lxml
The following NEW packages will be INSTALLED:
    libiconv: 1.14-4       conda-forge
    libxml2:  2.9.5-1      conda-forge
    libxslt:  1.1.29-5     conda-forge
    lxml:     4.1.0-py27_0 conda-forge
> conda install lxml
The following NEW packages will be INSTALLED:
    libiconv: 1.15-h63c8f33_5     
    libxml2:  2.9.4-0             
    libxslt:  1.1.29-0            
    lxml:     4.1.0-py27hb025457_0
```

Why is that? For example, when I install jupyter_contrib_nbextensions, which requires lxml. I fail to install the package because of this unresolved dependency (see ipython-contrib/jupyter_contrib_nbextensions#1153).

Here's my current setup:
```
> conda list
alembic                   0.9.6                     <pip>
astropy                   2.0.2            py27h57072c0_4  
backports                 1.0              py27h63c9359_1  
backports.functools_lru_cache 1.4              py27he8db605_1  
backports.shutil_get_terminal_size 1.0.0            py27h5bc021e_2  
backports_abc             0.5              py27h7b3c97b_0  
banal                     0.2.0                     <pip>
beautifulsoup4            4.6.0                     <pip>
bleach                    2.0.0            py27h3a0dcc8_0  
ca-certificates           2017.08.26           h1d4fec5_0  
certifi                   2017.7.27.1      py27h9ceb091_0  
chardet                   3.0.4                     <pip>
configparser              3.5.0            py27h5117587_0  
cycler                    0.10.0           py27hc7354d3_0  
dataset                   1.0.2                     <pip>
dbus                      1.10.22              h3b5a359_0  
decorator                 4.1.2            py27h1544723_0  
entrypoints               0.2.3            py27h502b47d_2  
enum34                    1.1.6            py27h99a27e9_1  
expat                     2.2.4                hc00ebd1_1  
freetype                  2.8                  h52ed37b_0  
funcsigs                  1.0.2            py27h83f16ab_0  
functools32               3.2.3.2          py27h4ead58f_1  
futures                   3.1.1            py27hdbc8cbb_0  
glib                      2.53.6               hc861d11_1  
gmp                       6.1.2                hb3b607b_0  
gst-plugins-base          1.12.2               he3457e5_0  
gstreamer                 1.12.2               h4f93127_0  
h5py                      2.7.0            py27h71d1790_1  
halotools                 0.5                       <pip>
hdf5                      1.10.1               hb0523eb_0  
html5lib                  0.999999999      py27hdf15f34_0  
icu                       58.2                 h211956c_0  
idna                      2.6                       <pip>
intel-openmp              2018.0.0             h15fc484_7  
ipykernel                 4.6.1            py27hc93e584_0  
ipyparallel               6.0.2                    py27_0  
ipython                   5.4.1            py27h36c99b6_1  
ipython_genutils          0.2.0            py27h89fb69b_0  
ipywidgets                7.0.0            py27h4fda95d_0  
jinja2                    2.9.6            py27h82327ae_1  
jpeg                      9b                   habf39ab_1  
jsonschema                2.6.0            py27h7ed5aa4_0  
jupyter_client            5.1.0            py27hbee1118_0  
jupyter_contrib_core      0.3.3                    py27_0    conda-forge
jupyter_core              4.3.0            py27hcd9ae3a_0  
jupyter_highlight_selected_word 0.0.11                   py27_0    conda-forge
jupyter_latex_envs        1.3.8.2                  py27_1    conda-forge
jupyter_nbextensions_configurator 0.2.8                    py27_0    conda-forge
libedit                   3.1                  heed3624_0  
libffi                    3.2.1                h4deb6c0_3  
libgcc-ng                 7.2.0                h7cc24e2_2  
libgfortran-ng            7.2.0                h9f7466a_2  
libpng                    1.6.32               hda9c8bc_2  
libsodium                 1.0.13               h31c71d8_2  
libstdcxx-ng              7.2.0                h7a57d05_2  
libxcb                    1.12                 h84ff03f_3  
llvmlite                  0.20.0                   py27_0  
Mako                      1.0.7                     <pip>
markdown2                 2.3.4                    py27_0  
markupsafe                1.0              py27h97b2822_1  
mistune                   0.7.4            py27h6da7e90_0  
mkl                       2018.0.0             hb491cac_4  
nbconvert                 5.3.1            py27he041f76_0  
nbformat                  4.4.0            py27hed7f2b2_0  
ncurses                   6.0                  h06874d7_1  
normality                 0.5.0                     <pip>
notebook                  5.0.0            py27h3661c2b_2  
numba                     0.35.0             np113py27_10  
numpy                     1.13.3           py27hbcc08e0_0  
openssl                   1.0.2l               h9d1a558_3  
pandas                    0.20.3           py27h820b67f_2  
pandoc                    1.19.2.1             hea2e7c5_1  
pandocfilters             1.4.2            py27h428e1e5_1  
pathlib2                  2.3.0            py27h6e9d198_0  
pcre                      8.41                 hc71a17e_0  
pexpect                   4.2.1            py27hcf82287_0  
pickleshare               0.7.4            py27h09770e1_0  
pip                       9.0.1            py27hbf658b2_3  
prompt_toolkit            1.0.15           py27h1b593e1_0  
ptyprocess                0.5.2            py27h4ccb14c_0  
py                        1.4.34           py27he5894e4_1  
pygments                  2.2.0            py27h4a8b6f5_0  
pyparsing                 2.2.0            py27hf1513f8_1  
PyPrind                   2.11.1                    <pip>
pytest                    3.2.1            py27h98000ae_1  
python                    2.7.14              h9b67528_20  
python-dateutil           2.6.1            py27h4ca5741_1  
python-editor             1.0.3                     <pip>
pytz                      2017.2           py27hcac29fa_1  
pyyaml                    3.12                     py27_1    conda-forge
pyzmq                     16.0.2           py27h297844f_2  
readline                  7.0                  hac23ff0_3  
requests                  2.18.4                    <pip>
scandir                   1.6              py27hf7388dc_0  
scipy                     0.19.1           py27h1edc525_3  
setuptools                36.5.0           py27h68b189e_0  
simplegeneric             0.8.1            py27h19e43cd_0  
singledispatch            3.4.0.3          py27h9bcb476_0  
sip                       4.18.1           py27he9ba0ab_2  
six                       1.10.0           py27hdcd7534_1  
SQLAlchemy                1.1.14                    <pip>
sqlite                    3.20.1               h6d8b0f3_1  
ssl_match_hostname        3.5.0.1          py27h4ec10b9_2  
subprocess32              3.2.7            py27h373dbce_0  
terminado                 0.6              py27h4be8df9_0  
testpath                  0.3.1            py27hc38d2c4_0  
tk                        8.6.7                h5979e9b_1  
tornado                   4.5.2            py27h97b179f_0  
tqdm                      4.19.4                    <pip>
traitlets                 4.3.2            py27hd6ce930_0  
urllib3                   1.22                      <pip>
wcwidth                   0.1.7            py27h9e3e1ab_0  
webencodings              0.5.1            py27hff10b21_1  
wheel                     0.29.0           py27h411dd7b_1  
widgetsnbextension        3.0.2            py27hcb77dec_1  
xz                        5.2.3                h2bcbf08_1  
yaml                      0.1.6                         0    conda-forge
zeromq                    4.2.2                hb0b69da_1  
zlib                      1.2.11               hfbfcf68_1
```

**Comment by mingwandroid** [comment]
There should not be any libiconv packages for GNU/Linux since it is built into glibc.

Therefore when I rebuilt AD5 I made sure to correct this.

**Comment by cbyrohl** [comment]
I am unsure that I understand. To summarize my problem: If there is no libiconv package upon installation of lxml I run into this error when using it:
"ImportError: libiconv.so.2: cannot open shared object file: No such file or directory"

**Comment by sensharma** [comment]
I am facing exactly the same issue on Ubuntu 16.04 with python3.6 environment.

**Comment by mingwandroid** [comment]
Can someone who is facing `ImportError: libiconv.so.2: cannot open shared object file: No such file or directory`

.. please show the output of `conda info` and `conda list --show-channel-urls`?

**Comment by cbyrohl** [comment]
```
> conda info
Current conda install:

               platform : linux-64
          conda version : 4.3.30
       conda is private : False
      conda-env version : 4.3.30
    conda-build version : 3.0.23
         python version : 3.6.2.final.0
       requests version : 2.18.4
       root environment : /home/uni09/cosmo/cbyrohl/anaconda3  (writable)
    default environment : /home/uni09/cosmo/cbyrohl/anaconda3/envs/test2
       envs directories : /home/uni09/cosmo/cbyrohl/anaconda3/envs
                          /usr/users/cbyrohl/.conda/envs
          package cache : /home/uni09/cosmo/cbyrohl/anaconda3/pkgs
                          /usr/users/cbyrohl/.conda/pkgs
           channel URLs : https://repo.continuum.io/pkgs/main/linux-64
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/linux-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : None
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.30 requests/2.18.4 CPython/3.6.2 Linux/3.10.0-693.2.2.el7.x86_64 Scientific Linux/7.3 glibc/2.17
```

```
> conda list --show-channel-urls
alembic                   0.9.6                     <pip>
astropy                   2.0.2            py27h57072c0_4    defaults
backports                 1.0              py27h63c9359_1    defaults
backports.functools_lru_cache 1.4              py27he8db605_1    defaults
backports.shutil_get_terminal_size 1.0.0            py27h5bc021e_2    defaults
backports_abc             0.5              py27h7b3c97b_0    defaults
banal                     0.2.0                     <pip>
beautifulsoup4            4.6.0                     <pip>
bleach                    2.0.0            py27h3a0dcc8_0    defaults
ca-certificates           2017.08.26           h1d4fec5_0    defaults
certifi                   2017.7.27.1      py27h9ceb091_0    defaults
chardet                   3.0.4                     <pip>
configparser              3.5.0            py27h5117587_0    defaults
cycler                    0.10.0           py27hc7354d3_0    defaults
dataset                   1.0.2                     <pip>
dbus                      1.10.22              h3b5a359_0    defaults
decorator                 4.1.2            py27h1544723_0    defaults
entrypoints               0.2.3            py27h502b47d_2    defaults
enum34                    1.1.6            py27h99a27e9_1    defaults
expat                     2.2.4                hc00ebd1_1    defaults
freetype                  2.8                  h52ed37b_0    defaults
funcsigs                  1.0.2            py27h83f16ab_0    defaults
functools32               3.2.3.2          py27h4ead58f_1    defaults
futures                   3.1.1            py27hdbc8cbb_0    defaults
glib                      2.53.6               hc861d11_1    defaults
gmp                       6.1.2                hb3b607b_0    defaults
gst-plugins-base          1.12.2               he3457e5_0    defaults
gstreamer                 1.12.2               h4f93127_0    defaults
h5py                      2.7.0            py27h71d1790_1    defaults
halotools                 0.5                       <pip>
hdf5                      1.10.1               hb0523eb_0    defaults
html5lib                  0.999999999      py27hdf15f34_0    defaults
icu                       58.2                 h211956c_0    defaults
idna                      2.6                       <pip>
intel-openmp              2018.0.0             h15fc484_7    defaults
ipykernel                 4.6.1            py27hc93e584_0    defaults
ipyparallel               6.0.2                    py27_0    defaults
ipython                   5.4.1            py27h36c99b6_1    defaults
ipython_genutils          0.2.0            py27h89fb69b_0    defaults
ipywidgets                7.0.0            py27h4fda95d_0    defaults
jinja2                    2.9.6            py27h82327ae_1    defaults
jpeg                      9b                   habf39ab_1    defaults
jsonschema                2.6.0            py27h7ed5aa4_0    defaults
jupyter_client            5.1.0            py27hbee1118_0    defaults
jupyter_contrib_core      0.3.3                    py27_0    conda-forge
jupyter_core              4.3.0            py27hcd9ae3a_0    defaults
jupyter_highlight_selected_word 0.0.11                   py27_0    conda-forge
jupyter_latex_envs        1.3.8.2                  py27_1    conda-forge
jupyter_nbextensions_configurator 0.2.8                    py27_0    conda-forge
libedit                   3.1                  heed3624_0    defaults
libffi                    3.2.1                h4deb6c0_3    defaults
libgcc-ng                 7.2.0                h7cc24e2_2    defaults
libgfortran-ng            7.2.0                h9f7466a_2    defaults
libpng                    1.6.32               hda9c8bc_2    defaults
libsodium                 1.0.13               h31c71d8_2    defaults
libstdcxx-ng              7.2.0                h7a57d05_2    defaults
libxcb                    1.12                 h84ff03f_3    defaults
llvmlite                  0.20.0                   py27_0    defaults
Mako                      1.0.7                     <pip>
markdown2                 2.3.4                    py27_0    defaults
markupsafe                1.0              py27h97b2822_1    defaults
mistune                   0.7.4            py27h6da7e90_0    defaults
mkl                       2018.0.0             hb491cac_4    defaults
nbconvert                 5.3.1            py27he041f76_0    defaults
nbformat                  4.4.0            py27hed7f2b2_0    defaults
ncurses                   6.0                  h06874d7_1    defaults
normality                 0.5.0                     <pip>
notebook                  5.0.0            py27h3661c2b_2    defaults
numba                     0.35.0             np113py27_10    defaults
numpy                     1.13.3           py27hbcc08e0_0    defaults
openssl                   1.0.2l               h9d1a558_3    defaults
pandas                    0.20.3           py27h820b67f_2    defaults
pandoc                    1.19.2.1             hea2e7c5_1    defaults
pandocfilters             1.4.2            py27h428e1e5_1    defaults
pathlib2                  2.3.0            py27h6e9d198_0    defaults
pcre                      8.41                 hc71a17e_0    defaults
pexpect                   4.2.1            py27hcf82287_0    defaults
pickleshare               0.7.4            py27h09770e1_0    defaults
pip                       9.0.1            py27hbf658b2_3    defaults
prompt_toolkit            1.0.15           py27h1b593e1_0    defaults
ptyprocess                0.5.2            py27h4ccb14c_0    defaults
py                        1.4.34           py27he5894e4_1    defaults
pygments                  2.2.0            py27h4a8b6f5_0    defaults
pyparsing                 2.2.0            py27hf1513f8_1    defaults
PyPrind                   2.11.1                    <pip>
pytest                    3.2.1            py27h98000ae_1    defaults
python                    2.7.14              h9b67528_20    defaults
python-dateutil           2.6.1            py27h4ca5741_1    defaults
python-editor             1.0.3                     <pip>
pytz                      2017.2           py27hcac29fa_1    defaults
pyyaml                    3.12                     py27_1    conda-forge
pyzmq                     16.0.2           py27h297844f_2    defaults
readline                  7.0                  hac23ff0_3    defaults
requests                  2.18.4                    <pip>
scandir                   1.6              py27hf7388dc_0    defaults
scipy                     0.19.1           py27h1edc525_3    defaults
setuptools                36.5.0           py27h68b189e_0    defaults
simplegeneric             0.8.1            py27h19e43cd_0    defaults
singledispatch            3.4.0.3          py27h9bcb476_0    defaults
sip                       4.18.1           py27he9ba0ab_2    defaults
six                       1.10.0           py27hdcd7534_1    defaults
SQLAlchemy                1.1.14                    <pip>
sqlite                    3.20.1               h6d8b0f3_1    defaults
ssl_match_hostname        3.5.0.1          py27h4ec10b9_2    defaults
subprocess32              3.2.7            py27h373dbce_0    defaults
terminado                 0.6              py27h4be8df9_0    defaults
testpath                  0.3.1            py27hc38d2c4_0    defaults
tk                        8.6.7                h5979e9b_1    defaults
tornado                   4.5.2            py27h97b179f_0    defaults
tqdm                      4.19.4                    <pip>
traitlets                 4.3.2            py27hd6ce930_0    defaults
urllib3                   1.22                      <pip>
wcwidth                   0.1.7            py27h9e3e1ab_0    defaults
webencodings              0.5.1            py27hff10b21_1    defaults
wheel                     0.29.0           py27h411dd7b_1    defaults
widgetsnbextension        3.0.2            py27hcb77dec_1    defaults
xz                        5.2.3                h2bcbf08_1    defaults
yaml                      0.1.6                         0    conda-forge
zeromq                    4.2.2                hb0b69da_1    defaults
zlib                      1.2.11               hfbfcf68_1    default
```

**Comment by mingwandroid** [comment]
Can I see the full stacktrace for someone experiencing this issue?

**Comment by cbyrohl** [comment]
```
> conda install lxml -y && conda install -c conda-forge jupyter_contrib_nbextensions -y
Fetching package metadata ...........
Solving package specifications: .

Package plan for installation in environment /home/uni09/cosmo/cbyrohl/anaconda3/envs/py27:

The following NEW packages will be INSTALLED:

    lxml: 4.1.0-py27hb025457_0

Fetching package metadata .............
Solving package specifications: .

Package plan for installation in environment /home/uni09/cosmo/cbyrohl/anaconda3/envs/py27:

The following NEW packages will be INSTALLED:

    jupyter_contrib_nbextensions: 0.3.3-py27_0 conda-forge

+ /home/uni09/cosmo/cbyrohl/anaconda3/envs/py27/bin/jupyter-contrib-nbextension install --sys-prefix
Traceback (most recent call last):
  File "/home/uni09/cosmo/cbyrohl/anaconda3/envs/py27/bin/jupyter-contrib-nbextension", line 11, in <module>
    load_entry_point('jupyter-contrib-nbextensions==0.3.3', 'console_scripts', 'jupyter-contrib-nbextension')()
  File "/home/uni09/cosmo/cbyrohl/anaconda3/envs/py27/lib/python2.7/site-packages/pkg_resources/__init__.py", line 570, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/uni09/cosmo/cbyrohl/anaconda3/envs/py27/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2751, in load_entry_point
    return ep.load()
  File "/home/uni09/cosmo/cbyrohl/anaconda3/envs/py27/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2405, in load
    return self.resolve()
  File "/home/uni09/cosmo/cbyrohl/anaconda3/envs/py27/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2411, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/uni09/cosmo/cbyrohl/anaconda3/envs/py27/lib/python2.7/site-packages/jupyter_contrib_nbextensions/application.py", line 15, in <module>
    from jupyter_contrib_nbextensions.install import (
  File "/home/uni09/cosmo/cbyrohl/anaconda3/envs/py27/lib/python2.7/site-packages/jupyter_contrib_nbextensions/install.py", line 21, in <module>
    import jupyter_contrib_nbextensions.nbconvert_support
  File "/home/uni09/cosmo/cbyrohl/anaconda3/envs/py27/lib/python2.7/site-packages/jupyter_contrib_nbextensions/nbconvert_support/__init__.py", line 6, in <module>
    from .embedhtml import EmbedHTMLExporter
  File "/home/uni09/cosmo/cbyrohl/anaconda3/envs/py27/lib/python2.7/site-packages/jupyter_contrib_nbextensions/nbconvert_support/embedhtml.py", line 6, in <module>
    import lxml.etree as et
ImportError: libiconv.so.2: cannot open shared object file: No such file or directory
```

**Comment by cbyrohl** [comment]
It is not obvious to me which of the following package updates is responsible for fixing the problem, but a conda update fixes the dependency problem.
```
> conda update --all
Fetching package metadata ...........
Solving package specifications: .

Package plan for installation in environment /home/uni09/cosmo/cbyrohl/anaconda3/envs/py27:

The following packages will be UPDATED:

    expat:    2.2.4-hc00ebd1_1                  --> 2.2.4-h6ea4f2b_2     
    jpeg:     9b-habf39ab_1                     --> 9b-h376031c_1        
    libffi:   3.2.1-h4deb6c0_3                  --> 3.2.1-hd88cf55_4     
    notebook: 5.0.0-py27h3661c2b_2              --> 5.2.1-py27h4055434_0 
    openssl:  1.0.2l-h9d1a558_3                 --> 1.0.2m-h8cfc7e7_0    
    pandas:   0.20.3-py27h820b67f_2             --> 0.21.0-py27he307072_1
    pip:      9.0.1-py27hbf658b2_3              --> 9.0.1-py27ha730c48_4 
    python:   2.7.14-h9b67528_20                --> 2.7.14-ha6fc286_23   
    readline: 7.0-hac23ff0_3                    --> 7.0-hb321a52_4       
    scipy:    0.19.1-py27h1edc525_3             --> 1.0.0-py27hf5f0f52_0 
    six:      1.10.0-py27hdcd7534_1             --> 1.11.0-py27h5f960f1_1
    sqlite:   3.20.1-h6d8b0f3_1                 --> 3.20.1-hb898158_2    
    tk:       8.6.7-h5979e9b_1                  --> 8.6.7-hc745277_3     
    xz:       5.2.3-h2bcbf08_1                  --> 5.2.3-h55aa19d_2     
    yaml:     0.1.6-0               conda-forge --> 0.1.7-h014fa73_2     
    zeromq:   4.2.2-hb0b69da_1                  --> 4.2.2-hbedb6e5_2     
    zlib:     1.2.11-hfbfcf68_1                 --> 1.2.11-ha838bed_2    

The following packages will be SUPERSEDED by a higher-priority channel:

    libxslt:  1.1.29-5              conda-forge --> 1.1.29-hcf9102b_5    
    pyyaml:   3.12-py27_1           conda-forge --> 3.12-py27h2d70dd7_1
```
