### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by maximazzik** [ContinuumIO/anaconda-issues#7157]
## Main error
Application <b>notebook</b> launch may have produced errors.
## Traceback
```
[E 08:06:02.425 NotebookApp] Exception while loading config file C:\Users\m.novopoltsev\.jupyter\jupyter_notebook_config.py
    Traceback (most recent call last):
      File "C:\Progs\Anaconda3\lib\site-packages\traitlets\config\application.py", line 562, in _load_config_files
        config = loader.load_config()
      File "C:\Progs\Anaconda3\lib\site-packages\traitlets\config\loader.py", line 457, in load_config
        self._read_file_as_dict()
      File "C:\Progs\Anaconda3\lib\site-packages\traitlets\config\loader.py", line 489, in _read_file_as_dict
        py3compat.execfile(conf_filename, namespace)
      File "C:\Progs\Anaconda3\lib\site-packages\ipython_genutils\py3compat.py", line 198, in execfile
        exec(compiler(f.read(), fname, 'exec'), glob, loc)
      File "C:\Users\m.novopoltsev\.jupyter\jupyter_notebook_config.py", line 202
        c.NotebookApp.notebook_dir = u'C:\max\Courcera\Notepads from ML Course'
                                    ^
    SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 15-16: malformed \N character escape
[I 08:06:03.330 NotebookApp] Serving notebooks from local directory: C:\Users\m.novopoltsev
[I 08:06:03.330 NotebookApp] 0 active kernels 
[I 08:06:03.330 NotebookApp] The Jupyter Notebook is running at: http://localhost:8888/?token=9116c8eb7cf71ff0e3b7ab81448c1a47daa7e5752459e14f
[I 08:06:03.330 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 08:06:03.331 NotebookApp]

**Comment by goanpeca** [comment]
@maximazzik it seems you jupyter notebook configuration is incorrect.

`u"C:\Users\m.novopoltsev\.jupyter\jupyter_notebook_config.py"`

Either change the `\` to `\\` or `/` in any path inside that folder, or erase it and start from scratch
