### ISSUE TITLE
Anaconda Navigator will not start even _after_ updating anaconda-navigator, navigator-updater

### ISSUE THREAD

**Issue by mdc713** [ContinuumIO/anaconda-issues#7201]
This _is not_ a duplicate of prior similar errors. I have tried earlier fixes and they haven't worked. I've attempted to update anaconda-navigator, navigator-update. I am running the Win 10 Enterprise, version 1709, build 16299.19, anaconda 5.0.1

Error message:
```Traceback (most recent call last):
File "C:\Users\macolli\AppData\Local\Continuum\anaconda3\lib\site-packages\psutil\_pswindows.py", line 636, in wrapper
return fun(self, *args, **kwargs)
File "C:\Users\macolli\AppData\Local\Continuum\anaconda3\lib\site-packages\psutil\_pswindows.py", line 706, in cmdline
ret = cext.proc_cmdline(self.pid)
PermissionError: [WinError 5] Access is denied

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "C:\Users\macolli\AppData\Local\Continuum\anaconda3\lib\site-packages\anaconda_navigator\exceptions.py", line 75, in exception_handler
return_value = func(*args, **kwargs)
File "C:\Users\macolli\AppData\Local\Continuum\anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 113, in start_app
if misc.load_pid() is None: # A stale lock might be around
File "C:\Users\macolli\AppData\Local\Continuum\anaconda3\lib\site-packages\anaconda_navigator\utils\misc.py", line 384, in load_pid
cmds = process.cmdline()
File "C:\Users\macolli\AppData\Local\Continuum\anaconda3\lib\site-packages\psutil\__init__.py", line 721, in cmdline
return self._proc.cmdline()
File "C:\Users\macolli\AppData\Local\Continuum\anaconda3\lib\site-packages\psutil\_pswindows.py", line 639, in wrapper
raise AccessDenied(self.pid, self._name)
psutil.AccessDenied: psutil.AccessDenied (pid=4368)```

this came _after_ I ran updates:
```
(C:\Users\macolli\AppData\Local\Continuum\anaconda3) C:\WINDOWS\system32>conda update anaconda-navigator navigator-updater
Fetching package metadata .................
Solving package specifications: .

# All requested packages already installed.
# packages in environment at C:\Users\macolli\AppData\Local\Continuum\anaconda3:
#
anaconda-navigator        1.6.9            py36hc720852_0
navigator-updater         0.1.0            py36h8a7b86b_0
```

**Comment by goanpeca** [comment]
@mdc713 see issue #1984 for more information on how to fix this.

**Comment by mdc713** [comment]
I literally just told you that didn't work. I updated, it didn't change the outcome. Windows doesn't have sudo. Please don't close until I say it is resolved, when I tell you the prior solution isn't working.

**Comment by goanpeca** [comment]
Hi @mdc713 you tried

`$ anaconda-navigator --reset` ?
