### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by akashzcoder** [ContinuumIO/anaconda-issues#7202]
## Main error
Application <b>spyder</b> launch may have produced errors.
## Traceback
```
Traceback (most recent call last):
  File "/Users/akashsingh/anaconda/bin/spyder", line 11, in <module>
    sys.exit(main())
  File "/Users/akashsingh/anaconda/lib/python2.7/site-packages/spyder/app/start.py", line 144, in main
    from spyder.app import mainwindow
  File "/Users/akashsingh/anaconda/lib/python2.7/site-packages/spyder/app/mainwindow.py", line 92, in <module>
    from qtpy import QtWebEngineWidgets  # analysis:ignore
  File "/Users/akashsingh/anaconda/lib/python2.7/site-packages/qtpy/QtWebEngineWidgets.py", line 26, in <module>
    from PyQt5.QtWebKitWidgets import QWebPage as QWebEnginePage
ImportError: No module named QtWebKitWidgets

```
## System information
```
platform: osx-64
version: 1.6.2
conda: 4.3.29
qt: 5.6.2
language: en
python: 2.7.13
os: Darwin;16.6.0;Darwin Kernel Version 16.6.0: Fri Apr 14 16:21:16 PDT 2017; root:xnu-3789.60.24~6/RELEASE_X86_64;x86_64;i386
pyqt: 5.6.0
```

**Comment by goanpeca** [comment]
Please provide the output of

```
conda list
conda info
```

**Comment by akashzcoder** [comment]
**conda list**
# packages in environment at /Users/akashsingh/anaconda:
#
_license                  1.1                      py27_1  
alabaster                 0.7.10                   py27_0  
anaconda                  custom                   py27_0  
anaconda-client           1.6.3                    py27_0  
anaconda-navigator        1.6.2                    py27_0  
anaconda-project          0.6.0                    py27_0  
appnope                   0.1.0                    py27_0  
appscript                 1.0.1                    py27_0  
asn1crypto                0.22.0                   py27_0  
astroid                   1.5.3                     <pip>
astroid                   1.4.9                    py27_0  
attrs                     17.2.0                    <pip>
Automat                   0.6.0                     <pip>
Babel                     2.5.1                     <pip>
babel                     2.4.0                    py27_0  
backports                 1.0                      py27_0  
backports.functools_lru_cache 1.4              py27h2aca819_1  
backports.weakref         1.0.post1                 <pip>
backports_abc             0.5                      py27_0  
beautifulsoup4            4.6.0                    py27_0  
bitarray                  0.8.1                    py27_0  
blas                      1.1                    openblas    conda-forge
bleach                    1.5.0                    py27_0  
bleach                    2.1.1                     <pip>
boto                      2.46.1                   py27_0  
cdecimal                  2.3                      py27_2  
certifi                   2017.11.5                 <pip>
cffi                      1.10.0                   py27_0  
chardet                   3.0.3                    py27_0  
chardet                   3.0.4                     <pip>
click                     6.7                      py27_0  
cloudpickle               0.2.2                    py27_0  
clyent                    1.2.2                    py27_0  
colorama                  0.3.9                    py27_0  
conda                     4.3.29                   py27_0    conda-forge
conda-env                 2.6.0                         0    conda-forge
configparser              3.5.0                    py27_0  
constantly                15.1.0                    <pip>
contextlib2               0.5.5                    py27_0  
cryptography              2.0.3                    py27_0    conda-forge
cssselect                 1.0.1                     <pip>
curl                      7.55.1                        0    conda-forge
cycler                    0.10.0                   py27_0  
cython                    0.25.2                   py27_0  
cytoolz                   0.8.2                    py27_0  
dask-core                 0.15.4                     py_0    conda-forge
decorator                 4.0.11                   py27_0  
decorator                 4.1.2                     <pip>
defusedxml                0.5.0                     <pip>
docutils                  0.14                      <pip>
docutils                  0.13.1                   py27_0  
entrypoints               0.2.3                     <pip>
entrypoints               0.2.2                    py27_1  
enum34                    1.1.6                    py27_0  
et_xmlfile                1.0.1                    py27_0  
ete3                      3.0.0b35                  <pip>
fastcache                 1.0.2                    py27_1  
flask                     0.12.2                   py27_0  
flask-cors                3.0.2                    py27_0  
Flask-Login               0.4.0                     <pip>
freetype                  2.8                  h143eb01_0  
funcsigs                  1.0.2                    py27_0  
functools32               3.2.3.2                  py27_0  
futures                   3.1.1                    py27_0  
get_terminal_size         1.0.0                    py27_0  
gevent                    1.2.1                    py27_0  
greenlet                  0.4.12                   py27_0  
grin                      1.2.1                    py27_3  
hdf5                      1.8.17                        1  
heapdict                  1.0.0                    py27_1  
html5lib                  0.999                    py27_0  
html5lib                  1.0b10                    <pip>
hyperlink                 17.3.1                    <pip>
icu                       54.1                          0  
idna                      2.5                      py27_0  
idna                      2.6                       <pip>
imagesize                 0.7.1                    py27_0  
incremental               17.5.0                    <pip>
intel-openmp              2018.0.0             h68bdfb3_7  
ipaddress                 1.0.18                   py27_0  
ipykernel                 4.6.1                    py27_0  
ipython                   5.3.0                    py27_0  
ipython                   5.5.0                     <pip>
ipython_genutils          0.2.0                    py27_0  
ipywidgets                7.0.4                     <pip>
ipywidgets                6.0.0                    py27_0  
isort                     4.2.15                    <pip>
isort                     4.2.5                    py27_0  
itsdangerous              0.24                     py27_0  
jbig                      2.1                           0  
jdcal                     1.3                      py27_0  
jedi                      0.10.2                   py27_2  
jedi                      0.11.0                    <pip>
jinja2                    2.9.6                    py27_0  
Jinja2                    2.10                      <pip>
jpeg                      9b                            0  
jsonschema                2.6.0                    py27_0  
jupyter                   1.0.0            py27hec63c99_0  
jupyter                   1.0.0                     <pip>
jupyter-client            5.1.0                     <pip>
jupyter-console           5.2.0                     <pip>
jupyter-core              4.4.0                     <pip>
jupyter_client            5.0.1                    py27_0  
jupyter_console           5.1.0                    py27_0  
jupyter_core              4.3.0                    py27_0  
Keras                     2.0.8                     <pip>
krb5                      1.14.2                        0    conda-forge
lazy-object-proxy         1.3.1                     <pip>
lazy-object-proxy         1.2.2                    py27_0  
libcxx                    4.0.1                h579ed51_0  
libcxxabi                 4.0.1                hebd6815_0  
libgfortran               3.0.1                h93005f0_2  
libiconv                  1.14                          0  
libpng                    1.6.32               hce72d48_2  
libprotobuf               3.2.0                         0  
libssh2                   1.8.0                         2    conda-forge
libtiff                   4.0.8                h8cd0352_9  
libxml2                   2.9.4                         0  
libxslt                   1.1.29                        0  
llvmlite                  0.20.0                   py27_0  
locarna                   1.9.2                pl5.22.0_0    bioconda
locket                    0.2.0                    py27_1  
lxml                      3.7.3                    py27_0  
Markdown                  2.6.9                     <pip>
MarkupSafe                1.0                       <pip>
markupsafe                0.23                     py27_2  
mccabe                    0.6.1                     <pip>
mistune                   0.7.4                    py27_0  
mistune                   0.8.1                     <pip>
mkl                       2018.0.0             h5ef208c_6  
mock                      2.0.0                    py27_0  
mpmath                    0.19                     py27_1  
msgpack-python            0.4.8                    py27_0  
multipledispatch          0.4.9                    py27_0  
MySQL-python              1.2.5                     <pip>
navigator-updater         0.1.0                    py27_0  
nbconvert                 5.1.1                    py27_0  
nbconvert                 5.3.1                     <pip>
nbformat                  4.4.0                     <pip>
nbformat                  4.3.0                    py27_0  
networkx                  2.0                       <pip>
networkx                  1.11                     py27_0  
nltk                      3.2.3                    py27_0  
nomkl                     1.0                           0  
nose                      1.3.7                    py27_1  
notebook                  5.2.1                     <pip>
notebook                  5.0.0                    py27_0  
numpy                     1.13.3                    <pip>
numpy                     1.13.3          py27_blas_openblas_200  [blas_openblas]  conda-forge
numpydoc                  0.7.0                     <pip>
numpydoc                  0.6.0                    py27_0  
olefile                   0.44                     py27_0  
openblas                  0.2.19                        2    conda-forge
openpyxl                  2.4.7                    py27_0  
openssl                   1.0.1k                        1  
packaging                 16.8                     py27_0  
pandocfilters             1.4.1                    py27_0  
pandocfilters             1.4.2                     <pip>
parsel                    1.2.0                     <pip>
parso                     0.1.0                     <pip>
partd                     0.3.8                    py27_0  
path.py                   10.3.1                   py27_0  
pathlib                   1.0.1                     <pip>
pathlib2                  2.2.1                    py27_0  
pathlib2                  2.3.0                     <pip>
pbr                       3.1.1            py27h45d16fa_0  
pep8                      1.7.0                    py27_0  
perl                      5.22.0.1                      0    conda-forge
pexpect                   4.3.0                     <pip>
pexpect                   4.2.1                    py27_0  
pickleshare               0.7.4                    py27_0  
Pillow                    4.3.0                     <pip>
pillow                    4.2.1            py27h2cf1d5f_0  
pip                       9.0.1                    py27_1  
ply                       3.10                     py27_0  
prompt-toolkit            1.0.15                    <pip>
prompt_toolkit            1.0.14                   py27_0  
protobuf                  3.2.0                    py27_0  
protobuf                  3.4.0                     <pip>
psutil                    5.4.1                     <pip>
psutil                    5.2.2                    py27_0  
ptyprocess                0.5.2                     <pip>
ptyprocess                0.5.1                    py27_0  
py                        1.4.33                   py27_0  
pyasn1                    0.3.5                     <pip>
pyasn1-modules            0.1.4                     <pip>
pyaudio                   0.2.7                    py27_0  
pycodestyle               2.3.1                     <pip>
pycosat                   0.6.2                    py27_0  
pycparser                 2.17                     py27_0  
pycrypto                  2.6.1                    py27_6  
pycurl                    7.19.0                   py27_1  
PyDispatcher              2.0.5                     <pip>
pyflakes                  1.5.0                    py27_0  
pyflakes                  1.6.0                     <pip>
pygments                  2.2.0                    py27_0  
pylint                    1.7.4                     <pip>
pylint                    1.6.4                    py27_1  
pymorph                   0.96                      <pip>
PyMySQL                   0.7.11                    <pip>
pyodbc                    4.0.16                   py27_0  
pyopenssl                 17.0.0                   py27_0  
pyparsing                 2.1.4                    py27_0  
pyparsing                 2.2.0                     <pip>
pyqt                      5.6.0                    py27_1  
pyquery                   1.2.17                    <pip>
pyspider                  0.3.9                     <pip>
pytest                    3.0.7                    py27_0  
python                    2.7.9                         1  
python-dateutil           2.6.1                     <pip>
python-dateutil           2.6.0                    py27_0  
python.app                1.2                      py27_4  
pytz                      2017.3                    <pip>
pytz                      2017.2                   py27_0  
pyyaml                    3.12                     py27_0  
pyzmq                     16.0.2                   py27_0  
pyzmq                     16.0.3                    <pip>
qt                        5.6.2                         2  
qtawesome                 0.4.4                    py27_0  
qtconsole                 4.3.0                    py27_0  
qtconsole                 4.3.1                     <pip>
qtpy                      1.2.1                    py27_0  
QtPy                      1.3.1                     <pip>
queuelib                  1.4.2                     <pip>
readline                  6.2                           2  
requests                  2.14.2                   py27_0  
requests                  2.18.4                    <pip>
rope                      0.10.7                    <pip>
rope                      0.9.4                    py27_1  
ruamel_yaml               0.11.14                  py27_1  
scandir                   1.6                       <pip>
scandir                   1.5                      py27_0  
scikit-image              0.13.1                    <pip>
scikit-learn              0.19.1                    <pip>
scikit-learn              0.19.1          py27_blas_openblas_200  [blas_openblas]  conda-forge
scipy                     0.19.1          py27_blas_openblas_202  [blas_openblas]  conda-forge
scipy                     1.0.0                     <pip>
Scrapy                    1.4.0                     <pip>
service-identity          17.0.0                    <pip>
setuptools                27.2.0                   py27_0  
setuptools                36.7.1                    <pip>
simplegeneric             0.8.1                    py27_1  
singledispatch            3.4.0.3                  py27_0  
sip                       4.18                     py27_0  
six                       1.11.0                    <pip>
six                       1.10.0                   py27_0  
snowballstemmer           1.2.1                    py27_0  
sortedcollections         0.5.3                    py27_0  
sortedcontainers          1.5.7                    py27_0  
Sphinx                    1.6.5                     <pip>
sphinx                    1.5.6                    py27_0  
sphinxcontrib-websupport  1.0.1                     <pip>
spyder                    3.1.4                    py27_0  
spyder                    3.2.4                     <pip>
sqlalchemy                1.1.9                    py27_0  
sqlite                    3.13.0                        0  
ssl_match_hostname        3.4.0.2                  py27_1  
subprocess32              3.2.7                    py27_0  
sympy                     1.0                      py27_0  
tbb                       4.3_20141023                  0    menpo
tblib                     1.3.2                    py27_0  
tensorflow                1.4.0                     <pip>
tensorflow-tensorboard    0.4.0rc2                  <pip>
terminado                 0.6                      py27_0  
testpath                  0.3.1                     <pip>
testpath                  0.3                      py27_0  
tflearn                   0.3.2                     <pip>
tk                        8.5.18                        0  
toolz                     0.8.2                    py27_0  
tornado                   4.5.2                     <pip>
tornado                   4.5.1                    py27_0  
traitlets                 4.3.2                    py27_0  
Twisted                   17.5.0                    <pip>
typing                    3.6.2                     <pip>
u-msgpack-python          2.4.1                     <pip>
unicodecsv                0.14.1                   py27_0  
unixodbc                  2.3.4                         0  
urllib3                   1.22                      <pip>
viennarna                 2.3.5                         0    bioconda
virtualenv                15.1.0                    <pip>
w3lib                     1.18.0                    <pip>
wcwidth                   0.1.7                    py27_0  
webencodings              0.5.1                     <pip>
werkzeug                  0.12.2                   py27_0  
wheel                     0.29.0                   py27_0  
wheel                     0.30.0                    <pip>
widgetsnbextension        3.0.7                     <pip>
widgetsnbextension        2.0.0                    py27_0  
wrapt                     1.10.10                  py27_0  
wrapt                     1.10.11                   <pip>
WsgiDAV                   2.2.4                     <pip>
xlrd                      1.0.0                    py27_0  
xlsxwriter                0.9.6                    py27_0  
xlwings                   0.10.4                   py27_0  
xlwt                      1.2.0                    py27_0  
xz                        5.2.3                ha24016e_1  
yaml                      0.1.6                         0  
zict                      0.1.2                    py27_0  
zlib                      1.2.11               h60db283_1  
zope.interface            4.4.2                     <pip>



**conda info**

Current conda install:

               platform : osx-64
          conda version : 4.3.29
       conda is private : False
      conda-env version : 4.3.29
    conda-build version : not installed
         python version : 2.7.9.final.0
       requests version : 2.18.4
       root environment : /Users/akashsingh/anaconda  (writable)
    default environment : /Users/akashsingh/anaconda
       envs directories : /Users/akashsingh/anaconda/envs
                          /Users/akashsingh/.conda/envs
          package cache : /Users/akashsingh/anaconda/pkgs
                          /Users/akashsingh/.conda/pkgs
           channel URLs : https://conda.anaconda.org/conda-forge/osx-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://conda.anaconda.org/anaconda-fusion/osx-64
                          https://conda.anaconda.org/anaconda-fusion/noarch
                          https://conda.anaconda.org/bioconda/osx-64
                          https://conda.anaconda.org/bioconda/noarch
                          https://conda.anaconda.org/r/osx-64
                          https://conda.anaconda.org/r/noarch
                          https://repo.continuum.io/pkgs/main/osx-64
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/osx-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/osx-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/osx-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : /Users/akashsingh/.condarc
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.29 requests/2.18.4 CPython/2.7.9 Darwin/16.6.0 OSX/10.12.5    
                UID:GID : 501:20
