### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by KimuraTian** [ContinuumIO/anaconda-issues#7209]
## Main error
Application <b>notebook</b> launch may have produced errors.
## Traceback
```
Traceback (most recent call last):
  File "C:\Users\mucun\Anaconda3\Scripts\jupyter-notebook-script.py", line 3, in <module>
    import notebook.notebookapp
  File "C:\Users\mucun\Anaconda3\lib\site-packages\notebook\notebookapp.py", line 39, in <module>
    from zmq.eventloop import ioloop
  File "C:\Users\mucun\Anaconda3\lib\site-packages\zmq\__init__.py", line 34, in <module>
    from zmq import backend
  File "C:\Users\mucun\Anaconda3\lib\site-packages\zmq\backend\__init__.py", line 40, in <module>
    reraise(*exc_info)
  File "C:\Users\mucun\Anaconda3\lib\site-packages\zmq\utils\sixcerpt.py", line 34, in reraise
    raise value
  File "C:\Users\mucun\Anaconda3\lib\site-packages\zmq\backend\__init__.py", line 27, in <module>
    _ns = select_backend(first)
  File "C:\Users\mucun\Anaconda3\lib\site-packages\zmq\backend\select.py", line 26, in select_backend
    mod = __import__(name, fromlist=public_api)
  File "C:\Users\mucun\Anaconda3\lib\site-packages\zmq\backend\cython\__init__.py", line 6, in <module>
    from . import (constants, error, message, context,
ImportError: cannot import name 'constants'

```
## System information
```
python: 3.6.1
language: en_US
os: Windows;10;10.0.15063;AMD64;Intel64 Family 6 Model 94 Stepping 3, GenuineIntel
version: 1.6.2
platform: win-64
qt: 5.6.2
pyqt: 5.6.0
conda: 4.3.27
```

**Comment by goanpeca** [comment]
Try uninstalling and reinstalling pyzmq.

See #https://github.com/jupyter/notebook/issues/636

**Comment by KimuraTian** [comment]
@goanpeca Thanks.
