### ISSUE TITLE
Placeholder: Navigator Error

### ISSUE THREAD

**Issue by Caesaryang** [ContinuumIO/anaconda-issues#7230]
## Main error
Application <b>spyder</b> launch may have produced errors.
## Traceback
```
Traceback (most recent call last):
  File "/Users/Fengkai/anaconda/lib/python3.6/site-packages/qtpy/QtWebEngineWidgets.py", line 22, in <module>
    from PyQt5.QtWebEngineWidgets import QWebEnginePage
ImportError: dlopen(/Users/Fengkai/anaconda/lib/python3.6/site-packages/PyQt5/QtWebEngineWidgets.so, 2): Library not loaded: @rpath/libQt5WebEngineCore.5.dylib
  Referenced from: /Users/Fengkai/anaconda/lib/python3.6/site-packages/PyQt5/QtWebEngineWidgets.so
  Reason: image not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/Fengkai/anaconda/bin/spyder", line 6, in <module>
    sys.exit(spyder.app.start.main())
  File "/Users/Fengkai/anaconda/lib/python3.6/site-packages/spyder/app/start.py", line 140, in main
    from spyder.app import mainwindow
  File "/Users/Fengkai/anaconda/lib/python3.6/site-packages/spyder/app/mainwindow.py", line 92, in <module>
    from qtpy import QtWebEngineWidgets  # analysis:ignore
  File "/Users/Fengkai/anaconda/lib/python3.6/site-packages/qtpy/QtWebEngineWidgets.py", line 26, in <module>
    from PyQt5.QtWebKitWidgets import QWebPage as QWebEnginePage
ModuleNotFoundError: No module named 'PyQt5.QtWebKitWidgets'

```
## System information
```
python: 3.6.1
language: en
os: Darwin;16.7.0;Darwin Kernel Version 16.7.0: Wed Oct  4 00:17:00 PDT 2017; root:xnu-3789.71.6~1/RELEASE_X86_64;x86_64;i386
version: 1.6.2
platform: osx-64
qt: 5.6.2
pyqt: 5.6.0
conda: 4.3.25
```

**Comment by goanpeca** [comment]
@ccordoba12 do you know the cause of this issue, it has come up quite a few times now. Thoughts?

**Comment by goanpeca** [comment]
@ccordoba12 @mingwandroid using this issue as the main one to resolve this problem

**Comment by ccordoba12** [comment]
I really don't know. It's like `libQt5WebEngineCore.5.dylib` wouldn't be present in `anaconda/lib`.

@mingwandroid, do you know what could be happening here?

**Comment by mingwandroid** [comment]
conda update --all would be my first thing to do here. The reporter is running pretty old stuff here.

**Comment by mingwandroid** [comment]
If `conda update --all` does not fix this, then please re-run `spyder` from an activated `Terminal` as follows:

```
DYLD_PRINT_LIBRARIES=1 DYLD_PRINT_BINDINGS=1 DYLD_PREBIND_DEBUG=1 DYLD_PRINT_INITIALIZERS=1 DYLD_PRINT_APIS=1 python $(which spyder)
```

and copy the result here.

**Comment by goanpeca** [comment]
Stale issue, closing.
