### ISSUE TITLE
scipy.special._ufuncs not exsisted

### ISSUE THREAD

**Issue by idchiang** [ContinuumIO/anaconda-issues#7231]
When I tried to import scipy.integrate.cumtrapz, an error message showed:

File "C:\Users\jxxxx\Anaconda3\lib\site-packages\scipy\special_init_.py", line 640, in 
from ._ufuncs import *
ImportError: DLL load failed: The specified module could not be found.

#Reproducing code example:

from scipy.integrate import cumtrapz

#Error message:

File "C:\Users\jxxxx\Anaconda3\lib\site-packages\scipy\special_init_.py", line 640, in 
from ._ufuncs import *
ImportError: DLL load failed: The specified module could not be found.

#Version information:
Anaconda3 for windows 10
Scipy 1.0.0

**Comment by alokreddy** [comment]
I am facing the same issue when using lifelines library for survival analysis.
 Error information below:

```
ImportError                               Traceback (most recent call last)
<ipython-input-1-ca4b8facbf77> in <module>()
      5 from datetime import date
      6 from bokeh.io import output_notebook
----> 7 from lifelines import KaplanMeierFitter

C:\Anaconda\lib\site-packages\lifelines\__init__.py in <module>()
      1 # -*- coding: utf-8 -*-
----> 2 from .estimation import KaplanMeierFitter, NelsonAalenFitter, \
      3     AalenAdditiveFitter, BreslowFlemingHarringtonFitter, CoxPHFitter, \
      4     WeibullFitter, ExponentialFitter, CoxTimeVaryingFitter
      5 

C:\Anaconda\lib\site-packages\lifelines\estimation.py in <module>()
      1 # -*- coding: utf-8 -*-
----> 2 from lifelines.fitters import BaseFitter
      3 from lifelines.fitters.weibull_fitter import WeibullFitter
      4 from lifelines.fitters.exponential_fitter import ExponentialFitter
      5 from lifelines.fitters.nelson_aalen_fitter import NelsonAalenFitter

C:\Anaconda\lib\site-packages\lifelines\fitters\__init__.py in <module>()
      6 import pandas as pd
      7 
----> 8 from lifelines.plotting import plot_estimate
      9 from lifelines.utils import qth_survival_times
     10 

C:\Anaconda\lib\site-packages\lifelines\plotting.py in <module>()
      3 
      4 import numpy as np
----> 5 from .utils import coalesce
      6 
      7 

C:\Anaconda\lib\site-packages\lifelines\utils\__init__.py in <module>()
      6 import numpy as np
      7 from numpy.linalg import solve
----> 8 from scipy import stats
      9 import pandas as pd
     10 from pandas import to_datetime

C:\Anaconda\lib\site-packages\scipy\stats\__init__.py in <module>()
    341 from __future__ import division, print_function, absolute_import
    342 
--> 343 from .stats import *
    344 from .distributions import *
    345 from .morestats import *

C:\Anaconda\lib\site-packages\scipy\stats\stats.py in <module>()
    167 from scipy._lib.six import callable, string_types
    168 from scipy._lib._version import NumpyVersion
--> 169 import scipy.special as special
    170 import scipy.linalg as linalg
    171 from . import distributions

C:\Anaconda\lib\site-packages\scipy\special\__init__.py in <module>()
    638 from .sf_error import SpecialFunctionWarning, SpecialFunctionError
    639 
--> 640 from ._ufuncs import *
    641 
    642 from .basic import *

ImportError: DLL load failed: The specified module could not be found.
```

There are many solutions which suggest installing .whl files of numpy and scipy be installed from this link[https://www.lfd.uci.edu/~gohlke/pythonlibs/](url)

**Comment by dmopalmer** [comment]
On Windows 7, I fixed my scipy._ufuncs `ImportError: DLL load failed: The specified module could not be found.` problem by 
```
conda install mkl
```
which seems to be an unspecified package requirement.

May be related to #956, #793, and others.
