### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by zhegufang** [ContinuumIO/anaconda-issues#7233]
## Main error
Application <b>notebook</b> launch may have produced errors.
## Traceback
```
[W 10:53:01.602 NotebookApp] Error loading server extension jupyter_nbextensions_configurator
    Traceback (most recent call last):
      File "D:\anaconda3\lib\site-packages\notebook\notebookapp.py", line 1271, in init_server_extensions
        mod = importlib.import_module(modulename)
      File "D:\anaconda3\lib\importlib\__init__.py", line 126, in import_module
        return _bootstrap._gcd_import(name[level:], package, level)
      File "<frozen importlib._bootstrap>", line 978, in _gcd_import
      File "<frozen importlib._bootstrap>", line 961, in _find_and_load
      File "<frozen importlib._bootstrap>", line 948, in _find_and_load_unlocked
    ModuleNotFoundError: No module named 'jupyter_nbextensions_configurator'
[I 10:53:01.824 NotebookApp] Serving notebooks from local directory: D:\work\ZGF
[I 10:53:01.824 NotebookApp] 0 active kernels 
[I 10:53:01.824 NotebookApp] The Jupyter Notebook is running at: http://localhost:8888/?token=4f00bcfd10a6a6f048ef3693edc2a062e2b839d656657e46
[I 10:53:01.824 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 10:53:01.826 NotebookApp] 
    
    Copy/paste this URL into your browser when you connect for the first time,
    to login with a token:
        http://localhost:8888/?token=4f00bcfd10a6a6f048ef3693edc2a062e2b839d656657e46
[I 10:53:02.153 NotebookApp] Accepting one-time-token-authenticated connection from 127.0.0.1
[W 10:53:02.850 NotebookApp] 404 GET /nbextensions/nbextensions_configurator/tree_tab/main.js?v=20171110105300 (127.0.0.1) 16.0

**Comment by goanpeca** [comment]
@bollwyvl thoughts?
