### ISSUE TITLE
UnicodeDecodeError: 'utf8' codec can't decode byte 0x88 in position 2: invalid start byte

### ISSUE THREAD

**Issue by pinkman61** [ContinuumIO/anaconda-issues#7256]
Please tell me how to resolve this. I tried few things but didn't work!

pinkman@pinkman:~$ anaconda-navigator
Traceback (most recent call last):
  File "/home/pinkman/anaconda2/bin/anaconda-navigator", line 11, in <module>
    sys.exit(main())
  File "/home/pinkman/anaconda2/lib/python2.7/site-packages/anaconda_navigator/app/main.py", line 125, in main
    from anaconda_navigator.utils.logs import clean_logs
  File "/home/pinkman/anaconda2/lib/python2.7/site-packages/anaconda_navigator/utils/logs.py", line 18, in <module>
    from anaconda_navigator.config import (LOG_FILENAME, LOG_FOLDER,
  File "/home/pinkman/anaconda2/lib/python2.7/site-packages/anaconda_navigator/config/__init__.py", line 24, in <module>
    from anaconda_navigator.config.main import CONF
  File "/home/pinkman/anaconda2/lib/python2.7/site-packages/anaconda_navigator/config/main.py", line 67, in <module>
    raw_mode=True,
  File "/home/pinkman/anaconda2/lib/python2.7/site-packages/anaconda_navigator/config/user.py", line 221, in __init__
    self.load_from_ini()
  File "/home/pinkman/anaconda2/lib/python2.7/site-packages/anaconda_navigator/config/user.py", line 275, in load_from_ini
    self.readfp(conf_file)
  File "/home/pinkman/anaconda2/lib/python2.7/ConfigParser.py", line 324, in readfp
    self._read(fp, filename)
  File "/home/pinkman/anaconda2/lib/python2.7/ConfigParser.py", line 479, in _read
    line = fp.readline()
  File "/home/pinkman/anaconda2/lib/python2.7/codecs.py", line 690, in readline
    return self.reader.readline(size)
  File "/home/pinkman/anaconda2/lib/python2.7/codecs.py", line 545, in readline
    data = self.read(readsize, firstline=True)
  File "/home/pinkman/anaconda2/lib/python2.7/codecs.py", line 492, in read
    newchars, decodedbytes = self.decode(data, self.errors)
UnicodeDecodeError: 'utf8' codec can't decode byte 0x88 in position 2: invalid start byte

------------------------------------------------------------------------------------------------------------------------------------------

pinkman@pinkman:~$ jupyter kernelspec list
Available kernels:
  python2    /home/pinkman/.local/share/jupyter/kernels/python2

------------------------------------------------------------------------------------------------------------------------------------------

**Comment by goanpeca** [comment]
@pinkman61 please reset naviagtor and try again

```
$ anaconda-navigator --reset
```

---

Please remember to update to the latest version of Navigator to include
the latest fixes.

Open a terminal (on Linux or Mac) or the Anaconda Command Prompt (on windows)
and type:

```
$ conda update conda
$ conda update anaconda-navigator
$ conda update navigator-updater
```

**Comment by pinkman61** [comment]
$ anaconda-navigator --reset

--------------------------------------------------------------------------------------------------------------------------------------------

This is not working 

Error:

pinkman@pinkman:~$ anaconda-navigator --reset

Anaconda Navigator configuration reset...


Traceback (most recent call last):
  File "/home/pinkman/anaconda2/bin/anaconda-navigator", line 11, in <module>
    sys.exit(main())
  File "/home/pinkman/anaconda2/lib/python2.7/site-packages/anaconda_navigator/app/main.py", line 101, in main
    from anaconda_navigator.config import CONF_PATH
  File "/home/pinkman/anaconda2/lib/python2.7/site-packages/anaconda_navigator/config/__init__.py", line 24, in <module>
    from anaconda_navigator.config.main import CONF
  File "/home/pinkman/anaconda2/lib/python2.7/site-packages/anaconda_navigator/config/main.py", line 67, in <module>
    raw_mode=True,
  File "/home/pinkman/anaconda2/lib/python2.7/site-packages/anaconda_navigator/config/user.py", line 221, in __init__
    self.load_from_ini()
  File "/home/pinkman/anaconda2/lib/python2.7/site-packages/anaconda_navigator/config/user.py", line 275, in load_from_ini
    self.readfp(conf_file)
  File "/home/pinkman/anaconda2/lib/python2.7/ConfigParser.py", line 324, in readfp
    self._read(fp, filename)
  File "/home/pinkman/anaconda2/lib/python2.7/ConfigParser.py", line 479, in _read
    line = fp.readline()
  File "/home/pinkman/anaconda2/lib/python2.7/codecs.py", line 690, in readline
    return self.reader.readline(size)
  File "/home/pinkman/anaconda2/lib/python2.7/codecs.py", line 545, in readline
    data = self.read(readsize, firstline=True)
  File "/home/pinkman/anaconda2/lib/python2.7/codecs.py", line 492, in read
    newchars, decodedbytes = self.decode(data, self.errors)
UnicodeDecodeError: 'utf8' codec can't decode byte 0x88 in position 2: invalid start byte

Please share some other way!

**Comment by goanpeca** [comment]
@pinkman61 not really sure what is going on. Have you tried using Anaconda/Miniconda with python3?

**Comment by pinkman61** [comment]
Not using python3 as of now.
But this thing was working fine and suddenly stopped, I don't know what went wrong!
Though I can/have to access app independently!

**Comment by goanpeca** [comment]
@pinkman61try deleting this folder

`$ rm -rf /home/pinkman/.anaconda`

**Comment by pinkman61** [comment]
Magic! It worked!
Can you please comment on the issue?
what is the motive of this operation?

**Comment by goanpeca** [comment]
@pinkman61 navigator keeps logs of its operation, somehow one of these log files got corrupted, so we just removed the log files. That is what navigator --reset should have done, but was not working either

**Comment by jeethjoseph** [comment]
I had the same issue. This worked for me.
conda install anaconda-clean
conda-clean --yes

**Comment by 292301001** [comment]
@goanpeca = 'hero'

**Comment by 292301001** [comment]
nvm I'm still having pretty much the same problem. python3.6.4 still runs through anaconda in terminal tho dunno if that helps. I've tryed all steps listed above

~$ anaconda-navigator
 Traceback (most recent call last):
  File "/home/xenozombie/anaconda3/bin/anaconda-navigator", line 11, in <module>
    sys.exit(main())
  File "/home/xenozombie/anaconda3/lib/python3.6/site-packages/anaconda_navigator/app/main.py", line 125, in main
    from anaconda_navigator.utils.logs import clean_logs
  File "/home/xenozombie/anaconda3/lib/python3.6/site-packages/anaconda_navigator/utils/logs.py", line 18, in <module>
    from anaconda_navigator.config import (LOG_FILENAME, LOG_FOLDER,
  File "/home/xenozombie/anaconda3/lib/python3.6/site-packages/anaconda_navigator/config/__init__.py", line 27, in <module>
    from anaconda_navigator.config.main import CONF
  File "/home/xenozombie/anaconda3/lib/python3.6/site-packages/anaconda_navigator/config/main.py", line 67, in <module>
    raw_mode=True,
  File "/home/xenozombie/anaconda3/lib/python3.6/site-packages/anaconda_navigator/config/user.py", line 219, in __init__
    self.load_from_ini()
  File "/home/xenozombie/anaconda3/lib/python3.6/site-packages/anaconda_navigator/config/user.py", line 277, in load_from_ini
    self.read(self.filename(), encoding='utf-8')
  File "/home/xenozombie/anaconda3/lib/python3.6/configparser.py", line 697, in read
    self._read(fp, filename)
  File "/home/xenozombie/anaconda3/lib/python3.6/configparser.py", line 1015, in _read
    for lineno, line in enumerate(fp, start=1):
  File "/home/xenozombie/anaconda3/lib/python3.6/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf0 in position 2: invalid continuation byte

**Comment by giupo** [comment]
I'd look after any ini file in `$HOME/.anaconda`, position 2 and check what character is there: probably encoding handling of some user input (you first name? your last name?...) was not handled properly by Anaconda.

my 2 cents.

**Comment by yoyo-sincerely** [comment]
open cmd
```
chcp 65001
anaconda-navigator
```
Perfectly solved the problem

**Comment by haoruilee** [comment]
> chcp 65001
> anaconda-navigator

Magic! I have wasted one hour on this problem!
Can you explain why it works?

**Comment by sisrfeng** [comment]
`conda init zsh`
falled

copy 
```
13 # >>> conda initialize >>>
 12 # !! Contents within this block are managed by 'conda init' !!
 11 __conda_setup="$('/root/anaconda3/bin/conda' 'shell.zsh' 'hook' 2> /dev/null)"
 10 if [ $? -eq 0 ]; then
  9     eval "$__conda_setup"
  8 else
  7     if [ -f "/root/anaconda3/etc/profile.d/conda.sh" ]; then
  6     ┊   . "/root/anaconda3/etc/profile.d/conda.sh"
  5     else
  4     ┊   export PATH="/root/anaconda3/bin:$PATH"
  3     fi
  2 fi
  1 unset __conda_setup
  0 # <<< conda initialize <<<
```
into ~/.zsrhc

everything is OK.


`conda init bash`
success.
then I 
`mv ~/.zshrc  ~/.zshrc_bk`
go into bash and
`conda init zsh`
success

then I remove ~/.zshrc, and put some Chinese in commented line in an empty ~/.zshrc
go into bash and
`conda init zsh`
success

then
`mv ~/.zshrc_bk  ~/.zshrc`

```
(base) root@wf:/# conda init zsh

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/root/anaconda3/lib/python3.8/site-packages/conda/exceptions.py", line 1079, in __call__
        return func(*args, **kwargs)
      File "/root/anaconda3/lib/python3.8/site-packages/conda/cli/main.py", line 84, in _main
        exit_code = do_call(args, p)
      File "/root/anaconda3/lib/python3.8/site-packages/conda/cli/conda_argparse.py", line 83, in do_call
        return getattr(module, func_name)(args, parser)
      File "/root/anaconda3/lib/python3.8/site-packages/conda/cli/main_init.py", line 50, in execute
        return initialize(context.conda_prefix, selected_shells, for_user, args.system,
      File "/root/anaconda3/lib/python3.8/site-packages/conda/core/initialize.py", line 119, in initialize
        run_plan(plan2)
      File "/root/anaconda3/lib/python3.8/site-packages/conda/core/initialize.py", line 637, in run_plan
        result = globals()[step['function']](*step.get('args', ()), **step.get('kwargs', {}))
      File "/root/anaconda3/lib/python3.8/site-packages/conda/core/initialize.py", line 1243, in init_sh_user
        rc_content = fh.read()
      File "/root/anaconda3/lib/python3.8/codecs.py", line 322, in decode
        (result, consumed) = self._buffer_decode(data, self.errors, final)
    UnicodeDecodeError: 'utf-8' codec can't decode byte 0xbc in position 9175: invalid start byte

`$ /root/anaconda3/bin/conda init zsh`

  environment variables:
                ALL_PROXY=<set>
                 CIO_TEST=<not set>
        CONDA_DEFAULT_ENV=base
                CONDA_EXE=/root/anaconda3/bin/conda
             CONDA_PREFIX=/root/anaconda3
    CONDA_PROMPT_MODIFIER=(base)
         CONDA_PYTHON_EXE=/root/anaconda3/bin/python
               CONDA_ROOT=/root/anaconda3
              CONDA_SHLVL=1
           CURL_CA_BUNDLE=<not set>
                     PATH=/root/anaconda3/bin:/root/anaconda3/bin:/root/anaconda3/condabin:/usr/
                          local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/root/.antigen
                          /bundles/sorin-ionescu/prezto:/root/.antigen/bundles/Vifon/deer:/root/
                          .antigen/bundles/zdharma/fast-syntax-
                          highlighting:/root/.antigen/bundles/zsh-users/zsh-
                          autosuggestions:/root/.antigen/bundles/willghatch/zsh-
                          cdr:/root/.antigen/bundles/zsh-users/zaw:/root/.antigen/bundles/zsh-
                          users/zaw/functions:/root/usr/local/bin:/root/.cargo/bin
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>

     active environment : base
    active env location : /root/anaconda3
            shell level : 1
       user config file : /root/.condarc
 populated config files : /root/.condarc
          conda version : 4.9.1
    conda-build version : 3.18.11
         python version : 3.8.3.final.0
       virtual packages : __cuda=10.1=0
                          __glibc=2.27=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /root/anaconda3  (writable)
           channel URLs : https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/linux-64
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /root/anaconda3/pkgs
                          /root/.conda/pkgs
       envs directories : /root/anaconda3/envs
                          /root/.conda/envs
               platform : linux-64
             user-agent : conda/4.9.1 requests/2.24.0 CPython/3.8.3 Linux/4.4.0-116-generic ubuntu/18.04.5 glibc/2.27
                UID:GID : 0:0
             netrc file : None
           offline mode : False


An unexpected error has occurred. Conda has prepared the above report.
```

What is wrong with my origin ~/.zshrc  ?

**Comment by sisrfeng** [comment]
Maybe it is because of some strange character in my ~/.zshrc
![image](https://user-images.githubusercontent.com/53520949/97795170-e8d83b80-1c3d-11eb-900b-85920e879285.png)

**Comment by paulacmylove** [comment]
Removing .anaconda and .conda folders worked for me. Thanks!

**Comment by mrabhishek007** [comment]
Removing .anaconda and .conda folders worked for me
