### ISSUE TITLE
suds-jurko package should not be marked as noarch_python

### ISSUE THREAD

**Issue by jjhelmus** [ContinuumIO/anaconda-issues#730]
The **suds-jurko** package in the default channel is built with `noarch_python: True` but the package is not Python version independent and will not work in the Python 3 environment as built.  The issue is that the Python version is used at build time to determine if [2to3 should be run on the source code](https://bitbucket.org/jurko/suds/src/0fcfff1ea149397bfa23c7537a0ae2ac300e9564/setup.py?at=release-0.6&fileviewer=file-view-default#setup.py-94) in order to make the package Python 3 compatible.

```
~$ conda create -n example_py35 python=3.5 suds-jurko
Using Anaconda Cloud api site https://api.anaconda.org
Fetching package metadata: ..
Solving package specifications: .........

Package plan for installation in environment /home/jhelmus/anaconda/envs/example_py35:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    suds-jurko-0.6             |             py_0         222 KB

The following NEW packages will be INSTALLED:

    openssl:    1.0.2g-0     
    pip:        8.1.1-py35_1 
    python:     3.5.1-0      
    readline:   6.2-2        
    setuptools: 20.3-py35_0  
    sqlite:     3.9.2-0      
    suds-jurko: 0.6-py_0     
    tk:         8.5.18-0     
    wheel:      0.29.0-py35_0
    xz:         5.0.5-1      
    zlib:       1.2.8-0      

Proceed ([y]/n)? y

Fetching packages ...
suds-jurko-0.6 100% |################################| Time: 0:00:00  30.65 MB/s
Extracting packages ...
[      COMPLETE      ]|###################################################| 100%
Linking packages ...
[      COMPLETE      ]|###################################################| 100%
#
# To activate this environment, use:
# $ source activate example_py35
#
# To deactivate this environment, use:
# $ source deactivate
#
~$ source activate example_py35
discarding /home/jhelmus/anaconda/bin from PATH
prepending /home/jhelmus/anaconda/envs/example_py35/bin to PATH
~$ python -c "import suds"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/jhelmus/anaconda/envs/example_py35/lib/python3.5/site-packages/suds/__init__.py", line 28, in <module>
    from version import __build__, __version__
ImportError: No module named 'version'
```

The current packages does work in Python 2 environment:

```
~$ conda create -n example_py27 python=2.7 suds-jurko
Using Anaconda Cloud api site https://api.anaconda.org
Fetching package metadata: ..
Solving package specifications: .........

Package plan for installation in environment /home/jhelmus/anaconda/envs/example_py27:

The following NEW packages will be INSTALLED:

    openssl:    1.0.2g-0     
    pip:        8.1.1-py27_1 
    python:     2.7.11-0     
    readline:   6.2-2        
    setuptools: 20.3-py27_0  
    sqlite:     3.9.2-0      
    suds-jurko: 0.6-py_0     
    tk:         8.5.18-0     
    wheel:      0.29.0-py27_0
    zlib:       1.2.8-0      

Proceed ([y]/n)? y

Linking packages ...
[      COMPLETE      ]|###################################################| 100%
#
# To activate this environment, use:
# $ source activate example_py27
#
# To deactivate this environment, use:
# $ source deactivate
#
~$ source activate example_py27
discarding /home/jhelmus/anaconda/bin from PATH
prepending /home/jhelmus/anaconda/envs/example_py27/bin to PATH
~$ python -c "import suds"
~$
```

**Comment by msarahan** [comment]
Thanks, I missed that detail.  I'll get a new package out ASAP.

**Comment by jjhelmus** [comment]
The new packages are working great!  Thanks for the quick fix.
