### ISSUE TITLE
Anaconda-navigator cannot launch with "no module named '_license'"

### ISSUE THREAD

**Issue by kczh** [ContinuumIO/anaconda-issues#7300]
(D:\Anaconda3) C:\Users\Kaicheng Zhang>anaconda-navigator
Traceback (most recent call last):
  File "D:\Anaconda3\Scripts\anaconda-navigator-script.py", line 5, in <module>
    sys.exit(anaconda_navigator.app.main.main())
  File "D:\Anaconda3\lib\site-packages\anaconda_navigator\app\main.py", line 63, in main
    from anaconda_navigator.app.start import start_app
  File "D:\Anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 30, in <module>
    from anaconda_navigator.widgets.main_window import MainWindow
  File "D:\Anaconda3\lib\site-packages\anaconda_navigator\widgets\main_window.py", line 32, in <module>
    from anaconda_navigator.api.anaconda_api import AnacondaAPI
  File "D:\Anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 24, in <module>
    import _license
ImportError: No module named '_license'

**Comment by kczh** [comment]
I cant open my anaconda navigator. Then I tried to open it in anaconda prompt and it returns 'no module named _license'.

Thank you in advance.

**Comment by kczh** [comment]
I've installed my anaconda just now so that it must be the newest version.
anaconda                  4.4.0               np112py36_0    defaults
anaconda-client           1.6.3                    py35_0    defaults
anaconda-navigator        1.6.2                    py36_0    defaults

**Comment by goanpeca** [comment]
@kczh no, that is not the latest Anaconda. Latest version is 5.0.1

**Comment by kczh** [comment]
Thank you soooo much!!
just need to update the software
I used the following command and succeeded
conda update --all

**Comment by kczh** [comment]
@goanpeca
