### ISSUE TITLE
after updating conda, anaconda-navigator and navigator updater getting this error

### ISSUE THREAD

**Issue by Srivatsa-M-Hegde** [ContinuumIO/anaconda-issues#7343]
Traceback (most recent call last):
File "D:\softwares\anaconda\lib\site-packages\psutil\_pswindows.py", line 620, in wrapper
return fun(self, *args, **kwargs)
File "D:\softwares\anaconda\lib\site-packages\psutil\_pswindows.py", line 690, in cmdline
ret = cext.proc_cmdline(self.pid)
PermissionError: [WinError 5] Access is denied

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "D:\softwares\anaconda\lib\site-packages\anaconda_navigator\exceptions.py", line 75, in exception_handler
return_value = func(*args, **kwargs)
File "D:\softwares\anaconda\lib\site-packages\anaconda_navigator\app\start.py", line 113, in start_app
if misc.load_pid() is None: # A stale lock might be around
File "D:\softwares\anaconda\lib\site-packages\anaconda_navigator\utils\misc.py", line 384, in load_pid
cmds = process.cmdline()
File "D:\softwares\anaconda\lib\site-packages\psutil\__init__.py", line 701, in cmdline
return self._proc.cmdline()
File "D:\softwares\anaconda\lib\site-packages\psutil\_pswindows.py", line 623, in wrapper
raise AccessDenied(self.pid, self._name)
psutil.AccessDenied: psutil.AccessDenied (pid=1476)

**Comment by Srivatsa-M-Hegde** [comment]
I did try updating the navigator and the navigator-updater, but to no avail. Is there any other error you see which is causing this ?

Traceback (most recent call last):
File "D:\softwares\anaconda\lib\site-packages\psutil\_pswindows.py", line 620, in wrapper
return fun(self, *args, **kwargs)
File "D:\softwares\anaconda\lib\site-packages\psutil\_pswindows.py", line 690, in cmdline
ret = cext.proc_cmdline(self.pid)
PermissionError: [WinError 5] Access is denied

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "D:\softwares\anaconda\lib\site-packages\anaconda_navigator\exceptions.py", line 75, in exception_handler
return_value = func(*args, **kwargs)
File "D:\softwares\anaconda\lib\site-packages\anaconda_navigator\app\start.py", line 113, in start_app
if misc.load_pid() is None: # A stale lock might be around
File "D:\softwares\anaconda\lib\site-packages\anaconda_navigator\utils\misc.py", line 384, in load_pid
cmds = process.cmdline()
File "D:\softwares\anaconda\lib\site-packages\psutil\__init__.py", line 701, in cmdline
return self._proc.cmdline()
File "D:\softwares\anaconda\lib\site-packages\psutil\_pswindows.py", line 623, in wrapper
raise AccessDenied(self.pid, self._name)
psutil.AccessDenied: psutil.AccessDenied (pid=1476)

**Comment by goanpeca** [comment]
@Srivatsa-M-Hegde did you read `See issue #1984 for more information on how to fix this.` ?

**Comment by Srivatsa-M-Hegde** [comment]
Im sorry...will do that thanks !

**Comment by Srivatsa-M-Hegde** [comment]
Thanks a lot. The solution worked !
