### ISSUE TITLE
libxml2 missing?

### ISSUE THREAD

**Issue by jlmeunier** [ContinuumIO/anaconda-issues#7366]
Hello,
I've installed anaconda from Anaconda2-5.0.1-Linux-x86_64.sh and libxml2 is not properly installed:

```
> which python
/nfs/project/read/anaconda2.501/bin/python
```

```
> python -c 'import libxml2'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named libxml2
```

What is strange is the conda believes libxml2 is installed:
```
> conda upgrade libxml2
Fetching package metadata ...........
Solving package specifications: .
# All requested packages already installed.
# packages in environment at /nfs/project/read/anaconda2.501:
#
libxml2                   2.9.4                h6b072ca_5
```

Forcing the re-install doesn't help:
```
 > conda upgrade libxml2 -f
Fetching package metadata ...........
Solving package specifications: .
Package plan for installation in environment /nfs/project/read/anaconda2.501:
The following NEW packages will be INSTALLED:
    libxml2: 2.9.4-h6b072ca_5
Proceed ([y]/n)? y
```

```
 > python -c 'import libxml2'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named libxml2
```

Any help appreciated. Thanks!

JL

ps: The same problem occurs with previous version 5.0.0

**Comment by mingwandroid** [comment]
libxml2 is a C library. The python module is called lxml.

**Comment by jlmeunier** [comment]
ok thanks. I missed that episode of the life of libxml2.
