### ISSUE TITLE
Error: spawn ENOENT

### ISSUE THREAD

**Issue by rgawlik** [ContinuumIO/anaconda-issues#737]
Can't start Anaconda on OS X 10.11.3.  Box pops up with

Error: spawn ENOENT
    at exports._errnoException (util.js:742:11)
    at Process.ChildProcess._handle.onexit (child_process.js:1027:32)
    at child_process.js:1110:20
    at process._tickCallback (node.js:279:11)

**Comment by simonsjw** [comment]
Hi, I'm running Ubuntu 16.04 and get the same error message:

Error: spawn ENOENT
    at exports._errnoException (util.js:742:11)
    at Process.ChildProcess._handle.onexit (child_process.js:1027:32)
    at child_process.js:1110:20
    at process._tickCallback (node.js:279:11)

**Comment by hollisn** [comment]
Just got the same error on OSX 10.11.6

Error: spawn ENOENT
    at exports._errnoException (util.js:742:11)
    at Process.ChildProcess._handle.onexit (child_process.js:1027:32)
    at child_process.js:1110:20
    at process._tickCallback (node.js:279:11)
