### ISSUE TITLE
numpydoc-0.4-py2.7.egg-info permission denied

### ISSUE THREAD

**Issue by Nodd** [ContinuumIO/anaconda-issues#740]
After updating anaconda, I get the following error:
`IOError: [Errno 13] Permission denied: '/data1/anaconda/lib/python2.7/site-packages/numpydoc-0.4-py2.7.egg-info'`
Just changing the permissions fixes the problem: `chmod a+r /data1/anaconda/lib/python2.7/site-packages/numpydoc-0.4-py2.7.egg-info`

I encountered this on at least 3 different machines. Anaconda is installed as root so that all users can have access to it. This problem doesn't appear when installing anaconda as a user.

**Comment by Nodd** [comment]
Here is the full traceback when launching spyder:
```python
[Errno 13] Permission denied: '/data1/anaconda/lib/python2.7/site-packages/numpydoc-0.4-py2.7.egg-info'
Traceback (most recent call last):
  File "/usr/local/anaconda/bin/spyder", line 2, in <module>
    from spyderlib import start_app
  File "/data1/anaconda/lib/python2.7/site-packages/spyderlib/start_app.py", line 14, in <module>
    from spyderlib.config import CONF
  File "/data1/anaconda/lib/python2.7/site-packages/spyderlib/config.py", line 22, in <module>
    from spyderlib.utils import iofuncs, codeanalysis
  File "/data1/anaconda/lib/python2.7/site-packages/spyderlib/utils/iofuncs.py", line 26, in <module>
    import pandas as pd
  File "/data1/anaconda/lib/python2.7/site-packages/pandas/__init__.py", line 7, in <module>
    from . import hashtable, tslib, lib
  File "pandas/tslib.pyx", line 46, in init pandas.tslib (pandas/tslib.c:79899)
  File "/data1/anaconda/lib/python2.7/site-packages/pytz/__init__.py", line 29, in <module>
    from pkg_resources import resource_stream
  File "/data1/anaconda/lib/python2.7/site-packages/setuptools-20.3-py2.7.egg/pkg_resources/__init__.py", line 2900, in <module>
    
  File "/data1/anaconda/lib/python2.7/site-packages/setuptools-20.3-py2.7.egg/pkg_resources/__init__.py", line 2886, in _call_aside
    
  File "/data1/anaconda/lib/python2.7/site-packages/setuptools-20.3-py2.7.egg/pkg_resources/__init__.py", line 2913, in _initialize_master_working_set
    
  File "/data1/anaconda/lib/python2.7/site-packages/setuptools-20.3-py2.7.egg/pkg_resources/__init__.py", line 633, in _build_master
    
  File "/data1/anaconda/lib/python2.7/site-packages/setuptools-20.3-py2.7.egg/pkg_resources/__init__.py", line 626, in __init__
    
  File "/data1/anaconda/lib/python2.7/site-packages/setuptools-20.3-py2.7.egg/pkg_resources/__init__.py", line 682, in add_entry
    
  File "/data1/anaconda/lib/python2.7/site-packages/setuptools-20.3-py2.7.egg/pkg_resources/__init__.py", line 1956, in find_on_path
    
  File "/data1/anaconda/lib/python2.7/site-packages/setuptools-20.3-py2.7.egg/pkg_resources/__init__.py", line 2343, in from_location
    
  File "/data1/anaconda/lib/python2.7/site-packages/setuptools-20.3-py2.7.egg/pkg_resources/__init__.py", line 2660, in _reload_version
    
  File "/data1/anaconda/lib/python2.7/site-packages/setuptools-20.3-py2.7.egg/pkg_resources/__init__.py", line 2308, in _version_from_file
    
  File "/data1/anaconda/lib/python2.7/site-packages/setuptools-20.3-py2.7.egg/pkg_resources/__init__.py", line 2476, in _get_metadata
    
  File "/data1/anaconda/lib/python2.7/site-packages/setuptools-20.3-py2.7.egg/pkg_resources/__init__.py", line 1847, in get_metadata_lines
    
  File "/data1/anaconda/lib/python2.7/site-packages/setuptools-20.3-py2.7.egg/pkg_resources/__init__.py", line 1841, in get_metadata
    
IOError: [Errno 13] Permission denied: '/data1/anaconda/lib/python2.7/site-packages/numpydoc-0.4-py2.7.egg-info'
```
