### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by huwwatersgwaith** [ContinuumIO/anaconda-issues#7437]
## Main error
Application <b>notebook</b> launch may have produced errors.
## Traceback
```
[E 11:21:33.785 NotebookApp] Exception while loading config file C:\Users\hwaters\.jupyter\jupyter_notebook_config.py
    Traceback (most recent call last):
      File "C:\ProgramData\Anaconda3\lib\site-packages\traitlets\config\application.py", line 562, in _load_config_files
        config = loader.load_config()
      File "C:\ProgramData\Anaconda3\lib\site-packages\traitlets\config\loader.py", line 457, in load_config
        self._read_file_as_dict()
      File "C:\ProgramData\Anaconda3\lib\site-packages\traitlets\config\loader.py", line 489, in _read_file_as_dict
        py3compat.execfile(conf_filename, namespace)
      File "C:\ProgramData\Anaconda3\lib\site-packages\ipython_genutils\py3compat.py", line 198, in execfile
        exec(compiler(f.read(), fname, 'exec'), glob, loc)
      File "C:\Users\hwaters\.jupyter\jupyter_notebook_config.py", line 139
        c.NotebookApp.extra_static_paths = ['C:\Users\hwaters\.jupyter\vis-4.19.1\dist']
                                           ^
    SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape
[I 11:21:35.056 NotebookApp] The port 8888 is already in use, trying another port.
[I 11:21:35.191 NotebookApp] Serving notebooks from local directory: C:\Users\hwaters
[I 11:21:35.191 NotebookApp] 0 active kernels 
[I 11:21:35.191 NotebookApp] The Jupyter Notebook is running at: http://localhost:8889/?token=147ff75d2b0c9b601c0c93516b35e5e739b7edd14b6065a6
[I 11:21:35.191 NotebookApp] Use Control-C to st

**Comment by goanpeca** [comment]
@huwwatersgwaith please fix the character error inside `C:\Users\hwaters\.jupyter\jupyter_notebook_config.py`, or just delete the file completely and try again
