### ISSUE TITLE
CondaHTTPError: HTTP 000 CONNECTION FAILED

### ISSUE THREAD

**Issue by whaasphd** [ContinuumIO/anaconda-issues#7439]
Any time I try to install a new package via CONDA INSTALL NAME, I get the following message:

CondaError: CondaHTTPError: HTTP 000 CONNECTION FAILED for url <https://conda.anaconda.org/conda-forge/linux-64/libuuid-1.0.3-1.tar.bz2>
Elapsed: -

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.

CONDA UPDATE CONDA and 
CONDA UPDATE ANCONDA worked

**Comment by Redzerman** [comment]
I have the same error! 
I'm running the latest version of Anaconda (newly installed today), on a Linux guest OS.
Unfortunately CONDA UPDATE CONDA and CONDA UPDATE ANACONDA didn't work for me.

**Comment by whaasphd** [comment]
I also tried the following, without success:

**Comment by whaasphd** [comment]
conda config --set ssl_verify no

conda list --explicit shows only IP addresses that start with
https://repo.continuum.io/pkgs/main/linux-64
https://conda.anaconda.org/bioconda/linux-64
https://conda.anaconda.org/conda-forge/linux-64
etc., no outdated IP addresses

**Comment by whaasphd** [comment]
Finally, conda install saffrontree -v returns:

Current conda install:

               platform : linux-64
          conda version : 4.3.29
       conda is private : False
      conda-env version : 4.3.29
    conda-build version : 3.0.23
         python version : 3.6.2.final.0
       requests version : 2.18.4
       root environment : /local/proj.wzh02/apps/anaconda3  (writable)
    default environment : /local/proj.wzh02/apps/anaconda3
       envs directories : /local/proj.wzh02/apps/anaconda3/envs
                          /home/wzh02/.conda/envs
          package cache : /local/proj.wzh02/apps/anaconda3/pkgs
                          /home/wzh02/.conda/pkgs
           channel URLs : https://conda.anaconda.org/bioconda/linux-64
                          https://conda.anaconda.org/bioconda/noarch
                          https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.continuum.io/pkgs/main/linux-64
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/linux-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://conda.anaconda.org/r/linux-64
                          https://conda.anaconda.org/r/noarch
            config file : /home/wzh02/.condarc
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.29 requests/2.18.4 CPython/3.6.2 Linux/3.5.0-42-generic debian/wheezy/sid glibc/2.15    
                UID:GID : 5624:101

`$ conda install saffrontree -v`




    Traceback (most recent call last):
      File "/local/proj.wzh02/apps/anaconda3/lib/python3.6/site-packages/conda/exceptions.py", line 640, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/local/proj.wzh02/apps/anaconda3/lib/python3.6/site-packages/conda/cli/main.py", line 140, in _main
        exit_code = args.func(args, p)
      File "/local/proj.wzh02/apps/anaconda3/lib/python3.6/site-packages/conda/cli/main_install.py", line 80, in execute
        install(args, parser, 'install')
      File "/local/proj.wzh02/apps/anaconda3/lib/python3.6/site-packages/conda/cli/install.py", line 326, in install
        execute_actions(actions, index, verbose=not context.quiet)
      File "/local/proj.wzh02/apps/anaconda3/lib/python3.6/site-packages/conda/plan.py", line 830, in execute_actions
        execute_instructions(plan, index, verbose)
      File "/local/proj.wzh02/apps/anaconda3/lib/python3.6/site-packages/conda/instructions.py", line 247, in execute_instructions
        cmd(state, arg)
      File "/local/proj.wzh02/apps/anaconda3/lib/python3.6/site-packages/conda/instructions.py", line 100, in PROGRESSIVEFETCHEXTRACT_CMD
        progressive_fetch_extract.execute()
      File "/local/proj.wzh02/apps/anaconda3/lib/python3.6/site-packages/conda/core/package_cache.py", line 492, in execute
        self._execute_action(action)
      File "/local/proj.wzh02/apps/anaconda3/lib/python3.6/site-packages/conda/core/package_cache.py", line 513, in _execute_action
        raise CondaMultiError(exceptions)
    conda.CondaMultiError: CondaHTTPError: HTTP 000 CONNECTION FAILED for url <https://conda.anaconda.org/bioconda/linux-64/kmc-2.3.0-noasmlib_3.tar.bz2>
    Elapsed: -
    
    An HTTP error occurred when trying to retrieve this URL.
    HTTP errors are often intermittent, and a simple retry will get you on your way.
    
    CondaHTTPError: HTTP 000 CONNECTION FAILED for url <https://conda.anaconda.org/bioconda/linux-64/kmc-2.3.0-noasmlib_3.tar.bz2>
    Elapsed: -
    
    An HTTP error occurred when trying to retrieve this URL.
    HTTP errors are often intermittent, and a simple retry will get you on your way.
    
    CondaHTTPError: HTTP 000 CONNECTION FAILED for url <https://conda.anaconda.org/bioconda/linux-64/kmc-2.3.0-noasmlib_3.tar.bz2>
    Elapsed: -
    
    An HTTP error occurred when trying to retrieve this URL.
    HTTP errors are often intermittent, and a simple retry will get you on your way.
    
 Any help would be greatly appreciated.
