### ISSUE TITLE
cannot import argparse module

### ISSUE THREAD

**Issue by antran89** [ContinuumIO/anaconda-issues#745]
Hi anaconda developers,
I am a new user of Anaconda. I installed Anaconda, but unable to use argparse module. The error is as following:
```
[a0081742@nscc04 python_scripts]$ python script_extract_calibrated_flow.py 
2.7.11 |Anaconda 4.0.0 (64-bit)| (default, Dec  6 2015, 18:08:32) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)]
Traceback (most recent call last):
  File "script_extract_calibrated_flow.py", line 9, in <module>
    import argparse
  File "/home/nus/a0081742/anaconda2/lib/python2.7/argparse.py", line 85, in <module>
    import collections as _collections
  File "/home/nus/a0081742/anaconda2/lib/python2.7/collections.py", line 8, in <module>
    from _collections import deque, defaultdict
ImportError: No module named _collections
```
I tried to reinstall Anaconda in #156, but it still has the same problem. 
Furthermore, I cannot use any `conda` commands:
```
[a0081742@nscc04 python_scripts]$ conda install -f conda
Traceback (most recent call last):
  File "/home/nus/a0081742/anaconda2/bin/conda", line 6, in <module>
    sys.exit(main())
  File "/home/nus/a0081742/anaconda2/lib/python2.7/site-packages/conda/cli/main.py", line 64, in main
    import logging
  File "/home/nus/a0081742/anaconda2/lib/python2.7/logging/__init__.py", line 26, in <module>
    import sys, os, time, cStringIO, traceback, warnings, weakref, collections
ImportError: No module named time
```

Hope to have your feedback.

**Comment by ilanschnell** [comment]
I suspect you have the `PYTHONPATH` environment variable set.  What is the output from ?:
```
$ echo PYTHONPATH
```
If this is set, please try:
```
$ unset PYTHONPATH
```

**Comment by antran89** [comment]
My PYTHONPATH is
```
/home/nus/a0081742/local/lib/python2.7/dist-packages:
```
which I might need to have other libs installed in my home folder.
I have unset PYTHONPATH as you said, but the same error still happens. For your information, I have another Python environment in our cluster. I do not know whether this information is helpful to you or not.

**Comment by ilanschnell** [comment]
You still have other things on `sys.path` it seems.

**Comment by antran89** [comment]
@ilanschnell What do you mean sys.path? If sys.path in my python code, I have not set anything.

**Comment by ilanschnell** [comment]
`sys.path` is a Python list, which contains the paths in which Python looks for modules when you import them.  Start a Python interpreter and type the following:
```
>>> import sys
>>> sys.path
```

**Comment by antran89** [comment]
FYI, my anacon is used in cluster environments.

```
[a0081742@nscc04 ~]$ python
Python 2.7.11 |Anaconda 4.0.0 (64-bit)| (default, Dec  6 2015, 18:08:32) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://anaconda.org
>>> import sys
>>> sys.path
['', '/home/nus/a0081742/local/lib/python2.7/dist-packages', '/home/nus/a0081742', '/home/nus/a0081742/anaconda2/lib/python27.zip', '/home/nus/a0081742/anaconda2/lib/python2.7', '/home/nus/a0081742/anaconda2/lib/python2.7/plat-linux2', '/home/nus/a0081742/anaconda2/lib/python2.7/lib-tk', '/home/nus/a0081742/anaconda2/lib/python2.7/lib-old', '/home/nus/a0081742/anaconda2/lib/python2.7/lib-dynload', '/home/nus/a0081742/.local/lib/python2.7/site-packages', '/home/nus/a0081742/anaconda2/lib/python2.7/site-packages', '/home/nus/a0081742/anaconda2/lib/python2.7/site-packages/Sphinx-1.3.5-py2.7.egg', '/home/nus/a0081742/anaconda2/lib/python2.7/site-packages/setuptools-20.3-py2.7.egg']
```

**Comment by antran89** [comment]
Hi @ilanschnell 
My `PYTHONPATH` and `sys.path` is as following:
```
[a0081742@nscc03 ~]$ echo $PYTHONPATH

[a0081742@nscc03 ~]$ python 
Python 2.7.11 |Anaconda 4.0.0 (64-bit)| (default, Dec  6 2015, 18:08:32) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://anaconda.org
>>> import sys
>>> sys.path
['', '/home/nus/a0081742/anaconda2/lib/python27.zip', '/home/nus/a0081742/anaconda2/lib/python2.7', '/home/nus/a0081742/anaconda2/lib/python2.7/plat-linux2', '/home/nus/a0081742/anaconda2/lib/python2.7/lib-tk', '/home/nus/a0081742/anaconda2/lib/python2.7/lib-old', '/home/nus/a0081742/lib/python2.7/lib-dynload', '/home/nus/a0081742/.local/lib/python2.7/site-packages', '/home/nus/a0081742/anaconda2/lib/python2.7/site-packages', '/home/nus/a0081742/anaconda2/lib/python2.7/site-packages/Sphinx-1.3.5-py2.7.egg', '/home/nus/a0081742/anaconda2/lib/python2.7/site-packages/setuptools-20.3-py2.7.egg']
>>> 

```
