### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by hyogase** [ContinuumIO/anaconda-issues#7451]
## Main error
An unexpected error occurred on Navigator start-up<br>'ascii' codec can't encode characters in position 12-13: ordinal not in range(128)
## Traceback
```
Traceback (most recent call last):
  File "/home/lvkai/anaconda2/lib/python2.7/site-packages/anaconda_navigator/exceptions.py", line 75, in exception_handler
    return_value = func(*args, **kwargs)
  File "/home/lvkai/anaconda2/lib/python2.7/site-packages/anaconda_navigator/app/start.py", line 115, in start_app
    window = run_app(splash)
  File "/home/lvkai/anaconda2/lib/python2.7/site-packages/anaconda_navigator/app/start.py", line 58, in run_app
    window = MainWindow(splash=splash)
  File "/home/lvkai/anaconda2/lib/python2.7/site-packages/anaconda_navigator/widgets/main_window.py", line 322, in __init__
    self.tab_projects = ProjectsTab(parent=self)
  File "/home/lvkai/anaconda2/lib/python2.7/site-packages/anaconda_navigator/widgets/tabs/projects.py", line 77, in __init__
    self.widget = ProjectsWidget()
  File "/home/lvkai/anaconda2/lib/python2.7/site-packages/anaconda_navigator/widgets/projects.py", line 212, in __init__
    self.file_explorer = ExplorerWidget()
  File "/home/lvkai/anaconda2/lib/python2.7/site-packages/anaconda_navigator/widgets/explorer.py", line 1252, in __init__
    self.update_breadcrumb()
  File "/home/lvkai/anaconda2/lib/python2.7/site-packages/anaconda_navigator/widgets/explorer.py", line 1267, in update_breadcrumb
    text += '<a href="{link}">{p}</a>'.format(p=p, link=cum_path)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 12-13: ordinal not in range(128)

```
## System information
```
platform: linux-64
version: 1.6.2
conda: 4.3.30
qt: 5.6.2
language: zh_CN
python: 2.7.14
os: Linux;3.10.0-327.el7.x86_64;#1 SMP Thu Nov 19 22:10:57 UTC 2015;x86_64;x86_64
pyqt: 5.6.0
```

**Comment by goanpeca** [comment]
@hyogase please ensure that the project path only contains ascii characters. This is being fixe don a future release.
