### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by Hinfa** [ContinuumIO/anaconda-issues#7468]
## Main error
Application <b>notebook</b> launch may have produced errors.
## Traceback
```
Traceback (most recent call last):
  File "d:\ProgramData\Anaconda3\Scripts\jupyter-notebook-script.py", line 3, in <module>
    import notebook.notebookapp
  File "d:\ProgramData\Anaconda3\lib\site-packages\notebook\__init__.py", line 25, in <module>
    from .nbextensions import install_nbextension
  File "d:\ProgramData\Anaconda3\lib\site-packages\notebook\nbextensions.py", line 572, in <module>
    from .extensions import (
  File "d:\ProgramData\Anaconda3\lib\site-packages\notebook\extensions.py", line 8, in <module>
    from tornado.log import LogFormatter
ModuleNotFoundError: No module named 'tornado.log'

```
## System information
```
python: 3.6.1
language: zh_CN
os: Windows;7;6.1.7601;AMD64;Intel64 Family 6 Model 58 Stepping 9, GenuineIntel
version: 1.6.2
platform: win-64
qt: 5.6.2
pyqt: 5.6.0
conda: 4.3.21
```

**Comment by goanpeca** [comment]
Open a terminal (on Linux or Mac) or the Anaconda Command Prompt (on windows)
and reinstall tornado typing:

```
conda install tornado --force
```

And please report, if this solves the issue
