### ISSUE TITLE
Applied solution to #1984 to get this

### ISSUE THREAD

**Issue by sbathreya** [ContinuumIO/anaconda-issues#7502]
Traceback (most recent call last):
File "/Applications/anaconda/lib/python3.6/site-packages/psutil/_psosx.py", line 293, in wrapper
return fun(self, *args, **kwargs)
File "/Applications/anaconda/lib/python3.6/site-packages/psutil/_psosx.py", line 356, in cmdline
return cext.proc_cmdline(self.pid)
PermissionError: [Errno 13] Permission denied

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/Applications/anaconda/lib/python3.6/site-packages/anaconda_navigator/exceptions.py", line 75, in exception_handler
return_value = func(*args, **kwargs)
File "/Applications/anaconda/lib/python3.6/site-packages/anaconda_navigator/app/start.py", line 113, in start_app
if misc.load_pid() is None: # A stale lock might be around
File "/Applications/anaconda/lib/python3.6/site-packages/anaconda_navigator/utils/misc.py", line 384, in load_pid
cmds = process.cmdline()
File "/Applications/anaconda/lib/python3.6/site-packages/psutil/__init__.py", line 701, in cmdline
return self._proc.cmdline()
File "/Applications/anaconda/lib/python3.6/site-packages/psutil/_psosx.py", line 306, in wrapper
raise AccessDenied(self.pid, self._name)
psutil.AccessDenied: psutil.AccessDenied (pid=576)

**Comment by goanpeca** [comment]
Please run 

```
anaconda-navigator --reset
```
