### ISSUE TITLE
Installing graphviz breaks spyder in virgin Anaconda 4.0 install

### ISSUE THREAD

**Issue by ijstokes** [ContinuumIO/anaconda-issues#752]
After installing Anaconda 4.0 (Python 3.5, Windows 8 64-bit, on VM Fusion VM) I was able to reproduce a problem reported on the Anaconda ML, namely that Spyder works initially, but once graphviz is installed Spyder is then broken.

I would guess that this is due to some dependency of Spyder being upgraded or downgraded as part of the graphviz install in a way that breaks Spyder.  I would assume that fixing the dependency specifications will prevent that from happening in the future.  But this is all speculation.

**Comment by ijstokes** [comment]
Here is a terminal trace:

```
[Anaconda3] C:\Users\builder>spyder
Traceback (most recent call last):
  File "C:\Anaconda3\lib\site-packages\spyderlib\qt\__init__.py", line 48, in <m
odule>
    from PySide import __version__  # analysis:ignore
ImportError: No module named 'PySide'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Anaconda3\lib\site-packages\spyderlib\requirements.py", line 40, in c
heck_qt
    from spyderlib import qt
  File "C:\Anaconda3\lib\site-packages\spyderlib\qt\__init__.py", line 50, in <m
odule>
    raise ImportError("Spyder requires PySide or PyQt to be installed")
ImportError: Spyder requires PySide or PyQt to be installed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Anaconda3\Scripts\spyder-script.py", line 2, in <module>
    start_app.main()
  File "C:\Anaconda3\lib\site-packages\spyderlib\start_app.py", line 114, in mai
n
    from spyderlib import spyder
  File "C:\Anaconda3\lib\site-packages\spyderlib\spyder.py", line 48, in <module
>
    requirements.check_qt()
  File "C:\Anaconda3\lib\site-packages\spyderlib\requirements.py", line 50, in c
heck_qt
    % (qt_infos['pyqt']+qt_infos['pyside']))
  File "C:\Anaconda3\lib\site-packages\spyderlib\requirements.py", line 25, in s
how_warning
    raise RuntimeError(message)
RuntimeError: Please check Spyder installation requirements:
PyQt4 4.6+ (or PySide 1.2.0+) is required.

[Anaconda3] C:\Users\builder>conda remove graphviz
```

**Comment by ijstokes** [comment]
If someone tells me where to look for the conda install history on Windows I can provide a list of the other things that were affected by the `graphviz` install.

**Comment by ccordoba12** [comment]
I think the problem was the recent addition of libpng as a Graphviz dependency, which in turn breaks Qt.

@msarahan, thoughts?

**Comment by groutr** [comment]
The win-64 package for graphviz has no dependencies.

**Comment by yipukangda** [comment]
yes, I meet the same thing, spyder can not be launched after installation of graphviz.
the os is win10 64 bit

**Comment by ccordoba12** [comment]
The problem seems to be that our Graphviz Windows packages come with its own copy of Qt, and that's what's making Spyder crash :-)

I'm working to fix this right now.

**Comment by thirumarane** [comment]
Graphviz installation also breaks Matplotlib as well. Looks like the Graphviz installs pyqt 5.x version and matplotlib depends on pyqt 4.x
