### ISSUE TITLE
psutil.AccessDenied (pid=772)

### ISSUE THREAD

**Issue by guto8797** [ContinuumIO/anaconda-issues#7537]
Traceback

Traceback (most recent call last):
  File "C:\Anaconda3\lib\site-packages\psutil\_pswindows.py", line 636, in wrapper
    return fun(self, *args, **kwargs)
  File "C:\Anaconda3\lib\site-packages\psutil\_pswindows.py", line 706, in cmdline
    ret = cext.proc_cmdline(self.pid)
PermissionError: [WinError 5] Acesso negado

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Anaconda3\lib\site-packages\anaconda_navigator\exceptions.py", line 75, in exception_handler
    return_value = func(*args, **kwargs)
  File "C:\Anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 113, in start_app
    if misc.load_pid() is None:  # A stale lock might be around
  File "C:\Anaconda3\lib\site-packages\anaconda_navigator\utils\misc.py", line 384, in load_pid
    cmds = process.cmdline()
  File "C:\Anaconda3\lib\site-packages\psutil\__init__.py", line 721, in cmdline
    return self._proc.cmdline()
  File "C:\Anaconda3\lib\site-packages\psutil\_pswindows.py", line 639, in wrapper
    raise AccessDenied(self.pid, self._name)
psutil.AccessDenied: psutil.AccessDenied (pid=772)

----

Anaconda Navigator previously worked just fine. Tried to launch it today, and I get this error. I used the anaconda prompt to update the navigator, but it always states it has the latest version. Even executing as administrator has no effect. Also tried re-installing, but nothing happens. I searched and found people with similar issues, but the answer to their problem of updating the navigator has not worked for me. 

Any help?

**Comment by csoja** [comment]
From the anaconda prompt, have you tried:
  _anaconda-navigator --reset_  ?

**Comment by guto8797** [comment]
Ok, thanks, that solved it and I feel like an idiot since this is probably the equivalent of turning it on and off again.

**Comment by csoja** [comment]
Not sure what you mean by lock this?  I'm glad that fixed your problem.

**Comment by guto8797** [comment]
I think issues can be closed, that was more my intention. Thanks for the help again.
