### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by CharlesXiaoyuanLi** [ContinuumIO/anaconda-issues#7559]
## Main error
Application <b>spyder</b> launch may have produced errors.
## Traceback
```
Traceback (most recent call last):
  File "/Users/charleslxy/anaconda2/envs/china-calliope/bin/spyder", line 7, in <module>
    from spyder.app.start import main
  File "/Users/charleslxy/anaconda2/envs/china-calliope/lib/python3.6/site-packages/spyder/app/start.py", line 13, in <module>
    import zmq
  File "/Users/charleslxy/anaconda2/envs/china-calliope/lib/python3.6/site-packages/zmq/__init__.py", line 34, in <module>
    from zmq import backend
  File "/Users/charleslxy/anaconda2/envs/china-calliope/lib/python3.6/site-packages/zmq/backend/__init__.py", line 21, in <module>
    if platform.python_implementation() == 'PyPy':
  File "/Users/charleslxy/anaconda2/envs/china-calliope/lib/python3.6/platform.py", line 1234, in python_implementation
    return _sys_version()[0]
  File "/Users/charleslxy/anaconda2/envs/china-calliope/lib/python3.6/platform.py", line 1192, in _sys_version
    repr(sys_version))
ValueError: failed to parse CPython sys.version: '3.6.3 |Anaconda, Inc.| (default, Oct  6 2017, 12:04:38) \n[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)]'

```
## System information
```
platform: osx-64
version: 1.6.2
conda: 4.3.30
qt: 5.6.2
language: en
python: 2.7.13
os: Darwin;16.7.0;Darwin Kernel Version 16.7.0: Wed Oct  4 00:17:00 PDT 2017; root:xnu-3789.71.6~1/RELEASE_X86_64;x86_64;i386
pyqt: 5.6.0
```

**Comment by goanpeca** [comment]
Please remember to update to the latest version of Navigator to include
the latest fixes.

Open a terminal (on Linux or Mac) or the Anaconda Command Prompt (on windows)
and type:

```
conda update conda
conda update anaconda-navigator
conda update navigator-updater
```
