### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by tbip** [ContinuumIO/anaconda-issues#7588]
## Main error
Application <b>orange3</b> launch may have produced errors.
## Traceback
```
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\numpy\core\__init__.py", line 16, in <module>
    from . import multiarray
ImportError: DLL load failed: The specified procedure could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\Scripts\orange-canvas-script.py", line 3, in <module>
    import Orange.canvas.__main__
  File "C:\ProgramData\Anaconda3\lib\site-packages\Orange\__init__.py", line 11, in <module>
    from .misc.lazy_module import _LazyModule
  File "C:\ProgramData\Anaconda3\lib\site-packages\Orange\misc\__init__.py", line 3, in <module>
    from .distmatrix import DistMatrix
  File "C:\ProgramData\Anaconda3\lib\site-packages\Orange\misc\distmatrix.py", line 1, in <module>
    import numpy as np
  File "C:\ProgramData\Anaconda3\lib\site-packages\numpy\__init__.py", line 142, in <module>
    from . import add_newdocs
  File "C:\ProgramData\Anaconda3\lib\site-packages\numpy\add_newdocs.py", line 13, in <module>
    from numpy.lib import add_newdoc
  File "C:\ProgramData\Anaconda3\lib\site-packages\numpy\lib\__init__.py", line 8, in <module>
    from .type_check import *
  File "C:\ProgramData\Anaconda3\lib\site-packages\numpy\lib\type_check.py", line 11, in <module>
    import numpy.core.numeric as _nx
  File "C:\ProgramData\Anaconda3\lib\site-packages\numpy\core\__init__.py", line 24, in <module>
    raise ImportError(msg)
Import

**Comment by tbip** [comment]
I am using anaconda navigator 1.6.2

**Comment by goanpeca** [comment]
@tbip it seems there is an issue with numpy. Also it seems you installed anaconda for all users. I would advise against it.

Also you are running an old version of navigator.

Please update navigator

Open a terminal (on Linux or Mac) or the Anaconda Command Prompt (on windows)
and type:

```
$ conda update conda
$ conda update anaconda-navigator
$ conda update navigator-updater
```

And then reinstall numpy

```
$ conda install numpy -f
```

**Comment by tbip** [comment]
Thank you for your time!  This seems to have resolved my issue at this time
.
