### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by ogalera-dev** [ContinuumIO/anaconda-issues#7605]
## Main error
Application <b>spyder</b> launch may have produced errors.
## Traceback
```
Traceback (most recent call last):
  File "/home/oscar/anaconda3/bin/spyder", line 6, in <module>
    sys.exit(spyder.app.start.main())
  File "/home/oscar/anaconda3/lib/python3.5/site-packages/spyder/app/start.py", line 103, in main
    from spyder.app import mainwindow
  File "/home/oscar/anaconda3/lib/python3.5/site-packages/spyder/app/mainwindow.py", line 165, in <module>
    from spyder.utils.environ import WinUserEnvDialog
  File "/home/oscar/anaconda3/lib/python3.5/site-packages/spyder/utils/environ.py", line 20, in <module>
    from spyder.widgets.variableexplorer.collectionseditor import CollectionsEditor
  File "/home/oscar/anaconda3/lib/python3.5/site-packages/spyder/widgets/variableexplorer/collectionseditor.py", line 46, in <module>
    from spyder.widgets.variableexplorer.importwizard import ImportWizard
  File "/home/oscar/anaconda3/lib/python3.5/site-packages/spyder/widgets/variableexplorer/importwizard.py", line 26, in <module>
    import pandas as pd
  File "/home/oscar/anaconda3/lib/python3.5/site-packages/pandas/__init__.py", line 51, in <module>
    plot_params = pandas.plotting._style._Options(deprecated=True)
AttributeError: module 'pandas' has no attribute 'plotting'

```
## System information
```
version: 1.6.2
conda: 4.3.30
os: Linux;4.4.0-101-generic;#124-Ubuntu SMP Fri Nov 10 18:29:59 UTC 2017;x86_64;x86_64
pyqt: 5.6.0
qt: 5.6.2
platform: linux-64
python: 3.5.3
language: en_US
```

**Comment by goanpeca** [comment]
Please reinstall pandas

```
conda install pandas -f
```
