### ISSUE TITLE
Juypter Notebook opening failed

### ISSUE THREAD

**Issue by RemedyLL** [ContinuumIO/anaconda-issues#7606]
## Main error
Application <b>notebook</b> launch may have produced errors.
## Traceback
```
[I 09:31:09.035 NotebookApp] [nb_conda_kernels] enabled, 2 kernels found
Traceback (most recent call last):
  File "d:\Program Files\Anaconda2\Scripts\jupyter-notebook-script.py", line 10, in <module>
    sys.exit(main())
  File "d:\Program Files\Anaconda2\lib\site-packages\jupyter_core\application.py", line 267, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "d:\Program Files\Anaconda2\lib\site-packages\traitlets\config\application.py", line 657, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-7>", line 2, in initialize
  File "d:\Program Files\Anaconda2\lib\site-packages\traitlets\config\application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "d:\Program Files\Anaconda2\lib\site-packages\notebook\notebookapp.py", line 1368, in initialize
    self.init_webapp()
  File "d:\Program Files\Anaconda2\lib\site-packages\notebook\notebookapp.py", line 1188, in init_webapp
    self.http_server.listen(port, self.ip)
  File "d:\Program Files\Anaconda2\lib\site-packages\tornado\tcpserver.py", line 142, in listen
    sockets = bind_sockets(port, address=address)
  File "d:\Program Files\Anaconda2\lib\site-packages\tornado\netutil.py", line 156, in bind_sockets
    0, flags)):
socket.gaierror: [Errno 10106] getaddrinfo failed

```
## System information
```
platform: win-64
version: 1.6.2
conda: 4.3.30
qt: 5.6.2
language: zh_CN
python: 2.7.13
os: Windows;7;6.1.7601;AMD64;Intel64 Family 6

**Comment by goanpeca** [comment]
Issue report seems incomplete
