### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by victorcoimbra** [ContinuumIO/anaconda-issues#7658]
## Main error
Application <b>spyder</b> launch may have produced errors.
## Traceback
```
Traceback (most recent call last):
  File "C:\Users\victor-pc\Anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 3011, in main
    mainwindow = run_spyder(app, options, args)
  File "C:\Users\victor-pc\Anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 2913, in run_spyder
    main.setup()
  File "C:\Users\victor-pc\Anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 766, in setup
    message=_("Spyder Internal Console\n\n"
  File "C:\Users\victor-pc\Anaconda3\lib\site-packages\spyder\plugins\console.py", line 65, in __init__
    light_background=light_background)
  File "C:\Users\victor-pc\Anaconda3\lib\site-packages\spyder\widgets\internalshell.py", line 141, in __init__
    profile)
  File "C:\Users\victor-pc\Anaconda3\lib\site-packages\spyder\widgets\shell.py", line 687, in __init__
    initial_message)
  File "C:\Users\victor-pc\Anaconda3\lib\site-packages\spyder\widgets\shell.py", line 71, in __init__
    self.history = self.load_history()
  File "C:\Users\victor-pc\Anaconda3\lib\site-packages\spyder\widgets\shell.py", line 521, in load_history
    encoding.writelines(rawhistory, self.history_filename)
  File "C:\Users\victor-pc\Anaconda3\lib\site-packages\spyder\utils\encoding.py", line 236, in writelines
    return write(os.linesep.join(lines), filename, encoding, mode)
  File "C:\Users\victor-pc\Anaconda3\lib\site-packages\spyder\utils\encoding.py", line 227, in write
    with open(filename, mode) as textfile:
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\victor-pc\\.spyder-py3\\history_internal.py'

```
## System information
```
python: 3.6.1
language: en_US
os: Windows;10;10.0.16299;AMD64;Intel64 Family 6 Model 158 Stepping 9, GenuineIntel
version: 1.6.2
platform: win-64
qt: 5.6.2
pyqt: 5.6.0
conda: 4.3.30
```

**Comment by victorcoimbra** [comment]
just reset everything and works, thanks!
