### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by qiuwenbogdut** [ContinuumIO/anaconda-issues#7672]
## Main error
Application <b>jupyterlab</b> launch may have produced errors.
## Traceback
```
[W 09:41:07.148 LabApp] Error loading server extension jupyter_nbextensions_configurator
    Traceback (most recent call last):
      File "E:\anaconda\lib\site-packages\notebook\notebookapp.py", line 1343, in init_server_extensions
        mod = importlib.import_module(modulename)
      File "E:\anaconda\lib\importlib\__init__.py", line 126, in import_module
        return _bootstrap._gcd_import(name[level:], package, level)
      File "<frozen importlib._bootstrap>", line 978, in _gcd_import
      File "<frozen importlib._bootstrap>", line 961, in _find_and_load
      File "<frozen importlib._bootstrap>", line 948, in _find_and_load_unlocked
    ModuleNotFoundError: No module named 'jupyter_nbextensions_configurator'
[W 09:41:07.149 LabApp] JupyterLab server extension not enabled, manually loading...
[I 09:41:07.149 LabApp] JupyterLab alpha preview extension loaded from E:\anaconda\lib\site-packages\jupyterlab
JupyterLab v0.27.0
Known labextensions:
[I 09:41:07.151 LabApp] Running the core application with no additional extensions or settings
[I 09:41:07.337 LabApp] Serving notebooks from local directory: C:\Users\CVTE
[I 09:41:07.337 LabApp] 0 active kernels
[I 09:41:07.337 LabApp] The Jupyter Notebook is running at:
[I 09:41:07.337 LabApp] http://localhost:8888/?token=644dd524f4b851e04c25e446a2e17d722405087e610c3965
[I 09:41:07.337 LabApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 09:41:07.339 LabApp] 
    
    Copy/paste this URL into your browser when you connect for the first time,

**Comment by goanpeca** [comment]
See https://github.com/jupyter/notebook/issues/2584 this might be related to a popup blocker plugin of your browser
