### ISSUE TITLE
anaconda-navigator fails with "No module named binstar_client"

### ISSUE THREAD

**Issue by jjpr** [ContinuumIO/anaconda-issues#774]
I updated to anaconda 4.0.0.  I later did "conda update --all", but IIRC the error was the same before and after that.  When I execute "anaconda-navigator" I get a trace ending in "ImportError: No module named binstar_client".  

```
Traceback (most recent call last):
  File "/Users/jjpr/anaconda/bin/anaconda-navigator", line 4, in <module>
    import anaconda_navigator.app.main
  File "/Users/jjpr/anaconda/lib/python2.7/site-packages/anaconda_navigator/app/main.py", line 22, in <module>
    from anaconda_navigator.widgets.main_window import MainWindow
  File "/Users/jjpr/anaconda/lib/python2.7/site-packages/anaconda_navigator/widgets/__init__.py", line 22, in <module>
    from anaconda_navigator.utils.analytics import GATracker
  File "/Users/jjpr/anaconda/lib/python2.7/site-packages/anaconda_navigator/utils/analytics.py", line 40, in <module>
    from anaconda_navigator.api import AnacondaAPI
  File "/Users/jjpr/anaconda/lib/python2.7/site-packages/anaconda_navigator/api/__init__.py", line 14, in <module>
    from anaconda_navigator.api.anaconda_api import AnacondaAPI
  File "/Users/jjpr/anaconda/lib/python2.7/site-packages/anaconda_navigator/api/anaconda_api.py", line 21, in <module>
    from conda_manager.api.manager_api import _ManagerAPI
  File "/Users/jjpr/anaconda/lib/python2.7/site-packages/conda_manager/__init__.py", line 13, in <module>
    from conda_manager import app, data, models, utils, widgets  # analysis:ignore
  File "/Users/jjpr/anaconda/lib/python2.7/site-packages/conda_manager/app/__init__.py", line 12, in <module>
    from .main import main               # analysis:ignore
  File "/Users/jjpr/anaconda/lib/python2.7/site-packages/conda_manager/app/main.py", line 18, in <module>
    from conda_manager.widgets.main_window import MainWindow
  File "/Users/jjpr/anaconda/lib/python2.7/site-packages/conda_manager/widgets/main_window.py", line 25, in <module>
    from conda_manager.widgets.packages import CondaPackagesWidget
  File "/Users/jjpr/anaconda/lib/python2.7/site-packages/conda_manager/widgets/packages.py", line 27, in <module>
    from conda_manager.api import ManagerAPI
  File "/Users/jjpr/anaconda/lib/python2.7/site-packages/conda_manager/api/__init__.py", line 9, in <module>
    from conda_manager.api.manager_api import ManagerAPI
  File "/Users/jjpr/anaconda/lib/python2.7/site-packages/conda_manager/api/manager_api.py", line 14, in <module>
    from conda_manager.api.client_api import ClientAPI
  File "/Users/jjpr/anaconda/lib/python2.7/site-packages/conda_manager/api/client_api.py", line 18, in <module>
    import binstar_client
ImportError: No module named binstar_client
```
From conda info:  
```
Current conda install:

             platform : osx-64
        conda version : 4.0.5
  conda-build version : 0+unknown
       python version : 2.7.11.final.0
     requests version : 2.9.1
     root environment : /Users/jjpr/anaconda  (writable)
  default environment : /Users/jjpr/anaconda
     envs directories : /Users/jjpr/anaconda/envs
        package cache : /Users/jjpr/anaconda/pkgs
         channel URLs : https://conda.anaconda.org/jjpr/osx-64/
                        https://conda.anaconda.org/jjpr/noarch/
                        https://conda.anaconda.org/jeprescottroy/osx-64/
                        https://conda.anaconda.org/jeprescottroy/noarch/
                        https://repo.continuum.io/pkgs/free/osx-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/osx-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : /Users/jjpr/.condarc
    is foreign system : False
```

**Comment by goanpeca** [comment]
Can you try to do `conda install anaconda-client` and try again?

**Comment by jjpr** [comment]
With "conda update anaconda-client" I just got:  

# All requested packages already installed.

but I tried "conda update -f anaconda-client" and it's now launching Anaconda Navigator.  

Thanks!  Problem solved!  

JJPR

**Comment by goanpeca** [comment]
Awesome :+:

**Comment by sjbaek** [comment]
I had the exact same issue, but "conda update -f anaconda-client" solved it. 
Thanks!

**Comment by aks18** [comment]
Wow! Same issue, solved with conda update -f anaconda-client

thanks. also can someone explain why this happened?
