### ISSUE TITLE
An unexpected error occurred on navigator start-up psutil.AccessDenied pid=9724

### ISSUE THREAD

**Issue by aanand1008** [ContinuumIO/anaconda-issues#7749]
I am getting below error when I start Anaconda Navigator on Windows from both Start Menu and Anaconda Prompt:
Traceback (most recent call last):
File "C:\ProgramData\Anaconda3\lib\site-packages\psutil\_pswindows.py", line 636, in wrapper
return fun(self, *args, **kwargs)
File "C:\ProgramData\Anaconda3\lib\site-packages\psutil\_pswindows.py", line 706, in cmdline
ret = cext.proc_cmdline(self.pid)
PermissionError: [WinError 5] Access is denied

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "C:\ProgramData\Anaconda3\lib\site-packages\anaconda_navigator\exceptions.py", line 75, in exception_handler
return_value = func(*args, **kwargs)
File "C:\ProgramData\Anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 113, in start_app
if misc.load_pid() is None: # A stale lock might be around
File "C:\ProgramData\Anaconda3\lib\site-packages\anaconda_navigator\utils\misc.py", line 384, in load_pid
cmds = process.cmdline()
File "C:\ProgramData\Anaconda3\lib\site-packages\psutil\__init__.py", line 721, in cmdline
return self._proc.cmdline()
File "C:\ProgramData\Anaconda3\lib\site-packages\psutil\_pswindows.py", line 639, in wrapper
raise AccessDenied(self.pid, self._name)
psutil.AccessDenied: psutil.AccessDenied (pid=9724)

I have run below commands in order to solve this issue in vain:
$ conda update anaconda-navigator
$ conda update navigator-updater
$ conda update --prefix C:\ProgramData\Anaconda3 anaconda

Kindly help me to solve this issue. Nothing worked for me

**Comment by aanand1008** [comment]
Got resolved automatically after windows updates
