### ISSUE TITLE
Error installing rasterstats package

### ISSUE THREAD

**Issue by devalc** [ContinuumIO/anaconda-issues#7775]
## Main error
Error installing rasterstats package with python 2 environment. Worked fine with python 3 environment.

The following errors occurred while installing it on python 2 environment:
## Traceback
```
Traceback (most recent call last):
  File "C:\Users\deva4998\AppData\Local\Continuum\Anaconda2\lib\site-packages\conda\exceptions.py", line 640, in conda_exception_handler
    return_value = func(*args, **kwargs)
  File "C:\Users\deva4998\AppData\Local\Continuum\Anaconda2\lib\site-packages\conda\cli\main.py", line 140, in _main
    exit_code = args.func(args, p)
  File "C:\Users\deva4998\AppData\Local\Continuum\Anaconda2\lib\site-packages\conda\cli\main_install.py", line 80, in execute
    install(args, parser, 'install')
  File "C:\Users\deva4998\AppData\Local\Continuum\Anaconda2\lib\site-packages\conda\cli\install.py", line 326, in install
    execute_actions(actions, index, verbose=not context.quiet)
  File "C:\Users\deva4998\AppData\Local\Continuum\Anaconda2\lib\site-packages\conda\plan.py", line 828, in execute_actions
    execute_instructions(plan, index, verbose)
  File "C:\Users\deva4998\AppData\Local\Continuum\Anaconda2\lib\site-packages\conda\instructions.py", line 247, in execute_instructions
    cmd(state, arg)
  File "C:\Users\deva4998\AppData\Local\Continuum\Anaconda2\lib\site-packages\conda\instructions.py", line 107, in UNLINKLINKTRANSACTION_CMD
    txn = UnlinkLinkTransaction.create_from_dists(index, prefix, unlink_dists, link_dists)
  File "C:\Users\deva4998\AppData\Local\Continuum\Anaconda2\lib\site-packages\conda\core\link.py", line 125, in create_from_dists
    for dist, pkg_dir in zip(link_dists, pkg_dirs_to_link))
  File "C:\Users\deva4998\AppData\Local\Continuum\Anaconda2\lib\site-packages\conda\core\link.py", line 125, in <genexpr>
    for dist, pkg_dir in zip(link_dists, pkg_dirs_to_link))
  File "C:\Users\deva4998\AppData\Local\Continuum\Anaconda2\lib\site-packages\conda\gateways\disk\read.py", line 84, in read_package_info
    paths_data = read_paths_json(extracted_package_directory)
  File "C:\Users\deva4998\AppData\Local\Continuum\Anaconda2\lib\site-packages\conda\gateways\disk\read.py", line 139, in read_paths_json
    data = json.load(paths_json)
  File "C:\Users\deva4998\AppData\Local\Continuum\Anaconda2\lib\json\__init__.py", line 291, in load
    **kw)
  File "C:\Users\deva4998\AppData\Local\Continuum\Anaconda2\lib\json\__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "C:\Users\deva4998\AppData\Local\Continuum\Anaconda2\lib\json\decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\deva4998\AppData\Local\Continuum\Anaconda2\lib\json\decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

```
## System information
```
platform: win-64
version: 1.6.2
conda: 4.3.30
qt: 5.6.2
language: en_US
python: 2.7.13
os: Windows;10;10.0.16299;AMD64;Intel64 Family 6 Model 158 Stepping 9, GenuineIntel
pyqt: 5.6.0
```

**Comment by csoja** [comment]
Where are you installing rasterstats from?  Do you have this problem installing anything in your Python2 environment, or is the problem limited to rasterstats?

**Comment by devalc** [comment]
I am installing rasterstats from conda packages (conda install -c conda-forge rasterstats). And I get the issue only while installing rasterstats in my python2 environment.

**Comment by csoja** [comment]
This isn't a package maintained by Anaconda, Inc. at this time, but by the conda-forge community.  Please open an issue here: https://github.com/conda-forge/rasterstats-feedstock
