### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by xiechenhao** [ContinuumIO/anaconda-issues#7787]
## Main error
Application <b>notebook</b> launch may have produced errors.
## Traceback
```
Traceback (most recent call last):
  File "D:\ProgramData\Anaconda3\Scripts\jupyter-notebook-script.py", line 6, in <module>
    from notebook.notebookapp import main
  File "D:\ProgramData\Anaconda3\lib\site-packages\notebook\notebookapp.py", line 36, in <module>
    from jinja2 import Environment, FileSystemLoader
  File "D:\ProgramData\Anaconda3\lib\site-packages\jinja2\__init__.py", line 33, in <module>
    from jinja2.environment import Environment, Template
  File "D:\ProgramData\Anaconda3\lib\site-packages\jinja2\environment.py", line 15, in <module>
    from jinja2 import nodes
  File "D:\ProgramData\Anaconda3\lib\site-packages\jinja2\nodes.py", line 19, in <module>
    from jinja2.utils import Markup
  File "D:\ProgramData\Anaconda3\lib\site-packages\jinja2\utils.py", line 624, in <module>
    from markupsafe import Markup, escape, soft_unicode
  File "D:\ProgramData\Anaconda3\lib\site-packages\markupsafe\__init__.py", line 14, in <module>
    from markupsafe._compat import text_type, string_types, int_types, \
ModuleNotFoundError: No module named 'markupsafe._compat'

```
## System information
```
python: 3.6.1
language: zh_CN
os: Windows;7;6.1.7601;AMD64;Intel64 Family 6 Model 58 Stepping 9, GenuineIntel
version: 1.6.2
platform: win-64
qt: 5.6.2
pyqt: 5.6.0
conda: 4.3.30
```

**Comment by goanpeca** [comment]
The traceback seems to be incomplete. What were you trying to accomplish?

Please update to the latest version of anaconda navigator 

Open a terminal (on Linux or Mac) or the Anaconda Command Prompt (on windows)
and type:

```
$ conda update conda
$ conda update anaconda-navigator
$ conda update navigator-updater
```
