### ISSUE TITLE
anaconda fails to launch

### ISSUE THREAD

**Issue by levisos92** [ContinuumIO/anaconda-issues#7796]
Traceback (most recent call last):
File "C:\Users\or_le\Anaconda2\lib\site-packages\anaconda_navigator\exceptions.py", line 75, in exception_handler
return_value = func(*args, **kwargs)
File "C:\Users\or_le\Anaconda2\lib\site-packages\anaconda_navigator\app\start.py", line 113, in start_app
if misc.load_pid() is None: # A stale lock might be around
File "C:\Users\or_le\Anaconda2\lib\site-packages\anaconda_navigator\utils\misc.py", line 384, in load_pid
cmds = process.cmdline()
File "C:\Users\or_le\Anaconda2\lib\site-packages\psutil\__init__.py", line 721, in cmdline
return self._proc.cmdline()
File "C:\Users\or_le\Anaconda2\lib\site-packages\psutil\_pswindows.py", line 639, in wrapper
raise AccessDenied(self.pid, self._name)
AccessDenied: psutil.AccessDenied (pid=9472)

***I've read some similar threads on the net and therfore updated anaconda navigator and updater. didn't help. Could you tell what is wrong? please help, it's urgent.
thanks.

**Comment by goanpeca** [comment]
@levisos92 please open the Anaconda Prompt and run 

```
anaconda-navigator --reset
```

And try again
