### ISSUE TITLE
Request - Add Pygraphviz to Anaconda channel

### ISSUE THREAD

**Issue by jgmorrison** [ContinuumIO/anaconda-issues#7798]
A customer has brought up that networkx( a package included in the Anaconda Distribution) is missing a dependency(pygraphviz) for its graphing abilities. It Is not available on the Anaconda channel.

```
>>>import networkx as nx
>>> G = nx.complete_graph(5)
>>> A = nx.nx_agraph.to_agraph(G)
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "/Users/jmorrison/anaconda2/lib/python2.7/site-packages/networkx/drawing/nx_agraph.py", line 133, in to_agraph
'http://pygraphviz.github.io/')
ImportError: ('requires pygraphviz ', 'http://pygraphviz.github.io/')
```

python-graphviz and graphviz are not suitable.  Can we get this added to the Anaconda channel?

**Comment by nehaljwani** [comment]
pygraphviz 1.3 for linux and macOS is available on defaults

**Comment by nehaljwani** [comment]
```
(test) [nwani@somebuildmachine aggregate]$ python
Python 3.5.4 |Anaconda, Inc.| (default, Nov 20 2017, 18:44:38) 
[GCC 7.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import networkx as nx                                                                                                                                                                                          
>>> G = nx.complete_graph(5)
>>> A = nx.nx_agraph.to_agraph(G)
>>> 
```

**Comment by nehaljwani** [comment]
I would vote for not closing this ticket until we have pygraphviz for Windows too.
