### ISSUE TITLE
Navigator:  on launching notebook, UnboundLocalError: local variable 'cmd' referenced before assignment

### ISSUE THREAD

**Issue by jjpr** [ContinuumIO/anaconda-issues#780]
```
Traceback (most recent call last):
  File "/Users/jjpr/anaconda/lib/python2.7/site-packages/anaconda_navigator/widgets/tabs/environments.py", line 277, in <lambda>
    lambda x, w=word: self.open_environment_in(w.lower()))
  File "/Users/jjpr/anaconda/lib/python2.7/site-packages/anaconda_navigator/widgets/tabs/environments.py", line 252, in open_environment_in
    launch.py_in_console(environment_prefix, which)
  File "/Users/jjpr/anaconda/lib/python2.7/site-packages/anaconda_navigator/utils/launch.py", line 143, in py_in_console
    cmd = activate + '/bin/' + cmd
UnboundLocalError: local variable 'cmd' referenced before assignment

```
in utils/launch.py, line 126, `elif prog == 'notebook':` should be`elif prog == 'jupyter notebook':`.  

Either that or change line 274 in widgets/tabs/environments.py.  

Lines 126 in launch.py and 274 in environments.py need to match, and they don't.  (Or don't use a string literal for this purpose.)

**Comment by ccordoba12** [comment]
Pinging @goanpeca about this one.

**Comment by goanpeca** [comment]
@jjpr we have fixed this error and will be released in a few weeks along with other bug corrections and enhancements.
