### ISSUE TITLE
Anaconda Navigator Start Error (pid=3768)

### ISSUE THREAD

**Issue by vmlmf** [ContinuumIO/anaconda-issues#7822]
Hello, i'm new to this situation envolving Navigator and now when i start it I'm having the following error:
![start error](https://user-images.githubusercontent.com/34633917/34084893-e4ad261e-e37f-11e7-9220-ac03339a966d.png)

Traceback (most recent call last):
File "C:\Users\vmlmf\Anaconda3\lib\site-packages\psutil\_pswindows.py", line 620, in wrapper
return fun(self, *args, **kwargs)
File "C:\Users\vmlmf\Anaconda3\lib\site-packages\psutil\_pswindows.py", line 690, in cmdline
ret = cext.proc_cmdline(self.pid)
PermissionError: [WinError 5] Access is denied

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "C:\Users\vmlmf\Anaconda3\lib\site-packages\anaconda_navigator\exceptions.py", line 75, in exception_handler
return_value = func(*args, **kwargs)
File "C:\Users\vmlmf\Anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 113, in start_app
if misc.load_pid() is None: # A stale lock might be around
File "C:\Users\vmlmf\Anaconda3\lib\site-packages\anaconda_navigator\utils\misc.py", line 384, in load_pid
cmds = process.cmdline()
File "C:\Users\vmlmf\Anaconda3\lib\site-packages\psutil\__init__.py", line 701, in cmdline
return self._proc.cmdline()
File "C:\Users\vmlmf\Anaconda3\lib\site-packages\psutil\_pswindows.py", line 623, in wrapper
raise AccessDenied(self.pid, self._name)
psutil.AccessDenied: psutil.AccessDenied (pid=3768)

Can anyone explain me what is happening? I already reinstalled the application and it didn't work.

Thanks in advance.

**Comment by goanpeca** [comment]
Please open the Anaconda Prompt:

```
anaconda-navigator --reset
```
