### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by riktimmondal** [ContinuumIO/anaconda-issues#7827]
## Main error
Application <b>spyder</b> launch may have produced errors.
## Traceback
```
Traceback (most recent call last):
  File "/home/tubai/anaconda3/envs/virtual_platform/lib/python3.5/site-packages/qtpy/QtWebEngineWidgets.py", line 22, in <module>
    from PyQt5.QtWebEngineWidgets import QWebEnginePage
ImportError: No module named 'PyQt5.QtWebEngineWidgets'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/tubai/anaconda3/envs/virtual_platform/bin/spyder", line 6, in <module>
    sys.exit(spyder.app.start.main())
  File "/home/tubai/anaconda3/envs/virtual_platform/lib/python3.5/site-packages/spyder/app/start.py", line 103, in main
    from spyder.app import mainwindow
  File "/home/tubai/anaconda3/envs/virtual_platform/lib/python3.5/site-packages/spyder/app/mainwindow.py", line 92, in <module>
    from qtpy import QtWebEngineWidgets  # analysis:ignore
  File "/home/tubai/anaconda3/envs/virtual_platform/lib/python3.5/site-packages/qtpy/QtWebEngineWidgets.py", line 26, in <module>
    from PyQt5.QtWebKitWidgets import QWebPage as QWebEnginePage
ImportError: libselinux.so.1: cannot open shared object file: No such file or directory

```
## System information
```
conda: 4.3.30
qt: 5.6.2
python: 3.5.4
os: Linux;4.9.33-1-MANJARO;#1 SMP PREEMPT Sat Jun 17 14:07:44 UTC 2017;x86_64;
platform: linux-64
version: 1.6.2
language: en_IN
pyqt: 5.6.0
```

**Comment by goanpeca** [comment]
Please install libselinux with your package manager to fix this error.
