### ISSUE TITLE
Anaconda 5.0.1 : navigator not starting on Windows 10

### ISSUE THREAD

**Issue by EmsArt** [ContinuumIO/anaconda-issues#7836]
The error returns this -->

Traceback (most recent call last):
File "C:\Users\John\Anaconda3\lib\site-packages\psutil\_pswindows.py", line 636, in wrapper
return fun(self, *args, **kwargs)
File "C:\Users\John\Anaconda3\lib\site-packages\psutil\_pswindows.py", line 706, in cmdline
ret = cext.proc_cmdline(self.pid)
PermissionError: [WinError 5] Access is denied

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "C:\Users\John\Anaconda3\lib\site-packages\anaconda_navigator\exceptions.py", line 75, in exception_handler
return_value = func(*args, **kwargs)
File "C:\Users\John\Anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 113, in start_app
if misc.load_pid() is None: # A stale lock might be around
File "C:\Users\John\Anaconda3\lib\site-packages\anaconda_navigator\utils\misc.py", line 384, in load_pid
cmds = process.cmdline()
File "C:\Users\John\Anaconda3\lib\site-packages\psutil\__init__.py", line 721, in cmdline
return self._proc.cmdline()
File "C:\Users\John\Anaconda3\lib\site-packages\psutil\_pswindows.py", line 639, in wrapper
raise AccessDenied(self.pid, self._name)
psutil.AccessDenied: psutil.AccessDenied (pid=3348)

any help most welcome
PS I have runned successfully conda update anaconda-navigator and conda update navigator-updater in the anaconda prompt console

**Comment by goanpeca** [comment]
@EmsArt please open the Anaconda prompt and run

```
anaconda-navigator --reset
```
