### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by ZizhenWang** [ContinuumIO/anaconda-issues#7859]
Hi

I have tried the method of #1984 but it doesn't help. I have also uninstalled and re-installed and still get the same error. I was using the Navigator without any problem up until today.

An unexpected error occurred on Navigator start-up
psutil.AccessDenied(pid=9332)

Traceback (most recent call last):
File "E:\anaconda\anaconda\lib\site-packages\anaconda_navigator\exceptions.py", line 75, in exception_handler
return_value = func(*args, **kwargs)
File "E:\anaconda\anaconda\lib\site-packages\anaconda_navigator\app\start.py", line 113, in start_app
if misc.load_pid() is None: # A stale lock might be around
File "E:\anaconda\anaconda\lib\site-packages\anaconda_navigator\utils\misc.py", line 384, in load_pid
cmds = process.cmdline()
File "E:\anaconda\anaconda\lib\site-packages\psutil\__init__.py", line 721, in cmdline
return self._proc.cmdline()
File "E:\anaconda\anaconda\lib\site-packages\psutil\_pswindows.py", line 639, in wrapper
raise AccessDenied(self.pid, self._name)
AccessDenied: psutil.AccessDenied (pid=9332)

the log of "anaconda-navigator --reset" is:
Anaconda Navigator configuration reset...
Anaconda Navigator configuration reset failed!!!
[Error 32] : u'C:\\Users\\wangzizhen\\.anaconda\\navigator\\logs\\navigator.log'

**Comment by goanpeca** [comment]
Please run

```
anaconda-navigator --reset

```

**Comment by ZizhenWang** [comment]
the log of "anaconda-navigator --reset" is:
Anaconda Navigator configuration reset...
Anaconda Navigator configuration reset failed!!!
[Error 32] : u'C:\Users\wangzizhen\.anaconda\navigator\logs\navigator.log'
