### ISSUE TITLE
Navigator will not start (possible Qt issue)

### ISSUE THREAD

**Issue by Peter-Clausen** [ContinuumIO/anaconda-issues#7865]
I have installed Ananconda 5.0.1 on a newly bought Windows 10 (x64) Lenovo L470 laptop. I'm unable to start Anaconda Navigator from windows meny or from terminal. It was suggested that I created an issue here from this thread:  https://groups.google.com/a/continuum.io/forum/#!topic/anaconda/_qB0OZgM_U4

I get the following error message when (C:\Users\kpc\anaconda3) C:\Users\kpc>anaconda-navigator

Traceback (most recent call last):
  File "C:\Users\kpc\anaconda3\Scripts\anaconda-navigator-script.py", line 10, in <module>
    sys.exit(main())
  File "C:\Users\kpc\anaconda3\lib\site-packages\anaconda_navigator\app\main.py", line 125, in main
    from anaconda_navigator.utils.logs import clean_logs
  File "C:\Users\kpc\anaconda3\lib\site-packages\anaconda_navigator\utils\__init__.py", line 15, in <module>
    from qtpy.QtGui import QIcon
  File "C:\Users\kpc\anaconda3\lib\site-packages\qtpy\QtGui.py", line 20, in <module>
    from PyQt5.QtGui import *
ImportError: DLL load failed: The specified procedure could not be found.

I have updated conda, anacondoa, navigator, Qt, PyQt etc, as suggested in different threads on the google groups forums.

**Conda Info:**

(C:\Users\kpc\anaconda3) C:\Users\kpc>conda info
Current conda install:

               platform : win-64
          conda version : 4.3.31
       conda is private : False
      conda-env version : 4.3.31
    conda-build version : 3.0.27
         python version : 3.6.3.final.0
       requests version : 2.18.4
       root environment : C:\Users\kpc\anaconda3  (writable)
    default environment : C:\Users\kpc\anaconda3
       envs directories : C:\Users\kpc\anaconda3\envs
                          C:\Users\kpc\AppData\Local\conda\conda\envs
                          C:\Users\kpc\.conda\envs
          package cache : C:\Users\kpc\anaconda3\pkgs
                          C:\Users\kpc\AppData\Local\conda\conda\pkgs
           channel URLs : https://repo.continuum.io/pkgs/main/win-64
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/win-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
            config file : None
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.31 requests/2.18.4 CPython/3.6.3 Windows/10 Windows/10.0.16299
          administrator : False

Conda list output is in:
[conda list.txt](https://github.com/ContinuumIO/anaconda-issues/files/1578654/conda.list.txt)

possible relevant packages:
anaconda-client           1.6.5            py36hd36550c_0
anaconda-navigator        1.6.10       py36h51c3d4f_0
conda                     4.3.31                py36_0
python                    3.6.3                 h9e2ca53_1
pyqt                      5.6.0                   py36hb5ed885_5
qt                        5.6.2                     vc14h6f8c307_12  [vc14]
qtpy                      1.3.1                   py36hb8717c5_0

On my system there are 3 other places where Qt is found when i search through the C:\ drive:
 **C:\Program Files\AMD\CNext\CNext** where there are several Qt5*** files such as Qt5Gui.dll (product version 5.5.0.0 and described as C++ application development framework)
**C:\Program Files\AMD\CIM\Bin64** where there are several Qt5*** files such as Qt5Gui.dll (product version 5.5.0.0 and described as C++ application development framework)
**C:\Users\kpc\AppData\Local\Microsoft\OneDrive\17.3.7131.1115** where there are several Qt5*** files such as Qt5Gui.dll (product version 5.9.1.0 and described as C++ application development framework)

I have also tried to reset Navigator C:\Users\kpc>anaconda-navigator --reset

Anaconda Navigator configuration reset...
Traceback (most recent call last):
  File "C:\Users\kpc\anaconda3\Scripts\anaconda-navigator-script.py", line 10, in <module>
    sys.exit(main())
  File "C:\Users\kpc\anaconda3\lib\site-packages\anaconda_navigator\app\main.py", line 101, in main
    from anaconda_navigator.config import CONF_PATH
  File "C:\Users\kpc\anaconda3\lib\site-packages\anaconda_navigator\config\__init__.py", line 22, in <module>
    from anaconda_navigator.config.base import (get_conf_path, get_home_dir,
  File "C:\Users\kpc\anaconda3\lib\site-packages\anaconda_navigator\config\base.py", line 18, in <module>
    from anaconda_navigator.utils import encoding
  File "C:\Users\kpc\anaconda3\lib\site-packages\anaconda_navigator\utils\__init__.py", line 15, in <module>
    from qtpy.QtGui import QIcon
  File "C:\Users\kpc\anaconda3\lib\site-packages\qtpy\QtGui.py", line 20, in <module>
    from PyQt5.QtGui import *
ImportError: DLL load failed: The specified procedure could not be found.

I'm happy to try other things to gather more info or find a solution.

Peter

**Comment by goanpeca** [comment]
Could you print the contents of your `PATH` variable?

**Comment by kpc-kpc** [comment]
Hi,

After installing Anaconda on some other systems (linux and Windows 10 VM)
without problems, I did an uninstall and then installed it again. This time
I used the default installation path which is C:\Users\kpc\AppData\Local\
Continuum\anaconda3 and now it all works fine. The original installation
path was  C:\Users\kpc\anaconda3.

The current PATH variable is:
PATH=C:\ProgramData\Oracle\Java\javapath;C:\Program Files (x86)\Intel\iCLS
Client\;C:\Program Files\Intel\iCLS
Client\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program
Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program
Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files
(x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program
Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program
Files\Git\cmd;C:\Program Files\Git\mingw64\bin;C:\Program
Files\Git\usr\bin;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common
Files\Intel\WirelessCommon\;C:\Users\kpc\AppData\Local\Microsoft\WindowsApps;C:\Program
Files (x86)\Sophos\Sophos SSL VPN
Client\bin;C:\Users\kpc\AppData\Local\atom\bin


best regards
Knut Peter
