### ISSUE TITLE
"Unknown encoding" from io.open("/etc/passwd")  on OS-X el-capitan

### ISSUE THREAD

**Issue by alxempirical** [ContinuumIO/anaconda-issues#787]
Fresh install (just now) from the [anaconda OS-X installer](http://repo.continuum.io/archive/Anaconda2-4.0.0-MacOSX-x86_64.sh):

```
bash-3.2$ ~/anaconda2/bin/python --version
Python 2.7.11 :: Anaconda 4.0.0 (x86_64)
bash-3.2$ python -c 'import io; io.open("/etc/passwd")'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
LookupError: unknown encoding: 
```

This is causing me grief when attempting to run [`python setup.py develop`](https://github.com/probcomp/bdbcontrib/issues/140)

Someone on `#python` suggested that this is a locale handling bug in anaconda.

```
bash-3.2$ locale
LANG="en_US"
LC_COLLATE="en_US"
LC_CTYPE="en_US"
LC_MESSAGES="en_US"
LC_MONETARY="en_US"
LC_NUMERIC="en_US"
LC_TIME="en_US"
LC_ALL=
bash-3.2$ 
```

I have run into a similar issue with `pydoc` / `help`:

```
bash-3.2$ pydoc matplotlib.pyplot.plot
Traceback (most recent call last):
  File "/Users/alx/anaconda/bin/pydoc", line 5, in <module>
    pydoc.cli()
  File "/Users/alx/anaconda2/lib/python2.7/pydoc.py", line 2377, in cli
    help.help(arg)
  File "/Users/alx/anaconda2/lib/python2.7/pydoc.py", line 1839, in help
    elif request: doc(request, 'Help on %s:')
  File "/Users/alx/anaconda2/lib/python2.7/pydoc.py", line 1578, in doc
    pager(render_doc(thing, title, forceload))
  File "/Users/alx/anaconda2/lib/python2.7/pydoc.py", line 1573, in render_doc
    return title % desc + '\n\n' + text.document(object, name)
  File "/Users/alx/anaconda2/lib/python2.7/pydoc.py", line 363, in document
    if inspect.isroutine(object): return self.docroutine(*args)
  File "/Users/alx/anaconda2/lib/python2.7/pydoc.py", line 1333, in docroutine
    doc = getdoc(object) or ''
  File "/Users/alx/anaconda2/lib/python2.7/pydoc.py", line 85, in getdoc
    result = _encode(result)
  File "/Users/alx/anaconda2/lib/python2.7/pydoc.py", line 206, in _encode
    return text.encode(encoding or _encoding, 'xmlcharrefreplace')
LookupError: unknown encoding: 
bash-3.2$ 
```

**Comment by alxempirical** [comment]
Bump.  Any suggestions about how to fix this?

Just ran into the same issue when attempting to execute a jupyter notebook non-interactively:

```
bash-3.2$ python -i ~/anaconda2/bin/jupyter-nbconvert --execute RUNME\ SIMULATE.ipynb
python -i ~/anaconda2/bin/jupyter-nbconvert --execute RUNME\ SIMULATE.ipynb
Traceback (most recent call last):
  File "/Users/alx/anaconda2/bin/jupyter-nbconvert", line 7, in <module>
    from nbconvert.nbconvertapp import main
  File "/Users/alx/anaconda2/lib/python2.7/site-packages/nbconvert/nbconvertapp.py", line 99, in <module>
    class NbConvertApp(JupyterApp):
  File "/Users/alx/anaconda2/lib/python2.7/site-packages/nbconvert/nbconvertapp.py", line 179, in NbConvertApp
    """.format(get_export_names()))
  File "/Users/alx/anaconda2/lib/python2.7/site-packages/nbconvert/exporters/export.py", line 210, in get_export_names
    sorted(entrypoints.get_group_named('nbconvert.exporters'))
  File "/Users/alx/anaconda2/lib/python2.7/site-packages/entrypoints.py", line 191, in get_group_named
    for ep in get_group_all(group, path=path):
  File "/Users/alx/anaconda2/lib/python2.7/site-packages/entrypoints.py", line 202, in get_group_all
    for config, distro in iter_files_distros(path=path):
  File "/Users/alx/anaconda2/lib/python2.7/site-packages/entrypoints.py", line 168, in iter_files_distros
    cp.read(path)
  File "/Users/alx/anaconda2/lib/python2.7/site-packages/backports/configparser/__init__.py", line 704, in read
    with open(filename, encoding=encoding) as fp:
LookupError: unknown encoding: 
>>> import pdb
import pdb
>>> pdb.pm()
pdb.pm()
> /Users/alx/anaconda2/lib/python2.7/site-packages/backports/configparser/__init__.py(704)read()
-> with open(filename, encoding=encoding) as fp:
(Pdb) filename
filename
'/usr/local/lib/python2.7/site-packages/autoflake-0.6.6.dist-info/entry_points.txt'
(Pdb) encoding
encoding
(Pdb) p encoding
p encoding
None
```

**Comment by msarahan** [comment]
I think you need this:
http://stackoverflow.com/questions/7165108/in-osx-lion-lang-is-not-set-to-utf8-how-fix

**Comment by alxempirical** [comment]
Thanks!
