### ISSUE TITLE
"ImportError: Failed to find TIFF library" - libtiff_ctypes.py looks for wrong file

### ISSUE THREAD

**Issue by mathnathan** [ContinuumIO/anaconda-issues#788]
On a clean 64bit Windows 7 Ultimate install with a fresh download of Anaconda the error was produced using the following method...

> [Anaconda2] C:\Users\root>conda install libtiff
Using Anaconda Cloud api site https://api.anaconda.org
Fetching package metadata: ....
Solving package specifications: .........

> Package plan for installation in environment C:\Users\root\Anaconda2:

> The following NEW packages will be INSTALLED:

>        libtiff: 4.0.6-vc9_1 [vc9]

> Proceed ([y]/n)? y

> Linking packages ...
> [      COMPLETE      ]|##################################################| 100%

This provides the libtiff wrapper. Next, to get the libtiff library itself we use pip...

> [Anaconda2] C:\Users\root>pip install libtiff
Collecting libtiff
Installing collected packages: libtiff
Successfully installed libtiff-0.4.0

Now when trying to import libtiff I get the *ImportError: Failed to find TIFF library* error

> [Anaconda2] C:\Users\root>python
Python 2.7.11 |Anaconda 4.0.0 (64-bit)| (default, Feb 16 2016, 09:58:36) [MSC v.
1500 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://anaconda.org
\>>> import libtiff
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\root\Anaconda2\lib\site-packages\libtiff\__init__.py", line 20,
 in <module>
    from .libtiff_ctypes import libtiff, TIFF, TIFF3D
  File "C:\Users\root\Anaconda2\lib\site-packages\libtiff\libtiff_ctypes.py", li
ne 41, in <module>
    raise ImportError('Failed to find TIFF library. Make sure that libtiff is in
stalled and its location is listed in PATH|LD_LIBRARY_PATH|..')
ImportError: Failed to find TIFF library. Make sure that libtiff is installed an
d its location is listed in PATH|LD_LIBRARY_PATH|..

So upon inspecting the file **libtiff_ctypes.py** I see the following code... 

```{Python}
if os.name=='nt':
    # assume that the directory of libtiff3.dll is in PATH.
    lib = ctypes.util.find_library('libtiff3')
    if lib is None:
        # try default installation path:
        lib = r'C:\Program Files\GnuWin32\bin\libtiff3.dll'
        if os.path.isfile (lib):
            print 'You should add %r to PATH environment variable and reboot.' % (os.path.dirname (lib))
        else:
            lib = None
```

However, looking over the install from `pip install libtiff` it was **libtiff.dll** that was installed not **libtiff3.dll**

Not sure where libtiff3 fits into the big picture (Python3?), but for me to get access to libtiff in python2.7 I simply changed the lines in libtiff_ctypes.py to look for libtiff.dll instead of libtiff3.dll.

I hope this helps others in the future find a more permanent solution.

**Comment by DieuTienBui** [comment]
For my case, I just replaced "C:\Program Files\GnuWin32\bin\libtiff3.dll" by lib = r'C:\Anaconda3\pkgs\libtiff-4.0.6-vc14_2\Library\bin\libtiff.dll', so run. 
(Please make sure the Libtiff version you install by Anaconda3, for me  it is "libtiff-4.0.6-vc14_2")

**Comment by mingwandroid** [comment]
You could instead either:
1. Activate.
2. and/or remove `C:\Program Files\GnuWin32\` from your system `PATH`. No user software should be on the system `PATH` really.
