### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by vinamrathakv** [ContinuumIO/anaconda-issues#7892]
## Main error
Application <b>spyder</b> launch may have produced errors.
## Traceback
```
Traceback (most recent call last):
  File "E:\Anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 3099, in main
    mainwindow = run_spyder(app, options, args)
  File "E:\Anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 3001, in run_spyder
    main.setup()
  File "E:\Anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 837, in setup
    from spyder.plugins.help import Help
  File "E:\Anaconda3\lib\site-packages\spyder\plugins\help.py", line 32, in <module>
    from spyder.utils.help.sphinxify import (CSS_PATH, generate_context,
  File "E:\Anaconda3\lib\site-packages\spyder\utils\help\sphinxify.py", line 30, in <module>
    from jinja2 import Environment, FileSystemLoader
  File "E:\Anaconda3\lib\site-packages\jinja2\__init__.py", line 33, in <module>
    from jinja2.environment import Environment, Template
  File "E:\Anaconda3\lib\site-packages\jinja2\environment.py", line 15, in <module>
    from jinja2 import nodes
  File "E:\Anaconda3\lib\site-packages\jinja2\nodes.py", line 19, in <module>
    from jinja2.utils import Markup
  File "E:\Anaconda3\lib\site-packages\jinja2\utils.py", line 624, in <module>
    from markupsafe import Markup, escape, soft_unicode
  File "E:\Anaconda3\lib\site-packages\markupsafe\__init__.py", line 14, in <module>
    from markupsafe._compat import text_type, string_types, int_types, \
ModuleNotFoundError: No module named 'markupsafe._compat'

```
## System information
```
python: 3.6.1
language: en_US
os: Windows;10;10.0.16299;AMD64;Intel64 Family 6 Model 158 Stepping 9, GenuineIntel
version: 1.6.2
platform: win-64
qt: 5.6.2
pyqt: 5.6.0
conda: 4.3.30
```

**Comment by goanpeca** [comment]
@vinamrathakv seems the installation is corrupt?

try force installing markupsafe

```
conda install markupsafe --force
```
