### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by assadRasheed** [ContinuumIO/anaconda-issues#7893]
## Main error
Application <b>notebook</b> launch may have produced errors.
## Traceback
```
Error processing line 2 of C:\ProgramData\Anaconda3\c.pth:

  Traceback (most recent call last):
    File "C:\ProgramData\Anaconda3\lib\site.py", line 168, in addpackage
      exec(line)
    File "<string>", line 1, in <module>
  ModuleNotFoundError: No module named 'c'

Remainder of file ignored
[I 16:27:07.137 NotebookApp] The port 8888 is already in use, trying another port.
[I 16:27:07.138 NotebookApp] The port 8889 is already in use, trying another port.
[I 16:27:07.451 NotebookApp] Serving notebooks from local directory: C:\Users\zaid-pc
[I 16:27:07.451 NotebookApp] 0 active kernels 
[I 16:27:07.452 NotebookApp] The Jupyter Notebook is running at: http://localhost:8890/?token=a6cd607e5c1ae5a300c2262d2159d234069b202c662fab7a
[I 16:27:07.452 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 16:27:07.490 NotebookApp] 
    
    Copy/paste this URL into your browser when you connect for the first time,
    to login with a token:
        http://localhost:8890/?token=a6cd607e5c1ae5a300c2262d2159d234069b202c662fab7a
[I 16:27:07.591 NotebookApp] Accepting one-time-token-authenticated connection from ::1

```
## System information
```
python: 3.6.1
language: en_US
os: Windows;8.1;6.3.9600;AMD64;Intel64 Family 6 Model 58 Stepping 9, GenuineIntel
version: 1.6.2
platform: win-64
qt: 5.6.2
pyqt: 5.6.0
conda: 4.3.31
```

**Comment by goanpeca** [comment]
Please install anaconda for the current user instead of all users
