### ISSUE TITLE
Scipy interpolate.interp1d broken in 0.17.1

### ISSUE THREAD

**Issue by delskorch** [ContinuumIO/anaconda-issues#793]
miniconda35
scipy 0.17.1 np111py35_0
numpy 1.11.0 py35_1
mkl 11.3.3 0

Appears to be a missing linalg DLL. I'm sure this breaks multiple things, but the problem can be demonstrated by trying to import interp1d:

```
python -c "from scipy.interpolate import interp1d"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\semigloss\Documents\ford\mosbot35\Miniconda35\lib\site-packages\scipy\interpolate\__init__.py", line 158, in <module>
    from .interpolate import *
  File "C:\Users\semigloss\Documents\ford\mosbot35\Miniconda35\lib\site-packages\scipy\interpolate\interpolate.py", line 11, in <module>
    import scipy.linalg
  File "C:\Users\semigloss\Documents\ford\mosbot35\Miniconda35\lib\site-packages\scipy\linalg\__init__.py", line 190, in <module>
    from ._decomp_update import *
  File "scipy/linalg/_decomp_update.pyx", line 1, in init scipy.linalg._decomp_update (scipy\linalg\_decomp_update.c:39400)
ImportError: DLL load failed: The specified module could not be found.
```

**Comment by patricksnape** [comment]
As a note - it also fails to import the `_ufuncs` package. Python 2.7 is totally broken right now! Scipy 0.17.1 links to VS2010 when it should link to VS2008! Note the missing dependencies via Dependency Walker. `mkl_intel_thread.dll` and `python27.dll` and red herrings are are actually satisfied at runtime. However, `libifcoremd.dll` and `libmmd.dll` appear to be Intel compiler runtime that are not being shipped. Furthermore, and possibly more dangerous is that scipy is linked against `msvcr100.dll` which is incorrect for Python 2.7. This is further illustrated by the conda install output
```
>>> conda create -n scipytest python=2.7 scipy=0.17.1
Fetching package metadata: ....
Solving package specifications: .........

Package plan for installation in environment C:\Miniconda3-32\envs\scipytest:

The following NEW packages will be INSTALLED:

    mkl:            11.3.3-0
    numpy:          1.11.0-py27_1
    pip:            8.1.1-py27_1
    python:         2.7.11-4
    scipy:          0.17.1-np111py27_0
    setuptools:     20.7.0-py27_0
    vs2008_runtime: 9.00.30729.1-0
    vs2010_runtime: 10.00.40219.1-0
    wheel:          0.29.0-py27_0

Proceed ([y]/n)?
```

@ilanschnell there seems to be a bug in the Anaconda build system.

![capture](https://cloud.githubusercontent.com/assets/708474/15294520/85392b7a-1b84-11e6-93d8-8531437e0d9d.PNG)

**Comment by kmuehlbauer** [comment]
@patricksnape The `msvcrt100.dll` issue also was/is discussed here: https://github.com/ContinuumIO/anaconda-issues/issues/753

Anyway, this is very much annoying, since this affects a whole bunch of packages. The error comes in various flavours and is sometimes hard to trace. 

Temporary solution we suggest is to pin mkl to 11.3.1 (like here: https://github.com/astropy/ci-helpers/pull/82.) But this can only be a very temporary solution.

**Comment by patricksnape** [comment]
Yes - I've got some experience spotting these errors and so the `DLL load Failed` error is one I'm very familiar with. Dependency Walker is always your friend here. The crux of it is that there are some Intel Compiler re distributable files that aren't being shipped any more that need to be copied as part of the MKL package (I believe).

**Comment by patricksnape** [comment]
Fixed by mkl 11.3.3-1 but scipy still incorrectly links to VS 2010.
