### ISSUE TITLE
UnicodeDecodeError

### ISSUE THREAD

**Issue by BuYanS** [ContinuumIO/anaconda-issues#8010]
Traceback (most recent call last):
  File "E:\Anaconda2\Scripts\conda-script.py", line 10, in <module>
    sys.exit(main())
  File "E:\Anaconda2\lib\site-packages\conda\cli\main.py", line 179, in main
    return handle_exception(e)
  File "E:\Anaconda2\lib\site-packages\conda\exceptions.py", line 634, in handle_exception
    print_unexpected_error_message(e)
  File "E:\Anaconda2\lib\site-packages\conda\exceptions.py", line 596, in print_unexpected_error_message
    stderrlogger.info(get_main_info_str(get_info_dict()))
  File "E:\Anaconda2\lib\site-packages\conda\cli\main_info.py", line 162, in get_info_dict
    from ..connection import user_agent
  File "E:\Anaconda2\lib\site-packages\conda\connection.py", line 12, in <module>
    from requests import Session, __version__ as REQUESTS_VERSION
  File "E:\Anaconda2\lib\site-packages\requests\__init__.py", line 52, in <module>
    from .packages.urllib3.contrib import pyopenssl
  File "E:\Anaconda2\lib\site-packages\requests\packages\urllib3\contrib\pyopenssl.py", line 47, in <module>
    from cryptography import x509
  File "E:\Anaconda2\lib\site-packages\cryptography\x509\__init__.py", line 7, in <module>
    from cryptography.x509.base import (
  File "E:\Anaconda2\lib\site-packages\cryptography\x509\base.py", line 16, in <module>
    from cryptography.x509.extensions import Extension, ExtensionType
  File "E:\Anaconda2\lib\site-packages\cryptography\x509\extensions.py", line 14, in <module>
    from asn1crypto.keys import PublicKeyInfo
  File "E:\Anaconda2\lib\site-packages\asn1crypto\keys.py", line 22, in <module>
    from ._elliptic_curve import (
  File "E:\Anaconda2\lib\site-packages\asn1crypto\_elliptic_curve.py", line 51, in <module>
    from ._int import inverse_mod
  File "E:\Anaconda2\lib\site-packages\asn1crypto\_int.py", line 56, in <module>
    from ._perf._big_num_ctypes import libcrypto
  File "E:\Anaconda2\lib\site-packages\asn1crypto\_perf\_big_num_ctypes.py", line 31, in <module>
    libcrypto_path = find_library('crypto')
  File "E:\Anaconda2\lib\ctypes\util.py", line 53, in find_library
    fname = os.path.join(directory, name)
  File "E:\Anaconda2\lib\ntpath.py", line 85, in join
    result_path = result_path + p_path
UnicodeDecodeError: 'ascii' codec can't decode byte 0xce in position 22: ordinal not in range(128)

**Comment by csoja** [comment]
Based on this error, it looks like you've got unicode characters in your path. We recommend Anaconda3 and Python 3 if you're using unicode as it is much more unicode friendly than Python 2.7.
