### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by Wei-Qun** [ContinuumIO/anaconda-issues#8020]
## Main error
Application <b>notebook</b> launch may have produced errors.
## Traceback
```
[I 09:53:11.870 NotebookApp] The port 8888 is already in use, trying another port.
[W 09:53:11.884 NotebookApp] Error loading server extension jupyter_nbextensions_configurator
    Traceback (most recent call last):
      File "D:\anaconda3\lib\site-packages\notebook\notebookapp.py", line 1271, in init_server_extensions
        mod = importlib.import_module(modulename)
      File "D:\anaconda3\lib\importlib\__init__.py", line 126, in import_module
        return _bootstrap._gcd_import(name[level:], package, level)
      File "<frozen importlib._bootstrap>", line 978, in _gcd_import
      File "<frozen importlib._bootstrap>", line 961, in _find_and_load
      File "<frozen importlib._bootstrap>", line 948, in _find_and_load_unlocked
    ModuleNotFoundError: No module named 'jupyter_nbextensions_configurator'
[I 09:53:12.110 NotebookApp] Serving notebooks from local directory: C:\Users\Administrator
[I 09:53:12.110 NotebookApp] 0 active kernels 
[I 09:53:12.110 NotebookApp] The Jupyter Notebook is running at: http://localhost:8889/?token=baf632214b94d471bd4e7cc1ccade18ce1bbfecbd8895a2f
[I 09:53:12.110 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 09:53:12.112 NotebookApp] 
    
    Copy/paste this URL into your browser when you connect for the first time,
    to login with a token:
        http://localhost:8889/?token=baf632214b94d471bd4e7cc1ccade18ce1bbfecbd8895a2f
[I 09:53:13.426 NotebookApp] Accepting one-time-token-authenticated connection from ::1
[W 09:53:13.969 NotebookApp] 404 GET /nbextensions/nbextensions_configurator/tree_tab/main.js?v=20180105095309 (::1) 33.19ms referer=http://localhost:8889/tree

```
## System information
```
python: 3.6.1
language: zh_CN
os: Windows;10;10.0.16299;AMD64;Intel64 Family 6 Model 94 Stepping 3, GenuineIntel
version: 1.6.2
platform: win-64
qt: 5.6.2
pyqt: 5.6.0
conda: 4.4.6
```

**Comment by goanpeca** [comment]
See https://github.com/jupyter/notebook/issues/2584
