### ISSUE TITLE
Possible issue with linear algebra pack used for numpy compilation

### ISSUE THREAD

**Issue by mrclary** [ContinuumIO/anaconda-issues#804]
I have recently discovered an issue with Anaconda installations of numpy >=1.9.3.
I believe it is related to the linear algebra library used to compile numpy since my MacPorts install of numpy 1.10.4 does not produce the error.
The behavior is detailed below.

With Anaconda numpy version <= 1.9.2 and all MacPorts numpy versions, polyfit behaved correctly, as follows:

    In [1]: np.polyfit([1, 10], [np.nan, np.nan], 1)
    Out[1]: array([ nan,  nan])

But for Anaconda numpy version >=1.9.3, polyfit raises the following error:

    In [1]: np.polyfit([1, 10], [np.nan, np.nan], 1)
    ---------------------------------------------------------------------------
    ValueError                                Traceback (most recent call last)
    <ipython-input-3-bf0d5d071f08> in <module>()
    ----> 1 np.polyfit([1, 10], [np.nan, np.nan], 1)
    
    /Users/rclary/anaconda/lib/python2.7/site-packages/numpy/lib/polynomial.pyc in polyfit(x, y, deg, rcond, full, w, cov)
        580     scale = NX.sqrt((lhs*lhs).sum(axis=0))
        581     lhs /= scale
    --> 582     c, resids, rank, s = lstsq(lhs, rhs, rcond)
        583     c = (c.T/scale).T  # broadcast scale coefficients
        584 
    
    /Users/rclary/anaconda/lib/python2.7/site-packages/numpy/linalg/linalg.pyc in lstsq(a, b, rcond)
       1865         work = zeros((lwork,), t)
       1866         results = lapack_routine(m, n, n_rhs, a, m, bstar, ldb, s, rcond,
    -> 1867                                  0, work, lwork, iwork, 0)
       1868     if results['info'] > 0:
       1869         raise LinAlgError('SVD did not converge in Linear Least Squares')
    
    ValueError: On entry to DGELSD parameter number 6 had an illegal value

Does anyone have any insight on this issue?

**Comment by jakirkham** [comment]
cc @ilanschnell @msarahan

**Comment by mrclary** [comment]
Upon further investigation, it appears to be isolated to the Intel Math Kernel Library (MKL).
Creating an Anaconda environment with nomkl does not exhibit this issue, regardless of numpy version.

**Comment by insertinterestingnamehere** [comment]
This seems like it is related to https://github.com/scipy/scipy/issues/6132 where the latest MKL quit accepting null parameters for arguments that are otherwise unused. More investigation is needed to say for sure though.

**Comment by seisdrum** [comment]
I have exactly the same problem. With the MKL version of numpy 1.11.2-py27_0 np.polyfit still crashes with the same error as above.

`conda remove mkl mkl-service` solves the problem for now.

**Comment by GregSilverman** [comment]
Getting same error and tried removing packages as recommended, but now I am getting the error that:
`ImportError: dlopen(/Users/gregsilverman/anaconda/lib/python3.5/site-packages/numpy/core/multiarray.so, 10): Library not loaded: @rpath/libmkl_intel_lp64.dylib
  Referenced from: /Users/gregsilverman/anaconda/lib/python3.5/site-packages/numpy/core/multiarray.so
  Reason: image not found`

So, had to reinstall said packages.

Back to square one.

**Comment by GregSilverman** [comment]
Filtering out NaN values worked, but this could get tedious, depending on the data being used.

**Comment by fkoehlin** [comment]
I can still confirm this issue for anaconda's Python 2.7.14 with numpy version 1.14.0-py27h8a80b8c_1 and scipy version 1.0.0-py27h793f721_0.
In my case though `numpy.linalg.inv`, `scipy.linalg.inv`and `scipy.linalg.solve` bounced back with the error message 
`File "/Users/fkoehlin/soft/anaconda2/lib/python2.7/site-packages/scipy/linalg/basic.py", line 963, in inv
    lu, piv, info = getrf(a1, overwrite_a=overwrite_a)
ValueError: On entry to DLASWP parameter number 6 had an illegal value`
when trying to invert a well-known matrix, which worked before and still does on other Linux systems without `anaconda` installed. Moreover, attempting an SVD inversion with `scipy.linalg.svd` turned into a random number generator (from one script execution to the other)...
Googling the error message led me to this thread here and switching back to `numpy` and `scipy` without MKL through
`conda install nomkl`
is my current workaround. My well-known matrix can be inverted again and the SVD also produces stable results again. Would be generally nice though to be able to use `numpy` and `scipy` reliably with MKL support...

**Comment by Negi93** [comment]
> I can still confirm this issue for anaconda's Python 2.7.14 with numpy version 1.14.0-py27h8a80b8c_1 and scipy version 1.0.0-py27h793f721_0.
> In my case though `numpy.linalg.inv`, `scipy.linalg.inv`and `scipy.linalg.solve` bounced back with the error message
> `File ".../anaconda2/lib/python2.7/site-packages/scipy/linalg/basic.py", line 963, in inv lu, piv, info = getrf(a1, overwrite_a=overwrite_a) ValueError: On entry to DLASWP parameter number 6 had an illegal value`
> when trying to invert a well-known matrix, which worked before and still does on other Linux systems without `anaconda` installed. Moreover, attempting an SVD inversion with `scipy.linalg.svd` turned into a random number generator (from one script execution to the other)...
> Googling the error message led me to this thread here and switching back to `numpy` and `scipy` without MKL through
> `conda install nomkl`
> is my current workaround. My well-known matrix can be inverted again and the SVD also produces stable results again. Would be generally nice though to be able to use `numpy` and `scipy` reliably with MKL support...

Thanks, 
"conda install nomkl" worked for me!
