### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by Wei-Qun** [ContinuumIO/anaconda-issues#8074]
## Main error
Application <b>notebook</b> launch may have produced errors.
## Traceback
```
[I 10:14:26.486 NotebookApp] The port 8888 is already in use, trying another port.
[W 10:14:26.503 NotebookApp] Error loading server extension jupyter_nbextensions_configurator
    Traceback (most recent call last):
      File "D:\anaconda3\lib\site-packages\notebook\notebookapp.py", line 1271, in init_server_extensions
        mod = importlib.import_module(modulename)
      File "D:\anaconda3\lib\importlib\__init__.py", line 126, in import_module
        return _bootstrap._gcd_import(name[level:], package, level)
      File "<frozen importlib._bootstrap>", line 978, in _gcd_import
      File "<frozen importlib._bootstrap>", line 961, in _find_and_load
      File "<frozen importlib._bootstrap>", line 948, in _find_and_load_unlocked
    ModuleNotFoundError: No module named 'jupyter_nbextensions_configurator'
[I 10:14:26.738 NotebookApp] Serving notebooks from local directory: C:\Users\Administrator
[I 10:14:26.739 NotebookApp] 0 active kernels 
[I 10:14:26.739 NotebookApp] The Jupyter Notebook is running at: http://localhost:8889/?token=81a9273efd1cea3f77707618363df45955097d14da4647f6
[I 10:14:26.739 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 10:14:26.754 NotebookApp] 
    
    Copy/paste this URL into your browser when you connect for the first time,
    to login with a token:
        http://localhost:8889/?token=81a9273efd1cea3f77707618363df45955097d14da4647f6
[I 10:14:27.470 NotebookApp] Accepting one-time-token-authenticated connection from ::1
[W 10:14:27.938 NotebookApp] 404 GET /nbextensions/nbextensions_configurator/tree_tab/main.js?v=20180110101424 (::1) 25.07ms referer=http://localhost:8889/tree

```
## System information
```
python: 3.6.1
language: zh_CN
os: Windows;10;10.0.16299;AMD64;Intel64 Family 6 Model 94 Stepping 3, GenuineIntel
version: 1.6.2
platform: win-64
qt: 5.6.2
pyqt: 5.6.0
conda: 4.4.6
```

**Comment by goanpeca** [comment]
See jupyter/notebook#2584, why ar eyou opening issue twice?
