### ISSUE TITLE
Can't run Anaconda Navigator after update

### ISSUE THREAD

**Issue by parnalte** [ContinuumIO/anaconda-issues#8081]
I have a fresh new install of Anaconda3 5.0.1 on Linux 64bit (Linux Mint 17.2).
After the installation, I run the Anaconda navigator from the CL, `$anaconda-navigator` and it worked fine. I could create a new environment there and add some packages. 
I got a prompt saying that a new version of the Anaconda was available, and I followed the instructions to update.
Now, when I try to run the Navigator I get this error:
____
```
$ anaconda-navigator 
An unexpected error occurred on Navigator start-up<br>'message'
Traceback (most recent call last):
  File "/home/pablo/anaconda3/lib/python3.6/site-packages/anaconda_navigator/exceptions.py", line 75, in exception_handler
    return_value = func(*args, **kwargs)
  File "/home/pablo/anaconda3/lib/python3.6/site-packages/anaconda_navigator/app/start.py", line 120, in start_app
    window = run_app(splash)
  File "/home/pablo/anaconda3/lib/python3.6/site-packages/anaconda_navigator/app/start.py", line 63, in run_app
    window = MainWindow(splash=splash)
  File "/home/pablo/anaconda3/lib/python3.6/site-packages/anaconda_navigator/widgets/main_window.py", line 161, in __init__
    self.api = AnacondaAPI()
  File "/home/pablo/anaconda3/lib/python3.6/site-packages/anaconda_navigator/api/anaconda_api.py", line 1269, in AnacondaAPI
    ANACONDA_API = _AnacondaAPI()
  File "/home/pablo/anaconda3/lib/python3.6/site-packages/anaconda_navigator/api/anaconda_api.py", line 71, in __init__
    self._conda_api = CondaAPI()
  File "/home/pablo/anaconda3/lib/python3.6/site-packages/anaconda_navigator/api/conda_api.py", line 1654, in CondaAPI
    CONDA_API = _CondaAPI()
  File "/home/pablo/anaconda3/lib/python3.6/site-packages/anaconda_navigator/api/conda_api.py", line 345, in __init__
    self.set_conda_prefix()
  File "/home/pablo/anaconda3/lib/python3.6/site-packages/anaconda_navigator/api/conda_api.py", line 493, in set_conda_prefix
    info = worker.communicate()[0]
  File "/home/pablo/anaconda3/lib/python3.6/site-packages/anaconda_navigator/api/conda_api.py", line 271, in communicate
    " ".join(self._cmd_list), result[0]['message']
KeyError: 'message'
```
____
Also, a new tab opens in my browser with this same error message.

I tried some solutions mentioned in other similar issues, with no success:
  * I tried updating the relevant packages with
  ```
  $conda update conda
  $conda update anaconda-navigator
  $conda update navigator-updater
  ```
  but all the requested packages were already installed. Current versions are:
  ```
  $ conda list anaconda
  # packages in environment at /home/pablo/anaconda3:
  #
  anaconda                  custom           py36hbbc8b67_0  
  anaconda-client           1.6.6            py36h59e3ba0_0  
  anaconda-navigator        1.6.11                   py36_0  
  anaconda-project          0.8.2            py36h44fb852_0  
  ```
  * I tried running `$anaconda-navigator --reset`, but nothing changed 
  * I checked that the path seems to be set correctly:
  ```
$ which conda
/home/pablo/anaconda3/bin/conda
$ which anaconda
/home/pablo/anaconda3/bin/anaconda
 $ which anaconda-navigator
/home/pablo/anaconda3/bin/anaconda-navigator
$ which python
/home/pablo/anaconda3/bin/python
  ```

Any idea on how to solve this? It would be easy for me to re-install from scratch, but would I hit the same problem again if I do this?

In case it is useful, here's the output of `$conda info`:
```
$ conda info

     active environment : None
            shell level : 0
       user config file : /home/pablo/.condarc
 populated config files : /home/pablo/.condarc
          conda version : 4.4.7
    conda-build version : 3.2.1
         python version : 3.6.4.final.0
       base environment : /home/pablo/anaconda3  (writable)
           channel URLs : https://repo.continuum.io/pkgs/main/linux-64
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/linux-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
          package cache : /home/pablo/anaconda3/pkgs
                          /home/pablo/.conda/pkgs
       envs directories : /home/pablo/anaconda3/envs
                          /home/pablo/.conda/envs
               platform : linux-64
             user-agent : conda/4.4.7 requests/2.18.4 CPython/3.6.4 Linux/3.16.0-38-generic ubuntu/14.04 glibc/2.19
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False
```

Thanks!

**Comment by parnalte** [comment]
After installing and running `anaconda-clean` this issue has been resolved. It looks like I had a mangled `~/.conda/` directory from a previous installation.
