### ISSUE TITLE
Can't open Spyder, failed to parse CPython sys.version

### ISSUE THREAD

**Issue by El-minadero** [ContinuumIO/anaconda-issues#8084]
I downloaded spyder  and ran it via the anaconda command:

`conda install spyder`
`spyder`

Spyder opens briefly, then immediately quits, spitting the following output to terminal:
`[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
Traceback (most recent call last):
  File "/anaconda3/lib/python3.6/site-packages/spyder/app/mainwindow.py", line 3126, in main
    mainwindow = run_spyder(app, options, args)
  File "/anaconda3/lib/python3.6/site-packages/spyder/app/mainwindow.py", line 3023, in run_spyder
    main.setup()
  File "/anaconda3/lib/python3.6/site-packages/spyder/app/mainwindow.py", line 862, in setup
    from spyder.plugins.editor import Editor
  File "/anaconda3/lib/python3.6/site-packages/spyder/plugins/editor.py", line 41, in <module>
    from spyder.utils.introspection.manager import IntrospectionManager
  File "/anaconda3/lib/python3.6/site-packages/spyder/utils/introspection/manager.py", line 21, in <module>
    from spyder.utils.introspection.plugin_client import PluginClient
  File "/anaconda3/lib/python3.6/site-packages/spyder/utils/introspection/plugin_client.py", line 18, in <module>
    import zmq
  File "/anaconda3/lib/python3.6/site-packages/zmq/__init__.py", line 34, in <module>
    from zmq import backend
  File "/anaconda3/lib/python3.6/site-packages/zmq/backend/__init__.py", line 21, in <module>
    if platform.python_implementation() == 'PyPy':
  File "/anaconda3/lib/python3.6/platform.py", line 1234, in python_implementation
    return _sys_version()[0]
  File "/anaconda3/lib/python3.6/platform.py", line 1192, in _sys_version
    repr(sys_version))
**ValueError: failed to parse CPython sys.version: '3.6.3 |Anaconda custom (64-bit)| (default, Oct  6 2017, 12:04:38) \n[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)**]'
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0`

Why is it throwing this exception and how do I go about fixing it?

**Comment by csoja** [comment]
Have you updated Spyder?

**Comment by El-minadero** [comment]
confirmed that updating to 3.3.4 resolves the error.
