### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by sapphirehx** [ContinuumIO/anaconda-issues#8170]
## Main error
Application <b>spyder</b> launch may have produced errors.
## Traceback
```
Traceback (most recent call last):
  File "D:\Anaconda3\Scripts\spyder-script.py", line 5, in <module>
    sys.exit(spyder.app.start.main())
  File "D:\Anaconda3\lib\site-packages\spyder\app\start.py", line 103, in main
    from spyder.app import mainwindow
  File "D:\Anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 165, in <module>
    from spyder.utils.environ import WinUserEnvDialog
  File "D:\Anaconda3\lib\site-packages\spyder\utils\environ.py", line 20, in <module>
    from spyder.widgets.variableexplorer.collectionseditor import CollectionsEditor
  File "D:\Anaconda3\lib\site-packages\spyder\widgets\variableexplorer\collectionseditor.py", line 46, in <module>
    from spyder.widgets.variableexplorer.importwizard import ImportWizard
  File "D:\Anaconda3\lib\site-packages\spyder\widgets\variableexplorer\importwizard.py", line 26, in <module>
    import pandas as pd
  File "D:\Anaconda3\lib\site-packages\pandas\__init__.py", line 23, in <module>
    from pandas.compat.numpy import *
  File "D:\Anaconda3\lib\site-packages\pandas\compat\numpy\__init__.py", line 10, in <module>
    _np_version = np.__version__
AttributeError: module 'numpy' has no attribute '__version__'

```
## System information
```
python: 3.6.1
language: zh_CN
os: Windows;7;6.1.7601;AMD64;Intel64 Family 6 Model 78 Stepping 3, GenuineIntel
version: 1.6.2
platform: win-64
qt: 5.6.2
pyqt: 5.6.0
conda: 4.3.21
```

**Comment by goanpeca** [comment]
Please remember to update to the latest version of Navigator to include
the latest fixes.

Open a terminal (on Linux or Mac) or the Anaconda Command Prompt (on windows)
and type:

```
conda update conda
conda update anaconda-navigator
conda update navigator-updater
```

Try reinstalling numpy

```
conda install numpy -f
```
