### ISSUE TITLE
navigator error after I updated all 

### ISSUE THREAD

**Issue by vivlwr** [ContinuumIO/anaconda-issues#8177]
I updated conda, anaconda-navigator, and all package except numpy.
Later I started navigator, the following message showed.

Traceback (most recent call last):
File "D:\Anaconda3\lib\site-packages\psutil\_pswindows.py", line 635, in wrapper
return fun(self, *args, **kwargs)
File "D:\Anaconda3\lib\site-packages\psutil\_pswindows.py", line 705, in cmdline
ret = cext.proc_cmdline(self.pid)
PermissionError: [WinError 5] 拒绝访问。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "D:\Anaconda3\lib\site-packages\anaconda_navigator\exceptions.py", line 75, in exception_handler
return_value = func(*args, **kwargs)
File "D:\Anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 113, in start_app
if misc.load_pid() is None: # A stale lock might be around
File "D:\Anaconda3\lib\site-packages\anaconda_navigator\utils\misc.py", line 384, in load_pid
cmds = process.cmdline()
File "D:\Anaconda3\lib\site-packages\psutil\__init__.py", line 666, in cmdline
return self._proc.cmdline()
File "D:\Anaconda3\lib\site-packages\psutil\_pswindows.py", line 638, in wrapper
raise AccessDenied(self.pid, self._name)
psutil._exceptions.AccessDenied: psutil.AccessDenied (pid=2924)

**Comment by ZhuQiaoqiao** [comment]
I have encountered the same problem as yours，is your problem solved ？ please tell me how to solve Thank you

**Comment by vivlwr** [comment]
Hi, I forgot to update this:
conda update navigator-updater
All error fixed. 
You can try.
