### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by yauh-xx** [ContinuumIO/anaconda-issues#8218]
## Main error
Application <b>jupyterlab</b> launch may have produced errors.
## Traceback
```
Traceback (most recent call last):
  File "c:\Programs\Anaconda\Scripts\jupyter-lab-script.py", line 6, in <module>
    from jupyterlab.labapp import main
  File "c:\Programs\Anaconda\lib\site-packages\jupyterlab\labapp.py", line 7, in <module>
    from notebook.notebookapp import NotebookApp, aliases, flags
  File "c:\Programs\Anaconda\lib\site-packages\notebook\__init__.py", line 25, in <module>
    from .nbextensions import install_nbextension
  File "c:\Programs\Anaconda\lib\site-packages\notebook\nbextensions.py", line 27, in <module>
    from jupyter_core.utils import ensure_dir_exists
ImportError: cannot import name 'ensure_dir_exists'

```
## System information
```
python: 3.6.1
language: ru_RU
os: Windows;10;10.0.16299;AMD64;Intel64 Family 6 Model 94 Stepping 3, GenuineIntel
version: 1.6.2
platform: win-64
qt: 5.6.2
pyqt: 5.6.0
conda: 4.4.4
```

**Comment by goanpeca** [comment]
Try 

```
conda install nbextensions --force
```

**Comment by amveerappan** [comment]
@goanpeca Still the same issue

**Comment by goanpeca** [comment]
try

```
conda upgrade jupyter_core
```

**Comment by perepau** [comment]
Worked!
