### ISSUE TITLE
After update problem

### ISSUE THREAD

**Issue by massecre2** [ContinuumIO/anaconda-issues#8228]
```
Main Error

'root_prefix'

Traceback

Traceback (most recent call last):
  File "D:\Python\Anaconda\lib\site-packages\anaconda_navigator\exceptions.py", line 75, in exception_handler
    return_value = func(*args, **kwargs)
  File "D:\Python\Anaconda\lib\site-packages\anaconda_navigator\app\start.py", line 120, in start_app
    window = run_app(splash)
  File "D:\Python\Anaconda\lib\site-packages\anaconda_navigator\app\start.py", line 63, in run_app
    window = MainWindow(splash=splash)
  File "D:\Python\Anaconda\lib\site-packages\anaconda_navigator\widgets\main_window.py", line 162, in __init__
    self.api = AnacondaAPI()
  File "D:\Python\Anaconda\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 1270, in AnacondaAPI
    ANACONDA_API = _AnacondaAPI()
  File "D:\Python\Anaconda\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 71, in __init__
    self._conda_api = CondaAPI()
  File "D:\Python\Anaconda\lib\site-packages\anaconda_navigator\api\conda_api.py", line 1663, in CondaAPI
    CONDA_API = _CondaAPI()
  File "D:\Python\Anaconda\lib\site-packages\anaconda_navigator\api\conda_api.py", line 346, in __init__
    self.set_conda_prefix()
  File "D:\Python\Anaconda\lib\site-packages\anaconda_navigator\api\conda_api.py", line 495, in set_conda_prefix
    self.ROOT_PREFIX = info['root_prefix']
KeyError: 'root_prefix'
```

when i update anaconda in anaconda prompt ``` conda update conda ``` gettin this issue. By the way conda prompt output below : 

```
(base) C:\Users\Oğuzhan> conda update conda
Solving environment: done

## Package Plan ##

  environment location: D:\Python\Anaconda

  added / updated specs:
    - conda


The following packages will be UPDATED:

    certifi: 2017.7.27.1-py36h043bc9e_0 --> 2017.11.5-py36hb8ac631_0
    openssl: 1.0.2l-vc14hcac20b0_2      --> 1.0.2n-h74b6da3_0

Proceed ([y]/n)? y

Preparing transaction: done
Verifying transaction: done
Executing transaction: failed
ERROR conda.core.link:_execute(481): An error occurred while installing package 'None'.
UnicodeDecodeError('utf-8', b'C:\\Users\\O\xf0uzhan\\.conda\\envs\\environment_name\r\nC:\\Program Files\\Anaconda3\\envs\\name_of_my_env\r\n', 10, 11, 'invalid continuation byte')
Attempting to roll back.

Rolling back transaction: done

UnicodeDecodeError('utf-8', b'C:\\Users\\O\xf0uzhan\\.conda\\envs\\environment_name\r\nC:\\Program Files\\Anaconda3\\envs\\name_of_my_env\r\n', 10, 11, 'invalid continuation byte')
```

**Comment by goanpeca** [comment]
@massecre2 it seems you have a non ascii character on your username, and it is currenly not fully supported.

`xf0uzhan`
