### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by Code37** [ContinuumIO/anaconda-issues#8236]
## Main error
Application <b>notebook</b> launch may have produced errors.
## Traceback
```
Traceback (most recent call last):
  File "D:\Anaconda3\Scripts\jupyter-notebook-script.py", line 6, in <module>
    from notebook.notebookapp import main
  File "D:\Anaconda3\lib\site-packages\notebook\__init__.py", line 25, in <module>
    from .nbextensions import install_nbextension
  File "D:\Anaconda3\lib\site-packages\notebook\nbextensions.py", line 27, in <module>
    from jupyter_core.utils import ensure_dir_exists
ImportError: cannot import name 'ensure_dir_exists'

```
## System information
```
python: 3.6.1
language: zh_CN
os: Windows;10;10.0.16299;AMD64;Intel64 Family 6 Model 94 Stepping 3, GenuineIntel
version: 1.6.2
platform: win-64
qt: 5.6.2
pyqt: 5.6.0
conda: 4.3.30
```

**Comment by Code37** [comment]
update jupyter_core to 4.4.0
