### ISSUE TITLE
Unable to install jupyterlab with anaconda-navigator

### ISSUE THREAD

**Issue by scubamut** [ContinuumIO/anaconda-issues#8265]
### Actual Behavior

unable to install jupyterlab after new installion of anaconda-navigator

### Expected Behavior

install jupyterlab

### Steps to Reproduce

Miniconda3-latest-Windows-x86_64 installed.
Activated root.
conda install anaconda-navigator.
Anaconda-navigator started sucessfully.
Clicked jupyterlab "install" -

Conda process error
The following errors occurred:
NotWritableError: The current user does not have write permissions to a required path.
path: C:\Users\scuba\C:\Users\scuba\.conda\environments.txt

> Traceback (most recent call last):
  File "C:\Users\scuba\Miniconda3\lib\site-packages\anaconda_navigator\widgets\main_window.py", line 1064, in check_outdated_channels
    self.add_default_channels(conda_data)
  File "C:\Users\scuba\Miniconda3\lib\site-packages\anaconda_navigator\widgets\main_window.py", line 1055, in add_default_channels
    worker.communicate()
  File "C:\Users\scuba\Miniconda3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 279, in communicate
    result[0], result[-1], **self._extra_kwargs
  File "C:\Users\scuba\Miniconda3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 1112, in <lambda>
    callback=lambda o, e: o.get('warnings', [])
AttributeError: 'bytes' object has no attribute 'get'
2018-01-24 11:23:23,833 - ERROR main_window._conda_output_ready:1593
NotWritableError: The current user does not have write permissions to a required path./n  path: C:/Users/scuba/C:/Users/scuba/.conda/environments.txt/n->

##### Anaconda or Miniconda version:
Miniconda3-latest-Windows-x86_64
##### Operating System:
windows 10 
##### `conda info`

```
(base) C:\Users\scuba\Miniconda3\Scripts>conda info

     active environment : base
    active env location : C:\Users\scuba\Miniconda3
            shell level : 1
       user config file : C:\Users\scuba\Miniconda3\Scripts\%USERPROFILE%\.condarc
 populated config files :
          conda version : 4.4.7
    conda-build version : not installed
         python version : 3.6.3.final.0
       base environment : C:\Users\scuba\Miniconda3  (writable)
           channel URLs : https://repo.continuum.io/pkgs/main/win-64
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/win-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
          package cache : C:\Users\scuba\Miniconda3\pkgs
                          C:\Users\scuba\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\scuba\Miniconda3\envs
                          C:\Users\scuba\AppData\Local\conda\conda\envs
                          C:\Users\scuba\Miniconda3\Scripts\%USERPROFILE%\.conda\envs
               platform : win-64
             user-agent : conda/4.4.7 requests/2.18.4 CPython/3.6.3 Windows/10 Windows/10.0.15063
          administrator : False
             netrc file : None
           offline mode : False
```

##### `conda list --show-channel-urls`

```
(base) C:\Users\scuba\Miniconda3\Scripts>conda list --show-channel-urls
# packages in environment at C:\Users\scuba\Miniconda3:
#
anaconda-client           1.6.7                    py36_0    defaults
anaconda-navigator        1.6.12           py36hdad2993_0    defaults
anaconda-project          0.8.2            py36hfad2e28_0    defaults
asn1crypto                0.23.0           py36h546eea3_0    defaults
ca-certificates           2017.08.26           h94faf87_0    defaults
certifi                   2017.11.5        py36hb8ac631_0    defaults
cffi                      1.11.2           py36h829d1a5_0    defaults
chardet                   3.0.4            py36h420ce6e_1    defaults
clyent                    1.2.2            py36hb10d595_1    defaults
conda                     4.4.7                    py36_0    defaults
conda-env                 2.6.0                h36134e3_1    defaults
console_shortcut          0.1.1                h6bb2dd7_3    defaults
cryptography              2.1.4            py36he1d7878_0    defaults
decorator                 4.2.1                    py36_0    defaults
freetype                  2.8                  h51f8f2c_1    defaults
icu                       58.2                 ha66f8fd_1    defaults
idna                      2.6              py36h148d497_1    defaults
ipython_genutils          0.2.0            py36h3c5d0ee_0    defaults
jpeg                      9b                   hb83a4c4_2    defaults
jsonschema                2.6.0            py36h7636477_0    defaults
jupyter_core              4.4.0            py36h56e9d50_0    defaults
libpng                    1.6.34               h79bbb47_0    defaults
libtiff                   4.0.9                h0f13578_0    defaults
menuinst                  1.4.10           py36h42196fb_0    defaults
nbformat                  4.4.0            py36h3a5bc1b_0    defaults
olefile                   0.44             py36h0a7bdd2_0    defaults
openssl                   1.0.2n               h74b6da3_0    defaults
pillow                    5.0.0            py36h0738816_0    defaults
pip                       9.0.1            py36h226ae91_4    defaults
psutil                    5.4.3            py36hfa6e2cd_0    defaults
pycosat                   0.6.3            py36h413d8a4_0    defaults
pycparser                 2.18             py36hd053e01_1    defaults
pyopenssl                 17.5.0           py36h5b7d817_0    defaults
pyqt                      5.6.0            py36hb5ed885_5    defaults
pysocks                   1.6.7            py36h698d350_1    defaults
python                    3.6.3                h3b118a2_4    defaults
python-dateutil           2.6.1            py36h509ddcb_1    defaults
pytz                      2017.3           py36h1d3fa6b_0    defaults
pywin32                   221              py36h9c10281_0    defaults
pyyaml                    3.12             py36h1d1928f_1    defaults
qt                        5.6.2           vc14h6f8c307_12  [vc14]  defaults
qtpy                      1.3.1            py36hb8717c5_0    defaults
requests                  2.18.4           py36h4371aae_1    defaults
ruamel_yaml               0.11.14          py36h9b16331_2    defaults
setuptools                36.5.0           py36h65f9e6e_0    defaults
sip                       4.18.1           py36h9c25514_2    defaults
six                       1.11.0           py36h4db2310_1    defaults
sqlite                    3.21.0               h9d3ae62_0    defaults
tk                        8.6.7                hcb92d03_3    defaults
tornado                   4.5.3                    py36_0    defaults
traitlets                 4.3.2            py36h096827d_0    defaults
urllib3                   1.22             py36h276f60a_0    defaults
vc                        14                   h2379b0c_2    defaults
vs2015_runtime            14.0.25123           hd4c4e62_2    defaults
wheel                     0.30.0           py36h6c3ec14_1    defaults
win_inet_pton             1.0.1            py36he67d7fd_1    defaults
wincertstore              0.2              py36h7fe50ca_0    defaults
yaml                      0.1.7                hc54c509_2    defaults
zlib                      1.2.11               h8395fce_2    defaults
```

**Comment by goanpeca** [comment]
Please remember to update to the latest version of Navigator to include
the latest fixes.

Open a terminal (on Linux or Mac) or the Anaconda Command Prompt (on windows)
and type:

```
conda update conda
conda update anaconda-navigator
conda update navigator-updater
```
