### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by Mengdi1** [ContinuumIO/anaconda-issues#8274]
## Main error
Application <b>notebook</b> launch may have produced errors.
## Traceback
```
Traceback (most recent call last):
  File "C:\Users\Mengmeng\Anaconda3\Scripts\jupyter-notebook-script.py", line 6, in <module>
    from notebook.notebookapp import main
  File "C:\Users\Mengmeng\Anaconda3\lib\site-packages\notebook\__init__.py", line 25, in <module>
    from .nbextensions import install_nbextension
  File "C:\Users\Mengmeng\Anaconda3\lib\site-packages\notebook\nbextensions.py", line 27, in <module>
    from jupyter_core.utils import ensure_dir_exists
ImportError: cannot import name 'ensure_dir_exists'

```
## System information
```
python: 3.6.1
language: zh_CN
os: Windows;10;10.0.15063;AMD64;Intel64 Family 6 Model 69 Stepping 1, GenuineIntel
version: 1.6.2
platform: win-64
qt: 5.6.2
pyqt: 5.6.0
conda: 4.3.29
```

**Comment by goanpeca** [comment]
Try

```
conda upgrade jupyter_core
```

**Comment by Mengdi1** [comment]
@goanpeca  Thank you. I've already reinstalled the anaconda but thank you anyway!
