### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by jjyock** [ContinuumIO/anaconda-issues#8320]
## Main error
Application <b>notebook</b> launch may have produced errors.
## Traceback
```
Traceback (most recent call last):
  File "F:\Anaconda3\Scripts\jupyter-notebook-script.py", line 5, in <module>
    sys.exit(notebook.notebookapp.main())
  File "F:\Anaconda3\lib\site-packages\jupyter_core\application.py", line 267, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "F:\Anaconda3\lib\site-packages\traitlets\config\application.py", line 657, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-7>", line 2, in initialize
  File "F:\Anaconda3\lib\site-packages\traitlets\config\application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "F:\Anaconda3\lib\site-packages\notebook\notebookapp.py", line 1290, in initialize
    super(NotebookApp, self).initialize(argv)
  File "<decorator-gen-6>", line 2, in initialize
  File "F:\Anaconda3\lib\site-packages\traitlets\config\application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "F:\Anaconda3\lib\site-packages\jupyter_core\application.py", line 243, in initialize
    self.migrate_config()
  File "F:\Anaconda3\lib\site-packages\jupyter_core\application.py", line 169, in migrate_config
    migrate()
  File "F:\Anaconda3\lib\site-packages\jupyter_core\migrate.py", line 240, in migrate
    ensure_dir_exists(env['jupyter_config'])
  File "F:\Anaconda3\lib\site-packages\ipython_genutils\path.py", line 167, in ensure_dir_exists
    os.makedirs(path, mode=mode)
  File "F:\Anaconda3\lib\os.py", line 220, in makedirs
    mkdir(name, mode)
PermissionError: [WinError 5] 拒绝访问。: 'C:\\WINDOWS\\system32\\config\\systemprofile\\.jupyter'

```
## System information
```
python: 3.6.1
language: zh_CN
os: Windows;10;10.0.16299;AMD64;Intel64 Family 6 Model 61 Stepping 4, GenuineIntel
version: 1.6.2
platform: win-64
qt: 5.6.2
pyqt: 5.6.0
conda: 4.3.21
```

**Comment by goanpeca** [comment]
Please delete this file manually 'C:\\WINDOWS\\system32\\config\\systemprofile\\.jupyter'

---

Please remember to update to the latest version of Navigator to include
the latest fixes.

Open a terminal (on Linux or Mac) or the Anaconda Command Prompt (on windows)
and type:

```
conda update conda
conda update anaconda-navigator
conda update navigator-updater
```
