### ISSUE TITLE
Importing numpy in windows 10

### ISSUE THREAD

**Issue by haicen** [ContinuumIO/anaconda-issues#8346]
It is not possible to import numpy through the command line on windows 10. numpy imports correctly in the spyder IDE, ipython console, and jupyter notebooks.

### Actual Behavior

`import numpy` fails with an error

```
Python 3.5.4 |Anaconda custom (64-bit)| (default, Nov  8 2017, 14:34:30) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\brandon9\AppData\Local\Continuum\Anaconda3\lib\site-packages\numpy\__init__.py", line 142, in <module>
    from . import add_newdocs
  File "C:\Users\brandon9\AppData\Local\Continuum\Anaconda3\lib\site-packages\numpy\add_newdocs.py", line 13, in <module>
    from numpy.lib import add_newdoc
  File "C:\Users\brandon9\AppData\Local\Continuum\Anaconda3\lib\site-packages\numpy\lib\__init__.py", line 8, in <module>
    from .type_check import *
  File "C:\Users\brandon9\AppData\Local\Continuum\Anaconda3\lib\site-packages\numpy\lib\type_check.py", line 11, in <module>
    import numpy.core.numeric as _nx
  File "C:\Users\brandon9\AppData\Local\Continuum\Anaconda3\lib\site-packages\numpy\core\__init__.py", line 16, in <module>
    from . import multiarray
SystemError: initialization of multiarray raised unreported exception
```

### Expected Behavior

numpy should import

### Steps to Reproduce

import numpy

##### Operating System:

Windows 10

##### `conda info`

```
     active environment : None
       user config file : C:\Users\brandon9\.condarc
 populated config files : C:\Users\brandon9\.condarc
          conda version : 4.4.8
    conda-build version : 0+unknown
         python version : 3.5.4.final.0
       base environment : C:\Users\brandon9\AppData\Local\Continuum\Anaconda3  (writable)
           channel URLs : https://conda.anaconda.org/r/win-64
                          https://conda.anaconda.org/r/noarch
                          https://conda.anaconda.org/anaconda-fusion/win-64
                          https://conda.anaconda.org/anaconda-fusion/noarch
                          https://repo.continuum.io/pkgs/main/win-64
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/win-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
          package cache : C:\Users\brandon9\AppData\Local\Continuum\Anaconda3\pkgs
                          C:\Users\brandon9\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\brandon9\AppData\Local\Continuum\Anaconda3\envs
                          C:\Users\brandon9\AppData\Local\conda\conda\envs
                          C:\Users\brandon9\.conda\envs
               platform : win-64
             user-agent : conda/4.4.8 requests/2.14.2 CPython/3.5.4 Windows/10 Windows/10.0.16299
          administrator : False
             netrc file : None
           offline mode : False
```

##### `conda list --show-channel-urls`

```
# packages in environment at C:\Users\brandon9\AppData\Local\Continuum\Anaconda3:
#
# Name                    Version                   Build  Channel
_license                  1.1                      py35_1    defaults
_nb_ext_conf              0.4.0                    py35_1    defaults
alabaster                 0.7.10           py35h3a808de_0    defaults
anaconda                  custom           py35h64770cb_0    defaults
anaconda-clean            1.1.0                    py35_0    defaults
anaconda-client           1.6.8                    py35_0    defaults
anaconda-navigator        1.6.12           py35hdad2993_0    defaults
anaconda-project          0.8.2            py35h06aeb26_0    defaults
arcgis                    1.2.1                    py35_1    esri
argcomplete               1.9.3                    py35_0    defaults
asn1crypto                0.24.0                   py35_0    defaults
astroid                   1.4.8                     <pip>
astroid                   1.6.0                    py35_0    defaults
astropy                   2.0.3            py35hfa6e2cd_0    defaults
attrs                     17.4.0                   py35_0    defaults
babel                     2.5.3                    py35_0    defaults
backports                 1.0              py35he88aa47_1    defaults
backports.shutil_get_terminal_size 1.0.0            py35h9d89c8b_2    defaults
beautifulsoup4            4.6.0            py35h61fcdcc_1    defaults
bitarray                  0.8.1            py35ha601307_0    defaults
blaze                     0.11.3           py35hae12140_0    defaults
bleach                    2.1.2                    py35_0    defaults
bokeh                     0.12.13          py35h047fa9f_0    defaults
boto                      2.48.0           py35ha0bef00_1    defaults
bottleneck                1.2.1            py35h8a3671c_0    defaults
bzip2                     1.0.6                haa5b126_2    defaults
ca-certificates           2017.08.26           h94faf87_0    defaults
certifi                   2018.1.18                py35_0    defaults
cffi                      1.11.4           py35hfa6e2cd_0    defaults
chardet                   3.0.4            py35h177e1b7_1    defaults
chest                     0.2.3                    py35_0    defaults
click                     6.7              py35h10df73f_0    defaults
cloudpickle               0.5.2            py35hd830302_0    defaults
clyent                    1.2.2            py35h3cd9751_1    defaults
colorama                  0.3.9            py35h32a752f_0    defaults
comtypes                  1.1.4                    py35_0    defaults
conda                     4.4.8                    py35_0    defaults
conda-build               3.3.0                    py35_0    defaults
conda-env                 2.6.0                h36134e3_1    defaults
conda-verify              2.0.0            py35h84a86bd_0    defaults
configobj                 5.0.6                    py35_0    defaults
console_shortcut          0.1.1                h6bb2dd7_3    defaults
contextlib2               0.5.5            py35h0a97e54_0    defaults
coverage                  4.4.2            py35h1d76e2e_0    defaults
cryptography              2.1.4            py35h8ead9e0_0    defaults
curl                      7.55.1               h3b839b5_4    defaults
cx-Freeze                 5.0.2                     <pip>
cycler                    0.10.0           py35hcc71164_0    defaults
cython                    0.27.3           py35h82876f0_0    defaults
cytoolz                   0.9.0            py35hfa6e2cd_0    defaults
dask                      0.16.1                   py35_0    defaults
dask-core                 0.16.1                   py35_0    defaults
datashape                 0.5.4            py35ha38994c_0    defaults
decorator                 4.2.1                    py35_0    defaults
dill                      0.2.7.1          py35hfe367cb_0    defaults
distributed               1.20.2                   py35_0    defaults
django                    1.11.8           py35hd476221_0    defaults
docutils                  0.14             py35h8ccb97f_0    defaults
dynd-python               0.7.2                    py35_0    defaults
entrypoints               0.2.3            py35hb91ced9_2    defaults
et_xmlfile                1.0.1            py35h2c13def_0    defaults
fastcache                 1.0.2            py35h8710e77_0    defaults
filelock                  2.0.13           py35hed8fc95_0    defaults
flask                     0.12.2           py35he898f9a_0    defaults
flask-cors                3.0.3            py35h5700fb0_0    defaults
freetype                  2.8                  h51f8f2c_1    defaults
get_terminal_size         1.0.0                h38e98db_0    defaults
gevent                    1.2.2            py35hb3d9581_0    defaults
glob2                     0.6              py35h9eb15d0_0    defaults
glue-core                 0.12.3           py35h8ad8396_0    defaults
glue-vispy-viewers        0.9              py35hcb157a0_0    defaults
greenlet                  0.4.12           py35h0b77e5a_0    defaults
h5py                      2.7.1            py35hb2c3add_0    defaults
hdf5                      1.10.1               h98b8871_1    defaults
heapdict                  1.0.0            py35h3d1311d_0    defaults
html5lib                  1.0.1            py35h047fa9f_0    defaults
hypothesis                3.38.5           py35h37a2ca4_0    defaults
icc_rt                    2017.0.4             h97af966_0    defaults
icu                       58.2                 ha66f8fd_1    defaults
idna                      2.6              py35h8dcb9ae_1    defaults
imageio                   2.2.0            py35hcd4b9a4_0    defaults
imagesize                 0.7.1            py35h7f87e83_0    defaults
imutils                   0.4.3                     <pip>
inflection                0.3.1                    py35_0    defaults
intel-openmp              2018.0.0             hd92c6cd_8    defaults
ipykernel                 4.8.0                    py35_0    defaults
ipython                   6.2.1            py35h4a2ac14_1    defaults
ipython_genutils          0.2.0            py35ha709e79_0    defaults
ipywidgets                7.1.0                    py35_0    defaults
isort                     4.2.15           py35h0bf7b49_0    defaults
isort                     4.2.5                     <pip>
itsdangerous              0.24             py35h99d45d4_1    defaults
jdcal                     1.3              py35h49a1460_0    defaults
jedi                      0.11.1                   py35_0    defaults
jinja2                    2.10             py35hdf652bb_0    defaults
jpeg                      9b                   hb83a4c4_2    defaults
jsonschema                2.6.0            py35h27d56d3_0    defaults
jupyter                   1.0.0            py35hce9caf1_2    defaults
jupyter_client            5.2.2                    py35_0    defaults
jupyter_console           5.2.0            py35hf76c22e_1    defaults
jupyter_core              4.4.0            py35h629ba7f_0    defaults
kerberos-sspi             0.2                      py35_0    defaults
lazy-object-proxy         1.3.1            py35he996729_0    defaults
lazy-object-proxy         1.2.2                     <pip>
libdynd                   0.7.2                         0    defaults
libiconv                  1.15                 h1df5818_7    defaults
libpng                    1.6.34               h79bbb47_0    defaults
libssh2                   1.8.0                hd619d38_4    defaults
libtiff                   4.0.9                h0f13578_0    defaults
libxml2                   2.9.7                h79bbb47_0    defaults
libxslt                   1.1.32               hf6f1972_0    defaults
llvmlite                  0.21.0           py35h255174b_0    defaults
locket                    0.2.0            py35h0dfcdd0_1    defaults
lxml                      4.1.1            py35hef2cd61_1    defaults
lzo                       2.10                 h6df0209_2    defaults
m2w64-bwidget             1.9.10                        2    defaults
m2w64-bzip2               1.0.6                         6    defaults
m2w64-c-ares              1.11.0                        2    defaults
m2w64-ca-certificates     20150426                    103    defaults
m2w64-curl                7.48.0                        2    defaults
m2w64-expat               2.1.1                         2    defaults
m2w64-fftw                3.3.4                         6    defaults
m2w64-flac                1.3.1                         3    defaults
m2w64-gcc-libgfortran     5.3.0                         6    defaults
m2w64-gcc-libs            5.3.0                         7    defaults
m2w64-gcc-libs-core       5.3.0                         7    defaults
m2w64-gettext             0.19.7                        2    defaults
m2w64-gmp                 6.1.0                         2    defaults
m2w64-gnutls              3.4.11                        2    defaults
m2w64-gsl                 2.1                           2    defaults
m2w64-jansson             2.7                           3    defaults
m2w64-libffi              3.2.1                         4    defaults
m2w64-libiconv            1.14                          6    defaults
m2w64-libidn              1.32                          4    defaults
m2w64-libjpeg-turbo       1.4.2                         3    defaults
m2w64-libmetalink         0.1.3                         2    defaults
m2w64-libogg              1.3.2                         3    defaults
m2w64-libpng              1.6.21                        2    defaults
m2w64-libsndfile          1.0.26                        2    defaults
m2w64-libssh2             1.7.0                         2    defaults
m2w64-libsystre           1.0.1                         3    defaults
m2w64-libtasn1            4.7                           2    defaults
m2w64-libtiff             4.0.6                         2    defaults
m2w64-libtre-git          122.c2f5d13                   5    defaults
m2w64-libvorbis           1.3.5                         2    defaults
m2w64-libwinpthread-git   5.0.0.4634.697f757               2    defaults
m2w64-libxml2             2.9.3                         4    defaults
m2w64-mpfr                3.1.4                         4    defaults
m2w64-nettle              3.1.1                         4    defaults
m2w64-nghttp2             1.9.2                         2    defaults
m2w64-nlopt               2.4.2                         3    defaults
m2w64-openssl             1.0.2.g                       2    defaults
m2w64-p11-kit             0.23.2                        2    defaults
m2w64-pcre                8.38                          2    defaults
m2w64-rtmpdump-git        499.a107cef                   4    defaults
m2w64-speex               1.2rc2                        3    defaults
m2w64-speexdsp            1.2rc3                        3    defaults
m2w64-tcl                 8.6.5                         3    defaults
m2w64-tk                  8.6.5                         3    defaults
m2w64-tktable             2.10                          5    defaults
m2w64-wineditline         2.101                         5    defaults
m2w64-xz                  5.2.2                         2    defaults
m2w64-zlib                1.2.8                        10    defaults
markupsafe                1.0              py35hc253e08_1    defaults
matplotlib                2.1.2            py35h016c42a_0    defaults
mccabe                    0.5.2                     <pip>
mccabe                    0.6.1            py35hcf31250_1    defaults
menuinst                  1.4.10           py35hb57c5a5_0    defaults
mistune                   0.8.3                    py35_0    defaults
mkl                       2018.0.1             h2108138_4    defaults
mkl-service               1.1.2            py35h051acba_4    defaults
more-itertools            3.2.0                    py35_0    defaults
mpmath                    1.0.0            py35h253b693_2    defaults
msgpack-python            0.5.1            py35he980bc4_0    defaults
msys2-conda-epoch         20160418                      1    defaults
multipledispatch          0.4.9            py35hfb38682_0    defaults
navigator-updater         0.1.0            py35h1d043e2_0    defaults
nb_anacondacloud          1.4.0                    py35_0    defaults
nb_conda                  2.2.0                    py35_0    defaults
nb_conda_kernels          2.1.0                    py35_0    defaults
nbconvert                 5.3.1            py35h98d6c46_0    defaults
nbformat                  4.4.0            py35h908c9d9_0    defaults
nbpresent                 3.0.2                    py35_0    defaults
networkx                  2.1                      py35_0    defaults
nltk                      3.2.5            py35hbbcff45_0    defaults
nose                      1.3.7            py35h0e9586c_2    defaults
notebook                  5.3.1                    py35_1    defaults
numba                     0.36.2          np113py35h15cbb59_0    defaults
numexpr                   2.6.4            py35hb78e28a_0    defaults
numpy                     1.13.3           py35h4a99626_2    defaults
numpy                     1.14.0                    <pip>
numpydoc                  0.7.0            py35h72ac4f2_0    defaults
odo                       0.5.1            py35hc850252_0    defaults
olefile                   0.44             py35h7ba86d0_0    defaults
opencv3                   3.1.0                    py35_0    menpo
openpyxl                  2.4.10                   py35_0    defaults
openssl                   1.0.2n               h74b6da3_0    defaults
packaging                 16.8             py35h5fb721f_1    defaults
pandas                    0.22.0           py35h6538335_0    defaults
pandoc                    1.19.2.1             hb2460c7_1    defaults
pandocfilters             1.4.2            py35h978f723_1    defaults
parso                     0.1.1            py35he39c48a_0    defaults
partd                     0.3.8            py35h894d1e4_0    defaults
path.py                   10.5             py35h3b5be1d_0    defaults
pathlib2                  2.3.0            py35h4f1e8f6_0    defaults
patsy                     0.5.0                    py35_0    defaults
pep8                      1.7.1                    py35_0    defaults
pickleshare               0.7.4            py35h2f9f535_0    defaults
pillow                    5.0.0            py35h0738816_0    defaults
pip                       9.0.1                     <pip>
pip                       9.0.1            py35h691316f_4    defaults
pkginfo                   1.4.1            py35hb922f74_1    defaults
plotly                    2.2.2            py35h85f5b52_0    defaults
pluggy                    0.6.0            py35h717ee57_0    defaults
ply                       3.10             py35hb60f152_0    defaults
praw                      4.4.0                     <pip>
prawcore                  0.8.0                     <pip>
prompt_toolkit            1.0.15           py35h89c7cb4_0    defaults
psutil                    5.0.0                     <pip>
psutil                    5.4.3            py35hfa6e2cd_0    defaults
py                        1.5.2            py35h4fcc378_0    defaults
pyasn1                    0.4.2            py35hd2f34a6_0    defaults
pycodestyle               2.3.1            py35h35694a3_0    defaults
pycosat                   0.6.3            py35h456c199_0    defaults
pycparser                 2.18             py35h15a15da_1    defaults
pycrypto                  2.6.1            py35h8890bb5_1    defaults
pycurl                    7.43.0.1         py35h74b6da3_0    defaults
pyflakes                  1.6.0            py35hb7fdafe_0    defaults
pygments                  2.2.0            py35h24c0941_0    defaults
pylint                    1.8.1                    py35_0    defaults
pylint                    1.6.4                     <pip>
pympler                   0.5              py35h0fea292_0    defaults
pyodbc                    4.0.22           py35h6538335_0    defaults
pyopengl                  3.1.1a1             np113py35_0    defaults
pyopenssl                 17.5.0           py35h75c5b16_0    defaults
pyparsing                 2.2.0            py35hcabcaab_1    defaults
pyqt                      5.6.0            py35hd46907b_5    defaults
pyqtdeploy                1.3.2                     <pip>
pyreadline                2.1              py35h9d47d9c_1    defaults
pyserial                  3.4              py35he0af20a_0    defaults
pytables                  3.4.2            py35h9e98cc6_2    defaults
pytest                    3.3.2                    py35_0    defaults
python                    3.5.4               h1357f44_23    defaults
python-dateutil           2.6.1            py35h6b299a3_1    defaults
pytz                      2017.3           py35hb294b1a_0    defaults
pywavelets                0.5.2            py35h7c47ace_0    defaults
pywin32                   222              py35hfa6e2cd_0    defaults
pyyaml                    3.12             py35h4bf9689_1    defaults
pyzmq                     16.0.3           py35h1861011_0    defaults
pyzmq                     16.0.1                    <pip>
qt                        5.6.2           vc14h6f8c307_12  [vc14]  defaults
qtawesome                 0.4.4            py35h639d0ff_0    defaults
qtconsole                 4.3.1            py35hc47b0dd_0    defaults
qtpy                      1.3.1            py35h4918c39_0    defaults
quandl                    3.2.0            py35h7552786_0    defaults
r-assertthat              0.2.0            r342h01a9704_0    r
r-backports               1.1.1            r342h3217c2d_0    r
r-base                    3.4.2                hd3afeec_0    r
r-base64enc               0.1_3            r342hca0b27c_4    r
r-bh                      1.65.0_1         r342h2243e07_0    r
r-bindr                   0.1              r342ha70b456_0    r
r-bindrcpp                0.2              r342he0cf37b_0    r
r-bitops                  1.0_6            r342hc4cc12e_4    r
r-boot                    1.3_20           r342h834dc84_0    r
r-broom                   0.4.2            r342h779228a_0    r
r-car                     2.1_5            r342h639fb79_0    r
r-caret                   6.0_77           r342h4d06727_0    r
r-catools                 1.17.1           r342h7ba4ff6_4    r
r-cellranger              1.1.0            r342hfe96f31_0    r
r-class                   7.3_14           r342hd963038_4    r
r-cluster                 2.0.6            r342hb962b98_0    r
r-codetools               0.2_15           r342hd33aafb_0    r
r-colorspace              1.3_2            r342h7878913_0    r
r-crayon                  1.3.4            r342h1ecf080_0    r
r-curl                    3.0              r342h0c1ac88_0    r
r-cvst                    0.2_1            r342h586ffb9_0    r
r-data.table              1.10.4_1         r342h70f4df9_0    r
r-dbi                     0.7              r342h740eb65_0    r
r-ddalpha                 1.3.1            r342h8577c99_0    r
r-deoptimr                1.0_8            r342h8011e7d_0    r
r-dichromat               2.0_0            r342h5d3b908_4    r
r-digest                  0.6.12           r342h45c1662_0    r
r-dimred                  0.1.0            r342h0a0e87f_0    r
r-dplyr                   0.7.4            r342hebb6f2c_0    r
r-drr                     0.0.2            r342ha33e3d9_0    r
r-essentials              1.7.0            r342hac5c45a_0    r
r-evaluate                0.10.1           r342h6002382_0    r
r-forcats                 0.2.0            r342he8e709c_0    r
r-foreach                 1.4.3            r342h420b518_4    r
r-foreign                 0.8_69           r342h0be368e_0    r
r-formatr                 1.5              r342hde702e4_0    r
r-ggplot2                 2.2.1            r342h574d846_0    r
r-gistr                   0.4.0            r342hce11cbc_0    r
r-glmnet                  2.0_13           r342he225388_0    r
r-glue                    1.1.1            r342hf365760_0    r
r-gower                   0.1.2            r342h601ddb7_0    r
r-gtable                  0.2.0            r342h0306998_0    r
r-haven                   1.1.0            r342h87b6d74_0    r
r-hexbin                  1.27.1           r342ha59edbe_4    r
r-highr                   0.6              r342h46316e3_0    r
r-hms                     0.3              r342hbed9107_0    r
r-htmltools               0.3.6            r342h6f9dbde_0    r
r-htmlwidgets             0.9              r342h1de9d11_0    r
r-httpuv                  1.3.5            r342hef81ad5_0    r
r-httr                    1.3.1            r342h3d373e7_0    r
r-ipred                   0.9_6            r342h8b93065_0    r
r-irdisplay               0.4.4            r342h493ca25_0    r
r-irkernel                0.8.9            r342h34d04e9_0    r
r-iterators               1.0.8            r342hfe8643f_4    r
r-jsonlite                1.5              r342h56bb22a_0    r
r-kernlab                 0.9_25           r342hd9ee2fe_0    r
r-kernsmooth              2.23_15          r342h0a5b6a8_4    r
r-knitr                   1.17             r342h2aeaf5c_0    r
r-labeling                0.3              r342h1b22440_4    r
r-lattice                 0.20_35          r342h36ddd8c_0    r
r-lava                    1.5.1            r342h7bde0ec_0    r
r-lazyeval                0.2.0            r342ha7c403b_0    r
r-lme4                    1.1_14           r342h47686e8_0    r
r-lubridate               1.6.0            r342h66b6780_0    r
r-magrittr                1.5              r342h30e08dc_4    r
r-maps                    3.2.0            r342h7d5dd07_0    r
r-markdown                0.8              r342h43f5b0a_0    r
r-mass                    7.3_47           r342h1a97f4d_0    r
r-matrix                  1.2_11           r342hdfe9c5d_0    r
r-matrixmodels            0.4_1            r342h3349024_4    r
r-mgcv                    1.8_22           r342h5004514_0    r
r-mime                    0.5              r342h2177764_0    r
r-minqa                   1.2.4            r342h3f8afa1_4    r
r-mnormt                  1.5_5            r342h5769c91_0    r
r-modelmetrics            1.1.0            r342hc782412_0    r
r-modelr                  0.1.1            r342h2d61cf6_0    r
r-munsell                 0.4.3            r342h66c67b1_0    r
r-nlme                    3.1_131          r342h50b31b5_0    r
r-nloptr                  1.0.4            r342h11b934d_4    r
r-nnet                    7.3_12           r342h4e6eed8_0    r
r-numderiv                2016.8_1         r342hcd88280_0    r
r-openssl                 0.9.7            r342hd1bc1d3_0    r
r-pbdzmq                  0.2_6            r342h9ec97ee_0    r
r-pbkrtest                0.4_7            r342h0816e6b_0    r
r-pkgconfig               2.0.1            r342hee5d7c7_0    r
r-plogr                   0.1_1            r342h364fde6_0    r
r-plyr                    1.8.4            r342habc6609_0    r
r-prodlim                 1.6.1            r342h7fd35c7_0    r
r-pryr                    0.1.2            r342h2b00293_0    r
r-psych                   1.7.8            r342h3d42236_0    r
r-purrr                   0.2.3            r342h7fe2810_0    r
r-quantmod                0.4_11           r342h574fc0c_0    r
r-quantreg                5.33             r342hb2c0cc3_0    r
r-r6                      2.2.2            r342h65183d9_0    r
r-randomforest            4.6_12           r342he4bac99_4    r
r-rbokeh                  0.5.0            r342h499442e_0    r
r-rcolorbrewer            1.1_2            r342h6cb45cc_0    r
r-rcpp                    0.12.13          r342h3e881fa_0    r
r-rcppeigen               0.3.3.3.0        r342h588b0e8_0    r
r-rcpproll                0.2.2            r342h4c765f1_0    r
r-readr                   1.1.1            r342h37978c3_0    r
r-readxl                  1.0.0            r342hfc97dd6_0    r
r-recipes                 0.1.0            r342h383f9f7_0    r
r-recommended             3.4.2                h1751db4_0    r
r-rematch                 1.0.1            r342h69263cc_0    r
r-repr                    0.12.0           r342hf93323b_0    r
r-reshape2                1.4.2            r342h278f13d_0    r
r-rlang                   0.1.2            r342ha421a6b_0    r
r-rmarkdown               1.6              r342h086bd35_2    r
r-robustbase              0.92_7           r342h25ff28c_0    r
r-rpart                   4.1_11           r342h4e779ed_0    r
r-rprojroot               1.2              r342hf57ac4f_0    r
r-rvest                   0.3.2            r342h4286d12_0    r
r-scales                  0.5.0            r342h44e79eb_0    r
r-selectr                 0.3_1            r342h5756207_0    r
r-sfsmisc                 1.1_1            r342hc96e9a0_0    r
r-shiny                   1.0.5            r342h9740604_0    r
r-sourcetools             0.1.6            r342h7a12c6a_0    r
r-sparsem                 1.77             r342hae7522b_0    r
r-spatial                 7.3_11           r342h351adbe_4    r
r-stringi                 1.1.5            r342h12ab220_0    r
r-stringr                 1.2.0            r342h38b0a1e_0    r
r-survival                2.41_3           r342h0998d5e_0    r
r-tibble                  1.3.4            r342h4fd6444_0    r
r-tidyr                   0.7.1            r342h92303bf_0    r
r-tidyselect              0.2.2            r342h3ab1f0f_0    r
r-tidyverse               1.1.1            r342h3a97584_0    r
r-timedate                3012.100         r342h6b5be10_4    r
r-ttr                     0.23_2           r342haa282ee_0    r
r-uuid                    0.1_2            r342hb7f30ee_4    r
r-viridislite             0.2.0            r342hb3e2508_0    r
r-withr                   2.0.0            r342h26ea15c_0    r
r-xml2                    1.1.1            r342hb18e4cc_0    r
r-xtable                  1.8_2            r342h5f07e11_0    r
r-xts                     0.10_0           r342hae93010_4    r
r-yaml                    2.1.14           r342h209047d_0    r
r-zoo                     1.8_0            r342h7ed1f00_0    r
requests                  2.14.2                   py35_0    defaults
rope                      0.10.7           py35h5756fe0_0    defaults
ruamel_yaml               0.15.35          py35hfa6e2cd_1    defaults
scikit-image              0.13.1           py35hfa6e2cd_1    defaults
scikit-learn              0.19.1           py35h2037775_0    defaults
scipy                     1.0.0            py35h75710e8_0    defaults
seaborn                   0.8.1            py35hc73483e_0    defaults
send2trash                1.4.2                    py35_0    defaults
setuptools                38.4.0                   py35_0    defaults
simplegeneric             0.8.1            py35h6406082_0    defaults
singledispatch            3.4.0.3          py35h33f66b4_0    defaults
sip                       4.18.1           py35h01cbaa7_2    defaults
six                       1.11.0           py35hc1da2df_1    defaults
snowballstemmer           1.2.1            py35h4c55bfa_0    defaults
sockjs-tornado            1.0.3                    py35_0    defaults
sortedcollections         0.5.3            py35h4a7ff62_0    defaults
sortedcontainers          1.5.9                    py35_0    defaults
sphinx                    1.6.6                    py35_0    defaults
sphinxcontrib             1.0              py35h45f5ca3_1    defaults
sphinxcontrib-websupport  1.0.1            py35ha3690eb_1    defaults
spyder                    3.2.6                    py35_0    defaults
sqlalchemy                1.2.1            py35hfa6e2cd_0    defaults
sqlite                    3.21.0               h9d3ae62_2    defaults
statsmodels               0.8.0            py35hfa6034c_0    defaults
sympy                     1.1.1            py35ha5375ed_0    defaults
tblib                     1.3.2            py35hd2cf7e1_0    defaults
testpath                  0.3.1            py35h06cf69e_0    defaults
tk                        8.6.7                hcb92d03_3    defaults
toolz                     0.9.0                    py35_0    defaults
tornado                   4.5.3                    py35_0    defaults
tqdm                      4.19.4           py35h1d89acb_0    defaults
traitlets                 4.3.2            py35h09b975b_0    defaults
typing                    3.6.2            py35h37628ea_0    defaults
unicodecsv                0.14.1           py35h0d88516_0    defaults
update-checker            0.16                      <pip>
vc                        14                   h0510ff6_3    defaults
virtualenv                15.1.0                    <pip>
vs2015_runtime            14.0.25123                    3    defaults
wcwidth                   0.1.7            py35h6e80d8a_0    defaults
webencodings              0.5.1            py35h5d527fb_1    defaults
werkzeug                  0.14.1                   py35_0    defaults
wheel                     0.30.0           py35h38a90bc_1    defaults
widgetsnbextension        3.1.0                    py35_0    defaults
win_unicode_console       0.5              py35h56988b5_0    defaults
wincertstore              0.2              py35hfebbdb8_0    defaults
wrapt                     1.10.11          py35h54666f7_0    defaults
wrapt                     1.10.8                    <pip>
xlrd                      1.1.0            py35h22b952b_1    defaults
xlsxwriter                1.0.2            py35h6052a16_0    defaults
xlwings                   0.11.5                   py35_0    defaults
xlwt                      1.3.0            py35hd04410a_0    defaults
yaml                      0.1.7                hc54c509_2    defaults
zict                      0.1.3            py35hf5542e0_0    defaults
zlib                      1.2.11               h8395fce_2    defaults
zope                      1.0                      py35_0    defaults
zope.interface            4.4.3            py35h57d3274_0    defaults

```

**Comment by YuQilin123** [comment]
Maybe this is because you have two numpy? The one is installed in pip, the other is installed in Anaconda.

**Comment by haicen** [comment]
This was resolved on my end almost a year ago. I don't remember what the fix was. Forgot to close.

**Comment by haicen** [comment]
This was resolved on my end almost a year ago. I don't remember what the fix was. Forgot to close.
