### ISSUE TITLE
An Unexpected Error has Occurred on Navigator Start-up

### ISSUE THREAD

**Issue by nlieb7** [ContinuumIO/anaconda-issues#8363]
I was running Anaconda Navigator yesterday, and my computer froze when I booted up Jupyter Notebook. The only way I could unfreeze my computer was to hard power it off. Once it booted back up, I run Anaconda Navigator, it opens up two terminals and closes them like usual, and then the Anaconda icon pops up and says it is initializing. After around 30 seconds, this error pops up: 'byte indices must be integers or slices, not str'

Here is the traceback:

Traceback (most recent call last):
  File "C:\Users\Nick Lobe\Anaconda3\lib\site-packages\anaconda_navigator\exceptions.py", line 75, in exception_handler
    return_value = func(*args, **kwargs)
  File "C:\Users\Nick Lobe\Anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 120, in start_app
    window = run_app(splash)
  File "C:\Users\Nick Lobe\Anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 63, in run_app
    window = MainWindow(splash=splash)
  File "C:\Users\Nick Lobe\Anaconda3\lib\site-packages\anaconda_navigator\widgets\main_window.py", line 161, in __init__
    self.api = AnacondaAPI()
  File "C:\Users\Nick Lobe\Anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 1258, in AnacondaAPI
    ANACONDA_API = _AnacondaAPI()
  File "C:\Users\Nick Lobe\Anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 70, in __init__
    self._conda_api = CondaAPI()
  File "C:\Users\Nick Lobe\Anaconda3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 1654, in CondaAPI
    CONDA_API = _CondaAPI()
  File "C:\Users\Nick Lobe\Anaconda3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 345, in __init__
    self.set_conda_prefix()
  File "C:\Users\Nick Lobe\Anaconda3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 494, in set_conda_prefix
    self.ROOT_PREFIX = info['root_prefix']
TypeError: byte indices must be integers or slices, not str

I have Anaconda3 (64-bit).

I am running it on Windows 10.

I also cannot seem to use the Anaconda Prompt, as it says things like 'conda' are not recognized. 

Any help would be greatly appreciated!

**Comment by goanpeca** [comment]
@nlieb7 , the space in your username is likely the cause of the issues please
