### ISSUE TITLE
All of the sudden I cannot open jupyter lab using CLI or Anaconda launch app.   

### ISSUE THREAD

**Issue by datadunce** [ContinuumIO/anaconda-issues#8382]
## Main error
Application <b>jupyterlab</b> launch may have produced errors.
## Traceback
```
Traceback (most recent call last):
  File "/Users/WilliamWright/anaconda/bin/jupyter-lab", line 7, in <module>
    from jupyterlab.labapp import main
  File "/Users/WilliamWright/anaconda/lib/python3.6/site-packages/jupyterlab/labapp.py", line 7, in <module>
    from notebook.notebookapp import NotebookApp, aliases, flags
  File "/Users/WilliamWright/anaconda/lib/python3.6/site-packages/notebook/__init__.py", line 25, in <module>
    from .nbextensions import install_nbextension
  File "/Users/WilliamWright/anaconda/lib/python3.6/site-packages/notebook/nbextensions.py", line 27, in <module>
    from jupyter_core.utils import ensure_dir_exists
ImportError: cannot import name 'ensure_dir_exists'

```
## System information
```
python: 3.6.3
language: en
os: Darwin;17.2.0;Darwin Kernel Version 17.2.0: Fri Sep 29 18:27:05 PDT 2017; root:xnu-4570.20.62~3/RELEASE_X86_64;x86_64;i386
version: 1.6.2
platform: osx-64
qt: 5.6.2
pyqt: 5.6.0
conda: 4.4.4
```

**Comment by datadunce** [comment]
I fixed problem by updated jupyter_core

**Comment by datadunce** [comment]
Found some help online, updating jupyter_core fixed issue
