### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by atii00** [ContinuumIO/anaconda-issues#8399]
## Main error
Application <b>notebook</b> launch may have produced errors.
## Traceback
```
[I 12:26:22.470 NotebookApp] The port 8888 is already in use, trying another port.
[I 12:26:22.471 NotebookApp] The port 8889 is already in use, trying another port.
[I 12:26:22.472 NotebookApp] The port 8890 is already in use, trying another port.
[I 12:26:22.474 NotebookApp] The port 8891 is already in use, trying another port.
[W 12:26:22.480 NotebookApp] Error loading server extension jupyter_nbextensions_configurator
    Traceback (most recent call last):
      File "C:\app\Anaconda3\lib\site-packages\notebook\notebookapp.py", line 1271, in init_server_extensions
        mod = importlib.import_module(modulename)
      File "C:\app\Anaconda3\lib\importlib\__init__.py", line 126, in import_module
        return _bootstrap._gcd_import(name[level:], package, level)
      File "<frozen importlib._bootstrap>", line 978, in _gcd_import
      File "<frozen importlib._bootstrap>", line 961, in _find_and_load
      File "<frozen importlib._bootstrap>", line 948, in _find_and_load_unlocked
    ModuleNotFoundError: No module named 'jupyter_nbextensions_configurator'
[I 12:26:22.764 NotebookApp] Serving notebooks from local directory: c:\Operation\My\lstm
[I 12:26:22.764 NotebookApp] 0 active kernels 
[I 12:26:22.764 NotebookApp] The Jupyter Notebook is running at: http://localhost:8892/?token=442a94041e693faabb27c35f054e7dca41eec650cff4ea97
[I 12:26:22.764 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 12:26:22.766 NotebookApp] 
    
    Copy/paste this URL into your browser when you connect for the f

**Comment by goanpeca** [comment]
Please run

```
conda upgrade jupyter_core
```
