### ISSUE TITLE
orange3 should have a dependency on joblib

### ISSUE THREAD

**Issue by SergiyKolesnikov** [ContinuumIO/anaconda-issues#842]
After installing **orange3 3.3.1 py35_0** package I ran **orange-canvas** from the command line and got the following exception:

```
Could not load 'Orange Widgets = Orange.widgets' (unsatisfied dependencies).
Traceback (most recent call last):
  File "/anaconda3/lib/python3.5/site-packages/Orange/canvas/registry/discovery.py", line 89, in run
    point = entry_point.load()
  File "/anaconda3/lib/python3.5/site-packages/setuptools-23.0.0-py3.5.egg/pkg_resources/__init__.py", line 2228, in load
    self.require(*args, **kwargs)
  File "/anaconda3/lib/python3.5/site-packages/setuptools-23.0.0-py3.5.egg/pkg_resources/__init__.py", line 2245, in require
    items = working_set.resolve(reqs, env, installer)
  File "/anaconda3/lib/python3.5/site-packages/setuptools-23.0.0-py3.5.egg/pkg_resources/__init__.py", line 829, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'joblib' distribution was not found and is required by the application
```

The tutorials in Orange also did not work.

After installing **joblib 0.9.4 py35_0** everything works perfectly, therefore orange3 should depend on joblib.

**Comment by nehaljwani** [comment]
Conda package orange3 >= `3.3.6` has the dependency on `joblib`. `conda update orange3` should fix this for you. Please reopen this issue if you want the dependency to be added to orange3 < `3.3.6` as well.
