### ISSUE TITLE
Anaconda Navigator not opening (following update)

### ISSUE THREAD

**Issue by craw-daddy** [ContinuumIO/anaconda-issues#8420]
### Actual Behavior

Following attempted launch of Anaconda Navigator, I get this response in a web browser window.

(The browser window address bar shows this:  file:///var/folders/v2/8l_3l2w53mv04l95l6w6k9wc0000gn/T/tmph3l3mb37.html)

Navigator Error

An unexpected error occurred on Navigator start-up
Report

Please report this issue in the anaconda issue tracker
Main Error

could not determine a constructor for the tag 'tag:yaml.org,2002:python/unicode'
  in "/Users/martin/Library/Application Support/binstar/config.yaml", line 1, column 1

Traceback

Traceback (most recent call last):
  File "/Anaconda/anaconda3/lib/python3.6/site-packages/anaconda_navigator/exceptions.py", line 75, in exception_handler
    return_value = func(*args, **kwargs)
  File "/Anaconda/anaconda3/lib/python3.6/site-packages/anaconda_navigator/app/start.py", line 120, in start_app
    window = run_app(splash)
  File "/Anaconda/anaconda3/lib/python3.6/site-packages/anaconda_navigator/app/start.py", line 63, in run_app
    window = MainWindow(splash=splash)
  File "/Anaconda/anaconda3/lib/python3.6/site-packages/anaconda_navigator/widgets/main_window.py", line 162, in __init__
    self.api = AnacondaAPI()
  File "/Anaconda/anaconda3/lib/python3.6/site-packages/anaconda_navigator/api/anaconda_api.py", line 1270, in AnacondaAPI
    ANACONDA_API = _AnacondaAPI()
  File "/Anaconda/anaconda3/lib/python3.6/site-packages/anaconda_navigator/api/anaconda_api.py", line 72, in __init__
    self._client_api = ClientAPI()
  File "/Anaconda/anaconda3/lib/python3.6/site-packages/anaconda_navigator/api/client_api.py", line 612, in ClientAPI
    CLIENT_API = _ClientAPI()
  File "/Anaconda/anaconda3/lib/python3.6/site-packages/anaconda_navigator/api/client_api.py", line 82, in __init__
    log_level=logging.NOTSET
  File "/Anaconda/anaconda3/lib/python3.6/site-packages/binstar_client/utils/config.py", line 96, in get_server_api
    config = get_config(remote_site=site)
  File "/Anaconda/anaconda3/lib/python3.6/site-packages/binstar_client/utils/config.py", line 229, in get_config
    file_configs = load_file_configs(SEARCH_PATH)
  File "/Anaconda/anaconda3/lib/python3.6/site-packages/binstar_client/utils/config.py", line 223, in load_file_configs
    raw_data = collections.OrderedDict(kv for kv in itertools.chain.from_iterable(load_paths))
  File "/Anaconda/anaconda3/lib/python3.6/site-packages/binstar_client/utils/config.py", line 223, in 
    raw_data = collections.OrderedDict(kv for kv in itertools.chain.from_iterable(load_paths))
  File "/Anaconda/anaconda3/lib/python3.6/site-packages/binstar_client/utils/config.py", line 203, in _dir_yaml_loader
    yield filepath, load_config(filepath)
  File "/Anaconda/anaconda3/lib/python3.6/site-packages/binstar_client/utils/config.py", line 187, in load_config
    data = yaml_load(fd)
  File "/Anaconda/anaconda3/lib/python3.6/site-packages/binstar_client/utils/yaml.py", line 9, in yaml_load
    return safe_load(stream)
  File "/Anaconda/anaconda3/lib/python3.6/site-packages/yaml/__init__.py", line 94, in safe_load
    return load(stream, SafeLoader)
  File "/Anaconda/anaconda3/lib/python3.6/site-packages/yaml/__init__.py", line 72, in load
    return loader.get_single_data()
  File "/Anaconda/anaconda3/lib/python3.6/site-packages/yaml/constructor.py", line 37, in get_single_data
    return self.construct_document(node)
  File "/Anaconda/anaconda3/lib/python3.6/site-packages/yaml/constructor.py", line 46, in construct_document
    for dummy in generator:
  File "/Anaconda/anaconda3/lib/python3.6/site-packages/yaml/constructor.py", line 398, in construct_yaml_map
    value = self.construct_mapping(node)
  File "/Anaconda/anaconda3/lib/python3.6/site-packages/yaml/constructor.py", line 204, in construct_mapping
    return super().construct_mapping(node, deep=deep)
  File "/Anaconda/anaconda3/lib/python3.6/site-packages/yaml/constructor.py", line 125, in construct_mapping
    key = self.construct_object(key_node, deep=deep)
  File "/Anaconda/anaconda3/lib/python3.6/site-packages/yaml/constructor.py", line 86, in construct_object
    data = constructor(self, node)
  File "/Anaconda/anaconda3/lib/python3.6/site-packages/yaml/constructor.py", line 414, in construct_undefined
    node.start_mark)
yaml.constructor.ConstructorError: could not determine a constructor for the tag 'tag:yaml.org,2002:python/unicode'
  in "/Users/martin/Library/Application Support/binstar/config.yaml", line 1, column 1

### Expected Behavior

Clearly in this case, I'm expecting the Navigator to start as normal.  ;)  

##### Anaconda or Miniconda version:

conda 4.4.8

##### Operating System:

OS X El Capitan (10.11.6)

##### `conda info`
```
     active environment : None
       user config file : /Users/martin/.condarc
 populated config files : /Users/martin/.condarc
          conda version : 4.4.8
    conda-build version : 3.4.0
         python version : 3.6.4.final.0
       base environment : /Anaconda/anaconda3  (writable)
           channel URLs : https://repo.continuum.io/pkgs/main/osx-64
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/osx-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/osx-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/osx-64
                          https://repo.continuum.io/pkgs/pro/noarch
          package cache : /Anaconda/anaconda3/pkgs
                          /Users/martin/.conda/pkgs
       envs directories : /Anaconda/anaconda3/envs
                          /Users/martin/.conda/envs
               platform : osx-64
             user-agent : conda/4.4.8 requests/2.18.4 CPython/3.6.4 Darwin/15.6.0 OSX/10.11.6
                UID:GID : 501:20
             netrc file : None
           offline mode : False
```

##### `conda list --show-channel-urls`
```
# packages in environment at /Anaconda/anaconda3:
#
# Name                    Version                   Build  Channel
_ipyw_jlab_nb_ext_conf    0.1.0            py36h2fc01ae_0    defaults
alabaster                 0.7.10           py36h174008c_0    defaults
anaconda                  custom           py36ha4fed55_0    defaults
anaconda-client           1.6.9                    py36_0    defaults
anaconda-navigator        1.6.12                   py36_0    defaults
anaconda-project          0.8.2            py36h9ee5d53_0    defaults
anyqt                     0.0.8                    py36_0    defaults
appdirs                   1.4.3                    py36_0    defaults
appnope                   0.1.0            py36hf537a9a_0    defaults
appscript                 1.0.1            py36h9e71e49_1    defaults
asn1crypto                0.24.0                   py36_0    defaults
astroid                   1.6.1                    py36_0    defaults
astropy                   2.0.3            py36h1de35cc_0    defaults
attrs                     17.4.0                   py36_0    defaults
automat                   0.6.0            py36hda01bcc_0    defaults
babel                     2.5.3                    py36_0    defaults
backports                 1.0              py36ha3c1827_1    defaults
backports.shutil_get_terminal_size 1.0.0            py36hd7a2ee4_2    defaults
beautifulsoup4            4.6.0            py36h72d3c9f_1    defaults
bitarray                  0.8.1            py36h20fa61d_0    defaults
bkcharts                  0.2              py36h073222e_0    defaults
blaze                     0.11.3           py36h02e7a37_0    defaults
bleach                    2.1.2                    py36_0    defaults
bokeh                     0.12.13          py36h2f9c1c0_0    defaults
boto                      2.48.0           py36hdbc59ac_1    defaults
bottleneck                1.2.1            py36hbd380ad_0    defaults
ca-certificates           2017.08.26           ha1e5d58_0    defaults
certifi                   2018.1.18                py36_0    defaults
cffi                      1.11.4           py36h342bebf_0    defaults
chardet                   3.0.4            py36h96c241c_1    defaults
click                     6.7              py36hec950be_0    defaults
cloudpickle               0.5.2            py36h379c7bd_0    defaults
clyent                    1.2.2            py36hae3ad88_0    defaults
colorama                  0.3.9            py36hd29a30c_0    defaults
conda                     4.4.8                    py36_0    defaults
conda-build               3.4.0                    py36_0    defaults
conda-env                 2.6.0                h36134e3_0    defaults
conda-verify              2.0.0            py36he837df3_0    defaults
constantly                15.1.0                   py36_0    defaults
contextlib2               0.5.5            py36hd66e5e7_0    defaults
coverage                  4.4.2            py36h8d5022f_0    defaults
cryptography              2.1.4            py36h842514c_0    defaults
cssselect                 1.0.3                    py36_0    defaults
curl                      7.58.0               ha441bb4_0    defaults
cycler                    0.10.0           py36hfc81398_0    defaults
cython                    0.27.3           py36h6ecb376_0    defaults
cytoolz                   0.9.0            py36h1de35cc_0    defaults
dask                      0.16.1                   py36_0    defaults
dask-core                 0.16.1                   py36_0    defaults
datashape                 0.5.4            py36hfb22df8_0    defaults
dbus                      1.12.2               haa0f8f7_0    defaults
decorator                 4.2.1                    py36_0    defaults
dill                      0.2.7.1          py36hdf89ffe_0    defaults
distributed               1.20.2                   py36_0    defaults
docutils                  0.14             py36hbfde631_0    defaults
entrypoints               0.2.3            py36hd81d71f_2    defaults
et_xmlfile                1.0.1            py36h1315bdc_0    defaults
expat                     2.2.5                hb8e80ba_0    defaults
fastcache                 1.0.2            py36h8606a76_0    defaults
filelock                  2.0.13           py36hf9de95b_0    defaults
flask                     0.12.2           py36h5658096_0    defaults
flask-cors                3.0.3            py36h7387b97_0    defaults
freetype                  2.8                  h143eb01_0    defaults
get_terminal_size         1.0.0                h7520d66_0    defaults
gettext                   0.19.8.1             hb0f4f8b_2    defaults
gevent                    1.2.2            py36ha70b9d6_0    defaults
glib                      2.53.6               ha08cb78_1    defaults
glob2                     0.6              py36h94c9186_0    defaults
glue-core                 0.12.3           py36hb64278a_0    defaults
glue-vispy-viewers        0.9              py36h1e4d04d_0    defaults
glueviz                   0.12.0               ha37a3ef_0    defaults
gmp                       6.1.2                h4a9834d_0    defaults
gmpy2                     2.0.8            py36h7ef02cb_1    defaults
greenlet                  0.4.12           py36hf09ba7b_0    defaults
h5py                      2.7.1            py36h39cdac5_0    defaults
hdf5                      1.10.1               h6090a45_0    defaults
heapdict                  1.0.0            py36h27a9ac6_0    defaults
html5lib                  1.0.1            py36h2f9c1c0_0    defaults
hyperlink                 17.1.1                   py36_0    defaults
hypothesis                3.38.5           py36hcba0581_0    defaults
icu                       58.2                 hea21ae5_0    defaults
idna                      2.6              py36h8628d0a_1    defaults
imageio                   2.2.0            py36h5e01289_0    defaults
imagesize                 0.7.1            py36h3495948_0    defaults
incremental               17.5.0           py36h8704290_0    defaults
inflection                0.3.1                    py36_0    defaults
intel-openmp              2018.0.0             hdd0ccc9_7    defaults
ipykernel                 4.8.0                    py36_0    defaults
ipython                   6.2.1            py36h3dda519_1    defaults
ipython_genutils          0.2.0            py36h241746c_0    defaults
ipywidgets                7.1.1                    py36_0    defaults
isort                     4.2.15           py36hceb2a01_0    defaults
itsdangerous              0.24             py36h49fbb8d_1    defaults
jbig                      2.1                  h4d881f8_0    defaults
jdcal                     1.3              py36h1986823_0    defaults
jedi                      0.11.1                   py36_0    defaults
jinja2                    2.10             py36hd36f9c5_0    defaults
joblib                    0.11                     py36_0    defaults
jpeg                      9b                   haccd157_1    defaults
jsonschema                2.6.0            py36hb385e00_0    defaults
jupyter                   1.0.0            py36h598a6cc_0    defaults
jupyter_client            5.2.2                    py36_0    defaults
jupyter_console           5.2.0            py36hccf5b1c_1    defaults
jupyter_core              4.4.0            py36h79cf704_0    defaults
jupyterlab                0.31.2                   py36_0    defaults
jupyterlab_launcher       0.10.2                   py36_0    defaults
keyring                   10.5.0           py36ha5eb305_0    defaults
lazy-object-proxy         1.3.1            py36h2fbbe47_0    defaults
libcurl                   7.58.0               hf30b1f0_0    defaults
libcxx                    4.0.1                h579ed51_0    defaults
libcxxabi                 4.0.1                hebd6815_0    defaults
libedit                   3.1                  hb4e282d_0    defaults
libffi                    3.2.1                hd939716_3    defaults
libgfortran               3.0.1                h93005f0_2    defaults
libiconv                  1.15                 h99df5da_5    defaults
libpng                    1.6.34               he12f830_0    defaults
libsodium                 1.0.15               hd9e47c5_0    defaults
libssh2                   1.8.0                h1218725_2    defaults
libtiff                   4.0.9                h0dac147_0    defaults
libxml2                   2.9.7                hab757c2_0    defaults
libxslt                   1.1.32               hb819dd2_0    defaults
llvmlite                  0.21.0           py36hff739e7_0    defaults
locket                    0.2.0            py36hca03003_1    defaults
lxml                      4.1.1            py36h6c891f4_0    defaults
markupsafe                1.0              py36h3a1e703_1    defaults
matplotlib                2.1.2            py36h6d6146d_0    defaults
mccabe                    0.6.1            py36hdaeb55d_0    defaults
mistune                   0.8.3                    py36_0    defaults
mkl                       2018.0.1             hfbd8650_4    defaults
mkl-service               1.1.2            py36h7ea6df4_4    defaults
more-itertools            3.2.0                    py36_0    defaults
mpc                       1.0.3                hc455b36_4    defaults
mpfr                      3.1.5                h7fa3772_1    defaults
mpmath                    1.0.0            py36hf1b8295_2    defaults
msgpack-python            0.5.1            py36h04f5b5a_0    defaults
multipledispatch          0.4.9            py36hc5f92b5_0    defaults
navigator-updater         0.1.0            py36h7aee5fb_0    defaults
nbconvert                 5.3.1            py36h810822e_0    defaults
nbformat                  4.4.0            py36h827af21_0    defaults
ncurses                   6.0                  ha932d30_1    defaults
networkx                  2.1                      py36_0    defaults
nltk                      3.2.5            py36h1190bce_0    defaults
nose                      1.3.7            py36h73fae2b_2    defaults
notebook                  5.3.1                    py36_2    defaults
numba                     0.36.2          np113py36hceb9f0c_0    defaults
numexpr                   2.6.4            py36habcfcfe_0    defaults
numpy                     1.13.3           py36h2cdce51_0    defaults
numpydoc                  0.7.0            py36he54d08e_0    defaults
odo                       0.5.1            py36hc1af34a_0    defaults
olefile                   0.45.1                   py36_0    defaults
openpyxl                  2.4.10                   py36_0    defaults
openssl                   1.0.2n               hdbc3d79_0    defaults
orange3                   3.4.1                    py36_0    defaults
packaging                 16.8             py36he5e8135_0    defaults
pandas                    0.22.0           py36h0a44026_0    defaults
pandasql                  0.7.3                    py36_0    defaults
pandoc                    1.19.2.1             ha5e8f32_1    defaults
pandocfilters             1.4.2            py36h3b0b094_1    defaults
parsel                    1.2.0                    py36_0    defaults
parso                     0.1.1            py36hc90e01c_0    defaults
partd                     0.3.8            py36hf5c4cb8_0    defaults
path.py                   10.5             py36h7bcb313_0    defaults
pathlib2                  2.3.0            py36h877a6d8_0    defaults
patsy                     0.5.0                    py36_0    defaults
pcre                      8.41                 h29eefc5_0    defaults
pep8                      1.7.1                    py36_0    defaults
pexpect                   4.3.1                    py36_0    defaults
pickleshare               0.7.4            py36hf512f8e_0    defaults
pillow                    5.0.0            py36hfcce615_0    defaults
pip                       9.0.1            py36hbbb9e21_2    defaults
pkginfo                   1.4.1            py36h25bf955_0    defaults
plotly                    2.2.2            py36h097dc49_0    defaults
pluggy                    0.6.0            py36hb1d0581_0    defaults
ply                       3.10             py36h10e714e_0    defaults
prompt_toolkit            1.0.15           py36haeda067_0    defaults
psutil                    5.4.3            py36h1de35cc_0    defaults
PTable                    0.9.2                     <pip>
ptyprocess                0.5.2            py36he6521c3_0    defaults
py                        1.5.2            py36ha69170d_0    defaults
pyasn1                    0.4.2            py36h62a34ed_0    defaults
pyasn1-modules            0.2.1            py36h1776605_0    defaults
pycodestyle               2.3.1            py36h83e8646_0    defaults
pycosat                   0.6.3            py36hee92d8f_0    defaults
pycparser                 2.18             py36h724b2fc_1    defaults
pycrypto                  2.6.1            py36h72f2894_1    defaults
pycurl                    7.43.0.1         py36hdbc3d79_0    defaults
pydispatcher              2.0.5                    py36_0    defaults
pyflakes                  1.6.0            py36hea45e83_0    defaults
pygments                  2.2.0            py36h240cd3f_0    defaults
pylint                    1.8.2                    py36_0    defaults
pympler                   0.5              py36hc2752d1_0    defaults
pyodbc                    4.0.22           py36h0a44026_0    defaults
pyopengl                  3.1.1a1             np113py36_0    defaults
pyopenssl                 17.5.0           py36h51e4350_0    defaults
pyparsing                 2.2.0            py36hb281f35_0    defaults
pyqt                      5.6.0            py36he5c6137_6    defaults
pyqtgraph                 0.10.0                   py36_0    defaults
pysocks                   1.6.7            py36hfa33cec_1    defaults
pytables                  3.4.2            py36h6e7b07d_1    defaults
pytest                    3.3.2                    py36_0    defaults
python                    3.6.4                hc167b69_1    defaults
python-dateutil           2.6.1            py36h86d2abb_1    defaults
python.app                2                py36h54569d5_7    defaults
pytz                      2017.3           py36hf0bf824_0    defaults
pywavelets                0.5.2            py36h2710a04_0    defaults
pyyaml                    3.12             py36h2ba1e63_1    defaults
pyzmq                     16.0.3           py36he48b5ad_0    defaults
qt                        5.6.2               h9975529_14    defaults
qtawesome                 0.4.4            py36h468c6fb_0    defaults
qtconsole                 4.3.1            py36hd96c0ff_0    defaults
qtpy                      1.3.1            py36h16bb863_0    defaults
queuelib                  1.4.2                    py36_0    defaults
readline                  7.0                  h81b24a6_3    defaults
requests                  2.18.4           py36h4516966_1    defaults
rope                      0.10.7           py36h68959ac_0    defaults
ruamel_yaml               0.15.35          py36h1de35cc_1    defaults
scikit-image              0.13.1           py36h1de35cc_1    defaults
scikit-learn              0.19.1           py36hffbff8c_0    defaults
scipy                     1.0.0            py36h1de22e9_0    defaults
scrapy                    1.4.0            py36h04ddb06_1    defaults
seaborn                   0.8.1            py36h595ecd9_0    defaults
send2trash                1.4.2                    py36_0    defaults
service_identity          17.0.0                   py36_0    defaults
setuptools                38.4.0                   py36_0    defaults
simplegeneric             0.8.1            py36he5b5b09_0    defaults
singledispatch            3.4.0.3          py36hf20db9d_0    defaults
sip                       4.18.1           py36h2824476_2    defaults
six                       1.11.0           py36h0e22d5e_1    defaults
snowballstemmer           1.2.1            py36h6c7b616_0    defaults
sortedcollections         0.5.3            py36he9c3ed6_0    defaults
sortedcontainers          1.5.9                    py36_0    defaults
sphinx                    1.6.6                    py36_0    defaults
sphinxcontrib             1.0              py36h9364dc8_1    defaults
sphinxcontrib-websupport  1.0.1            py36h92f4a7a_1    defaults
spyder                    3.2.6                    py36_0    defaults
sqlalchemy                1.2.1            py36h1de35cc_0    defaults
sqlite                    3.22.0               h3efe00b_0    defaults
statsmodels               0.8.0            py36h9c68fc9_0    defaults
sympy                     1.1.1            py36h7f3cf04_0    defaults
tblib                     1.3.2            py36hda67792_0    defaults
terminado                 0.8.1                    py36_0    defaults
testpath                  0.3.1            py36h625a49b_0    defaults
tk                        8.6.7                hcdce994_1    defaults
toolz                     0.9.0                    py36_0    defaults
tornado                   4.5.3                    py36_0    defaults
traitlets                 4.3.2            py36h65bd3ce_0    defaults
twisted                   17.9.0           py36h1a7ef6d_0    defaults
twitter                   1.17.1                    <pip>
typing                    3.6.2            py36haa2d9ef_0    defaults
unicodecsv                0.14.1           py36he531d66_0    defaults
unixodbc                  2.3.4                h4cb4dde_1    defaults
urllib3                   1.22             py36h68b9469_0    defaults
w3lib                     1.18.0           py36h63be7f5_0    defaults
wcwidth                   0.1.7            py36h8c6ec74_0    defaults
webencodings              0.5.1            py36h3b9701d_1    defaults
werkzeug                  0.14.1                   py36_0    defaults
wheel                     0.30.0           py36h5eb2c71_1    defaults
widgetsnbextension        3.1.0                    py36_0    defaults
wrapt                     1.10.11          py36hc29e774_0    defaults
xlrd                      1.1.0            py36h336f4a2_1    defaults
xlsxwriter                1.0.2            py36h3736301_0    defaults
xlwings                   0.11.5                   py36_0    defaults
xlwt                      1.3.0                    py36_0    defaults
xz                        5.2.3                ha24016e_1    defaults
yaml                      0.1.7                hff548bb_1    defaults
zeromq                    4.2.2                h131e0f7_1    defaults
zict                      0.1.3            py36h71da714_0    defaults
zlib                      1.2.11               h60db283_1    defaults
zope                      1.0                      py36_0    defaults
zope.interface            4.4.3            py36h74e83c9_0    defaults
```

**Comment by goanpeca** [comment]
Could you manually delete this file and try again?

`/Users/martin/Library/Application Support/binstar/config.yaml`

**Comment by craw-daddy** [comment]
Thanks!  That sorted the problem of Anaconda not starting!  

I did get this message when I restarted the kernel in a Jupyter notebook.  (I don't know if this is the proper place to mention this exception or not.  Mind you, the kernel did restart, but still output this in my terminal window in the background.)  

[E 17:00:37.761 NotebookApp] Exception restarting kernel
    Traceback (most recent call last):
      File "/Anaconda/anaconda3/lib/python3.6/site-packages/notebook/services/kernels/handlers.py", line 85, in post
        yield gen.maybe_future(km.restart_kernel(kernel_id))
      File "/Anaconda/anaconda3/lib/python3.6/site-packages/tornado/gen.py", line 1055, in run
        value = future.result()
      File "/Anaconda/anaconda3/lib/python3.6/site-packages/tornado/concurrent.py", line 238, in result
        raise_exc_info(self._exc_info)
      File "<string>", line 4, in raise_exc_info
    tornado.gen.TimeoutError: Timeout waiting for restart
[E 17:00:38.591 NotebookApp] {
      "Host": "localhost:8888",
      "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:57.0) Gecko/20100101 Firefox/57.0",
      "Accept": "application/json, text/javascript, */*; q=0.01",
      "Accept-Language": "en-US,en;q=0.5",
      "Accept-Encoding": "gzip, deflate",
      "Referer": "http://localhost:8888/notebooks/Codecademy-Data%20Analysis/Biodiversity/biodiversity.ipynb",
      "X-Xsrftoken": "2|f2f481da|9f3005620a6028797bb1ef4bf530dae9|1515535036",
      "X-Requested-With": "XMLHttpRequest",
      "Cookie": "username-localhost-8888=\"2|1:0|10:1517763324|23:username-localhost-8888|44:MzMyMDRjMGMxOTYxNGU2OTllNjA3ZDBiZGE3YWM1YTc=|21a2075d07b08872be9c8c7a553ad6f2419132a94b460899a7b4ebc9910b4750\"; _xsrf=2|f2f481da|9f3005620a6028797bb1ef4bf530dae9|1515535036",
      "Connection": "keep-alive",
      "Content-Length": "0"
    }
[E 17:00:38.591 NotebookApp] 500 POST /api/kernels/1fe8d9fe-9a8a-48cc-9e91-c47c473ed082/restart (::1) 35992.27ms referer=http://localhost:8888/notebooks/Codecademy-Data%20Analysis/Biodiversity/biodiversity.ipynb

**Comment by dgaultie** [comment]
Issue solve in deleting file config.yaml, and now works great. Thanks
