### ISSUE TITLE
An unexpected error occurred on Navigator start-up

### ISSUE THREAD

**Issue by 25shmeckles** [ContinuumIO/anaconda-issues#8422]
```
Navigator Error

An unexpected error occurred on Navigator start-up

Report

Please report this issue in the anaconda issue tracker

Main Error

could not determine a constructor for the tag 'tag:yaml.org,2002:python/unicode'
  in "/Users/alec/Library/Application Support/binstar/config.yaml", line 1, column 1
Traceback

Traceback (most recent call last):
  File "/Users/alec/anaconda/lib/python3.6/site-packages/anaconda_navigator/exceptions.py", line 75, in exception_handler
    return_value = func(*args, **kwargs)
  File "/Users/alec/anaconda/lib/python3.6/site-packages/anaconda_navigator/app/start.py", line 120, in start_app
    window = run_app(splash)
  File "/Users/alec/anaconda/lib/python3.6/site-packages/anaconda_navigator/app/start.py", line 63, in run_app
    window = MainWindow(splash=splash)
  File "/Users/alec/anaconda/lib/python3.6/site-packages/anaconda_navigator/widgets/main_window.py", line 162, in __init__
    self.api = AnacondaAPI()
  File "/Users/alec/anaconda/lib/python3.6/site-packages/anaconda_navigator/api/anaconda_api.py", line 1270, in AnacondaAPI
    ANACONDA_API = _AnacondaAPI()
  File "/Users/alec/anaconda/lib/python3.6/site-packages/anaconda_navigator/api/anaconda_api.py", line 72, in __init__
    self._client_api = ClientAPI()
  File "/Users/alec/anaconda/lib/python3.6/site-packages/anaconda_navigator/api/client_api.py", line 612, in ClientAPI
    CLIENT_API = _ClientAPI()
  File "/Users/alec/anaconda/lib/python3.6/site-packages/anaconda_navigator/api/client_api.py", line 82, in __init__
    log_level=logging.NOTSET
  File "/Users/alec/anaconda/lib/python3.6/site-packages/binstar_client/utils/config.py", line 96, in get_server_api
    config = get_config(remote_site=site)
  File "/Users/alec/anaconda/lib/python3.6/site-packages/binstar_client/utils/config.py", line 229, in get_config
    file_configs = load_file_configs(SEARCH_PATH)
  File "/Users/alec/anaconda/lib/python3.6/site-packages/binstar_client/utils/config.py", line 223, in load_file_configs
    raw_data = collections.OrderedDict(kv for kv in itertools.chain.from_iterable(load_paths))
  File "/Users/alec/anaconda/lib/python3.6/site-packages/binstar_client/utils/config.py", line 223, in 
    raw_data = collections.OrderedDict(kv for kv in itertools.chain.from_iterable(load_paths))
  File "/Users/alec/anaconda/lib/python3.6/site-packages/binstar_client/utils/config.py", line 203, in _dir_yaml_loader
    yield filepath, load_config(filepath)
  File "/Users/alec/anaconda/lib/python3.6/site-packages/binstar_client/utils/config.py", line 187, in load_config
    data = yaml_load(fd)
  File "/Users/alec/anaconda/lib/python3.6/site-packages/binstar_client/utils/yaml.py", line 9, in yaml_load
    return safe_load(stream)
  File "/Users/alec/anaconda/lib/python3.6/site-packages/yaml/__init__.py", line 94, in safe_load
    return load(stream, SafeLoader)
  File "/Users/alec/anaconda/lib/python3.6/site-packages/yaml/__init__.py", line 72, in load
    return loader.get_single_data()
  File "/Users/alec/anaconda/lib/python3.6/site-packages/yaml/constructor.py", line 37, in get_single_data
    return self.construct_document(node)
  File "/Users/alec/anaconda/lib/python3.6/site-packages/yaml/constructor.py", line 46, in construct_document
    for dummy in generator:
  File "/Users/alec/anaconda/lib/python3.6/site-packages/yaml/constructor.py", line 398, in construct_yaml_map
    value = self.construct_mapping(node)
  File "/Users/alec/anaconda/lib/python3.6/site-packages/yaml/constructor.py", line 204, in construct_mapping
    return super().construct_mapping(node, deep=deep)
  File "/Users/alec/anaconda/lib/python3.6/site-packages/yaml/constructor.py", line 125, in construct_mapping
    key = self.construct_object(key_node, deep=deep)
  File "/Users/alec/anaconda/lib/python3.6/site-packages/yaml/constructor.py", line 86, in construct_object
    data = constructor(self, node)
  File "/Users/alec/anaconda/lib/python3.6/site-packages/yaml/constructor.py", line 414, in construct_undefined
    node.start_mark)
yaml.constructor.ConstructorError: could not determine a constructor for the tag 'tag:yaml.org,2002:python/unicode'
  in "/Users/alec/Library/Application Support/binstar/config.yaml", line 1, column 1
```

##### Anaconda or Miniconda version:
conda 4.4.8

##### Operating System:
macOS 10.13.2

##### `conda info`

```
    active environment : None
       user config file : /Users/alec/.condarc
 populated config files : /Users/alec/.condarc
          conda version : 4.4.8
    conda-build version : not installed
         python version : 3.6.4.final.0
       base environment : /Users/alec/anaconda  (writable)
           channel URLs : https://repo.continuum.io/pkgs/main/osx-64
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/osx-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/osx-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/osx-64
                          https://repo.continuum.io/pkgs/pro/noarch
          package cache : /Users/alec/anaconda/pkgs
                          /Users/alec/.conda/pkgs
       envs directories : /Users/alec/anaconda/envs
                          /Users/alec/.conda/envs
               platform : osx-64
             user-agent : conda/4.4.8 requests/2.18.4 CPython/3.6.4 Darwin/17.3.0 OSX/10.13.2
                UID:GID : 501:20
             netrc file : None
           offline mode : False
```

##### `conda list --show-channel-urls`

```
# packages in environment at /Users/alec/anaconda:
#
# Name                    Version                   Build  Channel
_license                  1.1                      py36_1    defaults
alabaster                 0.7.10           py36h174008c_0    defaults
anaconda                  custom           py36ha4fed55_0    defaults
anaconda-client           1.6.9                    py36_0    defaults
anaconda-navigator        1.6.12                   py36_0    defaults
anaconda-project          0.8.2            py36h9ee5d53_0    defaults
appnope                   0.1.0            py36hf537a9a_0    defaults
appscript                 1.0.1            py36h9e71e49_1    defaults
asn1crypto                0.24.0                   py36_0    defaults
astroid                   1.6.1                    py36_0    defaults
astropy                   2.0.3            py36h1de35cc_0    defaults
attrs                     17.4.0                   py36_0    defaults
babel                     2.5.0            py36h9f161ff_0    defaults
backports                 1.0              py36ha3c1827_1    defaults
backports.shutil_get_terminal_size 1.0.0            py36hd7a2ee4_2    defaults
backports.weakref         1.0rc1                    <pip>
beautifulsoup4            4.6.0            py36h72d3c9f_1    defaults
bitarray                  0.8.1            py36h20fa61d_0    defaults
blaze                     0.11.3           py36h02e7a37_0    defaults
bleach                    2.1.1            py36h27c13d8_0    defaults
bokeh                     0.12.11          py36hf73f4a7_0    defaults
boto                      2.48.0           py36hdbc59ac_1    defaults
bottleneck                1.2.1            py36hbd380ad_0    defaults
bzip2                     1.0.6                h649919c_2    defaults
ca-certificates           2017.08.26           ha1e5d58_0    defaults
certifi                   2018.1.18                py36_0    defaults
cffi                      1.11.4           py36h342bebf_0    defaults
chardet                   3.0.4            py36h96c241c_1    defaults
click                     6.7              py36hec950be_0    defaults
cloudpickle               0.5.2            py36h379c7bd_0    defaults
clyent                    1.2.2            py36hae3ad88_0    defaults
colorama                  0.3.9            py36hd29a30c_0    defaults
conda                     4.4.8                    py36_0    defaults
conda-env                 2.6.0                h36134e3_0    defaults
contextlib2               0.5.5            py36hd66e5e7_0    defaults
coverage                  4.4.2            py36h8d5022f_0    defaults
cryptography              2.1.4            py36h842514c_0    defaults
curl                      7.55.1               h2e228d0_4    defaults
cycler                    0.10.0           py36hfc81398_0    defaults
cython                    0.27.3           py36h6ecb376_0    defaults
cytoolz                   0.8.2            py36h290905f_0    defaults
dask                      0.16.0           py36h40f4302_0    defaults
dask-core                 0.16.0           py36haa8de34_0    defaults
datashape                 0.5.4            py36hfb22df8_0    defaults
dbus                      1.12.2               haa0f8f7_0    defaults
decorator                 4.2.1                    py36_0    defaults
distributed               1.20.2                   py36_0    defaults
docutils                  0.14             py36hbfde631_0    defaults
entrypoints               0.2.3            py36hd81d71f_2    defaults
et_xmlfile                1.0.1            py36h1315bdc_0    defaults
expat                     2.2.5                hb8e80ba_0    defaults
fastcache                 1.0.2            py36h8606a76_0    defaults
flask                     0.12.2           py36h5658096_0    defaults
flask-cors                3.0.3            py36h7387b97_0    defaults
freetype                  2.8                  h12048fb_1    defaults
get_terminal_size         1.0.0                h7520d66_0    defaults
gettext                   0.19.8.1             h15daf44_3    defaults
gevent                    1.2.2            py36ha70b9d6_0    defaults
glib                      2.53.6               h33f6a65_2    defaults
gmp                       6.1.2                hb37e062_1    defaults
gmpy2                     2.0.8            py36hf9c35bd_2    defaults
greenlet                  0.4.12           py36hf09ba7b_0    defaults
h5py                      2.7.1            py36h39cdac5_0    defaults
hdf5                      1.10.1               ha036c08_1    defaults
heapdict                  1.0.0            py36h27a9ac6_0    defaults
html5lib                  0.9999999                 <pip>
html5lib                  0.999999999      py36h79312fd_0    defaults
hypothesis                3.38.5           py36hcba0581_0    defaults
icu                       58.2                 h4b95b61_1    defaults
idna                      2.6              py36h8628d0a_1    defaults
imageio                   2.2.0            py36h5e01289_0    defaults
imagesize                 0.7.1            py36h3495948_0    defaults
intel-openmp              2018.0.0             h8158457_8    defaults
ipykernel                 4.7.0            py36h2f9c1c0_0    defaults
ipython                   6.2.1            py36h3dda519_1    defaults
ipython_genutils          0.2.0            py36h241746c_0    defaults
ipywidgets                7.0.5            py36h5142716_0    defaults
isort                     4.2.15           py36hceb2a01_0    defaults
itsdangerous              0.24             py36h49fbb8d_1    defaults
jbig                      2.1                  h4d881f8_0    defaults
jdcal                     1.3              py36h1986823_0    defaults
jedi                      0.11.0                   py36_1    defaults
jinja2                    2.10             py36hd36f9c5_0    defaults
jpeg                      9b                   he5867d9_2    defaults
jsonschema                2.6.0            py36hb385e00_0    defaults
jupyter                   1.0.0            py36h598a6cc_0    defaults
jupyter_client            5.1.0            py36hf6c435f_0    defaults
jupyter_console           5.2.0            py36hccf5b1c_1    defaults
jupyter_core              4.4.0            py36h79cf704_0    defaults
lazy-object-proxy         1.3.1            py36h2fbbe47_0    defaults
libcxx                    4.0.1                h579ed51_0    defaults
libcxxabi                 4.0.1                hebd6815_0    defaults
libedit                   3.1                  hb4e282d_0    defaults
libffi                    3.2.1                h475c297_4    defaults
libgfortran               3.0.1                h93005f0_2    defaults
libiconv                  1.15                 hdd342a3_7    defaults
libpng                    1.6.34               he12f830_0    defaults
libsodium                 1.0.15               hd9e47c5_0    defaults
libssh2                   1.8.0                h9feafcd_3    defaults
libtiff                   4.0.9                h0dac147_0    defaults
libxml2                   2.9.4                hf05c021_6    defaults
libxslt                   1.1.29               hc208041_6    defaults
llvmlite                  0.20.0                   py36_0    defaults
locket                    0.2.0            py36hca03003_1    defaults
lxml                      4.1.1            py36h6c891f4_0    defaults
lzo                       2.10                 h362108e_2    defaults
Markdown                  2.6.8                     <pip>
markupsafe                1.0              py36h3a1e703_1    defaults
matplotlib                2.1.0            py36h5068139_0    defaults
mccabe                    0.6.1            py36hdaeb55d_0    defaults
mistune                   0.8.1            py36h638d0ca_0    defaults
mkl                       2018.0.1             hfbd8650_4    defaults
mkl-service               1.1.2            py36h7ea6df4_4    defaults
mpc                       1.0.3                h7a72875_5    defaults
mpfr                      3.1.5                h711e7fd_2    defaults
mpmath                    1.0.0            py36hf1b8295_2    defaults
msgpack-python            0.4.8            py36h46767b2_0    defaults
multipledispatch          0.4.9            py36hc5f92b5_0    defaults
navigator-updater         0.1.0            py36h7aee5fb_0    defaults
nbconvert                 5.3.1            py36h810822e_0    defaults
nbformat                  4.4.0            py36h827af21_0    defaults
ncurses                   6.0                  hd04f020_2    defaults
networkx                  1.11             py36he1dbd48_0    defaults
nltk                      3.2.5            py36h1190bce_0    defaults
nose                      1.3.7            py36h73fae2b_2    defaults
notebook                  5.2.2            py36h124cd7f_0    defaults
numba                     0.35.0              np113py36_6    defaults
numexpr                   2.6.4            py36habcfcfe_0    defaults
numpy                     1.13.3           py36h8a80b8c_2    defaults
numpydoc                  0.7.0            py36he54d08e_0    defaults
odo                       0.5.1            py36hc1af34a_0    defaults
olefile                   0.45.1                   py36_0    defaults
openpyxl                  2.4.9            py36h70dedc0_0    defaults
openssl                   1.0.2n               hdbc3d79_0    defaults
packaging                 16.8             py36he5e8135_0    defaults
pandas                    0.21.0           py36hfed917e_1    defaults
pandoc                    1.19.2.1             ha5e8f32_1    defaults
pandocfilters             1.4.2            py36h3b0b094_1    defaults
parso                     0.1.1            py36hc90e01c_0    defaults
partd                     0.3.8            py36hf5c4cb8_0    defaults
path.py                   10.5             py36h7bcb313_0    defaults
pathlib2                  2.3.0            py36h877a6d8_0    defaults
patsy                     0.4.1            py36ha1b3fa5_0    defaults
pcre                      8.41                 hfb6ab37_1    defaults
pep8                      1.7.0            py36hc268eb1_0    defaults
pexpect                   4.3.0            py36h427ab81_0    defaults
pickleshare               0.7.4            py36hf512f8e_0    defaults
pillow                    5.0.0            py36hfcce615_0    defaults
pip                       9.0.1            py36h1555ced_4    defaults
pluggy                    0.6.0            py36hb1d0581_0    defaults
ply                       3.10             py36h10e714e_0    defaults
prompt_toolkit            1.0.15           py36haeda067_0    defaults
protobuf                  3.3.0                     <pip>
psutil                    5.4.3            py36h1de35cc_0    defaults
ptyprocess                0.5.2            py36he6521c3_0    defaults
py                        1.5.2            py36ha69170d_0    defaults
pycodestyle               2.3.1            py36h83e8646_0    defaults
pycosat                   0.6.3            py36hee92d8f_0    defaults
pycparser                 2.18             py36h724b2fc_1    defaults
pycrypto                  2.6.1            py36h72f2894_1    defaults
pycurl                    7.43.0           py36hdb90038_3    defaults
pyflakes                  1.6.0            py36hea45e83_0    defaults
pygments                  2.2.0            py36h240cd3f_0    defaults
pylint                    1.7.4            py36hdee9077_0    defaults
pympler                   0.5              py36hc2752d1_0    defaults
pyodbc                    4.0.21           py36h816ef4a_0    defaults
pyopenssl                 17.5.0           py36h51e4350_0    defaults
pyparsing                 2.2.0            py36hb281f35_0    defaults
pyqt                      5.6.0            py36he5c6137_6    defaults
pysocks                   1.6.7            py36hfa33cec_1    defaults
pytables                  3.4.2            py36hfbd7ab0_2    defaults
pytest                    3.3.2                    py36_0    defaults
python                    3.6.4                hc167b69_1    defaults
python-dateutil           2.6.1            py36h86d2abb_1    defaults
python.app                2                py36h54569d5_7    defaults
pytz                      2017.3           py36hf0bf824_0    defaults
pywavelets                0.5.2            py36h2710a04_0    defaults
pyyaml                    3.12             py36h2ba1e63_1    defaults
pyzmq                     16.0.3           py36he48b5ad_0    defaults
qt                        5.6.2               h9975529_14    defaults
qtawesome                 0.4.4            py36h468c6fb_0    defaults
qtconsole                 4.3.1            py36hd96c0ff_0    defaults
qtpy                      1.3.1            py36h16bb863_0    defaults
readline                  7.0                  hc1231fa_4    defaults
requests                  2.18.4           py36h4516966_1    defaults
rope                      0.10.7           py36h68959ac_0    defaults
ruamel_yaml               0.15.35          py36h1de35cc_1    defaults
scikit-image              0.13.1           py36hd1453f6_0    defaults
scikit-learn              0.19.1           py36hffbff8c_0    defaults
scipy                     1.0.0            py36h1de22e9_0    defaults
seaborn                   0.8.1            py36h595ecd9_0    defaults
setuptools                38.4.0                   py36_0    defaults
simplegeneric             0.8.1            py36he5b5b09_0    defaults
singledispatch            3.4.0.3          py36hf20db9d_0    defaults
sip                       4.18.1           py36h2824476_2    defaults
six                       1.11.0           py36h0e22d5e_1    defaults
snowballstemmer           1.2.1            py36h6c7b616_0    defaults
sortedcollections         0.5.3            py36he9c3ed6_0    defaults
sortedcontainers          1.5.7            py36ha982688_0    defaults
sphinx                    1.6.3            py36hcd1b3e7_0    defaults
sphinxcontrib             1.0              py36h9364dc8_1    defaults
sphinxcontrib-websupport  1.0.1            py36h92f4a7a_1    defaults
spyder                    3.2.4            py36h908396f_0    defaults
sqlalchemy                1.1.13           py36h156b851_0    defaults
sqlite                    3.22.0               h3efe00b_0    defaults
statsmodels               0.8.0            py36h9c68fc9_0    defaults
sympy                     1.1.1            py36h7f3cf04_0    defaults
tblib                     1.3.2            py36hda67792_0    defaults
tensorflow                1.2.1                     <pip>
terminado                 0.6              py36h656782e_0    defaults
testpath                  0.3.1            py36h625a49b_0    defaults
tk                        8.6.7                h35a86e2_3    defaults
toolz                     0.8.2            py36h7b95164_0    defaults
tornado                   4.5.3                    py36_0    defaults
traitlets                 4.3.2            py36h65bd3ce_0    defaults
typing                    3.6.2            py36haa2d9ef_0    defaults
unicodecsv                0.14.1           py36he531d66_0    defaults
unixodbc                  2.3.4                h4cb4dde_1    defaults
urllib3                   1.22             py36h68b9469_0    defaults
wcwidth                   0.1.7            py36h8c6ec74_0    defaults
webencodings              0.5.1            py36h3b9701d_1    defaults
werkzeug                  0.12.2           py36h168efa1_0    defaults
wheel                     0.30.0           py36h5eb2c71_1    defaults
widgetsnbextension        3.0.8            py36h34759f8_0    defaults
wrapt                     1.10.11          py36hc29e774_0    defaults
xlrd                      1.1.0            py36h336f4a2_1    defaults
xlsxwriter                1.0.2            py36h3736301_0    defaults
xlwings                   0.11.4           py36hc75f156_0    defaults
xlwt                      1.2.0            py36h5ad1178_0    defaults
xz                        5.2.3                h0278029_2    defaults
yaml                      0.1.7                hc338f04_2    defaults
zeromq                    4.2.2                ha360ad0_2    defaults
zict                      0.1.3            py36h71da714_0    defaults
zlib                      1.2.11               hf3cbc9b_2    defaults
zope                      1.0                      py36_0    defaults
zope.interface            4.4.3            py36h74e83c9_0    defaults
```

**Comment by mocalvao** [comment]
I have the same kind of error when launching anaconda-navigator (either from console or through an icon launcher I created). This used to work seamlessly, but stopped after one of my last conda update's... My system is Python 3.7, in a Debian box

Navigator Error

An unexpected error occurred on Navigator start-up
Report

Please report this issue in the anaconda issue tracker
Main Error

could not determine a constructor for the tag 'tag:yaml.org,2002:python/unicode'
  in "/home/orca/.config/binstar/config.yaml", line 1, column 1

**Comment by goanpeca** [comment]
Please remove the configuration file

`/Users/alec/Library/Application Support/binstar/config.yaml`

---

@mocalvao please remove this file `/home/orca/.config/binstar/config.yaml`
