### ISSUE TITLE
dnf fails with `No module named '_sysconfigdata_x86_64_conda_cos6_linux_gnu'` after gcc_linux-64 is installed

### ISSUE THREAD

**Issue by kalefranz** [ContinuumIO/anaconda-issues#8437]
_From @rainwoodman on February 4, 2018 4:27_

After gcc_linux-64 is installed, the variable `_PYTHON_SYSCONFIGDATA_NAME` is set to override the sysconfig. 

dnf from Fedora uses the system python 3.6 installation, which fails if `_PYTHON_SYSCONFIG_DATA_NAME` is set, because the file is not in its python home.

Sequence to reproduce:
```
conda activate base
conda install gcc_linux-64
dnf
```

The workaround is to deactivate the conda environment before calling dnf.

The alternative would be asserting that the cross compilation no longer rely on environment variables to override the current Python's compiler setting -- which means switching to shipping a completely different python binary -- a lot of work with marginal gain. 

_Copied from original issue: conda/conda#6836_

**Comment by kalefranz** [comment]
@rainwoodman Are you using the latest build of python?  Can you be sure?  I think we discussed changing this recently.

**Comment by kalefranz** [comment]
This is ultimately a packaging issue.  Going to move it to the packages issue tracker.

**Comment by jjhelmus** [comment]
We have not changed from using the `_PYTHON_SYSCONFIG_DATA_NAME` variable but I think everyone is in favor of the change.  Rather than deactivating the environment you can clear the variable for the one command, `_PYTHON_SYSCONFIG_DATA_NAME= dnf`.

**Comment by rainwoodman** [comment]
Thanks. Indeed resetting the env should work.

I also noticed gdb fails for a similar reason. gdb is used far more frequently than dnf I would say.

**Comment by ironbar** [comment]
I'm having a similar problem after installing theano=1.0.1
When I run source deactivate I get the same import error.

```
(lynx_clone) $ source deactivate
Traceback (most recent call last):
  File "/home/gbarbadillo/anaconda2/lib/python2.7/site.py", line 553, in <module>
    main()
  File "/home/gbarbadillo/anaconda2/lib/python2.7/site.py", line 530, in main
    known_paths = addusersitepackages(known_paths)
  File "/home/gbarbadillo/anaconda2/lib/python2.7/site.py", line 275, in addusersitepackages
    user_site = getusersitepackages()
  File "/home/gbarbadillo/anaconda2/lib/python2.7/site.py", line 250, in getusersitepackages
    user_base = getuserbase() # this will also set USER_BASE
  File "/home/gbarbadillo/anaconda2/lib/python2.7/site.py", line 240, in getuserbase
    USER_BASE = get_config_var('userbase')
  File "/home/gbarbadillo/anaconda2/lib/python2.7/sysconfig.py", line 524, in get_config_var
    return get_config_vars().get(name)
  File "/home/gbarbadillo/anaconda2/lib/python2.7/sysconfig.py", line 476, in get_config_vars
    _init_posix(_CONFIG_VARS)
  File "/home/gbarbadillo/anaconda2/lib/python2.7/sysconfig.py", line 359, in _init_posix
    _temp = __import__(name, globals(), locals(), ['build_time_vars'], 0)
ImportError: No module named _sysconfigdata_x86_64_conda_cos6_linux_gnu
```

**Comment by mingwandroid** [comment]
@ironbar you need to update python in your base environment.

**Comment by ironbar** [comment]
Thanks Ray, currently I'm using 2.7.11, to which version I should update?

**Comment by mingwandroid** [comment]
The latest in the Python 2 series (2.7.14 build 29), but you do not need to worry about that and just need to do:

`conda update python`

**Comment by ironbar** [comment]
It works perfect!!! Thanks a lot

**Comment by csoja** [comment]
@mingwandroid can this issue be closed now?

**Comment by mingwandroid** [comment]
I don't think so, at present all we have is a workaround (deactivate conda when you need to use dnf).

This same problem is likely to manifest in other situations, we need to use a different env var than this one (and patch our Pythons and our compiler activation scripts) so that dnf (and anything else that uses the system Python) works correctly when conda is activated.
