### ISSUE TITLE
Jupyter does not start after installing gcc package

### ISSUE THREAD

**Issue by j0r1** [ContinuumIO/anaconda-issues#8498]
I've just installed Anaconda 5.0.1 for Linux x64, Python 3.6. When I run `jupyter notebook` everythings works fine. After I install the `gcc` package however (resolves to 4.8.5-7), jupyter no longer starts and I get the error:

    Traceback (most recent call last):
      File "/home/jori/anaconda3-501/bin/jupyter-notebook", line 7, in <module>
        from notebook.notebookapp import main
      File "/home/jori/anaconda3-501/lib/python3.6/site-packages/notebook/notebookapp.py", line 39, in <module>
        from zmq.eventloop import ioloop
      File "/home/jori/anaconda3-501/lib/python3.6/site-packages/zmq/__init__.py", line 34, in <module>
        from zmq import backend
      File "/home/jori/anaconda3-501/lib/python3.6/site-packages/zmq/backend/__init__.py", line 40, in <module>
        reraise(*exc_info)
      File "/home/jori/anaconda3-501/lib/python3.6/site-packages/zmq/utils/sixcerpt.py", line 34, in reraise
        raise value
      File "/home/jori/anaconda3-501/lib/python3.6/site-packages/zmq/backend/__init__.py", line 27, in <module>
        _ns = select_backend(first)
      File "/home/jori/anaconda3-501/lib/python3.6/site-packages/zmq/backend/select.py", line 26, in select_backend
        mod = __import__(name, fromlist=public_api)
      File "/home/jori/anaconda3-501/lib/python3.6/site-packages/zmq/backend/cython/__init__.py", line 6, in <module>
        from . import (constants, error, message, context,
    ImportError: /home/jori/anaconda3-501/lib/python3.6/site-packages/zmq/backend/cython/../../../../.././libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /home/jori/anaconda3-501/lib/python3.6/sitepackages/zmq/backend/cython/../../../../../libzmq.so.5.1.2)

From a listing of libstdc++ libs:

    -rw-rw-r-- 2 jori users 2943678 Nov 15  2016 libstdc++.a
    -rwxrwxr-x 2 jori users 1055192 Nov 15  2016 libstdc++.so.6.0.19*
    -rwxr-xr-x 2 jori users 8188008 Oct  6 06:05 libstdc++.so.6.0.24*
    -rw-rw-r-- 1 jori users    2339 Feb  9 20:32 libstdc++.so.6.0.19-gdb.py
    lrwxrwxrwx 1 jori users      19 Feb  9 20:32 libstdc++.so.6 -> libstdc++.so.6.0.19*
    lrwxrwxrwx 1 jori users      19 Feb  9 20:32 libstdc++.so -> libstdc++.so.6.0.19*

It seems that after installing the gcc package, `libstdc++.so` now is a link to an older version without GLIBCXX_3.4.20. 

After removing the gcc package again, it still didn't work but it seemed that now the ImportError pointed to one of my system libraries, not one of anaconda. A file listing of the libstdc++ libs now only shows 

    -rwxr-xr-x 2 jori users 8188008 Oct  6 06:05 libstdc++.so.6.0.24*
    
i.e., the symbolic links no longer exist. After restoring the symbolic links, jupyter starts again without problems.

**Comment by jjhelmus** [comment]
The `gcc` package has been replaced by the `gcc_linux-64` package.  Try removing `gcc` and installing `gcc_linux-64`.  It may be necessary to reinstall `libstdcxx-ng` to restore libstdc++ to its original version.

**Comment by j0r1** [comment]
That indeed solves it, thanks!
