### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by kboonma** [ContinuumIO/anaconda-issues#8539]
## Main error
Application <b>spyder</b> launch may have produced errors.
## Traceback
```
Traceback (most recent call last):
  File "C:\Users\kitti\Anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 3093, in main
    mainwindow = run_spyder(app, options, args)
  File "C:\Users\kitti\Anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 2995, in run_spyder
    main.setup()
  File "C:\Users\kitti\Anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 832, in setup
    from spyder.plugins.help import Help
  File "C:\Users\kitti\Anaconda3\lib\site-packages\spyder\plugins\help.py", line 32, in <module>
    from spyder.utils.help.sphinxify import (CSS_PATH, generate_context,
  File "C:\Users\kitti\Anaconda3\lib\site-packages\spyder\utils\help\sphinxify.py", line 32, in <module>
    from sphinx.application import Sphinx
  File "C:\Users\kitti\Anaconda3\lib\site-packages\Sphinx-1.5.6-py3.6.egg\sphinx\application.py", line 32, in <module>
    from sphinx.config import Config
  File "C:\Users\kitti\Anaconda3\lib\site-packages\Sphinx-1.5.6-py3.6.egg\sphinx\config.py", line 21, in <module>
    from sphinx.util.i18n import format_date
  File "C:\Users\kitti\Anaconda3\lib\site-packages\Sphinx-1.5.6-py3.6.egg\sphinx\util\i18n.py", line 20, in <module>
    import babel.dates
  File "C:\Users\kitti\Anaconda3\lib\site-packages\babel\dates.py", line 29, in <module>
    from babel.util import UTC, LOCALTZ
  File "C:\Users\kitti\Anaconda3\lib\site-packages\babel\util.py", line 19, in <module>
    from babel import localtime
ImportError: cannot import name 'localtime'

```
## System information
```
python: 3.6.1
language: en_GB
os: Windows;10;10.0.16299;AMD64;Intel64 Family 6 Model 61 Stepping 4, GenuineIntel
version: 1.6.2
platform: win-64
qt: 5.6.2
pyqt: 5.6.0
conda: 4.3.25
```

**Comment by goanpeca** [comment]
Try reinstalling sphinx and babel

```
conda install sphinx --force
conda install babel --force
```
