### ISSUE TITLE
Navigator fails on startup, asks me to report here

### ISSUE THREAD

**Issue by VeloSteve** [ContinuumIO/anaconda-issues#8563]
### Actual Behavior

After clicking the Anaconda Navigator shortcut my browser opens a window containing

> Navigator Error
> An unexpected error occurred on Navigator start-up
> 
> Report
> Please report this issue in the anaconda issue tracker
> 
> Main Error
> 'root_prefix'
> Traceback
> Traceback (most recent call last):
>   File "D:\Users\Steve\Anaconda3\lib\site-packages\anaconda_navigator\exceptions.py", line 75, in exception_handler
>     return_value = func(*args, **kwargs)
>   File "D:\Users\Steve\Anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 120, in start_app
>     window = run_app(splash)
>   File "D:\Users\Steve\Anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 63, in run_app
>     window = MainWindow(splash=splash)
>   File "D:\Users\Steve\Anaconda3\lib\site-packages\anaconda_navigator\widgets\main_window.py", line 162, in __init__
>     self.api = AnacondaAPI()
>   File "D:\Users\Steve\Anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 1270, in AnacondaAPI
>     ANACONDA_API = _AnacondaAPI()
>   File "D:\Users\Steve\Anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 71, in __init__
>     self._conda_api = CondaAPI()
>   File "D:\Users\Steve\Anaconda3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 1663, in CondaAPI
>     CONDA_API = _CondaAPI()
>   File "D:\Users\Steve\Anaconda3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 346, in __init__
>     self.set_conda_prefix()
>   File "D:\Users\Steve\Anaconda3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 495, in set_conda_prefix
>     self.ROOT_PREFIX = info['root_prefix']
> KeyError: 'root_prefix'

### Expected Behavior

Start the GUI.

### Steps to Reproduce

Here's the important part.
1) I could not upgrade some packages which Navigator said had updates available, and
   "pycosat" was always shown as a conflict.
2) Foolishly, I decided that since I never import anything called "pycosat" I would remove it.  I though that if anything important depended on it I would be shown the dependencies.
3) pycosat uninstalled
4) Now upgrade attempts led to long error messages.
5) Try to reinstall pycosat  with Scripts\conda.exe install -c anaconda pycosat
   - fails.
6) Try restarting Anaconda Navigator.
7) It crashed and told me to come here.

##### Anaconda or Miniconda version:
Directory is Anaconda3.  anaconda.exe -V reports 1.6.5
conda.exe -V reports 4.4.8
I'm not sure if any of these is what you want.  If it helps, I uninstalled an old Anaconda2 and installed Anaconda3 from scratch within the last 2-3 weeks.

##### Operating System:
Windows 7 Pro

##### `conda info`

```
# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "D:\Users\Steve\Anaconda3\lib\site-packages\conda\exceptions.py", line 772, in __call__
        return func(*args, **kwargs)
      File "D:\Users\Steve\Anaconda3\lib\site-packages\conda\cli\main.py", line 78, in _main
        exit_code = do_call(args, p)
      File "D:\Users\Steve\Anaconda3\lib\site-packages\conda\cli\conda_argparse.py", line 76, in do_
call
        module = import_module(relative_mod, __name__.rsplit('.', 1)[0])
      File "D:\Users\Steve\Anaconda3\lib\importlib\__init__.py", line 126, in import_module
        return _bootstrap._gcd_import(name[level:], package, level)
      File "<frozen importlib._bootstrap>", line 994, in _gcd_import
      File "<frozen importlib._bootstrap>", line 971, in _find_and_load
      File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
      File "<frozen importlib._bootstrap_external>", line 678, in exec_module
      File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
      File "D:\Users\Steve\Anaconda3\lib\site-packages\conda\cli\main_info.py", line 25, in <module>

        from ..core.repodata import SubdirData
      File "D:\Users\Steve\Anaconda3\lib\site-packages\conda\core\repodata.py", line 28, in <module>

        from ..core.package_cache import PackageCache
      File "D:\Users\Steve\Anaconda3\lib\site-packages\conda\core\package_cache.py", line 12, in <mo
dule>
        from .path_actions import CacheUrlAction, ExtractPackageAction
      File "D:\Users\Steve\Anaconda3\lib\site-packages\conda\core\path_actions.py", line 35, in <mod
ule>
        from ..history import History
      File "D:\Users\Steve\Anaconda3\lib\site-packages\conda\history.py", line 20, in <module>
        from .resolve import MatchSpec
      File "D:\Users\Steve\Anaconda3\lib\site-packages\conda\resolve.py", line 11, in <module>
        from .common.logic import Clauses, minimal_unsatisfiable_subset
      File "D:\Users\Steve\Anaconda3\lib\site-packages\conda\common\logic.py", line 32, in <module>
        import pycosat
    ModuleNotFoundError: No module named 'pycosat'

`$ D:\Users\Steve\Anaconda3\Scripts\conda info`


An unexpected error has occurred. Conda has prepared the above report.
If submitted, this report will be used by core maintainers to improve
future releases of conda.
Would you like conda to send this report to the core maintainers?
[y/N]: y
Upload successful.

Thank you for helping to improve conda.
Opt-in to always sending reports (and not see this message again)
by running

    $ conda config --set report_errors true
```

##### `conda list --show-channel-urls`

```
Traceback (most recent call last):
  File "D:\Users\Steve\Anaconda3\lib\site-packages\conda\exceptions.py", line 772, in __call__
    return func(*args, **kwargs)
  File "D:\Users\Steve\Anaconda3\lib\site-packages\conda\cli\main.py", line 78, in _main
    exit_code = do_call(args, p)
  File "D:\Users\Steve\Anaconda3\lib\site-packages\conda\cli\conda_argparse.py", line 76, in do_call

    module = import_module(relative_mod, __name__.rsplit('.', 1)[0])
  File "D:\Users\Steve\Anaconda3\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "D:\Users\Steve\Anaconda3\lib\site-packages\conda\cli\main_list.py", line 15, in <module>
    from ..egg_info import get_egg_info
  File "D:\Users\Steve\Anaconda3\lib\site-packages\conda\egg_info.py", line 15, in <module>
    from .misc import rel_path
  File "D:\Users\Steve\Anaconda3\lib\site-packages\conda\misc.py", line 17, in <module>
    from .core.index import get_index
  File "D:\Users\Steve\Anaconda3\lib\site-packages\conda\core\index.py", line 8, in <module>
    from .package_cache import PackageCache
  File "D:\Users\Steve\Anaconda3\lib\site-packages\conda\core\package_cache.py", line 12, in <module
>
    from .path_actions import CacheUrlAction, ExtractPackageAction
  File "D:\Users\Steve\Anaconda3\lib\site-packages\conda\core\path_actions.py", line 35, in <module>

    from ..history import History
  File "D:\Users\Steve\Anaconda3\lib\site-packages\conda\history.py", line 20, in <module>
    from .resolve import MatchSpec
  File "D:\Users\Steve\Anaconda3\lib\site-packages\conda\resolve.py", line 11, in <module>
    from .common.logic import Clauses, minimal_unsatisfiable_subset
  File "D:\Users\Steve\Anaconda3\lib\site-packages\conda\common\logic.py", line 32, in <module>
    import pycosat
ModuleNotFoundError: No module named 'pycosat'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Users\Steve\Anaconda3\Scripts\conda-script.py", line 10, in <module>
    sys.exit(main())
  File "D:\Users\Steve\Anaconda3\lib\site-packages\conda\cli\main.py", line 126, in main
    return conda_exception_handler(_main, *args)
  File "D:\Users\Steve\Anaconda3\lib\site-packages\conda\exceptions.py", line 1008, in conda_excepti
on_handler
    return_value = exception_handler(func, *args, **kwargs)
  File "D:\Users\Steve\Anaconda3\lib\site-packages\conda\exceptions.py", line 775, in __call__
    return self.handle_exception(exc_val, exc_tb)
  File "D:\Users\Steve\Anaconda3\lib\site-packages\conda\exceptions.py", line 815, in handle_excepti
on
    return self.handle_unexpected_exception(exc_val, exc_tb)
  File "D:\Users\Steve\Anaconda3\lib\site-packages\conda\exceptions.py", line 827, in handle_unexpec
ted_exception
    self.print_error_report(error_report)
  File "D:\Users\Steve\Anaconda3\lib\site-packages\conda\exceptions.py", line 880, in print_error_re
port
    from .cli.main_info import get_env_vars_str, get_main_info_str
  File "D:\Users\Steve\Anaconda3\lib\site-packages\conda\cli\main_info.py", line 25, in <module>
    from ..core.repodata import SubdirData
  File "D:\Users\Steve\Anaconda3\lib\site-packages\conda\core\repodata.py", line 28, in <module>
    from ..core.package_cache import PackageCache
  File "D:\Users\Steve\Anaconda3\lib\site-packages\conda\core\package_cache.py", line 12, in <module
>
    from .path_actions import CacheUrlAction, ExtractPackageAction
  File "D:\Users\Steve\Anaconda3\lib\site-packages\conda\core\path_actions.py", line 35, in <module>

    from ..history import History
  File "D:\Users\Steve\Anaconda3\lib\site-packages\conda\history.py", line 20, in <module>
    from .resolve import MatchSpec
  File "D:\Users\Steve\Anaconda3\lib\site-packages\conda\resolve.py", line 11, in <module>
    from .common.logic import Clauses, minimal_unsatisfiable_subset
  File "D:\Users\Steve\Anaconda3\lib\site-packages\conda\common\logic.py", line 32, in <module>
    import pycosat
ModuleNotFoundError: No module named 'pycosat'
```

**Comment by goanpeca** [comment]
@VeloSteve pycosat is de the dependency solver that conda uses... so basically conda is broken and unusable. Will need to add a safeguard to it.

You will need to reinstall everything from scratch I guess :-|

**Comment by VeloSteve** [comment]
Yes, I had to reinstall, but everything's fine now.  Lesson learned.  And yes, a safeguard (or at least a strong plain-language warning) seems like a good idea.

Thanks!
