### ISSUE TITLE
Navigator Start-Up Error

### ISSUE THREAD

**Issue by predictableprojection** [ContinuumIO/anaconda-issues#8582]
Installed Anaconda on Windows 8. Obtained:

#------------------------------------------------------

Navigator Error
An unexpected error occurred on Navigator start-up

Report
Please report this issue in the anaconda issue tracker

Main Error
could not determine a constructor for the tag 'tag:yaml.org,2002:python/unicode'
  in "C:\Users\Peter\AppData\Local\ContinuumIO\binstar\config.yaml", line 1, column 1
Traceback
Traceback (most recent call last):
  File "C:\Users\Peter\Anaconda3\lib\site-packages\anaconda_navigator\exceptions.py", line 75, in exception_handler
    return_value = func(*args, **kwargs)
  File "C:\Users\Peter\Anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 120, in start_app
    window = run_app(splash)
  File "C:\Users\Peter\Anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 63, in run_app
    window = MainWindow(splash=splash)
  File "C:\Users\Peter\Anaconda3\lib\site-packages\anaconda_navigator\widgets\main_window.py", line 163, in __init__
    self.api = AnacondaAPI()
  File "C:\Users\Peter\Anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 2004, in AnacondaAPI
    ANACONDA_API = _AnacondaAPI()
  File "C:\Users\Peter\Anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 89, in __init__
    self._client_api = ClientAPI()
  File "C:\Users\Peter\Anaconda3\lib\site-packages\anaconda_navigator\api\client_api.py", line 612, in ClientAPI
    CLIENT_API = _ClientAPI()
  File "C:\Users\Peter\Anaconda3\lib\site-packages\anaconda_navigator\api\client_api.py", line 82, in __init__
    log_level=logging.NOTSET
  File "C:\Users\Peter\Anaconda3\lib\site-packages\binstar_client\utils\config.py", line 96, in get_server_api
    config = get_config(remote_site=site)
  File "C:\Users\Peter\Anaconda3\lib\site-packages\binstar_client\utils\config.py", line 229, in get_config
    file_configs = load_file_configs(SEARCH_PATH)
  File "C:\Users\Peter\Anaconda3\lib\site-packages\binstar_client\utils\config.py", line 223, in load_file_configs
    raw_data = collections.OrderedDict(kv for kv in itertools.chain.from_iterable(load_paths))
  File "C:\Users\Peter\Anaconda3\lib\site-packages\binstar_client\utils\config.py", line 223, in 
    raw_data = collections.OrderedDict(kv for kv in itertools.chain.from_iterable(load_paths))
  File "C:\Users\Peter\Anaconda3\lib\site-packages\binstar_client\utils\config.py", line 203, in _dir_yaml_loader
    yield filepath, load_config(filepath)
  File "C:\Users\Peter\Anaconda3\lib\site-packages\binstar_client\utils\config.py", line 187, in load_config
    data = yaml_load(fd)
  File "C:\Users\Peter\Anaconda3\lib\site-packages\binstar_client\utils\yaml.py", line 9, in yaml_load
    return safe_load(stream)
  File "C:\Users\Peter\Anaconda3\lib\site-packages\yaml\__init__.py", line 94, in safe_load
    return load(stream, SafeLoader)
  File "C:\Users\Peter\Anaconda3\lib\site-packages\yaml\__init__.py", line 72, in load
    return loader.get_single_data()
  File "C:\Users\Peter\Anaconda3\lib\site-packages\yaml\constructor.py", line 37, in get_single_data
    return self.construct_document(node)
  File "C:\Users\Peter\Anaconda3\lib\site-packages\yaml\constructor.py", line 46, in construct_document
    for dummy in generator:
  File "C:\Users\Peter\Anaconda3\lib\site-packages\yaml\constructor.py", line 398, in construct_yaml_map
    value = self.construct_mapping(node)
  File "C:\Users\Peter\Anaconda3\lib\site-packages\yaml\constructor.py", line 204, in construct_mapping
    return super().construct_mapping(node, deep=deep)
  File "C:\Users\Peter\Anaconda3\lib\site-packages\yaml\constructor.py", line 125, in construct_mapping
    key = self.construct_object(key_node, deep=deep)
  File "C:\Users\Peter\Anaconda3\lib\site-packages\yaml\constructor.py", line 86, in construct_object
    data = constructor(self, node)
  File "C:\Users\Peter\Anaconda3\lib\site-packages\yaml\constructor.py", line 414, in construct_undefined
    node.start_mark)
yaml.constructor.ConstructorError: could not determine a constructor for the tag 'tag:yaml.org,2002:python/unicode'
  in "C:\Users\Peter\AppData\Local\ContinuumIO\binstar\config.yaml", line 1, column 1

**Comment by slothkins** [comment]
i'm getting same error on osx

**Comment by goanpeca** [comment]
Please remove this file

`C:\Users\Peter\Anaconda3\lib\site-packages\binstar_client\utils\config.py`

**Comment by goanpeca** [comment]
Could you please share the contents of 

`C:\Users\Peter\AppData\Local\ContinuumIO\binstar\config.yaml` ?

**Comment by predictableprojection** [comment]
Hi,

!!python/unicode 'sites':
  !!python/unicode 'alpha': {!!python/unicode 'url': !!python/unicode '
http://api.alpha.binstar.org'}
  !!python/unicode 'binstar': {!!python/unicode 'url': !!python/unicode '
https://api.anaconda.org'}
url: https://api.anaconda.org


Thanks!

Peter Ouwehand
Associate Professor
African Institute of Financial Markets & Risk Management
University of Cape Town
+27 21 650 1507
+27 74 143 2847

**Comment by goanpeca** [comment]
@predictableprojection  could you update anaconda-client on the terminal/anaconda prompt

```
conda update anaconda-client
```

Does it work now?
