### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by hj136330** [ContinuumIO/anaconda-issues#8595]
## Main error
Application <b>notebook</b> launch may have produced errors.
## Traceback
```
Traceback (most recent call last):
  File "f:\ProgramData\Anaconda3\Scripts\jupyter-notebook-script.py", line 5, in <module>
    sys.exit(notebook.notebookapp.main())
  File "f:\ProgramData\Anaconda3\lib\site-packages\jupyter_core\application.py", line 267, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "f:\ProgramData\Anaconda3\lib\site-packages\traitlets\config\application.py", line 657, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-7>", line 2, in initialize
  File "f:\ProgramData\Anaconda3\lib\site-packages\traitlets\config\application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "f:\ProgramData\Anaconda3\lib\site-packages\notebook\notebookapp.py", line 1296, in initialize
    self.init_webapp()
  File "f:\ProgramData\Anaconda3\lib\site-packages\notebook\notebookapp.py", line 1120, in init_webapp
    self.http_server.listen(port, self.ip)
  File "f:\ProgramData\Anaconda3\lib\site-packages\tornado\tcpserver.py", line 142, in listen
    sockets = bind_sockets(port, address=address)
  File "f:\ProgramData\Anaconda3\lib\site-packages\tornado\netutil.py", line 156, in bind_sockets
    0, flags)):
  File "f:\ProgramData\Anaconda3\lib\socket.py", line 743, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 10106] getaddrinfo failed

```
## System information
```
python: 3.6.1
l

**Comment by goanpeca** [comment]
@hj136330 did you perfomr a All Users install?
