### ISSUE TITLE
spyder stops at startup with "unknown locale: utf-8"

### ISSUE THREAD

**Issue by vnoel** [ContinuumIO/anaconda-issues#86]
After installing Anaconda 1.9 on my MBP (13", OS X 10.9.1), trying to launch spyder in the terminal gives me:

```
Traceback (most recent call last):
  File "/Users/vnoel/anaconda/bin/spyder", line 3, in <module>
    start_app.main()
  File "/Users/vnoel/anaconda/lib/python2.7/site-packages/spyderlib/start_app.py", line 72, in main
    from spyderlib import spyder
  File "/Users/vnoel/anaconda/lib/python2.7/site-packages/spyderlib/spyder.py", line 106, in <module>
    from spyderlib.plugins.inspector import ObjectInspector
  File "/Users/vnoel/anaconda/lib/python2.7/site-packages/spyderlib/plugins/inspector.py", line 46, in <module>
    from spyderlib.utils.inspector.sphinxify import (CSS_PATH, sphinxify,
  File "/Users/vnoel/anaconda/lib/python2.7/site-packages/spyderlib/utils/inspector/sphinxify.py", line 28, in <module>
    from docutils.utils import SystemMessage as SystemMessage
  File "/Users/vnoel/anaconda/lib/python2.7/site-packages/docutils/utils/__init__.py", line 20, in <module>
    import docutils.io
  File "/Users/vnoel/anaconda/lib/python2.7/site-packages/docutils/io.py", line 18, in <module>
    from docutils.utils.error_reporting import locale_encoding, ErrorString, ErrorOutput
  File "/Users/vnoel/anaconda/lib/python2.7/site-packages/docutils/utils/error_reporting.py", line 47, in <module>
    locale_encoding = locale.getlocale()[1] or locale.getdefaultlocale()[1]
  File "/Users/vnoel/anaconda/python.app/Contents/lib/python2.7/locale.py", line 511, in getdefaultlocale
    return _parse_localename(localename)
  File "/Users/vnoel/anaconda/python.app/Contents/lib/python2.7/locale.py", line 443, in _parse_localename
    raise ValueError, 'unknown locale: %s' % localename
ValueError: unknown locale: UTF-8
```

**Comment by vvvvalvalval** [comment]
Had the issue to. Setting the LANG var didn't solve it but got me a bit farther: it crashed during the loading window.

**Comment by ccordoba12** [comment]
What's the error you're seeing?

**Comment by vvvvalvalval** [comment]
Exactly the same as above.

**Comment by vnoel** [comment]
funnily enough, I can't reproduce anymore.
I'm now on 10.10.2, "echo $LANG" returns en_US.UTF-8
spyder 2.3.2.

**Comment by asmeurer** [comment]
Did Apple finally fix the bug?

**Comment by asmeurer** [comment]
See http://conda.pydata.org/docs/troubleshooting.html#issue-valueerror-unknown-locale-utf-8-on-mac-os-x for more information on the unknown locale issue. I'm closing this as there's nothing we can do about it, beyond that support document.
