### ISSUE TITLE
Navigator error when launching Anaconda-Navigator on mac OS 10.13.3

### ISSUE THREAD

**Issue by mainaezio** [ContinuumIO/anaconda-issues#8605]
### Actual Behavior

I reinstalled anconda3 from scratch on macOS 10.13.3
When I launch Anaconda-Navigator from the /Applications folder, I get in a new Chrome window:

Navigator Error
An unexpected error occurred on Navigator start-up

Report
Please report this issue in the anaconda issue tracker

Main Error
could not determine a constructor for the tag 'tag:yaml.org,2002:python/unicode'
  in "/Users/maina/Library/Application Support/binstar/config.yaml", line 1, column 1
Traceback
Traceback (most recent call last):
  File "/Users/maina/anaconda3/lib/python3.6/site-packages/anaconda_navigator/exceptions.py", line 75, in exception_handler
    return_value = func(*args, **kwargs)
  File "/Users/maina/anaconda3/lib/python3.6/site-packages/anaconda_navigator/app/start.py", line 120, in start_app
    window = run_app(splash)
  File "/Users/maina/anaconda3/lib/python3.6/site-packages/anaconda_navigator/app/start.py", line 63, in run_app
    window = MainWindow(splash=splash)
  File "/Users/maina/anaconda3/lib/python3.6/site-packages/anaconda_navigator/widgets/main_window.py", line 163, in __init__
    self.api = AnacondaAPI()
  File "/Users/maina/anaconda3/lib/python3.6/site-packages/anaconda_navigator/api/anaconda_api.py", line 2004, in AnacondaAPI
    ANACONDA_API = _AnacondaAPI()
  File "/Users/maina/anaconda3/lib/python3.6/site-packages/anaconda_navigator/api/anaconda_api.py", line 89, in __init__
    self._client_api = ClientAPI()
  File "/Users/maina/anaconda3/lib/python3.6/site-packages/anaconda_navigator/api/client_api.py", line 612, in ClientAPI
    CLIENT_API = _ClientAPI()
  File "/Users/maina/anaconda3/lib/python3.6/site-packages/anaconda_navigator/api/client_api.py", line 82, in __init__
    log_level=logging.NOTSET
  File "/Users/maina/anaconda3/lib/python3.6/site-packages/binstar_client/utils/config.py", line 96, in get_server_api
    config = get_config(remote_site=site)
  File "/Users/maina/anaconda3/lib/python3.6/site-packages/binstar_client/utils/config.py", line 229, in get_config
    file_configs = load_file_configs(SEARCH_PATH)
  File "/Users/maina/anaconda3/lib/python3.6/site-packages/binstar_client/utils/config.py", line 223, in load_file_configs
    raw_data = collections.OrderedDict(kv for kv in itertools.chain.from_iterable(load_paths))
  File "/Users/maina/anaconda3/lib/python3.6/site-packages/binstar_client/utils/config.py", line 223, in 
    raw_data = collections.OrderedDict(kv for kv in itertools.chain.from_iterable(load_paths))
  File "/Users/maina/anaconda3/lib/python3.6/site-packages/binstar_client/utils/config.py", line 203, in _dir_yaml_loader
    yield filepath, load_config(filepath)
  File "/Users/maina/anaconda3/lib/python3.6/site-packages/binstar_client/utils/config.py", line 187, in load_config
    data = yaml_load(fd)
  File "/Users/maina/anaconda3/lib/python3.6/site-packages/binstar_client/utils/yaml.py", line 9, in yaml_load
    return safe_load(stream)
  File "/Users/maina/anaconda3/lib/python3.6/site-packages/yaml/__init__.py", line 94, in safe_load
    return load(stream, SafeLoader)
  File "/Users/maina/anaconda3/lib/python3.6/site-packages/yaml/__init__.py", line 72, in load
    return loader.get_single_data()
  File "/Users/maina/anaconda3/lib/python3.6/site-packages/yaml/constructor.py", line 37, in get_single_data
    return self.construct_document(node)
  File "/Users/maina/anaconda3/lib/python3.6/site-packages/yaml/constructor.py", line 46, in construct_document
    for dummy in generator:
  File "/Users/maina/anaconda3/lib/python3.6/site-packages/yaml/constructor.py", line 398, in construct_yaml_map
    value = self.construct_mapping(node)
  File "/Users/maina/anaconda3/lib/python3.6/site-packages/yaml/constructor.py", line 204, in construct_mapping
    return super().construct_mapping(node, deep=deep)
  File "/Users/maina/anaconda3/lib/python3.6/site-packages/yaml/constructor.py", line 125, in construct_mapping
    key = self.construct_object(key_node, deep=deep)
  File "/Users/maina/anaconda3/lib/python3.6/site-packages/yaml/constructor.py", line 86, in construct_object
    data = constructor(self, node)
  File "/Users/maina/anaconda3/lib/python3.6/site-packages/yaml/constructor.py", line 414, in construct_undefined
    node.start_mark)
yaml.constructor.ConstructorError: could not determine a constructor for the tag 'tag:yaml.org,2002:python/unicode'
  in "/Users/maina/Library/Application Support/binstar/config.yaml", line 1, column 1

##### Anaconda or Miniconda version:
Anaconda 5.1 for macOS Installer
Python 3.6 version

downloaded from https://www.anaconda.com/download/#macos
##### `conda info`

```
     active environment : None
       user config file : /Users/maina/.condarc
 populated config files : /Users/maina/.condarc
          conda version : 4.4.10
    conda-build version : not installed
         python version : 2.7.14.final.0
       base environment : /anaconda  (writable)
           channel URLs : https://conda.anaconda.org/anaconda-fusion/osx-64
                          https://conda.anaconda.org/anaconda-fusion/noarch
                          https://repo.continuum.io/pkgs/main/osx-64
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/osx-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/osx-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/osx-64
                          https://repo.continuum.io/pkgs/pro/noarch
          package cache : /anaconda/pkgs
                          /Users/maina/.conda/pkgs
       envs directories : /anaconda/envs
                          /Users/maina/.conda/envs
               platform : osx-64
             user-agent : conda/4.4.10 requests/2.18.4 CPython/2.7.14 Darwin/17.4.0 OSX/10.13.3
                UID:GID : 503:20
             netrc file : None
           offline mode : False


```

##### `conda list --show-channel-urls`

```
_license                  1.1                      py27_1    defaults
alabaster                 0.7.10           py27h9dd7d6e_0    defaults
anaconda                  custom           py27h2cfa9e9_0    defaults
anaconda-client           1.6.9                    py27_0    defaults
anaconda-navigator        1.7.0                    py27_0    defaults
anaconda-project          0.8.2            py27h2dc806c_0    defaults
appnope                   0.1.0            py27hb466136_0    defaults
appscript                 1.0.1            py27h451298e_1    defaults
asn1crypto                0.24.0                   py27_0    defaults
astroid                   1.6.1                    py27_0    defaults
astropy                   2.0.4            py27h917ab60_1    defaults
attrs                     17.4.0                   py27_0    defaults
babel                     2.5.3                    py27_0    defaults
backports                 1.0              py27hb4f9756_1    defaults
backports.functools_lru_cache 1.4              py27h2aca819_1    defaults
backports.shutil_get_terminal_size 1.0.0            py27hc9115de_2    defaults
backports_abc             0.5              py27h6972548_0    defaults
beautifulsoup4            4.6.0            py27h9416283_1    defaults
bitarray                  0.8.1            py27h1de35cc_1    defaults
bkcharts                  0.2              py27haafc882_0    defaults
blaze                     0.11.3           py27hb49378a_0    defaults
bleach                    2.1.2                    py27_0    defaults
bokeh                     0.12.13          py27h5233db4_0    defaults
boto                      2.48.0           py27hacdd0fd_1    defaults
bottleneck                1.2.1            py27h71f98a3_0    defaults
bzip2                     1.0.6                hd86a083_4    defaults
ca-certificates           2017.08.26           ha1e5d58_0    defaults
cairo                     1.14.12              hab642c4_0    defaults
certifi                   2018.1.18                py27_0    defaults
cffi                      1.11.4           py27h342bebf_0    defaults
chardet                   3.0.4            py27h2842e91_1    defaults
chest                     0.2.3                    py27_0    defaults
click                     6.7              py27h2b86a94_0    defaults
cloudpickle               0.5.2                    py27_1    defaults
clyent                    1.2.2            py27hc0ae608_0    defaults
colorama                  0.3.9            py27hbbe92b6_0    defaults
conda                     4.4.10                   py27_0    defaults
conda-env                 2.6.0                h36134e3_0    defaults
configobj                 5.0.6                    py27_0    defaults
configparser              3.5.0            py27hc7edf1b_0    defaults
contextlib2               0.5.5            py27h9cb85f4_0    defaults
coverage                  4.4.2            py27hf37a882_0    defaults
cryptography              2.1.4            py27hdbc5e8f_0    defaults
curl                      7.58.0               ha441bb4_0    defaults
cycler                    0.10.0           py27hfc73c78_0    defaults
cython                    0.27.3           py27h6429b90_0    defaults
cytoolz                   0.9.0            py27h1de35cc_0    defaults
dask                      0.17.0                   py27_0    defaults
dask-core                 0.17.0                   py27_0    defaults
datashape                 0.5.4            py27hd6a1745_0    defaults
dbus                      1.12.2               h5243cc1_1    defaults
decorator                 4.2.1                    py27_0    defaults
dill                      0.2.7.1          py27hc0d316d_0    defaults
distributed               1.21.0                   py27_0    defaults
docutils                  0.14             py27h0befae3_0    defaults
entrypoints               0.2.3            py27hd680fb1_2    defaults
enum34                    1.1.6            py27hf475452_1    defaults
et_xmlfile                1.0.1            py27hc42f929_0    defaults
expat                     2.2.5                hb8e80ba_0    defaults
fastcache                 1.0.2            py27h1de35cc_2    defaults
filelock                  2.0.13           py27h2c227fa_0    defaults
flask                     0.12.2           py27h3ac5568_0    defaults
flask-cors                3.0.3            py27h13db576_0    defaults
fontconfig                2.12.4               hffb9db1_2    defaults
freetype                  2.8                  h12048fb_1    defaults
funcsigs                  1.0.2            py27hb9f6266_0    defaults
functools32               3.2.3.2          py27h8ceab06_1    defaults
futures                   3.2.0            py27h1b80678_0    defaults
get_terminal_size         1.0.0                h7520d66_0    defaults
gettext                   0.19.8.1             h15daf44_3    defaults
gevent                    1.2.2            py27hc02608c_0    defaults
glib                      2.53.6               h33f6a65_2    defaults
glob2                     0.6              py27h55c9705_0    defaults
gmp                       6.1.2                hb37e062_1    defaults
gmpy2                     2.0.8            py27h4bc979a_2    defaults
graphite2                 1.3.10               h337f25e_1    defaults
graphviz                  2.40.1               h0a44026_0    defaults
greenlet                  0.4.12           py27h081ed54_0    defaults
h5py                      2.7.1            py27h75626f5_0    defaults
harfbuzz                  1.7.4                h08e020e_0    defaults
hdf5                      1.10.1               ha036c08_1    defaults
heapdict                  1.0.0                    py27_2    defaults
html5lib                  1.0.1            py27h5233db4_0    defaults
hypothesis                3.38.5           py27h3e2e078_0    defaults
icu                       58.2                 h4b95b61_1    defaults
idna                      2.6              py27hedea723_1    defaults
imageio                   2.2.0            py27h37746d9_0    defaults
imagesize                 0.7.1            py27h4f7bcc8_0    defaults
intel-openmp              2018.0.0             h8158457_8    defaults
ipaddress                 1.0.19                   py27_0    defaults
ipykernel                 4.8.0                    py27_0    defaults
ipython                   5.4.1                    py27_2    defaults
ipython_genutils          0.2.0            py27h8b9a179_0    defaults
ipywidgets                7.1.1                    py27_0    defaults
isort                     4.2.15           py27h5bf637f_0    defaults
itsdangerous              0.24             py27h3948ded_1    defaults
jbig                      2.1                  h4d881f8_0    defaults
jdcal                     1.3              py27hfeaf94f_0    defaults
jedi                      0.11.1                   py27_0    defaults
jinja2                    2.10             py27h70b8dc5_0    defaults
jpeg                      9b                   he5867d9_2    defaults
jsonschema                2.6.0            py27hd9b497e_0    defaults
jupyter                   1.0.0                    py27_4    defaults
jupyter_client            5.2.2                    py27_0    defaults
jupyter_console           5.2.0            py27h9702a86_1    defaults
jupyter_core              4.4.0            py27h5ea6ba4_0    defaults
jupyterlab                0.31.8                   py27_0    defaults
jupyterlab_launcher       0.10.2                   py27_0    defaults
lazy-object-proxy         1.3.1            py27h712ce3f_0    defaults
libcurl                   7.58.0               hf30b1f0_0    defaults
libcxx                    4.0.1                h579ed51_0    defaults
libcxxabi                 4.0.1                hebd6815_0    defaults
libedit                   3.1                  hb4e282d_0    defaults
libffi                    3.2.1                h475c297_4    defaults
libgfortran               3.0.1                h93005f0_2    defaults
libiconv                  1.15                 hdd342a3_7    defaults
libopenblas               0.2.20               hdc02c5d_4    defaults
libpng                    1.6.34               he12f830_0    defaults
libprotobuf               3.4.1                h326466f_0    defaults
libsodium                 1.0.15               hd9e47c5_0    defaults
libssh2                   1.8.0                h322a93b_4    defaults
libtiff                   4.0.9                h0dac147_0    defaults
libxml2                   2.9.7                hab757c2_0    defaults
libxslt                   1.1.32               hb819dd2_0    defaults
llvmlite                  0.21.0           py27hac8ee23_0    defaults
locket                    0.2.0            py27ha10513d_1    defaults
lxml                      4.1.1            py27hef8c89e_1    defaults
lzo                       2.10                 h362108e_2    defaults
markupsafe                1.0              py27hd3c86fa_1    defaults
matplotlib                2.1.2            py27h6d6146d_0    defaults
mccabe                    0.6.1            py27h1f69e8d_0    defaults
mistune                   0.8.3                    py27_0    defaults
mkl                       2018.0.1             hfbd8650_4    defaults
mkl-service               1.1.2            py27hcba3029_4    defaults
mock                      2.0.0            py27h300204c_0    defaults
mpc                       1.0.3                h7a72875_5    defaults
mpfr                      3.1.5                h711e7fd_2    defaults
mpmath                    1.0.0            py27h6b0eff6_2    defaults
msgpack-python            0.5.1            py27h04f5b5a_0    defaults
multipledispatch          0.4.9            py27h10993aa_0    defaults
navigator-updater         0.1.0            py27ha63e0b4_0    defaults
nbconvert                 5.3.1            py27h6455e4c_0    defaults
nbformat                  4.4.0            py27hddc86d0_0    defaults
ncurses                   6.0                  hd04f020_2    defaults
networkx                  2.1                      py27_0    defaults
nltk                      3.2.5            py27h2e86947_0    defaults
nose                      1.3.7            py27h2ee3cb8_2    defaults
notebook                  5.4.0                    py27_0    defaults
numba                     0.36.2          np112py27hdcb5c31_0    defaults
numexpr                   2.6.4            py27hf375000_0    defaults
numpy                     1.12.1           py27h71f5d73_1    defaults
numpydoc                  0.7.0            py27h022f19e_0    defaults
odo                       0.5.1            py27h992a9f7_0    defaults
olefile                   0.45.1                   py27_0    defaults
openblas                  0.2.20                        4    defaults
openblas-devel            0.2.20                        4    defaults
openpyxl                  2.4.10                   py27_0    defaults
openssl                   1.0.2n               hdbc3d79_0    defaults
packaging                 16.8             py27h24b219a_0    defaults
pandas                    0.22.0           py27h0a44026_0    defaults
pandoc                    1.19.2.1             ha5e8f32_1    defaults
pandocfilters             1.4.2            py27hed78c4e_1    defaults
pango                     1.41.0               h3bae10e_0    defaults
parso                     0.1.1            py27he57c4c6_0    defaults
partd                     0.3.8            py27h7560dbf_0    defaults
path.py                   10.5             py27h0d68f8b_0    defaults
pathlib2                  2.3.0            py27he09da1e_0    defaults
patsy                     0.5.0                    py27_0    defaults
pbr                       3.1.1            py27h45d16fa_0    defaults
pcre                      8.41                 hfb6ab37_1    defaults
pep8                      1.7.1                    py27_0    defaults
pexpect                   4.3.1                    py27_0    defaults
pickleshare               0.7.4            py27h37e3d41_0    defaults
pillow                    5.0.0            py27hfcce615_0    defaults
pip                       9.0.1            py27h1567d89_4    defaults
pixman                    0.34.0               hca0a616_3    defaults
pkginfo                   1.4.1            py27ha9221e7_0    defaults
pluggy                    0.6.0            py27had36429_0    defaults
ply                       3.10             py27h6279b8a_0    defaults
prompt_toolkit            1.0.15           py27h4a7b9c2_0    defaults
protobuf                  3.4.1            py27h66c1d77_0    defaults
psutil                    5.4.3            py27h1de35cc_0    defaults
ptyprocess                0.5.2            py27h70f6364_0    defaults
py                        1.5.2            py27he6783ac_0    defaults
pyasn1                    0.4.2            py27hc80d542_0    defaults
pycodestyle               2.3.1            py27h5b634e0_0    defaults
pycosat                   0.6.3            py27h6c51c7e_0    defaults
pycparser                 2.18             py27h0d28d88_1    defaults
pycrypto                  2.6.1            py27h1de35cc_7    defaults
pycurl                    7.43.0.1         py27hdbc3d79_0    defaults
pydot                     1.2.3            py27h5ed12cb_0    defaults
pyflakes                  1.6.0            py27h4446e76_0    defaults
pygments                  2.2.0            py27h1a556bb_0    defaults
pylint                    1.8.2                    py27_0    defaults
pympler                   0.5              py27hf3ee101_0    defaults
pyodbc                    4.0.22           py27h0a44026_0    defaults
pyopenssl                 17.5.0           py27hfda213f_0    defaults
pyparsing                 2.2.0            py27h5bb6aaf_0    defaults
pyqt                      5.6.0            py27hf21fe59_6    defaults
pysocks                   1.6.7            py27h1cff6a6_1    defaults
pytables                  3.4.2            py27ha4551b8_2    defaults
pytest                    3.3.2                    py27_0    defaults
python                    2.7.14              hde5916a_29    defaults
python-dateutil           2.6.1            py27hd56c96b_1    defaults
python-graphviz           0.8.2                    py27_0    defaults
python.app                2                py27hf2d5e94_7    defaults
pytz                      2018.3                   py27_0    defaults
pywavelets                0.5.2            py27hd99e88a_0    defaults
pyyaml                    3.12             py27ha7932d0_1    defaults
pyzmq                     16.0.3           py27h91ccc67_0    defaults
qt                        5.6.2               h9975529_14    defaults
qtawesome                 0.4.4            py27hdeb2f59_0    defaults
qtconsole                 4.3.1            py27hdc90b4f_0    defaults
qtpy                      1.3.1            py27h39159f8_0    defaults
readline                  7.0                  hc1231fa_4    defaults
redis                     4.0.2                hc28a91c_0    defaults
redis-py                  2.10.6           py27hda58ff7_0    defaults
requests                  2.18.4           py27h9b2b37c_1    defaults
rope                      0.10.7           py27hffa1879_0    defaults
ruamel_yaml               0.15.35          py27h1de35cc_1    defaults
scandir                   1.6              py27h97aa1ee_0    defaults
scikit-image              0.13.1           py27h1de35cc_1    defaults
scikit-learn              0.19.1           py27h9788993_0    defaults
scipy                     1.0.0            py27h793f721_0    defaults
seaborn                   0.8.1            py27h6bd0ddc_0    defaults
send2trash                1.4.2                    py27_0    defaults
setuptools                38.4.0                   py27_0    defaults
simplegeneric             0.8.1                    py27_2    defaults
singledispatch            3.4.0.3          py27he22c18d_0    defaults
sip                       4.18.1           py27h6300f65_2    defaults
six                       1.11.0           py27h7252ba3_1    defaults
snowballstemmer           1.2.1            py27h68ac032_0    defaults
sockjs-tornado            1.0.3                    py27_0    defaults
sortedcollections         0.5.3            py27h8094be4_0    defaults
sortedcontainers          1.5.9                    py27_0    defaults
sphinx                    1.6.6                    py27_0    defaults
sphinxcontrib             1.0              py27hd2ed746_1    defaults
sphinxcontrib-websupport  1.0.1            py27h857890b_1    defaults
spyder                    3.2.6                    py27_0    defaults
sqlalchemy                1.2.1            py27h1de35cc_0    defaults
sqlite                    3.22.0               h3efe00b_0    defaults
ssl_match_hostname        3.5.0.1          py27h8780752_2    defaults
statsmodels               0.8.0            py27h6d68dbf_0    defaults
subprocess32              3.2.7            py27h24b2887_0    defaults
sympy                     1.1.1            py27hce55102_0    defaults
tblib                     1.3.2            py27ha684fc4_0    defaults
tensorflow                1.1.0               np112py27_0    defaults
terminado                 0.8.1                    py27_1    defaults
testpath                  0.3.1            py27h72d81a5_0    defaults
tk                        8.6.7                h35a86e2_3    defaults
toolz                     0.9.0                    py27_0    defaults
tornado                   4.5.3                    py27_0    defaults
traitlets                 4.3.2            py27hcf08151_0    defaults
typing                    3.6.2            py27h646fea0_0    defaults
unicodecsv                0.14.1           py27h170f95c_0    defaults
unixodbc                  2.3.4                h4cb4dde_1    defaults
urllib3                   1.22             py27hc3787e9_0    defaults
wcwidth                   0.1.7            py27h817c265_0    defaults
webencodings              0.5.1            py27h19a9f58_1    defaults
werkzeug                  0.14.1                   py27_0    defaults
wheel                     0.30.0           py27h677a027_1    defaults
widgetsnbextension        3.1.0                    py27_0    defaults
wrapt                     1.10.11          py27hd341262_0    defaults
xlrd                      1.1.0            py27hbd41ed1_1    defaults
xlsxwriter                1.0.2            py27h7f1064a_0    defaults
xlwings                   0.11.5                   py27_0    defaults
xlwt                      1.2.0            py27hbeec4ae_0    defaults
xz                        5.2.3                h0278029_2    defaults
yaml                      0.1.7                hc338f04_2    defaults
zeromq                    4.2.2                ha360ad0_2    defaults
zict                      0.1.3            py27h5fff8b1_0    defaults
zlib                      1.2.11               hf3cbc9b_2    defaults
zope                      1.0                      py27_0    defaults
zope.interface            4.4.3            py27h03e767a_0    defaults

```

**Comment by goanpeca** [comment]
@mainaezio could you provide the contents of this file -> `/Users/maina/Library/Application Support/binstar/config.yaml` so we can check what the corruption might be coming from?

Thanks

**Comment by mainaezio** [comment]
Here it is:

!!python/unicode 'sites':
  !!python/unicode 'alpha': {!!python/unicode 'url': !!python/unicode
'http://api.alpha.binstar.org'}
  !!python/unicode 'binstar': {!!python/unicode 'url': !!python/unicode
'https://api.anaconda.org'}
url: https://api.anaconda.org



> @mainaezio could you provide the contents of this file ->
> `/Users/maina/Library/Application Support/binstar/config.yaml` so we can
> check what the corruption might be coming from?
>
> Thanks
>
> --
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/ContinuumIO/anaconda-issues/issues/8605#issuecomment-366749180


Ezio Maina
Dip. di Fisica Teorica, Universita' di Torino
INFN, Sez di Torino
Via Giuria 1, 10125 Torino, Italy
+39 011 6707203

**Comment by goanpeca** [comment]
@abarto did anaconda-client start saving yaml files with a different format or parser ?

**Comment by goanpeca** [comment]
@mainaezio could you manually remove this file `/Users/maina/Library/Application Support/binstar/config.yaml` and try again? That should solve the issue.

Also, after doing that and restarting navigator could you share its content again ?

**Comment by mainaezio** [comment]
It solved the problem.

The file has not been recreated.


$more  "/Users/maina/Library/Application Support/binstar/config.yaml"
/Users/maina/Library/Application Support/binstar/config.yaml: No such file
or directory





> @mainaezio could you manually remove this file
> `/Users/maina/Library/Application Support/binstar/config.yaml` and try
> again? That should solve the issue.
>
> Also, after doing that and restarting navigator could you share its
> content again ?
>
> --
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/ContinuumIO/anaconda-issues/issues/8605#issuecomment-367029224


Ezio Maina
Dip. di Fisica Teorica, Universita' di Torino
INFN, Sez di Torino
Via Giuria 1, 10125 Torino, Italy
+39 011 6707203
