### ISSUE TITLE
Anaconda 3.6 Install error

### ISSUE THREAD

**Issue by kybudman** [ContinuumIO/anaconda-issues#8607]
### Actual Behavior

Fails to initialize.
### Expected Behavior
Initialization Anaconda/Python 3.6

I should get Python
### Steps to Reproduce
Click on Anaconda Navigator in start menu

##### Anaconda or Miniconda version:
Python 3.6
##### Operating System:
Windows10 64 bit
##### `conda info`

```
Navigator Error
An unexpected error occurred on Navigator start-up
Filed to initialize
Report
Please report this issue in the anaconda issue tracker

Main Error
could not determine a constructor for the tag 'tag:yaml.org,2002:python/unicode'
  in "C:\Users\Bud\AppData\Local\ContinuumIO\binstar\config.yaml", line 1, column 1
Traceback
Traceback (most recent call last):
  File "C:\Users\Bud\Anaconda3_6\lib\site-packages\anaconda_navigator\exceptions.py", line 75, in exception_handler
    return_value = func(*args, **kwargs)
  File "C:\Users\Bud\Anaconda3_6\lib\site-packages\anaconda_navigator\app\start.py", line 120, in start_app
    window = run_app(splash)
  File "C:\Users\Bud\Anaconda3_6\lib\site-packages\anaconda_navigator\app\start.py", line 63, in run_app
    window = MainWindow(splash=splash)
  File "C:\Users\Bud\Anaconda3_6\lib\site-packages\anaconda_navigator\widgets\main_window.py", line 163, in __init__
    self.api = AnacondaAPI()
  File "C:\Users\Bud\Anaconda3_6\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 2004, in AnacondaAPI
    ANACONDA_API = _AnacondaAPI()
  File "C:\Users\Bud\Anaconda3_6\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 89, in __init__
    self._client_api = ClientAPI()
  File "C:\Users\Bud\Anaconda3_6\lib\site-packages\anaconda_navigator\api\client_api.py", line 612, in ClientAPI
    CLIENT_API = _ClientAPI()
  File "C:\Users\Bud\Anaconda3_6\lib\site-packages\anaconda_navigator\api\client_api.py", line 82, in __init__
    log_level=logging.NOTSET
  File "C:\Users\Bud\Anaconda3_6\lib\site-packages\binstar_client\utils\config.py", line 96, in get_server_api
    config = get_config(remote_site=site)
  File "C:\Users\Bud\Anaconda3_6\lib\site-packages\binstar_client\utils\config.py", line 229, in get_config
    file_configs = load_file_configs(SEARCH_PATH)
  File "C:\Users\Bud\Anaconda3_6\lib\site-packages\binstar_client\utils\config.py", line 223, in load_file_configs
    raw_data = collections.OrderedDict(kv for kv in itertools.chain.from_iterable(load_paths))
  File "C:\Users\Bud\Anaconda3_6\lib\site-packages\binstar_client\utils\config.py", line 223, in 
    raw_data = collections.OrderedDict(kv for kv in itertools.chain.from_iterable(load_paths))
  File "C:\Users\Bud\Anaconda3_6\lib\site-packages\binstar_client\utils\config.py", line 203, in _dir_yaml_loader
    yield filepath, load_config(filepath)
  File "C:\Users\Bud\Anaconda3_6\lib\site-packages\binstar_client\utils\config.py", line 187, in load_config
    data = yaml_load(fd)
  File "C:\Users\Bud\Anaconda3_6\lib\site-packages\binstar_client\utils\yaml.py", line 9, in yaml_load
    return safe_load(stream)
  File "C:\Users\Bud\Anaconda3_6\lib\site-packages\yaml\__init__.py", line 94, in safe_load
    return load(stream, SafeLoader)
  File "C:\Users\Bud\Anaconda3_6\lib\site-packages\yaml\__init__.py", line 72, in load
    return loader.get_single_data()
  File "C:\Users\Bud\Anaconda3_6\lib\site-packages\yaml\constructor.py", line 37, in get_single_data
    return self.construct_document(node)
  File "C:\Users\Bud\Anaconda3_6\lib\site-packages\yaml\constructor.py", line 46, in construct_document
    for dummy in generator:
  File "C:\Users\Bud\Anaconda3_6\lib\site-packages\yaml\constructor.py", line 398, in construct_yaml_map
    value = self.construct_mapping(node)
  File "C:\Users\Bud\Anaconda3_6\lib\site-packages\yaml\constructor.py", line 204, in construct_mapping
    return super().construct_mapping(node, deep=deep)
  File "C:\Users\Bud\Anaconda3_6\lib\site-packages\yaml\constructor.py", line 125, in construct_mapping
    key = self.construct_object(key_node, deep=deep)
  File "C:\Users\Bud\Anaconda3_6\lib\site-packages\yaml\constructor.py", line 86, in construct_object
    data = constructor(self, node)
  File "C:\Users\Bud\Anaconda3_6\lib\site-packages\yaml\constructor.py", line 414, in construct_undefined
    node.start_mark)
yaml.constructor.ConstructorError: could not determine a constructor for the tag 'tag:yaml.org,2002:python/unicode'
  in "C:\Users\Bud\AppData\Local\ContinuumIO\binstar\config.yaml", line 1, column 1

```

##### `conda list --show-channel-urls`

```

```
M. B. Fields, Jr.
thewebcastguru@live.com

**Comment by goanpeca** [comment]
@kybudman there seems to be some corruption of this file

`C:\Users\Bud\AppData\Local\ContinuumIO\binstar\config.yaml` could you please attach the contents so that we can take a look at what is wrong with it?

**Comment by dgaultie** [comment]
Hi, 
I have got the same issue, but on Mac OS High Sierra, problem see below 👍 
Navigator Error

An unexpected error occurred on Navigator start-up

Report

Please report this issue in the anaconda issue tracker

Main Error

could not determine a constructor for the tag 'tag:yaml.org,2002:python/unicode'
  in "/Users/Didier/Library/Application Support/binstar/config.yaml", line 1, column 1
Traceback

Traceback (most recent call last):
  File "/Users/Didier/anaconda3/lib/python3.6/site-packages/anaconda_navigator/exceptions.py", line 75, in exception_handler
    return_value = func(*args, **kwargs)
  File "/Users/Didier/anaconda3/lib/python3.6/site-packages/anaconda_navigator/app/start.py", line 120, in start_app
    window = run_app(splash)
  File "/Users/Didier/anaconda3/lib/python3.6/site-packages/anaconda_navigator/app/start.py", line 63, in run_app
    window = MainWindow(splash=splash)
  File "/Users/Didier/anaconda3/lib/python3.6/site-packages/anaconda_navigator/widgets/main_window.py", line 163, in __init__
    self.api = AnacondaAPI()
  File "/Users/Didier/anaconda3/lib/python3.6/site-packages/anaconda_navigator/api/anaconda_api.py", line 2004, in AnacondaAPI
    ANACONDA_API = _AnacondaAPI()
  File "/Users/Didier/anaconda3/lib/python3.6/site-packages/anaconda_navigator/api/anaconda_api.py", line 89, in __init__
    self._client_api = ClientAPI()
  File "/Users/Didier/anaconda3/lib/python3.6/site-packages/anaconda_navigator/api/client_api.py", line 612, in ClientAPI
    CLIENT_API = _ClientAPI()
  File "/Users/Didier/anaconda3/lib/python3.6/site-packages/anaconda_navigator/api/client_api.py", line 82, in __init__
    log_level=logging.NOTSET
  File "/Users/Didier/anaconda3/lib/python3.6/site-packages/binstar_client/utils/config.py", line 96, in get_server_api
    config = get_config(remote_site=site)
  File "/Users/Didier/anaconda3/lib/python3.6/site-packages/binstar_client/utils/config.py", line 229, in get_config
    file_configs = load_file_configs(SEARCH_PATH)
  File "/Users/Didier/anaconda3/lib/python3.6/site-packages/binstar_client/utils/config.py", line 223, in load_file_configs
    raw_data = collections.OrderedDict(kv for kv in itertools.chain.from_iterable(load_paths))
  File "/Users/Didier/anaconda3/lib/python3.6/site-packages/binstar_client/utils/config.py", line 223, in 
    raw_data = collections.OrderedDict(kv for kv in itertools.chain.from_iterable(load_paths))
  File "/Users/Didier/anaconda3/lib/python3.6/site-packages/binstar_client/utils/config.py", line 203, in _dir_yaml_loader
    yield filepath, load_config(filepath)
  File "/Users/Didier/anaconda3/lib/python3.6/site-packages/binstar_client/utils/config.py", line 187, in load_config
    data = yaml_load(fd)
  File "/Users/Didier/anaconda3/lib/python3.6/site-packages/binstar_client/utils/yaml.py", line 9, in yaml_load
    return safe_load(stream)
  File "/Users/Didier/anaconda3/lib/python3.6/site-packages/yaml/__init__.py", line 94, in safe_load
    return load(stream, SafeLoader)
  File "/Users/Didier/anaconda3/lib/python3.6/site-packages/yaml/__init__.py", line 72, in load
    return loader.get_single_data()
  File "/Users/Didier/anaconda3/lib/python3.6/site-packages/yaml/constructor.py", line 37, in get_single_data
    return self.construct_document(node)
  File "/Users/Didier/anaconda3/lib/python3.6/site-packages/yaml/constructor.py", line 46, in construct_document
    for dummy in generator:
  File "/Users/Didier/anaconda3/lib/python3.6/site-packages/yaml/constructor.py", line 398, in construct_yaml_map
    value = self.construct_mapping(node)
  File "/Users/Didier/anaconda3/lib/python3.6/site-packages/yaml/constructor.py", line 204, in construct_mapping
    return super().construct_mapping(node, deep=deep)
  File "/Users/Didier/anaconda3/lib/python3.6/site-packages/yaml/constructor.py", line 125, in construct_mapping
    key = self.construct_object(key_node, deep=deep)
  File "/Users/Didier/anaconda3/lib/python3.6/site-packages/yaml/constructor.py", line 86, in construct_object
    data = constructor(self, node)
  File "/Users/Didier/anaconda3/lib/python3.6/site-packages/yaml/constructor.py", line 414, in construct_undefined
    node.start_mark)
yaml.constructor.ConstructorError: could not determine a constructor for the tag 'tag:yaml.org,2002:python/unicode'
  in "/Users/Didier/Library/Application Support/binstar/config.yaml", line 1, column 1

**Comment by MackT** [comment]
Hi, I get the same error when I try  yo open the navigator. The content of the config.yaml file is

!!python/unicode 'sites':
  !!python/unicode 'alpha': {!!python/unicode 'url': !!python/unicode 'http://api.alpha.binstar.org'}
  !!python/unicode 'binstar': {!!python/unicode 'url': !!python/unicode 'https://api.anaconda.org'}
url: https://api.anaconda.org

**Comment by jingyuzhang3** [comment]
I have the same error.

Navigator Error

An unexpected error occurred on Navigator start-up

Report

Please report this issue in the anaconda issue tracker

Main Error

could not determine a constructor for the tag 'tag:yaml.org,2002:python/unicode'
  in "/Users/jingyuzhang/Library/Application Support/binstar/config.yaml", line 1, column 1
Traceback

Traceback (most recent call last):
  File "/anaconda3/lib/python3.6/site-packages/anaconda_navigator/exceptions.py", line 75, in exception_handler
    return_value = func(*args, **kwargs)
  File "/anaconda3/lib/python3.6/site-packages/anaconda_navigator/app/start.py", line 120, in start_app
    window = run_app(splash)
  File "/anaconda3/lib/python3.6/site-packages/anaconda_navigator/app/start.py", line 63, in run_app
    window = MainWindow(splash=splash)
  File "/anaconda3/lib/python3.6/site-packages/anaconda_navigator/widgets/main_window.py", line 163, in __init__
    self.api = AnacondaAPI()
  File "/anaconda3/lib/python3.6/site-packages/anaconda_navigator/api/anaconda_api.py", line 2004, in AnacondaAPI
    ANACONDA_API = _AnacondaAPI()
  File "/anaconda3/lib/python3.6/site-packages/anaconda_navigator/api/anaconda_api.py", line 89, in __init__
    self._client_api = ClientAPI()
  File "/anaconda3/lib/python3.6/site-packages/anaconda_navigator/api/client_api.py", line 612, in ClientAPI
    CLIENT_API = _ClientAPI()
  File "/anaconda3/lib/python3.6/site-packages/anaconda_navigator/api/client_api.py", line 82, in __init__
    log_level=logging.NOTSET
  File "/anaconda3/lib/python3.6/site-packages/binstar_client/utils/config.py", line 96, in get_server_api
    config = get_config(remote_site=site)
  File "/anaconda3/lib/python3.6/site-packages/binstar_client/utils/config.py", line 229, in get_config
    file_configs = load_file_configs(SEARCH_PATH)
  File "/anaconda3/lib/python3.6/site-packages/binstar_client/utils/config.py", line 223, in load_file_configs
    raw_data = collections.OrderedDict(kv for kv in itertools.chain.from_iterable(load_paths))
  File "/anaconda3/lib/python3.6/site-packages/binstar_client/utils/config.py", line 223, in 
    raw_data = collections.OrderedDict(kv for kv in itertools.chain.from_iterable(load_paths))
  File "/anaconda3/lib/python3.6/site-packages/binstar_client/utils/config.py", line 203, in _dir_yaml_loader
    yield filepath, load_config(filepath)
  File "/anaconda3/lib/python3.6/site-packages/binstar_client/utils/config.py", line 187, in load_config
    data = yaml_load(fd)
  File "/anaconda3/lib/python3.6/site-packages/binstar_client/utils/yaml.py", line 9, in yaml_load
    return safe_load(stream)
  File "/anaconda3/lib/python3.6/site-packages/yaml/__init__.py", line 94, in safe_load
    return load(stream, SafeLoader)
  File "/anaconda3/lib/python3.6/site-packages/yaml/__init__.py", line 72, in load
    return loader.get_single_data()
  File "/anaconda3/lib/python3.6/site-packages/yaml/constructor.py", line 37, in get_single_data
    return self.construct_document(node)
  File "/anaconda3/lib/python3.6/site-packages/yaml/constructor.py", line 46, in construct_document
    for dummy in generator:
  File "/anaconda3/lib/python3.6/site-packages/yaml/constructor.py", line 398, in construct_yaml_map
    value = self.construct_mapping(node)
  File "/anaconda3/lib/python3.6/site-packages/yaml/constructor.py", line 204, in construct_mapping
    return super().construct_mapping(node, deep=deep)
  File "/anaconda3/lib/python3.6/site-packages/yaml/constructor.py", line 125, in construct_mapping
    key = self.construct_object(key_node, deep=deep)
  File "/anaconda3/lib/python3.6/site-packages/yaml/constructor.py", line 86, in construct_object
    data = constructor(self, node)
  File "/anaconda3/lib/python3.6/site-packages/yaml/constructor.py", line 414, in construct_undefined
    node.start_mark)
yaml.constructor.ConstructorError: could not determine a constructor for the tag 'tag:yaml.org,2002:python/unicode'
  in "/Users/jingyuzhang/Library/Application Support/binstar/config.yaml", line 1, column 1
