### ISSUE TITLE
Update to Anaconda 4.1 Fails - conda update removed pycosat

### ISSUE THREAD

**Issue by navneethc** [ContinuumIO/anaconda-issues#862]
Output from when I tried to update to Anaconda 4.1 (I think it's self-explanatory). Not sure if I should be installing pycosat again.

It appears that pretty much any conda/anaconda command is also affected due to this. (Further examples below.)

Windows 7 64-bit (Please let me know if you require any other information.)

I have also opened an issue on conda's Issue tracker: https://github.com/conda/conda/issues/2913

```
C:\Users\chandrav\AppData\Local\Continuum\Anaconda>conda update conda
Fetching package metadata .......
Solving package specifications: ..........

Package plan for installation in environment C:\Users\chandrav\AppData\Local\Continuum\Anaconda:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    conda-4.1.4                |           py27_0         243 KB

The following packages will be REMOVED:

    pycosat: 0.6.1-py27_0 <unknown>

The following packages will be UPDATED:

    conda:   4.1.2-py27_0           --> 4.1.4-py27_0

Proceed ([y]/n)?

Fetching packages ...
conda-4.1.4-py 100% |###############################| Time: 0:00:01 190.57 kB/s
Extracting packages ...
[      COMPLETE      ]|##################################################| 100%
Unlinking packages ...
[      COMPLETE      ]|##################################################| 100%
Linking packages ...
[      COMPLETE      ]|##################################################| 100%

C:\Users\chandrav\AppData\Local\Continuum\Anaconda>conda update anaconda
Traceback (most recent call last):
  File "C:\Users\chandrav\AppData\Local\Continuum\Anaconda\Scripts\conda-script.py", line 5, in <module>
    sys.exit(main())
  File "C:\Users\chandrav\AppData\Local\Continuum\Anaconda\lib\site-packages\conda\cli\main.py", line 61, in main
    from conda.cli import conda_argparse
  File "C:\Users\chandrav\AppData\Local\Continuum\Anaconda\lib\site-packages\conda\cli\conda_argparse.py", line 15, in <module>
    from .common import add_parser_help
  File "C:\Users\chandrav\AppData\Local\Continuum\Anaconda\lib\site-packages\conda\cli\common.py", line 16, in <module>
    from ..resolve import MatchSpec
  File "C:\Users\chandrav\AppData\Local\Continuum\Anaconda\lib\site-packages\conda\resolve.py", line 12, in <module>
    from .logic import minimal_unsatisfiable_subset, Clauses
  File "C:\Users\chandrav\AppData\Local\Continuum\Anaconda\lib\site-packages\conda\logic.py", line 31, in <module>
    import pycosat
ImportError: No module named pycosat

C:\Users\chandrav\AppData\Local\Continuum\Anaconda>
```

**General conda commands**

```
C:\Users\chandrav\AppData\Local\Continuum\Anaconda>activate py3env
Traceback (most recent call last):
  File "C:\Users\chandrav\AppData\Local\Continuum\Anaconda\Scripts\conda-script.py", line 5, in <module>
    sys.exit(main())
  File "C:\Users\chandrav\AppData\Local\Continuum\Anaconda\lib\site-packages\conda\cli\main.py", line 48, in main
    activate.main()
  File "C:\Users\chandrav\AppData\Local\Continuum\Anaconda\lib\site-packages\conda\cli\activate.py", line 130, in main
    prefix = prefix_from_arg(sys.argv[3], shelldict=shelldict)
  File "C:\Users\chandrav\AppData\Local\Continuum\Anaconda\lib\site-packages\conda\cli\activate.py", line 46, in prefix_from_arg
    from conda.cli.common import find_prefix_name
  File "C:\Users\chandrav\AppData\Local\Continuum\Anaconda\lib\site-packages\conda\cli\common.py", line 16, in <module>
    from ..resolve import MatchSpec
  File "C:\Users\chandrav\AppData\Local\Continuum\Anaconda\lib\site-packages\conda\resolve.py", line 12, in <module>
    from .logic import minimal_unsatisfiable_subset, Clauses
  File "C:\Users\chandrav\AppData\Local\Continuum\Anaconda\lib\site-packages\conda\logic.py", line 31, in <module>
    import pycosat
ImportError: No module named pycosat

C:\Users\chandrav\AppData\Local\Continuum\Anaconda>conda info envs
Traceback (most recent call last):
  File "C:\Users\chandrav\AppData\Local\Continuum\Anaconda\Scripts\conda-script.py", line 5, in <module>
    sys.exit(main())
  File "C:\Users\chandrav\AppData\Local\Continuum\Anaconda\lib\site-packages\conda\cli\main.py", line 61, in main
    from conda.cli import conda_argparse
  File "C:\Users\chandrav\AppData\Local\Continuum\Anaconda\lib\site-packages\conda\cli\conda_argparse.py", line 15, in <module>
    from .common import add_parser_help
  File "C:\Users\chandrav\AppData\Local\Continuum\Anaconda\lib\site-packages\conda\cli\common.py", line 16, in <module>
    from ..resolve import MatchSpec
  File "C:\Users\chandrav\AppData\Local\Continuum\Anaconda\lib\site-packages\conda\resolve.py", line 12, in <module>
    from .logic import minimal_unsatisfiable_subset, Clauses
  File "C:\Users\chandrav\AppData\Local\Continuum\Anaconda\lib\site-packages\conda\logic.py", line 31, in <module>
    import pycosat
ImportError: No module named pycosat

C:\Users\chandrav\AppData\Local\Continuum\Anaconda>
```

**Comment by ilanschnell** [comment]
Thanks for also opening https://github.com/conda/conda/issues/2913.
This is clearly a conda issue.
