### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by josefazimov** [ContinuumIO/anaconda-issues#8627]
## Main error
Application <b>notebook</b> launch may have produced errors.
## Traceback
```
Failed to import the site module
Traceback (most recent call last):
  File "/home/ze/anaconda3/envs/ze_env36/lib/python3.6/site.py", line 544, in <module>
    main()
  File "/home/ze/anaconda3/envs/ze_env36/lib/python3.6/site.py", line 530, in main
    known_paths = addusersitepackages(known_paths)
  File "/home/ze/anaconda3/envs/ze_env36/lib/python3.6/site.py", line 282, in addusersitepackages
    user_site = getusersitepackages()
  File "/home/ze/anaconda3/envs/ze_env36/lib/python3.6/site.py", line 258, in getusersitepackages
    user_base = getuserbase() # this will also set USER_BASE
  File "/home/ze/anaconda3/envs/ze_env36/lib/python3.6/site.py", line 248, in getuserbase
    USER_BASE = get_config_var('userbase')
  File "/home/ze/anaconda3/envs/ze_env36/lib/python3.6/sysconfig.py", line 601, in get_config_var
    return get_config_vars().get(name)
  File "/home/ze/anaconda3/envs/ze_env36/lib/python3.6/sysconfig.py", line 550, in get_config_vars
    _init_posix(_CONFIG_VARS)
  File "/home/ze/anaconda3/envs/ze_env36/lib/python3.6/sysconfig.py", line 421, in _init_posix
    _temp = __import__(name, globals(), locals(), ['build_time_vars'], 0)
ModuleNotFoundError: No module named '_sysconfigdata_x86_64_conda_cos6_linux_gnu'

```
## System information
```
python: 3.6.4
language: pt_BR
os: Linux;4.4.0-112-generic;#135-Ubuntu SMP Fri Jan 19 11:48:36 UTC 2018;x86_64;x86_64
version: 1.6.2
platform: linux-64
qt: 5.6.2
pyqt: 5.6.0
conda: 4.4.10
```

**Comment by goanpeca** [comment]
Please update to the latest python

Open the terminal and type

```
conda update python
```

**Comment by mingwandroid** [comment]
I should clarify here you likely need to update the python in your base/root env.

**Comment by goanpeca** [comment]
Open the terminal and type

```
source activate root
conda update python
```
