### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by RaulCanay** [ContinuumIO/anaconda-issues#8636]
## Main error
Application <b>orange3</b> launch may have produced errors.
## Traceback
```
Traceback (most recent call last):
  File "C:\Users\Raul\Anaconda3\lib\site-packages\Orange\canvas\application\canvasmain.py", line 26, in <module>
    from AnyQt.QtWebEngineWidgets import QWebEngineView
  File "C:\Users\Raul\Anaconda3\lib\site-packages\AnyQt\QtWebEngineWidgets.py", line 4, in <module>
    from PyQt5.QtWebEngineWidgets import *
ModuleNotFoundError: No module named 'PyQt5.QtWebEngineWidgets'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Raul\Anaconda3\Scripts\orange-canvas-script.py", line 3, in <module>
    import Orange.canvas.__main__
  File "C:\Users\Raul\Anaconda3\lib\site-packages\Orange\canvas\__main__.py", line 26, in <module>
    from Orange.canvas.application.canvasmain import CanvasMainWindow
  File "C:\Users\Raul\Anaconda3\lib\site-packages\Orange\canvas\application\canvasmain.py", line 29, in <module>
    from AnyQt.QtWebKitWidgets import QWebView
  File "C:\Users\Raul\Anaconda3\lib\site-packages\AnyQt\QtWebKitWidgets.py", line 14, in <module>
    from PyQt5.QtWebKitWidgets import *
ImportError: DLL load failed: No se puede encontrar el módulo especificado.

```
## System information
```
python: 3.6.1
language: es_ES
os: Windows;10;10.0.16299;AMD64;Intel64 Family 6 Model 78 Stepping 3, GenuineIntel
version: 1.6.2
platform: win-64
qt: 5.6.2
pyqt: 5.6.0
conda: 4.3.34
```

**Comment by goanpeca** [comment]
Please remember to update to the latest version of Navigator and Qt to include
the latest fixes.

Open a terminal (on Linux or Mac) or the Anaconda Command Prompt (on windows)
and type:

```
conda update conda
conda update qt
conda update anaconda-navigator
conda update navigator-updater
```
