### ISSUE TITLE
Navigator Error - an unexpected error occurred on Navigator start-up

### ISSUE THREAD

**Issue by StevenEY** [ContinuumIO/anaconda-issues#8637]
This appears after I try to open Navigator:

```
Traceback (most recent call last):
  File "C:\Users\2022547\AppData\Local\Continuum\anaconda3\lib\site-packages\anaconda_navigator\exceptions.py", line 75, in exception_handler
    return_value = func(*args, **kwargs)
  File "C:\Users\2022547\AppData\Local\Continuum\anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 120, in start_app
    window = run_app(splash)
  File "C:\Users\2022547\AppData\Local\Continuum\anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 63, in run_app
    window = MainWindow(splash=splash)
  File "C:\Users\2022547\AppData\Local\Continuum\anaconda3\lib\site-packages\anaconda_navigator\widgets\main_window.py", line 163, in __init__
    self.api = AnacondaAPI()
  File "C:\Users\2022547\AppData\Local\Continuum\anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 2004, in AnacondaAPI
    ANACONDA_API = _AnacondaAPI()
  File "C:\Users\2022547\AppData\Local\Continuum\anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 88, in __init__
    self._conda_api = CondaAPI()
  File "C:\Users\2022547\AppData\Local\Continuum\anaconda3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 1690, in CondaAPI
    CONDA_API = _CondaAPI()
  File "C:\Users\2022547\AppData\Local\Continuum\anaconda3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 347, in __init__
    self.set_conda_prefix()
  File "C:\Users\2022547\AppData\Local\Continuum\anaconda3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 496, in set_conda_prefix
    self.ROOT_PREFIX = info['root_prefix']
TypeError: byte indices must be integers or slices, not str
```

This appeared when I opened Anaconda Prompt:

```
# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "C:\Users\2022547\AppData\Local\Continuum\anaconda3\lib\site-packages\conda\cli\main.py", line 110, in main
        from ..activate import main as activator_main
      File "C:\Users\2022547\AppData\Local\Continuum\anaconda3\lib\site-packages\conda\activate.py", line 12, in <module>
        context.__init__()  # oOn import, context does not include SEARCH_PATH.
This line fixes that.
      File "C:\Users\2022547\AppData\Local\Continuum\anaconda3\lib\site-packages\conda\base\context.py", line 234, in __init__
        argparse_args=argparse_args)
      File "C:\Users\2022547\AppData\Local\Continuum\anaconda3\lib\site-packages\conda\common\configuration.py", line 723, in __init__
        self._set_search_path(search_path)
      File "C:\Users\2022547\AppData\Local\Continuum\anaconda3\lib\site-packages\conda\common\configuration.py", line 729, in _set_search_path
        self._set_raw_data(load_file_configs(search_path))
      File "C:\Users\2022547\AppData\Local\Continuum\anaconda3\lib\site-packages\conda\common\configuration.py", line 371, in load_file_configs
        raw_data = odict(kv for kv in chain.from_iterable(load_paths))
      File "C:\Users\2022547\AppData\Local\Continuum\anaconda3\lib\site-packages\conda\common\configuration.py", line 371, in <genexpr>
        raw_data = odict(kv for kv in chain.from_iterable(load_paths))
      File "C:\Users\2022547\AppData\Local\Continuum\anaconda3\lib\site-packages\conda\common\configuration.py", line 346, in _file_yaml_loader
        yield fullpath, YamlRawParameter.make_raw_parameters_from_file(fullpath)

      File "C:\Users\2022547\AppData\Local\Continuum\anaconda3\lib\site-packages\conda\common\configuration.py", line 334, in make_raw_parameters_from_file
        ruamel_yaml = yaml_load(fh)
      File "C:\Users\2022547\AppData\Local\Continuum\anaconda3\lib\site-packages\conda\common\serialize.py", line 54, in yaml_load
        return yaml.load(string, Loader=yaml.RoundTripLoader, version="1.2")
      File "C:\Users\2022547\AppData\Local\Continuum\anaconda3\lib\site-packages\ruamel_yaml\main.py", line 639, in load
        return loader._constructor.get_single_data()  # type: ignore
      File "C:\Users\2022547\AppData\Local\Continuum\anaconda3\lib\site-packages\ruamel_yaml\constructor.py", line 102, in get_single_data
        node = self.composer.get_single_node()
      File "C:\Users\2022547\AppData\Local\Continuum\anaconda3\lib\site-packages\ruamel_yaml\composer.py", line 75, in get_single_node
        document = self.compose_document()
      File "C:\Users\2022547\AppData\Local\Continuum\anaconda3\lib\site-packages\ruamel_yaml\composer.py", line 96, in compose_document
        node = self.compose_node(None, None)
      File "C:\Users\2022547\AppData\Local\Continuum\anaconda3\lib\site-packages\ruamel_yaml\composer.py", line 132, in compose_node
        node = self.compose_mapping_node(anchor)
      File "C:\Users\2022547\AppData\Local\Continuum\anaconda3\lib\site-packages\ruamel_yaml\composer.py", line 187, in compose_mapping_node
        while not self.parser.check_event(MappingEndEvent):
      File "C:\Users\2022547\AppData\Local\Continuum\anaconda3\lib\site-packages\ruamel_yaml\parser.py", line 144, in check_event
        self.current_event = self.state()
      File "C:\Users\2022547\AppData\Local\Continuum\anaconda3\lib\site-packages\ruamel_yaml\parser.py", line 561, in parse_block_mapping_key
        token.start_mark)
    ruamel_yaml.parser.ParserError: while parsing a block mapping
      in "C:\Users\2022547\.condarc", line 1, column 1
    expected <block end>, but found '<block mapping start>'
      in "C:\Users\2022547\.condarc", line 5, column 2

`$ C:\Users\2022547\AppData\Local\Continuum\anaconda3\Scripts\conda shell.cmd.exe activate activate C:\Users\2022547\AppData\Local\Continuum\anaconda3`

  environment variables:
                 CIO_TEST=<not set>
               CONDA_ROOT=C:\Users\2022547\AppData\Local\Continuum\anaconda3
                 HOMEPATH=\Users\2022547
                     PATH=C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\Sys
                          tem32\WindowsPowerShell\v1.0\;C:\Program Files
                          (x86)\Java\jre7\bin\;C:\Program Files (x86)\Vodafone\Vodafone Mobile
                          Broadband\Optimization Client\;C:\Program
                          Files\Intel\WiFi\bin\;C:\Program Files\Common
                          Files\Intel\WirelessCommon\;c:\Program Files (x86)\Microsoft SQL
                          Server\110\Tools\Binn\;c:\Program Files\Microsoft SQL
                          Server\110\Tools\Binn\;c:\Program Files\Microsoft SQL
                          Server\110\DTS\Binn\;C:\Program Files\Microsoft SQL Server\Client
                          SDK\ODBC\110\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL
                          Server\120\Tools\Binn\;C:\Program Files\Microsoft SQL
                          Server\120\Tools\Binn\;C:\Program Files\Microsoft SQLServer\120\DTS\B
                          inn\;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files
                          (x86)\Common Files\Hitachi ID\;C:\Program Files\Common Files\Hitachi I
                          D\;C:\Users\2022547\AppData\Local\Continuum\anaconda3;C:\Users\2022547
                          \AppData\Local\Continuum\anaconda3\Library\mingw-w64\bin;C:\Users\2022
                          547\AppData\Local\Continuum\anaconda3\Library\usr\bin;C:\Users\2022547
                          \AppData\Local\Continuum\anaconda3\Library\bin;C:\Users\2022547\AppDat
                          a\Local\Continuum\anaconda3\Scripts;C:\Users\2022547\AppData\Local\Pro
                          grams\Git\cmd;C:\Users\2022547\Downloads\;C:\Program Files\Microsoft
                          VS Code\bin
             PSMODULEPATH=C:\Windows\system32\WindowsPowerShell\v1.0\Modules\;C:\Program
                          Files\Microsoft Application Virtualization\Client\;c:\Program Files
                          (x86)\Microsoft SQL Server\110\Tools\PowerShell\Modules\;C:\Program
                          Files (x86)\Microsoft SQL Server\120\Tools\PowerShell\Modules\
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>

     active environment : None
       user config file : C:\Users\2022547\.condarc
 populated config files :
          conda version : 4.4.10
    conda-build version : 3.4.1
         python version : 3.6.4.final.0
       base environment : C:\Users\2022547\AppData\Local\Continuum\anaconda3  (writable)
           channel URLs : https://repo.continuum.io/pkgs/main/win-64
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/win-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
          package cache : C:\Users\2022547\AppData\Local\Continuum\anaconda3\pkgs
                          C:\Users\2022547\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\2022547\AppData\Local\Continuum\anaconda3\envs
                          C:\Users\2022547\AppData\Local\conda\conda\envs
                          C:\Users\2022547\.conda\envs
               platform : win-64
             user-agent : conda/4.4.10 requests/2.18.4 CPython/3.6.4 Windows/7 Windows/6.1.7601
          administrator : False
             netrc file : None
           offline mode : False

```

**Comment by StevenEY** [comment]
@goanpeca did you even look at the second part of my post?

When I use Anaconda Prompt or try` conda update ...`, I get an error. 

Besides, I think I have the latest version? (installed Anaconda 5.1 recently)

**Comment by Raphaelozioko** [comment]
Navigator Error

An unexpected error occurred on Navigator start-up

Report

Please report this issue in the anaconda issue tracker  


Main Error

expected str, bytes or os.PathLike object, not NoneType


Traceback

Traceback (most recent call last):
  File "C:\Users\oziorap\AppData\Local\Continuum\anaconda3\lib\site-packages\anaconda_navigator\exceptions.py", line 75, in exception_handler
    return_value = func(*args, **kwargs)
  File "C:\Users\oziorap\AppData\Local\Continuum\anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 151, in start_app
    window = run_app(splash)
  File "C:\Users\oziorap\AppData\Local\Continuum\anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 65, in run_app
    window = MainWindow(splash=splash, tab_project=False)
  File "C:\Users\oziorap\AppData\Local\Continuum\anaconda3\lib\site-packages\anaconda_navigator\widgets\main_window.py", line 168, in __init__
    self.api = AnacondaAPI()
  File "C:\Users\oziorap\AppData\Local\Continuum\anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 2337, in AnacondaAPI
    ANACONDA_API = _AnacondaAPI()
  File "C:\Users\oziorap\AppData\Local\Continuum\anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 89, in __init__
    self._conda_api = CondaAPI()
  File "C:\Users\oziorap\AppData\Local\Continuum\anaconda3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 1767, in CondaAPI
    CONDA_API = _CondaAPI()
  File "C:\Users\oziorap\AppData\Local\Continuum\anaconda3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 353, in __init__
    self.sys_rc_path = join(self.ROOT_PREFIX, '.condarc')
  File "C:\Users\oziorap\AppData\Local\Continuum\anaconda3\lib\ntpath.py", line 76, in join
    path = os.fspath(path)
TypeError: expected str, bytes or os.PathLike object, not NoneType

Please i need assistance with this error message. I need this urgently so i can complete and submit my assignment.
