### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by mahadyRayhan** [ContinuumIO/anaconda-issues#8661]
## Main error
Application <b>jupyterlab</b> launch may have produced errors.
## Traceback
```
[W 12:47:45.483 LabApp] JupyterLab server extension not enabled, manually loading...
[I 12:47:45.491 LabApp] JupyterLab beta preview extension loaded from C:\Users\Nocturnal\Anaconda3\lib\site-packages\jupyterlab
[I 12:47:45.491 LabApp] JupyterLab application directory is C:\Users\Nocturnal\Anaconda3\share\jupyter\lab
Traceback (most recent call last):
  File "C:\Users\Nocturnal\Anaconda3\lib\site-packages\jupyterlab\commands.py", line 321, in __init__
    self._run(['node', 'node-version-check.js'], cwd=HERE, quiet=True)
  File "C:\Users\Nocturnal\Anaconda3\lib\site-packages\jupyterlab\commands.py", line 1165, in _run
    proc = Process(cmd, **kwargs)
  File "C:\Users\Nocturnal\Anaconda3\lib\site-packages\jupyterlab\process.py", line 73, in __init__
    self.proc = self._create_process(cwd=cwd, env=env)
  File "C:\Users\Nocturnal\Anaconda3\lib\site-packages\jupyterlab\process.py", line 131, in _create_process
    cmd[0] = which(cmd[0], kwargs.get('env'))
  File "C:\Users\Nocturnal\Anaconda3\lib\site-packages\jupyterlab\jlpmapp.py", line 59, in which
    raise ValueError(msg)
ValueError: Please install nodejs 5+ and npm before continuing installation. nodejs may be installed using conda or directly from the nodejs website.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Nocturnal\Anaconda3\Scripts\jupyter-lab-script.py", line 10, in <module>
    sys.exit(main())
  File "C:\Users\Nocturnal\Anaconda3\lib\site-packages\jupyter_core\application.py", line 267, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "C:\Users\Nocturnal\Anaconda3\lib\site-packages\traitlets\config\application.py", line 657, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-7>", line 2, in initialize
  File "C:\Users\Nocturnal\Anaconda3\lib\site-packages\traitlets\config\application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "C:\Users\Nocturnal\Anaconda3\lib\site-packages\notebook\notebookapp.py", line 1299, in initialize
    self.init_server_extensions()
  File "C:\Users\Nocturnal\Anaconda3\lib\site-packages\jupyterlab\labapp.py", line 213, in init_server_extensions
    load_jupyter_server_extension(self)
  File "C:\Users\Nocturnal\Anaconda3\lib\site-packages\jupyterlab\extension.py", line 111, in load_jupyter_server_extension
    info = get_app_info(app_dir)
  File "C:\Users\Nocturnal\Anaconda3\lib\site-packages\jupyterlab\commands.py", line 244, in get_app_info
    handler = _AppHandler(app_dir, logger)
  File "C:\Users\Nocturnal\Anaconda3\lib\site-packages\jupyterlab\commands.py", line 324, in __init__
    raise ValueError(msg)
ValueError: Please install nodejs 5+ and npm before continuing installation. nodejs may be installed using conda or directly from the nodejs website.

```
## System information
```
python: 3.6.1
language: en_US
os: Windows;10;10.0.16299;AMD64;Intel64 Family 6 Model 42 Stepping 7, GenuineIntel
version: 1.6.2
platform: win-64
qt: 5.6.2
pyqt: 5.6.0
conda: 4.3.33
```

**Comment by goanpeca** [comment]
@blink1073 ?

**Comment by blink1073** [comment]
This should be fixed in the latest jupyterlab: `conda upgrade jupyterlab`
