### ISSUE TITLE
anaconda navigator are not working on Mac OS  high Sierra

### ISSUE THREAD

**Issue by kalefranz** [ContinuumIO/anaconda-issues#8663]
_From @sravanthbaratam on November 30, 2017 2:13_

$ anaconda-navigator 

Traceback (most recent call last):
  File "/Users/sravanthbaratam/anaconda3/bin/anaconda-navigator", line 11, in <module>
    sys.exit(main())
  File "/Users/sravanthbaratam/anaconda3/lib/python3.6/site-packages/anaconda_navigator/app/main.py", line 125, in main
    from anaconda_navigator.utils.logs import clean_logs
  File "/Users/sravanthbaratam/anaconda3/lib/python3.6/site-packages/anaconda_navigator/utils/logs.py", line 18, in <module>
    from anaconda_navigator.config import (LOG_FILENAME, LOG_FOLDER,
  File "/Users/sravanthbaratam/anaconda3/lib/python3.6/site-packages/anaconda_navigator/config/__init__.py", line 24, in <module>
    from anaconda_navigator.config.main import CONF
  File "/Users/sravanthbaratam/anaconda3/lib/python3.6/site-packages/anaconda_navigator/config/main.py", line 67, in <module>
    raw_mode=True,
  File "/Users/sravanthbaratam/anaconda3/lib/python3.6/site-packages/anaconda_navigator/config/user.py", line 221, in __init__
    self.load_from_ini()
  File "/Users/sravanthbaratam/anaconda3/lib/python3.6/site-packages/anaconda_navigator/config/user.py", line 279, in load_from_ini
    self.read(self.filename(), encoding='utf-8')
  File "/Users/sravanthbaratam/anaconda3/lib/python3.6/configparser.py", line 697, in read
    self._read(fp, filename)
  File "/Users/sravanthbaratam/anaconda3/lib/python3.6/configparser.py", line 1015, in _read
    for lineno, line in enumerate(fp, start=1):
  File "/Users/sravanthbaratam/anaconda3/lib/python3.6/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x81 in position 0: invalid start byte
$ 

_Copied from original issue: conda/conda#6374_

**Comment by goanpeca** [comment]
Please remember to update to the latest version of Navigator to include
the latest fixes.

Open a terminal (on Linux or Mac) or the Anaconda Command Prompt (on windows)
and type:

```
conda update conda
conda update anaconda-navigator
conda update navigator-updater
```

---

Please run on the Terminal or Anaconda prompt:

```
anaconda-navigator --reset
```

And try again

**Comment by sravanthbaratam** [comment]
no change after all those commands
still not working.
![screen shot 2018-02-25 at 8 10 38 am](https://user-images.githubusercontent.com/19935237/36637523-9967acdc-1a03-11e8-831e-27d78f6d9a36.jpg)

**Comment by sravanthbaratam** [comment]
@goanpeca

**Comment by goanpeca** [comment]
@sravanthbaratam please run

```
conda install anaconda-client=1.6.11
```

**Comment by sravanthbaratam** [comment]
@goanpeca 

![screen shot 2018-02-25 at 10 10 25 am](https://user-images.githubusercontent.com/19935237/36638198-39f8cefa-1a14-11e8-842e-d257e5e9f016.jpg)

**Comment by goanpeca** [comment]
Hmm try deleting the `~/.anaconda/navigator` folder and restart?

**Comment by sravanthbaratam** [comment]
@goanpeca 
its working now...
thanks

**Comment by jinisjin12** [comment]
Traceback (most recent call last):
File "/Users/hlee21/anaconda3/lib/python3.6/site-packages/psutil/_psosx.py", line 293, in wrapper
return fun(self, *args, **kwargs)
File "/Users/hlee21/anaconda3/lib/python3.6/site-packages/psutil/_psosx.py", line 356, in cmdline
return cext.proc_cmdline(self.pid)
PermissionError: [Errno 13] Permission denied

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/Users/hlee21/anaconda3/lib/python3.6/site-packages/anaconda_navigator/exceptions.py", line 75, in exception_handler
return_value = func(*args, **kwargs)
File "/Users/hlee21/anaconda3/lib/python3.6/site-packages/anaconda_navigator/app/start.py", line 113, in start_app
if misc.load_pid() is None: # A stale lock might be around
File "/Users/hlee21/anaconda3/lib/python3.6/site-packages/anaconda_navigator/utils/misc.py", line 384, in load_pid
cmds = process.cmdline()
File "/Users/hlee21/anaconda3/lib/python3.6/site-packages/psutil/__init__.py", line 701, in cmdline
return self._proc.cmdline()
File "/Users/hlee21/anaconda3/lib/python3.6/site-packages/psutil/_psosx.py", line 306, in wrapper
raise AccessDenied(self.pid, self._name)
psutil.AccessDenied: psutil.AccessDenied (pid=919)

**Comment by jinisjin12** [comment]
how do I fix this?

**Comment by rpranesh21** [comment]
I deleted the ~/.anaconda/navigator file and ran anaconda-navigator --reset. This seems to work.

**Comment by zoakes** [comment]
Is there a way to get the icon back ? My icon for navigator broke, and I cannot drag the ini back to an icon or anything.
