### ISSUE TITLE
Anaconda Navigator is failing to launch

### ISSUE THREAD

**Issue by dgaultie** [ContinuumIO/anaconda-issues#8672]
### Actual Behavior

An unexpected error occurred on Navigator start-up

### Expected Behavior

It should launch Anaconda Navigator 

##### `conda info`

```

could not determine a constructor for the tag 'tag:yaml.org,2002:python/unicode'
  in "/Users/Didier/Library/Application Support/binstar/config.yaml", line 1, column 1

Traceback

Traceback (most recent call last):
  File "/Users/Didier/anaconda3/lib/python3.6/site-packages/anaconda_navigator/exceptions.py", line 75, in exception_handler
    return_value = func(*args, **kwargs)
  File "/Users/Didier/anaconda3/lib/python3.6/site-packages/anaconda_navigator/app/start.py", line 120, in start_app
    window = run_app(splash)
  File "/Users/Didier/anaconda3/lib/python3.6/site-packages/anaconda_navigator/app/start.py", line 63, in run_app
    window = MainWindow(splash=splash)
  File "/Users/Didier/anaconda3/lib/python3.6/site-packages/anaconda_navigator/widgets/main_window.py", line 163, in __init__
    self.api = AnacondaAPI()
  File "/Users/Didier/anaconda3/lib/python3.6/site-packages/anaconda_navigator/api/anaconda_api.py", line 2004, in AnacondaAPI
    ANACONDA_API = _AnacondaAPI()
  File "/Users/Didier/anaconda3/lib/python3.6/site-packages/anaconda_navigator/api/anaconda_api.py", line 89, in __init__
    self._client_api = ClientAPI()
  File "/Users/Didier/anaconda3/lib/python3.6/site-packages/anaconda_navigator/api/client_api.py", line 612, in ClientAPI
    CLIENT_API = _ClientAPI()
  File "/Users/Didier/anaconda3/lib/python3.6/site-packages/anaconda_navigator/api/client_api.py", line 82, in __init__
    log_level=logging.NOTSET
  File "/Users/Didier/anaconda3/lib/python3.6/site-packages/binstar_client/utils/config.py", line 96, in get_server_api
    config = get_config(remote_site=site)
  File "/Users/Didier/anaconda3/lib/python3.6/site-packages/binstar_client/utils/config.py", line 229, in get_config
    file_configs = load_file_configs(SEARCH_PATH)
  File "/Users/Didier/anaconda3/lib/python3.6/site-packages/binstar_client/utils/config.py", line 223, in load_file_configs
    raw_data = collections.OrderedDict(kv for kv in itertools.chain.from_iterable(load_paths))
  File "/Users/Didier/anaconda3/lib/python3.6/site-packages/binstar_client/utils/config.py", line 223, in 
    raw_data = collections.OrderedDict(kv for kv in itertools.chain.from_iterable(load_paths))
  File "/Users/Didier/anaconda3/lib/python3.6/site-packages/binstar_client/utils/config.py", line 203, in _dir_yaml_loader
    yield filepath, load_config(filepath)
  File "/Users/Didier/anaconda3/lib/python3.6/site-packages/binstar_client/utils/config.py", line 187, in load_config
    data = yaml_load(fd)
  File "/Users/Didier/anaconda3/lib/python3.6/site-packages/binstar_client/utils/yaml.py", line 9, in yaml_load
    return safe_load(stream)
  File "/Users/Didier/anaconda3/lib/python3.6/site-packages/yaml/__init__.py", line 94, in safe_load
    return load(stream, SafeLoader)
  File "/Users/Didier/anaconda3/lib/python3.6/site-packages/yaml/__init__.py", line 72, in load
    return loader.get_single_data()
  File "/Users/Didier/anaconda3/lib/python3.6/site-packages/yaml/constructor.py", line 37, in get_single_data
    return self.construct_document(node)
  File "/Users/Didier/anaconda3/lib/python3.6/site-packages/yaml/constructor.py", line 46, in construct_document
    for dummy in generator:
  File "/Users/Didier/anaconda3/lib/python3.6/site-packages/yaml/constructor.py", line 398, in construct_yaml_map
    value = self.construct_mapping(node)
  File "/Users/Didier/anaconda3/lib/python3.6/site-packages/yaml/constructor.py", line 204, in construct_mapping
    return super().construct_mapping(node, deep=deep)
  File "/Users/Didier/anaconda3/lib/python3.6/site-packages/yaml/constructor.py", line 125, in construct_mapping
    key = self.construct_object(key_node, deep=deep)
  File "/Users/Didier/anaconda3/lib/python3.6/site-packages/yaml/constructor.py", line 86, in construct_object
    data = constructor(self, node)
  File "/Users/Didier/anaconda3/lib/python3.6/site-packages/yaml/constructor.py", line 414, in construct_undefined
    node.start_mark)
yaml.constructor.ConstructorError: could not determine a constructor for the tag 'tag:yaml.org,2002:python/unicode'
  in "/Users/Didier/Library/Application Support/binstar/config.yaml", line 1, column 1

```

##### `conda list --show-channel-urls`

```

```

**Comment by skadoosh12311** [comment]
![Capture](https://user-images.githubusercontent.com/48491071/59965543-467a5500-952d-11e9-9bfb-7f0b916af2aa.PNG)

It shows this error.

**Comment by tschuerhaus** [comment]
None of the above solutions work. Receive same error as above
![error](https://user-images.githubusercontent.com/36141112/60748634-ae289b00-9f44-11e9-8ef9-be22e4731df3.PNG)

**Comment by csoja** [comment]
@tschuerhaus & @skadoosh12311 Looks like your .condarc file has been corrupted.  You'll need to either replace it with a good .condarc file or delete it altogether.

**Comment by tschuerhaus** [comment]
C:\Users\\AppData\Local\Continuum\anaconda3\Scripts> C:\Users\\AppData\Local\Continuum\anaconda3\Scripts\activate

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "C:\Users\\AppData\Local\Continuum\anaconda3\lib\site-packages\conda\cli\main.py", line 97, in main
        from ..activate import main as activator_main
      File "C:\Users\\AppData\Local\Continuum\anaconda3\lib\site-packages\conda\activate.py", line 15, in <module>
        context.__init__()  # oOn import, context does not include SEARCH_PATH. This line fixes that.
      File "C:\Users\AppData\Local\Continuum\anaconda3\lib\site-packages\conda\base\context.py", line 237, in __init__
        argparse_args=argparse_args)
      File "C:\Users\\AppData\Local\Continuum\anaconda3\lib\site-packages\conda\common\configuration.py", line 722, in __init__
        self._set_search_path(search_path)
      File "C:\Users\\AppData\Local\Continuum\anaconda3\lib\site-packages\conda\common\configuration.py", line 728, in _set_search_path
        self._set_raw_data(load_file_configs(search_path))
      File "C:\Users\\AppData\Local\Continuum\anaconda3\lib\site-packages\conda\common\configuration.py", line 369, in load_file_configs
        raw_data = odict(kv for kv in chain.from_iterable(load_paths))
      File "C:\Users\\AppData\Local\Continuum\anaconda3\lib\site-packages\conda\common\configuration.py", line 369, in <genexpr>
        raw_data = odict(kv for kv in chain.from_iterable(load_paths))
      File "C:\Users\\AppData\Local\Continuum\anaconda3\lib\site-packages\conda\common\configuration.py", line 344, in _file_yaml_loader
        yield fullpath, YamlRawParameter.make_raw_parameters_from_file(fullpath)
      File "C:\Users\\AppData\Local\Continuum\anaconda3\lib\site-packages\conda\common\configuration.py", line 332, in make_raw_parameters_from_file
        ruamel_yaml = yaml_load(fh)
      File "C:\Users\\AppData\Local\Continuum\anaconda3\lib\site-packages\conda\common\serialize.py", line 54, in yaml_load
        return yaml.load(string, Loader=yaml.RoundTripLoader, version="1.2")
      File "C:\Users\\AppData\Local\Continuum\anaconda3\lib\site-packages\ruamel_yaml\main.py", line 638, in load
        loader = Loader(stream, version, preserve_quotes=preserve_quotes)
      File "C:\Users\\AppData\Local\Continuum\anaconda3\lib\site-packages\ruamel_yaml\loader.py", line 59, in __init__
        Reader.__init__(self, stream, loader=self)
      File "C:\Users\\AppData\Local\Continuum\anaconda3\lib\site-packages\ruamel_yaml\reader.py", line 80, in __init__
        self.stream = stream  # type: Any  # as .read is called
      File "C:\Users\\AppData\Local\Continuum\anaconda3\lib\site-packages\ruamel_yaml\reader.py", line 125, in stream
        self.determine_encoding()
      File "C:\Users\\AppData\Local\Continuum\anaconda3\lib\site-packages\ruamel_yaml\reader.py", line 180, in determine_encoding
        self.update(1)
      File "C:\Users\\AppData\Local\Continuum\anaconda3\lib\site-packages\ruamel_yaml\reader.py", line 266, in update
        self.check_printable(data)
      File "C:\Users\\AppData\Local\Continuum\anaconda3\lib\site-packages\ruamel_yaml\reader.py", line 233, in check_printable
        'unicode', "special characters are not allowed")
    ruamel_yaml.reader.ReaderError: unacceptable character #x0000: special characters are not allowed
      in "C:\Users\\.condarc", position 0

`$ C:\Users\\AppData\Local\Continuum\anaconda3\Scripts\conda shell.cmd.exe activate activate`

  environment variables:
                 CIO_TEST=<not set>
               CONDA_ROOT=C:\Users\\AppData\Local\Continuum\anaconda3
                 HOMEPATH=\Users\
                     PATH=C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS
                          Client\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WIN
                          DOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files
                          (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program
                          Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files
                          (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program
                          Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program
                          Files\Intel\WiFi\bin\;C:\Program Files\Common
                          Files\Intel\WirelessCommon\;C:\Program Files\dotnet\;C:\Program
                          Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files
                          (x86)\Microsoft SQL Server\Client SDK\ODBC\130\Tools\Binn\;C:\Program
                          Files (x86)\Microsoft SQL Server\140\Tools\Binn\;C:\Program Files
                          (x86)\Microsoft SQL Server\140\DTS\Binn\;C:\Program Files
                          (x86)\Microsoft SQL Server\140\Tools\Binn\ManagementStudio\;C:\Program
                          Files (x86)\Microsoft SQL Server\110\DTS\Binn\;C:\Program Files
                          (x86)\Microsoft SQL Server\120\DTS\Binn\;C:\Program Files
                          (x86)\Microsoft SQL Server\130\DTS\Binn\;C:\Program Files
                          (x86)\Microsoft SQL Server\150\DTS\Binn\;C:\WINDOWS\System32\OpenSSH\;
                          C:\Users\tschuerhaus\AppData\Local\Microsoft\WindowsApps
             PSMODULEPATH=C:\Program Files\WindowsPowerShell\Modules;C:\WINDOWS\system32\Windows
                          PowerShell\v1.0\Modules
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>

     active environment : None
       user config file : C:\Users\\.condarc
 populated config files :
          conda version : 4.5.11
    conda-build version : 3.15.1
         python version : 3.7.0.final.0
       base environment : C:\Users\\AppData\Local\Continuum\anaconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/win-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/win-64
                          https://repo.anaconda.com/pkgs/pro/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\Users\\AppData\Local\Continuum\anaconda3\pkgs
                          C:\Users\\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\\AppData\Local\Continuum\anaconda3\envs
                          C:\Users\\AppData\Local\conda\conda\envs
                          C:\Users\s\.conda\envs
               platform : win-64
             user-agent : conda/4.5.11 requests/2.19.1 CPython/3.7.0 Windows/10 Windows/10.0.17763
          administrator : False
             netrc file : None
           offline mode : False


An unexpected error has occurred. Conda has prepared the above report.
If submitted, this report will be used by core maintainers to improve
future releases of conda.
Would you like conda to send this report to the core maintainers?
[y/N]:

**Comment by tschuerhaus** [comment]
deleting the .condarc file doesn't  solve the problem
