### ISSUE TITLE
navigator crushing under ubuntu 16.04

### ISSUE THREAD

**Issue by leobargigli** [ContinuumIO/anaconda-issues#8676]
### Actual Behavior

anaconda navigator crushes when opened from the launcer of ubuntu 16.04

Navigator Error

An unexpected error occurred on Navigator start-up

Report

Please report this issue in the anaconda issue tracker

Main Error

string indices must be integers, not str
Traceback

Traceback (most recent call last):
  File "/home/leo/anaconda2/lib/python2.7/site-packages/anaconda_navigator/exceptions.py", line 75, in exception_handler
    return_value = func(*args, **kwargs)
  File "/home/leo/anaconda2/lib/python2.7/site-packages/anaconda_navigator/app/start.py", line 115, in start_app
    window = run_app(splash)
  File "/home/leo/anaconda2/lib/python2.7/site-packages/anaconda_navigator/app/start.py", line 58, in run_app
    window = MainWindow(splash=splash)
  File "/home/leo/anaconda2/lib/python2.7/site-packages/anaconda_navigator/widgets/main_window.py", line 160, in __init__
    self.api = AnacondaAPI()
  File "/home/leo/anaconda2/lib/python2.7/site-packages/anaconda_navigator/api/anaconda_api.py", line 1205, in AnacondaAPI
    ANACONDA_API = _AnacondaAPI()
  File "/home/leo/anaconda2/lib/python2.7/site-packages/anaconda_navigator/api/anaconda_api.py", line 65, in __init__
    self._conda_api = CondaAPI()
  File "/home/leo/anaconda2/lib/python2.7/site-packages/anaconda_navigator/api/conda_api.py", line 1622, in CondaAPI
    CONDA_API = _CondaAPI()
  File "/home/leo/anaconda2/lib/python2.7/site-packages/anaconda_navigator/api/conda_api.py", line 340, in __init__
    self.set_conda_prefix()
  File "/home/leo/anaconda2/lib/python2.7/site-packages/anaconda_navigator/api/conda_api.py", line 489, in set_conda_prefix
    self.ROOT_PREFIX = info['root_prefix']
TypeError: string indices must be integers, not str

##### `conda info`

```

```

##### `conda list --show-channel-urls`

```

```

**Comment by goanpeca** [comment]
@leobargigli you must run navigator from a properly activated env

```
conda activate base
anaconda-navigator
```
