### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by Anurag27031994** [ContinuumIO/anaconda-issues#8703]
## Main error
Application <b>spyder</b> launch may have produced errors.
## Traceback
```
Traceback (most recent call last):
  File "D:\Anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 3011, in main
    mainwindow = run_spyder(app, options, args)
  File "D:\Anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 2913, in run_spyder
    main.setup()
  File "D:\Anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 824, in setup
    self.findinfiles = FindInFiles(self)
  File "D:\Anaconda3\lib\site-packages\spyder\plugins\findinfiles.py", line 52, in __init__
    include = self.include_patterns()
  File "D:\Anaconda3\lib\site-packages\spyder\plugins\findinfiles.py", line 105, in include_patterns
    for ext in get_edit_extensions():
  File "D:\Anaconda3\lib\site-packages\spyder\config\utils.py", line 140, in get_edit_extensions
    edit_filetypes = get_edit_filetypes()
  File "D:\Anaconda3\lib\site-packages\spyder\config\utils.py", line 118, in get_edit_filetypes
    pygments_exts = _get_pygments_extensions()
  File "D:\Anaconda3\lib\site-packages\spyder\config\utils.py", line 85, in _get_pygments_extensions
    for lx in lexers.get_all_lexers():
  File "D:\Anaconda3\lib\site-packages\pygments\lexers\__init__.py", line 53, in get_all_lexers
    for lexer in find_plugin_lexers():
  File "D:\Anaconda3\lib\site-packages\pygments\plugin.py", line 53, in find_plugin_lexers
    yield entrypoint.load()
  File "D:\Anaconda3\lib\site-packages\pkg_resources\__init__.py", line 2408, in load
    return self.resolve()
  File "D:\Anaconda3\lib\si

**Comment by goanpeca** [comment]
@Anurag27031994 the error trace is incomplete
