### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by gnudennis** [ContinuumIO/anaconda-issues#8719]
## Main error
Application <b>jupyterlab</b> launch may have produced errors.
## Traceback
```
[I 19:16:59.818 LabApp] [jupyter_nbextensions_configurator] enabled 0.4.0
[W 19:16:59.818 LabApp] JupyterLab server extension not enabled, manually loading...
[I 19:16:59.827 LabApp] JupyterLab beta preview extension loaded from /Users/dennisfan/anaconda/lib/python3.6/site-packages/jupyterlab
[I 19:16:59.827 LabApp] JupyterLab application directory is /Users/dennisfan/anaconda/share/jupyter/lab
Traceback (most recent call last):
  File "/Users/dennisfan/anaconda/lib/python3.6/site-packages/jupyterlab/commands.py", line 321, in __init__
    self._run(['node', 'node-version-check.js'], cwd=HERE, quiet=True)
  File "/Users/dennisfan/anaconda/lib/python3.6/site-packages/jupyterlab/commands.py", line 1165, in _run
    proc = Process(cmd, **kwargs)
  File "/Users/dennisfan/anaconda/lib/python3.6/site-packages/jupyterlab/process.py", line 73, in __init__
    self.proc = self._create_process(cwd=cwd, env=env)
  File "/Users/dennisfan/anaconda/lib/python3.6/site-packages/jupyterlab/process.py", line 131, in _create_process
    cmd[0] = which(cmd[0], kwargs.get('env'))
  File "/Users/dennisfan/anaconda/lib/python3.6/site-packages/jupyterlab/jlpmapp.py", line 59, in which
    raise ValueError(msg)
ValueError: Please install nodejs 5+ and npm before continuing installation. nodejs may be installed using conda or directly from the nodejs website.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/dennisfan/anaconda/bin/jupyter-lab", line 11, in <module>
    sys.exit(main())
  File "/Users/dennisfan/anaconda/lib/python3.6/site-packages/jupyter_core/application.py", line 267, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/Users/dennisfan/anaconda/lib/python3.6/site-packages/traitlets/config/application.py", line 657, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-7>", line 2, in initialize
  File "/Users/dennisfan/anaconda/lib/python3.6/site-packages/traitlets/config/application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "/Users/dennisfan/anaconda/lib/python3.6/site-packages/notebook/notebookapp.py", line 1299, in initialize
    self.init_server_extensions()
  File "/Users/dennisfan/anaconda/lib/python3.6/site-packages/jupyterlab/labapp.py", line 213, in init_server_extensions
    load_jupyter_server_extension(self)
  File "/Users/dennisfan/anaconda/lib/python3.6/site-packages/jupyterlab/extension.py", line 111, in load_jupyter_server_extension
    info = get_app_info(app_dir)
  File "/Users/dennisfan/anaconda/lib/python3.6/site-packages/jupyterlab/commands.py", line 244, in get_app_info
    handler = _AppHandler(app_dir, logger)
  File "/Users/dennisfan/anaconda/lib/python3.6/site-packages/jupyterlab/commands.py", line 324, in __init__
    raise ValueError(msg)
ValueError: Please install nodejs 5+ and npm before continuing installation. nodejs may be installed using conda or directly from the nodejs website.

```
## System information
```
python: 3.6.1
language: en
os: Darwin;16.7.0;Darwin Kernel Version 16.7.0: Mon Nov 13 21:56:25 PST 2017; root:xnu-3789.72.11~1/RELEASE_X86_64;x86_64;i386
version: 1.6.2
platform: osx-64
qt: 5.6.2
pyqt: 5.6.0
conda: 4.3.30
```

**Comment by goanpeca** [comment]
Please update to the latest versions of conda, navigator and jupyterlab.

Please open a terminal and type

```
conda install conda=4.4.11
conda install anaconda-navigator=1.7.0
conda install jupyterlab=0.31.9
```
