### ISSUE TITLE
jupyter notebook won't open after conda update

### ISSUE THREAD

**Issue by vdevgan** [ContinuumIO/anaconda-issues#8720]
Traceback (most recent call last):
File "E:\anaconda\Scripts\jupyter-notebook-script.py", line 6, in 
from notebook.notebookapp import main
File "E:\anaconda\lib\site-packages\notebook\__init__.py", line 25, in 
from .nbextensions import install_nbextension
File "E:\anaconda\lib\site-packages\notebook\nbextensions.py", line 27, in 
from jupyter_core.utils import ensure_dir_exists
ImportError: cannot import name 'ensure_dir_exists'

**Comment by goanpeca** [comment]
@vdevgan pelase run

```
conda upgrade jupyter_core
```
