### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by wyhljbb** [ContinuumIO/anaconda-issues#8768]
## Main error
Application <b>spyder</b> launch may have produced errors.
## Traceback
```
Traceback (most recent call last):
  File "C:\Users\WYH\Anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 3208, in main
    mainwindow = run_spyder(app, options, args)
  File "C:\Users\WYH\Anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 3084, in run_spyder
    main.setup()
  File "C:\Users\WYH\Anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 813, in setup
    from spyder.plugins.console import Console
  File "C:\Users\WYH\Anaconda3\lib\site-packages\spyder\plugins\console.py", line 37, in <module>
    from spyder.widgets.reporterror import SpyderErrorDialog
ModuleNotFoundError: No module named 'spyder.widgets.reporterror'

```
## System information
```
python: 3.6.1
language: en_AU
os: Windows;10;10.0.16299;AMD64;Intel64 Family 6 Model 94 Stepping 3, GenuineIntel
version: 1.6.2
platform: win-64
qt: 5.6.2
pyqt: 5.6.0
conda: 4.3.30
```

**Comment by goanpeca** [comment]
@ccordoba12
