### ISSUE TITLE
Unable to install gdal package

### ISSUE THREAD

**Issue by aquamarine48** [ContinuumIO/anaconda-issues#8785]
Hi, 

I am trying to install the package gdal, but get the following error when run 'conda install -c conda-forge pyhdf gdal'. 

I am very new to Python and Conda so could you please reply with very simple and easy to understand steps?

Thank you very much,

Current conda install:

               platform : win-64
          conda version : 4.2.9
       conda is private : False
      conda-env version : 4.2.9
    conda-build version : 2.0.2
         python version : 3.5.2.final.0
       requests version : 2.11.1
       root environment : C:\Program Files\Anaconda3  (read only)
    default environment : C:\Program Files\Anaconda3
       envs directories : C:\Users\username\.conda\envs
                          C:\Program Files\Anaconda3\envs
          package cache : C:\Users\usename\.conda\envs\.pkgs
                          C:\Program Files\Anaconda3\pkgs
           channel URLs : https://conda.anaconda.org/sean/win-64/
                          https://conda.anaconda.org/sean/noarch/
                          https://repo.continuum.io/pkgs/free/win-64/
                          https://repo.continuum.io/pkgs/free/noarch/
                          https://repo.continuum.io/pkgs/pro/win-64/
                          https://repo.continuum.io/pkgs/pro/noarch/
                          https://repo.continuum.io/pkgs/msys2/win-64/
                          https://repo.continuum.io/pkgs/msys2/noarch/
            config file : C:\Users\username\.condarc
           offline mode : False

`$ C:\Program Files\Anaconda3\Scripts\conda-script.py install -c conda-forge pyh
df gdal`

    Traceback (most recent call last):
      File "C:\Program Files\Anaconda3\lib\site-packages\conda\fetch.py", line 1
12, in fetch_repodata
        timeout=(3.05, 60))
      File "C:\Program Files\Anaconda3\lib\site-packages\requests\sessions.py",
line 488, in get
        return self.request('GET', url, **kwargs)
      File "C:\Program Files\Anaconda3\lib\site-packages\requests\sessions.py",
line 475, in request
        resp = self.send(prep, **send_kwargs)
      File "C:\Program Files\Anaconda3\lib\site-packages\requests\sessions.py",
line 596, in send
        r = adapter.send(request, **kwargs)
      File "C:\Program Files\Anaconda3\lib\site-packages\requests\adapters.py",
line 390, in send
        conn = self.get_connection(request.url, proxies)
      File "C:\Program Files\Anaconda3\lib\site-packages\requests\adapters.py",
line 290, in get_connection
        proxy_manager = self.proxy_manager_for(proxy)
      File "C:\Program Files\Anaconda3\lib\site-packages\requests\adapters.py",
line 194, in proxy_manager_for
        **proxy_kwargs)
      File "C:\Program Files\Anaconda3\lib\site-packages\requests\packages\urlli
b3\poolmanager.py", line 367, in proxy_from_url
        return ProxyManager(proxy_url=url, **kw)
      File "C:\Program Files\Anaconda3\lib\site-packages\requests\packages\urlli
b3\poolmanager.py", line 312, in __init__
        proxy = parse_url(proxy_url)
      File "C:\Program Files\Anaconda3\lib\site-packages\requests\packages\urlli
b3\util\url.py", line 189, in parse_url
        raise LocationParseError(url)
    requests.packages.urllib3.exceptions.LocationParseError: Failed to parse: se
rver:port

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "C:\Program Files\Anaconda3\lib\site-packages\conda\fetch.py", line 2
87, in fetch_index
        repodatas = [(u, f.result()) for u, f in zip(urls, futures)]
      File "C:\Program Files\Anaconda3\lib\site-packages\conda\fetch.py", line 2
87, in <listcomp>
        repodatas = [(u, f.result()) for u, f in zip(urls, futures)]
      File "C:\Program Files\Anaconda3\lib\concurrent\futures\_base.py", line 40
5, in result
        return self.__get_result()
      File "C:\Program Files\Anaconda3\lib\concurrent\futures\_base.py", line 35
7, in __get_result
        raise self._exception
      File "C:\Program Files\Anaconda3\lib\concurrent\futures\thread.py", line 5
5, in run
        result = self.fn(*self.args, **self.kwargs)
      File "C:\Program Files\Anaconda3\lib\site-packages\conda\fetch.py", line 7
0, in func
        res = f(*args, **kwargs)
      File "C:\Program Files\Anaconda3\lib\site-packages\conda\fetch.py", line 1
37, in fetch_repodata
        .format(url, filename, e))
    conda.exceptions.CondaRuntimeError: Runtime error: Invalid index file: https
://conda.anaconda.org/conda-forge/win-64/repodata.json: Failed to parse: server:
port

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "C:\Program Files\Anaconda3\lib\site-packages\conda\fetch.py", line 1
12, in fetch_repodata
        timeout=(3.05, 60))
      File "C:\Program Files\Anaconda3\lib\site-packages\requests\sessions.py",
line 488, in get
        return self.request('GET', url, **kwargs)
      File "C:\Program Files\Anaconda3\lib\site-packages\requests\sessions.py",
line 475, in request
        resp = self.send(prep, **send_kwargs)
      File "C:\Program Files\Anaconda3\lib\site-packages\requests\sessions.py",
line 596, in send
        r = adapter.send(request, **kwargs)
      File "C:\Program Files\Anaconda3\lib\site-packages\requests\adapters.py",
line 390, in send
        conn = self.get_connection(request.url, proxies)
      File "C:\Program Files\Anaconda3\lib\site-packages\requests\adapters.py",
line 290, in get_connection
        proxy_manager = self.proxy_manager_for(proxy)
      File "C:\Program Files\Anaconda3\lib\site-packages\requests\adapters.py",
line 194, in proxy_manager_for
        **proxy_kwargs)
      File "C:\Program Files\Anaconda3\lib\site-packages\requests\packages\urlli
b3\poolmanager.py", line 367, in proxy_from_url
        return ProxyManager(proxy_url=url, **kw)
      File "C:\Program Files\Anaconda3\lib\site-packages\requests\packages\urlli
b3\poolmanager.py", line 312, in __init__
        proxy = parse_url(proxy_url)
      File "C:\Program Files\Anaconda3\lib\site-packages\requests\packages\urlli
b3\util\url.py", line 189, in parse_url
        raise LocationParseError(url)
    requests.packages.urllib3.exceptions.LocationParseError: Failed to parse: se
rver:port

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "C:\Program Files\Anaconda3\lib\site-packages\conda\exceptions.py", l
ine 473, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "C:\Program Files\Anaconda3\lib\site-packages\conda\cli\main.py", lin
e 144, in _main
        exit_code = args.func(args, p)
      File "C:\Program Files\Anaconda3\lib\site-packages\conda\cli\main_install.
py", line 80, in execute
        install(args, parser, 'install')
      File "C:\Program Files\Anaconda3\lib\site-packages\conda\cli\install.py",
line 238, in install
        prefix=prefix)
      File "C:\Program Files\Anaconda3\lib\site-packages\conda\api.py", line 24,
 in get_index
        index = fetch_index(channel_urls, use_cache=use_cache, unknown=unknown)
      File "C:\Program Files\Anaconda3\lib\site-packages\conda\fetch.py", line 2
93, in fetch_index
        for url in urls]
      File "C:\Program Files\Anaconda3\lib\site-packages\conda\fetch.py", line 2
93, in <listcomp>
        for url in urls]
      File "C:\Program Files\Anaconda3\lib\site-packages\conda\fetch.py", line 7
0, in func
        res = f(*args, **kwargs)
      File "C:\Program Files\Anaconda3\lib\site-packages\conda\fetch.py", line 1
37, in fetch_repodata
        .format(url, filename, e))
    conda.exceptions.CondaRuntimeError: Runtime error: Invalid index file: https
://conda.anaconda.org/conda-forge/win-64/repodata.json: Failed to parse: server:
port

**Comment by msarahan** [comment]
That is an old conda version.  You need to update it:

```conda update conda```

If you can't do that, either, you may need to download the latest miniconda or anaconda installer, and reinstall.  I do recommend uninstalling your old installation first.
