### ISSUE TITLE
Navigator Launch Error

### ISSUE THREAD

**Issue by alexdaniel654** [ContinuumIO/anaconda-issues#8786]
### Actual Behavior

On a fresh install of Anaconda the navigator won't open. Nothing happens when I use the shortcut in the start menu and if I try and launch it from the command line I receive the following error.
```
Traceback (most recent call last):
  File "D:\Anaconda2\envs\navigatortest\lib\site-packages\qtpy\__init__.py", line 148, in <module>
    from PySide import __version__ as PYSIDE_VERSION  # analysis:ignore
ModuleNotFoundError: No module named 'PySide'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Anaconda2\envs\navigatortest\Scripts\anaconda-navigator-script.py", line 10, in <module>
    sys.exit(main())
  File "D:\Anaconda2\envs\navigatortest\lib\site-packages\anaconda_navigator\app\main.py", line 125, in main
    from anaconda_navigator.utils.logs import clean_logs
  File "D:\Anaconda2\envs\navigatortest\lib\site-packages\anaconda_navigator\utils\__init__.py", line 15, in <module>
    from qtpy.QtGui import QIcon
  File "D:\Anaconda2\envs\navigatortest\lib\site-packages\qtpy\__init__.py", line 154, in <module>
    raise PythonQtError('No Qt bindings could be found')
qtpy.PythonQtError: No Qt bindings could be found
```
I then installed PySide (which I thought wasn't a requirement) and tried to launch the navigator again. The startup splash screen appears for a couple of seconds before crashing. When I click debug in the windows dialog I receive the following

```
An unhandled win32 exception occurred in phython.exe [4192]. Just-In-Time debugging this exception failed with the following error: No installed debugger has Just-In-Time debugging enabled. In Visual Studio, Just-In-Time debugging can be enabled from Tools/Options/Debugging/Just-In-Time.
```

I've also tried running spyder both before and after installing PySide and get similar errors complaining about Qt issues.
### Expected Behavior

Anaconda Navigator should open
### Steps to Reproduce

This issue appeared on a previous install so on a fresh install I made a new environment with only the required packages and tried to launch the navigator.

Install using `Anaconda2-5.1.0-Windows-x86_64.exe`

`conda create --name navigatortest`

`conda activate navigatortest`

`conda install anaconda-navigator`

`anaconda-navigator`

First Error Occurs

`conda install PySide`

`anaconda-navigator`

Splash screen appears then crashes.

##### Anaconda or Miniconda version:

Anaconda 5.1.0

##### Operating System:

Windows 10
##### `conda info`

```
     active environment : navigatortest
    active env location : D:\Anaconda2\envs\navigatortest
            shell level : 2
       user config file : C:\Users\Alex Daniel\.condarc
 populated config files : C:\Users\Alex Daniel\.condarc
          conda version : 4.4.10
    conda-build version : 3.4.1
         python version : 2.7.14.final.0
       base environment : D:\Anaconda2  (writable)
           channel URLs : https://conda.anaconda.org/anaconda-fusion/win-64
                          https://conda.anaconda.org/anaconda-fusion/noarch
                          https://repo.continuum.io/pkgs/main/win-64
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/win-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
          package cache : D:\Anaconda2\pkgs
                          C:\Users\Alex Daniel\AppData\Local\conda\conda\pkgs
       envs directories : D:\Anaconda2\envs
                          C:\Users\Alex Daniel\AppData\Local\conda\conda\envs
                          C:\Users\Alex Daniel\.conda\envs
               platform : win-64
             user-agent : conda/4.4.10 requests/2.18.4 CPython/2.7.14 Windows/10 Windows/10.0.16299
          administrator : True
             netrc file : None
           offline mode : False
```

##### `conda list --show-channel-urls`

```
# packages in environment at D:\Anaconda2\envs\navigatortest:
#
# Name                    Version                   Build  Channel
alabaster                 0.7.10           py27h2cab13d_0    defaults
anaconda-client           1.6.11                   py27_0    defaults
anaconda-navigator        1.7.0                    py27_0    defaults
anaconda-project          0.8.2            py27he89e3ca_0    defaults
asn1crypto                0.24.0                   py27_0    defaults
astroid                   1.6.1                    py27_0    defaults
babel                     2.5.3                    py27_0    defaults
backports                 1.0              py27h6492d98_1    defaults
backports.functools_lru_cache 1.5                      py27_1    defaults
backports.shutil_get_terminal_size 1.0.0            py27h1657125_2    defaults
backports_abc             0.5              py27h0ec6b72_0    defaults
bleach                    2.1.2                    py27_0    defaults
ca-certificates           2017.08.26           h94faf87_0    defaults
certifi                   2018.1.18                py27_0    defaults
cffi                      1.11.4           py27h0c8e037_0    defaults
chardet                   3.0.4            py27h56c3b73_1    defaults
cloudpickle               0.5.2                    py27_1    defaults
clyent                    1.2.2            py27h4424948_1    defaults
colorama                  0.3.9            py27hdfe4ae1_0    defaults
configparser              3.5.0            py27h2fa79a8_0    defaults
cryptography              2.1.4            py27h0628b04_0    defaults
decorator                 4.2.1                    py27_0    defaults
docutils                  0.14             py27h8652d09_0    defaults
entrypoints               0.2.3            py27h0271f2b_2    defaults
enum34                    1.1.6            py27h2aa175b_1    defaults
freetype                  2.8                  hea645e0_1    defaults
functools32               3.2.3.2          py27h0cdbcdb_1    defaults
futures                   3.2.0            py27h8b2aecd_0    defaults
html5lib                  1.0.1            py27h5a33001_0    defaults
icu                       58.2                 h2aa20d9_1    defaults
idna                      2.6              py27h1ea29d3_1    defaults
imagesize                 1.0.0                    py27_0    defaults
ipaddress                 1.0.19                   py27_0    defaults
ipykernel                 4.8.2                    py27_0    defaults
ipython                   5.4.1                    py27_2    defaults
ipython_genutils          0.2.0            py27hbe997df_0    defaults
isort                     4.3.4                    py27_0    defaults
jedi                      0.11.1                   py27_0    defaults
jinja2                    2.10             py27hba1794b_0    defaults
jpeg                      9b                   ha175dff_2    defaults
jsonschema                2.6.0            py27haaf3834_0    defaults
jupyter_client            5.2.2                    py27_0    defaults
jupyter_core              4.4.0            py27h1619e65_0    defaults
lazy-object-proxy         1.3.1            py27ha5c8080_0    defaults
libpng                    1.6.34               h325896a_0    defaults
libtiff                   4.0.9                hafacce9_0    defaults
markupsafe                1.0              py27h9d4480d_1    defaults
mccabe                    0.6.1            py27hde0bf6e_1    defaults
mistune                   0.8.3                    py27_0    defaults
nbconvert                 5.3.1            py27h7a573cf_0    defaults
nbformat                  4.4.0            py27hf49b375_0    defaults
numpydoc                  0.7.0            py27hf7b062b_0    defaults
olefile                   0.45.1                   py27_0    defaults
openssl                   1.0.2n               hc64555f_0    defaults
packaging                 16.8             py27hae1a450_1    defaults
pandoc                    1.19.2.1             hb2460c7_1    defaults
pandocfilters             1.4.2            py27h76461d3_1    defaults
parso                     0.1.1            py27hd69ea77_0    defaults
pathlib2                  2.3.0            py27h0ae272f_0    defaults
pickleshare               0.7.4            py27hb5f6335_0    defaults
pillow                    5.0.0            py27h901f87c_0    defaults
pip                       9.0.1                    py27_5    defaults
prompt_toolkit            1.0.15           py27h3a8ec6a_0    defaults
psutil                    5.4.3            py27h0c8e037_0    defaults
pycodestyle               2.3.1            py27h24cd5d9_0    defaults
pycparser                 2.18             py27hb43d16c_1    defaults
pyflakes                  1.6.0            py27h34e7826_0    defaults
pygments                  2.2.0            py27ha50f84f_0    defaults
pylint                    1.8.2                    py27_0    defaults
pyopenssl                 17.5.0           py27h59156d7_0    defaults
pyparsing                 2.2.0            py27hc7d9fa6_1    defaults
pyqt                      5.6.0            py27h224ed30_5    defaults
pyside                    1.2.1                    py27_0    defaults
pysocks                   1.6.8                    py27_0    defaults
python                    2.7.14              h8c3f1cb_23    defaults
python-dateutil           2.6.1            py27hbdcc174_1    defaults
pytz                      2018.3                   py27_0    defaults
pyyaml                    3.12             py27ha287073_1    defaults
pyzmq                     16.0.3           py27he883654_0    defaults
qt                        5.6.2            vc9hc26998b_12    defaults
qtawesome                 0.4.4            py27h766b13d_0    defaults
qtconsole                 4.3.1            py27h77d40ac_0    defaults
qtpy                      1.3.1            py27h1ff2b4b_0    defaults
requests                  2.18.4           py27h3159eba_1    defaults
rope                      0.10.7           py27hb65afb6_0    defaults
ruamel_yaml               0.15.35          py27h0c8e037_1    defaults
scandir                   1.7              py27h0c8e037_0    defaults
setuptools                38.5.1                   py27_0    defaults
simplegeneric             0.8.1                    py27_2    defaults
singledispatch            3.4.0.3          py27h3f9d112_0    defaults
sip                       4.18.1           py27h5ec1c1a_2    defaults
six                       1.11.0           py27ha5e1701_1    defaults
snowballstemmer           1.2.1            py27h28d3bf7_0    defaults
sphinx                    1.7.1                    py27_0    defaults
sphinxcontrib             1.0              py27h0e2fb95_1    defaults
sphinxcontrib-websupport  1.0.1            py27h0d0f901_1    defaults
spyder                    3.2.7                    py27_0    defaults
sqlite                    3.22.0               h8b3e59e_0    defaults
ssl_match_hostname        3.5.0.1          py27hea8a0f4_2    defaults
testpath                  0.3.1            py27h1cd488d_0    defaults
tk                        8.6.7                h144d9c4_3    defaults
tornado                   4.5.3                    py27_0    defaults
traitlets                 4.3.2            py27h1b1b3a5_0    defaults
typing                    3.6.4                    py27_0    defaults
urllib3                   1.22             py27hb9f5a07_0    defaults
vc                        9                    h7299396_1    defaults
vs2008_runtime            9.00.30729.1         hfaea7d5_1    defaults
vs2015_runtime            14.0.25123                    3    defaults
wcwidth                   0.1.7            py27hb1a0d82_0    defaults
webencodings              0.5.1            py27h4e224a2_1    defaults
wheel                     0.30.0           py27ha643586_1    defaults
win_inet_pton             1.0.1            py27hf41312a_1    defaults
win_unicode_console       0.5              py27hc037021_0    defaults
wincertstore              0.2              py27hf04cefb_0    defaults
wrapt                     1.10.11          py27hcd2b27d_0    defaults
yaml                      0.1.7                h3e6d941_2    defaults
zlib                      1.2.11               hbc2faf4_2    defaults
```

**Comment by goanpeca** [comment]
@alexdaniel654 

>I then installed PySide (which I thought wasn't a requirement)

It is not, the error is

`qtpy.PythonQtError: No Qt bindings could be found`

So Qt was not installed correctly on your system

try running on the anaconda prompt

```
conda install qt=5.* --force
conda install pyqt=5.* --force
```

Also you installed in a path with spaces `C:\Users\Alex Daniel` that will be a source of all sort of problems with modules (including Qt on some parts). So I would advice installing on a path with no spaces for the current user.
