### ISSUE TITLE
Anaconda-Navigator Error messages during startup

### ISSUE THREAD

**Issue by sebi06** [ContinuumIO/anaconda-issues#879]
Hi guys,

I am running conda 4.1.6 but always get an error when I try to start the navigator un Ubuntu 16-04 LTS. The splash screen shows up but then I get the errors below.

```
Traceback (most recent call last):
  File "/home/user1/anaconda/bin/anaconda-navigator", line 6, in <module>
    sys.exit(anaconda_navigator.app.main.main())
  File "/home/user1/anaconda/lib/python2.7/site-packages/anaconda_navigator/app/main.py", line 58, in main
    window = run_app(splash)
  File "/home/user1/anaconda/lib/python2.7/site-packages/anaconda_navigator/app/main.py", line 33, in run_app
    window = MainWindow(splash=splash)
  File "/home/user1/anaconda/lib/python2.7/site-packages/anaconda_navigator/widgets/main_window.py", line 122, in __init__
    self.environments_tab = EnvironmentsTab(parent=self)
  File "/home/user1/anaconda/lib/python2.7/site-packages/anaconda_navigator/widgets/tabs/environments.py", line 95, in __init__
    conda_url=conda_url)
  File "/home/user1/anaconda/lib/python2.7/site-packages/conda_manager/widgets/packages.py", line 159, in __init__
    for ch in active_channels:
TypeError: 'NoneType' object is not iterable

Conda Info:

platform : linux-64
conda version : 4.1.6
conda-env version : 2.5.1
conda-build version : 1.21.3
python version : 2.7.11.final.0
requests version : 2.9.1
...

**Comment by goanpeca** [comment]
Please download the latest version of navigator

On the command prompt you can type

`conda install anaconda-navigator`
