### ISSUE TITLE
unable to launch anaconda navigator

### ISSUE THREAD

**Issue by YashDidwania125** [ContinuumIO/anaconda-issues#8790]
this is the error which is been showing to me. Can you help me sort the situation?

Traceback (most recent call last):
File "C:\Users\dell\Anaconda3\lib\site-packages\psutil\_pswindows.py", line 636, in wrapper
return fun(self, *args, **kwargs)
File "C:\Users\dell\Anaconda3\lib\site-packages\psutil\_pswindows.py", line 706, in cmdline
ret = cext.proc_cmdline(self.pid)
PermissionError: [WinError 5] Access is denied

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "C:\Users\dell\Anaconda3\lib\site-packages\anaconda_navigator\exceptions.py", line 75, in exception_handler
return_value = func(*args, **kwargs)
File "C:\Users\dell\Anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 113, in start_app
if misc.load_pid() is None: # A stale lock might be around
File "C:\Users\dell\Anaconda3\lib\site-packages\anaconda_navigator\utils\misc.py", line 384, in load_pid
cmds = process.cmdline()
File "C:\Users\dell\Anaconda3\lib\site-packages\psutil\__init__.py", line 721, in cmdline
return self._proc.cmdline()
File "C:\Users\dell\Anaconda3\lib\site-packages\psutil\_pswindows.py", line 639, in wrapper
raise AccessDenied(self.pid, self._name)
psutil.AccessDenied: psutil.AccessDenied (pid=9400)

**Comment by goanpeca** [comment]
https://github.com/Microsoft/vscode-python/issues/727#issuecomment-370813834

**Comment by YashDidwania125** [comment]
The link is showing a link of the Ipython console. But I am unable to launch anaconda navigator even after uninstalling and reinstalling the softwarem

**Comment by goanpeca** [comment]
**See issue #1984 for more information on how to fix this.**

Or you can run on the Terminal or Anaconda prompt:

```
anaconda-navigator --reset
```

**Comment by YashDidwania125** [comment]
It worked . Thanks
