### ISSUE TITLE
Navigator Error: An unexpected error occurred on Navigator start-up

### ISSUE THREAD

**Issue by PrinterMark** [ContinuumIO/anaconda-issues#8797]
Navigator Error
An unexpected error occurred on Navigator start-up

Report
Please report this issue in the anaconda issue tracker

Main Error
byte indices must be integers or slices, not str
Traceback
Traceback (most recent call last):
  File "E:\Anaconda3\lib\site-packages\anaconda_navigator\exceptions.py", line 75, in exception_handler
    return_value = func(*args, **kwargs)
  File "E:\Anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 120, in start_app
    window = run_app(splash)
  File "E:\Anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 63, in run_app
    window = MainWindow(splash=splash)
  File "E:\Anaconda3\lib\site-packages\anaconda_navigator\widgets\main_window.py", line 163, in __init__
    self.api = AnacondaAPI()
  File "E:\Anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 2004, in AnacondaAPI
    ANACONDA_API = _AnacondaAPI()
  File "E:\Anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 88, in __init__
    self._conda_api = CondaAPI()
  File "E:\Anaconda3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 1690, in CondaAPI
    CONDA_API = _CondaAPI()
  File "E:\Anaconda3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 347, in __init__
    self.set_conda_prefix()
  File "E:\Anaconda3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 496, in set_conda_prefix
    self.ROOT_PREFIX = info['root_prefix']
TypeError: byte indices must be integers or slices, not str
-->

### Actual Behavior

Got this error message

### Expected Behavior

Expected navigator to start

### Steps to Reproduce:
repeat
E:\Anaconda3\pythonw.exe E:\Anaconda3\cwp.py E:\Anaconda3 E:\Anaconda3\pythonw.exe E:\Anaconda3\Scripts\anaconda-navigator-script.py

##### Anaconda or Miniconda version:
5.1.0

##### Operating System:
windows 10

##### `conda info`

```
E:\Anaconda3\Scripts>conda info

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "E:\Anaconda3\lib\site-packages\conda\exceptions.py", line 789, in __call__
        return func(*args, **kwargs)
      File "E:\Anaconda3\lib\site-packages\conda\cli\main.py", line 74, in _main
        context.__init__(argparse_args=args)
      File "E:\Anaconda3\lib\site-packages\conda\base\context.py", line 234, in __init__
        argparse_args=argparse_args)
      File "E:\Anaconda3\lib\site-packages\conda\common\configuration.py", line 723, in __init__
        self._set_search_path(search_path)
      File "E:\Anaconda3\lib\site-packages\conda\common\configuration.py", line 729, in _set_search_path
        self._set_raw_data(load_file_configs(search_path))
      File "E:\Anaconda3\lib\site-packages\conda\common\configuration.py", line 371, in load_file_configs
        raw_data = odict(kv for kv in chain.from_iterable(load_paths))
      File "E:\Anaconda3\lib\site-packages\conda\common\configuration.py", line 371, in <genexpr>
        raw_data = odict(kv for kv in chain.from_iterable(load_paths))
      File "E:\Anaconda3\lib\site-packages\conda\common\configuration.py", line 346, in _file_yaml_loader
        yield fullpath, YamlRawParameter.make_raw_parameters_from_file(fullpath)
      File "E:\Anaconda3\lib\site-packages\conda\common\configuration.py", line 334, in make_raw_parameters_from_file
        ruamel_yaml = yaml_load(fh)
      File "E:\Anaconda3\lib\site-packages\conda\common\serialize.py", line 54, in yaml_load
        return yaml.load(string, Loader=yaml.RoundTripLoader, version="1.2")
      File "E:\Anaconda3\lib\site-packages\ruamel_yaml\main.py", line 637, in load
        loader = Loader(stream, version, preserve_quotes=preserve_quotes)
      File "E:\Anaconda3\lib\site-packages\ruamel_yaml\loader.py", line 59, in __init__
        Reader.__init__(self, stream, loader=self)
      File "E:\Anaconda3\lib\site-packages\ruamel_yaml\reader.py", line 80, in __init__
        self.stream = stream  # type: Any  # as .read is called
      File "E:\Anaconda3\lib\site-packages\ruamel_yaml\reader.py", line 125, in stream
        self.determine_encoding()
      File "E:\Anaconda3\lib\site-packages\ruamel_yaml\reader.py", line 180, in determine_encoding
        self.update(1)
      File "E:\Anaconda3\lib\site-packages\ruamel_yaml\reader.py", line 241, in update
        self.check_printable(data)
      File "E:\Anaconda3\lib\site-packages\ruamel_yaml\reader.py", line 208, in check_printable
        'unicode', "special characters are not allowed")
    ruamel_yaml.reader.ReaderError: unacceptable character #x0000: special characters are not allowed
      in "C:\Users\Sam\.condarc", position 0

`$ E:\Anaconda3\Scripts\conda info`


An unexpected error has occurred. Conda has prepared the above report.
If submitted, this report will be used by core maintainers to improve
future releases of conda.
Would you like conda to send this report to the core maintainers?
[y/N]:
```

##### `conda list --show-channel-urls`

```
E:\Anaconda3\Scripts>conda list --show-channel-urls

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "E:\Anaconda3\lib\site-packages\conda\exceptions.py", line 789, in __call__
        return func(*args, **kwargs)
      File "E:\Anaconda3\lib\site-packages\conda\cli\main.py", line 74, in _main
        context.__init__(argparse_args=args)
      File "E:\Anaconda3\lib\site-packages\conda\base\context.py", line 234, in __init__
        argparse_args=argparse_args)
      File "E:\Anaconda3\lib\site-packages\conda\common\configuration.py", line 723, in __init__
        self._set_search_path(search_path)
      File "E:\Anaconda3\lib\site-packages\conda\common\configuration.py", line 729, in _set_search_path
        self._set_raw_data(load_file_configs(search_path))
      File "E:\Anaconda3\lib\site-packages\conda\common\configuration.py", line 371, in load_file_configs
        raw_data = odict(kv for kv in chain.from_iterable(load_paths))
      File "E:\Anaconda3\lib\site-packages\conda\common\configuration.py", line 371, in <genexpr>
        raw_data = odict(kv for kv in chain.from_iterable(load_paths))
      File "E:\Anaconda3\lib\site-packages\conda\common\configuration.py", line 346, in _file_yaml_loader
        yield fullpath, YamlRawParameter.make_raw_parameters_from_file(fullpath)
      File "E:\Anaconda3\lib\site-packages\conda\common\configuration.py", line 334, in make_raw_parameters_from_file
        ruamel_yaml = yaml_load(fh)
      File "E:\Anaconda3\lib\site-packages\conda\common\serialize.py", line 54, in yaml_load
        return yaml.load(string, Loader=yaml.RoundTripLoader, version="1.2")
      File "E:\Anaconda3\lib\site-packages\ruamel_yaml\main.py", line 637, in load
        loader = Loader(stream, version, preserve_quotes=preserve_quotes)
      File "E:\Anaconda3\lib\site-packages\ruamel_yaml\loader.py", line 59, in __init__
        Reader.__init__(self, stream, loader=self)
      File "E:\Anaconda3\lib\site-packages\ruamel_yaml\reader.py", line 80, in __init__
        self.stream = stream  # type: Any  # as .read is called
      File "E:\Anaconda3\lib\site-packages\ruamel_yaml\reader.py", line 125, in stream
        self.determine_encoding()
      File "E:\Anaconda3\lib\site-packages\ruamel_yaml\reader.py", line 180, in determine_encoding
        self.update(1)
      File "E:\Anaconda3\lib\site-packages\ruamel_yaml\reader.py", line 241, in update
        self.check_printable(data)
      File "E:\Anaconda3\lib\site-packages\ruamel_yaml\reader.py", line 208, in check_printable
        'unicode', "special characters are not allowed")
    ruamel_yaml.reader.ReaderError: unacceptable character #x0000: special characters are not allowed
      in "C:\Users\Sam\.condarc", position 0

`$ E:\Anaconda3\Scripts\conda list --show-channel-urls`

  environment variables:
                 CIO_TEST=<not set>
               CONDA_ROOT=E:\Anaconda3
                 HOMEPATH=\Users\Sam
                     PATH=E:\Anaconda3\Library\bin;C:\ProgramData\Oracle\Java\javapath;C:\WINDOW
                          S\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\Win
                          dowsPowerShell\v1.0\;C:\Program Files (x86)\ATI
                          Technologies\ATI.ACE\Core-Static;C:\Program Files (x86)\Windows
                          Live\Shared;C:\php;C:\Apache24;C:\Apache24\bin;;c:\users\Sam\appdata\local\enthought\canopy\user\scripts;
                          C:\Users\Sam\AppData\Local\Enthought\Canopy\User;C:\Users\Sam\AppDat
                          a\Local\Enthought\Canopy\User\Scripts;C:\Users\Sam\AppData\Local\Micr
                          osoft\WindowsApps;E:\graphviz-feedstock-master;
             PSMODULEPATH=C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules\
               PYTHONPATH=E:\Python33\mglearn
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>

     active environment : None
       user config file : C:\Users\Sam\.condarc
 populated config files :
          conda version : 4.4.10
    conda-build version : 3.4.1
         python version : 3.6.4.final.0
       base environment : E:\Anaconda3  (writable)
           channel URLs : https://repo.continuum.io/pkgs/main/win-64
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/win-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
          package cache : E:\Anaconda3\pkgs
                          C:\Users\Sam\AppData\Local\conda\conda\pkgs
       envs directories : E:\Anaconda3\envs
                          C:\Users\Sam\AppData\Local\conda\conda\envs
                          C:\Users\Sam\.conda\envs
               platform : win-64
             user-agent : conda/4.4.10 requests/2.18.4 CPython/3.6.4 Windows/10 Windows/10.0.16299
          administrator : False
             netrc file : None
           offline mode : False


An unexpected error has occurred. Conda has prepared the above report.
If submitted, this report will be used by core maintainers to improve
future releases of conda.
Would you like conda to send this report to the core maintainers?
[y/N]:
```

**Comment by xiaoyangstat** [comment]
works for me! Thanks.

**Comment by gnkumar0696** [comment]
Hi, while entering the command in cmd its displaying the following message:

![image](https://user-images.githubusercontent.com/54973000/64402493-d0e54600-d092-11e9-8191-26172d19916a.png)
