### ISSUE TITLE
numpy failed test for Python 3, due to violation of PEP 3149

### ISSUE THREAD

**Issue by zym1010** [ContinuumIO/anaconda-issues#880]
When running `python -c 'import numpy as np;np.test()'` for a Python 3 environment with only numpy (all installed through `conda`), I got the following (at least this is case for numpy 1.11.0 & 1.11.1 without mkl on Linux, and Anaconda3 64-bit 4.1 on Linux).

```
ERROR: test_basic2 (test_ctypeslib.TestLoadLibrary)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/yimengzh_everyday/miniconda2/envs/numpy-test/lib/python3.5/site-packages/numpy/testing/decorators.py", line 147, in skipper_func
    return f(*args, **kwargs)
  File "/home/yimengzh_everyday/miniconda2/envs/numpy-test/lib/python3.5/site-packages/numpy/testing/decorators.py", line 217, in knownfailer
    return f(*args, **kwargs)
  File "/home/yimengzh_everyday/miniconda2/envs/numpy-test/lib/python3.5/site-packages/numpy/tests/test_ctypeslib.py", line 41, in test_basic2
    load_library('multiarray%s' % so, np.core.multiarray.__file__)
  File "/home/yimengzh_everyday/miniconda2/envs/numpy-test/lib/python3.5/site-packages/numpy/ctypeslib.py", line 155, in load_library
    raise OSError("no file with expected extension")
OSError: no file with expected extension
```

Looks that numpy expects the extension of libraries to be `.cpython-35m-x86_64-linux-gnu.so` (according to PEP 3149), yet this is not the case for numpy installed through `conda` (they end with `.so`)

It's interesting that for some numpy versions in the conda repo, while the older builds conform to PEP 3149, the latest build doesn't. For example, compare `numpy-1.10.4-py35_nomkl_1` and `numpy-1.10.4-py35_nomkl_2`, I found the suffix for Python 3.5 (`cpython-35m-x86_64-linux-gnu`) is gone for all `.so` files in the latter. No idea why such regression is happening.

**Comment by remkade** [comment]
This appears to be fixed now. I'll go ahead and close it, but please reopen if you have any more problems with this issue!
