### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by somous-jhzhao** [ContinuumIO/anaconda-issues#8815]
## Main error
Application <b>spyder</b> launch may have produced errors.
## Traceback
```
Traceback (most recent call last):
  File "C:\Users\jihui\Anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 3093, in main
    mainwindow = run_spyder(app, options, args)
  File "C:\Users\jihui\Anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 2995, in run_spyder
    main.setup()
  File "C:\Users\jihui\Anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 1075, in setup
    self.apply_statusbar_settings()
  File "C:\Users\jihui\Anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 2580, in apply_statusbar_settings
    show_status_bar = CONF.get('main', 'show_status_bar')
  File "C:\Users\jihui\Anaconda3\lib\site-packages\spyder\config\user.py", line 387, in get
    value = ast.literal_eval(value)
  File "C:\Users\jihui\Anaconda3\lib\ast.py", line 48, in literal_eval
    node_or_string = parse(node_or_string, mode='eval')
  File "C:\Users\jihui\Anaconda3\lib\ast.py", line 35, in parse
    return compile(source, filename, mode, PyCF_ONLY_AST)
MemoryError

```
## System information
```
python: 3.6.1
language: zh_CN
os: Windows;10;10.0.16299;AMD64;Intel64 Family 6 Model 60 Stepping 3, GenuineIntel
version: 1.6.2
platform: win-64
qt: 5.6.2
pyqt: 5.6.0
conda: 4.3.21
```

**Comment by goanpeca** [comment]
@ccordoba12 thoughts?

**Comment by goanpeca** [comment]
Stale issue, closing
