### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by divanshudodeja** [ContinuumIO/anaconda-issues#8848]
## Main error
Application <b>orange3</b> launch may have produced errors.
## Traceback
```
An ImportError occurred while loading entry point 'Audio - IJS = orangecontrib.audio.widgets'
Traceback (most recent call last):
  File "C:\Users\DIVANSHU\Anaconda3\lib\site-packages\Orange\canvas\registry\discovery.py", line 89, in run
    point = entry_point.resolve()
  File "C:\Users\DIVANSHU\Anaconda3\lib\site-packages\setuptools-27.2.0-py3.6.egg\pkg_resources\__init__.py", line 2264, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
ModuleNotFoundError: No module named 'orangecontrib.audio'

```
## System information
```
python: 3.6.1
language: en_IN
os: Windows;10;10.0.16299;AMD64;Intel64 Family 6 Model 69 Stepping 1, GenuineIntel
version: 1.6.2
platform: win-64
qt: 5.6.2
pyqt: 5.6.0
conda: 4.4.11
```

**Comment by goanpeca** [comment]
@divanshudodeja it may be that Orange was not correctly installed?

Open a terminal and try

```
conda install orange3 --force
```

Also you seem to be using a very old version of navigator.

Please remember to update to the latest version of Navigator to include
the latest fixes.

Open a terminal (on Linux or Mac) or the Anaconda Command Prompt (on windows)
and type:

```
conda update conda
conda update anaconda-navigator
conda update navigator-updater
```
