### ISSUE TITLE
No module named '_sysconfigdata_m' in Ubuntu 16.04

### ISSUE THREAD

**Issue by John1231983** [ContinuumIO/anaconda-issues#8861]
Hello all, I have the error when installing anaconda in Ubuntu 16.04 . Could you help me to fix it?
### Actual Behavior
```
Do you wish the installer to prepend the Anaconda3 install location
to PATH in your /home/john/.bashrc ? [yes|no]
[no] >>> yes

Prepending PATH=/home/john/anaconda3/bin to PATH in /home/john/.bashrc
A backup will be made to: /home/john/.bashrc-anaconda3.bak


For this change to become active, you have to open a new terminal.

Thank you for installing Anaconda3!

Share your notebooks and packages on Anaconda Cloud!
Sign up for free: https://anaconda.org

```
Typing : `conda info` then error 
```
conda info
Failed to import the site module
Traceback (most recent call last):
  File "/usr/lib/python3.5/site.py", line 580, in <module>
    main()
  File "/usr/lib/python3.5/site.py", line 566, in main
    known_paths = addusersitepackages(known_paths)
  File "/usr/lib/python3.5/site.py", line 287, in addusersitepackages
    user_site = getusersitepackages()
  File "/usr/lib/python3.5/site.py", line 263, in getusersitepackages
    user_base = getuserbase() # this will also set USER_BASE
  File "/usr/lib/python3.5/site.py", line 253, in getuserbase
    USER_BASE = get_config_var('userbase')
  File "/usr/lib/python3.5/sysconfig.py", line 595, in get_config_var
    return get_config_vars().get(name)
  File "/usr/lib/python3.5/sysconfig.py", line 538, in get_config_vars
    _init_posix(_CONFIG_VARS)
  File "/usr/lib/python3.5/sysconfig.py", line 410, in _init_posix
    from _sysconfigdata import build_time_vars
  File "/usr/lib/python3.5/_sysconfigdata.py", line 6, in <module>
    from _sysconfigdata_m import *
ImportError: No module named '_sysconfigdata_m'

```
### Steps to Reproduce

 
```
./Anaconda3-4.2.0-Linux-x86_64.sh
conda info
```
##### Operating System:  Ubuntu 16.04
`python -V`
Python 3.5.2 :: Anaconda 4.2.0 (64-bit)

**Comment by John1231983** [comment]
I have solved it by following steps:
```
sudo ln -fs /usr/lib/python3.5/plat-x86_64-linux-gnu/_sysconfigdata_m.py /usr/lib/python3.5/
pip3 install conda
unset PYTHONPATH
conda update conda
```
Hope it help someone
