### ISSUE TITLE
hi I keep getting this notification when I try open anaconda on mac and get my access denied

### ISSUE THREAD

**Issue by mr-gloom** [ContinuumIO/anaconda-issues#8870]
Traceback (most recent call last):
File "/anaconda3/lib/python3.6/site-packages/psutil/_psosx.py", line 348, in catch_zombie
yield
File "/anaconda3/lib/python3.6/site-packages/psutil/_psosx.py", line 412, in cmdline
return cext.proc_cmdline(self.pid)
ProcessLookupError: [Errno 3] No such process

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/anaconda3/lib/python3.6/site-packages/anaconda_navigator/exceptions.py", line 75, in exception_handler
return_value = func(*args, **kwargs)
File "/anaconda3/lib/python3.6/site-packages/anaconda_navigator/app/start.py", line 113, in start_app
if misc.load_pid() is None: # A stale lock might be around
File "/anaconda3/lib/python3.6/site-packages/anaconda_navigator/utils/misc.py", line 384, in load_pid
cmds = process.cmdline()
File "/anaconda3/lib/python3.6/site-packages/psutil/__init__.py", line 666, in cmdline
return self._proc.cmdline()
File "/anaconda3/lib/python3.6/site-packages/psutil/_psosx.py", line 330, in wrapper
return fun(self, *args, **kwargs)
File "/anaconda3/lib/python3.6/site-packages/psutil/_psosx.py", line 412, in cmdline
return cext.proc_cmdline(self.pid)
File "/anaconda3/lib/python3.6/contextlib.py", line 99, in __exit__
self.gen.throw(type, value, traceback)
File "/anaconda3/lib/python3.6/site-packages/psutil/_psosx.py", line 361, in catch_zombie
raise AccessDenied(proc.pid, proc._name)
psutil._exceptions.AccessDenied: psutil.AccessDenied (pid=510)

**Comment by goanpeca** [comment]
https://www.larebajavirtual.com/catalogo/producto/producto/93027/descripcion/MELATONINA-FUNAT-3-MG.html

**Comment by mr-gloom** [comment]
wtf?

**Comment by mr-gloom** [comment]
sorry that link confused me

**Comment by mr-gloom** [comment]
i already tried updating before posting this

**Comment by goanpeca** [comment]
Run `anaconda-navigator --reset`

**Comment by mr-gloom** [comment]
hi i solved it. Thank you
