### ISSUE TITLE
An unexpected error occurred on Navigator start-up psutil.AccessDenied(pid=2684) 

### ISSUE THREAD

**Issue by someguyintha415** [ContinuumIO/anaconda-issues#8883]
Hi !

When trying to launch anaconda navigator, I get the a error box with the following text:

"Traceback (most recent call last):
File "C:\ProgramData\Anaconda3\lib\site-packages\psutil\_pswindows.py", line 635, in wrapper
return fun(self, *args, **kwargs)
File "C:\ProgramData\Anaconda3\lib\site-packages\psutil\_pswindows.py", line 705, in cmdline
ret = cext.proc_cmdline(self.pid)
PermissionError: [WinError 5] Access is denied

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "C:\ProgramData\Anaconda3\lib\site-packages\anaconda_navigator\exceptions.py", line 75, in exception_handler
return_value = func(*args, **kwargs)
File "C:\ProgramData\Anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 113, in start_app
if misc.load_pid() is None: # A stale lock might be around
File "C:\ProgramData\Anaconda3\lib\site-packages\anaconda_navigator\utils\misc.py", line 384, in load_pid
cmds = process.cmdline()
File "C:\ProgramData\Anaconda3\lib\site-packages\psutil\__init__.py", line 666, in cmdline
return self._proc.cmdline()
File "C:\ProgramData\Anaconda3\lib\site-packages\psutil\_pswindows.py", line 638, in wrapper
raise AccessDenied(self.pid, self._name)
psutil._exceptions.AccessDenied: psutil.AccessDenied (pid=2684)"

I've tried uninstalling and reinstalling several times but keep running into this error.  Is there a fix for this?

Thanks!

**Comment by someguyintha415** [comment]
Addition...I am running Windows 10, and starting running anaconda as administrator also does not work.

Thanks!
