### ISSUE TITLE
Issue with scipy in Python 2.6 on Mac OS X

### ISSUE THREAD

**Issue by asmeurer** [ContinuumIO/anaconda-issues#89]
On Mac OS X, Python 2.6:

``` py
Python 2.6.9 |Continuum Analytics, Inc.| (unknown, Jan 10 2014, 13:33:57)
[GCC 4.2.1 (Apple Inc. build 5577)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from scipy.io import loadmat
/Users/aaronmeurer/anaconda/envs/test/lib/python2.6/site-packages/numpy/oldnumeric/__init__.py:11: ModuleDeprecationWarning: The oldnumeric module will be dropped in Numpy 1.9
  warnings.warn(_msg, ModuleDeprecationWarning)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/aaronmeurer/anaconda/envs/test/lib/python2.6/site-packages/scipy/io/__init__.py", line 85, in <module>
    from .matlab import loadmat, savemat, whosmat, byteordercodes
  File "/Users/aaronmeurer/anaconda/envs/test/lib/python2.6/site-packages/scipy/io/matlab/__init__.py", line 13, in <module>
    from .mio import loadmat, savemat, whosmat
  File "/Users/aaronmeurer/anaconda/envs/test/lib/python2.6/site-packages/scipy/io/matlab/mio.py", line 13, in <module>
    from .mio4 import MatFile4Reader, MatFile4Writer
  File "/Users/aaronmeurer/anaconda/envs/test/lib/python2.6/site-packages/scipy/io/matlab/mio4.py", line 11, in <module>
    import scipy.sparse
  File "/Users/aaronmeurer/anaconda/envs/test/lib/python2.6/site-packages/scipy/sparse/__init__.py", line 206, in <module>
    from .csr import *
  File "/Users/aaronmeurer/anaconda/envs/test/lib/python2.6/site-packages/scipy/sparse/csr.py", line 15, in <module>
    from .sparsetools import csr_tocsc, csr_tobsr, csr_count_blocks, \
  File "/Users/aaronmeurer/anaconda/envs/test/lib/python2.6/site-packages/scipy/sparse/sparsetools/__init__.py", line 5, in <module>
    from .csr import *
  File "/Users/aaronmeurer/anaconda/envs/test/lib/python2.6/site-packages/scipy/sparse/sparsetools/csr.py", line 26, in <module>
    _csr = swig_import_helper()
  File "/Users/aaronmeurer/anaconda/envs/test/lib/python2.6/site-packages/scipy/sparse/sparsetools/csr.py", line 22, in swig_import_helper
    _mod = imp.load_module('_csr', fp, pathname, description)
ImportError: dlopen(/Users/aaronmeurer/anaconda/envs/test/lib/python2.6/site-packages/scipy/sparse/sparsetools/_csr.so, 2): Symbol not found: __ZNSt8ios_base4InitC1Ev
  Referenced from: /Users/aaronmeurer/anaconda/envs/test/lib/python2.6/site-packages/scipy/sparse/sparsetools/_csr.so
  Expected in: dynamic lookup
```

**Comment by mwcraig** [comment]
Came across this on OSX 10.11 (don't think it is OSX version-dependent problem)

**Comment by goanpeca** [comment]
Closing for lack of activity.

Please reopen if this is still a problem with an update of the status.

Thanks!
