### ISSUE TITLE
Navigator start error AccessDenied (pid=8860)

### ISSUE THREAD

**Issue by kibrovic** [ContinuumIO/anaconda-issues#8916]
I'm encountering an error when launching Anaconda Navigator:
```
Traceback (most recent call last):
File "C:\ProgramData\Anaconda3\lib\site-packages\psutil\_pswindows.py", line 635, in wrapper
return fun(self, *args, **kwargs)
File "C:\ProgramData\Anaconda3\lib\site-packages\psutil\_pswindows.py", line 705, in cmdline
ret = cext.proc_cmdline(self.pid)
PermissionError: [WinError 5] Access is denied

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "C:\ProgramData\Anaconda3\lib\site-packages\anaconda_navigator\exceptions.py", line 75, in exception_handler
return_value = func(*args, **kwargs)
File "C:\ProgramData\Anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 113, in start_app
if misc.load_pid() is None: # A stale lock might be around
File "C:\ProgramData\Anaconda3\lib\site-packages\anaconda_navigator\utils\misc.py", line 384, in load_pid
cmds = process.cmdline()
File "C:\ProgramData\Anaconda3\lib\site-packages\psutil\__init__.py", line 666, in cmdline
return self._proc.cmdline()
File "C:\ProgramData\Anaconda3\lib\site-packages\psutil\_pswindows.py", line 638, in wrapper
raise AccessDenied(self.pid, self._name)
psutil._exceptions.AccessDenied: psutil.AccessDenied (pid=8860)
```

I'm on Windows 10, 64-bit. Already reinstalled it, updated conda, anaconda-navigator and navigator-updater
conda info:
```
active environment : base
    active env location : C:\ProgramData\Anaconda3
            shell level : 1
       user config file : C:\Users\Kenan\.condarc
 populated config files : C:\Users\Kenan\.condarc
          conda version : 4.4.11
    conda-build version : 3.4.1
         python version : 3.6.4.final.0
       base environment : C:\ProgramData\Anaconda3  (writable)
           channel URLs : https://repo.continuum.io/pkgs/main/win-64
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/win-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
          package cache : C:\ProgramData\Anaconda3\pkgs
                          C:\Users\Kenan\AppData\Local\conda\conda\pkgs
       envs directories : C:\ProgramData\Anaconda3\envs
                          C:\Users\Kenan\AppData\Local\conda\conda\envs
                          C:\Users\Kenan\.conda\envs
               platform : win-64
             user-agent : conda/4.4.11 requests/2.18.4 CPython/3.6.4 Windows/10 Windows/10.0.16299
          administrator : True
             netrc file : None
           offline mode : False
```

**Comment by kibrovic** [comment]
Nevermind, I tried `anaconda-navigator --reset`  and it worked
