### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by pursh2002** [ContinuumIO/anaconda-issues#8925]
## Main error
Application <b>jupyterlab</b> launch may have produced errors.
## Traceback
```
[W 23:33:16.738 LabApp] WARNING: The notebook server is listening on all IP addresses and not using encryption. This is not recommended.
[W 23:33:16.751 LabApp] Error loading server extension ipyparallel.nbextension
    Traceback (most recent call last):
      File "/Users/apple/Downloads/anaconda/lib/python3.6/site-packages/notebook/notebookapp.py", line 1271, in init_server_extensions
        mod = importlib.import_module(modulename)
      File "/Users/apple/Downloads/anaconda/lib/python3.6/importlib/__init__.py", line 126, in import_module
        return _bootstrap._gcd_import(name[level:], package, level)
      File "<frozen importlib._bootstrap>", line 994, in _gcd_import
      File "<frozen importlib._bootstrap>", line 971, in _find_and_load
      File "<frozen importlib._bootstrap>", line 941, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
      File "<frozen importlib._bootstrap>", line 994, in _gcd_import
      File "<frozen importlib._bootstrap>", line 971, in _find_and_load
      File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
    ModuleNotFoundError: No module named 'ipyparallel'
[I 23:33:16.783 LabApp] [jupyter_nbextensions_configurator] enabled 0.3.0
[I 23:33:16.794 LabApp] JupyterLab beta preview extension loaded from /Users/apple/Downloads/anaconda/lib/python3.6/site-packages/jupyterlab
[I 23:33:16.794 LabApp] JupyterLab application directory is /Users/apple/Downloads/anaconda/share/jupyter/lab
[W 23:33:16.798 LabApp] JupyterLab server extension not enabled, manually loading...
[I 23:33:16.798 LabApp] JupyterLab beta preview extension loaded from /Users/apple/Downloads/anaconda/lib/python3.6/site-packages/jupyterlab
[I 23:33:16.798 LabApp] JupyterLab application directory is /Users/apple/Downloads/anaconda/share/jupyter/lab
[I 23:33:16.811 LabApp] Serving notebooks from local directory: /Users/apple
[I 23:33:16.811 LabApp] 0 active kernels 
[I 23:33:16.811 LabApp] The Jupyter Notebook is running at: http://[all ip addresses on your system]:7000/?token=0b02a38a52245e152e85841661be479721db0939963576ab
[I 23:33:16.811 LabApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 23:33:16.812 LabApp] 
    
    Copy/paste this URL into your browser when you connect for the first time,
    to login with a token:
        http://localhost:7000/?token=0b02a38a52245e152e85841661be479721db0939963576ab

```
## System information
```
python: 3.6.4
language: en
os: Darwin;17.4.0;Darwin Kernel Version 17.4.0: Sun Dec 17 09:19:54 PST 2017; root:xnu-4570.41.2~1/RELEASE_X86_64;x86_64;i386
version: 1.6.2
platform: osx-64
qt: 5.6.2
pyqt: 5.6.0
conda: 4.4.8
```

**Comment by goanpeca** [comment]
Please remember to update to the latest version of Navigator to include
the latest fixes.

Open a terminal (on Linux or Mac) or the Anaconda Command Prompt (on windows)
and type:

```
conda update conda
conda update anaconda-navigator
conda update navigator-updater
```
