### ISSUE TITLE
conda.exceptions.ResolvePackageNotFound : pip 9.0.2 py36_0

### ISSUE THREAD

**Issue by spMohanty** [ContinuumIO/anaconda-issues#8967]
Hi, 
I found this error when building a new environment from an `environment.yml` file : 
```
An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues



Current conda install:

               platform : linux-64
          conda version : 4.3.30
       conda is private : False
      conda-env version : 4.3.30
    conda-build version : not installed
         python version : 3.6.4.final.0
       requests version : 2.18.4
       root environment : /srv/conda  (writable)
    default environment : /srv/conda
       envs directories : /srv/conda/envs
                          /home/crowdai/.conda/envs
          package cache : /srv/conda/pkgs
                          /home/crowdai/.conda/pkgs
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.continuum.io/pkgs/main/linux-64
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/linux-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : /srv/conda/.condarc
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.30 requests/2.18.4 CPython/3.6.4 Linux/4.4.0-112-generic debian/stretch/sid glibc/2.26
                UID:GID : 1001:1001

`$ /srv/conda/bin/conda-env update -v -n root -f environment.yml`




    Traceback (most recent call last):
      File "/srv/conda/lib/python3.6/site-packages/conda/exceptions.py", line 640, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/srv/conda/lib/python3.6/site-packages/conda_env/cli/main_update.py", line 106, in execute
        installer.install(prefix, specs, args, env, prune=args.prune)
      File "/srv/conda/lib/python3.6/site-packages/conda_env/installers/conda.py", line 32, in install
        channel_priority_map=_channel_priority_map)
      File "/srv/conda/lib/python3.6/site-packages/conda/plan.py", line 475, in install_actions_list
        dists_for_envs = determine_all_envs(r, specs, channel_priority_map=channel_priority_map)
      File "/srv/conda/lib/python3.6/site-packages/conda/plan.py", line 540, in determine_all_envs
        spec_for_envs = tuple(SpecForEnv(env=p.preferred_env, spec=p.name) for p in best_pkgs)
      File "/srv/conda/lib/python3.6/site-packages/conda/plan.py", line 540, in <genexpr>
        spec_for_envs = tuple(SpecForEnv(env=p.preferred_env, spec=p.name) for p in best_pkgs)
      File "/srv/conda/lib/python3.6/site-packages/conda/plan.py", line 539, in <genexpr>
        best_pkgs = (r.index[r.get_dists_for_spec(s, emptyok=False)[-1]] for s in specs)
      File "/srv/conda/lib/python3.6/site-packages/conda/resolve.py", line 563, in get_dists_for_spec
        raise ResolvePackageNotFound([(ms,)])
    conda.exceptions.ResolvePackageNotFound:
      - pip 9.0.2 py36_0
```

Changing the relevant line to just `pip` instead of `pip=9.0.2=py36_0` fixes the issue though for me.

**Comment by goanpeca** [comment]
pip 9.0.2 introduced some breaking changes, so it is no longer available on the main channels or conda-forge
