### ISSUE TITLE
Anaconda Navigator Not Opening

### ISSUE THREAD

**Issue by PabloRR100** [ContinuumIO/anaconda-issues#8987]
### Actual Behavior

I can't open the Navigator from the icon "The application can't be opened".
I can't either open it from the terminal using ```anacoda-navigator```

➜  ~ anaconda-navigator
```
Traceback (most recent call last):
  File "/Users/pablorr10/miniconda3/bin/anaconda-navigator", line 11, in <module>
    sys.exit(main())
  File "/Users/pablorr10/miniconda3/lib/python3.6/site-packages/anaconda_navigator/app/main.py", line 129, in main
    from anaconda_navigator.app.start import start_app
  File "/Users/pablorr10/miniconda3/lib/python3.6/site-packages/anaconda_navigator/app/start.py", line 33, in <module>
    from anaconda_navigator.widgets.main_window import MainWindow
  File "/Users/pablorr10/miniconda3/lib/python3.6/site-packages/anaconda_navigator/widgets/main_window.py", line 32, in <module>
    from anaconda_navigator.api.anaconda_api import AnacondaAPI
  File "/Users/pablorr10/miniconda3/lib/python3.6/site-packages/anaconda_navigator/api/anaconda_api.py", line 33, in <module>
    from anaconda_navigator.api.client_api import ClientAPI
  File "/Users/pablorr10/miniconda3/lib/python3.6/site-packages/anaconda_navigator/api/client_api.py", line 24, in <module>
    from anaconda_navigator.api.conda_api import CondaAPI
  File "/Users/pablorr10/miniconda3/lib/python3.6/site-packages/anaconda_navigator/api/conda_api.py", line 33, in <module>
    from anaconda_navigator.utils.findpip import PIP_LIST_SCRIPT
  File "/Users/pablorr10/miniconda3/lib/python3.6/site-packages/anaconda_navigator/utils/findpip.py", line 22, in <module>
    import pip
  File "/Users/pablorr10/miniconda3/lib/python3.6/site-packages/pip/__init__.py", line 45, in <module>
    from pip.vcs import git, mercurial, subversion, bazaar  # noqa
  File "/Users/pablorr10/miniconda3/lib/python3.6/site-packages/pip/vcs/mercurial.py", line 9, in <module>
    from pip.download import path_to_url
  File "/Users/pablorr10/miniconda3/lib/python3.6/site-packages/pip/download.py", line 40, in <module>
    from pip._vendor import requests, six
  File "/Users/pablorr10/miniconda3/lib/python3.6/site-packages/pip/_vendor/requests/__init__.py", line 98, in <module>
    from . import packages
  File "/Users/pablorr10/miniconda3/lib/python3.6/site-packages/pip/_vendor/requests/packages.py", line 12, in <module>
    sys.modules['pip._vendor.requests.packages.' + mod] = sys.modules["pip._vendor." + mod]
KeyError: 'pip._vendor.urllib3.contrib'
```
##### Anaconda or Miniconda version:
**miniconda3**
anaconda-navigator        1.8.1                    py36_0

##### Operating System:
Mac Os High Sierra 10.13.3

##### `conda info`
```
     active environment : None
       user config file : /Users/pablorr10/.condarc
 populated config files : /Users/pablorr10/.condarc
          conda version : 4.5.0
    conda-build version : not installed
         python version : 3.6.4.final.0
       base environment : /Users/pablorr10/miniconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/osx-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/osx-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/osx-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/osx-64
                          https://repo.anaconda.com/pkgs/pro/noarch
          package cache : /Users/pablorr10/miniconda3/pkgs
                          /Users/pablorr10/.conda/pkgs
       envs directories : /Users/pablorr10/miniconda3/envs
                          /Users/pablorr10/.conda/envs
               platform : osx-64
             user-agent : conda/4.5.0 requests/2.18.4 CPython/3.6.4 Darwin/17.4.0 OSX/10.13.3
                UID:GID : 501:20
             netrc file : /Users/pablorr10/.netrc
           offline mode : False
```

##### `conda list --show-channel-urls`
```
# packages in environment at /Users/pablorr10/miniconda3:
#
# Name                    Version                   Build  Channel
absl-py                   0.1.10                    <pip>
anaconda-client           1.6.14                   py36_0    defaults
anaconda-navigator        1.8.1                    py36_0    defaults
anaconda-project          0.8.2            py36h9ee5d53_0    defaults
asn1crypto                0.23.0           py36h782d450_0    defaults
bleach                    1.5.0                     <pip>
ca-certificates           2017.08.26           ha1e5d58_0    defaults
certifi                   2018.1.18                py36_0    defaults
cffi                      1.11.2           py36hd3e6348_0    defaults
chardet                   3.0.4            py36h96c241c_1    defaults
clyent                    1.2.2            py36hae3ad88_0    defaults
conda                     4.5.0                    py36_0    defaults
conda-env                 2.6.0                h36134e3_0    defaults
cryptography              2.1.4            py36h842514c_0    defaults
dbus                      1.12.2               h5243cc1_1    defaults
decorator                 4.2.1                    py36_0    defaults
dj-database-url           0.4.2                     <pip>
Django                    2.0.2                     <pip>
django-heroku             0.2.0                     <pip>
expat                     2.2.5                hb8e80ba_0    defaults
fasteners                 0.14.1                    <pip>
flake8                    3.5.0                     <pip>
freetype                  2.8                  h12048fb_1    defaults
gettext                   0.19.8.1             h15daf44_3    defaults
glib                      2.53.6               h33f6a65_2    defaults
hpelm                     1.0.5                     <pip>
html5lib                  0.9999999                 <pip>
icu                       58.2                 h4b95b61_1    defaults
idna                      2.6              py36h8628d0a_1    defaults
ipython_genutils          0.2.0            py36h241746c_0    defaults
jpeg                      9b                   he5867d9_2    defaults
jsonschema                2.6.0            py36hb385e00_0    defaults
jupyter_core              4.4.0            py36h79cf704_0    defaults
Keras                     2.1.4                     <pip>
libcxx                    4.0.1                h579ed51_0    defaults
libcxxabi                 4.0.1                hebd6815_0    defaults
libedit                   3.1                  hb4e282d_0    defaults
libffi                    3.2.1                h475c297_4    defaults
libiconv                  1.15                 hdd342a3_7    defaults
libpng                    1.6.34               he12f830_0    defaults
libtiff                   4.0.9                h0dac147_0    defaults
Markdown                  2.6.11                    <pip>
mccabe                    0.6.1                     <pip>
monotonic                 1.4                       <pip>
nbformat                  4.4.0            py36h827af21_0    defaults
ncurses                   6.0                  hd04f020_2    defaults
nose                      1.3.7                     <pip>
numexpr                   2.6.4                     <pip>
numpy                     1.14.0                    <pip>
olefile                   0.45.1                   py36_0    defaults
openssl                   1.0.2n               hdbc3d79_0    defaults
pcre                      8.41                 hfb6ab37_1    defaults
pew                       1.1.2                     <pip>
pillow                    5.0.0            py36hfcce615_0    defaults
pip                       9.0.2                     <pip>
pip                       9.0.1            py36h1555ced_4    defaults
pipenv                    9.0.3                     <pip>
protobuf                  3.5.1                     <pip>
psutil                    5.4.3            py36h1de35cc_0    defaults
psycopg2                  2.7.4                     <pip>
pycodestyle               2.3.1                     <pip>
pycosat                   0.6.3            py36hee92d8f_0    defaults
pycparser                 2.18             py36h724b2fc_1    defaults
pyflakes                  1.6.0                     <pip>
pyopenssl                 17.5.0           py36h51e4350_0    defaults
pyqt                      5.6.0            py36he5c6137_6    defaults
pysocks                   1.6.7            py36hfa33cec_1    defaults
python                    3.6.4                hc167b69_1    defaults
python-dateutil           2.6.1            py36h86d2abb_1    defaults
python.app                2                py36h54569d5_7    defaults
pytz                      2017.3           py36hf0bf824_0    defaults
pyyaml                    3.12             py36h2ba1e63_1    defaults
qt                        5.6.2               h9975529_14    defaults
qtpy                      1.3.1            py36h16bb863_0    defaults
readline                  7.0                  hc1231fa_4    defaults
requests                  2.18.4           py36h4516966_1    defaults
ruamel_yaml               0.11.14          py36h9d7ade0_2    defaults
scipy                     1.0.0                     <pip>
setuptools                38.5.1                    <pip>
setuptools                36.5.0           py36h2134326_0    defaults
sip                       4.18.1           py36h2824476_2    defaults
six                       1.11.0                    <pip>
six                       1.11.0           py36h0e22d5e_1    defaults
sqlite                    3.20.1               h7e4c145_2    defaults
tables                    3.4.2                     <pip>
tensorflow                1.5.0                     <pip>
tensorflow-tensorboard    1.5.1                     <pip>
tk                        8.6.7                h35a86e2_3    defaults
tornado                   4.5.3                    py36_0    defaults
traitlets                 4.3.2            py36h65bd3ce_0    defaults
urllib3                   1.22             py36h68b9469_0    defaults
virtualenv                15.1.0                    <pip>
virtualenv-clone          0.2.6                     <pip>
Werkzeug                  0.14.1                    <pip>
wheel                     0.30.0           py36h5eb2c71_1    defaults
wheel                     0.30.0                    <pip>
whitenoise                3.3.1                     <pip>
xz                        5.2.3                h0278029_2    defaults
yaml                      0.1.7                hc338f04_2    defaults
zlib                      1.2.11               hf3cbc9b_2    defaults
```

**Comment by csoja** [comment]
You have installed pip v9.0.2 with <pip>.  There is a known issue with v9.0.2 and Navigator - Navigator v1.8.2 will be coming out soon with a fix for it.  In the meantime, please downgrade pip to v9.0.2 or upgrade it to v9.0.3.  Generally, we recommend using conda to update pip, and not pip to update pip when using Anaconda.

**Comment by williamswl** [comment]
I solved this issue by
`conda update --all`
