### ISSUE TITLE
Import error matplotlib.pyplot (undefined symbol: xcb_dri3_get_supported_modifiers)

### ISSUE THREAD

**Issue by Bladefidz** [ContinuumIO/anaconda-issues#8988]
### Actual Behavior

I used Spyder 3.2.8 with Python 3.6.4 Anaconda custom (64-bit). I just got **ImportError: /usr/lib/x86_64-linux-gnu/mesa/libGL.so.1: undefined symbol: xcb_dri3_get_supported_modifiers** when trying to import matplotlib.pyplot as plt 

```
in[27] import matplotlib.pyplot as plt

Traceback (most recent call last):

  File "<ipython-input-27-a0d2faabd9e9>", line 1, in <module>
    import matplotlib.pyplot as plt

  File "/opt/anaconda3/lib/python3.6/site-packages/matplotlib/pyplot.py", line 115, in <module>
    _backend_mod, new_figure_manager, draw_if_interactive, _show = pylab_setup()

  File "/opt/anaconda3/lib/python3.6/site-packages/matplotlib/backends/__init__.py", line 62, in pylab_setup
    [backend_name], 0)

  File "/opt/anaconda3/lib/python3.6/site-packages/matplotlib/backends/backend_qt5agg.py", line 15, in <module>
    from .backend_qt5 import (

  File "/opt/anaconda3/lib/python3.6/site-packages/matplotlib/backends/backend_qt5.py", line 19, in <module>
    import matplotlib.backends.qt_editor.figureoptions as figureoptions

  File "/opt/anaconda3/lib/python3.6/site-packages/matplotlib/backends/qt_editor/figureoptions.py", line 20, in <module>
    import matplotlib.backends.qt_editor.formlayout as formlayout

  File "/opt/anaconda3/lib/python3.6/site-packages/matplotlib/backends/qt_editor/formlayout.py", line 54, in <module>
    from matplotlib.backends.qt_compat import QtGui, QtWidgets, QtCore

  File "/opt/anaconda3/lib/python3.6/site-packages/matplotlib/backends/qt_compat.py", line 140, in <module>
    from PyQt5 import QtCore, QtGui, QtWidgets

ImportError: /usr/lib/x86_64-linux-gnu/mesa/libGL.so.1: undefined symbol: xcb_dri3_get_supported_modifiers
```

### Expected Behavior

But, when I used **/usr/bin/python3** to compile corresponding file, matplotlib.pyplot imported without any errors or warning.

##### Anaconda or Miniconda version:

```
conda --version
conda 4.5.0
```

##### Operating System:

Linux Mint 18.3 Cinnamon 64-bit / Ubuntu 16.04 64-bit

##### `conda info`

```
active environment : None
       user config file : /home/bladefidz/.condarc
 populated config files : /home/bladefidz/.condarc
          conda version : 4.5.0
    conda-build version : 3.4.1
         python version : 3.6.4.final.0
       base environment : /opt/anaconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/linux-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/linux-64
                          https://repo.anaconda.com/pkgs/pro/noarch
          package cache : /opt/anaconda3/pkgs
                          /home/bladefidz/.conda/pkgs
       envs directories : /opt/anaconda3/envs
                          /home/bladefidz/.conda/envs
               platform : linux-64
             user-agent : conda/4.5.0 requests/2.18.4 CPython/3.6.4 Linux/4.13.0-32-generic linuxmint/18.3 glibc/2.23
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False

```

##### `conda list --show-channel-urls`

```
# packages in environment at /opt/anaconda3:
#
# Name                    Version                   Build  Channel
_ipyw_jlab_nb_ext_conf    0.1.0            py36he11e457_0    defaults
_r-mutex                  1.0.0               anacondar_1    defaults
alabaster                 0.7.10           py36h306e16b_0    defaults
anaconda                  custom           py36hbbc8b67_0    defaults
anaconda-client           1.6.12                   py36_0    defaults
anaconda-navigator        1.8.1                    py36_0    defaults
anaconda-project          0.8.2            py36h44fb852_0    defaults
asn1crypto                0.24.0                   py36_0    defaults
astroid                   1.6.1                    py36_0    defaults
astropy                   2.0.3            py36h14c3975_0    defaults
attrs                     17.4.0                   py36_0    defaults
babel                     2.5.3                    py36_0    defaults
backports                 1.0              py36hfa02d7e_1    defaults
backports.shutil_get_terminal_size 1.0.0            py36hfea85ff_2    defaults
beautifulsoup4            4.6.0            py36h49b8c8c_1    defaults
bitarray                  0.8.1            py36h14c3975_1    defaults
bkcharts                  0.2              py36h735825a_0    defaults
blaze                     0.11.3           py36h4e06776_0    defaults
bleach                    2.1.2                    py36_0    defaults
bokeh                     0.12.13          py36h2f9c1c0_0    defaults
boto                      2.48.0           py36h6e4cd66_1    defaults
bottle                    0.12.13                  py36_0    conda-forge
bottleneck                1.2.1            py36haac1ea0_0    defaults
bzip2                     1.0.6                h9a117a8_4    defaults
ca-certificates           2017.08.26           h1d4fec5_0    anaconda
cairo                     1.14.12              h77bcde2_0    defaults
certifi                   2018.1.18                py36_0    anaconda
cffi                      1.11.4           py36h9745a5d_0    defaults
chardet                   3.0.4            py36h0f667ec_1    defaults
click                     6.7              py36h5253387_0    defaults
cloudpickle               0.5.2                    py36_1    defaults
clyent                    1.2.2            py36h7e57e65_1    defaults
colorama                  0.3.9            py36h489cec4_0    defaults
conda                     4.5.0                    py36_0    anaconda
conda-build               3.4.1                    py36_0    defaults
conda-env                 2.6.0                h36134e3_1    defaults
conda-verify              2.0.0            py36h98955d8_0    defaults
contextlib2               0.5.5            py36h6c84a62_0    defaults
cryptography              2.1.4            py36hd09be54_0    defaults
curl                      7.58.0               h84994c4_0    defaults
cycler                    0.10.0           py36h93f1223_0    defaults
cyrus-sasl                2.1.26               h1dd3434_1    defaults
cython                    0.27.3           py36h1860423_0    defaults
cytoolz                   0.9.0            py36h14c3975_0    defaults
dask                      0.16.1                   py36_0    defaults
dask-core                 0.16.1                   py36_0    defaults
datashape                 0.5.4            py36h3ad6b5c_0    defaults
dbus                      1.12.2               hc3f9b76_1    defaults
decorator                 4.2.1                    py36_0    defaults
distributed               1.20.2                   py36_0    defaults
docutils                  0.14             py36hb0f60f5_0    defaults
entrypoints               0.2.3            py36h1aec115_2    defaults
et_xmlfile                1.0.1            py36hd6bccc3_0    defaults
expat                     2.2.5                he0dffb1_0    defaults
fastcache                 1.0.2            py36h14c3975_2    defaults
filelock                  2.0.13           py36h646ffb5_0    defaults
flask                     0.12.2           py36hb24657c_0    defaults
flask-cors                3.0.3            py36h2d857d3_0    defaults
font-ttf-dejavu-sans-mono 2.37                 h6964260_0    defaults
font-ttf-inconsolata      2.001                hcb22688_0    defaults
font-ttf-source-code-pro  2.030                h7457263_0    defaults
font-ttf-ubuntu           0.83                 h8b1ccd4_0    defaults
fontconfig                2.12.4               h88586e7_1    defaults
fonts-anaconda            1                    h8fa9717_0    defaults
freetype                  2.8                  hab7d2ae_1    defaults
get_terminal_size         1.0.0                haa9412d_0    defaults
gevent                    1.2.2            py36h2fe25dc_0    defaults
glib                      2.53.6               h5d9569c_2    defaults
glob2                     0.6              py36he249c77_0    defaults
gmp                       6.1.2                h6c8ec71_1    defaults
gmpy2                     2.0.8            py36hc8893dd_2    defaults
graphite2                 1.3.10               hf63cedd_1    defaults
greenlet                  0.4.12           py36h2d503a6_0    defaults
gsl                       2.2.1                h0c605f7_3    defaults
gst-plugins-base          1.12.4               h33fb286_0    defaults
gstreamer                 1.12.4               hb53b477_0    defaults
h5py                      2.7.1            py36h3585f63_0    defaults
harfbuzz                  1.7.4                hc5b324e_0    defaults
hdf5                      1.10.1               h9caa474_1    defaults
heapdict                  1.0.0                    py36_2    defaults
html5lib                  1.0.1            py36h2f9c1c0_0    defaults
icu                       58.2                 h9c2bf20_1    defaults
idna                      2.6              py36h82fb2a8_1    defaults
imageio                   2.2.0            py36he555465_0    defaults
imagesize                 0.7.1            py36h52d8127_0    defaults
intel-openmp              2018.0.0             hc7b2577_8    defaults
ipykernel                 4.8.0                    py36_0    defaults
ipython                   6.2.1            py36h88c514a_1    defaults
ipython_genutils          0.2.0            py36hb52b0d5_0    defaults
ipywidgets                7.1.1                    py36_0    defaults
isort                     4.2.15           py36had401c0_0    defaults
itsdangerous              0.24             py36h93cc618_1    defaults
jbig                      2.1                  hdba287a_0    defaults
jdcal                     1.3              py36h4c697fb_0    defaults
jedi                      0.11.1                   py36_0    defaults
jinja2                    2.10             py36ha16c418_0    defaults
jpeg                      9b                   h024ee3a_2    defaults
jsonschema                2.6.0            py36h006f8b5_0    defaults
jupyter                   1.0.0                    py36_4    defaults
jupyter_client            5.2.2                    py36_0    defaults
jupyter_console           5.2.0            py36he59e554_1    defaults
jupyter_core              4.4.0            py36h7c827e3_0    defaults
jupyterlab                0.31.12                  py36_0    defaults
jupyterlab_launcher       0.10.2                   py36_0    defaults
kiwisolver                1.0.1            py36h764f252_0    anaconda
krb5                      1.14.2               hcdc1b81_6    defaults
lazy-object-proxy         1.3.1            py36h10fcdad_0    defaults
libcurl                   7.58.0               h1ad7b7a_0    defaults
libedit                   3.1                  heed3624_0    defaults
libffi                    3.2.1                hd88cf55_4    defaults
libgcc-ng                 7.2.0                h7cc24e2_2    defaults
libgfortran-ng            7.2.0                h9f7466a_2    defaults
libntlm                   1.4                  h14c3975_2    defaults
libpng                    1.6.34               hb9fc6fc_0    defaults
libsodium                 1.0.15               hf101ebd_0    defaults
libssh2                   1.8.0                h9cfc8f7_4    defaults
libstdcxx-ng              7.2.0                h7a57d05_2    defaults
libtiff                   4.0.9                h28f6b97_0    defaults
libtool                   2.4.6                h544aabb_3    defaults
libuuid                   1.0.3                h1bed415_2    defaults
libxcb                    1.12                 hcd93eb1_4    defaults
libxml2                   2.9.7                h26e45fe_0    defaults
libxslt                   1.1.32               h1312cb7_0    defaults
llvmlite                  0.21.0           py36ha241eea_0    defaults
locket                    0.2.0            py36h787c0ad_1    defaults
lxml                      4.1.1            py36hf71bdeb_1    defaults
lzo                       2.10                 h49e0be7_2    defaults
markupsafe                1.0              py36hd9260cd_1    defaults
matplotlib                2.2.2            py36h0e671d2_0    anaconda
mccabe                    0.6.1            py36h5ad9710_1    defaults
mistune                   0.8.3                    py36_0    defaults
mkl                       2018.0.1             h19d6760_4    defaults
mkl-service               1.1.2            py36h17a0993_4    defaults
mpc                       1.0.3                hec55b23_5    defaults
mpfr                      3.1.5                h11a74b3_2    defaults
mpmath                    1.0.0            py36hfeacd6b_2    defaults
msgpack-python            0.5.1            py36h6bb024c_0    defaults
multipledispatch          0.4.9            py36h41da3fb_0    defaults
navigator-updater         0.1.0            py36h14770f7_0    defaults
nbconvert                 5.3.1            py36hb41ffb7_0    defaults
nbformat                  4.4.0            py36h31c9010_0    defaults
ncurses                   6.0                  h9df7e31_2    defaults
networkx                  2.1                      py36_0    defaults
nltk                      3.2.5            py36h7532b22_0    defaults
nose                      1.3.7            py36hcdf7029_2    defaults
notebook                  5.4.0                    py36_0    defaults
numba                     0.36.2          np114py36hc6662d5_0    defaults
numexpr                   2.6.4            py36hc4a3f9a_0    defaults
numpy                     1.14.0           py36h3dfced4_1    defaults
numpydoc                  0.7.0            py36h18f165f_0    defaults
odo                       0.5.1            py36h90ed295_0    defaults
olefile                   0.45.1                   py36_0    defaults
openpyxl                  2.4.10                   py36_0    defaults
openssl                   1.0.2n               hb7f436b_0    anaconda
packaging                 16.8             py36ha668100_1    defaults
pandas                    0.22.0           py36hf484d3e_0    defaults
pandoc                    1.19.2.1             hea2e7c5_1    defaults
pandocfilters             1.4.2            py36ha6701b7_1    defaults
pango                     1.41.0               hd475d92_0    defaults
parso                     0.1.1            py36h35f843b_0    defaults
partd                     0.3.8            py36h36fd896_0    defaults
patchelf                  0.9                  hf79760b_2    defaults
path.py                   10.5             py36h55ceabb_0    defaults
pathlib2                  2.3.0            py36h49efa8e_0    defaults
patsy                     0.5.0                    py36_0    defaults
pcre                      8.41                 hc27e229_1    defaults
pep8                      1.7.1                    py36_0    defaults
pexpect                   4.3.1                    py36_0    defaults
pickleshare               0.7.4            py36h63277f8_0    defaults
pillow                    5.0.0            py36h3deb7b8_0    defaults
pip                       9.0.1            py36h6c6f9ce_4    defaults
pixman                    0.34.0               hceecf20_3    defaults
pkginfo                   1.4.1            py36h215d178_1    defaults
pluggy                    0.6.0            py36hb689045_0    defaults
ply                       3.10             py36hed35086_0    defaults
prompt_toolkit            1.0.15           py36h17d85b1_0    defaults
psutil                    5.4.3            py36h14c3975_0    defaults
ptyprocess                0.5.2            py36h69acd42_0    defaults
py                        1.5.2            py36h29bf505_0    defaults
pycodestyle               2.3.1            py36hf609f19_0    defaults
pycosat                   0.6.3            py36h0a5515d_0    defaults
pycparser                 2.18             py36hf9f622e_1    defaults
pycrypto                  2.6.1            py36h14c3975_7    defaults
pycurl                    7.43.0.1         py36hb7f436b_0    defaults
pyflakes                  1.6.0            py36h7bd6a15_0    defaults
pygments                  2.2.0            py36h0d3125c_0    defaults
pylint                    1.8.2                    py36_0    defaults
pymongo                   3.4.0                    py36_0    defaults
pyodbc                    4.0.22           py36hf484d3e_0    defaults
pyopenssl                 17.5.0           py36h20ba746_0    defaults
pyparsing                 2.2.0            py36hee85983_1    defaults
pyqt                      5.6.0            py36h0386399_5    defaults
pysocks                   1.6.7            py36hd97a5b1_1    defaults
pytables                  3.4.2            py36h3b5282a_2    defaults
pytest                    3.3.2                    py36_0    defaults
python                    3.6.4                hc3d631a_1    defaults
python-dateutil           2.6.1            py36h88d3b88_1    defaults
pytz                      2017.3           py36h63b9c63_0    defaults
pywavelets                0.5.2            py36he602eb0_0    defaults
pyyaml                    3.12             py36hafb9ca4_1    defaults
pyzmq                     16.0.3           py36he2533c7_0    defaults
qt                        5.6.2               hd25b39d_14    defaults
qtawesome                 0.4.4            py36h609ed8c_0    defaults
qtconsole                 4.3.1            py36h8f73b5b_0    defaults
qtpy                      1.3.1            py36h3691cc8_0    defaults
r-assertthat              0.2.0            r342h06193eb_0    defaults
r-backports               1.1.1            r342h9a9f1f2_0    defaults
r-base                    3.4.2                haf99962_0    defaults
r-base64enc               0.1_3            r342h7c929ec_4    defaults
r-bh                      1.65.0_1         r342h2d7c2ce_0    defaults
r-bindr                   0.1              r342hdee8079_0    defaults
r-bindrcpp                0.2              r342h4ea5b31_0    defaults
r-bit                     1.1_12           r342h7a05cba_0    defaults
r-bit64                   0.9_7            r342hcc44603_0    defaults
r-bitops                  1.0_6            r342hd891396_4    defaults
r-blob                    1.1.0            r342hf606c5c_0    defaults
r-boot                    1.3_20           r342ha5ac741_0    defaults
r-broom                   0.4.2            r342h90c284a_0    defaults
r-caret                   6.0_77           r342h201f268_0    defaults
r-catools                 1.17.1           r342hf01772b_4    defaults
r-cellranger              1.1.0            r342h51baf57_0    defaults
r-class                   7.3_14           r342h4797347_4    defaults
r-cluster                 2.0.6            r342hcb72a25_0    defaults
r-codetools               0.2_15           r342hc9ffb9b_0    defaults
r-colorspace              1.3_2            r342h81b277d_0    defaults
r-config                  0.2              r342hcf13b6a_0    defaults
r-crayon                  1.3.4            r342h0ed458a_0    defaults
r-curl                    3.0              r342hba591e3_0    defaults
r-cvst                    0.2_1            r342h830f301_0    defaults
r-data.table              1.10.4_1         r342h3908b10_0    defaults
r-dbi                     0.7              r342h835dbd3_0    defaults
r-dbplyr                  1.1.0            r342h3750f00_0    defaults
r-ddalpha                 1.3.1            r342hd2d3f94_0    defaults
r-deoptimr                1.0_8            r342h996e1ad_0    defaults
r-dichromat               2.0_0            r342h341c752_4    defaults
r-digest                  0.6.12           r342hee14287_0    defaults
r-dimred                  0.1.0            r342hb158d3e_0    defaults
r-dplyr                   0.7.4            r342hee63e26_0    defaults
r-drr                     0.0.2            r342h0fe108c_0    defaults
r-essentials              1.7.0            r342hf65ed6a_0    defaults
r-evaluate                0.10.1           r342hb679cc2_0    defaults
r-forcats                 0.2.0            r342h5fcb364_0    defaults
r-foreach                 1.4.3            r342h49221b0_4    defaults
r-foreign                 0.8_69           r342hbd6b6bb_0    defaults
r-formatr                 1.5              r342h0e06a18_0    defaults
r-ggplot2                 2.2.1            r342h8b6cf70_0    defaults
r-gistr                   0.4.0            r342h5cd5773_0    defaults
r-glmnet                  2.0_13           r342h0aac7f1_0    defaults
r-glue                    1.1.1            r342h3154e12_0    defaults
r-gower                   0.1.2            r342h54e18f5_0    defaults
r-gtable                  0.2.0            r342h8e3b2c8_0    defaults
r-haven                   1.1.0            r342h8909e7d_0    defaults
r-hexbin                  1.27.1           r342h72fd8d9_4    defaults
r-highr                   0.6              r342h2351100_0    defaults
r-hms                     0.3              r342ha729a9b_0    defaults
r-htmltools               0.3.6            r342h4080c21_0    defaults
r-htmlwidgets             0.9              r342h7fcc9b6_0    defaults
r-httpuv                  1.3.5            r342ha5ddd88_0    defaults
r-httr                    1.3.1            r342h7aba7de_0    defaults
r-ipred                   0.9_6            r342h7d58d5b_0    defaults
r-irdisplay               0.4.4            r342hc31a1b2_0    defaults
r-irkernel                0.8.9            r342hfe3cb8f_0    defaults
r-iterators               1.0.8            r342h4caec00_4    defaults
r-jsonlite                1.5              r342hf92f79e_0    defaults
r-kernlab                 0.9_25           r342hd770e69_0    defaults
r-kernsmooth              2.23_15          r342hdc3efa4_4    defaults
r-knitr                   1.17             r342h6500ef9_0    defaults
r-labeling                0.3              r342h7c30189_4    defaults
r-lattice                 0.20_35          r342h0f762c2_0    defaults
r-lava                    1.5.1            r342h598eca9_0    defaults
r-lazyeval                0.2.0            r342h346dbdc_0    defaults
r-lubridate               1.6.0            r342h47739ec_0    defaults
r-magrittr                1.5              r342h895a831_4    defaults
r-maps                    3.2.0            r342h79c810f_0    defaults
r-markdown                0.8              r342h4cc6e3e_0    defaults
r-mass                    7.3_47           r342hd8605c9_0    defaults
r-matrix                  1.2_11           r342h3a55fe1_0    defaults
r-mgcv                    1.8_22           r342h176cc83_0    defaults
r-mime                    0.5              r342h01856a9_0    defaults
r-miniui                  0.1.1            r342h33c7739_0    defaults
r-mnormt                  1.5_5            r342he1a489d_0    defaults
r-modelmetrics            1.1.0            r342h5a23eb1_0    defaults
r-modelr                  0.1.1            r342heb933ea_0    defaults
r-mongolite               1.2              r342hdcf03d2_0    defaults
r-munsell                 0.4.3            r342h79883fb_0    defaults
r-nlme                    3.1_131          r342h7f704e8_0    defaults
r-nnet                    7.3_12           r342ha98c111_0    defaults
r-numderiv                2016.8_1         r342h12eb246_0    defaults
r-odbc                    1.1.2            r342hf7c7794_0    defaults
r-openssl                 0.9.7            r342h1e3c16d_0    defaults
r-packrat                 0.4.8_1          r342h7bab2f7_0    defaults
r-pbdzmq                  0.2_6            r342h934a24f_0    defaults
r-pkgconfig               2.0.1            r342h5d9b92e_0    defaults
r-pki                     0.1_5.1          r342hba91d42_0    defaults
r-plogr                   0.1_1            r342h6d7f4c2_0    defaults
r-plyr                    1.8.4            r342h876901b_0    defaults
r-prodlim                 1.6.1            r342hd95c883_0    defaults
r-profvis                 0.3.3            r342h36dbb6c_0    defaults
r-pryr                    0.1.2            r342hf3bf84b_0    defaults
r-psych                   1.7.8            r342h1e2dc86_0    defaults
r-purrr                   0.2.3            r342h7916a1c_0    defaults
r-quantmod                0.4_11           r342h9c9c021_0    defaults
r-r6                      2.2.2            r342hcc750b5_0    defaults
r-randomforest            4.6_12           r342h41e62a9_4    defaults
r-rappdirs                0.3.1            r342h03ed50e_0    defaults
r-rbokeh                  0.5.0            r342h257354a_0    defaults
r-rcolorbrewer            1.1_2            r342h0dda8fb_0    defaults
r-rcpp                    0.12.13          r342h9f83869_0    defaults
r-rcpproll                0.2.2            r342hdd0cc16_0    defaults
r-rcurl                   1.95_4.8         r342hecb3894_0    defaults
r-readr                   1.1.1            r342hb25467c_0    defaults
r-readxl                  1.0.0            r342h1e5739b_0    defaults
r-recipes                 0.1.0            r342h0924b81_0    defaults
r-recommended             3.4.2                h1751db4_0    defaults
r-rematch                 1.0.1            r342he3f91f1_0    defaults
r-repr                    0.12.0           r342hde08b23_0    defaults
r-reshape2                1.4.2            r342h2e254a0_0    defaults
r-rjava                   0.9_9            r342h9890981_0    defaults
r-rjdbc                   0.2_5            r342he0388cf_0    defaults
r-rjsonio                 1.3_0            r342h5685322_4    defaults
r-rlang                   0.1.2            r342hc878738_0    defaults
r-rmarkdown               1.6              r342hacd9e3e_2    defaults
r-robustbase              0.92_7           r342h6021a74_0    defaults
r-rpart                   4.1_11           r342hd35cc14_0    defaults
r-rprojroot               1.2              r342hd69aa9e_0    defaults
r-rsconnect               0.8.5            r342h3a8d77b_0    defaults
r-rstudioapi              0.7              r342hedff9e9_0    defaults
r-rvest                   0.3.2            r342h8e81af5_0    defaults
r-scales                  0.5.0            r342h876bdd3_0    defaults
r-selectr                 0.3_1            r342hd6c1ff9_0    defaults
r-sfsmisc                 1.1_1            r342hadb04b4_0    defaults
r-shiny                   1.0.5            r342hc0a01ce_0    defaults
r-sourcetools             0.1.6            r342h519fec0_0    defaults
r-sparklyr                0.6.3            r342hac80a45_0    defaults
r-spatial                 7.3_11           r342hff2a1d0_4    defaults
r-stringi                 1.1.6            r342hf484d3e_0    defaults
r-stringr                 1.2.0            r342h701d218_0    defaults
r-survival                2.41_3           r342hac888f2_0    defaults
r-tibble                  1.3.4            r342h041fa31_0    defaults
r-tidyr                   0.7.1            r342h1bc61e7_0    defaults
r-tidyselect              0.2.2            r342h04f720c_0    defaults
r-tidyverse               1.1.1            r342hf9e2102_0    defaults
r-timedate                3012.100         r342h48d2e88_4    defaults
r-ttr                     0.23_2           r342hf82c04a_0    defaults
r-uuid                    0.1_2            r342h1393287_4    defaults
r-viridislite             0.2.0            r342h3706391_0    defaults
r-withr                   2.0.0            r342hfa1897f_0    defaults
r-xml2                    1.1.1            r342h3ff9a91_0    defaults
r-xtable                  1.8_2            r342hb75f6e7_0    defaults
r-xts                     0.10_0           r342h17852d6_4    defaults
r-yaml                    2.1.14           r342h72d8650_0    defaults
r-zoo                     1.8_0            r342h9faeba2_0    defaults
readline                  7.0                  ha6073c6_4    defaults
requests                  2.18.4           py36he2e5f8d_1    defaults
rope                      0.10.7           py36h147e2ec_0    defaults
rstudio                   1.1.383              h2c9cdda_2    defaults
ruamel_yaml               0.15.35          py36h14c3975_1    defaults
scikit-image              0.13.1           py36h14c3975_1    defaults
scikit-learn              0.19.1           py36h7aa7ec6_0    defaults
scipy                     1.0.0            py36hbf646e7_0    defaults
seaborn                   0.8.1            py36hfad7ec4_0    defaults
send2trash                1.4.2                    py36_0    defaults
setuptools                38.4.0                   py36_0    defaults
simplegeneric             0.8.1                    py36_2    defaults
singledispatch            3.4.0.3          py36h7a266c3_0    defaults
sip                       4.18.1           py36h51ed4ed_2    defaults
six                       1.11.0           py36h372c433_1    defaults
snowballstemmer           1.2.1            py36h6febd40_0    defaults
sortedcollections         0.5.3            py36h3c761f9_0    defaults
sortedcontainers          1.5.9                    py36_0    defaults
sphinx                    1.6.6                    py36_0    defaults
sphinxcontrib             1.0              py36h6d0f590_1    defaults
sphinxcontrib-websupport  1.0.1            py36hb5cb234_1    defaults
spyder                    3.2.8                    py36_0    defaults
sqlalchemy                1.2.1            py36h14c3975_0    defaults
sqlite                    3.22.0               h1bed415_0    defaults
statsmodels               0.8.0            py36h8533d0b_0    defaults
sympy                     1.1.1            py36hc6d1c1c_0    defaults
tblib                     1.3.2            py36h34cf8b6_0    defaults
terminado                 0.8.1                    py36_1    defaults
testpath                  0.3.1            py36h8cadb63_0    defaults
tk                        8.6.7                hc745277_3    defaults
toolz                     0.9.0                    py36_0    defaults
tornado                   4.5.3                    py36_0    defaults
traitlets                 4.3.2            py36h674d592_0    defaults
typing                    3.6.2            py36h7da032a_0    defaults
unicodecsv                0.14.1           py36ha668878_0    defaults
unixodbc                  2.3.4                hc36303a_1    defaults
urllib3                   1.22             py36hbe7ace6_0    defaults
wcwidth                   0.1.7            py36hdf4376a_0    defaults
webencodings              0.5.1            py36h800622e_1    defaults
werkzeug                  0.14.1                   py36_0    defaults
wheel                     0.30.0           py36hfd4bba0_1    defaults
widgetsnbextension        3.1.0                    py36_0    defaults
wrapt                     1.10.11          py36h28b7045_0    defaults
xlrd                      1.1.0            py36h1db9f0c_1    defaults
xlsxwriter                1.0.2            py36h3de1aca_0    defaults
xlwt                      1.3.0            py36h7b00a1f_0    defaults
xz                        5.2.3                h55aa19d_2    defaults
yaml                      0.1.7                had09818_2    defaults
zeromq                    4.2.2                hbedb6e5_2    defaults
zict                      0.1.3            py36h3a3bf81_0    defaults
zlib                      1.2.11               ha838bed_2    defaults
```

**Comment by danyXu** [comment]
did you resolved this problem

**Comment by Bladefidz** [comment]
@danyXu, to be honest, I do not exactly how this problem occurred and to be solved since a day after this problem occured, my previous OS just break due false package installation. So after install new OS, the problem seems not re occured.

**Comment by Bladefidz** [comment]
@dannyXu thank you for follow up. Recently, I got simillar problem when trying to open rstudio installed on opensuse tumbleweed. So *.so libraries just missing, so I just do some tricks: Find related *.so libraries in google, download it and placed inside /usr/share directory.

**Comment by neinhus** [comment]
This problem could be caused if libGL is linked against or picking up the wrong libxcb library. Using ldd, I would check which copy of libxcb libGL is using. Maybe Anaconda ships its own version of libxcb and it is not picked up.
