### ISSUE TITLE
Jupyter Notebook not opening 

### ISSUE THREAD

**Issue by hawkingsteven** [ContinuumIO/anaconda-issues#8999]
Darwin StevenZirovsMBP 17.4.0 Darwin Kernel Version 17.4.0: Sun Dec 17 09:19:54 PST 2017; root:xnu-4570.41.2~1/RELEASE_X86_64 x86_64

High Sierra 10.13.3

Hello, I have a problem opening jupyter notebook and just running conda info, and conda list 

StevenZakirovs-MacBook-Pro:~ stevenzakirov$ jupyter notebook
Traceback (most recent call last):
  File "/Users/stevenzakirov/anaconda2/bin/jupyter", line 7, in <module>
    from jupyter_core.command import main
  File "/Users/stevenzakirov/anaconda2/lib/python2.7/site-packages/jupyter_core/command.py", line 11, in <module>
    import argparse
  File "/Users/stevenzakirov/anaconda2/lib/python2.7/argparse.py", line 86, in <module>
    import copy as _copy
  File "/Users/stevenzakirov/anaconda2/lib/python2.7/copy.py", line 52, in <module>
    import weakref
  File "/Users/stevenzakirov/anaconda2/lib/python2.7/weakref.py", line 14, in <module>
    from _weakref import (
ImportError: cannot import name _remove_dead_weakref
StevenZakirovs-MacBook-Pro:~ stevenzakirov$ conda list
Traceback (most recent call last):
  File "/Users/stevenzakirov/anaconda2/bin/conda", line 7, in <module>
    from conda.cli import main
  File "/Users/stevenzakirov/anaconda2/lib/python2.7/site-packages/conda/__init__.py", line 10, in <module>
    from .common.compat import iteritems, text_type
  File "/Users/stevenzakirov/anaconda2/lib/python2.7/site-packages/conda/common/compat.py", line 113, in <module>
    from io import open as io_open  # NOQA
  File "/Users/stevenzakirov/anaconda2/lib/python2.7/io.py", line 51, in <module>
    import _io
ImportError: dlopen(/Users/stevenzakirov/anaconda2/lib/python2.7/lib-dynload/_io.so, 2): Symbol not found: __PyCodecInfo_GetIncrementalDecoder
  Referenced from: /Users/stevenzakirov/anaconda2/lib/python2.7/lib-dynload/_io.so
  Expected in: flat namespace
 in /Users/stevenzakirov/anaconda2/lib/python2.7/lib-dynload/_io.so
StevenZakirovs-MacBook-Pro:~ stevenzakirov$ conda info
Traceback (most recent call last):
  File "/Users/stevenzakirov/anaconda2/bin/conda", line 7, in <module>
    from conda.cli import main
  File "/Users/stevenzakirov/anaconda2/lib/python2.7/site-packages/conda/__init__.py", line 10, in <module>
    from .common.compat import iteritems, text_type
  File "/Users/stevenzakirov/anaconda2/lib/python2.7/site-packages/conda/common/compat.py", line 113, in <module>
    from io import open as io_open  # NOQA
  File "/Users/stevenzakirov/anaconda2/lib/python2.7/io.py", line 51, in <module>
    import _io
ImportError: dlopen(/Users/stevenzakirov/anaconda2/lib/python2.7/lib-dynload/_io.so, 2): Symbol not found: __PyCodecInfo_GetIncrementalDecoder
  Referenced from: /Users/stevenzakirov/anaconda2/lib/python2.7/lib-dynload/_io.so
  Expected in: flat namespace
 in /Users/stevenzakirov/anaconda2/lib/python2.7/lib-dynload/_io.so

**Comment by jjhelmus** [comment]
@hawkingsteven Can you provide the information requested in the issue template?  Specifically the output of `conda info` and `conda list --show-channel-urls`.
