### ISSUE TITLE
Jupyter notebook run start error

### ISSUE THREAD

**Issue by ramza0925** [ContinuumIO/anaconda-issues#9037]
Jupyter notebook program in anconda navigator does not start to work. 
I hope to solve this problem. quickly!

error message :  
Traceback (most recent call last):
File "C:\Python\Anaconda3\Scripts\jupyter-notebook-script.py", line 6, in 
from notebook.notebookapp import main
File "C:\Python\Anaconda3\lib\site-packages\notebook\notebookapp.py", line 78, in 
from .services.kernels.kernelmanager import MappingKernelManager
File "C:\Python\Anaconda3\lib\site-packages\notebook\services\kernels\kernelmanager.py", line 19, in 
from jupyter_client.session import Session
File "C:\Python\Anaconda3\lib\site-packages\jupyter_client\session.py", line 61, in 
from jupyter_client.jsonutil import extract_dates, squash_dates, date_default
File "C:\Python\Anaconda3\lib\site-packages\jupyter_client\jsonutil.py", line 11, in 
from dateutil.parser import parse as _dateutil_parse
ModuleNotFoundError: No module named 'dateutil.parser'

**Comment by jjhelmus** [comment]
Can you provide the output of `conda info` and `conda list --show-channel-urls`?

It appears as if python-dateutil is not installed or install incorrectly which is odd as it is a dependency of jupyter_client.  `conda install python-dateutil` may fix the issue.

**Comment by Musdem88** [comment]
hi there, i got the following error message after installing tensorflow on my python 3.6. Now my jupyter notebook is not working neither from conda prompt or anaconda launcher. thanks for your help.

raceback (most recent call last):
  File "C:\Users\MustafaDemir\Anaconda3\lib\site-packages\anaconda_navigator\exceptions.py", line 75, in exception_handler
    return_value = func(*args, **kwargs)
  File "C:\Users\MustafaDemir\Anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 138, in start_app
    window = run_app(splash)
  File "C:\Users\MustafaDemir\Anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 64, in run_app
    window = MainWindow(splash=splash, tab_project=False)
  File "C:\Users\MustafaDemir\Anaconda3\lib\site-packages\anaconda_navigator\widgets\main_window.py", line 163, in __init__
    self.api = AnacondaAPI()
  File "C:\Users\MustafaDemir\Anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 2086, in AnacondaAPI
    ANACONDA_API = _AnacondaAPI()
  File "C:\Users\MustafaDemir\Anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 89, in __init__
    self._conda_api = CondaAPI()
  File "C:\Users\MustafaDemir\Anaconda3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 1699, in CondaAPI
    CONDA_API = _CondaAPI()
  File "C:\Users\MustafaDemir\Anaconda3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 347, in __init__
    self.set_conda_prefix()
  File "C:\Users\MustafaDemir\Anaconda3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 506, in set_conda_prefix
    self.ROOT_PREFIX = info['root_prefix']
TypeError: byte indices must be integers or slices, not str

**Comment by goanpeca** [comment]
@Musdem88 please post on a new issue as the problems are unrelated
