### ISSUE TITLE
Navigator Crashes while launching

### ISSUE THREAD

**Issue by SpainTopher** [ContinuumIO/anaconda-issues#9044]
### Actual Behavior

Click Anaconda-Navigator icon or open via terminal on Mac High Sierra 10.13.3, icon bounces a few seconds in dock and then closes

### Expected Behavior

Anaconda Navigator should open

### Steps to Reproduce

Click icon or initiate via terminal

##### `conda info`

```
_ipyw_jlab_nb_ext_conf-0.1.0-py36h2fc01ae_0.json
alabaster-0.7.10-py36h174008c_0.json
anaconda-5.1.0-py36_2.json
anaconda-client-1.6.9-py36_0.json
anaconda-navigator-1.7.0-py36_0.json
anaconda-project-0.8.2-py36h9ee5d53_0.json
appnope-0.1.0-py36hf537a9a_0.json
appscript-1.0.1-py36h9e71e49_1.json
asn1crypto-0.24.0-py36_0.json
astroid-1.6.1-py36_0.json
astropy-2.0.3-py36h1de35cc_0.json
attrs-17.4.0-py36_0.json
babel-2.5.3-py36_0.json
backports-1.0-py36ha3c1827_1.json
backports.shutil_get_terminal_size-1.0.0-py36hd7a2ee4_2.json
beautifulsoup4-4.6.0-py36h72d3c9f_1.json
bitarray-0.8.1-py36h1de35cc_1.json
bkcharts-0.2-py36h073222e_0.json
blaze-0.11.3-py36h02e7a37_0.json
bleach-2.1.2-py36_0.json
bokeh-0.12.13-py36h2f9c1c0_0.json
boto-2.48.0-py36hdbc59ac_1.json
bottleneck-1.2.1-py36hbd380ad_0.json
bzip2-1.0.6-hd86a083_4.json
ca-certificates-2017.08.26-ha1e5d58_0.json
certifi-2018.1.18-py36_0.json
cffi-1.11.4-py36h342bebf_0.json
chardet-3.0.4-py36h96c241c_1.json
click-6.7-py36hec950be_0.json
cloudpickle-0.5.2-py36_1.json
clyent-1.2.2-py36hae3ad88_0.json
colorama-0.3.9-py36hd29a30c_0.json
conda-4.4.10-py36_0.json
conda-build-3.4.1-py36_0.json
conda-env-2.6.0-h36134e3_0.json
conda-verify-2.0.0-py36he837df3_0.json
contextlib2-0.5.5-py36hd66e5e7_0.json
cryptography-2.1.4-py36h842514c_0.json
curl-7.58.0-ha441bb4_0.json
cycler-0.10.0-py36hfc81398_0.json
cython-0.27.3-py36h6ecb376_0.json
cytoolz-0.9.0-py36h1de35cc_0.json
dask-0.16.1-py36_0.json
dask-core-0.16.1-py36_0.json
datashape-0.5.4-py36hfb22df8_0.json
dbus-1.12.2-h5243cc1_1.json
decorator-4.2.1-py36_0.json
distributed-1.20.2-py36_0.json
docutils-0.14-py36hbfde631_0.json
entrypoints-0.2.3-py36hd81d71f_2.json
et_xmlfile-1.0.1-py36h1315bdc_0.json
expat-2.2.5-hb8e80ba_0.json
fastcache-1.0.2-py36h1de35cc_2.json
filelock-2.0.13-py36hf9de95b_0.json
flask-0.12.2-py36h5658096_0.json
flask-cors-3.0.3-py36h7387b97_0.json
freetype-2.8-h12048fb_1.json
get_terminal_size-1.0.0-h7520d66_0.json
gettext-0.19.8.1-h15daf44_3.json
gevent-1.2.2-py36ha70b9d6_0.json
glib-2.53.6-h33f6a65_2.json
glob2-0.6-py36h94c9186_0.json
gmp-6.1.2-hb37e062_1.json
gmpy2-2.0.8-py36hf9c35bd_2.json
greenlet-0.4.12-py36hf09ba7b_0.json
h5py-2.7.1-py36h39cdac5_0.json
hdf5-1.10.1-ha036c08_1.json
heapdict-1.0.0-py36_2.json
history
html5lib-1.0.1-py36h2f9c1c0_0.json
icu-58.2-h4b95b61_1.json
idna-2.6-py36h8628d0a_1.json
imageio-2.2.0-py36h5e01289_0.json
imagesize-0.7.1-py36h3495948_0.json
intel-openmp-2018.0.0-h8158457_8.json
ipykernel-4.8.0-py36_0.json
ipython-6.2.1-py36h3dda519_1.json
ipython_genutils-0.2.0-py36h241746c_0.json
ipywidgets-7.1.1-py36_0.json
isort-4.2.15-py36hceb2a01_0.json
itsdangerous-0.24-py36h49fbb8d_1.json
jbig-2.1-h4d881f8_0.json
jdcal-1.3-py36h1986823_0.json
jedi-0.11.1-py36_0.json
jinja2-2.10-py36hd36f9c5_0.json
jpeg-9b-he5867d9_2.json
jsonschema-2.6.0-py36hb385e00_0.json
jupyter-1.0.0-py36_4.json
jupyter_client-5.2.2-py36_0.json
jupyter_console-5.2.0-py36hccf5b1c_1.json
jupyter_core-4.4.0-py36h79cf704_0.json
jupyterlab-0.31.5-py36_0.json
jupyterlab_launcher-0.10.2-py36_0.json
lazy-object-proxy-1.3.1-py36h2fbbe47_0.json
libcurl-7.58.0-hf30b1f0_0.json
libcxx-4.0.1-h579ed51_0.json
libcxxabi-4.0.1-hebd6815_0.json
libedit-3.1-hb4e282d_0.json
libffi-3.2.1-h475c297_4.json
libgfortran-3.0.1-h93005f0_2.json
libiconv-1.15-hdd342a3_7.json
libpng-1.6.34-he12f830_0.json
libsodium-1.0.15-hd9e47c5_0.json
libssh2-1.8.0-h322a93b_4.json
libtiff-4.0.9-h0dac147_0.json
libxml2-2.9.7-hab757c2_0.json
libxslt-1.1.32-hb819dd2_0.json
llvmlite-0.21.0-py36hff739e7_0.json
locket-0.2.0-py36hca03003_1.json
lxml-4.1.1-py36hef8c89e_1.json
lzo-2.10-h362108e_2.json
markupsafe-1.0-py36h3a1e703_1.json
matplotlib-2.1.2-py36h6d6146d_0.json
mccabe-0.6.1-py36hdaeb55d_0.json
mistune-0.8.3-py36_0.json
mkl-2018.0.1-hfbd8650_4.json
mkl-service-1.1.2-py36h7ea6df4_4.json
mpc-1.0.3-h7a72875_5.json
mpfr-3.1.5-h711e7fd_2.json
mpmath-1.0.0-py36hf1b8295_2.json
msgpack-python-0.5.1-py36h04f5b5a_0.json
multipledispatch-0.4.9-py36hc5f92b5_0.json
navigator-updater-0.1.0-py36h7aee5fb_0.json
nbconvert-5.3.1-py36h810822e_0.json
nbformat-4.4.0-py36h827af21_0.json
ncurses-6.0-hd04f020_2.json
networkx-2.1-py36_0.json
nltk-3.2.5-py36h1190bce_0.json
nose-1.3.7-py36h73fae2b_2.json
notebook-5.4.0-py36_0.json
numba-0.36.2-np114py36hc2f221f_0.json
numexpr-2.6.4-py36habcfcfe_0.json
numpy-1.14.0-py36h8a80b8c_1.json
numpydoc-0.7.0-py36he54d08e_0.json
odo-0.5.1-py36hc1af34a_0.json
olefile-0.45.1-py36_0.json
openpyxl-2.4.10-py36_0.json
openssl-1.0.2n-hdbc3d79_0.json
packaging-16.8-py36he5e8135_0.json
pandas-0.22.0-py36h0a44026_0.json
pandoc-1.19.2.1-ha5e8f32_1.json
pandocfilters-1.4.2-py36h3b0b094_1.json
parso-0.1.1-py36hc90e01c_0.json
partd-0.3.8-py36hf5c4cb8_0.json
path.py-10.5-py36h7bcb313_0.json
pathlib2-2.3.0-py36h877a6d8_0.json
patsy-0.5.0-py36_0.json
pcre-8.41-hfb6ab37_1.json
pep8-1.7.1-py36_0.json
pexpect-4.3.1-py36_0.json
pickleshare-0.7.4-py36hf512f8e_0.json
pillow-5.0.0-py36hfcce615_0.json
pip-9.0.1-py36h1555ced_4.json
pkginfo-1.4.1-py36h25bf955_0.json
pluggy-0.6.0-py36hb1d0581_0.json
ply-3.10-py36h10e714e_0.json
prompt_toolkit-1.0.15-py36haeda067_0.json
psutil-5.4.3-py36h1de35cc_0.json
ptyprocess-0.5.2-py36he6521c3_0.json
py-1.5.2-py36ha69170d_0.json
pycodestyle-2.3.1-py36h83e8646_0.json
pycosat-0.6.3-py36hee92d8f_0.json
pycparser-2.18-py36h724b2fc_1.json
pycrypto-2.6.1-py36h1de35cc_7.json
pycurl-7.43.0.1-py36hdbc3d79_0.json
pyflakes-1.6.0-py36hea45e83_0.json
pygments-2.2.0-py36h240cd3f_0.json
pylint-1.8.2-py36_0.json
pyodbc-4.0.22-py36h0a44026_0.json
pyopenssl-17.5.0-py36h51e4350_0.json
pyparsing-2.2.0-py36hb281f35_0.json
pyqt-5.6.0-py36he5c6137_6.json
pysocks-1.6.7-py36hfa33cec_1.json
pytables-3.4.2-py36hfbd7ab0_2.json
pytest-3.3.2-py36_0.json
python-3.6.4-hc167b69_1.json
python-dateutil-2.6.1-py36h86d2abb_1.json
python.app-2-py36h54569d5_7.json
pytz-2017.3-py36hf0bf824_0.json
pywavelets-0.5.2-py36h2710a04_0.json
pyyaml-3.12-py36h2ba1e63_1.json
pyzmq-16.0.3-py36he48b5ad_0.json
qt-5.6.2-h9975529_14.json
qtawesome-0.4.4-py36h468c6fb_0.json
qtconsole-4.3.1-py36hd96c0ff_0.json
qtpy-1.3.1-py36h16bb863_0.json
readline-7.0-hc1231fa_4.json
requests-2.18.4-py36h4516966_1.json
rope-0.10.7-py36h68959ac_0.json
ruamel_yaml-0.15.35-py36h1de35cc_1.json
scikit-image-0.13.1-py36h1de35cc_1.json
scikit-learn-0.19.1-py36hffbff8c_0.json
scipy-1.0.0-py36h1de22e9_0.json
seaborn-0.8.1-py36h595ecd9_0.json
send2trash-1.4.2-py36_0.json
setuptools-38.4.0-py36_0.json
simplegeneric-0.8.1-py36_2.json
singledispatch-3.4.0.3-py36hf20db9d_0.json
sip-4.18.1-py36h2824476_2.json
six-1.11.0-py36h0e22d5e_1.json
snowballstemmer-1.2.1-py36h6c7b616_0.json
sortedcollections-0.5.3-py36he9c3ed6_0.json
sortedcontainers-1.5.9-py36_0.json
sphinx-1.6.6-py36_0.json
sphinxcontrib-1.0-py36h9364dc8_1.json
sphinxcontrib-websupport-1.0.1-py36h92f4a7a_1.json
spyder-3.2.6-py36_0.json
sqlalchemy-1.2.1-py36h1de35cc_0.json
sqlite-3.22.0-h3efe00b_0.json
statsmodels-0.8.0-py36h9c68fc9_0.json
sympy-1.1.1-py36h7f3cf04_0.json
tblib-1.3.2-py36hda67792_0.json
terminado-0.8.1-py36_1.json
testpath-0.3.1-py36h625a49b_0.json
tk-8.6.7-h35a86e2_3.json
toolz-0.9.0-py36_0.json
tornado-4.5.3-py36_0.json
traitlets-4.3.2-py36h65bd3ce_0.json
typing-3.6.2-py36haa2d9ef_0.json
unicodecsv-0.14.1-py36he531d66_0.json
unixodbc-2.3.4-h4cb4dde_1.json
urllib3-1.22-py36h68b9469_0.json
wcwidth-0.1.7-py36h8c6ec74_0.json
webencodings-0.5.1-py36h3b9701d_1.json
werkzeug-0.14.1-py36_0.json
wheel-0.30.0-py36h5eb2c71_1.json
widgetsnbextension-3.1.0-py36_0.json
wrapt-1.10.11-py36hc29e774_0.json
xlrd-1.1.0-py36h336f4a2_1.json
xlsxwriter-1.0.2-py36h3736301_0.json
xlwings-0.11.5-py36_0.json
xlwt-1.2.0-py36h5ad1178_0.json
xz-5.2.3-h0278029_2.json
yaml-0.1.7-hc338f04_2.json
zeromq-4.2.2-ha360ad0_2.json
zict-0.1.3-py36h71da714_0.json
zlib-1.2.11-hf3cbc9b_2.json
 
acbc32c9e491:conda-meta USER$ anaconda-navigator
An unexpected error occurred on Navigator start-up<br>byte indices must be integers or slices, not str
Traceback (most recent call last):
  File "/Users/lyg622/anaconda3/lib/python3.6/site-packages/anaconda_navigator/exceptions.py", line 75, in exception_handler
    return_value = func(*args, **kwargs)
  File "/Users/lyg622/anaconda3/lib/python3.6/site-packages/anaconda_navigator/app/start.py", line 120, in start_app
    window = run_app(splash)
  File "/Users/lyg622/anaconda3/lib/python3.6/site-packages/anaconda_navigator/app/start.py", line 63, in run_app
    window = MainWindow(splash=splash)
  File "/Users/lyg622/anaconda3/lib/python3.6/site-packages/anaconda_navigator/widgets/main_window.py", line 163, in __init__
    self.api = AnacondaAPI()
  File "/Users/lyg622/anaconda3/lib/python3.6/site-packages/anaconda_navigator/api/anaconda_api.py", line 2004, in AnacondaAPI
    ANACONDA_API = _AnacondaAPI()
  File "/Users/lyg622/anaconda3/lib/python3.6/site-packages/anaconda_navigator/api/anaconda_api.py", line 88, in __init__
    self._conda_api = CondaAPI()
  File "/Users/lyg622/anaconda3/lib/python3.6/site-packages/anaconda_navigator/api/conda_api.py", line 1690, in CondaAPI
    CONDA_API = _CondaAPI()
  File "/Users/lyg622/anaconda3/lib/python3.6/site-packages/anaconda_navigator/api/conda_api.py", line 347, in __init__
    self.set_conda_prefix()
  File "/Users/lyg622/anaconda3/lib/python3.6/site-packages/anaconda_navigator/api/conda_api.py", line 496, in set_conda_prefix
    self.ROOT_PREFIX = info['root_prefix']
TypeError: byte indices must be integers or slices, not str
```

##### `conda list --show-channel-urls`

```
Not sure where to get this
```

**Comment by goanpeca** [comment]
Please open a terminal and provide the output of

```
conda info
```

and 

```
conda list --show-channel-urls
```

And update this issue

**Comment by SpainTopher** [comment]
i've gone to 
cd anaconda3
cd conda-meta
conda info (doesn't do anything, but take me back to $)
confa list (doesn't do anything, but take me back to $)

**Comment by SpainTopher** [comment]
i've installed anaconda3 3x, but still persists with same issue

**Comment by SpainTopher** [comment]
i did try this too, but takes back to $
conda list --show-channel-urls

**Comment by puyihua** [comment]
I have encountered the same question too. Is there any possibility to solve this problem by reinstalling anaconda?

**Comment by goanpeca** [comment]
I cannot provide additional help until the requested information is provided:

Please open a terminal and provide the output of

```
source activate base
conda info
```

and

```
source activate base
conda list --show-channel-urls
```

and

```
source activate base
anaconda-navigator
```
