### ISSUE TITLE
Unable to launch spider via Anaconda navigator on mac

### ISSUE THREAD

**Issue by Tanmoyray** [ContinuumIO/anaconda-issues#9046]
Error has shown : Unable to launch seder

Traceback (most recent call last):
File "/anaconda3/bin/spyder", line 7, in 
from spyder.app.start import main
File "/anaconda3/lib/python3.6/site-packages/spyder/app/start.py", line 27, in 
from spyder.config.main import CONF
File "/anaconda3/lib/python3.6/site-packages/spyder/config/main.py", line 22, in 
from spyder.config.user import UserConfig
File "/anaconda3/lib/python3.6/site-packages/spyder/config/user.py", line 26, in 
from spyder.utils.programs import check_version
File "/anaconda3/lib/python3.6/site-packages/spyder/utils/programs.py", line 18, in 
import subprocess
File "/anaconda3/lib/python3.6/subprocess.py", line 136, in 
import _posixsubprocess
ImportError: dlopen(/anaconda3/lib/python3.6/lib-dynload/_posixsubprocess.cpython-36m-darwin.so, 2): Symbol not found: __Py_set_inheritable_async_safe
Referenced from: /anaconda3/lib/python3.6/lib-dynload/_posixsubprocess.cpython-36m-darwin.so
Expected in: flat namespace
in /anaconda3/lib/python3.6/lib-dynload/_posixsubprocess.cpython-36m-darwin.so

**Comment by mingwandroid** [comment]
@Tanmoyray, this is fixed now. Please run `conda update python.app`.

**Comment by Tanmoyray** [comment]
@mingwandroid Thank you Sir. This issue is solved now.
