### ISSUE TITLE
Anaconda3 SSLError when updating or installing anything

### ISSUE THREAD

**Issue by chuckmalek123** [ContinuumIO/anaconda-issues#9059]
Here's the issue: Get this Anaconda3 error when installing or updating anything.

PS C:\> conda update conda
Solving environment: failed

CondaHTTPError: HTTP 000 CONNECTION FAILED for url <https://repo.continuum.io/pkgs/r/win-64/repodata.json.bz2>
Elapsed: -

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.
SSLError(MaxRetryError('HTTPSConnectionPool(host=\'repo.continuum.io\', port=443): Max retries exceeded with url: /pkgs/r/win-64/repodata.json.bz2 (Caused by SSLError(SSLError("bad handshake: Error([(\'SSL routines\', \'ssl3_get_server_certificate\', \'certificate verify failed\')],)",),))',),)

PS C:\>
----------------------------------------------------------------------------------------------------------------
Here's a few of the work-arounds from google anaconda community help that I have tried:

- multiple PCs.
- multiple locations.
- windows firewall /virus scanners off or on.
- conda config --set ssl_verify False
- check that c:\Users\chuck\.condarc actually has ssl_verify : False
- conda config --set ssl_verify c:\ProgramData\Anaconda3\pkgs\tornado-4.5.3-py36_0\Lib\site-packages\tornado\test\test.crt
- where openssl //no response
- openssl -sclient -connect repo.continuum.io:443 -> same SSL Error
- conda update openssl cryptography    -> SAME SSLError
- conda remove certifi ->SAME SSLError
- conda install certifi -> SAME SSLError

These and more always produce the same identical SSL Error.
----------------------------------------------------------------------------
PS C:\> conda info

     active environment : None
       user config file : C:\Users\chuck\.condarc
 populated config files : C:\Users\chuck\.condarc
          conda version : 4.4.10
    conda-build version : 3.4.1
         python version : 3.6.4.final.0
       base environment : C:\ProgramData\Anaconda3  (read only)
           channel URLs : https://conda.anaconda.org/conda-forge/win-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.continuum.io/pkgs/main/win-64
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/win-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
          package cache : C:\ProgramData\Anaconda3\pkgs
                          C:\Users\chuck\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\chuck\AppData\Local\conda\conda\envs
                          C:\ProgramData\Anaconda3\envs
                          C:\Users\chuck\.conda\envs
               platform : win-64
             user-agent : conda/4.4.10 requests/2.18.4 CPython/3.6.4 Windows/10 Windows/10.0.16299
          administrator : False
             netrc file : None
           offline mode : False

PS C:\>
------------------------------------------------------------------------------------------------------------
PS C:\> conda env list
# conda environments:
#
base                  *  C:\ProgramData\Anaconda3
-------------------------------------------------------------------------------------
And all I set out to do was to simply type conda install -c anaconda pywin32 !
--------------------------------------------------------------------------------------------

**Comment by WillieMaddox** [comment]
Same exact problem here.  Any word on a solution?

**Comment by fmnoori** [comment]
getting same problem..

**Comment by mrjakers** [comment]
Same issue.  Is there still no solution?

**Comment by arecalt** [comment]
Ditto, same problem. I've tried a number of the OP's attempted workarounds myself, to no avail. 

For me, the trouble started *after* I'd done an update on a ton of packages on my machine (a laptop I haven't used in a good year or so and so required a lot of updates to python-related stuff). No errors during package updates, but now I get this same error. 

I'm about to wipe the ssd and start fresh because this is such a headache.

**Comment by stumpylog** [comment]
I believe I'm seeing this with miniconda3 as well, 4.5.12.  I actually tried a fresh installation, but still see the same problem.  Attempting `import ssl` also fails in a Python prompt.  Is the SSL module missing from Anaconda somehow?

**Comment by msarahan** [comment]
Are you using anaconda prompt or otherwise activating your environment?

**Comment by stumpylog** [comment]
This is a Miniconda install, so I don't believe that includes an Anaconda prompt.  There's also no environment, I'm using the python.exe as installed fresh and on my PATH.  It's like the ssl module isn't being properly included?

```
λ python
Python 3.7.1 (default, Dec 10 2018, 22:09:34) [MSC v.1915 32 bit (Intel)] :: Anaconda, Inc. on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import ssl
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Miniconda3\lib\ssl.py", line 98, in <module>
    import _ssl             # if we can't import it, let the error propagate
ImportError: DLL load failed: The specified module could not be found.
>>>
```

**Comment by stumpylog** [comment]
Ah, so here's something interesting.  If I chose to add Anaconda to the PATH during installation, instead of adding it to just my user PATH manually after installation, `import ssl` will work.  I think it may be the addition of `Library\bin` to the PATH

**Comment by mingwandroid** [comment]
I general having the necessary folders on PATH is essential for software to work correctly, yes.

**Comment by mingwandroid** [comment]
Miniconda does come with the `Anaconda Prompt`.

**Comment by kc2u11** [comment]
That SSL error is misleading. I am using Anaconda 3, conda version 4.6.11, have the most current version of openssl on a Windows 10 instance. I got the issue resolved by changing the security settings on the Anaconda3 folder to Full Control. 
Don't think this helped, but I also have modified the ..\Anaconda3\Lib\site-packages\certifi\cacert.pem file to include the company's SSL cert. Instructions are here. 
https://stackoverflow.com/questions/33699577/conda-update-failed-ssl-error-ssl-certificate-verify-failed-certificate-ver
http://blog.majcica.com/2016/12/27/installing-self-signed-certificates-into-git-cert-store/

Hope this info helps you.
