### ISSUE TITLE
Spyder not working on Windows 10

### ISSUE THREAD

**Issue by shadab-shah** [ContinuumIO/anaconda-issues#9066]
I have install anaconda and trying to open spyder, but i am getting the below error.

Traceback (most recent call last):
File "C:\Users\admin\Anaconda3\Scripts\spyder-script.py", line 6, in 
from spyder.app.start import main
File "C:\Users\admin\Anaconda3\lib\site-packages\spyder\app\start.py", line 25, in 
from spyder.config.base import get_conf_path, running_in_mac_app
File "C:\Users\admin\Anaconda3\lib\site-packages\spyder\config\base.py", line 362, in 
_ = get_translation("spyder")
File "C:\Users\admin\Anaconda3\lib\site-packages\spyder\config\base.py", line 336, in get_translation
os.environ["LANG"] = language # Works on Windows
File "C:\Users\admin\Anaconda3\lib\os.py", line 675, in __setitem__
self.putenv(key, value)
ValueError: embedded null character

I had install-re-install anaconda couple of times.
tried --reset command too, but nothing is working as of now.

Thanks for the help.

**Comment by ccordoba12** [comment]
@shadab-shah, please open your bug in our tracker

https://github.com/spyder-ide/spyder/issues

and close it here. We'll add a validation to use English as the language of our interface if this error happens.
