### ISSUE TITLE
Windows7 64bit OSError: Failed to create shortcut

### ISSUE THREAD

**Issue by raderaj** [ContinuumIO/anaconda-issues#91]
I had Anaconda 1.8.0 x86_64 installed on my Windows7 machine and attempted to upgrade anaconda to 1.9.0 by typing the following commands:
C:\Anaconda>conda update conda
C:\Anaconda>conda update anaconda

When executing the second command, I got this error:

``` pytb
Linking packages ...
menuinst Exception:  ] |                                                 |   1%
Traceback (most recent call last):
  File "C:\Anaconda\lib\site-packages\conda\install.py", line 221, in mk_menus
    menuinst.install(join(prefix, f), remove, prefix)
  File "C:\Anaconda\lib\site-packages\menuinst\__init__.py", line 42, in install

    ShortCut(m, sc, prefix=prefix).create()
  File "C:\Anaconda\lib\site-packages\menuinst\win32.py", line 128, in create
    u'' + icon,
OSError: Failed to create shortcut 'C:\ProgramData\Microsoft\Windows\Start Menu\
Programs\Anaconda (64-bit)\Wakari (in the cloud).lnk' - error 0x80070005
menuinst Exception:  ] |##################                               |  36%
Traceback (most recent call last):
  File "C:\Anaconda\lib\site-packages\conda\install.py", line 221, in mk_menus
    menuinst.install(join(prefix, f), remove, prefix)
  File "C:\Anaconda\lib\site-packages\menuinst\__init__.py", line 42, in install

    ShortCut(m, sc, prefix=prefix).create()
  File "C:\Anaconda\lib\site-packages\menuinst\win32.py", line 128, in create
    u'' + icon,
OSError: Failed to create shortcut 'C:\ProgramData\Microsoft\Windows\Start Menu\
Programs\Anaconda (64-bit)\IPython (Py 2.7).lnk' - error 0x80070005
```

Essentially, the start menu links to IPython  and Wakari are missing.

MANUAL SOLUTION:
One can manually re-generate these by creating a shortcut in the windows startmenu folder: 
C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Anaconda (64-bit).
For straight Ipython The shortcut Target should be something like:
C:\Anaconda\python.exe "C:\Anaconda\Scripts/ipython-script.py"
And you can change the Start in location to something like:
"C:\Users\username\Documents\Python Scripts"

Similarly for the IPython Notebook shortcut  use:
C:\Anaconda\python.exe "C:\Anaconda\Scripts/ipython-script.py" notebook
and 
"C:\Users\username\Documents\IPython Notebooks"

for target and start in locations.

**Comment by flutefreak7** [comment]
I think that if Anaconda is installed for all users, then the shortcuts require admin rights to write to the C:\ProgramData folder.

Assuming this is the issue, I think the best solution is to run the command prompt as an administrator.

A more clean way to fail would be for conda or menuinst to check write permissions before attempting to create the shortcut and inform the user that the shortcut can't be made without write permissions. Even better would be to offer to elevate permissions and try again if write permissions aren't there or shortcut creation failed.

The user is also left to hope that shortcut creation was the last thing the installer needed to do since the error isn't caught cleanly.  At the very least the installer should catch the error and report something like "Error creating shortcut... finishing install..."

**Comment by H0R5E** [comment]
The behaviour of conda with the Windows start menu continues to be very unsatisfactory. For me, two things need to happen:

1. There needs to be a separate package (even executable) for just updating the menus that can be run with admin rights.
2. The current packages that want to create menu shortcuts shouldn't have this responsibility as they often fail for standard users and they also try to install when using environments, which is undesirable behaviour.

**Comment by flutefreak7** [comment]
Yeah I think if conda is going to manage start menu stuff which might require admin rights, it should request elevated privileges. Conda is already interactive with asking yes/no to proceed, it could easily also ask if you want your start menus updated and if so, request elevation (via UAC prompt).  If elevated privileges aren't granted, it should fail cleanly with a warning.

These are my opinions as a layman conda user.  If a Windows software installation wants admin rights I'm used to it asking for it or failing cleanly asking to be re-run with elevated privileges.

**Comment by ccordoba12** [comment]
Pinging @msarahan about this one.

**Comment by msarahan** [comment]
Thanks for these suggestions.  We are working on implementing them, and this issue should be solved in time for the 2.4.1 bugfix release in early December.

**Comment by H0R5E** [comment]
Great! I look forward to trying it out.

**Comment by stmax82** [comment]
I ran into a similar problem: installing ipython-notebook into an environment produces the same error, unless the console is opened as admin.

Output:

C:\...>conda install -p pyenv ipython-notebook
Fetching package metadata: ....
Solving package specifications: ................
Package plan for installation in environment C:\...\pyenv:

The following NEW packages will be INSTALLED:

    decorator:        4.0.4-py34_0
    ipykernel:        4.1.1-py34_0
    ipython:          4.0.0-py34_1
    ipython-notebook: 4.0.4-py34_3
    ipython_genutils: 0.1.0-py34_0
    jinja2:           2.8-py34_0
    jsonschema:       2.4.0-py34_0
    jupyter_client:   4.1.1-py34_0
    jupyter_core:     4.0.6-py34_0
    libsodium:        1.0.3-0
    markupsafe:       0.23-py34_0
    mistune:          0.7.1-py34_0
    nbconvert:        4.0.0-py34_0
    nbformat:         4.0.1-py34_0
    notebook:         4.0.6-py34_0
    path.py:          8.1.2-py34_0
    pickleshare:      0.5-py34_0
    pygments:         2.0.2-py34_0
    pyreadline:       2.1-py34_0
    pyzmq:            14.7.0-py34_1
    simplegeneric:    0.8.1-py34_0
    tornado:          4.2.1-py34_1
    traitlets:        4.0.0-py34_0
    zeromq:           4.1.3-vc10_1  [vc10]

Proceed ([y]/n)? y

Linking packages ...
menuinst Exception:Traceback (most recent call last):###                 |  66%
  File "C:\Anaconda3\lib\site-packages\conda\install.py", line 338, in mk_menus
    menuinst.install(join(prefix, f), remove, prefix)
  File "C:\Anaconda3\lib\site-packages\menuinst\__init__.py", line 42, in install
    ShortCut(m, sc, prefix=prefix).create()
  File "C:\Anaconda3\lib\site-packages\menuinst\win32.py", line 133, in create
    u'' + icon,
OSError: Failed to create shortcut 'C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Anaconda${PY_VER} ${PLATFORM}\IPython.lnk' - error 0x80070005
menuinst Exception:Traceback (most recent call last):#################   |  95%
  File "C:\Anaconda3\lib\site-packages\conda\install.py", line 338, in mk_menus
    menuinst.install(join(prefix, f), remove, prefix)
  File "C:\Anaconda3\lib\site-packages\menuinst\__init__.py", line 42, in install
    ShortCut(m, sc, prefix=prefix).create()
  File "C:\Anaconda3\lib\site-packages\menuinst\win32.py", line 133, in create
    u'' + icon,
OSError: Failed to create shortcut 'C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Anaconda${PY_VER} ${PLATFORM}\Jupyter Notebook.lnk' - error 0x80070005
[      COMPLETE      ]|##################################################| 100%

C:\...>

**Comment by goanpeca** [comment]
Closing for lack of activity.

Please reopen if this is still a problem with an update of the status.

Thanks!
