### ISSUE TITLE
Anaconda Navigator can't launch on macOS

### ISSUE THREAD

**Issue by guozhenli** [ContinuumIO/anaconda-issues#9103]
### Actual Behavior
When launching Anaconda Navigator from its icon in Launchpad, nothing happens.

When launching Anaconda Navigator from Spotlight Search, I get this window:
![image](https://user-images.githubusercontent.com/7464471/38404168-f2aaaea6-391c-11e8-8043-9c54b11c5b1d.png)

When running `anaconda-navigator` from terminal, I get `KeyError: 'pip._vendor.urllib3.contrib'`
```
$ which anaconda-navigator
/Users/my_username/anaconda/bin/anaconda-navigator

$ anaconda-navigator
Traceback (most recent call last):
  File "/Users/my_username/anaconda/bin/anaconda-navigator", line 11, in <module>
    sys.exit(main())
  File "/Users/my_username/anaconda/lib/python3.6/site-packages/anaconda_navigator/app/main.py", line 129, in main
    from anaconda_navigator.app.start import start_app
  File "/Users/my_username/anaconda/lib/python3.6/site-packages/anaconda_navigator/app/start.py", line 32, in <module>
    from anaconda_navigator.widgets.main_window import MainWindow
  File "/Users/my_username/anaconda/lib/python3.6/site-packages/anaconda_navigator/widgets/main_window.py", line 32, in <module>
    from anaconda_navigator.api.anaconda_api import AnacondaAPI
  File "/Users/my_username/anaconda/lib/python3.6/site-packages/anaconda_navigator/api/anaconda_api.py", line 33, in <module>
    from anaconda_navigator.api.client_api import ClientAPI
  File "/Users/my_username/anaconda/lib/python3.6/site-packages/anaconda_navigator/api/client_api.py", line 24, in <module>
    from anaconda_navigator.api.conda_api import CondaAPI
  File "/Users/my_username/anaconda/lib/python3.6/site-packages/anaconda_navigator/api/conda_api.py", line 33, in <module>
    from anaconda_navigator.utils.findpip import PIP_LIST_SCRIPT
  File "/Users/my_username/anaconda/lib/python3.6/site-packages/anaconda_navigator/utils/findpip.py", line 22, in <module>
    import pip
  File "/Users/my_username/anaconda/lib/python3.6/site-packages/pip/__init__.py", line 45, in <module>
    from pip.vcs import git, mercurial, subversion, bazaar  # noqa
  File "/Users/my_username/anaconda/lib/python3.6/site-packages/pip/vcs/mercurial.py", line 9, in <module>
    from pip.download import path_to_url
  File "/Users/my_username/anaconda/lib/python3.6/site-packages/pip/download.py", line 40, in <module>
    from pip._vendor import requests, six
  File "/Users/my_username/anaconda/lib/python3.6/site-packages/pip/_vendor/requests/__init__.py", line 98, in <module>
    from . import packages
  File "/Users/my_username/anaconda/lib/python3.6/site-packages/pip/_vendor/requests/packages.py", line 12, in <module>
    sys.modules['pip._vendor.requests.packages.' + mod] = sys.modules["pip._vendor." + mod]
KeyError: 'pip._vendor.urllib3.contrib'
```

All these were done after trying the solution provided in #1984 

### Anaconda or Miniconda version:
```
$ conda list anaconda*
# packages in environment at /Users/my_username/anaconda:
#
# Name                    Version                   Build  Channel
anaconda                  custom           py36ha4fed55_0  
anaconda-client           1.6.6            py36hd86ed11_0  
anaconda-navigator        1.7.0                    py36_0  
anaconda-project          0.8.2            py36h9ee5d53_0  
```
### Operating System:
macOS High Sierra 10.13.3 (17D102)

### `conda info`

```
$ conda info

     active environment : None
       user config file : /Users/my_username/.condarc
 populated config files : /Users/my_username/.condarc
          conda version : 4.5.0
    conda-build version : not installed
         python version : 3.6.3.final.0
       base environment : /Users/my_username/anaconda  (writable)
           channel URLs : http://conda.anaconda.org/gurobi/osx-64
                          http://conda.anaconda.org/gurobi/noarch
                          https://repo.anaconda.com/pkgs/main/osx-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/osx-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/osx-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/osx-64
                          https://repo.anaconda.com/pkgs/pro/noarch
          package cache : /Users/my_username/anaconda/pkgs
                          /Users/my_username/.conda/pkgs
       envs directories : /Users/my_username/anaconda/envs
                          /Users/my_username/.conda/envs
               platform : osx-64
             user-agent : conda/4.5.0 requests/2.18.4 CPython/3.6.3 Darwin/17.4.0 OSX/10.13.3
                UID:GID : 501:20
             netrc file : None
           offline mode : False
```

**Comment by mingwandroid** [comment]
Please fill in all of the information requested in the template. You didn't provide the output from `conda list --show-channel-urls`.

**Comment by mingwandroid** [comment]
But of you are using old software here too, and you can probably fix all this with a `conda update --all`.

**Comment by goanpeca** [comment]
Correct @mingwandroid updating pip specifically fixes this issue

Open a terminal and type::
```
conda update pip
```

But updating all packages is a great idea!

Open a terminal and type
```
conda update --all
```

**Comment by guozhenli** [comment]
Thanks everyone. `conda update pip` solved it.

**Comment by ludwigwittgenstein2** [comment]
conda update fixes it

**Comment by MAvalleza** [comment]
`conda update pip` worked for me as well
