### ISSUE TITLE
Anaconda-Navigator breaks after GraphLab install

### ISSUE THREAD

**Issue by wanqingshao** [ContinuumIO/anaconda-issues#9107]
### Navigator Error
An unexpected error occurred on Navigator start-up

### Main Error
'conda_prefix'

### Traceback
Traceback (most recent call last):
  File "/Users/was/anaconda3/lib/python3.5/site-packages/anaconda_navigator/exceptions.py", line 75, in exception_handler
    return_value = func(*args, **kwargs)
  File "/Users/was/anaconda3/lib/python3.5/site-packages/anaconda_navigator/app/start.py", line 138, in start_app
    window = run_app(splash)
  File "/Users/was/anaconda3/lib/python3.5/site-packages/anaconda_navigator/app/start.py", line 64, in run_app
    window = MainWindow(splash=splash, tab_project=False)
  File "/Users/was/anaconda3/lib/python3.5/site-packages/anaconda_navigator/widgets/main_window.py", line 163, in __init__
    self.api = AnacondaAPI()
  File "/Users/was/anaconda3/lib/python3.5/site-packages/anaconda_navigator/api/anaconda_api.py", line 2086, in AnacondaAPI
    ANACONDA_API = _AnacondaAPI()
  File "/Users/was/anaconda3/lib/python3.5/site-packages/anaconda_navigator/api/anaconda_api.py", line 89, in __init__
    self._conda_api = CondaAPI()
  File "/Users/was/anaconda3/lib/python3.5/site-packages/anaconda_navigator/api/conda_api.py", line 1699, in CondaAPI
    CONDA_API = _CondaAPI()
  File "/Users/was/anaconda3/lib/python3.5/site-packages/anaconda_navigator/api/conda_api.py", line 347, in __init__
    self.set_conda_prefix()
  File "/Users/was/anaconda3/lib/python3.5/site-packages/anaconda_navigator/api/conda_api.py", line 507, in set_conda_prefix
    self.CONDA_PREFIX = info['conda_prefix']
KeyError: 'conda_prefix'

### Current conda install:

             platform : osx-64
        conda version : 4.0.8
  conda-build version : 1.20.3
       python version : 3.5.5.final.0
     requests version : 2.11.1
     root environment : /Users/was/anaconda3  (writable)
  default environment : /Users/was/anaconda3
     envs directories : /Users/was/anaconda3/envs
        package cache : /Users/was/anaconda3/pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/osx-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/osx-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : None
    is foreign system : False

### Conda install generates error

Fetching package metadata: ....
.Solving package specifications: .
Error:  Dependency missing in current osx-64 channels: 
  - libedit (target=libedit-3.1-hb4e282d_0.tar.bz2) -> ncurses 6.0.*

Did you mean one of these?

    ncurses

You can search for this package on anaconda.org with

    anaconda search -t conda ncurses 6.0.*

**Comment by wanqingshao** [comment]
How should I fix this?

**Comment by goanpeca** [comment]
Requested information was not provided, closing
