### ISSUE TITLE
anaconda-navigator did not launch after installing opencv (Failed to launch GPU process)

### ISSUE THREAD

**Issue by esra-aydemir** [ContinuumIO/anaconda-issues#9159]
#### A have just installed opencv in conda using
[instructions here](https://anaconda.org/conda-forge/opencv)
#### It gave this error: 
[13848:13886:0413/023107.613354:ERROR:browser_gpu_channel_host_factory.cc(120)] Failed to launch GPU process.
#### The traceback on the error page opened is as follows:
Traceback (most recent call last):
  File "/home/aras/anaconda3/lib/python3.6/site-packages/anaconda_navigator/exceptions.py", line 75, in exception_handler
    return_value = func(*args, **kwargs)
  File "/home/aras/anaconda3/lib/python3.6/site-packages/anaconda_navigator/app/start.py", line 138, in start_app
    window = run_app(splash)
  File "/home/aras/anaconda3/lib/python3.6/site-packages/anaconda_navigator/app/start.py", line 64, in run_app
    window = MainWindow(splash=splash, tab_project=False)
  File "/home/aras/anaconda3/lib/python3.6/site-packages/anaconda_navigator/widgets/main_window.py", line 163, in __init__
    self.api = AnacondaAPI()
  File "/home/aras/anaconda3/lib/python3.6/site-packages/anaconda_navigator/api/anaconda_api.py", line 2086, in AnacondaAPI
    ANACONDA_API = _AnacondaAPI()
  File "/home/aras/anaconda3/lib/python3.6/site-packages/anaconda_navigator/api/anaconda_api.py", line 89, in __init__
    self._conda_api = CondaAPI()
  File "/home/aras/anaconda3/lib/python3.6/site-packages/anaconda_navigator/api/conda_api.py", line 1699, in CondaAPI
    CONDA_API = _CondaAPI()
  File "/home/aras/anaconda3/lib/python3.6/site-packages/anaconda_navigator/api/conda_api.py", line 347, in __init__
    self.set_conda_prefix()
  File "/home/aras/anaconda3/lib/python3.6/site-packages/anaconda_navigator/api/conda_api.py", line 510, in set_conda_prefix
    self._user_agent = info['user_agent']
KeyError: 'user_agent'

##### Anaconda or Miniconda version:
4.2.16
##### Operating System:
ubuntu_16.4
##### `conda info`

```
Current conda install:

               platform : linux-64
          conda version : 4.2.16
       conda is private : False
      conda-env version : 4.2.16
    conda-build version : 2.1.17
         python version : 3.6.3.final.0
       requests version : 2.18.4
       root environment : /home/aras/anaconda3  (writable)
    default environment : /home/aras/anaconda3
       envs directories : /home/aras/anaconda3/envs
          package cache : /home/aras/anaconda3/pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : /home/aras/.condarc
           offline mode : False

```

##### `conda list --show-channel-urls`

```
# packages in environment at /home/aras/anaconda3:
#
_ipyw_jlab_nb_ext_conf    0.1.0            py36he11e457_0    https://repo.continuum.io/pkgs/main
alabaster                 0.7.10           py36h306e16b_0    https://repo.continuum.io/pkgs/main
anaconda                  custom           py36hbbc8b67_0    anaconda
anaconda-client           1.6.12                   py36_0    anaconda
anaconda-navigator        1.8.2                    py36_0    https://repo.anaconda.com/pkgs/main
anaconda-project          0.8.0            py36h29abdf5_0    https://repo.continuum.io/pkgs/main
asn1crypto                0.22.0           py36h265ca7c_1    https://repo.continuum.io/pkgs/main
astroid                   1.5.3            py36hbdb9df2_0    https://repo.continuum.io/pkgs/main
astropy                   2.0.2            py36ha51211e_4    https://repo.continuum.io/pkgs/main
autograd                  1.1.2               np112py36_0    omnia
babel                     2.5.0            py36h7d14adf_0    https://repo.continuum.io/pkgs/main
backports                 1.0              py36hfa02d7e_1    https://repo.continuum.io/pkgs/main
backports.shutil_get_terminal_size 1.0.0            py36hfea85ff_2    https://repo.continuum.io/pkgs/main
beautifulsoup4            4.6.0            py36h49b8c8c_1    https://repo.continuum.io/pkgs/main
bitarray                  0.8.1            py36h5834eb8_0    https://repo.continuum.io/pkgs/main
bkcharts                  0.2              py36h735825a_0    https://repo.continuum.io/pkgs/main
blas                      1.1                    openblas    conda-forge
blaze                     0.11.3           py36h4e06776_0    https://repo.continuum.io/pkgs/main
bleach                    2.0.0            py36h688b259_0    https://repo.continuum.io/pkgs/main
bokeh                     0.12.10          py36hbb0e44a_0    https://repo.continuum.io/pkgs/main
boto                      2.48.0           py36h6e4cd66_1    https://repo.continuum.io/pkgs/main
bottleneck                1.2.1            py36haac1ea0_0    https://repo.continuum.io/pkgs/main
bzip2                     1.0.6                h0376d23_1    https://repo.continuum.io/pkgs/main
ca-certificates           2016.2.28                     1    conda-forge/label/broken
cairo                     1.14.10              haa5651f_5    https://repo.continuum.io/pkgs/main
certifi                   2018.1.18                py36_0    https://repo.anaconda.com/pkgs/main
cffi                      1.10.0           py36had8d393_1    https://repo.continuum.io/pkgs/main
chardet                   3.0.4            py36h0f667ec_1    https://repo.continuum.io/pkgs/main
click                     6.7              py36h5253387_0    https://repo.continuum.io/pkgs/main
cloudpickle               0.4.0            py36h30f8c20_0    https://repo.continuum.io/pkgs/main
clyent                    1.2.2            py36h7e57e65_1    https://repo.continuum.io/pkgs/main
colorama                  0.3.9            py36h489cec4_0    https://repo.continuum.io/pkgs/main
conda                     4.2.16                   py36_0    conda-forge/label/broken
conda-build               2.1.17                   py36_0    defaults
conda-env                 2.6.0                h36134e3_1    anaconda
conda-verify              2.0.0            py36h98955d8_0    https://repo.continuum.io/pkgs/main
contextlib2               0.5.5            py36h6c84a62_0    https://repo.continuum.io/pkgs/main
cryptography              2.0.3            py36ha225213_1    https://repo.continuum.io/pkgs/main
curl                      7.55.1               hcb0b314_2    https://repo.continuum.io/pkgs/main
cycler                    0.10.0           py36h93f1223_0    https://repo.continuum.io/pkgs/main
cython                    0.26.1           py36h21c49d0_0    https://repo.continuum.io/pkgs/main
cytoolz                   0.8.2            py36h708bfd4_0    https://repo.continuum.io/pkgs/main
dask                      0.15.3           py36hdc2c8aa_0    https://repo.continuum.io/pkgs/main
dask-core                 0.15.3           py36h10e6167_0    https://repo.continuum.io/pkgs/main
datashape                 0.5.4            py36h3ad6b5c_0    https://repo.continuum.io/pkgs/main
dbus                      1.10.22              h3b5a359_0    https://repo.continuum.io/pkgs/main
decorator                 4.1.2            py36hd076ac8_0    https://repo.continuum.io/pkgs/main
distributed               1.19.1           py36h25f3894_0    https://repo.continuum.io/pkgs/main
docutils                  0.14             py36hb0f60f5_0    https://repo.continuum.io/pkgs/main
entrypoints               0.2.3            py36h1aec115_2    https://repo.continuum.io/pkgs/main
et_xmlfile                1.0.1            py36hd6bccc3_0    https://repo.continuum.io/pkgs/main
expat                     2.2.4                hc00ebd1_1    https://repo.continuum.io/pkgs/main
fastcache                 1.0.2            py36h5b0c431_0    https://repo.continuum.io/pkgs/main
ffmpeg                    3.2.4                         3    conda-forge
filelock                  2.0.12           py36hacfa1f5_0    https://repo.continuum.io/pkgs/main
flask                     0.12.2           py36hb24657c_0    https://repo.continuum.io/pkgs/main
flask-cors                3.0.3            py36h2d857d3_0    https://repo.continuum.io/pkgs/main
fontconfig                2.12.4               h88586e7_1    https://repo.continuum.io/pkgs/main
freetype                  2.8                  h52ed37b_0    https://repo.continuum.io/pkgs/main
future                    0.16.0                   py36_1    defaults
get_terminal_size         1.0.0                haa9412d_0    https://repo.continuum.io/pkgs/main
gevent                    1.2.2            py36h2fe25dc_0    https://repo.continuum.io/pkgs/main
giflib                    5.1.4                         0    conda-forge
glib                      2.53.6               hc861d11_1    https://repo.continuum.io/pkgs/main
glob2                     0.5              py36h2c1b292_1    https://repo.continuum.io/pkgs/main
gmp                       6.1.2                hb3b607b_0    https://repo.continuum.io/pkgs/main
gmpy2                     2.0.8            py36h55090d7_1    https://repo.continuum.io/pkgs/main
graphite2                 1.3.10               hc526e54_0    https://repo.continuum.io/pkgs/main
greenlet                  0.4.12           py36h2d503a6_0    https://repo.continuum.io/pkgs/main
gst-plugins-base          1.12.2               he3457e5_0    https://repo.continuum.io/pkgs/main
gstreamer                 1.12.2               h4f93127_0    https://repo.continuum.io/pkgs/main
h5py                      2.7.0            py36he81ebca_1    https://repo.continuum.io/pkgs/main
harfbuzz                  1.7.4                hc5b324e_0    https://repo.anaconda.com/pkgs/main
hdf5                      1.10.1               hb0523eb_0    https://repo.continuum.io/pkgs/main
heapdict                  1.0.0            py36h79797d7_0    https://repo.continuum.io/pkgs/main
html5lib                  0.999999999      py36h2cfc398_0    https://repo.continuum.io/pkgs/main
icu                       58.2                 h211956c_0    https://repo.continuum.io/pkgs/main
idna                      2.6              py36h82fb2a8_1    https://repo.continuum.io/pkgs/main
imageio                   2.2.0            py36he555465_0    https://repo.continuum.io/pkgs/main
imagesize                 0.7.1            py36h52d8127_0    https://repo.continuum.io/pkgs/main
intel-openmp              2018.0.0             h15fc484_7    https://repo.continuum.io/pkgs/main
ipykernel                 4.6.1            py36hbf841aa_0    https://repo.continuum.io/pkgs/main
ipython                   6.1.0            py36hc72a948_1    https://repo.continuum.io/pkgs/main
ipython_genutils          0.2.0            py36hb52b0d5_0    https://repo.continuum.io/pkgs/main
ipywidgets                7.0.0            py36h7b55c3a_0    https://repo.continuum.io/pkgs/main
isort                     4.2.15           py36had401c0_0    https://repo.continuum.io/pkgs/main
itsdangerous              0.24             py36h93cc618_1    https://repo.continuum.io/pkgs/main
jasper                    1.900.1                       4    conda-forge
jbig                      2.1                  hdba287a_0    https://repo.continuum.io/pkgs/main
jdcal                     1.3              py36h4c697fb_0    https://repo.continuum.io/pkgs/main
jedi                      0.10.2           py36h552def0_0    https://repo.continuum.io/pkgs/main
jinja2                    2.9.6            py36h489bce4_1    https://repo.continuum.io/pkgs/main
jpeg                      9b                   habf39ab_1    https://repo.continuum.io/pkgs/main
jsonschema                2.6.0            py36h006f8b5_0    https://repo.continuum.io/pkgs/main
jupyter                   1.0.0            py36h9896ce5_0    https://repo.continuum.io/pkgs/main
jupyter_client            5.1.0            py36h614e9ea_0    https://repo.continuum.io/pkgs/main
jupyter_console           5.2.0            py36he59e554_1    https://repo.continuum.io/pkgs/main
jupyter_core              4.3.0            py36h357a921_0    https://repo.continuum.io/pkgs/main
jupyterlab                0.27.0           py36h86377d0_2    https://repo.continuum.io/pkgs/main
jupyterlab_launcher       0.4.0            py36h4d8058d_0    https://repo.continuum.io/pkgs/main
lazy-object-proxy         1.3.1            py36h10fcdad_0    https://repo.continuum.io/pkgs/main
libedit                   3.1                  heed3624_0    https://repo.continuum.io/pkgs/main
libffi                    3.2.1                h4deb6c0_3    https://repo.continuum.io/pkgs/main
libgcc-ng                 7.2.0                h7cc24e2_2    https://repo.continuum.io/pkgs/main
libgfortran               3.0.0                         1    defaults
libgfortran-ng            7.2.0                h9f7466a_2    https://repo.continuum.io/pkgs/main
libiconv                  1.15                          0    conda-forge
libpng                    1.6.32               hda9c8bc_2    https://repo.continuum.io/pkgs/main
libsodium                 1.0.13               h31c71d8_2    https://repo.continuum.io/pkgs/main
libssh2                   1.8.0                h8c220ad_2    https://repo.continuum.io/pkgs/main
libstdcxx-ng              7.2.0                h7a57d05_2    https://repo.continuum.io/pkgs/main
libtiff                   4.0.8                h90200ff_9    https://repo.continuum.io/pkgs/main
libtool                   2.4.6                hd50d1a6_0    https://repo.continuum.io/pkgs/main
libwebp                   0.5.2                         7    conda-forge
libxcb                    1.12                 h84ff03f_3    https://repo.continuum.io/pkgs/main
libxml2                   2.9.4                h6b072ca_5    https://repo.continuum.io/pkgs/main
libxslt                   1.1.29               hcf9102b_5    https://repo.continuum.io/pkgs/main
llvmlite                  0.20.0                   py36_0    https://repo.continuum.io/pkgs/main
locket                    0.2.0            py36h787c0ad_1    https://repo.continuum.io/pkgs/main
lxml                      4.1.0            py36h5b66e50_0    https://repo.continuum.io/pkgs/main
lzo                       2.10                 h1bfc0ba_1    https://repo.continuum.io/pkgs/main
markupsafe                1.0              py36hd9260cd_1    https://repo.continuum.io/pkgs/main
matplotlib                2.1.0            py36hba5de38_0    https://repo.continuum.io/pkgs/main
mccabe                    0.6.1            py36h5ad9710_1    https://repo.continuum.io/pkgs/main
mistune                   0.7.4            py36hbab8784_0    https://repo.continuum.io/pkgs/main
mkl                       2018.0.0             hb491cac_4    https://repo.continuum.io/pkgs/main
mkl-service               1.1.2            py36h17a0993_4    https://repo.continuum.io/pkgs/main
mpc                       1.0.3                hf803216_4    https://repo.continuum.io/pkgs/main
mpfr                      3.1.5                h12ff648_1    https://repo.continuum.io/pkgs/main
mpmath                    0.19             py36h8cc018b_2    https://repo.continuum.io/pkgs/main
msgpack-python            0.4.8            py36hec4c5d1_0    https://repo.continuum.io/pkgs/main
multipledispatch          0.4.9            py36h41da3fb_0    https://repo.continuum.io/pkgs/main
navigator-updater         0.1.0            py36h14770f7_0    https://repo.continuum.io/pkgs/main
nbconvert                 5.3.1            py36hb41ffb7_0    https://repo.continuum.io/pkgs/main
nbformat                  4.4.0            py36h31c9010_0    https://repo.continuum.io/pkgs/main
ncurses                   6.0                  h06874d7_1    https://repo.continuum.io/pkgs/main
networkx                  2.0              py36h7e96fb8_0    https://repo.continuum.io/pkgs/main
nltk                      3.2.4            py36h1a0979f_0    https://repo.continuum.io/pkgs/main
nose                      1.3.7            py36hcdf7029_2    https://repo.continuum.io/pkgs/main
notebook                  5.0.0            py36h0b20546_2    https://repo.continuum.io/pkgs/main
numba                     0.35.0              np112py36_0    defaults
numexpr                   2.6.2            py36hdd3393f_1    https://repo.continuum.io/pkgs/main
numpy                     1.12.1          py36_blas_openblas_201  [blas_openblas]  conda-forge
numpydoc                  0.7.0            py36h18f165f_0    https://repo.continuum.io/pkgs/main
odo                       0.5.1            py36h90ed295_0    https://repo.continuum.io/pkgs/main
olefile                   0.44             py36h79f9f78_0    https://repo.continuum.io/pkgs/main
openblas                  0.2.20                        7    conda-forge
opencv                    3.4.1           py36_blas_openblas_200  [blas_openblas]  conda-forge
openpyxl                  2.4.8            py36h41dd2a8_1    https://repo.continuum.io/pkgs/main
openssl                   1.0.2o               h20670df_0    https://repo.anaconda.com/pkgs/main
packaging                 16.8             py36ha668100_1    https://repo.continuum.io/pkgs/main
pandas                    0.20.3           py36h842e28d_2    https://repo.continuum.io/pkgs/main
pandoc                    1.19.2.1             hea2e7c5_1    https://repo.continuum.io/pkgs/main
pandocfilters             1.4.2            py36ha6701b7_1    https://repo.continuum.io/pkgs/main
pango                     1.40.11              h8191d47_0    https://repo.continuum.io/pkgs/main
partd                     0.3.8            py36h36fd896_0    https://repo.continuum.io/pkgs/main
patchelf                  0.9                  hf79760b_2    https://repo.continuum.io/pkgs/main
path.py                   10.3.1           py36he0c6f6d_0    https://repo.continuum.io/pkgs/main
pathlib2                  2.3.0            py36h49efa8e_0    https://repo.continuum.io/pkgs/main
patsy                     0.4.1            py36ha3be15e_0    https://repo.continuum.io/pkgs/main
pcre                      8.41                 hc71a17e_0    https://repo.continuum.io/pkgs/main
pep8                      1.7.0            py36h26ade29_0    https://repo.continuum.io/pkgs/main
pexpect                   4.2.1            py36h3b9d41b_0    https://repo.continuum.io/pkgs/main
pickleshare               0.7.4            py36h63277f8_0    https://repo.continuum.io/pkgs/main
pillow                    4.2.1            py36h9119f52_0    https://repo.continuum.io/pkgs/main
pip                       9.0.1            py36h8ec8b28_3    https://repo.continuum.io/pkgs/main
pixman                    0.34.0               h83dc358_2    https://repo.continuum.io/pkgs/main
pkginfo                   1.4.1            py36h215d178_1    https://repo.continuum.io/pkgs/main
plotly                    2.4.1                    py36_0    https://repo.continuum.io/pkgs/main
ply                       3.10             py36hed35086_0    https://repo.continuum.io/pkgs/main
prompt_toolkit            1.0.15           py36h17d85b1_0    https://repo.continuum.io/pkgs/main
psutil                    5.4.0            py36h84c53db_0    https://repo.continuum.io/pkgs/main
ptyprocess                0.5.2            py36h69acd42_0    https://repo.continuum.io/pkgs/main
py                        1.4.34           py36h0712aa3_1    https://repo.continuum.io/pkgs/main
pycodestyle               2.3.1            py36hf609f19_0    https://repo.continuum.io/pkgs/main
pycosat                   0.6.3            py36h0a5515d_0    anaconda
pycparser                 2.18             py36hf9f622e_1    https://repo.continuum.io/pkgs/main
pycrypto                  2.6.1            py36h6998063_1    https://repo.continuum.io/pkgs/main
pycurl                    7.43.0           py36h5e72054_3    https://repo.continuum.io/pkgs/main
pyflakes                  1.6.0            py36h7bd6a15_0    https://repo.continuum.io/pkgs/main
pygments                  2.2.0            py36h0d3125c_0    https://repo.continuum.io/pkgs/main
pylint                    1.7.4            py36hb9d4533_0    https://repo.continuum.io/pkgs/main
pyodbc                    4.0.17           py36h999153c_0    https://repo.continuum.io/pkgs/main
pyopenssl                 17.2.0           py36h5cc804b_0    https://repo.continuum.io/pkgs/main
pyparsing                 2.2.0            py36hee85983_1    https://repo.continuum.io/pkgs/main
pyqt                      5.6.0            py36h0386399_5    https://repo.continuum.io/pkgs/main
pysocks                   1.6.7            py36hd97a5b1_1    https://repo.continuum.io/pkgs/main
pytables                  3.4.2            py36h3b5282a_2    https://repo.continuum.io/pkgs/main
pytest                    3.2.1            py36h11ad3bb_1    https://repo.continuum.io/pkgs/main
python                    3.6.3                hc9025b9_1    https://repo.continuum.io/pkgs/main
python-dateutil           2.6.1            py36h88d3b88_1    https://repo.continuum.io/pkgs/main
pytz                      2017.2           py36hc2ccc2a_1    https://repo.continuum.io/pkgs/main
pywavelets                0.5.2            py36he602eb0_0    https://repo.continuum.io/pkgs/main
pyyaml                    3.12             py36hafb9ca4_1    https://repo.continuum.io/pkgs/main
pyzmq                     16.0.2           py36h3b0cf96_2    https://repo.continuum.io/pkgs/main
qt                        5.6.2               h974d657_12    https://repo.continuum.io/pkgs/main
qtawesome                 0.4.4            py36h609ed8c_0    https://repo.continuum.io/pkgs/main
qtconsole                 4.3.1            py36h8f73b5b_0    https://repo.continuum.io/pkgs/main
qtpy                      1.3.1            py36h3691cc8_0    https://repo.continuum.io/pkgs/main
readline                  7.0                  hac23ff0_3    https://repo.continuum.io/pkgs/main
requests                  2.18.4           py36he2e5f8d_1    https://repo.continuum.io/pkgs/main
rope                      0.10.5           py36h1f8c17e_0    https://repo.continuum.io/pkgs/main
ruamel_yaml               0.11.14          py36ha2fb22d_2    https://repo.continuum.io/pkgs/main
scikit-image              0.13.0           py36had3c07a_1    https://repo.continuum.io/pkgs/main
scikit-learn              0.19.1          py36_blas_openblas_201  [blas_openblas]  conda-forge
scipy                     1.0.1           py36_blas_openblas_200  [blas_openblas]  conda-forge
seaborn                   0.8.0            py36h197244f_0    https://repo.continuum.io/pkgs/main
setuptools                36.5.0           py36he42e2e1_0    https://repo.continuum.io/pkgs/main
simplegeneric             0.8.1            py36h2cb9092_0    https://repo.continuum.io/pkgs/main
singledispatch            3.4.0.3          py36h7a266c3_0    https://repo.continuum.io/pkgs/main
sip                       4.18.1           py36h51ed4ed_2    https://repo.continuum.io/pkgs/main
six                       1.11.0           py36h372c433_1    https://repo.continuum.io/pkgs/main
snowballstemmer           1.2.1            py36h6febd40_0    https://repo.continuum.io/pkgs/main
sortedcollections         0.5.3            py36h3c761f9_0    https://repo.continuum.io/pkgs/main
sortedcontainers          1.5.7            py36hdf89491_0    https://repo.continuum.io/pkgs/main
sphinx                    1.6.3            py36he5f0bdb_0    https://repo.continuum.io/pkgs/main
sphinxcontrib             1.0              py36h6d0f590_1    https://repo.continuum.io/pkgs/main
sphinxcontrib-websupport  1.0.1            py36hb5cb234_1    https://repo.continuum.io/pkgs/main
spyder                    3.2.4            py36hbe6152b_0    https://repo.continuum.io/pkgs/main
sqlalchemy                1.1.13           py36hfb5efd7_0    https://repo.continuum.io/pkgs/main
sqlite                    3.20.1               h6d8b0f3_1    https://repo.continuum.io/pkgs/main
statsmodels               0.8.0            py36h8533d0b_0    https://repo.continuum.io/pkgs/main
sympy                     1.1.1            py36hc6d1c1c_0    https://repo.continuum.io/pkgs/main
tblib                     1.3.2            py36h34cf8b6_0    https://repo.continuum.io/pkgs/main
terminado                 0.6              py36ha25a19f_0    https://repo.continuum.io/pkgs/main
testpath                  0.3.1            py36h8cadb63_0    https://repo.continuum.io/pkgs/main
tk                        8.6.7                h5979e9b_1    https://repo.continuum.io/pkgs/main
toolz                     0.8.2            py36h81f2dff_0    https://repo.continuum.io/pkgs/main
tornado                   4.5.2            py36h1283b2a_0    https://repo.continuum.io/pkgs/main
traitlets                 4.3.2            py36h674d592_0    https://repo.continuum.io/pkgs/main
typing                    3.6.2            py36h7da032a_0    https://repo.continuum.io/pkgs/main
unicodecsv                0.14.1           py36ha668878_0    https://repo.continuum.io/pkgs/main
unixodbc                  2.3.4                hc36303a_1    https://repo.continuum.io/pkgs/main
urllib3                   1.22             py36hbe7ace6_0    https://repo.continuum.io/pkgs/main
wcwidth                   0.1.7            py36hdf4376a_0    https://repo.continuum.io/pkgs/main
webencodings              0.5.1            py36h800622e_1    https://repo.continuum.io/pkgs/main
werkzeug                  0.12.2           py36hc703753_0    https://repo.continuum.io/pkgs/main
wheel                     0.29.0           py36he7f4e38_1    https://repo.continuum.io/pkgs/main
widgetsnbextension        3.0.2            py36hd01bb71_1    https://repo.continuum.io/pkgs/main
wrapt                     1.10.11          py36h28b7045_0    https://repo.continuum.io/pkgs/main
x264                      20131217                      3    conda-forge
xlrd                      1.1.0            py36h1db9f0c_1    https://repo.continuum.io/pkgs/main
xlsxwriter                1.0.2            py36h3de1aca_0    https://repo.continuum.io/pkgs/main
xlwt                      1.3.0            py36h7b00a1f_0    https://repo.continuum.io/pkgs/main
xz                        5.2.3                h2bcbf08_1    https://repo.continuum.io/pkgs/main
yaml                      0.1.7                h96e3832_1    https://repo.continuum.io/pkgs/main
zeromq                    4.2.2                hb0b69da_1    https://repo.continuum.io/pkgs/main
zict                      0.1.3            py36h3a3bf81_0    https://repo.continuum.io/pkgs/main
zlib                      1.2.11               hfbfcf68_1    https://repo.continuum.io/pkgs/main

```

**Comment by esra-aydemir** [comment]
After I have removed and reinstallled conda forge it worked as expected.

**Comment by goanpeca** [comment]
@esra-aydemir you are using an old version of conda, I would suggest you updated all your packages to newer versions

```
conda update conda
conda update --all
```

**Comment by atahadd** [comment]
I have the same problem, and it didnt work
