### ISSUE TITLE
Trouble started with could not get R to work and then Navigator

### ISSUE THREAD

**Issue by mccurcio** [ContinuumIO/anaconda-issues#9179]
### Actual Behavior
loaded and Anaconda3-5.1.0-Linux-x86_64.sh,
I did a clean install of Anaconda Python3.6 for linux 64 bit and was running the 'anaconda-navigator' to learn it. I could not get the Environments working, bc it did not show the "create" button on the new create mini-window.  Then I was investigating how the R was working.  I could not get anything to work after a while.

### Expected Behavior

I wanted to work with a jupyter notebook and R then install a package for R, seqinr. None of that worked.

### Steps to Reproduce

All I need to do is Run: anaconda-navigator

AND (pow)
Navigator Error
An unexpected error occurred on Navigator start-up

Report
Please report this issue in the anaconda issue tracker

Main Error
byte indices must be integers or slices, not str
Traceback
Traceback (most recent call last):
  File "/home/mcc/anaconda3/lib/python3.6/site-packages/anaconda_navigator/exceptions.py", line 75, in exception_handler
    return_value = func(*args, **kwargs)
  File "/home/mcc/anaconda3/lib/python3.6/site-packages/anaconda_navigator/app/start.py", line 138, in start_app
    window = run_app(splash)
  File "/home/mcc/anaconda3/lib/python3.6/site-packages/anaconda_navigator/app/start.py", line 64, in run_app
    window = MainWindow(splash=splash, tab_project=False)
  File "/home/mcc/anaconda3/lib/python3.6/site-packages/anaconda_navigator/widgets/main_window.py", line 163, in __init__
    self.api = AnacondaAPI()
  File "/home/mcc/anaconda3/lib/python3.6/site-packages/anaconda_navigator/api/anaconda_api.py", line 2086, in AnacondaAPI
    ANACONDA_API = _AnacondaAPI()
  File "/home/mcc/anaconda3/lib/python3.6/site-packages/anaconda_navigator/api/anaconda_api.py", line 89, in __init__
    self._conda_api = CondaAPI()
  File "/home/mcc/anaconda3/lib/python3.6/site-packages/anaconda_navigator/api/conda_api.py", line 1699, in CondaAPI
    CONDA_API = _CondaAPI()
  File "/home/mcc/anaconda3/lib/python3.6/site-packages/anaconda_navigator/api/conda_api.py", line 347, in __init__
    self.set_conda_prefix()
  File "/home/mcc/anaconda3/lib/python3.6/site-packages/anaconda_navigator/api/conda_api.py", line 506, in set_conda_prefix
    self.ROOT_PREFIX = info['root_prefix']
TypeError: byte indices must be integers or slices, not str

##### Operating System:
linux mint 18.2

##### `conda info`

NOTHING HAPPENED
```
~/anaconda3 $ conda info 
~/anaconda3 $ 

```

##### `conda list --show-channel-urls`

```
NOTHING HAPPENED
~/anaconda3 $ conda list --show-channel-urls
~/anaconda3 $ 

```

**Comment by goanpeca** [comment]
@mccurcio you will need to properly activate the environment before issuing the commands. Open a terminal and type

```
source activate base
conda info
conda list --show-channel-urls
```

Also try to run navigator that way

```
source activate base
anaconda-navigator
```

**Comment by mccurcio** [comment]
Wow, This is strange.  When I use:
~/anaconda3 $ source activate base
I now get back:
bash: /home/mcc/anaconda3/etc/profile.d/conda.sh: line 80: syntax error near unexpected token `('
bash: /home/mcc/anaconda3/etc/profile.d/conda.sh: line 80: `conda() {'

Then I tried:
~ $ conda info
mcc@A505 ~ $ conda list --show-channel-urls
mcc@A505 ~ $ source activate base
bash: /home/mcc/anaconda3/etc/profile.d/conda.sh: line 80: syntax error near unexpected token `('
bash: /home/mcc/anaconda3/etc/profile.d/conda.sh: line 80: `conda() {'
mcc@A505 ~ $ anaconda-navigator
An unexpected error occurred on Navigator start-up<br>byte indices must be integers or slices, not str
Traceback (most recent call last):
  File "/home/mcc/anaconda3/lib/python3.6/site-packages/anaconda_navigator/exceptions.py", line 75, in exception_handler
    return_value = func(*args, **kwargs)
  File "/home/mcc/anaconda3/lib/python3.6/site-packages/anaconda_navigator/app/start.py", line 138, in start_app
    window = run_app(splash)
  File "/home/mcc/anaconda3/lib/python3.6/site-packages/anaconda_navigator/app/start.py", line 64, in run_app
    window = MainWindow(splash=splash, tab_project=False)
  File "/home/mcc/anaconda3/lib/python3.6/site-packages/anaconda_navigator/widgets/main_window.py", line 163, in __init__
    self.api = AnacondaAPI()
  File "/home/mcc/anaconda3/lib/python3.6/site-packages/anaconda_navigator/api/anaconda_api.py", line 2086, in AnacondaAPI
    ANACONDA_API = _AnacondaAPI()
  File "/home/mcc/anaconda3/lib/python3.6/site-packages/anaconda_navigator/api/anaconda_api.py", line 89, in __init__
    self._conda_api = CondaAPI()
  File "/home/mcc/anaconda3/lib/python3.6/site-packages/anaconda_navigator/api/conda_api.py", line 1699, in CondaAPI
    CONDA_API = _CondaAPI()
  File "/home/mcc/anaconda3/lib/python3.6/site-packages/anaconda_navigator/api/conda_api.py", line 347, in __init__
    self.set_conda_prefix()
  File "/home/mcc/anaconda3/lib/python3.6/site-packages/anaconda_navigator/api/conda_api.py", line 506, in set_conda_prefix
    self.ROOT_PREFIX = info['root_prefix']
TypeError: byte indices must be integers or slices, not str

**Comment by goanpeca** [comment]
@kalefranz thoughts?

**Comment by mccurcio** [comment]
After I down loaded I did check the md5 and it as good. I am considering starting over and deleting and reinstalling...
What do you think?

**Comment by mccurcio** [comment]
As an aside, I loaded Anaconda in my home director but I think I will use /opt/anaconda3 for the next time.
