### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by jgrundling** [ContinuumIO/anaconda-issues#9180]
## Main error
Application <b>spyder</b> launch may have produced errors.
## Traceback
```
Traceback (most recent call last):
  File "/home/jack/anaconda3/bin/spyder", line 7, in <module>
    from spyder.app.start import main
  File "/home/jack/anaconda3/lib/python3.6/site-packages/spyder/app/start.py", line 14, in <module>
    import zmq
  File "/home/jack/anaconda3/lib/python3.6/site-packages/zmq/__init__.py", line 47, in <module>
    from zmq import backend
  File "/home/jack/anaconda3/lib/python3.6/site-packages/zmq/backend/__init__.py", line 40, in <module>
    reraise(*exc_info)
  File "/home/jack/anaconda3/lib/python3.6/site-packages/zmq/utils/sixcerpt.py", line 34, in reraise
    raise value
  File "/home/jack/anaconda3/lib/python3.6/site-packages/zmq/backend/__init__.py", line 27, in <module>
    _ns = select_backend(first)
  File "/home/jack/anaconda3/lib/python3.6/site-packages/zmq/backend/select.py", line 26, in select_backend
    mod = __import__(name, fromlist=public_api)
  File "/home/jack/anaconda3/lib/python3.6/site-packages/zmq/backend/cython/__init__.py", line 6, in <module>
    from . import (constants, error, message, context,
ImportError: libsodium.so.23: cannot open shared object file: No such file or directory

```
## System information
```
python: 3.6.3
language: en_AU
os: Linux;4.13.0-38-generic;#43~16.04.1-Ubuntu SMP Wed Mar 14 17:48:43 UTC 2018;x86_64;x86_64
version: 1.6.2
platform: linux-64
qt: 5.6.2
pyqt: 5.6.0
conda: 4.5.0
```

**Comment by goanpeca** [comment]
@ccordoba12 ?

**Comment by mathubhalan** [comment]
Having Spyder load error in Anaconda

Traceback (most recent call last):
  File "C:\Users\mathu_gopalan\AppData\Local\Continuum\anaconda3\lib\site-packages\qtpy\__init__.py", line 148, in <module>
    from PySide import __version__ as PYSIDE_VERSION  # analysis:ignore
ModuleNotFoundError: No module named 'PySide'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\mathu_gopalan\AppData\Local\Continuum\anaconda3\Scripts\spyder-script.py", line 10, in <module>
    sys.exit(main())
  File "C:\Users\mathu_gopalan\AppData\Local\Continuum\anaconda3\lib\site-packages\spyder\app\start.py", line 159, in main
    from spyder.app import mainwindow
  File "C:\Users\mathu_gopalan\AppData\Local\Continuum\anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 49, in <module>
    requirements.check_qt()
  File "C:\Users\mathu_gopalan\AppData\Local\Continuum\anaconda3\lib\site-packages\spyder\requirements.py", line 39, in check_qt
    import qtpy
  File "C:\Users\mathu_gopalan\AppData\Local\Continuum\anaconda3\lib\site-packages\qtpy\__init__.py", line 154, in <module>
    raise PythonQtError('No Qt bindings could be found')
qtpy.PythonQtError: No Qt bindings could be found

**Comment by stared** [comment]
Did you try `conda install -c conda-forge libsodium`? (It helped me with the same `zmq` problem.)
