### ISSUE TITLE
Navigator Error on Start-Up - root_prefix

### ISSUE THREAD

**Issue by ksednew** [ContinuumIO/anaconda-issues#9201]
An unexpected error occurred on Navigator start-up

Report

Please report this issue in the anaconda issue tracker

Main Error

'root_prefix'
Traceback

Traceback (most recent call last):
  File "/anaconda3/lib/python3.6/site-packages/anaconda_navigator/exceptions.py", line 75, in exception_handler
    return_value = func(*args, **kwargs)
  File "/anaconda3/lib/python3.6/site-packages/anaconda_navigator/app/start.py", line 120, in start_app
    window = run_app(splash)
  File "/anaconda3/lib/python3.6/site-packages/anaconda_navigator/app/start.py", line 63, in run_app
    window = MainWindow(splash=splash)
  File "/anaconda3/lib/python3.6/site-packages/anaconda_navigator/widgets/main_window.py", line 163, in __init__
    self.api = AnacondaAPI()
  File "/anaconda3/lib/python3.6/site-packages/anaconda_navigator/api/anaconda_api.py", line 2004, in AnacondaAPI
    ANACONDA_API = _AnacondaAPI()
  File "/anaconda3/lib/python3.6/site-packages/anaconda_navigator/api/anaconda_api.py", line 88, in __init__
    self._conda_api = CondaAPI()
  File "/anaconda3/lib/python3.6/site-packages/anaconda_navigator/api/conda_api.py", line 1690, in CondaAPI
    CONDA_API = _CondaAPI()
  File "/anaconda3/lib/python3.6/site-packages/anaconda_navigator/api/conda_api.py", line 347, in __init__
    self.set_conda_prefix()
  File "/anaconda3/lib/python3.6/site-packages/anaconda_navigator/api/conda_api.py", line 496, in set_conda_prefix
    self.ROOT_PREFIX = info['root_prefix']
KeyError: 'root_prefix'

**Comment by goanpeca** [comment]
@ksednew  if you open the anaconda prompt does it print something?

Also could you provide the output of running on the anaconda prompt

```
conda info
```

and
```
conda list --show-channel-urls
```

If there is an error please paste (as text) the text of the error

**Comment by ksednew** [comment]
Turns out my company had my conda config --set ssl_verify set to a specific file name (certificate), instead of "True" or "False" ... the boolean value it was looking for. Once I did that, I pushed conda install conda-build --force" and voila! all fixed!

**Comment by goanpeca** [comment]
@ksednew well actually ssl_verify expects True, False or a certificate, so maybe the certificate was not correctly set, but a path to a certificate is a valid option as well.
