### ISSUE TITLE
Getting this error after installation & unable to open anaconda

### ISSUE THREAD

**Issue by pavansvn** [ContinuumIO/anaconda-issues#9207]
Traceback

Traceback (most recent call last):
  File "C:\Anaconda3\lib\site-packages\anaconda_navigator\exceptions.py", line 75, in exception_handler
    return_value = func(*args, **kwargs)
  File "C:\Anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 120, in start_app
    window = run_app(splash)
  File "C:\Anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 63, in run_app
    window = MainWindow(splash=splash)
  File "C:\Anaconda3\lib\site-packages\anaconda_navigator\widgets\main_window.py", line 161, in __init__
    self.api = AnacondaAPI()
  File "C:\Anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 1258, in AnacondaAPI
    ANACONDA_API = _AnacondaAPI()
  File "C:\Anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 70, in __init__
    self._conda_api = CondaAPI()
  File "C:\Anaconda3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 1654, in CondaAPI
    CONDA_API = _CondaAPI()
  File "C:\Anaconda3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 345, in __init__
    self.set_conda_prefix()
  File "C:\Anaconda3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 493, in set_conda_prefix
    info = worker.communicate()[0]
  File "C:\Anaconda3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 271, in communicate
    " ".join(self._cmd_list), result[0]['message']
KeyError: 'message'

**Comment by goanpeca** [comment]
@pavansvn  if you open the anaconda prompt does it print something?

Also could you provide the output of running on the anaconda prompt

```
conda info
```

and
```
conda list --show-channel-urls
```

If there is an error please paste (as text) the text of the error

**Comment by sapeters68102** [comment]
I have the exact same error.
could not determine a constructor for the tag 'tag:yaml.org,2002:python/unicode'
  in "/Users/Scott/Library/Application Support/binstar/config.yaml", line 1, column 1
Traceback

Traceback (most recent call last):
  File "/anaconda3/lib/python3.6/site-packages/anaconda_navigator/exceptions.py", line 75, in exception_handler
    return_value = func(*args, **kwargs)
  File "/anaconda3/lib/python3.6/site-packages/anaconda_navigator/app/start.py", line 120, in start_app
    window = run_app(splash)
  File "/anaconda3/lib/python3.6/site-packages/anaconda_navigator/app/start.py", line 63, in run_app
    window = MainWindow(splash=splash)
  File "/anaconda3/lib/python3.6/site-packages/anaconda_navigator/widgets/main_window.py", line 163, in __init__
    self.api = AnacondaAPI()
  File "/anaconda3/lib/python3.6/site-packages/anaconda_navigator/api/anaconda_api.py", line 2004, in AnacondaAPI
    ANACONDA_API = _AnacondaAPI()
  File "/anaconda3/lib/python3.6/site-packages/anaconda_navigator/api/anaconda_api.py", line 89, in __init__
    self._client_api = ClientAPI()
  File "/anaconda3/lib/python3.6/site-packages/anaconda_navigator/api/client_api.py", line 612, in ClientAPI
    CLIENT_API = _ClientAPI()
  File "/anaconda3/lib/python3.6/site-packages/anaconda_navigator/api/client_api.py", line 82, in __init__
    log_level=logging.NOTSET
  File "/anaconda3/lib/python3.6/site-packages/binstar_client/utils/config.py", line 96, in get_server_api
    config = get_config(remote_site=site)
  File "/anaconda3/lib/python3.6/site-packages/binstar_client/utils/config.py", line 229, in get_config
    file_configs = load_file_configs(SEARCH_PATH)
  File "/anaconda3/lib/python3.6/site-packages/binstar_client/utils/config.py", line 223, in load_file_configs
    raw_data = collections.OrderedDict(kv for kv in itertools.chain.from_iterable(load_paths))
  File "/anaconda3/lib/python3.6/site-packages/binstar_client/utils/config.py", line 223, in 
    raw_data = collections.OrderedDict(kv for kv in itertools.chain.from_iterable(load_paths))
  File "/anaconda3/lib/python3.6/site-packages/binstar_client/utils/config.py", line 203, in _dir_yaml_loader
    yield filepath, load_config(filepath)
  File "/anaconda3/lib/python3.6/site-packages/binstar_client/utils/config.py", line 187, in load_config
    data = yaml_load(fd)
  File "/anaconda3/lib/python3.6/site-packages/binstar_client/utils/yaml.py", line 9, in yaml_load
    return safe_load(stream)
  File "/anaconda3/lib/python3.6/site-packages/yaml/__init__.py", line 94, in safe_load
    return load(stream, SafeLoader)
  File "/anaconda3/lib/python3.6/site-packages/yaml/__init__.py", line 72, in load
    return loader.get_single_data()
  File "/anaconda3/lib/python3.6/site-packages/yaml/constructor.py", line 37, in get_single_data
    return self.construct_document(node)
  File "/anaconda3/lib/python3.6/site-packages/yaml/constructor.py", line 46, in construct_document
    for dummy in generator:
  File "/anaconda3/lib/python3.6/site-packages/yaml/constructor.py", line 398, in construct_yaml_map
    value = self.construct_mapping(node)
  File "/anaconda3/lib/python3.6/site-packages/yaml/constructor.py", line 204, in construct_mapping
    return super().construct_mapping(node, deep=deep)
  File "/anaconda3/lib/python3.6/site-packages/yaml/constructor.py", line 125, in construct_mapping
    key = self.construct_object(key_node, deep=deep)
  File "/anaconda3/lib/python3.6/site-packages/yaml/constructor.py", line 86, in construct_object
    data = constructor(self, node)
  File "/anaconda3/lib/python3.6/site-packages/yaml/constructor.py", line 414, in construct_undefined
    node.start_mark)
yaml.constructor.ConstructorError: could not determine a constructor for the tag 'tag:yaml.org,2002:python/unicode'
  in "/Users/Scott/Library/Application Support/binstar/config.yaml", line 1, column 1

**Comment by goanpeca** [comment]
@sapeters68102 that is not the exact same error. To fix your problem, please open a terminal and run

```
conda install anaconda-client=1.6.14
```

**Comment by goanpeca** [comment]
@pavansvn please update navigator open a terminal and run

```
conda install anaconda-navigator=1.8.4
conda install navigator-updater=0.2
```
