### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by wuzeen** [ContinuumIO/anaconda-issues#9211]
## Main error
Application <b>notebook</b> launch may have produced errors.
## Traceback
```
Traceback (most recent call last):
  File "C:\Software\Anacoda\Scripts\jupyter-notebook-script.py", line 3, in <module>
    import notebook.notebookapp
  File "C:\Software\Anacoda\lib\site-packages\notebook\notebookapp.py", line 33, in <module>
    ioloop.install()
  File "C:\Software\Anacoda\lib\site-packages\zmq\eventloop\ioloop.py", line 210, in install
    assert (not ioloop.IOLoop.initialized()) or \
AttributeError: type object 'IOLoop' has no attribute 'initialized'

```
## System information
```
python: 3.6.1
language: zh_CN
os: Windows;10;10.0.16299;AMD64;Intel64 Family 6 Model 69 Stepping 1, GenuineIntel
version: 1.6.2
platform: win-64
qt: 5.6.2
pyqt: 5.6.0
conda: 4.4.6
```

**Comment by goanpeca** [comment]
Please remember to update to the latest version of packages to include
the latest fixes.

Open a terminal (on Linux or Mac) or the Anaconda Command Prompt (on windows)
and type:

```
conda update conda
conda update --all
```
