### ISSUE TITLE
Anaconda would not launch

### ISSUE THREAD

**Issue by tolyla25** [ContinuumIO/anaconda-issues#9271]
### Actual Behavior

 Anaconda would not launch. Version 3.5 64 bit for Windows

Error log:

could not determine a constructor for the tag 'tag:yaml.org,2002:python/unicode'
  in "C:\Users\Toly_Novik\AppData\Local\ContinuumIO\binstar\config.yaml", line 1, column 1

Trace:

raceback (most recent call last):
  File "C:\Users\Toly_Novik\Anaconda3\lib\site-packages\anaconda_navigator\exceptions.py", line 75, in exception_handler
    return_value = func(*args, **kwargs)
  File "C:\Users\Toly_Novik\Anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 120, in start_app
    window = run_app(splash)
  File "C:\Users\Toly_Novik\Anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 63, in run_app
    window = MainWindow(splash=splash)
  File "C:\Users\Toly_Novik\Anaconda3\lib\site-packages\anaconda_navigator\widgets\main_window.py", line 163, in __init__
    self.api = AnacondaAPI()
  File "C:\Users\Toly_Novik\Anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 2004, in AnacondaAPI
    ANACONDA_API = _AnacondaAPI()
  File "C:\Users\Toly_Novik\Anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 89, in __init__
    self._client_api = ClientAPI()
  File "C:\Users\Toly_Novik\Anaconda3\lib\site-packages\anaconda_navigator\api\client_api.py", line 612, in ClientAPI
    CLIENT_API = _ClientAPI()
  File "C:\Users\Toly_Novik\Anaconda3\lib\site-packages\anaconda_navigator\api\client_api.py", line 82, in __init__
    log_level=logging.NOTSET
  File "C:\Users\Toly_Novik\Anaconda3\lib\site-packages\binstar_client\utils\config.py", line 96, in get_server_api
    config = get_config(remote_site=site)
  File "C:\Users\Toly_Novik\Anaconda3\lib\site-packages\binstar_client\utils\config.py", line 229, in get_config
    file_configs = load_file_configs(SEARCH_PATH)
  File "C:\Users\Toly_Novik\Anaconda3\lib\site-packages\binstar_client\utils\config.py", line 223, in load_file_configs
    raw_data = collections.OrderedDict(kv for kv in itertools.chain.from_iterable(load_paths))
  File "C:\Users\Toly_Novik\Anaconda3\lib\site-packages\binstar_client\utils\config.py", line 223, in 
    raw_data = collections.OrderedDict(kv for kv in itertools.chain.from_iterable(load_paths))
  File "C:\Users\Toly_Novik\Anaconda3\lib\site-packages\binstar_client\utils\config.py", line 203, in _dir_yaml_loader
    yield filepath, load_config(filepath)
  File "C:\Users\Toly_Novik\Anaconda3\lib\site-packages\binstar_client\utils\config.py", line 187, in load_config
    data = yaml_load(fd)
  File "C:\Users\Toly_Novik\Anaconda3\lib\site-packages\binstar_client\utils\yaml.py", line 9, in yaml_load
    return safe_load(stream)
  File "C:\Users\Toly_Novik\Anaconda3\lib\site-packages\yaml\__init__.py", line 94, in safe_load
    return load(stream, SafeLoader)
  File "C:\Users\Toly_Novik\Anaconda3\lib\site-packages\yaml\__init__.py", line 72, in load
    return loader.get_single_data()
  File "C:\Users\Toly_Novik\Anaconda3\lib\site-packages\yaml\constructor.py", line 37, in get_single_data
    return self.construct_document(node)
  File "C:\Users\Toly_Novik\Anaconda3\lib\site-packages\yaml\constructor.py", line 46, in construct_document
    for dummy in generator:
  File "C:\Users\Toly_Novik\Anaconda3\lib\site-packages\yaml\constructor.py", line 398, in construct_yaml_map
    value = self.construct_mapping(node)
  File "C:\Users\Toly_Novik\Anaconda3\lib\site-packages\yaml\constructor.py", line 204, in construct_mapping
    return super().construct_mapping(node, deep=deep)
  File "C:\Users\Toly_Novik\Anaconda3\lib\site-packages\yaml\constructor.py", line 125, in construct_mapping
    key = self.construct_object(key_node, deep=deep)
  File "C:\Users\Toly_Novik\Anaconda3\lib\site-packages\yaml\constructor.py", line 86, in construct_object
    data = constructor(self, node)
  File "C:\Users\Toly_Novik\Anaconda3\lib\site-packages\yaml\constructor.py", line 414, in construct_undefined
    node.start_mark)
yaml.constructor.ConstructorError: could not determine a constructor for the tag 'tag:yaml.org,2002:python/unicode'
  in "C:\Users\Toly_Novik\AppData\Local\ContinuumIO\binstar\config.yaml", line 1, column 1

### Expected Behavior

 Anaconda should launch and show its user interface

### Steps to Reproduce

 Just clicked on icon or from the Start menu

##### `conda info`

```
Main Error

could not determine a constructor for the tag 'tag:yaml.org,2002:python/unicode'
  in "C:\Users\Toly_Novik\AppData\Local\ContinuumIO\binstar\config.yaml", line 1, column 1

Traceback (most recent call last):
  File "C:\Users\Toly_Novik\Anaconda3\lib\site-packages\anaconda_navigator\exceptions.py", line 75, in exception_handler
    return_value = func(*args, **kwargs)
  File "C:\Users\Toly_Novik\Anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 120, in start_app
    window = run_app(splash)
  File "C:\Users\Toly_Novik\Anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 63, in run_app
    window = MainWindow(splash=splash)
  File "C:\Users\Toly_Novik\Anaconda3\lib\site-packages\anaconda_navigator\widgets\main_window.py", line 163, in __init__
    self.api = AnacondaAPI()
  File "C:\Users\Toly_Novik\Anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 2004, in AnacondaAPI
    ANACONDA_API = _AnacondaAPI()
  File "C:\Users\Toly_Novik\Anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 89, in __init__
    self._client_api = ClientAPI()
  File "C:\Users\Toly_Novik\Anaconda3\lib\site-packages\anaconda_navigator\api\client_api.py", line 612, in ClientAPI
    CLIENT_API = _ClientAPI()
  File "C:\Users\Toly_Novik\Anaconda3\lib\site-packages\anaconda_navigator\api\client_api.py", line 82, in __init__
    log_level=logging.NOTSET
  File "C:\Users\Toly_Novik\Anaconda3\lib\site-packages\binstar_client\utils\config.py", line 96, in get_server_api
    config = get_config(remote_site=site)
  File "C:\Users\Toly_Novik\Anaconda3\lib\site-packages\binstar_client\utils\config.py", line 229, in get_config
    file_configs = load_file_configs(SEARCH_PATH)
  File "C:\Users\Toly_Novik\Anaconda3\lib\site-packages\binstar_client\utils\config.py", line 223, in load_file_configs
    raw_data = collections.OrderedDict(kv for kv in itertools.chain.from_iterable(load_paths))
  File "C:\Users\Toly_Novik\Anaconda3\lib\site-packages\binstar_client\utils\config.py", line 223, in 
    raw_data = collections.OrderedDict(kv for kv in itertools.chain.from_iterable(load_paths))
  File "C:\Users\Toly_Novik\Anaconda3\lib\site-packages\binstar_client\utils\config.py", line 203, in _dir_yaml_loader
    yield filepath, load_config(filepath)
  File "C:\Users\Toly_Novik\Anaconda3\lib\site-packages\binstar_client\utils\config.py", line 187, in load_config
    data = yaml_load(fd)
  File "C:\Users\Toly_Novik\Anaconda3\lib\site-packages\binstar_client\utils\yaml.py", line 9, in yaml_load
    return safe_load(stream)
  File "C:\Users\Toly_Novik\Anaconda3\lib\site-packages\yaml\__init__.py", line 94, in safe_load
    return load(stream, SafeLoader)
  File "C:\Users\Toly_Novik\Anaconda3\lib\site-packages\yaml\__init__.py", line 72, in load
    return loader.get_single_data()
  File "C:\Users\Toly_Novik\Anaconda3\lib\site-packages\yaml\constructor.py", line 37, in get_single_data
    return self.construct_document(node)
  File "C:\Users\Toly_Novik\Anaconda3\lib\site-packages\yaml\constructor.py", line 46, in construct_document
    for dummy in generator:
  File "C:\Users\Toly_Novik\Anaconda3\lib\site-packages\yaml\constructor.py", line 398, in construct_yaml_map
    value = self.construct_mapping(node)
  File "C:\Users\Toly_Novik\Anaconda3\lib\site-packages\yaml\constructor.py", line 204, in construct_mapping
    return super().construct_mapping(node, deep=deep)
  File "C:\Users\Toly_Novik\Anaconda3\lib\site-packages\yaml\constructor.py", line 125, in construct_mapping
    key = self.construct_object(key_node, deep=deep)
  File "C:\Users\Toly_Novik\Anaconda3\lib\site-packages\yaml\constructor.py", line 86, in construct_object
    data = constructor(self, node)
  File "C:\Users\Toly_Novik\Anaconda3\lib\site-packages\yaml\constructor.py", line 414, in construct_undefined
    node.start_mark)
yaml.constructor.ConstructorError: could not determine a constructor for the tag 'tag:yaml.org,2002:python/unicode'
  in "C:\Users\Toly_Novik\AppData\Local\ContinuumIO\binstar\config.yaml", line 1, column 1
```

##### `conda list --show-channel-urls`

```

```

**Comment by tolyla25** [comment]
Thank you!

A few comments:

trying conda update navigator-updater produced:

conda update navigator-updater

PackageNotInstalledError: Package is not installed in prefix.
  prefix: C:\Users\Toly_Novik\Anaconda2
  package name: navigator-updater


When tried this, I got the following:
conda install anaconda-client=1.6.14

conda install anaconda-client=1.6.14
Using Anaconda Cloud api site https://api.anaconda.org
Fetching package metadata: ......
Solving package specifications: .
Error:  Package missing in current win-64 channels:
  - anaconda-client 1.6.14*

Did you mean one of these?

    anaconda-client, anaconda-clean

You can search for this package on anaconda.org with

    anaconda search -t conda anaconda-client 1.6.14*

Could you help, please?

 

    On Sunday, April 29, 2018, 5:22:20 PM PDT, Gonzalo Peña-Castellanos <notifications@github.com> wrote:  
 
 
Closing as duplicate of #8420

Please remember to update to the latest version of Navigator to include
the latest fixes.

Open a terminal (on Linux or Mac) or the Anaconda Command Prompt (on windows)
and type:
conda update conda
conda update anaconda-navigator
conda update navigator-updater

See issue #8420 for more information on how to fix this issue.

Or run
conda install anaconda-client=1.6.14

**Comment by tolyla25** [comment]
Still have the error:


Main Error
 could not determine a constructor for the tag 'tag:yaml.org,2002:python/unicode'
  in "C:\Users\Toly_Novik\AppData\Local\ContinuumIO\binstar\config.yaml", line 1, column 1 
Traceback
 Traceback (most recent call last):
  File "C:\Users\Toly_Novik\Anaconda3\lib\site-packages\anaconda_navigator\exceptions.py", line 75, in exception_handler
    return_value = func(*args, **kwargs)
  File "C:\Users\Toly_Novik\Anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 120, in start_app
    window = run_app(splash)
  File "C:\Users\Toly_Novik\Anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 63, in run_app
    window = MainWindow(splash=splash)
  File "C:\Users\Toly_Novik\Anaconda3\lib\site-packages\anaconda_navigator\widgets\main_window.py", line 163, in __init__
    self.api = AnacondaAPI()
  File "C:\Users\Toly_Novik\Anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 2004, in AnacondaAPI
    ANACONDA_API = _AnacondaAPI()
  File "C:\Users\Toly_Novik\Anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 89, in __init__
    self._client_api = ClientAPI()
  File "C:\Users\Toly_Novik\Anaconda3\lib\site-packages\anaconda_navigator\api\client_api.py", line 612, in ClientAPI
    CLIENT_API = _ClientAPI()
  File "C:\Users\Toly_Novik\Anaconda3\lib\site-packages\anaconda_navigator\api\client_api.py", line 82, in __init__
    log_level=logging.NOTSET
  File "C:\Users\Toly_Novik\Anaconda3\lib\site-packages\binstar_client\utils\config.py", line 96, in get_server_api
    config = get_config(remote_site=site)
  File "C:\Users\Toly_Novik\Anaconda3\lib\site-packages\binstar_client\utils\config.py", line 229, in get_config
    file_configs = load_file_configs(SEARCH_PATH)
  File "C:\Users\Toly_Novik\Anaconda3\lib\site-packages\binstar_client\utils\config.py", line 223, in load_file_configs
    raw_data = collections.OrderedDict(kv for kv in itertools.chain.from_iterable(load_paths))
  File "C:\Users\Toly_Novik\Anaconda3\lib\site-packages\binstar_client\utils\config.py", line 223, in 
    raw_data = collections.OrderedDict(kv for kv in itertools.chain.from_iterable(load_paths))
  File "C:\Users\Toly_Novik\Anaconda3\lib\site-packages\binstar_client\utils\config.py", line 203, in _dir_yaml_loader
    yield filepath, load_config(filepath)
  File "C:\Users\Toly_Novik\Anaconda3\lib\site-packages\binstar_client\utils\config.py", line 187, in load_config
    data = yaml_load(fd)
  File "C:\Users\Toly_Novik\Anaconda3\lib\site-packages\binstar_client\utils\yaml.py", line 9, in yaml_load
    return safe_load(stream)
  File "C:\Users\Toly_Novik\Anaconda3\lib\site-packages\yaml\__init__.py", line 94, in safe_load
    return load(stream, SafeLoader)
  File "C:\Users\Toly_Novik\Anaconda3\lib\site-packages\yaml\__init__.py", line 72, in load
    return loader.get_single_data()
  File "C:\Users\Toly_Novik\Anaconda3\lib\site-packages\yaml\constructor.py", line 37, in get_single_data
    return self.construct_document(node)
  File "C:\Users\Toly_Novik\Anaconda3\lib\site-packages\yaml\constructor.py", line 46, in construct_document
    for dummy in generator:
  File "C:\Users\Toly_Novik\Anaconda3\lib\site-packages\yaml\constructor.py", line 398, in construct_yaml_map
    value = self.construct_mapping(node)
  File "C:\Users\Toly_Novik\Anaconda3\lib\site-packages\yaml\constructor.py", line 204, in construct_mapping
    return super().construct_mapping(node, deep=deep)
  File "C:\Users\Toly_Novik\Anaconda3\lib\site-packages\yaml\constructor.py", line 125, in construct_mapping
    key = self.construct_object(key_node, deep=deep)
  File "C:\Users\Toly_Novik\Anaconda3\lib\site-packages\yaml\constructor.py", line 86, in construct_object
    data = constructor(self, node)
  File "C:\Users\Toly_Novik\Anaconda3\lib\site-packages\yaml\constructor.py", line 414, in construct_undefined
    node.start_mark)
yaml.constructor.ConstructorError: could not determine a constructor for the tag 'tag:yaml.org,2002:python/unicode'
  in "C:\Users\Toly_Novik\AppData\Local\ContinuumIO\binstar\config.yaml", line 1, column 1

 

    On Sunday, April 29, 2018, 5:22:20 PM PDT, Gonzalo Peña-Castellanos <notifications@github.com> wrote:  
 
 
Closing as duplicate of #8420

Please remember to update to the latest version of Navigator to include
the latest fixes.

Open a terminal (on Linux or Mac) or the Anaconda Command Prompt (on windows)
and type:
conda update conda
conda update anaconda-navigator
conda update navigator-updater

See issue #8420 for more information on how to fix this issue.

Or run
conda install anaconda-client=1.6.14

**Comment by goanpeca** [comment]
Please run

```
conda install navigator-updater
conda install anaconda-client=1.6.14
```

Then run

```
conda update conda
```

And then

```
conda update --all
```

**Comment by tolyla25** [comment]
while running client install I got this:

  Returning 0.
extern "Python": function Cryptography_locking_cb() called, but got internal exception (out of memory / shutdown issue).  Returning 0.
extern "Python": function Cryptography_locking_cb() called, but got internal exception (out of memory / shutdown issue).  Returning 0.
 

    On Sunday, April 29, 2018, 8:15:01 PM PDT, Gonzalo Peña-Castellanos <notifications@github.com> wrote:  
 
 
Please run
conda install navigator-updater
conda install anaconda-client=1.6.14

Then run
conda update conda

And then
conda update --all

**Comment by tolyla25** [comment]
the same message when running conda install navigator-updater
 

    On Monday, April 30, 2018, 7:15:02 AM PDT, Toly Novik <tolynovik@yahoo.com> wrote:  
 
 while running client install I got this:

  Returning 0.
extern "Python": function Cryptography_locking_cb() called, but got internal exception (out of memory / shutdown issue).  Returning 0.
extern "Python": function Cryptography_locking_cb() called, but got internal exception (out of memory / shutdown issue).  Returning 0.
 

    On Sunday, April 29, 2018, 8:15:01 PM PDT, Gonzalo Peña-Castellanos <notifications@github.com> wrote:  
 
 
Please run
conda install navigator-updater
conda install anaconda-client=1.6.14

Then run
conda update conda

And then
conda update --all

**Comment by tolyla25** [comment]
It is working!! thanks a million!

A few comments

1. update all - installed cryptography 2.2.2 So I did not run your command to upgrade to 1.7

2. if cryptography update is required in must be run the last since it requires a newer ipykernel that is taken care of by update all

3. Antivirus software must be disabled

4. must clean up thoroughly older Anaconda installations

5. Why would update all command not enough for everything (except for an updater)?

6. Naming consistency (conda/anaconda) would be nice
 

    On Sunday, April 29, 2018, 8:15:01 PM PDT, Gonzalo Peña-Castellanos <notifications@github.com> wrote:  
 
 
Please run
conda install navigator-updater
conda install anaconda-client=1.6.14

Then run
conda update conda

And then
conda update --all
