### ISSUE TITLE
Caffe installation issues 

### ISSUE THREAD

**Issue by hani1814** [ContinuumIO/anaconda-issues#9273]
Hi,

I have created a python 3.5 environment and installed caffe. There seems to be an issue with libprotobuf library. 

conda create -n test python=3.5 caffe

I get the following error on import

Traceback (most recent call last):<br>&nbsp; File "&lt;stdin&gt;", line 1, in &lt;module&gt;<br>&nbsp; File "/opt/app/anaconda3/envs/test/lib/python3.5/site-packages/caffe/__init__.py", line 1, in &lt;module&gt;<br>&nbsp; &nbsp; from .pycaffe import Net, SGDSolver, NesterovSolver, AdaGradSolver, RMSPropSolver, AdaDeltaSolver, AdamSolver, NCCL, Timer<br>&nbsp; File "/opt/app/anaconda3/envs/test/lib/python3.5/site-packages/caffe/pycaffe.py", line 13, in &lt;module&gt;<br>&nbsp; &nbsp; from ._caffe import Net, SGDSolver, NesterovSolver, AdaGradSolver, \<br>ImportError: /opt/app/anaconda3/envs/test/lib/python3.5/site-packages/caffe/../../../libcaffe.so.1.0.0: undefined symbol: _ZN6google4base21CheckOpMessageBuilder9NewStringB5cxx11Ev

**Comment by jjhelmus** [comment]
Can you provide the output of `conda list --show-channel-urls` and `conda info` as requested by the issue template?  Without this information it is very difficult to debug this issue.

**Comment by hani1814** [comment]
As requested, I masked the home directory. We have a local repo based on anaconda repo


     active environment : test
    active env location : /opt/app/anaconda3/envs/test
            shell level : 1
       user config file : /home/XX/.condarc
 populated config files : /home/XX/.condarc
          conda version : 4.5.0
    conda-build version : 3.8.0
         python version : 3.5.4.final.0
       base environment : /opt/app/anaconda3  (writable)
           channel URLs : file://opt/condarepo/linux-64
                          file://opt/condarepo/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/linux-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/linux-64
                          https://repo.anaconda.com/pkgs/pro/noarch
          package cache : /opt/app/anaconda3/pkgs
                          /home/XX/.conda/pkgs
       envs directories : /opt/app/anaconda3/envs
                          /home/XX/.conda/envs
               platform : linux-64
             user-agent : conda/4.5.0 requests/2.14.2 CPython/3.5.4 Linux/2.6.32-431.17.1.el6.x86_64 rhel/6.5 glibc/2.12
                UID:GID : XX
             netrc file : None
           offline mode : False


# Name                    Version                   Build  Channel
bokeh                     0.12.4                   py35_0    file://opt/condarepo
boost                     1.65.1           py35heb9229b_3    file://opt/condarepo
bzip2                     1.0.6                h6d464ef_2    file://opt/condarepo
ca-certificates           2017.08.26           h1d4fec5_0    file://opt/condarepo
caffe                     1.0              py35h69a20d1_2    file://opt/condarepo
cairo                     1.14.12              h77bcde2_0    file://opt/condarepo
certifi                   2018.1.18                py35_0    file://opt/condarepo
click                     6.7                      py35_0    file://opt/condarepo
cloudpickle               0.5.2            py35hbe86bc5_0    file://opt/condarepo
cycler                    0.10.0                   py35_0    file://opt/condarepo
dask                      0.16.0           py35hcb8ecc8_0    file://opt/condarepo
dask-core                 0.16.0           py35hfc66869_0    file://opt/condarepo
dbus                      1.10.22              h3b5a359_0    file://opt/condarepo
decorator                 4.1.2                    py35_0    file://opt/condarepo
distributed               1.20.0           py35h5ba6bfe_0    file://opt/condarepo
expat                     2.2.5                he0dffb1_0    file://opt/condarepo
ffmpeg                    3.4                  h7264315_0    file://opt/condarepo
fontconfig                2.12.4               h88586e7_1    file://opt/condarepo
freetype                  2.8                  hab7d2ae_1    file://opt/condarepo
gflags                    2.2.1                hf484d3e_0    file://opt/condarepo
glib                      2.53.6               h5d9569c_2    file://opt/condarepo
glog                      0.3.5                         0    file://opt/condarepo
graphite2                 1.3.10               hc526e54_0    file://opt/condarepo
gst-plugins-base          1.12.2               he3457e5_0    file://opt/condarepo
gstreamer                 1.12.2               h4f93127_0    file://opt/condarepo
h5py                      2.7.1            py35ha1a889d_0    file://opt/condarepo
harfbuzz                  1.7.4                hc5b324e_0    file://opt/condarepo
hdf5                      1.8.18               h6792536_1    file://opt/condarepo
heapdict                  1.0.0                    py35_1    file://opt/condarepo
icu                       58.2                 h211956c_0    file://opt/condarepo
imageio                   2.2.0            py35hd0a6de2_0    file://opt/condarepo
intel-openmp              2018.0.0             hc7b2577_8    file://opt/condarepo
ipython                   6.2.1            py35hd850d2a_1    file://opt/condarepo
ipython_genutils          0.2.0                    py35_0    file://opt/condarepo
jasper                    1.900.1              hd497a04_4    file://opt/condarepo
jedi                      0.11.1                   py35_0    file://opt/condarepo
jinja2                    2.8.1                    py35_0    file://opt/condarepo
jpeg                      9b                   h024ee3a_2    file://opt/condarepo
leveldb                   1.20                 hf484d3e_1    file://opt/condarepo
libboost                  1.65.1               h4055789_3    file://opt/condarepo
libedit                   3.1                  heed3624_0    file://opt/condarepo
libffi                    3.2.1                hd88cf55_4    file://opt/condarepo
libgcc-ng                 7.2.0                h7cc24e2_2    file://opt/condarepo
libgfortran-ng            7.2.0                h9f7466a_2    file://opt/condarepo
libopus                   1.2.1                hb9ed12e_0    file://opt/condarepo
libpng                    1.6.34               hb9fc6fc_0    file://opt/condarepo
libprotobuf               3.4.1                h5b8497f_0    file://opt/condarepo
libstdcxx-ng              7.2.0                h7a57d05_2    file://opt/condarepo
libtiff                   4.0.9                h28f6b97_0    file://opt/condarepo
libvpx                    1.6.1                h888fd40_0    file://opt/condarepo
libxcb                    1.12                 h84ff03f_3    file://opt/condarepo
libxml2                   2.9.7                h26e45fe_0    file://opt/condarepo
lmdb                      0.9.22               hf484d3e_1    file://opt/condarepo
locket                    0.2.0                    py35_1    file://opt/condarepo
markupsafe                1.0                      py35_0    file://opt/condarepo
matplotlib                2.1.2            py35h0e671d2_0    file://opt/condarepo
mkl                       2018.0.2                      1    file://opt/condarepo
msgpack-python            0.4.8            py35h783f4c8_0    file://opt/condarepo
ncurses                   6.0                  h9df7e31_2    file://opt/condarepo
networkx                  2.1                      py35_0    file://opt/condarepo
numpy                     1.14.0           py35h3dfced4_1    file://opt/condarepo
olefile                   0.44             py35h2c86149_0    file://opt/condarepo
opencv                    3.3.1            py35h9bb06ff_1    file://opt/condarepo
openssl                   1.0.2n               hb7f436b_0    file://opt/condarepo
pandas                    0.22.0           py35hf484d3e_0    file://opt/condarepo
parso                     0.1.1            py35h1b200a3_0    file://opt/condarepo
partd                     0.3.8            py35h68187f2_0    file://opt/condarepo
path.py                   10.5             py35h39c98c1_0    file://opt/condarepo
pcre                      8.41                 hc27e229_1    file://opt/condarepo
pexpect                   4.3.1                    py35_0    file://opt/condarepo
pickleshare               0.7.4                    py35_0    file://opt/condarepo
pillow                    5.0.0            py35h3deb7b8_0    file://opt/condarepo
pip                       9.0.1            py35h7e7da9d_4    file://opt/condarepo
pixman                    0.34.0               hceecf20_3    file://opt/condarepo
prompt_toolkit            1.0.15           py35hc09de7a_0    file://opt/condarepo
protobuf                  3.4.1            py35he6b9134_0    file://opt/condarepo
psutil                    5.4.3            py35h14c3975_0    file://opt/condarepo
ptyprocess                0.5.2                    py35_0    file://opt/condarepo
py-boost                  1.65.1           py35hdf000e1_3    file://opt/condarepo
pygments                  2.2.0                    py35_0    file://opt/condarepo
pyparsing                 2.2.0                    py35_0    file://opt/condarepo
pyqt                      5.6.0            py35h0e41ada_5    file://opt/condarepo
python                    3.5.4               h56e0582_23    file://opt/condarepo
python-dateutil           2.6.1                    py35_0    file://opt/condarepo
python-gflags             3.1.2                    py35_0    file://opt/condarepo
python-leveldb            0.194                    py35_0    file://opt/condarepo
pytz                      2017.3           py35hb13c558_0    file://opt/condarepo
pywavelets                0.5.2            py35h53ec731_0    file://opt/condarepo
pyyaml                    3.12             py35h46ef4ae_1    file://opt/condarepo
qt                        5.6.2               h974d657_12    file://opt/condarepo
readline                  7.0                  ha6073c6_4    file://opt/condarepo
requests                  2.14.2                   py35_0    file://opt/condarepo
scikit-image              0.13.1           py35h14c3975_1    file://opt/condarepo
scipy                     1.0.0            py35hcbbe4a2_0    file://opt/condarepo
setuptools                36.5.0           py35ha8c1747_0    file://opt/condarepo
simplegeneric             0.8.1                    py35_1    file://opt/condarepo
sip                       4.18.1           py35h9eaea60_2    file://opt/condarepo
six                       1.11.0           py35h423b573_1    file://opt/condarepo
snappy                    1.1.7                h493ac5f_1    file://opt/condarepo
sortedcontainers          1.5.9                    py35_0    file://opt/condarepo
sqlite                    3.22.0               h1bed415_0    file://opt/condarepo
tblib                     1.3.2            py35hf1eb0b4_0    file://opt/condarepo
tk                        8.6.7                hc745277_3    file://opt/condarepo
toolz                     0.9.0                    py35_0    file://opt/condarepo
tornado                   4.5.3                    py35_0    file://opt/condarepo
traitlets                 4.3.2            py35ha522a97_0    file://opt/condarepo
wcwidth                   0.1.7            py35hcd08066_0    file://opt/condarepo
wheel                     0.30.0           py35hd3883cf_1    file://opt/condarepo
xz                        5.2.3                h55aa19d_2    file://opt/condarepo
yaml                      0.1.6                         0    file://opt/condarepo
zict                      0.1.3            py35h29275ca_0    file://opt/condarepo
zlib                      1.2.11               hfbfcf68_1    file://opt/condarepo

**Comment by jjhelmus** [comment]
Can you update your version of glog?  The package with the build string of `hf484d3e_1` has the necessary symbols.  Normally `conda install glog` would perform the necessary update to the environment but it looks like you may be storing a local copy of the repository.

**Comment by hani1814** [comment]
This has solved the problem. Thank you
