### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by gitmoneyMSBA** [ContinuumIO/anaconda-issues#9275]
## Main error
Application <b>jupyterlab</b> launch may have produced errors.
## Traceback
```
[E 10:34:49.240 LabApp] Exception while loading config file /Users/Fleder/.jupyter/jupyter_notebook_config.py
    Traceback (most recent call last):
      File "/anaconda/lib/python2.7/site-packages/traitlets/config/application.py", line 562, in _load_config_files
        config = loader.load_config()
      File "/anaconda/lib/python2.7/site-packages/traitlets/config/loader.py", line 457, in load_config
        self._read_file_as_dict()
      File "/anaconda/lib/python2.7/site-packages/traitlets/config/loader.py", line 489, in _read_file_as_dict
        py3compat.execfile(conf_filename, namespace)
      File "/anaconda/lib/python2.7/site-packages/ipython_genutils/py3compat.py", line 290, in execfile
        builtin_mod.execfile(filename, *where)
      File "/Users/.jupyter/jupyter_notebook_config.py", line 204
    SyntaxError: Non-ASCII character '\xe2' in file /Users/.jupyter/jupyter_notebook_config.py on line 204, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
[I 10:34:49.926 LabApp] The port 8888 is already in use, trying another port.
[W 10:34:49.937 LabApp] JupyterLab server extension not enabled, manually loading...
[I 10:34:49.945 LabApp] JupyterLab beta preview extension loaded from /anaconda/lib/python2.7/site-packages/jupyterlab
[I 10:34:49.946 LabApp] JupyterLab application directory is /anaconda/share/jupyter/lab
[I 10:34:49.955 LabApp] Serving notebooks from local directory: /Users
[I 10:34:49.955 LabApp] 0 active kernels 
[I 10:34:49.955 LabApp] The Jupyter Notebook is running at: http://localhost:8889/?token=4f4f51975ac3984b16895897362b7ef6105447867c99be79
[I 10:34:49.955 LabApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 10:34:49.957 LabApp] 
    
    Copy/paste this URL into your browser when you connect for the first time,
    to login with a token:
        http://localhost:8889/?token=4f4f51975ac3984b16895897362b7ef6105447867c99be79
osascript: OpenScripting.framework - scripting addition "/Library/ScriptingAdditions/Adobe Unit Types.osax" cannot be used with the current OS because it has no OSAXHandlers entry in its Info.plist.
[I 10:34:50.181 LabApp] Accepting one-time-token-authenticated connection from ::1
[W 10:34:51.280 LabApp] Could not determine jupyterlab build status without nodejs
[I 10:34:54.671 LabApp] Kernel started: 88a920ca-5191-4dff-8c90-005bd8b05ee4

```
## System information
```
platform: osx-64
version: 1.6.2
conda: 4.4.11
qt: 5.6.2
language: en
python: 2.7.13
os: Darwin;15.6.0;Darwin Kernel Version 15.6.0: Sun Jun  4 21:43:07 PDT 2017; root:xnu-3248.70.3~1/RELEASE_X86_64;x86_64;i386
pyqt: 5.6.0
```

**Comment by goanpeca** [comment]
@gitmoneyMSBA, the error
```
  File "/Users/.jupyter/jupyter_notebook_config.py", line 204
    SyntaxError: Non-ASCII character '\xe2' in file /Users/.jupyter/jupyter_notebook_config.py on line 204, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details

```

Indicates that `Non-ASCII character` is being used. Please fix that on `/Users/.jupyter/jupyter_notebook_config.py`
