### ISSUE TITLE
Jupyter is crashing

### ISSUE THREAD

**Issue by NeilPrograms** [ContinuumIO/anaconda-issues#929]
Error message:
`Traceback (most recent call last):
  File "/Users/neil/anaconda/bin/jupyter-notebook", line 6, in <module>
    sys.exit(notebook.notebookapp.main())
  File "/Users/neil/anaconda/lib/python3.5/site-packages/jupyter_core/application.py", line 267, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/Users/neil/anaconda/lib/python3.5/site-packages/traitlets/config/application.py", line 595, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-7>", line 2, in initialize
  File "/Users/neil/anaconda/lib/python3.5/site-packages/traitlets/config/application.py", line 74, in catch_config_error
    return method(app, *args, **kwargs)
  File "/Users/neil/anaconda/lib/python3.5/site-packages/notebook/notebookapp.py", line 1069, in initialize
    self.init_configurables()
  File "/Users/neil/anaconda/lib/python3.5/site-packages/notebook/notebookapp.py", line 837, in init_configurables
    parent=self,
  File "/Users/neil/anaconda/lib/python3.5/site-packages/nb_conda_kernels/manager.py", line 19, in __init__
    specs = self.find_kernel_specs() or {}
  File "/Users/neil/anaconda/lib/python3.5/site-packages/nb_conda_kernels/manager.py", line 129, in find_kernel_specs
    self.conda_info = self._conda_info()
  File "/Users/neil/anaconda/lib/python3.5/site-packages/nb_conda_kernels/manager.py", line 29, in _conda_info
    p = subprocess.check_output(["conda", "info", "--json"]
  File "/Users/neil/anaconda/lib/python3.5/subprocess.py", line 626, in check_output
    **kwargs).stdout
  File "/Users/neil/anaconda/lib/python3.5/subprocess.py", line 693, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/Users/neil/anaconda/lib/python3.5/subprocess.py", line 947, in __init__
    restore_signals, start_new_session)
  File "/Users/neil/anaconda/lib/python3.5/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg)
FileNotFoundError: [Errno 2] No such file or directory: 'conda'
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.`

**Comment by bollwyvl** [comment]
@NeilPrograms We've released versions of `nb_conda`, `nb_conda_kernels` and `nb_anacondacloud` through the official Anaconda conda repos that should resolve the issues you are seeing! sorry for the delay!

```shell
conda update nb_conda nb_conda_kernels nb_anacondacloud
```

As-installed kernel names that are eligible for being `default` (e.g. `python2`, `python3`, `ir`, etc.) will be maintained unmodified, so they should always appear there.

The downside is as many as three options for the current env, i.e. if you are in root, you will see _Python 2_ and _Python [root]_ and _Python [default]_, you can now reproducibly capture which environment your kernel should run against.

meta: https://github.com/Anaconda-Platform/anaconda-nb-extensions/issues/166

**Comment by mehdipira** [comment]
Hi,
I'm having the same problem. I just downloaded Anaconda and related packages like gdal and rasterio when I run my code in Jupyter or Iphython it crashes and kernel dies. any ideas or thoughts?
Thank you.

**Comment by mehdipira** [comment]
Hi @bollwyvl 
 I'm having the same problem. I just downloaded Anaconda and related packages like gdal and rasterio when I run my code in Jupyter or Iphython it crashes and kernel dies. any ideas or thoughts?
 Thank you.

**Comment by mayoore** [comment]
I just install Anaconda 4.3.0 (python version 3.6 64 bit). Jupyter is crashing without opening kernel.
