### ISSUE TITLE
Updating ipykernel to 4.8.2 fails => cannot import name \'constants\'\r\n'

### ISSUE THREAD

**Issue by TacoVerhagen** [ContinuumIO/anaconda-issues#9291]
### Actual Behavior
This issue sounds like #8733, but it has a different dynamics. See also the history section.
Run conda update ipykernel

Linking error, see below. To get extra output I modified the ipykernel-post-link.bat to remove the > NUL in the 4.8.2 package. That explains the hash warning.

...
(base) C:\WINDOWS\system32>conda update -v  ipykernel
Solving environment: ...working... done

## Package Plan ##

  environment location: C:\ProgramData\Anaconda3

  added / updated specs:
    - ipykernel

The following packages will be UPDATED:

    ipykernel: 4.8.0-py36_0 --> 4.8.2-py36_0

Proceed ([y]/n)? y

Preparing transaction: ...working... done
Verifying transaction: ...working... conda.CondaMultiError: The package for ipykernel located at C:\ProgramData\Anaconda3\pkgs\ipykernel-4.8.2-py36_0
appears to be corrupted. The path 'Scripts/.ipykernel-post-link.bat'
has a sha256 mismatch.
  reported sha256: 107afea0489497f63e691f97318144d14b0d2e3e97f2fa6e384313987ae4d2d3
  actual sha256: 184a0dfb7de028b3c37a0f69f33ba7b3c512fa01b6c1901c916f9e57f15614a9

(SafetyError: The package for ipykernel located at C:\ProgramData\Anaconda3\pkgs\ipykernel-4.8.2-py36_0
appears to be corrupted. The path 'Scripts/.ipykernel-post-link.bat'
has a sha256 mismatch.
  reported sha256: 107afea0489497f63e691f97318144d14b0d2e3e97f2fa6e384313987ae4d2d3
  actual sha256: 184a0dfb7de028b3c37a0f69f33ba7b3c512fa01b6c1901c916f9e57f15614a9
,)

done
Executing transaction: ...working... ===> UNLINKING PACKAGE: defaults::ipykernel-4.8.0-py36_0 <===
  prefix=C:\ProgramData\Anaconda3

===> LINKING PACKAGE: defaults::ipykernel-4.8.2-py36_0 <===
  prefix=C:\ProgramData\Anaconda3
  source=C:\ProgramData\Anaconda3\pkgs\ipykernel-4.8.2-py36_0

$ C:\WINDOWS\system32\cmd.exe /d /c C:\ProgramData\Anaconda3\Scripts\.ipykernel-post-link.bat
==> cwd: C:\ProgramData\Anaconda3\Scripts <==
==> exit code: 1 <==
==> stdout <==
b'Traceback (most recent call last):\r\n  File "C:\\ProgramData\\Anaconda3\\lib\\runpy.py", line 183, in _run_module_as_main\r\n    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)\r\n  File "C:\\ProgramData\\Anaconda3\\lib\\runpy.py", line 142, in _get_module_details\r\n    return _get_module_details(pkg_main_name, error)\r\n  File "C:\\ProgramData\\Anaconda3\\lib\\runpy.py", line 109, in _get_module_details\r\n    __import__(pkg_name)\r\n  File "C:\\Users\\Taco\\AppData\\Roaming\\Python\\Python36\\site-packages\\ipykernel\\__init__.py", line 2, in <module>\r\n    from .connect import *\r\n  File "C:\\Users\\Taco\\AppData\\Roaming\\Python\\Python36\\site-packages\\ipykernel\\connect.py", line 18, in <module>\r\n    import jupyter_client\r\n  File "C:\\Users\\Taco\\AppData\\Roaming\\Python\\Python36\\site-packages\\jupyter_client\\__init__.py", line 4, in <module>\r\n    from .connect import *\r\n  File "C:\\Users\\Taco\\AppData\\Roaming\\Python\\Python36\\site-packages\\jupyter_client\\connect.py", line 23, in <module>\r\n    import zmq\r\n  File "C:\\Users\\Taco\\AppData\\Roaming\\Python\\Python36\\site-packages\\zmq\\__init__.py", line 47, in <module>\r\n    from zmq import backend\r\n  File "C:\\Users\\Taco\\AppData\\Roaming\\Python\\Python36\\site-packages\\zmq\\backend\\__init__.py", line 40, in <module>\r\n    reraise(*exc_info)\r\n  File "C:\\Users\\Taco\\AppData\\Roaming\\Python\\Python36\\site-packages\\zmq\\utils\\sixcerpt.py", line 34, in reraise\r\n    raise value\r\n  File "C:\\Users\\Taco\\AppData\\Roaming\\Python\\Python36\\site-packages\\zmq\\backend\\__init__.py", line 27, in <module>\r\n    _ns = select_backend(first)\r\n  File "C:\\Users\\Taco\\AppData\\Roaming\\Python\\Python36\\site-packages\\zmq\\backend\\select.py", line 26, in select_backend\r\n    mod = __import__(name, fromlist=public_api)\r\n  File "C:\\Users\\Taco\\AppData\\Roaming\\Python\\Python36\\site-packages\\zmq\\backend\\cython\\__init__.py", line 6, in <module>\r\n    from . import (constants, error, message, context,\r\nImportError: cannot import name \'constants\'\r\n'
==> stderr <==
b''

===> REVERSING PACKAGE LINK: defaults::ipykernel-4.8.2-py36_0 <===
  prefix=C:\ProgramData\Anaconda3

failed
An error occurred while installing package 'defaults::ipykernel-4.8.2-py36_0'.
LinkError: post-link script failed for package defaults::ipykernel-4.8.2-py36_0
running your command again with `-v` will provide additional information
location of failed script: C:\ProgramData\Anaconda3\Scripts\.ipykernel-post-link.bat
==> script messages <==
<None>

Attempting to roll back.

Rolling back transaction: ...working... ===> REVERSING PACKAGE UNLINK: defaults::ipykernel-4.8.0-py36_0 <===
  prefix=C:\ProgramData\Anaconda3

done
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\conda\core\link.py", line 794, in run_script
    subprocess_call(command_args, env=env, path=dirname(path))
  File "C:\ProgramData\Anaconda3\lib\site-packages\conda\gateways\subprocess.py", line 56, in subprocess_call
    output=_format_output(command_str, path, rc, stdout, stderr))
subprocess.CalledProcessError: Command '['C:\\WINDOWS\\system32\\cmd.exe', '/d', '/c', 'C:\\ProgramData\\Anaconda3\\Scripts\\.ipykernel-post-link.bat']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\conda\core\link.py", line 558, in _execute_actions
    run_script(target_prefix, prec, 'post-unlink' if is_unlink else 'post-link')
  File "C:\ProgramData\Anaconda3\lib\site-packages\conda\core\link.py", line 810, in run_script
    raise LinkError(message)
conda.exceptions.LinkError: post-link script failed for package defaults::ipykernel-4.8.2-py36_0
running your command again with `-v` will provide additional information
location of failed script: C:\ProgramData\Anaconda3\Scripts\.ipykernel-post-link.bat
==> script messages <==
<None>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\conda\core\link.py", line 493, in _execute
    cls._execute_actions(pkg_idx, axngroup)
  File "C:\ProgramData\Anaconda3\lib\site-packages\conda\core\link.py", line 574, in _execute_actions
    reverse_excs,
conda.CondaMultiError: post-link script failed for package defaults::ipykernel-4.8.2-py36_0
running your command again with `-v` will provide additional information
location of failed script: C:\ProgramData\Anaconda3\Scripts\.ipykernel-post-link.bat
==> script messages <==
<None>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\conda\exceptions.py", line 819, in __call__
    return func(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\conda\cli\main.py", line 78, in _main
    exit_code = do_call(args, p)
  File "C:\ProgramData\Anaconda3\lib\site-packages\conda\cli\conda_argparse.py", line 77, in do_call
    exit_code = getattr(module, func_name)(args, parser)
  File "C:\ProgramData\Anaconda3\lib\site-packages\conda\cli\main_update.py", line 14, in execute
    install(args, parser, 'update')
  File "C:\ProgramData\Anaconda3\lib\site-packages\conda\cli\install.py", line 253, in install
    handle_txn(unlink_link_transaction, prefix, args, newenv)
  File "C:\ProgramData\Anaconda3\lib\site-packages\conda\cli\install.py", line 282, in handle_txn
    unlink_link_transaction.execute()
  File "C:\ProgramData\Anaconda3\lib\site-packages\conda\core\link.py", line 229, in execute
    self._execute(tuple(concat(interleave(itervalues(self.prefix_action_groups)))))
  File "C:\ProgramData\Anaconda3\lib\site-packages\conda\core\link.py", line 521, in _execute
    rollback_excs,
conda.CondaMultiError: post-link script failed for package defaults::ipykernel-4.8.2-py36_0
running your command again with `-v` will provide additional information
location of failed script: C:\ProgramData\Anaconda3\Scripts\.ipykernel-post-link.bat
==> script messages <==
<None>
...

### Expected Behavior
Update succeeds.

### Steps to Reproduce
Run conda update ipykernel

### The history
From the start, installing Anaconda 5.1.0 succeeds but only the Anaconda prompt is shown in the start menu and running that fails on the fact that activate.bat is not present (really isn't)
Installing miniconda 5.1.0 succeeds, but conda install anaconda fails on

An error occurred while installing package 'defaults::ipykernel-4.8.0-py36_0'.
LinkError: post-link script failed for package defaults::ipykernel-4.8.0-py36_0
running your command again with `-v` will provide additional information
location of failed script: C:\ProgramData\Anaconda3\Scripts\.ipykernel-post-link.bat

conda update ipykernel  -> fails as ipykernel is not present (wait, what?)
conda install ipykernel => above link error
Previous 2 package versions, admin rights on/off, paths, etc => not working

In the end, installed this on another machine in the EXACT same location
Installed Anaconda 5.1.0 on target machine
Copied other over target => works!
conda update conda base => good
conda update conda => some error about 'block' should really be equivalent
  running again gives the all good message
conda update --all => link error
conda update ipykernel => link error
conda update sphinx => good

##### Anaconda or Miniconda version:
5.1.0

##### Operating System:
Windows 10, not yet received the big update from 30th March

##### `conda info`

```
(base) C:\WINDOWS\system32>conda info

     active environment : base
    active env location : C:\ProgramData\Anaconda3
            shell level : 1
       user config file : C:\Users\Taco\.condarc
 populated config files :
          conda version : 4.5.2
    conda-build version : 3.4.1
         python version : 3.6.4.final.0
       base environment : C:\ProgramData\Anaconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/win-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/win-64
                          https://repo.anaconda.com/pkgs/pro/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\ProgramData\Anaconda3\pkgs
                          C:\Users\Taco\AppData\Local\conda\conda\pkgs
       envs directories : C:\ProgramData\Anaconda3\envs
                          C:\Users\Taco\AppData\Local\conda\conda\envs
                          C:\Users\Taco\.conda\envs
               platform : win-64
             user-agent : conda/4.5.2 requests/2.18.4 CPython/3.6.4 Windows/10 Windows/10.0.16299
          administrator : True
             netrc file : None
           offline mode : False
```

##### `conda list --show-channel-urls`

```
(base) C:\WINDOWS\system32>conda list --show-channel-urls
# packages in environment at C:\ProgramData\Anaconda3:
#
# Name                    Version                   Build  Channel
_ipyw_jlab_nb_ext_conf    0.1.0            py36he6757f0_0    defaults
alabaster                 0.7.10           py36hcd07829_0    defaults
anaconda                  5.1.0                    py36_2    defaults
anaconda-client           1.6.9                    py36_0    defaults
anaconda-navigator        1.7.0                    py36_0    defaults
anaconda-project          0.8.2            py36hfad2e28_0    defaults
asn1crypto                0.24.0                   py36_0    defaults
asn1crypto                0.22.0                    <pip>
astroid                   1.6.1                    py36_0    defaults
astroid                   1.5.3                     <pip>
astropy                   2.0.2                     <pip>
astropy                   2.0.3            py36hfa6e2cd_0    defaults
attrs                     17.4.0                   py36_0    defaults
babel                     2.5.3                    py36_0    defaults
Babel                     2.5.0                     <pip>
backcall                  0.1.0                    py36_0    defaults
backports                 1.0              py36h81696a8_1    defaults
backports.shutil_get_terminal_size 1.0.0            py36h79ab834_2    defaults
beautifulsoup4            4.6.0            py36hd4cc5e8_1    defaults
bitarray                  0.8.1            py36hfa6e2cd_1    defaults
bkcharts                  0.2              py36h7e685f7_0    defaults
blaze                     0.11.3           py36h8a29ca5_0    defaults
bleach                    2.0.0                     <pip>
bleach                    2.1.2                    py36_0    defaults
bokeh                     0.12.13          py36h047fa9f_0    defaults
boto                      2.48.0           py36h1a776d2_1    defaults
bottleneck                1.2.1            py36hd119dfa_0    defaults
bzip2                     1.0.6            vc14hdec8e7a_1  [vc14]  defaults
ca-certificates           2018.03.07                    0    defaults
certifi                   2017.07.27.1              <pip>
certifi                   2018.4.16                py36_0    defaults
cffi                      1.10.0                    <pip>
cffi                      1.11.4           py36hfa6e2cd_0    defaults
chardet                   3.0.4            py36h420ce6e_1    defaults
click                     6.7              py36hec8c647_0    defaults
cloudpickle               0.4.0                     <pip>
cloudpickle               0.5.2                    py36_1    defaults
clyent                    1.2.2            py36hb10d595_1    defaults
colorama                  0.3.9            py36h029ae33_0    defaults
comtypes                  1.1.4                    py36_0    defaults
comtypes                  1.1.2                     <pip>
conda                     4.5.2                    py36_0    defaults
conda-build               3.4.1                    py36_0    defaults
conda-env                 2.6.0                h36134e3_1    defaults
conda-verify              2.0.0            py36h065de53_0    defaults
console_shortcut          0.1.1                haa4cab3_2    defaults
contextlib2               0.5.5            py36he5d52c0_0    defaults
cryptography              2.1.4            py36he1d7878_0    defaults
cryptography              2.0.3                     <pip>
curl                      7.58.0               h7602738_0    defaults
cycler                    0.10.0           py36h009560c_0    defaults
Cython                    0.26.1                    <pip>
cython                    0.27.3           py36h22f4c84_0    defaults
cytoolz                   0.9.0            py36hfa6e2cd_0    defaults
cytoolz                   0.8.2                     <pip>
dask                      0.16.1                   py36_0    defaults
dask                      0.15.2                    <pip>
dask-core                 0.16.1                   py36_0    defaults
datashape                 0.5.4            py36h5770b85_0    defaults
decorator                 4.2.1                    py36_0    defaults
decorator                 4.1.2                     <pip>
distlib                   0.2.5            py36h51371be_0    defaults
distributed               1.20.2                   py36_0    defaults
distributed               1.18.3                    <pip>
docutils                  0.14             py36h6012d8f_0    defaults
entrypoints               0.2.3            py36hfd66bb0_2    defaults
et_xmlfile                1.0.1            py36h3d2d736_0    defaults
fastcache                 1.0.2            py36hffdae1b_0    defaults
filelock                  2.0.12                    <pip>
filelock                  2.0.13           py36h20000bf_0    defaults
flask                     0.12.2           py36h98b5e8f_0    defaults
flask-cors                3.0.3            py36h8a3855d_0    defaults
freetype                  2.8              vc14h17c9bdf_0  [vc14]  defaults
get_terminal_size         1.0.0                h38e98db_0    defaults
gevent                    1.2.2            py36h342a76c_0    defaults
glob2                     0.5                       <pip>
glob2                     0.6              py36hdf76b57_0    defaults
greenlet                  0.4.12           py36ha00ad21_0    defaults
h5py                      2.7.0                     <pip>
h5py                      2.7.1            py36he54a1c3_0    defaults
hdf5                      1.10.1           vc14hb361328_0  [vc14]  defaults
heapdict                  1.0.0                    py36_2    defaults
html5lib                  0.999999999               <pip>
html5lib                  1.0.1            py36h047fa9f_0    defaults
icc_rt                    2017.0.4             h97af966_0    defaults
icu                       58.2             vc14hc45fdbb_0  [vc14]  defaults
idna                      2.6              py36h148d497_1    defaults
imageio                   2.2.0            py36had6c2d2_0    defaults
imagesize                 0.7.1            py36he29f638_0    defaults
intel-openmp              2018.0.0             hd92c6cd_8    defaults
ipykernel                 4.6.1                     <pip>
ipykernel                 4.8.0                    py36_0    defaults
ipython                   6.1.0                     <pip>
ipython                   6.3.1                    py36_0    defaults
ipython_genutils          0.2.0            py36h3c5d0ee_0    defaults
ipywidgets                7.1.1                    py36_0    defaults
isort                     4.2.15           py36h6198cc5_0    defaults
itsdangerous              0.24             py36hb6c5a24_1    defaults
jdcal                     1.3              py36h64a5255_0    defaults
jedi                      0.12.0                   py36_1    defaults
jedi                      0.10.2                    <pip>
jinja2                    2.9.6            py36h10aa3a0_1    defaults
jpeg                      9b               vc14h4d7706e_1  [vc14]  defaults
jsonschema                2.6.0            py36h7636477_0    defaults
jupyter                   1.0.0                    py36_4    defaults
jupyter-client            5.1.0                     <pip>
jupyter-core              4.3.0                     <pip>
jupyter_client            5.2.2                    py36_0    defaults
jupyter_console           5.2.0            py36h6d89b47_1    defaults
jupyter_core              4.4.0            py36h56e9d50_0    defaults
jupyterlab                0.31.4                   py36_0    defaults
jupyterlab_launcher       0.10.2                   py36_0    defaults
lazy-object-proxy         1.3.1            py36hd1c21d2_0    defaults
libcurl                   7.58.0               h7602738_0    defaults
libiconv                  1.15             vc14h29686d3_5  [vc14]  defaults
libpng                    1.6.34               h79bbb47_0    defaults
libssh2                   1.8.0            vc14hcf584a9_2  [vc14]  defaults
libtiff                   4.0.9                h0f13578_0    defaults
libxml2                   2.9.7                h79bbb47_0    defaults
libxslt                   1.1.32               hf6f1972_0    defaults
llvmlite                  0.20.0                    <pip>
llvmlite                  0.21.0           py36he0b0552_0    defaults
locket                    0.2.0            py36hfed976d_1    defaults
lockfile                  0.12.2           py36h0468280_0    defaults
lxml                      3.8.0                     <pip>
lxml                      4.1.1            py36hef2cd61_1    defaults
lzo                       2.10                 h6df0209_2    defaults
markupsafe                1.0              py36h0e26971_1    defaults
matplotlib                2.0.2                     <pip>
matplotlib                2.1.2            py36h016c42a_0    defaults
mccabe                    0.6.1            py36hb41005a_1    defaults
menuinst                  1.4.8            py36h870ab7d_0    defaults
mistune                   0.7.4                     <pip>
mistune                   0.8.3                    py36_0    defaults
mkl                       2018.0.1             h2108138_4    defaults
mkl-service               1.1.2            py36h57e144c_4    defaults
mpmath                    1.0.0            py36hacc8adf_2    defaults
mpmath                    0.19                      <pip>
msgpack-python            0.5.1            py36he980bc4_0    defaults
msgpack-python            0.4.8                     <pip>
multipledispatch          0.4.9            py36he44c36e_0    defaults
navigator-updater         0.1.0            py36h8a7b86b_0    defaults
nbconvert                 5.3.1            py36h8dc0fde_0    defaults
nbformat                  4.4.0            py36h3a5bc1b_0    defaults
networkx                  1.11                      <pip>
networkx                  2.1                      py36_0    defaults
nltk                      3.2.5            py36h76d52bb_0    defaults
nltk                      3.2.4                     <pip>
nose                      1.3.7            py36h1c3779e_2    defaults
notebook                  5.4.0                    py36_0    defaults
numba                     0.36.2          np114py36h12cb543_0    defaults
numba                     0.35.0+10.g143f70e           <pip>
numexpr                   2.6.2                     <pip>
numexpr                   2.6.4            py36h30784b8_0    defaults
numpy                     1.13.1                    <pip>
numpy                     1.14.0           py36h4a99626_1    defaults
numpydoc                  0.8.0                    py36_0    defaults
odo                       0.5.1            py36h7560279_0    defaults
olefile                   0.45.1                   py36_0    defaults
olefile                   0.44                      <pip>
openpyxl                  2.4.8            py36hf3b77f6_1    defaults
openpyxl                  2.4.10                    <pip>
openssl                   1.0.2o               h8ea7d77_0    defaults
packaging                 16.8             py36ha0986f6_1    defaults
pandas                    0.20.3                    <pip>
pandas                    0.22.0           py36h6538335_0    defaults
pandoc                    1.19.2.1             hb2460c7_1    defaults
pandocfilters             1.4.2            py36h3ef6317_1    defaults
parso                     0.1.1            py36hae3edee_0    defaults
partd                     0.3.8            py36hc8e763b_0    defaults
path.py                   10.3.1                    <pip>
path.py                   10.5             py36h2b94a8f_0    defaults
pathlib2                  2.3.0            py36h7bfb78b_0    defaults
patsy                     0.5.0                    py36_0    defaults
patsy                     0.4.1                     <pip>
pep8                      1.7.1                    py36_0    defaults
pep8                      1.7.0                     <pip>
pickleshare               0.7.4            py36h9de030f_0    defaults
Pillow                    4.2.1                     <pip>
pillow                    5.0.0            py36h0738816_0    defaults
pip                       9.0.1            py36h226ae91_4    defaults
pkginfo                   1.4.1            py36hb0f9cfa_1    defaults
pluggy                    0.6.0            py36hc7daf1e_0    defaults
ply                       3.10             py36h1211beb_0    defaults
progress                  1.3              py36hbeca8d3_0    defaults
prompt_toolkit            1.0.15           py36h60b8f86_0    defaults
psutil                    5.2.2                     <pip>
psutil                    5.4.3            py36hfa6e2cd_0    defaults
py                        1.4.34                    <pip>
py                        1.5.2            py36hbcfbabc_0    defaults
pycodestyle               2.3.1            py36h7cc55cd_0    defaults
pycosat                   0.6.2                     <pip>
pycosat                   0.6.3            py36h413d8a4_0    defaults
pycparser                 2.18             py36hd053e01_1    defaults
pycrypto                  2.6.1            py36hfa6e2cd_7    defaults
pycurl                    7.43.0.1         py36h74b6da3_0    defaults
pycurl                    7.43.0                    <pip>
pyflakes                  1.6.0            py36h0b975d6_0    defaults
pyflakes                  1.5.0                     <pip>
pygments                  2.2.0            py36hb010967_0    defaults
pylint                    1.8.2                    py36_0    defaults
pylint                    1.7.2                     <pip>
pyodbc                    4.0.22           py36h6538335_0    defaults
pyodbc                    4.0.17                    <pip>
pyOpenSSL                 17.2.0                    <pip>
pyopenssl                 17.5.0           py36h5b7d817_0    defaults
pyparsing                 2.2.0            py36h785a196_1    defaults
pyqt                      5.6.0            py36hb5ed885_5    defaults
pysocks                   1.6.7            py36h698d350_1    defaults
pytables                  3.4.2            py36h85b5e71_1    defaults
pytest                    3.3.2                    py36_0    defaults
pytest                    3.2.1                     <pip>
python                    3.6.4                h6538335_1    defaults
python-dateutil           2.6.1            py36h509ddcb_1    defaults
pytz                      2017.2                    <pip>
pytz                      2017.3           py36h1d3fa6b_0    defaults
pywavelets                0.5.2            py36hc649158_0    defaults
pywin32                   222              py36hfa6e2cd_0    defaults
pywin32                   221                       <pip>
pywinpty                  0.5              py36h6538335_1    defaults
pyyaml                    3.12             py36h1d1928f_1    defaults
pyzmq                     16.0.2                    <pip>
pyzmq                     16.0.3           py36he714bf5_0    defaults
qt                        5.6.2           vc14h6f8c307_12  [vc14]  defaults
qtawesome                 0.4.4            py36h5aa48f6_0    defaults
qtconsole                 4.3.1            py36h99a29a9_0    defaults
qtpy                      1.3.1            py36hb8717c5_0    defaults
requests                  2.18.4           py36h4371aae_1    defaults
rope                      0.10.5                    <pip>
rope                      0.10.7           py36had63a69_0    defaults
ruamel_yaml               0.15.35          py36hfa6e2cd_1    defaults
ruamel_yaml               0.11.14                   <pip>
scikit-image              0.13.1           py36hfa6e2cd_1    defaults
scikit-learn              0.19.1           py36h53aea1b_0    defaults
scikit-learn              0.19.0                    <pip>
scipy                     0.19.1                    <pip>
scipy                     1.0.0            py36h1260518_0    defaults
seaborn                   0.8                       <pip>
seaborn                   0.8.1            py36h9b69545_0    defaults
send2trash                1.4.2                    py36_0    defaults
setuptools                36.5.0.post20170921           <pip>
setuptools                38.4.0                   py36_0    defaults
simplegeneric             0.8.1                    py36_2    defaults
singledispatch            3.4.0.3          py36h17d0c80_0    defaults
sip                       4.18.1           py36h9c25514_2    defaults
six                       1.10.0                    <pip>
six                       1.11.0           py36h4db2310_1    defaults
snowballstemmer           1.2.1            py36h763602f_0    defaults
sortedcollections         0.5.3            py36hbefa0ab_0    defaults
sortedcontainers          1.5.7                     <pip>
sortedcontainers          1.5.9                    py36_0    defaults
sphinx                    1.7.4                    py36_0    defaults
sphinxcontrib             1.0              py36hbbac3d2_1    defaults
sphinxcontrib-websupport  1.0.1            py36hb5e5916_1    defaults
spyder                    3.2.6                    py36_0    defaults
SQLAlchemy                1.1.13                    <pip>
sqlalchemy                1.2.1            py36hfa6e2cd_0    defaults
sqlite                    3.22.0               h9d3ae62_0    defaults
statsmodels               0.8.0            py36h6189b4c_0    defaults
sympy                     1.1.1            py36h96708e0_0    defaults
tblib                     1.3.2            py36h30f5020_0    defaults
terminado                 0.8.1                    py36_1    defaults
testpath                  0.3.1            py36h2698cfe_0    defaults
tk                        8.6.7            vc14hb68737d_1  [vc14]  defaults
toolz                     0.9.0                    py36_0    defaults
toolz                     0.8.2                     <pip>
tornado                   4.5.2                     <pip>
tornado                   4.5.3                    py36_0    defaults
traitlets                 4.3.2            py36h096827d_0    defaults
typing                    3.6.2            py36hb035bda_0    defaults
unicodecsv                0.14.1           py36h6450c06_0    defaults
urllib3                   1.22             py36h276f60a_0    defaults
vc                        14                   h2379b0c_1    defaults
vs2015_runtime            14.0.25123           hd4c4e62_1    defaults
wcwidth                   0.1.7            py36h3d5aa90_0    defaults
webencodings              0.5.1            py36h67c50ae_1    defaults
werkzeug                  0.14.1                   py36_0    defaults
Werkzeug                  0.12.2                    <pip>
wheel                     0.30.0           py36h6c3ec14_1    defaults
wheel                     0.29.0                    <pip>
widgetsnbextension        3.1.0                    py36_0    defaults
win_inet_pton             1.0.1            py36he67d7fd_1    defaults
win_unicode_console       0.5              py36hcdbd4b5_0    defaults
wincertstore              0.2              py36h7fe50ca_0    defaults
winpty                    0.4.3                         4    defaults
wrapt                     1.10.11          py36he5f5981_0    defaults
xlrd                      1.1.0            py36h1cb58dc_1    defaults
xlsxwriter                1.0.2            py36hf723b7d_0    defaults
XlsxWriter                0.9.8                     <pip>
xlwings                   0.11.5                   py36_0    defaults
xlwings                   0.11.4                    <pip>
xlwt                      1.3.0            py36h1a4751e_0    defaults
yaml                      0.1.7            vc14hb31d195_1  [vc14]  defaults
zict                      0.1.3            py36h2d8e73e_0    defaults
zict                      0.1.2                     <pip>
zlib                      1.2.11           vc14h1cdd9ab_1  [vc14]  defaults
```

**Comment by TacoVerhagen** [comment]
I moved on, issue closed
