### ISSUE TITLE
Spyder fails to launch with navigator 1.8.4 on mac

### ISSUE THREAD

**Issue by acarrami** [ContinuumIO/anaconda-issues#9305]
### Actual Behavior

Spyder does not launch. I get an application launch error message. This goes for spyder 3.2.8, 3.2.7 or 3.2.6. The launch error message is: 
Traceback (most recent call last):
File "/anaconda3/bin/spyder", line 4, in 
import spyder.app.start
File "/anaconda3/lib/python3.6/site-packages/spyder/app/start.py", line 27, in 
from spyder.config.main import CONF
File "/anaconda3/lib/python3.6/site-packages/spyder/config/main.py", line 22, in 
from spyder.config.user import UserConfig
File "/anaconda3/lib/python3.6/site-packages/spyder/config/user.py", line 26, in 
from spyder.utils.programs import check_version
File "/anaconda3/lib/python3.6/site-packages/spyder/utils/programs.py", line 18, in 
import subprocess
File "/anaconda3/lib/python3.6/subprocess.py", line 136, in 
import _posixsubprocess
ImportError: dlopen(/anaconda3/lib/python3.6/lib-dynload/_posixsubprocess.cpython-36m-darwin.so, 2): Symbol not found: __Py_set_inheritable_async_safe
Referenced from: /anaconda3/lib/python3.6/lib-dynload/_posixsubprocess.cpython-36m-darwin.so
Expected in: flat namespace
in /anaconda3/lib/python3.6/lib-dynload/_posixsubprocess.cpython-36m-darwin.so

### Expected Behavior

Spyder should open, as it did before I updated anaconda navigator.

##### `conda info`

```

```

##### `conda list --show-channel-urls`

```

```

**Comment by ccordoba12** [comment]
Please open Terminal.app and run there

    coda update python python.app

to fix this problem.

**Comment by acarrami** [comment]
It worked. Thanks!

**Comment by acarrami** [comment]
Actually…. It didn’t. Spyder opens but hangs. Now jupyter doesn’t open, with a similar message. It’s all kind of messed up.

**Comment by acarrami** [comment]
I ran “conda update —all” and now everything seems to work fine.

**Comment by ccordoba12** [comment]
Ok, good to know.

**Comment by NeelkanthMehta** [comment]
I tried everything; I keep getting error:

"from PyQt5.QtWebEngineWidgets import QWebEnginePage
ValueError: PyCapsule_GetPointer called with incorrect name"
