### ISSUE TITLE
Not able to launch anaconda navigator: C:\ProgramData\Anaconda3\Scripts\conda-script.py, line 10, in <module> sys.exit(main()) TypeError: module object is not callable

### ISSUE THREAD

**Issue by richdevboston** [ContinuumIO/anaconda-issues#9335]
I need help on this error.  I've been scouring the internet looking for a solution for the past 2 weeks.  My Anaconda installation appears to be corrupted, because I cannot start the Navigator.  
I can launch Jupyter NB from "under the covers" of Navigator by using 'jupyter notebook' command at the Anaconda command prompt (from my Anaconda login root directory, but this is a hassle.  I want to use the Anaconda Navigator.  

Occurs when I try to launch Anaconda from the Anaconda Navigator shortcut or the Anaconda Command Prompt.

### Actual Behavior

When I launch the Anaconda Navigator from a Windows shortcut, the Anaconda command prompt window flashes and then nothing is left running.  The process does not stay running.  

### Expected Behavior

Anaconda Navigator should start up.  

### Steps to Reproduce

Occurs when I try to launch Anaconda from the Anaconda Navigator shortcut or the Anaconda Command Prompt.

##### Operating System: Windows 10

In my Windows Path, I have the following paths to Anaconda (these were the defaults from the installation process:
    c:\ProgramData\Anaconda3
    c:\ProgramData\Anaconda3\scripts
    c:\ProgramData\Anaconda3\Library\bin

##### `conda info`

```
'conda info' command does not work.  It gives the error message above.

c:\ProgramData\Anaconda3\Scripts>conda info
Traceback (most recent call last):
  File "c:\ProgramData\Anaconda3\Scripts\conda-script.py", line 10, in <module>
    sys.exit(main())
TypeError: 'module' object is not callable


```

##### `conda list --show-channel-urls`

```
The Anaconda command does not work.  It gives the error message below: 

>>> c:\ProgramData\Anaconda3\Scripts>conda list
Traceback (most recent call last):
  File "c:\ProgramData\Anaconda3\Scripts\conda-script.py", line 10, in <module>
    sys.exit(main())
TypeError: 'module' object is not callable

```
''' if I try to start it with the compiled script anaconda-navigator.exe at the command prompt, I get the following message.  

>>> c:\ProgramData\Anaconda3\Scripts>anaconda-navigator
#
# Please activate the conda root enviroment properly before running the
# `anaconda-navigator` command.
#
# To activate the environment please open a Windows Command Prompt and run:
#
#   c:\ProgramData\Anaconda3\Scripts\activate root
#
# For more information please see the documentation at:
#
#   https://docs.anaconda.com/anaconda/navigator/
#

And when I try running 'activate root', I get the following messages: 

c:\ProgramData\Anaconda3\Scripts>activate root
Traceback (most recent call last):
  File "c:\ProgramData\Anaconda3\Scripts\conda-script.py", line 10, in <module>
    sys.exit(main())
TypeError: 'module' object is not callable

'''

**Comment by nanbaima** [comment]
I am getting the same problem

**Comment by goanpeca** [comment]
@richdevboston did you use a normal prompt or the `Anaconda Prompt`? You will need to use the `Anaconda Prompt` to correctly activate the **base** environment so you can run the `conda info` and `conda list` commands

**Comment by goanpeca** [comment]
@nanbaima seems your instalation might be corrupt
