### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by HNoorazar** [ContinuumIO/anaconda-issues#9372]
Navigator Error

An unexpected error occurred on Navigator start-up

Report

Please report this issue in the anaconda issue tracker

Main Error

'conda_prefix'
Traceback

Traceback (most recent call last):
  File "/anaconda3/lib/python3.5/site-packages/anaconda_navigator/exceptions.py", line 75, in exception_handler
    return_value = func(*args, **kwargs)
  File "/anaconda3/lib/python3.5/site-packages/anaconda_navigator/app/start.py", line 138, in start_app
    window = run_app(splash)
  File "/anaconda3/lib/python3.5/site-packages/anaconda_navigator/app/start.py", line 64, in run_app
    window = MainWindow(splash=splash, tab_project=False)
  File "/anaconda3/lib/python3.5/site-packages/anaconda_navigator/widgets/main_window.py", line 163, in __init__
    self.api = AnacondaAPI()
  File "/anaconda3/lib/python3.5/site-packages/anaconda_navigator/api/anaconda_api.py", line 2122, in AnacondaAPI
    ANACONDA_API = _AnacondaAPI()
  File "/anaconda3/lib/python3.5/site-packages/anaconda_navigator/api/anaconda_api.py", line 89, in __init__
    self._conda_api = CondaAPI()
  File "/anaconda3/lib/python3.5/site-packages/anaconda_navigator/api/conda_api.py", line 1699, in CondaAPI
    CONDA_API = _CondaAPI()
  File "/anaconda3/lib/python3.5/site-packages/anaconda_navigator/api/conda_api.py", line 347, in __init__
    self.set_conda_prefix()
  File "/anaconda3/lib/python3.5/site-packages/anaconda_navigator/api/conda_api.py", line 507, in set_conda_prefix
    self.CONDA_PREFIX = info['conda_prefix']
KeyError: 'conda_prefix'

**Comment by goanpeca** [comment]
@HNoorazar please provide the output of

```
conda info
```

and

```
conda list --show-channel-urls
```

**Comment by goanpeca** [comment]
Please try to update your system. Open a terminal and run

```
conda update conda
conda update --all
```

**Comment by numanyilmaz** [comment]
Try `conda update --all` It solved the issue for me.
