### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by katemamyan** [ContinuumIO/anaconda-issues#9388]
## Main error
Application <b>notebook</b> launch may have produced errors.
## Traceback
```
Traceback (most recent call last):
  File "C:\Users\Kate Mamyan\Anaconda3\Scripts\jupyter-notebook-script.py", line 3, in <module>
    import notebook.notebookapp
  File "C:\Users\Kate Mamyan\Anaconda3\lib\site-packages\notebook\notebookapp.py", line 39, in <module>
    from zmq.eventloop import ioloop
ModuleNotFoundError: No module named 'zmq'

```
## System information
```
python: 3.6.1
language: ru_RU
os: Windows;10;10.0.16299;AMD64;Intel64 Family 6 Model 61 Stepping 4, GenuineIntel
version: 1.6.2
platform: win-64
qt: 5.6.2
pyqt: 5.6.0
conda: 4.5.1
```

**Comment by goanpeca** [comment]
Please reinstall zmq and pyzmq

```
conda install zmq --force
conda install pyzmq --force
```
