### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by gautam-matkar** [ContinuumIO/anaconda-issues#9393]
## Main error
Application <b>notebook</b> launch may have produced errors.
## Traceback
```
[I 22:25:02.651 NotebookApp] The port 8888 is already in use, trying another port.
[I 22:25:02.652 NotebookApp] The port 8889 is already in use, trying another port.
[W 22:25:02.671 NotebookApp] Error loading server extension jupyter_nbextensions_configurator
    Traceback (most recent call last):
      File "C:\Users\iw207\AppData\Local\Continuum\Anaconda3\lib\site-packages\notebook\notebookapp.py", line 1271, in init_server_extensions
        mod = importlib.import_module(modulename)
      File "C:\Users\iw207\AppData\Local\Continuum\Anaconda3\lib\importlib\__init__.py", line 126, in import_module
        return _bootstrap._gcd_import(name[level:], package, level)
      File "<frozen importlib._bootstrap>", line 978, in _gcd_import
      File "<frozen importlib._bootstrap>", line 961, in _find_and_load
      File "<frozen importlib._bootstrap>", line 948, in _find_and_load_unlocked
    ModuleNotFoundError: No module named 'jupyter_nbextensions_configurator'
[I 22:25:02.851 NotebookApp] Serving notebooks from local directory: C:\Users\iw207
[I 22:25:02.851 NotebookApp] 0 active kernels 
[I 22:25:02.851 NotebookApp] The Jupyter Notebook is running at: http://localhost:8890/?token=732f231b07b9c4af35e617cfa5f140b97e5a74cd6242ec80
[I 22:25:02.851 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 22:25:02.860 NotebookApp] 
    
    Copy/paste this URL into your browser when you connect for the first time,
    to login with a token:
        http://localhost:8890/?token=732f231b07b9c4af35e61

**Comment by goanpeca** [comment]
Try reinstalling `jupyter_nbextensions_configurator`

```
conda install jupyter_nbextensions_configurator --force
```
