### ISSUE TITLE
Permission Denied 

### ISSUE THREAD

**Issue by chanakyashah** [ContinuumIO/anaconda-issues#9408]
**Navigator Error**

An unexpected error occurred on Navigator start-up

**Main Error**

[Errno 13] Permission denied: '/Users/chanakya/Library/Application Support/binstar/https%3A%2F%2Fapi.anaconda.org.token'
Traceback

**Traceback (most recent call last):**
  File "/Users/chanakya/anaconda3/lib/python3.6/site-packages/anaconda_navigator/exceptions.py", line 75, in exception_handler
    return_value = func(*args, **kwargs)
  File "/Users/chanakya/anaconda3/lib/python3.6/site-packages/anaconda_navigator/app/start.py", line 138, in start_app
    window = run_app(splash)
  File "/Users/chanakya/anaconda3/lib/python3.6/site-packages/anaconda_navigator/app/start.py", line 64, in run_app
    window = MainWindow(splash=splash, tab_project=False)
  File "/Users/chanakya/anaconda3/lib/python3.6/site-packages/anaconda_navigator/widgets/main_window.py", line 163, in __init__
    self.api = AnacondaAPI()
  File "/Users/chanakya/anaconda3/lib/python3.6/site-packages/anaconda_navigator/api/anaconda_api.py", line 2183, in AnacondaAPI
    ANACONDA_API = _AnacondaAPI()
  File "/Users/chanakya/anaconda3/lib/python3.6/site-packages/anaconda_navigator/api/anaconda_api.py", line 90, in __init__
    self._client_api = ClientAPI()
  File "/Users/chanakya/anaconda3/lib/python3.6/site-packages/anaconda_navigator/api/client_api.py", line 638, in ClientAPI
    CLIENT_API = _ClientAPI()
  File "/Users/chanakya/anaconda3/lib/python3.6/site-packages/anaconda_navigator/api/client_api.py", line 93, in __init__
    self.reload_binstar_client()
  File "/Users/chanakya/anaconda3/lib/python3.6/site-packages/anaconda_navigator/api/client_api.py", line 312, in reload_binstar_client
    log_level=logging.NOTSET
  File "/Users/chanakya/anaconda3/lib/python3.6/site-packages/binstar_client/utils/config.py", line 116, in get_server_api
    token = load_token(url)
  File "/Users/chanakya/anaconda3/lib/python3.6/site-packages/binstar_client/utils/config.py", line 173, in load_token
    with open(tokenfile) as fd:
PermissionError: [Errno 13] Permission denied: '/Users/chanakya/Library/Application Support/binstar/https%3A%2F%2Fapi.anaconda.org.token'

> conda info

active environment : None
       user config file : /Users/chanakya/.condarc
populated config files : /Users/chanakya/.condarc
          conda version : 4.5.2
    conda-build version : 3.10.2
         python version : 3.6.5.final.0
       base environment : /Users/chanakya/anaconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/osx-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/osx-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/osx-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/osx-64
                          https://repo.anaconda.com/pkgs/pro/noarch
          package cache : /Users/chanakya/anaconda3/pkgs
                          /Users/chanakya/.conda/pkgs
       envs directories : /Users/chanakya/anaconda3/envs
                          /Users/chanakya/.conda/envs
               platform : osx-64
             user-agent : conda/4.5.2 requests/2.18.4 CPython/3.6.5 Darwin/16.7.0 OSX/10.12.6
                UID:GID : 501:20
             netrc file : None
           offline mode : False

I have tried everything that was possible mentioned on this repo i.e.

> $ conda update conda
> $ conda update anaconda-navigator
> $ conda update navigator-updater
> $ anaconda-navigator --reset

Nothing worked. Can you please help me fix.

**Comment by goanpeca** [comment]
@chanakyashah did you start navigator with sudo?

Try manually removing this file `/Users/chanakya/Library/Application Support/binstar/https%3A%2F%2Fapi.anaconda.org.token`

and avoid using navigator with sudo.

**Comment by chanakyashah** [comment]
Thanks, it worked.
