### ISSUE TITLE
Navigator Error when opening Anaconda 

### ISSUE THREAD

**Issue by tjratana** [ContinuumIO/anaconda-issues#9453]
### Actual Behavior

**Navigator Error**

An unexpected error occurred on Navigator start-up

**Report**

Please report this issue in the anaconda issue tracker

**Main Error**

'user_agent'

**Traceback**
Traceback (most recent call last):
  File "/Users/TJR/anaconda3/lib/python3.6/site-packages/anaconda_navigator/exceptions.py", line 75, in exception_handler
    return_value = func(*args, **kwargs)
  File "/Users/TJR/anaconda3/lib/python3.6/site-packages/anaconda_navigator/app/start.py", line 138, in start_app
    window = run_app(splash)
  File "/Users/TJR/anaconda3/lib/python3.6/site-packages/anaconda_navigator/app/start.py", line 64, in run_app
    window = MainWindow(splash=splash, tab_project=False)
  File "/Users/TJR/anaconda3/lib/python3.6/site-packages/anaconda_navigator/widgets/main_window.py", line 163, in __init__
    self.api = AnacondaAPI()
  File "/Users/TJR/anaconda3/lib/python3.6/site-packages/anaconda_navigator/api/anaconda_api.py", line 2183, in AnacondaAPI
    ANACONDA_API = _AnacondaAPI()
  File "/Users/TJR/anaconda3/lib/python3.6/site-packages/anaconda_navigator/api/anaconda_api.py", line 89, in __init__
    self._conda_api = CondaAPI()
  File "/Users/TJR/anaconda3/lib/python3.6/site-packages/anaconda_navigator/api/conda_api.py", line 1714, in CondaAPI
    CONDA_API = _CondaAPI()
  File "/Users/TJR/anaconda3/lib/python3.6/site-packages/anaconda_navigator/api/conda_api.py", line 350, in __init__
    self.set_conda_prefix(info=get_conda_info())
  File "/Users/TJR/anaconda3/lib/python3.6/site-packages/anaconda_navigator/api/conda_api.py", line 509, in set_conda_prefix
    self._user_agent = info['user_agent']
**KeyError**: 'user_agent'

### Expected Behavior

Anaconda Navigator should Open 

### Steps to Reproduce
Cntrl + Space - _type_ Anaconda - _press_ Enter 

##### Anaconda or Miniconda version:

conda 4.2.16

##### Operating System:

macOS High Sierra 10.13.4 

##### `conda info`

```
Current conda install:

               platform : osx-64
          conda version : 4.2.16
       conda is private : False
      conda-env version : 4.2.16
    conda-build version : 2.1.18
         python version : 3.6.3.final.0
       requests version : 2.18.4
       root environment : /Users/TJR/anaconda3  (writable)
    default environment : /Users/TJR/anaconda3
       envs directories : /Users/TJR/anaconda3/envs
          package cache : /Users/TJR/anaconda3/pkgs
           channel URLs : https://conda.anaconda.org/conda-forge/osx-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.continuum.io/pkgs/free/osx-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/pro/osx-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : /Users/TJR/.condarc
           offline mode : False

```

##### `conda list --show-channel-urls`

```
# packages in environment at /Users/TJR/anaconda3:
#
_ipyw_jlab_nb_ext_conf    0.1.0            py36h2fc01ae_0    https://repo.continuum.io/pkgs/main
absl-py                   0.1.13                    <pip>
alabaster                 0.7.10           py36h174008c_0    https://repo.continuum.io/pkgs/main
anaconda                  custom           py36ha4fed55_0    https://repo.continuum.io/pkgs/main
anaconda-client           1.6.14                     py_0    conda-forge
anaconda-navigator        1.8.5                    py36_0    https://repo.anaconda.com/pkgs/main
anaconda-project          0.8.0            py36h99320b2_0    https://repo.continuum.io/pkgs/main
appnope                   0.1.0            py36hf537a9a_0    https://repo.continuum.io/pkgs/main
appscript                 1.0.1            py36h9e71e49_1    https://repo.continuum.io/pkgs/main
asn1crypto                0.22.0           py36hb705621_1    https://repo.continuum.io/pkgs/main
astor                     0.6.2                     <pip>
astroid                   1.5.3            py36h1333018_0    https://repo.continuum.io/pkgs/main
astropy                   3.0.2                    py36_1    conda-forge
attrs                     18.1.0                     py_0    conda-forge
autopep8                  1.3.5                     <pip>
babel                     2.5.0            py36h9f161ff_0    https://repo.continuum.io/pkgs/main
backports                 1.0              py36ha3c1827_1    https://repo.continuum.io/pkgs/main
backports.shutil_get_terminal_size 1.0.0            py36hd7a2ee4_2    https://repo.continuum.io/pkgs/main
basemap                   1.1.0                    py36_4    conda-forge
basemap-data-hires        1.1.0                         0    conda-forge
beautifulsoup4            4.6.0            py36h72d3c9f_1    https://repo.continuum.io/pkgs/main
bitarray                  0.8.1            py36h20fa61d_0    https://repo.continuum.io/pkgs/main
bkcharts                  0.2              py36h073222e_0    https://repo.continuum.io/pkgs/main
blaze                     0.11.3           py36h02e7a37_0    https://repo.continuum.io/pkgs/main
bleach                    2.0.0            py36h8fcea71_0    https://repo.continuum.io/pkgs/main
bleach                    1.5.0                     <pip>
bokeh                     0.12.15            pyh8da4227_0    bokeh
boost                     1.66.0                   py36_1    conda-forge
boost-cpp                 1.66.0                        1    conda-forge
boto                      2.48.0           py36hdbc59ac_1    https://repo.continuum.io/pkgs/main
bottleneck                1.2.1            py36hbd380ad_0    https://repo.continuum.io/pkgs/main
bzip2                     1.0.6                h92991f9_1    https://repo.continuum.io/pkgs/main
ca-certificates           2016.2.28                     1    conda-forge/label/broken
cairo                     1.14.10                       0    conda-forge
catboost                  0.8.1                    py36_0    conda-forge
certifi                   2018.4.16                py36_0    conda-forge
cffi                      1.10.0           py36h880867e_1    https://repo.continuum.io/pkgs/main
chardet                   3.0.4            py36h96c241c_1    https://repo.continuum.io/pkgs/main
clangdev                  4.0.0                 default_0    conda-forge
click                     6.7              py36hec950be_0    https://repo.continuum.io/pkgs/main
click-plugins             1.0.3                    py36_0    conda-forge
cligj                     0.4.0                    py36_0    conda-forge
cloudpickle               0.4.0            py36h13b7e56_0    https://repo.continuum.io/pkgs/main
clyent                    1.2.2            py36hae3ad88_0    https://repo.continuum.io/pkgs/main
colorama                  0.3.9            py36hd29a30c_0    https://repo.continuum.io/pkgs/main
conda                     4.2.16                   py36_0    conda-forge/label/broken
conda-build               2.1.18                   py36_0    conda-forge
conda-env                 2.6.0                         0    conda-forge
conda-verify              2.0.0            py36he837df3_0    https://repo.continuum.io/pkgs/main
contextlib2               0.5.5            py36hd66e5e7_0    https://repo.continuum.io/pkgs/main
coverage                  4.5.1                    py36_0    conda-forge
cryptography              2.0.3            py36h22d4226_1    https://repo.continuum.io/pkgs/main
curl                      7.55.1               h7601780_3    https://repo.continuum.io/pkgs/main
cycler                    0.10.0           py36hfc81398_0    https://repo.continuum.io/pkgs/main
cython                    0.26.1           py36hd51f8eb_0    https://repo.continuum.io/pkgs/main
cytoolz                   0.8.2            py36h290905f_0    https://repo.continuum.io/pkgs/main
dask                      0.15.3           py36hc3ad2d6_0    https://repo.continuum.io/pkgs/main
dask-core                 0.15.3           py36hc0be6b7_0    https://repo.continuum.io/pkgs/main
datashape                 0.5.4            py36hfb22df8_0    https://repo.continuum.io/pkgs/main
dbus                      1.11.0                        0    conda-forge
decorator                 4.1.2            py36h69a1b52_0    https://repo.continuum.io/pkgs/main
descartes                 1.1.0                      py_1    conda-forge
distributed               1.19.1           py36h4ae75d2_0    https://repo.continuum.io/pkgs/main
docutils                  0.14             py36hbfde631_0    https://repo.continuum.io/pkgs/main
drms                      0.5.5                      py_0    conda-forge
entrypoints               0.2.3            py36hd81d71f_2    https://repo.continuum.io/pkgs/main
et_xmlfile                1.0.1            py36h1315bdc_0    https://repo.continuum.io/pkgs/main
expat                     2.2.4                h8f26bf8_1    https://repo.continuum.io/pkgs/main
fastcache                 1.0.2            py36h8606a76_0    https://repo.continuum.io/pkgs/main
filelock                  2.0.12           py36h0d0b4fb_0    https://repo.continuum.io/pkgs/main
fiona                     1.7.11                   py36_0    conda-forge/label/broken
flask                     0.12.2           py36h5658096_0    https://repo.continuum.io/pkgs/main
flask-cors                3.0.3            py36h7387b97_0    https://repo.continuum.io/pkgs/main
folium                    0.2.1                    py36_0    ioos
fontconfig                2.12.6                        0    conda-forge
freetype                  2.8.1                         0    conda-forge
freexl                    1.0.5                         0    conda-forge
futures-compat            1.0                       py3_0  
gast                      0.2.0                     <pip>
gdal                      2.1.4                    py36_1    conda-forge/label/broken
geojson                   1.3.3                    py36_0    ioos
geojsonio                 0.0.3                      py_0    conda-forge
geopandas                 0.3.0                    py36_0    conda-forge
geos                      3.6.2                         1    conda-forge
geotiff                   1.4.2                         1    conda-forge
get_terminal_size         1.0.0                h7520d66_0    https://repo.continuum.io/pkgs/main
gettext                   0.19.8.1             hb0f4f8b_2    https://repo.continuum.io/pkgs/main
gevent                    1.2.2            py36ha70b9d6_0    https://repo.continuum.io/pkgs/main
giflib                    5.1.4                         0    conda-forge
github3.py                1.1.0                    py36_0    conda-forge
glib                      2.55.0                        0    conda-forge
glob2                     0.5              py36h12393a9_0    https://repo.continuum.io/pkgs/main
glymur                    0.8.15                   py36_0    conda-forge
gmp                       6.1.2                h4a9834d_0    https://repo.continuum.io/pkgs/main
gmpy2                     2.0.8            py36h7ef02cb_1    https://repo.continuum.io/pkgs/main
greenlet                  0.4.12           py36hf09ba7b_0    https://repo.continuum.io/pkgs/main
grpcio                    1.11.0                    <pip>
h5py                      2.7.0            py36h6400cee_1    https://repo.continuum.io/pkgs/main
hdf4                      4.2.13                        0    conda-forge
hdf5                      1.10.1               h6090a45_0    https://repo.continuum.io/pkgs/main
heapdict                  1.0.0            py36h27a9ac6_0    https://repo.continuum.io/pkgs/main
html5lib                  0.999999999      py36h79312fd_0    https://repo.continuum.io/pkgs/main
html5lib                  0.9999999                 <pip>
hypothesis                3.56.5                   py36_0    conda-forge
icu                       58.2                 hea21ae5_0    https://repo.continuum.io/pkgs/main
idna                      2.6              py36h8628d0a_1    https://repo.continuum.io/pkgs/main
imageio                   2.2.0            py36h5e01289_0    https://repo.continuum.io/pkgs/main
imagesize                 0.7.1            py36h3495948_0    https://repo.continuum.io/pkgs/main
intel-openmp              2018.0.0             h68bdfb3_7    https://repo.continuum.io/pkgs/main
ipykernel                 4.6.1            py36h3208c25_0    https://repo.continuum.io/pkgs/main
ipython                   6.1.0            py36hf612aae_1    https://repo.continuum.io/pkgs/main
ipython_genutils          0.2.0            py36h241746c_0    https://repo.continuum.io/pkgs/main
ipywidgets                7.0.0            py36h24d3910_0    https://repo.continuum.io/pkgs/main
isort                     4.2.15           py36hceb2a01_0    https://repo.continuum.io/pkgs/main
itsdangerous              0.24             py36h49fbb8d_1    https://repo.continuum.io/pkgs/main
jbig                      2.1                  h4d881f8_0    https://repo.continuum.io/pkgs/main
jdcal                     1.3              py36h1986823_0    https://repo.continuum.io/pkgs/main
jedi                      0.10.2           py36h6325097_0    https://repo.continuum.io/pkgs/main
jinja2                    2.9.6            py36hde4beb4_1    https://repo.continuum.io/pkgs/main
jpeg                      9b                   haccd157_1    https://repo.continuum.io/pkgs/main
json-c                    0.13.1               h470a237_0    conda-forge
jsonschema                2.6.0            py36hb385e00_0    https://repo.continuum.io/pkgs/main
jupyter                   1.0.0            py36h598a6cc_0    https://repo.continuum.io/pkgs/main
jupyter-contrib-core      0.3.3                     <pip>
jupyter-contrib-nbextensions 0.5.0                     <pip>
jupyter-highlight-selected-word 0.2.0                     <pip>
jupyter-latex-envs        1.4.4                     <pip>
jupyter-nbextensions-configurator 0.4.0                     <pip>
jupyter_client            5.1.0            py36hf6c435f_0    https://repo.continuum.io/pkgs/main
jupyter_console           5.2.0            py36hccf5b1c_1    https://repo.continuum.io/pkgs/main
jupyter_core              4.3.0            py36h93810fe_0    https://repo.continuum.io/pkgs/main
jupyterlab                0.27.0           py36hd3092eb_2    https://repo.continuum.io/pkgs/main
jupyterlab_launcher       0.4.0            py36h93e02e9_0    https://repo.continuum.io/pkgs/main
jupyterthemes             0.19.1                    <pip>
kealib                    1.4.7                         4    conda-forge
Keras                     2.1.5                     <pip>
lazy-object-proxy         1.3.1            py36h2fbbe47_0    https://repo.continuum.io/pkgs/main
lesscpy                   0.13.0                    <pip>
libcxx                    4.0.1                h579ed51_0    https://repo.continuum.io/pkgs/main
libcxxabi                 4.0.1                hebd6815_0    https://repo.continuum.io/pkgs/main
libdap4                   3.18.3                        2    conda-forge
libedit                   3.1                  hb4e282d_0    https://repo.continuum.io/pkgs/main
libffi                    3.2.1                hd939716_3    https://repo.continuum.io/pkgs/main
libgdal                   2.1.4                         9    conda-forge
libgfortran               3.0.1                h93005f0_2    https://repo.continuum.io/pkgs/main
libiconv                  1.15                 h99df5da_5    https://repo.continuum.io/pkgs/main
libkml                    1.3.0                         6    conda-forge
libnetcdf                 4.4.1.1                      10    conda-forge
libpng                    1.6.34               he12f830_0    anaconda
libpq                     9.6.3                         0    conda-forge
libsodium                 1.0.13               hba5e272_2    https://repo.continuum.io/pkgs/main
libspatialindex           1.8.5                         1    conda-forge
libspatialite             4.3.0a                       19    conda-forge
libssh2                   1.8.0                h1218725_2    https://repo.continuum.io/pkgs/main
libtiff                   4.0.8                h8cd0352_9    https://repo.continuum.io/pkgs/main
libxml2                   2.9.4                hbd0960b_5    https://repo.continuum.io/pkgs/main
libxslt                   1.1.29               h95a2935_5    https://repo.continuum.io/pkgs/main
lightgbm                  2.1.0                    py36_0    conda-forge
llvm-meta                 6.0.0                         0    conda-forge
llvmdev                   4.0.0                 default_0    conda-forge
llvmlite                  0.20.0                   py36_0    https://repo.continuum.io/pkgs/main
locket                    0.2.0            py36hca03003_1    https://repo.continuum.io/pkgs/main
lxml                      4.1.0            py36h8179fc0_0    https://repo.continuum.io/pkgs/main
lzo                       2.10                 hb6b8854_1    https://repo.continuum.io/pkgs/main
Markdown                  2.6.11                    <pip>
markupsafe                1.0              py36h3a1e703_1    https://repo.continuum.io/pkgs/main
matplotlib                2.1.0            py36h5068139_0    https://repo.continuum.io/pkgs/main
mccabe                    0.6.1            py36hdaeb55d_0    https://repo.continuum.io/pkgs/main
mistune                   0.7.4            py36hccd6237_0    https://repo.continuum.io/pkgs/main
mkl                       2018.0.0             h5ef208c_6    https://repo.continuum.io/pkgs/main
mkl-service               1.1.2            py36h7ea6df4_4    https://repo.continuum.io/pkgs/main
mock                      2.0.0                    py36_0    conda-forge
mpc                       1.0.3                hc455b36_4    https://repo.continuum.io/pkgs/main
mpfr                      3.1.5                h7fa3772_1    https://repo.continuum.io/pkgs/main
mpmath                    0.19             py36h9185fea_2    https://repo.continuum.io/pkgs/main
msgpack-python            0.4.8            py36h46767b2_0    https://repo.continuum.io/pkgs/main
multipledispatch          0.4.9            py36hc5f92b5_0    https://repo.continuum.io/pkgs/main
munch                     2.3.2                      py_0    conda-forge
navigator-updater         0.1.0            py36h7aee5fb_0    https://repo.continuum.io/pkgs/main
nbconvert                 5.3.1            py36h810822e_0    https://repo.continuum.io/pkgs/main
nbformat                  4.4.0            py36h827af21_0    https://repo.continuum.io/pkgs/main
ncurses                   6.0                  ha932d30_1    https://repo.continuum.io/pkgs/main
ndg-httpsclient           0.4.4                    py36_0    conda-forge
networkx                  2.0              py36hefccab9_0    https://repo.continuum.io/pkgs/main
nltk                      3.2.4            py36h27d1ea0_0    https://repo.continuum.io/pkgs/main
nose                      1.3.7            py36h73fae2b_2    https://repo.continuum.io/pkgs/main
notebook                  5.0.0            py36h462289e_2    https://repo.continuum.io/pkgs/main
numba                     0.35.0              np113py36_6    https://repo.continuum.io/pkgs/main
numexpr                   2.6.2            py36h0f4f1da_1    https://repo.continuum.io/pkgs/main
numpy                     1.13.3           py36h2cdce51_0    https://repo.continuum.io/pkgs/main
numpy                     1.14.2                    <pip>
numpydoc                  0.7.0            py36he54d08e_0    https://repo.continuum.io/pkgs/main
odo                       0.5.1            py36hc1af34a_0    https://repo.continuum.io/pkgs/main
olefile                   0.44             py36ha08bf50_0    https://repo.continuum.io/pkgs/main
openjpeg                  2.3.0                         2    conda-forge
openmp                    4.0.0                         1    conda-forge
openpyxl                  2.4.8            py36he899640_1    https://repo.continuum.io/pkgs/main
openssl                   1.0.2o                        0    conda-forge
packaging                 16.8             py36he5e8135_0    https://repo.continuum.io/pkgs/main
pandas                    0.20.3           py36hd6655d8_2    https://repo.continuum.io/pkgs/main
pandoc                    1.19.2.1             ha5e8f32_1    https://repo.continuum.io/pkgs/main
pandocfilters             1.4.2            py36h3b0b094_1    https://repo.continuum.io/pkgs/main
partd                     0.3.8            py36hf5c4cb8_0    https://repo.continuum.io/pkgs/main
path.py                   10.3.1           py36hd33c240_0    https://repo.continuum.io/pkgs/main
pathlib2                  2.3.0            py36h877a6d8_0    https://repo.continuum.io/pkgs/main
patsy                     0.4.1            py36ha1b3fa5_0    https://repo.continuum.io/pkgs/main
pbr                       4.0.2                      py_0    conda-forge
pcre                      8.39                          0    conda-forge
pep8                      1.7.0            py36hc268eb1_0    https://repo.continuum.io/pkgs/main
pexpect                   4.2.1            py36h3eac828_0    https://repo.continuum.io/pkgs/main
pickleshare               0.7.4            py36hf512f8e_0    https://repo.continuum.io/pkgs/main
pillow                    4.2.1            py36h0263179_0    https://repo.continuum.io/pkgs/main
pip                       10.0.1                    <pip>
pip                       9.0.1            py36hbd95645_3    https://repo.continuum.io/pkgs/main
pixman                    0.34.0                        2    conda-forge
pkginfo                   1.4.1            py36h25bf955_0    https://repo.continuum.io/pkgs/main
plotly                    2.5.1                     <pip>
ply                       3.10             py36h10e714e_0    https://repo.continuum.io/pkgs/main
poppler                   0.61.1                        3    conda-forge
poppler-data              0.4.9                         0    conda-forge
prettytable               0.7.2                     <pip>
proj4                     4.9.3                         5    conda-forge
prompt_toolkit            1.0.15           py36haeda067_0    https://repo.continuum.io/pkgs/main
protobuf                  3.5.2.post1               <pip>
psutil                    5.4.0            py36ha052210_0    https://repo.continuum.io/pkgs/main
psycopg2                  2.7.4                    py36_0    conda-forge
ptyprocess                0.5.2            py36he6521c3_0    https://repo.continuum.io/pkgs/main
py                        1.4.34           py36hecf431b_1    https://repo.continuum.io/pkgs/main
pyasn1                    0.4.2                      py_0    conda-forge
pycodestyle               2.3.1            py36h83e8646_0    https://repo.continuum.io/pkgs/main
pycosat                   0.6.3                    py36_0    conda-forge
pycparser                 2.18             py36h724b2fc_1    https://repo.continuum.io/pkgs/main
pycrypto                  2.6.1            py36h72f2894_1    https://repo.continuum.io/pkgs/main
pycurl                    7.43.0           py36hdb90038_3    https://repo.continuum.io/pkgs/main
pyflakes                  1.6.0            py36hea45e83_0    https://repo.continuum.io/pkgs/main
pygments                  2.2.0            py36h240cd3f_0    https://repo.continuum.io/pkgs/main
pylint                    1.7.4            py36hdee9077_0    https://repo.continuum.io/pkgs/main
pyodbc                    4.0.17           py36h5478161_0    https://repo.continuum.io/pkgs/main
pyopenssl                 17.2.0           py36h5d7bf08_0    https://repo.continuum.io/pkgs/main
pyparsing                 2.2.0            py36hb281f35_0    https://repo.continuum.io/pkgs/main
pyproj                    1.9.5.1                  py36_0    conda-forge
pyqt                      5.6.0            py36he5c6137_6    https://repo.continuum.io/pkgs/main
pysal                     1.14.3                   py36_0    conda-forge
pyshp                     1.2.12                     py_0    conda-forge
pysocks                   1.6.7            py36hfa33cec_1    https://repo.continuum.io/pkgs/main
pytables                  3.4.2            py36hfbd7ab0_2    https://repo.continuum.io/pkgs/main
pytest                    3.2.1            py36h9963153_1    https://repo.continuum.io/pkgs/main
pytest-arraydiff          0.2                        py_0    conda-forge
pytest-astropy            0.2.1                      py_0    conda-forge
pytest-doctestplus        0.1.2                      py_0    conda-forge
pytest-mock               1.10.0                   py36_0    conda-forge
pytest-openfiles          0.2.0                      py_0    conda-forge
pytest-remotedata         0.2.0                      py_0    conda-forge
python                    3.6.3                h6804ab2_0    https://repo.continuum.io/pkgs/main
python-dateutil           2.6.1            py36h86d2abb_1    https://repo.continuum.io/pkgs/main
python-json-logger        0.1.8                    py36_0    conda-forge
python.app                2                py36h7fe2238_6    https://repo.continuum.io/pkgs/main
pytz                      2017.2           py36h2e7dfbc_1    https://repo.continuum.io/pkgs/main
pywavelets                0.5.2            py36h2710a04_0    https://repo.continuum.io/pkgs/main
pyyaml                    3.12             py36h2ba1e63_1    https://repo.continuum.io/pkgs/main
pyzmq                     16.0.2           py36h087ffad_2    https://repo.continuum.io/pkgs/main
qt                        5.6.2               h9975529_14    https://repo.continuum.io/pkgs/main
qtawesome                 0.4.4            py36h468c6fb_0    https://repo.continuum.io/pkgs/main
qtconsole                 4.3.1            py36hd96c0ff_0    https://repo.continuum.io/pkgs/main
qtpy                      1.4.2            py36h8a2030e_0    conda-forge
readline                  7.0                  h81b24a6_3    https://repo.continuum.io/pkgs/main
requests                  2.18.4           py36h4516966_1    https://repo.continuum.io/pkgs/main
rope                      0.10.5           py36h5764ad1_0    https://repo.continuum.io/pkgs/main
rtree                     0.8.3                    py36_0    conda-forge
ruamel_yaml               0.11.14          py36h9d7ade0_2    https://repo.continuum.io/pkgs/main
scikit-image              0.13.0           py36h398857d_1    https://repo.continuum.io/pkgs/main
scikit-learn              0.19.1           py36hffbff8c_0    https://repo.continuum.io/pkgs/main
scipy                     0.19.1           py36h3e758e1_3    https://repo.continuum.io/pkgs/main
seaborn                   0.8.0            py36h74df97e_0    https://repo.continuum.io/pkgs/main
setuptools                39.0.1                    <pip>
setuptools                36.5.0           py36h2134326_0    https://repo.continuum.io/pkgs/main
shapely                   1.6.4                    py36_0    conda-forge
simplegeneric             0.8.1            py36he5b5b09_0    https://repo.continuum.io/pkgs/main
simplejson                3.14.0           py36h1de35cc_0    anaconda
singledispatch            3.4.0.3          py36hf20db9d_0    https://repo.continuum.io/pkgs/main
sip                       4.18.1           py36h2824476_2    https://repo.continuum.io/pkgs/main
six                       1.11.0           py36h0e22d5e_1    https://repo.continuum.io/pkgs/main
snowballstemmer           1.2.1            py36h6c7b616_0    https://repo.continuum.io/pkgs/main
sortedcollections         0.5.3            py36he9c3ed6_0    https://repo.continuum.io/pkgs/main
sortedcontainers          1.5.7            py36ha982688_0    https://repo.continuum.io/pkgs/main
sphinx                    1.6.3            py36hcd1b3e7_0    https://repo.continuum.io/pkgs/main
sphinxcontrib             1.0              py36h9364dc8_1    https://repo.continuum.io/pkgs/main
sphinxcontrib-websupport  1.0.1            py36h92f4a7a_1    https://repo.continuum.io/pkgs/main
spyder                    3.2.4            py36h908396f_0    https://repo.continuum.io/pkgs/main
sqlalchemy                1.1.13           py36h156b851_0    https://repo.continuum.io/pkgs/main
sqlite                    3.20.1               h900c3b0_1    https://repo.continuum.io/pkgs/main
statsmodels               0.8.0            py36h9c68fc9_0    https://repo.continuum.io/pkgs/main
suds-jurko                0.6                      py36_1    conda-forge
sunpy                     0.9.0                    py36_0    conda-forge
sympy                     1.1.1            py36h7f3cf04_0    https://repo.continuum.io/pkgs/main
tabulate                  0.8.2                     <pip>
tblib                     1.3.2            py36hda67792_0    https://repo.continuum.io/pkgs/main
tensorboard               1.7.0                     <pip>
tensorflow                1.7.0                     <pip>
termcolor                 1.1.0                     <pip>
terminado                 0.6              py36h656782e_0    https://repo.continuum.io/pkgs/main
testpath                  0.3.1            py36h625a49b_0    https://repo.continuum.io/pkgs/main
textblob                  0.15.1                    <pip>
tk                        8.6.7                hcdce994_1    https://repo.continuum.io/pkgs/main
toolz                     0.8.2            py36h7b95164_0    https://repo.continuum.io/pkgs/main
tornado                   4.5.2            py36h468dda9_0    https://repo.continuum.io/pkgs/main
traitlets                 4.3.2            py36h65bd3ce_0    https://repo.continuum.io/pkgs/main
typing                    3.6.2            py36haa2d9ef_0    https://repo.continuum.io/pkgs/main
unicodecsv                0.14.1           py36he531d66_0    https://repo.continuum.io/pkgs/main
unixodbc                  2.3.4                h4cb4dde_1    https://repo.continuum.io/pkgs/main
uritemplate.py            3.0.2                    py36_0    conda-forge
urllib3                   1.22             py36h68b9469_0    https://repo.continuum.io/pkgs/main
wcwidth                   0.1.7            py36h8c6ec74_0    https://repo.continuum.io/pkgs/main
webencodings              0.5.1            py36h3b9701d_1    https://repo.continuum.io/pkgs/main
werkzeug                  0.12.2           py36h168efa1_0    https://repo.continuum.io/pkgs/main
Werkzeug                  0.14.1                    <pip>
wheel                     0.29.0           py36h3597b6d_1    https://repo.continuum.io/pkgs/main
wheel                     0.31.0                    <pip>
widgetsnbextension        3.0.2            py36h91f43ea_1    https://repo.continuum.io/pkgs/main
wrapt                     1.10.11          py36hc29e774_0    https://repo.continuum.io/pkgs/main
xerces-c                  3.2.0                         0    conda-forge
xgboost                   0.71                     py36_0    conda-forge
xlrd                      1.1.0            py36h336f4a2_1    https://repo.continuum.io/pkgs/main
xlsxwriter                1.0.2            py36h3736301_0    https://repo.continuum.io/pkgs/main
xlwings                   0.11.4           py36hc75f156_0    https://repo.continuum.io/pkgs/main
xlwt                      1.2.0            py36h5ad1178_0    https://repo.continuum.io/pkgs/main
xz                        5.2.3                ha24016e_1    https://repo.continuum.io/pkgs/main
yaml                      0.1.7                hff548bb_1    https://repo.continuum.io/pkgs/main
zeromq                    4.2.2                h131e0f7_1    https://repo.continuum.io/pkgs/main
zict                      0.1.3            py36h71da714_0    https://repo.continuum.io/pkgs/main
zlib                      1.2.11               h60db283_1    https://repo.continuum.io/pkgs/main

```

**Comment by goanpeca** [comment]
the conda version you have is

`conda                     4.2.16                   py36_0    conda-forge/label/broken` 

Please update conda.

```
conda install conda=4.5
```
