### ISSUE TITLE
byte indices must be integers or slices, not str

### ISSUE THREAD

**Issue by ShreyaManna** [ContinuumIO/anaconda-issues#9472]
Navigator Error
An unexpected error occurred on Navigator start-up.

### Actual Behavior
Prompt opens and vanishes.

### Expected Behavior
Prompt stays

##### Operating System:
Windows
##### `conda info`

Traceback (most recent call last):
  File "C:\Users\Inspiron 15\Anaconda3\lib\site-packages\anaconda_navigator\exceptions.py", line 75, in exception_handler
    return_value = func(*args, **kwargs)
  File "C:\Users\Inspiron 15\Anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 120, in start_app
    window = run_app(splash)
  File "C:\Users\Inspiron 15\Anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 63, in run_app
    window = MainWindow(splash=splash)
  File "C:\Users\Inspiron 15\Anaconda3\lib\site-packages\anaconda_navigator\widgets\main_window.py", line 163, in __init__
    self.api = AnacondaAPI()
  File "C:\Users\Inspiron 15\Anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 2004, in AnacondaAPI
    ANACONDA_API = _AnacondaAPI()
  File "C:\Users\Inspiron 15\Anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 88, in __init__
    self._conda_api = CondaAPI()
  File "C:\Users\Inspiron 15\Anaconda3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 1690, in CondaAPI
    CONDA_API = _CondaAPI()
  File "C:\Users\Inspiron 15\Anaconda3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 347, in __init__
    self.set_conda_prefix()
  File "C:\Users\Inspiron 15\Anaconda3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 496, in set_conda_prefix
    self.ROOT_PREFIX = info['root_prefix']
TypeError: byte indices must be integers or slices, not str```

```

##### `conda list --show-channel-urls`
<!-- between the ticks below, paste the output of 'conda list --show-channel-urls' -->
```

```

**Comment by goanpeca** [comment]
@ShreyaManna please provide the output of 

```
conda info
```

``` 
conda list --show-channel-urls
```

**Comment by goanpeca** [comment]
No information provided closing.

---

Please remember to update to the latest version of Navigator to include
the latest fixes.

Open a terminal (on Linux or Mac) or the Anaconda Command Prompt (on windows)
and type:

```
conda update conda
conda update anaconda-navigator
conda update navigator-updater
```
