### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by medmond78** [ContinuumIO/anaconda-issues#9485]
## Main error
Application <b>jupyterlab</b> launch may have produced errors.
## Traceback
```
Traceback (most recent call last):
  File "C:\Users\mpausley\AppData\Local\Continuum\Anaconda3\Scripts\jupyter-lab-script.py", line 6, in <module>
    from jupyterlab.labapp import main
  File "C:\Users\mpausley\AppData\Local\Continuum\Anaconda3\lib\site-packages\jupyterlab\labapp.py", line 7, in <module>
    from notebook.notebookapp import NotebookApp, aliases, flags
  File "C:\Users\mpausley\AppData\Local\Continuum\Anaconda3\lib\site-packages\notebook\__init__.py", line 25, in <module>
    from .nbextensions import install_nbextension
  File "C:\Users\mpausley\AppData\Local\Continuum\Anaconda3\lib\site-packages\notebook\nbextensions.py", line 27, in <module>
    from jupyter_core.utils import ensure_dir_exists
ImportError: cannot import name 'ensure_dir_exists'

```
## System information
```
python: 3.6.1
language: en_US
os: Windows;7;6.1.7601;AMD64;Intel64 Family 6 Model 94 Stepping 3, GenuineIntel
version: 1.6.2
platform: win-64
qt: 5.6.2
pyqt: 5.6.0
conda: 4.5.4
```

**Comment by medmond78** [comment]
I installed Anaconda prior to losing admin privileges on my machine, so I'm hoping this is fixable without drastic measures.

**Comment by medmond78** [comment]
This was resolved by running `conda update jupyter_core`
