### ISSUE TITLE
object of type 'NoneType' has no len()

### ISSUE THREAD

**Issue by sgrossberndt** [ContinuumIO/anaconda-issues#9499]
### Actual Behavior

Anaconda Navigator does not start but displays error message:

```
object of type 'NoneType' has no len()

Traceback

Traceback (most recent call last):
  File "D:\Anaconda2\lib\site-packages\anaconda_navigator\exceptions.py", line 75, in exception_handler
    return_value = func(*args, **kwargs)
  File "D:\Anaconda2\lib\site-packages\anaconda_navigator\app\start.py", line 150, in start_app
    window = run_app(splash)
  File "D:\Anaconda2\lib\site-packages\anaconda_navigator\app\start.py", line 65, in run_app
    window = MainWindow(splash=splash, tab_project=False)
  File "D:\Anaconda2\lib\site-packages\anaconda_navigator\widgets\main_window.py", line 163, in __init__
    self.api = AnacondaAPI()
  File "D:\Anaconda2\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 2185, in AnacondaAPI
    ANACONDA_API = _AnacondaAPI()
  File "D:\Anaconda2\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 89, in __init__
    self._conda_api = CondaAPI()
  File "D:\Anaconda2\lib\site-packages\anaconda_navigator\api\conda_api.py", line 1714, in CondaAPI
    CONDA_API = _CondaAPI()
  File "D:\Anaconda2\lib\site-packages\anaconda_navigator\api\conda_api.py", line 353, in __init__
    self.sys_rc_path = join(self.ROOT_PREFIX, '.condarc')
  File "D:\Anaconda2\lib\ntpath.py", line 65, in join
    result_drive, result_path = splitdrive(path)
  File "D:\Anaconda2\lib\ntpath.py", line 115, in splitdrive
    if len(p) > 1:
TypeError: object of type 'NoneType' has no len()
```

### Expected Behavior

Anaconda Navigator should start

### Steps to Reproduce

Install Anaconda3-5.1.0-Windows-x86_64.exe
Start "Anaconda Navigator"
Uninstall Anaconda3 5.1.0
Install Anaconda2-5.2.0-Windows-x86_64.exe and try to start "Anaconda Navigator"

##### Anaconda or Miniconda version:

Anaconda2 5.2.0

##### Operating System:

Windows 10 1803

##### `conda info`

```
# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "D:\Anaconda2\lib\site-packages\conda\cli\main.py", line 97, in main
        from ..activate import main as activator_main
      File "D:\Anaconda2\lib\site-packages\conda\activate.py", line 12, in <module>
        context.__init__()  # oOn import, context does not include SEARCH_PATH. This line fixes that.
      File "D:\Anaconda2\lib\site-packages\conda\base\context.py", line 236, in __init__
        argparse_args=argparse_args)
      File "D:\Anaconda2\lib\site-packages\conda\common\configuration.py", line 722, in __init__
        self._set_search_path(search_path)
      File "D:\Anaconda2\lib\site-packages\conda\common\configuration.py", line 728, in _set_search_path
        self._set_raw_data(load_file_configs(search_path))
      File "D:\Anaconda2\lib\site-packages\conda\common\configuration.py", line 369, in load_file_configs
        raw_data = odict(kv for kv in chain.from_iterable(load_paths))
      File "D:\Anaconda2\lib\collections.py", line 69, in __init__
        self.__update(*args, **kwds)
      File "D:\Anaconda2\lib\_abcoll.py", line 571, in update
        for key, value in other:
      File "D:\Anaconda2\lib\site-packages\conda\common\configuration.py", line 369, in <genexpr>
        raw_data = odict(kv for kv in chain.from_iterable(load_paths))
      File "D:\Anaconda2\lib\site-packages\conda\common\configuration.py", line 344, in _file_yaml_loader
        yield fullpath, YamlRawParameter.make_raw_parameters_from_file(fullpath)
      File "D:\Anaconda2\lib\site-packages\conda\common\configuration.py", line 332, in make_raw_parameters_from_file
        ruamel_yaml = yaml_load(fh)
      File "D:\Anaconda2\lib\site-packages\conda\common\serialize.py", line 54, in yaml_load
        return yaml.load(string, Loader=yaml.RoundTripLoader, version="1.2")
      File "D:\Anaconda2\lib\site-packages\ruamel_yaml\main.py", line 637, in load
        loader = Loader(stream, version, preserve_quotes=preserve_quotes)
      File "D:\Anaconda2\lib\site-packages\ruamel_yaml\loader.py", line 59, in __init__
        Reader.__init__(self, stream, loader=self)
      File "D:\Anaconda2\lib\site-packages\ruamel_yaml\reader.py", line 80, in __init__
        self.stream = stream  # type: Any  # as .read is called
      File "D:\Anaconda2\lib\site-packages\ruamel_yaml\reader.py", line 125, in stream
        self.determine_encoding()
      File "D:\Anaconda2\lib\site-packages\ruamel_yaml\reader.py", line 180, in determine_encoding
        self.update(1)
      File "D:\Anaconda2\lib\site-packages\ruamel_yaml\reader.py", line 241, in update
        self.check_printable(data)
      File "D:\Anaconda2\lib\site-packages\ruamel_yaml\reader.py", line 208, in check_printable
        'unicode', "special characters are not allowed")
    ReaderError: unacceptable character #x0000: special characters are not allowed
      in "D:\Users\MyUserName\.condarc", position 0

`$ D:\Anaconda2\Scripts\conda shell.cmd.exe activate activate D:\Anaconda2`

  environment variables:
                 CIO_TEST=<not set>
               CONDA_ROOT=D:\Anaconda2
                 HOMEPATH=\Users\MyUserName
                     PATH=D:\Anaconda2\Library\bin;C:\Program Files (x86)\Common Files\Oracle\Ja
                          va\javapath;C:\ProgramData\Oracle\Java\javapath;C:\WINDOWS\system32;C:
                          \WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShel
                          l\v1.0\;C:\Program Files (x86)\ATI Technologies\ATI.ACE\Core-
                          Static;D:\php7.0-nts-x64;C:\ProgramData\ComposerSetup\bin;C:\Program
                          Files\TortoiseGit\bin;C:\Program
                          Files\PuTTY\;C:\WINDOWS\System32\OpenSSH\;C:\Program
                          Files\Git\cmd;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\us
                          r\bin;D:\Users\MyUserName\AppData\Local\Microsoft\WindowsApps;;C:\Program
                          Files\Microsoft VS Code\bin
             PSMODULEPATH=C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules\
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>

     active environment : None
       user config file : D:\Users\MyUserName\.condarc
 populated config files :
          conda version : 4.5.4
    conda-build version : 3.10.5
         python version : 2.7.15.final.0
       base environment : D:\Anaconda2  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/win-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/win-64
                          https://repo.anaconda.com/pkgs/pro/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : D:\Anaconda2\pkgs
                          D:\Users\MyUserName\AppData\Local\conda\conda\pkgs
       envs directories : D:\Anaconda2\envs
                          D:\Users\MyUserName\AppData\Local\conda\conda\envs
                          D:\Users\MyUserName\.conda\envs
               platform : win-64
             user-agent : conda/4.5.4 requests/2.18.4 CPython/2.7.15 Windows/10 Windows/10.0.17134
          administrator : False
             netrc file : None
           offline mode : False


An unexpected error has occurred. Conda has prepared the above report.
If submitted, this report will be used by core maintainers to improve
future releases of conda.
Would you like conda to send this report to the core maintainers?
[y/N]:

```

##### `conda list --show-channel-urls`

```

```

**Comment by sgrossberndt** [comment]
`D:\Users\MyUserName\.condarc` contained several NUL bytes. After deleting directories `D:\Users\MyUserName\.anaconda`, `D:\Users\MyUserName\.conda` and file `D:\Users\MyUserName\.condarc` and startup works again
