### ISSUE TITLE
segmentation fault - sparse eigenvalue solver - openblas

### ISSUE THREAD

**Issue by ajgpitch** [ContinuumIO/anaconda-issues#9500]
### Actual Behavior

Segmentation fault when running scipy linalg.eigs with sparse complex matrix when using the nomkl scipy version, that is using openblas.
Problem does not occur with mkl version

### Expected Behavior

Should return eigenvalues and eigenvectors

### Steps to Reproduce

```
conda create -n sp_eigs_test python=3 nomkl numpy scipy
python

import numpy as np
import scipy.sparse as sparse
from scipy.sparse import linalg

mat = np.array([[1,1j,1+1j],
                [-1j, 2, 0],
                [1-1j, 0, 3]])
print(np.linalg.eig(mat)[0])
print(linalg.eigs(sparse.csr_matrix(mat, dtype=complex), 1))
```

##### Anaconda or Miniconda version:
anaconda                  4.4.0               np112py36_0

##### Operating System:
Linux Mint 17 Cinnamon 64-bit
Also fails on Travis CI

##### `conda info`

```
Current conda install:

               platform : linux-64
          conda version : 4.3.30
       conda is private : False
      conda-env version : 4.3.30
    conda-build version : 2.1.6
         python version : 3.6.1.final.0
       requests version : 2.14.2
       root environment : /home/agp1/anaconda3  (writable)
    default environment : /home/agp1/anaconda3/envs/sp_eigs_test
       envs directories : /home/agp1/anaconda3/envs
                          /home/agp1/.conda/envs
          package cache : /home/agp1/anaconda3/pkgs
                          /home/agp1/.conda/pkgs
           channel URLs : https://repo.continuum.io/pkgs/main/linux-64
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/linux-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
            config file : /home/agp1/.condarc
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.30 requests/2.14.2 CPython/3.6.1 Linux/3.13.0-24-generic debian/jessie/sid glibc/2.19    
                UID:GID : 11310:11310

```

##### `conda list --show-channel-urls`

```
blas                      1.0                         mkl    defaults
ca-certificates           2018.03.07                    0    defaults
certifi                   2018.4.16                py36_0    defaults
intel-openmp              2018.0.0                      8    defaults
libedit                   3.1.20170329         h6b74fdf_2    defaults
libffi                    3.2.1                hd88cf55_4    defaults
libgcc-ng                 7.2.0                hdf63c60_3    defaults
libgfortran-ng            7.2.0                hdf63c60_3    defaults
libopenblas               0.2.20               h9ac9557_4    defaults
libstdcxx-ng              7.2.0                hdf63c60_3    defaults
mkl                       2018.0.2                      1    defaults
mkl_fft                   1.0.1            py36h3010b51_0    defaults
mkl_random                1.0.1            py36h629b387_0    defaults
ncurses                   6.1                  hf484d3e_0    defaults
nomkl                     2.0                           0    defaults
numpy                     1.14.3           py36hcd700cb_1    defaults
numpy-base                1.14.3           py36h9be14a7_1    defaults
openssl                   1.0.2o               h20670df_0    defaults
pip                       10.0.1                   py36_0    defaults
python                    3.6.5                hc3d631a_2    defaults
readline                  7.0                  ha6073c6_4    defaults
scipy                     1.1.0           py36_nomklh9d22d0a_0  [nomkl]  defaults
setuptools                39.2.0                   py36_0    defaults
sqlite                    3.23.1               he433501_0    defaults
tk                        8.6.7                hc745277_3    defaults
wheel                     0.31.1                   py36_0    defaults
xz                        5.2.4                h14c3975_4    defaults
zlib                      1.2.11               ha838bed_2    defaults
```

This issue also reports the same problem
https://github.com/scipy/scipy/issues/7667
Claims it is not scipy related.

**Comment by stuartarchibald** [comment]
I think this might be because although nomkl is requested MKL is in use.
```
gdb -ex r -ex bt --args python example.py
```
gives:
```
Program received signal SIGSEGV, Segmentation fault.
0x00007fffeb12d0dc in zdotc_ ()
   from <path>/lib/python3.6/site-packages/mkl_fft/../../../libmkl_intel_lp64.so
#0  0x00007fffeb12d0dc in zdotc_ ()
   from <path>/lib/python3.6/site-packages/mkl_fft/../../../libmkl_intel_lp64.so
#1  0x00007fffd7039852 in zneupd (rvec=.TRUE., howmny='A', select=..., d=..., z=..., ldz=3, sigma=(0,0), workev=..., bmat='I', 
    n=3, which='LM', nev=1, tol=1.1102230246251565e-16, resid=..., ncv=3, v=..., ldv=3, iparam=..., ipntr=..., workd=..., 
    workl=..., lworkl=45, rwork=..., info=0, _howmny=1, _bmat=1, _which=2)
    at scipy/sparse/linalg/eigen/arpack/ARPACK/SRC/zneupd.f:735
#2  0x00007fffd7032819 in f2py_rout__arpack_zneupd ()
   from <path>/lib/python3.6/site-packages/scipy/sparse/linalg/eigen/arpack/_arpack.cpython-36m-x86_64-linux-gnu.so
```

**Comment by msarahan** [comment]
I have uploaded new numpy and openblas packages that should fix the metadata problems that lead to this state.  Please ping me if you have further issues.  I will need to do the same for other packages, such as scipy, scikit-learn, and possibly numexpr.  I'll get to those as time allows, but I hope this update will fix you right now.

**Comment by ajgpitch** [comment]
Our spare eigs Travis tests are now passing. So, I think this means it must be fixed.
@msarahan Thank you so much for your speedy and effective action.
