### ISSUE TITLE
Unable to open anaconda

### ISSUE THREAD

**Issue by anusha12xy** [ContinuumIO/anaconda-issues#9503]
### Actual Behavior

I am trying to open the anaconda navigator but I am getting an error in the browser :

Main Error
byte indices must be integers or slices, not str

Traceback

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\anaconda_navigator\exceptions.py", line 75, in exception_handler
    return_value = func(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 115, in start_app
    window = run_app(splash)
  File "C:\ProgramData\Anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 58, in run_app
    window = MainWindow(splash=splash)
  File "C:\ProgramData\Anaconda3\lib\site-packages\anaconda_navigator\widgets\main_window.py", line 160, in __init__
    self.api = AnacondaAPI()
  File "C:\ProgramData\Anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 1205, in AnacondaAPI
    ANACONDA_API = _AnacondaAPI()
  File "C:\ProgramData\Anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 65, in __init__
    self._conda_api = CondaAPI()
  File "C:\ProgramData\Anaconda3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 1622, in CondaAPI
    CONDA_API = _CondaAPI()
  File "C:\ProgramData\Anaconda3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 340, in __init__
    self.set_conda_prefix()
  File "C:\ProgramData\Anaconda3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 489, in set_conda_prefix
    self.ROOT_PREFIX = info['root_prefix']
TypeError: byte indices must be integers or slices, not str

**Comment by anusha12xy** [comment]
@goanpeca I have made the requested changes, can you have a look now.. 
I don't know how to change the status from close to open

**Comment by goanpeca** [comment]
You still need to provide

```
conda list --show-channel-urls
```

Try opening the Anaconda Prompt and running

```
anaconda-navigator
```

**Comment by anusha12xy** [comment]
with Anaconda prompt I am getting a similar error, I will update the conda list in post

**Comment by goanpeca** [comment]
@anusha12xy you have an old version of navigator running not compatible with lates conda. Please update it

Open a terminal (on Linux or Mac) or the Anaconda Command Prompt (on windows)
and type:

```
conda update conda
conda update anaconda-navigator
conda update navigator-updater
```

**Comment by anusha12xy** [comment]
One more error 
'''
'conda' is not recognized as an internal or external command,
operable program or batch file.
'''
