### ISSUE TITLE
Anaconda navigator doesn't launch  

### ISSUE THREAD

**Issue by codezero-01** [ContinuumIO/anaconda-issues#9509]
i am on Ubuntu 18.04 LTS
upon launching anaconda-navigator i get this message 

Failed to write user configuration file.
Please submit a bug report.
Traceback (most recent call last):
  File "/home/vijay/anaconda3/lib/python3.6/site-packages/anaconda_navigator/config/user.py", line 122, in _save
    _write_file(fname)
  File "/home/vijay/anaconda3/lib/python3.6/site-packages/anaconda_navigator/config/user.py", line 118, in _write_file
    with open(fname, 'w', encoding='utf-8') as configfile:
FileNotFoundError: [Errno 2] No such file or directory: '/home/vijay/.anaconda/navigator/anaconda-navigator.ini'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/vijay/anaconda3/bin/anaconda-navigator", line 11, in <module>
    sys.exit(main())
  File "/home/vijay/anaconda3/lib/python3.6/site-packages/anaconda_navigator/app/main.py", line 99, in main
    from anaconda_navigator.utils.logs import clean_logs
  File "/home/vijay/anaconda3/lib/python3.6/site-packages/anaconda_navigator/utils/logs.py", line 18, in <module>
    from anaconda_navigator.config import (LOG_FILENAME, LOG_FOLDER,
  File "/home/vijay/anaconda3/lib/python3.6/site-packages/anaconda_navigator/config/__init__.py", line 27, in <module>
    from anaconda_navigator.config.main import CONF
  File "/home/vijay/anaconda3/lib/python3.6/site-packages/anaconda_navigator/config/main.py", line 67, in <module>
    raw_mode=True,
  File "/home/vijay/anaconda3/lib/python3.6/site-packages/anaconda_navigator/config/user.py", line 222, in __init__
    old_ver = self.get_version(version)
  File "/home/vijay/anaconda3/lib/python3.6/site-packages/anaconda_navigator/config/user.py", line 261, in get_version
    return self.get(self.DEFAULT_SECTION_NAME, 'version', version)
  File "/home/vijay/anaconda3/lib/python3.6/site-packages/anaconda_navigator/config/user.py", line 392, in get
    self.set(section, option, default)
  File "/home/vijay/anaconda3/lib/python3.6/site-packages/anaconda_navigator/config/user.py", line 455, in set
    self._save()
  File "/home/vijay/anaconda3/lib/python3.6/site-packages/anaconda_navigator/config/user.py", line 132, in _save
    raise (e)
  File "/home/vijay/anaconda3/lib/python3.6/site-packages/anaconda_navigator/config/user.py", line 128, in _save
    _write_file(fname)
  File "/home/vijay/anaconda3/lib/python3.6/site-packages/anaconda_navigator/config/user.py", line 118, in _write_file
    with open(fname, 'w', encoding='utf-8') as configfile:
FileNotFoundError: [Errno 2] No such file or directory: '/home/vijay/.anaconda/navigator/anaconda-navigator.ini'

I tried this 
$ conda update conda
$ conda update anaconda-navigator
$ conda update navigator-updater            and still get the same message .

I've  also tried resetting anaconda-navigator 
$ anaconda-navigator --reset 

then i got this message

Anaconda Navigator configuration reset...

Failed to write user configuration file.
Please submit a bug report.
Traceback (most recent call last):
  File "/home/vijay/anaconda3/lib/python3.6/site-packages/anaconda_navigator/config/user.py", line 122, in _save
    _write_file(fname)
  File "/home/vijay/anaconda3/lib/python3.6/site-packages/anaconda_navigator/config/user.py", line 118, in _write_file
    with open(fname, 'w', encoding='utf-8') as configfile:
FileNotFoundError: [Errno 2] No such file or directory: '/home/vijay/.anaconda/navigator/anaconda-navigator.ini'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/vijay/anaconda3/bin/anaconda-navigator", line 11, in <module>
    sys.exit(main())
  File "/home/vijay/anaconda3/lib/python3.6/site-packages/anaconda_navigator/app/main.py", line 75, in main
    from anaconda_navigator.config import CONF_PATH
  File "/home/vijay/anaconda3/lib/python3.6/site-packages/anaconda_navigator/config/__init__.py", line 27, in <module>
    from anaconda_navigator.config.main import CONF
  File "/home/vijay/anaconda3/lib/python3.6/site-packages/anaconda_navigator/config/main.py", line 67, in <module>
    raw_mode=True,
  File "/home/vijay/anaconda3/lib/python3.6/site-packages/anaconda_navigator/config/user.py", line 222, in __init__
    old_ver = self.get_version(version)
  File "/home/vijay/anaconda3/lib/python3.6/site-packages/anaconda_navigator/config/user.py", line 261, in get_version
    return self.get(self.DEFAULT_SECTION_NAME, 'version', version)
  File "/home/vijay/anaconda3/lib/python3.6/site-packages/anaconda_navigator/config/user.py", line 392, in get
    self.set(section, option, default)
  File "/home/vijay/anaconda3/lib/python3.6/site-packages/anaconda_navigator/config/user.py", line 455, in set
    self._save()
  File "/home/vijay/anaconda3/lib/python3.6/site-packages/anaconda_navigator/config/user.py", line 132, in _save
    raise (e)
  File "/home/vijay/anaconda3/lib/python3.6/site-packages/anaconda_navigator/config/user.py", line 128, in _save
    _write_file(fname)
  File "/home/vijay/anaconda3/lib/python3.6/site-packages/anaconda_navigator/config/user.py", line 118, in _write_file
    with open(fname, 'w', encoding='utf-8') as configfile:
FileNotFoundError: [Errno 2] No such file or directory: '/home/vijay/.anaconda/navigator/anaconda-navigator.ini'

**Comment by FrancisChung** [comment]
I had the same issue. I fixed it by completely removing the anaconda & the hidden anaconda directory and started installing from scratch again. 2nd time seems to be the lucky charm.

https://conda.io/docs/user-guide/install/linux.html?highlight=uninstall
