### ISSUE TITLE
navigator and all comand can't run

### ISSUE THREAD

**Issue by wudishidove** [ContinuumIO/anaconda-issues#9510]
## Navigator Error

An unexpected error occurred on Navigator start-up
Report

Please report this issue in the anaconda issue tracker
## Main Error

byte indices must be integers or slices, not str

## Traceback

Traceback (most recent call last):
  File "D:\program\anaconda3\lib\site-packages\anaconda_navigator\exceptions.py", line 75, in exception_handler
    return_value = func(*args, **kwargs)
  File "D:\program\anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 138, in start_app
    window = run_app(splash)
  File "D:\program\anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 64, in run_app
    window = MainWindow(splash=splash, tab_project=False)
  File "D:\program\anaconda3\lib\site-packages\anaconda_navigator\widgets\main_window.py", line 163, in __init__
    self.api = AnacondaAPI()
  File "D:\program\anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 2086, in AnacondaAPI
    ANACONDA_API = _AnacondaAPI()
  File "D:\program\anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 89, in __init__
    self._conda_api = CondaAPI()
  File "D:\program\anaconda3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 1699, in CondaAPI
    CONDA_API = _CondaAPI()
  File "D:\program\anaconda3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 347, in __init__
    self.set_conda_prefix()
  File "D:\program\anaconda3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 506, in set_conda_prefix
    self.ROOT_PREFIX = info['root_prefix']
TypeError: byte indices must be integers or slices, not str

**Comment by goanpeca** [comment]
@wudishidove please open the Anaconda Prompt and update navigator and other packages

```
conda update conda
conda update --all
```
