### ISSUE TITLE
Launching anaconda, conda, spyder

### ISSUE THREAD

**Issue by GeoLL** [ContinuumIO/anaconda-issues#9512]
I an on Windows 10, 64-bit
Upon launching anaconda-navigator, conda or spyder i get this message:
this happend with the anaconda version Anaconda3-5.2.0-Windows-x86_64 but also with 5.1.

## Navigator Error

An unexpected error occurred on Navigator start-up
Report

Please report this issue in the anaconda issue tracker
Main Error

expected str, bytes or os.PathLike object, not NoneType

# Traceback

Traceback (most recent call last):
  File "C:\Users\xx\AppData\Roaming\Anaconda\lib\site-packages\anaconda_navigator\exceptions.py", line 75, in exception_handler
    return_value = func(*args, **kwargs)
  File "C:\Users\xx\AppData\Roaming\Anaconda\lib\site-packages\anaconda_navigator\app\start.py", line 150, in start_app
    window = run_app(splash)
  File "C:\Users\xx\AppData\Roaming\Anaconda\lib\site-packages\anaconda_navigator\app\start.py", line 65, in run_app
    window = MainWindow(splash=splash, tab_project=False)
  File "C:\Users\xx\AppData\Roaming\Anaconda\lib\site-packages\anaconda_navigator\widgets\main_window.py", line 163, in __init__
    self.api = AnacondaAPI()
  File "C:\Users\xx\AppData\Roaming\Anaconda\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 2185, in AnacondaAPI
    ANACONDA_API = _AnacondaAPI()
  File "C:\Users\xx\AppData\Roaming\Anaconda\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 89, in __init__
    self._conda_api = CondaAPI()
  File "C:\Users\xx\AppData\Roaming\Anaconda\lib\site-packages\anaconda_navigator\api\conda_api.py", line 1714, in CondaAPI
    CONDA_API = _CondaAPI()
  File "C:\Users\xx\AppData\Roaming\Anaconda\lib\site-packages\anaconda_navigator\api\conda_api.py", line 353, in __init__
    self.sys_rc_path = join(self.ROOT_PREFIX, '.condarc')
  File "C:\Users\xx\AppData\Roaming\Anaconda\lib\ntpath.py", line 76, in join
    path = os.fspath(path)
TypeError: expected str, bytes or os.PathLike object, not NoneType

**Comment by goanpeca** [comment]
Please provide the information requested on the issue template.



### Actual Behavior



### Expected Behavior



### Steps to Reproduce




##### Anaconda or Miniconda version:

##### Operating System:

##### `conda info`

```

```

##### `conda list --show-channel-urls`

```

```

**Comment by GeoLL** [comment]
Actual Behavior
Doppelclick on Anaconda Navigator to open
Open conda promt mit admin-right
Doppelclick von Spyder to open
... all produce the Traceback posted above

Expected Behavior
open the above programs
Steps to Reproduce
try to open all programs
Anaconda or Miniconda version:
anaconda 5.2 (but whas also not working with 5.1)
Operating System:
Windows 10 (64-Bit)
is not possible to open conda, so not possible to add any commands (conda info etc.)

**Comment by GeoLL** [comment]
May I ask you why you did close this ticket?
