### ISSUE TITLE
Windows 10 MatPlotlib "ImportError: DLL load failed: The specified procedure could not be found." with 32 bit Anaconda in otherwise empty venv

### ISSUE THREAD

**Issue by FredDavison** [ContinuumIO/anaconda-issues#9516]
Very similar to #6689

### Actual Behavior
`import matplot.pyplot` fails with `ImportError: DLL load failed: The specified procedure could not be found.` when called from an Anaconda 32 bit environment on Windows 10.

### Full Traceback
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Anaconda3\envs\test_mpl_32\lib\site-packages\matplotlib\pyplot.py", line 31, in <module>
    import matplotlib.colorbar
  File "C:\Anaconda3\envs\test_mpl_32\lib\site-packages\matplotlib\colorbar.py", line 36, in <module>
    import matplotlib.contour as contour
  File "C:\Anaconda3\envs\test_mpl_32\lib\site-packages\matplotlib\contour.py", line 20, in <module>
    import matplotlib.font_manager as font_manager
  File "C:\Anaconda3\envs\test_mpl_32\lib\site-packages\matplotlib\font_manager.py", line 55, in <module>
    from matplotlib import afm, cbook, ft2font, rcParams, get_cachedir
ImportError: DLL load failed: The specified procedure could not be found.
```

### Steps to Reproduce
- force 32 bit Python when creating env `set CONDA_FORCE_32BIT=1`
- `conda create -y --no-default-packages --name mpl32test python=3.6`
- `conda activate mpl32test`
- `conda install matplotlib`
- run Python interpreter and try `import matplotlib.pyplot` or, more specifically because I think this is the problematic module: `from matplotlib import ft2font`

I followed the same steps but without forcing 32 bit and there was no error.  

##### Operating System:
Windows 10

##### `conda info`

```
    active environment : test_mpl_32
    active env location : C:\Anaconda3\envs\test_mpl_32
            shell level : 1
       user config file : C:\Users\fda\.condarc
 populated config files : C:\Users\fda\.condarc
          conda version : 4.5.4
    conda-build version : 3.0.22
         python version : 3.6.2.final.0
       base environment : C:\Anaconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/win-32
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/win-32
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/win-32
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/win-32
                          https://repo.anaconda.com/pkgs/pro/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-32
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\Anaconda3\pkgs32
                          C:\Users\fda\AppData\Local\conda\conda\pkgs32
       envs directories : C:\Anaconda3\envs
                          C:\Users\fda\AppData\Local\conda\conda\envs
                          C:\Users\fda\.conda\envs
               platform : win-32
             user-agent : conda/4.5.4 requests/2.18.4 CPython/3.6.2 Windows/10 Windows/10.0.15063
          administrator : False
             netrc file : None
           offline mode : False
```

##### `conda list --show-channel-urls`

```
blas                      1.0                         mkl    defaults
ca-certificates           2018.03.07                    0    defaults
certifi                   2018.4.16                py36_0    defaults
cycler                    0.10.0           py36hd299a41_0    defaults
freetype                  2.8                  h0224ed4_1    defaults
icc_rt                    2017.0.4             h97af966_0    defaults
icu                       58.2                 h3fcc66b_1    defaults
intel-openmp              2018.0.0                      8    defaults
jpeg                      9b                   he27b436_2    defaults
kiwisolver                1.0.1            py36h7de1d16_0    defaults
libpng                    1.6.34               h79bbb47_0    defaults
matplotlib                2.2.2            py36h153e9ff_1    defaults
mkl                       2018.0.2                      1    defaults
mkl_fft                   1.0.1            py36h452e1ab_0    defaults
mkl_random                1.0.1            py36h9258bd6_0    defaults
numpy                     1.14.3           py36h9fa60d3_1    defaults
numpy-base                1.14.3           py36h555522e_1    defaults
openssl                   1.0.2o               h8ea7d77_0    defaults
pip                       10.0.1                   py36_0    defaults
pyparsing                 2.2.0            py36h9ef7486_1    defaults
pyqt                      5.9.2            py36h1aa27d4_0    defaults
python                    3.6.5                h0c2934d_0    defaults
python-dateutil           2.7.3                    py36_0    defaults
pytz                      2018.4                   py36_0    defaults
qt                        5.9.5            vc14he4a7d60_0    defaults
setuptools                39.2.0                   py36_0    defaults
sip                       4.19.8           py36h6538335_0    defaults
six                       1.11.0           py36h7f2c006_1    defaults
sqlite                    3.23.1               h35aae40_0    defaults
tornado                   5.0.2                    py36_0    defaults
vc                        14                   h0510ff6_3    defaults
vs2015_runtime            14.0.25123                    3    defaults
wheel                     0.31.1                   py36_0    defaults
wincertstore              0.2              py36hcdd9a18_0    defaults
zlib                      1.2.11               hbb18732_2    defaults
```

**Comment by msarahan** [comment]
CONDA_FORCE32BIT was a developer flag for building packages only.  It is not supported for creating user environments.  Please use a 32-bit windows installer if you need to run a 32-bit distribution.
