### ISSUE TITLE
Import h5py has two errors: loading DDL error & cannot import name _errors

### ISSUE THREAD

**Issue by Skycocoo** [ContinuumIO/anaconda-issues#9523]
### Actual Behavior

In both normal CMD and Anaconda Prompt (and in both python and ipython):
```
In [1]: import h5py
-------------------------------------------------
ImportError     Traceback (most recent call last)
<ipython-input-1-c9f0b8c65221> in <module>()
----> 1 import h5py

C:\Users\[]\Anaconda2\lib\site-packages\h5py\__init__.py in <module>()
     34 _errors.silence_errors()
     35
---> 36 from ._conv import register_converters as _register_converters
     37 _register_converters()
     38

h5py\h5r.pxd in init h5py._conv()

h5py\_objects.pxd in init h5py.h5r()

h5py\_objects.pyx in init h5py._objects()

ImportError: DLL load failed

In [2]: import h5py
-------------------------------------------------
ImportError     Traceback (most recent call last)
<ipython-input-2-c9f0b8c65221> in <module>()
----> 1 import h5py

C:\Users\[]\Anaconda2\lib\site-packages\h5py\__init__.py in <module>()
     24 # We tried working around this by using "package_dir" but that breaks Cython.
     25 try:
---> 26     from . import _errors
     27 except ImportError:
     28     import os.path as _op

ImportError: cannot import name _errors
```

The strange part is, the first import should fail, but the failure behavior changes for the second attempt. The error message after the first attempt stays to be "cannot import name _errors". 

I dont know whether its something todo with my machine, or it is a common behavior for others.
 

### Expected Behavior

import h5py works normally

### Steps to Reproduce

install newly downloaded Anaconda 2.7 for Windows 64 bit
```
conda update anaconda
python
import h5py
import h5py
```

##### Anaconda or Miniconda version:
4.5.4

##### Operating System:
Windows 10

##### `conda info`

```
    active environment : base
    active env location : C:\Users\[]\Anaconda2
            shell level : 1
       user config file : C:\Users\[]\.condarc
 populated config files :
          conda version : 4.5.4
    conda-build version : 3.10.5
         python version : 2.7.15.final.0
       base environment : C:\Users\[]\Anaconda2  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/win-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/win-64
                          https://repo.anaconda.com/pkgs/pro/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\Users\[]\Anaconda2\pkgs
                          C:\Users\[]\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\[]\Anaconda2\envs
                          C:\Users\[]\AppData\Local\conda\conda\envs
                          C:\Users\[]\.conda\envs
               platform : win-64
             user-agent : conda/4.5.4 requests/2.18.4 CPython/2.7.15 Windows/10 Windows/10.0.16299
          administrator : False
             netrc file : None
           offline mode : False

```

##### `conda list --show-channel-urls`

```
# packages in environment at C:\Users\[]\Anaconda2:
#
# Name                    Version                   Build  Channel
_ipyw_jlab_nb_ext_conf    0.1.0            py27h9111531_0    defaults
alabaster                 0.7.10           py27h2cab13d_0    defaults
anaconda                  5.2.0                    py27_3    defaults
anaconda-client           1.6.14                   py27_0    defaults
anaconda-navigator        1.8.7                    py27_0    defaults
anaconda-project          0.8.2            py27he89e3ca_0    defaults
asn1crypto                0.24.0                   py27_0    defaults
astroid                   1.6.3                    py27_0    defaults
astropy                   2.0.6            py27hc997a72_1    defaults
attrs                     18.1.0                   py27_0    defaults
babel                     2.5.3                    py27_0    defaults
backports                 1.0              py27h6492d98_1    defaults
backports.functools_lru_cache 1.5                      py27_1    defaults
backports.shutil_get_terminal_size 1.0.0            py27h1657125_2    defaults
backports.shutil_which    3.5.1                    py27_2    defaults
backports_abc             0.5              py27h0ec6b72_0    defaults
beautifulsoup4            4.6.0            py27hc287451_1    defaults
bitarray                  0.8.1            py27h0c8e037_1    defaults
bkcharts                  0.2              py27h92b6de3_0    defaults
blas                      1.0                         mkl    defaults
blaze                     0.11.3           py27h97e5449_0    defaults
bleach                    2.1.3                    py27_0    defaults
blosc                     1.14.3               h95ae18b_0    defaults
bokeh                     0.12.16                  py27_0    defaults
boto                      2.48.0           py27h1ccb131_1    defaults
bottleneck                1.2.1            py27hde90680_0    defaults
bzip2                     1.0.6                h0c8e037_5    defaults
ca-certificates           2018.03.07                    0    defaults
cdecimal                  2.3              py27h0c8e037_3    defaults
certifi                   2018.4.16                py27_0    defaults
cffi                      1.11.5           py27hdb016f4_0    defaults
chardet                   3.0.4            py27h56c3b73_1    defaults
click                     6.7              py27hb6defca_0    defaults
cloudpickle               0.5.3                    py27_0    defaults
clyent                    1.2.2            py27h4424948_1    defaults
colorama                  0.3.9            py27hdfe4ae1_0    defaults
comtypes                  1.1.4                    py27_0    defaults
conda                     4.5.4                    py27_0    defaults
conda-build               3.10.5                   py27_0    defaults
conda-env                 2.6.0                h36134e3_1    defaults
conda-verify              2.0.0            py27h5217224_0    defaults
configparser              3.5.0            py27h2fa79a8_0    defaults
console_shortcut          0.1.1                h6bb2dd7_3    defaults
contextlib2               0.5.5            py27h42efda5_0    defaults
cryptography              2.2.2            py27h0c8e037_0    defaults
curl                      7.60.0               h7a46e7a_0    defaults
cycler                    0.10.0           py27h59acbbf_0    defaults
cython                    0.28.2           py27h0c8e037_0    defaults
cytoolz                   0.9.0.1          py27h0c8e037_0    defaults
dask                      0.17.5                   py27_0    defaults
dask-core                 0.17.5                   py27_0    defaults
datashape                 0.5.4            py27h3d6e61b_0    defaults
decorator                 4.3.0                    py27_0    defaults
distributed               1.21.8                   py27_0    defaults
docutils                  0.14             py27h8652d09_0    defaults
entrypoints               0.2.3            py27h0271f2b_2    defaults
enum34                    1.1.6            py27h2aa175b_1    defaults
et_xmlfile                1.0.1            py27h1de5d23_0    defaults
fastcache                 1.0.2            py27h0c8e037_2    defaults
filelock                  3.0.4                    py27_0    defaults
flask                     1.0.2                    py27_1    defaults
flask-cors                3.0.4                    py27_0    defaults
freetype                  2.8                  hea645e0_1    defaults
funcsigs                  1.0.2            py27h8885ae1_0    defaults
functools32               3.2.3.2          py27h0cdbcdb_1    defaults
futures                   3.2.0            py27h8b2aecd_0    defaults
get_terminal_size         1.0.0                h38e98db_0    defaults
gevent                    1.3.0            py27h0c8e037_0    defaults
glob2                     0.6              py27hd4eee8c_0    defaults
greenlet                  0.4.13           py27h0c8e037_0    defaults
grin                      1.2.1                    py27_4    defaults
h5py                      2.7.1            py27h5f1a774_2    defaults
hdf5                      1.10.2               h4b43f98_1    defaults
heapdict                  1.0.0                    py27_2    defaults
html5lib                  1.0.1            py27h5a33001_0    defaults
icc_rt                    2017.0.4             h97af966_0    defaults
icu                       58.2                 h2aa20d9_1    defaults
idna                      2.6              py27h1ea29d3_1    defaults
imageio                   2.3.0                    py27_0    defaults
imagesize                 1.0.0                    py27_0    defaults
intel-openmp              2018.0.0                      8    defaults
ipaddress                 1.0.22                   py27_0    defaults
ipykernel                 4.8.2                    py27_0    defaults
ipython                   5.7.0                    py27_0    defaults
ipython_genutils          0.2.0            py27hbe997df_0    defaults
ipywidgets                7.2.1                    py27_0    defaults
isort                     4.3.4                    py27_0    defaults
itsdangerous              0.24             py27hcf63135_1    defaults
jdcal                     1.4                      py27_0    defaults
jedi                      0.12.0                   py27_1    defaults
jinja2                    2.10             py27hba1794b_0    defaults
jpeg                      9b                   ha175dff_2    defaults
jsonschema                2.6.0            py27haaf3834_0    defaults
jupyter                   1.0.0                    py27_4    defaults
jupyter_client            5.2.3                    py27_0    defaults
jupyter_console           5.2.0            py27h6ed736b_1    defaults
jupyter_core              4.4.0            py27h1619e65_0    defaults
jupyterlab                0.32.1                   py27_0    defaults
jupyterlab_launcher       0.10.5                   py27_0    defaults
kiwisolver                1.0.1            py27h9815e84_0    defaults
lazy-object-proxy         1.3.1            py27ha5c8080_0    defaults
libcurl                   7.60.0               h0990ea7_0    defaults
libiconv                  1.15                 hda2e4ec_7    defaults
libpng                    1.6.34               h325896a_0    defaults
libsodium                 1.0.16               h8b3e59e_0    defaults
libssh2                   1.8.0                h77a7533_4    defaults
libtiff                   4.0.9                h1c3b264_1    defaults
libxml2                   2.9.8                hdfd6920_1    defaults
libxslt                   1.1.32               h89dfad8_0    defaults
llvmlite                  0.23.1           py27hf224fbf_0    defaults
locket                    0.2.0            py27h1ca288a_1    defaults
lxml                      4.2.1            py27h803002f_0    defaults
lzo                       2.10                 h0bb7fe3_2    defaults
m2w64-gcc-libgfortran     5.3.0                         6    defaults
m2w64-gcc-libs            5.3.0                         7    defaults
m2w64-gcc-libs-core       5.3.0                         7    defaults
m2w64-gmp                 6.1.0                         2    defaults
m2w64-libwinpthread-git   5.0.0.4634.697f757               2    defaults
markupsafe                1.0              py27h9d4480d_1    defaults
matplotlib                2.2.2            py27h8803d4e_1    defaults
mccabe                    0.6.1            py27hde0bf6e_1    defaults
menuinst                  1.4.14           py27h0c8e037_0    defaults
mistune                   0.8.3            py27h0c8e037_1    defaults
mkl                       2018.0.2                      1    defaults
mkl-service               1.1.2            py27h3c6b6b0_4    defaults
mkl_fft                   1.0.1            py27hc997a72_0    defaults
more-itertools            4.1.0                    py27_0    defaults
mpmath                    1.0.0            py27h0d59bc2_2    defaults
msgpack-python            0.5.6            py27hdc96acc_0    defaults
msys2-conda-epoch         20160418                      1    defaults
multipledispatch          0.5.0                    py27_0    defaults
navigator-updater         0.2.1                    py27_0    defaults
nbconvert                 5.3.1            py27h7a573cf_0    defaults
nbformat                  4.4.0            py27hf49b375_0    defaults
networkx                  2.1                      py27_0    defaults
nltk                      3.3.0                    py27_0    defaults
nose                      1.3.7            py27h84c72c6_2    defaults
notebook                  5.5.0                    py27_0    defaults
numba                     0.38.0           py27h39f3610_0    defaults
numexpr                   2.6.5            py27h3b259a0_0    defaults
numpy                     1.14.3           py27h911edcf_1    defaults
numpy-base                1.14.3           py27h917549b_1    defaults
numpydoc                  0.8.0                    py27_0    defaults
odo                       0.5.1            py27h64810b2_0    defaults
olefile                   0.45.1                   py27_0    defaults
opencv                    2.4.11                   py27_1    menpo
openpyxl                  2.5.3                    py27_0    defaults
openssl                   1.0.2o               h2c51139_0    defaults
packaging                 17.1                     py27_0    defaults
pandas                    0.23.0           py27h39f3610_0    defaults
pandoc                    1.19.2.1             hb2460c7_1    defaults
pandocfilters             1.4.2            py27h76461d3_1    defaults
parso                     0.2.0                    py27_0    defaults
partd                     0.3.8            py27h1e0692f_0    defaults
path.py                   11.0.1                   py27_0    defaults
pathlib2                  2.3.2                    py27_0    defaults
patsy                     0.5.0                    py27_0    defaults
pep8                      1.7.1                    py27_0    defaults
pickleshare               0.7.4            py27hb5f6335_0    defaults
pillow                    5.1.0            py27h901f87c_0    defaults
pip                       10.0.1                   py27_0    defaults
pkginfo                   1.4.2                    py27_1    defaults
pluggy                    0.6.0            py27h89dc50b_0    defaults
ply                       3.11                     py27_0    defaults
prompt_toolkit            1.0.15           py27h3a8ec6a_0    defaults
psutil                    5.4.5            py27h0c8e037_0    defaults
py                        1.5.3                    py27_0    defaults
pycodestyle               2.4.0                    py27_0    defaults
pycosat                   0.6.3            py27hcd410c5_0    defaults
pycparser                 2.18             py27hb43d16c_1    defaults
pycrypto                  2.6.1            py27h0c8e037_8    defaults
pycurl                    7.43.0.1         py27hc64555f_0    defaults
pyflakes                  1.6.0            py27h34e7826_0    defaults
pygame                    1.9.2a0                  py27_0    cogsci
pygments                  2.2.0            py27ha50f84f_0    defaults
pylint                    1.8.4                    py27_0    defaults
pyodbc                    4.0.23           py27hc56fc5f_0    defaults
pyopenssl                 18.0.0                   py27_0    defaults
pyparsing                 2.2.0            py27hc7d9fa6_1    defaults
pyqt                      5.6.0            py27h224ed30_5    defaults
pysocks                   1.6.8                    py27_0    defaults
pytables                  3.4.3            py27hdd5b532_1    defaults
pytest                    3.5.1                    py27_0    defaults
python                    2.7.15               he216670_0    defaults
python-dateutil           2.7.3                    py27_0    defaults
pytz                      2018.4                   py27_0    defaults
pywavelets                0.5.2            py27h0dc3f48_0    defaults
pywin32                   223              py27h0c8e037_1    defaults
pywinpty                  0.5.1                    py27_0    defaults
pyyaml                    3.12             py27ha287073_1    defaults
pyzmq                     17.0.0           py27h0c8e037_1    defaults
qt                        5.6.2            vc9hc26998b_12  [vc9]  defaults
qtawesome                 0.4.4            py27h766b13d_0    defaults
qtconsole                 4.3.1            py27h77d40ac_0    defaults
qtpy                      1.4.1                    py27_0    defaults
requests                  2.18.4           py27h3159eba_1    defaults
rope                      0.10.7           py27hb65afb6_0    defaults
ruamel_yaml               0.15.35          py27h0c8e037_1    defaults
scandir                   1.7              py27h0c8e037_0    defaults
scikit-image              0.13.1           py27h0c8e037_1    defaults
scikit-learn              0.19.1           py27he00e316_0    defaults
scipy                     1.1.0            py27ha6b90e7_0    defaults
seaborn                   0.8.1            py27hab56d54_0    defaults
send2trash                1.5.0                    py27_0    defaults
setuptools                39.1.0                   py27_0    defaults
simplegeneric             0.8.1                    py27_2    defaults
singledispatch            3.4.0.3          py27h3f9d112_0    defaults
sip                       4.18.1           py27h5ec1c1a_2    defaults
six                       1.11.0           py27ha5e1701_1    defaults
snappy                    1.1.7                he46498f_3    defaults
snowballstemmer           1.2.1            py27h28d3bf7_0    defaults
sortedcollections         0.6.1                    py27_0    defaults
sortedcontainers          1.5.10                   py27_0    defaults
sphinx                    1.7.4                    py27_0    defaults
sphinxcontrib             1.0              py27h0e2fb95_1    defaults
sphinxcontrib-websupport  1.0.1            py27h0d0f901_1    defaults
spyder                    3.2.8                    py27_0    defaults
sqlalchemy                1.2.7            py27h9dc6b9e_0    defaults
sqlite                    3.23.1               h0f31022_0    defaults
ssl_match_hostname        3.5.0.1          py27hea8a0f4_2    defaults
statsmodels               0.9.0            py27hc997a72_0    defaults
subprocess32              3.5.0            py27h0c8e037_0    defaults
sympy                     1.1.1            py27hde44fae_0    defaults
tblib                     1.3.2            py27h8ae915c_0    defaults
terminado                 0.8.1                    py27_1    defaults
testpath                  0.3.1            py27h1cd488d_0    defaults
tk                        8.6.7                h144d9c4_3    defaults
toolz                     0.9.0                    py27_0    defaults
tornado                   5.0.2                    py27_0    defaults
traitlets                 4.3.2            py27h1b1b3a5_0    defaults
typing                    3.6.4                    py27_0    defaults
unicodecsv                0.14.1           py27h0bf7bb0_0    defaults
urllib3                   1.22             py27hb9f5a07_0    defaults
vc                        9                    h7299396_1    defaults
vs2008_runtime            9.00.30729.1         hfaea7d5_1    defaults
vs2015_runtime            14.0.25123                    3    defaults
wcwidth                   0.1.7            py27hb1a0d82_0    defaults
webencodings              0.5.1            py27h4e224a2_1    defaults
werkzeug                  0.14.1                   py27_0    defaults
wheel                     0.31.1                   py27_0    defaults
widgetsnbextension        3.2.1                    py27_0    defaults
win_inet_pton             1.0.1            py27hf41312a_1    defaults
win_unicode_console       0.5              py27hc037021_0    defaults
wincertstore              0.2              py27hf04cefb_0    defaults
winpty                    0.4.3                         4    defaults
wrapt                     1.10.11          py27hcd2b27d_0    defaults
xlrd                      1.1.0            py27h2b87a7f_1    defaults
xlsxwriter                1.0.4                    py27_0    defaults
xlwings                   0.11.8                   py27_0    defaults
xlwt                      1.3.0            py27h2271735_0    defaults
yaml                      0.1.7                h3e6d941_2    defaults
zeromq                    4.2.5                h907ab29_0    defaults
zict                      0.1.3            py27h0171463_0    defaults
zlib                      1.2.11               hbc2faf4_2    defaults

```

**Comment by nehaljwani** [comment]
@Skycocoo Could you also share the output for the command:
```
set PATH
```
I hope you don't have any conflicting DLLs in your PATH.

**Comment by Skycocoo** [comment]
@nehaljwani 

I tried to make it more readable (its a little bit messy); but I dont think there is conflicting DLLs as far as I know.

```
Path=
C:\ProgramData\Oracle\Java\javapath;
C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v7.0\bin
;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v7.0\libnvvp
;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v7.5\bin
;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v7.5\libnvvp
;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common；F:\caffe_win\v-maxee\caffe\3rdparty\bin；
C:\cygwin64\bin；
C:\Program Files\Java\jdk1.8.0_65\bin；.;
%JA;A_HOME%\jre\bin.;
C:\Program Files\Java\jdk1.8.0_65\bin;
F:\java\android_sdk\tools;
F:\java\android_sdk\platform-tools;
C:\WINDOWS\system32;
C:\WINDOWS;
C:\WINDOWS\System32\Wbem;
C:\WINDOWS\System32\WindowsPowerShell\v1.0\;
C:\Program Files (x86)\Windows Kits\10\Windows Performance Toolkit\;
C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;
C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit\;
D:\nba07\runtime\win64;
D:\nba07\bin;C:\Program Files\VTK 7.1.0\bin;
C:\Program Files\VTK\bin\Lib\site-packages;
C:\Program Files (x86)\Skype\Phone\;
C:\Program Files\Git\cmd;
C:\Users\[]\Anaconda2;
C:\Users\[]\Anaconda2\Scripts;
C:\Users\[]\Anaconda2\Library\bin;
%USERPROFILE%\AppData\Local\Microsoft\WindowsApps;
C:\Users\[]\AppData\Local\Programs\MiKTeX 2.9\miktex\bin\x64\;

PATHEXT=.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC
```

**Comment by nehaljwani** [comment]
@Skycocoo If you strip out everything out of the PATH env var, except:
```
C:\WINDOWS\system32;
C:\WINDOWS;
C:\WINDOWS\System32\Wbem;
C:\Users\[]\Anaconda2;
C:\Users\[]\Anaconda2\Scripts;
C:\Users\[]\Anaconda2\Library\bin;
```
Does the problem still occur?

**Comment by nehaljwani** [comment]
Actually, vtk depends on hdf5, so probably that is bringing in some DLLs, from C:\Program Files\VTK 7.1.0\bin;

**Comment by Skycocoo** [comment]
@nehaljwani 

Yes its still happening 

```
C:\Users\[]>set path
Path=C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\Program Files\Git\cmd;C:\Users\qiuziming\Anaconda2;C:\Users\qiuziming\Anaconda2\Scripts;C:\Users\qiuziming\Anaconda2\Library\bin;
PATHEXT=.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC

C:\Users\[]>python
Python 2.7.15 |Anaconda, Inc.| (default, May  1 2018, 18:37:09) [MSC v.1500 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import h5py
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\[]\Anaconda2\lib\site-packages\h5py\__init__.py", line 36, in <module>
    from ._conv import register_converters as _register_converters
  File "h5py\h5r.pxd", line 21, in init h5py._conv
  File "h5py\_objects.pxd", line 12, in init h5py.h5r
  File "h5py\_objects.pyx", line 1, in init h5py._objects
ImportError: DLL load failed
>>>
```

**Comment by nehaljwani** [comment]
@Skycocoo Could you try running `C:\Users\qiuziming\Anaconda2\python.exe -c 'import h5py'` in DependencyWalker and see where does the DLL load problem occur?

**Comment by Skycocoo** [comment]
@nehaljwani Sorry I searched online but did not find out the way to insert command in [Dependency Walker](http://www.dependencywalker.com/). I opened the ```C:\Users\[]\Anaconda2\python.exe``` without ```-c 'import h5py``` and the loading problems are happening for ```IESHIMS.DLL, NGCRECOVERY.DLL, WPAXHOLDER.DLL``` and all the ```API-MS-WIN-*``` and ```EXT-MS-WIN-*```

**Comment by nehaljwani** [comment]
@Skycocoo Could you dump the entire output that dependency walker shows, when you run python with that import?

**Comment by Skycocoo** [comment]
@nehaljwani  I mean Dependency Walker cannot correctly process the ```C:\Users\[]\Anaconda2\python.exe```; the entire output is too large to dump into here (the file size is ~90M in .txt). The final log of Dependency Walker when trying to open python is:

```

Error: At least one required implicit or forwarded dependency was not found.
Error: At least one module has an unresolved import due to a missing export function in an implicitly dependent module.
Error: Modules with different CPU types were found.
Error: A circular dependency was detected.
Warning: At least one delay-load dependency module was not found.
Warning: At least one module has an unresolved import due to a missing export function in a delay-load dependent module.
```

**Comment by nehaljwani** [comment]
Calling the big shots. @mingwandroid , any ideas?

**Comment by nehaljwani** [comment]
@Skycocoo What's your CPU model?

**Comment by nehaljwani** [comment]
@Skycocoo Could you try compressing the txt file and then upload it here as attachment to a comment?

**Comment by Skycocoo** [comment]
@nehaljwani  CPU model is Intel i5-4200H CPU @ 2.80GHz;  4GB RAM;

The file is far too big so I created a [shared file on google drive](https://drive.google.com/file/d/1gVqHsezG_45MyEVymSaYMo_wzZmoO-RF/view?usp=sharing)

**Comment by nehaljwani** [comment]
The output is too much. I wonder which output you dumped. I don't see any reference to hdf5 or h5py. When the import fails, there is a box at the bottom half where text prints in red color. That output is probably not 90MB is size. Maybe you could try copying that? 

Attaching your first error report as a compressed file.
[python.txt.gz](https://github.com/ContinuumIO/anaconda-issues/files/2073721/python.txt.gz)

**Comment by nehaljwani** [comment]
Basically, you need to open python.exe in dependency walker, then click on profile->Start profiling. Then, in `program arguments`, type: `-c 'import h5py'` and then click okay. Then copy paste the output dumped in the lower section in dependency walker.
![screenshot from 2018-06-06 01-07-17](https://user-images.githubusercontent.com/1779189/40998895-cdf08448-6926-11e8-9b78-2267434ce5e5.png)

**Comment by Skycocoo** [comment]
@nehaljwani  

(Forgot that I can just simply send an image instead of the dreadful file) Dependency Walker cannot successfully open the file, and therefore I cannot profile it (as shown in the image, the ```start profiling``` option is in grey)

![log](https://user-images.githubusercontent.com/22590859/40999970-7f525b28-68da-11e8-8777-efa837c8706a.PNG)

**Comment by Skycocoo** [comment]
@nehaljwani @mingwandroid  Thanks for help! I guess I should just reinstall the OS

**Comment by fbereux** [comment]
I faced a similar issue with Anaconda 2019.07 installed on Windows 10 : 
```
$ ipython
Python 3.7.3 (default, Apr 24 2019, 15:29:51) [MSC v.1915 64 bit (AMD64)]
Type 'copyright', 'credits' or 'license' for more information
IPython 7.6.1 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import h5py
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-c9f0b8c65221> in <module>
----> 1 import h5py

L:\APP-FB\anaconda3\lib\site-packages\h5py\__init__.py in <module>
     24 # We tried working around this by using "package_dir" but that breaks Cy
thon.
     25 try:
---> 26     from . import _errors
     27 except ImportError:
     28     import os.path as _op

ImportError: DLL load failed: %1 n’est pas une application Win32 valide.
```
I found a workaround which may be useful (import tables before importing h5py) : 
```$ ipython
Python 3.7.3 (default, Apr 24 2019, 15:29:51) [MSC v.1915 64 bit (AMD64)]
Type 'copyright', 'credits' or 'license' for more information
IPython 7.6.1 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import tables

In [2]: import h5py

In [3]:
```
