### ISSUE TITLE
Error when launching jupyter

### ISSUE THREAD

**Issue by biographie** [ContinuumIO/anaconda-issues#954]
Hello, I'm running into this error while trying to launch jupyter from navigator. I'm on a mac running OSX 10.11.16

~ » /Users/bio/anaconda/bin/jupyter_mac.command ; exit;
[W 17:36:05.472 NotebookApp] Unrecognized JSON config file version, assuming version 1
Traceback (most recent call last):
File "/Users/bio/anaconda/bin/jupyter-notebook", line 6, in 
sys.exit(notebook.notebookapp.main())
File "/Users/bio/anaconda/lib/python2.7/site-packages/jupyter_core/application.py", line 267, in launch_instance
return super(JupyterApp, cls).launch_instance(argv=argv, *kwargs)
File "/Users/bio/anaconda/lib/python2.7/site-packages/traitlets/config/application.py", line 595, in launch_instance
app.initialize(argv)
File "", line 2, in initialize
File "/Users/bio/anaconda/lib/python2.7/site-packages/traitlets/config/application.py", line 74, in catch_config_error
return method(app, *args, *kwargs)
File "/Users/bio/anaconda/lib/python2.7/site-packages/notebook/notebookapp.py", line 1069, in initialize
self.init_configurables()
File "/Users/bio/anaconda/lib/python2.7/site-packages/notebook/notebookapp.py", line 837, in init_configurables
parent=self,
File "/Users/bio/anaconda/lib/python2.7/site-packages/nb_conda_kernels/manager.py", line 19, in init
specs = self.find_kernel_specs() or {}
File "/Users/bio/anaconda/lib/python2.7/site-packages/nb_conda_kernels/manager.py", line 129, in find_kernel_specs
self.conda_info = self.conda_info()
File "/Users/bio/anaconda/lib/python2.7/site-packages/nb_conda_kernels/manager.py", line 29, in conda_info
p = subprocess.check_output(["conda", "info", "--json"]
File "/Users/bio/anaconda/lib/python2.7/subprocess.py", line 566, in check_output
process = Popen(stdout=PIPE, popenargs, *kwargs)
File "/Users/bio/anaconda/lib/python2.7/subprocess.py", line 710, in __init
errread, errwrite)
File "/Users/bio/anaconda/lib/python2.7/subprocess.py", line 1335, in _execute_child
raise child_exception
OSError: [Errno 2] No such file or directory

any ideas on how to resolve this issue?

**Comment by bollwyvl** [comment]
@biographie  We've released versions of `nb_conda`, `nb_conda_kernels` and `nb_anacondacloud` through the official Anaconda conda repos that should resolve the issues you are seeing!

```shell
conda update nb_conda nb_conda_kernels nb_anacondacloud
```

As-installed kernel names that are eligible for being `default` (e.g. `python2`, `python3`, `ir`, etc.) will be maintained unmodified, so they should always appear there.

The downside is as many as three options for the current env, i.e. if you are in root, you will see _Python 2_ and _Python [root]_ and _Python [default]_, you can now reproducibly capture which environment your kernel should run against.

meta: https://github.com/Anaconda-Platform/anaconda-nb-extensions/issues/166

**Comment by damianavila** [comment]
Closing this one, @biographie feel free to re-open if you still see the issue.
