### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by hudingyin** [ContinuumIO/anaconda-issues#9540]
## Main error
Application <b>orange3</b> launch may have produced errors.
## Traceback
```
Traceback (most recent call last):
  File "/Users/hudingyin/anaconda/lib/python3.6/site-packages/Orange/canvas/application/canvasmain.py", line 26, in <module>
    from AnyQt.QtWebEngineWidgets import QWebEngineView
  File "/Users/hudingyin/anaconda/lib/python3.6/site-packages/AnyQt/QtWebEngineWidgets.py", line 4, in <module>
    from PyQt5.QtWebEngineWidgets import *
ImportError: dlopen(/Users/hudingyin/anaconda/lib/python3.6/site-packages/PyQt5/QtWebEngineWidgets.so, 2): Library not loaded: @rpath/libQt5WebEngineCore.5.dylib
  Referenced from: /Users/hudingyin/anaconda/lib/python3.6/site-packages/PyQt5/QtWebEngineWidgets.so
  Reason: image not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/hudingyin/anaconda/bin/orange-canvas", line 4, in <module>
    import Orange.canvas.__main__
  File "/Users/hudingyin/anaconda/lib/python3.6/site-packages/Orange/canvas/__main__.py", line 26, in <module>
    from Orange.canvas.application.canvasmain import CanvasMainWindow
  File "/Users/hudingyin/anaconda/lib/python3.6/site-packages/Orange/canvas/application/canvasmain.py", line 29, in <module>
    from AnyQt.QtWebKitWidgets import QWebView
  File "/Users/hudingyin/anaconda/lib/python3.6/site-packages/AnyQt/QtWebKitWidgets.py", line 14, in <module>
    from PyQt5.QtWebKitWidgets import *
ModuleNotFoundError: No module named 'PyQt5.QtWebKitWidgets'

```
## System information
```
python: 3.6.1
language: en
os: Darwin;17.6.0;Darwin Kernel Version 17.6.0: Tue May  8 15:22:16 PDT 2018; root:xnu-4570.61.1~1/RELEASE_X86_64;x86_64;i386
version: 1.6.2
platform: osx-64
qt: 5.6.2
pyqt: 5.6.0
conda: 4.3.24
```

**Comment by goanpeca** [comment]
@hudingyin please update you packages


Open a terminal (on Linux or Mac) or the Anaconda Command Prompt (on windows)
and type:

```
conda update conda
conda update --all
```
