### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by LeChn** [ContinuumIO/anaconda-issues#9547]
## Main error
Application <b>notebook</b> launch may have produced errors.
## Traceback
```
Traceback (most recent call last):
  File "C:\Users\USER\Anaconda2\Scripts\jupyter-notebook-script.py", line 3, in <module>
    import notebook.notebookapp
  File "C:\Users\USER\Anaconda2\lib\site-packages\notebook\notebookapp.py", line 40, in <module>
    ioloop.install()
  File "C:\Users\USER\Anaconda2\lib\site-packages\zmq\eventloop\ioloop.py", line 210, in install
    assert (not ioloop.IOLoop.initialized()) or \
AttributeError: type object 'IOLoop' has no attribute 'initialized'

```
## System information
```
platform: win-64
version: 1.6.2
conda: 4.5.0
qt: 5.6.2
language: en_US
python: 2.7.13
os: Windows;10;10.0.17134;AMD64;Intel64 Family 6 Model 78 Stepping 3, GenuineIntel
pyqt: 5.6.0
```

**Comment by goanpeca** [comment]
Please update you packages

Open a terminal (on Linux or Mac) or the Anaconda Command Prompt (on windows)
and type:

```
conda update conda
conda update --all
```

**Comment by LeChn** [comment]
Thank you goanpeca. I didn't update the packages ,but it worked after I reinstalled ipykernel
