### ISSUE TITLE
conda error

### ISSUE THREAD

**Issue by aaryapatel007** [ContinuumIO/anaconda-issues#9559]
`# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "C:\Users\user\Anaconda3\lib\site-packages\conda\exceptions.py", line 819, in __call__
        return func(*args, **kwargs)
      File "C:\Users\user\Anaconda3\lib\site-packages\conda\cli\main.py", line 74, in _main
        context.__init__(argparse_args=args)
      File "C:\Users\user\Anaconda3\lib\site-packages\conda\base\context.py", line 236, in __init__
        argparse_args=argparse_args)
      File "C:\Users\user\Anaconda3\lib\site-packages\conda\common\configuration.py", line 722, in __init__
        self._set_search_path(search_path)
      File "C:\Users\user\Anaconda3\lib\site-packages\conda\common\configuration.py", line 728, in _set_search_path
        self._set_raw_data(load_file_configs(search_path))
      File "C:\Users\user\Anaconda3\lib\site-packages\conda\common\configuration.py", line 369, in load_file_configs
        raw_data = odict(kv for kv in chain.from_iterable(load_paths))
      File "C:\Users\user\Anaconda3\lib\site-packages\conda\common\configuration.py", line 369, in <genexpr>
        raw_data = odict(kv for kv in chain.from_iterable(load_paths))
      File "C:\Users\user\Anaconda3\lib\site-packages\conda\common\configuration.py", line 344, in _file_yaml_loader
        yield fullpath, YamlRawParameter.make_raw_parameters_from_file(fullpath)
      File "C:\Users\user\Anaconda3\lib\site-packages\conda\common\configuration.py", line 332, in make_raw_parameters_from_file
        ruamel_yaml = yaml_load(fh)
      File "C:\Users\user\Anaconda3\lib\site-packages\conda\common\serialize.py", line 54, in yaml_load
        return yaml.load(string, Loader=yaml.RoundTripLoader, version="1.2")
      File "C:\Users\user\Anaconda3\lib\site-packages\ruamel_yaml\main.py", line 637, in load
        loader = Loader(stream, version, preserve_quotes=preserve_quotes)
      File "C:\Users\user\Anaconda3\lib\site-packages\ruamel_yaml\loader.py", line 59, in __init__
        Reader.__init__(self, stream, loader=self)
      File "C:\Users\user\Anaconda3\lib\site-packages\ruamel_yaml\reader.py", line 80, in __init__
        self.stream = stream  # type: Any  # as .read is called
      File "C:\Users\user\Anaconda3\lib\site-packages\ruamel_yaml\reader.py", line 125, in stream
        self.determine_encoding()
      File "C:\Users\user\Anaconda3\lib\site-packages\ruamel_yaml\reader.py", line 180, in determine_encoding
        self.update(1)
      File "C:\Users\user\Anaconda3\lib\site-packages\ruamel_yaml\reader.py", line 241, in update
        self.check_printable(data)
      File "C:\Users\user\Anaconda3\lib\site-packages\ruamel_yaml\reader.py", line 208, in check_printable
        'unicode', "special characters are not allowed")
    ruamel_yaml.reader.ReaderError: unacceptable character #x0000: special characters are not allowed
      in "C:\Users\user\.condarc", position 0

`$ C:\Users\user\Anaconda3\Scripts\conda update conda`

  environment variables:
                 CIO_TEST=<not set>
               CONDA_ROOT=C:\Users\user\Anaconda3
                 HOMEPATH=\Users\user
                     PATH=C:\Users\user\Anaconda3\Library\bin;C:\Program Files (x86)\Common File
                          s\Oracle\Java\javapath;C:\ProgramData\Oracle\Java\javapath;C:\WINDOWS\
                          system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\Windo
                          wsPowerShell\v1.0\;C:\Program Files (x86)\ATI
                          Technologies\ATI.ACE\Core-Static;C:\Program Files\Lenovo\Bluetooth
                          Software\;C:\Program Files\Lenovo\Bluetooth
                          Software\syswow64;C:\Program Files\Git\cmd;C:\WINDOWS\System32\OpenSSH
                          \;C:\Users\user\AppData\Local\Microsoft\WindowsApps;
             PSMODULEPATH=C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules\
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>

     active environment : None
       user config file : C:\Users\user\.condarc
 populated config files :
          conda version : 4.5.4
    conda-build version : 3.10.5
         python version : 3.6.5.final.0
       base environment : C:\Users\user\Anaconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/win-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/win-64
                          https://repo.anaconda.com/pkgs/pro/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\Users\user\Anaconda3\pkgs
                          C:\Users\user\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\user\Anaconda3\envs
                          C:\Users\user\AppData\Local\conda\conda\envs
                          C:\Users\user\.conda\envs
               platform : win-64
             user-agent : conda/4.5.4 requests/2.18.4 CPython/3.6.5 Windows/10 Windows/10.0.17134
          administrator : False
             netrc file : None
           offline mode : False

An unexpected error has occurred. Conda has prepared the above report.
If submitted, this report will be used by core maintainers to improve
future releases of conda.
Would you like conda to send this report to the core maintainers?
[y/N]: y
Upload successful.

Thank you for helping to improve conda.
Opt-in to always sending reports (and not see this message again)
by running

    $ conda config --set report_errors true`

**Comment by nehaljwani** [comment]
@aaryapatel007 Open command prompt, and share the output for:
```
type C:\Users\user\.condarc
```

**Comment by aaryapatel007** [comment]
![2018-06-10](https://user-images.githubusercontent.com/30631425/41204835-5cd0be2e-6d07-11e8-8219-b460e0bae6d0.png)
it opens in notepad.

**Comment by csoja** [comment]
@aaryapatel007 
You only entered "C:\Users\user\.condarc"
@nehaljwani was requesting you execute "type C:\Users\user\.condarc" in a command prompt, and share that output.

**Comment by aaryapatel007** [comment]
![2018-06-11](https://user-images.githubusercontent.com/30631425/41241976-f913dc8a-6dbb-11e8-8a2c-de8dc5815e7b.png)
nothing happens.

**Comment by nehaljwani** [comment]
@aaryapatel007 Okay, type:
```
del C:\Users\user.condarc
```
And then open Anaconda Prompt and type `conda update conda`

**Comment by aaryapatel007** [comment]
![2018-06-12](https://user-images.githubusercontent.com/30631425/41270990-ac00785c-6e2b-11e8-8a60-c56d85d654e8.png)
nothing happens.

**Comment by aaryapatel007** [comment]
Thank a lot @nehaljwani  Sir.Now everything is working perfectly.
