### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by alexsomoza** [ContinuumIO/anaconda-issues#9569]
Navigator Error
An unexpected error occurred on Navigator start-up
Report
Please report this issue in the anaconda issue tracker 
Main Error

expected str, bytes or os.PathLike object, not NoneType

Traceback

Traceback (most recent call last):
  File "C:\Continuum\anaconda3\lib\site-packages\anaconda_navigator\exceptions.py", line 75, in exception_handler
    return_value = func(*args, **kwargs)
  File "C:\Continuum\anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 150, in start_app
    window = run_app(splash)
  File "C:\Continuum\anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 65, in run_app
    window = MainWindow(splash=splash, tab_project=False)
  File "C:\Continuum\anaconda3\lib\site-packages\anaconda_navigator\widgets\main_window.py", line 163, in __init__
    self.api = AnacondaAPI()
  File "C:\Continuum\anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 2185, in AnacondaAPI
    ANACONDA_API = _AnacondaAPI()
  File "C:\Continuum\anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 89, in __init__
    self._conda_api = CondaAPI()
  File "C:\Continuum\anaconda3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 1714, in CondaAPI
    CONDA_API = _CondaAPI()
  File "C:\Continuum\anaconda3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 353, in __init__
    self.sys_rc_path = join(self.ROOT_PREFIX, '.condarc')
  File "C:\Continuum\anaconda3\lib\ntpath.py", line 76, in join
    path = os.fspath(path)
TypeError: expected str, bytes or os.PathLike object, not NoneType

**Comment by goanpeca** [comment]
@alexsomoza please provide the requested information.

`conda info`

`conda list --show-channel-urls`

Also, try opening the Anaconda Prompt and running:

```
anaconda-navigator
```

**Comment by rdebnath93** [comment]
Did anyone find the solution yet? 
Thanks in advance.

**Comment by monkeysforever** [comment]
deleting .condarc file worked for me

**Comment by alexsomoza** [comment]
conda info

conda info

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "C:\Continuum\anaconda3\lib\site-packages\conda\exceptions.py", line 819, in __call__
        return func(*args, **kwargs)
      File "C:\Continuum\anaconda3\lib\site-packages\conda\cli\main.py", line 74, in _main
        context.__init__(argparse_args=args)
      File "C:\Continuum\anaconda3\lib\site-packages\conda\base\context.py", line 236, in __init__
        argparse_args=argparse_args)
      File "C:\Continuum\anaconda3\lib\site-packages\conda\common\configuration.py", line 722, in __init__
        self._set_search_path(search_path)
      File "C:\Continuum\anaconda3\lib\site-packages\conda\common\configuration.py", line 728, in _set_search_path
        self._set_raw_data(load_file_configs(search_path))
      File "C:\Continuum\anaconda3\lib\site-packages\conda\common\configuration.py", line 369, in load_file_configs
        raw_data = odict(kv for kv in chain.from_iterable(load_paths))
      File "C:\Continuum\anaconda3\lib\site-packages\conda\common\configuration.py", line 369, in <genexpr>
        raw_data = odict(kv for kv in chain.from_iterable(load_paths))
      File "C:\Continuum\anaconda3\lib\site-packages\conda\common\configuration.py", line 344, in _file_yaml_loader
        yield fullpath, YamlRawParameter.make_raw_parameters_from_file(fullpath)
      File "C:\Continuum\anaconda3\lib\site-packages\conda\common\configuration.py", line 332, in make_raw_parameters_from_file
        ruamel_yaml = yaml_load(fh)
      File "C:\Continuum\anaconda3\lib\site-packages\conda\common\serialize.py", line 54, in yaml_load
        return yaml.load(string, Loader=yaml.RoundTripLoader, version="1.2")
      File "C:\Continuum\anaconda3\lib\site-packages\ruamel_yaml\main.py", line 639, in load
        return loader._constructor.get_single_data()  # type: ignore
      File "C:\Continuum\anaconda3\lib\site-packages\ruamel_yaml\constructor.py", line 102, in get_single_data
        node = self.composer.get_single_node()
      File "C:\Continuum\anaconda3\lib\site-packages\ruamel_yaml\composer.py", line 75, in get_single_node
        document = self.compose_document()
      File "C:\Continuum\anaconda3\lib\site-packages\ruamel_yaml\composer.py", line 96, in compose_document
        node = self.compose_node(None, None)
      File "C:\Continuum\anaconda3\lib\site-packages\ruamel_yaml\composer.py", line 132, in compose_node
        node = self.compose_mapping_node(anchor)
      File "C:\Continuum\anaconda3\lib\site-packages\ruamel_yaml\composer.py", line 187, in compose_mapping_node
        while not self.parser.check_event(MappingEndEvent):
      File "C:\Continuum\anaconda3\lib\site-packages\ruamel_yaml\parser.py", line 144, in check_event
        self.current_event = self.state()
      File "C:\Continuum\anaconda3\lib\site-packages\ruamel_yaml\parser.py", line 561, in parse_block_mapping_key
        token.start_mark)
    ruamel_yaml.parser.ParserError: while parsing a block mapping
      in "C:\Users\asomoza\.condarc", line 1, column 1
    expected <block end>, but found '<block mapping start>'
      in "C:\Users\asomoza\.condarc", line 8, column 2

`$ C:\Continuum\anaconda3\Scripts\conda info`


An unexpected error has occurred. Conda has prepared the above report.
If submitted, this report will be used by core maintainers to improve
future releases of conda.
Would you like conda to send this report to the core maintainers?
[y/N]: y
Upload did not complete.

**Comment by alexsomoza** [comment]
conda list --show-channel-urls

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "C:\Continuum\anaconda3\lib\site-packages\conda\exceptions.py", line 819, in __call__
        return func(*args, **kwargs)
      File "C:\Continuum\anaconda3\lib\site-packages\conda\cli\main.py", line 74, in _main
        context.__init__(argparse_args=args)
      File "C:\Continuum\anaconda3\lib\site-packages\conda\base\context.py", line 236, in __init__
        argparse_args=argparse_args)
      File "C:\Continuum\anaconda3\lib\site-packages\conda\common\configuration.py", line 722, in __init__
        self._set_search_path(search_path)
      File "C:\Continuum\anaconda3\lib\site-packages\conda\common\configuration.py", line 728, in _set_search_path
        self._set_raw_data(load_file_configs(search_path))
      File "C:\Continuum\anaconda3\lib\site-packages\conda\common\configuration.py", line 369, in load_file_configs
        raw_data = odict(kv for kv in chain.from_iterable(load_paths))
      File "C:\Continuum\anaconda3\lib\site-packages\conda\common\configuration.py", line 369, in <genexpr>
        raw_data = odict(kv for kv in chain.from_iterable(load_paths))
      File "C:\Continuum\anaconda3\lib\site-packages\conda\common\configuration.py", line 344, in _file_yaml_loader
        yield fullpath, YamlRawParameter.make_raw_parameters_from_file(fullpath)
      File "C:\Continuum\anaconda3\lib\site-packages\conda\common\configuration.py", line 332, in make_raw_parameters_from_file
        ruamel_yaml = yaml_load(fh)
      File "C:\Continuum\anaconda3\lib\site-packages\conda\common\serialize.py", line 54, in yaml_load
        return yaml.load(string, Loader=yaml.RoundTripLoader, version="1.2")
      File "C:\Continuum\anaconda3\lib\site-packages\ruamel_yaml\main.py", line 639, in load
        return loader._constructor.get_single_data()  # type: ignore
      File "C:\Continuum\anaconda3\lib\site-packages\ruamel_yaml\constructor.py", line 102, in get_single_data
        node = self.composer.get_single_node()
      File "C:\Continuum\anaconda3\lib\site-packages\ruamel_yaml\composer.py", line 75, in get_single_node
        document = self.compose_document()
      File "C:\Continuum\anaconda3\lib\site-packages\ruamel_yaml\composer.py", line 96, in compose_document
        node = self.compose_node(None, None)
      File "C:\Continuum\anaconda3\lib\site-packages\ruamel_yaml\composer.py", line 132, in compose_node
        node = self.compose_mapping_node(anchor)
      File "C:\Continuum\anaconda3\lib\site-packages\ruamel_yaml\composer.py", line 187, in compose_mapping_node
        while not self.parser.check_event(MappingEndEvent):
      File "C:\Continuum\anaconda3\lib\site-packages\ruamel_yaml\parser.py", line 144, in check_event
        self.current_event = self.state()
      File "C:\Continuum\anaconda3\lib\site-packages\ruamel_yaml\parser.py", line 561, in parse_block_mapping_key
        token.start_mark)
    ruamel_yaml.parser.ParserError: while parsing a block mapping
      in "C:\Users\asomoza\.condarc", line 1, column 1
    expected <block end>, but found '<block mapping start>'
      in "C:\Users\asomoza\.condarc", line 8, column 2

`$ C:\Continuum\anaconda3\Scripts\conda list --show-channel-urls`

  environment variables:
                 CIO_TEST=<not set>
               CONDA_ROOT=C:\Continuum\anaconda3
                 HOMEPATH=\Users\asomoza
                     PATH=C:\Program Files\Microsoft MPI\Bin\;C:\Java\jdk-9.0.1\bin;C:\Python36\
                          Scripts\;C:\Python36;C:\Program Files (x86)\Common
                          Files\Oracle\Java\javapath;C:\Program Files\Common Files\Microsoft
                          Shared\Microsoft Online Services;C:\Program Files (x86)\Common
                          Files\Microsoft Shared\Microsoft Online Services;C:\oracle\product\11g
                          _64bits\bin;C:\oracle\product\11g_32bits\bin;C:\Program Files
                          (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\WINDOW
                          S\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\Win
                          dowsPowerShell\v1.0\;C:\Program Files (x86)\Intel\Intel(R) Management
                          Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management
                          Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management
                          Engine Components\IPT;C:\Program Files\Intel\Intel(R) Management
                          Engine Components\IPT;C:\Program Files\Internet Explorer\;C:\Program
                          Files (x86)\Sennheiser\SoftphoneSDK\;C:\Program
                          Files\Intel\WiFi\bin\;C:\Program Files\Intel\WirelessCommon\;C:\Contin
                          uum\anaconda3\Scripts;C:\Continuum\anaconda3\Library\bin;C:\apache-ant
                          -1.10.3\bin;C:\kibana-6.2.4\bin;C:\zookeeper\bin;C:\WINDOWS\System32\O
                          penSSH\;C:\Program Files\dotnet\;C:\Program Files\Microsoft SQL
                          Server\130\Tools\Binn\;C:\Java\jdk-9.0.1\bin;C:\apache-ant-1.10.3\bin;
                          C:\Python36;C:\Python36\Scripts;C:\Continuum\anaconda3;C:\Continuum\an
                          aconda3\Library\mingw-w64\bin;C:\Continuum\anaconda3\Library\usr\bin;C
                          :\Continuum\anaconda3\Library\bin;C:\Continuum\anaconda3\Scripts;C:\Us
                          ers\asomoza\AppData\Local\Microsoft\WindowsApps;C:\Program
                          Files\Microsoft VS Code\bin;C:\kibana-6.2.4\bin;C:\zookeeper\bin;
        PLMVIS_82_LIBPATH=C:\Program Files (x86)\SAP\FrontEnd\SAPgui\Program
             PSMODULEPATH=C:\Program Files\WindowsPowerShell\Modules;C:\WINDOWS\system32\Windows
                          PowerShell\v1.0\Modules
              PYTHON_HOME=C:\Python36
       REQUESTS_CA_BUNDLE=<not set>
         SSF_LIBRARY_PATH=C:\Program Files (x86)\SAP\FrontEnd\SecureLogin\lib\sapcrypto.dll
            SSL_CERT_FILE=<not set>

     active environment : None
       user config file : C:\Users\asomoza\.condarc
 populated config files :
          conda version : 4.5.4
    conda-build version : 3.10.5
         python version : 3.6.5.final.0
       base environment : C:\Continuum\anaconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/win-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/win-64
                          https://repo.anaconda.com/pkgs/pro/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\Continuum\anaconda3\pkgs
                          C:\Users\asomoza\AppData\Local\conda\conda\pkgs
       envs directories : C:\Continuum\anaconda3\envs
                          C:\Users\asomoza\AppData\Local\conda\conda\envs
                          C:\Users\asomoza\.conda\envs
               platform : win-64
             user-agent : conda/4.5.4 requests/2.18.4 CPython/3.6.5 Windows/10 Windows/10.0.17134
          administrator : False
             netrc file : None
           offline mode : False


An unexpected error has occurred. Conda has prepared the above report.
If submitted, this report will be used by core maintainers to improve
future releases of conda.

**Comment by goanpeca** [comment]
@alexsomoza please remove this file

`C:\Users\asomoza\.condarc` and try again
