### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by magdalenat** [ContinuumIO/anaconda-issues#9576]
## Main error
Application <b>python-microscopy</b> launch may have produced errors.
## Traceback
```
INFO:OpenGL.acceleratesupport:No OpenGL_accelerate module loaded: No module named OpenGL_accelerate
11:47:50: Debug: Adding duplicate image handler for 'PNG file'
11:47:50: Debug: Adding duplicate image handler for 'JPEG file'
11:47:50: Debug: Adding duplicate image handler for 'TIFF file'
11:47:50: Debug: Adding duplicate image handler for 'GIF file'
11:47:50: Debug: Adding duplicate image handler for 'PNM file'
11:47:50: Debug: Adding duplicate image handler for 'PCX file'
11:47:50: Debug: Adding duplicate image handler for 'IFF file'
11:47:50: Debug: Adding duplicate image handler for 'Windows icon file'
11:47:50: Debug: Adding duplicate image handler for 'Windows cursor file'
11:47:50: Debug: Adding duplicate image handler for 'Windows animated cursor file'
11:47:50: Debug: Adding duplicate image handler for 'TGA file'
11:47:50: Debug: Adding duplicate image handler for 'XPM file'
DEBUG:PYME.LMVis.visCore:Creating VisGUI menu bar
DEBUG:PYME.LMVis.Extras:Initializing setBGImage plugin
DEBUG:PYME.LMVis.Extras:Initializing fusionUtils plugin
DEBUG:PYME.LMVis.Extras:Initializing perFrameVariable plugin
DEBUG:PYME.LMVis.Extras:Initializing saved_views plugin
DEBUG:PYME.LMVis.Extras:Initializing dockedPanel plugin
DEBUG:PYME.LMVis.Extras:Initializing photophysics plugin
DEBUG:PYME.LMVis.Extras:Initializing vibration plugin
DEBUG:PYME.LMVis.Extras:Initializing showShortcuts plugin
DEBUG:PYME.LMVis.Extras:Initializing particleTracking plugin
DEBUG:PYME.LMVis.Extras:Initializing animation plugin
DEBUG:PYME.LMVis.Extras:Initializing scaleBox plugin
DEBUG:PYME.LMVis.Extras:Initializing clusterAnalysis plugin
DEBUG:PYME.LMVis.Extras:Initializing pointwiseColoc plugin
DEBUG:PYME.LMVis.Extras:Initializing temperaturePlot plugin
DEBUG:PYME.LMVis.Extras:Initializing pointSetGeneration plugin
/home/magt/anaconda3/envs/pymicroscopy/lib/python2.7/site-packages/pyface/wx/drag_and_drop.py:94: wxPyDeprecationWarning: Call to deprecated item. Use wx.DataFormat instead.
  PythonObject = wx.CustomDataFormat('PythonObject')
DEBUG:PYME.LMVis.Extras:Initializing flagZMotionArtifacts plugin
DEBUG:root:Adding menu items for event filters
DEBUG:PYME.LMVis.Extras:Initializing shiftmapGenerator plugin
DEBUG:PYME.LMVis.Extras:Initializing multiviewMapping plugin
DEBUG:root:Adding menu items for multi-view manipulation
DEBUG:PYME.LMVis.Extras:Initializing spherical_harmonics plugin
DEBUG:PYME.LMVis.Extras:Initializing snapshot plugin
Traceback (most recent call last):
  File "/home/magt/anaconda3/envs/pymicroscopy/lib/python2.7/site-packages/PYME/LMVis/VisGUI.py", line 384, in OnInit
    self.main = VisGUIFrame(None, self.filename, use_shaders=self.use_shaders, cmd_args=self.cmd_args)
  File "/home/magt/anaconda3/envs/pymicroscopy/lib/python2.7/site-packages/PYME/LMVis/VisGUI.py", line 85, in __init__
    self.CreateMenuBar(use_shaders=use_shaders)
  File "/home/magt/anaconda3/envs/pymicroscopy/lib/python2.7/site-packages/PYME/LMVis/visCore.py", line 275, in CreateMenuBar
    Extras.InitPlugins(self)
  File "/home/magt/anaconda3/envs/pymicroscopy/lib/python2.7/site-packages/PYME/LMVis/Extras/__init__.py", line 40, in InitPlugins
    m = __import__('PYME.LMVis.Extras.' + mn, fromlist=['PYME', 'LMVis', 'Extras'])
  File "/home/magt/anaconda3/envs/pymicroscopy/lib/python2.7/site-packages/PYME/LMVis/Extras/snapshot.py", line 25, in <module>
    from wx import wx
ImportError: cannot import name wx
OnInit returned false, exiting...
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/home/magt/anaconda3/envs/pymicroscopy/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
wxAssertionError: C++ assertion "GetEventHandler() == this" failed at /tmp/build/80754af9/wxpython_1520998275718/work/ext/wxWidgets/src/common/wincmn.cpp(478) in ~wxWindowBase(): any pushed event handlers must have been removed
Error in sys.exitfunc:
Traceback (most recent call last):
  File "/home/magt/anaconda3/envs/pymicroscopy/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
wx._core.wxAssertionError: C++ assertion "GetEventHandler() == this" failed at /tmp/build/80754af9/wxpython_1520998275718/work/ext/wxWidgets/src/common/wincmn.cpp(478) in ~wxWindowBase(): any pushed event handlers must have been removed

```
## System information
```
python: 3.6.3
language: pl_PL
os: Linux;3.16.0-4-amd64;#1 SMP Debian 3.16.51-3 (2017-12-13);x86_64;
version: 1.6.2
platform: linux-64
qt: 5.6.2
pyqt: 5.6.0
conda: 4.5.4
```

**Comment by goanpeca** [comment]
Please remember to update to the latest version of Navigator to include
the latest fixes.

Open a terminal (on Linux or Mac) or the Anaconda Command Prompt (on windows)
and type:

```
conda update conda
conda update --all
```
