### ISSUE TITLE
Running Anaconda Prompt. Error: FileNotFoundError: [Errno 2] No such file or directory: 'shell.cmd.exe'

### ISSUE THREAD

**Issue by shishirbharti** [ContinuumIO/anaconda-issues#9585]
Error occured while running Anaconda Propmpt. Error occured after a recent windows 10 update.

Traceback (most recent call last):
  File "d:\programdata\anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "d:\programdata\anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "d:\ProgramData\Anaconda3\Scripts\conda.exe\__main__.py", line 9, in <module>
  File "d:\programdata\anaconda3\lib\site-packages\markdown\__main__.py", line 130, in run
    markdown.markdownFromFile(**options)
  File "d:\programdata\anaconda3\lib\site-packages\markdown\__init__.py", line 529, in markdownFromFile
    kwargs.get('encoding', None))
  File "d:\programdata\anaconda3\lib\site-packages\markdown\__init__.py", line 428, in convertFile
    input_file = codecs.open(input, mode="r", encoding=encoding)
  File "d:\programdata\anaconda3\lib\codecs.py", line 895, in open
    file = builtins.open(filename, mode, buffering)
FileNotFoundError: [Errno 2] No such file or directory: 'shell.cmd.exe'

**Comment by lusensama** [comment]
I'm having the same problem here...
Windows 10 
Anaconda 3

**Comment by wqysq** [comment]
I'm also having the same problem here.
Windows 7
anaconda 3
who knows how to solve the problem?

**Comment by shubham4576** [comment]
I found the solution to this problem.
**Link to Solution :** [https://docs.anaconda.com/reference/troubleshooting/#trouble-with-activation-on-powershell-on-windows](https://github.com/ContinuumIO/anaconda-issues/issues/url)
I works fine for me.

**Comment by wqysq** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，您的来信我已收到，非常感谢。
