### ISSUE TITLE
Spyder not launching

### ISSUE THREAD

**Issue by junejashubh** [ContinuumIO/anaconda-issues#9593]
Traceback (most recent call last):
  File "C:\Users\Shubham\Anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 3208, in main
    mainwindow = run_spyder(app, options, args)
  File "C:\Users\Shubham\Anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 3084, in run_spyder
    main.setup()
  File "C:\Users\Shubham\Anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 828, in setup
    self.workingdirectory = WorkingDirectory(self, self.init_workdir, main=self)
  File "C:\Users\Shubham\Anaconda3\lib\site-packages\spyder\plugins\workingdirectory.py", line 159, in __init__
    self.chdir(workdir)
  File "C:\Users\Shubham\Anaconda3\lib\site-packages\spyder\plugins\workingdirectory.py", line 296, in chdir
    self.refresh_plugin()
  File "C:\Users\Shubham\Anaconda3\lib\site-packages\spyder\plugins\workingdirectory.py", line 204, in refresh_plugin
    self.save_wdhistory()
  File "C:\Users\Shubham\Anaconda3\lib\site-packages\spyder\plugins\workingdirectory.py", line 234, in save_wdhistory
    encoding.writelines(text, self.LOG_PATH)
  File "C:\Users\Shubham\Anaconda3\lib\site-packages\spyder\utils\encoding.py", line 236, in writelines
    return write(os.linesep.join(lines), filename, encoding, mode)
  File "C:\Users\Shubham\Anaconda3\lib\site-packages\spyder\utils\encoding.py", line 227, in write
    with open(filename, mode) as textfile:
FileNotFoundError: [Errno 2] No such file or directory: '%USERPROFILE\\.spyder-py3\\workingdir'

This is the error msg

**Comment by ccordoba12** [comment]
Please open a system terminal (cmd.exe) and run there

    spyder --reset

then try again. That should fix the problem.

**Comment by junejashubh** [comment]
@ccordoba12 its still not working.

**Comment by ccordoba12** [comment]
Please don't open more issues about this problem. We don't understand why it happens but it'll be fixed in our next version (Spyder **3.3**), to be released in a couple of weeks.

For reference, this is the pull request that fixed this problem:

https://github.com/spyder-ide/spyder/pull/7210

*Note*: Since we don't understand why this happens, until we release 3.3 there's no workaround or temporary fix for this problem.

**Comment by junejashubh** [comment]
@ccordoba12 it working now.. 
in cmd:
setx HOME "%USERPROFILE%"
and anaconda navigator has started working.
