### ISSUE TITLE
TypeError: string indices must be integers

### ISSUE THREAD

**Issue by dongjinguang-china** [ContinuumIO/anaconda-issues#9616]
Whenever I install Anaconda of version 3-5.2.0-Linux-x86_64 on Ubuntu 16.04,  I will got the following error:

For this change to become active, you have to open a new terminal.

Thank you for installing Anaconda3!

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/home/d00268009/anaconda3/lib/python3.6/site-packages/conda/exceptions.py", line 819, in __call__
        return func(*args, **kwargs)
      File "/home/d00268009/anaconda3/lib/python3.6/site-packages/conda/cli/main.py", line 74, in _main
        context.__init__(argparse_args=args)
      File "/home/d00268009/anaconda3/lib/python3.6/site-packages/conda/base/context.py", line 236, in __init__
        argparse_args=argparse_args)
      File "/home/d00268009/anaconda3/lib/python3.6/site-packages/conda/common/configuration.py", line 722, in __init__
        self._set_search_path(search_path)
      File "/home/d00268009/anaconda3/lib/python3.6/site-packages/conda/common/configuration.py", line 728, in _set_search_p                      ath
        self._set_raw_data(load_file_configs(search_path))
      File "/home/d00268009/anaconda3/lib/python3.6/site-packages/conda/common/configuration.py", line 369, in load_file_con                      figs
        raw_data = odict(kv for kv in chain.from_iterable(load_paths))
      File "/home/d00268009/anaconda3/lib/python3.6/site-packages/conda/common/configuration.py", line 369, in <genexpr>
        raw_data = odict(kv for kv in chain.from_iterable(load_paths))
      File "/home/d00268009/anaconda3/lib/python3.6/site-packages/conda/common/configuration.py", line 344, in _file_yaml_lo                      ader
        yield fullpath, YamlRawParameter.make_raw_parameters_from_file(fullpath)
      File "/home/d00268009/anaconda3/lib/python3.6/site-packages/conda/common/configuration.py", line 336, in make_raw_para                      meters_from_file
        return cls.make_raw_parameters(filepath, ruamel_yaml) or EMPTY_MAP
      File "/home/d00268009/anaconda3/lib/python3.6/site-packages/conda/common/configuration.py", line 325, in make_raw_para                      meters
        for key in from_map)
      File "/home/d00268009/anaconda3/lib/python3.6/site-packages/conda/common/configuration.py", line 325, in <genexpr>
        for key in from_map)
    TypeError: string indices must be integers

`$ /home/d00268009/anaconda3/bin/conda info --json`

An unexpected error has occurred. Conda has prepared the above report.

# >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

I have check the code of  configuration.py, it descript that:
323             return dict((key, cls(source, key, from_map[key],
324                                   cls._get_yaml_key_comment(from_map, key)))
325                         for key in from_map)   # it is said that shoud be integers, not string
326         return EMPTY_MAP

Could you kindly help to check it?

**Comment by goanpeca** [comment]
@dongjinguang-china could you provide the `conda info` and `conda list` information

**Comment by goanpeca** [comment]
@kalefranz ?

**Comment by dongjinguang-china** [comment]
Hi kalefranz, could you kindly help to check for this issue? Thanks a lots

**Comment by Atralb** [comment]
So, has a solution been given for this issue ? @dongjinguang-china @goanpeca @kalefranz 
Thanks.

**Comment by dongjinguang-china** [comment]
Sorry, it haven't been resolved:(

**Comment by ddeemerpurdue** [comment]
Late to the party - your ~/.condarc file can actually be a cause of this issue. If anyone is having this issue, share the contents of that file and it might be the reason.

**Comment by TalBen1802** [comment]
someone knows the reason of this issue？I have the same problem~

**Comment by hongsua** [comment]
Hi, I am facing the same issue. Does anyone know the solution? Thanks a lot.

**Comment by bajcsiadel** [comment]
> Late to the party - your ~/.condarc file can actually be a cause of this issue. If anyone is having this issue, share the contents of that file and it might be the reason.

Hello @ddeemerpurdue, I have the same issue. My `~/.condarc` looks as follows:
``` bash
#
# ~/.condarc
#

CONDA_HOME="<path to anaconda>"

export PATH="$CONDA_HOME/bin:$PATH"
```

**Comment by yongkangchen** [comment]
I faced the same issue when I tried to install conda on a MacBook M1 running MacOS 14.4.1. 
This occurred with both the Graphic installer and CLI installer, for both Anaconda and Miniconda. 

After deleting `~/.conda`, `~/.condarc`, and `~/anaconda3`, I was able to install successfully.

**Comment by wintermutant** [comment]
@bajcsiadel -- try deleting that file, or renaming it from ~/.condarc to something else (that way anaconda doesn't automatically grab it). I need to go back in my notes to remember exactly why the ~/.condarc can cause this error, but I believe it has something to do with an issue reading the rc file and configuration.py parsing it.

**Comment by bajcsiadel** [comment]
> @bajcsiadel -- try deleting that file, or renaming it from ~/.condarc to something else (that way anaconda doesn't automatically grab it). I need to go back in my notes to remember exactly why the ~/.condarc can cause this error, but I believe it has something to do with an issue reading the rc file and configuration.py parsing it.

Thank you for the answer @ddeemerpurdue.

In the meantime, I also found [this page](https://conda.io/projects/conda/en/latest/user-guide/configuration/use-condarc.html), where it is explained that `.condarc` is used to store general configuration.
