### ISSUE TITLE
Anaconda  [ 2.6.11 : NO SUCH FILE or DIRECTORY : Shell.cmd.exe"

### ISSUE THREAD

**Issue by joshuagithub** [ContinuumIO/anaconda-issues#9624]
I have this issue this morning. It does affect me work with anacoda navigator (i have copy and paste the errors)

DO i NEED to REINSTALL  ALL OVER AGAIN?  

PLease assist

Traceback (most recent call last):
  File "c:\users\jjoshua\appdata\local\continuum\anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\jjoshua\appdata\local\continuum\anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\jjoshua\AppData\Local\Continuum\anaconda3\Scripts\conda.exe\__main__.py", line 9, in <module>
  File "c:\users\jjoshua\appdata\local\continuum\anaconda3\lib\site-packages\markdown\__main__.py", line 130, in run
    markdown.markdownFromFile(**options)
  File "c:\users\jjoshua\appdata\local\continuum\anaconda3\lib\site-packages\markdown\__init__.py", line 529, in markdownFromFile
    kwargs.get('encoding', None))
  File "c:\users\jjoshua\appdata\local\continuum\anaconda3\lib\site-packages\markdown\__init__.py", line 428, in convertFile
    input_file = codecs.open(input, mode="r", encoding=encoding)
  File "c:\users\jjoshua\appdata\local\continuum\anaconda3\lib\codecs.py", line 897, in open
    file = builtins.open(filename, mode, buffering)
FileNotFoundError: [Errno 2] No such file or directory: 'shell.cmd.exe'

**Comment by joshuagithub** [comment]
i am reinstalling.... really annoying!
any suggestions please...........

**Comment by maharshi3patel** [comment]
I am also facing a similar situation. Have you found a solution?

**Comment by joshuagithub** [comment]
Hi

Yes. I have uninstalled Anaconda and Re-Install once again. It works!
But no reply from the anaconda team.

--
JJ

**Comment by cpgrant** [comment]
I have the same issue on Windows 10:

When I try to run  activate d36 i get:

Traceback (most recent call last):
  File "c:\users\root\miniconda3\envs\d36\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\root\miniconda3\envs\d36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\root\Miniconda3\Scripts\conda.exe\__main__.py", line 9, in <module>
  File "c:\users\root\miniconda3\envs\d36\lib\site-packages\markdown\__main__.py", line 130, in run
    markdown.markdownFromFile(**options)
  File "c:\users\root\miniconda3\envs\d36\lib\site-packages\markdown\__init__.py", line 529, in markdownFromFile
    kwargs.get('encoding', None))
  File "c:\users\root\miniconda3\envs\d36\lib\site-packages\markdown\__init__.py", line 428, in convertFile
    input_file = codecs.open(input, mode="r", encoding=encoding)
  File "c:\users\root\miniconda3\envs\d36\lib\codecs.py", line 897, in open
    file = builtins.open(filename, mode, buffering)
FileNotFoundError: [Errno 2] No such file or directory: 'shell.cmd.exe'

I prefer not to reinstall everything.
Any solution?

**Comment by joshuagithub** [comment]
I had no solution on this. However, it is pretty time-consuming to fix the
bug or look at the log-files that you run with conda. It is a long list.

i run DNN application (images) to get those errors. I had no choice, i
reinstall the Conda. I try update conda instead, it doesn't work. please
re-install.
It helps!

**Comment by shubham4576** [comment]
I found the solution to this problem.
**Link to Solution :**  [https://docs.anaconda.com/reference/troubleshooting/#trouble-with-activation-on-powershell-on-windows](url) 
I works fine for me.
