### ISSUE TITLE
Can't start Anacoda 3.5.2

### ISSUE THREAD

**Issue by aliceliu9988** [ContinuumIO/anaconda-issues#9652]
### Actual Behavior

Windows 10, Anacoda 3.5.2

After successful installation and click to start it, it threw out an Navigator Error like:

Navigator Error
An unexpected error occurred on Navigator start-up
Report
Please report this issue in the anaconda issue tracker 
Main Error

expected str, bytes or os.PathLike object, not NoneType

Traceback

Traceback (most recent call last):
  File "d:\Users\alice\Anaconda3\lib\site-packages\anaconda_navigator\exceptions.py", line 75, in exception_handler
    return_value = func(*args, **kwargs)
  File "d:\Users\alice\Anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 150, in start_app
    window = run_app(splash)
  File "d:\Users\alice\Anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 65, in run_app
    window = MainWindow(splash=splash, tab_project=False)
  File "d:\Users\alice\Anaconda3\lib\site-packages\anaconda_navigator\widgets\main_window.py", line 163, in __init__
    self.api = AnacondaAPI()
  File "d:\Users\alice\Anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 2185, in AnacondaAPI
    ANACONDA_API = _AnacondaAPI()
  File "d:\Users\alice\Anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 89, in __init__
    self._conda_api = CondaAPI()
  File "d:\Users\alice\Anaconda3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 1714, in CondaAPI
    CONDA_API = _CondaAPI()
  File "d:\Users\alice\Anaconda3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 353, in __init__
    self.sys_rc_path = join(self.ROOT_PREFIX, '.condarc')
  File "d:\Users\alice\Anaconda3\lib\ntpath.py", line 76, in join
    path = os.fspath(path)
TypeError: expected str, bytes or os.PathLike object, not NoneType

### Expected Behavior

The 1st time when I installed an older version, starting the app will trigger the Anacoda in a browser page.

##### `conda info`

```

```

##### `conda list --show-channel-urls`

```

```

**Comment by goanpeca** [comment]
Please remember to update to the latest version of Navigator to include
the latest fixes.

Open a terminal (on Linux or Mac) or the Anaconda Command Prompt (on windows)
and type:

```
conda update conda
conda update --all
```
