### ISSUE TITLE
Navigator error: main_user 

### ISSUE THREAD

**Issue by Steven177** [ContinuumIO/anaconda-issues#9656]
##### `conda info`

```
Navigator Error
An unexpected error occurred on Navigator start-up

Report
Please report this issue in the anaconda issue tracker

Main Error
'user_agent'
Traceback
Traceback (most recent call last):
  File "/anaconda3/lib/python3.6/site-packages/anaconda_navigator/exceptions.py", line 75, in exception_handler
    return_value = func(*args, **kwargs)
  File "/anaconda3/lib/python3.6/site-packages/anaconda_navigator/app/start.py", line 150, in start_app
    window = run_app(splash)
  File "/anaconda3/lib/python3.6/site-packages/anaconda_navigator/app/start.py", line 65, in run_app
    window = MainWindow(splash=splash, tab_project=False)
  File "/anaconda3/lib/python3.6/site-packages/anaconda_navigator/widgets/main_window.py", line 163, in __init__
    self.api = AnacondaAPI()
  File "/anaconda3/lib/python3.6/site-packages/anaconda_navigator/api/anaconda_api.py", line 2185, in AnacondaAPI
    ANACONDA_API = _AnacondaAPI()
  File "/anaconda3/lib/python3.6/site-packages/anaconda_navigator/api/anaconda_api.py", line 89, in __init__
    self._conda_api = CondaAPI()
  File "/anaconda3/lib/python3.6/site-packages/anaconda_navigator/api/conda_api.py", line 1714, in CondaAPI
    CONDA_API = _CondaAPI()
  File "/anaconda3/lib/python3.6/site-packages/anaconda_navigator/api/conda_api.py", line 350, in __init__
    self.set_conda_prefix(info=get_conda_info())
  File "/anaconda3/lib/python3.6/site-packages/anaconda_navigator/api/conda_api.py", line 509, in set_conda_prefix
    self._user_agent = info['user_agent']
KeyError: 'user_agent'
```

##### `conda list --show-channel-urls`

```

```

**Comment by goanpeca** [comment]
please provide the requested information so we can help you debug the issue
