### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by KiranParigi** [ContinuumIO/anaconda-issues#9671]
### Actual Behavior
Not able to open Anaconda

##### `conda info`

```

```

##### `conda list --show-channel-urls`

```

```Traceback (most recent call last):
  File "D:\Users\KiranPS\Anaconda\lib\site-packages\anaconda_navigator\exceptions.py", line 75, in exception_handler
    return_value = func(*args, **kwargs)
  File "D:\Users\KiranPS\Anaconda\lib\site-packages\anaconda_navigator\app\start.py", line 150, in start_app
    window = run_app(splash)
  File "D:\Users\KiranPS\Anaconda\lib\site-packages\anaconda_navigator\app\start.py", line 65, in run_app
    window = MainWindow(splash=splash, tab_project=False)
  File "D:\Users\KiranPS\Anaconda\lib\site-packages\anaconda_navigator\widgets\main_window.py", line 163, in __init__
    self.api = AnacondaAPI()
  File "D:\Users\KiranPS\Anaconda\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 2185, in AnacondaAPI
    ANACONDA_API = _AnacondaAPI()
  File "D:\Users\KiranPS\Anaconda\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 89, in __init__
    self._conda_api = CondaAPI()
  File "D:\Users\KiranPS\Anaconda\lib\site-packages\anaconda_navigator\api\conda_api.py", line 1714, in CondaAPI
    CONDA_API = _CondaAPI()
  File "D:\Users\KiranPS\Anaconda\lib\site-packages\anaconda_navigator\api\conda_api.py", line 353, in __init__
    self.sys_rc_path = join(self.ROOT_PREFIX, '.condarc')
  File "D:\Users\KiranPS\Anaconda\lib\ntpath.py", line 76, in join
    path = os.fspath(path)
TypeError: expected str, bytes or os.PathLike object, not NoneType

**Comment by goanpeca** [comment]
@KiranParigi please provide the requested information so we can debug the issue

**Comment by KiranParigi** [comment]
@goanpeca Thanks for the quick response.

I was trying to open Anaconda Navigator and it is giving the error. Please find the error report below:


# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "D:\Users\KiranPS\Anaconda\lib\site-packages\conda\exceptions.py",
ne 819, in __call__
        return func(*args, **kwargs)
      File "D:\Users\KiranPS\Anaconda\lib\site-packages\conda\cli\main.py", li
 74, in _main
        context.__init__(argparse_args=args)
      File "D:\Users\KiranPS\Anaconda\lib\site-packages\conda\base\context.py"
line 236, in __init__
        argparse_args=argparse_args)
      File "D:\Users\KiranPS\Anaconda\lib\site-packages\conda\common\configura
on.py", line 722, in __init__
        self._set_search_path(search_path)
      File "D:\Users\KiranPS\Anaconda\lib\site-packages\conda\common\configura
on.py", line 728, in _set_search_path
        self._set_raw_data(load_file_configs(search_path))
      File "D:\Users\KiranPS\Anaconda\lib\site-packages\conda\common\configura
on.py", line 369, in load_file_configs
        raw_data = odict(kv for kv in chain.from_iterable(load_paths))
      File "D:\Users\KiranPS\Anaconda\lib\site-packages\conda\common\configura
on.py", line 369, in <genexpr>
        raw_data = odict(kv for kv in chain.from_iterable(load_paths))
      File "D:\Users\KiranPS\Anaconda\lib\site-packages\conda\common\configura
on.py", line 344, in _file_yaml_loader
        yield fullpath, YamlRawParameter.make_raw_parameters_from_file(fullpat

      File "D:\Users\KiranPS\Anaconda\lib\site-packages\conda\common\configura
on.py", line 332, in make_raw_parameters_from_file
        ruamel_yaml = yaml_load(fh)
      File "D:\Users\KiranPS\Anaconda\lib\site-packages\conda\common\serialize
y", line 54, in yaml_load
        return yaml.load(string, Loader=yaml.RoundTripLoader, version="1.2")
      File "D:\Users\KiranPS\Anaconda\lib\site-packages\ruamel_yaml\main.py",
ne 637, in load
        loader = Loader(stream, version, preserve_quotes=preserve_quotes)
      File "D:\Users\KiranPS\Anaconda\lib\site-packages\ruamel_yaml\loader.py"
line 59, in __init__
        Reader.__init__(self, stream, loader=self)
      File "D:\Users\KiranPS\Anaconda\lib\site-packages\ruamel_yaml\reader.py"
line 80, in __init__
        self.stream = stream  # type: Any  # as .read is called
      File "D:\Users\KiranPS\Anaconda\lib\site-packages\ruamel_yaml\reader.py"
line 125, in stream
        self.determine_encoding()
      File "D:\Users\KiranPS\Anaconda\lib\site-packages\ruamel_yaml\reader.py"
line 180, in determine_encoding
        self.update(1)
      File "D:\Users\KiranPS\Anaconda\lib\site-packages\ruamel_yaml\reader.py"
line 241, in update
        self.check_printable(data)
      File "D:\Users\KiranPS\Anaconda\lib\site-packages\ruamel_yaml\reader.py"
line 208, in check_printable
        'unicode', "special characters are not allowed")
    ruamel_yaml.reader.ReaderError: unacceptable character #x0000: special cha
cters are not allowed
      in "D:\Users\KiranPS\.condarc", position 0

`$ D:\Users\KiranPS\Anaconda\Scripts\conda list`

  environment variables:
                 CIO_TEST=<not set>
               CONDA_ROOT=D:\Users\KiranPS\Anaconda
                 HOMEPATH=\Users\KiranPS
                     PATH=D:\Windows\system32;D:\Windows;D:\Windows\System32\W
m;D:\Windows\Sys
                          tem32\WindowsPowerShell\v1.0\;D:\Users\KiranPS\Anaco
a;D:\Users\Kiran
                          PS\Anaconda\Library\mingw-w64\bin;D:\Users\KiranPS\A
conda\Library\us
                          r\bin;D:\Users\KiranPS\Anaconda\Library\bin;D:\Users
iranPS\Anaconda\
                          Scripts;D:\Users\KiranPS\AppData\Local\Programs\Pyth
\Python36\Script
                          s\;D:\Users\KiranPS\AppData\Local\Programs\Python\Py
on36\;D:\Windows
                          \system32;D:\Windows;D:\Windows\System32\Wbem;D:\Win
ws\System32\Wind
                          owsPowerShell\v1.0\;D:\Users\KiranPS\AppData\Local\P
grams\Python\Pyt
                          hon37\Scripts\;D:\Users\KiranPS\AppData\Local\Progra
\Python\Python37
                          \;D:\Program Files\Microsoft VS Code\bin;D:\Python34
:\Python34\Scrip
                          ts;D:\Users\KiranPS\AppData\Local\Programs\MiKTeX 2.
miktex\bin\x64\
             PSMODULEPATH=D:\Windows\system32\WindowsPowerShell\v1.0\Modules\
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>

     active environment : None
       user config file : D:\Users\KiranPS\.condarc
 populated config files :
          conda version : 4.5.4
    conda-build version : 3.10.5
         python version : 3.6.5.final.0
       base environment : D:\Users\KiranPS\Anaconda  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/win-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/win-64
                          https://repo.anaconda.com/pkgs/pro/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : D:\Users\KiranPS\Anaconda\pkgs
                          D:\Users\KiranPS\AppData\Local\conda\conda\pkgs
       envs directories : D:\Users\KiranPS\Anaconda\envs
                          D:\Users\KiranPS\AppData\Local\conda\conda\envs
                          D:\Users\KiranPS\.conda\envs
               platform : win-64
             user-agent : conda/4.5.4 requests/2.18.4 CPython/3.6.5 Windows/8.
Windows/6.3.9600
          administrator : False
             netrc file : None
           offline mode : False


An unexpected error has occurred. Conda has prepared the above report.
If submitted, this report will be used by core maintainers to improve
future releases of conda.
Would you like conda to send this report to the core maintainers?
[y/N]:


Check and let me know if you need any further details.

Thanks, Kiran

**Comment by KiranParigi** [comment]
Dear  Gonzalo Peña-Castellanos,

Thanks for the quick response.

I was trying to open Anaconda Navigator and it is giving the error. Please
find the error report below:
>>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

Traceback (most recent call last):
  File "D:\Users\KiranPS\Anaconda\lib\site-packages\conda\exceptions.py",

ne 819, in *call*
return func(*args, **kwargs)
File "D:\Users\KiranPS\Anaconda\lib\site-packages\conda\cli\main.py", li
74, in _main
context.*init*(argparse_args=args)
File "D:\Users\KiranPS\Anaconda\lib\site-packages\conda\base\context.py"
line 236, in *init*
argparse_args=argparse_args)
File "D:\Users\KiranPS\Anaconda\lib\site-packages\conda\common\configura
on.py", line 722, in *init*
self._set_search_path(search_path)
File "D:\Users\KiranPS\Anaconda\lib\site-packages\conda\common\configura
on.py", line 728, in _set_search_path
self._set_raw_data(load_file_configs(search_path))
File "D:\Users\KiranPS\Anaconda\lib\site-packages\conda\common\configura
on.py", line 369, in load_file_configs
raw_data = odict(kv for kv in chain.from_iterable(load_paths))
File "D:\Users\KiranPS\Anaconda\lib\site-packages\conda\common\configura
on.py", line 369, in
raw_data = odict(kv for kv in chain.from_iterable(load_paths))
File "D:\Users\KiranPS\Anaconda\lib\site-packages\conda\common\configura
on.py", line 344, in _file_yaml_loader
yield fullpath, YamlRawParameter.make_raw_parameters_from_file(fullpat

  File "D:\Users\KiranPS\Anaconda\lib\site-packages\conda\common\configura

on.py", line 332, in make_raw_parameters_from_file
ruamel_yaml = yaml_load(fh)
File "D:\Users\KiranPS\Anaconda\lib\site-packages\conda\common\serialize
y", line 54, in yaml_load
return yaml.load(string, Loader=yaml.RoundTripLoader, version="1.2")
File "D:\Users\KiranPS\Anaconda\lib\site-packages\ruamel_yaml\main.py",
ne 637, in load
loader = Loader(stream, version, preserve_quotes=preserve_quotes)
File "D:\Users\KiranPS\Anaconda\lib\site-packages\ruamel_yaml\loader.py"
line 59, in *init*
Reader.*init*(self, stream, loader=self)
File "D:\Users\KiranPS\Anaconda\lib\site-packages\ruamel_yaml\reader.py"
line 80, in *init*
self.stream = stream # type: Any # as .read is called
File "D:\Users\KiranPS\Anaconda\lib\site-packages\ruamel_yaml\reader.py"
line 125, in stream
self.determine_encoding()
File "D:\Users\KiranPS\Anaconda\lib\site-packages\ruamel_yaml\reader.py"
line 180, in determine_encoding
self.update(1)
File "D:\Users\KiranPS\Anaconda\lib\site-packages\ruamel_yaml\reader.py"
line 241, in update
self.check_printable(data)
File "D:\Users\KiranPS\Anaconda\lib\site-packages\ruamel_yaml\reader.py"
line 208, in check_printable
'unicode', "special characters are not allowed")
ruamel_yaml.reader.ReaderError: unacceptable character #x0000: special cha
cters are not allowed
in "D:\Users\KiranPS.condarc", position 0

$ D:\Users\KiranPS\Anaconda\Scripts\conda list

environment variables:
CIO_TEST=
CONDA_ROOT=D:\Users\KiranPS\Anaconda
HOMEPATH=\Users\KiranPS
PATH=D:\Windows\system32;D:\Windows;D:\Windows\System32\W
m;D:\Windows\Sys
tem32\WindowsPowerShell\v1.0;D:\Users\KiranPS\Anaco
a;D:\Users\Kiran
PS\Anaconda\Library\mingw-w64\bin;D:\Users\KiranPS\A
conda\Library\us
r\bin;D:\Users\KiranPS\Anaconda\Library\bin;D:\Users
iranPS\Anaconda
Scripts;D:\Users\KiranPS\AppData\Local\Programs\Pyth
\Python36\Script
s;D:\Users\KiranPS\AppData\Local\Programs\Python\Py
on36;D:\Windows
\system32;D:\Windows;D:\Windows\System32\Wbem;D:\Win
ws\System32\Wind
owsPowerShell\v1.0;D:\Users\KiranPS\AppData\Local\P
grams\Python\Pyt
hon37\Scripts;D:\Users\KiranPS\AppData\Local\Progra
\Python\Python37
;D:\Program Files\Microsoft VS Code\bin;D:\Python34
:\Python34\Scrip
ts;D:\Users\KiranPS\AppData\Local\Programs\MiKTeX 2.
miktex\bin\x64
PSMODULEPATH=D:\Windows\system32\WindowsPowerShell\v1.0\Modules
REQUESTS_CA_BUNDLE=
SSL_CERT_FILE=

 active environment : None
   user config file : D:\Users\KiranPS\.condarc

populated config files :
conda version : 4.5.4
conda-build version : 3.10.5
python version : 3.6.5.final.0
base environment : D:\Users\KiranPS\Anaconda (writable)
channel URLs : https://repo.anaconda.com/pkgs/main/win-64
https://repo.anaconda.com/pkgs/main/noarch
https://repo.anaconda.com/pkgs/free/win-64
https://repo.anaconda.com/pkgs/free/noarch
https://repo.anaconda.com/pkgs/r/win-64
https://repo.anaconda.com/pkgs/r/noarch
https://repo.anaconda.com/pkgs/pro/win-64
https://repo.anaconda.com/pkgs/pro/noarch
https://repo.anaconda.com/pkgs/msys2/win-64
https://repo.anaconda.com/pkgs/msys2/noarch
package cache : D:\Users\KiranPS\Anaconda\pkgs
D:\Users\KiranPS\AppData\Local\conda\conda\pkgs
envs directories : D:\Users\KiranPS\Anaconda\envs
D:\Users\KiranPS\AppData\Local\conda\conda\envs
D:\Users\KiranPS.conda\envs
platform : win-64
user-agent : conda/4.5.4 requests/2.18.4 CPython/3.6.5 Windows/8.
Windows/6.3.9600
administrator : False
netrc file : None
offline mode : False

An unexpected error has occurred. Conda has prepared the above report.
If submitted, this report will be used by core maintainers to improve
future releases of conda.
Would you like conda to send this report to the core maintainers?
[y/N]:

Check and let me know if you need any further details.

Thanks, Kiran


Thanks and Regards,
Kiran.

**Comment by goanpeca** [comment]
Please delete this file

` D:\Users\KiranPS\.condarc`

**Comment by KiranParigi** [comment]
Thanks  Gonzalo Peña-Castellanos,

Its working fine now.

Regards, Kiran.

Thanks and Regards,
Kiran.
