### ISSUE TITLE
ERROR anaconda_api.is_vscode_available:956 && jupyter does not run

### ISSUE THREAD

**Issue by magdalenat** [ContinuumIO/anaconda-issues#9675]
### Actual Behavior

When run anaconda-navigator, error as reported in topic appears. 
The additional "effect" is that Jupyter runs neither from a terminal, nor from Anaconda-Navigator produce the following output:
```
user@local~$jupyter-notebook
gcc: error: unrecognized command line option ‘-R’
Traceback (most recent call last):
  File "/home/magt/anaconda3/bin/jupyter-notebook", line 7, in <module>
    from notebook.notebookapp import main
  File "/home/magt/anaconda3/lib/python3.6/site-packages/notebook/notebookapp.py", line 45, in <module>
    from zmq.eventloop import ioloop
  File "/home/magt/anaconda3/lib/python3.6/site-packages/zmq/__init__.py", line 47, in <module>
    from zmq import backend
  File "/home/magt/anaconda3/lib/python3.6/site-packages/zmq/backend/__init__.py", line 40, in <module>
    reraise(*exc_info)
  File "/home/magt/anaconda3/lib/python3.6/site-packages/zmq/utils/sixcerpt.py", line 34, in reraise
    raise value
  File "/home/magt/anaconda3/lib/python3.6/site-packages/zmq/backend/__init__.py", line 27, in <module>
    _ns = select_backend(first)
  File "/home/magt/anaconda3/lib/python3.6/site-packages/zmq/backend/select.py", line 26, in select_backend
    mod = __import__(name, fromlist=public_api)
  File "/home/magt/anaconda3/lib/python3.6/site-packages/zmq/backend/cython/__init__.py", line 6, in <module>
    from . import (constants, error, message, context,
ImportError: libsodium.so.23: cannot open shared object file: No such file or directory
```

### Expected Behavior
Have running anaconda navigator without errors AND have working Jupyter

### Steps to Reproduce
"A" scenario: 

* Run anaconda-navigator from terminal.
* Click  "Launch" on  "Notebook" section from Navigator

"B" scenario:
type `jupyter notebook` or `jupyter-notebook` in terminal

##### Anaconda or Miniconda version:
conda version 4.5.4
navigator 1.8.7

##### Operating System:
LMDE2 (Mint Debian Edition)

##### `conda info`
```
     active environment : None
       user config file : /home/magt/.condarc
 populated config files : /home/magt/.condarc
          conda version : 4.5.4
    conda-build version : 3.0.23
         python version : 3.6.2.final.0
       base environment : /home/magt/anaconda3  (writable)
           channel URLs : https://conda.anaconda.org/david_baddeley/linux-64
                          https://conda.anaconda.org/david_baddeley/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/linux-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/linux-64
                          https://repo.anaconda.com/pkgs/pro/noarch
          package cache : /home/magt/anaconda3/pkgs
                          /home/magt/.conda/pkgs
       envs directories : /home/magt/anaconda3/envs
                          /home/magt/.conda/envs
               platform : linux-64
             user-agent : conda/4.5.4 requests/2.18.4 CPython/3.6.2 Linux/3.16.0-4-amd64 linuxmint/2 glibc/2.19
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False
```

##### `conda list --show-channel-urls`

```
# Name                    Version                   Build  Channel
_ipyw_jlab_nb_ext_conf    0.1.0            py36he11e457_0    defaults
alabaster                 0.7.10           py36h306e16b_0    defaults
anaconda                  custom                   py36_0    defaults
anaconda-client           1.6.14                   py36_0    defaults
anaconda-navigator        1.8.7                    py36_0    defaults
anaconda-project          0.8.0            py36h29abdf5_0    defaults
anyqt                     0.0.8                    py36_0    defaults
asn1crypto                0.22.0           py36h265ca7c_1    defaults
astor                     0.6.2                     <pip>
astroid                   1.5.3            py36hbdb9df2_0    defaults
astropy                   2.0.2            py36ha51211e_4    defaults
autobahn                  17.10.1                    py_0    vpython
babel                     2.5.0            py36h7d14adf_0    defaults
backports                 1.0              py36hfa02d7e_1    defaults
backports.shutil_get_terminal_size 1.0.0            py36hfea85ff_2    defaults
beautifulsoup4            4.6.0            py36h49b8c8c_1    defaults
bitarray                  0.8.1            py36h5834eb8_0    defaults
bkcharts                  0.2              py36h735825a_0    defaults
blaze                     0.11.3           py36h4e06776_0    defaults
bleach                    2.0.0            py36h688b259_0    defaults
bokeh                     0.12.7           py36h169c5fd_1    defaults
boto                      2.48.0           py36h6e4cd66_1    defaults
bottleneck                1.2.1            py36haac1ea0_0    defaults
bowtie                    0.7.0                     <pip>
bzip2                     1.0.6                h0376d23_1    defaults
ca-certificates           2018.4.16                     0    conda-forge
cairo                     1.14.10              hdf128ce_6    defaults
certifi                   2018.4.16                py36_0    defaults
cffi                      1.10.0           py36had8d393_1    defaults
chardet                   3.0.4            py36h0f667ec_1    defaults
click                     6.7              py36h5253387_0    defaults
cloudpickle               0.4.0            py36h30f8c20_0    defaults
clyent                    1.2.2            py36h7e57e65_1    defaults
colorama                  0.3.9            py36h489cec4_0    defaults
commonmark                0.7.5                    py36_0    defaults
conda                     4.5.4                    py36_0    defaults
conda-build               3.0.23           py36h1da9bb0_0    defaults
conda-env                 2.6.0                h36134e3_1    defaults
conda-verify              2.0.0            py36h98955d8_0    defaults
contextlib2               0.5.5            py36h6c84a62_0    defaults
cryptography              2.0.3            py36ha225213_1    defaults
curl                      7.55.1               hcb0b314_2    defaults
cycler                    0.10.0           py36h93f1223_0    defaults
cyrus-sasl                2.1.26               h1dd3434_1    defaults
cython                    0.26.1           py36h21c49d0_0    defaults
cytoolz                   0.8.2            py36h708bfd4_0    defaults
dash                      0.21.1                     py_1    conda-forge
dash                      0.20.0                    <pip>
dash-core-components      0.18.1                    <pip>
dash-html-components      0.8.0                     <pip>
dash-renderer             0.11.3                    <pip>
dash-renderer             0.12.1                     py_1    conda-forge
dask                      0.15.2           py36h9b48dc4_0    defaults
dask-core                 0.15.2           py36h0f988a8_0    defaults
datashape                 0.5.4            py36h3ad6b5c_0    defaults
dbus                      1.10.22              h3b5a359_0    defaults
decorator                 4.2.1                     <pip>
decorator                 4.1.2            py36hd076ac8_0    defaults
dill                      0.2.6                    py36_0    defaults
distributed               1.18.3           py36h73cd4ae_0    defaults
docutils                  0.14             py36hb0f60f5_0    defaults
entrypoints               0.2.3            py36h1aec115_2    defaults
enum34                    1.1.6                     <pip>
et_xmlfile                1.0.1            py36hd6bccc3_0    defaults
eventlet                  0.22.0                    <pip>
expat                     2.2.4                hc00ebd1_1    defaults
fastcache                 1.0.2            py36h5b0c431_0    defaults
filelock                  2.0.12           py36hacfa1f5_0    defaults
flask                     0.12.2           py36hb24657c_0    defaults
flask-compress            1.4.0                      py_0    conda-forge
Flask-Compress            1.4.0                     <pip>
flask-cors                3.0.3            py36h2d857d3_0    defaults
Flask-SocketIO            2.9.3                     <pip>
font-ttf-dejavu-sans-mono 2.37                          0    defaults
font-ttf-inconsolata      2.000                         0    defaults
font-ttf-source-code-pro  2.030                         0    defaults
font-ttf-ubuntu           0.83                          0    defaults
fontconfig                2.12.4               h88586e7_1    defaults
fonts-anaconda            1                    h8fa9717_0    defaults
fonts-continuum           1                             0    defaults
freeglut                  2.8.1                         0    defaults
freetype                  2.8                  hab7d2ae_1    defaults
future                    0.16.0                    <pip>
future                    0.16.0                   py36_1    defaults
get_terminal_size         1.0.0                haa9412d_0    defaults
gevent                    1.2.2            py36h2fe25dc_0    defaults
glib                      2.53.6               h5d9569c_2    defaults
glob2                     0.5              py36h2c1b292_1    defaults
glue-core                 0.12.3           py36h15cce50_0    defaults
glue-vispy-viewers        0.9              py36h491feeb_0    defaults
glueviz                   0.12.0               ha37a3ef_0    defaults
gmp                       6.1.2                hb3b607b_0    defaults
gmpy2                     2.0.8            py36h55090d7_1    defaults
graphite2                 1.3.10               hc526e54_0    defaults
greenlet                  0.4.12           py36h2d503a6_0    defaults
gsl                       2.2.1                h0743c53_2    defaults
gst-plugins-base          1.12.2               he3457e5_0    defaults
gstreamer                 1.12.2               h4f93127_0    defaults
h5py                      2.7.0            py36he81ebca_1    defaults
harfbuzz                  1.5.0                h2545bd6_0    defaults
hdf5                      1.10.1               hb0523eb_0    defaults
heapdict                  1.0.0            py36h79797d7_0    defaults
hide-code                 0.5.0                     <pip>
html5lib                  0.999999999      py36h2cfc398_0    defaults
icu                       58.2                 h9c2bf20_1    defaults
idna                      2.6              py36h82fb2a8_1    defaults
imageio                   2.2.0            py36he555465_0    defaults
imagesize                 0.7.1            py36h52d8127_0    defaults
intel-openmp              2018.0.0             h15fc484_7    defaults
ipykernel                 4.7.0            py36h2f9c1c0_0    defaults
ipython                   6.1.0            py36hc72a948_1    defaults
ipython_genutils          0.2.0            py36hb52b0d5_0    defaults
ipywidgets                7.0.0            py36h7b55c3a_0    defaults
isort                     4.2.15           py36had401c0_0    defaults
itsdangerous              0.24             py36h93cc618_1    defaults
jbig                      2.1                  hdba287a_0    defaults
jdcal                     1.3              py36h4c697fb_0    defaults
jedi                      0.10.2           py36h552def0_0    defaults
jedi                      0.12.0                    <pip>
jeepney                   0.3.1                     <pip>
jinja2                    2.9.6            py36h489bce4_1    defaults
joblib                    0.11                     py36_0    defaults
jpeg                      9b                   h024ee3a_2    defaults
jsonschema                2.6.0            py36h006f8b5_0    defaults
jupyter                   1.0.0                     <pip>
jupyter                   1.0.0            py36h9896ce5_0    defaults
jupyter-core              4.4.0                     <pip>
jupyter_client            5.2.3                    py36_0    defaults
jupyter_console           5.2.0            py36he59e554_1    defaults
jupyter_core              4.4.0            py36h7c827e3_0    defaults
jupyterlab                0.30.6           py36h2f9c1c0_0    defaults
jupyterlab_launcher       0.6.0                    py36_0    defaults
keyring                   9.3.1                    py36_0    defaults
keyrings.alt              3.0                      py36_0    defaults
krb5                      1.14.2               h56d4222_4    defaults
lazy-object-proxy         1.3.1            py36h10fcdad_0    defaults
libedit                   3.1                  heed3624_0    defaults
libffi                    3.2.1                h4deb6c0_3    defaults
libgcc                    7.2.0                h69d50b8_2    defaults
libgcc-ng                 7.2.0                hcbc56d2_1    defaults
libgfortran-ng            7.2.0                h6fcbd8e_1    defaults
libiconv                  1.14                          0    defaults
libntlm                   1.4                  hbaadc6b_1    defaults
libpng                    1.6.32               hda9c8bc_2    defaults
libsodium                 1.0.13               h31c71d8_2    defaults
libssh2                   1.8.0                h8c220ad_2    defaults
libstdcxx-ng              7.2.0                h24385c6_1    defaults
libtiff                   4.0.9                h28f6b97_0    defaults
libtiff                   0.4.1                     <pip>
libtool                   2.4.6                hd50d1a6_0    defaults
libuuid                   1.0.3                h5bb35a6_1    defaults
libxcb                    1.12                 he6ee5dd_2    defaults
libxml2                   2.9.4                         0    defaults
libxslt                   1.1.29                        0    defaults
llvmlite                  0.20.0                   py36_0    defaults
locket                    0.2.0            py36h787c0ad_1    defaults
lxml                      3.8.0            py36h6c6e760_0    defaults
lzo                       2.10                 hc0eb8fc_0    defaults
Markdown                  2.6.11                    <pip>
markupsafe                1.0              py36hd9260cd_1    defaults
matplotlib                2.1.0            py36hba5de38_0    defaults
mccabe                    0.6.1            py36h5ad9710_1    defaults
mistune                   0.7.4            py36hbab8784_0    defaults
mkl                       2018.0.0             hb491cac_4    defaults
mkl-service               1.1.2            py36h17a0993_4    defaults
mpc                       1.0.3                hf803216_4    defaults
mpfr                      3.1.5                h12ff648_1    defaults
mpmath                    0.19             py36h8cc018b_2    defaults
msgpack-python            0.4.8            py36hec4c5d1_0    defaults
multipledispatch          0.4.9            py36h41da3fb_0    defaults
navigator-updater         0.1.0            py36h14770f7_0    defaults
nbconvert                 5.3.1            py36hb41ffb7_0    defaults
nbformat                  4.4.0            py36h31c9010_0    defaults
ncurses                   6.0                  h06874d7_1    defaults
networkx                  1.11             py36hfb3574a_0    defaults
nltk                      3.2.4            py36h1a0979f_0    defaults
nodejs                    8.9.3                         0    conda-forge
nose                      1.3.7            py36hcdf7029_2    defaults
notebook                  5.5.0                    py36_0    defaults
numba                     0.35.0             np113py36_10    defaults
numexpr                   2.6.2            py36hdd3393f_1    defaults
numpy                     1.13.1           py36h5bc529a_2    defaults
numpydoc                  0.7.0            py36h18f165f_0    defaults
odo                       0.5.1            py36h90ed295_0    defaults
olefile                   0.44             py36h79f9f78_0    defaults
openpyxl                  2.4.8            py36h41dd2a8_1    defaults
openssl                   1.0.2o               h20670df_0    defaults
orange3                   3.13.0           py36h637b7d7_0    defaults
packaging                 16.8             py36ha668100_1    defaults
pandas                    0.20.3           py36h842e28d_2    defaults
pandoc                    1.19.2.1             hea2e7c5_1    defaults
pandocfilters             1.4.2            py36ha6701b7_1    defaults
pango                     1.40.11              h8191d47_0    defaults
parso                     0.2.0                     <pip>
partd                     0.3.8            py36h36fd896_0    defaults
patchelf                  0.9                  hf79760b_2    defaults
path.py                   10.3.1           py36he0c6f6d_0    defaults
pathlib2                  2.3.0            py36h49efa8e_0    defaults
patsy                     0.4.1            py36ha3be15e_0    defaults
pcre                      8.39                          1    defaults
pdfkit                    0.6.1                     <pip>
pep8                      1.7.0            py36h26ade29_0    defaults
pexpect                   4.2.1            py36h3b9d41b_0    defaults
pickleshare               0.7.4            py36h63277f8_0    defaults
pillow                    4.3.0            py36h6f462bf_1    defaults
pip                       10.0.1                    <pip>
pip                       9.0.1            py36h30f8307_2    defaults
pixman                    0.34.0               ha72d70b_1    defaults
pkginfo                   1.4.1            py36h215d178_1    defaults
plotly                    2.5.1                    py36_0    defaults
plotly                    2.3.0                     <pip>
pluggy                    0.6.0                     <pip>
ply                       3.10             py36hed35086_0    defaults
prompt_toolkit            1.0.15           py36h17d85b1_0    defaults
psutil                    5.2.2            py36h74c8701_0    defaults
ptyprocess                0.5.2            py36h69acd42_0    defaults
py                        1.4.34           py36h0712aa3_1    defaults
pycodestyle               2.3.1            py36hf609f19_0    defaults
pycosat                   0.6.3            py36h0a5515d_0    defaults
pycparser                 2.18             py36hf9f622e_1    defaults
pycrypto                  2.6.1            py36h6998063_1    defaults
pycurl                    7.43.0           py36h5e72054_3    defaults
pyflakes                  1.5.0            py36h5510808_1    defaults
pygit2                    0.27.0                    <pip>
pygments                  2.2.0            py36h0d3125c_0    defaults
pylint                    1.7.2            py36h484ab97_0    defaults
pyodbc                    4.0.17           py36h999153c_0    defaults
pyopengl                  3.1.1a1             np113py36_0    defaults
pyopenssl                 17.2.0           py36h5cc804b_0    defaults
pyparsing                 2.2.0            py36hee85983_1    defaults
pyqt                      5.6.0                    py36_2    defaults
PyQt5                     5.10.1                    <pip>
pyqtgraph                 0.10.0                   py36_0    defaults
pysocks                   1.6.7            py36hd97a5b1_1    defaults
pytables                  3.4.2            py36hdce54c9_1    defaults
pytest                    3.2.1            py36h11ad3bb_1    defaults
python                    3.6.2               hdfe5801_15    defaults
python-dateutil           2.6.1            py36h88d3b88_1    defaults
python-engineio           2.0.2                     <pip>
python-language-server    0.18.0                    <pip>
python-socketio           1.8.4                     <pip>
pythreejs                 0.4.1                    py36_0    conda-forge
pytz                      2017.3                    <pip>
pytz                      2017.2           py36hc2ccc2a_1    defaults
pywavelets                0.5.2            py36he602eb0_0    defaults
pyyaml                    3.12             py36hafb9ca4_1    defaults
pyzmq                     17.0.0           py36h14c3975_0    defaults
qt                        5.6.2               h974d657_12    defaults
qtawesome                 0.4.4            py36h609ed8c_0    defaults
qtconsole                 4.3.1            py36h8f73b5b_0    defaults
qtpy                      1.4.1                    py36_0    defaults
r-assertthat              0.2.0            r342h06193eb_0    defaults
r-backports               1.1.1            r342h9a9f1f2_0    defaults
r-base                    3.4.2                haf99962_0    defaults
r-base64enc               0.1_3            r342h7c929ec_4    defaults
r-bh                      1.65.0_1         r342h2d7c2ce_0    defaults
r-bindr                   0.1              r342hdee8079_0    defaults
r-bindrcpp                0.2              r342h4ea5b31_0    defaults
r-bit                     1.1_12           r342h7a05cba_0    defaults
r-bit64                   0.9_7            r342hcc44603_0    defaults
r-bitops                  1.0_6            r342hd891396_4    defaults
r-blob                    1.1.0            r342hf606c5c_0    defaults
r-boot                    1.3_20           r342ha5ac741_0    defaults
r-broom                   0.4.2            r342h90c284a_0    defaults
r-car                     2.1_5            r342h9479375_0    defaults
r-caret                   6.0_77           r342h201f268_0    defaults
r-catools                 1.17.1           r342hf01772b_4    defaults
r-cellranger              1.1.0            r342h51baf57_0    defaults
r-class                   7.3_14           r342h4797347_4    defaults
r-cluster                 2.0.6            r342hcb72a25_0    defaults
r-codetools               0.2_15           r342hc9ffb9b_0    defaults
r-colorspace              1.3_2            r342h81b277d_0    defaults
r-config                  0.2              r342hcf13b6a_0    defaults
r-crayon                  1.3.4            r342h0ed458a_0    defaults
r-curl                    3.0              r342hba591e3_0    defaults
r-cvst                    0.2_1            r342h830f301_0    defaults
r-data.table              1.10.4_1         r342h3908b10_0    defaults
r-dbi                     0.7              r342h835dbd3_0    defaults
r-dbplyr                  1.1.0            r342h3750f00_0    defaults
r-ddalpha                 1.3.1            r342hd2d3f94_0    defaults
r-deoptimr                1.0_8            r342h996e1ad_0    defaults
r-dichromat               2.0_0            r342h341c752_4    defaults
r-digest                  0.6.12           r342hee14287_0    defaults
r-dimred                  0.1.0            r342hb158d3e_0    defaults
r-dplyr                   0.7.4            r342hee63e26_0    defaults
r-drr                     0.0.2            r342h0fe108c_0    defaults
r-essentials              1.7.0            r342hf65ed6a_0    defaults
r-evaluate                0.10.1           r342hb679cc2_0    defaults
r-forcats                 0.2.0            r342h5fcb364_0    defaults
r-foreach                 1.4.3            r342h49221b0_4    defaults
r-foreign                 0.8_69           r342hbd6b6bb_0    defaults
r-formatr                 1.5              r342h0e06a18_0    defaults
r-ggplot2                 2.2.1            r342h8b6cf70_0    defaults
r-gistr                   0.4.0            r342h5cd5773_0    defaults
r-glmnet                  2.0_13           r342h0aac7f1_0    defaults
r-glue                    1.1.1            r342h3154e12_0    defaults
r-gower                   0.1.2            r342h54e18f5_0    defaults
r-gtable                  0.2.0            r342h8e3b2c8_0    defaults
r-haven                   1.1.0            r342h8909e7d_0    defaults
r-hexbin                  1.27.1           r342h72fd8d9_4    defaults
r-highr                   0.6              r342h2351100_0    defaults
r-hms                     0.3              r342ha729a9b_0    defaults
r-htmltools               0.3.6            r342h4080c21_0    defaults
r-htmlwidgets             0.9              r342h7fcc9b6_0    defaults
r-httpuv                  1.3.5            r342ha5ddd88_0    defaults
r-httr                    1.3.1            r342h7aba7de_0    defaults
r-ipred                   0.9_6            r342h7d58d5b_0    defaults
r-irdisplay               0.4.4            r342hc31a1b2_0    defaults
r-irkernel                0.8.9            r342hfe3cb8f_0    defaults
r-iterators               1.0.8            r342h4caec00_4    defaults
r-jsonlite                1.5              r342hf92f79e_0    defaults
r-kernlab                 0.9_25           r342hd770e69_0    defaults
r-kernsmooth              2.23_15          r342hdc3efa4_4    defaults
r-knitr                   1.17             r342h6500ef9_0    defaults
r-labeling                0.3              r342h7c30189_4    defaults
r-lattice                 0.20_35          r342h0f762c2_0    defaults
r-lava                    1.5.1            r342h598eca9_0    defaults
r-lazyeval                0.2.0            r342h346dbdc_0    defaults
r-lme4                    1.1_14           r342hc4ad05c_0    defaults
r-lubridate               1.6.0            r342h47739ec_0    defaults
r-magrittr                1.5              r342h895a831_4    defaults
r-maps                    3.2.0            r342h79c810f_0    defaults
r-markdown                0.8              r342h4cc6e3e_0    defaults
r-mass                    7.3_47           r342hd8605c9_0    defaults
r-matrix                  1.2_11           r342h3a55fe1_0    defaults
r-matrixmodels            0.4_1            r342hf12786b_4    defaults
r-mgcv                    1.8_22           r342h176cc83_0    defaults
r-mime                    0.5              r342h01856a9_0    defaults
r-miniui                  0.1.1            r342h33c7739_0    defaults
r-minqa                   1.2.4            r342h332e735_4    defaults
r-mnormt                  1.5_5            r342he1a489d_0    defaults
r-modelmetrics            1.1.0            r342h5a23eb1_0    defaults
r-modelr                  0.1.1            r342heb933ea_0    defaults
r-mongolite               1.2              r342hdcf03d2_0    defaults
r-munsell                 0.4.3            r342h79883fb_0    defaults
r-nlme                    3.1_131          r342h7f704e8_0    defaults
r-nloptr                  1.0.4            r342h3bea5cc_4    defaults
r-nnet                    7.3_12           r342ha98c111_0    defaults
r-numderiv                2016.8_1         r342h12eb246_0    defaults
r-odbc                    1.1.2            r342hf7c7794_0    defaults
r-openssl                 0.9.7            r342h1e3c16d_0    defaults
r-packrat                 0.4.8_1          r342h7bab2f7_0    defaults
r-pbdzmq                  0.2_6            r342h934a24f_0    defaults
r-pbkrtest                0.4_7            r342h26b13be_0    defaults
r-pkgconfig               2.0.1            r342h5d9b92e_0    defaults
r-pki                     0.1_5.1          r342hba91d42_0    defaults
r-plogr                   0.1_1            r342h6d7f4c2_0    defaults
r-plyr                    1.8.4            r342h876901b_0    defaults
r-prodlim                 1.6.1            r342hd95c883_0    defaults
r-profvis                 0.3.3            r342h36dbb6c_0    defaults
r-pryr                    0.1.2            r342hf3bf84b_0    defaults
r-psych                   1.7.8            r342h1e2dc86_0    defaults
r-purrr                   0.2.3            r342h7916a1c_0    defaults
r-quantmod                0.4_11           r342h9c9c021_0    defaults
r-quantreg                5.33             r342hc2498b2_0    defaults
r-r6                      2.2.2            r342hcc750b5_0    defaults
r-randomforest            4.6_12           r342h41e62a9_4    defaults
r-rappdirs                0.3.1            r342h03ed50e_0    defaults
r-rbokeh                  0.5.0            r342h257354a_0    defaults
r-rcolorbrewer            1.1_2            r342h0dda8fb_0    defaults
r-rcpp                    0.12.13          r342h9f83869_0    defaults
r-rcppeigen               0.3.3.3.0        r342h1736bfc_0    defaults
r-rcpproll                0.2.2            r342hdd0cc16_0    defaults
r-rcurl                   1.95_4.8         r342hecb3894_0    defaults
r-readr                   1.1.1            r342hb25467c_0    defaults
r-readxl                  1.0.0            r342h1e5739b_0    defaults
r-recipes                 0.1.0            r342h0924b81_0    defaults
r-recommended             3.4.2                h1751db4_0    defaults
r-rematch                 1.0.1            r342he3f91f1_0    defaults
r-repr                    0.12.0           r342hde08b23_0    defaults
r-reshape2                1.4.2            r342h2e254a0_0    defaults
r-rjava                   0.9_9            r342h9890981_0    defaults
r-rjdbc                   0.2_5            r342he0388cf_0    defaults
r-rjsonio                 1.3_0            r342h5685322_4    defaults
r-rlang                   0.1.2            r342hc878738_0    defaults
r-rmarkdown               1.6              r342hacd9e3e_2    defaults
r-robustbase              0.92_7           r342h6021a74_0    defaults
r-rpart                   4.1_11           r342hd35cc14_0    defaults
r-rprojroot               1.2              r342hd69aa9e_0    defaults
r-rsconnect               0.8.5            r342h3a8d77b_0    defaults
r-rstudioapi              0.7              r342hedff9e9_0    defaults
r-rvest                   0.3.2            r342h8e81af5_0    defaults
r-scales                  0.5.0            r342h876bdd3_0    defaults
r-selectr                 0.3_1            r342hd6c1ff9_0    defaults
r-sfsmisc                 1.1_1            r342hadb04b4_0    defaults
r-shiny                   1.0.5            r342hc0a01ce_0    defaults
r-sourcetools             0.1.6            r342h519fec0_0    defaults
r-sparklyr                0.6.3            r342hac80a45_0    defaults
r-sparsem                 1.77             r342h5d35ddd_0    defaults
r-spatial                 7.3_11           r342hff2a1d0_4    defaults
r-stringi                 1.1.5            r342h15434fd_0    defaults
r-stringr                 1.2.0            r342h701d218_0    defaults
r-survival                2.41_3           r342hac888f2_0    defaults
r-tibble                  1.3.4            r342h041fa31_0    defaults
r-tidyr                   0.7.1            r342h1bc61e7_0    defaults
r-tidyselect              0.2.2            r342h04f720c_0    defaults
r-tidyverse               1.1.1            r342hf9e2102_0    defaults
r-timedate                3012.100         r342h48d2e88_4    defaults
r-ttr                     0.23_2           r342hf82c04a_0    defaults
r-uuid                    0.1_2            r342h1393287_4    defaults
r-viridislite             0.2.0            r342h3706391_0    defaults
r-withr                   2.0.0            r342hfa1897f_0    defaults
r-xml2                    1.1.1            r342h3ff9a91_0    defaults
r-xtable                  1.8_2            r342hb75f6e7_0    defaults
r-xts                     0.10_0           r342h17852d6_4    defaults
r-yaml                    2.1.14           r342h72d8650_0    defaults
r-zoo                     1.8_0            r342h9faeba2_0    defaults
readline                  7.0                  hac23ff0_3    defaults
requests                  2.18.4           py36he2e5f8d_1    defaults
rope                      0.10.5           py36h1f8c17e_0    defaults
rope-py3k                 0.9.4.post1               <pip>
rstudio                   1.1.383              h2c9cdda_2    defaults
ruamel_yaml               0.11.14          py36ha2fb22d_2    defaults
scikit-image              0.13.0           py36had3c07a_1    defaults
scikit-learn              0.19.0           py36h97ac459_2    defaults
scipy                     0.19.1           py36h9976243_3    defaults
seaborn                   0.8.0            py36h197244f_0    defaults
SecretStorage             3.0.1                     <pip>
selenium                  3.12.0                    <pip>
send2trash                1.5.0                    py36_0    defaults
serverfiles               0.2.1            py36h79d4018_0    defaults
setuptools                36.5.0           py36he42e2e1_0    defaults
simplegeneric             0.8.1            py36h2cb9092_0    defaults
singledispatch            3.4.0.3          py36h7a266c3_0    defaults
sip                       4.19.8                    <pip>
sip                       4.18.1           py36h51ed4ed_2    defaults
six                       1.10.0           py36hcac75e4_1    defaults
six                       1.11.0                    <pip>
snowballstemmer           1.2.1            py36h6febd40_0    defaults
sortedcollections         0.5.3            py36h3c761f9_0    defaults
sortedcontainers          1.5.7            py36hdf89491_0    defaults
sphinx                    1.6.3            py36he5f0bdb_0    defaults
sphinxcontrib             1.0              py36h6d0f590_1    defaults
sphinxcontrib-websupport  1.0.1            py36hb5cb234_1    defaults
spyder                    3.2.8                    py36_0    defaults
spyder-notebook           0.1.1                    py36_0    spyder-ide
spyder-unittest           0.2.0                    py36_0    spyder-ide
sqlalchemy                1.1.13           py36hfb5efd7_0    defaults
sqlite                    3.20.1               h6d8b0f3_1    defaults
statsmodels               0.8.0            py36h8533d0b_0    defaults
sympy                     1.1.1            py36hc6d1c1c_0    defaults
tblib                     1.3.2            py36h34cf8b6_0    defaults
terminado                 0.8.1                    py36_1    defaults
testpath                  0.3.1            py36h8cadb63_0    defaults
tifffile                  0.12.1                   py36_1    conda-forge
tk                        8.6.7                h5979e9b_1    defaults
toolz                     0.8.2            py36h81f2dff_0    defaults
tornado                   4.5.2            py36h1283b2a_0    defaults
tqdm                      4.19.4           py36ha5a5176_0    defaults
traitlets                 4.3.2            py36h674d592_0    defaults
traittypes                0.0.6                    py36_0    conda-forge
txaio                     2.8.2                      py_0    vpython
typing                    3.6.2            py36h7da032a_0    defaults
ujson                     1.35                     py36_0    defaults
unicodecsv                0.14.1           py36ha668878_0    defaults
unixodbc                  2.3.4                hc36303a_1    defaults
urllib3                   1.22             py36hbe7ace6_0    defaults
vpnotebook                0.1.3                    py36_1    vpython
vpython                   7.3.1                    py36_0    vpython
wcwidth                   0.1.7            py36hdf4376a_0    defaults
webencodings              0.5.1            py36h800622e_1    defaults
werkzeug                  0.12.2           py36hc703753_0    defaults
wheel                     0.29.0           py36he7f4e38_1    defaults
widgetsnbextension        3.0.2            py36hd01bb71_1    defaults
wrapt                     1.10.11          py36h28b7045_0    defaults
xlrd                      1.1.0            py36h1db9f0c_1    defaults
xlsxwriter                0.9.8            py36hf41c223_0    defaults
xlwt                      1.3.0            py36h7b00a1f_0    defaults
xz                        5.2.3                h2bcbf08_1    defaults
yaml                      0.1.7                h96e3832_1    defaults
yarn                      1.3.2                         0    conda-forge
zeromq                    4.2.3                h439df22_3    defaults
zict                      0.1.2            py36ha0d441b_0    defaults
zlib                      1.2.11               hfbfcf68_1    defaults
```
##### Additional info - 'suspect' and presumption
I noticed this issue after installing Visual Studio Code and extension for Jupyter (https://github.com/DonJayamanne/vscodejupyter), but I'm not sure if this cause a problem. It may also by any of the latest updates. About month ago both  Navigator and Jupyter  worked ok.

**Comment by imnasnainaec** [comment]
I had this issue and found the solution by chapmanb (https://github.com/bcbio/bcbio-nextgen/issues/2274) worked: `conda install -c conda-forge libsodium`

**Comment by AnaValero** [comment]
Hi,
I've been worked with anaconda_ete package today using EvolTree to test the models M0, M2, etc and suddenly, after just changed my data files, I got the error:
ERROR anaconda_api.is_vscode_available:956
Anaconda navigator also stops running

I'm having other new issues using the evol models  SLR, as it is not creating the outfile "out". I don't know if they are related.

The data seems to be ok since it does not produce error when using other complex commands of the ete3 package.

My OS: Linux Mint
Anaconda navigator 1.8.7

I have tried your suggestion:
conda install -c conda-forge libsodium
with no results.

Many thanks!
A
