### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by alletag** [ContinuumIO/anaconda-issues#9677]
Traceback (most recent call last):
  File "C:\Users\Acer\Anaconda3\lib\site-packages\anaconda_navigator\exceptions.py", line 75, in exception_handler
    return_value = func(*args, **kwargs)
  File "C:\Users\Acer\Anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 150, in start_app
    window = run_app(splash)
  File "C:\Users\Acer\Anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 65, in run_app
    window = MainWindow(splash=splash, tab_project=False)
  File "C:\Users\Acer\Anaconda3\lib\site-packages\anaconda_navigator\widgets\main_window.py", line 163, in __init__
    self.api = AnacondaAPI()
  File "C:\Users\Acer\Anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 2185, in AnacondaAPI
    ANACONDA_API = _AnacondaAPI()
  File "C:\Users\Acer\Anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 89, in __init__
    self._conda_api = CondaAPI()
  File "C:\Users\Acer\Anaconda3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 1714, in CondaAPI
    CONDA_API = _CondaAPI()
  File "C:\Users\Acer\Anaconda3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 350, in __init__
    self.set_conda_prefix(info=get_conda_info())
  File "C:\Users\Acer\Anaconda3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 505, in set_conda_prefix
    self.ROOT_PREFIX = info['root_prefix']
KeyError: 'root_prefix'

**After using**
`conda update conda conda-build
` in anaconda prompt it gives:

(base) C:\Users\Acer>conda install conda-build --force
Solving environment: done

## Package Plan ##

  environment location: C:\Users\Acer\Anaconda3

  added / updated specs:
    - conda-build

The following packages will be UPDATED:

    conda-build: 3.10.5-py36_0 --> 3.10.9-py36_0

Proceed ([y]/n)? y

Preparing transaction: done
Verifying transaction: failed

NotWritableError: The current user does not have write permissions to a required path.
  path: C:\Program Files\Java\jdk-9.0.4\bin\.conda\environments.txt

**Comment by goanpeca** [comment]
Please remember to update to the latest version of Navigator to include
the latest fixes.

Open a terminal (on Linux or Mac) or the Anaconda Command Prompt (on windows)
and type:

```
conda update conda
conda update --all
```

If you installed for `All users` you will need to open the `Anaconda Prompt` with elevated administrator privileges.
