### ISSUE TITLE
Implicit dependency in the ZeroMQ area

### ISSUE THREAD

**Issue by rolweber** [ContinuumIO/anaconda-issues#9702]
Platform: Linux x86_64

Steps to reproduce:
1. Install Miniconda
2. `conda create -n ZeroMQ python zeromq=4.2.3 libsodium=1.0.15 pyzmq=16.0.2`
3. `source activate ZeroMQ`
4. `python -c 'import zmq'`
Output:
```txt
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/rolweber/conda/envs/ZeroMQ/lib/python3.6/site-packages/zmq/__init__.py", line 34, in <module>
    from zmq import backend
  File "/home/rolweber/conda/envs/ZeroMQ/lib/python3.6/site-packages/zmq/backend/__init__.py", line 40, in <module>
    reraise(*exc_info)
  File "/home/rolweber/conda/envs/ZeroMQ/lib/python3.6/site-packages/zmq/utils/sixcerpt.py", line 34, in reraise
    raise value
  File "/home/rolweber/conda/envs/ZeroMQ/lib/python3.6/site-packages/zmq/backend/__init__.py", line 27, in <module>
    _ns = select_backend(first)
  File "/home/rolweber/conda/envs/ZeroMQ/lib/python3.6/site-packages/zmq/backend/select.py", line 26, in select_backend
    mod = __import__(name, fromlist=public_api)
  File "/home/rolweber/conda/envs/ZeroMQ/lib/python3.6/site-packages/zmq/backend/cython/__init__.py", line 6, in <module>
    from . import (constants, error, message, context,
ImportError: libzmq.so.5.1.2: cannot open shared object file: No such file or directory
```
Expected behavior: Step 2 should have warned about incompatible package versions.

Either upgrading `pyzmq` to 17.0.0 or downgrading `zeromq` to 4.2.2 lets step 4 succeed.

**Comment by rolweber** [comment]
This isn't about fixing a bug, it's about declaring a version dependency. Afaict, `pyzmq` 17.0.0 should require ZeroMQ 4.2.3 or later. Something in your build system generates a dependency on a specific library version that isn't reflected in your metadata.

**Comment by rolweber** [comment]
I remember running into this problem a year or two ago, with other versions of the packages. It's going to happen again in the future.

I can rephrase the description or open a new issue if that helps.

**Comment by mingwandroid** [comment]
> It's going to happen again in the future

I have our some fairly strong technical ok measures in place to help ensure it does not. We track DSOs now.

**Comment by rolweber** [comment]
I hope that works. But I still wish `conda` would have told me that I had to upgrade ZeroMQ when I tried to upgrade `pyzmq`. As you can see from this issue, it didn't. If it does next time, that would be great.
