### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by AIchild** [ContinuumIO/anaconda-issues#9711]
**Navigator Error**
An unexpected error occurred on Navigator start-up
**Main Error**
expected str, bytes or os.PathLike object, not NoneType
**Traceback**
Traceback (most recent call last):
  File "C:\Users\anmol singh\Anaconda3\lib\site-packages\anaconda_navigator\exceptions.py", line 75, in exception_handler
    return_value = func(*args, **kwargs)
  File "C:\Users\anmol singh\Anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 150, in start_app
    window = run_app(splash)
  File "C:\Users\anmol singh\Anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 65, in run_app
    window = MainWindow(splash=splash, tab_project=False)
  File "C:\Users\anmol singh\Anaconda3\lib\site-packages\anaconda_navigator\widgets\main_window.py", line 163, in __init__
    self.api = AnacondaAPI()
  File "C:\Users\anmol singh\Anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 2185, in AnacondaAPI
    ANACONDA_API = _AnacondaAPI()
  File "C:\Users\anmol singh\Anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 89, in __init__
    self._conda_api = CondaAPI()
  File "C:\Users\anmol singh\Anaconda3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 1714, in CondaAPI
    CONDA_API = _CondaAPI()
  File "C:\Users\anmol singh\Anaconda3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 353, in __init__
    self.sys_rc_path = join(self.ROOT_PREFIX, '.condarc')
  File "C:\Users\anmol singh\Anaconda3\lib\ntpath.py", line 76, in join
    path = os.fspath(path)
**_TypeError: expected str, bytes or os.PathLike object, not NoneType_**
-->

### Actual Behavior

Anaconda3 not opening on my web browser after installation and re-installation also

### Expected Behavior

Anaconda navigator should open after installing

##### `conda info`

```

```

##### `conda list --show-channel-urls`

```

```

**Comment by goanpeca** [comment]
@AIchild please provide the requested information so we can help you debug the issue

**Comment by AIchild** [comment]
Thanks for addressing my issue ASAP , as you mentioned above to run certain commands in Anaconda Prompt. On running both of the commands I received the same message -> 'conda' is not recognized as an internal or external command, operable program or batch file'.

P.s.- on opening anaconda prompt i also an error report generated by conda, which I failed to send due to my internet connection issue.

**Comment by goanpeca** [comment]
>on opening anaconda prompt i also an error report generated by conda

What error?

**Comment by AIchild** [comment]
Error-Report generated on Anaconda Prompt

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "C:\Users\anmol singh\Anaconda3\lib\site-packages\conda\cli\main.py", line 97, in main
        from ..activate import main as activator_main
      File "C:\Users\anmol singh\Anaconda3\lib\site-packages\conda\activate.py", line 12, in <module>
        context.__init__()  # oOn import, context does not include SEARCH_PATH. This line fixes that.
      File "C:\Users\anmol singh\Anaconda3\lib\site-packages\conda\base\context.py", line 236, in __init__
        argparse_args=argparse_args)
      File "C:\Users\anmol singh\Anaconda3\lib\site-packages\conda\common\configuration.py", line 722, in __init__
        self._set_search_path(search_path)
      File "C:\Users\anmol singh\Anaconda3\lib\site-packages\conda\common\configuration.py", line 728, in _set_search_path
        self._set_raw_data(load_file_configs(search_path))
      File "C:\Users\anmol singh\Anaconda3\lib\site-packages\conda\common\configuration.py", line 369, in load_file_configs
        raw_data = odict(kv for kv in chain.from_iterable(load_paths))
      File "C:\Users\anmol singh\Anaconda3\lib\site-packages\conda\common\configuration.py", line 369, in <genexpr>
        raw_data = odict(kv for kv in chain.from_iterable(load_paths))
      File "C:\Users\anmol singh\Anaconda3\lib\site-packages\conda\common\configuration.py", line 344, in _file_yaml_loader
        yield fullpath, YamlRawParameter.make_raw_parameters_from_file(fullpath)
      File "C:\Users\anmol singh\Anaconda3\lib\site-packages\conda\common\configuration.py", line 332, in make_raw_parameters_from_file
        ruamel_yaml = yaml_load(fh)
      File "C:\Users\anmol singh\Anaconda3\lib\site-packages\conda\common\serialize.py", line 54, in yaml_load
        return yaml.load(string, Loader=yaml.RoundTripLoader, version="1.2")
      File "C:\Users\anmol singh\Anaconda3\lib\site-packages\ruamel_yaml\main.py", line 637, in load
        loader = Loader(stream, version, preserve_quotes=preserve_quotes)
      File "C:\Users\anmol singh\Anaconda3\lib\site-packages\ruamel_yaml\loader.py", line 59, in __init__
        Reader.__init__(self, stream, loader=self)
      File "C:\Users\anmol singh\Anaconda3\lib\site-packages\ruamel_yaml\reader.py", line 80, in __init__
        self.stream = stream  # type: Any  # as .read is called
      File "C:\Users\anmol singh\Anaconda3\lib\site-packages\ruamel_yaml\reader.py", line 125, in stream
        self.determine_encoding()
      File "C:\Users\anmol singh\Anaconda3\lib\site-packages\ruamel_yaml\reader.py", line 180, in determine_encoding
        self.update(1)
      File "C:\Users\anmol singh\Anaconda3\lib\site-packages\ruamel_yaml\reader.py", line 241, in update
        self.check_printable(data)
      File "C:\Users\anmol singh\Anaconda3\lib\site-packages\ruamel_yaml\reader.py", line 208, in check_printable
        'unicode', "special characters are not allowed")
    ruamel_yaml.reader.ReaderError: unacceptable character #x0000: special characters are not allowed
      in "C:\Users\anmol singh\.condarc", position 0

`$ C:\Users\anmol singh\Anaconda3\Scripts\conda shell.cmd.exe activate activate C:\Users\anmol singh\Anaconda3`

  environment variables:
      3DSMAX_2011X64_PATH=C:\Program Files\Autodesk\3ds Max 2011\
         3DSMAX_2011_PATH=C:\Program Files (x86)\Autodesk\3ds Max 2011\
                 CIO_TEST=<not set>
               CONDA_ROOT=C:\Users\anmol singh\Anaconda3
                 HOMEPATH=\Users\anmol singh
                     PATH=C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\oraclexe\app
                          \oracle\product\10.2.0\server\bin;C:\ProgramData\Oracle\Java\javapath;
                          C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\Sys
                          tem32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Common
                          Files\Autodesk Shared\;C:\Program Files\Common Files\Autodesk
                          Shared\;C:\Python27;C:\Program Files
                          (x86)\KiCad\bin;C:\spice\bin;C:\Program
                          Files\Java\jdk1.8.0_131\bin;C:\Program Files\Java\jre1.8.0_131;C:\TDM-
                          GCC-64\bin;C:\WINDOWS\System32\OpenSSH\;C:\Users\anmol
                          singh\Anaconda3;C:\Users\anmol
                          singh\Anaconda3\Library\mingw-w64\bin;C:\Users\anmol
                          singh\Anaconda3\Library\usr\bin;C:\Users\anmol
                          singh\Anaconda3\Library\bin;C:\Users\anmol
                          singh\Anaconda3\Scripts;C:\Users\anmol
                          singh\AppData\Local\Programs\Python\Python36-32;C:\Users\anmol
                          singh\AppData\Local\Programs\Python\Python36-32\Scripts
             PSMODULEPATH=C:\Program Files\WindowsPowerShell\Modules;C:\WINDOWS\system32\Windows
                          PowerShell\v1.0\Modules
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>
    VBOX_MSI_INSTALL_PATH=C:\Program Files\Oracle\VirtualBox\

     active environment : None
       user config file : C:\Users\anmol singh\.condarc
 populated config files :
          conda version : 4.5.4
    conda-build version : 3.10.5
         python version : 3.6.5.final.0
       base environment : C:\Users\anmol singh\Anaconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/win-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/win-64
                          https://repo.anaconda.com/pkgs/pro/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\Users\anmol singh\Anaconda3\pkgs
                          C:\Users\anmol singh\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\anmol singh\Anaconda3\envs
                          C:\Users\anmol singh\AppData\Local\conda\conda\envs
                          C:\Users\anmol singh\.conda\envs
               platform : win-64
             user-agent : conda/4.5.4 requests/2.18.4 CPython/3.6.5 Windows/10 Windows/10.0.17134
          administrator : False
             netrc file : None
           offline mode : False


An unexpected error has occurred. Conda has prepared the above report.
If submitted, this report will be used by core maintainers to improve
future releases of conda.
Would you like conda to send this report to the core maintainers?
[y/N]: y
Upload successful.

Thank you for helping to improve conda.
Opt-in to always sending reports (and not see this message again)
by running

    $ conda config --set report_errors true

**Comment by goanpeca** [comment]
Please delete this file ` C:\Users\anmol singh\.condarc` and try again

**Comment by goanpeca** [comment]
also having a username with spaces will generate problems on some libraries

**Comment by AIchild** [comment]
A very big thank you @goanpeca you're a lifesaver. Deleting .condarc worked for me. And apology if i caused much pain in finding errors from the error report.

**Comment by AIchild** [comment]
just one question bothering me. Is deleting .condarc will cause any trouble in future?

**Comment by goanpeca** [comment]
@AIchild it somehow got corrupted, so we just "reset" it, so no worries ;0)

**Comment by Deepbaran** [comment]
@goanpeca Thanks a lot. I was also having the same problem. You just saved me. Thank you.

**Comment by jardinetsouffleton** [comment]
Worked for me too! thanks @goanpeca for your wizardry skills!

**Comment by mohitkr17** [comment]
Worked for me too! thanks @goanpeca.

**Comment by YusufKolawole** [comment]
Thanks to @goanpeca, much love  bro

**Comment by DongkyuSim** [comment]
@goanpeca I have the same problem. But, I cannot find the .condarc. Where can I find the .condarc file?

**Comment by christiantutiven** [comment]
Amazing!! @goanpeca Thanks!!

**Comment by js4968128** [comment]
Thank you @goanpeca

**Comment by sashastewart-28** [comment]
> Please delete this file ` C:\Users\anmol singh\.condarc` and try again

Thank you so much.Error solved in a critical moment thanks to you

**Comment by dop1943** [comment]
You saved my life, thank you =)))

**Comment by LITTLESTAR2019** [comment]
Thank you so much. error solved

**Comment by Farber98** [comment]
Thanks a lot. It worked for me too.

**Comment by SushmaSubburayan** [comment]
Thanka a lot goanpeca!!! Deleting .condarc resolved the issue.

**Comment by vickykhan89** [comment]
Hello Sir,  I have the same issue, I already deleted the .condarc, but still i get the error. Please need any other solution.

Traceback (most recent call last):
  File "F:/pythonProgramming/dragonnet-master/src/experiment/ihdp_main.py", line 310, in <module>
    main()
  File "F:/pythonProgramming/dragonnet-master/src/experiment/ihdp_main.py", line 306, in main
    turn_knob(args.data_base_dir, args.knob, args.output_base_dir)
  File "F:/pythonProgramming/dragonnet-master/src/experiment/ihdp_main.py", line 285, in turn_knob
    output_dir = os.path.join(output_base_dir, knob)
  File "F:\anaconda3\lib\ntpath.py", line 76, in join
    path = os.fspath(path)
TypeError: expected str, bytes or os.PathLike object, not NoneType
