### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by albertsunild** [ContinuumIO/anaconda-issues#9769]
## Main error
Application <b>notebook</b> launch may have produced errors.
## Traceback
```
C:\Users\IBM_ADMIN\Anaconda3\lib\site-packages\notebook\notebookapp.py:45: VisibleDeprecationWarning: zmq.eventloop.minitornado is deprecated in pyzmq 14.0 and will be removed.
    Install tornado itself to use zmq with the tornado IOLoop.
    
  from zmq.eventloop import ioloop
Traceback (most recent call last):
  File "C:\Users\IBM_ADMIN\Anaconda3\Scripts\jupyter-notebook-script.py", line 6, in <module>
    from notebook.notebookapp import main
  File "C:\Users\IBM_ADMIN\Anaconda3\lib\site-packages\notebook\notebookapp.py", line 46, in <module>
    ioloop.install()
  File "C:\Users\IBM_ADMIN\Anaconda3\lib\site-packages\zmq\eventloop\_deprecated.py", line 202, in install
    from tornado import ioloop
  File "C:\Users\IBM_ADMIN\Anaconda3\lib\site-packages\tornado\ioloop.py", line 56, in <module>
    from tornado.util import (
ImportError: cannot import name 'TimeoutError'

```
## System information
```
python: 3.6.6
language: en_US
os: Windows;7;6.1.7601;AMD64;Intel64 Family 6 Model 61 Stepping 4, GenuineIntel
version: 1.6.2
platform: win-64
qt: 5.6.2
pyqt: 5.6.0
conda: 4.5.8
```

**Comment by goanpeca** [comment]
Please remember to update to the latest version of Navigator to include
the latest fixes.

Open a terminal (on Linux or Mac) or the Anaconda Command Prompt (on windows)
and type:

```
conda update conda
conda update --all
```
