### ISSUE TITLE
Anaconda Navigator starting issues

### ISSUE THREAD

**Issue by LordBambinz** [ContinuumIO/anaconda-issues#9772]
Dear All,
I have a computer with windows 10, and after the last update anaconda navigator doesn't work. When i start the  program I recive the following message:

`Main Error

expected str, bytes or os.PathLike object, not NoneType

Traceback

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\anaconda_navigator\exceptions.py", line 75, in exception_handler
    return_value = func(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 150, in start_app
    window = run_app(splash)
  File "C:\ProgramData\Anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 65, in run_app
    window = MainWindow(splash=splash, tab_project=False)
  File "C:\ProgramData\Anaconda3\lib\site-packages\anaconda_navigator\widgets\main_window.py", line 163, in __init__
    self.api = AnacondaAPI()
  File "C:\ProgramData\Anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 2185, in AnacondaAPI
    ANACONDA_API = _AnacondaAPI()
  File "C:\ProgramData\Anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 89, in __init__
    self._conda_api = CondaAPI()
  File "C:\ProgramData\Anaconda3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 1714, in CondaAPI
    CONDA_API = _CondaAPI()
  File "C:\ProgramData\Anaconda3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 353, in __init__
    self.sys_rc_path = join(self.ROOT_PREFIX, '.condarc')
  File "C:\ProgramData\Anaconda3\lib\ntpath.py", line 76, in join
    path = os.fspath(path)
TypeError: expected str, bytes or os.PathLike object, not NoneType
`
I have tried the following commands from the anaconda promt:
 - conda install anaconda-navigator
 - Anaconda-navigator --reset
 - conda update navigator-updater
 - conda update anaconda-navigator

But doesn't work. I have also removed anaconda and all relative directory and reinstalled but same things. 

Thank you very much in advance for your time and help!

**Comment by LordBambinz** [comment]
The operating system is Windows 10 pro: Microsoft Windows [Versione 10.0.16299.522]
**The command: conda info:**
`# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\exceptions.py", line 819, in __call__
        return func(*args, **kwargs)
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\cli\main.py", line 74, in _main
        context.__init__(argparse_args=args)
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\base\context.py", line 236, in __init__
        argparse_args=argparse_args)
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\common\configuration.py", line 722, in __init__
        self._set_search_path(search_path)
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\common\configuration.py", line 728, in _set_search_path
        self._set_raw_data(load_file_configs(search_path))
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\common\configuration.py", line 369, in load_file_configs
        raw_data = odict(kv for kv in chain.from_iterable(load_paths))
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\common\configuration.py", line 369, in <genexpr>
        raw_data = odict(kv for kv in chain.from_iterable(load_paths))
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\common\configuration.py", line 344, in _file_yaml_loader
        yield fullpath, YamlRawParameter.make_raw_parameters_from_file(fullpath)
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\common\configuration.py", line 332, in make_raw_parameters_from_file
        ruamel_yaml = yaml_load(fh)
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\common\serialize.py", line 54, in yaml_load
        return yaml.load(string, Loader=yaml.RoundTripLoader, version="1.2")
      File "C:\ProgramData\Anaconda3\lib\site-packages\ruamel_yaml\main.py", line 637, in load
        loader = Loader(stream, version, preserve_quotes=preserve_quotes)
      File "C:\ProgramData\Anaconda3\lib\site-packages\ruamel_yaml\loader.py", line 59, in __init__
        Reader.__init__(self, stream, loader=self)
      File "C:\ProgramData\Anaconda3\lib\site-packages\ruamel_yaml\reader.py", line 80, in __init__
        self.stream = stream  # type: Any  # as .read is called
      File "C:\ProgramData\Anaconda3\lib\site-packages\ruamel_yaml\reader.py", line 125, in stream
        self.determine_encoding()
      File "C:\ProgramData\Anaconda3\lib\site-packages\ruamel_yaml\reader.py", line 180, in determine_encoding
        self.update(1)
      File "C:\ProgramData\Anaconda3\lib\site-packages\ruamel_yaml\reader.py", line 241, in update
        self.check_printable(data)
      File "C:\ProgramData\Anaconda3\lib\site-packages\ruamel_yaml\reader.py", line 208, in check_printable
        'unicode', "special characters are not allowed")
    ruamel_yaml.reader.ReaderError: unacceptable character #x0000: special characters are not allowed
      in "C:\Users\aleva\.condarc", position 0

`$ C:\ProgramData\Anaconda3\Scripts\conda info`


An unexpected error has occurred. Conda has prepared the above report.
If submitted, this report will be used by core maintainers to improve
future releases of conda.
Would you like conda to send this report to the core maintainers?`

**Instead, the command: conda list --show-channel-urls**
` environment variables:
                 CIO_TEST=<not set>
               CONDA_ROOT=C:\ProgramData\Anaconda3
                 HOMEPATH=\Users\aleva
          MOZ_PLUGIN_PATH=C:\Program Files (x86)\Foxit Software\Foxit Reader\plugins\
                     PATH=C:\ProgramData\Anaconda3;C:\ProgramData\Anaconda3\Library\mingw-w64\bi
                          n;C:\ProgramData\Anaconda3\Library\usr\bin;C:\ProgramData\Anaconda3\Li
                          brary\bin;C:\ProgramData\Anaconda3\Scripts;C:\Program Files
                          (x86)\Intel\iCLS Client\;C:\Program Files (x86)\Common Files\Oracle\Ja
                          va\javapath;C:\ProgramData\Oracle\Java\javapath;C:\Program
                          Files\Microsoft MPI\Bin\;C:\Program Files\Intel\iCLS Client\;C:\WINDOW
                          S\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\Win
                          dowsPowerShell\v1.0\;C:\Program Files\MiKTeX
                          2.9\miktex\bin\x64\;C:\Program Files
                          (x86)\Sennheiser\SoftphoneSDK\;C:\Program Files\dotnet\;C:\Program
                          Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program
                          Files\MATLAB\R2017a\runtime\win64;C:\Program
                          Files\MATLAB\R2017a\bin;C:\Program Files\PuTTY\;C:\Program
                          Files\Intel\WiFi\bin\;C:\Program Files\Common
                          Files\Intel\WirelessCommon\;C:\Program Files (x86)\Intel\Intel(R)
                          Management Engine Components\DAL;C:\Program Files\Intel\Intel(R)
                          Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R)
                          Management Engine Components\IPT;C:\Program Files\Intel\Intel(R)
                          Management Engine Components\IPT;C:\Users\aleva\AppData\Local\Microsof
                          t\WindowsApps;C:\Program Files\Microsoft VS Code\bin
             PSMODULEPATH=C:\Program Files\WindowsPowerShell\Modules;C:\WINDOWS\system32\Windows
                          PowerShell\v1.0\Modules
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>
    VBOX_MSI_INSTALL_PATH=C:\Program Files\Oracle\VirtualBox\

     active environment : None
       user config file : C:\Users\aleva\.condarc
 populated config files :
          conda version : 4.5.4
    conda-build version : 3.10.5
         python version : 3.6.5.final.0
       base environment : C:\ProgramData\Anaconda3  (read only)
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/win-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/win-64
                          https://repo.anaconda.com/pkgs/pro/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\ProgramData\Anaconda3\pkgs
                          C:\Users\aleva\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\aleva\AppData\Local\conda\conda\envs
                          C:\ProgramData\Anaconda3\envs
                          C:\Users\aleva\.conda\envs
               platform : win-64
             user-agent : conda/4.5.4 requests/2.18.4 CPython/3.6.5 Windows/10 Windows/10.0.16299
          administrator : False
             netrc file : None
           offline mode : False


An unexpected error has occurred. Conda has prepared the above report.
If submitted, this report will be used by core maintainers to improve
future releases of conda.
Would you like conda to send this report to the core maintainers?`

**Comment by goanpeca** [comment]
please delete this file "C:\Users\aleva\.condarc" and try again

**Comment by LordBambinz** [comment]
Thank you very much! the problem is resolved, now works correctly!
Thank you again for your time and help!
