### ISSUE TITLE
Can't open the Anaconda3 navigator and prompt, conda update command throwing below error.

### ISSUE THREAD

**Issue by siddu100** [ContinuumIO/anaconda-issues#9773]
C:\Users\sudyerra>conda update

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "C:\Users\sudyerra\Anaconda3\lib\site-packages\conda\exceptions.py", line 819, in __call__
        return func(*args, **kwargs)
      File "C:\Users\sudyerra\Anaconda3\lib\site-packages\conda\cli\main.py", line 74, in _main
        context.__init__(argparse_args=args)
      File "C:\Users\sudyerra\Anaconda3\lib\site-packages\conda\base\context.py", line 236, in __init__
        argparse_args=argparse_args)
      File "C:\Users\sudyerra\Anaconda3\lib\site-packages\conda\common\configuration.py", line 722, in __init__
        self._set_search_path(search_path)
      File "C:\Users\sudyerra\Anaconda3\lib\site-packages\conda\common\configuration.py", line 728, in _set_search_path
        self._set_raw_data(load_file_configs(search_path))
      File "C:\Users\sudyerra\Anaconda3\lib\site-packages\conda\common\configuration.py", line 369, in load_file_configs
        raw_data = odict(kv for kv in chain.from_iterable(load_paths))
      File "C:\Users\sudyerra\Anaconda3\lib\site-packages\conda\common\configuration.py", line 369, in <genexpr>
        raw_data = odict(kv for kv in chain.from_iterable(load_paths))
      File "C:\Users\sudyerra\Anaconda3\lib\site-packages\conda\common\configuration.py", line 344, in _file_yaml_loader
        yield fullpath, YamlRawParameter.make_raw_parameters_from_file(fullpath)
      File "C:\Users\sudyerra\Anaconda3\lib\site-packages\conda\common\configuration.py", line 332, in make_raw_parameters_from_file
        ruamel_yaml = yaml_load(fh)
      File "C:\Users\sudyerra\Anaconda3\lib\site-packages\conda\common\serialize.py", line 54, in yaml_load
        return yaml.load(string, Loader=yaml.RoundTripLoader, version="1.2")
      File "C:\Users\sudyerra\Anaconda3\lib\site-packages\ruamel_yaml\main.py", line 637, in load
        loader = Loader(stream, version, preserve_quotes=preserve_quotes)
      File "C:\Users\sudyerra\Anaconda3\lib\site-packages\ruamel_yaml\loader.py", line 59, in __init__
        Reader.__init__(self, stream, loader=self)
      File "C:\Users\sudyerra\Anaconda3\lib\site-packages\ruamel_yaml\reader.py", line 80, in __init__
        self.stream = stream  # type: Any  # as .read is called
      File "C:\Users\sudyerra\Anaconda3\lib\site-packages\ruamel_yaml\reader.py", line 125, in stream
        self.determine_encoding()
      File "C:\Users\sudyerra\Anaconda3\lib\site-packages\ruamel_yaml\reader.py", line 180, in determine_encoding
        self.update(1)
      File "C:\Users\sudyerra\Anaconda3\lib\site-packages\ruamel_yaml\reader.py", line 241, in update
        self.check_printable(data)
      File "C:\Users\sudyerra\Anaconda3\lib\site-packages\ruamel_yaml\reader.py", line 208, in check_printable
        'unicode', "special characters are not allowed")
    ruamel_yaml.reader.ReaderError: unacceptable character #x0000: special characters are not allowed
      in "C:\Users\sudyerra\.condarc", position 0

`$ C:\Users\sudyerra\Anaconda3\Scripts\conda update`

  environment variables:
                 CIO_TEST=<not set>
               CONDA_ROOT=C:\Users\sudyerra\Anaconda3
                 HOMEPATH=\Users\sudyerra
                     PATH=C:\Users\sudyerra\Anaconda3\Library\bin;C:\Program Files (x86)\Common
                          Files\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\S
                          ystem32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program
                          Files (x86)\Sennheiser\SoftphoneSDK\;C:\Program Files\Git\cmd;C:\Users
                          \sudyerra\AppData\Local\Programs\Python\Python36-32\Scripts\;C:\Users\
                          sudyerra\AppData\Local\Programs\Python\Python36-32\;C:\Users\sudyerra\
                          AppData\Local\Microsoft\WindowsApps;C:\Users\sudyerra\AppData\Local\at
                          om\bin;C:\Users\sudyerra\AppData\Local\Microsoft\WindowsApps;C:\Users\
                          sudyerra\Anaconda3;C:\Users\sudyerra\Anaconda3\Scripts;
             PSMODULEPATH=C:\Program Files\WindowsPowerShell\Modules;C:\WINDOWS\system32\Windows
                          PowerShell\v1.0\Modules
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>
    VBOX_MSI_INSTALL_PATH=C:\Program Files\Oracle\VirtualBox\

     active environment : None
       user config file : C:\Users\sudyerra\.condarc
 populated config files :
          conda version : 4.5.4
    conda-build version : 3.10.5
         python version : 3.6.5.final.0
       base environment : C:\Users\sudyerra\Anaconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/win-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/win-64
                          https://repo.anaconda.com/pkgs/pro/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\Users\sudyerra\Anaconda3\pkgs
                          C:\Users\sudyerra\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\sudyerra\Anaconda3\envs
                          C:\Users\sudyerra\AppData\Local\conda\conda\envs
                          C:\Users\sudyerra\.conda\envs
               platform : win-64
             user-agent : conda/4.5.4 requests/2.18.4 CPython/3.6.5 Windows/10 Windows/10.0.16299
          administrator : False
             netrc file : None
           offline mode : False

An unexpected error has occurred. Conda has prepared the above report.
If submitted, this report will be used by core maintainers to improve
future releases of conda.
Would you like conda to send this report to the core maintainers?
[y/N]: n

No report sent. To permanently opt-out, use

    $ conda config --set report_errors false

##### `conda info`

```

```

##### `conda list --show-channel-urls`

```

```

**Comment by siddu100** [comment]
Thank you Goanpeca
