### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by Anchor007** [ContinuumIO/anaconda-issues#9778]
## Main error
Application <b>spyder</b> launch may have produced errors.
## Traceback
```
Traceback (most recent call last):
  File "/Users/Yao/anaconda3/lib/python3.6/site-packages/qtpy/QtWebEngineWidgets.py", line 22, in <module>
    from PyQt5.QtWebEngineWidgets import QWebEnginePage
ImportError: dlopen(/Users/Yao/anaconda3/lib/python3.6/site-packages/PyQt5/QtWebEngineWidgets.so, 2): Library not loaded: @rpath/libQt5WebEngineCore.5.dylib
  Referenced from: /Users/Yao/anaconda3/lib/python3.6/site-packages/PyQt5/QtWebEngineWidgets.so
  Reason: image not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/Yao/anaconda3/bin/spyder", line 6, in <module>
    sys.exit(spyder.app.start.main())
  File "/Users/Yao/anaconda3/lib/python3.6/site-packages/spyder/app/start.py", line 140, in main
    from spyder.app import mainwindow
  File "/Users/Yao/anaconda3/lib/python3.6/site-packages/spyder/app/mainwindow.py", line 92, in <module>
    from qtpy import QtWebEngineWidgets  # analysis:ignore
  File "/Users/Yao/anaconda3/lib/python3.6/site-packages/qtpy/QtWebEngineWidgets.py", line 26, in <module>
    from PyQt5.QtWebKitWidgets import QWebPage as QWebEnginePage
ModuleNotFoundError: No module named 'PyQt5.QtWebKitWidgets'

```
## System information
```
python: 3.6.1
language: en
os: Darwin;17.5.0;Darwin Kernel Version 17.5.0: Fri Apr 13 19:32:32 PDT 2018; root:xnu-4570.51.2~1/RELEASE_X86_64;x86_64;i386
version: 1.6.2
platform: osx-64
qt: 5.6.2
pyqt: 5.6.0
conda: 4.3.25
```

**Comment by goanpeca** [comment]
Please remember to update to the latest version of Navigator to include
the latest fixes.

Open a terminal (on Linux or Mac) or the Anaconda Command Prompt (on windows)
and type:

```
conda update conda
conda update --all
```
