### ISSUE TITLE
navigator error

### ISSUE THREAD

**Issue by LeeQiao** [ContinuumIO/anaconda-issues#9802]
### Actual Behavior

navigator error, could not access anaconda

### Steps to Reproduce
after trying to install pywren and do some configuration with aws

##### Anaconda or Miniconda version:
anaconda 2
##### Operating System:
windows7
##### `conda info`

```

```

##### `conda list --show-channel-urls`

```
Traceback (most recent call last):
  File "C:\Users\Qiao\Anaconda2\lib\site-packages\anaconda_navigator\exceptions.py", line 75, in exception_handler
    return_value = func(*args, **kwargs)
  File "C:\Users\Qiao\Anaconda2\lib\site-packages\anaconda_navigator\app\start.py", line 150, in start_app
    window = run_app(splash)
  File "C:\Users\Qiao\Anaconda2\lib\site-packages\anaconda_navigator\app\start.py", line 65, in run_app
    window = MainWindow(splash=splash, tab_project=False)
  File "C:\Users\Qiao\Anaconda2\lib\site-packages\anaconda_navigator\widgets\main_window.py", line 163, in __init__
    self.api = AnacondaAPI()
  File "C:\Users\Qiao\Anaconda2\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 2185, in AnacondaAPI
    ANACONDA_API = _AnacondaAPI()
  File "C:\Users\Qiao\Anaconda2\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 89, in __init__
    self._conda_api = CondaAPI()
  File "C:\Users\Qiao\Anaconda2\lib\site-packages\anaconda_navigator\api\conda_api.py", line 1714, in CondaAPI
    CONDA_API = _CondaAPI()
  File "C:\Users\Qiao\Anaconda2\lib\site-packages\anaconda_navigator\api\conda_api.py", line 350, in __init__
    self.set_conda_prefix(info=get_conda_info())
  File "C:\Users\Qiao\Anaconda2\lib\site-packages\anaconda_navigator\api\conda_api.py", line 505, in set_conda_prefix
    self.ROOT_PREFIX = info['root_prefix']
KeyError: 'root_prefix'
```

**Comment by goanpeca** [comment]
@LeeQiao please open the `Anaconda Prompt` and provide the requested information

```
conda info
```

```
conda list --show-channel-urls
```

**Comment by LeeQiao** [comment]
Sorry,  I have reinstalled the Anaconda. the problem disappeared.

Gonzalo Peña-Castellanos <notifications@github.com> 于2018年7月24日周二 上午1:17写道：
