### ISSUE TITLE
Navigator stucks at Loading applications

### ISSUE THREAD

**Issue by Pimpwhippa** [ContinuumIO/anaconda-issues#9822]
### Actual Behavior

Anaconda Navigator stucks at loading applications... (green circle remains there)

(base) C:\Users\Pimwipa>anaconda-navigator
2018-07-26 13:40:37,611 - ERROR client_api._load_repodata:151
Expecting value: line 1 column 1 (char 0)
2018-07-26 13:40:37,611 - ERROR client_api._load_repodata:151
Expecting value: line 1 column 1 (char 0)
2018-07-26 13:40:37,611 - ERROR client_api._load_repodata:151
Expecting value: line 1 column 1 (char 0)
2018-07-26 13:40:37,611 - ERROR client_api._load_repodata:151
Expecting value: line 1 column 1 (char 0)
2018-07-26 13:40:37,611 - ERROR client_api._load_repodata:151
Expecting value: line 1 column 1 (char 0)
2018-07-26 13:40:37,611 - ERROR client_api._load_repodata:151
Expecting value: line 1 column 1 (char 0)
2018-07-26 13:40:37,611 - ERROR client_api._load_repodata:151
Expecting value: line 1 column 1 (char 0)
2018-07-26 13:40:37,611 - ERROR client_api._load_repodata:151
Expecting value: line 1 column 1 (char 0)
2018-07-26 13:40:37,626 - ERROR client_api._load_repodata:151
Expecting value: line 1 column 1 (char 0)
2018-07-26 13:40:37,626 - ERROR client_api._load_repodata:151
Expecting value: line 1 column 1 (char 0)
2018-07-26 13:40:37,626 - ERROR client_api._load_repodata:151
Expecting value: line 1 column 1 (char 0)
2018-07-26 13:40:37,626 - ERROR client_api._load_repodata:151
Expecting value: line 1 column 1 (char 0)
2018-07-26 13:40:37,642 - ERROR client_api._load_repodata:151
Expecting value: line 1 column 1 (char 0)
2018-07-26 13:40:37,642 - ERROR client_api._load_repodata:151
Expecting value: line 1 column 1 (char 0)
2018-07-26 13:40:37,642 - ERROR client_api._load_repodata:151
Expecting value: line 1 column 1 (char 0)
2018-07-26 13:40:37,642 - ERROR client_api._load_repodata:151
Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
File "C:\Users\Pimwipa\Anaconda3\lib\site-packages\anaconda_navigator\widgets\main_window.py", line 442, in process_application_info
self.post_setup(processed_apps)
File "C:\Users\Pimwipa\Anaconda3\lib\site-packages\anaconda_navigator\widgets\main_window.py", line 457, in post_setup
self.home_tab.setup_tab(apps, prefix=self.current_prefix)
File "C:\Users\Pimwipa\Anaconda3\lib\site-packages\anaconda_navigator\widgets\tabs\home.py", line 253, in setup_tab
self.set_applications(prefix=prefix)
File "C:\Users\Pimwipa\Anaconda3\lib\site-packages\anaconda_navigator\widgets\tabs\home.py", line 267, in set_applications
missing_apps = [app for app in linked_apps if app not in self.apps]
File "C:\Users\Pimwipa\Anaconda3\lib\site-packages\anaconda_navigator\widgets\tabs\home.py", line 267, in 
missing_apps = [app for app in linked_apps if app not in self.apps]
TypeError: argument of type 'NoneType' is not iterable

##### `conda info`

```

(base) C:\Users\Pimwipa>conda info

     active environment : base
    active env location : C:\Users\Pimwipa\Anaconda3
            shell level : 1
       user config file : C:\Users\Pimwipa\.condarc
 populated config files : C:\Users\Pimwipa\.condarc
          conda version : 4.5.8
    conda-build version : not installed
         python version : 3.6.6.final.0
       base environment : C:\Users\Pimwipa\Anaconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/win-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/win-64
                          https://repo.anaconda.com/pkgs/pro/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\Users\Pimwipa\Anaconda3\pkgs
                          C:\Users\Pimwipa\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\Pimwipa\Anaconda3\envs
                          C:\Users\Pimwipa\AppData\Local\conda\conda\envs
                          C:\Users\Pimwipa\.conda\envs
               platform : win-64
             user-agent : conda/4.5.8 requests/2.12.4 CPython/3.6.6 Windows/10 Windows/10.0.17134
          administrator : False
             netrc file : None
           offline mode : False

```

##### `conda list --show-channel-urls`

```
(base) C:\Users\Pimwipa>conda list --show-channel-urls
# packages in environment at C:\Users\Pimwipa\Anaconda3:
#
# Name                    Version                   Build  Channel
_license                  1.1                      py36_1    defaults
alabaster                 0.7.9                    py36_0    defaults
anaconda                  custom           py36h363777c_0    defaults
anaconda-client           1.6.0                    py36_0    defaults
anaconda-navigator        1.5.0                    py36_0    defaults
anaconda-project          0.4.1                    py36_0    defaults
astroid                   1.4.9                    py36_0    defaults
astropy                   1.3                 np111py36_0    defaults
babel                     2.3.4                    py36_0    defaults
backports                 1.0                      py36_0    defaults
beautifulsoup4            4.5.3                    py36_0    defaults
bitarray                  0.8.1                    py36_1    defaults
blaze                     0.10.1                   py36_0    defaults
blosc                     1.14.3               he51fdeb_0    defaults
bokeh                     0.12.4                   py36_0    defaults
boto                      2.45.0                   py36_0    defaults
bottleneck                1.2.0               np111py36_0    defaults
bzip2                     1.0.6                hfa6e2cd_5    defaults
ca-certificates           2018.03.07                    0    defaults
cffi                      1.9.1                    py36_0    defaults
chardet                   2.3.0                    py36_0    defaults
chest                     0.2.3                    py36_0    defaults
click                     6.7                      py36_0    defaults
cloudpickle               0.2.2                    py36_0    defaults
clyent                    1.2.2                    py36_0    defaults
colorama                  0.3.7                    py36_0    defaults
comtypes                  1.1.2                    py36_0    defaults
conda                     4.5.8                    py36_0    defaults
conda-env                 2.6.0                         0    defaults
configobj                 5.0.6                    py36_0    defaults
console_shortcut          0.1.1                    py36_1    defaults
contextlib2               0.5.4                    py36_0    defaults
cryptography              1.7.1                    py36_0    defaults
curl                      7.60.0               h7602738_0    defaults
cycler                    0.10.0                   py36_0    defaults
cython                    0.25.2                   py36_0    defaults
cytoolz                   0.8.2                    py36_0    defaults
dask                      0.13.0                   py36_0    defaults
datashape                 0.5.4                    py36_0    defaults
decorator                 4.0.11                   py36_0    defaults
dill                      0.2.5                    py36_0    defaults
docutils                  0.13.1                   py36_0    defaults
entrypoints               0.2.2                    py36_0    defaults
et_xmlfile                1.0.1                    py36_0    defaults
fastcache                 1.0.2                    py36_1    defaults
flask                     0.12                     py36_0    defaults
flask-cors                3.0.2                    py36_0    defaults
freetype                  2.8                  h51f8f2c_1    defaults
get_terminal_size         1.0.0                    py36_0    defaults
gevent                    1.2.1                    py36_0    defaults
greenlet                  0.4.11                   py36_0    defaults
h5py                      2.8.0            py36h3bdd7fb_0    defaults
hdf5                      1.10.2               hac2f561_1    defaults
heapdict                  1.0.0                    py36_1    defaults
icc_rt                    2017.0.4             h97af966_0    defaults
icu                       58.2                 ha66f8fd_1    defaults
idna                      2.2                      py36_0    defaults
imagesize                 0.7.1                    py36_0    defaults
ipykernel                 4.5.2                    py36_0    defaults
ipython                   5.1.0                    py36_0    defaults
ipython_genutils          0.1.0                    py36_0    defaults
ipywidgets                5.2.2                    py36_1    defaults
isort                     4.2.5                    py36_0    defaults
itsdangerous              0.24                     py36_0    defaults
jdcal                     1.3                      py36_0    defaults
jedi                      0.9.0                    py36_1    defaults
jinja2                    2.9.4                    py36_0    defaults
jpeg                      9b                   hb83a4c4_2    defaults
jsonschema                2.5.1                    py36_0    defaults
jupyter                   1.0.0                    py36_3    defaults
jupyter_client            4.4.0                    py36_0    defaults
jupyter_console           5.0.0                    py36_0    defaults
jupyter_core              4.2.1                    py36_0    defaults
kiwisolver                1.0.1            py36h12c3424_0    defaults
lazy-object-proxy         1.2.2                    py36_0    defaults
libcurl                   7.60.0               hc4dcbb0_0    defaults
libpng                    1.6.34               h79bbb47_0    defaults
libssh2                   1.8.0                hd619d38_4    defaults
libtiff                   4.0.9                hb8ad9f9_1    defaults
llvmlite                  0.15.0                   py36_0    defaults
locket                    0.2.0                    py36_1    defaults
lxml                      3.7.2                    py36_0    defaults
lzo                       2.10                 h6df0209_2    defaults
markupsafe                0.23                     py36_2    defaults
matplotlib                2.2.2            py36h153e9ff_0    defaults
menuinst                  1.4.4                    py36_0    defaults
mistune                   0.7.3                    py36_0    defaults
mkl                       2017.0.1                      0    defaults
mkl-service               1.1.2                    py36_3    defaults
mpmath                    0.19                     py36_1    defaults
multipledispatch          0.4.9                    py36_0    defaults
nbconvert                 4.2.0                    py36_0    defaults
nbformat                  4.2.0                    py36_0    defaults
networkx                  1.11                     py36_0    defaults
nltk                      3.2.2                    py36_0    defaults
nose                      1.3.7                    py36_1    defaults
notebook                  4.3.1                    py36_2    defaults
numba                     0.30.1              np111py36_0    defaults
numexpr                   2.6.1               np111py36_2    defaults
numpy                     1.11.3                   py36_0    defaults
numpydoc                  0.6.0                    py36_0    defaults
odo                       0.5.0                    py36_1    defaults
olefile                   0.45.1                   py36_0    defaults
openpyxl                  2.4.1                    py36_0    defaults
openssl                   1.0.2o               h8ea7d77_0    defaults
pandas                    0.19.2              np111py36_1    defaults
partd                     0.3.7                    py36_0    defaults
path.py                   10.0                     py36_0    defaults
pathlib2                  2.2.0                    py36_0    defaults
patsy                     0.4.1                    py36_0    defaults
pep8                      1.7.0                    py36_0    defaults
pickleshare               0.7.4                    py36_0    defaults
pillow                    5.1.0            py36h0738816_0    defaults
pip                       9.0.1                    py36_1    defaults
ply                       3.9                      py36_0    defaults
prompt_toolkit            1.0.9                    py36_0    defaults
psutil                    5.0.1                    py36_0    defaults
py                        1.4.32                   py36_0    defaults
pyasn1                    0.1.9                    py36_0    defaults
pycosat                   0.6.3            py36h413d8a4_0    defaults
pycparser                 2.17                     py36_0    defaults
pycrypto                  2.6.1                    py36_5    defaults
pycurl                    7.43.0.2         py36h74b6da3_0    defaults
pyflakes                  1.5.0                    py36_0    defaults
pygments                  2.1.3                    py36_0    defaults
pylint                    1.6.4                    py36_1    defaults
pyopenssl                 16.2.0                   py36_0    defaults
pyparsing                 2.1.4                    py36_0    defaults
pyqt                      5.6.0                    py36_2    defaults
pytables                  3.4.4            py36he6f6034_0    defaults
pytest                    3.0.5                    py36_0    defaults
python                    3.6.6                hea74fb7_0    defaults
python-dateutil           2.6.0                    py36_0    defaults
pytz                      2016.10                  py36_0    defaults
pywin32                   220                      py36_2    defaults
pyyaml                    3.12                     py36_0    defaults
pyzmq                     16.0.2                   py36_0    defaults
qt                        5.6.2           vc14h6f8c307_12  [vc14]  defaults
qtawesome                 0.4.3                    py36_0    defaults
qtconsole                 4.2.1                    py36_2    defaults
qtpy                      1.2.1                    py36_0    defaults
requests                  2.12.4                   py36_0    defaults
rope                      0.9.4                    py36_1    defaults
ruamel_yaml               0.11.14                  py36_1    defaults
scikit-image              0.12.3              np111py36_1    defaults
scikit-learn              0.18.1              np111py36_1    defaults
scipy                     0.18.1              np111py36_1    defaults
seaborn                   0.7.1                    py36_0    defaults
setuptools                27.2.0                   py36_1    defaults
simplegeneric             0.8.1                    py36_1    defaults
singledispatch            3.4.0.3                  py36_0    defaults
sip                       4.18                     py36_0    defaults
six                       1.10.0                   py36_0    defaults
snappy                    1.1.7                h777316e_3    defaults
snowballstemmer           1.2.1                    py36_0    defaults
sockjs-tornado            1.0.3                    py36_0    defaults
sphinx                    1.5.1                    py36_0    defaults
spyder                    3.1.2                    py36_0    defaults
sqlalchemy                1.1.5                    py36_0    defaults
sqlite                    3.24.0               h7602738_0    defaults
statsmodels               0.6.1               np111py36_1    defaults
sympy                     1.0                      py36_0    defaults
tk                        8.6.7                hcb92d03_3    defaults
toolz                     0.8.2                    py36_0    defaults
tornado                   4.4.2                    py36_0    defaults
traitlets                 4.3.1                    py36_0    defaults
unicodecsv                0.14.1                   py36_0    defaults
vc                        14.1                 h0510ff6_3    defaults
vs2015_runtime            15.5.2                        3    defaults
wcwidth                   0.1.7                    py36_0    defaults
werkzeug                  0.11.15                  py36_0    defaults
wheel                     0.29.0                   py36_0    defaults
widgetsnbextension        1.2.6                    py36_0    defaults
win_unicode_console       0.5                      py36_0    defaults
wrapt                     1.10.8                   py36_0    defaults
xlrd                      1.0.0                    py36_0    defaults
xlsxwriter                0.9.6                    py36_0    defaults
xlwings                   0.10.2                   py36_0    defaults
xlwt                      1.2.0                    py36_0    defaults
zlib                      1.2.11               h8395fce_2    defaults

(base) C:\Users\Pimwipa>

```

**Comment by goanpeca** [comment]
Please remember to update to the latest version of Navigator to include
the latest fixes.

Open a terminal (on Linux or Mac) or the Anaconda Command Prompt (on windows)
and type:

```
conda update conda
conda update --all
```

**Comment by Pimpwhippa** [comment]
I just did all the updates..
