### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by behnamoh** [ContinuumIO/anaconda-issues#9824]
## Main error
Application <b>orange3</b> launch may have produced errors.
## Traceback
```
/Users/behnam/anaconda/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
/Users/behnam/anaconda/lib/python3.6/site-packages/Orange/widgets/io.py:18: UserWarning: WebView from QWebKit or QWebEngine is not available. Orange widgets that depend on it will fail to work.
  warn('WebView from QWebKit or QWebEngine is not available. Orange '
Traceback (most recent call last):
  File "/Users/behnam/anaconda/bin/orange-canvas", line 11, in <module>
    sys.exit(main())
  File "/Users/behnam/anaconda/lib/python3.6/site-packages/Orange/canvas/__main__.py", line 402, in main
    canvas_window = CanvasMainWindow()
  File "/Users/behnam/anaconda/lib/python3.6/site-packages/Orange/canvas/application/canvasmain.py", line 189, in __init__
    self.setup_ui()
  File "/Users/behnam/anaconda/lib/python3.6/site-packages/Orange/canvas/application/canvasmain.py", line 361, in setup_ui
    self.help_view = QWebView()
TypeError: 'NoneType' object is not callable

```
## System information
```
python: 3.6.1
language: en
os: Darwin;15.6.0;Darwin Kernel Version 15.6.0: Thu Jun 21 20:07:40 PDT 2018; root:xnu-3248.73.11~1/RELEASE_X86_64;x86_64;i386
version: 1.6.2
platform: osx-64
qt: 5.6.2
pyqt: 5.6.0
conda: 4.5.8
```

**Comment by goanpeca** [comment]
Please remember to update to the latest version of Navigator to include
the latest fixes.

Open a terminal (on Linux or Mac) or the Anaconda Command Prompt (on windows)
and type:

```
conda update conda
conda update --all
```
