### ISSUE TITLE
Cannot add Op to Tensorflow built using C++11 ABI

### ISSUE THREAD

**Issue by iandreariley** [ContinuumIO/anaconda-issues#9826]
### Actual Behavior

Adding a custom op compiled with G++ 4.8.5 fails because the anaconda package is built using the C++11 ABI. This is differs significantly from behavior expected from [tensorflow's own releases, which are built with GCC 4.x](https://www.tensorflow.org/extend/adding_an_op#compile_the_op_using_your_system_compiler_tensorflow_binary_installation). Further, this is not fixable with G++ 4.x because the `-D_GLIBCXX_USE_CXX11_ABI' flag wasn't introduced until 5.x.

Full stack trace when trying to load an op :
```sh
>>> import tensorflow as tf
>>> tf.load_op_library('zero_out.so')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/anaconda3/envs/TF17/lib/python3.5/site-packages/tensorflow/python/framework/load_library.py", line 58, in load_op_library
    lib_handle = py_tf.TF_LoadLibrary(library_filename, status)
  File "/usr/local/anaconda3/envs/TF17/lib/python3.5/site-packages/tensorflow/python/framework/errors_impl.py", line 516, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.NotFoundError: zero_out.so: undefined symbol: _ZN10tensorflow8internal21CheckOpMessageBuilder9NewStringEv
```

### Expected Behavior

The tensorflow binary provided by anaconda should be built with GCC 4.x (or with `-D_GLIBCXX_USE_CXX11_ABI=0` ) for backward compatibility and consistency with tensorflow's own release binaries. GCC 5.x users may set `-D_GLIBCXX_USE_CXX11_ABI=0` to compile ops against a tensorflow binary built with GCC 4.x. 4.x users have no equivalent way to compile ops to work with tensorflow binaries built with 5.x

### Steps to Reproduce

1. conda install tensorflow=1.7.0
1. Build example custom op from [tensorflow page](https://www.tensorflow.org/extend/adding_an_op#top_of_page)
1. Attempt to load the op with
    ```py
    import tensorflow as tf
    tf.load_op_library('zero_out.so')
    ```

##### `conda info`

```
     active environment : tf_channel_test
    active env location : /home/iriley/.conda/envs/tf_channel_test
            shell level : 1
       user config file : /home/iriley/.condarc
 populated config files : /home/iriley/.condarc
          conda version : 4.5.8
    conda-build version : 1.21.3
         python version : 3.5.2.final.0
       base environment : /usr/local/anaconda3  (read only)
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/linux-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/linux-64
                          https://repo.anaconda.com/pkgs/pro/noarch
          package cache : /usr/local/anaconda3/pkgs
                          /home/iriley/.conda/pkgs
       envs directories : /home/iriley/.conda/envs
                          /usr/local/anaconda3/envs
               platform : linux-64
             user-agent : conda/4.5.8 requests/2.14.2 CPython/3.5.2 Linux/3.12.49-11-default sles/12.1 glibc/2.19
                UID:GID : 1002:100
             netrc file : None
           offline mode : False
```

##### `conda list --show-channel-urls`

```
absl-py                   0.3.0                    py36_0    anaconda
astor                     0.6.2                    py36_1    anaconda
blas                      1.0                         mkl    anaconda
bleach                    1.5.0                    py36_0    anaconda
ca-certificates           2018.03.07                    0    anaconda
certifi                   2018.4.16                py36_0    anaconda
cudatoolkit               9.0                  h13b8566_0    anaconda
cudnn                     7.1.2                 cuda9.0_0    anaconda
cupti                     9.0.176                       0    anaconda
gast                      0.2.0                    py36_0    anaconda
grpcio                    1.12.1           py36hdbcaa40_0    anaconda
html5lib                  0.9999999                py36_0    anaconda
intel-openmp              2018.0.3                      0    anaconda
libedit                   3.1.20170329         h6b74fdf_2    defaults
libffi                    3.2.1                hd88cf55_4    defaults
libgcc-ng                 7.2.0                hdf63c60_3    defaults
libgfortran-ng            7.2.0                hdf63c60_3    anaconda
libprotobuf               3.5.2                h6f1eeef_0    anaconda
libstdcxx-ng              7.2.0                hdf63c60_3    defaults
markdown                  2.6.11                   py36_0    anaconda
mkl                       2018.0.3                      1    anaconda
mkl_fft                   1.0.2            py36h651fb7a_0    anaconda
mkl_random                1.0.1            py36h4414c95_1    anaconda
ncurses                   6.1                  hf484d3e_0    defaults
numpy                     1.14.5           py36h1b885b7_4    anaconda
numpy-base                1.14.5           py36hdbf6ddf_4    anaconda
openssl                   1.0.2o               h20670df_0    anaconda
pip                       10.0.1                   py36_0    defaults
protobuf                  3.5.2            py36hf484d3e_1    anaconda
python                    3.6.5                hc3d631a_2    defaults
readline                  7.0                  ha6073c6_4    defaults
setuptools                39.2.0                   py36_0    defaults
six                       1.11.0                   py36_1    anaconda
sqlite                    3.24.0               h84994c4_0    defaults
tensorboard               1.7.0            py36hf484d3e_1    anaconda
tensorflow-gpu            1.7.0                         0    anaconda
tensorflow-gpu-base       1.7.0            py36hcdda91b_1    anaconda
termcolor                 1.1.0                    py36_1    anaconda
tk                        8.6.7                hc745277_3    defaults
werkzeug                  0.14.1                   py36_0    anaconda
wheel                     0.31.1                   py36_0    defaults
xz                        5.2.4                h14c3975_4    defaults
zlib                      1.2.11               ha838bed_2    defaults
```

**Comment by msarahan** [comment]
As you've discovered, all of our software is built on the new C++ ABI.  You have to be on one side of that fence.  We have moved to the newer side of that fence.  We're not going back.  Sorry.

You may want to read up on how to use our compilers.  https://conda.io/docs/user-guide/tasks/build-packages/compiler-tools.html

**Comment by iandreariley** [comment]
Thanks, @msarahan, for your absurdly fast reply. I recompiled the op using the anaconda `gxx_linux-64` compiler and it worked perfectly. Great to know anaconda has added compilers as packages. Thanks again for the help.

**Comment by mingwandroid** [comment]
> I recompiled the op using the anaconda gxx_linux-64 compiler and it worked perfectly

Great to hear!

We need to be modern and secure in our tools and packages here and we cannot build out variants for things like old compilers as working on newer stuff is always higher value (and old tools rot against new software).
