### ISSUE TITLE
Navigator Error after updating Spyder on Mac

### ISSUE THREAD

**Issue by harryHoward** [ContinuumIO/anaconda-issues#9845]
### Actual Behavior

After updating Spyder with "condo update spyder" & clicking on Anaconda-Navigator icon, my web browser opened this page:

Navigator Error

An unexpected error occurred on Navigator start-up

Report

Please report this issue in the anaconda issue tracker

Main Error

get_server_api() got an unexpected keyword argument 'config'
Traceback

Traceback (most recent call last):
  File "/Users/harryhow/anaconda/lib/python2.7/site-packages/anaconda_navigator/exceptions.py", line 75, in exception_handler
    return_value = func(*args, **kwargs)
  File "/Users/harryhow/anaconda/lib/python2.7/site-packages/anaconda_navigator/app/start.py", line 138, in start_app
    window = run_app(splash)
  File "/Users/harryhow/anaconda/lib/python2.7/site-packages/anaconda_navigator/app/start.py", line 64, in run_app
    window = MainWindow(splash=splash, tab_project=False)
  File "/Users/harryhow/anaconda/lib/python2.7/site-packages/anaconda_navigator/widgets/main_window.py", line 163, in __init__
    self.api = AnacondaAPI()
  File "/Users/harryhow/anaconda/lib/python2.7/site-packages/anaconda_navigator/api/anaconda_api.py", line 2127, in AnacondaAPI
    ANACONDA_API = _AnacondaAPI()
  File "/Users/harryhow/anaconda/lib/python2.7/site-packages/anaconda_navigator/api/anaconda_api.py", line 90, in __init__
    self._client_api = ClientAPI()
  File "/Users/harryhow/anaconda/lib/python2.7/site-packages/anaconda_navigator/api/client_api.py", line 638, in ClientAPI
    CLIENT_API = _ClientAPI()
  File "/Users/harryhow/anaconda/lib/python2.7/site-packages/anaconda_navigator/api/client_api.py", line 93, in __init__
    self.reload_binstar_client()
  File "/Users/harryhow/anaconda/lib/python2.7/site-packages/anaconda_navigator/api/client_api.py", line 312, in reload_binstar_client
    log_level=logging.NOTSET
TypeError: get_server_api() got an unexpected keyword argument 'config'
### Expected Behavior

Anaconda-Navigator should have opened

### Steps to Reproduce

Click on Anaconda-Navigator icon.

##### Anaconda or Miniconda version:

conda 4.3.16

##### Operating System:

OSX 10.10.5

##### `conda info`

```
               platform : osx-64
          conda version : 4.3.16
       conda is private : False
      conda-env version : 4.3.16
    conda-build version : 1.21.3
         python version : 2.7.12.final.0
       requests version : 2.13.0
       root environment : /Users/harryhow/anaconda  (writable)
    default environment : /Users/harryhow/anaconda
       envs directories : /Users/harryhow/anaconda/envs
                          /Users/harryhow/.conda/envs
          package cache : /Users/harryhow/anaconda/pkgs
                          /Users/harryhow/.conda/pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/osx-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/osx-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/osx-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : None
           offline mode : False
             user-agent : conda/4.3.16 requests/2.13.0 CPython/2.7.12 Darwin/14.5.0 OSX/10.10.5
                UID:GID : 503:20

```

##### `conda list --show-channel-urls`

```
_nb_ext_conf              0.2.0                    py27_0    defaults
alabaster                 0.7.8                    py27_0    defaults
anaconda                  custom                   py27_0    defaults
anaconda-client           1.4.0                    py27_0    defaults
anaconda-navigator        1.2.1                    py27_0    defaults
appnope                   0.1.0                    py27_0    defaults
appscript                 1.0.1                    py27_0    defaults
argcomplete               1.0.0                    py27_1    defaults
args                      0.1.0                     <pip>
astropy                   1.1.2               np110py27_0    defaults
babel                     2.3.3                    py27_0    defaults
backports                 1.0                      py27_0    defaults
backports_abc             0.4                      py27_0    defaults
basemap                   1.0.8.dev0          np110py27_3    conda-forge
beautifulsoup4            4.4.1                    py27_0    defaults
bitarray                  0.8.1                    py27_0    defaults
blaze                     0.10.1                   py27_0    defaults
bokeh                     0.12.0                   py27_0    defaults
boto                      2.40.0                   py27_0    defaults
bottleneck                1.0.0               np110py27_1    defaults
cartopy                   0.13.1              np110py27_0    scitools
cdecimal                  2.3                      py27_2    defaults
cffi                      1.6.0                    py27_0    defaults
chest                     0.2.3                    py27_0    defaults
click                     6.6                      py27_0    defaults
clint                     0.5.1                     <pip>
cloudpickle               0.2.1                    py27_0    defaults
clyent                    1.2.2                    py27_0    defaults
colorama                  0.3.7                    py27_0    defaults
conda                     4.3.16                   py27_0    defaults
conda-build               1.21.3                   py27_0    defaults
conda-env                 2.6.0                         0    defaults
configobj                 5.0.6                    py27_0    defaults
configparser              3.5.0b2                  py27_1    defaults
ConnPlotter               0.7a                      <pip>
contextlib2               0.5.3                    py27_0    defaults
cryptography              1.4                      py27_0    defaults
curl                      7.49.0                        0    defaults
cycler                    0.10.0                   py27_0    defaults
cython                    0.24                     py27_0    defaults
cytoolz                   0.8.0                    py27_0    defaults
dask                      0.10.0                   py27_0    defaults
datashape                 0.5.2                    py27_0    defaults
decorator                 4.0.10                   py27_0    defaults
dill                      0.2.5                    py27_0    defaults
docopt                    0.6.2                     <pip>
docutils                  0.12                     py27_2    defaults
dynd-python               0.7.2                    py27_0    defaults
entrypoints               0.2.2                    py27_0    defaults
enum34                    1.1.6                    py27_0    defaults
et_xmlfile                1.0.1                    py27_0    defaults
facebook-sdk              2.0.0                     <pip>
fastcache                 1.0.2                    py27_1    defaults
feedparser                5.2.1                     <pip>
flask                     0.11.1                   py27_0    defaults
flask-cors                2.1.2                    py27_0    defaults
freetype                  2.5.5                         1    defaults
funcsigs                  1.0.2                    py27_0    defaults
functools32               3.2.3.2                  py27_0    defaults
futures                   3.0.5                    py27_0    defaults
Gammatone                 1.0                       <pip>
geos                      3.5.1                         1    conda-forge
get_terminal_size         1.0.0                    py27_0    defaults
gevent                    1.1.1                    py27_0    defaults
greenlet                  0.4.10                   py27_0    defaults
grin                      1.2.1                    py27_3    defaults
h5py                      2.6.0               np110py27_1    defaults
hdf5                      1.8.16                        0    defaults
heapdict                  1.0.0                    py27_1    defaults
idna                      2.1                      py27_0    defaults
imagesize                 0.7.1                    py27_0    defaults
internetarchive           1.0.10                    <pip>
ipaddress                 1.0.16                   py27_0    defaults
ipykernel                 4.3.1                    py27_0    defaults
ipython                   4.2.0                    py27_1    defaults
ipython_genutils          0.1.0                    py27_0    defaults
ipywidgets                4.1.1                    py27_0    defaults
itsdangerous              0.24                     py27_0    defaults
jbig                      2.1                           0    defaults
jdcal                     1.2                      py27_1    defaults
jedi                      0.9.0                    py27_1    defaults
jinja2                    2.8                      py27_1    defaults
jpeg                      8d                            1    defaults
jsonpatch                 0.4                       <pip>
jsonschema                2.5.1                    py27_0    defaults
jupyter                   1.0.0                    py27_3    defaults
jupyter_client            4.3.0                    py27_0    defaults
jupyter_console           4.1.1                    py27_0    defaults
jupyter_core              4.1.0                    py27_0    defaults
latexcodec                1.0.4                     <pip>
libdynd                   0.7.2                         0    defaults
libNeuroML                0.2.27                    <pip>
libpng                    1.6.22                        0    defaults
libtiff                   4.0.6                         2    defaults
libxml2                   2.9.2                         0    defaults
libxslt                   1.1.28                        2    defaults
llvmlite                  0.11.0                   py27_0    defaults
locket                    0.2.0                    py27_1    defaults
lxml                      3.6.0                    py27_0    defaults
markupsafe                0.23                     py27_2    defaults
matplotlib                1.5.1               np110py27_0    defaults
mistune                   0.7.2                    py27_1    defaults
mkl                       11.3.3                        0    defaults
mkl-service               1.1.2                    py27_2    defaults
mock                      2.0.0                    py27_0    defaults
mpmath                    0.19                     py27_1    defaults
multipledispatch          0.4.8                    py27_0    defaults
nb_anacondacloud          1.1.0                    py27_0    defaults
nb_conda                  1.1.0                    py27_0    defaults
nb_conda_kernels          1.0.3                    py27_0    defaults
nbconvert                 4.2.0                    py27_0    defaults
nbformat                  4.0.1                    py27_0    defaults
nbpresent                 3.0.2                    py27_0    defaults
nengo                     2.3.1                     <pip>
networkx                  1.11                     py27_0    defaults
nltk                      3.2.1                    py27_0    defaults
nose                      1.3.7                    py27_1    defaults
notebook                  4.2.1                    py27_0    defaults
numba                     0.26.0              np110py27_0    defaults
numexpr                   2.5.2               np110py27_1    defaults
numpy                     1.10.4                   py27_2    defaults
oauthlib                  2.0.0                     <pip>
odo                       0.5.0                    py27_1    defaults
openpyxl                  2.3.2                    py27_0    defaults
openssl                   1.0.2h                        1    defaults
oset                      0.1.3                     <pip>
owslib                    0.10.3                   py27_0    scitools
pandas                    0.18.1              np110py27_0    defaults
partd                     0.3.4                    py27_0    defaults
path.py                   8.2.1                    py27_0    defaults
pathlib2                  2.1.0                    py27_0    defaults
patsy                     0.4.1                    py27_0    defaults
Pattern                   2.6                       <pip>
pbr                       1.10.0                   py27_0    defaults
pep8                      1.7.0                    py27_0    defaults
pexpect                   4.0.1                    py27_0    defaults
pickleshare               0.7.2                    py27_0    defaults
pillow                    3.2.0                    py27_1    defaults
pip                       8.1.2                    py27_0    defaults
ply                       3.8                      py27_0    defaults
powerlaw                  1.4.1                     <pip>
proj.4                    4.9.1                         1    scitools
psutil                    4.3.0                    py27_0    defaults
ptyprocess                0.5.1                    py27_0    defaults
py                        1.4.31                   py27_0    defaults
pyasn1                    0.1.9                    py27_0    defaults
pyaudio                   0.2.7                    py27_0    defaults
pybtex                    0.20.1                    <pip>
pybtex-docutils           0.2.1                     <pip>
pycosat                   0.6.1                    py27_1    defaults
pycparser                 2.14                     py27_1    defaults
pycrypto                  2.6.1                    py27_4    defaults
pycurl                    7.43.0                   py27_0    defaults
PyDSTool                  0.90.2                    <pip>
pyepsg                    0.2.0                    py27_0    scitools
pyflakes                  1.2.3                    py27_0    defaults
pygments                  2.1.3                    py27_0    defaults
PyLEMS                    0.4.9                     <pip>
pymnet                    0.1                       <pip>
PyNEST                    2.10.0                    <pip>
pyopenssl                 16.2.0                   py27_0    defaults
pyparsing                 2.1.4                    py27_0    defaults
pyproj                    1.9.5.1                  py27_0    defaults
pyqt                      4.11.4                   py27_3    defaults
pyshp                     1.2.3                    py27_0    scitools
pytables                  3.2.2               np110py27_3    defaults
pytest                    2.9.2                    py27_0    defaults
python                    2.7.12                        1    defaults
python-dateutil           2.5.3                    py27_0    defaults
python.app                1.2                      py27_4    defaults
pytz                      2016.4                   py27_0    defaults
pyyaml                    3.11                     py27_4    defaults
pyzmq                     15.2.0                   py27_1    defaults
qt                        4.8.7                         3    defaults
qtconsole                 4.2.1                    py27_0    defaults
qtpy                      1.0.2                    py27_0    defaults
readline                  6.2                           2    defaults
redis                     3.2.0                         0    defaults
redis-py                  2.10.5                   py27_0    defaults
requests                  2.13.0                   py27_0    defaults
requests-oauthlib         0.7.0                     <pip>
rope                      0.9.4                    py27_1    defaults
ruamel_yaml               0.11.14                  py27_0    defaults
schema                    0.5.0                     <pip>
scikit-image              0.12.3              np110py27_1    defaults
scikit-learn              0.17.1              np110py27_2    defaults
scipy                     0.17.1              np110py27_1    defaults
setuptools                23.0.0                   py27_0    defaults
shapely                   1.5.16                   py27_0    defaults
simplegeneric             0.8.1                    py27_1    defaults
singledispatch            3.4.0.3                  py27_0    defaults
sip                       4.16.9                   py27_0    defaults
six                       1.10.0                   py27_0    defaults
snowballstemmer           1.2.1                    py27_0    defaults
sockjs-tornado            1.0.3                    py27_0    defaults
sphinx                    1.4.1                    py27_0    defaults
sphinx_rtd_theme          0.1.9                    py27_0    defaults
sphinxcontrib-bibtex      0.3.4                     <pip>
spyder                    2.3.9                    py27_0    defaults
sqlalchemy                1.0.13                   py27_0    defaults
sqlite                    3.13.0                        0    defaults
ssl_match_hostname        3.4.0.2                  py27_1    defaults
statsmodels               0.6.1               np110py27_1    defaults
sympy                     1.0                      py27_0    defaults
terminado                 0.6                      py27_0    defaults
tk                        8.5.18                        0    defaults
toolz                     0.8.0                    py27_0    defaults
Topology                  2.10.0                    <pip>
tornado                   4.3                      py27_1    defaults
traitlets                 4.2.1                    py27_0    defaults
tweepy                    3.5.0                     <pip>
unicodecsv                0.14.1                   py27_0    defaults
werkzeug                  0.11.10                  py27_0    defaults
wheel                     0.29.0                   py27_0    defaults
wordcloud                 1.2.1                     <pip>
xlrd                      1.0.0                    py27_0    defaults
xlsxwriter                0.9.2                    py27_0    defaults
xlwings                   0.7.2                    py27_0    defaults
xlwt                      1.1.2                    py27_0    defaults
xz                        5.2.2                         0    defaults
yaml                      0.1.6                         0    defaults
zlib                      1.2.8                         3    defaults

```

**Comment by goanpeca** [comment]
You are using outdated and deprecated versions of several packages, please update.

Open a terminal (on Linux or Mac) or the Anaconda Command Prompt (on windows)
and type:

```
conda update conda
conda update --all
```

**Comment by harryHoward** [comment]
Mr. Peña-Castellanos,

thanx for your quick response. I updated following your instructions and all is well. In my defense, when I started using Anaconda, the update instructions were:

```
conda update conda
conda update anaconda
```

Clearly, that is no longer adequate, as I had dozens of out-of-date modules. Thanx again for putting me on the right path.
