### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by manimarashi** [ContinuumIO/anaconda-issues#9849]
## Main error
Application <b>orange3</b> launch may have produced errors.
## Traceback
```
C:\Users\smarash1\AppData\Local\Continuum\Anaconda3\lib\site-packages\orangecontrib\datafusion\widgets\graphview.py:10: RuntimeWarning: Loaded module AnyQt._backport as a substitute for PyQt4
  from PyQt4 import QtCore, QtGui
C:\Users\smarash1\AppData\Local\Continuum\Anaconda3\lib\site-packages\orangecontrib\datafusion\widgets\graphview.py:11: RuntimeWarning: Loaded module AnyQt._backport.QtCore as a substitute for PyQt4.QtCore
  from PyQt4.QtCore import QLineF, QPointF, QRectF, Qt
C:\Users\smarash1\AppData\Local\Continuum\Anaconda3\lib\site-packages\orangecontrib\datafusion\widgets\graphview.py:12: RuntimeWarning: Loaded module AnyQt._backport.QtGui as a substitute for PyQt4.QtGui
  from PyQt4.QtGui import qApp, QBrush, QPen, QPolygonF, QStyle, QColor, QFont
Error while importing 'orangecontrib.bio.widgets3.OWGeneNetwork'. The widget will not be shown.
Traceback (most recent call last):
  File "C:\Users\smarash1\AppData\Local\Continuum\Anaconda3\lib\site-packages\Orange\canvas\registry\discovery.py", line 261, in iter_widget_descriptions
    module = asmodule(name)
  File "C:\Users\smarash1\AppData\Local\Continuum\Anaconda3\lib\site-packages\Orange\canvas\registry\discovery.py", line 491, in asmodule
    return __import__(module, fromlist=[""])
  File "C:\Users\smarash1\AppData\Local\Continuum\Anaconda3\lib\site-packages\orangecontrib\bio\widgets3\OWGeneNetwork.py", line 15, in <module>
    from orangecontrib import network
ImportError: cannot import name 'network'
Error parsing
Traceback (most recent call last):
  File "C:\Users\smarash1\AppData\Local\Continuum\Anaconda3\lib\site-packages\Orange\canvas\help\provider.py", line 195, in _load_inventory
    self.items = self._parse(stream.read().decode("utf-8"))
  File "C:\Users\smarash1\AppData\Local\Continuum\Anaconda3\lib\site-packages\Orange\canvas\help\provider.py", line 207, in _parse
    for el in self.root.findall(path):
AttributeError: 'NoneType' object has no attribute 'findall'

```
## System information
```
python: 3.6.6
language: en_US
os: Windows;10;10.0.16299;AMD64;Intel64 Family 6 Model 158 Stepping 9, GenuineIntel
version: 1.6.2
platform: win-64
qt: 5.6.2
pyqt: 5.6.0
conda: 4.5.8
```

**Comment by goanpeca** [comment]
Please remember to update to the latest version of Navigator to include
the latest fixes.

Open a terminal (on Linux or Mac) or the Anaconda Command Prompt (on windows)
and type:

```
conda update conda
conda update anaconda-navigator
conda update navigator-updater
```
