### ISSUE TITLE
Anaconda navigator doesn't show up

### ISSUE THREAD

**Issue by ambekarsameer** [ContinuumIO/anaconda-issues#9868]
Main Error
expected str, bytes or os.PathLike object, not NoneType
Traceback
Traceback (most recent call last):
  File "/home/sameer/anaconda3/lib/python3.6/site-packages/anaconda_navigator/exceptions.py", line 75, in exception_handler
    return_value = func(*args, **kwargs)
  File "/home/sameer/anaconda3/lib/python3.6/site-packages/anaconda_navigator/app/start.py", line 150, in start_app
    window = run_app(splash)
  File "/home/sameer/anaconda3/lib/python3.6/site-packages/anaconda_navigator/app/start.py", line 65, in run_app
    window = MainWindow(splash=splash, tab_project=False)
  File "/home/sameer/anaconda3/lib/python3.6/site-packages/anaconda_navigator/widgets/main_window.py", line 163, in __init__
    self.api = AnacondaAPI()
  File "/home/sameer/anaconda3/lib/python3.6/site-packages/anaconda_navigator/api/anaconda_api.py", line 2185, in AnacondaAPI
    ANACONDA_API = _AnacondaAPI()
  File "/home/sameer/anaconda3/lib/python3.6/site-packages/anaconda_navigator/api/anaconda_api.py", line 89, in __init__
    self._conda_api = CondaAPI()
  File "/home/sameer/anaconda3/lib/python3.6/site-packages/anaconda_navigator/api/conda_api.py", line 1714, in CondaAPI
    CONDA_API = _CondaAPI()
  File "/home/sameer/anaconda3/lib/python3.6/site-packages/anaconda_navigator/api/conda_api.py", line 353, in __init__
    self.sys_rc_path = join(self.ROOT_PREFIX, '.condarc')
  File "/home/sameer/anaconda3/lib/python3.6/posixpath.py", line 80, in join
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType

from the terminal conda update --all command returns nothing. It prompts me to enter a new command. 

Please help me. 
Ubuntu 16.4
conda 4.5.8

when I type anaconda-navigator in the terminal it shows this error 
![image](https://user-images.githubusercontent.com/25266231/43637155-d4f123f4-9731-11e8-9d66-9cd3ba318f6b.png)

**Comment by goanpeca** [comment]
@ambekarsameer please open a terminal and provide the requested information on the issue template.



### Actual Behavior



### Expected Behavior



### Steps to Reproduce




##### Anaconda or Miniconda version:

##### Operating System:

##### `conda info`

```

```

##### `conda list --show-channel-urls`

```

```

**Comment by ambekarsameer** [comment]
sameer@sameer:~$ conda info
sameer@sameer:~$ conda list --show-channel-urls
sameer@sameer:~$ 

As you can see above that it shows nothing.

Ubuntu version - 16.04 

although it shows me the version of conda. 
sameer@sameer:~$ conda --v
conda 4.5.8

**Comment by ambekarsameer** [comment]
Actual Behaviour : It shows me the error message and doesn't open the anaconda navigator
Expected Behaviour : It should open the anaconda navigator through which I can open jupyter-notebook
Steps to Reproduce : type "anaconda-navigator" to in terminal or launch it from ubuntu apps.

**Comment by goanpeca** [comment]
@ambekarsameer unless you provide the output of `conda info` and `conda list` we cannot help you debug the issue
