### ISSUE TITLE
An unexpected error occurred on Navigator start-up

### ISSUE THREAD

**Issue by jasleen-chadha** [ContinuumIO/anaconda-issues#9876]
I'm getting the following error after installing Anaconda Navigator.  Kindly help me out. Thank you! 

    <html>
    <head>
      <title>Navigator Error</title>
    </head>
    <body>
      <div>
        <h1>Navigator Error</h1>
        <p>An unexpected error occurred on Navigator start-up</p>
        <h2>Report</h2>
        <p>Please report this issue in the anaconda
          <a href="https://github.com/continuumio/anaconda-issues">
            issue tracker
          </a>
        </p>
      </div>
      <div>
        <h2>Main Error</h2>
        <p><pre>expected str, bytes or os.PathLike object, not NoneType</pre></p>
        <h2>Traceback</h2>
        <p><pre>Traceback (most recent call last):
  File "C:\anacondanavigator\lib\site-packages\anaconda_navigator\exceptions.py", line 75, in exception_handler
    return_value = func(*args, **kwargs)
  File "C:\anacondanavigator\lib\site-packages\anaconda_navigator\app\start.py", line 150, in start_app
    window = run_app(splash)
  File "C:\anacondanavigator\lib\site-packages\anaconda_navigator\app\start.py", line 65, in run_app
    window = MainWindow(splash=splash, tab_project=False)
  File "C:\anacondanavigator\lib\site-packages\anaconda_navigator\widgets\main_window.py", line 163, in __init__
    self.api = AnacondaAPI()
  File "C:\anacondanavigator\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 2185, in AnacondaAPI
    ANACONDA_API = _AnacondaAPI()
  File "C:\anacondanavigator\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 89, in __init__
    self._conda_api = CondaAPI()
  File "C:\anacondanavigator\lib\site-packages\anaconda_navigator\api\conda_api.py", line 1714, in CondaAPI
    CONDA_API = _CondaAPI()
  File "C:\anacondanavigator\lib\site-packages\anaconda_navigator\api\conda_api.py", line 353, in __init__
    self.sys_rc_path = join(self.ROOT_PREFIX, '.condarc')
  File "C:\anacondanavigator\lib\ntpath.py", line 76, in join
    path = os.fspath(path)
TypeError: expected str, bytes or os.PathLike object, not NoneType
</pre></p>
      </div>
    </body>
    </html>

**Comment by goanpeca** [comment]
@jasleen-chadha please provide the information requested on the issue template.



### Actual Behavior



### Expected Behavior



### Steps to Reproduce




##### Anaconda or Miniconda version:

##### Operating System:

##### `conda info`

```

```

##### `conda list --show-channel-urls`

```

```

**Comment by jasleen-chadha** [comment]
Navigator Error

An unexpected error occurred on Navigator start-up

Main Error

TypeError: expected str, bytes or os.PathLike object, not NoneType

Jasleen Chadha

**Comment by goanpeca** [comment]
@jasleen-chadha that is not the information requested. Please fill the requested information.
