### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by rand-RI** [ContinuumIO/anaconda-issues#9877]
## Main error
Application <b>jupyterlab</b> launch may have produced errors.
## Traceback
```
[I 22:16:12.695 LabApp] JupyterLab beta preview extension loaded from C:\Users\xxklow\Anaconda3\lib\site-packages\jupyterlab
[I 22:16:12.695 LabApp] JupyterLab application directory is C:\Users\xxklow\Anaconda3\share\jupyter\lab
[W 22:16:12.709 LabApp] Error loading server extension jupyterlab
    Traceback (most recent call last):
      File "C:\Users\xxklow\Anaconda3\lib\site-packages\jupyterlab\commands.py", line 321, in __init__
        self._run(['node', 'node-version-check.js'], cwd=HERE, quiet=True)
      File "C:\Users\xxklow\Anaconda3\lib\site-packages\jupyterlab\commands.py", line 1165, in _run
        proc = Process(cmd, **kwargs)
      File "C:\Users\xxklow\Anaconda3\lib\site-packages\jupyterlab\process.py", line 73, in __init__
        self.proc = self._create_process(cwd=cwd, env=env)
      File "C:\Users\xxklow\Anaconda3\lib\site-packages\jupyterlab\process.py", line 131, in _create_process
        cmd[0] = which(cmd[0], kwargs.get('env'))
      File "C:\Users\xxklow\Anaconda3\lib\site-packages\jupyterlab\jlpmapp.py", line 59, in which
        raise ValueError(msg)
    ValueError: Please install nodejs 5+ and npm before continuing installation. nodejs may be installed using conda or directly from the nodejs website.
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "C:\Users\xxklow\Anaconda3\lib\site-packages\notebook\notebookapp.py", line 1454, in init_server_extensions
        func(self)
      File "C:\Users\xxklow\Anaconda3\lib\site-packages\jupyterlab\extension.py", line 111, in load_jupyter_server_extension
        info = get_app_info(app_dir)
      File "C:\Users\xxklow\Anaconda3\lib\site-packages\jupyterlab\commands.py", line 244, in get_app_info
        handler = _AppHandler(app_dir, logger)
      File "C:\Users\xxklow\Anaconda3\lib\site-packages\jupyterlab\commands.py", line 324, in __init__
        raise ValueError(msg)
    ValueError: Please install nodejs 5+ and npm before continuing installation. nodejs may be installed using conda or directly from the nodejs website.
[W 22:16:12.719 LabApp] JupyterLab server extension not enabled, manually loading...
[I 22:16:12.720 LabApp] JupyterLab beta preview extension loaded from C:\Users\xxklow\Anaconda3\lib\site-packages\jupyterlab
[I 22:16:12.720 LabApp] JupyterLab application directory is C:\Users\xxklow\Anaconda3\share\jupyter\lab
Traceback (most recent call last):
  File "C:\Users\xxklow\Anaconda3\lib\site-packages\jupyterlab\commands.py", line 321, in __init__
    self._run(['node', 'node-version-check.js'], cwd=HERE, quiet=True)
  File "C:\Users\xxklow\Anaconda3\lib\site-packages\jupyterlab\commands.py", line 1165, in _run
    proc = Process(cmd, **kwargs)
  File "C:\Users\xxklow\Anaconda3\lib\site-packages\jupyterlab\process.py", line 73, in __init__
    self.proc = self._create_process(cwd=cwd, env=env)
  File "C:\Users\xxklow\Anaconda3\lib\site-packages\jupyterlab\process.py", line 131, in _create_process
    cmd[0] = which(cmd[0], kwargs.get('env'))
  File "C:\Users\xxklow\Anaconda3\lib\site-packages\jupyterlab\jlpmapp.py", line 59, in which
    raise ValueError(msg)
ValueError: Please install nodejs 5+ and npm before continuing installation. nodejs may be installed using conda or directly from the nodejs website.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\xxklow\Anaconda3\Scripts\jupyter-lab-script.py", line 10, in <module>
    sys.exit(main())
  File "C:\Users\xxklow\Anaconda3\lib\site-packages\jupyter_core\application.py", line 266, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "C:\Users\xxklow\Anaconda3\lib\site-packages\traitlets\config\application.py", line 657, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-7>", line 2, in initialize
  File "C:\Users\xxklow\Anaconda3\lib\site-packages\traitlets\config\application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "C:\Users\xxklow\Anaconda3\lib\site-packages\notebook\notebookapp.py", line 1510, in initialize
    self.init_server_extensions()
  File "C:\Users\xxklow\Anaconda3\lib\site-packages\jupyterlab\labapp.py", line 213, in init_server_extensions
    load_jupyter_server_extension(self)
  File "C:\Users\xxklow\Anaconda3\lib\site-packages\jupyterlab\extension.py", line 111, in load_jupyter_server_extension
    info = get_app_info(app_dir)
  File "C:\Users\xxklow\Anaconda3\lib\site-packages\jupyterlab\commands.py", line 244, in get_app_info
    handler = _AppHandler(app_dir, logger)
  File "C:\Users\xxklow\Anaconda3\lib\site-packages\jupyterlab\commands.py", line 324, in __init__
    raise ValueError(msg)
ValueError: Please install nodejs 5+ and npm before continuing installation. nodejs may be installed using conda or directly from the nodejs website.

```
## System information
```
python: 3.6.4
language: en_AU
os: Windows;10;10.0.17134;AMD64;Intel64 Family 6 Model 78 Stepping 3, GenuineIntel
version: 1.6.2
platform: win-64
qt: 5.6.2
pyqt: 5.6.0
conda: 4.5.9
```

**Comment by goanpeca** [comment]
Please remember to update to the latest version of Navigator to include
the latest fixes.

Open a terminal (on Linux or Mac) or the Anaconda Command Prompt (on windows)
and type:

```
conda update conda
conda update --all
```
