### ISSUE TITLE
What is this error

### ISSUE THREAD

**Issue by NavinSinghsays** [ContinuumIO/anaconda-issues#9879]
`import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
Traceback (most recent call last):

  File "<ipython-input-1-2422ca4a6ed6>", line 2, in <module>
    import matplotlib.pyplot as plt

  File "C:\Users\Navin\Anaconda3\lib\site-packages\matplotlib\__init__.py", line 127, in <module>
    from . import cbook

  File "C:\Users\Navin\Anaconda3\lib\site-packages\matplotlib\cbook\__init__.py", line 2640, in <module>
    class _StringFuncParser(object):

  File "C:\Users\Navin\Anaconda3\lib\site-packages\matplotlib\cbook\__init__.py", line 2652, in _StringFuncParser
    _funcs['quadratic'] = _FuncInfo(np.square,

AttributeError: module 'numpy' has no attribute 'square'`

**Comment by goanpeca** [comment]
You did not provide the requested information on the issue template.



### Actual Behavior



### Expected Behavior



### Steps to Reproduce




##### Anaconda or Miniconda version:

##### Operating System:

##### `conda info`

```

```

##### `conda list --show-channel-urls`

```

```
