### ISSUE TITLE
Annaconda Navigator suddenly stop to open

### ISSUE THREAD

**Issue by Tasze** [ContinuumIO/anaconda-issues#9900]
##### `conda info`

```

```

##### `conda list --show-channel-urls`

```

```

**Comment by goanpeca** [comment]
Please provide the information requested in the template

**Comment by Tasze** [comment]
I do have Mac Air and Annaconda 3
I am not able to see any information  regarding annaconda. I run anaconda -V and got  following.

Traceback (most recent call last):
  File "/Users/zeba/anaconda3/bin/conda", line 11, in <module>
    sys.exit(main())
  File "/Users/zeba/anaconda3/lib/python3.6/site-packages/conda/cli/main.py", line 112, in main
    from ..exceptions import conda_exception_handler
  File "/Users/zeba/anaconda3/lib/python3.6/site-packages/conda/exceptions.py", line 18, in <module>
    from .common.io import timeout
  File "/Users/zeba/anaconda3/lib/python3.6/site-packages/conda/common/io.py", line 5, in <module>
    from concurrent.futures import ThreadPoolExecutor, _base, as_completed
  File "/Users/zeba/anaconda3/lib/python3.6/concurrent/futures/__init__.py", line 17, in <module>
    from concurrent.futures.process import ProcessPoolExecutor
  File "/Users/zeba/anaconda3/lib/python3.6/concurrent/futures/process.py", line 55, in <module>
    from multiprocessing.connection import wait
  File "/Users/zeba/anaconda3/lib/python3.6/multiprocessing/connection.py", line 18, in <module>
    import tempfile
  File "/Users/zeba/anaconda3/lib/python3.6/tempfile.py", line 45, in <module>
    from random import Random as _Random
ModuleNotFoundError: No module named 'random'
