### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by nawar82** [ContinuumIO/anaconda-issues#9919]
## Main error
Application <b>spyder</b> launch may have produced errors.
## Traceback
```
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\Scripts\spyder-script.py", line 10, in <module>
    sys.exit(main())
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\app\start.py", line 179, in main
    from spyder.app import mainwindow
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 51, in <module>
    requirements.check_spyder_kernels()
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\requirements.py", line 66, in check_spyder_kernels
    % actual_ver)
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\requirements.py", line 24, in show_warning
    raise RuntimeError(message)
RuntimeError: Please check Spyder installation requirements:
spyder-kernels >= 1.0 is required (found 0.2.4).

```
## System information
```
python: 3.6.5
language: da_DK
os: Windows;7;6.1.7601;AMD64;Intel64 Family 6 Model 78 Stepping 3, GenuineIntel
version: 1.6.2
platform: win-64
qt: 5.9.6
pyqt: 5.9.2
conda: 4.5.9
```

**Comment by goanpeca** [comment]
Please remember to update to the latest version of Navigator to include
the latest fixes.

Open a terminal (on Linux or Mac) or the Anaconda Command Prompt (on windows)
and type:

```
conda update conda
conda update --all
```
