### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by debebe123** [ContinuumIO/anaconda-issues#9923]
## Main error
Application <b>spyder</b> launch may have produced errors.
## Traceback
```
Traceback (most recent call last):
  File "c:\anaconda\lib\site-packages\spyder\app\mainwindow.py", line 3099, in main
    mainwindow = run_spyder(app, options, args)
  File "c:\anaconda\lib\site-packages\spyder\app\mainwindow.py", line 3001, in run_spyder
    main.setup()
  File "c:\anaconda\lib\site-packages\spyder\app\mainwindow.py", line 922, in setup
    from spyder.plugins.ipythonconsole import IPythonConsole
  File "c:\anaconda\lib\site-packages\spyder\plugins\ipythonconsole.py", line 59, in <module>
    from spyder.widgets.ipythonconsole import ClientWidget
  File "c:\anaconda\lib\site-packages\spyder\widgets\ipythonconsole\__init__.py", line 12, in <module>
    from .debugging import DebuggingWidget
  File "c:\anaconda\lib\site-packages\spyder\widgets\ipythonconsole\debugging.py", line 16, in <module>
    from qtconsole.rich_jupyter_widget import RichJupyterWidget
  File "c:\anaconda\lib\site-packages\qtconsole\rich_jupyter_widget.py", line 14, in <module>
    from .jupyter_widget import JupyterWidget
  File "c:\anaconda\lib\site-packages\qtconsole\jupyter_widget.py", line 19, in <module>
    from IPython.lib.lexers import IPythonLexer, IPython3Lexer
  File "c:\anaconda\lib\site-packages\IPython\__init__.py", line 48, in <module>
    from .core.application import Application
  File "c:\anaconda\lib\site-packages\IPython\core\application.py", line 25, in <module>
    from IPython.core import release, crashhandler
  File "c:\anaconda\lib\site-packages\IPython\core\crashhandler.py", line 28, in <module>
    from IPython.core import ultratb
  File "c:\anaconda\lib\site-packages\IPython\core\ultratb.py", line 128, in <module>
    from IPython.utils.terminal import get_terminal_size
  File "c:\anaconda\lib\site-packages\IPython\utils\terminal.py", line 22, in <module>
    from backports.shutil_get_terminal_size import get_terminal_size as _get_terminal_size
ImportError: No module named shutil_get_terminal_size

```
## System information
```
platform: win-64
version: 1.6.2
conda: 4.4.11
qt: 5.6.2
language: en_US
python: 2.7.13
os: Windows;10;10.0.16299;AMD64;Intel64 Family 6 Model 94 Stepping 3, GenuineIntel
pyqt: 5.6.0
```

**Comment by goanpeca** [comment]
Please remember to update to the latest version of Navigator to include
the latest fixes.

Open a terminal (on Linux or Mac) or the Anaconda Command Prompt (on windows)
and type:

```
conda update conda
conda update --all
```
