### ISSUE TITLE
Missing visualisation widgets in Orange app

### ISSUE THREAD

**Issue by fascani** [ContinuumIO/anaconda-issues#993]
Hello,

for some reason, I am missing visualization widgets such as Scatter Plot in the Orange app. In canvas.log, I found these error messages: 

Could not import 'Orange.OrangeWidgets.VisualizeQt.OWScatterPlotGraphQt'.
Traceback (most recent call last):
 ...
ImportError: cannot import name orangeqt

and

Could not import 'Orange.OrangeWidgets.Prototypes.OWTimeDataVisualizerGraph'.
Traceback (most recent call last):
...
ImportError: No module named Qwt5

which tells me it is related to the absence of the widgets. I downloaded Python 2.7 for Windows 7 64x via Anaconda. My machine had previously Python 3.4 installed by my IT department, probably not via Anaconda so I am wondering if I should uninstall that bit and re-install Anaconda?

Thanks

**Comment by tomasarcher** [comment]
Hello.

I have the exact same problem here.

Anaconda2 on windows 10 - Python 2.7.12 | Anaconda 4.1.1 (64-bit) | orange 2.7.8 | orange-app 1.0.1

Like fascani, In canvas.log, I find this type of error messages:

_Running widget discovery process.
Could not import 'Orange.OrangeWidgets.Data.OWDiscretize'.
Traceback (most recent call last):
  File "C:\Users\tomas.archer\Anaconda2\lib\site-packages\Orange\OrangeCanvas\registry\discovery.py", line 296, in iter_widget_descriptions
    module = asmodule(name)
  File "C:\Users\tomas.archer\Anaconda2\lib\site-packages\Orange\OrangeCanvas\registry\discovery.py", line 557, in asmodule
    return __import__(module, fromlist=[""])
  File "C:\Users\tomas.archer\Anaconda2\lib\site-packages\Orange\OrangeWidgets\Data\OWDiscretize.py", line 3, in <module>
    from OWGraph import *
  File "C:\Users\tomas.archer\Anaconda2\lib\site-packages\Orange\OrangeWidgets\OWGraph.py", line 6, in <module>
    from PyQt4.Qwt5 import *
ImportError: No module named Qwt5_

and

_Could not import 'Orange.OrangeWidgets.VisualizeQt.OWDiscretizeQt'.
Traceback (most recent call last):
  File "C:\Users\tomas.archer\Anaconda2\lib\site-packages\Orange\OrangeCanvas\registry\discovery.py", line 296, in iter_widget_descriptions
    module = asmodule(name)
  File "C:\Users\tomas.archer\Anaconda2\lib\site-packages\Orange\OrangeCanvas\registry\discovery.py", line 557, in asmodule
    return __import__(module, fromlist=[""])
  File "C:\Users\tomas.archer\Anaconda2\lib\site-packages\Orange\OrangeWidgets\VisualizeQt\OWDiscretizeQt.py", line 10, in <module>
    from plot.owplot import *
  File "C:\Users\tomas.archer\Anaconda2\lib\site-packages\Orange\OrangeWidgets\plot\__init__.py", line 15, in <module>
    from owcurve import *
  File "C:\Users\tomas.archer\Anaconda2\lib\site-packages\Orange\OrangeWidgets\plot\owcurve.py", line 138, in <module>
    from Orange import orangeqt
ImportError: cannot import name orangeqt_

I cannot find any reference to the Qwt5 module in the anaconda installation folder, so I guess that might me part of the problem.

Are there any ideas on how to fix this problem?

Thanks,

**Comment by fascani** [comment]
I recently installed Python 3.5 with anaconda, replacing the 2.7 Python
version and Orange did have more plotting tools than before although I did
not check it has everything.

Francois
