### ISSUE TITLE
Navigator Error: Main Error 'conda_prefix'

### ISSUE THREAD

**Issue by QianXuX** [ContinuumIO/anaconda-issues#9942]
### Actual Behavior

When I double clicked on the "Anaconda-Navigator" application, a tab pops up with the error message.

### Expected Behavior

No problems opening the app.

### Steps to Reproduce

When I double clicked on the "Anaconda-Navigator" application, a tab pops up with the error message:

Navigator Error
An unexpected error occurred on Navigator start-up

Report
Please report this issue in the anaconda issue tracker

Main Error
'conda_prefix'
Traceback
Traceback (most recent call last):
  File "/Users/Qian/anaconda2/envs/py36/lib/python3.6/site-packages/anaconda_navigator/exceptions.py", line 75, in exception_handler
    return_value = func(*args, **kwargs)
  File "/Users/Qian/anaconda2/envs/py36/lib/python3.6/site-packages/anaconda_navigator/app/start.py", line 115, in start_app
    window = run_app(splash)
  File "/Users/Qian/anaconda2/envs/py36/lib/python3.6/site-packages/anaconda_navigator/app/start.py", line 58, in run_app
    window = MainWindow(splash=splash)
  File "/Users/Qian/anaconda2/envs/py36/lib/python3.6/site-packages/anaconda_navigator/widgets/main_window.py", line 160, in __init__
    self.api = AnacondaAPI()
  File "/Users/Qian/anaconda2/envs/py36/lib/python3.6/site-packages/anaconda_navigator/api/anaconda_api.py", line 1205, in AnacondaAPI
    ANACONDA_API = _AnacondaAPI()
  File "/Users/Qian/anaconda2/envs/py36/lib/python3.6/site-packages/anaconda_navigator/api/anaconda_api.py", line 65, in __init__
    self._conda_api = CondaAPI()
  File "/Users/Qian/anaconda2/envs/py36/lib/python3.6/site-packages/anaconda_navigator/api/conda_api.py", line 1622, in CondaAPI
    CONDA_API = _CondaAPI()
  File "/Users/Qian/anaconda2/envs/py36/lib/python3.6/site-packages/anaconda_navigator/api/conda_api.py", line 340, in __init__
    self.set_conda_prefix()
  File "/Users/Qian/anaconda2/envs/py36/lib/python3.6/site-packages/anaconda_navigator/api/conda_api.py", line 490, in set_conda_prefix
    self.CONDA_PREFIX = info['conda_prefix']
KeyError: 'conda_prefix'

Browser URL: file:///private/var/folders/wx/w07ktx196wj9dw5f0kblmmdm0000gn/T/tmpw24tyg9e.html

##### `conda info`

```
➜ conda info
Using Anaconda API: https://api.anaconda.org
Current conda install:

             platform : osx-64
        conda version : 4.0.8
  conda-build version : 2.0.2
       python version : 2.7.12.final.0
     requests version : 2.11.1
     root environment : /Users/Qian/anaconda2  (writable)
  default environment : /Users/Qian/anaconda2
     envs directories : /Users/Qian/anaconda2/envs
        package cache : /Users/Qian/anaconda2/pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/osx-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/osx-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : None
    is foreign system : False
```

##### `conda list --show-channel-urls`

```
➜ conda list --show-channel-urls

# packages in environment at /Users/Qian/anaconda2:
#
DEPRECATION: The default format will switch to columns in the future. You can use --format=(legacy|columns) (or define a format=(legacy|columns) in your pip.conf under the [list] section) to disable this warning.
_license                  1.1                      py27_1    defaults
_nb_ext_conf              0.3.0                    py27_0    defaults
alabaster                 0.7.9                    py27_0    defaults
anaconda                  4.2.0               np111py27_0    defaults
anaconda-clean            1.0.0                    py27_0    defaults
anaconda-client           1.5.1                    py27_0    defaults
anaconda-navigator        1.3.1                    py27_0    defaults
appnope                   0.1.0                    py27_0    defaults
appscript                 1.0.1                    py27_0    defaults
argcomplete               1.0.0                    py27_1    defaults
astroid                   1.4.7                    py27_0    defaults
astropy                   1.2.1               np111py27_0    defaults
autopep8                  1.3.5                     <pip>
babel                     2.3.4                    py27_0    defaults
backports                 1.0                      py27_0    defaults
backports-abc             0.4                       <pip>
backports.shutil-get-terminal-size 1.0.0                     <pip>
backports.ssl-match-hostname 3.4.0.2                   <pip>
backports_abc             0.4                      py27_0    defaults
beautifulsoup4            4.5.1                    py27_0    defaults
bitarray                  0.8.1                    py27_0    defaults
blaze                     0.10.1                   py27_0    defaults
bokeh                     0.12.2                   py27_0    defaults
boto                      2.42.0                   py27_0    defaults
bottleneck                1.1.0               np111py27_0    defaults
cdecimal                  2.3                      py27_2    defaults
cffi                      1.7.0                    py27_0    defaults
chest                     0.2.3                    py27_0    defaults
click                     6.6                      py27_0    defaults
cloudpickle               0.2.1                    py27_0    defaults
clyent                    1.2.2                    py27_0    defaults
colorama                  0.3.7                    py27_0    defaults
conda                     4.0.8                    py27_0    defaults
conda-build               2.0.2                    py27_0    defaults
conda-env                 2.4.5                    py27_0    defaults
configobj                 5.0.6                    py27_0    defaults
configparser              3.5.0                    py27_0    defaults
contextlib2               0.5.3                    py27_0    defaults
cryptography              1.5                      py27_0    defaults
curl                      7.49.0                        1    defaults
cycler                    0.10.0                   py27_0    defaults
cython                    0.24.1                   py27_0    defaults
cytoolz                   0.8.0                    py27_0    defaults
dask                      0.11.0                   py27_0    defaults
datashape                 0.5.2                    py27_0    defaults
decorator                 4.0.10                   py27_0    defaults
dill                      0.2.5                    py27_0    defaults
django                    1.10.4                    <pip>
docutils                  0.12                     py27_2    defaults
dynd                      0.7.3.dev1                <pip>
dynd-python               0.7.2                    py27_0    defaults
entrypoints               0.2.2                    py27_0    defaults
enum34                    1.1.6                    py27_0    defaults
et-xmlfile                1.0.1                     <pip>
et_xmlfile                1.0.1                    py27_0    defaults
fastcache                 1.0.2                    py27_1    defaults
filelock                  2.0.6                    py27_0    defaults
flask                     0.11.1                   py27_0    defaults
flask-cors                2.1.2                    py27_0    defaults
freetype                  2.5.5                         1    defaults
funcsigs                  1.0.2                    py27_0    defaults
functools32               3.2.3.2                  py27_0    defaults
futures                   3.0.5                    py27_0    defaults
get_terminal_size         1.0.0                    py27_0    defaults
gevent                    1.1.2                    py27_0    defaults
greenlet                  0.4.10                   py27_0    defaults
grin                      1.2.1                    py27_3    defaults
gunicorn                  19.7.1                    <pip>
h5py                      2.6.0               np111py27_2    defaults
hdf5                      1.8.17                        1    defaults
heapdict                  1.0.0                    py27_1    defaults
httplib2                  0.10.3                    <pip>
icu                       54.1                          0    defaults
idna                      2.1                      py27_0    defaults
imagesize                 0.7.1                    py27_0    defaults
indicoio                  1.0.8                     <pip>
ipaddress                 1.0.16                   py27_0    defaults
ipykernel                 4.5.0                    py27_0    defaults
ipython                   5.1.0                    py27_0    defaults
ipython-genutils          0.1.0                     <pip>
ipython_genutils          0.1.0                    py27_0    defaults
ipywidgets                5.2.2                    py27_0    defaults
itsdangerous              0.24                     py27_0    defaults
jbig                      2.1                           0    defaults
jdcal                     1.2                      py27_1    defaults
jedi                      0.9.0                    py27_1    defaults
jinja2                    2.8                      py27_1    defaults
jpeg                      8d                            2    defaults
jsonschema                2.5.1                    py27_0    defaults
jupyter                   1.0.0                    py27_3    defaults
jupyter-client            4.4.0                     <pip>
jupyter-console           5.0.0                     <pip>
jupyter-core              4.2.0                     <pip>
jupyter_client            4.4.0                    py27_0    defaults
jupyter_console           5.0.0                    py27_0    defaults
jupyter_core              4.2.0                    py27_0    defaults
lazy-object-proxy         1.2.1                    py27_0    defaults
libdynd                   0.7.2                         0    defaults
libpng                    1.6.22                        0    defaults
libtiff                   4.0.6                         2    defaults
libxml2                   2.9.2                         0    defaults
libxslt                   1.1.28                        2    defaults
llvmlite                  0.13.0                   py27_0    defaults
locket                    0.2.0                    py27_1    defaults
lxml                      3.6.4                    py27_0    defaults
markupsafe                0.23                     py27_2    defaults
matplotlib                1.5.3               np111py27_0    defaults
mistune                   0.7.3                    py27_1    defaults
mkl                       11.3.3                        0    defaults
mkl-service               1.1.2                    py27_2    defaults
mock                      1.3.0                     <pip>
mpmath                    0.19                     py27_1    defaults
multipledispatch          0.4.8                    py27_0    defaults
nb-anacondacloud          1.2.0                     <pip>
nb-conda                  2.0.0                     <pip>
nb-conda-kernels          2.0.0                     <pip>
nb_anacondacloud          1.2.0                    py27_0    defaults
nb_conda                  2.0.0                    py27_0    defaults
nb_conda_kernels          2.0.0                    py27_0    defaults
nbconvert                 4.2.0                    py27_0    defaults
nbformat                  4.1.0                    py27_0    defaults
nbpresent                 3.0.2                    py27_0    defaults
networkx                  1.11                     py27_0    defaults
nltk                      3.2.1                    py27_0    defaults
nose                      1.3.7                    py27_1    defaults
notebook                  4.2.3                    py27_0    defaults
numba                     0.28.1              np111py27_0    defaults
numexpr                   2.6.1               np111py27_0    defaults
numpy                     1.11.1                   py27_0    defaults
oauth2                    1.9.0.post1               <pip>
oauthlib                  2.0.2                     <pip>
odo                       0.5.0                    py27_1    defaults
openpyxl                  2.3.2                    py27_0    defaults
openssl                   1.0.2j                        0    defaults
pandas                    0.18.1              np111py27_0    defaults
partd                     0.3.6                    py27_0    defaults
path.py                   8.2.1                    py27_0    defaults
pathlib2                  2.1.0                    py27_0    defaults
patsy                     0.4.1                    py27_0    defaults
pbr                       2.1.0                     <pip>
pep8                      1.7.0                    py27_0    defaults
pexpect                   4.0.1                    py27_0    defaults
pickleshare               0.7.4                    py27_0    defaults
pillow                    3.3.1                    py27_0    defaults
pip                       8.1.2                    py27_0    defaults
pkginfo                   1.3.2                    py27_0    defaults
ply                       3.9                      py27_0    defaults
prompt-toolkit            1.0.3                     <pip>
prompt_toolkit            1.0.3                    py27_0    defaults
psutil                    4.3.1                    py27_0    defaults
ptyprocess                0.5.1                    py27_0    defaults
py                        1.4.31                   py27_0    defaults
pyasn1                    0.1.9                    py27_0    defaults
pyaudio                   0.2.7                    py27_0    defaults
pycodestyle               2.4.0                     <pip>
pycosat                   0.6.1                    py27_1    defaults
pycparser                 2.14                     py27_1    defaults
pycrypto                  2.6.1                    py27_4    defaults
pycurl                    7.43.0                   py27_0    defaults
pydot                     1.2.3                     <pip>
pydotplus                 2.0.2                     <pip>
pyflakes                  1.3.0                    py27_0    defaults
pygments                  2.1.3                    py27_0    defaults
pylint                    1.5.4                    py27_1    defaults
pyopenssl                 16.0.0                   py27_0    defaults
pyparsing                 2.1.4                    py27_0    defaults
pyqt                      5.6.0                    py27_0    defaults
pytables                  3.2.3.1             np111py27_0    defaults
pytest                    2.9.2                    py27_0    defaults
python                    2.7.12                        1    defaults
python-dateutil           2.5.3                    py27_0    defaults
python.app                1.2                      py27_4    defaults
pytz                      2016.6.1                 py27_0    defaults
pyyaml                    3.12                     py27_0    defaults
pyzmq                     15.4.0                   py27_0    defaults
qt                        5.6.0                         0    defaults
qtawesome                 0.3.3                    py27_0    defaults
qtconsole                 4.2.1                    py27_1    defaults
qtpy                      1.1.2                    py27_0    defaults
readline                  6.2                           2    defaults
redis                     3.2.0                         0    defaults
redis-py                  2.10.5                   py27_0    defaults
requests                  2.11.1                   py27_0    defaults
requests-oauthlib         0.8.0                     <pip>
rope                      0.9.4                    py27_1    defaults
ruamel-yaml-              VERSION                   <pip>
ruamel_yaml               0.11.14                  py27_0    defaults
scikit-image              0.12.3              np111py27_1    defaults
scikit-learn              0.17.1              np111py27_2    defaults
scipy                     0.18.1              np111py27_0    defaults
setuptools                27.2.0                   py27_0    defaults
simplegeneric             0.8.1                    py27_1    defaults
singledispatch            3.4.0.3                  py27_0    defaults
sip                       4.18                     py27_0    defaults
six                       1.10.0                   py27_0    defaults
snowballstemmer           1.2.1                    py27_0    defaults
sockjs-tornado            1.0.3                    py27_0    defaults
sphinx                    1.4.6                    py27_0    defaults
spyder                    3.0.0                    py27_0    defaults
sqlalchemy                1.0.13                   py27_0    defaults
sqlite                    3.13.0                        0    defaults
ssl_match_hostname        3.4.0.2                  py27_1    defaults
statsmodels               0.6.1               np111py27_1    defaults
sympy                     1.0                      py27_0    defaults
tables                    3.2.3.1                   <pip>
tensorflow                0.5.0                     <pip>
terminado                 0.6                      py27_0    defaults
tk                        8.5.18                        0    defaults
toolz                     0.8.0                    py27_0    defaults
tornado                   4.4.1                    py27_0    defaults
traitlets                 4.3.0                    py27_0    defaults
tweepy                    3.5.0                     <pip>
unicodecsv                0.14.1                   py27_0    defaults
urllib                    1.21.1                    <pip>
wcwidth                   0.1.7                    py27_0    defaults
werkzeug                  0.11.11                  py27_0    defaults
wheel                     0.29.0                   py27_0    defaults
widgetsnbextension        1.2.6                    py27_0    defaults
wrapt                     1.10.6                   py27_0    defaults
xlrd                      1.0.0                    py27_0    defaults
xlsxwriter                0.9.3                    py27_0    defaults
xlwings                   0.10.0                   py27_0    defaults
xlwt                      1.1.2                    py27_0    defaults
xz                        5.2.2                         0    defaults
yaml                      0.1.6                         0    defaults
zlib                      1.2.8                         3    defaults

```

**Comment by goanpeca** [comment]
Please remember to update to the latest version of Navigator to include
the latest fixes.

Open a terminal (on Linux or Mac) or the Anaconda Command Prompt (on windows)
and type:

```
conda update conda
conda update --all
```

**Comment by DaliaDawod** [comment]
I have the same problem and 

```
conda update conda
conda update --all
```

did not work for me.
Anyone can help?
