### ISSUE TITLE
Installing anaconda 5.2.0 with miniconda3 failed

### ISSUE THREAD

**Issue by julianhemde** [ContinuumIO/anaconda-issues#9955]
I had previously Anaconda3 installed but had some issues, so i decided to reinstall it. Then I got after starting the Anaconda prompt the message: ...\Scripts\activate.bat is not found. Then i followed these instructions [https://github.com/conda/conda/issues/6053](#6053) and installed miniconda, which solved this first problem but then i got following problems while trying to install anaconda.

### Actual Behavior

After Downloading and extracting packages, this showed up:

```
Preparing transaction: done
Verifying transaction: done
Executing transaction: / menuinst Exception
Traceback (most recent call last):
  File "C:\ProgramData\Miniconda3\lib\site-packages\conda\gateways\disk\create.py", line 207, in make_menu
    menuinst.install(join(prefix, win_path_ok(file_path)), remove, prefix)
AttributeError: module 'menuinst' has no attribute 'instal| menuinst Exception
Traceback (most recent call last):
  File "C:\ProgramData\Miniconda3\lib\site-packages\conda\gateways\disk\create.py", line 207, in make_menu
    menuinst.install(join(prefix, win_path_ok(file_path)), remove, prefix)
AttributeError: module 'menuinst' has no attribute 'instalfailed
ERROR conda.core.link:_execute(502): An error occurred while installing package 'conda-forge::ipykernel-4.8.2-py36_0'.
LinkError: post-link script failed for package conda-forge::ipykernel-4.8.2-py36_0
running your command again with `-v` will provide additional information
location of failed script: C:\ProgramData\Miniconda3\Scripts\.ipykernel-post-link.bat
==> script messages <==
<None>

Attempting to roll back.

Rolling back transaction: \ menuinst Exception
Traceback (most recent call last):
  File "C:\ProgramData\Miniconda3\lib\site-packages\conda\core\link.py", line 794, in run_script
    subprocess_call(command_args, env=env, path=dirname(path))
  File "C:\ProgramData\Miniconda3\lib\site-packages\conda\gateways\subprocess.py", line 56, in subprocess_call
    output=_format_output(command_str, path, rc, stdout, stderr))
subprocess.CalledProcessError: Command '['C:\\Windows\\system32\\cmd.exe', '/d', '/c', 'C:\\ProgramData\\Miniconda3\\Scripts\\.ipykernel-post-link.bat']' return
ed non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ProgramData\Miniconda3\lib\site-packages\conda\core\link.py", line 558, in _execute_actions
    run_script(target_prefix, prec, 'post-unlink' if is_unlink else 'post-link')
  File "C:\ProgramData\Miniconda3\lib\site-packages\conda\core\link.py", line 810, in run_script
    raise LinkError(message)
conda.exceptions.LinkError: post-link script failed for package conda-forge::ipykernel-4.8.2-py36_0
running your command again with `-v` will provide additional information
location of failed script: C:\ProgramData\Miniconda3\Scripts\.ipykernel-post-link.bat
==> script messages <==
<None>


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ProgramData\Miniconda3\lib\site-packages\conda\core\link.py", line 493, in _execute
    cls._execute_actions(pkg_idx, axngroup)
  File "C:\ProgramData\Miniconda3\lib\site-packages\conda\core\link.py", line 574, in _execute_actions
    reverse_excs,
conda.CondaMultiError: post-link script failed for package conda-forge::ipykernel-4.8.2-py36_0
running your command again with `-v` will provide additional information
location of failed script: C:\ProgramData\Miniconda3\Scripts\.ipykernel-post-link.bat
==> script messages <==
<None>



During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ProgramData\Miniconda3\lib\site-packages\conda\gateways\disk\create.py", line 207, in make_menu
    menuinst.install(join(prefix, win_path_ok(file_path)), remove, prefix)
AttributeError: module 'menuinst' has no attribute 'instal| menuinst Exception
Traceback (most recent call last):
  File "C:\ProgramData\Miniconda3\lib\site-packages\conda\core\link.py", line 794, in run_script
    subprocess_call(command_args, env=env, path=dirname(path))
  File "C:\ProgramData\Miniconda3\lib\site-packages\conda\gateways\subprocess.py", line 56, in subprocess_call
    output=_format_output(command_str, path, rc, stdout, stderr))
subprocess.CalledProcessError: Command '['C:\\Windows\\system32\\cmd.exe', '/d', '/c', 'C:\\ProgramData\\Miniconda3\\Scripts\\.ipykernel-post-link.bat']' return
ed non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ProgramData\Miniconda3\lib\site-packages\conda\core\link.py", line 558, in _execute_actions
    run_script(target_prefix, prec, 'post-unlink' if is_unlink else 'post-link')
  File "C:\ProgramData\Miniconda3\lib\site-packages\conda\core\link.py", line 810, in run_script
    raise LinkError(message)
conda.exceptions.LinkError: post-link script failed for package conda-forge::ipykernel-4.8.2-py36_0
running your command again with `-v` will provide additional information
location of failed script: C:\ProgramData\Miniconda3\Scripts\.ipykernel-post-link.bat
==> script messages <==
<None>


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ProgramData\Miniconda3\lib\site-packages\conda\core\link.py", line 493, in _execute
    cls._execute_actions(pkg_idx, axngroup)
  File "C:\ProgramData\Miniconda3\lib\site-packages\conda\core\link.py", line 574, in _execute_actions
    reverse_excs,
conda.CondaMultiError: post-link script failed for package conda-forge::ipykernel-4.8.2-py36_0
running your command again with `-v` will provide additional information
location of failed script: C:\ProgramData\Miniconda3\Scripts\.ipykernel-post-link.bat
==> script messages <==
<None>



During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ProgramData\Miniconda3\lib\site-packages\conda\gateways\disk\create.py", line 207, in make_menu
    menuinst.install(join(prefix, win_path_ok(file_path)), remove, prefix)
AttributeError: module 'menuinst' has no attribute 'instaldone

LinkError: post-link script failed for package conda-forge::ipykernel-4.8.2-py36_0
running your command again with `-v` will provide additional information
location of failed script: C:\ProgramData\Miniconda3\Scripts\.ipykernel-post-link.bat
==> script messages <==
<None>
```

### Expected Behavior

successful installation

### Steps to Reproduce

install miniconda
`conda clean --all`
`conda update --all`
`conda install anaconda=5.2.0`

I also tried with version 5.1.0 but the same.

##### Anaconda or Miniconda version:
downloaded from here: [https://repo.continuum.io/miniconda/Miniconda3-latest-Windows-x86_64.exe](https://repo.continuum.io/miniconda/Miniconda3-latest-Windows-x86_64.exe)

##### `conda info`

```
     active environment : base
    active env location : C:\ProgramData\Miniconda3
            shell level : 1
       user config file : C:\Users\Admin\.condarc
 populated config files : C:\Users\Admin\.condarc
          conda version : 4.5.10
    conda-build version : not installed
         python version : 3.6.6.final.0
       base environment : C:\ProgramData\Miniconda3  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/win-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/win-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/win-64
                          https://repo.anaconda.com/pkgs/pro/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\ProgramData\Miniconda3\pkgs
                          C:\Users\Admin\AppData\Local\conda\conda\pkgs
       envs directories : C:\ProgramData\Miniconda3\envs
                          C:\Users\Admin\AppData\Local\conda\conda\envs
                          C:\Users\Admin\.conda\envs
               platform : win-64
             user-agent : conda/4.5.10 requests/2.19.1 CPython/3.6.6 Windows/7 Windows/6.1.7601
          administrator : True
             netrc file : None
           offline mode : False
```

##### `conda list --show-channel-urls`

```
# packages in environment at C:\ProgramData\Miniconda3:
#
# Name                    Version                   Build  Channel
asn1crypto                0.24.0                   py36_2    conda-forge
ca-certificates           2018.8.13            ha4d7672_0    conda-forge
certifi                   2018.8.13                py36_0    conda-forge
cffi                      1.11.5           py36hfa6e2cd_1    conda-forge
chardet                   3.0.4                    py36_3    conda-forge
conda                     4.5.10                   py36_0    conda-forge
conda-env                 2.6.0                         1    conda-forge
console_shortcut          0.1.1                         3    defaults
cryptography              2.3.1            py36h74b6da3_0    conda-forge
cryptography-vectors      2.3.1                    py36_0    conda-forge
idna                      2.7                      py36_2    conda-forge
menuinst                  1.4.14                   py36_0    conda-forge
openssl                   1.0.2o                   vc14_0  [vc14]  conda-forge
pip                       18.0                     py36_1    conda-forge
pycosat                   0.6.3            py36hfa6e2cd_1    conda-forge
pycparser                 2.18                       py_1    conda-forge
pyopenssl                 18.0.0                   py36_0    conda-forge
pysocks                   1.6.8                    py36_1    conda-forge
python                    3.6.6                he025d50_0    conda-forge
pywin32                   221                      py36_0    conda-forge
requests                  2.19.1                   py36_1    conda-forge
ruamel_yaml               0.15.53          py36hfa6e2cd_0    conda-forge
setuptools                40.0.0                   py36_1    conda-forge
six                       1.11.0                   py36_1    conda-forge
urllib3                   1.23                     py36_1    conda-forge
vc                        14                            0    conda-forge
vs2015_runtime            14.0.25420                    0    conda-forge
wheel                     0.31.1                   py36_1    conda-forge
win_inet_pton             1.0.1                    py36_1    conda-forge
wincertstore              0.2                      py36_2    conda-forge
yaml                      0.1.7                    vc14_0  [vc14]  conda-forge
```

I would appreciate any help, because I'm struggeling a while with issues concerning anaconda.

**Comment by julianhemde** [comment]
Already tried `conda update menuinst`

**Comment by xieliwei** [comment]
Leaving a comment to note that I am facing exactly this issue right now. 

Scripts\activate.bat is missing, tried cleaning up my PATH, PYTHON_PATH, etc, uninstalled all python/anaconda installations, and still activate.bat is not being installed properly.

Trying the miniconda route and getting stuck at the same issue with the "AttributeError: module 'menuinst' has no attribute 'instal| menuinst Exception" error.

At least two instances of the same problem probably means something, right?

**Comment by csoja** [comment]
@julianhemde  It looks like you've got conda-forge at the top of your conda channels and the packages installed are from conda-forge - this means that the packages are being built by the conda forge community and not by Anaconda.  https://conda-forge.org/  The error appears to be related to the post link script of the ipykernel-4.8.2-py36_0 package from conda forge.  You will want to raise your issue with them, or attempt to install the packages you need from defaults only. 

@xieliwei you've not provided sufficient information about your issue to determine the problem.  Typically, there is a template when a new issue is created - and this is the minimum amount of information needed to begin to diagnose what might be going wrong.  However, there are some tips in the documentation regarding issues installing anaconda, that may help you.  
https://docs.anaconda.com/anaconda/user-guide/troubleshooting/#windows-error-failed-to-create-anaconda-menus-or-failed-to-add-anaconda-to-the-system-path
