### ISSUE TITLE
An unexpected error occurred on Navigator start-up : 'root_prefix'

### ISSUE THREAD

**Issue by QingTianGG** [ContinuumIO/anaconda-issues#9963]
### Actual Behavior

```
Navigator Error

An unexpected error occurred on Navigator start-up

Report

Please report this issue in the anaconda issue tracker

Main Error

'root_prefix'
Traceback

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda2\lib\site-packages\anaconda_navigator\exceptions.py", line 75, in exception_handler
    return_value = func(*args, **kwargs)
  File "C:\ProgramData\Anaconda2\lib\site-packages\anaconda_navigator\app\start.py", line 150, in start_app
    window = run_app(splash)
  File "C:\ProgramData\Anaconda2\lib\site-packages\anaconda_navigator\app\start.py", line 65, in run_app
    window = MainWindow(splash=splash, tab_project=False)
  File "C:\ProgramData\Anaconda2\lib\site-packages\anaconda_navigator\widgets\main_window.py", line 163, in __init__
    self.api = AnacondaAPI()
  File "C:\ProgramData\Anaconda2\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 2185, in AnacondaAPI
    ANACONDA_API = _AnacondaAPI()
  File "C:\ProgramData\Anaconda2\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 89, in __init__
    self._conda_api = CondaAPI()
  File "C:\ProgramData\Anaconda2\lib\site-packages\anaconda_navigator\api\conda_api.py", line 1714, in CondaAPI
    CONDA_API = _CondaAPI()
  File "C:\ProgramData\Anaconda2\lib\site-packages\anaconda_navigator\api\conda_api.py", line 350, in __init__
    self.set_conda_prefix(info=get_conda_info())
  File "C:\ProgramData\Anaconda2\lib\site-packages\anaconda_navigator\api\conda_api.py", line 505, in set_conda_prefix
    self.ROOT_PREFIX = info['root_prefix']
KeyError: 'root_prefix'
```
##### Anaconda or Miniconda version:
Anaconda2-5.2.0-Windows-x86_64
##### Operating System:
Microsoft Windows [版本 6.1.7601]

##### `conda info`

```
     active environment : base
    active env location : C:\ProgramData\Anaconda2
            shell level : 1
       user config file : C:\Users\Administrator\.condarc
 populated config files :
          conda version : 4.5.10
    conda-build version : 3.13.0
         python version : 2.7.15.final.0
       base environment : C:\ProgramData\Anaconda2  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/win-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/win-64
                          https://repo.anaconda.com/pkgs/pro/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\ProgramData\Anaconda2\pkgs
                          C:\Users\Administrator\AppData\Local\conda\conda\pkgs
       envs directories : C:\ProgramData\Anaconda2\envs
                          C:\Users\Administrator\AppData\Local\conda\conda\envs
                          C:\Users\Administrator\.conda\envs
               platform : win-64
             user-agent : conda/4.5.10 requests/2.19.1 CPython/2.7.15 Windows/7
Windows/6.1.7601
          administrator : True
             netrc file : None
           offline mode : False
```
##### `conda info --json`
```
{
  "active_prefix": "C:\\ProgramData\\Anaconda2",
  "active_prefix_name": "base",
  "channels": [
    "https://repo.anaconda.com/pkgs/main/win-64",
    "https://repo.anaconda.com/pkgs/main/noarch",
    "https://repo.anaconda.com/pkgs/free/win-64",
    "https://repo.anaconda.com/pkgs/free/noarch",
    "https://repo.anaconda.com/pkgs/r/win-64",
    "https://repo.anaconda.com/pkgs/r/noarch",
    "https://repo.anaconda.com/pkgs/pro/win-64",
    "https://repo.anaconda.com/pkgs/pro/noarch",
    "https://repo.anaconda.com/pkgs/msys2/win-64",
    "https://repo.anaconda.com/pkgs/msys2/noarch"
  ],
  "conda_build_version": "3.12.1",
  "conda_env_version": "4.5.10",
  "conda_location": "C:\\ProgramData\\Anaconda2\\lib\\site-packages\\conda",
  "conda_prefix": "C:\\ProgramData\\Anaconda2",
  "conda_private": false,
  "conda_shlvl": 1,
  "conda_version": "4.5.10",
  "config_files": [],
  "default_prefix": "C:\\ProgramData\\Anaconda2",
  "env_vars": {
    "CIO_TEST": "<not set>",
    "CONDA_DEFAULT_ENV": "base",
    "CONDA_EXE": "C:\\ProgramData\\Anaconda2\\Scripts\\conda.exe",
    "CONDA_PREFIX": "C:\\ProgramData\\Anaconda2",
    "CONDA_PROMPT_MODIFIER": "(base) ",
    "CONDA_PYTHON_EXE": "C:\\ProgramData\\Anaconda2\\python.exe",
    "CONDA_ROOT": "C:\\ProgramData\\Anaconda2",
    "CONDA_SHLVL": "1",
    "HOMEPATH": "\\Users\\Administrator",
    "PATH": "C:\\ProgramData\\Anaconda2;C:\\ProgramData\\Anaconda2\\Library\\min
gw-w64\\bin;C:\\ProgramData\\Anaconda2\\Library\\usr\\bin;C:\\ProgramData\\Anaco
nda2\\Library\\bin;C:\\ProgramData\\Anaconda2\\Scripts;C:\\ProgramData\\Anaconda
2\\bin;D:\\Program Files (x86)\\SecureCRT_x86\\;C:\\ProgramData\\Oracle\\Java\\j
avapath;C:\\Windows\\system32;C:\\Windows;C:\\Windows\\System32\\Wbem;C:\\Window
s\\System32\\WindowsPowerShell\\v1.0\\;D:\\Program Files (x86)\\Microsoft SQL Se
rver\\100\\Tools\\Binn\\;D:\\Program Files\\Microsoft SQL Server\\100\\Tools\\Bi
nn\\;D:\\Program Files\\Microsoft SQL Server\\100\\DTS\\Binn\\;D:\\Program Files
 (x86)\\Microsoft SQL Server\\100\\Tools\\Binn\\VSShell\\Common7\\IDE\\;C:\\Prog
ram Files (x86)\\Microsoft Visual Studio 9.0\\Common7\\IDE\\PrivateAssemblies\\;
D:\\Program Files (x86)\\Microsoft SQL Server\\100\\DTS\\Binn\\;C:\\Program File
s (x86)\\Windows Kits\\8.1\\Windows Performance Toolkit\\;C:\\Program Files\\Mic
rosoft SQL Server\\110\\Tools\\Binn\\;C:\\Python27;C:\\Python27\\Scripts;C:\\Pro
gram Files\\Git\\cmd;C:\\Program Files\\Git\\usr\\bin;C:\\Program Files\\Git\\mi
ngw64\\bin;C:\\Program Files (x86)\\Common Files\\Thunder Network\\KanKan\\Codec
s;C:\\MinGW\\bin;C:\\Program Files\\Microsoft VS Code\\bin;C:\\Users\\Administra
tor\\AppData\\Local\\Programs\\Fiddler;E:\\0\u653b\u9632\u5de5\u5177\\11\u9006\u
5411\\apktool;C:\\Program Files\\Wireshark",
    "PSMODULEPATH": "C:\\Windows\\system32\\WindowsPowerShell\\v1.0\\Modules\\",

    "PYTHONIOENCODING": "936",
    "REQUESTS_CA_BUNDLE": "<not set>",
    "SSL_CERT_FILE": "<not set>"
  },
  "envs": [
    "C:\\ProgramData\\Anaconda2"
  ],
  "envs_dirs": [
    "C:\\ProgramData\\Anaconda2\\envs",
    "C:\\Users\\Administrator\\AppData\\Local\\conda\\conda\\envs",
    "C:\\Users\\Administrator\\.conda\\envs"
  ],
  "is_windows_admin": true,
  "netrc_file": null,
  "offline": false,
  "pkgs_dirs": [
    "C:\\ProgramData\\Anaconda2\\pkgs",
    "C:\\Users\\Administrator\\AppData\\Local\\conda\\conda\\pkgs"
  ],
  "platform": "win-64",
  "python_version": "2.7.15.final.0",
  "rc_path": "C:\\Users\\Administrator\\.condarc",
  "requests_version": "2.19.1",
  "root_prefix": "C:\\ProgramData\\Anaconda2",
  "root_writable": true,
  "site_dirs": [],
  "sys.executable": "C:\\ProgramData\\Anaconda2\\python.exe",
  "sys.prefix": "C:\\ProgramData\\Anaconda2",
  "sys.version": "2.7.15 |Anaconda custom (64-bit)| (default, May  1 2018, 18:37
:09) [MSC v.1500 64 bit (AMD64)]",
  "sys_rc_path": "C:\\ProgramData\\Anaconda2\\.condarc",
  "user_agent": "conda/4.5.10 requests/2.19.1 CPython/2.7.15 Windows/7 Windows/6
.1.7601",
  "user_rc_path": "C:\\Users\\Administrator\\.condarc"
}
```
##### `conda list --show-channel-urls`

```
# packages in environment at C:\ProgramData\Anaconda2:
#
# Name                    Version                   Build  Channel
_ipyw_jlab_nb_ext_conf    0.1.0                    py27_0    defaults
alabaster                 0.7.11                   py27_0    defaults
anaconda                  custom           py27h689e5c3_0    defaults
anaconda-client           1.7.1                    py27_0    defaults
anaconda-navigator        1.8.7                    py27_0    defaults
anaconda-project          0.8.2                    py27_0    defaults
appdirs                   1.4.3            py27h28b3542_0    defaults
asn1crypto                0.24.0                   py27_0    defaults
astroid                   1.6.5                    py27_0    defaults
astropy                   2.0.8            py27hc997a72_1    defaults
atomicwrites              1.1.5                    py27_0    defaults
attrs                     18.1.0                   py27_0    defaults
automat                   0.7.0                    py27_0    defaults
babel                     2.6.0                    py27_0    defaults
backports                 1.0                      py27_1    defaults
backports.functools_lru_cache 1.5                      py27_1    defaults
backports.shutil_get_terminal_size 1.0.0                    py27_2    defaults
backports.shutil_which    3.5.1                    py27_2    defaults
backports_abc             0.5              py27h0ec6b72_0    defaults
beautifulsoup4            4.6.3                    py27_0    defaults
bitarray                  0.8.3            py27h0c8e037_0    defaults
bkcharts                  0.2              py27h92b6de3_0    defaults
blas                      1.0                         mkl    defaults
blaze                     0.11.3                   py27_0    defaults
bleach                    2.1.3                    py27_0    defaults
blosc                     1.14.3               h95ae18b_0    defaults
bokeh                     0.13.0                   py27_0    defaults
boto                      2.49.0                   py27_0    defaults
bottleneck                1.2.1            py27hc997a72_1    defaults
bzip2                     1.0.6                h0c8e037_5    defaults
ca-certificates           2018.03.07                    0    defaults
cdecimal                  2.3              py27h0c8e037_3    defaults
certifi                   2018.8.13                py27_0    defaults
cffi                      1.11.5           py27hdb016f4_0    defaults
chardet                   3.0.4                    py27_1    defaults
click                     6.7              py27hb6defca_0    defaults
cloudpickle               0.5.3                    py27_0    defaults
clyent                    1.2.2                    py27_1    defaults
colorama                  0.3.9            py27hdfe4ae1_0    defaults
comtypes                  1.1.7                    py27_0    defaults
conda                     4.5.10                   py27_0    defaults
conda-build               3.13.0                   py27_0    defaults
conda-env                 2.6.0                         1    defaults
conda-verify              3.1.0                    py27_0    defaults
configparser              3.5.0            py27h2fa79a8_0    defaults
console_shortcut          0.1.1                         3    defaults
constantly                15.1.0           py27h28b3542_0    defaults
contextlib2               0.5.5            py27h42efda5_0    defaults
cryptography              2.3              py27hc64555f_0    defaults
cryptography-vectors      2.3                      py27_0    defaults
curl                      7.61.0               h7a46e7a_0    defaults
cycler                    0.10.0           py27h59acbbf_0    defaults
cython                    0.28.5           py27hc56fc5f_0    defaults
cytoolz                   0.9.0.1          py27h0c8e037_1    defaults
dask                      0.18.2                   py27_0    defaults
dask-core                 0.18.2                   py27_0    defaults
datashape                 0.5.4                    py27_1    defaults
decorator                 4.3.0                    py27_0    defaults
distributed               1.22.1                   py27_0    defaults
docutils                  0.14             py27h8652d09_0    defaults
entrypoints               0.2.3                    py27_2    defaults
enum34                    1.1.6                    py27_1    defaults
et_xmlfile                1.0.1            py27h1de5d23_0    defaults
fastcache                 1.0.2            py27h0c8e037_2    defaults
filelock                  3.0.4                    py27_0    defaults
flask                     1.0.2                    py27_1    defaults
flask-cors                3.0.6                    py27_0    defaults
freetype                  2.9.1                h4d385ea_1    defaults
funcsigs                  1.0.2            py27h8885ae1_0    defaults
functools32               3.2.3.2                  py27_1    defaults
future                    0.16.0                   py27_1    defaults
futures                   3.2.0                    py27_0    defaults
get_terminal_size         1.0.0                h38e98db_0    defaults
gevent                    1.3.5            py27h0c8e037_0    defaults
glob2                     0.6                      py27_0    defaults
greenlet                  0.4.14           py27h0c8e037_0    defaults
grin                      1.2.1                    py27_4    defaults
h5py                      2.8.0            py27h5f1a774_1    defaults
hdf5                      1.10.2               h4b43f98_1    defaults
heapdict                  1.0.0                    py27_2    defaults
html5lib                  1.0.1                    py27_0    defaults
hyperlink                 18.0.0                   py27_0    defaults
icc_rt                    2017.0.4             h97af966_0    defaults
icu                       58.2                 h2aa20d9_1    defaults
idna                      2.7                      py27_0    defaults
imageio                   2.3.0                    py27_0    defaults
imagesize                 1.0.0                    py27_0    defaults
incremental               17.5.0                   py27_0    defaults
intel-openmp              2018.0.3                      0    defaults
ipaddress                 1.0.22                   py27_0    defaults
ipykernel                 4.8.2                    py27_0    defaults
ipython                   5.8.0                    py27_0    defaults
ipython_genutils          0.2.0            py27hbe997df_0    defaults
ipywidgets                7.4.0                    py27_0    defaults
isort                     4.3.4                    py27_0    defaults
itsdangerous              0.24                     py27_1    defaults
jdcal                     1.4                      py27_0    defaults
jedi                      0.12.1                   py27_0    defaults
jinja2                    2.10                     py27_0    defaults
jpeg                      9b                   ha175dff_2    defaults
jsonschema                2.6.0            py27haaf3834_0    defaults
jupyter                   1.0.0                    py27_5    defaults
jupyter_client            5.2.3                    py27_0    defaults
jupyter_console           5.2.0                    py27_1    defaults
jupyter_core              4.4.0                    py27_0    defaults
jupyterlab                0.33.11                  py27_0    defaults
jupyterlab_launcher       0.11.2                   py27_0    defaults
keyring                   13.2.1                   py27_0    defaults
kiwisolver                1.0.1            py27hc56fc5f_0    defaults
lazy-object-proxy         1.3.1            py27h0c8e037_2    defaults
libcurl                   7.61.0               h7a46e7a_0    defaults
libiconv                  1.15                 hda2e4ec_7    defaults
libpng                    1.6.34               h325896a_0    defaults
libsodium                 1.0.16               h8b3e59e_0    defaults
libssh2                   1.8.0                h77a7533_4    defaults
libtiff                   4.0.9                h1c3b264_1    defaults
libxml2                   2.9.8                hdfd6920_1    defaults
libxslt                   1.1.32               h89dfad8_0    defaults
linecache2                1.0.0                    py27_0    defaults
llvmlite                  0.24.0           py27hc56fc5f_0    defaults
locket                    0.2.0            py27h1ca288a_1    defaults
lxml                      4.2.4            py27h31b8cb8_0    defaults
lzo                       2.10                 h0bb7fe3_2    defaults
m2w64-gcc-libgfortran     5.3.0                         6    defaults
m2w64-gcc-libs            5.3.0                         7    defaults
m2w64-gcc-libs-core       5.3.0                         7    defaults
m2w64-gmp                 6.1.0                         2    defaults
m2w64-libwinpthread-git   5.0.0.4634.697f757               2    defaults
markupsafe                1.0              py27h0c8e037_1    defaults
matplotlib                2.2.3            py27h263d877_0    defaults
mccabe                    0.6.1                    py27_1    defaults
menuinst                  1.4.14           py27h0c8e037_0    defaults
mistune                   0.8.3            py27h0c8e037_1    defaults
mkl                       2018.0.3                      1    defaults
mkl-service               1.1.2            py27h3f2f999_4    defaults
mkl_fft                   1.0.4            py27h31cbb53_1    defaults
more-itertools            4.3.0                    py27_0    defaults
mpmath                    1.0.0                    py27_2    defaults
msgpack-python            0.5.6            py27hdc96acc_1    defaults
msys2-conda-epoch         20160418                      1    defaults
multipledispatch          0.6.0                    py27_0    defaults
navigator-updater         0.2.1                    py27_0    defaults
nbconvert                 5.3.1                    py27_0    defaults
nbformat                  4.4.0            py27hf49b375_0    defaults
networkx                  2.1                      py27_0    defaults
nltk                      3.3.0                    py27_0    defaults
nose                      1.3.7                    py27_2    defaults
notebook                  5.6.0                    py27_0    defaults
numba                     0.39.0           py27h39f3610_0    defaults
numexpr                   2.6.7            py27h8d23284_0    defaults
numpy                     1.15.0           py27h911edcf_0    defaults
numpy-base                1.15.0           py27hfef472a_0    defaults
numpydoc                  0.8.0                    py27_0    defaults
odo                       0.5.1            py27h64810b2_0    defaults
olefile                   0.45.1                   py27_0    defaults
openpyxl                  2.5.5                    py27_0    defaults
openssl                   1.0.2p               h0c8e037_0    defaults
packaging                 17.1                     py27_0    defaults
pandas                    0.23.4           py27h39f3610_0    defaults
pandoc                    2.2.1                h1a437c5_0    defaults
pandocfilters             1.4.2                    py27_1    defaults
parso                     0.3.1                    py27_0    defaults
partd                     0.3.8            py27h1e0692f_0    defaults
path.py                   11.0.1                   py27_0    defaults
pathlib2                  2.3.2                    py27_0    defaults
patsy                     0.5.0                    py27_0    defaults
pep8                      1.7.1                    py27_0    defaults
pickleshare               0.7.4            py27hb5f6335_0    defaults
pillow                    5.2.0            py27h5b88493_0    defaults
pip                       10.0.1                   py27_0    defaults
pkginfo                   1.4.2                    py27_1    defaults
pluggy                    0.7.1                    py27_0    defaults
ply                       3.11                     py27_0    defaults
prometheus_client         0.3.1                    py27_0    defaults
prompt_toolkit            1.0.15           py27h3a8ec6a_0    defaults
psutil                    5.4.6            py27h0c8e037_0    defaults
py                        1.5.4                    py27_0    defaults
pyasn1                    0.4.4                    py27_0    defaults
pyasn1-modules            0.2.2                    py27_0    defaults
pycodestyle               2.4.0                    py27_0    defaults
pycosat                   0.6.3            py27h0c8e037_0    defaults
pycparser                 2.18                     py27_1    defaults
pycrypto                  2.6.1            py27h0c8e037_9    defaults
pycurl                    7.43.0.2         py27hc64555f_0    defaults
pyflakes                  2.0.0                    py27_0    defaults
pygments                  2.2.0            py27ha50f84f_0    defaults
pylint                    1.9.2                    py27_0    defaults
pyodbc                    4.0.23           py27hc56fc5f_0    defaults
pyopenssl                 18.0.0                   py27_0    defaults
pyparsing                 2.2.0                    py27_1    defaults
pyqt                      5.6.0            py27h6e61f57_6    defaults
pysocks                   1.6.8                    py27_0    defaults
pytables                  3.4.4            py27hdd5b532_0    defaults
pytest                    3.7.1                    py27_0    defaults
python                    2.7.15               he216670_0    defaults
python-dateutil           2.7.3                    py27_0    defaults
pytz                      2018.5                   py27_0    defaults
pywavelets                0.5.2            py27hc997a72_2    defaults
pywin32                   223              py27h0c8e037_1    defaults
pywinpty                  0.5.4                    py27_0    defaults
pyyaml                    3.13             py27h0c8e037_0    defaults
pyzmq                     17.1.2           py27h0c8e037_0    defaults
qt                        5.6.2            vc9hc26998b_12  [vc9]  defaults
qtawesome                 0.4.4            py27h766b13d_0    defaults
qtconsole                 4.4.0                    py27_0    defaults
qtpy                      1.4.2                    py27_1    defaults
requests                  2.19.1                   py27_0    defaults
rope                      0.11.0                   py27_0    defaults
ruamel_yaml               0.15.46          py27h0c8e037_0    defaults
scandir                   1.9.0            py27h0c8e037_0    defaults
scikit-image              0.14.0           py27hc56fc5f_1    defaults
scikit-learn              0.19.1           py27hbe35404_0    defaults
scipy                     1.1.0            py27ha6b90e7_0    defaults
seaborn                   0.9.0                    py27_0    defaults
send2trash                1.5.0                    py27_0    defaults
service_identity          17.0.0           py27h28b3542_0    defaults
setuptools                40.0.0                   py27_0    defaults
simplegeneric             0.8.1                    py27_2    defaults
singledispatch            3.4.0.3          py27h3f9d112_0    defaults
sip                       4.18.1           py27hc56fc5f_2    defaults
six                       1.11.0                   py27_1    defaults
snappy                    1.1.7                he46498f_3    defaults
snowballstemmer           1.2.1            py27h28d3bf7_0    defaults
sortedcollections         1.0.1                    py27_0    defaults
sortedcontainers          2.0.4                    py27_0    defaults
sphinx                    1.7.6                    py27_0    defaults
sphinxcontrib             1.0                      py27_1    defaults
sphinxcontrib-websupport  1.1.0                    py27_1    defaults
spyder                    3.3.1                    py27_1    defaults
spyder-kernels            0.2.6                    py27_0    defaults
sqlalchemy                1.2.10           py27h0c8e037_0    defaults
sqlite                    3.24.0               h7a46e7a_0    defaults
ssl_match_hostname        3.5.0.1                  py27_2    defaults
statsmodels               0.9.0            py27hc997a72_0    defaults
subprocess32              3.5.2            py27h0c8e037_0    defaults
sympy                     1.2                      py27_0    defaults
tblib                     1.3.2            py27h8ae915c_0    defaults
terminado                 0.8.1                    py27_1    defaults
testpath                  0.3.1            py27h1cd488d_0    defaults
tk                        8.6.7                h144d9c4_3    defaults
toolz                     0.9.0                    py27_0    defaults
tornado                   5.1              py27h0c8e037_0    defaults
traceback2                1.4.0                    py27_0    defaults
traitlets                 4.3.2            py27h1b1b3a5_0    defaults
twisted                   17.5.0                   py27_0    defaults
typing                    3.6.4                    py27_0    defaults
unicodecsv                0.14.1           py27h0bf7bb0_0    defaults
unittest2                 1.1.0                    py27_0    defaults
urllib3                   1.23                     py27_0    defaults
vc                        9                    h7299396_1    defaults
vs2008_runtime            9.00.30729.1         hfaea7d5_1    defaults
vs2015_runtime            15.5.2                        3    defaults
wcwidth                   0.1.7            py27hb1a0d82_0    defaults
webencodings              0.5.1                    py27_1    defaults
werkzeug                  0.14.1                   py27_0    defaults
wheel                     0.31.1                   py27_0    defaults
widgetsnbextension        3.4.0                    py27_0    defaults
win_inet_pton             1.0.1                    py27_1    defaults
win_unicode_console       0.5              py27hc037021_0    defaults
wincertstore              0.2              py27hf04cefb_0    defaults
winpty                    0.4.3                         4    defaults
wrapt                     1.10.11          py27h0c8e037_2    defaults
xlrd                      1.1.0                    py27_1    defaults
xlsxwriter                1.0.5                    py27_0    defaults
xlwings                   0.11.8                   py27_0    defaults
xlwt                      1.3.0            py27h2271735_0    defaults
yaml                      0.1.7                h3e6d941_2    defaults
zeromq                    4.2.5                h2880e7c_1    defaults
zict                      0.1.3                    py27_0    defaults
zlib                      1.2.11               hbc2faf4_2    defaults
zope                      1.0                      py27_0    defaults
zope.interface            4.5.0            py27h0c8e037_0    defaults
```

I have try update conda conda-build anaconda-navigator navigator-updater,and Anaconda-navigator --reset,but it still not working.can you help me fix it?

**Comment by goanpeca** [comment]
@QingTianGG please open the `Anaconda Prompt` and type

```
anaconda-navigator
```

What is the output?

**Comment by QingTianGG** [comment]
```
(base) C:\Users\Administrator>anaconda-navigator
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda2\lib\site-packages\anaconda_navigator\api\anacon
da_api.py", line 369, in _conda_info_processed
    processed_info = self._process_conda_info(info)
  File "C:\ProgramData\Anaconda2\lib\site-packages\anaconda_navigator\api\anacon
da_api.py", line 553, in _process_conda_info
    for env_dir in info['envs_dirs']:
KeyError: 'envs_dirs'
````

it appear a green icon and stop at adding featured channels...
then the Anaconda Prompt window print the error code

**Comment by QingTianGG** [comment]
According the key words “envs_dirs”, I find another issues [https://github.com/ContinuumIO/anaconda-issues/issues/9756](url)
it‘s problem is the $PATH variable Contains some Chinese characters.I have the same situation
.I remove Chinese characters from my $PATH variable.Then anaconda-navigator start-up successfully.
thanks for your help. @goanpeca
