### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by Pravdaray** [ContinuumIO/anaconda-issues#9964]
## Main error
Application <b>notebook</b> launch may have produced errors.
## Traceback
```
Traceback (most recent call last):
  File "/home/pravda/anaconda2/envs/tensorflow/bin/jupyter-notebook", line 7, in <module>
    from notebook.notebookapp import main
  File "/home/pravda/anaconda2/envs/tensorflow/lib/python2.7/site-packages/notebook/notebookapp.py", line 45, in <module>
    ioloop.install()
  File "/home/pravda/anaconda2/envs/tensorflow/lib/python2.7/site-packages/zmq/eventloop/ioloop.py", line 210, in install
    assert (not ioloop.IOLoop.initialized()) or \
AttributeError: type object 'IOLoop' has no attribute 'initialized'

```
## System information
```
platform: linux-64
version: 1.6.2
conda: 4.4.10
qt: 5.6.2
language: en_US
python: 2.7.14
os: Linux;4.15.0-30-generic;#32~16.04.1-Ubuntu SMP Thu Jul 26 20:25:39 UTC 2018;x86_64;x86_64
pyqt: 5.6.0
```

**Comment by goanpeca** [comment]
Please remember to update to the latest version of Navigator to include
the latest fixes.

Open a terminal (on Linux or Mac) or the Anaconda Command Prompt (on windows)
and type:

```
conda update conda
conda update --all
```
